### ISSUE TITLE
Add `always` value for triggers.disjunctive

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1004]
**Is your feature request related to a problem? Please describe.**

Sometimes, I want to create an aura which is always visible, but the trigger I am using does not have a "Show Always" option. Currently, the only way around this is to use "Any Triggers" and add a status - conditions - always active trigger, or to write a custom function which looks like:
```lua
function() 
	return true
end
```
Neither of these options is particularly intuitive, unless you have already been told how to do it.

**Describe the solution you'd like**

I would like for the "Required for Activation" drop-down to include an "Always Activate" option, which when selected, will cause the aura to always be active, so long as its load conditions are satisfied.

**Describe alternatives you've considered**

We could alternatively achieve this by including an option in *every* possible trigger (aside from possibly custom triggers, which are their own beast in this regard) which mimics the behavior in, for example, buff triggers, which allow you to change how the trigger activates. This might well be worth doing, but it would not have the degree of simplicity for the user which I think a new option in the disjunctive drop-down achieves.

**Comment by InfusOnWoW** [comment]
Right, renaming that to Activate is probably better.

Which triggers are missing a always active option though? I'd rather fix those, then add this.

**Comment by emptyrivers** [comment]
- All event triggers
	- Event triggers have the hide drop-down, which is ultimately useless. I'm not sure if there's anything to really be done with event triggers, though.
- Status triggers which don't have any way to always activate:
	- Action usable
	- Alternate Power
	- Bigwigs Timer
	- Cast
	- Conditions (partially, this is the source of the always active trigger after all)
	- Crowd Controlled
	- DBM Timer (maybe? I don't have DBM installed to check)
	- Equipment Set Equipped
	- Fishing Lure / Weapon Enchant (Old)
	- Global Cooldown
	- Item Count
	- Item Equipped
	- Item Set Equipped
	- Pet
	- Range Check
	- Spell Activation Overlay Glow
	- Spell Known
	- Stance/Form/Aura
	- Swing Timer
	- Talent Selected
	- Totem
- Status Triggers which can always activate, but do not advertise this:
	- Death Knight Rune (Show Always is there, but hidden? The UX here doesn't make sense)
	- Health (has a UI which makes it look like an event trigger, but the custom hide actually works properly. Usage is entirely unclear, however.)
	- Power (same as Health)
	- Threat Situation (same as Health)
	- Unit Characteristics (same UI as Health)

**Comment by emptyrivers** [comment]
If you really do prefer to go with fixing triggers, then I think that every trigger (except custom and *possibly* event) should include a drop-down along the lines of:

| Activate |
| ------- | 
| Always |
| When Requirements are Met |
| Custom |
| Other? |

**Comment by InfusOnWoW** [comment]
Well, lists the triggers where you want it, not all where there's not a option for it.

E.g. Alternate Power, Equipment Set Equippewd, Item Count, Pet, Range Check, Stance, Talent Selected are always shown by default.

**Comment by emptyrivers** [comment]
> I mean what do you expect the item count trigger to do if you configure no item count check?

Without any kind of explanation? No idea, whatsoever. *That's the point.* All of the triggers which you listed that are active by default, I had no idea that they did that. Because they don't advertise it. Why is it such a burden to change the UI so that it's both more consistent and explains what will happen more clearly?

> what's the original use case that would be fixed by this feature request?

Let's say I want to create an alert for a particular spell being cast in an encounter. That's pretty simple, the combat log event trigger does it for me. But I don't want the display to *appear* when the spell is cast. Instead, I want it to always be visible, but be faded slightly normally. When the spell is cast, I want it to glow, and attain full opacity.

There is *no* way to do this currently without either writing code, or by adding a bogus secondary trigger. Most users are uncomfortable with writing code, and without being told where the status - conditions - always active trigger is, I doubt that many users would think to look for it.

The solution I proposed is simply an alias for a custom activation which uses 

```lua
function()
  return true
end
```

as a trigger logic function. This would be a simple addition which satisfies any similar future use cases with minimal bloat, and would likely not confuse very many users (particularly if the verb in the trigger is changed to activate, and the verb in trigger logic is changed to show).

**Comment by emptyrivers** [comment]
(The real solution I would like is for the trigger logic to be removed entirely, and the aura's active status be controlled by conditions. But that's too big of a change, I think.)

**Comment by InfusOnWoW** [comment]
I have never seen any user be confussed about how the item count trigger works and when it'll show. It works the same way the power trigger works, and that's one of the most commonly used triggers, yet no one has ever been suprised that it shows always. 

So that point doesn't convince me, those triggers do not need a addition to explain what they do.

In fact it's the opposite, adding it adds confusion to those triggers, where you can select a "Show Always" option that behaves similar to the "Trigger 1" option.

And additionally you can combine "Show Always" and with a checks like e.g. Power > 50, which then won't work.

And for Cooldown Progress, that option clashes with the existing Show On option that does something different. Renaming that option does not improve that, it makes it worse. Now a familar name suddenly behaves differently.

That doesn't feel like progress to me.

And I agree that the visibility via conditions would be a more natural way to configure that, but that's not easy to achive at all. I don't know if there's a backwards compatible way to get there, and it would obviously require some work on how conditions work.

Extending the CLEU trigger to be always shown has its problems too. The model for event triggers is that they aren't always shown but are triggered on certain events.

**Comment by emptyrivers** [comment]
So, what specifically about event triggers is so unchangeable, that adding a show always option to the trigger or to trigger logic will break them? Perhaps that is something which can be improved.

Or do you disagree that the use case I described needs improvement?

**Comment by InfusOnWoW** [comment]
The short answer is that event triggers whole concept relies on events being their trigger/untrigger. (The concept for status trigger is subtle different, they recheck their status on events, and decide whether they should be shown atm.)

That concept for event triggers has to somehow evolve.  Buds has been going through all triggers checking how the hide mechanism actually works, and the current hide options for event triggers are a bit strange. (Although I know for a fact that e.g. the show/hide combination for chat triggers was used and did at some point work.)

So maybe the answer is that, the existing hide option for the CLEU trigger is rather stupid anyway, and that instead it should be replaced by a show option: "Show for x seconds" vs "Show Always". Is that something other event triggers would want to have too? Frankly no idea. Also there's no condition at the moment which would be usable to check if a event happened in the last x seconds.



For status trigger it's normal to have a always show option e.g. the Action Usable should ideally have that and a few others too. As an aside, adding such a option allows the trigger to give additional information. A trigger independent method means, a fallback state must be used, which won't contain e.g. the spell name/icon for e.g. Action Usable.

**Comment by emptyrivers** [comment]
It seems then that there's not much that is actionable in this request, that isn't already covered by #897.
