### ISSUE TITLE
Add "Alive" and "Mounted" Load Conditions

### ISSUE THREAD

**Issue by ShaunDreclin** [WeakAuras/WeakAuras2#1007]
I've had to add a superfluous `Conditions` trigger to almost all of my auras to check for being `Alive` and `Not Mounted`; it would be great if I could put these as `Load` conditions instead. Could these be added?

**Comment by ShaunDreclin** [comment]
Any particular reasoning?

**Comment by InfusOnWoW** [comment]
I agree with Stanzilla, those are imho too narrowly useful for load options. We only add load options for 
stuff that is typically not changing often. As all auras need to be checked on any load option changing.

Also you seem to copied the list from the Condition, instead of making a good argument for the options you need. E.g. I'd be curious to know what a load option "Always" does.

**Comment by ShaunDreclin** [comment]
I copied the list of missing options from the `Conditions` trigger because I figured it'd make more sense to add them all at once instead of having to go back and add more when somebody else comes along needing them. Personally I only want the `Mounted` and `Alive` conditions.

We already have a load condition for `In Vehicle`, so why not have one for `Mounted`? It's pretty common to not be actively fighting but still be `In Combat` because you ran past some mobs, and having all your combat auras pop up every time you run by mobs is pretty annoying. I would argue that your `Mounted` status changing is no more common than your `In Combat` status changing.

For the `Alive` condition, there are hardly any actions at all you can perform while dead, so again it doesn't really make sense to be showing auras for things like missing pets or buffs that you're unable to do anything about. And again, your `Alive` status definitely doesn't change more often than your `In Combat` status.

**Comment by emptyrivers** [comment]
That came out a bit harsher than I intended. But please do understand that your request looks pretty lazy when you ignore the template, and seem to include far more than is reasonable.

**Comment by InfusOnWoW** [comment]
So after the 8.1 release we had to fix a few regressions first.

We did discuss that for a bit and we don't feel adding Alive/Mounted adds much to the existing load options. We don't want to add every possible load option, and those just don't feel too useful to us.
