### ISSUE TITLE
Animations: Color not applying to Progress Bar

### ISSUE THREAD

**Issue by Kruithne** [WeakAuras/WeakAuras2#101]
Setting the 'Custom Function' for 'Color' under the 'Main' animation for a 'Progress Bar' to the following appears to have no effect.

```
function (p, r1, g1, b1, a1, r2, g2, b2, a2)
    local _, cl = UnitClass("party1");
    local colour = RAID_CLASS_COLORS[cl];
    print(colour);
    
    return colour.r, colour.g, colour.b, 1;
end
```

Changing the colour values to be an arbitrary value also achieves nothing. As far as I can tell, the function is not even being run, as the `print` call is never invoked.

**Comment by InfusOnWoW** [comment]
That works for eveyone else. I suspect you have no duration entered.

**Comment by Kruithne** [comment]
Which duration are you speaking of? I can't seem to locate that.

**Comment by InfusOnWoW** [comment]
Huh? I got a mail where you asked where the duration setting is.

In case you are still wondering, it's a bit above
