### ISSUE TITLE
Entire WeakAuras bugged in 8.1

### ISSUE THREAD

**Issue by neslin2** [WeakAuras/WeakAuras2#1011]
**Describe the bug**
All WeakAura's is loading together with and questmark icon

**Do you have an error log of what happened?**
Yes, here is the only error related to weakauras on BugSack: https://pastebin.com/tTCnzBEr

**To Reproduce**
Just logged and the bug was there, dont need to do nothing to the bug happen.

**Screenshots**
https://imgur.com/a/nNDhfBE

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, still with the same problem.

**Which version of WeakAuras are you using?**
2.10.3

**Was it working in a previous version? If yes, which was the last good one?**
Yes, the last good one was 2.10.2

**Additional context**
Here's the string that bugsack gives of WeakAuras, from what i see even don't understanding how it works it might be something with a dynamic group that i have for dungeons.
Heres the string link: https://pastebin.com/ksgiTrv6
And a SavedVariables of WeakAuras download: https://mega.nz/#F!y9Fzka6I!RLCyQFxZjeqjNrj0-Is2sw

**Comment by ragingpastry** [comment]
I am having these exact same symptoms.

**Comment by neslin2** [comment]
I noticed that in the BugSack string has one of my dungeon groups names as "8 - BfA Dungeons", so i got to weakauras.lua and removed every text lines related to" 8 - BfA Dungeons" and the ui actually came back to normal, strange AF. https://imgur.com/a/3xtmSpf

**Comment by emptyrivers** [comment]
We are pushing out a release to improve this momentarily.

**Comment by mrbuds** [comment]
i tested neslin2 SV, no problem for me
i counted 912 entries in WeakAurasSaved.displays
