### ISSUE TITLE
Script Ran too long

### ISSUE THREAD

**Issue by jakester55** [WeakAuras/WeakAuras2#1014]
**Describe the bug**

Weakauras are partially loading and cant see them in /wa
**Do you have an error log of what happened?**
 
1x WeakAuras\WeakAuras-2.10.4.lua:4252: script ran too long
WeakAuras\WeakAuras-2.10.4.lua:4252: in function <WeakAuras\WeakAuras.lua:4235>

Locals:
self = <unnamed> {
 0 = <userdata>
}
elapsed = 0.010000
start = 15871813.049253
hasData = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 addmany = <no value>
}
(for control) = "addmany"
name = "addmany"
func = <no value>
(*temporary) = <function> defined =[C]:-1
(*temporary) = false
(*temporary) = "WeakAuras\WeakAuras.lua:1669: script ran too long"
(*temporary) = "script ran too long"
debugprofilestop = <function> defined @TradeSkillMaster\Libs\AccurateTime\AccurateTime.lua:94
dynFrame = <table> {
 RemoveAction = <function> defined @WeakAuras\WeakAuras.lua:4223
 AddAction = <function> defined @WeakAuras\WeakAuras.lua:4210
 frame = <unnamed> {
 }
 update = <table> {
 }
 size = 1
}
debug = <function> defined @WeakAuras\WeakAuras.lua:295
debugstack = <function> defined =[C]:-1
----------------------------------------------------------------------------------------
1x WeakAuras\WeakAuras-2.10.4.lua:4252: ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1064: attempt to index field '?' (a nil value)
[C]: in function `assert'
WeakAuras\WeakAuras-2.10.4.lua:4252: in function <WeakAuras\WeakAuras.lua:4235>

Locals:
(*temporary) = false
(*temporary) = "...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1064: attempt to index field '?' (a nil value)"

**To Reproduce**
 

**Screenshots**

https://gyazo.com/d0a5eb05173b6164a336fa387ffa8701

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** Disabled elvui and it worked but gave me 10 errors with language
https://gyazo.com/5d9b641c0c15b20d99a96fbf1c30d65a

**Which version of WeakAuras are you using?** WeakAuras 2.10.4

**Was it working in a previous version? If yes, which was the last good one?** Yes

**Additional context**

``` HERE ```

**Comment by mrbuds** [comment]
can you include your weakauras.lua from savedvariables?

**Comment by jakester55** [comment]
https://pastebin.com/CM690gPJ

I think thats it

**Comment by jakester55** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/2670316/WeakAuras.zip)

Here is the zipped file

**Comment by mrbuds** [comment]
ty

**Comment by mrbuds** [comment]
i can reproduce with your huge 9mb SV ty

**Comment by jakester55** [comment]
what do i need to do now?

**Comment by mrbuds** [comment]
we are working on fixing that

**Comment by InfusOnWoW** [comment]
The new 2.10.5 should fix it.
