### ISSUE TITLE
WeakAuras using massive amount of Memory

### ISSUE THREAD

**Issue by Rubeek** [WeakAuras/WeakAuras2#1016]
**Describe the bug**
First time logging in after 8.1 I noticed my load screen was enormous and my FPS incredibly low, turns out WeakAuras was using ~3500MB AddonMemory. Even if every WeakAura is set to 'Load: Never' it persists. After deleting the WeakAuras SavedVariables and having 0 Auras, the AddonMemory is sitting between 400-700MB.

**Do you have an error log of what happened?**
The only lua errors I seem to get is if i type /wa shortly after logging in:
1: https://pastebin.com/KG87jk8e
2: https://pastebin.com/tpYX5S5z

**To Reproduce**

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
2.10.5

**Was it working in a previous version? If yes, which was the last good one?**
I have only tested 2.10.5 with the 8.1 patch.

**Additional context**
After a long login period the game seems to be stable, just slightly lower FPS than expected and absurd memory usage. If i mouseover the Game Menu to view AddonMemory my game turns into a slide show at about 2 FPS.

**Comment by DonnieErgo** [comment]
Same issue.

**Comment by InfusOnWoW** [comment]
This should be fixed with the 2.10.6 release that we just released.
