### ISSUE TITLE
[2.10.5] Custom code in Actions-Oninit is not run when logging in

### ISSUE THREAD

**Issue by wing5wong** [WeakAuras/WeakAuras2#1017]
**Describe the bug**
Prior to 2.10.5 the bar loaded properly. since 2.10.5 the bar does not laod properly until opening the code editor and hitting done. see image https://imgur.com/a/QELE1YW

**Do you have an error log of what happened?**
No errors

**To Reproduce**
use this aura https://wago.io/ByIpnHAk4
logout, login - bar is green/yellow.
edit aura:  actions>onit - expand editor - done.
bar is now purple as expected

**Screenshots**
see first area

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Not yet sorry as its raid time, the temporary fix is enough for now. others have confirmed the issue

**Which version of WeakAuras are you using?**
2.10.5

**Was it working in a previous version? If yes, which was the last good one?**
2.10.4

**Additional context**
https://wago.io/ByIpnHAk4

**Comment by wing5wong** [comment]
may be better to use the collection - https://wago.io/SJSy9mKVm
i notice the issue immediately with the AP bar there

**Comment by emptyrivers** [comment]
Does this problem persist in 2.10.6?

**Comment by Alex-Miller** [comment]
Yes. And not only on init code isnt executed after relog/reload.
trigger-always active-every frame also is not running until you expand and close editor.
example: aura1 and aura2 are not shown. expand editor in one aura,close and both will work as usual

**Comment by InfusOnWoW** [comment]
That should be fixed in 2.10.8
