### ISSUE TITLE
[2.10.5] FPS drop from 60 to 30 upon addon activation

### ISSUE THREAD

**Issue by YGrancharov** [WeakAuras/WeakAuras2#1018]
**Describe the bug**
I updated the addon once the addon became available. Upon starting the game, my fps dropped from 60 to 30. I was turning addons on and off to narrow down the cause and it turned out it is WA2.

It is not a hardware issue for sure, my machine has i5 650016gb ram,  GTX 1060 6gb

**Do you have an error log of what happened?**
No

**To Reproduce**
Updated from 2.10.2 to 2.10.5 and the issue was present.

**Screenshots**
Not needed

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did. I left WeakAuras as the only addon enabled and I got the fps drop.

**Which version of WeakAuras are you using?**
2.10.5

**Was it working in a previous version? If yes, which was the last good one?**
2.10.2

**Additional context**
I removed all my auras and kept the addon only - still happening.

**Comment by emptyrivers** [comment]
2.10.5 is not the latest version of WeakAuras.

**Comment by YGrancharov** [comment]
Fixed in 2.10.6
