### ISSUE TITLE
[8.1] Can't send aura to guild chat

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#1025]
**Describe the bug**
I expected to send an aura to my guild, but it only send the text.

**To Reproduce**
 
1. Type /wa
2. Press enter and type /g
3. Shift-click on an aura
4. Press enter

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes.

**Which version of WeakAuras are you using?**

2.10.8

**Was it working in a previous version? If yes, which was the last good one?**

Was working before 8.1.

**Additional context**

Blizzard removed some communities and guild api.

**Comment by emptyrivers** [comment]
This is unfortunately a breaking change from blizzard, and there doesn’t seem to be a workaround currently. I’ll keep this open for now in case we learn something new.

**Comment by InfusOnWoW** [comment]
Fixed the immediate problems and added a message when pasting a aura into guild chat.

While we could add guild-wide sharing system, I don't think that's needed atm.

**Comment by Vardex** [comment]
Access to guild chat messages is now possible again.
