### ISSUE TITLE
[8.1] Icon Display with Multi-Target Debuff Trigger for total dots not resetting on death

### ISSUE THREAD

**Issue by ryanschmitty** [WeakAuras/WeakAuras2#1028]
**Describe the bug**

My Icon Display using a single Multi-Target Debuff Trigger to look for moonfire (or sunfire or both) does not reset upon death (e.g. on a raid boss). I expect it to reset to 0 after I die.

**Do you have an error log of what happened?**
 
No errors reported via bug sack (and I got some earlier so I know it's working).

**To Reproduce**
 

1. Create an icon display with text tracking total unit's debuffed (%unitCount)
2. Add an aura trigger for multi-target debuff, own-only, unit count > 0 (I used moonfire and/or sunfire as a druid)
3. die while the icon displays the %unitCount and it's > 0
4. observe it doesn't reset the %unitCount

**Screenshots**

n/a

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, same issue.

**Which version of WeakAuras are you using?**

2.10.9-1-g0510588

**Was it working in a previous version? If yes, which was the last good one?**

Not tried on older version.

**Additional context**

``` HERE ```

!nwv3Ujpoq0NM9Y(jcf6c3SsuA4RirdDJd7LMAsMKyvJDuSdu6f9zFNXjbOvA1IekXCS9zM5m)eEapHZK8OG7FyW0h4mlNn8xbd(107cURyW4GbJNmHZ2Zzz0p8So4d3WxnsTJZMhgLeg3IfSWODm5NaY1iol1Om145Jc8)g6FEV)5i6jE7tRZZTGd3CmNj0PLM6FWBQXOYmh1SJYkG)ic0yDM9jO52uLjCaN109U)OHzfaFhgsPgnDdxTSOaQTTUsYzaAPT0CCUYOblDd3j0gmrtTyy7lTyp0Dp2lgJoxwdKFxuBAQ2MAA0U1vqTWHbk7V4m06R1QtKvHdafhpdcLRKZ6zcHSn78B(AnKl)GZyVgUA1fywtUhE78zSKTSKzXKFwbk1YSogA0s85(gLt(nFHZgGBAHFFf0JEKi080YmyhsFIpoFEw8ll2SQLWlAIJaePo5biPf8ftgMsVlyaTJprhQf7uqgX47aundDVuxSWjnKmk0Y90ATxHDIANx19gvJAn6gO2shyBlOfWufgCuqjK6B)05sT0wEZNV39NJ1POD27ZqR3KWw(uikKkSw4)VM1ZqxvA8YF)CFdbv8VqjkSEkxTmcPSeKfLy5Da2aPmcF3dMn2MQewBxQzBf42jCoLVOLai1SFZdqPmvbBK9B2bq)TLfsJL6ceI9u8MLp1xy0Lj9KD5muL833N6xt(oib7KPVF6PoLSZ4xuiQ9s7GATq9pyRfDKOPDcX3u3Lrxe32YUDnoNrV(auReNUAWbNTOw(5xV93nIm0QIVEljH6cD4qH1vKx0x9lXbrJSP5poD6hLXZUIJFQ)1qbEVw76hhW(OBIZIXJcMC)KhMmE6WHtd(ZX887gDEi0IASFP9AS5XHHrxLJBhWnCuhuFRWUZr)TvbXz)b1gpVTVLKNZu8FRg(TXBw5fgdvK8PXSNhH99KQKyCc1xVTVFuflNceCGhYGp1luvLTRokZW5s(kZ(bN0q1R6StjskA1CPgZxwO3fdUHOKgH0MZopdWtKSB15ExF9g1IkVkjBbv(p(uqgyfoQGKCde)a9zMHKT4)7

**Comment by ryanschmitty** [comment]
It's possible they just last longer than I expected. They might go away once the mobs actually respawn in the boss room (I was on g'huun)

**Comment by emptyrivers** [comment]
Due to limitations in the API, it is not possible to reliably detect the removal of a debuff from arbitrary units due to death. Multi-target clones will destroy themselves after a minute if they are not updated, but there's not much we can do to improve this.
