### ISSUE TITLE
Improvement suggestion: Allow modifying progress bar BG via custom animation function

### ISSUE THREAD

**Issue by rnyberg** [WeakAuras/WeakAuras2#103]
Would be nice if we could modify progress bar BG the same way we can modify the FG via custom animation color function.

**Comment by InfusOnWoW** [comment]
That's actually hard to do, the set of animation functions is the same for all regions.

**Comment by rnyberg** [comment]
Is there any global variable we could override to make a feasible workaround?

**Comment by InfusOnWoW** [comment]
the feasiable workaround is to have two bars, and have the second bar always full.

**Comment by rnyberg** [comment]
I guess so, sure.
