### ISSUE TITLE
PixelUtil

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1035]
Placeholder for tomorrow

**Comment by Stanzilla** [comment]
Sort of, my plan was to test replacing all SetPoint calls in RegionTypes with WeakAuras.SetPoint and route that to PixelUtil.SetPoint and I did that locally but I could not see any change so I have no posted anything.

*If* that resulted in an improvement, my idea would have been to do just that and/or offer an option to toggle `pixel perfect` positioning on the region and offer that as a default in https://github.com/WeakAuras/WeakAuras2/issues/983

**Comment by InfusOnWoW** [comment]
I don't think PixelUtil helps us in any way. People will expect a aura positioned at x: 100 and x: 101 to be one pixel apart. And the only way to do that, is to scale the coordinate system so that the virtual and physical coordinate systems match.

**Comment by emptyrivers** [comment]
So, it looks like nothing interesting will come of PixelUtil, so I’m closing this ticket, since we already have a ticket open about pixel perfection.
