### ISSUE TITLE
Additional Feature Request

### ISSUE THREAD

**Issue by Zevade** [WeakAuras/WeakAuras2#104]
Hey, I noticed that WeakAuras does not have an option where you can have a different cooldown indicator for charge based abilities.

For example, here is what I currently see with a WeakAura charged based cooldown:
http://puu.sh/reGm3/a30dd5f334.jpg

And this is what I would like to see (This was taken from my action bars.):
http://puu.sh/reGsa/b910ccda5a.jpg

It's a subtle "sonar" line that would show if stacks are greater than or equal to 1, and less than the max stacks. (Black clock cooldown would show at 0 charges and no cooldown box at max stacks, obviously.)

Hopefully this sounds like a feature that you would be willing to add. =)

**Comment by rnyberg** [comment]
It's easy to add as custom text already though.

**Comment by InfusOnWoW** [comment]
I'm not sure what you are asking for. I see no sonar line in the second screenshot.
