### ISSUE TITLE
Collapsable Options: Make headers clickable

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1047]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 
I can only click the chevron instead of the whole header

**Describe the solution you'd like**
The header text should be clickable as well

**Describe alternatives you've considered**
None

**Additional context**
Rivers is a meep meep

**Comment by emptyrivers** [comment]
This is \*difficult\* with our current framework. We could do it if we started making use of AceGUI more directly. But outside of that I don't see this happening ever.

**Comment by emptyrivers** [comment]
Well, actually it wouldn't be difficult, just it would look like this: 
![image](https://user-images.githubusercontent.com/24878501/50529583-8fd87300-0abb-11e9-8a17-fa2f72a8288d.png)

Which I think is kind of ugly.

**Comment by InfusOnWoW** [comment]
I'll propose a patch for AceConfig that would make it possible to make it non ugly. And argueably it's exactly fits AceConfigs existing code, that means it has a some chance of getting in.

**Comment by InfusOnWoW** [comment]
I've suggested this patch to AceConfig to nevcariel:
https://pastebin.com/UtSu24UA

Let's see what he says.

**Comment by InfusOnWoW** [comment]
And that suggestion was ignored, so can't do unless we fork AceOptions

**Comment by Stanzilla** [comment]
Opened a ticket https://www.wowace.com/projects/ace3/issues/475

**Comment by emptyrivers** [comment]
That ticket has no response yet. Is this just how slow nevcariel is at responding to tickets?

**Comment by Stanzilla** [comment]
Yeah is also currently not playing the game so interest is low.

**Comment by InfusOnWoW** [comment]
You can reopen it, when that issue gets any movement....

**Comment by emptyrivers** [comment]
That patch has now been implemented, so we can now actually make some progress.

**Comment by emptyrivers** [comment]
*(1 month later, still haven't gotten around to looking at the new patch)*
