### ISSUE TITLE
Idea: On init - [WA] - You have xx auras using legacy aura trigger, type /wa bt2 for more information

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1049]
**Is your feature request related to a problem? Please describe.**
BuffTrigger2 migration was not done automatically, and i think a considerable amount of users have no clue about it, and their fps still suffer from legacy aura trigger.

When someone have performance issues on discord i redirect them to https://wago.io/UpgradeBT2
I wish someting like this was included in the addon (until next expansion ?) with more feature

**Describe the solution you'd like**
On init, show a warning in chat telling how much auras still needs to be upgraded like this :
`[WA] - You have xx auras using legacy aura trigger that can have a bad impact on your framerate, type /wa bt2 for more information`

And bt2 command would then open a window, like the one we use for profiling result, showing : 
- some text or links explaining what is BT2
- real time list of auras that needs fixing
- a convert button in the list next to each aura (not limited to 1st trigger)

**Describe alternatives you've considered**
With the future tagging system, auto tag auras that needs upgrading

**Comment by Stanzilla** [comment]
Not opposed

**Comment by emptyrivers** [comment]
+1

**Comment by emptyrivers** [comment]
This is now implemented in the latest alpha! (though not quite as this ticket suggests, see the pull request for more information)

**Comment by mrbuds** [comment]
ok thx
