### ISSUE TITLE
Idea: Addon's version update check

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1050]
**Is your feature request related to a problem? Please describe.**
It's common to see people coming on discord with issues that can be fixed by upgrading their weakauras version.

**Describe the solution you'd like**
Show a message once per session when a newer version is detected, like details or bigwigs do.

**Comment by emptyrivers** [comment]
I always found those kinds of update nags to be obnoxious.

-1

**Comment by Stanzilla** [comment]
Currently opposed as well, mainly because of the overhead of a addon msg channel, other ways to communicate it could be found, like coloring the version in the header in a different color or make it blink.

**Comment by InfusOnWoW** [comment]
Same, also not very keen on having that.
