### ISSUE TITLE
Custom Options + custom trigger on FRAME_UPDATE = excessive garbage collection

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1057]
**Describe the bug**
WeakAuras memory reported by the "?" tooltip increase by 0.1mb every second using the following aura

If i set load condition to never and /reload, the memory increase of weakauras is much slower.
If i keep it loaded and delete every custom options, weakauras memory increase like the aura is not loaded.

```!TEvBZPnoq4)l9(Y1zUJqEP96DZ0paeY0MJa0itZCFXyzBzqxmsEKLjK8b)B)2DLSX5TozUYaJrwA1U7ZZUA1s4XHbHSnHSu8lmuxzZLkriB2IGjFD64qwMwzzYheHtp(KqwIoxBabNEm99e65P0ZZWNwqpYYIC(9bIDWl1rHS7NLLvkSHt7hY4QK1AZCTubloA80GXxhY21raJyLuRcUVa8blPcELf2YSclmFPZ0GJENm1UghZSKSLICrcADrgVk3sRCR4EaC6uy5QsX5IYKWHHST88kHxrm2A9D1r3TwMlQJkmIYsrkcl2qGgUfxrO2VaOFfFdOUZDySo6ks7POQzJaMYOZlPDzxlm1r6TcdjNeMTeSLQ1yGa1rXvwRw5w2BeytWgJrZdtgBKISCqb8mlQqsiWpax8TqcN8e4ocdFGTbITYiAa6dpWnGD)fkuYgvvA1BqS2H0iQSzBEsywd4cAM)58a32AnyGUoc0zDuMEp3GG5uemoiy1RwLl8geeM84Ui1z7fOA8R1XnBaE8piM06fjoYORZSNASycDRx5s7DovYl7rVUZ8JpT8e307u6SN7tqAcmRqXJZPCXPFyVdkvfvpoI59VtA9pkS2gSQJMZH192hh7yMeVypYMpns7ZNfw3E8zmE6HEPnLixOwr8u)9ecJC0jUvIrK8X9irvTjw8yICdFhr0LwrbuKOx)JBHx)EFawxQOAhoGorK19iq)MK3Dnl4iCTjvQ4wrPJSPJJ5GeadNUs4M8NGmal)hhqqDTC16xQ6MDx7kVoSmOihoC9PdcU8UFGU4XblhE9t)6yYQloCi6ppGrQHAlDy4fcv7x61XvmjZHdAW5UGMBsBLnPRPP6F)mh7DehckJKULUttdSnIuz1MoLJSyvV9fjwuKcUbW3n)AYdzRT2IY)6OJUJVs3tQpYClxFYhl6)TJGYz8KMobGic3G1xbnMjvYY1UXWqCwVvGMqUS(sWb1l9te7CclCUyLWSVNc)eDk77vqzvSyRaGuvwMCxiB5ObSGLSGbxhGapgM21XYxgpz(flMeYiXH3f8CSkBf6rmSLbm3YP2LoB4LetEkDUFJvZQueu)vsKFRxVEVhqsK7dDvaoFD0N)CD07U46bxnE5I5Npiy87OCj1EHB(yeqyeA3iJNdxa2USqLwFj94))hGhUhWGm58kdNscI9yRmK115a2SqKN)1upAB425gbXTS5JNmPLJwlX(RSYnUUVQu7Jrumetg2kcCtsnJn93HuEkHyNi9gFwx)(ywb0bLIN)DiKJ(hDL0)cMrMbNoNm(IaQbQmFZPdNfem7kyBqRXdxaJNwhDZGGrFb7yf6jvVbGzIZaSbW7GjnqqeYI4woDS31S7f4SU0d2ORhpEkCyao(DJHdL4UPDuIwLjxr5EUBQWskDB3UFVZOwiOFp1)BtBen3dq9c2P7UNCBCNwQg6BnM2bvggnyBrkNA365kgEUtj34ISDo5Xs9H7LnDGc4acTnvt1kSvkOeQu92LU9S8BtEmVaJs)97pNPho4F(u23j6mv2uOaKixZP)GdK8Lq)NhO2SSjlkjNxw(SzbQAPcYnnyQCjwn7jsyDf6G8BJ8H6OVvXtXypuV0Lzd)pbXwGebY8Stq(m8)o```

**Do you have an error log of what happened?**
 

**To Reproduce**
1. import the aura and watch weakauras memory
2. unload it and watch weakauras memory
3. load id and remove all custom options and ..

**Screenshots**
with empty SV and after disabling a few addon (i dont use any skinning addon)

with only the aura i gave string loaded:
![preview](https://i.imgur.com/X4nmVWd.gif)

after removing all custom options:
![preview](https://i.imgur.com/uJWi6Tc.gif)

**Comment by emptyrivers** [comment]
already fixed in #1055

**Comment by mrbuds** [comment]
doh

**Comment by mrbuds** [comment]
indeed it fixes the problem
