### ISSUE TITLE
Fire mage rune of power "Action usable" trigger does not take into account rune CD

### ISSUE THREAD

**Issue by EKanadily** [WeakAuras/WeakAuras2#1060]
**What steps will reproduce the problem?**
make a trigger to track fire mage rune of power spell Action usable. 
At the beginning of the fight rune of power has 2 charges and the "action usable" trigger is ON . if you cast rune of power the usable trigger stays ON despite the fact that the ability is not usable for 10 seconds after casting it due to rune CD.

in other words there is no means to track "rune CD" regardless of the checkbox that says ignore rune CD.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes with the same result

**Which version of WeakAuras are you using?**
2.10.11

**Was it working in a previous version? If yes, which was the last good one?**
no

**Do you have an error log of what happened?** 
no error ,just a bug report.

**Please provide any additional information below:**

**In case you do know which aura is problematic, please export the string and paste it below.**

!nwvtZjooq0Fn7H9Wmf2HVMJegZmuvIHfz2JkiSKT1ocjx2YHKCGF7B3sYadBQAPkkBrRwD)071DBAenJsK00Xd(20OruslLe)1ObFnkIsoqjC8h4Hv8MnETrQTuY8K0SKnEBrlmAlr(HGMgftjVVQOOvyPlgfpzY4rrJIggn(H4bdOfFzieDMoVY0CtCYngf3CutokRf09GHUwR5qge(T1CMvqjDH39UMWlDEkZnA6JauAKLLIMwaQPUBuWGB57qujTwMTdUCCX(UIImNTFM806fBFc2SBV4vbCrGTKVrjVmFgj7fs2SnW51SdcmWaI5DnmResjbyh3jOKz5OLt722Y2RqOQLG1Af7Di9KgbtrQfkvkefkztNwCANP40U1MJ4(DTIxApVpCtC)zjpKWEGTUr4agzDYtaElfArJmNuzoUcatR798a3GqiGnwN14ZXVFI(84sAAu04bGCBXdEH3SObgC5EvK5n(SHdE)LOboKjufFw9qIgPboko)siQNb5j3Ubzn0etlp4zWmNK0yXf906lbPsaQkWabLtB0cmJhys997DHulBRUB)TyTLUqwg4DRm)xV)9E5gqEPYCCUrzA8Ly4Vy3ZhCphIpTboiWlpUklB1ZBw(JF23aHnlluSsi7R2M90Y0ekPsilRSq0g4GaxIzmi)kdZ19HkyUI126uoSBdmEOtzL9cLLPqfhzvPUeQdt)2nEGcX17hFZ((4FXbYZZ(rYn(eQwZryGRdz9X(sfpWplSxldWAj2z0J3E6Gsw0i)40U)QJXb2MDAxgoqsBfnAM6VHEAuasHIo)zMdNbkeo4QVxMsw(9eV44BP33zTg9QxfnqdyqoUdz7T(5wtgpDYKPJM(W4OPpmAumo3AifMmXTvEn68uVBfYgrjavpmCZLifnq)fmkcUwyEa59UQFIVmtngYntvx5p)5u)5KMBBk5pA9ecw1(HXCGM2ZDWE1HHc7ptN)VqsY)pZToTRlmTJlAH5Qn4W5(qE1ea)4(fin45fY8njjPomaBSQ(QA9omp83Ih)p11vB38NyraiJTIqX2LgW9x(oa(nI(8bUXLT4G3Lo2)yL86pz0JVOpRccw9kCDhgJ3y6)(d

**Comment by emptyrivers** [comment]
By the way, the `ignore tune cd` option refers to Death Knight Runes, which tend to put every skill on cool down. Not the mage Rune of Power.

**Comment by InfusOnWoW** [comment]
Rune of Power seems to be a special case, which we'll handle better with the next release.

**Comment by EKanadily** [comment]
thanks
