### ISSUE TITLE
Add "Mirror" property setting, to Conditions, for Texture and Progress Texture

### ISSUE THREAD

**Issue by anaseskyrider** [WeakAuras/WeakAuras2#1063]
In my attempts to make my own version of the Demonology Warlock's Demonic Core power aura proc, using a TSU instead of two separate weak auras for the left and right side of the spell activation overlay, I've learned that WA doesn't natively support forcing a texture to be mirrored. My attempts to do so end up with the texture only being mirrored for a split-second before returning to its original appearance.

My request is to add the ability to control a texture's mirror state, using Conditions. Asakawa has informed me that this would likely result in the addition of a function which is usable in custom code, something that I don't need at this time but which I would like to see.

**Comment by InfusOnWoW** [comment]
This is now implemented for the next release.
