### ISSUE TITLE
Armor Trigger

### ISSUE THREAD

**Issue by Zed-Wick** [WeakAuras/WeakAuras2#1065]
**Is your feature request related to a problem? Please describe.**
Not really to a problem, but could make life easier. Personally I don't like the Armor Man and i'd rather just have an alert.

**Describe the solution you'd like**
New trigger to detect when armor durability (of a certain slot or just in general) lowers below (x) durability.

ex. Armor Durability is 100
Weakaura Detects for x>75
Armor Durability is 70
Weakaura will display whatever you want, be it an icon/sound played.

**Describe alternatives you've considered**
Using default armor man that comes with the base game.

**Comment by emptyrivers** [comment]
This isn’t a bad request actually, but in case we decide not to implement it here is a custom script that I wrote for just this purpose a few years ago: https://wago.io/EyobZ1hsf

**Comment by InfusOnWoW** [comment]
I don't think we would ever want to have such minor utility as a whole separate trigger. So in that sense it is out of scope.

But, it would probably fit right into the scope tracked in: https://github.com/WeakAuras/WeakAuras2/issues/386 So I have made a note at that trigger to consider Armor too.

Although that's not a priority for anyone on the team as can be seen by the length that ticket has been open.

**Comment by InfusOnWoW** [comment]
We briefly discussed this after Buds did fix #386, and it seems no one thinks this would be useful enough to make a default trigger.
