### ISSUE TITLE
switching quickly between certain tabs causes certain parts of conditions to hide/deface

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1067]
**Describe the bug**
i expected all specified settings of the condition's tab to show but instead the operator and the specified value was hidden when switching fast between tabs

wwhen switching from load to condition tab it instead defaces stuff

**Do you have an error log of what happened?**
no error

**To Reproduce**
1. import wa below
2. switch quickly between custom options and conditions until operator and specified value hides
3. (optional) switching between load and condition tab seems to cause it too. can't reproduce it with all tabs though
--> 

**Screenshots**
https://i.gyazo.com/113a6a905b8b7cce7242be3e6605b533.gif
https://i.gyazo.com/9970f0107cd1b46060cccdb739475682.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes, same result

**Which version of WeakAuras are you using?**
2.10.11

**Additional context**

``` !nVrdtjUsYFlhv9QNELIqae8QARRqe)6POhb39E3QbhtgG5mKHljORV3943(1Dpt(e1LG6BVIDXWKz6P7E6VMP7XQQ1alZPwMo4)Ghh7kF06olZq(3cREO0l0u8BCREv31Y0wkDDKp6naEvxp2DUChR9HHjcM5YEcB1YmyeBeZzKtWilZNUy0OaEOvVkwMmp7js)lLcpOtD62Bq3(wMZ9DTmNegol4VTZopYglllK7C3iMpt4ySZUgwMcBPhohi2yGyJLzBFbZDXT9y((aMAEpNpRDWmUDyFwOqIO(JsFNV4ZMzz(L4NC4bSW5(SqocoKi7iDL(af3Rk9pd67A031XVd18anoV)fdgCX5PWKdDzJdSmV4QbNDsVUwMUsgXadq(fYtN7gkGhcri5lD5Qx6ngEYCq7E)c2(8a(qp(dCFeVrQyPrI9GgnG22USGGL6b3Zwo3lK7lG1qdJDRTf8vd8RDXVAbF1Sk(Lb(f2wRk4xyBTQJF1qnnPb0(iKr20GNMb47DZddLExaikSsNs4iptWNpwi9uJHw7s4xk5iJg6MSm)jyGS5HY413uYuWqhjgJKQrRM7TxTaxHdWKqjjaNBuFxStgT2B392t)KXEgQNASx9gz6o2G(vTAwx)u190TvREfniW5jbSzbrRMnWviv3D8LZq9aukbFzLkvY27DBwv1BJk1Ag9Q6rZ7s0sc8mOPOrZS0Rr961tOYCZEZg72ixty)ZaaeIrcyIrcUJjSo7q9Mt88KFB0Qv1gASVERAvvZRrLw1IEQwtnleiBnJdqbLaZiX34oFr4eobOf41aCdDfE8usi2FF1o75bHYPk7jjwDmFumtPfe)6RM5Gk0MZ1)fLMMcwbSvOGzBu6Ym0xmEm3pqnPdIBGEKKuvqm6VFMbwyaMciE(7loDXTQpaVZ19KdwC7NwCBjV5tVJ7xARuVoKzFFa92q)58uVXJnLRgvamXEJtpk(3Mj8rZwEde6EPh9FaRwZVdSmakoZhb8vlZHDABoyiy6O)a0E2DqZkfTJ7E2LhE1zqJZvaZYe0YOXcVKZCrEXCpb8l0qnq5MisfqgqmveMJ(xrSIrZ9SrqTbZ1fOTqEWwa6IGe(B5YL3mHieJ0VbWFKm7CX573EWWZU4OHD)myPF4v9o8KZad(DpOeqFt4EjJn6JR0gnQhcCby2ModMeG87QNVjGSChwayzcBxo33MF0vNCq8p6but8pitsX)Qp4kjQfWhqOEC4J6rHpMUhPhHErFRHWNf3Ya2lYXXhNIwkPfmGzSm9G8KnIOanFX8YUND2W2x1V9W2xE5zNqSdPFcL(I9B4bxy29725(Dp)IpV6D(W(DnpU0MV0ks0NT32EcNeThHqeL62rj8bCHzZCbRjaiKlU1wUDiZd74DSaSrPxcl7LH)l)gKhEfi1EKVC(S(GlWG2bbIXECNnIw(2utyO7uGKzEoQHCsWNfbcqhoDpt92lj1GLEzKaYI)7N(cNDFBa5dkp9jQPxenFD2xAIbzgGt2hkR8U91sPm(w6gfPuvJkBKVZArXYLlPmThnGijrCX5LhtKhI4PzZvfXJ(GSmctpuaS14zkaB6Rlrzz90u6MBaDMsNd2V62V0MF)jLdSG1ILgkvgz3qt6BEtrPtTLOHrA)yumBPTVtHhTL6LGT2Tid4kl3KPGV0E4r8quedfD2iLrMidjzXyiCQWVgPICZMRosgBuozjos29gct(9vhwXEWMiF858FTQFSNW8gJ69RpiM5lh7ZdcilgKlt0HGtP1aurUcjWqRvfgepJZz9Y9Aamm0KJb923c7joscqgh2YLiCJsBd8guSRdUZaAhnOaxIHTnxJPbL4vttI8FXLMsIhkTQtXHtQWUIvIwzO8hVM)LvYyZR(s0cuU1Ii1WiptD854(o5rENIDiQE9(xD4HLwvtupJR4C(GVtgeuD7g65YNdZSxGQ5)j0dM)yE4phOLK(UZhnlcI1xDlaOoYvHDMZqkg3PsxgXIsLllwDqqrrrHaaC0nqiPzRP4YeL6jdJCTJFtDf86PiyCzPKkW3sf2T3)N4)ouoESlF99E)d1B(A5D)phV9FGE)rzW3Fp))zejW7DKbFark8bg5WhqKeFOrw8rePX6h5rwlVRv8hFiXJ8rfFY7B8kRv8l5)CheYX9f0k7k15IhOe3nGtbj9CNdrYXzLo4O3M99CHiblT(HOLgBwqyGEWKRev8ayKdy0eQqPECc4mm(GmsAxpQqLLWGxE2xVaMEdbk9IbiLCizF8HiHibb9CoaJayAxFGTcPTa8x5CaXCJ8ArruCC7(NF4vNvkcLFghQzW4cd11l2GFOXkPfo8uhJaMMe9FG9uSLwahDCCU5wKoO6zsoczC4PMckqN4nsQfpo9neHrSqv5YrC43AmgVxXw8ogtXhqSezIHi1Q0oGHIkvQa2TwCliQJnVXBXL5ZfyXsZ2Ba(VNXwKKxKbmW37BH9ghHqSIXP)y9F)hR(qkI363zhWPZAW39qiO9FfBkiApgPneSAwxFnyuoVw8BeCXgxgXa(qrzDPBmZpuNRsegcVkkTzdvPtKqOOCssXJeNno6pbwMVsoYss83L(CkXF0Qv8CGjdZYKmjr1hGxs6mPYbGzhkEGpq145sOZ92UAf8ncm3(Em3pZ9dWSe2RkvygIPQKgoGWC)WK8I6jXu3gz8kI64G2MtacWPmH3Q37rcprWKvU)yQjdf23)0brz18olZhIqDS4qMWfJNeA1RfqgJIRWGgn1LtqhOjabNsm(t6zEYbD1vUWku6hFlvTROH23pV16mv31zmpQeAmYu(i9p5OJhqfBrsfOChL36js)lMHuzQ0utmeqS22xmtLw3qkN4Q6KyXTKDZf3sbA83tXcmbrdX8PwMpQYepICachdYaUl3oeb9i2C3qkV)pWCNZ1ZT5VcpH1Iqpjsw3ZFkBDcqzpgtnFA4x71HpbKC1Fq2jvtnBmYxofiQjmFUZ5aHWg2HbmSa(MeoLTBXPPBtedm7dX6a)dIzBciC9S9QULzBHpWU9EUxhgrCMeQ(eyGHcMgX2iQTCnKERNIENXS5i1OQBavXhSF8amWU34fwrxErtTgdbe0zcB6mkObPAtilU9muGhIwilS3nb2QZjmH1Fxm9qMcbJd(O519DzOreArrxEijKhbZMjW0hTjtcThayocYPSVH13bQGYNrlE6bxPCl4TGrbuTrpXiZdyJaA)TOTDNzM1vQsI0cARQxRIXE3R4S3J8LOKsoEjysSqtC1QRmZVJ)8GjGr7iINktOSaZyLbwFWTdjPVVimzLKQtPSGS2ldY9ZcY9bhOuP1nyIUY6EkUYQYjDuT(RRThzGiJc(fGKCBmBf2kZ5O28bIaLTmLfHWmZACznLw8cNGgRan1ro9o5eU7mCx(BetBGSBWKnJNgQWMYtC7wyWNz1yZ0lh1ZALSAZckEvq9GQ79QEoaX(tbn)rcFGLFovrnbKkWl67GGQrLvwiQViGyeh6svyucFUwZ88zdvPNQTwKXwtSSu9mqiYurS9NxZeZZzBcN1vxhBai0KsFLkmUS8LAfB1XOEXntDXS5UCpB(swQmAuWjF3vEr8a(mxoDUzhiytLEj8aQ0lZVo28vmgyKymifis0Sxdle5wplOgIXA4QaIK02L9apLN4otKb4PcMBrP2QRPCmQ(5rklFrGH8gB1aRx1C84ARGUsLmq49qxPMXktnNbCEmmDKC64YEmLQpw9Q5jNAfHCsvpRVnYznu)ogI4cSei8Uhn0Fo)(7zHs))Z8L1hR1yLzwDbLKYGO(uquFuKWESNpSMMZZV2Ti8RuLV8BJF1CLPOJeJzpiDdPOw9hNk2sS8QZtnTkWErkuudzQo78BtjIQ2RygmQxP4sn)cPh0h0Wz3pHTSzI6vlGTyw4KNqBeGDhmzijA5ynSNJ1w3Oq2jsQgDLGs1kRNKs9vpktyxY(2ti(Zb8qPxwHFQKZZYQk4gTQVg70cWz)PpYCDXDgjTVN5SS6D9v395VaHfcly(SzZshUpwV85xUAwOLRKlAWBsVUERIZIoJ58eg8OWd2q8L(Y5otLs)NHnT3YSPmBcAIW1Lw9hiNBpjM2OlFrAgAwgvJkfHrL6gJ8MyunwD102Grl8ooLy5JUve5jdJp69nL56GKNCky4QnQ)QBM4VEG07NdXcpdwibuKoelWhjEKJPeLCv(dsbyyS)MuofXRAQZRuDSxjh)OJCy09qtF4llUn6MjaVt12DQZ0uqJi6T5lYM85N6RQsUtL3Qs6Bor6Cp81sh0ntx0PpeVtgloD7TvL6Ug2jvZ3g4y2rn0nxCR6GL6Cw3RwC7m2t4DddMItZM8WLWTQ658e8GAhblqxFDBhNl8cU(6N58WU(AckxFnDKyLb5Zm0HXldS4d866RjicGhHuWlbQARdO0NfhDsClbX6RdeBl8pw67fbmA5aldsxxW0KV4bAZSosEajw(iZluvvKmhh9H4bbWptLhoAzKKzIAliZcu(ukV0ALA39kYqDWlBHLFqMtcit3XJAiU772Sk19SNlbLIo9XeLC)iWKjbu6x)6IttQibgvhNjyjqVqac0XvcbIJN7TQOhwCQlFuOEtlyd4WItYfchSzuEs3h9uCQV6Ogt1w6rEA4eb8t8)ZPl7bv6dyztSTnEYiBtZ9Tt5ygDe24ijJem4PX4bVTdB8yF2uM)n3qQ0A939ZKOGW4lHPL5pPSns)k1ffeSIok3n0uBPbZkaGBhL(G21N(FQ8cCXvdujgaV8KDKBpGQ8ds(duQ7OLq0hn)FztlZ)n0KyeyR9SUhc2Dgbeb3me26dJmwRUNRhITQUCwMD63TBpLbrlZd9f)2IB)hZzo4iaNGaiyUZMOgSanReq5oiGpfVvOMvlxPSX2y2oIVZLlDfyXmMiYM7avwNsDx36TTrI1EGS7R7ZY3koerKZSm)0Nspa9cV21u8rNfNyHcoy6KXcvlWQK(LGiQob8GzGFmqw(j9LsomEa68SGR)ZX1TF9Yd5v(xSgxoAxkTrWmuUALYvX9sGhwPbE2Bw)Vp ```

**Comment by emptyrivers** [comment]
Well then, don’t do that?

**Comment by InfusOnWoW** [comment]
Yeah, that's my reaction too. I'll take a look at whether I can figure out what is happening, but this is most likely a bug in AceConfig+AceGui, which we can't do anything about.

**Comment by InfusOnWoW** [comment]
This is a wow bug, not a AceGui bug. That is I checked that AceOption/AceGui does the right things on both a buggy/non buggy tab switching.

If you run /fstack after a buggy tab switching, the drop down on the right will not have show up as a frame and also the editboxes will not show up as frames.

But, creating a minimal test case from that would take a lot of work and this feels like too much work for too little gain.

Thanks for the bug report
