### ISSUE TITLE
Use: LibDataBroker 'launcher' buttons

### ISSUE THREAD

**Issue by JPEscher** [WeakAuras/WeakAuras2#1068]
Hi Weak Auras, one of the auctioneer suite ( https://auctioneeraddon.com/ ) is Noganna SlideBar. They use Slack for interaction with fans.
I asked about getting Details added to Norganna SlideBar and they said it is up to you. I asked if they have any requirements or other materials i could give you to expedite any such request being fulfilled.
They responded with:

brykrys [2018/12/31 6:10 AM]
@JPEscher SlideBar looks for LibDataBroker 'launcher' buttons - that's how it picks up buttons from most other AddOns
It also has a direct function to add a button, though I'm not sure if even our own AddOns use it anymore

Would it be possible to get the option of using this?

**Comment by Stanzilla** [comment]
What kind of functionality are you looking for exactly?

**Comment by JPEscher** [comment]
just to remove the WA button from the minimap (i think this is possible and i have) with the ability to have the button in the slidebar. i think the slidebar automatically does that if there's LibDataBroker information. 

here's what mine currently looks like: https://imgur.com/YeA9wBk

**Comment by mrbuds** [comment]
WeakAuras icon and tooltip show correctly on every ldb addon but this one.

First problem with this addon is it filter dataobj.type == "launcher", all other addon we have tested doesn't do this.
Second problem is with the tooltip, i don't know how it is trying to handle it but it obviously doesn't work with some addons like weakauras or exorsus raid tools
