### ISSUE TITLE
Overlapping Error that occurs when renaming auras.

### ISSUE THREAD

**Issue by Zed-Wick** [WeakAuras/WeakAuras2#1069]
**Describe the bug**
Had a set of items from one group that I duplicated and dragged to another. It kept its order. But as soon as I started renaming everything the order would keep breaking. And it would continue to break every time I closed WA and reopened it.

Reloading UI did fix it.

**Do you have an error log of what happened?**
Visual Bug. Not a logical error.

**To Reproduce**
1. Have a couple auras 2+ overlapping in the same spot (intended for design purposes.)
2. Duplicated them and move them to a new location.
_Note: Moving them to a new group might also be a part of the bug, can't confirm. Also left them in the same order they were as they were duplicated._
3. Rename the auras to something new.
4.  Overlapping error.

**Screenshots**
Oops, this is a video because I don't like messing with screenies. Also shows you how to reproduce in case the explanation above sucked. https://youtu.be/wDWfA2rHi8A

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No need.

**Which version of WeakAuras are you using?**
2.10.11

**Was it working in a previous version? If yes, which was the last good one?**
Unknown

**Additional context**
Needs more then 1 aura that stack over each other. Could happen with any aura.

My theory is that it has to do (in my case) with the names being super similar and WA want's to organize it alphabetically, so it may be doing that but not appearing that was on the list.

**Comment by InfusOnWoW** [comment]
I cannot reproduce that with a few auras I created. I need your original auras or a simplfieid test case that shows the problem.

**Comment by Zed-Wick** [comment]
[ogaura.txt](https://github.com/WeakAuras/WeakAuras2/files/2719202/ogaura.txt)

**Comment by emptyrivers** [comment]
Even with the auras you provided, I can't reproduce the issue (or alternatively I am, and I just don't see the problem). Can you perhaps provide a simpler test case, or maybe a video or gif of what you're seeing?

**Comment by InfusOnWoW** [comment]
I can reproduce it now

**Comment by Zed-Wick** [comment]
rivers theres a video in the main post. https://youtu.be/wDWfA2rHi8A
