### ISSUE TITLE
Rebirth - Cooldown Progress (spell)

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#1073]
**Describe the bug** (this could easily have been ticketed as a feature request tbh)

Rebirth (SpellID: 20484 - the Druid combat res spell) can be queried by any class in a raid encounter or M+ run to see the current state of the Combat Res stacks and CD. However making a default WA trigger for Cooldown Progress does not trigger at all. 

**To Reproduce**

https://wago.io/FjBFVxiiS    
This import contains a group with 3 Auras. The top one is a default trigger. The second is checking every frame. The third uses WA provided events (`WeakAuras.WatchSpellCooldown(20484)` in Init to enable them)

On a default trigger, does WA check to see if the spell is valid on the character once and not recheck later if it's all nils at that point perhaps? (just a guess, you'll know best of course). 

(Seems like everyone's using Auras that use an Always Active trigger and format the output in custom text every frame 😞 )

**Comment by InfusOnWoW** [comment]
!TF5wZPnoua4FnDM2zBi2ecx2z2h4IjHwkKIinBFXyHTW4gJfRKCijp4F77rsgJnqGSz2TBMDZKamwxo6C)t220ESnAHnYZgXTrLlzAuY08KAN4JRxhB24C5mWkEy4SzCIWEWj1kBJMszEegk4rI9aZQ2O7imEancEWgfasAezAatmpXrq4IehFgnEjSlS7TEm6Y20qkdekSA5)LvFFM67k2dmkDUTaetKGWIWHFlt0g2iCuWcSq(OuPXbQFfpSKyJIOrW3EXm18t0dYjU0ipUuECbMjE(lFwquaF(ZE9WoWXI5u2WLY55WgLNjjC2vuWsSrTgoE8WV03Q741EVwPEdyUWGhFeZ8sCgtPHIayOywOnAUqSK)RNE6kSpTua90U)Ov3VDFqa6uZ1czDubctsvji3HRxG9uBe5(L4ipINDlWUy4feKamdSkAPx1ZkIWi(G0hRS80i69zzfvmk1OrJ61Q1OCJQ1RVwWwE(WQhOCE4ixWbL6pABnyS1iWf5IdjknHtwaPr2iZsgLGqDifRs8CdXCUkChdUgLPj9SljU7oOmFC7bJ5KjAzmvfLukrxPxqBjO2JSSgaHzwGVpKRP9cGuIJshs7o38G8Wdd75L6N1PcyiZOSCtbWqldXpinfYDePTEjbhkMd7lEQAKRyKzb3dh9vw97Vzyu8m1WtA3enEcACZrWzfbkA6b5rMcRqR1xA1)QUx3xzIzX6ErQyHj4mJLvHRA2267r3mBg5hGc6Uo3akTcePjOPff5t4vcesMMf4V(P7aHwPmiw3mVtw)GY1HaMHXzgNBw78A1LQjhlK1jezUNGCVWSqnWOExC54deiEnxJFlHSSPm3tmsUgPbMRgFDoTluf7rxfPs(NU55XGVWkcpnuxkYfbU3(qN0JlZz1LkLvxwWJjoFng7jlvHodJlwagaAv(6pZQNlddLRuXSIrvit0pKUskZ8TMpExLTkc3tpnvM1moR9FCRRXzn(8gZtAtzwqkBOSEOYB5HEXjJ6diNtCvGhuAnOAfTfF4gzMzsOnOIqQ1cv9zVbOEDSs9PT0empYmm0gjXPDhGILw7JCJ5c6czC86LEYmCuC6V7fxPm99EuQzYzgQN343kdMdoC5CDp6hP0fqx40vzJEhpX50eN3Tm7eoQrdbsAH4t3qSpW7hE94(9gyTlxaABUXFonNcU9g3g7i3LofDASqqJgc5tq7WnPjqidMDTUawtK07jttvflhPV)(AXVpyGiNkV)QPd2Wh5tIiSax0C6QHGcYHFBgUc)aFlwGeVGNYPSPFH6PmR91MwTSIISLSEghIKSKbGVhIBgvQxrVuY9qfYeE2CT2MSehLYwub2dOTkXvqq8DoX9XZGIrrmVa)j9eBNghtCUIr9zeoKn(ELz8HxgItQHkRR1MMVqhO0BvbDkUJmw7WvUyOxNXgs(wnwslUpA9WCsG)CHUVH7rxUeZva6zwtb9mlx2OMXzMVb9(xc6vrb9mQAAC25Y3d5FuO3fJAtit)8x6v)S)Jc9YETTtsCG6v2djokUWBGV)3a(ogDtNiGeWlVcoJzXrQK63)HKpL4O)lKcVsxIJ7htCwK48Bjoxqek8q75yMpH)Ef1j3gyeOZjGtCt(ejY7jaO6ZTNQbqUtnBZRpezkAmJS(qCusuV5dVXT0o9gZJM0czsr8O7CI7TBkgoiKUiMnpPlv2zDflOOP(ZjFu)HdF8oOFDTL5jx5VaLmP(1TEBuTHS218CFj09d4FvHQpRaQUALCiIZR(Sr17YDEJr)KDuEY295z1M)Cy1RbAVacD(uTTzUQRau)XQl(9lU2)YOV(3lf(jHh7T05LqJ3hc7Vem(iuLIS6FAK5cxkyBK8U34kRF3ne8TnHmCEPBWc356gPPzmPDsHko6K0136i3v7NmHxMlYkEzTiXBKDyJeq5c8GPp5KLmOAyZaBaJpfYppNKNI2M0E4W(DgEZGjJSA257joBnQIqA1zNXBFzZbxy1Pa78q3Gincw4wbh8(dfVQXR8lqK)EuVOBqSZBd9mAW4(m6b9eVpUsBK8NEqemJ)adA)N

**Comment by InfusOnWoW** [comment]
This was caused by adding a spell known check in response to #708
