### ISSUE TITLE
down-arrow breaks author options

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1075]
**Describe the bug**
down-arrow breaks author options after adding a new option while group is selected.
from that point on an error fires continuously when clicking on a related aura that has author options, forcing you to delete it.

**Do you have an error log of what happened?**
```
8x WeakAurasOptions\AuthorOptions.lua:971: attempt to index local 'option' (a nil value)
WeakAurasOptions\AuthorOptions.lua:971: in function <WeakAurasOptions\AuthorOptions.lua:966>
WeakAurasOptions\AuthorOptions.lua:1566: in function `GetAuthorOptions'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:3448: in function `ReloadTriggerOptions'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:2862: in function `ReloadTriggerOptions'
WeakAurasOptions\AuthorOptions.lua:930: in function <WeakAurasOptions\AuthorOptions.lua:921>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-67.lua:50: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:48>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-67.lua:789: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:610>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
Quartz\libs\AceGUI-3.0\AceGUI-3.0-36.lua:314: in function `Fire'
...nTools\libs\AceGUI-3.0-36\widgets\AceGUIWidget-Icon.lua:26: in function <...nTools\libs\AceGUI-3.0\widgets\AceGUIWidget-Icon.lua:25>
```

**To Reproduce**
1. Import https://wago.io/bfaraid2
2. click the entire group
3. go to author options tab and add a new option
4. press down-arrow on the newely created option

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
elvui's acestuff was disabled

**Which version of WeakAuras are you using?**
Only tried misc from emptyrivers's github, assumed it will break on live too.
https://github.com/emptyrivers/WeakAuras2/tree/misc

**Comment by emptyrivers** [comment]
Don't open issues for bugs you find in a pull request. Make a comment in the pull request instead.
