### ISSUE TITLE
Multi-selecting auras with conflicting collapsed data in display tab behaves poorly.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1088]
**Describe the bug**

The image on the collapse button vanishes, and the button cannot be pressed, if the auras selected do not agree on that particular key.

**Do you have an error log of what happened?**

This causes no errors.

**To Reproduce**
1. Create a non-group type aura.
2. Click on the > button to the left of `Position Settings'
3. Create another non-group type aura.
4. Select both the auras just created

Expected result:
The rendered options should resolve as collapsed, and should be changeable by clicking the > button in the header.

Actual result:
The rendered options are not collapsed, and cannot be changed. Additionally, the > does not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/24878501/50732246-d291ef00-113c-11e9-933a-a1bad9e066c5.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Naturally.

**Which version of WeakAuras are you using?**
1b3787b54bfd8a6b040f3b9b04c6bac476d1aaec

**Was it working in a previous version? If yes, which was the last good one?**
Unknown. When I wrote this, I am fairly sure that I checked that this worked correctly. However, I do not clearly remember, and it has since been touched by @InfusOnWoW, so I cannot say for sure.

**Comment by InfusOnWoW** [comment]
This is "fixed".
