### ISSUE TITLE
status cast trigger (missing an event?)

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#1093]
**Describe the bug**

default trigger > status > cast > focus
if unit is casting and you /focus it cast bar is not displayed until new cast starts
if you change /focus unit to other one  the old cast bar will finish its duration
feels like missing PLAYER_FOCUS_CHANGED
**Do you have an error log of what happened?**
 
no errors
**To Reproduce**
 
make a status cast trigger tracking a focus
start casting hearthstone and focus yourself
or
focus yourself, start casting and change focus unit or /clearfocus
**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by mrbuds** [comment]
i have a fix for this ready

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
