### ISSUE TITLE
Profiling UX improvment

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1094]
Current ways to activate, stop and show profiling:
### /wa commands
* /wa pstart
* /wa pstop
* /wa pprint

### minimap
* Right-Click minimap icon (start)
* Right-Click minimap icon (stop)
* Shift-Right-Click minimap icon (show result)

> [10:52] asakawa: How annoying would it be to add a command to the minimap button that profiles the next period of combat that you get into?
> [10:53] asakawa: Maybe also have the button pulse or glow in some way if you have unviewed profiling data?

Imotbh we could drop the "show result" click and display it when profiling is stopped.
User gain one click, and it free shift-right-click for asakawa's suggestion of activating profiling for the duration of next combat period.

/wa profiling commands behavior can be kept unchanged if we want a way to use profiling like before.

**Comment by asakawa-k** [comment]
The reason I started this train of thought was that people showing Profile data and looking for advice could have been Profiling while standing still in their Garrison for 20 minutes or could have been doing 1 min in P3 G'Huun. I think that if people had an easy way to just get pure combat data then it would provide much more useful info about only highly relevant periods.

**Comment by emptyrivers** [comment]
tbh I think a details plugin would work best.

**Comment by emptyrivers** [comment]
In terms of usability I mean. No idea if the current profiling code supports that kind of live inspection.

**Comment by emptyrivers** [comment]
@mrbuds as I recall, you did write a details plugin somewhere. Can we close this ticket now? Or did you still want to change the flow of the native profile feature?

**Comment by mrbuds** [comment]
I forget what i did, i need to dig it

**Comment by mrbuds** [comment]
Cool i still have it in my data, now i wanted a nice way to integrate it into details and i remember i asked tercio about it, but i lost track on it

Auras:
`1jv4QTnmq4xNuWXS93b7hMSXMn00bkSYyTcFX6CJOYsgPtbkJQNM9M0xSEwjPjlPJdljRVV7tF6oj)OCLueCrFhkxlfqK248sXsTcE5VZ)vWzvEukuyOtkyMJOXOvtuTWadClcpwf9qi1MNykDE9ijfgxhysTlCdRbQGxedKByHZsG2IEENABGaBhMA)CQTSSm1SphYrGPyAEKhHbx0szsFOy)3BuvabzO3ms5O31Rn4xyKsiBTMutVZZkX)vR483MA12u7iO9HztsCfRKJ51Ul09mNs0aJbuX(ydApcEiMp)WQ9Er35S)RxeWwuvQ0Hrd8u437o)7pSr9e)lK9S60NQuQFcMixLM9NlzFEm1vYE4WD9ImEU4K72vhXrRk1KhsnN0aYIDUN(gsRMOuzvFx)WgmqzloJL7KU17K1Y4qvh54Q(0j34rk6T)NgEZXqkiW)as5NOe51RJu(96ujxkQTe67Ho8U6f3SuC3QVE9p4uCodPhLIScKu(6d`

Systems:
`1j5Blromqy8VoRqVY5BpWxuwpURfCvilEiiHoBZSUbtZusMiCiMpn(nXVyoTU)JvLqtl95380NmD0NRxQvrkf6q9kTcs8gkOvlSg4Tx)XDrYBcOwzWyNwjKdOZznJOEOxe(hcpwLcqm3Q(FKX(Oa1fSdSw5OoWLBNt9RaUqEifzQFo5zW6XG8MAFKbFhMBVi3wwwMB2wdtm4kgVpi7qpL88e0pl2ETh1ammjTpkLdbAT1HxkkLXpsvUj3SMcIxcrTrC4PCR1NBhaBioB0KZeViHR9JLDTWuIoyiIgjjBq)bXDRtos)QYyUfCj5an75ptF6ASfof9DH6tv8sXrH4Sd6O3KBM2Ynh1RMm70m9hKxoIu5n)1(WgmYtrCMy3rn2VOQfP(QoMK2Z4xUjGCk4)M)nIUwXq4bKhhoSDKxRQ9mgwdD491ZVEH6(L)(QBKzmMd2vjEAGJjYX2bTAYbwRF)d`

You can test it in /details > Tools > Custom Displays > Import

**Comment by mrbuds** [comment]
Changes allowing this were merge with https://github.com/WeakAuras/WeakAuras2/pull/1515

**Comment by mrbuds** [comment]
Atm mouseover-ing them raise this error
```
45x Details\classes\classe_custom.lua:991: attempt to call method 'GetClassColor' (a nil value)
Details\classes\classe_custom.lua:991: in function `ToolTip'
Details\core\control.lua:1654: in function `MontaTooltip'
Details\gumps\janela_principal.lua:1911: in function <Details\gumps\janela_principal.lua:1907>
```

**Comment by emptyrivers** [comment]
Well... that sounds like a bug in either the details thing, or details itself

**Comment by mrbuds** [comment]
From what i understand Details is meant to deal with units, and i'm feeding it with names it doesn't know about, i'm not sure if Details is the right tools for this task tbh.

**Comment by gtosh4** [comment]
In the meantime, you can work around the "attempt to call method 'GetClassColor'" error by adding a fake `GetClassColor` method:
```diff
        CustomContainer:AddValue ({
                name = auraId,
+                ["GetClassColor"] = function() return 1,1,1,1 end,
        }, v.elapsed)
```

**Comment by mrbuds** [comment]
@asaka-wa @asakawa-k with https://github.com/WeakAuras/WeakAuras2/commit/36d83ba673b51d88fe85e31f16d844609a743cfe now merged, do you think this ticket can be closed or more needs to be done ?
