### ISSUE TITLE
Condition to Add/Remove Button Glow

### ISSUE THREAD

**Issue by alexisakov1** [WeakAuras/WeakAuras2#1095]
We need a way to Add/Remove Button Glow in the Conditions.

Right now the only way to get Button Glow is in 'On Show'/'On Hide' in Actions.

There is also a way with using Custom Codes with LibCustomGlow but is very messy and inconvenient.

Looking forward for it to get implemented! :)

Thanks!

**Comment by emptyrivers** [comment]
This exists, it's called "Set Glow Visibility".
