### ISSUE TITLE
Condition to Add/Remove Button Frame Glow

### ISSUE THREAD

**Issue by alexisakov1** [WeakAuras/WeakAuras2#1096]
To not confuse with a regular icon glow controlled via 'Set Glow Visibility', this request is for Button FRAME Glow that is called "Button Glow" in Actions tab.

Currently, there is a way to add a glow to a button frame by ticking "Button Glow" checkbox in Actions tab and then Choosing the desired frame by clicking on it.

Wouldn't it be nice to be able to manipulate that Button Frame Glow in Conditions tabs? 

Right now the only way to achieve it is by using some custom code conditions, but its not convenient at all.

Thanks in advance!

**Comment by emptyrivers** [comment]
Well, you could have reopened your previous ticket with further explanations, but this is ok too. 

However, I’m still leaning on the side of declining this request. The feature you mention is not one which I want to propagate. It’s clumsy, doesn’t perfectly solve its use case, and is overall more complex then just calling `WeakAuras.ShowOverlayGlow(frameName)` in a Run Custom Code condition.

**Comment by emptyrivers** [comment]
I’ll leave this ticket open in case someone wants to chime in.

**Comment by mrbuds** [comment]
while i agree with you rivers, i wanted to add the Ipse tried to implement it today

**Comment by mrbuds** [comment]
@ping ipse ?

**Comment by emptyrivers** [comment]
Nobody has chimed in to defend this feature request. So I'm closing it.
