### ISSUE TITLE
Code block that is run on trigger update

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#1097]
**Is your feature request related to a problem? Please describe.**

I want to be able to run some code whenever *any* trigger's state changes. 

**Describe the solution you'd like**

I'd *like* to see `Actions - On Trigger Update`, a function that gets sent the trigger (and clone?) whose state has changed.

If the consistency of Actions code blocks not running functions were imported then perhaps simply `aura_env.lastTriggerUpdate` could be provided. 

**Describe alternatives you've considered**

"Trigger Update" on Custom Text only runs when the "current" trigger changes and, honestly, Custom Text gets abused enough - perhaps some more options for running custom code at useful times could draw people away from lazily running every frame code so much. 

**Additional context**

A specific use case might be having trigger2 checking for buffs on the raid and creating clone states. I want to make trigger1 to check those states, make decisions based on them and output my own info based on them. Currently I need to run my own custom trigger on every frame to catch changes to the clones. 
I think it would see a lot (relative) of use with the amount of anchoring that's done these days too. 

(tbh, I'd welcome an "Every Frame" code block there too so that, when Every Frame code really is appropriate, we don't need to muddy things by using Animations or Custom Text.)

**Comment by asakawa-k** [comment]
An additional benefit to this would be providing a way to run custom code on an Aura like a Texture that has no Custom Text to piggy-back on to.

**Comment by asakawa-k** [comment]
That would be fine for all my own use cases, as I would probably be running ScanEvents in the clode block itself, but it would effectively hide it form users entirely.

**Comment by emptyrivers** [comment]
A...trigger update event? As in, a fake event called “TRIGGER_EVENT” which you could subscribe to? That doesn’t sound very practical (not to mention the performance cost for heavy users...)

**Comment by asakawa-k** [comment]
I actually made something just today that would really love to have a better way to trigger. 
https://wago.io/GlowOnDemand++

I'm basically comparing 2 group-unit triggers to evaluate multiple buffs on each unit. The workaround I had to use was to track UNIT_AURA and add a delay to allow for the default aura triggers to set their states. 
My feeling is that Auras like this will become more widely used over time. The updated custom text method will help but still feels like "abusing" something that happens to work.

**Comment by InfusOnWoW** [comment]
But while having a Action On Trigger Update helps with that, it would still be a kludge, since you aren't supposed to change trigger's states from there. That would be better suited by a kind of proxy trigger.

**Comment by emptyrivers** [comment]
We could add a global condition to achieve this.

**Comment by asakawa-k** [comment]
If the Global Condition thing goes ahead, would also suggest a per-trigger Condition too for that trigger updating.

**Comment by InfusOnWoW** [comment]
This is now possible via a watching custom trigger.
