### ISSUE TITLE
Feature Request: Parenting

### ISSUE THREAD

**Issue by socalminstrel** [WeakAuras/WeakAuras2#110]
A nice feature to have in WeakAuras would be the ability to parent to other frames. kgPanels leaves open text inputs to put in the name of the frame to parent to (and anchor to, which would also be nice), as an example. That way it would be fairly simple to create an aura that, say, only showed up when your minimap was displayed or somesuch.

**Comment by Stanzilla** [comment]
https://github.com/WeakAuras/WeakAuras2/pull/7

**Comment by InfusOnWoW** [comment]
That's tracked as https://www.wowace.com/addons/weakauras-2/tickets/666-enhancement-anchor-to-personal-resource-display/ . It's something I want to work on in the future.

**Comment by socalminstrel** [comment]
Okay, thanks a lot!
