### ISSUE TITLE
Bloodlust/Heroism template broken

### ISSUE THREAD

**Issue by Rolienolie** [WeakAuras/WeakAuras2#1101]
**Describe the bug**
For the template of a progress texture, choosing Bloodlust/Heroism under the General tab gives you 3 options. Each of these options returns a lua error. 

I will post all 3 separate buttons lua errors below since I'm not sure if all of them are needed or different. 

**Number 1**
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:2180: attempt to index local 'dest' (a nil value)
Time: Mon Jan 14 22:38:29 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:2180: attempt to index local 'dest' (a nil value)
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:2180: in function `recurse'
Interface\AddOns\WeakAuras\WeakAuras.lua:2184: in function `DeepCopy'
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:243: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:227>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:779: in function `createTriggers'
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:982: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:980>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1012: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1007>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1255: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1240>

**Number 2**
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:2180: attempt to index local 'dest' (a nil value)
Time: Mon Jan 14 22:45:40 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:2180: attempt to index local 'dest' (a nil value)
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:2180: in function `recurse'
Interface\AddOns\WeakAuras\WeakAuras.lua:2184: in function `DeepCopy'
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:243: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:227>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:789: in function `createTriggers'
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:982: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:980>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1012: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1007>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1255: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1240>

**Number 3**
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:2180: attempt to index local 'dest' (a nil value)
Time: Mon Jan 14 22:46:38 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:2180: attempt to index local 'dest' (a nil value)
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:2180: in function `recurse'
Interface\AddOns\WeakAuras\WeakAuras.lua:2184: in function `DeepCopy'
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:243: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:227>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:801: in function `createTriggers'
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:982: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:980>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1012: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1007>
...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1255: in function <...rface\AddOns\WeakAurasTemplates\TriggerTemplates.lua:1240>

To Reproduce
1. Go to 'New -> From Template'
2. Click on 'Progress Texture -> Default'
3. Scroll down to 'General -> Bloodlust/Heroism'
4. Click any of the 3 displayed options. 
5. See error

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
