### ISSUE TITLE
custom options could use a sound option

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1102]
**Is your feature request related to a problem? Please describe.**
The problem is that any alternative is ugly and a bad solution because
a) adding sounds from sharedmedia sources to a dropdown forces you to kinda explain that it requires an addon for it to work which makes everything look ugly
b) can't make the default dropdown hide if you don't have the sharedmedia addon. if it behaved equally to action tab's sound option and you were lacking the sharedmedia addon, then it would be blank and the user looking at your custom options would feel like "oh i have to input something here"
c) the process of adding all sounds to a table so it can be used in a dropdown is soul draining https://i.gyazo.com/9f235c6f1bc7c338680e55374988c9fc.gif

**Describe the solution you'd like**
a sound option where the sound-path is the value?

**Describe alternatives you've considered**
https://i.gyazo.com/b7f4750b8d6e598035f2f92c50c9b4fd.png

**Comment by Causese** [comment]
yeah that sounds even better, assuming the sound sub-option doesn't have to be populated manually.

**Comment by emptyrivers** [comment]
The idea was to hook into the same LSM widgets which are used in the rest of the addon.

**Comment by Causese** [comment]
i slipped on the comment button

**Comment by Peter-Day** [comment]
Any chance this could happen before Shadowlands? I'm very interested in using it for WAs I want to have ready for then.

**Comment by Peter-Day** [comment]
Still very interested in this. Would be willing to bribe with a pizza or something ;)
