### ISSUE TITLE
Cooldown Progress Triggers losing "maxCharges" info on last charge

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#1112]
To reproduce, make a simple Aura with `Status - Cooldown progress (spell)` using a spell with charges (I tested with Blink on Mage and Barbed Shot on Hunter)
In Display use `%charges %maxCharges`
The text will be, for example, `2 2`
Now use the ability a couple of times until the last charge is on CD. 
The text will be `0`

the specific reason this came up was someone using `aura_env.state.maxCharges` in a custom text function but I think it's reasonable for people to want `maxCharges` to show throughout on any spell that has charges. 

I think this is due to https://github.com/WeakAuras/WeakAuras2/commit/b81a16907984d860818ac00b5357dd4e4bc95d02

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
