### ISSUE TITLE
Add a "Unit" field in "Status > Conditions" Trigger type

### ISSUE THREAD

**Issue by Guema** [WeakAuras/WeakAuras2#1114]
**Is your feature request related to a problem? Please describe.**
When i create a Status > Condition Trigger, i can check different things on myself. It works well but
what would be great should to have a "Unit" field to check things on the Unit you want.

Atm i want to check if my target is alive, i have to make a life or life% > 0 condition where an alive check should be enough : 

![image](https://user-images.githubusercontent.com/8943532/51420803-0685ff00-1b96-11e9-8ab5-11533ecb0d3c.png)

This is just a little bit more elegant for my problem and, but it may be necessary if you want to check your target is mounted or is in combat for exemple.

**Comment by InfusOnWoW** [comment]
I don't think adding a unit field to that trigger is warranted. While some of those checks can be done for any target, not all of them can. And some of them seem to be pretty pointless to check on other units.

And using a Health trigger (or a simple custom trigger) doesn't sound to bad to me for that use case.
