### ISSUE TITLE
Playing a sound through a Condition and Actions->On Hide does not respect selected Audio Channel

### ISSUE THREAD

**Issue by TheLinXx** [WeakAuras/WeakAuras2#1119]
**What steps will reproduce the problem?**
When playing a sound in response to a Condition, or when using On Hide under the actions tab to play a sound, the selected Sound Channel does not have any effect on which channel the sound plays out of. The sound will sound exactly the same as played through the Master channel, regardless of picking Sound Effects or any other. If you play the same sound through the Actions tab, the sound does respect the selected sound channel.

**What is the expected output? What do you see instead?**
Volume being lower when played through a different channel, such as using the Sound Effects channel, instead of Master, to lower some sounds, like using the Air Horn, instead of it blasting at full volume.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I have tested both the Conditions and the Actions->On Hide problems without any other addons, and the same problem occurs.

**Which version of WeakAuras are you using?**
WeakAuras 2.11.0-14-g6e5f2cb

**Do you have an error log of what happened?** 
I do not.

**Please provide any additional information below:**
No specific WeakAura is having this problem, as I can recreste the issue with any WeakAura, new or old, imported or not.
It works as expected when using the Actions->On Show, where the sound is played at the expected volume, depending on the selected channel.

**Comment by InfusOnWoW** [comment]
I cannot reproduce this, sounds are played on the channel that I select.

Can you attach a aura that shows the problem?
