### ISSUE TITLE
Allow aura to be selected by index.

### ISSUE THREAD

**Issue by Kruithne** [WeakAuras/WeakAuras2#112]
Currently an aura can be specified by the name, partial aura name or spell ID. If you enter a number, but do not have "Use Full Scan" selected, it would be great if the number was used to check the aura in that index for the unit, rather than passing it in as a string still.

Use-case: Setting up a custom buff frame using WeakAuras.

**Comment by InfusOnWoW** [comment]
The buff trigger can already show all buffs for a unit. What is missing for your needs?

Otherwise, this sounds to me like something that should be solved with custom code.

**Comment by Kruithne** [comment]
I'm unable to produce what I described.

Can you demonstrate how a trigger would be created to show a buff/debuff on the unit without a specific ID or name. Whichever buff is in Index 1, regardless of what it is.

**Comment by Kruithne** [comment]
@Stanzilla pointed out that the "Use Full Scan" has "Auto-Clone" which solves this issue.
