### ISSUE TITLE
Auto-Clone memory leak(?)

### ISSUE THREAD

**Issue by Kruithne** [WeakAuras/WeakAuras2#113]
Spoke to Stanzilla about this over Twitter; there appears to be some form of memory leak in the auto-clone functionality (assumed).

WeakAura example: https://ghostbin.com/paste/cd3tk

Reproducing this is slightly difficult, since the effects only start to become apparent after a fair amount of game play. To begin with, changing target will work fine and display the buffs said target has on them. After a few hours of game-play (more or less depending on how much you switch targets), selecting a new target (providing they have at least one buff) will stall the client with a fraction of a section.

The length of the stall increases overall as the player continues to target swap throughout the session, but the effect is also amplified by the amount of buffs on a target. If the client stalls for 1 second when switching targets, switching to a target with 5 buffs will stall for 5 seconds, the former amount still increasing as target swapping continues.

**Comment by Kruithne** [comment]
Additionally to the frame drops, after elongated use, the auto-clone feature will start to malfunction and never hide auras once they're shown, instead just stacking them from previous targets.

http://i.imgur.com/MchO9PA.png

**Comment by InfusOnWoW** [comment]
I think I've found the problematic code and this should be fixed with the next release. (Though with memory leaks, there could always be multiple instead of just the one I fixed.)
