### ISSUE TITLE
A way to track only recharge rate of charges after one of the recent updates to Status - Cooldown Progress.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1132]
**Is your feature request related to a problem? Please describe.**
One of the recent updates changed the behavior of Cooldown Progress (Spell) when used with a charge-based ability that incurs a Cooldown separate to the recharge (example given was Rune of Power). This had a side effect of removing the ability to track the recharge rate of a charge during the CD in most scenarios. Selecting Show CD of Charge does not change this behavior (unless you are not recharging that charge at the moment).

**Describe the solution you'd like**
I'd prefer the following behavior:
Selecting Show CD of Charge with no value in the input field should ignore the CD entirely and simply track the current remaining recharge.
Selecting Show CD of Charge with a number value should always show the recharge rate of that specific charge and ignore the CD entirely.

**Describe alternatives you've considered**
An alternative would be a checkbox option that states something along the lines of "Ignore CD incurred by cast for charge based abilities", but I felt that was too vague and long, with risking making it even more vague if you shorten it.

**Additional context**
Perfect recreation of the problem (gif below):
Play an Outlaw Rogue. Have a Cooldown Progress (Spell) aura of Blade Flurry with settings to show Cooldown (varies based on addons installed). Optionally include the trigger setting Show CD of Charge (nil, 1, and 2) to test all behaviors. (Alternatively test a mage with Rune of Power, but I don't know the exact values).
Working as desired:
- Press Blade Flurry with 1 charge remaining when you have more than 12 seconds remaining on the recharge.

Not working as desired:
- Press Blade Flurry with full (2) charges. The CD will count down from 12 for the initial CD, and then count down again for 13 seconds.
- Press Blade Flurry with 1 charge remaining when you have less than 12 seconds remaining on the recharge. The CD will again count down from 12 for the initial CD, and then count down again for the amount of time remaining on the recharge.

Gif showing behavior of clicking Blade Flurry once at full (2) charges (I accidentally clicked Remaining Time when changing my focus back to WoW but it had no impact on the behavior so ignore it):
https://i.imgur.com/yl4kaDY.gifv

The gif also shows a weird lapse that occurs between the CD expiring and the recharge showing.

This could potentially be done as a bug report as well, as I wouldn't expect selecting Show CD of Charge to show the CD incurred by a cast in the first place. The behavior changing based on your recharge duration also seems off to me.

As an aside, this could also be used to remove the internal hidden "insignificant CD" portion of the change entirely. Users could simply select the option that removes the CD.

**Comment by 1ps3** [comment]
I like to think that when tracking a spell that has charges, it should default to showing the full cooldown, not the recast cooldown by default. The reason is because not all spells have this, only a few of them do. Having a little toggle like gcd is already would be nice, something like "Show Recast Cooldown" or something like that which gives the user the option to show it if they want to, by default I don't really think anyone wants to see this nor do they care about it as things that trigger this cooldown usually have buffs applied to them like blade flurry and rune of power.

**Comment by InfusOnWoW** [comment]
The latest alpha has now a additional setting to choose whether to track only charges, only cooldowns or the current combined method,
