### ISSUE TITLE
Caster's Target condition not activating

### ISSUE THREAD

**Issue by lundgren87** [WeakAuras/WeakAuras2#1135]
**Describe the bug**
A WeakAura triggering based on `Event>Cast>boss1>"Spell Name = Buster Cannon"` is displayed as `%i %n on %destName %i` works as expected (icon Buster Cannon on name icon). The condition `If Trigger 1 > Caster's Target = Player` is set to change color or font size and is expected to activate when cast on player but doesn't. Neither does it activate if the inverse is set (Caster's Target != Player), which leads me to believe it's not evaluated properly or evaluated at all. Other old conditions work fine with the same aura.

**Do you have an error log of what happened?**
Bugsack/grabber report no errors.

**To Reproduce**
Reproduction can be done through setting the WA to trigger on any targeted cast (used Heal below) by player instead of boss1 (Triggers as "Heal on name" but condition remains inactive regardless of setting).

**Screenshots**
https://puu.sh/CE3BD/19ab20a0b4.png

**Which version of WeakAuras are you using?**
2.11.1

**Additional context**
Basic aura used to test with Status>Cast>Player>"Spell name = Heal" exported below.

``` !nwvtZjooq0Fn54mLTXqGdZHegZoufJjlYztTxer2wg0gJKxlziKd53(2TKmXtMu1MkeHqF09R7x3prdPzuYbkPe)atvDMAHKtjRVpB1Y0ekzxT6enNsm8NnHlusdr8cNMggrjfkvDP6Kmd2krYYR5L0Bbdj0n1SZ4QuYvIxF8k5RpQG)VQKRnPSdCyQGsoVUQsZnGTMeqjmzXEv7DkHeU18K0SKnGtBf72XB1a0sTq1Vaov3WRRxwstJcW7x21YmcLKscPKonFRDFepsWJOfa7Ia4EPaMHieSdSsExvv25giM)rYQ7wC)kVPHFZzWOUlNFKdXnCoXZuY253qY2sYUzdac7oaEzAZBN8UwU9KK7swTYbMo0P3oayaWZVedE0HBYY1Q28FQk54XnwCPnmtN2T)LiaUDN07EwNrH)CqGHMtoiB9UnXlvyeh5zUJyDy6xcdWD65vYjrJdgavg9oQPOtBuhqs((MsMbGzN)7(RNuUJJWuuaSIl2XIP5QAvlUoGAGXx3GSMpdylYguk9eN3CdKKkmBqY1ElP4GJOZSzMwdoPN936ZyCWNqA1NaLkOKgm)bMq(5pDLqk07)0NhUXZ9v0boobbAXdIsZEk5glhHjDx0Eb7d9emxGef6t1wxkgdA)mIZnqnauq0Ij7CxdQlNABsWpr2Xr2XyCe9HczVfTIxE9X)SJvcxN96JzzE2f7SxuZ2Ph06VNl2ThIMjXiSm8wjR(VGUrm5NgcTz1kMv1qJscOqsxTryddWvCzHQdVLaexIIUEceg1mT(3oiYV)2IyT(qlKJlEs1w(qlRHsE4YmKke9jvNirXEEXtdvlGLjhzTcSUAOiGcU)3(MTKFptUJ)MjoYQ74dtOlUEs0SjqueeheoEwqiT6lJhJj5fxplmc0GIdIdNedF53PpX30QA4TMZiurwY4)ZYioX0rrEwyoSeuJEW2vVmLS87EfyNavENXOKRpYBH(yF3YNG6lE7ilMmA80GOrbbJgfpz80RrWoYgGthhpniy61bXXZMfnlYVZVAkVl)au6X))lyA57aYYfpg7tewB6vxUDDw26FUz5F8duZcRCw(s0t)R54T)D1UbLQU8weuyw1cY7atdLZwE29oYcCvNtiZ3KKK6Dd8GeuHZQB27o9Lx1(4wJxuqxxF3mkiP51v)cuHoJs3lfWn4AZat((2jl47f3Gg3twHbB3Lg0jE6837Fcl3wwxj21ljamU22S)pGqGOc4(vjl6BDHyQb1qEMx60AGxedgKR(4qZ)k9suCMyBdHU0Vgg(vSxbYnXriDr)Vp ```

**Comment by mrbuds** [comment]
Indeed the condition for "player" doesn't work as expected.
A temporary workaround is to select "target", and then select again "player" and it will work.
