### ISSUE TITLE
Icon Region: border

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1138]
**Is your feature request related to a problem? Please describe.**
Icons can't have a border like bars have, it could be use as an indicator for ... anything

**Describe the solution you'd like**
Same implementation as bar region

**Comment by InfusOnWoW** [comment]
Yeah eventually that's the plan. Won't be immediate, but long term that's the idea.

**Comment by emptyrivers** [comment]
I like to call it, “medium term”.

**Comment by emptyrivers** [comment]
The infrastructure for this exists now. It is now “just” a matter of implementation.
