### ISSUE TITLE
Play glow birth/death animation when showing/hiding an aura

### ISSUE THREAD

**Issue by Guema** [WeakAuras/WeakAuras2#1140]
When creating a glowing by default icon aura (ticking "show glow effect") and then showing or hiding it, the glow poping/unpoping animation will not play.

Normally the glow effect start with a flashy noticeable spark effect before starting to rotate over the button. The birth animation in facts.

The animation can work well when activating it at the right moment via conditions panel.

I think the glow animation is - at the moment, in the code - welded as a property of the icon aura, and then it only show and hide on ticking/unticking glow effect box, resulting in glow never playing birth and death animation because it is still activated on icon aura whatever its state.

I think it would be probably better if it was playing birth and death animation on aura showing/hiding by default. 

Expecting it was understandable (French)

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
