### ISSUE TITLE
Update Auras as default

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1148]
"Moved" from WeakAuras/WeakAuras-Companion#98:

> Currently the default import mode is Create a Copy.
If the Update Auras mode is generally safe to use then I suggest making that the default, as I think the use case is usually more fit to that; its less likely that someone wants to keep a copy of the old auras to tinker with them, they are more likely updating the fast changing auras like Causese's T23 one.

**Comment by NLZ** [comment]
OH, I didnt know that the functionality was provided by WA directly, I tought WA-Companion had some extra code for it.
Thanks for moving the issue here.
