### ISSUE TITLE
Adding popular zone/zone group IDs to the load condition's mouseover tooltip might be neat

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1151]
**Is your feature request related to a problem? Please describe.**
To provide zone ID / zone group IDs easier to users similar to how it's done for encounterIDs

**Describe the solution you'd like**
Simply adding these to either the zone Id / zone group Id tooltip:

Zone ID(s)

**Dungeons**
Freehold: 936
Kings' Rest: 1004
Siege of Boralus: 1162
The MOTHERLODE!!: 1010

Zone Group ID(s)

**Raids**
Uldir: 384
Battle of Dazar'alor: 396
Crucible of Storms: 393

**Dungeons**
Atal'Dazar: 275
Shrine of the Storm: 281
Temple of Sethraliss: 283
The Underrot: 282
Tol Dagor: 277
Waycrest Manor: 279

**Comment by InfusOnWoW** [comment]
I really dislike having to maintain a hardcoded list. Thusunless there's a way to automatically generate such a list, I don't think we would add this.

**Comment by emptyrivers** [comment]
Agreed

**Comment by oratory** [comment]
Couple random ideas on this:
1. Using `GetInstanceInfo()`, build a local-to-client list, over time as the player enters new dungeons.
2. Add support for a tooltip and make an API so that other people can make auras which add to the tooltip's content.

**Comment by mrbuds** [comment]
i think it's doable, from something caucese did to get list of last tier zone group id

```Lua
local raid = false -- change to true for dungeons
local instance_index = 1
local name
local instance_id
local instances = {}
repeat
   instance_id, name = EJ_GetInstanceByIndex(instance_index, raid)
   instance_index = instance_index + 1
   if instance_id then instances[name] = true end
until not instance_id
for i=1,2000 do
   local mapInfo = C_Map.GetMapInfo(i)
   if mapInfo
   and mapInfo.name and instances[mapInfo.name]
   and mapInfo.mapID and C_Map.GetMapGroupID(mapInfo.mapID)
   then
      -- print(mapInfo.name.." : "..C_Map.GetMapGroupID(mapInfo.mapID))
      instances[mapInfo.name] = C_Map.GetMapGroupID(mapInfo.mapID)
   end
end
for k,v in pairs(instances) do
   if v ~= true then
      print(k,v)
   end
end
```
![prev](https://i.imgur.com/9sO5OLg.png)


still looking how to do it for zone ids...
still have to check for

**Comment by InfusOnWoW** [comment]
Iterating over all map ids and checking if anything has the same name as the dungeon? That doesn't feel very good to me.

**Comment by mrbuds** [comment]
i have updated the algorithm to not iterate over all ids

**Comment by InfusOnWoW** [comment]
Right, that's much better and somewhat on par with get_encounters_list()
