### ISSUE TITLE
Master of the Elements Buff not working properly from template in WeakAuras 2

### ISSUE THREAD

**Issue by NicholasWSmith** [WeakAuras/WeakAuras2#1153]
**Describe the bug**
When making a weak aura from a template, I try to get an icon to show the Master of the Elements uptime. When setting the trigger to in combat, and being in combat, the weak aura does not display and does not change when the buff is active. I did the same thing with a different talent, Storm Keeper, and it works. 

**To Reproduce**
1. Create a weak aura icon from template for the Master of the Elements Elemental Shaman Talent.
2. Set condition to In Combat. 
3. Enter combat and gain the Master of the elements buff.
4. The weakaura does not appear. 

**Screenshots**

![image](https://user-images.githubusercontent.com/9642815/52180747-3e0cc200-27b8-11e9-8df8-1aabfcd2a5f1.png)

![image](https://user-images.githubusercontent.com/9642815/52180749-41a04900-27b8-11e9-99a7-caf797e88f46.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, as the other weak auras for my class are working. 

**Which version of WeakAuras are you using?**
2.11.3

``` !nwv3YTQnq4NMEzoJb7Z50CPJdU2ZyJtSiDMEJILbbOjcjgKWoKl8ZE3vcmUz6Pn2mGy1(Z3U7NwOb0ekrqJdM(JjH)Ksmus43cc(wiLurjz4fOGL)Un8jTqzPKfrXjr79YcwQvwI4do4aWIuTwMPpRsGTIuSJsEg9bkPBxEUHBPlV73dMCp(ly69F)(zHZO53nBgLWuPL6Mp5)bNrolQ5OBsBnwDf67xQZywoL02)Cq1OSco9iKpPAfAHTruuWBmqke7s0Eb4YwdpMv5CmRTHPG196rc)XKFoDgfWc4ZDkzhQe)ehr3kotAlbZvc4TAjRdCN7TO3fgRbdFfZMwYnKs95DkOKcpNlpZ6GARPMlLRZWibMpeuyPP9Olcp1WZfVtjKNI2SzumPn3j(1fZjjVssMVhZMoOW4qpu7Z4hbDsCIwfT5PLVSb9BRAmNTOawQvCIN4fUvNbTU7cMG74AYydLsw2i(4YHNBzznml7YHeiAVX51Zb8NA3ZScnMOgUm)FJvSaCctOQCvS1XK1pgrjfs95fAPUXxLXRq39PU7ZW79OiO3PpSljz329R)Jvj3aVLswbuk39sYM1XGJl5IIsl4HjitqLlk8LuPML13PFnvYmgSnAqYkiSQvAfd1emRqHgHQqYDCG)X(wMetLB047FsdV)hvGqwnF784pPLdj6QJmlcf8nxK7x3hLhCiYksFR7rO1cLAfwRD1LBouH9rTYhtlRX6Z5CHsyk9RfifDidWI3VST4znhBTwTA3jEdWQV2j)FBymLOYJYBGcjRh6V6jPgo0zaAFpNvPvC02kaoFDTVMCFn9rS1AHbl7Qhkv2BgB9zAudVa0YxkCdqiV3p3kEAWukmgkdo47yzxPI(rFWCmsEdCwgMVahxC8N0VitNs(nJVjCTj)Rpc6IlyrTlZ0in4dTUIgdysaZQ3YmwEZLd68lhSL8lhIKCSBBUsa(sGkCGMDCy08sm78LgYI9rraXMjRl9PAlg61DD8zp)8B)1j87jkGez8JIvaIum5FccqosCqGJTpon4O7uBMyOh5NuddqtFdxCIjB9hjpXAeiUqMAEoaVRJZ9qpTKPk4JUWBj4(6gDnVX2ncmlM8xv5HBvX1kWE(4()NfSrl9TCB))RFucDFg3WSiNfXdS3jW4zHO90)o ```

**Comment by NicholasWSmith** [comment]
Discovered the problem. When the Weak Aura is created, it is automatically setting the `Talent Selected` to `Call the Thunder` instead of `Master of the Elements`.

![image](https://user-images.githubusercontent.com/9642815/52180806-bffceb00-27b8-11e9-9aa5-c1ad1ffbf80c.png)

This may be caused from when the elemental shaman talents were modified in 8.1, and their talent ID's were changed: This is just speculation though.

**Comment by InfusOnWoW** [comment]
I think we fixed those issues for the next release.
