### ISSUE TITLE
Status=cast, unit=target and interruptible checked does not refresh on target change

### ISSUE THREAD

**Issue by Saxayone** [WeakAuras/WeakAuras2#1155]
**Describe the bug**
Using an interrupt weakaura with the status cast, unit target and interruptible checked does not refresh when changing targets.

**To Reproduce**
Target TargetA which is casting an interruptible spell, 
Switch to TargetB which is not casting anything or casting an non-interruptible spell.
Trigger will still be active.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
2.11.3

**Was it working in a previous version? If yes, which was the last good one?**
Yes, 2.11.2

**Comment by mrbuds** [comment]
I noticed something was wrong but didn't identified how to reproduce, i'll investigate thanks
