### ISSUE TITLE
Weird eq slot behavior when loading game

### ISSUE THREAD

**Issue by nullValueReturned** [WeakAuras/WeakAuras2#1166]
**Describe the bug**

It's just a trinket slot 1 (eq slot) cd tracker. Super randomly it wont load when i log into the game, but if i open and close WAs it works normally (see screenshots). Using the trinket also makes it behave as intended
**Do you have an error log of what happened?**
it doesn't generate errors

**To Reproduce**
Simply exiting and rebooting wow. Re-logging wont reproduce it

**Screenshots**
https://gyazo.com/77cb8dd1744ab27c3969631757c90c43
me opening and closing WA to make it load.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

2.11.3
**Was it working in a previous version? If yes, which was the last good one?**

i don't quite remember when i made the WA, but it was during legion. I think it started to not work properly around early BFA
**Additional context**
I first went to the "help" channel on discord and got 
"That Aura contains a lot of old info, looks like it's an Aura that's been duplicated and altered many times. 
Try remaking the simple trigger from scratch and if that solves the issue then make a ticket, posting the old and new wago links so the devs can see which piece of older info might be causing it.
(this is just a guess as to why, since nothing else is jumping out at me as looking odd in that wago link.)" as a response from Asakawa.

Thanks for making WAs. It's awesome

``` HERE ```
https://wago.io/eJQs5Z8tG - WA in question

**Comment by nullValueReturned** [comment]
i have remade the WA as asakawa recommended. It is still bugged
https://wago.io/y7awZ9mUg new WA (essentially the same)

**Comment by nullValueReturned** [comment]
If there is anything i can do to help discover any bug, either with my setup or WAs, let me know.

**Comment by InfusOnWoW** [comment]
I've just pushed a fix for this for the next release.

I'm not 100% sure that this is the right fix, since I couldn't reproduce it. But I think my guess is based on a bit of experience. If the next release doesn't fix it, please comment again and I'll take another look at the problem.
