### ISSUE TITLE
Blue circular Halo around my characters

### ISSUE THREAD

**Issue by mbarbone1369** [WeakAuras/WeakAuras2#1167]
**Describe the bug**

1) There is this Blue circular halo around my characters when I am not in a vehicle, or have Weak Auras 2 open.

2) Also, I get an error, when I open WA --  attempt to index global 'aura_env' (a nil value)

3) In chat window, there are print statements of "true" and "false" when I switch between ground and in vehicle, or open WA.

**Screenshots**

[Screen Cap](https://1drv.ms/u/s!AkIMejhywgcrgvFgskaPEki85ltVrQ)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes. Weak Auras -- Latest version updated from Twitch yesterday, is when this started. I tried adding addons, until this started happening and just Weak Auras, and happens whenever WA is enabled.

**Which version of WeakAuras are you using?**

Version 2.11.3

**Was it working in a previous version? If yes, which was the last good one?**

Yes, was working prior to this update.

**Comment by emptyrivers** [comment]
We don’t have any code which will do that in the codebase. You have an aura installed which is misbehaving.

**Comment by mbarbone1369** [comment]
I disabled all other addons and it happened, as well.

 

And, I just re-installed  the previous version 2.11.2, and everything is back to normal. 

So, what was changed that would make one of my auras misbehave ?  I also noticed after I posted, some of my other auras were not working as well.  But, now after reinstalling previous version, all is back to normal.

 

Thank you
