### ISSUE TITLE
Horizontally centered Dynamic group with custom texts have wrong width

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1175]
**Describe the bug**
@Levjing on Discord asked about an issue with a dynamic group with custom texts that have wrong width on login
https://wago.io/LH25JcV4m or https://wago.io/OuKuGX7Jk if it expires

![img](https://i.imgur.com/p3iYEJt.png)

instead of

![img](https://i.imgur.com/QwKmseG.png)

editing width of all element from 210px to 211px fix the display

I tried with @emptyrivers new dynamic group branch but had same display, and it bugged weakaurasoptions

**Comment by emptyrivers** [comment]
Texts don't have widths (which has been a source of bugs before...). What exactly are you editing when you say this?

> editing width of all element from 210px to 211px fix the display

**Comment by emptyrivers** [comment]
Ah, this is the fixed width option. Well, I have no idea how that works :)

**Comment by emptyrivers** [comment]
Until somebody who knows that bit of the codebase well comes along, try the Automatic width setting, and use the spacing in the group tab. That seems to continue to work correctly.

**Comment by InfusOnWoW** [comment]
This should be fixed for the next realease-
