### ISSUE TITLE
Progress bar doesn't show in-text icons (%i) when bar's own icon is disabled

### ISSUE THREAD

**Issue by twsx** [WeakAuras/WeakAuras2#1176]
**Describe the bug**
Progress bar that contains %i in one of its texts stops showing the icon after the bar's own icon has been disabled **and** the UI has been reloaded.

**To Reproduce**
1. Progress Bar
2. Trigger: Status > Cast > Player
3. Add %i to a text
4. Remove the bar's own icon
5. Reload UI
6. Cast a spell, Icon doesn't display

**Screenshots**
https://imgur.com/Yp2lgoo

**Which version of WeakAuras are you using?**
2.11.3

```!nA12Yjooq0VM5rsH5YeMhHeyHQigwKZSZS1uIiSKnAXyrjjNfYd5BF7ULDGKzRuujLVi3QVC6tFe8iEcNTNZK4)WJE1r)KcrUJZw8yY8zXJ5mNxKUZX0VO4XrD4mrLFRXU4GxBkDWM8nMuVXytPIZoTilZP8842WoktHDS0OlbBVBCCY4vC2gJvQS3zkmwWjXrOLXDORDPR9GR3C7x73(RTBpOt7BV9BdWyznEHxLajkeQfycQtnL8nH7RtVWHrKdJihgromIYwvr2htgX7YKOFltOnkvoHVYcHhdN7GWUluL)KkZcJGaXkNADAHW54JcV4oOsXNP7GboDzEHc9oBFvHxtGi4)WMoBaJnD4ddJ)GvoStK8(fHL969Q)NI43QEiHgk)NkNxjvYh0eYzv5qZm50bf2ETcaoAAQ4NrwrLf(2q7EJ9unnXGa4W0uTuv6ffV(0sRYHVKE6ngbzZeR(LxF6pResa6eV(ussn4r(gt7p3xIIdBfy2ZGgCMopW5WC4kk3l6s)G6s0cRqseuYpyKyz9yYIGddS8oGzERopxzDbVN82c0JeqbLOVc47UQnQNH0MvLLPpYzRVBilznlz4kWujsxGaXzq6tMbKoHl0hwxvQ9ejPS(tWSLH4jffZK1dxKrSdfItq0zLI9QMpaEqSXzSBOYy05ubqpkvylhpFoYB3a5wO9oD88LtECEWXNRjIcjs96NvjHfjFg3kQn(fyyrzlffFhqeSAIJIWXA9(qXLqOH1ZVOIxxJskOPbLsnOvIIdGd3l0LxV1z6sTB7vBVhhOt3jTMdZkNyrYvnlMajVoD3P7BAmWxQ0G(3YKT7M)TFMp7htGWODiGJQmZvzG)E9j8VVOF9PwWTYAEl6Uab(JAMij7AzNJkuLYAM493)XjuXrmfdQLnvZO6DM0myod7pzIu1VqYfOEmsy)1JZAD(TwmAIJaMCRPQu(5sVu61e1gH8gu9t36KbDBhniAq7(D62R)G(94zT639S7WSp80yzoK7rW0U(OQO5CIjwGIhiRS7wnECCJ5HHZUbEA4SN3ODxssi(Q23WQPJfqXeoB1S)ykSPuaBn7rW7XdsunNvvFNq1)sl9BHARrSyQsNVfaGUTBYKr14aNnQq)YlcReu1mgqpgwcjtSTRuqmq4F0zT0RGqqSPZQqVtS6S81uTe0gHZ)g)D80RlyRROuL9LdbclGkiAcIxGYlgf2)gkUErdQvBGUX26cStFe5EgMXPd4oEXr4gRgvMdsztxSA2FVioz4CsswQV4Nc8IXSpWviKQXfb2oN15MOOBGw4ZWs96GRY)V```

**Comment by InfusOnWoW** [comment]
I fixed that for the next release.
