### ISSUE TITLE
Add scaling/hook positioning of 'Action Button Glow'

### ISSUE THREAD

**Issue by Jalopyy** [WeakAuras/WeakAuras2#1181]
Currently the Action Button Glow is hooked to the inside of the icon. Would be nice if it could be made so I could (outside of LUA or making a 2nd blank icon that overlays the first) making the shine effect be more on the edge/outside of the aura so it surrounds it better,  as the way it is default sometimes encroaches on the text settings.

IE

https://i.imgur.com/ayO9Qaj.jpg - Default position of the shine
https://i.imgur.com/JQaTzYS.jpg - How it looks using a 2nd aura entirely that is overlaid on top of the original one so the shine part isn't almost clipping into the timer text.

I'm pretty sure this kind of manipulation for the activation shine used to exist, but Blizz removed or changed something about it.

**Comment by InfusOnWoW** [comment]
The glow effect is provided by a library, we only tell the library to activate glow on a specific icon.
