### ISSUE TITLE
Collapse Child Groups

### ISSUE THREAD

**Issue by Colorado4Wheeler** [WeakAuras/WeakAuras2#1184]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
I would like to see the ability to collapse all child groups under the Loaded and Not Loaded sections so that you could easily look for "root items" without having to scroll through potentially dozens or even hundreds of icons.

**Describe alternatives you've considered**
I've used the search feature but I don't always remember what something may be called and even if I remember the name of the group that name doesn't match the icons in that group so they get filtered out anyway.

**Additional context**
None.

**Comment by emptyrivers** [comment]
So, currently, whether or not a group is expanded in the options pane is controlled by a setting which is persisted in the aura data itself. In my opinion this is just magic, and likely contributed to the situation that you now find yourself in.

Would anybody object if I removed that value from the aura data, and just made the collapsed state of groups in WeakAurasOptions a transient value, which resets to being collapsed when you reload your UI?

**Comment by emptyrivers** [comment]
This would also make it’s collapsed state consistent with newer collapse buttons elsewhere in the UI, which are also transient.

**Comment by InfusOnWoW** [comment]
yeah that's fine for me

**Comment by Stanzilla** [comment]
Same

**Comment by mrbuds** [comment]
Fine for me as well

**Comment by emptyrivers** [comment]
This has been fixed in the latest beta.
