### ISSUE TITLE
It would be neat if converting an icon to progress-bar resets width/height

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1188]
**Is your feature request related to a problem? Please describe.**
Converting an icon to a progress bar makes it still seem like it's an icon.
It would be neat if converting resets the width/heigth to the values that are picked when creating that region from scratch.

I think it's confusing for users if it looks like an icon after converting

**Describe the solution you'd like**
simply resetting width/height when converting an aura to a different region.
the values should probably equal the ones when creating the region from scratch

**Additional context**
https://i.gyazo.com/aec4b1d8cb017cca5ed07760b545b33f.gif

**Comment by InfusOnWoW** [comment]
Yes, that's unfourtunate, but the point of the conversion is to preserve as many settings as possible. (Although the code doesn't do a good job of that.)

I don't think adding complexity to treat a icon -> progress bar conversion special would be a good idea.
