### ISSUE TITLE
WeakAuras 2 tooltips based on instant ability not the real one

### ISSUE THREAD

**Issue by Sikim2** [WeakAuras/WeakAuras2#1190]
Dear reader

for handling some sort of buffs and debuffs for unit "player", a TSU icon was created for this matter. All things went right( positioning, labeling and etc. ) but the clones do not trigger the right tool-tips in the game. one example is shown in attachments for shaman enhancement. "Roiling Storm" is an Azerite Power Ability which is introduced newly in the recent updates. As you can see in image 1, this is real tool-tip for this ability but in image 2(result of coding in WA) it is shown the "Instant" type of this ability with its based value(s)( 63 not 13040 ). What I'm trying to do is to make tool-tips not based on their dependent-abilities but based on what the results of abilities are.

Any Suggestions?

Highly 
![1](https://user-images.githubusercontent.com/47757629/52973268-53661c80-3372-11e9-9405-58b284384dbd.png)
![2](https://user-images.githubusercontent.com/47757629/52973270-53feb300-3372-11e9-8dca-2ab1ad20bc8d.png)

Regards

**Comment by InfusOnWoW** [comment]
This isn't a help forum, but a bug/feature tracker, thus this is the wrong place to ask questions.

Two quick hints though:
Your tooltip must come from the buff not the spell.
The processing of the tooltip is in GenericTrigger.SetToolTip, and you want't the code path that calls SetUnitBuff

**Comment by Sikim2** [comment]
My apologies for asking this issue in this forum
and many thanks for your guide
