### ISSUE TITLE
Cooldown Progress (Spell) not showing when ready

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1191]
**Describe the bug**
- new icon aura
- status > cooldown progress (spell) > spell = bloodthirst > show="not on cooldown"
use BT > BT icon hide > use any ability just before BT get ready > BT icon doesn't show

![preview](https://i.imgur.com/N1FbkXP.gif)
```
!nw1xVPTou8pntA3hMutOARVwOHBr32adNonThm4KCsWRo2r2oqHh6N9DSDcWTRBcPOeZ5)NF)o(anIMrjCAA0OpFvumLyOK7GTusdLu6EqTw4fB8cfxAPKjjPzjldYIMQKwc)aGEJEwOuIs1ozgQkrYYfqjDmLSFEvLbS00ROeMSyJs)Mqn4hzhVfCEu0zSQgxyEQTKzbkPR)7GPjL1anhR7cL05rNbQfQDtucL2lxAbTKj(gOnC0K0Oik5zaAV10cf2Lmlx5SJj5nUZsxBASmT1DOSt7fUYUhliIbWSuI4s4NsLeOy53W4Yl36kUKB2CX2JEucgM1zRVtp1Ezy34FI9Vh5FFT7TTNw6X3XZZYM)4Yz)79dCOJVMky1y2M)u2dZstOKnaVEdYoF(Ah8kR41ygqVfkMN8DaM7BtNWY9QqLfcMX8BsnUrH3ief)Yzdagqu92jjnVUg5PqJLDuG7iYRRy5gLo)rvPF2OgKGMxq2O2nxIXZ)DjWk3Jwl5yCBfS9O3i(L3vvL5r17tEyX0NEyaKrM22HGGPlh2c4mmAi)fkz1KBjzRiz3USp3(iIzvYAatax8oGvF)K4RRxOv1AWyED9hjTGq8pNI7cn4JlzrYdyY1at4njfdhYpcLQ0UHRn2q2mh1n2J7cXSY(SEsvA8OBUjY1S9vcRZQonvrjrHGz1SIN7VBS6)JAJDrStEgo)xqvpfYkS8TqwWbpvK(PORgg4INGZv4THgF9mlLm7UKWeBa9Z7SwLC(wqJut)m6folhFb2vCHxlEVPFnuJGwOm9ltCWjUIAERdm7b)DCKMc3qoEnkS2lgfXeTByU847y3DvF2OKpyoZEkzQMF411FTJvImf711ziUxPrkfh4rb(iCqPAclkDK64E)Xq1ILhUoESFnfV4593nW395lEyJB(Ww2PUyh6mYKLjjPbAm0vhx2D(QjRBXj3oCDUZLXeXpF8h)3HrF)llCAro0ah7X)CJ5vF2Fc42XXpdshwKp0JrV3ieEAlclxh74q6Vc
```

**Comment by Thontor** [comment]
I'm having the same issue

**Comment by Micrologist** [comment]
Just to add to this: This bug works both ways. If you add a new icon for a spell and trigger it by show="on cooldown" it shows as long as you keep casting on GCD.

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/GenericTrigger.lua#L1457

If gcd is "active" all calls to HandleSpell made by WeakAuras.CheckSpellCooldown return false and duration+expirationTime are not updated
I have not found yet the right way to fix it

**Comment by emptyrivers** [comment]
2.11.5 contains a fix for this issue.
