### ISSUE TITLE
Add an option for group buff/debuff default trigger to only check/return information about members in the same instance

### ISSUE THREAD

**Issue by Pewtro** [WeakAuras/WeakAuras2#1193]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to track raid-wide buffs/debuffs for dispelling/ready checks and I can't trust it 100% because it's also returning information about people outside the instance (generally inside group 5-8) 

**Describe the solution you'd like**
A tickbox like "Fetch unaffected/affected names"

**Describe alternatives you've considered**
A snippet that does this.

**Comment by emptyrivers** [comment]
“Fetch affected/unaffected names”? What would that option do, and how would it solve the issue you’re having?

**Comment by Pewtro** [comment]
“Fetch affected/unaffected names” is an existing tickbox, was merely an example. 

The option would filter out anyone in the group/raid not in the same instance as me. 

Example:

Scanning for lack of debuffs in the raid

Person1 is in Group3 is missing the debuff
Person2 is in Group 5 and is not in the instance and is therefore also missing the debuff

Currently this trigger will return both Person1 and Person2, but I'm only interested in Person1 since that will allow me to apply the debuff to them. (Think Shadow-Touched on Opulence, or a raidwide buff like Battle-Shout etc)
![image](https://user-images.githubusercontent.com/29204244/53111934-5e6da800-353e-11e9-9e47-063883d7e7ea.png)

**Comment by emptyrivers** [comment]
Ah, I thought you were suggesting that this option be implemented with the name “Fetch affected/unaffected names”

**Comment by InfusOnWoW** [comment]
I don't think there's a good api for checking if a unit is in the same instance, and afaik there's no event on units entering/leaving the instance. So I don't see how we could easily add that.

**Comment by emptyrivers** [comment]
The 4th value of UnitPosition provides the necessary information.

**Comment by InfusOnWoW** [comment]
Hmm, right. Is there any event though? The only one I saw in my tests was UNIT_PHASE, which doesn't sound like it should fire all the time, thus we would need to continuously check this.

**Comment by emptyrivers** [comment]
So, I took a look at a few other addons which handle this (namely, bigwigs). They weren't very helpful, largely due to different use cases. BigWigs simply checks at the start of a boss encounter to see which raid units have the same instanceID (4th value of UnitPosition) as the player.

**Comment by InfusOnWoW** [comment]
Since it appears there's no straight forward way to implement this, I don't think we should add this.

Instead this might become possible after looking at https://github.com/WeakAuras/WeakAuras2/issues/1193

**Comment by emptyrivers** [comment]
Unless I’m mistaken, you just linked to this issue. Did you mean to link to a different issue?

**Comment by InfusOnWoW** [comment]
ah yeah meant https://github.com/WeakAuras/WeakAuras2/issues/937

**Comment by emptyrivers** [comment]
Ah, that makes more sense!
