### ISSUE TITLE
Using %{p} in Display Text does not display Time Precision options.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1196]
**Describe the bug**

Using `%{p}` in Display Text does not make the Time Precision options appear like using `%p` does, despite being the same value.

**Do you have an error log of what happened?**
 
N/A

**To Reproduce**
 
1. Make any Weak Aura capable of having a Display Text (Text aura used in this example).
2. Observe intended behavior as the Default Text box defaults to `%p`.
3. Replace `%p` with `%{p}` and observe as the Time Precision settings disappear.

**Screenshots**

Bug apparent: https://i.imgur.com/ql67aDV.png
Intended appearance: https://i.imgur.com/qDi1L7l.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes. Tested with only the 5 official addons enabled.

**Which version of WeakAuras are you using?**

2.11.5

**Was it working in a previous version? If yes, which was the last good one?**

No.

**Additional context**

It's possible that this affects more variables than simply `%p` but I do not know what everything else can change.

**Comment by InfusOnWoW** [comment]
This should be fixed now in the latest alpha.
