### ISSUE TITLE
UIParent:Hide() results in any model-type aura you have becoming invisible

### ISSUE THREAD

**Issue by Sectimus** [WeakAuras/WeakAuras2#1199]
**What steps will reproduce the problem?**
Create a model aura > alt+z > alt+z > model aura is gone until you > /wa > /wa

**What is the expected output? What do you see instead?**
A model of arthas staying on the screen
A model of arthas not re-appearing on the screen

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.11.3

**Was it working in a previous version? If yes, which was the last good one?**
Not sure

**Do you have an error log of what happened?** 
No error given

**Please provide any additional information below:**
This bug also triggers occasionally on PLAYER_ENTERING_WORLD

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 
It is in every single Model aura I use

**In case you do know which aura is problematic, please export the string and paste it below.**

Just create a Model aura (it defaults to Arthas) and the bug will still occur.

**Comment by emptyrivers** [comment]
This is fixed in the latest beta release.
