### ISSUE TITLE
Add GCD to "is on cooldown" for conditions.

### ISSUE THREAD

**Issue by cdanek** [WeakAuras/WeakAuras2#1202]
![clipboard01](https://user-images.githubusercontent.com/21341843/53269870-e23ea600-369e-11e9-981e-d1e5a7d6f872.jpg)

For spells that are not on cooldown but ARE on GCD, the condition: ("On Cooldown" = True) is false (and in my opinion, should be true). 

This could likely be solved one of two ways, depending on how you think "on cooldown" should work:

1) Add a boolean for is on GCD to the "on cooldown" check, or
2) Add a conditional for "is on GCD"

**Comment by nullKomplex** [comment]
I disagree that it should be true when GCD is selected but it's not on CD and maybe instead should either have a Trigger option for On GCD or a global condition for GCD.

**Comment by InfusOnWoW** [comment]
If you really want that behaviour add a trigger for the gcd cooldown. I very much doubt that many people want to check for the gcd and thus this feels very much unnecessary to add to the cooldown progress trigger.
