### ISSUE TITLE
[Feature] Allowing 'trigger replacements' in Custom Messages.

### ISSUE THREAD

**Issue by Kruithne** [WeakAuras/WeakAuras2#121]
When you create a Custom Function for displaying text in a WeakAura, you're provided with a bunch of Trigger Replacements that you can use, such as %sourceName, %spellId and so on; they vary depending on the trigger.

It would be amazing if we could have these also available for the "Custom Message" action option, so we could set the message to something akin to "%spellName on %destName" without having to write custom triggers and call all sorts of functions to get it done.

**Comment by InfusOnWoW** [comment]
You don't need to write any custom triggers to use the text replacements, a custom action is enough

**Comment by Kruithne** [comment]
When looking over the Custom Action, I was unable to get any of that information. Could you elaborate on how I would achieve that?

**Comment by InfusOnWoW** [comment]
On the actions select custom and insert e.g.:
SendChatMessage(aura_env.state.sourceName .. "on" .. aura_env.state.destName, "YELL")

**Comment by InfusOnWoW** [comment]
Note that even with that, it's a valid feature request.

**Comment by Kruithne** [comment]
Thanks, I wasn't aware of the `state` variable contained in `aura_env`.

**Comment by Stanzilla** [comment]
implemented in https://github.com/WeakAuras/WeakAuras2/commit/e0013fee72ac9a44605605c1eba1e3c3fb679cc0
