### ISSUE TITLE
UnitIsAFK not able to target "player"

### ISSUE THREAD

**Issue by Borinius** [WeakAuras/WeakAuras2#1211]
**Describe the bug**
I have a afk screen weakaura that uses UnitIsAFK("player") to trigger a model of my character to show up on screen. But this recently stopped working with the new WA update.

**Do you have an error log of what happened?**
No errors are generated, tried the console command and the addons listed.

**To Reproduce**
1. Install afk screen weakaura
2. install weakaura version 2.11.5-1-g72951d3
3. login and type /afk and the model works
4. then install 2.11.5-5-gf29a283
5. repeat step 3 but the model doesn't work now. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes and it's still broken. 

**Which version of WeakAuras are you using?**
2.11.5-5-gf29a283 (broken)
2.11.5-1-g72951d3(working)

!TVv)tPTYA4)xCgNrN5yCZhB(OZC)bubLwf9AOho9E7nYkzbsnKqt2iA)b(B)(UBsGqiGyR6XEgA6aKn7NVVV7ZZt2D1r2PTJnb(G5yh7yRijllHpaFWG(kweftvh7ro2U8)d57wsV7CJchFCOFyeKqlzX)veFQk(uZPfscZRTBdJCPrhLveh7J89(XpirUt72om0N5bjf3J4t5fZ(Hl73pMYGcNxqNBDSFSqQr0bEHbTFCm1XEquyY48mA79dEDO7y3lmOV3G0Xs6ZEgD06UdGAUvya8zsKVJ9qgBC8ho8WjKbHsEHh26X)SbgpCs)dvCSPpmMe4sD59swK3Gb0O402P9See)u0Fjjrey0MCl9EAaZoPFFVhCSV54A2TVXUDTRHmkEIJ9zuIpB488EvevKx7RQF(5qYJP((nDJthJU0BHQk1KCw9ZVQXNHSKe4bpASp5rOhyhqgrZYnpV2ddNCzaupIVR1J5DpL)SKG59zMOQ9I)wsq6ZTj(G5GiUPDA2Ui0fS5hiJ45Le0Byy0vHE8bWX1B1U(1o2Wn0OaI)FcggWVbwgWlhthDpVxjlHKq8c6nIW4pfmaXmseJ)dxWyXt8MuBxmfCRWioZugWDqq7mI4fS55UVxGx8Wno)qj8Gy(An(00U29IO0G8OK8asmuNrGTf81egrecNAgAWtn1LyF811R3k1YfgexCqwSlXBmUplZYNWB5jbdUBsJGV8V)2Po23NBcv49x)(zw6JUSD7lV486nAN35Agi6BClnFu5L3SqM9djIzWmycxatH)ZrjWKW8wLWdjfrklMEA(xkzioS3sj6fKoVSC6rHWK8YjMetVPNpjoMpdkI0JUIMwDP0hF)4v0RC9GrrpiLhx6rPnv5u7N6AwE4XHukLi3iLWap8LJNBx518SP9HjmFpo8XLFU95nBvxmlIprSn9biJ72dYCsmlCu699fZVcd2B)PFCA30lV(t7(ziyO(dEXS492jDA8o7pTlBinyE(YV8dbe0PD5ZYN29FLw2wWnfk5sLz5uIOSKOGPD3Jxpfkb1pMU6CVZofYzG70pcFmhYUXb6wgMyvz4cBQGmLD6FGM2kqlMBx(8yxcJdbN9nyZd5Ge9645YbgRb3)CNsToa6kXqtbds7u5FNdyWiSK4NamVaQlpoxajFeqBrdOrE9QeeUeUTOUHM5QZR9L6xFtJZRDk0eNvR1P1pPmnqE)Cvbu7Lgx0mgWZkgsTFXybr81mFllkHwL3Df0s9gs7D3moSSVoEiHnT7f04yYaX4llDIWdMzuh6bej2mVravAjEO1oUwOJ2v07M(XNp11kyPMHXMIU6sJbNEepEKdwfYsjT4Qs6hkGIPbE3Tiq9qQ3GHaySHSKUQksgzQRPGnZkUOIEHXKxf8BLy1vIjVk4W1GR(cHCxn8SGJiC0Teg3CXVBmLb3X8f2VvGsZDjPAcna)WiVOOqHyYIcizce4BH(IRiEW(OZR36erSdq3ZO3SGtMN7Kiixn5HlGvI(1AUUxge)1ouYD1GiJ4VEb11J812P5m(R2FpHerVPZqpbi2pRqh7XqLrfUg3xBzpLBl2YQi(gmJ0R)J5ZlMiGKBPOQlPAAAPPJvvvkiDIZeXRK1Pbxw0plkLYAnsPkQWxiuQZjFQ((dU6QETbwKjGkOore4nd6m7xLLCUefUnFsMBNSHccn)DrakmG5sdzzatFTm00T4uyQBWRhW4dZ)wvemiXZ3vij4uk7u(nnd6hUozbcMI8IbLlWZVICvDJMFLsokA2(KkfpiWPxvXx9tMPqr0bROFvTuL1jzPYEujjmGUflDtvnfewdJu03kH59NeMTcxMjC53vAMFf9vQAsgwQY6gYYB1x9gRVsf)C1xTK06FzPvlqwdK0i4YceIyONrwVzAyGGhjfnfDdSHPScUGigb55RSkMpz1PHRBGpZw5ftft1sz3ePlQBG0fpFau0xW0VjQyYuLCZFaW5(37NlmPgmOam2Mm6OZ51xv6tYbmJba2Gbs9dJamU92zxju)DYQU9xATh0WgQquGfgRRyHWgzXcBjU3sCVL4(9bXTIMegBzAau3QytTTe3VHe3k43jlmYs6b2m2AldjfzDfzdKMmIVZFZyRt5LELPRVFY1Dqd)2zmCZxLfDWaJmL1KvL1mHjhpJfDqt41b)MFZyoSl37wEByTd95JbYyVI7WAJd4QOLvrQ6QggkwqeYAOmfnXnpuy3AlUrRijt9c)ZOG5hjzPAOG1SqYw6idZ5EJNElxFt5DlXD8IZ4UcAT3vuVlQkOsg38TRUszkVEeUvqVkcIghgbZN9y)NqOsVDvKTU3db1cGY044Xe(qq4bSp8ekC3Nc4Cu30HVf)CvNx5tgKqLgPKxKygmwtpwcfXdRINtgHvMtPTewD1a8vYEufS(R6g6Ug6n(4Gh3ZhcRID85Z2TkM6f57QKIw0zSRDBKhjGioUdvCwva045ypAa(QaAQIuvRm1CSQy63tO8qiUpF(zyj7CRC0INOKAr31mGpBjm6XPDtP)M2vzrAxruvPd0IwHGny6ul878tmXSoB0pegMzhPNduSKSSSmWytma)JRKqCEPtNxLV3cyDu(dtR2sCRlEYhsvcWj74bsaGrx58sNwTlq6B8Ci9zuLAF5VgDHP(FvS3cKGkgOYhpefZIifPeLLL2m)55dSzAHY4zfNZKsm6h9my01TqwyzdDDKMPr6gWJ)NjJ(A5AlWpxbLujI)1Y0xPWH1rLpNHC9m7PT(jzZ0QMpCMKAPuKJ4)7oWl8cmfah3o)VSeLeoYpytz8OL1TEkO)anJNVI3tE97g1sIk(1vuuu6uvcDwuCXlJqI0DPRq1SwV)IbkBIdTSGOfgWRnMDJooGp9b3l4XxoXs)wW9SKQmv8Q0LjZFTRT6YExOllvhwkHs2rZvxbyTq68JnJo8k(pPSRBFLKDPHwMkVSuNk0ZSmBEfIgY38bmcTScOnqOZm8)IICKK)vwBJtMCQ11QF)H7ynw89J6fr5R1h9qyI)qsSVxVH3bXfLUTW7i9d(AEkHXvPn6P0cnt7OQjwYaeFOiJeshHK0FHozf50c816FVD29SpS7f7SFg7q61cIPuvritesr1cPPaVs3p1rb4Tut0gSrcvjhQeZZMQSATmNV6lvXZADtwGfEfQ3wuPsv6(ELxkJN6KjEDZtpR9pZ(JVDX1Fd2v8Lxs93ZQNkTi7LiEkJvpBT2p2pKprA2kxBQAPyPAQHqgg6WBdMTcYL5IYi90rsQg6AAYwymwxFJwYEbd1OZU(JJS78DJRMu9QVxKtR6TWDPvFF1)TBuXr(VLXRdd0Od319WDFCnKqMQAY6QMggAyfztS2wsOTKqBjH2scTPKq)g93FxjoP1tcjEXU58qAidSLMLHUUHQXtXdzHLK1TGxXu3Ysr2AZ5HiAkFYx7o5ZNe)3dpeuT3lo5A8(KZ))d

**Comment by emptyrivers** [comment]
You are 8 revisions out of date. Please update to a current version (2.11.6 for release/beta branches, or 2.11.6-1-gaed85ea), and confirm that the issue persists.

**Comment by Borinius** [comment]
yeah it does, that is the reason I went back to find the faulty version.

**Comment by mrbuds** [comment]
This won't solve the issue but just a tip, do not use SetModel on your duration function, instead do this:
![preview](https://i.imgur.com/uW4kTUd.png)

**Comment by emptyrivers** [comment]
Ok thanks @Borinius. I just wanted to be sure.

**Comment by InfusOnWoW** [comment]
That's a nicely looking set of auras. 

I'll fix that for the next release, but do note that the next release will take a bit of time to release since we merged a bigger feature which will take a bit of time to test, so you might want to downgrade to 2.11.3 until 2.12 is out.

**Comment by emptyrivers** [comment]
Either that, or become an alpha tester :p

**Comment by InfusOnWoW** [comment]
That is, it's now fixed in the latest alpha.
