### ISSUE TITLE
SPELL_COOLDOWN_STARTED event doesn't exists anymore

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1212]
**Describe the bug**
I don't know if it has to be fixed, or if [documentation ](https://github.com/WeakAuras/WeakAuras2/wiki/Useful-Snippets#get-weakauras-to-help-you-track-cds) has to be updated but the event SPELL_COOLDOWN_STARTED is no longer triggered.

SPELL_CHARGES_CHANGED is triggered when a cooldown start or end, as intended
SPELL_COOLDOWN_READY is triggered as intended

For context, i wanted to make a simple TSU that check if purify/purge/.. is on cooldown or not after casting it, without using a separate cooldown trigger

**Comment by emptyrivers** [comment]
That's not really documentation, so much as it is "stuff we found when we didn't have much of an idea of what we were doing". At least, that's how I treated that page at first.

But I've updated the wiki page to reflect the current state of WeakAuras.

**Comment by emptyrivers** [comment]
To be clear, for anyone else who reads this, that wiki page is full of what amount to insane hacks to get things done. In addition to updating the snippet that @mrbuds mentioned, I've also removed the most dangerous ones (such as a snippet that I made years ago which would edit database data), and ones which are no longer relevant or which don't work anymore.
