### ISSUE TITLE
Smooth Progress

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#1213]
**Describe the bug**
Expect the bar to not produce a smooth progress animation when it first shows

**Do you have an error log of what happened?**
As you can see in this video the sky golem mount cast bar has a smooth progress animation applied to it. When the bar is shown the previous progress is used to start the smooth progress animation even though the bar was untriggered. The expected behaviour would have the bar's not progress smoothly when it is first shown.

**To Reproduce**
Have a bar hide when it's progress is some value, then show it when the progress is smaller than the value it was hidden at. 

**Screenshots**
https://www.twitch.tv/videos/388360542?t=28s

**Comment by InfusOnWoW** [comment]
This is fixed for the next release.
