### ISSUE TITLE
Sound que's no longer working as intended.

### ISSUE THREAD

**Issue by Danteyouuu** [WeakAuras/WeakAuras2#1214]
My sound ques no longer work for tigers fury with the last version I used so I had to downgrade.

!1EvBVjooq4)lvA11vAxkj8sBxP7daf2LULxeME7h2EHAsCaFeSJSDGL7d8B)MXjHeEPQN0Pt0cjtgpEMhpZZmXZXBQhH7n0PMRBDxpI2J4wXXPsnpYApsa(hOGH9lJ7yjxy8iD6oCA3jPYC6jfgc)VzGbQ7r8LYOa5wXu4rDf05rSaV2G4eTrUgf6rcte(gUuC9h3)4(xt)ej9Pr7FvT)1FF)R)Grx1krr1vuSfGI6FsH7MXeBQWd(ZmHfRvvX6BFPteJQAffzDsDzRNRbHzSp86RApA60rdM0)RFB6vFcua()uzovXVaRWeagSBuyOMz8695g31426nR1WPwT7CV3PPx4NR30Jqf(lLQtaOC0GSLhZqCGMyaTgfJXVgGvtzO554aQH5rsY)vf5rwAmX6VCZnBPlKv4YB(2UbD0vFO76BUhmNFUHiAdvzWlcKZwej36nhKjtebZ8xsfcgyQbuTHPYe7r6lG7cP(SxAfemsOF5aU)YawaN(cb1t)shQzatU1TICXcR5txFB05d5cUEPD)VGrLhz0XYTmL9YJmFxY4wt(UZjwFoADW45HukkzfdpirZWySJmsQSbklk8c5MUyUPhXPYaPkEPhzfJf3shZ8ntOaWHRKk4RXRfhHHMDWXfjwXWJCsa4ZOkZsfRz(sWXlEUEPIlwH(1Ak3AO3AfP3kKc2XG3X7x(VluWX4BzlloGxYZtbgAlK9xY8xzTPIVybCCdIjBOkowlclpMff9So9Mn0OeSU1AkilzbRWoPpl)GnBZhhr39F4OoMkmlzQSZ6lNDAJFzmtzoStgVHUfUu7YkeW0udcqiGoSMTIYCybNJfUhHflr899bHJ2rBT1XE008IypsopglaipwOymb87CqjlXMZNGp7F8iYUduB50A8W9VkKgK1sVKlGvcyM4mQYSNbwOJIbXFpfDn76R6nP1GUi91v)O1vvQuI4SsLRSR5aFxReJSda6eu6u264iWmxvI20QosA(gKQfUq6vit5(hZP3bnW1(vaVUgrA8IslhdZsYpjiZ)CKpo7WDyD61zoWNUeCxAJyrA2)EdlJZTBztGXL9R9pECcA65UVm4q(xwoX8YAXfBykTvL6OkLwVLbZK9HKtCBBSwQ9P9(oazgWVSMHCA9hs6)qxRPG4wRhRy(CnYJnSAM(NqiIUG953xICSxeDbWln65Pp1FiyULm(ILGB2SwLAnUVQtZ6o3vVXTwMMq(I0owrsQDKaGfEwmZmNAmr2igfiyWgH34hr1PDM4Ify52dtEU)dahzsKHNvOAxrQIquQKr2IPZ0aPSrf04ygNQGHgbiI7zYPHH8FzRLVK(LCSHoUfQG30UyN3WwY9tdoRtuAvUNy3aoSH(GKDNTLHP9PptE8M4cV5ONOaA1ZecBSsMeFQ8S8M0MHwMl8px731SFxpJElDgfltXulFoPZKUDhMLpCs(M7fZ3WDkDTZtmgPyeCABBkKLI(U(WHzgl1xMJDse0O)ipf1X5Gp8UgmL3m1N4qAk2gN7VA3dz9nXZUqmKHUaudfxEr(FXGR)Te4VXAhRnYR58iFi(OUmZlfbNw8yTkSc9h8Tt6jTt(((rahAM(ZhujWWT7FDkhAu9B69V2lrT7qNRIws5TYYQ)OZ1s18bibeSzlycMI7taA1rI0gCTI2s3PtvobNNQngpZtcdtHSV19PX9E(P8zqGrGmjG6caWY2usBQALEfmzdwuG134HNn(sRot3T2fJQahTEKm96Knc8(xhNrvb8(eCkKpIwJJLbqceoxk0hlY(KHWM7robjYicYEA7Srz6hKngTozUDhbIqOUhsTh39PNketscTIN1Pfz6mY0wtYaWJHS2PcHmfyWH89WUHdB46CBkcu6iqFbK(81KpUqPfMI2zyeEAu(mBKOfqySH9oU)fpgbOEKiAh68NDcmHrd29)d8xoF54v(2NnhYLm81SGYPpnExKpJYv)x2PnqOIgfL(crByttvZwvaipMTgfVKADUT8aZsVE3DBZAvRFFZ7DQ50011fFloOnxcwlUUZ3dUtx9UVVIu07gI4FL9oGd)C1knCCH)CREB1AWvfVPx3GfwscW1qCTVVLoRwthxNcLqJH0m9fwZvf9WninKlYh49pd

**Comment by mrbuds** [comment]
Please answer all the questions asked when you make the ticket

**Comment by InfusOnWoW** [comment]
I just tested that aura and it works with the latest version, from how the trigger setup looks like, this indeed appears to be the bug that was fixed with 2.11.6.
