### ISSUE TITLE
Expel Harm WA being displayed at 0 stacks, when trigger set to "stacks > 0"

### ISSUE THREAD

**Issue by krityan** [WeakAuras/WeakAuras2#1215]
**Describe the bug**
Created a Weakaura that tracked spell cooldown for expel harm, with a requirement that stacks are > 0. Icon renders regardless of stack number. During Uldir (exact patch to break this unknown) this would correctly hide the icon if I had no stacks of expel harm.

**Do you have an error log of what happened?**
No.

**To Reproduce**
1. New Icon
2. Trigger: status, cooldown progress (spell)
3. Expel Harm as spell
4. Stacks > 0 (or >= 1)

**Screenshots**
![image](https://user-images.githubusercontent.com/15201801/53654228-1983f880-3c45-11e9-8b26-ec76edbe898b.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Tested without other addons, behaviour continued.

**Which version of WeakAuras are you using?**
2.11.6

**Was it working in a previous version? If yes, which was the last good one?**
Last played during November when it worked fine, sadly can't be more specific.

**Additional context**
```
!nwvxVjoou0FnJ0UpmvKuOL5HUsTmbnOLj0ToDF0GjXK4Pg7iBhO0h43(EV2jbOD3vvcLpCU(6Z9Co3l0iAgLiOP3eF7WX3qjwkj(QOORGh3sjf4piah)vx8JAHYrjtssZsEkSw0uTYreVXPPXJPKCTuBG4tJ8)I9xV2FDiEf29HfB2y5oA6xJgsjmvEL28UeNR1Yc9EfzVOMtFawOX60BZGZ756cMJtjnT37cnPOKtxdfsUwH7OXYlL69t84bxx54gft(3CJvaHKgfrjVW513BR55UNyoHgJZYLBEhAk4wMRXGhheWPS()wLEU5FHVIr(AQKvc08INZMplnHsQ4IYkGrgoali1grjKCyJsnZt(qXSmxYS22kBjIzpV4xeIWkuLsGo(5I0)e0TgPt4tbKeFSNcbG37(okEzxUOdfgXwKuu(96ygh(qbYdWIlDhaLbylaUfqPeEvPvCCVBzc1Np6ncLWw9PJh2XRDwOObxdF1iklbzniiz9l0ZCvmtj36fpUIBe5Kk9(fk4aG73l3ZoaNHITLBd0oWyszk8o6sgn42yGOd5yPUMdqeeFYF0ViLaYwJIVJJInRXPrpZ6MnBY84(hjZFC6ZZdG5seasy72M06JpU6rJU0WT2JR(nccKFhtUacPwYoavfXWzsspejjVcpFC1pyMT9MJ2V9qBTmROTYA5vh4NTNOBkb8e2M1EOqaClELswo5Es2ss29p1sJodl)fFkBJ8rd3hj5XK5ZXS3OoX8EDQqy)vJk3j2bNktkHl(xYcH9tDbhhdmORHjEc0CaENTEkzwkz23tcDCbMCDJZPvl2Xnav02J9HEXPJVD03(2W4XdgEt0GXdVLU5RJU23Fo4Y(Z4prFC38fC2tIITwYlqoOF037BLn8sGrdW1plcneWeUf1it3kd7ffUQq7E)mH2zO4irzDfZ3NIvoAB9NgL8f7zXtjtnI3oU6VAyfGmYoUkdeQngq3HgaybFgEtR3I1DWw2cCWp)LAaEWS9u(E0piYF5W37CdThyCx5UUBk9um5HsJm5PKK0GEgkR(zeN3r7WbVcxNFObpYz2SBtMnsXI2JFfetlVVidvgyPXoG99I8zmposq0DOH(98ko4mHh2XKnHjC7ygbUf8eSOJoxaEQN4wDJjhBz7CQTQCftvYpLXqIcgJbxnYBn83V0CuBW5bUdD)Vxy0je8hbfoJ4eO6NCCgmiAqtU7U)B48WLh45)fPRBQDBlXh7IGN2bzBymcC6)8
```

**Comment by InfusOnWoW** [comment]
This should be fixed in the latest alpha.
