### ISSUE TITLE
Holy Shock weak aura doesn't update with Crusader's Might talent

### ISSUE THREAD

**Issue by grizzlysaurusrex** [WeakAuras/WeakAuras2#1218]
**Describe the bug**

Using a template weak aura for Holy Shock (holy paladin) in version 2.11.6, Holy Shock weak aura displays as on cooldown while action bar shows it available. This happens while running Crusader's Might talent if you Crusader Strike with low cooldown remaining on Holy Shock.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

1. Create template Holy Shock weak aura that always displays.
2. Select Crusaders Might talent.
3. Holy Shock to put it on cooldown
4. Crusader Strike with less than 2 seconds remaining on Holy Shock

**Screenshots**

https://imgur.com/a/wenQ8UY

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by InfusOnWoW** [comment]
Fixed to work as in 2.11.3.

**Comment by InfusOnWoW** [comment]
And I was wrong about how this worked in 2.11.3 and thus reverted the fix I made.

Fundamentally the api that wow is providing for spell cooldowns does not contain enough information while the cd is shorter than the gcd, because the gcd information is returned in that case.
