### ISSUE TITLE
Dynamic group horizontal alignment 

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1219]
**Describe the bug**
Dynamic group require migration for fixing alignment

![prev](https://i.imgur.com/pVawm6a.png)
top group = not aligned
bottom group = aligned after changing alignment to top, and back to center after that

[weakauras-140126336#2-20190301212229.zip](https://github.com/WeakAuras/WeakAuras2/files/2921559/weakauras-140126336.2-20190301212229.zip)

**Comment by emptyrivers** [comment]
Since this requires a migration, I don't want to start work on it until #1216 has been merged.

**Comment by emptyrivers** [comment]
unblocked!
