### ISSUE TITLE
Preserve Option Name and Option Key when changing Custom Option Type

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#1222]
**Is your feature request related to a problem? Please describe.**
At the moment when changing the type of custom option removes the variable and name given to it whereas the description remains the same. 
**Describe the solution you'd like**
I'd like to see a change that keeps the variable assigned to the custom option while keeping it's name too.

**Comment by emptyrivers** [comment]
This has been fixed in the latest alpha.
