### ISSUE TITLE
Condition Clusters

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1229]
As a continuation of https://github.com/WeakAuras/WeakAuras2/issues/957

I really dislike how some of our on/off Conditions look at the moment 

![image](https://user-images.githubusercontent.com/75278/53795035-66135080-3f31-11e9-8af6-d0afa7e72767.png)

That lonely checkbox really needs some label.

I could not find where I proposed it first, it might have been just on Discord, but I really think we should move to a cluster of options for things that can be clustered like `Glow`, `Offsets`, cooldown like we already do on the `Display` tab 

![image](https://user-images.githubusercontent.com/75278/52357188-f7c49680-2a35-11e9-9b7e-2684a3128d51.png)

This would end up looking something like this: 

![wow_2019-02-06_17-35-49_edit](https://user-images.githubusercontent.com/75278/52357481-876a4500-2a36-11e9-8d9e-e2d7a26ae3c7.jpg)

Problems with our current (newish) system of two dropdowns:

- too many dropdowns
- if you want to change two things about the first selection, you have to duplicate it, ending up with two "Glow" or whatever dropdowns
- `Visibility` is still a lonely checkbox with no label

![image](https://user-images.githubusercontent.com/75278/53795334-0c5f5600-3f32-11e9-936f-3b1952bdda91.png)

**Comment by InfusOnWoW** [comment]
The most common use case of glows imho is to configure it once in the main settings and then toggling it on/off via a condition. I don't think having to configure all those things every time a glow is toggled is good.

**Comment by Stanzilla** [comment]
Well you would not have to, you just could. If we use the collapse design + the advanced button design you made, the main option could just be on/off and when users click on advanced they get the full sheet. 

Also this is not only about glow.

**Comment by InfusOnWoW** [comment]
The collpased design doesn't realy solve that, because we would need a additional toggle for "apply color change" in addition to "color".

**Comment by emptyrivers** [comment]
We could do this, but in order for it to not be a loss of functionality, these “clusters” would need to be able to express that certain values aren’t specified, and shouldn’t be modified on this property change. The same concept as inherited attributes in css, I suppose.

**Comment by Stanzilla** [comment]
Oh thanks for adding that to the ticket, I totally forgot to do that after our discussion

**Comment by jec324** [comment]
I do think the biggest offender is glow like infus mentioned.  If rivers solution of inherited attributes is workable and simple enough I think that would be greatly useful moving forward.  If it's not though we could just work through the display tab.  

Right now most people just select "add glow" and move on to the conditions.  Within the properties there we could let users set all the defaults of the "12", yes twelve, properties for glow activity.  Essentially letting users preset the properties.  Then when they select Glow -> Use Preset it uses all the things they set.  

As part of the larger discussion I do think the drop downs are really important for this particular context of UX/UI.  The reasoning  is conditions form a series of logic chains and by selecting the dropdowns you're parsing and working through that chain in an organized manner.  I think this really helps the novice/moderate users a lot.  If we throw all the options on the screen like much of our existing display we're going to get a bit of overload and eye fatigue.  That's something I've been working on in the background and I have some stuff I've shown stan and ipse.  Maybe it's time I brought it out even though it's not quite finished.

**Comment by InfusOnWoW** [comment]
I think while the condition ui is not 100% ideal, the orthogonality of the various glow settings is now common knowledge and I think this is no longer something worth keeping open.
