### ISSUE TITLE
Auto-Clone for CooldownTriggers

### ISSUE THREAD

**Issue by Loqy0815** [WeakAuras/WeakAuras2#1232]
**Is your feature request related to a problem? Please describe.**
In order to track multiple Spell- or Item-Cooldowns, I have to duplicate and maintain multiple WeakAuras, while each of them shares almost the same properties (eg.: Style, Conditions etc)

**Describe the solution you'd like**
I'd love to be able to track multiple Spells with a single WeakAura and AutoClone enabled, just like we can do it for buff-tracking.

**Describe alternatives you've considered**
- having a new WA for each Spell to track:
works, but as mentioned, I feel like combining them into a single WA would make things a bit more organised. In particular when thinking about multiple chars/specs.
- writing a custom solution using a TSU:
would most likely get me what I'd like to have, and I feel like I'd be able to do it, but imho this would be a good feature to have included by default, as I see a lot of people out there using WeakAuras to track multiple spellcooldowns.

**Comment by InfusOnWoW** [comment]
I don't think there's much value in this and it would be pretty complex to implement.
