### ISSUE TITLE
MultipleDisplayTooltipMenu and MultipleDisplayTooltipDesc are duplicated.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1238]
How did this happen? 😂 

https://github.com/WeakAuras/WeakAuras2/blob/1c9851919d9221a9f7ba136561e26cb50aef8472/WeakAurasOptions/WeakAurasOptions.lua#L133-L274

https://github.com/WeakAuras/WeakAuras2/blob/1c9851919d9221a9f7ba136561e26cb50aef8472/WeakAurasOptions/WeakAurasOptions.lua#L1247-L1387

https://github.com/WeakAuras/WeakAuras2/blob/1c9851919d9221a9f7ba136561e26cb50aef8472/WeakAurasOptions/WeakAurasOptions.lua#L63-L73

https://github.com/WeakAuras/WeakAuras2/blob/1c9851919d9221a9f7ba136561e26cb50aef8472/WeakAurasOptions/WeakAurasOptions.lua#L352-L362

I believe that @mrbuds is the last person to touch any of these 2 (4?) functions, so I'll leave it to him to figure out which one is the correct version, and to delete the other.

**Comment by InfusOnWoW** [comment]
My commit fa75abcc7b618b93d416aaa3f0a6315a2ab486d8 for buff trigger 2 introduced the duplication, which is probably due to a error while rebasing.

**Comment by InfusOnWoW** [comment]
So I just extracted the various versions of those functions, that is two original from when the dupliation occured and the current state, and nothing was lost and it's safe to just remove the duplication. I'll put that up in a PR soon.

Note, that we did stumble upon this, but missed to investigate 3b55fd87b7f6cc0609d359fe3a117ddd5fc97703
