### ISSUE TITLE
trigger update text display

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#1245]
**Is your feature request related to a problem? Please describe.**
When switching to trigger update from every frame in display its not possible to see preview text while WeakAuras.IsOptionsOpen(). So when changing text settigns it's not possible to see what's changed.
**Describe the solution you'd like**
If it's possible i'd like to see it fire one "fake" trigger update event or some OnUpdate stuff to be able to see text and its positions
**Describe alternatives you've considered**
Don't see any other possible ways
**Additional context**
https://i.imgur.com/6BXoqB7.png
https://i.imgur.com/RJQbXR6.png

**Comment by emptyrivers** [comment]
That doesn't seem too unreasonable. Patches welcome!
