### ISSUE TITLE
totem trigger

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#1246]
**Is your feature request related to a problem? Please describe.**
Since totem API is bad i have to go custom to make it work the way i want to be possible of using it on multiple language clients. I'd like to see an additional field in the status - totem trigger
**Describe the solution you'd like**
Adding one more field for totem icon/texture
Not always possible to use totem number. As an example - elemental shaman. Index for one totem can be different depending on totem numbers
**Describe alternatives you've considered**
Bashing blizzard to change totem API
**Additional context**
https://i.imgur.com/FwgiJCv.png
https://i.imgur.com/pRKhh1v.png
https://i.imgur.com/YZkogxQ.png

**Comment by InfusOnWoW** [comment]
So looking at the existing trigger, you can enter a spell id in that field, and if the totem name is the same as the spell name that works.

I tried to find a totem where the spell that summons it does not match the name of the totem and didn't quickly find any, Can you provide a example of a totem where that would be a problem?

**Comment by InfusOnWoW** [comment]
Translit was unaware of how exactly the totem trigger works. So closing for now.
