### ISSUE TITLE
debuffType trigger bug when switching targets

### ISSUE THREAD

**Issue by SKSniperSK** [WeakAuras/WeakAuras2#1248]
Test WA: https://wago.io/2vV58rI7D
This WA should only trigger if the target has a buff with debuffType "magic".

When having no target and then switching to a target with no magic buff everything is fine, but when you switch from one target having a magic buff to another target without a magic buff it remains active (triggered) using the first (random?) buff it can find.
This way it triggers on things like mounts, resounding protection, challengers burden etc.

Assumption is that on changing targets if no (proper) debuffType is returned from any buff on the new target it somehow keeps the debuffType information from the last target.

**Comment by mrbuds** [comment]
i can confirm the bug

**Comment by emptyrivers** [comment]
This is fixed for the next release, thanks for the report.
