### ISSUE TITLE
WeakAuras2 no longer recognizes the new ElvUI nameplate system

### ISSUE THREAD

**Issue by anaseskyrider** [WeakAuras/WeakAuras2#1249]
When anchoring to the personal resource display via display settings, WA2 doesn't recognize ElvUI's new nameplate system. It's not registering as the personal resource display.

EDIT: It turns out I hadn't reloaded after re-enabling the nameplates, and that's what caused WA to not recognize it.

**Comment by anaseskyrider** [comment]
I did a lot more experimenting, and the results are as follows:

- On a fresh reload, weakauras will parent roughly accurately. If the options window is opened, they stop parenting correctly.
- The ElvUIPlayerNamePlateAnchor frame that WAs uses no longer exists.
- There is a new frame, ElvNP_Player, but it's only used for the static version of the player's nameplate. I recall that, before, you could only ever have the static player plate or the one that follows your character, but not both. Now, you can have both visible. I'm guessing that they simply reused and moved that frame with the old system, but now ElvNP_Player is used exclusively for the static plate.

**Comment by mrbuds** [comment]
How is called the one that follows your character?

**Comment by anaseskyrider** [comment]
I was bugging the ElvUI guys, asking if a replacement mobile frame existed. I couldn't find one, so I assumed it didn't exist. I found out a couple of minutes ago that Azriloka needs to fix some parenting stuff, and when he does, the new frame will be ElvNP_TargetClassPower.

The name confuses me, but he assured me that it was the frame for the mobile player nameplate.

**Comment by anaseskyrider** [comment]
Further communicating with Azil revealed that my suspicions about the frame name were correct. There seemed to be a misunderstanding. That frame was for the player's class power (combo points, arcane charges, etc) that you see above your target's nameplate in many nameplate addons.

Short and sweet, the results: The mobile player nameplate frame doesn't exist anymore. He'll be adding it back to ElvUI, though, with the same frame name. We have to wait for ElvUI to update for this WAs feature to work again. Nothing has to be done on this side.

**Comment by mrbuds** [comment]
I'm for keeping ticket open until it's fixed upstream to check there is no regression for weakauras

**Comment by InfusOnWoW** [comment]
I don't think we need to track elvui bugs in our bug tracker.

**Comment by InfusOnWoW** [comment]
Have the elvui maintainers done anything in the week since this was opened?

**Comment by mrbuds** [comment]
Azilroka confirmed on elvui's discord it was fixed.

**Comment by mrbuds** [comment]
@anaseskyrider can you test and confirm it's fine now ?

**Comment by anaseskyrider** [comment]
Sorry about not giving any updates. I had some issues with it parenting incorrectly, but it turned out that one of my weakauras was breaking it in ways I don't understand. Without that poorly-made WA, it works perfectly fine.
