### ISSUE TITLE
Custom Sounds

### ISSUE THREAD

**Issue by Imiona** [WeakAuras/WeakAuras2#125]
Since the old Wow Ace Forums are gone (wth^^), i must repost this Question. How can i add a custom (default) WOW Sound, for example this (http://www.wowhead.com/sound=11501/a-blcktmple-mothrsha-taunt01) when my Trinket proccs. There was a good Guide on WoW Ace but as i said, its gone, so i have to ask this question here.

Thank you

**Comment by InfusOnWoW** [comment]
By selectiong "Sound by Kit ID" and entering the id. In your case that is 11501.

Do note though, that this is not a help forum. This is for bug reports.
