### ISSUE TITLE
Unused settings are affecting aura function.

### ISSUE THREAD

**Issue by jackshlin** [WeakAuras/WeakAuras2#1251]
**What steps will reproduce the problem?**
1. Use a potion. The Aura will hide, as expected.
2. Get into combat. Stay in combat and wait for the potion to come off CD.
3. Still in combat, observe that the aura does not show up.
4. Get out of combat. The aura still does not show up.
5. Type "/wa" to open up WeakAuras window. Close it.
6. Observe that the aura shows up again.

**What is the expected output? What do you see instead?**
I expect to see the aura show up during # 3 above, when potion comes off CD.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did not, but I tested an identical aura that I created clean and verified that it's working as intended. So, one aura works and ther other doesn't and the difference is old and unused settings.

**Which version of WeakAuras are you using?**
2.11.6

**Was it working in a previous version? If yes, which was the last good one?**
As far as I know, it never worked.

**Do you have an error log of what happened?** 
No error log popped up.

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 
Pasted aura below.

**In case you do know which aura is problematic, please export the string and paste it below.**

!nAvutnUnq4Fn3C39qbCGch302zGqsVCeCsJm39MsKTLDupzjxj5ecpKF7DxjNGdhTWaJDK0UR2VVD1NmnIMqjcA8LNFXVEApkPIsYPelL07OOOJohhbgSzsrHL7OXNatWTmxJH540ukXXFWfnvluok56jjjtUJsyQSLAZqdRINSPMtjK(ZgmigxquXCcTcJzft4F78MO0k4zogxy95HjT8mTk3sHyBDmJ7TBEHqjSlFZ2dE8doV(kBnpZndTbXMLllAHw)bXjdMrjzATmxVwniV0d)DJtaAyGILk550RXSvK9Jn30UD75PHAmwdnIh3U4VAy5WYSTlsGSSuQxh4Q0gNtRMSIBKSnuc82IHioIsEOtvaDaJBJrsjlDUA7Np(41Ss9rc9X9(NB)2PZllYpg8YWlHaecUaamIRkiSus0rNCeekwJdkxtQXu1cuMlKT9WSDOKvcndtUpz8O4bDw4LHXEusepYHC(8wpEglUKlkxc448ZqguvikdBBJLJ4QVwQni4wlYDldM908jixG)3Z)8u)ZZWNTjEuFibGMRkoUNJIjJUzxM)IReAxFEHUX60vyz9(6CSxN00(gmJBum532xzIA33ona(DB340o8wGy6biIjRxY811h16kFrTapYqCiF6xWxUU2xH0h0e1wws(YO(3EyTHsEx9EW(Q0vUWwdTzJY8440ZU48t9vKCrNMHNOcidBuz4sF4JB)62fH)mCqoqTDX7jlzWzHcTP69B)kxLdM8I)90XgOcdTLT8fa4Ptq1if207pEj1mV(tUOOqK1iDB8khWpe(Cdfgqc95twWY2lZ0DEUkt3G1pbiYf9PZU03ZnV70inZKydYZD2WY(5DcDxXXJtOGbiFGwyfQsjhj79gd)(6GhzsM12XkY0zJgq6e3Dta0Y3VA2SrtMTZvJwY76zYvX32Xp)WwtdyO3lMVpIIHPirxA0n1)Kn1RQFzkawlqS(8hKyDHoKDIZDfEdzHruwcfZqxi4dWYHPWbLCfq5zKL61tqzj)7zCw(Mo(69csAHJxfdhpqAbhZsTAt6D6C)m580MIIGi3xgmE6W7hhm7W9aS0d55(6n0cCYjVdvizssnxk9XhpiABsHAQYn1WlepaxGnDW4Xh47KAoCmfoFr(n42fWVwmsMQxZnBx8DTj)ZBxmuBCcxdKKTCFir777bsdt1G8iKz7ryC0z9IIUaAxx5fQ63EAz7IPgDPHBTBx8HrG1FeLgmS342V72pa2)VCVpPS75JR991Diheah63Dcl2sINRpGA(JF3hS)SdLJyw1IlVSwi4JYBfBGVpiBj3(FeFpvrqjl8(RmDvQqXVl4sW4Xa(TUDx7dnMUg7t1tcK6y9CE)RijZHdmZs2d3mbiXekgTfghW7ornmCFR)kEsOT034f)lrN4fr)BVS4koQQl9LAuG5XBktU8tPtxjF6MPxvsgDSpamMdk3A4XmELqLhW7R5n4)Qq7dC5j8XaJUb(qUDFmaSk9F)

**Comment by emptyrivers** [comment]
You did not provide any details. Can you please explain the issue you are having?

**Comment by asakawa-k** [comment]
For context this issue was raised on the Discord. I didn't have time to log in and check the related Aura but could see from wago (https://wago.io/2qKV3_gfd) that it carried a lot of settings from prior versions, as the Aura had been duplicated and reused. I suggested that if making a fresh Aura with the same trigger solved the issue then it would be worth a ticket carrying the old Aura to let the devs find the problematic setting.

**Comment by InfusOnWoW** [comment]
I can't reproduce that issue with the aura that is in the ticket. It correctly shows up after a pre-pot and while staying in combat.

**Comment by mrbuds** [comment]
Could not replicate
