### ISSUE TITLE
state.GUID of a BuffTrigger2 target debuff gets stuck at nil.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1257]
**Describe the bug**

state.GUID contains the GUID of the unit the trigger's currently held debuff is applied to. For some reason, when the trigger stops tracking the current debuff, whether through the debuff expiring or through targetting a different unit, state.GUID gets stuck at nil until WA Options is re-opened and closed.

**Do you have an error log of what happened?**
 
Only when attempting to use the GUID for additional purposes.

**To Reproduce**
 
(Pre-made aura supplied below)
1. Create a new text aura.
2. Under the Display Text field write `%GUID`.
3. Under Trigger, set the following options: Aura -> Target -> Debuff -> (Debuff of your choosing, I used Rupture)
4. Apply Rupture to a target.
5. Observe bug through either of the following behaviors:
a. De-target the unit with debuff. Re-target said unit. GUID is now missing and will not appear again.
b. Wait for debuff to expire. Re-apply debuff. GUID is now missing and will not appear again.

Open and close WA Options for a temporary fix.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tested with only the 5 official WA addons enabled.

**Which version of WeakAuras are you using?**

2.11.6

**Was it working in a previous version? If yes, which was the last good one?**

Yes, but I do not know when this regression occurred. I have only been investigating in 2.11.6. It should be noted that Legacy Aura works as expected, and may be the last time it did.

**Additional context**

This may extend past simply GUID and target debuffs. I don't really know the scope of what to check here.

``` !novZYPnmq4NMESzWoz6Dc10KPeBcRO0tce2YGASL8OFsW5ap7DxztsM2lzgnsRwT)(TFINWzCqXZtUo96jPCWXH0RssU6BCOLdv0cnWe8nkTKdfRzlUppJd1gThuVkrprVe6YJg7sJs75WSSCw2koCQOU2j988jyuuUUgrptEcn4l)y99FNd9F4DR8GYOz9Dyo8rJknnglM78K4knUFDC)gANmj48MwkMR7QeE01W4PiGpi8QYnQk)romfVJAl9ysCud58cRhfWOO0QrPAu0DmkJ38w1HdsRBOgyVPikglurWksho0Iw5OLWQqNpyLummVOl0n98B5G8zjbo3jfnuf5c7JAwAL1QtCawMTybQUt20CFLBOGUyeeQJgTD2uGTfytxH1qWjZXSsX(s2rxcu3ay3DarwOsUhDDawVB6QhMVEXGrV3lXELqMNLSbLpyQWX6xtMqV8IXwTXk64WM3KWPS0Qfn)crheqXMg76)GddvDphwKnNayzt9iF42cgR4b0nKnrt(Z7aFO8PZ7ysxe1pjRgMt5PtqUqTfBheTfErephixZjTdDcmBvwworr01QdJ9nf99TZEIT0Q)D)phyOCyUv965Dpgevu8WCYOaQiYbw5FGjmot1gIMxHJuYGTdkDsmv4qbJxRqP)8w)gJ6ZzFK2RRuxOP49gJi(dejgL0zBOXRUm2kBeo3)P1rFl)hL(4Fcegl6Ep4OYNre(Mu63e)Vp ```

**Comment by mrbuds** [comment]
That's not supported, use UnitGUID(state.unit)

**Comment by emptyrivers** [comment]
This has been fixed.
