### ISSUE TITLE
Disparities between border settings for groups & dynamic groups

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1260]
Normal Group:
![img](https://i.imgur.com/TEKBXlq.png)

Dynamic Group:
![img](https://i.imgur.com/A7Z96i2.png)

- "Enable" checkbox
- "Border Style" & "Backdrop Style" versus "Border" & "Background"
- Border Size
- Border Color
- Backdrop Color

**Comment by emptyrivers** [comment]
We do actually have a TODO comment in the codebase about this.
