### ISSUE TITLE
[Beta] Aura disappearing

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#1267]
**Describe the bug**
One of my dynamic group disappeared.

**Do you have an error log of what happened?**
I forgot to check for error. 😔

**To Reproduce**
1. Open WA options
2. Click on some auras
3. 🤷
4. Close WA options
5. Dynamic group disappeared

**Screenshots**
https://youtu.be/ZzBYKladJGk?t=365

It disappeared near 6:12.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of WeakAuras are you using?**
2.12.0-beta6

**Was it working in a previous version? If yes, which was the last good one?**
First time seeing that bug

**Additional context**
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3005274/WeakAuras.zip)

**Comment by emptyrivers** [comment]
I can't reproduce this, when following your instructions. Do you have any more information on how to reproduce this?

**Comment by emptyrivers** [comment]
No response from reporter.
