### ISSUE TITLE
[Beta] WA capturing clicks

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#1268]
**Describe the bug**
On some part of my screen, WA is capturing my click.

**Do you have an error log of what happened?**
No error.

**To Reproduce**
1. 🤷
2. You now have part of your screen that capture you click

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of WeakAuras are you using?**
2.12.0-beta6

**Was it working in a previous version? If yes, which was the last good one?**
First time seeing that bug.

**Additional context**
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3005410/WeakAuras.zip)

Doing fstack on part of my blocked screen show this frame:
![image](https://user-images.githubusercontent.com/12969608/54952755-0532d300-4f47-11e9-9e95-706f236d3225.png)

Doing fstack on part not blocked doesn't have this frame.

**Comment by mrbuds** [comment]
Without proof and minimal reproducible example i don't see how can i "fix" your "problem"

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release.
