### ISSUE TITLE
The "Cooldown Progress" trigger should allow you to condition on "Remaining Time" even when "Show" is set to "Always"

### ISSUE THREAD

**Issue by alecbenzer** [WeakAuras/WeakAuras2#127]
E.g., I want to have Cenarion Ward always active when possible. So, I want to know when it's off cooldown and I should cast it. But, I'd like some warning, so I want the display to start when the cooldown remaining is < X (e.g., 5 seconds). But I don't want the icon to disappear after 5 seconds, I want it to stick around for a bit until I actually re-cast Cenarion Ward.

**Comment by InfusOnWoW** [comment]
This is now in the latest alpha.
