### ISSUE TITLE
Formatting issue in Region Prototype

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#1271]
**Describe the bug**
Message: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: invalid option in `format'
Time: Sun Mar 31 18:42:26 2019
Count: 942
Stack: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: invalid option in `format'
[C]: in function `format'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:348>
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:446: in function `SetDurationInfo'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1590: in function `GiveDynamicInfo'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1617: in function `DoConfigUpdate'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1638: in function <...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1633>

Locals: (*temporary) = "%.-0f"
(*temporary) = 7.999986

Message: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: invalid option in `format'
Time: Sun Mar 31 18:37:02 2019
Count: 12080
Stack: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: invalid option in `format'
[C]: in function `format'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:368: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:348>
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:401: in function `TimerTick'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:450: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:450>

Locals: (*temporary) = "%.-0f"
(*temporary) = 7.445992

**To Reproduce**
`
!DA1xVTTnq8pnfOPB1XwjonPaDaoUoTzir2i0P)5fztlrBteAsbrk74(Gbg2l7TbSpj9HTN262xbNVr7UJswoPUODRnrIH3PF84V73DKrnI6hXKrHno4O6nooIzJyVumpInlILG)awNOmlIgfXCIBDnoZODm5herHbhgXIngvIzHUpyQJMpsjsIonITS74XwHdqT(H1Qd)7G6nB8SMa8CD8utwpJu7IyT7e2VZvvOWwitf43Z1YzCN0OXL364zoCGBjyLLMjqO38EmpbMnjpJ(GbENSIyJoXgb2NXLemXgLj7kiKQCoIvVwZclTil0WxrdZTIbUmU2Q4okO8iRnA45gdNLRJHyaEIa(40mZeiUSF)QHuy)UYbVhgKiuo(7kh8(9w9JRgw9FLjMRwnKRNOeRg(Ivd3a2QHF3QH1Rf0CVvdFYQHb0tGFMwlvEFmYeU8mD5AtF3JjhJn2hti7HWhjv4SX8tc2BVnH8wFpFK9HaTfsVVcjRuxHuvWj0j()asnW2uSKOyUkDkpk8P1bfd8cM5w)lknCk5d5(T0WYmo9z9YvwirKzCy6HW4lObQsw99ZNkZ4kUojLGaLqsT0o9)Ted8io36mZWQGRttWaILx(otfXM6CP2NV)(l4tm1KM9BnwO5zdyt5Z469BEcSNi9J9E69eZGYsp89aVpGdtHj9tnoJpdwK3k430ccp7ZBzHDRcqwoMcmyNHyDVn5xc3PsABAgyn56KnM)ARHdzy5KjImm8dPgkftGdH6OxLzYthedO6qubHs8uHLbBJUfBNU6wqqmh5lmGzPk(s4Z9fHq3bNmf)YeXO8XJ9PXx35IEND9fKpHyeEQ3DVpTvCRf)eB(iXCb0ZcMuEBeBq7wS(dy9BDfeBKfakbx5Mw5BVmb5lRxNlGfqdOxS1yR)T1)9D)06)z9FU(JR)R1)X6pr)(P1F8UFD1W1)(D)8D)Y6pwjjg4jvNCg0zeKEcL68KcWcdo64to5yIaPTehO3a)RTxZGJo446hryAMnsQfx6jqp1DHzHWc2G(ND1QLinGeWozxhYVv5gk3Xjt99tEPbIwynDexIP)2yPisKqhBrMMREdKNr5sydi0UrisBb7Qy3vyTbr4c14h0FprAXe65XOkRr9GtAECtV4YJUNnqcHEEa98WI4ap1jap1jI15wSI0UGVeRsKX3S8LLDYhHvR(2Lq2lw6drSRaDQvra1VBVi28Ynaw3Tb9Zu8jaJ296(xCEyhOyqiNmfob7GM(Ji0JLt8fskdNowmMKyybReB4bYLx36YwHG(oh0ROHIjoTOibAKPDbOHspCfe9anO7iw270o9zUyQmgwNrKokEBFaMQyrGqbl2(magxuKVlG9Beq3KXJf70dA9qkEE6xiaZmQp)ttKqnxmmZYDIAQWnI7CfBj8ofpWlx1vd6KmHCBHmbQulYkuNjS9UJJQgFYSnKmHJ8Nrv2NhYo)LD8AnFBJr5oNr3fOBfkJi1X3Gk82YB080gNS5odFDHBJDjTYetGuHpCKunXgxFGgxmdLfSg1Qx7OT0Qv3)IMkI9il2B0YDy5GyZD1IyRg(O0n8Y3weVt(7dgZSOq4oipdBp5mLlrWwx6tcn4ERuNm4v52Y62h0iO4a)gL3d8mmb6jcw7R60jKqhm0nT84quRGiFDA7BA)MREBwVlrvowexTrlJIrfe6PufBISee)HsqpZ4B2(0jmqma)8dVa6kWv5cS7eomtI4rhfhFdDlY4PWTAevy5D)ZztOJZg6eAiLkYC3xL511HbFZb0H)xcOt3EvPd5DpSsQKKox71Z1rJZbuomaJ6O)9d
`

**Comment by emptyrivers** [comment]
The progress precision is set to -0. We don’t support that value in progress precision (and it’s not possible to select it in the ui). Just change the value of the remaining time precision drop down.
