### ISSUE TITLE
Button nudgers vanish off the screen for very large groups.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1275]
**Describe the bug**

This can make it impossible to use the nudging feature.

**Do you have an error log of what happened?**

N/A

**To Reproduce**
1. Create a dynamic group that grows in a linear fashion
2. Fill it with a very large number of children (enough so that the group is quite skinny as a whole)
3. Position it so that the center of the group is beyond the edge of the screen

Expected Results:
The nudge controls clamp to the edge of the screen (or a few pixels before the edge), and remain usable.

Actual results:
Half of the nudge controls vanish of the edge of the screen, becoming unusable.

**Screenshots**

Hopefully this doesn't look like I've doctored the shot. This group goes on for a few dozen more elements beyond this point.
![image](https://user-images.githubusercontent.com/24878501/55299578-31dc6400-53f9-11e9-9215-b4ec471d2be5.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Naturally.

**Which version of WeakAuras are you using?**

2.12-beta6

**Was it working in a previous version? If yes, which was the last good one?**

No, this never worked to my knowledge

**Additional context**

Another edge case (literally) is if the group is tall or wide enough to go outside the edges of the screen on opposite sides simultaneously. Then, those nudge controls become unusable.

Additionally, this occurs with single auras, but I suspect that few users will ever make a single e.g. icon which is quite so huge. This is mostly an issue with dynamic groups.

**Comment by mrbuds** [comment]
fixed with https://github.com/WeakAuras/WeakAuras2/pull/1270/commits/8a754650c9aa68e53b239657191fa47c0f1c5c36

**Comment by InfusOnWoW** [comment]
This is fixed now.
