### ISSUE TITLE
strings can no be decoded

### ISSUE THREAD

**Issue by eavnzh** [WeakAuras/WeakAuras2#1278]
Hi, friend
My name is Evan , I have played WoW for 9 years but I quit WoW before BFA.  Recently,  I want to play some WoW, however whatever i copied string from Wago website it does not work. WA always show Error decoding, I try to use different browser from Chroma to firefox and i delete all the WTF and Interface and only install WA2 but still the same issue. also i try to use an older version of WA2 even the Legion ones that still not working. 
please help
![111](https://user-images.githubusercontent.com/49223042/55454532-bb2fa880-563c-11e9-9b23-c53ec61082a0.jpg)

**Comment by InfusOnWoW** [comment]
I still want to know which exact aura you tried to import in that screenshot. Or if you don't remember, please link the aura and make a new screenshot.

**Comment by eavnzh** [comment]
Took me a day to download a new WoW.  I have nothing but Weak auras2 in the
addon. Still shows me the same issue. However, I can use WA only I make on
my own.
My system is Win 10 with AMD 2600 and GTX 1080
[image: sample.jpg]
[image: nothing but wa.jpg]
[image: IMPORT.jpg]


InfusOnWoW <notifications@github.com> 于2019年4月5日周五 上午7:08写道：

**Comment by Stanzilla** [comment]
Please provide the import string of the aura that fails to import

**Comment by eavnzh** [comment]
!T31cVTnos4)llWc0cCnvupTk2UaXjoBtVwNCroBpChohlBlhRR2s(KOBAwCW)2VHupmjf1lBNhDV0cK6klrroCLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83t3gE(PdD(Wh)24WPN8X)o57H77(lMnl2dpSps9iBBBDdfZoAg26dD(MxuSFyWW(WN9H264jlU3DZiNlh64oDQpg(o3f3GJ8V9w4oH2cdnPF8)EDWeS)38G7AXc4jdWErWn(7zTg0xCP3WGKN8ZHt9g2)nifO36Ty2LHWtm0P7fdgCXN)uVZGU44WOPErDDN81PrHRg60pmaA91rqRphJxf)U3(wYO7i)W3Mp6El0PdwVCqwVRpAOJ33x5gm1B6WUdD(E2W(n6A6hPa)XePOzGmj9ILWqFOd6iLJGo1IqxQGAQ)Sz(twVj2khmccLDDH1GxGcJxFPBN4bzMLPqVsp842fqF(YRoVNdvqbxikC9QcpsK7eVcxCDS3njTLdoAn0orHlkExR(2kS7cpq6j(nvEzvXRt(MeXgTRpp8UlcY(19ZWRxs5wXgEwtXT6ixAMhK8zeuZNsCGGdOomb(N(io1S3OHS4L335pfph0Yazn277y1Zcjka9((QiV447CVpr77Z(bthdYaCYDHs1tgCXLY06y7D(tGPg2HerCgVYBXI(Ul9ikdSNcEH1C3UXSaTcNMHNLGNuLZqjGKbSrEMZNcGNFFWRUMdx9n83t0dtF0tcdxmn8UGnJUmk8wYWzZOxrFMxN0IRd8X0oqE70VJITAAxmPxbFnMooIXU41XdXmIjh))WJy52eRHvPDHlJ8M4NykQWBKtLRfL(IMr03(qNFoMOf7JVb6xryWQk)76f4oErIzgi6tqkIZ1eMm3BYxjFGyk)lBNyO9g3iFYZsUl19ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNch.109773641.109773641.109773641.109773641.109773641HlHM)inMHyIKtnvNd65)8QcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH4QS83tzeuZNsCGGd)6GsarYmWe15Z0R5iaaDAp)BNJtGhYbT1un4WqGlPkdLbHS0TvnTm5v0lL(QiSHBG)s38Pyx)GdzVHQ4E7pvx6R98h7BXLpcar1LRvdSKNcXHlVzUpiZCW(l9LNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83tZNsCGGdgU4qqz(xFpNSNcEH1C3UXSaTcNMHNLGNuLZqjGKbSrEMZvo5cxPGPKQbjVZurQQS83taLh.109773641.109773641.109773641.109773641.1097736412Y0Wu1OGrCwRsXr5T(r68QCuUew9TMXm58L3Lmv0mNFeHifaZjqsGeDa0TX(Ricar836WuF)7fbvPiOsHx19ZWRxs5wXgEwtXT6ixAMhK8zeuZNsCGGdF(V9HbP9iAdKcZ1Te8ZsG1KGRM)9GdzVHQ4E7pvx6R98h7BXLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83tU0jXWBsMHHEysVrQ7dBPwjwIsD0lbJ2G3rpw04jHlcJsK2KwsXOthvndvBDeQdbxxYf1KCrCz46jQ1SsgEO66WMVi4Z(XK5t4)UEmf3eecZ8)oy6FzVp9PuH65ttFz9r26Q62K3cG7CrWI7j6lt9gVE2SeQLp07txE21Fkhe(daopizsr)DbtUTVkh4PiVQBo5yNb34m44RGUCambM(2CiypZcJws1RiZEoRw4Epm0svvGdzVHQ4E7pvx6R98h7BXLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83tihjAhXXqFuLS1xSsNcBI(LNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83t)sILk9YKETihOFarp2l7)YW3xieJM6aq(7JQl0Ta)oR9RGdzVHQ4E7pvx6R98h7BXLpcar1LRvdSKNcCc8(Eq7imILI8(CFRJPrMhCSmSg5(xVzuP(xZHgEW8OodbgzZcbBtq019ZWRxs5wXgEwtXT6ixAMhK8zeuZNsCGGdqIsfFutS(erEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh.100148163.109773641.100148163.100148163.100148163.100148163.100148163.109773641.100148163.100148163.100148163.100148163.109773641.100148163.100148163.100148163.100148163.100148163.109773641.100148163.100148163.100148163.100148163.100148163.109773641.100148163.100148163.100148163sYKoihjAhXXqFuLS1xSslCL8)nnIfhk4kBanGE5Du)0aS19ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNch.109773641.109773641.109773641.109773641.1097719ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSs7jxuh.100148163.100148163.10019ZWRxs5wXgEwtXT6ixAMhK8zeuZNsCGGdQS83tWKS0c2ADSn17O3KCXS)q(PzQ(zJl78mpLqeKo9utAOkd2gFGDKVDjKPamq5oM3Iu0yuPUwdZqtcnu3Wf4dysAyqR4b8GWDv0vQopnYt6Dyqw64Ys4s)9jV3mGOmrQ84aGQZG)9NjKZSay3nkurC3h4egl6(vT5k(9VxQtqTkxXQTmxXstSeyUBkNeX0wVJQUkNPpJvq3Svlm2l6(T5DOHw98thUuzmDfx7wg9cVj2khmccLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83tDvejowFFWRUMdx9nrm(Slxo4aNFnLWeZqB0w19ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNch.109773641.109773641.109773641.109773641.109773641wuh2q3gWj0rs8gHv0w7Qs)(YyONsqzOyP5RQYUZplPifeC7qEs3FgyFA9dP9jd(oRd4cwe0UolvlvT)IOSKiHR0JvI2Vi(lZ6RSnZkKOEVjDEH(EOl6cnw4Xm(VXHa0P5CIIPA7u3OVMTMXSfqZj96pO3vnCzcKLJP4jG8(7jE8tvp3AJa)N7t0yj3Z9PRE5IWOJ3(XbCjyIEPFB73EvI8JSo70gkketMHY4ztw6OUP3C3Tp3zWqbe20buyWRYSJ(lBgfHGFCl5hJj)WL8JivY1i)ym5hUQVEZh3mk9V5FYh0pib6DJxW3oIWp7Du2qf(6)773mszZi8CVaMho9VFXZ9Rhd3B8rjc14)zEd5p9FLEXJic5354Hpnh0y6RiEFW0B8we7DiB(zUqdY2(btLn0J8GhiGk8arhi4CrB(iCVstIy88i)GdzVHQ4E7pvx6R98h7BXLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83tZNsCGGdn100ntGdzVHQ4E7pvx6R98h7BXLpcar1LRvdSKNcvx9vSVa2urcYPU7r0RY9NGdzVHQ4E7pvx6R98h7BXLpcar1LRvdSKNcNsCGGd2TYpYh)siEjyD19ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNch.109773641.109773641.109773641.109773641.1097719ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSs7jxuh.100148163.100148163.100148163Hkvo5cxPGPKQbjVZurQQS83tP0u19ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNch.109773641.109773641.109773641.109773641.109773641ewHNNhfvDUzU(pMHRwIps73c6MypuoPDAjTsvzZzxX0QcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH4b8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh.100148163.100148163.100148163.100148163.1001481635cxPGPKQbjVZurQQS83tvC(7KpxzOsDLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83t(DlLNjvUhA1HFHkvo5cxPGPKQcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH48DuaLh.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163ZurQQS83t)DLxJHYGMRAJwiNwJUPuLs60r3shPcmsvLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83t(4KZs2KmlnZYmzEMjVYBZZ9F(t65UUdzZOGlHWn1sS9rxjSRv6yi6WIKS0(NK8E(KMaMDzptTxBxks9EjjzN79(L6aN4ZeDWLNjvUhA1HFHkvo5cxPGPKQcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH4y7jxu(uVtgC2vh)5EsXHkUYY7mOeZ7M(JHo5W9V78GyGsfF)MrDDJ2m6nBg9zGuL()QcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH49hKv0H1hjDDnTczhIdD95aywDwiyzvW9JoQwRoynAo(2UINzXwnJwK6ihzkfvJbnEC1yzYO0BzbjWIvvWJxmnefz5Cw1s30OJARoYoOiuqG6xo4CcUtR94UGNwZCN6j3pR0Vb)4uPsYMgQ)m2OLNjvUhA1HFHkvo5cxPGPKQcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH48DuaLh.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163.100148163PKQbjVZurQQS83teUrB)TxppxvPnyoo8YXU4nJ(u4T8L6ZLHjH(qQ1Nt9CNUaOH(nk0aU0eKD9jN0ZXz7qL2rhZgYhYGPCR)5jpk7zfE8I9EnSpWRzDrCV9BhoYFMYSfRtY(AO5lSMHuqonBtl1og1unvGvA6L()ENV0n4xj5haNVyf3hwFV0Tmkgn5ZmFVeYJ6HfwF8pAo49d2zM0JH3AM72bVbpq2wF0k94rQzPqT2DN8b1LUdDLMx0D0QMoy9wZXu3aPBuaAKjU0skazg4n(DGyJ3MJLAA2eprklkOh)iXougW0HxLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83tNcn0YwNHTjD3zIBqpcjx8R(jNEx(HR)h3Cr)Bo50F610Yqh0nJDVnr(XCsajRO1PxAMOJgzfphBjTNF4c16Ud)rreFLnzlRYMSn1T2E8aLWIIkU)zAWHtXGWOOeFbACXkWvHKO0dgLTFFXQ)R86ssEfjws5biEQcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH4QS83ttvdSKNcbZ()MByYUDTf2j31D2CiDCiTMsQ808OEo0G7pSftx74)K4pICxyEo6rm6qILMCEMv8LOw6lzFQzboVm0E4pVAfqd2JtS2m4H6pZAFgvrG)yUbtp41VFk7uDlJLHcIYGkS)Zutd93q1OJvh7C2unJQkfztY51NvgbDkHTvk)Tcc4ZZoH)2EfcdFBoH)sPgLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83tZNsCGGd(xjJHa7VqMgAbfrB2HUvECylCuOOPBJ019ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsj1k2hm)teIJlmb(47WVXVj2khmccLNjvUhA1HFHkvo5cxPGPKQbjVZurQQS83th.10019ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNc)(4d(wB4oC1cTKTo1UerrLRZ0Jn6QcwmVWnsiKnZ6VWN8hrtCM2BcF674KfWH4b8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh.100148163.100148163.100148163.100148163.100148163NcCGGdG0dXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNch.109773641.109773641.109773641.109773641.109773641QkkQ0Z7TPvDS0LUfy7yORBRsoWhB(XshrLF)pw6C(Y7OsJgs)u3zsN6EqxuYHzNdPauuSEsTVzqUFbQUKtJor)nkZtf5EfuDXki4)OKKTBMDi8t8ReL6(OWftYAhsE(dubDmfnutZFWo3fEGdzVHQ4E7pvx6R98h7BXLpcar1LRvdSKNc)yiT(yTFG8swUU3tVNYz2qT219ZWRxs5wXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSs(mpe8x8VVXKgvSr(Qj)f62wK8xKFmU0Q8xOQk3378TYxHFv01gVwP)64a7TmBjsiFgM6tQLzPjcNBh7rtaVxm(SNcEH1C3UXSaTcNMHNLGNuLZqjGKbSrEMZQ0v5nYJSFcjugcN595JK(idenWKMSDNE8orNbxMR80JPMcCQUFpVj395ZU4Qt6DkiE)BxF8v9s)kGeedYWL0jMlUEGZ5N2RvhYZm9muD)M3k9nM6mcXXJupny9irr9zXU14f3MB7YOTZ)o1sU1kRXu8fnzi2oHAxu7sYKoihjAhXXqFuLS1xSsr1LRvdSKNch.109773641.109773641.109773641.109773641.109773641NUyWMr0gVVQMiqRwdozipoEIxq5f08d759Zd3osTY1aVWiFFwf8okwiuDRco7V1cLdk9SlNLz2PeGBjBnZFmw48wTS4jZKy54)cuzp548S8MLCuQt(7W)3


can you tell me why the code become numbers. I think this mightbe the
problem for me

Benjamin Staneck <notifications@github.com> 于2019年4月5日周五 上午10:31写道：

**Comment by emptyrivers** [comment]
That Import string is corrupted. If you are copying strings from wago, then the issue is with your operating system or your browser. 

Try again with the latest version of chrome or Firefox, with all extensions disabled.

**Comment by eavnzh** [comment]
still not working , would you mind send a sample ?

Allen Leigh Faure <notifications@github.com> 于2019年4月5日周五 上午10:56写道：

**Comment by InfusOnWoW** [comment]
There are random numbers in the string you posted, e.g. "109773641.109773641.109773641.109773641.109773641", so clearly something is going wrong with your browser or operating system.

**Comment by Stanzilla** [comment]
Try this one

```
!nVXc7jUXX)l0V8zCpqhINM7lUFFGbBZvBSlcFxtCmMfPfHIfsu9WVso(T3z2D1lqcexAABCSrAzEp7o7mZU3e5jJNOSCII2ef3jkvLAlvP8mQhP6eLxi62d6nrr5PF9sJMYDFhHcG(TBMp3L6nzOSmaDLkTLB0OARA1NO8m1X1W2c(MtMO4q1HNh)2kkG3BwKLgQ6o2(RMOqSmws8qarEtmyF6Xa0Y2cb33H99pYh0LQABP5oXdE0J44LFWNByz4Ui3Wdy4BawINhqR912)CFcTlmIJ5eLfEERC)0h)iAtKmS)yOn5JOQsFDfXsJQnba)1aRt5A1aZz72nBx)KQ1RwnqVPtMbghIMHV7KHvRubeavIjfmAtuqMF9BElmu)W6PdS8Ooo(R8wpDSdr9jQZ6P9Uy90NRnrzg8oAnTaegYuk4TxMO07MVoeidIPfX8lb(J2ag2oAuNaOjwQlSDU1gGCIYz9hoU)Oaqc9UnNOaggWIB5Dor1ZgqEuNEdUtbKyBWlOqCvPwAgw6GH2HSKQ4b2vctrqlQbAJDbJp63OlFg5USufjuJPMZfmF8n3gxDgyXyoadWsb(G(y4jOJW)h33Y8BM2e2KtnJ5Znu9n9EJn5cEWiaexJ3PBn4CoB2ACvtIR7wJ6boklVTgg8oBtz3vu1Tg03L(iN04KaBZTrB1ZRYGlGHMT(jDHQ6MJJoitdDRi)RNJHUomLaayiBDVVLyiUfn6LWLiGhdEHoZF(C(k5l7F1TNF3vGldgszH9l3aW4Y(SdyjFMIuL(mk)kEglPAmdHP5anXmb(AocqFyDdhUlPetVfaG(ZyJCRdDUXRqGNB7F1vrdRaCeh(XZ6Om(rLXDgXubd0OzsEdNEbrzOUX0FMenMRwxBRblYklxbNK4(R(wcXLyAYGLTI4CCEmxtvoBu)(dzt5ywfCoP7k0tpSk6784giyya7NblA9QGTIW1s1qBSbSu4rxdG3kx1)C00sDjEO5LfiaOOZtJPVcJaqWwYdtjP)YzexpWH3L48l3nOC0BLvqesgDfnMZioOOAO(0B9c8Da59cOCxtJ3FN4OTE6iIb83Ui88f8ILCYYmddAkr55k6Cqp(bv5nw8wgd4HEwhfC90q5QmtK6tUNzBA7W1B8)RY(Bn2FRJ)fi3lgAGJEy1gveA(OyMr(iDHjZAmFLsNEWUpQ(UE2lrj6UvAOrtXx8zcciW4UX3GrtC2TSurcI7I)x9wnpPwRQSab2qyotIoSl4n3n(Qbd7VzaXgc9waLiqQVNng2pMLBKH(cMPRk37JF9MXdXaEAo2RgyDUdWyMRcPncl6ZWpnSW9tzZscIUHHpWvxoSPoI4zUWmdiqcoXaI6fgdq8E3)NeNl7OyPg0lRqBO(YuZUBgzpqPvxaRFPw60ykE0yD3xeYdiKiklKzWoFZyZ16MrCr(8vWGZcWyBveKfy9Hh1TelkwjjjPJx)51tf)e(KX81tzqSE6PNUEAHZU56UDg)4v3CXJ9)ceb)X7gE(GRGa597vy9uVfuRqASfTc(X0gsTy90GiOaLHxOMuvVIv3uqIjgXGhLewCyru37o7S(kkbcWwyVjJT9DuPdHyQXzDJmyDQiFXDd6fh565ez(MoXXuU6EqfvDmw6JuRNL8yPCPPG0X9Eb5EyF6DWpBO46GfTy0yLaJ6pu((1F73F4dfWxkC86PLl7cZ2wTEQdSD4Y1tX9Y2pJkxUJhG2mFpGt3sbxgtIpYfKuBqL8GhSFXcYDCVKsy5WnO5MnphiMMHxXcLlukYzC8(PeAifKbN)aIvH8A4c(zUnKTlU5oqnRyULlW4extxodw0weSAA25NMXfV7asJAtrKhssfwbY4XC5n(8UdtOtFwq4m4e884dMC)bfJWjJOyGVieJ)tr2Cmh)7MvZG1epD4OdzsKFKYfWiqF3(NYLHD41bR1lehyX2tHrPCZ3sQOyAG5gk(UTCfyXTZMFrTQ1R0oyhI4XbLB3SERCQOLl7aLf)mwZPTPggma3ctSUeinmcZXhsFcAzIpH)71kfeahz4(HMjpgAVwYLhOyfXacmeUN7bgHGzLLsSSDJacC1ukHfp8LVVOfCnLfX9pHzR5AMLLTxOCCykHWBbEaMg8xcT8Fqo)ejeP7b68aJqBoe6M)TVLFsgzu3Gs)5UeNXjjSEygV9C8P5fjiRviLvTdgVnZXk61CsGvo26oux3XbB8FeRW9JYl(yjqxcf4YWDoX0n3Cg4QTJ3bOX5o6rq)l4Za2DoDsA05eOSG8euuDbfJBZlOy90L25n2DOmyyHfm5DLXSdDPw66Ko1lOG)Icn6WswlFBsMtpAczm8LCIm91vgCmgBiMnhrVpSE6fup8lW0(Y9ebSa84fbuReqf2eGbwZTdSyhFCELXq6XE4GwIgvjt0R5LaXRMj45)ZL4Od1Z3XsSi8GPsAbm)8oNLLCk3N5V(N0pIUm6orzhfuZRUN1lXUbLWhC6aOdiOLtSL)H9Tmrts3Dxp1PqjygQP3W0OUwgq5ZSxoJaXxUYwpOJPb9vyNDdnJoOMOjPhCNrX(rLJE7XAhxoGl84JQi6IkfBA2eLH3GTCJrfoe)tgiGJPJ2VckpvJQDTbRRMPEasQiR7Wo9HxdW8r2GOp9nEhgXtA5vgmShFtCyfaqJIECCcdEsZpdGlyWsmxTGetnypMXzlXXRBepohSYXAsuMDekmoViHgw(NjhmrgaPVLIiyi1s30WDXzyp)s2liSMq2WfZK2hNrZIss0u7l1EdHiKpMLHlzJ6mO3JNDvhfyc(nxDZiL7JZNh2DtCcOt(2Fni6hhljNsIh0dEywj5dl633vuW9ep8)kN(zSZLl5Hcg0N68DEOVgBjoh)(AyhA5TmpXPeJbxs0qD(zjKSh7BDsGHlhtnTky6d8PIN)SpbB2dp6qCERyb4bw3Jgyb7)RoUSSKCHs4wE4e7phsj7vmUXiZVf5wCOenw79VWHsTcZzT06p)TeONihtbrGehdZ28uvBOGA7xInX8(6TAu9KhWhrWfPJEQCJVvcrfc6btXohy77Xsr(E5knpPw7hshhLN8nnXt5XDrmuADsZwn2IpnRiWX2Kavz1LswgNnNudKUmytpdx2buhd86TQ1CtWRwNd(z2(4bCTEkSpycKoPvRkTYGhx7)(7MXv8QYm1Et1yBMGw84CrUzRknYYGTIIk)LS4RyB)FkolB3SAn5mDqJOZ8taUCRMntrcdG)VBOgRzw33Ov7213M4v5a)vM3xzbkEr40SbZNKfhU1F5sAsDh7wugUfUHcs2alTbs9yjZi0JUmEgU3Z6E0dzz1tqdmgmS7lqK5o2lxpDf2x6zjuaExQ(oeOPq4ahJ5gQjm4nQFY2Yw9gL4fQ5E6VDp4aR16HtRv5BFReWbdyCGetRvz90xm8wevthpgmBr9xPKN6alSDvipt1U)iXH85E0d3hf4bkGeYV6F5tf5NxyOLTUo56peE)ne3EJcijlxEZqNq53ZbP5JexYtKxiii(UeD6NWNoK2GxUmA7GNGIgGKdXby7KeKKrwO7qzNZOwjw30uP3INBySn7fBoZLcMkwK1VOiGfPLmWDGfE6YfHuf4JCKd86r8U3Ce78ipAl6A5VmU4W7IWMKgIJp0FPI)m9nuCoT5F9ggLnzKbJ0bARGWBXDKCf56k2BVaPMdTOFRYhhFFbE2dPMkxsbWbxgKEsugCUvrWNu4ViXQpVJSy4nVHNMFkDVHA6sf86hpnfnNXz4l)Bm5y35ofWnUGkjHi(5C1zbUxWGvqFXnCgLL32(UPDg5CYuOePlvUSokublJjIIgI3gIuwjK72NemjYAUDYgWeL5bMTXzeOgrnEVf2bzGYjj5P3ujlgGZ809m8gZZu(bAVw6X4TdhXtsekCpDehzdkCbGl8mXh6(qUeCCOHoNmbl1PcBLn8w5cNGUHTPlm)y8qkqaaPuLx(blJD2gpO54zIPHy1KBwE)Z4yS5HHf2vC(m8KQzcbx4rJOEpQkuEQ5y7lPVw0PKEPz7y6mEMVw6sG4cv0wSWVRoF(puP6Rb)INCMZFTAJgWN6IpNHFECg1riKgEqaR9DKFjGMzclD7vD(P(JyvEfIkVYWSSqjWiPHIB8stazmJ5TYOCVyu9HuyAC8Zlpz(cg7IWgl3l6f94VmljBrdXa3Eqza34CXcBxVGJXvW(qIxrQrjXV7P5yBzlwq5hJYoNcfwVAC0KKIC5ssf(DmBdkE7q1SFuuSu3DEbkZ((Vf1rMFkwfDIB)vtbayBz27TxfV5Qj7Nd51WR(uoADuWTMAF3URgbaZVtPXbVIuTgvBxxgsrVounqBg2BpyT0gmum4xL2zHfRIvgRCUJX7RN(p8jAoSG7JhlUnXJmF9KMx2ZIUQBytJKdWn2LOdnJxszxESH1QiknMr6ooQlmE2EiXXX(LYDH6hNO8Un4srHCIITJbeOv0kYlVz0GF(MHJ7Cvk3k3W7sxSwpLSR7LI2VeEm4OH4PgIxEzTErFRf)y(XoHxI1PAqFslaXM9WA)btTeNFwuh)3hvLGfdE8Shs9l(rbrlJRpLZAt0ur9uoQzNvNEWbEewVGei4JyJxmwHcLcFw102cQxiRoQLWJ8JXo2JCDPRIIQM36xcUWK7kFpuzqaLMP)jfQ3xOoW8tgwfzm8E5h49l7(Qbpul4H6pSJZxzdBUyh8WZZmT9QZUhLhkBUvmbpjReTasAZE(Wsfc2J(8ZRub)De(9yOw28UcSxlKEI35T7NhOFlriU)V29TvRQ)J4Pwf(s6zvM5oUjc2eebkBvO0ELM8F4vz8p6cEyt299fVP4Q58GwU0qtJcH7h2)lmQGJ1JFZYPHBPM9Uh4ElrB9e0)cGCz07Ijkle7mH)dzHVbyU2fMjyFLFTVXdyk7)PP0vS5E87Q(yBBtpJvIBR7K)9p
```
