### ISSUE TITLE
Kul Tiran Humans not in race dropdown of Load tab

### ISSUE THREAD

**Issue by jf647** [WeakAuras/WeakAuras2#1282]
**Describe the bug**

I am trying to set up a display that only loads on Kul Tiran characters (for their racial, Haymaker).  In the load tab, after selecting race the dropdown lists every other race (including Zandalari Trolls) but not Kul Tiran.

The code that is missing the entry is here:

https://github.com/WeakAuras/WeakAuras2/blob/47563d1d95dd2064989c7b9886ed8675ae4bab95/WeakAuras/Types.lua#L201

**Do you have an error log of what happened?**

N/A

**To Reproduce**

- create a new display
- move to the Load tab
- click the Checkmark for race
- Open the dropdown menu and try to find Kul Tiran
- despair at the clear Horde bias.  :)

**Comment by Stanzilla** [comment]
Oh right, I forgot to revert that revert, fixed now, thanks!
