### ISSUE TITLE
WeakAura frame taint

### ISSUE THREAD

**Issue by Evolutious** [WeakAuras/WeakAuras2#1283]
**Operating System:**
- [X] Windows
- [ ] Mac
- [ ] Linux

**Companion Version:**
```
Check the bottom left of the "About" panel in the app.
Not installed
```

**Companion App Console Log:**
```
Press Ctrl+Shift+I to open the console and copy-paste everything here
Not installed
```

**WeakAuras Version:**
```
/run print(WeakAuras.versionString) in-game.
2.12.0-beta6-7-gff79dcf
```

**WeakAuras Errors:**
```
1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • GREEN
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • There are error messages. Click on the red bag to see them.
     • Copy & Paste here all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
No errors reported by BugSack
```

**Describe the bug**
My WeakAuras appear to be leaving a taint on my screen where my mouse will not click through them to allow me to interact with the world or anything "under" them. This is not every WeakAura but it is several and it seems to vary on which ones it is with changing occasionally on its own.

**To Reproduce**
1. Open the WeakAura config window for a few seconds to dispaly your current WeakAuras
2. run /fstack to enable in game frame analysis
3. Move mouse over the screen to locate any taints that appear as a green box of the same size and location of existing WeakAuras
4. Make note of the Frame Stack window and specifically which frame has the arrow pointing to it (it is on the left of the listed frames). This should be pointing to a frame labelled "table: xxxxx" where xxxxx is a random string of characters
5. Now click and hold your mouse on that area and try to move your screen and you will find that you cannot. Essentially, these areas will not allow the mouse clicks to pass through to the lower frames, one of which would be the world frame.

**Expected behavior**
The taint should not be preventing my mouse from interacting with the frames behind my weakauras when they are not being shown

**Screenshots**
https://i.gyazo.com/a2088cf57869456e64e36270c688dd74.jpg Here you can see a taint (green box) and the frame stack in the lower right corner showing the frame is labelled "table: xxxxx". this is with all addons disabled except for WeakAuras.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras-Companion/files/3065892/WeakAuras.zip)

**Include a .zip file containing:**
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by sragia** [comment]
Hey I am getting something similar. Mostly noticed it because of having tooltip enabled for them https://i.imgur.com/UBjpxeO.gifv . Here's an aura for it https://wago.io/88zGFpY2z It's TSU aura, but I am not really doing anything dodgy there that should break it. Here's frame stack of it https://i.imgur.com/F53bCas.png
Also here's aura with default triggers that does similar thing except for showing tooltip but still captures mouse clicks. https://wago.io/bnn6fVYtx https://i.imgur.com/ZgAggzu.gifv fstack - https://i.imgur.com/U6vORMu.png
Seems to be related with cloning auras for me (TSU, Auto-Clone) as I couldn't reproduce with "standard" aura

Im on ff79dcf07e252a
No idea when exactly this started

**Comment by Evolutious** [comment]
Rolling back to release 2.12.0-beta6 fixes my issues so it appears to be something introduced in the latest alpha releases.

**Comment by Evolutious** [comment]
> Seems to be related with cloning auras for me (TSU, Auto-Clone) as I couldn't reproduce with "standard" aura
> 
> Im on [ff79dcf](https://github.com/WeakAuras/WeakAuras2/commit/ff79dcf07e252a6fbd033579cfcee9d5076616ca)
> No idea when exactly this started

You know, now that i look it is also for me with any WeakAuras that are doing clones. Maybe that is the trigger!

**Comment by Evolutious** [comment]
Rolling the builds forward and testing, this was introduced in release: 2.12.0-beta6-5-g658d1f8
