### ISSUE TITLE
[2.12.0] Anchored aura changed position

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#1285]
**Describe the bug**
I expected the position of my anchor to stay the same between 2.11.6 and 2.12.0 but that not the case, my group of auras anchored to each other are not aligned at all in latest beta or alpha.

**Do you have an error log of what happened?**
I don't have any errors.

**To Reproduce**
1. Update WeakAuras to the latest beta/alpha
2. Anchor have changed position

**Screenshots**
In latest beta/alpha it looks like this:
![image](https://user-images.githubusercontent.com/12969608/55996204-fffbb500-5cb6-11e9-89fd-1e1cd41f0eca.png)

Where in 2.11.6 it looks like this:
![image](https://user-images.githubusercontent.com/12969608/55996243-186bcf80-5cb7-11e9-8cb0-f87ec4ce36af.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I didn't try.

**Which version of WeakAuras are you using?**
Tried with `2.12.0-beta6` and `2.12.0-beta6-8-gdc684ec`

**Was it working in a previous version? If yes, which was the last good one?**
It was working with `2.11.6` release.

**Additional context**
SavedVariables: [WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3070797/WeakAuras.zip)
Aura shown in the screenshot: https://wago.io/VardexRogue

**Comment by emptyrivers** [comment]
Your main bar has corrupted data, possibly due to the fact that you have rolled back versions (note that the database version has changed between 2.11.6 and 2.12). 

`/run WeakAuras.GetData("Rogue Main").selfPoint = "CENTER"` should fix it, so long as you do not revert versions again (in which case you may have to reapply that fixup).

**Comment by emptyrivers** [comment]
Alternatively, fake a change by changing the grow setting on the affected group.

**Comment by Vardex** [comment]
Using `/run WeakAuras.GetData("Rogue Main").selfPoint = "CENTER"` and reloading fixed my issue.
