### ISSUE TITLE
Region aurabar not supported and /wa doesn't work

### ISSUE THREAD

**Issue by giovanniro** [WeakAuras/WeakAuras2#129]
Hi guys, i have a problem with wa; when I type /wa or /weakauras in game, the menu doesn't show up, but some wa bars show up in combat (not complete, but with half icons). i use elvui with a player custom profile, could it be an interaction with this? i also use DBM, Detail, and vuhdo

**Comment by giovanniro** [comment]
on chat it says: improper arguments to weakauras.createregion - Region Type "aurabar" is not supported

**Comment by InfusOnWoW** [comment]
That sounds more like a broken installation. But it could also be other addons. Try reinstalling weakauras and or disabling other addons.

**Comment by Stanzilla** [comment]
and enable errors and tell us which one you get

**Comment by InfusOnWoW** [comment]
If you have further questions, just comment.

**Comment by giovanniro** [comment]
These are the errors:
4x ElvUI\Modules\skins\addons\ace3.lua:124: attempt to call method 'Point' (a nil value)
ElvUI\Modules\skins\addons\ace3.lua:124: in function <ElvUI\Modules\skins\addons\ace3.lua:107>
(tail call): ?
...aceAddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0-34.lua:136: in function <...aceAddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:125>
...aceAddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0-34.lua:174: in function `Create'
WeakAurasOptions\WeakAurasOptions-2.2.2.1.lua:7492: in function `CreateFrame'
WeakAurasOptions\WeakAurasOptions-2.2.2.1.lua:1240: in function `ShowOptions'
WeakAurasOptions\WeakAurasOptions-2.2.2.1.lua:1212: in function `ToggleOptions'
WeakAuras\WeakAuras-2.2.2.1.lua:65: in function `OpenOptions'
WeakAuras\WeakAuras-2.2.2.1.lua:71: in function `?'
FrameXML\ChatFrame.lua:4385: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4053: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4089: in function <FrameXML\ChatFrame.lua:4085>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = <table> {
 objPools = <table> {
 }
 RegisterAsContainer = <function> defined @ElvUI\Modules\skins\addons\ace3.lua:258
 RegisterWidgetType = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:559
 WidgetBase = <table> {
 }
 RegisterAsWidget = <function> defined @ElvUI\Modules\skins\addons\ace3.lua:107
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 GetLayout = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:583
 GetWidgetVersion = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:613
 Create = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:172
 GetWidgetCount = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:607
 GetNextWidgetNum = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:596
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 RegisterLayout = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:573
 Release = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:206
 ClearFocus = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:257
 WidgetContainerBase = <table> {
 }
 SetFocus = <function> defined @AddOnSkins\Libs\AceGUI-3.0\AceGUI-3.0.lua:247
}
widget = <table> {
 OnRelease = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:172
 label = <unnamed> {
 }
 SetText = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:215
 SetMaxLetters = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:223
 OnAcquire = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:162
 SetCursorPosition = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:257
 button = MultiLineEditBox1Button {
 }
 scrollFrame = MultiLineEditBox1ScrollFrame {
 }
 SetNumLines = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:207
 type = "MultiLineEditBox"
 scrollBG = <unnamed> {
 }
 DisableButton = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:227
 numlines = 4
 labelHeight = 10
 SetDisabled = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:176
 editBox = MultiLineEditBox1Edit {
 }
 GetCursorPosition = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:253
 ClearFocus = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:237
 SetFocus = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:242
 HighlightText = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:249
 scrollBar = MultiLineEditBox1ScrollFrameScrollBar {
 }
 frame = <unnamed> {
 }
 SetLabel = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:193
 GetText = <function> defined @Decursive\Libs\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:219
}
TYPE = "MultiLineEditBox"
frame = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = MultiLineEditBox1ScrollFrame {
 ScrollBar = MultiLineEditBox1ScrollFrameScrollBar {
 }
 0 = <userdata>
 offset = 0
 obj = <table> {
 }
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = <unnamed> {
 0 = <userdata>
 backdropTexture = <unnamed> {
 }
 template = "Default"
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = -4
(*temporary) = 8
(*temporary) = "attempt to call method 'Point' (a nil value)"
E = <table> {
 GetTimeInfo = <function> defined @ElvUI\core\math.lua:322
 Bags = <table> {
 }
 resolution =

**Comment by InfusOnWoW** [comment]
Elvui's addonskin is to blame. Update (or deinstall it)
