### ISSUE TITLE
[8.2 PTR] Editbox selection quirk

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1290]
**Describe the bug**
When selecting multiple characters with the mouse, or with shift+keyboard arrows, it highlight characters for the next line.

![img](https://i.imgur.com/k5crkT6.gif)

**Comment by mrbuds** [comment]
It seems the problem is coming from blizzard, and not from allindentandpurpose lib as i first though.
I can replicate the issue by pasting a big text in a simple editbox (tested with profiling editbox)

**Comment by InfusOnWoW** [comment]
This does look similar to a problem that we had in 7.3, can you check whether cherry-picking 8305cd5733c6b4470a84a8df37bd725e104b9c1c works? (That commit was later reverted when they fixed the bug.)

**Comment by mrbuds** [comment]
it make it worse without modifications but it's probably close to how to fix it indeed

![img](https://i.imgur.com/JUnBEM4.gif)

**Comment by mrbuds** [comment]
Nop it doesn't help, i tried with scaling enable and disable it's the same.

I also noted that clicking on a character to position cursor is off by a few lines and get worse the further down i do it.

![img](https://i.imgur.com/eTnMTHu.gif)

**Comment by InfusOnWoW** [comment]
Can you create a minimal example, so that we can report that to Blizzard?

**Comment by mrbuds** [comment]
https://i.imgur.com/FXe6132.gif
[EditBoxBugTest.zip](https://github.com/WeakAuras/WeakAuras2/files/3098189/EditBoxBugTest.zip)

**Comment by InfusOnWoW** [comment]
I just told TSquare about it, so hopefully it won't release in that state.

**Comment by InfusOnWoW** [comment]
And we reminded him again, no response though. Might want to try in a month or so again.

**Comment by emptyrivers** [comment]
Tracked in Stanzilla/WoWUIBugs#1
