### ISSUE TITLE
Riptide template has incorrect load conditions

### ISSUE THREAD

**Issue by Mez-WoW** [WeakAuras/WeakAuras2#1297]
**Describe the bug**
The load conditions for riptide require the Deluge and Earth Shield talents to be chosen. This aura should not require any talents.

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.11.6

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by emptyrivers** [comment]
No, this is correct, from my understanding. There are two templates, one which correctly tracks riptide when you do not have echo of the elements selected (the one you say is incorrect), and another which tracks riptide when you do have echo of the elements selected. Echo of the elements causes riptide to have a second charge.
