### ISSUE TITLE
WeakAurasOptions: Aura list broken

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1298]
**Describe the bug**
- Open options (/wa)
- Scroll down in aura list and select an aura that need scrolling to be seen
- Collapse loaded AND not loaded display
- Close options
- Open options
=> no more aura list

(reported by Abby on discord)

**Do you have an error log of what happened?**
no error log

**Screenshots**
![img](https://i.imgur.com/U8O1Veb.png)
![img](https://i.imgur.com/FRPuQk3.gif)

**Comment by emptyrivers** [comment]
I do not know an Abby on discord
