### ISSUE TITLE
Further Glow Options by default

### ISSUE THREAD

**Issue by Zero42** [WeakAuras/WeakAuras2#1299]
As I'm going through the custom glow library, I realized that the ability to change the speed, number of lines and length/thickness would be very nice without having to know how to write the line of code.

If possible, having the aforementioned options easily accessible to the user akin to glow color would be nice. If a low target audience, then they could all be hidden by a "Show More" tab of sorts.

Customizing them myself, which really isn't that much of a hassle

**Comment by emptyrivers** [comment]
Those options weren't included initially because nobody had asked for them, and I had little desire to implement options in the UI for things that people hadn't expressed a desire.

**Comment by emptyrivers** [comment]
This will be available in the next release.
