### ISSUE TITLE
Suggestions: Timed hide for Conditions

### ISSUE THREAD

**Issue by rnyberg** [WeakAuras/WeakAuras2#130]
Would be nice to get a timed hide option for conditions.

**Comment by InfusOnWoW** [comment]
I struggle to see any use case for that. Looking at the conditions trigger, the only one where I can imagine one is the "in combat" condtion. What's use cases did you have in mind?

**Comment by rnyberg** [comment]
Usecases that pop into mind:
- Entering rested area
- In combat notification
- Out of combat notification
- High threat notification (forgot this was under Threat Situation and not under conditions, though)

And ofcourse, you could chain an always active trigger with a timed hide condition to pretty much anything you can come up, as well.

**Comment by InfusOnWoW** [comment]
That aren't use cases. I can imagine some for the entering/leaving combat one, but for rested? In what kind of aura would that be used?

It needs to be useful to more than one person, otherwise it's best served by custom code.

**Comment by rnyberg** [comment]
> In what kind of aura would that be used?

I currently use it for having a popup so I know exactly when I can hit the logout keybind, but I could be the odd one out in that. :)

**Comment by InfusOnWoW** [comment]
Yeah, that sounds like a odd use case. Anyway, entering/leaving combat has probably some value and we don't have that many event triggers. So I've added a trigger for that.
