### ISSUE TITLE
Enhancement to #1301:  Collapsed Conditions don't have descriptive text.

### ISSUE THREAD

**Issue by Hekili** [WeakAuras/WeakAuras2#1302]
**Is your feature request related to a problem? Please describe.**

Porting the collapsible sections from Custom Options to Conditions makes sense, but Custom Options have the benefit of a descriptive name (set by the user in Author Mode).  Conditions are not labeled beyond their index, so these are "Condition 1" and "Condition 2" and so forth.

If you collapse multiple conditions, you have to expand them all again to differentiate them.

**Describe the solution you'd like**

Use the condition's values to confabulate a descriptive name, if possible.  

![image](https://user-images.githubusercontent.com/9438134/56705292-5c5ecb80-66de-11e9-8a14-fe18d8fb6378.png)

In this case, instead of `Condition 1` when collapsed, you could generate:

`1. If Trigger 1 Active Is True Then...`

...and display this rather than just `Condition 1`.  Obviously, more complicated conditions could potentially get very long names, but an abbreviation of the first condition is probably sufficient for most users.

**Describe alternatives you've considered**

Whining at Rivers in Discord while he repeats "submit a ticket" over and over again.

**Additional context**

No.

**Comment by emptyrivers** [comment]
> Whining at Rivers in Discord while he repeats "submit a ticket" over and over again.

rude

**Comment by emptyrivers** [comment]
For seriousness, though, there is a potential issue with localization for auto-generated names. It's non-trivial to translate "If X is Y then do Z" into other languages, and still retain enough flexibility to describe "most" conditions.

**Comment by Hekili** [comment]
Yeah, it's a consideration, but it seems like it would be effectively no different from how the fields used to enter data are organized, so that translation would be no better or worse than what the UI does for an expanded condition.

**Comment by emptyrivers** [comment]
Well to nitpick, the word "is" does not appear anywhere in the Conditions UI, so `1. If Trigger 1 Active Is True Then...` would not correspond with that suggestion. But sure, that makes sense.

**Comment by Hekili** [comment]
`1. If Trigger 1 Active = True Then...`
`1. If Trigger 1 Active (True) Then...`

But yeah, your point stands.

**Comment by InfusOnWoW** [comment]
Also Trigger 1 might not be a very descriptive name as #705 points out.

**Comment by mrbuds** [comment]
This is very close to https://github.com/WeakAuras/WeakAuras2/issues/705 and was solved with https://github.com/WeakAuras/WeakAuras2/pull/4495
