### ISSUE TITLE
Naming Conditions (or providing a description)

### ISSUE THREAD

**Issue by MikeCook9994** [WeakAuras/WeakAuras2#1306]
**Is your feature request related to a problem? Please describe.**
With conjuction and disjunction supported in conditions we're able to create some complex things that only reference some trigger by number. This can create a lot of flipping back and forth and rethinking something I did in the past to understand it again. Being able to name conditions (instead of just condition 1, condition 2, etc...) would help alleviate this problem.

**Describe the solution you'd like**
Allow the name of the condition to be provided in place of the place holder "Condition #". Additionally a more descriptive note can be added to the condition

**Comment by InfusOnWoW** [comment]
That's more or less what https://github.com/WeakAuras/WeakAuras2/issues/1302 is alluding too. (Note that it describes collapsed conditions, which is a feature of one of the next releases.)

And it's related to https://github.com/WeakAuras/WeakAuras2/issues/705.
