### ISSUE TITLE
Profession spell trigger spell known, issue with spell id's 

### ISSUE THREAD

**Issue by Leuze** [WeakAuras/WeakAuras2#1309]
**What steps will reproduce the problem?**

I made a WA for showing clickable buttons for professions, trigger set to spell known: type in profession name. 

**What is the expected output? What do you see instead?**

Expected to then have alchemy button show up on any toon  with alchemy, instead I had to go in and edit the name on every log in for the buttons to be visible. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

2.12

**Was it working in a previous version? If yes, which was the last good one?**

N/A

**Do you have an error log of what happened?** 
 
No, bugsack says no errors.

**Please provide any additional information below:**
After asking in the WA discord and doing some troubleshooting of my own, I think I figured out that it is related to professions having different spell-ids pending on which expansions profession your toon knows. Which could be solved by being able to add in spell-id specific triggers, but on the "spell known" trigger even if you enter a spell id it is converted to text name.
I also edited the button variables so they didn't all share the same, but still no. Temporary work-around for me is to set the trigger to condition: always active and just have separate groups for different characters so they only show 4 profession buttons at a time: 2 main crafting, cooking fire and cooking. 

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**

``` HERE ```
!TZ56onoYsa43fKoAgKolJVKlKvA)rcKmewiHbBGD1QJHo2Ds8GJDo2TjK5h5zFRQTDUAtCUqcgqAeqS70Dvvxv91v32JMOMQMspnfdnfpnfPJefpQa(j4QdB2UThLP143KkjFuPsLYNtssUGSSMYtuxpthBTgIAkU0oWFQoSpf(EdTj9m174643xtHyB2JWW2HJbXK)BgVH2o2yZ9D53)(Gl6r1DSn80yWFYiUS0382M2MEDtD7XbGA1(khtB4pvBELMIVRLMsxgRV3V)TVnG0X5itNV9ZVl)ZbNFzzPVb6j95(eBdQHwlnLNJmnLYjEKGGGOKKqrbzXiDMInI4Z6642SpkcEGSbdfrp6dkGeZcUyKUoTEWLrqCBB2j4oUoSatzdb47cZwx560M65X7oLwe9hrJUnCJgCDh(0anLtBExdCOyuxBI1TJN1abTLJRb1nQ5eBDqwdniNuTHA1RJAsKQkc(fE9j6uTgsWF54I6JNo12W0Udxl60b6qu(q7S5uQThT3t4yb2QJGB7smm99GUrqyArVUnFCGR5Jk4JNrQuuQMA1la3tlhc3Nu3I4XnF98TyMrgkV(u9fVO5VOlCrFp69b9rl(8HLzh7jkmZ1e1bCaAWdm8TdVuGEm5d4qAzv3iubdCWiG)Me(LGzwL(wKHOotFII20ZOelwxWZK0Jgzv8BXVPIF72MpRPC)jLvuVxrT81QtU5vUu(nvUQ6fxaU00wqRdc2oR6fxv7Ml4kg674cDniIegHhxctcWCInRg405acY1LpT(nkrt11Wwh0pkNCD1QGBINoXIIFvOZEc(DojSxgBlgNoqafdpcdJU4o6m6ZmXqFNknvvBE511)(zQVWq9woZWJuA)YOhf7ASnOcovYIixfDhhldNb2vn6WTbrFwfSfvTjTSGefvqP1u)XHNgoCJnw1CW(QMR5Vg9Wp8jg4K2OhubPSJLZGaBvlFgZXUje4aEstLYriOryFnDA4LNaBUOWyspnDQCtWKekTNaslmh1J7ixVHs9tRoLEOGXzneLcUK0C2PUuZoDbPwUWr5NnJgpixOsH(Tg08hMxcd2atdiejSP8olz7e)2jlyrtbTcveyQq33J50dNFUPVb65Q4h(7yZpUyQ6WEatgbrkJEW9pUJsESmm36DuGLZ7F(szl9U0Ed)Y)l8sJopS1T(JrpCIlfgqE8WxpOcF(9G)7Oho4YHt(GlEbfQUVlTmxecULkThKrHrp4WrNp68w)(OhuOSYwwCZT3xpCY1yqwkW3bgbmreV)dYfDqSnINiJ3Qqrp(MHbk8wf0(dHyiN7dnivErkgFMAQ5JXtSboos5W0W97gK06xoq)HU48wPP8F6pEQ2YXnixe(pj(pL5)mxyolWH2zMiSAwKoaCS5nQxuVr1fZqcWamskORHVOHPhAPQRZ9bKliLlgw2yXF(Epkda4gdXpvcLdqf8qpimuLNOyjKS4GwXH3yjWSxbewusqiJW8qR4WmC2jPfa(BDPJbxd9TdPBCtFatSbyJHHUuEHs5JhtcEkma)Z7p(WwzmLubB(Oh(tBWoMEwj2rtg7kjbpzrRa7jQAGvGRhn(nrb8oy6OWqGX59wQp3e)NxSz6lTjm8QRhLnrKXNu2KOhlc62f41ydy5yWbEsLQvTgv(RpTfiRjMIAga7wZ1DzO65tZUIG4555RepznP4vSGQs86zY6c12Kfz5ZOaBBI(yi98a1LsGNIQhTSSfHUIjaDtLZ62GbVsvtIiq3WQjtQCNDkuEkkSKG4XXtPtajNqvNBx68uC)LGKxs1hPWHi5YeW0UZeLGiy5pl099ncMtBlEoXQnR13Ri2CPfsUjC4exy26WHxsSqCaX4n8Ri(fnyN448iFt(24A5IY6VY1QLwcWC4e5sfJbNKI108z1CZwnNO0XzQQ5wZf(f6PNfxYxOO)AS9nPM0gxK8Cl)NHFLpl099pL1QE(BVDyU7U5c7xW7yJHSreL9tTTjV6HvD7MJn9)oOu3W0gJEOMPlndN3lqbE1k1DQ1WST3N58hlKFFxY7kSqLfwU5BJ1OCSygBbkjUzbRaWvmXsBNjQaHU5xtO7IeKpPTVjp825ZYSLp62yRYm2UFvog3uqGrV5QqWcXMnPg0ypaUDYb8oruYIWYjs)(4yEJBnojUzYBTJ9nvB6CUfjWtwA1(DBLN5OD2t7KCXCIIz5DsE12KTL2UGdT7hhAkzwruHkKmohYFw4tY7Ro5n2ul7cQ7Yo7t0r5Ul))21(RYx3w9S9CbVR4MiVvkSDDXSDmTPu3mlNDS4)245PAxqxxsDU5ekiViLnX1mVFHUbR6C8K4(J8MtqUqwM8(Y7832zt6Eb4BXp4NOlhaD2t)6VVYOWzNQ8xV32Q5iA4R3gmVJof3ywS0g(GtnHcSU1MH(o1T90Dn7hKpBRSDOR1r5kjxumUJYDnxEXuAvwC5ftj(B7LxSFXUVr3C5C5LZxmtT9YP4CR2SNFQu9inF8hC677(t6nr44RhpofRhCDjZX7PZxcv)s)5WBnoUCLwxT5G591z9EoDa1s3L0oRU91ZOaVjpR3e2H5CcfL23NX77mMSuEjPsFuzYjFWVZeIGm4sFu3(zEE7HvTF0PV9Tw5p91J9MiSBxwb8lII383NOLFuVVgLaVDFwMxtS5fasSl1DGJBw9zdDwn4d5r)UKnNwUGO4R)raNvEmRMgZkkKPFhIs5Z4zAaVjwvkcAMnedbVW4)z1VVRR(nOYWhnYxQ6PhAE4FVAmWn9jWk2dcoDRXm29Zjna)14LhsLyc2JTZRp08jX3vVgrfKYvAN)FfeB2RH6BZ3Ki5sczSht31BjJJD6ZIRwCSWVVExIsbZoPQD4JdMoVouV3405Wf1(3)

**Comment by InfusOnWoW** [comment]
I've added a "exact spell id" option for the next release. Now, the behaviour of the Spell Known trigger currently is to internally use the spell id that you entered, even while showing the name. In the next release that behaviour is optionally.

If you don't want to wait to the next release, you can use the Cooldown Progress (Spell) trigger with Active on "Always", and the exact spell id unchecked.
