### ISSUE TITLE
Event type custom trigger behaves like Status type

### ISSUE THREAD

**Issue by AlternateFiction** [WeakAuras/WeakAuras2#131]
I'm not sure whether this is intended functionality or not, but since I haven't seen it documented anywhere I'll report it here in the case it isn't intended.

Events used in Status type triggers cause events in Event type triggers to also fire when, for example, the WA configuration window is closed.

(Note: I don't believe the type of aura has any impact on this but I'll list the ones I used to reproduce the issue)

## Steps to reproduce:
**Example 1:**

Create aura 1: Progress Bar
- Trigger: Status > Cast

Create aura 2: Text
- Trigger: Custom > Event
- Event: UNIT_SPELLCAST_START
- Custom Trigger:
`function() print("This should not be printed when WA options is closed") end`

**Example 2:**

Create aura 1: Icon
- Trigger: Custom > Status
- Check On: Event(s)
- Event: PLAYER_ENTERING_WORLD
- Load condition: Never

Create aura 2: Text
- Trigger: Custom > Event
- Event: PLAYER_ENTERING_WORLD
- Custom Trigger:
`function() print("This should not be printed when WA options is closed") end`

**Comment by InfusOnWoW** [comment]
That's a side effect of how that is implemented. I don't think it's ideal, but it's been that way forever.

**Comment by AlternateFiction** [comment]
I figured that may be the case. Then I'd suggest that perhaps this be better documented in the future to avoid people discovering this by things not working as they intended.
