### ISSUE TITLE
health-bar(targettarget) not correct load if ressource-bar(party1) exist

### ISSUE THREAD

**Issue by Celuldor** [WeakAuras/WeakAuras2#1313]
https://wago.io/8WS4ZZPd-
https://wago.io/sRaDyOCMg

The health-bar of the targettarget does not load properly when there is a resource bar from party member 1-4. but this error occurs only about every 2 /reload. and only if the two bars are not together in the same wa group.

**Describe the bug**

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by InfusOnWoW** [comment]
Please fill in the whole template, and do what the template tells you. Especially the part about "**Do you have an error log of what happened?**"
