### ISSUE TITLE
Marrowrend Stacks Bug

### ISSUE THREAD

**Issue by Drowsypill** [WeakAuras/WeakAuras2#1321]
**Describe the bug**

When tracking cooldown progress spell of Marrowrend, I expect to see stacks of bone armor buff stacks using %s in the text field.  This only works when the spell is not on cooldown, or more accurately runes are not on cooldown.  When the death knight has insufficient runes to cast the spell, the weak aura will display a cooldown based on the runes and the stacks of bone armor will stop being tracked.  This used to work in the past, but the most recent release update has made it stop showing the stacks.

**Do you have an error log of what happened?**

It looks like this when ability is usable (have runes):
https://i.imgur.com/UwNUYPO.png
It looks like this when ability is unusable (runes are on cooldown) even when you have bone armor stacks:
https://i.imgur.com/zd1AP4g.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

2.12.3

**Was it working in a previous version? If yes, which was the last good one?**

Yes, all previous release versions.

**Additional context**

The one I use is:
!LAvBVnUnm4Fndy7dxrJt71Daddin1znyTobrUB7dfkvXw2wRksgsYjn3h6V9rkzN4K27UcmGIevsk(YdjFuOdOPuIGMmy4vF(QlUKsSus0zdIoBiLSMsYX)alkL6T0vuIJ)IBWeTYreFLd3kIsynUkTzwTtOvwWwhLSBwrHL7OjNdQvzG65AHcumoojnEbLKP1YC9wfzROMtVge0yD61PG3FOoN54ust73DMgNxYXmqKPv4nASCmPgRLAZ(mlwXwj55O(N586r2AEMBbdsn0elxw0MiPZMFx8eOWY5wMRXGHAvOmdEmfko)Fr(ph6)8c8txBSA901ZstND)IP)XTPbfri8mrYkbKC2dP3nnjMsQ4IYkaqU0JiI1ykPqG16yghEihtcq4s3oasGCfQZCWfH)vPvCmYRzc1h36cHsyR(W2d3qQz((TqvA0n14X1nsNW3xDEuFPIVHhGCMKRCVXMmjZA91g4fj4(BIhLE7FMeGOJmf7p9Seq3J1hIq0BcrUOOqKbs29gvgwg)Dt7qAfMCw6dmCUGL11jo6c1BQ)gvNrlFR)T42WjcD9ghOK41WG56wrhn6eMdTor2Z7UPTn1nqhngUm0YxJzczAcz6nXHP0uFJBvJZPvZG(HKTR325H4b95crzyT8LERLTE)hoQB4Lq(eIMF1RDHEIHTMhetgVioobWsueXbvaZ3j3x9h4k8j4hiQa8WnkM8V4glchjdUS9Ya7eL8vTEnufihLpiuYpzpWuGSi3iSbMGvEckn2R3JoNUCkawU7zgJERHRGZmzDvVsOhPYwrURkSfN9JRIg0X383Jwm56hs(NpRX6cAvwpJxyWZEehGv3GXFkw9WKj)Xr55Zu2hNdy6NgE25psqdSpovvOptxwclc6LHlT6K99JKdIDTsdeTEX4aQruwczuOos3liCKL9Cl653zk5kUrKrQ0BN5PGpwaXcFpsULTZgSVbJA3(gORml)av)Ykrom74eRbKTLgcWbxJf5Kx1uuegUUn(U5tE4oWliTdozFiHS7ZeFOi1WsaK7Kwdh3op86tZn6sd3AF9PFMuZLYFbIvZkVzeisIxOKLJhrsxsshTifh6zsVHjWe9XZgTKhTQU2tHjLtZBF5RZTZnCVBjZJVdsEfyCRfDmXuYGG3c4CNN8UnzWxUCWVg5NHu9Aj23bP7DRHd)YGR8n2KOtAMqG6sygKaD5doJFnq()6tKkbxMhEIXLvXTVxxTfyVfGhyn4BvSFxOn0PXCi6022712pbbAj)T)BJcwF2GEskd7sB4PbZUxddwjFAW5(3IGN5eDlAHrCO4a8Uh8GGWgMrGB5OAMPeahIUMs(DuJSbeFP3Bvmvj)GRc6amT2OR5g41O()EcxVwXBdAu)GYFPweglsf4ehg7FBFSBlLtc(3lMd)FhZpA96)HHUUh86OG3t3(EVFbN2ao8IiKKK(Fd

But the one in your template has the same issue, and is likely an easier one to find the issue for.  (I would think it's a problem of the weak aura tracking the cooldown of runes rather than the ability itself?  making it stop tracking information on marrowrend itself which is where the it would pull the information on bone armor from as it does on the blizzard action bars where it also shows bone armor stacks on marrowrend's icon)
``` HERE ```

**Comment by emptyrivers** [comment]
Enable the "Ignore Rune CD" option.

**Comment by Drowsypill** [comment]
But I want it to show rune cooldown... that's like 50% of its purpose.  The other purpose being to show bone armor stacks.
