### ISSUE TITLE
DBM_TimerUpdate

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1322]
Support the `DBM_TimerUpdate` event which will pass 
`fireEvent("DBM_TimerUpdate ", id, elapsed, totalTime)` 

This would find existing bar by ID, then overwrite elapsed and total with new values

**Comment by mrbuds** [comment]
i think dbm and bw triggers deserve a refactor and additional properties

like for BW:
- emphasize
- ignore cast bar (matched with regex on text)
- spell cast number (regex too, very common request)
- color ?
- drop "BigWigs Addon" ? i don't think anyone use it and it's confusing
- rename adjust timer to offset ?

for DBM the "id" & "spell/encounter id" fields are very confusing
