### ISSUE TITLE
Add 8.2 raid encounter IDs to the encounter ID tooltip

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1326]
No, I don't know what they are :) But raid testing is on thursday, so we should be able to find out quickish.

**Comment by Nightwarden24** [comment]
You can find keys for the [WeakAuras.encounter_table](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/Prototypes.lua#L46) in the ID column of [journalencounter.db2](https://wow.tools/dbc/?dbc=journalencounter.db2), and values -  in the same column of [dungeonencounter.db2](https://wow.tools/dbc/?dbc=dungeonencounter.db2). 

A little advice: see desired values directly at the end of the tables

Probably, these values ​​may still change. It's noteworthy that the 7th column (Field_8_1_5_some_numbers) in the journalencounter table contains a link to encounter IDs, but they are zero for some 8.2 bosses, although these values ​​already exist in the dungeonencounter table
