### ISSUE TITLE
Allowing %values for condition - remaining duration

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1329]
**Is your feature request related to a problem? Please describe.**
I want to make a sound only fire if a) cast is finished and b) i have a certain aura applied to me and I don't want to put in a non%-number since cast times tend to change based on raid-difficulty/nerfs/etc.

on hide -> play sound is not a solution since the player who's targeted by the cast might die, which causes the cast to abort and to play the sound.

**Describe the solution you'd like**
simply allowing %values for remaining duration, e.g 100% to make a sound only fire when the cast finishes/reaches max duration.

**Describe alternatives you've considered**
i could custom code it to make it fire when the cast succeeds but that would require multiple events which makes things a bit more expensive.

**Comment by mrbuds** [comment]
T1: event - combat log - spell cast success
T2: aura 
req activation: all
on show => sound 

"that would require multiple events" what ??

**Comment by Causese** [comment]
i want to show the cast's duration

**Comment by mrbuds** [comment]
you can use a cast trigger + condition if "remaining duration" < 0.1 then play sound

**Comment by Causese** [comment]
was thinking bout that but player might still die at 0.1s

**Comment by mrbuds** [comment]
why not split the task in 2 auras ? 
- one for the cast
- one for the spell cast success event with sound on show

**Comment by Causese** [comment]
the player is immediately pinned by the javelin once the cast succeeds. showing an aura for a second or so just to fire a sound is bit overkill imo.

after that player is pinned, another player with matching color has to free him

**Comment by mrbuds** [comment]
Yeah i get that, i'm giving solutions for doing it without custom but you don't like them :(

The second aura could show a visual clue for those who don't have your sound pack
And i guess both have a debuff/buff so you can use 2 aura trigger

**Comment by Causese** [comment]
the 4s cast visual should be enought of a clue :P
i guess i could make a second trigger that doesn't return true and make it fire via condition

**Comment by emptyrivers** [comment]
This is close enough to #477 that I think any solution we choose for that ticket would solve this one. So I’m going to close this as a duplicate.
