### ISSUE TITLE
Event - Chat Message could use a destName - "player" (unitID) option

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1330]
**Is your feature request related to a problem? Please describe.**
I want to make an aura that shows up if I'm the target of a chat message without having to "hard code" my character's name, basically a unitID option. 
custom coding for this kind of auras should probably not be a thing anymore
example: https://i.gyazo.com/32171296410f9c13db8a6759bd529fda.png

the event in this case is:
`CHAT_MSG_RAID_BOSS_EMOTE: "text", "playerName", "languageName", "channelName", "playerName2", "specialFlags", zoneChannelID, channelIndex, "channelBaseName", unused, lineID, "guid", bnSenderID, isMobile, isSubtitle, hideSenderInLetterbox, supressRaidIcons`

and according to the log, the parameter that I would have to track is playerName2
`"<48.61 22:05:29> [CHAT_MSG_RAID_BOSS_EMOTE] |TInterface\\ICONS\\INV_POLEARM_2H_MISC_SPEARFISHINGROD.BLP:20|t Mageya has been targeted for |cFFFF0000|Hspell:295606|h[Frost Javelin]|h|r!#Abyssal Commander Sivara#blank#blank#Mageya##0#0##0#206#nil#0#false#false#false#false", -- [1575]`

**Describe the solution you'd like**
an option for destUnit == "Player" and an option to exclude myself, in case I want it to fire when someone else is affected by it.

**Describe alternatives you've considered**
custom coding

**Comment by InfusOnWoW** [comment]
I'll add a dest name option, but I don't want to add a dest unit option, as we only have the name not the unit id or the guid of the target and thus can't distinguish between players with the same name.
