### ISSUE TITLE
Combat Log (UNIT_DIED) could use a npcID option since destName is outdated

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1331]
**Is your feature request related to a problem? Please describe.**
If i was to make a weakaura for this mechanic
https://i.gyazo.com/998f4bedb5d32cca17798d5427995f8f.png
then I would have to custom code it since destName isn't viable for a broader audience (localization issues)

the easier way would be to just have a NPCID option.

**Describe the solution you'd like**
a CLEU - Message Prefix (UNIT_DIED) - destination NPC ID option

**Describe alternatives you've considered**
custom coding it or making it english-only by using destName

**Comment by emptyrivers** [comment]
We don’t have a trigger named CLEU ;)
