### ISSUE TITLE
Event Abbreviations for custom triggers

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1332]
**Is your feature request related to a problem? Please describe.**

If I am writing a custom trigger, and I would like to listen to more than one event, then it can be cumbersome to both read and write the event names into the box provided. This is especially true if I want to listen to the combat log, since COMBAT_LOG_EVENT_UNFILTERED is an absurdly long event name.

**Describe the solution you'd like**

For convenience’s sake, I would like to be able to write an abbreviated version of the event name into this box. So, for example, instead of COMBAT_LOG_EVENT_UNFILTERED, I could write CLEU. Instead of ZONE_CHANGED_NEW_AREA, I would like to be able to write ZCNA.

**Describe alternatives you've considered**
We could also convert the event entry box into a UI that mimics the dropdown creation in Custom Options.

**Additional context**
An example of some code that might be close to what we’d do to generate the abbreviations:

```
WeakAuras.event_abbreviations = {}
local ambiguous_abbreviations = {}
for _, event_name in event_list do -- where can we automatically get this?
  local abbr = event_name:gsub("%a+_?", function(m)
      return m:sub(1,1)
  end)
  if not ambiguous_abbreviations[abbr] then
    if WeakAuras.event_abbreviations[abbr] then -- ambiguous! Don’t rely on this abbreviation. 
      WeakAuras.event_abbreviations[abbr] = nil
      ambiguous_abbreviations[abbr] = true
    else
      WeakAuras.event_abbreviations[abbr] = event_name
    end
  end
end```

**Comment by mrbuds** [comment]
I don't like permit to use a lot of cryptic auto-generated event acronyms like ZCNA, i think it will contribute to make weakauras custom code less accessible that what it already is.

But i admit for COMBAT_LOG_EVENT_UNFILTERED, CLEU is well known enough to be used instead and would help make more readable the following idea for improvement.

Right now the generic trigger "Combat Log" register it's triggerdata with it's subevent and is run only for the right subevent. https://github.com/mrbuds/WeakAuras2/blob/a58acf17172faae1ac6ed33c6921ec0859ed0711/WeakAuras/GenericTrigger.lua#L815

Custom code doesn't have that possibility, COMBAT_LOG_EVENT_UNFILTERED is converted to COMBAT_LOG_EVENT_UNFILTERED_CUSTOM and lose the subevent filtering the generic trigger has.

We could make it possible to filter by subevent for custom code with a syntax close to what #1325 add for units like `CLEU:subevent1:subevent2:subevent3`

**Comment by InfusOnWoW** [comment]
Same as Buds, I don't see the value in allowing random abbreviations, especially as that is not future proof. E.g. if UA today maps to only UNIT_AURA it might map to 2 or more matches later. So keeping that backwards compatible would lead to a very strange system.

Accepting CLEU would be okay for me though.

**Comment by nullKomplex** [comment]
> **Describe alternatives you've considered**
> We could also convert the event entry box into a UI that mimics the dropdown creation in Custom Options.

I'd like to :+1: this suggestion personally.

**Comment by InfusOnWoW** [comment]
CLEU is now available, I don't think any other would work.
