### ISSUE TITLE
Double Glow entries for Conditions properties

### ISSUE THREAD

**Issue by sragia** [WeakAuras/WeakAuras2#1339]
**Describe the bug**
Condition properties have 2 glow options. See screenshot

**Do you have an error log of what happened?**
No Error

**To Reproduce**
New Icon aura -> Conditions have double Glow properties

**Screenshots**
https://i.imgur.com/0WtXhWu.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
Currently on ff120bf6c

**Was it working in a previous version? If yes, which was the last good one?**
Probably before new Glow option PR

**Additional context**
If I had to guess, this is at fault https://github.com/WeakAuras/WeakAuras2/pull/1311/files#diff-dcdb2a7a3775e06af65801e3d8409dbaR110 It looks for parent with Glow with new feature string
But that's just a guess and I haven't looked too much into it or how it works (literally 10 sec in that PR)

**Comment by InfusOnWoW** [comment]
This should be fixed.
