### ISSUE TITLE
Weakauras 2.12.4-beta1 not updating with Companion 1.1.9

### ISSUE THREAD

**Issue by GaryREM** [WeakAuras/WeakAuras2#1341]
**Describe the bug**

A weakaura was updated and appears in weakaura companion,
However, when opening the weakauras add-on, the old version is there, but there is no update button.

**Do you have an error log of what happened?**
 

No errors appear for the addon in WoW.

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

weakauras 2.12.4-beta1
weakauras companion 1.1.9

**Was it working in a previous version? If yes, which was the last good one?**

This had been working fine in previous versions.

**Additional context**

``` HERE ```

**Comment by mrbuds** [comment]
Check that WeakAuras Companion addon is enable in your addon list

**Comment by mrbuds** [comment]
If that doesn't solve your issue please come on WeakAuras Discord #companion-support channel

**Comment by GaryREM** [comment]
Of course, it wasn’t ;)  I didn’t realize it existed! 

Thank you!
