### ISSUE TITLE
Provide mechanism for cleaning modified (cloned?) regions before recycling

### ISSUE THREAD

**Issue by Hekili** [WeakAuras/WeakAuras2#1342]
**Is your feature request related to a problem? Please describe.**

Lately, we have seen an increase in cloned auras that may have non-standard frames/textures/texts added via custom code.  These are often not cleaned properly, leading to odd behavior when recycled.

**Describe the solution you'd like**

Option 1:  Provide a function hook for authors using custom code to hide/clear/etc. their added textures/text/etc. when the region is recycled.  I.e., if aura_env.scrub() is not nil, run that function at the appropriate time so I can :Hide() whatever might otherwise appear when the clone is next used.

**Describe alternatives you've considered**

Option 2:  Segregate clones by aura ID so that the recycled clones are not used by other auras.

Option 3:  Custom region types?  So a HekiliPollutedIcon WA isn't part of the same pool as a regular Icon WA?

**Additional context**

Asakawa noted that the upcoming Widget changes may provide mechanisms to address all of this.  An intermediate step might be useful to help avoid a lot of the issues where someone's nameplate-anchoring-glow WA is polluting other WAs and leading to bug reports for the addon instead of the problematic WA.

**Comment by emptyrivers** [comment]
I think that the ability to add a custom subregion/widget/component/whatever we want to call those things, possibly with an optional on create/on reset code box associated with it would be sufficient.

**Comment by InfusOnWoW** [comment]
Custom region types are already possible, but they do involve a bit of too much work for a typical aura.

I think optionally segregating auras per aura id, would be the solution I'd prefer. Although I'd like to first introduce as many as possible features that more or less obsolete what people are using this for.

**Comment by emptyrivers** [comment]
Bump to see if there is still any desire for this request, or if the needs have been obsoleted by now. @Hekili @nullKomplex

**Comment by InfusOnWoW** [comment]
So after pondering this for 9 month, I think the solution is to make OnHide work.

Basically, if you really want to modify the region, (and you shouldn't want too), then do so in OnShow and remove your modifications in OnHide.

The problem there is that OnHide is not always called before reusing a clone, which is something that I'm open to fixing. All I need is to know in which cases OnHide appears to be not called.

**Comment by nullKomplex** [comment]
In addition, OnShow is not always called.
STR:
1. Create aura with debug prints in on show/hide
2. TSU trigger, with any fake event:
```Lua
function(a)
    aura_env.toggle = not aura_env.toggle
    a[1] = { show = aura_env.toggle, changed = true }
    return true
end
```
3. Close and reopen WA options to observe both OnShow and OnHide not firing.

**Comment by Hekili** [comment]
If making OnShow and OnHide more consistent is the solution, we potentially have to deal with the fact that a lot of existing WAs won't have an OnHide that cleans up after itself.

Should we wrap CreateFrame(), when used within the WA environment, so that it will tag the frames to identify the aura that created/caused it?  Is that needed?  It'd help identify problematic auras when answering questions in x-auras-help.

**Comment by InfusOnWoW** [comment]
Wrapping CreateFrame is a interesting idea, which I have considered too.

But, that's entirely orthogonal to making OnShow/OnHide consistent.
