### ISSUE TITLE
Check if Companion is installed but disabled

### ISSUE THREAD

**Issue by InfusOnWoW** [WeakAuras/WeakAuras2#1343]
We do get a few but regular reports of users where they don't see pending updates in game, because a "helpful" addon manager disabled the new addon.

We could detect that the WeakAuras companion addon is installed, but disabled and show a warning in the WeakAuras window.

** Other solutions
Document this better (?)

**Comment by Stanzilla** [comment]
Maybe even force load it? Or too intrusive?
