### ISSUE TITLE
Visual reminder about snap mode

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1344]
We talked about it in the original PR but I think we should at least add a little "plate" aka a square with a text string below the mover icons that says something like "Disable Snap Mode by holding Shift"

**Comment by InfusOnWoW** [comment]
Or maybe add a "toolbar" with a disable snapping.

**Comment by emptyrivers** [comment]
It wouldn’t be hard to whip a toolbar up quickish, if someone provides icons that make sense for the toolbar.

**Comment by InfusOnWoW** [comment]
A magnet next to a yellow line would work.

**Comment by Stanzilla** [comment]
WoW icons would probably look bad at that size, i.e https://www.wowhead.com/item=46029/magnetic-core so maybe something like https://www.iconfinder.com/icons/1895742/attract_magnet_magnetic_magnetism_physic_icon

**Comment by mrbuds** [comment]
Where would you want to show an icon? Next to the "disable import" checkbox on top/right ? I remember we talked about doing this but it was decided to not do it.

**Comment by Stanzilla** [comment]
I can't find my own comment (🤦‍♂) but something like

[/!\ Tip: Hold Shift to disable snapping]

or

[{icon}] [ ] Disable snapping]

**Comment by emptyrivers** [comment]
Honestly I expected this to be added to the list of things that we’d have on a toolbar in the options pane.

**Comment by Stanzilla** [comment]
You mean when we have options like https://github.com/WeakAuras/WeakAuras2/issues/983?

**Comment by emptyrivers** [comment]
No, not at all like that actually.

**Comment by Stanzilla** [comment]
mockups then please!

**Comment by mrbuds** [comment]
I'd like to implement an icon to disable snapping but you guys confused me with all your suggestions and i have no idea what to do
- [ ] Add a small icon in a corner of the selected aura (next to the nudges)
- [ ] Add a checkbox, or a 2 state icon next to the "disable import" checkbox, top right of options
- [ ] A toolbar .. with what ? where ? This suggestion confuse me the most
- [ ] Within a setting screen opened with a button under "External / Import" #983

**Comment by Stanzilla** [comment]
![image](https://user-images.githubusercontent.com/75278/59071575-8ef40a80-88bf-11e9-96b0-8037530d90fc.png)
is what I was thinking of

**Comment by Stanzilla** [comment]
![image](https://user-images.githubusercontent.com/75278/59071679-fe69fa00-88bf-11e9-82d3-a174af2be160.png)
or that

**Comment by mrbuds** [comment]
I think we will get much more request to remove that thing than we have to disable snapping
I was thinking of something like that
![img](https://i.imgur.com/6IUVZxp.png)
clicking the icon change it's color, or something better, i imagine something with a size close to the nudges

**Comment by Stanzilla** [comment]
that bad? :( What if it only showed up during dragging?

**Comment by mrbuds** [comment]
mhm i like, it could show a description of CTRL key too
but the checkbox wouldn't work and some want to get rid of that without holding shift..

**Comment by Causese** [comment]
https://i.gyazo.com/1b2839d3a957211ef71f7ad2630d4928.png

sick photoshop skillz

**Comment by sragia** [comment]
I feel like people that want it to be disabled, want it everywhere, not just for 1 aura. Also clicking one small button to disable it in my opinion is still annoying if you are moving loads of auras.


Causese suggestion is best one here imo, or have some kind of small box of checkboxes in lover right of screen or something that shows up when options are open

**Comment by InfusOnWoW** [comment]
![Snap Toolbar](https://user-images.githubusercontent.com/12950521/59150883-98e64c80-8a2a-11e9-9860-3b94431eacd9.png)

What I had in mind looks like the screenshot. The New buton is a bit strange in the sidebar anyway, and import could be a top-level item too.

**Comment by Stanzilla** [comment]
We should split this in two things, one is a short time "reminder" kind of thing I proposed with the panel, the other is our long term solution for settings, which we were talking about here https://github.com/WeakAuras/WeakAuras2/issues/983

Now, do we want a short turn solution / quick toggle option for snapping that will later move into the options "regiontype" or just a reminder for people until we have those options?

**Comment by InfusOnWoW** [comment]
I don't think the snap on/off toggle should be in a options panel. In a drawing/painting app, you wouldn't put a similar option into the options either.

**Comment by Stanzilla** [comment]
makes sense yeah
