### ISSUE TITLE
(Re-)Add Remaining Time to "Aura(s) Missing" Triggers

### ISSUE THREAD

**Issue by DatBear** [WeakAuras/WeakAuras2#1348]
When switching from Aura(s) Found to Aura(s) Missing, the Remaining Time option goes away, but I don't think it should, because it removes functionality and turns one trigger into two.

If I'm trying to track an aura that is either missing or below 4 seconds remaining...
Legacy Aura Triggers: Make an Aura(s) Missing Trigger and set Remaining Time to ">= 4" 

"New" Aura Triggers: make an Aura(s) Missing trigger, and then make an Aura(s) Found trigger, and set Remaining Time to "<= 4", and modify required for activation to "Any," or if you have more triggers needed, make a custom function since you now probably need, for example, "(t[1] or t[2]) and t[3]"

It just complicates triggers a lot for me, and I'm not sure why it was removed when converting to new auras. It also messes up when converting old auras in this format, since the Time Remaining doesn't carry over correctly I believe.

**Comment by InfusOnWoW** [comment]
That is no longer supportable due to how the internal system works.
