### ISSUE TITLE
Weakaura for power (mana) shows my mana (319) as duplicate (319319)

### ISSUE THREAD

**Issue by MalikenGD** [WeakAuras/WeakAuras2#1350]
**What steps will reproduce the problem?**
https://i.imgur.com/2GCl8Po.jpg
https://i.imgur.com/Y9BUPgw.jpg

This is the only changes I made, I did not edit DISPLAY, CONDITIONS, etc. Only TRIGGER.

**What is the expected output? What do you see instead?**
My mana is 319, but it is showing 319319. It should show 319. 
The progress bar functionality (depleting/lowering the bar when I spend mana) works, just not the number

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
## Version: @project-version@ (thats from the weakauras.toc, but its the latest as of this time. Classic version)

**Was it working in a previous version? If yes, which was the last good one?**
N/A

**Do you have an error log of what happened?** 
N/A

**Comment by MalikenGD** [comment]
https://pastebin.com/zEshmsgA This is the export

**Comment by mrbuds** [comment]
What you see is the "stacks" that can you disable, it's the same thing on live and i don't think changing the behavior now is a good idea.
