### ISSUE TITLE
Option key resets on change in (dynamic) group custom options 

### ISSUE THREAD

**Issue by NaR00W** [WeakAuras/WeakAuras2#1352]
**Describe the bug**
If you go into Author Mode with a (dynamic) group selected, then you can configure most things just fine. But if you attempt to change an option key's value then it resets to what it was before. If you navigate to the WA icon and try the same under its Custom Options then it works just fine. 

**To Reproduce**
1) Have a dynamic group with 1 WA in it
2) Select group
3) Go to Custom Options
4) Add toggle
5) Change toggle's Option Key
6) It'll reset back
7) Repeat the same but on the WA itself
8) It won't reset

**Screenshots**

https://gyazo.com/9f5db431f3dc41557fcfa8a982e7b292

**Comment by emptyrivers** [comment]
This is fixed (or, rather it is rendered moot) by a change in #1295
