### ISSUE TITLE
custom conditions overlay color error

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#1356]
**Describe the bug**

When creating TSU aura with custom overlay conditions
```
{    
    additionalProgress = {
        [1] = {}
    },
}
```
and then setting a color for them in the conditions then if some clones missing a state value of `additionalProgress = {[1] = {}},` WA errors 
Do i need to add `additionalProgress` field to the state all the time no matter what?
**Do you have an error log of what happened?**
 
https://i.imgur.com/MMbIEtS.png
**To Reproduce**
 
Create TSU with custom conditions overlay but without additional progress set in the state and then try to change overlay colors in the conditions
**Screenshots**

-
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

-
**Which version of WeakAuras are you using?**

2.12.3
**Was it working in a previous version? If yes, which was the last good one?**

no idea, guess not
**Additional context**

editing line 529 in `\RegionTypes\AuraBar.lua` to
```if self.extraTextures[id] then self.extraTextures[id]:SetVertexColor(unpack(color)); end```
removing the errors

``` HERE ```

**Comment by mrbuds** [comment]
can you export it ?

**Comment by Translitdk** [comment]
https://wago.io/WbVLvMmVs
Trigger line 87, 198, 309. If this state value doesn't exists WA errors.
Can test on anything that will attack you
