### ISSUE TITLE
BigWigs Timer Trigger Misfiring

### ISSUE THREAD

**Issue by Cistoran** [WeakAuras/WeakAuras2#1358]
**Describe the bug**
Certain auras that utilize the BigWigs Timer trigger are firing seemingly randomly when loaded even though they should not be.

**Do you have an error log of what happened?**
No errors were thrown that I could see.

**To Reproduce**
1. Import this aura (https://wago.io/Uej5o9Q5K)
2. Start a Jaina encounter (I noticed it on heroic but it may work on LFR or Normal?)
3. Note how in P1 there is no Glacial Ray timer but the aura still fires.

**Screenshots**
https://www.twitch.tv/videos/428978702?t=01h27m50s

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did not test it with only WeakAuras enabled.

**Which version of WeakAuras are you using?**
2.12.4-beta4

**Was it working in a previous version? If yes, which was the last good one?**
Yes it worked in the previous version. I want to say 2.12.3 but not 100% sure on that.

**Additional context**
N/A

https://wago.io/Uej5o9Q5K

**Comment by mrbuds** [comment]
Indeed there is a bug with text comparison, thanks for the report
As a workaround you can use the spell Id until it's fixed
