### ISSUE TITLE
Everytime I Fel rush, Blade Dance and Eye Beam lights up, even with insufficient resources. 

### ISSUE THREAD

**Issue by Frozdh** [WeakAuras/WeakAuras2#1366]
As the title says, Everytime I use Fel Rush, my Blade Dance and Eye Beam thinks it has sufficient resources in the Fel Rush window. 

Here is a short clip of the problem:
https://clips.twitch.tv/ToughEnjoyableGalagoNotLikeThis

Here`s the string: 
https://wago.io/XW1AnPBxf

I only want Blade Dance and Eye Beam to light up when I have _sufficient_ resources.

Kindly regards Frozdh

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/1235#issuecomment-473492863

**Comment by mrbuds** [comment]
if you replace the resource condition with a spell usable condition it works like you want
