### ISSUE TITLE
8.2 PlaySoundFile

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1367]
It has been reported that PlaySoundFile had some change that may affecting us for 8.2.

I leave it here so we don't forget to track if this issue remain on futur 8.2 live and if we need to address it or not

Copy from UI Dev irc-mirror:
![img](https://i.imgur.com/WUjji2f.png)

**Comment by Causese** [comment]
nice timing. discovered an error few min ago.

`3x WeakAurasOptions\ActionOptions.lua:48: PlaySoundFile Error - Invalid fileDataID for sound.`

to reproduce:
on show/hide - play sound - click sound by kit id or custom. both cause the error

**Comment by mrbuds** [comment]
Fixed (and tested) on ptr
