### ISSUE TITLE
using UnitEffectiveLevel in triggers and load conditions

### ISSUE THREAD

**Issue by Ironii** [WeakAuras/WeakAuras2#1368]
**Is your feature request related to a problem? Please describe.**
Legendary items (among other things) require your effective level to be under 116, so you can use them in content where your level is reduced under the requirement.

**Describe the solution you'd like**
"Effective level" load condition and/or "Effective level" option under Status -> Unit Characteristics

**Comment by InfusOnWoW** [comment]
This is part of the next release.
