### ISSUE TITLE
Changing triggers from group selection returns you to a WA perspective

### ISSUE THREAD

**Issue by NaR00W** [WeakAuras/WeakAuras2#1371]
**Describe the bug**
If you have a (dynamic) group with 1 WA in it, you can change everything as though you had the 1 WA selected, while having the group selected.        
When you have the group selected you have the "Group" panel option, when you have the WA selected you don't have that.          
If you open code view and change something, you always go back to the view without the "Group" panel - even though the left-side overview still indicates that you have the group selected., 

**To Reproduce**

1. Add Dynamic group
2. Add 1 WA
3. Select the group
4. Write code in a custom trigger
5. See that "Group" disappears when you close the code viewer 

**Screenshots**
The dynamic group is selected on the left, the "Group" panel isn't shown on the right: 
https://gyazo.com/6ad688a754464364c2597a826d720eea

Video of the thing in action:
https://gyazo.com/e1b0bd6661a45240fb38b8485831cbc0

**Comment by InfusOnWoW** [comment]
We haven't forgotten about this bug, we can reproduce it, so there's nothing that we need to ask.

**Comment by InfusOnWoW** [comment]
This is actually already fixed via my text PR. No idea why, but it is.

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release.
