### ISSUE TITLE
"Overlay" Cost of Casts for texts

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#1372]
**Is your feature request related to a problem? Please describe.**
I like the "Overlay Cost of Casts" feature for powerbars. I think the same concept would be really usefull for texts too.

**Describe the solution you'd like**
The soul shard bar and the counter above it are both WA's. While i can overlay the cost of the powerbar i don't see any similar option for the text weakaura (soul shard count) above it. So if you take the screenshot i'd like if it shows a 1 instead of a 3 because i'm casting Chaos Bolt.

![6d74b518e9dddc36d213923829a29658](https://user-images.githubusercontent.com/51278436/58755856-bd9f6900-84ec-11e9-9e76-5cfff20a8cfa.png)

**Comment by InfusOnWoW** [comment]
%cost is not documented but works.
