### ISSUE TITLE
[alpha-ptronly] some GetPoint:() error

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1373]
**Describe the bug**
i saw a invisible icon inbetween two visible icons (dynamic group), no idea if related to the error.
looked definitely bugged

**Do you have an error log of what happened?**
```
2x WeakAuras\WeakAuras-2.12.4-beta4-9-g29158a8.lua:3831: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetPoint().
[C]: in function `GetPoint'
WeakAuras\WeakAuras-2.12.4-beta4-9-g29158a8.lua:3831: in function `Animate'
...aceWeakAuras\RegionTypes\RegionPrototype.lua:474: in function <...aceWeakAuras\RegionTypes\RegionPrototype.lua:473>
...aceWeakAuras\RegionTypes\RegionPrototype.lua:554: in function `Expand'
WeakAuras\WeakAuras-2.12.4-beta4-9-g29158a8.lua:4709: in function <WeakAuras\WeakAuras.lua:4659>
WeakAuras\WeakAuras-2.12.4-beta4-9-g29158a8.lua:4765: in function <WeakAuras\WeakAuras.lua:4751>
WeakAuras\WeakAuras-2.12.4-beta4-9-g29158a8.lua:4853: in function `UpdatedTriggerState'
WeakAuras\GenericTrigger.lua:677: in function `ScanEventsInternal'
WeakAuras\GenericTrigger.lua:632: in function `ScanEvents'
WeakAuras\GenericTrigger.lua:721: in function <WeakAuras\GenericTrigger.lua:712>
```

Locals:
InCombatSkipped

**To Reproduce**
can't

**Which version**
![](https://i.gyazo.com/9a333b55218cd0d2f529998415b368b1.png)

**Comment by emptyrivers** [comment]
That sounds like you have an aura which is trying to do things to nameplates. That's not allowed anymore, so go and remove the aura which is doing that.

**Comment by emptyrivers** [comment]
On second thought, it's probably wise to defend against auras which anchor themselves to nameplates, anyways.

**Comment by InfusOnWoW** [comment]
The settings are missing.

**Comment by Causese** [comment]
import: https://wago.io/kJ-FksbTa
to reproduce:
apply debuffs to enemy nameplates, do a 360° spin and it will cause the error.
this only happens while the aura is in a dynamic group

**Comment by InfusOnWoW** [comment]
Should be fixed in the next release.
