### ISSUE TITLE
Anchored to Screen

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1374]
**Is your feature request related to a problem? Please describe.**
We have an option for anchoring auras to "Screen/Parent Group"
If an aura is in a group and i want to anchor it to Screen i must choose "Select Frame" and type myself "UIParent"

**Describe the solution you'd like**
An other option for "Screen"

**Comment by emptyrivers** [comment]
Are there really that many people who want this? This sounds like a workaround for organization problems, so eg tags could solve this same problem more generally. 

Since it is possible to specify the screen specifically, I don’t think we need to do anything just yet.
