### ISSUE TITLE
Being able to return Custom Options Color in the Custom Color Animations

### ISSUE THREAD

**Issue by DevoidCoding** [WeakAuras/WeakAuras2#1377]
**Is your feature request related to a problem? Please describe.**
Actually, to return the color get in the custom options, you need to do that
```lua
function()
    local customColor = aura_env.config["myCustomColor"]
    return customColor[1], customColor[2], customColor[3], customColor[4]
end
```

**Describe the solution you'd like**
Returning the object like that
```lua
function()
    return aura_env.config["myCustomColor"]
end
```

**Describe alternatives you've considered**
None except the actual solution :')

**Additional context**
I'm returning a color based on the role of each player in the group. But still, it would be a lot of contexts.

**Comment by emptyrivers** [comment]
What's wrong with using `unpack`?

e.g.
```lua
function()
  if UnitIsDeadOrGhost("player") then
    return unpack(aura_env.config.deadColor)
  end
  return 1, 1, 1, 1
end
```

**Comment by InfusOnWoW** [comment]
No response from reporter.
