### ISSUE TITLE
Re-add scaling glow as an option.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1380]
**Is your feature request related to a problem? Please describe.**
Prior to the expanded glow options that allow you to customize your glow's settings, your glow automatically scaled to the size of the icon. I'd like to see that feature return (and ideally be the default selection, as this change was kind of jarring, but there's no way to retroactively fix the auras already impacted by this change I'd imagine).

**Describe the solution you'd like**
A checkbox in the new glow options that will cause the glow to auto-scale as it did previously. Potential implementation: Below Color, above rest of settings. Labeled something like Automatic. Disables other settings options when enabled.

**Describe alternatives you've considered**
A drop down box that hides the other options when selecting Automatic.

**Additional context**
There have been several reports about the new pixel glow. Initially I thought the defaults were just changed (actually can you make the defaults smaller too while you're at it please? It's way too thick) but I was told it used to automatically scale previously.

**Comment by ehern87** [comment]
I think this might be related to the issue I am having now...

I use [this weakaura](https://wago.io/HyLk5Zgy4) to track my potion cooldowns in combat and the pixel glow when a battle potion is active is completely messed up with the newest version. It ends up being a giant thick white square that covers most of the icon. I looked through the trigger options and I don't see any options for adjusting the size, I can only change the glow type and color, it sounds like I am having problems due to the lack of auto-scaling that OP is talking about.

**Comment by mrbuds** [comment]
You can click on the pencil icon and you will see more options @ehern87

**Comment by mrbuds** [comment]
I think people have to get used to click the pencil icon for advanced settings, the pencil widget will be used more with next new features.

**Comment by ehern87** [comment]
> You can click on the pencil icon and you will see more options @ehern87

Thanks, found it. Didn't realize I had to look in the display tab since the the glow is actually being triggered by conditions.

**Comment by mrbuds** [comment]
Before the new settings were added, LibCustomGlow received nil and the lib compute a default values from the size of the given frame.

To be able to send nil for each of the parameters, we need to add a toggle in display + a new glow condition for each of these parameters, like it's done for "Custom Color"
- Lines & Particles
- Frequency
- Thickness
- Length
- Scale

I'm not 100% against the idea, but we trade simplicity for little gain i think, but knowing that it's already like that for the color option i don't know...
What is your stance on that @InfusOnWoW @emptyrivers @Stanzilla ?

**Comment by emptyrivers** [comment]
I'd rather not do that. This is a majorly confusing point on glow color for a lot of users, and I don't relish the idea of extending that confusion.

**Comment by InfusOnWoW** [comment]
Ah okay, so it was calculating a default scale value. That's a unfortunate that we didn't catch that behaviour change, but as rivers said adding options for all of  these is not good.
