### ISSUE TITLE
load / Player Level

### ISSUE THREAD

**Issue by Sooleawa** [WeakAuras/WeakAuras2#1381]
In weakauras,  load / Player Level .  there is no option to set it up  so its like when player level is between 2 values? If no, i would like to request it as a new feature to set up level ranges.
*i am only a beginner user,  so if its a stupid idea,  already done, or unimportant,  just close this.
Thank You.

**Comment by mrbuds** [comment]
What is the use case ?

**Comment by Sooleawa** [comment]
my personal case is that  between level 98-110,  i would like to hasten my leveling up with legion invasions. I do have invasion timer / warning auras, but i would like to show it only on characters that actually care about this timer (in that level range).

**Comment by mrbuds** [comment]
The zone group id load condition seems more fit for your need

**Comment by Sooleawa** [comment]
unless if i am in a non-legion zone, doing ah stuff.  would miss loading aura.   or show on an inappropriate level one, if i fly over handing in a quest, in a legion zone.
Will figure out something,  combining these in multiple load options,  thanks :)
