### ISSUE TITLE
Add individual triggers to "Required for Activation"

### ISSUE THREAD

**Issue by Hekili** [WeakAuras/WeakAuras2#1382]
**Is your feature request related to a problem? Please describe.**

Right now, the Required for Activation dropdown has 3 options:  All Triggers, Any Triggers, and Custom Function.  However, since Conditions has been implemented, it's not uncommon to see auras developed that have a single main trigger to determine whether to show/hide, but other triggers included for making conditional changes to how the aura is displayed.  'Any Triggers' may lead to an ancillary trigger causing the aura to show, when the main trigger isn't shown.  Obviously, a Custom Function can be created to handle the specific trigger (`function(t) return t[1] end`) but there is a pretty big gulf between selecting from a dropdown and having any confidence in writing custom code.

**Describe the solution you'd like**

Add each trigger to the "Required for Activation" dropdown, perhaps as "Specific Trigger: Trigger 1" or just "Trigger 1", "Trigger 2", etc.  This would have to dynamically populate in case people do something really weird.

**Describe alternatives you've considered**

Using a Custom Function is the present solution, but is probably intimidating to some users.

**Additional context**

This is probably the most critical feature request in WeakAuras history.

**Comment by emptyrivers** [comment]
Duplicate-ish of #1236
