### ISSUE TITLE
API CreateMacro and EditMacro

### ISSUE THREAD

**Issue by gjfLeo** [WeakAuras/WeakAuras2#1385]
Can I use WoW API CreateMacro and EditMacro? Now they are considered as blocked functions. 

If it's necessary to block them, is there any way to use them only out of combat?

If I make a copy such as `MyCreateMacro = CreateMacro` in some lua file, I can use the copy in aura environments. But is there any way to do this only in WeakAuras's options?

(Sorry for my poor English)

**Comment by InfusOnWoW** [comment]
No, we blocked those functions because they can be abused.

**Comment by ESpmdark** [comment]
Sorry for necroing this issue, but I guess its better than creating yet another issue.

I dont fully understand why you felt the need to block the functions.
Blizzard has already placed blocks for the functions in their API, making it required for the player to NOT be in combat.
This already stops any possible abuse of the functions.

The blocks that weakaura has put in place is overkill imo.
Please reconsider this feature request.

**Comment by InfusOnWoW** [comment]
You don't understand why we block those functions. It has nothing to do with botting your rotation.

**Comment by ESpmdark** [comment]
Indeed, I do not. As is why I'm asking.

So let me ask a final question:
Is the reason for the block of these 2 functions something you can share with us?

**Comment by InfusOnWoW** [comment]
Because we don't want auras be able to change the user's macros at all.

**Comment by Elehiggle** [comment]
For anyone stumbling upon this thread, you can still use EditMacro in WA via a secure button if you don't mind clicking when necessary.

```
local r = WeakAuras.regions[aura_env.id].region
local b = CreateFrame("Button", "SwitchPetInMacroButton", r, "SecureActionButtonTemplate")
b:SetAllPoints()
b:SetAttribute("type","macro")
b:SetAttribute("macrotext", "/run EditMacro(\"testtest\", nil, nil, \"#showtooltip Coordinated Assault\")")
```
