### ISSUE TITLE
Classic vs. Live Import Check

### ISSUE THREAD

**Issue by jec324** [WeakAuras/WeakAuras2#1386]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When importing either a classic or live aura on the opposite game version it alerts the user and informs them the aura may not work as intended.  Something that ties in the import string the game version it was created on. 

**Describe alternatives you've considered**
N/A

**Additional context**
With classic coming full steam there's going to be a host of people who will be importing new auras.  While basic triggers will likely function fine based on game version there's some that will simply not work.  This will become a problem for both End Users as well those trying to debug the issue.  If it's known the issue is a game version and the user is looking for a port they can be more directly assisted and the problem solved faster.  

Additionally, this could help wago by sorting those strings on import into a category for "classic" or "live" as they are added to the site.

**Comment by mrbuds** [comment]
A "tocbuild" field was already added on the Classic PR https://github.com/WeakAuras/WeakAuras2/pull/1347/commits/423bdd22f1f2c8bc1bd0723639fa286f03558ba2 Wago will use it.

I added a red text on import to show if it was exported from classic and you are on retail, and vice versa
![img](https://i.imgur.com/jsTQXFV.png)

I have not committed it yet, do you things that's enough ?

**Comment by jec324** [comment]
I personally think that's absolutely plenty.  Between that and the fact Wago will likely show it's "Classic" as a tag or something similar it should be really good.
