### ISSUE TITLE
child_envs update too infrequently

### ISSUE THREAD

**Issue by NaR00W** [WeakAuras/WeakAuras2#1389]
**Describe the bug**
I'm taking information defined in a WA's aura_env.config and using it in a custom grow function, through child_envs. 
The information only update when I /reload. 

I'm doing the following to get config information (in the CustomGrow):
local distance = aura_env.child_envs[1].config.iDistance

**To Reproduce**
1. Define a custom option, a number for instance
2. Retrieve from a customGrow function with child_envs 
3. See that it remains the same no matter how much you change it, until you reload

**Comment by InfusOnWoW** [comment]
It'll help if you attach a aura that shows the problem.

**Comment by NaR00W** [comment]
https://wago.io/Wtxr-AR0h
