### ISSUE TITLE
Typo in BuffTrigger2.lua

### ISSUE THREAD

**Issue by Fayap** [WeakAuras/WeakAuras2#1393]
**Describe the bug**
Scimming through the code, I think I have found a typo in [BuffTrigger2.lua:730](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/BuffTrigger2.lua#L730). It seems like it's supposed to be: `unit == "nameplate"`.

I would suggest you check that this is actually necessary, though, since I didn't find that bug through wrong behavior. I have no idea what that line actually does/when it is called so I cannot test if the line actually causes undesired behavior. 

**Do you have an error log of what happened?**
No. Just check the code.

**To Reproduce**
Check the code at [BuffTrigger2.lua:730](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/BuffTrigger2.lua#L730).

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
As stated above, I have not been able to reproduce the bug or even verify that it is in fact a bug, but the line has definitionally undesired behavior. 

**Which version of WeakAuras are you using?**
I check the master branch

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by Stanzilla** [comment]
Great find, thank you!
