### ISSUE TITLE
Feature that allows other triggers to use the unit that Dynamic Info is set to.

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1398]
**Is your feature request related to a problem? Please describe.**
Often non-aura triggers lack the amount of units that you can set the trigger to so it would be nice if you could just grab the unit that the currently selected dynamic information uses.

I think this would especially be powerful if the trigger you set dynamic info to is a TSU.

**Describe the solution you'd like**
So let's say you have 2 triggers.
Dynamic Information set to t[1]
t[1] aura - debuff group
t[2] status - range check

If you set dynamic info to t[1], another dropdown appears in any other trigger's unit dropdown that's named "Dynamic Info" or w/e.
Upon clicking it, another box appears that allows you to specify it further, similar to the "specified unit" box. There you can add things like "target", so if t[1]'s unit is raid4, then it becomes raid4target.

**Describe alternatives you've considered**
custom coding

**Additional context**
I assumed this would be the easiest to implement since you can just grab the unit that Dynamic Information is set to. 
With text rewrite branch dynamic info won't be as important anymore so this could add some usefulness to it

**Comment by mrbuds** [comment]
Triggers are independent, they can't know the state of another trigger.
