### ISSUE TITLE
Suggestion: Groups within Groups.

### ISSUE THREAD

**Issue by Killobyte** [WeakAuras/WeakAuras2#141]
I use weakauras for everything.  To make it so that I don't get overwhelmed, I tend to create a group for a specific toon that contains all of the auras I use.  However there are times that I cannot do this.  An example would be that I use several auras for my healing character that are stationary, however there are 4 that I would like to adjust their position dynamically.  I either have to do them in a separate group all their own(cluttered) or just have specific positions they never move out of(clunky).  If you could put a dynamic group inside of a normal group that would allow for this functionality

**Comment by krazyito65** [comment]
I cannot find the old ticket that was created, but basically from what I understand there would have to be a major refactor or change in the weak auras code to support groups within groups.   It was an ongoing issue for a long time, but in the end it was shot down and not do-able.

Infus may be able to find the old ticket with info in it.

**Comment by Stanzilla** [comment]
Yup, chime in here https://www.wowace.com/projects/weakauras-2/issues/64
