### ISSUE TITLE
SexyMap with WeakAuras is causing drop-down menus to get scrambled

### ISSUE THREAD

**Issue by jjholleman** [WeakAuras/WeakAuras2#1416]
Since updating to SexyMap v8.1.2 I'm experiencing this error. SexyMap is scrambling items in WeakAuras drop down menus like this:
~~The error is similiar to #957~~ (probably not)   
  
![image](https://user-images.githubusercontent.com/6916881/59969549-f52f8d00-954f-11e9-80c0-185991484a07.png)
  
How it is supposed to look:
![image](https://user-images.githubusercontent.com/6916881/59969579-d54c9900-9550-11e9-93a1-064d45456501.png)
  
This bug only occurs when SexyMap and WeakAuras are both enabled.
SexyMap v8.1.2
WeakAuras 2.12.4.2 

I'm unsure if this is because of SexyMap or because of WeakAuras, therefore I've opened an issue in both addons repositories. (https://github.com/funkydude/SexyMap/issues/56)

**Comment by InfusOnWoW** [comment]
I believe, this was caused by a change in AceGui, which was already reverted. The next release of sexymap should fix it automatically.

**Comment by InfusOnWoW** [comment]
Or if you impatient, download from https://www.wowace.com/projects/ace3/files and replace the libs/AceGUI-3.0 folder with the one from the download.

**Comment by mrbuds** [comment]
Sexymap was just updated and it fix the issue
