### ISSUE TITLE
Request for anchoring to a frame that is currently not visible because Triggers not met

### ISSUE THREAD

**Issue by Konghol** [WeakAuras/WeakAuras2#142]
What steps will reproduce the problem?
* create a WA Icon (Calling it WA_1) that has a display trigger
* Create another WA Icon (Calling it WA_2) that is anchored to WA_1 and also has it's own display triggers. (i.e. doesn't have the same display triggers as WA_1)
* Issue: When WA_1's display triggers are not met, but WA_2's display triggers are met, WA_2 does _NOT_ display.

What is the expected output? What do you see instead?
* Expected output: To see WA_2 when WA_2 display triggers are met

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
* No

What version of WeakAuras are you using?
* 2.2.2.6

Was it working in a previous version? If yes, which was the last good one?
* No, previous version I use did not support anchoring to frames

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
* Bug does not generate an error

Please provide any additional information below.
* I love the anchoring of frames! Can't wait till all the bugs are worked out. Keep up the good work dev(s)!
* I'm pretty new to WAs. Sorry if some of the terminology I used seems off.

**Comment by InfusOnWoW** [comment]
That's intentional.

**Comment by Konghol** [comment]
Can an option be added to anchor to frame always? 

It seems like anchors are a great way to keep relevant WAs positioned correctly, even if some of the WAs are not visible due to trigger conditions.

**Comment by InfusOnWoW** [comment]
No, it's intentionally that way. The position of hidden auras is undefined, if e.g. the aura is in a dynamic group.

**Comment by Konghol** [comment]
Gotcha. I guess I can still maintain a group around an anchored point - I'd just need to make a dummy icon that is always loaded and alpha 0. Perhaps there is a better way to do this in general and I've just not been exposed to it.
