### ISSUE TITLE
PlaySoundFile Error - Invalid fileDataID for sound.

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1421]
**Describe the bug**
I expected it to only attempt to play the sound if a) box is ticked and b) the author's sharedmedia addon is installed, instead it plays the sound regardless of the sharedmedia addon being installed / the play sound box being enabled. (which then causes an error)

**Do you have an error log of what happened?**
```
4x ...aceWeakAuras\RegionTypes\RegionPrototype.lua:168: 
/w[C]: in function `PlaySoundFile'
...aceWeakAuras\RegionTypes\RegionPrototype.lua:168: in function <...aceWeakAuras\RegionTypes\RegionPrototype.lua:143>
...aceWeakAuras\RegionTypes\RegionPrototype.lua:180: in function `SoundPlay'
[string "--[[ Error in 'New 5' ]] local newActiveCon..."]:31: in function `?'
WeakAuras\WeakAuras-2.13.0.lua:4834: in function <WeakAuras\WeakAuras.lua:4814>
WeakAuras\WeakAuras-2.13.0.lua:4916: in function `UpdatedTriggerState'
WeakAuras\BuffTrigger2.lua:1070: in function <WeakAuras\BuffTrigger2.lua:908>
WeakAuras\BuffTrigger2.lua:1227: in function <WeakAuras\BuffTrigger2.lua:1223>
WeakAuras\BuffTrigger2.lua:1508: in function <WeakAuras\BuffTrigger2.lua:1501>

Locals:
(*temporary) = "Addons\SharedMedia_Causese\sound\Dodge.ogg"
(*temporary) = "Master"

```

**To Reproduce**
1. import: https://wago.io/RSkLBKQTA
2. closing options will fire the error unless you have my sharedmedia installed
2a. closing options will also fire the sound with my sharedmedia addon installed, regardless of the Play Sound checkbox being unticked. (same for the error)

**Which version of WeakAuras are you using?**
2.13.0

**Additional Context**
Tested on US trial account (8.2)

**Comment by teyasio** [comment]
Well I found a sound file weak auras trying to play
Sound\interface\iQuestActivate
I searched all my addons, everything, every file, every sub folder etc for iQuestActivate
Only place I found it was in sharedmedia in a comment
LSM:Register("sound", "Quest Added", 567400)          -- Sound\INTERFACE\iQuestActivate.ogg

So not sure where its finding that path from, since it don't exist anywhere
