### ISSUE TITLE
Quirk in HP trigger aura

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1422]
**Describe the bug**

Sometimes, my aura that shows me an alert when my target is below a certain hp threshold shows a cooldown when it activates

**Do you have an error log of what happened?**
No error

**To Reproduce**
 

**Screenshots**

![image](https://user-images.githubusercontent.com/75278/60141770-0cbc7f00-97b7-11e9-87e5-c04ff2945802.png)

Video: https://dl.dropboxusercontent.com/s/ho6roxaltfzj0so/2019-06-25_16-21-50.mp4
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I tried with OmniCC on and off but could repro with both.

**Which version of WeakAuras are you using?**

2.13.0

**Was it working in a previous version? If yes, which was the last good one?**

I don't remember

**Additional context**
I like trains

``` !nAvBVnUnm4Fndy7d3HM0UdBa3oGMuNR5qQtxK7HTV4efBABTQi5jjN2CFi)2hPKCsAx2TIe4xOOiFi5dPC(G8SC2MCwj9hF0bp7gEVwOC5SXjPzjlcYgmrRCmX3G80HxKZ4DUgTzERtOvwCFO27MxvzbxEkTSQax(vMHx0RnZ64gh9qPEPv3PkZxtMqOe9sl6So9guml(eJuOc1W249NlIvcx5SjgX32V6374LgUJVFvgALhbO9ABlu4wWrpt2YcYQxHQsWYDD4UasHAP(PXAP2G(iDG))q)1l9xVIUg98GOHgnplB(DlM(5BZobstK8ABoB(dzZMMMKZKAUp)ku1gDxRpR3jDI(yPZclvWwW4dzj3gYtO6siND31Fo5mBiO3OCMrJADotsHpPGLQCVwbhxck3W)d5N1EBHgrH0NQ8M(igX80lvVuuvjkqj7(xwQDB73XhTGBn35cEXWlGtZeJKADzIS64(okAuWgvbI23d)piceoQCNTRfT76oNtRMJfajFxCbu1hvaMHX6(XMGxxznqn6TGvefOFpscI9l4U)MgPWPHghDprJvWPe3G4osu81sOSF1)8K(Pob2Fo2jkME5IN)6v3szxBlI0PKdthE5hg(RxeC)uv)McnozOPXCsNYNu(XFA)x2Vk8ZaiVxTFfhz)lb123dgJ2q6V)la2sYk0AzP(jf7jbgCJo1Ip0wsDmSU49EvtkR9LnmxFSvAnr7DGrXLFfmwQ2Ko4dHO8pEXudXgEFP7WicNpZQ0k8Aj1OIkSmi0cyaxAPk5gUq921(WCK3M(ocoizy3nrnOqAd3(3DqFrdZonGOUbJKR(LqOntGKN804BtmaQUQyhgQVF4phR5JrwcI8nuVaBAkB6njrQ2BCk0W3GECzBd3ZZE(KSThIGQ21GlDr0A5SFOnSefIEGGISub()1n9CaIFCJWEGmJtylWgSD7xDh3OFC)Q3TF1hNQOAGB3NiPkL2ODnV7bw)rhtm8nqONInErssAS3ctZuRad4gCGqMURObHPruxJeRa8YoiWFusFfJHbsnOaJOG1OFAokX6VFn2ySfcJh6OdGOXLDRXzXk39gOs8m6V7tMnRN)hPhEfoiRruchpRQew3vvfW)TjZUFYdZ6PAiV21zdURb4sm975o0tl1TacxmrZ(0rqWqtrGy54RzzlzzxVaJluXcCTOfyxEXbaDBuK)v0r9g3Nb6urT8ZHOz4s50Y4j4eK4RTAZ670L(gEF(appWudhgoFQFh9kGCsa8XFdBRWIO9W4x1jLLxy44Xf2)YpKIQfCPm89cBHSWM8ikWZQiUbwJXd69K6NeLehMA78e2tMJEyO95)cbHcN3B9dSqYvLOoKhI9FNPZKgii6)kMaxRObkE8ushbPTi9KarGJrVl76HFrdxvdhnqynktAOSNlE6tUl(7qFfPdTYiTP0)Dc0yPC2nWw0iOXUAiz)8)5d ```

**Comment by mrbuds** [comment]
i could not reproduce, maybe it's pollution from other auras or skinning addon
