### ISSUE TITLE
Pet 3d Portrait

### ISSUE THREAD

**Issue by ColliderGX** [WeakAuras/WeakAuras2#1427]
**Describe the bug**
The weakaura actually works. However it will only work once I do /wa ingame to open weakauras, then it stays open until I log out. 

**Do you have an error log of what happened?**
No errors that I can see
**To Reproduce**

1. Go to 'Trigger'
2. Type>Status>Unit Characteristics>Pet
3. OR: Type>Custom>Status>Event(s)> UNIT_MODEL_CHANGED:pet UNIT_PET
Custom Trigger
--trigger
function()
    return UnitExists("pet")
end
3. OR: Status>Health>Pet>Health%  <=100
4. Made sure to load if player class hunter, but still wont work under any load condition when game is logged into. 
All of these triggers and load conditions work after I type /wa and close it. 

**Screenshots**
https://imgur.com/a/waM2xnM

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Dont use ELV UI but can start disabling addons as a test if need be. 

**Which version of WeakAuras are you using?**
2.13.1

**Was it working in a previous version? If yes, which was the last good one?**
I created the weakaura in this version. 

**Additional context**

!nwvqZPoom4FrTVKa0wMz3duMWwMPnLPoDpShm1K4K4Pb78SDOTCO)2Fs2Xqwo1zymczzPpPpjbnMMtj7PKs8dkQk5TRnVkfw69uYoLUKRVNv8EPw1rj33koEKPl)(TCLQ1kavSobDh8vVTrPFUZkusd4jlL81ZvvgULMnfUwwaxVrjKWfVS(FEieRTFsxD1TrZNeFZ8PXtIJUBwYCA1vZIdrFPQvPbpMf7(K4oN4oNsZIUEgglwriWeJLPTEeujKctJxwGPekbYwTOUMRnEVMFsbk2XTMoEbEbP3W32dVtyWtmnB5hamR64AMfqf5V(7ZwHfmuMTZO07EcYUGMGpbhiz75d1Ns(U(QQ8V64uYdPpUz1RpcOVFhecPDJMxj(KsiBsFeuBDwbPMT349PdjOhdVGaodFX2Lli5Bj5lEbYghUWCcp0fGznCwRTHsIJIOe3dPeKU)(TLnmnuh5AHXkkGWu2dzjuwbJ9XebpgYE5WdbwxbiOJ32UUCiTgvW8b2JusCsuOAmgi3FbYUO4ILisJ6JNbuyCFVaO6dCFKoZB2qxWbEUxPJaYUkocVPtPTAMW(Fk1EmKqFixlzT)l0fGzyw8nHgYkrlFD5a2zsXEFnyuN1PcZ2bAHxOKq6pWssL0bV9mH8NB9PE1FM92aCnwWoyoGs0kRhQz3nz8TF6UTHlQBGHXzGCRI5M2r2OOLzmHgvKx1id71I5Sqw3InOVMLN(c42EySpuVDn15xQuCKFPsBybryQWW)DpxwWDJzMcwRx6ZWkJKKW4pIgVuAznaKmm)jAEnKP(zhxMgmIGrFeBcfayIjBAuqrhd7(xQ5WOKM)RfABdZ0kkAEhY0FX(F)869jJ8J(i447ahXkpWqSFczbuply9r6QBMnjkjE(0zZV5UBtsMoStd4YkrTFs5SN9e45FduwYTGMpeLaADCMaAj3WHX0jW23ndTZF)2ja6DrLggrH1zmlB0E3vOwFXIK(y6Y8vVS4PuKfARg2jVm1ZV(eAT0LpX4Cpgy2t1R1PZULe9eyYWFh8JwmJ9UIr)PW52YJoapcGUdaHVUc3hHJFy3eLKCD8KRbKCaC90Kyql9p)

**Comment by mrbuds** [comment]
I use SUF too and i can't replicate your issue, but i had to fix x/y/z coordinates to show my pet

**Comment by ColliderGX** [comment]
> I use SUF too and i can't replicate your issue, but i had to fix x/y/z coordinates to show my pet

The model seems to get all messed up when i use set transform. Is that what you meant by setting x,y,z?

**Comment by mrbuds** [comment]
no

**Comment by ColliderGX** [comment]
> no

So what did you mean by setting x/y/z coordinates?

**Comment by mrbuds** [comment]
After importing your aura :
![img](https://i.imgur.com/1bCJOJ8.png)
Modified offsets:
![img](https://i.imgur.com/hfFXv1j.png)

**Comment by mrbuds** [comment]
if i /reload it show without opening weakauras options

**Comment by ColliderGX** [comment]
> if i /reload it show without opening weakauras options

I can mess around with the x,y,z offsets. I have that showing properly. Doing a /rl, it stays there. But if I logout or exit, it will not show up again until I do /wa. Every trigger I try mentioned in original post works, as long as its already loaded by doing /wa. If I intentionally mess up the trigger, the portrait will disappear. If I correct the trigger, it shows up. It has something to do with when logging into the game, something I'm missing or perhaps a bug in Weakauras.

**Comment by ColliderGX** [comment]
Update: I made a border(background) for this and it shows up upon login, but the model isnt there.

**Comment by ColliderGX** [comment]
If I change model settings to Use Display Info ID to 81975, this works upon login.

**Comment by InfusOnWoW** [comment]
This is fixed for the next release.
