### ISSUE TITLE
Anchoring to frame that is not always loaded/triggered fails to maintain position 

### ISSUE THREAD

**Issue by Konghol** [WeakAuras/WeakAuras2#143]
What steps will reproduce the problem?
* create a WA Icon (Calling it WA_1) that has a display trigger and load conditions
* Create another WA Icon (Calling it WA_2) that is anchored to WA_1
* Issue: Zoning when WA_1's display triggers are not met and load conditions are not met can sometimes result in WA_2's position to be completely out of place. Seems to happen inconsistently.
* Note: To resolve the issue, I simply had to go to WA_2, and press enter on the selected frame text entry (i.e. did not change selected frame text, just pressed enter on it to "refresh" the selected frame) 

What is the expected output? What do you see instead?
* WA_2's position to always be anchored to where WA_1's position would be. 

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
* No. ElvUI is enabled

What version of WeakAuras are you using?
* 2.2.2.6

Was it working in a previous version? If yes, which was the last good one?
* No, previous version I use did not support anchoring to frames

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
* Bug does not generate an error

Please provide any additional information below.
* I love the anchoring of frames! Can't wait till all the bugs are worked out. Keep up the good work dev(s)! 
* I'm pretty new to WAs. Sorry if some of the terminology I used seems off.

**Comment by InfusOnWoW** [comment]
If WA_1 display triggers are not met, WA_2 should not be visible.

Do the load conditions differ between the auras?

**Comment by Konghol** [comment]
The load conditions are the same. Basically, in-combat/spec/talent requirements for the load condition. 

Is there a loading order to WAs? Perhaps the anchored WAs tried to load before the WA they were anchored to and lost position as a result. 

I'll try to provide a more specific use case when I get home tonight.

**Comment by InfusOnWoW** [comment]
I did a change that should ensure that the aura always gets attached to the right parent just before being shown. Thus I think this should no longer happen in the next alpha.
