### ISSUE TITLE
Issue with roll back from WTF folder

### ISSUE THREAD

**Issue by TheNMy** [WeakAuras/WeakAuras2#1430]
**Describe the bug**
The last time I logged in to WoW was in January this year. My weakauras were working perfectly and I made a copy of my whole WTF folder.
Today I returned to play wow and I wanted to use my old weakauras, so I overwrote the WTF folder with my old one but when I log in the weakaura addon is empty.
After this failed attempt I deleted the whole WTF folder, logged in and out and only copied the ACCOUNTNAME\SavedVariables, as it is mentioned on Discord #wa-discussion, but still no auras when I log in.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
 At first I tried with the latest one, but after that I tried with the older ones.

**Was it working in a previous version? If yes, which was the last good one?**
 No matter which older version I tried, it's still not working.

**Additional context**
I'd be glad if you could take a look on my weakauras.lua file.

``` HER
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3341844/WeakAuras.zip)
E ```

**Comment by mrbuds** [comment]
Your WeakAuras.lua is empty you need to replace it with your backup
