### ISSUE TITLE
a way to make an aura unique again

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1432]
**Is your feature request related to a problem? Please describe.**
I sometimes make slight changes to my aura's code and users reported that similar auras pick it up as an update. Currently there doesn't seem to be an easy way to make an aura unique again.

**Describe the solution you'd like**
an option to reset uid or w/e makes the aura unique upon right-clicking it or making copy > everything not copy the uid

**Describe alternatives you've considered**
lots of copy pasting

**Comment by emptyrivers** [comment]
Duplicate it before exporting.

**Comment by aneri90** [comment]
I also make a lot of WA based on work of @Causese. 
Everytime he release an update (and I got notified by WA Companion) all my group that were based ( duplicated) on his collection got prompted to be updated.

A featured to duplicate with a plain new UID would be nice. Or a button to manually regenerate it.

**Comment by mrbuds** [comment]
![img](https://i.imgur.com/PWV6EAN.png)

**Comment by aneri90** [comment]
Isn't "Ignore all updates" tied to UID? 
Doing so it will ignore updates from original collection too.
Either way when I export my modified WA to guildies it become even more messy. 
WA notifies that they already got that collection (e.g. with Causese Raid collection) and ask them for merge/create copy (and after that notifies update from original source, so I cannot make my version updates on wago).

I fixed this by manually editing UID in the editor section of wago.io.

**Comment by mrbuds** [comment]
Emptyrivers answered the uid issue, duplicate your group and delete the previous one.
Companion use the url field which can't be manually changed, you need to export to wago, and them to import from wago.
You can also import your own auras from wago to have this field with correct value.
