### ISSUE TITLE
Progress bar texts don't get carried over to new sub region system

### ISSUE THREAD

**Issue by sragia** [WeakAuras/WeakAuras2#1441]
**Describe the bug**
Bar Auras coming pre sub region system are missing all texts

**Do you have an error log of what happened?**
No errors

**To Reproduce**
Can reproduce with this aura for example https://wago.io/ryn11ud_7

**Screenshots**

![Wow_2019-07-07_22-51-35](https://user-images.githubusercontent.com/20356414/60773151-c990d300-a109-11e9-82a9-24557623b32d.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
On de85af1c693e9

**Comment by InfusOnWoW** [comment]
Fixed!
