### ISSUE TITLE
Animate displays on aura refresh

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1444]
Ported over from https://www.wowace.com/projects/weakauras-2/issues/16

**Is your feature request related to a problem? Please describe.**
Please add an option to play animations when an aura's duration is refreshed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by emptyrivers** [comment]
#314 + #1357 should solve this feature request.

**Comment by InfusOnWoW** [comment]
Indeed, so no need for this ticket anymore.
