### ISSUE TITLE
%percenthealth and %percentpower (moved from WoWace ticket #958)

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#1448]
asakawa created this issue May 8, 2017

> Quick one:
> When using a simple status - health or status - power trigger the new (I think they're new, right?) outputs for percentage are very useful but they return many decimal places so still need a snippet of custom code to format them. Could they work with the "precision" option in the display tab?

InfusOnWow  posted a comment May 13, 2017

> No, we can't do that easily. There are currently actually two precision settings, one for %p and one for %t. So that you can have e.g. as a display: 4.3/10 . And somewhat strangely those only apply to time values, not to static progress values.
> 
> Now, probably the most common custom text wish is a "K", "M" formatting for values. Which is for again not easy to add as currently those precision settings don't apply to static progress values.
> 
> I think it's pretty clear that there's room for improvement, but I have no idea how we can improve that in a backwards compatible way. (And currently focussed on other topics too)

(https://www.wowace.com/projects/weakauras-2/issues/958)

On the Discord we very frequently advise people to use custom text and snippets.
Buds and I knocked around ideas for rounding/precision done in the text box itself, like `%percenthealth*2` to round to 2 decimal places. Obviously this is easier discussed than achieved and would add to the increasing complexity of that text box.

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/1618 is essentially the same ticket, but adds a bit more information.
