### ISSUE TITLE
Dynamic Info from varying sources (moved from WowAce ticket #985)

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#1449]
asakawa created this issue Jun 20, 2017

> Suggestion:
> Have checkboxes to allow users to override specific Dynamic Infos.
> Or, generally have finer control over the dynamic info used. 
> 
> Explanation:
> Quite often you will want all the dynamic info from one trigger but a specific part to be custom or from an alternative trigger. Say you want to show the buff duration from trigger 1 but the stack count from trigger 2. Or maybe you want all the dynamic info from the main trigger but want to be able to have custom control over the icon used. In these cases you're kinda forced to either go full custom or use methods on the region to set stuff yourself (like running region:SetDurationInfo() from an animation or something)
> 
> I understand if this is beyond the scope of what you would want for the addon but I think it would have an audience that would use it. 

InfusOnWow  posted a comment Jun 24, 2017

> If I would design it from a clean state:
> - I would have "use dynamic info" from first active trigger be the default.
> - No combobox on the triggers page
> - Add a way for conditions to "override" either all dynamic information
>   or a subset of the dynamic information.
> 
> I think that's both more flexibel and a better user interface. That is, a rarely used option that's probably confussing should not be that prominent. ( I added that, because the old default of always using trigger 1 was very limiting.)
> 
> While it makes certain setups a bit more complicated those are probably pretty rare.
> 
> It is possible to do transition to that for user settings, probably would be best to do that at a Expansion Launch when people are redoing their auras anyway.
> 
> Internally conditions are evaluated after deciding which dynamic information to use, so changing that isn't exactly a small project.

(https://www.wowace.com/projects/weakauras-2/issues/985)

The text replacements go a *long* way to solving (or providing a reasonable workaround) for the vast majority of times where this would be useful. Still, more flexibility will always be nice and used by someone... somewhere.

**Comment by InfusOnWoW** [comment]
So taking another look at this, first of all which part of the dynamic information is used by which region type

* clones: all
* progress: aura bar, icon, progress texture
* overlays: aura bar, progress texture
* icon: aura bar, icon
* texture: progress texture, texture


Now technically all of them could come from a different trigger and be controllable via conditions, though I'm likely only implementing setting the icon as a first step.

**Comment by InfusOnWoW** [comment]
The icon part is now done.

**Comment by InfusOnWoW** [comment]
The progres part is now also done. The clone control is tracked in https://github.com/WeakAuras/WeakAuras2/issues/1236.
