### ISSUE TITLE
Pet Health Progress Bar

### ISSUE THREAD

**Issue by Throckal** [WeakAuras/WeakAuras2#1450]
When using a Progress Bar with the trigger Status Pet Health, after dismissing the pet, the bar still stays up. I've tried it with Mage Water Elemental, Warlock pets and Hunter pets and it all acts the same. It was disappearing before 8.2. With at least Water Elemental, when re-summoning the pet, the bar doesn't update with it's current health either.

**Comment by mrbuds** [comment]
which version of weakauras are you using ?

**Comment by Throckal** [comment]
2.13.4

**Comment by InfusOnWoW** [comment]
This is fixed for the next release.
