### ISSUE TITLE
Update to WA incorrectly showing in app

### ISSUE THREAD

**Issue by Musouv** [WeakAuras/WeakAuras2#1453]
After updating and logging out for https://wago.io/HB29dQYlW the app continues to show that there is an update available. It seems to think the installed version is 1.2.3 (version 13) when it has already been updated to 1.2.6 (version 16) as shown here: https://i.imgur.com/PK7U6aY.png

The issue seems to be linked to the fact that the WA used to be a group but is now a singular aura (change was made between versions 1.2.3 (13) and 1.2.4 (14)

**Comment by mrbuds** [comment]
@Musouv do you still have this issue ?

**Comment by mrbuds** [comment]
if you do, please can you zip and upload these files
`%programfiles%\World of Warcraft\_retail_\WTF\Account\<AccountName>\SavedVariables\WeakAuras.lua`
AND
`%appdata%\weakauras-companion\config.json`

**Comment by Musouv** [comment]
I reinstalled the aura with the new version and it stopped showing that, but I can try installing the older version and seeing if it happens again

**Comment by mrbuds** [comment]
Alright, if it happen again please open a ticket at https://github.com/WeakAuras/WeakAuras-Companion/issues

**Comment by InfusOnWoW** [comment]
And sorry that this feel through the cracks. Reporting at the right place, should help the next time in ensuring that we won't miss it.
