### ISSUE TITLE
Text not showing on Alpha 2.13.4-6-ga753a5d and higher

### ISSUE THREAD

**Issue by Evolutious** [WeakAuras/WeakAuras2#1454]
**Describe the bug**
Starting with Alpha build 2.13.4-6-ga753a5d, all Weakauras that have a custom generated text display is not showing anything. If I move back to release 2.13.4-5-gc8d2801, everything is fine.

**Do you have an error log of what happened?**
No errors are being produced, just the text is not showing.

**To Reproduce**
Load an Alpha release of 2.13.4-6-ga753a5d or more current and then use any Weakaura that uses custom LUA for text to be displayed; such as the WA posted on wago here: https://wago.io/Hk9_mlUkN/1

**Screenshots**
Working: https://i.gyazo.com/a9bd4351361656d214c7df541d83b3ae.png

Not Working: https://i.gyazo.com/3cab71bacca037d3292128742242b393.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of WeakAuras are you using?**
Listed above in my problem description.

**Was it working in a previous version? If yes, which was the last good one?**
Yes, listed above in my problem description

**Additional context**
None

``` HERE ```

**Comment by mrbuds** [comment]
Last alpha version is 2.13.4-15-g9cb39d6 please use last version before you open a ticket for alpha

**Comment by Evolutious** [comment]
I am using the latest release, of course. But I actually figured out the issue. It looks like you guys change the text for progress bars to a new section that does not migrate over previous release settings. I am having to go through all of my progress bars and reset all of the text on each one... one by one... Any chance of this not requiring people to do this manually?

**Comment by mrbuds** [comment]
This was fixed with https://github.com/WeakAuras/WeakAuras2/commit/58b08dbefda01fe2e525afcdfde3d3019e10a761 but if you used the version just before it your data has not migrate correctly.
I suggest you use a backup from before yesterday and use last alpha.
On a side note, you should never revert weakauras to an older version, after a migration your SV is not compatible with previous versions.

**Comment by emptyrivers** [comment]
Also, please ensure you are taking regular backups if you choose to use the alpha. Alpha is for testing and finding bugs like this before they hit the general public, not for getting features before everybody else (you can use the beta branch for that).

**Comment by Evolutious** [comment]
Totally get it and fully understand. I absolutely have no issue with the work to fix my weakauras, I was just surprised by the change. I thought it was a bug when it was actually just a change in how text fields are mapped to progress bars. Is there some place that someone such as myself can see the alpha change notes or is that not available? It would help to ensure these sort of bug reports are not made when it is not actually a bug. ;)

but regardless, thanks for an awesome mod!

**Comment by mrbuds** [comment]
You can take a look at commits descriptions https://github.com/WeakAuras/WeakAuras2/commits/master
If you use alpha i highly recommend you to join WeakAuras's Discord https://discord.gg/wa2 then in #bot-channel type `!role alpha` to get access to our development channels
