### ISSUE TITLE
Unable to inspect gear in bags while in combat when WeakAuras2 is enabled

### ISSUE THREAD

**Issue by chromaerror** [WeakAuras/WeakAuras2#1456]
**Describe the bug**
I was expecting my character to appear with the gear that I ctrl + click in my bags to inspect. However, the window doesn't open, rather there is just a print in chat "Interface action failed because of an AddOn"

**Do you have an error log of what happened?**
Bugsack and Bug-grabber were unable to get any bugs.

**To Reproduce**
1. Go to combat
2. Ctrl + Click on any item to inspect it
3. Dont see any errors (except for "Interface action failed because of an AddOn") but it doesn't work. Disable the addon and it works.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
Latest version (2.13.4)

**Was it working in a previous version? If yes, which was the last good one?**
It has been broken for a while I think?

EDIT:
P.S: I forgot to mention that I also tried removing all my auras. Didn't work. Problem went away only when disabling the AddOn completely.

**Comment by Stanzilla** [comment]
That is not really an issue with WeakAuras, areyou sure you tried with only WeakAuras enabled?

**Comment by chromaerror** [comment]
Yes, I am 100% sure.

**Comment by mrbuds** [comment]
Is it when you are in nazjatar ? I know mrrl aura is popular and interact with bags.

**Comment by chromaerror** [comment]
It's everywhere. Also as mentioned in the first comment

>  I also tried removing all my auras. Didn't work. Problem went away only when disabling the AddOn completely.

**Comment by mrbuds** [comment]
From taint.log after using /console taintlog 2
```
7/10 18:59:46.563  Execution tainted by WeakAuras while reading HandleModifiedItemClick - Interface\FrameXML\ContainerFrame.lua:1350 ContainerFrameItemButton_OnModifiedClick()
7/10 18:59:46.563      ContainerFrame4Item7:OnClick()
7/10 18:59:46.563  Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by WeakAuras - Interface\FrameXML\UIParent.lua:5296 DisplayInterfaceActionBlockedMessage()
7/10 18:59:46.563      Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
7/10 18:59:46.563      Interface\FrameXML\UIParent.lua:3200 ShowUIPanel()
7/10 18:59:46.563      Interface\FrameXML\DressUpFrames.lua:189 DressUpFrame_Show()
7/10 18:59:46.563      Interface\FrameXML\DressUpFrames.lua:31
7/10 18:59:46.563      Interface\FrameXML\ItemButtonTemplate.lua:156
7/10 18:59:46.563      Interface\FrameXML\ContainerFrame.lua:1350 ContainerFrameItemButton_OnModifiedClick()
7/10 18:59:46.563      ContainerFrame4Item7:OnClick()
```

**Comment by Stanzilla** [comment]
If the PTR is still up, /console taintLog 11 works on there and should give more details

**Comment by chromaerror** [comment]
At least I dont have PTR on my machine, so its not a possibility for me

**Comment by Stanzilla** [comment]
Could you do me a favor and install this version of Ace3 https://www.curseforge.com/wow/addons/ace3/files/2738492 standalone and try with only that addon and WeakAuras enabled?

**Comment by chromaerror** [comment]
Done. This time nothing in `taint.log` regarding WeakAuras but still doesn't work. Keeps throwing the same "Interface action failed because of an AddOn" stuff

**Comment by Stanzilla** [comment]
=/

**Comment by chromaerror** [comment]
Odd to say the very least. Trying if I can replicate with a different PC.

**Comment by Wolryr** [comment]
This is happening to me as well.

From taint.log after using /console taintLog 11 with both Ace3 and a fresh install of WeakAuras2 enabled. (No other AddOns enabled) - The exact same issue chromaerror is experiencing: 

> 7/10 22:26:53.246  Global variable LibStub tainted by Ace3 - Interface\AddOns\Ace3\LibStub\LibStub.lua:8
7/10 22:26:53.257  Global variable AceGUIEditBoxInsertLink tainted by Ace3 - Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:29
7/10 22:26:53.257  Global variable AceGUIMultiLineEditBoxInsertLink tainted by Ace3 - Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:26
7/10 22:26:53.257  Global variable ChatThrottleLib tainted by Ace3 - Interface\AddOns\Ace3\AceComm-3.0\ChatThrottleLib.lua:48
7/10 22:26:53.257  Global variable BINDING_HEADER_ACE3 tainted by Ace3 - Interface\AddOns\Ace3\Ace3.lua:10
7/10 22:26:53.257  Global variable BINDING_NAME_RELOADUI tainted by Ace3 - Interface\AddOns\Ace3\Ace3.lua:11
7/10 22:26:53.257  Global variable Ace3 tainted by Ace3 - Interface\AddOns\Ace3\Ace3.lua:18
7/10 22:26:53.257  Global variable SLASH_ACECONSOLE_ACE31 tainted by Ace3 - Interface\AddOns\Ace3\AceConsole-3.0\AceConsole-3.0.lua:99 RegisterChatCommand()
7/10 22:26:53.257      Interface\AddOns\Ace3\Ace3.lua:107
7/10 22:26:53.257      xpcall()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70 safecall()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:498 InitializeAddon()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:613
7/10 22:26:53.257  Global variable SLASH_ACECONSOLE_RL1 tainted by Ace3 - Interface\AddOns\Ace3\AceConsole-3.0\AceConsole-3.0.lua:99 RegisterChatCommand()
7/10 22:26:53.257      Interface\AddOns\Ace3\Ace3.lua:108
7/10 22:26:53.257      xpcall()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70 safecall()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:498 InitializeAddon()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:613
7/10 22:26:53.257  Global variable SLASH_ACECONSOLE_PRINT1 tainted by Ace3 - Interface\AddOns\Ace3\AceConsole-3.0\AceConsole-3.0.lua:99 RegisterChatCommand()
7/10 22:26:53.257      Interface\AddOns\Ace3\Ace3.lua:109
7/10 22:26:53.257      xpcall()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70 safecall()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:498 InitializeAddon()
7/10 22:26:53.257      Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:613
7/10 22:26:53.282  Global variable AceGUIWidgetLSMlists tainted by WeakAuras - Interface\AddOns\WeakAuras\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:20
7/10 22:26:53.297  Global variable WeakAuras tainted by WeakAuras - Interface\AddOns\WeakAuras\Init.lua:1
7/10 22:26:53.333  Global variable WeakAurasTimers tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:22
7/10 22:26:53.333  Global variable SLASH_WEAKAURAS2 tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:88
7/10 22:26:53.333  Global variable SLASH_WEAKAURAS1 tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:88
7/10 22:26:53.333  Global variable BINDING_HEADER_WEAKAURAS tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:122
7/10 22:26:53.333  Global variable BINDING_NAME_WEAKAURASTOGGLE tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:123
7/10 22:26:53.333  Global variable BINDING_NAME_WEAKAURASSTARTPROFILING tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:124
7/10 22:26:53.333  Global variable BINDING_NAME_WEAKAURASSTOPPROFILING tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:125
7/10 22:26:53.333  Global variable BINDING_NAME_WEAKAURASPRINTPROFILING tainted by WeakAuras - Interface\AddOns\WeakAuras\WeakAuras.lua:126
7/10 22:26:53.333  Global variable HandleModifiedItemClick tainted by WeakAuras - Interface\AddOns\WeakAuras\Transmission.lua:597
7/10 22:26:53.345  Global variable WeakAurasAceEvents tainted by WeakAuras - Interface\AddOns\WeakAuras\GenericTrigger.lua:68
7/10 22:26:58.619  Execution tainted by WeakAuras while reading HandleModifiedItemClick - Interface\FrameXML\PaperDollFrame.lua:1605 PaperDollItemSlotButton_OnModifiedClick()
7/10 22:26:58.619      CharacterLegsSlot:OnClick()
7/10 22:26:58.619  Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by WeakAuras - Interface\FrameXML\UIParent.lua:5296 DisplayInterfaceActionBlockedMessage()
7/10 22:26:58.619      Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
7/10 22:26:58.619      Interface\FrameXML\UIParent.lua:3200 ShowUIPanel()
7/10 22:26:58.619      Interface\FrameXML\DressUpFrames.lua:189 DressUpFrame_Show()
7/10 22:26:58.619      Interface\FrameXML\DressUpFrames.lua:31
7/10 22:26:58.619      Interface\FrameXML\ItemButtonTemplate.lua:156
7/10 22:26:58.619      Interface\FrameXML\PaperDollFrame.lua:1605 PaperDollItemSlotButton_OnModifiedClick()
7/10 22:26:58.619      CharacterLegsSlot:OnClick()
7/10 22:27:44.498  Execution tainted by Ace3 while reading SLASH_ACECONSOLE_ACE31 - Interface\FrameXML\ChatFrame.lua:2655 ChatFrame_ImportListToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:2703 ChatFrame_ImportAllListsToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4822 ChatEdit_ParseText()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4571 ChatEdit_OnSpacePressed()
7/10 22:27:44.498      ChatFrame1EditBox:OnSpacePressed()
7/10 22:27:44.498  Execution tainted by WeakAuras while reading SLASH_WEAKAURAS1 - Interface\FrameXML\ChatFrame.lua:2655 ChatFrame_ImportListToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:2703 ChatFrame_ImportAllListsToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4822 ChatEdit_ParseText()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4571 ChatEdit_OnSpacePressed()
7/10 22:27:44.498      ChatFrame1EditBox:OnSpacePressed()
7/10 22:27:44.498  Execution tainted by WeakAuras while reading SLASH_WEAKAURAS2 - Interface\FrameXML\ChatFrame.lua:2663 ChatFrame_ImportListToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:2703 ChatFrame_ImportAllListsToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4822 ChatEdit_ParseText()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4571 ChatEdit_OnSpacePressed()
7/10 22:27:44.498      ChatFrame1EditBox:OnSpacePressed()
7/10 22:27:44.498  Execution tainted by Ace3 while reading SLASH_ACECONSOLE_PRINT1 - Interface\FrameXML\ChatFrame.lua:2655 ChatFrame_ImportListToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:2703 ChatFrame_ImportAllListsToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4822 ChatEdit_ParseText()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4571 ChatEdit_OnSpacePressed()
7/10 22:27:44.498      ChatFrame1EditBox:OnSpacePressed()
7/10 22:27:44.498  Execution tainted by Ace3 while reading SLASH_ACECONSOLE_RL1 - Interface\FrameXML\ChatFrame.lua:2655 ChatFrame_ImportListToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:2703 ChatFrame_ImportAllListsToHash()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4822 ChatEdit_ParseText()
7/10 22:27:44.498      Interface\FrameXML\ChatFrame.lua:4571 ChatEdit_OnSpacePressed()
7/10 22:27:44.498      ChatFrame1EditBox:OnSpacePressed()

**Comment by Stanzilla** [comment]
Okay we have a good idea on how to fix it, will tell you when it went in

**Comment by Wolryr** [comment]
If there's any other way I can help, please let me know.

**Comment by chromaerror** [comment]
Yeah, would be nice to say the very least to get this fixed. It's especially annoying when doing old raid tmog runs and you cant view the items you get and you're constantly in combat

**Comment by Stanzilla** [comment]
Haven't found a simple fix yet, last one was a "i had 2 hours of sleep"-idea and did not work out. We're not ignoring this but if we can't find a way to do this better, you might have to live with it.

**Comment by chromaerror** [comment]
So what is exactly the thing causing the problem? Why would weakauras not allow us to inspect gear in combat?

**Comment by Stanzilla** [comment]
That is not a WeakAuras issue, it's Blizzard's taint system that is protecting their secure code paths. Until this patch (I assume) nothing touched anything secure from that path, not it seems like it does. This sadly means that any addon that uses custom chat links will have to switch to a new way to do that.

**Comment by Stanzilla** [comment]
So, I have a tentative fix, can you try replacing your Transmission.lua file with this one https://github.com/WeakAuras/WeakAuras2/blob/b69d8061b9e3f65694d9d386365c136a82aa1925/WeakAuras/Transmission.lua and see if that works better?

**Comment by Wolryr** [comment]
Hello.

Just finished replacing and testing, with the Transmission.lua file (at \_retail_\Interface\AddOns\WeakAuras), but the error is still there. 'Interface action flailed because of an AddOn'.

**Comment by Stanzilla** [comment]
@Wolryr with WeakAuras as the only addon?

**Comment by Wolryr** [comment]
My apologies. Seems I teseted that while using TradeSkillMaster as well. 

So now I've tested again USING ONLY WeakAuras, and it worked. I'm hittinh the training dummies and inspecting gear in combat, it's working so far.

**Comment by Stanzilla** [comment]
Great, so now you'd need to ask the TradeSkillMaster author for the same thing basically.

**Comment by Wolryr** [comment]
Thank you so much for the amazing help. I'll ask TSM for the same thing then. What a weird thing indeed. But again, it's not any of you guy's fault, just Blizzard and patchs things.

What would be a good way you'd recommend to say to other AddOn devs or authors to talk about this error and possible fix, so I don't screw it with my limited user knowledge? Just tell them the 'Blizzard's taint system that is protecting their secure code paths' and therefore will have to find a workaround? 

Thanks again!

**Comment by Stanzilla** [comment]
You can link them this ticket and the pull request https://github.com/Stanzilla/WeakAuras2/commit/b69d8061b9e3f65694d9d386365c136a82aa1925

in general it seems like touching HandleModifiedItemClick is a bad idea now

**Comment by Wolryr** [comment]
Will do.

For now, it's seems to be fully solved with your help. Thank you!

**Comment by Stanzilla** [comment]
You're welcome :)
