### ISSUE TITLE
Extra options for cooldown progress (equipment slot)

### ISSUE THREAD

**Issue by jefffi** [WeakAuras/WeakAuras2#1457]
Currently this trigger sends global cooldown as a cooldown for display, and it can not be turned off unlike on spells. The cooldown progress (item) does not pick up global cooldown at all and it isn't an option either.

In the latest hotfix the trinket Pocket-Sized Computation Device got added to the global cooldown which is how I noticed this issue (trinket slot 1 cooldown weakaura).

**Comment by InfusOnWoW** [comment]
I don't have a usable pocket sized computation device, so I can't test with that. But using the guild cloak from the guild vendor (which reacts to the gcd), I can't reproduce the issue.

The Cooldown Progress (Item Slot) ignores the gcd.

**Comment by InfusOnWoW** [comment]
I asked on discord and Vardex actually checked, and he couldn't reproduce cooldown progress (equipment slot) showind a gcd.

**Comment by asakawa-k** [comment]
From what I've seen the issue is the opposite. With more items being added that obey the GCD now people want the option to show the GCD on the Cooldown Progress triggers for items, but the option to show it doesn't exist (presumably because it was seen as a pointless addition before).

**Comment by InfusOnWoW** [comment]
Adding that option is not a problem, but I still doubt that the reporter had that in mind.
