### ISSUE TITLE
Load condition for AmMelee/AmRanged

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1459]
**Is your feature request related to a problem? Please describe.**
in the past i tend to run into a problem where a weakaura is not requied for melees since the mechanic avoids them and therefore a load condition to exclude melees would be neat.

**Describe the solution you'd like**
the only way I know to make this possible is GetSpecializationInfo.
Basically making a list of speccs and assigning them to AmMelee or AmRanged.
This would require updating whenever a new class is added but should be rare.

i could make a full list, including the api etc if you intend to implement this.

**Describe alternatives you've considered**
baking it into the trigger, doesn't avoid the WA from wasting resources though

**Comment by Hekili** [comment]
Are encounters consistent regarding targeting ranged vs. melee?  That is, the same specializations are 'melee' for all mechanics that target melee and the same specializations are 'ranged' for all mechanics that target ranged?

I was under the impression that this has been somewhat inconsistent in the past.

**Comment by Causese** [comment]
afaik melees are only targeted by ranged-mechanics if there's a lack of melees e.g when most ranged players died. there sure has been times where melees aren't targeted regardless

regardless, I doubt that most melees would suddenly care about a mechanic because most ranged died.

**Comment by Hekili** [comment]
Even then, it sounds like you're setting up a problem if you're a melee, don't load ranged mechanics, and then get targeted by ranged mechanics because the ranged are all dead.

But granular support for multiple specializations (without being filtered by class) would be good.

**Comment by InfusOnWoW** [comment]
Isn't it also inconsistent on how exactly certain healer classes are clasified? E.g. sometimes heal paladins/monks are treated as melee and sometimes as range?

**Comment by emptyrivers** [comment]
So far, mistweavers have never been treated as ranged. Holy paladins have been inconsistent, though.

**Comment by Causese** [comment]
yeah I guess speccs would be an overall better implementation. i could then just have a snippet-aura where i select all melee / ranged classes and just copy it whenever I need it.

**Comment by Causese** [comment]
talent speccs already exists as load condition so the only changed that would have to be made is making all speccs available instead of showing only yours
