### ISSUE TITLE
Quickly identify Weakaura where a sound is activated

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#146]
When you import a Weakauras and it has saved a sound trigger somewhere it in, but you dont want it you'll have to search through the whole group to find which triggers a sound.
For me, I like being notified by sound but only when it suits me, so I want to disable the sound of imported weakauras alltogether. Currently you have to do that manually and to save time it would be easier to have some sort of identification which Weakaura (or Group) has a soundtrigger enabled.

**Comment by emptyrivers** [comment]
That seems like a solution with no problem to solve, honestly. You can mass edit a group, for one; check the actions tab, and force the "sound" action on show and hide to be disabled will achieve this, for example. If the sound is played via custom code, then inspecting the code (which you should be doing anyways) for a PlaySoundFile or PlaySoundKit call and commenting out those lines will achieve this.

**Comment by InfusOnWoW** [comment]
I think so to, there's a easy way to mass edit auras.

**Comment by InfusOnWoW** [comment]
If all auras are selected, the tooltip should tell you which auras have the option enabled/disabled.
