### ISSUE TITLE
Tweaks to display tab styling

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1465]
Default Ace3 headers have a grey horizontal line at their ending, I'd love our collapsable settings to have those as well.

Should improve 
![image](https://user-images.githubusercontent.com/75278/61131664-1255dc80-a4ba-11e9-9bb4-fb5f316794d9.png)

by quit a bit, also can we move those Zoom/Item Inset/Icon alpha settings up to the top to Desaturate etc? I think they'd fit better there now.

**Comment by mrbuds** [comment]
like this ?
![img](https://i.imgur.com/DO8VnxA.png)

**Comment by Stanzilla** [comment]
Yes!

**Comment by mrbuds** [comment]
no we can't do that.

**Comment by Stanzilla** [comment]
ok.

**Comment by InfusOnWoW** [comment]
I think we can hide more options by default, e.g.
Zoom, Keep Aspect Ratio and Icon Alpha
Anchor, Anchored To, To XXX, Frame Strata

**Comment by Stanzilla** [comment]
I think it's fine for now, the anchors stuff I don't really like anyway, especially the "smart anchor" stuff.

**Comment by mrbuds** [comment]
![img](https://i.imgur.com/oSCb8Bq.png)
![img](https://i.imgur.com/bnrmoRw.png)

btw, I noticed a bug with extra options indenting, the indent size works only if there is a scrollbar

**Comment by Stanzilla** [comment]
@InfusOnWoW what do you think about changing the naming of text headers to "Text 1" instead of "1. Text"?

**Comment by InfusOnWoW** [comment]
Fine with me.

**Comment by Stanzilla** [comment]
I talked to Buds yesterday about our usage of the pencil button and we think we really need to come up with a common vision and rule set of what it should hide and stand for. How do we best do that? Maybe make a list of all options first?

**Comment by Stanzilla** [comment]
Does the default color picker have an alpha slider by now?

**Comment by InfusOnWoW** [comment]
the icon alpha works differently from the color's alpha. It's stupid that we have both, but we have both :(

**Comment by Stanzilla** [comment]
Okay maybe that's something we can fix with a migration. I'm currently against hiding any more stuff with the pencil on that page, especially the icon ones. We have to be careful to not overcomplicate the UI by hiding away too much. What I do want changed though is:

- The above mentioned naming of "1. Text" to "Text 2" so it's the same name as Conditions
- Renaming "Show Glow Effect" to "Show Glow" 
- Renaming the main cooldown option from "Cooldown" to "Show Cooldown" so it's the same as "Show Glow"

**Comment by InfusOnWoW** [comment]
There is no yellow color that would work as a default, because the default glow isn't a grayscale that is colorized, but a texture using yellow colors.

**Comment by Stanzilla** [comment]
@mrbuds I like your latest changes, especially the indent of pencil settings once expanded.

Things I would change:

- don't hide "Font" and "Font Size" in the pen, those are way too common. 
- For Anchors, I would not hide anything at all, also used way too often.
- For progress bars, rename the dropdown from "icon" to "icon position"
- For progress bars, rename "icon color" to just "color"
- For progress bars, hide "zoom" like we do for icons
- For progress bars, rename "Border Settings > Enable" to "BorderSettings > Show Border"
- For progress bars, are "Border in front" and "Background in front" mutually exclusive? If yes, make it a dropdown instead.

**Comment by mrbuds** [comment]
The ident is not new, i changed value to make it work when there is no scrollbar.

I'm bothered with "Border Settings", they are not consistent with other options for which if you disable the "show" it hide children, for borders it disable them instead.
But if this is changed then it feels weird to have a collapsing group for a single "Show Border" checkbox instead of a simple delemiter like the spark/BarColor/icon settings. And for consistency it should be same for border options for group & dynamicgroup.

**Comment by Stanzilla** [comment]
yup, agree

**Comment by mrbuds** [comment]
> For progress bars, are "Border in front" and "Background in front" mutually exclusive? If yes, make it a dropdown instead.
They are not exclusive, but i don't understand why we have an option to show backdrop in front of bar texture, it hide it

**Comment by mrbuds** [comment]
I have not touched "Font" & "Font Size", indent and the naming of texts, they are @InfusOnWoW babies.
I reverted anchor pen options, and reverted collapsing border options to show them like we do with Icon & Spark settings, and moved x/y offsets before anchor options
![img](https://i.imgur.com/Li8LaPb.png)

ps: these changes are done on my dynamicgroup branch, border options would conflict with it if it was done in a branch merge-able with master

**Comment by Stanzilla** [comment]
@InfusOnWoW want me to make an extra ticket for those then or is this fine?

@mrbuds Currently we hide all anchoring in the pencil, personally I think we should have a simples option shown by default though but that clashes with the concept of the pencil and goes more into a "advanced options shown" setting that @emptyrivers had in mind a while back. that's definitely something to keep in mind but I don't think we can do this better right now.

**Comment by mrbuds** [comment]
> Currently we hide all anchoring in the pencil

no i reverted this commit

**Comment by InfusOnWoW** [comment]
I disagree that anchors are used often. I would assume that over 95% of all auras use the default anchors.

**Comment by Stanzilla** [comment]
What's missing:
- The above mentioned naming of "1. Text" to "Text 2" so it's the same name as Conditions
- Maybe rename Text's "Visible" to "Show Text" do be consistent?
- Maybe rename "Add Sub Regions" to "Add extra elements"? Might be the more user friendly name
- For progress bars, move `Bar Color Settings` above `Icon Settings` so all always available settings are above all optional ones
- For icons, show the current values of `Alpha, Zoom, Item Inset, Aspect Ratio" when no `Extra` options are changed to be consistent with the other hidden pencil settings. Currently it's blank when nothing is changed.

**Comment by InfusOnWoW** [comment]
I think for the icon extra values, if they are all on default, we should so something like "No Extra Options selected" (wording to be improved), instead of what the values are. 

And yes on the test, especially the "Add extra elements" thing

**Comment by Stanzilla** [comment]
@InfusOnWoW I thought about that but then realized all the other pencils show WHICH options are actually available in it and I think that is good for discovery

**Comment by InfusOnWoW** [comment]
Actually they don't, there are just too many font flags to list them all.

**Comment by Stanzilla** [comment]
okay but in general they do and it's still better for discovery

**Comment by Stanzilla** [comment]
How about:

`Default Alpha, Zoom, Item Inset, Aspect Ratio`
=>
`Default Alpha, Item Inset, Aspect Ratio, Zoom: 5%`
=> 
`Default Item Inset, Aspect Ratio, Alpha: 10%, Zoom: 5%`

**Comment by mrbuds** [comment]
meh, it clutter the screen with things you won't read

**Comment by Stanzilla** [comment]
How do we tell the users which extra options are available then?

**Comment by mrbuds** [comment]
they click it

**Comment by Stanzilla** [comment]
😐

**Comment by Stanzilla** [comment]
I don't like that all, the other pencils at least show some of the extra options available, so should this one.

**Comment by mrbuds** [comment]
if we start doing it here, we need do it everywhere, it defeat the purpose to make ui lighter
it needs to be consistent with spell cooldown options
![img](https://i.imgur.com/3zMEZTF.png)

**Comment by InfusOnWoW** [comment]
so how about "No Texture Tweaks" ?

That covers Item Inset/Zoom/Aspect Ratio

**Comment by Stanzilla** [comment]
I'd rather have "None" than something vague do at least get the benefit of people getting used to clicking the pen.

@mrbuds now that you mention it, can you make that "Extra Options" yellow and "none" => "None" in the cooldown trigger pencil, please?

**Comment by InfusOnWoW** [comment]
I would hold up the Cooldown Progress Options as a shining example to follow. :) It's more like a experiment, and I think it's the right direction that would allow us to clean up some of our uis.

**Comment by Stanzilla** [comment]
@mrbuds bug: item inset does not show up as changed when you collapse the pencil again

**Comment by Stanzilla** [comment]
I really like this:

https://dl.dropboxusercontent.com/s/wabh2usk2icvwgc/2019-08-05_18-47-33.mp4

Shows the user which options are available in the extra menu, encouraging to click, after something was changed it only shows what changed and not every option. user hopefully remembers that there are more than one settings and clicks again if he is looking for something.

**Comment by mrbuds** [comment]
https://i.imgur.com/YeXBBQq.gif ?

**Comment by Stanzilla** [comment]
`Default Alpha, Zoom, Icon Inset, Aspect Ratio` or `None` imo
