### ISSUE TITLE
buggy green fields on entering combat

### ISSUE THREAD

**Issue by Entharion** [WeakAuras/WeakAuras2#1473]
See screenshot. Using 8.2 version from Twitch. also have Elvui running

**Describe the bug**

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```
![WoWScrnShot_071419_121057](https://user-images.githubusercontent.com/52881357/61182400-a77be100-a632-11e9-818e-82f7eb645ee6.jpg)

**Comment by mrbuds** [comment]
1 - Disable WeakAuras, does is still happen ?
2 - Search for a texture aura showing green square, replace path with fileID

A useful resource for finding the fileID when you have a path is https://wow.tools/files
For example the Arthas model used as the default model in Auras: https://wow.tools/files/index.php?#search=arthaslichking.m2&page=1&sort=0&desc=asc

If your issue come from aura found on wago, please leave a comment for the author to let him know he needs to update it

**Comment by Entharion** [comment]
The bug does not occur when WeakAuras 2 is disabled. It only occurs with WeakAuras 2 enabled.

Im really not that handy with this stuff that I know how to do what you ask with path and FileID.

**Comment by mrbuds** [comment]
This is a bug with an aura, not with the addon, you can come on WeakAuras discord if you need more help https://discord.gg/wa2

**Comment by Entharion** [comment]
I only used the default UI to create auras. I will log in to discord.

**Comment by Entharion** [comment]
following is an aura with the buggy behavior, which only started after the latest update:

!ns1wVPooq4)o7(qRiCR0ZB9cvBLyd5GPNkTQYGjzsWBn2r2oqzFGF77moju6PfPkv1mmEM5BU8ndpIpNZK84HrDVE4ioZXzDVmQ3L95SnCwg9hAG3klkaRdLJJorbjw5GffGgSYu2AZUPA(TC2hvWCHVZar2Eotl2auK8O(sqPIXFJHT71Dh0bJ8(saFWl8vyUuPHTGgTuu5n1y5ocswLv4Lgm(rCwJD3zmQmZo9HLjwtHfCUdl)dgbZFIoaRQYZNhq4Vgpj5HNMWzwqOyhZdwIzhypS8zJn7hhwYmkrk0a8rJUTjZFmRToQwfWpXc5Y34mwY4jtExndrLuV4UByZxWMFZmQVPLONLkXESpgaWBfPVsbpTY5nBwSwMHq7LBGmcKk9jDD3x1zpPD2TZvx3Fi6g6yM09Vv6uVClgoHsH)l8J51H7VnimXxe1PX2ul4HfwJVU5gJdLuJYyRh(pmAy0OHd61Vt)b9g2)Qr88lg0db8SV07SV0hd(LxnGWDJ0AriwXz7NMN7apIfrhSqbMe1Jmp8MVYIcHClmgwPaDwOay3ozC89C2BTUJoVtM5xJjqhuo3I9fK3k8ckLcTaJ2f6LEH1xpiL0qjiLJIU1bz)jqpVwW9sGYCd1hdTPPBblokDVCpOnyZgOMMoxwqaykjtIWQlaHhSAH6x4(uO)gnetbqLNyKbg8445JNHjOwUPEcCsk2SEOnA4D()IMDgarezKu3ui1FFRpwQFp7PAapmK88X9JdlNr0VmWHBTwA0SIiALRfeJbRK01g7d0aOEqYUB24XXnZXwowff0F(KCVkPF1Z2)jSZJ(nTSDq1C6PMlykku1lM3dUucWxH9V3QXKjxuP80d6WIDDCoSm6iViQUywdYI1eFdzI0qlt2ci(OYicxaXvR0WxPMWLkRny4LTeeuT1uvsM8b9EbYq9DpJ(pPU5otA4kGs4CNGjlz2JJzFLh1wIUKxZQ)uyZK4bOuuZ(ZHOs9QgpBsTlRbb73nRCB5zszlDG8lZkZMvc)XJL1XV9Wewu)3NCZ3Yv(4QakTf7497sdm())d
