### ISSUE TITLE
Custom Options tooltips don't show up with a blank name.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1475]
**Describe the bug**

Setting a tooltip on a Custom Option only shows a tooltip when mousing over a Custom Option with a name. Leaving the name field blank prevents the tooltip from showing.

**Do you have an error log of what happened?**
 

**To Reproduce**
 
Example aura provided below
1. Enter the Custom Options tab of any aura
2. Create two Custom Options. One with a name and one with a blank name. Add a tooltip to both.
3. Enter User Mode, mouse over each option, and observe as tooltip shows for only the entry with a name.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tested with only the 5 official WA addons enabled.

**Which version of WeakAuras are you using?**

2.13.4

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` !no1YUTnmqWVMESfXkb9EIRmAauKDdzQVXygrkh2stkWhj25G)27Su2ob9fcGG0YLR2hZmRyIGlyBemf9atFoznoTGn)oEZ1T1cwV3LyMx0I2jvcM019OpSWBCjbBADlV(wbB78((OojApdzXehSYDC9weWhgeSDV5YGETX747gqbsLi68wFafUDs5PQ8(8Y7lO3ui5yYVHs4Ddkzc)A(WxzgxitMULgv6rb7sCgE7sOirAAIjzibdKfJZCWQhMXhl24ukywVwhIJ9a)KdYuPFi33p2UFTUzXS7AW9LJYCqc4ioOT2RvXXmhZpOFsd4c)LzRGD)0lz87z8lVfjltnaJWgK8tHUiOlHYwu3GKx8HIPLwAGCYn64Xon7ET1koOb9jnF05nEfOOpo5m6MN9b1YGeO)YtwGX0bN0(DmSaFW0(zb7haBn97eSM6zeEPT9h42RMZ5ZVb)gugtlmW(vZhki7(vCV3Mmdrcm3QvJWFB1zGI7dONbiktscqpiyMrEhbs20BRRBjM31Bwx0CL0wjE4O5eysdmv78YMDtntTQQfJArbBwW8Y(vFllvuvq3WPYyiLaMR3q7h4kNNe0kWyua3p6mQrdaId5BJ04E)rFs(8(IVOXDkZrnjoB9YYUgepDL1VmaZJKANvgJ)H3iTa(BotLfaaUhOLxvWJ7x(1RT47p17EfxHKo2r7EXeoKJ6VqNVAuPHL(sy7xvcSxIIrKYZJ0lTmIf0)xbQEBbQ(lf4FL3XHuWQ(0KZ)0fc2tW9fv0nIFb ```

**Comment by InfusOnWoW** [comment]
That's a limitation of ace gui, which we can't work around.
