### ISSUE TITLE
unexpected error when naming a state: allstates[""]

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1476]
**Describe the bug**
i expected allstates[""] to not be a thing after the aura was hidden.
giving it a proper name like allstates["hi"] fixed the issue.

**Do you have an error log of what happened?**
`1x [string "--[[ Error in 'ThisErrors' ]] return functi..."]:18: attempt to perform arithmetic on field 'name' (a nil value)`

**To Reproduce**
1. import https://wago.io/exPtbH_ps
2. move ingame then stop moving
3. type test in say chat

one aura will error, the other won't. the only difference is that one is name allstates["hi"] and the other allstates[""]

**Which version of WeakAuras are you using?**
2.13.4

**Comment by InfusOnWoW** [comment]
That's different in the next release.
