### ISSUE TITLE
Issue with UpdatedTriggerState

### ISSUE THREAD

**Issue by GinJeanie** [WeakAuras/WeakAuras2#1477]
**Describe the bug**

When a WA triggers, or I update a WA using the updater tool, or just reload sometimes. 

1x WeakAuras\WeakAuras-2.13.4-29-g6295b46.lua:5245: attempt to call method 'Update' (a nil value)
WeakAuras\WeakAuras.lua:5245: in function <WeakAuras\WeakAuras.lua:5244>
WeakAuras\WeakAuras.lua:5335: in function <WeakAuras\WeakAuras.lua:5302>
WeakAuras\WeakAuras.lua:5419: in function `UpdatedTriggerState'
WeakAuras\WeakAuras.lua:5184: in function `UpdateFakeStatesFor'
WeakAuras\WeakAuras.lua:5160: in function `FakeStatesFor'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1782: in function `PriorityShow'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1654: in function `PriorityShow'
WeakAurasOptions\WeakAurasOptions-2.13.4-29-g6295b46.lua:1613: in function <WeakAurasOptions\WeakAurasOptions.lua:1578>

I also have the WA stopmotion addon installed and enabled, but that hasn't been updated since December so I'm not sure if that's a problem in this or not.

**Comment by InfusOnWoW** [comment]
If you update the WA StopMotion addon to the latest alpha, that should be fixed.

**Comment by GinJeanie** [comment]
The file version I had is the exact one that's listed, but I manually installed what you have on github vs what's updating on the twitch client. I'll keep an eye on it, thanks.
