### ISSUE TITLE
InCombat: ChatFrame link click triggers 'Interface action blocked'

### ISSUE THREAD

**Issue by Wolryr** [WeakAuras/WeakAuras2#1479]
**Describe the bug**

After disabling all AddOns but WeakAuras, I'd get a INTERFACE_ACTION_BLOCKED message printed in the chat while clicking on a link (item, achievement, etc) during player combat. Seems another of those pesky protected frames introduced in 8.2. This is obviously Blizzard's fault, but I'd really appreciate if you can take a look into this.

>I also tested while using no loaded auras whatsoever and using bot Ace3 and WeakAuras enabled: same thing.

**Do you have an error log of what happened?**

I do have the /console taintlog 11 message related:

>Execution tainted by WeakAuras while reading SetItemRef - Interface\FrameXML\ChatFrame.lua:3721
>ChatFrame_OnHyperlinkShow()
>ChatFrame1:OnHyperlinkClick()
Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by WeakAuras - Interface\FrameXML\UIParent.lua:5296 DisplayInterfaceActionBlockedMessage()
Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
Interface\FrameXML\UIParent.lua:3200 ShowUIPanel()
Interface\FrameXML\ItemRef.lua:391
Interface\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3513 SetItemRef()
Interface\FrameXML\ChatFrame.lua:3721
 >ChatFrame_OnHyperlinkShow()
 >ChatFrame1:OnHyperlinkClick()

**To Reproduce**

I was able to constantly reproduce this error by: 

1. Disabling all AddOns but WeakAuras.

2. Engaging in combat with a target dummy in Orgrimmar.

3. Clicking on whatever type of link was available in the chat at that moment: in my case, I clicked several pieces of gear people was linking in TradeChat, as well as some of my guild mates achievements popping out in the chat as well.

4. A 'Interface action blocked due to an AddOn' message appears in the chat immediately. 

**Which version of WeakAuras are you using?**

Most updated version currently in Curseforge, version: 2.13.4 (according to TOC file).

**Comment by Stanzilla** [comment]
That is fixed for the next release
