### ISSUE TITLE
All Weak Auras vanished

### ISSUE THREAD

**Issue by oleRellik** [WeakAuras/WeakAuras2#1481]
I just started World of Warcraft bfa and all my weak auras have vanished on all my toons. What steps can I take to recover my data? I have the Weak Auras desktop app and it shows all auras up to date.
I tried the steps listed but no help.

**Comment by mrbuds** [comment]
Looks like you have a Lua error, install bugsack & buggrabber to know what is wrong
If you use addonskins, disable or update it
For further help please join discord https://discord.gg/wa2 in #aura-help or #aura-help-2 channels
