### ISSUE TITLE
Untrigger not working on multi unit aura

### ISSUE THREAD

**Issue by Wizeowel** [WeakAuras/WeakAuras2#1485]
**Describe the bug**
I made a weakaura to show if my friend Davenport has cast Demo Shout. The primary trigger is multi-target of aura 1160. If unitCount > 0 then a condition sets the glow effect to visible. This sometimes triggers even when I'm not grouped with a warrior, but I was in Hellfire Ramparts and figured maybe some mobs are casting it somewhere else in the instance. The real issue is that the weakaura doesn't untrigger. Glow effect stays visible even after all the mobs in the instance are all dead and unitCount is presumably 0.

**Do you have an error log of what happened?**
There's no error message

**To Reproduce**
https://wago.io/cVBK29kQE
Run Hellfire Ramparts, eventually it'll trigger.

**Screenshots**
Can get a screenshot if needed.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No but not using ElvUI.

**Which version of WeakAuras are you using?**
2.13.4

**Was it working in a previous version? If yes, which was the last good one?**
It was working for ages while I was regularly grouping with my warrior friend. But playing recently with paladin and dk tanks is when I noticed it is triggering when it should not.

**Additional context**
Quick description of the WA:
match any trigger, show first active.
trigger 1 is multi-unit with matchCount > 0 for aura 1160
trigger 2 is combat log event for cast success Demoralizing Shout, source in group, duration 45s
trigger 3 is unit characteristics for specific unit Davenport
condition 1 sets colour to grey when trigger 2 is active (ie Demo Shout is on cooldown)
condition 2 sets glow on when trigger 1 has unitCount > 0 (ie when mobs are weaker)
display shows %unitCount and cooldown swipe from either trigger 1 or trigger 2

!nAv3wTnoq4NM9YfInuw6ErpN8JHKttSProTBVXGITITkosELKbcxWZ(oJKCIBAHLdCITLgnZ38nJMzYcYsZipslLZMKrY)6Oph(X7)sugrNrcpj4StopJuGIuW0utRIAyzRZig2tMGBKCHjJmkjnnzXYzxpfeRSw(y6UgwgzDRXifjpWu10DzK7zSMH6gwUzj1WLOsqzNZeLMQS4GbGjn8873nbncxk6KaFQzBb9KrcozWjdClpsQkGL8c9pjB2OzMSyy3h5fOgdV0T1yzTubEqCG9)q7VNz)9C8xWdYB1g52uWNw1uGEiP1)eCqMsqR)ktPrmfhCHZ5dJe011SIoaqYP1muDeARX6D8Cq(rGYLIco6qAhiaskVILFp(IrXllbVaqf5bQIJQe82kWRHVRBzDaSIkkzhuqJs2WuMDO2rVZlSZjhCYhc)W5FCqWhVyWFD55Nz95FDXZ(Dl6ze3FW56dwztg5t9WCqFm3k4MXYwmFWHfYG3g42qRx2r7n2H95ciIRzDISEpQaxwwxiFuab6g8SUKXmYF0ddDNgId1sQnbUvZUvWEWLZGjI4IAUO0h322wB4oGoYzin)zKt3VJDrunWHuY2g024NnmZAQXuBnxEnvR7PAYnlNfr6PfYIHxhHhDrs8NXNFB4YLZswIVojcwC6Q40i3Nlxb3kDImpzSv6d7EZW5dNml2(QZgWBltUELv7KPdxmm2P0HPt)CS9(P3Z6CGEW0TG3bFGvXZRzR4wEVlKBdJ2WeWX(SG0E7Blt0D7LC(hC6cO666y6wBOQGTUDZgxbIPrZV5QvZD5oqOhktG3X1Ywvo7QAAjucAM4AlUazGqhgzn8TWToIvRZk0EayvOxIdgKmHTvQO18NbN8L7ivYwZEXgl3crTxUBUSmJiaX96s3U2kbbak)PmYTJhssVLSA84icX7s9G4OdN4gfZEcYnrZN7iAAUH)al1XplKfqQ2FcL6GlFhXIDuvoFdp)wlJmQJzMqbT3ivMJ46J39vaYbUZwAQxikWzw6ATuT2IoFgnQzU2Q)17jSvWNVC34kQc8kMIJLR1hKVptCe3LoC5R5HUiN2a9w0UIobVDcgwCCCTuaHR1)uCZXgUBzOTwqn5v3MBRhCCM3WLlSzEVcHrbgQtZyPHGGlg0zIONahx7RH0lfClAoMgYXEmr4GzIyOn8730JfOWyhJoLrRHwviA7UG8MmOJSq0f(t6mbQzsnyFGp5s7k46F0k8gNk2z5qSk57Oz4UETsTDO5ixhFjQi(wxMdwoJYTpDysabKdzw36JQmS3N2EPYqHe03T4B4cUU6DlpgA4qrHrp(92P3)J2lNxFOnrur5HUexjrE)kf)5xU7lT0cqH0xUlfm0th52FV33W9MkPkPPRlEVMqDAo0pm04iB5zsfJxwzCtHaWCdV0NjJY(6Oi))p(8W(rroGcC0LjCTBIeariz8nQsXLkSeOVWND2mOW(9qavJket8UE)isR7Hoc26loeeHw3urTgtZQ3CKxUNtDYheUpntyG8JT2S8zXKztGjkFwk3APZ9NYxKpzv68zXGeBuWTa4YoqhwlAHZ7iLfs3XUhZYT0YzHNDXfwFR8x8nykHgxvzxKe6eYn(6((u0(PFUA4ICi6FfInx5dY4LrrXwlKcbadVb1VtSFdbf(Bzdlj0ne5ixW5kf7FBzI8D4OzHq)tfReaQZQ25jjTki1UYyA0)9PNIJTFcxE6(X2pnOxm8i2ftDa258qCwhCOEtw2)n

**Comment by Wizeowel** [comment]
Thanks for taking the time testing it :)
I'm not so bothered tracking specific user, was just wondering why it doesn't untrigger, but I suppose it makes sense if I'm out of combat, then WA won't see the mobs death for the untrigger moment?
So then it's more about why WA can't differentiate "source in group" on multi-target.

**Comment by InfusOnWoW** [comment]
The problem is that the "multi" mode relies on the combat log, which does not always have all events. The "nameplate" mode is far more reliable. 

I'll check why the source in group option doesn't work.

**Comment by InfusOnWoW** [comment]
That's because the aura activates if any trigger is active, meaning that as long as something is debuffed with demo shout it'll show.
