### ISSUE TITLE
BuffTrigger2: unit=nameplate + autoclone can leave "ghost" clone

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1486]
**Describe the bug**
With the new anchor PR in mass pvp situation, with a aura trigger unit=nameplate + autoclone, filter on magic + enrage buffs, attached to nameplates, i saw some ghost icons.
So i tested make same trigger (without magic/enrage filter) with a simple dynamic group, and after a minute, when going away and zooming on my feet to see no nameplate on screen, i still have 10ish ghost auras

**Do you have an error log of what happened?**
no error

**To Reproduce**
new dynamic group
new aura, trigger aura: unit=nameplate, type=buff, auto-clone
join call to arm group in nazjatar
have fun
look somewhere with no nameplate on screen

**Comment by mrbuds** [comment]
You can see it around 6mn40 in this video https://www.twitch.tv/videos/454253204

**Comment by mrbuds** [comment]
another example https://www.twitch.tv/videos/454559017 at 10mn17s 
i didn't filtered nameplates by magic/enrage this time to make it easier to get what happen
you can see someone going off-screen top right of screen and regions for that unit are not hidden

**Comment by mrbuds** [comment]
An example in dungeon (the healing buff on nameplate) https://clips.twitch.tv/SuperBloodyAdminDogFace there is no phasing possibly involved this time.
I made some tests in world pvp environment and it seemed easier to reproduce with many nameplates on screen and a bit of lag, but that's not the case here.

**Comment by InfusOnWoW** [comment]
Hmm, I looked at the code for quite a bit and didn't figure it out so far.

I think the only potential explanation is that we get a UNIT_AURA event after a NAMEPLATE_REMOVED, and that somehow UnitExists/UnitAura still return values.

**Comment by mrbuds** [comment]
it's partially fixed

**Comment by emptyrivers** [comment]
Is this still an issue? It’s been over 2 months and no conversation has happened.

**Comment by mrbuds** [comment]
Yes it is

**Comment by InfusOnWoW** [comment]
And I actually have a few more ideas on how to track it down. It's on my list of things that I need to look at.

**Comment by emptyrivers** [comment]
Bump + confirm this is still a bug

**Comment by mrbuds** [comment]
it is still a bug

**Comment by InfusOnWoW** [comment]
And I think I have actually found the problem and have a fix in my next PR.
