### ISSUE TITLE
cannot import string

### ISSUE THREAD

**Issue by pandamonster** [WeakAuras/WeakAuras2#1492]
Hi, 

I cannot import strings anymore.  I had one weakaura that was working and wanted to add more.  When I paste the string and hit "Done" nothing happens.  Ive uninstalled and re-installed and made sure the box in the top right is not checked. 

Thanks in advance!

**Comment by mrbuds** [comment]
This probably not a bug in weakauras, if you need help please come on Discord https://discord.gg/wa2 in #auras-help or #auras-help2 channels
