### ISSUE TITLE
Wago browse inside of WA client.

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#1497]
It would be kind of nice to have the option of browsing WeakAuras from wago inside of the WA client. Obviously this would have to be done through something like the companion, having it store url's strings and the like for the user to browe through and preview. Maybe a preview button would be nice too, to import an aura set and see what it looks like. 
![Wow_1B7el09PrC](https://user-images.githubusercontent.com/15392657/61991128-1fb0c080-b08f-11e9-9652-21fc2e94cb61.png)
![Wow_dFwY7Dnl5T](https://user-images.githubusercontent.com/15392657/61991147-466ef700-b08f-11e9-8395-3ef3d56a924a.png)

**Comment by mrbuds** [comment]
Are you suggesting to download entire wago website data into an addon ?

**Comment by mrbuds** [comment]
Or just add a button that give a link to wago ?

**Comment by 1ps3** [comment]
Both, though I think the entire wago website is a bit much, something like top 20 auras wouldn't be too bad though. Just the string

**Comment by InfusOnWoW** [comment]
So I certainly don't want to bundle the "top" auras in WeakAuras. 

But as a separate addon, or manged by wago, it would actually be feasiable. Even the biggest auras, e.g. raid boss mods are less than 50kb, so more than 200 auras would fit into a 10 MB download.

Although I'm not too interested in the idea of downloading them just in case.

**Comment by emptyrivers** [comment]
I have always been of the opinion that WeakAuras addon should not marry itself too closely with Wago (or any other similar project). So, my opinion is to give this request a hard pass, as it stands. If it were to be built, it would need to be an external addon that interfaces with WeakAuras, instead of a builtin feature.

**Comment by Stanzilla** [comment]
agree with the above
