### ISSUE TITLE
"Inverse" or "Missing" option in the "Trigger > Event > Combat Log" Menu

### ISSUE THREAD

**Issue by beevme** [WeakAuras/WeakAuras2#1498]
Hello, if not added yet. I was wondering if you can add an option for if a damage or heal from a specific source is missing in the combat log like Efflorescence or Healing Rain. Thanks.

**Comment by emptyrivers** [comment]
Perhaps you could be more specific about what you're trying to achieve?

**Comment by beevme** [comment]
I'm trying to make a WeakAura that'll detect or warn me if a heal from a specific source, like Efflorescence or Healing Rain, is missing. Heals from like Efflorescence or Healing Rain, don't show any buffs at all when use on friendly targets. They just heals.

I was wondering if the "inverse" or "missing" option can be added in the "Trigger > Event > Combat Log" menu.

**Comment by emptyrivers** [comment]
Those are totems. Use the status-totem trigger to track them.

**Comment by beevme** [comment]
Hello. I know that Efflorescence is a totem, and already created a WeakAura for it. 

I trying to create a WeakAura to let me know if a spell like Efflorescence or Healing Rain is already casted and not healing because friendly players are not standing in it. That way, I can recast Efflorescence or Healing Rain on friendly targets.

Again, just wondering if the "inverse" or "missing" option can be added in the "Trigger > Event > Combat Log" menu for the above scenario.

**Comment by emptyrivers** [comment]
We won’t be adding a “missing” option to the combat log trigger, as that would imply quite a lot of foreknowledge on the part of WeakAuras about what should be in the combat log at any given time. Supporting such a gesture would require far too much development work to maintain, and it probably wouldn’t even work very well.

You can use something similar to [this](https://wago.io/EfflorescenceCounter) to implement the functionality you want specially.
