### ISSUE TITLE
Suggestions for improvements to Trigger Dynamic Information configuration

### ISSUE THREAD

**Issue by JoakimYsland** [WeakAuras/WeakAuras2#1500]
**Is your feature request related to a problem? Please describe.**
In the trigger settings, "Dynamic information from first active trigger" means from the lowest-numbered active trigger in the trigger list. However, this can be confused with meaning the trigger that was the first one to activate.

**Describe the solution you'd like**
Something like this was my first idea:
![image](https://user-images.githubusercontent.com/3741467/62078151-33edec80-b24c-11e9-89c9-fd0b05e89cf7.png)

**Describe alternatives you've considered**
Or maybe more of a restructure like this:
![image](https://user-images.githubusercontent.com/3741467/62079221-90eaa200-b24e-11e9-82ce-6bf44c533957.png)

My two cents, thanks :)

**Comment by InfusOnWoW** [comment]
So I did see this when you opened it a few months ago, and wasn't really convinced that it is a clear improvement and "priority" seems like the wrong word to use.

Revisiting this now, I'm still of that opinion.

**Comment by Stanzilla** [comment]
I like your UI suggestion, just not really the word "priority" and having to stick it everywhere. We're talking about it now.

**Comment by Stanzilla** [comment]
So we're going to change the trigger UI over to the same UI we have for Conditions, so no more dropdown.
![image](https://user-images.githubusercontent.com/75278/65792068-4197f380-e163-11e9-9d10-b17da03ce086.png)


This will solve the "highest priority" problem since it will be more obvious what gets priority by the order the elements are listed in

**Comment by InfusOnWoW** [comment]
This is then better handled as <https://github.com/WeakAuras/WeakAuras2/issues/1511>
