### ISSUE TITLE
Broken aura prevents access to options

### ISSUE THREAD

**Issue by Urtgard** [WeakAuras/WeakAuras2#1502]
I tried to change an aura to not using OnUpdate triggers but I failed and couldn't access the options anymore.

A reload didn't help. Only deleting the aura from the saved variables helped.

The aura: https://pastebin.com/kbEe8hRn

Chat says: Options will finish loading after the login process has completed.
And I get these 3 Errors: 
- https://pastebin.com/zSTthNHi
- https://pastebin.com/UXA0zunm
- https://pastebin.com/74yVq23N

**Comment by mrbuds** [comment]
Hey, can you explain step by step how you make the bugged aura?

**Comment by Urtgard** [comment]
1. Import this aura: https://wago.io/H1irh5Zv7
2. Change Custom Trigger to: `function() return true end`
3. Copy this to stack info
 ```
function() 
    local azeriteItemLocation = C_AzeriteItem.FindActiveAzeriteItem()
    if not azeriteItemLocation then return end
    
    local azeriteItem = Item:CreateFromItemLocation(azeriteItemLocation)
    local xp, totalXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation)
    --for showing the current AzeritLevel of your neck
    --local currentLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
    local xpToNextLevel = totalXP - xp
    local percent = 0
    if xp > 0 then percent = floor((xp / totalXP)  * 100) end
    
    local thousandSeperators = function(v)
        if v <= 999 then
            return v
        else
            return format("%.3f", v/1000)
        end
    end
    
    --ret = string.format("%slvl %s%% %s", currentLevel, percent, xpToNextLevel)
    
    ret = string.format("%s / %s (%s%%)", thousandSeperators(xp), thousandSeperators(totalXP), percent)
    
    return ret
end
```
4. Change trigger settings to this:
![image](https://user-images.githubusercontent.com/13890391/62140153-c3e27380-b2ea-11e9-9238-d86b8ea18066.png)

**Comment by SpatenLa** [comment]
it should be guarded against, but you must return a number in stacks. not a string
https://github.com/WeakAuras/WeakAuras2/wiki/Dynamic-Information#stack-info

**Comment by mrbuds** [comment]
On current alpha version of WeakAuras following your steps works without errors.

**Comment by Urtgard** [comment]
Can confirm it, no errors with current alpha.
