### ISSUE TITLE
An Expandable/Collapsible 3rd column that shows only groups

### ISSUE THREAD

**Issue by jec324** [WeakAuras/WeakAuras2#1503]
**Is your feature request related to a problem? Please describe.**
Right now the list of auras available to see limits the ability to group auras within the list as both auras AND groups are listed together.  So if I create a series of Auras with unique names and wish to group them into the same group I have to scroll back and forth to do so.  If you're rearranging or grouping several auras between multiple groups the process gets quite tedious very quickly. 

**Describe the solution you'd like**
It'd be nice if there was an expandable/collapsible 3rd column that could come out from the left in which you could "put this aura in group" and click on the group displayed within that column.  ONLY groups would be displayed in that column, the view/expand wouldn't need to be displayed.  just the basic group listing.  

**Describe alternatives you've considered**
multiple "group" auras but the entire process can still be tedious.

**Additional context**
This is a very horrid rough screenshot I compiled using paint from the work PC.  
![expanded groups](https://user-images.githubusercontent.com/42066548/62145948-fcb62480-b2b9-11e9-9b95-54db1248ed25.png)

**Addendum** 
This would also potentially open up the option to allow you to move an expanded groups child element auras to another group without first ungrouping them.  Also, the default view/opening should always have the 3rd column collapsed.

**Comment by InfusOnWoW** [comment]
Why aren't you creating the group first and create the auras directly into the group?

**Comment by jec324** [comment]
There's a lot of reasons auras may not be within the group... This could be due to being linked auras for say a specific boss or if you are rearranging auras and remove them from an existing group.  You could have also just created the auras initially outside of the group and decided to group them post.

**Comment by InfusOnWoW** [comment]
Right, so the problem with the feature request is that you describe a grand solution in quite a bit of detail, but didn't really explain what kind of problems you are trying to solve. 

And we certainly won't be investing that much dev time, and user confusion (that is, the annoyance of a changed interface), without it solving some problems that warrant the effort.

Though rearranging auras between groups is certainly not ideal, that doesn't sound like a too common use case to me. Nor am I convinced that this would be the best solution for that.

**Comment by mrbuds** [comment]
Something simple that could improve your use case is to make the "Group" button hide all auras, and show the button for all auras instead of only those without a group.
But personally i dislike the button and think i'd prefer remove it and add a "Move to a group" option in the contextual menu, but then it would be even less used that this button already is ..

**Comment by jec324** [comment]
I gave just my take on a potential solution, I definitely don't think it's best -- just the best option I could come up with.  I definitely think Aura Organization and rearranging auras is a bigger issue than perhaps you might see infus.  I believe it's just one of those issues that people are used to with regards to the tediousness of it, and any improvement in the topic would likely be welcome. The issue really crops up when you have a not-loaded aura you're wanting to move into a loaded group.  For example, a talent you're not using.  


@buds yah, those solutions would work as well, and as you said potentially make the button even less used.  A contextual menu option that enabled you to Move To -> List of Groups and a Confirm Dialog would be great.  

The ideal solution would be to move an aura from the list, no matter where it is, without excessive scrolling in any direction.  And if you could do it to multiple auras at one time that'd be even better.

**Comment by emptyrivers** [comment]
We do intend to improve the options LHS, but as infus and buds say, this is somewhat grandiose and only solves a narrow subset of problems. So, I would rather not focus on this unless it remains a big issue after we do more work on the LHS.
