### ISSUE TITLE
Quick Config UI

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1504]
This has been bouncing around in my head for a while, but recent discussions have prompted me to write my thoughts where everyone can see them.

Introducing Custom Options has opened a few cans of worms; users and authors of WeakAuras now expect to some degree the ability to customize what they see in the options pane. Additionally, adding other features has crossed some threshold where multiple people have commented that our Options Interface is too much to digest. In general, it seems that our current interface for configuring WeakAuras has too many decorations on it to properly meet people's needs.

Certainly we don't want to remove features to simplify the interface, but that leaves us in a bit of a bind. We need to still provide all the power that we have right now, while also not intimidating new users who just see a wall of buttons they don't understand. I think that there are two strategies we can employ to help with this:

First, we can shunt more features into a visual style editor. Some highly visual elements like size and position are already like this, and I think that it would be beneficial to consider adding more power where we can to this style of editing. 

Second, we can present a simplified interface which contains only the most important options to the user in a kind of Quick Config interface, and leave the less useful ones hidden away. Bonus points if this can interface with Custom Options in such a way that authors can mark some custom options as good for quick config, while others should be left alone by default.

As always, feedback is welcome. If you have ideas on what specifically should be considered "quick configurable", or if there is some other idea you have for improving our UX, those are also welcome.

Also, I hate doing mockups, so I would be thrilled if some ~sucker~ helpful soul might make some mocks of what they think would work best with these ideas.

**Comment by jec324** [comment]
From a design standpoint having two levels of collapse/expand would potentially be a good start.  

You could have a fully collapsed section, a semi-collapsed showing the most important, and a fully expanded.  You could also have it default to however the author set it up upon /wa opening.  The biggest thing is you'd need to also make it clear at a glance that the user has extra options, should they choose.  

An example would be position settings... rarely does anyone need to mess with the anchor settings and they mostly just want to get at the W/H/X/Y.

You could also go with a simple nested collapsing.  Following the above example for position settings... Expand Position Settings and it shows W/H/X/Y sliders as well as a sub-section of "adv position settings" which has anchor settings that is by default collapsed, even upon expanding the parent Position Settings.  

I was thinking something like this? (ignore the fact I didn't change the icon settings text for position in one of hte images lol)

I feel like if you create an aura and you're presented with that you have just about everything you need at your fingertips without needing a lot of the extra options initially...

![display-UX-v1](https://user-images.githubusercontent.com/42066548/62149782-1fe4d200-b2c2-11e9-8cfd-54f691caf897.png)
![display-UX-2-v1](https://user-images.githubusercontent.com/42066548/62149783-1fe4d200-b2c2-11e9-9cdc-67ecb151b899.png)

**Issues I see**
I think there needs to be more delineation or separation visually of the sub-section elements.  For example they need to be indented or slightly offset some so they don't look like they currently do trumping the fact they're a subsection.

**Comment by InfusOnWoW** [comment]
We already have a second level of collapsing with the pencil icon. We haven't applied it consistently though.

In general I'm not a big fan of hiding advanced options. That usually does not work too well.

**Comment by InfusOnWoW** [comment]
That second level is in the alphas, thus you might not have seen it yet.
