### ISSUE TITLE
Sounds skipping requisitions for activation

### ISSUE THREAD

**Issue by Orteku** [WeakAuras/WeakAuras2#1506]
**Describe the bug**
I have an aura that need all the triggers to activate and play a sound, but the sound play with only trigger 1 activated.

**Do you have an error log of what happened?**
No. 

**To Reproduce**
I was trying to make a new aura to play a sound when Roll the Bones active 2 buffs at the same time.
I was trying with conditions but didn't work properly so I thought I was making something wrong.
Later I tried with 2 triggers (and all triggers required): 1 for Skull and Crossbones and 2 for any other buff, and an action to play the sound when the aura is activated. But the sound play only with Skull and Crossbones.
I added a button glow for testing. that work as intentended only with two buffs active, but the sound still working as described before.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of WeakAuras are you using?**
WeakAuras 2.13.4

**Was it working in a previous version? If yes, which was the last good one?**
I don't know.

**Additional context**
``` !nA1wZPUnq4FnDM(sYG5soKhHeOHoedf500thgtewYgLyKOwY52d53E3DLiq4KComddiTiTx(2D)wLgLMKYwNYe4hyPDdV6HBvc3Q04OgWEhp7blt9Qe23mLXRDRmvt24ugTfUGdUNYUPK)sI8zyZVTjL9YK8CR0Lo8KV1(82n)wNoTpVB3UDG7NFs7oGs0zGsMAuA4gxmiozWSu2stLqwDHP0ub6noI(0K(Uf9D704gN2bTyLXXDsVbJNepa0y2whc94khUqywuuAEkTpT0AQ1cCnTyXgoeHSrANSkNNjN3tiMOTZVT3j9QR425tvz85wJwjm253dyWgJ7utrrkd15I8k(AzkRFs7(1oNrhfK79dWiRad7f5EzdCYPQNLLbJFGDnODL8hcg28KSIwETuO4Zz4nSZxYx7nV39ZwX1AuHxQ4LMceuuA12WoR26mRtxIIZb52vhGh)OJ9bVFLsi)Ya1rglZOxK9tZv4jzpbj1BR4qrXTVVAj)tYYnOB2y3nfsl3bWGtcXbl3GLkdRuV(2D)vnxaY5VDxY2cwFb33rfWkn8qLSmJkURlDkQsf0qwj3A)bPwS8(aHGyNA9VQGKC1ARSN4EaZLcP4ALgD4kzbaLjee7OcvFNeI(4(6kevlvV(kVs4fn8lJXxnq2eJnkyr1tU2xFbE5MvC07yqEkxv4BuZHuTi0B3SrdVvpI4Zu7kvAWFNCtY4ry7MVxTpeqIkZMDbcyDJbWWnOH)L6LIMzyVmavxBWAUE3KmHizmRbPzENL1d2792DerUkvrHSY6nrY7cOLeSZHQh4G26LYhLAhRohaGu2Il6XswWs6ndoj9pPSRK8s0qAOypWQbLpLLJeHDOUijkrWISOZp)SgTO8p25XqoqW8VBVPvsYESPdgpMksg8m0GX86LyLKlbFYxJC1GXthEZyV62fkyDiGDFm8(uNPvRoDXJ6xEoI1ExK6P8splnUty53Oc89XPpgfFI7(fbgKOYwjTmGXBsG5BIUhWK8O8D89IvC3B3DT0A5fYpcZ)SSJa7)jgPOdtiFg2Ho9I1bJSeJOG5XUfXh(B6IWrqL8PE(NKhWbD3xRdrgVS0p25rzI)yufC8jWuZ372)6oufobqZl)BOegJW4OZ22wfMEgtdkvR9iW(d28PnTbBj3crb2CReA4bmYH5fL(4p9UXeh15DinUV7FKEyfgMldeDbcUHL8clmEM0Jf6LF4Ll3MoxUnuhPPinkYprbV7w1EupeypY))HiijErYficY99bVfdeiNfUB)sPweOEU8YdPY5pVD2ZoENN2J)85TPQwTBDAJgnA3TBZUrn74JIIkCu9(XrJFyu3(XXvkHqc1HXd(7DVhAhwnqGTo(ybjijWkGI(mW2WENZsJPT008zJ(JRGSR)Pb4tNUzJahUYQd)U3Z4MPkwfElN3ZKKG4wnoG02puIk1pI5iiUQYFjLnEWWKpyWXYC0EqWRG(0zMYY3UZTs(2D9HW1(E30(Pt6HjaRi0rrmG(3uoeL6zfyxmBWGySOTm)GNAsXWr4Wk9Jq7jruSkabrqY1uPaALaZ0vtMn6FNeN0BmnSvO27LXKDs2oTF3J(UGdaHUOpVA(nJoz3Uty08DwnIcfN)9MdJME1V)N)hPRuwZtJADkWL)i4gTBIEy6)) ```

**Comment by InfusOnWoW** [comment]
The aura works just like I expect it to work. If I get Skull and Crossbones and any other buff, I hear the sound, otherwise I don't. 

I suspect you have a different aura playing the sound.

**Comment by Orteku** [comment]
I tried with a new WTF folder, all addons except WeakAuras deactivated, and import the code I posted above.
https://gfycat.com/foolishunknownharborporpoise
You can see when the sound play with only Skull and Crossbones (Calavera y tibias cruzadas in Spanish).

**Comment by InfusOnWoW** [comment]
Ah you video helps explain the problem. The problem is that trigger 1 activaed before trigger 2 deactivated and thus for a moment both were active. That's fixable.
