### ISSUE TITLE
Tweaks to trigger tab styling

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1511]
- Like in custom options, add a duplicate button to triggers
- Make `Events` editbox multi-line

**Comment by InfusOnWoW** [comment]
https://user-images.githubusercontent.com/75278/65792068-4197f380-e163-11e9-9d10-b17da03ce086.png

**Comment by InfusOnWoW** [comment]
I forgot to add the ticket number to the pull request but this is done now.
