### ISSUE TITLE
Improve Glow Color Condition

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1516]
I don't remember if it worked before but it currently (957325a33648394a890f7fa89660383d049d46ed) does nothing.

**Comment by mrbuds** [comment]
It does work
![img](https://i.imgur.com/0kmm2vN.png)

**Comment by Stanzilla** [comment]
That's...bad. :( This should not be that complicated

**Comment by InfusOnWoW** [comment]
Yes, but we don't have a good solution.

**Comment by emptyrivers** [comment]
Due to the nature of the glow library we use, there is little hope of straight up removing the Use Glow Color property, which would be ideal. So, the only other alternative is to combine the properties.

**Comment by Stanzilla** [comment]
Do we want to keep this open for tracking future improvements or nah?

**Comment by InfusOnWoW** [comment]
well, I'm always in favor of closing feature requests, that don't have a good chance of being implemented in the near future. (Because otherwise, the end result is a overflowing ticket system) But that's a rather extreme position.

**Comment by emptyrivers** [comment]
I was going to do this yesterday, but I didn’t see a way to achieve it quickly. The main technical challenge here seems to be that the conditions property system is not set up to allow for custom components. @InfusOnWoW, do you have any advice?

**Comment by InfusOnWoW** [comment]
Yep, the list of properties is hardcoded, so you would need to introduce a new property type "optionalcolor"(?).

**Comment by InfusOnWoW** [comment]
There are two places that need to be adjusted for a new property type:
* The options code in ConditionOptions.lua, look for e.g. "color"
* formatValueForAssignment and formatValueForCall in WeakAuras.lua

**Comment by jec324** [comment]
Instead of trying to remove the property is it possible that when that property is selected it also automatically loads the 2nd property and toggles it active?

**Comment by InfusOnWoW** [comment]
This is now 2years old and at least to me it seems like people have adapted to how it is.
