### ISSUE TITLE
Tweaks to conditions tab styling

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1517]
Our problems: 

- https://github.com/WeakAuras/WeakAuras2/issues/1516

As a first measure, rename all Glow Conditions to have the same name as their `Display` tab counterpart

- `Visibility` => `Show Glow`

**Comment by asakawa-k** [comment]
Do you have direct control over the order of the elements in that drop down? If so then also putting Visibility/"Show Glow" at the top would be a good idea. That setting is lost in the mix right now, not only because of the slightly obscure name.

**Comment by emptyrivers** [comment]
I think that making the visibility property the default one would probably be the most effective.

**Comment by Stanzilla** [comment]
Yup, what do you guys think about the name change?

**Comment by mrbuds** [comment]
The name change is already merged https://i.imgur.com/QZ1yRzQ.png
I don't know what can be done with ace dropdown regarding item order, but @emptyrivers suggestion to auto select "Show Glow" when selecting "! Glow" sound doable.

**Comment by Stanzilla** [comment]
Oh, guess I missed that

**Comment by emptyrivers** [comment]
As I recall, AceConfigDialog sorts select and multi select widgets via the key AKA the internal value we store into data. So, changing the order is possible but may require a migration or at least some extra moving parts, depending on how we choose to do it.

**Comment by InfusOnWoW** [comment]
The TwoColumnDropDown internally sorts the list:

* Meaning since it's our widget, we could sort in any way we would want.
* And second, a lot of code in ConditionOptions.lua could now be simplified, because it assumed that the control did not sort by displayname (which is the ace default).

I think selecting by default is even better though, that's a great insight.
