### ISSUE TITLE
Icons attaching but not sticking to enemy nameplates

### ISSUE THREAD

**Issue by Petrol30** [WeakAuras/WeakAuras2#1525]
**Describe the bug**

With the latest beta / alpha : Icons no longer stay attached to nameplates. The icons appear to stay clamped to the screen position instead of the nameplates when any affected enemy / camera movement happens.

**Do you have an error log of what happened?**
n/a

**To Reproduce**

1. Install WA : https://wago.io/purgebuffs/21
2. Find any mobs with a debuff in the world / dungeon
3. move camera or mob once aura appears on nameplate.
4. Notice it attaches to the nameplate properly but does not stick to it when any movement happens.  It stays at the x,y position of your screen where it initially appeared.

**Screenshots**
Will try and get a screenshot tonight

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.14.0-beta1-4-g2665f6d

**Was it working in a previous version? If yes, which was the last good one?**
Yes, 2.13.4

**Additional context**

``` HERE ```

**Comment by mrbuds** [comment]
This aura is using unsupported custom code for anchoring, you can achieve almost same function without code
```
!nFvBVTTnq4)ldyaTadjXojdTdOdWorPnDo2UMkDBFr20s0YCMMuJKY5LpOF77UJsYYjPRzFBOfjsKNUxFEU7ssVK4eMlHDPyxcBBcld)pCuU1CxcBu0vWZln2mHDipDtM1uKWgQKp(i3MvTi2yuEjCuMyfVu5Vo1OtwMWEyYQvoHpz8jjmUoDTXo1i1(dv4fgLXc2ACpuUX9PFEk9ZZWdbXbNGvWtf4RSLGdaUvPg8XXgTauDQxA0oke8CRhEa(OvsT0To8m8y4u4zVvMNlSUGjJBpaFmtSSC1Q4hkaT(POrtV62rW90R8slVpyGcHsDDMlOxx5sXoH2ZGVsEFcB(fdyXZzXdMbkRenkRqXFauotZ3kQ)k6tadi4k)69kzQvqkHnnA0iuUs9ExZhC(uJQCREFYWYZKLoiRDcLILB5yQOBMGLbooE48qC4eqXb8)6WsJzqqXB5s9Rx62C7RtE4l4kzUoHDr044OzK3rbgImG4FMiVUcIjvHAvnoz21F8tGrugoHglDI5PkUZHGlOsKIhUfaCYMIB42NEQt(O4Ph6dijek3fb2JqG9ieypcbEYrNtctG1R1eEUxtYwGEYEez91yqLYvHs09DibbLqFd9uuwoKL6vTyQ8EHckNuEiG)YEaGmYuuXfnYZWazmcdnqXnKEBywc7TeGB8GBIMoAqCeYB8b8aA7sjsQJpDtAF)NgoAcsULzbBn7seAPHQI2FfqNG0bB2GlV(wgL0hj3cAU1RBcOZcQ43LzamE85qr3KUdywKfF3jeMen6n8Cz6XrAlpxuTazyUQfgD1cKta8dpqma(LhIIjf(9aHvw4EGEY986uogOxHNgCB2fZIIgtDPklOMoSENE(7E)zu0SsMh0debdoihne0LnDKqNJo(P)m4NkkeXGabWYoEHlq26JDr8cRMR(Atm2N6oL22jjxbDlx(I5HUOauSHTiH0sN3SnwCpgXLAQx2Be3xideRy5wXpvTWYV7YAQg8wH1KBfoh84kJfXHzDUftRWVKP0BqrnDJ7TvFUAr4FkdGnHZRw8HQfEJUC7sH9nptmRWxA1KCCDg97FTArV9VzSvl(HFO6ZcSt83SvFlJxSDh2hS3rNCupmlBuzM70S7KqLCyiP8NDuY(0YTfzirRPTzPfikR9(c3VC8X3XZnhjnhhQVxsTVDXMXTaRJF)loFOw9H26Zf6Dhnil7cfWNEt7jGSEXryxCil2EAGI(wGkzMxRKLh2sSr1ptK6PqTca56p)uHcWvmze6kbaeSoIzi48MbT15R)Ot(QtxZMu(lqP6slAkbyo(sPJVujYqn78Y0np0GNqpyV78TAsseHwm)7Fst965SGDM7wZZo0XRhCuU0tuasQWJ)yA9RPFFBtYTYGH)vw5Jvl(sjpd7CaBNCOTFf7B0r6UqYWX7ZZdUnEshlh6jn524rxpoQ(8dOcWvrZMpCsC8KBAyjpt)7KojujWcrRMdT971V5J6M(OE8Iq7JXtadtyO1cz(AqGtbjUl0F(06opJKAOF74398(R4Txzf)DPqN(ao4R)5nGOBmzKlTrikgGtE9Zq0rdqme6ll9q7Kjama25P(I1awcSNJMw8)5fua21h7Y6Ouv9eIZoCYmripG(ePdSh47AAndBZLkd0HZ2VbZ)HLwWLD0IDHHeFJny6mrCk3IThxIlX64EmQPLtEfCNhnqZhQXDPVTKYAxGbhHhmu1IT0OCrNr54iKdNK)sJjH9)kw)DMI)VTyUBnuAW2ZoIy0DJCmpf2B)ckpo87SwEdGagf9kxf)jl931yyjbtjOvdzf4jFZU)TzLdw)VuxBvpmAp7L)JoEHT)zzs3Fr7hSddELQDgzqSrg0pyHXD7e1Nse3qzMwa8lzx0V4T)2u7x3GvkSLTObUdqiO1FPseyRnaCAj1HpzXOqfkDTiDt3sfwG3XTsKoCyMIH)jJF4d41QsrtAdr)R56CXEDgUFiXKkewFDNKAiFN5wOmivSDPB62DGAoJwml5F(d
```

**Comment by Petrol30** [comment]
Thank you very much - this works great!

**Comment by Petrol30** [comment]
It appears that didn't fix it after all.  
Not sure which is happening - it's either :
(1) The icons are randomly clamping to the screen 
(2) Or Icons are not disappearing when the unit dies and locking the icon to the screen position

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/1486
