### ISSUE TITLE
[Templates] [Text Subregions] [Suggestion] CD Ready and Pandemic Text Effects

### ISSUE THREAD

**Issue by anaseskyrider** [WeakAuras/WeakAuras2#1529]
We already have dynamic text precision for when a timer (be it a CD or aura) is below 3 seconds. A feature often complemented with this is enlarging the text and coloring the text from white to red.

Primary suggestion: Add these features to the WeakAura templates, and if possible make these visual effects on these timers be tied to the Pandemic mechanic (for aura components), not just <3s remaining.

Secondary suggestion: Add options to text subregions for these, similar to the text precision settings.

**Comment by InfusOnWoW** [comment]
Conditions are exactly for that purpose. As to templates, I think that's a bit too niche.
