### ISSUE TITLE
Load by specific item equipped

### ISSUE THREAD

**Issue by Hansrutger** [WeakAuras/WeakAuras2#1530]
**Is your feature request related to a problem? Please describe.**
The current issue is very minor but significant toward having WA being as convenient as possible for players with no coding knowledge. The issue right now is that you cannot load in a weakaura by setting specific item equipped.

**Describe the solution you'd like**
All types of weakauras, should be allowed to be loaded in if the player has a specific item (given by ID or name) equipped and for multi-slot options such as trinkets and weapons it would check both slots. I am not meaning the slot being occupied by any item but the option to have a specific item id being equipped.

**Describe alternatives you've considered**
Right now I am solving it by making a group for each character and then loading it in by "Player Name" as can be seen in image 1. 
Image 1: https://i.imgur.com/musz2MY.png

**Additional context**
This is a minor issue as it can easily be solved right now but I was looking for this option multiple times in the load page but couldn't find anything so thought it would be a cool addition to an already cool addon!

**Comment by Vardex** [comment]
For now, you can make a trigger for item equipped.
