### ISSUE TITLE
Auras 'inside' action bar buttons

### ISSUE THREAD

**Issue by mspykerez** [WeakAuras/WeakAuras2#1532]
**Is your feature request related to a problem? Please describe.**
Kinda yes and no. One can consider it related to clickable auras but its not really a clickable aura when you associate it with a action bar button.

**Describe the solution you'd like**
The solution is simple, allow us to create auras 'inside' action bar buttons.

**Describe alternatives you've considered**
I've consider using https://github.com/AdiAddons/AdiButtonAuras but it has very few updates as of late and creating custom rules via coding itself isn't for me.

**Additional context**
I really want a way to create auras for action bar buttons like AdiButtonAuras does but with the powerful and simplicity that weakauras provides.
Example glow highlight a button when X aura is detected on self, or glow highlight when X stacks is detected, glow highlight when its about to expire or its completely missing, glow when you can cleanse someone, or dispell something. Show cd remaining of an ability, or show cd of the aura itself until it expires.

**Comment by Stanzilla** [comment]
What prevents you from just anchoring auras to buttons?

**Comment by mspykerez** [comment]
Humm theres a solution but not the method I was thinking and wish for.
