### ISSUE TITLE
Visually edit subregions

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1533]
**Is your feature request related to a problem? Please describe.**

We have subregions now, everybody rejoice! 🎉 But I'd like to have a more "direct" way of configuring them. Currently, the options panel interface we have feels quite abstract. It works, but I think we can do better.

**Describe the solution you'd like**

Something like this (but perhaps not styled to look like it's from the late 80s. Also please don't make fun of me for what I work with 😞): 
![image](https://user-images.githubusercontent.com/24878501/62706872-f6a8fd80-b9b5-11e9-8a15-03b40554a071.png)

Specifically, a toolbox that i can pull subregions from to add them onto the aura, and the ability to select specific subregions to tinker with.

**Comment by InfusOnWoW** [comment]
Yeah, but no. :)

As in, sure that would be good. But I don't think it'll ever happen :)

**Comment by emptyrivers** [comment]
Imma go ahead and close this, since I can’t imagine anybody has any plans to tackle this.
