### ISSUE TITLE
Dynamic Group keeps duplicating its children

### ISSUE THREAD

**Issue by Olorun** [WeakAuras/WeakAuras2#1534]
**Describe the bug**

I created a dynamic group and added a debuff tracker to it (doesn't matter which debuff or what's anchored). When I log out and log back in, the dynamic group shows that there are two children now. If you repeat, it adds another child ad infinitum. So over time as you're playing, the dynamic group will bloat and you'll have hundreds.

**Do you have an error log of what happened?**
 
No errors.

**To Reproduce**
 
1. Create dynamic group.
2. Create a debuff to be tracked (only one is enough).
3. Log out, log back in.
4. Now there are double the children inside the dynamic group (so 2 if you created 1 debuff in step #2).
5. Repeat step 3, the number of children will keep growing.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

2.14.0-beta2

**Was it working in a previous version? If yes, which was the last good one?**

The same error happened with all of the versions for Classic beta...I reported it on mrbuds fork.

**Comment by mrbuds** [comment]
> I reported it on mrbuds fork.
That's not a place to make bug reports for weakauras

**Comment by mrbuds** [comment]
I can't reproduce the issue
What do you mean by "Create a debuff to be tracked" ?

steps i do:
- click new
- click dynamic group
- click new icon
- logout / login

**Comment by Olorun** [comment]
https://imgur.com/a/jARJBUd

Should have clarified that I mean the options panel

**Comment by Olorun** [comment]
I used the template for Icon>Medium Icon>Debuffs>Frost Nova

**Comment by mrbuds** [comment]
> Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
>
> Yes

I see skinning addon used on your screenshots

**Comment by mrbuds** [comment]
I have tested using templates, and still can't reproduce the issue

**Comment by Olorun** [comment]
Hm during the beta I tried it with only weakauras on. But you're right, it doesn't seem to happen in sandbox when I turn everything else off. Gonna see what other addon causes it, at least.

**Comment by mrbuds** [comment]
I'm very interested to know which of your addons is doing this..

**Comment by Olorun** [comment]
Currently testing through the whole list one by one, will keep you updated

**Comment by Olorun** [comment]
It's caused by the addon SpeedRunSplits (https://www.curseforge.com/wow/addons/speedrunsplits/files).
Very strange, would have never expected that.

**Comment by mrbuds** [comment]
After installing the addon on first login ..
![img](https://i.imgur.com/4pGlB7j.png)

**Comment by Olorun** [comment]
Yeah exactly

**Comment by emptyrivers** [comment]
Report this issue to the author of that addon, and mention to him that he probably shouldn’t replace the tContains global function. 


Or you can simply uninstall that addon, your choice.
