### ISSUE TITLE
Game Freezes/Crashes/Lags when clicking on Group Weakaura

### ISSUE THREAD

**Issue by Shiekrunner** [WeakAuras/WeakAuras2#1547]
**Describe the bug**

 I opened Weakauras and i clicked on one of my group Weakauras thats consist out of 9weakauras
then the game crashed sometimes it just severely lagged. I expected it to not crash this did not happen to me yesterday it's the same group of Weakauras.
**Do you have an error log of what happened?**
 

**To Reproduce**
1. Open Weakauras
2. Click on any Group
3. Success the game crashed.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I have disabled all my addons besides Weakauras and it still happens.

**Which version of WeakAuras are you using?**

I'm using 2.14.0

**Was it working in a previous version? If yes, which was the last good one?**

It worked before yes, i think it was the one before 2.13.4? because it started to not work with  
version 2.13.4 and i have the same issue with 2.14.0. It could also very well be started by 2.13.4?
**Additional context**

``` HERE ```
it's all larger weakaura groups that you can see especially the cooldown tracker one results always in a crash i couldn't export it tho because when i try right clicking the group it already crashes .
[1WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3489303/1WeakAuras.zip)

**Comment by Shiekrunner** [comment]
I think the issue is it being overloaden for some reason it wants to create 5000buttons by removing the groups it is "fixed"

**Comment by InfusOnWoW** [comment]
Your settings were quite broken, I would be intrested how you ended up with those settings. I suspect some other addon interferred with WeakAuras I've fixed your settings here:


[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3489956/WeakAuras.zip)

**Comment by mrbuds** [comment]
Maybe related to #1534 where speedrunsplit add-on is messing with tcontains

**Comment by Shiekrunner** [comment]
thanks alot guys :D
