### ISSUE TITLE
Debuff progress bar isn't triggered properly when mouseover casting

### ISSUE THREAD

**Issue by Vaktras** [WeakAuras/WeakAuras2#1552]
**Describe the bug**
I created an aura to display a progress bar for my polymorph. When polymorph is casted on a targeted enemy, it works properly. However, when polymorph is casted with a mouseover macro, a "?" symbol appears instead of the polymorph icon next to the bar, and there is no progress on the bar. However, when the polymorphed enemy is targeted, the icon changes to the right one and the current progress is shown properly.

**To Reproduce**
Create a polymorph progress bar with the template, cast polymorph with a mouseover macro (
/cast [target=mouseover] Polymorph).

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but I don't use any other addons that could interfere with this, I believe. I only use one to display vendor prices, DBM and one that outlines item rarity.

**Which version of WeakAuras are you using?**
2.14.0-beta4-classic

**Was it working in a previous version? If yes, which was the last good one?**
Never tried with a previous version.

**Comment by mrbuds** [comment]
Can you export and include the aura you use and give a step by step example to reproduce your issue?

**Comment by Vaktras** [comment]
I'm kind of a noob, so I don't know how to export it.

**Comment by Vaktras** [comment]
To replicate the issue, just load the Aura, and use the macro in my first post to cast polymorph on any enemy unit that isn't targeted.

**String, is this what you are asking for?**
!DBv3Ujoou4NM9I9cQscqbUyxjGgArccS40z7mAuOMehINgSrooTfUOp7Z5yhtHUsJQwP9MvGGKJp)(D(Zj(jXjeEsKF7R965NqQsibx535kVwByAANeYUesg(fyRApv90FZZ0fa)EjKnsvgtnIM(uMsUpHmQKF8ivL92JXszPMdKO16cPAXEnxkQaDezSN(WEg8RC72s4)6k2nSQ0KnjKNyhsisd3GVKXYP1LA8abDhWPvpV9iC2lnUrIg(qsLIC(wu1oH3GKpSipVIPtM0Qx)((b9d8VUVxWa)b9tYB1za4EIuW9wk5cG7XHrXHRa)HdbCG)Dh)gBE3FC)V7c0XYsPYgd43aZVTn)2jjY7QUOjny0kPMIUXCzg41dVpEbGXGpMmcIAfF7wM6mWWsWcWSYYPzWb(9rStrX4UHvcseSG8fXcr5bux1coqyhGrC7lHVYR0viGTvjR3VovwJrMbl3uNNhBa(7gUA(K7N5YdODcaJxVH9mtOjaF8xtiRhpKeVMepCf4zMtajz0sa2jo3sFYNDV1OKLkMrjKLHZMzsXrygCK5XBpZ3ak7O60cwfPq(YcbOcZ)dt18Nzxehl2ZuunKci)5FG2ciDc6mvbuJmXwIgSpQfuNQTGpOKFv(Z3WNqZucA5xGeeK)aM8)qkfs0yzdFN9nmPPPkn(qgGJiX1wyTIbgfWLguwifm0e7OCXNN7CUGxv8P5hKytt74uXeLuyAEqsiokYoVe2ZabEgiW78s4nu1)Kp)Z4ZavzSkQg9jgAce6TD4NWJZ9Ed0Y1UeLbrT9MF1aOqzZk22lNrWEvVUQGMjF5HM2ySjOj6R3GN3WL9XFBFZRFI8SHVCeEitu8JV94FvtZGyHcJUU02)Ae7DLz5(RopTLVJoRmVz(IDoWjtB7fJWeNL4fdJMgffUA9SWjXUPuN0Txd)pZR4BknnvkS6KfBWHOfrHozE4JYGgMWpcDg(bGVdXZ)kOw8)pOE10BV7)uSgyVGX3waRJmBJ61RD7R9h4nO)aCBemWVANuQlwQKBvSQk0wLsQzZlm0CDAj1seM4MIeTZ9BAPSNITFCHzR68H3g(bEQqN5dc66ghvYezn7RU5gJfhM9J6knlJLnN(k2K)QBDAVGo9g0Bq3Ex3TBVU9cq)VJBn5uHTaY3rimB7j03cvtuWYaBsHeolCC8KvdNJaz5(cQP2ZkjA0lDey2jqtzMveFA7fmXYjsdGFDc5OuUZKmmd)R4yO1KKnr8D8Smguihf(fCRVHgMvRvaJtXfb50u23htR0aKoIQ((9tB9(BTiOaoDztSrTBY9gD4UoudpMjXgF0vO01C)iP5wbY0ND7C89B7b7JXBHSuwEyNuTV4DW1ovhejhbr42dqRKbYAUruGN3fdyFWoGfjm(ZSaeDdMBRbUi5tDThPIdB9T7ej3Ty10VTikE4mZnZY4UDdyX27nPU7BbiA6thUPz)M9MBpd6Vta6sj)8p

**LUA Table**
{
    ["sparkWidth"] = 10,
    ["borderBackdrop"] = "Blizzard Tooltip",
    ["authorOptions"] = {
        [1] = {
            ["type"] = "toggle",
            ["key"] = "option1",
            ["useDesc"] = false,
            ["name"] = "Option 1",
            ["default"] = false,
            ["width"] = 1,
        },
    },
    ["yOffset"] = -13.999969482422,
    ["anchorPoint"] = "CENTER",
    ["stickyDuration"] = false,
    ["borderColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 0.5,
    },
    ["sparkRotationMode"] = "AUTO",
    ["actions"] = {
        ["start"] = {
        },
        ["init"] = {
        },
        ["finish"] = {
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["spellId"] = 118,
                ["useGroup_count"] = true,
                ["ownOnly"] = true,
                ["unit"] = "multi",
                ["unitExists"] = false,
                ["group_count"] = "1",
                ["debuffType"] = "HARMFUL",
                ["useName"] = true,
                ["subeventSuffix"] = "_CAST_START",
                ["group_countOperator"] = ">=",
                ["event"] = "Health",
                ["spellIds"] = {
                },
                ["auranames"] = {
                    [1] = "118",
                },
                ["type"] = "aura2",
                ["matchesShowOn"] = "showOnActive",
                ["subeventPrefix"] = "SPELL",
                ["names"] = {
                },
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["internalVersion"] = 21,
    ["sparkOffsetX"] = 0,
    ["selfPoint"] = "CENTER",
    ["backdropInFront"] = false,
    ["xOffset"] = 411.99993896484,
    ["barColor"] = {
        [1] = 0,
        [2] = 1,
        [3] = 0,
        [4] = 1,
    },
    ["desaturate"] = false,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["main"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["finish"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
    },
    ["sparkColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        [1] = {
            ["text_shadowXOffset"] = 1,
            ["type"] = "subtext",
            ["text_text"] = "%p",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_shadowYOffset"] = -1,
            ["text_selfPoint"] = "AUTO",
            ["text_fontType"] = "None",
            ["text_anchorPoint"] = "INNER_LEFT",
            ["anchorYOffset"] = 0,
            ["rotateText"] = "NONE",
            ["text_fontSize"] = 12,
            ["anchorXOffset"] = 0,
            ["text_visible"] = true,
        },
        [2] = {
            ["text_shadowXOffset"] = 1,
            ["type"] = "subtext",
            ["text_text"] = "%n",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_shadowYOffset"] = -1,
            ["text_selfPoint"] = "AUTO",
            ["text_fontType"] = "None",
            ["text_anchorPoint"] = "INNER_RIGHT",
            ["anchorYOffset"] = 0,
            ["rotateText"] = "NONE",
            ["text_fontSize"] = 12,
            ["anchorXOffset"] = 0,
            ["text_visible"] = true,
        },
    },
    ["height"] = 27.999921798706,
    ["icon"] = true,
    ["load"] = {
        ["use_class"] = true,
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["class"] = {
            ["single"] = "MAGE",
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = false,
    ["borderSize"] = 16,
    ["uid"] = "21HzZeM5jU)",
    ["backdropColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 0.5,
    },
    ["width"] = 200,
    ["frameStrata"] = 1,
    ["border"] = false,
    ["useAdjustededMin"] = false,
    ["regionType"] = "aurabar",
    ["borderInFront"] = true,
    ["config"] = {
        ["option1"] = false,
    },
    ["icon_side"] = "RIGHT",
    ["id"] = "Polymorph",
    ["sparkHeight"] = 30,
    ["texture"] = "Blizzard",
    ["auto"] = true,
    ["borderOffset"] = 5,
    ["spark"] = false,
    ["sparkTexture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
    ["sparkHidden"] = "NEVER",
    ["zoom"] = 0,
    ["alpha"] = 1,
    ["anchorFrameType"] = "SELECTFRAME",
    ["borderEdge"] = "None",
    ["borderInset"] = 11,
    ["inverse"] = false,
    ["smoothProgress"] = true,
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {
    },
    ["backgroundColor"] = {
        [1] = 0,
        [2] = 0,
        [3] = 0,
        [4] = 0.5,
    },
    ["sparkRotation"] = 0,
}

**Comment by mrbuds** [comment]
This is normal behavior with the "multi-target" unit when it's not possible to get more data yet.
You can use "nameplate" unit for something more reliable, but you will need to be in nameplate display range (20 yards afaik)
You can also force the icon in display tab instead of auto

**Comment by Vaktras** [comment]
What do you mean with "when it's not possible to get more data yet"? Does that mean that it's impossible to get the aura to display timer with mouseover, you actually have to target the enemy for the aura to be registered?

________________________________
Fra: Buds <notifications@github.com>
Sendt: søndag 11. august 2019 21:12
Til: WeakAuras/WeakAuras2 <WeakAuras2@noreply.github.com>
Kopi: Vaktras <aleksanderbodolai@outlook.com>; Author <author@noreply.github.com>
Emne: Re: [WeakAuras/WeakAuras2] Debuff progress bar isn't triggered properly when mouseover casting (#1552)


This is normal behavior with the "multi-target" unit when it's not possible to get more data yet.
You can use "nameplate" unit for something more reliable, but you will need to be in nameplate display range (20 yards afaik)
You can also force the icon in display tab instead of auto
