### ISSUE TITLE
Code for classic version

### ISSUE THREAD

**Issue by nummersyv** [WeakAuras/WeakAuras2#1554]
The latest `WeakAuras-2.14.0-beta5-classic.zip` includes an additional `LibClassicDurations` library as well as changes to the `.toc` files compared to the main version. My question is, where is this version developed? It would be great to have another branch with the classic version (like other projects are doing).

Thanks for the great work!

**Comment by emptyrivers** [comment]
We use the same source code for both versions of WeakAuras. The only difference is the packaging script that we use.

**Comment by nummersyv** [comment]
Thank you for the quick reply. That makes sense given the fact that only the interface version needs to be changed in the `.toc` files. But what about the entire `LibClassicDurations` library? That code doesn't seem to be under version control.

**Comment by emptyrivers** [comment]
Most of our libraries (indeed, all but one) are not checked into this repository, no. When we publish a release, we package the libraries in on the fly, using the .pkgmeta files to specify the resource location and tag we need. See [here](https://github.com/WeakAuras/WeakAuras2/blob/0989f94a6a19b8f1e1ef1ee5ee31f503e683e5a6/.pkgmeta-classic#L20) for how we embed LibClassicDurations, for example.

**Comment by nummersyv** [comment]
Ah, I see. I thought this library was part of the WeakAuras project. Thank you very much for your time and in-depth answers.
