### ISSUE TITLE
Importing new string on beta3 as copy is broken

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#1555]
**Describe the bug**

Expected to see copy of the import
Instead there is nothing in the options until you reload ui
And after you reload UI you are able to see them, but can't interact with new import

Did this on classic but not sure if it matters
**Do you have an error log of what happened?**
 
no errors in bugsack
**To Reproduce**
 
https://wago.io/VfDydLRTj Import this and then import again as copy
**Screenshots**

https://i.imgur.com/uDJi7zE.png
https://i.imgur.com/XAOfXhb.gifv
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

same issue
**Which version of WeakAuras are you using?**

.beta3
**Was it working in a previous version? If yes, which was the last good one?**

1st time i used beta3 at classic. On retail it is working. Not sure if beta5 has fixes to it
**Additional context**

After you import as copy options doesn't display anything. If you reload you they are there but you are not able to interact with them (expand). After you delete them all auras from this copies appears in the 1st non-copy group.
https://i.imgur.com/J3xxmsl.gifv
``` HERE ```

**Comment by mrbuds** [comment]
i get this after /reload https://i.imgur.com/zz8TEuH.png

**Comment by mrbuds** [comment]
after importing a copy and /reload
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3493892/WeakAuras.zip)
