### ISSUE TITLE
Issue Trying To Delete A Weakaura (Classic Version)

### ISSUE THREAD

**Issue by HolteUnderscore** [WeakAuras/WeakAuras2#1556]
**Describe the bug**

Unable to delete existing weakauras

**Do you have an error log of what happened?**
 

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:2231: attempt to index field '?' (a nil value)
Time: Mon Aug 12 05:31:51 2019
Count: 20
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:2231: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:2231: in function `Delete'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1289: in function `DeleteOption'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1315: in function `OnAccept'
Interface\FrameXML\StaticPopup.lua:5003: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**To Reproduce**
 

**Which version of WeakAuras are you using?**

Have tried with both 2.14.0-beta4-classic and beta5-classic

**Was it working in a previous version? If yes, which was the last good one?**

Get the same error on both beta 4 and beta 5 for classic

**Comment by HolteUnderscore** [comment]
Disregard this if you like, it seemed to be one particular weakaura that was causing the problem.  I can delete others fine.  Had to delete each child individually in this particular one to get rid of it.

**Comment by InfusOnWoW** [comment]
Without your settings, it's hard to tell what is exactly broken, but we think we know what the problem was and that it's fixed.
