### ISSUE TITLE
Wrong localization in italian client

### ISSUE THREAD

**Issue by TopoDiFogna** [WeakAuras/WeakAuras2#156]
What steps will reproduce the problem?
Update to lastest release and run with the italian client

What is the expected output? What do you see instead?
the addon should be at least in english (or italian if localized) , instead it's localized in chinese

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
yes

What version of WeakAuras are you using?
Last release pulled from curse

Was it working in a previous version? If yes, which was the last good one?
It was working in english (previous release from curse)

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
No errors

Please provide any additional information below.
![image](https://cloud.githubusercontent.com/assets/8290162/23360598/8a38730c-fcec-11e6-90ca-4ffe7e0f2bbc.png)

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/803555/SavedVariables.zip)

**Comment by Stanzilla** [comment]
Haha sorry, my bad. Fixed in the next version!
