### ISSUE TITLE
Condition Property Change to change relative position of auras

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1561]
**Is your feature request related to a problem? Please describe.**
It's a common problem (and frustration) that the current Condition Offsets Property Changes move the aura to the exact same place every time. Users often report that when they move an aura they've imported and close the options panel that their aura appears to reset its position to the same place every time, despite its X and Y coordinates being proper. In addition, setting a static location works well in a group, where the position is already relative to where you place the group, but I think that auras outside of a group could use a better option.

Therefore I propose the addition of a Relative Positioning Condition Property Change.

**Describe the solution you'd like**
An additional set of Condition Property Changes should be added to adjust the x an y offsets of an aura, relative to the location specified under the Display panel. Could be named Relative X-Offset or Adjust X-Offset.

The setting would simply move the aura the specified number of "pixels" away from its position specified in the Display tab. These effects would likely be additive, but could also be exclusive.

It should be able to work in tandem with the original Offset condition.

**Describe alternatives you've considered**
An alternative could be also renaming X-Offset in the current Condition Property Changes, to something like Set X Position (or even just Set X-Offset).

**Additional context**
Afenar.

Also, while technically accurate, the name of X and Y Offsets bothers me with the advent of this new potential condition. Potential for rename?

**Comment by InfusOnWoW** [comment]
So a few thoughts:
* Offsets to the position would probably have been a better choice than x/y positions.
* Having both is pretty confussing for the user, but might be the lesser evil.
* We should investigate whether there's any feature which would solve Afenars use case in a better way.
