### ISSUE TITLE
11 WA errors for chars less than level 10 on Classic.

### ISSUE THREAD

**Issue by TimothyLuke** [WeakAuras/WeakAuras2#1565]
I didn't get to capture the logs of this before the last classic stress test ended but if you had a char who was less than level 10 (no talents available) WA would throw 11 different lua errors the first relating to talents being a null.

**To Reproduce**
1. Go to Classic create a char and login

When this happened only WA was installed - 2.13.4 via Twitch Client

**Was it working in a previous version? If yes, which was the last good one?**
unknown

**Additional context**
No WA's loaded 
WA.lua file contains:

`WeakAurasSaved = nil`

**Comment by TimothyLuke** [comment]
Raising this as once past level 10 this disappears so may not be something to be cared about but more a fyi.

**Comment by emptyrivers** [comment]
2.13.4 does not support WoW classic. That support begins in 2.14.0, which is currently in beta.
