### ISSUE TITLE
hasPet not working

### ISSUE THREAD

**Issue by dunger** [WeakAuras/WeakAuras2#157]
sience version 2.3.1 hasPet isn't working anymore.

> 			["trigger"] = {
> 				["type"] = "status",
> 				["unevent"] = "auto",
> 				["debuffType"] = "HELPFUL",
> 				["event"] = "Conditions",
> 				["subeventPrefix"] = "SPELL",
> 				["names"] = {
> 				},
> 				["use_unit"] = true,
> 				["spellIds"] = {
> 				},
> 				["subeventSuffix"] = "_CAST_START",
> 				["unit"] = "player",
> 				["use_alive"] = true,
> 				["use_HasPet"] = false,
> 				["use_mounted"] = false,
> 			},

with version 2.3.0.0 i have no problems

**Comment by Stanzilla** [comment]
Can you post the whole aura please?

**Comment by dunger** [comment]
`d0J8caGAvOA9sv4Lsv0UKqBtcMPuLmxvKMTOUPkIdl42KYFLODku7fTBc7NO6NuvgMqghvrFJOudLOKbtcdNKoOuv8AQsDms15ub1cjrlvfIftuSCL6HuL8uWYuj8CftufKPsLjtKPdDrPQYvLQQUmLRlYPv1OKQuBwsTDPYNLKVQIY0Ok8DvGgPkG1PcLrRs04vH0jvjDlPQ01ur15vPEgvvpwj)wktD6iOrqIGeDecl87m3(RQS9jnjJXreW9xvzB6iG3QgHbdyAiKewNjqcHe2iKgR8aHrwgsziKgRmK)oJkjyDMaj4vti943edH0yLATKanjkdrc5wqIocPXkfwNTPmeWq2eiDe0sz8PJX6fOsgRlBQKircJQTOJW8IQSXy)e0sz8PJX(PsIejSYHzOJW8IQSr4S(CKE5ZREsKqASsmKnbsziKgRCLdZqLe2HLrhbTugF6isKqDyHFtqhbTugF6isKGANkgYMaPJGwkJpDejsq6RR)vkJ30rqlLXNoIejSBzJocAPm(0rKiH0yLJQTOsIeQBce(Eymw3dcs)OMd3agwEpeo4L22g5kUBPTCfQgkxHwqixXX6nHTv9nH7w1i8RMGWr9vxpgY4(Q7)WfJIIIkOh5)C9ceEXJLRMMA2qtIX6eK(54jXc)oJqqCtyWWY7XRMadVqZeibF93bxpu)iC7RUEmKXfkgffP7PF9OZ9OGNEs4LiC2L22g5ksB5kunuUcjBWDJGiP52FvLThgRtq6h1C4(6QjiCvG2UoSStVUAI50x0vQAy52KudcPaHbdlVhz1EbsqPpNZ3jejmeUOO)IrfJi0XyDpUqNija`

Original WA: https://wago.io/Vyx12GkVZ/g/Wheres%20ur%20pet%20demo

**Comment by InfusOnWoW** [comment]
Fixed in the next release/alpha.
