### ISSUE TITLE
bug error loading item id

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#1570]
**Describe the bug**
Few days ago i got hamered in EP raid with messsage"error loading item id number": I removed all addons ,went into raid by myself and turned of addons  1 by 1 .All was clean until i got to WA.Then i started getting sam message again.I tried switching from latest alpha to release version  and few beta and alphas in betwwen but nothing changed everything was gtting same erorr messages.In the end i even switched off Wa and error was still there. Its very confusing.Not sure if wa is responsiable for it but it started when i tried to turn on WA.

**Do you have an error log of what happened?**
no error logs

**To Reproduce**

Just using addons and going into raid. No errors outside raid.
**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did,  didnt trigger a errors on itself .

**Which version of WeakAuras are you using?**
When i started noticing errors was beta 5 then last raid latest beta5-12.

**Was it working in a previous version? If yes, which was the last good one?**
Started in last monday raid i think didnt notice before it.
**Additional context**
Not sure if directly related to specific aura since they all seemed to work .Only chat window got spammed to oblivion with that error message

**Comment by mrbuds** [comment]
> Do you have an error log of what happened?
no error logs

**Comment by mrbuds** [comment]
Some auras will need an update for current beta / next release, but you must give us a error log or we can't help you.
The issue template explained how to provide an error lof

>If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install https://www.curseforge.com/wow/addons/bugsack & https://www.curseforge.com/wow/addons/bug-grabber, yes both are needed. 
Note that if the error looks like `[string "--[[ Error in ' my awesome aura' ]` then the bug is in the aura that got mentioned, not in WeakAuras itself -->

**Comment by Addonman** [comment]
It doesnt give any errors that i can catch and post herer just spams  chat window with "error loading item id ...." non stop so basicly i couldnt read chat because of it.

**Comment by mrbuds** [comment]
The string "error loading item" is not in WeakAuras source code, your error must come from something else. You said yourself you can see the error message with WeakAuras turned off.
