### ISSUE TITLE
status - cast - "multitarget" turned to"nameplate" after updating to recent beta

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1576]
**Describe the bug**
all status - cast - unit - multitarget weakauras were converted to unit - nameplate auras upon updating to recent beta

**To Reproduce**
1. import https://wago.io/bfaraid4 with 2.13.4, check out 08 Arcane Detonation weakaura
2. update to recent beta and try again, notice how it's "nameplate" unit now.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
WeakAuras-2.14.0-beta5-16-ge384546

**Was it working in a previous version? If yes, which was the last good one?**
2.13.4

**Comment by mrbuds** [comment]
it's intendended
