### ISSUE TITLE
[2.14.0-beta5] Importing aura weird behavior.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1578]
**Describe the bug**

I have a copy of an aura from wago.io, that I modified for other use. I deleted the original, and re-imported the original. Instead of importing as its own aura as indicated, it put my modified copy into the group that I imported, but the actual aura that is supposed to have been imported with the group does not appear.

Then attempting to import again, as a copy now, appears to do nothing. Reloading shows new auras, but still has my modified copy in the new group, and the copy aura is in the first group instead of the copy group.

**Do you have an error log of what happened?**
 
No errors are being thrown.

**To Reproduce**
 
(Saved Variables file provided below)
1. Delete existing ZT Front-End Bars children and group.
2. Import https://wago.io/EhARpYudu/1.0.8
3. Observe that the modified copy was placed into newly imported group, and aura expected to be imported is missing.
4. Import again, as copy.
5. Observe no change in auras.
6. Reload and observe all imported auras inside one group, and an additional empty group.

**Screenshots**

https://streamable.com/ter6y
https://streamable.com/7qur4
https://i.imgur.com/XL13jiR.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tested with only the 5 official WA addons enabled.

**Which version of WeakAuras are you using?**

2.14.0-beta5

**Was it working in a previous version? If yes, which was the last good one?**

At least 2.14.0-beta1.

**Additional context**

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3511733/WeakAuras.zip)

**Comment by mrbuds** [comment]
this was fixed with https://github.com/WeakAuras/WeakAuras2/commit/a0ac71e4ead81c52efdcd0494141b28c08721b33
