### ISSUE TITLE
Status - Power - PowerType trigger naming improvements

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1593]
Currently when you select a PowerType, I'd expect the trigger to only return true if the player has this PowerType active, yet it returns true all the time. Checking "Only if Primary" fixes that but it's a bit weird. Thoughts?

```
!nsv0YjUom0VMDM9LDNaLE39vOn0Ym0ewS7D69ftDsCs8SbBASdu6d73(vsouY2(q7mmHezzDKo6ijgj4c2wbRa)bVw1ypiYeSNtllDkVijsWoo4DPjV22UYQnEb7Q4eE8Abl3ABkShmSd6DkXSZgIlQuy005wdA33QRQuToaPec5Ed0RhH7YCEPVZb)3LP2RmEwxzP(zbBZvtz8nm(01GRfDTsVgcjBKG15uBKzoBB2D2ccD6Ic2k7biY05DgThpPZ0FMSZBfSDOheUjJUaWCNQPzrbMD(ZzWQwfLbSvXlxkyg5wvVhuuz7AKhpHZ5acGvOYGKNtL1TXlxn)(LHBDUO9ObzUxVxXdgPAi5BJIWtasw1AKn)lqzy5MmESG9BLA3uivZ9RrsaPxPrVnqiCIbB9IbS0MEMvbnbO46jAJ1Oqm2k1MpV3LAJ2v)P93JSGd6OGVKqaLxxzBSTbfa(Bm98c65e8zG7xRQGOpqPOE2VXvlbz1dd0J9O3LHN37v41V46)m)JXJ8R0IkJ5T6x(ZJ)Qtwa5S8ppY)BShM8ruWIOGf9MGf8()gMPKzvtz)WZ075PdqoOtsVNVCrsCV9)AyBrss86nZs5807wV4MB5NggFhi71oDwdPbBTW8KItesskg4WDE4T3btbM(fCsyCOXvR0v1Gh)ZebRXkPTdOSJwy0141N0V5nsN7DwDyWEJrFqamVv9uNYKFeG)7JVeYaB((ts8Fgnokk4xGsY68ERjfCag06pOwN)BJcqfyCYYW6PLuoHltlEG1sf(6qLGQuTVxz1p8f(41bNHYCAiu7FDuTZdKx6UbbOtdRohvC38BoU9PVEdSi4fRDlLiyInS5iB2vlPu(0(rSXCT2jHUvbniJRLMfUjlx2OiVre4khsQNLpN29w2clKG9OGyLCo0FNJwdua7Q1XXjiMF4yaqoL6QtLn2sEDODPYuHCiSyc30DEogoVq7WLGlqUgwKE5pM0x8l1qtcAPHVMzBlu4fWcrWUwTxW2dxyYyeCX))
```

Demo Aura

**Comment by mrbuds** [comment]
I'd expect it to work the way it's working now

**Comment by InfusOnWoW** [comment]
I think it's fine too, this works nicely for druids. Maybe the "Only if Primary" needs a better name.

**Comment by Stanzilla** [comment]
certainly something that clarifies that it only checks for the above selected power type if you also select this one

**Comment by InfusOnWoW** [comment]
you need to suggest something...

**Comment by Stanzilla** [comment]
I'm thinking!11

**Comment by InfusOnWoW** [comment]
Let's try the closing a report, gets you a response from reporter thing.

**Comment by InfusOnWoW** [comment]
@Stanzilla you are supposed to suggest somthing....

**Comment by Stanzilla** [comment]
"Ignore Mana"?

**Comment by InfusOnWoW** [comment]
you can track mana in bear form with the trigger set to mana and only if primary not selected.

**Comment by nullKomplex** [comment]
Given this one probably too much thought. The only thing I can think of is inverting its behavior, and instead making the toggle something like "Show Always".

**Comment by InfusOnWoW** [comment]
"Show Always" as in, "show even if not currently active"? That would work for druids. But doesn't for classes that have multiple "active" powers, e.g. shadow priests, warlocks.

**Comment by InfusOnWoW** [comment]
There's little point in keeping this open, unless there's something concrete to be done.
