### ISSUE TITLE
Bar length returns as 0 On Init if weakaura is within a Dynamic Group

### ISSUE THREAD

**Issue by Saxayone** [WeakAuras/WeakAuras2#1596]
**Describe the bug**

Bar length returns as 0 when called in On Init if the weakaura is within Dynamic Group.

aura_env.region:GetWidth() and aura_env.region.icon:GetWidth() will return the correct values for the weakaura however aura_env.region.bar:GetWidth() will just return 0
 
This only happens within a dynamic group.
I am assuming that it has something to do with the dynamic group and waiting to see if the width is altered due to it?
However the I was just using a grow downward so the width shouldn't ever change as a result of it being a dynamic group.

**Comment by InfusOnWoW** [comment]
That's because of how anchoring in wow works. A not yet anchored frame has no size.
