### ISSUE TITLE
Document OPTIONS fake event and other new things relevant for custom code.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#1599]
2.14 introduces a lot of new features. It is also a breaking upgrade for a lot of custom code, and we should document the new behavior in the wiki with the OPTIONS fake event, and anything else that we want users to know about.

I would do it, but tbh I don't even know everything that's been added/changed. You can blame Final Fantasy XIV + my own laziness for that.

**Comment by InfusOnWoW** [comment]
I added some sentences to https://github.com/WeakAuras/WeakAuras2/wiki/Custom-Triggers, but I don't know what else to add.
