### ISSUE TITLE
Error prevents Weakauras from loading after updating to 2.14.1

### ISSUE THREAD

**Issue by BillWiegert** [WeakAuras/WeakAuras2#1600]
**Describe the bug**
Updated to version 2.14.1 from 2.13.4 (Never updated to 2.14.0)

**Do you have an error log of what happened?**
1x WeakAuras\WeakAuras-2.14.1.lua:3184: table index is nil
WeakAuras\WeakAuras.lua:3184: in function `Modernize'
WeakAuras\WeakAuras.lua:3940: in function `PreAdd'
WeakAuras\WeakAuras.lua:4054: in function `Add'
WeakAuras\WeakAuras.lua:3609: in function `load'
WeakAuras\WeakAuras.lua:3616: in function `AddMany'
WeakAuras\WeakAuras.lua:1521: in function <WeakAuras\WeakAuras.lua:1509>

**To Reproduce**
1) Update to 2.14.1
2) Log in

I've had to revert to version 2.13.4 and replace my WTF folder with a backup made prior to updating

**Comment by emptyrivers** [comment]
I'm so glad that you have a backup. Can you please provide a copy of said backup? This looks to be a data-specific issue, so that will help with fixing the problem.

**Comment by BillWiegert** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3537879/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
This should be fixed with 2.4.2
