### ISSUE TITLE
RegionTypes error, can't open WA window

### ISSUE THREAD

**Issue by Dracolince** [WeakAuras/WeakAuras2#1604]
I've just updated to 2.14.1 and this error pops up constantly:

> Message: ...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:480: SetDrawLayer: sublevel must be between -8 and 7!
Time: Sun Aug 25 14:20:42 2019
Count: 5
Stack: ...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:480: SetDrawLayer: sublevel must be between -8 and 7!
[C]: in function `SetDrawLayer'
...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:480: in function <...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:470>
...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:784: in function <...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:781>
...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:880: in function `SetAdditionalProgress'
...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:1298: in function `Update'
Interface\AddOns\WeakAuras\WeakAuras.lua:5472: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:5471>
Interface\AddOns\WeakAuras\WeakAuras.lua:5561: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:5528>
Interface\AddOns\WeakAuras\WeakAuras.lua:5645: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\GenericTrigger.lua:663: in function `ScanEventsInternal'
Interface\AddOns\WeakAuras\GenericTrigger.lua:619: in function `ScanEvents'
Interface\AddOns\WeakAuras\GenericTrigger.lua:748: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:739>
[C]: in function `TargetUnit'
Interface\FrameXML\SecureTemplates.lua:496: in function `handler'
Interface\FrameXML\SecureTemplates.lua:632: in function `SecureActionButton_OnClick'
Interface\FrameXML\SecureTemplates.lua:672: in function <Interface\FrameXML\SecureTemplates.lua:664>
Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
{*temporary) = "OVERLAY"
(*temporary) = 8

I can't revert to a previous WA version, the error still persists. I can't even open the Weak Auras window, the /wa command doesn't work, no chat message or error or anything at all. Everything was fine a few hours ago when I logged out for the night, so the only thing I did in between was to update WeakAuras this morning before logging in (I usually update once a day in the morning, if there's an update) :\

I'm attaching my WA file (it uses some custom textures, but I guess they'll show up as green squares, if anything).

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3538137/WeakAuras.zip)

**Comment by timmywil** [comment]
I get a different error, but I also can't open the weakauras window.

> Message: Interface\AddOns\WeakAuras\WeakAuras.lua:3968: attempt to call field 'ClearAuraEnvironment' (a nil value)
Interface\AddOns\WeakAuras\WeakAuras.lua:3968: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3949>
Interface\AddOns\WeakAuras\WeakAuras.lua:4055: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3609: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3588>
Interface\AddOns\WeakAuras\WeakAuras.lua:3601: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3616: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>

> Time: Sun Aug 25 09:47:20 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:3968: attempt to call field 'ClearAuraEnvironment' (a nil value)
Interface\AddOns\WeakAuras\WeakAuras.lua:3968: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3949>
Interface\AddOns\WeakAuras\WeakAuras.lua:4055: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3609: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3588>
Interface\AddOns\WeakAuras\WeakAuras.lua:3601: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3616: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>

> ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:582: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:542>
Interface\AddOns\WeakAuras\WeakAuras.lua:1632: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1586>

> Locals: <none>

**Comment by InfusOnWoW** [comment]
@timmywil  that's unrelated, create a new bug report and include your settings please.

**Comment by timmywil** [comment]
I take it back. It was an installation issue.
