### ISSUE TITLE
latest version of classic is updating for Retail (BFA)

### ISSUE THREAD

**Issue by Dimmn** [WeakAuras/WeakAuras2#1606]
Your latest version of Weakaura 2.14.1-3-g423d436-classic just updated through the twitch client for retail and broke my 100 of custom weakauras.

**Comment by emptyrivers** [comment]
Unfortunately, there is nothing we can do to fix bugs in the twitch client. I would suggest turning off auto-updating in the meantime until that is sorted out on twitch’s end.

**Comment by InfusOnWoW** [comment]
And we are pretty sure, that your settings aren't lost. The classic version should not load on retail and thus not modify your settings. That is on using the correct version, your auras should appear.
