### ISSUE TITLE
Unable to open WA with the 2.14.2 patch.   I get a stream of LUA errors once I am in WoW as well.  I reverted back to the  2.13.4 version to get WA to work.

### ISSUE THREAD

**Issue by Lorgard** [WeakAuras/WeakAuras2#1607]
**Describe the bug**

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by InfusOnWoW** [comment]
Please actually include information in your bug reports.

**Comment by Lorgard** [comment]
Message: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)
Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: in function `GetNameAndIcon'
Interface\AddOns\WeakAuras\BuffTrigger.lua:1893: in function `CreateFallbackState'
Interface\AddOns\WeakAuras\WeakAuras-2.14.2.lua:4930: in function `CreateFallbackState'
Interface\AddOns\WeakAuras\WeakAuras.lua:5627: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\BuffTrigger.lua:823: in function `ScanAuras'
Interface\AddOns\WeakAuras\BuffTrigger.lua:1343: in function `ScanAll'
Interface\AddOns\WeakAuras\BuffTrigger.lua:1446: in function `FinishLoadUnload'
Interface\AddOns\WeakAuras\WeakAuras.lua:2193: in function `FinishLoadUnload'
Interface\AddOns\WeakAuras\WeakAuras.lua:2005: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1869>
Interface\AddOns\WeakAuras\WeakAuras.lua:2099: in function `ReloadAll'
Interface\AddOns\WeakAuras\WeakAuras.lua:1758: in function `ScanAll'
Interface\AddOns\WeakAuras\WeakAuras.lua:1703: in function `Resume'
Interface\AddOns\WeakAuras\WeakAuras.lua:1542: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>

Time: Sun Aug 25 15:26:53 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)
Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: in function `GetNameAndIcon'
Interface\AddOns\WeakAuras\BuffTrigger.lua:1893: in function `CreateFallbackState'
Interface\AddOns\WeakAuras\WeakAuras-2.14.2.lua:4930: in function `CreateFallbackState'
Interface\AddOns\WeakAuras\WeakAuras.lua:5627: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\BuffTrigger.lua:823: in function `ScanAuras'
Interface\AddOns\WeakAuras\BuffTrigger.lua:1343: in function `ScanAll'
Interface\AddOns\WeakAuras\BuffTrigger.lua:1446: in function `FinishLoadUnload'
Interface\AddOns\WeakAuras\WeakAuras.lua:2193: in function `FinishLoadUnload'
Interface\AddOns\WeakAuras\WeakAuras.lua:2005: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1869>
Interface\AddOns\WeakAuras\WeakAuras.lua:2099: in function `ReloadAll'
Interface\AddOns\WeakAuras\WeakAuras.lua:1758: in function `ScanAll'
Interface\AddOns\WeakAuras\WeakAuras.lua:1703: in function `Resume'
Interface\AddOns\WeakAuras\WeakAuras.lua:1542: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>


Locals: <none>
Message: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)
Time: Sun Aug 25 15:26:58 2019
Count: 4
Stack: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)

Locals:

**Comment by mrbuds** [comment]
We need you WeakAuras.lua  that you can find in this path:

World of Warcraft/_retail_/WTF/Account/<account #>/SavedVariables/WeakAuras.lua (change <account #> to your account #).

**Comment by Lorgard** [comment]
Here you go!

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3538662/WeakAuras.zip)
