### ISSUE TITLE
2.14.2 broke WAs and unable to open WA interface.

### ISSUE THREAD

**Issue by PooCz** [WeakAuras/WeakAuras2#1608]
**Describe the bug**

2.14.2 broke WAs and unable to open WA interface using minimap button or /wa.
**Do you have an error log of what happened?**
 
Message: Interface\AddOns\WeakAuras\Prototypes.lua:4379: attempt to index field 'form' (a number value)
Interface\AddOns\WeakAuras\Prototypes.lua:4379: in function `init'
Interface\AddOns\WeakAuras\GenericTrigger.lua:238: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:220>
Interface\AddOns\WeakAuras\GenericTrigger.lua:1051: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3982: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3951>
Interface\AddOns\WeakAuras\WeakAuras.lua:4057: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3611: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3618: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>

Time: Sun Aug 25 11:56:42 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:4379: attempt to index field 'form' (a number value)
Interface\AddOns\WeakAuras\Prototypes.lua:4379: in function `init'
Interface\AddOns\WeakAuras\GenericTrigger.lua:238: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:220>
Interface\AddOns\WeakAuras\GenericTrigger.lua:1051: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3982: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3951>
Interface\AddOns\WeakAuras\WeakAuras.lua:4057: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3611: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3618: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>

Locals: <none>
**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

YEs, WA only addon enabled.
**Which version of WeakAuras are you using?**

2.14.2
**Was it working in a previous version? If yes, which was the last good one?**

[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/3538307/WeakAuras.lua.zip)
It was working yesterday (08/24/2019). Not sure what version that was.
**Additional context**

``` HERE ```

**Comment by PooCz** [comment]
I uninstalled WA, reinstalled, used backup to get WAs back, and now everything is working.

**Comment by Recanna** [comment]
I'm having this same problem. WA don't seem to display and I can't open the config window. 

I've tried uninstalling and reinstalling as the OP but issue is still unresolved.

**Comment by Recanna** [comment]
I had to roll back to 2.13.4  before it worked. Something in 12.14.1 and 12.14.2 breaks for me.

1x WeakAuras\Prototypes.lua:4379: attempt to index field 'form' (a number value)
WeakAuras\Prototypes.lua:4379: in function `init'
WeakAuras\GenericTrigger.lua:238: in function <WeakAuras\GenericTrigger.lua:220>
WeakAuras\GenericTrigger.lua:1051: in function `Add'
WeakAuras\WeakAuras-2.14.1.lua:3980: in function <WeakAuras\WeakAuras.lua:3949>
WeakAuras\WeakAuras.lua:4055: in function `Add'
WeakAuras\WeakAuras.lua:3609: in function `load'
WeakAuras\WeakAuras.lua:3616: in function `AddMany'
WeakAuras\WeakAuras.lua:1521: in function <WeakAuras\WeakAuras.lua:1509>

**Comment by arharex123** [comment]
Same stuff here, after updating to 2.14.2 WA interface wont open, also most of WA's wont work. Tried reinstalling and rerolling, nothing works.

2777x WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)
WeakAuras\BuffTrigger.lua:1821: in function `GetNameAndIcon'
WeakAuras\BuffTrigger.lua:1893: in function `CreateFallbackState'
WeakAuras\WeakAuras-2.14.2.lua:4930: in function `CreateFallbackState'
WeakAuras\WeakAuras-2.14.2.lua:5627: in function `UpdatedTriggerState'
WeakAuras\GenericTrigger.lua:641: in function `ScanUnitEvents'
WeakAuras\GenericTrigger.lua:776: in function <WeakAuras\GenericTrigger.lua:773>

Locals:
InCombatSkipped

**Comment by mrbuds** [comment]
OP issue is fixed, @arharex123 @Recanna please make a new ticket and include your settings and answer all questions asked on issue template

**Comment by PooCz** [comment]
@
