### ISSUE TITLE
Maaany Lua Errors from WA 2

### ISSUE THREAD

**Issue by DerTooni** [WeakAuras/WeakAuras2#1612]
Hey cant open WA after the new update and got so many lua errors that many weakauras dont displayed...

https://pastebin.com/rJSADTnd

**Comment by InfusOnWoW** [comment]
Please include your settings without these your bug report is useless.

**Comment by DerTooni** [comment]
[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/3538677/SavedVariables.zip)

**Comment by Stanzilla** [comment]
This should be fixed now!
