### ISSUE TITLE
WA Version  2.14.2 can not open WA

### ISSUE THREAD

**Issue by Lorgard** [WeakAuras/WeakAuras2#1613]
WA does work if I roll back to 2.13.4   Here are the errors:

Message: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)
Time: Sun Aug 25 15:26:58 2019
Count: 4
Stack: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)

Locals: 
Message: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)
Time: Sun Aug 25 15:26:58 2019
Count: 4
Stack: Interface\AddOns\WeakAuras\BuffTrigger.lua:1821: attempt to index field 'spellCache' (a nil value)

Locals:

**Comment by Stanzilla** [comment]
This should be fixed now!

**Comment by Lorgard** [comment]
Yes, it is fixed.  Thanks for the fast fix.
