### ISSUE TITLE
Add wiki links to edit boxes

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1616]
All our custom code edit boxes should have a small text + wiki link below them so people have a easier time finding info about them

I guesst this format:

`(white)Learn more about custom code that you can use here on our (yellow) wiki(wikiurl).`

**Comment by emptyrivers** [comment]
This is done now, ain’t it?

**Comment by Stanzilla** [comment]
I think @infusonwow added them everywhere, in the form of a standard WoW red button though, which I'm fine with

**Comment by InfusOnWoW** [comment]
Yep I did. I apparently forgot the # before the ticket number.

The button + edit isn't exactly the best system, but better than before.
