### ISSUE TITLE
%n not formatting.

### ISSUE THREAD

**Issue by nullKomplex** [WeakAuras/WeakAuras2#1617]
**Describe the bug**

Reported by a user in discord. Example case was a progress bar using `%n`, but I didn't test all formatted text replacements to see any other changes.

Previously if the text supplied via `%n` was "too long" it was truncated and `...` was appended. This is no longer the case.

**Do you have an error log of what happened?**
 
No errors.

**To Reproduce**
 
1. Create progress bar aura.
2. Set trigger to Status - Health - Target
3. Click on a training dummy. Alternatively you can try other mobs with long names, other triggers, or resize the bar shorter.
4. Observe as name extends into other text, icon, and potentially off the aura altogether.

**Screenshots**

Old:
![image](https://user-images.githubusercontent.com/28709830/63667949-c8d3ff00-c792-11e9-8cb2-d57902aa8de3.png)

New:
![image](https://user-images.githubusercontent.com/28709830/63667943-c2de1e00-c792-11e9-974d-895547d31ea0.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tested with only the 5 official WA addons enabled and a fresh SV.

**Which version of WeakAuras are you using?**

2.14.4

**Was it working in a previous version? If yes, which was the last good one?**

Yes, 2.13.4

**Additional context**

I will be submitting a Feature Request that will address formatting very soon.

**Comment by nullKomplex** [comment]
It's likely this is by design, as a result of the text rework. Since text's positions are now movable it's likely difficult to determine where the text should be cut-off now.

**Comment by InfusOnWoW** [comment]
That truncating was a special feature of the progress bar, that didn't survive the porting. I planned to add a max width setting to texts, but forgot to do that.

**Comment by InfusOnWoW** [comment]
So I think this hasn't been a big problem. That is I haven't seen that many complaints and thus it can wait for the more serious rework that is #1618
