### ISSUE TITLE
Same error as `#1608...

### ISSUE THREAD

**Issue by Recanna** [WeakAuras/WeakAuras2#1620]
**Describe the bug**
I upgraded to 2.14.2 and when I log in it won't work. The config panel won't open. No WA displayed. I get a single bug in bugsack.  The Minimap tooltip said that the addon was Paused. I shift+clicked as the tooltip indicated and that notice went away. However the addon still did not seem to function. The case in 1608 said to uninstall/reinstall. I did that. No change. I uninstalled and installed 2.14.1, and still had the same problem. I had to roll back to 2.13.4 before it would work again. 

**Do you have an error log of what happened?**
1x WeakAuras\Prototypes.lua:4379: attempt to index field 'form' (a number value)
WeakAuras\Prototypes.lua:4379: in function `init'
WeakAuras\GenericTrigger.lua:238: in function <WeakAuras\GenericTrigger.lua:220>
WeakAuras\GenericTrigger.lua:1051: in function `Add'
WeakAuras\WeakAuras-2.14.1.lua:3980: in function <WeakAuras\WeakAuras.lua:3949>
WeakAuras\WeakAuras.lua:4055: in function `Add'
WeakAuras\WeakAuras.lua:3609: in function `load'
WeakAuras\WeakAuras.lua:3616: in function `AddMany'
WeakAuras\WeakAuras.lua:1521: in function <WeakAuras\WeakAuras.lua:1509>
**To Reproduce**
Upgrade to 2.14.2 and log into WoW.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
Now I am using 2.13.4 however the problem was seen in 2.14.2 and 2.14.1.

**Was it working in a previous version? If yes, which was the last good one?**
I skipped 2.14.1 but it was working in 2.13.4. 

**Additional context**

``` HERE ```

**Comment by mrbuds** [comment]
2.14.4 fix it, it was released 14h ago
