### ISSUE TITLE
WeakAura Trigger Error

### ISSUE THREAD

**Issue by GoldennDragonn** [WeakAuras/WeakAuras2#1625]
Greetings,
I have a WeakAura that I'm unable to detect where the bug is coming from.
The WeakAura and problem screenshot attacthed. 
https://wago.io/ja4IRIEUD
![unknown (1)](https://user-images.githubusercontent.com/54574918/63753051-fd42da80-c8ba-11e9-9081-e5710fe1927a.png)

**Comment by GoldennDragonn** [comment]
So I just shoud make the changes to WeakAuras/Prototypes.lua as you suggested or it will be fixed in future update of WeakAura addon ?

**Comment by mrbuds** [comment]
The plan is to fix the addon function for everyone, but you can make the change on your own weakauras if you want
