### ISSUE TITLE
Maul/Heroic strike visible toggle

### ISSUE THREAD

**Issue by Castnicke** [WeakAuras/WeakAuras2#1628]
**Is your feature request related to a problem? Please describe.**
I am unable to get druid maul (and warrior heroic strike) to visibly show that it has been queued/toggled in weakauras

**Describe the solution you'd like**
There should be something that looks for this state so that the weak aura icon can visibly change when queued/toggled

**Describe alternatives you've considered**
I tried many ways to get it to work but was unable to

**Comment by mrbuds** [comment]
for reference https://github.com/WeakAuras/WeakAuras2/issues/1645 has useful info on how to do it

**Comment by mrbuds** [comment]
I have something that seems to work with heroic strike and raptor strike, but i don't like that it doesn't work as good as i wish with attack and auto shot

what i have:
```Lua
  ["Current Action"] = {
    type = "status",
    events = {
      ["events"] = {
        "ACTIONBAR_UPDATE_STATE",
        "ACTIONBAR_SLOT_CHANGED",
        "ACTIONBAR_PAGE_CHANGED",
        -- "SPELL_UPDATE_USABLE"
      }
    },
    name = L["Current Action"],
    init = function(trigger)
      local ret = [[
        local spell = %q
        local button
        if spell ~= "" then
          local spellid = select(7, GetSpellInfo(spell))
          if spellid then
            local buttons = C_ActionBar.FindSpellActionButtons(spellid)
            if buttons and buttons[1] then
              button = buttons[1]
            end
          end
        end
      ]]
      return ret:format(trigger.spell or "")
    end,
    args = {
      {
        name = "spell",
        display = L["Spell Id or Name"],
        type = "string",
        conditionType = "string",
        test = "button and IsCurrentAction(button)",
      },
    },
    statesParameter = "one",
    automaticrequired = true,
    nameFunc = function(trigger)
      return GetSpellInfo(trigger.spell)
    end,
    iconFunc = function(trigger)
      return select(3, GetSpellInfo(trigger.spell))
    end
  },
```

**Comment by InfusOnWoW** [comment]
That would only work with the ability on the action bar. E.g. it fails if it is in a macro

**Comment by Castnicke** [comment]
If I want to try this out, where exactly would I put it?

**Comment by mrbuds** [comment]
You can use this instead @Castnicke https://wago.io/3Jg6NPdc3 but as infus said you must have heroic strike on action bars (without macro).

I don't think this is going to be a built-in generic trigger in weakauras, and i'd like to close it, do you agree @WeakAuras/core ?

**Comment by nullKomplex** [comment]
We have the same restriction with Pet stances, which is a default trigger.

**Comment by Castnicke** [comment]
@mrbuds How to I get this weak aura to work with maul?

**Comment by InfusOnWoW** [comment]
I actually think we should provide a built-in trigger for that. Either the name or a description should point to the limitations though.
