### ISSUE TITLE
GetWeaponEnchantInfo function not updated (classic)

### ISSUE THREAD

**Issue by Seminko** [WeakAuras/WeakAuras2#1636]
**Describe the bug**
Setting up Type: Status, Status: Fishing Lure / Weapon Enchantment (Old) the addon stops working.
It shouldn't.

**Do you have an error log of what happened?**
Message: Interface\AddOns\WeakAuras\GenericTrigger.lua:2928: attempt to perform arithmetic on local 'oh_rem' (a boolean value)
Interface\AddOns\WeakAuras\GenericTrigger.lua:2928: in function `tenchUpdate'
Interface\AddOns\WeakAuras\GenericTrigger.lua:2953: in function `TenchInit'
Interface\AddOns\WeakAuras\Prototypes.lua:4497: in function `init'
Interface\AddOns\WeakAuras\GenericTrigger.lua:238: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:220>
Interface\AddOns\WeakAuras\GenericTrigger.lua:1051: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3985: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3954>
Interface\AddOns\WeakAuras\WeakAuras.lua:4060: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3614: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3621: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>

Time: Thu Aug 29 18:40:37 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\GenericTrigger.lua:2928: attempt to perform arithmetic on local 'oh_rem' (a boolean value)
Interface\AddOns\WeakAuras\GenericTrigger.lua:2928: in function `tenchUpdate'
Interface\AddOns\WeakAuras\GenericTrigger.lua:2953: in function `TenchInit'
Interface\AddOns\WeakAuras\Prototypes.lua:4497: in function `init'
Interface\AddOns\WeakAuras\GenericTrigger.lua:238: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:220>
Interface\AddOns\WeakAuras\GenericTrigger.lua:1051: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3985: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3954>
Interface\AddOns\WeakAuras\WeakAuras.lua:4060: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3614: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3621: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1521: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1509>

Locals: <none>

**To Reproduce**
Set Type: Status, Status: Fishing Lure / Weapon Enchantment (Old), Weapon, Weapon enchant and restart the game. The above error appears and the GUI won't even show.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
WeakAuras-2.14.5-classic

**Was it working in a previous version? If yes, which was the last good one?**
No idead, probably not

**Additional context**
It has to do with the fact that the GetWeaponEnchantInfo function changed a while ago - a few parameters were added so the function in the addon takes incorrect info.
https://wow.gamepedia.com/API_GetWeaponEnchantInfo

**Comment by mrbuds** [comment]
please answer the questions asked in the template

**Comment by Seminko** [comment]
done

**Comment by InfusOnWoW** [comment]
That's going to be fixed by https://github.com/WeakAuras/WeakAuras2/pull/1633

**Comment by Seminko** [comment]
As per the channel log, this has been fixed. Unfortunately, I still can't figure out how to set it up so that an overlay lights up when my poison expires.
Could you please help?

**Comment by emptyrivers** [comment]
If you want help using WeakAuras, please visit our discord server: http://discord.gg/wa2
