### ISSUE TITLE
Animation Sequence

### ISSUE THREAD

**Issue by Yaki-tory** [WeakAuras/WeakAuras2#1641]
**Describe the bug**

Animation Sequence: 1135049
It is between 0 and 150, none make any difference in the animation, like it used to before a week.

**Do you have an error log of what happened?**
No.
 

**To Reproduce**
 

**Screenshots**

It is an animation.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, no change.

**Which version of WeakAuras are you using?**

The newest one: 2.14.5

**Was it working in a previous version? If yes, which was the last good one?**

Yes, but can't really say which one, it was 1 week ago.

**Additional context**

``` HERE ```

**Comment by mrbuds** [comment]
Can you give more information, like a step by step guide on how to reproduce the issue, what it does and what you expect it to do ? And also please add an export an aura as an example.

**Comment by Yaki-tory** [comment]
The animation sequence should show an animation. And moving the bar from lower animation sequence to higher should speed up the animation that i've chosen (1135049 - sort of an arcane explosion). I've put this one on the Havoc Demon Hunter's Fury Bar while I have Metamorphosis On. So the Arcane explosion happens like thousands of times a second and it looks really glittering, it looks like sparkles. Before a week and few days there was an update and this Animation Sequence doesnt work at all, doesnt matter if I put it on 1-2-3-4-5 or 120-130-140-150 you get the idea. It is the same animation without speed/slow up. Just simple arcane explosion once every 3 seconds instead thousands of times in a second.
[Animation Sequence bug.docx](https://github.com/WeakAuras/WeakAuras2/files/3562309/Animation.Sequence.bug.docx)

**Comment by Yaki-tory** [comment]
Its on "Fury_Model"
