### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by b3369** [WeakAuras/WeakAuras2#1644]
Date: 2019-08-30 09:50:43
ID: 1
Error occured in: Global
Count: 1
Message: [string "--[[ Error in 'Ice Block Buff 2':'custom te..."] line 3:
   attempt to index field 'text2' (a nil value)
Debug:
   [C]: xpcall()
   WeakAuras\WeakAuras.lua:5705: RunCustomTextFunc()
   ...nterface\AddOns\WeakAuras\SubRegionTypes\SubText.lua:221: Update()
   WeakAuras\WeakAuras.lua:5481:
      WeakAuras\WeakAuras.lua:5476
   WeakAuras\WeakAuras.lua:5566:
      WeakAuras\WeakAuras.lua:5533
   WeakAuras\WeakAuras.lua:5650: UpdatedTriggerState()
   WeakAuras\GenericTrigger.lua:728: ScanWithFakeEvent()
   WeakAuras\GenericTrigger.lua:988: LoadDisplays()
   WeakAuras\WeakAuras.lua:2148: LoadDisplays()
   WeakAuras\WeakAuras.lua:2003:
      WeakAuras\WeakAuras.lua:1869
   WeakAuras\WeakAuras.lua:2099: ReloadAll()
   WeakAuras\WeakAuras.lua:1758: ScanAll()
   WeakAuras\WeakAuras.lua:1703: Resume()
   WeakAuras\WeakAuras.lua:1542:
      WeakAuras\WeakAuras.lua:1509

**Comment by emptyrivers** [comment]
This is an error in the aura named "Ice Block Buff 2". Updates the aura, contact the author to get them to fix it, or disable it.

**Comment by InfusOnWoW** [comment]
Or if you want to fix it yourself, delete the code that refers to text2 and position the text with the options on the display page.
