### ISSUE TITLE
Classic Hunter Aimed Shot 

### ISSUE THREAD

**Issue by Fraggling** [WeakAuras/WeakAuras2#1654]
Hey im not sure if i am doing something wrong but i have been using weakauras for some time and  know a fair bit about using the addon.
i am currently playing MM hunter in classic and have just got aimed shot my issue is that i have cast  bar set up and a swing timer bar for ranged and melee but for some reason aimed shot cast is not being tracked by my standard player cast bar yet every other cast or channeled  ability shows up fine. is there something i am missing or is there a reason this cast cannot be tracked. ???

**Comment by mrbuds** [comment]
I don't think so, but please answer all the questions asked in the ticket template

**Comment by emptyrivers** [comment]
No response after 3 days.
