### ISSUE TITLE
TickMark Progress Bar

### ISSUE THREAD

**Issue by efremzero7** [WeakAuras/WeakAuras2#1656]
So, there's no way that i know of, to add tickmarks to certain points of a progress bar, without codes. Am i missing something? if not, i would really love this feature. Thanks

**Comment by nullKomplex** [comment]
Potentially as a SubRegion maybe?

**Comment by efremzero7** [comment]
sorry, i dont know how that works :(

**Comment by InfusOnWoW** [comment]
That wasn't meant for you. There's no feature for that atm, nullKomplex was suggesting how to implement it. And indeed that's the plan, though it might take a bit of work to get there.
