### ISSUE TITLE
Unit Characteristics Trigger for Target Race

### ISSUE THREAD

**Issue by dotrich** [WeakAuras/WeakAuras2#1657]
**Describe the solution you'd like**
I have a chest item in Classic WoW called Raptorbane Armor. It has an effect on equip to increase AP by 30 when fighting beasts. I would like to be able to check the target for race such as Beasts. I checked 'Trigger > Status > Unit Characteristics > Target' to no avail. It would be most useful if it was under 'Character Type' as a sub-option depending on if you chose NPC or Player Character. I would choose NPC, a sub-option would appear and I would select Beast.

**Additional context**
I was going to create a small icon and text to appear when the  target I select was a Beast so I would remember to hotswap my gear. I'm sure there are other circumstances this would be useful in.

Thank you.

(This is the second time I have wrote this message out because the 'Show related issues' option above deleted my message.)

(Clicking 'Show related issues' seems to have removed the feature request attirbute from this post. Sorry!)

**Comment by InfusOnWoW** [comment]
The api for that, UnitCreatureType unfortunately only returns a localized string and no id that we could use. And even if it would return a non-localized id, I'd say that's not something I expect more people to have use for, so I think this is best handled with a custom trigger.
