### ISSUE TITLE
Faerie Fire doesn't have a duration/progress like other debuffs on Classic

### ISSUE THREAD

**Issue by typhirz** [WeakAuras/WeakAuras2#1658]
**Describe the bug**
Faerie Fire, and the feral version, are not showing a duration, cooldown sweep, etc. when using a weakaura that would show these things with a different debuff. The same weakaura that successfully shows the remaining duration of, say, Moonfire, does not show the remaining duration of Faerie Fire by just changing the name (nor does it work with a general weakaura like DebuffsOnNameplates). It shows the icon correctly, just not the duration, cooldown sweep, etc. 

**Do you have an error log of what happened?**
No errors.

**To Reproduce**
1. Create an icon or progress bar weakaura
2. Set Type to Aura, Unit to Target, Aura Type to Debuff, and select name, typing Faerie Fire
3. (If Icon) Turn on "Show Cooldown"
4. Find a mob and cast Faerie Fire on it
5. Observe

**Screenshots**
https://imgur.com/Cc9HPw9
The debuffs above the nameplate are from DebuffsOnNameplates on wago.io, showing that Rake and Rip both work. Then there is a progress bar and an icon above the target unitframe.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, everything except WeakAuras was turned off for a test and it still occurred.

**Which version of WeakAuras are you using?**
2.14.6

**Was it working in a previous version? If yes, which was the last good one?**
Have not tried with previous versions.

**Additional Context**
https://wago.io/DebuffsOnNameplates

and also

!Dx12UTnoq0VMfy7doqxCCtE0XrETbCKtfvAtxuqhAPr2CRmLbfLBIFiF7DgkQy70IUblW(sbSKPgE4WzoZnUppLZK8y)WbEHHCwnNfCMF)ZgWzB4SC6hcOERq)1pjZnRrKEUVNxuudM75XOarJzDLE(wJSsvJNWWzp1UpF85(bx67DPNN3GlcppOpVOx)ZXJOYWJCBLuHGhffNgL4uCsLrqkYQ5tKCtvoWzdVlDoA0ziIR4mJwUAfOPBn26nob0YMAiwSbiyIgTqHRD4yJfGwcp)WyPg4XbNk45h(ZXGwu(oYrGDazItarj6)S6MLwj3QHc5JCg72OzZi7eklNM7C(oqSMclOfJgYsxWshMqwLsIqmc9kKEyDgfj6PTqRLI2toSepCQv0KHj3m(UzeMg1b)Zqcezg5oiTvOLGI7HXitldTiRQSs36Z0Va77q77(0BcNYaALO8JilAP9akraklEvWzPqp6h0MNvBEh0woulmOlya(YtYu(CB8SzzcSYLM4cyV424nSaFq1GQM2bE0SOETiV6B37sNOyx7bqnr77q1U8p26(8n42wCfvKhowl3)8dFOrKJ2T45hsp9Up2R9(5E9rO)CNL2ZVt(bUSn39LRUn8gxPaNWtQkMghhLSyw040UYLx0TNd)ozTCzPndxtfjqQLhINhh1DM7F9zOlMj3Jjk(bevh(FJQv)(r1jt)Rj)VY1i81GC1AICXEGLvcx)viJ(FttPr2vyNvkQR)bP1KYELqJRo7QsqL76rE9122FdZ)NMAdKd53iEKki)wBx8apVxVVur7RTfNPhxssoNCtBlzYyXoxgArovLJcx4ssaSFd2a0LZOiMgTSncP6TJUqQK1RFZ4D9)A7M8ILDSES93KMo6Z2tSwsuKlyVVQAt3mSkk2APYjUOuOlq2Gtjyxvk3VxOXPIs8POWHnTB)PuJ0crg8LrIAJuT6kH(l3nT3HV6XOd4ohr3MQSDDTD99d9c6UFzEoGvyXrFKA9IwDHCLZ104edCkhw(ylrBZ8gtsBdBSrjrrX4gLBx3cPHS3THp9KENQeMCnXj01EOf9O)9I4kC8OYnzMnzEY0)EEC6WzwJlxE0K)h7M8FXGl73FGFGVV3fbV)9EUj)lfzFDLUQrL)RR29o782G2oeq)aYi4F)

**Comment by mrbuds** [comment]
I made a ticket for libclassicduration you can track it at https://github.com/rgd87/LibClassicDurations/issues/12
When it is solve there, either install the lib standalone or wait for a new version of weakauras that include it.
