### ISSUE TITLE
Search filter periodically resets to empty

### ISSUE THREAD

**Issue by jcai1** [WeakAuras/WeakAuras2#166]
The issue is only on my warlock. I type something into the search filter, and periodically it just disappears. It still occurs with WeakAuras as the only enabled addon.

I traced it down to the `SPELLS_CHANGED` event periodically firing for my warlock (not sure why), This causes `WeakAuras.ScanForLoads` to be called, then `WeakAuras.afterScanForLoads`, then `WeakAuras.SortDisplayButtons()` which resets the filter to empty.

I'm confused about the logic at the beginning of `WeakAuras.SortDisplayButtons`:

    local recenter = false;
    filter = filter or (overrideReset and previousFilter or "");
    if(frame.filterInput:GetText() ~= filter) then
      frame.filterInput:SetText(filter);
    end
    if(previousFilter and previousFilter ~= "" and (filter == "" or not filter)) then
      recenter = true;
    end
    previousFilter = filter;
    filter = filter:lower();

What's the purpose of that? Would there be issues if it simply said,

    local recenter = true;
    filter = frame.filterInput:GetText():lower();

**Comment by InfusOnWoW** [comment]
So no one is around that wrote that code.

Looking at that code it looks to me that scanAfterLoad should call SortDisplayButtons with nil, true.

**Comment by Stanzilla** [comment]
That fixes the issue, any downsides? Haven't found one so far.

**Comment by jcai1** [comment]
I also think this fix is good.

**Comment by InfusOnWoW** [comment]
I have frankly no idea, the options code is pretty arcane. But lets do that.
