### ISSUE TITLE
Slider Default Value - cant be set higher than 100

### ISSUE THREAD

**Issue by wolfpassing** [WeakAuras/WeakAuras2#1662]
Hi !

I have a slider from 60 to 900 and wanted a default value of 300. But the default value slider is 0 to 100 only. I was expecting for the default the same maximum value as for the slider.

This leads me to another question, why there is a slider for the default and not just a edit box for the value?

Regards

**Comment by emptyrivers** [comment]
I presume you’re talking about custom options? Please provide an aura which demonstrates the issue, or more precise steps to reproduce. 

To answer your second question, if you pick a custom option’s type as a slider, then the default selector will be a slider. If you pick a dropdown menu, then the default selector will be a dropdown menu. The default selector is intended to double as a preview of what the custom option will look like in User Mode.

**Comment by wolfpassing** [comment]
{
    ["glow"] = false,
    ["color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["customText"] = "function ()\\nreturn aura_env.config[\\\"O_Slider\\\"]\\nend",
    ["yOffset"] = 0,
    ["anchorPoint"] = "CENTER",
    ["cooldownSwipe"] = true,
    ["cooldownEdge"] = false,
    ["icon"] = true,
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["names"] = {
                },
                ["type"] = "aura2",
                ["spellIds"] = {
                },
                ["subeventSuffix"] = "_CAST_START",
                ["unit"] = "player",
                ["subeventPrefix"] = "SPELL",
                ["event"] = "Health",
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["internalVersion"] = 23,
    ["glowXOffset"] = 0,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["main"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["finish"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
    },
    ["desaturate"] = false,
    ["glowColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["subRegions"] = {
        [1] = {
            ["text_shadowXOffset"] = 0,
            ["type"] = "subtext",
            ["text_text"] = "%c",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_shadowYOffset"] = 0,
            ["text_selfPoint"] = "AUTO",
            ["text_fontType"] = "OUTLINE",
            ["text_anchorPoint"] = "INNER_BOTTOMRIGHT",
            ["anchorYOffset"] = 0,
            ["rotateText"] = "NONE",
            ["text_fontSize"] = 12,
            ["anchorXOffset"] = 0,
            ["text_visible"] = true,
        },
    },
    ["height"] = 64,
    ["load"] = {
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["class"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["glowFrequency"] = 0.25,
    ["displayIcon"] = 133570,
    ["glowType"] = "buttonOverlay",
    ["glowThickness"] = 1,
    ["frameStrata"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["keepAspectRatio"] = false,
    ["regionType"] = "icon",
    ["config"] = {
        ["O_Slider"] = 100,
    },
    ["glowLines"] = 8,
    ["xOffset"] = 0,
    ["useglowColor"] = false,
    ["glowLength"] = 10,
    ["authorOptions"] = {
        [1] = {
            ["type"] = "range",
            ["useDesc"] = true,
            ["max"] = 900,
            ["step"] = 30,
            ["width"] = 1,
            ["min"] = 60,
            ["name"] = "Slider from 60 to 900",
            ["desc"] = "Default Value should be 300 ... but cant go higher than 100",
            ["key"] = "O_Slider",
            ["default"] = 100,
        },
    },
    ["cooldownTextDisabled"] = false,
    ["auto"] = false,
    ["glowScale"] = 1,
    ["id"] = "Bug1662",
    ["selfPoint"] = "CENTER",
    ["alpha"] = 1,
    ["glowYOffset"] = 0,
    ["zoom"] = 0,
    ["uid"] = "dJ09GYY8Odt",
    ["inverse"] = false,
    ["actions"] = {
        ["start"] = {
        },
        ["init"] = {
        },
        ["finish"] = {
        },
    },
    ["conditions"] = {
    },
    ["width"] = 64,
    ["glowBorder"] = false,
}
