### ISSUE TITLE
Swing timer

### ISSUE THREAD

**Issue by WorthyPenguin** [WeakAuras/WeakAuras2#1666]
Hello. I am playing **WoW Classic,** and I have a question about the **swing timer** for my main hand weapon. After making a bar that should show me my swings, I noticed **this bar is only visible when I'm actually "swinging" my weapon.** Is there a way to **make it visible all the time?** Like, even if I'm currently out of combat and just sitting, I would like this bar to be visible and show me "0" number and so on. In the **"Trigger"** menu I selected **"Status"** and then **"Swing Timer"** of **"Main Hand".** I hope I made myself clear enough. :) Thank you very much for this extremely useful addon!

**Comment by InfusOnWoW** [comment]
This is a bug tracker, not a help forum. If you need help, join our discord.

For your specific case, you need to add a second trigger, Status/Conditions/Always Active and choose the trigger combination "Any".
