### ISSUE TITLE
Wiki > Examples images are broken

### ISSUE THREAD

**Issue by Deveritas** [WeakAuras/WeakAuras2#167]
What steps will reproduce the problem?
Navigate to the [Examples](https://github.com/WeakAuras/WeakAuras2/wiki/Examples) wiki page.

What is the expected output? What do you see instead?
I expected to see images for all of the examples given. Instead, all images have broken links.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Technically, no.

What version of WeakAuras are you using?
Google Chrome

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
`Failed to load resource: the server responded with a status of 404 (Not Found)`

Please provide any additional information below.
Trying to navigate to the [`static.wowace.com` image](http://static.wowace.com/content/images/30/271/Group_Consumables.png) page links me to the main [Curseforge](//www.curseforge.com) website.

**Comment by Stanzilla** [comment]
Uh indeed, that must have broken with the new CurseForge release...investigating with them where they images are, thanks for the report!

**Comment by Notter** [comment]
it's still broken, been almost 4 months, but no rush, heh

**Comment by Stanzilla** [comment]
The problem is that the Curse IT guys can't find the images anymore
