### ISSUE TITLE
hemorrhage stopping kidney shot stun timer - classic

### ISSUE THREAD

**Issue by sapandtap2** [WeakAuras/WeakAuras2#1672]
I use a progress bar to keep track of my stuns. If i cast hemorrhage during kidney shot the progress bar and timer disappear for kidney shot. this does not happen with cheap shot

aura, target, debuff, kidney shot. see image

Tried clicking the different options and it didnt change. Tried using exact spell id 408, didnt change. Same problem if using these settings with progress texture, icon, and text.

![image](https://user-images.githubusercontent.com/54646476/64478241-9b645980-d173-11e9-9f09-634dec289de4.png)

**Comment by mrbuds** [comment]
You need to make a new aura per buff/debuff you want to track, if you type multiple spells in a aura trigger (without the auto-clone option (which works with dynamic groups)) it will match only one of them.
If you need further help please come on WeakAuras's Discord.
