### ISSUE TITLE
Bug with cooldown count with icon aura

### ISSUE THREAD

**Issue by Merlinou** [WeakAuras/WeakAuras2#1675]
**Describe the bug**
If i use an icon to track the cooldown of a spell, and use the text 1 to display the time remain before the spelle is ready, the time bug, and don't decrease seconde after seconde. It just display a number and don't evoluate. I use %p in my aura.

If i edit the text 1 of the aura, close WA, and try again, it work ! But if i reload ui, or disconnect / reconnect, the bug is back.

**Do you have an error log of what happened?**
No error

**To Reproduce**
1. Create an Aura with icon style.
2. Progress spell recharge.
3. Add text 1, with %p for progress.
4. Close WA options. Try your aura. It will problably work. Reload ui, or disconnect/reconnect, and try again.
5. It should be bug.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, i have try with all other addons disabled.

**Which version of WeakAuras are you using?**
Try with the last release (2.14.6), and with the last alpha (2.14.6-23-gbf80ec2

**Was it working in a previous version? If yes, which was the last good one?**
I try with all version bewteen 2.14.6 and 2.14.0, bug. I back to 2.13.4 to have the fonctionality back.

**Additional context**
I think the bug appear with the new system for text customisation.

An exemple of bug : 
`!nwv3YPUnq4NMot7fjJXhYp3cuNEygogkYPZPNlerylBuJqIkjdHCrE27URSbsox0mdJrE)Fx9TFMpGxWzkE(WBgm42bCMNZsVEWWRV9Q0VCvZ667tKLPC2woRc)bg3OTh4R5mrByJ1nFxqznEqrGZooVU2ld88eqTPeuVWQmGIjz5fzl5SsRvxzpyyhu7K8XNfKv1iXGQkTguERxI5zIvBDKCtq6mc9FjDEiF880HC2Zs5Ur(DYYWsbufurzuBXZgSs9bHlGhchHSXmwd8SQ1rgSkk0lHmw5XQFRqz(8wxRmk)MpT9GhvsViG6Po9C7vWZhq)sPNFHEoeFco5BxVu20nIZPBRG8LWk)gbm3((fd8Um2Ug13zv84VSR71Y))8r2vBXlThCQxF7P)Svub1S4TNkEFUVS4tOGLqbl5dblA9FFzLsIL66o0XOhlMFrMzQxLqas7eTx5vR1eAHE)DaRP55zlxnEErX8VTC6F81IEG3pLV)P1hu1hpJfD2aCvuqtO855z9E(9p6jwtf0WD(JfZMcwsxNBKQMnGz3cirTvq7giye)FBRoOODcWWsTW7)jPESl)GWqew8Gt(VTst5rOgUo9MOWyfSUneSM57LoT4yNInQYNnsifWqNfSL773rUpjnbAchHFI(t7xKBx2M47ZuqmaFGq4unnqmod4IcWJ94BodYvJ0iDQs2g7H5Gep9)KUnAckk3lnHfozT6foJTiB2mCnyDBDDSC(A2Sfp84StGx4gPfyGAnKJehJLidw9(CHmegfyWoymavgRZ((K)2tlC2ghmuE7PFLTtQ1)wmmI1ERB93SveEYjfAsBUylK(LwVhdgAO)K4X01QwpTQJLRVVyqBG91QjJyfRyfJww0zk5x(D3D3nW40aV05jg4Gtu(Chf3kQjgtQmNNYeqqugu7LfrHubNF1GKEiYmPPjSbUFsoZHIq5Fx5fWYsfYWax11QMUA(82wp(pI2FWbLx8YGnzzwwoN9Q1UnsHJt)XXeYkfAjHWuWhcYLhagq0vaCaKdKcHE3M4PdQkS4WnJpbLtlgXMP7hFF6p0)4zgY2Jy4t0KxUlJJLiz4j69a6GQ70jA54QhW(QU4duV0hP0B6G9JTUkj(jgq7EOGgMI1e))o`

**Comment by InfusOnWoW** [comment]
I can't reproduce that, the aura works correctly for me regardless of login/logout or reloaduis.

**Comment by InfusOnWoW** [comment]
Can you upload your whole settings? Maybe it has something to do with your other auras.

**Comment by mrbuds** [comment]
i can't reproduce either

**Comment by Merlinou** [comment]
I found the problem... i use an other aura that add 1px border to all icon auras... This aura create this bug... I'm sorry for making you waste time :/ And one more time, thx for your great work ! 

If you are interested, the aura is : https://wago.io/IconSkins/8 i update it to the v1.0.12-20 version, and now it work.

**Comment by InfusOnWoW** [comment]
Okay, that's good to know, though nothing we can do about it.
