### ISSUE TITLE
have error massage in-game

### ISSUE THREAD

**Issue by AfxousaAjagara** [WeakAuras/WeakAuras2#1677]
**What steps will reproduce the problem?**

copy-paste this code (https://wago.io/9EBTx7-J0)  and clicked mimized weakaura button twice.

**What is the expected output? What do you see instead?**

expecting option screen but does not.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

up-to-date classic version of weakauras.

**Was it working in a previous version? If yes, which was the last good one?**

doesn't try it.

**Do you have an error log of what happened?** 
 
here is my error massage

Date: 2019-09-09 12:54:38
ID: 2
Error occured in: Global
Count: 1
Message: ...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua line 317:
   attempt to compare nil with number
Debug:
   ...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:317:
      ...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:313
Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
frame = WeakAurasOptions {
 buttonsContainer = <table> {
 }
 texturePicker = <table> {
 }
 PickDisplay = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:836
 CenterOnPicked = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:907
 window = "default"
 FillOptions = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:652
 pickedDisplay = "Warrior"
 codereview = <table> {
 }
 loadedButton = <table> {
 }
 PickDisplayMultiple = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:923
 0 = <userdata>
 filterInput = WeakAurasFilterInput {
 }
 container = <table> {
 }
 buttonsScroll = <table> {
 }
 ClearPick = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:662
 PickDisplayBatch = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:948
 importexport = <table> {
 }
 iconPicker = <table> {
 }
 mover = <unnamed> {
 }
 loadProgress = <unnamed> {
 }
 texteditor = <table> {
 }
 RefillOptions = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:978
 ClearPicks = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:678
 newButton = <table> {
 }
 RefreshPick = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:968
 PickOption = <function> defined @Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:711
 unloadedButton = <table> {
 }
 filterInputClear = <unnamed> {
 }
 moversizer = <unnamed> {
 }
}
db = <table> {
 dynamicIconCache = <table> {
 }
 login_squelch_time = 10
 minimap = <table> {
 }
 history = <table> {
 }
 clearOldHistory = 30
 registered = <table> {
 }
 displays = <table> {
 }
 frame = <table> {
 }
 editor_theme = "Monokai"
}
WeakAuras = <table> {
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:296
 ScheduleCooldownScan = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:3035
 CheckItemSlotCooldowns = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2200
 OpenIconPicker = <function> defined @Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:4701
 IsEnvironmentInitialized = <function> defined @Interface\AddOns\WeakAuras\AuraEnvironment.lua:137
 form_types = <table> {
 }
 ConfirmDelete = <function> defined @Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1352
 SafeToNumber = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:6516
 tutorials = <table> {
 }
 pet_spec_types = <table> {
 }
 LayoutDisplayButtons = <function> defined @Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:1564
 author_option_classes = <table> {
 }
 animations = <table> {
 }
 TenchInit = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2898
 regionTypes = <table> {
 }
 absorb_modes = <table> {
 }
 bufftrigger_2_combine_types = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 OpenOptions = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:71
 autoeventend_types = <table> {
 }
 talent_types = <table> {
 }
 EJIcons = <table> {
 }
 SetModel = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:6488
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 GetAuraTooltipInfo = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:5075
 FinishLoadUnload = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2193
 GetHSVTransition = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:272
 ToggleMinimap = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:128
 ConstructOptions = <function> defined @Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:205
 FrameTick = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:528
 ResetCollapsed = <function> defined @Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:4875
 
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.9
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicAuraDurations, v
  ClassicCastbars, vv1.0.4
  ClassicCastbarsOptions, v
  ClassicCodex, v1.2.1
  ClassicSpellActivations, v
  ClassicThreatMeter, v1.06
  DBMCore, v1.13.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.2
  GTFO, v4.49.2
  Immersion, v1.2.0
  Informant, v8.2.6374 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.28
  LeatrixPlus, v1.13.27
  OmniCC, v8.2.4
  Quester, v1.13.2.1
  Questie, v4.0.18 BETA
  RealMobHealth, v2.6
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.2.2
  WeakAuras, v2.14.6
  WeakAurasOptions, v2.14.6
  WeaponSwingTimer, v4.1.0
  BlizRuntimeLib_koKR v1.13.2.11302 <none>
  (ck=59a)

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**

``` HERE ```
!S35EZjQsAd8VltvVvLPQDYWfb0tvZwvmXmj5KO5iM5YP2YeurLjkyam3(d)S)2xaHUPbBumrnUZEsIyd000D)875s)0TfB3QT(4269AR71wx6qXshQ2w)jJboNFsB9k1Q26zTVCHaSaGc(sJ(99m9Bx)lIkGJ511yKz76IT1F001ZYXg83YT1TaxSFA46A542wVJr37756m5yNrGp2cwA4)xc9tz0pl1UUWHkT9bNPTVPRTXOFeE5KaxUooU9mDB3PTUVt3OBKOSGuB9PWB2)Amw)Ixe)Hy5HT1nS7o0X9AhW1QT(X1Q3QwtqXCh1wFOV)eV)6RFf(0DOLZxN)09vX53MWhWsGNoZr9dUmvB0QvJRUS2PTclNU1RMWNIGpwn4Peu0rwV(QHBVz31YXzKVf4q9DngBQ77A4BGASWNsTEdmBRlo7URTE2eu7CnhaEWA9YeWrh46mfCIDDS7z5doQhOHZp8ep3gvdbxiJP(Gh1gtIvKNdFaeouqqqwqrutrRSOKc85zmO1dClpu4qrqnFKJb6LApR(9T6oDK)lO(cG)WcDTaxnp4tj9b7B0fEdtC8UJm8G1cWzzpa0Vq)Nh1S55nAsvmFqFgqBk9z7A0n5TYBIz3ehCQN5T47fOnDk4(46mk5Po5XjPCNa1ouZBlMvmj6J7h2L6u4Rr87h9JBwRwD493AWaqpsC)AWjo1o4q43grFa8nwWA1iJxGVd6z2zA)(4l2z1U86tV5sWRxWH0h68udBWto63hbAPF0e1omA059cEhB(i8Xs)mtJr(Go8Et7GoY1UM9TEgu5UU2LxgDyDWvfE4Bp(i9w3Q36OMGAJp6oBm11OTUn4XYl2dl6E2cxZVYPNjC0oCcalV)m1oOczmAuuhY4dTfqdTfqdTfqdTfXTGwJnM3RXWc9BCLW2Xg8ZEGQc87VfFqptyFFpuFaFdxF(lEFlBlVHCx(Ghy84hqxdlFCBC4Dn(ve3l3XUV1GWp9i45RKeCOiUSDN3ti2uLckhwPsLYIQLRusrMAYsVjgU33Y8z)PUGk25WjabdWm)FhB45d6Pw1W9)DZ5Fj6tFrhEcOrbh17pt98n7z27kqdANn7w5yZMgoPC40zN66aoCvUMLg0m09(xoj4gHeke22vB0J3C(S7QoYW((KZlxhvdjB1mEgEbIMYm4Tr2IQeXtmbkxthFuTanir)OBA1iqE0fDE((NotFW4NVo50UGXLnrt1hnRr0OXogU3c(pWTOoAIi4d3TpA5z1bmfxWd7T9Hnx6N6A96S7(NPg9GcwaIBAf7RXING3oxyL0e2bd0g0OETGcf71bUIJNJ7xXAlqLZhDIZUlSa)MUaEdn658ehtbGknHW5ZRxVwZBBE(3plSQ3DXT8XUP)oAigXXN)qig20cAZXpiZBGWt9I6u4dVfFmARXemVRn1L2GAQ))8wln1h3O(THZX9U2wR0EoVkrDiLhLGs6HBKN)5W3tvJDBdyYdlc(5hc7hDmNOABWrmjjEJHwrjyivEl00UNzAnyiCqRqELDpm4mfvGWXcLu00uLv1ieQJVh4M6FJ6p8KvpaMvDPsLGIXRuUKwjrOiFczaOscN7huC7bGUTwJHTpOYufWv2lqiXjNePsuOKVoS1skL3sS1rcC(qQw7EexHdLf1ulPjOuUSKma9aDbpussRKIqLYcYvKevXx)db0jQrhpqPmvb0)tsUCjXYQO(igK4EhQHVmk4tp4oOkg)(gChkjlkRjPuQIGyf1yD9H9BpDKXaWGXg306YZHdMngnziwzjg68HAuHTAXvzkq6jsPihyFvgkhrRiMvxmcXRooJrVaPv4cwaEg9I7xA1RNjaDVETFa7eJo2jMEgi6KoWxCWhe0Fw0QEbvjcPRu11QAybxrytxkAKv9nqBmhxlW3Gh1PFwJMN)VnQ36OlZL2yHKQGPJWvFJoEoUDqdsJMNdCtM6LIYAKQKn0WUxaYn4UgOGgQNO(atBtxRUPOyhBD3IujluzpYPvG1yKcLvxGEEKADcpnunTkQLeJyYRkRjBLYZdkvlA8M)GlYXrJ9wkvAr1Vrpz8IhYQavjALYHMT2Vqjf4xrAg8tSOa4jHMAWZcoPEabBp8yDawcyiEyRBm1aLurQbQPvrQIAfwQbg)(LQmW9k5fPKhBB9XqhVeV9yjenUIGmfTq8gE(K4WUzWrcituMRPTtzooENcpTPozohoSw(O5qRUyI7mMsh83vHc4QY7K7WsmX0VJHVFaop7P6ZqAxQYh8tQandb7j4cJd0Huj)7n614px9qFXH)c8TGohoJXkp0hnY3X(Gpp7Iz3H)Nv)z3bFPFRP9JhI7jm7o)HM2rfj8FJC6AmA2DUgdmND33MD3nG5BU25jt3d(eEIZp9FMDxn7PJpeDuyhQdBck8NtEPOUJhc7Zl)x6M(Wk6bUKNeGOC2fOFW(FrWUscPdrXeZvjn02MOhYQgPX1MCkXCG1MQfvsfTnI6urmX1Kd2vr2vew4O8ymjSj44LyCoYziUklescEv5iE1L1MHj8NqsfrIaVZIF1b8xGE3ZjTWVrkjRivPua6VASw3qF8iPKMfxdgsc(8Ih6foKdnEJUSeJHTD8bLdpqAbdGdkZ3GLh0p5Vo21emn)PqBoaiIShCGT1iWi5p1a8I5YJ(9Nym(D(n6BHxU0kcCq9fGhyR(VC2bFcl3kJRySI)Jd(0vNFYjxwBbfhjsC(L()e8ubFa44Uba3oGEQgg3dDKvjWtHCGi4A)fXpZSGWwXdWF(V(EWh)m7Ic7uJgJgR8rhdEsjMZdixX52GUpvZu9)COFWWaFRieOB1qOTG88dPkNaNlhoqaruJlBvcSDM6mqG9IRY3oenFPpGRVx4T9wNjMGccnOY)9BXUHiGRQla0Mckp6eJz2Oak84AreCsiHulh)nPcre6oKB)kvu2iV2ZtCn98akfK0iIkfLre7(XZ64v5UvU8ERIV3Q47TkEoTkoVUHmvtHfAI0WrVXmdHQeLPhgmY5PlTSbsUQxMuXxeV5gTbhU30CYrqDz9BcldcooPni664mc0vXgfYnX94lqaKaUbaEy4VJ3LNdfpHNs15XNe8tXhuT0rwqOYyqDXGxuo6kWXOjoS8csx5RuhR)ZNErxt)GO2o4KkNy5za6Z3dRnadlOaRRTgA19EqVjpuNC0rqV36m133XUbwZbkr8P5ii4zRppiZcRkWXCOUMvJRhvA2lJ2O)aQNOMucnEiupctD0DOz37rDidydrb7MHRfSDam(Z(4W6e4OJMAg(YyOH9aZOlZexisN)lHVMckCKItj1LnXbLzDWGxT(XSN7cQYimTB8WFiOolKDDoMzVcoJQZVBrLku9WyfXN0TBWEZHVdb9WXWSH6)gE6v3i8oc8ucmiv11MtrsZ8FrwcB(1UmNM(ll7OXWiqzQruGIf4FFeYY6bDFQdgrbboaA7t7YGeojGPIqWIrQfdSncO8J(8lV(voU(qnZHx(7njvUkUEuK60qQfsIAlTpnwOhmcFUd6dfC1QYu5PW5caIYDDgarIND3bONOpV8U0WBE7dQpjOR495ZFgynQGt5DQR5dtnT7(sGTyqg1JUzgrdyApi0s50E1OedCcs7ItYtSv6hJ9yfZJ2GEWqA2XbCEwUE5aIq(VhQ1rr)AlV)zLHisYKghfGdYbw2)MI)yoibnFaZGgOkxax7bkwpafeQVKGOioUXEQImOkK1kaQIyrQZgmmbXuyRijHKC5YI7jjiijOPgcP6tt9VqZW8beKGUPQGOiOLNvKiemeFUwmqbtj5mNSF9asmFQmA7oelycwm(tUjjqHn6qlZr9ay4JmgVhCyVLiwUG8zDgOMj5hu0YKVjJ1txsnE2KHhihBUY0dvKK2tpqqpWq36uTBms5sDLF0RFz1PA)rgo(xLgLqegPLQQLKfa)it3DSRqvGAwU39IZF4eNQNQDmxsQIqnu2qinw7(aHrxnMuhRl3EWdVbdClsW4LIWOPjme1ZISagzBF7B0IRHIqHXbtKGBW4IUdp2bmd9YiToqgq6OyzQi)M2INiuwyLyXpBLWjgrtuFVn81DDrnr4A)nnTZxDj3ZLmGVHDYj6qM64Nt51jLe7hKle6qjg(OMxHedhkuf(CJ6O6h0nZ0JPuqK0tWKidm9jK1chQRPjH8n(t2nSh9s8LibLmp61BF8RETNT889WyHUgXREbxEQfHp4HmuICxNXDaYxUcx9Xx6lDEYeA6HOOysIhzUGofwG(4yb84Wn77WxP32fn6RZAw7Dkvtbdf1YxWeSRiDLHuJ8iE9T1zaZJLw6akh0Y19EVyHhkoTMGcXmymIsvEy0Isvcb4)95zxK(vMvqHgpcn78(k(pPuhe4u9ZKoZ8Z1Th293fIO)SSVtod0Hu9tre9WIIWb4t4zgJ9qbY8YGaWqWFeyWYJae5jLTqb)0sVNlOxsvSKi)c6L3Ke0VGqei3RxWqftH)DFhxyaARJ(DSgaPWNPy2DHsF4W1aPpySJ5xpfCb(6rOuxZYOmB6kTNLWuCy0X9Zoz9Fr2jiWkgAWyso8zfE8z393OxXlVs7PyPaKn6YTzwKuuvYNvwcX74XklXMHkMjwOPVIkfPzv0K1Ksy1f2TAKWJzszM(BrIE3e8IzB8M4VmiE7KAF8CImMUzAYfoitLxd5cPJjKY5JkCRpet52fo7ewvjU7jQoYPBAR72mIqMLeLIgKH0kiPz(egi05XRnChiPH4lmeAU3)nRh)3SqZQTfeeizhDNWpu9DYdp5pvCexrLTbp4em9vCH3es1tJZkvN5ajIkoF5KmTFKPRCOijxE0G8d2hcZNk1cjFerlctfaw(KyjRCksXywSqChKjcug80bpE5KYgQ)Khln4dnd8hlQOv0iz7gUGcL7JhA5o6jlO7wYx6nBfXLOXq5XxteYjPxtnCyqTfU6AMBk59erVVerKWZ7zIwxmrBzlZMytwrBtJyPRAcijQf6pHW9emnXFsullKjqum(Nu4b2OWIiAvy(ciz(wieCAbzTTeTPuH4d3McnHHvJ)ALfjwHHoXYnwXnAc2Xlpi1YRtzfD9)GmjPq7pMbfCEwDrlnOuqI0i9e5WoqwgaLqhI51YvlxdiSKPAGWehL)IHtjdj1v2oDtTb3Nz3DK7yikeh83leG49AnBLpQDcfRYD8rX3Aa)n15O0XGXCoog8fBQWCP6J0YsckBPUiTOJDzv5sYRpNQ1AyWechpYycbGvgyy01okIpchsr6mTmJo5mDNwMHCf5SA(eosld)39(eo0RbJPrHrYH504obbNYZFXBmnoKaZKqSYzv)3lUqCI75AicrX9wvlvYWDNLDEbMnBK8SAa4sCoP7V2NnB2sS4gAo0nBdVTfUuY2Ww(5IYBGj1gjvbnHYRrpr(eykEuQ8hNWv8sgOCG(SUW(SDyeYrjnTwA56gPfGnKLFjjiuYPtj3exFz49LLen8lkv3ikLpwJ0JBQTlKJeCy5WlE7oiiWonNyA4pC2D)eErzltpDZCuqoXdXWu7Mxklm9H)533FFwltDoIACETiY(GA6nJKG0(2BrrY0ggpHCrWtWJHI3K5liMXADqwilvEpzrIqek1LvCsv48rOdFmDZf3bo9(uFZhNuFZXo2DN65H2PpQcFLVN0yzCy0wObj2KZTnL2qYTnRBGHKJ(YGAybGc0XTcH0(0x3BsLfQKj2abSYoa1qUZ3nIsnvvF9K7fu)Be)avs4vsaT10gSZ0kUFj5ZrgVPIYBhGbhRiFwBhu7eRFF51pMuHBdMfUe(ZXkpJceAoHekXkJ2XeNDhyoVP(fMTyEtdtfonEH8614f7875Xf2cTsvP06lyIXxDIW4L(7OdTdYHa(TZABeJkYtYkwtOcUKCSIS2vIRKLjdeOQQj)gMbckMexuMRuDe90LYVov(7VykEZae9KYYtp9HkCs(II2HWTqvvrbzfGYUBYo2PyXm4n2s(J94l8U6eZdux9aMDFSLSRAGM8hujYBp2WzvyQK2PwOwksLuxF2P5CBFRXw9m8XXWawJHvmxeJQX7tfX0HkcZM6fgSiQmPk0uukRurUC2(3zxjYrWB1(pBEXFE6XBQlCDM7UbvGWfsLkjwsqv69WAmVv21ahjjJDCngz9A8(uVrjJygqRj5Z4jQssGsWbN0cHksFXWVHKPIZuOmHUcBfsMjskXIQcBPRdNcFzwdBkwBRdhMd)Zin3XQ8(jRV7aj8oowk3REUV7nW2j43hBz2oH0i3l267ynqG0oAlG2zx2gk8hflLrgwstRIuf1YL3OC40UPlKqXtcYF1S9qi87vhCWzx(NwDL8NSYOvSD)ro3ChwhbwtXGv9fcdIyzdtT9g(V3wWznzpL1qgMEJ0VuPH7LgAg6kIFX35TDTrdJcW1xGVemnXQUVsdJuX9MqjFR03unHDk7vKILxbJRSdhXlV3KhXNFn9iLnNYVphk6TR5K3SW9GwMkpIX3PyUObAxLea4Caeos8FPWBe4PfwKhBQ8gOThGnBFlXFMcKPnT2thTq6OQlAPffPzZMlwuSzFtnGA4DRUuqvu79l9iVjYgTC5MEKARogQpCKT00x16IqIQqJePKng0oNzxYvYfwBhj4vG9eOsQtz6Yi6Cb8YIiH2dPE4IgdkzB589HmIkfo8FuQbd7QWzS3)r7ZJBBaB1vfzgXxmdN5SgYi(Vb7Tv48ixH6DK4lrP4ycl3EB1BAA4lE1VOYdF0WseVx43NFu5ZVmtlFKpv(eU779NvBvwnwHkVMHjPKeyAsQYIQLRucUt)Ul7bSCLUIvHTlLueullRuP0ochwbgeXE)(VVU39sxw6Zw7dI4TOGiEfIxx4KvW5DrTi7wrOBAWGzaYUjK33elxQsL1NvvQc7b4EpuyztJIWRtOQ7UKFNYhXn7xeCtMMBG9Ljh6st1l3UO2DfqRDu6EulkaLLe3dSS07nvlldZB8gvvEdkzaGH74TODPk597svlcjPa3qO2HPuY)6ikd(L3W9cQ1lLs48bR7nckvn1DP9bQpUBpMCThpDD)NR114hch5FeQXu6dmhYQ4dR8KXAwZ2oPWI1NQJCC65AKs46wWoXIfmwkR6UCzCesbPRPnFOTe8JmTisCI1TcFDTXqFKr(Mlnm9nzqJyd7tZqi5ER4wTCrgRj51GifgSrbVTvxXRXt)(x6nlv)ao32QLOsoTWucZoDCLGANgoU2GJACWRth)35mrY9wNX7lMLVCXM9Ax0kIAffChxczU2dbzWPSYzgFyVfiPWeNNGgF7lZUlmooZV4BwHb6cKFJ6PrhaOR3ipf38ZxIM9Tk2rlMnzAL4BY0k5AtMU48mYY4(JLuQF6satkQ3h8Q13AckzXZTCESKmM5)vqVKg2JEHbnW8rtPk1pEuhCQRJ)q0YIEUjW5nkdYkSrseDdamxfnjgw2GEzr)D4BVB7IIsSomJ1Ig2hfi3odeeytm7tkgLJMC5seqqOzKJQPGhk8lRJrDf7qetgWWugi2(kCfeFxUe0U75Nl(fB8gzeoiEAA2FKjEi6BtIYLNqZOuscMpaBBpRAgXncKP6sbYex2mV7YXPop2YTF9WsUmy8)8jk(mlCve)N10swhn((VxBQZAXodreEP5JdA(dgSlrrFbCqqgmkGbyWPDpVlUhVKKKmfEIF6qAlWbbBgcZ5yVNH3WsDzLKh)AWgKiR1mYChRKPy(IG(VqcRvE0nNso5Q7yDsHs51F6lkSwrtuCleY1WhAsS)73OBacGsuWvz0NqvPKgTp67QZmydWxPiBjCDM4oCh7R0g1pjYxsUUXwEETcEkIoF5uO8sud)551)EQ2zX3ASzVeogco62zQBxZBcQ2ZRc6N04KVxlg8gCDun7UlDgW0jqZBpU6CD9ANe2qhC2XUhH1S8fiOlHIUS0bfsGOKpBOSRSeLxf3BKp(dAzS8cFWqQkt7iSwmtsci0mDu)ssFWfh0S7K4LlHndEI0hxarcVwrHtcLisXe0jrzs)9GjmblwvkLTdWe2kUUUjtiWH2dMu4GjSY7)b1qMykeGmXihwlKjz2ljenjTwWvhsHX(dBDLR)XzDFOJWt(m0WfcKOMltISRWJKRSD)7N9pElypsFdMkLSFsXJFCIzFtBpqp8pZ)YhMKAUqe7eIQqdRUsOkm3JE2ziwwFo)yDcPqY3MPNr4vn5sPi)Hqc1gIYXPO6EksGssGXYzfnSBAA07fQ2lID5hTsj2(DI3CKgHgtVjrGRq51OMWlZaZmRMC7vOeX(HRju6gOxx42EixyHmIbwIajDbGFjs4UHqUCUcty5TQvN1nJTXr0dvPpC0SRUJT4DTHwA4V6j(WpQECNJsbStBVLMYmh8UwX6k8OZHJ(ffQNXIqYqweIbV8AzZvmsQCCWyE9mwc3GTcPpgUG728sDA7X8AV0lYM8y5Hft(fJeJccC7WYdRc3xgRnOmwGlB0OEldQqc838Y9TvzDtPWOnCp33seqtuM9ab59C1H2tE4iNhESt6EuSC(484lOM()BVRUMtBCOO)A2zAFzhJXgmZSZodKssiLc0yyztFifsawiKb2wt2KMh43(kjBajzjzjJSXaE6tnXb)bY6CU375CVzFEE7ROMSnp2gSu6nTFSuNFY4RBAg5em7ILuTrVCyyxFL5YMw)6hU4zqlG(ws2TzokfNnbb0dXip4iuy2A1owQocesCjzZqtWcLOmpUxH4ofggwfdtrZwuzzyJPNC(sNwKLVOjDrPJBcvxxUIavxti6DjKQUiDyhhklPOGSj6jyJ2U6GYgmePIbU1hDVk2(SO6JAsnuztMl8TaUIzMQ5qpq4TWOvgHwgvdSepC(80EAO2WGq2zWjF7FZLQ9U8uTLfIenIMW5FKmzucTFv2eGpgPEsFnU)WSlGd94DSlkTp5Es6E6F8aZPWTXXwAaGvbX2VEq3PGTF)8m)nT9NiiT3f0TiWrU4gyqRyiZIBflxdOnaE7Nfqk6Ac1zTPHqTCkzgGTJdgtZbaBlIOWpvCIrcw1nd8wHpZLiygLAthjY46rrbDzXwJ7mY6oN(Zr5tYqTSbC07rB5l3Jkb8FyCJTwqoJ7q2Iz8H6UzZktlDdFNtgyWkhPp8TK6lG9uccweCd6pCq1YzW5CewjqylwqBiSXZPZAbULievHbzfHonOgdYyT(gg41mf1r0i)CnBnnykyhhlhgXthg4wGJKLbshlHaIqS5wUIegkpkjNt8Tp)AQq(quX2aZM1nSfYdLB1Xw2iJKQsOcwiPWv6z52WTs)o22JrewkKltfvtbqMVTYKwezi4SKi6rjAwmYKsamcn8AYmsx3Iy3qApkRAHaD6VL4foRSSf5lLMjrjz5kKUqk8RFbIg9BJF8LvKj1n7vedmkoQupJGBoAOAn2Hz411BnnkvYquboiQJab9J4vGds(duK7OiUiQLYSL7kbRJJ4QyGyO8vRElQ3S(OfZUiC(e2g1kK7I55j3fvmpvgxIThuxFlbNpEP3slsSLWVz8m5nfHf2WauE4s5wNhLyBTlA7eU(gIvWq2LfWzshPjqY1zMzLyk3E0JJ3TjGYde9yHKt1J77CR5LqseomHpIXei1ta44JEXQPO6bH9K4peW3Z)GPMBGuJIq4nm(hT)UbuNK)CZpdLBk(CCwjH8v2urR4S4I8k110GXkmPPRW36UWTPl61XTWDp15HVvGTfHks3qFnH9B)Y22o2vkw2oxhPYmaGm)DddJYfnTml4uwHgXpbWQ)lsRaG6F))M5ndgyvTG))KLWlTl)5S3xp4RVmCee7C9GUDX(1UqaSwWpuq8jGVSGKdU3Tv7w1doiS7XQ962EdhhC2uOJBf6p8382Ca3rFaEthoIK9JHFpH3VjWVJAd6Ojys1OvR63(9AT72T9xUTXvxV5gqcEsyNAoxrBVt2TD4lp4F3S9PK)I12962Sb4bZQukvy564nkD8(EZRFQIZK2xm8r9PJ3thbVYwskjuH8oKcEvlvMdxvk6wXlctMernPcR8fx)6IvlczWqNci3PZg)8O1dQ98YhNh8vm7IQfDDa1DAzywBTque1VYsjEMWxyGq(nwQLFMCkn(yOggqonwooMofm1aLggy0NJmDctcriZggx5my2iZK7yFy6S(M13KZ2rFSD8E4YcxmzXh)rHQN9SDYyAtc(KtxAt6aZ9rivfUccsGSEICMlHEHTKrzdhSkITHaebLMxbawOAObVLNp2tFc3ne7jwNQq8Vsiwk0NBXmvy0wGZ9btkWsj9Gg1MTy(04HRMUEqFWNDUTyYTftAiAx9bmMa2IP6TFrgBXWemqiojgYibgeFysk1xkj6OKdIN4eJonIi2EhjkwyCCYYF9ppn36kRAVnTics88SX0MdjgdiXlwUaCcHFqO0c9kcx8tO9cYrgZrgtWEvM1HgzedKIjQOaWkSuLZdPsIPUhtCvkeofmSbrP9PHVOFp)(vhueRMU)RR3BD(qRgtqiwuDCZiAMbNCwVurOQ8sLNxQ80n5X7aprV(E1Kp79E1p62)V92)j7hFjXg)jsm5woXAEeF7yaGZm0B18C)QeebOjsKT4eCsv08dNPwfx6CAOySfwBk)Cu1pxIMuHunsI909PeXOlmbajy7KiHZc9w3ke9mXTOtywlNdfj3xIK9AE3VMT8Y3)57c8WqYoi)5nbyseiW0OpEZBUXijqOw4sW1NLC3GLhk6PvjxpLWk3)279jKaZuxtz9dasKawMhw6XQKYWLrg8Xag1y19KfedTIAyOh9H(V)kmlR3cdsCKyc0dCqM9d7fU0UYhE1Z7A7sLFUQocdn6SsRwePpo)zWL7cK)O5gskVX47rGF)oLWypGXJgREAOqiuPARHmMPvSbDLkm0WHnVB1FW3M8scFkJYM(bKsGHc)39)p

**Comment by mrbuds** [comment]
I can't reproduce your issue, can you include your WeakAuras.lua in you savedvariable as a zip ? Also if you have the possibility to make a short video starting from load screen that could help.

**Comment by AfxousaAjagara** [comment]
Here it is. lua and video.
https://drive.google.com/file/d/1Iu5-lWIW3y5QlY6MZQqJOl4NAWuoYMM4/view?usp=sharing
