### ISSUE TITLE
Rebirth cooldown being shown randomly

### ISSUE THREAD

**Issue by daviderickson** [WeakAuras/WeakAuras2#1680]
**Describe the bug**
I have a Rebirth icon that I want to be shown when it is on CD, along with a countdown.  As the druid, when in instances, the icon seems to begin showing up randomly with high cooldown times, when the actual spell is not on CD, and nobody else in the instance even has Rebirth.  IE in the below screenshot, see my WA triggered with an 8:15 cooldown, yet the button on my bar for the spell has zero CD.

**Do you have an error log of what happened?**
No, if there is a way to dump WA state I'm unaware of how to do that.

**To Reproduce**
This seems to happen in every M+ I run, but I don't know the exact triggering condition.  See my WA icon exported below.

**Screenshots**
![image](https://user-images.githubusercontent.com/107007/64575346-2e45f500-d328-11e9-95fd-7b92158d60f9.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but a conflict with ElvUI for this seems odd.

**Which version of WeakAuras are you using?**
2.14.6

**Was it working in a previous version? If yes, which was the last good one?**
Have not seen it work properly yet.

**Additional context**

``` !fxvZUnUnq4NMc0EObYkUl8vBVkDnQxjxrLI2l0MsIsMiYKEjPSJZb)S3ziPIv2EOb5Yciirro)(nFCg6eAbLiOPtU)trZIOedLeF3KP39jk5aLuJpGaTDQZ0s)31CzRDpObi9LSMgd3stH1mz1ELEJsiTuYYK0IKCkPsP6QvNLKZIJC6cyJEJvDOG)S9XJ1mlNs6dFhenPULJ(IvzfkPbDVXY0wyby4gHuy27xdl97cRTArBlxJIN6YPWgo17l5N4s7gnVr8mLq2KSEniXfiKqBB7HS2CK31LYoWPPXrtNnfcmPtlis6Tk8xWBKJDSlGvj9g(2wUKRfvK9QZzsm5E7geJ77YqErjsW6gFOR5SoYREKKZlfAauDM9wKSiewRQdQnKjK(gxMSD5CsXwsX8CinR71meYOKjusi0hC(1DB0Qwn3yUU7NDo(x8oZQzvpHoQMxcgTWHjFjz9MhECn6XE5nG0b0yz5eVWV5xv1aE9RavWvoSCTK19xqzadJ047PKN48JZHKOYMJbhwyn8UMVJMySIQNU85HeiW0wQ6uAFbfFIDVV39Ek(2di582apju4bU1wZEgK2)9i6zOA3xINhKYV8NmHFR()9NtUgfg7pOfVCD3F2ZQHOMDDxXB994GpYzSiNXI(oJ5L(FghPUTVbsZFSilS7jHru25igU)FZDUvPPj5BxKvuK918v)(xkgUt(FmoMa(kD2JfRxLMmAFI4fOKojEq5XyOwbxw4foulnduZIj2hcZp(HW8nfx3bXfqItzAn0t6hlIpqF)WWC803jmdR2ZfT7bbMoJs6umxFz8IL7Rq22H2d6A33zfikedXStXQoMXmskYM8vjKIBIoSrqEdgAJo2g6WQQonCZEwuCuK)s6dA(365YQlqOFx8VfMriKqNU0z()8yqzV1QKzGnGwOHd2dx7bjny5b6azGwXACya0a45rac0O6w)GsS7jEL3Bwrf2XRxaJQoK9nX8dD)rCPeHvXbF3KrdqETh52a1KdAxBgyQsLKJP6bMq((L(1rsVp5T(CFmBPrdD7HjwqFehs4YjGXDm0ZggCvj8i)KBdkrcYNfggqpRru5fL6GFsmoVAH3nKkgsmqJwpAoJN09a6xpmswMNKKch0DCVpiolQXX8iDdmiiD2XHbYiPsjBeTdZHrIbFWLJPYVJR3igjEJLdZldMBHsxZXYoC2jqNPXOA0)9d ```

**Comment by daviderickson** [comment]
I watched it closely on the last run I did, I think the trigger is when I died, then it would start from the top and tick all the way down to zero, then it would actually stack, ie I saw a tiny 2 in the corner of the WA after it immediately reset and started counting down from 10 min again.

**Comment by InfusOnWoW** [comment]
That's how the spell works in a M+ environment. You gain charges of it.
