### ISSUE TITLE
Cant access WA2 using /wa ingame

### ISSUE THREAD

**Issue by drum84** [WeakAuras/WeakAuras2#1681]
I cant access WeakAura's option panel using the /wa chat command ingame, when using the Prat3.0 addon.

WeakAura version: **WeakAuras-2.14.6-30-g0657844-classic.zip**
Prat version: **Prat-3.0-3.7.33-classic.zip**

**The Error Log Page 1/3:**

> Message: Interface\SharedXML\Util.lua:598: bad argument #1 to 'format' (string expected, got nil)
Time: Tue Sep 10 11:33:04 2019
Count: 1
Stack: Interface\SharedXML\Util.lua:598: bad argument #1 to 'format' (string expected, got nil)
[C]: ?
[C]: in function `format'
Interface\SharedXML\Util.lua:598: in function `WrapTextInColorCode'
Interface\AddOns\WeakAuras\Types.lua:197: in main chunk

**The Error Log Page 2/3:**

> Message: Interface\AddOns\WeakAuras\Transmission.lua:231: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue Sep 10 11:33:04 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\Transmission.lua:231: bad argument #1 to 'pairs' (table expected, got nil)
[C]: ?
[C]: in function `pairs'
Interface\AddOns\WeakAuras\Transmission.lua:231: in main chunk

**The Error Log Page 3/3:**

> Message: Interface\AddOns\WeakAuras\WeakAuras.lua:330: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\WeakAuras\WeakAuras.lua:330: in function `validate'
Interface\AddOns\WeakAuras\WeakAuras.lua:4052: in function `PreAdd'
Interface\AddOns\WeakAuras\WeakAuras.lua:4168: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3720: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3699>
Interface\AddOns\WeakAuras\WeakAuras.lua:3712: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3727: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1534: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1520>

> Time: Tue Sep 10 11:33:05 2019
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:330: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\WeakAuras\WeakAuras.lua:330: in function `validate'
Interface\AddOns\WeakAuras\WeakAuras.lua:4052: in function `PreAdd'
Interface\AddOns\WeakAuras\WeakAuras.lua:4168: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:3720: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3699>
Interface\AddOns\WeakAuras\WeakAuras.lua:3712: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:3727: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1534: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1520>
Interface\AddOns\WeakAuras\WeakAuras.lua:1589: in function `Login'
Interface\AddOns\WeakAuras\WeakAuras.lua:1661: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1613>

**Comment by Stanzilla** [comment]
I assume it was this 
![image](https://user-images.githubusercontent.com/75278/64622087-0cf80e00-d3e7-11e9-9b30-77d652e51784.png)

and he fixed that with the latest version.

Can you try with Prat 3.7.34, please?

**Comment by drum84** [comment]
Alright, no error anymore! Working with prat 3.7.34

**Comment by Stanzilla** [comment]
Nice, thank you!
