### ISSUE TITLE
Twitch updating classic version over retail

### ISSUE THREAD

**Issue by Krambor** [WeakAuras/WeakAuras2#1690]
I'm using Twitch to keep my add-ons up-to-date.  The Twitch client seems to think that the classic version of WeakAuras2 is an update to the version (same version number) of the retail version, and overwrites it.  It appears that these two (essentially) separate add-ons are on Twitch as one add-on.  I can install the correct version for retail manually from the "versions" tab in Twitch, after which it shows that an update is available and that the "classic" .zip filename is the latest version, so this makes auto-updates unreliable.  It also makes me wonder if players using both classic and retail WoW on the same machine can install both versions of WA2?!

![2019-09-13_21-10-17](https://user-images.githubusercontent.com/55297656/64891887-ffeb5100-d66a-11e9-868a-2eebcf9c669e.jpg)

**Comment by emptyrivers** [comment]
There is not much we can do to make the twitch app more reliable about updates. WeakAuras does detect when it has been installed in the wrong environment, and will notify the user of that, while also bailing out in order to avoid accidentally damaging your data.

Did you have any issue specific to WeakAuras to report?

**Comment by Krambor** [comment]
The problem isn't with how Twitch does updates, it's with the fact that the classic and retail versions of WA2 have been added to Twitch as if they were a single add-on.  I appreciate that in terms of user functionality they are, in essence, pretty much the same, but they are two add-ons that should be treated separately rather than just as different versions of one on Twitch.  If the two versions were separate on Twitch then Twitch can easily be configured to manage and update them correctly.  It shouldn't be the responsibility of Twitch to determine which flavour of WoW a particular version of a single (from Twitch's perspective) add-on relates to.  And showing an in-game warning and expecting the user to exit the game, go to Twitch, find the proper version, install it, then go back to the game isn't a user-friendly workaround.  Please upload "WeakAuras 2 (retail)" and "WeakAuras 2 (classic)" as distinct add-ons to Twitch.

**Comment by Stanzilla** [comment]
Yeah no, Twitch just had an outage the other day, otherwise it works fine.

**Comment by Krambor** [comment]
TBH I hadn't experienced this problem until I updated my add-ons today, and I do keep them up-to-date, hence not raising the issue before.  I see the two types have been uploaded to Twitch like this for the last several updates, so maybe it was the outage that's knocked something out of whack...  I'll see what happens when the next update is published.
