### ISSUE TITLE
WA2 i have wa2 installed but is showing up as classic. how do i get the retail version, cannot seem to find that version to install. had the retail version and on Tuesday reset and addon updated all i can get is classic

### ISSUE THREAD

**Issue by Maricit** [WeakAuras/WeakAuras2#1692]
**What steps will reproduce the problem?**

**What is the expected output? What do you see instead?**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Do you have an error log of what happened?** 
 

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**

``` HERE ```

**Comment by InfusOnWoW** [comment]
By downloading it manually from the website. We are not responsible for the twitch client being broken.

**Comment by Maricit** [comment]
the only download on twitch is classic. wa2 from curse client go into retail addon but does not work because it is for classic not 8.2

**Comment by InfusOnWoW** [comment]
Again, that's nothing we can fix. That's a bug in the twitch software.

**Comment by emptyrivers** [comment]
This is the zip that we give to twitch for 8.2 WoW, if you feel up to manual installation: https://github.com/WeakAuras/WeakAuras2/releases/download/2.14.6/WeakAuras-2.14.6.zip
