### ISSUE TITLE
Enemy buffs not showing up?

### ISSUE THREAD

**Issue by mckeonj1** [WeakAuras/WeakAuras2#1694]
This might not be a bug, or maybe I have set it up wrong. But for Classic WOW I set up weakauras2 so that i can see all dispellable buffs next to the frame as well as key dispellable buffs on the enemy nameplates.  The problem is that it only shows buffs and key dispellable buffs that i wanted to see on friendly targets. it never shows any of the buffs on enemy targets???? is this a bug? is there a way to reverse this because really i dont want it on friendly frames or nameplates I want it for the enemy frames or nameplates so as a priest i know what to offensively dispel.

Please let me know if this is possible, a bug, or maybe classic wont let you look at enemy buffs so theres no way to do this? please let me know thank you!

**Comment by mrbuds** [comment]
You need to apply this debuff https://classic.wowhead.com/spell=2855/detect-magic to see buffs on enemies
