### ISSUE TITLE
WA-Group not loaded properly until WA Configuration is opened

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#1695]
**Describe the bug**
I created a WA-Group for Orgozoa benthic Gear and made the requirement for it to load by the ZoneID (ZoneIDs are set in the according WAs itself). It consists of two WAs, therefore the Group. When you enter the raid and get to the first time it should be loaded, the Orgozoa Boss Room, it won't load the WA-Group. You have to open the configuration of WA so the Addon 'checks' it and from then on it works fine. It's just the initial Load for it that seems not to happen correctly. Without the Group it works perfectly fine without having to open the configuration, so I'm guessing it seems to be the group that causes the issue here.

WA for code review purposes:
https://wago.io/2_n91MwPA

**Do you have an error log of what happened?**
no Error log, since the is no lua error or smth. like that

**To Reproduce**
1. Enter Raid
2. get to Orgozoa Room -> won't load the WA
3. open WA Configuration
4. close WA Configuration
5. WA works fine

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
latest Release Version; 2.14.6

**Was it working in a previous version? If yes, which was the last good one?**
n/a

**Comment by InfusOnWoW** [comment]
The group consists of two auras, I'm not sure which of the auras is the one that is problematic.

I've tried reproducing, but can't access Orogonzas room anymore, just the pool below, which has the zone id 1517. There the aura works correctly for me, thus I'd be suprised if the zone I could reproduce it.

Putting auras in a group does not affect the loading/unloading at all, so that has nothing to do with it.

**Comment by Breakerzeus** [comment]
I tried to ungroup them and then noticed that they indeed have the same issue without the grouping.
But the Problem remains the same. The WA are set like this:
In a normal state the WA has visibility 0% and one condition, that if you do not have the belt equipped, the visibility goes 100%. maybe there is some issue by loading the conditions? IDK

**Comment by InfusOnWoW** [comment]
Yoi still haven't actually explained which aura does not show up.

**Comment by Breakerzeus** [comment]
It's the 'Benthic_Equip_Reminder' WeakAura.

**Comment by InfusOnWoW** [comment]
I haven't forgotten about this bug report, but to reproduce it, I would need to at least to a LFR wing. And that consistently puts it behind pratically any other bug report, that takes less time to figure out.

**Comment by Breakerzeus** [comment]
Yeah well I tried it in the last few days with my mythic ID. We killed Orogoza so I got into the boss room as I entered the raid. That way, the WA ist loaded instantly and displayed correctly. So it seems the only way to reproduce it is to get through the other "raid zones" I guess. It's getting more mysterious...

**Comment by Breakerzeus** [comment]
I have new Information that it works for a Guildmate. He rarely updates his addons and has some old version 2.13.4 installed. So that is also a strong indicator that it has to be something with the addon itself, the WA seems not to be the issue here.
