### ISSUE TITLE
Copying conditions between aura types.

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#1696]
**Describe the bug**
Copying the condition settings of an aura with a different region type will result in conditions displaying nothing until something is edited. Would be nice to have the options roll over. Obviosuly not all options will be similar though. 

**To Reproduce**
Have two different types of aura regions, copy conditions between the two, seems to break. 

**Screenshots**
https://imgur.com/a/cN2eSx9

**Comment by InfusOnWoW** [comment]
I can't even read what you are copying in that screenshot.

**Comment by 1ps3** [comment]
https://youtu.be/fqnbJCuxMUg This should help in seeing the issue.
