### ISSUE TITLE
Can't open weakaura.

### ISSUE THREAD

**Issue by Laukagen** [WeakAuras/WeakAuras2#1700]
**Describe the bug**
So earlier today I tried to make a healer mana tracker, and wanted to shorten the amount of decimals in an number connected to this progress bar. I didn't know how, so I looked for it on reddit, but after posting this:
function()

    local p = math.max(0, UnitPower("player")) / math.max(1, UnitPowerMax("player")) * 100;
    return string.format("%.0f%%", p);
end

and using TSU, everything went down and i'm unable to open the optionsmenu. 
When I reboot the game, Weakaura opened in paused mode, but nothing happens when I try to resume.

**Do you have an error log of what happened?**
1x WeakAuras\GenericTrigger.lua:3125: attempt to index local 'variables' (a function value)
WeakAuras\GenericTrigger.lua:3125: in function <WeakAuras\GenericTrigger.lua:3104>
(tail call): ?
WeakAuras\WeakAuras-2.14.6.lua:4813: in function <WeakAuras\WeakAuras.lua:4795>
(tail call): ?
WeakAuras\WeakAuras.lua:4900: in function `GetOverlayInfo'
WeakAuras\RegionTypes\AuraBar.lua:126: in function `propertiesFunction'
WeakAuras\WeakAuras.lua:1005: in function `GetProperties'
WeakAuras\WeakAuras.lua:1135: in function `ConstructConditionFunction'
WeakAuras\WeakAuras.lua:4010: in function <WeakAuras\WeakAuras.lua:3956>
WeakAuras\WeakAuras.lua:4062: in function `Add'
WeakAuras\WeakAuras.lua:3616: in function `load'
WeakAuras\WeakAuras.lua:3623: in function `AddMany'
WeakAuras\WeakAuras.lua:1523: in function <WeakAuras\WeakAuras.lua:1511>

**To Reproduce**
1. Post the code
2. Weakauras stops working.

**Screenshots**
![image](https://user-images.githubusercontent.com/55357330/64924753-18cd4100-d7e8-11e9-8d75-90b35613bfc2.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.14.6 Classic

**Additional context**
Since i'm kinda clueless on what happened, i'm uploading both the weakaura file, and the string i worked on, with my mana bar.

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3613993/WeakAuras.zip)

``` HERE ```
["Healer Mana"] = {
			["sparkWidth"] = 10,
			["sparkOffsetX"] = 0,
			["authorOptions"] = {
			},
			["yOffset"] = -213.740905761719,
			["anchorPoint"] = "CENTER",
			["sparkRotation"] = 0,
			["sparkRotationMode"] = "AUTO",
			["id"] = "Healer Mana",
			["actions"] = {
				["start"] = {
				},
				["init"] = {
				},
				["finish"] = {
				},
			},
			["triggers"] = {
				{
					["trigger"] = {
						["type"] = "status",
						["subeventSuffix"] = "_CAST_START",
						["duration"] = "1",
						["event"] = "Power",
						["subeventPrefix"] = "SPELL",
						["use_specific_unit"] = true,
						["spellIds"] = {
						},
						["use_unit"] = true,
						["unevent"] = "auto",
						["names"] = {
						},
						["unit"] = "Rexios",
						["debuffType"] = "HELPFUL",
					},
					["untrigger"] = {
						["use_specific_unit"] = true,
						["unit"] = "Rexios",
					},
				}, -- [1]
				{
					["trigger"] = {
						["type"] = "status",
						["unevent"] = "auto",
						["duration"] = "1",
						["event"] = "Power",
						["subeventPrefix"] = "SPELL",
						["unit"] = "Rexios",
						["subeventSuffix"] = "_CAST_START",
						["use_percentpower"] = true,
						["use_specific_unit"] = true,
						["use_unit"] = true,
						["percentpower"] = "30",
						["percentpower_operator"] = "<",
					},
					["untrigger"] = {
						["use_specific_unit"] = true,
						["unit"] = "Rexios",
					},
				}, -- [2]
				{
					["trigger"] = {
						["customVariables"] = "function()\n    local p = math.max(0, UnitPower(\"player\")) / math.max(1, UnitPowerMax(\"player\")) * 100;\n    return string.format(\"%.0f%%\", p);\nend",
						["type"] = "custom",
						["custom"] = "function()\n    local p = math.max(0, UnitPower(\"player\")) / math.max(1, UnitPowerMax(\"player\")) * 100;\n    return string.format(\"%.0f%%\", p);\nend",
						["subeventSuffix"] = "_CAST_START",
						["check"] = "update",
						["custom_type"] = "stateupdate",
						["event"] = "Health",
						["subeventPrefix"] = "SPELL",
					},
					["untrigger"] = {
					},
				}, -- [3]
				["disjunctive"] = "any",
				["activeTriggerMode"] = -10,
			},
			["icon_color"] = {
				1, -- [1]
				1, -- [2]
				1, -- [3]
				1, -- [4]
			},
			["internalVersion"] = 23,
			["animation"] = {
				["start"] = {
					["type"] = "none",
					["duration_type"] = "seconds",
				},
				["main"] = {
					["type"] = "none",
					["duration_type"] = "seconds",
				},
				["finish"] = {
					["type"] = "none",
					["duration_type"] = "seconds",
				},
			},
			["backdropInFront"] = false,
			["xOffset"] = -493.803070068359,
			["barColor"] = {
				0.129411764705882, -- [1]
				0.352941176470588, -- [2]
				0.647058823529412, -- [3]
				1, -- [4]
			},
			["desaturate"] = false,
			["backgroundColor"] = {
				0, -- [1]
				0, -- [2]
				0, -- [3]
				0.5, -- [4]
			},
			["stickyDuration"] = false,
			["sparkOffsetY"] = 0,
			["subRegions"] = {
				{
					["type"] = "aurabar_bar",
				}, -- [1]
				{
					["type"] = "subborder",
					["border_offset"] = 0,
					["border_anchor"] = "bar",
					["text_color"] = {
					},
					["border_color"] = {
						0, -- [1]
						0, -- [2]
						0, -- [3]
						1, -- [4]
					},
					["border_visible"] = true,
					["border_edge"] = "1 Pixel",
					["border_size"] = 1,
				}, -- [2]
				{
					["text_shadowXOffset"] = 0,
					["text_text"] = "Healer Mana",
					["text_shadowColor"] = {
						0, -- [1]
						0, -- [2]
						0, -- [3]
						1, -- [4]
					},
					["text_selfPoint"] = "AUTO",
					["anchorYOffset"] = 0,
					["rotateText"] = "NONE",
					["type"] = "subtext",
					["text_anchorXOffset"] = 0,
					["text_color"] = {
						1, -- [1]
						1, -- [2]
						1, -- [3]
						1, -- [4]
					},
					["text_font"] = "Naowh",
					["text_shadowYOffset"] = 0,
					["text_visible"] = true,
					["text_anchorPoint"] = "TOPLEFT",
					["text_anchorYOffset"] = 8,
					["text_fontSize"] = 14,
					["anchorXOffset"] = 0,
					["text_fontType"] = "OUTLINE",
				}, -- [3]
				{
					["text_shadowXOffset"] = 1,
					["type"] = "subtext",
					["text_text"] = "%c",
					["text_color"] = {
						1, -- [1]
						1, -- [2]
						1, -- [3]
						1, -- [4]
					},
					["text_font"] = "Naowh",
					["text_shadowColor"] = {
						0, -- [1]
						0, -- [2]
						0, -- [3]
						1, -- [4]
					},
					["text_shadowYOffset"] = -1,
					["text_selfPoint"] = "AUTO",
					["text_fontType"] = "None",
					["text_anchorPoint"] = "INNER_RIGHT",
					["anchorYOffset"] = 0,
					["text_fontSize"] = 12,
					["rotateText"] = "NONE",
					["anchorXOffset"] = 0,
					["text_visible"] = true,
				}, -- [4]
			},
			["height"] = 15,
			["icon"] = false,
			["load"] = {
				["spec"] = {
					["multi"] = {
					},
				},
				["class"] = {
					["multi"] = {
					},
				},
				["size"] = {
					["multi"] = {
					},
				},
			},
			["sparkBlendMode"] = "ADD",
			["useAdjustededMax"] = false,
			["config"] = {
			},
			["borderInset"] = 11,
			["uid"] = "Ad5QkmsAHKf",
			["borderEdge"] = "None",
			["anchorFrameType"] = "SCREEN",
			["border"] = false,
			["useAdjustededMin"] = false,
			["regionType"] = "aurabar",
			["borderSize"] = 16,
			["alpha"] = 1,
			["icon_side"] = "RIGHT",
			["selfPoint"] = "CENTER",
			["sparkHeight"] = 30,
			["texture"] = "Melli",
			["spark"] = false,
			["zoom"] = 0,
			["auto"] = true,
			["sparkTexture"] = "Interface\\CastingBar\\UI-CastingBar-Spark",
			["sparkHidden"] = "NEVER",
			["borderOffset"] = 5,
			["frameStrata"] = 1,
			["width"] = 160,
			["borderInFront"] = true,
			["sparkColor"] = {
				1, -- [1]
				1, -- [2]
				1, -- [3]
				1, -- [4]
			},
			["inverse"] = false,
			["backdropColor"] = {
				1, -- [1]
				1, -- [2]
				1, -- [3]
				0.5, -- [4]
			},
			["orientation"] = "HORIZONTAL",
			["conditions"] = {
				{
					["check"] = {
						["trigger"] = 2,
						["variable"] = "show",
						["value"] = 1,
					},
					["changes"] = {
						{
							["value"] = {
								0.63921568627451, -- [1]
								0.105882352941176, -- [2]
								0.117647058823529, -- [3]
								1, -- [4]
							},
							["property"] = "barColor",
						}, -- [1]
					},
				}, -- [1]
			},
			["borderBackdrop"] = "Blizzard Tooltip",
			["borderColor"] = {
				1, -- [1]
				1, -- [2]
				1, -- [3]
				0.5, -- [4]
			},
		},

**Comment by InfusOnWoW** [comment]
That's because you accidentally inserted the text into the wrong text field. We'll fix that for the next release (and one of the next alphas).

Though it seems from the information that you have given, the function you posted won't help you accomplish what you want. You might want to stop by our discord for help with writing that aura.

**Comment by Laukagen** [comment]
So how do I make my Weakaura file work again? Can't use the addon atm. :)

**Comment by InfusOnWoW** [comment]
" We'll fix that for the next release (and one of the next alphas)."

**Comment by emptyrivers** [comment]
If you don't wish to install alpha then you can upload your saved variables here, and i'll repair it for you.

**Comment by Laukagen** [comment]
I had a guy on disc fix it for me, so everything is good. Thanks for the help. ;)
