### ISSUE TITLE
Classic Version is Being Installed As Latest Version When Using the Twitch Client

### ISSUE THREAD

**Issue by Calesta** [WeakAuras/WeakAuras2#1703]
**Describe the bug**
Typically, when we users 'Update' an addon using the Twitch client the latest version is downloaded and installed. A few addons like yours have now started including a classic version in the same project as the retail version and it's causing the classic version to be interpreted as the latest version. We have to manually revert the update to the retail version.

Please separate your projects if the code base can't support both versions. Thanks.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by Stanzilla** [comment]
Nope it works fine, just had a CurseForge outage last week.

**Comment by Calesta** [comment]
I *just* did this as of this writing and it doesn't work fine.  I had to revert back to the release version.

**Comment by Stanzilla** [comment]
reinstall them once manually. either way, not a bug for us but for Twitch

**Comment by Calesta** [comment]
![image](https://user-images.githubusercontent.com/13042214/64925904-21f8e680-d7c5-11e9-8b86-3b3a3a2981cd.png)

**Comment by emptyrivers** [comment]
We unfortunately cannot solve bugs in the twitch. Contact twitch for support on this issue. If there is a fix available, then you can try updating your twitch app. Otherwise, seek alternative solutions until a fix is available from them.

**Comment by Calesta** [comment]
Other addons don't seem to have this problem only those who put two different code versions in the same project.  I'll just flag WeakAuras as one I'll have to revert each time.

I've also sent a note to Twitch support in case they can help prevent this from happening on their end. 

Thanks for the replies.

**Comment by Stanzilla** [comment]
Okay, cool!

**Comment by Stanzilla** [comment]
Also make sure you have the latest version of the Twitch app.

**Comment by gowan2019** [comment]
Ok this is not a twitch problem since i am facing the same issue, the two versions (classic and retail) are on the same addon so when we use twitch to update, it just update to the latest version whether it was intended for the retail or classic so if you can separate them into two addons it would be great, thanks.

**Comment by InfusOnWoW** [comment]
That you think that it isn't a twitch problem, does not make it not a twitch problem. What we are doing is entirely correct, twitch is just broken.

**Comment by gowan2019** [comment]
Ok no worries, i thought there might be a fix from your side, sorry :)

**Comment by ZeldoKavira** [comment]
Hey @gowan2019 and @Calesta I work for Mods in the Twitch App and am looking for more information on this, can you please reach out to me on Discord so I can help track down this issue? I am Zeldo#1872 on there, or if you want to DM me on here instead I can give you my email.

Thanks!

**Comment by Calesta** [comment]
@ZeldoKavira I haven't had any issues since the initial incident so perhaps it was a fluke.  It certainly caught me by surprise because I've gotten used to simply updating all my addons at once.

According to the reply I got back from Twitch, it shouldn't happen because classic is a separate installation and I'd need to select it from the dropdown like the PTR.  I don't even have classic installed so it doesn't show up in the install directories but the classic versions of the mods were still considered updates for retail.  

Since I can't recreate it, I'm considering this a one-time event.  If I'm able to replicate it, then I'll reach out.  

Thanks for the follow-up!
