### ISSUE TITLE
Dynamic grouping in classic

### ISSUE THREAD

**Issue by dalesnail** [WeakAuras/WeakAuras2#1706]
Wondering if dynamic groups are supposed to be absent from classic? If the classic api doesn't allow for it, I understand. Just would like to have it if possible!

**Comment by InfusOnWoW** [comment]
Is there any basis to your wondering? They are after all in the WeakAuras for classic

**Comment by dalesnail** [comment]
> Is there any basis to your wondering? They are after all in the WeakAuras for classic

I cannot seem to find it, I will ask some guild mates if they can see this.
