### ISSUE TITLE
well the retail version is now classic, so broken in retail

### ISSUE THREAD

**Issue by eaglegoboom** [WeakAuras/WeakAuras2#1707]
**What steps will reproduce the problem?**

**What is the expected output? What do you see instead?**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Do you have an error log of what happened?** 
 

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**

``` HERE ```

**Comment by emptyrivers** [comment]
This is a bug with the twitch app, where it is serving the wrong version. Ensure you have the latest version of the twitch app, and failing that, you can install manually using this link: https://github.com/WeakAuras/WeakAuras2/releases/download/2.14.6/WeakAuras-2.14.6.zip
