### ISSUE TITLE
Notify user when the specific unit they choose is not valid for the trigger

### ISSUE THREAD

**Issue by LiangYuxuan** [WeakAuras/WeakAuras2#1711]
**Describe the bug**

Specific Unit `targettarget` fails in BuffTrigger2, always not exists.

**Do you have an error log of what happened?**

No.

**To Reproduce**

1. Create a BuffTrigger2 trigger and use specific unit `targettarget`
2. Try to track a buff you have, and target yourself
3. The icon fails to show
4. Check _Show If Unit Does Not Exist_ and the icon shows

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No.

**Which version of WeakAuras are you using?**

2.14.6

**Was it working in a previous version? If yes, which was the last good one?**

Didn't try.

**Additional context**
```
!nwvZUnUnq4NMESb(NSgPhtCv2KchPutLI0l0lL0iPbrM0vKY)Kd7PEyp2xY2NJodPuIwxuSlGHm1W53V5BgjNktLcugpD(Ijx9bPWkfZUy6LxSqk2kff8psHQgZbzMuCmPS0coz8eP40OZkDETP9rdQDsXYO40O1srUX0uyoOfhWDG8M3fevubS3WCJML7AXQkO1srk2Np9c4JDw4JTMUDBYnDKZjRihKOBoXgQvBHERe)ZF(L)(V(IKIFNgDrhrRZY6qoyJJcSd3XwB3b5yjM)ePefivBf4cpLISUYsrT5qIM0Z))dO1I6ksXtujiuDTQzbxwaS2lBuwl7wsu0rvUtSdAAUVGdmShy04oq14Qd2A5BXIHu(QFA(coHTDzELFSfkXJsH4XOvRcwmUcFt9qm6fhpiERYLxd2)NcyigckR5ySz51I0nI0RxNYnMTzOgEi4HGTRmhaBpAsoh2MrnerOSt9OXDrRE82NwfG83Bzowabf4Eini8btbiJ)XPt4Bikc0Qvn)g1WrQ)hpBUu8ca7UMBnU1khAyevPXT8znZcSulYXhkimHfUj0qSarHiKOV)OnAiafO(7x7suJ26VB9DmkyvowxpnMhowAAmT9ne63m)Z5(NxYpdD51qf59r8C4OBJTwrdfppAAQp6Dz899Afo(d2(xZ)2XZRxPH5G32IV(5p9RDQckNvF(tPFDShN8t8oBI3ztoZzbT)9XzQxm0u2p6F9tPjJICGNK8u6Q7JJ6L)vRkUpooA9MBssttEy99F8U0Hvj)NGShTywJFnsRXriFQhqItyhhS55ZTHtbb(kX9Mol04QbSQM0yXLsrJr53TX0o()TD0oIb(BUFW(CPw2zNj0fia32c)rhOZprH)IzFiimu)zDoNrNShABuN6VOgZFrdui4bBNjF)W0WvtMnHY)wptjyVFnP3Sv0qkzYvsALAbTuXxh0QN3zGzHrVaj7TXMXKC)ii6ERq)2ePoK(mquZRZ)LNpUm7fLu8QXS1dZCGh3Qg2WZnNFgTkQJv4ZPoNHBDS(ICvd4RB2Vo)sgvZUALxwzlTXJ(aaXt9VhAT3YsdOHy56OOyE48nw37FWrxIvd1idPqFWjxKSBaw67yRaDfJHt95TUap7(X0j(9BmTfaJW097jZUCgJoY)n
```

**Comment by emptyrivers** [comment]
targettarget is unfortunately not a primitive unit id, so we do not receive UNIT_AURA events for that unit. This, it is not possible to maintain accurate information about that particular unit. We could check on every frame for derived units like this, but I do not think that is an acceptable performance impact.

**Comment by LiangYuxuan** [comment]
Thanks to your reply. I think it's reasonable, but is there any chance to add a line of text to tell unitid like this is not accpected? The tooltip tells me to input a unit id, but I didn't know `targettarget` is not accpected until I thought it's a bug and open this issue.

**Comment by emptyrivers** [comment]
That’s fair, we can do that.

**Comment by emptyrivers** [comment]
Would “{userEntry} is not a trackable unit” make sense to you as an alert?

**Comment by LiangYuxuan** [comment]
Yes, I think.
