### ISSUE TITLE
Twitch updated Weakauras with Weakauras classic

### ISSUE THREAD

**Issue by Anothersignup** [WeakAuras/WeakAuras2#1713]
I downloaded the file manually now. Do I have to do that from now on.

I have lots of addons. Twitch also updated the addon XP MultiBar with the classic one.

**Comment by krazyito65** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/1703
https://github.com/WeakAuras/WeakAuras2/issues/1707

https://github.com/WeakAuras/WeakAuras2/issues/1690

Download manually until Twitch fixes it.

**Comment by Stanzilla** [comment]
Yeah sadly nothing we can do about that.

**Comment by ZeldoKavira** [comment]
@Anothersignup Can you please reach out on Discord? I am looking into this issue and am trying to gather more information. My discord is Zeldo#1872

Do you have classic installed? If so did you just add it to the app? Is the issue still happening for you now?

**Comment by Anothersignup** [comment]
It happened with other addons as well, like XP Multibar and Sexymap. The
response I got from them was that it was something the Twitch app did and
they could do nothing about it.

I do not have classic WoW installed.
