### ISSUE TITLE
Error in Mana Regen

### ISSUE THREAD

**Issue by Spiricore** [WeakAuras/WeakAuras2#1714]
Hi there,
I've been getting this error a lot since I started using the three resource trackers posted here: https://wago.io/p/Rabble

>  [string "--[[ Error in 'Mana Regen' ]] return functi..."]:5: attempt to compare nil with number
[C]: in function `xpcall'

>  WeakAuras\GenericTrigger.lua:512: in function <WeakAuras\GenericTrigger.lua:505>

>  WeakAuras\GenericTrigger.lua:636: in function `ScanUnitEvents'

>  WeakAuras\GenericTrigger.lua:776: in function <WeakAuras\GenericTrigger.lua:773>

It only seems to happen for a bit after /reloadui. Is this an error on my behalf?

Also, thank you so much for WA2 and continuing to support it!

**Comment by InfusOnWoW** [comment]
The link you posted doesn't go the aura, but from the error message it's clear that it's a bug in the aura you imprtet and that you need to contact the author. Or if they don't respond, seek help in our discord.
