### ISSUE TITLE
I GET THIS LUA ERROR EACH LOGON :(

### ISSUE THREAD

**Issue by darthyoda74** [WeakAuras/WeakAuras2#1717]
Message: ...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:147: table index is nil
Time: Sat Sep 21 10:39:34 2019
Count: 1
Stack: ...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:147: table index is nil
...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:147: in function `Spell'
...eakAuras\Libs\LibClassicDurations\classAbilities.lua:64: in main chunk

Locals: id = 26635
opts = <table> {
 type = "BUFF"
 duration = 10
}
lastRankID = 26635
spellName = nil
(*temporary) = <table> {
 Free Action = 6615
 Mind Amplification Dish = 13181
 Goblin Rocket Boots = 8892
 Shadow Reflector = 23132
 Invulnerability = 3169
 Freedom = 9774
 Gnomish Rocket Boots = 13141
 Running Speed = 9175
 Goblin Mortar = 13237
 Mithril Insignia = 12733
 Damage Absorb = 23991
 Recently Bandaged = 11196
 Tidal Charm = 835
 Spell Vulnerability = 23605
 Restoration = 11359
 Self Invulnerability = 16621
 Thorium Grenade = 19769
 Fire Reflector = 23097
 Abolish Poison = 14253
 Aura of Protection = 23506
 Frost Reflector = 23131
 The Burrower's Shell = 29506
 Flash Bomb = 5134
 Flee = 5024
 Berserking = 23505
 Reckless Charge = 13327
 Sleep = 1090
 Net-o-Matic = 16566
 Dazed = 1604
 Poison Mushroom = 6727
 Living Free Action = 24364
 Speed = 14530
}
(*temporary) = "number"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
GetSpellInfo = <function> defined =[C]:-1
spellNameToID = <table> {
 Free Action = 6615
 Mind Amplification Dish = 13181
 Goblin Rocket Boots = 8892
 Shadow Reflector = 23132
 Invulnerability = 3169
 Freedom = 9774
 Gnomish Rocket Boots = 13141
 Running Speed = 9175
 Goblin Mortar = 13237
 Mithril Insignia = 12733
 Damage Absorb = 23991
 Recently Bandaged = 11196
 Tidal Charm = 835
 Spell Vulnerability = 23605
 Restoration = 11359
 Self Invulnerability = 16621
 Thorium Grenade = 19769
 Fire Reflector = 23097
 Abolish Poison = 14253
 Aura of Protection = 23506
 Frost Reflector = 23131
 The Burrower's Shell = 29506
 Flash Bomb = 5134
 Flee = 5024
 Berserking = 23505
 Reckless Charge = 13327
 Sleep = 1090
 Net-o-Matic = 16566
 Dazed = 1604
 Poison Mushroom = 6727
 Living Free Action = 24364
 Speed = 14530
}
spells = <table> {
 3169 = <table> {
 }
 23451 = <table> {
 }
 29506 = <table> {
 }
 11196 = <table> {
 }
 4068 = <table> {
 }
 14253 = <table> {
 }
 26740 = <table> {
 }
 11359 = <table> {
 }
 1090 = <table> {
 }
 23097 = <table> {
 }
 25746 = <table> {
 }
 25747 = <table> {
 }
 25750 = <table> {
 }
 13099 = <table> {
 }
 19769 = <table> {
 }
 23991 = <table> {
 }
 16621 = <table> {
 }
 5134 = <table> {
 }
 5024 = <table> {
 }
 6615 = <table> {
 }
 9774 = <table> {
 }
 2379 = <table> {
 }
 8892 = <table> {
 }
 13141 = <table> {
 }
 16566 = <table> {
 }
 9175 = <table> {
 }
 6727 = <table> {
 }
 13237 = <table> {
 }
 13138 = <table> {
 }
 24364 = <table> {
 }
 12733 = <table> {
 }
 23506 = <table> {
 }
 13327 = <table> {
 }
 23505 = <table> {
 }
 1604 = <table> {
 }
 23493 = <table> {
 }
 835 = <table> {
 }
 23131 = <table> {
 }
 23132 = <table> {
 }
 13181 = <table> {
 }
 14530 = <table> {
 }
 23605 = <table> {
 }
}
Message: ...ras\Libs\LibClassicCasterino\LibClassicCasterino.lua:466: table index is nil
Time: Sat Sep 21 10:39:34 2019
Count: 1
Stack: ...ras\Libs\LibClassicCasterino\LibClassicCasterino.lua:466: table index is nil
...ras\Libs\LibClassicCasterino\LibClassicCasterino.lua:466: in main chunk

Locals: MAJOR = "LibClassicCasterino"
MINOR = 10
lib = <table> {
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\AutoVendor\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 casters = <table> {
 }
 UnregisterCallback = <function> defined @Interface\AddOns\AutoVendor\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UnitCastingInfo = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:222
 callbacks = <table> {
 }
 frame = <unnamed> {
 }
 UnitChannelInfo = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:239
 RegisterCallback = <function> defined @Interface\AddOns\AutoVendor\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
}
f = <unnamed> {
 0 = <userdata>
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:125
 UNIT_SPELLCAST_START = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
 UNIT_SPELLCAST_FAILED = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:253
}
callbacks = <table> {
 recurse = 0
 events = <table> {
 }
 OnUsed = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:267
 Fire = <function> defined @Interface\AddOns\AutoVendor\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 OnUnused = <function> defined @Interface\AddOns\WeakAuras\Libs\LibClassicCasterino\LibClassicCasterino.lua:285
}
casters = <table> {
}
UnitGUID = <function> defined =[C]:-1
bit_band = <function> defined =[C]:-1
GetTime = <function> defined =[C]:-1
CastingInfo = nil
ChannelInfo = nil
COMBATLOG_OBJECT_TYPE_PLAYER = 1024
classCasts = <table> {
 10468 = 1.500000
 24239 = 1
 10216 = 3
 126 = 5
 10605 = 2.500000
 19943 = 1.500000
 17923 = 1.500000
 5784 = 3
 25297 = 3.500000
 759 = 3
 9858 = 2
 25307 = 3
 25309 = 2
 25311 = 2
 688 = 10
 17951 = 3
 17953 = 3
 982 = 10
 20755 = 3
 20757 = 3
 6366 = 3
 20773 = 10
 17727 = 5
 28270 = 1.500000
 13819 = 3
 25357 = 3
 10140 = 3
 3552 = 3
 23214 = 3
 10912 = 3
 10054 = 3
 8690 = 10
 14327 = 1.500000
 18658 = 1.500000
 2641 = 5
 1002 = 2
 20904 = 3
 12826 = 1.500000
 9853 = 1.500000
 1842 = 2
 10623 = 2.500000
 20777 = 10
 556 = 10
 691 = 10
 9912 = 2
 2645 = 3
 6196 = 2
 17924 = 4
 25292 = 2.500000
 17928 = 2
 10934 = 2.500000
 25298 = 3.500000
 15208 = 3
 4068 = 1
 25304 = 3
 25306 = 3.500000
 6064 = 3
 6201 = 3
 10053 = 3
 6202 = 3
 25316 = 3
 17952 = 3
 23161 = 3
 10947 = 1.500000
 20752 = 3
 10876 = 3
 20756 = 3
 2053 = 2.500000
 15261 = 3.500000
 10318 = 2
 25314 = 3
 10955 = 1.500000
 10917 = 1.500000
 20770 = 10
 10207 = 1.500000
 693 = 3
 17728 = 5
 10326 = 1.500000
 28612 = 3
 20748 = 2
 28023 = 3
 18960 = 10
 9901 = 1.500000
 11729 = 3
 11730 = 3
 6215 = 1.500000
 11605 = 1.500000
 2362 = 5
 712 = 10
 697 = 10
 1122 = 2
 1
Message: ...r\libs\LibWidgetFactory-1.0\LibWidgetFactory-1.0.lua:85: AceGUI30DropDown4:SetPoint(): <unnamed> is dependent on this
Time: Sat Sep 21 10:39:47 2019
Count: 1
Stack: ...r\libs\LibWidgetFactory-1.0\LibWidgetFactory-1.0.lua:85: AceGUI30DropDown4:SetPoint(): <unnamed> is dependent on this
(tail call): ?
[C]: in function `SetPoint'
...r\libs\LibWidgetFactory-1.0\LibWidgetFactory-1.0.lua:85: in function `?'
...r\libs\LibWidgetFactory-1.0\LibWidgetFactory-1.0.lua:124: in function `factory'
Interface\AddOns\SheepMonitor\options.lua:189: in function `CreateInterfaceOptions'
Interface\AddOns\SheepMonitor\main.lua:44: in function <Interface\AddOns\SheepMonitor\main.lua:23>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...erface\AddOns\AGZ\libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...erface\AddOns\AGZ\libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...erface\AddOns\AGZ\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>
Message: ...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:175: table index is nil
Time: Sat Sep 21 10:40:19 2019
Count: 1
Stack: ...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:175: table index is nil
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:582: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:542>
[C]: ?
...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:175: in function <...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:170>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: errMsg = "...e\AddOns\WeakAuras\Libs\LibClassicDurations\core.lua:175: table index is nil"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:334
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:116
 hitInternalError = false
 errorFrame = <unnamed> {
 }
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:349
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:342
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:312
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:280
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by emptyrivers** [comment]
Hi there, thanks for the issue report. This is an error in one of the libraries we package in our classic version of WeakAuras. Did you install that to the retail environment unintentionally?

If so, then you can install the retail package using this link: https://github.com/WeakAuras/WeakAuras2/releases/download/2.14.6/WeakAuras-2.14.6.zip

**Comment by InfusOnWoW** [comment]
Pretty sure it's twitch installing the wrong version.

And pretty sure we ask what the game version is in the template, simply deleting that question without answering doesn't exactly help.

**Comment by darthyoda74** [comment]
thx. All is well.
uninstalled what was the classic version and installed the correct one.
