### ISSUE TITLE
After the loading the WoW update, my weakauras are gone.  

### ISSUE THREAD

**Issue by XXXiexie** [WeakAuras/WeakAuras2#172]
What steps will reproduce the problem?  IDK...uploaded today's patch, entered the game and no WAs.

What is the expected output? What do you see instead?  There is nothing but the WeakAurasOptions screen with no Loaded or Unloaded WAs listed.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?  Yes, still no WAs listed on the Options screen

What version of WeakAuras are you using?  2.3.5

Was it working in a previous version? If yes, which was the last good one?

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`  

Would love to but none of my WAs are there...

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by Stanzilla** [comment]
That is sadly nothing we can fix, it's a Bug in WoW and sadly low priority for their UI team.
