### ISSUE TITLE
Icon desaturates even though condition is not active with old group

### ISSUE THREAD

**Issue by Jundarer** [WeakAuras/WeakAuras2#1720]
I have a very old dynamic group that I kept updating. A few weeks ago (can't remember when it exactly first happened) the icons stayed desaturated after opening the settings, viewing the group and then closing it again.
The condition that is used is destaturate if the trigger is on cooldown in all cases. No custom code used.
Dynamic Group causing the bug: https://wago.io/pr5o_Nopp

Remade the group with basically the same settings and it doesnt happen anymore: https://wago.io/TEKe6wejx

Note: In the bugged group I already tried changing the spells to spell id and it didnt fix it. I have also been told this might have to do with old settings present in the group.

**To Reproduce**
1. Import wa
2. Make any icons of the wa visible in settings
3. Close settings

**Screenshots**
https://cdn.discordapp.com/attachments/218084462523711489/625304758311190558/unknown.png this is what it looks like after clicking on just cen ward as visible in the settings and then closing the settings. All icons(with the condition) are grayed out if you had the whole group visible

**Which version of WeakAuras are you using?**
2.14.6

**Was it working in a previous version? If yes, which was the last good one?**
I cannot remember which was the last version.

**Comment by InfusOnWoW** [comment]
That's interesting. It's caused by the "Fade out" animation these auras have. I'll fix the underlying problem in the next release, but that should help you before then.
