### ISSUE TITLE
When casting an aura on multiple mobs, progress bars do not update properly without targeting

### ISSUE THREAD

**Issue by pamilaa** [WeakAuras/WeakAuras2#1726]
**What steps will reproduce the problem?**

Set multi-target aura progress bar for Psychic Scream. Aggro 2 mobs. Cast Psychic Scream.

I also managed to reproduce this by casting dots on targets and switching the target immeadiately (before the dot lands).

**What is the expected output? What do you see instead?**

Weakauras display 2 progress bars with timers and progress. What I get is one progress bar with timer and progress and one progress bar with icon, but no progress nor timer.

When targeting each affected mob separately after casting, the progress bar starts to update normally.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

2.15.0 (2019-09-24)

**Are you on World of Warcraft Classic or Retail?**

Classic

**Was it working in a previous version? If yes, which was the last good one?**

No

**Do you have an error log of what happened?** 

No errors logged in neither.

**Please provide any additional information below:**

Screenshot: https://www.dropbox.com/s/lxif4mfae7oy44o/weakauras.png?raw=1

**Comment by emptyrivers** [comment]
This is a known limitation of the multi-target option on the aura trigger. The WoW API does not provide enough information to correctly track the durations of every aura detected via the combat log. You can use the nameplate option (with nameplates enabled) for accurate tracking, albeit for a smaller scope of units.
