### ISSUE TITLE
Powertype conditioning. Gone.

### ISSUE THREAD

**Issue by Dajova** [WeakAuras/WeakAuras2#1728]
**Describe the bug**
Powertype conditioning dropdown menu is gone.

**Do you have an error log of what happened?**
No error.

**To Reproduce**
Make any aura.
Set a power trigger.
Go to conditions and try to set a powertype. The dropdown is gone. From ALL versions. Since last patch.

**Screenshots**
[gif](https://i.imgur.com/MjbjvGc.gif)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes. Downgraded as well to version where i'm 100% certain it was a thing. Still gone.

**Which version of WeakAuras are you using?**
All versions from today until 1 month back.

**Was it working in a previous version? If yes, which was the last good one?**
It was working fine before the 8.2.5 patch. Then it was gone.

It seems to be a Blizzard bug, because i've never seen a bug like this with no error logs and that former versions are also gone the same way, just like that.

**Comment by emptyrivers** [comment]
For whoever picks this ticket up, this block needs updating: https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/Types.lua#L445-L461
Those global strings have been deprecated for years but never got replaced.

**Comment by emptyrivers** [comment]
Either that, or dajova happens to have an addon which wipes those values, anyways.

**Comment by Vardex** [comment]
Those global still exist for me

**Comment by SpatenLa** [comment]
Its wiped from only the conditions, but not from the trigger itself
