### ISSUE TITLE
Trigger/Chat Message on Load - ACE3 problem?

### ISSUE THREAD

**Issue by Obsurd** [WeakAuras/WeakAuras2#1733]
**What steps will reproduce the problem?**
Any/Every time I try to use any of my WA's that send a chat message action on trigger, this occurs.  The unload triggers seem to work, but the load triggers aren't.

**What is the expected output? What do you see instead?**
It's supposed to send chat to a channel.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Tried with ONLY WA enabled.

**Which version of WeakAuras are you using?**
2.15.0, 2.15.0-2-g5e5717c, 2.15.0-3-gf45f8a7. 

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
YES!  Was working perfectly fine until the 8.2.5

**Do you have an error log of what happened?** 
Message: ADDON_ACTION_BLOCKED: WeakAuras tried to call the protected function 'UNKNOWN()'.
Time: Wed Sep 25 18:55:15 2019
Count: 1
Stack: ADDON_ACTION_BLOCKED: WeakAuras tried to call the protected function 'UNKNOWN()'.
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: ?
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:4362: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4362>
[C]: in function `pcall'
Interface\AddOns\WeakAuras\WeakAuras.lua:4362: in function `HandleChatAction'
Interface\AddOns\WeakAuras\WeakAuras.lua:4399: in function `PerformActions'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:694: in function `Collapse'
Interface\AddOns\WeakAuras\WeakAuras.lua:5782: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\GenericTrigger.lua:663: in function `ScanEventsInternal'
Interface\AddOns\WeakAuras\GenericTrigger.lua:619: in function `ScanEvents'
Interface\AddOns\WeakAuras\GenericTrigger.lua:752: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:743>

Locals: <none>

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**

!DB1sZTTnq4FnDM2d2JSIDQZrAzjlnrIuvGQjThOeijOiIjbubaTICNQF7D3fK6rA90CUZWHeyX(a7RVLj3KeNWQty54dSCtLExYdjSmDL2aecVHE6tVFh9(w8TlHTpQOWkCWU(xFxcJRYk1M5APcoBWWW4Hlq1ORY17uSDYTcsVnwNUow8v3YT5CNiH10(TJ1H5BejPjmzMwHs4mYnBegR)YeFKaUSXkwvOn1i)4AE1o(ERZ0q2I3y4kETOvugtRoSwxCy9t8QkbODWTybV2yehw)j4oyoSgvEoOBWvzJmARZwYn5hwprvimkEf69m2Z7bDORe1jHGJpqNYRChwp3iR1MCjV6W6hLgbenat8(e2mzUsUPeIu)mOvURuxdCStaxcWs3NWIn8xeGuJqxj8djSXWzfs8ED0Wqq1UfihcousypiDbENtcEbdCnBtQ4fHYXAkkKFnHTAqalEfloyrBuQrjDymH(YQf1PGTPtCqC3j3IHWAUlRuyzL6DrGET03zsRvQ2qMptwiZwsQikfcZw5lcnCvePGDJ3dPy24HtNpA5us3pz0nBxLPBGsI2mKuLPRt50EuO3Ww)FkTbUnL0EWhb8bRbvCRLckkkXHvRoTNJAmGjYXtDum164UgBcRLZbAvUet92U(PvN4t01pze8k2fvmOUpvd9qBb1KCmq7ovdn3iOAi28HtH8iurK98rBJzpPsmZxP4ZBt17ew3r9tfjNk4W2YuR2KotNJwfzuDQh2HeYL2V0OYCq5ecKShErBI9SrsgE1n9qEb8fk0(RaMGKQgU1dB95o8OEOoK1(UJykSyC4IUwMUWLaGyaVVnkR0kbAGAUKeZtDRrGk94xE12s(8MkR4n1hWvHujTLF32eJ(oz2Z7FSRPo17td(VHHH02cXgQA4icjaVUcAbYVmO0EdAsXZB5YV8hSTB)oG9j(k0yXWiJ81dR)LgEoCR5hwhFPTp)Y3Juwpsz9(gL55(3o)MsKfvfTJtcwghDMLzYxf4yNwsViTY0kAObT)IjrtcdhUy1drXXrZwm5PXXDtQ(h27lqRKSy)PHxgn2pftrOWOWHDs(5Vvs8o5r)IwgpDcWjLslfE4J(aAJtN9sxb79963divP55DdXSOh57iZOjYnaMCx3bYq2r8cceDdISIBXUCy8Da89W6767p3teN2ssHTaGiqeI94WzrHJx69VoJaudIh)Xqk6as9PGflMeTaxopyAWJtcXLZcEAirAXKHSo(Mgn4J4YZ1lS90QfrpTKedoN4KnoywqiHdqnZEp5SRONWPlNFpiPHlZ7KJIxNje1hDruZ5BGgze)rJqLThYwxJjcK4uabZsq44oFMlTX50QiijvX33Eqj0scCAPXhzNqDj4seHYV5eadm0YY3azRsUsjQsyV)enF33GXbqbjaRMRx1Ec6BDlz)jQR)cMOvPHztF8W6z4WGdRxU9W6UZUeG5n0)BRXbCuHT69Oo)3VqN7ju6s66Qk99cJmWSe6vcBy1llhTAoe)W)TWqGs(Gl9VC4eoqIOTNfeBGuk7Xn96xo(3dlFyp(VewyyNbhHLEHr8AInyXWHHG)JKGX(aUdnn)mgNZn4Ok)SNtGOG2EvRRPU2U)1e7TFuA5a6bnULMb3c9YY4vc6hqW74SiOK(QFCYGOWFcIIjSVE(0gCMaX6ozUR03XJ64Cmgieui34DBPcbdeDMAQqTbfdgWXEwi2gGWaUf4KaKfy64wiOoHcI3)HB73Vpoi5i6yhEfQQhGFLrGol2KKW6F9n3DDVRE3vBkU9UI75WFY8cyNB7JOVj)9d

^^ That is just one of many that I have that were working before, np.  Guess it does appear to be an ACE3 issue with the patch?  But, making pretty much all of my WA's non functioning.  

EDIT:  Should mention that the icon/text triggers that are associated with all the WA's trigger for themselves.  Just the action to send chat on show, isn't.  And in this particular case the chat message on hide does work the first time it's called upon.

**Comment by Stanzilla** [comment]
That's a problem with the new block blizzard introduced, you can no longer send those messages in the outside world

**Comment by Obsurd** [comment]
"outside world" - referring to any/everywhere that isn't instanced?  Or something else and that this can some how still be accomplished?

I ask because I multibox and have a multitude of WA's like this.  They send chat on load/hide (in this case, mounted/not mounted), that notify me when one of my characters have done something -   Mount/Loot/Combat/Paragon Rep status, etc..  This method of loading/unloading the WAs based off of chat commands that are sent/read from a private channel ended up being the easiest and most simplistic generic way that I came up with doing it and keeping track of everyone.

Wasn't perfect, but really served it's purpose in only having to make 1 of each kind for each account, opposed to 1 of each kind for each character.

**Comment by Stanzilla** [comment]
Yeah, everything that is not instanced now requires a Hardware event for those messages

**Comment by emptyrivers** [comment]
FYI your use case would also be served by addon messages. https://wow.gamepedia.com/API_C_ChatInfo.SendAddonMessage

**Comment by Obsurd** [comment]
Thanks for the prompt response(s). 

So testing, they appear to still send to other channels (party/guild/officer) just the same.  Just can't get it to trigger off of the chat sent to officer like it does other channels and is supposed to.  Not sure what I'm missing there.

@emptyrivers - Yeah, I know.  Not entirely sure how to go about doing it.  Barely pieced together the stuff I have as it is with my limited knowledge.  Have been meaning to look into trying to figure out how to use the addon message, either with WA and/or the ease of taking the coding it produces and turning it into an addon of it's own if not possible.

**Comment by InfusOnWoW** [comment]
We still need to do a bit of work to make the error message better, so I'll reopen this.
