### ISSUE TITLE
Cost of Monk's Vivify Spell

### ISSUE THREAD

**Issue by aksiere** [WeakAuras/WeakAuras2#1735]
**Describe the bug**
Spell-cost of [Vivify](https://www.wowhead.com/spell=116670/vivify) should be equal to 30 as both specs (_Windwalker_/_Brewmaster_). But in reality this is true only for the _Windwalker_. For _Brewmaster_ spell-cost is equal to 0. 

**To Reproduce**
GetSpellPowerCost() to check cost of Vivify in both specs

**Comment by InfusOnWoW** [comment]
I fail to see what that has to do with WeakAuras?

**Comment by Stanzilla** [comment]
Wild guess, he used an overlay and it displayed wrong info?

**Comment by InfusOnWoW** [comment]
Maybe, I'm sure the reporter will enlighten us.

**Comment by aksiere** [comment]
yeah, sry.

I mean, when I use the spell-cost overlay on the progress bar for one of Monk's specs it doesn’t work ._.

pic.1 from Windwalker and pic.2 from Brewmaster while casting Vivify
![image](https://user-images.githubusercontent.com/33295331/65819635-7b323280-e227-11e9-91b4-06b2aeda6fa0.png)
![image](https://user-images.githubusercontent.com/33295331/65819649-b0d71b80-e227-11e9-962f-603df62d9a46.png)

**Comment by InfusOnWoW** [comment]
Please include the actual aura that shows the problem.

**Comment by aksiere** [comment]
e.g. [this ](https://wago.io/Ojmk-TxlX) & [this](https://wago.io/UniversalPowerBar)
in both i solved it with manually set spellcost for vivify, but in trigger-status-power-overlay cost doesnt work too

**Comment by InfusOnWoW** [comment]
These are custom auras, this is the bug tracker for the addon, not for each individual aura.
