### ISSUE TITLE
Castbar of specific unit disappears after reload ui

### ISSUE THREAD

**Issue by sMuve** [WeakAuras/WeakAuras2#1736]
**Describe the bug**
I want to have a cast bar of a specific player, which appears if he casts any spell. It works fine, but if I reload ui the castbar won't appear until I relog.

**Do you have an error log of what happened?**
No errors appears.

**To Reproduce**
Use the code attached at the end of the report

**Screenshots**
Not available

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes. The error is still the same.

**Which version of WeakAuras are you using?**
2.15.0

**Was it working in a previous version? If yes, which was the last good one?**
Did also bug in 2.14

**Additional context**
```DBX2Ujoo0VM9rQYfyc8iTnSGetGfNoB7QrHAsCaptig5KWu4H(TVNZXoCBKMTAFyFyLOPhF85(vN4MeNW2MWYWFay1oU(7)PmREtsKRJ98S88kr9ZjraI3mhsg1P7N8hmWpyWGEDd8g44KK3PRFc7Wzc6f41ZPRVha4663fjOBcJxMUrPNRKL1jShcJIdxy1ZcvnVwQkjfDfMpRYejSHpfpd4pfXurwBnxxdaGGYLLYQngya0GfGR1Y1RfAK8iYzTiqWMkXYuEvD8HDIKvqeOrB0pZ1Cz1orrbEtdkr2KIIMsU9kvJovmQGVUIyvSQjpNeeBC405JEAkOk6iyK1nvW)Bwj2lkRzaHY3sylFyilEjlE4cWuOBGWbynNuDQmxMUKu99jSs(wrLX)AL0CTGKeBE40PyedS2jzwIoBKpzLqtPvl8MA1nA5AkV40voT1wqPxEzC8NJo3y9uQatC7fXg(OmAuhOgdtyPQYLPQcL2KMWFE0xF6Bx8lLyRf6sEXxGekvN4r1tYTM02fveNYLlTjbbOci0yZjLQsbkWTCz5hN6t1yFm6bowX1p8p7wzIkOebKivfErl3lMoHMvleRT182IyspCGhqdlH)aXaIgVr8w9YQn8m1pE22jcS0wk2ScV3sLb832zp(bI)eD5kSgAKwE89x)JgEgy383Fn(ADFPx7qcZHeMZncZq9lTwAh3w8IIC7ictx)jvB6XIWqSb5EzLCvHaRBPZxnFzsuu4ILtdhf3o45KUCS0)TMQAz(HZZIoPkM8iuJ661Y6ZxWQgNmjIPqy0SOqmb4)Vlbu())eWIj)(4)dYaa0gHC9gy7tFhp3bbbb9D62Zh2sHlF6NWkuCApNSCTw1SJ2(1uulradg7WkCkgoVuBAjfPxskrrAbVQ6NWwHw8niRTn13xikZSRYE8rshdZqNxKjY(m)nuv)G29okWX)t9d6h46fawVlT7S3TCaZUao00SH4lNiyMOstYpNgBdU0W2kjAfM(Iv80VJ(Ez2VUOX5UENCLXYSmbu4gf(LtRVhBc9r(28AJguX9fYJh5A49f8IDB4uVWrLAlLcPfryzJkDF7iD4Lcoq(wcCmhMLF49xXLIV)69OBr65dmrnxdBlHv9qNbPrt1ZieRjqXEyryyKvGyueck5Y1TVFaTgAyCdAh92(Tf9p84GPWJCykTewIAFNW4zlM8xZIIhoLKqMS9PjTXP424WeC1vopv8v0DGYpWF(6tt6C(uhgzlyqbS1z7olkuyjmV7C7Dhya7bpQRh6Mj)9d```

**Comment by InfusOnWoW** [comment]
That's unsupported and that it works at all is surprising. I'll fix the tooltip to no longer claim that it works.
