### ISSUE TITLE
Custom Symbol not working on WA 2.15.0 WOW-Classic

### ISSUE THREAD

**Issue by cimba007** [WeakAuras/WeakAuras2#1740]
Switching from automatic symbols to custom does not present any icons in the upcoming list.

![image](https://user-images.githubusercontent.com/3453121/65816853-3dbaae80-e201-11e9-9c94-34f6eefdbb90.png)

2.15.0

dont'know

**Comment by InfusOnWoW** [comment]
You need to insert at least on character.
