### ISSUE TITLE
Multi target trigger

### ISSUE THREAD

**Issue by circuitj3rky** [WeakAuras/WeakAuras2#1741]
**Describe the bug**
Like you know, if you set up a progress bar for a debuff and set the unit as "target" the bar will hide if that debuff isn't on anything. When i select multitarget, for sap, because i dont want to track it for just my target the bar doesnt disappear. It stays on my screen without a duration and a full bar (which it doesnt have a sap target so it wouldn't have a duration anyway). It will track my sap just fine like i want it to my issue is that it won't disappear./ Setting it to load in combat only alleviates the issue when im not in combat but i'd rather not have a bar sitting there when i want to track important things.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**String**
[!nwvuVjooq4Fn7JTcNeAHt39qklCfjiWHZE72vvMAsCcEBijYXHc9H(B)MXobcuDsRuvWD84p)nZ8nJzewiJkzbexhxspgTIrDUL0)wy5ogng)dCOUsOwFKf0Rz5bZsETEBHArPwwKxbUPz0JlssQeA725rW2llK5WgJgheoEfaNOIRRvCT4bE0RPQI68y2g4E57eHIdWwc2dWzJAbLwP5kTf9ezUSARDnS0AfwRvY0uHcDpWeqngAOEaGTbu4EZH1n(rP8s80I9cKHpk4z6TWbqGP7QZ0s4YlfzztJBIUQ6ngNxQejYdaalhpB2zZ06eJ51J8PHRPH(RG7V9crAESuyzHdMi2aUhAm9O)Q5t(2m0N68ZC3eByMyVi0ACErSGfCduOqENh7NNMbgCVRhMq0cvop7FHebK7yboEynqUJJPYUzsAmwaaJRTmQsevKdXydbZlYfi(74Y8FFVpvB(98hoHQqBPgkwskWAWeL89pE5FQ5Xae8pEjm0KDxjsBudnLxqOSUAlpU4TF0k4inMXpm6xY)JpE5lLx46OIScLfd4gdCmFDnF9qJ6wVfzjnQw)VfUOvi)uhPTXVFvxPLjhpRTnbKrfZOblcg3gYqeyzL5yw0oX7BidBbmQdbjgcsmeKCfbT5QX5YuS2gDbUFIL7LvYnzg9Fh3AIVvt)7hd7GQvogGLOZgPY3bngXPnr8JRVcB69PZrKT(Uvit3QztUNCVJNJhXXXB4WEdjSKB8gchTiAFRuLqC7b4NvWnJBIY4vMEFBxytNa0jdPODB4AmyGoZOp5sfs1RmApPFmwUeXI458d4aNlJSivrPza3TEeCpLWoAQDKeLm4oYG(m6MttTUqoDBFRGc)1T5xp7VW9Jnas9fs4OTIOx7oQcfW75kjhlwuXHsPTlkucdVGDYQrwaP8cqv)N)Lb2T88uXzmTo1r)mXBqp3bUdVRNtFNb9DgcP((3DTOVeIDHsFSBCBdoncYva))05CgKRZq62QWoPsb))MRRhWugWMY0JBfGayPkrvLUn7FOJKdYp5XMbH0hMno4Rwri423v8sR9rZ8NVeudz8CT1Y0a60VcnK1s4jTJ7l)LZ0Y3DgmVlDpvRNItst4rIN9JJHI2ZFxWF1hMQv98YI3ekZY5Iyj)zRv8RlJ(MmgEajGmeEbfAwYk3YnL1ZV5n5ucgdzqmxIHjUg5vf8EKDiDZCDCUOcE)aejW4qdw2wWjOvBUIoA14XbFU2zQwtUF4aOWti98C6rgaViaca3ovWoJwarAImT9XvS1uyjPfnWAHscVYzNztFCXQP)CrqO)SMUNdTDpDMF2oz8Cs(84Ay79WVEo4s2)9]

**Screenshots**

I'm not sure how to include a screenshot but this is a tweet i made with it in it
https://twitter.com/Nibblerriffic/status/1178033635305369601?s=20  (the url function seems to redirect whatever link i put as a link to the issues section)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by emptyrivers** [comment]
This is a known limitation of the multi-target option on the buff trigger. You can use the "nameplate" option instead for more accuracy, but lower sensitivity.

**Comment by circuitj3rky** [comment]
alright, thanks for the help!
