### ISSUE TITLE
Focus casting in classic wow

### ISSUE THREAD

**Issue by Karnage1** [WeakAuras/WeakAuras2#1742]
**the buff Focus casting which appears due to the talent "eye of the storm" cant be found in the aura name section**

i dont have any error messages just spell name not found etc

**Comment by mrbuds** [comment]
I don't get exactly what is your issue but that doesn't look like a bug, if you need help to setup weakauras i suggest you ask first on discord https://discord.gg/wa2 in the channel #classic-auras-help

**Comment by Karnage1** [comment]
thanks i will go on there to see if i can find help.  the buff that appears will simply not log itself into the weak aura options for some reason and i cant figure out why
