### ISSUE TITLE
infinite loop started on game load - makes game impossible to play

### ISSUE THREAD

**Issue by YammYcoding** [WeakAuras/WeakAuras2#1743]
**Describe the bug**

on game load, it started looping forever, hanging the game and making it impossible to play

**Do you have an error log of what happened?**

Message: [string "--[==[ Error in 'Primary Power':'custom tex..."]:43: attempt to index field 'border' (a nil value)
Time: Sun Sep 29 14:59:55 2019
Count: 1
Stack: [string "--[==[ Error in 'Primary Power':'custom tex..."]:43: attempt to index field 'border' (a nil value)
[string "--[==[ Error in 'Primary Power':'custom tex..."]:43: in function <[string "--[==[ Error in 'Primary Power':'custom tex..."]:1>
[C]: in function `xpcall'
Interface\AddOns\WeakAuras\WeakAuras.lua:5832: in function `RunCustomTextFunc'
...nterface\AddOns\WeakAuras\SubRegionTypes\SubText.lua:225: in function `Update'
Interface\AddOns\WeakAuras\WeakAuras.lua:5608: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:5603>
Interface\AddOns\WeakAuras\WeakAuras.lua:5693: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:5660>
Interface\AddOns\WeakAuras\WeakAuras.lua:5777: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\GenericTrigger.lua:663: in function `ScanEventsInternal'
Interface\AddOns\WeakAuras\GenericTrigger.lua:619: in function `ScanEvents'
Interface\AddOns\WeakAuras\GenericTrigger.lua:1300: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:1298>

Locals: <none>

Message: [string "--[==[ Error in 'Primary Power':'custom tex..."]:43: attempt to index field 'border' (a nil value)
Time: Sun Sep 29 15:04:35 2019
Count: 11186
Stack: [string "--[==[ Error in 'Primary Power':'custom tex..."]:43: attempt to index field 'border' (a nil value)
[string "--[==[ Error in 'Primary Power':'custom tex..."]:43: in function <[string "--[==[ Error in 'Primary Power':'custom tex..."]:1>
[C]: in function `xpcall'
Interface\AddOns\WeakAuras\WeakAuras.lua:5832: in function `RunCustomTextFunc'
...nterface\AddOns\WeakAuras\SubRegionTypes\SubText.lua:247: in function `FrameTick'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:541: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:528>

Locals: <none>

-------------------------------------------------------
**To Reproduce**

**Was it working in a previous version? If yes, which was the last good one?**

it's beeing around 3 or 4 months i played and it was fine with no errors back then.

**Comment by SpatenLa** [comment]
Can you Provide your saved variables file?

**Comment by YammYcoding** [comment]
[WeakAuras.txt](https://github.com/WeakAuras/WeakAuras2/files/3667892/WeakAuras.txt)

**Comment by YammYcoding** [comment]
I now suspect of a custom aura with 'primary power' string on it:


!TZ1cZjoUY6)lCRTkyUjemjqs2ZmBvec5XSeGdMSzMBMaymcWtmwC8J8yV7KF7NULKF)cct2ZC2ARmtITSuRUB19NAj7wdLgoyO8YHYtX)bxATsX8(B0MAVyyhjXTDNnZIy)PHDQmuEMPYsISTPITcRcQuDQj0qB4shlB6YbKNGRN5yOARrnkw6Lp(Yy(p6uvf9xgBaeyNxgBQyCp8hnvQb8hvQJHn83PKjoZMn45vyvM6aDJg75KNwPXVzGgR5ogA2nvSSjMyRvmKTjk6Dn75yohFm2jR0vSjYlOp2JyArnu0HYTwr01VCkVnnwTs)5gqNG8H1julRtzDp7wK4N8CpDLNzDric2qhPLnWjxrNgtavDmnjg2nxOa8IfuXLkp5FJkLQpL(iWWkM2bU)uFHvLvzG09H(lg5xrFKyk0qExdJiAgZFz8hEz81GMPNB5flSIjbfIpoaQcvwdoNyldxRPOR97mw4sJz0IXkTyPa0W)QD3fhDujRW68Y4zuZxg3NaSZehwjEvuBMxFcD6Hvaf4csGN7(tEY3Xq5fUOB7ppQx3BA1VGpfi6wKW9s161EzmYrblQE8Io81YmhImJC3RBps(Ig9pvUquceG7mMMK(tmAysMZ0FanvalHreJhklklAvNOyYQh)XLXBt0gPjyesmdtsRfutBIrhNLtiMf9mv8mt2XtilvkzQ2xB(cBgrluib5GvN2KzEvjAf(k7bsPQiSb8dV2lerSSeROpZ4wtWN0moTZ2CTNj1MOML1kAZKSbY3zNDF)rDDbzkwB)6vQukfBZadYRB7qrdQlcKcWZJ3ncB(Y4F5LXP6DgQZ9v)wmxIYG6CPIDXc)uzPzf2Pye6()gxbW6EpMPuPYLlyviEVg23jQVjhwiJkeWHnfKJK9nrJfyMplHpNcul4k17NBctxnfLgyYV44)HD5yoyNOy2eR8Tr4P7s1pycJkv8lhyHFwMy)BeWb(jgXkQw2Ch1YZH)pP06zQFIj5XLSPnHR1brH6admnPlNqdB7FtJrWWccqGtq6JpuisRGjwsZZil1qHRA0PrH7I3kxqnQ5uctEpb6UPM0vNWkjb5oe8)RKGv2b(Puy7Hy6tyaO8K5jmgSxvKBy)EYEvlLTLedlBCrbUboTcXuLFfZ(cWpkfEOiOD(hYW1mkEqY(KzI5VN3tVs5PeNu4DsaMc4L(t579G8EE0daBWzdQujBPk0KozpkLgeUuLQRRIRW6GmC7TR70lZmjemEtlC4h0)lO6pdJ2NA6OHbIsSvlTM(EDxcS)ykuLM6kMA2pJEFyxKAlUIcnXEZAJSZ0Py)CkLUmD37mz01JeU)8DyfbSXT1LDsLrqzI1VI4cZJXtZakW9GRYlJFQAH0jsIZTf00oUjEA2T)H6SzvQG)Vq5YHzI)WSWAhs6D3LM7Kb1MJdQYO7agwwY6OO16d8zWAAsG4CoJAyZNaSOHgUwQcD)Tw9B34ZfWRphShWACb41RJE(jnMfM(iQ8naG(nMkRkotbMjOukIzGOhdO6IYTrfE3OsX(bRrrV4ClXD6B9PETA)YyyraxX9Pd3wExfU18YkfUImKUW1JvuP0OxpQMHDX46NcnB1zaeKZojQ62zJAqLKkZVOu5nCqSONQ7CrbLsP(WcRlMZKNSTJWY)jpUqtNWeOBlWEgy3)viMQP0eL6Gv6NVqBkPycgw8fO8vw4QsB0Kn(RYc7LEulneE6KNX1rFlot0DP5SWMNqJVYiW85)zDOusYys(Q(cT2DRlGM3weanmIRlAx6ysC9BB0FWnD7)Rfk9pYNQmYH2fNAQ8yBeBUOx7bAT)6qJyc0hCzZmbyZflnf676jIsCHlr70zkQKV8LgtN21W6lF5gIY94KnWLxrMQP8LViQnuG8)YrXKm6MfA2KY2ZvYAMNe6w2MWvuQSuwQLeA3feeVOiIOnBo60jkO0gsNt0bfhSUuqWB0U3fn(1wFUWgsIGXjdyiJD)V0gOjAQtumBORZW5SkUz6qo4yH2ToBaAHXa(g7DlQJqfextxApm023LVR3TA3vSekjzWlBaxgf2lbx51KNYz9b5XjPbiMBGkHNOf(1q5N57zmBlJvmuxqnzdfdL5tYmuMVEm31InuUL(dxFjBnPg3pugImEOS(1pE1V2q9F(VOwInIUp1MfXhJS(B381RMcatqRC)RP(q5f22RS(5927rL50YA09Cx)5E1boITzpwS97g3Ac((xptZqZAb)A4sSurNa8sWfLhzd647aNpKB5tKJoeiAo(aemnzOuVqGomWGWjYODmZfYT6s7W(jwLAOVAHsXkrkpI5fN7(aJx(iB8cljiUriid(JlRyOTKZ6yL5CFdOm2OX5MuNvyFiKYqvM10OTaquqEfbezpgdvWKUuiaLRfO8buFXYTm3npksvLxsP2lWykl096biXxqP3BrGLAtW3hrXjOwMBS0ZKohaPTqyGKExfb9(MuELj5bnQJ1VPO7qsY5wSYD7fLvMyvCs5h4vC3ynU0EtkdRWNVhBLLe2jzaxi0P60hfQubP)Le4l((tfTum0c3MLx3mvB2mw)eqwIqUD9OwwqXmZK1h5wyckGRh0TNleni3Cn27MeaPENkRbX41fLOeOqoTNB1IV8NKy7ebcJPO(qcQDwlrk(XeFTj05yd57g3yUAd0b3OycdpqCyYuhymsEHI5uS8ROgqHnxObUaUisQyBVcnW(qYg2UBtpBPXYBZRaYngrcSE9Pm01O7yjBZRc2rbFJmXFq90EqQVDMO99HjhUEKzKnjamQrA7nvaAk2OKkcGs(G2skysPrMI7RdfW5CNNzUM9cNj4aWEGEBbzVhPpURJ2UwuhtvYEt0Pt2tx7bYENHVb1pDvB2ETXUPSUJsGXWq7uktU())2)iTN7TtQS6bchFqOC1AGfYCXnhG3i2q5Y1HaeYIE9BCERO0tQCLkbOh7MjE3Kn9oRBZRLZHG1csWQ1YMGT60Q)5FoUiFuqr(OGu8GCOyZUxDs3r96EzNb5XPhxpiDLYrvEDNwYXz0APk61QKlbVSP4TxeJSH4ZJQ6rwPChIc(cmZMB3VAqUnh1A7R70OFAC7(Hucbj7X5WTbEdoXO6XbTboUYgy2FvJwTLh0V7v5OydmELVI9YoYn6C5GpNJ4hYF6W8mwV4YmzrPnJCn63SrNwJAcJ(NNKXQuOH)ABGWF219tqWRNQGFuo0RxJl7KGxFL086DPxakMW6NeaS5vTBLQCGxFJZdCoS4Eyb)bMv6wP7sDA3itAoNA(C2Bz95SACMJP721dlsivYzdRlsFL30Gj8kEK8NllfAOsT47slawMyyWCEo7Lw6re(fGAQ4b1EhcPVUHrfuIyukOSTRGWFm)LBJCSGi8xNnl4yrjV)dPn7VuUVSc3Oh4KA9ek32uju8jb2u1BR(xctNJR83MoVzMoj92BatOVHfLjYv1AvcHCDIon4xTwcWwR9MAf4t6lBBYUwwaE5ZRJfP4nJNPnz9ThoJZZBQnzTxRTyyPkvRXxPTx9FyGT(BtN)CmDEx1)R34z))245)ugp7)FPgpEgeSz98(0zTD3XRK5XJ9h1YCIYddppzIFfZBZSLOkwApx2998pd21t552m8ZV6hb0BuuQ(6eLQVfIY(BNOS)Rtu2)Tquoy7eLdEDIYbF)eLuzZBRTDIwTxNOv7pdrR(2jA1FDIw93qr7BbVX91gysTB6)LRc35I8M2hFEMaU1RhcWnPVd)ThV1Jl3qaxr7(XcX91jmvFteMTgZ91jm7)MimBnQ7Rtyo47OWKkd)TKkm7TmO(rH3Ya)0gyJ2UtpXeINCV0cpB)sHf(nFRX8SZRTXDZ3YvtCCinXnAgtFur)(xRMO2gQjwhoSwioSXSz6AF3rrJ9gMrs8(ncqnbs8Jf46wlJvFZLXTgZDRLX9FZLXTgkERLXdEJKX3WiJ3AzU2F6Y8whY8wlZ1FdLzF58WTtopC7LZdFZKtFP8OTtkpA7LYJ(tqkpE7KYJ3EP843C)0WR8lNypeoXRrekySjNswsnO605pNlHpCdjSLTPJBupFm58Dp8qNbRSiPENnEMj4(KXV8hywvXVTqAdqg(02MYVjoTdnu49Pc720KjSyKAnpabuMnt7jILisW4z3ts51tH7tS0Ljw6KGL(T84erw(h9ztfFWfvIFSG4Suk8NEAmLOiBF410pVrzBuTOtFpM8mUAIKYqgVUHFXEcIe)l61tiexfpBGcN7p8A9lz4j7k7vt)9z4SSQpZfRw(YFvx5p70aki9Qke20RTl)X(7UHe30)A)dztlmNFFgjHGN(F3WYykg3UOvXYL5cLld8z5YfMbxjgXVL9372H3lLePIWu6iXxX)jdTXVTFGuZNtmXp))oSJ)grb4LUjy6qzPHYZjgetnv8tOVluIf7Vna0JhidLX3JJfpzb8tr1HYx0QDVZUUnqu2TU5pa)VJ4fAzRy7ynu2XImcphBagt2Yzc5bIHTSdkddLh1SH8GrYdA0h4k2tgkZwWOFv7zsyvvUxR2TD7It9eGS(6F)r4iK5n(0Y5VpHAw3tOM1nTG)l0rNclrVd19CM1Ndw7T1yhPDGipiBy0xr7Cy2LIS)L5bZsjggE8ZqLsrvEH5OCWwZ8eHyN8obhespdQ1XqGuP4yt9b)cfTCSUpy7baryMFQ5emVdryr1fe17dKzxiAPmNjWCcJDyEjqHzDnGQEDNlhWD8WsDm8r3zO)t1S(kJFqqCfDDE2G9azaVASoUZUsvyzbMk1yK7jCgmxb(VQSFVp73hG)MLTy2etdf9FdMvHLEAvpyO8tHsborMpfmLZ8MSXDAbwMhy5o1Hb1GGeFPIgRzbkLFQR1NDaSLgryvHpN0kha2H9r0cphaDjpZAPcMyv8uPdFwdwHp7xWj(hWBNZU8j)NDgOchk7L(YUdWRePvfEAoGjY8C8xtWFPG)Ye)mVNZ(wVXFPunIRPxcKnxN7p7rWxg)o25XW7eXhUsJ7GuuChZXifYzqESNhzqIYBKLMrrwpvIhCxP9Qgn9wDnrnL4EOHOeWkfnRY4ctPsL2jnSI5P1458gppRgpjTgpH34jz1yL0AScVXksLsAjkdLnX8SKWgTz2lpXg(rVtUZWjHsxY1ZogAXer2EEPXzMuaMycAmzmtBo3bEI4l9oKVwfMVwfFFnlBn17F2lmNjIudfwaieuLjY2tIKTOmxA5gxpO7q5hC9qRZIJQplbodejiJJXvpcmZi4)qpcCb(eYt2JSwOaaVFY1XwYTbaLSzh7HSAXV8Nuf3Ug4hS6ndvjYTEAfoo9OYZH6ZGkMkjRycu7p7YH7k5worFMidC5kcwPpOzPnrNb06XcCiJUxpO9LDAjkpug8EzNoT6pQ)LNFXa3C79ZbG6yn4RaYV2SN9t3xpYlR97GH1XUT8tbAj3QJF(r2Pl052Oi(Q09g)Lw3Jjh5Rw1lvFD19h8609w)vv33SBNrUk13A7(AOUNNJ8JS4JBE3ZPadV0RmQ)qJOe181CIAgqBikHmDoOlGzp6blRwpWOn)5C08fSCehOCfoYo)qXl0aw59pUQuT6hvV6HhutGNhTS9tOSdWYQHDIovHDS0IZ9SIyprX2wNHWJfGrBAI3ydZrzWcPAPJUTMBOEyDEGSqtvxmParnwDu1vSSIvkNGvJvoMnXAQqjph7rMkQKS4GR1qEyg)Ohiwfx9WQuectQEC6clUdt6(yLZmvIuOTy6qVZZJHYN0UvNt9NpEnCYqt4Z0vMBfWfbJoMPx99XCn7zD4vAMMu24Z0WtoZYtF3isedMnMI(oKPKPxPXOk)SvyqWjKDTpDJF4KqNpXFM5mXcz3sdLsXuu4rjrpti(BmhueBHs4ou5jVygUiGrTn)8wi6ztXJIdh5JCpEKh4wp)ZhgXXdJ)Pdd)WHX7SHj4rddQaxIgYYsLRug7xQQxykhvPALAU8MgEkMbJEDhCbBjwakq3vUNKf2Eb0l5cYWsUyUguUz)wT6iwyMREl7XD(kGmqwHenmlwbutnWGvSBtx0T)L)FD7mOrBwqDt1cWx)ofwfilysKeqtrtYHYvllvRmWSpamWbvrZSH)7p

**Comment by YammYcoding** [comment]
This was an aura to display player current life and mana, etc on screen. Apparentelly something changed from last versions when it worked until now.

**Comment by SpatenLa** [comment]
yes, and that aura needs to be purged of this world. even before that it was rather badly made

**Comment by emptyrivers** [comment]
While that's putting it somewhat strongly, yes the correct action is to remove or update the aura. The things that changed from previous versions to make that aura not properly work anymore are not things which were intended for users to use like that aura does.

**Comment by YammYcoding** [comment]
hmm so we cannot see the life and mana, bla power, like this anymore? :( no aura to substitute this ?

**Comment by YammYcoding** [comment]
i deleted it and error is gone. that was it. thank you man! :)

i just found a new one at: https://wago.io/UniversalPowerBar
