### ISSUE TITLE
auras break on classic when you get a new spell rank

### ISSUE THREAD

**Issue by teyasio** [WeakAuras/WeakAuras2#1745]
**Describe the bug**

Expecting the aura to keep working after its new spell rank

**Do you have an error log of what happened?**
no errors

**To Reproduce**
1. Make any aura of a spell
1.1 Type of aura is Cooldown progress spell
2. Wait until you get a new rank of that spell
3. The aura should stop working after the new rank

**Which version of WeakAuras are you using?**
2.15.1

**Comment by InfusOnWoW** [comment]
@mrbuds I think it should be enough to call "WeakAuras.CheckCooldownReady" on level up.

I think that might be best done in InitCooldownReady in the "SPELLS_CHANGED" code path.

**Comment by InfusOnWoW** [comment]
That should hopefully fix it for the next release. We can't really test that easily.
