### ISSUE TITLE
Weak auras Set Role?

### ISSUE THREAD

**Issue by magnussonn** [WeakAuras/WeakAuras2#1746]
Was wondering if you were going to add a load > Set Role Tank/Dps/Healer like live? Would help alot thanks

**Comment by SpatenLa** [comment]
from what information? there is no role in classic. there are no specs in classic

**Comment by magnussonn** [comment]
Sorry meant Specialization Protection like taunt, shield block etc

**Comment by mrbuds** [comment]
There is no API on classic for that sorry
