### ISSUE TITLE
WA isn't working with LibClassicCasterino

### ISSUE THREAD

**Issue by bgfds** [WeakAuras/WeakAuras2#1752]
Auras are not being cleared on "UNIT_SPELLCAST_FAILED", instead the aura will remain active after being told by LibClassicCasterino that the unit isn't casting.

**Comment by bgfds** [comment]
The author of the Lib pointed me to https://github.com/WeakAuras/WeakAuras2/blob/50d3fed8721b5b9efc9470c9152d96ae9f9ac67f/WeakAuras/Prototypes.lua#L5222 and said it might have something to do with this, but adding 
            or event == "UNIT_SPELLCAST_FAILED"

doesn't fix the issue

**Comment by bgfds** [comment]
https://streamable.com/qu5zs

**Comment by mrbuds** [comment]
My tests show there is no CLEU event matching UNIT_SPELLCAST_INTERRUPTED
But LibClassicCasterino has a workaround for testing if cast was interrupted by checking GetUnitSpeed on enemy players every frames.
My tests on friendly players doesn't work but friendly units are not supported from what i understand of the lib code (this could be fixed), sadly i don't have 2 accounts to test this with players from both faction.

**Comment by bgfds** [comment]
I am alliance in my video, testing on a horde second account. LibClassicCasterino works with the creators own addon NugCast, I've already discussed this with him because initially I thought it was an issue on the Libs end. I tested v17, 19 and 20 of the Lib with WA, all of which work with NugCast. None work with WA.

All other castbars are also using this "hack" of GetUnitSpeed and have it working.

**Comment by mrbuds** [comment]
I don't see areason it work with nugcast and not with weakauras.
I need find someone to test this with.

**Comment by d87** [comment]
I did some testing. Issue is that not all cast event are added into internal_events here
https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/Prototypes.lua#L5181
Everything other than these 3 gets filtered out

**Comment by mrbuds** [comment]
Yup i could properly test this with a friend this morning and made a proper fix.
