### ISSUE TITLE
Weak Auras 2 - error while eating food

### ISSUE THREAD

**Issue by kiwaczeek** [WeakAuras/WeakAuras2#1755]
**Describe the bug**
Every time when any of my characters start eating, i get this LUA errors 

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'UNKNOWN()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: ?
[C]: ?
WeakAuras\WeakAuras-2.15.2.lua:4380: in function <WeakAuras\WeakAuras.lua:4380>
[C]: in function `pcall'
WeakAuras\WeakAuras-2.15.2.lua:4380: in function `HandleChatAction'
WeakAuras\WeakAuras-2.15.2.lua:4399: in function `PerformActions'
...aceWeakAuras\RegionTypes\RegionPrototype.lua:736: in function `Expand'
WeakAuras\WeakAuras-2.15.2.lua:5613: in function <WeakAuras\WeakAuras.lua:5603>
WeakAuras\WeakAuras-2.15.2.lua:5693: in function <WeakAuras\WeakAuras.lua:5660>
WeakAuras\WeakAuras-2.15.2.lua:5777: in function `UpdatedTriggerState'
WeakAuras\BuffTrigger.lua:823: in function `ScanAuras'
WeakAuras\BuffTrigger.lua:1358: in function <WeakAuras\BuffTrigger.lua:1354>

Could You please take a look and maybe find a fix for this ?:) 

Best Regards 

*

**Comment by InfusOnWoW** [comment]
This is caused by a change Blizzard did in 8.2.5, but didn't bother to put on the PTR nor into the patch notes. Addons can no longer send say messages outside of instances, thus any aura that tries puts out a error. That error is tracked in https://github.com/WeakAuras/WeakAuras2/issues/1733.
