### ISSUE TITLE
A couple of ideas for future improvements to bufftrigger2

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#1756]
These are low impact but they come up occasionally:

- [x] Black-listing, not just white-listing.
  * Currently we can get "all buffs" or "some specific things". Would be nice to get everything *but* the matches.  
- ~~Remaining < #  and include missing~~
  * ~~It's common to want to trigger when an aura is low or missing and currently requires 2 triggers.~~
- [x] Total duration
  * IIRC infinite buffs have a 0 duration so show up in Remaining < 5 checks. 
  * Currently people end up using workarounds with Conditions
- [ ] Group member names as well as units
- ~~Maybe some broader UnitIsUnit functionality to allow some limited use of targettarget and other "secondary" unitIDs.~~ 

- ~~When tracking unaffected (using Fetch Affected/Unaffected or by cloning unaffected) remove dead units~~

- [x] Expand Group Role to classes

- [x] Party
- [x] %totalStackCount
- ~~unit = group & auto-clone, having a unique property "number" (?) from 1 to %unitCount for each state when multiple units have same buff/debuff~~

**Comment by asaka-wa** [comment]
Additional:

* When tracking unaffected (using Fetch Affected/Unaffected or by cloning unaffected) remove dead units
  * And those not in the same zone?
* Expand Group Role to classes

**Comment by InfusOnWoW** [comment]
"Remaining < # and include missing" can't be implemented due to how the buff trigger works.
TargetTarget is afaik not implementable because there are no UNIT_AURA events for that, iirc.
Group member names is not something I want to support.

The rest look fine.

**Comment by mrbuds** [comment]
For classic there are some case where you would want to check if player is in same group, like warrior's battle shout, or shaman's totem that cleanse poisons only in your group.

**Comment by asaka-wa** [comment]
Feel free to split this to a new ticket (or tell me to do so) if this ticket is already too far progressed to have stuff added, or if it's just not perfectly relevant to this ticket.

We get quite a lot of call for showing stacks as progress. This would, of course, require manually inputting the max value but I think it might actually get used a bit if the setting were added.

**Comment by InfusOnWoW** [comment]
I think we have a ticket for that already.

**Comment by InfusOnWoW** [comment]
That one https://github.com/WeakAuras/WeakAuras2/issues/1445

**Comment by asaka-wa** [comment]
Ah, perfect!

**Comment by asaka-wa** [comment]
%totalStackCount (or similar) 

Occasionally people want to not just see the number of affected units, but be able to actually sum the total number of stacks across all those affected units. The example I usually see is DK diseases.

**Comment by mrbuds** [comment]
An idea with unit = group & auto-clone, having a unique property "number" (?) from 1 to %unitCount for each state when multiple units have same buff/debuff
That would allow using conditions for setting different colors and/or raid markers for each unit.

**Comment by emptyrivers** [comment]
Can we please not tack on new requests to old tickets?

Additionally, can we confirm which requests have been implemented, which won't be implemented, and which ones are planned, so that we don't have a perpetual zombie ticket that nobody knows what to do with? @InfusOnWoW @mrbuds @asaka-wa

**Comment by InfusOnWoW** [comment]
Indeed I'll clean this up now.

**Comment by asaka-wa** [comment]
Can Unaffected include only living units, or a setting be provided to specify that?

**Comment by InfusOnWoW** [comment]
That's not easy to do, open a new ticket for that please.
