### ISSUE TITLE
Retail AddOn on Twitch is the Classic Version ?

### ISSUE THREAD

**Issue by Faritass** [WeakAuras/WeakAuras2#1757]
So, I was browsing Twitch, looking for my updates, and after I installed them, WeakAuras stopped functionning on Retail WoW, because apparently, even when I chose "Retail", the version I get is the "2.15.2 Classic".
Any idea on how to fix it without losing everything I have already ?

**Comment by Stanzilla** [comment]
You can just install the correct version manually, the data will be intact.

@zeldokavira

**Comment by Netherling** [comment]
Dumb question. Same problem. How do I install it manually?

**Comment by Netherling** [comment]
Nvm I seem to have figured that part out. Now on twitch under file it still lists classic tho some reason and says update available. If I update, will it replace with classic??

**Comment by Jubolum** [comment]
Hello,   I have tried unistalling it, and the only weak auras option I have is the classic zip version.   I have checked that I am set to retail.    Can you help with this .  I am using twitch .

**Comment by emptyrivers** [comment]
https://github.com/WeakAuras/WeakAuras2/releases/download/2.15.2/WeakAuras-2.15.2.zip here is the retail version.

**Comment by Jubolum** [comment]
So how do I install this?   I use twitch because I don't understand a lot of this  .

**Comment by InfusOnWoW** [comment]
Download the zip and put it into WoW\__retail__\Interface\Addons

**Comment by user004** [comment]
Why is the Classic version being added? Is this a WA bug or a Twitch bug?

**Comment by InfusOnWoW** [comment]
A twitch bug.

**Comment by user004** [comment]
Shoot! Well thanks for the update and for the work on this addon :)

**Comment by Jubolum** [comment]
THis zip still reports missing dependency.

**Comment by Stanzilla** [comment]
which ones?

**Comment by Jubolum** [comment]
I am receiveing it from the  wow interface  weak auras and weak aura options,    but its there when I download and paste it in .   Ive deleted all weak auras in interface> add ons   and then re installed all over  but still receive same dependency  error

**Comment by Stanzilla** [comment]
we need the error message

**Comment by Jubolum** [comment]
dang  im   stuck the only wa im seeing it is on the add on menu in wow .  let me look  further

**Comment by Jubolum** [comment]
interface/Addons/Weakauras/GEnericTrigger.lau:762:attemptto call field 'Preshowmodels'(a nilvalue)  

This is one one the 8 lau errors

**Comment by Stanzilla** [comment]
Sounds like you still downloaded the wrong version

**Comment by Jubolum** [comment]
ok   ill re do it ty

**Comment by Jubolum** [comment]
ty  that  did it   !
