### ISSUE TITLE
Animating Progress Texture

### ISSUE THREAD

**Issue by anhls** [WeakAuras/WeakAuras2#1758]
**Describe the bug**

The Progress texture animate weirdly when anchored to Personal Resource Bar
**Do you have an error log of what happened?**
There's no error or whatsoever, just the texture behaves weirdly

**Screenshots**
https://imgur.com/a/6mBd47A -> When not anchored
 https://imgur.com/a/hQmcpa1 -> When being anchored

Link to texture file I used: https://bit.ly/2XCSDRR

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Tested

**Which version of WeakAuras are you using?**
2.15.2

**Was it working in a previous version? If yes, which was the last good one?**
Havent tested yet, I'm afraid to mess up the current aura set up

**Comment by anhls** [comment]
Update: fixed by enabling the PRB option in interface, you can change the alpha of it later by some CVar

**Comment by InfusOnWoW** [comment]
The link you posted went to a .pdf that didn't seem relevant, so I removed that link,

**Comment by anhls** [comment]
Yea, sorry about that. I found the fix for it already also, so all good.
Goodluck team!

*Best Regards,*


*Tuan Anh (Mr.)*M. +84 913 044 366
anhlsls1@gmail.com



*Graphic DesignerSaatchi&Saatchi Vietnam*



Vào Th 7, 12 thg 10, 2019 vào lúc 20:16 InfusOnWoW <
notifications@github.com> đã viết:
