### ISSUE TITLE
Classic: Trigger->Status->Swingtimer is bugged for all Fury Warriors because of the Flurry talent

### ISSUE THREAD

**Issue by MassMania** [WeakAuras/WeakAuras2#1759]
**Describe the bug**
I expected the Swingtimer trigger to speed up or down, depending on Flurry https://classic.wowhead.com/spell=12974/flurry aura GAIN or LOSS. It does not always work.
It works fine when the Flurry aura stays constant the entire Autoswing.

These are the scenarios where the bug occurs, the Player has a 4sec speed weapon for the example:

1. Player has no Flurry aura.
2. Player autoattacks, the Swingtimer is 4sec, everything is fine.
3. Player uses Bloodthirst right after the autoattack and the ability Crits proccing Flurry.
4. The Swingtimer SHOULD now recalculate the time until next swing, because it's 30% faster now.
5. The Swingtimer does not get recalculated, it stays at 4sec and is displaying the wrong time.

The same thing happens if Flurry is UP, and the player uses an ability that does not crit, and uses the last stack of Flurry.

Basically, every time Flurry is GAINED or LOST in between autoattacks, the Swingtimer is wrong.

**To Reproduce**
1. Have a Fury Warrior with Flurry talented (like all do)
2. Equip a big slow 2hander (makes it easier to spot the bug)
3. Make a WeakAura using the Swingtimer trigger
4. Attack something
5. Watch how the Swingtimer is wrong, every time Flurry is GAINED or LOST in between swings

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.15.2

**Was it working in a previous version? If yes, which was the last good one?**
I don't thing Swingtimer ever worked properly for Flurry? I do not know, didn't use the Trigger until today.

Just linking the temporary Swingtimer I made. The problem should be present with any Swingtimer on a Fury Warrior.

```!Lwv3YPYnm4NOs4NKt7P3riKP0dHqXBBANjJjM1AxCZI9wBVbixKN9kjVBcC6f90PZWywllRF(0NKLdKzsHrUyWORgn8Zsrqkg2BWv9gkf7Kcn9dvOja(1hLl6lfLvU9YnTIoWIunXTo)91rJZgq1JsXX7lkcqmDSnhpEPZyXdMmDr20vOFu7Gm4qSXdYRrR5RKITXyD4hV4I9QsxpJ7cH6y4l3Dv4txmaTsEN5fHOYht(Xyn0xI8Mq0HbmgVU1TB2qkuGAe2YkJ7EgG6XHAipUsHMJYJauv8vXMgckmWurGuW7IKUwoxkCKI36nV(2t)sJsJkPE7PmmcQCQoOADUB3gvKYR8kvGJ5DnvrtxyqrW)uO5v4RfIIJjq6bVQ(oNgWOC(47w2ccJTLvW7LLSTM8NTa6Wfd4azS(prOa0G(oJLZfOeZKSJ1ODQ9UspQCRdKInvGvN8X1ZNU4g0hvkBmjz2cXSBMkfV6qKTTOZ4x0L)c4dmanyWO(iXrvvVvXXafv)XjuHCNTWuMkDAtOUsDCgkdnVnc(cvo84yT(EB4Xha1ZJXAq4X7aTr9ylxj84eJpVcw)WwtKIzv(ZLExJvFMxQCE0jyeq)gYRJ41lP14PL4RF3cu2K7CvA3ERyVPMjMDcMQlz2Whx8whIMVFreTPKDc7ACpcLTfNrFQpXtX8ZQQ(ToOA4Lj053pRrXSlr1oHKlIC1Y6S4QM8mQW6KWaGGNoq1sGmcwWmAOckyMZoLX(F2a1gVcR666MQaCwd03IDy)(bDapOzZkMZ1oxylyk3Iz7GH)qk)NBqcRCr7UB9WF1a2CAutVHxL63euJbEJKkICfHQOT3z8(ey3vKisYnMGczY6uXZQnNmv6WjGDJbhU98QBk(8QFU(lVCSTfItNnnXOZEpMiibnDWK)Do15nCQduKT3OJBBt3p4QNAS(SX6ZgRpBS(9UImhJoGTKVF)tVE3CZZ7ACN11S0Th88NP(NKuADeHQDu3VH0YqnOiys414WEJT8TNWAr0BklXkD6YzVlGFpjc7wGd4tanoq0yjsb3a1qtSfuNpQlF4wKUroG)pXAX2SnnffPQXpnD(YB)15DeqSXi2eyQf8cG0durZbPy9KXIS1ISXRANcJujtDDIjWbrxuH7T4)TKc6ioOornbeNX3dNuxvnt3QAePE22xEyFlfIeGKz2rPtxmT0dCmjwoD(CkNB1MhA(EZJuK4n2pGoUbIEQ7filjKh)U47qga1m6X4grA8vhUfi906TK0ewjMSA60fNwH))rw(EKTK7D18J)9UCanjlvk52RD0CJavwDEdMHTP1K53p5lpmtmT9Yh6UCxJkDBIFFTZRbF6L6xWm6YHeIi)7) ```

**Comment by mrbuds** [comment]
I don't have a warrior with enough talent points to test it on classic, but i tried to fix that on retail.
Can you test replacing Interface/AddOns/WeakAuras/GenericTrigger.lua with this version ?

[GenericTrigger.zip](https://github.com/WeakAuras/WeakAuras2/files/3719392/GenericTrigger.zip)

**Comment by MassMania** [comment]
Tried hitting the immortal mobs in Blasted Lands for 10mins and the Flurry issue SEEMS to be fixed, at least with a big 2hander. I didn't test dual wielding.

There's still some occasional weirdness going on though. Maybe because of Parry-Haste? I'm not sure how accurate information like this is: https://vanilla-wow.fandom.com/wiki/Parry

**Comment by mrbuds** [comment]
Parry haste is handled already

**Comment by MassMania** [comment]
I should of course have been more precise than "weirdness".

When the immortal mobs get below 1% hp they just stand still, essentially becoming Target Dummies (which don't exist in Classic otherwise).

So when hitting a target dummy, the Swingtimer should go from 0-100% repeated uninterrupted correct?

But sometimes the Swingtimer stays unactivated for around 0.3sec, in between autoswings. And sometimes it starts the autoattack new cycle early, before the old one got all the way to 100%.

**Comment by mrbuds** [comment]
What is called parry haste is when you parry an attack your next swing will be earlier, which is handled by the swing timer trigger pretty well afaik.
But what you are describing means my change with attack speed modifiers is not working well.

**Comment by mrbuds** [comment]
I made another version which seems to fit better, but i see sometime it act a bit weird when speed is going down, i could  test it only on retail, and offhand speed modification should be handled now.

[GenericTrigger.zip](https://github.com/WeakAuras/WeakAuras2/files/3720062/GenericTrigger.zip)
