### ISSUE TITLE
Classic Item Equipped Ammo

### ISSUE THREAD

**Issue by Sinestessia** [WeakAuras/WeakAuras2#1762]
WA 2.15.2 isnt recognizing ammo as equipped. However it does track any other item.

I do switch between ammo types between bosses in Raid, so I wanted to have a reminder of what Im using at the moment.

String: `!vwvuZjUnq4Fn9XMb7KCnVcPMgMbSPiNBU(IicBzBDXiXzjdH8q(T3DxzdgUEZDDcJJL0QD)2V9BxZd4PCMIhhC79F6tbCMLZcVj4(Bc5STCwo(dmOS2CGVHZElPOWkD84Fpy0io7y)s4DHoRY0S0O0oo7XO40OvCwMXuNBoOzhu7K8jN3ikVuIouLz04(UgvzPSXcblMGu3ge6CYTXITs4KGWhUhGKCtBrr6rWLSNIMVC6ZZbG3UrUxQDm4i1BC26hhZsxZshVk98HlBK0HSLrZH7K32iCkabmiZjd4Szq0(4LOV1Q2Ttc5VgImcl4OwRCDRw5qa3Q7Sx06mqa2jRRNLpWWtOEIFn4fRWN0Kpy7QfhHeK5O8W6eUwG8XmJvzoKaGYs)FCMtTxsUvFMvCWFXHxXudb4LU9hqaxLf)ak4cA67YTlsMgPOMHCHVGnYBV90otUMQ()xlhuqgOmEy0DHD(Up0)hmglxz)AR2ZOGK9i8GwK6nBHjxsIBY7ANSrlQ)mOlXSpo8oo7vPC3yimzUviNGLtHwT1ZpPeH34Wx6jT1DfcjO0HKURUOnAQKUvO0)6wxO0kB1VS9e9Abbaylj8W24hn1MgFBg(lKEEl98o8PJO)vYsW7dAhLV5wBReqV7xg003f92n45Dw5F93SDlZ(5XJSRWGsVPnQ3)4L)UvKdyw8XlPxg7HGFe5SrKZgDLZ8w)pdrkTTSUOBc14Ntt62DVYQ2utAZtiXlitEoD(S4OU9Vyc3S44OvRNKKMMSy1S)6P0(jGFxq)AR1PkoEEOyJbAkLPenfNGU3FZVC9nrGWuVJY7qF5SsQkRalUf061grEFtFwTWA7AUYWn32w7u9IE)PO4uPlRXgTN9i5cRSyKU6QoVMzAJ8BTsD2raB3ectGDMS99Dfbb3ok0BNN1206CgDcyamuO7Gkv2RAyciwK6s3PnqFk9GZwsJp6w0qApVVOVpqUyi7CqL7Q8SaK9Nv1B8TZEH7PwXHnouBTYDIz(5IZwfmbSEX0dVvQQ(Jp)eN9UXSLGbg4HL7(pUHL2)uzfGOkNWeoCDI3EwMOwsSa63XnnWhwzI6DvcAZcKcGr6G4)AQYtiSO5rpMoD14fryB)j985V4QluL9zkwKKDqa8tYUEYPRWoxQlrMmGqVoxD95kOOXJFWVAIPjxISmC6E4s3fIme)F)`

**Comment by mrbuds** [comment]
This trigger use IsEquippedItem(itemName) to check if item is equipped.
On classic `print(IsEquippedItem("Rough Arrow"))` on a lvl 1 hunter return false

**Comment by mrbuds** [comment]
Changes were made to the trigger "Cooldown Progress (Equipment Slot)" for tracking amno, you can try it with last alpha version.

**Comment by c0mm0n** [comment]
@mrbuds excuse me for asking but I couldnt use this to do a simple "are thorium arrows equipped" icon.

Any guidance? 🙏

**Comment by atsolberg** [comment]
@mrbuds I don't think that PR helps with know a specific ranged item/ammo is equipped.  I made a working macro to swap ammo:
```lua
/run local a=GetInventoryItemID("player", 0); if a == 11285 then UseContainerItem(3,13) elseif a == 18042 then UseContainerItem(3,16) else UseContainerItem(4,16) end
```
ranged slot is 0, 11285 is jagged arrow id, 18042 is thorium plated arrow id

Is there are way to use the `Custom` trigger to do something like `GetInventoryItemID("player", 0) == <some item id>`?

**Comment by atsolberg** [comment]
@mrbuds I was able to do this with a custom trigger:
```
!WA:2!DrvZUTTrq44QgKavGIyhhJMlfeUibXajQXo1UffiO1urkwbksUu0jUNKwsoKCRP2LD3Lw2(uRoLEva9fqN7j9i4NacHI(aeG(c4xG0zxkQMeciro)SZp789nR0CTHRfSwWB(QPuFoRhpt4dvC85jCXlQGpIZ7ggkb1b)i5Z6(dV7DVBgH5hZfhYPmLx9gDCB4m3NZtc4Jy9grtHbxwk2iicIT1XDWyLGgfbc5NFFXIpFZThtvWWoKHWnF4Dsxntc9JagiO(9I5J6Ygm)deFR08Q(IGBNXOkV0eY5GWeOEjC19MgaEzHHUNNcIdA0(WMh12wHcE(zsfF4SIx9nQKkIkt(wzMhCkWuhkGq6zo9oSr72xQlMYQBWyTKoDdwQxNSbom0QS6yzkKK0kqwn92A7kqQAYfLf6ah)yW)eVS0aIcCm5kDZsRwhk4rcqkTEqJFnJMoeTAPJ(wllSEydrpBw)673ZTFp39DCZVt6FgMX8vuo7bBv1cFidhYTEQ1ZbvlM(qCX5TW6S1ZEWMf3rB(qRhx4knCH3p1A7T35721sfdmJf9ZJEK1li48jWIie8rs8fyb6slfcw6LauzcMLsKbgDalOk(BsgBX0DdSg)YpQgF)dHoNUkbTEk4wCIxYdG)6AxHWkqWijVcbl4rjxDcaP7JxX(khcgS4jegDO(l2Eo4iuOAMVUnJZGlbIe6PealsfFJ5bzcJxMHTqcimmqow7JgDKxZEiHYWZMxl)RVr(JZ3oFN8AEHugvg)XQryLeblyaH4P4CXbIWil)(nYxFok6r8pjsWZybVz901uWzQ(YycoEpUG8Ss6Dnkn)fYfy53xU4J8AtwABZ7jtV17D86gA4kRSsL3wOfscnep79pYTB6TnkjziIg7u)xtduX27JIxvKi6zqGr5VpVG0(ZlkNln2)fKlqdpp)6tfCKkaUOs7oD70iFDb2uAFMAC8)3gmzrhGi4B1uqVW6NYib4TcXY19dA8Ymn3OBexe8AbjD8Rx8rrbCkvs9sGbl653BXs6QT60PHtF7UUUDFPtRNFG78LPUh9c4Ul6OJ)G8OTAO(DpYTDRon(N5rj8rnfi8fy(NF4N(4A7SBr3Pnmt)xzegRf0hEUxMsXzDpfeiXzQwDBdK6og)l7SjAH6lVz0BgEEPMyBTXyJl98jjqftH4gt9pHHC9kglTP43RAsGnEVaIyVyGgfR2YoHtcE1e9Ye)eIuoWtHbHP2WzywIIw1wth2ihQ6ymFFpjLfLaEhCKEDCoSroDGTeVM0(mvyaRgq)nfNvUo)K)9SF7Ax7teeddvUx(JQAJyFv18VP64Yn4XZcOs9(Jwi7XB7NS7E7TD66Lw1aMNrLeCggephXH4aPBQjCvNQ4(NwqHV5d)JnPbPFX(f7tASyxIv5Igpm2H0OQoKK0ysLRkMSnf4YvDr71RUtJgDCgPrYBTtgnyMnnQ1bxeu)442cktNgiEwO(ai9hrJvSVGZhUYunLNwupZOSc(gkvDYsIu(1xt68KAFBTDx70)(4)7
```

Would be nice to have a built in way to check ranged slot item equipped which a custom trigger but it's awesome the custom triggers can do so much.

**Comment by mrbuds** [comment]
Please don't necro 2 years old ticket, if you found an issue open a new ticket with all information asked

**Comment by atsolberg** [comment]
Will do, although this will actually help people coming from search results, which was me.
