### ISSUE TITLE
WA2 Won't Open on Retail

### ISSUE THREAD

**Issue by Sekenx** [WeakAuras/WeakAuras2#1763]
**Describe the bug**
When trying to open Weak Auras on retail it says the add-on is for classic despite being the retail download from curse/twitch app. 

When looking at the package in Twitch it states "WeakAuras 2
WeakAuras-2.15.2-classic.zip" but is in the retail repository. 

**Do you have an error log of what happened?**
Not an error as such, not applicable. 

**To Reproduce**
1. Type /WA or /WA 2 and you get the following "This version of WeakAuras was packaged for World of Warcraft Classic."

**Screenshots**

https://imgur.com/a/96fiGIU

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
N/A

**Which version of WeakAuras are you using?**
Latest through Twitch Application, 2.15.2

**Was it working in a previous version? If yes, which was the last good one?**
Was working the other day, this has only recently become an issue.

**Additional context**
N/A

**Comment by Sekenx** [comment]
It is worth noting that all Weak Auras are not functioning either.

**Comment by mrbuds** [comment]
This is a bug on Twitch side, they are working on it and there is nothing much we can do about it.
You can download retail version of WeakAuras at https://github.com/WeakAuras/WeakAuras2/releases/tag/2.15.2
