### ISSUE TITLE
Pet ability rank gets stuck to old rank id when switching pet from stable master.

### ISSUE THREAD

**Issue by Teme009** [WeakAuras/WeakAuras2#1765]
When I do a trigger (status - cooldown progress (spell)) and write Bite on the spell section and I make it display the icon when the bite is on cooldown. It works on my main pet with rank 8 bite but when I switch to a pet with rank 7 bite it no longer works. Reloading or loading/unloading the weakaura does not fix the issue BUT after relogging it works with the rank 7 bite pet. Same happens the other way around it seems to get stuck with the first rank ability it uses.

Below is a simple weakaura to reproduce the issue. Everything but the trigger is on default. Load the weakaura and use any pet with bite. The icon shows when bite is on cooldown. After using bite and switching pet from stable master to a pet with different rank bite it no longer works, only relogging seems to fix the weakaura for the new pet.

!nwvZYjooq4NMTQDoKu2MFcxdSMDsvmggKZwZEreHTST2yKyKKHqoKN9TBjzGKCyMQCzl1Q)tF9x3MgtZPebnlEqsYDtOedLKCB8OBtOKDusj(aku3Qos36)UGlRTnGfruYPLvvgUf2mk(27IgmgCZK4Kructw0O0RucPLsMLMLNUMskuQ2s1rj5OypNo9IG0YAo6FwHvOKgmKgltBHfG5cPiSQcwAACRHDwTOUMRr1ZC3JGaCzzNMH(IsIH0Ml5ArbPrDCjiX4(oleBkPZW30HXaYOs(2UQQ8tq(r(A6IvZFCb4x3wiJSDa(0j5h441I1zvERFFaa3e0OpgV90kTQwZnM3E6pj75TTFb9desY(w2jiLjAoR1DsgBheSPcl37BZzHGFDBEO04Hdt3wxGiqklEHs2m7Es(gs(9RZdQ6Sll(UKXamiHnblrhB1SINDon4MvAUZnKvPlw40sEbrDiowFoWZ9c)MQe89napWvJSCTK1(pq9aH9SKHuYZC((7H8OWUglgUkSuSZxyUQghayPsYVu52eqDEHscxyig7yc5VV2N5k)E6BXAVbQWW58EU(mvRs7Px4tI79a37H4BFnynVoWAd0q(l2nMggu5)rFds0zwu3w88Gw(L)HjST4xhpNEvkKDnxlE9TN(EhReYz2BpL)(yFDYh5CwKZzrFWzET)3RZuNyEBvO)9(hZxEvKjIxrsvsq0bHrST1rpD7FxR)dzzPR3mDzE(YVT(H)(R59Jg(u8(VoJvuD6Y0cTcA445oekBzwAVL)4JwI5KVJD5J5lEa00voB4I6gqTXatSvXCdYqYi(DxxRv0ZQlAzgZNKAWB5heA90I5A(p74YItqoCloTdf6ZGTDwRsU8axd91HdAefplHEFe0jwvXH(EK44brjyRpYF82lkWzwWKf4IUCF)0qFh7fg5wK5EU80dyVeaM53mjjzYKOOjJgpzu0Wbj0QBgo8Y4wet)lHHbvTs0xqmRe1(4Gb56AJhZNRHzh(mKmBDAAgL8QsTZRbogCQ3ssbRL7UNIY(HyvOTWSzGJ6oH1UVXV6OOe)tYyxQ9lz(DOlFo(0pxns9L0Vpgh6Gq55U1fcaLPztcOO7)lYsXvGiQ110hC)uLUKJqkC(biudtWOr)))

All other addons are disabled and I used version: WeakAuras 2 WeakAuras-2.15.2-classic

**Comment by InfusOnWoW** [comment]
I suspect that this is a bug in how wow handles that.  Unfortunately no developer plays a hunter, so we can't easily test that, but can you try doing a few tests.

Namely, first the cases that should work:
1) With a Bite Rank 8, relog
2) Run /dump GetSpellInfo("Bite") via the chat frame, the value that interest me is the [7], which is most likely 17261
3) Make your Pet use "Bite"
4) Immediately run /dump GetSpellCooldown("Bite")
That outputs several lines, the one that interest me is the [2] line, which should match the duration of the Bite cooldown.

Now, the other case that should work.
1) With a Bite Rank 7, relog
2) Run /dump GetSpellInfo("Bite") via the chat frame, the value that interest me is the [7], which is most likely 17260
3) Make your Pet use "Bite"
4) Immediately run /dump GetSpellCooldown("Bite") 

Again, the second line should have the duration of the spell.

And now the case that according to your description doesn't work
1) Start with your Rank 8 pet, make it use Bite
2) Switch to your Rank 7 pet
3) Run /dump GetSpellInfo("Bite") via the chat frame
4) Make your pet use "Bite"
5) Run /dump GetSpellCooldown("Bite")

**Comment by Teme009** [comment]
> I suspect that this is a bug in how wow handles that. Unfortunately no developer plays a hunter, so we can't easily test that, but can you try doing a few tests.

> Namely, first the cases that should work:
2. 17261
4.
[1]=22332.57
[2]=10

> Now, the other case that should work.
2. 17260
4.
[1]=22493.894
[2]=10

> And now the case that according to your description doesn't work
3. 17261
5. 
[1]=22740.802
[2]=10

After relogging it changes to 17260 so yeah it looks like the bug is in how wow handles the spellid.

**Comment by InfusOnWoW** [comment]
Hmm, okay the spell id seems to be broken. But from the output it does look like GetSpellCooldown actually returned the right cooldown information. 

I'll check what else we do. As a guess, there's a "hidden" option to disable the "IsSpellKnown" check behind the pencil, try toggling that one.

**Comment by Teme009** [comment]
"Ignore Spell Known" toggle does in fact fix the trigger for all the cases. Also I noticed in the load tab the "Spell Known" doesn't work for hunter pet abilities even if I type 17261, 17260 or Bite.

I found this: https://wow.gamepedia.com/API_IsSpellKnown
And tested it: I changed from rank 7 bite pet to rank 8 pet. 

/dump GetSpellInfo("Bite")  returns [7]=17260      <---- wrong rank bite
/dump IsSpellKnown(17260, true)  returns [1]=false
/dump IsSpellKnown(17261, true)  returns [1]=true

After relogging:
/dump GetSpellInfo("Bite")  returns [7]=17261      <---- correct rank bite
/dump IsSpellKnown(17260, true)  returns [1]=false
/dump IsSpellKnown(17261, true)  returns [1]=true

**Comment by InfusOnWoW** [comment]
Do note, that it currently doesn't check pet spells at all, but from your data it's pretty obvious that we couldn't even make it work for your case.

So as far as I can tell, there's nothing more to do. The original and the spell known issue are both due to a wow bug. For the Cooldown Progress we at least support it, for load we can't.
