### ISSUE TITLE
Castbar / Progress Bar disappears with 2.15.3

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#1766]
**Describe the bug**

after i updated to 2.15.3 my WA castbar (right above the fury bar in the GIF) dissapers immediatly after i started the cast. Only tested it with my DH and only happens when i cast eye beam, so i don't know exactly which other spells are affected. If i mount up, use hearthstone etc. the castbar works perfectly fine. The weakaura just tracks the player cast, no conditions, nothing else.

**Do you have an error log of what happened?**

No

**Screenshots**

a GIF so you see perfectly what i mean: https://gyazo.com/2d60c7c680c7ca5e7c2b22f1a015d237

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, issue persists

**Which version of WeakAuras are you using?**

2.15.3

**Was it working in a previous version? If yes, which was the last good one?**

Yes, it worked with 2.15.2. Reverted back 2 times just now.

**Comment by Dasaneux** [comment]
I'm having the same issue, as recorded here ..

https://youtu.be/LrSPpGo8how
