### ISSUE TITLE
avenger shield/bulwark of order missing text

### ISSUE THREAD

**Issue by Hackebein** [WeakAuras/WeakAuras2#177]
What steps will reproduce the problem?
Cast spell "avenger shield" on target. Applies a buff "bulwark of order".

What is the expected output? What do you see instead?
I see the buff in the vanilla WoW buf list, but not in the list of Weak Auras 2.

Did you try having WeakAuras as the only enabled addon and everything else disabled?
yes

What version of WeakAuras are you using?
2.3.6

Was it working in a previous version? If yes, which was the last good one?
no, i can't find a working version.

Do you have an error log of what happened?
```
[string "return function()..."]:3: attempt to compare nil with number
[21:39] [string "return function()..."]:3: in function <[string "return function()..."]:1>
Interface\AddOns\WeakAuras\RegionTypes\text.lua:112: in function `UpdateCustomText'
Interface\AddOns\WeakAuras\WeakAuras-2.3.1.lua:3260: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3220>
Interface\AddOns\WeakAuras\WeakAuras-2.3.1.lua:3324: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3316>
Interface\AddOns\WeakAuras\WeakAuras-2.3.1.lua:3401: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\BuffTrigger.lua:733: in function `ScanAuras'
Interface\AddOns\WeakAuras\BuffTrigger.lua:1189: in function <Interface\AddOns\WeakAuras\BuffTrigger.lua:1186>
```

Please provide any additional information below.
Error is only visible with !BugGrabber (my version is 7.1.5) not with BugSack.

**Comment by emptyrivers** [comment]
That looks like an error with a specific aura string (in particular the custom text function [%c]), not with weakauras itself, where whoever created the string forgot to check for nils in his code. Without a copy of the aura string itself, it's impossible to know exactly how to solve this issue.

**Comment by Hackebein** [comment]
A friend removed the spell before i report it. Based on `compare nil with number` (invalid data type compare) and the stacktrace i hope you can fix this problem for other users. If not, a moderator can close this report.

**Comment by Stanzilla** [comment]
Like Rivers said, this is a mistake in one of your auras that needs to be fixed.
