### ISSUE TITLE
Castbar with macros

### ISSUE THREAD

**Issue by turnover2** [WeakAuras/WeakAuras2#1770]
I have a weakaura for my castbar, cause i didnt like the wow bar. Since the last update the castbar doesnt show up, when i use a cast on which i have a macro to use my trinkets first. If i use the cast whithout that macro the castbar is shown up.

**Comment by Stanzilla** [comment]
Please try again with 2.15.4

**Comment by turnover2** [comment]
Works fine with 2.15.4

Thanks a lot
