### ISSUE TITLE
WA2 thinks its installed for classic

### ISSUE THREAD

**Issue by rippythefish** [WeakAuras/WeakAuras2#1771]
**What steps will reproduce the problem?**
Updated via Twitch client - launched wow

**What is the expected output? What do you see instead?**
Expected WA to work - it did not, instead it says 'This version of WeakAuras was packaged for World of Warcraft Classic. Please install the retail version instead.'

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
2.15.4

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [XXXXXXXX ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes - presumably 2.15

**Do you have an error log of what happened?** 
Error isn't thrown - only chat message noting addon is for Retail

**Please provide any additional information below:**

![image](https://user-images.githubusercontent.com/33566991/66968991-80bbb500-f03c-11e9-91af-3d02f5a24682.png)

**Comment by mrbuds** [comment]
You have installed the wrong version. I guess you use twitch app, it's a bug on their end.
Install it directly from

• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
    (see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
    (See C and R on the right)

**Comment by rippythefish** [comment]
I didn't install the wrong version - I updated directly from Twitch. Is this something you need to fix in your listing or something they need to fix?

**Comment by SilkCharm** [comment]
I am on a Mac and we use Twitch (as Curseforge no longer supports Mac) I am also getting this error 'This version of WeakAuras was packaged for World of Warcraft Classic. Please install the retail version instead.' I did not download the Classic version of wago. If anyone has a suggestion other than "it's a Mac problem, buy a PC" please let me know?

**Comment by Stanzilla** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• [CurseForge](https://www.curseforge.com/wow/addons/weakauras-2) 
    (see the **Recent Files** section, bottom right, for both versions)
• [WoWInterface](https://www.wowinterface.com/downloads/info24910-WeakAuras2.html)
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)
