### ISSUE TITLE
Says it's Classic and to install Retail version

### ISSUE THREAD

**Issue by Demonicka** [WeakAuras/WeakAuras2#1772]
**Describe the bug**

I expect it to work and it doesn't.
**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by emptyrivers** [comment]
Twitch is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing Retail on Classic and vice versa. Ensure that you have got the right version selected but if you do and it still installs the wrong version then you may have to just install manually with the zip.
You can get the latest versions from:
• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
    (see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
    (See C and R on the right)
