### ISSUE TITLE
Twitch file is not correct

### ISSUE THREAD

**Issue by casutton08** [WeakAuras/WeakAuras2#1773]
I kept getting an error in game saying I had the classic version of WA installed. Looked on my twitch page, and sure enough it says I have 2.15.4-classic installed.

I don't have classic installed, nor have I. 

I tried deleting the addon and reinstalling, but it's still tagged -classic.  I downloaded the correct file from curse forge, but cannot find the non-classic tagged WA in twitch at all. 
![2019-10-16](https://user-images.githubusercontent.com/36038484/66977130-41a45880-f06a-11e9-8235-ca00309312f8.png)

**Comment by Bitexd** [comment]
I'm having the same problem, after updating my WA2 few minutes ago, and I never played classic or downloaded it but someohow I'm getting this message"This version of WeakAuras was packaged for World of Warcraft Classic. Please install the Retail version instead." All I did is updating my previous version of WA which I use in retail.. so does anyone have a solution for this without losing all my WA data?

**Comment by Bitexd** [comment]
> I kept getting an error in game saying I had the classic version of WA installed. Looked on my twitch page, and sure enough it says I have 2.15.4-classic installed.
> 
> I don't have classic installed, nor have I.
> 
> I tried deleting the addon and reinstalling, but it's still tagged -classic. I downloaded the correct file from curse forge, but cannot find the non-classic tagged WA in twitch at all.
> ![2019-10-16](https://user-images.githubusercontent.com/36038484/66977130-41a45880-f06a-11e9-8235-ca00309312f8.png)

I tried reinstalling the addon and now its working fine.

**Comment by Stanzilla** [comment]
That's a Twitch bug, please report it at @CurseForge on Twitter or support@twitch.tv
