### ISSUE TITLE
Can't view weakaura

### ISSUE THREAD

**Issue by Sinbad-SM** [WeakAuras/WeakAuras2#1777]
**Describe the bug**
The addon is installed and the icon appears on the mini map but when I click to open the option menue nothing happens.  I can't get it to open by typing /wa either. 

**Do you have an error log of what happened?**
2x WeakAuras\Types.lua:377: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
WeakAuras\Types.lua:377: in main chunk
 
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
 
2x WeakAuras\Transmission.lua:231: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
WeakAuras\Transmission.lua:231: in main chunk
 
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
 
2x WeakAuras\WeakAuras-2.15.4.lua:330: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
WeakAuras\WeakAuras.lua:330: in function `validate'
WeakAuras\WeakAuras.lua:4070: in function `PreAdd'
WeakAuras\WeakAuras.lua:4186: in function `Add'
WeakAuras\WeakAuras.lua:3738: in function <WeakAuras\WeakAuras.lua:3717>
WeakAuras\WeakAuras.lua:3730: in function `load'
WeakAuras\WeakAuras.lua:3745: in function `AddMany'
WeakAuras\WeakAuras.lua:1534: in function <WeakAuras\WeakAuras.lua:1520>
 
WeakAuras\WeakAuras-2.15.4.lua:1661: in function <WeakAuras\WeakAuras.lua:1613>

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes- I do not use ElvUI but all other addons were disabled except Bugsack and Buggrabber.

**Which version of WeakAuras are you using?**
Latest 2.15.4

**Was it working in a previous version? If yes, which was the last good one?**
It started when I updated my addons through Twitch

**Additional context**

``` HERE ```

**Comment by InfusOnWoW** [comment]
That looks like either there are more error mesages or that your installation is broken. Are there any other error messsages? If not, try reinstalling WeakAuras via the twitch client. 

If that doesn't help, we need your WeakAuras settings.

**Comment by Sinbad-SM** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/3744102/WeakAuras.zip)

**Comment by Sinbad-SM** [comment]
I did delete and reinstall weakaura through Twitch but I get the same issue.  Not being able to open Weakaura menu or see my weakauras.

**Comment by Sinbad-SM** [comment]
On my 4th attempt to reinstall the addon through Twitch, it is now finaly working.  Thank you for your support and help.
