### ISSUE TITLE
Truncating font after game launch

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#1778]
**Describe the bug**

Text font truncates after you just started the game and did fire WA that was unloaded, instead of displaying full text.
This issue started to happen after WA switched text to subregions.
**Do you have an error log of what happened?**
 
No errors
**To Reproduce**
 
Make any WA, add some load parameters (like combat), close the game, open the game and login, enter the combat and trigger WA.
**Screenshots**

expected https://i.imgur.com/yMGMwkg.png
getting instead https://i.imgur.com/PwfrRFI.png / https://i.imgur.com/HDnBq5u.png
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes, same issue.
**Which version of WeakAuras are you using?**

2.15.4
**Was it working in a previous version? If yes, which was the last good one?**

Was working in latest version before text subregions
**Additional context**

Playing around with different stuff noticed that checking fonts after the most 1st login is bugged too https://i.imgur.com/Maryycv.png
Possibly SharedMedia issue or WA additial fonts? 
Currently truncating comes from **Fira Mono Medium** font which is not "default" by blizzard.
Testing with **Friz Quadrata TT / Arial Narrow** doesn't seem replicate the issue.
Switching to self registed font from SharedMedia **PFSquareSansPro** doesn't provide the issue too.
But switching back to **Fira Mono Medium** reproduces that.

Not WA related, but if ElvUI is enabled it has the similar problem. https://i.imgur.com/zicgusU.png On this screenshot on the first login the font is different. If i show/hide them it goes back to what it's set. https://i.imgur.com/viFIwDN.gif Might be something is not loaded right after the most 1st login.

``` !nAv3YPTru43LCv7uhgqgsS7m9calSjdiCyfPjZ4rOfPvWwlPLQDfyYf6zVNZzLaSjTnd2IvNF)o)Ue0jWpGLfWIX)GJRtv7dwfW4LMnQIzBnsvUgyycyhMLKOfMaV2a78iG9JkzoWyORNV78awKsLgR2NZ2l3kcgaek1gvMV4fZITXCJiGvw)DJOUXRfK7IACetB4fg6GQmhG14CJOiHhjEQFCmiZt)PG)C)YcU(Phv7ff0XPIyj)jgQH(P9Q0KETuRxdXKAP1mdWiqMljlduTq7eiXiUGVuKVRLERinvgxf(hvHDU5Mo3(bu3eqz9gktaVzkKRxlkqa7rPWAc0XdBfNmR97LBKXarJmtaHKUCLyNi3WktsKVeWwoSpZFjZV)C)tkMuMtjLFHe9QQWwTA9RvFQk0(rMufsCaCca9DdNnDqF)LtMD)s3VafKLl8gnEcuxCV7DvH88yYavHMnI8twP5tQkINwfUeCtMqR5RfxzFtxeD)IX3zp5XZAOJ)hl0MAM4XZ4IVoNlJhLYxRrDplLIO4c)JrtTJRJh2JUtMuNywmCOlJ1eg1qYk3XMHwzhSuTYC0HGmxwz)XjHMphLpgoGLac3oT)31OqyklaXmfLIlLsai6tV6flf6d0nw7LawNoT6fWOQAa7bbp1SbyFiNNjJURrQJTShPCQv5S(JgiDrWC1pma)TQW7fgFO)enYr8vJgnmKpXDXVFzrbAMXK6446Le1T72zG6ibWVOMDjobY2MYpaZkhNdESqqZbK5HiwScgm8jt8G7KhhTyIv3tdz0qiU0yNW3sCQcgW8EFN22bDyNrop9lWikMH8C6AxT91xTdtMztGNV1XI8CvU4uLPoC0IifSFbDqgxM)Zl9XDh)CYBWuGMBq(02re5dvPQc76g8ph6510ZU4tdLoNlwxVhTETeS7DPEdp(1HEThlxH8RLYEC0y2dvH(JNIl0j6r))oMKlrH16rYcEv4uvUcEclLlZEfiopkAtgRnzS2VXywP)25qMilstQV0P)c)z1u3j1YvP0nohrIT7z2c)jJ9CRP)QlTawUZxoyMV)SPn3NDH)(lOBwMC40vCfkdut8PuL3m0Ywn)6B1eXat(DOLSZT2s6gHC9gqIpaTIPkoDBBPwaZHrWnuq)QmgR1rPCnDpywzQr20QJcgPYwXnyuEUkmhNBULMcJUqlncG3qeZWQODndg302PDpBh2OcXFxcM(aefTCQjAZJRkngv(mqlyYTMXgz0Z5WkBSSXoRW0KQKr2LvXsnoVpgF172p2(gNRH8i1NAnoji7)SnBu3E3C9h72TNJtxN2WJGK337AAhaL(hvaRySwJnCURRhKXWCZH0dth8WN5FUNdLdpnibz69Yyy)kvp4PB3WPa5LZkKn)ifSCFNuZHEmQe9DfC)mTbP0OWqenldUavqMaDSVlZVkC0mp4P)8fEd77p27ERKtKqAdY8WEbe2WpDGBSoh5EEpijTiFncZoeGYtKRTBsL5ynKwp8SqSTp2aa35cluqsqBB0ZhoEdXks3y5z)AUMGRb)dufXcmVG9nqxvRo9AbzMDGN76GdMb)Zp```

change aura_env.spell **on init** to match SPELL_CAST_SUCCESS trigger. WA loads in combat by default

**Comment by InfusOnWoW** [comment]
I can reproduce that. It's obviously a upstream issue, but I'll try to figure out whether we can workaround it and whether I can figure out a minimal example.

Restarting the game for each test will be fun!

**Comment by Translitdk** [comment]
I guess it's the same if you put some table On init (Can be different API call) with

aura_env.something = {
    [GetItemInfo(6948)] = true,
    [GetItemInfo(169451)] = true,
    [GetItemInfo(169299)] = true,
}
print(aura_env.something[GetItemInfo(6948)] ~= 1)

It would not create needed table and will error on nil index if you will try to use it. 
As workaround i had to add delay or wrap table in the function to rebuild it with C_Timer.After(0.5, ...)

**Comment by InfusOnWoW** [comment]
Well, I'll investigat some more. After all it somehow worked before...

**Comment by emptyrivers** [comment]
![ED769B55-C041-4C47-8CA1-64FF5B230362](https://user-images.githubusercontent.com/24878501/68620848-f9732d00-0493-11ea-8eac-b8dec671b0be.png)

This might be relevant.

**Comment by emptyrivers** [comment]
![080D8051-E7A2-48CE-AF26-9900A41987A0](https://user-images.githubusercontent.com/24878501/68622088-e9a91800-0496-11ea-9fb9-7b435fb68977.png)
