### ISSUE TITLE
Mooncloth Cooldown Tracking returns wrong value

### ISSUE THREAD

**Issue by m33ts4k0z** [WeakAuras/WeakAuras2#1779]
**Describe the bug**
Tracking mooncloth cooldown (18560) returns a very strange number using %p. It should return the minutes of the remaining time. The expirationTime seems to be awfully wrong.

**Do you have an error log of what happened?**
No errors occur

**To Reproduce**
Create trigger -> Status -> Cooldown Progress (Spell) -> Exact match 18560.
Then on display use %p as text.

**Screenshots**
http://prntscr.com/plenes

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes. Thes result is the same

**Which version of WeakAuras are you using?**
2.5.14 classic

**Was it working in a previous version? If yes, which was the last good one?**
When I first created the icon on Thursday 17/10/2019 it worked as expected. But the day after, after Blizz maintenance, it somehow broke.

**Comment by m33ts4k0z** [comment]
I believe the problem relies somewhere where the GetTime() is involved? Since this returns the uptime of the client it can't really be used as starting point from Blizz but yet it does?

**Comment by mrbuds** [comment]
This doesn't look like a bug on weakauras, you can try report it to blizzard's dev on twitter or irc.
