### ISSUE TITLE
overlay does not disappear after closing the WA window

### ISSUE THREAD

**Issue by aksiere** [WeakAuras/WeakAuras2#1783]
### **Describe the bug**
When I open the WA window during the cast (showing the overlay on the bar), It (overlay) does not disappear after closing the window itself.

### **To Reproduce**
- Use [linked](https://wago.io/ezzJSOyEl) WA that shows a dynamic overlay
- Start a cast which spends power
- Open the WA window during overlay is showing
- Сlose the WA window

### **Screenshots (more precisely, gif)**
![2](https://user-images.githubusercontent.com/33295331/67152121-4e7ab380-f2d9-11e9-85ce-1532a0b91b56.gif)

### **Which version of WeakAuras are you using?**
2.15.4

**Comment by mrbuds** [comment]
i don't see any issue when i try to reproduce what you explain
![img](https://i.imgur.com/Uf1s9c2.gif)

**Comment by aksiere** [comment]
> i don't see any issue when i try to reproduce what you explain
> ![img](https://camo.githubusercontent.com/8e6dc003c35945e4d9e08db22fdd1401e543bc94/68747470733a2f2f692e696d6775722e636f6d2f556631733963322e676966)

hm. can u try with linked wa?

**Comment by mrbuds** [comment]
no your link to pastebin doesn't work

**Comment by aksiere** [comment]
> no your link to pastebin doesn't work

generally should, but okay https://wago.io/2c8g17nu4

**Comment by mrbuds** [comment]
Can you make a minimal example ? Generic triggers works fine, this aura has a lot of custom code and i don't want to dig into all of this

**Comment by aksiere** [comment]
> Can you make a minimal example ? Generic triggers works fine, this aura has a lot of custom code and i don't want to dig into all of this

[this](https://wago.io/ezzJSOyEl)

**Comment by InfusOnWoW** [comment]
That's a bug in your custom code. While the options are open no events are delivered to your aura. There's a fake event "LOAD" send on options close, where you need to set aura_env.cost and aura_env.incoming to the right values.
