### ISSUE TITLE
Classic version currently incorrectly flagged as 8.2.5 compatible on twitch

### ISSUE THREAD

**Issue by MashmanAU** [WeakAuras/WeakAuras2#1784]
Hi,

As can be seen in the screen clip attached, the current version associated with Patch 8.2.5 on the Twitch App is actually for Classic.
![image](https://user-images.githubusercontent.com/56819213/67186838-9cf09500-f434-11e9-9197-76aeb44db574.png)

Sorry if this is a Twitch bug, not a WA bug.

**Comment by InfusOnWoW** [comment]
It's a twitch bug, wer can't do anything about it.
