### ISSUE TITLE
Remove "in encounter" load condition in classic version

### ISSUE THREAD

**Issue by Olorun** [WeakAuras/WeakAuras2#1785]
**Is your feature request related to a problem? Please describe.**
The "in encounter" feature is missing in WoW Classic, so the load condition is pretty much useless for now.

**Describe the solution you'd like**
Just remove the checkbox and text from the load tab.

**Additional context**
![image](https://user-images.githubusercontent.com/10301169/67216209-c5d95000-f45d-11e9-9842-fed0d33b808c.png)

**Comment by mrbuds** [comment]
The "in encounter" load condition is working as intended.
