### ISSUE TITLE
Group by Frame: Unit Frame not updating frames after GROUP_ROSTER_UPDATE

### ISSUE THREAD

**Issue by nnogga** [WeakAuras/WeakAuras2#1786]
**Describe the bug**
Created a WeakAura that displays a frame on top of a group/raid member when they write "123" in group or raid chat. 
[Summon Group](https://wago.io/j587Ah2a7)
Due to the nature of the WeakAura being used outside of combat the raidcomposition can change while states are active. Due to this i am also tracking the event "GROUP_ROSTER_UPDATE" and change the state to include the updated unitId. Due to the implementation of [LibGetFrame](https://github.com/mrbuds/LibGetFrame/blob/master/LibGetFrame-1.0.lua#L90) the library has not yet scanned the new unitIds and frames when WeakAuras wants to update the frames. I have to manually delay the code that i want to run on "GROUP_ROSTER_UPDATE" to wait for the new frames to be stored properly by the lib.

**Do you have an error log of what happened?**
no 
**To Reproduce**
1. Import the WeakAura i linked
2. Edit the trigger to run the code of the delayed event "WA_RAIDFRAMES_UPDATE" on "GROUP_ROSTER_UPDATE" instead
3. Form Raidgroup
4. Drag group members around

**Screenshots**
https://streamable.com/eu437

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.15.4

**Was it working in a previous version? If yes, which was the last good one?**
I started making this WeakAura on the current version of WA

**Additional context**
A suggestion was to add a callback to LibGetFrame once the new frames are cached to solve this issue.

**Comment by mrbuds** [comment]
The way you do it with a delay after GROUP_ROSTER_UPDATE is correct.
There is no generic way to know which of your code or <insert unitframe addon name here> is executed first on the event, without a delay your unitframe addon may not have updated it's frames yet.
