### ISSUE TITLE
Classic and Retail Versions

### ISSUE THREAD

**Issue by Racerx323** [WeakAuras/WeakAuras2#1790]
**Describe the bug**
Twitch keeps replacing the retail version of the addon with the classic version.

**Do you have an error log of what happened?**
no. Reported to Twitch and they said it was an addon author issue. I do not have the classic WoW installed.

**To Reproduce**
Update the addon in Twitch

**Screenshots**

**Comment by InfusOnWoW** [comment]
We can't fix bugs in the twitch client.

**Comment by InfusOnWoW** [comment]
They are wrong about this being a addon author bug, this is a bug on their end.
