### ISSUE TITLE
Проблема с импортом, из за верификации кода на lua

### ISSUE THREAD

**Issue by lingfill** [WeakAuras/WeakAuras2#1791]
Раньше такого не было, до какого то обновления. Сейчас не могу вообще импортировать любые коды, даже от тех людей от кого импортировал раньше. 
как это исправить?
удалял все уже установленные Wa, полностью удалял wa2, качал другие версии включая альфы, не работает, хотелось бы узнать что сделать
![unknown](https://user-images.githubusercontent.com/56969411/67497005-bee95200-f696-11e9-9086-6c2dd976b0dd.png)

**Comment by Translitdk** [comment]
Ты выключил любой импорт. Убери галку

**Comment by lingfill** [comment]
В 

> Ты выключил любой импорт. Убери галку
> ![image caption](https://camo.githubusercontent.com/ff5c4a5c7b3c8a46763d514593b7f3e94152ab17/68747470733a2f2f692e696d6775722e636f6d2f3734484750456e2e706e67)

в том то и дело что не выключал

**Comment by Translitdk** [comment]
Попробуй только с включенной ВА без других аддонов. Скорее всего что-то из них блочит импорт. Если заработает - включай по 1 аддону по очереди до тех пор пока не выключится импорт.
