### ISSUE TITLE
Swing timer causing error?

### ISSUE THREAD

**Issue by spidor** [WeakAuras/WeakAuras2#1793]
I'm getting the following error while using a swing timer (https://wago.io/-WCbLx83B) and a battle shout reminder WA:

> Message: Interface\AddOns\WeakAuras\GenericTrigger.lua:1606: attempt to perform arithmetic on local 'offSpeedNew' (a nil value)
> Time: Fri Oct 25 21:17:25 2019
> Count: 12
> Stack: Interface\AddOns\WeakAuras\GenericTrigger.lua:1606: attempt to perform arithmetic on local 'offSpeedNew' (a nil value)
> [C]: ?
> Interface\AddOns\WeakAuras\GenericTrigger.lua:1606: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:1588>
> Interface\AddOns\WeakAuras\GenericTrigger.lua:1668: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:1664>
> 
> Locals:

**Comment by spidor** [comment]
I've unloaded the swing timer wa, yet I still get this error.

**Comment by mrbuds** [comment]
Can you try the alpha version of weakauras ?

**Comment by spidor** [comment]
Sure, how can I download it?

**Comment by mrbuds** [comment]
If you use twitch app you can right click on the addon and change "Release Type" to alpha channel.
Or you can direct download it from https://www.curseforge.com/wow/addons/weakauras-2/files or https://www.wowace.com/projects/weakauras-2/files

**Comment by spidor** [comment]
I've downloaded i. But I have an idea what may cause the issue. I get the error when I'm getting aggro and changing from berserker stance to defensive stance and I change my off-hand weapon to my main hand and equip a shield into my off-hand. 
I'll test it with the alpha version now.

**Comment by spidor** [comment]
Well so far I have no issues with the alpha version :)
