### ISSUE TITLE
expose official Blizzard colours in colour / color picker

### ISSUE THREAD

**Issue by jokeyrhyme** [WeakAuras/WeakAuras2#1794]
**Is your feature request related to a problem? Please describe.**
Sometimes, I like to build indicators that blend in better with the vanilla UI
Today, I wanted to build my own health and mana bars, but it's difficult to select exactly the same health and mana bar colours that Blizzard uses
Previously, with other text indicators, I've wanted to use official-Blizzard class colours, or default chat channel colours, etc

**Describe the solution you'd like**
- It might be nice for the colour picker to have a tab that lists official-Blizzard colours so that specific ones can be easily selected
- It might also be nice for the colour picker to have more dynamic options like "match my primary power type colour" or "match my class colour"

**Describe alternatives you've considered**
- I can find the official colour values either in Lua or on a website, and manually edit my WeakAuras settings in a text editor outside the game
- I might be able to use Lua in WeakAuras to refer to the colour values at game runtime

**Additional context**
I'm really fond of this addon, and grateful for all the awesome work that goes into it

**Comment by emptyrivers** [comment]
You can use this addon to improve the color picker: https://www.curseforge.com/wow/addons/colorpickerplus
