### ISSUE TITLE
[Classic] Showing Aura by Tooltip information seems bugged

### ISSUE THREAD

**Issue by gobacktogo** [WeakAuras/WeakAuras2#1795]
**Describe the bug**

I want to show all kind of stuns on me and figured an aura showing auras based on tooltip information might be the way, since all stuns contain the word "Stunned" in their tooltip. this is working great, with the exception that sometimes it simply will not show the aura. this is not specific to any specific stun, in fact it happens with every type of cc, or tooltip information, i would guess.

my working theory is that it only happens once per wow restart. WA might first have to "learn" the tooltip. so possibly the first application of the aura will not show, and every other application after that will show up. i am not 100% sure about this but it seems very likely from my testing.

if this is an issue that can not be fixed, is there another way to make WA show for example all kind of stuns on me, other than adding each and every stun manually?

**Do you have an error log of what happened?**
no error is shown.

**To Reproduce**
1) load the WA posted below. (trigger: aura - player - debuff - use tooltip information - tooltip pattern match: contains - tooltip content: Stunned)
2) get stunned 

**Screenshots**
i've recorded a short video showing the stun not showing up:
https://streamable.com/sx7m1
as you can see, the first stun does not trigger the aura, the second does.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
2.15.4

**Was it working in a previous version? If yes, which was the last good one?**
i don't think so.

**Additional context**
-

!nsvxZTPoq0FnzY9(qZytsMEF1Xf34P2qkICB6lIidcqPyjxKK)ipKF7DxjigN2zAMHHbwT7QDp7zp0X0ukznLuGpWNvnQD0vuYH4Ysn3qJgrjmzETQ9oLqAOKPHrPHjusUs1uO2jj7eB40BoAiSOIJzqKRKODtROQI3QHSh5UTod4N6A1UPnkjxJryoazIWSTSa4i7k(wU0qSLLI9us20jK0ms6KeiUsUjVofUqJydEhopPKB5Sgt9XyVRL7ILCx4IfuIvZZmhdsVH30mValmi2(dieJvk5aEyLcW(Mg2bOyjs2A(PUMP2WBzgfCyPqw8pNFM(8)fGr(kOKtD9YTtswo7(fyqw5X(2Ggke6NSYCJyl20YdWl3pPE3wQk40OpmEKlynFq3IZOhoz(iwZmcaUri1WAn4hfaoIgZ8WQMdZdOz7qzja6yMxZeY3V3qFk01VB)XUKRzg0xhNaR8PQgvRNmGpbU3x6EFf(24MFj8ki7din89MmDnR40wV72TRWZ78Y)5z6UFZ)73NZVsfsHM1kE(Lh)QLva1m7Lhtp9Uhw8JCjBKlzJEtY8E)9HvQZmVPSBpAY9PXDw3k0IvnULOxRep)j((0fZJc7SFYE48OOWKSBIttJxMm)Z3M2VN(Bx6twTruE44QBRYaZJuhmffJP3h5dVnsSqiINbE44a)4SMlQQbpUgCPrXCsg5nmT2jJybgAp9g2UY)nJ4gOewnBrYGgZ8B8W45iZA5)0YL5hGA5IGRXvUCiknYXJgp(YrbE)8O0kRXOKXGdWUA3b1I8FaYkACO4SSqGQmr)himjn8wjR5)7tyWv9iWSwyl3NuY0KWWiaSCerVnNKgz)ayAWaThDTcq74lFBwvu6sZ(p(q31ZLvG0ueSp7(F4uI1SPM5kuM1avr8gth33CuwfhxFsOzarParVNvQ1(OTgvVQajN1WDzclIPtZGf0L8xE8vnT3XYqjIbGinq)DzANOalCCIdJVJBWRWSjlfv(6uiXbKBl)hC(Mj483KGAeOjuAZ3sVkqnuoXfVW0ttqTeXFad6BZBuTfooeYZOKGlgF9fWmCluVxfGnb9x)

**Comment by InfusOnWoW** [comment]
Indeed this can be reproduced even with "Power Word: Fortitude".

To reproduce:
1) Buff Fortitude
2) Close wow
3) Open wow

On the very first check after the game was newly started, the tooltip doesn't contain the spell description. As far as I can see tell, there's no way for WeakAuras to detect that the line is missing, and secondly there's no event associated with the tooltip being completly fillled.

Thus, this is a wow bug, most likely their spell cache, which as far as I can tell, we can't work around.

This bug seems to not affect retail, while initially the tooltip is indeed also missing the spell description, there are additional events that let us know that the tooltip has changed.

**Comment by Kolmarwow** [comment]
@InfusOnWoW noticed this problem was still present, i'm wondering since this is 6 years later and classic has gotten some retail events/functions ported over is it still unfixable?

**Comment by InfusOnWoW** [comment]
I would have to investigate this anew. There's supposed to be a UNIT_AURA event whenever anything changes, but that was missing on classic. I assume that's still the case though.
