### ISSUE TITLE
Integrating a snippet-pasting/saving tool to code blocks

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1798]
**Is your feature request related to a problem? Please describe.**
I always tend to look/import some of my older auras in order copy parts of code from it which can be a time consuming process.

**Describe the solution you'd like**
After opening a code block, you have the option to save the entire code block's content or only the highlighted parts (once blizz fixes it, ffs), then a new window appears where you can specifiy its name.

And another button within the code block for "Insert code from snippet" or w/e where you can search for snippets.

And a new saved variable for snippets? WeakAurasSnippets 💯

**Comment by mrbuds** [comment]
There are a few addons dedicated to save snippets of lua code
wowlua https://www.wowinterface.com/downloads/info7366-WowLua.html
REHack https://www.wowinterface.com/downloads/info24734-REHack-UINotebook.html

**Comment by InfusOnWoW** [comment]
I think that's out of scope.
