### ISSUE TITLE
health and mana percentage

### ISSUE THREAD

**Issue by Luzbeliten** [WeakAuras/WeakAuras2#1800]
Hi, sorry if this is offtopic or it's already a feature and I didn't realize it.

My request is regarding the "%1.healthpercent" and power percent; I created two bars near the middle of the screen for health and mana and added the percentage but when it goes below 100% it's too precise, showing numbers like "90.876237125%". 

The request itself is adding an option to show round numbers, or maybe 2 decimals at best, so the number is much smaller and easier to read.

Thank you!

**Comment by julesssb** [comment]
You can use the following to fix this:

> %percenthealth or %percentpower showing far too many decimal places when using a Status - Health/Power trigger?
> Instead use %c, set to Trigger Update, and:
```
 function()
     if aura_env.states[1].percentpower then
         return Round(aura_env.states[1].percentpower).."%"
     end
 end
```
>  
> Change percentpower to percenthealth above for a health trigger and change [1] to other trigger numbers as needed.

**Comment by InfusOnWoW** [comment]
This is a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/1618
