### ISSUE TITLE
Track threat percentage

### ISSUE THREAD

**Issue by heyimjace** [WeakAuras/WeakAuras2#1801]
I would like to be able to track Threat percentage in the same way Tiny Threat or ClassicThreatMeters does, but customizable.

I just want to be able to track my own Threat percentage in an easy and customizable way. If other addons can track threat for the entire raid why cant i make a threat tracker based on my target for my personal threat?

**Comment by mrbuds** [comment]
The game does not give an easy API for this information, and there are several incompatible solutions for threat implement into several addons.
I don't want to add an other dependency for something best handled by a dedicated addon.

If someone has the motivation to implement it into weakauras maybe we can review a PR for this, it depend on the position about this from other devs.

**Comment by Vardex** [comment]
ClassicThreatMeters and ElvUI seem to both use [LibThreatClassic](https://github.com/EsreverWoW/LibThreatClassic)

**Comment by InfusOnWoW** [comment]
I agree with Buds, if there's a PR, we can review it. Otherwise it's out of scope.

**Comment by InfusOnWoW** [comment]
I see no point in keeping the ticket open, if no developer wants to work on it.

In my experience that will eventually just lead to a bug tracker full of "dead" tickets. If someone, not currently a developer, wants to work on such a trigger, the existance of the ticket won't make any difference anyway.
