### ISSUE TITLE
Load -> Spell Known: checked. My character knows the spell but the Weak Aura Icon won't load.

### ISSUE THREAD

**Issue by jesse-greathouse** [WeakAuras/WeakAuras2#1802]
**What steps will reproduce the problem?**
In the "Load" tab of my "Thunder Clap" Icon aura, when I check "spell known" and put "Thunder Clap" in the box, The weak aura icon will not load. This started happening when I bought the new rank of Thunder Clap at level 58; it stopped loading then. It seems like the Weakaura has identified the specific previous rank of Thunder Clap and will not recognize the new level of Thunder Clap.

**What is the expected output? What do you see instead?**
Since the form does not call for the exact spell ID, I think it should recognize any rank of Thunder Clap as being "known". The reason I'm using "spell known", for most of the weakauras that I create, Is because I expect that I can share the Weakaura with anyone, of any level, and if they have not learned the spell yet, the weakaura for that spell will not load.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I tried with loading only Weak Auras and I still experience the same result.

**Which version of WeakAuras are you using?**
2.15.5

**Are you on World of Warcraft Classic or Retail?**
- [X] Classic
- [ ] Retail

I have not tried this in retail.

**Was it working in a previous version? If yes, which was the last good one?**
It's unknown to me if this was happening in a previous version of Weakauras.

**Do you have an error log of what happened?** 
There are no errors.

**Please provide any additional information below:**
Here is the import string of the Aura with the problem:

``` !nAvyZjUnq0Fn9JjhgcP5lxNbsHgMHyNZYP96xmrylBRgJe1wgcz6KF79Ts2Gj31Rzgghz5v7(23(2vj2lokMjJ99gDT3GXXS6y2Wl9gFjwUjMLs)Gb5L69XRJzj6sDf2W3Z(BO95i7ZRONMy2HGSSAHj2)IH3miMXvjf6Qh0sf(2TZ8JMfsUrxMQ3Ry7LBfXtpTXS0CbfhEIrQv1uORn8kdwGJlvY2vzyzDHDnEZujZZfv1oGfDCdAzLaPHxmRPweILiw8MkUIVr0AolQOrLkQE7PBl5Bj3HJeSvuXnivz)YNbrWnjfIAwHEFGcic)Ds5E(bWvIDckXUtWlnfXSo)ITAiWYa4ZbzWQBwBnL1KLjFjMT62jSOvSOjHukUvuwUiT7G1cF4ghTSzTujUxNkCH9ozoasp)9qLW6p2dZwUeH7a4tBgoevoXAeTi7w3nj8(5pU0bSt0drFOkEoLbaSktxzjRgvBgYBmAW702eILQ8srBfV1cKRQeXNMdt(0eGG)tq(d5chTTTKFaGXcf7ot7YnihmnG4treincvC)ojLvbTte520sG(x4nWPImIkfV83HIHCG)WRCc8V2PCTYw5gN)7jbBHGsReNaWQwCjs0kucnKCrQ(4wFuk)XS3q11AWb472wfc53()3wcspuK32u12LiEXSQUGNEEQ3gXM103BTYT8NQBF9dmgWAxMMegZRKV(2tFPHNcmZF7POZJDFWpW6SbwNn4DoZz9F2hP2TfLzTJxM8yuaAF1qIiISi2pWFwpS46fcEmA5IJ7F2aQf((Zcxnnikk4(Wf)2DrDdW(MW(xn1gz2HtZ0ogeM8vQZyy3r)67p6ozTCDj1GBlNfc0uJpFnKHLAEAxlysjVU22dIxSJiEwHrK25c2pDQpK9htcdxeauSPP0i76bWHsiRoBtRRXCfUTPQNF998gttSRj8)UtzC6S5vI)UrOsoGK5YHJDB6i1hKVikB3OqM8SsaesJxn6KDDDAEEJgaE5zHy7ecCMqsKtQ4kR205kzc1wtEAjg(bVCJD8dOYGTDxlaa9YXlAiM7vTEJfvxtJnvzYCNvUAW8kmr15D2THZM578F)QAgzcgdcjQf3DxjrcPFvwZrfl1E1eniCQ78SeUBkitM((lsy9eMDAeE52cN33ltX9f2AEdD2Vm(gvEYOr)CEfnHIymB3nQwNAWB72xku50HX4mkvtLMZARXvvjp3FKoAPy74vskfAhHJ3lBCixdO(2)8zIRsk4QCXjp1AecZ2knUr0COlfm9U54BJNx)4r3bbM7ue)bb6YXx99ILlooJM23GEtcn0mJO(F0()Sy6KVwrvBzBQUc1jqNy)DacxnKqv8)c ```

**Comment by InfusOnWoW** [comment]
This should be automatically fixed with the next release. The old behaviour is opt-in now.
