### ISSUE TITLE
error in mythich

### ISSUE THREAD

**Issue by Pozzyx2019** [WeakAuras/WeakAuras2#1804]
**Describe the bug**
error in bugsuck when make dps

8x [string "--[==[ Error in 'Temple of Sethraliss - Nox..."]:15: table index is nil
[C]: in function `xpcall'
WeakAuras\GenericTrigger.lua:512: in function <WeakAuras\GenericTrigger.lua:505>
WeakAuras\GenericTrigger.lua:658: in function `ScanEventsInternal'
WeakAuras\GenericTrigger.lua:619: in function `ScanEvents'
WeakAuras\GenericTrigger.lua:752: in function <WeakAuras\GenericTrigger.lua:743>

**Comment by mrbuds** [comment]
This is not a bug in the addon, delete that aura with name starting with "Temple of Sethraliss - Nox"
