### ISSUE TITLE
AlternatePower API changes in 8.3

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#1808]
Just dumping this here for now https://github.com/tomrus88/BlizzardInterfaceCode/commit/ffbd8a3f993fb455aaff5726a8192b1a6d81f56c#diff-d7aabcfe763a5ad07076fd09fa911d89R21

**Comment by emptyrivers** [comment]
When does 8.3 land, out of curiosity?

**Comment by Causese** [comment]
they only said that it's not gonna release this year.
most likely january/february

**Comment by InfusOnWoW** [comment]
After looking at this in some detail and checking the bosses, it appears that we don't have to do anything.
