### ISSUE TITLE
Add more filtering options to Event - Combat Log trigger

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#1810]
**Is your feature request related to a problem? Please describe.**
When making an event trigger the user is forced to put some kind of hide in the field, this is great when people want to actually start timers and the like for events but if you just want to increment a counter it's just not really doable because if things happen on the same frame it just doesn't work. 

**Describe the solution you'd like**
A way to be abel to leave the field blank or toggle off the hide timer entirely. Currently setting 0 makes the aura just show up forever, I wouldn't want to take that functionality away. 

**Describe alternatives you've considered**
Using a custom event trigger, but this isn't really doable for most people. 

**Additional context**

**Comment by 1ps3** [comment]
Along with this I think it'd be really nice to see some more options inside of the combat log trigger for class and race using the `GetPlayerInfoByGUID()` function

**Comment by InfusOnWoW** [comment]
Are you talking about the built-in triggers? Or custom event triggers?

For the GetPlayerInfoByGUID, you'd have to describe in which cases that would be useful. I can't think of any good use case, nor have I seen any requests for it in discord. 

The built-in trigger does not have to cover everything, for niche cases requiring custom code is perfectly fine, so you have to actually explain how it would be useful.

**Comment by 1ps3** [comment]
I'm talking about the built in triggers. The other day someone was making an aura that incremented a counter on certain cleu event, using conditions to increment. If the events happened to close to eachother the aura wouldn't increment because the event tirgger required a timer. As for the GetPlayerInfoByGUID I don't think it's really too important but for classic a few times people have come in asking for class/hostility filtering. Just wanting to see spells casted by hostile units or certain classes only.

**Comment by InfusOnWoW** [comment]
Hostility is something I can understand, and that's certainly something that I can look at adding. class though, I'd like to understand why.

For the counting event triggers, we already have a separate ticket: https://github.com/WeakAuras/WeakAuras2/issues/1508

**Comment by emptyrivers** [comment]
Arguably we \*should\* provide full support for filtering on the source/destination flags of combat log events. Currently we provide the option to filter based on a subset of controller affiliation (i.e. whether or not the source or destination is part of the player’s group), so it is not a huge ask to also filter on the entire set of possibilities, as well as the controller type and reaction, and the object type. Documentation [here](https://wow.gamepedia.com/UnitFlag), for further reference.

Also, patches are welcome, this isn’t too complex of a ticket to implement.

**Comment by InfusOnWoW** [comment]
I don't want to add every option, as that would add another 8 options. That's essentially one page of additional options. I'll add hostility, since that seems to me pretty useful, and I already have the patch for that.

But the others, I'd like to see some reasoning, or some user requests that could have been solved with that. Ipse mentioned https://wow.gamepedia.com/API_GetPlayerInfoByGUID, which adds class, race, sex to the potential things we probably could filter on. But those don't seem that useful to me.

**Comment by 1ps3** [comment]
I've only seen it come up in classic discussion, people want to either see things that happen from hostiles and certain classes. A lot of the time for classes it's just people wanting to see everything that happens from a certain class of tracking general spells/item useage that comes from a certain class only.

**Comment by InfusOnWoW** [comment]
can you be more specific on the class thing? I don't undestand the benefit, nor how wide spread that kind of demand is. Adding class isn't that hard technically, just that I wouldn't want to add it if it's just for a few people's niche case.

**Comment by 1ps3** [comment]
The requests that I've seen come through discord are things like people wanting to see if a certain item has been used but filter by something like mages only. Or like tracking trinket uses but only healers or something, so that would be just the classes that can heal ofc.

**Comment by InfusOnWoW** [comment]
I only added a hostility check, as so far the class based sound to niche to me. Though that doesn't rule out adding it in the future if there's enough demand for that.
