### ISSUE TITLE
expirationTime is overwriting "Marked first" sort order (Hybrid sorting)

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1811]
**Describe the bug**
"marked first" sort order is overwritten by expirationTime when using hybrid sorting - marked first - descending.

**To Reproduce**
1. import string
2. apply arcane intellect + slow fall to yourself
3. see how B is displayed before A

**Which version of WeakAuras are you using?**
2.15.5

**Additional context**
only tested on ptr

``` !vBvxZPUnq0Fr9oycjT9rCc0KPudf50BU9bNiBlBuJrIRKmjKh43E3vYgBtGe60B)iZWWyVA1Qv7E2ZXrErHreDeP)N8o)tNhrwgrsXFG1CL8PiY8B(PRHxILQuMYNM8yQsUkI4xWF5fQkD7dHszHHdMEEAwMMzIc6fr206zTuzUEtSINgsJlyyOhg5dHa(Zuh5lLfsfSuGhUNG(2)pZ()a0i4OEfnHHlrOjgUuOTPUHQmWdW6zCbxVW9m8OZk8SrXZZzkTl6H7mGpMYIlZYc3SIfrUE0KzJVDcSU9vAPI2hpvwrXnPAxC1LXS1mHHa7I)Ce5(lhscVNeoCoeSs8qjRkOBGGte0LSQDz3cCamAHzrtqMPy2GqMnAYe0VsrtQzCjFISOCPG4U6ErefnLxQHQqpOYsf8LuSu0UsqsHehnEV7EOzjsbK)vxlHuWWaVKYfNU37QTNM)WoOf8Cre5YrbHJMBZo7fZcikJNZYR6GGRfsQfWvQz3Nuq16OyBDpbnUSeqx1Ts3Q7BvZFHTVreyvbwBdT8Sqlpl0YZcT6bOEmgSISzso2MMmACyDTLztLeAHR6d31mEUlRD4wCD3tJsZHca5RLufB7dJllk2(WNxWHqqu2BRdLLUbag8ey4QCv9wj4fab24OsezHDybhaHrg7MMFvT1zsn32XREFmxPHTaJQnye3keiw)ImfpsMoHjs5IC7naAfcZyygcQkK5dV6MBjqpGVeaVbNxNs1ZVdG2cMlP05bj3zkmxxc9AzYAyGctJGFO3ziue9jG902h67Y7pZtbOogVmfmiaZCud1MDurYcPAmA1D5ixoF0OaCGZalmDLPbz4YLBe2ubr)sJdVJWiQkzctKJhZzx0RoWvnXAChIo5TIiGXMyVQXijHHPe0IFR(U0FGfKTJOiVayaJ7YMDKtrwKkFsqEId3i)gdwqbEuqEG2FlUii1cGIc6wPOIYaQjYMzUiINBkHgdiLyB31)v0lOdwQi)Jr1ShtvxkUw8wify9Ry537SEVljyhYZdrVEaEolH(AwOZO9Af8DE9Ce5VUhz7l31PN8)xEqy4JAqFT4amZFB(iVQkCddzfqH9S5E9cAA3RE1PxgJRx5L7XHvVL8(hN1VmjcIgR4VS9HFTKMIdSG6E3J(eKPB59xANOwZnSSdVnCAL11Cnh)Wa)wzIdZm92Wj3emQY(bh9CgF1j9hLAdpBtJFwQdwOT0emfJPBN3T)oXt3riF2fUw4cgpFb4XfdA0Q(7lpHqHXk2xlzIKnOou)ZpiZk6NRAexAmsXuWbyWTAHf8Khfm4uFtQ1hzSvdXu2mhbTisSTMKLDYgVjCiyWr)x9BSS7TImggCDAg)EE2JHtwpAWxasMxKYL2Im6A72fTy1cNYql0X(eRyF7kUg)(XueNy5f9DbJStEgp0H2Vz69q87lk9KtUc7WhqgQTSpxGni7Wmq02mph39dG3x3P(IuN0(1F9GbtWwAnh7RO)aO70vu5ikpTfNozDNbN)JFGeEAjbCmzIwcpNM3ncpNK))xk84)Hr4Pdv)H1I(3tZPRI3ReE6Yo)pG4X3oLTtsT5W6l70uAR0Ci9L9OEBZqFc4UJkuUVUWbKK2jKDCni)3q4ANAxljhRAj)YFo7QV3JTmzwhvMxPxEq9PtvSbwDnC8d6J1HO)8 ```

**Comment by InfusOnWoW** [comment]
You have both A and B selected, thus both A and B would be before any other aura in the group. But the ordering between A and B is still via the expirationTime.

That's how it's supposed to work and afaik has always worked.
