### ISSUE TITLE
Bar growing from the center or from the sides

### ISSUE THREAD

**Issue by Dracolince** [WeakAuras/WeakAuras2#1814]
I've tinkered a bit making a bar that grows from the center or from the sides, but it ultimately is a 2-3 auras endeavor: left side, right side, and optional border on top.

So, if it isn't too farfeched to add it, I'd like to suggest adding two new grow options for bars: from center and from sides, with their mirrored sparks, overall borders and such.

It would look like this:

![example2](https://user-images.githubusercontent.com/49983316/68696531-6dd5cb00-057d-11ea-9ecd-15eeca6d44b8.png)

**Comment by InfusOnWoW** [comment]
That doesn't fit into the progress bar's architecture and would be pretty complicated.
