### ISSUE TITLE
Game crashing from WeakAuras/Azerite Gear Panel

### ISSUE THREAD

**Issue by Clouds15** [WeakAuras/WeakAuras2#1819]
**Describe the bug** - After opening WA's and closing it, and then trying to open the Azerite panel on my azerite gear my game crashes. Alternatively, opening the Azerite panel and then WA's also crashes the game. This is fixed if I delete two of my weakauras (they are spell animation groups, here is a link to one of the sets, importing them also apparently crashes other peoples game - https://wago.io/kw4cyDfMh). The WA linked has worked fine until about a week ago when I updated my WA addon. For more background information, the animations are part of a UI set and should function as such - https://www.youtube.com/watch?v=YlTFskRPyJA&feature=youtu.be. I have remade the WA's so that they are not outdated, but they broke when updating WAs. I updated them this morning and they were working fine until I opened/closed WA then tried right clicking an azerite piece (Sometimes it bugs out when opening the mission table by the docks). Expectation was that the WA should work and not crash my game when opening any other interface.

Side note, when importing the WA, people have stated that all the models get defaulted to the LK model. This may just be a common occurence in WA when trying to import models. 

**Do you have an error log of what happened?** No error logs. Bugsack/Buggrabber is not reporting any errors (Green). I tried running a profile in WA, but as the occurence crashes the game I can not capture a profile.
 

**To Reproduce** Import/make the WA, /wa, and then close WA's interface. Then right click on an azerite piece to open the azerite panel, game then  freezes/crashes.
 

**Screenshots**
![WoWScrnShot_111819_105748](https://user-images.githubusercontent.com/57912520/69073524-3c348800-09f3-11ea-9e80-8c8612c76274.jpg)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** All addons have been turned off and the error still occurs. No error when WA is disabled.

**Which version of WeakAuras are you using?** 2.15.5

**Was it working in a previous version? If yes, which was the last good one?** Unknown, it has been a few weeks before updating WA. I would imagine it was 2.15.1 > 2.15.3 range.

**Additional context**

``` HERE ```

**Comment by InfusOnWoW** [comment]
Can you try a downgrade? I would assume that it still crashes and that it is more likely that Blizzard changed something...

**Comment by Clouds15** [comment]
By downgrade, you mean using say only half the wa's?

**Comment by Clouds15** [comment]
I did notice there is now an output when logging into into game from WA's.
![WoWScrnShot_111819_115918](https://user-images.githubusercontent.com/57912520/69077284-e7950b00-09fa-11ea-9689-3a84e76c6caf.jpg)

**Comment by InfusOnWoW** [comment]
No, using a old version of WeakAuras.

**Comment by Clouds15** [comment]
Previous versions are not working now. I tried going back as far as 2.14.6. I don't remember what version I was on before the latest update. Will try a few other versions.

**Comment by InfusOnWoW** [comment]
Your settings appear to be corrupted, so you probably need to start from empty settings + importing your auras for a good test.

**Comment by Clouds15** [comment]
I did that this morning, somehow they are already corrupted. This is the second time it is happening, the group I have was not imported but I manually created the group/models. I guess I will try it again. Something else is causing them to be corrupted.

**Comment by emptyrivers** [comment]
Can you please verify that you have no other addons enabled, and this behavior persists?

**Comment by Clouds15** [comment]
Correct. I have shut off every addon except WA. I have even gone as far as completely wipe WoW from my computer and start from scratch. And it continues to happen, somehow the Models are getting corrupted. Have not had any issues until about a week ago.

**Comment by Clouds15** [comment]
Any ideas what the issue might have been and/or suggestions to prevent it from happening/becoming corrupted?

**Comment by InfusOnWoW** [comment]
So from what I can tell there's just too many models created in these scenarios. I have some ideas on how to imrpove that a bit, and that will come in one of the next releases.

**Comment by xl0418** [comment]
Similar issue here. I afk for almost one year. Yesterday, I logged in and found that all animations are defaulted to LK models. And when opening wa, the whole game got stuck for a while and crashed. Then, I tried more times and the game persists but still got stuck for like 10 seconds. I am also using some strings from Birg's ui but modified by myself. 

So, in sum, two issues:
1. Opening wa causes stuck and game crash.
2. All animations are reset to the same animation code, i.e. the LK model.

**Comment by InfusOnWoW** [comment]
All animations being reset is not a bug. That was a change Blizzard did in 8.3, which we can't do anything about. Models no longer have  file names and since your settings contain file names, the models are no longer found.

Your settings would be interesting though, to see if the optimizations I do help enough to make opening the wa settings possible.
