### ISSUE TITLE
Overlay Cost of Casts bugged with Far Sight

### ISSUE THREAD

**Issue by Rothgate** [WeakAuras/WeakAuras2#1822]
The Trigger: "Overlay Cost of Casts" under [Power>Player] get stuck after the Shaman class has used the spell "Far Sight" . Casting any other spell with a cast time will "fix it" and clear it.

**Comment by mrbuds** [comment]
[Prototypes.zip](https://github.com/WeakAuras/WeakAuras2/files/3902915/Prototypes.zip)

@Rothgate can you test replacing this file in Interface/AddOns/WeakAuras/ ?

**Comment by mrbuds** [comment]
or try this version of weakauras https://github.com/WeakAuras/WeakAuras2/suites/323199490/artifacts/399495

**Comment by Rothgate** [comment]
That fixed it! You're amazing!
