### ISSUE TITLE
Border coloring based on debuffType

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1823]
a**Is your feature request related to a problem? Please describe.**
I wanted to add something that improves the awareness of removable debuffs further (poison, curse, disease, magic) on icon-Type auras

The initial idea was to request a feature that adds icons to the aura which was implemented some time ago
![](https://media.wago.io/screenshots/g0zAi7Ivc/5dd0c94fe650bc426c85ad71.png)

I feel like that's not enough to make users aware of it so I wanted to request a feature that changes the border's color based on the debuffType, e.g:

![](https://i.gyazo.com/741a5702fd2137de037f713c9d40dea6.png)

It's basically how blizzard does it too. 
Here you can find the exact color values: https://wow.gamepedia.com/Debuff

**Describe the solution you'd like**
A checkbox or something that appears at the border's settings that says "DebuffType based coloring" or whatever.

It should maybe not show the border by default, only when trigger is active

**Describe alternatives you've considered**
manually handpicking the color :| and running into risk that it's not a dispellable debuff

**Comment by mrbuds** [comment]
![img](https://i.imgur.com/NGuKn5A.png)

**Comment by Causese** [comment]
well that solves it
