### ISSUE TITLE
glow/borders don't adjust to the icon's border

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1825]
**Describe the bug**
the glow / border's position doesn't adjust to the icon's border when using skinning addons, such as masque.

**Do you have an error log of what happened?**
no error

**To Reproduce**
1. grab masque addon, change skin to "dream"
2. import string & check it out

**Screenshots**
![](https://i.gyazo.com/bd39eae6327b8491e07d927d5ec82901.gif)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
2.15.5

**Additional context**

``` !TRvBVPTYs4)lv6i1(HuHbd4KVfOqkrutoSK2gPitm2lWEQzn1EDcjQIF7Nz21gBSnjKgDvZjxQQsShVVm7mpZmpEIT0SgzrcTiv)Ow9pw3ISWI4I)hKolW)olYWEN9z4Mj(bU0Gw2o)WnWFPfPLh7HhSdCxFZiFFpbdeTAW0PHuHLPMXhnmmA0uZOjSI3hlUB9Mg1nA0qVIr96g1pUQ10J0HNBZDM7hCHpJlSiT7yoQZWKTRTVNFaOkMAwMvSmRk)zn5p1rHWeaDKS02HI3sSDemFEO8ijSdeWfWqMY4SW5QRHlvsHRfbSzZObHQny0gb4LU0jrtNo6(LulYN70)IUx2hEU8w7Oa7QWgSK651ZnuTUHrtO3s5ccml2klY42NsgnMm60HWIfHBkzPN99WIVzOxeqLdLCrN(WIlLbBg12tm3IWTxqdt00iEQQjuIC89IwWtp6b2USOqWgvPcAszlSrtrwlbXfuCu4y15iK64Zb9p(yX95uCHxyZ47)O3yB3VXdZW2JnJN6ObTtEWaFkAzgsNf7bHH65BlbIrH0XoE2HHwtK2Dhu4Iia1LyGupnV0q2d08cbXtIbXzrxAs0LMeDPjrxvGObrIPKk3zhBpLXwHorzQR64odoJKFgzhqxFt3ipV138T5myAKa5bsbKCVh8QmhiUkAzYujOoAI4jFWlPStKiged(LZATC1zAoxyEgglYCvlYWpHGEHY9IwnWodgrUOlG(HZdz4PFQ3Le0qjXgvt2PKOtDWWYwaisti4t47ClecixlJk1qWdU30v2lw6bNfPUU(g5UmLnt5xqL5BmxaMAUj(TBaayvAiP9WoDmriG304W6(D6UjhspUkjbaEW5arD2cBv4BGtFkFgUU1AGW4ibSYdwksHeiOIL5EaA0xEyMGX2cAa327RjhOQ6YPSj(EMhKqRvMevO1lku4VyeDfcMJ4YeiV)dRppGkIc4RV5D)AupCDNcgZRVUd3XpcV9C)iCRU(6l7DuNZpQh6eob)x16noPH(jnHloP2XNuV5VeVB95uUBAIqZk7iPNdKj11)oo5ogyhBLv5UCPlIcjrX)ozOsKhE2bfaNXFOCAPzRYNhR8SDLKttM8(w6iLWV47cy3J0QOsAx0XkDMFFllAz58YK9zxzOYKZB)gDAoV9A8c0YhAlWNl9vOM)45E0In)PzdJDMasyC4CB3Tp6sXcjeUDuqiDRbUh1qvJonA90lhnibIEv(95FamjB69POwzYiQkcYCGzNeZcO)kDson1QvqRDEA7GCCt9rfRBa7H1383r2UyodG6X22Kc66TSq2epzOugLi(uo4sq9h3AWOrd(sMDrLqwRrIbOGkJdsfebRq)EWbwGk(E5E(lN)d4Bos)pVZPNP5gNJQ4rMXCvbnn1XvTYZYXbB1CkB2Cbw(lLXXZGKbsoHdP4K0b2bJdmIVBa9NruUZ9i1IQLx6fhNsdVGTI6flyoZ5hCkS1ynY7u1DrLTC2UBy4ML3RyBIiYQfexwiM)gRDblDnDD9gQDmPiSwLTR7)dkD5POPrmet1Hh4Dw8VqT9YQLRQHHWZpXcTbWGRCnJe(j5jjB4CH0swIwfGucwhN8GV)c0wwd5uUCUABWhLfPThqyjzRzN)HAD70(9MF3fnHOJrX5lnYljMcC4PzWNuKsI0cYahgS(nv32kHVysMIeMifS2VnyJ88EpS8g0xq5(xhVIZHY9hk3FOC)tAh3)Y(5DS7v5(ICf2z5(D0(GYib8)MY9N2MmNHVfrXc(Lu09)UnU6rEjVI8tYxyTKAX7B5D(WbKVz8H3p7F4B)6)55lKYKid9INprf8jo2HI13eQ8RLq)PadPDrLklfSmutYXZidXWsj2L0HG88rQ9gVZippwYh6FYH(NCGq1bcvVMiu9yn943Lr1Jqs7jjwLIkE92)KjrcHpFamaidBz0QY)sNLqZAp7ysMcVpwZtYvU(L04KSD(yNuqunjzNuxEXDmP2Nho6kTVEvRk9FQoMKq9OSoLKLkI(gQit()0wH8MKz)H(5CG(Xb6hV5OF8783Vzxuw2lEhfqjjV96gJs83Lr8hAW4WKVTI47Zyq6A0W44QhBOvrVEZAnAuZA6r11Z4dZyKINDMZBSe6U)SpIhHFgD91AVNEsQsjLVZq05PBwtX)kj7hTIbhl4n)E7P6(R2IZKXJ1RMDXYzVikLaAEjTOzR(MuE7AkHGzE6ILsVSe(u54nbp5wy86vrRO1)( ```

**Comment by InfusOnWoW** [comment]
This is mostly fixed for the next release. E.g. round skins + skins with very wide borders don't work, but all normal skins do.
