### ISSUE TITLE
Having issues with weakauras not opening

### ISSUE THREAD

**Issue by Burrill1** [WeakAuras/WeakAuras2#1827]
**Describe the bug**
When I relogged last night my weakauras didnt show up and /wa and /weakauras arent opening anything anymore

**Do you have an error log of what happened?**
 I do not

**To Reproduce**

1. Have Details, Mik's scrolling battle text, Elvui, and DBM downloaded
2. Type /weakauras

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I have disabled all other addons, including ELVUI and unfortunately it didn't help

**Which version of WeakAuras are you using?**
2.15.5

**Was it working in a previous version? If yes, which was the last good one?**
It did work in the most recent previous version, however it didnt stop working when i updated. I also tried downloading that previous version to see if it would work, and it doesn't

**Additional context**
Its not an individual aura unfortunately

**Comment by mrbuds** [comment]
Are you playing on classic or retail ?
Can you check that you don't have the wrong version installed ?
Do you have a message in chat from weakauras showing you use wrong version ?
Did you install bugsack ?
If you installed weakauras from twitch app, please reinstall twitch app with last version.

**Comment by Burrill1** [comment]
Retail.
Ive tried both the previous version and the newest version.
There is no message in chat when I type /wa or /weakauras
I haven't installed bugsack
I reinstalled the twitch app and unfortunately it still isnt opening

**Comment by mrbuds** [comment]
> I haven't installed bugsack

**Do you have an error log of what happened?**
If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install https://www.curseforge.com/wow/addons/bugsack & https://www.curseforge.com/wow/addons/bug-grabber, yes both are needed. 
Note that if the error looks like `[string "--[[ Error in ' my awesome aura' ]` then the bug is in the aura that got mentioned, not in WeakAuras itself

**Comment by Burrill1** [comment]
This is what came up when i opened up the addon, nothing seems to change when i type in /wa or /weakauras
![image](https://user-images.githubusercontent.com/58093626/69470812-231b3680-0d67-11ea-911e-f1024eacaf81.png)

**Comment by mrbuds** [comment]
Can i ask you to open the file `WeakAuras/Prototypes.lua` with an editor and change the line 2787 from
`spellName = trigger.spellName;`
to
`spellName = trigger.spellName or "";`

**Comment by mrbuds** [comment]
and then just /reload

**Comment by mrbuds** [comment]
i have edited the thing i asked you to change

**Comment by Burrill1** [comment]
Everything is working! Thank you!

**Comment by mrbuds** [comment]
Good thanks for reporting and helping fix it :)
I'll reopen the ticket until a fix is merged
