### ISSUE TITLE
works only in classik now

### ISSUE THREAD

**Issue by badborz** [WeakAuras/WeakAuras2#1830]
After update it works only in classic and i play bfa.

**Comment by InfusOnWoW** [comment]
Twitch is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing Retail on Classic and vice versa. Ensure that you have got the right version selected but if you do and it still installs the wrong version then you may have to just install manually with the zip.
You can get the latest versions from:
• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
    (see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like https://github.com/AcidWeb/CurseBreaker or https://www.minion.gg/

Most importantly this is a Twitch issue that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is.
