### ISSUE TITLE
Taxi conditional for classic

### ISSUE THREAD

**Issue by pmb123** [WeakAuras/WeakAuras2#1836]
Please add a "in taxi" load condition.  My previous ticket was closed saying vehicle would account for this, but vehicle is not in classic.

**Comment by mrbuds** [comment]
Taking a look at how it's done by the addon TopGun https://www.wowinterface.com/downloads/download25413-TopGun

It hook the function TakeTaxiNode
When the function is used, register UI_ERROR_MESSAGE and PLAYER_CONTROL_LOST
On UI_ERROR_MESSAGE unregister UI_ERROR_MESSAGE and PLAYER_CONTROL_LOST
On PLAYER_CONTROL_LOST set a local IsFlying to true and register PLAYER_CONTROL_GAINED and unregister UI_ERROR_MESSAGE and PLAYER_CONTROL_LOST
On PLAYER_CONTROL_GAINED set IsFlying to false and unregister PLAYER_CONTROL_GAINED

**Comment by mrbuds** [comment]
I don't see how to implement that with how load events are implemented at first sight

**Comment by InfusOnWoW** [comment]
yep that sounds too complicated for my taste. You'll have to lobby blizzard for a less broken system.

**Comment by pmb123** [comment]
hi, asakawa helped me with a custom trigger.  could this be added as a default option?

function() return not UnitOnTaxi("player") end

**Comment by InfusOnWoW** [comment]
The ticket already explains the problems with adding that, afaik nothing has changed.
