### ISSUE TITLE
Load condition per character

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#184]
Is it possible to have one weakaura but have load conditions per character?
One scenario would be this weakaura https://wago.io/UseArtifactPower, which you only want active in your holy paladin specc and guardian druid specc. You cannot use talent specc because Guardian specc equals Retribution specc if you logon to the other character.

**Comment by Healarious** [comment]
A temporary solution would be to just duplicate the weakaura and make 1 load for your guardian druid spec and the toher for your holy palladin spec, this should resolve the issue for you for now

**Comment by Stanzilla** [comment]
No plans, sorry.
