### ISSUE TITLE
Remove "delete" option for groups

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1841]
I had a feedback in my guild that the `Delete` option for groups is confusing and many make the error of using it instead of `Delete children and group`, and suggested to merge them and ask if user want to delete children or not. I'm more for just removing the Delete option.
What do you guys think ?

**Comment by nullKomplex** [comment]
I've had to ingrain into users that I play with and help that you need to hit "Delete children and group" if it's an available option. Only had problems with auras getting spat out everywhere, never once used the regular delete on purpose.

**Comment by emptyrivers** [comment]
I'd be fine with it.

**Comment by InfusOnWoW** [comment]
Yeah, let's see who complains and for what reason.

**Comment by InfusOnWoW** [comment]
Do note that we should probably do that in two steps:
1) Remove the Delete option
and some time later
2) Rename the "Delete group and children" entry to just Delete

**Comment by Causese** [comment]
i have a feeling that it's related to them not knowing what children are, I assume buds guild is french & translation might suck so another pop-up that gives you the same options might not help.

it's also 2 clicks 🗡
