### ISSUE TITLE
Soul Shard counter not displaying on weakaura

### ISSUE THREAD

**Issue by Denziz** [WeakAuras/WeakAuras2#1846]
Hello! So I have this weakaura that shows the cooldown of Shadowburn (I play a Warlock) whether it's on cooldown or not it displays the WA always.

The problem is that I had a soul shard counter on the WA icon by using the text 2 custom function %s which would show how many soul shards I have in total (the spell costs 1 soul shard if I had 15 it would display 15 in the bottom right corner). However this is not the case anymore.

**Comment by InfusOnWoW** [comment]
There were questions in the bug report template. Please answer them to the best of your ability.
