### ISSUE TITLE
spellcount not working since latest patch in classic dec 10th 2019

### ISSUE THREAD

**Issue by yespls16** [WeakAuras/WeakAuras2#1848]
i'll use blind(rogue) as an example, i used spellcount in my text options to show many casts i am able to do(basically # of reagents on me) it was all working perfectly prior to the bg patch, and as soon as i got the update it stopped working.

symptoms: without opening the /wa window once, the number(text) for spellcount on blind would simply not appear, nonexistent, however if i /wa and close it without doing anything, it'll show the number "0" and only 0, while i have 70+ reagents available, same goes for other skills of the same nature such as vanish etc.

**Comment by InfusOnWoW** [comment]
There are questions in the bug report template. Please try answering them.
