### ISSUE TITLE
spellcount not working since latest patch in classic dec 10th 2019

### ISSUE THREAD

**Issue by yespls16** [WeakAuras/WeakAuras2#1849]
## Describe the bug

i'll use blind(rogue) as an example, i used spellcount in my text options to show many casts i am able to do(basically # of reagents on me) it was all working perfectly prior to the bg patch, and as soon as i got the update it stopped working.
**Do you have an error log of what happened?**

no only reporting other addons

### To Reproduce

1. import string
2. look at bottom right of square for the text(number)
3. make sure to have blinding powder in inventory
4. see no display of spellcount
5. open /wa and close to see 0 instead of nothing, but still incorrect

**Screenshots**

https://imgur.com/ZD5FFwL
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes
**Which version of WeakAuras are you using?**

2.15.5 also in screenshot
**Are you on World of Warcraft Classic or Retail?**
- [ X] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

it was always working fine, just until the BG patch in classic that went live on Dec 10th, 2019 that this started happening.
### Additional Info

```
https://wago.io/nWxm-__3b
```

**Comment by mrbuds** [comment]
I asked a rogue friend to type `/run print(GetSpellCount(2094))` for his Blind and it return 0 instead of 16

**Comment by mrbuds** [comment]
The API for GetSpellCount doesn't return the information anymore, you will have to add a second trigger "status >item count" and in display use "%2.s"
