### ISSUE TITLE
Chat message (say) condition calls unknown function in Combat Log Event trigger

### ISSUE THREAD

**Issue by jesse-greathouse** [WeakAuras/WeakAuras2#1851]
## Describe the bug
When I interrupt a cast with Pummel or Shield Bash, my character should say that there was an interruption on a spell with Pummel or Shield Bash respectively. Instead I receive and error.

### To Reproduce
Create a "Text" Weakaura
Under Trigger select type: Event, under event select: Combat Log
in Message Prefix, select: Spell
in Message Suffix, select: Interrupt
Check: Source Unit and select: Player

Under Conditions create a new condition.
in If Trigger 1, select: Active and select: True
in Then, select Chat Message and select: Say

In the Message text box put: %spellName on %destName's %extraSpellName

Then fight a spellcasting mob and interrupt them with any spell.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I tried testing this with only WeakAuras installed, the result was the same.

**Which version of WeakAuras are you using?**
2.15.5

**Are you on World of Warcraft Classic or Retail?**
- [X] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes, this was working in a previous version. It was only after the last wow classic update, on December 10th 2019, that this started happening. 

### Additional Info
Here is the Aura export string:
`
!nsvtZTjmq0FnDAV0u)rYHEmodEQNHGDSW1T9GILHfSAbjgjHJDo4F7DxjG42tzGb2D1h7BF7tIpMNYz1Cwo9IM6wxLubC2YnPXlsI4ScTYXKVc8KXt4StllkSGJNmcxG02ujoNcNCC2hA4SZxnOqLDqBwPLkCWhIssJwZzoD2rWyLAfUBJNoAkN1kXup9R)O4t)k9PJ2yoltxPniwsg7FN4)o1)9w6lUFzTwNUMs8MMCHdHBB3FrloGWjZ2kZDh4S7rFmAMdZPLkqRtyCObUlsLSZQanTh82ONZillrygWq6qaV55gmlWrGkRwvNHtwd59W65dYCyiwERrqjNZUByDpOR3lCx2fRlra1U3hELbkKN4m2QO443cZAl8HFEbrHR3ScbHsud2aYTnqv1I8oVwl8Sv3AYGnuTnJGi(NrTje)9a8FkIRM)W8YH9yAt9t7BrXRMVj2V9Q3ycptr86rine8rnw2jFE8iAeduIfDyhCEbckeaJsu99EbWKB5SFJaswCMZIJMtnhOQOtYmBzA6YhXLHC4Q26AO6lZeypI6WOWAztFhLAFgKqWUKWjOowN2BofnGa2dRJIsO(8jipOmsMmAeP1ufYYWUiuY6qR6kzsxdxPPZe99Yoc0c4YrQhxBTqQE)ZEqU9(MVZRgw7z0Uk(fTjFRrGN52oyrtx2ZkbHB2bi7pxRGj25OWif7ROuCq)c5x1c9hSoiuLWBBqym6kcWAfLqh2y3)ZHq4rFVimbz7l70Ql7(qoyDK7hTOd28ncw)mOK0y0nGXD2NohV)HvPf(7GivCwLWA57do0Xmd5eIsThPQKQGT3VE9IL4nl1TvojnsFKzDexdK5XF34HG01z)xqx4MooBUr(6LDp1kYj90LDPHZzC2KBgF3n4H4Ji3C7eIU4)n
`

```
 Date: 2019-12-12 14:13:35
ID: 1
Error occured in: AddOn: WeakAuras
Count: 1
Message: Note: AddOn WeakAuras attempted to call a protected function (UNKNOWN()) during combat lockdown.
Debug:
   [C]: ?
   [C]: ?
   WeakAuras\WeakAuras.lua:4383:
      WeakAuras\WeakAuras.lua:4383
   [C]: pcall()
   WeakAuras\WeakAuras.lua:4383: HandleChatAction()
   ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:237: SendChat()
   [string "--[==[ Error in 'Pummel/Bash':'condition ch..."]:27: ?()
   WeakAuras\WeakAuras.lua:5701:
      WeakAuras\WeakAuras.lua:5666
   WeakAuras\WeakAuras.lua:5783: UpdatedTriggerState()
   WeakAuras\GenericTrigger.lua:663: ScanEventsInternal()
   WeakAuras\GenericTrigger.lua:610: ScanEvents()
   WeakAuras\GenericTrigger.lua:747:
      WeakAuras\GenericTrigger.lua:743
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AtlasLootClassic, vv1.4.2
  AtlasLootClassicData, vv1.4.2
  AtlasLootClassicDungeonsAndRaids, vv1.4.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BlueShamans, v
  ChocolateBar, vv3.3.4
  ClassicCastbars, vv1.2.0-hotfix
  ClassicCastbarsOptions, v
  Coordinates, v2.1.0
  DBMCore, v1.13.24
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r039
  Details, v
  DetailsTinyThreat, v
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  GearMenu, vv1.1.0
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LetMeCast, v1.3
  OmniCC, v8.2.5
  Prat30, v3.7.43
  Prat30Libraries, v
  Questie, v5.3.1
  RealMobHealth, v2.15
  ShadowedUnitFrames, vv4.2.1-Classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TinyTooltip, v8.2.1
  TradeSkillMaster, vv4.8.23
  TradeSkillMasterAppHelper, vv4.0.5
  WeakAuras, v2.15.5
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=5e4)

```

**Comment by emptyrivers** [comment]
Hi, thanks for the report. Unfortunately there is nothing we can do to fix this, as sending a SAY message is restricted in non-instanced areas.

**Comment by mrbuds** [comment]
I think the error is already fixed, it won't work for next version but will not make an error
