### ISSUE TITLE
Status Totem isn't finding totems

### ISSUE THREAD

**Issue by SkroneTone** [WeakAuras/WeakAuras2#1855]
Prior to the update, using a Trigger set to Status -> Totem -> Totem Number allowed me to see the status of that totem number;if the totem is active, which totem it is, and its duration. With the update, this trigger never occurs.

**Comment by InfusOnWoW** [comment]
While we aren't very good in mind reading, and thus require actual answers to the questions we ask in the bug template. In this case I would assume you are playing classic. In that case, that is because Blizzard removed the api and thus totems can't be tracked anymore.
