### ISSUE TITLE
"Attackable" triggering on dead targets.

### ISSUE THREAD

**Issue by Drexl** [WeakAuras/WeakAuras2#1858]
## Describe the bug
Status --> Unit characteristics --> Target --> Attackable
This trigger should not activate on dead targets, but is. Dead targets are not attackable. If you attempt to attack such a target your character says "I can't attack that".

**Do you have an error log of what happened?**
Not applicable

### To Reproduce
Create a trigger as described above.
Target a dead creature, that would otherwise be attackable if alive.
Observe that the trigger activates.

**Screenshots**
N/A

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
2.15.5

**Are you on World of Warcraft Classic or Retail?**
Classic

**Was it working in a previous version? If yes, which was the last good one?**
N/A

### Additional Info
N/A

**Comment by InfusOnWoW** [comment]
That's because that's what the blizzard api returns.

**Comment by Drexl** [comment]
While I wasn't certain, I figured that was likely when writing this. However, since an average user not accustomed with the WoW API is likely to make the same conclusions I did, would it not be reasonable to add a check for UnitIsDead?

**Comment by InfusOnWoW** [comment]
Well maybe, though I think what the trigger does is fine.

**Comment by wazerstar** [comment]
> Well maybe, though I think what the trigger does is fine.

Will this ever get fixed for TBC too, attackable and unit is dead will still show :D
