### ISSUE TITLE
Big Green Blocks

### ISSUE THREAD

**Issue by NubiaSkye** [WeakAuras/WeakAuras2#1859]
Whenever I enter combat WA pops up big multiple green blocks that obscure my screen. The only way to clear them from my screen is to shift+click o pause addon execution.

 Any idea how to prevent this? I need WA for Queen Azshara fight.

![WA-Error](https://user-images.githubusercontent.com/58920346/70871556-37211500-1f6e-11ea-9857-2997c1eda805.png)

**Comment by InfusOnWoW** [comment]
Those are auras you have installed. You need to go through your aura list and figure out which auras it is and remove it.
