### ISSUE TITLE
"C_Timer.After duration is too large" on 3 days cooldown

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1861]
## Describe the bug
Reported on discord by Cartina#1384
Lua error: 

```
1x WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:75: C_Timer.After duration is too large
[C]: ?
WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0.lua:75: in function <WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0.lua:32>
(tail call): ?
(tail call): ?
WeakAuras\GenericTrigger.lua:2403: in function `WatchItemCooldown'
WeakAuras\Prototypes.lua:2872: in function `loadFunc'
WeakAuras\GenericTrigger.lua:915: in function <WeakAuras\GenericTrigger.lua:875>
WeakAuras\GenericTrigger.lua:963: in function `LoadDisplays'
WeakAuras\WeakAuras-2.15.5.lua:2190: in function `LoadDisplays'
WeakAuras\WeakAuras.lua:2035: in function <WeakAuras\WeakAuras.lua:1901>
WeakAuras\WeakAuras.lua:2131: in function `ReloadAll'
WeakAuras\WeakAuras.lua:1790: in function `ScanAll'
WeakAuras\WeakAuras.lua:1735: in function `Resume'
WeakAuras\WeakAuras.lua:1555: in function <WeakAuras\WeakAuras.lua:1520>
 
WeakAuras\WeakAuras-2.15.5.lua:1661: in function <WeakAuras\WeakAuras.lua:1613>
```

SV: http://www.mediafire.com/file/fg8fa82jka0h6rf/WeakAuras.zip/file

My guess is error is coming from this trigger https://i.imgur.com/y8w5vOY.png
https://classic.wowhead.com/item=15846/salt-shaker
Which is a 3 days cooldown

**Comment by InfusOnWoW** [comment]
In my testing it takes a far longer cooldown to trigger that warning. For me that's ~20 days. But! There's already a check in WeakAuras that prevents scheduling timers that are longer than 1 week, something is strange. 

So please add to this:
/dump GetTime(), GetItemCooldown(15846)
/run C_Timer.After( select(2, GetItemCooldown(15846)) + GetItemCooldown(15846) - GetTime())

**Comment by Cartinaa** [comment]
**The result of the dump:** https://i.imgur.com/WGfkHYa.png
```
Dump: value=GetTime(), GetItemCooldown(15846)
[1]=4199623.264,
[2]=4111541.014,
[3]=259200,
[4]=1
```

**The result of the run:**
```
1x [string "C_Timer.After( select(2, GetItemCooldown(15..."]:1: C_Timer.After duration is too large
[C]: in function `After'
[string "C_Timer.After( select(2, GetItemCooldown(15..."]:1: in main chunk
[C]: in function `RunScript'
FrameXML\ChatFrame.lua:2033: in function `?'
FrameXML\ChatFrame.lua:4666: in function <FrameXML\ChatFrame.lua:4613>
[C]: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4327: in function <FrameXML\ChatFrame.lua:4326>
[C]: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4363: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = 170122.980000
(*temporary) = <function> defined C_Timer.After( select(2, GetItemCooldown(15846)) + GetItemCooldown(15846) - GetTime(), function() end):1

```

**Comment by InfusOnWoW** [comment]
That's the 49,7 day bug. That is your computer has a uptime of 47,5 days, and if we try to schedule a timer for 47,5+3 days, that's too big for wow. There's nothing we can do to fix that, it's a wow bug. 

You need to restart your computer.

I'll add some code to handle that with a clearer message, but I strongly recommend to restart asap as the game won't cope well the nearer you get to 49,7 days of uptime.

**Comment by Yenlari** [comment]
I'm really sorry to re-open this issue and after some searching I'm still not sure how to produce an error log, but I'm facing the same issue upong logging into any character. It keeps saying I should restart my computer, which I did multiple times - I also never let my computer go to sleep or anything, it always gets shut down completly. But this error message will not go away.

Screenshot: https://i.imgur.com/tDlLkuX.png

Also please tell me how to produce a log so I can provide one as well, that'd be greatly appreciated!

**Comment by InfusOnWoW** [comment]
Whatever you are doing is not a proper restart. That output comes from directly from GetTime() which is the uptime of your computer.

**Comment by Yenlari** [comment]
I'm not trying to come off as snarky but I even unplugged the computer, then turned it back on. The timer can in no way be correct.

**Comment by InfusOnWoW** [comment]
Neither of these indicate that you rebooted your OS. The timer is correct, you can verify that by entering this in your chat window
/dump GetTime()

and reading https://wowpedia.fandom.com/wiki/API_GetTime
