### ISSUE TITLE
Allow multiple sets of loading conditions

### ISSUE THREAD

**Issue by semecan** [WeakAuras/WeakAuras2#1862]
**Is your feature request related to a problem? Please describe.**
No, it is a quality of life request.

**Describe the solution you'd like**
I would find it very useful if you could have multiple sets of loading conditions. This would enable loading auras in multiple distinct scenarios. For example I would like to load some auras either when in combat or when in a dungeon. If I am in the open world farming herbs or so I don't need my auras out of combat, but inside a dungeon I would like to see them even when not in combat.

**Describe alternatives you've considered**
I think this already could sort of be done by using triggers, but that would mean the auras are loaded to check the triggers and also setting up loading conditions is just way more convenient, especially when setting up mulitple auras.

**Comment by InfusOnWoW** [comment]
Well setting up the load settings is much easier than doing that via triggers, exactly because they don't support what you (or others) want in additional flexibility.

I don't see a way how to easily add that to the UI without making it more or less as complicated as it would be via triggers.

**Comment by semecan** [comment]
My suggestion would have been to make the load conditions tab tabbed itself. That way the load condition page itself stays exactly the same, but you have multiple sets of conditions. There wouldn't be a need to add the option to "combine" them (like "when conditions x and y are active, load the aura"). If one condition page is validated, the aura is loaded. At least for me, that would already cover all use cases.

**Comment by InfusOnWoW** [comment]
Sorry, that doesn't sound like a user interface that would work very well.

**Comment by semecan** [comment]
Would you mind if I make a mockup screenshot of another idea I have in mind? It would basically just add a dropdown menu with delete and add buttons. Or is this a feature you will definitely not implement?

**Comment by InfusOnWoW** [comment]
I can imagine how that would look like, so no need for that. But again that feels like a strange addition to the load options. They are not supposed to be that complicated.
