### ISSUE TITLE
The interface menu doesn't open when you put in the command or click on the minimap icon.

### ISSUE THREAD

**Issue by SatanicBitxh** [WeakAuras/WeakAuras2#1869]
## Describe the bug

I was expecting the interface menu to pop up so I could put in my auras after updating, but when I typed in /wa or clicked the minimap icon, nothing happened. It didn't open, it didn't say anything, nothing.

**Do you have an error log of what happened?**

I do not, but since I just updated weakauras, and that was the only addon I updated, and all of my weakauras I had got deleted so there were no auras to cause an issue.

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, I disabled all of my addons except weakauras and nothing changed.

**Which version of WeakAuras are you using?**

I was using the 2.15.4 retail version for BFA 8.2.5 and it worked fine, then I updated it to 2.15.5 BFA 8.2.5 and it didn't work so I tried to go back to the 2.15.4 version and the issue persisted. 

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes, it worked when I was using the 2.15.4 retail version.

### Additional Info

```
  ERROR HERE
```

**Comment by InfusOnWoW** [comment]
You skipped over this part of the bug report template without doing what it suggests.:

 **Do you have an error log of what happened?**
