### ISSUE TITLE
Spell Known does not report spell name with %1.n

### ISSUE THREAD

**Issue by corporategoth** [WeakAuras/WeakAuras2#1871]
## Describe the bug
If you use %1.n, %2.n, etc. with a Spell Known trigger, you just get back the name of the aura, not the name of the spell

### To Reproduce
1. Create a Spell Known trigger with a spell
2. Use %1.n in the text to display

**Which version of WeakAuras are you using?**
2.15.5

**Are you on World of Warcraft Classic or Retail?**
- [X] Classic
- [ ] Retail

**I fixed this locally by adding:**
```
    nameFunc = function(trigger)
      return GetSpellInfo(trigger.spellName or 0);
    end,
```
to the Spell Known entry in the WeakAuras.event_prototype array (Prototypes.lua).  This fixes the problem.

**Comment by mrbuds** [comment]
> Create a Spell Known trigger with a spell

Which one ?

**Comment by corporategoth** [comment]
There is only one "Spell Known" entry in the event prototype array.   It's under 'Status' (as the type) in the menus.  It doesn't matter which spell you choose.
