### ISSUE TITLE
[master] Pixel glow color unchecked itself after upgrade from 2.15.5 to master

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1872]
## Describe the bug
Pixel glow color box unchecked itself after upgrading to master instead of keeping the currently selected glow color (white). 

### To Reproduce
1. import https://wago.io/bfaraid5 on 2.15.5
2. check "01 Scales of Wrathion" pixel glow color
3. upgrade to master and notice how it changed from white to yellow / unchecked

**Which version of WeakAuras are you using?**
2.15.5 & 2.15.5-63-g9f61464

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Comment by Causese** [comment]
i'll just dump this here:

it might be neat if better action button glow default values are picked for icon-type auras (x/y offset)

this is how it looks:
![](https://i.gyazo.com/c0f0928353d91a576c14ce91631b1306.png)
and it looks pretty much the same without masque besides the skinning part

especially since you can't change x/y offset in wa for actionbutton glow.

before the update it looked better for masque users
example:
![](https://i.gyazo.com/b3949bc86bf9cb5d68aa52078fdf91b1.png)

**Comment by InfusOnWoW** [comment]
I'm not sure why it looks different, that might have been my fix to adjust it to fit all masque skins.

**Comment by Causese** [comment]
you could argue that if the outer glow "dots" line up with the frame, that it's the intended way for the glow to work even though it causes more from the icon to be visible and kind of makes it look ugly

![](https://i.gyazo.com/ab10af5c6241dbd62f5ae0722be7b3ba.png)
