### ISSUE TITLE
GenericTrigger.lua line 2474 crash

### ISSUE THREAD

**Issue by dmkusner** [WeakAuras/WeakAuras2#1873]
I've been getting nothing but the following for several days now. I've tried the latest release version and recent alpha versions, re-installing completely from scratch, disabling all other addons -- nothing changes. Get this as soon as I log in (provided I have swatter enabled, otherwise weakauras2 just simply doesn't work). 

Any workarounds?

Date: 2019-12-29 11:11:27
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WeakAuras\GenericTrigger.lua line 2474:
   bad argument #1 to 'upper' (string expected, got nil)
[C]: upper'
..\AddOns\WeakAuras\GenericTrigger.lua line 2474:
   in function WatchUnitChange'
..\AddOns\WeakAuras\Prototypes.lua line 1348:
   in function <..\AddOns\WeakAuras\Prototypes.lua:1341>
..\AddOns\WeakAuras\Prototypes.lua line 5331:
   in function `internal_events'
..\AddOns\WeakAuras\GenericTrigger.lua line 1138:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 4253:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:4222>
..\AddOns\WeakAuras\WeakAuras.lua line 4331:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 3882:
   in function `load'
..\AddOns\WeakAuras\WeakAuras.lua line 3889:
   in function `AddMany'
..\AddOns\WeakAuras\WeakAuras.lua line 1568:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:1554>

Debug:
   WeakAuras\WeakAuras.lua:1695:
      WeakAuras\WeakAuras.lua:1647
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AutoVendor, v65
  Bartender4, v4.8.9
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  Informant, v8.2.6508 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  MapCoords, v0.32
  ShadowedUnitFrames, vv4.2.8
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  WeakAuras, v2.15.5-63-g9f61464
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=448)

**Comment by mrbuds** [comment]
please answer all the questions asked when you open a ticket

**Comment by dmkusner** [comment]
The questions asked where? I don't see them.

**Comment by mrbuds** [comment]
I'll close this ticket, so you can open a new one and see them

**Comment by dmkusner** [comment]
So I have to create a community account just to even see the damn questions? Seriously, not even worth it. Thanks anyway.

**Comment by InfusOnWoW** [comment]
You get a template full of question once you click on "New Issue/Bug Report".

**Comment by dmkusner** [comment]
And except for saying that I was using the retail version, I answered them all. Addon deleted, problem solved.

**Comment by InfusOnWoW** [comment]
Except this one:
If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the `WeakAuras.lua` file in `World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\`. In case you do, please export the string and paste it below.

Or the version question.

Or whether you remember the last known version.

But whatever, if you are no longer a WeakAuras users, we are happy too.
