### ISSUE TITLE
Issues with glow from Options

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#1878]
With last alpha from twitch, tested on classic

<https://www.twitch.tv/videos/530054835>

1st issue:
- create new icon
- add glow
- check "Show Glow" => doesn't show glow
- switch type to "Pixel Glow" => show pixel glow
- switch type to "Action Button Glow" => show action button glow

video also show another issue where the glow show at the wrong place but i can't manage to reproduce it yet

**Comment by Causese** [comment]
the glow @ different place can be reproduced by:

1. create new aura (icon)
2. add glow element
3. show glow 
4. switch glow to autocast shine and back to actionbutton glow
5. untick show glow
6. move aura to different location
7. tick show glow

notice how it's at the old position

**Comment by Causese** [comment]
also after reproducing buds 1st issue and moving the aura, it will stop glowing
