### ISSUE TITLE
Stop Motion not working with wa 2.15.5-72-g522f25e

### ISSUE THREAD

**Issue by trav-i** [WeakAuras/WeakAuras2#1883]
## Describe the bug
With Stop Motion installed, wa interface can’t open without error. After closing the error, every time the wa interface is used a new error pops up. Prior made stop motion was continue to function. No was of any type can be edited and no new was of any type can be made. These errors are all “wrong object type for function in function ‘CreateFrame’”

### To Reproduce

1. While wa Stop Motion is installed, open WA interface
2. See error

**Screenshots**

![8EBD69D5-A720-4F8C-9966-2099AEB3AF82](https://user-images.githubusercontent.com/32317280/71770458-a00b0580-2efa-11ea-90e9-4b4cc71b759a.jpeg)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes 

**Which version of WeakAuras are you using?** See title

**Are you on World of Warcraft Classic or Retail?**
- [x] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?** Yes, it was last working for me in 2.15.5-gafd2b45-classic. Took a break after that so unsure when the most recent working version was.

**Comment by InfusOnWoW** [comment]
There has never been a release of the StopMotion plugin for Classic.
