### ISSUE TITLE
[master] convert breaks aura-display and movesizer(?)

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1884]
## Describe the bug
after creating and icon-type aura and converting it to a progress bar, the aura display suddenly vanishes.
once it's a bar, it's also no longer possible to resize it via mouse

**Do you have an error log of what happened?**
no error surprisingly

### To Reproduce
1. create new icon-type aura
2. convert to progress bar
3. see how aura display is vanished

**Screenshots**
convert issue : https://i.gyazo.com/31e7a56913f0b6b7615cac9f4c6cdede.gif
movesizer: https://i.gyazo.com/0b3440c2942bfb281b613706c7eeb622.gif (me trying to change width etc by dragging)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
master, no alpha in twitch so dunno what to call it

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
2.15.5-72-g522f25e had this issue too
2.15.5 works fine

**Comment by InfusOnWoW** [comment]
Actually it appears I broke the MoverSizer completly.
