### ISSUE TITLE
Trigger  > Status > Totem not working on Classic

### ISSUE THREAD

**Issue by Buugar** [WeakAuras/WeakAuras2#1887]
been trying to make a weak Aura for displaying a Texture when i have a certain totem out, this works well for totems that give your character an actual buff, but for others that do specific things without buffs (like Tremor Totem removing CC effects) none of the Triggers seem to work at all.

**Comment by mrbuds** [comment]
Please answer all questions from the template when you open a new issue, but first test with the alpha version of weakauras because changes were made to the totem trigger and we don't know which version you are using.
