### ISSUE TITLE
bonjour impossible de finir l instalation de l addon

### ISSUE THREAD

**Issue by james91620** [WeakAuras/WeakAuras2#1888]
bonjour impossible de selectionner l emplacement du dossier pour l addon compagnion rien apparait quand je selectionne mon dosier wow

**Comment by mrbuds** [comment]
Hello,
WeakAuras Companion tickets goes to https://github.com/WeakAuras/WeakAuras-Companion/issues
Your issue should be fixed with last beta, currently https://github.com/WeakAuras/WeakAuras-Companion/releases/tag/v2.0.1-beta1
