### ISSUE TITLE
Group By Frame should not hide the WA display

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1896]
## Describe the bug
As soon as you toggle Group By Frame (group tab), the WA display is hidden and makes it more difficult for users to make adjustments. e.g changing color, texture, icon.. etc

i feel like the issue makes the old way to anchor things more attractive since users would have to untick group by frame, adjust aura, tick group by frame again to adjust it.

**Do you have an error log of what happened?**
no error

### To Reproduce
1. make an icon
2. put it in a dynamic group
3. enable group by frame in group settings
4. notice how the icon is gone

**Screenshots**
https://i.gyazo.com/38b3a1b5d46835eca731ecb2f3fbc352.gif

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.15.5

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Comment by mrbuds** [comment]
I can't reproduce your issue with a status > health > nameplate, and group by frame > nameplate, it show an example on nameplate1

**Comment by mrbuds** [comment]
> As soon as you toggle Group By Frame (group tab), the WA display is hidden 

This is because the next option is not selected yet (nameplate or unitframe or custom)

If the type of "group by frame" is selected, and the trigger create clones with correct "unit" property on "OPTIONS" event, you will see a preview (like with my example above)

**Comment by InfusOnWoW** [comment]
I think we should anchor auras to a fake anchor, similar to what we do for the prd and mouse anchored auras.

**Comment by mrbuds** [comment]
It's possible to see exactly how it will look with your nameplate & unitframe addon with current implementation.
A fake anchor won't have same size & look

**Comment by mrbuds** [comment]
implemented in https://github.com/WeakAuras/WeakAuras2/pull/2438
