### ISSUE TITLE
[beta] movesizer error after re-opening options

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1897]
## Describe the bug
It throws an error after toggling the aura view until the eye is fully open

**Do you have an error log of what happened?**
1x WeakAurasOptions\OptionsFrames\MoverSizer.lua:467: attempt to index local 'region' (a nil value)

### To Reproduce
1. create a progress bar
2. toggle the aura view until the eye is fully open. (eye should be half open when aura is created)
3. close and re-open options

**Screenshots**
![](https://i.gyazo.com/cc880f4f00af8b94e7d8a6856f6bec87.gif)

**Which version of WeakAuras are you using?**
2.16.0-beta1

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Comment by mrbuds** [comment]
```
2x WeakAurasOptions\OptionsFrames\MoverSizer.lua:467: attempt to index local 'region' (a nil value)
WeakAurasOptions\OptionsFrames\MoverSizer.lua:467: in function `SetToRegion'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:4558: in function `SetMoverSizer'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:977: in function `finishPicking'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1011: in function `PickDisplay'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:4281: in function `PickDisplay'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:1432: in function `ShowOptions'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:1380: in function `ToggleOptions'
WeakAuras\WeakAuras-@project-version@.lua:81: in function <WeakAuras\WeakAuras.lua:77>
[C]: in function `OpenOptions'
```
