### ISSUE TITLE
Deleting Ogg files upon updates

### ISSUE THREAD

**Issue by Lordmemnar** [WeakAuras/WeakAuras2#1901]
## Describe the bug

Is this a natural thing and if so can it be not done?

**Do you have an error log of what happened?**

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

```
  ERROR HERE
```

**Comment by Causese** [comment]
you have to create your own folder in Interface or Interface\AddOns that is not part of an addon that you're updating

**Comment by Lordmemnar** [comment]
Thank you, though I had to start over again since the base files were gone.

**Comment by InfusOnWoW** [comment]
That's not our fault, talk with the support of your addon updater. Though the likely response is that you shouldn't have put the files into the WeakAuras folder.

**Comment by Lordmemnar** [comment]
Well I am at a loss then, now nothing plays and ive followed the same
course ive done before.
