### ISSUE TITLE
New "Global Condition" for mouseover

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#1903]
**Is your feature request related to a problem? Please describe.**

It's not super common but comes up consistently, some people want Auras that are only visible (or occasionally more subtle differences like text becomes visible etc.) when you mouseover the frames. 

**Describe the solution you'd like**

A Global Condition for mouseover. 

Extra points if you could specify a frame rather than only the Aura's region itself (though, of course, default to the Aura). This would mostly be used when people want to affect a whole group when any part of the group is moused over. 

**Describe alternatives you've considered**

We've had a snippet for a while that uses `aura_env.region:SetScript("OnEnter", function() frame:SetAlpha(1) end), etc. 
I think there's now something in place that clears Scripts like this from Aura regions? In any case the above is a fairly hacky method that doesn't make it easy to change the properties that are available in Conditions.

**Comment by InfusOnWoW** [comment]
That's unimplementable. The only way that would fit into WA as a subregion. But a subregion can't change conditions, they are only changed by conditions.
