### ISSUE TITLE
Updates to Init custom function not being run. 

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#1904]
## Describe the bug

When you alter the custom function in Actions - Init the code you just input is not run, instead the previous version is run. 

**Do you have an error log of what happened?**

No error

### To Reproduce

New Aura
Actions - Init - Custom
`print"test1"`
click Accept
No print.
Change to `print"test2"`
click Accept
prints 1
etc.

**Did you try having WeakAuras as the only enabled addon and everything else (especially 

Didn't try this

**Which version of WeakAuras are you using?**

2.16.0

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [• ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yup

### Additional Info

I did not test any other custom code blocks to see if the behaviour appears elsewhere too.

**Comment by InfusOnWoW** [comment]
Ups, that would be quite seriously broken. Hmm
