### ISSUE TITLE
Load on Corruption Value setting. 

### ISSUE THREAD

**Issue by jec324** [WeakAuras/WeakAuras2#1906]
**Is your feature request related to a problem? Please describe.**
In 8.3 Visions patch we get a corruption value for our personal stats.  When these values reach certain break points they have different effects.  Such as when you have NET 40 corruption you can spawn a "thing from beyond" which follows you.  A WA that would target this issue wouldn't need to load unless your net corruption was 40.  An example I considered was a variation of the Algan WA that shows an arrow / plays a sound when the mob spawns.

** Other solutions **
I also considered something like a 2nd trigger where Item Equipped Corruption -> Value could be useful as well.  

**Additional context**
Adding corruption info available for WA to make conditionals on could be useful down the line as well. Not sure how just yet...

**Comment by InfusOnWoW** [comment]
We in general don't add support for features of a expansion that are likely only temporary, as the whole adding, deprecating, removal dance is a lot of hassle.

For corruption I even doubt the general usefulness of a load/conditon option. A custom trigger sounds entirely reasonable for that and would be as performant as a load option.

Maybe that'll change if there's lots of demand for complicated auras that have to take corruption into account, but I doubt that.
