### ISSUE TITLE
Game crashes after /wa

### ISSUE THREAD

**Issue by Nina629** [WeakAuras/WeakAuras2#1913]
Since 8.3 my whole game crashes when I am using /wa command an mouse over the window.
This happens with the current release candidate and the latest alpha.

I tried downgrading to 2.15.5 but now the /wa command seems to do nothing.

**Comment by InfusOnWoW** [comment]
Please don't ignore the text that you saw on opening a bug report.

With the information that you have provided we can't help you at all. You actually need to answer those questions.
