### ISSUE TITLE
GenericTrigger.lua error

### ISSUE THREAD

**Issue by Zetaprime82** [WeakAuras/WeakAuras2#1921]
## Describe the bug

**Do you have an error log of what happened?**

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** 

i only use WA addon

**Which version of WeakAuras are you using?**
 WeakAuras-2.16.1.zip (8.3)

**Are you on World of Warcraft Classic or Retail?**

- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

!S3vcZTnoY6)lPQPw73ZrHN6y2D2QS8rIZ4iNXujzoYijsjkjoHwudjLV23QF7VUb4b4bOOuSZ4KbRNvrIeaeaDJgFDd8boqEq)bgMWhHdmcgyO0qUzd5bgxnWyc(FWnTmh)Pj(ElpYZ1ZhUqpzY)Pq(uL8P2GEsn0XIWYZFITF3OSmWORRZ93B6pz9O(EEUHoWLc9gFTTFGJ3Ib9AlPkjbp)vHZ98VyziCXGO6YytxBSWJkYbwdmU7IPtdSdhC6ZBR0STQC726sD0K6O0EW0NRPpWW3Eguc9VBP9aJz(ERwgNBdN7TXQSXTjfrt5okAY6YkTA3PPutnSiAhNE22QePTkrARsK2QCAl9KjZGNLXFUY03E9Otx56UE0hM7ecxCLV7aJ5HHld((x8IBmN51WX7fV)U3)(lDKcV)fYy7ECCl2ii00pK20Dw4e9TPWxdMt(o8RqFNzZGEoA9QFYfiFL0Mnx5Bcf1kl7RTxeASA6uNBhym8Odn6p0O)HxcjKCNbgVY20nCEAAFRVnjTgV9KZphU8sBx3ZMejlSGcYyU3nxSaUd5FpeQ4xdpWfMxzhLOvyT2yPR5DqnYyInMjQK4vNC(Bp9DNttuADM0MM4e8hRwevAMUU0(KRT7tt2B8MaYTNd9vqAnxmg0sERNd2ao6KE9p5YyXqKufeogb2xDnwdKBi1qc)P70OS09I(9V4nNFYPq3GdODFKV3NUfKAxSW9U1JUeAaJFR3n2(Rh9)s(PDxt63F5rhJsLqB)fMUVpw3vPjiG8HoaqoygAs0vPvXtXRsB7ghD5jN0dVHZvMOWMvwhj1w4Ta(Cci7WemKEXa7XElabauVVY0zr9tDIot9sFIM8zli9GqJiz0jQIcPBQZmQiEIDW44UTN3)gNGqNfZwpQND4CShhlshMHWUEMediqIiJfHVE1kWgqI(mmcFryHlp21mGoKaYiydW44toS)R(XEN9YxLpP(EW9ZFXvb2dPLbiywb533CCXubA4JlCXP0bKCQPkfU(ehye2y4k3v4wlVEjN2xaAlk3fXQnQs(ZRU9L)uRpjDvN9iDfjd1HgL)W7qdqgxbJjCpl4D44nRO7Cl5oXg3WVhBReg8O0QYXo1YUEaQrBFB4kF7bDRLTnCAduUVysgJPnKKA1wtvwTLIUwhjfQX1gkuZRnusVLCNMPwBx65dJYCc)vpVRWwnPty4stInm0yvWlAn92Hxzode(ZDCDTNe6bQLJ98ThcJ3cTBCLcrd2mehkyJfIVxiDmj2Hn1d7Ao135(1J(PvMtWX0WSw93SEmQWTW(A6CuBH2BQIA3kuLjkQwLR2WvXKJQhwExBp3zSlP9hpgiQQIZpgNCOxVlEHUOCP7g12zk435GfnF1FmPlTdTmddP1IshEYzKiQjA)NRSxmgXgOteBWK(e1Sy1tJZql1qby)XdNm5IfbF8d2MF6qqQh8X3ypXX8JrPm4J05ThcAtEefPemhJrWlG6OMCSQwq4WvbG(i8id35hueYGKs0NoIES3vlHufG9gMUlNBYG7j2SmBfj8Es2shHXmUVgaWgxyaVeZaEYWn6JIAvPe8APdJonP7hR8vHqbL7(WKQOYE8SrWS0aqn7f2(oJ3iaJL4CZKPV61msnk5kDlhXroqjrZ9bd6brPX4vbHExnCUdaXWi05k7jy6JWhbis9IEKd9wAdvxOlZ4F)dCrmfLpcaIyLC)XW1iLbXMzCnMm0RkmAzrFrZJrheFl2)H6gyzrABq5M55y0rk7vYw7)CHGzVyYHuBfQnL4GjYCY1M44tRhEupen3ljALCYiJQvdTOm0L0LrgCFhfLgDmMu09P6mlx5gytNQY4U0BEi1Ea(1xs(6TP37uOBdSar688wS3sFVz4W4dwpYxg(yg(Hf(Hj(HVcEn8dl8dtL9x)61Js)Z1dQHW1X(31J(H1JskW1J(FwpsH8j0DoVXsN9xp65qcI(16rVaUF5f3c7BEBsXGfkntGj)9ipP9jiCL3)fk7)pZwa(2Wq8fyBHKK9YusqvzpFfsTWxE)9piBwt)BgVmpJM5zvLzlEz2IMzRQYSjVmBsZSjK508ck20FeHkWMiLj6m3MmIJA4S7UHYo16nv7capp(t3DCS6QfzG4yOthmtYIlHXbMyCBzaOtgwfnOe(5CBNzZXjmutAjDlcnVehU3k38rWsuFQLvY62nPzgHM19U3CU17v0xQPYoPh0HQ0sI1XEwFP7r6j56ifR)8YnzNemz()0zDr7OKzsiDNxa9BWmbbF8KXUolb5jylmUEn1X1(mOklRO0PzB2A79rJ3tDdQ2ETBeqMymlobVm4eiZxq(kfXGbMJGpgoh(hB)gEZMb6fEddIMHnmYnSOzF7M04tXeJAyuBuMljqXY5qCkGPscYrJMTBQ0stxQdmtFhL8WcqHkXpzWZymwhXpZ7Oq4l4o8notaCv9a48qkD899OqKbTmAw0WUnuBMmBHfGxCcz6gJUNFspWNBpFhyESi75V6Ilp7xVOx)dppQiUnQiYgca94k190kDpLC(pvdhMAVHUP8XckyPP)NUmZO2T2FjNXuRa4qRtDnNbZLDX76F(z9oHEVHJRCGjTEu0wHLP)2lNRWnjstL2v9l0rgSsZhs04GC6Wj)basZEI9K34q6CyT0Gb7cADLP3KGqhYgGaX1jiwivs16itsCmav6p(UZEE6VEUbMHiOGD5HsNyOBCVF(xV3E54UD)unHL3lfpt1iXPOuXQ9aJVB56xZF4FgLqA3XHVR)fF(O1XVB6Edy5KepLTc)EgGQvdGVm84zrSxNaBgdaplq(SiQzCQGIOUjxy97uunPMCkeD24Mb2YDwaQtGpWB0xGDRRUwTMOEOJsXgqf1wbE(wefOU57i3S)dlU7Z2)HNYHknAa8zlo1hJxuxEO2YcrBL1LedxPd1O2dg6fzHqj5kuGpe72jxliE1lI(946U6edV2jWbmpI1ZORytazLgvGJMBgUEu3vwyYIvuHFrXMLOlZAXDiw3cXNyFQP2HbZnN4DZphBVtMPGcjwUiPI(veIn5N1y(ms64hyoMNDnMKMj1)s6C9XxpDMtQrtk2zQD3ExGtctsxChQv0VZex1Z617KlhEjnuF078lmZbqYaoHMZ07sNGoPngTgvsXz9NZNvmruBpXadiR4XUje20FF3sUIjPgD60mnkU6L2r)1MuJUSq7OqtU92j003jH23f8vXiN89nk1siC0f9gg37wxPqrP9gfceCxet5jokRX6OCjb7KGRQBkgZdp(4s8wg9noEgIpl)rZ4Pzr30zCJkNp9zXlBEBcMq8l3JRBsVi3mGjuWgsKHksAoAZQuLUesKm)QOUsvPkCCNXXHFokWgzxOw8(FG6WiXFOyFnxpkcth9z5mzIn0n17K3Jp)mECQY4XP(2U668wVk54fJIyXlYay(lQw2ft8Ao1fxXsj9uAPKQx4fYfGnMLgkgdeRQRQujQ6LT)wYQ9Nl6dLowRe9zm2qZC9UHe(W0WezGxBizSXaJOFf1lyq8VIt8QYhPPsIRbpNm)cfHJs9yO0WEuaOEUiHeJLrwsVDBfvDLoAYW84Pt9jvmsiXbKhCRASta3qISz8(YnAxde)Apki(pC8ChWeZvGQ)6rFWZBIa2F5aiPqc)YaGS5xgu)FddGCx89QO0UUaifq4F4HWVDsGCq4jgHFtc446a0kd0HmiVQhMNTaFwE4rYLbpQoiJQgKhV9Vw1qOYG2Quiu8WgYzRSvppMkvzfrr3wrstxrtxULutS4yxLgEO01y3vzrZSlP1IzUDL8tTxv4VJIx8GEnv1BkvwCrRDOyllS2CcpBUWeNjyTCcs87o6Otmm4T7xIW87aAu06JvsuFFPRNfU)aoYZZfmkSOqiZxqapEmijb7n(MlcM65hfx24cM0f1nt01rPHUUIQAIphER8hB)UOoJ0OzJX5koo84WH3BE1shF0BVUUiMKqYQNgN1KUbOMIBxx6IWVdXDp76yKRjVBXAFhcQoVDDDfleWNBK3jRt1FAO7(tZFZp171lYejaQL3aYcVfVzjIw5N6TeC833ZjlugXOWXzGtNni5SE3FYBEB)Fjx0f004SWE83YBh7y66nduPsSAaxJSOEjXdjE19kjWpypgDyYUV4HCxrC94GZ0T(rGHjqcSrjIJBSdpR37p5sJtQxKIEcVQlX4DZhHOnVq(sTRkSvFDSG9nIwJEzD6A2hp5w(RMfV3t2vWNDN1wZfUVWy1swjEPgT0JmY9RDA1z))8O3CO0LCwm(cXNPgRdVyv3RAv3ZmDNyP3fl9(3wl9ElrG4ebbQKGajcd3drSqfrH7BMOW9nXcPlwK2Nu89lElmSv7i7DFBoSRE6x)DcbZErp3QaxMJ5r7dc7UvfOJxA677e4TGnuhvV5ikBZuuAODy3G(Lh81scIBZMs6T70SPUClnT278ATVv7GJ4Pd2(WeilctWF)ctG19gF41bh(RNzPlctGimbIWeictWNBycAkctGimbIWeictGimb8dtGAZhSWe0qVLEtL2T1A2UTARwIOgiIAGiQbPrnGnuaFwHoqHj0bT)gn0bnXu6Tk01zbZwTTmtaaCseFEmLSZejbvErsiLg3VB5etYXdz0)IO2r00JPHSW4qI7qpCNmKB)zTeoRyxFBZW5Rh5nD9i4XctLnZlWS4XWuPhIs17OzIXzOY9KSGRrvF2mXX5jENitB3HW0yq1nK0fs(2fSp2OtEjPChXtzpxMWJNuoNlt)RcNltL5nEU6E2ozRQ2sA5QinR(aIs4CCjohZN7j3agw)GVjyg4djFlghiyjWZj4c0GsgVnJHcPi1Ov7MQQnB3PDBjTumevV7KRh4HmxT7xqSej4ey3KZkYS1Hhf0f8btWBBrxkMIQWVXcEjZPGeUBwzNcK6abO7Apjks0ksLDy0wyUCoBdr2dN2ERUYIECRUruj1(4PnE6DLg6sAkknB2wtVvwWWSXoNea12wDF7Bp(dExE)FuRaHNbWmDAQXZTh)jwJnyLeHNGh0ExB67ysovcYAa7Atx8uDvLeUQXZnxmZoTeP3KO7T0hTSbkkPYPyBB0uLJt7jNgoY6n7KhzyAHr72dzSu(50k6uzRqP2TcjgfGICAR6wbCJcU690E7G2QS15Pq46VLzJG2SrNoDubCLATX9r8oUhr)kH8JLbqV0Zbk5Qp4NkHUJA7eDhL25J3eo9eBi4PLEESlcA6FTbnD7oHgE4dAkyIVfld9JSvkXEGtl1Uub0j3swiXBmV7lGGHrPMdbqFK4GQwzsNcsqr4uFYD8LW1THspK7FWj3ipeZ8GDxbg(srKVfHnKN3jB4ffq3TJkJLfWTn)Y5GgQKKqMK1P6sdrcZQGxTRZz8lMw(jhSSPNpXmh3TrhoWh)J4olsMGV7GKFgJ9k9k4AWFPT5K7ihHWV0oeVAmZb3tMxbRKTGvkuWkvxWk8ky1SfSAHcwT6cwLxbRLTG1kuWAvxWA8ky9SfSEHcwV6cwNxb3mBb3Sqb3S6cUj7XgD5pI(O)lg4JHuc)h2eg)xonjEjqztjqDtjiwcX526vFBAVv6D)V1RXhpyAJTFMEFUDb1inQ1inm6M86l2yks0w2qpsi2j0iWZpCV8Qe7VPuf33XKqeR9q7fx3iQxlv3kFP)BY)o)SLrQuYtmtMt)MZ0YFoJ(bOyKGMXC7ff7WIpn0LoqI5ud3nWMFsl9H8CYqW(oxzVh9OxV8k(bvCdCJEvYPEE2ZYC6bAE0F1898uLrYLgLJKLTiE2SYMDjUdGwrZuty)RWlJQswmHp73zuLUokmREs8AQK0Gs0YOMjD9w5Fej8me1mstA0ZbP47cSdwpcryTE0ysYGFo1ZhA(qgXxcaOIguxrb4eIAvCcxpcqqaxYji6YaQo4xlI(fMNL4RKkya16xNP(G6n(5Qi)I3kOGnHCBpXjmQmqCJRhzztVi510e56U2tdJV7uhB3jOItYJiEwHJIQMzEoNKw6PnJ0so(AlDg)jsJlU5KekPG8TOJVdq44mgByb5Ey99MbOoHRoHMgqmdDiOTfSSj9WRFnMWt9WTffaxgBKq6j(9hA(jymC28o137QSTF2oCe8uu1lY8p1HHBj1lzALIQhel0GBT0lWHAbIwI08KRiOZ7(8OYyCMY4o(LbMydI21rXAxeHmktnJqFI)Y17MdsKeG)rliHhgVt4n2yVGekcGKk3augAmd(uUTev5d(Ylu01jvqPgTKy12SHAQ)mBgvH)tz9cXIDCHchdQpKQbQdLiLITk8BpZ)z)E0JQdoXgP08XwbjsMSPCwjPCMpP5uiTwLKwlmnftQzusLtsizFbxwHMwxXxwhj1ulMtsGIzAwHmfvPRoBwfYgT(xDUsAm5AlLKR)lJGLC8ASnsvlmdvinLRRSS(sYhf5O6oih3jP4JVm8uFVGWTrgofZqvJiRPmuU2Yq5hdz4UmsuD3gjQ(4lfF3I5EU3TnIXvKC8aihLA0w(GVmdgh9Wjkv0FAnEe)lAQEltQimHZlnOlhCWVLiUDM87rxSbMAiViar4RnWLf02Vpz6FI3h5U63)karm6UabkD0terlitEMqI)(JW9RJncgcd80Iz7TWXfA3p7I3FYLNF4V8m87V08kskELZS5Uy0dFgGzp)Z)hIl5C357nSdJ3Hd7n1eC8z)YsIbb9cnaM7fbH6GeKq7toIrJqAhTI(peR0i7lNPKxsyY8FjHLlGCPVKWYSDvk91ewCMO7epMxgyVm9ffgZ7mShWxry5Jpbm05GOHchq1UpirFnA4yY)VqMr)wo744icH4mDmDDU3mVRCzDBov7(SGO9e3flTXmeP3wLBP1YnE5nN(0OfixY7VRIv648hbdoP4iVvqZFrwNSsCiP8icu8kr9Ty(V0g1njGH)HQAYfchq5TwEpkQ9K6B5HBbfB)kJbQYtkAE4iYG(yRpSgq4wtHgJ)b0)Dw0)Af9VMCAa)dspW)iXSj(K)ES7cRb4OR92N7Z7KBxI266b28oi5x0nAB6Vjle)w(WX8v2ZT4vqLVC6c)71J05QpXTGscWwsppAQf7f2lGyTVb9S5BVN9DnMIM6Z8u3F)T5zHH0QKk()IuXjJvk2KKE63K2Y6WZE2(F(TgIMsfft0Fz0uRBQJ1KRB6PA6Ct9(pmYo6GYnxPInguVuoR2P0Q2P08rTVGSQW1OF4z0Lc(z1qocMzp4bTaLQtA2PEj2(I5E3uMXYmtxN5hB9m2fIzzY02ztxw0dR))Qky)Lft)kbBXIGitGZAGQ58U3SkUNvf3ReL3A73rdRzOg67T9bXeD8k3Qqv1DRkR8vv7TmZ)MMnZBBw(D0Vo)CuvfQ(Tg8gwGjOIPUaURtQTbLLYcfxw9e2BmJ3nS4DJkST9GOMKPsWTEBXVIZTMxUQXUOIKxvHvYQ84lzzcqxwjl7nMX7gw8UXJTKntLGB92IFfNBn)lJKv9XxYYg0USI2m3zg37yX9op2s3Svd(1DRkQ88R9pcs4m(0xCzU5aRV4JG6zlt8w2YPFKlU26fFnHFx6Bz(BJPFXwF6vu2lkOAYavwUAu)xDUKTcD8zLH1UZJ1ImNTUhj4SKFT83BVzzitDp5UjO9yjcmlxy0sO8IwjVCEn8CXsGWYLddUyz338Jtox78ucT2DdeATHg7MkoMvg5VySKJp)wZrX8mKiREVpfKPeMODzeMGtZoL2envrwt0wUz7oA6QY)vqBIhWU5V(zEXwEK1iyDHG1fcwxiyDHG1fcwxiyDHG1fcwxiyDHG1fcwxe1JSr6tOWN7fkvqzd2Svkxlu(sW1cL6Y1cfECTqrW1ITJRfXhXbcoxi4CHGZfcoxi4CHGZfcoxi4CHGZfcoxi4CXtkoxWzzMZ(YorSEY5xpzL6TEYckT83BkTOSLuAr5RFkTOuFkTO83EkTO8xjLwueuArqPfbLweuArqPLVnO0IIGslckTiO0IGslckTiO0IGslckT80Islewu0zQT3pEKYcB3dZWII6sULAtrI6ZkIcVhdch0RZortcf5gsW)RPSKQUSEtbnje0Kqqtcbnje0Kqqtcbnje0Kqqtcbnje0Kqqtcbnj(AKMeQBKMeQ8PjHAf0KqDt0Kq9lbnjuRlnju5rtcvbnje0Kqqtcbnje0Kqqtcbnje0Kqqtcbnje0Kqqtcbnj(7knjuf0KqqtInttc1TKMeQF9ttc16ttc1)2ttc1)kPjHQGMecAsiOjHGMecAs8Tbnjuf0Kqqtcbnje0Kqqtcbnje0KqqtING0KOfmUXY8OFCYFA(uMMeYs7cpjuKX3MeT01BR3rTLUGMecAsiOjHGMecAsiOjHGMecAsiOjHGMecAsiOjHGMeFnstcTnstcn(0KqRcAsOTjAsO9LGMeA1LMeA8OjH2tsAs8)ZE3XQ0WGrbqHFD0TMW9EjRoiccoOGd(oiOsxSV9sNL0)0o0K089mCM)4GjbMeysGjbMeysGjbMeysGjbMeysGjXvGjrGjbMeTzseNjtIy9ZKiMotIyZZKiMtMebMeysGjbMeysCBWKiWKatcmjWKatcmjWKatIfitIdV85ZVE3JV)Wx3VOzs0DjmjQ84nj6JOl2v9ysGjbMeysGjbMeysGjbMeysGjbMeysSkzsKnzsKJZKipbtISftI8AWKiNktICmMejMeysGjbMeysGjbMeysGjbMeysGjbMeBvMejMeys0MjrEMmjY1ptIC6mjYnptICozsKysGjbMeysGjXTbtIetcmjWKatcmjWKatcmjwGmj2)X(FEQ)WBFh)UOzs0Fjmj62nC0jrmm0p0HjX8YKy3)dlQeOsGkbQeOsGkbQeOsGkbQeOsGkXKPsunPsuJtLOobvIQfvI6AqLOMkvIAmQefQeOsGkbQeOsGkbQeOsGkbQeOsGkbQeBvQefQeOs0MkrDMujQ1pvIA6ujQnpvIAoPsuOsGkbQeOsGkXTbvIcvcujqLavcujwCuj(BJUvjgDRsmuzRsG6YfG2TTj8TKWsYIcni4Y007bnBBcKVeca7sld0A80iqYfhGd
```
  Message: [string "--[==[ Error in 'Rune3' ]==] return functio..."]:34: attempt to perform arithmetic on field '?' (a nil value)
Time: Mon Jan 20 19:04:12 2020
Count: 35
Stack: [string "--[==[ Error in 'Rune3' ]==] return functio..."]:34: attempt to perform arithmetic on field '?' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:413: in function `ActivateEvent'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:552: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:512>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:665: in function `ScanEventsInternal'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:626: in function `ScanEvents'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:1307: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:1305>

Locals: <none>
```

**Comment by mrbuds** [comment]
The aura you are using seems outdated, ask it's author for an update or find an alternative, but this isn't a bug in the addon.
