### ISSUE TITLE
Model not appearing on progress bar

### ISSUE THREAD

**Issue by mikkelon** [WeakAuras/WeakAuras2#1925]
Hey.
So I am tracking my Arcane Charges using 4 progress bars. The progress bars are set with a maximum progress of 0, so that the bars are constant. I am using a model on all of the bars to add a bit of flair.
Example of my conditions on the progress bar tracking the first Arcane Charge:
If Power >= 1
Then Change Bar Color
And Model, Visibility On.

However, if I restart my game and I charge up my Arcane Charges, the model will not appear by itself. If I go into the Weak Auras settings and uncheck and check the "Show Model" box, or any other box next to the model for that matter, they will work just fine - appearing and disappearing when they should.
It's as if it's not updating by itself when the game has been restarted. I don't know.

Import string, if needed/interested:
`!TRzBxTnowa4)o7(byLSKLT)q3ZHqtkSdnHjoTtN9mhhuIvs8wh7m(fgiFGF77vso2oghi0aDGEApuoXY6kD1v3xEKcEyVrEUPEUghJzhJ9Cx656l)bADcF6x9tIxDACyCc0qFS6hd1VjQFt96Jo20ld6CCIViPtHiEUDcdwVMN4F3vJIJdZcGMsNYdfsXk6S3ep3BhmBwQidggpxE00fXjxghebJ3PD7pQ7WnD1nyTqoZfpwxJqkncP0iKsJWs9jlE61IK0G4iV(2iccg)BQpxtZGxLQw8z8Km4dGqZcIcsxO)m8rDRYbljy(Cy00t5OYgKF0xmjF2Sr3Us45Ew3lUS3NUaEV6rEEch050vIWWZ9t1JBA(eX1IOmxqQGB8ChF6jUJg7o6KHWGLlNu3vH8BHb3nIVuuiLseyce8WSfvdYLjc1G4Ez3lUq2V8OkvltR8Atwx)5Gg5(N58eXDx1lpm8UR(TfbzInDyJXH65MiMdgh9sAEsC(k5EtWsU0Kv3I56dlqzJJ1R3uX04iyDwS8JIJesfyjpiA)7D5EW(1F5of4WEsYuEeSWoDbpzoy0CH(olyEX2AcyiH9mEgx5(PD06jBvViDpDy3U9bRNCOULo8)SG9lyJVu6PEEKY0GLEfzIKiE4N34BzWu7gdvMSInlEEgm(dwLv1Ku1dQ9CymxfJLNkgpnKNkxwj5cLZYu5lwMdbnB8)09qA5dIMdXqUF8Kp0TrFsLHineu2SiCwrivNbJgn4Jx0TNwJkDMtxXt(6Vf4dow9XOIN1UdFrfSSjWPhdtXucbXqw2mSfZB2ruty96))YtZe(FKdUIOQG6EhzzWCqoiqktthdIsa2oI0vt7W4mTBwFuJw(ySpSWp5tJgOZmjDmJ8FWmb9SPmMfZYgtTnnyiBy6nPpwaDH3gmR5P6nOvX)LoB1ti2vkhFsACYeLI3Pme(s1GPEVsIoBfNRMkLg0hZ2vQJTJ6lJt8CXsTOyEaNW4AQVAm70E6QwYBOsqETyKUr1sO)rGZHmCd8Lhp9bRjG1jqBluPYDSmdpVE(8EmdmZIqyiIHLHbMk3ZiYzONPnJyIryiBUnZWHu8gcid1Wg2PTqeInb2WlEZgnXxKcBMGrsO2eRCV)DTBw9W3c3HY83G2ng(pmmGkaVHVkqoilbls44BuYR)CA2yWFPpfPwrJ1nEDqAWKqrLeqVsUTMuZccfNdjDubwiWaLjUjR06MvtSS6ID72tCcOigwOsF38jGkOElKmVEev1OTUXZ1xknExs9NxXv1FK(LP)lRz3mEjFUyCwCoerplBHaEmySm4rmHNkoEPrDZbpC1cDk4Q2MgcSbtK2xsTOpyfOzekYapwNYqjyzBQuEv8eB5uUdSGIEUzFPtzlIhR(444s6bvaYcrW8fYCIGBPjIYSjow2wMyzko72sW3PipoSu8hxKMpt3b1tD2Z88ffik6IC5Vx1bKE9Dcfr(fjsF)7lA8SaFFbK8OF3pldhFAKrG2Fsr2FD()onBdQ9pzBKIIWQwRtQsUKgi1WHN)HZ2uD60hpDJQFLX3NP3D6tq6qQ8eye)L8G7UsNy)URan4UR(htsK9tK8p3MyqngJ2i35YmzZ4tf)XP80mWU3HN8hF68JQE6ix1SRt62Pv6ZkkfnJc9b4qQIt(lDzzg((umkyLLD(9ZDw9N3m4ZRLBmYjv5vVooEPkQnojakhuuF4Sbdp))oO)OtUObrIoR30fIPFTE1q50CnpjGlJv01MKnekbva9xY5)U3PGjwWJMlQgjDFa9yfCyazXhvi9XghF)uJBsSQfrxdWeBAHyemYWctPQykOUDzaDpOSUHPjYazqnPygQr((QjTS2s2M4aPdM0l5vmq7glYJYL1s8Z3DuSn2Z9NOAlCLxiIQDqk9G0v1OW2c67nprLjZMz7ytmnCCieIrnIktBKdbtqanLLPjRgrfYYKsPgicgkRrzV8ev3Ji45LR6BME5PbGvNlClYR2GGAsFTt2VTiWw3kj39j)2quDp8LwrQ2f31llt1gcUFOjQo4tREqqwLhE3YXaHqehBO0Pf2Mwua4(exkWIHy33p8dV3)xhudR5Vt0Qs(U9GTI8GGt7b21(cD(9H4sYz9VFxj5f5LG4IsCyuSdcoinbBB)msC1(bkkper9JwKTlUSAes7IIQgx2(17kUS9Q)zLjuFtWL9ZRi7h3RiZ0H5qTSWMemqOXCQb01oQhzNY8QfOB9RgyUk0YN0vP1YvX1KNRjV3UzeVrFTtBb0182VA7gYUp03lepxt8XFya6AIwyuDK3NjSmmeqAty2wiBkIiVvBQvByz1HOouGmnIxCq4Q0fN9bj7tj(YdXz169fUlAQMyx1iYoiqRVvaYxSBcZOKq7fGlZYa(hYcS)ySJb9fNlBxx07R77lJUFCz)8YXELE5yAh)DAvEydrD9z3R6glV7BWASu2lsYMl3T2u(oYm(k(utpf4vmKmJWa4v4Ju763gjfHnW2GmwoqxEtdVEyFdVh0fm2c3SFcFEC0Keb04yUc0zBs5K1pkoBtcynU8p)gD)BaxTnM02O2A5qMhYxBBjn7rmk10IbLqjw2M6)8nOo78wgnUaN29lbRMC6V(8ElJ7foBt2E8H(vY(MMMTXTmI3nnRorULHfJcitiITHdeP8CGMwhaEpzM)MULXd92XudY1Gqud5IX7))d`

**Comment by Ishamaelronin** [comment]
This is also happening with Holy Power for Ret paladins. Really frustrating, hope this gets fixed soon.
