### ISSUE TITLE
Idea: Text element return empty string if value < 2 (or min/max controls for text elements with numerical values)

### ISSUE THREAD

**Issue by jneuls** [WeakAuras/WeakAuras2#1926]
Simple version:
In addition to %s, add %ss or %s1 (or whatever's clever) with the behavior that an empty string is returned unless the numerical value is greater than 1 (so textual stack values would be invisible unless there are multiple stacks).

Less-simple (but more valuable) version:
A broader scope could be achieved if min/max threshold controls were added to text elements allowing for application to %s, %p, etcetera.  i.e. Return an empty string if a timer has > 10 seconds remaining, so the text doesn't appear until it's down to 10 seconds.

To be clear, I understand we already have similar functionality in Trigger definitions.  I'm suggesting similar functionality at the text element level.

**Comment by InfusOnWoW** [comment]
We do have similar functionality via %c, and the ability to hide text via conditions.

All of what you requisted is in fact easily done via conditions.
