### ISSUE TITLE
Issue with cooldown progress spell icons

### ISSUE THREAD

**Issue by Suddow** [WeakAuras/WeakAuras2#1929]
## Describe the bug
The spell isn't registered when entered, all my existing weakauras disappear from view.

If I use the spell ID, the spell is recognized, but the weakaura itself does not remain visible

**Do you have an error log of what happened?**
No errors pop up in bugsack.

### To Reproduce
New icon aura, trigger 1 type: status
status: cooldown progress:
enter spell name

**Screenshots**
 https://gfycat.com/SoreShyBirdofparadise
https://gfycat.com/ClumsyCanineBumblebee

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Not yet, it started happening after updating today, I'll try to narrow it down tomorrow but it's late.

**Which version of WeakAuras are you using?**
2.16.1

**Are you on World of Warcraft Classic or Retail?**
- [ x] Classic

**Was it working in a previous version? If yes, which was the last good one?**
Yes, I've had these auras for over a month.

**Comment by mrbuds** [comment]
Still trying to get a guild mate type `/dump GetSpellInfo("Shadowburn")` and `/dump GetSpellInfo("Death Coil")`
I could have another one with french client test it, and couldn't replicate your issue.

**Comment by mrbuds** [comment]
Tested with guild mate, can't reproduce issue.

**Comment by Suddow** [comment]
Managed to narrow it down to this addon: https://github.com/coolmodi/LevelUpSpells

In case anyone has this issue again, I'm not sure why they conflict this way.

**Comment by InfusOnWoW** [comment]
That's another reminder why we ask the reporters to disable all other addons.

**Comment by InfusOnWoW** [comment]
Because it overides a global function. What can possibly go wrong in overriding GetSperllInfo? https://github.com/coolmodi/LevelUpSpells/blob/master/TEMP_GetSpellInfo_fix.lua
