### ISSUE TITLE
Showing duplicate zone IDs when mousing over Zone ID box in load tab

### ISSUE THREAD

**Issue by AdamHayse** [WeakAuras/WeakAuras2#1930]
## Describe the bug
one set of zone IDs

**Do you have an error log of what happened?**
no

### To Reproduce
Mouse over the Zone ID box in the load tab.
**Screenshots**
![image](https://user-images.githubusercontent.com/31489472/72949275-d13a6100-3d55-11ea-8881-082710cf7508.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no

**Which version of WeakAuras are you using?**
2.16.1

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Comment by mrbuds** [comment]
I don't know exact steps to reproduce the issue but i'v seen same issue with encounter id field.
This happened after i 'v read the encounter journal for some boss.
It seems it is an issue with blizzard API not returning correct values after some action.
Reloading UI (/reload) should fix it. I don't know if there is something we can do about that.
