### ISSUE TITLE
Rage condition not working correctly outside of Berserker stance for Whirlwind.

### ISSUE THREAD

**Issue by alucardu** [WeakAuras/WeakAuras2#1931]
## Describe the bug

I created a Weak Aura to hide/show a glow on the Whirlwind ability based on the resources condition. When I'm in Berserker stance the glow is disabled correctly (when I have no rage). When I switch to Defensive/Battle the glow is enabled even though there's not enough rage.

**Which version of WeakAuras are you using?**
Latest.

**Are you on World of Warcraft Classic or Retail?**
- [X] Classic
- [ ] Retail

**Comment by InfusOnWoW** [comment]
Please include the actual aura.

**Comment by InfusOnWoW** [comment]
No reponse from reporter.

This is likely caused by IsUsableSpell returning something non-sensical while in the wrong stance, e.g. that the spell is usable.
