### ISSUE TITLE
Model Aura incorrect amount displayed in relation to Holy Power

### ISSUE THREAD

**Issue by Ishamaelronin** [WeakAuras/WeakAuras2#1935]
## Describe the bug

Using this: https://wago.io/3TPZLEVag

I have been using the following weakaura (linked above) for some time now with no problems. Only recently since 8.3 has it not been working as expected. Normally, it is supposed to display a glowing orb model for each amount of holy power I have currently (3 orbs for 3 holy power, 5 orbs for 5 holy power, etc). 

Currently, when I log into the game, it seems to have a problem displaying the model when I have holy power. It will show 0 orbs when I have 1 holy power, 2 orbs when I have 3. Basically it shows the incorrect number of orb models for how many holy power I have.  I tried making a weakaura text display to show how much holy power I currently have, and it always tracks the correct amount, yet the orb models will still show up incorrectly. 

I am able to temporarily fix this problem by going into the weakaura options for each orb model, going to the display tab, and checking the box "Show Model Unit", then un-checking the box. For some reason this seems to correct the problem until I logout or relaunch the game.

**Do you have an error log of what happened?**

No, I installed both bugsack and buggrabber and it is reporting 0 problems/errors

### To Reproduce

Issue is persistent 100% of the time upon logging into the game, no matter where I am. 
I am able to temporarily fix it as stated above, but I have to do that work around every time I log in.

**Screenshots**

![Screenshot (15)](https://user-images.githubusercontent.com/44132743/73046858-7a518c00-3e28-11ea-994f-563bb52980a8.png)
As you can see, the weakaura text is stating that I have 3 holy power (which is the correct amount), yet it is only showing 2 orbs.

![WoWScrnShot_012320_143113](https://user-images.githubusercontent.com/44132743/73046864-7faed680-3e28-11ea-93ed-351517cbab2e.jpg)
Here is a picture of how it should be working, with 3 orbs for 3 holy power. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, this problem persists with only WeakAuras enabled and every other addon disabled.

**Which version of WeakAuras are you using?**

Currently using 2.16.1 
I also tested 2.16 and it has the same problem

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes, I have downgraded to version 2.15.5 and it is working normally again. So update 2.16 and newer seems to be the problem.

**Comment by JinsTonik** [comment]
Exactly the same problem with my DH Model animations (on spell casts, full fury, buffs). The don't load/triger unless I tick and untick "Show model of unit" in the "Display" tab of each aura.  https://wago.io/0gvRAtUsT
