### ISSUE TITLE
Can no longer send a chat message via Weakura

### ISSUE THREAD

**Issue by CharlesW07** [WeakAuras/WeakAuras2#1936]
Get an interface error now when I try to have weakaura2 use the chat feature after detecting an action in the combat log

i.e. if a taunt resisted, it would say taunt, now I get an error

1/25 11:37:57.613  Global variable WeakAuras tainted by WeakAuras - Interface\AddOns\WeakAuras\Init.lua:1
1/25 11:37:57.613  Execution tainted by WeakAuras while reading WeakAuras - Interface\AddOns\WeakAurasOptions\SubRegionOptions\Glow.lua:255 create()
1/25 11:37:57.613      Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:2656 AddOption()
1/25 11:37:57.613      Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:2812 EnsureOptions()
1/25 11:37:57.613      Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1005 WeakAurasOptions:PickDisplay()
1/25 11:37:57.613      Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:4282 PickDisplay()
1/25 11:37:57.613      Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:546
1/25 11:37:57.613  Interface\AddOns\Questie\Modules\QuestieTooltips.lua:-1
1/25 11:37:57.613  An action was blocked because of taint from WeakAuras - 
1/25 11:37:57.613      SendChatMessage()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\WeakAuras.lua:4549
1/25 11:37:57.613      pcall()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\WeakAuras.lua:4549 HandleChatAction()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\WeakAuras.lua:4571 PerformActions()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:815 <unnamed>:Expand()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\WeakAuras.lua:5789 ApplyStateToRegion()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\WeakAuras.lua:5869 ApplyStatesToRegions()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\WeakAuras.lua:5953 UpdatedTriggerState()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\GenericTrigger.lua:670 ScanEventsInternal()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\GenericTrigger.lua:617 ScanEvents()
1/25 11:37:57.613      Interface\AddOns\WeakAuras\GenericTrigger.lua:754
1/25 11:38:08.093  Interface\AddOns\Questie\Modules\QuestieTooltips.lua:-1
1/25 11:38:08.093  An action was blocked because of taint from WeakAuras - 
1/25 11:38:08.093      SendChatMessage()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\WeakAuras.lua:4549
1/25 11:38:08.093      pcall()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\WeakAuras.lua:4549 HandleChatAction()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\WeakAuras.lua:4571 PerformActions()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:815 <unnamed>:Expand()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\WeakAuras.lua:5789 ApplyStateToRegion()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\WeakAuras.lua:5869 ApplyStatesToRegions()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\WeakAuras.lua:5953 UpdatedTriggerState()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\GenericTrigger.lua:670 ScanEventsInternal()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\GenericTrigger.lua:617 ScanEvents()
1/25 11:38:08.093      Interface\AddOns\WeakAuras\GenericTrigger.lua:754

**Comment by mrbuds** [comment]
Sending chat message in open world is blocked by wow API.
Btw for next time you open a ticket please answer all questions from the template.
