### ISSUE TITLE
Warlock pet cooldowns progress spell icons issue

### ISSUE THREAD

**Issue by Saokkei** [WeakAuras/WeakAuras2#1937]
## Describe the bug

I created an icon to appears when my felhunter's spell lock is on cooldown and the icon appears on the screen when I use Devour Magic (or Tainted Blood) (when spell lock isn't on cooldown)

**Do you have an error log of what happened?**
Any error

### To Reproduce
New icon aura > Trigger = Status > Cooldown Progress > Spell Lock

**Screenshots**
https://puu.sh/F3G6k/31597271f0.jpg  (note : I used it when no target for the screenshot but even if I  Devour Magic on a target the Spell Lock icon appears)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.16.1

**Are you on World of Warcraft Classic or Retail?**
Classic

**Was it working in a previous version? If yes, which was the last good one?**
I didn't tried the icon before but I'm pretty sure that wasn't worked before

### Additional Info
If I made an icon aura for devour magic the same bug appears if I try to use Spell Lock, it makes the icon to appears

**Comment by mrbuds** [comment]
Can you export the aura ?
I suspect you didn't check "show cooldown" in display tab

**Comment by Saokkei** [comment]
Sure :)
https://wago.io/uDwaYghf3  here we go

**Comment by mrbuds** [comment]
> I created an icon to appears when my felhunter's spell lock is on cooldown and the icon appears on the screen when I use Devour Magic (or Tainted Blood) (when spell lock isn't on cooldown)
you don't say what's the problem

**Comment by Saokkei** [comment]
I also tried to make the icon permanent and not only appearing when Spell Lock is on CD and the same problem appears, if I use Devour Magic it's make the Spell Lock icon refreshing, is so perturbating :p

**Comment by mrbuds** [comment]
Guild mate helped me test it, when he use other pet's spell it show pet's gcd (his own spells are not on gcd)

**Comment by Saokkei** [comment]
Yes I think it's it ! :) 

Is there a way to fix it ?

**Comment by InfusOnWoW** [comment]
Well, maybe. We currently don't have anyone that knows how exactly the pet spells work on classic. It's certainly different from what is going on in BfA.

**Comment by emptyrivers** [comment]
<insert canned bump message here>

**Comment by InfusOnWoW** [comment]
I think we'll never do anything with this ticket, as classic is now done.

If the issue still persist in BC, we surely get a new ticket and hopefully find more clues to what exactly goes wrong.

**Comment by slinedberg** [comment]
Have this problem atm. Trying to make a pulse weakaura for spell lock + Devour magic. But they keep flashing everytime pet has a global cooldown. How do i solve?

**Comment by InfusOnWoW** [comment]
@slinedberg then make a new ticket.
