### ISSUE TITLE
targettarget not a valid trackable unit for aura trigger set to specific unit

### ISSUE THREAD

**Issue by frankgalloro** [WeakAuras/WeakAuras2#1941]
I started playing my monk again and noticed and noticed one of my weakauras had stopped working.

It's certainly possible that this never worked but I seem to be unable to find the correct Unit ID for tracking buffs and debuffs applied to my targets targets.

![image](https://user-images.githubusercontent.com/23197221/73410169-719d0200-42cf-11ea-86e6-f729b84bf481.png)

**Comment by emptyrivers** [comment]
This is unfortunately a limitation from blizzard, and there is not anything we can reasonably do to improve this for you. Consider setting the unit you want to track as your focus, instead.
