### ISSUE TITLE
Encryption key for shared weakauras

### ISSUE THREAD

**Issue by Andorion** [WeakAuras/WeakAuras2#1948]
Watching the World First race, with how prevalent streaming and custom WA are, there is constantly a danger of someone showing the export code for their WA on-stream, and anyone being able to manually type it in and re-create it.

Recommend adding a mechanism to encrypt exports, for example a global encryption key that a guild could configure off-channel, then all shared WA could be encrypted using that key (and non-encrypted WA could still be imported as well.)

**Comment by krazyito65** [comment]
In my opinion, this is bad and break the spirit of the addon which is to share your creations.

If they want security, they are better off not sharing or hiding it from their streams.

**Comment by InfusOnWoW** [comment]
We certainly don't have any intention of implementing that. We might add some point allow for installing auras from the companion, which solves that problem.
