### ISSUE TITLE
Recognise ItemLink's as well as ItemId's for automatic tooltip.

### ISSUE THREAD

**Issue by aksiere** [WeakAuras/WeakAuras2#1952]
**Is your feature request related to a problem? Please describe.**
For example, I've 475th feet w/ corruption but auto tooltip (which takes data from an itemId) return tooltip for 300th feet (I assume this is their minimum level) and without any effects.

**How it works now**
_(left - currently equipped item; right - tooltip from tsu)_

![image](https://user-images.githubusercontent.com/33295331/73598261-0d847300-4547-11ea-8021-6b4bd640f19a.png)

**Describe the solution you'd like**

> TSU triggers have the "Tooltip on Mouseover" option available by default in the Display tab. However you need to provide specific information in the state in order for the tooltip you want to show. With that option ticked you need to use:
> 
> - itemLink = link : _To show an **clearly defined** item's tooltip_

**Comment by InfusOnWoW** [comment]
This would be much easier to implement if you would provide a aura that actually sets itemLink

**Comment by InfusOnWoW** [comment]
This will be state.link, since those links aren't specific to items.
