### ISSUE TITLE
Using Model glitches character panel, loot panel.

### ISSUE THREAD

**Issue by Naiala** [WeakAuras/WeakAuras2#1956]
## Describe the bug

Basically title explains it. Using model in WeakAuras causes UI glitches and removes background of several parts of it i.ex character panel
**Do you have an error log of what happened?**

There's no log for it
### To Reproduce

1. Make weak aura and add model to it 
2. Open character panel and start fighting with something. Its background should dissapear for combat duration.

**Screenshots**

![unknown (1)](https://user-images.githubusercontent.com/35207410/73617425-cf5a8280-461e-11ea-9f04-eef942d15977.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I tested with all other addons enabled and just WA. Same problem no matter what.
**Which version of WeakAuras are you using?**

WeakAuras 2.16.1-19-g15274e4
**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

It worked correctly before 8.3 patch
### Additional Info
!T35cZjoo2c4)ltvBD7UQnP9dSb26oBvqAshYnbYgi909S7MedyiEcyZyBscPMk)2Vhj5hs2YgzEfsctpD6GrwwV8rFNJo6ORLVU71D8UUJYHY6hkFGC1dgjRPuUKzPR7m56odq)pKIEoUdmDRB0)(bUotVUt9Xwp)SH7GxUTRJZyFl4sgZ8VZXT9uFlhBp4E8VUZixNztB23X(6oYQAvK0Guz3hs1fow2W3FuJwDBCzyUFKZyhx4gBjJ)Ff8pvX)S01TKoudLLZChFDN789N69p(YxE0yKZHwoFXv(3Q9N1kBm5lLHNq)WsqhpFdxFsrzOLTL3DKFh(vYvHF331A0itxpYZTB0fq)6aZEZgoS78PMx35KgNDXXxDg894pAmZ1qbEatnhpU5GGQR3SEMpyA73bUlRNUUZnhvRt3B60T2LqMzBmXmiDZqp)othBmhEoDW3c8amng7FxCMCHRjot6CrJZoJCxXfnFsHhAenDTng)DOca1zOnthYaZXddAFR3UB32NFwJJHN)yhdCp5mpZB6p2WZdvvNbvfYhqTww2Jgdx48AFRb05pd6wdBLG6zFusyVO1ZMjViC5EbdseQ70RVb8iHRfmg46EH)wJbJGYslhB4NUMJGQhPJapMkmrDqfHwY6HFU9WHEM(x3sd1mm5buZR8HshczVVt)hcBLQiPkjbTEWG7JTCnF52Zngb)8V(l0Vzz)YTYFb6Bh6c9yqBKHVbUasg5Em6QKssNJUSrJwOVWAIbAmh9qUodGriOlEdzaJNj8AWaVWXp2O6fu)NappXtD0GyXspChWLhAnImSJ0e10g3cjd1O5HnxhOGApIAFkJVVbwuVj)uysH0nd1WjF5DkZ)Zp)WDxCb(5e9(J3ud37)nRbWy5wYsbFMC3)aF7rz1bv1PldvYq4aodU0XN0e3skXvo3zauJRDv32KHEOXh2dOh8jHh8jHh8jrp4lV39H(9(3JfQ5qENXONNJBp8tRomk00201QFN7CESniDZd(3AJF0yUxY3Ur3koV6FNH7i89IfA0cggHAGQurtn4PfKIoYzi5zMDGOcsHkCia(gqpg2Yu9ijlhbsOh48imU(cxNrUMEEVC7N6GkeFMrSKlibQtuzl4vJ6G0bFs(hxURxijFbdrHURzEKCc3evNQXbNJIi4lNgE84DKW)hm7sspUZQ1bWOqKSsyi9n9ZvMKCMYu5)ko1lBz9cj1R4IL64xXfk9y5T0ZCESEzzzLs6AsQAQkAWuUdpqReQQECfvvDPYL0LkPwPC5sLqFJg1Bf4Q)atpOFcEAMirXuV8(tYREZ6Djwym1lnrticLKBG)cxY8j)B8UZag1fw08dUA)Op7JkuW9Bm1c9O4FptGUWX38e(zt(Dp)BGHrTkjHR53qU4dwEw9gJhysUWud8CPObPEFrF4t3megnFZeZbwZMCZyNh9G)E4efQm1Do1dzO1yZMGuUQQLljxkvrpquk9vi33C2cQluWvktFf)NXPWLwCwqF6SEq9bNq60tQ6X10(JbwREHP4z2NN)8eP2y807iZEfxMW3JpQFVltR(pcLeltvKqFFqQi)6FBAIwJCEvcNUHoizq1EWW2)BaWO5xnNyvVl3(B(cRJZksQ)z0mgYHxpM4HmpaU51SlUa3QDRgbPJAuc(Zmt30SvRgxEt4KoKV6NuZ6HVJ)yMNV1W5x3HWufvbd4qI4B)rYBeLiI482x19SMqrYhv56s37taGchBrYiCNz018ipMuJ)YPHliLuv9GRyI5RKHjfSEcnKl4YorfCSWL7mTgDhAmrjEeKbIWNA63ZW3FmwKbwMoa1zJLWh8BX0LTisJdMpPpknfbanmxueJffl)QouegeGj81VIF21gG6jnhyo4CJNqLAAojVjoo(3foxzqLK6oaX59yzsde(rMKb9LC0fcp)JNfQuCzZVDcuwF2XzsmqvltZJn(H9V)8jndk3Ne02RgmiAMlCVng)WvnXtlBFFacBDayTpcF94XWKZVClEErug0n8MAIMtBOrFZ)ZrWS5qtyDd3)Zvnpi(th0bDdb3hwCCAEzsHYAWat4b0QX3JFpHduCs65hjeHvrVIejucNJhjYCYOYcE0lM9b(xhxlyGvaa0jTVS5V3Uv3ANLMCLV6GrQasRyOpJYtbIccNMQaCTLvEJW1YGqMdslTURIXZYG8LKUnbildripvJZfGnnB(MIJLpGkF0BgYwE087gCTPhUVhNKfNmlsVfrmUSyO(0zAw4K8a8yqktq7LINKMEmnBzUaPphd1W04)ogNmdcUneuzA41CykJapdXjtHXXLNmlOZnaqziZ6QJt2JloPCm0h6d1HFQa)0FxKYuuENDzlkUc0XcrfVSKRHGHIIoZJMnIippmyAMBAywHTxCakSCjLa0)F0DYXp3rA0zFBadRlTsjcZ7gPcsrwgKq53leYDTI1gwulKDytHATw5wPjvvsz6YS5wziPFBGTY3m1728Q7Ycg39aN3qiXzIhUiRMwqi3uK38rC95J4kOjtDFwatMo)9Vjt3wmUHPBTq5M0EO8SzAAs41jKBsq6pugnvuCwowzyvOilK)D8(I5uH1oVRgakYwSy(ZrLkn6sPh)UX5(Ri)jzMO(3zcGeuCCOsZdgUwgOxM6q4RGzqros0l)1VI(UXZWMg0h)T2JmJZSPUotnDHzmqVLDO6HmcK8dhZs7FcfZAPHIue3(UVzmV761Tf47nujaMzTLB2(RafzUi0YCq13EERq(g3DVBl8EXTf2OoKqr9WGIXkZbjNbwox8w)NYXMXpNlmDm(DkA9pi4YXR8FUe0BtI54XEFa8XG3(gfgJG9ON5PF)N)r7JFQXRGdiW49df01du6V68Zc6Sb0gonwoMWUGWs4Tbrm5Bc83iQ3iq4Lg)Dn4KdAVrS)RWaT5SC9f1bgkU74UuUXqkqZngJln1UkF7Khk4nGMFV)kS3SRlHzxRV3SRlfh5RTfx57RQVJDUG3qMDfdm(hhn6e9F7H6ZnNwydiTExc)IXESHOqvtAyuKPr3UyPSU26BwQ0KgLvznyu2Q722IckH64MOf3l0hEhXzcri6Wz24H(F6ZVCkAah6pwdF5w0ll3yA)WHi8ry4OH9GKx8qO1Rp01n15rt3xU1)ot748i8pUMWaxyO8LOxS)uozWNp8WF5V9lXzaic5LtHFqHRlRjLbVE)aQuyy8uIv)JQIxnDaceQZSW)DlU3BbjsHGTOAEiHkAqlgag1SDo(FPSHC4EOLf)MpyCc1cy3wVcUrEfWrjwenmpk37nnNwdnlI)LOHSysuolHMVv)7N)1q1o6XUbo5rQYHGskxckVDgckPCbOssljKv42cRyTIuKYafVXF675gF4Rae2UTVyZ2(RWsgQwUiKHcY8r(y9vI9JM1cBvKiXYO67xT8qtspavWyvqD3ERNtQb4nYFVyQkm(kmY48Z(E7oT7Eb9sGl0E2V(5rmxOouX3N(rWz0KMHCv9yxezCVqDbjPoGbLYYUVZeyOehWPyd2LIJgTWYVZHquL3kqiHDD5Awrw77rB7oHJIhPmgjxkeFexTFkZfMbgclRsq77DbzOQA6TppBsQN4EUbHPB4Jun))9x3M8k7YcMsyJV1bOevJ(BSzT7v8zTjrvMaT3300tuZEJSm66XUoQjnRtotB3kAHdlehGOZZhmrwPeXFLIPi1alpKYo4iTulfvDLQsPN)LEspkBUWhZihtGGMc28jZ(ZqsJtn57InasQqjtPN)(pCAQ)TJE8BmthZXwtjaewLjNdSVb2cZPSVr43DOUgTXoi1oFQDBixRQGmHY)m2ckiZxfxayfyN5ZMwYH0Hs60)x5KV(hxcjIDclDrvJszxnufW4qjMhcv)(146Nu(wiI(P5lMMSqXQcUy9gf05av9Dfqhr3YmTTV00yW8mbtYjwOLZ2JXRqXIiwZ2KyXpB2hV2NoOvdErR9z865wsRKALfW0LkqkfT(NX0Ejx(tpUnDjFUXYjOV18mavyBzUf4CBOlChEUT6a7b86e0qmLtREswuwA4LAlrf7wLXTLkQAkYvlCxq0TfTcIX3BstkEY8PoGyb3jwgecuFqIOhBZvnmumNayvqaqSxIxsQD55e)ei2sMOKtsZrywIEP7lt6fUFdfU7aAYzeFDkHkgqtzB7XZXlugKR8lWRAelKtdeAoulBZZjTtKh4zGWrp)C97cMbiCu8iWB12bFxjCG7QiKAl96sOONeVTWt2ecC8pWZRIgNyyp)JLQFtdAuHrx9T8ICxP1IcH7TC(QTxVkNWYTvI19tiL14QtiswGlRlJYyDwdKaeSmp2Rxen)GuGJqPjZd4n1uAeYQgRRZ40PyirtqU3zO2RtFyAgvObwqnQpCL5P(kYDOiAuDntnxr9mftBvoAaWg6rtQ36cFfcRgP2vJ6QBzE05nhhR)kx9BRlQLMXIZ7reNVeA6MEf64z456C10L2RiwSoULO1wZHA2QanaLZwrZ606QrjFmFTCvwWdCb6eM(5OUDvEVKaA9UoBhPwpeukJJvyYkiJr1QkkJIVAfL3Sk)E8bAs66AL0uQOvrPKMS61dpOu5vxF4KYfev73v1HHxcnFzqel4wDtehb(RUgJCS)FGBRo8n41AyvcqeXOHQY66Y5Pr8gXJGxjWYDJDZ2Mynf2JqUwx(aAesXx8)iWk)xjhbOyUxz)LA34ZH)ilWPiUKfScbPfrrZ(Kr0bfZsgXvHP668Tg9oF69JSoTnlYuwqx7ORjWwbRGNH0bzSmOfLK)GBx9u(LY6ZNfzM3pHrQO2JrAQA6f0rdksuVkdoMemeNB6B64UqYH82Ltf2kvVQ(l5(POFNnfDERWVICo2l5vF1(XZZTdBMuAZXS4LHmTzocvndpdE75Md)8JD6o14QyQHc6YFHcRwcJWiI)0jSvzYIkANh6WY2dnltF0(f5stpNzW8UEIWFeij6qTaprqlzJxAFpqy3kyZrcroGJ6UN0zdr6i(ULGZsPgYPKyTmtCaP14jlpFpIFaXUyTk6v11KJwOFkufMD9bFkiQvmLAHz3Vro2VxceFVCmASZJh7A(NZmT7J2JYhQOr16J(wsAOZn0Nj1KEZ89DSBd9XWivYxCMP9OWqUa6Z)mXnkW2degmhNscG03O)m6l7eDy7Hln3bd7SrBa0WReMUZSGlJCbl8NQhEW8TKOA8GJ4BILyGmjX3sTlhXgd)iF7U8w84(lc8AHqBjmiqXGKY39rRVqJdDXCxhuV1K8cFHuSYyosJlpZUV5t)lJJ7VimT3gUjA8tdn5d0Wjaeup6NtyJaR7Ewp52Zv5q8l3HqzP9VuzXy6sySjg9P9XryPUbrVHMExHMlUNyNBSKWKbNUrbOHOdJgf4uKTygvvysOKKkhbJHqt9ad)9f8GEnxMgkIfkAP8DUXndzd)ipch4MKbFKmcMipL21Bwzt3VbJvdybsw3BxY50jN8VMyu0t9wc7azUyEhbUut(G)X1D(ntJ7RbdV8(hXdQE526qF7l36eYsqplwqiIj55KBQyntQqYsQtFx6JYMJqgZFMR5xQ56FNH3yR(3Dp009fdMpIpsBmga4J9nJLcqD48YeBbtES0MXKg5uVZpI2KEM8gN14OUhFzTZBWmntMRqHw6O4i9Uyi5rWqYyKZUDOpqwDVIYcPOCW0db5dsIe8MlQ2mcpM8xPAlcU2POwnBh)WeHNiozRsq2q(kitWVIrET)t)Yfyj)i5XJ)L)oKxwJ)7HzgvNdtU)RH5vWFof3QrLK)rht))pqZuCU22(eRbMFcDuG)5uPQ24X4gvVpf9itKcCE8P)9)o4iUYYgAVGx6TnFCQJlayFtpdptqCW)9)M4EXpv4AHJ1cReOmfP4YNqwka9ljgdsD9mhDrvcHetpk2CSNz(3ry5k5qUxofEpY5MG((EfdsiFUGIU(oCIUfblSuvjv5Qmyc57B0modnx)CrKL4HznHsT)bIQPlALMyS)dZIoXWyTebFzVmCjfH8(z5v3fvMtzEgIezcUdunS9gJmebXWaG4W(zlUoSMtULqyhIUg92g(4sA7uX3bQx7wVk7Lzt6WQ6v0vkxstQkGkuLRfOEtTfBFZgvsowtxtwRSUKKs1YLkdOLdpqRCoDihz0ZY(G6GGL9U5opfDYYrYtPZtwETEg(eoJJWVMCPPyJWLN)QNVNUlMhTZ1n6xFU5o15PzklcgJ8FOKKKQISIAzDDjfznTkC19v8DWzsR1I1VSEZANp8BN4CEThO97QSxOZLYwCmQvD1XhNY6zj1eIrHP16ARUJBLoe(G4lzkrOOUsLYQLROkPQkvvTAfKqr1fV9TfXCBLENhTy2H2e1lX5KTaEnEbyZf6msri3(Qaa581SGZXHs6TyzS)ItRRIGC5P2X0lw9jwF8NZrztg7rx2ogknmYFx6MZ2UnJf3MEVFMrhvoRuEcBclO6D5TjDPBoB2F(l3(Dtq39GCNDphZZAXRFnNwOd7TxxJ96AiKxlSxVIa9kil33Q5Sc1oQZDwidd8Q5McHxnT7kuu3uyZTVHZsjJIODvwAXLJUnS6uXtXOS1JIwBRS0zJRAAzPwAgkuLCv9fDdUWXR02B499gEp417CTZkFRQM28RRQDw3wbovUgh4HVpV35T(95F1OjLXby0nFfnhqkdbuOy7gptK8oYwaR19yVQa7XEXDrOobhrgjJr)rtQl(whtBVjgEv3pzRNn(1QAkIu7g8qfzflMUXO5CcRrCj81VCRdm84cuxwHwJqru7Nt4rswwxswE7V71fYXV)qTR0y0suGJ9OT7bEuU6SYX16lydvYwKLVsXBKqX66bvNS8WhPo9Vhh(YE6P87pfQBI6BIYafUwiOi9lBAVcS4R4L47K)fsnHCfBXDH73ohfayI1kpCvLV(JbpE8LNU07dWuZxiK7J)UD)9Liq8Y9aDAX7SpDPYvkPkRwwrRu1WT5xIlQY7Il9wamvaeUiL7cfreOSpSp2by7YVFFpa7MaGTORBgE1iS7BGqQqHoKJj7BHvo4dtH)PPPIo(GfbDLAvEsg7eSCDDGo4MtmgzkCWxItarnfD)cxtWLEL1s3iKfy72yDB(qURg79gk8lKN3hTuEpeBeBOyUde3TqywgDFXUdvioxLLzxgMJ94Z3A7mePCTwFg2H)9Z2tuCVXiTQXKy858VE)C3AdU)OVU6HOkgP4OZl0SJUeRfFEkbIld1)h5OwvcgTY7z02u(XushPjfRfsKNCjD85JJOWBzUDecqT4Y5W4Wnlc)RaokfLVXS6wNCTG5XLDLnkued1LTpaTtr4j6ob4dfL3oT5m3fO8YkaOVHP8k)ks5vGi6(cC(8ukPVdhmC399KBFqERx8b0vKfPeYNU1K0KLQQlPPORvrVCPc4t3cfwSsu6kvSsxjnfzfDPkskQLRwUQmQ0vsWsxPIx60kuPJiN9ynv9kvRwwrsPcuuLqriCnDb8h(ew8gnNDIGQFXcSduy9f0q0HykHukzQmIWNoTy9BQ18p1M1zy)p)ZJyuDGrxbAFEn1j)hYlTPHRx8SMiM79N2AB5Z2(cTU(jw1BmTiXm5lWH2JnokViJMy408pJBxHne8m87nORS4GplTxZtDYEjRwn)TDWsVVGt9y44U7Oc(wic1U)0jA5mCAZwT22hsT7DW9TUdURNVVaSkBq2SukAT75azPBtokFST8YBgn3wDpC4TsWowKJpHfeTJRnW90wMv6nZEDDkurpLzbmtD2N(ZRZtEQ3P2Koc4UIcgqU6(yK0sC8lrbUM5PHGIQMQS6IoIIkWsOlSPQtqMwFSXZG06xUTUHRRL5h3JgHp8rF494M7pUk2CNOuVEoGkfEq08BOZFqHoInxIJbIDExsDWPnU47h95Q)MC71fSw6zrY2fvZgxUqMAAtH296EasOSD5nFTpVkqvbuqDrbLJx)))d

```
  ERROR HERE
```

**Comment by InfusOnWoW** [comment]
I cannot reproduce that. I do remember that there was a outdated addon that lead to this problem.

So please try a) disabling all other addons. and b) updating all addons.
