### ISSUE TITLE
Event - Combat Log, Add npcID check to Source and Dest settings.

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#1958]
**Is your feature request related to a problem? Please describe.**

Using npcID will help people make Auras that work across locales, and help people avoid custom triggers for that.

**Describe the solution you'd like**

Add an additional setting to Source and Dest sections that compares the provided number against the npcID (6th value in GUID IIRC)

**Comment by InfusOnWoW** [comment]
#1331
