### ISSUE TITLE
[Idea] Conditions Tab: Add Buttons for Reordering 

### ISSUE THREAD

**Issue by anaseskyrider** [WeakAuras/WeakAuras2#196]
The conditions tab, while awesome, suffers greatly from a lack of good "user experience" design. The main issue I find with it is that it's slow to use and if you have a slightly complicated aura, then it becomes immediately unwieldy to read the tall list of conditions in any kind of logical chain when you're trying to fix it. It requires a lot of starting over when you discover issues with your aura, basically requiring trial and error in order to get it right because it's difficult to plan entirely ahead, or otherwise requiring that you prepare the logical chain of command for the conditions ahead of time in something like Notepad.

The suggestion is simply to adjust the UI so that you can reorder conditions quickly and easily in a manner similar to the aura list on the left half of the window. Add buttons, allow 'drag and drop', something like that.

**Comment by krazyito65** [comment]
Could we extend this to the trigger tab as well?

**Comment by InfusOnWoW** [comment]
This is in the next release/alpha.
