### ISSUE TITLE
There seems to be a problem with Hybrid Sorting

### ISSUE THREAD

**Issue by Idubaren** [WeakAuras/WeakAuras2#1960]
Hello. You see, not that long ago I made some auras to show bosses health bars depending on how many bosses there are on screen. Long story short it works as I wanted thanks to help. Thing is! Before the recent update that I did today Tuesday Febrary 4th 2020, as I went into the game and went to try  once more and get Thori'dal Fury of Stars from Kill Jaeden at Sunwell I noticed on the battle against Kalecgos (a battle of 2 bosses) that the healthbars seemed to be moving and shifting in place, so I decided to check what was happening. So I did, this is the only way I can explain it realy since it's how I saw it. upon entering the weak auras menu I noticed that all the bars where missplaced. They kept doing their job and everything but they shifted possiton as more bars appeared, which was something that didn't happen before the update. I fixed this by going into the Dynamic group and in the group options select "nothing" in the sorting submenu. However, I was told in discord that that the hybrid option shouldn't affect the position of the bars. I don't know if it's a bug with the hybrid option or if the update did something to the position of the healthbars anchoring. I have still not updated the wago.io with the cahnge I made so here it is in case you can replicate the situation. I didn't try other bosses since upon making all bars vissible I noticed that the bars used for more than 4 bosses where posstioned weird like in this image

![imagen](https://user-images.githubusercontent.com/23164653/73773225-b0243800-4779-11ea-9351-1b5a38e3de67.png)

And as said, the bars only went bar to the position i wanted them the moment I disabled the hybrid sorting on the group menu of the dynamic group where all the auras are stored, here's the link to the wago: https://wago.io/csE1hc0ga

**Comment by InfusOnWoW** [comment]
I don't know whether that behaves differently but your settings are all over the place, which makes it hard to determinte.

From the look of your auras, you don't want to have a xOffset and yOffset set and probably should make them all the same widht.

After fixing that, the auras appreared in the order that they are set in.

**Comment by Idubaren** [comment]
Uhm... well I mean... The bars are diferent sizes because I wanted them to show depending on how many bosses there are on screen, I got that part covered arleady but the thing is that, with this sorting options I made them and got them to look like this
![imagen](https://user-images.githubusercontent.com/23164653/73987773-5e2a1080-4939-11ea-8b8b-aa46cc567c9e.png)
this is for when there 1, 2 or 3 bosses on the battle
or like this:
![imagen](https://user-images.githubusercontent.com/23164653/73988064-7ac64880-4939-11ea-8d68-ecea57916d72.png)
when there are more than 3 bosses in the encounter.

AS you can see with the hybrid set up i could make them work and be positioned as I wanted. And also I added extra healthbars since they are for other kind of targets like, rares, rareelites and quest bosses. Sorry forgot to add this images as how they should look, my bad. But this is how they looked before the update and after it looked like i posted on the first post

**Comment by InfusOnWoW** [comment]
I'm not sure if you understand how dynamic groups and hybrid sorting works, because that's not something for which dynamic groups would be a good tool to use.

**Comment by Idubaren** [comment]
Honestly, no, I don't know. This is the first aura I work with and I needed help to get it working properly from acquaintances and the Discord Server. So if there's a better, more efficient way to do it, I'd be glad to learn.
