### ISSUE TITLE
Weakaura nameplates don't work with threatplates

### ISSUE THREAD

**Issue by teyasio** [WeakAuras/WeakAuras2#1962]
Not sure if this is fixable or not.  But I tested this by not loading threatplates. Had no other nameplate addon loaded. And the weakaura works fine.

If it can't be fixed. Maybe add a tooltip in there saying may not work with nameplate addons

This is using the nameplate option for auras

Thanks

**Comment by mrbuds** [comment]
I have no idea what you are talking about, please make a new ticket and answer all the questions.
