### ISSUE TITLE
Recent update 2.16.3 from 2 hours ago DOES NOT WORK

### ISSUE THREAD

**Issue by JeffreySWhitmore** [WeakAuras/WeakAuras2#1963]
Edited for correct version

Installed 2.16.3 via Twitch/Curse from update 2 hours ago.  
My WA frames no longer show and I cannot open /wa or /weakauras
Reloaded UI, restarted client, did not help.

I uninstalled, went back to version 2.16.1 from 2 days ago, and it worked.

**Comment by nullKomplex** [comment]
Try 2.16.3

**Comment by JeffreySWhitmore** [comment]
Correction: 2.16.3, not 2.16.2 which I was using earlier today,  is actually the issue.  Sorry I had a digit wrong.
To be 100% safe i went back 3 versions to 2.16.1 from back in January 17 and that worked.
I just went back an installed the new 2.16.3 from 2 hours ago and it does not work as I described.
I understand the WeakaurasArchives is being added in maybe this version, and that's causing the error?  idk tbh

**Comment by Wevah** [comment]
Yes, I'm getting a bunch of "Couldn't open WeakAuras\Libs\Archivist\Archivist.xml" errors. Along with

```
2x WeakAuras\WeakAuras-2.16.1.lua:1547: attempt to index upvalue 'Archivist' (a nil value)
[string "@WeakAuras\WeakAuras.lua"]:1547: in function `OpenArchive'
[string "@WeakAuras\WeakAuras.lua"]:1562: in function `LoadFromArchive'
[string "@WeakAuras\WeakAuras.lua"]:1582: in function <WeakAuras\WeakAuras.lua:1578>

[string "@WeakAuras\WeakAuras-2.16.1.lua"]:1734: in function <WeakAuras\WeakAuras.lua:1685>
```

The Archivist.xml file exists.

**Comment by emptyrivers** [comment]
Always restart the game when updating addons.

**Comment by Wevah** [comment]
The game wasn't running when I updated it the first time.

**Comment by wangyf0411** [comment]
Same problem here. Latest working version is 2.16.1. Tried updates till 2.16.5 and all they cannot work.
When login account, WA is automatically paused process, need to hold 'Shift' + 'left mouse click' on the mini maps WA button. And /wa or /weakauras cannot open WA options.

**Comment by InfusOnWoW** [comment]
Same advice, you need to not have the game open while updating addons.

**Comment by RBLWell** [comment]
Game wasn't running when getting updated.

**Comment by InfusOnWoW** [comment]
Then create a new ticket and pay attention to the questions that get asked. Especially those that ask you to run with bugsack/bugrabber enabled.
