### ISSUE TITLE
Issue with Progress Bars and Icons

### ISSUE THREAD

**Issue by Hebizuki** [WeakAuras/WeakAuras2#1968]
Issue: Progress Bars with icons will seemingly randomly have icons hidden. Progress Bars without icons will seemlingly randomly have an invisible icon appear. Reloading UI appears to fix this, but sometime later this issue will appear again on random progress bars. It does appear to happen more often to WA with TSU's or auto-clone producing multiple progress bars.

I have not been able to force this issue appear (hence the usage of 'seemingly random'). However, I have been able to consistently produce an undesired result which could be related (with added screenshots of the result after each step):

1. Create a new progress bar WA: https://i.gyazo.com/0b9f57aaad53f1f82a7162e30d211d9c.png
2. Disable the Show Icon: https://i.gyazo.com/fb2584599055367580024a3cc78e1dd9.png
3. (Optional) Click Add Border: https://i.gyazo.com/8f086e846f3d4146e9762cec3d553c7d.png

As you can see, in image 2, the width of the bar element does not take up the area that the icon would take. This is even more clearly visible if I add a border in image 3.

A real example of the issue can be seen in the following screen shot: https://i.gyazo.com/bd99b7eaf9fc3fffe619a43d8f9520db.jpg

In this WA you see 6 gray progress bars with 2 having empty squares. These are static progress bars (which have value 0 and maximum value 1) and grey is the background. If for example I put the border anchor from Bar to Background, it will look like this: https://i.gyazo.com/f11d70ae697d5f5b7435775cc8a4cf85.jpg

These 6 bars are produced by 2 TSU weakauras as can be seen here: https://i.gyazo.com/c2459c35ecb17bd6e2eacca12d406add.jpg

A link to the full package is here: https://wago.io/BVGQHg3fA

Again, this issue is not limited to this WA, but to all progress bar WAs. This issue has been present since I updated WA addon a couple days ago.

Bugsack does not record any LUA errors related to WA.

I would greatly appreciate any help figuring this one out, as I am at a loss here whats happening.

Thanks in advance for the assistance.

**Comment by mrbuds** [comment]
I can replicate issue with last commit from master
Doesn't have issue with another branch with last commit 
```
commit 8cc83296542a81b3cf0c728ce9e04999ec141b96 (upstream/master)
Author: Allen Faure <afaure6@gmail.com>
Date:   Thu Jan 30 00:09:39 2020 -0600

    swallow stacksfunc errors
```

**Comment by Hebizuki** [comment]
Thank you, that tentatively resolves the issue for me.

**Comment by mrbuds** [comment]
changing icon position from right to left doesn't update it's position

**Comment by InfusOnWoW** [comment]
This should be fixed now.
