### ISSUE TITLE
Zone check bugged again in raid after using teleportation device (similar to fixed #1695)

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#1974]
## Describe the bug

The zone check after using a vehicle in raid is bugged again. So by that, a weakaura that is only loaded in that zone would not load until you open the config window and close it again.
This issue was tracked in the last tier "The Eternal Palace" and was fixed. already. Now this issue happens again in the new raid. The old tracking ID was #1695.
Happened after the boss fight of Vexiona by clicking the spawning transportation orb.

**Do you have an error log of what happened?**
no Error log, since the is no lua error or smth. like that

### To Reproduce

1. Go to vexiona boss room
2. Click on teleportation device -> teleports to zone beneath
3. WA won't load 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no need

**Which version of WeakAuras are you using?**
2.16.5

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
was bugged since the 8.3 update I guess. never worked in the new raid.

### Additional Info
Wago.io Download:
https://wago.io/irIdjAboZ

Bug was fixed in previous versions in the last tier:
https://github.com/InfusOnWoW/WeakAuras2/commit/ef622c342069b87d84b31461ec0b8100358a63f1

**Comment by InfusOnWoW** [comment]
Please include the actual aura that is showing the problem.

**Comment by Breakerzeus** [comment]
Description edited --> https://wago.io/irIdjAboZ
