### ISSUE TITLE
Error on Loading

### ISSUE THREAD

**Issue by MetalHeadSeven** [WeakAuras/WeakAuras2#1976]
When loading any character or changing zone I get the following error.

3x Error loading WeakAuras\RegionTypes\DynamicGroup.lua

That is the FULL error log.

**Comment by InfusOnWoW** [comment]
That's a broken installation. 

Please do not open another bug report without filling answers to all the questions that are relevant. It's a waste of our time and we'll instantly close them.

**Comment by MetalHeadSeven** [comment]
Thanks for being USELESS.  I have on other information.

**Comment by InfusOnWoW** [comment]
If you can't answer simple questions, we can't help you. It's as simple as that.

**Comment by MetalHeadSeven** [comment]
What Questions???  I have NO OTHER INFORMATION other than what I included.

**Comment by InfusOnWoW** [comment]
The questions you get on creating a new bug report.

But like I said, this is most likely a broken installation.

And thank god, that we don't have to deal with your attitude anymore.
