### ISSUE TITLE
Space between auras in dynamic group after converting icons to text issue

### ISSUE THREAD

**Issue by Alex-Miller** [WeakAuras/WeakAuras2#1977]
Spaces between text auras (after converting icons to text) depend on icon height and width. Same for horizontal and vertical
![1](https://user-images.githubusercontent.com/2015294/74103108-fe5a8200-4b51-11ea-933d-ba88f6d65ec2.png)

**Comment by mrbuds** [comment]
Please make a new ticket and answer all questions from the template as best as you can.
