### ISSUE TITLE
GetSpellInfo(spellID/name) support for Status - Cast

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#1980]
**Is your feature request related to a problem? Please describe.**
Occasionally you can't tell the correct spellID since wowhead tends to offer multiple that have "cast" in their tooltip, e.g
https://www.wowhead.com/spell=318971/dark-matter
https://www.wowhead.com/spell=319259/dark-matter

so instead of making multiple triggers, it might be neat if spellIDs that are put into the Spell Name box are converted to names, similar to how Aura handles it

**Describe the solution you'd like**
- SpellId (GetSpellInfo) support for Spell Name
- Renaming Spell Id to Exact Spell Id
 
**Describe alternatives you've considered**
making multiple triggers. not sure how that affects performance

**Comment by mrbuds** [comment]
That's already how the cast trigger's spellid field works

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras2/blob/e7982ffe753b36fcd8ce3ce8938b587936612883/WeakAuras/Prototypes.lua#L5371
