### ISSUE TITLE
Add more options to status>cast trigger

### ISSUE THREAD

**Issue by Nnoggie** [WeakAuras/WeakAuras2#1982]
**Is your feature request related to a problem? Please describe.**
When using the status>cast trigger and a unit type like "group" i would like to check for example only for casts of certain roles, similar to how buff trigger can filter for certain roles.

**Describe the solution you'd like**
New option should appear in the status>cast trigger that filter out units that do not match the prefered role type.

**Describe alternatives you've considered**
As an alternative to this i filtered out the states that did not match my preferd type in the custom trigger logic custom code block as seen here: https://wago.io/MRZKqbjnf
**Additional context**
Maybe more options that are present in the buff trigger could be carried over to the cast trigger.

**Comment by mrbuds** [comment]
Your example is bit too much of a specific case for my taste to make it to the generic trigger.
Do you see more use case ?
