### ISSUE TITLE
today this error----

### ISSUE THREAD

**Issue by Pozzyx2019** [WeakAuras/WeakAuras2#1985]
today, while doing the valentines event, i took this bug in bugsack ...

1x [string "--[==[ Error in 'Temple of Sethraliss - Nox..."]:15: table index is nil
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:519: in function <WeakAuras\GenericTrigger.lua:512>
[string "@WeakAuras\GenericTrigger.lua"]:665: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:626: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:759: in function <WeakAuras\GenericTrigger.lua:750>

and this also while I was doing grottamarcia

2x [string "--[==[ Error in 'Waycrest Manor - Devouring..."]:15: table index is nil
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:519: in function <WeakAuras\GenericTrigger.lua:512>
[string "@WeakAuras\GenericTrigger.lua"]:665: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:626: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:759: in function <WeakAuras\GenericTrigger.lua:750>

retail version game...

hope help me tx ciao

**Comment by mrbuds** [comment]
Please answer all question from the github issue template and include the auras that are triggering this error
Temple of Sethraliss - Nox...
Waycrest Manor - Devouring...

**Comment by InfusOnWoW** [comment]
That's a issue in your auras named " Temple of Sethraliss - Nox..." and " Waycrest Manor - Devouring...", not a error in the addon. Thus we need at least those auras, though you might get better help by contacting the authors.
