### ISSUE TITLE
Add WeakAura Save/Load Profiles so different Alts can select different batches of auras to load

### ISSUE THREAD

**Issue by DaynishWoW** [WeakAuras/WeakAuras2#1987]
**Is your feature request related to a problem? Please describe.**
I like certain weak auras, but I'd like to quickly load batches of weak auras tied to a profile-tag instead of each weak aura having a-la-carte load settings.

**Describe the solution you'd like**
A simple profile maker that allows the user  to select which auras they want to add to a profile, as well as which profile should be currently loaded. 

**Describe alternatives you've considered**
if i have a group of weak auras that I like on one character, but want in a different place on another, I currently have to make a duplicate, and have it load if the name of my character is something specific and different. But if I want to use that profile on another alt that's not the same class, then I have to duplicate it again and change the name it's referencing to see if the load is valid to do.

**Additional context**
Please make it simple for people who play alts to load weak aura batches by profile-tag

**Comment by DaynishWoW** [comment]
There's got to be a more memory efficient solution to having the same weak aura in different places/configuration without having to entirely duplicate it, change the display/custom option settings/group settings, and set the load settings to be slightly different so it doesn't load on Char A but does on Char B. It would be great if the adjusting the profile would auto-adjust certain values on the weak aura to be moved pr reconfigured to the correct place without a full duplicate needing to be kept un-loaded.

**Comment by InfusOnWoW** [comment]
We don't believe that complexity is worth the benefits it brings.

The benefit in memory usage is neglitable. The main benefit would be in not having the duplicated auras, which is indeed some benmefit.

But the additional complexity in the user interface where every option becomes profile dependant is staggering.

**Comment by OzanKurt** [comment]
It is worth 100%
