### ISSUE TITLE
Automatically change SpellName to SpellID in Aura Name if 'convert to spellID' option is selected

### ISSUE THREAD

**Issue by DaynishWoW** [WeakAuras/WeakAuras2#1988]
**Is your feature request related to a problem? Please describe.**
Many times people make weak auras with a spell or aura name in english, or german, or korean, whatever their client's language is, and there's no easy way for the author to quickly change the buff/debuff name to the spellid so that the weak aura can referenced and triggered in any region easily

**Describe the solution you'd like**
a check box next to the Aura Name that says "auto convert to spellID"

**Describe alternatives you've considered**
Have to go back, find the spellid, edit the aura, and re-upload it, and mention its now changed to work across all regions

**Additional context**
This will allow people from different regions to easily convert their auras for others to use. Plus, it will allow users to not have to find the spellID separately of the spell they are thinking of, which is usually in the name of the language they play WoW in.

**Comment by InfusOnWoW** [comment]
That can't be done, there's no api for that.

**Comment by LybrialsGit** [comment]
Hi,

what do you mean with: "there's no api for that"? 
https://wowwiki.fandom.com/wiki/API_GetSpellInfo

**Comment by asaka-wa** [comment]
WowWiki is always outdated compared to Wowpedia so default to that in all cases. (Wowpedia isn't guaranteed to be perfectly up to date, but will always be the same or better than WowWiki)

Think of it this way. There are 7 spells in the database all with the name "Vivify". There's only one with the spellID 116670. So how does WA know if you want 157851, not 116670?

This is before worrying about the fact that I can't do `GetSpellInfo("Shadow Word: Pain")` at all on a non-Priest, while I can do `GetSpellInfo(589)` and get info back.

**Comment by LybrialsGit** [comment]
Thx
