### ISSUE TITLE
Text placed over Border-Edge of an Icon is rendered under the border, instead of over of it, resulting in the border's line cutting through the text

### ISSUE THREAD

**Issue by DaynishWoW** [WeakAuras/WeakAuras2#1990]
## Describe the bug
Text appears under the border but over the spellIcon graphic in the middle

**Do you have an error log of what happened?**
no error log, just the visual bug

### To Reproduce
make an aura, set it to have a border or a pixel glow that's on the border. place any text in one of the text fields and move it over the edge using the x & y offset values under the text configs

**Screenshots**
https://imgur.com/a/KYB1xYo

**Which version of WeakAuras are you using?**
2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
not sure

### Additional Info
just a visually annoying bug

**Comment by mrbuds** [comment]
That's not a bug, you can change strata order by reordering sub-regions

**Comment by asaka-wa** [comment]
That doesn't mean it's useless, just that you need further clarification. 
You'll find Subelements in the Display tab and can use the ▲▼ buttons to change their order. 

If you need more assistance I recommend you visit the Discord and discuss it there rather than dredge up closed issues on github.
