### ISSUE TITLE
cant find chaos strike on the templates for a new aura with DH

### ISSUE THREAD

**Issue by pelos** [WeakAuras/WeakAuras2#1992]
I don't know if we added to the templates the chaos strike for demon hunters, I would assume that would be under abilities.
thanks.

**Comment by InfusOnWoW** [comment]
There's nothing to track about that ability. It has no cooldown nor does it cost any resources

**Comment by InfusOnWoW** [comment]
I was wrong about it not costing any resources, so I'll add it.
