### ISSUE TITLE
[Idea] Limit amount of shown icons in group / dynamic groups

### ISSUE THREAD

**Issue by Kittiez** [WeakAuras/WeakAuras2#200]
I like making groups an dynamic groups, but some of them i only want to show few icons in (example quickest off cd), but it doesn't seem to be possible to limit groups to 3-4 only, so far. Is it possible to have that implemented in the future.

**Comment by anaseskyrider** [comment]
Is this a correct rewording of your idea?: add a sorting and limiting feature for WAs in dynamic groups (primarily to be used for icons)?

**Comment by InfusOnWoW** [comment]
That's a duplicate of https://www.wowace.com/projects/weakauras-2/issues/857
