### ISSUE TITLE
doesn't work!

### ISSUE THREAD

**Issue by Ezbeincheezy** [WeakAuras/WeakAuras2#2002]
HELLO, i just bought a fire mage script and have followed the instructions per the video, but nothing happens, am I supposed to have a toggle button or what? please help!

**Comment by Stanzilla** [comment]
Instructions unclear, set barn on fire instead.

**Comment by emptyrivers** [comment]
In a more serious tone, we don't sell anything so I don't know what you bought. And we can't help if you don't tell us what it is you have. Finally, our [discord server](https://discord.gg/wa2) is more appropriate for help using WeakAuras.
