### ISSUE TITLE
Add another type of shake animation

### ISSUE THREAD

**Issue by d87** [WeakAuras/WeakAuras2#2004]
Suggestion to add this function to default list of translation animation types:

```lua
function(progress, startX, startY, deltaX, deltaY)
    local easeMul = sin(progress*90)
    local amX = deltaX * easeMul
    local amY = deltaY * easeMul
    local moveX = random(-amX, amX)
    local moveY = random(-amY, amY)
    return startX + moveX, startY + moveY
end
```

It's dumb but pretty effective

**Comment by InfusOnWoW** [comment]
If you do a pull request (which shouldn't be too hard) and show a few videos/gifs how it looks like, that would probably raise the chances by a good amount.

**Comment by d87** [comment]
![](https://i.imgur.com/phpRjt4.gif)

PR is too hard

**Comment by InfusOnWoW** [comment]
I don't like that it randomly jumps around and thus depends on frame rate.

The idea of having a eased in random shake is imho something that has merit.

**Comment by d87** [comment]
Pre-generated array of 0-1 offsets then. That would also solve the issue of nearby icons playing animation synchronously without overlapping.
