### ISSUE TITLE
DynamicGroup Error

### ISSUE THREAD

**Issue by gaveer** [WeakAuras/WeakAuras2#2008]
## Describe the bug

**Do you have an error log of what happened?**
Yes

### To Reproduce
Type /wa and the game hangd for like 20 sec

**Screenshots**
No screenshot

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.16.3+5-g0361513

**Are you on World of Warcraft Classic or Retail?**
- [ * ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

```
1x WeakAuras\RegionTypes\DynamicGroup.lua:84: script ran too long
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:84: in function `resetterFunc'
[string "@SharedXML\Pools.lua"]:65: in function `Release'
[string "@SharedXML\Pools.lua"]:76: in function `ReleaseAll'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:861: in function `ReloadControlledChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1203: in function `modify'
[string "@WeakAuras\WeakAuras-2.16.6-5-g0361513.lua"]:4455: in function `SetRegion'
[string "@WeakAuras\WeakAuras-2.16.6-5-g0361513.lua"]:4287: in function <WeakAuras\WeakAuras.lua:4259>
[string "@WeakAuras\WeakAuras-2.16.6-5-g0361513.lua"]:4386: in function `Add'
[string "@WeakAurasOptions\WeakAurasOptions-2.16.6-5-g0361513.lua"]:3395: in function <WeakAurasOptions\WeakAurasOptions.lua:3392>
[string "=[C]"]: ?
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
```

**Comment by InfusOnWoW** [comment]
There's a "How to Reproduce" section and a "attach your settings section", which you ignored and is vital information.-

**Comment by InfusOnWoW** [comment]
Ah I saw you actually did write a sentence in the Steps to Reproduce, which I missed because you left the rest in. Sorry about that.

Please add your settings to the ticket, so that we can investigate it.

**Comment by gaveer** [comment]
where do i find the settings ?

**Comment by InfusOnWoW** [comment]
If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the `WeakAuras.lua` file in `World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\`. In case you do, please export the string and paste it below.

**Comment by gaveer** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4239973/WeakAuras.zip)

**Comment by gaveer** [comment]
uploded

**Comment by gaveer** [comment]
Spork's Updated Clickable WA's  i think the issue from it i mark it as never load.

**Comment by gaveer** [comment]
also i report the bug to AceConfig-3.0-3 and they say cuz the script to long

**Comment by mrbuds** [comment]
Try replace the file with this one
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4239997/WeakAuras.zip)
And don't install clickable auras

**Comment by gaveer** [comment]
could you tell me the changes on the file?

**Comment by mrbuds** [comment]
deleted spork's auras

**Comment by InfusOnWoW** [comment]
I'm not going to invest time into debugging clickable auras.

**Comment by gaveer** [comment]
so is the error Reproduce by spork's auras ?

**Comment by InfusOnWoW** [comment]
Clicable auras are the source of many problems, you should never use them.

**Comment by gaveer** [comment]
going to delete them . thanks for the help , i always report issues for addone developers .
