### ISSUE TITLE
Omission from "local class_agnosticize" in WeakAuras.lua?

### ISSUE THREAD

**Issue by mltco78dhs** [WeakAuras/WeakAuras2#201]
What steps will reproduce the problem?  
Open the WeakAuras.lua file and search for "local class_agnosticize"

What is the expected output? What do you see instead?
I would expect to see a table that de-localizes every class.
I see a table that de-localizes every class EXCEPT Demon Hunter.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
This is not a run-time bug that I'm reporting.  I did not have the game open when I found it.

What version of WeakAuras are you using?
From the TOC file:
## Version: 2.4.2
Downloaded by and maintained by the Curse/Twitch desktop application.

Was it working in a previous version? If yes, which was the last good one?
Unknown if this is a recent issue or if it's just that no one added Demon Hunter when the last expansion pack came out.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
This is not a run-time error.  The game was not up when I found it.

Please provide any additional information below.
I was born in a taxi-cab in Evreux, France on the way to the hospital.  It was a rainy October afternoon.  As this was my mother's first pregnancy, she was apprehensive about the process and a little frightened....  Oh, wait, that's probably not what you meant.  Never mind.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`
This hasn't yet cause me any issues other than prompting me to build my own de-localization process.  I was digging around in WA to find out how you folks handled de-localization of Demon Hunter because the the gamepedia entry on UnitClass() is missing that class as well.

In case you do know which aura is problematic, please export the string and paste it below.
Not applicable.  Note:  That's not the aura string.  It's a commentary on the applicability of my pasting an aura string in this location.  Additional note:  This isn't the aura string either.  Dang it, I'm never gonna get out of here.

**Comment by mltco78dhs** [comment]
I apologize if the mild wise-assery offends.  I've been up all night and, hey, if you can't laugh, you might as well not live.

**Comment by Stanzilla** [comment]
The `class_agnosticize` table is only used and needed in the `Modernize()` function that is used to upgrade old auras to current code. Since DHs did not exist back when WA used non-agnostic class names, it is not needed for Demon Hunters.
