### ISSUE TITLE
Bug with 2.16.6-29-g9b72ba6 

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#2016]
## Describe the bug
I expect alternate power bar not showing when not needed
**Do you have an error log of what happened?**
No errors
### To Reproduce
Just simple use of wa

**Which version of WeakAuras are you using?**
Alpha see title

**Are you on World of Warcraft Classic or Retail?**
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
yes, noticed when i Dl latest aplpha

### Additional Info
https://wago.io/Ek2SDKW9G first for number on bar ,but numbers are always on now
 changed into 
https://wago.io/ozJ5qyrK0
now i see  something like black/empty bar (more like  black background for bar )  with 0/0 in it.

**Comment by InfusOnWoW** [comment]
Fixed.
