### ISSUE TITLE
Anchoring an aura to another aura that have a status trigger hide it

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#2017]
## Describe the bug
After loading game with `2.16.6-29-g9b72ba6` (latest alpha when I'm writing that issue), one of my aura stopped showing. I expect my aura to stay the same/display the same same way after updating WeakAuras.

**Do you have an error log of what happened?**
This bug doesn't produce error.

### To Reproduce
1. Create an aura (tested with icon and progress bar)
2. Create a second aura (tested with icon and progress bar)
3. Anchor the second aura to the first
4. Second aura should still be displayed outside of WeakAuras Option
5. Now change the first aura to status
6. Second aura stop being displayed outside of WeakAuras Option

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I didn't try.

**Which version of WeakAuras are you using?**
 `2.16.6-29-g9b72ba6` 

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
It was working on release 2.16.6.

### Additional Info
Exemple of an icon anchored to a progress bar that should be displayed but isn't:
```
!LFvBVjooq4FlOTD)qLAfqbkCFQ8sOWsi0M4YlvNc1jXbmeIdXjuaj43(z7KaukTBVvRwvDNulkzI94jZ8mppt0ZOd01O6AzVktHRkCz2sxoQKXnznGf01MPRzX)JTcdO5ulFIxvIdXNzqjJ4VSIFVw8BoDL0xLxpGTyIVfYVs8w01Q4GxVg6BT9zaH4eGzMOMqheFBXlw3qxBvhBBkkG5gDnOR5yI)9eSlZFvLuasQjlvdVgXp54BpmIslIO0IikTiIYWJNaI5cKpftC1vkM(60m)V8WZYmG9iQirea9dyxW2Kn2fthhDn7YiRCN5JhnI5TOJeSZa)slKrOTnyLhsxRHK891FuM9CXTWqFilMPEihNMw0i)sdnqlqUbASDHxQRnSAznWqnqzvMZc5hQMNdCfZ5AUWzO4Dj2c7aqqNGX7DY9(iHt0UxswMVUq39HwquWhLYKSgXIiT5HqF02NRh64S95EJXbOKfKKCYPR5JgXsorVsJ8jHE8AdEgKNYomJPzXEb5ghg9(srMex27z8RVlXfXdGzqS7NF17QbFU1ZRumali7Ou1RemPQ8IwM5Q8WyJTBQ)sXsfVi1n3LZpVnqdxdmrMuH(uRk9)2S1TuVyfD50aSATfTiGQRKlE(ze7ZQb2Uzuk31pC)2nRlo(2sGNO5g3DX8LLTRP036H7Au09MjLQvh)IrQ2GX(eJhUDgbQRXIpB8OyOKpR4XWjWaOaYhbURZTgLy1QQkjPWQy8WFTRQkYVKx1jZtQhnDfLJmCKyaY3f60nbpNTGabOkktXaeyyaZ)D8c2BINUWhCVdbk6RdPOHMoqkL3aYaNMCJZcznPj49ONESvkVj8iJCZih74M2kDaGoTLLQhD(7AxOEq)P9WwmORsM0X3hb46lAh3rdu4QmPVoFM8fYMhDz68VdPGy)QKGiePs6JS0MyXsWLFe0jIeJJHDT(ysJyASpQtpggYoJq6pPpob6QRL5n9U80VOpVcVDn(HSYh5yMI3LmG7bObL4BiEtR8E8bNKB6eKec2WfiqKrHpvUKvN49wmq0qZpuaiteB5PWO7rg7OZH(Vvo5nK3wikljZsHOii6o0YGOI9Hy)4Y0ocx2jmK9pZnmxZFcAzWq6yOf5L(jOSm7kMHg8NhVQOlp3l(2pXRTyD2e(ByDF86Tp)qi0I3ZZK9E9z)zKS2V6bjr6LzsSVpxgbSfwxGPydhbeyxOevUv40JrgFvlutffj1HIw04ERbhilkw)KqAa2E1(IMpVVcbezhLoksj7S)X7KF8rs1zYYlax)RvaC)VFbqT5Dn(dubylFmcpAmpLNFVcWVbsFEpzfhKRvmzBTAcEPYw8yhzHSAdxYBEput8R8qeVo2zNLXRNdkMA5F7KJI8eVUf6ZCstolPn0e93vHSkS7Okq))(XMxU)Ul14BiM3LI5P2eOcxHOYjf6fhsJ4681XqbXbMmfE8AQ(ZBOwtiZ2ROYZcNys6OdeBzHyTQksD5quOJ34OrD(0J(8s0ebz5Uumg0JZlI9EOuh776WtJ8JvOaWF22n0I3v86L3KQSuJ(3lVDZJPcl03TN)ftZxRFJ5pnq(wV7OYLVBIS)Q5PkSK6TSDF0KVVa8sp24G(B3mzAWzG8UAlRwh(y)sB3Cx1LJ6HmNy(9GBNLVnT6T1k6ErDxcmxJukB30Q1Qz9(E)5RtXcGhlJyJZt8XmL2y59gDuB(uhfqz53oVfVgYRyh8DhjIsFcMTF6xgzY(UkgtLlln6jiGsmig134)pFJZhn(YPglzkc5vMtbgOYRIIu1xyMPJgg6eZ(Ccb20FOal9lKaB6Fr91opcKBYvcFpj2Opg5pVqBHC)ofApG8u8JUwpeCAzgEG(xFzOepuOuW6TJlINjRHPqwn064XbowNyN0tIu3juE4kb1LOl0A348bZNDtxY8CYN3R12ntXLMM9jR773lOxD5gb9YMlfysxQsDaqT)GQ2ZDnkySOiEsdt1UN)JTBGZgbhHguC7g2nR)X8h8ATSejf(CZfnSvoZUeGUUfLPndkAVa3TF37ZvBU83gFdWA5j)4M9sGXkBCOWj0RfADvFQYYUkfwwdm41ADXQghRM8wvujzPQG6QLBlDKgdB1lyHrUS8Mo9)5
```

If you switch the progress bar to aura or some custom that always return true the icon will be correctly displayed again. I only see it happening on some of the status trigger.

**Comment by mrbuds** [comment]
![img](https://i.imgur.com/xwYshGW.png)

**Comment by mrbuds** [comment]
I can reproduce only with the new unit status triggers, not with other status triggers like spell known or item count

**Comment by Vardex** [comment]
Yes I tried with some and only reproduced with health and power but haven't tried them all so didn't put that in my initial issue.

**Comment by InfusOnWoW** [comment]
Fixed
