### ISSUE TITLE
Tells me WeakAuras is now only classic, no retail version I can see on Twitch?

### ISSUE THREAD

**Issue by NewVenari** [WeakAuras/WeakAuras2#2018]
## Describe the bug
Expected to keep playing as normal, but apparently this addon switched to Classic. No Retail versions visible on Twitch

**Do you have an error log of what happened?**"this version of WeakAuras was packaged for World of Warcraft Classic. Please install the Retail version instead.
If you are using hte Tiwtch Client, then please contact the twitch support for further assistance."
### To Reproduce
 type in /wa in game

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

no

Version: 2.16.6.zip

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Whichever one was before this

**Comment by InfusOnWoW** [comment]
Twitch is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing Retail on Classic and vice versa. Ensure that you have got the right version selected but if you do and it still installs the wrong version then you may have to just install manually with the zip.
You can get the latest versions from:
• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
    (see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like https://github.com/AcidWeb/CurseBreaker or https://www.minion.gg/

Most importantly this is a Twitch issue that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is.
