### ISSUE TITLE
Cast trigger: specific unit "randomname" show player casts

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#2020]
## Describe the bug
- new aura
- status > cast > unit = specific = "randomname"
- cast something => show cast

expected: don't show cast

**Comment by Herdrage** [comment]
I was testing it some. It seems to show all casts (target or not) from enemies and friendlies within nameplate range, even without being in combat with the enemy and without being in group for the friendlies. Nameplates have to be enabled. It will also show target casts outside of nameplate ranged. Feels like basically any casts that the client sees.

**Comment by InfusOnWoW** [comment]
Fixed
