### ISSUE TITLE
DH Afenar Fury bar not working with alpha update

### ISSUE THREAD

**Issue by devil81** [WeakAuras/WeakAuras2#2025]
## Describe the bug

If i try to use any alpha update the furry bar no longer change collor anymore , its just blank , if i go back to last release version works fine . 

There is no error to link you guys .  Its not only me with this problem , its everyone that using any of the last alpha version . 

this is afenar weakaura - > https://wago.io/Afenar_DH

https://media.wago.io/screenshots/H1X3b4jzG/5ddf62598e2af50bc2997a8f.gif - this is just the furry bar 

**Do you have an error log of what happened?**

No 

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes  . 2.16.6 

### Additional Info

```
  ERROR HERE
```

**Comment by InfusOnWoW** [comment]
This is the same underlying issue as e.g. #2017, it'll be fixed soon.
