### ISSUE TITLE
[options] %c for "Chat message" action does not show a lua editor

### ISSUE THREAD

**Issue by delroth** [WeakAuras/WeakAuras2#203]
**What steps will reproduce the problem?**

Try to use "%c" in a "Chat message" action (advertised in the hover card as something that should work).

**What is the expected output? What do you see instead?**

The custom lua code editor doesn't show up. I was expecting the same behavior as you get when using %c as the display text for an aura.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

n/a

**What version of WeakAuras are you using?**

2.4.2

**Was it working in a previous version? If yes, which was the last good one?**

Not that I know of.

**Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack).** 

n/a

**Please provide any additional information below.**

This is a minor inconvenience since one can just use a custom action with SendChatMessage to achieve the same thing, but it's still an inconsistency in the UI.

**Comment by emptyrivers** [comment]
I took a look at this myself, and it's not just %c that isn't working properly. the %i option will throw an "SendChatMessage(): Invalid escape code in chat message" error.

**Comment by InfusOnWoW** [comment]
This is now implemented. Enjoy.
