### ISSUE TITLE
[Classic] Mac Aura trigger missing Unit options compared to Windows

### ISSUE THREAD

**Issue by audiosmith** [WeakAuras/WeakAuras2#2036]
When I create an aura trigger on PC with 'Party' and a Mac user imports the addon it does not work. If I try create the same aura trigger on a Mac I do not have the 'Party' option in the 'Unit' drop down, only 'Group' which will not do for me as I am tracking imp buff for my party and don't want to check the rest of the raid. This means the weakaura I am publishing is simply unusable for Mac clients.
Running 2.16.6 on both Mac and PC

**Comment by InfusOnWoW** [comment]
No you aren't running 2.16.6 on both, as there's no "party" unit in any release.

**Comment by audiosmith** [comment]
![Party](https://user-images.githubusercontent.com/9102111/76261468-f449b180-62be-11ea-999c-bf22bc579c5f.png)

**Comment by Vardex** [comment]
That not 2.16.6 but an alpha version.
