### ISSUE TITLE
Condition "Destination Unit" doesnt work on classic

### ISSUE THREAD

**Issue by Lupe4js** [WeakAuras/WeakAuras2#2041]
When using the condition "Destination Unit" = player or != player, the condition is never true.

![image](https://user-images.githubusercontent.com/40595781/76627527-79d99580-653b-11ea-9264-435170dd12da.png)

WA v2.16.6
wow Classic

**Comment by mrbuds** [comment]
Can you give the aura you use to test this and step by step how to reproduce ?

**Comment by Lupe4js** [comment]
Project was to whisper the innervage target ("Ïnnervate on you!"), but I had to add a condition to not send a whisper to myself when using innervate on me.

trigger : Event > Combatlog > Successfull cast https://cdn.discordapp.com/attachments/218087027042811905/688002846670716993/unknown.png

action: Announce in /group /raid that innervate was used
https://cdn.discordapp.com/attachments/218087027042811905/688002945903624253/unknown.png

condition: check if innerv target is someone different from player and whisper him
https://cdn.discordapp.com/attachments/218087027042811905/688003046336495619/unknown.png

WA string:
[innervate_WA.txt](https://github.com/WeakAuras/WeakAuras2/files/4330170/innervate_WA.txt)

**Comment by Lupe4js** [comment]
I use this workaround :

```lua
if aura_env.state.destName ~= GetUnitName("player") then
    SendChatMessage("> Innervate on you!", "WHISPER", nil, aura_env.state.destName)
end
```
