### ISSUE TITLE
Classic: Load option for specific encounters using ENCOUNTER_START and ENCOUNTER_END

### ISSUE THREAD

**Issue by EmElw** [WeakAuras/WeakAuras2#2044]
**Is your feature request related to a problem? Please describe.**
Makes it pretty clean to make boss-specific auras.

**Describe the solution you'd like**
A checkbox and a name, similar to zone name load 

**Additional context**
It is not entirely certain that these events are going to be around forever in classic to my knowledge.

**Comment by InfusOnWoW** [comment]
As far as I know that event does not carry any information on classic which allows detecting which encounter started.

**Comment by EmElw** [comment]
it does, contains the name, can upload a few pictures of me tracking it if you want
