### ISSUE TITLE
Duration Timer

### ISSUE THREAD

**Issue by whyttedragun** [WeakAuras/WeakAuras2#2046]
Could you add the ability for a duration timer?  I mean for items that will disappear or change after a certain time, like the Mysterious Egg from Oracles rep in Sholazar or the items you buy from the murlocs in Nazjatar.  Item CD doesn't seem to work.

**Comment by InfusOnWoW** [comment]
I think that's too niche for WeakAuras.

And I'm not even sure what the api is to get those timers.
