### ISSUE TITLE
auraData.stacks is nil

### ISSUE THREAD

**Issue by saenic** [WeakAuras/WeakAuras2#2049]
## Describe the bug
Error popup when casting some spells (e.g. Frostnova Cone of Cold) saying that BuffTrigger2.lua:1016 `auraData.stacks` is nil

**Which version of WeakAuras are you using?**
 2.16.6-49-g5236c74-classic

**Are you on World of Warcraft Classic or Retail?**
- [x] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
It was working a week ago or so.

### Additional Info
I fixed it currently by changing
`stackCount = stackCount + auraData.stacks`
into
`totalStacks = totalStacks + (auraData.stacks or 0)`
everywhere in BuffTrigger2.lua

**Comment by InfusOnWoW** [comment]
I need the actual aura that shows the problem

**Comment by saenic** [comment]
It is just a variant of this https://wago.io/ieUt1vGkT

**Comment by InfusOnWoW** [comment]
I can't reproduce the issue with that aura.

Can you export the actual aura that shows the problem?

**Comment by mrbuds** [comment]
same

**Comment by mrbuds** [comment]
Report from @ThisisJazzy on Discord having same issue, error doesn't show which aura does it
![img](https://i.imgur.com/kyK0y50.png)

**Comment by Thisisjazzy** [comment]
> Report from @ThisisJazzy on Discord having same issue, error doesn't show which aura does it
> ![img](https://camo.githubusercontent.com/6350ceac5c767c01adbda07222ec175a2c8cb7e5/68747470733a2f2f692e696d6775722e636f6d2f6b794b307935302e706e67)
> 
> Happen on retail with version 2.16.6-65-g79e6fee

Using retail and it happens every now and then. Sometimes I can play in a dungeon for half an hour before it shows up and sometimes it is after just a couple of trash packs.

**Comment by Thisisjazzy** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4409636/WeakAuras.zip)

**Comment by mrbuds** [comment]
Thisisjazzy reported only playing Hunter these days both beast mastery & survival.

Auras with buff trigger and %s or %stacks used:

Mongoose Bite : player buff, aura found, "%stacks"
Wildfire Bomb :  target debuff, aura found, "%stacks"
Trick Shots : player, buff, show always, "%s"
Barbed Shot : pet, buff, show always, "%s"
Bloodseeker : player buff, aura found, "%s"
Sniper Shot - Active : player, buff, aura found, "%s"
Sniper Shot : player, buff, aura missing, "%s"
Steady Focus 2 : player, buff, show always, "%s"
Frenzy - Buff 2 : pet, buff, aura found, "%s"

**Comment by mrbuds** [comment]
Can reproduce with this aura
```
!nA16pkUnq8)DA)WXYchTRQuReWY(OInzpCO66xcysmj(wJDQTdSSFG)27mtsGaCNALqH4zgpV(nps8TXrXmzCWT9hCx)phZCXS7fBJzBIzP4pG77HRx7e(4GUXS9TENRtYn2xnsTpMnEsq0KzXSeJrLA2Pz7KfI4raHsN3Sjs8UFErk3lIzL1)3i6K0mr8kWlsmA8gERmltyDGTdi3RMa(APt8c3NKViXucMfKMxA5A(grT4S(9hmigCiqXHA1EuKmHwyLjSCZUqneIW)dv747HyTulbz3uQ8s4VwAMbQkfuTxcofEWviuQaWqGvU7x)LbqcWvUsSvO9VAfRLVhZyVoz6uWD3dro5x9ojdRCnjZIXdzrlyrdNfDMbdleGXm2y2F87uyUWv5UJQorok8oPmiDxN7oS8vRjZkCUdl)jg6I)mgu1sXl9MyMvWvSJEp7bRq8HuNDyzKLxuBRJShvhPpNIjupXUHbkjFLZyx9Ij9iLZZUaXg0aUCQyfe3ruc5PHZE5H5tjDQBbPUVdSCDY2tQt6(wPoXl3IjyLcEqhIQ0g5vbF6wuAguvkSAU6VGkjedd6Dxm7nHOyiO8e)mezPOvOwFrnCQWLaNG8MxKEy5Q9hwoT8DFUXD4pZ9(c3VDZn72TRJFNeWVo(T3OQyhZ22yT7iOFMido1QsgAdaGLdq3xB1jvvXaYJ8RLQ61dlRpMyugBLEWF9ON9PNFgF2CT1gmsEWk)4WYVuYtHIkoG0NB7XTuwxszDjL19cLvj9F32tjYNszdNhfwtDR0jxPOYIJEsfYhopA6ZbtQPF2yJNdcMmBXOWOOWxM98Jpf1mw5kJ(nyoIC9(tOK14b8jIstbHO6RU5xV8MOJWKFG1s9HqdcxWkzkZoOt4Fkf6K9GSD6nOIyDz9JQM00Qk6vHYWXSCPwutkxM8Mg69W0grPTxNPopr)dqnumwcxjOPx4PVBLb5Ae7PcDMphKU2gtb)XrfC4PrgBQaDAQHjxiZYbn1hcoLHtJZ9GT0Ekjun3lQs2k6uhjmDG8NpFse8WOkbtuCNRLCSNMxHinY2qaYKZcFC(KMlUg7wHMJlTCQeMnMau2FfRJdNEtdt7qSWYtexjwX2ItU)zCax0AklUIU1OUwn4KH2ebezeIAJqqRoiCyL0fxe1h1PxvKqlYWHVq1yyHVEcano0X94sfAFhxl3WBsiop3sEFZsNf1qVaugmlUUsqBGIpCJfxsxRIAbSaq4)X3THpxvKZFTu5iDSwQLU8)32er()7Y5ki21oKABkcrK(MeoyN1YSk6FymBWgX(9p9Pby399shhMRKsPmCHgoGXKCAsB3(DHwbz6LR2oS8thwoSzBbnB4blStPcKyJNnzsa4Aij4tmG5Kuh4ozk2DHDmu6IiwIAFSzq5Ztt7LnPeJc0biCS0clIoUxGNz6in3m6TVyYULX2CdUjqSbKg(mIo96qrNov2QSOjAP1rEyMY(7B(YdSpMTf7(6HP34)9
```
- disable nameplates
- /reload
- launch a freezing trap to a target dummy, but don't select it

**Comment by Thisisjazzy** [comment]
So the issue is fixed in the next update or?

Thanks!!
