### ISSUE TITLE
Latest Update force loading Classic Weakaura 2 

### ISSUE THREAD

**Issue by minkeemomo** [WeakAuras/WeakAuras2#2054]
## Describe the bug

Updated from Twich APP as usual and tried to load Weakaura for WoW but it keep saying that I have a classic version. I deleted Addon and selected "non=Classic version" but it force twich to download the latest version which is 5236c74-classic zip.

**Do you have an error log of what happened?**

When I log on wow and try to load weakaura it says "you have a classic version" so add on doesn't show up at all.
### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

```
  ERROR HERE
```

**Comment by mrbuds** [comment]
This isn't a weakauras issue, i'll copy our bot answer and close it.

> Twitch is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing Retail on Classic and vice versa. Ensure that you have got the right version selected but if you do and it still installs the wrong version then you may have to just install manually with the zip.
> You can get the latest versions from:
> • CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
>     (see the Recent Files section, bottom right, for both versions)
> • WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
>     (See C and R on the right)
> 
> To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like https://github.com/AcidWeb/CurseBreaker or https://www.minion.gg/
> 
> Most importantly this is a Twitch issue that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is.
