### ISSUE TITLE
Swapping Gear does not trigger an update for Item Set Equipped

### ISSUE THREAD

**Issue by Medry** [WeakAuras/WeakAuras2#2056]
## Describe the bug
Aura made to track when different set bonus's are active does not update when gear is swapped until UI is reloaded.
Swapping Gear does not trigger an update for Item Set Equipped

### To Reproduce
Any status, Item Set Equipped with operator = 6 for example
Swap off 6 set, aura will not deactivate even though operator =/= 6

**Which version of WeakAuras are you using?**
2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [x] Classic

**Comment by mrbuds** [comment]
Tested with Tier 2 Priest (set id = 202) and equipped >= 5, it un-trigger when i wear only 4 parts

**Comment by mrbuds** [comment]
As the tooltip says you can use https://classic.wowhead.com/item-sets to find item set ids

**Comment by Medry** [comment]
It was not the incorrect set ID.
I clipped a video from my stream showing the exact issue. The Aura has no issue loading, but it will not unload for me
https://clips.twitch.tv/ThoughtfulRockyPancakePrimeMe

**Comment by InfusOnWoW** [comment]
We can reopen this, which I'll do and Buds will have another look at the problem.

**Comment by mrbuds** [comment]
I can't reproduce issue, tested with blue pvp set and T2.
Can you try install https://mods.curse.com/addons/wow/BugSack & https://mods.curse.com/addons/wow/bug-grabber to check if you have Lua errors ? I don't see green icon on your twitch clip.
Also can you try with all others addons disable, only keep weakauras & bugsack/buggrabber

**Comment by InfusOnWoW** [comment]
No response from reporter.

**Comment by Medry** [comment]
only 5 days to respond? guess it's staying bugged

**Comment by emptyrivers** [comment]
If we can’t reproduce a bug, then yes it won’t get fixed. If you are still consistently affected by this issue, then follow @mrbuds’ instructions and report back your findings, and we will take another look.
