### ISSUE TITLE
Support for (de)buff augmented by existing buffs.

### ISSUE THREAD

**Issue by celdorwow** [WeakAuras/WeakAuras2#2059]
**Is your feature request related to a problem? Please describe.**
There are situations where debuffs on targets are influence by a player's buffs, e.g. the Druid Feral's main damage source is a number of debuffs or DoTs. It turns out many DoTs / debuffs are supposed to be applied while buffs are on to significantly increase the damage: e.g. Rake with Bloodtallon and Incarnation. which are massive damage increase.
In current state it is not possible to create an aura which would reflect in which conditions a debuff was applied on a target and it should reflect each target I tab to. The difficulty is a debuff remains affected or augmented for its remaining duration even though a buff may already expired unless a player re-apply a debuff on the same target under different conditions.

**Describe the solution you'd like**
An extra field with a list of buff names or buff Ids which affect current an aura.

**Describe alternatives you've considered**
Currently, every auras which track snapshots use Custom Triggers with a manual approach such storing targets in a tables and remove them when a debuff expires.

**Additional context**

**Comment by InfusOnWoW** [comment]
That's too fringe to be handled by the default buff trigger.
