### ISSUE TITLE
WeakAuras2 not loading or working with most recent build (2.16.6-54)

### ISSUE THREAD

**Issue by KCCatisthebest** [WeakAuras/WeakAuras2#2061]
## Describe the bug
Updated WeakAuras2 to most recent build (on March 23, 2020) and none of my WeakAuras are loading for any of my characters. Inputting /wa will not bring up the WeakAuras menu, clicking on the minimap icon does not bring up the menu.

**Do you have an error log of what happened?**
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:4401: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4401: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4365: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4268>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4395: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3928: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3935: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1606: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1578>

Time: Mon Mar 23 14:42:16 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:4401: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4401: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4365: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4268>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4395: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3928: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3935: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1606: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1578>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1734: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1685>

Locals: <none>
### To Reproduce
Updated the addon via Twitch, then would not work upon entering game.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, did not solve issue.

**Which version of WeakAuras are you using?**
2.16.6-54
**Are you on World of Warcraft Classic or Retail?**
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes, 

2.16.6-53

**Comment by didallwrong** [comment]
I am getting the same bug; i even tried installing  it:[

**Comment by Zabulonn** [comment]
I am getting the same issue. Anyone know how to fix this? Rolling it back doesn't work for me.

**Comment by Brendawise** [comment]
Same issue. I'm very annoyed

**Comment by Sniffu** [comment]
Same for me, guess i cant play wow until (and if) i can get this fixed

**Comment by Tangerinus** [comment]
It seems they seriously broke something, if you delete all weakaura data from WTF folder (so all your saved auras) it loads properly but it doesnt really helps a lot :/

**Comment by mrbuds** [comment]
It's fixed on alpha.

**Comment by Brendawise** [comment]
It's not fixed.

**Comment by Brendawise** [comment]
Please don't close a thread ffs

**Comment by Tangerinus** [comment]
Yep nothing works, rip raid night for me

**Comment by emptyrivers** [comment]
Hi, we're sorry that you're having an issue, but this is not a forum thread. As best as we can tell, the issue described in the original post is now resolved in the latest alpha version. Please note that it can sometimes take some time for the CurseForge CDN to update, so you may not see an update to WeakAuras just yet. Please be patient.

If you continue to have additional problems, then feel free to open a new ticket and describe the issues that you are having

**Comment by InfusOnWoW** [comment]
Also, if you are annoyed that alphas sometimes have bugs, then DO NOT USE ALPHAS.

If you are using a alpha, you have opted into sometimes having issues.
