### ISSUE TITLE
Alpha release this morning

### ISSUE THREAD

**Issue by didallwrong** [WeakAuras/WeakAuras2#2063]
## Describe the bug
 I logged inot the game; got an error;, tried to do /wa and click the icon and the addon did not open/auras not displaying.

**Do you have an error log of what happened?** Message: Interface\AddOns\WeakAuras\Locales\zhTW.lua:8: unexpected symbol near '<'
Time: Mon Mar 23 15:34:33 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Locales\zhTW.lua:8: unexpected symbol near '<'

Locals: 

### To Reproduce

1. Go to '...' download alpha release this morning
2. Click on '....' log into the game

**Screenshots**
 https://cdn.discordapp.com/attachments/517622768741777410/691732757738422272/WoWScrnShot_032320_153442.jpg

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** 
 yes I did

**Which version of WeakAuras are you using?** 2.16.6-54-g43a63f5

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ ] Retail
Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

```
  ERROR HERE
```

Message: Interface\AddOns\WeakAuras\Locales\zhTW.lua:8: unexpected symbol near '<'
Time: Mon Mar 23 15:34:33 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Locales\zhTW.lua:8: unexpected symbol near '<'

**Comment by Brendawise** [comment]
I have trued every fix possible, it is not working. Previous bug report was closed when it's still a thing.

**Comment by emptyrivers** [comment]
@Brendawise this appears to be a separate issue to the one reported here, please do not spam. Open a new issue if, with the new update (which may not yet be out) has not resolved your issue.

**Comment by InfusOnWoW** [comment]
We believe to have this fixed.
