### ISSUE TITLE
Better Preview and Preview Options

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#2068]
**Is your feature request related to a problem? Please describe.**
It's not really a problem though having the preview be some static timer locks it to only being able to show certain things. Recently there was a user in the discord who had a condition to set their auras to 0 alpha if they were on CD and they couldn't see much of anything. If I had some conditions for some random value at like 100 I wouldn't be able to test it in the options menu. 

**Describe the solution you'd like**
Idealy it would be really cool to see some kind of menu that one could open to adjust the preview, make it static, set durations etc. 

**Describe alternatives you've considered**
The only alternative would be something like setting the auras to 50% if they're below that, like what's done with textures. Though that would only solve that specific issue.

**Comment by InfusOnWoW** [comment]
What I did is to improve the current solution that prevents auras from being invisible.

A config mode is almost impossible since there are lots of things in the state that affect the display.
