### ISSUE TITLE
Event timers Ragnaros/Vaelstrazs

### ISSUE THREAD

**Issue by Rowny12** [WeakAuras/WeakAuras2#2069]
Hey. I talked with some of you at discord.
About EVENT timer's issue. (Rag/Vaelstrazs)

Nowdays i have to switch BigWigs for dbm to see when
event timer's for Vaelstrazs / Ragnaros fight.

I would like 1 bar with timer to count down from etc. 40-0.
Today I have to use DBM to get that. 

Best Regards Ronny

**Comment by mrbuds** [comment]
Sorry this is not a place for requesting auras, if you miss a function in DBM you can try their discord at <https://discord.gg/deadlybossmods> or if it's for Bigwigs try <https://discord.gg/jGveg85>
