### ISSUE TITLE
weak aura command error

### ISSUE THREAD

**Issue by randomuserx123** [WeakAuras/WeakAuras2#2072]
hi
i am no coder just using this addon wanted to tell that the command you linked in the closed topic
`/run for id, data in pairs(WeakAurasSaved.displays) do if not data.regionType then WeakAurasSaved.displays[id] = nil end end C_UI.Reload()`

makes my weak auras stack in one place and they look like this now.
![FV1gVfy](https://user-images.githubusercontent.com/62614795/77457232-affcfc00-6dfc-11ea-9a47-7dab6c2077ff.jpg)

weak aura grps are gone
i use the weak aura companion i got the backup but like stuff like grps are removed, some other existing weak auras are mixed together in other grps. its weired.

hope you fix this soon, since tommorrow i will need this for raiding
thx alot for the great work

**Comment by emptyrivers** [comment]
If you had read the post more closely, you would notice that if you needed to run this command, then some of your data would be lost. This is unfortunate, but unavoidable, and there is nothing that we can do to fix it. If you have a backup, then restoring from that backup would be the preferred solution.
