### ISSUE TITLE
WA Text Cloning Bug

### ISSUE THREAD

**Issue by Zero42** [WeakAuras/WeakAuras2#2073]
## Describe the bug
I have an interrupt tracker WA that creates a bar when each unique member of the party uses their interrupt, and tracks everyone's CD. When on my mage it works exactly as intended, someone uses the interrupt, bar appears and tracks. On my prot paladin I started noticing that it would sometimes get polluted with text. I disabled every addon except WA, and deleted every WA instead of my interrupt tracker and one of the bar WAs my tank had that my mage didn't, that was causing the bug to happen.

**Do you have an error log of what happened?**
There were no errors produced by this, at least none that Bugsack caught.

### To Reproduce
Specifically, it works on my prot paladin tank with both of the aforementioned WAs installed, in a dungeon eventually after someone interrupts. If only the Interrupt WA is active, or as long as the tank bar WA is disabled (in the case of my mage), the error will never occur.
Specific steps would be: Log on paladin tank, import both WAs, queue for a dungeon, get people to use their interrupts. Notice the text that shouldn't be there, but is.

**Screenshots**
![Mage Interrupt](https://user-images.githubusercontent.com/3150056/77619766-ec1c8380-6f06-11ea-9d16-885a9818c414.jpg)
![Tank Interrupt](https://user-images.githubusercontent.com/3150056/77619779-f2126480-6f06-11ea-93de-b0fd00d5b57d.jpg)
![Tank Interrupt 2](https://user-images.githubusercontent.com/3150056/77619787-f50d5500-6f06-11ea-99f6-9356d19ea7a7.jpg)
YouTube documentation of the bug happening: https://youtu.be/oyYdMC7qpuU
https://youtu.be/hS4CTfsZcLk

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, as seen in video documentation above I tried having literally only WA enabled, and specifically, literally only the 2 WAs in question as my only WAs, deleted the rest.

**Which version of WeakAuras are you using?**
2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
The bug only occurs on my prot paladin tank, but not on my mage (Or only when said WAs are both active, to be more specific)

### Additional Info
WAs in question
M+ Interrupt Tracker: https://wago.io/6HLbBELfC
Tank Bars 2: https://wago.io/ffsMMpKCs (Tank Azerite Minor, specifically, will get the job done in producing the bug)

**Comment by mrbuds** [comment]
What you describe looks like pollution from another aura, can you include your savedvariable ? It was asked on the issue template.

**Comment by mrbuds** [comment]
You can ignore my last comment, i have an idea of what's going on.

- Your 2 auras doesn't seem to do frame pollution (good point), and i don't see global variables
- "Mythic+ Interrupt Tracker v3" aura has 2 text subregions showing a variable undefined in the trigger.

%coloredProgress
%coloredName

So my guess is there is a global or uncleaned variable use in WeakAuras's text substitution function

**Comment by mrbuds** [comment]
So, your interrupt tracker have an hidden custom text function, doing insane unsupported stuff

This is an old version of Nnooggies's https://wago.io/SkjHi61Bz for which he was jailed by Weakauras' discord police team.

Please update or use something else.

**Comment by mrbuds** [comment]
It still show a bug in WeakAuras, i made a minimal example

Import this
```
!LJvBZPnoq4)l9MBMRFi3G5Tq)yGaxih1KImnT30XyHLauJXIkBtc5d(3(TRKn2eiPKCZ1jD600u71sR2xE2DFuDTCDCjrUKZ5RDjlDjm8hq0CL8wq6WRTDjtLkgx1M6Fdtjx5sAhiU)EQIL65iLbXcq0DdNnlIh72Rz9k1A0SQvZQnTAvRzl3zNuVUlzt(3RFQf(t96VRvTwvAvb)Etxcn0FHuDLueg7s6012P7O8ZTJmqQatY2Y1UIRDv9VRP)DDuiSbWwjRO(C8vc1pwidJ0(vmvfdpalzMiueTW8m8Ork8CSsmFoxfzoaNTcWhz8PjZM5Szf3LCr3bx1B8a476xPjkAv4awXdc6ZIm6nkzkFnpmMa7sCNlzsNZiotioNncuwcEOKvb0nGYjH0L8SDP3cCaCAq8IcLCLIRvc5QUdgGRljSW0IngVVmizzyHRROmrseeJQubdPILumuuosqyGHJcNy8JiUVmeS)m3kugYrfVKkcp(vVn2ECRh2bnqmpSirdwN2XGCk6)J4ZZYGWsdKunGmjIpXpGgf5ovh39rHlta4xEQ081hknsCp)HcbXtZqZLrxwA0LLgDzPrxv(ZgAZvhk56t2Ngyc2GRntm3yKgKk(DZtDzZb)L8TeQIN61ljii176fcqfeL25mGk2gahi8HATKv5BLG2RnITKqgZeZaaESjvIrO5kbZS)rNRndi8fg3dW9GNqgD259htWqKgvunxVzfGGxrcelbSODdiVi9xdGFTMBvPgcBeqhahH)n84uVFRALtRbHEu2L3V(MpSAjR1)CkKXva(fkvOXutnNU8Thk1yzKoJ621grabZYQQDgEvUT0puBkwgF5Abda(O5qv(d4HZX3Q1eHWjXGAhUkUaoGakrP3byXaT7mfRRJ5QqAWhZDPQT0BzBTnetu3KDCwvYE3ey(Ko0M3MYUYJ0ssVJrLZg7i59sg48Nn2ziynGPIw1t1HXuxK1b4rAFmUtNUesrTLlPX2T0rUCkfsudKZFyhMd3AA3UkWwYuuSyjNTtBjt9gG(6ZCBF4EHhOPKU77AUJrOoCyFceQJnXJj(pz5MLP78(zXY4OTthOQ9lE3B0aJhrJXiNP6TiH)5972KLE22GhoHjWFb1aQg)c)U4jrlOm5TFkhOyLVbqt43ZwL5XFpjKbX7qm0QfFeUVEDZKON2tjUp17djugwObtB31goIbJLw9NZT4tSYLxetniwT01IiXuOfx7sMIjTBRBfPfUtTrFB7UJMmOBpN8IMpxQmsV(VMeflMTPi5PBOXD0rj7H2DZ35NE4oXJ30s0QkMiQ9Yse()cLjg1)VU4hqQaw(cUy(cm23Oyo9)9rZ6I02b8qww70Zpx3o6mgA7CgN9E6DBRM789tKhymYUQtOBuxEYCw5)RBwu3vkdP7UgjW4vw(xhDW0AIce2h7QodOe8LouaaeoVnv9LX9pP4Tti4g0rljI507)ISmCTmqGwx58)ZxJGX4Wyj7UFeXt3lLllMmQNaEywg(WrN6fL47ZJIs9WZ9e9ehKF4QfgMfhntJBnJ11uF1ewQ(2gJdIFxY3AqXHkOfONbuM3MujGXFzJvVy4O()ZqBNZgSpnJN3LkqYLiPUq2t3zWqVmF8Y3LDYHOdbqy5stX7SKqTv(hVn9YupZFuCiLfM69MvYGGe8RVj9sOY6fr1P4WgVIHtujjz)7ZZHFskrrlG(Pikis34BNBB9u3V6OUg1dyfvMUZoKNETZ2P3P1QFAL6TGQPwnp1Qzn4A0nAw6eE1WaA1pfZB3Fg4)JCF2Fy6JnXTGbWlN5t4VcjGNjLNxygO(lK75ppuopy8opgm9hB8FpiXRbkNfet0xVV9ZHj5bPqSL2qzYeFxUD5C0kZL5y4RPjgn(VJ)ARLnhSjIDKS1oenVY8ToAsA4XJbKupC(AzoFPE3kIxK6bdTvB06l1ZW3i1ZuhDSS9lr17Lsb(OPf(O)N)C4RnuIa)JrYV01goUvxCTHJA9za(1qWQEvmE5(Vp
```
Casting spells/buffs will show pollution in the other aura on text "%cundefined"
![img](https://i.imgur.com/9EiJEGv.png)
