### ISSUE TITLE
Models not appearing when I relog or /reload

### ISSUE THREAD

**Issue by Daugen** [WeakAuras/WeakAuras2#2075]
## Describe the bug

Hi, I put some models on my WA icons and bars and it all works until I relog or /reload. The models will not load until I go to /wa and double click on them individually. The actual auras work fine though but it's just the models that aren't appearing

**Do you have an error log of what happened?**
Bugsack isn't reporting any

**Screenshots**

[![Screenshot from Gyazo](https://gyazo.com/f6ba11c9bbf303c940636ead9c9101c1/raw)](https://gyazo.com/f6ba11c9bbf303c940636ead9c9101c1) (gif)
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes and it did not fix the issue.
**Which version of WeakAuras are you using?**

v2.16.6
**Are you on World of Warcraft Classic or Retail?**
- Retail

### Additional Info
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4397090/WeakAuras.zip)
-->

```
  ERROR HERE


```

**Comment by mrbuds** [comment]
please included your SV as asked in the template

**Comment by InfusOnWoW** [comment]
The Icons don't yet work, I'm still invistigating.
