### ISSUE TITLE
WA classic not showing cooldown properly

### ISSUE THREAD

**Issue by sterob** [WeakAuras/WeakAuras2#2078]
I made WA to track mooncloth and arcanite cooldown. Yesterday it was showing everything properly.  Then today when i log back it no longer show the cooldown text or the swipe. I don't recall making any change to setting or addons at all. 

Disabling OmniCC and re-enable "Show Number for Cooldowns" in Interface Option> ActionBars shows the number again. However it shows the wrong number 

https://i.imgur.com/laXXamn.jpg

Changing display text to %p shows number like this

https://i.imgur.com/KumJ5XI.jpg

My WA classic version is 2.16.6

 `!nwv3YPUnq4NMot7fjJny(5CjqnNtMjXqroTP9cbcBzB1ySOsYqixWZE3vY2qsM2HzymsR29t7pF7kQpnMse0i)(bbd(gLOPKE37p8(HuYokjf)bkKilLkyrKV9xp73(2Vb4xdLCArwMMBOZVBqqp)((J9hfe4nEKxan7UGakHvLuivlLIkq7zHrXHRqGLLPYJvKJI9C60lcctZ50TGvjgHSsJoH2WugybyUOs0SkdwQlSRHDgLipNR0oxnUtGBjl51lxaaIHVlITJtJ8OKAnF9oMjPGNUQUY6kOOCEfxjsifYJlQqHFuard)pP8i7eK301B5h4vMLkEM4nkHSm8XhDWGQLNKIbukFBDww8jiCj)i8XLZFg0Xy3cbOPgaQgJoY(s2jWZHDwuHurTr2a3EEz5mznifqScIbTlB0O5SMy88MLkzUIR1N38Ze0OFXba)niV6GXMbGatXzLKobr(J8hp6QBRvn7MhsBUp9xmOnjqGGetcRNnHeVMepzfucsRvmSCsj(oOD1KMCDx9ykcneC)p1U)7YGLhGSMd8yhapjtb)7oFphZXWvvSYFhyjONe1dy6VY57NaXsIzf6F24KxM9jUAkxd1hicSetiqxXZB4MnKn(BqsTGbU4lnDdi1QP4wVfpVrl3YFAFZ2BO)YQxMeDO5kX7N38B1SuWzyN3e)X7E2vG5zbZZcM3NaZP9FETNAfFjYN8C8cGzibEjp26XrlIcVYxC04fph)4dDY)qF(drrHRwpDrC8INw9W3)rC7CGVCT)DT2iYoDjD3DjeX7i)QxRPV8ztpi0ITLoEdeUWDSvQs5Q1ARL9UQe4oOtHBiV3Oz7DSTtchNqri)tntXpVzEDz55n)rbqI70q25NwszbxKxaB7pGskLm7GvdRe7yXPBIQCa)O(4K36sJaDlyZuNXjLmT(k9ipn57Hx00Qd2e50d7Nzj8UM0e0YVORT791kSHA6xMl0j)QDDn5yE9tiAWriy)GJtisW28mf0pJDVggMoHcOyNBcWvZZBQovsySB3iI1nLmoGtk2vt2Xev3U2DVlCB6dwCuKAkCvhivedJAmI9x)Ke2b8RcndOb2j525XW5gzYH2Pj((9Hh8ic4HZjQeiCna3iwXQ07QrMX7s5olXLvUVOnNGK65yMYL6iZwfggzXhoyX(2harwGSktK3(giERUxQW7BXFnWN8I4L6XjuYBT9ibJhEVNN33gnCWWEdSiKk(aInJuN2uZSdFpaEg8koSK(Vp`

**Comment by InfusOnWoW** [comment]
Please fill in the template that you got on creating a bug report. Specifally this is missing the version number and the auras that are showing the problem.

**Comment by sterob** [comment]
My bad, the WA i am using is 2.16.6 

Is it ok to export the string aura?

**Comment by InfusOnWoW** [comment]
Can you add the output of /dump GetSpellCooldown(18560) after creating Mooncloth?

I suspect that the data that blizzard is returning is simply wrong.

**Comment by sterob** [comment]
Sorry for the delay in reply. Here is what i got 

https://i.imgur.com/jbpRhCg.jpg

**Comment by InfusOnWoW** [comment]
Well that's a nice little bug that World of Warcraft has there.

You don't need to understand this explanation, but for myself and others trying to understand the issue in the future:

The second value is the duration, which is entirely correct. The first value is the cooldown start time, where 0 is the login time. Since you just logged in, and the Mooncloth is on cooldown for roughly 15h already, that's supposed to be -15 * 60 * 60.

But due to a bug in how blizzard handles cooldown timers this overflows.
And thus -15 * 60 * 60 + 2^32 / 1000 ~=~ 4237313,307 from your screenshot.

I think we can fix that.
