### ISSUE TITLE
Tiny issues in UI

### ISSUE THREAD

**Issue by Nightwarden24** [WeakAuras/WeakAuras2#2081]
- The [Preferred Match option](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAurasOptions/BuffTrigger2.lua#L857) isn't hidden in one case (combination of trigger.showClones, trigger.combinePerUnit and trigger.perUnitMode). "trigger.perUnitMode == "unaffected"" isn't taken into account. Look at [that option](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAurasOptions/BuffTrigger2.lua#L868), which works properly.

- These options ([1](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAurasOptions/BuffTrigger2.lua#L285)  and [2](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAurasOptions/BuffTrigger2.lua#L292)) are displayed even when I select a buff as aura type.

- Typo in [name](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAurasOptions/BuffTrigger2.lua#L689). It should be "Class"

- Could you set double width for these options ([1](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAurasOptions/BuffTrigger2.lua#L892) and [2](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAurasOptions/BuffTrigger.lua#L1067))? There are no other options on the line that they are on. So it looks strange, if text doesn't fit in the provided space (I mean translation).

**Comment by InfusOnWoW** [comment]
The debuffClass is intentionally also visible for buffs.

For the unitExists option, I've made it wider for Bufftrigger2, but not for BuffTrigger.lua. Only critical bugs are fixed in that code.
