### ISSUE TITLE
Dynamic Size for regions anchored to Unitframes/Nameplates

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#2083]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [...] i want to anchor a specific texture to Unitframes/Nameplates and need to set the size based on the frame. That's why I need to use diffrent Auras for Group/Raid unitframes just because of the size.

**Describe the solution you'd like**
An option for "dynamic size". 

**Describe alternatives you've considered**
"If condition" for raid/party to change size via condtions (if possible). 
Maybe [4de847b](https://github.com/WeakAuras/WeakAuras2/commit/4de847b3cc4f4b26f55e645489b68553d8f05a4e) can be used for that.

**Additional context**
Sketch of how it may work: `GetSize of the anchor. SetSize to the region.`

**Comment by InfusOnWoW** [comment]
I think that's out of scope for the time being.

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/2878 is a very similar ticket, that asks for this feature in the context of dynamic groups, and thus it's best to merge the tickets.
