### ISSUE TITLE
Weakauras2 update and now its classic edition??

### ISSUE THREAD

**Issue by MadRav3n** [WeakAuras/WeakAuras2#2084]
Updated WA through twitch. It was running perfectly before the update and after the update, WA notifies me and says it is for classic only.

**Comment by emptyrivers** [comment]
Yeah, it's a pretty well known bug with the twitch app. You can install packages manually from the curse website to get around it, but there's nothing we can do to fix their app.

**Comment by MadRav3n** [comment]
got it thanks!
