### ISSUE TITLE
Fix sharing via chat link for some players on CN servers

### ISSUE THREAD

**Issue by nebularg** [WeakAuras/WeakAuras2#2090]
## Describe the bug

CN servers started force enabling the profanity filter cvar in 33941. The fun part is that some server names trigger it, so chat links with the full player name will no longer work for players on affected servers.

Enjoy :p

**Comment by emptyrivers** [comment]
Thanks I hate it

**Comment by InfusOnWoW** [comment]
The poor server's name is: 迦拉克, which is apparently Galakrond.

I'm not yet sure how much work converting that would be. I'll probably try telling Blizzard to be less stupid, but that hasn't worked in the past, so...

**Comment by EKE00372** [comment]
迦拉克隆
克隆 is in banned list

is that possible  simply hide realm name when CN user share their WAs?

**Comment by InfusOnWoW** [comment]
We use the realm name to look up whom to contact, so we need to have something there.

**Comment by InfusOnWoW** [comment]
Any idea on how to check if a name/realm is in the profanity filter? That is without hardcoding the realm name.

**Comment by Stanzilla** [comment]
Impossible without hardcoding, that info is only in the DBCs

**Comment by InfusOnWoW** [comment]
Hmm can we check whcih region we are?

**Comment by InfusOnWoW** [comment]
GetCurrentRegion()

**Comment by InfusOnWoW** [comment]
@EKE00372 can you try the package at https://github.com/WeakAuras/WeakAuras2/pull/2097/checks?check_run_id=579521188 ?

The package is behind the "Artifacts" link in the top right area. I think that should work on 迦拉克隆.

**Comment by EKE00372** [comment]
> @EKE00372 can you try the package at https://github.com/WeakAuras/WeakAuras2/pull/2097/checks?check_run_id=579521188 ?
> 
> The package is behind the "Artifacts" link in the top right area. I think that should work on 迦拉克隆.

I am not am not am not zhCN user, i'll forward this.

**Comment by EKE00372** [comment]
a CN user tried this patch, looks good, seems ok now.
