### ISSUE TITLE
Texture Strat Incorrect Upon Reload

### ISSUE THREAD

**Issue by arabinowe** [WeakAuras/WeakAuras2#2091]
## Describe the bug
I attempted to load an always on custom (my TGA, correct dimensions) texture in the "background" layer of the strata options. The image loads as expected. Upon reloading or launching a new client , the default strata is incorrect by behavior. Only upon launching the addon's GUI does the correct strata apply. Requiring the user to open the GUI often depending on their usage patterns. For me it's rather obnoxious.

**Do you have an error log of what happened?**
No error messages.

### To Reproduce

Create an always on via trigger, texture only aura set to the background strata. Place part of it behind another UI element that is of a 

**Screenshots**

Won't be more helpful than the description above.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but it is not worth it to me to make that compromise as a user. I do use the addon moveanything to alter my the other element the weak aura interacts with.

**Which version of WeakAuras are you using?**
 Version: 2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [X] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Haven't tested.

### Additional Info

```
  ERROR HERE
```

**Comment by emptyrivers** [comment]
Your steps to reproduce stop in the middle of a sentence, which makes it

**Comment by emptyrivers** [comment]
...more seriously, can you please complete your steps to reproduce? This looks quite incomplete:
> Create an always on via trigger, texture only aura set to the background strata. Place part of it behind another UI element that is of a

**Comment by mrbuds** [comment]
> I do use the addon moveanything

Please test with moveanything disabled.

**Comment by arabinowe** [comment]
> 
> 
> Your steps to reproduce stop in the middle of a sentence, which makes it

I'm sorry. I didn't realize it had cut off. I'm doing my best to describe the issue while balancing my own priorities.

It should read:

Create an always on via trigger, texture only aura set to the background strata. Place part of it behind another UI element that is of a higher priority (toward foreground) strata. The background layer will, in this case at least, appear in front of the foreground layer until the WA GUI is opened via the /wa command.

Here are screenshots:

https://imgur.com/a/g5Kyre9

**Comment by InfusOnWoW** [comment]
Please try with all other addons disabled, especially MoveAnything is known to be broken.

**Comment by InfusOnWoW** [comment]
We are still waiting for that information. I'll close this until you try without MoveAnything.
