### ISSUE TITLE
Default Form trigger generates LUA error

### ISSUE THREAD

**Issue by Aqua-1994** [WeakAuras/WeakAuras2#2094]
**Bug Description:**
On Classic wow,
On the Default-build in Trigger: Status: Stance/Form/aura: Form (multiple) [Form0/1/3] gives lua error on form switching from 0 to 1, 0 to 3 and 1 to 3

ingame look at the configuration:
![afbeelding](https://user-images.githubusercontent.com/42642303/78911464-9e675580-7a86-11ea-8961-b52a06c37522.png)

**Error log:**
![afbeelding](https://user-images.githubusercontent.com/42642303/78911504-ade69e80-7a86-11ea-8194-a0e785dba212.png)

**To Reproduce:**
1. with a aura using the configuation as above, switch from stance 0 to 1 OR 0 to 3 OR 1 to 3

**Which version of WeakAuras are you using?**
2.16.6

**Was it working in a previous version? If yes, which was the last good one?**
no clue if it worked on a previous version, i do not have a lingering older version of weakauras installed

**Are you on World of Warcraft Classic or Retail?**
- [V] Classic
~~- [ ] Retail~~

**Comment by InfusOnWoW** [comment]
This is fixed for the next release.
