### ISSUE TITLE
Classic - Can't load weak auras

### ISSUE THREAD

**Issue by TripodMedic** [WeakAuras/WeakAuras2#2095]
## Describe the bug
Installed weakauras and got this error upon loading. Tried reinstalling to no avail. 

**Do you have an error log of what happened?**
   Improper arguments to WeakAuras.SetRegion - regionType not defined
[C]: error'
..\AddOns\WeakAuras\WeakAuras.lua line 4401:
   in function SetRegion'
..\AddOns\WeakAuras\WeakAuras.lua line 4365:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:4268>
..\AddOns\WeakAuras\WeakAuras.lua line 4395:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 3928:
   in function `load'
..\AddOns\WeakAuras\WeakAuras.lua line 3935:
   in function `AddMany'
..\AddOns\WeakAuras\WeakAuras.lua line 1606:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:1578>

Debug:
   WeakAuras\WeakAuras.lua:1734:
      WeakAuras\WeakAuras.lua:1685
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.47.00.11303.00
  AtlasBattlegrounds, vv1.46.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasDungeonLocs, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.8
  AtlasLootClassicData, vv1.4.8
  AtlasLootClassicDungeonsAndRaids, vv1.4.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.3.5
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicCastbars, vv1.3.3
  ClassicCastbarsOptions, v
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v8.3.1
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  GatherMate2, v1.45.5
  GTFO, v4.55
  GuildRosterManager, v1.871
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.57
  Necrosis, v6.4
  OmniCC, v8.3.5
  Prat30, v3.7.50
  Prat30Libraries, v
  Questie, v5.10.0 0 fd3ff918
  SexyMap, vv5-classic
  ShadowedUnitFrames, vv4.2.3-Classic-1-ga64713d
  SkilletClassic, v1.13
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.24
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TellMeWhen, v8.7.5
  TomTom, vv11304-1.1.2
  VendorPrice, v1.3.5
  WeakAuras, v2.16.6
  WIM, v3.8.8
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=632)

**Comment by InfusOnWoW** [comment]
Unfortunately that was a error in one of the recent alphas, which corrupted your settings. You should restore your setting from a backup. If you are using the companion app, that automatically saves backups.
