### ISSUE TITLE
LibCustomGlow error spam when friendly nameplates are enabled

### ISSUE THREAD

**Issue by Baconsaber** [WeakAuras/WeakAuras2#2096]
## Describe the bug
Whenever I enable friendly nameplates, I get an error regarding LibCustomGlow multiple times per second.

**Do you have an error log of what happened?**
11410x ...akAuras\Libs\LibCustomGlow-1.0\LibCustomGlow-1.0-15.lua:685: attempt to index local 'r' (a nil value)
[string "--[==[ Error in 'NamePlateGlow - Unit TSU':..."]:115: in function `glow'
[string "--[==[ Error in 'NamePlateGlow - Unit TSU':..."]:45: in function `autoGlowUnit'
[string "--[==[ Error in 'NamePlateGlow - Unit TSU' ..."]:8: in function <[string "--[==[ Error in 'NamePlateGlow - Unit TSU' ..."]:1>
[C]: in function `xpcall'
WeakAuras\GenericTrigger.lua:512: in function <WeakAuras\GenericTrigger.lua:505>
WeakAuras\GenericTrigger.lua:725: in function `ScanWithFakeEvent'
WeakAuras\GenericTrigger.lua:992: in function `LoadDisplays'
WeakAuras\WeakAuras-2.15.5.lua:2190: in function `LoadDisplays'
WeakAuras\WeakAuras-2.15.5.lua:2035: in function <WeakAuras\WeakAuras.lua:1901>
WeakAuras\WeakAuras-2.15.5.lua:2131: in function `ReloadAll'
WeakAuras\WeakAuras-2.15.5.lua:1790: in function `ScanAll'
WeakAuras\WeakAuras-2.15.5.lua:1735: in function `Resume'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:198: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:174>
[C]: in function `Hide'
WeakAurasOptions\WeakAurasOptions-2.15.5.lua:1450: in function <WeakAurasOptions\WeakAurasOptions.lua:1448>

### To Reproduce
This error occurs multiple times per second whenever I have friendly nameplates enabled in dungeons and raids.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I have (the error persisted)

**Which version of WeakAuras are you using?**
2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Unknown, sorry.

### Additional Info
I've tried going through the WeakAuras.lua file and checking for references to "LibCustomGlow", and deleting those WeakAuras. Afterwards I was still experiencing this issue (even after a game restart). If I delete my entire WeakAuras.lua SV file, the issue is gone (but so are all my WAs)

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4461054/WeakAuras.zip)

**Comment by mrbuds** [comment]
It does not look like an error in weakauras but in the aura you use called "NamePlateGlow - Unit TSU"
Btw the error show you are not using last release version 2.16.6 but the version 2.15.5

**Comment by Baconsaber** [comment]
That's very strange. I don't have a WA by that name. Maybe an update for the addon went wrong on my end? I'll reinstall the addon. 
![image](https://user-images.githubusercontent.com/63450744/78985054-1c2f6d80-7b28-11ea-919a-27a704b2802c.png)

**Comment by mrbuds** [comment]
Are you sure this is not a very old error ?
Check in "current session" tab of bugsack
You can clean the bugs with alt+click on bugsack's minimap icon

**Comment by Baconsaber** [comment]
It turns out was a very old error, thanks for the tip. Here's the new one:
`111x ...akAuras\Libs\LibCustomGlow-1.0\LibCustomGlow-1.0-15.lua:685: attempt to index local 'r' (a nil value)
[string "--[==[ Error in 'Thing From Beyond':'initialization' ]==] return function() local enableGlow = true -- glow
local enableIcon = true -- show icon
local enableMarks = false -- assign marks 

---------------------------------------
aura_env.glow = function(unit,show)
    if enableGlow and show then  
        local namePlateFrameBase = C_NamePlate.GetNamePlateForUnit(unit)
        ActionButton_ShowOverlayGlow(namePlateFrameBase)
    else
        ActionButton_HideOverlayGlow(C_NamePlate.GetNamePlateForUnit(unit))
    end 
end

aura_env.things = 0
aura_env.icon = enableIcon
aura_env.marks = enableMarks
aura_env.npcID = { -- possible to add more 
    [161895] = true, -- thing from beyond
    -- [92168] = true, -- testingdummies
    -- [92166] = true, -- testingdummies
}
aura_env.marksBlocked = false
 end"]:11: in function `glow'
[string "--[==[ Error in 'Thing From Beyond' ]==] return function()
    local thingsUp = 0
    local markIndex = 1
    for i=1,40 do
        local unit = "nameplate"..i 
        if UnitExists(unit) then
            local guid = UnitGUID(unit)
            local type, zero, server_id, instance_id, zone_uid, npc_id, spawn_uid = strsplit("-",guid)
            if aura_env.npcID[tonumber(npc_id)] then
                thingsUp = thingsUp + 1
                aura_env.glow(unit,true)
                if aura_env.marks and not GetRaidTargetIndex(unit) and not aura_env.marksBlocked then 
                    SetRaidTarget(unit,markIndex)
                    if not GetRaidTargetIndex(unit) then
                        aura_env.marksBlocked = true
                        C_Timer.After(0.1,function() WeakAuras.ScanEvents('WA_RETRYMARKS') end)
                    end
                end
                markIndex = markIndex<=8 and markIndex+1 or 1
            else
                aura_env.glow(unit,false)
            end
        end
    end
    aura_env.things = thingsUp
    return aura_env.icon and thingsUp > 0
end"]:21: in function <[string "--[==[ Error in 'Thing From Beyond' ]==] re..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:548: in function <WeakAuras\GenericTrigger.lua:512>
[string "@WeakAuras\GenericTrigger.lua"]:665: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:626: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:1307: in function <WeakAuras\GenericTrigger.lua:1305>`

**Comment by Baconsaber** [comment]
Removing the "Thing from Beyond" WA has resolved the issue. Thank you so much for pointing me in the right direction, turns out all I needed was a lesson in using Bugsack. Sorry for wasting your time.
