### ISSUE TITLE
[classic] Following error in 2.17.  Happens intermittently.

### ISSUE THREAD

**Issue by pmb123** [WeakAuras/WeakAuras2#2102]
Message: Interface\AddOns\WeakAuras\BuffTrigger2.lua:369: attempt to perform arithmetic on field 'stacks' (a nil value)
Time: Wed Apr 15 07:21:18 2020
Count: 2344
Stack: Interface\AddOns\WeakAuras\BuffTrigger2.lua:369: attempt to perform arithmetic on field 'stacks' (a nil value)
[C]: ?
Interface\AddOns\WeakAuras\BuffTrigger2.lua:369: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:345>
Interface\AddOns\WeakAuras\BuffTrigger2.lua:977: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:962>
Interface\AddOns\WeakAuras\BuffTrigger2.lua:1288: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1283>
Interface\AddOns\WeakAuras\BuffTrigger2.lua:1623: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1616>

Locals: 

affected aura is:
{
    ["xOffset"] = 0,
    ["yOffset"] = 0,
    ["anchorPoint"] = "CENTER",
    ["cooldownSwipe"] = true,
    ["cooldownEdge"] = false,
    ["actions"] = {
        ["start"] = {
        },
        ["init"] = {
        },
        ["finish"] = {
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["useMatch_count"] = true,
                ["type"] = "aura2",
                ["subeventSuffix"] = "_CAST_START",
                ["useName"] = true,
                ["ownOnly"] = true,
                ["event"] = "Health",
                ["subeventPrefix"] = "SPELL",
                ["auranames"] = {
                    [1] = "Banish",
                },
                ["match_countOperator"] = ">",
                ["spellIds"] = {
                },
                ["unit"] = "multi",
                ["match_count"] = "0",
                ["auraspellids"] = {
                    [1] = "17941",
                },
                ["names"] = {
                },
                ["debuffType"] = "HARMFUL",
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["internalVersion"] = 28,
    ["keepAspectRatio"] = false,
    ["selfPoint"] = "CENTER",
    ["desaturate"] = false,
    ["subRegions"] = {
        [1] = {
            ["text_shadowXOffset"] = 0,
            ["type"] = "subtext",
            ["text_text"] = "%p",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "PT Sans Narrow Bold",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_shadowYOffset"] = 0,
            ["text_selfPoint"] = "AUTO",
            ["rotateText"] = "NONE",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "OUTER_BOTTOM",
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["text_fontSize"] = 12,
            ["anchorXOffset"] = 0,
            ["text_fontType"] = "OUTLINE",
        },
    },
    ["height"] = 35,
    ["load"] = {
        ["use_class"] = true,
        ["use_never"] = false,
        ["class"] = {
            ["single"] = "WARLOCK",
            ["multi"] = {
            },
        },
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["regionType"] = "icon",
    ["icon"] = true,
    ["cooldownTextDisabled"] = false,
    ["parent"] = "cc",
    ["displayIcon"] = 136135,
    ["zoom"] = 0,
    ["auto"] = false,
    ["frameStrata"] = 1,
    ["id"] = "banish",
    ["width"] = 35,
    ["alpha"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["uid"] = "ouHzxdKzjfR",
    ["config"] = {
    },
    ["inverse"] = false,
    ["color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["conditions"] = {
    },
    ["authorOptions"] = {
    },
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["main"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["finish"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
    },
}

**Comment by InfusOnWoW** [comment]
This should be fixed if you update to the 2.17.0 that we just released.
