### ISSUE TITLE
Version pub to twitch for retail is 2.16.6-classic

### ISSUE THREAD

**Issue by cam3ron2** [WeakAuras/WeakAuras2#2103]
The version of WeakAuras that installs when you install/update for retail is the 2.16.6 CLASSIC version.

**Comment by Stanzilla** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• [CurseForge](https://www.curseforge.com/wow/addons/weakauras-2) 
    (see the **Recent Files** section, bottom right, for both versions)
• [WoWInterface]{https://www.wowinterface.com/downloads/info24910-WeakAuras2.html}
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)

Most importantly **this is a Twitch issue** that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is. @ZeldoKavira @telshin
