### ISSUE TITLE
Load condition: Instance type for Zul'Gurub

### ISSUE THREAD

**Issue by xCharg** [WeakAuras/WeakAuras2#2104]
I've got a couple of weakauras that has to load only inside raids (any, including new ZG one)
Here are the settings of one of these https://i.imgur.com/WnukZH3.jpg
However, they do not load inside ZG for some reason, while working perfectly fine everywhere else (UBRS, Onyxia, MC, BWL)

**Comment by mrbuds** [comment]
You are not in ZG in the screenshot you are showing

**Comment by xCharg** [comment]
## Describe the bug
WeakAuras should load while im in ZG with 'instance type' checkbox selected with appropriate settings.
I've tried to use single-option 20man-raid, i've tried to use multiple selection and select just 20man raid or select everything except No instance

**Do you have an error log of what happened?**
Used `/console scriptErrors 1`, then I made new WA, selected described above options - no errors popped (or I'm don't know where else to look for errors)

### To Reproduce

Steps to reproduce the behavior:
1. Go inside ZG
2. Create new aura, call it somehow => its loaded
3. On "load" tab check "instance type" => WA imidiately goes to unloaded section
4. Regardless of what checkboxes I choose in 'instance type' - WA never loads again.

**Screenshots**
https://gfycat.com/ru/paralleljoyfulcoyote

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Same result

**Which version of WeakAuras are you using?**
2.17.0

**Are you on World of Warcraft Classic or Retail?**
Classic

**Was it working in a previous version? If yes, which was the last good one?**
Initially tried on 2.16.6 that was released before ZG, updated to latest 2.17.0 as of now - bug is still there

### Additional Info

!TsvuZPnmm4Fn72tBhq522RuwAl7OjmS7yBpyQjXj4TGDoBhcHh6V9jztG02x2d9ooJISKS0N0NydzugzhJKH)arNoDVWyLAflE4WRgmMroKKNBfow8agjvRYLfGHouUuBaX4H(FJ8Nx5phJNGj8A3wTjPYbXZg8IN29bX64gxqBUujTBdYGyqlATkfcWng(obTTsWiKPlJIIzK2EjvWOfAPc8yAumnAjJyefW7eCscPnMV6YmDJI0ibLxZih16DHau70OIolIYkeSnN8d07mYIcavcfl9ScumtSPopp8o3fnFXnpmhU3)jV2WhbLzLOSCw2P63wVrSxOCeWl5bgz90je6AcDYsiy1yPtQk5TqWjkOQp5L3f4be8s32lbzHr4dczr085OD1QlPMRdU3lObL3RZeS4pmCGhYrqfQeUJJv15INko4(Q0Y3ukYqq4Vcr1eOgsDl5qRdvzfL5VaULWautEJObHBLtyu8YF0nin6lqIuwTn8qnYmOgI)0ySZj3Hbv1FCGi4wmXeQc0UR6GtLwbNzaOIESoO0kGEeGTENOxSdsTDCP6nmCNhrFJci2TqulBvJ5(2Rt(gzpcDi7Zp8b94L(z4EJDqRzTDlhAt)S38VxnEWiVZ(mRM2JIoWtrh4POdUqrdwFPHo5bAYjTiTaBpPR8DmYeKMeUcM6ezR63irk4VEzs9NARtM32JvQDCNG6Z14K4OoSdk2qb4D7)yZsil0ygFJrE8Ph)EnpdNLF6r6ZrQxLunAt2kdVIrwDwYFXEPvct9EgVV(7VxzwCC0Y1xNqPj3VC2T3r7Lde5rGxnCuho8QMdAuO5N8aD(mOU99)TczXwxabXXezV9KLAUFHCTvS(ioXSbxyHty)UU893wBQ3eU0IpoiNwYT(1Q7QlDYo(psCFTs0fKXjvfq9sCnWUK2lgrSPcf3i1bOiSd0BtoSmb)kxBCT74(BQaABRxzP4qhaYb6b)IFE72xb)5cPqMWYDivbZDmLyKrFC4N)iGy7bOC8iSlZ(h
```
  ERROR HERE
```
