### ISSUE TITLE
Z-Order keeps changing on aura update

### ISSUE THREAD

**Issue by tetsuomiyaki** [WeakAuras/WeakAuras2#2105]
## Describe the bug
Before update 2.17.0, I could properly set the z-order of auras in an aura group. This allowed me to overlay textures.

After update 2.17.0, the z-order of the auras now keep changing dynamically when any aura updates. They will only reset correctly after I type /wa. However, the problem will continue again the moment an aura updates.

**Do you have an error log of what happened?**
There are no errors.

### To Reproduce
-

**Screenshots**
I have uploaded 3 images to show what it looked like before, and how it is now.
[https://imgur.com/a/qTKOkRx](https://imgur.com/a/qTKOkRx). Each picture has a description of the problem.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of WeakAuras are you using?**
2.17.0

**Are you on World of Warcraft Classic or Retail?**
Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes, the release version right before 2.17.0.

**Comment by mrbuds** [comment]
Can you explain how to reproduce and give an export of an aura showing the issue ?

**Comment by tetsuomiyaki** [comment]
I found the cause, it's actually because of the 'Set parent to Anchor' option when anchoring to other auras. The z-order no longer jumps around if I disable that option. Seems like 2.17 made it inherit the parent's z-order?

**Comment by InfusOnWoW** [comment]
Please attach your auras and please try with other addons disabled.

**Comment by InfusOnWoW** [comment]
@tetsuomiyaki we still need your auras to reproduce and fix the issue.

**Comment by tetsuomiyaki** [comment]
aura group: https://pastebin.com/tmjpDS2h
textures/media: https://drive.google.com/file/d/1w9PJR0k2sMgTlqCSmbjaR-gyP7Rx5HD4/view?usp=sharing

To repro, just cast Immolation Aura to update fury resource.
The z-order will jumble up.
It can be fixed by making all the auras disabling 'Set Parent to Anchor'.

**Comment by mrbuds** [comment]
I installed your files and tested it on my DH, and i can't reproduce your issue

**Comment by mrbuds** [comment]
https://i.imgur.com/cmiPh6b.png

**Comment by mrbuds** [comment]
Does it still happen when you disable the addon you use to skin weakauras icons ?
Which addon are you using for this ?

**Comment by tetsuomiyaki** [comment]
I use Masque to skin the icons, but since it works on your import then it's not a bug I guess, I'll fix it manually from my end :)

**Comment by mrbuds** [comment]
Can you test with Masque disabled ?

**Comment by tetsuomiyaki** [comment]
Tried it with Masque disabled, yep still happens.

**Comment by InfusOnWoW** [comment]
I couldn't reproduce the issue. I do have a iea where it could come from. Can you test whether https://github.com/WeakAuras/WeakAuras2/suites/629528427/artifacts/5087545 fixes the issue?

(Make a backup of your settings and then install that version of WeakAuras)

**Comment by InfusOnWoW** [comment]
We have released this as a potential fix, if you still have problems we can try to investigate this more.

**Comment by tetsuomiyaki** [comment]
Tested, it's fixed! Z-order no longer jumps around, thanks!
