### ISSUE TITLE
Regular texture with health trigger can't select relative animation duration in 2.17.0

### ISSUE THREAD

**Issue by Dracolince** [WeakAuras/WeakAuras2#2111]
## Describe the bug

A regular (non-progress) TEXTURE aura with a pure Health trigger (player, target or whatever, no other option selected other than selecting the trigger) seemingly can't select a **relative duration** for its animation, allowing only a **timed duration**.

Up until now, I've been able to set up a texture aura that way and it worked just fine.

I had an aura that has been hit with this bug (a rotating spark-like aura that followed the progress of a circular health bar aura), but it really won't work in _any_ regular aura with a health trigger (it works fine on a spell cast trigger, for example). The option for a relative duration of the animation is always greyed out.

**Do you have an error log of what happened?**
There's no error message. It just doesn't work as usual.

### To Reproduce
1. Create a regular (non-progress) texture aura.
2. Add a Status > Health trigger (player, target, etc. doesn't matter).
3. Add a Custom main animation.
4. No option to select Relative duration (it's greyed out).

**Which version of WeakAuras are you using?**
I'm using 2.17.0 Release branch.

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
It worked fine up until 2.16.6 Release. The health aura would properly animate depending on the unit's health progress.

**Comment by mrbuds** [comment]
There was a template with questions, please answer them to help us help you

**Comment by Dracolince** [comment]
Huh, the message box was empty, I didn't see any template :S
