### ISSUE TITLE
Not a bug in Weak Auras but in Twitch

### ISSUE THREAD

**Issue by auddie2015** [WeakAuras/WeakAuras2#2113]
This is just a headsup to check your addons, particularly this one. Auto-update in Twitch installed the Classic version of WA into Retail. Manual reinstall fixed it. Other addons were affected as well but that is for their pages. That said, be sure to check any addons that have both a Retail and Classic version.

**Comment by Stanzilla** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• [CurseForge](https://www.curseforge.com/wow/addons/weakauras-2) 
    (see the **Recent Files** section, bottom right, for both versions)
• [WoWInterface](https://www.wowinterface.com/downloads/info24910-WeakAuras2.html)
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)

Most importantly **this is a Twitch issue** that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is. @ZeldoKavira @telshin
