### ISSUE TITLE
Weak auras not working at all

### ISSUE THREAD

**Issue by Clockzeone** [WeakAuras/WeakAuras2#2114]
Hello. I upgraded my WA2 addon and after that one of my weak auras wasnt work correctly so i decided to download 1 of old verions, and after that it said smth like "you are using old version and some of your wa wouldnt work that was made at new verion" and asked to repair, i pressed that, and wa just became broken. i deleted it and installed the latest version again. 
 So now, addon not working at all, it doest show at addons list ingame(in character choose window its fine) and when type /wa it doest show, also no one of my weak auras not working too. tryed to reinstall, download from site - nothing helps. 

What to do? i really need them. Im blind without them :)

**Comment by Clockzeone** [comment]
Fixed it via deleting weakauras.lua and weakauras.lua and weakauras.lua.bak . they was 44 kb for some reason. 
But Holypower still doest show correcty. Think would be fixed soon.

**Comment by emptyrivers** [comment]
Downgrading versions is not fully supported (and in truth will never work quite right, as downgrading also removes bug fixes). The dialog you encountered should have warned you that it is an experimental feature, and for 2.16.6 there was unfortunately a bug in it which you ran afoul of.
