### ISSUE TITLE
Apparently weakauras is not functioning properly as before.

### ISSUE THREAD

**Issue by hugo400** [WeakAuras/WeakAuras2#2115]
there is no any errors related to the issue mentioned. I have few spells attached to auras, when I cast to this spells auras are switching off when it shoudn´t happen and sometimes they are not showing on at all. Where the issue come from? No idea, as I said above there is no any error linked. 

THANK YOU VERY MUCH in advance

**Comment by mrbuds** [comment]
Please fill a proper ticket.
