### ISSUE TITLE
Apparently weakauras is not functioning properly as before.

### ISSUE THREAD

**Issue by hugo400** [WeakAuras/WeakAuras2#2116]
## Describe the bug

Yesterday, Started to happen.
**Do you have an error log of what happened?**
no

### To Reproduce

1- starting combat
2- cast solar wrath on enemy
3- while casting aura switch off
4-after release spell aura show up
5-sometimes it not showing any aura at all for a while
**Screenshots**
This screenshot is before casting any spell you see the red squares ? next screenshot you will see them dissapear while casting solar wrath
![image](https://user-images.githubusercontent.com/63847682/79564719-177a3480-80a7-11ea-9545-93f2b7716618.png)
this is the screenshot while casting solar wrath
![image](https://user-images.githubusercontent.com/63847682/79564824-498b9680-80a7-11ea-8a91-d4fbdb9012ce.png)

there are auras linked to spells that when I cast them auras switch off and come back when the spell has finish or basically they switch off and they don´t come back after a while. After few testing removing triggers I found the main trigger was causing this issue. It's a trigger with this default settings(status, cast, player,  cast type channel, inverse) So basically if i am casting Solar Wrath, while I am casting it the auras is switching it off when it shound't happen because solar wrath is not a channel type spell, but if I remove this entirely trigger then it´s not switching off. I believe the issue is in this trigger which is not interpreting well the function given.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**no

**Which version of WeakAuras are you using?**the latest 2.17.1

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail 
Retail

**Was it working in a previous version? If yes, which was the last good one?** Yes

### Additional Info

```
![image](https://user-images.githubusercontent.com/63847682/79564618-e8fc5980-80a6-11ea-96ad-4ad457a1f337.png)

  ERROR HERE
```
As i don´t have any error I create an auras in wago so you guys can see what I have and try to understand what I have explained. 
https://wago.io/MLp3s8s6j

**Comment by mrbuds** [comment]
Please fill a proper ticket.

**Comment by hugo400** [comment]
I have attached the reproduce steps

**Comment by mrbuds** [comment]
Please make a simple example the aura you gave is too complex

**Comment by hugo400** [comment]
I have updated as you advice it me in discord channel and I have removed all trigger except the cast one. Then I added 2 pictures explaning what I am experancing.

**Comment by hugo400** [comment]
just to add another point of view I think is the whole trigger that doe snot work, As i have give an specific spell ID as Tranquility and still not showing when casting other spells. So yes, status-cast is not working at all for me.

**Comment by mrbuds** [comment]
Everything is working as intended for me

**Comment by hugo400** [comment]
Ok, then can you give an advice how to fix this on me?

**Comment by InfusOnWoW** [comment]
The aura works differently from 2.16.6, becuase we fixed a bug. There is no "Cast Type" setting if inverse is checked. That it was previously taken into account was a bug.
