### ISSUE TITLE
Anchoring/glowing Elv nameplates

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#2117]
## Describe the bug

Issues using the new Nameplate features with Elv's plates. I don't think I have any particularly interesting Elv plate setup. Mostly their default. Put the two issues in to the same ticket because I'm pretty sure they're strongly related. That could be an assumption of course. 

**Do you have an error log of what happened?**

No errors.

### To Reproduce

Anchoring issue:

1. New Aura
2. Trigger = Status - Health - Nameplates
3. Display = Anchored to = Nameplates
4. Close config to test 
    * I see nothing here using Elv plates - anchored as expected using Blizz plates
5. untick Set Parent to Anchor 
6. Close config to test
    * I see it working as expected now. Anchoring shouldn't really be an issue but doesn't seem intended. 

Glowing issue:

1. Conditions - IF trigger1 active = true THEN glow external element - Show - Name Plate - Action Button Glow
2. Close Config to test
    * All plates should be glowing. I see no glows
3. Disable Elv plates
    * All plates (now Blizz ones) are glowing. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Issue requires Elv. Didn't disable others though. Can do if you think it might be relevant.

**Which version of WeakAuras are you using?**

2.17.1 (retail)

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

### Additional Info

If I had to guess, the Parenting thing makes me think that the nameplate frame that's found is the Blizz one and, since it's hidden, parenting to that hides the Auras/clones. Would also explain the glow now showing if the hidden Blizz frames are glowing. Just a guess though. 

The Aura I was using to test:
```!Ts12UTnpm4xNDZksslWFVnPWbPyUozvQ)fyxixzBzhTPizOd5qVOp7JuYU1O72cyyqrkEqF8JKnNrzKdmsd(bIMGxj1cgz7t087lYyKwJ2tKVkyfZxWi1gLXcxSyE8Br8)1X)3G)9qCKUEf)cvCgoC3MS7(bJ4n1hfwN0Ozf3o76zZyKlBBBDcpRaK5669g7oJuJUKvqZEeug8GYT9EWlhKsWKv0bhOx6Hc0hJFYZ1w(bXoUva(xbfzW5nhWc4P(gUhUS4iAcdP5a3lRFw243ZilHZG26XuqCEU1NYvRulD7rL7LnIsUsv2PmNCSvOvWy6EGS3k76GxxcwOVRikgRviS(GJrc6jfcGublhtnJm)9sCJGRWsl4eLbmjRa3dvrRKqBR8mJuE3scTKqx(iwY9cL6(MbesdaXG4Ox7SIOxKDz55PaZRCgB1dMgbg(yAIEc9neTAevqMsW8MS8DRFkhdyqp5H9zNIibIKhf00TIHV47ZNHwopPBdDzHvZv))iJyXTmYVHEMS9cJKNTgFvcv7aFy1wkD7dGBahTqCc5G6wz3qxc78aGZ9Ce8NYhs1FXYhY2LVKMH2Khs49KonrWDyae6oa2bQ8qltBWPGXou5qFua5gG6Ot0pUhuih4s9xy4(G991eqS9HayZ9BwD8Bh5R(1Siq2ih5(jQB9Er9FMYHrq9i3k5vkmb7nNWZQGyyAVEpx3j(iajBGaoSugBpdf3Kor0wsBvW7n6TW2byNXGL0a5q2GC0Bn9cRFWmmwhPpXxLFGP)yCZWaZhxzXiRTYxF7LFg4ni74TxOuewplAsd)flWTqkdpU3dMIQJRcdkVCCWUwXDU)rRdxg(jLG6tgBZZwEpJ88OeEzgzXvZ)VRqueqOBwGGg7V```

**Comment by mrbuds** [comment]
This will be fixed on next WeakAuras release with LibGetFrame 1.4.1
https://github.com/mrbuds/LibGetFrame/commit/b0e4f21f5ac9e9faf91ee55259e9e4e2a25d1e67
