### ISSUE TITLE
Can’t Open Weak Auras config menu

### ISSUE THREAD

**Issue by Two-Tec** [WeakAuras/WeakAuras2#2119]
## Describe the bug

Launched WOW, says that WA2 is installed but when I type in /wa to open it nothing happens.

**Do you have an error log of what happened?**
No

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I deleted the other addons I had and left WA as the only one.

**Which version of WeakAuras are you using?**
The latest version 2.17.1

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?** this is my first time trying it. I downloaded an older version and it asked me to repair and then still didn’t work.

### Additional Info

```
  ERROR HERE
```

**Comment by Stanzilla** [comment]
Enable Lua errors via /console scriptErrors 1 or install BugSack

**Comment by InfusOnWoW** [comment]
@Two-Tec we need the actual error message to figure out the problem.

1. Install https://mods.curse.com/addons/wow/BugSack
2. Install https://mods.curse.com/addons/wow/bug-grabber
3. Try to do whatever it is you're having a problem with again:
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
   • RED 
     • You have an error with an addon, maybe not WeakAuras.
     • Make sure you clear the bugs once by alt + click the bugsack, to turn it green, then try to replicate the problem again.
          • You may also want to disable all other addons while you test this
     • There are error messages. Click on the red bag to see them.
     • Copy all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
     • Paste the error messages here

**Until we get that information, we can't help you.**
