### ISSUE TITLE
No default aura for glow since 2.17

### ISSUE THREAD

**Issue by Azhll** [WeakAuras/WeakAuras2#2120]
Since 2.17 all my wa don't glow anymore and i have to downgrade to 2.16 to make them glow again.

Weak Aura discord helped me and the issue is that in 2.17 there is no default aura for glow so you have to choose one now. Old weak aura may have the default so glow doesn't work on 2.17 because of that

**Comment by emptyrivers** [comment]
Thanks for the report, this will be fixed in the next release.
