### ISSUE TITLE
Weakaura ignores cooldowns

### ISSUE THREAD

**Issue by Elabas** [WeakAuras/WeakAuras2#2122]
## Describe the bug
WA ignores the cooldowns of all spells. for example i use Warrior execute with Action Usable trigger. it starts showing the aura if the target is below 25% health but still shows after that even thoug the skill is on cooldown. other triggers where i use stacks for example work fine.

**Do you have an error log of what happened?**
no errors

### To Reproduce

it occured after i updated it to 2.17.1 bevor that i belive i used version 2.16.6 and it worked

**Screenshots**
[Screenshot 1](https://i.imgur.com/ph6uMo3.png) 
The aura together with the trigger

[Screenshot 2](https://i.imgur.com/xHXUgOt.png)
in combat. Spell is on cooldown aura still shows

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes disabled everything, also tried a new install, and tried to import an aura from Wago.io

**Which version of WeakAuras are you using?**
2.17.1

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
latest version without the problem is 2.16.6, tested it with 2.16.6, 2.17 and 2.17.1

### Additional Info
one Aura with the problem:
!Tsv0YjUom0VO2jj0c0hPT0z7m0ugCy37dmM1jwj4zd2S2ou4(W(TFLSjuAV7JDMmjYshFKS0jMNYl4mfppDWWK0moZXzzxNo66eoBlNjPheG3uThSoLrZZhNmibJk68Bm2x35rNoeJNZo8ADTd88CmSdARNBuA09dtZlMUa5tzTglVKZo2dmJisxHe9jSVPK(n88HuMkBbT8fJe4S7Nnn)roRY0IevGvD4jJYy(a(t3CBwA2WKXjzdgD3O7Y41xneJCdg)6r3sLOfAW6T44oKmpCW3zbIoTuDX5qu1VG58cRp6TwPvUnrB0m61FbnpR9GTwubRMiL4(x9dq8RjDwHB1CZBGny(civIvrV07Hz9DGNSITqSYypSy60CkniJAr73779zJX8zvnnOJ45V4SdYSZbRfLoJTm0VUh9qvkBxR4iIGjHYU66ys(20zZFA5mC)HL4j135Ona7bAuGdydNPXI6uBHipqhs7jmtcDQ)8ZLoboLIqGdy)BTBh02MJBMqBbrl7SJ8SbJhNgb)byHfplpLoxxzilZTqT6a2uMpD2S4UWHsd4xa)UtzbjPOC)p2LyZLkool9DUy4PN4A9dtyfRzftwepz637H(EfWEOi6m0kZVknjerR2g59c1X5KT(uVeijLRV1QnA8niCaoRaDdPSheDu8oaK8TcL(lKUZk2VicjHpEJW9Tgd(PJSxY0pE4FouRE(iMpsbJui8csAIQnhQPWLanIKkxLf8WARXh7G09eyHuRAIt8peahzlc)SEsoSbunB8NUsiGmOzAnczVYFh4lfEFBiDvTcNBTqljnwvyAP0nyS8rz9Q59WgvveEpOTDTEvVm4cmlvNj9VcRYSfZD4poA1htoPTv)l85nsYP2DBcnl0Ep(9MmYK)F)

just in case my  [WeakAura.lua](https://drive.google.com/file/d/1JVDzZzMT-3tvlMintce6fqgiXBBfHyet/view?usp=sharing)

```
  ERROR HERE
```

**Comment by ad-l** [comment]
Can confirm spell cooldown status trigger is broken, but apparently only for some spells. For instance the trigger doesn't work for Tiger Fury, Berserk, Shadowmeld or essences like bote, but it works for abilities with charges like brutal slash.

**Comment by HardKullez** [comment]
The bug is happening due to system uptime out of range; 3221225.472 is the threshold, if you have more for some reason - the value is out of range and wa won't show any CD. Problem appeared due to [this](https://github.com/WeakAuras/WeakAuras2/pull/2089/commits/da932c71029daaf218e66574b58ef712e9562119) commit

**Comment by InfusOnWoW** [comment]
@HardKullez thanks, that explains it.

**Comment by drejjmit** [comment]
Yeah. Removing line 2184-2187 in GenericTrigger.lua fixes it.

**Comment by ad-l** [comment]
> The bug is happening due to system uptime out of range; 3221225.472 is the threshold, if you have more for some reason - the value is out of range and wa won't show any CD.
My uptime is 40 days and this started 3 days ago, so you are absolutely spot on. What a strange bug... patching GenericTrigger as suggested solves it
