### ISSUE TITLE
error on mytich+

### ISSUE THREAD

**Issue by Pozzyx2019** [WeakAuras/WeakAuras2#2124]
while doing the doungeon he gave me this bugsuck error-----

2x [string "--[==[ Error in 'Temple of Sethraliss - Nox..."]:15: table index is nil
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:539: in function <WeakAuras\GenericTrigger.lua:532>
[string "@WeakAuras\GenericTrigger.lua"]:714: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:675: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:814: in function <WeakAuras\GenericTrigger.lua:799>

the beauty of everything is that the mythical doungeon was another, and not that ..
I would like to send you the attached file but I don't know how to do [it](url)

**Comment by InfusOnWoW** [comment]
That's a error in the aura "Temple of Sethraliss - Nox" please contact the author of tha aura.
