### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Solyad331** [WeakAuras/WeakAuras2#2125]
## Describe the bug
Error keeps popping every time I log in on my shaman only. Doesn't occur with warlock, mage, or warrior WAs.

**Do you have an error log of what happened?**
no log, but I have a screenshot of the error.

### To Reproduce

Just log in and out of character.

**Screenshots**
attaching a .jpg

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
disabled everything and the error still popped. it is WA specific problem.

**Which version of WeakAuras are you using?**
the latest version from the twitch loader.

**Are you on World of Warcraft Classic or Retail?**
- [ x] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
yes the error is new.
![WA Lau error capture](https://user-images.githubusercontent.com/63916961/79641683-127cba00-8167-11ea-8eb2-9a47e4da54ba.PNG)

### Additional Info

```
  ERROR HERE
```

**Comment by InfusOnWoW** [comment]
That's a error in your aura "Main-Hand Enchant"m whcih apparently is using custom code.

**Comment by Solyad331** [comment]
I'm not using any custom code. Are you talking about a problem with shaman aura i'm using and not the baseline WA code?

William King
wjking_va@verizon.net


-----Original Message-----

**Comment by InfusOnWoW** [comment]
then please add that aura to the ticket

**Comment by Solyad331** [comment]
below is a link and a copy of the actual code. 

https://wago.io/Cd0Kqh-jx

!T3vdZPTo66)lDM7mjZEchS57oB37ajKeonHKcKM2U7jbd4aUbSP2M81Dw(TFFLKLTKTKXgifAdtV3ZgSLK1hVsppVFiPBuUPZnTNCt7b3025M2QzukKrb9l4PpFXD35O7EtZSW76Rnw)MMWREq32XWY8MMQWpmGS1EK2enZ5DvZaPRVL5DgdHC7Et7EA9VFGT10dTgBzdpcYn6)tf)FZH)V5HcptbuIT1hcLANNNQFt7H2wZMc53YEGU9n9GV(SETWV3HuYo6JV7sldt4pRDrNoxC(z1pgQWAM9hzz79IdR3St9w30EM94BApY1DQZ7)Z)8rTHwzmS(ZdhK9J)y0bF)P)e1kiFiARnp9bS17S46DwC9olUERGBI4ewZRHc1MXgV8IM9G5D7yzn21aE0tm9I3zRnrVTRTMRgUVKK92gVOJk(2AZCH6)ftDdAPq)5adMFtYrdtCjIgamD1Tn1g)z)rL8O(bJjAOmHhB1mW)VU4Uwtlt4)oyMn(93sEOJo6Z4G7zD1SDtEYVZW0WzuItpEOBcibDtBLmzZOcDjJT0WcBot17JRUZGUnCBf16hR54GFRH5qq(RD7tREE1MHsLdQ)lCwN5OFlj7q)9m9G(U6dgcfKY8UxA8K(y0Bngoe69id0qXmZ07rKE8GFGQJJh3yG3qbPXPbTvvuMmGhnDS2ZOgN(d6irWt11g7oc6vGrDQK7SE4x2E2D3z80nTV9WQT7CB7ovB1j4LxARJFz7lRF2zq3PEpi1KPgNw)Slp(QZWTrxQe)XiXkY7BFyR61HoOzOzMF8Rn27CL(vU8hvHK2NkgbcngUEvhVHB2HsCb7A13FIUIsUSQOh(a835rty673z5VgXbQfvdT4WWXwpEMHj00BwoMQ62S06966tRIenDBHsdATiCRs3CimW2ujBIwFXFjGdYxHua0c6RSlXgAMb3IEKEBx9NCV1zK2aRh)ctoXp(bdhJEWCKEE)(olKi4NnEsZM5jK1AuGHkBlxnx9oWlUPDZlAwNw6blTw9Qoxqh3I85CXz8)XHMGVgobKQzcwdfNAULUB0Sz9w3swzVvJtoL2Y7hlqsqHr(0C1iYq7SEKQTF3brs8IR6Cwd)EGVpZX14UN9rqWccObRA(4rOFX2JSQZTA)OXaK8ev84Wf3qrZVp2WwhH04Qprc4hQWiTXEZCDTmVa(WWAuiCfRXqFKjA8)idhnqYzaQLjepbxkJm6Fpmx2bd7WIwBaZxqf4cRYAJNoIG7HkW2(mkO1f8kZ94q3PTJxSSMGOkKZ7ZvlkwkSGFqxhukdmCqlh3ax7uYvOSAHOWPS0vOvdyWaAwWxyKUXWrUKrfdt0qgU6flILqSOfcJrFqTaSlt9hiYAbaz1WDIr5iKcemrqjG8iia1e6nH6HUMnuh9fQqFCBD0IYWtr9jOhGX68(BA)snKmHx6U1AQomSaddT)Wh4r)eaGcttCN5eSmmmyrk6GQf5Br)tpuDAFipY7mtpSxOFYIGot)(iHKqTpePRZ1gorZ)bGa2XJHmaZvgoZFYfIt4X2woUZ72s3XaQYM9dEzb6mXMwp4xsUmDi30ol)4iLGWvqDFE3dhPzdRGOBdfSrFhP8aIL7ai4EH54NrfoGM2FKUt7rwpEb0D6G)Fp3Wbj95rBawV6b9oe5IZTgaZdpaWY8wN7yB9Fmt3S)ZOzCOzn4(s0ukDhyScgMidjOLG0CB9PVok)4V9upi7q)5BsobcwXk8IAlhhabZ2FLrIcwKo9ysjadikWr41TxrKPeqhBjjwvlbeRulUUiwn91Gyfv4CtZMskxLasbXWCjaYEQT1qByKhwOSVbrQiBug6HzkqzqWYqOPmgcmmpIqqaVUyTTiYbSmwsbRaE02ERgJaCEXJC18ki8pqD8Cq8cPIelyop7bE0vgsgE5XR(YtYiwiurey(xYqJJdhfjz99zM4xIe2FwkYkdIAppevvRF8XVPCXxF4RJ5y5Bmbny6IMIUdJnXM2la2Ts5DQE)lPQ30LDfr3HDbpwGbHamlNs21br9r(l)fL)sy0MvK)cp9U0rNtMc2sXsfX)ZJRFyAzjbefuZUyw08SOQzZtgwesAyEUBnGQmmawAm1AHH2eH18p)ajByCoA24XVybBzbPHbvDN7nmJfMMrxAgu6EHrPzGsz1WVxuTPXtn6zyoGvFACDb6(EKvN6oqDXYMvDA)Qmw)zONdpfAExR7M3fxUOVFcimGhRqffwUI30aO0ZRfCvpm5uWS4xy92fOV(1vVtzYDhp(l9kNe91WUdlv0nKUwZVy0nW9wxO9Y(NV35t735O40OpnulsVg9IGYshUalYyuaSxf98LY6KfnFfHkfGELagHYajfRljldacdCw8aE67PXI0nLbvYZOjemjf0va2ihc2AbtuiABuRrJ1aEDPS5kGJXRTPQe8cgWnMvELO5hp4sinj5GmwKzN9b7ecVqr051CDzqt4jzWcFUE0xDNPZ20AdfwDJOQf7Iyu9M0ebRIR5ZUZ6a)sADGTshZFnmaAVZZ8jJhubf1s78mFe7fWqlcfhzyBWJutwBch5ijoJNNiqy(iskqI7Wn1GNpLZn55OwHwG3VZtZthJbC(eheE11CGhD4yDnth2YdG6bXihltbVmSA)mm24zGfszFj(tig98JvF7FI69hqPDn7C(J63(8l2)tZo34beRGI7yfS9Xkyh14TsQaVsotGsmWZuccWtfHFVsec4TrblYzQDxadwVyRLqnhWAHbaLore0)WSs2AyaiG)4AYWiXXayP8gFUDEJxiuAygCyC0VzAF3xh8XbhpEwcnAEPDqTPfQTWonW3Pb(Atd8Qg70)oX(HixLD6Fl17Yu0041wuO6CS4GH0wnvUp4eqDtDIRXzKRrAR3erTtSE5GaX1gMdEuB8ywD1rp7Uz2pZQP(j2wZGrFEf0BdviMKvc5eFnZFmZymxTWvuik8kQ38Y5HJLq559(0fp2Z5OXoVGAKakDueDEQ17G03aq67uFEReh)vq95LAZfWX5Efr2dOvix7Dza5HHGfR(mdwUaWSegg7IHZPAMhbkxaJRTMOl4viC2Ja1T8QqNpmyukuUnf6slKysIIuajAqZqkz9hGaHzSIHs)RVN3P4GZpPHZvYjEdJZvEBQ18kgz7vEv3pzIw8wwuxhMRWRYI8yjQxECV7g(LFuOXPmrCn76BCRXxlXRXNouo5X6OeyakDZfU8)kgyzigpCiaKLmb9x6Fpwy1BXs855IMTbQBc0HX8qApj80XZ0PdkJ0mhQhumqThwpX9zUQPxoQr3fOUE)tUzCzp7yoWlOFN3f0VcQJ)81Q0xLfKUwS59c7(mze9RA0MwAT3B7H6MG2p9z1HS64h1EgFiLOHA3yjKeQzkFPvJVm4GXI57kqTw6R4rLKaYeYgXHdFDgLHL5vxuju)jqNqhYobqqmMtflWGJAJB7)f4FD7GpDZYzZR6JtsLRN39sVzEZ7UhUu2FvGTXSdW95ercY2FoEIjA4ox8rstTK50AUy(NRU6368NPVuQuZVZ7zhp3f0G)EOAxywzruuYfdyZY(kVA2mkzvvRKVIQs5YXselQExVTyGLcZC8kVH(zzJ5X(Qy(1j7Ry2EhcK7x19YpIIW(pyRQ95pxRXG9wto(5yBJxM39tZ0gGyubkc2zNxGw9T0FcDHryURS28qM(Cj2YhLlkXYh9IXjgOjilLjpW0gTM0tddnVChGDHyIcPcF2h2rG1qw9Ol4rDTPE9Cs4us5Q5LsYs3c44r5J4i2BiCmksLRoAb846zGdsMRj1bKBo4osEOpphRZmOpeglJHSA04sGKpq7dtKwoUPJniISRp571(U3lK(rr7zIOVnNwJiiDLWq6Vj26EP50453fO7qclNHwAZKeXqJm0hpa5Iq0u(erSzThdA7GT3wHTt8w5m2dRhwO0WlkrXFx6OtOGsuqDbyHrW3zJmIOW7JH11HjcLte2(kdJt(A1sGBpivmwl2)bE6vPbZN3x5IW8JpQgI5aVnmWDKvCyazPNdUmemwMZb3a07vCZWt9lr2wkn(MPTD(V(d5SpDXlRW5yICOWv9nGJjKD0MebfTKYwHJ(v2znOv3r)I8Q96)0gixH1UpHo(6R78WNMCTRvpjhL6RKRHy9Y0A)ygGcsU(CbuPcBsxa5TenLxqUcP7WmyXOKR)OjmSFF6yBnEmtwj)(1W3pX4UNQToxU7Ec5kKlNzJoz75cFboxRevRCIRsYvkRum3yCpetipgwfFeTdy5HHWsk8E6jED)1nh4nSWEepW5pP1SdDIXXyP15oH8Isex4W74hH3xaSoYjfnczEMlqqy94hN0z73qAKsKorKPYLcYuqIxJExaw2sh9rB3ZcAW6Br2NijNATUaA0ZhrLY4oaIuYwitPTKZ3WTBoyBHQGl)qSDrHLJanm4rCdiIHzi9Lp(1IpF)(p1ezNCFIyzsovSqZPr7DB7(AqBcPSyyTd4jW0hA6wtqYexnDaMTWmV)3eX)ktLfqdfNJBjjHSqU3JWmNWg69(QqTX59hPRHdzayT771N3DMdH6ZaRBXtFQfLrBaxUeylKKY8SxYpRfH3FI)7f43dLszxgYEKoPKrZd31eLGhRgIfZKp1wHzGbGN1hOy9CeYCAiKoCDH)535ngVC3vqUWWKPBKmtj)jiTQrJ5ip2PEFiuNk99WFlmMISglR4ZLSqAkWIs8pF6dtf3Kwifv6msYtoZAOrFOZfteWYCpVeU)8)AExY)gBbI4Z7IgXN39dZ7IyVDRU5dzi4Zbjm4VmUdyL5vs)BL)E)5DDhPZMsV)HkZ33w3fjKVhIHeZNvFSJ(cYXDAqAyZI5ar1gBDy1iyHlAfs9VN)xKK69pPuKeWMN3XxbknXqRoFLkvkV0XYviY9iUwtTEu0H5Hsr18fjE6ewEdLfJbrExOGAU(tqtTnH1UqE2Xs4KZqGYJEOOHwnJUacyEZ2pkkaPjDRLYvoFCrmncoJrdcVIPkwSEE3R8wTpfHmT)XYQ)ydzMZTJmabK2Ugt0hqMWXXKMKOF5vBqGYaSAc4DjQfeKNjyZrRKpDMt93f)sUkBLkLSf3ur5nIkPaOK1HP9cXNSgIEG99expSZmXBCxdk(q7Eny)uEvdKh6qH3ezcu4zHHsFcdEiv1Yv2cSyQ09PvyDewkRMk2gNHTeAQ3kxYCGk(ZvJA7PuCkaSznKk7YqYIFDPg)m0MHMZuOXzTrol1gJvx5I(QawrQzluiVCtQg6mDp1MuD52P2XgS8RH4kxGD0qikxE)SbFA)x(8h1ooPmskiGrYBHD39kg4ZPIvYoe9nnI(p1dAE8uXALBDvVpR)PS6N8k56x5kh866b4qWXR8o(JLTDsVWYkTz3NFEuweUh7LTl)Qn2YAW8UhpZ(5LKdddXIxbAlI29FBP(7LRRm8LSQpRGsQXqwj290hL1suCCkZHyOPeXQqY3HFmU9LBF3VL4331)EIpSDaeUBSkMsgj)YVhSsCWMDqU8PYzNP2AijGbuSUzl7Nh6EYzF7PR)Q9AWOiE37WE7WvPWD7yxTPzx9AYUyXUDu0v52RTntkuo)wJnteERY5tkBR5iT5xrdHG2YrT0qXwgdlJWO4CltfjiWIjqYLzwLKXZqE0UTaiEEVDfqzsbKPRSXmkYUtqajmOw4Q6CAHi8sXrP0UO4)xZZ)(1hbKxLT112cbKuhx)YyXg3j23pjR3SXotNeOhLet7SOTCzc4zT(2tCBcExHcWpH3o(92I4E9ZXeoPjQEIEX5WHvNO9y3c8eLhll(ahjEcvP7aBAz5zvuPs2D8S2U4zj7cqWnVzd37Qm4QHFkIHzqmRkVZyvYmwvXkzkvQuLc5vYQuOyUTyZwn9z3C1Bx)SbkpSomBf6i7yNzR2(zn(w0SvOTv0gN(0oZw96y2QMzJ3qvSlm9lSHQ2rEAlJ806XivvsjvQFxco6vmsKY9tp8Ox5l2ijNw2RxdSeLP9ogx)gX4kSEhP7uNi8jmNUHzFnOgqwLKYpzjImPIzlVu7iX1mdlgQHlt8uVzOAXQx2g2)FHeiIHuLFm8SqYuuq9Tm2uQzbz2DmQ2UyuXrxcBJc1HzV(VURxPINyf7j2LA23O0OwfN996YHkyp0VI3KucSmWoQt7OoTYuNwSXQy4tiGpVyowCRHLuduvP42GbQI907AJWFcJBsoUdOW33BIAUnvkLRy(Kg(4mzSh7rcb9aDihElZhC8p4kW(2GeG9eh8ziYgNNgxDjohiMEAAmmZ2gCAizuEhlTTjwAIoWiPhSn4lWHg)1(hQ68yTjFc3jQSZzHsCw4RkbmoGOvCBD1)J29)EVsFUXltwdUkS(y9jGWl60L5Cnhai)5FobgKam8Dm820m8sanmjhHQ(kyKWDv3IcYkfLTHJqvPEjmMJp1FzjEb94rjEjvRVnmRlrlBXqesg3R0Uz84HV5S7fppc5N6QjK51cS32R5(XJpWWkw8Nf5lUo3fY(I7SxyzoAL2ioDmjNTOICfPQAkjQ97saZ)BURi3aNp7lIb8A0So7yWflNRKXylmZSKYkm2BcUFAwpRCXTHOJ)nR1ZkuyXwptqGVVHzZTGqXx(5rj03vOYYYLJJtvcT1wOdNHeE0kq)irVc82cpl9FJAjT4olBcSN2LtF287A12Z9bBCxzOZtF1C5chOzt1SVN8(VqIuCh9QdqRXRpqFW5gMe3FS9YrtaHSEygsnmp22ISC2sDc6JG1MzdFUJ0D1mg7GdBDxAPxdeyhal2di9KQih3x29ijUhobuLeFrjaT0BDWNLSENi9jzRv6hzQ90SVf()9NvjITJYnBlxSEZ7(6DQ(Vgop)pqzrMWIikiX(vnZ92Ee4S6hVHhaYV9pa8kD3sE4fnVDDye3vDeaFukswaLRkiPL4LshsFS)Vz1lJwziVYpjKMp8tTGNzfmA79eDKkMTvaYn4tQAQnvdR1nEf8ou4Ggi9oVtRV()5qYTBrnn7)Zvnoi4xh0gLbV8DkLQFwETRPQauwSVgcGL)kweWt1B18f8EzlK4MKG1esnAFG2Xyc645OUjOKsFDV8vdOEpataPD1JokT2hONhSxcedfQFok)OlRaZbCLqg1sLZNtjxj1c5RaTFCbMrjBHYLvZvqTsEfLYreo0SfulY4xkkvqrTxGqD2m5lxjFUsvQukhuEy34JKBbu9HomQchOIkTXszs0ZRleFJGXyCepKwFTydnc51zJN8lun1EShTV83LPy8)emzLiQzmyGoqaTz9pJMOJF2reEj6suKmM7ydHQvk7c2WtFL(j6crn1x2gXCPAKQ7tJOxxhlZvNHLTbY0(eY(NErRgF7IMDQE2nP52xnIYEA9CSS7HfvQjxfrrk6WRCjmvFqWvZoNkqcVvfQ6P6riFce5EeGDjLuP5x4tUpCfmfA6X1Ve(auo5TVKO09Qyv)OxUfC6OMADaLAVC8S6RjOb4G4eT2)DNEXWx(23h(KAHWAWP9ezFyRg6IvqTs5mzZ)gqBqNjwwUJOMVaRP86uDqC)FUdpU2OVC89dE4lc7)5g1qJrSkiYR6O0vxcR3zTXgV8IM9aKjPSGfOMMipiWsbHNFsHyGTOKvufEZ1tVotA7FT)aRf7smA2hM39kivxIUEA27DK5hVBE3)yE3S7JVxT8YBnz0o8lC)lPRmT7Rzwhnt0zV31PXHF8QlpQAN6V7pqxFpZ05k2Es3HvRcdRcTXYC)duteu(w3uc3kzeiOa1W63NLoIsEKCuPSIkvmFjwYazJHzeBEYwmCMimB42HXc54SSKHJ5UTTMi7CWXukFatP0BVdgT6IQJMeTXeQqJiLHcutSA)(q9N4ZFOrIAmiZ3fwvr1SYummgVR8A6AO2xwT1htHAHcu)luNik2yItn7qTbYfZoX8ic0nmA9aDnofr7WIrupS3YPEyHqQhIfaOohvQBJqRi)pd79iKxFAxG1ps(8nI13ruI6rDCus1hqOXe9vpjPNT2l2jsNx9K6O5VxxT1zxC4hr)5PxH)AWFDzRg1B3b9xh16QghH(dFNobsDNv9Ogl(EcHz3VfXUUPHWTiQZuOf)B2onadrhHJe9UTR)mBBy29Ir1KDz3Xva)l2sa4i4xiKIqYDHh9wQdFP2TW70o0hvhQRWN6Dx1SrNBV8IRR362JBv)txbseq9fOIhUEXC39faIlU241XqfPX9kQrtM2)(DV7VXV8)l6lP)drwhNgec(FipDK5mdsss5Qx0Fet61FAQbjriLCW56eDx0FVhmG8psuzqb5qYz4s4D4BaU3ftwqiGNI9SOxtkAs)Vc6ufY0IDOm6hK7AtmIWbwHiIgnxD4H1RFu9JekH8pxrjKIzYxaOqDW8Upo65)3O55GdeLRc7KR22KRKSQZbhKIYi4A3ev)qoKMOeoO5TmHY3twOew(m6sAVNQ)nJ1m8UpgdSCGo9UfMGDt16pWsaQ0m9zpyBO2WiIXn(tQ4)3i6)liIacUc8r2kZAMDF9RySlc1kdEz8uDTXG6ij2v01BwV1jn(gWOLPO9RpKwVhCx6VW6HQh((ffxmrd4HG3XeZqHSnuO6Vx(VKCRLUcwzb5MCdBDCbHr37fRTwwOLv4nlDLatjxQCEp9Oi)GAN5WmVezHCPuyPm5idjfeyHgK9QZNRC(sL(DZunKZvovZE65U7KR)4PlNF7f7n(uy(MfySgLigOrQ8tGnDYKnB2CflQQKTsUsfeAhGKhjxYm5UmtAJNTQ72tZ11tjOuyPDuMFqFKrFswx0TzniqN4R060grAYmnFmUSioR2hXzC)KdKI6pnfHG)OwutcG0xE9494(7cHcrHSBC99L3f6e7cDIDHoX6i0jI4BbrUsiPwWkfrAaR3jsRL(L6UfHbLCnFlGhjmkezWncHBKC9vE6C4X7nvXgrowoO58iHwihl1ubghnLrhHYIdhIL1Y)rTTF8bpb1NaCEaihtSsi3buiRA4R(j5Re22eEwxWgR(w40Yz7mtlxiDzqtiZTalC4LMpGsp0yE)H26WW9XOf5aLQmhUNPX4)a0A)IpxV1zv)672xGT9YeuiK)swsEFBD3)ISaXP79oISwmLitY)8EV78ghD0z1xqYXIX(f9F41QqnGe81gz94E7lXmbmFJ24Lhjtl3tbk7du2xycr9I7r(97pX7N7loPiHtSupt6dEgktKAdZ)sKpiJA9Fx2j3mgqEFErOfilgskAICBl)hOW4A2Km(65MbTG0(XyahYxKVVzVj8zc3BePlHTZjTXvKfjQ09PqtwblFipp6VioDjl1csDFFkSX)ipBMK1ZglJqy(o(wybBMcS))rHHcjT1eCPz7BOMydOeIAw29H1Z9lypBnncVwh2cDHnhc5ZElYrpAUiu2)1heyFLKSHg4n6I8DFqitTSmBTHqxq4P0KlHcVfYDkVSOSmbXjFuFZtdkpCTazMGgaGSVzcGhEZ)p

**Comment by InfusOnWoW** [comment]
That group does not contain any aura named "Main-Hand Enchant".

**Comment by Solyad331** [comment]
that's the only aura i use on the shaman and the shaman is the only character i get this error with. i use WAs on 5 other characters, but this is the only with that throws the error. 

in the error message, i assume you don't see the name of another addon?

**Comment by InfusOnWoW** [comment]
That's a name of a aura. Please attach your settings found in WTF/Account/<account>/SavedVariables.

**Comment by Solyad331** [comment]
i tried to drag/drop and copy/paste the and it says "we don't support that file type".  they are the LUA files out of the SavedVariables folder.

**Comment by Vardex** [comment]
Zip it first

**Comment by Solyad331** [comment]
[WA saved variables.zip](https://github.com/WeakAuras/WeakAuras2/files/4497233/WA.saved.variables.zip)

**Comment by InfusOnWoW** [comment]
That does contain a "Main-Hand Enchant" aura, and indeed the custom code in the Actions tab is broken, you can probably just disable it. If you have any further questions on that aura, this is not a bug in WeakAuras and thus we can't help you here.

**Comment by Solyad331** [comment]
I'm not seeing a specific "Main-Hand Enchant" aura, but there is one wit Rockbiter Weapon which is a main hand enchant. Is that the one you're talking about? by the way, thanks very much for taking the time to walk me through this. much appreciated.

**Comment by InfusOnWoW** [comment]
It's in the group: "Dajovas Missing Buffs and Enchants".

**Comment by Solyad331** [comment]
BLESS YOU!! I was looking under the damned shaman wa and couldn't it.

You're the best. Thanks very much and have a great weekend.
