### ISSUE TITLE
Allow custom points when using custom anchors

### ISSUE THREAD

**Issue by anaseskyrider** [WeakAuras/WeakAuras2#2126]
**Is your feature request related to a problem? Please describe.**
Custom anchoring is great, but if I want to anchor clones to different relative points on the *same* region (not just different regions for each clone), then it's more difficult to achieve.

**Describe the solution you'd like**
Some way of returning the frame position and relative position when returning the frame I want to custom-anchor to. If custom x,y offsets could be returned as well, that would be even more helpful.

**Comment by InfusOnWoW** [comment]
I don't think we want that. We use the same "design" for anchoring individual auras as we use for customizing dynamic groups. And for dynamic groups, that doesn't fit and thus imho we shouldn't add it to individual auras, as it has a very niche benefit.
