### ISSUE TITLE
Status - power - not working

### ISSUE THREAD

**Issue by taccr** [WeakAuras/WeakAuras2#2127]
## Describe the bug
I use weakauras to display my current power on various classes. e.g. Insanity on shadow priest.
This does not work anymore on any version after 2.16.6. It simply doesn't show a number anymore. Nothing is displayed. 

**Do you have an error log of what happened?**
No errors.

### To Reproduce
Just load the weakaura in any version after 2.16.6

**Screenshots**
Very simple trigger setup:
https://i.imgur.com/fWlJyS3.png
https://i.imgur.com/OeuQy3z.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes.

**Which version of WeakAuras are you using?**
I tried any release version after 2.16.6, including latest version 2.17.2 today.

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
2.16.6

**Comment by mrbuds** [comment]
Using %s does not make sense in this trigger, %p works for what you are trying to show.

I think this ticket is a duplicate but not sure, and i don't know if @InfusOnWoW want to do something about it, so i'll leave it open.

**Comment by InfusOnWoW** [comment]
Yeah it doesn't make sense, but apparently we used to do that, so I'll readd it.
