### ISSUE TITLE
[classic] taxi conditional

### ISSUE THREAD

**Issue by pmb123** [WeakAuras/WeakAuras2#2129]
hello, asakawa helped me with a custom trigger to hide auras while on a flight path.  could this be added as a default trigger?

function() return not UnitOnTaxi("player") end

"it's part of the vehicle check in retail but there's no equivalent in Classic" -- asakawa

**Comment by asaka-wa** [comment]
You didn't follow the template pmb123

The working trigger for this is custom - status - events - `UNIT_FLAGS:player STARTUP`

```LUA
function()
   function() return UnitOnTaxi("player") 
end
```
