### ISSUE TITLE
Looped sound actions don't stop with "Stop Sound"

### ISSUE THREAD

**Issue by Mpstark** [WeakAuras/WeakAuras2#213]
What steps will reproduce the problem?

_Have an aura with a looped sound, with Stop Sound selected OnHide._

What is the expected output? What do you see instead?

_The looped sound doesn't stop. However, if the aura is hidden during the initial sound, that will stop._

What version of WeakAuras are you using?

_2.4.3_

Was it working in a previous version? If yes, which was the last good one?

_First version that I've checked._

In case you do know which aura is problematic, please export the string and paste it below.

```
dSdVdaGAuv0UuIETuQMPusZvvA2k1nLk9yjCBP4ZcStHyVKDRy)cPFIQsdJs14qfLllAOOQQblOgUs6GukBJsQJjvDour1cfklfvelwQOLlPhsj5PGLPkEoftevvMkvnzQmDKlsjQRkLYZqvUokBKsKtRYMvv2UQQ)krFLsW0eQ(UGyKOI0HHA0OsJxkXjPe6wcsxtjCEuHdHQcFtQWVHS6LxawEbDXdoAy(D)3Ctq0WaHMur65fp(dprcmcEwgFjpbncCcCYlWDg(Knf09NcW7Ta3zw3yo8zlKao1YT2kFfGlO7p91liiRDrUurcT3UadInobwCOS(HlYxBohAmVwiXTBJvXMx(JcjR2yvSPB6o8lGyJZ8wWfp0ZsuqGaQEbbzvEbSj)ZHeqxt6e4yvmDOrG9L9cY)CibwHA6etrd3kkqWGBsJ8ksVGU4bhnm)U)BUjiAyGqtksaZKLgeRwKTnhPycyMSKnhPycmSoZ)CiG99DTiO0kBGVeAZkRSmacmiwTiBBosW6gZrwfGcz47S5qXejGBEbCjzjRxyFrpNX7HN18EwWRdR1xOX5CbgeBCLRyIRabgeBCLfCXZKBbDXgkRcQzWHgphRPakBHeyqSXv2(rLNtGGAUMyYFnPISqGHlITDCsUMysXemSgF9ccYQrr6fGlOdng5fyiCLKxGbXgxznxtmPile4qLBeAvXeyqSXjWIdL1pCr(AZ5qJ51cjUDBSk28YFuiz1gRInDt3HFbeBCM3cU4HEwIcce4qLgeBCkMibF3CgUYlWqO1sdInoftKibNtaF4tdfnmGyJlAyBf0HgJGnc7KxaH35qpYlOHTPtErIeWmz5K)zvDkGW7Ci5f0W20jVircC333vW2ehYlOHTPtErIeuXfP8cAyB6KxKibR)ReENdjVGg2Mo5fjsqfTt5f0W20jVirc(Wf0Hg5f0W20jVirIeeY5iUYsXxyNN12T3H9(((hEp21xOX7qKGFfPp(tVij
```

Attached aura is using the Mana Divining Stone aura.

**Comment by Stanzilla** [comment]
Fixed in https://github.com/WeakAuras/WeakAuras2/commit/aa4bda86f4e8c9e352520d08e73025d016777dc4
