### ISSUE TITLE
Spirit of Preservation not available in Template

### ISSUE THREAD

**Issue by AvalonInk** [WeakAuras/WeakAuras2#2132]
## Describe the bug
Spirit of Preservation not available in template.

**Do you have an error log of what happened?**
No.

### To Reproduce
Click New Aura
Click From Template
Click Icon
Click Medium Icon
Search through all the options and find that Spirit of Preservation is not there. 

Then I updated WeakAuras 2 (in case the spell was there) - no luck

**Screenshots**
![image](https://user-images.githubusercontent.com/63978981/79699541-222afa00-825e-11ea-9c34-cbae10834b88.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Pretty sure it's not a UI issue.

**Which version of WeakAuras are you using?**
2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I don't know if Spirit of Preservation was there before, because I didn't have it before.

**Comment by InfusOnWoW** [comment]
That's because we didn't add the Azerite Essences, mostly because it's a lot of effort.

For trackint the cooldown, you create a new aura and set the trigger to "Cooldown Progess (Spell)", name 296208

**Comment by AvalonInk** [comment]
Thank you! That was very helpful. How do I make it show up all the time like my other template based auras? I am not sure which setting does that.

**Comment by InfusOnWoW** [comment]
That's setting at the bottom, "Show on".

**Comment by AvalonInk** [comment]
Thank you again. I know I'd found it before but it's not as intuitive as you'd think, having that near the bottom of the "Trigger" tab rather than the "Display" tab. Still a great addon, thanks for all your hard work!
