### ISSUE TITLE
2.17.3 Buffs on ennemies's nameplate not working anymore

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#2133]
## Describe the bug
Using the following aura
```
!LJ17VProt4)xQuLALUJe(r61Es9vciqB6rbkEt717dly21S4YYAET9cH8b(B)Mz8(lc0KEN63o1QK1JhpE8mJFMhh)6(E(mJpRrT6)wTg(S1(Sq8)GuUoyGijYU0FyZxDjmo1UuPhTXkvjgqblON0SjMV3tChm45B8z7hTyHry9hc6hPLHE73i8ztU2NnxPdf6UQyLgw7W6OkdBq)Sj9ZwOqWmMn8aboflvh7ZwATBm)(fxSJhPQjvxC3N)R5V6BHnV(I6GlfK7mmJLRToVAHmrAw6(g(0jf(EopyvKwLMeEtsUtUdCRVO5GR)LIVatffj008lujWk7RL3Fy2Ns5HAULFyMhSHXkofMsnIPbXCJXFUpZ9biDDASvMVXMnIGtfkVx8qHGyEICn3kqJzc4XcmQW0Ii4C6cMH7t4RLb4bb81a44B5j2(qOaISSjTV(MBz5H78SrlFMvfSvOnGzalwV5LTY1jlwuhJB3jc)ImeZ4nUKYGQD(Sb967LRChiegQvWg3jwE)9CDiemuk4eq(szYToLCRtj36Lj3GuJvTgRxUDtiEmzPz)Um54ZgQsajwTetdgNf9keGFgkMNUyHlG8(Edg3)2bW80qEQM3GI5XX3eMvOAsNl2ksSmyvY78zt72M5nL51EcymiEkY0lflxyynnSpmAjWgi4XqmPWiJ1cYiSX9gmWTQsxllncXI01jmxTmMb5HYutwCfkzgixd7eKK5XYOeFw3Ed96nXNvMJO9BcL4ZCU5zb)UpAC(YAxrxcGcxgwInSoenuP2yjguhDR3GBg2lpFIEG7REHrW01pmBmufa37mk46elHYeonCwdmwm57dVctdl4q57nqviAPVbzx5I95LmujknhREZRE9BAHv3bagYyLeJRoTGASYWeIzKvbEffNA7wGqFlMz6a(Ly9wm3uV2L1UexTLBPagmqc1oDGmS5WmvYHzyEfsLwi5cllEr22o5M39EyFxOHPHAk4cnT1oxRpk1vxX6oPxVHGxGMn0R5QGg233zWO87O4Uwb4HfcfEOWPU6qJao5q9xwzPlsk4gCpZHvDc8kvaCV1CzYprZvag(tYGuTDYczKRMKFu(HnS9h7nEqBVEu7cfgLcC5twBymT2qzLoiqgrOt4XFoVUVXB8z3LJB9RuPCqjcaaC0ilnMFJHK1)7ctJtxV)rxgURstQsajiuLMq9tEH4UnsxSYtUw8lhMP57Uol6bJ2OvrAHXaFUqPr06WkZIvDWVKb0iO6iyL5Lh(WHzU)fRauDq(HzV9WmRkjD9CH(fNOMwyt1jKE8Kq63)VdZQxosPpm7zp7WheiGz12UhDflpifay0HQDj4bTxcFESiKAxLjMTtcP4o)lHWZGjF621ymb3Lhdz3SuTRBmuRzqnD48Dl6QYJKbOCrIMhHEmH(M5awizfwwNdyeNaHxbQ)4geh374Sa9znhkqvEIUkNRf1z6vGCO(gv4TfDG44IiStTbk8iZCCD2kYK(rvOipFKLdja8oeOzEhzy0kHytBK)HDcguqr)hh96mCgZI4U8)urY2ATddPIWxuib01kQHLaWT6cPoIzVeCp10mJm)y)o30NOsgZ0cfG7(F4HkzplRBcsl)wmDjXWTy4HynMJobfVbshMARS1Kbk0zKN3OpM1g87s4OeXDQzjhQW(ZkGmKyRJ2FWrA9dWW3PDzd5236nkt65BAqtvLD6RkOs81h6ufCqYH(igcchc)Wri1NSkO05UdaTSFaGpNx8OnAYIbN4uN7vg0eBHmeKgjqr68xf8g4Q1BYux2QY2x2iZP9j5fujxvFoBplEIqgzXQD91I)FQijypsvSXvvch4SoDQAsCSZAZtTqdRrqfdWp2nr(deB5g(1hSUUpDufvRtbxua86DfRBUBwwXZGixzPmyf0DWuSP56nqInng(AYkrvScDpAPqgTe8SMxEezW8QK8xZ9p4bC4d)WwpKJ(DEn3zP3q3f7cjjaRCn1E6MHSBUUxfUm9J5rMkS1Pjo7sGQ9Gv7Z5FGUsbJNhHq0pqI5HPImx4jxx13Qsn8)(mRl80ZECljT1O1P01VxbyK5L8W4NBoAJgZ1yyA(jpyOktORLMcque5HUgE67Kr()otFygXa5ch9JdZWo8ilUJFRb9GHpf2TXMx(hJ1FEf2wFZsNBVZbG1mZXB4(ZMuLrTmb3FrEvnCqGmCASWuGJ34igCv4t7GSdwkcwvLvfUV4t2F7Bb4EECQiNifmslrtDmrlKuXsEsKO0MUL1H6USrOT7jaJAnQrxaTLV61fCrnXCFXFNfA2TGXA1als8)7)
```

With 2.17.3
I'v see sometime buffs on friendly nameplate show on wrong unit
And in battleground it never show on enemies

I tested to revert to 2.17.2 and can't replicate this
Some ppl complained about this issue in battlegrounds in classic help channel on discord.

**Do you have an error log of what happened?**
no error

### To Reproduce
Use aura from pasted string, test in battlegrounds .. (i'v test in a duel with 2.17.2 but it doesn't show buffs in duel in this version either)

**Are you on World of Warcraft Classic or Retail?**
- [x] Classic
- [ ] Retail

**Comment by InfusOnWoW** [comment]
Hmm, can you reproduce anything odd on retail with that?

**Comment by InfusOnWoW** [comment]
Code wise everything looks good. I only found a bug in the boss support. 

I can probably test that on classic for friendly nameplates, but I think testing enemies would be hard...

**Comment by mrbuds** [comment]
Good news, it seems the bug exists on retail too.

**Comment by rokmanfilms** [comment]
1. The issue isn't necessarily related to battlegrounds from my observations. The issue has to do with being in a raid group. If I am solo, the debuffs appear on nameplates just fine. You can go kill some boars in durotar and see. The moment someone invites you to a raid group, the debuffs willl stop appearing on nameplates. Since battlegrounds join you into a temporary raid group, that causes this issue.

2. I have just noticed a new error while running around on my rogue. If I sap/blind a target and then vanish/sprint away, all new enemies I approach will already have the sap/blind debuff on their nameplate. This is quite frustrating. 

Thanks for any help!

**Comment by Obreezy13** [comment]
It is also reproducible in world pvp, if you CC an opposing faction that same CC icon will show up on all other nameplates for a period of time. Either that will happen or no buffs/debuffs will show at all.

**Comment by mrbuds** [comment]
2 tests i reproduced on classic:

test1
- group with someone
- frost bolt an npc => show debuff on nameplate
- change group mode to raid => frost bolt => no more debuff
(no issue with 2.17.2)

test2
- frost bolt an enemy out of nameplate range => when nameplate show debuff doesn't show, if i frost nova then it show both debuffs
(no issue with 2.17.2)

**Comment by InfusOnWoW** [comment]
@Obreezy13 I believe I have both issues fixed. If you want you can try this build: https://github.com/WeakAuras/WeakAuras2/suites/616337367/artifacts/4793517.
