### ISSUE TITLE
Cast spell triggers main hand swing timer 

### ISSUE THREAD

**Issue by uily** [WeakAuras/WeakAuras2#2134]
In Classic after using any spell (casted or instant) u got one main hand swing timer.
I have used v 2.16.6 since yesterday and WeakAuras doesn't show these swing timers right after casts. Now i use 2.17.3 and by successfully casting a spell, WeakAuras triggers the main hand swing timer and if u use instant spells it doesn't trigger.

- [ x] Classic
- [ ] Retail

**Comment by mrbuds** [comment]
Indeed that was a fix, what is your issue ?
