### ISSUE TITLE
My weakauras for Retail keeps updating to classic today for some reason 

### ISSUE THREAD

**Issue by super69r** [WeakAuras/WeakAuras2#2137]
![image](https://user-images.githubusercontent.com/48585280/79917533-c25f6980-847e-11ea-8140-073e292137db.png)

**Comment by Stanzilla** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• [CurseForge](https://www.curseforge.com/wow/addons/weakauras-2) 
    (see the **Recent Files** section, bottom right, for both versions)
• [WoWInterface](https://www.wowinterface.com/downloads/info24910-WeakAuras2.html)
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)

Most importantly **this is a Twitch issue** that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is. @ZeldoKavira @telshin

**Comment by super69r** [comment]
Thank you very much youve helped me with my problem
