### ISSUE TITLE
Weakauras not showing up after todays update

### ISSUE THREAD

**Issue by petesmisc** [WeakAuras/WeakAuras2#2141]
Today=04/22/2020

So as of today (1:30pm CT) and after updating my weakauras, my minibutton is gone and I cant access WA using the command line, addons shows that weakauras2 is loaded but it does not seem to work at all.

Hmmm, whats going on?, too many bug fixes lately without testing methinks.

**Comment by petesmisc** [comment]
Oh, forgot to mention, when I try to bring it up with the command line, its saying to load the "retail" version, what?!! is twitch loaded/updating my weakauras2 to the "CLASSIC" version?
In fact I notice in my twitch account that GSE, and Decursive are all marked as CLASSIC, never noticed that before and they too were updated today.

**Comment by Stanzilla** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• [CurseForge](https://www.curseforge.com/wow/addons/weakauras-2) 
    (see the **Recent Files** section, bottom right, for both versions)
• [WoWInterface](https://www.wowinterface.com/downloads/info24910-WeakAuras2.html)
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)

**Comment by InfusOnWoW** [comment]
Seems you aren't a very good thinker then.

**Comment by petesmisc** [comment]
Thanks for the reply, Ive been using Twitch since they bought Courseforge,
never had a problem like this, four addons where updated to Classic.
I guess Twitch wants people to watch the games not play them ;(

I gave Minion a try and it did not pass the smell test of my antivirus
(bitdefender), it tried to delete a folder in an area it had no business
deleting anything, aside from it needed a reboot.
But it did come up and updated itself, but it recognized Weakareas as
uptodate and other addons as out of date, so it wanted to "downgrade" them
to lower versions, so it seems that its brains are scrambled as well.

I not sophisticated enough to give CurseBreaker a try, I'm just a GUI kind
of guy, just want to play the game.

Anyway, didn't not mean to impute the reputation of Weakauras developers .

Cheers,
Pete
