### ISSUE TITLE
Multiple Entry Options within the "Load" Tab

### ISSUE THREAD

**Issue by zazomazzo** [WeakAuras/WeakAuras2#2144]
**Is your feature request related to a problem? Please describe.**
I want as few **loaded** WAs as possible. I.e. I only want a specific WA to load if I have **any'** fishing pole equipped or if I am within one of the three major cities Orgrimmar, Thunde Bluff or Undercity. The problem is, within the Load tab the entries "Zone Name" and "Item Equipped" are single entry options.

**Describe the solution you'd like**
I would like the "Zone Name" and "Item Equipped" to be comma separated multiple entry options like i.e. the "Encounter ID(s)" option. 

**Describe alternatives you've considered**
No real alternative found so far. The only one that came to my mind were to duplicate my WAs like 3 times and edit one for Ogrimmar, one for Undercity and one for Thunder Bluff.

**Additional context**
N/A

**Comment by InfusOnWoW** [comment]
Multipe zone names are now supported. For items, you can just add multiple trigers.
