### ISSUE TITLE
Crowd controlled

### ISSUE THREAD

**Issue by Solisans** [WeakAuras/WeakAuras2#2145]
## Describe the bug
The crowd controlled trigger does not seem to do anything when used. Whenever I got CC'd (tried being stunned, trapped and feared) nothing happened.

### To Reproduce
I only made a text aura and used the trigger crowd controlled and checked the box for being crowd controlled.
There really is a lack of options so not sure if I missed anything but I dont think so.

**Which version of WeakAuras are you using?**
Weakauras 2.16.6

**Are you on World of Warcraft Classic or Retail?**
- [X] Classic

**Was it working in a previous version? If yes, which was the last good one?**
Never tried it before

**Comment by mrbuds** [comment]
The function from the API used by this trigger still exists on classic, i'll test if it's working or not
