### ISSUE TITLE
"State-Cast "Trrigger Condition not work

### ISSUE THREAD

**Issue by q513902026** [WeakAuras/WeakAuras2#2149]
## Describe the bug

my English is bad,so i use translate software.
When using State - Cast Trigger, I find that the spell and spellid in the condition do not work properly
**Do you have an error log of what happened?**

no error log
### To Reproduce

you can use this WeakAurasString to reproduce the bug
https://wago.io/Ax-5G4CoX
**Screenshots**

![QQ截图20200426140002](https://user-images.githubusercontent.com/3034197/80299423-d250b380-87c6-11ea-8f02-5c296f125db6.png)
![QQ截图20200426140032](https://user-images.githubusercontent.com/3034197/80299424-d250b380-87c6-11ea-83c7-4f90707d5e22.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes, i try only enable WeakAuras
**Which version of WeakAuras are you using?**

2.17.4
**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [√] Retail

**Was it working in a previous version? If yes, which was the last good one?**
working in weakauras 2.16.6

### Additional Info

```
  ERROR HERE
```
i try to fix this bug
https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/Prototypes.lua#L5713
```
      {
        name = "spell",
        display = L["Spell Name"],
        type = "string",
        enable = function(trigger) return not trigger.use_inverse end,
        conditionType = "string",
        store = true,
      },
      {
        name = "spellId",
        display = L["Spell Id"],
        type = "spell",
        enable = function(trigger) return not trigger.use_inverse end,
        conditionType = "number",
        forceExactOption = true,
        test = "GetSpellInfo(%s) == spell",
        store = true,
      },
```

**Comment by InfusOnWoW** [comment]
Did that fix work?

**Comment by q513902026** [comment]
> Did that fix work?

yes fix work

**Comment by InfusOnWoW** [comment]
What's your name?

**Comment by q513902026** [comment]
> What's your name?

HopeAsd
