### ISSUE TITLE
WeakAuras2 on Twitch is Classic Version?

### ISSUE THREAD

**Issue by aerosdarking** [WeakAuras/WeakAuras2#2151]
Weakauras2 is not on my minimap. When I checked it by typin /wa, the chat window tells me "WeakAuras: This version of WeakAuras was packaged for World of Warcraft Classic. Please install the Retail version instead.
If you are using the Twitch Client, then please contact the twitch support for further assistance."

Twitch support button sends a link to this homepage.

This is the only version available on Twitch, and it worked fine on Retail World of Warcraft just last night (4/25/2020) before I updated it this morning (4/26/2020) through the twitch client.

**Comment by Stanzilla** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• [CurseForge](https://www.curseforge.com/wow/addons/weakauras-2) 
    (see the **Recent Files** section, bottom right, for both versions)
• [WoWInterface](https://www.wowinterface.com/downloads/info24910-WeakAuras2.html)
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)
