### ISSUE TITLE
progress bar texture reverting to standard in new session

### ISSUE THREAD

**Issue by ghost** [WeakAuras/WeakAuras2#2153]
I set my progress bars to a certain texture. When I quit the game and restart, the default progress bar texture is being used, not the one I chose. I can then set the texture again (it's still available) but I have to redo that each session. It used to work just fine but since a couple days this bug occurs.

Edit: Might have first appeared in the 22nd April update that I downloaded from Curse/Twitch.

**Comment by Earthling-Z4R0** [comment]
After downloading/deleting/re-installing WeakAuras it seems to be working again now. Coincidentally I removed GSE (Gnomish Sequencer Addon) at the same time. So maybe that was the actual culprit. Will try to reproduce.

**Comment by InfusOnWoW** [comment]
The most likely reason for that is that you are using a texture that is registerd by a addon, but that addon registeres the texture not immediately on loading.
