### ISSUE TITLE
Can no longer get spell ID in aura environment from cast trigger

### ISSUE THREAD

**Issue by leobolin** [WeakAuras/WeakAuras2#2163]
## Describe the bug
After updating WeakAuras, I have noticed that it seem like the Status > Cast trigger is no longer providing the spell ID for the cast in the aura environment. I believe this is a bug since it was working in earlier versions of WA.

I'm not exactly sure which version I was using before I updated today but it can't have been more than a month or so old.

**Do you have an error log of what happened?**
There are no errors. The variable is just gone.

### To Reproduce
1. Create an aura with Type: Status, Status: Cast, Unit: Player
2. Set a text for the aura to ``%c`` and add a custom function: ``function() return aura_env.state.spellId or "NO SPELL ID" end``
3. Notice that ``aura_env.state.spellId`` returns ``nil`` and the aura text displays "NO SPELL ID"

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.17.4

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes, but I'm not sure which version I was using before I updated. I know that it was at working in version 2.14.4 (and probably later versions too.)

**Comment by InfusOnWoW** [comment]
That has been already fixed for the next release.
