### ISSUE TITLE
Weak Auras won't open after error.

### ISSUE THREAD

**Issue by SteveC84** [WeakAuras/WeakAuras2#2174]
Please help.  I imported an aura string from wowhead for a Demon Hunter fury bar... after I got this error, I can't even get into Weak Auras on any character by typing /wa  ….. and Weak 
Auras is not working after this error..... How can I fix this..... I cant find how to delete that import...?  Please help soon, It'll be greatly appreciated. Here is the error.....       

4x WeakAuras\SubRegionTypes\SubText.lua:195: Usage: <unnamed>:SetFont("font", fontHeight [, flags])
[string "=[C]"]: in function `SetFont'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:195: in function `modify'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:572: in function `modifyFinish'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:1225: in function `modify'
[string "@WeakAuras\WeakAuras-2.17.4-21-g9c9d8ee.lua"]:4550: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:4445: in function <WeakAuras\WeakAuras.lua:4348>
[string "@WeakAuras\WeakAuras.lua"]:4480: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:4008: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:4015: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1643: in function <WeakAuras\WeakAuras.lua:1615>

[string "@WeakAuras\WeakAuras-2.17.4-21-g9c9d8ee.lua"]:1771: in function <WeakAuras\WeakAuras.lua:1722>

**Comment by mrbuds** [comment]
can you zip and include your weakauras.lua from the savedvariables folder ?

**Comment by SteveC84** [comment]
Sure... I should be able to. One min.

**Comment by SteveC84** [comment]
Where do I find it?  Do you just want my weakauras.lua from the interface folder?  The only place I see saved variables is in the WTF folder... Please help. :)

**Comment by mrbuds** [comment]
yes in your wtf folder

**Comment by SteveC84** [comment]
Is this what you want?   
[SavedVariables Steve.zip](https://github.com/WeakAuras/WeakAuras2/files/4584328/SavedVariables.Steve.zip)

**Comment by mrbuds** [comment]
The path was given in the issue template
> If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the `WeakAuras.lua` file in `World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\`. In case you do, please export the string and paste it below.

**Comment by SteveC84** [comment]
Here is the string form here... https://wago.io/kib-dh-power-bar ........ 

!1M1dZPkss8VlPQRkDFrEcrnMxDVTknsmMYOEIMTUDRdeKrK7Ha3WGjUxT(zF7zgqab)B2TOcr6P7E6PNUN(xdQIQtuvwPQyQQeOQij0qOb9bG4MHlweGiQdQiwxsvznchy75Qoquvr300MapO7OrW2wwWqGedy6k0nIe8arvj5bL5HbeVvAlTnrXpat6sV3h6g))wZj2Rtn6Iq350jQeAnYLC72zcccL3(Y2z8lhV56oBNPVD23H7HyDnK76KHTxSDgtqyCGHBMoO3eTo9ug1V1)E0WFrE8nBN5HZYdDm5XAYdMipU3GUA)YWX97Cy(gl3vEaWDR29LPSrwICtmGDx5OOl4Jr(m7UArJAVALhXJqxDmwkwfEVJWt24Jymn11MmkMsPB8D03GW3u(Gc(ONJxiMj6)Vato6IZatVT1zYG)TuZ8)raF7Hf26ucBDeHnoLWg5L9psiHCcq7ha84WxB3AIw)HD1KFd2I1Mo4PE9HD6JS3ffJPbbFbHgYrXHShb33Cu3P96er4q)f4JCC6zYwpqaC(5GANjAJBS0Tt6tP2jpu0vATezIrlyLrY97dHNYJ727xLV5uAGFvPY2z(yBxsPSzBh6kYdHCryRnSfzaYbnNusSEUm2Jz7Ls8tGoKQ38bjjEIx(bQwWaI338(AhCaXYN3Q)yzTh6A)81mpxzNR5K6d5AEgt6b5ioKVWGGwth3sR1Or97DSdQkkKkJZV6DnQx9s9KPoTRlImXEfQeSB8fyNP6z4uIxvffeCP2r29PMx70hhQ95MEPQFYqItVHpw(1HVDbB4vQWZ8JwTLVMqK)s2AU6aJpBa6NEpPObZqK9aCda9eAWkpPeUyH9hQkAp2szIMYKwJNKm4imIniBxfiZxTbrWRGkHjWLy8dW4osDo4ezgmig(hTPJ60AICmT0qJaAfcfkAsuvEgP7qwQQ4QVcfzmra842ueBMidyXnHr6z5(JEAAFkgrByiEDnqq6Lcgzba94msHYzOJHF4AVsNcaKHsv3M9)aOCd6dgqu4Evyoa2zmPaK2WinNcxOfJhg7By)KrTBYpNKX7XinMnAw3QUJ)sDMAXq8jbX(zyasJjHA7irBNO4NaCRPqV6J9SWOGaWPIfHBw0Bg0B60Byjkn6nd6nDP8qC3hXwmy3mq52xidRS8YDXcGNvagAh3gwFtbrEdHjOpyWSkLsPc4FQQGeTqEAIwfr0iMOyk7hJiHy3SmI3xB7RiQo41Xb3f4SaxLUyQSQx45tWfp2jxtgdHUvGOlXu7bxwBdzoo6NziWl(efgWL4JpQKQ(guG7NAECzZoHmpaRQ4j0xeRVQ)X5Emx8MqIK3MrnNSaZ5ADFjVN7tBTNysVGvYFFt9L6yE56qa(YH3Fs50)skZ6I2a2B1Fcp7j8Ox0SSZ6tz7Nrr0mhieN73zx1GRi3FNJlDd17Ab72mDDxoNymFCAjbcNw4J52Hhi4quMfyXlSyTKI9SvXYuDoaQJfgS3XLsx9XLx7jGuz)B6SVRiyMH)9CnM)zk7(eNRD524PM9ZfG58LO5)aWQ4BsHTavkdXoQklje)GV91V(UULNGT3x)HTrfZLvyZCfaDWxPiGqFa2gePi7SEAVTZg4HHyiBiWwdIDaOcMCayjVKqvfdpSjclBAbIb1Vhz)bcMnt7aAgWeqH9rlaB4FaqJcqRGyoGnHQcayQLiBRLGwKAeRff7FhXMbByz055Oxe02zTPWcbv(FzbQ03vOU7gQHrqyxDN3IFlL1bfPp)hwyVqxtgQg(BOCqvbrjX6nA2q6(A1R(qt1b3rjc9n8qcD1b1OmtOkbNv6g5eMX3cpxYto6wqo1WPt63BGC8kPnygMypFvLbEUOyQX(Tix9tEuWYYF4tHj(UoSICdxnj(DRoqkJBCmZzPSDgSUNdlwdWjWCgrc8QNjhJkvZroYMX56ufC08CCrGgZXvqwUONNGUOJmC9G2vXclcXBoucu8OFN(tyJ4BpIrW0q9vuiFUwLCTDGKMBGwChdnRu0l7KRdka3xGLV9Inpx6Mx71PtF5ZI73kDZJSgGoo3J8OnnhZ6Tr2l10sivL(3r1cDHvclq31(w3OhlFujOBMCi7jILq7yYU079079zo)48TORXsYktPSDYuof2(Sxq0mCaiMgSdbBZ)ra9xms5ZD841Z29rj4zU1Qx7HQIp0O69nRDNinPIsNM9Zs3PnV04(gqIT49nUtSUk98OiH5CxviJgQTNWvBExnj4ObrPhK49L44PZ(uk0EfDrR5wp9H1OL2ZDqtTPewOpFxlUHoeBwZ002PD0dcyn8cH6oWjhDKFD4GNNsdOOJduHt38ZjhwFokhXuZkZXb9e7sKkKn(82M2TRtEfXLSqb9redDcHpdM2lwyphyztoE9x7xSwi8dY8CzlBAXMKw64VvGKiLt)Dp2XFU3SuIMs9wFYQ(JGamNzuEFHpjoWtRII)6mf(1yYPSSFugRZuM0FlgJZugJTV8hfLSUFQRPNw0UyB(2mpfoFMlV4yMkU8uVu5A86YmgPrPVBBswcmj(aL(Ay8Asqvvk4MEDGGyX)NF)FxP9)cgv9p)

**Comment by mrbuds** [comment]
i asked your weakauras.lua

**Comment by SteveC84** [comment]
Ok. I thought you wanted the string.... sorry.  One sec.

**Comment by SteveC84** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4584393/WeakAuras.zip)

**Comment by SteveC84** [comment]
I found the Demon Hunter power bar now by searching for "fury" in that lua.  Should I just delete everything associated with it, and move on, or are you looking for a way to fix it?  I don't even know if I like the bar or not, because I've never seen it in action. There are more to choose from, I only selected that one because it had a prediction function built in, and I like that on some of my other characters power bars... not a big deal though.

**Comment by mrbuds** [comment]
I can't reproduce your issue, but i removed the aura from the file
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4584437/WeakAuras.zip)

**Comment by SteveC84** [comment]
Ok, thanks. I'll try it with your removal.  I wonder why it bugged out for me?  Any Ideas?   Should I try importing it again?  And thank you very, very much by the way... If you were anywhere near me, I'd buy you a beer or ten next time I saw you.... :)

**Comment by InfusOnWoW** [comment]
We actually found the issue, it was a bug in the latest alpha, which we fixed. You can restore the original auras with that.
