### ISSUE TITLE
Weak auras not working /wa doesnt work I cant open it

### ISSUE THREAD

**Issue by Primordial79** [WeakAuras/WeakAuras2#2177]
3x WeakAuras\SubRegionTypes\SubText.lua:195: Usage: <unnamed>:SetFont("font", fontHeight [, flags])
[string "=[C]"]: in function `SetFont'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:195: in function `modify'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:572: in function `modifyFinish'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:1225: in function `modify'
[string "@WeakAuras\WeakAuras-2.17.4-22-gc31eeac.lua"]:4550: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:4445: in function <WeakAuras\WeakAuras.lua:4348>
[string "@WeakAuras\WeakAuras.lua"]:4480: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:4008: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:4015: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1643: in function <WeakAuras\WeakAuras.lua:1615>

**Comment by emptyrivers** [comment]
Can you uh, provide any more information?

**Comment by Primordial79** [comment]
Sorry I guess my first comment didn't upload. I just got the weakaura companion tried to get the addon in game didn't work. So I went to waigo and copy and pasted a new weakaura tried to import it and these are the errors I'm getting. I can't use /wa /weakaura. I can't get into the addon at all now. Bug sack gives me these lua errors. I have no idea how to fix this.
