### ISSUE TITLE
Change version names or reorder them.

### ISSUE THREAD

**Issue by Blohdridder** [WeakAuras/WeakAuras2#2180]
## Describe the bug

**Do you have an error log of what happened?**

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

```
The twitch app keeps "updating" my retail version to the classic version, then I have to select reinstall and it goes back to the retail version. So I would suggest either having different version numbers, or putting the classic tag before the version number.
```

**Comment by mrbuds** [comment]
**Twitch** is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing **Retail** on **Classic** and vice versa. Ensure that you have got the right version selected. If you do and it still installs the wrong version then you may have to just install manually with the zip.

You can get the latest versions from:
• [CurseForge](https://www.curseforge.com/wow/addons/weakauras-2) 
    (see the **Recent Files** section, bottom right, for both versions)
• [WoWInterface](https://www.wowinterface.com/downloads/info24910-WeakAuras2.html)
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) or [Minion](https://www.minion.gg/)
