### ISSUE TITLE
Target of target glitching

### ISSUE THREAD

**Issue by birgwow** [WeakAuras/WeakAuras2#2181]
## Describe the bug

Want to show target of target's health. Using a progress bar and text. When the health updates the bar disappears and reappears, flickering. 
**Do you have an error log of what happened?**

No error, installed both addons.

### To Reproduce

1. Create a progress bar
2. Go to trigger - > Status -> Health
3. Specific unit -> "targettarget"
4. Make something attack you

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes.

**Which version of WeakAuras are you using?**

2.17.4

**Are you on World of Warcraft Classic or Retail?**
- [X] Retail

**Comment by InfusOnWoW** [comment]
That should be fixed for the next release already.
