### ISSUE TITLE
Target cast bar tracks player casting at <1 second

### ISSUE THREAD

**Issue by birgwow** [WeakAuras/WeakAuras2#2182]
## Describe the bug

Tracking target casting instead tracks player casting, but only when player cast is <1 second remaining.
**Do you have an error log of what happened?**

No, both addons installed.

### To Reproduce

1. Create a progress bar.
2. Go to trigger -> status > Cast -> Target
3. Target anything. Cast a spell, wait until it's 1 second remaining and your spell with show.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes.

**Which version of WeakAuras are you using?**

2.17.4

**Are you on World of Warcraft Classic or Retail?**
- [X] Retail

**Comment by InfusOnWoW** [comment]
!TBvuVnUnm4Fn7H9qhQtBpS9ysQ7LaKZPlY9A7WbLt2s2r7CKcKSttZd3V9rsPK40dy7a2T3gARQIifj1h5hz4j8CoBnNjXFHT(nc3xEulBxXZsUm(55vvEv7t8m4arx7kRB(MwT14HB0YzVgKheBkbX3B1gqW40S80frJSW2kWlrQD2jFWkvC2WhYNZzfIYVu7SDg5yBJ1boilbVr2aA9kA9Ay9xUbDDRtxxRC(GE5hpG2(6gWSEWhDE4)DfQTktlRRQsVJZwoEilFjlF4cq1oVAPOWBDfuSmIZiDHxGWdRDgn6lHRgELmzNl8qyj4dr10mvgrc0oKYJWlfTbGywoZiwRIADiuU3POqHDF6SzGDvfqSLtr9K0z3F3dZiBA69MolsWFyIYw9wvEqfk6ZUasCGeDP1SSShkMqOycHIjekMq6zAvoJO5Jaos5Nb)gMh1RdVYCcdDTNGuJ1aRkHxbWTYuJ1kxDcxwgbEf4FayifZpDrWJRfAZpqZvPnA)QFCgSfldDJ)gKRF9hHCsLhkUaRQ4fNrvEouK3vSqvh5jXYtYpc4oGhwc)bMbmnkrTRDPFLqAF5Pd8PK4X4cN9tBotR)E(bfFbTvnvr(yGIrNIfLycUmW1zdPIuseutQKXwaV76du6N7rYj1(ZoFRU61tSChsNv5uSMnpl9idSRi8aOR9DuqgIclgX3507)6N)9oHeqzXx)C(5i1XG6Idq1lwN8rNaGQhpUJeSv71fne3oaa9BunnllDXYzP3L3Z7m9EGmLm4ac80BrauPqHtwOWbEhFFzsZ)Nj)pntUy67N8VlvcMALsxVcZD3WznwrC8OQKMy210QPU5GILncV)Bo1J(8nh2g7smQrzKXXE3Eln3yOetdkPs(bXoSDsisVZbZncrgB8I00S3Qm0jfu2r9zY73DjmaarjYLy2SZbINIT7ReLQpHd30M6rc3NEy6fN(0fm8cXbiEngLraDxpCJS6X(EtIG1vreLC1Og9(9cNmQZ4)5cM9w76dFndlLHTLBpmx6xV8QlbrAWEzQxaGa39(z7(5KNtvzVdstviAbn9HkmIZ9sO2FaEnrZMvHtHNvLUomlwBqZFQ)9eTuQa6zw6hrMG1PHb1XX9tMVy6FmplF4mYgsDVVdeogo8HJtljRRJ7ooJkueCIjh5C4HC2TQTC2wiiVEach8)6d

**Comment by InfusOnWoW** [comment]
I can't reproduce any issue with a aura created to your description. It doesn't show up on my own casts and correctly tracks target casts. That's both with the alpha version and 2.17.4

You most likely have a second trigger.
