### ISSUE TITLE
WA is unable to track "boss5"

### ISSUE THREAD

**Issue by Jinjita** [WeakAuras/WeakAuras2#2184]
I have WAs that track's dots from boss1-4. However there can be 5 boss unit frames but it bugs out when I try to track on boss5.

https://gyazo.com/5d16cf99a2714618ddbd941d9f80a813

https://gyazo.com/9cdf8767e8616413017a062d29966038

**Comment by mrbuds** [comment]
Please make a proper ticket without deleting the template
