### ISSUE TITLE
Non Dynamic Information for Target Aura Duration doesn't update correctly.

### ISSUE THREAD

**Issue by Jinjita** [WeakAuras/WeakAuras2#2186]
## Describe the bug
Text that displays Target Aura duration that isn't dynamically tracked does not update when tabbing around units. It re updates on button presses.

I expect aura to update dot duration based on what target I'm on.

**Do you have an error log of what happened?**
No it doesn't produce any lua errors

### To Reproduce

1. Created an aura with 2 triggers. SpellCoolDown Progress(Spell) and Aura > Target > Debuff
2. SpellCoolDown is dynamic information
3. In Display Tab %2.p in Text 1 box to display Dot duration from 2nd trigger.
4. Go to 4 target dummies in the Great Seal.
5. Apply dot on one target and start tabbing around. The dot duration starts persisting no matter what target you're on unless you use some kind of GCD.

I apply one garrote and it shows it on all targets I tab to.
https://gyazo.com/56c91c62ff1f67683645bfc81dfb5748

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
2.17.5

**Are you on World of Warcraft Classic or Retail?**
Retail

**Was it working in a previous version? If yes, which was the last good one?**
I'm unsure if it was not me paying attention, but I noticed it like 3 updates ago maybe.

### Additional Info
https://wago.io/Kl_9Q8nDX

**Comment by asaka-wa** [comment]
If it isn't clear above, the issue (I think) is specifically with showing the %p value from a trigger that isn't on the currently active dynamic info state. 

With this minimal example ```!Tw1YUTToq0VMlWDtVW2XiODPtIsJbCL81KPUDdDOLOKyRmPbjLDCwKV9oZq)qjXTOlcGbnXWdhEMZ8qI(cUGTsWkWFW2GnFJY51wJi9J9UOxpb7XSYsVkisH9TAa44H1xkl)xxOEMGjBd1wx26aCfp4HGGLBBSoyBAF63aA9cADiUcqK5hWZ8bPleVyP2O91X9W2OveTjhEJBDYvk(U1kbJD9SKKubBxhQfbn1QnWnUojLNaSZPQG3jEjDoeua5Snf2Tg2wny8k8HckNr281dH9GprrLfp8a6KIkLy5EFa2doDvfCHyuYpAG2sVgewHwp8F7s1gLjWAll1pkylUEeJVGXhndG26vlKl9w3YVyli2qyfS7uYMqDeqlQeWrfTojQAcwFWTRvnnJl2R4ee26g5oGcmdOthpyVdPa6izM6uezyttMmb8SAjWUOkDxYKP3E)K4LpfvyEaYKNlsLaVg8B99Fm(p3dZa5oZ0S7CQbfMq9sLkCocYk0(F0AGARniVm7IfABu8imsKt)q)EurvZ6AjM9oMK5Qhd3O9YLnQcmz)tLA9iqOZdZqHhn5vnLVQed7isvBF(bqdEYAxrfJLyTkivYq8j2QlGai9YHiT0RI5Xof)mL0J4vMke3fh0wJ1OoL5xSV0sbvHqQNUe)eoGuRKAZ7O7o2q(o5qA4GPuxDOhhN1qnwqzYmQxTtlfKow4RLqQ5BD6ZjZ4IG9pd(V1Va31DM80JM80JM8070KNi6tPXr3ZZ2Bf7rWut(CkBXgr9m0rqPRQyE3KioS57VMw)O1h0L76m)XcJbuCITPzPjhNo0Umgc01(lgygzHfz8To9tp)W)3klWYRNFG)sT6nKAR1vm3jbLA(XD0bB0EnuRtZZO4V7e0XPPjZwCvgNN9LzJ)8D8oCGPFc6J6p4Go8M0dckM4ZUNpzme3uUVwPRQdrfelr0D(OrJvsFac73OVj12e0h6RZBKE)BS6rA8kJ4qaLhg9cAdwyHWeSBuBeSnaLhoavtXVc```
I see the timer sticking as I target and untarget the unit with my buff running. 
https://i.imgur.com/qZG7UOm.gif
