### ISSUE TITLE
Progress Texture for Auto Clone Aura Tracking updates every Frame

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#2191]
## Describe the bug
The same trigger (Player Auras tracked with Auto Clone) updates with a different frequency based on display (text, icon, progress bar, progress texture)

**Do you have an error log of what happened?**
no error log

### To Reproduce

1. Go to https://wago.io/TK55KHoxF
2. Profile Performance of different weakauras

**Screenshots**
![image](https://user-images.githubusercontent.com/48932939/81921335-bfb5e700-95da-11ea-81fc-45e4202efd45.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Tested it with only WA enabled. Same behavior.

**Which version of WeakAuras are you using?**
Weakauras 2.17.5

**Are you on World of Warcraft Classic or Retail?**
Just tested on Retail

**Was it working in a previous version? If yes, which was the last good one?**
Don't know.

### Additional Info
Im actually not quiet sure if this is a bug. It could be a lacking knowledge about weakauras on my part. :)

**Comment by mrbuds** [comment]
This is not a profiling per trigger but by aura, and progress texture/bar auras have to update how they are displayed every frame.
