### ISSUE TITLE
weakauras 

### ISSUE THREAD

**Issue by elvanna** [WeakAuras/WeakAuras2#2195]
Just logged into the game after a few hours away, to none of my auras working or even the options menu will not open and getting this message, but seeing as all installs from the twitch app and curse forge website are all flagged as classic this does not seem like an issue I can fix, even after reinstalling the addon
![unknown](https://user-images.githubusercontent.com/57573761/82087874-e06c6280-96e8-11ea-9772-e3e1597e4ec4.png)

**Comment by InfusOnWoW** [comment]
Twitch is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing Retail on Classic and vice versa. Ensure that you have got the right version selected but if you do and it still installs the wrong version then you may have to just install manually with the zip.
You can get the latest versions from:
• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
    (see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like https://github.com/AcidWeb/CurseBreaker or https://www.minion.gg/

Most importantly this is a Twitch issue that is ongoing and a frustration to many people. Don't just fix the issue and move on without contacting Twitch and letting them know how bad their client is.
