### ISSUE TITLE
WeakAuras.lua line 807:    attempt to call field '?' (a nil value)

### ISSUE THREAD

**Issue by mourneris** [WeakAuras/WeakAuras2#2197]
Date: 2020-05-17 16:09:04
ID: 8
Error occured in: Global
Count: 1
Message: ..\AddOns\WeakAuras\WeakAuras.lua line 807:
   attempt to call field '?' (a nil value)
Debug:
   [string "@WeakAuras\WeakAuras.lua"]:807: func()
   [string "@Details\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57:
      ...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50
Locals:
region = <unnamed> {
 0 = <userdata>
 AnchorSubRegion = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:127
 subRegionEvents = <table> {
 }
 Expand = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:825
 yOffset = 16
 anchorPoint = "CENTER"
 GetColor = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:392
 icon = <unnamed> {
 }
 SetOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:329
 keepAspectRatio = false
 SendChat = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:277
 SetInverse = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:433
 toShow = true
 SetRegionHeight = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:428
 useAuto = true
 OptionsClosed = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:713
 Color = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:364
 cloneId = ""
 Update = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:532
 regionType = "icon"
 stacks = <unnamed> {
 }
 GetRegionAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:402
 relativePoint = "CENTER"
 SoundPlay = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:259
 zoom = 0
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:424
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:338
 SetGlow = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:539
 SetRegionWidth = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:423
 RealClearAllPoints = <function> defined =[C]:-1
 RunCode = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:284
 GetYOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:350
 SetAnimAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:406
 ColorAnim = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:378
 SetYOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:367
 triggerProvidesTimer = true
 states = <table> {
 }
 cooldownSwipe = true
 state = <table> {
 }
 GetXOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:346
 SetYOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:342
 SetCooldownEdge = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:447
 color_g = 1
 Collapse = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:803
 ClickToPick = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:718
 GetYOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:375
 SetAnchor = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:317
 GlowExternal = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:292
 SetRegionAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:388
 GetXOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:371
 SetOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:354
 regionHasTimer = true
 subRegions = <table> {
 }
 height = 60
 SetZoom = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:455
 cooldownEdge = false
 SetOffsetAnim = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:379
 UpdateSize = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:281
 SetDesaturated = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:419
 Scale = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:410
 frameId = "kill_command"
 SetIcon = <function> 
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  AzeritePowerWeights, v8.3.11
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  Configator, v5.1.DEV.431(/embedded)
  DBMCore, v8.3.21
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  Gatherer, v7.3.1
  GTFO, v4.55.2
  Omen, v3.2.2
  OmniCC, v8.3.5
  Peggle, v2.2.8
  RareScanner, v8.2
  SexyMap, vv8.3.0
  ShadowedUnitFrames, vv4.2.9
  Simulationcraft, v1.12.5
  SlideBar, v7.3.1 (<%codename%>)
  TomTom, vv80300-1.1.2
  WeakAuras, v2.17.4
  WeakAurasOptions, v2.17.4
  WIM, v3.8.8
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=265)

**Comment by InfusOnWoW** [comment]
Please fill out the template.
