### ISSUE TITLE
talk on canal when bar is show

### ISSUE THREAD

**Issue by Nawake234** [WeakAuras/WeakAuras2#2200]
Hello :)

## What did you expect to happen?
My goal is to display the cd of a spell for some player in raid.
Bar progress "prêtre Amra" follow cd of my spell and have to talk in chat text on show.
Bar progress "prêtre Tali" simulate when other player use previous bar

## Describe the bug
When Bar progress "prêtre Amra" pop up the text in chat don't show! I have to open + hide window's option of WeakAuras for have text send in chat :(

**Do you have an error log of what happened?**
I use swatter and he catch no error

### To Reproduce
1) Use power + shield for start cd of spell
2) open + hide option window
3) text have send (but not in good time :(  )

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
i have try alone or just with swatter absolutely no change

**Which version of WeakAuras are you using?**
2.17.5

**Are you on World of Warcraft Classic or Retail?**
Classic

**Was it working in a previous version? If yes, which was the last good one?**
first try so i don't know ^^

### Additional Info
[weakauras.txt](https://github.com/WeakAuras/WeakAuras2/files/4643227/weakauras.txt)

nice day :)

**Comment by InfusOnWoW** [comment]
This is due to limitations that Blizzard put in place to prevent addons from spamming channels. There's nothing we can do about that.

**Comment by Nawake234** [comment]
hi

really, the addon can't send one message (not spam, just 1) in the onshow event of a progress bar?

i have many addon who can talk and spam in canal like "Details!"

**Comment by mrbuds** [comment]
With Details, when you click on the button to send in a chat channel the list of top dps, the path of execution of this function start with an hardware event (the click).

Without this hardware event, the API for sending a message stop the execution of the function and raise an error.

This restriction was added in patch 8.2.5 
https://wow.gamepedia.com/API_SendChatMessage
https://twitter.com/deadlybossmods/status/1176685822223011842

**Comment by Nawake234** [comment]
thanks for the explication but this addon become useless to me :(
