### ISSUE TITLE
Conditionals not working properly with glow specially time related ones

### ISSUE THREAD

**Issue by frankmolcas92** [WeakAuras/WeakAuras2#2203]
## Describe the bug

I wanted to make an icon glow in certain way aura is on cooldown and another when is active, I have manage to make blue blow on active both cannot make yellow one go away when ability is active

### To Reproduce
Nor total time nor remaining time seems to work
**Screenshots**

![Captura de Pantalla 2020-05-21 a la(s) 03 40 56](https://user-images.githubusercontent.com/37858279/82535981-be724600-9b15-11ea-86e6-450f1e5efb95.png)
![Captura de Pantalla 2020-05-21 a la(s) 03 41 25](https://user-images.githubusercontent.com/37858279/82535989-c336fa00-9b15-11ea-82c4-39a368edc090.png)
![Captura de Pantalla 2020-05-21 a la(s) 03 42 49](https://user-images.githubusercontent.com/37858279/82535997-c500bd80-9b15-11ea-873d-6a04598a1237.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.17.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
No new aura

I will add string:
!TA1xZPnoq8Vo9EOemMKgUz6dHustUHy4qoxUEpOGWw2wnclFsYMqEGp73Us2aHKzUx60oGy1UR(9B)BOb0ykrqJccpF0LxsjgkzqVGV07CkznLKI)hu4LzzzgULg1Ns2E0zwzsHspxjkTuY1tIINSGssukzQAtjzJOIthdcQnw16y(l2hQszwoLu39TwsjfwBL53p7SnSCvpH6SBF(FJ385Rh)LZgbVqIvOkniimwM2chGNktukmf(ZWrVu4SvlYZ5Au9ihZAfGhtR1m0xusaLKZl5ArcPqTzgiXaFFLCdBlq)s2AERdiJLIYNrhNYxvNLfVfie52jtNFZdtbN7(jalBnyNPIlLrGXGLbdhCbiPEfVHxAjGPIxOKNU(ks8tK4RwaWP2WFY4F(X(F9wmbcDgdX1245ULZ1QCn3y2T8te81(nWqK9KkjBlWsIMZKK94GCxcF3YXmTwGx6EX9xoUfX3L2s2OGrNhICf1Z52wCXwzu6v3RsDgvx2clwTv5vWQzjp7CylHNR5octMpz6uNllpkry(GG(7cEU0zQW8Z6sOcObidtk9Ldn8yVZCqk6Zb99LbwUUKj)li9Jz5Obq1ZZCE1vGVtSlWCVdJCz2jfSPCdKc1yf5kkPPZbJCeAbpVTaSTIckJHehdYi)9rDcoX4huYULVrRRvsLUne3hGL7Zq3NdrH2oTpaSREiEwRumkVgWEYJIuBbCLlQ7UccX8uV4Olg21m(Jtb1pHUpr22d0vRGkwESdRrZIMSVqUELNaoZsoc2boyh4GDWjWotHi(gT41Dl)ZAwkegz7wg)2i17a1gLo9rnRIsEC)j3fncJyL0vP55)XtyUlkAYINgploE29lU773gFegiIxXINWU4W7soOs(g4zpep9oG3UAScUiVauleM4jvm34orzUwvxHhxxlTIUXljsMXpkc0aaj5(R((Kt0XYKy7XbLIU4GgW5XE1W(MkUDfZALUYoSk9yRcpYQaWkqW4UUcyCscC323bqTcm9uH4t5roeuHw1pwJgEHirYFqGGPQP6apEJQz(bYVtUx9bFORDudB9Wu0jkGG21H5tnIeCanu0dzWzvDJ(XPnLI1SUxUBtW(z6p1wbZbZH5zTf0LQs4toZWH9a8YCSrj0li(GcGZxZeL)cD3(Tt)ICOB)Jjb6GH57wE6ULR2UB506xGOKz3FSF)5Mn9SBe2KIE2MZK(RpSoEsAURqdGqMiVnQIttGmZg)ueShOtDC(W3egg0mM6Qp5RBWTib9G)bmqLSFq5L9d7dDzI0t34WKvfm3I0mnmBhyjmCW9BFp6nOupvjxVyYKi85)Fh7uJp08SM6)zu6NgN9i2VIyXXUxvQ1qpFVWW2IPXogNkSVzkEsbhwzD0FGackfme6RFf2aW0cK3GKYULVOuznVfcjfSYC(b35VdEQkTQIRHoZJxQyrESxR2nb9ggC(fxEXGVm88(JU0Vx4uzHFGSUOWHxYhYSDTtDjqxhhS445TFR7V8zfEFd4GHdqFq)V)

**Comment by Ganbin** [comment]
I have the same behavior with the latest version of today. Why this issue is close?

**Comment by Ganbin** [comment]
I configure my trinket to show a glow when it is not in CD. It work. However when I use my trinket and it is in CD the glow effect is still there. However, if I do a /reload, the glow disapear and appear when the trinket is available again. Then the bug reapear until I do a /reload during CD.

This show me that the config is good and it must be a bug.

**Comment by Ganbin** [comment]
For classic version

**Comment by Ganbin** [comment]
https://wago.io/CrCSKXN9S

Here the link to one of the WA.

The setting is : Icon with glow activated,
Condition : if in CD glow inactivated

With some help on discord (Spaten), I could make it to work by doing the other way around : 
Icon with glow inactivated
Condition : Not on CD : activated
