### ISSUE TITLE
"Boss" unit type doesn't check auras on boss4

### ISSUE THREAD

**Issue by razko** [WeakAuras/WeakAuras2#2205]
So here's my trigger: https://i.imgur.com/bMgzuw1.png

It works fine if the debuff goes on boss2 and boss3 (can't check boss1, the boss only throws this debuff on boss2, boss3 and boss4), but it doesn't work if the debuff goes on boss4 ever. It simply doesn't trigger.

**Comment by razko** [comment]
Screenshots:

Pull 1, he Gooped boss4 and you can see the WA not triggering on it: https://i.imgur.com/taTX9fx.jpg

Pull 2, he Gooped boss3 first: https://i.imgur.com/vqmciOZ.jpg
Then he Gooped boss4 and you can see the WA not triggering on that one: https://i.imgur.com/1bWnvVh.jpg
Then he Gooped boss2 and you can see it working on all but boss4: https://i.imgur.com/0cz2qLo.jpg

Sorry for not using the Bug Report template btw - I clicked "create issue", then logged in, and it threw me straight back to a page with just the text field so I didn't realize there's a template until I clicked "new issue" again later.

This is on Retail, WA version 2.17.5.

**Comment by mrbuds** [comment]
This is already fixed for next release
