### ISSUE TITLE
Error every time I log into a character

### ISSUE THREAD

**Issue by JeremyMorton** [WeakAuras/WeakAuras2#2212]
## Describe the bug
Every time I log into one of my characters, errors related to WeakAuras pop up.

**Do you have an error log of what happened?**
Message: Interface\AddOns\WeakAuras\Profiling.lua:14: attempt to index field 'frames' (a nil value)
Time: Tue May 26 17:08:28 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Profiling.lua:14: attempt to index field 'frames' (a nil value)
[string "@Interface\AddOns\WeakAuras\Profiling.lua"]:14: in main chunk

Locals: WeakAuras = <table> {
 IsSpellKnownForLoad = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:888
 normalWidth = 1.250000
 swing_types = <table> {
 }
 frame_strata_types = <table> {
 }
 operator_types = <table> {
 }
 CheckRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:33
 subevent_actual_prefix_types = <table> {
 }
 CheckTalentByIndex = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:746
 anchor_frame_types = <table> {
 }
 form_types = <table> {
 }
 UnitCastingInfo = <function> defined =[C]:-1
 spec_types_2 = <table> {
 }
 author_option_types = <table> {
 }
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:84
 tooltip_count = <table> {
 }
 totem_types = <table> {
 }
 pet_spec_types = <table> {
 }
 race_types = <table> {
 }
 ValidateNumeric = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:805
 CheckMPlusAffixIds = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:823
 versionMismatchPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:44
 event_types = <table> {
 }
 CheckChargesDirection = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:835
 subevent_suffix_types = <table> {
 }
 absorb_modes = <table> {
 }
 StopProfile = <function> defined @Interface\AddOns\WeakAuras\Init.lua:91
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 group_option_types = <table> {
 }
 autoeventend_types = <table> {
 }
 difficulty_types = <table> {
 }
 talent_types = <table> {
 }
 EJIcons = <table> {
 }
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 sound_types = <table> {
 }
 GetHSVTransition = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:340
 group_hybrid_position_types = <table> {
 }
 spec_types_3 = <table> {
 }
 text_check_types = <table> {
 }
 class_color_types = <table> {
 }
 timedeventend_types = <table> {
 }
 blend_types = <table> {
 }
 texture_types = <table> {
 }
 IsClassic = <function> defined @Interface\AddOns\WeakAuras\Init.lua:32
 threat_unit_types = <table> {
 }
 group_sort_types = <table> {
 }
 group_types = <table> {
 }
 GetRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:29
 sound_condition_types = <table> {
 }
 anchor_frame_types_group = <table> {
 }
 versionString = "2.16.2"
 debuff_types = <table> {
 }
 text_rotate_types = <table> {
 }
 newFeatureString = ""
 weapon_enchant_types = <table> {
 }
 CheckCombatLogFlags = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:841
 anim_ease_types = <table> {
 }
 anim_translate_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 CheckPvpTalentByIndex = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:763
 hostility_types = <table> {
 }
 aurabar_anchor_areas = <table> {
 }
 printPrefix = "WeakAuras: "
 sound_channel_types = <table> {
 }
 charges_change_condition_type = <table> {
 }
 L = <table> {
 }
 event_prototypes = <table> {
 }
 anim_rotate_types = <table> {
 }
 StartProfile = <function> defined @Interface\AddOns\WeakAuras\Init.lua:88
 combatlog_flags_check_reaction = <table> {
 }
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:81
 dbm_types = <table> {
 }
 multiUnitId = <table> {
 }
 baseUnitId = <table> {
 }
 combatlog_flags_check_object_type = <table> {
 }
 spark_rotation_types = <table> {
 }
 font_sizes = <table> {
 }
 glow_types = <table> {
 }
 chat_message_types = <table> {
 }
 slant_mode = <table> {
 }
 load_prototype = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 PrintProfile = <function> defined @Interface\AddOns\WeakAuras\Init.l

### To Reproduce

1. Enter World on a character on my account
2. See error

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, this happens with only WeakAuras enabled (WeakAuras 2, WeakAuras Archive, WeakAuras Model Paths, WeakAuras Options, and WeakAuras Templates).

**Which version of WeakAuras are you using?**
2.17.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
It was working in the past; I haven't logged in much in the last few months. Rolling back to 2.17.0 still has the same error; I haven't tried even older versions.

### Additional Info

I don't know which, if any, aura is causing this issue; I've attached my saved variables file.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4685694/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
That looks like a broken installation, can you try to reinstall WeakAuras?

You can keep your settings in place.

**Comment by JeremyMorton** [comment]
Thanks, this made me dig deeper and realize that I had a subtle problem my my addon source control.
