### ISSUE TITLE
Progress Bar won't show values after opening WA Options

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#2214]
## Describe the bug

Ok, so now I convinced myself to create a report for this since it's an issue for me for months now on multiple devices (Desktop PC & Gaming Notebook). it can be solved by reloading the UI and does not occur every time but often after opening the options menu. So this is the Issue: after opening the Options some progress bars won't show any value anymore or there are some values missing. The best way to reproduce this is to import the sanity tracker WA (below) and go into a horiffic vision. there you can see the empty bar. after reloading the UI the bar is filled with values like Name, Percentage and Sanity (absolute).
This can also be tested with Nnoggies Interrupt Tracker for M+. Happens very often with that too.

EDIT: yesterday I also had the issue with my own WA that tracks the Debuff "Banish" on a target. There is no custom code in it, just the multi-target-tracker with Banish as SpellID. So it's not an custom code issue.

**Do you have an error log of what happened?**

no log

### To Reproduce

1. Import Sanity Tracker
2. Go to Horiffic Vision
3. open WA options
4. close WA options
5. look at sanity tracker

**Screenshots**

- WA broken: https://imgur.com/a/kNIXTf9
- after reloading the UI: https://imgur.com/a/bFU8XE4
- after opening the WA options again: https://imgur.com/a/yv0k4Hy

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes

**Which version of WeakAuras are you using?**

2.17.5
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Don't know. Issue for months now.

### Additional Info

- Sanity Tracker: https://wago.io/QqZFpQSZ4
- Nnoggies M+ Interrupt Tracker: https://wago.io/SkjHi61Bz

**Comment by mrbuds** [comment]
This doesn't look like an issue with weakauras, you should leave a comment for the author of the aura on wago
