### ISSUE TITLE
Make weakauras grab icons from achievements aswell

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2215]
**Is your feature request related to a problem? Please describe.**
I tend to go to https://www.wowhead.com/icons to grab certain icons that are not available within weakauras like https://www.wowhead.com/icon=2032225 and I'd prefer not having to do that extra step

**Describe the solution you'd like**
After the user inputs a name, iterate over all achievements and show the icons of achievements that contain the user's input in their name

**Describe alternatives you've considered**
https://www.wowhead.com/icons/

**Additional context**
This code can be used to to obtain iconID and achievement name:

![](https://i.gyazo.com/4258bb45ef08cb3995176915f126db06.png)

```lua
for k,v in pairs(GetCategoryList()) do
   local total = GetCategoryNumAchievements(v, true)
   for i = 1, total do
      local _,name,_,_,_,_,_,_,_,iconID = GetAchievementInfo(v, i)
      if name and iconID then 
         --if user input contains parts of av name then show icon..
      end
   end
end
```

According to print, it adds 2902 icons (1963 unique icons after filtering same iconID)

**Comment by InfusOnWoW** [comment]
Well, that's not exactly a PR, is it? Nor does it contain any information how long that fetching takes.
