### ISSUE TITLE
Add a Load Option for Raid Status (Lead, Assistant)

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#2216]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to create WAs for my raid but only usable for my raidlead. Like automarker or something like that.

**Describe the solution you'd like**
I'd prefer a Load Option like the Class Options where you can select whether to load or not load the WA when you are Raidlead or Assistant

**Describe alternatives you've considered**
There are some alternatives as write custom code, but it's often not optimized for system ressources.

**Additional context**
nothing special here, just a load option

**Comment by InfusOnWoW** [comment]
That sounds far too niche and is easily handled in your already custom code trigger.
