### ISSUE TITLE
Overlay cost of Casts bug when pressing spell again

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#2217]
## Describe the bug
Using a Progress Bar with Status->-Power and with "Overlay Cost of Casts". If a spell gets pressed once the overlay works perfectly until the cast is ended. If you press the spell again before it ended the overlay for the cost disappears.

**Do you have an error log of what happened?**
no error log

### To Reproduce

1. Create Progress Bar with Status/Power
2. Enable Overlay Cost of Casts
3. Press a spell again before it ended

**Screenshots**
Can add a video/gif if needed.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
2.17.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
don't know

**Comment by InfusOnWoW** [comment]
I cannot reproduce any issue with that, which class and spell are you testing?

**Comment by Nercus** [comment]
I tried it again and now it works. Don't know why. I don't want to waste your time.
I actually tried reloading, restarting, only WA enabled. 1 Day later and it works again very sorry to bother you.
Keep up the awesome work!
