### ISSUE TITLE
Aura positioning with different screen resolutions unpon importing.

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#2218]
**Is your feature request related to a problem? Please describe.**
I guess this sort of classifies as a feature request and a bug fix. Currently when importing auras it seems they're placed where they would have been on the original resolution. This is great but when going from something like 4k to 1080 aura tend to be well of the screen, this results in users getting confused and even thinking the addon itself or the import is broken. 
**Describe the solution you'd like**
It would be nice to see wa sort of force the positioning of auras to be within the bounds of the resolution on importing.

**Comment by InfusOnWoW** [comment]
This is a good suggetion, though I don't think we want to force the position to be in bound of the screen.

I've seen auras were the group was at a offscreen offset, but because the auras had the reverse offset, they were at the right position.
