### ISSUE TITLE
WeakAuras2 is not responding at all - pls help ^^

### ISSUE THREAD

**Issue by TikTakFlow** [WeakAuras/WeakAuras2#2219]
I followed some advice from Discord to create a ticket here, hope this is the correct place.

## Describe the bug
WeakAuras2 is not responding in any way what so ever (Retail WoW).
No error massig, no minimap button respons (it shows up and can be moved), can't open options with /wa or any other way, no auras loading at any character.
Several small grey squares (one up to five) are showing up randomly on the screen. Transparency and location is switching witch every loadingscreen.
 
Tried running no addons except WA, reinstalling WA, same result

**Do you have an error log of what happened?**
Bugsack gave me this:
https://pastebin.com/6JgVaT8P

### To Reproduce

logging in with WA2 ^^

**Which version of WeakAuras are you using?**
2.17.5
patch 8.3.0 (twitch app)

**Are you on World of Warcraft Classic or Retail?**
- [+] Retail

**Was it working in a previous version? If yes, which was the last good one?**

I am on it to test this, but last time i played on this PC was around February.

### Additional Info

WeakAuras.lua in ZIP

[WA2 lua.zip](https://github.com/WeakAuras/WeakAuras2/files/4707893/WA2.lua.zip)

Thanks a lot in advance, if anybody can help with this ^^

**Comment by zaCade** [comment]
Found out whats causing the error, its the stance/form trigger in `Pulverize Rahmen` because of:
```
["form"] = 2,
```
wich shouldve been:
```
["form"] = {
	["single"] = 2,
},
```
in the weakaura savedvariables, the current weakauras code just doesnt seem to handle the first way anymore, because im assuming it used to.

**Comment by mrbuds** [comment]
You data is weird, there's 212 occurrences of `["form"] = 2,` in triggers that are not form triggers

I tried fixing it, can you test with this file ?
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4708040/WeakAuras.zip)
