### ISSUE TITLE
Additional filter for aura trigger for UnitIsVisible()

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#2220]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a filter to remove units that are not visible (UnitIsVisible()) / in range from beeing checked. Specially when smart group/raid/party unit type is used to stop cheking auras on units that in the raid group but not in the instance or pretty far away.

**Describe the solution you'd like**
Similar to ignore dead/disconnected checkbox add one more to ignore not visible (or some other name so people cold understand what is that for, like far away)

**Describe alternatives you've considered**
Don't see any alternatives

**Additional context**
No idea what events to check besides UNIT_FLAGS that could help there. Might be some fake event provided by WA (like OPTIONS) to check units for UnitIsVisible() or range check >100 every X amount of like (like every 5 sec)

**Comment by InfusOnWoW** [comment]
Yeah it's annoying to implement, but I guess enough people have asked for it by now.
