### ISSUE TITLE
Lua errors appearing after beta installation

### ISSUE THREAD

**Issue by nullValueReturned** [WeakAuras/WeakAuras2#2221]
## Describe the bug
Well the bug is simply triggering lua errors, and i don't see any slow down in performance or any WAs that aren't working.
NOTE! I am playing on the beta client, but I can't guarantee that it's the reason for the errors

**Do you have an error log of what happened?**
```
73x FrameXML\UIParent.lua:5145: attempt to compare number with nil
[string "=(tail call)"]: ?
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\WeakAuras-2.17.6-beta1.lua"]:6266: in function `RunCustomTextFunc'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:267: in function `?'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:33: in function `Notify'
[string "@WeakAuras\WeakAuras-2.17.6-beta1.lua"]:6044: in function <WeakAuras\WeakAuras.lua:6041>
[string "@WeakAuras\WeakAuras-2.17.6-beta1.lua"]:6127: in function <WeakAuras\WeakAuras.lua:6094>
[string "@WeakAuras\WeakAuras-2.17.6-beta1.lua"]:6228: in function `UpdatedTriggerState'
[string "@WeakAuras\BuffTrigger2.lua"]:1334: in function <WeakAuras\BuffTrigger2.lua:1326>
[string "@WeakAuras\BuffTrigger2.lua"]:1644: in function <WeakAuras\BuffTrigger2.lua:1637>
```

### To Reproduce

I was able to reproduce the errors simply by running around doing random things. It triggered both in and out of combat

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes it still triggered with only WAs loaded

**Which version of WeakAuras are you using?**
2.17.6-beta
snippets are legit awesome. 

**Are you on World of Warcraft Classic or Retail?**
Retail beta client

**Was it working in a previous version? If yes, which was the last good one?**
I am 99% sure i was not getting this error before getting the beta client

### Additional Info
I hope i was able to upload my WeakAuras.lua file with this post.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/4746280/WeakAuras.zip)
Ty for making WAs. it's awesome

If you have any questions you want answered instantly you can just DM me on discord
anDe#0001 
but i will try to check in on this post as well

**Comment by InfusOnWoW** [comment]
That's a problem in one of your auras. The function that is erroring in line 5145 of UIParent.lua is AbbreviateNumber, which your version of WeakAuras doesn't call. 

The aura name is not visible because lua has optimized away that specific function. I somewhat suspect the custom text of the aura named "Resounding Protection", or maybe "Tick amount".
