### ISSUE TITLE
Multi textural support 

### ISSUE THREAD

**Issue by thisismygithhubtag** [WeakAuras/WeakAuras2#2226]
Inquiring the possibility of multi- textural support for models within the current infrastructure of weak auras. As it stands concurrently the ui does not support multi textural models when importing via wow model viewer etc... is this a planned implementation? Most if not all of the current models are unsupported and ported blank assuming you can even find the model number or equivalent tag. Also a search option at the very least would also help in quickly finding existing models. If this program could succeed in supporting multi textural models would ensure its survival as many of the ones to come are surely going to be multi textural. Lastly it would definitely improve tenfold upon the program itself being able to use any 3d model from the game to create alpha layers with unique mini maps, and many other possibilities.

**Comment by emptyrivers** [comment]
Sorry, there's nothing we can do to support this currently.

**Comment by thisismygithhubtag** [comment]
Thank you for the response.  I figured as much.
