### ISSUE TITLE
Issues with Debuffs

### ISSUE THREAD

**Issue by Mythogit** [WeakAuras/WeakAuras2#2227]
## Describe the bug
I expected to see an Icon to come up when I setup a debuff. Trigger = Player, Debuff, Aura, Demoralizing Shout.

I am receiving an error that says "attempt to compare nil with number"

**Do you have an error log of what happened?**
Message: Interface\AddOns\WeakAuras\RegionTypes\icon.lua:324: attempt to compare nil with number
Time: 06/12/20 14:18:58
Count: 5
Stack: [C]: ?
Interface\AddOns\WeakAuras\RegionTypes\icon.lua:324: in function <Interface\AddOns\WeakAuras\RegionTypes\icon.lua:323>
Interface\AddOns\WeakAuras\RegionTypes\icon.lua:414: in function `SetDurationInfo'
Interface\AddOns\WeakAuras\WeakAuras.lua:2670: in function `SetAuraVisibility'
Interface\AddOns\WeakAuras\WeakAuras.lua:2525: in function `ScanAuras'
Interface\AddOns\WeakAuras\WeakAuras.lua:1828: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1825>

### To Reproduce

1. Open Weak Auras
2. Click Icon
3. Go to Trigger Tab
4. Type = Aura, Aura Name = Demoralizing Shout, Unit = Player, Aura Type = Debuff
5. Have enemy player apply debuff

This is for TBC

**Comment by InfusOnWoW** [comment]
There's no supported version for TBC.
