### ISSUE TITLE
[Idea] Split Init Action into 2 parts

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#223]
For auras that are always shown, or are always loaded, this is a moot point. However, an aura that loads only in combat or in just one particular encounter may have code it wants to run at the beginning of each combat. Neither the On Show action nor the On Init action is sufficient for this task; Init scripts run exactly once per session (unless the aura is modified, of course), while Show scripts might run too late if the aura doesn't show immediately upon load.

Thus, I propose splitting the init action into 2 options: On init, which runs when the session begins (or when the aura is modified), and a new one; On Load, which is called from WeakAuras.LoadDisplay. 

Currently you can emulate the behavior of the proposed On Load script by adding an always active trigger, and then setting a condition to run a custom action when that trigger is active (so immediately). However, not only is this hacky and invites kludges, it also doesn't work properly, since as I understand, custom condition actions will run after the On Show action.

**Comment by InfusOnWoW** [comment]
How is a OnLoad custom code different from a custom trigger that reacts to e.g. combat entered event?

**Comment by emptyrivers** [comment]
If you can guarantee that those events will fire even if load options restrict to specific encounters/combat, then that's acceptable to me.

**Comment by InfusOnWoW** [comment]
They should. That is the aura should start receiving events starting with the event that lead to it being loaded.
