### ISSUE TITLE
Classic WA: Not working with aBlueShaman

### ISSUE THREAD

**Issue by Kerpzor** [WeakAuras/WeakAuras2#2230]
## Describe the bug

Installed WA and it didn't work. So disabled all addons and it worked. Then I enabled all again, and thought to try to disable them 1 by 1 to find the error one. And aBlueShaman seems to be the fault of it.
**Do you have an error log of what happened?**

### To Reproduce

Described above, disabled the addon and WA was working again. Before when I had aBlueShaman on WA was not working at all. Did /WA ingame and nothing happened.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

Just downloaded the latest version.

**Are you on World of Warcraft Classic or Retail?** 

- [x] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Wasn't using WA before this. Not sure if it's in this version or in older versions.

### Additional Info

The fault might be on their end (aBlueShaman) not sure.
Spoke with you on Twitter and was told to make ticket here.

```
  ERROR HERE
```

**Comment by InfusOnWoW** [comment]
Indeed aBlueShaman is a broken addon.
