### ISSUE TITLE
Options UI quirk with auto-clone

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#224]
What steps will reproduce the problem?

new => icon => trigger
unit => multi-target => yes
aura name => renew
=>> works fine

new => icon => trigger
tick "use full scan"
tick Show all matches (auto-clone) => yes
unit => Multi-target is gone

Observations:

* When you click "Use Full Scan" to disable it, trigger.fullscan is nil instead of false, probably not relevant?
* WeakAuras.ReloadTriggerOptions(data) after UpdateCloneConfig is not enough to fix it.
* Removing a few weird restrictions and setters fixes it, see https://github.com/WeakAuras/WeakAuras2/pull/225

**Comment by InfusOnWoW** [comment]
This is implemented in the new buff trigger 2.
