### ISSUE TITLE
Open Custom Options by Default

### ISSUE THREAD

**Issue by Kanegasi** [WeakAuras/WeakAuras2#2242]
**Is your feature request related to a problem? Please describe.**
When WeakAuras first loads, all auras open to the display tab. I'm assuming this is simply because it's the first tab. I feel this may be confusing to the typical user wanting to use a complicated but popular aura.

**Describe the solution you'd like**
If an aura has custom options, always open that tab first. The last tab open during a session will still be the one open when you go back to that aura, but upon first load, show custom options. This could be as straight as "if custom options then open custom options" or it could be an author choice, like a toggle while in author mode.

**Comment by emptyrivers** [comment]
We thought about this when first designing custom options, but ultimately decided to not do it.

We don’t want to produce the impression that an aura is a monolithic *thing*, impenetrable to the lowly user (though admittedly lots of our users already have that idea). The user always has the ability to edit any aspect of an aura to whatever they prefer, and custom options are simply an extension of that principle.

Putting custom options first gives (in my opinion) the impression that it isn’t valid to change options in other tabs, which might benefit the author by avoiding the “I deleted your code and it doesn’t work pls fix” kind of complaints, but goes against what we’re trying to achieve.

As for your suggestion that this is specifically a problem with complex auras, I would say that the burden is on the author to provide the simplest possible solution, and when custom options are necessary, to provide sensible defaults, so the user is less likely to be confused.
