### ISSUE TITLE
"Action Button" Display Template

### ISSUE THREAD

**Issue by Kanegasi** [WeakAuras/WeakAuras2#2243]
**Is your feature request related to a problem? Please describe.**
In the default Blizzard bars, there is a space open between the bottom left bar and the "new" way they handle the bottom right bar, above the paging arrows. I recently made an aura to populate that spot, but I find it difficult to visually match the surrounding buttons. *This is purely visual and not actually button related.*

**Describe the solution you'd like**
Some sort of visual template for an icon region to make it look like a button, or at the very least, add **Interface\Buttons\UI-ActionButton-Border** to the border options.

**Additional context**
I've been able to get the visual pretty close using the blizzard tooltip border, but it's still a bit off. The included screenshot is my personal battle rez aura using the engineering item Unstable Temporal Time Shifter, which simply shows cooldowns and has the current encounter/instance rez count above it, currently hidden.

![Untitled](https://user-images.githubusercontent.com/2686302/85974555-c8ecee80-b9a3-11ea-960f-a9af6b07b5f8.png)

**Comment by InfusOnWoW** [comment]
If you want to style your WeakAuras in a Blizzard style, Masque has a Blizzard style.

The border styles we have come from shared media, there's no list of borders inside WeakAuras. If you want to add a Border, create a SharedMedia addon that adds the border.

There are also bar addons that can be configured to have more buttons everywhere, which then are all styled in the same way.

And if no of these work for you, then I'm sorry to say that this too niche and we would never get around to implementing anything for that, as most people rather not want the uglyness that is the default Blizzard style. Nor do they put their auras so far away from the center of the screen.
