### ISSUE TITLE
Lag animations on 3D models.

### ISSUE THREAD

**Issue by DygDyg** [WeakAuras/WeakAuras2#2245]
Lag animations on 3D models. On Pandaren will frisat almost all animations for other races are almost the same. Checked on 2 clients. 
https://youtu.be/pGH3bz9_zcQ
https://youtu.be/IRfhrST77_s
https://youtu.be/wcUZ1pKho-0
https://youtu.be/jo6IGwgxMYo
https://youtu.be/od2j0PT6m2E
https://youtu.be/c1v9OlB1Swo
https://youtu.be/guV3gy-KWoQ

**Comment by InfusOnWoW** [comment]
The issue template asks you a number of questions. Not answering them make it impossible to investiage this.
