### ISSUE TITLE
Latest WA %matchcount seems busted

### ISSUE THREAD

**Issue by nedempst** [WeakAuras/WeakAuras2#2253]
I have a %matchcount nameplate/multitarget trigger that won't work or show the number on the latest build.  I reverted back to the latest release. Works fine.

Thanks!

**Comment by InfusOnWoW** [comment]
The issue template asks you a number of questions. Ignoring them makes it impossible to figure out what the bug is.

**Comment by nedempst** [comment]
K will do it later was just trying to help you out....

------ Original Message ------

**Comment by InfusOnWoW** [comment]
You aren't helping if you don't answer the questions.

**Comment by nedempst** [comment]
Are you trying to trigger me?

I get that.  I said I will redo it later though honestly it's quite 
straightforward however I understand I filled it out wrong and will do 
it later.

Take care

------ Original Message ------

**Comment by InfusOnWoW** [comment]
Good, and thanks.
