### ISSUE TITLE
A few Textures that I think could be useful

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#2258]
I've made 7 textures that I think could be useful for use in Auras. 

There's a lack of good quality ring shapes in the WoW UI, with the PowerAuras one being quite fuzzy and the one in the WA set being small, so scaling up badly. I made a few thicknesses of ring too. 

It feels like there ought to be a straight alpha gradient square texture but I couldn't easily find one so I made one of those. Then, since I was making a gradient, I made a couple of gradient circles. 

[Textures.zip](https://github.com/WeakAuras/WeakAuras2/files/4895188/Textures.zip)

**Comment by InfusOnWoW** [comment]
I know you know how to do a PR. I think the textures themselves are pretty good.

**Comment by InfusOnWoW** [comment]
I'll include them into one of my PRs.

**Comment by asaka-wa** [comment]
Ah thanks. Was gonna but didn't get around to it yet.
