### ISSUE TITLE
Bug with "Smart Group" in GlowOnDemand WA

### ISSUE THREAD

**Issue by Hummbler** [WeakAuras/WeakAuras2#2259]
## Describe the bug
The issue I'm having is that my party/raid frames isn't glowing when a certain Buff is applied to them, in this case Soothing Mist. I figured out that WeakAuras 2 version 2.17.10 is causing the issue because I wasn't having this issue with version 2.17.9.

**Do you have an error log of what happened?**
No error log was displayed.

```
PASTE ERROR HERE
```

### To Reproduce

1. With WA version 2.17.9 and GlowOnDemand's Trigger-Unit set to Smart Group, my party/raid frames displayed a glow when I used Soothing Mist on myself.
2. With WA version 2.17.9 and GlowOnDemand's Trigger-Unit set to Player, my party/raid frames displayed a glow when I used Soothing Mist on myself.
3. With WA version 2.17.10 and GlowOnDemand's Trigger-Unit set to Smart Group, my party/raid frames **DID NOT** display a glow when I used Soothing Mist on myself. **THIS IS THE ISSUE.**
4. With WA version 2.17.10 and GlowOnDemand's Trigger-Unit set to Player, my party/raid frames displayed a glow when I used Soothing Mist on myself.

**Screenshots**

The screenshots below are described as follows:
1. WA version 2.17.10 with Smart Group enabled
2. Casting Soothing Mist on self; party frames DOES NOT glow w/ WA version 2.17.10 with Smart Group enabled. **This shows the issue.**
3. WA version 2.17.10 with Smart Group enabled
4. Casting Soothing Mist on self; party frames DOES glow w/ WA version 2.17.10 with Player enabled
5. Message appears when opening WA Addon after downgrading to WeakAuras 2 version 2.7.9. I clicked Repair.
6. WA version 2.17.9 with Smart Group enabled
7. Casting Soothing Mist on self; party frames DOES glow w/ WA version 2.17.9 with Smart Group enabled
8. WA version 2.17.9 with Player enabled
9. Casting Soothing Mist on self; party frames DOES glow w/ WA version 2.17.9 with Player enabled

![1 WA 2 17 10 Smart Grp](https://user-images.githubusercontent.com/68047862/87010060-e297ee00-c17a-11ea-81c8-3602f509cb51.png)
![2 WA 2 17 10 Smart Grp cast](https://user-images.githubusercontent.com/68047862/87010066-e3c91b00-c17a-11ea-9c7e-09ba54feb2ee.png)
![3 WA 2 17 10 Player](https://user-images.githubusercontent.com/68047862/87010079-e75ca200-c17a-11ea-8a0a-39b45459bb9d.png)
![4 WA 2 17 10 Player cast](https://user-images.githubusercontent.com/68047862/87010084-e9266580-c17a-11ea-855c-5609ab9e11bb.png)
![5  Downgrade msg 12 17 9](https://user-images.githubusercontent.com/68047862/87010091-ea579280-c17a-11ea-82e3-2f3593c3b20a.png)
![6 WA 2 17 9 Smart Grp](https://user-images.githubusercontent.com/68047862/87010098-eb88bf80-c17a-11ea-892c-d6d513e61ffd.png)
![7 WA 2 17 9 Smart Grp cast](https://user-images.githubusercontent.com/68047862/87010102-ecb9ec80-c17a-11ea-8970-8016af7a91b4.png)
![8 WA 2 17 9 Player](https://user-images.githubusercontent.com/68047862/87010105-edeb1980-c17a-11ea-88c6-2a775356fbe1.png)
![9 WA 2 17 9 Player cast](https://user-images.githubusercontent.com/68047862/87010108-ee83b000-c17a-11ea-8a18-a3258b353e60.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, as I discovered the issued was with WeakAuras 2 version 2.17.10

**Which version of WeakAuras are you using?**
Version 2.17.10 causes the issue
Version 2.17.9 removes the issue

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Version 2.17.9 was the most recent working version

### Additional Info
!fRrdZPToY)lCZnpYnnumeYxZ07Mecjp6qjCXKxED68myWcqVASySLjL2P8B)2vYsw2yhiTDMlKj4iTFVRwTYADSCg6ytD6FA9tB1QUJDKJDJAwNv7ch7Lo2E4VaaSyUpnG4yF)Jd71TFhh75(SNDMaWtwUMe6yBvRETMo2CYx4w3Yc420VsC6B1WX2nMVGfE)koLfebeRVGL8nRii2(KPCGjKzUX(CCo7pt2ij)qbibUlH)Eh8)BhlhzTRFmjHs29zHlD9D6dmAa9le4jqkSxGclq3NPE8fiCCeIu2UYDQGqHu3j(KNeqDDwWBMcoNnFUpjvkNKiKmqZdPEK2mFLCEFYqBhlLyykwC4)jlPpjL0tH5dtPSqNWFBi(BtXFprIwQHXGFMCjltALYeps00qQWbi9qo2BFp(ryXuIAeHZPbZJU0XEMYbAVK4rJxQPCdKYNIuEjnqy)LCi0nyUHbQ)5jsBq8YEGRacQw6(fa96k5UF8YjKWTJzZ2o2xcreNSsqstT4mnVQxRERYyx9AnALWXvOkzVIq8s4PvTwkMMmSKrs6zYRZ3VE1iHl8f0PFgKALIzPvSHPZuOcDX(dReQW1SqpCDvIKVa9qteJLlycyT2evQ9XKY)59ZMTJy)NBhdddHaLi2ww734yzYLpwex(4(4sJdiOvS4(veUA1C)I(jPXR3fYIxTRF1mGTYk3qoDQpPY2XZtaVy95Kdm81sh)gHA3pw8RvldUTxVu0uxm4tWJuoihuXH8QZPVUuOwND4HMc9(hl088xjx(XcnVyVHM7jqe3MJgTY3DZqjkJH0)XrC2YHgr3L9XXEtI81)4MNwRo8tZ6TSoR1zqUw3GPWwSdy0aGoT70FyNhKcwJCJj3U5f3LjvKECLNlh0Ly13HW2ol48vrx(23(S7Cwnk7T4Eh3hCdzPBG3BBagn3PQn6bdjSobFqsthBFgeFTD8SqWKVD872o2no0DejyDT7i8BXrRQhbqMtQfhq5hT990zAS4libGbzS8JgCCFrBKFvfW9gJPM6ZciD9aYqcWcAyJsKNRr9LcCWugp(1(d6DsumuigHXizvUPSGz051u10yGqV23jaThDInpEs1kWdTfccAxpgkQQci27QKcKMfhiS1AnovrvMh0UzkuawnZBcvFazP2vXCwB3ioY9rLzot1gOUJcMrNeTG5stVv0Ky2NYqcZnu2CFuo3U6pXpIuGnOXlzdeff9ZAaev9uWuPLNatgqlcBDTfLHEjwc92UfmNSYHsnr7AiEI4(5RaIevdl9aRQfYBHgL9zomPCGNyjhgVFibI5cZzRKln2nSeM59hQNTCIA6NvuCF4LAw(DOiFdZIwrp(N(N80aQpNeqcPtXhKzj3o(zkFb4nDNcH)Z3o(Gi0pQWKY3OQWkI5emJmo82XHeECyayZXAaKfh56RYWhbFZGsMWC4VtIiacmW3(Ua)mKUmkZWA9ss9xm1GvrkKW5sG11ZJbOVkKYcP8nqQqqCG6bG1LEkZNKUJuWmwrgmUIYrZBWVbFb4aO4AsSvUCojmaxIIakpgRagOYdp2YTJx6Yt8nsbss60m)zzTi46BPrFiWHUupTLupZNS(lbWv2(9)WZQYBKWUoEHhZaOgAG(DIR)egxb4c5)AaAtnO3bhCTN7g4S(kONdJya6jzaTXUW2Wa4wAG74V(XBh9aOoITfuiq8xBa(PAWzaWt8qoOGCIxob5mtGR9VqlLwmuRvGzmW4Cng9OljzKdF6sJ19F6cnK2pEly9G8MM0pkEMPZOUg62SLqjX8hmGDIp9RFnRtfp5WMI8Qw7YwbSsALJRnYzBhGq(cgxRMznyguUulMvQ3EaLFDSV)jJKBRlzNc9vu(eCstuBL3QKbJImlqAu80vjRvsP0PMMLhHL3sibsza0z7kPY0vJgua0NN34vamxKZETlins98sci4icY3Xv5pD1iDsZ2qwAzfHfmQkFiMZjawyUlm9OWbscqRt2D2Ebabw1oKa1pltTwrkBgBnRscvSuPjKg(zx(azooAyN1KaE1kd6D1h78WOh6CxN(JUPR9vx3RZnMC4LXOt)9JWDpC)Jdg9W92Wjxg94GBUAyNSWBt42IZHvTY9bcKWimDvXqszSuicob8DTA1oA36Ck1ykZi)9mvZCKExEL9lHxfUdzEBTg2BH9tUoMZHtjDlledQ1fvTdY5isijcopB0ocNz9(yXqscEKSMOkIDNRaBpH7JjcYetFzxK)tOEEKGQhvwjX5Ka9PBKKa077N83WMF4bBQ(cgyLKLisYisz4VXWsZsL9jl6yae9rVb2O1h0mkyBPRCPHrv)Mw6AJZfIk43bv0CtYdK4RLews3cCDcMN66ELmr9HtdIiWHnsCWa9wF0Htfzu5pdqV4K58DVsNusGdwBw2aNR48q6KyoP6VHt(BhGcJsIKqIyzvy8FqJOqiogeBmoWI(y6VJoujT0KbFsqqzcFb7pysHcmgM0nseSGiBSm)vkxz2XmKIjjV9sroVS67r)kI)sYG8)7yWchuD4av6W3xm0zEniI8EOtOZxGDzsZtxIpqNjvdNi2pcczdMRYLkN7s8acWgCYIe2RxvD2L3Po3q1tFd46KO3nyg76n39y3BQQtOSRnPWJSN34u0(dzSp4)mUiZ1E2SrKyuTJLC1yAgYDw7uscXJpojcEwiECj8KSKdmw(NAnL(njwCgiHxwQth2AZx)cNx27L6fF5D6Z)zcuV3N)zwBvYshv00)qlq)7TJRNe)RhdJikyVXh7cf(ll)sxzt2kOOryr4DfQz3OR88UpOhdo8dSEsmbwX3ofq90InWKWFRM3wlo5UIKPBfu82cjRBvNdOsMDpQHhCgFjbfhgOmlzGDpVtTm4u8RjB77t1YDF34LwAzYBB5DVyDO6KGkWfAMwQWxJs2GaX6C67SEZ)i)lROOf0jLlLyVttii52EklcLTQ5x5l9pz59NO)1bVTPsZkpC5NCvsjmi6tw)vjx2aOr0Of)sUsKDEbLLFXh5fdqqG8EZNtcn6hd5a4Ji(4LIPAXcBgJlFvwFa25uChrSLtObKbeXYC8A)yphCFG)g8re1ruyFmjLCSJINioe2GqYm6xa6nOtVEo2XrKrCgZNtxHx99K4zZeVR5a8A6WVVcwiSMOmvJsU3r0gOUrkpcILSRq(9o9gC7J9Ki3g18iuAaUGHtjposIrBF3OiKPXbcjduF6sXvRMiQ2aqOOoQ9v2dhzp8QhgkvmLnza7z8G2pXc9UC7y7fuIVhAzsiNmHaiGGbqEnHaoIRkw4tqPrQoOfQbEBQeF)UErQRM7mKwG8kEHlJMYIdeThaSh50pNEHCjUHpGVQrrhuaAEpqWIKipcO6u6m60ryiJuDHVLYHGbbPEDEAlYKgjKAYJJKK01)z3nqrqXslQY85gZz51w5RvQyxQuqKVwfTrRnlWJkV8WYIzEr)dkFXY4Xcuo8Yx)BrYvuaC991x1PeSES50PQlY1vawYmFG5rC6FSvDKkrlC9yp)r9DXAL0ZtDcWdz7HwLVONS1jne3u7fwTA14SMo2pdXlpf6UYX(j9tOTBjy3MkVdD7Re2s6uWoEDYT4InuLJ9TH0VUD8)n21dmZUBhpuCfR0PFEZnkdVOHS8NL7wFNvk6RHuaiE9ByzWQB9DNhz0Rxli05lenbsTlGFADE9MN3SjE1P4lb31)p0u5cmHMROLX4U(GJserTeksGQCdOxcdBcrHvc0oWmvS(m)OEuWPpfgzZotfInJq(bHuwIi98JptEf17moUCzxkZ83LYRwVQejpcV9)CdYtcrG4BUlnyPiyVBF7U30bV6E6sxL4OVWC5cVamvHEvLkbibImGmf2e3icSyLemh7WGMYbgMIih7XbAWVqYLU71VgcYn6ycrRckIal0mjmGf0GdwT3Fhn4rIGeyHykZjgDOyXRi0tNFrqizoOKs5x2ZhttZxHoA7rI3ZMOPj1lLK6wJtG4Ekm(Jpn8R9gmPXhwAR129k)crYX(FgOBGKUyYH(NFIvZZprLs6pvzDuRKbmGSl)nKJJoBJJDVo3IQhBQEnpSmUEDyzINSncvDXbQymFGIbytGCdnsMydmDIcmaxkySWgzlPTtefPiTl2TFOtN(jBhmryHMrNlIS1nEd2loQMy8fvBDlGIAKSBLWNsBrR(NKPDPuTrvAV5HTRNUdeXEsmT)3qPWSp7My22AiBm6JWK2lmTdLqKn79ZjYSnOHveI9vguOfcK0Zy6IRl016cDTEQUcBMr8EkPxHqNIWdQ2tzIUpIovKa(8tp9KZB16ItruxJTzwdKko)V)

**Comment by asaka-wa** [comment]
See #2255

**Comment by asaka-wa** [comment]
I'll also add that you commented on my Wago regarding this issue and I replied. You should've continued that conversation, where I could've let you know about this instead of you making a duplicate ticket.

**Comment by InfusOnWoW** [comment]
That should be fixed in the latest release.

**Comment by Hummbler** [comment]
@asaka-wa My apologies. I submitted that issue before I figured out the patch was an issue so I thought this was the proper place to submit the bug. Thank you for the assistance.
