### ISSUE TITLE
Rake ability DoT effect

### ISSUE THREAD

**Issue by NotaBeneRnD** [WeakAuras/WeakAuras2#2260]
## Describe the bug

Wrong time for druid Rake ability DoT effect (12 sec instead 9 sec).
WoW Classic version.

**Comment by mrbuds** [comment]
Aura duration in classic are handled by LibClassicDurations, please open a ticket at https://github.com/rgd87/LibClassicDurations/issues

**Comment by NotaBeneRnD** [comment]
Hi, I'm posted ticket at https://github.com/rgd87/LibClassicDurations/issues & they ansewered, that in lib is all OK. Then i checked string in my ...\World of Warcraft\_classic_\Interface\AddOns\WeakAuras\Libs\LibClassicDurations\classAbilities.lua
Spell({ 1822, 1823, 1824, 9904 }, { duration = 9, stacking = true }) -- Rake
It's looks like right, but problem still ingame. Please, look at this:
![WoWScrnShot_071020_094716](https://user-images.githubusercontent.com/68054544/87126119-52e66280-c294-11ea-88e1-ea779f8dcd1b.jpg)
![WoWScrnShot_071020_094655](https://user-images.githubusercontent.com/68054544/87126191-73aeb800-c294-11ea-84b8-dcd153a17b7a.jpg)
![WoWScrnShot_071020_094703](https://user-images.githubusercontent.com/68054544/87126194-75787b80-c294-11ea-8236-83eca4f0575c.jpg)
![WA2](https://user-images.githubusercontent.com/68054544/87126420-d1430480-c294-11ea-871e-5fdf3dd635eb.jpg)

**Comment by InfusOnWoW** [comment]
WeakAuras does absolutely no duration calculation. We simply use the value that the lib gives us. So I doubt that the bug is in WeakAuras.
