### ISSUE TITLE
Threat Situation status as condition

### ISSUE THREAD

**Issue by caspervk** [WeakAuras/WeakAuras2#2261]
Please add support for accessing Threat Situation status in conditions. My use case is a progress bar, showing my current threat percentage, and then playing a sound ("aggro!") if the threat status changes to 1 (higher than tank) or greater. Therefore, not only accessing the value, but comparing it like "if threat status > higher than tank (1)" is important to me.

Currently, the alternative is to create five triggers; one for the naked threat situation, and one for each of the four threat statuses with additional constraints on the threat status, and then checking "if trigger 2 is active" etc, but this doesn't allow for greater/less than comparisons.

**Comment by caspervk** [comment]
@mrbuds @InfusOnWoW would it be possible to check greater/less than for threat status?

![image](https://user-images.githubusercontent.com/2924482/87167938-0455ba00-c2ce-11ea-8c63-a317b5bad8b6.png)

**Comment by mrbuds** [comment]
Please open a new ticket if you have a new request.

**Comment by caspervk** [comment]
Thanks for the quick response. It was part of the original request;
> Therefore, not only accessing the value, but comparing it like "if threat status > higher than tank (1)" is important to me.

but I've opened a new ticket [here](#2266), as requested.
