### ISSUE TITLE
Cant open options.

### ISSUE THREAD

**Issue by Maybeear** [WeakAuras/WeakAuras2#2263]
## Describe the bug
Cant open options.

**Do you have an error log of what happened?**
From buggsack, 

1x WeakAuras\WeakAuras-2.17.11.lua:4732: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@WeakAuras\WeakAuras.lua"]:4732: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:4690: in function <WeakAuras\WeakAuras.lua:4593>
[string "@WeakAuras\WeakAuras.lua"]:4725: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:4253: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:4260: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1695: in function <WeakAuras\WeakAuras.lua:1667>

[string "@WeakAuras\WeakAuras-2.17.11.lua"]:1823: in function <WeakAuras\WeakAuras.lua:1774>

```

```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes, i have tried everthing execpt reinstallning entire game.

**Which version of WeakAuras are you using?** Current release

**Are you on World of Warcraft Classic or Retail?**

-
- [] Retail

**Was it working in a previous version? If yes, which was the last good one?**
yes, did an uppdate on most addons, Use Elui and some other.

**Comment by InfusOnWoW** [comment]
There was a version a few versions back that on downgrading corrupted your settings. That very much looks like that error. In that case you need to restore from a backup to fix your auras.

There's a way to delete the broken auras, but restoring a backup is better.

**Comment by Maybeear** [comment]
Ok thx, how do i do that? I have no problem deleting and starting over if that makes it easer?

**Comment by Maybeear** [comment]
Nevermind, i deleted the saved variables, thanks for the quick respons. 
Cheers!
