### ISSUE TITLE
Threat Situation status condition comparison

### ISSUE THREAD

**Issue by caspervk** [WeakAuras/WeakAuras2#2266]
Requesting support for less/greater than comparisons of the threat situation status in conditions. Currently, only *equals* and *not equals* is supported, so the current workaround for implementing e.g. "if threat status > higher than tank (1)" is an "any of" condition checking for each status value higher than the desired one.

![image](https://user-images.githubusercontent.com/2924482/87170688-f73aca00-c2d1-11ea-8726-3eda90b741b3.png)

**Comment by mrbuds** [comment]
There is a "aggro" condition added for next weakauras version.
