### ISSUE TITLE
"Trigger Active False" conditions not running

### ISSUE THREAD

**Issue by jcai1** [WeakAuras/WeakAuras2#227]
What steps will reproduce the problem?

- create a new aura with some trigger
- add condition: If [Trigger 1] [Active] [False], Then [Chat Message] [Chat Frame] [active=false]
- activate, then deactivate the trigger.
- see import string at the bottom for an example

What is the expected output? What do you see instead?

- when the trigger deactivates, "active=false" should be printed in chat.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

- no

What version of WeakAuras are you using?

- 2.4.7

Was it working in a previous version? If yes, which was the last good one?

- unknown

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/run scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```
duZZcaGArv16fszxkLABiWSPQBQuXTrLDsL2lSBb7xPWWeLFJIHkK0GvQYWfQdjQuhJiNJIyHIQyPIQYIfv0Yf5HcP6PQwgr55u6YKMkstgvnDPlkK4Xu4zcX1rPnQuvhMWMruBNkopf1Pvmne67kf9nIkFwjJgrgVsLoPOkDlksxtuj3JOQ)IGgNsjVwuHHeO4C4848GItMj0prtHBez48Jn)SbJookUW7X5hBSxyMQ7wCHrhhfxy0XrPPzT00om8kCnvkdF4XZnnkNUXEgmb(PdtaNKolsf7tmxzriiltUmjjjzrKLbYMsuo8MM1stGIxZXkU6OHIZPwRyPeYeRjrzs4YlpopBs0HjGhbxD0qXJojr3yVDuRvSuCo1AflfVQT4SwLqo1Aflf5bNnOoAO4D4uEu8nh(sc7tWwMqGerzBfHOjMijLreKnLib4bwoAAwlnzHRe(eMsOTIuvE4kHBWe4NomblOWvcuCdsQroafVPzT0eCZWDePrKtVIBjXSjUJWZQWndf3GKiSulOWvcuChHNvbfNtTwXsjSMJv8OMV86sX5uRvSuCHrhhvEYcVvrXJtmXAQMXnijkkkkkUNrWdkEfEnuzGIZX67akkkEfEnuqX5y9DafffNFitEmy91mO4CS(oGIIINegkO4CS(oGIIIh7exHxdfuCowFhqrrXtmEfuCowFhqrrXjlm6WeafNJ13buuuu8KUgMa1CSIxD3IIBXLTnXTLd3bUseLjHca
```

**Comment by emptyrivers** [comment]
This is due to the fact that conditions are only checked when the aura itself is shown. As a workaround, add a status - conditions - 'always active trigger' trigger, and ensure that it's included in the trigger activation logic (or just use 'any' for the activation requirement).

**Comment by jcai1** [comment]
Hmm, I see. That's not really a great workaround though, as it would cause the aura to be always active. That would be undesirable if the aura had "On Show" or "On Hide" actions, or if it were part of a Dynamic Group.

**Comment by emptyrivers** [comment]
On Show and On Hide actions can all be replicated in Conditions, and if Dynamic groups are such a concern, then you can shunt the conditions into custom scripts that don't rely on the aura being shown.

I'm not saying I necessarily disagree with your assessment of this not being a good workaround, mind. Just providing an alternative viewpoint.

**Comment by InfusOnWoW** [comment]
That's by design. Conditions are only checked for visible auras.
