### ISSUE TITLE
Scaling Fix Doesn't Work With 2.17.12

### ISSUE THREAD

**Issue by zaksquatch** [WeakAuras/WeakAuras2#2273]
## Describe the bug
In order to get a pixel perfect setup, I've been using a scaling fix that was originally discussed on Reddit here: https://www.reddit.com/r/WowUI/comments/95o7qc/other_how_to_pixel_perfect_ui_xpost_rwow/e3uhcky?utm_source=share&utm_medium=web2x

I've been using this WA which has worked fine until the recent update: https://wago.io/hYA8lkFY-

Upon logging in with the current version of WA, the scaling is all broken, thus breaking the arrangement of all my WA's.

Ultimately, all this is is a WA that runs this as a custom function:

local scale = string.match( GetCVar( "gxWindowedResolution" ), "%d+x(%d+)" );
local uiScale = UIParent:GetScale( );
WeakAuras.frames["WeakAuras Main Frame"]:SetScale(768/scale/uiScale);

**Do you have an error log of what happened?**

```
I have error reporting on and use the above two addons. No errors reported.
```

### To Reproduce

Updated WA via the Twitch app, loaded WoW and the scaling broke.

**Screenshots**

No screenshots as it would have required a before and after comparison.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, I turned everything off but WA to test.

**Which version of WeakAuras are you using?**

2.17.12, worked without issue in 2.17.11

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

2.17.11

**Comment by InfusOnWoW** [comment]
As far as I know nothing has changed that could have broken that. Do note that this kind of dirty hack is not supported by the WeakAuras team and thus you would have to contact whoever came up with that idea.
