### ISSUE TITLE
Vehicle - Causes WeakAuras to disapear

### ISSUE THREAD

**Issue by Luxthos** [WeakAuras/WeakAuras2#2281]
## Describe the bug
When entering some vehicle like the Tomb in King's Rest or the Canon in Tol Dagor, some WeakAuras will sometimes completely disappear and won't load again until /reload or /wa

**Do you have an error log of what happened?**
No.

### To Reproduce
https://clips.twitch.tv/QuaintGrossJellyfishTooSpicy

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but I'm not using ElvUI or any other big UI interface and it seems to happen to everyone using my WeakAuras package.

**Which version of WeakAuras are you using?**
2.17.10

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I can't remember which was the last working version, a lot of version came out since I've received multiple bug reports.

**Comment by InfusOnWoW** [comment]
You need to actually include a WeakAura that shows the problem.

**Comment by Luxthos** [comment]
From what I understand all of my WeakAuras currently suffer from this issue. Here is the Ressource group used in the Twitch clip:
https://wago.io/H1alybdVQ
