### ISSUE TITLE
TSU - Complex Custom Conditions cannot be assigned custom events

### ISSUE THREAD

**Issue by Sallena2** [WeakAuras/WeakAuras2#2284]
## Describe the bug
Assigning a custom event (one triggered by ScanEvents somewhere else) to a complex custom condition causes a lua error ("attempt to register unknown event")

**Do you have an error log of what happened?**
1x WeakAuras\WeakAuras-2.17.12.lua:1420: Attempt to register unknown event "TEST_EVENT"
[string "=[C]"]: in function `RegisterEvent'
[string "@WeakAuras\WeakAuras-2.17.12.lua"]:1420: in function `RegisterForGlobalConditions'
[string "@WeakAuras\WeakAuras-2.17.12.lua"]:2370: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-2.17.12.lua"]:2212: in function <WeakAuras\WeakAuras.lua:2096>
[string "@WeakAuras\WeakAuras-2.17.12.lua"]:2319: in function `ReloadAll'
[string "@WeakAuras\WeakAuras-2.17.12.lua"]:1952: in function `ScanAll'
[string "@WeakAuras\WeakAuras-2.17.12.lua"]:1898: in function `Resume'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:198: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:174>
[string "=[C]"]: in function `Hide'
[string "@WeakAurasOptions\WeakAurasOptions-2.17.12.lua"]:1423: in function <WeakAurasOptions\WeakAurasOptions.lua:1421>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>

### To Reproduce
Example:
https://pastebin.com/FLB2dPqa

Uncomment the "TEST_EVENT" in the custom variables for the error,

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
2.17.12

**Are you on World of Warcraft Classic or Retail?**
- [] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Don't know

**Comment by InfusOnWoW** [comment]
Conditions only listen to in game events.
