### ISSUE TITLE
Missiong Option after Update

### ISSUE THREAD

**Issue by datyin** [WeakAuras/WeakAuras2#2290]
## Describe the bug
After updating weakaura to 2.17.12 option to change decimal of %p display text is missing.

**Screenshots**
[Imgur](https://imgur.com/vgttZbO)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, no effect

**Which version of WeakAuras are you using?**
`## Version: 2.17.12`

**Are you on World of Warcraft Classic or Retail?**
- [] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes it was, not sure which was my last version

**Comment by InfusOnWoW** [comment]
It has moved to a setting directly below the text entry.
