### ISSUE TITLE
Shadowlands base install not working.

### ISSUE THREAD

**Issue by freernnur5** [WeakAuras/WeakAuras2#2294]
## Describe the bug
Blizzard just enabled addons on the Shadowlands beta and I wanted to test out some WeakAuras. I had copied over my live folders, but was getting an error so I did a fresh install. I get a LUA error upon logging in. I cannot open WeakAuras. Note that the below error log is best that I can get as BugSack and BugGrabber seem to be broken as well.

**Do you have an error log of what happened?**
Message: Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua:52: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua"]:52: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:590: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua"]:1269: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4820: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4715: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4618>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4750: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4278: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4285: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1695: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1667>

Time: Fri Jul 17 14:12:58 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua:52: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua"]:52: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:590: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua"]:1269: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4820: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4715: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4618>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4750: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4278: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4285: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1695: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1667>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1823: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1774>

Locals: <none>

### To Reproduce

Login

**Screenshots**
Not sure if needed, but I can gather one for you if that helps. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Everything is disabled except for WA, WA Archive, WA Model Paths, WA Options and WA Templates.

**Which version of WeakAuras are you using?**
2.17.12

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [] Retail
- [X] Shadowlands Beta - version 9.0.1.35213

**Was it working in a previous version? If yes, which was the last good one?**
Not to my knowledge

### Additional Info
I have no WeakAuras setup at the moment as I wanted to make sure those weren't causing the problem. If you'd like more information from me, please let me know.

**Comment by InfusOnWoW** [comment]
There is no release for shadowlands.

**Comment by Stanzilla** [comment]
..yet!
