### ISSUE TITLE
Icons move up or down after loading screens

### ISSUE THREAD

**Issue by Excalithor** [WeakAuras/WeakAuras2#2295]
## Describe the bug
Created Texture Icons to show in certain position on screen when I have a primary or secondary stat procc.

Positions of icons do not stay in place, they move 5-8 mm (on screen) up or down. 

When I start up the game, all icons are in the position they are supposed to be in. Then, randomly, the icons move up or down a bit after loading screens.

Example:

start up game - hitting training dummy - icons in original position - enter BG (isle of conquest) - icons in org posi - leave BG - hitting training dummy - icons now in in higher position - enter BG (battle for gilneas) - icons in higher posi - leave BG - hitting training dummy - icons still in higher position - enter BG (wintergrasp) - icons in org position again - leave BG - hitting training dummy - icons now in in higher position again

Quit game

start up game again - hitting training dummy - icons in original position again

Don't use elvui.

Using latest WA2 (release type) version, 2.17.12

WoW Retail
<img width="284" alt="Icons in Original Position" src="https://user-images.githubusercontent.com/68453668/87843525-9d04bf00-c8f8-11ea-88a9-004e0714153b.png">

<img width="302" alt="Icons in higher Position(changed after loading screen gettin ginto BG)" src="https://user-images.githubusercontent.com/68453668/87843524-98400b00-c8f8-11ea-8c88-d15a888d2de6.png">

For some reason, these icons move 5-8 mm up or down on screen, usually there is a change when I go into a BG or leave a BG, but also restarting game has an efect and an change position of icons.

Most of my other ones seem to stay in place, not sure what this is all about.

Anchor „center“, anchored to „Screeen/parent group“, To screen’s „center“, Frame Strata „inherited“

I think thats standard for most of my weak aura icons I get displayed. some seem to move now and then for some reason, some dont.

They are not “actively moving up and down” during the game activity per se, its like after I enter a BG or leave a BG (so after loading screen) that they are suddenly moved up a bit, or down a bit. Probably same with other instance types, havent tested yet.

Seems like its mostly the “texture” ones that move, looks like most of my “auto icon” ones remain in place.

 In case you do, please export the string and paste it below.
-->
Sample 1:

`!Ts1YUTToq0FNUjbIsuu2lDtTBdGJIHPA7Tag0HrIsMnYKgKuopwKV9odLDYTTBlGH1OrZC45mpOGiQeCTOmDkRGKqfCVGNEjP4ssQGVxWBWFqibB9rLZRTgr5KKSKeb)PBBB9QGybDcJLtj50SICcBsIO9c6ubxoe2zD3Eiaj5bmcGR(d7KIscaT25SoXhf8NFdMcgllHKLKc4NLvGWua5yQbywz1gaGRMxwnFTGxB7HSRqOwqZtjPSKjjPzftlMMc5LpbuKybllh9MaOrz5tIFHkkZelYz5K8cwss60cAbfPCotucFm5YICKQ33Rmn3yBuc(hxoV8tcUt1bkP65dGRG6PWGdnC6UoOWmYLQ3CGMdEvPCVcfPCWjnG9P44lhQ1nVE3NCk5EpECQJkuFFrj7d7GUWW9rpRCQw9tcoF18Llb3hu99x3CQAEoi(qBmOTxnJxTLxnBnE4gneYHE5Zaz4NpBWvikaKqqhUrDpK8OM(Y8LRw81LymdM3Lri24Qd6JQQrNXQs5fKe8l1wtJ()3IRp)c3hKUaA0y36TdMgSsmAWV2euUwzTAZSMgi(nFxjFygqk)Mv2hvUO5nQgTCdhZWV5rBFB(L2UUtySTEN0yu9qXzX)HNCR2O97gzHgv)jU)wVIGZvtZWrk9EjsZFJLkPxbTpLPd6aWqYPkLXAG)Ba(GzSD0PxH62pMu17Xbh3EP28peU3u1)iaJfhO2BK9F78cDw251SfoyqzmE(vRNpVeHQV9p2(0qdCTTBq96Dx86D84zjDphFdbvctqymFGE8Hp)JRV5ZV8tqii0a)LHXBaEu3a6a3EtZytyzuAonHWWT(CqpAFTtfuBD2WyRQmjoS1Q7gBXnkVmGQwjUpUlSoUFEAmCNs3TdUujNqjSuy9NWOPPXfDkd2LruJBM9wz8coy1QgFUFOpOpp6u3l9()YRx)I6pDgoHzKPPfXvJJGoPPeWu8Rp`

Sample 2:
`!TJ1BVjoot8pnN098IwbekLv6Uxauyl6Hn0dh2)CQkbtSj4TH4i7K2sFr)SFZy7aH0TDR0DVCLQa8KzgpEMFZKFUHTddcjIq)2ED68H(HeDiPZ5TV882Dcj7cjm8pqdDovD3xeSITGQTCRNVzJMx81qFqaTSyRunpVqiZ0GffGi23l1fC2NOpg6FrizVv)q)ZA3fTilgS4gPid0D0y)GXlC(DHSGI(X44yWhYDb8hlwMZOf8qsP77nk6ooPqrlOqqfswtJVlrjlZyJKPsfeeGuWf(DmF6z(Sl855xGHxHsKKWvAREbheysif8D(G3nrqPMhLWZ4krmzR8H5zHddjNkGOnFpsktzYhG1LzcylYtP7bhsu8DurMiljKa5bgFD5Mnb7ZHZW1JNDZKLZWdopn1ULDBb1bwPYMdiWjRWORgYkLAB8y8peg6Y1875zfeWJIhdjrJgqcIibdweyvuFiIZaN7QmgtGKUlCFE1nkzIIR1pV63jyG8)SgFinmepd0uYHGK8)fSm((NxbjGc3oD4HdDhNPm3(vfL3O4MOKCZ4zZWKKlqaWJSwwksMZHtpucj)XFADouLJVdDmU4y6Ci69YSAvUM5XMrwbAbtO)EzwCH4E4KqttHpmlcS(5tsghrPTqDfXYSO4AaQ2gavBdGQTbq1o0MccG8zHipCTz1Gk4VidLO5PBAa2raltjZNMnrjHhaATwQyC1q3dcjdtfp9evXEEvLZbRuJAgot639Yl961TvRUD71Pv)wHBo7IEyioPB)wE99(qVwDUOt)l8A7EsvyZ4AavPWgQ12dlMLFSQv90w9VzfuUEbpX1NBBDSHDKw8eK4A37GaBpUjMpit6C9fhK82zxx7Qt37fAX6u(XCveNLavrFzg)qJs5A7Za7aVfujNcNtisIWOPa3b8jWGLiZhBKQD0IO8OcXoEuUIhdBfoeQDnTcj)wUBPElfAEE7rnMuSv7JL)bldM7KIaFytfX2rRKbMgbB4iEKZCtC71TAC53QvymQHymXM9hbvkC4jpWeR(Z9hxlPypagZEhaAxsbJ4jkXtpV6VkPmCylGfdojh8TJd2pr(xRKxj(bOQ8fffYGF5WVmpOQQoSkVu)Ddt99hViA24jb1ck74txv)L1q7pGhb1swnZiwe6H85xBMp)bqb2Ey0PigGCfy2j4TpJous2Vqj)uuYpfoS(1HdlM(XRFt8qTQ9LVRQD2bqtg6fZeQ3rTUYC9PMFcyq)lWW)EWWpE2WO5(rvNJg19oTE16EdeJHuWwUizl(cJlAqd1qhWvcsLudFyG8bW0mh)5Us49YgEoygGMImAAkgyGe)cHXPuT2Wzb8gCajlM)XLJBOeYFXQiYbtcQ10nBqUlW7PAkp)(8xjAaUuV0nmbWGmgKS)vouDE5PctZnew4sEdbtyUm3vxDcHi7ncgAjDzzrGCBvMavJ83H6AwbxbNm(TdymqNBVIxqfP6Bnp39v0dBf5TpxMa8QzYiRPgkHcKESH65g4N6T2TqM70z9)b7ZAx2hqstsPjql(8LbZMIDpc0Pz00pd3UWWGWZdrIID0Qc1HJRTrdiBGWtcNcKinsSZqW1W1s4zjylT3rf15cfn94TeICnSCG)gq6U2Th6Gbjsx(4UD0313RtDnnJLxMQ5V(w0m2ojxxFJEVoOzevb)hu7AKyHBNuwST6clUReudAzzBRmeudQt7RIWyn22WCW472FvvYYragOXIWwlHJko6JEpCulfaKQ3qVLZ7Qg)XNM46fU2nzXZn(PuXpYSVAg1e82S2aMmAX4X(oJdQm4iuDefc8SKHu1TlNE2XvNrqdC2zE5Pm((kmiCnGwvS5VwWyCaC4p(Z4CtZ1VW(X08T2Rs)G5Lit6551ZRv)(GTD9Glqa3DOlmDepLlKjL8NxD2ZRS3eKCTSWS84vjhI5CZ(n6N)QdrggPMx5Bm5k79smcKkbm)XbOVE(IP)9C)GbZIM6dHpbA4qeLO2)5HNKYD2)5bYSnIKQ5v3Jm)6GBx4)m`

**Comment by InfusOnWoW** [comment]
I cannot reproduce the issue, please try with all other addons disabled.

**Comment by Excalithor** [comment]
Hi

Inhaber tried it with all other Addons disabled.

The error / moving of icons happens every time I have a loading screen, even when just using a teleportation toy



Message sent via Phone.
