### ISSUE TITLE
Shadowlands WIP

### ISSUE THREAD

**Issue by InfusOnWoW** [WeakAuras/WeakAuras2#2297]
[ ] Templates
[ ] Shadowlands Temporary Systems Support?
-  Convenants?
- Legendaries?
- Soul Binds?
- Conduits?

**Comment by emptyrivers** [comment]
- Decide what to do with any existing legacy aura triggers (we did talk about dropping this feature for 9.0, as I recall)

**Comment by InfusOnWoW** [comment]
* Drag and dropping to move auras appears to be broken

**Comment by InfusOnWoW** [comment]
And now I can't reproduce half of the bugs I added... The MoveResizer works fine now, as does the Group icon.

**Comment by mrbuds** [comment]
* Templates update
* Test if changes doesn't break classic

**Comment by Nightwarden24** [comment]
- Change stuff having PvP-talents. The 1st category of talents (Gladiator’s Medallion, Adaptation, Relentless) will be removed. [Source](https://us.forums.blizzard.com/en/wow/t/pvp-medallion-trinkets-in-shadowlands/589985/15)

**Comment by Stanzilla** [comment]
Turned this into this https://github.com/WeakAuras/WeakAuras2/projects/10
