### ISSUE TITLE
I cannot reproduce the issue, please try with all other addons disabled.

### ISSUE THREAD

**Issue by Excalithor** [WeakAuras/WeakAuras2#2308]
I cannot reproduce the issue, please try with all other addons disabled.

_Originally posted by @InfusOnWoW in https://github.com/WeakAuras/WeakAuras2/issues/2295#issuecomment-660436397_

Hi Infus & thx for reply.

I have tried it with all other Addons disabled.

The error / moving of icons still occurs, and it happens every time I have a loading screen, even when just using a teleportation toy. So not restricted to BGs/dungeons only.

Any other suggestions?

**Comment by InfusOnWoW** [comment]
No one else has any problems with auras moving around. So I have absolutely no idea what it could be.
