### ISSUE TITLE
Lua 'linter' like the new one on wago.io

### ISSUE THREAD

**Issue by Krattan** [WeakAuras/WeakAuras2#2314]
**Is your feature request related to a problem? Please describe.**
Not a problem per se. more of a quality of life thing.
I was impressed by the 'code review' feature recently added to wago.io and wanted to check all my auras for issues but also did not want to upload every aura to wago to do it.

**Describe the solution you'd like**
I would like the WA editor to improve the linting functionality it currently has.
I believe this would improve the quality of the auras created when custom code is required.
Example.
8:13: shadowing definition of argument 'unit' on line 1
39:47: empty if branch
Function runs on every frame but no throttling functionality is detected..

**Describe alternatives you've considered**
Uploading every single aura I've written to wago :)

**Additional context**

**Comment by Stanzilla** [comment]
So the thing is, wago can use an existing tool for that and integrate it, there is no way to do this in a good way for WoW itself so I think this is out of scope
