### ISSUE TITLE
Issues with Conditions and Power Types

### ISSUE THREAD

**Issue by Bigabyte** [WeakAuras/WeakAuras2#2319]
## Describe the bug
It seems like there are some issues with Power Types & the Conditions.

I was trying make a combo points/chi/holy power tracker and color the "point" texture based on the Power Type.

This is an example of a working Aura checking for "Trigger>Active>True": https://wago.io/PHkGdEggC.

I'd expect the same result with "Trigger>Power Type> Chi" but it doesn't work that way.
I've tested it with Chi, Holy Power and Combo Points and neither of them seems working.

### To Reproduce

1. Create a Texture Aura
2. Set Trigger to "Status - Power - Player - Power >= 1 - Power Type = Combo Points/Chi/Holy Power/..."
3. Set Condition to "If Trigger 1 - Power Type = Combo Points/Chi/Holy Power/..." then "random property change"
4. You can see it has no effect

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, same result

**Which version of WeakAuras are you using?**
2.17.12

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I don't know

**Comment by InfusOnWoW** [comment]
This works as I would expect it to work. If you set the trigger to be only active on a certain power type in step 2, then the trigger will not provide any information for conditions if the power type does not match and thus you cannot use any conditions.

If you want to use conditions to change properties the trigger must not contain a power type setting.
