### ISSUE TITLE
overlays not obeying min/max progress

### ISSUE THREAD

**Issue by rationes** [WeakAuras/WeakAuras2#2320]
**To Reproduce**
I created a group containing 4 progress textures, each representing 25% hp. (ie. 4 full progress textures = 100% hp; 3 full progress textures and an empty one = 75% hp) - this is working fine.

However, I added overlays to it for absorb and heals, and noticed the following behavior:
![img](https://user-images.githubusercontent.com/22204307/88313408-30385d00-cd1c-11ea-9a00-3a7865ef8b8c.png)

The red portion is the HP, and the blue portion is the shield absorption. The issue is that it would be impossible for that to be accurate since the second progression texture would need to be filled for the shield to appear on the 3rd one, yet the shield appears on all 4 textures without filling all of the previous textures. In case it is relevant, the shield in question would cover 30% hp (122k shield, 408k hp), and this happens with both the absorb and incoming heal option.

Below is the lua for the group containing the progress textures:
`{
    ["backdropColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 0.5,
    },
    ["controlledChildren"] = {
        [1] = "HP skull 75",
        [2] = "HP skull 50",
        [3] = "HP skull 25",
        [4] = "HP 0",
    },
    ["borderBackdrop"] = "Blizzard Tooltip",
    ["authorOptions"] = {
    },
    ["border"] = false,
    ["yOffset"] = -180,
    ["anchorPoint"] = "CENTER",
    ["borderSize"] = 2,
    ["xOffset"] = -130,
    ["borderColor"] = {
        [1] = 0,
        [2] = 0,
        [3] = 0,
        [4] = 1,
    },
    ["regionType"] = "group",
    ["actions"] = {
        ["start"] = {
        },
        ["init"] = {
        },
        ["finish"] = {
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["debuffType"] = "HELPFUL",
                ["type"] = "aura2",
                ["spellIds"] = {
                },
                ["subeventSuffix"] = "_CAST_START",
                ["unit"] = "player",
                ["subeventPrefix"] = "SPELL",
                ["event"] = "Health",
                ["names"] = {
                },
            },
            ["untrigger"] = {
            },
        },
    },
    ["borderEdge"] = "Square Full White",
    ["borderOffset"] = 4,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["selfPoint"] = "BOTTOMLEFT",
    ["id"] = "HP Skulls",
    ["internalVersion"] = 33,
    ["frameStrata"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["config"] = {
    },
    ["borderInset"] = 1,
    ["uid"] = "S3eMHUh2xVx",
    ["subRegions"] = {
    },
    ["conditions"] = {
    },
    ["load"] = {
        ["use_class"] = false,
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["class"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["scale"] = 1,
}`

**Screenshots**
[https://i.imgur.com/2Fi052n.png](https://i.imgur.com/2Fi052n.png) )

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
WA Version: 2.17.12

**Are you on World of Warcraft Classic or Retail?**
Retail

**Was it working in a previous version? If yes, which was the last good one?**
Not sure if this worked in a previous version or not.

**Comment by nullKomplex** [comment]
Minimal example:
1. Destruction Warlock
2. Cast Chaos Bolt
Overlay shows 2/3rds of bar as overlay (incorrect), but when cast finishes entire bar disappears. Expected behavior is full bar is overlay.

```
!WA:2!1v13VnXXt8CYpuKPQL4wS(sfsqJev8cvqQi8J(L26ZXMyiyBoFMavi5BVB3Z3cN396U7fNK3WQpKN9Fc(zEY)jK)cwz1)cYFc5VGo7EgharJuSNz2z3zMpZNzStZkJQGRGp(2ZKziXB3JIvjx(eRCN4yjr9shXbfsoZr43Klve8Zqhu5xoxJYQChXHRCIfLWfD5uMkSEJ2(n8wyFopUcPOCMt26FI(Z4yIBT((DCPrCwWeLGoCiri)MFsSu84lFAUKmafk5IqJ7bNy0Lj8X15svGhdnIilpnJpMiuhMr(2fMZxPgmdtcZJJ9bzXon2TBZ(76AoiucPqUCIX7CgvfiYzK9jmLlkxXxmKWicAupioDyNkTFvNZtX8XGAEO11Ucsm9aVEDBS7UEwlEDnbEQmJKM2gYmNfcckT35Q2K)dQbtSITWYYREZEqYspy(G6165pONFnpFxt6fMLIoKiMGZfwKRYDMAEkLaf92GS1nYFskhmnNTeclNToksr3N4xOBqX3V2mdIpiINYfpPe83zqpJiyO0xa4peG6tLK0yBRuFHjHir9cxDCkbqQeWoirijFmD5voZGQWJmeUU8Hv1vNJaNGRoa()4QzvuKduqRdbG4llUsPPwBMp24gzzx6J8OiEoq8oTW6Q05IzFN1IPrncqJilZ1TgOEM9aaajyRX3TOGs(QLm0tSNB4U04d1xyMWqej(Gr32DA3qxvavGXNzwhphEkYZyotLDPMc6rx)55imGaOR77)jf2YiD11kc1(ujnmLeSWQnMlW7jqzt2BPWIvpRHG62MZilbHpAuAwR2TB4ny3gn9Z(Xv4fClbu9dYgOOJagVGernnUszx5l4tHGNXv85bTh9iYvwcrl7iozx7)ke4dHHnAuYXFVERs67TXny67BBq6hOVO(H6Fv))FN(ro6FtFb9VR)dDvDnTRf9011BRBC110pwVJUzG(PZlkjVwpEhFDl9t0DVI(5oFHmNTuWLbqtycHomrDn3uocVLlm8ev1BuEQIw2lkfjLv1VQSRekkJWPwQPBkHHnu(nRT92zxcguQTC3LDxwG3ydp5V)6p)iklyMWsLTRowYKNIy0r2bWT8GficvZtiijPNsqydvjFfuZ9x8Hz0bM9mcjbg0WYjg)mpLUV7ieL1utSERJ1d1j6(HXugvM85MfMrxyCAlnUS(nLDbNuLNANDLumXRab)HGnOyV2KXx)UZTv9owG6rcduMlitCtPhDesGxaZmqVUtM9rl7EeNpYXZELKzkE0(fd))pNh8(LpefJjmV2nErdVqiQX0HLNhlGLxqnd0)sNvWEAAmzkVWE19A0OThknlbvAZCkE(9Q1u9xS7V5t3(MckZecssXp5uF181CUGcB)S42SD6416p702V2UZmyhTizlw14xurz3SLzFvmkI866iyCMn0fjED)w36CTB1ZCHZcHvKdf8CgE1kLULU9pF3kYn3MSFL9)Nx(V
```

Requires dev branch for encoding changes, sorry.
