### ISSUE TITLE
[Beta] Custom Conditions not working

### ISSUE THREAD

**Issue by Rhkqt** [WeakAuras/WeakAuras2#2321]
## Describe the bug
When you make custom conditions the option if they are true/false should appear

**Do you have an error log of what happened?**
No errors

```
PASTE ERROR HERE
```

### To Reproduce
Created a custom condition set

Import https://wago.io/Simpadins
Go to Conditions
Glow and Cooldown show no option to true/false

**Screenshots**
https://images-ext-1.discordapp.net/external/qjNr0QBgEtJq8Bg1RnAbg_3v03gZuC1H_9KUVCB-QIU/https/i.imgur.com/H4XmBL7.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
WeakAuras 3.0.0-alpha2
**Are you on World of Warcraft Classic or Retail?**

- [x]Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Latest Live version

**Comment by InfusOnWoW** [comment]
It's *bool* not *boolean*, see https://github.com/WeakAuras/WeakAuras2/wiki/Trigger-State-Updater-(TSU)#standard-conditions
