### ISSUE TITLE
Issue with %p

### ISSUE THREAD

**Issue by zaldor30** [WeakAuras/WeakAuras2#2323]
## Describe the bug
If you specify %p in Text with an extra element, I find that the aura just constantly uses clock cycles.  It does not matter if the %p is used, checked, unchecked, called or not called the clock cycles continue to climb.

**Do you have an error log of what happened?**
Does not generate an error, just notice it using the WeakAuras Profiling 

```
PASTE ERROR HERE
```

### To Reproduce
Create an icon, add a text element and type %p then close the options panel and start a WeakAuras Profiling and watch the icon go crazy.  Delete or change the %p and repeat the same WeakAuras Profiling and it will not show up on there anymore.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
2,,17,12
**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Unknown

**Comment by InfusOnWoW** [comment]
After looking at this in some more detail, that's not something I want to change.

**Comment by zaldor30** [comment]
Understand you don't want to, but even if the icon, progress bar or anything with %p on it is not being used at all, the processor is still ticking and if you have a few bars or whatever, that ticking can add up quick.  
Truly appreciate what you do for the community and know this is hard work, WeakAuras is amazing and the main reason I play WoW.  I have been doing some coding in WA and have gained an appreciation for processes and how it can affect FPS.  I just hope you think about this a bit and not just as one icon or bar, but several in a WA and see if you don't think the processing adds up.

Thank you!

**Comment by InfusOnWoW** [comment]
I don't think making this more optimal is worth the effort and complexity it would require. Nor do I think the effect would be big anyway.
