### ISSUE TITLE
All text fields are appearing in the center

### ISSUE THREAD

**Issue by Solstais03** [WeakAuras/WeakAuras2#2326]
## Describe the bug
All my text fields are set to either the top edge or bottom edge. When I installed the v217.12-20-ge7e43c53 all the text fields appeared in the center even though the settings are showing top edge or bottom edge. 

**Do you have an error log of what happened?**
```
1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'SetTargetClampingInsets()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetTargetClampingInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:274: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:213>
[string "=[C]"]: in function `SetupClassNameplateBars'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:96: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:51: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:42>
```

### To Reproduce
Installed the newest version of alpha and logged into the game. 

1. Login
2. Add a condition to change the x-offset of a text field when a trigger is active

**Screenshots**
https://imgur.com/a/I4QXsYq

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
 Yes

**Which version of WeakAuras are you using?**
v217.12-20-ge7e43c53

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
 Yes, Release version it is working. Downloaded the alpha to use the x/y offset feature in conditions

**Comment by mrbuds** [comment]
You didn't include an example aura

**Comment by Solstais03** [comment]
!1EvJUTTnq43LamaBGup)tAAr36aCCCBtqQCqOYYgkQSPLOKzRSOafLtCXGF23DhLSLKTt2WWGduKiV)VJF3rVEEUEmPNtVb973FGhlZJ1VtV30PxFp2spwa(hqXttcdZegpNUEm)8mJAPR4jJhlmpX3ivjTAV56nZ2mtgUzgpxZNksw1jZWnc47KGMl2ja(e57L2932mR7MzMfIeR8XFXkFE8MzAXsUmrMeTz273tcINsLwz4kxc2WR2m7Jcd(EPLI)0ctUoPMOafo48UDlSlFHmU12D)zCN2D6CYIt2mtPBY35hHRZjEwwWtySsP3TBH1ia(UgE4XwxjsZt8xO03QKjqOE0yh3X3bHFLkoq9yc7rzQW7IQ5J7tdaN3JLx8)sshhej8Md5zFvcYHrlJIe6miZ6qfaflyFL7)Dq15gfiOmX0irIql9zlupoH4U(cSm4)dJFKVgkDs4lfOunwwXTI8dqMceZZddDxdMm7tJV52pC)nGUOpXmwoWCEIyLa90cDNiH3tJ5RbdJvws4X65XkOBuH7Tz2TAvKwKLTzwlwQioUni185ez3QfHYN8ySBhFdOsTGhtK4aMQhBYkHov9iQbYG3UdyY0hxfuXFit6c7785zk98pRcS0wOng4KO2MoAiZDkZD4DUwYTH1sPsQW5ndE7zKOtow8)4HAd8ZPFZCx94jOwzIVA5CU1QRhFpCenjqIlMD0a4Z7P1YzpBiRHFt(ZGN3FEz7)EqBBMnAbhcIgiYLzK()NCfdxhjm)7CL6Sso2zpRJ9S2Xbtt8mZr9Q9loRz81Zq1cPhiLWcKzFJW4xjkrA2I4yP8gvK0VsNGcbCay2ID(sVVwauws7x6)vl4y53dA89zFTDb8iNmLcvtoOZR61fTuaKuOt4X)oaSHXlNbq7SVlePdHJC(M7WOiDaueh2asnqKbzcnIzoNIR3jIOdbBXhbWvanJdOn)rf8zAz6rOsVKdKu8cGeQseviWJ9t(1eZivSsBLpij4Km(Ca98mCrtj17S2H37oPyvmDbQr6)GmWSa2IoryTe5tIa7YoNFwzpK)SPv)nifkdxVlgOvyJtBxDNjoJ3wKMp36aeB(vm7EKz3Jm7Enm7qfAXJFkfrLbaRA((EgdsTT1WK7DV5ks546pQ0bpO5PESh2(gTXkzMCEmvCBJhvBu6o52dKAsNAGU)tbdYxARp6EqQktGi1bvSpM8hqTgowKvzpBDqHYcwdneHdhZTNLwiKrlqy7x7XIvCAWk8SzQWaq0MyQ6dxapvQl)yLyH03UNFmpdlkzzWKdWsShgE3DxnbYElZJnYYZSixwsVyBBn)IEp(vyhYx7ZyH6UxshfqN2TovgSjkE8WMXOzkyHAOJg27YWjXcsYf6oBKPOE5jYLwqmxc1tB2bcIviicRGdSqRyp6uI7nTOmua6b6fVL(qoC2N4cuRijcR3hGghoy1oXBfwtYoQ0ByfOEGX0Yw8)N9ASyAw0MTbhcptsHPsq3TJ9grtgxDM3I1UgN(orzkjQZhhD5rgEM2beXiyEiJ4dy2R1jJMm5MlN8GZjNcIrgFAPCGxoPCwlIuxXsOdIrCs7FPkk)oD(ERgUMgRD3gVJjmxQ5pIZJcy)5I2n3Le)nq5poanTr5mSV7J12T9ES(jzGyKcAGHu7KVCo0h4WkHMCMaGB17u8x32hYkVigoM0kKhN1qeOMORrCDJOzZBdvjGdLhqyeUwcr4dc(3hczVSoGxbCFvsOQktyIe4OzYRHmPIfsEvmoqGL5k86ozvfBvXxWm1hU49n)17jt8vpJQ3pBJHRsn2QG7tjZV9)m2HHApKrs1oB)asc7tYHYjv5Uz5h2wpdMsymo0tRtObMME)Txo0D80Tf)ynDJ6fFTmfOFscXiE8a2bug8SfCvJa10IdPZRHyqhU)Hcw3PBN(7Uog2K9szgh6Gr3nIg(cBLP8xvo8YB7oOl0zrgu)ok43o)y9R)WGj9x48zG340fwixBBj75tccIn6UXJD8GQDAyaSRdGjfkJkXxqLjkmaG1jPLWqgIYYBcuoeK)cbCZKkdYIADfxlrhXJPskRcWvJZffZd4VGNej2jg7ExGiJQuH2SU28xMk3S5fu4UjJTIKbHyfmHWVECToVQwHjB60RtT5jmLD4ktv09RFXzEagwbVDwF8dV)o

**Comment by InfusOnWoW** [comment]
That aura does not contain any condition to adjust the text offset. Adding that, I can't reproduce the problem.

The error message is also strange, because we do not call SetTargetClampingInsets, nor is the aura attached to any nameplates.

Please try to create a *minimal* example that actually shows the problem you are encountering.

**Comment by InfusOnWoW** [comment]
I've found the bug that made the texts appear at the center though, and it'll be fixed soon.
