### ISSUE TITLE
[Bug][Classic] Group Loses Border and Background 'fill'

### ISSUE THREAD

**Issue by illutian** [WeakAuras/WeakAuras2#2328]
## Describe the bug

I expect the WA to look like the attached screenshot, and it does. But upon reloading or relogging it ends up "squished" to the other part of the same screenshot.

I suspect it has to do with the fact the text shown is actually in a %c custom function as a String. My thinking is the frame this all appears in is initialized before the function with the text is run. So, on the surface, WA is performing as expected...for a frame that is 'currently' empty.

I run another WA that displays only when the Character Sheet is opened, and it too has a border and background. At no time has it ever messed them up.

**Do you have an error log of what happened?**

```
No Error thrown.
```

### To Reproduce

1. Create a group that uses the 'Text' aura.
2. Give said group a border/background.
3. Perform a /reload or relog
4. Border/Background no longer fill the entire frame created by the displayed text
![wow - classic - WA - Bug_1](https://user-images.githubusercontent.com/2457706/88475806-3a678080-cf01-11ea-9053-b17126d96a11.png)

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** Yes

**Which version of WeakAuras are you using?** 2.17.12

**Are you on World of Warcraft Classic or Retail?**

- [x] Classic
- [] Retail

**Was it working in a previous version? If yes, which was the last good one?** No

**Comment by mrbuds** [comment]
Can you include your aura for testing ?

**Comment by illutian** [comment]
The string is:

!TZ1AZPnox4)lzMod0etm3sYUVB7mHesFPLaumzZ2VqWGLbTXxyTStc5d8BFps2glFdCsiTBcEOdXswNJo6iPJEEKeDy5HdgkrgkvPu5JlvUYqj9Hsk0)bzp20sbz1qEYTkwMZhk1qd)4JYwklh1t2AYmDKH9YrGiYo2ZmT6o3gBAqabThkn1Y0zERjMgd7uUA9JRwfkLXeOu9mXgW7pRzNbn77xfNzQzAbc2Pm7FvyFxL9Dn63GaowAdLMzBpN87hE49YtnlHnp8O51D6CXjk3Fyzq)t8RFjITSLTRHGnWEpPcpsMXEgszBHNofzrCR1bRYG(OcASJQ6GfZrdL()nB37IRAdVNLu2XsgAXK5inTwkEnwIZy0DGZqcKc)WqPBo7uPb3in40(dcEzple7Ls9A2guNHSoYtC2RHAcjRzpdAPulwAUM8cWAOTCJatZ214bxiYYqw7pHgaM6JP(xcst1Z72O7GbDVSDZlG6)o)YuMzl9rtd6L0mLzD0oe0nt0KjKHJhk5(aKRUJMn23FbT4jXZe)ikAMq2J9gXW1TErT6vkx5iXteRu94Fd(muvOEnAxDAVPAQVXFibzISgI1UChfnSH)tnvMI4hUEowwZC6qjlwJ3TJLnc1xajAdPtzr)0DvvjiBAvjzBojWfwUQyDW9dtqohPImiqxOKQf0vcdFKTLzgJ748lO56wtsN1VzZo(QULbtZqbFWVwQ(BIuXW6Y0rW8dG9g1zyAaFRaJ9Of4g3mjiy6fmeucjtO1pYykm8b8BSmgeii4Q0LXgBr1TAQ0wsHGkx47meQicEdQOyU4jqAv8u3NDO()YnU9QVx8BNjv8e27xnp20XwdtnNUxnODRon58ZGEvWe6mRbOhaH(WeqqhITPUBAvhdwmKLJkuC5xxoY9JMjmoB5iOhzkYUnmzfs8PLJUcMMYsvyp3xThNmy1OcasiugYCgYiOy(FwJUDJdSxX9RgigsJGsSgeFbvaN6nuI161xKrHtXVjrdy2dmnQccznFC5O6Xe6Md0x0hrWe7v1OBsyYfAv1EWrftWqBQQYjQVE2hMCnRKU8dfk41we4mJIFS(bIffCld2OqyJELXKy7mbtWT0NnJATmROGFEhgwZFuS0X1l(XYIIPR1GNee89Pi)w3MBuBw8m1EtqyEpTGWveeeP120Ve3jBHLhRHij3sSq2owWWH9g0uAWVd)TujcSoNX0sQMwGDvGQfU6Fv5p1AISb4vDRzQKlhvQ0YrHLEVpuQI6EheTZOyPs79H9w(v3H4SpcchsMyHNBth1rBa2YAh4(8nRDWNyX)3YrsGMavBFjIqKNcV9YfE6y5izlDtliwaH16yzsfrqOlSEo2GwKt71A5ihQKW0UhK1NRbpOAzQVC01Mx79(7X3I5cqkMcuQGizxnxr2gIa649xaFMjDTLjxJvOimofsNgEjousbyN2aEjV492Y2oKnGgcmJjZqePzM331akl83t1UxEbjgmOuWn5VidScquyyCqQOaAy4OAebpfKYREKzoHqq9oT)LuOErWCffqMTRR7o0a3ICPPcGDqaapKgYSKxApTLl5xs9jS0(wsDblTVDuivLMu)9fw4hxo67oYkuKslhnic2uFSOjHPmatkbMJRr7RUYDqVFP8ZOry0QEfNQ)q6Jo(GvMg(gyacqYmzfZ7)l)PBLddB0MHuyY2GWsumoUv8pwbeIoahPFhDuB5sILat7VHP4y1fdLCH2Nc00WritKEwMXSgd31JDBFsLY)t1bo)TVfZZEtK5mezodXaNbmdgP4g9PddFhhzLbD752CUhWhFTLmak)A)NSPQlrqDj0OYHY9ggkxLCOC7Cq5UaBTdcKlHW8VI45Eo7)1RcEUWWWE6W4sbp4Vc8CjT417qqo747ivmmljGpj02wfdUwk4Z4d7fdtxMrMXqJj1)OQx3UaPx3VggRwgaOgBRWYmAUOax3muxUTGJUFNBEF6YXY9gglx1CSC7Cy56aGfYrZ9CqZ9CpzZ8DQlhz3ZfzxYeisylvISsFaCNAX3oQSH(jCGImHu55VBvMg)4BxFUDvN7B9sa8edk4o(o6M8o1vlzyDphOO5W)Edd)Rwo8VDVTYZYKQ(D2dLv4iXFAa)Y3sVFwhr7UZED9(dJBgpHXKoAYqWy53vQSD(RHIfMidXN2M8D6Lo69v0LWTXHH4MaG9N9E4LiLaWCRN5JFnhe37jqC1tcLXUomUJQ((e9MelQXUm8TtYVvD53QU8Bv3VwiBz5kZTX9s616w1fog5lztj)XFDS0J)q)XR7AfgE5pJRt3r5xNUTe8TToqUtTTLNCBFi8GXuMsQZGWXBHBsfNzH5rgvpEXPENcCQuWZQlsF5NPFvD9UQ4vX(GgleYpkSYzueaHXF1(sSd6p48DVIv9A78gdHy9(nDbOugBA4qcso3KMObSMgKWan1lbZkepG9jMcnC0LUfRPryL6li7oEz0gM5rsyAeH(YwgkOhC1BqbuzqEy5w(GqAwXmUVIxDDGOrm5GaeOj2fOIdMYk7OLHQzbCXIX1cBCcVoaLCEZlA2rQzX06L8)ePLGtVKJTqY3g)1H6QcLiWS80pmKvmvdIRtL3luljVqGstYDWpGGxvhLDvrh6Vwt8GeQgACeV0BmGeZ3evhFMf7lvpuWiBw1fs2ytAJP8)y9kpYmLuu(gIPccmWf7)Nc5T2pz1L8rpGyqlHc7XYkqPcjg9DDQRbyd0ir9rkoElk(P4vde4gaxuBTAIQLw66uKWlCNDlkkuiESoHeR2ilQgvDF2vFP13KCTVXULmYCoIYZet2No)1eyYsR3LJ8R5mWKL3q5yYUZEnDF6ee5zfYtw8xobXe3T38RP779RPlpJQGn4PSyMVFUHJH8cVHUnTAH6OmRGsJ)8)03q3eyqcUTJZVshVLOtMZQjNvtoRMDbwn2woOlXec)XGviqTcCQKUpiI1kUF91OomP5)4GNpNcshuvRvjBzJ0PRQvypPzyKMczT7JL(ItVZeReDMo1lhQg(KBdiDUjbQjCdDFyu55MktrUjluKMrpzlRf8z0amNB9ZiEhEutrvMog(vWwY6WHjwoKzC9KLfRk4xVBqkgkf0kYJ8AkJS3YkJop3W6OYL6rsMoXTePWbTHNahoo)WwMa3VUlOve6spHRKfhzSSDOERL3yysCPXn8TbzooEwBDoCP8FeABNBT02)gkXMIXoLHawoVK)xIGX0P)FR8Lh)w72NpyCyMoCKWQiUTVIs740FbV6j53qRCoz5CYY5KLZjlNtwoNSxkNmUl76RsloJmVIZjS864eUsUZwXgY)y9o5O3f0czveTfKHd1Jv2)Jqgm)QFM)Z0ER(Z0okTO1q)lBN31QzwVY)ySjF9HPx8JAng)LVhIuynX8Fk2B3Fk2q(3b(RAvOUSH)7d

**Comment by InfusOnWoW** [comment]
That's due to them being in a normal group and not in a dynamic group. Normal groups don't automatically adjust to the size of their members. This interacts poorly with the text region type, but that is how it is.

You can put your texts into dynamic group and that will correctly resize itself to the size of the texts. Make sure to configure the dynamic group with Grow: Down, and Align: Left.
