### ISSUE TITLE
Weakauras disappears on 2 bosses encounter - Kings' rest and Siege Of Boralus

### ISSUE THREAD

**Issue by Abuhmeed** [WeakAuras/WeakAuras2#2331]
so this has been an issue for sometime now

basically my WeakAuras disappears during 2 bosses encounters

- first boss is the last boss at Siege Of Boralus "Viq'Goth", when I get on the Cannon and get out of it, my Weakaurras are gone, and are fixed after /Reload

- the other boss is at King's Rest, second boss "Mchimba the Embalmer", during the "[Entomb]" when the boss Entombs me, my weakauras disappears, only fixed after /Reload

WeakAura im using is 2.17.12

Game : Retail

this wasn't an issue before the last 3 weakauras updates

sorry, i dont use error addon and stuff like that

**Comment by mrbuds** [comment]
Hello,

You really need to install bugsack & buggrabber as asked in the issue template and tell us if you the error you have, otherwise your bugreport won't help us fix it for you and everyone.

Also when you say "my WeakAuras disappears" are you talking about all of your auras ? a specific dungeon aura ? if yes can you export and link it here ?

I'll close this ticket until more you can provide us more information.

**Comment by Abuhmeed** [comment]
yes, all of my weakauras 


!T3vBZTjox7FnpZS7hAhH49zU37zItSBYDtTZACAA70XjydXMnyWlGBI7hYV9hjX7GalCiVZm7MAJbHq6OZ56CPZ5WuUPtMQ5pvd(ro5pYbNQTAQMb()qhEM(8Bm8CxFORTRh6ad5i)hK8xEYFfMoe8rXPbOt21ZW0Rx0LmvRNT1V)TUNX9xnX11oWcDi)562M4ll6KNol(t9nwyovBORd6V6oZx66DMRLdQvpS)Wj9hhFAAw)gF9sXFNPoM(Mau7nADGLRJp6KXhAE8x08d09ccp61wow(ld)m6JHhf95apRflm98dVrtsoa(JgMZ2C91t2Ug1XpU)PNn48tr)o5R6B80rJN(RnTTpXi6o7VzM5VmDc0qxL1Dt1U8Wd0MCP2KdgJASn4BQ2AB9TOgxZrFLz0vrUe0nWu3oyzAJCMNjPr0oR)PNIpVnoPDTGWo)2rxFTVzW0HFqcepSfFiXPAEMlqJeH9)fEUBqZsbUZ)f6PfD4Pdva8a0LzHKiUq3ZZY17(RoyMLTvGL59xbJBWtCiThhAM9Apu3gncPhOtMPdNnhGpA4Dr7WX97pCQ2CxNRTwe(8TbFd26O(1J5DgC9FSzQ2DX9r8D3jW0Zr3(RX9kEEC7ATshplMDsuZanMJp4LHtb(MO7cAOpAgXHiFzQ7J7GMolqJLiPfYbMKEcO(ZkDlNwS5seSAPgmGm6zyLrI22vNSKDJV5LZT19XTP3gtI43C8pSAdAnySeD4zGh4SCwGwsQDXbJhFYOXfonF8YTcxl(WM2xhT8S3Ojtg9Lt7pG0jMNSczETlm5YlyYHLmPUQFosZHH7ToA3AHE87LEaI(IzT5cz8aN(mFxVzFX1GCVwy6y6znxBP7TJCqTp6FpW(w9T(fxOwJoauNkyJ)Uw2JU1KwShTf9hg9iF)vN55UWZ03)(R(dnSsL)SknbOv162KtziQ5qhnW1B19x1dPgo8U5N8B9kPGk5NgYbKfLb4N2OUcstQBQm8unUWwdTyF(n4wc)L8JA9kQvQMr1GynZ)YCs45tMjqYhGWjskAbUX0C9byr8GX4(erKGQIHslQYUIRQvLvRyOLAUufdTtdgGfg9rICOZNS(ajFmMOHpJmV5Dbx6Vuhjt9TmkzjhM8NRrcl6Otj6dXDIKtyQ2)NFUMjRvyazXoGSyhKUyp8St1BCW5tgfDuSqfEcB(fwgyJBhqeYc7jw3zAeE4HscX6i(EXE9)SXpW66TPQn8Crl7mNq6RdhnSFYQXnZcFaixgd6OIgpW94bEw)((R(7n6gytBiqn5hkl1PUfzy8cpDK90ls(e5h(LLV1mBYkVWN)Sk(oz4W(JVmuR64t(0XtY0hIa)aJhhkn7HpPqXHrNp50tqp3b4hRjzE8JWDfz2(sIcES0w03zyij6mJFksqWDPjbcN2)Ur3dbnyWgB77V6ILwi5W4ZWnP)sKuxAATyjgfciV5R1MbZ0dccB8aeIrNGmMQgknnsj2VmxAnp8SInYfFoWcgYiAPcBPEzTr2lrD484ph1QNBHB3hMDYSyRSMJvyMzfqQjUuyqfXo9Bx3vKPxII3EvcnlN(9ytKyX)JS81rZsge9I2RxUdizuqktqMnC2qfJHCF(ZhPJ1dJ7cKH9BdxAINaZHhjcdWstKzHmwzX37FP7zH7st1CDITSHpQ9gZibS5l1DwyM2mH)g6HFnYTctVGT50XfouhkL38BiGXBiALZhHFSGOF8Tn88jx9arroaurscavbaEz40R)GOq6cPbYQkqfrooGaeWPabr)E8IRkUJHlldILRiYs9YGrgDZs6n(R19UjsNjYWz43dpXVrKLsXDjwfSlY1mgReLiPbkCeIz5iv4yxeX(n4yuVvGiFXQdbwoVMW)dbkILr0jRXPiWlbP4ougmt5XYKhMwTyWQaifsJq)7qys0cBx8Oon0EuC9QoKmO5pwu1sfXdfviZ0l7i8azripsouuKxvcWb5XsA8ezqrbzbvjbOiurHtwwn6xIVRfaqKk(89qjbkiksM4q9Klr)FIWyjf)XhjuSJ01R2608DJR4bynk02hmVTi5AmfHpagjSx8xYyaIrdfLS8KZAdlwXInvvLRz4PREidDgrlsp6iY1DGbgKKPHPXx0VJynGcPiVV9Oo)OeQ3olVf8i578utqmp(TV8PE38NxC9OT9JwC7BHh8JaWrMtWwJ34Ho4j4f1xRp38NhQJGT6SONU3pp)KpK(TpOHVGql79x5PVajaJv5q4BH0yhhjTYhH8J0WFbRSm6eoC3kxsWwqUacuRYGlcVBwggMiBMd7)vS2MiJ(qS1dMj7jf8rw8ozGseJWX1ZcPfoY)YJhn(KFmA4KdoTmHhnZZFIjZzy9s84Rid3d87n3dXMHR1MgX14ihNBefdvyqkN75GI0muWtDA(JNJTbwOyiN7(fiw4WL6Ey9S7GtHgyhoJT8CulWGv3oQfEUPwOS5(sM2Z55DWtKJNXU5M4oChfivqbYazbffEEKNj8QcCI8GeyJLEucPf5yx0611BCEmidzYOZkjGeuIqKuf4mricRepuhApwaQrLGHgatmpYWhabdPKiuLX5IwXRKbH6zHi0yabLcn0LjiaYWAab(0xhEXc)v)OFVLhthEqwxD)aKhW02l8YKqIpaZEhpy4rrNuzWdm13IuNL5sW786F9xzV05KPf)4RtJlw6H(Z1S6FU4zyGm5oI7m)3)k3DMv2w4yGTLOPEIM2bscQQ8CqbaVaeOkYHvCjwfZkC0ywbDUn4zl5zI8u(FQ(rBi4JcIz7aHReIUNImCpdbt5mg36SqDv5bhzvoieijae4KeK4fXdok0gCkW0uSMa88tJaChpAMbOTAlVjFj3TS9H2Ct(YafTn3HVka2ZcuCQ45laj)ytpxR53F1PMyJSncyoZ7ZxgNqKefeEPaeVwx(Boq8wQ5sbI3on4(be)PDdFkc7)ToSlk4D2nSRSCISxaUIxQBJwQtGDfZirraD53NM8rDJJ6z3oz0NM8JjBZH4IcsYsGWERVLpSdcH6g)es3UaAgtbtcpMWDryr623bWecGRgG9QzdX1InPG9)DRQigoZtg7A5Sq9G4steki1yl65rs0uE1yXy(jobwRSm0XmdF)vOtBZUdGNSmOvGoW8w77Ox71wK7uX(Kv2m)tfDADKP0(w1TWR5JxY7JxYxfLk1yMNyAFWpMy8lpfJv8M7MyLx38Q8uB1FGOKiNOSeazVxwqwiMN0kyqvS4O4RgR(n1RFPwZR)2eaqwBZm4lFb7M5SOM1ekRM5ZduOGn(E4LIE3y6D)vJ1zyZ0QcmZUqRqDJaP5spNIGQ6tV1FkABz1p3eVAzjssEzexJVs9ZTrmXvLbWm2PsTwYASoMz5syOrazYSfZrQaXYPnq(hd(S14b4L)vy5KIb5Igt7SuMYd9hfkUlIVESb(UMTrsuXviWsfzkD)YSNTSKSpLJ605B8dCxHvFC(AdSOT2MO)TDZ7N1U3I(sSY0L4TZ3Vy24qohYO1qUmxf5i9E47qaPXUelmQhGdms82MfbV4msVRyq0KdtqEQ6ZJEj8Hd)dvhJRXGJEcJJ1OiYIXfxzKjrRznXIsijWnoZnpYCU(w2LWRzfhT7H)AlpDBDhJ1BS9nB0TP6vIT4dtqAs6EIZapCizmJEabxoGu8dSMFZ2JIfDEWb7BPWNz9LipzrRt8mNBfoXZLpgAw3LgrvLgrFGJEykXTRiQjnMxgMgZsuYXOSzxugqVuMeJJbk8KPrtYhjkYcgBrQuTMNjumR7HmsmXPtmzNIjpy5bso8wEEZHwiWX0SFQqvCWaSRP6Ump85xw4WrdVm(HP5Z19Y7bm2lOgvdjErM7fOUyp8b6H7V9A)uXGcXheNqn5(JVVC9NVBLlSivizDjnx6iWAomex2gcHm0Rg)HlNpdLCLoYH9CPMa25QKutq7MT2wybocR0B82E)v3gxnjGftqItj93R1TTVSNUxuUqeMKc92Dsk0B0KJZsMqXOoKxHwoXXAstKpHfk6(pB5UatmbebApkiZKftILUge0xkarEbvrfGaKxfaeQCJNtGlgKt29HNUFi5afCp0Dtq48FCy4Qrr1LHLp25Mj1bAGIhHz81PSU8wSoVK1dRkCK6H7Iybx3k4airPO3C0XY5WAmX215GyzwOznlmYDh1a5pqEhwBM3JuNVlG1KQNJ0mVfAPS)Dy3P8VvFBbxxEQnTKyAO5wvyHy2uBYqq8APSiQYQYpe2bvcxQEfxEx2kvVxkNnwzncLakkcsjDEChtiVD4MvZm9yDdoRN0wW6FF6XFXzS7IJYBHKswoOkilcvKff4u4HqfQz5qMHNqFvzgZzw0JqqUCUMtg8EptlrddQ42JYeol0e2ErdC95ox(s8tw1)5vlVp7hxElfLvvtPAarpGJ2PbMgYOh7vAR3PbBRxUQIqJJ8wbABj5ajvvEfOipGxsHdkWLjycaqvobzjrE05OWNjl(LuuKveXxLeuuqQi6UcBmtVhCu7I9Ll07wCJ9sZAAJmFUYYZZ1ROVrjERml1NTEN2hNIobLtE7dmmg54)Zlm1V5aCPQ4NFX0Ws)NrEX4)ZWb4lXJVrJUuCZRctJH7RjX4xOLXeNyQiIFio1qSbUw60FBQyF9qrXQ9sSE6ha0kVCvA5fzKCUNzG5Lzxyeqk9i5ceeEorMdeKk31N9jerqcfjXrrDQKrQ4q(K5Nn(gg58flFSWg7vCK8v(Xk2VLCwwWNBCZHNs7rwkfhSNbpAA1BPiWOlvAF)vnXwy7E7apZ)DJPZ8TyF9HIzgtW)kzz3NSJNmNfEnHT2SnbbUoJqk(SX(PH)HtJSmJRxr4VN9XFHDErIkgBXN23kCzK87c9VAjLDwsVazG4ghKBIjh5ul0xXuvq(wV4stBoZFybMx1vggMsALYBj4EeAnmx1YcJT1EXL2K00lrGJg1D4PaIrUjW)3N73B5Hh74uD9ePrEjuxrQnNDWkJP3DIrUoiNm6rxl1C0XiV)niXJooU827HCGNh797SkIjZrcUruZoYXEBMS1O(QRCRuhN3)Yjw(m9UjH(AtlvTf8dUMGgPueLYs8WMz0OqGWo2C(n2OtMOBM1OGDNPBlD)MPg3RrsgnjSxrWF)NnoeKxyX9TpsWWOeQgDqXEPcfBwhuSYqXMTdOyc7akwyWI0LxZp751CEpcB2gS9oVcdwdkZ9ktX8YyWmko4RUwctnO7dZa8)X)768FY9px3lxaUNGJVTYkm4tDSUdBXyDNN9CbNWHRaqeiaLLWzavyr(fNl4QcIC4mehkbGkQQ1w(F5PwKAyju4XOuA8OAyfhMOSo)JM2bhQT0kmyvlFYej54(fLXcrbfaqrgiiOQcvfshlKLLbQCYaGaqfnEixBb7j8EfhLcHHtwLpd5m4fNu6uo78EIeN8AviNfge8uQrsXRyOM6azODnGyIFVDs6rRM4GmSTkcaSOQeg)aRUwSRcKtwy40df(smJwQ8vwa6oZPF3jONQ)SMeFd)uJSwhKXKALfjNOtNjAKZ7ttumzr1DdqxzZ5LwzZPZdQ3FKz35srIcoKBKiRng7PxgzBHetjV2kPsiTRoKCl9d3F1xT0T37YQ06XYcdcGxO)PVZCzvkApB7EpAKpowfL4KWH5Giuf9rbLAlGsv9oZOXvYio(NacTFKIpvgReczaJGgAveankJfPd5RX1hb2EdM9jKMtdlDut4E99xDWVnr2XwYeYTIaizRaPNaylfJ7lHcIqhpWVcqXugRrBJMjB620Xdm9cnFxLWQn5b(9nXTLEHBHzQIb4O7jiuS5nKu29xT2D96TpaMDDxU5V)FBun8HFBxLUKUk)fRC8cIQYxI8aorfrEviuLptgeW1i(ClannhffyuOeMoZl39ciilOIBQ5fGZNXxCU7SSCD2gpeKdsr4Rhs9AWtqT0gbcNNx(1rL3QdKzhitAGmPb67XeKjnqTjGBlbRmpStwI7ZNoWC7ZlE29kUpl7eztdwY3ZX6ykSVC0)Txa9q2Lq)IRDjiEm8U6TikqcGVJxFK0F7ipyvpJDd47TprJ02m7ZqwdSRDRS3BgddFxUSBDwplKk(O)6sz3fzDOQmhqHH3zHpamD7QIQ3Z211iKfXGLixS67yUABB(cmSAKEVGRX6VBuE3HRTBlG3RGO9nbU23Ybr7l38Skp7nuC2oMXfgQxYmxLKhnPFRHQ8Z3iU9K)9l8odTF3HQmmb9vKe5vLfLffeffbYPjOF4kIbkICqjfjErbbfGmaw7wuxIhWS4tzHtskaul5thgpQuJXJY9gcp6RZxFFh5PVWfD5JD19EcOCKJtbaaDWqFIHH2Tp(DqrFBNpxCVb2hFrwHIgGgeCcYcCKtUWgUZk6YOMQxn72)(sw8d59Evme19kQm3t2rZAkSgSSXOJfRa96Tc)yvWPANFU8i6V5R4KGTeW12EVMhibvK5Lv4b88avEvL0cdLiuvHxekcGYkkkCkj5vt1VHnONprWNym67AdVLl8cK65AlUF7LF99S1rJ2biScphzxVGKkuOBVT7aE1b86znakBlaokVIb4WuLpQl12BqesMbegRuuolXCuRruP)Grtu3i)9Vo8KCq9Qca6JaeqUDrLOOOcckhhpaQYllkkNbsh9FHVYFPmmVDYO4Z7gXV37SUYtaOW29vkgZ0u2WxnPSw223VxuP7IDY(3zoFtWUFhLw37JSAa8sd3Oipq5Lc)KVBuN3Xpzhm5U6n1Bg(jFHwhUldmNHrXD6qFm5ozGKUNeqAgATBNjGddPJobE6c(B8((5Fx3YLNEHwQv2qDITZZ9d)sdrRTFWdPDh5EukTsLfhARsMuBrXzyhFF2c)eNruLjyEv7ic9XQqJQVADtEt73M1yufbEj5UCjVdJxhgVomEVaX49Su257QPOVCQPOH2gzoPZflHYDjuFT1P)4F(8fo5Qi)TE5enh(nlhFSv6543aNJn9D34nhTO)PjIsR)E)4uKrJQnscIqoOeqba5LvLvjbEQ6Jqbf9PdHFunFsLxGdx6q55G8cYegVLA2ZLaRpxN4mg)qWC0ahvztRyOVQiWOQK(p72qWdjV2uXVvhFph5UmKjzkazz4ZBMKPzzUWCg6G3y61LazDjqwNhtDEm9EnbYEl4X0l3QVvAcKrai8qsHSgeFgzTV1ArOXVvD(xJVj(n1LlEFMkzrGhl8gFfUpHV7JuAJb56iE(rlcCDDrRdT8yOCs9iq(mKxrHRJ75oKuDCp3X9Ch3ZDCp)cJ75zPMhFa8pFN1)EXNnMF(5AF7X91z1Zl2ZMsD5UczHhmdZjWs5lhbePLIlH6UxsYkCkQCqaVOKQKcH1xz2Xdl2C8W7BSHaIUOYaxzYdH8VnxXxIlYQ7)jPiLLRnmVBTv4k2jwRmtGX36V2YKK5qUIijIg95HIaH0sAl4HusBt9EnmWwGWo)lE0cSLfrfS2iCspXoyOicvuE94GX(qBxoa5bTkgtQyyRJgV9h8j8Lj4ZqTXD(9vLFF1u1Xbu9f8yxKQI1BCEm8aCYOZk5ZhVyJ85RZzJoNnEUC2i2wjYPJBFaEBW9jOXj)68rb)yXZR3gpqePbT8BWRbYCYabEzGiVSSaeKwY0Q6x4R8xAWB6lMCDc9y6HFmlb6EF9xJVj30ui(4B))9VEBmWxjOFCQ1s(5FHFBwaXT30))p

**Comment by Abuhmeed** [comment]
I just installed bugsack & buggrabber and hopefully ill learn how they work, going to do few runs, ill get back to you

**Comment by Abuhmeed** [comment]
> You really need to install bugsack & buggrabber as asked in the issue template and tell us if you the error you have, otherwise your bugreport won't help us fix it for you and everyone.

ok the bugsack & buggrabber didnt show any bugs, not sure if i know how to use them or not

but i went to my WeakAuras > Load section

and I always had these 3 options checked

**"Not In Vehicle"    "Not In Pet Battle"    "Not Has Vehicle UI"**

and during some testing for a while in Siege, it seems like the having the option **"Not Has Vehicle UI"** Checked is what makes my weakaura disappear, i don't know why it makes my Weakauras permanently disappear, even after getting out of "Vehicle"

this dosent happen in a  none-instance content, only inside those 2 dungeons so far

**Comment by Abuhmeed** [comment]
was it my fault for having **"Not Has Vehicle UI"** checked, or is it an error needs fixing ?

**Comment by InfusOnWoW** [comment]
The error is already fixed, we just haven't released the fix yet.
