### ISSUE TITLE
Detection of Global Cooldown (boundary issue)

### ISSUE THREAD

**Issue by mltco78dhs** [WeakAuras/WeakAuras2#234]
What steps will reproduce the problem?  Create an aura with a required status trigger of inverse GCD.  Logout, log in with the aura active (or reload).  The trigger will report **_falsely_** that inverse GCD is **_false_**.

What is the expected output? What do you see instead?  Trigger **_should_** report that inverse GCD is **_true_**.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?  Yes.

What version of WeakAuras are you using?  2.4.9.1

Was it working in a previous version? If yes, which was the last good one?
No, this has never worked for me.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
Does not generate a bug.  It's not a hard error.

Please provide any additional information below.
Hitting ANY spell that fires GCD will make this work properly.  It seems that the GCD inverse is NOT reporting "is GCD NOT running" but is reporting "has the *last* GCD completed" - when no GCD has run yet at all, it returns false information.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by InfusOnWoW** [comment]
The issue was that we didn't run the trigger on login, which works fine for the normal case but not inverse.

**Comment by mltco78dhs** [comment]
Does that mean "We know it's messed up, but we're not fixing it" or does it mean "We know how to fix it and a fix is coming."  The answer is unclear.

**Comment by InfusOnWoW** [comment]
It's already fixed.
