### ISSUE TITLE
Weakauras don't work after 07/29/2020 beta update.

### ISSUE THREAD

**Issue by Vich79** [WeakAuras/WeakAuras2#2347]
## Describe the bug
After the 07/29/2020 Shadowland update, weakauras 2 do not work anymore.

**Do you have an error log of what happened?**
[image](https://user-images.githubusercontent.com/18463244/89001384-60729380-d2fa-11ea-9de8-1693f537fb15.png)

```
Message: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1667: attempt to call field 'IsPaused' (a nil value)
Time: Fri Jul 31 06:53:29 2020
Count: 7667
Stack: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1667: attempt to call field 'IsPaused' (a nil value)
[string "=[C]"]: in function `IsPaused'
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1667: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1666>

Locals: 
```

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
Tried with the latest Shadowland version, others from 1 to 4 days ago when it worked well. Even the retail version.
I've tried a complete reinstall of WoW Beta for Shadowland to get a from scratch test aswell.

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [] Retail
- [X] Shadowland beta

**Comment by InfusOnWoW** [comment]
You downloaded the wrong file, or didn't extract all files.

**Comment by Vich79** [comment]
I'm dumb, I downloaded the latest commit instead of latest alpha release. Sorry for your time, keep up the good work !
