### ISSUE TITLE
Error not receiving display information 

### ISSUE THREAD

**Issue by tixxilicious** [WeakAuras/WeakAuras2#2351]
When someone shares an aura i cant import, and they cant import if i share an aura.
![unknown](https://user-images.githubusercontent.com/32714745/89124475-8739f100-d4d7-11ea-9ee9-c9a1099217d9.png)
already tried to reinstall wa, but nothing changed. any ideas?

**Comment by InfusOnWoW** [comment]
Please answer the questions in the template.
