### ISSUE TITLE
[Bug][Shadowlands] 

### ISSUE THREAD

**Issue by gaveer** [WeakAuras/WeakAuras2#2352]
**Do you have an error log of what happened?**

```
2x ...erface\WeakAuras\RegionTypes\DynamicGroup.lua:1056: attempt to index local 'regionData' (a number value)
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1056: in function 'DoPositionChildrenPerFrame'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1172: in function 'DoPositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1039: in function 'PositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1020: in function 'SortUpdatedChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:827: in function 'Resume'
[string "@WeakAuras\WeakAuras-3.0.0-alpha4.lua"]:6435: in function <WeakAuras\WeakAuras.lua:6394>
[string "@WeakAuras\WeakAuras-3.0.0-alpha4.lua"]:6528: in function 'UpdatedTriggerState'
[string "@WeakAuras\GenericTrigger.lua"]:721: in function 'ScanUnitEvents'
[string "@WeakAuras\GenericTrigger.lua"]:872: in function <WeakAuras\GenericTrigger.lua:868
```

### To Reproduce

Doing Torghast Tower , used [Torghast Panel](https://wago.io/shadowlands-weakauras/pve/torghast) Weak aura , after reach like 3rd floor start to produced ( maybe more power to earn )

**Screenshots**

![image](https://user-images.githubusercontent.com/45834601/89126328-33360900-d4e5-11ea-882d-65ea1651e9ba.png)

**Which version of WeakAuras are you using?**

3.0.0-alpha4
**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [] Retail
- [x] Shadowlands
**Was it working in a previous version? If yes, which was the last good one?**

**Comment by mrbuds** [comment]
This is not an issue with the addon, you should report this to the author of this aura.

**Comment by gaveer** [comment]
ok

**Comment by emptyrivers** [comment]
There's nothing obviously wrong with the aura. I'll take a look.

**Comment by mrbuds** [comment]
@gaveer there was an update to this aura made today, it should have fixed your issue

**Comment by InfusOnWoW** [comment]
I think we should be more resilent against this kind of errors now.
