### ISSUE TITLE
Ticks only show up if Options are opened

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#2355]
## Describe the bug
Added ticks on a progress bar only show up if the WeakAuras options are open. 

**Do you have an error log of what happened?**
no error log

### To Reproduce

1. Create Progress Bar
2. Add Tick
3. Close options
4. Tick gone

**Screenshots**
can add later if requested

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Same error happens with only WA enabled.

**Which version of WeakAuras are you using?**
2.18.0

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
worked in previous version (2.17.12)

**Comment by InfusOnWoW** [comment]
With those settings the tick might not show up because it is out of bounds. You need to ensure that the trigger and the position of the tick fit together.
