### ISSUE TITLE
Menu location

### ISSUE THREAD

**Issue by ricerds** [WeakAuras/WeakAuras2#2361]
## Describe the bug

**Do you have an error log of what happened?**

```
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by ricerds** [comment]
When using all imported groups, such as Ipis warlock auras, a menu box pops up on top of the "cooldown text" box located in the display tab preventing a the box to be checked. This popup's locations in other parts of the program are ok, but as soon as the cursor is on top of  this box or on "cooldown text" next to it, then the menu popup appears. This is a new problem that began with the program update immediately proceeding today's update. Finally, I have to say that I absolutely love this addon and imo  it is by far the most important addon available in World of Warcraft. Thank you.

**Comment by InfusOnWoW** [comment]
I don't understand the problem, can you make screenshots showing it?

**Comment by InfusOnWoW** [comment]
I think I understand now, you are talking about the tooltip that shows up on hovering controls.

That tooltips position is not something we control, but that tooltip also does not prevent interacting with the control behind the tooltip.

**Comment by ricerds** [comment]
The second screen shot shows the location in the program with the cool down settings. The first screen shot shows the tooltip that pops up whenever my cursor is on the box as well as on the characters Show Cooldown. When I place my cursor directly over the box and attempt to click on it, the game pauses for a second, however I am still prevented from interacting with the box.  After receiving your response (thank you for responding so quickly) I disabled all addons and tried different screen resolutions hoping the tooltip would move, but it stayed at the same location. I tried to interact with the control each time and I still couldn’t activate that feature.  I remember this happened one time in the past after a weakaura program update during the Battle for Azeroth expansion. Some of the program’s settings reverted to default (as well as the tooltip problem). I was able to change the settings that defaulted back to mine, but still couldn’t interact with the control behind the tooltip. Fortunately, the tool tip was fixed ( I think it was moved to the right, but I just don’t remember for sure) within a short time allowing me to interact with that control. I apologize for not giving you more information in my first message.

**Comment by InfusOnWoW** [comment]
Please attach the screenshot to the ticket.

**Comment by ricerds** [comment]
![WoWScrnShot_080420_152146](https://user-images.githubusercontent.com/69169758/89425502-f25d1080-d6ed-11ea-9703-b918179aefcb.jpg)
![WoWScrnShot_080420_151902](https://user-images.githubusercontent.com/69169758/89425517-f7ba5b00-d6ed-11ea-8891-95327fe6df5f.jpg)

The first picture shows the page in weakauras where the control is located.  The second picture shows what happens when i place my cursor on top of the box and text next to the box. The game does pause when I attempt to interact with the control, but nothing else happens. The Show Cooldown box still remains unchecked. It seems strange that a program update would change the location of only 1 tooltip. Just a review: I disabled all addons except weakauras and had the same result. I even tried changing the screen and game resolution hoping the tooltip would move, but had no luck.

**Comment by InfusOnWoW** [comment]
So the problem is only reproducable with the aura pack that is visible in your screenshot. With that I can reproduce it.

It would helped a lot if you'd actually filled out the template properly and included the auras that showed the problem immediately. You've wasted a lot of our time by ignoring that template.
