### ISSUE TITLE
Doesn't play well with Kibs Item Level

### ISSUE THREAD

**Issue by hahuang65** [WeakAuras/WeakAuras2#237]
What steps will reproduce the problem?
If you enable both WeakAuras2 and Kibs Item Level

What is the expected output? What do you see instead?
When you open the /wa panel and select a display to edit, the right side of the options panel where all the configuration happens will not appear.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes, I systematically binary-searched my addons until I narrowed it down to Kibs Item Level.

What version of WeakAuras are you using?
Latest on Twitch: 2.4.9.1

Was it working in a previous version? If yes, which was the last good one?
Not sure, this is the first version I've used.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by Stanzilla** [comment]
Well WA work without Kib's so it's more a bug in Kib's than in WA.

**Comment by InfusOnWoW** [comment]
Yeah, that's a bug in Kibs
