### ISSUE TITLE
Allow Multiple Items Equipped

### ISSUE THREAD

**Issue by danjohnso** [WeakAuras/WeakAuras2#2375]
**Is your feature request related to a problem? Please describe.**
I have a WA that uses a common rollup WA for sub pieces.  The sub pieces all activate on different gear pieces being equipped, but I can't add multiple gear options to the rollup

**Describe the solution you'd like**
Allow an multiple items to be a load condition, be nice to have ANY and ALL option with it

**Describe alternatives you've considered**
Custom function to look at Item Ids

**Comment by InfusOnWoW** [comment]
I don't understand the use case at all, can you explain it?

**Comment by danjohnso** [comment]
I am modifying a WA that looks like this:
![image](https://user-images.githubusercontent.com/852995/89716508-1f6e2500-d973-11ea-9304-fbd2a813c1e1.png)

I need the workhorse WA to be loaded anytime I have any of a list of items equipped.  For example, I only show the Nature Resistance WA if I am wearing Fangdrip Runners, so I would also need to load the workhorse WA when wearing that item.  I only show the Fire Resistance WA if I am wearing a piece of Black Dragonscale, but I again need the workhorse  loaded in that scenario as well.  Right now, the Item Equipped load option only allows selecting a single item, but I would like it to allow selecting any of a list of items.

**Comment by InfusOnWoW** [comment]
Right that's too niche as a usecase.
