### ISSUE TITLE
WeakAuras 3.0.0-alpha4-6 -- Stormstrike & "Spell in Range" Condition bugged

### ISSUE THREAD

**Issue by ByucknahTheRed** [WeakAuras/WeakAuras2#2376]
Messing around with WeakAuras on the Alpha for the past few builds I have noticed that the condition "Spell in Range" is not properly functioning with the spell Stormstrike. It functions properly on Live with WeakAuras 2 and it functions properly with other spells like Lava Lash, shock's, etc. but the function does not seem to properly trigger with the ability Storm Strike on Beta.

**Comment by Crelam** [comment]
IIRC this is an issue with the WoW api.

Try using Primal Strike instead.
https://shadowlands.wowhead.com/spell=73899/primal-strike

**Comment by ByucknahTheRed** [comment]
Very interesting. Using Primal Strike works, however using "Exact Spell Match" and the spell id "73899" does not work.

But yeah, using Primal Strike instead works! Thank you very much for the advice as a work around!

**Comment by InfusOnWoW** [comment]
I can't reproduce that, with !WA:2!DrvZUTTrq4kid0uHI0yvhJ6EYnOnOTa1nXa1xlevKSDQIKkjDT7jPLKJ4U1u7YU7sjlJEj6KVw9iOZ9KEe8tabrAFa8JGFc6SR(bXHhiNz2DNVD(MVHLAwDy1OQr38vYR6myGc0LKtwzSGWdPczxbJRdQ3OTFd3IqHijsmM7nMLc9VDTBJOyGkjHAMGRoYvPjsDLGbmotrR4GF0vMQLS4yqQE8ZLRmVP6DzkOhjqjKbVreb9lIboizHEuX4o85k8tTKXKjkNmmhbPjKjGCEeeKnyG)KuqEsJwDBEwlhn6eGWQZu3PYcGrax7HBID1IE1R553ZZVMR)udCMm13LtgcQkU2nMUx9v1X(DLIyjOu7)TEPqsY3TjzDLaMmxVUnA1QqcKe76TXSSWtNjhQcPjK4cdaQ1R0FQ180ivLzBc(O6VtMXT50HKPftJYKedVv9LZmNwJ04L9t32y)a2O)Sm(kIB38hN)zPBB47rG)Yyg(7F(O7XEfi5KKFdzAmPhF)LaKwdrpu7AGHoJWzdTaEu(JAElquGNwc8yn9JZ3XHl4qX6RupdTkvqOGhPMA2QH0ZpWziHXBM)d4bYpi)hZFr(lXVFYhgbBukSJG5cOZrI0fIn6JV)MDsRQHR09uucY6xSsVLUNnO91aHeVK9uRmYpy2M1E23OsFY7D86IeH81LkvQ8DlJcjdSAwNAN53j9ZTbnmTPQdpNfPPo1q37xce7kiYg8Tfl17)(QRZT21)JmLMnys(wZLcuEb(yqN2DA3iFhjwsM9m3UXq71Om(mBvfGcRN0uYUE)FnJeHKazFF)hu4RrQWgBSqgDUKKo98vglVaJykwqc0Fvn)EZKPBFA72nC750X3VZBCp94t8l2aTh7AyVvv0fpahZQ2zNoN53602n(VI4eX4Ms4pZaE4KUB9Ido8NwwDMfwyETodtnoMdxeKP1cENrGeNjNBc3YQHEQD)RRSzgN6ByMBrr9XRJqDmlsTO7tzHxYX5UY2t4fssGLMTyy4TTa4G8ciPbuGft1V1jrqIoYXiT31DywIMvXnmHOu7MtQ4OW63ymxAfDM7Sdd1XZ2ipY3ka9hWIR4sssPKYoxledlL)19NRfHJwo)8fL693pJfDyByC6oR)BNrd8kMIGTLi6IbsCQghHWgC57xs4nnHmqg4v3TrJ2fO8dd3j1()XkhMXIwq872EWjxp5xoHjzCdCa1DSviMd9NBg5y2T)Lp3nKcHxEu(NwE6iIKzW92L)zH7s4XG7issgusgsnE4bYN86YN8Z)7tTpLkpnvkW(TEIRvKoDDDqZ)lBBPQ6WxbJQo6Dx8)d

It seems to work for me.

Though note, that even if it was currently bugged, that would be almost certainly a blizzard bug, and I wouldn't look into a workaround until much closer to the release.

**Comment by Crelam** [comment]
I was able to recreate the issue, using the WA provided.  It only occurs when you log in as Enhancement.  Swapping specs to Enhancement fixes the it until you log in again as Enhancement.

Its definitely a blizzard bug and hopefully it'll be fixed before release.
