### ISSUE TITLE
Hidden trigger

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#2378]
## Describe the bug
Import https://wago.io/cCG9gEf6U
Trigger 2 does not show, but the dynamic information option and required for activation option does, adding a new trigger show as trigger 3

I don't know how to reproduce this bug from scratch

**Comment by InfusOnWoW** [comment]
They do have a second trigger, but that trigger has no type. Which is very strange.

**Comment by mrbuds** [comment]
i talked with author on the discord he made, he made his auras on retail, and i imported them on classic

**Comment by mrbuds** [comment]
i still don't understand how he happen to have such a corrupted trigger
