### ISSUE TITLE
Weakauras has the Classic client in the Retail tab and is overriding retail's package.

### ISSUE THREAD

**Issue by Asthlynn** [WeakAuras/WeakAuras2#2380]
https://gyazo.com/b87cb7e3f3da00d0e9bd2ec5364bee79

I'm not used to doing things manually on the addons and do it via the Twitch Client.

**Comment by emptyrivers** [comment]
Well, then this is your lucky day to learn a new skill! Here is a helpful guide https://www.wowhead.com/addons-how-to-install-and-maintain#installing

**Comment by InfusOnWoW** [comment]
Rivers didn't mention it, so I'll do it. This is a bug in the twitch client, we can't do anything about it.

**Comment by abeiter19** [comment]
You can also "downgrade" your version by going to WeakAuras in Twitch client, clicking versions, and installing the correct version.
