### ISSUE TITLE
Any retail players just get a classic version of WeakAuras installed from twitch

### ISSUE THREAD

**Issue by Kirbdawg** [WeakAuras/WeakAuras2#2385]
- [ X] Retail

WA is not loading since I updated from twitch.   It appears that I got the classic version of WA installed after I updated.  I'm getting this message:   

""WeakAuras:  This version of WeakAuras was packaged for World of Warcraft Classic.  Please install the etail version instead.  If you are using the Twitch Client, then contact Twitch Support forurther assistance and reinstall weakauras manually.""

This is just an FYI.   I'll try to find the correct version or restore my backup.   But there appears to be only one version on twitch, and it's not the one for retail.

**Comment by SebastianKC** [comment]
This happened on my PC but for some reason my laptop grabbed the correct version.

**Comment by InfusOnWoW** [comment]
This is a problem in the twitch client, which we have no control over.
