### ISSUE TITLE
Weak Auras may have updated and changed it to classic not retail version of WoW? I'm using Twitch client

### ISSUE THREAD

**Issue by Lockraw** [WeakAuras/WeakAuras2#2386]
## Describe the bug

My Weak Auras are no longer showing up and I get message in the chat window when I log in referring to WeakAuras version is for WoW Classic.  See message below.  I use the Twitch client and the WA worked fine before but maybe there was an update that caused this problem?  I don't know if you have gotten any other feedback related to this.  Wehn I search for WeakAuras in Twitch I cannot find it anymore?

**Do you have an error log of what happened?**

```
The Error is just a message that reads, "This version of WeakAuras was packaged for World of Warcraft Classic. Please install the retail version instead. If you are using the Twitch client, then contact Twitch Support for further assistance and reinstall WeakAuras manually."
```

### To Reproduce

Nothing to click on y WeakAuras are gone or unusable.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
Twitch is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing Retail on Classic and vice versa. Ensure that you have got the right version selected but if you do and it still installs the wrong version then you may have to just install manually with the zip.
You can get the latest versions from:
• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2 
    (see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
    (See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like https://github.com/AcidWeb/CurseBreaker or https://www.minion.gg/

**Comment by Lockraw** [comment]
I was using the retail version but after the update it reads it as classic in Twitch so I don't know what happened? I have never installed the classic version though I probably updated it without even noticing that it was changing?

**Comment by emptyrivers** [comment]
This is a known issue with the twitch app.

**Comment by Lockraw** [comment]
Yes I see your answer thank you.  I will do that and just wanted to let you know this happened.  Very fast response...much appreciated!!

**Comment by Lockraw** [comment]
Just FYI, in Twitch if you go to WeakAuras and then to versions, you can select the 2.18.1.zip instead of the 2.18.1.g*****.zip which is probably the WoW Classic one because that is the one I had when this started.  IT is working now and from the Twitch client but not the normal route to downloading it.

Thanks again for your fast response that was unexpected!!
