### ISSUE TITLE
Weakauras Update 12/08/2020 (22:00 GMT+2)

### ISSUE THREAD

**Issue by RamzGlory** [WeakAuras/WeakAuras2#2387]
Hey so i was playing retail and out tabed to see if there was any update available for the addons that i use, and there was one for 
my (Weakauras), I updated it and it changed from "Weakauras-2.18.1.zip" to "Weakauras-2.18.1-classic.zip" and the version changed from 8.3.0 to 1.13.5 i've never played classic and i don't have it downloaded i only play retail.

![image](https://user-images.githubusercontent.com/28738498/90064789-9268fa00-dceb-11ea-9970-c16f9de23745.png)

Before Update
-----------------------------------------------------------------------------------------------------------------------------------------
 After Update
![image](https://user-images.githubusercontent.com/28738498/90064722-7d8c6680-dceb-11ea-9218-e3dfc542b858.png)

Update;
If you run into this problem click on the "Weakauras" and then go to "Versions" and download the one that says (2.18.1 Release) and it should be fixed.

**Comment by InfusOnWoW** [comment]
Twitch is known to occasionally serve the wrong version of addons when installing via the app - i.e. installing Retail on Classic and vice versa. Ensure that you have got the right version selected but if you do and it still installs the wrong version then you may have to just install manually with the zip.
You can get the latest versions from:
• CurseForge: https://www.curseforge.com/wow/addons/weakauras-2
(see the Recent Files section, bottom right, for both versions)
• WoWInterface: https://www.wowinterface.com/downloads/info24910-WeakAuras2.html
(See C and R on the right)

To avoid this kind of issue entirely you might consider looking into alternatives to Twitch like https://github.com/AcidWeb/CurseBreaker or https://www.minion.gg/
