### ISSUE TITLE
Optional "Smooth Progress" for Overlay Bars

### ISSUE THREAD

**Issue by Grimonja** [WeakAuras/WeakAuras2#2388]
**Is your feature request related to a problem? Please describe.**
Transitions are snappy when you use  "Smooth Progress" on a bar with an overlay .
This happens because overlays are not animated while bar it self is. 

This can be seen in this sample WA that i made to showcase the issue:
https://dl.dropboxusercontent.com/s/a1w8l9jm55ai99i/OJx3HApKUw.txt

**Describe the solution you'd like**
I would like an additional optional field in "additionalProgress" entry that would indicate if transition should be smoothed.

**Additional context**
I came to this problem while making a Insanity bar with prediction. In some cases even if you have "Smooth Progress" you want an overlay change to be instant(CAST_START,CAST_END). But in some cases you want to to be animated(Void Torrent,Death and Madness recovery).

**Comment by InfusOnWoW** [comment]
That's too niche. Unless someone comes with a PR, that's out of scope.

Also you can obviously implement a smooth transition in your custom code for the overlay.
