### ISSUE TITLE
Updating Issue with Groups

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#2391]
## Describe the bug
If you update a group with Weakauras in it from Wago, the option to "update the group" is missing.
This works with single Auras copied from Wago, but if you put the same Aura into a group and try to update it then the option is missing. I tried it with 2 Versions of the same Aura (changed the Spell ID). One time I tested it without a Group, just the single WA. The second time I put the WA into a group and tried the same procedure.

**Do you have an error log of what happened?**
No log

### To Reproduce

ISSUE:
1. Go to Wago.io
2. Copy Import String of Version 1.0 UpdateTestGroup: https://wago.io/85SnqXBux/1.0.0
3. Import to WoW
4. Copy Import String of Version 2.0 UpdateTestGroup: https://wago.io/85SnqXBux
5. Import to WoW --> No option to update the group

Proof that it works without Group:
1. Go to Wago.io
2. Copy Import String of Version 1.0 UpdateTestSingle: https://wago.io/8LTES0mZg/1.0.0
3. Import to WoW
4. Copy Import String of Version 2.0 UpdateTestSingle:  https://wago.io/8LTES0mZg
5. Import to WoW --> Update Option available

**Screenshots**

Try updating Group:
![grafik](https://user-images.githubusercontent.com/55335747/90255678-e76c5380-de44-11ea-95c5-de4e20f5401c.png)

Try updating Single:
![grafik](https://user-images.githubusercontent.com/55335747/90255625-d28fc000-de44-11ea-968b-e478c3395dfc.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes

**Which version of WeakAuras are you using?**
2.18.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

- Wago-Link GroupWA: https://wago.io/85SnqXBux

- Wago Link SingleWA: https://wago.io/8LTES0mZg

**Comment by emptyrivers** [comment]
This is working as designed.

**Comment by Breakerzeus** [comment]
Wait what? So it's intended to not let you update whole Packages? So it was a Bug that stayed in the whole Addon until now? Sorry but i doubt that, seriously.

**Comment by emptyrivers** [comment]
> Wait what? So it's intended to not let you update whole Packages? So it was a Bug that stayed in the whole Addon until now? Sorry but i doubt that, seriously.

Yes, this system was indeed designed so that a group import will only update the group (and any children), and a single aura import will only update an aura which is not a member of a group. This was done to avoid confusion in the scenario where certain auras published by one user are often republished in groups by other users. If we naively updated auras that matched the ones being imported, then importing one group might cause breaking changes to an entirely unrelated group, with no good way to realize what exactly caused that change.

No, the solution isn't perfect and we knew that when it was being developed. Perhaps in the future we might develop an improvement, but for now this is a deliberate limitation.

**Comment by emptyrivers** [comment]
#1881, #1031, and especially #1512 are also relevant to this discussion, if you are curious.

**Comment by Breakerzeus** [comment]
> Yes, this system was indeed designed so that a group import will only update the group (and any children), and a single aura import will only update an aura which is not a member of a group. 
But exaclty that does not work. If I import a group, then the group AND the children should be updated, shouldn't it?
Just in case you misunderstand this: I import a WA that is in a group. then this group is updated on wago and i like to import it as well. That is the case where it should give me the option to update. I want to update the exact same package that I imported a while ago, just an updated one.
I just remembered, there even were options to add new auras or remove auras that where not in the updated package on wago anymore. So that seems to be working like you wanted if there is this option. I can't understand why this should be not wanted now.

EDIT: Just for the understand which impact this have: if you download a whole raid package from Reloe or someone else, you can't update it. You have to delete the old one and then you can import it as new package. Sorry but this cannot be intended.

**Comment by InfusOnWoW** [comment]
I can reproduce the issue.
