### ISSUE TITLE
global condition for GetInstanceInfo (difficultyID) would be neat

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2394]
**Is your feature request related to a problem? Please describe.**
Boss mechanics tend to change based on difficulty and this feature would make it easier to create raid-difficulty based conditions.

**Describe the solution you'd like**
Simply a global conditon that allows you to check for normal, heroic, mythic raid difficulty.
https://wow.gamepedia.com/DifficultyID

**Describe alternatives you've considered**
run custom code & add instance check there but that also requires all properties to be coded

**Additional context**
https://wow.gamepedia.com/API_GetInstanceInfo (3rd arg)
https://wow.gamepedia.com/DifficultyID
14 = normal
15 = heroic
16 = mythic

**Comment by InfusOnWoW** [comment]
Can you list a few examples of actual abilities where that would be useful? 

This sounds far too niche for my taste.

**Comment by Causese** [comment]
On shadowlands beta there is a boss (Huntsman Altimor) that applies a debuff that does different things based on which add is active.

Trigger1: Tracks debuff
Trigger2: Tracks unit characteristics - boss

condition:
if t1 and t2 npc id == xyz then do things.

this condition is repeated 3x

**Comment by InfusOnWoW** [comment]
You know, that you can now easily do that with a custom condition check?

**Comment by Causese** [comment]
Yea i know that there are custom coding solutions. I assume the one presented with "Run custom code" is better in this case
