### ISSUE TITLE
Position Locking

### ISSUE THREAD

**Issue by EJ-K** [WeakAuras/WeakAuras2#2395]
**Is your feature request related to a problem? Please describe.**
It's irritating when you accidentally move a WeakAura. Allow us to "lock" the position of individual WeakAuras (disable drag and the x/y-offset options), as for most WeakAuras, once they're set up once, you don't need to touch them again. Alternatively, lock our their options altogether until you explicitly unlock them.

**Describe the solution you'd like**
An option in the right-click menu or display options of individual WeakAuras or WeakAura Groups to disable the ability to move them.

**Describe alternatives you've considered**
None

**Additional context**
This is a feature in a number of addons (ExRT/Details) for the reasons stated above, please consider adding this to WeakAuras.

**Comment by InfusOnWoW** [comment]
I don't think that's entirely unresaonable, though note that other addons need to have that, because they typically allow moving while the options are closed. We don't.

**Comment by EJ-K** [comment]
That's true - I was just trying to give some context to the idea the it's annoying to move things by accident.

**Comment by C9Agent** [comment]
Seconding the issue - it's entirely frustrating when working with large numbers of WA like I do (I build entire UI's for each class and have dozens of WA's displayed at a time) and accidentally moving or rescaling something. Currently you can move and rescale stuff that isn't explicitly being worked on - ie, selected on the left side column. I'd love a lock feature that prevents anything related to a WA being adjusted if it's not selected on the left.

**Comment by AdrieAdrie** [comment]
I was about to request this feature. I would love to be able to "lock" a WA. E.g. not being able to delete or move a WA.

**Comment by whitepawn23** [comment]
I have modified the version: 2.18.4-14-gf325373
concerning game version 80300 with a new option (Lock/Unlock) for groups or items.
It may not be the best option but it sure does the job.

**To lock/unlock Group or Item by mouse down event**
AddOns\WeakAurasOptions\OptionsFrames\MoverSizer.lua
locate: mover.startMoving = function()
_add these lines at then beginning of the function_
`		if (data.locked ~= nil and data.locked) then
			return
		end`

AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua
locate: ["Initialize"] = function(self)
_add this new line after self.callbacks = {}_
`self.utils = {}`

locate: function self.callbacks.OnDeleteAllClick()
_add these new functions after the OnDeleteAllClick function_
```
function self.callbacks.onLockToggleGroupClick()
  if (WeakAuras.IsImporting()) then return end;
  local toLock = {}
  if(data.controlledChildren) then
	local region = WeakAuras.regions[data.id];
	if (region.Suspend) then
	  region:Suspend();
	end
	data.locked = self.utils.toggle(data.locked)
	for _, id in pairs(data.controlledChildren) do
	  local child = WeakAuras.GetData(id)
	  child.locked = data.locked
	end
  end
end			
function self.callbacks.onLockToggleItemClick()
  if (WeakAuras.IsImporting()) then return end;
  local item = WeakAuras.GetData(data.id)
  item.locked = self.utils.toggle(item.locked)
end		
function self.utils.toggle(v)
  if v == nil then
	return true --default toggle value
  end
  return not v
end	
```

locate: L["Delete children and group"]
_add these lines after if statement_
```
if (data.controlledChildren) then      
  tinsert(self.menu, {
	text = "Lock/Unlock",--no lang support on this version
	notCheckable = true,
	func = self.callbacks.onLockToggleGroupClick
  });
else
  tinsert(self.menu, {
	text = "Lock/Unlock",--no lang support on this version
	notCheckable = true,
	func = self.callbacks.onLockToggleItemClick
  });
end
```

**To lock/unlock Group or Item by position settings slider**
AddOns\WeakAurasOptions\CommonOptions.lua
locate: xOffset table ( xOffset = { )
_inside set function add these lines at then beginning of set function_
```
if (data.locked ~= nil and data.locked) then
	return
end
```

locate: yOffset table ( yOffset = { )
_inside set function add these lines at then beginning of set function_
```
if (data.locked ~= nil and data.locked) then
	return
end	
```

**To lock/unlock Group or item move buttons**
AddOns\WeakAurasOptions\OptionsFrames\MoverSizer.lua
locate: function moveOnePxl
_add these lines at then beginning of "if data then"_
```
if (data.locked ~= nil and data.locked) then
	return
end	
```
[wa lock-unlock.zip](https://github.com/WeakAuras/WeakAuras2/files/7770935/wa.lock-unlock.zip)

**Comment by whitepawn23** [comment]
> He modificado la versión: 2.18.4-14-gf325373 relativa a la versión del juego 80300 con una nueva opción (Bloquear / Desbloquear) para grupos o elementos. Puede que no sea la mejor opción, pero seguro que funciona.
> 
> **Para bloquear / desbloquear grupo o artículo por ratón de eventos** addons \ WeakAurasOptions \ OptionsFrames \ MoverSizer.lua localizar: mover.startMoving función = () _añadir estas líneas a continuación, a partir de la función_ ` if (data.locked ~= nil and data.locked) then return end`
> 
> AddOns \ WeakAurasOptions \ AceGUI-Widgets \ AceGUIWidget-WeakAurasDisplayButton.lua localizar: ["Initialize"] = function (self) _agregar esta nueva línea después de self.callbacks = {}_ `self.utils = {}`
> 
> localizar: función self.callbacks.OnDeleteAllClick () _agregue estas nuevas funciones después de la función OnDeleteAllClick_
> 
> ```
> function self.callbacks.onLockToggleGroupClick()
>   if (WeakAuras.IsImporting()) then return end;
>   local toLock = {}
>   if(data.controlledChildren) then
> 	local region = WeakAuras.regions[data.id];
> 	if (region.Suspend) then
> 	  region:Suspend();
> 	end
> 	data.locked = self.utils.toggle(data.locked)
> 	for _, id in pairs(data.controlledChildren) do
> 	  local child = WeakAuras.GetData(id)
> 	  child.locked = data.locked
> 	end
>   end
> end			
> function self.callbacks.onLockToggleItemClick()
>   if (WeakAuras.IsImporting()) then return end;
>   local item = WeakAuras.GetData(data.id)
>   item.locked = self.utils.toggle(item.locked)
> end		
> function self.utils.toggle(v)
>   if v == nil then
> 	return true --default toggle value
>   end
>   return not v
> end	
> ```
> 
> localizar: L ["Eliminar niños y grupo"] _agregar estas líneas después de la declaración if_
> 
> ```
> if (data.controlledChildren) then      
>   tinsert(self.menu, {
> 	text = "Lock/Unlock",--no lang support on this version
> 	notCheckable = true,
> 	func = self.callbacks.onLockToggleGroupClick
>   });
> else
>   tinsert(self.menu, {
> 	text = "Lock/Unlock",--no lang support on this version
> 	notCheckable = true,
> 	func = self.callbacks.onLockToggleItemClick
>   });
> end
> ```
> 
> **Para bloquear / desbloquear el control deslizante de configuración de Grupo o Elemento por posición** AddOns \ WeakAurasOptions \ CommonOptions.lua ubique: tabla xOffset (xOffset = {) _dentro de la función de conjunto agregue estas líneas al comienzo de la función de conjunto_
> 
> ```
> if (data.locked ~= nil and data.locked) then
> 	return
> end
> ```
> 
> localizar: tabla yOffset (yOffset = {) _dentro de la función de conjunto agregue estas líneas al comienzo de la función de conjunto_
> 
> ```
> if (data.locked ~= nil and data.locked) then
> 	return
> end	
> ```
> 
> **Para bloquear / desbloquear botones de movimiento de grupo o elemento** AddOns \ WeakAurasOptions \ OptionsFrames \ MoverSizer.lua localice: función moveOnePxl _agregue estas líneas al principio de "si datos entonces"_
> 
> ```
> if (data.locked ~= nil and data.locked) then
> 	return
> end	
> ```
> 
> [wa lock-unlock.zip](https://github.com/WeakAuras/WeakAuras2/files/7770935/wa.lock-unlock.zip)

only prevents the movement of groups or items, not their deletion.

**Comment by whitepawn23** [comment]
I have modified the version: 2.18.4-14-gf325373
concerning game version 80300 with a new option (Lock/Unlock) for groups or items.
It may not be the best option but it sure does the job.

**To lock/unlock Group or Item by mouse down event**
AddOns\WeakAurasOptions\OptionsFrames\MoverSizer.lua
locate: mover.startMoving = function()
_add these lines at then beginning of the function_
`		if (data.locked ~= nil and data.locked) then
			return
		end`

AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua
locate: ["Initialize"] = function(self)
_add this new line after self.callbacks = {}_
`self.utils = {}`

locate: function self.callbacks.OnDeleteAllClick()
_add these new functions after the OnDeleteAllClick function_
```
function self.callbacks.onLockToggleGroupClick()
  if (WeakAuras.IsImporting()) then return end;
  local toLock = {}
  if(data.controlledChildren) then
	local region = WeakAuras.regions[data.id];
	if (region.Suspend) then
	  region:Suspend();
	end
	data.locked = self.utils.toggle(data.locked)
	for _, id in pairs(data.controlledChildren) do
	  local child = WeakAuras.GetData(id)
	  child.locked = data.locked
	end
  end
end			
function self.callbacks.onLockToggleItemClick()
  if (WeakAuras.IsImporting()) then return end;
  local item = WeakAuras.GetData(data.id)
  item.locked = self.utils.toggle(item.locked)
end		
function self.utils.toggle(v)
  if v == nil then
	return true --default toggle value
  end
  return not v
end	
```

locate: L["Delete children and group"]
_add these lines after if statement_
```
if (data.controlledChildren) then      
  tinsert(self.menu, {
	text = "Lock/Unlock",--no lang support on this version
	notCheckable = true,
	func = self.callbacks.onLockToggleGroupClick
  });
else
  tinsert(self.menu, {
	text = "Lock/Unlock",--no lang support on this version
	notCheckable = true,
	func = self.callbacks.onLockToggleItemClick
  });
end
```

**To lock/unlock Group or Item by position settings slider**
AddOns\WeakAurasOptions\CommonOptions.lua
locate: xOffset table ( xOffset = { )
_inside set function add these lines at then beginning of set function_
```
if (data.locked ~= nil and data.locked) then
	return
end
```

locate: yOffset table ( yOffset = { )
_inside set function add these lines at then beginning of set function_
```
if (data.locked ~= nil and data.locked) then
	return
end	
```

**To lock/unlock Group or item move buttons**
AddOns\WeakAurasOptions\OptionsFrames\MoverSizer.lua
locate: function moveOnePxl
_add these lines at then beginning of "if data then"_
```
if (data.locked ~= nil and data.locked) then
	return
end	
```

**To prevent delete Group or item**
AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua
locate: function self.callbacks.OnDeleteClick()
_add these lines after if (WeakAuras.IsImporting()) then return end;_
```
if data.locked then 
	return 
end
```
locate: function self.callbacks.OnDeleteAllClick()
_add these lines before  for _, id in pairs(data.controlledChildren) do_
```
if data.locked then 
	return 
end
``
[wa lock-unlock.zip](https://github.com/WeakAuras/WeakAuras2/files/7770995/wa.lock-unlock.zip)
`
