### ISSUE TITLE
Add Trigger Scroll Position

### ISSUE THREAD

**Issue by jec324** [WeakAuras/WeakAuras2#2399]
## Describe the bug

When you have a single trigger and click the "+" or "Add" trigger the window scrolls/jumps to the 2nd trigger.  Further additions do not scroll/jump the user to the new trigger location.  Also, there's no UI/UX feedback that the add was successful.  

**Do you have an error log of what happened?**

```
PASTE ERROR HERE
```

### To Reproduce

Click Add trigger once (thereby adding a 2nd trigger, window jumps to trigger 2)
Click Add trigger again (thereby adding a 3rd trigger, window doesn't jump at all)

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

Latest release for Beta, have not had the chance to test on other game versions at this time. 

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

Unknown, I only recently learned of the feature when testing for S-lands.

**Comment by InfusOnWoW** [comment]
We actually don't have any automatic scrolling behaviour, though I can take a look at what we can do.

**Comment by jec324** [comment]
I isolated this issue down to a bug in another addon that a friend hasn't fully published, he was doing some very ill-advised things with ace which caused some rather interesting effects.  When removed everything appears normal.  I'd like to close this bug and add a feature request for the functionality as I think it might be something we should look to add in.
