### ISSUE TITLE
Operator in Status-Range Check is broken

### ISSUE THREAD

**Issue by bitfluxhound** [WeakAuras/WeakAuras2#2417]
## Describe the bug
Testing weakaura that triggers when
Range Check distance to unit us >5 and <25.
The weakaura only triggers when it's >5 and >25 (possibly =25).
Works correctly with <= 25 operator.

**Do you have an error log of what happened?**

```
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by Sethadon** [comment]
confirmed; seems to be that the < operator is not working correctly

Steps:

1. Create Range Check Trigger < X (not working)
1. Create Range Check Trigger =< X (working)

**Comment by mrbuds** [comment]
Trigger is wroking fine for me, can you export your example ?

**Comment by mrbuds** [comment]
no example given.

**Comment by bitfluxhound** [comment]
Here is the export https://wago.io/95penyNV_
Here is the video evidence on Retail and Beta (Versions used are Alpha 3.0.0 for beta and 2.17.12 for retail)
https://www.twitch.tv/videos/725429277

Total operators that do not work - Distance < X ; Distance = X ; Distance != X

**Comment by bitfluxhound** [comment]
Tested with 2.18.2
< behaves as >
= behaves as > 
!= behaves as >
