### ISSUE TITLE
Green confirmation aura of the trading window disappears after weakauras2 is enabled in WoW Classic

### ISSUE THREAD

**Issue by liule024** [WeakAuras/WeakAuras2#2421]
After weakauras2 is enabled in WoW Classic, if you click "Trade" button in the trade window, the green overlay on the transaction item list will show and soon disappear.

Under normal circumstances, the green overlay should last until the end of the trading.

Only used weakauras2(Latest version - 2.18.2-classic)

**Comment by mrbuds** [comment]
WeakAuras has no interaction with the trade window and i can't reproduce your issue.
