### ISSUE TITLE
Double timers. Wa is affected by blizzard timers

### ISSUE THREAD

**Issue by BohdanPenchukov** [WeakAuras/WeakAuras2#2424]
Hi. I have activated blizzard timers
![image](https://user-images.githubusercontent.com/23499600/91388765-b0cd0a80-e840-11ea-8fb6-ef0119d1564f.png)
And i have double timers in any wa
![image](https://user-images.githubusercontent.com/23499600/91388801-c6dacb00-e840-11ea-968f-4b060de19eb2.png)
I dont have this bug on retail. I use blizz timers for action bars but no need them in wa. Change it if its possible please

**Comment by asaka-wa** [comment]
disable or delete the WA texts on your Auras if you don't need them. The settings for that can be found in the Display tab.

**Comment by BohdanPenchukov** [comment]
But i need them. This text is customisable. Default blizzard is not
