### ISSUE TITLE
aura cast type channel inverse issue

### ISSUE THREAD

**Issue by hugo400** [WeakAuras/WeakAuras2#2425]
## Describe the bug

I have created a trigger with this setting. Status/cast/unit-player/cast type-channel(spell)/inverse
To show the aura while I am not casting a spell type Channel. I did not show the aura when I casted Regrowth which is a type cast spell.

**Do you have an error log of what happened?**NO
NO ERRORS AT ALL

```
PASTE ERROR HERE
```

### To Reproduce

I click regrowth then the aura dissapear.

**Screenshots**
 https://wago.io/0mmosnIZz

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**Yes

**Which version of WeakAuras are you using?**2.18.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
There's is no cast type setting if inverse is active.
