### ISSUE TITLE
Aura '250168' used in Client PlayerCondition '32509' is not known.

### ISSUE THREAD

**Issue by kyleatcodeandtheory** [WeakAuras/WeakAuras2#2426]
## Describe the bug
Logged in today and my weak auras are now throwing an error whenever I try to edit them.

![Capture](https://user-images.githubusercontent.com/50026048/91452643-cf390300-e84c-11ea-9c90-30327dbef8f9.PNG)

### To Reproduce
By opening Weak Auras, in game, this error immediately pops up.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I had only Weak Auras and Details for Shadowlands enabled.

**Which version of WeakAuras are you using?**
9.0 release

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [X ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
It was working yesterday.

**Comment by mrbuds** [comment]
This is an issue on WoW's client side, it should be fixed in a future PTR release, but we can't do anything about it.
