### ISSUE TITLE
Weakaura completely broken

### ISSUE THREAD

**Issue by albinvalastig** [WeakAuras/WeakAuras2#2429]
Hello!

Since three hours ago my weakauras and the addon itself have been completely broken. Some of my auras refuse to load, even though they have been for several months before this and at this point I can't even open the addon ingame. When I reload my client random amounts of my weakauras show up, sometimes it's 4 of them and so on. Sometimes even everything loads properly but even though it appears to work I cannot open the addon.

Things I've tried up until the time of writing this:

Reinstalling Wow, both completely fresh and once with my WTF and Addons folders pasted in afterwards.
Reinstalling the Addon and reimporting the Weakauras.

None of this seems to work and I'm now clueless as to what to do next.

Screenshots from 3 reloads done after eachother:
[https://gyazo.com/71886fe106c7d5ea45d99d38039cb2f7](url)
[https://gyazo.com/b4723a8431f09501672338ccf282cef6](url)
[https://gyazo.com/80c9c0de45a438678363d1206aa50fad](url)

[Weakaura.zip](https://github.com/WeakAuras/WeakAuras2/files/5143250/Weakaura.zip)

Errorcode from BugSack:
93x [string "--[==[ Error in 'Int Pot Mängd':'condition..."]:13: attempt to index field 'name' (a number value)
[string "--[==[ Error in 'Int Pot Mängd':'condition checks' ]==] local newActiveConditions = {};
local propertyChanges = {};
local nextTime;
return function(region, hideRegion)
  local id = region.id
  local cloneId = region.cloneId or ''
  local activatedConditions = WeakAuras.GetActiveConditions(id, cloneId)
  wipe(newActiveConditions)
  local recheckTime;
  local now = GetTime();
 if (not hideRegion) then
    state = region.states
    if (state[1] and state[1].show and state[1].name~= nil and state[1].name:match([[0]], 1, true)) then
      newActiveConditions[1] = true;
    end

  end
  if (recheckTime) then
    WeakAuras.scheduleConditionCheck(recheckTime, id, cloneId);
  end
  wipe(propertyChanges)
  if (activatedConditions[1] and not newActiveConditions[1]) then
    propertyChanges['xOffsetRelative'] = 0
  end

  if (newActiveConditions[1]) then
    if (not activatedConditions[1]) then
      propertyChanges['xOffsetRelative'] = 0
    else
      if(propertyChanges['xOffsetRelative'] ~= nil) then
        propertyChanges['xOffsetRelative'] = 0
      end
    end
  end

  activatedConditions[1] = newActiveConditions[1]
  if(propertyChanges['xOffsetRelative'] ~= nil) then
    region:SetXOffsetRelative(propertyChanges['xOffsetRelative'])
  end
end
"]:13: in function `?'
[string "@WeakAuras\WeakAuras-2.18.2.lua"]:6406: in function <WeakAuras\WeakAuras.lua:6371>
[string "@WeakAuras\WeakAuras-2.18.2.lua"]:6505: in function `UpdatedTriggerState'
[string "@WeakAuras\GenericTrigger.lua"]:742: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:698: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:850: in function <WeakAuras\GenericTrigger.lua:835>

Locals:
region = <unnamed> {
 SoundRepeatStop = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:205
 subRegionEvents = <table> {
 }
 Expand = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:851
 yOffset = -228
 anchorPoint = "BOTTOM"
 GetColor = <function> defined @WeakAuras\RegionTypes\Text.lua:240
 SetOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:330
 SendChat = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:277
 toShow = true
 useAuto = true
 OptionsClosed = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:739
 Color = <function> defined @WeakAuras\RegionTypes\Text.lua:218
 cloneId = ""
 Update = <function> defined @WeakAuras\RegionTypes\Text.lua:169
 regionType = "text"
 GetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:403
 relativePoint = "CENTER"
 SoundPlay = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:259
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:425
 color_r = 1
 SetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:339
 Collapse = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:829
 RealClearAllPoints = <function> defined =[C]:-1
 RunCode = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:285
 GetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:351
 SetAnimAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:407
 duration = 0
 SetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:368
 expirationTime = Infinite
 GetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:347
 UpdateTimerTick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:442
 color_g = 1
 GetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:376
 SetAnchor = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:318
 TimerTick = <function> defined @WeakAuras\RegionTypes\Text.lua:169
 text = <unnamed> {
 }
 SetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:389
 GetXOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:372
 regionHasTimer = true
 subRegions = <table> {
 }
 height = 16.666668
 startFormatters = <table> {
 }
 SetOffsetAnim = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:380
 xOffsetAnim = 0
 yOffsetAnim = 0
 triggerProvidesTimer = false
 states = <table> {
 }
 state = <table> {
 }
 SetXOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:364
 SetTriggerProvidesTimer = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:420
 SoundStop = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:214
 ClickToPick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:744
 0 = <userdata>
 ClearAllPoints = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:478
 relativeTo = <unnamed> {
 }
 values = <table> {
 }
 xOffset = 125
 id = "Int Pot Mängd"
 ResetPosition = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:312
 SetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:343
 width = 31.111126
 SetTextHeight = <function> defined @WeakAuras\RegionTypes\Text.lua:247
 color_a = 1
 xOffsetRelative = 0
 yOffsetRelative = 0
 GlowExternal = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:293
 finishFormatters = <table> {
 }
 SetOffsetRelative =

**Comment by mrbuds** [comment]
You have to delete an aura called "Int Pot Mängd"

**Comment by albinvalastig** [comment]
Thanks you for your suggestion but I assume you didn't read my issue correctly. I am unable to open the addon.

**Comment by mrbuds** [comment]
data from the problematic aura for reference
```
		["Int Pot Mängd"] = {
			["outline"] = "OUTLINE",
			["color"] = {
				1, -- [1]
				1, -- [2]
				1, -- [3]
				1, -- [4]
			},
			["displayText"] = "%p",
			["yOffset"] = -228,
			["displayText_format_p_time_dynamic"] = false,
			["customTextUpdate"] = "event",
			["automaticWidth"] = "Auto",
			["actions"] = {
				["start"] = {
				},
				["finish"] = {
				},
				["init"] = {
				},
			},
			["triggers"] = {
				{
					["trigger"] = {
						["itemName"] = 168498,
						["use_count"] = false,
						["duration"] = "1",
						["subeventPrefix"] = "SPELL",
						["use_includeCharges"] = false,
						["debuffType"] = "HELPFUL",
						["type"] = "status",
						["unevent"] = "auto",
						["use_itemName"] = true,
						["use_unit"] = true,
						["use_absorbMode"] = true,
						["spellIds"] = {
						},
						["count"] = "0",
						["subeventSuffix"] = "_CAST_START",
						["unit"] = "player",
						["event"] = "Item Count",
						["names"] = {
						},
						["count_operator"] = "==",
					},
					["untrigger"] = {
					},
				}, -- [1]
				["activeTriggerMode"] = -10,
			},
			["displayText_format_p_format"] = "timed",
			["internalVersion"] = 33,
			["animation"] = {
				["start"] = {
					["easeStrength"] = 3,
					["type"] = "none",
					["duration_type"] = "seconds",
					["easeType"] = "none",
				},
				["main"] = {
					["easeStrength"] = 3,
					["type"] = "none",
					["duration_type"] = "seconds",
					["easeType"] = "none",
				},
				["finish"] = {
					["easeStrength"] = 3,
					["type"] = "none",
					["duration_type"] = "seconds",
					["easeType"] = "none",
				},
			},
			["font"] = "Expressway",
			["subRegions"] = {
			},
			["load"] = {
				["class"] = {
					["single"] = "WARLOCK",
					["multi"] = {
						["WARLOCK"] = true,
					},
				},
				["spec"] = {
					["multi"] = {
					},
				},
				["size"] = {
					["multi"] = {
					},
				},
			},
			["fontSize"] = 17,
			["shadowXOffset"] = 1,
			["regionType"] = "text",
			["displayText_format_p_time_precision"] = 1,
			["parent"] = "Pots",
			["authorOptions"] = {
			},
			["conditions"] = {
				{
					["check"] = {
						["trigger"] = 1,
						["variable"] = "name",
						["op"] = "match('%s')",
						["value"] = "0",
					},
					["changes"] = {
						{
							["property"] = "xOffsetRelative",
						}, -- [1]
						{
						}, -- [2]
						{
						}, -- [3]
					},
				}, -- [1]
			},
			["justify"] = "LEFT",
			["tocversion"] = 80300,
			["id"] = "Int Pot Mängd",
			["selfPoint"] = "BOTTOM",
			["frameStrata"] = 1,
			["anchorFrameType"] = "SCREEN",
			["config"] = {
			},
			["uid"] = "9EZb6tztUF2",
			["xOffset"] = 125,
			["wordWrap"] = "WordWrap",
			["shadowColor"] = {
				0, -- [1]
				0, -- [2]
				0, -- [3]
				1, -- [4]
			},
			["fixedWidth"] = 200,
			["shadowYOffset"] = -1,
			["anchorPoint"] = "CENTER",
		},
```

**Comment by mrbuds** [comment]
you didn't answer the question from the issue template asking which version of weakauras you are using, which do you use ? retail? classic ?

**Comment by mrbuds** [comment]
Nothing was changed in the item count trigger recently, please answer all questions from the template for help.
