### ISSUE TITLE
Dynamic Group won't align icons properly

### ISSUE THREAD

**Issue by Schlurcher** [WeakAuras/WeakAuras2#243]
Repro: Create a dynamic group which aligns the items horizontally and put some icons into it. It will just stack the items on top of instead of aligning them next to each other.

This was working in the version before 2.4.10. 

See [here for the aura on wago.io ](https://wago.io/BJ7UjLHS-) and [here for a screenshot](https://prnt.sc/fvd3pol) of how it looks.

**Comment by InfusOnWoW** [comment]
Fixed in the next alpha.
