### ISSUE TITLE
Opening WA crashes the game (SL beta)

### ISSUE THREAD

**Issue by Ravec** [WeakAuras/WeakAuras2#2430]
The following error seems to be recurring to various people I've spoken to that are currently using WA on the shadowlands beta, this seemingly does not prevent existing weakauras from working, but upon opening the weakauras interface the game crashes with the following error. I'll preface this by saying the latest Github version 3.0.0-alpha9 (2020-08-07) is being used, and a complete uninstall including saved variables etc, was tried and didn't change anything.

"This application has encountered a critical error:

ERROR#110 (0x8510006e) The feature is not implemented. 

Program: E:\World of Warcraft\_beta_\WowB.exe
ProcessID:                                  10404
ThreadID:                                   25324
File:
D:\BuildServer\WoW\1\Work\shared-checkout\branches\wow-patch-9_0_1-branch-fastpatch-22\Mainline\Source\Object\ObjectClient\PlayerConditions_C.cpp
Line:                        688

Aura '250168' used in Client PlayerCondition '32509' is not known on the client. Check your flags and update your DBC!

Do you wish to keep running anyway?
             OK:            Keep running
             Cancel:      Terminate application
"

1) I don't have a D:\ drive
2) "OK; Keep running" results in a looped error that doesn't go away untill I press cancel and the game crashes.

Would love to hear your/anyones input,

Thanks in advance.

**Comment by spamwax** [comment]
<img width="285" alt="wow-crash" src="https://user-images.githubusercontent.com/1251233/91634065-70de6280-e9bb-11ea-9fb3-ffe80cf1192d.png">

**Comment by mrbuds** [comment]
This is an issue on WoW's client side, it should be fixed in a future PTR release, but we can't do anything about it.
duplicate #2426
