### ISSUE TITLE
Exclude self for Status triggers. 

### ISSUE THREAD

**Issue by Albanmonk** [WeakAuras/WeakAuras2#2432]
**Is your feature request related to a problem? Please describe.**
I wanted a weakaura to track healer mana without custom code. I did Status>Power, set unit to Raid and Assigned Role to Healer. This worked like a charm. The problem is that I am also a healer myself, for that reason the weakaura also tracks my mana - which I don't want it to, as I am already tracking that in another weakaura.

**Describe the solution you'd like**
Add an exclude self checkbox for Status triggers, like the one present on Aura triggers. I believe the one for Aura triggers is called Own Only or Not Own Only, depending on whether you want to make yourself the only trigger source or exclude yourself from the trigger sources.

**Describe alternatives you've considered**
I have asked around with the people I know that work with weakauras often or other types of addon making or coding in relation to WoW (ElvUI developers), but none of them had an idea, unless I made the entire weakaura custom code - which wasn't my intention.
I also asked in WA discord for help, where I was told by Spaten to make a ticket for the feature.

**Additional context**
https://cdn.discordapp.com/attachments/218084462523711489/749304744081621132/unknown.png
Just a picture showing the trigger I made in case it might be relevant.

**Comment by InfusOnWoW** [comment]
This is in the shadowlands version.
