### ISSUE TITLE
Beta critical error when importing WA

### ISSUE THREAD

**Issue by Twotrapz** [WeakAuras/WeakAuras2#2434]
Whenever I go to important a WA on beta, my game encounters a critical error shortly after selling the import function. I have deleted and reinstalled WA's numerous time, and have even used an earlier release to see if that would fix the issue, but it does not.
![errors](https://user-images.githubusercontent.com/70460570/91650892-2c9aa300-ea4b-11ea-803c-943a2e205860.PNG)

**Comment by emptyrivers** [comment]
That's because there's a bug in blizzard's code. Quickly click "ok" on that prompt and you should be fine.
