### ISSUE TITLE
Dummy initial event for Status/TSU shouldn't just fire all events

### ISSUE THREAD

**Issue by jcai1** [WeakAuras/WeakAuras2#2435]
**Is your feature request related to a problem? Please describe.**
Status/TSU triggers that check "on event" get a dummy event when the WA is initialized. This dummy event calls _all_ registered events with no args. As a result, events that naturally have no args can't distinguish dummy calls from real calls. And events with args need extra nil checks.

**Describe the solution you'd like**
The dummy trigger should just call a single dummy event with a name like `WA_INIT` instead of calling all registered events.

The new behavior should be default for new auras (like a checkbox that's auto-ticked for new auras but not for older auras). I believe the current behavior of calling all registered events is simply a design flaw, somewhat like pushing every single button when starting a plane.

**Describe alternatives you've considered**
There is a workaround which is to manually add a dummy `WA_INIT` at the end of the registered events list. On receiving `WA_INIT` you could set a flag. All other events need to check this flag to determine if it's the dummy init event or not. This workaround relies on the dummy events being called in the order they're written, and is also inelegant.

**Comment by asaka-wa** [comment]
What you're describing isn't the behaviour of *TSU* triggers, but the behaviour of any Status trigger, of which TSU is one. 

The idea is that if you're using a Status trigger, tracking, say, `PLAYER_XP_UPDATE`, then you'll *want* WA to fire something when it loads, or when you close WA config, to let you get up to speed with the current XP value. Rather than having to wait for the next time the player gains XP. 

If you're trying to use a TSU as if it were an Event type trigger then, yes, events that don't naturally have args will cause issues. It's the one instance in which TSU can be considered inferior to a regular custom trigger. 

So, this "design flaw" stuff is a bit short-sighted. It's working as intended. Though that's not to say it isn't worth a ticket to see TSU's use could be broadened to include Event type triggering. 

Perhaps the most user-friendly solution would be a control in the trigger settings to set TSU to be either Event or Status. I would guess this would be a surprising amount of work and still has the shortcoming that most people, even using custom triggers, don't know the important differences between the trigger types. 

Another solution might be to make it so that dummy events *do* carry an arg that can be identified as WA-generated. This could presumably be done in such a way that it doesn't alter the regular use of those dummy events by all of WA's own triggers, while providing players with something they can use in rare cases like this.

**Comment by jcai1** [comment]
The problem with pure Event triggers is that they don't have a way to trigger initially. This is the issue that Status/TSU-type triggers solve by having a dummy event. But the latter triggers have their own problem, i.e. the ambiguity described by this issue.

I apologize for my tone. The design of the dummy trigger is has probably not been too big of an issue, as the ambiguity would only cause problems for events that have no args and convey real information by the firing of the event. Events we're typically interested in like `CLEU`, `UNIT_AURA`, `SPELL_UPDATE_COOLDOWN` would not be impacted. However, events like `PLAYER_REGEN_DISABLED`, `PLAYER_STARTED_MOVING`, `TRADE_SHOW` would be impacted.

Probably the most real-world example would be with `PLAYER_REGEN_DISABLED`. Let's say a user coded for `PLAYER_REGEN_DISABLED` to store `aura_env.inCombat=true` and `PLAYER_REGEN_ENABLED` to store `aura_env.inCombat=false`. Also suppose the user wrote the event registration in the order `PLAYER_REGEN_ENABLED, PLAYER_REGEN_DISABLED`. As a result of this the WA would always start out with `aura_env.inCombat==true` which might lead to confusing bugs.

My main motivation is to have a default template to work with on custom WAs that don't need OnUpdate calls. Status/TSU-type triggers that fire on Events would be great here, except for the issue described. Even if the issue typically doesn't manifest, I don't want to be caught unaware by it in the future.

**Comment by InfusOnWoW** [comment]
It's trivial to check if a player is in combat or not, so that's a non issue for that case.

Anyway, the design won't change, since the cost of a backwards incompatible change by far outweight the small benefit in some edge cases this would bring.

**Comment by asaka-wa** [comment]
You are describing the use case of Status triggers.    
You want them to show a status, so not have to wait for the next tracked event to fire. Great. 

However, any status trigger requires that you, the author, check the current status that you're hoping to display with the Aura. 

In the case of your combat status I would expect that to look something like:

[Custom - TSU - `PLAYER_REGEN_ENCABLED PLAYER_REGEN_DISABLED]
```LUA
function(allstates)
  if not allstates[""] then
    allstates[""] = {show = true, changed = true, inCombat = UnitAffectingCombat("player")}
  else
    allstates[""].inCombat = UnitAffectingCombat("player")
    allstates[""].changed = true
  end
  return true
end
```

You use the relevant API function to check the status you're displaying. 

If you need help making custom triggers then please do drop by the WA Discord (linked in the Wiki).

**Comment by jcai1** [comment]
Well yes, for the specific case of `PLAYER_REGEN_DISABLED` you can obviously check with the `UnitAffectingCombat` call. It's supposed to be an example to illustrate how the design doesn't make sense. When your trigger receives a `PLAYER_REGEN_DISABLED` call you can't automatically just *know* that you're in combat, as would be sensible, but you rather have to *check again*: am I actually in combat? It's frustrating to have to work around that design.

It doesn't have to be a breaking change, it can be a checkbox that's off by default.

**Comment by InfusOnWoW** [comment]
Checking again is the right thing to do. As e.g. after the options close or on initial load you have absolutely no idea in what state you are.

**Comment by jcai1** [comment]
That's the point of the proposed `WA_INIT` dummy event. On receiving `WA_INIT` the weakaura knows it has to recheck everything. This of course makes sense.

It should not have to recheck everything after receiving something like a `PLAYER_REGEN_DISABLED` event. AddOns using `frame:RegisterEvent("PLAYER_REGEN_DISABLED")` know for certain that immediately after receiving this event, the player is in combat. There should be no need to recheck `UnitAffectingCombat`.

**Comment by InfusOnWoW** [comment]
Introducing a WA_INIT event is obviously backwards incompatible, and I've already told you that we won't do that. Thus it's a pretty pointless point to bring up again.

The WeakAuras environment is obviously different from what you would do in your own addon.

There's no point in discussing this further. I've explained how it works, why we won't change and why it is the designed that way. 

If you want a different behaviour, WeakAuras is open source and thus you can easily fork WeakAuras to change it to your vision.

Or write your own addon from scratch.

**Comment by jcai1** [comment]
The `WA_INIT` was the crucial piece of my proposed change, it's not just some random "point" I'm bringing up.

It's obviously not backwards incompatible if it's an opt-in checkbox. But since it seems your mind cannot be changed on this I won't bother you any further.
