### ISSUE TITLE
Percent Power text replacement inconsistent formatting by default

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#2437]
## Describe the bug
Using the percent power text replacement, it seems that the formatting differs for some reason. This has been tested with characters of varying levels. 

### To Reproduce
https://wago.io/99uRCzYR6
Using this aura should allow this to be reproduced. Level 1 characters and max level chars differ. 

**Screenshots**
![image](https://user-images.githubusercontent.com/15392657/91800504-6dbdcd80-ec6c-11ea-9d6e-70f37df6345b.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
SL alpha 6

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ ] Retail
- [x] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
N/A

**Comment by InfusOnWoW** [comment]
NONE of the auras in that set have any formatting set for %percentpower, so rather unsupringly no formatting is done.

**Comment by 1ps3** [comment]
I mean, no formatting is still a type of formatting I suppose. Though after looking into it a little more it was just a coincidence that the number ended up being small due to the size of the mana pool and the regen values. Since max level chars have consistent mana pools these days.
