### ISSUE TITLE
3.0.0-beta1 client crash

### ISSUE THREAD

**Issue by niketa-wow** [WeakAuras/WeakAuras2#2443]
## Describe the bug
Opening WeakAuras causes the WoW client to crash.

**Do you have an error log of what happened?**
No.

### To Reproduce
1. Open WeakAuras

**Screenshots**
![image](https://user-images.githubusercontent.com/58258335/92204309-cd70d000-ee48-11ea-8cbf-8dba3d0ff796.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I disabled all addons but WeakAuras and still experience the crash.

**Which version of WeakAuras are you using?**
3.0.0-beta1

**Are you on World of Warcraft Classic or Retail?**
- [ x] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
It was working before but I don't remember what version that was. However, that version stopped working. So I think it has to do with a recent beta patch.

### Additional Info

**Comment by Ivan-esp** [comment]
Hi, I have the same problem ;
`[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:4094: in function 'RunCustomTextFunc'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:288: in function '?'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:34: in function 'Notify'
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3873: in function <WeakAuras\WeakAuras.lua:3870>
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3956: in function <WeakAuras\WeakAuras.lua:3923>
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:4038: in function 'UpdatedTriggerState'
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3810: in function 'UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3783: in function 'FakeStatesFor'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1856: in function 'PriorityShow'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1649: in function 'PriorityShow'
[string "@WeakAurasOptions\WeakAurasOptions-3.0.0-beta1.lua"]:681: in function <...terface\WeakAurasOptions\WeakAurasOptions.lua:647>129x [string "--[==[ Error in 'PhoGuild - Raid Ability Ti..."]:4: bad argument #1 to 'strtrim' (string expected, got nil)
[string "--[==[ Error in 'PhoGuild - Raid Ability Timeline Icon':'custom text' ]==] return function()
    if not aura_env.state then return end
    local text = aura_env.state.name
    text = strtrim(text) -- Trim
    local inlineIconAdjust = string.len(string.match(text,"") or "")
    if inlineIconAdjust > 0 then inlineIconAdjust = inlineIconAdjust - 2 end -- Make icons take 2 characters.
    if (aura_env.config.textMaxLength or 0)>=5 and text:len()-inlineIconAdjust>aura_env.config.textMaxLength then
        text = string.sub(text,1,aura_env.config.textMaxLength+inlineIconAdjust-2)..".." -- Truncate
    end
    if aura_env.state.colorTable then
        local t=aura_env.state.colorTable
        text = string.format("\124c%02x%02x%02x%02x%s\124r",255*(t[4] or 1),255*(t[1] or 0),255*(t[2] or 0),255*(t[3] or 0),text)
    end
    return text
end"]:4: in function <[string "--[==[ Error in 'PhoGuild - Raid Ability Ti..."]:1>
[string "=[C]:"]: in function 'xpcall'
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:4094: in function 'RunCustomTextFunc'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:288: in function '?'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:34: in function 'Notify'
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3873: in function <WeakAuras\WeakAuras.lua:3870>
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3956: in function <WeakAuras\WeakAuras.lua:3923>
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:4038: in function 'UpdatedTriggerState'
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3810: in function 'UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras-3.0.0-beta1.lua"]:3783: in function 'FakeStatesFor'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1856: in function 'PriorityShow'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1649: in function 'PriorityShow'
[string "@WeakAurasOptions\WeakAurasOptions-3.0.0-beta1.lua"]:681: in function <...terface\WeakAurasOptions\WeakAurasOptions.lua:647>`

**Comment by InfusOnWoW** [comment]
@Ivan-esp that has nothing to do with the original report. And this appears to bea a error in the "Error in 'PhoGuild - Raid Ability Timeline Icon" aura, not in WeakAuras.

The original report is a bug in WoW. We can't do anything about it.
