### ISSUE TITLE
Shadowlands beta - client crash on WA options window

### ISSUE THREAD

**Issue by Araiia** [WeakAuras/WeakAuras2#2444]
## Describe the bug
Entire WoW client crit errors after opening the weakaura options window.

**Do you have an error log of what happened?**
Crit error display window:

```
Error #110 (0x8510006e) The feature is not implemented.
Program: (WoW Beta filepath)
File: D:\BuildServer\WoW\6\work\shared-checkout\branches\wow-patch-9_0_1-branch-fastpatch-23\Mainline\Source\Object\ObjectClient\PlayerConditions_C.cpp
Line: 688
Aura '250168' used in Client PlayerCondition '32509' is not known on the client. Check your flags and update your DBC!
```

### To Reproduce
1. /wa options
2. wait a few seconds 
3. crit error happens

**Screenshots**
reproduced above in crit error window text

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.0-beta1
3.0.0-alpha9

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ ] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
I think it was working in 3.0.0-alpha9 **12 days ago**. But now that I try to revert to that version of WA, it's not working either. I haven't logged on or played beta in the last 2 weeks so I don't know what's changed since then.

### Additional Info
Existing WAs are functional as long as I don't cause a crash by opening the options window, but this means I can't create/edit weakauras directly ingame.

I keep several old code snippets in my WAs (set to never load), some of which create lua errors if I click on them, but it's never caused a crash before - especially when I'm not even clicking on them. Don't know if one of those is causing the issue.

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5177309/WeakAuras.zip)

**Comment by omicron-o** [comment]
I'm getting the exact same behavior also using the same two versions of WeakAuras. Almost immediately after I open the options the game freezes and a few seconds later it crashes. I'm running wow using wine-staging-5.16 on linux, I don't know if that is related to the crash.

**Comment by mrbuds** [comment]
This is not a bug in WeakAuras, hope blizzard fix it with their next ptr release.

**Comment by alecs91ro** [comment]
Version alpha 3 still works thou :)

**Comment by jwshive** [comment]
Version alpha 3 does not work for me.
