### ISSUE TITLE
Weak aura error

### ISSUE THREAD

**Issue by lovetoseeit** [WeakAuras/WeakAuras2#2447]
Game version : Retail but also had the exact same bug on beta using the latest version on beta and retail at the time this post is created (retail being 2.18-4 & beta being WeakAuras-3.0.0-beta1 downloaded on the WA discord)

## Describe the bug

very often when opening WA menu (i do not know if this is the only trigger for the error i'm about to paste), the error pops up.

**Screenshots or the error **
![image](https://user-images.githubusercontent.com/70891659/92377586-a5ad9080-f104-11ea-9fbb-f65615740945.png)

i've been told in the WA discord this : " it's when WA has something anchored to a nameplate at the point where you open the config." if that is any help for you guys.
also been told to do a ticket for this, so here you go.

Hopefully you'll figure it out, cheers

**Comment by sragia** [comment]
This is on e67ffe17b10bc860ef4eabaf6c9da7ccc7824695 
https://streamable.com/yrjya6
For me only happens when you create aura and set anchor to nameplate first time.
Create aura with 
Trigger:  Status - Health, Unit: Nameplate
In Display: Anchored To: Nameplate
See error as soon as you set anchor

From the looks of it, MoverSizer is just not removed before attaching it to nameplate in options as changing auras and selecting display again doesn't produce any error.

**Comment by asaka-wa** [comment]
```
!WA:2!vw1tVnsnu8TklArdslS5WkK4YOCO0IkP)rLfbOEiPDsBrPnHjPfQiOrEM5nzC7e7bBpPPG4spX58riN3t5JWEyppAfFcq8jy)eWZoPLn7MeGrktS988Z)(9(z)ZRuRyVIHfd)9sVIKPI5IgPkkNjTe30ikscQvgtyb44n5uMQADNAT3jtKK(jXkvQ8R3CZRjD5LP8nZUiEx3lDo8Yn3rqcm5OMRurekRQugvz5gKqdUYYpc7jJTUvjOD7cc5JxvmT5lRQUjf8dYKkEV)uM5d9bMQvwueDWyV9R0QTxR2vCB7Ag3)iGKOIRMHj3pnHCdiCzKEG0k)dhu4LrzmdkwJSHnSHD26w24d5hlv6NS3B6)CH9VkJ5xJdersKWgbXewxie7RezWVzMcnYgS3Bp7snRx5chxVAn2)SwE7FuLtp05Gs2QyGzIBASNHWXzavQKRvkIJCP06ZgJ(jcxzkUkBVH9UBzhYN5JVrIowQFVwjnVqkQGsLlt3WEXj(Uhd)kRln4Qm70xs8tRfAUVKOMTin3afGktWM)3bwO1I6dOiyTqEWOjwle0gb06)fANhkVdnAKCVYFALtC8q5VTJ3zNECBVkhCGw6jSq7mZ75j63n(unmBrY2mumZ6FxrwkVEBoTuE46CsJZFxM8FdXZTUVuSTqX8Dankc6FwwtSaKPvN3Hp75Ql2lGL3BO0uaOHIBRMo1R7gedbxLxC8ethpTb0y01sbzPH47BLPqsYXHsRrHGp6e1gdqCKt9M1oR(Wm2uNlR0NO986dTN0)eEi88h8A0XeemsY5OnhAfT)qcJ2JODLEw(7xl)XvzCg8cGiHwkbW6QIF0RcZeMimqriHaoluERog9sNVA1EekdNB(Q5F6JYxlF98pdB(bV9iiCLeLoxqC6tcPYaSidEcUYK9)6Je9NaQ3BewxCHUgtF)yG2nwb(M4G4QjCs4ZqNBIu(u3EzjkQvvSKe808DXg0Fb0nEXKIxfZ9ePX378UUT1BOUeemEaRFzt5DY2a9oU99ofTNAQTNkFiOUVtnUWSnCoZdtmU9WVhvi4I4rcd6nkJcgGlgm0pbdqRcU4vwNEq(3KU3XAXiIeaDQeg2Gj789a5QkyYLDobcPKoTNmxzhuuX9VjWN7ZfHGOSQlXxc9WcM72L3Q82Ju8GPvVpELV65LOHJnNtSnES(OIfr7AnosGubfwIIuW9AAiEg62)P(VtgoTlAD(LR)D)C9(orUKK0ysbXGPx7oucjrMlDDDp(WJApsVrGo5Uz3aEcx8TfkuO5d3Q8x(fVEYv010lOUmmuFeWCcOOCNdG(f7)h)WF)
```
This Aura provides an example of the issue. 

It's a fairly simple custom trigger that provides a nameplate unit for your current focus. In Display Anchored To is set to Nameplate which works fine, but upon opening config the error occurs. As a workaround I used a Custom Anchor which should be saved in the import if you switch to that setting. 

Not sure if this provides any insight or not but there it is.
