### ISSUE TITLE
Game Crashed after click on import WA ( Shadowlands Beta ).

### ISSUE THREAD

**Issue by L30m4nc3r** [WeakAuras/WeakAuras2#2449]
Screenshot: https://prnt.sc/udb4v4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [X ] Shadowlands

**Comment by InfusOnWoW** [comment]
That's a blizzard bug, not a weakauras bug. You can click ok on it.
