### ISSUE TITLE
Supporting !ClassColors

### ISSUE THREAD

**Issue by Wastingmoney** [WeakAuras/WeakAuras2#2450]
**Is your feature request related to a problem? Please describe.**
I searched up a way to change Shaman Class Color to the normal Blue in >>Classic WoW<< . I Found the AddOn " !ClassColors "
and its working greatly and other Big AddOns like ElvUI do support it. It doesnt taint the UI. In WeakAuras however the Classcolor given for shamans still stay pink.

**Describe the solution you'd like**
I'd love to see WeakAuras Supporting that AddOn so Shamans are blue.

**Describe alternatives you've considered**
I asked on the WeakAura-Discord on how to maybe fix that myself. And "Infus" told me I should open up a ticket and here I am.

**Additional context**

In the Screenshot below you see what I basically just described. Shamans Color is blue on all Elements except that WeakAura above the targetframe. 
![bluepinkidk](https://user-images.githubusercontent.com/70923476/92421053-f2ca4a80-f176-11ea-84bc-4886d3a6f1e4.png)

here its the clock wa
![bluepinkidk2](https://user-images.githubusercontent.com/70923476/92421230-ccf17580-f177-11ea-94a8-6222d4064eb5.png)

Thanks for taking your time. :)

**Comment by mrbuds** [comment]
I think an option to change class color should be global for the addon and would fit in an eventual future setting panel

**Comment by mrbuds** [comment]
Do you have a link for that addon !ClassColors ?

**Comment by Wastingmoney** [comment]
https://www.curseforge.com/wow/addons/classcolors
There you go.

**Comment by Stanzilla** [comment]
Ah good old custom class colors. Yeah we can add that, it's super easy to support, just need `CUSTOM_CLASS_COLORS or RAID_CLASS_COLORS` instead of just `RAID_CLASS_COLORS`

**Comment by Wastingmoney** [comment]
Sounds great, can't wait :)
