### ISSUE TITLE
Deadly Poison countdown

### ISSUE THREAD

**Issue by NotaBeneRnD** [WeakAuras/WeakAuras2#2451]
Hello!
I want to view Deadly Poison countdown on my target (12 sec). 
It looks right until 5 stacks up. When i have 5 stacks and aply it again timer dont refresh.

![WoWScrnShot_090820_134746](https://user-images.githubusercontent.com/68054544/92467266-f6db8400-f1d9-11ea-9a47-11d14b344dea.jpg)
![WoWScrnShot_090820_135022](https://user-images.githubusercontent.com/68054544/92467682-ad3f6900-f1da-11ea-8138-389bcc45249a.jpg)

**Comment by mrbuds** [comment]
This is a known issue in LibClassicDurations https://github.com/rgd87/LibClassicDurations/issues/11
