### ISSUE TITLE
Numerous issues with ElvUI skins

### ISSUE THREAD

**Issue by pjaws** [WeakAuras/WeakAuras2#2455]
These issues all started after the latest weekly reset. I originally started writing this ticket on the ElvUI issues page, but to my surprise WeakAuras turned out to be the culprit. The only specific WeakAuras I have updated in between when things were working and now are Afenar's all-in-one class WAs.

1. All interface panels are transparent. This is occurring whether or not I enable Blizzard skins and/or Parchment Remover.
2. Opening the game menu shows either a large red gradient or black rectangle in the upper 2/3 of the screen depending on whether or not Blizzard skins are enabled.
3. In the ElvUI options panel itself, only the "inner" menu is displaying normally. The left sidebar and surrounding panel look like they have a black semi-transparent overlay on them.
4. The LFG finder "eye" in the mini-map is not showing.
5. Opening my bank causes the screen to go black aside from the item level text in the bags.
6. Opening my bags shows only the item level text. Items are transparent.

![Screenshot (141)](https://user-images.githubusercontent.com/53156002/92532606-7cb0fc80-f1e5-11ea-98e1-9467d4667431.png)
![Screenshot (151)](https://user-images.githubusercontent.com/53156002/92532629-863a6480-f1e5-11ea-9d25-996cf5b50b74.png)
![Screenshot (143)](https://user-images.githubusercontent.com/53156002/92532856-1c6e8a80-f1e6-11ea-974b-5804795cbd08.png)

I have tried reinstalling WA. I've tried downgrading to the previous patch. I'm not sure what else to do, since I can't really imagine playing without both of these addons.

**Comment by InfusOnWoW** [comment]
There are questions in the issue template. Without answers to them we can't help you.

**Comment by pjaws** [comment]
> There are questions in the issue template. Without answers to them we can't help you.

I literally answer all of those questions in the issue

**Comment by mrbuds** [comment]
Sadly no, we don't know the version of addons you are using, nor what is the afenar aura you talk about

**Comment by mrbuds** [comment]
If we can't replicate a bug with the information given it's hard for us to help

**Comment by InfusOnWoW** [comment]
Also, this.
**Do you have an error log of what happened?**
which contains instrunctions on how to get a error log.

**Which version of WeakAuras are you using?**

Just create a new bug report, but this time add all the necessary information.
