### ISSUE TITLE
Beta Game Crash after opening Weakaura

### ISSUE THREAD

**Issue by elthoras** [WeakAuras/WeakAuras2#2459]
the title says, since 2 weeks i get gamecrash when i open weakauras with /wa.

my Weakauras are still working, but i cant change them, because i get a Game Crash.

Here a picture from it 

[https://i.imgur.com/9h8cWIB.png](url)

idk if this screenshot also helps:
[https://i.imgur.com/Efbl6Of.png](url)

**Comment by emptyrivers** [comment]
Just click past the error. It's something on blizzard's end, and they should fix it eventually.
