### ISSUE TITLE
Does not draw buttons in WA UI. "TexCoord out of range" error

### ISSUE THREAD

**Issue by yaghani** [WeakAuras/WeakAuras2#2469]
## Describe the bug

My weak aura installation is giving me errors when loading the Weak Aura UI. As the weak aura UI loads, it loads all the auras and then tries to create the buttons. While creating the button, it throws an error "5x TexCoord out of range" and spits out a backtrace. 

I play Shadow Priest mostly. But recently I have started playing couple of new characters: one is Warlock, and another is Hunter. I also upgraded my computer recently and moved game folder to new machine and updated some of the graphics settings (not sure if this is relevant). 

**Do you have an error log of what happened?**

```
5x TexCoord out of range
[string "=[C]"]: ?
[string "=[C]"]: in function SetTexCoord'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:363: in function UpdateAdditionalBars'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:460: in function SetAdditionalBars'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:1228: in function Update'
[string "@WeakAuras\WeakAuras-2.18.4.lua"]:6319: in function <WeakAuras\WeakAuras.lua:6318>
[string "@WeakAuras\WeakAuras.lua"]:6404: in function <WeakAuras\WeakAuras.lua:6371>
[string "@WeakAuras\WeakAuras.lua"]:6488: in function UpdatedTriggerState'
[string "@WeakAuras\WeakAuras.lua"]:6258: in function UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras.lua"]:6231: in function FakeStatesFor'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1883: in function PriorityShow'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1676: in function PriorityShow'
[string "@WeakAurasOptions\WeakAurasOptions-2.18.4.lua"]:659: in function <WeakAurasOptions\WeakAurasOptions.lua:625>
```

### To Reproduce

Error is logged every time I open weak aura from the chat prompt. using /wa command. 
[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/5202632/WeakAuras.lua.zip)

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No, but will try it tonight. 

**Which version of WeakAuras are you using?**

Latest. 

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

Was working couple of weeks ago. Not sure how I got into this state.

**Comment by yaghani** [comment]
I disabled all addons and just keep WA add-on installed. Still seeing the same error. 

I then updated to the latest unreleased version of WA (2.18.4-9-gb4239fe) to see if I can debug the error. Still seeing the same error. Here are the logs: 

```
1x WeakAuras\RegionTypes\AuraBar.lua:363: TexCoord out of range
[string "=[C]"]: in function `SetTexCoord'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:363: in function `UpdateAdditionalBars'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:460: in function `SetAdditionalBars'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:1228: in function `Update'
[string "@WeakAuras\WeakAuras-2.18.4-9-gb4239fe.lua"]:6319: in function <WeakAuras\WeakAuras.lua:6318>
[string "@WeakAuras\WeakAuras.lua"]:6404: in function <WeakAuras\WeakAuras.lua:6371>
[string "@WeakAuras\WeakAuras.lua"]:6488: in function `UpdatedTriggerState'
[string "@WeakAuras\WeakAuras.lua"]:6258: in function `UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras.lua"]:6231: in function `FakeStatesFor'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1883: in function `PriorityShow'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1676: in function `PriorityShow'
[string "@WeakAurasOptions\WeakAurasOptions-2.18.4-9-gb4239fe.lua"]:659: in function 
```

**Comment by InfusOnWoW** [comment]
We'll investigate it.

**Comment by InfusOnWoW** [comment]
I cannot reproduce that, looking through your auras, there are two candidates, which based on your error messsage, might the cause of the problem.

Could you, after maling a backup of your settings, try deleting the aura "Main Astral Power (Druid)" and "CastBar_Enemy_2" and see if that changes anything ?

**Comment by yaghani** [comment]
Yay, deleting the "CastBar_Enemy_2" worked! No more error and I can now see the buttons and search bar. This was one of the WAs in a group. I deleted the whole group. Thank you for your help. Much appreciated.

**Comment by mrbuds** [comment]
Should we keep the ticket open until something is done to prevent this error, or is that aura doing something very unsupported ?

**Comment by InfusOnWoW** [comment]
Yeah, now that we have identified the aura, I can take a closer look at what it does and maybe figure out what might trigger it.
