### ISSUE TITLE
Scrolling Down issue

### ISSUE THREAD

**Issue by lovetoseeit** [WeakAuras/WeakAuras2#2472]
## Describe the bug

**_**the issue happens most when a group of WA has "enough" WAs inside to force you scrolling down but the scrolling only works "partially". the scrolling sort of "get stuck" and i have to manually scroll down.**_**

**Do you have an error log of what happened?**

_No error detected_

```
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**https://imgur.com/tDQ9DmT _(video of the issue)**_

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

_Yes i tried with only WA enabled_

**Which version of WeakAuras are you using?** => **_2.18.4 (retail)_**

**Are you on World of Warcraft Classic or Retail?**

- [] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

I've had this bug happen since a few month already, but never did a ticket, after asking the WA discord, i was suggested to send a ticket

### Additional Info

Added a gif video for visual support as i hope it will be helpful

**Comment by lovetoseeit** [comment]
Actually found an error : dont know if it's related, but assuming the name, it might be : 

2x FrameXML\UIDropDownMenu.lua:64: attempt to concatenate local 'name' (a nil value)
[string "@FrameXML\UIDropDownMenu.lua"]:64: in function <FrameXML\UIDropDownMenu.lua:60>
[string "@FrameXML\UIDropDownMenu.lua"]:970: in function <FrameXML\UIDropDownMenu.lua:910>
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@FrameXML\UIDropDownMenuTemplates.lua"]:19: in function <FrameXML\UIDropDownMenuTemplates.lua:17>

Locals:
frame = <unnamed> {
 0 = <userdata>
 template = "Default"
 PixelSnapDisabled = true
 SetBackdropColor = <function> defined =[C]:-1
 pixelBorders = <table> {
 }
 SetBackdropBorderColor = <function> defined =[C]:-1
}
name = nil
key = "Left"
(*temporary) = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 740
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 AceGUI30PulloutScrollbar29 = AceGUI30PulloutScrollbar29 {
 }
 InterfaceOptionsActionBarsPanelStackRightBarsPixelBorderTOP = InterfaceOptionsActionBarsPanelStackRightBarsPixelBorderTOP {
 }
 StaticPopup4MoneyInputFrameCopperPixelBorderLEFT = StaticPopup4MoneyInputFrameCopperPixelBorderLEFT {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 CombatConfigColorsColorizeEntireLinePixelBorderCENTER = CombatConfigColorsColorizeEntireLinePixelBorderCENTER {
 }
 FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture = FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 LFGListInviteDialog_OnEvent = <function> defined @FrameXML\LFGList.lua:2423
 MerchantItem4AltCurrencyFrameItem1Text = MerchantItem4AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 EncounterDetails_SpellAurasScrollScrollChildFrame = EncounterDetails_SpellAurasScrollScrollChildFrame {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:778
 PaperDollTitlesPaneButton13BgTop = PaperDollTitlesPaneButton13BgTop {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 HasZoneAbility = <function> defined @FrameXML\ZoneAbility.lua:162
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 ElvUI_Bar5Button12Shine7 = ElvUI_Bar5Button12Shine7 {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:957
 StackSplitFramePixelBorderTOP = StackSplitFramePixelBorderTOP {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 ElvUI_StanceBarButton7PixelBorderRIGHT = ElvUI_StanceBarButton7PixelBorderRIGHT {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 LibDBIcon10_BugSack = LibDBIcon10_BugSack {
 }
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 CombatConfigColorsColorizeDamageNumberSchoolColoringPixelBorderLEFT = CombatConfigColorsColorizeDamageNumberSchoolColoringPixelBorderLEFT {
 }
 CompactUnitFrameProfilesSaveButton = CompactUnitFrameProfilesSaveButton {
 }
 LFDQueueFrameRoleButtonDPSPixelBorderLEFT = LFDQueueFrameRoleButtonDPSPixelBorderLEFT {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 RaidUtility_CloseButton = RaidUtility_CloseButton {
 }
 Is64BitClient = <function> defined =[C]:-1
 CompactRaidFrameManagerDisplayFrameFilterOpt2x FrameXML\UIDropDownMenu.lua:64: attempt to concatenate local 'name' (a nil value)
[string "@FrameXML\UIDropDownMenu.lua"]:64: in function <FrameXML\UIDropDownMenu.lua:60>
[string "@FrameXML\UIDropDownMenu.lua"]:970: in function <FrameXML\UIDropDownMenu.lua:910>
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@FrameXML\UIDropDownMenuTemplates.lua"]:19: in function <FrameXML\UIDropDownMenuTemplates.lua:17>

Locals:
frame = <unnamed> {
 0 = <userdata>
 template = "Default"
 PixelSnapDisabled = true
 SetBackdropColor = <function> defined =[C]:-1
 pixelBorders = <table> {
 }
 SetBackdropBorderColor = <function> defined =[C]:-1
}
name = nil
key = "Left"
(*temporary) = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 740
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 AceGUI30PulloutScrollbar29 = AceGUI30PulloutScrollbar29 {
 }
 InterfaceOptionsActionBarsPanelStackRightBarsPixelBorderTOP = InterfaceOptionsActionBarsPanelStackRightBarsPixelBorderTOP {
 }
 StaticPopup4MoneyInputFrameCopperPixelBorderLEFT = StaticPopup4MoneyInputFrameCopperPixelBorderLEFT {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 CombatConfigColorsColorizeEntireLinePixelBorderCENTER = CombatConfigColorsColorizeEntireLinePixelBorderCENTER {
 }
 FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture = FriendsListFrameScrollFrameButton20TravelPassButtonPushedTexture {
 }
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 LFGListInviteDialog_OnEvent = <function> defined @FrameXML\LFGList.lua:2423
 MerchantItem4AltCurrencyFrameItem1Text = MerchantItem4AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 EncounterDetails_SpellAurasScrollScrollChildFrame = EncounterDetails_SpellAurasScrollScrollChildFrame {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:778
 PaperDollTitlesPaneButton13BgTop = PaperDollTitlesPaneButton13BgTop {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 HasZoneAbility = <function> defined @FrameXML\ZoneAbility.lua:162
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 AceConfigDialogTooltipTexture20 = AceConfigDialogTooltipTexture20 {
 }
 CinematicFrameRaidBossEmoteFrame = CinematicFrameRaidBossEmoteFrame {
 }
 ElvUI_Bar5Button12Shine7 = ElvUI_Bar5Button12Shine7 {
 }
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:957
 StackSplitFramePixelBorderTOP = StackSplitFramePixelBorderTOP {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 ElvUI_StanceBarButton7PixelBorderRIGHT = ElvUI_StanceBarButton7PixelBorderRIGHT {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 LibDBIcon10_BugSack = LibDBIcon10_BugSack {
 }
 FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
 }
 CombatConfigColorsColorizeDamageNumberSchoolColoringPixelBorderLEFT = CombatConfigColorsColorizeDamageNumberSchoolColoringPixelBorderLEFT {
 }
 CompactUnitFrameProfilesSaveButton = CompactUnitFrameProfilesSaveButton {
 }
 LFDQueueFrameRoleButtonDPSPixelBorderLEFT = LFDQueueFrameRoleButtonDPSPixelBorderLEFT {
 }
 ElvUI_Bar6Button6 = ElvUI_Bar6Button6 {
 }
 ACTION_SPELL_MISSED_POSSESSIVE = "1"
 RaidUtility_CloseButton = RaidUtility_CloseButton {
 }
 Is64BitClient = <function> defined =[C]:-1
 CompactRaidFrameManagerDisplayFrameFilterOpt

**Comment by InfusOnWoW** [comment]
You need to give us your settings.

**Comment by lovetoseeit** [comment]
> You need to give us your settings.

Can you be more specific on what you need exactly?

**Comment by InfusOnWoW** [comment]
Your WeakAuras.lua file from the WTF folder. The template asked you for that file....

**Comment by lovetoseeit** [comment]
> Your WeakAuras.lua file from the WTF folder. The template asked you for that file....

i hope this is the right file

**Comment by InfusOnWoW** [comment]
I don't see any file.

**Comment by lovetoseeit** [comment]
> I don't see any file.

had to edit, because website didnt support the format i sent

**Comment by InfusOnWoW** [comment]
I cannot reproduce the issue. You can attach the WeakAurasOptions.lua file that is found in the same directory?

**Comment by lovetoseeit** [comment]
there you go : https://easyupload.io/a4kfha

**Comment by InfusOnWoW** [comment]
Still can't reproduce this, it just scrolls correctly for me.

Does this bug depend on which groups you have expanded? Or on which class you are logged in?

**Comment by lovetoseeit** [comment]
It was  bugging when a group of WA was longer than the actual screen height i have, and having to scroll down, most of the time it was on a list of WA done for dungeons (made in a large group of WA), class didnt matter as far as i remember, because i had this issue on retail on my warrior, and on beta with my DK or monk

**Comment by lovetoseeit** [comment]
also since i updated beta1, i havent had this issue yet. I didnt update to beta 2 yet

**Comment by InfusOnWoW** [comment]
Right, I watched your video a few times, and tried to reproduce it based on that. If you happen to have the same problem, please report back and maybe with more instances of it happening we can figure out what is happening. For now, there's nothing left to do though.

**Comment by wing5wong** [comment]
i have also experienced this. not 100% sure on the reproduction steps but will monitor this a bit more and offer some feedback when i have it

**Comment by wing5wong** [comment]
https://imgur.com/a/ei6Gw0p

trying to scroll up and the handle will not go up. scroll to the bottom and it then will scroll to the top. not really useful without the reproduction steps but definitely occuring

**Comment by wing5wong** [comment]
here i reload, open weakauras, scroll down to the bottom, now i cant scroll up
https://imgur.com/a/M9TUFqk
