### ISSUE TITLE
Custom options unreachable after removing description from option group.

### ISSUE THREAD

**Issue by aredon** [WeakAuras/WeakAuras2#2473]
## Describe the bug
I removed a description from an option group and placed it above. Then I added some text to a separator above that. I received an lua error and was then unable to access the custom options tab and errors are spat out every time.

**Do you have an error log of what happened?**
```
7x WeakAurasOptions\AuthorOptions.lua:1898: attempt to index field '?' (a nil value)
WeakAurasOptions\AuthorOptions.lua:1898: in function <WeakAurasOptions\AuthorOptions.lua:1838>
WeakAurasOptions\AuthorOptions.lua:2542: in function `?'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:817: in function `EnsureOptions'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:791: in function `UpdateOptions'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:769: in function `ClearAndUpdateOptions'
WeakAurasOptions\WeakAurasOptions-2.18.4.lua:714: in function `ClearAndUpdateOptions'
WeakAurasOptions\AuthorOptions.lua:2492: in function <WeakAurasOptions\AuthorOptions.lua:2482>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[C]: ?
...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua:72: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua:306: in function `Fire'
...Libs\Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua:22: in function <...Libs\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>
```

### To Reproduce
As above I removed a description option from it's option group and placed above group via the button. Then I added text to a separator option at the top. Unfortunately I am unable to create a valid export string but I did dump the lua table here: https://pastebin.com/Pbw1NyDn

1. Click on 'custom options'
2. See error

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, no effect.

**Which version of WeakAuras are you using?**
2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [X] Classic
- [ ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
No idea.

### Additional Info
Here's the lua table. Sorry but wago won't let me import the string as it's invalid. I assume for a similar reason to why I can't open custom options now. I've also attached my SV file. Look for Darpeh's Trade Catalog v1.06
https://pastebin.com/Pbw1NyDn
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5211486/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
This is fixed.
