### ISSUE TITLE
attempt to perform arithmetic on local 'perc'

### ISSUE THREAD

**Issue by Quiley** [WeakAuras/WeakAuras2#2475]
## Describe the bug
Getting a lot of Error Messages in combat but can't find the selcted aura that could cause the problems. 
Have 3 Clips down below whenever bugsack find anything

**Do you have an error log of what happened?**

```
117x WeakAuras\Prototypes.lua:356: attempt to perform arithmetic on local 'perc' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\WeakAuras-2.18.4.lua"]:5301: in function <WeakAuras\WeakAuras.lua:5201>

Locals:
Skipped (In Encounter)
```

**Screenshots**

https://streamable.com/ccgdcq
https://streamable.com/uxwzdb
https://streamable.com/ojk8lo
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No
**Which version of WeakAuras are you using?**

2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

[Weakauras.zip](https://github.com/WeakAuras/WeakAuras2/files/5212881/Weakauras.zip)

**Comment by InfusOnWoW** [comment]
Your "screenshots" cannot be found. Please ensure that any screenshot you add actually survives for more than a few hours.

I cannot reproduce any issue with any of the auras that appear to run that code line, nor can I see anything wrong with the code. 

I need a better description on how to reproduce this.
