### ISSUE TITLE
Spell cache script appears to run too long and cause hangs.

### ISSUE THREAD

**Issue by razc411** [WeakAuras/WeakAuras2#2476]
Upon opening the WeakAuras menu, my game froze until I was able to hit the OK dialogue on the continue running/terminate application message window. This continues to occur after it occurs once. This occurs with a fresh install of Weak Auras.

```
Locals: self = <unnamed> {
 0 = <userdata>
}
elapsed = 0.033000
start = 11336931.051800
hasData = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 spellCache = <no value>
}
(for control) = "spellCache"
name = "spellCache"
func = <no value>
ok = false
msg = "Interface\AddOns\WeakAurasOptions\Cache.lua:40: script ran too long"
(*temporary) = false
(*temporary) = "Interface\AddOns\WeakAurasOptions\Cache.lua:40: script ran too long"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "script ran too long"
debugprofilestop = <function> defined =[C]:-1
dynFrame = <table> {
 RemoveAction = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3638
 AddAction = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3625
 frame = <unnamed> {
 }
 update = <table> {
 }
 size = 1
}
debugstack = <function> defined =[C]:-1

```

**Steps to reproduce the behavior**

I am running Shadowlands on Wine through lutris using wine-staging-git 5.17 with Arch Linux 5.8.8. To reproduce simply load the game up and open WeakAuras. You may need to add a weak aura.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.0-beta1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
3.0.0-alpha8

**Comment by InfusOnWoW** [comment]
That's because the game is crashing, which is a blizzard bug.
