### ISSUE TITLE
new WAs generate trigger settings/code from previously created ones

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2478]
## Describe the bug
the trigger settings / code that was added to a new WA is automatically added to any further WAs that are created.

**Do you have an error log of what happened?**

no error

### To Reproduce

1. Create a new text wa, custom - event and add some code (or any default trigger)
2. Create another weakaura
3. Notice how the trigger settings from the step 1 WA were applied to the WA created in step 2
4. (optional) Delete both weakauras and create a new one. Step 3 should occur

**Screenshots**
![](https://i.gyazo.com/597de49e4fb14337c4c68e6df54ad371.gif)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes

**Which version of WeakAuras are you using?**
beta-2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [x] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
beta-1 was fine

**Comment by chrisRidgers** [comment]
I think im seeing the same behaviour, doesn't appear to be consistent though.

Managed to get 2 weakauras setup tracking spell cooldowns before the 4th clone the 3rds settings, and they appeared to be linked.

Updating either the 3rd or the 4th auras Spell name field in the trigger settings would cause the other auras similar field to also update.

Tried deleting the 4 aura multiple times and recreating but it always seemed to get linked.

**Comment by InfusOnWoW** [comment]
The next release will cointain the fix for it.
