### ISSUE TITLE
Text Duration is not removed when buff is manually clicked off

### ISSUE THREAD

**Issue by krazyito65** [WeakAuras/WeakAuras2#248]
What steps will reproduce the problem?
https://wago.io/B1jc7JdrW -- this is for flame tongue enhance shaman, but it might work with almost any other buff that you can click off.

What is the expected output? What do you see instead?
expected: timer goes away when I click off the buff
actual: timer keeps going
http://i.imgur.com/zottUBw.gifv

(the glow in the gif means the buff is not active)

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Weak auras is the only addon enabled.

What version of WeakAuras are you using?
2.4.14

Please provide any additional information below.
I have 3 triggers in this aura, but they are mostly for condition checking, since i want it  'always active'.

**Comment by emptyrivers** [comment]
Can this be reproduced with a /cancelaura macro as well?

**Comment by krazyito65** [comment]
Yes it happens when you use cancel aura as well.

**Comment by InfusOnWoW** [comment]
Fixed in the alpha

**Comment by InfusOnWoW** [comment]
Reverted the fix as it caused a different regression. Will look at this agin.

**Comment by InfusOnWoW** [comment]
Fixed again in the latest alpha.
