### ISSUE TITLE
Confirmation prompt when closing code editor

### ISSUE THREAD

**Issue by d07RiV** [WeakAuras/WeakAuras2#2481]
**Is your feature request related to a problem? Please describe.**
Pressing escape while editing code closes it with no warning, discarding all changes. I'm very used to other edit windows (like macro editor) being ok to close this way, so I often lose a lot of typing.

**Describe the solution you'd like**
Show some confirmation prompt when attempting to close a code editor with changes made to the code.

**Comment by InfusOnWoW** [comment]
Well that would defeat the whole purpose of the key bind. If Esc would require clicking a confirmation dialog, the whole convenience is gone.

So that's not a good solution. I'm leaving this open for now, in case someone has a better idea.

**Comment by InfusOnWoW** [comment]
Looking through the default UI, only the macro window seems to not use Esc for Cancel. All of System Interface, Keyboard Bindings, Addons discard any changes if closed via Esc. 

So, then I'd argue that our behaviour is fine.
