### ISSUE TITLE
%c "on every frame" code only runs on trigger update (Shadowlands 3.0.0-beta2)

### ISSUE THREAD

**Issue by BartStam** [WeakAuras/WeakAuras2#2483]
## Describe the bug
I expect the `%c` code to run on every frame, but instead it runs only on trigger update.

**Do you have an error log of what happened?**
N/A

### To Reproduce
%c on every frame:
`function() return GetTime() end`

Trigger 1:
status -> conditions -> always active trigger

Trigger 2:
event -> combat log -> spell -> cast success -> define spell id

Required for activation: any trigger

Display text only updates when the spell in trigger 2 is cast.

**Screenshots**
N/A

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
3.0.0-beta2

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ ] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Yes, I assume in whichever one came before the big refactoring.

### Additional Info
N/A

**Comment by InfusOnWoW** [comment]
Well the bot was entirely correct. Deleting crucial questions doesn't help.

**Comment by InfusOnWoW** [comment]
Thanks
