### ISSUE TITLE
Trigger alternate Power is broken 

### ISSUE THREAD

**Issue by blabaer** [WeakAuras/WeakAuras2#2484]
![8D57D2A0-EDF7-4D81-8585-43D1080F8C4A](https://user-images.githubusercontent.com/71343411/93243045-f027b080-f787-11ea-930d-2f37723c24cb.png)
## Describe the bug

**Do you have an error log of what happened?**

```
PASTE ERROR HERE
```

See screenshot.

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

Sl beta 
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [X Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Yes

### Additional Info

https://wago.io/d5ruX4EC9

**Comment by cimba007** [comment]
Is this issue already fixed? In 3.1.4 it seems to still not work. Example WA: https://wago.io/iDDz2rtfT does not rigger in combat.
