### ISSUE TITLE
Using spark textures as ticks

### ISSUE THREAD

**Issue by Dracolince** [WeakAuras/WeakAuras2#2485]
**Is your feature request related to a problem? Please describe.**
I've noticed the (relatively) new tick feature for progress bars, and I love it for the most part but after a while the tick design starts bothering me since it's just a block of pixels and that can clash with some bar designs.

**Describe the solution you'd like**
I'd love it if you could optionally use a **SPARK** texture as the tick, so that you'd be able to create cooler designs for the ticks away from just rectangles.

**Describe alternatives you've considered**
The alternative is a complex and cumbersome system of several texture auras (the spark texture I mentioned). This new feature saves me a lot of work creating and placing the ticks, but I want to replicate the visual feel I had before.

**Additional context**
No more context, it's pretty self-explanatory I think 😋

**Comment by emptyrivers** [comment]
This has already been done, and will be available in 3.0.

**Comment by Dracolince** [comment]
Wow, NICE!

Thanks a lot for your hard work. I love fidgeting around with new features :)
