### ISSUE TITLE
REQUEST: Change "Status" Trigger to Non-Cloning

### ISSUE THREAD

**Issue by Snichy** [WeakAuras/WeakAuras2#2490]
As per discussion with Asakawa on the WA discord who suggested I post this suggestion here.  I have an icon-with-text aura that displays when a mobs nameplates is in view (Status > Unit Characteristics > Nameplate then manually enter mobs name in Unit Name).  It works fine but when there there are more than one of the same mob name in view it duplicates itself and asakawa said it was because it is a cloning trigger therefore I would like to suggest that it be changed to a non-cloning trigger with an "auto-clone" setting added to prevent duplicates occurring.

Thank you in advance.

**Comment by InfusOnWoW** [comment]
The design of the unit trype triggers make it much harder than it looks like. It was a conscious decision to not support that in the design.

You can achieve that via the limit option of a dynamic group though.
