### ISSUE TITLE
You can't have more than 84 entries in an "Option Group" array.

### ISSUE THREAD

**Issue by Lardeck** [WeakAuras/WeakAuras2#2491]
## Describe the bug
I expected to see the dropdown menu but instead i got an error.

**Do you have an error log of what happened?**

```
Message: ...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:111: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: AceGUI30DropDownItem85:SetPoint.
Time: Fri Sep 18 23:16:23 2020
Count: 1
Stack: ...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:111: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: AceGUI30DropDownItem85:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua"]:111: in function `SetPoint'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua"]:199: in function `Open'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua"]:392: in function <...as\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:382>

Locals: (*temporary) = AceGUI30DropDownItem85 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = AceGUI30DropDownItem84 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 1

```

### To Reproduce

1. Create any aura
2. Create an "Option Group" with the "Array" group type in author mode in the custom options tab
3. Go back to the use mode and create 84 entries
4. Open the dropdown menu
5. Create one more entry
6. Try to open the dropdown menu

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

WeakAuras 3.0.0-beta2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [x] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

I don't know.

### Additional Info

This is probably a AceGUI error but its triggered from WeakAuras so i post it here first.

**Comment by InfusOnWoW** [comment]
Please add a aura with 84 entries.

**Comment by Lardeck** [comment]
`!WA:2!1svZYTTnq4QrEM0HhQJvt800tkU)COZupoQToNfTLSDhfjxq6y3PhKajxkGykawaqjlFZ6qNCwpbD05Espc(jGJMo5bipc(jOaGuQj9E1bQD)2fy3pSFavAxBuTOArV95IB6fhlbvfX0sJLywiHloNtzQGJA11VfAviNNeXNW8MqtHb3V2Tv0qGiWHkkNjpejvyHYXLYOkNGy9FsIZmLGoCiiKF23kkn)JfrqqwCS)0uqCARoN3(IoUkTdcNjWnMjtHKKZIKoVxMfaJbMYtNn9ML9pQPNFFp)MiF3mDrcstWtbXM0oxa60qEN3QthKfj4uaNOiigEeiDMNXkBbN0DmD9yWVW)v8i4V(Kh0mgemCYR19RMsN8W1aK2u3pHkewtsYCmJoYyXom)tBNVTlJZG7bSe8ucGnurE0Qinjmz03qjHec5Si5mtogcNx3DeMY0RnVE(ZFu(E5Fv(xRnD(Vi6djjwz2lGSqZqem0Ck)DV9jP1uWnQ(scwpdUQCQL(mlO9tmxOBY(YsJ86Z3eBVVrM(4py5hXt4IFUsLkvFFbkKeBN8UnVWVx6NBbXzkUH1HxsJue3MA3hkke9giYcE3QcvZVw2o3BJ)MmPIgpnFRfcUsteFnOB3EDBLVTqtjtolSjgABJQ6FZlzatL(42c6T1)LmCK(qax33)Ji(6kTYInHlIUuGtNDzPrrdmMkPbjWGso)bk70DoRB3wO(U98979k0zNCQ)QnL2JEl8SsgD1hvhtuRUT3f(DoRBR3TAycFsBb87zalC65BDW(n(Pc2zcS08z9omZ4yw8QGmLIZ6ngeAb8cdChR45P28xZS5gNJ2CYCFMeozncX1eKyRUpHgEndKYQ2v4fItGcZoun8o2c4QpxabjGa0He1DUjCC0HUgP9UOrzjkQdkmblL7M774k183ySqyfDME2LQ1XZ3ipY3kq7hthURGNAu7V4p9D(F4hcNKsWvDVLZhvX1iehSqXdhxCb9lQ0F(E0iuxys9Fm9jRFwYiZoMkX6jFezzSqF5xF9uRHQ(qXmTTbYWQaVJqTA1DLEJ1W9Smr(LVZCFR0XjFB0qbplvOp(pgKHKfMht84zIqOcAIr8xDPoMESKGtLWGgxdtZ)nxtwZk2K6VyjHgbiWodgmpHoIQkEmyUDV9Tp(je4PZcl3gs(RFAJmA0YPbh)YPbHjUPVuqzgIRJ9M7YVAWcZll0IUC2AUtq)7DPAYL)W(hS)bFFaOWnQn(VV6Fo`

**Comment by InfusOnWoW** [comment]
I can reproduce the issue, this is actually a issue in how the library we are using is creating those drop down items. 

Each item is acnhored to the previous one, thus this creates a 84 deep anchor stack, and apparently wow doesn't like that.

Changing how the anchoring works, like this attached patch would fix that:
[AceGUIWidget-DropDown.lua.txt](https://github.com/WeakAuras/WeakAuras2/files/5248398/AceGUIWidget-DropDown.lua.txt)

I'll propose that patch to the AceGui maintainers.

**Comment by Lardeck** [comment]
Thanks a lot!

**Comment by InfusOnWoW** [comment]
Further information is at https://github.com/Stanzilla/WoWUIBugs/issues/40#issuecomment-695203489

This looks like a regression in Blizzard's anchoring code, so hopefully they'll fix it before the release. Or LibAceGui fixes their code to work around blizzard's new limitation. The maintainer of AceGui is aware of the problem.
