### ISSUE TITLE
Openning sound dropdown list causes Ace3 error

### ISSUE THREAD

**Issue by spamwax** [WeakAuras/WeakAuras2#2493]
## Describe the bug
Opening the list of sounds in any part of config panel causes an error window pop up.

**Do you have an error log of what happened?**
This is the error message:

```lua
Message: ...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:111: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: AceGUI30DropDownItem360:SetPoint.
Time: Mon Sep 21 04:36:56 2020
Count: 1
Stack: ...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:111: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: AceGUI30DropDownItem360:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua"]:111: in function `SetPoint'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua"]:199: in function `Open'
[string "@Interface\AddOns\WeakAuras\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua"]:392: in function <...as\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:382>

Locals: (*temporary) = AceGUI30DropDownItem360 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "TOP"
(*temporary) = AceGUI30DropDownItem359 {
 0 = <userdata>
 obj = <table> {
 }
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 1
```

### To Reproduce
1. Create a new aura
2. Go to condition tab and add a condition and select "Sound" as property change.
3. Select Play/Loop/Stop
4. Click on the arrow for the drop down menu of sound files
5. See error

**Screenshots**
![World of Warcraft 9_21_2020 5_34_55 AM](https://user-images.githubusercontent.com/1251233/93752240-5b301780-fbcc-11ea-805d-1386b3f192c6.png)

The first time error occurs, WA gives me access to list of sound files. If I scroll that list there is bunch of corrupted text at the bottom

**Consequent** clicks on drop down menu **_only_** opens up the error window without the sound list.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
WA is the only addon enabled

**Which version of WeakAuras are you using?**
3.0.0-beta2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
I believe it was working in 3.0.0-beta1 with rare occurrences of this error, in beta2 it's reproducible every time.

**Comment by InfusOnWoW** [comment]
This is a bug in World of Warcraft. A workaround has been commited to the AceGui library and thus this will be fixed in the next beta release.
