### ISSUE TITLE
Dynamic Groups: Counter Clockwise option not working

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#2495]
## Describe the bug

When using the "Counter Clockwise" option for animated group sorting, it does clockwise instead.

**Do you have an error log of what happened?**

```
no errors
```

### To Reproduce

1. Create dynamic group
2. Add 3+ auras
3. Set to counter clockwise

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

beta3

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [x] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
Works fine for me?

!WA:2!TBv3YTTXvyHI6ef4Ahl6FIvAtIQMjUUzgNXrXswU)Kjc0Kw0LMuce6NK(J0cGLeRfia8UaIsST2rm2UUtB6f8rGxMP3uo9bOJEcodNo5bWpcEYdqplaOmTSZy1B6n13aI9S7bNZ5778DwQSAoXmxNUDUM5CY58Ol1LWTlt9Be5E)Z9yRaUdLRtS3YHhegEkDpw72eUZuMbbErSq(ovRxxqJw8FDxTV(lgBSX47Mz4tnxXexpwFIVTBaFPaMFKv(cvmly0RESNxEg32JUPHiKyt)NVbNyhXc8fZziIi8inR6mFMWvth)jsRteN1ObLlE7lWZE9H9COwX1RBUBiLVyHYlvCLY6r4cdsmNmthri1ZRKJq7XIyl62u)OA4Pz70FJ8luZCJAMlyyQhJFCRqpYUuUHpPjvOzKCuRfPeVi3dCDjofD1O2sfkxUBSFwkO13oWlUPFnzjO(eSaPCFI3QyEILsPUcQx9K6gg3G4XA4dJZXQt6Qsp8tBqBilznDVaIZC6ygBFoJMXiUQzy7reIZbxutxWAtLVmWkJfYh4fWVPQQ6sQx(dNLt8znjru3zIzo9Br35wxVqTwSzBziSjEuvRuk0Tx6VfCAqdNO2DIjC6ufrEyQ1Czr0E8KCrcM77Slcfm7g8G4WmVQH5WX0fb8iD)aFQLDGFDwdTUPXgDCo4huCFkrqRfXt6DED40Wvh4GuHC7nKedxqr)CeDKNtgj4Q6njm)IWpl50Wph(fWVe)9eh2s)0SiTWvuuuFm(HqK0pQi22eW51wAH8LQCJbK4iSxRAysRK2(PUL2q(gD4bTszQErb2BNssNxzJUtZCMPcTv3gCMZAmNi3J3VohBgWsHeruFsAdCrPjzwBvlVrHcv6ipUC90gxpl)k5JXr1WJ1KfDCDe)AzLVKr(Yf6elOLLwD7jrawA6zXjoSyr0jXmlkbMuYz3(rtdhtbEnf41HXhyJQmNGw(iHgs3C)HlLKOlCCe01GtObNudEZtEb4upeMaYH42zGZQbNdEl48WKWBRb)q4hbVd8UW7PfoHuMTn1mTb(wbo0)(yWpU0t2Isdxq2agziZex4Asg9WeZN8YPkuvkirsAhZW3)dE0zcZfr3jAdHlbZ81t5cLWjtmM8OEah7H2qK9cC1UhS30VVi8uJ4(inaPwhkW0xyfZQHNoXi2deiBkTt4s9fWLpjnqSDOPe8Eds50pllD2pz)BJCbR(UW49s4dQjAuVs1kfGtZr1Q8m9soO9qbOA3SkWpk8uf5S2tTCmXr21mLP5Zu4dJ0GeBTW2L14KWoRL9sAcSntWSWzIz18idodNOuLkfm2qVQPz1Bzu6glAo4GqlfNtMvrR)mXrUBY8XQRywUuLcFZGgEbTkYP3jM6BV7sF)l)HZmBA1j3OV8XWVqh5cPZdSIJIc8RIkgCqzpP50RhoBY5hwzDLloy0K6(yl)ngAXvxUPBs0nDz2B5tfc1epQLmKk51Ym08ejbqpDMLLlL1WnAp4cZb)e5mq4NM88dsE(X6munbZRHdxdDjQWYAHNzOersExNjiiE64Q3oiOPIUSZWfkKP5nqn)uZatdJdlQA0kPVa01Gl1Fvx6IF02H670UkN5lNuG9YF5Mqj4M9Dyc59fLWiF(VxU)rNHXZ14PDfOeov)cMBcRmuOEYeT63TqvQqLkvuW(EAWQj6syTHkrPedvAJOepKLt8CwwpvacFMc854YFnQMGFtI6b(TWVd2a2ei7bwkGnMPoaf9Vo0iPcaxGb3wb2c8GMBc(qaeojChfGdIVbIg24aXWFWfAb7a7EwOTc87tDEBf4p6c3tfURk8fta75cD(UOq4lLa7Fl1pjvSSg8N3dEOc8Noet9XiXCf3LSVyTgnlDTq4(Qs(qoRCEn4V4kzUfvH)ksknHVYfEG7HzbmohXPKph4)F)yW)3a(iq)CGpsii4Ji)9okGFgY)axjEUSS5FTRTAXMLDUj3E5xenCLmbJKLqipf7rsqYfi4)AFRe8h5MjKfYIXrNm()vLGedhDwHePtXueGrk6WCXSs4)(juXL6F719MT5C2l38JM7PYbKrr64HkVslCeGFjCJD8J(3Qq8dbYxa0phI4KLBxSE(2I5d5sSwYEzT6PQcKwUV6tffhtYc4x7v6GxgrGKWXuEgLqkiIa6lGkUAMkqI)xQplUvX5Av9k30YrYbzeYbsbKJFLw4iqbJkcK6cKpqamdnFbxlmV825l)50lw6A1(vBT1HVGqYnJQfEGBUT)3R)F(d

is crrectly displayed.

**Comment by Stanzilla** [comment]
@InfusOnWoW try with this? https://wago.io/DNMbEtrMj

**Comment by InfusOnWoW** [comment]
I don't see any issue with that aura? It is set to counter clock wise and it behaves in that way.
