### ISSUE TITLE
Dynamic Group + Auto Clone Aura + Unit Frames not sticking to correct frame on GROUP_ROSTER_UPDATE

### ISSUE THREAD

**Issue by aredon** [WeakAuras/WeakAuras2#2497]
## Describe the bug
I expected the auras to follow their respective unitframes around as the group got reorganized.

**Do you have an error log of what happened?**
No error log as there were no errors.

### To Reproduce
https://wago.io/OToUOKOBa

Load this up and make sure there are empty slots in group 1. Buff someone with AI then reorganize the group. Add players, kick players, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/1328757/94076247-43ba7f80-fdc2-11ea-8c99-34264521463b.png)
![image](https://user-images.githubusercontent.com/1328757/94076265-4c12ba80-fdc2-11ea-9ad5-d5ca6fd2717d.png)
![image](https://user-images.githubusercontent.com/1328757/94076658-3782f200-fdc3-11ea-95d2-49de49261f18.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [X] Classic
- [ ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Don't know

**Comment by mrbuds** [comment]
This will be fixed in next release with https://github.com/WeakAuras/WeakAuras2/commit/f3253736d8b8bdeee4e4981dd070d2d8953a6d6e
