### ISSUE TITLE
Custom Condition code claims errors when there are none.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#250]
What steps will reproduce the problem?

Use any aura, enable a condition with custom code. Write a standard script, such as:
```lua
local h = "Hello, World!"
print(h)
```
(note that this only seems to occur with scripts that begin with `local`)

What is the expected output? What do you see instead?

Expected: Nothing.
Actual: The large editbox erroneously claims that there is an error in your script, as if you need a function constructor wrapping it.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

Yes.

What version of WeakAuras are you using?

2.4.14-1-g4e1c086-alpha

Was it working in a previous version? If yes, which was the last good one?

Unknown.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

This is a runtime error, so no logs to show.

**Comment by emptyrivers** [comment]
Can also reproduce as far back as release 2.4.10 (which was the version I was using before switching to alpha branch)

**Comment by Healarious** [comment]
It does work regardless of error text BUT:
it does not only give an error text when your code starts with local but it also gives an error text when any of your code contains ANY keywords

**Comment by InfusOnWoW** [comment]
Fixed in the last alpha.
