### ISSUE TITLE
Frame Strata controls do not work for weakauras managed to Personal Resource Display

### ISSUE THREAD

**Issue by Kretuhtuh** [WeakAuras/WeakAuras2#2500]
## Describe the bug
For shadowlands I'm anchoring my rotation weakauras to the Personal Resource Display. However, other UI elements will draw in front of those PRD-anchored weakauras, and changing frame strata options do not resolve the issue.

### To Reproduce
Create a weakaura that anchors to the personal resource display, then overlap it with another UI element that should have a lower strata.

1. Create two weakauras that are always visible and overlap (e.g. big icons that display if player health > 1), Aura A and Aura B
2. Anchor Aura A to the personal resource display, set the frame strata to high
3. Anchor Aura B to screen, set the frame strata to medium
4. Observe that Aura B is drawn over Aura A, frame strata is not working as configured
5. Change Aura A to anchor to something else, such as mouse cursor.
6. Observe that Aura A is now drawn over Aura B, frame strata is now working as configured

**Screenshots**
https://i.imgur.com/SH6cXby.png
The green bar (player health) is configured to have a medium frame strata, the nameplate is configured to have a low frame strata, yet the nameplate draws in front of the health bar.

Same thing with no other addons https://i.imgur.com/6LYJeGR.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
WeakAuras 2.18.4

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
First time encountering this issue

**Comment by mrbuds** [comment]
Can you include an export of your aura ?

**Comment by Kretuhtuh** [comment]
The group is currently set to only load on warrior https://wago.io/0mW69-Eoy

**Comment by InfusOnWoW** [comment]
That's because the personal ressource display is special. If you disable the "Set Parent to Anchor" option the frame strata behaves as you expect.
