### ISSUE TITLE
Multi select for "Filter by Group Role" in Bufftrigger.

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2501]
**Is your feature request related to a problem? Please describe.**
I received this request https://i.gyazo.com/d7428a4ba356c4df29ba606e815ec063.png
and the simplest way would've been to use a smart group trigger and tell the person to filter himself,
but since only one role can be chosen to filter, I'd have to custom code it.

**Describe the solution you'd like**
A way to select multiple roles to filter

**Describe alternatives you've considered**
custom coding or maybe duplicating the aura for each role..? But the latter sucks a bit for user experience

**Additional context**
![](https://i.gyazo.com/da8faac3f713bc0adcba5c04c4098591.gif)

**Comment by InfusOnWoW** [comment]
I'm pretty sure I won't find time until after the shadowlands release for it.
