### ISSUE TITLE
Multi selecting auras can cause them to move to other groups

### ISSUE THREAD

**Issue by Sharrq** [WeakAuras/WeakAuras2#2503]
## Describe the bug
Occasionally, if i move a weakaura up or down within a group, it can cause auras that i previously multi-selected or multi-edited to also move into that group even though they arent selected anymore.

**Do you have an error log of what happened?**
I did not see any errors, but i will see if i can find one.

```
PASTE ERROR HERE
```

### To Reproduce
Im working on finding a way to reliably reproduce it. But this happened multiple times while i was making a bunch of changes to auras. As an example, i selected like 4-5 auras in one group and changed something on all of them (to make them bigger or smaller, or whatever). Then made some other changes, multiselected 2-3 other auras in another group and edited them. Made some changes to some other auras, duplicated some auras. Then i go to move an aura down in the list below another one, and all of the ones i multiselected 10-15 minutes earlier were all moved into that group and i then had to move them all back to where they should be and then rearrange them so they are all in order again. This happened like 4-5 times over the course of 2-3 hours while I was redoing my weakaura suite.

Working on coming up with steps that cause it to happen every time, havent managed to find one yet.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No i didnt, but the error is happening within the weak auras UI and not the auras themselves

**Which version of WeakAuras are you using?**
2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Never ran into this issue previously, but dont know of any particular version where it didnt happen

### Additional Info
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5285814/WeakAuras.zip)
I was specifically working with stuff in the _Abilities, _Cooldowns, _Buffs, _Defensives, and _Resources & Alerts. It wasnt any one particular aura, just anything i previously multi selected or multi edited.

**Comment by InfusOnWoW** [comment]
What kind of method are you using for multi-selection?

**Comment by Sharrq** [comment]
I was holding ctrl and clicking them.

**Comment by seanpeters86** [comment]
I have been making auras the past couple weeks on various versions and noticed this on Shadowlands beta client as well. This happens when also manipulating multiple auras at a time and then going to move something later.

**Comment by InfusOnWoW** [comment]
I can't reproduce that. Can either of you record a video of the issue, so that what you are doing is visible?

**Comment by Sharrq** [comment]
Managed to reproduce it.

1. Multi select several auras and then close Weak Auras
2. Open Weak auras again (notice they are still multi selected)
3. Click any other aura (It will show that you deselected the ones that were multi selected previously)
4. Click and drag another aura up or down. The auras multi-selected in Step 1 will also move alongside them even if its another group.


https://imgur.com/a/3vICkc4

**Comment by emptyrivers** [comment]
Thanks for following up on this, we'll look into it some more.
