### ISSUE TITLE
SubElement Model Not Showing After Loading

### ISSUE THREAD

**Issue by Downertool** [WeakAuras/WeakAuras2#2504]
## Describe the bug

I have a SubElement Model #166902 which overlays my Battle Shout hotkey when Battle Shout is missing.  The model overlay will stop working after I load in or change zones.  I can force it to work again if I check and uncheck the box to Never Load (turn it off/on) or if I re-enter the model ID on the display tab.

**Do you have an error log of what happened?**

No error log.

```
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, issue still occurs with only WeakAuras enabled.

**Which version of WeakAuras are you using?**

2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

Sorry, I don't remember what version it was, but it worked when the SubElement Model was added first added. Prior to that, it was taken from Titania's warrior package that I adjusted to make it work for my UI layout.

### Additional Info

https://wago.io/jq2iabdxZ is the import string

**Comment by Downertool** [comment]
I have re-created the weakaura from scratch and it appears to work just fine. Everything was setup the same.  I also downloaded Titania's 8.3 Fury warrior suite and those work as well.  Is it possible some old code in the WTF folder?

**Comment by Downertool** [comment]
As I started remaking my weakaura, I noticed it started having the issue again.  It only seems to happen if the weakaura is touching another UI element.  The SubElement model does not show if I move it to overlay my hotbar ability.  This happens for ElvUI hotbars as well as default.

**Comment by InfusOnWoW** [comment]
I can't reproduce that at all. I've run through multiple portals and relogged a few times.

I need more information on how to reproduce this, it's unlikely that the positioning has much to do with it, unless it's entirely obscured by a different ui element.

**Comment by Downertool** [comment]
Thank you for looking into it.  Sorry I don't know what steps to do to try to reproduce this on another computer.  I was on earlier today and the weakaura models were working.  I don't understand why.  I will see if a friend in game can try and help discover how.
