### ISSUE TITLE
Custom cooldown vertex

### ISSUE THREAD

**Issue by souleiman** [WeakAuras/WeakAuras2#2506]
**Is your feature request related to a problem? Please describe.**
I wouldn't necessarily say it's a problem but does produce some precision issue when creating a Texture Progress and you want to control the representation of the texture cooldown utilizing some geometry. The precision issue is obvious when the cooldown is rather long, for example, a 30 second cooldown will show completed when the aura finishes but it's hard to distinguish a 3 minute cooldown at 97% vs 100% visually without adding some form of states

Image shown below has 4 square textures (corners) with various cooldown orientation (clockwise/anticlockwise).
![image](https://user-images.githubusercontent.com/1203609/94587591-ce7efc80-0250-11eb-8a74-86368f3c8c18.png)

This is the behavior and it does work as intended, left corners (but with some caveat). Since the notches are made for clarity and keep the UI clean and consistent.

https://media.discordapp.net/attachments/275445461131984897/760203913688645642/ptr_1.gif

**Describe the solution you'd like**
The solution I am recommending is to be able to define the cooldown vertex region, in such a way that it's not in the center but rotates from that vertex. With respect to my implementation, I would use a rectangle texture and have the vertex set to one corner. For example, if I have a texture of size 32x32, instead of having the cooldown center vertex at (16, 16), I would like to add it to (0, 0), and the cooldown line appears at (0,0) to (0, 32), it will rotate from (0, 32) towards (32, 32) and end at (32, 0).

**Describe alternatives you've considered**
N/A, but open to suggestion/solution if one exists. Currently I am resolving this by creating a custom rectangle texture .tga and setting the start/end degree. As shown below, 

![image](https://user-images.githubusercontent.com/1203609/94588797-66311a80-0252-11eb-94a6-65a944d25377.png)

**Additional context**

If it helps to view the behavior, here's the WeakAura in question.
https://wago.io/BJqUUcobz

**Comment by InfusOnWoW** [comment]
That's far too niche for the complexity it would require.
