### ISSUE TITLE
Buffs on Frames explude actual Player Frame

### ISSUE THREAD

**Issue by Tizula** [WeakAuras/WeakAuras2#2512]
## Describe the bug
I built a Dynamic Group with HoTs to help healing. So if the party member has a hot from me on it, it shows the buff. i built my ui in a way that the party frame sits on top of my player frame. party and player frame also look the same and the player is hidden in the party frames. so when i join a party the other four members appear above my player frame and i dont need myself as part of the party group too. so my weakaura works fine on party members, the dynamic group is "group by frame" -> Unitframes and at the bottom at position settings its Screen/Parent Group. what happens is that the hots only show on my party frames but not on my player frame. so when doing group content i am missing the hots on myself

**Do you have an error log of what happened?**

![Screenshot_4](https://user-images.githubusercontent.com/66146687/95003032-17310f80-05db-11eb-90c5-59d366151289.png)
![Screenshot_5](https://user-images.githubusercontent.com/66146687/95003063-70993e80-05db-11eb-9415-93ad0d96dbb3.png)
![Screenshot_6](https://user-images.githubusercontent.com/66146687/95003064-7131d500-05db-11eb-81cc-7c0b670d7bb7.png)
![Screenshot_8](https://user-images.githubusercontent.com/66146687/95003239-90316680-05dd-11eb-8cbb-71ecf63e878d.png)

```
PASTE ERROR HERE
```

### To Reproduce
i tested the weakaura on wrong triggers, but thtat does not seem to be a problem. they are loaded properly and if i set the anchor specifically to the player frame or any other unit and put hots on myself, it does work fine. so in that regard it is ok. it is not a trigger problem where the player is excluded or something.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes
**Which version of WeakAuras are you using?**
2.18.4
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info
i am not sure if it is a bug or just me having wrong settings. my guess was that i need a custom anchor that specifies to show the weakaura on party frames and the player frame. but i lack the skills to do that and test it. my coding knowledge is very basic and i could not find anything that i could understand on the weakaura github documentation.

**Comment by mrbuds** [comment]
Player Unit Frame is ignored by default by LibGetFrame, and group by frame / unit frame does not give options in the UI to change that.

I'm not sure what is the unitframe addon you use but i'll guess it's elvui, to work around that lack of option and achieve what you want, player frame should be hidden and your party frames should include player frame.

**Comment by InfusOnWoW** [comment]
Yeah, this is working as intended and is simply due to how you have setup your elvui.

**Comment by Tizula** [comment]
> Player Unit Frame is ignored by default by LibGetFrame, and group by frame / unit frame does not give options in the UI to change that.
> 
> I'm not sure what is the unitframe addon you use but i'll guess it's elvui, to work around that lack of option and achieve what you want, player frame should be hidden and your party frames should include player frame.

this is not an option because then i wont have a player frame when i am not in a group. my "workaround" is that i copied my grp and stuck it to the player frame as explained. works fine, i just have to have two weakaura setups. thanks for your reply.
