### ISSUE TITLE
Queued Action trigger not firing when multiple QA WA's exist

### ISSUE THREAD

**Issue by C9Agent** [WeakAuras/WeakAuras2#2514]
The Queued Action trigger only fires if it's a part of the first WA created with a QA trigger. If subsequent WA's are created with QA triggers in them, those subsequent QA's will never fire, even if the original one is unloaded (as a result of settings in the Load tab).

This WA works as expected (displaying a flashing icon when the druid ability Maul is queued up:
`!WA:2!DrvWUTTrq0QAdydcKIy10GMEkThCDccmQnAc6vrz5yvilPUKo29K0sYHKBn1US7UuYo3IoLd9KUvGEsN7j9j4VacHI8bKpb)f0zxk56uDqC2zMDM5nZB2AhxFu9O6rV)BjHImH8N3a)jVUxCSc0)vTfuEyQq2xW46GMT663ISmuiYIet4Ety5WWBwFSvucKkPHAMGREfrPPsTJlJZ0obX4hvQZuTKLKas1xSRCL4hC1xNdbO36cLSGdJbU2LwOftJkKutWQFaXQD5Vuafq0tBytHBbg5G8m61GCMkhYY6shbBV7FUSqbdUtXWPwX2rkNpQkcSbQVeIzxr863QtNPgVnHAiHJUFpV8kIrVwmOzdp)bE(ni(ZJGauPpwWYtA1P)XN1zwbFfqCY3XG9XGF15tfrWF)z3I9nqYPzVbrnw1nV9saYBG1uOMyqx6mkNnYIZxvU9BkFqqUeWw)uGQatMC5coSCDVyGPBjvqOGhPk3nqLkz8lVX4SNwc8eD6wUJOmogPYDl)(Y9kFw5Zl3DonlpL2VitbLVyRsN)Nz3ePycAarOcheyUG05yJGajMP5ZF)JYRRHR0duPuCwFrf9Ow(tSkT)flKimgOwjuU3S7Sv)G8hEVB30YZQvR2gFSslKfBjyUnoZVx(xAvAyaM2s45SiDQBd84Tv5HDfezv(ULvKZFDv1CJ1(VvO0S4Rl3CUuGKkWhv62Tx3wLpqIiY4ZCRJ)hDF2kaW15FtxHw4r5QN6bJynXUmWvqKlsX)KoW6CU0QBIqgDUKMp98vcvLYyMIfKbdxH(7TkLVt7UDBrg42Z3V3PK2V(e)L3veES3cpzf2U4tYJXQL917m)oT726dltYetowc)EbWdVU)M)W(h(YkCAmCdYTFD2QgE6uJkZTxguO1cEVXGe3EMBu3XYC(Qfg51qBwY6RABsUMJdTECxrzJykl8soOuByVGxindQe7Wq17yJVl2xazAqkWss1VZntqJoEMz1lmJQudDnlepMmQitZCiwDi3MXtYaYrKZAFu5ahxf2xEmkmxAzL2LdgUiucdNDhhQCZfrmL5zH2OPV(Z3Cp33keJQv(W05Ar44Q1WTFXZ(ow0ItPfz2Ntgd5pA97ygcZrmffNCrPlIL4Rc4Qfvt3GmzfTRqJJME52x6CcW8eZsCWfrt0H0dlWq)YXn4xfehtoHiVQQF9hBn3S2YQU2Tvd4JnX3aLaVMKwT6sSlQBuxfC4(h8t7)J1h)px8Vp`

Creating a new WA using the Duplicate feature on the above WA, then switching the load condition from Druid to Hunter and the spell from Maul to Raptor Strike produces this WA, which doesn't function at all:
`!WA:2!LrvZUTTrq4OOaed1GIAf3GMEPU9GBsAHrJtBAVkQkh7czkvs6y3CrAj5qY1MAx2DxkzNlfvNYzDUN05Esa9fWpbeef9biOOpa(jOZUus1b1hSgo)SZmF733wB)MJAg2m8nFQ4YErrsq9B1wqybjCrFoLP8B3X2RJtzaNNgYNWCNqZGHxT6ZoHXqIGeOOCM85osfrOA4hrzuzsdl8hvJPkbnogeY3FhXsZ)XsDzg4JzRYLVvM7dJbMYnpkIEXIbTB56nW1RLJ38qWhD6HjloOt3(7FC3PH5cIUBnFQJPQYFmhYHWTBzMHS7NlHbWf4enqMbPP2KrqYuTZCCygwQTwhy4uJ5HHYgRNI(caNch3(D621sxJFwk5sq4WWcKne5mtAwKCfF26tAJV9pMLZwUEnY2uJiJbVQVpIhc)(TUgrtqWiPVeXcCuBF95aK1cpIaLJELsMry0rML75f39Lf3Zpta4fYuGibngyX4mOCfamqJHcjeWzHYR054QealwLC3ID8Ljck7CRrekdpPIDk(8Ihv84INu8fy05K0Ses)8ujuSX)pSvSGpbXEjE9G9csMJGJdeRVJFYB2kRPcUaH3ecYaoTI0ul7HgNM)fXf4AmqU0O4rZwhBVJSEw2hCJ6BZt5IFOwTA1FBLxinYq8SADSxVS7BCQXAnWeCcnuLy1c)86QorVacno)1Yks7pTCEUYe)SCPIgDzr95cos2ap0PLDp7of3tG7KoN5MedmJrD8VzlxbMk7JT5kUlHj32fgrBJ4mWKqOfs9Fhmyvpln(MWfHNiiztpzPr1OmMkP(PWWLB)nKyzBEOTDhNbw9886DKZHV4aVY1dHl91WdxUBN(o9rh1Om6DSx3dT78xLXP8j7lGFohybx2)oF1U79nwAFdVcz9ViDjyNmv7txzPFUsXz9gdcKIpx7URHa9Hl02RwRzXRk1aqvqN2NjRtVzwUbKuOUzq8sObNZaPSUjsxkAVPPhwiUaIe)eGgNOiwPCs4(Z0cZGuIuo0sljEGZO8ufTHJXhYNPS4uW)GJ1VgvmSHLebMhGgZfgIPrFqrTWIibQhrParrQlUOA6(73RiA4CTsHAEPQr2wREbttj(EQKG3nHjfFsYCfpyCLcDJV8XFgnmBlhsMIl2gpt65G5HMXG1R58r1CmcP6xxD)SVUZ6bX3TTtNo2o)hRYh7DenUbkk1hoKSxonCXzIN9Qu7Zo3t9QzRj(f1xesL6hDoel6JU9D(fNjAgoPeLbyx6LvTcnL(7T7t)UD)6MJ)Zt)3)`

**Comment by mrbuds** [comment]
Can you copy here the result of these commands in the chat
`/dump C_ActionBar.FindSpellActionButtons(select(7, GetSpellInfo(GetSpellInfo(14261))))` done on your hunter
and
`/dump C_ActionBar.FindSpellActionButtons(select(7, GetSpellInfo(GetSpellInfo(9881))))` done on your druid ?

**Comment by C9Agent** [comment]
This is interesting; for Druid I'm getting a position on the bar ([1]=97) but for Hunter I'm showing an empty result, even though the Raptor Strike ability is on my action bar.

![Screenshot_6](https://user-images.githubusercontent.com/33342506/95214786-fddace00-083b-11eb-917b-95528845085e.png)

![Screenshot_7](https://user-images.githubusercontent.com/33342506/95214827-07643600-083c-11eb-834e-ab97d5d9693c.png)

I wasn't expecting an empty result. This calls for some more experimentation on my side; I'll report back with my findings.

**Comment by C9Agent** [comment]
Ok, some unexpected results.

On my Hunter, if I drag an ability from the spellbook onto any action bar, FindSpellActionButtons() throws an empty result and QA does not fire when I activate the ability. However, if I create a simple macro (/cast Raptor Strike) and place that macro on any action bar, FindSpellActionButtons() returns a valid value and the same QA will now fire when I activate that macro.

This seems to suggest that there is no issue with WA but rather with the FindSpellActionButtons() function. I suppose that amounts to a closed ticket on this hub and I can now solve my original problem by using a macro instead of a raw action button, but I'm still curious about why this is happening. Any thoughts before you close the issue?

**Comment by mrbuds** [comment]
The major difference i see between your hunter and druid is you are using the main action bar on druid (1-9 ..), while the action button used for hunter may not be a standard button since you use an addon that replace your action bars.

Anyway i don't think there is a way to work around this and i'll close it as "wont fix" for now.
