### ISSUE TITLE
Infinite error count during WA addon loading.

### ISSUE THREAD

**Issue by imp0** [WeakAuras/WeakAuras2#2515]
## Describe the bug
By the time I enable weakauras addon and reloading UI, I'm getting those infinite loop errors and can't play at all.

**Do you have an error log of what happened?**
Message:
Interface\AddOns\WeakAuras\BuffTrigger2.lua.1665:
attemp to call field 'IsPaused' (a nil value)
Time:....
Count 22000++ (never stop counting)
Stack:Interface\AddOns\WeakAuras\BuffTrigger2.lua.1665:
attemp to call field 'IsPaused' (a nil value)
[string "=[C]"]: in function 'IsPaused'
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua.1665: in
function
<Interface\AddOns\WeakAuras\BuffTrigger2.lua.1664>

### To Reproduce
Infinite loop errors don't let me use weakauras at all.

Just enabling the weakauras addon on Shadowlands Beta

**Screenshots**
https://prnt.sc/ute018

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did yes. the same happened

**Which version of WeakAuras are you using?**
3.0.0-beta3 (2020-09-21)

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Yes it did with 3.0.0-beta2 (2020-09-14)

**Comment by mrbuds** [comment]
You are using wrong files download it from https://github.com/WeakAuras/WeakAuras2/releases/download/3.0.0-beta3/WeakAuras-3.0.0-beta3.zip
