### ISSUE TITLE
Message: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1665: attempt to call field 'IsPaused' (a nil value)

### ISSUE THREAD

**Issue by OmarMAbbasi** [WeakAuras/WeakAuras2#2516]
I am getting this on load in Beta right now. There are no other addons active, and I have the most recent build for the Shadowlands WeakAura. 

Happening on line 1665 in BuffTrigger2.lua

`
Message: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1665: attempt to call field 'IsPaused' (a nil value)
Time: Mon Oct  5 11:51:34 2020
Count: 220
Stack: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1665: attempt to call field 'IsPaused' (a nil value)
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1665: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1664>

Locals: (*temporary) = nil
(*temporary) = "attempt to call field 'IsPaused' (a nil value)"
WeakAuras = <table> {
 halfWidth = 0.650000
 normalWidth = 1.300000
 doubleWidth = 2.600000
 SetTextureOrAtlas = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:894
 RegisterRegionOptions = <function> defined @Interface\AddOns\WeakAuras\Init.lua:63
 BuildInfo = 90002
 defaultFont = "Friz Quadrata TT"
 buildTime = "Dev"
 IsCorrectVersion = <function> defined @Interface\AddOns\WeakAuras\Init.lua:37
 prettyPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:41
 IsClassic = <function> defined @Interface\AddOns\WeakAuras\Init.lua:33
 WA_ClassColorName = <function> defined @Interface\AddOns\WeakAuras\AuraEnvironment.lua:72
 L = <table> {
 }
 WA_Utf8Sub = <function> defined @Interface\AddOns\WeakAuras\AuraEnvironment.lua:91
 PrintProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:439
 GenerateUniqueID = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:100
 regionPrototype = <table> {
 }
 CallCustomConditionTest = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:120
 defaultFontSize = 12
 CancelScheduledProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:385
 StartProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:322
 RealTimeProfilingWindow = <unnamed> {
 }
 RegisterRegionType = <function> defined @Interface\AddOns\WeakAuras\Init.lua:60
 versionString = "Dev"
 scheduleConditionCheck = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:94
 ToggleProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:377
 newFeatureString = ""
 createSpinner = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:474
 CountWagoUpdates = <function> defined @Interface\AddOns\WeakAuras\Init.lua:94
 StopProfile = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:350
 frames = <table> {
 }
}
Private = <table> {
 CancelAnimation = <function> defined @Interface\AddOns\WeakAuras\Animations.lua:382
 Animate = <function> defined @Interface\AddOns\WeakAuras\Animations.lua:173
 RegisterGroupForPositioning = <function> defined @Interface\AddOns\WeakAuras\Animations.lua:167
 LoadConditionFunction = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:582
 Modernize = <function> defined @Interface\AddOns\WeakAuras\Modernize.lua:5
 RemoveHistory = <function> defined @Interface\AddOns\WeakAuras\History.lua:54
 CleanArchive = <function> defined @Interface\AddOns\WeakAuras\History.lua:21
 StartProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:69
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:75
 RunConditions = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:589
 SetMigrationSnapshot = <function> defined @Interface\AddOns\WeakAuras\History.lua:65
 GetProperties = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:377
 StartProfileUID = <function> defined @Interface\AddOns\WeakAuras\Init.lua:78
 ProfileRenameAura = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:282
 GetMigrationSnapshot = <function> defined @Interface\AddOns\WeakAuras\History.lua:72
 UnloadAllConditions = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:728
 StartProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:66
 RenameConditions = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:768
 ConvertBuffTrigger2 = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:2568
 CanConvertBuffTrigger2 = <function>
`

**Comment by InfusOnWoW** [comment]
You downloaded the wrong file. Download this: https://github.com/WeakAuras/WeakAuras2/releases/download/3.0.0-beta4/WeakAuras-3.0.0-beta4.zip
