### ISSUE TITLE
Show and edit RGB Values with Coloring

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#2518]
**Is your feature request related to a problem? Please describe.**
Lately I'm using Borders with my Weakauras and like to color them to make the status more visable. But If I create new Auras or like to edit old ones by switching to another color (maybe a Green to Blue or smth. like that) I have to set it manually for every Aura with no visual mark what color tone I chose with the first one. I have to point with the nail of my finger on the screen to set it all to the same color. That's kind of annoying for such simple thing. Also it is almost never the excact same color tone because I can only reckon it.

**Describe the solution you'd like**
I'd like to have the RGB Values to be shown and to be edited. The values are already there (code wise), because you can set them by custom code. You could add three new writable fields (RGB) and let me set the color that way. So I don't have to precisly click on the color table. I can write down the numbers and have the exact same color like my other Auras.

**Describe alternatives you've considered**
There is no alternative method, other then let it be as it is.

**Comment by emptyrivers** [comment]
https://mods.curse.com/addons/wow/colorpickerplus

**Comment by InfusOnWoW** [comment]
This is working link: https://www.curseforge.com/wow/addons/colorpickerplus
