### ISSUE TITLE
OmniCC display duration after closing WA options

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#2523]
## Describe the bug
When you enable CD in display OPTIONS event starts fake duration. When you close options this duration remains on the aura. Also hide cooldown checkbox do not help with that.

**Do you have an error log of what happened?**
no error

### To Reproduce
Create any aura, enable cooldown to start duration, close options

**Screenshots**
https://www.youtube.com/watch?v=-6lX6uG-2UM&feature=youtu.be
https://www.youtube.com/watch?v=FlFdvTzmgGA&feature=youtu.be
https://imgur.com/82ZufbV

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
Latest test was with beta-3

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [ ] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Not sure, i didn't use hide cooldown text that often, but iirc there was some omnicc changes in some of alpha/beta shadowlands releases

### Additional Info
OmniCC version was ## Version: 9.0.0-beta, same issue exist with retail version

**Comment by mroesler** [comment]
This now comes up with the following error and WA does not open anymore (3.0,3 is the first version I actively noticed this):

Message: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:361: attempt to index field 'Cooldown' (a nil value)
Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:361: in function `modify'
Interface\AddOns\WeakAuras\WeakAuras.lua:2863: in function `SetRegion'
Interface\AddOns\WeakAuras\WeakAuras.lua:2758: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2664>
Interface\AddOns\WeakAuras\WeakAuras.lua:2793: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:2324: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:2331: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1010: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:982>

Time: Sun Oct 18 23:51:48 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:361: attempt to index field 'Cooldown' (a nil value)
Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:361: in function `modify'
Interface\AddOns\WeakAuras\WeakAuras.lua:2863: in function `SetRegion'
Interface\AddOns\WeakAuras\WeakAuras.lua:2758: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2664>
Interface\AddOns\WeakAuras\WeakAuras.lua:2793: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:2324: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:2331: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1010: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:982>

Interface\AddOns\WeakAuras\WeakAuras.lua:1058: in function `Login'
Interface\AddOns\WeakAuras\WeakAuras.lua:1132: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1083>

Locals: <none>

**Comment by InfusOnWoW** [comment]
@mroesler that's a outdated OmniCC then

**Comment by mroesler** [comment]
you are correct. I removed omnicc a while back from the launcher but there were still remains from it in the addons folder. Problem solved now, thanks.
