### ISSUE TITLE
Changing the model subelement of multiple progress bars simultaneously produces a lua error

### ISSUE THREAD

**Issue by BartStam** [WeakAuras/WeakAuras2#2524]
## Describe the bug
The expected behaviour is that the model for the subelement for every progress bar inside a group changes. Instead it produces a lua error.

**Do you have an error log of what happened?**
Lua error in question: https://pastebin.com/eXhXM73r

### To Reproduce
1. Import this aura: https://wago.io/_qetknLNA
2. Select the group
3. Attempt to "choose" a model for both bars' model subelements simultaneously

**Screenshots**
N/A

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, testing only with WeakAuras enabled.

**Which version of WeakAuras are you using?**
Version 2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Do not know

### Additional Info
N/A

**Comment by InfusOnWoW** [comment]
I can reproduce that, it's not that easy to fix as it requires a bit bigger changes and thus has to wait until the more pressing pre patch issues are fixed.
