### ISSUE TITLE
Inputting a valid texture id as a subregion model id crashes the game

### ISSUE THREAD

**Issue by BartStam** [WeakAuras/WeakAuras2#2525]
## Describe the bug
I'd expect the aura to show a placeholder model (like it does for inputting an invalid texture/model id). Like so:
![image](https://user-images.githubusercontent.com/7372712/95790311-64019e00-0cdf-11eb-93f1-0896c497b34a.png)
The above can be reproduced by inputting practically any random id (such as 0, 1, 2) for the model subregion.

Instead, it crashed the game whenever the id is valid for textures, but invalid for models (no exhaustive testing has been done, obviously):
![image](https://user-images.githubusercontent.com/7372712/95790367-84315d00-0cdf-11eb-962c-11f6dae52e6b.png)

**Do you have an error log of what happened?**

See the above image.

### To Reproduce

1. Create a progress bar aura
2. Add a model subregion
3. Input "1" as model id
4. Observe that the game does not crash, even though "1" is not a valid model id
5. Input a valid texture id (such as 424570) as model id
6. Observe that the game crashes

Alternatively:
`local frame = CreateFrame("Model"):SetModel(424570)`
or `/run CreateFrame("Model"):SetModel(424570)` if you are really lazy.

**Screenshots**
See problem description.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, testing with only WeakAuras enabled.

**Which version of WeakAuras are you using?**
Version 2.18.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Don't know

### Additional Info
I'm not sure if this is something WeakAuras could actually prevent (other than indexing all valid model ids and not calling `SetModel()` at all unless it's one of those). But I figured I'd ticket it anyway.

**Comment by InfusOnWoW** [comment]
Thanks I've reported that to Blizzard. As far as I know there's no way to actually prevent this crash.
