### ISSUE TITLE
Can't remove minimap icon with middle click

### ISSUE THREAD

**Issue by ddelk** [WeakAuras/WeakAuras2#2527]
## Describe the bug

I expected the minimap icon would disappear. My middle mouse click is tied to movement, so my toon moved. But the minimap icon stayed.

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by ddelk** [comment]
Can you just have an options menu and a checkbox for the icon (and anything else you may want)? That would be consistent with other addon behavior.

**Comment by Vardex** [comment]
Try `/wa minimap`
