### ISSUE TITLE
Text indicator bug

### ISSUE THREAD

**Issue by NotaBeneRnD** [WeakAuras/WeakAuras2#2529]
## Describe the bug
Hello i want to display amount of poison stacks enchant on my weapon and i did it befor update, but now it display nothing.

### To Reproduce

%s in text setting
Trigger - Status, Enchant on weapon, Right (or left) hand, Enchant applied.

**Screenshots**

![WoWScrnShot_101420_074753](https://user-images.githubusercontent.com/68054544/95944826-cf3b9500-0df1-11eb-8fd2-de7f3b898dc1.jpg)
![WoWScrnShot_101420_074802](https://user-images.githubusercontent.com/68054544/95944829-d06cc200-0df1-11eb-92c9-833834479a13.jpg)

**Which version of WeakAuras are you using?**

3.0.0

**Are you on World of Warcraft Classic or Retail?**

- [x] Classic
- [ ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

2.18.4-14-gf325373-classic

**Comment by InfusOnWoW** [comment]
Can you make screenshots of return values of these two commands?

* /dump GetWeaponEnchantInfo()
* /dump WeakAuras.GetMHTenchInfo()

**Comment by NotaBeneRnD** [comment]
Hello:
/dump GetWeaponEnchantInfo()
![WoWScrnShot_101520_085827](https://user-images.githubusercontent.com/68054544/96082860-b18b3000-0ec4-11eb-9dcd-03f9784135d5.jpg)
/dump WeakAuras.GetMHTenchInfo()
![WoWScrnShot_101520_085927](https://user-images.githubusercontent.com/68054544/96082881-bea81f00-0ec4-11eb-8d0b-30e9fa76135b.jpg)
Instant Poison 98 charges
![WoWScrnShot_101520_085955](https://user-images.githubusercontent.com/68054544/96083043-10e94000-0ec5-11eb-8f1a-713c898f05ab.jpg)
