### ISSUE TITLE
WA Memory leak?

### ISSUE THREAD

**Issue by ArcAIN6** [WeakAuras/WeakAuras2#2530]
Several members in our guild have been reporting a slow, but steady climb in their addon memory usage. 
After disabling almost every addon, it's clear  that weakaura is consuming an ever increasing ammount of memory. 

While this isn't a big deal for me, as i only have a couple of things in my WA, for some people who have quite a few, this could become problematic. 

I just thought it should be brought to someone's attention for further investigation. 
As i was typing this it climbed:
![image](https://user-images.githubusercontent.com/418929/95973729-0609af00-0de2-11eb-854e-5830f36b99a0.png)
to 
![image](https://user-images.githubusercontent.com/418929/95973570-d78bd400-0de1-11eb-833d-72f125355ae7.png)

👍

**Comment by InfusOnWoW** [comment]
Without your settings nor the other questions of the issue template answered, there's no way to investigate this at all.

**Comment by ArcAIN6** [comment]
I just followed the bug report link in WA.. there was no template mentioned, it just opened this. 
As for "no way to investigate" that's absurd.

**Comment by InfusOnWoW** [comment]
Right, that is a small bug that we need to fix. You should get a template of questions if you click on new issue. We need the answers to these questions to investigate.
