### ISSUE TITLE
Progress Texture with Weapon Enchant results Lua Error (this issue emerged after 14.10.2020 update)

### ISSUE THREAD

**Issue by eeGuler** [WeakAuras/WeakAuras2#2531]
**Aura Type = Progress Texture
Trigger 1 = Status > Weapon Enchant

It works with custom code (below) but fails with default/pre-defined triggers.

```
function()
    
    hasMainHandEnchant, _, _, _, hasOffHandEnchant = GetWeaponEnchantInfo()
    
    if not hasMainHandEnchant or not hasOffHandEnchant then
        
        return true
        
    end
    
end
```
Default/pre defined triggers work before 14.10.2020 update. Error message below:**

Message: ...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:1009: attempt to perform arithmetic on local 'duration' (a nil value)
Time: Wed Oct 14 14:34:49 2020
Count: 935
Stack: ...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:1009: attempt to perform arithmetic on local 'duration' (a nil value)
...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[C]: ?
...ace\AddOns\WeakAuras\RegionTypes\ProgressTexture.lua:1009: in function `TimerTick'
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:447: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:443>
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:459: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:458>

**Comment by mrbuds** [comment]
Please answer all questions from the issue template, btw 14.10.2020 is not weakauras version

**Comment by eeGuler** [comment]
> Please answer all questions from the issue template, btw 14.10.2020 is not weakauras version

ye sorry i used date :/ it should be WeakAuras-3.0.0-classic

**Comment by mrbuds** [comment]
Ho ok but please make a new ticket without deleting the issue template, you just mentioned classic but didn't say in original ticket, you didn't give an export of the faulty aura and steps to reproduce issue
