### ISSUE TITLE
Dynamic Group "Grow" does not migrate properly after updating to WA 3.0 in some cases

### ISSUE THREAD

**Issue by cont1nuity** [WeakAuras/WeakAuras2#2532]
## Describe the bug

Some dynamic groups with "Grow" set to "Centered Horizontal" are not showing as "centered":
![image](https://user-images.githubusercontent.com/10164755/95987942-6cb1bb80-0e28-11eb-91c3-5044297fbefd.png)

After switching the grow to something else and back, it is fixed:
![image](https://user-images.githubusercontent.com/10164755/95987986-818e4f00-0e28-11eb-9196-78a861e6d818.png)

### To Reproduce
Test import:
[https://wago.io/xiPH-mGg_](https://wago.io/xiPH-mGg_)

As lua table:
https://pastebin.com/hYQYg4fU

1. Import the group above
2. See non-center icons
3. Go to Group settings and switch Grow to "Left" and back to "Centered Horizontal"
4. Icons are now centered

**Screenshots**
See above

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
-

**Which version of WeakAuras are you using?**
3.0.0 for SL

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Pre-9.0

### Additional Info
I believe this is happens due to changes in alignment: `["selfPoint"] = "LEFT",` is set in the old version, whereas the fixed version shows `["selfPoint"] = "CENTER",`. 
During my tests I reverted to `["internalVersion"] = 33,` and removed `["fullCircle"] = true,` to match my old backup state.

**Comment by InfusOnWoW** [comment]
The pastebin has already expired.

**Comment by cont1nuity** [comment]
As wago is working again now, I uploaded to wago and removed the pastebin for the import string.

**Comment by InfusOnWoW** [comment]
The wago link has expired too.

**Comment by cont1nuity** [comment]
Not expired, the underscore is actually part of the URL, but GIT does not care... I updated it to a hyperlink embed in the description.

**Comment by InfusOnWoW** [comment]
I've looked in this for a bit and while I did find a small bug in how we handle the setting of selfPoint for grid layouts, it doesn't appear to be possible to create settings like that dynamic group has.

So the interesting question would be how to get the aura to be in that strange state.

**Comment by cont1nuity** [comment]
I have not found a way to reproduce this state in 3.0, the WA was quite old already and I suspect it went through some versions and changes to dynamic groups in the past.
Thank you for looking into it!
