### ISSUE TITLE
shadowlands pre-patch errors - WA 3.0.1

### ISSUE THREAD

**Issue by glofiondial** [WeakAuras/WeakAuras2#2536]
i'm fairly certain this is a me issue, and not a WA issue, but any help is appreciated.  on a clean install, no issues.  on an install where my old weakauras.lua file is used i get these 2 errors, and cannot load /wa.  thanks for any help - i just don't want to have to re-create all of the auras i had made :(

1x WeakAuras\SubRegionTypes\SubText.lua:409: attempt to call method 'AnchorSubRegion' (a nil value)
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:409: in function `UpdateAnchor'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:412: in function `modify'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:611: in function `modifyFinish'
[string "@WeakAuras\RegionTypes\Text.lua"]:278: in function `modify'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:2863: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:2758: in function <WeakAuras\WeakAuras.lua:2664>
[string "@WeakAuras\WeakAuras.lua"]:2793: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2324: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2331: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1010: in function <WeakAuras\WeakAuras.lua:982>

[string "@WeakAuras\WeakAuras-3.0.1.lua"]:1132: in function <WeakAuras\WeakAuras.lua:1083>

error 2(there's a lot more after the "locals" part, but it would be very long to add).
1x WeakAuras\RegionTypes\Icon.lua:8: attempt to call method 'AddType' (a nil value)
[string "@WeakAuras\RegionTypes\Icon.lua"]:8: in main chunk

Locals:
AddonName = "WeakAuras"
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras\WeakAuras.lua:3126
 frame_strata_types = <table> {
 }
 combat_event_type = <table> {
 }
 frameLevels = <table> {
 }

**Comment by how2pingu** [comment]
I'm having this issue as well. When I clear my WeakAura settings from the WTF folder the issue "disappears", but immediately happens when I import an aura again. Really frustrating, and makes WA unusable/near-unusable.

**Comment by glofiondial** [comment]
how2pingu - thanks for your edit - since masque was working i didn't even think of it, but updating masque worked and removed all of the above errors.  knew it had to be a me problem!

thanks everyone!
