### ISSUE TITLE
DK rune error 3.0.1

### ISSUE THREAD

**Issue by Nillx** [WeakAuras/WeakAuras2#2539]
## Describe the bug
Started getting this error after updating to 3.0.1

**Do you have an error log of what happened?**
```
1x [string "--[==[ Error in 'Rune Bar' ]==] return func..."]:10: attempt to perform arithmetic on local 'start' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:544: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:808: in function `ScanWithFakeEvent'
[string "@WeakAuras\GenericTrigger.lua"]:1092: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:1659: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:1478: in function <WeakAuras\WeakAuras.lua:1362>
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:1639: in function `Resume'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:193: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:174>
[string "=[C]"]: in function `Hide'
[string "@WeakAurasOptions\WeakAurasOptions-3.0.1.lua"]:540: in function <WeakAurasOptions\WeakAurasOptions.lua:538>
```

```
2x [string "--[==[ Error in 'Rune Bar' ]==] return func..."]:33: attempt to perform arithmetic on local 'start' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:544: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:808: in function `ScanWithFakeEvent'
[string "@WeakAuras\GenericTrigger.lua"]:1092: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:1659: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:1478: in function <WeakAuras\WeakAuras.lua:1362>
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:1639: in function `Resume'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:193: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:174>
[string "=[C]"]: in function `Hide'
[string "@WeakAurasOptions\WeakAurasOptions-3.0.1.lua"]:540: in function <WeakAurasOptions\WeakAurasOptions.lua:538>
```

```
59x [string "--[==[ Error in 'Rune Blood':'translate ani..."]:17: attempt to perform arithmetic on field 'cloneId' (a string value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\Animations.lua"]:76: in function <WeakAuras\Animations.lua:15>
```

### To Reproduce
Simply updated to 3.0.1 and started getting this error. No issues if i go back to 3.0.0

On aura show up

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.0.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
3.0.0

### Additional Info

!WA:2!TRrtZTTXvZQKMzyVeRP1XnnhwZzIcLdffjLTsIMOKHKIsIjYsmquYwXXLCbWscedIfZcqks7Xx0jFT6q)bOPtp1tA6VaFUhWOP)c8PE2)c6B3fae8ljz3pofOHK7UV3(23B33((ckXMZ3zE951F56N56Gzp9HM6Eg)UxRsz6ewjS2t1zuNs7sTjS(71QLlX7RtCAlQT3Mw42US9oO(ov3TYzADD9ODQt671)9E)wDT18mP2PxmjcEmBHWDz4ge7EiSTEuNSUEypcYZGylWJ)yr1WwigA9HyXiTbAnggUXXqqNXqahdHXa5z2Haq3I4vhAfWKbmQn1dXYQr7A7nkJXFcbSo0sfZwRmJal8MWMX(Emt72PTnTYGsT3Hvu2P4rPwCAtET9jEFhSzz2AW2PXz)5GMxfUhoe3dNjU1OM2EaIouxt((FgjFMbfFiCwxdmt)rrToAM0JlzPzz9Gt112kO7IZeB(HFzQfLfBkdhBwZZGECStaITEY3Eg5DHjIPuk1FYs67yYW8njUAbAjPEYxVok3m1ecxX0PIDytSCjxBQJwrqCe6sjVRq9kBlkRdgwSpnB(wPYCTwHfhLVU0vbOTr2wwuyJ6TL0bhBWVOK8oWdBG0CX)iX5yBndktODQwUYU1RO8kHTgjcpkHShNh6YioPRA7ryTWAKFQmg04TBxcZ(PdQU0WElTpFcxiMMc1tWzjCU5i9FavNuQ4b13RqxMLZNy4554U2YlFmUnnRjD5TZJTgOQF4pSC(8Lm1O2gNaBYTBtyU)XfybnF5V91DDjnWQUuMkNGnVOnbSeAQX1B3Z(vUIFkcw76rk1120t1XcpGWo1HEmH5nWH87VGtHOUgNlTu2WWuNOW3g1lXhxvo8zCKniylpJim5GpxCo01rh((1UDvj9iGrNUTAz2)8gLlUF9g7xVOsDfX4k14RgRRTOxjCxpQ)D6)RxlYSm2YAFo9CZGeOKbLnBw5PzeiU5ZO2ug65Vi0wUykO1xhLs5GDR0O2EpSIsJdQTrX6vsn6nfqFfzcekFMvr60r09cSI7HzWQR3vQCb2RaMwHG1hiTpRaDltPw60JTtBoQfKiU7XMpbW(5JaK)OzGTBt0byESUKmtaNF2ntGomABgX1ToS5diLsCsLAs8g7MX6src95dLPjMsiea5zJKPToPpGH5iqEXunu6HvTizbvuV4NSdpTZOU4K0hmqn(1AUVz1XhCctFrwpiWTv7jPYxpbnMCtBClrJrt(rYKtkMedThksjJz0DOUznWdmOxkS2uD3TA8W9u2zJuCn5jWz)AvkxT4ov)XI1RU3UnkVDXD3QYgJPlp0IOdrJFotSiAEPlKHRNUpmMj2Y8zczUQDlA6jgfC(mgppczlQZDVxNYNu6rwSf)L7t)Y9P)pDFkCW4teg7eqp0YQQUBsPNhxNnV07ozMWZqg0uVqg5lRgJa(YuaYTZokAgeTN6)zNWDgYDQ2uXg3H4M8mDIk4ZJRdX2UYo128GDofcGr6Ro5c(36V6Ju5Ek76(k(CnT1ODuXEn9)u)f8)OM(F2zLP26IaHD9l00)J9)d(l7N7Kq9M5Z7VO)D9xn556MU)S4aVhPa2EGZnXI21LRfpuG5oJh1qdnEGLF3CWZBm5XTyJToeIHai23Fb45fI7zphX6L8uSTzhXYSQIqREtFujBiXQxrWUeidcIDBpJp4IqMr44N5sGvr39eooCb3VCPoyt7xEBvXkRmNFf)nLTlnN83TMt1fSgq6h0V4CIyq8yyBxlqzUP)gFWP8reyz4J8VJCcdMZFl)YxeH4MWoq)5(lrA(HxIZiVv(OGFpcS4qS8Wpk43JExt7lc9PK6w8iQ7GT7YZJBIOYdUcfIxyspUpoAinlydVQ(tY2pZ1dVbZo(54See1hTR0RIkTFQPFnxkL9WwD5w2wk94R2s5x8UPhlVxEcmBtmBBaz885rWG4F1GqHxK7pl3LTopcwOCt1A1yRn6BcsfzQgsUeE(EVT88SxaoZIMgXefL4ArR4w1gtTqUezK)M8kTFEfNEx7dVzY7t)SloZMzm4JzYoYIn8rCFwCBVPc2YXaNy((jMFqItfJjmCCNtfxYJ3wCbprIRXfCb6pk43jVGhPfbxaYZfSPby1r1VwAjhMOEfZCplwg(YDL8qGarmj6UO0R8vlVYxc78lMbLp5ehLHZkcOCVk5epYDj5UXFEk7gmGeTHpQWhm8HbH91g(OcFWf(FH5UROsvsWoXlcwniwfsSYGDLLG4BKKFwwrDYQqGq(yTjzzzI3R9i9uVK6lesOnPWrlJ21wxsQy9BpwF1zPGRY451tsm07Kur2FT5ZP2Y0201a8N6xg8TX9iYDK9g1GYxw1Etg12ZW5dhwMYde5sRktP(evmRS0r(2FRFnXtuJ5ETRNP2thSrGFzdgwOF4UQFPf8VZV6uDAdjDnkb8Hhmw)FZnMWZakvlGRtLCPLqbreGWmsWO8RmshhPHVxdvO)kqeNaK1qW1heJE8Ijh3936Owy(woqq4ONESlcwiKhni1euKxnKCcwdsosEfCbUlZniKDoz4hxqY(2iroo8VmBzQH0KiMuQ0vYIs1Jsqy4rhIlILVx(nxPuqC98QhhadaLl39(IC5cafQ(iM0xMJ)ha5fblbCA56nRLOG2xP2Q1uxIicD1lXb2guRbZAnYLJC)iEDmXyL7FVCRCfRX42655SX3G3gYqQtxndyVfRrqQeVJjey7MxgwxuSJNWk0oYahX9LZ9jaucaEeI2IF7fXRZj)uJ3guKhsMWIllozebElu)ckP8W5cbPA(m4cIqhbqie5mOu7uzZ6PqlGsPuDRTRNAcAFiN2pO6gBStLPt7EegC7jIYbOcuU(E1eeU0E1RV3dIr5q92X4AofLfse0Sb)gXLEbP5emtiJgrx(sieI1eyRr4bPVKGcUHKamYd66847rUM6e3SH0tsljZkisMq6gTVi7krCn4QcZgIzFiH18GKMHSjJVTgNtgvwIWhn52HBKY6JZlsqNNo7s5lC)mi(DLCOxi1jFCHHq)IjaUYqGtoZ7fbCsy3pc2KeD1iyJYoVaK6LqBqT)mpuDkxVh6Nm0)6mQ9XWsEiVPgH(2K(1PkBvQgHPL2G0FCVHYIKdlp1UBhvctu8GrhA8xZeqfWrU4Bvdr9bcQ0oKwAAXWGZ(clMzIHbRZ3Bkddc)QtPipbocFoNLczL0Yfp)QlUCH7dZRDCyThfMACyQXH9IrYAp5OHg88udnRj0CJmKjUNey7kLKgHL1AKAwfgyJ41InvNhJe9quJ4U052gh5OtyDpgclgBAXS1o9PneH4tlUD4PmPqWtPMHtY7G4oLA3jdSDIyLUubv4PCQc6vkSYPonH9key5eNuGdQp6mKScVLs2Spc)p4y8D8O8YLSvElLmzCbVBIwWCFhKTGzofHlwgFtwZ4Gq(bQ5mIDGPIah4)DkIDYRtrR91B6)eE4X(6gXFBFhL4mWCPIivp37ElF0585bHT0a(07c5)3bnOcCNlSR0VFbaJZdgX18zK5Evqhzn4sKiXCb)Fl0ONPRPQfPzi6e92ewEunZ(elF0Pahibagt5LPO27LpF27Riytd4kew)LZlFVDepvSNNfXqKGn)nQXmu0SWUUlO6AYDvF(gvkwF7VFxEeakD6A5zMuMmohPMLGKfi3Y)5jffZKVZ0SeN35dXGaUGGakWB)Ab6GGQlqkPQegh058z2JyyQbSrjo0f8h8baGZ0nBbXNdl5ab5AjZlH3UeJAjxdGhbDrhE7tD65mKSxeJShyA8AHWxcGQZRUzHIBSXfH5pvoA)9uqJPL4f5wIhb0zqWsypEEredr2ws9(i83(B)x3(VL7g34gSEYAI(roFiSSs1gIor)b4(gmVGx87nlbQzpdc0fPGn1H4UzJJTPTXzYQeiQbCGMtGwsqwEnlbmLMtj5)Cg6i1bOQoGHEqQGSzKdSt3(Egu3KjJERWhFCwVJn90mY61Bzlj4tff4LhrOIi(ovOBlZ2jpxSvjlW16o3uQCUjd3HudYOJNN5TnBBdwqcYZRcVa3vymkZTPZhgdDXxV5He8tlcsI7A8xpJBPNrPDsO6s6a7zk5ZwiB(Z8OAbBG3orJ)ukt9t4OY3HEtmYX3tu3VSsLk76xFoLJ5frP85T4G2hYA2d)(Y)fFkhvYAq7Gtxst)728CijaGpfxZpB79uQ(J7TB9I7CMwufZ)4f8ZVQ)T(KBCspmZK)ssojSc7kI6vLGjFhrCm)71Mlx2voXbuF4V5B)6b7AM66eBLDRCyfLcDn1pFWpC)6v)HJEynt95DvwjBUS5MV3)8r)7d

**Comment by Nillx** [comment]
Nvm i started getting this error with 3.0.0 too.

**Comment by mrbuds** [comment]
This is not a bug in weakauras but in custom code, so we can't fix it for you.
I can give you an hint and add a nil check on the value of the variable start before adding values to allStates table.
If you are not the author, please contact author.

**Comment by Nillx** [comment]
Yea i thought so. Im not the author and i will check for newer version. Sorry for bothering you.
