### ISSUE TITLE
Require Valid Target not working.

### ISSUE THREAD

**Issue by Zegnautus** [WeakAuras/WeakAuras2#2540]
Trigger > Status > Action Usable > Require Valid Target appears to be broken now. I did not make any changes between 8.3.7 and 9.0.1, just logged in after the update to find that my Fire Blast charges were no longer appearing when I target an enemy.

Here is the code from my Aura.

{
    ["user_y"] = 0,
    ["user_x"] = 0,
    ["parent"] = "Fire Procs",
    ["yOffset"] = 130,
    ["foregroundColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["desaturateBackground"] = true,
    ["sameTexture"] = true,
    ["backgroundTexture"] = "Textures\\\\SpellActivationOverlays\\\\Eclipse_Sun",
    ["desaturateForeground"] = false,
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["names"] = {
                    [1] = "Fire Blast",
                },
                ["duration"] = "1",
                ["unit"] = "player",
                ["use_charges"] = true,
                ["useCount"] = true,
                ["use_absorbMode"] = true,
                ["spellName"] = 108853,
                ["charges"] = "1",
                ["spellIds"] = {
                },
                ["debuffType"] = "HELPFUL",
                ["charges_operator"] = ">=",
                ["type"] = "status",
                ["use_targetRequired"] = true,
                ["subeventSuffix"] = "_CAST_START",
                ["ownOnly"] = true,
                ["countOperator"] = ">=",
                ["event"] = "Action Usable",
                ["use_exact_spellName"] = true,
                ["realSpellName"] = 108853,
                ["use_spellName"] = true,
                ["count"] = "1",
                ["unevent"] = "auto",
                ["buffShowOn"] = "showOnActive",
                ["use_unit"] = true,
                ["subeventPrefix"] = "SPELL",
                ["use_inverse"] = false,
            },
            ["untrigger"] = {
                ["unit"] = "player",
            },
        },
        ["disjunctive"] = "any",
        ["activeTriggerMode"] = -10,
    },
    ["endAngle"] = 360,
    ["internalVersion"] = 37,
    ["selfPoint"] = "CENTER",
    ["xOffset"] = -40,
    ["anchorPoint"] = "CENTER",
    ["texture"] = "457658",
    ["desaturate"] = false,
    ["rotation"] = 0,
    ["font"] = "Friz Quadrata TT",
    ["version"] = 2,
    ["backgroundColor"] = {
        [1] = 0.5,
        [2] = 0.5,
        [3] = 0.5,
        [4] = 0.5,
    },
    ["height"] = 30,
    ["rotate"] = false,
    ["crop_y"] = 1.69,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeStrength"] = 3,
            ["easeType"] = "none",
        },
        ["main"] = {
            ["type"] = "preset",
            ["easeType"] = "none",
            ["duration_type"] = "seconds",
            ["preset"] = "pulse",
            ["easeStrength"] = 3,
        },
        ["finish"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
            ["easeStrength"] = 3,
            ["easeType"] = "none",
        },
    },
    ["useAdjustededMax"] = false,
    ["fontSize"] = 12,
    ["authorOptions"] = {
    },
    ["foregroundTexture"] = "Textures\\\\SpellActivationOverlays\\\\Impact",
    ["conditions"] = {
    },
    ["stickyDuration"] = false,
    ["mirror"] = false,
    ["useAdjustededMin"] = false,
    ["crop"] = 0.41,
    ["discrete_rotation"] = 0,
    ["blendMode"] = "BLEND",
    ["load"] = {
        ["ingroup"] = {
            ["multi"] = {
            },
        },
        ["talent2"] = {
            ["multi"] = {
            },
        },
        ["use_never"] = false,
        ["talent"] = {
            ["multi"] = {
            },
        },
        ["use_vehicle"] = false,
        ["spec"] = {
            ["single"] = 2,
            ["multi"] = {
                [3] = true,
            },
        },
        ["class"] = {
            ["single"] = "MAGE",
            ["multi"] = {
            },
        },
        ["role"] = {
            ["multi"] = {
            },
        },
        ["use_class"] = true,
        ["race"] = {
            ["multi"] = {
            },
        },
        ["pvptalent"] = {
            ["multi"] = {
            },
        },
        ["use_spec"] = true,
        ["faction"] = {
            ["multi"] = {
            },
        },
        ["difficulty"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["textureWrapMode"] = "CLAMP",
    ["slantMode"] = "INSIDE",
    ["ignoreOptionsEventErrors"] = true,
    ["startAngle"] = 0,
    ["config"] = {
    },
    ["actions"] = {
        ["start"] = {
            ["do_sound"] = false,
            ["sound"] = "Sound\\\\Spells\\\\SimonGame_Visual_GameStart.wav",
            ["sound_channel"] = "Master",
        },
        ["finish"] = {
            ["do_glow"] = false,
            ["glow_frame"] = "BT4Button2",
            ["do_sound"] = false,
            ["do_custom"] = false,
            ["glow_action"] = "show",
            ["sound"] = "Interface\\\\Addons\\\\WeakAuras\\\\PowerAurasMedia\\\\Sounds\\\\splash.ogg",
            ["sound_channel"] = "SFX",
        },
        ["init"] = {
        },
    },
    ["compress"] = false,
    ["id"] = "Fire Blast 1",
    ["regionType"] = "texture",
    ["alpha"] = 1,
    ["width"] = 35,
    ["anchorFrameType"] = "SCREEN",
    ["uid"] = "Cz)8(Uc23b3",
    ["inverse"] = true,
    ["frameStrata"] = 1,
    ["orientation"] = "HORIZONTAL",
    ["crop_x"] = 0.68,
    ["color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 0.75,
    },
    ["backgroundOffset"] = 0,
}

**Comment by mrbuds** [comment]
- Can you export string instead of lua code ? We can't import lua tables.
- Is it working if you uncheck "require valid target" ? My own tests with it show it's working fine.
- Fireblast may have a new spellid with 9.1 (i have not checked) you may have to update it.

**Comment by InfusOnWoW** [comment]
I just created a Action Usable aura for Fire Blast and it works correctly even if "Require Valid Target" is selected. So we really need your aura to figure out why it doesn't work for you.

**Comment by Zegnautus** [comment]
> * Can you export string instead of lua code ? We can't import lua tables.

Oh sorry about that, I figured it was safer using lua code since it's readable without importing a stranger's string code. I didn't realize it can't import lua. I pasted it below.

> * Is it working if you uncheck "require valid target" ? My own tests with it show it's working fine.

It works, but it's always on my screen. I like to only have it show when I have an enemy target selected.

> * Fireblast may have a new spellid with 9.1 (i have not checked) you may have to update it.

Actually so, I don't know what's going on here but I just unchecked Exact Spell Match, and now it's working.
The SpellID is 108853 according to the tooltip, and that was what it defaults to when I enter the name "Fire Blast" into the Spell Field.
What's even stranger is that if I uncheck Require Valid Target, then it still works with Exact SpellID, but as soon as I turn on Valid Target, it won't work. Not sure why it's being so picky, but hey, it works now. I should have tried that sooner.


Here's the code if you still want to look at it.


!WA:2!fwvZoUrrqymorbTsG21GwfYjRiuaeiR4n76SHKaYJJ9Mf8ABMX5hHS04EMPT7o74UB6UhV25OfseeCb)i4BiXj)iKNGrw8eKhH9aNP6E8Uokx4I7E6UQV(RQ6RkNRrHrfIke9QddsuyP)0CzRtY5gYJ5YVpF(8DUYTlD3dKtBpyGcR)Sp48bCjEOKNWIQDHn5fFsewH0jsKg7Gcpn7((l08WXyPIYzxpN)FUuHgH7INa2H7)2U04sijZ0s6WHGpTULC92xDJLaR8dji5qSQVtcJQdeXOPyP9ckZ8gyYm4JAai6(VrLeGhJz6os8a6exVo1B20CTVX3(lIWbjdg0DQalFC9MDA8KMx6HhCbDYs)Av96671TQBxivaywO8cJpEe(zTzVwzxQgQPJXITxZmFoGhsZL38BFOC9zfkltywGDqjAUOGHeAZvAx8pNqL4O(oAGibknKmuUwBxzqMZk(efkigVYsG2Bax8XguWtqHAFLahh3cYR9xjXOyVl(865(RdwzmBJbZSBposTLKFgRnlEA)3ySafO4YGt4r4(UmWq1nw0aiwrNyKspx92iolYuVaQvO8CGtz1NDt)W0pAzev9IeMnJShInvSdYUVBMng0)73BgMfvLnmg)l7EoLPXsgk(Pz6JFyUchpOdhooOw9wDR7ohXOJSpwfxi5i1nwDXR7BYyqjpKZIuPfDyCg(1yKc7PLy2qn5AZmFzkWP33zeIYEAAXaHedk40hME)07L(nPp4APFNRijwHdgqzufPH94IW1WvGvRGkgHlBlmpPARGqjx4pX0pu5W3O00WtN(O1eIi2bI)qjwJ9LCT9SCod4mTy7gs6ll(JjOiWuuXUDLR7iU6seleW3gZPvciy6qI(Hbw)XeNyok6FLAumii2Bx3rjXA6wZnfmJGsscYUA30wBzBdgJj0WymXneQBQBfOOMmTZjvpQoyIduhdVvQ3vtBT716BHXAh0mqbfFiG(uduosuioBdp2UroazvJM9ZwROc7pxmwSHas4TG(xH1rf9Lwhpp4Yjbztk6K)2Lo4D(rSnaz1OxKO04iC0jOjKZ1zJiEMejm6g3AnREsNfwnGv9KBVeA0YAV8lp8lEs4E3j4oUOybbLpyevk5sY7IjLrwadyGyW2YVg(ZZs)nKMHsMoqVAU1R3Ao0XXISVRtZ6TEuwzFANRuUuL7n7YI7CvmIPnMfCClVJFuDX1PdzWCS1YL6M(46g6O6N(IG9p4Uvo4qXoBgEUEoO4ZxVr1Z27ANPyFI2qrggYP6D8ibubCm8Wi(2VSCs2W4)49NfYhzK1kYnPrVEtxBXYZmIppOs8PlhyIqOZaKF5DpJgPjhj2ztT5cI81)VePEymvacaVewa06nGo0u4TdFnZuVyAozjxsHO368Ih3294FQDRUvBUW0UsZAMKzAkvL0dRSszOHz(oJHJdob4pw6Apu8vEMLmgbeJoIZocIg)NsvjOy)JSrgOlkDgA8SiUV1lId0pR3kT6yjC0Wy(zK0FNSWSX3Mmw40DFNeTMZ2l93ep4yZOiqLJ7vnkcivVNHrNwfIfvVo8ZWs72tWruuplDu9uWF)OiL4dhU0IAw04y(BH5Wtgckp(is6VUNxJNl2EtUoRULRGY9oLUDPYfg)pp))c

**Comment by jonbca** [comment]
I appear to be having the same problem with this aura:

```
!WA:2!DnvZUTTrq4k4c4c2EiwijWiaP1nfiWNm8pOohliLLQuJKfbfJDrGbKwYDi5ctTl7SlTS6rHEixRqFceqV1t6rOOpalek6HE0pc(jO7s6KIwEG7WLZ(nF738nn60CAtAt67(I7vWTQseUejfdeuO4XT67oWpCOxF3wV29SZ6f27I2RuI4BauYe8DBm(NpUKrx31Tv4Ls)(xuCYgsPktGdluMeKolqHIydBenLHOaZW5dtsKG6p(K1eESjvFbJRIA1(8W2bbXICb(DB19B(73w90W)Jp8Gx91lJYbo1sQJn8yfcPgidNxa4dCgVTg1gRIfCkRU4ijUk40aPIGkNOegNjZC8mlkNfkKLMAUjF(lXhcF3oljLiHtMcYNv8i)smf2tLb7Djl(AGIIz8H885twukHXLgqMSIcrLjjvuPRBWGoVPpA(55geMCVnR6)3kNiLzyjhUb4kpJgjcQcJ6cKCvwqvjDUtwgvTTpcjSBdg53UFFpLb8alVoEHSaYZ7rLoBMsuXzGCuMy2q(gz1YaMuY4P3zRljskWiRInXZY0iJcKcQfudowrP5rFOyJmeKD76XTChfoEuOBq4Ys(dkIZl17(x69JmcOQuw00cDnsbWpuYqGorFyZJ2KcCazX105UA60siYPgjtFqurozoGBqZLDK9ky1h9Z2yrt((VNS8dH7U1Z)v9xQFrXo2m(pypr)vBCRAR79gjXylwwrjtR(6j6NJDB3330d0N4uSJT7FdewFrSkXV9r6hvCApUcWesmCLlLAChxDjqU21ilYR8fZaSkCaqzKRQ31((v3ZShJtYVO27)6asErgzRLeoBALIEQ(XxO33Jl4WcGibRNq3EZ7f8X22ikbR)u(72egPqGNQY2oQabJ3DDKOKhdNbXK5EtjmEhDVT17RBR)wDxDhZ6t()78cgDHVA2EwkUuc5jvdt6pDDcAKrtbikYwgpQ009mXqwXouMmgbfm(FNmnukHL6CF98yh7rTKpAuRG2TpFLXNeunWjDIYawAM6N(SOQtB8w5cc9uptNl(PbtlZvmNGyRz)P6364jz)iydcMXOQSF5jnLbNCWHhCuZB(ZV)Fo
```

**Comment by InfusOnWoW** [comment]
The reason for that is the "Exact Spell Id" checkbox.

I need to investigate why that makes a difference, but disabling that checkbox should fix the problem for you.

**Comment by lassevk** [comment]
Where is this "Exact Spell Id" checkbox located?

I have the same problem with one of my auras, and the checkbox for Exact Spell Match is not checked for the trigger that is failing. But, it has a different name, you say "Exact Spell Id", mine is named "Exact Spell Match", so perhaps it's not the same checkbox?

Anyway, mine is for Demon Hunter, Fracture skill. The skill is usable, but if I reduce the triggers down to just the Action Usable one, it only shows up if I uncheck Require valid target.

`!WA:2!Dz1tVnXruCLAIqyOTjBcqkurDdLOKEiQjKqVahYgSbADInRDkGqiVZU74Dhy9mBNzwNeUHvBvUvvFOFaS6NaFQNZHEEKvvp0J(q)aKpb9nZU2nuFi78EZBM3737p)MmtfRowbwbNCB(X1A3wGLZmer9Jy86mcv6TB59Bw2zKpJfhWoK24qsc290jILdcXrCKVKWOI75iKiUSOnHsKf9AdFerf7j5KWqmx87ZwyfEUWjZpovGBH8emU3ESaS7yrQhUlMkRZXTjh50OE5Qv7lsWXX7J6Gx6cZ(32YJtWEGpKPcEk1yTnkvYStbh6LeJogZtS0xmehHyPd(7tjCCGRJX2r7yIZshiqEX4Kf0gIpcc(wtDt0iogf3yIyVkASLYXJ02o1k3EMLpjquSNEdT7)pa0iTnaGHT2DNgnB1O5oonDOWHaBds5iDeyTXGaShywtaq8hxUA9khuTFknp5uCf1Lp5QosW3VrTqY8AxeIPyoXVre7WAu3rVN4yH5ZU51e1TChAcxqBOFGR6J1jphti3RcKp8qXXQR4QSul0FkUCvlBTH66jFYKRPuDolKJfIsRAYhRPwuD1E(iHuh126fQp1v9zQsNQVKjB4QMtnV6gQBAUAdgCvFO6Ju35AQvvRbq7pmwaNlZJdDq0qCPDJWaAx0lVYX1kT2EAmAKD1r9TChBeAXGChsY4lF)hmXblQ2s7aoCctDsF0gsieeMaDuhK0pclYsBJYsB7LPtDDVhdLEzK(U0nzWHS2snNdckABQXEF9ktL8gJBWsJlbnhHDGcUyCM51oxaDB1xOUJUq(ptq74e2Hy(0O26(zW3PUwTbaxXTVXgDB(TDmlx(R3w7Aa0MSGrN7OPlLMeoKJaFnmGiEDkfAX7I98tfswNeRSVnZ6RQYcj(jVOTXigD182T1kwc(XXqFoTuUUxUXRkHObtfVBM4KJ8YTEvjgF6UB)Q1kIPbjZJmEp3D6X6zpd4qWCkk(7agaWPF7zVbJt2bA58Lo6HHO(ikPJzS4EQlwrnNnLrXJMmQ0sdrUa7ZObItXiD9KJPHYOl2tlPB5u1T7Giu4SQ6QNQCunUOQjS8s)FnWuNaipGBghnagxDWHAERV8KfsSK4JaEGie06)8CEW(gD6)yTrYCNZGDzXm(3mZmZuyCMwCCBdBP9oh0SwYcgLAIjnU8FgjqgzVdiEMzdGCahyu(UrzmTVi3HNA2)1qnJ0(yvHbCgW1HBckT3V2(LvZXHGwBZaJH(MWOa8llsBZOYK5QWjVT0ttrbamrLA289G2epnYO7qgp4zCusVNLVila6seeGG0nhZN71GtRDa8yql7AnBwBVrtDAdYBXFEowE(75b9Ugso4GvFY(L)RrHXSdRWbIzm1)46x4RwFZTZWLEdntYJIZtWr90Q0NEKxQuYO16I5ah)aT6QMEGRouVEcO6ho5OMKIzVjHJTwiY49Mre)3qbITcMd0WhfJZwwLaQN3C)2qgbZJ8IWKWi57SJzOGFnBWdl9qszmoYWY2fdxhiyRBPxXtqOHX4zD6KgljxB2SXw)yKqKn2MB(bKOE5uV(Udm2W6axRRJX2vu)4WhwEVA7)4d0V(Q(PI2cihFnyXaUPP1WbtGPcNZ1fmTpuvq9ZUAcb9BIpbSAPpW6hswIeszCCTeZR1L1VvvMZzCHBYItEqx3S9qI5bYGi73YyDMrTG7ajZVB2a8sZ06xwMeOUPhCTTjHfh2MdCIWuj0Uv4SSMGkAv6q0RXUoLlVVdkojcvyZusWWAqoTPZJwn5fhWju9Tc)hehLxMCo0mxmqpUtmH5nwXXx)0qf1LVuVUiorhAQh40ffNIT2AzwI195(r6xeaBv)MBVeUMJvESEcF9nxxxn7nbEUJGXsiaZZbfTeo3DDOh0Q7F(8)9p`

**Comment by InfusOnWoW** [comment]
This is a bug in the library we are using. It essentially ignores spells on the spec specific spell book page.

I've created a pull request upstream that fixes the bug.

https://github.com/ascott18/LibSpellRange-1.0/pull/1
