### ISSUE TITLE
Duration related conditions not working for TSU

### ISSUE THREAD

**Issue by BillWiegert** [WeakAuras/WeakAuras2#2541]
## Describe the bug
Conditions that depend on the remaining duration of a TSU trigger do not function properly. They seem to only update if the condition is true and the trigger is updated.

### To Reproduce
I made [this WeakAura](https://wago.io/szMhppGq_) to demonstrate the issue. It shows a progress bar for four seconds after any spell you cast. The condition should make the bar turn from green to red when the remaining duration is less than 2 seconds, but it only updates when you update the trigger by casting another spell or when another state expires.

1. Make a TSU with a timed duration that doesn't return true every frame (trigger update will update the condition)
2. Add `expirationTime = true` to the custom variables
3. Add a condition that changes something when the remaining duration is less than some amount
4. Test the WeakAura and notice that the condition does not take effect when it should, if at all.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.0 & 3.0.1

**Are you on World of Warcraft Classic or Retail?**
- [x] Retail (9.0.1)
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
I'm sure it was, but I can't say for sure when. I've only tried to add this condition with the latest version.
Edit: Tested and working as intended on the beta4 version

**Comment by mrbuds** [comment]
I can replicate with current mater branch
Did not have this issue with shadowlands branch with last commit 3f1a21ae630dafb017c7a40cec931a8ec31536fb  Fix BarModels sometimes being incorrectly clipped

**Comment by mrbuds** [comment]
In `WeakAuras.scheduleConditionCheck` `if (region and region.toShow) then` is always false with TSU, work as intended with an event trigger
