### ISSUE TITLE
Couple of errors left after patching from last update.

### ISSUE THREAD

**Issue by Stravides** [WeakAuras/WeakAuras2#2542]
Very little in the way of WA on this character but these are the only 2 errors after removing most of the other addons.

ERROR 1
======
Message: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:8: attempt to call method 'AddType' (a nil value)
Time: Thu Oct 15 09:41:10 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:8: attempt to call method 'AddType' (a nil value)
[string "=[C]"]: in function `AddType'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:8: in main chunk

Locals: 

ERROR 2
======
Message: Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua:327: attempt to call method 'AnchorSubRegion' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua"]:327: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:611: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Text.lua"]:278: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2863: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2758: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2664>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2793: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2324: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2331: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1010: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:982>

Time: Thu Oct 15 09:41:15 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua:327: attempt to call method 'AnchorSubRegion' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Glow.lua"]:327: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:611: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Text.lua"]:278: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2863: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2758: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2664>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2793: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2324: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2331: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1010: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:982>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1058: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1132: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1083>

Locals: <none>

**Comment by InfusOnWoW** [comment]
That error points to a very outdated version of Masque. That was added to Masque roughly half a year ago.
