### ISSUE TITLE
Implementation of a hierarchy system.

### ISSUE THREAD

**Issue by Lame-One** [WeakAuras/WeakAuras2#2548]
Currently, a large issue with managing larger amounts of weakauras is the lack of comprehensive organizational tools.  This is especially prevalent when playing multiple roles for multiple classes.  A straightforward, although potentially not simple, solution would be to implement a more in-depth hierarchy system, with a "parent" aura (or group) containing any number of children, which may have children of their own.  The key differences between this system and the current implementation would be

1. The ability for more than 2 levels of organization. Currently every group can have 1 level of aura's below it, and no more. The ability to have "Druid" as a group, overseeing "Restoration" and potentially further "PVP" would allow for a much more understandable modular approach. While this is possible in the current weakauras, doing so would require PVE/PVP for every spec for every class, which would end up being a LOT of groups, all on the same level, with no structure overseeing them. This also goes hand in hand with the next point.

2. The ability to apply simple triggers and conditionals on the parent that could be inherited by the below groups. At the moment, a group is an abstract collection of the below values as opposed to it's own, independent object.   There does seem to be some level of inheritance at the moment, but at the same time, navigating to a group itself displays a hodgepodge of values for all of the auras contained within it, in a manner that is, in my experience, not terribly useful. I'm sure that some are able to utilize it, but I believe that it would be working around the system as opposed to with it.

There are plenty of alternatives that would solve the above problem, such as a more graphical tree approach, or even using a windows explorer view, but those would be a much more drastic change in terms of UX, whereas my proposed solution would be nothing more than the combination of being able to drag one group into another, and the group interface displaying the shared properties of all sub-groups/auras as opposed to individual ones.  With proper planning, this should also be fully capable of being backwards compatible, further minimizing the impact to users.

I'm aware that this is a duplicate of #98, but in addition to being 4 years old, that links to an issue on a no longer active tracking board, so any discussion as far as I know has been lost.

While I don't necessarily think that this would be a quick and easy fix, I do think that this improvement would positively impact all levels of users, from casual "let me just import my class and be done with it" to powerusers managing multiple different "collections" and subsets between raiding, pvp, and different roles.  The simple ability to drop a new spell in my resto druid "spells that buff" folder, which suddenly imports all the appropriate glows and conditions, requiring only that I set up my triggers, would be a very noticeable increase in usability.

**Comment by InfusOnWoW** [comment]
That's something that we are well aware, but it's rather close to being impossible.
