### ISSUE TITLE
WorldMapFrame taint caused by WeakAuras

### ISSUE THREAD

**Issue by StanDude** [WeakAuras/WeakAuras2#255]
What steps will reproduce the problem?

Hard to say, have not been able to safely reproduce this. Just now this occured while at the beginning of the Surama questline where you fight Oculeth's former apprentice and he teleports you into the Drift (with the weird gravity and stuff)

What is the expected output? What do you see instead?

No difference in gameplay whatsoever, yet a taint being caused

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

Yes.

What version of WeakAuras are you using?

2.4.15

Was it working in a previous version? If yes, which was the last good one?

I got the same taint.log in the previous version. Did not report there because i was gonna wait for the update, however this apparently has not been fixed.

**Error Log** 

7/23 08:34:47.323  Interface\FrameXML\WorldMapFrame.lua:275 WorldMapFrame_InWindowedMode()
7/23 08:34:47.323  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:Hide()
7/23 08:34:47.323      Interface\FrameXML\WorldMapActionButton.lua:58 <unnamed>:Clear()
7/23 08:34:47.323      Interface\FrameXML\WorldMapActionButton.lua:67 <unnamed>:Refresh()
7/23 08:34:47.323      Interface\FrameXML\WorldMapActionButton.lua:19 <unnamed>:SetMapAreaID()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1341 WorldMapFrame_Update()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:2873 WorldMapFrame_UpdateMap()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:451
7/23 08:34:47.323      SetMapToCurrentZone()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:381
7/23 08:34:47.323      WorldMapFrame:Show()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2374 <unnamed>:SetUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2213 <unnamed>:ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2133
7/23 08:34:47.323      <unnamed>:SetAttribute()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2915 ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2899 ToggleFrame()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:263 ToggleWorldMap()
7/23 08:34:47.323      TOGGLEWORLDMAP:1
7/23 08:34:47.323  Interface\FrameXML\WorldMapFrame.lua:275 WorldMapFrame_InWindowedMode()
7/23 08:34:47.323  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:ClearAllPoints()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1536 WorldMapFrame_SetOverlayLocation()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1559 WorldMapFrame_UpdateOverlayLocations()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1342 WorldMapFrame_Update()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:2873 WorldMapFrame_UpdateMap()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:451
7/23 08:34:47.323      SetMapToCurrentZone()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:381
7/23 08:34:47.323      WorldMapFrame:Show()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2374 <unnamed>:SetUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2213 <unnamed>:ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2133
7/23 08:34:47.323      <unnamed>:SetAttribute()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2915 ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2899 ToggleFrame()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:263 ToggleWorldMap()
7/23 08:34:47.323      TOGGLEWORLDMAP:1
7/23 08:34:47.323  Interface\FrameXML\WorldMapFrame.lua:275 WorldMapFrame_InWindowedMode()
7/23 08:34:47.323  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:SetPoint()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1538 WorldMapFrame_SetOverlayLocation()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1559 WorldMapFrame_UpdateOverlayLocations()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1342 WorldMapFrame_Update()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:2873 WorldMapFrame_UpdateMap()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:451
7/23 08:34:47.323      SetMapToCurrentZone()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:381
7/23 08:34:47.323      WorldMapFrame:Show()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2374 <unnamed>:SetUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2213 <unnamed>:ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2133
7/23 08:34:47.323      <unnamed>:SetAttribute()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2915 ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2899 ToggleFrame()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:263 ToggleWorldMap()
7/23 08:34:47.323      TOGGLEWORLDMAP:1
7/23 08:34:47.323  Interface\FrameXML\WorldMapFrame.lua:275 WorldMapFrame_InWindowedMode()
7/23 08:34:47.323  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:Hide()
7/23 08:34:47.323      Interface\FrameXML\WorldMapActionButton.lua:58 <unnamed>:Clear()
7/23 08:34:47.323      Interface\FrameXML\WorldMapActionButton.lua:73 <unnamed>:Refresh()
7/23 08:34:47.323      Interface\FrameXML\WorldMapActionButton.lua:26 <unnamed>:SetHasWorldQuests()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1020 WorldMap_UpdateQuestBonusObjectives()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1343 WorldMapFrame_Update()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:2873 WorldMapFrame_UpdateMap()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:451
7/23 08:34:47.323      SetMapToCurrentZone()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:381
7/23 08:34:47.323      WorldMapFrame:Show()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2374 <unnamed>:SetUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2213 <unnamed>:ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2133
7/23 08:34:47.323      <unnamed>:SetAttribute()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2915 ShowUIPanel()
7/23 08:34:47.323      Interface\FrameXML\UIParent.lua:2899 ToggleFrame()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:263 ToggleWorldMap()
7/23 08:34:47.323      TOGGLEWORLDMAP:1
7/23 08:34:47.323  Interface\SharedXML\Pools.lua:78 Release()
7/23 08:34:47.323  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:ClearAllPoints()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1536 WorldMapFrame_SetOverlayLocation()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1559 WorldMapFrame_UpdateOverlayLocations()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:513
7/23 08:34:47.323  Interface\SharedXML\Pools.lua:78 Release()
7/23 08:34:47.323  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:SetPoint()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1538 WorldMapFrame_SetOverlayLocation()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:1559 WorldMapFrame_UpdateOverlayLocations()
7/23 08:34:47.323      Interface\FrameXML\WorldMapFrame.lua:513
7/23 08:34:47.888  Interface\FrameXML\WorldMapFrame.lua:275 WorldMapFrame_InWindowedMode()
7/23 08:34:47.888  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:Hide()
7/23 08:34:47.888      Interface\FrameXML\WorldMapActionButton.lua:58 <unnamed>:Clear()
7/23 08:34:47.888      Interface\FrameXML\WorldMapActionButton.lua:67 <unnamed>:Refresh()
7/23 08:34:47.888      Interface\FrameXML\WorldMapActionButton.lua:19 <unnamed>:SetMapAreaID()
7/23 08:34:47.888      Interface\FrameXML\WorldMapFrame.lua:429
7/23 08:34:47.888      WorldMapFrame:Hide()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2369 <unnamed>:SetUIPanel()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2446 <unnamed>:HideUIPanel()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2137
7/23 08:34:47.888      <unnamed>:SetAttribute()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2931 HideUIPanel()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2897 ToggleFrame()
7/23 08:34:47.888      Interface\FrameXML\WorldMapFrame.lua:244 ToggleWorldMap()
7/23 08:34:47.888      TOGGLEWORLDMAP:1
7/23 08:34:47.888      RunBinding()
7/23 08:34:47.888      Interface\FrameXML\WorldMapFrame.lua:606
7/23 08:34:47.888  Interface\FrameXML\WorldMapFrame.lua:275 WorldMapFrame_InWindowedMode()
7/23 08:34:47.888  An action was blocked in combat because of taint from WeakAurasOptions - <unnamed>:Hide()
7/23 08:34:47.888      Interface\FrameXML\WorldMapActionButton.lua:58 <unnamed>:Clear()
7/23 08:34:47.888      Interface\FrameXML\WorldMapActionButton.lua:67 <unnamed>:Refresh()
7/23 08:34:47.888      Interface\FrameXML\WorldMapActionButton.lua:26 <unnamed>:SetHasWorldQuests()
7/23 08:34:47.888      Interface\FrameXML\WorldMapFrame.lua:430
7/23 08:34:47.888      WorldMapFrame:Hide()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2369 <unnamed>:SetUIPanel()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2446 <unnamed>:HideUIPanel()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2137
7/23 08:34:47.888      <unnamed>:SetAttribute()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2931 HideUIPanel()
7/23 08:34:47.888      Interface\FrameXML\UIParent.lua:2897 ToggleFrame()
7/23 08:34:47.888      Interface\FrameXML\WorldMapFrame.lua:244 ToggleWorldMap()
7/23 08:34:47.888      TOGGLEWORLDMAP:1
7/23 08:34:47.888      RunBinding()
7/23 08:34:47.888      Interface\FrameXML\WorldMapFrame.lua:606

Please provide any additional information below.

Ever since the last occurence I recreated all auras I am using and reinstalled the AddOn.

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/1167918/WeakAuras.zip)

In case you do know which aura is problematic, please export the string and paste it below.

sadly not.

**EDIT:** My inability to format properly.

**Comment by InfusOnWoW** [comment]
Please enable taint level 2, by running /console taintLog 2

That should have more information on how the taint was caused. It's unlikely to be a bug in WA though.

**Comment by nebularg** [comment]
This is just a problem with the map with pretty much no way to prevent it. There is a secure button (instantly complete WQ) that is easily tainted when you go into combat with your map open.

I have had a bunch of reports blaming oRA3 which doesn't ever touch anything related to the map, so it probably spreads from something like ShowUIPanel (which should be safe via delegates) but who knows.

**Comment by InfusOnWoW** [comment]
Okay, what neularg said. He certainly knows more than me on taint issues.
