### ISSUE TITLE
Energy icon flickering

### ISSUE THREAD

**Issue by EKanadily** [WeakAuras/WeakAuras2#2555]
## Describe the bug
i have an icon that appear ( in solid green color) if the energy level of my brewmaster monk is => 65% 
the problem : 
1-if energy < 65 the icon disappear (as expected) 
2-when energy caps the icon become solid green (as expected)
but when the energy is moving from 65 to 100 the icon flicker (several times per second) during that period  

**Do you have an error log of what happened?**
buggrabber / sack show no error message

### To Reproduce
create this icon 

!WA:2!DrvZUnUnq4AKcST6qAxJMGG9uAkqkAr7I9NM0EOzbIILBtxNydzTP7nlkPrIerMuLKYooh9PThRFe859KFeYtaHrFc8JqEc6q5FqspPrd)goFC((iR1SE)6j1t(W3iVPDAQc0JKJwguBgHhtfYocgxp1TDqq7lA51myESqKNigY7oKvaH3T(xVKmGkjXAMGRo2xPjsTtukJZuuhx8J2zSwYYYaPA7dLRc)WH(ASORDjLAXesPKWj9b1ZgFLGLKkK9hNG5S7z9xoVub9IPeBtajDIQaYZVeHVxT)(JlWggFTQDbGWfYdo5KfQYiyaW1Dlttz3mR3zN2nOx3Gt9dwuigcYEI1GFZjZXWyelfi5A6b)8r(vL63XcS4lTDEfIQsPtSzQyE4cBijsjKrxisGW5zahKS4UuXW28fQQpNTAkn2cUehgHv7qCorPOrl5E9xxLRQbHf7(igTHR1)vzjVIBMTNVbUEekfttGi8OgGXYF3RvNMVRLeryNqHUwe2(OlvU2(hvKtgbs)QYp44J2mT6ibCA53TJxRwfp12HhDEcNSPHpzMDvgFaQOaDUejA31sY0agQU73HK3VILB0QWXvHNNOC8Ro9(n8F35n8RKDNLn8rN8W7E4GhzAXopmXdfXjL8v2QDn)G5hlEQ1noacwMZkoF8tUhDZGKtYVcznARE79xdqXPiPI1(wJgDcHZ6xz5o28znVdikORwc8mn9jMV3Ll4W81MYE25aE6Jf8e1ylu7030WTpHXBAodlW0W4zAA(n87N))ZGkMcveCVa6uua8Hm7ThNikWYO6DCZfKKRmFD44vZW4qZVCyKIXZYb3lAF5B97xMRzoU21o0C5wMopl0vXUf210XzQSA)SuYLHuCoEjdVr3UO6oQJjiCQL4SL)wShlJlKWQL9SMbpPuivHfF16B5bWn6gmfjkhsOU3ke9Rz2MovlIhSCEUxTE)ZbSK7FXpTVhABYgT)Boz)Jp6vLSKz)5FD9TnjFhBK(9(K8ckzl)HSen9BVF5tnnLOjWY2OUN575DzeYUuwMJCThZpwKlK)rTTQT1SulyuyiAYxmlHPS(5ZXcEfkqJxtx8rcipT6jmZNwx5)6N)IN)Y6d(33)F)

**Screenshots**
Not applicable, need video because there is a flicker

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes, the problem persist

**Which version of WeakAuras are you using?**
3.0.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [x ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
 it was working. i have NOT played the monk for about 2 weeks
### Additional Info

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5391160/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
Well, that's due to using a invalid icon path. Convert the aura to a texture and use a solid square texture instead.
