### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by dakar2008** [WeakAuras/WeakAuras2#2557]
Getting Following LUA Error:

`2x [string "--[==[ Error in 'Obsidium Ore' ]==] return ..."]:3: attempt to compare number with string
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:601: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:761: in function `CreateFakeStates'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:3773: in function `UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:3749: in function `FakeStatesFor'
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:2773: in function <WeakAuras\WeakAuras.lua:2664>
[string "@WeakAuras\WeakAuras-3.0.1.lua"]:2793: in function `Add'
[string "@WeakAurasOptions\LoadOptions.lua"]:370: in function <WeakAurasOptions\LoadOptions.lua:368>
[string "=[C]"]: ?
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Masque\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Masque\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-EditBox.lua"]:74: in function <...que\Libs\AceGUI-3.0\widgets\AceGUIWidget-EditBox.lua:71>`

**Comment by InfusOnWoW** [comment]
The error is in the aura "Obsidium Ore" not in WeakAuras itself.
