### ISSUE TITLE
templates

### ISSUE THREAD

**Issue by akaia033** [WeakAuras/WeakAuras2#2560]
I just figured out it is just the template text that isnt working on my retail wow. I can make template bars and they work fine. IM not computer literate but I figured this much out lol

**Comment by InfusOnWoW** [comment]
which template did you use and what exactly didn't work?

**Comment by akaia033** [comment]
I figured it out ahh they are hiding behind my icons lol. I usually have them floating over my icons. How can I put them on top of my icons again? I play all classes so I need them to watch stacks and stuff lol

**Comment by akaia033** [comment]
the template text

**Comment by akaia033** [comment]
I figured it out lol
