### ISSUE TITLE
Weakaura addons is 100% broke, can't create a new weakaura

### ISSUE THREAD

**Issue by Dcent** [WeakAuras/WeakAuras2#2561]
## Describe the bug

**Do you have an error log of what happened?**
sadly no, but for some reason when I create a new weak aura it is not in the list of weakaura, and the button for import and so dissapear in the window

![weakaura problem](https://user-images.githubusercontent.com/2535976/96310981-c244be80-1008-11eb-879d-915de267ef86.png)

### To Reproduce

1. 'install weak aura addon version ``weakAuras.3.0.2.zip``'
2. 'login to wow'
3. 'type ``/wa``'
4. 'create a new weakaura and you should get the same resualt as this'
![weakaura problem](https://user-images.githubusercontent.com/2535976/96310981-c244be80-1008-11eb-879d-915de267ef86.png)
**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, I do not use ElvUI or that many other addons

**Which version of WeakAuras are you using?**

3.0.2
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

it was working before prepatch so older version did work yes.

**Comment by mrbuds** [comment]
Where did you install the addon from ?
Can you try with the file found on https://www.curseforge.com/wow/addons/weakauras-2 ?

**Comment by Dcent** [comment]
I installed it with the twitch app. I have just tried to down grade to version 3.0.0, and this version works perfectly for me.. 
then I upgraded again to 3.0.2 in twitch app, and the problem is gone. so it seems like the twitch app are missing some files or something from a clean install.

**Comment by InfusOnWoW** [comment]
If you encounter the problem again, feel free to open a new ticket.
