### ISSUE TITLE
Progress Bar Tick Default Color Not Allowing Updates in the UI

### ISSUE THREAD

**Issue by clearlyspam23** [WeakAuras/WeakAuras2#2563]
## Describe the bug
When adding a Tick to a progress bar, there is a Color Selector Available to set the color of the tick.

Under some circumstances, it appears that the tick color resets to white regardless of what color is picked.

**Do you have an error log of what happened?**

No Lua errors seem to get printed to the console.

### To Reproduce

I don't know if this is falls under self promotion, but this weak-aura I have reliably exhibits the problem across 2 computers.

1. import this weak aura group - https://wago.io/ACD6UryIi
2. attempt to change one of the tick colors of the "Holy Power Bar" weak aura.

I have been trying to see if I can get a minimally reproduceable version of this issue, but so far have had no such luck. I'm honestly not certain what specific combination is required to reproduce this issue.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I have tried this running with only WeakAuras, WeakAuras Archive and WeakAuras Options and it reliably reproduces.

**Which version of WeakAuras are you using?**

WeakAuras-3.0.0-beta3 for shadowlands
WeakAuras-3.0.1 for retail

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

I cannot say for certain when this broke, as it only seems to occur sometimes. After the issue occurs once it seems to be reliably reproduceable. I believe this was working in WeakAuras-3.0.0-beta1, I did not use beta2 and it is not working in beta3. I do not know for certain when this broke.

**Comment by InfusOnWoW** [comment]
I cannot reproduce that. The likely cause of that is a outdated color picker addon. We did ask you to disable all other addons...

**Comment by clearlyspam23** [comment]
The bug still reliably reproduces for me with only weak aura and weak aura options enabled. I've noticed after further testing that it seems to only affect weak auras that have been imported by string and then modified.

**Comment by InfusOnWoW** [comment]
Then you should really add a example of that kind of aura to the ticket.

**Comment by clearlyspam23** [comment]
I have updated the issue with a better description of how I am reproducing the issue. As called out above I have tried to get a minimally reproduceable example of this issue to share, but so far have not managed to get a solid example.

What I have tried:

1. Create a progress bar and add a tick to it, color the tick in anyway. Export and Import this progress bar again (behaves as expected).
2. The same as above, but the bar is a part of a group (also behaves as expected).

The Weak Aura I have linked above was made in the shadowlands beta 3.0.0-beta1 version of weak auras, its possible that this issue was caused by some kind of change in how the weak auras were persisted between that version and the current version, I will try remaking the whole weak aura to see if that is the case.

Sorry for the inadequate reproduce steps in the original posting.

**Comment by InfusOnWoW** [comment]
Well, I can reproduce the issue with that aura.

**Comment by clearlyspam23** [comment]
After further testing, it appears to be related to the second condition in the aura I have linked. Removing that condition seems to cause the color pickers to work as expected. (the other 2 conditions can be left as is).

Worth noting that although the condition changes the color of the 4 ticks and the border, only the color of the ticks seems to be exhibiting the issue.

I still can't seem to get a more minimally reproduceable issue, but attempting to recreate the Holy Power Bar Weak Aura from scratch exhibited the same issue when readding the 2nd condition.

**Comment by InfusOnWoW** [comment]
Ah thanks that explains the issue. I'll fix that for the next release.

**Comment by InfusOnWoW** [comment]
Also thanks for the through investigation into figuring out how to reproduce the issue.

**Comment by clearlyspam23** [comment]
Can confirm this is fixed. Thank you for the quick turnaround.
