### ISSUE TITLE
Please allow for working with lists of spells to be easier

### ISSUE THREAD

**Issue by TheInternetIsReal** [WeakAuras/WeakAuras2#2564]
**Is your feature request related to a problem? Please describe.**
The problem is two fold:
1. I cannot quickly supply a simple line or comma separated list of spells to weak auras like I can with Grid2 or NeatPlates. This makes it incredibly painful to trigger on the 200 or so roots and snares in the game for Blessing of Freedom to cure.

2. Only certain Triggers allow for a manual list entry at all. For example, Aura Triggers allow for multiple spell names whereas Event Triggers only accept one spell name, period. I need to use Event Trigger for an icon to show up whenever my group is snared by the various 200 spells. This makes my idea impossible to implement without creating 200 separate auras.

**Describe the solution you'd like**
A paragraph block to paste a list of spells into for EVERY trigger type, instead of the current manual entry solution for (only) aura triggers.

**Describe alternatives you've considered**
Built in trigger for each PVP cc status: stun, root, snare, fear, incapacitate, and any others

**Additional context**
Grid2 example
![image](https://user-images.githubusercontent.com/8439537/96324719-09668b80-0fd8-11eb-8ac1-59b46e99549f.png)
NeatPlates example:
![image](https://user-images.githubusercontent.com/8439537/96324747-21d6a600-0fd8-11eb-9311-f0a3609c92f1.png)

**Comment by TheInternetIsReal** [comment]
I may have found another bug when trying to use Aura trigger using the unit of Group or Raid.

This works by not showing beacon of light icon. I don't have it on afterall:
![image](https://user-images.githubusercontent.com/8439537/96325306-a70f8a00-0fdb-11eb-8abc-d8fdc60e17ac.png)

When I select a Unit type of Party, it keeps showing the icon even though no one is in my party and I do not have the beacon of light buff on:
![image](https://user-images.githubusercontent.com/8439537/96325322-bdb5e100-0fdb-11eb-8879-bcd52d5dbefe.png)
![image](https://user-images.githubusercontent.com/8439537/96325326-c3abc200-0fdb-11eb-9a27-7643d9d53bab.png)

**Comment by TheInternetIsReal** [comment]
One last bit of troubleshooting for you. I tried triggering the aura by pattern matching:
![image](https://user-images.githubusercontent.com/8439537/96325613-feaef500-0fdd-11eb-8374-95e406b308d4.png)
No beacon of light buff on:
![image](https://user-images.githubusercontent.com/8439537/96325616-053d6c80-0fde-11eb-880d-7edea7483e29.png)
With beacon of light buff on:
![image](https://user-images.githubusercontent.com/8439537/96325626-0ec6d480-0fde-11eb-92f0-d0c9c6215ee8.png)
Again, this is only an issue when I select Party, not Player.

**Comment by InfusOnWoW** [comment]
Please do not fill up your feature requests with random imagined bugs. It both fills the feature request with garbarge. And is a bad way to even report bugs, because all the necessary information on how to reproduce the bug is missing.

First, as you have already found out the aura trigger allows entering multiple spells with no pratical limit. That is essentially the same as Grid2 or Neat Plates do.

But even without any example aura that has your problem, I can guess to what the problem is. A group aura has a myriad of settings which control when it shows up. You simply did not enabled any of them and thus it shows up.

**Comment by TheInternetIsReal** [comment]
Hi, sorry for adding extra stuff. However, you ignored the request. The request is about being able to copy and paste a large list. You cannot do that in WA. It took me 15 minutes to add a list of 50 spells to a trigger one by one.

**Comment by InfusOnWoW** [comment]
That's not something which we want to do.
