### ISSUE TITLE
Error information

### ISSUE THREAD

**Issue by gongzifusu** [WeakAuras/WeakAuras2#2565]
1786x [string "--[==[ Error in 'Friends 2':'custom text' ]..."]:2: attempt to call global 'GetNumFriends' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\WeakAuras-3.0.2-2-g5323266.lua"]:4060: in function `RunCustomTextFunc'
[string "@WeakAuras\SubRegionTypes\SubText.lua"]:310: in function `?'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:34: in function `Notify'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:648: in function <...aceWeakAuras\RegionTypes\RegionPrototype.lua:638

**Comment by InfusOnWoW** [comment]
That's a bug in your aura: Friends 2, which is using a API that was moved in 9.0 to a different place.
