### ISSUE TITLE
Debuff Aura seems to randomly choose when to trigger

### ISSUE THREAD

**Issue by TheInternetIsReal** [WeakAuras/WeakAuras2#2566]
## Describe the bug
I expect the list of spells to trigger whenever anyone in my group has the debuff applied to them. However, it seems like it triggers whenever it feels like it. I can't find any rhyme or reason when it will decide to show or not. I've been testing in BGs.

**Do you have an error log of what happened?**
I don't think there are any errors, just some bug in the functionality I don't understand.

```plaintext
No Error
```

### To Reproduce
Use this and go into a bg. Watch the actual debuffs with something like Grid2 or Vuhdo:
`!WA:2!DrvqVTTnu4AKaSnHHHe3SI1BEfydlDdbbzOb74S8KtsNJDgfttgWaSPKOe5QmjhjLDCUvFQxN)j4Z7KpSZf5xGGXW(b0Fc5pWgjLTx70bPh)EpY377XVNQ1U(W6j1tE9NlVPxAQcRp97F4)8MhyEKtwdCYB(ylWcelMWLxWPmDuRGUWaWYyoppHpMfoMkWdUB9YGKmmrII1uotDmqPrsTxukLrvepFZhT3uTKMLHLQp5lLRm)tzHc3fnep4TQIi8imthwKMsVzr)wndH9dHnbqGdp6umkxt2e3fsSjoq4fbD64RNiWauHeD0uLaNNFwIYZVWKuqMKxiweZhgrz4Z5j4fkcF8P0mcwPbmtQvEZS70z(CXoTKuHiNYYAyOTIZM3wYv6gD5JqIDcyAelZ5fW5A1uis2akrI5j4itHdn1H80MGZBFzNzfSvS0tSRTXmcdRwBlJ)4b3BAQyjdL)ctlX01(X7FjglAAQ)ynaz6JKzigDO1IDC5h2(omsHd1smltt(GY98zCgEzIP0Tr032cKkCmNLOMAd1wlL77perzTl)kZgk3V8PLFD53y((r)Fet9RqA7zHjZnTyaoZEr(0xVNOUgFJUVIGmxZxxjqQjESd09kLlnfzF1kJY9NTX3t(cLyN3z7T45C5ZRvR2wVTcfNN6ex(nVe2t8qhiQqZTSo(kAIM430S8(QerVbN4aF1YkH5pVQCUZ5)xluAA6KYTNl5AdrGgq)U96guUN0qjBmZDbg7kJTmpZwXaMwStBj92g)ubkX0eqnGW3J4RZ0sh2yUm5kZT(0RwzuvaJOkAuoEWko)odpIDpRB3aqF)EqyVZbNDYPWLBsDi9w8JxXORFV8y96Ku9Ue25SUb)9YSC(42s8VvGzXtUy7dp4ONvXoRJf2xRpHP2f2nVmQqR5SEJWYC0K5w4oon0N6IFnZMzx0AtN5oZG5jRri(wNex2HeA8lzyLAl3ocJr54kZoMjm1UUe4B6lyjjIGndA6x5NZrjh7BL2pcmSixt9aX5iL6rL)INVYWFRXCPt0zRzFQrhpBJ8OC7iZ6uAMhaLliOT8VLZhwZ3kvgmxZJhvnc9z16)7pHMm9ky7gWGqOyV1)EYQf(bQczUEsilsLMHDZOK5IER7RA8TTq2uhf2cee0DP5SnW9eUFO5DubnzrI(z(hnm)fFxVujLzZjMag7eKLdgm3o6rRcF668sa)NyRUc8ThC4bhwF0FD9)(`

```
{
    ["authorOptions"] = {
    },
    ["yOffset"] = 47.500366210938,
    ["anchorPoint"] = "CENTER",
    ["cooldownSwipe"] = true,
    ["cooldownEdge"] = false,
    ["actions"] = {
        ["start"] = {
        },
        ["init"] = {
        },
        ["finish"] = {
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["type"] = "aura2",
                ["subeventSuffix"] = "_CAST_START",
                ["event"] = "Health",
                ["subeventPrefix"] = "SPELL",
                ["useName"] = true,
                ["spellIds"] = {
                },
                ["auranames"] = {
                    [1] = "Crippling Poison",
                    [2] = "Frost Nova",
                    [3] = "Entangling Roots",
                    [4] = "Tar Trap",
                },
                ["combineMode"] = "showHighest",
                ["names"] = {
                },
                ["unit"] = "group",
                ["debuffType"] = "HARMFUL",
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["internalVersion"] = 37,
    ["keepAspectRatio"] = false,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
    ["desaturate"] = false,
    ["subRegions"] = {
        [1] = {
            ["text_shadowXOffset"] = 0,
            ["text_text_format_s_format"] = "none",
            ["text_text"] = "%s",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_selfPoint"] = "AUTO",
            ["text_automaticWidth"] = "Auto",
            ["text_fixedWidth"] = 64,
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["rotateText"] = "NONE",
            ["type"] = "subtext",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowYOffset"] = 0,
            ["text_wordWrap"] = "WordWrap",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "INNER_BOTTOMRIGHT",
            ["text_fontSize"] = 12,
            ["anchorXOffset"] = 0,
            ["text_fontType"] = "OUTLINE",
        },
        [2] = {
            ["glowFrequency"] = 0.25,
            ["type"] = "subglow",
            ["useGlowColor"] = false,
            ["glowType"] = "buttonOverlay",
            ["glowLength"] = 10,
            ["glowYOffset"] = 0,
            ["glowColor"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["glowXOffset"] = 0,
            ["glow"] = false,
            ["glowScale"] = 1,
            ["glowThickness"] = 1,
            ["glowLines"] = 8,
            ["glowBorder"] = false,
        },
    },
    ["height"] = 64,
    ["load"] = {
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["class"] = {
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["regionType"] = "icon",
    ["selfPoint"] = "CENTER",
    ["width"] = 64,
    ["frameStrata"] = 1,
    ["zoom"] = 0,
    ["auto"] = true,
    ["xOffset"] = 4.999755859375,
    ["id"] = "WTF TEST",
    ["color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["alpha"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["icon"] = true,
    ["uid"] = "dt5B2mlV8Of",
    ["inverse"] = false,
    ["cooldownTextDisabled"] = false,
    ["conditions"] = {
    },
    ["cooldown"] = false,
    ["config"] = {
    },
}
```

1. Go to a bg
2. Watch the icon only show for the debuffs your teammates have sometimes and not others
3. Use Grid2 or Vuhdo to show the same list on your unit frames to compare and contrast

**Screenshots**
It took 10 minutes into this BG for anything to show on the left icon
![image](https://user-images.githubusercontent.com/8439537/96327621-07a8c200-0ff0-11eb-86dd-b0625920a0d3.png)
`!WA:2!DzvtVTrYr0vGgWi8qGKSDWU50abS2j5GHHdYgShwGWHI0I2uukZmY05KuZzkYUxoS7oD3dPOUTmojg5w4XCkGhdYjEniabe5sUnGiFCx)e4VGuvtkfVrhO6P6A6QQx9Qxp718WrhMDy2hoYC9z97Bb3j)TK)v0NG)zMUZWpR1x)NidlzYuUYCUsiD9Q3OtsJO1PkvEMAImEIqdxT6UhBKna4HIuL8QzoJyWaWy)Up1SB5hEYCwHHjzJa7Fmz5Xg2aLmisXmlERihcsyyew3rmG7csaJrzSRRZrJ2av)GwPWMwY(qQdYc6QkKz2n1vY0cRvmgcI5k3m0NGedtpVPrzD9u5UW4C1KvOFaDg1X08w)E9fgiieDy(PczwqZC20vhdSS8PbjCJAIE)6gHwNlKdcWk3QKl9VhfN0Hl2E(yTKTPbZ449Odjr5Gr6hvVWy9rRX1CwH1juYBpggPKI0GqdWC81NlatkD0NOMKp)e2ilcrYb69BiDm5aFuJukNDttLj1FyDyUcdOp4uM1gSZnyeqTeoZmaw3HHi2KGg2uMgwGEG4GF)MgaUb2MYbDuJzEyQlZKzowyz9YHT1WadR32AWKmvZvk56yUqs5IplwLWrqh7OoLz0Iewo18azM(GtqCGYXtquaXKuyExOxqS2GGAZcJqvydcfoyrc6o9wc9IWCLkZ3bM1gr0GxZMSSMCisdQByPdN1Ll05mlxV)Bb5aOFrogmhbFR2wjBHYvNayUheJ43qqFyeIZi6Ndii1fztGzwcZ45eRdX(IJQgIQmVlTQEUqplmxCZniA0RzEHXmDjHoHiyI9OLiVajR(dF(Ba8vhrP0JAMp1FqGrJiCWBePdxEUabMC)HFBmNHJdpZg8kdZQVd4WWX0ltezm0TcQNfpbaDGJdbTHb6N0s6eJWT9z55gWciwQFsSMdgpjiUqRrZwKsPp4(hiNlYTWQ6CrEoHfaB4QUS8H0weRUxcoalTRAYaSScINWmJwMuy6PcAIPT1CUDAFCeieB4Jxfp1IKGTm9LnHCYhlr(23J8tMAgHLg2yNQ3)v4ucLzunqrAtSyGi3pR5NCV9cJvLJU)wLXbxJ9oC)mQ3KzroadBKDzJPu3OKkmMI(o9(XAivGO0XqooBBMUUlBOhaQz5GvFiopBHudJKcELH0cwvybALosLd81JyUu0tSeMCMCL1)VAPo8WMtYpxkK9vgKFnfPZ3Al6bJX(iI49fxhfFEJ2TxuifUgxtGdFzQAeoGdNQYGL0zDckrHSIfzqVI(9XHfWCsTOtBErBdMgDWaC1gCXLB3h76wl)(OeJMexV8Y61ItUmoPwuYQ(aMTjOgQtO5rEV6H86Chx)ykDpN5qMS8sfgigo9T0xE)GN952N9ddPen0WezZSAipVvMTAOdtPisR9L69)4dGwVjeyOanHMTjP2B3LY78Hh51NR2dnJtt85fYDY3v1hW8qyY2Nj44p)jB8tzsw(BrOe5LVzZqKtxdZLuxeYKv85mPyeTs(frwhoT2SCsOevKxbmlqSv5ah)HRZW8L86sk7XHymjZSZiFieU89HJqcf(ULVV8x)WYFt5VT8dLVVxFuHYY))nJTgljyIme(ce5JGb4jB)rF4X6drAO7sRFc9DBVQBp9N5n6)bjgy2EPD3IY3p)(9o6ZT69)OxhVorzE9E7TxLB3AfY77VMmS2fjNPFK3iRWPOYpTRiZXdRHpUzBGexdzEJFZ6TxX(l2LoR87)10Dh9Nw(GfgLdlKe0yyNZ60OCIbljYNfEht9Prf8V57QaPJMvf3e8ZlyOISJfKK8Tk87I0AVTjktwxuICw3Dl2MaJfwbE7Wv7Q5p6Za0h0QtNgrxgEwsYzNg16vNKS((qhlUb(SDv07(wXH21pTC2fjTB1PX)E9a82z8(PFzbQ0n98h8IN)YFY2QJ2yj9ZDNWm6b6Lx3RW5uYZqDbC(DbzUTNb9eV)3vzZPhQFpY41hUZcpK2K7DjoLLdv8jsch1XLOIAf)oTXrE7b(aeI4cy494anX8n4DxSS(ZPr8uA4(Qz0sIYFvK3Wt7rQY5G58ATRDCRorJkWz7QHKlpT8VuP8VwDH)TrHf8sSqlczFpYOXZt989hUgzoieEMMgkSvJ(FT5iwUMZQSGMqe(D)(pnc17sh2S87uz2yMrqxRpNKgQJQJUOXS8c4WxCKsF0x9vMuo(1da(sL)JkZ0gswXnT8VRF8DFhhr129Tbz8qIbF1cNkD82r8pDVl)9hjYmTVOwsJ4KWBuQr7TSVb1nWPzKTvzZ2UFtYevm9IRh1OrNxwiYwAKF5x)6V8N2OgRDpSa6lguf)2h6Ob(87NGkFq0e)OXYmHLeQBH((Pv(d)Nz3LJCdPgH1(xu(RQgIQaUQL)UQhAJ(Xp)fp)fho(F(U)l`

Until then it looked like this:
![image](https://user-images.githubusercontent.com/8439537/96327664-6e2de000-0ff0-11eb-88a3-90d4be0c28c4.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No but I can test and report later. I don't have Elv UI or anything else that installs weak auras. Grid2 is installed and shows debuffs correctly from the same spell name list I gave it.

**Which version of WeakAuras are you using?**
3.0.0

**Are you on World of Warcraft Classic or Retail?**
Retail

- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Pre pre-patch

### Additional Info
Part of the issue may be smart group vs raid vs arena vs whatever.

**Comment by TheInternetIsReal** [comment]
Still making no sense. Notice the red sword debuff on grid2 on the left. That showed correctly, immediately. It took ANOTHER application on my party for it to show up in the bigger center icon from weak auras. Then randomly the weak aura icon on the right showed a frost bolt (????). The weak aura icon on the right was a duplicate of the left icon with the only difference being that the left is set to Raid and the right is set to Arena.
![image](https://user-images.githubusercontent.com/8439537/96327834-1db78200-0ff2-11eb-9a49-3ad5e097c048.png)

**Comment by InfusOnWoW** [comment]
I don't know why you assume that we can figure out what are the actual weakaura displays in your screenshots. Though I note that both of your auras are set to always show one aura, whether they match or not. And that they will never show more than one match.

As to showing Frostbolt, that's because you entered Frostbolt as one of the debuffs to track. I don't know why you are suprised that it indeed shows Frostbolt when you ask for it to show the Frostbolt debuff.

**Comment by TheInternetIsReal** [comment]
They are set to only show one aura. Once this actually works as intended the icon will be set as bof no matter what triggers it. This will tell me to push bof.

How can I help you understand better what icon is the weak aura better?

**Comment by InfusOnWoW** [comment]
Because they are not indentically. One tracks your party and one tracks the raid?

**Comment by TheInternetIsReal** [comment]
Right, and I'm in a bg with one partner so why would one show one debuff but the other would show another debuff if they have the same list?

Secondly, why do they only show the debuffs in the list sometimes and not others?

I'm just trying to help the devs figure out why this is bugged. I've ready did half the trouble shooting to narrow down the bug in the code for them.

At this point it's on them to understand why it's not working as expected.

**Comment by InfusOnWoW** [comment]
Because while you are in a BG, the raid is the whole group and the party is the subgroup you are in. 

It shows the debuff based on the settings you have selected, which is the one with the longest duration. That's what you have configured it to do.

At this point it is pretty clear that you have no understanding of what you have actually configured and what it should display.

**Comment by TheInternetIsReal** [comment]
Because we can't seem to get past a single tangential piece of info I was trying to supply to help the devs I'm going to open a new ticket with only the specifics of the initial bug I found. Hope to speak to you there. Thank you for your help so far.
