### ISSUE TITLE
there is a bug, pls help, many thanks

### ISSUE THREAD

**Issue by control111** [WeakAuras/WeakAuras2#2567]
2x [string *--[==[Error in 'DataTests-WarMode' ]==]re...*]:3: attempt to call global 'UnitIsWarModeDesired' (a nil value)
[string *=[C]*]: in function 'xpcall'
[string *@WeakAuras\GenericTrigger.lua*]:601: in function <WeakAuras\GenericTrigger.lua:537>
[string *@WeakAuras\GenericTrigger.lua*]:733: in function 'ScanEventsInternal'
[string *@WeakAuras\GenericTrigger.lua*]:694: in function 'ScanEvents'
[string *@WeakAuras\GenericTrigger.lua*]:840: in function <WeakAuras\GenericTrigger.lua:825>

**Comment by InfusOnWoW** [comment]
The error is in your aura: 'DataTests-WarMode', which is using a api that Blizzard removed in 9.0
