### ISSUE TITLE
pls help to fix the bug....

### ISSUE THREAD

**Issue by control111** [WeakAuras/WeakAuras2#2568]
47x [string "--[==[ Error in 'DataTexts-WarMode' ]==] re..."]:3: attempt to call global 'UnitIsWarModeDesired' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:601: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:733: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:694: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:840: in function <WeakAuras\GenericTrigger.lua:825>

**Comment by Causese** [comment]
The error is in your aura: 'DataTests-WarMode', which is using a api that Blizzard removed in 9.0

**Comment by control111** [comment]
thanks a lot, but how can i fix it?













At 2020-10-17 17:18:39, "Causese" <notifications@github.com> wrote:

The error is in your aura: 'DataTests-WarMode', which is using a api that Blizzard removed in 9.0

**Comment by Causese** [comment]
This github is about reporting bugs in the weakauras addon and not about bugs in some weakaura that you are using.

You might get help in the weakauras discord. https://discord.com/invite/wa2

**Comment by InfusOnWoW** [comment]
By either:
* Deleting the aura, or
* Updating the aura if there's a newer version of it, or contacting the author if there isn't, or
* Fixing the code yourself.
