### ISSUE TITLE
Imported on <Date> in WA UI

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#257]
Would it be possible to add info about when an aura has been imported?
This is for shared auras on wago, which do not publish some sort of version when a new update is available.

For example:

Aura A has been created 10 July 2017, it has been imported by the user on 11 July. The aura has been updated on 20 July 2017, but the aura does not give away a changelog and inside the aura is nowhere an info about what version the current imported aura is. 
If the WA UI would give away that this aura has been imported on ```<Date>``` you could easily find out if your aura is outdated by looking at the wago.io "updated at" field.

**Comment by InfusOnWoW** [comment]
The date isn't that useful. Especially since you could e.g. import a aura, and share it later via chat. What would the imported date for the receiver be?

But we can certainly look into adding a version.

Also btw. Patreons on wago.io get notifications for auras they starred.

**Comment by pquerner** [comment]
The receiver would get the same date as the sharer, of course. They both have the same data, so why would that change?

> But we can certainly look into adding a version.

What do you mean?
Imported aura first time = version 1, imported second time = version 1.1 (if anything changed) ?
That _should_ be defined by the auras author (but isnt all the time, hence my proposal here for a workaround)

I'm not arguing about starred auras, but that could help aswell but is behind payment.

**Comment by InfusOnWoW** [comment]
If you share the aura at version 1.0 with a friend via chat. What version number does he get?

Especially if you moved the aura around.

**Comment by pquerner** [comment]
Ah, I see your dilemma. When is a new version a new version.
That wouldnt be a dilemma if you dont focus on a version number now.
The imported date would indicate it more clearer, that you are using an outdated version, I think.

As a user you would see "oh I imported it on the 20th of July, but wago says the latest version is uploaded on the 23th of July, therefore it must have some changes".

**Comment by InfusOnWoW** [comment]
I talked to the Ora, who maintains wago. The url now includes which version was imported.

For auras that have updated, visting the url shows this:  
![notnewest](https://user-images.githubusercontent.com/12950521/28559716-f7e3388e-7117-11e7-89cb-ce97936dabf3.png)

**Comment by pquerner** [comment]
Not really what I had in mind, because from the looks of it, that info shows when you visit a aura with an outdated revision url.
Ie: https://wago.io/RaidCDs/49

When I copy that rev49 aura, revisit the page without revision indicator, the aura does not remind me of an update.
(So its not saved in local storage or cookie or something)

**Comment by krazyito65** [comment]
So I think the idea would be that the 'copy url' function in game would now include the version in the url.
 (probably new imports from wago) 

Try importing the newest, and see if the 'copy url' function in game has the version appended to it.

**Comment by krazyito65** [comment]
an example (on a smaller aura) would be here: https://wago.io/RollTheBones  in the 'table data' do a ctrl + f search for `url`

```lua
"url": "https://wago.io/RollTheBones/9",```

**Comment by pquerner** [comment]
Oh I see. Didnt check that function. Of course, that works in a similar way. But I guess its just as good.

**Comment by krazyito65** [comment]
its definitely a small step to a better model. 👍

**Comment by InfusOnWoW** [comment]
WeakAuras can now also interpret a version field. And wago embeds that field.
