### ISSUE TITLE
Instance triggers never trigger on zone changes

### ISSUE THREAD

**Issue by p3lim** [WeakAuras/WeakAuras2#2571]
## Describe the bug
These instance triggers never update when zoning in/out of a dungeon:
![image](https://user-images.githubusercontent.com/26496/96349294-f5da2400-10ae-11eb-8f0a-e8c7b416d9c4.png)

**Do you have an error log of what happened?**
No errors.

### To Reproduce

1. Create a new icon, set the trigger to Status > Conditions
2. Select all the instance type triggers except "No Instance"
3. Enter/leave a dungeon, the icon never shows/hides
4. `/reload` shows/hides it

**Screenshots**
See above.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No change with WeakAuras as the only addon.

**Which version of WeakAuras are you using?**
3.0.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

Never tried.

### Additional Info

I assume registering PEW here would do the trick.

**Comment by InfusOnWoW** [comment]
I can't reproduce that. Which dungeon are you testing with? And can you export the aura?

**Comment by p3lim** [comment]
Every dungeon I've done the past week since I created the icon.

Here's the string:
```
!WA:2!DrvZUTTrq4QQcyuwJIAHKGGc0wHK20K0cxB5ex0JIkY5pLybk10uey4Dj5qYTMAxMDxkBLJ6uVgFOpa6qpv0d6qEa8tWcII8aKd9bWpbDwskdKYdCND25)5BMg71AsRWwH)(1LZ2pksb6glP8GeHCOGX1(96)0X99kceI0qXX8rhZYaYzRU2pmgsK0antWv76P0uP2XLXzAh)i8qL4mxlzXXGu933qwt(gx9SmWJMlPDoZ(xLbPPSq1N7U9DU7pvmHQdsa1OeXX7ZluLhpHPumEShmfWO6banvN4MJoYplLodKZlTXddvoVtL7xk1O8Oi2jlpSx3rJpC04UEJV4PHsaFYB0W(dg4XPtaLZ55kO)jyQmQYqKfHGpAHXyOkFq)bd37NhCAoVofCUH5tERzDFmJ15QZqDpKXdet8PAImNx6exAUwKTH9TyGdswqvgrkEVRVRkb7vxsnxYC5cjMFLXXtXyRrH1eQvxjNEbzdtRf9e8qwz9FEiwkTuT2(uRgASXCeX8fMV08v249FlyCmE5bOXyVcUI3K8un7pMRcaovYeKoAGtwOpgJ9zrSPazEKqQNnHYrQu4eMFkq8YWE8mIhvIAr8RKM0jBAgXSUPT5AMRB(UwBB(gZnSPI5BByUjXCRgvfI3lcsmTm3281eZ3VkkxgYu)wohXttb)GCLwmjRv154Qc)armli7rrLcj43SUFClN24Ne05sE7AEVy7dAt5HTxjZl6CqBH8Ix35GB5a8WSnOLUR2(prec)1hCoc9bjNM(me4IU5XNFeazDXcFG2ZwJtoLYztkR27AwBpZ6UCbhodOkyKgRmX6K1kw1po0c3LkiaBvQ5wzSGktx3jugh11014UMPN5EM(i5h))5GarfIYqBbjlqeSheBB33oAPVqgcYYAzZI6lIQH4ZQVgisfYh1OrJMVRMZuMQSrUsBaNHZ2y0lZXoA79YttB)ljmnyw)u0xvY82I4uXX7jHxMd8Gzd)OT2SZDDT8iwO)9rIEw)qMB5ztUc)CTwW3FkiXXZfw2dkRkxEPL(xRx1CA8kvFut8ZSUe9PLxPupVwQsVpoHfCehuQMLknkGMcvKdyi7nk9HBz4M4NaS4e9RDtf0WN5Rrr56Ry28tjRrwuoAuYjXliLQu4doU2wBfHD0WS5FA(bIzlIzBIPdXSdX0LyUdXCxIzxI5hjlKLnbBQ6YW(QjchlH0OYLMMMYtwTlfb02fupeL5QFyR3KDvwmxiH9Zkhz7B3t0xkfsfPaxxGRDRFXX9vcXKHn3AZDmxhhkfbtRGIxTXHV(ASWSpRRmGYH2perQPPiUStolCP)jJPVA3h7PVVAzKexrGOrQM288QD67zzzdA)r9863)PEhZc1jV2hJUiwSJKXTEbWcZf9epAAwcT5IGl2Z4mF16)KSlTICmCI(EmffrwHjTuE7SjIrAn9FE()9
```

It should show an icon for Arcane Intellect if the buff is missing and the player is in an instance or in combat.

**Comment by InfusOnWoW** [comment]
Every dungeon is not a dungeon in the game. The aura you have attached has no instance load setting at all.

**Comment by InfusOnWoW** [comment]
Ah it's a trigger. Could have mentioned that or just included the aura from the start.

**Comment by p3lim** [comment]
> Could have mentioned that or just included the aura from the start.

From the very first line in the ticket:

> These instance triggers ...
