### ISSUE TITLE
Can't create or import Aura

### ISSUE THREAD

**Issue by Phrive** [WeakAuras/WeakAuras2#2574]
## Describe the bug
Wanted to create a new aura but it has no options available

**Do you have an error log of what happened?**
Message: ...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1047: attempt to index local 'button' (a nil value)
Time: Sat Oct 17 20:25:22 2020
Count: 2
Stack: ...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1047: attempt to index local 'button' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1047: in function `NewAura'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua"]:755: in function `ShowOptions'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua"]:534: in function `ToggleOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:89: in function `OpenOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:133: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5073: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4737: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4773: in function <Interface\FrameXML\ChatFrame.lua:4769>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: errMsg = "...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1047: attempt to index local 'button' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

### To Reproduce

**Screenshots**
https://i.ibb.co/1dmXfcJ/Capture.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Not 100% sure but have checked with the two previous versions and still not working

**Comment by InfusOnWoW** [comment]
That error message is essentially impossible. You probably have a incomplete WeakAuras installation or didn't really disable all other addons.
