### ISSUE TITLE
mele range check for dh doesnt work after 9.0

### ISSUE THREAD

**Issue by MaBpuJia** [WeakAuras/WeakAuras2#2575]
function()
    if (IsSpellInRange("Soul Cleave", "target")==1) then
        return false
    else
        return true
    end
end

function()
    if (IsSpellInRange("Soul Cleave", "target")==1) then
        return true
    else

doesnt work on dh tank, on other classes work (other mele skills)
worked before update

**Comment by mrbuds** [comment]
This is not a bug in weakauras, you can join the discord if you need help with custom code.

**Comment by MaBpuJia** [comment]
but it worked in 8.3
