### ISSUE TITLE
PLAYER_ENTER_COMBAT Event Doesn't Activate Trigger When Load Condition Set to In Combat

### ISSUE THREAD

**Issue by srhinos** [WeakAuras/WeakAuras2#2578]
## Describe the bug
When setting an aura's Trigger to a Custom Event with `PLAYER_ENTER_COMBAT` as the event type and the Aura's Load Conditions set to only while In Combat, the initial `PLAYER_ENTER_COMBAT` event does cause the trigger function to fire.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.2-8-g5d7e6fb

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Not Sure?

### Additional Info

I'm not sure if this is an unintended behavior or not. It could be easily argued either way that this is intended or isn't but I was hoping for a simple way to check my current target but only while in combat and only while I have a target without over zealously hooking a ton of events

**Comment by InfusOnWoW** [comment]
You can use the PLAYER_REGEN_DISABLED event and it should work.
