### ISSUE TITLE
Update loop

### ISSUE THREAD

**Issue by Tor99er** [WeakAuras/WeakAuras2#2579]
i started using the WA companion app to update auras which btw is an awesome app. After i did an update and went in to the game to apply them i kept getting (WeakAuras: No data for "The WA name here") in chat and it just kept going like that for about 5 min until i logged out and forced it to stop

**Comment by InfusOnWoW** [comment]
We need much more information.

* Your WeakAuras.lua
* Your WeakAurasCompanion addon that was created by the companion
* Which aura is the problem.

**Comment by InfusOnWoW** [comment]
Just attach the necessary information here and we'll investigate further.
