### ISSUE TITLE
Spell Range Check for changed spells not working

### ISSUE THREAD

**Issue by Diablolock** [WeakAuras/WeakAuras2#2580]
Since the Pre Patch release there are a few spells that got its ID changed such as Unstable Affliction and Drain Soul (Warlock spells). I can't get the Range spell check to work on these. It's like the lib is outdated.

/e I'm using the lastest WA version as of now, v3.0.2.

**Comment by InfusOnWoW** [comment]
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/2540
