### ISSUE TITLE
Cannot successfully import Paladin modules

### ISSUE THREAD

**Issue by danielzeyangyi** [WeakAuras/WeakAuras2#2582]
## Describe the bug
Cannot import Paladin modules into Weak Aura v3.03.

**Do you have an error log of what happened?**
no

### To Reproduce

1. Open Weak Aura via typing `/wa` in chat
2. Go to https://www.luxthos.com/weakauras/paladin-weakauras-for-world-of-warcraft-shadowlands/ and copy either one of the 3 required module strings
3. Click "Import" that brings up the text window and copy the string in.

Expected:
- Module imported and showed under loaded list.

Observed:
- Nothing is being added and showed under loaded list 

**Screenshots**
![image](https://user-images.githubusercontent.com/39638786/96389816-4cef0000-1166-11eb-80a0-ed516154e8df.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
3,03

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [x] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by mrbuds** [comment]
What if you click the "+" button right of "Not Loaded" ?

**Comment by InfusOnWoW** [comment]
There should be a popup showing after clicking on Import, where you have to click import again.
