### ISSUE TITLE
WeakAuras keeps saying some auras aren't up to date

### ISSUE THREAD

**Issue by zerbiniandrea** [WeakAuras/WeakAuras2#2587]
I'm using WeakAuras 3.0.3. Every time I log in (or /reload), I get the following message:

> WeakAuras: There are 2 updates to your auras ready to be installed! 
![image](https://user-images.githubusercontent.com/43417875/96433275-71e68000-1205-11eb-9ded-38e0c6ab72b4.png)

When I check the list of all WeakAuras I have installed, there are no WeakAuras with an update available (I've also checked inside every group).
The WeakAuras Companion app is also saying that everything is up to date, but every time I log in or reload I get the message in game that says my auras have an update.

![image](https://user-images.githubusercontent.com/43417875/96432950-5d09ec80-1205-11eb-924a-999d082cadca.png)

I've tried both reinstalling WeakAuras Companion and WeakAuras but it didn't fix the problem.

**Comment by InfusOnWoW** [comment]
We would need to gather a lot more information, which includes which auras you have installed.

Since you blocked that in your screenshot, I'm pretty sure you wouldn't want to tell us and thus there's nothing for us to do.
