### ISSUE TITLE
WA not working anymore

### ISSUE THREAD

**Issue by Kiri1999** [WeakAuras/WeakAuras2#2588]
## Describe the bug

Just updated WeakAuras for classic today and when i started playing it showed me an error message and stopped working as usual. Also it wont open the WeakAuras window with /wa.

**Do you have an error log of what happened?**

```plaintext
Date: 2020-10-19 16:47:40
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WeakAuras\RegionTypes\Icon.lua line 361:
   attempt to index field 'Cooldown' (a nil value)
..\AddOns\WeakAuras\RegionTypes\Icon.lua line 361:
   in function `modify'
..\AddOns\WeakAuras\WeakAuras.lua line 2863:
   in function `SetRegion'
..\AddOns\WeakAuras\WeakAuras.lua line 2758:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:2664>
..\AddOns\WeakAuras\WeakAuras.lua line 2793:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 2324:
   in function `load'
..\AddOns\WeakAuras\WeakAuras.lua line 2331:
   in function `AddMany'
..\AddOns\WeakAuras\WeakAuras.lua line 1010:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:982>

Debug:
   WeakAuras\WeakAuras.lua:1058: Login()
   WeakAuras\WeakAuras.lua:1132:
      WeakAuras\WeakAuras.lua:1083
Locals:
None
```

### To Reproduce

Just updated WA via the Twitch app and just started the game and logged into my character.

**Screenshots**

![d5df7423bf9dee0c0c61d31f19c819f4](https://user-images.githubusercontent.com/73123442/96469741-d87f9400-122d-11eb-9996-7a0bc1f44ff2.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
 

**Which version of WeakAuras are you using?**
 3.0.3-classic

**Are you on World of Warcraft Classic or Retail?**

- [X ] Classic
- [ ] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**
Last one I had which worked properly was 3.0.2-classic

### Additional Info

[WeakAurasLua.zip](https://github.com/WeakAuras/WeakAuras2/files/5402835/WeakAurasLua.zip)

**Comment by mrbuds** [comment]
You are using an old version of OmniCC, a workaround for those who have not updated it yet was added to WeakAuras 3.0.4 (release 10mn ago)
