### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by deemerz** [WeakAuras/WeakAuras2#2589]
## Describe the bug
LUA error thrown at startup:

Message: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:361: attempt to call field 'SetNoCooldownCount' (a nil value)
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:361: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2863: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2758: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2664>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2793: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2324: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2331: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1010: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:982>

Time: Mon Oct 19 19:03:33 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:361: attempt to call field 'SetNoCooldownCount' (a nil value)
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:361: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2863: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2758: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2664>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2793: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2324: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2331: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1010: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:982>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1132: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1083>

Locals: <none>

**Which version of WeakAuras are you using?**
3.0.4

**Are you on World of Warcraft Classic or Retail?**
retail

**Was it working in a previous version? If yes, which was the last good one?**
3.0.2

**Comment by mrbuds** [comment]
Hi, which version of OmniCC are you using ?

**Comment by deemerz** [comment]
Hi, it was 8.0.1. Issue is gone after I updated OmniCC to the latest version. Thanks.

**Comment by InfusOnWoW** [comment]
Fixed already
