### ISSUE TITLE
/wa not bringing up the weakauras menu

### ISSUE THREAD

**Issue by Celtas08** [WeakAuras/WeakAuras2#2592]
## Describe the bug

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail
- [ ] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by mrbuds** [comment]
If you don't answer any question we can't help you
