### ISSUE TITLE
setbackdrop error

### ISSUE THREAD

**Issue by Kyle-corbeel** [WeakAuras/WeakAuras2#2596]
## Describe the bug
Opening WeakAuras conig menu

**Do you have an error log of what happened?**

```plaintext
Message: Interface\AddOns\WeakAuras\Profiling.lua:154: attempt to call method 'SetBackdrop' (a nil value)
Time: Tue Oct 20 13:08:27 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Profiling.lua:154: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\Profiling.lua"]:154: in function <Interface\AddOns\WeakAuras\Profiling.lua:84>
[string "@Interface\AddOns\WeakAuras\Profiling.lua"]:194: in function `ProfilePopup'
[string "@Interface\AddOns\WeakAuras\Profiling.lua"]:201: in main chunk

Locals: popupFrame = WADebugEditBox {
 0 = <userdata>
 orig_Show = <function> defined =[C]:-1
 AddText = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:108
 Show = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:102
 orig_Hide = <function> defined =[C]:-1
 Hide = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:94
}
scrollFrame = WADebugEditBoxScrollFrame {
 ScrollBar = WADebugEditBoxScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
bg = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
WeakAuras = <table> {
 IsSpellKnownForLoad = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:777
 normalWidth = 1.250000
 swing_types = <table> {
 }
 frame_strata_types = <table> {
 }
 operator_types = <table> {
 }
 CheckRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:33
 subevent_actual_prefix_types = <table> {
 }
 CheckTalentByIndex = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:635
 anchor_frame_types = <table> {
 }
 form_types = <table> {
 }
 UnitCastingInfo = <function> defined =[C]:-1
 spec_types_2 = <table> {
 }
 author_option_types = <table> {
 }
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:84
 tooltip_count = <table> {
 }
 totem_types = <table> {
 }
 pet_spec_types = <table> {
 }
 race_types = <table> {
 }
 ValidateNumeric = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:694
 CheckMPlusAffixIds = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:712
 versionMismatchPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:44
 event_types = <table> {
 }
 CheckChargesDirection = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:724
 subevent_suffix_types = <table> {
 }
 absorb_modes = <table> {
 }
 StopProfile = <function> defined @Interface\AddOns\WeakAuras\Init.lua:91
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 group_option_types = <table> {
 }
 autoeventend_types = <table> {
 }
 difficulty_types = <table> {
 }
 talent_types = <table> {
 }
 EJIcons = <table> {
 }
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 sound_types = <table> {
 }
 GetHSVTransition = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:266
 group_hybrid_position_types = <table> {
 }
 spec_types_3 = <table> {
 }
 text_check_types = <table> {
 }
 class_color_types = <table> {
 }
 timedeventend_types = <table> {
 }
 blend_types = <table> {
 }
 texture_types = <table> {
 }
 IsClassic = <function> defined @Interface\AddOns\WeakAuras\Init.lua:32
 threat_unit_types = <table> {
 }
 group_sort_types = <table> {
 }
 group_types = <table> {
 }
 GetRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:29
 sound_condition_types = <table> {
 }
 versionString = "2.16.1"
 debuff_types = <table> {
 }
 text_rotate_types = <table> {
 }
 newFeatureString = ""
 weapon_enchant_types = <table> {
 }
 CheckCombatLogFlags = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:730
 anim_translate_types = <table> {
 }
 item_slot_types = <table> {
 }
 anim_color_types = <table> {
 }
 CheckPvpTalentByIndex = 

page 2

Message: Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua:52: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua"]:52: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:543: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:541: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4422: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4323: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4227>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4353: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3887: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3894: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1568: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1554>

Time: Tue Oct 20 13:08:28 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua:52: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua"]:52: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:543: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:541: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4422: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4323: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4227>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4353: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3887: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3894: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1568: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1554>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1695: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1647>

Locals: <none>

page 3

Message: (null)
Time: Tue Oct 20 13:08:28 2020
Count: 3
```

### To Reproduce

1. Enable Lua error logs
2. Reload UI
3. See error

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail
- [ X] Shadowlands

**Was it working in a previous version? If yes, which was the last good one?**

BfA

### Additional Info
Since the /wa command didn't work I tried to search for a solution online and found out how to display LUA error logs. All my addons are up to date, I tried making WeakAuras the only loaded addon and I still get the same error.

**Comment by Stanzilla** [comment]
That looks like an outdated installation, which version do you have installed?

**Comment by Kyle-corbeel** [comment]
I am currently on 3.0.4 I last updated this morning

**Comment by Stanzilla** [comment]
Could you try reinstalling that, please?

**Comment by Kyle-corbeel** [comment]
I still seem to be getting the same error

**Comment by Kyle-corbeel** [comment]
Message: Interface\AddOns\WeakAuras\Profiling.lua:154: attempt to call method 'SetBackdrop' (a nil value)
Time: Tue Oct 20 13:44:56 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\Profiling.lua:154: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\Profiling.lua"]:154: in function <Interface\AddOns\WeakAuras\Profiling.lua:84>
[string "@Interface\AddOns\WeakAuras\Profiling.lua"]:194: in function `ProfilePopup'
[string "@Interface\AddOns\WeakAuras\Profiling.lua"]:201: in main chunk

Locals: popupFrame = WADebugEditBox {
 0 = <userdata>
 orig_Show = <function> defined =[C]:-1
 AddText = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:108
 Show = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:102
 orig_Hide = <function> defined =[C]:-1
 Hide = <function> defined @Interface\AddOns\WeakAuras\Profiling.lua:94
}
scrollFrame = WADebugEditBoxScrollFrame {
 ScrollBar = WADebugEditBoxScrollFrameScrollBar {
 }
 offset = 0
 0 = <userdata>
}
bg = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
WeakAuras = <table> {
 IsSpellKnownForLoad = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:777
 normalWidth = 1.250000
 swing_types = <table> {
 }
 frame_strata_types = <table> {
 }
 operator_types = <table> {
 }
 CheckRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:33
 subevent_actual_prefix_types = <table> {
 }
 CheckTalentByIndex = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:635
 anchor_frame_types = <table> {
 }
 form_types = <table> {
 }
 UnitCastingInfo = <function> defined =[C]:-1
 spec_types_2 = <table> {
 }
 author_option_types = <table> {
 }
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:84
 tooltip_count = <table> {
 }
 totem_types = <table> {
 }
 pet_spec_types = <table> {
 }
 race_types = <table> {
 }
 ValidateNumeric = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:694
 CheckMPlusAffixIds = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:712
 versionMismatchPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:44
 event_types = <table> {
 }
 CheckChargesDirection = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:724
 subevent_suffix_types = <table> {
 }
 absorb_modes = <table> {
 }
 StopProfile = <function> defined @Interface\AddOns\WeakAuras\Init.lua:91
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 group_option_types = <table> {
 }
 autoeventend_types = <table> {
 }
 difficulty_types = <table> {
 }
 talent_types = <table> {
 }
 EJIcons = <table> {
 }
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 sound_types = <table> {
 }
 GetHSVTransition = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:266
 group_hybrid_position_types = <table> {
 }
 spec_types_3 = <table> {
 }
 text_check_types = <table> {
 }
 class_color_types = <table> {
 }
 timedeventend_types = <table> {
 }
 blend_types = <table> {
 }
 texture_types = <table> {
 }
 IsClassic = <function> defined @Interface\AddOns\WeakAuras\Init.lua:32
 threat_unit_types = <table> {
 }
 group_sort_types = <table> {
 }
 group_types = <table> {
 }
 GetRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:29
 sound_condition_types = <table> {
 }
 versionString = "2.16.1"
 debuff_types = <table> {
 }
 text_rotate_types = <table> {
 }
 newFeatureString = ""
 weapon_enchant_types = <table> {
 }
 CheckCombatLogFlags = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:730
 anim_translate_types = <table> {
 }
 item_slot_types = <table> {
 }
 anim_color_types = <table> {
 }
 CheckPvpTalentByIndex = 

page 2 

Message: Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua:52: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua"]:52: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:543: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:541: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4422: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4323: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4227>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4353: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3887: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3894: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1568: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1554>

Time: Tue Oct 20 13:45:42 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua:52: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\Border.lua"]:52: in function `modify'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:543: in function `modifyFinish'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Icon.lua"]:541: in function `modify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4422: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4323: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4227>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4353: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3887: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3894: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1568: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1554>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1695: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1647>

Locals: <none>

page 3 

Message: (null)
Time: Tue Oct 20 13:45:42 2020
Count: 3

**Comment by Stanzilla** [comment]
Where are you getting your WeakAuras download from?

**Comment by Kyle-corbeel** [comment]
Most of them are from Wagio, some I customized myself. Might it be some specific weakauras? If so, is there a way to disable them one by one?

**Comment by Stanzilla** [comment]
I meant WeakAuras itself, from Twitch?

**Comment by Kyle-corbeel** [comment]
yes the twitch launcher

**Comment by Stanzilla** [comment]
Can you try downloading and installing it manually? https://www.wowace.com/projects/weakauras-2/files/3086537 click download here.

**Comment by Kyle-corbeel** [comment]
It works now. I noticed that the zip file I just downloaded had an extra map called WeakAurasArchive, I didn't have that map before.
Thank you for your help and your quick responses. Do you need me to do something more, to figure out what the problem was?

**Comment by Kyle-corbeel** [comment]
When reenabling other addons, I seem to be encountering lua errors there as well. There might be something wrong with my specific twitch installer, since I seem to be one of the only people encountering this problem.

**Comment by Stanzilla** [comment]
I'd blame it on the Twitch app, yeah!
