### ISSUE TITLE
Every frame progress updates could be optimised.

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#2598]
## Describe the bug
When using a progress text that's visibility is set to fgalse, wa continues to update the text every frame. This seems to also be the case for progress type auras, even if the progress they should be showing is either full or empty. 

**Which version of WeakAuras are you using?**
WA 3

**Are you on World of Warcraft Classic or Retail?**
- [x] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I believe this issue is consistent across all past versions 

### Additional Info

For custom TSU auras I'm currently setting the state to status when I don't expect to be needing it to update.

**Comment by mrbuds** [comment]
I have a solution by testing subRegion visibility in RegionPrototype.lua's SubRegionEventsSystem.Notify function

```Lua
  Notify = function(self, event, ...)
    if self.events[event] then
      for _, subRegion in ipairs(self.events[event]) do
        if subRegion:IsVisible() then
          subRegion[event](subRegion, ...)
        end
      end
    end
  end
```

I don't have a clear idea if that solution have undesirable side effects

**Comment by Krytos** [comment]
Any ETA on this?

**Comment by InfusOnWoW** [comment]
There are no ETAs on aynthing.
