### ISSUE TITLE
Error mage frost

### ISSUE THREAD

**Issue by Mithras2801** [WeakAuras/WeakAuras2#2599]
Message: ...terface\AddOns\WeakAurasOptions\WeakAurasOptions-3.0.4.lua:706: attempt to index field 'Private' (a nil value)
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua"]:706: in function `ShowOptions'
[string "@Interface\AddOns\WeakAuras\Transmission.lua"]:407: in function <Interface\AddOns\WeakAuras\Transmission.lua:392>

Time: Tue Oct 20 16:26:49 2020
Count: 1
Stack: ...terface\AddOns\WeakAurasOptions\WeakAurasOptions-3.0.4.lua:706: attempt to index field 'Private' (a nil value)
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua"]:706: in function `ShowOptions'
[string "@Interface\AddOns\WeakAuras\Transmission.lua"]:407: in function <Interface\AddOns\WeakAuras\Transmission.lua:392>

Locals: <none>

**Comment by mrbuds** [comment]
This looks like your installation of weakauras is corrupted, try reinstall it, if that does not solve your issue, please open a new ticket with answers to all questions asked in the issue template.
