### ISSUE TITLE
Multiple conditional expressions

### ISSUE THREAD

**Issue by nb41** [WeakAuras/WeakAuras2#260]
It could be there's a way to do this which I'm just not seeing, so apologies if my real failure is in not Googling well enough. I'd like to be able to have more than one expression for a condition on the Conditions tab.

As an example, I'd like to make a single WA (rather than the 2 I have right now) which shows:

- While on CD, the CD progress as an icon (v. straight forward, right now this is one WA)
- While not on CD *and* when a debuff on a target is over a certain stack count, the icon glows (the other WA, also simple to make, involving 2 triggers: one for the spell CD and one for the debuff stacks)

The need to have the icon glow when the ability is off CD as well as when the stack count is met is my stumbling block. I don't want it glowing just when the debuff stack is up to a certain level if the ability is on CD, and I don't want it glowing if the ability isn't on CD but the debuffs aren't racked up yet. But right now, I can only pick a single expression - eg., a trigger being active (like the one counting the debuff stacks) or the spell not being on CD; I can't choose both simultaneously.

Is there already a way to do this using conditions which I'm not seeing? If not, what it seems I would need is, as right now you can add more than one property change, the ability to add more than one conditional expression.

**Comment by krazyito65** [comment]
Does the current 'conditions' tab not already do that for you?

**Comment by emptyrivers** [comment]
What you're asking for is the ability to link conditions via boolean operations. This is on the to-do list as I recall, but isn't being actively worked on (@InfusOnWoW would be able to answer more accurately).

**Comment by krazyito65** [comment]
As rivers mentioned, yes you cannot do this currently.

For now the only way you could do that with with a custom trigger, which basically returns true when the 2 conditions are met.  Here's an example:

https://wago.io/SyyP6As8-
http://bot.weakauras.wtf/picture_uploads/OqUoKRd6.gif

**Comment by nb41** [comment]
It occurred to me after posting this that was the likely answer. tyvm for the example!

**Comment by krazyito65** [comment]
Another way would be, instead of making a 2nd custom trigger, you could make the condition 'run custom code' based on the cooldown status of the first trigger, and then run custom code (in the conditions tab) to check if the stack count and set the glow.

**Comment by nb41** [comment]
So the problem with the first method (set a second trigger which is a custom function encapsulating both states I want to track) is it seems to take a GCD for it to actually set the icon to glow once the condition is met. Is this a known problem or as-expected? (I can provide a WA string if you want; it's happening on numerous different WAs I have which are like this, so it's not just this one, but that could easily be because I've done them all roughly the same.)

For the second option, is there an example in the wiki of programmatically setting an icon's visual state? I didn't see one, but I wouldn't mind trying the second method to see if it too has the GCD delay to actually fire off the visual change.

**Comment by krazyito65** [comment]
i noticed the gcd thing as weell on mine (you can even see it in my gif) im not usre if thats a problem with my trigger or conditions (i think the conditions)

as for programatically
```
WeakAuras.regions[aura_env.id].region:SetGlow(true) -- on
WeakAuras.regions[aura_env.id].region:SetGlow(false) -- off
```

you have to make sure to disable it somewhere as well

**Comment by nb41** [comment]
Awesome, thanks. And I just realized what my delay was--forgot about GetSpellCooldown returning the GCD as a cooldown. Value. So I'm good to go; thanks again!

**Comment by InfusOnWoW** [comment]
So yeah what the others said, this is planned and likely the next addition to the Conditions. But that still means it'll take a while until I get around to that.

You can do that with the current Conditions, but not in a straight forward way.

- Not on CD => GLOW
- less than x stacks => UNGLOW

That makes the icon glow if you have more or equal than x stacks and the ability is not on cd.

**Comment by Zhyraea** [comment]
please implement this asap xd

**Comment by InfusOnWoW** [comment]
This was just merged.
