### ISSUE TITLE
Pet Behaviour's

### ISSUE THREAD

**Issue by Leggolock** [WeakAuras/WeakAuras2#2609]
Tried to show an Icon whenever I had my pet on Passive/Assist/Defensive

### To Reproduce
I used the template provided for pet behaviours and it wouldn't show the icon, I also tried to create the weak aura without the template to the same issue

Steps to reproduce the behaviour:

1. Go to 'Trigger'
2. Click on 'Type'
3. Scroll down to 'Status'
4. Click on 'Status'
5. Scroll down to 'Pet'
6. Click on 'Pet Behaviour'
7. Choose any Behaviour
8. Won't trigger.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes I tested without any other additional addons enabled.

**Which version of WeakAuras are you using?**
3.0.4

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Was working during WoW patch 8.3

**Comment by InfusOnWoW** [comment]
The pet behaviour trigger is special in that it requires the spells to be on the pet action bar, because there's no good api to check the pet behaviour.
