### ISSUE TITLE
Unit Frames misapplying to offline players after GROUP_ROSTER_UPDATE with custom Trigger State Updater

### ISSUE THREAD

**Issue by stuar7** [WeakAuras/WeakAuras2#2617]
## Describe the bug
Expected icons to stick to their respective raid frames, instead they have a chance of sticking to offline players.

**Do you have an error log of what happened?**
N/A

### To Reproduce
Make any WA that uses a Trigger State Updater and applies an icon to a unit frame. If an offline player is present, icons have a high chance of being misapplied to the offline player when players are moved.

Example WA: Make a raid group with an offline player and type anything in raid chat to apply an icon to the senders raid frame. Move the players around into different groups with the offline player.

`!WA:2!fAv3oTXru46Unk0nPPGPHMs6pRCvPqQRfqsOQQLl8c2GBn)K1girrvMz3D8UJy9oBMzwmqvUXkQkx7hbFDVYpc8emcvLhG8iWtqpZSgAsOvDL1UZpN)pFNZX52np35(LMV0dY3jVFE)xoFFeZRoooqe(IPETlL5Jz2iVd8z0KKXTJiNCcI5B1KsJeKe2rB1UnhlY1pGrttQ5rJVZ7p5ppef7fszBtjXc3vQSzZkodZe1k0ik7xYLlNHdpb5HVgd5ji0y(soCbIjmTjXeHPBB4dp0SNGrccWm(0ZWgT8pg4JDtB3U5Xjy26vQVD1DQBlGnoOugAXE8eCuunFU5R5PU4dXXIga1KJg2ALYnA2QrZYonTtbL4MeHogZCIrDWCthnPURJrrIWlzDBggy1PX2vQxVFA8itWCOhnkTtCdLhy4Yq(Ku(lUzFooQT2NDCQT26nDqrKGy5y9yubs5K5gaY1bhO8xZHTzGIBiyibYWoII8xYgSDVPC6KcHwthVieNpL8EM2CYjy1IZChLiYIIgggBBmFPhYqXKoiboSxkhxN0HicD4EOiSr)SBa9TK8MvLtAhtJXNIrCLE154RFMpe1uu0sfdzCmKc959u0OIWYfT7GiXaVYfL3)6YhiFOCjy5TE3tCZYVHdY(wXpaNmrJNLIyyRQPrrw7fse4bmT3RK8P(hdrEINg4mIRgGJETZgbEWSDGSu)D2SwZQoL3OInNYeYftgh8YYVjj7FoeYXSyu0UGdaIFJrGTAXa0041GhbyRyrvaQrzUoLxT2on6fWi(k7OWQ1pnJ8mO8hcPRUzz2bcQ3HzICSIZvG4pOjMlSwtzXlMs8hwP7by(s7G5eCFL82J4lcnopZbQQYVkn42yfNkv28muQaoERenE30fmR2KatBia01EnNARoOneNwHW8IW7ZoEuH1av(GKXItKk5Edg4nkyyU8Et)YcYRLtUto51LJDMhuu6t7g3OljbV)PxSvLlcL3aGaMYpYuElt5hFRzKJ)k5KUEPCbTJCk5NkNqMxEx5Nl)c5xom7ynIyiOmbonXhElF6rV)30onwxXolkksFhVOLUwPOfuhXrb4IwTU4hhhdb2IwLkvAotl4jIcatlpvnN1YwCOGkoOuauwm7fKw47lDVcWNczm0MYa52XfZSiXw7vUvnivdAvNe2qFbF25S8PAQvpK2wkuXMGkMnJZ5SwE5r6ueIJVKs1ZLEXt1e8BGv97VfbAJGLzV7HrhugQx4LwdlukrNJVqlfVcFjmAadckkuaWEbLMiEfUkHa0GUoXxruBuehFvkuDSGBZu1vVMhs7cxlyP)l86fIIdW()N3FikkvPAbnovj(zhLiFhp65xUdsvMJ(AzPxXWIuwSw(MWPYBBkNgAHfI9oqE3SEP8KVEL1l3S1gnwRLt5ARw06T22QELYRwXrEh5NDEg(BxeJGCJW8KBNLsU0o1EXZLFLzYeQXhhIBM1yEdQp(pFpP9gNFagNuw1ov4O6UfklihdgCWrcv7oOCyMPF1zbr0Uvz4NLIJ9oE7py(sl(q5KmamQU4uOnZAWxDV2WEQJuPXZCtfqCAlOVam(yG64SPL3EOA9tUCE4fSQAtByR2gQP4XVjfn0TP1gsZqI3bXqG3qFtDcSEcT8TZ6S6gIjbHIYYzxsoNACG870VlQF)t2eOtHJ3)OYtO0o5K7o9mYwvLJB07WrHthDyuEs(fkqtkS8YSm4bmIvEY(9ailmgqCSAuvPfkP0pmhljezK8jx0qPj(iXQeUsy(H2kSBOSwwhsxDhYfK)6qVhT3Xn5pzNz)rh53Ai3uULCBt5JmHkEvpvifC4(oDvnmlp0NWvdJZ(7d3OrVluuOCHSbxV9WNF4)FCu(d)Rh)3p`

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/31646052/97043607-52ed4280-15a5-11eb-9276-37a007dd5827.png)
After (Moving the Offine Player Down):
![image](https://user-images.githubusercontent.com/31646052/97043658-613b5e80-15a5-11eb-9e90-410004cb6feb.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
All other addons and WeakAuras disabled.

**Which version of WeakAuras are you using?**
3.0.4

**Are you on World of Warcraft Classic or Retail?**

- [X ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
N/A

**Comment by InfusOnWoW** [comment]
You have to update your states and the contained "unit" variable on GROUP_ROSTER_UPDATE
