### ISSUE TITLE
ENCOUNTER_START, ENCOUNTER_END triggers with load on encounter

### ISSUE THREAD

**Issue by JoeMShanahan** [WeakAuras/WeakAuras2#262]
Looks like ENCOUNTER_START and ENCOUNTER_END events are not passed to trigger handlers when the (un)load condition of the aura is encounter ID.

**Comment by JoeMShanahan** [comment]
Motivation: I want auras to be able to pre-pull and post-pull actions, in order to do this I need a different on load trigger, or have a trigger based on subzone (not ideal).

**Comment by InfusOnWoW** [comment]
I just tested this, and auras do get the ENCOUNTER_START event, but not the ENCOUNTER_END event. That's by design, first auras are loaded/unloaded and then the events are forwarded to the loaded auras.

**Comment by JoeMShanahan** [comment]
@InfusOnWoW In that case, is there scope for "On(Un)Load" actions? I can submit a PR.

**Comment by InfusOnWoW** [comment]
No I don't think OnLoad/OnUnload would add much. Just using a trigger with a broader load condtion works well enough.

**Comment by mgarbacz** [comment]
@InfusOnWoW Do you have any specific suggestions on a broader load condition to use?

I have a weakaura that paints some nameplate textures on the adds on Mythic Aggramar to show their energy (their energy varies on mythic and its important to let in the high energy ones first). These nameplate textures remain after the encounter ends and the weakaura is unloaded, so I need to manually loop over the ones I've painted to specifically remove them using `:Hide()`.

If I use a load condition for the encounter, I don't get the ENCOUNTER_END event as reported here. If I don't use the load condition, the weak aura is always active and that is not ideal. Any ideas on what I could do instead? I'd like to be able to handle wipes during the intermission phase (where the adds will despawn together with the encounter ending) as wiping during the intermission phase is my current use case ;)

Thanks!

**Comment by InfusOnWoW** [comment]
Remove them as soon as the add dies.

**Comment by InfusOnWoW** [comment]
Ah right that doesn't work on wipes. I don't want to change that now though. Might be worth changing for BfA though.

**Comment by mgarbacz** [comment]
Aye, I have it working cleanly with adds that die. It is the wipes that mess everything up.

Understood about your conclusion to not make a change.

I'll have our guildies turn the weakaura on while we work on the fight, and turn it off otherwise. I suppose that's not all that elegant, but it will work fine for us. Thanks much for maintaining the project! Seriously the best addon ever :)

**Comment by InfusOnWoW** [comment]
Are you sure you diagnosed that correctly?

Can you try reproducing with a minimal test case? 

E.g. just watch both events and add 
* print in "init"
* print in "ENCOUNTER_START"
* set a variable in both that the code has run
* and a print in CLEU if either init or ENCOUNTER_START has not run.

Also what was the exact error message?

**Comment by mrbuds** [comment]
![log](https://i.imgur.com/1NCXnXz.png)

"ON INIT" show when i enter raid

with this aura 
```
dqe)haGivQAuQk1PuvYSucDluPQDHe)IsOHHk5yQQwgLuptLsMMQcBtLsnoPsQZPeSouPO7rj6GijluvrpKsYebL6IGyJQu5JGQAKOsPtIKALuQMji5Muc2jf9tPIHcQ0rLkjlfu8uIPIYvbP2Quj(kOkNfvkSxXFLQgmvhwHfdQ4XOQjJuxwYMvL(Ss0OrfNgXQrLkVwLcZMc3wLSBGFROHRKwUs9CvmDORlLTRk(oOKXlvQZtPSEvkA)Ko)Hf5kcDe6WImBObbur6andkQnHe5DcqHCZkM)whHFAm3HfZ)y(htRJ5FmVvm)J5hX8pyeAYz1yyJvDJrupIToVVNcJjxrgaEoZnCNeagXkiMmiWePrOJCOgk2KBq1xDb6kYUwsMaMT1kcwDJr4BhCEXQUrOxPhyfPTspWkYOHZRbs4HhHg5eHQgoJm4rYeCclYbhBmSGriacgwe(2bNxrw3ea(99DmvNAtQz3)LAF02J(c8qHaiO6wQoUBve6zpF7GZR8zWiVea5WjSGbJGBYYL1(ewm)dlcUjlxw7WIW3o48QNdHUIW3o48kcABTIW3o48ksdqWiRgdB1ocF7GZRE02AfPEkagPDQ(gGG5Zi1tbWiCBnmqorwwGAt4foty1be5WzcRoaQ4rYtf50Gt9uaeU76L0DebUqGcQinq9uamYOHZiN1YWGA6tybJW3o48kYBdWJKj476Pa4IQtHcLVu7QRU6QtEvVEkaQULwQ(9qmTQd0MmiW0lmQGHDV6daT6uOqrDKtbu7QRU6QRU6QR(6MaWVRNcGlQ(OTh9f4HcbqWVu7QRU6QRU6QR(OTh9f4Hsb4Nnaw7(do2O6wQoUBLAxD1vx9cqR2vxD1vxTRU6QRo5v96PaO6wAP63Bvhl8jvSEO6a)EiDbIjRhAZ7OgkgeyGa77vh5ua1U6QRU6QRU6Q3V4Pbh1TuDkuOO2vxD1vxD1vxDJj)WqD66GWhAQHT6wQ(PmkE87UEr1PqHYxQD1vxD1vxD1vxTRU6QRU6QRU6Kx1PRdcFOPg2QJCkGAxD1vxD1vxD1vxD1vFDta431tbWfvF02J(c8qPa8ZgaRD)bhBCr1hT9OVapuiac(LAxD1vxD1vxD1laTAxD1vx9cqR2laDK6Pa4jIvDSWNuX6HQd87H0fiMSEOnVJAOyqGbcSxuDiMw1bAtgey6fgvWWIWZP4VrK6PayeW4QoHfmYPbN6PaO0EFjDhP3kQewVWOcgwe6coT3xMT1kc3cbk4Eh0qfmsdGBYYL1oSGbJqtoCxdWJKNkYWWiYGhjpfBtwUS2wysxXK7)5kye(jGMGKj4ewWieawBWWOl1(qMGyUqeURDqYRTiqb5owKtz8c3jbGr(SdJ1Xcri0ryqeM6CV6qmTQd0MmiW0lmQGHfbwZnn82J1iWBUPH3ESg5DpUkb3dCeZ)idapN5(U94Qy2wRiIvWabIzKbGCnqYeewKdo2yyrqBRveWeurOB7bsMGE02Af5u8ta9jyKRbbewe02Afbmbve62EGKjOhTTwrof)eqFcg5LaihoHfbTTwratqfHUThizc6rBRvKtXpb0NGbJ8obyK72KBQEx1g07bouNXIalcnYjM))u4IlU46)2w)B9h3(wr6UZ77PWyYveofzjhmM))uwyHfwyH)p(V9c36pYlP7IgEeAKtmTMlUIymh0HfbhgfaToSixndKewWGrANQhup1oWjcomkagwKRMbsclyWi8gJZjSixndKewWGriGL7zBnSixndKewWGrANQVa8ZgaRnHoFgHM8(s4BgOTWIC1mqsybdgzp4RWIC1mqsybdgPa8ZgaRnHoI1)F8rK1NvCyuamSixndKewWGroRfFyrUAgijSGbJSNgvyrUAgijSGbJ8o4rYeewKRMbsclyWihYnRWIC1mqsybdgmsBBeHdIRhUPfTiSglNuitlk3Gb)6ggyxzX)GrorGD9e5jM)Fy9FWe
```

**Comment by InfusOnWoW** [comment]
Thanks, that's interesting. I'll do check what's going on there.

**Comment by InfusOnWoW** [comment]
Okay I found the problem, I'll work on a fix later today.

**Comment by InfusOnWoW** [comment]
This is the commit that broke it: https://github.com/WeakAuras/WeakAuras2/pull/462/commits/0bfb77d508af46d6080ba2ad26aa93cba60faafd which fixed https://github.com/WeakAuras/WeakAuras2/issues/461

**Comment by InfusOnWoW** [comment]
Fixed again
