### ISSUE TITLE
how fix pls ?

### ISSUE THREAD

**Issue by Dobi83** [WeakAuras/WeakAuras2#2620]
Message: [string "--[==[ Error in 'Gift of the Titans':'custo..."]:3: attempt to index field 'triggerState' (a nil value)
Time: Fri Oct 23 23:11:45 2020
Count: 2
Stack: [string "--[==[ Error in 'Gift of the Titans':'custo..."]:3: attempt to index field 'triggerState' (a nil value)
[string "--[==[ Error in 'Gift of the Titans':'custom text' ]==] return function()
    if aura_env.state then
        local t = WeakAuras.triggerState[aura_env.id].triggers
        if t[1] then
            return "UP"
        elseif t[2] then
            return "CD"
        end
    end
end"]:3: in function <[string "--[==[ Error in 'Gift of the Titans':'custo..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4060: in function `RunCustomTextFunc'
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\SubText.lua"]:288: in function `?'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:34: in function `Notify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3839: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3836>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3922: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3889>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4004: in function `UpdatedTriggerState'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3776: in function `UpdateFakeStatesFor'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3749: in function `FakeStatesFor'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1847: in function `PriorityShow'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1640: in function `PriorityShow'
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:781: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:770>

Locals: <none>

**Comment by mrbuds** [comment]
You have an aura called "Gift of the Titans" that use a function that was removed.

What the aura does do not require custom code, you can make 2 texts subregions and use conditions to show either text1 or text2.
