### ISSUE TITLE
ADDON_ACTION_BLOCKED

### ISSUE THREAD

**Issue by Zonk1987** [WeakAuras/WeakAuras2#2622]
## Describe the bug

**Do you have an error log of what happened?**

```plaintext
1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' hat versucht die geschützte Funktion '<unnamed>:ClearAllPoints()' aufzurufen.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:45: in function `SetAnchorPoint'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1070: in function `DoPositionChildrenPerFrame'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1186: in function `DoPositionChildren'
[string "@WeakAuras\Animations.lua"]:20: in function <WeakAuras\Animations.lua:15>
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.0.4-15-gcdff494

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by Stanzilla** [comment]
not a WA bug
