### ISSUE TITLE
Fire mage Ignite icon no longer shows damage count, dealed to the target. It worked yesterday, but no more.

### ISSUE THREAD

**Issue by mrPrizrak** [WeakAuras/WeakAuras2#2625]
## Describe the bug

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
Well, without any information, e..g the aura that has changed behaviour, we can't figure out what the problem is.
