### ISSUE TITLE
Add alpha setting to model aura

### ISSUE THREAD

**Issue by WareditorGit** [WeakAuras/WeakAuras2#2626]
You can modify the alpha of a model aura inside of a fade animation but you can't do it in the display tab or in the condition tab.
It would be nice to have a setting the model settings and an associated property change in the conditions tab.

**Comment by InfusOnWoW** [comment]
Yes,that would be nice. Unfortunately models are react rather strange with settings of alpha. I wouldn't be suprised if there are bugs with the fade animation and a aura that has a alpha setting.

So I'd rather not open that can of worms further.

**Comment by WareditorGit** [comment]
I understand it sometimes doesn't work because of how the model is made. However there are many cases where it works and is useful. Also it's kinda frustrating since when you add a model to another aura you can change the alpha there as shown in the picture below.

![model_alpha](https://user-images.githubusercontent.com/38940363/99925512-c0c09180-2d3e-11eb-9d6f-42a1ee255f0c.PNG)

**Comment by InfusOnWoW** [comment]
Yes and getting that to work involved several revisions. I don't want to do that again for a minor feature.
