### ISSUE TITLE
Error importing WA updates

### ISSUE THREAD

**Issue by yajinni** [WeakAuras/WeakAuras2#2627]
After updating some WA's with the companion. Using the latest release and beta, when i click the circle ingame to update them i get this error:

6x WeakAuras\Transmission.lua:1305: attempt to get length of field 'controlledChildren' (a nil value)
[string "@WeakAuras\Transmission.lua"]:1305: in function <WeakAuras\Transmission.lua:1255>
[string "@WeakAuras\Transmission.lua"]:1704: in function `Import'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:815: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:812>

Locals:
data = <table> {
 controlledChildren = <table> {
 }
 borderBackdrop = "Blizzard Tooltip"
 authorOptions = <table> {
 }
 yOffset = 0
 anchorPoint = "CENTER"
 borderColor = <table> {
 }
 url = "https://wago.io/IX1t89U6H/24"
 actions = <table> {
 }
 triggers = <table> {
 }
 internalVersion = 38
 animation = <table> {
 }
 version = 24
 subRegions = <table> {
 }
 load = <table> {
 }
 backdropColor = <table> {
 }
 scale = 1
 border = false
 borderEdge = "Square Full White"
 regionType = "group"
 borderSize = 2
 ignoreOptionsEventErrors = true
 borderOffset = 4
 semver = "1.0.23"
 tocversion = 90001
 id = "Nexus Sx Ny'alotha"
 frameStrata = 1
 anchorFrameType = "SCREEN"
 uid = "NZ5zkpjxTG7"
 xOffset = 0
 config = <table> {
 }
 conditions = <table> {
 }
 borderInset = 1
 selfPoint = "BOTTOMLEFT"
}
children = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
}
target = <table> {
 sparkWidth = 2
 sparkOffsetX = 0
 color = <table> {
 }
 preferToUpdate = false
 customText = "function() 
    if aura_env.state and aura_env.state.tooltip1 then
        return AbbreviateNumbers(aura_env.state.tooltip1)
    end
end

"
 yOffset = -11.000046
 anchorPoint = "CENTER"
 zoom = 0.300000
 borderBackdrop = "None"
 sparkRotation = 0
 sparkRotationMode = "AUTO"
 url = "https://wago.io/IX1t89U6H/22"
 actions = <table> {
 }
 triggers = <table> {
 }
 icon_color = <table> {
 }
 internalVersion = 38
 useAdjustedMin = false
 animation = <table> {
 }
 backdropInFront = false
 xOffset = 0
 barColor = <table> {
 }
 stickyDuration = false
 authorOptions = <table> {
 }
 semver = "1.0.21"
 version = 22
 subRegions = <table> {
 }
 height = 33
 customTextUpdate = "update"
 load = <table> {
 }
 sparkBlendMode = "ADD"
 useAdjustededMax = false
 backgroundColor = <table> {
 }
 selfPoint = "CENTER"
 desaturate = false
 icon = false
 useAdjustedMax = false
 smoothProgress = true
 useAdjustededMin = false
 regionType = "aurabar"
 borderInFront = true
 ignoreOptionsEventErrors = true
 icon_side = "RIGHT"
 sparkOffsetY = 0
 backdropColor = <table> {
 }
 sparkHeight = 35
 texture = "Flat"
 uid = "UKmGSuUcVAo"
 sparkTexture = "WeakAuras\Media\Textures\Square_FullWhite"
 auto = true
 tocversion = 80300
 id = "Maut - Mana Pool"
 anchorFrameType = "SCREEN"
 frameStrata = 1
 width = 300
 alpha = 1
 config = <table> {
 }
 inverse = false
 sparkHidden = "NEVER"
 orientation = "HORIZONTAL"
 conditions = <table> {
 }
 spark = true
 sparkColor = <table> {
 }
}
oldParent = <table> {
 sparkWidth = 2
 sparkOffsetX = 0
 color = <table> {
 }
 preferToUpdate = false
 customText = "function() 
    if aura_env.state and aura_env.state.tooltip1 then
        return AbbreviateNumbers(aura_env.state.tooltip1)
    end
end

"
 yOffset = -11.000046
 anchorPoint = "CENTER"
 zoom = 0.300000
 borderBackdrop = "None"
 sparkRotation = 0
 sparkRotationMode = "AUTO"
 url = "https://wago.io/IX1t89U6H/22"
 actions = <table> {
 }
 triggers = <table> {
 }
 icon_color = <table> {
 }
 internalVersion = 38
 useAdjustedMin = false
 animation = <table> {
 }
 backdropInFront = false
 xOffset = 0
 barColor = <table> {
 }
 stickyDuration = false
 authorOptions = <table> {

**Comment by InfusOnWoW** [comment]
We obviously need your settings + information which auras you are trying to update. Please provide them.
