### ISSUE TITLE
Easy option to display GCD/Range/Resource options for spell icons

### ISSUE THREAD

**Issue by GadgetC** [WeakAuras/WeakAuras2#2629]
It would be extremely nice if there was an easy option(s) to display a spell/item icon as it would be displayed on the action bar.
Specifically, I am requesting the following to be preset options:
- The spell icon turns red when it is out of range
- The spell icon is dimmed when you do not have the resources to cast it
- The GCD cooldown swipe is displayed on the spell icon

**Additional context**
Doing all of the above is apparently possible already, but for someone like me with no programming/scripting knowledge, I am really struggling to figure out how to implement all these things for an icon which feels like it should be easy to do.

**Comment by InfusOnWoW** [comment]
There's no need for any programming knowledge to use these.

The spell cooldown trigger pvovides conditions to apply any change you want for out of range, or resource checks.
It also has a extra option for displaying the gcd.

The New From Template / Abilities section can create icons that have te first two as a default.
