### ISSUE TITLE
Aura trigger with unit=group and multiple auras only trigger on the last one

### ISSUE THREAD

**Issue by mrbouyou** [WeakAuras/WeakAuras2#263]
Let's say i play a shaman, make new icon
-> trigger: "Aura"
-> Aura(s): "Riptide" or "Renew"
-> Unit: "player"
-> Aura Type: "Buff"

I cast riptide on me: icon show (this is normal)

Now if i switch **Unit: "Group"** and cast riptide on me, aura won't work.
If i remove the 2nd aura, "Renew", it works back again

**Comment by InfusOnWoW** [comment]
The group trigger only works if you are in a group. (iirc)

**Comment by mrbouyou** [comment]
It's a simple test case i made because i had problem with an other aura i use in group only working with the last "aura name"

**Comment by InfusOnWoW** [comment]
I'm not 100% sure what you are repoting. Are you saying that the group trigger works if you have just "Riptide" there, but not if you have both "Riptide" and "Renew"?

That's a bit strange then. I'll take a look.

**Comment by mrbouyou** [comment]
It works only if Riptide is the last aura of the list

**Comment by InfusOnWoW** [comment]
Fixed in the latest alpha/next release.
