### ISSUE TITLE
Conditions Tab: can't assign Specific Unit

### ISSUE THREAD

**Issue by Bibimbapi** [WeakAuras/WeakAuras2#2630]
hi. thank you for everything you do for the WoW community. 

Issue: When I create a 'Combat-Log-Spell-Cast-Success' Trigger, set 'Source Unit' to 'Specific Unit', and then go to the Conditions tab and set: 'If Trigger 1' -> 'Source Unit' = 'Specific Unit', then there is no field where I can enter the name of the Specific Unit (e.g. arena1, arena2 etc.). 

I am trying to make the following Condition: if the 'Specific Unit' is arena1, then do X and if the 'Specific Unit' is arena2, then do Y.

It's possible to do this:
if the 'Source Unit' = 'Specific Unit', then do X - but it won't let me specify which Specific Unit. 

My guess is that checking what any Specific Unit does is so CPU intensive that you disabled working with it within the Conditions tab? if that's not the case, then I would be very grateful if you could add a field within the Conditions tab, that makes it possible to enter whatever Specific Unit you want to work with. 

cheers and thank you again for this amazing addon.

**Comment by InfusOnWoW** [comment]
That's not how teh trigger work. You need to specifiy the unit that you want to check against in the trigger.

**Comment by Bibimbapi** [comment]
in the trigger I have my base case. if, say, arena1 is the specific unit and arena1 casts a spell, then my weakaura triggers. 

then, under the conditions tab, I would like to change a property of the aura, depending on which'Specific Unit' cast the spell. 

in my base trigger the specific unit is arena1 and shows the standard aura on activation. within the conditions tab, I would now like to change a property of the aura, whenever the spell is cast by a different specific unit, like arena2 or arena3. 

I want to be able to check 'Specific Unit' vs. 'Specific Unit', not 'Specific Unit' vs. 'Player' or 'Specific Unit' vs. 'Target'. please let me know if that's not possible at the moment. 

cheers and thank you for taking the time to reply!

**Comment by InfusOnWoW** [comment]
I understand what you want, but that's not how WA works. You can't retroactively change what the trigger is tracking.
