### ISSUE TITLE
UNIT_SPELLCAST_SENT:player does not trigger custom function

### ISSUE THREAD

**Issue by spamwax** [WeakAuras/WeakAuras2#2632]
## Describe the bug

`UNIT_SPELLCAST_SENT` should be sent to custom trigger function if it's filtered using `:player` format, but it is not sent and trigger function is not called.

**Do you have an error log of what happened?**
No error is reported by bugsack or bug-grabber

### To Reproduce

1. Create an aura
2. Set trigger to Custom->Event
3. In Event(s) field enter `UNIT_SPELLCAST_SENT:player`
4. In Custom Trigger enter a `print` for debug:
```lua
function(event, arg1)
    if not arg1 then arg1 = "empty" end
    
    print(string.format("(%s), arg1: >>%s<<", event, arg1))
    return true
end
```
5. Set Hide to Timed and enter any number, I used 3
6. Start casting a spell
7. No message is printed!

However if `:player` is removed and I cast a spell I see something like this (using above funtion)
```
(UNIT_SPELLCAST_SENT), arg1: >>player<<
```

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, WA is the only addon

**Which version of WeakAuras are you using?**
3.0.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail
- [X] Beta (Shadowlands 9.0.2.36292)

**Was it working in a previous version? If yes, which was the last good one?**
I am not sure! My limited tests showed that despite [event's documentation](https://wow.gamepedia.com/UNIT_SPELLCAST_SENT) this event is only fired when player starts casting but even if that is true adding a `:player` should not completely ignore the event.

**Comment by InfusOnWoW** [comment]
That's not a bug. The :unit suffix uses the RegisterUnitEvent functrion, whereas without the suffix it is using the RegisterEvent function.

The former function should be used for all events that can be filtered by unit. UNIT_SPELLCAST_SENT does not fall into that category.

**Comment by spamwax** [comment]
Thanks for info, where do I find info/list of events that fall into either category?

**Comment by InfusOnWoW** [comment]
I'm not sure blizzard has documented that somewhere.

**Comment by spamwax** [comment]
So old fashion trial and error I guess.
