### ISSUE TITLE
Weakauras blocking guild notes

### ISSUE THREAD

**Issue by LordKrycek** [WeakAuras/WeakAuras2#2633]
## Describe the bug
When Weakauras is active and I try to change or add a character note in guild (to anyone); upon hitting 'Accept' it gets blocked. Disabling the offending addon disables the Weakauras main module.

**Do you have an error log of what happened?**
Yes:-
https://pastebin.com/RxCh7RYq

1x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'SetNote()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetNote'
[string "@FrameXML\StaticPopup.lua"]:2776: in function `OnAccept'
[string "@FrameXML\StaticPopup.lua"]:5147: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

### To Reproduce
As described above.

1. Go to Guild page by pressing J, select the 'Roster' tab, click on any member, click into their 'Note', type the entry, press 'Accept'. =error.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I have tested with only Weakauras active. The problem is not repeating; however, the issue doesn't happen 100% of the time so it's hard to pinpoint the issue.

I do not believe that this is down to Weakauras alone, since I have also caught an addon called 'World Quest Tracker' causing the same error (but only once). 99% of the time it is W.A.

**Which version of WeakAuras are you using?**
3.0.4.

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I don't know as WeakAuras is a relatively new thing for me.

### Additional Info
n/a

**Comment by InfusOnWoW** [comment]
That's a problem in one of your auras or some of your other addons, most likely one that does something with the GuildFrame.
