### ISSUE TITLE
Support for "maintank" tag in triggers

### ISSUE THREAD

**Issue by AdmyraYakar** [WeakAuras/WeakAuras2#2635]
Hello,

I'm aware that WeakAuras2 is not ment for creating stand alone unit frames, but it is a very effective tool to attach additional information to them!

For example I created a WeakAura, that displays all incoming heals on my target as progress bars. Here is a screenshot:
![target incoming heals](https://user-images.githubusercontent.com/73445188/97127211-46015800-1739-11eb-9c00-d2f7ba76e3a1.png)

With the Blizzard UI and several other unit frame addons (for example Pitbull, or ElvUI) you can tag units as "main tanks" and they will appear in a seperate frame. 
From a healers perspective you want to have more information about whats happening with the tanks, so you might make this frame bigger and display more information on it than your normal raid frames. Also you will likely heal with mouse over casting and not have the tank in your target.

Here is a little concept what I want to do:
![Concept](https://user-images.githubusercontent.com/73445188/97132237-97641400-1746-11eb-97b6-7073abdb4fbb.png)

All of this can already be done with WeakAuras for a specific UID like raid1, party3, or target, but not for the main tank frames. So i kindly ask for an option in the trigger setup to relate a WA to a main tank :-)

Since there is no UID like "maintank1", but only a tag, I was thinking of something like getting the UnitID, or UnitName from the parent frame? But what the heck do I know :) Maybe there is a better approach.

Best regards
Admyra

**Comment by InfusOnWoW** [comment]
Classic has no bult-in concept of "main tanks" and as such there's no good way to support this.

**Comment by mrbuds** [comment]
On event `PLAYER_ROLES_ASSIGNED` you can get the roles MAINTANK or MAINASSIST
```
local unit = "raid2"
local raidID = UnitInRaid(unit)
local role = select(10, GetRaidRosterInfo(raidID))
print(UnitName(unit), role)
```

**Comment by mrbuds** [comment]
It is possible to add a filter to triggers with unit=[party/raid/smartgroup] for maintank or maintarget

But they still not have a dedicated unitID, and their is no notion of order between them (no maintank1, maintank2 etc..)
The ordering you see in pitbull is specific of how it's implemented in this addon.

I don't think adding filters for maintanks/maintargets will solve your use case, you better make patches for pitbull and contribute to improve their code with your ideas.

**Comment by AdmyraYakar** [comment]
> It is possible to add a filter to triggers with unit=[party/raid/smartgroup] for maintank or maintarget
> 
> But they still not have a dedicated unitID, and their is no notion of order between them (no maintank1, maintank2 etc..)
> The ordering you see in pitbull is specific of how it's implemented in this addon.
> 
> I don't think adding filters for maintanks/maintargets will solve your use case, you better make patches for pitbull and contribute to improve their code with your ideas.

Thank you very much for taking the time to look into this request and giving me this information. Just as info: In Pitbull the order of the maintanks can be configured (index, group, class, name) and other UF addons will probably do it differently, so there is no universal approach to it and understandably this is out of scope of WeakAuras. 

I see some use cases for the filtering, but alas they are very specific and don't justify an additional option. (thinking of some combatlog filtering for casts/attacks on the maintanks, but tbh I would need to test if this is actually benefitial or just more information overkill)

I still think that those cast progress bars on maintanks would be helpful. Especially with Patchwerk when healers must use 2.5 cast and the casts must be "offset" (not sure, if this is the correct word in english... heals must hit every second or so and healers must delay their cast in timing with the other healers). 
So if someone is looking for a good idea for an addon, create something that indicates the heal casts on the tanks (progress bars are probably the best option) and name it **Patchwerk Healer Helper** or so :D 

Cheers
Admyra
