### ISSUE TITLE
Models in a group are not scaling

### ISSUE THREAD

**Issue by LootFever** [WeakAuras/WeakAuras2#2638]
## Describe the bug
I have a group that contains textures and models.
When I use the scale function in the group tab the textures are being scaled just fine 
but the models keep their size and just get pushed together.

**Do you have an error log of what happened?**
No error received.

### To Reproduce
Selecting the group tab,
Moving the scale slider.

**Screenshots**
scale 1.0: https://imgur.com/a/PVerGff
scale 0.3: https://imgur.com/a/2ZQXNZR

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes
**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Not tested on a previous version.

**Comment by InfusOnWoW** [comment]
Please include the actual aura you are using to test this.

**Comment by LootFever** [comment]
https://wago.io/VT3LqAjAJ
