### ISSUE TITLE
Editing custom checks on a dynamic group can't use expanded code editor

### ISSUE THREAD

**Issue by capoferro** [WeakAuras/WeakAuras2#2642]
## Describe the bug
When clicking "expand" on a custom check in a condition, the editor is empty if there is code in the check already, and if new code is added, that new code is not persisted to the check upon pressing done.

**Do you have an error log of what happened?**
 No errors are triggered

### To Reproduce

1. Create a dynamic group with multiple auras contained
2. Select the dynamic group
3. Navigate to the Conditions tab
4. Create a new condition
5. Add a Custom Check (in my case, I have Any of: Custom Check, In Combat)
6. Add code to Custom Check code editor.
7. Press Expand.
8. Note that there is no code contained in the expanded editor.
9. Add new code to the expanded editor.
10. Press Done.
11. Note that the newly added code is not persisted to the Custom Check.

**Which version of WeakAuras are you using?**
3.0.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Comment by InfusOnWoW** [comment]
I did find the issue, but your steps to reproduce are very incomplete. Next time please just include a aura that skips to the important bits.
