### ISSUE TITLE
Add possibility of loading if in instance or in combat.

### ISSUE THREAD

**Issue by capoferro** [WeakAuras/WeakAuras2#2643]
Currently, Load triggers are `and` conditionals. I can tell something to load if I am both in an instance and if I'm in combat, but it's common to want to load something both if I am in an instance or if I'm in combat.

The current workaround for this is to add a Custom Check function to check if in instance `or` if in Combat and set the Alpha % accordingly.

The custom check I currently use is this (or the inverse):

```lua
function()
    -- Snippet: Is in instance
    local isInInstance, instanceType = IsInInstance()
    if(isInInstance == nil) then
        return false;
    elseif(instanceType == 'party' or instanceType == 'raid') then
        return true;
    else
        return false;
    end
    
end
```

**Comment by InfusOnWoW** [comment]
Adding the ability to combine load options would complicate the UI too much. Using triggers, whether built-in, or custom is fine for it.
