### ISSUE TITLE
Importing Weakaura ingame via Sharing fails and produce LUA Error 

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#2645]
## Describe the bug

 If I try to import a Weakaura via ingame share function, it will not be completed and producing LUA errors:

**Do you have an error log of what happened?**

```plaintext
1x WeakAuras\Transmission.lua:1812: Error creating thumbnail
[string "=[C]"]: ?
[string "@WeakAuras\Transmission.lua"]:1628: in function <WeakAuras\Transmission.lua:1419>
[string "@WeakAuras\Transmission.lua"]:1812: in function <WeakAuras\Transmission.lua:1787>
[string "=[C]"]: ?
[string "@Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@BugSack\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:218: in function `OnReceiveMultipartLast'
[string "@BugSack\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:256: in function <...faceBugSack\Libs\AceComm-3.0\AceComm-3.0.lua:246>
```

### To Reproduce

1. Friend/other shares WA via Ingame chat
2. Click on ingame Link to import
3. Loading wioll not be finished; LUA Errors

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

3.0.5
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

I don't exactly know, but I guess it worked before 3.0 release
### Additional Info

WA String of Example: 
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5454557/WeakAuras.zip)

`!WA:2!DnvZUrorq4mkhIKfcTmifwK2dExGCJvWUICMXdE2ey(l2omlCzCB3Lh3lE62Q62tYKJwCGRKhH5aN408iWtGvepb7H9ahZtavBh2d0x6QQUQ6RQVQ6EJ6VUpVp)3CrvLPqibC2LrJpFQFDMsAcf3axSZOs3aOwOKpU3YF)wnuKnxjKMeVzrrZMCNoNXvx96zzzAWC4EUqxwW2gbxBUF6m35(rUHxozYSP(FhEDNt9EiMFQt9jhSdHvu(J2wcEgkWGuvHc)(dPdUTZPZ(w()4DaD2ZKP5kSReg6pnYpO8rPvAJATfZll5mdKu1E9wwfzMzePleCtU3asfzPgcl9PbAddnoEcPW4KKrx6CNYhlwjvimRS1j)nG04JOc1X3rjJa(HxCUNWhqjR4h7iNj4BOIqKT1BS)OOBzsHfyL80MpzKNX2zsLeUJxHTMxAnHAivj56)cyAi0GGCLj)OARMLlAEQ3AMqoQXT5PnpR5ZA(8JA(cs8t))wEMGx(XlyyHk9xCNdg3jcTwixvBqXQvemF4j4dIVRXnHACtL(T6QeW2FHvzzIR3VC4GWOLHrdcI2xPHLBGCrAbKx)FLC)VoO1)DdPAw0Ycbs2Aq706)AvfXi8CSs26MNL8R1LqrX5CTZ7HBoceCbHZ9hp2RIi)e7(cG3AtcRqSbI3zfpJPPwjFhNMMzzw(apZF88rxo(wcOUUXP8JSJZnquN(efh(Zd2NHuzr8jZWo8(U9Lrwt2KKeomW3F6lQe89N(QZo)gZfN(g4N9Sl8LpAekUX9Ikg3gRBuu9vkKVazL1lEqiHMyzIvo772Hh2UP2RxVd3L(EAXXRqX4)XD22OemjmJHiY2g0YnyEIHvquXXbRRkmcNMVmpiTGP1NKyhBfaUyqW4zd)HM5h7nzWR8JBJT1LypIstpPj4i6XJI3Xf00lLsZwhKIL(ix64PPFUh3mpRoRaUwKuaX16uqYqHkoOKw73ghWO1nwCI5kQq2g)IYnLX7ObdWB)R8RFqFDWlF(x98VP)M)(1)7d`

**Comment by mrbuds** [comment]
Can you export the string of that aura and paste it here ?

**Comment by mrbuds** [comment]
You didn't answer to the question `Which version of WeakAuras are you using?` (we need to know if it's release, beta, alpha ..)

**Comment by Breakerzeus** [comment]
Sorry, added the actual version and the string. This happens with every aura, that is shared ingame. It works as soon as you open the addon via minimap button or /wa. then the import is valid.

**Comment by mrbuds** [comment]
Can you include your `WeakAuras.lua` file from `World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\` ?

**Comment by Breakerzeus** [comment]
Updated with the file.
