### ISSUE TITLE
Weird error, no idea what it is.

### ISSUE THREAD

**Issue by griddark** [WeakAuras/WeakAuras2#2647]
## Describe the bug
Recently I noticed during combat that the custom weakaura rotation I've made for different specs wouldn't show properly. When attacking a single mob, the error still occurs, but I don't notice the actual issue with the rotation.

**Do you have an error log of what happened?**

```plaintext
23x WeakAuras\AuraEnvironment.lua:98: attempt to index local 'input' (a number value)
[string "@WeakAuras\AuraEnvironment.lua"]:98: in function <WeakAuras\AuraEnvironment.lua:91>
[string "=(tail call)"]: ?
[string "@WeakAuras\WeakAuras-3.0.5.lua"]:4221: in function <WeakAuras\WeakAuras.lua:4212>
[string "@WeakAuras\WeakAuras-3.0.5.lua"]:4319: in function `ReplacePlaceHolders'
[string "@WeakAuras\RegionTypes\Text.lua"]:172: in function `Update'
[string "@WeakAuras\WeakAuras-3.0.5.lua"]:3841: in function <WeakAuras\WeakAuras.lua:3840>
[string "@WeakAuras\WeakAuras-3.0.5.lua"]:3926: in function <WeakAuras\WeakAuras.lua:3893>
[string "@WeakAuras\WeakAuras-3.0.5.lua"]:4008: in function `UpdatedTriggerState'
[string "@WeakAuras\GenericTrigger.lua"]:716: in function `ScanUnitEvents'
[string "@WeakAuras\GenericTrigger.lua"]:865: in function <WeakAuras\GenericTrigger.lua:861>

Locals:
input = 94.755854
size = 2
output = ""
i = 1
(*temporary) = nil
(*temporary) = 94.755854
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'input' (a number value)"
```
and 

```plaintext
1x WeakAuras\AuraEnvironment.lua:98: attempt to index local 'input' (a number value)
[string "@WeakAuras\AuraEnvironment.lua"]:98: in function <WeakAuras\AuraEnvironment.lua:91>
[string "=(tail call)"]: ?
[string "@WeakAuras\WeakAuras-3.0.5.lua"]:4221: in function <WeakAuras\WeakAuras.lua:4212>
[string "@WeakAuras\WeakAuras.lua"]:4319: in function `ReplacePlaceHolders'
[string "@WeakAuras\RegionTypes\Text.lua"]:172: in function `Update'
[string "@WeakAuras\WeakAuras.lua"]:3841: in function <WeakAuras\WeakAuras.lua:3840>
[string "@WeakAuras\WeakAuras.lua"]:3926: in function <WeakAuras\WeakAuras.lua:3893>
[string "@WeakAuras\WeakAuras.lua"]:4008: in function `UpdatedTriggerState'
[string "@WeakAuras\WeakAuras.lua"]:3780: in function `UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras.lua"]:3753: in function `FakeStatesFor'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1847: in function `PriorityShow'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1640: in function `PriorityShow'
[string "@WeakAurasOptions\WeakAurasOptions-3.0.5.lua"]:658: in function <WeakAurasOptions\WeakAurasOptions.lua:627>
```

### To Reproduce

1. While using this rotation https://wago.io/BfaNNtcXG
2. Attacking a mob would causes the error. 
3. The Second error was caused by opening options.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
The error occurs even if weakauras is the only addon loaded.

**Which version of WeakAuras are you using?**
Version: 3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I'm pretty sure it's been happening since the 9.0.1 update, I just didn't notice?

### Additional Info
I have tried different characters using different rotations, all produce a similar issue.

**Comment by griddark** [comment]
It was my fault, figured it out.

**Comment by mrbuds** [comment]
Can you give an hint on what caused it for reference if anyone else have this issue ?

**Comment by griddark** [comment]
In a weakaura for target health I used %1.percenthealth
and in Format options I used string instead of number.

[image: image.png]

I only noticed because I was getting so many errors it was causes other
weakauras to mess up.

**Comment by mrbuds** [comment]
Thank you for the information, i reopen ticket to remember us to add a type check there, using default options should not raise lua errors.
