### ISSUE TITLE
using WeakAuras.ScanEvents() onHide stops weakaura from triggering

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2649]
## Describe the bug
TSU WA no longer triggering after onHide WeakAuras.ScanEvents() code is fired.
The odd thing is that the code still prints from trigger and onHide.

**Do you have an error log of what happened?**
no error

### To Reproduce

1. Import https://wago.io/D8NEd21cL
2. (optional) As soon as you close options, start moving to retrigger the WA just to prove that it works.
3. Let it hide naturally and notice how a) onHide doesn't retrigger it and b) how it doesn't trigger when moving
4) check prints whenever you move and 3s after moving

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
no idea

**Comment by InfusOnWoW** [comment]
I think that falls under the: "Don't do that then".

In OnHide WA is in the middle of synchronizing the state with the actual aura. Callling ScanEvents in that state is not a good idea and should be avoided.
