### ISSUE TITLE
[Idea] Time conditions for Status>Cast Trigger

### ISSUE THREAD

**Issue by babbelnedd** [WeakAuras/WeakAuras2#265]
An additional option to check the duration or remaining time. Basically like so

    [x] duration [operator] [int field]

    [x] remaining [operator] [int field]

    [x] Cast Type [string field]

--------------

Background: I created a castbar for my target and want to hide it if the spellcast is ridiculous long. Some NPCs do that.

**Comment by InfusOnWoW** [comment]
I added the remaining time check to the trigger page. Cast Type is already there. And we don't have duration on any trigger.
