### ISSUE TITLE
Progression Bar for Warrior Rage

### ISSUE THREAD

**Issue by Warmouser** [WeakAuras/WeakAuras2#2653]
**What did you expect to happen and what happened instead?**
Hi I found a WeakAura on Wago.io for my Rogue to track Energy. I liked it and rewrited it for my Warrior for Rage. I only changed the Power Trigger from Energy to Rage and in the Load Tab from Player Class: Rogue to Warrior. The WA uses a Model in the Background of the Bar.

On my Rogue the WA works just fine but on my Warrior everytime i reload the game or start the game with 0 Rage the Background Model does not load.

**To Reproduce:**

1. Install the WeakAura i link here (or Import from String below): https://wago.io/zt5WCvtnK
2. Log onto a Warrior.
3. Attack a TrainingsDummy
4. The RageBar does not show a model in the Background
5. Leave Combat and open WeakAura quickly (so u still have Rage).
6. After WeakAura opened completly close it again.
7. Attack TrainingsDummy again.
8. Background should load now.

**Screenshots**
RageBar with Background:
![image](https://user-images.githubusercontent.com/73718109/97748946-90465880-1aee-11eb-97b3-ffe03fdfc2d0.png)

RageBar without Background:
![image](https://user-images.githubusercontent.com/73718109/97748999-a0f6ce80-1aee-11eb-93a7-9a620e8eb18b.png)

**Which version of WeakAuras are you using?**
WA 3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

### Additional Info

!WA:2!1z1tVTrrB8SYKIWhQA8l10wvj6BLi03dKK68Ncv6vG3uBscP2URDBAl6v2ZU7yVdz9odZmR)3fegoKR4pcg9EJdiFeK4G)eSYIpbwvI75mh4zMDJJBfyPe)mpZZ87zE(3VXgfZ0oJBg3Z2DSGH4NEcXv6D9PA5YnBkWYNBy5q9P808(Xko4ZE438NRSYkfNGcC8O8kusG0E)cLQvWAM(GwujssObgS1ET1pM6InZ)0ALZfY9z32tkzIhU5MDrTOBqOB6wVCV2fFPvHn3(bNBJCoTfNgg4UVY7hzyyuj1wBS7qjN0QfMlU668eXZUoBTqbUElCaMtCQ6r7woOXuLkbiVpviBmuTkmGiBmIr7I5Y(mCQzkLlw2ySl2oSzZAGm)GchxP4tp2uTHTaU(HcRauBSinpma3bhinrHsQPcsBMpQpMpxeAR3PkacP3K67NVAT6vRL3QMLwVvfLRwywfogmZQALchF8mog5xLH99lbozA0pg9Rr)w0KOFj6N1xsXfB1yOw8qxr6zVw8owfQ597I6lg6gY157m3FU6WiBbLBRs(ngPwl5qUTXOfy(QbJcdsYLzJ(WO7Xwd5ijDW1I1Po5pTYyIdnOUUv4OuWNZHQoMhG8Fgumuf3rOasBTF3ZcYyCzXPyKaxvYXbTKEVDuwZaAaE2f3U6QClxGbyDfdvMQY8r7y2grckgTnCGODI2nAVOheTJDtsar49MQnL4EsVH2iECxsQd(0)49uFExddOCkG6g4mShVt8L8lgdzFlClquCu2OStqW(WPRd)Dww2)wbxD9)As5qWuNvxsAdnjCSdrbqQrlm5UFaJDZ)MdelyPoN7C9wcSFt9us07W(xAnQEhvUYrpVzMhwEEmkKEyxTYVDw841lIN6mMQ3)RcfssZ(rxzmxnuHRbknlvUuHOSCi0u2mwB4LfQrjxVa54c9GariGMewM4BMhYL2nXf3Ef21ws7I5UuZ0A7s5UNWrSHNKimBbWQcNzjO4MaWsedtpSuPcw1JPhEnV(8yVMkoW6aPxBFCJlbTkza(MjjHeBnyV))ufYTpmEsC8oltoeJ4XBdnT(17zmjwqiRhkEYLl4dmsmzGX0yHMeF8HU27UDUpENDhhRJHKES7Hd6q40G2WqRytvRTytzxIpPLNun32wCA)TU)gTZDj8Y(xaF)LUb8EV6Ad5xqoUK(LnsU8DwoWaAsHcl0FQvox1SgVTJpH148lxJ8zEOuS1UuZf50orzhPWaQBy(S4VsQr5aRNKOraj8vNMSWzr1FEIMlq7cZXUTWS1Q(1Hio(ofd99VZjEej(c8PXvmBpSkp9FMbT8G)kZuXUiTPpf52rth54JeIg2sKpKFtRP76G9io(4Ns8MS0sptGYYzDBbjOLpEvR2H(ss2vByPry9OH8tYBzDyzROVlTPkyYccZ1Vazcy7Q4XYL)rpIDna08UQrjSl29XOEEMkYnpUI2dUD7fLlD0NK2eOCKPTHDAsALMDdsRakhNebfuu4f4Ckx0yUOnLk9QWPTuJxnEthqc8gZ1Ko63ws4CIFWD)fZPMdO02gJ00ScIlgcLp)GANhxNkYbIA1PTRUVvHcLM0uPa4wrs0Qt0iDGor)F5QHJqoEOPpzWae3n6wnIFpVw8gZpmqau1Y(FuvLwBbUnWoATZgBTX2JLuNeQYByu)hUlXD8x(mRQ)V7yHAHtCdX1fhyvQWZkyzf3Zz1vry99zS0g0ixiXDIV8uPJn27rp5iojqHjWc3lzmEcLtG0NEoy8bLTo8LLlvl)XJvpfq0P3BTULJh2509IU6TxzyheNGGEVHKahABBGDTdYpeBWD8qbTWG1rtQ8wBTrUDhY4uM698O))OlPDVYY)GMxyKryTneT7MPZV)8)6p

**Comment by jjholleman** [comment]
Moreover; If the model shows correctly and you do a /reload whilst at 0 rage, the model "unloads" itself.
