### ISSUE TITLE
Frame strata selector for individual weakaura text or text overlapping borders

### ISSUE THREAD

**Issue by Finneas98** [WeakAuras/WeakAuras2#2654]
Basically, I have an issue with borders overlapping weakaura text. I like having black borders around my class weakauras and I also like tracking buff stacks/charges at the outer top of the weakaura. The problem is it overlaps with the borders and it looks extremely ugly and is hard to read. I will show an example of what I'm talking about. 
![weakaura text](https://user-images.githubusercontent.com/64990055/97752712-773ca800-1aec-11eb-8e11-dd413aa2591e.png)

I know you can workaround this problem by making a seperate weakaura to track the stacks/charges but I think having the functionality to overlap borders or be able to select frame strata for text would be a great quality of life feature to have.

**Comment by InfusOnWoW** [comment]
I have no idea how you exactly setup that, since you did not attach your auras.

If that is a one aura with both a border and text sub element, then reordering those does adjust their z-order.

**Comment by Finneas98** [comment]
> I have no idea how you exactly setup that, since you did not attach your auras.
> 
> If that is a one aura with both a border and text sub element, then reordering those does adjust their z-order.

Thanks, I wasn't aware that reordering changed the z-order. Sorry for wasting your time.
