### ISSUE TITLE
TSU custom variables

### ISSUE THREAD

**Issue by superderpicus** [WeakAuras/WeakAuras2#2656]
In TSU custom variables i would like ”boolean” to be added as an alias of typing bool, as multiple times I have made this mistake. I feel it makes more sense to have boolean rather than bool, but I would like to see both as functional.

**Comment by InfusOnWoW** [comment]
I don't like that, though I can look at providing a error message below the field, similar to what we do for syntax errors.

**Comment by superderpicus** [comment]
i would also like to note that calling type() on a boolean gives you “boolean” which is one of the reasons i’m so used to using the word
