### ISSUE TITLE
Can no longer open WeakAuras after updating

### ISSUE THREAD

**Issue by thezeldrak** [WeakAuras/WeakAuras2#2657]
## Describe the bug
After updating WeakAuras2, I noticed it changed to just WeakAuras, and now it will no longer open or show up in game.

**Do you have an error log of what happened?**
I do not have any bug reports, but will edit this post, or reply to it, with a bug report as soon as I can get one.

Note that if the error looks like `[string "--[[ Error in ' my awesome aura' ]` then the bug is in the aura that got mentioned, not in WeakAuras itself -->

```plaintext
PASTE ERROR HERE
```

### To Reproduce
Using WeakAuras2, then updated using Overwolf/CurseForge.  It changed the name to WeakAuras from WeakAuras2 and now it won't even load.  I can't use /wa to open it, and when I go to the Interface tab, it's not even there, but it's all active in the AddOns screen before loading in game.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did, yes, and still no dice.

**Which version of WeakAuras are you using?**
All I know is that before I updated to this recent version, it was called WeakAuras2, now it's just called WeakAuras.

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
WeakAuras2 was the last version.  I know that's no help.  I don't know the specific version number, or I'd try to download it again.

**Comment by InfusOnWoW** [comment]
It sounds like you might be having an error. Follow these steps:
1. Install https://www.curseforge.com/wow/addons/bugsack
2. Install https://www.curseforge.com/wow/addons/bug-grabber
3. Try to do whatever it is you're having a problem with again:
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
    • GREEN
      • You have no lua errors from your addons.
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • You have an error with an addon, maybe not WeakAuras.
     • Make sure you clear the bugs once by alt + click the bugsack, to turn it green, then try to replicate the problem again.
          • You may also want to disable all other addons while you test this
     • There are error messages. Click on the red bag to see them.
     • Copy all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
     • Paste the error messages into https://pastebin.com/ and click "Create New Paste"
     • You will be redirected to the new Pastebin that you just created. Copy the URL and share it with us, and we will be able to give you more specific advice.

**Comment by InfusOnWoW** [comment]
No response
