### ISSUE TITLE
Dynamic (event-based) conditions are not updated if dynamic information trigger is inactive

### ISSUE THREAD

**Issue by Mitalie** [WeakAuras/WeakAuras2#2660]
## Describe the bug

If an aura's dynamic information is set to come from a specific trigger, and that trigger can sometimes be inactive even when the aura is showing, some conditions (from another trigger) such as Insufficient Resources don't get updated.

### To Reproduce

`!WA:2!fw16YTTXv4HbXJTXKPrKYwtKBQdTNjEsCRCTKJutM0uxbzsl5sjsdczz3MgXfaljwlqa4DbOevZnXMlA60lj09jGpc6rqpbNHth)a4(eu3(a0ZUaqH2D8u8dGDp7bNRFNVTW9kjIkEJRD9RT4CZV0CDEVfN)9NV9nk1TKBj3dFZX2eNDC5HrRe6hYVJMMwdnu1NAhYDPCJSdJMYWNT)(eUBzRWq)yweFV6TBlOXfSt10J3ptWrKahVqEJqwqS9kv2WQI5OuDAY2NEQJsxN6UcfkOz7eg0M1r3u4q8PACItmlmqSKPiMWJ1TBZcycpDd8tS(GyoRthkxCHRWZw(nJCP2jTBB1pIYxTsTgv3SMrmUXKKWjlmqer99xZvO)urInThniUjQnBVJ2ELLBATDtRLnTmdiDPtOrdof1WSzJk1QzQKyVkL4h7zKGrHDKpPpLpmjile0ZsWkUDOrfB(OecNwUAIVF5T8yX0NHvckpG4FpmWXCB9rCAh8RmIn7WdtIgkO(TvvSrg1TSQVETkvTUmZnQuxsablqUmzrzoxA3WHKawxIC7sWRx9ykrqBgZPbDI9onmJrqyaDSlM5sn2wwh4cQ0cIbsvL(eMZOlHfuf(z4paZbxd(5W1XVt9IsoQnhRlO1jXeTNL2xRkfjTIDZvmRuzJXKKyuC9ivxtpR9Uwacf0ooDtkW4SJWQRPkXf6lKWCpQZQ7VgxyzT288rNKJcDd)qI7sgyFZzgZUjiAt30XNieZa)kDdbcIKlgfh60lTE(gf2(7l5C1dVeCQx7vGtxaodC2Xoio1nC3GM7YIOTooFRSf5b)iS0PdtPdf1HsFYvGPFcmJnI3Itepnrq3M4VlPViMNqBXtcuaadmpdtp0weYTxp0L2cU4OvojWHFSomlCb4n0HYWLG3e(jdKQlrmTgK3rknpCo48WL1rNE40MyP1zh42WQTg3Hgq5mNMEH7wpyKa)SSkkugt(pZa3sz)70s6Plgn7kz5u5g8WoCQqu(DAkb7VR03J5iGvTDdSHnsTseJYgldkr(bTWWD4j7otV)fufdNFtP5hkvtfETIkkx)CXxl4YZaRdBCKlt8WKaCKThDbsq)OIe1AR0bdzrsdE71F2ouA0YYoASPSm4b)uj49fbGZ))hsId7cSnHftSn((x9WZfvkMUx82cpcwkUFghu0SkHQxTd544Y2ISfWCdp5SOIzXz55)4G0apAQjm3pqs90uP5tPglVPv9OPvcL4c58OZwmxKGyzC7ZsDmBpQRs4bJtNDEqw4DS68hMiIzT7dNDepeHEuluOXg13OcmdhhvK6msPOto1S2WSmkioAQQC2(LVBcXvoDw2Y65ke5EASs2U4y4wCs0GTYwKga9ycMTpTvwopbVno)CINKS2ZMLa3)5mR8ufRB9nTQT2gvEY4o(H7wLtFucnWPFJx96xBHfttg5bhjFLBHbYnYFESDsCCyqDCwgzvhjfxtrMDEL(5jYq5MtUJs7yerE7CjEgYd9uE3YJ5StaolOP(JMQ7uulRXqXfvoWi9klBpkRJx8bWVCj4JKCkWnvV)1Q3xXGHKsWRPBs8J8iAWnG3l6C58iYM1Tyccw)C9m2pmSBb42TGLLCrsI736fiU7NFxXCP4mybnZDvyd4DGZcFWrB046vQxNV4E34D5SajZgcW)6wWI6WhEHRy64rD2zjy6tnOhHZKUn68SaH8MmhgspzsfHjChQWShXpbVg1XJe0HI3tcF3Dw9MWuQNvV5)8FlF(pAAdIW71P84(Mk41G8eZdESQcJSPPmPGrlyLCkZIkwZCktKqQIxoHbCryTjOarwQmwqKCBsopOMIVtYEOoDsQTntP2G6kd2aUlykjOuUOPKCsAsRwsJNY)a3d2cUVKIbEqoPIKTajnMGu5fKm1)JKFBkxc87kaFmU93hn9eedSmQbyBfva0ciGn4aUha0cqBSc1b8qlYGhQQCWoGpGWHaieIAbpcvGplikaXqYtGE5JfWUWN7b9H9H)W5HpTa8zP)8EfGVWdoqd(snyqr4p6bF1ldGcFDwVsbHwqd(thaFR3ZbdV0lfgEswHySVrbUrqy8VGUzS)98U7MvrGp8N9KWVtTSebc)fj6d(RWFd(on47FP4kyi8y4V7bhwOuV)X9)V)`

Cast Spellsteal (or another spell that spends a resource faster than it regenerates - change the spell in trigger 2) until you can't cast it anymore. Both auras have a condition that should tint the display blue, but the right-side one doesn't change.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

3.0.5-16-g45181f3

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

No

### Additional Info

https://github.com/WeakAuras/WeakAuras2/blob/45181f30b8df7d1fd323656a18504a6eecafd0ee/WeakAuras/Conditions.lua#L642-L646 If I understand correctly, `Private.ActiveTrigger` returns the trigger that should supply dynamic information. If that trigger is inactive, there are no states to loop over. Perhaps it could instead use the states for the trigger that the condition belongs to? Or, considering that the state itself isn't actually passed to the function, simply use all clone regions or the one region of a non-cloning aura?

**Comment by InfusOnWoW** [comment]
Fixed by https://github.com/WeakAuras/WeakAuras2/commit/9545e8ab6a1fe890a1d9713f94859d8bcc5dea9f
