### ISSUE TITLE
Y-offset for multiple elements in a dynamic group is container based, not element based

### ISSUE THREAD

**Issue by c048** [WeakAuras/WeakAuras2#2661]
Hello,

I want to start of to say that this is first and foremost more of a "is how the addon is supposed to work, or if it's actually a bug?" question. I'm not trying to state that 'this is how I believe it should work, damnit!'.

To describe my issue;

E.g., multiple elements with a height of 1px with an y-offset of 12;
- the first element starts at a height of 12. 
- The second starts at a height of 13 (offset 12 + 1px from previous bar height)
- the fourth at 14 (offset 12  + 2px from previous bar height)
- ect... 

This translates to a static offset 12 **from the bottom of the container**. Basically 12px + (n)px, with n = amount of bars.

I would expect this to be working as followed (same setup);
- the first element starts at a height of 12. 
- The second starts at a height of 25 (offset 24 + 1px from previous bar height)
- the fourth starts at a height of 38 (offset 36 + 2px from previous bars)
- ect...

This translates to an offset 12 **from the previous element**. Basically 12*(n)px + (n)px, with n = amount of bars.

Thank you for your time and dedication to this wonderful project.

**Comment by InfusOnWoW** [comment]
Yes that's how it's supposed to work.
