### ISSUE TITLE
Player Covenant Load condition does not work while leveling/trying out Covenants

### ISSUE THREAD

**Issue by seanpeters86** [WeakAuras/WeakAuras2#2663]
## Describe the bug
When selecting a Covenant load condition, I would expect this to work even if I am in the process of trying out a Covenant while leveling, or when the game gives me access to the ability while testing out the various Covenants before making a choice.

**Do you have an error log of what happened?**
No error, the load condition just isn't tripped when I have the Covenant ability without actually selecting a covenant.

### To Reproduce
Create a fresh character on Beta and get a Covenant ability to test out, or start leveling in a zone while having access to an ability. Select the Load `Player Covenant` that corresponds to that ability and see that it does not load when you just have this ability as a "test" before joining the Covenant.

**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Comment by InfusOnWoW** [comment]
You haven't joined a covenant while leveling or trying out a covenant.

**Comment by seanpeters86** [comment]
@InfusOnWoW could we reopen this as a feature request then maybe? Struggling to get around this as `Spell Known` also doens't work for the Covenant abilities while leveling.

**Comment by InfusOnWoW** [comment]
It can't be part of the covenant load option, since obviously you aren't part of a covenant while leveling.

As a separate load option, no. We don't add options for things that'll be relevant for all 2 days of leveling.
