### ISSUE TITLE
Model dissapears on progress bar when resource hits 0

### ISSUE THREAD

**Issue by Londonne** [WeakAuras/WeakAuras2#2668]
## Describe the bug

Currently making a holy power tracker without any custom code. trying to make an overlay with a model to give it some shine and the model seems to unload when my holy power hits zero

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

Not sure if this really applys, just a progress bar with a model overlay thats clipped by progress triggered by players power

**Screenshots**

https://i.imgur.com/DDTedCt.gif

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Retested with everything off, and the same behaviour

**Which version of WeakAuras are you using?**

3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

I used to have something similar back in legion but a lot of changes have been made so im not sure if that helps

### Additional Info

Below is a the weak aura in question

!WA:2!1v1tVPXruCVf1MguvSJJsuvVKuFikTPXbWPw(qJCzjqWPyB6co2jnvWS7oWoXl7SAMzjah5KVg(iW5EcP0paCUhMALpbO2Va(qp1d9nZUGjrQJKn7BM3)NFZVNrP17SU76UN9WX8qe70JjUcVBov)9HTAXXItmohfj8OSddfeAap9eK7RJ4cS7(KGCz2mlRFSIL)XFyLpzLvwXyckWb0VkLeiSlu8G6fTox7qlQaP8Hr41)a59PUyZ8hv)qtIdnWBOGrA3gZ4x7USKp)htr)qSnh0pIBH7IdewvPVbZMXJS1I1IA1I0BsJc5RvVrT65TQBgfqe2H(O(y2q3iMouRNDAeh3G7rFtbkx4zfG6G5PhQ2uPFZrHk3QI2ngYdX((75YtVikvzyikw1QwSsLzkBq2CkZwvanzrbADmH2f9C1HlCvZXUyBibRdFZkxSs1shvzuuqsXLo86ihbPlUESSYB)2kJv9IgouFk7zPG1fq3eZcq(ph6mQM2iuaPJUO22cAmmrj5QMb0a8umIJRjy4G2cVRC(8sVHktyCm4wx(qLoQ0rEFZoisayR8(YV7kYhi3u(q59TBrciCVpE7H2iwbDkvE3)(DQ1VxE3z50lJuqvYHliiCyVLHqVWym0aTWTv4Nb3sU6eeOe4QgWFNTEouiP5mLyhOY9B44tcBoj(BUOreV(vdV(Lh3LWj2(4L0G1)DtJfAr8X75YYU1oz36rBpoEZqKWl8Mq6iio(y(d9PurREzYTzNCx6drFdwSq)Y7(V)HA9NlfHE)1AdzZHVqba1dKr6ZxYh9QyCXLjkYp0dvnvMn3AjhnyEyguE3lAPw0LCWGV4ZsoUNXzRDbKWN2aQ1axTlZL)jp5C9ElsLPAXEX9zJydw6wiCnfyuHsCA4RXdnNP1r4b)paZ5PKRYGIrT5efMvG7b2cwEdTEWZhhChavRtGr5fvXmhqmoUjkhEV9uyZwGQVQaIlibTnrSxD0Ep4sPhutHhInB(n4SpmeBKlt85jekgt0sX59TJf6qymkZBSwi(XHHHrQZwt(tYkay1sEGH8qpz1MYFoLSU8iznp5VQ1r(sd5ZLhlpPP8fB8OmYF52Yx5j334)X29nwY0xSX2zwY(ytbVNylO7YMMyunTkXXBNfMhBleTUtSPmxmRbNma)PNNieZDMdqrYvhPqz6TNMC6Lv8SKDw8Airg7cmizVtvspS)CFsJBN2EysBpX3y6trULmb2nNBz1jYxqsB54J48BjFD6rkqGIiJ5zQsm1EZ0VLnv4qf3KSs4AGw5tgdadcq982G4oUm1V)D0KES5iYpwtsG3yMMiqZfMWdmIJ9BPNxi)8rAEpoXfBzT3tlx3geBrANw(1nNOZJY6Q4XSeW3yWNapOpHlYfrCNu6POSODU3t4pDqmhu9y9KhBPfBowqD6gZH(LgnEBItjUU4aRdk(8IwxeFhuIbJguzPDTcwflEWKwQnaEvKaLY6nQbLV)QwlEKVt8a0cliSzKavyWEMdO0ogtOmcaY1pBhx(qR9E5HhupFLXk6yIEY6xDxlhpSZPLKxl1WUigbbxStdJFWPBRBqd34Xp2QlYpcNlBMmmhpuqBmyP8T6yomKrdvZCK5yQzkGx3w(TPnHwKiTmBAGDY502mAuGBH5qjvY)9RZT2At1VDF)j)3d

**Comment by InfusOnWoW** [comment]
Fixed by https://github.com/WeakAuras/WeakAuras2/commit/818752c4ac3d3a5d599737ef07a5ddfac69db119
