### ISSUE TITLE
Create New Aura type: Icon does not work

### ISSUE THREAD

**Issue by benleighton** [WeakAuras/WeakAuras2#2669]
## Describe the bug
When clicking Icon in the list of aura types to create, nothing at all happens.
If I create a different type of aura then try to convert to icon, it says:
Improper arguments to WeakAuras.CreateRegion - regionType "icon" is not supported
in chat.

**Do you have an error log of what happened?**

1x WeakAurasOptions\WeakAurasOptions-3.0.5-16-g45181f3.lua:1363: attempt to index field '?' (a nil value)
[string "@WeakAurasOptions\WeakAurasOptions-3.0.5-16-g45181f3.lua"]:1363: in function `NewAura'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1085: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1084>

Locals:
sourceData = nil
regionType = "icon"
targetId = nil
ensure = <function> defined @WeakAurasOptions\WeakAurasOptions.lua:1353
new_id = "New"
data = <table> {
 internalVersion = 38
 animation = <table> {
 }
 id = "New"
 regionType = "icon"
 uid = "n(7cOVgKNzd"
 authorOptions = <table> {
 }
 load = <table> {
 }
 config = <table> {
 }
 conditions = <table> {
 }
 actions = <table> {
 }
 triggers = <table> {
 }
}
(*temporary) = <function> defined @WeakAuras\WeakAuras.lua:307
(*temporary) = <table> {
 internalVersion = 38
 animation = <table> {
 }
 id = "New"
 regionType = "icon"
 uid = "n(7cOVgKNzd"
 authorOptions = <table> {
 }
 load = <table> {
 }
 config = <table> {
 }
 conditions = <table> {
 }
 actions = <table> {
 }
 triggers = <table> {
 }
}
(*temporary) = nil
(*temporary) = <function> defined @WeakAuras\WeakAuras.lua:1957
(*temporary) = <function> defined @WeakAuras\WeakAuras.lua:1957
(*temporary) = <table> {
 config = <table> {
 }
 actions = <table> {
 }
 animation = <table> {
 }
 authorOptions = <table> {
 }
 conditions = <table> {
 }
 load = <table> {
 }
 triggers = <table> {
 }
}
(*temporary) = <table> {
 internalVersion = 38
 animation = <table> {
 }
 id = "New"
 regionType = "icon"
 uid = "n(7cOVgKNzd"
 authorOptions = <table> {
 }
 load = <table> {
 }
 config = <table> {
 }
 conditions = <table> {
 }
 actions = <table> {
 }
 triggers = <table> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to index field '?' (a nil value)"
WeakAuras = <table> {
 IsSpellKnownForLoad = <function> defined @WeakAuras\Prototypes.lua:913
 unitLoadFrame = <unnamed> {
 }
 ClearAndUpdateOptions = <function> defined @WeakAurasOptions\WeakAurasOptions.lua:781
 StopMotion = <table> {
 }
 GetRuneCooldown = <function> defined @WeakAuras\GenericTrigger.lua:1899
 GetUnitFrame = <function> defined @WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua:208
 DisplayToString = <function> defined @WeakAuras\Transmission.lua:744
 regions = <table> {
 }
 SetMoverSizer = <function> defined @WeakAurasOptions\WeakAurasOptions.lua:1326
 CheckTalentByIndex = <function> defined @WeakAuras\Prototypes.lua:767
 ShowOverlayGlow = <function> defined @WeakAuras\Libs\LibCustomGlow-1.0\LibCustomGlow-1.0.lua:601
 RegisterItemCountWatch = <function> defined @WeakAuras\GenericTrigger.lua:3206
 CheckForItemBonusId = <function> defined @WeakAuras\GenericTrigger.lua:3823
 UnitCastingInfo = <function> defined =[C]:-1
 UnitNameWithRealm = <function> defined @WeakAuras\WeakAuras.lua:5153
 RealTimeProfilingWindow = <unnamed> {
 }
 GetSpellCharges = <function> defined @WeakAuras\GenericTrigger.lua:1937
 SafeToNumber = <function> defined @WeakAuras\WeakAuras.lua:5052
 GetAllDBMTimers = <function> defined @WeakAuras\GenericTrigger.lua:2739
 ToggleProfile = <function> defined @WeakAuras\Profiling.lua:377
 IsAuraActive = <function> defined @WeakAuras\WeakAuras.lua:4413
 regionOptions = <table> {
 }
 SetRegion = <function> defined @WeakAuras\WeakAuras.lua:2798
 EnsureString = <function> defined @WeakAuras\WeakAuras.lua:3601
 CheckMPlusAffixIds = <function> defined @WeakAuras\Prototypes.lua:848
 CheckChargesDirection = <function> defined @WeakAuras\Prototypes.lua:860
 regionTypes = <table> {
 }
 StopProfile = <function> defined @WeakAuras\Profiling.lua:350
 GetMoverSizerId = <function> defined @WeakAurasOptions\WeakAurasOptions.lua:1339
 GetGCDInfo = <function> defined @WeakAuras\GenericTrigger.lua:1961
 GcdSpellName = <function> defined @WeakAuras\GenericTrigger.lua:1973
 OpenOptions = <function> defined @WeakAuras\WeakAuras.lua:85
 GetUniqueCloneId = <function> defined @Int
```plaintext
```

### To Reproduce

1. Open WA
2. Click on New Aura
3. Click on Icon

**Screenshots**
nothing to show

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
It was working in Legion. I just resubbed. I thought maybe all my old auras were creating issues so I tried a fresh WA install with no auras, same problem.

**Comment by InfusOnWoW** [comment]
Your installation appears to be pretty broken, try reinstalling weakauras.

**Comment by benleighton** [comment]
Hi Infus (this is Kaitain from the mmo forums btw). This is a fresh install

**Comment by benleighton** [comment]
dw i think i fixed it. Clusterfucky addon conflict. Starting from absolute scratch now.
