### ISSUE TITLE
Renaming aura bug

### ISSUE THREAD

**Issue by racklinc** [WeakAuras/WeakAuras2#267]
What steps will reproduce the problem?

- While logged into my main character I get a bug while renaming an aura. About every 3 -5 seconds while renaming, all text in the in rename field will be selected (think ctrl + a).

What is the expected output? What do you see instead?

- Not select all text in an unexpected manner.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

- Yes

What version of WeakAuras are you using?

- 2.4.16

Was it working in a previous version? If yes, which was the last good one?
- It has always done this since I started using the add-on.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
- No errors reported.

Please provide any additional information below.
- This only happens on my main character, Racklinc-Shadowsong. I don't get any errors that I can see. WeakAuras2 works fine aside from this. It is just incredibly frustrating setting up an aura on my main because I have to pause and hesitate while typing or the ctrl-a like-bug will select all text while I am typing. For instance I could name an aura "Wk - Unstable Affliction group" and while I am typing the character "r" in group it'll act like I hit ctrl-a and I'll end up with just "r" or "roup" if I just kept typing without noticing.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`
- I cannot identify a specific aura that would be the cause.

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by racklinc** [comment]
Well I wish I had thought of doing this before I posted this, or even months ago. I think I fixed it by deleting my WeakAurasOptions.lua and my WeakAurasOptions.lua.bak files. Managed to keep my auras intact too!

**Comment by InfusOnWoW** [comment]
Eh, so you can't reproduce it anymore?

**Comment by racklinc** [comment]
It appears to not be an issue now. I really wish I had thought of that months ago to be honest. I did back up my wtf folder before I started just whilly-nilly deleting stuff. So the suspected problem-files would still be able to be put back in place and presumably cause the issue again.

**Comment by InfusOnWoW** [comment]
Hmm okay. I can't reproduce that either.
