### ISSUE TITLE
Prot Consecrate Cooldown Swipe

### ISSUE THREAD

**Issue by cSooy417** [WeakAuras/WeakAuras2#2670]
## Describe the bug
Prot Consecrate Rank 3 cooldown swipe doesn't go with the actual cooldown.

**Do you have an error log of what happened?**
No Errors

### To Reproduce

Use consecrate on a prot pally after level 23.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
??

**Comment by InfusOnWoW** [comment]
WeakAuras won't magically show anything on using consecrate. You forgot to add a link to the aura, or steps on how to setup a aura.

**Comment by InfusOnWoW** [comment]
No response.
