### ISSUE TITLE
BUg with 3.0.5.-29

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#2671]
Retail -square around group wa is out of sync with it
![WA1](https://user-images.githubusercontent.com/2686143/98049734-9874ff80-1e30-11eb-8acd-8f4d063b441c.PNG)
![WA2](https://user-images.githubusercontent.com/2686143/98049743-9b6ff000-1e30-11eb-9e61-87b3041d9025.PNG)

so its harder to set it up

i noticed its not on all wa but for me its on core class wa -it was same on old ipse warlock wa and new luxthos core warlock wa
also when i went to release version bug wasnt there

**Comment by InfusOnWoW** [comment]
Please answer the questions that the default template ask you.
