### ISSUE TITLE
bug with newest alpha 29

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#2672]
## Describe the bug
Square around wa to be around WA

**Do you have an error log of what happened?**
Nope

```plaintext
PASTE ERROR HERE
```

### To Reproduce
Nothing

1. Go to '...' wowup or twitch up and update to latest aplha
2. Click on '....' wa in qustion
4. See error  as posted pics

**Screenshots**
![WA1](https://user-images.githubusercontent.com/2686143/98051027-42558b80-1e33-11eb-9582-4f85e67adac5.PNG)
![WA2](https://user-images.githubusercontent.com/2686143/98051030-45507c00-1e33-11eb-9c65-6743874b2d08.PNG)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

no since doesnt seem to be other addons related  bug and changing to release version fixes it

**Which version of WeakAuras are you using?**

latest alpha 3.05. -29
bug was in version before 29 as well

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

yes,release version

**Comment by InfusOnWoW** [comment]
There's a question in the template:
If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the `WeakAuras.lua` file in `World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\`. In case you do, please export the string and paste it below.

Answering that would help a lot.

**Comment by Addonman** [comment]
[WeakAuras.txt](https://github.com/WeakAuras/WeakAuras2/files/5484668/WeakAuras.txt)

To me it seems that size of that square around group of wa -if its bigger then certain size its gets dialigned with  group like in pictures.
