### ISSUE TITLE
Error while sharing WA before WAOptions window is open once

### ISSUE THREAD

**Issue by Grimonja** [WeakAuras/WeakAuras2#2675]
## Describe the bug
As the title said.

**Do you have an error log of what happened?**
```plaintext
1x WeakAurasOptions\WeakAurasOptions-3.0.5-29-g8b833d0.lua:706: attempt to index field 'Private' (a nil value)
[string "@WeakAurasOptions\WeakAurasOptions.lua"]:706: in function `ShowOptions'
[string "@WeakAuras\Transmission.lua"]:407: in function <WeakAuras\Transmission.lua:392>
```

### To Reproduce
1.Share any WA in party
2.On receiver try to import it before you opened WAOptions at least once
3.Thats it

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.5-29-g8b833d0 - latest alpha

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Not sure tbh but it 100% worked at one point.

**Comment by InfusOnWoW** [comment]
And the aura that was shared?

**Comment by Grimonja** [comment]
It doesn't matter really its any WA I try.
But here you go random WA I tested it with:
https://dl.dropboxusercontent.com/s/fwth1nww2kevmum/vJM8Hm9ULy.txt
