### ISSUE TITLE
Multi-target Aura trigger doesn't work with "In Combat" load condition

### ISSUE THREAD

**Issue by ntowle** [WeakAuras/WeakAuras2#2677]
## Describe the bug

I made a WeakAura with a load condition of "In Combat" to track my Unstable Affliction on Multi-target in my case. If I'm out of combat and I cast Unstable Affliction on my target but target something else before the cast is complete, the Aura never triggers, and even a second trigger that checks for Unstable Affliction on my target (with match any trigger) doesn't work either.

If I remove the "In Combat" load condition and make a third "In Combat" trigger instead (with activation (t[1] or t[2]) and t[3) then everything works as expected.

### To Reproduce

Broken WeakAura (In Combat load):

!WA:2!1v1xVTrXwCC3IQWv6sRttPuPEXnOMBBFikXHwEHErEno0wCItxVH0RQQ8o7UJ9onRNzyMz9F6diHFa1NavJepEFWpZtMVbbjEEKfIpa5Jq(eWzgVjTaf)G3Z5mN58NFN)mf2QuVsXLIFXneJA2PJeRkmdrJsyIDzeQkSw9D8R7npIXsJzdOTgq44GdpHTECxCIafPimQ8UEsfsOk6sOevXWoWhzsXXkbPBxSq()xvKt(ILoktI3gPIsAhXYOQed)Nlyz8C(59mhILTsydAsNkHpvthGgj9OOEyzXPzGlQpKivYGz9ELHoZ0yCywNo(J4yX9R6T9w71WvbmEOmbQYXGBAVqJAPiPm5izwiUpMQAbIidN1Uw1w(TB5x1Z3Zkp8(yuQkHV0R5KMGTrkMO0)DIXQ2i6Q8L2JcPFykUC1oDsjwizSKJttFqSSOa88oGIbca1Asthf4AsbVEzPkYPrXUcmefET2TEJgMyT(qaABTWgjtaxVa)kUQ(8FR(Ij6Yb6L0xsFTRQ)36)L(D1xpqVS(Y6vcH6qxSs)FkolMiFwgfIM(4ki6iEPOmPI1ZFHLAW6sI4R1XQbJEt1TklWQmbT8nvpzJNwMjkREsLNERYiAmqT5tlJPX8lIS2l3gBZIX)0BDm0SGfuu6xcLAWuBF8bymVkaarkpey8KjikPNHIEx952sVSlLrXhIrsClLat7Qso38yapnA02uZesCeJglhB0Xur1B42drOWD1BORCo9M6psFhG8D(RsGUajszSf0D2Fra5mfqzpCxtN6TFX7XlPWdvTLjiOp(X5D(833k0(xhMaI22YCc9gto9SvUbNFHx761yPmXdluOGZrlKIt7yNECRUNFt(swHOma2HKlAFsSkXTkWE8chrgIJTc)M5lM8(F5HZH2ZFguWiDgPDMkykiJ8bHU70CN66Lfqkz0zQvXiBy4a)MKNbuf)cBjipV8JYqXaAGk77)Ns8t8e)6)TeN3wr6HBZf4iIb)km3E6aMiEFbIpE)CI5N6l7qxZ98B8GDQNJpV2MeTZI0Ppynykj4nG18CcpJNJFLHBrEo(g5yZPLQp4FkIJhbtKKOKFFE3u2GTe4VkdtJgT7zxFTk3zbMzo4qZkN08IxYeJOwrOuSJ9A(jKOdOyP0zMH9eCYQwTtX5XwvH0EEyMsXOnHETu0i7vojqDnmjtn)3W2LVS1iniG1VOvSlGKyrsycM0nrHDtzO4FDUzvfhRcrkvkgg(bwkSKqKmZq2hdbii3lYShB1qjH2nfl2VQxJM1(c9hw0Eb7HbMLRTTBIoGcBFcCndLRQtDa1gNFwuWrwLHkwSLhwXAmaRheabtF1TVYzN)lUsOGCz42tf25jdc4sGz1kzI0Zm502FTJ7ZzSE76S(ABQheigEsT7kKUuMa3KBF3OUz1xDHGjKbvYiXZsoyV9RV7dWpYFB(Lo5PgtB)NrKMnSXjUMPPGPkwu(09vk0(LRqI5x7nSfUSp8c1byr5khVOhAlbSj2e0HTQ5vV(oEOuEcYXBGziepRJ5yyNemV4eczvhs3Icc14jCsOe3dO82yT1xB95qya2lppko1SUIyPV9QEW7xrhSL(8oJ7Jeetmn1(isnZBiRW4R813ZRpkndxADrucI2fEfzv9ldgZfmyqsns)XRQ)oWaVTr5p5E6V)i8qozXcsFOtx)Yk3fa2jMB9W7)P)8sMFR5uWr)dE2DbJpb7s0)OTFTK0BtiUVtP()2J)Jp

Working WeakAura (In Combat trigger):

!WA:2!1vvZUTvXxCCDqawvIwhAtOGeUbIvBLik19FZkkiFn2nT4ehU2HuuvLVFn23P56zgMzU(JSaP6fqGD)9oeOcYRrSWiXdq4fyKfQpa5ripbCMXxN0cfVW3Z5mN58XVZhtQkz7KniBWHRo1nwgs51ysmLiYWhuRvlbsMAIlXhKVdftKELkVDJY2t9P0OaAps9EygY5O5SLdAJc5U(glSHTq6YLz8AHjyrygl4JmZqjh3UnIl(T88eYdx84ybAlxPFytFAmrgQ5VlNgZs4N2rFisupK2RgzSa(umQN7aXXIypuxerUdh1c33U(oLRwDCm4OY9XcPWzsNZm75ghG8IB1QXagIVzr7TQSBvljWy7gZDlCc40MZ0OuKRqeEQXRdIW9N0SuX6nAwVrr7g2g5EBICJKH2e3oirg99l3hs(6muu09cchkMriYyPJi7oXrsmhGPAKOboCq9THl6ms7DJjUcBXDjaO5fHYvSvRiSbizl(C5qni0DLuE2pEeWnd)YKxD(VrTyO6dCuxsDz1QxrLx9MQlOEFh1sQLvx1dQdTrs110A(m1sEGpKXIJ0jmM4t745kH4HysklOnGYUO(S2icIJ9NH6otFb2JfMpLsQ8GtyrUdq8PCatmiGo5snvBhXCwNrNsMs9UJlrjbytVYWaad0uzV5i9nKqt0(q2W3SC1DGYee6tcWIhhtaiPlYZpwiPDyzN9TXmCOkTn2NTwlJsuY1KxphhjJ5KCxt(WB(OCuEo5dl8ORNZLeau36r5qKa2fDnMmXgBrdq)6RCc0QJ4e3OVaAubtT1j7JqSIqW7lT1Xz4ibkQLzKqTa0wja8esaO5V7SBKEm08yJARtUBC4sSRkr9Lnn)1IYHcAtwtjUdQjJJ8X6BKI92)lDejewekbn60Jxzvg7cgorOlG(LOru(9tLkv6JNjDESzvC3g1ylAeQlRGPW(7HdKHwfb2tM5lCFuGr4tMoBu)ltM8pYC(Jbmg3AaKNCk03GAacT2U22LvlXHKuRZyJI(MWin8BussqKSluHJpi3Nh7ga4JBUgnyzFUiFUNEbHpir4uJSEuEWECx2W9siMEQXndY12Tr17TD5ea552vPwyw83fGxyIY5LGVSecBDPi4mdxhFaA1eWyE0WEV)RsyWay6f7h(SPTJO9QWrFvmI4pyNfwFTc3EgiPpqpUD3OKQv4qTiDcm1lwkPKAqJdmazmrJqS)(eKqKEIMDoinQ98BpdK1S19DJqZuBEGowZufrAldVKLMo0OzvmyXlAo0cqsep0leHBhkrwru3G)WmPYqsyxGmcfAgd1Be4Ht0KDrqqbYT0db59eysBWXQvYyu0xVW054th23Na7eCgMW77CSrbO6ey4ZyB4ZR6X3ROD1AL(mWqJp7MlVW0)0safHlRLZnJrASYc7tj8(ZRiV183D0TKFkwOxCge6jqDGW2(MRT(ARpYLG7y2SSH61RCeYvGQl5gW51GLJvMoFXtt9dbCbcCqGyOwpTdvvS64IjvuFRrB1HQVt99W334FkHTmUnHYrjVEwwVjTmNt5chpWKTWTZyDaL2zN0RV2TuFOZyj1pzvXYPA()xbhWENxYU)Cn0lcHKXnIf6MEsloS6esayukTDp9ml6KzTPv0NOdzV6LSlxE7cX4GjB4DaUW246fQ8)4yI2FOq1tCSpBsDS)P7GVrEB4nw)9ROoF6HDD5yDSm282tj9tp2DDJIrzxFfkBLV(oC)qxsB4nR8QN6mKXPa6jhOkMx9JGbEvTsF0DupTWgq6(thJ6ZWZW5gWeJ6N136(B(j)(I6FRLovA1VO(HHZlNHfI5rNlRW(wqj82z7(xp4V)d

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No... but I could if you want.

**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Haven't tried.

### Additional Info

Seems to be something about the "In Combat" load condition causing the triggers to not update, because maybe they are technically triggering before the aura is loaded. Fairly certain the logic is fine seeing as using a "In Combat" trigger with everything else the same works.

**Comment by InfusOnWoW** [comment]
Well, that's not a bug.

**Comment by ntowle** [comment]
@InfusOnWoW Wondering if you could explain in a bit more detail how this is not a bug - the WeakAura loads as I enter combat with the cast but the triggers will never activate despite their trigger conditions being met. The WeakAura is loaded, and is showing up on my screen, while I'm targeting a mob with Unstable Affliction, while I'm in combat, and there's no dynamic information loading such as duration remaining on the debuff.

Is the "In Combat" load condition not able to be used with spells that you can cast from out of combat?

If I was unclear on any of this let me know.

**Comment by InfusOnWoW** [comment]
You enter combat after the cast.
