### ISSUE TITLE
Rounding for special variables

### ISSUE THREAD

**Issue by babbelnedd** [WeakAuras/WeakAuras2#268]
Not really an issue but something that should be addressed imo.

When you create a statusbar and use a special variable such as `%percentpower`  (available when trigger status>mana is selected) there is no way to change rounding. ends up with showing something like `91.9129381243278423%` which is kind of useless.

The *Remaining Time Precision* field does not have any influence. 

```
d4ZDeaGAPq6XiAxsrzBG4WQAMiuZfjmBv65s6MaIVbWTPkNMs7Kc7LSBj2Vs6Nsr6ViKFl4zujdfuzWGYWPIdkL4usb6ykvhxkOwOuklvkQwmvQLR4HGQEkQLPuwNuaNukvtvOjtrth6IaXvLI4YIUUuTrvyusbzZa12vcFMQ6Rsjnne8DG0ibKgNkA0iLXReDjPqClKORbOopsALsH61ivddKw7kk2tSPytffxD(HERwtKMm2eBjdf5wm4qbpUVFvCtBsK42narS7FGpCdJIYyxhaCraaucNNqDDcbWoKnbMsGHiJnDaWfbaqjCEc11jea7q2eykbgImCPdaUiaakHZtOUoHayhYMatjWqek2zc(twRWnjPTAdfzav8n8Mkkg)BwWnff71VOvrHcfJ)nlOII96x0QOqHInTGbBj7xKQII96x0QOqHINNmvuSx)IwffkuSZch8VzbvuSx)Iwffku8eUPII96x0QOqHIb)KOnuuuSx)IwffkuOyYEfdEXX67NdXbFlPyW9cjAdLgQbxB8kSvytI9PScdNEU24SykEsFBOeP6KI)(8U)rCfFs6v5wmMlX(KIb5UOjTVcRT7xOlgZL4rOGIHlUcJ)sDfMXptauXO1lNJqbfd0GxwD6fXpjAxKXX67NdqcMPmOChQytB15(uJ5sK4emkEfMyCS((5OOyKQtkUIp2RIZfzbfdxa0Ce7eanhKQtkdOI71KOEXIQnX9AsKta0CqQoPAtCVKlYck(7yqOymxIYT4k(K0RhHckgObVS60lIPLwFAOm2aw8xiPfMJ59YJ59sXTMp9w6ZxBa4Up1CwHb)xr3)ScBfM4s3lowF)CQYyx8xiPfMJ59YivNumdcXGaF8O5TaeqeBnfd39PMZkm4)k6(NvyT9K0nNGJ4VqslmhZ7LW9twq5wSPT6CFQXCj2CRpnuCJ4KdzwqNaO5i2sgkevTMPyIb5ikMmCdJIcfxD(HoqtRpnugBal(nnTOnu(lr4y99ZPQOqXM2AJ2lKODrk(VxXGN3lzCE8LXMyqTMinzSDcvS7NKU)e6ft4d3WOOm2LXUm20baxeaaLW5juxNqaSdztGPeyaYGGm2fkU68d9yUe7tkU9cMd4NmPOftZMwQu0A(0BPpFLcGKM2NIyUe7twPGB4(pjrTsZIPqXvXBnJqZ2HiEHm2jSTluca
```

**Comment by InfusOnWoW** [comment]
That's because the percentpower is not a "remaining time". It's still a valid wish to have %percentpower rounded, but we already have a ticket tracking that at: https://www.wowace.com/projects/weakauras-2/issues/958

**Comment by emptyrivers** [comment]
This does need to be looked at, but it's not as simple as Round()ing or format()ing the value before saving it into `state`. Other things like `amount` and `sourceName` (from a spell damage trigger) also get saved in there, and you wouldn't want to handle those the same way as `percentpower`. In addition, you can save custom values into `state`; how should that be dealt with? (realistically, I would expect to ignore custom values in state actually) Ideally, a resolution to this issue wouldn't amount to "special case all the things".

In the meantime, a simple script will format the `percentpower` value to the correct # of digits (replace 2 with the desired # of digits after the decimal):
```lua
function()
  return ("%.2f%%"):format(aura_env.state and aura_env.state.percentpower or 0)
end```
