### ISSUE TITLE
I can't open weak auras at all other then profiling please help me don't just delete me rude!

### ISSUE THREAD

**Issue by ariesof84** [WeakAuras/WeakAuras2#2681]
## Describe the bug

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by mrbuds** [comment]
You have to answer question asked for us to be able to help you.

**Comment by InfusOnWoW** [comment]
There's nothing rude about asking those questions. Since you choose to not answer even the most basic ones, there is nothing that we can do to help you.
