### ISSUE TITLE
I don't know what your talking about you didn't ask a question it doesn't work at all it there's no error code!

### ISSUE THREAD

**Issue by ariesof84** [WeakAuras/WeakAuras2#2682]
## Describe the bug

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
Take a look at your own bug report: https://github.com/WeakAuras/WeakAuras2/issues/2682

This is your last chance, if you don't answer those question you'll be blocked from creating bug reports.
