### ISSUE TITLE
PLEASE HELP ME Can't do anything I gave screenshots of everything I can do!

### ISSUE THREAD

**Issue by ariesof84** [WeakAuras/WeakAuras2#2683]
## Describe the bug

I expected it to work and it doesn't all it gives me an option to do is start profiling.

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```
did all those steps still not getting error

### To Reproduce

nothing works the I click and only profiling works I don't even know what that is.....I just need the options window to open to copy and paste my aura's please

**Screenshots**

![2020-11-05](https://user-images.githubusercontent.com/74013037/98272172-6a89db00-1f56-11eb-9296-5cde92652d0d.png)
![2020-11-05 (1)](https://user-images.githubusercontent.com/74013037/98272177-6bbb0800-1f56-11eb-8476-1f7951533ead.png)
![2020-11-05 (2)](https://user-images.githubusercontent.com/74013037/98272181-6cec3500-1f56-11eb-88e7-19fc1587893d.png)
![2020-11-05 (3)](https://user-images.githubusercontent.com/74013037/98272186-6eb5f880-1f56-11eb-9847-502a815945d5.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** YES

**Which version of WeakAuras are you using?** THE NEWEST ONE
3.0.5-29-g8b833d0

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

IT WORKED FINE BEFORE PREPATCH HAVEN'T GOT IT TO WORK SINCE AND IT'S HORRIBLE.

**Comment by InfusOnWoW** [comment]
I see that you have bugsack installed. Please open the bugsack by clicking on the red bag icon at the minimap and paste the error into this bug report.

**Comment by ariesof84** [comment]
21x AddOnSkins\Core\API.lua:370: attempt to call method 'SetBackdrop' (a nil value)
[string "@AddOnSkins\Core\API.lua"]:370: in function `SetTemplate'
[string "@AddOnSkins\SkinsAce3.lua"]:287: in function <AddOnSkins\SkinsAce3.lua:209>
[string "=(tail call)"]: ?
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:108: in function <...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:146: in function `Create'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:403: in function `CreateFrame'
[string "@WeakAurasOptions\WeakAurasOptions-3.0.5-29-g8b833d0.lua"]:712: in function `ShowOptions'
[string "@WeakAurasOptions\WeakAurasOptions-3.0.5-29-g8b833d0.lua"]:534: in function `ToggleOptions'
[string "@WeakAuras\WeakAuras-3.0.5-29-g8b833d0.lua"]:89: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.0.5-29-g8b833d0.lua"]:885: in function `OnClick'
[string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-43.lua"]:144: in function <BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:142>

Locals:
self = <table> {
 AC = <table> {
 }
 SkinAchievement = <function> defined @AddOnSkins\Skins\Blizzard\Retail\Achievement.lua:16
 Blizzard_Channels = <function> defined @AddOnSkins\Skins\Blizzard\Retail\Channels.lua:12
 Blizzard_AbilityButton = <function> defined @AddOnSkins\Skins\Blizzard\Retail\ExtraButtons.lua:4
 ArrowRotation = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @AddOnSkins\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 FindFrameBySizeChild = <function> defined @AddOnSkins\Core\API.lua:1148
 Blizzard_ItemSocketingUI = <function> defined @AddOnSkins\Skins\Blizzard\Retail\Character.lua:440
 GradientHighlight = <function> defined @AddOnSkins\Core\API.lua:285
 Blank = "Buttons\WHITE8X8"
 LCG = <table> {
 }
 SkinIconButton = <function> defined @AddOnSkins\Core\API.lua:709
 ScheduleTimer = <function> defined @AddOnSkins\Libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 ADDON_LOADED = <function> defined @AddOnSkins\Core\Core.lua:163
 SkinErrors = <table> {
 }
 BuildProfile = <function> defined @AddOnSkins\Core\Options.lua:557
 data = <table> {
 }
 UIScale = 0.755162
 db = <table> {
 }
 SkinBackdropFrame = <function> defined @AddOnSkins\Core\API.lua:997
 AdjustForTheme = <function> defined @AddOnSkins\Core\API.lua:1058
 SetEnabledState = <function> defined @AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @AddOnSkins\Libs\Ace3\AceHook-3.0\AceHook-3.0.lua:274
 Options = <table> {
 }
 Font = "Fonts\FRIZQT__.TTF"
 events = <table> {
 }
 Noop = <function> defined @AddOnSkins\Init.lua:41
 SetBackdropColor = <function> defined @AddOnSkins\Core\API.lua:99
 SkinDoubleStateIconRow = <function> defined @AddOnSkins\Core\API.lua:1282
 Blizzard_Mail = <function> defined @AddOnSkins\Skins\Blizzard\Retail\Mail.lua:4
 SkinWidgetContainer = <function> defined @AddOnSkins\Core\API.lua:1312
 Media = <table> {
 }
 SkinSlideBar = <function> defined @AddOnSkins\Core\API.lua:885
 SkinTooltip = <function> defined @AddOnSkins\Core\API.lua:1028
 FindFrameByPoint = <function> defined @AddOnSkins\Core\API.lua:1183
 EnumObjects = <function> defined @AddOnSkins\Core\API.lua:1096
 Blizzard_Calendar = <function> defined @AddOnSkins\Skins\Blizzard\Retail\Calendar.lua:13
 GetChatWindowInfo = <function> defined @AddOnSkins\Embed\Core.lua:19
 EmbedEnterCombat = <function> defined @AddOnSkins\Embed\Core.lua:153
 GetName = <function> defined @AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 GetOptions = <function> defined @AddOnSkins\Core\Options.lua:665
 Blizzard_DebugTools = <function> defined @AddOnSkins\Skins\Blizzard\Retail\DebugTools.lua:4
 name = "AddOnSkins"
 SkinIconTextAndCurrenciesWidget = <function> defined @AddOnSkins\Core\API.lua:1263
 SkinLibraries = <function> defined @AddOnSkins\SkinsLibraries.lua:154
 BugSack = <function> defined @AddOnSkins\SkinsBugSack.lua:5
 Unhook = <function> defined @AddOnSkins\Libs\Ace3\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @AddOnSkins\Core\Core.lua:94
 preload = <table> {
 }
 Blizzard_IslandsPartyPoseUI = <function> defined @AddOnSkins\Skins\Blizzard\Retail\BfA.lua:70
 RGBToHex = <function> defined @AddOnSkins\Core\Core.lua:42
 Init = <function> defined @AddOnSkins\Core\Core.lua:330
 Blizzard_BlackMarketUI = <function> defined @AddOnSkins\Skins\Blizzard\Retail\Auction.lua:323
 Blizzard_IslandsQueueUI = <function> defined @AddOnSkins\Skins\B

**Comment by InfusOnWoW** [comment]
Deinstall, or update AddonSkins.

**Comment by ariesof84** [comment]
that works but what is addonskins?

**Comment by InfusOnWoW** [comment]
a addon you have installed.
