### ISSUE TITLE
bug with "Hide all glows created by this aura" aka libcustomglow

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#2684]
## Describe the bug

When you use "glow external element" (or just use libcustomglow this happens for both) on a Nameplate and the unit dies before the unglow is called be it via the checkbox or other means it fails and you get stuck with a glow that only goes away via reloading

**Do you have an error log of what happened?**

```plaintext
sadly can't get an error text for you. I tried but bugsack isn't catching anything
```

### To Reproduce

use for example 
https://wago.io/wY9FhqgSl
and kill a couple of mobs

**Screenshots**

https://imgur.com/a/mSh29mq

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

not specifically cause i'm lazy

**Which version of WeakAuras are you using?**

3.0.5 but this has been happening forever with lib.customglow

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

no never
### Additional Info
I know i'm lazy with this ticket you know where to find me

**Comment by InfusOnWoW** [comment]
That's a bug in your custom code. At the time that you tell the state to hide the unit -> nameplate mapping has already changed and thus the nameplate cannot be found anymore.
