### ISSUE TITLE
Fully transparent WeakAuras are not visible during configuration anymore since 3.0.5

### ISSUE THREAD

**Issue by SubtleNudge** [WeakAuras/WeakAuras2#2687]
## Describe the bug

In WeakAuras Version 3.0.4, WeakAuras that had Conditions that rendered them fully transparent (by setting their alpha to 0%) were still visible during configuration, even if said Conditions were met during the configuration. I guess there was some sort of "minimum alpha" that was being applied during configuration.

Updating from 3.0.4 to 3.0.5, I noticed that I couldn't see those WeakAuras anymore. The WeakAuras themselfes have not been changed and downgrading from 3.0.5 to 3.0.4 immediately restored the old behavior.

Oddly enough, clicking on the WeakAura's frame or dragging it around would make it visible, but closing and opening the configuration window would make it disappear again until moved.

**Do you have an error log of what happened?**
BugSack/BugGrabber did not report any errors from any of my addons.

### To Reproduce

1. Create a new WeakAura
2. Go to the "Conditions" tab and add a new Condition.
3. Set the new Condition to "If [In Combat] = [False] Then [Alpha] = [0%]". This is an example of a Condition that is met during the configuration (as you have to be out of combat for the configuration window to open) and sets the WeakAura's alpha to 0, making them invisible.
4. The WeakAura will now be fully invisible during even during configuration.

Extra steps (odd behavior):
5. Now click on the WeakAura's frame (from the WeakAura itself).
6. The WeakAura is now visible.
7. Close and open the configuration window.
8. The WeakAura is invisible again.

**Screenshots**

The first screenshot shows the currently bugged behavior where the WeakAura is invisible after opening the configuration window. This is WeakAuras version 3.0.5, as you can see in the title bar.

![wa1](https://user-images.githubusercontent.com/74121303/98454598-25d09080-215e-11eb-9bdc-a9636784589e.png)

The second screenshot shows the old behavior from 3.0.4.

![wa2](https://user-images.githubusercontent.com/74121303/98454599-308b2580-215e-11eb-835e-7d99f20a9215.png)

After taking the first screenshot, the only thing I did was to downgrade WeakAuras from 3.0.5 to 3.0.4, did a /reload and took the second screenshot.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I tested both versions with all other addons disabled and the results were the same as reported above.

**Which version of WeakAuras are you using?**

3.0.5.

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes, it was working in 3.0.4.

**Comment by InfusOnWoW** [comment]
That was a intentional change. It turned that there were quite a few bugs with the minimum alpha change, and thus it was removed.
