### ISSUE TITLE
After hitting 0 power, model disappears from progress bar.

### ISSUE THREAD

**Issue by Albhe428** [WeakAuras/WeakAuras2#2691]
## Describe the bug
I expect the model to keep being visible and never disappear, but after hitting exactly 0 rage it magically disappears. After doing /reload or selecting the model again in weakauras options it appears again.

**Do you have an error log of what happened?**
No, I did not get any error log when using the recommended addons and the console statement.

### To Reproduce
1. Download the wa (further down in this issue)
2. Start getting fury (watch as the model appears)
3. Get to **Exactly** 0 fury and then gain more to get the bar back
4. The model is gone and only the color is shown

**Screenshots**
https://i.imgur.com/PyMxSNG.png Working as intended
...getting to 0 fury
then this happens https://i.imgur.com/2brHcOc.png 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I tried on the ptr with only weakauras downloaded and with only this weakaura.

**Which version of WeakAuras are you using?**
3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
It was working the version that was shipped last before prepatch ( I use a similar weakaura on main and it broke the day prepatch came out)

### Additional Info
This weakaura is the one giving problems!
!WA:2!1vvWUTTrq0qi0euH6cBvuJg0ce3ae3KIgNyNgFlhevKQvGIKcftCsraOxYDP42qTCZUlLL0Tk0d5S(e05EsFc(qpty0VaJ(f4VGo7sAjLGwdy7DMD23oZSV5rRgvgubxb)H9Ml5iX7oMIvrF9zM1DcdLe1RTeJYxzjgxSybIfeLi6Mqzk)A1B7w35CZrCsuifnHzX36JSFEcMyx9LUDU0hf8U(IKugUwsCI4zwwwDl9W9E8uLG2Vpri)YDffl)lB1yoXxcqKkVqM6tgsyQEPHH0rl8QvTNRxp3QoUtXPcZTuzFhtioDtoLiStzuLppgnMiUivs8q(YeHVovozQKtIJBILLxIBxbbW1Px36TAjszgF2OuvIddnGilpvdHgYtMJj(qs4cjN4O6T624LTMLYks6Y8Tqbk6qIBUT(6(ZRnNgKW8cmvCj4NlHghrWqXVcQyD)zgIrhykIdDGcwOAKTHnlHroJGKKEkbH1xfDJZVQu90TgHKaWILt1XOtNSDThGOm4Sz7M9d3i7Uz3l7hZ21pKYOYOp19uFKi)rOKLvjOQKqJgGNeT(7)BSMdTihsF4wLpB7SnwGGGGJ6b)(HkhG40Ol0MdGkn2liMYpzr(APYlv(c(wR2Divs9JjRfGyS1z5gH0ystS)H7V)p)4hnp3hhPI43JWgsfjSbWlI8b6UJ8bdqmffJHSu(UXpCFpzeAVbhScw1ylrUXyR1USr)ZMtfxXrHsbQmi5m7V2zhzD5QugfZJqLwdJjxH8K1qwT07iRpSnVIImsPtkCYPVoVpwAMXN(p3(oC(MRfXYjHsxK7LehAMTY(C(xz8O5HA6rGz(0UkyEPzdGYsWgN)(55dLVPyg9mZ()wQurdhND95MYM4coTB3PD9SneqXRJzUjWvCZ88mmHP4B2qqNSZlsryGwG2X19JkSIB67U25lpHMeA3gOT5UonrGpwG4tpUyrEsDflOOjSMyYznB3UUJxUKc)7x2XaWfq97X9u0bepUGeq1ZnL438)iM8fo6qXRYTE0jKBw0KkEtS436)7kWJHXEAq0Wf(qUteEs44F25fg5OCaWsY2yMMezCFwXUbREpl8SK3xytW9j8T69(uKGStJ044DooIQixbFsE25hrO9Ju3YoobHp0g0Sc22zqASIw2jigjLBNLu2wNy6fxygATJjmSw05GQp9P8nbrRQynjGGj4NJgfDzEQ3qaIA6xl)E1CQxV9NgjLfnxyM5nYCfJ82AzSOZb2iarhUEkswEMrBtsXehNM)YrU5IhAIwQGWVBtTsxikG82AiGlY6BJeV9LnV)kR73Z8PcZXIwy(3rMc)jcvoktTJPtMGe4dsP4fHIdB1k893ZpSN9KKKbwzF7jZvjbdZ1s)glVzfOakeeMt76VQUt(N3QTKLdOaDaqyfi2LCovpb9hFHt(WUpuqH0(LfuMgts0TPy7WuX4fjckiczKpMFuhNM)AN2UvBnxRctZ7gcT6pS4WS7u2gKDvLZ(PYZwnrF9ksNhTh8bVkd)7x)Vd
I am sorry if I managed to create a duplicate issue or if I provided bad info, my first time doing one of these :). I am glad to answer any questions if I was unclear in any way!

**Comment by InfusOnWoW** [comment]
That should be already fixed for the next release.
