### ISSUE TITLE
Texture drop down list is blank

### ISSUE THREAD

**Issue by paradisewoods** [WeakAuras/WeakAuras2#2692]
## Describe the bug

When creating a new WA, I chose "Textures". The drop down to change the textures, in the upper right, is blank.

**Do you have an error log of what happened?**
Nothing came up, no.

### To Reproduce

Addons disabled, standard reset WTF/cache, fully uninstalled/fresh install, etc.

1. Go to New Aura
2. Click on Texture
3. Click on Choose
3. Click on the drop down in the upper left

**Screenshots**
https://imgur.com/a/Ojlb6lN

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
Looks like 3.0.5

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes, I switched to 3.0.4 and it's working fine

**Comment by mrbuds** [comment]
This is fixed on alpha build
