### ISSUE TITLE
Won't let me open weakauras in game 

### ISSUE THREAD

**Issue by Csant042** [WeakAuras/WeakAuras2#2695]
## Describe the bug

I can open weakauras in game but not the main menu

**Do you have an error log of what happened?**

```plaintext
https://pastebin.com/i0wSNDs0
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes
**Which version of WeakAuras are you using?**

3.0.5
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

The one before prepatch was working fine

**Comment by InfusOnWoW** [comment]
That looks like a incomplete installation or some other addon doing something very strange.
