### ISSUE TITLE
All WAs shifted. Bug?

### ISSUE THREAD

**Issue by Bakamaka11** [WeakAuras/WeakAuras2#2697]
## Describe the bug

For me and for many people in retail and classic all WA have been shifted in 3.0.6 update and now look ugly and weirdly aligned. Should i just use 3.0.5 version (there everything works fine) and wait for update or 3.0.6 is the new standard and i should edit every single WA in my UI?

**Screenshots**

https://i.imgur.com/cpt0tPu.png

**Which version of WeakAuras are you using?**

3.0.6
**Are you on World of Warcraft Classic or Retail?**

- [x] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

3.0.5 works perfectly

**Comment by InfusOnWoW** [comment]
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/2696

**Comment by InfusOnWoW** [comment]
Having that aura as a export would help, so please export that aura.

**Comment by Bakamaka11** [comment]
> Having that aura as a export would help, so please export that aura.

This is the export for classic version. If you need retail version (all my WAs shifted there too) i can provide it too.

Energy bar: 
>!WA:2!DJvxSXXvvyVDtWKX0whhAA(dYKLgh7whh)tZpTfJZo2RJ3w71Bhp2onnODNDM7UZep7mtUZS(VslngARLGQwzKa6BOL)HWFlGqI(as(bE(ilKaE1pGqcHqkpdQCU37SRx74euqTsigPS((Z5EVNZ9EoFNVtInBhbQd2BF9E(ok3HzhMRDYTk4rnjufDJ5nPE((TR4yVYk6utznppNqB)n1ReA5rNYp02ZnqIU8uflgqc)SXQP7AGtK1Z2nSWiPYOLsTMyZgXZXJ(8XIfl(avOo(h3km0p4zp35wuVKxV2ENt1PSXado786NRFQUbFFVGAqOonusX21ouQqr8pbwsRgsTlvIqdowN0OMVzvtsHkflQTSpHoEQjYo2mtOeIDu1Rq1hy1aFIJtAZaPTcQuGSaXnCAuA7LQLBKKtRLBATKQAnMklLGtPoD2utmHQREzsGKkFIcJt0DcTuQGAtbFh9Lj01R4gPcs3bTyc1v3zwu1qTFY11DTlRZmKlaFIXGdP465s20evi2y5yQhnGy45AgSbrpGmDiL4wk0Q1vz9yMcKqPSUTlUwib8zGNaoDRqNyZhz3JqxqCMXRIgHkPe)rrXXt3CS1ReqYz4OheOesRqu5n7SqGTBjhIQ6uxzMuQLRGVPsk4TKXHH(Wg2Rqyn2SqKdG4TlE84zJJEjQbg6oK4feVRwvf)nLjEl0VCw7LiovPCDGzdQLOEv8JKzACJ3V)rSl56rjropPyxTPOupAq(neIjCMoq1qpJid7J3t3jSn9pykxcT0YYk6u5NswZ2y(AfP4leE1PhQh)ocNVXydXo7ctpIAQuzgOITzTkJMjGS8vhvPVrkG35fTljf5yM2fpS4vzpe2c351diof5UWvvMstBQjNi1yA0LeQ14xUN9)TAb)6W4zx75Qg4RtNFoBZqRhgEiioSpjy)Fbj4JbTcP)NTSbFAXcVASn59u9c5EaX8p4o6pPNjrj5mAtbh4UJoU4OoEM2gAp95UKInQQwWJ(iDcTV2bxTUdvhdaFk4tdhe6aoubJkbHELPvC5oUky0QhCe4OWHxpxQmPuVs6RLcooCIAc54(I1WyTqsfFt8x4ysRY8ByE65HhtAlwNaVkudYmSHunSigZdhxeWe435mzsRLl7uZLsn3yQPEXzWa)NveHip1SPuNi5lPLEKxO62BbQPQlTVflwXLhQ3LEpYKEKd7wsg)C8qhmzJkuA079qYS1K1BrcTReI9nrpYd2S02UgOynTMZk3fl4phXDHErF(WOH9OnjKydSlk3frEOHKtShMrcUiSpDxZM3)p39C)7R7DSgMM9AdjF(9AWlTxdoWEk6G75OxOpPDns)9fD(OM8rPz18ZttVptQV0oEI2TU0K7qc((e(GVBHwe3g6c(656HBYlNiXNFxtXvv(4dj)k7yu2xGL3I4emuXEURjnS0DlrmVNZxpQdfyG7EwYs(2I51SlJ2T8viHSwD1ncBThY7t9krjbbmqlu6eHOSMj2HyVAJEeNaYoMseaeGlKBS7yUGE3PLSRjB2m21u3FByxc30D5oMzKCSLq7nzrm3yxd0JCJa(ULNJOpFs88d6DAdDxEAGGU2H)rp8nSBzIR52(EyhPM)7E5T2mqaxikjSc1vOF4cHtk5FqgjJfiAI03mW3B3svg0AoJ6z7IdYtQY7jbxbA9o1thM2DmQNBOfFaw(nxZgSBIvJdQpPnlJM1wbHysQLhn6A2cAd5cibpSeGO3Q(DT33bmJFMSJMulv9RG1n9YjWQTAoLYlfd6(jpmCOASlHc60C4)wytrATCECrARExrUXbqjIY7LJLM)urPC32O5P4JiaMBb7a7coeR6lHGj5vYG8yGdTos1qmAblIDjRWZcNcnUz5utySuoDRf8rNAsOsrDtcNTYzeexqslSECQmnlpecv4Z8KZcpvEoZfwcmQf0pJocC2oHEHZXAnaR)w8Bcfh8bL98nqYrhfgSHjSkAPr8wgF4)2XzFTn(WVE7SVZedjmgOhYEwiwIC4czhF4)XWSVJHl6V)VyF)XXh(p)OZF5wA5iqxheuQPMDYStFjn)(gCGTck75fALnk61YVDuLtAEd8HIysmN0gFWVen6TzZ6Sn4(o53TS6lzDhUEm62k26C3XaBtKOw6RmUM6ImEgprBcxSX536dbpxEvDhFl94kR45vowHasz8otTFKq)fHHqMtrIBBAsCvZKcdWu5JKhgUn4YqsgZQdJSGq(QHlFMa5OGig9kyujQTlJegjpnKSeQye1P9CqcvEuB0BL7wxD8PutFTPYOLCcySJ1jCTlaTFIwwDbDQTo6943UEyigPWAJ85lrcvxq3PcjgvGnHe5HVo7n7PxfbcrwXHldVfOLx4PRjov)lMMXVUOUb56jnnrAAxVrWZ155k4nNKyARFDXOSFV4tV2LGN)XGxiwdAzpeCtyIyWKqg4aGutrKscov)fK)eJluLayAqBdo1heEBeVaKl0l2r)WXv5NhNU1HHhFDFwpgfQwrQsCAwhtcUA(nzRSXC55mZoPeK72Ta5RJUWGvGcwkSRwlyz097p9nzFFd0L99zF)UXh(VkgjoqSyukblmO)5XGEWETd7Fk2kZX)POhfl3iNFow2JCyONHnVMG1BisItJLYX7fyPBYmP6LKTLy060EHm(hIpcJ4iRggdodxLKy37iomKMVjFWBTPaz5LeqsX2GppZV2U4YqRvPm6Te2ROsMPYKcoefboyYuLl42GTRhzfUH(Tpg1Ef5xSIUjJxVSMMFhnP2rN0jAzhJEvXOX3Kp2IyW2CuD)vNlQHqTIWZYhDn0uXQBKodsmoNOK1nBOk8YWUP)r3JRzrdvEU6TxaReNJgDLePsX8p596vYCzSatBdR1(KWViounXPDHVn)bb(oO753f(EW3)wWpig8dr3KFe8JXh9Bd)eHZZpf(zWp)eTa1GFj8RSGFDnHbWbk2d91nQbc0(Bpk8(XGFdCZfGYTcZdo42sbxX56Lh89pAJ69tAyzJqWLXqD5588mHBedcg)YN)d(G8T0sVGbBrC4wbMnSW9aRgwewQjWziRfpBXDvA7z(pxSl8kIlGrLGUIdVAE41quw4lcVEE4nYU)(V4L69zGVe8LH3ko8UvrmySiCh7Gq4nzqLiwxbb(g8E(DTnKYii5bSKySWYRpt6ZUDVZonddcbJ4iPWxb(QWBBbdFagUjSwmmFqH(Y6CHNj9mEPkdVJfR(V1HVgmMeCllyfR1UWUqFAc5jBurC)E0avHzH5yLKjktdECggI6sXFUp8Qqc561GM39VKNhKAc2n)EE5L))e9ES5dib)9Cf)VafFS5dcj)7w8p8O53KBYhDS8zjOVgguHzLFz)tFF()OyBTzVZsVpPOe1yk64iIhgyZWE4CVbBeg9unbJ2aJZZc8rUg3Oni4ScKYy1rjZFFqjVL1o4KGWCyI)MGovQD(BmITIYiPgSVcmmOTX)yGsmOVHJZqS4aECiR3d2aEBbegcaENPMyu8ILFhYkpbE3vRJ3ZanFdZ24)pzfbZ(o55SoIa1qYh)3IB3Xc)HR(V)d

CP squares: 
>!WA:2!TF52ZTXvDCCl2qDJcP1wL42uceNuQNKsItSCUyktWvRT8LeBj5vYXoHqLo7UhPDDwT7MZURVXLsm3m3bbuOq5My4wBgUOG5wFHj)f8B80PpYm4N4bgyM8cpw(Do7Ahz7KMoqdthMUZyPDp756VFF((9NCSYjiXt4P0B3hV7tMOAc9e6lV)1uDy6uMmr7Y6mhx32KTmxCrctVZcoow(MURsc8nCyzD9nDS9IZwiB5YEu)r(ZtL75BbVAqS1W3NZX02xDG0zkKwPr4CoGJLd7Ssss5KWfmzaZY9Dz47769Kh7yZrQ40TPZXE)dE6XoFqFxX6y9YiAIL4ukE(eMFC1YM2MEgXLXV8JVKpZSsfkZltxSOBFwz)fCPYKagznVav6SuB)8bLlBoFJIdKkFHI5lKsPGIOD1rOelFd5aCUuDTilqzl55sTSgv3lEDvCu5nCMlR9n8eFLc3kZs3ywZXO4SQKpx6XgtXMuLIJrNYhvbChWgj9y5gAYXQfyhTZI3q30BMaBXSKKyz52orCFHW3pUJo9ATCtmIrz2eRZJhl8KpEnpQvzrGSUC2cfYo(yPhQaB2W32QSLdr)vyM2vyobUDOunatpXze(bM61b8(IR6tSWDl)wz8WPXVHf2ws(911nXoRHJBbrFWioLFtTapArnlINNSplGwZDw3BntkIx0LQhUWwufLSdpzAXGDSedMvomVfUQMlkACv1iEAZmGINgoVsQH8Hr9WVtRxHkNXXMwNrRGZepMQioKrDipoRhW9rmRy7WOrGyAEEjnJ5W8kDJWUfcM7s1JwfJzk9GyEY6(oArbW7)ih(GM6hCGCnkZWuyEFgXNiDZq8DiEt8fwn)akPtNjzGPEJH7Hn54QQNwRVuQAo2LnReVgX2SkHVdof8ogAvDK94puKtImpk2lDpODzB80CdkXJVku7k(gTUe)j(catixLyApeKfYbTdtakTc5XV29wBPoFYmdvDrkQrTXd4dZMpsc(uLF8)2Z8QV6)kH2fxUV6EUe2LNYu33ypWBd6VbrFMapFQ(4K5LG3(0740NO7tc3h0k0f06QIoR44l29XCBFtpZXt5utwilSZTRynmUSM2fSnp6X65M8SmprzRhMNJflMipdp4d0f02RaTRIsz)apwGTqhHAvFNLwpOLOhypk5CMdLICaKlnlb7dE31C5TXJO7e2BC4HG3j8EIdpm8iRY72gVSeSFOt4aXH371APUjgSkQToSjbp(4qgEgsep5X1OOCHT1YU3Al3CD2Du7Hyo2(glPsI8YgP))z)8RhvAK()h)f(1lhdnc8WZiEKOgY8THbCiP6OZHIaM9oBhq7n4Eu4Sue)B5oCpGpDE)IIpk7WqCQOBrFZQ4zJr1m5SQuTn6YbFC0uw8KNbr3zUnI0sRf266EgWLCFirl8GmNr1eWGCk8XBgUyOrHUOXRUAi2FHqsk2neVNZlMLxaAToJtc0cyJYzYMjn0odpq8(ux0XBfORfDkS9DBBiM5IDorarNlS6Sqb3enTTJwP91YMAD6WwLwv02CiKpfJ4U0ur3eUTMfdjQwuJOWqt1BQpAMmPvkYTjxDJnIqK1V7EVnb5WBu4XA9BnaU9YEJcirBOyU7)oLJ0xalayQzSChGTe4GPhWvKoGRaxcyGh4FviigmlQ0MdMhHRfGfdHYpc8rHp2(Ab(4sWZaFc4QgWsncpbkJo8ifGpf0p8PHpd8z3lSCm4ZzmBKSVi3wT1vJEiCJMerjO9AyAjS5ipWOuJapIAjk8vA9jJI2TU7DJY8P0mmrXzvuE25uoo6RVmoHbcvdQzfd)hdM6ApiC4ZdjljQwW1Zmd4KDbNconA4dDZT9HNK)5AcZezSaIo3jjzQbh0TnCqPImKewsLGDeh2fkrJdpqCy3XVHyqHr)PJbJhxErhNQXwZRQJJVroMtfg1ZZyRtKjk3EkwK8A11Djf62sWOWzRjmg8m1XkxIy8i7eiLAiwSreNSZW4j5agToozO3ULPNpwNqEGCD2t4MQq47Dp0O861y5o6LgGGkf7kYe2LMC0JERNoAEHpQyygWWyjNOLYuxNARKj95tRadusHy5AqKuMJRfhU5J(fIbNRXm5TNFmJuJNFOtJL75LVOgH27BuovQHdZetzcJ06JKvz0lMntHuJbt(eDPOzq1U8qqBsh0X9GFWZS0SeMjbrafH3PYSeRaAIEyAge7kuVhTlyf0z7Vob)kBSr6FL9WV6qAjx0eK71cMDbnW57iTaxpzQmdYN2ZCgvXY49e8fcUoSsyRWkjo(PG2qk)6lzAR5uvL4dRed(D8Lrc(9WlaFGn(9aRHXnTlVWGrfemwUpyArXlykRDdxyBLTGlgd(qOkBNWhgW476vzGIqjGaQ8ckGgOlQIaBT6buU5kgqL)RluaggG5TTMa8sgnZ2W1Ibw86aq13yCnGp528kEdAI)8B3ec(cTcFr4lHJ8ldFLWP(Rwc(Aqn4Rhd(gpwOPa8nVdMbWZcFRMY4Cv)tFRFNWZfd(vHBMVtm47AappQMHVh89lbV4WWpa(HHYv4hDgOo8JJuLjHFc8tHFwO8c(5WVafuWliXv7yLxu(0tQbvp0WxXoDQjGFPbALa)A43WfgciosuGe7Vfz1KHG5TL)ryTjWh(dra(F8ot8WFAlO(3UemtevJh1PoYUUlqDZqZBEP7zmAoh(wWDZWnAlX9Voxd5XNZtUp9Szp8vE9a3cqUjWoc27DZWDKy5Ur19EpNQFPMO6)(9FxO6NE7)JbVPeQBw9Hb73IQ3kvhHFCmDt8mNo5ancQBgOrWFZ88j48mY9VyUD07j6UpU5bsYipFUg2g69ELjlm2ezZ)AG2N4)zOn)aJh9TG2)htE3t1dCb3R5VgbtG)FTp9ux7(E9q1y6Tzr(ZX)12UvNEgNPSUOJYXVZK92SQ3gzFYiNA0Bh9ocH6i9YDMMp59wAUjr8mgjM9LN(F)d

Everything was shifted by ~1 pixel to the bottom and ~1 pixel to the left side.
