### ISSUE TITLE
Can't use custom texture

### ISSUE THREAD

**Issue by K41eb** [WeakAuras/WeakAuras2#270]
I'm using weakauras2 whithout any other addon and i just can't use my own textures for my custom weakaura textures. I tried almost everything for the pathname, my texture is  a .tga 128*128 (i've tried 256*256 to) picture file.

My path looks like this: \\Interface\aFolder\myTextureName

I get a green square 100% of the time, btw it's too bad weakaura wan't tell su whether it's a path problem or a file problem (type / number of pixels)

**Comment by Stanzilla** [comment]
remove the leading \ and use double \\ after
