### ISSUE TITLE
Missing an Elemental Shaman Buff: Spiritwalker's Grace

### ISSUE THREAD

**Issue by doubletrouble123** [WeakAuras/WeakAuras2#2700]
## Describe the bug

The Elemental Shaman ability "Spiritwalker's Grace" is not located under the "Buffs" category, despite being an ability selectable in the "Abilities" category. I'd love to see it under the Buffs catagory so that the aura is only visible when I'm using it, like other buffs.
**Do you have an error log of what happened?**

```plaintext
N/A
```

### To Reproduce

1. Open the WeakAuras UI as an Elemental Shaman.
2. Click on New Aura in the top left, then select 'From Template' on the right.
3. Click 'Icon' and choose any size.
4. Select 'Buffs' and see that 'Spiritwalker's Grace' is not there. 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

3.0.6

**Are you on World of Warcraft Classic or Retail?**

Retail

**Was it working in a previous version? If yes, which was the last good one?**

No clue

**Comment by InfusOnWoW** [comment]
This should be in the next release
