### ISSUE TITLE
Weak Aura bug (Can't open config menu after importing Legion weak aura accidentally)

### ISSUE THREAD

**Issue by Damenkata** [WeakAuras/WeakAuras2#2701]
## Describe the bug

I expected to import a weak aura and when I imported it , it would not let me open the config menu of Weak Aura afterwards. It printed some text in the chat box in-game that something has taken control of other things, dependency was compromised or something like that, I can't remember properly.
**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
2x WeakAuras\RegionTypes\Icon.lua:236: attempt to index local 'id' (a number value)
[string "@WeakAuras\RegionTypes\Icon.lua"]:236: in function `create'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:2833: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:2759: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras.lua"]:2794: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2325: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2332: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1009: in function <WeakAuras\WeakAuras.lua:981>

[string "@WeakAuras\WeakAuras-3.0.6.lua"]:1131: in function <WeakAuras\WeakAuras.lua:1082>
```

### To Reproduce

I imported a weak aura that I thought was currently up-to-date but it turned out that the aura was in version 7.0.1

**Screenshots**

Screenshots are not needed I think.
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I tried disabling all the addons and still the problem occurred , I still can't open the config menu of Weak Auras in-game
**Which version of WeakAuras are you using?**

I am using version 9.0.1 version of the addon.

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

I don't think that would help.
### Additional Info
I actually think that the problem is in the code itself, as mentioned above, I also tried erasing the code of the specific Legion aura that was out of date but still it did not help, I included the zip file untouched though.

**Comment by InfusOnWoW** [comment]
The problem is that for some reason the id field (that is the name) is a number not a string. I'm 100% sure no official weakauras release ever did that, so no idea what kind of strange import that was.

If you attach your current settings, I can fix that for you.

**Comment by Damenkata** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5524700/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
While there lots of your auras generate errors, I couldn't reproduce the specific error you have posted. And none of these errors prevented the opening of options.

Are you this is the WeakAuras.lua file from the right wow installation?

**Comment by Damenkata** [comment]
Positive, it is the right .lua file

**Comment by Damenkata** [comment]
I still get these errors from the ,,red bag" :
7x WeakAuras\RegionTypes\Icon.lua:236: attempt to index local 'id' (a number value)
[string "@WeakAuras\RegionTypes\Icon.lua"]:236: in function `create'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:2833: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:2759: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras.lua"]:2794: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2325: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2332: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1009: in function <WeakAuras\WeakAuras.lua:981>

[string "@WeakAuras\WeakAuras-3.0.6.lua"]:1131: in function <WeakAuras\WeakAuras.lua:1082>

**Comment by Damenkata** [comment]
I actually may have attached the wrong file, my bad. I have been trying yesterday to solve the problem on my own that I lost track of my files. This is certainly the right one :
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5525970/WeakAuras.zip)

**Comment by Damenkata** [comment]
I believe the problem could be solved if I revert the addon version back to 7.0.1 (like the specific addon). And hopefully it lets me open the config menu there and therefore delete the 7.0.1 weak aura.
What do you think ?

**Comment by InfusOnWoW** [comment]
that version does not work anymore.

**Comment by Damenkata** [comment]
These are the auras from the account folder , I am not sure if that is what you requested me to attach :
[WeakAuras_from_account_savedvariables.zip](https://github.com/WeakAuras/WeakAuras2/files/5526008/WeakAuras_from_account_savedvariables.zip)
I am yet again sorry for keeping you from doing your actual important stuff.

**Comment by InfusOnWoW** [comment]
This should work:
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5526057/WeakAuras.zip)

**Comment by Damenkata** [comment]
Which .lua file must I replace ?

**Comment by InfusOnWoW** [comment]
The WeakAuras.lua file in your WTF folder.

**Comment by Damenkata** [comment]
I appreciate your help very much ! Thank you a hundred times Infus, if I may call you this way!

**Comment by Damenkata** [comment]
It worked!

**Comment by Damenkata** [comment]
If you don't mind me asking , what was the problem actually ? I am studying software engineering myself as well.

**Comment by InfusOnWoW** [comment]
The id field should be a string, for some reason the id field was a number in one of your auras. So I suspect it was either a bug on wago that created the aura, or someone did something very strange.
