### ISSUE TITLE
Conflict in my simple buff trigger WA

### ISSUE THREAD

**Issue by oayorkshireman** [WeakAuras/WeakAuras2#2705]
Have a simple buff tracking weak aura, that for some reason has started to display the caution warning notice.
Warning reads "Forbidden function or table : loaded"

![](https://cdn.discordapp.com/attachments/218084462523711489/776581579962187786/unknown.png)

Weak aura string is https://wago.io/mgEe_HRRS

thanks

**Comment by InfusOnWoW** [comment]
You have a outdated version of the Zen aura installed.

**Comment by oayorkshireman** [comment]
zen aura? 
i have the same fault with a similar weak aura tracking blood dk bone shield?

**Comment by InfusOnWoW** [comment]
Yes, a very popular M+ aura access a) loaded, and b) infects random other auras with its code.

**Comment by oayorkshireman** [comment]
oh, i do have zen tracker for interupts? So thats infecting weak auras i make?
oh shame guess i need to remove it.

thanks, i didnt know that could happen

**Comment by InfusOnWoW** [comment]
I think there's a update to most of these auras, otherwise contact the author of that aura.
