### ISSUE TITLE
Add Specialization Status Trigger

### ISSUE THREAD

**Issue by jjholleman** [WeakAuras/WeakAuras2#2710]
**Is your feature request related to a problem? Please describe.**
Need to use custom code / duplicate auras for a simple status

**Describe the solution you'd like**
A Status Trigger for Specialization

**Describe alternatives you've considered**
Spell known trigger, custom code or duplicating auras and changing them for the different specs, e.g.; a soul shard bar but you want it to display differently based on your spec.

**Comment by InfusOnWoW** [comment]
Actually implemented
