### ISSUE TITLE
Weakauras not loading

### ISSUE THREAD

**Issue by szaragoza** [WeakAuras/WeakAuras2#2711]
1x WeakAuras\WeakAuras-3.0.6.lua:2801: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@WeakAuras\WeakAuras.lua"]:2801: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:2759: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras.lua"]:2794: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2325: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2332: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1009: in function <WeakAuras\WeakAuras.lua:981>

[string "@WeakAuras\WeakAuras-3.0.6.lua"]:1131: in function <WeakAuras\WeakAuras.lua:1082>

**Comment by InfusOnWoW** [comment]
Your settings are broken. I'd recommend restoring a backup. If you use the WeakAuras Companion that automatically creates backups.

**Comment by szaragoza** [comment]
I just downloaded these files. This is a completely new download of the addon after deleting all old files out of my add on folder
