### ISSUE TITLE
Weakauras not loading

### ISSUE THREAD

**Issue by szaragoza** [WeakAuras/WeakAuras2#2712]
Just downloaded the addon for the 100th time. After deleting all files from my addon folder. Addon still will not load in game. Cannot even access the option menu. Backups will not load either. Continue to receive this message. I've tried turning off all add ons, still no luck, tried deleting addons no luck. Tried changing resolutions, no luck. Someone help.

1x WeakAuras\WeakAuras-3.0.6.lua:2801: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@WeakAuras\WeakAuras.lua"]:2801: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:2759: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras.lua"]:2794: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2325: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2332: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1009: in function <WeakAuras\WeakAuras.lua:981>

[string "@WeakAuras\WeakAuras-3.0.6.lua"]:1131: in function <WeakAuras\WeakAuras.lua:1082>

**Comment by mrbuds** [comment]
Close the game and delete this file `WTF\Account\<Account #>\SavedVariables\WeakAuras.lua`
