### ISSUE TITLE
Custom Tooltips for Custom Triggers

### ISSUE THREAD

**Issue by leobolin** [WeakAuras/WeakAuras2#2714]
**Is your feature request related to a problem? Please describe.**
I would love the ability to be able to add a custom tooltip text to my custom trigger auras.

For example, I have an aura that displays the cooldown of the extra action bar, and I'd love to be able to give it a tooltip that lets me know what the ability does.

**Describe the solution you'd like**
It would be as simple as adding a function/field called "Tooltip Info" when defining a custom trigger, just like how "Duration Info", "Name Info" and "Icon Info" work right now.

**Describe alternatives you've considered**
I'm sure you could do it with some sort of hacky custom code implementation, but this solution seems more elegant.

**Comment by mrbuds** [comment]
You can do that with TSU by setting the property "tooltip" https://github.com/WeakAuras/WeakAuras2/wiki/Trigger-State-Updater-(TSU)#tooltips
