### ISSUE TITLE
Auras won't load since Shadowlands pre patch

### ISSUE THREAD

**Issue by Sylvanosa** [WeakAuras/WeakAuras2#2716]
I took Hyperion's DK aura and modified it to suit my preferences. I made variants of the aura for different specs and classes.

The auras have been working through the entirety of BFA but since the pre patch the auras won't load despite being there.

I tried updating the addon and disabling all other addons but both didn't work. Please advice, thanks!

Screenshot:
![image](https://user-images.githubusercontent.com/74540634/99246528-04dffd80-2838-11eb-819b-1cf583c2bc27.png)

Error message from bugsack:
https://pastebin.com/MaivMBSx

**Comment by InfusOnWoW** [comment]
Please fill out the default template, do not just delete it.

We are missing, your version and your setting.

Also are you sure you tried with all other addons disabled, that error message without the necessary context looks very much like a broken installation or another addon interferring
