### ISSUE TITLE
Auras won't load since Shadowlands pre-patch

### ISSUE THREAD

**Issue by Sylvanosa** [WeakAuras/WeakAuras2#2717]
## Describe the bug

I took Hyperion's DK aura and modified it to suit my preferences. I made variants of the aura for different specs and classes. The auras have been working through the entirety of BFA but since the pre patch the auras won't load despite being there. I tried updating the addon and disabling all other addons but both didn't work.

Expect to happen: load as usual.
What happened: auras stop/stuck loading at the first group.

**Do you have an error log of what happened?**

Error message from bugsack:
https://pastebin.com/MaivMBSx

### To Reproduce

I'm not sure why the error occurred but it happened when i resubbed for shadowlands pre-patch after a +- 3 months break. When I updated all my addons (including WA), only WA has problems that persists till today.

**Screenshots**

![image](https://user-images.githubusercontent.com/74540634/99253520-783b3c80-2843-11eb-9aa4-bc25e75d0fdd.png)

In the dynamic group, we can see that the auras are there, however it won't load. That is the first group out of all the groups that I made.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, error persists even without all my other addons

**Which version of WeakAuras are you using?**

3.0.6

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

The one in patch 8.3, at around July

**Comment by InfusOnWoW** [comment]
Can you attach your WeakAuras.lua file from your WTF folder?

**Comment by Sylvanosa** [comment]
[WeakAuras Backup.zip](https://github.com/WeakAuras/WeakAuras2/files/5548442/WeakAuras.Backup.zip)

**Comment by InfusOnWoW** [comment]
I can't reproduce the issue with those files. Looking at the back trace that looks like some kind of incomplete update. Can you try reinstalling WeakAuras?

**Comment by Sylvanosa** [comment]
Sorry for all the trouble, it seems that my other addons are corrupted (despite disabling it, it hinders WA2 from running). I deleted all my addons and reinstalled it and it works. Thank you for all the help!

**Comment by InfusOnWoW** [comment]
I'd be interested in that. So if you can figure out which addon it is and attach it as a zip.
