### ISSUE TITLE
Weakauras Archive - Causes disconnects

### ISSUE THREAD

**Issue by Marscgm** [WeakAuras/WeakAuras2#2720]
## Describe the bug

Keep getting kicked from game (wow51900319) whenever Weakauras Archive is enabled. Interestingly enough, only occurs on my Warrior. Seems to occur any time I'm in Icecrown and only occassionally elsewhere.

**Do you have an error log of what happened?**
Error kills my log-in and puts me to the log in screen.

### To Reproduce
Log in -> Get kicked from game

Log in -> Get kicked from game

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.0.6

**Are you on World of Warcraft Classic or Retail?**
Retail

**Was it working in a previous version? If yes, which was the last good one?**
Every prior version prior to this wow patch.

**Comment by emptyrivers** [comment]
I'm going to need your saved variables to investigate this. Navigate to `World of Warcraft\_retail_\WTF\Account\<Account #>\SavedVariables\`, find the `WeakAuras.lua` and `WeakAurasArchive.lua` files, and upload them here.

**Comment by InfusOnWoW** [comment]
No response from reporter. If you add the necessary information, we'll take another look at this ticket. But without that, there's nothing we can do.

**Comment by Marscgm** [comment]
I only see SavedVariables.lua in that folder. So World of Warcraft\_retail_\WTF\Account\<Account #>, then it stops. Tried looking into the character folder but there's no WeakAuras.lua there either.

**Comment by InfusOnWoW** [comment]
Those files exist, so you are likely looking at a different installation of wow.

**Comment by codedbymatt** [comment]
i am having this issue as well but its only on one specific toon? should i make a new topic?

**Comment by mrbuds** [comment]
> 
> 
> i am having this issue as well but its only on one specific toon? should i make a new topic?

Yes, and please provide more details than OP as rivers asked
