### ISSUE TITLE
Automatic Icon not working

### ISSUE THREAD

**Issue by Caza4** [WeakAuras/WeakAuras2#2721]
## Describe the bug

**Do you have an error log of what happened?**
No

```plaintext
PASTE ERROR HERE
```

### To Reproduce

1. Create new Aura
2. Icon Type
3. Add a trigger to track a buff/cooldown progress
4. WA doesn't recognize the buff/spell automatically and the Icon must be set manually in the display tab.

**Screenshots**

![WoWScrnShot_111620_220420](https://user-images.githubusercontent.com/43317711/99328430-57dba400-287c-11eb-81e1-7391686333cd.jpg)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes
**Which version of WeakAuras are you using?**

3.0.6
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes, 3.0.5
### Additional Info
WeakAuras is no longer able to recognize icons automatically. If I try to create a new Icon type WA i get a question mark instead of the Icon(see image attached) but if I duplicate a pre-existing WA (created before the latest update) and just change the trigger the WA recognizes the new spell/buff Icon automatically. I guess the issue is related to the new display feature.

**Comment by Maczuga** [comment]
Broken with the introduction of fallback / dynamic / trigger icon source. Some code still refers to data.auto variable which does not exist in new auras.

Fix is here: https://github.com/Maczuga/WeakAuras2-MoP/commit/eae902ca8ea7521dd830130c30d5667da05cad9a

Can't really do a pull request atm. Hopefully the WeakAuras stuff will be able to pull this.
