### ISSUE TITLE
WeakAuras (don't show when not active) Shadow Priest

### ISSUE THREAD

**Issue by Gavamalas** [WeakAuras/WeakAuras2#2723]
Hi guys,

I'm newbie with Wa and trying to do my own cd bars etc..
I do have a debuff bar on target which shows time left... which i want.
I just can't configure the option with the spell to show this bar glowing but only when spell is ready to use.

Here is the sdtring.
Help me plz :)

!WA:2!9zvtSTrUvyROMeeJfO2kBmYge0ojORr2U7A46K4fOaTPAKLwPwhj1rk)SObvIZmuZW4rKmKCKT8HweDYxRaAV1EqN7jDR7PcJ27ec9ypzuuGE1h65(iNX)KGT7ayzYhjF)8X377Xc1knSuyPWJE8mjhj27fKqv8TMrcy0oSuraUG4GwdgiXQ)wjX4Sr)ZRmhrdIzI2mcv5xPAZUv9wypUhtHuegTaF13z(tzHy3YpRBRt9rb7fjyP0WkSeM4NxOqH2f3CJhprjirryH8xVUiF4)vKkXnrdX9pfg0le7NoyqLeKugFIm1hpctvDarKdM3Rs5oD71PBzVUNVuBbgwYRt7Q7URGTpTfnzCFp7s(1XOevShfuU8o8v2bpccwcnYPDckkfpXyVukr1FkkvGY2M)dF4JF02FXejhNK0iuENBF1V3EUMD5RqIiS64byvqCxglrr4XNK78TrkfwqJDvJ5ypJ62AwwO0feiQx27P1E2UttP5r9YRR)GJULNsaaLlkvXMBCMGyJjKXlIWuSGe0jMTFl6CP9FEyu4y9D95jOXyXuRdAmTXb5RKF0EmWAiftu6NkYfvAt99f1RUBBWbePul0Ox3449S6OcCnPIxiaWQZL1P(d5Fufimdbu1PTGfjWsPZdS75t430CE8bOavVZ9K(hBesu4HDsyQ(lo3e2fNecOIjnP0psV6v0F3ROD8LqItQCQzJwOOpFvZ43j87R)bRPFG(tMhsKVoLgOiJWBHOJ5RISJ7MHOMKV)8s2C6Eb2KUIW3mqDNDx5ztwJNIOKHwhzBpW(cvTfN5z9m3Ecjg0rOu74szu8XyKe3rjW0iv81NyMzUs174oerO10U6kAh9o6QxxxtVJ)acLiJFFXZmAKymH8oR7feJd2BB9h8zlnzesqq(j4Tk3ChFRC5pgw5Q6FXClY9mPzvVrOKuCXSfool1K6HOryDRCPZy0ZUS0TkyU7HvL)W11T6pHlmzfQXZGIMn2EJOe2(lpXhjYQnR)K)LY(v)j)9FV57pu)j)N)I57Rlc5Ws4gcqhC8Xw4lJC4Rky0LhoYerVE0CFMiel6jjhIV6I8jzShBb25mjm7zlCC(0lULojxYiIKaHB8z6dhgH5R25nPib2PwAsIZlIH0lTZuW6z7znTZCt5gyMEWFhTgVKcFaKugJaS4LzUBXPwzMF2Y5J58vU0woNGQ4jzsXjdSuE6BWVPvIP80KWeyPnDldtp1Uaq8GdTcF7ISO9RALhI21FDQurgmwFTzcddjUli0ZRXxwVR2rarGztZS78cOiZthWOk(k1eKdD(LPOqa)roD7(oHwUPU7slo)eM8s3MqoBMO9ba6fceFYlYhK5v5GC)Cu4sK8ZB0SzvVEwpKFVZHmq3ci(7X7PidX94cCaOcgTi)J(g2t2apZwdVW16azg3lhKYVukW)())mr4yGmMeeF0n1bf1HLC0dS3q6i9n0XAI(1VvVxbDI(A6HUnB1SkuQX0ClaQFJwOL3Dj9i9(ALovpEwwyTB1AD1)M7P)Tf0h0)Ope083G)lZhavUH3)JLFl2v)2VvJoVrLwn7L118CR(VxyQ9QjWVjftdg3(7S5gB94SCbZcg6ZVmjpLmEIrK5kDHFQsXOTgHfa1)mJ4DTSr3AUz8z5CtJo7OwxY1mn2AWUXKG9Oa7Dr7E6eGsWfTNn)2x)RSZE5L10Ue4eRATMRTsl2pgtIIvH3qyiEHc)T1LxteY6zTKU(YUa3NATPGKaiZNnm2nHHcFULEpW0rV)K8wcb9Dn)UUVeAhNGVU3WuGIEzp7Uwx)h9B71OANU6)0YUgoL1GbNyPFCtW0qdv)wL3zh(kG6khAkZWH4WNIoiw)PMwxNcjZq3yuYZb2CWtB5TVPkT(p7rlDJ)6slT0cOKgc7wCBySC2JIUa6oroKXuXN1ZR)7BhcnEMWY9zBUNt)mFGaAZbDkGI1I(aH)as0YtT9JKe4HrM8pxZ0(3NeYV37)AeNDSpxWiOR9HgZTEvDlM)t43MerzcCUlx10eVQqWeY(z8YgULubM)GgMqFaka)QkiG(Hg5IeV6zn(8lM95DSi5Hm2Wc61JNPybJYWPBxO3Vl3SKWqm1Rz1Nx1tOY19QUjKdpejcD8qKqhqvEOeEmQ4PzPr1maGbs87uXRA1MxUJXllSvkjCoEFVhT7M1A3AZVaIDJzXXtVGY9AZzcceA2UX8vaJ3TrLY72RrtyyNQMNayE(tdaf5F2frQzU8v2(I5SJW7iZHxE2B9cYBo2VK07HBS5gBxA0)4L)Vp

**Comment by Gavamalas** [comment]
I managed to set it up on Action Usable but i want it to glow and show only when target is avbailable.

**Comment by InfusOnWoW** [comment]
This is a BUG tracker. If you need help with configuring weakauras, seek it on our discord.
