### ISSUE TITLE
Icon 134020 missing from selection list (Smoked Desert Dumplings)

### ISSUE THREAD

**Issue by lvangh** [WeakAuras/WeakAuras2#2725]
## Describe the bug
The icon for desert dumplings does not appear in the icon browser. 

**Do you have an error log of what happened?**
No error.

```plaintext
No error.
```

### To Reproduce
Search for "smoked" or search by icon number 134020.

1. Go to WA
2. Click on New Aura Icon
3. Scroll down to choose Icon
4. Can't find icon

**Screenshots**

![image](https://user-images.githubusercontent.com/19690096/99463833-7cbb3000-28eb-11eb-972f-b82d4b999492.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Not applicable

**Which version of WeakAuras are you using?**
3.06 classic

**Are you on World of Warcraft Classic or Retail?**

- [x] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
No

**Comment by InfusOnWoW** [comment]
The icon browser creates a list of icons by enumerating all spells.

Enumerating all items is pratically impossible.
