### ISSUE TITLE
When uiScale is less than 0.64, change the text size in TextEditor to make it easier to read

### ISSUE THREAD

**Issue by JerichoZG** [WeakAuras/WeakAuras2#2726]
TextEditor.lua
Add the following code on line 161

  if (fontPath) then
    local Value, _, _, _, _, _, _ = GetCVarInfo("uiScale")
    local uiScaleValue = tonumber(Value)
    if uiScaleValue >= 0.64 then
      editor.editBox:SetFont(fontPath, 12)
    else
      editor.editBox:SetFont(fontPath, 24)
    end
  end

**Comment by InfusOnWoW** [comment]
Eh, well maybe not choose a ui scale that doesn't work for your monitor?
