### ISSUE TITLE
2 crash lightning buffs

### ISSUE THREAD

**Issue by Mynameistakenalready** [WeakAuras/WeakAuras2#2727]
## Describe the bug
 Creating 2 icons:
187878- Crash lightning (enabling stormstrike and lava lash to do cleave damage)
333964- Crash lightning (buffing damage of crash lightning 20% for every stack)
What is happening:
Both icons are active, while 1 of those buffs is active. Overlapping names propably cause this issue even with diffrent IDs

**Which version of WeakAuras are you using?**
3.0.6

- [X ] Retail

**Comment by InfusOnWoW** [comment]
That's because your auras are misconfigured. You've likely put the spell ids into the name field.
