### ISSUE TITLE
Missing Aura trigger bugged

### ISSUE THREAD

**Issue by Fr4mby** [WeakAuras/WeakAuras2#2728]
## Describe the bug

When i setup an icon with a trigger configured as a missing aura on a player buff, it's supposed to show the icon when the buff is not up, but the trigger is always true, even if the buff is there.

**Do you have an error log of what happened?**

no error displayed.

### To Reproduce

1. Just setup an icon from "aura" type on the unit "player" from the "buff" type.
2. Setup the spell ID you're tracking (use a mount buff ID for example, easy to check the presence of the buff or not).
3. display on "missing aura".

The icon will be always displayed, even if the buff is there.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
i tried to disable elvui, same issue.

**Which version of WeakAuras are you using?**
I'm using the 3.1.0 version. By the way, i didn't have the issue before this version.

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
if i properly remember, i was on the 3.0.6 version before this last upgrade.

**Comment by Ra1dMaX** [comment]
same issue with a crapload of weakauras. auras that are only supposed to show when a buff is missing is now showing all the time after the 3.1.0 version

**Comment by YudiH** [comment]
yep

**Comment by Fr4mby** [comment]
i just tested the changed into the bufftrigger2.lua and it worked perfectly.
Thank you for your fast answer 👍
