### ISSUE TITLE
Fort aura missing wa bugged after recent update. 

### ISSUE THREAD

**Issue by YudiH** [WeakAuras/WeakAuras2#2729]
## Describe the bug

Just a simple wa to show only when fort buff is missing. Now its still showing even when I have fort. Relogged and redo the on show criteria to no avail.

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

I only updated through the twitch app and logged into wow. Forted and the icon is still showing.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No I have not. I just updated elvui too. I might try this after.

**Which version of WeakAuras are you using?**

3.1.0

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes it was fine until I updated just now.

**Comment by InfusOnWoW** [comment]
Duplicate.
