### ISSUE TITLE
Script ran too long upon deleting/duplicating dynamic group

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2731]
## Describe the bug
I tried to delete a dynamic group which lead to a pc freeze, the errors below, and the dynamic group not being deleted.
Upon reload I was able to delete it without freeze.

**Do you have an error log of what happened?**

```plaintext
1x WeakAuras\RegionTypes\DynamicGroup.lua:776: script ran too long
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:776: in function <WeakAuras\RegionTypes\DynamicGroup.lua:774>
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1215: in function `Resize'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1198: in function `DoPositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1048: in function `PositionChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1029: in function `SortUpdatedChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:926: in function `ReloadControlledChildren'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1255: in function `modify'
[string "@WeakAuras\WeakAuras-3.1.1.lua"]:2864: in function `SetRegion'
[string "@WeakAuras\WeakAuras-3.1.1.lua"]:2693: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras-3.1.1.lua"]:2794: in function `Add'
[string "@WeakAurasOptions\WeakAurasOptions-3.1.1.lua"]:88: in function `DuplicateAura'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:651: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:905: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
--
3x WeakAurasOptions\WeakAurasOptions-3.1.1.lua:445: attempt to index local 'data' (a nil value)
--
3x WeakAuras\WeakAuras-3.1.1.lua:1762: attempt to index field '?' (a nil value)
```
don't have the remaining errors

### To Reproduce
Tried few things but the only thing I could reproduce is the "script ran too long" by duplicating the dynamic group from https://wago.io/slraid1 (not reliably though, mostly doesn't error)

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no

**Which version of WeakAuras are you using?**
3.1.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
I made Duplicate Aura quite a bit faster, but couldn't reproduce the issue with Deleting it.

The optimization I employ these actions is to suspend the dynamic group while doing the mass edits on a group. So I suspect that there might be a bug where that suspension is broken by a previous action, which then manifests much later.
