### ISSUE TITLE
Options not working under 'From Template'

### ISSUE THREAD

**Issue by Shaggy0708** [WeakAuras/WeakAuras2#2733]
## Describe the bug

Clicking on 'From Template' and trying to use any of the options within does nothing. For example, when I click on 'Progress Bar' it does not load the next page. 

**Do you have an error log of what happened?**

```plaintext
No error
```

### To Reproduce

1. Go to 'From Template'
2. Click on 'Any of the options'

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes
**Which version of WeakAuras are you using?**

3.1.1
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by mrbuds** [comment]
Did you install bugsack & buggrabber and are you sure you don't get any error ?

**Comment by Shaggy0708** [comment]
For some reason the bug addons were disabled. Here is what I get when opening WeakAuras

4x ...ceWeakAurasOptions\RegionOptions\AuraBar.lua:488: attempt to index field 'orientation' (a nil value)
[string "@WeakAurasOptions\RegionOptions\AuraBar.lua"]:488: in function <...ceWeakAurasOptions\RegionOptions\AuraBar.lua:477>
[string "@WeakAuras\WeakAuras-3.1.1.lua"]:448: in function `acquireThumbnail'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasNewButton.lua"]:60: in function `SetThumbnail'
[string "@WeakAurasTemplates\TriggerTemplates.lua"]:1302: in function <...rfaceWeakAurasTemplates\TriggerTemplates.lua:1293>
[string "@WeakAurasTemplates\TriggerTemplates.lua"]:1617: in function <...rfaceWeakAurasTemplates\TriggerTemplates.lua:1605>
[string "@WeakAurasTemplates\TriggerTemplates.lua"]:1288: in function <...rfaceWeakAurasTemplates\TriggerTemplates.lua:1287>

Locals:
parent = WeakAurasDisplayButton18 {
 0 = <userdata>
 highlight = <unnamed> {
 }
 obj = <table> {
 }
 text = WeakAurasDisplayButton18Text {
 }
 width = 570
 toggleFunc = <function> defined @SharedXML\OptionsFrameTemplates.lua:164
 title = <unnamed> {
 }
 height = 40
 toggle = WeakAurasDisplayButton18Toggle {
 }
 background = <unnamed> {
 }
 icon = <unnamed> {
 }
 description = ""
}
borderframe = <unnamed> {
 0 = <userdata>
 region = <unnamed> {
 }
 texture = <unnamed> {
 }
 icon = <unnamed> {
 }
 bar = <unnamed> {
 }
}
data = <table> {
 inverse = true
 height = 30
 smoothProgress = true
 barColor = <table> {
 }
 width = 200
}
fullModify = nil
width = 26
height = 15
region = <unnamed> {
 0 = <userdata>
}
bar = <unnamed> {
 0 = <userdata>
}
texture = <unnamed> {
 0 = <userdata>
}
icon = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = WeakAurasDisplayButton18 {
 0 = <userdata>
 highlight = <unnamed> {
 }
 obj = <table> {
 }
 text = WeakAurasDisplayButton18Text {
 }
 width = 570
 toggleFunc = <function> defined @SharedXML\OptionsFrameTemplates.lua:164
 title = <unnamed> {
 }
 height = 40
 toggle = WeakAurasDisplayButton18Toggle {
 }
 background = <unnamed> {
 }
 icon = <unnamed> {
 }
 description = ""
}
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'orientation' (a nil value)"
SharedMedia = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:293
 GetDefault = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:289
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:280
 GetGlobal = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:276
 List = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:266
 HashTable = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:262
 MediaTable = <table> {
 }
 RegisterCallback = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IsValid = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:258
 LOCALE_BIT_zhCN = 4
 UnregisterCallback = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Fetch = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:251
 DefaultMedia = <table> {
 }
 Register = <function> defined @BugSack\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:218
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}

**Comment by InfusOnWoW** [comment]
I can't reproduce that.

After looking at the code, there doesn't appear any way to actually get into the state you have. There's code in the addon that prevents orientation from being nil.

Thus that leaves two possiblities.
a) Your WeakAuras installation is incomplete, or 

b) We recently had a bug report where a disabled add-on broke WeakAuras, so I'd suggest temporarily moving all other addons out of the addon folder.
