### ISSUE TITLE
ability to ADD a custom name to a trigger

### ISSUE THREAD

**Issue by Nivius** [WeakAuras/WeakAuras2#2735]
**Is your feature request related to a problem? Please describe.**
When we make more and more complicated weakauras it can be sligtly hard to remember what trigger is what. i have a fairly bad memory and either i need to write it down on a paper/notepad, or just recheck all the time. able to give them a short name like "Mortal Strike CD trigger" or "Target have debuff X"
my example isnt that complicated, but i do have some stuff with 8++ triggers, and it can get really confusing

**Describe the solution you'd like**
Before sort arrows, add "name note" icon, adds either a clear name after "trigger 1 - name" or even fully replace "trigger 1" to whatever we want. (keep Trigger 1 behind the curtain so to speak)

**Describe alternatives you've considered**
hoverable icon next to "trigger 1 [¤]" that shows attached note

**Additional context**
Example ugly image:
https://i.imgur.com/NsSHbun.png

//
Thanks for making this great addon!

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/705
