### ISSUE TITLE
I can't seem to open WeakAuras. 

### ISSUE THREAD

**Issue by Ephera** [WeakAuras/WeakAuras2#2736]
## Describe the bug

I typed /wa and the addon didn't open. I also typed /weakauras and still, it didn't open. I disabled all the addon, but weakauras, and the addon still didn't open. 
**Do you have an error log of what happened?**

```plaintext
33x WeakAuras\WeakAuras-3.1.1.lua:2801: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@WeakAuras\WeakAuras.lua"]:2801: in function `SetRegion'
[string "@WeakAuras\WeakAuras.lua"]:2759: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras.lua"]:2794: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2325: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2332: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1009: in function <WeakAuras\WeakAuras.lua:981>

[string "@WeakAuras\WeakAuras-3.1.1.lua"]:1131: in function <WeakAuras\WeakAuras.lua:1082>
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, the problem persisted
**Which version of WeakAuras are you using?**

3.1.1
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

I don't particularly remember which version of WeakAuras I was using, but I do remember using it in BFA, and it was working.

**Comment by mrbuds** [comment]
It's an unrecoverable issue that happened when you reverted to an older version that has been fixed since, but your data is still corrupted.

You will have to restore a backup from when it was working, or reset your weakauras data at start from scratch.

To do that, close the game and delete `WTF\Account\<Account #>\SavedVariables\WeakAuras.lua`
