### ISSUE TITLE
Group Custom Anchors Code Editor won't show Code

### ISSUE THREAD

**Issue by Geko1990** [WeakAuras/WeakAuras2#2737]
## Describe the bug
Just wanted to test the anchor snippet from https://github.com/WeakAuras/WeakAuras2/wiki/Custom-Anchor. I didnt open the editor via expand and just copy pasted the snipped into the window. When clicked on accept bug-grabber cried and i got the error. When i click on Expand then the code i inserted is not appearing inside.

**Do you have an error log of what happened?**
Yes

```plaintext
[string "--[==[ Error in 'Davion M+ Experimental Nam..."]:2: attempt to index field 'state' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:4946: in function <WeakAuras\WeakAuras.lua:4867>
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:4973: in function `AnchorFrame'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:570: in function `modify'
[string "@WeakAuras\RegionTypes\Group-Group.lua"]:82: in function `modify'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:2864: in function `SetRegion'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:2693: in function <WeakAuras\WeakAuras.lua:2665>
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:2794: in function `Add'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:2341: in function `AddMany'
[string "@WeakAuras\WeakAuras-3.0.6.lua"]:1009: in function <WeakAuras\WeakAuras.lua:981>
```

### To Reproduce
Just Open a Group with a Single Icon inside. Try to write a Custom Anchor without expanding the editor. Click accept. Bug should appear.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes Bug appears only with weakauras too

**Which version of WeakAuras are you using?**
3.1.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I dont know because i just started writing custom code. but it appeared in 3.0.6 too.

**Comment by InfusOnWoW** [comment]
You pasted that into the groups custom anchor instead of the icon's group anchor.

Do note, that this is a bug tracker for the addon. If you need help ask on the discord.
