### ISSUE TITLE
long-time custom Sound not stop

### ISSUE THREAD

**Issue by q513902026** [WeakAuras/WeakAuras2#2742]
## Describe the bug

When I use the custom long-time sound playback trigger to reloadUI, the sound will not stop correctly and must wait until it is finished playing. 
**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```
no error
### To Reproduce

1.https://wago.io/hHVSSqJx8 use this temp wa
2. reloadUI in combat

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

WeakAuras 3.1.1
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

in a previous not work
### Additional Info

I tried to make a wa string to fix it
https://wago.io/Bc0B-DKuk but this wa only work in WeakAuras 3.0.1,
must write the table WeakAurasSaved ,save soundhandler to icon date

temp WA and fix WA use this sound.  
[sound.zip](https://github.com/WeakAuras/WeakAuras2/files/5571562/sound.zip)

**Comment by InfusOnWoW** [comment]
That's how the wow api works. We can't stop any sounds on reloading the UI.

**Comment by q513902026** [comment]
if icon save soundhandler , when ui reloading over ,icon can stop last play sound

**Comment by InfusOnWoW** [comment]
Yes, but we can't distinguish between a reloadui and a player login in. And to store sound handlers is wrong for the second case.

And in any case, this is far too strange of a edge case to care about. It's argueably a bug in WoW's handling of the UI.

**Comment by q513902026** [comment]
Using PLAYER_ENTERING_WORLD  event can distinguish between a reloadui and a player login in


`frame:RegisterEvent("PLAYER_ENTERING_WORLD")
frame:SetScript("OnEvent",function(self,event,isInit,isReloadUI)
     print(isInit,isReloadUI)
end)`
when player login in
> true false
when reloadui
> false true

**Comment by InfusOnWoW** [comment]
I didn't actually know that the event caried that information. So thanks for that.

Still, I don't feel like saving all sound handler ids just in case of a reload ui.

**Comment by q513902026** [comment]
OK, I understand and thanks. my fix wa string  before can't save soundhandler for the weakaurassaved table due to the wa version update, so I came to ask if wa can save sound handler

Thank you for your answer. I use translation software for most of my answers
