### ISSUE TITLE
Flametongue enchant not being recognized in certain scenarios with Better Wardrobe Tooltips enabled

### ISSUE THREAD

**Issue by linaori** [WeakAuras/WeakAuras2#2743]
## Describe the bug
Occasionally I found that my WA alerting me that I'm missing a Flametongue enchant, was reporting this while I already have the enchant on me. 

**Do you have an error log of what happened?**
No. I installed bugsack and buggrabber to see, I did get an error in tomtom, but nothing that seems related to this.

### To Reproduce
1. Install BetterWardrobe and enable it + the tooltips
2. Import the attached weak aura on a shaman with a staff
3. Cast Flametongue
4. Log off
5. Log on
6. See the aura being active while Flametongue is applied

Occasionally I seem to get this bug while joining/leaving raids or epic battle grounds. Reload does not trigger it, in fact fixes it.

**Screenshots**
![image](https://user-images.githubusercontent.com/1754678/99829955-47b61400-2b5d-11eb-9fdf-7e012a22501e.png)
![image](https://user-images.githubusercontent.com/1754678/99828964-f35e6480-2b5b-11eb-9ed7-04307d4112fb.png)
![image](https://user-images.githubusercontent.com/1754678/99828991-fbb69f80-2b5b-11eb-9658-822159bd6921.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
When all addons besides the better wardrobe options are disabled, it works. When I have all addons besides of better wardrobe options enabled, it also works. As soon as I enable the addon, it starts failing according to the reproducer.

**Which version of WeakAuras are you using?**
3.3.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
No clue, I only recently created it

### Additional Info
I suspect it's related to better wardrobe injecting info in the tooltip of the weapon in the player buff list. 

Weak Aura string:
```
!WA:2!nr1tVTrru8ezqb5diQf0evUeHqgKOkQjTjTG4aEdRjb5eB21PTOEW7S7(2Dg66z2oZS(p9eYId9gs(taYN5K)iKpbJSq8biFeYDK4nJJfSNE)BFVFZV3Vz2UDJHnsBK(UpFblrWdfvYey7GerHq(J1Wp50UzzkqF239R7T1(BT1wlj8eQq2tW464t9VSVFWQeHOivmMhoMvcrxVX1pnhOE2(gntlz55GuDzt5DMVBxjGTIW1lBxqgcAbpVcMtQKeo6QEq5h1HLt1CgpF)qkdksLyt7YlMgDJQkggbCDpjKXMee2ZVtNfvCM2FctPv0fvkyWyGuIZErkexLL1FAjipZVtV2x1zwkofntWBCONgJhR0eDLAM9VSDjswXD93JuPfUMPOIXD5rlT23H7Oaxn38c3C23FD0BSvqIvcz8fIu4)WAicc2KLdoTvy)bH9Bf0xILEjEwJMPkHIIZtv1xnKOtOGk0nUvRN6fmLczH41EMMbocQUNfQXLfKPGmE9H1BiHXNxXVJJBA(cttZxzE4YuM6xQ4jA2i4icFA59io7(RRZc0)CRBXvki5KINJlkKC(PBFnaLTqSLOdS0fDoHZg6iUtcqktQBB21Jl4W1arbHACJMRP7SAd9oWsUsfGsGu1mBn2TG5yZdFUz34sjGklZxJ(p18mZj7y(MGYQcfeNX4mffBoMcdBZIvHlsfUMWwd0fiRga54mup4VxLxig3wcVPc3mt79Ep6GJo2Zgl6AKH)b04uRGMoZgZIGvXvAuV1Deir2BHnChh0)KLw7FETMF755B(v3DbZUsCQ2yUQE5)VQWesbuZbK(uwYR5GsvZLPddTVNBgEczkiPXuWkSFLxHGKMn3QxskikvKZ0k8qO60CiZtdC5AgBvafqC4zTUO1LbdRk0S6E2kAAcRzU6dJ2jYtXElCFZv1xiDuJJS)aPDvJ80jMNu3djwDDZ3wFfkSXRXDlDPQpBZDwQvPyLuNJ7S4dF8Xp7WNu(XBY2hMO)EMIexaPuV3ked328Prl0IKrRLm7T9G5Fglv(Iw7RbLogBsglV(YmjQyr9brtQD76xqABdzryC4Pb((xkNS5LMF73)N)aFP5Okw6YSELhD(xkE65V5rsg3ofGgmMLQPVkGuusj1wyfxS1hJLmEMqUwHE)Y9y5CHeU7m6BVd6lLcjs0kOiZ9eM59BOcE8bhEWHng9xV8F)

```

**Comment by InfusOnWoW** [comment]
Well, that doesn't sound like a bug on our end?

**Comment by linaori** [comment]
Nice, you closed my bug report faster than it took me to write it.

It does sound like a bug on the end of weak auras, because there are certain scenarios where weak auras do not detect the enchant while it's there, and this only happens during certain loading scenarios. This because when I cast Flametongue, it's properly detected, it just "forgets" about Flametongue in these scenarios, that's a bug in WA. 

I have no idea about the weak aura code, so I can't really dig into this and try to find out why it's not being detected in this scenario, and I highly doubt that if I report this issue at Better Wardrobe, they'll tell me the exact same "It's not a bug in our addon because WA doesn't detect it properly".

**Comment by linaori** [comment]
@InfusOnWoW The addon I mentioned does the following:
```lua
local frame = CreateFrame("FRAME");
frame:RegisterEvent("PLAYER_ENTERING_WORLD");
local function eventHandler(self, event, ...)
 LoadAddOn("Blizzard_Collections")
end
frame:SetScript("OnEvent", eventHandler);
```

It seems to not do anything weird, just loads a Blizzard Addon.

**Comment by InfusOnWoW** [comment]
That's one of the addons, the other addon is sure to contain more code. And presumably they modify tooltips in a incompatible way. If they do that, then clearly their modification is the problem.

The code in WeakAuras that parses the enchant name is in the function getTenchName

**Comment by linaori** [comment]
Thanks, I'll take a look at it!
