### ISSUE TITLE
Checkbox for Ticks to act as masks and hide content below

### ISSUE THREAD

**Issue by IngEyn** [WeakAuras/WeakAuras2#2745]
**Is your feature request related to a problem? Please describe.**
I'd keep all of my character's resources as bars in one dynamic group throughout all classes. This allows me to log in my rogue and the group would only load the health, energy and combo points bars and, since it's dynamic, snap them together so that there are no gaps in between the bars. Now, when I'd like to make the combo points bar look more like individual points by seperating the bar itself into five smaller bars, there is currently no way to do so.

**Describe the solution you'd like**
I'd suggest to add a checkbox to the Tick feature which allows the Tick to basically hide everything it would cover and that is in a lower layer than the Tick itself, while making the Tick itself invisible. That way the Tick would effectively work as a separation for individual bars.

**Describe alternatives you've considered**
Another way of implementing this would be that one could add groups to groups. While the Tick feature would be the simpler solution, adding groups to groups would be the more useful but more difficult one, I'd assume. That way, instead of having one combo points bar, I could have my higher group load health, energy and the lower combo points group, which would include five individual combo points as bars.

**Additional context**
I did try out multiple workarounds but noting worked the way this would work. I know that this specific scenario would be realizable through normal groups but having to convert all of those bars into individual groups removes a lot of the functionality my initial group has and would add more complexity than it would need to.

**Comment by InfusOnWoW** [comment]
That's not any graphics engine works. You cannot make stuff invisible by layering other things on top of it.

As to groups in groups, we have a ticket for that already.
