### ISSUE TITLE
Auras located at the top of the screen (y = 539) show as "Aura is Off screen"

### ISSUE THREAD

**Issue by Mawkes** [WeakAuras/WeakAuras2#2747]
## Describe the bug
Auras located at the top of the screen (y = 539) show as "Aura is Off screen"

### To Reproduce
Try to place an aura, e.g. a 1x1 pixel in size, at the top of your screen (i.e. y = 539 on a 1080 resolution).

**Which version of WeakAuras are you using?**
3.1.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes. This issue is not present in 3.1.1

**Comment by InfusOnWoW** [comment]
That's intended. If a aura is right at the border we already consider it off-screen.

**Comment by Mawkes** [comment]
Well, the problem is that I need to move down the aura down some 25 pixels before it starts showing again.

What's the reasoning behind this "margin" btw?

**Comment by InfusOnWoW** [comment]
That auras that are almost entirely off screen are almost as hard to see as auras that are beyond the actual edge. For that reason anything that is less than the 30px from the border is considered off-screen already.

**Comment by Mawkes** [comment]
Would it be possible to make this "hard margin" adjustable for people like me who wish to put auras at the border?

**Comment by InfusOnWoW** [comment]
It's just a arrow reminding you where the aura is while the options are open. I don't see why that is a huge deal in any case.

If you want to have the arrow not appear, then you need to design a better approach and create a pull request implementing it.

**Comment by Mawkes** [comment]
No, it's not just the arrow appearing. The aura itself is hidden in 3.1.2 if it's placed within 30px of the screen edge.

**Comment by InfusOnWoW** [comment]
Then I need a example aura that clearly shows that problem.

**Comment by Mawkes** [comment]
I provided clear repro steps.. :)

Just try placing an aura 1x1 at the top edge of the screen and you'll see the result.

**Comment by InfusOnWoW** [comment]
!WA:2!Dr1tVnoru8gfqGS0I2gwwXkXHLkbcXbekc694SoBlknj7y3TD5s6y7NZmSoZyMzCstVroG2Z5mNYzofXNG(jWkcXhG9Jq)eWBgNu2LCW(9V59(975FtA0R10wPTsFZrR5jsrOSuLaFXbQRhMLPbZFCGArT1F9LBOIeMunsYfM4UbdIciBtKY8u5Cr4CEbC1T7DdsNamFBdVAPrXNmbu6p5Rv7m)91PqCzww0IcqDsq)r9oVVVbDi0sfT9sDbKNFAQ27T6YyygimHy18R3mUBNWOXHrDir(LcUjUiNUauebDkO9iUsJpbO5g29hDKcWJschf0V)QsXoi4vCinXWNbr1(NjtH)8G7qMbkbn)LiE5sXlU71au0bXtIHqnCjBLgYZCBGQpezHMAqeBa2ACCeycEg93(Mhv0YaxBgRzuCzCz9(RrXtCbDpYKQPuSGDg(cPawDF6J(kDXdFNo0vMlv)uJgnA(26O7XGFNZJgw8PUG0sJeBfp5cEQH53bDVREw8RHuxWFBB9xWxTdr36Y)lLAdpBbYhL0GCjcd6py4GGQhOqwzRzTRWehmAI)wTJectXd7P4380xustX9a9PrrVh33pPTUyZLQ0lu0ILxSZOgaZ4AECoC1oo)oQSIdpDWGaYy)HrrdpJC6ZpjA79JoKFd8KDm6Y3Bo2SoT1WZJ6F6GG)z7KC58Ek4xlbrYIrFW3)DT)XA2ztSX(yFhwADShEBCPXifdNbkuKT2gUpiMyyFMR(9mBL1P79BMBl1WZ3hH5BtYCtpIXtETa06MUteMqZHAZ(Cm8HUb4J7fqXIzaFcZ00pxstp23k)EmzAzUH7rsYPA9JRoZZxJ83ASw50Dwmx9XkRQgfHht0gQY4fNXfCnZZhFz8wrfCRgrkoUI07wGQHqJYXQpQ6bvhTn1QMX0JT3gvAaVaNQxARZ1(J8Ns5IEvV0vD1fvxw9k8D4)pYgUOwyJTYZ)gPCAdYCRcS5AJmzw9LRpVX4vhXtBpaMt(pP1MmfEzgrfQMAEx9x3E2qwaeh2LeemGqZly0MXi6Y4t8uCHTLaRDjpDZpptpORU938desXJ2))rwn9Z4AkkZszRTSI7wtEl3xbBlEbcN1WI6eT0TFgmR1S)(Y)9p


works correctly.

**Comment by Mawkes** [comment]
I will try again in a bit.

**Comment by Mawkes** [comment]
Well, that's odd.
It works as you said.

I spent perhaps 30 minutes trying to get them auras to appear in 3.1.2 but they didn't.
Then when I downgraded to 3.1.1 they appeared again (with no changes to the auras).
And now that I upgraded to 3.1.2 they are shown again.

Sorry for taking your time with this non-issue.
