### ISSUE TITLE
Hidden Models enabling after teleports

### ISSUE THREAD

**Issue by lorientalas** [WeakAuras/WeakAuras2#2748]
## Describe the bug
I have activating by buff condition model in weakaura turned off by default. And after change location(teleport for example) it's activating. Still turned off in WA.
It's starting happen couple releases ago.
Seems like the problem is buff trigger condition.

### To Reproduce

1. Login at Orgimmar
2. Use WA ability and waiting for cooldown off.(Sometimes it's required)
3. Click at Dazar'Alor Portal at Portal Room
4. Model at WA is Active without buff.

Opening WA window resets animation.

**Screenshots**
![image](https://user-images.githubusercontent.com/48098692/99992561-8d761500-2dc7-11eb-84e0-fca997d1a5c0.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.1.2

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
3.0.5-16-g45181f3 is good
3.0.5-28-gbcdea7d is bad

### Additional Info

Example WA:
!WA:2!1vvtVTrrF8AzG(0vpGsCEi02hEXaIiAvvOjbAEOCkBQnnOu701onfHQwp7UJ9onRNzyMzDSZT6t5iYqbjQef8boXjF4rCGt5tWil(eeXNG8jG)ZURJDlGp4DM)V(7)RtUYfAxiOqWrV7qIpJwJfl8XV(5e9Q2SPeRMFeI6hYe7WiuL3MLQuVKZyFglkGDaT2beoUXXtUwkOfo02yLg9vcsRwyH8hwsKD8NTv94yhuSaT6jYypChmvvlUzts3rUBUrT6U1QVHtDNe6E3gJIuHouuBS0QVKJJI2kqAzhtjkpEeQhwCASexQlYxvlLBJJn2orusG8YoRS6hU(upTJadEYP2oL2E7HbypWX1b8iUDPT3P8UBpiMMHtRL0x4OfobmUlYtYeE3HfGBmUfMIfe)AHSdQshkHpBeDaQNu)A6lQVK(YAlpPcPILdsqqfa4)RR)R6)T(L7BmLb3neX0eSyJIvm9RWV0MzzUI7iyTeyPS47NemxHVGrjSj6CpZEnglGSsTzm)yJut5RN3QFaKduegTWk85nCFgC3qpN1advLa5VFdDb9c6)7I63q)MJciYhgt9vKo4vr0E8c(XsfRD90KY2SweF(1AMibJ((z5QRyve(jWQybTygTVyLh8jwyAaFEuI1YSGjl(lN7uOlclOOO7b9gGHU7P7JX8nGqWx5yWD4ajoQzs3M(fG6KesPqaHdhcfshClqh5npArEbfUlKAcrq67(PTQ5gKqZ8378EC(CZiXMSiM4ZYLlx(tsPoXh2BSB9Q8fsiAkkTbm4VhjqfAVbC90egqFdoiH4JgNon85zE84e(peYuKM9a8kyqlaUoq0Us1kL0wca1gzgMiOFcmYd)sHAtgvXNRSGCyX7gJcG4evSE9Nj2M4j(BFwWbQjaC6YDvK2yxUa7tm5Y8Jt4EateSNaX7Vx2Huq2bKXlchMLxMzQMp)wvQuYX1UA96vVJZwF6TRp(m4LmJuD36BVvLs8l93GH0dogOemvTAKdXVAwYAs5H)w)tHqqpyoN4h2CShGzSWLLOrET1ai)Ls74mw(tlLzuYISgJYUJH1q85R9LXibUy54OOI7fsu4jSLa0YFuHvrCs4jEiHBBOZmY1pIWBmk9Su5glVlF(PCNK9ePxpm3XPhAsIWBfiwzT)36R9rF8WuICKkKFTKXs5hSEZUUbM(kbQRRhmNqOT8XrWmPQNRzJbE52Ro1VQE5Y8rVCtPk6(hZ1pP5cQZteO7mcO6M70POffXdrq2BKj7HsfFgJnRLvhoRBomNxiM0ku9a7igk4)NSFHJvEiLcI(t8Jqsj07eyw64VONecMi8JgzeRdoK4BAWkyU9Ss24KZwuTpf231WjH)IoTJJueRXZO)UKq7eJRpWI)FEUTGPkpC6zyhOTPGAKEOiz9GPJvFEr30UUF7L6p55PgcuYYl5nCG8Uqz51KqjYqlB4JcC2ebnZV3IirqbpiCmSwaAIRYtu1Y(qgR9o5V(YRPF3gdvm)oPlYUyo3bVdj40YcMuvCl)EfVhMqLEWJHnjTSg1ualORPmJ45pnDUOSHKbTE120PuPkohywX8GvJjbJUYddkTon66BxAfbHA8bo0jTSoarjTtAeUH(rLhpzFVR51vqmWHbsTLnLrXhJrsJtX0wQWZ33Clj78y72icTS(R1FJ2s)y93EE93bF6)8ugAmgjjWV6so(Hy)9VH(cx7C97Geet6z1nQClVe6YRcCEr9tgYOtEuZPdkkgNhONx)eBZlM6NMt4hIOTWYBUK(Pn6Zfma0QE61mx1d5fGo2Lxz5z3yLYr)vlP)(utP)r9tZR)PldmcbvEnJkRT8FzwDeHMULbG)I8lsArzcCwzSK5v4scbtiHwXZ2kxq6Sg49vl053V)Fo

**Comment by lorientalas** [comment]
The proble in [bad commit](https://github.com/WeakAuras/WeakAuras2/commit/818752c4ac3d3a5d599737ef07a5ddfac69db119)

**Comment by InfusOnWoW** [comment]
Are you sure about that?

**Comment by lorientalas** [comment]
Yes, I reverted 
`      self:Show()
    else
      self:Hide()` and it works fine now.

**Comment by InfusOnWoW** [comment]
If you didn't revert the whole commit that proves nothing at all.

**Comment by lorientalas** [comment]
First I revert whole commit and it work. After it I just try to do something and it also works.

`self:Hide()` is useless?

**Comment by ramblingmanjones** [comment]
I have also been experiencing a similar issue, only in my case the models are set to hidden initially and via conditions are set to show under specific circumstances. However after zoning to a new area the models which I use as bar and icon overlays will often show. The only way to rectify the issue is reload the UI. This started happening a few weeks ago after the end of 8.3. I can't remember the version though I'm afraid.
