### ISSUE TITLE
Aura softlocks when feeding NaN as static progress

### ISSUE THREAD

**Issue by CalibeR50** [WeakAuras/WeakAuras2#275]
What steps will reproduce the problem?
See end of ticket of an example WeakAura
1. Create a new progress bar aura
2. Set trigger to custom, in duration info return NaN (produced for example by dividing 0 by 0) for a single tick and some legit values for static progress
3. Return legit values in duration info
4. The Aura will lock to the invalid NaN value and won't recover

What is the expected output? What do you see instead?
Expected: First frame does not produce a progress bar, first frame does produce a progress bar but with invalid data or even get a lua error
What I see instead: The Aura softlocks to the invalid state even tho it gets correct values after the first frame

What version of WeakAuras are you using?
current

Please provide any additional information below.
Even tho NaN is the programmers fault, it can happen pretty easily. In my case I wanted to create a simple percent display for boss1 in a specific fight, so I returned UnitHealth("boss1") / UnitHealthMax("boss1") as the current progress without verifying the unit even exists. When entering the fight, the unit is not available in the first frame thus it returned 0/0 a single tick. Debugging was quite hard as the code would work infight and the function returned correct data the rest of the fight.

In case you do know which aura is problematic, please export the string and paste it below.

```
dWZkeaakreNse0SeH6wkvzxIQ(LsXWqLCmqSmrQMMiKVHkvwhQu6EkuoOiWcbPEOcvtuePlksyJOsXifP4KkewPsMji5MIOANuu)uPQmuruwQsv1tHMQGRIkvDwrkTxYFvWGrvhMslwu5XGAYuLllzZOIptvnALkNgXQvi61kKMnfUTI2nWVfA4uKLJYZPY0vDDP2UO8DrIgViPoVsP1lsY(rAbrbHtHEcDctpFIYdH7e6PGqcG8b3TSxEYmeHepHHYDZwZcTEEKtIaRXWzeF)I5uqMHOGWgCgX3VykOl8mIVFXuq43AQe6U9Tty7QHzSbV8e0cBa5cnzy3wmHvwbUWXJapYjrGty7QHgqUGwORZvzf4yZHdj1chgpbyyadjy)bHUoxLvGNmwXHKAHyYsbuqjSbvwbUqB)OUUUqpIBKna(KSsO1WqiR8jrqyRPsOTz2CwMWSI5irGmdr4zeF)IPGq4294uiNgaFseKKesxuEkpLNYZQ3maL)SUORc4rx0fDrx0fDrx0Lq4294mPnZEseiKtdGpjcsscPlkpLNYt5z1BgGYBBMDOaz5b9mxXsmLhsIP8N1fDvap6IUOl6IUOl6IUOl6syLvGlC8D2t5tE5Cw)s43AQec3UhNcHB3JZHV1uj0D7BNWguzf4cT9JcH3vWJkSn5zFPlKteCUXW67eUpUpa1imNcHgrRNccV1OapDfeoBJtuqxxOhHdhcCB8TkiC2gNOGUUqow4tIafeoBJtuqxxilAukiC2gNOGUUW2vdGkRykNqMfUuq4SnorbDDH3AuGRGWzBCIc66cnLz6wJcCfeoBJtuqxxxyZmeU73KJB3SjLw)yEsCtAgD3ckxQs7EBGi0cFswfyeF)IL8OxjZ7bHlHw4tIaNccjaYvqiC7ECk02m7qbYYd6zUIr5hJYZ1gUe6fhGB3JtbTUq3TSRGq4294uOTz2HcKLh0ZCfJYpgLhIqV4aC7ECkO1fYHaiUDkieUDpofABMDOaz5b9mxXO8Jr55Adxc9IdWT7XPGwxxiONbgX3VyozoDDHzYmKeLoeHP06hhrsfMMr3TGYLQ0UNUea
```
It is a progress bar with custom static duration info. It will activate when mounted, in the first frame the custom duration info script will return NaN as the current value (see onInit and onFinish), all further frames will return the legit value 1 (see onStart). You can verify by printing the value before returning in duration info.

**Comment by InfusOnWoW** [comment]
I can't reproduce that with your aura, nor with some similar test auras I've made, e.g. a trigger function running each frame:

function()
    if (not aura_env.first) then
        aura_env.first = true;
        return 0/0, 1, true;
    end    
    
    return 0.5, 1, true
end

Or this variant:
function()
    if (not TMP) then
        return 0/0, 1, true;
    end    
    
    return 0.5, 1, true
end

Which returns 0/0 until the global TMP is set.

**Comment by CalibeR50** [comment]
I recorded a small Video, I can still reproduce the issue using your provided function. See https://czymm.de/EY0UdzjC

Used WA:
```
dqtueaGAkv0UuOEnfkntkumBO6Mui)IcvUTszNsf7fSBv2p6NukLHjvQFtrdvcAWIHlrDkOKJjHwiLkSykLy5eweLQEQQwguQNRGjsPOMQsMSIMoPlsPqxLsP6YuDDiBKcvTzkz7uWJLQMfuyAuQ0HL0FviNxQKrlbgfu0jPus3IsbNMO7jrwPuEhLI8zLQHIWc(n4NWpHf8wMNA8419b4TnBFzm2AhBeECZ6ewWRvC)uSHf8BiCvclqbfETI7Ncl43q4QewGck8tPLLShHRDbl43q4QewGck8IAVdl43q4QewGck8LnuwR4(PWc(neUkHfOGcVWe3Hf8BiCvclqbfERAVknpyb)gcxLWcuqbfEHVlnVvxLD4Rir1wQc4NYb7eD9Q0GdFfhhE0Pc5(UlGf89Ob1CdEl01RsZdtSyJHHHr4ksCmQa5S53Kn2yJn2ydu4R9Q0GVeY9DxyK50Ho2qXUHxfY9Dxal41Uk7W3JguZn4rNBWpf(ksnHVhnOMBJ0Uk7WpOvfnaFpAqn3SzKOQsZdEl01RsZdtSyJHHHrAXG5zQmlJkelgTa)yJHHHHHHHrAXurI6i)mmE6wYZNmLkXOcKZykyQirDKFggpDl55tMsLyojoJwGFSXWWWWWWWWWWWurI6i)mmE6wYZNmLySQ4doBmmmmmmmmmmmmLfYtX0(LrfYCMkZ0TKNpXGr4ksCYBNPtTJ9yXgdddddddJFt2yyyyyyyyeUIeht3gx3yWuedgvGCBIngggg)MSXWWWiTyQirDKFggpDl55tMsLySQ4doJwGFSXWWWWWWWurI6i)mmE6wYZNmLyubYzJHHHHHHHPSqEkM2VmQqMPBjpFIbJWvK4K3odUVlvgdvCKBpwSXWWW43KnggggHRiXXSmQqmykIbJkqoB(nHVhnOMBWBHUEvAEyIfBmmmmcxrIJrfiNn)MSXgBSXgBSXg8ObFe6KkyhW3xG3BSWJkpRQdk8Yj8lFqz6u7WGn8hABjK77Uya6ueu4hGh7X2Dm2fH3a0PODXUiOaa
```

**Comment by InfusOnWoW** [comment]
That aura works for me too.

In Step 4, the aura switches to displaying 0.5 immediately. Are you sure you are on the latest version?

I'll record a video of what I'm seeing.

**Comment by InfusOnWoW** [comment]
The video: https://youtu.be/oXKYyfC5Mc8

**Comment by CalibeR50** [comment]
I'm running the latest Version, 2.4.21 (Checked curse client and .toc)

**Comment by Asteaguinity** [comment]
Interestingly enough I can reproduce the problem on WA 2.4.21, at least in a quick test on my normal WoW profile with english locale, other WAs and a bunch of addons. Didn't try it with a clean slate.

But as long as I close the options window with TMP unset or explicitly set to nil, the problem easily reproduces.

You don't happen to play on a Mac or a 32-bit client, do you Infus? I'd generally assume the cause for an issue is rooted in those differences, rather than a difference in client locale, as seen from your video.

**Comment by InfusOnWoW** [comment]
Nope 64bit windows, so that can't be it.

**Comment by CalibeR50** [comment]
Just for reference: I'm running Windows 10 with 64bit WoW Client, too

**Comment by InfusOnWoW** [comment]
Oh I was wrong. The computer on which I tested it was in 32bit mode. Seems I forgot to switch it back to 64bit after investigating a different bug. I can reproduce it now. I'll take a closer look at where it goes wrong then.

**Comment by InfusOnWoW** [comment]
So yeah NaN handling in 64bit is just wrong.
Running:
`/dump 0/0 == 0/0`
returns false on 32bit and true on 64bit. 

And:
`/dump 0/0 == 0.5`
returns false on 32bit and true on 64 bit.

I've forwarded that information to Blizzard and I think there's nothing we can do about that then.
