### ISSUE TITLE
Align Horizontal nuked my 93 element group - can we get a ctrl-z feature

### ISSUE THREAD

**Issue by captain-git-planet** [WeakAuras/WeakAuras2#2754]
I did not know what the align features did for groups, I was just trying to scale my group. I thought they would change where the group itself was centered (not the actual positions of the auras within the group) and now I have to re-position my entire UI. 

I did this with one keypress, surely an undo button / keybind for this addon would be something many would want.

**Comment by InfusOnWoW** [comment]
Yes, also pratically impossible to implement at this point. There are some long term plans to work towards that, but we are talking about years of effort.
