### ISSUE TITLE
Allow custom actions to register functions accessible in macros

### ISSUE THREAD

**Issue by liujisi** [WeakAuras/WeakAuras2#2761]
I used to leverage WA for in-game lua function authoring and then use them in macros to workaround the macro length limit and for easy editing and sharing (without having to define my own util addon). The way I did it was to define the function in an on-init action, and then add/register the custom function to the WeakAura table with a unique prefix to avoid collision.

When I'm back to the game for the new expansion, it seemed to me the WeakAura table now has a read-only mixin. Is there any recommended way to allow auras to export functions/variables outside of its sandbox? Or anyway that the external environment can access the aura exported functions would also work.

I feel like WA is a powerful framework and it would be really nice to support such use cases. Thanks!

**Comment by InfusOnWoW** [comment]
That's not a intended use case for WeakAuras.
