### ISSUE TITLE
 Hello, today I entered the game and I had the Weak Auras configuration empty, can someone help me please?, I have lost everything, the rest of the addons have also appeared unconfigured but I only care about the auras.

### ISSUE THREAD

**Issue by LunethVendetta** [WeakAuras/WeakAuras2#2762]
## Describe the bug

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by SoLoR1** [comment]
If all addons lost configuration its probably not weakauras fault, this sometimes happen when something goes wrong during wow closing... thats why i backup WTF every other week.

HOWEVER there is currently bug in WA alpha branch and auras do not work, but again this is only for alpha branch and if you lost configuration on all addons it is probably corrupt WTF folder.

**Comment by InfusOnWoW** [comment]
@SoLoR1 there are no known issues in the alpha. 

@LunethVendetta We can't help you if the game deletes your settings. If you are using the WeakAuras companion, that takes regular backups.
