### ISSUE TITLE
Weakauras do not show up on login/reloadui in 3.1.2-5-gdd58908

### ISSUE THREAD

**Issue by SoLoR1** [WeakAuras/WeakAuras2#2763]
## Describe the bug
Weakauras do not show up on login/reloadui

**Do you have an error log of what happened?**
There is no error

### To Reproduce

**Screenshots**
![image](https://user-images.githubusercontent.com/3218757/100541356-bec96780-3243-11eb-8dad-bbf4c6634d9f.png)

if you see above chat frame, that empty WA is thing I get from WA on login/realodui and about ~half of WAs are not showing up. After i open /wa menu all WAs show up as expected and bug seems to go away until I reloadui.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.1.2-5-gdd58908

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I think it was 3.1.2-2 from alpha branch, anyway latest offical version 3.1.2 works as well.

**Comment by SoLoR1** [comment]
I litterally put every single WA group to load "NEVER" and still get that "empty" WA above chat.

![image](https://user-images.githubusercontent.com/3218757/100541606-5a0f0c80-3245-11eb-84bb-b3ff185baf21.png)

**Comment by InfusOnWoW** [comment]
You are supposed to give us enough information to be able to reproduce your issue.

**Comment by SoLoR1** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5612157/WeakAuras.zip)

OK WeakAuras.lua attached from WTF, I also disabled ALL addons except WeakAuras and problem still exists.

Only step to reproduce issue is to login/reload UI with those specific WA settings and latest 3.1.2-5 alpha branch. It was fine with same weakauras on whatever version WA was 2 days ago in alpha branch (i think it was 3.1.2-2).

**Comment by SoLoR1** [comment]
I can fix a bug for my self if i revert commit #dd589085aee5ac731bc7179811e8bba3e687d76d
