### ISSUE TITLE
Condemn Cooldown Bug

### ISSUE THREAD

**Issue by Ronln** [WeakAuras/WeakAuras2#2766]
## Describe the bug
**Condemn** Cooldown Bug

**Do you have an error log of what happened?**
After some time WA stop tracking Cooldown for Condemn

```plaintext
No errors happen
```

### To Reproduce

0. Chose Venthyr Covenant for your Fury Warrior to get Condemn
1. Go to kill mobs
2. Click on your combat rotation including Condemn
3. After some killed mobs, you'll notice that WA doesn't track cooldown Condemn

**Screenshots**

https://i.imgur.com/SsQpF7B.png
https://i.imgur.com/YTe1LhQ.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, it happens anyway.

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

WeakAuras-3.1.2-5-gdd58908
WeakAuras-3.1.2

### Additional Info

```
!WA:2!9z1tZTXTv8Os5PDOBBSOS1i744s7gZP2tnLLuKtAUXvHSXzueLxsfLEPCXUl4UiAjamawkrDR8qQpZd9sDJB5L62CJN6zDONXWPJNPx1hb)jOpGDj9Fg5QzejW7p)aEV3V3dCHgL6vkSu4tQmMeWOTyPIa81FpXGMD7kXQR)JMGObXmXEmcv5VD9DBx3DAaJLeYoI26ich7TrQiH)bXkfx(zRT2rOiwvcBTb929aNpw8jF1AB5yq2BOsqIIWc5VVIiF5tw(SujUdYxYe(Ffle7nnctXcsqRy2rnPtK2VCXOWboPuIYNNGgGfJdX(PD72Eahl(I67SxJ93XrbB8LkKkvo0aQXCprkf3htvoOufJVKr(BCaENjt9Tw0cWJC8KoBxRv7oTAxZTTRvo)QBNhSL3tWIeyPS8VQfhNKCh(Yg8WhJcuDKgj7I6brGaJsAnB7QxO4(tnM9kdgAx(WqzX5h(EcmC4UT2R(o74sbJKfhgMkqkcJwA9rg)vcuWHEJKVoWJsP5jYv0)u9pRIU4l0L0lRxvFv9VS066RnTwGbIY7lr(jy9190FOXp9n80x2txwFt9px)(6l6PVIEf9TTQQuCsir(TPuWZ(4nq0b8Lq21TZoktzQWlbYawqrjFnupHt4rV8qmMxdUDbkxZ1gUP4KUwsJErOCjH6cep4yr)mpU4yi4DXrWs5N1FIpteIfDKKtWfMMVHzzGfgRWhR6eWsyIINMRYU7lxyHfkCwUK(ejbIrVziHdJW8LA94uKaxUrAss5dIjkSU0i4CZS5jL5LSylJrqb(BYy8lW)qRq7hDzIEivhoqr9f4(eteW)OZrVpjQdnTNpCYzY4lvBUl7AvipxGnSLEDm1CxdvvW)GZXOOGWobiPkMF1ZrB2cxfPhoC0C93628ZYIUzfcNA73UjFzRqt)a4ej4asOk2PgS9LzOsoghAf(h438)BIOtp0XlnnB6WVlp3DQ14VnvQiDhafEbdAiXTbHo72C368vpheT1sVZ9WmHuhUahqmuMcNBMpe02dL8AMPljGASXk(1Ehjt4Fp9MFzb4p(nExj8yeLItIZIPz8R3GYmlShL7nmU4sneKtk)Ouuiq3rLB3EQv3raJ7abIp8G8ftN7IDkwZ9BVZdHe0LYQoVAKRErE53XfmMeI7CcwWIZDl7sT98EJxDgTG(QBMxRMZZ)fVRmE4aGpsc8EX0Oe2rne4hNIPbd2BX7xDJTCmYINy(CgsdnBmHXu)uLIrBc8yyo9yJ4DW0iv8vS2ppDz2KDnnvGtH5B)2zsITkBfGsW5fsZE7fPDmj4qkmaUG1MDiW6LShIJTFo2pgtIIvyNegk8FBh7YXkFKsLGJTtrTTyXtml7Jb4a5UbjiPSIVKqJsWIdQ56(WMUU9stuKIwNSg4D28P4hsHxd8gMVpWB6Rb3(KyhJWk60lOpQi)YV1tez(o(vRxDX)0)YXm2BfW8Xc7artQu)tCdMNHMqOzviq5k8vjruMa3KB2kRBEaPUqWesVtN9WCDy6xSazN(lFGl8SOqv0VlHsKXfDGVufNcJaa2qokf9HNO7sIk6lX9GCK76v3O668lpdqtl8NtSpJaDoR4nwXcYNKV6cDgDls4PBZOH4E0onsfdEzgvRHaMRzIg)wB7wV(Ut6Ae0szAnk4EKzkd2fLWJrf2iLeo5RF0DECnE3tc(cIGqn4drXXzSM)RZjmwV9kC)QBogURHe79(UvCdIXbh(aDXF97nSpsqmxXB1013kwExqrb9thZOZEg3TpkjfxaKFb9tDm)ad9ZwqyA2JWYRvr)mVHCbdAjvd0vRO)ZwK1pDJA7(56)soC6Vh8jdb9Fv)Sc6)M1r9yZJAv3SQHtoCwQZBeIsYQDpq)DnofJKMuGTV4hRl5qzu80zV23X8ZyGW2eHYHgtTKHN70drOn0)DWb9Z1)d9)u)dW3)X3wsjj)sBwfQD3BR7ffgU1N(BU)NwQ))5B(Fp
```

**Comment by InfusOnWoW** [comment]
That's a bug in WoW and/or the setup of your auras.

The right spell id to use is: 317485, not the other one you use.

This should work correctly:

!WA:2!9z1tVTXXvCRslueweyl6yf6)LqR4k062kzjx7M4BCLjtSlTO8sQQ0lH7S7oC3jA5mJNzwsrHEP8qHbAAlGo0pamoXj5ipLZ6qopGOii5Q(iOpb5nZsslhivcWDFZ7)Z79MFZox1cDkewi85lpKeWOnyPIa81pNyV6TBlXQFu0pJ46)IriAqmtSfJqv(BuzZMvChhWyjHSE0g9iCS3HtxwjmchlqbkcJkVVRuHeQ8(TjuImoVd8sLFGsqIIWc5NSSyc5ZVSRcmAxhuQIDuQe3c5lzc)NWcXEJJWuSGe0iM1RoDOeEvoPhQVCGrXuWLEddX(PTB3Sphl(Ok12Q621Cmc85jO(yHJce4d5IkvoimvGmzxH1osM6J7IPQgGTK9g1AJYnA2QrZYUnfPuRe9fMP0wcmOKBJTQuRMRLd)kBmzxxAlblsGLYs)MgCCsYVLFjtUH3dkeTKgoBI6a7ebgL0y6YIN)h(dJnQ9kfgyjFuOmVlfwlZZFlJcKiktGTg(NPq4I5lyy)A1fVdmSSvrVdKNmghKsNuMxuVGUWY63871f1xrFd9f0x0txACzB3Q02sKFcwFjp97zmtFlp97OFx9I63wVKN(QfwtFn91132k73LFuir(PPuW0U41r0(8fqw6MzHY05YDmmVGfuuYFb62qiE6X7IX8Yq2fOCnnbitXjTTZv65HMOe6qq3bMG6MzXVAiu(DXrMPPh0vx8ayPpteIfJYE1ss2hNBOcVNQvalHjYF4eb2vpEU5Ml3rt40LijWo0BQPyywLVqJNLIe4svttskTtmrHhprmZo9N75L4fSUxgJGE9hNDOyo(nTmTpAZeDqQwCyQ1xG7sGDqRoO9wGFRtrhFsulAAhFicz84luEMzBAfi534)RZJ5x7uKhfe2kajvX8lEI8DJzLb(vofJYiCvKo4WJYmBAhXP82nRZVKLP5CjOhjyhsOk2PmS84mhr2dhAz(3pyM7x6xZhNbz8xNuTo0k7ttLks7(qRwWGdJ4MatNnRVzfEXtj1SnqVtToBs3wCboGygsYDQ15qqAhuYjutxuaJpgT4x9mQFWFp97)4CWp(7Cw14yeLItIZ2tthQETHKPB7dMynGvCXQcY(LEAkkegWrLA2CSvwpywBhbIpyNjeJNzIfnR(2nR9iOaL1spboSEEEPZibJjH4w7JfS4tDoYac1PLbFX1aYjEveBaNLU5Ko3S5839SQ)H9bFqc8((XrjSEvf4NLIPb93683zL1VNJHx8iZZPEAGzHztn2pvPy06qSb45Hg21W0iv8LT6pR4zwKn(A6hhc4BF4uoXwHncqj4jTvZABI0mMeSlfWIZz1PgbOxWgeh756y)ymjkwHDsyOWVZIaZXkFKsLGJTOO2Ys8idzxm4oGVBqcskx2xsOrjyXoLDDFuDx3oPjksERrwf8oAgG(UgKAVbtwh4n(eUBBsSJH5Y69Nx)3MGYFIBlYSD4ROlE()736yG6weuFOWciAkLoMBU1)dVreAwZb4ViVy2fg152BHRyURQIqWesp9f8CdMvsparjz2CF9Bu9qmsIBOe2wXVux0HYO4XtVUSL5ouHedXluoWOQj(6pZPdIqRQ)NGb6pt)V0)B9)bEN)NZXhSRnjkVZ(mwNTYDNvURVe3bkZURTY6RS2qflycKFX5ADWsKWJ2aceUdTv1ur)sR7Is4XOCJAlG5wijHZq5C7zWDWhNnWw1iXKt(n2WTsLnxpLeoI8bO(p79R90h7ah)OMiGJxpvKWVwSsXLpy1v7HIyRqyR2VZM748hf)PNS69gdODGdNu(Yp0SLjw6BVSBqmoy37RFZF)5g0fjiMRmxQURVLT82GGC6xmKrN(LbUDrjP4Ca)51VWX8Tl6xoNWaHeHLxDz9l9gWfmOYQ6RV7Y6p36z9lwV8Mpu)ftCN(lbBY8G(R0VmN(RTgQ)gZLJRC3vmZ2dM(byE83AkPbE9He7T6HEfKR)qC3cD)FF8p9

**Comment by JoepHeijnen** [comment]
I just tried your import string. It doesn't work for me. I have the same reproduction path as the created of this issue.

**Comment by InfusOnWoW** [comment]
That import works correctly for me, so I need a better description of what exactly triggers your issue.

Also note, that you should try to minimize the aura to a minimal reproducable example that doesn't work. This aura contains multiple triggers, and it is important to know which trigger is not working.

**Comment by JoepHeijnen** [comment]
Apparently it doesn't work with the talent Massacre. So if you choose Massacre the import should not work.

**Comment by InfusOnWoW** [comment]
That's not a bug in WeakAuras then. The aura has "Exact Spell Id" checked as did you initial aura.

That makes it only work for that exact spell id. With Massacre selected the spell id appears to be 330325

**Comment by JoepHeijnen** [comment]
Ok. Good to know. Thanks for answering!

**Comment by InfusOnWoW** [comment]
There's a api to map names to spell ids, but due to a wow bug it doesn't work correctly with Condemn. Appanrently the other id is: 317485

**Comment by evgen66rus** [comment]
It works with the spell ID 317485. Thanks for navigating :)
