### ISSUE TITLE
Event: UNIT_POWER subfield support

### ISSUE THREAD

**Issue by HildoYe** [WeakAuras/WeakAuras2#2767]
When I want to create a custom event with UNIT_POWER_FREQUENT, I figure that it will bring some performance issue.

The current WA I'm making is for shadow priest, which has 2 types of power: insanity and mana. I want to do updates whenever my insanity is changed, but I also wish the mana change event is ignored. My current solution is manually check second parameter (power type) every time the event is trigger, but I hope that you can add some parsing for this specific event (maybe related to RegisterUnitEvent?)

**Comment by asaka-wa** [comment]
What you're doing is correct.

**Comment by InfusOnWoW** [comment]
That's how the in game api works. There's little to be gained to further filter that on the WeakAuras side instead of your code.
