### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#2769]
## Describe the bug
every time i log in i get error with weakaura name in it-not sure if its really cause by Wa2

**Do you have an error log of what happened?**
Message: ..\FrameXML\ItemButtonTemplate.lua line 201:
   attempt to index field 'IconOverlay2' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149:
      ...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
   [string "=[C]"]: ?
   [string "@..\FrameXML\ItemButtonTemplate.lua"]:201: SetItemButtonOverlay()
   [string "@..\FrameXML\ItemButtonTemplate.lua"]:160:
      ..\FrameXML\ItemButtonTemplate.lua:118
   [string "=[C]"]: ?
   [string "=[C]"]: SetItemButtonQuality()
   [string "@Atlas\Integration\EJLoot.lua"]:368: Atlas_EncounterJournal_SetLootButton()
   [string "@Atlas\Integration\EJLoot.lua"]:423: Atlas_EncounterJournal_LootUpdate()
   [string "@Atlas\Integration\EJLoot.lua"]:477: Atlas_EncounterJournal_Refresh()
   [string "@Atlas\Integration\EJLoot.lua"]:332: Atlas_EncounterJournal_UpdateDifficulty()
   [string "@Atlas\Integration\EJLoot.lua"]:303:
      Atlas\Integration\EJLoot.lua:285
   [string "=[C]"]: EJ_SelectInstance()
   [string "@WeakAuras\Prototypes.lua"]:235: InitializeEncounterAndZoneLists()
   [string "@WeakAuras\WeakAuras.lua"]:1152: callback()
   [string "@WeakAuras\WeakAuras.lua"]:1168:
      WeakAuras\WeakAuras.lua:1081

### To Reproduce
i just loged in game

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.1.2-5-gdd58908

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by Stanzilla** [comment]
Not WA, no.
