### ISSUE TITLE
Merge Zone ID & Zone Group ID

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2770]
**Is your feature request related to a problem? Please describe.**
Some dungeons only have a zone Id and not zone group Id. that is usually the case when the entire zone only has one ID.
Therefore it is difficult to make shadowland dungeon weakauras that work for all dungeons since ticking both zone & zone group ID doesn't use an "or" logic

**Describe the solution you'd like**
merge zone ID & zone group ID into one

**Describe alternatives you've considered**

**Additional context**

**Comment by mrbuds** [comment]
As stated in https://github.com/WeakAuras/WeakAuras2/issues/2772 adding a instance Id field could fix this

**Comment by InfusOnWoW** [comment]
This is now implemented.
