### ISSUE TITLE
Lost all my Weak Auras out of nowhere

### ISSUE THREAD

**Issue by Triaan88** [WeakAuras/WeakAuras2#2774]
## Describe the bug

I logged off the game, updated the Weak Aura Addon, through the new Curseforge App and when i got back on all my weak auras were gone... note: Vuhdo addon profiles were also all gone and when the WoW game, came with a Lua error at startup (can't recall what)
**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
If you are using the companion, then that will have made a backup. As to wow's ability to randomly throw away your data, we can't help you with that.
