### ISSUE TITLE
Special Code for Item (Bonus) Id

### ISSUE THREAD

**Issue by Smxdge** [WeakAuras/WeakAuras2#2775]
**Is your feature request related to a problem? Please describe.** - **Describe the solution you'd like**
I would like if there was an option to dynamically change a text aura based on what legendary is currently equipped. A special code like %x when there is a trigger looking for a "Item Bonus Id Equipped" similar to how "Use tooltip Information" works. Also future-proofing this idea, allow a %x1 and %x2 when we are allowed to wear two legendaries.

**Describe alternatives you've considered**
I've considered creating a Load option that pays attention to "Item Bonus Id Equipped" but that would require several auras for a single class.

**Additional context**
Only reason I ask for this is to help streamers show what legendary they are currently wearing cause right now some streamers just show what the gear icon is, Which isn't really helpful to a common viewer.

**Comment by mrbuds** [comment]
You can use the "Item Bonus Id Equipped" trigger.
