### ISSUE TITLE
Texture for Fleshcraft

### ISSUE THREAD

**Issue by daddyearl** [WeakAuras/WeakAuras2#2776]
On retail with shadowlands...

Wow 9.0.2
WeakAuras 3.1.2
Frost Mage level 60

## Describe the bug
The spell "Fleshcraft" does not seem to trigger when set up for "Aura Missing"

**Do you have an error log of what happened?**
There doesn't seem to be an error, but might not be hooked up (a new spell)

Here is the export...
!WA:2!DjvVUTTou4AKcua1GIgJ0G07uWDOaDjOXoXzmWYrg2T(hvk1KoyaxkXJSiUYKQKuoo3rJm0Xc)i45o5H(aKNabJ(au0Po7NGskBKHYbEo8NVZ578DoLAwECzszYxoAHIhobeskNDyPHZxRGPQmbCTaN2LtG09B0PExx)(2DQ34D1V8Y2(TVYzfotfZf9tvAysl0nuIk(UDft7hfjbvjuipHlEBRl(9HfRwx8ZVwS2X9XV54Zplymvi4IyXTBbSqaJ0HY)2uqSLblJe4XGNsGv4DMhKamIHqv0CyjMfQtVlNYubnC657GwszrCXySHqwlc5mcDd3e4WcNAiPcluwbrugvgBzRnkRzkbD0iD5)Sxj26(DBLMfiCMax5EZUmfssOe5)euTYP1QEYkDwcJbPxm)M(SvYctxQuszJqWeqZPwaorf)lzwqXzxberNI8CD60zwr4AtKwp8SxwK(5LdBu3ZFONFDKVDMMCbPj4BbbIPLbP16mj4mvxmEBW)PfeiqdSqYA50XT5h6mpJTTiSs3Zu3ta)nNnk33Eu(ttpVntbIiCimOoHO1Lbxd4)RUPmh4YVbefUDbcfpyZTM9tQTMAWXWjxTzw59P7rOYqbOGHcUQq3lnhZOBAb1Y3V59awA6FaBKk(j5V0MXzWkIoCMFm0OYcjyAvYzMVAQK8Q2JXuwZ8kAa5vZpn)S8AA7l(7B(xkzDpaih1mbKXHcCKAUesIkMjYFocNKgJ3rRrsSYKriE2d0mqNZi6iR1BgJAAMZmjpWRbYXP3cDFbvmokTcIb6Oy1D7guGg(KDchtQzRBIHhGgNLOOwOWeSuEqUJLTK()GXPsgLSCA0RD)87tpRhsuwIQE8jhxP8KF8X)m

**Comment by Causese** [comment]
Whether it is "hooked up" or not is decided by blizzard. You used the wrong spellID (324867 is the correct one) 

I suggest an addon that helps you figuring out the spellID by mouseovering the buff if you're having trouble to find the correct ID.
Like: https://www.curseforge.com/wow/addons/idtip
