### ISSUE TITLE
Icon border offset.

### ISSUE THREAD

**Issue by Theguyxd** [WeakAuras/WeakAuras2#2777]
## Describe the bug
My icon borders keep resetting upon login. Only fixed once I reload ui or open weakauras "/wa". Then everything is as it should be again. It's only broken upon login. 

The border offset seems to revert back to a value of "0" until I reload ui or opening the weakaura menu/config after logging in. 

**Do you have an error log of what happened?**
 No errors. Just seems like something is wrong with the first load of the weakaura. 

```plaintext
PASTE ERROR HERE
```

### To Reproduce

Create an icon with a border. Make sure the border offset is +1 (do not leave it at 0). 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

 I do not use any skinners or anything like that. Elvui is not installed. 

**Which version of WeakAuras are you using?**

 The latest version as of this post. (3.1.2)

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

 Don't know. I did not have the weakauras configured this way last update.

**Comment by Theguyxd** [comment]
I might have mislabeled this as bug. The behaviour of this seems affected by the group spacing. However it is still inconsistent with the setting "appearing" to have changed upon login.

**Comment by mrbuds** [comment]
Can you give an export of an aura with the issue and screenshots of it ?

**Comment by Theguyxd** [comment]
> Can you give an export of an aura with the issue and screenshots of it ?

I reworked my auras and found a way around it. So screenshots might be an issue. However I can do a better job explaining what is happening. 

The aura in question is a dynamic group with a number of icons for abilities and such. When the groups "space" between auras is a negative value, like -1. The icons borders offset seem to load incorrectly upon logging in. It is like the border offset is at 0 even though another value was set. But as soon as you open the weakauras options (/wa) it fixes itself and the icons border offset corrects itself and applies the correct set value. It also seems to fix itself by reloading the ui. However, as soon as you log out and back in the issue is back. Again though, this only seems to happen if the groups spacing is set below 0. I can not figure out why group space value would impact the border offset. Or if it does at all. It might just appear that way due to how the icons line up within the group upon first login. The issue also only seems to present itself if the group is set to centerd horizontal. 

If it happens again I'll upload screenshots and the aura. Cheers.

**Comment by InfusOnWoW** [comment]
You are supposed to make our work easy by providing a reproducable example. I will try with your description, but it would be much easier if you just created a group with the right settings and produce a before and after screenshot.

That also ensures that regardless of which exact settings affect the behaviour, we'll probably will reproduce it. That bit seems to be important, since you are apparently unsure which exact settings are necessary.

**Comment by InfusOnWoW** [comment]
Can't reproduce.

Please make it easy to reproduce the issue by including a simple aura that shows the problem and a clear illustration of any changed visuals.
