### ISSUE TITLE
trigger firing although load is set to never

### ISSUE THREAD

**Issue by Melethrion** [WeakAuras/WeakAuras2#2779]
Hello,

I haven't entered the game for 2 yrs now, but upon editing my auras I recently noticed, that their triggers are being activated, although:

- wa is opened, during which formerly the auras never were supposed nor enabled to do "their thing",
- loading conditions are set to "never", which should normally mean that the aura/trigger wouldn't be active/activated at all

this occurs when selecting an aura within the list of auras within the main window and upon opening weakauras ingame in general.

**Comment by mrbuds** [comment]
We can't help if you delete the issue template and don't answer any question

**Comment by InfusOnWoW** [comment]
I think I understand what the issue is even without a actual aura.

This behaviour is intended, the aura's triggers are run while the options are open so that the triggers can control what is displayed.

**Comment by Melethrion** [comment]
i don't understand

**Comment by Melethrion** [comment]
i didnÄt delete anything? what

**Comment by Melethrion** [comment]
what didn't i answer?

**Comment by InfusOnWoW** [comment]
Please do not spam the issue. If you click on New Issue, there are a bunch of questions. Do note though, that this issue was already answered.

**Comment by Melethrion** [comment]
can u link? or give the answer? what does it cost, definitely not more time than typing in what has been typed in yet ... -.-

**Comment by InfusOnWoW** [comment]
It seems you haven't actually read or understood the answer that I gave you early in this ticket.

**Comment by Melethrion** [comment]
okay. so i did now use the "template" i believe, opening a new issue, like, as i hope, it is supposed to be handled. with screenshot and everything. i, personally, believe, this wasn't really necessary, but if u insist, i am willing to do anything superfluent u want to feel respected enough. ? dunno. srsly. but here we go. https://github.com/WeakAuras/WeakAuras2/issues/2782
