### ISSUE TITLE
Suggested Improvement for UI

### ISSUE THREAD

**Issue by roylofquist** [WeakAuras/WeakAuras2#278]
Dear Sirs,

The following is based upon the Microsoft Visual Studio development environment for forms design. In that environment properties of a particular visual element can be copied from a designated element. In fact, multiple elements can copy properties from one master element. The relevant properties vis a vis WA could be height, width, x-offset, y-offset, font, font size, etc. Although not adding function to WA this would relieve much of the tedium involved in the visual formatting.

Regards,

Roy Lofquist
Ocoee, Florida

**Comment by emptyrivers** [comment]
You can multiselect auras to change any property en masse.
