### ISSUE TITLE
"Talent NOT selected" Loading

### ISSUE THREAD

**Issue by Tuhljin** [WeakAuras/WeakAuras2#2780]
**Is your feature request related to a problem? Please describe.**
I have a couple auras which load when I have a certain talent selected and another aura that loads when I don't have that aura. (The talent is Glacial Spike for frost mage. My icicle tracker needs to behave differently when I have Glacial Spike so I use separate auras depending on whether it's selected.) Since there is no "talent NOT selected" option, I set it to load when either of the other two are selected. This works fine normally, but in Torghast, I've had the situation where I have both Glacial Spike and one of the other two talents. This makes it so BOTH sets of auras are loaded.

**Describe the solution you'd like**
A way to specify that an aura is to load if a talent is NOT selected would solve this issue. (Perhaps other missing "NOT" logic could also be implemented, e.g. "Spell NOT known.")

**Comment by mrbuds** [comment]
You can multiselect the 2 other talents from the row

**Comment by Tuhljin** [comment]
That doesn't work to reliably detect you don't have a talent in Targhast, as explained above.

**Comment by leobolin** [comment]
Selecting the other 2 talents is also problematic for low level situations. I know that's a bit niche but some of us are not max level, and also party sync is a thing.
