### ISSUE TITLE
trigger firing although load is set to never (with answered template questions)

### ISSUE THREAD

**Issue by Melethrion** [WeakAuras/WeakAuras2#2782]
## Describe the bug

I haven't entered the game for 2 yrs now, but upon editing my auras I recently noticed, that their triggers are being activated, although:

- wa is opened, during which formerly the auras never were supposed nor enabled to do "their thing",
- loading conditions are set to "never", which should normally mean that the aura/trigger wouldn't be active/activated at all.

This occurs when selecting an aura within the list of auras within the main window and upon opening weakauras ingame in general.

**Do you have an error log of what happened?**

no error

```plaintext
PASTE ERROR HERE
```

no error

### To Reproduce

triggers are being activated, although:

- wa is opened, during which formerly the auras never were supposed nor enabled to do "their thing",
- **loading conditions are set to "never", which should normally mean that the aura/trigger wouldn't be active/activated at all.**

This occurs when selecting an aura within the list of auras within the main window and upon opening weakauras ingame in general.

1. Go to '...' type in /wa or somewhat to open the wa main window and/or select a aura out of the auras list
2. Click on '....' see above
3. Scroll down to '....' see above
4. See error no error

**Screenshots**

![Unbenannt](https://user-images.githubusercontent.com/21197654/101091495-85cd2200-35b8-11eb-922a-20eeae25abdd.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes

**Which version of WeakAuras are you using?**

3.1.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

all ones same

### Additional Info

any aura, the issue is general in nature

**Comment by InfusOnWoW** [comment]
This behaviour is intended, the aura's triggers are run while the options are open so that the triggers can control what is displayed.

**Comment by Melethrion** [comment]
okay. last question, just to be sure: this is even so, when "never" is selected in the laoding conditions? intended? really? and if so:

don't i have any option to avoid that? why can't i set an aura to not be activated at all without actually deleting it anymore?

if so, i do suggest to (re-)implement any kind of option to do so. - why wouldn't one like to have it?

thx 4 ur time. cheers

**Comment by InfusOnWoW** [comment]
Yes it's intended. You get a special "OPTIONS" event, and it's up to the trigger to handle it in a way that works for the options.

**Comment by Melethrion** [comment]
okay. so, i do notice that the mistake seems to be on my side here. and i assume, there is probably still a way to make sure that a aura isn't being triggered/activated at all. and it seems to be connected with some kind of option(s)-(event?) ... which i would have to therefore avoid, if i want to _completely_ deactivate the function of a aura? is there any way to learn how to do this? i apologize for my nescience. i have been inactive quite a long time... :/

**Comment by InfusOnWoW** [comment]
There's no way to disable this options event.

**Comment by Melethrion** [comment]
Ok. Thank you for your patience and for all the answering.

I do suggest to (re-)implement a way to disable auras completely withour deleting them. It would be really pleasant.

Have a nice eve. Cheers.
