### ISSUE TITLE
WatchItemCooldown events don't get checked when registered in TSU Custom Variables

### ISSUE THREAD

**Issue by Boneshockx** [WeakAuras/WeakAuras2#2784]
## Describe the bug
Events from WeakAuras.WatchItemCooldown() and WatchSpellCooldown() in a TSU Custom Variable aren't checked when they fire. 
"ITEM_COOLDOWN_CHANGED" 
"ITEM_COOLDOWN_READY" 
"SPELL_COOLDOWN_CHANGED" 
"SPELL_COOLDOWN_READY"

### To Reproduce

1. Use WeakAuras.WatchItemCooldown(id)
2. Have a TSU with custom variable like this:
```
onCooldown = {
        display = "On Cooldown",
        type = "bool",
        test = function(state, needle)
            return (state.expirationTime > GetTime()) == (needle == 1)
        end,
        events = {
            "ITEM_COOLDOWN_READY", "ITEM_COOLDOWN_CHANGED"
        }
    }
```
3. Have a condition that checks On Cooldown == true (and e.g. desatures)
4. Use item
5. aura doesn't desaturate, or unsatures when it get's off cooldown.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
3.1.2
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
No clue

### Additional Info
Registering the events to the TSU itself does make the condition check function like it should. But when registering the events separately in the CustomVariables it will not.
I haven't tested if it's the same for WatchSpellCooldown(), I only assume it behaves the same.

**Comment by InfusOnWoW** [comment]
Yes that's intended for now. 

Two reasons:
1) These functions are internal and thus their behaviour is whatever their behaviour is. And there's no gurantee that they'll behave like that tomorrow. (Though likely no change until a expansion.) 

So, making them work with custom condition checks is future backward compability break, which I'd rather avoid.

2) The system that fires those events is inside the generic trigger system. That's different from the conditions, which are trigger-independant. So making it work requires some coordination between systems that are supposed to be independant. 

Neither of these reasons are very strong, but there's also a trivial work-around by making your trigger listen to these events.

So at the moment, I'd rather not go down this road.
