### ISSUE TITLE
Lag in auras attached to cursor

### ISSUE THREAD

**Issue by Perfek00** [WeakAuras/WeakAuras2#2790]
## Describe the bug
Auras attached to the cursor have a slight lag. The aura feels like is following the cursor instead of being attached. 

### To Reproduce
Here is the code of a simple texture attached to the cursor:

!WA:2!DjvZUnnqqyIcsizQQuJQQkNaXbowbj0axTtDud40yw7(ZHifw7DC8k2SR1URtB5yufIZ5riN5uEe4jWQINaEe6ta76e1dCz3zhnFZ899TtJ(TM1I0I8ZxTslsNdsfvWpSXKLpOHB0Ls4sjUyOGaf73lWDyy8iVa3EF29Ktgep4cFuQGjKFQzZMHp9Th9HJxraf2adRH87XL6CHCuH20sLJ8Mrzzkq3izgvkfYC5TBtSgZtnfgkOCDsp)ZI9rEmbM01tvaPhGMvY0uhukdRuhuTRJNI(DWgSmHbCILDiVa)ZozLeMAMv8TfGCl9xLk4e6gguTFr3bCniZWPWyxcXKC8La(BUgcRghkUgK1HdbcfpEtw7zhjoTUfDrknwQDsYOCQk3XZCPDwOL0Ptnw3UVrUn8hgJiPmlRMkN6he2)8apT5bcB6x7fgHXydikN)QktG5axhzQMEZ6j9CJINef7II9knnpPGHVfKioEgOCq1LMCkGz68hHgkbduuuOFqWYs(wk4uSNL1ZH4nVT20VEccZkYXnFGA9boMDXMF8V0UKswZAx6n6QYpgvwSeZPZWwr3T6W()gWkislb(uD(ZQEPhxWH7j2)ztftSctQaRvRwyl1k7QoEZWuE)Q2gavDQEF1XvDn3V4)Z8AkP9zW1lvalREhO65RZKg9AgiwJBIUMs053TtXEeQkvcAyIuORNCJeZmZOtDEyZkuFlm7WrdhDEK)kJdHQxjuoj5aDAU(UDsQbdFDnLNjKB0OZIh7ylfQZrV7O2TM)NR(3d

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, no addons and the only loaded aura.

**Which version of WeakAuras are you using?**
3.1.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I dont remember the lag before 3.0.6 but i could be mistaken.

**Comment by InfusOnWoW** [comment]
You probably have hardware cursor enabled.

**Comment by Perfek00** [comment]
> You probably have hardware cursor enabled.

Thanks for the tip. I don't see the the hardware cursor option in settings. I found the following script:

`/script SetCVar("rawMouseEnable", 0)`

Is that the correct approach?  Spoiler: It did nothing for me, however I limited the Max Foreground FPS to my monitor refresh and that helped a lot.

What is your recommendation?

**Comment by InfusOnWoW** [comment]
Apparently the setting was removed and this is how the game now behaves.
