### ISSUE TITLE
Import disabled.

### ISSUE THREAD

**Issue by Skelektrix** [WeakAuras/WeakAuras2#2791]
Hi,

I cant import anything in my weakauras. 
Theres no tickle for disable/enable import anymore. 
If i import a string, all my spells are activated on my actionbar. 
Also my character moves while typing and not writing the keys i press in import window that are bound to skills/movement etc.

Any help pls?

I deleted Cache, Interface, WTF already.

**Comment by mrbuds** [comment]
Please open a ticket without deleting the issue templates, we need answers to all questions
