### ISSUE TITLE
Can't update WAs - "Import in progress"

### ISSUE THREAD

**Issue by Jbleedge** [WeakAuras/WeakAuras2#2792]
Everytime I update one WA, it desappear from the list and if I try to update another WA it says "Import in progress".
No matter the size of the aura, it does this even with basic "light" WAs.
I have to /rl UI and sometimes the WA is updated sometimes it isn't and I have to repeat the process all over again over and over.
Using latest WA addon and companion.
Not very good at this so if you're missing info please ask, thank you!

**Comment by InfusOnWoW** [comment]
You most likely have a lua error:

a) Follow these instructions

It sounds like you might be having an error. Follow these steps:
1. Install https://www.curseforge.com/wow/addons/bugsack
2. Install https://www.curseforge.com/wow/addons/bug-grabber
3. Try to do whatever it is you're having a problem with again:
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
    • GREEN
      • You have no lua errors from your addons.
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • You have an error with an addon, maybe not WeakAuras.
     • Make sure you clear the bugs once by alt + click the bugsack, to turn it green, then try to replicate the problem again.
          • You may also want to disable all other addons while you test this
     • There are error messages. Click on the red bag to see them.
     • Copy all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
     • Paste the error messages into https://pastebin.com/ and click "Create New Paste"
     • You will be redirected to the new Pastebin that you just created. Copy the URL and share it with us, and we will be able to give you more specific advice.

Or 
b) Disable all other addons.

**Comment by Jbleedge** [comment]
Ok, I've tried. Some WAs are getting updated correctly, some other don't.
So the first two that got me the problem are these:

https://pastebin.com/0Dahk7CR
https://pastebin.com/UnADrNv1

**Comment by InfusOnWoW** [comment]
Appanrently your settings are broken, if you have backups of your aura, you should try those.

**Comment by InfusOnWoW** [comment]
No, something broke the settings of your existing auras. That is very rare, but everytime we have seen that it was a other addon that interferred.

**Comment by Jbleedge** [comment]
Ok... I'll try to understand what it is even tho I'm not that great with these things :D
