### ISSUE TITLE
Import disabled.

### ISSUE THREAD

**Issue by Skelektrix** [WeakAuras/WeakAuras2#2793]
## Describe the bug

I cant import anything in my weakauras.
Theres no tickle for disable/enable import anymore like in older Versions of WA.
If i import a string, all my spells are activated on my actionbar.
Also my character moves while typing.
No Focus on import frame.

**Do you have an error log of what happened?**
 NO ERROR

```plaintext
PASTE ERROR HERE
```
No ERROR

### To Reproduce

Open Import Frame

1. Go to 'import'
2. Click on 'CTRL+V' or type anything on keyboard
4. See error No - Focus lost

**Screenshots**

you would only see one letter after CTRL+V

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
 

Yes

**Which version of WeakAuras are you using?**
 3.1.2 also tryed Alpha/Beta

**Are you on World of Warcraft Classic or Retail?**
 

- [ ] Classic
- [ X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Module Disabled, offline.

### Additional Info

It feels like The Menu (espacially the Import Frame) is in background and not in Focus.
I'm able to change the numbers/sliders in the options section on the right.
Also copy the Bug report is not working.

 I can type one letter in Import frame then loses focus 
by spamming mousebutton again i can type another letter...

**Comment by InfusOnWoW** [comment]
You likely have a lua error caused by another addon.

Follow these instructions to get the error message:
It sounds like you might be having an error. Follow these steps:
1. Install https://www.curseforge.com/wow/addons/bugsack
2. Install https://www.curseforge.com/wow/addons/bug-grabber
3. Try to do whatever it is you're having a problem with again:
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
    • GREEN
      • You have no lua errors from your addons.
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • You have an error with an addon, maybe not WeakAuras.
     • Make sure you clear the bugs once by alt + click the bugsack, to turn it green, then try to replicate the problem again.
          • You may also want to disable all other addons while you test this
     • There are error messages. Click on the red bag to see them.
     • Copy all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
     • Paste the error messages into https://pastebin.com/ and click "Create New Paste"
     • You will be redirected to the new Pastebin that you just created. Copy the URL and share it with us, and we will be able to give you more specific advice.

**Comment by Skelektrix** [comment]
Step 1: I deleted everything.

Step 2: Reinstalled WoW Retail.

Step 3: Only Addons -> BugSack / BugGrabber / WeakAuras 3.1.2. / installed via CurseForge client / /console ScriptErrors 1 on.

Step 4: Open WeakAuras / Open Import / Left-Click on import frame -> focus OK -> type one Letter - > Focus lost -> left-Click on import frame -> focus OK -> type one Letter -> focus lost and so on.

Step 5: Every setting in WoW Retail is on Default . 
In Windows 10 x64: no 3rd Party App like YoloMouse etc.

Step 6: I made 2 screenshots, you can see the frame focus lost ->

![WoWScrnShot_120820_062317](https://user-images.githubusercontent.com/51407614/101444031-ee9cfd00-391e-11eb-8763-e57789cb624d.jpg)
![WoWScrnShot_120820_062526](https://user-images.githubusercontent.com/51407614/101444038-efce2a00-391e-11eb-9318-ad4d41923fe2.jpg)

**Comment by Skelektrix** [comment]
Step 1: I deleted everything.

Step 2: Reinstalled WoW Retail.

Step 3: Only Addons -> BugSack / BugGrabber / WeakAuras 3.1.2. / installed
via CurseForge client / /console ScriptErrors 1 on.

Step 4: Open WeakAuras / Open Import / Left-Click on import frame -> focus
OK -> type one Letter - > Focus lost -> left-Click on import frame -> focus
OK -> type one Letter -> focus lost and so on.

Step 5: Every setting in WoW Retail is on Default .
In Windows 10 x64: no 3rd Party App like YoloMouse etc.

Step 6: I made 2 screenshots, you can see the frame focus lost ->

![WoWScrnShot_120820_062317](
https://user-images.githubusercontent.com/51407614/101444031-ee9cfd00-391e-11eb-8763-e57789cb624d.jpg
)

![WoWScrnShot_120820_062526](
https://user-images.githubusercontent.com/51407614/101444038-efce2a00-391e-11eb-9318-ad4d41923fe2.jpg
)


Am Mo., 7. Dez. 2020 um 17:15 Uhr schrieb InfusOnWoW <
notifications@github.com>:

**Comment by InfusOnWoW** [comment]
That frame is not meant to be typed into, but for the import string to be pasted in.

**Comment by Skelektrix** [comment]
Fixed!

I need to hold CTRL before i open the import window frame. If I then press
V it worked....

I used to just press CTRL+V when window was active.

InfusOnWoW <notifications@github.com> schrieb am Di., 8. Dez. 2020, 16:50:
