### ISSUE TITLE
Model Overlays Not Hiding on Zone Change (?)

### ISSUE THREAD

**Issue by EmElw** [WeakAuras/WeakAuras2#2794]
## Describe the bug

Overlay model that is shown and hidden via conditions becomes permantly shown once a load screen zone change happens. Seems to create duplicate models if set to show via conditions again, presumably because there's an "stale" model overlay still active.

### To Reproduce
<details>
<summary>aura string</summary>
!WA:2!DAvZVnssv8XRz1c(akXtMadZIO3i2OKvdMDYoenlsrRCNXzsg8y702zZSxOD1Dx2DTPDv9wv1o25acS4WWb(YiXvewZUN4KVZbYboxyH4pGiUW18xaVQA32z2vinIsYUR6vVp(9(OEvL7GI9kgum4fBmH4ZOnzjCF8BFl(G6D6iWYC8HZNmfr9dz8gmcv6TFLATQ4mZNXIcyNtBEojg3(YSLvc6Id5iFjHrf76iKiUSGnHsKBooG56NiKSEHEPFhK7VfX8rrwbijYApRtXOZkNWrIspblFmqBleSYft7xIeSDHomUL797BrOwXicxSLwSssoPBxmxSTvaRGfmiDS6Nr1crdwUQeUpMkT2BpRn2FoETAWzD5yHWARMX4OOT3WsgIPgfPhlHutFeTIwEXwBCA5w7FOR9jTAvVMBdNknBUX9xAfHwr1q9W33QdksaFEf3it1ECq3MvyGPVcQFDH9rsCV))r9nScbuukQL8Kxdqtdka)86ajxryHrz5HF6M85tFXAosOu4mBuIKnkauNUQO4dM1ftXCIFZq251PteWNYrNJgkUsK4z81gCChYaNMnQuT60eb2vZtx)G2tcWEjD60AymMFyLQno4KQ2syHhuOjte8eQrEvX4v1I9kgQTDcug6fhHgI5og(IV7)Z6GR0YJ8emU3Zyb42ZahpQzwMD6PKOaRNWzNldNzay2oThzMEuGOWc3PjazYGPU7xUzl3MTk70A8c()6)1DDOWxrHXA9ycyThPNQrB7Xj05rZ1vRPUZMQv(7Q7PEh131rs6Hdu3EN3V0JuVt86lCehmkyyMxOw)nuFF17Q2ST69alDPwV68CZiMST67PSuB9gQ7Q(oQsfMgqeFAcfo52hVdIomEvKzERuZRdc)LBDn0baZPOOpgY0qY84RpdJJldEJV0rNEdhlWrDmDkuVjKTeqAbY74WjqWWb3v3w4PVyT4Is8ajKwraMF(82mX31q08hCwVhcyy(eBkJIhVy7nExr8k3qd7ZIy8NMlxU8xLsndd2LpPv94BBiQRcbvr8pLeidTldlVo1wKb4adXFXS0oDFYCeDPz)pfAwr6me8hodkZWTaI21QxRI6ECWR08mXWOVbg5HX45obvE9(WFeAssVNHdij9EfppZoZm0oNXdoLJIhD68jPMVprq8IWTN7X3OxC8QhvRwfhx76Wr6N5C0toS1SfgUj5c8DN7pp)vSJExZjO6N0Q6r1Q0zQhyqm3vaIKxDVXGtLs5Y5B4Vm(oNsgOYefd99JxT5NLG4yRdsIISonek0MnFBwQ9)xZ6gXo)ao(ZsWu)Hn(AVFPD(rPrr9gt1)LH1r6fAyoZlrkz069XC4O7en5QyAxz4Dm8NfdhRxS)ImGUu)jzucT1BgAyb6igHZBasRqI)zu4qFEZovjW8vngW2a7WxuChumj8kpe3ThCaiY1pIe3EA6CH0nrCC8Ql3DEujCjd8H5UmDrhse(Oa(dEWh8Oh(ODMKsmgjdJ320mq8d3TZaxe3pK0JrdmTcOcIULzmJlrrL6TZs9khMJNUyyUByTb)7vgzksbPYPU3uDMeLY4nKDqURxIzuuCik)n0XfzA(IBOz5cQdY5fIjDdLhBhXqbF8vlA)Dgf6)02w3myDNEjrssbh)iKqSU6xwyYswGgr26sndzUPNGopBRFeYm4ukuWwp28aIcJYExr7XikPNXV2v9noa6bU3LyKa3uYn1cV1SS7xC13hWfyqzbIrAE0kxTNDpeHAeu9RFl1Vr9Bv)oy638ltX(cgRxoN0OYejZVFANUVDo3XBqcIV9J5jKaRFG1nUbWz5b)PD4qZCavWttYFD6PVd0K0GWR5(ovQuZdGwhs3c7akAQTZp54UNjREcBxoHQngomETm3w3Q5XebckQccDox3J64jApZuxi(XB64hI9pBx1kV5O(iorZOT(YsN(OOeCEOAcr7IfV3MQx2EumNbHgi(8TG6IspS0xPWf46Ph(r)Np0mo8J(h)E94pSysE1xO(JBQ(ZG5YRMmHrZU0r9Y8Qp3ydGJpCD1xeFNVSfmbuq2duR823AdwC8AnQw(tGMxTkxfErP7jnEC5wvutMM(0qJBPEzCPoMRKy0T22IJH7sOwWBdHl38jOiYfO5B9Z2Z6H6xKKIITbu8NM)9NpLqtVdb4SG6x1UOW5dk9Gs7uS))85)3
</details>

Using the aura above, changing zone with load screen. 
For posterity, this aura is in my setup in a dynamic group that is anchored to an element in another dynamic group.

**Which version of WeakAuras are you using?**
3.1.2

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X ] Retail

**Comment by InfusOnWoW** [comment]
I believe this is fixed for the next release and the current alpha.
