### ISSUE TITLE
 I can't add and remove any aura from the pre-patch output

### ISSUE THREAD

**Issue by bojote** [WeakAuras/WeakAuras2#2797]
## The error is that I do not get the interface to add or remove any aura, if not that I get a small box with only 3 options

and when I use the /wa or /WeakAuras command I stop serving the chat

**Do you have an error log of what happened?**
Since leaving the pre-patch, I have a friend who happened the same
his solution was to delete the game and reinstall it

Note that if the error looks like `[string "--[[ Error in ' my awesome aura' ]` then the bug is in the aura that got mentioned, not in WeakAuras itself -->
if you don't let me add or in which case remove I guess it's the weack

```plaintext
I don't know how to get the error ... (sorry in this regard ... I don't know how to do it
```

### To Reproduce
and reinstalled the addon several times, but it still does not work (and I make sure that the vercion

1- give the specific click to the map option (it does nothing
2- put the command in the chat: it won't let me enter or the chat stops working

**Screenshots**
At the moment I do not have it available once the servers are available and I will do it with the weack2, if it fails I will leave the capture in responses (if it works I will close the post or leave it in the comments

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I used to only have the weack

**Which version of WeakAuras are you using?**
i use the final the moment

**Are you on World of Warcraft Classic or Retail?**
-  [  ] classic 
- [ x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
before preparch

**Comment by mrbuds** [comment]
Your ticket is missing the most important parts, we need the Lua error, your files, and the exact version number of WeakAuras you have installed.

**Comment by InfusOnWoW** [comment]
No response from reporter.
