### ISSUE TITLE
"Remaining time" condition in multi-target triggers

### ISSUE THREAD

**Issue by Yakkers17** [WeakAuras/WeakAuras2#2802]
I like to use the remaining time condition on my DOTs to have the countdown text turn red when it's within the pandemic window. With "limit one target" aoe DOTs like arcane mage's nether tempest, I use the multi-target trigger so I can tab through different targets in the aoe pull while still tracking the DOT. I see multi-target doesn't have the remaining time condition though, so I can't do my red text.

It's very likely that this is a limitation of how multi-target works, but if not, this is something I'd get a lot of use out of and would love to see.

**Comment by InfusOnWoW** [comment]
Yes, that's because the multi target trigger has only unreliable duration information. Using the nameplate trigger is much better.

**Comment by Yakkers17** [comment]
Well that doesn't do it because the nameplate has to be onscreen. In what way is it unreliable if it's able to display the timer? I'd just want to be able to display/hide auras based on what the timer is showing.
