### ISSUE TITLE
failure to load conditions window for dynamic group and children

### ISSUE THREAD

**Issue by HexxGamerDraenor** [WeakAuras/WeakAuras2#2808]
## Describe the bug

I expected the conditions window to load, and instead I got a blank window that didn't allow me to edit the conditions. When I accessed the children directly, the conditions would load but I could not add/edit them or it came up with an error
**Do you have an error log of what happened?**

```plaintext
13x WeakAurasOptions\ConditionOptions.lua:2346: attempt to index field 'check' (a nil value)
[string "@WeakAurasOptions\ConditionOptions.lua"]:2346: in function <WeakAurasOptions\ConditionOptions.lua:2339>
[string "@WeakAurasOptions\ConditionOptions.lua"]:2512: in function <WeakAurasOptions\ConditionOptions.lua:2505>
[string "@WeakAurasOptions\ConditionOptions.lua"]:2581: in function `?'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:912: in function `EnsureOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:889: in function `UpdateOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:931: in function `FillOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:972: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:970>
[string "=[C]"]: ?
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:156: in function `SelectTab'
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:67: in function <...Ace3\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>
```

### To Reproduce

1. Go to the dynamic group
2. Click on conditions
3. See error

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes
**Which version of WeakAuras are you using?**

3.1.4
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

yes, 3.1.0

**Comment by InfusOnWoW** [comment]
We obviously need that dynamic group you are clicking on in step 1.

**Comment by HexxGamerDraenor** [comment]
https://wago.io/WlK9EBtuU
