### ISSUE TITLE
Colour different in Display and Animation

### ISSUE THREAD

**Issue by Rehok** [WeakAuras/WeakAuras2#281]
What steps will reproduce the problem?
Assign a colour in display colour box e.g 72,0,250 and then assign it in a custom colour function and it returns a different colour

Animation Return - https://i.imgur.com/mhWo8x3.png
Display Return - https://i.imgur.com/LixgpYZ.png

What is the expected output? What do you see instead?
Exact same colour

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

Yep still appears

What version of WeakAuras are you using?
2.4.21

Was it working in a previous version? If yes, which was the last good one?

Not sure, Just made this aura on this verison

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

None

Please provide any additional information below.

https://wago.io/rkG1QbM5Z Aura im using, Requires a paragon rep if you dont want to edit it

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by emptyrivers** [comment]
Custom animation expects normalized rgba values, and clamps the values to the 0-1 range. Divide your values by 255, and you will get the expected result.

**Comment by InfusOnWoW** [comment]
What rivers said.
