### ISSUE TITLE
Want to import Aura, cant do that: Aura: https://wago.io/2zlSvoluD

### ISSUE THREAD

**Issue by Zorro420** [WeakAuras/WeakAuras2#2810]
## Describe the bug

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by Zorro420** [comment]
no error, it worked already.

**Comment by mrbuds** [comment]
This is not a weakauras but a MDT string
