### ISSUE TITLE
Totem Name Tracking

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#2811]
## Describe the bug
Seems as though the totem trigger checks for exact string match when trying to match name. This means that if a capital is missed, the totem won't track by name. 

**Do you have an error log of what happened?**
https://wago.io/UwwhYRN7E

### To Reproduce

Make an aura to track totem name, and use lowercase for everything. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.1.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
N/A

### Additional Info
A solution would to use the lower function on both the totem name input and the string recieved from the wow api. I don't know if this extends to any other trigger that accept name as a check, though if it does, it's probably worth looking at those too.

**Comment by InfusOnWoW** [comment]
Yeah, that's how these things have always worked. Changing that everywhere would take quite a bit of work for something that I'm not sure is correct in all cases either.
