### ISSUE TITLE
An option to unlink weakauras from dynamic groups and preserving it in future updates

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2815]
**Is your feature request related to a problem? Please describe.**

A lot of players want to position specific weakauras individually in dynamic groups and the only satisfying solution would be an option that allows you to unlink specific auras.

1. The initial idea is usually to make a regular (non-dynamic group) but that sucks as an author since you have to pre-determine positions for everyone that usually don't go well with everyone's UI.

2. Another idea is to do it via custom grow options by adding a custom option to each WA that allows you to unlink the weakaura and enter x, y coordinates. This is unintuitive because you have to enter coordinates and can't just drag it around and I believe the changes wouldn't even be reflected immediately while in options.

3. "The user can just remove the weakura from the group". The issue with this is that it's not very update friendly and creates a mess.

**Describe the solution you'd like**

I would like an option to unlink a weakaura from the dynamic group while preserving the history(?) when updates are done.
Unlinking it should allow you to freely move the weakaura.

In order for the user to understand that it's a thing, I thought maybe a clickable chain would do the job, something like:
![](https://i.gyazo.com/3a8ab29a298b242625db0094a39ac17c.png)

**Describe alternatives you've considered**

suffer

**Additional context**

I believe this would also help authors of HUD-Type wa packs like the class stuff etc.

**Comment by InfusOnWoW** [comment]
Well a "easier" solution is to have a setting where the dynamic group doesn't layout some children.

The benefit of such a solution is that we could then merge groups and dynamic groups.

**Comment by Causese** [comment]
You mean something like hybrid sorting where u can select which auras to "unlink"? Sounds good aswell

**Comment by InfusOnWoW** [comment]
Yes.

**Comment by 1ps3** [comment]
Continuing on from this, I'm using this type of group at the moment, with custom grow which is great. I think for this to be a real thing would be for a new setting in the dynamic group to create different sorting groups, and then applying each aura to them. This sounds like it would be something cool but I have no idea how to handle old data coming it. This is also a solution to nested groups too.

**Comment by Causese** [comment]
I guess the nested PR takes care of this
