### ISSUE TITLE
weakauras will not work

### ISSUE THREAD

**Issue by Jazifi** [WeakAuras/WeakAuras2#2816]
## Describe the bug
I had to reinstall all my addons and they all work except for weakauras below is my message on wow
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:2796: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2796: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2754: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2660>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2789: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2320: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2327: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1009: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:981>

Time: Mon Dec 14 20:42:46 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:2796: Improper arguments to WeakAuras.SetRegion - regionType not defined
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2796: in function `SetRegion'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2754: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2660>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2789: in function `Add'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2320: in function `load'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:2327: in function `AddMany'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1009: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:981>

[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1057: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1131: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1082>

**Comment by InfusOnWoW** [comment]
That means that your settings are entirely broken. There was a bug around half a year ago, that broke the settings if you downgraded. Since that was a while ago, I'm a bit suprised that you have the issue.

If you do have a backup then restore that, or start from scratch by deleting the WeakAuras.lua file in the WTF folder.
