### ISSUE TITLE
Trigger Status: Armor Kits

### ISSUE THREAD

**Issue by ManagerWoW** [WeakAuras/WeakAuras2#2817]
Shadowlands has added Armor Kits and Weapon Oils. Weapon Oils already work using the "Weapon Enchant / Fishing Lure" Aura Status, however Armor Kits currently do not work.

Can the "Weapon Enchants / Fishing Lure" be updated to be "Gear Enchants / Fishing Lure", and add the Chest slot to the drop down for available item slots. http://manager.heroicstrike.org/pyr4rigj.png

There are currently 2 armor kits: 
https://www.wowhead.com/item=172346/desolate-armor-kit
https://www.wowhead.com/item=172347/heavy-desolate-armor-kit

Oils show up as a player buff but armor kits do not. As far as I know, you have to parse the item slot tooltip. Example: http://manager.heroicstrike.org/34bNNiPL.png

**Comment by InfusOnWoW** [comment]
Due to Blizzard not providing a API for that, we won't add a trigger for it.
