### ISSUE TITLE
Update/Import WeakAuras with default font and texture settings

### ISSUE THREAD

**Issue by Jerks88** [WeakAuras/WeakAuras2#2819]
**Is your feature request related to a problem? Please describe.**
Everytime i update or import a new weakaura its a pain in the ass to re-/configure the fonts and textures to fit it into my ui. 
For some WAs its not possible to inherit these settings from the group, then you have to go through every single WA to check if the font and texture is correct.

**Describe the solution you'd like**
Would be great if there is an option to set a default font and texture for the whole WA addon and give us the possibility to change the fonts and textures of new WAs while importing or updating (with companion) to the default ones.

**Comment by InfusOnWoW** [comment]
That's a variant of: https://github.com/WeakAuras/WeakAuras2/issues/1129
