### ISSUE TITLE
Custom chat message sends %c message

### ISSUE THREAD

**Issue by pmkaboo** [WeakAuras/WeakAuras2#282]
**What steps will reproduce the problem?**
actions
on show
type `say`
message `%c`
custom code
```
function()
  return string.format("1")
end
```

**What is the expected output?** 
chat message in say, saying `1`

**What do you see instead?**
chat message in say, saying `%c`

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**What version of WeakAuras are you using?**
2.4.21

**Was it working in a previous version? If yes, which was the last good one?**
dont know

**Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack).** 
there are no errors

**Please provide any additional information below.**
other special codes seem to work as expected

**In case you do know which aura is problematic, please export the string and paste it below.**
```
diKzeaGifsUKkfJsqXPeu1TuLSlfIHPiDmrSmvYZOittqUMOY2uv6BkuJtu15efhuvfluvvpKuYffPSrsHpksyKQQKtQs1kvuVuHuZuK0njfTts1pvfDusP0svP0tjMQqxvqLTks0zjLkRLukMRGs7f9xL0GvvCykTykQhRutMcxwQnRGplWOfP60GwnPu1RvfMTKUnj2Te)Mkdxjwov9CGPdDDvSDfX3vvPgVQuNxuA)K0mHrkqk3ly7hS7oS33UciS31t5QMqWEvBpnaHUIMw)dkakxJeAKRekkumOyWiL3phgans9xjJKjtM8JhN5kZ38JZrj7ZHbqJuJx5nzk)38FZDLyA83XJV4WRq5Oy2UFe4DNIHwUQZZi1dr9PePm4kOgvBaGYZWft9UEAumB9A5QopJupH6tjsP6SgmsbT1UGxmsr5uriJejsbT1UGmsr5uriJejsbS0BgPaGLGAt9eIu2vlaWifaSeuBkA(uF0ePCa96UAba(NI3UBgPOCQiKrIePSmzbT1UGmsr5uriJejs5a6vWsV5FkExTzKIYPIqgjsKYGDJqxHrkkNkczKirkgWHb4(uXSmsr5uriJejsKIVdGUsm7stXE8wZwpfaA3pa0mfybIRBNYsTX2G6juW(nE8nLF8koFwkGfR)b)tz7QopJePy3iCsh9WGG2RPZOP(RKPumGGLQnBSFJP2diLB2uqpmiO9msbZU0uaOfpak9KUGusr1z2wv)OLZvnC)Uq5u6jDbPypOJYb0RNce5Fk7daDkRPdnAkiuPnisb73intbSy9p0e69opntj9ggKos9CuqOs7PzkopSlOfHUcLF9827AZt94pPUExpLPDRKgLYrj6HbbThq9ekWTRqZuSBe6kagPaqRhzKIsda2GEfZU0uKF0okknaydAk3SPy4wvAaWg08pfLgaSb96(aqNcLHtzJqxjmHxDw9J6h1pQF8nE8f1pa0dlbJm48kwmmJkzuHxDUlgQZQZQZQZQZQZQZQZQZQZQZQZejsbSy9p0YvDEgPEc1iFMPjxMUUMg6B(Cxj54WRCMOUjQr(qt)oojJPPHcDfkZLjo8kNjIuGBxzfanAkPMMgrkqdkPqlkgqWs1Mn2VXBHbPJuUztXac0(tzJWjnfBTszFaOtj2VXWTyyXMspPlifybIRa06X2G6jePmH6jHUsisca
```

**Comment by emptyrivers** [comment]
As a workaround, you can use a custom action as so:
```lua
SendChatMessage("Your message here")```
Click [here](http://wowprogramming.com/docs/api/SendChatMessage) for documentation of SendChatMessage.

**Comment by InfusOnWoW** [comment]
Fixed in the alpha/next release.
