### ISSUE TITLE
About the animation when the glow disappears

### ISSUE THREAD

**Issue by X-Zou** [WeakAuras/WeakAuras2#2823]
At the moment the glow on an original Blizzard icon disappears, its halo will flash for a last time then vanishes.

While using following "condition":

["check"] = {
						["trigger"] = 1,
						["variable"] = "show",
						["value"] = 0,
					},
					["changes"] = {
						{
							["property"] = "sub.1.glow",
						}, -- [1]

The glow on this WA icon will vanish immediately without a "last flash".

I wonder if this "last flash" can also be added to WA glow disappear animation.

BTW, I found that the glow disappear animation of the condition "FRAMESELECTOR" will show a same "last flash" as the Blizzard icon (As I hoped):

["check"] = {
						["trigger"] = 1,
						["variable"] = "show",
						["value"] = 0,
					},
					["changes"] = {
						{
							["value"] = {
								["glow_frame_type"] = "FRAMESELECTOR",
								["glow_frame"] = "WeakAuras:TestGlow",
								["glow_action"] = "hide",
							},
							["property"] = "glowexternal",
						}, -- [1]

3.1.3
Retail

**Comment by InfusOnWoW** [comment]
Due to how we handle glows, we hide the glow immediately on finishing.
