### ISSUE TITLE
Dynamic text tooltip is too long

### ISSUE THREAD

**Issue by Nightwarden24** [WeakAuras/WeakAuras2#2824]
Dynamic text tooltip is too long. There are situations when it doesn't fit and extends beyound screen. Especially if you use more than 2-3 triggers. 

Example: Resolution is 1920x1080 (full HD); UIscale is not used.

From my point of view, the tooltip has a maximum length when selecting Aura or Character Stats as a trigger. In these cases, a description already occupies more than 70% of screen height.

<img src="https://i.imgur.com/TmEfI93.png"  width="300"/> <img src="https://i.imgur.com/sbj0AXY.png"  width="300"/>

Create 2 Aura triggers with "all" options, and the tooltip no longer fits on the screen.

<img src="https://i.imgur.com/8AdAtAA.png"  width="300"/>

Situation is slightly worse in Russian locale (more space is required). 

<img src="https://i.imgur.com/xMv6PRc.png"  width="300"/> <img src="https://i.imgur.com/V70g5I2.png"  width="300"/>
<img src="https://i.imgur.com/HZQHydM.png"  width="300"/>

Possible solution to the issue is using a separate pop-up window.

**Comment by mrbuds** [comment]
AceGUI / AceConfigDialog doesn't have an option for scrollable tooltip on editbox widget, adding the option doesn't seem to be trivial

**Comment by InfusOnWoW** [comment]
Well, the tooltip is also a rather stupid interface. You can't see the tooltip while typing, which was fine when there were just 4 text options, but nowadays it doesn't really work.

I think making it appear to the right, in the same way as the snippets could work.

**Comment by mrbuds** [comment]
This was fixed with https://github.com/WeakAuras/WeakAuras2/pull/5102
