### ISSUE TITLE
Script ran too long

### ISSUE THREAD

**Issue by machpm** [WeakAuras/WeakAuras2#2825]
## Describe the bug
Config menu doesnt show up, but all auras work. It has something with ElvUi becouse if i disable it, config menu will show up. But until now everything works just fine

**Do you have an error log of what happened?**

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:1048: script ran too long
Time: Wed Dec 16 17:33:14 2020
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:1048: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1048: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1131: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1082>

Locals: 

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Without ElvUi it works just fine

**Which version of WeakAuras are you using?**
3.1.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
We obviously need your settings to reproduce the issue.

**Comment by machpm** [comment]
i think the problem was in this [https://www.icy-veins.com/forums/topic/55071-weakaura-for-mythic-great-vault-loot-item-level/](url). After deleting it without using ElvUI it is working just fine. So maybe if you could find what can be wrong with that aura, becouse its so handy one

**Comment by InfusOnWoW** [comment]
Well, no, this is a bug tracker not a forum to ask for help with random auras someone else created.
