### ISSUE TITLE
Class Colored Progress-Bars

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#2828]
**Is your feature request related to a problem? Please describe.**
There is no really good way to Class Color a progress bar in a neat fashion

**Describe the solution you'd like**
Pretty much the Same thing you can do with text formating options but Class color the ProgressBar instead of text using state.unit could be a simple text box rly

**Describe alternatives you've considered**
Currently I either have to use 12 conditions or do Code sth along the lines of
function()
    if aura_env.state then
        local config = aura_env.config["display"]
        local classColor = {aura_env.state.member.classColor:GetRGBA()}
        local barColor, nameColor, timerColor
        if config["colorBarUseClass"] then
            barColor = classColor
        else
            barColor = config["colorBar"]
        end
        aura_env.region:Color(unpack(barColor))
    end  
 end
yes i know that code is shit but it's an example of how zen tracker does it and was the only thing I had without having to do it on my own :D

**Additional context**
Pretty Self explanatory i think

**Comment by InfusOnWoW** [comment]
That's https://github.com/WeakAuras/WeakAuras2/issues/2013
