### ISSUE TITLE
Conditional "on cooldown"="false" not working

### ISSUE THREAD

**Issue by Railander** [WeakAuras/WeakAuras2#2831]
Conditional "on cooldown"="false" doesn't work, it never triggers. "true" statement does.

tested specifically for "glow" "visibility" "unchecked".

**Comment by InfusOnWoW** [comment]
It does work.

**Comment by Railander** [comment]
did more thorough testing now and found the exact way to replicate:

icon aura
On trigger,

type="status"
status="cooldown progress (spell)"
spell=<spellofchoice>
show="on cooldown"

show _must_ be set to "on cooldown" and seems to be where the problem lies. it does otherwise work perfectly when set to "always" or "not on cooldown".
requires a second trigger of choice to actually show the icon while off cooldown.

then on conditions,

if trigger "on cooldown" = "false"
then glow = "visibility" unchecked

create a glow and enable it on display if you haven't done so yet.

**Comment by InfusOnWoW** [comment]
Yes you are is incorrectly setup.
