### ISSUE TITLE
Thorns aura always displayed even when not buffed

### ISSUE THREAD

**Issue by thedurko** [WeakAuras/WeakAuras2#2832]
Hi there,

I play an affliction warlock. I added the thorns aura using the simple template, leaving the load options blank. This is a buff cast by a druid, but I want it displayed only when cast on me. Instead it always displays by default (have the same setup done with another druid buff, Ironbark, works fine). Is this a bug?

![Screenshot 2020-12-19 at 08 53 05](https://user-images.githubusercontent.com/76242853/102684322-baa3c080-41d7-11eb-970e-343276270e9d.png)
![Screenshot 2020-12-19 at 08 52 59](https://user-images.githubusercontent.com/76242853/102684324-bc6d8400-41d7-11eb-9491-26d27875d4ce.png)

![Screenshot 2020-12-19 at 08 53 09](https://user-images.githubusercontent.com/76242853/102684321-b9729380-41d7-11eb-8f8e-fa90d52b96f9.png)

**Comment by InfusOnWoW** [comment]
You can adjust what exactly the aura shows on the trigger tab.
