### ISSUE TITLE
Dynamic Information controlling TSU Conditions

### ISSUE THREAD

**Issue by LexaraTalionis** [WeakAuras/WeakAuras2#2833]
**What did you expect to happen?**
I expected a TSU condition in the Conditions tab to update an aura, regardless of what Dynamic Information trigger is chosen in the Trigger tab.

**What happened instead?**
When using TSU triggers in the Conditions tab, the aura is only properly updated if that TSU trigger is also selected as the Dynamic Information trigger in the Trigger tab.

**Do you have an error log of what happened?**
No errors occurred.

**Describe what you clicked or did when the problem occurred.**
1. Import the following WeakAura: https://wago.io/Q1XxSJRwI
2. Note that the icon in the center of the screen is a mouse (from Dynamic Info), and moussing over any valid unit activates the glow (from Conditions).
3. Open WeakAuras, select the "TSU Condition Test" aura, and set Dynamic Information to "Dynamic Information from Trigger 2" on the Trigger tab.
5. Close WeakAuras.
6. Note that the icon is now a Hearthstone (from Dynamic Information), but moussing over any valid unit _no longer_ activates the glow (from Conditions).

**Screenshots**
N/A

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
3.1.4

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I do not know.

**Comment by InfusOnWoW** [comment]
You have to set the cloneId correctly. You need to use "" as the clone id for your first trigger.
