### ISSUE TITLE
Aura still active if you release before the encounter end

### ISSUE THREAD

**Issue by Krattan** [WeakAuras/WeakAuras2#2834]
## Describe the bug
While wiping on Loatheb I noticed my heal order aura not deactivating if I released and started running before the encounter ended.

**Do you have an error log of what happened?**
no

### To Reproduce

1. Aura with Encounter ID(s) 1115 as the only Load setting.
2. Die.
3. Release.
4. Start corpse running before everyone has died ending the encounter.

**Screenshots**
-

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
-

**Which version of WeakAuras are you using?**
## Version: 3.1.4

**Are you on World of Warcraft Classic or Retail?**

- [x] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I dont know

### Additional Info
https://wago.io/ekXf9XT5V

**Comment by InfusOnWoW** [comment]
We can't work around issues where Blizzard does not send a ENCOUNTER_END event.
