### ISSUE TITLE
[Classic] Aura trigger with unit=group can wrongly update duration

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#2837]
## Describe the bug
With an aura trigger/unit=group/auto-clone with multiple exact spell id filter
It seems that when 1 unit take the debuff it refresh to full duration on other units that already had it (on classic)

**Do you have an error log of what happened?**
no error and i don't have a video record of it but i'v seen it and had reports with that loatheb debuff tracker aura https://wago.io/IlHoMjt3X

**Which version of WeakAuras are you using?**
3.1.4 alpha gfe2f0ce

**Are you on World of Warcraft Classic or Retail?**
- [x] Classic
- [ ] Retail

**Comment by mrbuds** [comment]
https://discord.com/channels/172440238717665280/218087027042811905/791379106151399464

**Comment by caspervk** [comment]
Logs:
[Transcriptor.txt](https://github.com/WeakAuras/WeakAuras2/files/5755878/Transcriptor.txt)
[loatheb.txt](https://github.com/WeakAuras/WeakAuras2/files/5755887/loatheb.txt)

**Comment by mrbuds** [comment]
Looking at your logs, the issue come from the 1st "Corrupted Mind" debuff is refreshed on all healers every 11-12s

This information is received with a CLEU event that only have the spell name information, so it's impossible to distinguish which of the 2 debuff is refreshed in a generic way (a custom made trigger can ignore those SPELL_AURA_REFRESH events)
