### ISSUE TITLE
Multitarget doesnt work. 

### ISSUE THREAD

**Issue by borisruzanov** [WeakAuras/WeakAuras2#2839]
## Describe the bug

I expected to show several agony on several targets at once. But in multitargets options it shows all the time only one. I checked lot of videos on you tube. Looks like in previous version it worked correctly. Now it does not

**Which version of WeakAuras are you using?**

3.1.4

**Are you on World of Warcraft Classic or Retail?**

RETAIL

**Was it working in a previous version? If yes, which was the last good one?**

Based on youtube videos it worked fine

**Comment by mrbuds** [comment]
we can't help if you don't answer what is asked
