### ISSUE TITLE
"Status->Cooldown Progress (Spell)->Show GCD" that checks whether the specified spell is on GCD

### ISSUE THREAD

**Issue by razko** [WeakAuras/WeakAuras2#2840]
**Is your feature request related to a problem? Please describe.**
The "Show GCD" extra option for "Status->Cooldown Progress" trigger does not check if the spell specified in the trigger is subject to the GCD, it simply makes that trigger also track the GCD. If I'm creating a lot of cooldown-tracking auras for a new class/spec that I'm starting to play (which I'm duplicating over and over from a template whilst specifying different spells), I then have to go and manually check which spells are subject to the GCD and toggle the extra option as needed, which is where I find this frustrating. Or Blizzard decides to take a certain ability off the GCD rule and I miss the patch note and my UI never reflects that until I manually check...

**Describe the solution you'd like**
Imho, the "show GCD" extra option should be aware if the spell specified in the trigger is subject to the GCD or not, and shouldn't do anything if it is, i.e. this "Show GCD" option should be logically tied to the spell in the trigger. After all, it IS a part of a spells trigger, so if spell X is not subject to GCD, then "showing GCD of spell X" should show nothing.

If someone wanted to draw the GCD on an aura with no logic, there's the Status->Global Cooldown trigger which is perfectly suited for that instead.

**Describe alternatives you've considered**
If you don't want to change the way "show GCD" works currently, a new tickbox could be added like "Show GCD (smart)" or something, with a tooltip explaining that this will also check if the spell in the trigger is subject to GCD or not.

**Additional context**
The API has a function that lets us check if a spell is subject to the GCD: https://wow.gamepedia.com/API_GetSpellBaseCooldown

**Comment by InfusOnWoW** [comment]
GetBaseSpellCooldown does not work in the way you describe.

THe behaviour of the gcd option won't change.

**Comment by razko** [comment]
> GetBaseSpellCooldown does not work in the way you describe.
> 
> THe behaviour of the gcd option won't change.

Does it not? I'm very confused then. I pretty much quoted the wiki, and checked what it returned with a couple of priest spells (the ones off GCD returned 0 in arg2, all the other normal spells returned 1500). The way I understand it is that it returns the GCD duration that a spell will incur, and to my knowledge, all spells that incur a GCD are also subject (i.e. unusable during) to it and vice versa - spells that don't incur a GCD can be cast while player is on GCD. Where am I wrong?

**Comment by razko** [comment]
Maybe I wasn't clear in my original description/title, but I don't mean something that checks whether a spell is on GCD _right now_, like, dynamically. I mean we have spells like interrupts and defensives which are completely exempt from the GCD rules (don't trigger GCD and can be cast while player is on GCD), and I want the "show GCD" option to respect that; e.g. if I make a weakaura for let's say Kick or Pummel and tick "show GCD" on it, it won't actually do anything because Kick and Pummel are not subject to GCD rules.

**Comment by InfusOnWoW** [comment]
You might be right that the second return value is accurate enough. I was remembering the issues with the first value, that doesn't take into account various effects that change abilities.

Nevertheless, the behaviour of that option cannot be changed anymore. It has worked this way since forever. Maybe it would have been better to only show the gcd for abilities that trigger a gcd, but it's too late to change now.

As to adding a option for that specific behaviour. I don't see what that would add, since you can simply not tick the "Show GCD" option for spells thjat aren't on the gcd.

**Comment by razko** [comment]
Well, for me at least this would come into play in these scenarios:
- Making CD WAs for a new class/spec, i.e. specifically when I'm making _a lot_ of new WAs at the same time. It doesn't sound like a big deal when you just have to be aware of whether 1 spell is subject to GCD or not, but when you have to check and verify a whole spellbook, you'd wish the option was automatic;
- Blizzard changes something. They keep screwing around with which abilities are or aren't subject to GCD. I've had a couple of "surprises" where I suddenly and accidentally discovered something is now off GCD, whilst my WAs were still drawing the GCD spinner for those abilities as per BFA settings;
- There are some odd cases. For example, the new Discipline Priest talent called Spirit Shell replaces your Rapture. I had a weakaura for Rapture which automatically transformed into Spirit Shell, which I thought was great. However, Rapture is subject to GCD and Spirit Shell is not, and since I had "Show GCD" ticked on for Rapture, this kind of tricked me into thinking that Spirit Shell is on GCD as well, until I accidentally and surprisingly realized that it isn't. I've now made separate WAs for Rapture and Spirit Shell that load depending on which talents are selected, but it feels a bit odd to do this for an ability that transforms.

I'm repeating myself on the first two points though (sorry!), and I understand not wanting to change existing behavior, so I'll leave this be.
