### ISSUE TITLE
Audio and text being triggered on zone

### ISSUE THREAD

**Issue by Caldar** [WeakAuras/WeakAuras2#2841]
## Describe the bug
I have a WA that reminds me to click a trinket that provides an hour long buff. The WA reminds me if the buff is missing or when I have less than 5m on the buff. The issue is that when I zone somewhere (get a loading screen) the audio and text warnings play even though the buff is active.

**Do you have an error log of what happened?**
There is no error.

### To Reproduce
I zoned by using hearthstone, entering instance, etc.

**Screenshots**
n/a

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.14

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

https://wago.io/3kGA8VegG

**Comment by InfusOnWoW** [comment]
Is that only reproducable with the buff from that trinket? I can't reproduce it with a hour long battle shout buff.

**Comment by Caldar** [comment]
While I haven’t tested battle shout, checking for correct forms (shadowform, moonkin) or rogue poisons has the same issue when there is an audio cue involved. This happens every time you zone where there is a load screen.

**Comment by InfusOnWoW** [comment]
Then I need some easy to check aura and a loading screen that reliably triggers the issue.

**Comment by Caldar** [comment]
Literally any zone change portal, like Oribos to main city. Enter any instance. Anything that give you a loading screen causes the audio/text to fire even though the buff is up.

**Comment by InfusOnWoW** [comment]
Neither Shadowform nor Moonkin form are valid auras to test with, since they don't have any duration and thus immediately show the "expiring soon" aura.

I just tried again with a simple food buff and I can't reproduce your issue at all. 

So I need you to create the simples test case possible with clear instructions on how to reproduce, otherwise I'm not trying for a 3. time to reproduce it.
