### ISSUE TITLE
[Classic] Long fades in animation sometimes skip ahead

### ISSUE THREAD

**Issue by pmb123** [WeakAuras/WeakAuras2#2843]
## Describe the bug
i set a very long fade (120 seconds) from 50% alpha to 100%.  occasionally the "fade in" will just not occur (icon shows up with 100% alpha).

**Do you have an error log of what happened?**

no errors

### To Reproduce

unable to reproduce, seems random

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.1.4

**Are you on World of Warcraft Classic or Retail?**

- [x ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
unknown

### Additional Info

!WA:2!DrvZYTTnq4OrtNKH(sIIBAsM0wnUt8066jtKJt6L2dIQujowwYHIU29qhrqsirutcWcaQF8TOt5SEe05Esh6dGV1By00NGCOpa(jOlaLCtcpqcS7YD)(w8TOuZkPvIQe9UVzojKr7YY5H4hDJLOCzmJ3jtsyuHfFsN(9fyzPfiAiy)ygHkdA402ZXDziJLeXgr7oIKH9VC9wNOb4yBDs9Nk5KbdWCXxTnF1Y)1wojd7IY5O9MPFtrPyXdDRv7hE2ZdYfyxCQ)YuKmmgl6gZg1HEPW8PEOKmeCpedq4vyuIm(9I8aZ(J54(KXUDp2PvlxtgTSZPezqwcAcMpvKHtsoicieuH2GF)fCCANmmhjz8T(XF66m1nVpKPf9AuVRxVUE1D92dICVA7905r4aWPhaF(RCADCZtAnlNUIwwBRS(RfqY7XXcjHoiw9i1xAmmehtctWXtJa2QBRvQPQmVbJgrmnz1xOU)uDGAa7R2u95Z07qjaB955udSSHZfMAJaHejZfQTSYUdY0p8kQ)rSi8FEJRGthmNIs(fONd5(nxDogNvhyFO0vx74zcCsFZPO6ZacjGSbGchph4VlEGgpp8DBMvrIhl7jIrWb6zRKazpWy08QpJdhr9eRwytzu8SRDV1Jfz3(dYqdwcJ)6sLkv(9fwxJb76N41j7UgJAccPIeEkjsgBxh2EvrTiJXrgJVDzHk8xxHOln()9COH3FcWhod6oypWOD7oTDuBWbwPJzUjWqdmkdpZwrcQm72n5KlQ(MCue0hqv98(iUVUsln2gX4rNYrztpD1IcamKiibjy)vC(dMuYUZbTB742ZUJNxNJCp4LVYB51LUl5c8dwXOZ(O6O9AKzDoXR1bTDcIXKbXY3ANWqrdnQJWeKq4BKnxa9(4RidOmUrA7cJgP2oIuC2D1()ep(UM)D7abOstW8tR72QtJdDtZtKelBTw5EQZGfa80lMZnYcnEu3AgIssnI4x4csrU8DvcmTv3YlxlV7PhW5cmCbqKygkjlgP)5PcjhPPrXpyxU47llxesZCAy2H9H36C8TzC2ayssSBvtz2TAeorI(oRQWdhdIwAHJQFF1RJT6oRJctJSwnebP2hMBcbrclDkgjWgMSFGieLGNu21eYXLF6tEELjLQmUuHJXLvpw91xQJVRKJPdKX3mOqFvQa41lBNIi0MQ0BQ2qTVQNYxrG82NqjI4p18ccTyubi39YUFXzYQBzD0d4oCoJl85id)fVq9BwQ)WYgsM0kBZ13TQ12)mrGa5wuS9fmwAj1o(ZLSWHft83A3D2Ie9EepLXRIhNr4WPmayAFYaRf95Gka4dO0lFvHYRP2KULe0THRJtB3)FkzVCs0ck9KdpFu2r5P1GuPRcowDEz3rMbY5HxFnM101GmMpUqo)3veUp7j1EY(vg(pN9F)

**Comment by InfusOnWoW** [comment]
I tried your aura with a different buff and it worked, as expected.

We need a smaller example and some idea on how to reproduce that, otherwise there's no way we can figure out why this is not working for you. 

Although I also note that using the start animation is the wrong way to animate this, a main animation using a alpha based on the remaining time sounds like the better choice anyway.

**Comment by pmb123** [comment]
so is there any difference between the start and main?  i have the trigger as a time remaining, should i just switch the animation parameter from start to main?
