### ISSUE TITLE
WeakAuras 3.1.4: Not able to find PvP icons

### ISSUE THREAD

**Issue by bbenefield89** [WeakAuras/WeakAuras2#2844]
## Describe the bug

Skill Name: Sharpen Blade
Skill Icon: spell_warrior_sharpenblade
Skill ID: 198817

When creating a WA that uses a PvP skill, WA cannot find the correct icon via the Trigger tab when given the skill name, icon, or id. Instead, WA returns the fallback/error text of `Invalid Spell Name/ID/Link` and sets the WA icon to the question mark, `?`.

When creating the same WA but setting the Icon Source via the Display tab, `Icon Source: Dynamic Information -> Fallback Icon: Sharpen Blade`, it then turns the icon into a green box. This result happens for any combination of `Icon Source` and `Fallback Icon` values be it the skill name, icon name, and the skill id.

As a sanity check I tried using a skill name that works, `Rallying Cry`, and everything above works as expected with this PvE skill.
I've tried this with two PvP skills, Sharpen Blade, and Disarm, and both seem to have the same behavior as the bug described above.

**Do you have an error log of what happened?**

No

### To Reproduce

1. Open WA UI in game `/wa`
2. Create a new WA
3. Click `Trigger` tab
4. Set Trigger to `Type: Status -> Status: Cooldown Progress (Spell) -> Spell: Sharpen Blade -> Show: Always`

**Screenshots**

![SharpenBladeWaBug](https://user-images.githubusercontent.com/29239201/103160376-5918be80-47a2-11eb-8373-c855cf20c42d.gif)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

Weak Auras 3.1.4

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

N/A

**Comment by mrbuds** [comment]
If you check the "exact spell match" toggle and type spell id it should work

**Comment by bbenefield89** [comment]
That worked, thank you
