### ISSUE TITLE
tooltips run off screen when auras attached to nameplate

### ISSUE THREAD

**Issue by tidehunter1** [WeakAuras/WeakAuras2#2846]
## Describe the bug

Occasionally during gameplay the tooltips on the character window/bags/anything with a tooltip go off-screen. Reloading the UI with /rl temporarily corrects this.
I believe this is caused by attaching buffs/debuffs to the nameplate
 **the issue seems to be related to the "show tooltip" option on the Weak Aura group**
Do you have an error log of what happened?

no errors

### To Reproduce
install this weakaura from this user
https://wago.io/LPp9kaUda
appears theres no custom code involved

1. Play the game normally
2. Eventually tooltips such as items will run off the screen

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

weakauras was the only addon loaded and only 1 weakaura was loaded for testing purposes

**Which version of WeakAuras are you using?**

Version: 3.1.4
**Are you on World of Warcraft Classic or Retail?**

Using Retail

**EDIT**
User of above WA "BigDebuff_Nameplates" made a workaround by disabling tooltips on icons,

**Comment by InfusOnWoW** [comment]
I cannot reproduce this with version 1.0.2 of the linked aura. 
Can you provide either:
a) A better description on how to reproduce it?
or
b) A video showing the effect.

**Comment by nullKomplex** [comment]
https://cdn-cf-east.streamable.com/video/mp4/ze88u5.mp4?Expires=1609868400&Signature=ZPK-o21dIoZgPAtLSwzH0qqMBXfcBZoz4x2I94Rttq0jTAPA9HTYEaYz9rjN5oUmqEXFYxXpOUlOWYieHk94NajAAyANlqtphMj-vLkmfq3DLPnOvLS1d1xVhkOemyAH9S0Ii~HEHd2EOjPnp-N9dM5BWQze7ztzIKq2oZ69rOJz-CC2kZnXGqsAiZezh8SgT5YINbVaFSI2LNDjVCS6VUblglvucIvjdzfQTXrZ8bxFM6hDPf1Q5v9YrWCK2nC4C2YgIQwldEepaeToSTgK9CUbAxF3EByCCHb5TkXJD-Aa3jTxG18gaUyZXBeFnrKUPnxzYo2cYHynL8OyHPsGRA__&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ

**Comment by nullKomplex** [comment]
```
!WA:2!Dr1tVTTnu8A4numnG1gVUI1HDWOdBhYHHIuSEy3SCSBYGJTRKYs6Uytl9KjxLj1iPSJZT6t9S(iOZ7K)iKd7SGXW(a0pc5tWEKsoRD(a97pK8973J)EQr)wlAf1k6DFxbluW9fzYq4BVN8QrXXkq3qUU2ylHhsfYXcgxpRBVHb982fkejrIvC)vSuy6n7D7fnhOssOMj4Qx4P0eP2XLXzANzX4FkQZgTKnFoivFXpiRn)RcfvSQBIGdQPU61PGhjtsok3SYjla13KEGpLGvO9fcz0p3EmHXLy9gXtwp1dwciYobijA67vzZS(JLqm7kp)X9gmyJkfssons5CxA)Sym92jD74hmXpOJxGmtbdXIn1Zwsh3me25g70eIgkIGz4zcq0jpPJ3z9pFqEgVMboPhyi9siOY)mre8N37wSHbsoj5xr6IDKxD7BaiTdcMqThb7r0CfKeBBSLFkwafrJmwd0ceMEWCtx8W39O0wA4k9eLTdCz9Rs6tSbTlXc5ccUHAdxo2jZVl9t)Ev6d)GBORiri)LgnA089vr3Jb3oNhmk9lTbjzAbEvSWlyrAQBh092QAXUcISbF7UkHXRRr0n28)EMsZIxJ8rk0ixcWGUdhnSx5dKiRm7PWUXqlmAI)YRjbxN(W(s21TFvgjc7dK2bbFe33xPD2yRqPWfss6MlQnQaWsMInlbMwZ5pq8MEWPdh2ZBI7OGGrN5D6lpjy3DL2NDn8KAgD5hvhtw7Z(OZdgC6WE)ZU5jIv9LWFKb8W1J)KN9Jh9tvSZKyRzz)nSX4yo8UzzATGpAjitiRlmHha85A6xz3)EMLBC6ExN5gut(Y9rOUMKu7w8djjqtlqcOSW3GtoQM2mdyO9b2c4I9fqsNrb2CQ(TUjcsuFxfs0h7TilrZCCnAXhxEUJxycrPmwZ04nZ1gZcPvcAGVR5te7qrb2DgLAhVDkqWfGd(Aw60n7)canNWzgHJG)IYpRF5dkp8gGOaFT0s37VlYiXX0tmd6sfGxCKAJzpMcvEO7cC42EWYj3VCAjPCgA(5))iUxlelA4rssPKMfAr4YQHSVUXK8NYI8gcRA)CV)tKTnwIJYimqDvZBREN7BczQA(WoN1B8Gob9MHWjMn35Omw02l9pEo75DFT8yCoNBkaqtF0EQAu2hZueuSfr9wzhjkmSHv1F2Y4vZJONt5VnTL6OJHLTw(3x(Vd```
All recreation steps are shown in video, but if you import this, apply SW:P, mouse over the aura, and then check any tooltip that is too large it will no longer clamp to screen.

**Comment by tidehunter1** [comment]
@nullKomplex gj following up for us, this is more guaranteed to reproduce than anything I had, i was going to leave it and hope someone else picked it up
