### ISSUE TITLE
"Grow" option should be preserved when updating a dynamic group with "size and position" unchecked

### ISSUE THREAD

**Issue by cremor** [WeakAuras/WeakAuras2#2847]
## Describe the bug
When I update an aura from wago.io that is a dynamic group, and I uncheck the "size and position" option for the update, then the "grow" direction of the dynamic group should also stay, but it is overwritten.

**Do you have an error log of what happened?**
No error

### To Reproduce
1. Install https://wago.io/slraid1
2. Change the grow direction of the group to "left"
3. Update the aura (doesn't matter if via the companion app or by manually importing)
4. During the update, uncheck the "size and position" option
5. Notice that the grow direction is reset to "right"

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, I didn't test that. But I doubt another addon would have an effect on this small part of an aura update.
Also, I don't use ElvUI or some other "all in one" addon.

**Which version of WeakAuras are you using?**
3.1.4

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I'm not sure, but I don't think that it worked previously.

**Comment by emptyrivers** [comment]
This is working as intended, the grow option is classified under "Group Arrangement" and not "Size & Position".
