### ISSUE TITLE
V. 3.1.5  Installs from the Hub as classic

### ISSUE THREAD

**Issue by sabanim** [WeakAuras/WeakAuras2#2854]
Just updated using both Overwolf and Wowup.io.  No minimap icon but /weakauras shows install but prints "this version is for classic"   Changed source in Wowup.io to wowinterface and it install correctly.   Thanks for all the hard work, love the addon

**Comment by Stanzilla** [comment]
That's not a WeakAuras issue, should report that to Wowup
