### ISSUE TITLE
'Grow' Option changes when updating aura from wago.

### ISSUE THREAD

**Issue by krazyito65** [WeakAuras/WeakAuras2#2857]
## Describe the bug
When updating an aura via wago, the grow option reverts, even when 'size and position' are checked.

### To Reproduce
1. Install old version of https://wago.io/slraid1/
2. Change Grow direction under groups to 'Left'
3. Update aura, which unchecking 'size and position', to newest version
4. aura should now be growing right.

**Which version of WeakAuras are you using?**
3.1.5

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Unknown, I doubt it.

**Comment by mrbuds** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/2847
