### ISSUE TITLE
Conditions. Default colour is black.

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#286]
_What steps will reproduce the problem?_
New icon aura. 
Conditions - IF trigger 1 - Active = true THEN...
Click Color and use the colour Picker. It defaults to black rather than white. 

_What is the expected output? What do you see instead?_
Would expect white and full opacity. 
Defaults to Black and full opacity. 
Not a big problem in most cases where someone is changing the colour but when people are using it to control the alpha it trips them up very often.

**Comment by InfusOnWoW** [comment]
Should be fixed in the next release.
