### ISSUE TITLE
Certain wa not displaying and now getting error 

### ISSUE THREAD

**Issue by blackjack1031** [WeakAuras/WeakAuras2#2867]
Message: Interface\AddOns\WeakAuras\Prototypes.lua:7947: invalid option in `format'
Time: Sun Jan  3 23:17:32 2021
Count: 1
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:7947: invalid option in `format'
[string "=[C]"]: ?
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\WeakAuras\Prototypes.lua"]:7947: in function <Interface\AddOns\WeakAuras\Prototypes.lua:7921>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4097: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4075>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4270: in function `ReplacePlaceHolders'
[string "@Interface\AddOns\WeakAuras\SubRegionTypes\SubText.lua"]:275: in function `?'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:34: in function `Notify'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3840: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3837>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3927: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3894>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4010: in function `UpdatedTriggerState'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:817: in function `ScanWithFakeEvent'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:1089: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1658: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1482: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1359>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1514: in function `ScanForLoads'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1564: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1562>

**Comment by mrbuds** [comment]
You ignore the issue template and i don't have enough information to help you, please open a new ticket

**Comment by mrbuds** [comment]
I check for last release & alpha, there is no call to format at Prototypes.lua:7947
