### ISSUE TITLE
nil value in generic trigger

### ISSUE THREAD

**Issue by Rottenbeer** [WeakAuras/WeakAuras2#2869]
## Describe the bug
I get the following error in multiple weak auras I have installed when using the teleporter in oribos:

```plaintext
1x [string "--[==[ Error in 'Inscrutable Quantum Device..."]:18: attempt to perform arithmetic on field 'startTime' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:589: in function <WeakAuras\GenericTrigger.lua:534>
[string "@WeakAuras\GenericTrigger.lua"]:730: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:691: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:837: in function <WeakAuras\GenericTrigger.lua:822>
```

I'm using WeakAuras 3.1.6

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Comment by InfusOnWoW** [comment]
That's a already fixed for the next release.

**Comment by Rottenbeer** [comment]
Very nice! Can I get the beta release or so? Thanks for the fast answer!

**Comment by InfusOnWoW** [comment]
yes, how you do that depends on what method you use to update your addons. All of them should offer alpha/beta releases.
