### ISSUE TITLE
Using %c and custom replacement in Actions Chat Messages fails to replace the placeholder.

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#287]
_What steps will reproduce the problem?_
Any trigger
Actions - On Show 
Chat Message - say - "testing %c"
`function() return "test" end`

_What is the expected output? What do you see instead?_
Expected "testing test"
See "testing %c" 

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
No.
What version of WeakAuras are you using?
2.4.22
Was it working in a previous version? If yes, which was the last good one?
It hasn't worked as long as I've been aware of it. Several versions. 

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
No errors

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by InfusOnWoW** [comment]
Should be already fixed.
