### ISSUE TITLE
WeakAura BUG

### ISSUE THREAD

**Issue by Lynxzes** [WeakAuras/WeakAuras2#2873]
## Describe the bug

Clicking portal in ring of fates (ORIBOS) to get to the higher layer (transportation layer) triggers the error.
Also in Mythic+ keystone runs it triggers on certain event of bosses abilities.

**Do you have an error log of what happened?**

**Error 1:**

Message: [string "--[==[ Error in 'Effects - Group' ]==] retu..."]:18: attempt to perform arithmetic on field 'startTime' (a nil value)
Time: Wed Jan  6 11:00:17 2021
Count: 1
Stack: [string "--[==[ Error in 'Effects - Group' ]==] retu..."]:18: attempt to perform arithmetic on field 'startTime' (a nil value)
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:691: in function `ScanEvents'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:837: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:822>

Locals: <none

**Error 2 :**

Message: [string "--[==[ Error in 'Effects - Group' ]==] retu..."]:18: attempt to perform arithmetic on field 'startTime' (a nil value)
Time: Wed Jan  6 11:01:15 2021
Count: 1
Stack: [string "--[==[ Error in 'Effects - Group' ]==] retu..."]:18: attempt to perform arithmetic on field 'startTime' (a nil value)

Locals: <none>

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Clicking on the portal to go between layer 1 and 2 in ORIBOS triggers it every time.**

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**No. Not tried that.**

**Which version of WeakAuras are you using?**

**3.1.6**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**YES**. Version before 3.1.6

**Comment by InfusOnWoW** [comment]
That should be already fixed for the next release.
