### ISSUE TITLE
Message contains exactly throwing error

### ISSUE THREAD

**Issue by Prejudice182** [WeakAuras/WeakAuras2#2876]
## Message contains exactly

**Do you have an error log of what happened?**

```plaintext
[string "--[==[ Error in 'Whisper Test' ]==] return function(state, even..."]:10: unexpected symbol near '%' 
```

### To Reproduce

1. Set trigger to Event -> Chat Message  
2. Set the message type to any field
3. Set message operator to "Is Exactly"

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

v3.1.7

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by j-dav** [comment]
I have the same issue too, message trigger WA's are returning errors

**Comment by mrbuds** [comment]
Can you link an export of one of those auras?

**Comment by Prejudice182** [comment]
> 
> 
> Can you link an export of one of those auras?

https://pastebin.com/LCu9tPFx

**Comment by Prejudice182** [comment]
Thanks for the quick fix! I tried to dig into the code myself to find where and what was going wrong, but I was helpless.
