### ISSUE TITLE
Conflict with Elvui

### ISSUE THREAD

**Issue by Roktaal** [WeakAuras/WeakAuras2#2880]
## Describe the bug

Versions 3.1.7 and 3.1.8 mess up Elvui options window by covering left part, with various options, with slightly transparent black area. Version 3.1.6 works fine

**Do you have an error log of what happened?**

No lua errors

### To Reproduce

-

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Tested with only WeakAuras disabled and everything works fine. When I enable WeakAuras the bug appears

**Which version of WeakAuras are you using?**

3.1.7 and 3.1.8

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes, 3.1.6

**Comment by mrbuds** [comment]
If you can add a screenshot that would help understand what is your problem

**Comment by SpatenLa** [comment]
its a elvui bug. its fixed in the next elvui release.
