### ISSUE TITLE
Anchor to Boss Frame failing

### ISSUE THREAD

**Issue by Saxayone** [WeakAuras/WeakAuras2#2881]
## Describe the bug
Found a really odd potential bug, made 3 different wa's for attaching a debuff to boss frame (because thought it wasn't working w/ previous methods)
1. aura>boss> debuff> name > auto-clone + combine (display, anchor to center>center of Unit Frames)
2. Same as above in dynamic group pretty much
3. dynamic group but with 5 individual boss1, boss2 etc unit.
The issue I have is that randomly they never show/work.
I used Taloc in Uldir who starts with debuff "Damaged" + he's easy to access/doesn't die easily.

From what I can gather from my testing, when I start an encounter with any trinket that deals direct damage (Dreadfire Vessel or Grim Codex) it seems to cause nothing to attach to boss frames, even if it triggers/applies much later in the fight. (made a different separate wa to just track my own debuffs for testing that last part)
or
Secondary method:
Door of Shadows (non disorientation soulbind) onto the boss and it causes the same issue but seems less consistent. (sometimes it forces non-anchor, other times it just works as normal)

**Do you have an error log of what happened?**
No logs.

### To Reproduce
1. Create any aura on unit "Boss" > clone matches or Specific Unit "Boss1".
2. Start encounter with trinket that deals direct damage only. (or door of shadows onto boss)
3. Activate trigger for aura, it should be showing but will not.

**Screenshots**
None

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I disabled all addons except wa and removed all wa's except the one to anchor to boss frames (dif methods)
Nothing ever attached to Blizzard Boss frame (don't know if just a me issue.)
Described behaviour occurred with only:
WA + ShadowedUnitFrames
WA + ElvUI
WA + PitBull

**Which version of WeakAuras are you using?**
3.1.8

**Are you on World of Warcraft Classic or Retail?**
- [ x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Attaching to Boss Frames have always been inconsistent for me (tried to make one that attached goop debuff on boss in mechagon but it was always inconsistent.)

### Additional Info
Potentially unrelated, never had something attach to boss frame if boss is added during encounter, see Huntsman Altimor/Beastmaster Darmac.

**Comment by mrbuds** [comment]
Please include exports of these auras

**Comment by Saxayone** [comment]
All the different methods I used for testing it:
Non-Grouped - anchored to unit frame - Aura - Debuff - unit Boss - Auto clone - combine matches - offsetx -100 :
https://wago.io/Z5iCqj2f_ - Damaged(on Taloc from start)
https://wago.io/TdKkF86Jl - Blood Plague (applied by my dk)

Dynamic group - group anchored to unit frame, contains 1 wa with:
Aura - Debuff - unit Boss - Auto clone - combine matches - offsety +100 :
https://wago.io/dpTxAZDAE - Damaged(on Taloc from start)
https://wago.io/xOEy7NYOT - Blood Plague (applied by my dk)


Dynamic group - group anchored to unit frame, contains 5 wa with:
Aura - Debuff - specific unit; boss1, boss2 etc - offsety -100 :
https://wago.io/ZPxguD7jY - Damaged(on Taloc from start)
https://wago.io/H7zhDutIa - Blood Plague (applied by my dk)

**Comment by mrbuds** [comment]
https://github.com/mrbuds/LibGetFrame/commit/92782ffb5be341bd296b7fe4fed9364c48ea2c05 should help with that
