### ISSUE TITLE
WeakAuras and ElvUI new issue

### ISSUE THREAD

**Issue by mbarbone1369** [WeakAuras/WeakAuras2#2882]
Hello,
I have ElvUI 12.14 running, and just updated WeakAuras to 3.1.8.
When I open the ElvUI interface panel, the side buttons have disappeared.
Prior to the 3.1.8 version, the ElvUI buttons were displayed. 
I tested, have only the 2 Addons running, no buttons. I disable WA, buttons.

![Screenshot 2021-01-09 120805](https://user-images.githubusercontent.com/47456996/104104015-6c805b00-5273-11eb-88e4-b91ae3349b7d.png)

**Comment by InfusOnWoW** [comment]
Your elvui is out of date.
