### ISSUE TITLE
Memory Consumption Increase Over Time , starting from 11.82mb

### ISSUE THREAD

**Issue by ze3rax** [WeakAuras/WeakAuras2#2885]
## Describe the bug
The addon slowly takes over resources with no interactions (staying still and watching the graph)

**Do you have an error log of what happened?**
There are no error logs, as far as my knowledge extends for such things.

### To Reproduce
No clicking, no anything, just updated the WeakAuras as usual.

Stay still, watch the garbage growing up.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, still gave garbage building up.

**Which version of WeakAuras are you using?**
3.1.8

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Followed the URL -> Module Disabled
We're sorry, but this module is currently disabled. Please contact a site admin if this has been done in error. Support

### Additional Info

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5792553/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
That's not a issue. Lua is a garbage collecting language.
