### ISSUE TITLE
Tigger with unit  (ie: smart group, nameplate...) do not register their information unless they are the dynamic information provider

### ISSUE THREAD

**Issue by supergeoff** [WeakAuras/WeakAuras2#2888]
## Describe the bug
Any aura relying on a trigger with unit field that make the aura use clones (ie: Smart group, Nameplate...) does not register its information to be use in other tabs (ie: Conditions) unless it is the trigger providing the dynamic information.
It does not register the overall active state of the trigger.

### To Reproduce
https://wago.io/ZeNlLFcpI

In order to have glow affected in conditions you need either:

- Set trigger 2 as dynamic information provider
- Set unit to something that does not rely on clones (target)

**Which version of WeakAuras are you using?**
3.1.8
**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Comment by InfusOnWoW** [comment]
That works as designed, the clone ids have to match for conditions.
