### ISSUE TITLE
New Load Settings for Instance Size Type / Instance Type - Suggestion to change

### ISSUE THREAD

**Issue by Naiyia** [WeakAuras/WeakAuras2#2890]
Since Torghast being introduced, it's been added to the addon under Load Settings for "Instance Type" and playing around with Load Settings I've realized that I have WAs I use specifically for Arenas, Dungeons, and Torghast _only_. Although, I can't select it from both, as it has to be one or the other. So I can do Arenas and Dungeons only, or Torghast only, or just unload the type and use it universally which gets very spammy for some of my WAs I just don't want to show outside of an instance.

See screenshot below for what I'm talking about with it not being able to load both, it's either/or:
![unknown](https://user-images.githubusercontent.com/28378328/104604170-cc477f00-5642-11eb-8110-6cccc06fd34c.png)

I very briefly discussed with Asakawa who said it's not going to load for both, as it's a new feature since Torghast came out, and to reference the following link and open a ticket regarding this: [Difficulty ID](https://wow.gamepedia.com/DifficultyID)

I wanted to re-organize these to make it seem more easier, by type, and then by size, hoping that this might help make it more clear to others and also settle my OCD. It makes it easier to either select an actual type, or sort it by size if you're picky. Currently, the types are under size, and the sizes are under type so I just kind of cleaned some of it up.

Please see the screenshot of my suggestion:
![Instance Types   Sizes](https://user-images.githubusercontent.com/28378328/104605460-285ed300-5644-11eb-9df1-be87629f5bb2.jpg)

If you'd like to contact me, I can be reached at Abbygale#11988 on bnet, or Abby#7395 on Discord. Please note that I do not accept friend requests on Discord without knowing you, but you can message me first. <3

**Comment by InfusOnWoW** [comment]
That's not how the game organises the instance types/sizes and thus won't work.

**Comment by InfusOnWoW** [comment]
I should maybe expand a bit on that.

The two load options are a somewhat curious development, but in essence:

* Instance Size Type is based on what Blizzard thinks are the various instance difficulty types.
That leads to somewhat strange things, e.g. why there are 4 of them for Path of Ascension.
This list will automatically update whenever Blizzard adds a new entry to the system.

The *Instance Type* is a manually maintained mapping of various outputs to what WA considers the main types of instance types. Torgast, Warfronts and Visions nor Path qualify as major types as they are only for this expansion.
