### ISSUE TITLE
Monster Say trigger is not working with some strings

### ISSUE THREAD

**Issue by jrowles** [WeakAuras/WeakAuras2#2891]
## Describe the bug
The Monster Say trigger is not firing when comparing against some strings.

**Do you have an error log of what happened?**
No error is being thrown.

### To Reproduce
1. Create a WA with a Monster Say trigger that contains any of text from the known bad strings.
2. Go to the Limbo world quest in Bastion and hope the NPC you need is active that day.

Result:  WA is not triggered.

**Non-Working Strings:**
- My Explodinator 5000 just, uh, explodinated the dam above my lab! All of my experiments--I mean dear sweet pets--are in grave danger!

**Working Strings:**
- Mmm! I haven't felt the sting of a blade like that in a while.
- The Lich King calls to me. I must serve him once more!
- Invaders threaten the Firelands! I must return to my kin at once!
- I have been at this crossroads countless times. I wish to be bound no longer! Grant me the peace of death!
- Battle rages in my city. I must return to protect the little ones before the beasts reach them!
- Woof! Bark! Bark! Bark! Grrrr...

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
N/A

**Which version of WeakAuras are you using?**
3.1.8

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

https://wago.io/x4fYEqEYE

**Comment by InfusOnWoW** [comment]
Much smaller example:
!WA:2!DrvZUTTrq4iOw0cMIcB10GgGEW1aPPUaPO1an3fvOsSJSKcjDTl6p0ljhkUXu7YU7sjlFl6uoRhbDUN0JGEciekYdqEe8tqNDjLBs1bHzNz2z((M9ByJUTg3kUv8B2FjnIZ84fIi4RVZgsHkLlgKROCM0smBqsIeunwryrO)HCktf2XPVVJ7MioplMpL5nLMdxSE7rN4rqQTUOxmxjOJgbc5N)TIAZ3ARMLdUWeGPENSi0y4vKKqVAvqN2E(bE(TD9NhxiiAm06Nk)S1DsjQ9obKsYiWUGrvH5zKzGqmUYxOsjF8J)grbZuoxfDmepxMdzzhflTCzemrRvfsiO(gxCBVhkaS3UEdD61lFN6Wb8Ca7pxSmHYI)Uh9q5JoyzmeI40hHV45o9g290Elky10YkFxsKIob8RoFcpg(77CdoTabJK9l4majZlV5saYBJals5QPx6cjKLyMQLFm2ajrP5nKUeHNlms)i89V5E5TuWvQazkbhWNx)KK)aJtZFjCXycMqTHnJZGf3gE)hkZ359QqhEgxCCJgnA(UkVBXGD7t9hK)fgNOqGJLIgDgnwLA3gpEtvVOxbXgNVEtLQ4xRr0At8xviv0KziFeCfYfF0PD)b9DkVRazLoNLMeJmWOj(BrnjyQ8D6kOxV3lliX4CGSNV)hW9TDAJX3uUi(mbjF(z1gvaycvsdZGlQ587PCZ39O(9DCdSh47p4e3JE2Z93CBR9OxdpOMrN)b9rh18Sp4u)Eh135TBgLXN2va)vbWIMn8J(XF4WFUID6aR0)TTcZ1h0xEtyHsXzdMacu7Uu7UhWgPs)st(Bz2c9Ho3ozwJA2NT1tQToyQP7(P0OlzOATP5gErKmOYShfDVRPb24CbePHPaDuQ612zCsC3qfMktDF3XfzkQLTwnE)sFl3OmIuQTSL4OqBSuyKGA4x(P53B7gU(f9PujbhYXPlim6yZQ6tCLkIq1DnqKGNsyy3NuE3Yd2SDBoqV8lKa(XHy5CDEMAFG9ycL1T83nzx(hL)zzq5bH4UhvM()DVIYQu5y9SSVMZh3qO39WvLNu(BwLelB8EkRLkE0KQ9UVQrWI9PXh2hM6(FQUvjc87ciqrHwt3PgfT4Q63HqeIj0rwcktxei9WcA8QJpM)IxrZEXLYo3uPu6QRHMeHEDCDC6VutnA1xpNVDGL6sYYtjnBjp8PWKwt(NZ)3d
