### ISSUE TITLE
Cant Import or delete wa

### ISSUE THREAD

**Issue by Andjelo** [WeakAuras/WeakAuras2#2892]
Hello
Cant import wa from wago, import string all good, but after reload ui see only name, there is no child inside aura, no config, just name. when deleting when i press delete button aura dissaper from list but promt window to delete still on screen
Seems it can import whole group or delete whole group. Used addon buggraber here is the link for errors https://pastebin.com/DdAviqVB
1 try to import wa last step after pressing install button in small promt window
2 try to delete whole group 
3 same as 1 after reload ui
all addons disable only WA and buggraber is ON
Thx

**Comment by InfusOnWoW** [comment]
We need your settings to investigate this further.
The issue template asked you several questions, which you choose to ignore and thus you are best opening a new ticket and actually answering the questions there.
