### ISSUE TITLE
Unexpected symbol in WeakAuras.lua file

### ISSUE THREAD

**Issue by LukaszGretka** [WeakAuras/WeakAuras2#2894]
## Describe the bug

Hello, after log in, I received an error, which say "WeakAuras.lua:84901: unexpected symbol". Yesterday I had some power issues while closing system (Windows 10).

It's looks like new WeakAuras.lua file was generated, and overide all my existing auras (sigh). My suggestion here is to change logic which is responsible for generatin new or at least give the user any possibility to affect on that action. If so, more advanced user can change file manualy, without clearing everything out automaticlly.

**Do you have an error log of what happened?**

Logs from FrameXML.log file:

```plaintext
> 1/21 17:32:41.558  Loading add-on WeakAuras
> 1/21 17:32:41.558  WTF\Account\<account_name>\SavedVariables\WeakAuras.lua:84901: unexpected symbol
```

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

I don't use any other UI packs

**Which version of WeakAuras are you using?**

3.1.8

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Comment by InfusOnWoW** [comment]
You WeakAuras.lua file was apparently broken by whatever computer issues you had. There's usually a .bak file next to it, which might work. 

Otherwise you need to restore from a backup.

This isn't a WeakAuras issue.
