### ISSUE TITLE
账号名称显示乱码

### ISSUE THREAD

**Issue by SaintSilent** [WeakAuras/WeakAuras2#2895]
在使用该wa更新器时，账号名称处显示均为乱码

**Comment by mrbuds** [comment]
google translator tell me it's not an issue with weakauras addon

**Comment by mrbuds** [comment]
I invite you to open a more detailed ticket at https://github.com/WeakAuras/WeakAuras-Companion/issues in english if possible, with a screenshot showing what you mean and steps to reproduce your problem
