### ISSUE TITLE
Health Bar Color Bug

### ISSUE THREAD

**Issue by Fing10** [WeakAuras/WeakAuras2#2896]
## Describe the bug

I duplicated mana bar as fire mage to make into health bar and after setting the color of the duplicated one to green it was still blue.
**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes it worked in a previous version

**Comment by InfusOnWoW** [comment]
This does sound like a user error.

Since you failed to actually provide the aura, nor have detailed the steps to reproduce, there's nothing we can investigate.
