### ISSUE TITLE
Error when clicking the Weakaura frame title bar to move the options panel after opening a large weakaura group

### ISSUE THREAD

**Issue by CMcFadyen** [WeakAuras/WeakAuras2#2897]
After clicking the Castle Nathria weakauras to change its settings, the Weakauras options pane was covering the auras, so I tried to move it and got the following error:

2x ...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:237: attempt to perform arithmetic on a nil value
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:237: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:236>
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:264: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:262>

Locals:
(*temporary) = nil
(*temporary) = 2100.512939
(*temporary) = 2100.512939
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on a nil value"
frame = WeakAurasOptions {
 0 = <userdata>
 texturePicker = <table> {
 }
 HideTip = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:513
 CenterOnPicked = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1246
 window = "default"
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 ClearOptions = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:830
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
 EnsureOptions = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:895
 PickDisplayMultiple = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1262
 RightEdge = <unnamed> {
 }
 importexport = <table> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 importThumbnail = <unnamed> {
 }
 ShowTip = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:506
 ClearPick = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:979
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 TopRightCorner = <unnamed> {
 }
 iconPicker = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 UpdateFrameVisible = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:275
 TopEdge = <unnamed> {
 }
 mover = <unnamed> {
 }
 bottomLeftResizer = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 unloadedButton = <table> {
 }
 buttonsContainer = <table> {
 }
 tipFrame = <table> {
 }
 toolbarContainer = <table> {
 }
 codereview = <table> {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
 container = <table> {
 }
 loadProgress = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 texteditor = <table> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
 backdropInfo = <table> {
 }
 moversizer = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
 pickedDisplay = "Castle Nathria (wago.io/slraid1)"
 PickDisplay = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1189
 loadProgressNum = 627
 tipFrameIsVisible = true
 SetLoadProgressVisible = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:635
 FillOptions = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:924
 addonsButton = <table> {
 }
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
 loadProgessVisible = false
 filterInput = WeakAurasFilterInput {
 }
 GetPickedDisplay = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1305
 buttonsScroll = <table> {
 }
 BottomLeftCorner = <unnamed> {
 }
 PickDisplayBatch = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1286
 modelPicker = <table> {
 }
 loadedButton = <table> {
 }
 TopLeftCorner = <unnamed> {
 }
 PickOption = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1163
 NewAura = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:1034
 bottomRightResizer = <unnamed> {
 }
 ClearPicks = <function> defined @WeakAurasOptions\OptionsFrames\OptionsFrame.lua:998
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 UpdateOptions

**Comment by InfusOnWoW** [comment]
You need to answer the questions in the template.
