### ISSUE TITLE
Implement a "Not Zone Name", "Not Zone ID", "Not Encounter ID(s)" feature

### ISSUE THREAD

**Issue by NaR00W** [WeakAuras/WeakAuras2#2898]
**Is your feature request related to a problem? Please describe.**
If I want an aura to run on everything except for one specific fight, then it's tedious to do so. For instance, having to use Focus Frames to heal Sun King but generally having an aura for focus frames in all other instances. 

**Describe the solution you'd like**
Akin to first 7 check boxes when I click the checkbox a second time I want it to change from "Encounter ID(s)" to "Not Encounter ID(s)". 

**Describe alternatives you've considered**
Whitelist every single Encounter ID that isn't this one.

**Additional context**

**Comment by InfusOnWoW** [comment]
That sounds like your auras are incorrectly setup and you are looking for a work-around.

And as such, this sounds too niche.

**Comment by NaR00W** [comment]
What's the correct way to set up a generic aura that shouldn't run in certain edge cases then?

**Comment by InfusOnWoW** [comment]
This isn't a help forum on how to setup your auras. In any case you didn't actually attach your auras, nor explain what they do, nor what makes them unsuitable for Sub King.

**Comment by NaR00W** [comment]
I understand that it's not a support forum, but I think that your assessment is wrong. So I'd like to hear how you think unloading auras in edge cases should be handled, if not through more powerful load conditions. Given that I'm setting things up incorrectly.  Isn't "not in pet battle" similarly too niche of a load condition to be implemented? 

This is unrelated to Sun King specifically, but Sun King is an example of a fight that is different from many other fights, which would cause a lot of otherwise good basic auras to not be applicable. Almost all healing being funnelled into a non-player: this is an edge case. If you have a WA that highlights low hp targets as a holy priest, so you can GS them quickly, it would make sense to exclude this from Sun King, since that is reserved for KT. 

Any type of WA "game assistance"-logic tied to how you ought to play your class generally, that changes due to edge case circumstances on certain encounters, doesn't seem like an incorrectly setup situation to me. But rather a scenario you can't setup correctly, given the current load condition design limitations. But maybe I'm wrong.

**Comment by InfusOnWoW** [comment]
None of what you write convinces me that this is a common enough problem.

The "Not in Pet Battle" load option probably has a 1000x more use cases than all 3 load options you proposed.

**Comment by NaR00W** [comment]
I'm not trying to convince you that it's a common problem. If you said that you don't want to do it, since you don't see any value in it, then that's fair enough. 
However, you said the solution was just not doing things wrong. Which I don't really think is the case. You can't do what I described. It's not things be setup incorrectly. 
 
I have no idea what the most common issues with auras are, obviously. I'm merely requesting what I think is missing.

**Comment by Causese** [comment]
>Isn't "not in pet battle" similarly too niche of a load condition to be implemented?

no, encounterID can be used to check & exclude, whereas "in pet battle" only loads if true

> So I'd like to hear how you think unloading auras in edge cases should be handled

It's probably just not worth for infus to spend dev time on it.
custom coding will always be necessary for niche things since adding a trigger / load conditon for each case is not an option. too much bloat

> This is unrelated to Sun King specifically, but Sun King is an example of a fight that is different from many other fights
That's what makes it niche. An inverse for encounter ID that the majority of users will probably never figure out / need.
You need to get into custom coding. If not this time, at some point you will reach a dead end.
