### ISSUE TITLE
custom activation function bug

### ISSUE THREAD

**Issue by Seigerzz** [WeakAuras/WeakAuras2#2899]
## Describe the bug
If you make a weakaura with a custom activation function and none of the individual triggers fire, weakauras assumes the custom activation function will return false.

**Do you have an error log of what happened?**
no

### To Reproduce
I have the following weakaura:

[https://wago.io/Nr-yJikco](https://wago.io/Nr-yJikco)

log on with the above weakaura active.  It won't fire.  But if you negate the custom activation function and flip the inequality in the trigger, it does fire.  If you add multiple triggers to the weakaura, the custom activation function will only work correctly if at least one of the triggers is true.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of WeakAuras are you using?**
3.1.8

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I don't know

**Comment by asaka-wa** [comment]
A dev can tell you whether this is something they'd consider in need of fixing but from my point of view I'll say that a status trigger that has never been true will have a value of nil and the activation function will not fire. Once the trigger has been true it will go through activation as expected each time it changes state from then on. The method I usually suggest to people when they want to invert a single Status trigger like this is to add a trigger for [status - conditions - always active], which will ensure the activation is run immediately.

**Comment by InfusOnWoW** [comment]
That is technically a bug, but that's not going to be changed, as that requires to far reaching changes for a case that's easily worked around.
