### ISSUE TITLE
Weakaura Checker (without Exorsus Raid Tools)

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#290]
With AddOn "Exorsus Raid Tools" it is possible to check a installed Weakaura for the whole raid (ie. User A does not have Weakaura B installed). Would it be possible to hand that information (I dont know how ERT does that) to ERT without having ERT especially installed?

So this

ERT <magic> WA "Foo" is installed

becomes

WA <says to ERT WA "Foo" is installed> <magic> ERT

**Comment by emptyrivers** [comment]
Exorsus Raid tools simply searches through the SavedVariables of WeakAuras and communicates the display name of each found aura. I'm not sure what "hand that information to ERT...without having [it] installed" means in this context, but if you're looking to access the information that ERT uses independently, just iterate through `WeakAurasSaved.displays`.

**Comment by pquerner** [comment]
So you mean ERT iterates locally through your saved WAs, saved them to a database inside of ERT, and then the Raidleader gets the "database" of each member and an algorithm finds matches and mismatches?

Can Weakaura then not simply "send" a database itself IF ERT requests it? (So only the Raidleader needs ERT installed, while all others do not)

**Comment by emptyrivers** [comment]
That is possible, sure. But then, why even install ExRT? Just have a custom aura that, on an appropriate `CHAT_MSG_ADDON` event, iterates through the savedvariables directly and communicates what it finds.

**Comment by pquerner** [comment]
True. Are you aware of some Aura which already does that?

**Comment by InfusOnWoW** [comment]
I think this would be out of scope and undesirable for many users.

**Comment by norecha** [comment]
why would it be undesirable? dbm has it(/dbm version), I wish WA had /wa version command as well. it is really helpful for the raid leader to be able to tell if someone is lying

**Comment by emptyrivers** [comment]
Personally, I find this kind of nannying to be hugely annoying.

It could also be trivially faked, no matter how hard we tried to implement it.
