### ISSUE TITLE
[classic] additional convenience triggers in Load tab.

### ISSUE THREAD

**Issue by pmb123** [WeakAuras/WeakAuras2#2901]
**Is your feature request related to a problem? Please describe.**
I hide many of my auras when in a city, and many of them are irrelevant when dead.

**Describe the solution you'd like**
Just as on taxi was added to the load tab, I would like to see alive and resting options in the load tab.

**Describe alternatives you've considered**
continue to manually add triggers, sometimes needing a custom trigger where i might not otherwise need one.

**Additional context**

**Comment by InfusOnWoW** [comment]
Alive sounds useful enough.
Rested, though sounds like a very niche one.

The reason we have the "On Taxi" one is because it's essentially the same as the "In Vehicle" for retail. Otherwise we probably would not have bothered adding a On Taxi option.
