### ISSUE TITLE
Request for feature: When to check triggers?

### ISSUE THREAD

**Issue by Ayzkronos** [WeakAuras/WeakAuras2#2905]
There are many weakauras which have custom checks on triggers. for example only check triggers when changing target, or only check when starting a cast etc. i think it would be very sweet if we could more easily setup such things to reduce CPU usage without having to dabble into custom code. something like this?

https://i.gyazo.com/fe80405b96495c160ea97322f227ee10.png
- Constantly (default)
- Changing targets
- Starting a cast
- Once per 0.5 seconds
- Once per 1 second
- Once per 3 seconds
- Once when an item is equipped or unequipped
- etc.

**Comment by InfusOnWoW** [comment]
Triggers do that automatically.
