### ISSUE TITLE
Alpha of icon with position anchored to another icon is determined by other icon

### ISSUE THREAD

**Issue by williamcol3** [WeakAuras/WeakAuras2#2906]
## Describe the bug
If two icons (henceforth named Base and Derived) as positioned relative to one another (Derived is relative to base) using the "Anchored To: Select Frame" option, the alpha of Derived is determined by the alpha of Base. This is not the case when the two icons are absolutely positioned.

I expect the behavior to match when the icons are absolutely positioned.

**Do you have an error log of what happened?**
As far as I know, no error log is produced.

### To Reproduce

I created an example WA to illustrate. Base is an icon that goes to 50% alpha when affected by "Food & Drink". Derived is an icon with no triggers. The behavior on my machine is that while eating food, both Base and Derived are at 50% alpha.

1. Load WA from <see comment below>
2. Eat food. Ethereal Pomegranate was used in testing, but any from an innkeeper should work.
3. Observe effect.

**Screenshots**
![image](https://user-images.githubusercontent.com/6266711/106400328-43229d00-63e3-11eb-8af9-ba6b71a1aed4.png)
![image](https://user-images.githubusercontent.com/6266711/106400317-300fcd00-63e3-11eb-8a93-b89e801d82c1.png)
![image](https://user-images.githubusercontent.com/6266711/106400333-5f263e80-63e3-11eb-97fc-16dac1f91229.png)
![image](https://user-images.githubusercontent.com/6266711/106400343-68171000-63e3-11eb-9768-4f049ba302a9.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but it seems unlikely there would be complications.

**Which version of WeakAuras are you using?**

3.1.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Unknown

**Comment by SpatenLa** [comment]
![grafik](https://user-images.githubusercontent.com/39881841/106400381-6c145380-641e-11eb-9667-2a87a35efc6e.png)

**Comment by williamcol3** [comment]
Ah, completely missed that.
