### ISSUE TITLE
error - '<unnamed>:Hide()'.

### ISSUE THREAD

**Issue by woohunter** [WeakAuras/WeakAuras2#2907]
18x [ADDON_ACTION_BLOCKED] 애드온 'WeakAuras' 보호된 함수 호출 '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Hide'
...aceWeakAuras\RegionTypes\RegionPrototype.lua:635: in function <...aceWeakAuras\RegionTypes\RegionPrototype.lua:628>
...aceWeakAuras\RegionTypes\RegionPrototype.lua:698: in function `Collapse'
WeakAuras\WeakAuras-2.15.5.lua:5788: in function `UpdatedTriggerState'
WeakAuras\GenericTrigger.lua:663: in function `ScanEventsInternal'
WeakAuras\GenericTrigger.lua:619: in function `ScanEvents'
WeakAuras\GenericTrigger.lua:752: in function <WeakAuras\GenericTrigger.lua:743>

**Comment by mrbuds** [comment]
This is most probably the result of using clickable auras, can't be sure because you didn't give yours settings as requested.
Don't use clickable auras.

**Comment by woohunter** [comment]
> This is most probably the result of using clickable auras, can't be sure because you didn't give yours settings as requested.
> Don't use clickable auras.

Thank you
