### ISSUE TITLE
Rightclick Dropdown menu not showing up

### ISSUE THREAD

**Issue by GarVishLS** [WeakAuras/WeakAuras2#2908]
## Describe the bug
I expect the Dropdown menu to be showing if i rightclick an aura or a group. This Dropdown menu isn't showing up at all.

**Do you have an error log of what happened?**

```plaintext
80x SharedXML\UIDropDownMenu.lua:952: DropDownList1:SetScale(): Scale must be > 0
[string "=[C]"]: in function `SetScale'
[string "@SharedXML\UIDropDownMenu.lua"]:952: in function <SharedXML\UIDropDownMenu.lua:920>
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleDropDownMenu'
[string "@FrameXML\EasyMenu.lua"]:22: in function `EasyMenu'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:565: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:532>

Locals:
(*temporary) = DropDownList1 {
 0 = <userdata>
 dropdown = WeakAuras_DropDownMenu {
 }
 shouldRefresh = true
 numButtons = 11
 Border = DropDownList1Backdrop {
 }
 maxWidth = 93.733330
}
(*temporary) = 0
```

### To Reproduce
I don't know exactly how to reproduce because i don't know how to fix it. but i can tell you what i did before the bug appeared.

1. Changed UI Scale from 0.71 to 0.53
2. Changed UI Scale back to 0.71

I don't know if this bug appeared while changing to 0.53 or to 0.71.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, bug still is present.

**Which version of WeakAuras are you using?**

3.1.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Bug appeared for the first time for me.

### Additional Info

I reloaded wow, restarted wow, reinstalled WeakAuras and restarted my Computer, nothing helped.

**Comment by InfusOnWoW** [comment]
We need your WeakAuras.lua and WeakAurasOptions.lua from your WTF folder.

**Comment by GarVishLS** [comment]
I just checked and found out than none of the ingame dropdowns were working. I am just "scanning and repairing" wow atm. Maybe it's not an Weakauras Problem at all. Haven't tried without any Addons activated.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5904349/WeakAuras.zip)

**Comment by GarVishLS** [comment]
Scanning and repairing hasn't fixed something. Bug still exists with all Addons disabled.

`Message: Interface\SharedXML\UIDropDownMenu.lua:952: DropDownList1:SetScale(): Scale must be > 0
Time: Mon Feb  1 15:04:13 2021
Count: 3
Stack: Interface\SharedXML\UIDropDownMenu.lua:952: DropDownList1:SetScale(): Scale must be > 0
[string "=[C]"]: in function `SetScale'
[string "@Interface\SharedXML\UIDropDownMenu.lua"]:952: in function `ToggleDropDownMenu'
[string "@Interface\FrameXML\PlayerFrame.lua"]:57: in function `handler'
[string "@Interface\FrameXML\SecureTemplates.lua"]:654: in function `SecureActionButton_OnClick'
[string "@Interface\FrameXML\SecureTemplates.lua"]:694: in function <Interface\FrameXML\SecureTemplates.lua:686>

Locals: (*temporary) = DropDownList1 {
 0 = <userdata>
 dropdown = LFDQueueFrameTypeDropDown {
 }
 shouldRefresh = true
 numButtons = 3
 Border = DropDownList1Backdrop {
 }
 maxWidth = 207.466660
}
(*temporary) = 0
`

**Comment by InfusOnWoW** [comment]
Indeed looking at the code of the UIDropDownMenu this is not a WeakAuras problem.

If you include the output of:
/dump GetCVar("useUIScale")
/dump GetCVar("uiscale")
/dump UIParent:GetScale()

It should be relatively easy to spot the problem.
