### ISSUE TITLE
Progress Bar Add Model doesn't accept "player" attribute

### ISSUE THREAD

**Issue by Uriyel** [WeakAuras/WeakAuras2#2909]
## Describe the bug

Maybe this is more of a feature request, I'm unsure.

Typing "player" in for the model ID when adding a model to the progress bar aura does not show my character.  I can pick from the model browser just fine, but I keyed in player expecting the same behavior as the 3D mode.

My goal was to make a player HP bar that shows my zoomed portrait and clips as my health goes down.  This functions with any model I choose from the browser, but not a quick add of my toon.  Maybe this doesn't have the same code base as a 3D model aura, but it would be amazing if it did.

**Do you have an error log of what happened?**

```plaintext
No errors
```

### To Reproduce

1. Go to Progress Bar
2. Click on Display tab
3. Scroll down to Add Model button
4. type the word player in the model path 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
The model sub element does indeed not use the same code as the model aura.

And this is out of scope of what the sub element is. It was a intentional choice to not support the same features as the model aura.
