### ISSUE TITLE
Inverse Aura triggers - Dynamic info (VERY minor request)

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#291]
Using "inverse" on an aura trigger to trigger when an aura isn't present doesn't carry icon info for the aura. It would help people be able to continue to use dynamic icons on WAs that will continue to show when an aura isn't present if the dynamic info could grab the icon still. 

Ideally it would grab the icon for the version of that spell name that was recently used, but if it just used whatever icon the config defaults to for that spell name that would be fine too in the vast majority of circumstances.

**Comment by InfusOnWoW** [comment]
Should be fixed in the next release.
