### ISSUE TITLE
Cannot get Spell Known Status trigger to work for Condemn

### ISSUE THREAD

**Issue by DeathtoneDesta** [WeakAuras/WeakAuras2#2913]
## Describe the bug
I attempted to use the spell known status trigger to only show my weakaura if my character knows the spell condemn. However, after closing weakaura control panel or selecting another aura, the aura I'm attempting to create disappears. My character knows condemn. I tried with with typing "Condemn" and using multiple Spell IDs for the spell including the one listed in my spell book (3303340

**Do you have an error log of what happened?**
I got no errors for this issue

### To Reproduce
As a warrior of the Venthyr Covenant:
1. Go to 'New Aura'
2. Click on select any type of aura (I recommend 'Icon' for ease of reproduction)
3. Go to 'Trigger' tab
4. Change Trigger 1 to the following information: 
5. Type = Status; Status = Spell Known; Exact Spell Match = Checked; Spell = '330334'
6. See while WA window open that the icon changes to Condemn's icon.
7. Close WA window or select different aura
8. See that Icon disappears even though the character knows the spell.

**Screenshots**
![image](https://user-images.githubusercontent.com/78512098/106821039-0e605100-6642-11eb-8a31-cb8869aeb414.png)
![image](https://user-images.githubusercontent.com/78512098/106821165-44053a00-6642-11eb-9281-8723b5cc9ee3.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.1.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Unsure, this is my first attempt at this trigger status.

### Additional Info
I've tried other spells and they work fine when applying their spell IDs. I hope I'm in the right place to figure this out. I'm sorry if I'm not.

**Comment by InfusOnWoW** [comment]
I did investigate that some months ago. That's a wow bug. 
I don't recall what the right spell id, and setting for Exact Spell Id was though, but there's combination that works.

I think Exact Spell Id needs to be enabled.
