### ISSUE TITLE
Legendaries sharing the same base item not distinguishable in WA Load Settings.

### ISSUE THREAD

**Issue by jwshive** [WeakAuras/WeakAuras2#2917]
## Describe the bug

I have 2 legendary items using the same slot. I'm using the Boneshatter Helm for both [Deeply Rooted Elements](https://www.wowhead.com/spell=336738/deeply-rooted-elements) and [Doom Winds](https://www.wowhead.com/item=183354/memory-of-the-doom-winds)

I have a weakaura that tells me when the Doom Winds effect would be available. I would like to hide that WA when I'm wearing the Deeply Rooted Elements legendary. The legendary name, when equipped, shows as Helm of Deep Elements or Doom Winds, but when I try to use that in the Load > Item Equipped portion of the weak aura, it just defaults to "Boneshatter Helm" and the weakaura remains.

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

1. Import WeakAura https://wago.io/SB53Ikey3
2. Go to WA Settings (/wa) in game.
3. Select "Doom winds" WA
4. click Load tab
5. Tick the box for "Item Equipped"
6. Attempt to put "Doom Winds" in the Item Equipped text field
7. Hit Okay

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No
**Which version of WeakAuras are you using?**

3.1.9
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

No

**Comment by SpatenLa** [comment]
![grafik](https://user-images.githubusercontent.com/39881841/107119557-b8311f00-6888-11eb-8704-256c9d49335d.png)

**Comment by jwshive** [comment]
Well, I feel foolish now.
