### ISSUE TITLE
Export String Contains Bogus Class Information 

### ISSUE THREAD

**Issue by Amadeus-** [WeakAuras/WeakAuras2#2918]
## Describe the bug
I have a weak aura that does not have any Load->Player Class settings; however, both the export string and export LUA Table contain Load->Player Class setting information.

### To Reproduce
1.  Import the weak aura at [https://pastebin.com/raw/gL7uDh75](https://pastebin.com/raw/gL7uDh75)
2. Confirm that under the Load tab, there is no setting for Player Class
3. Export to LUA Table and confirm that there is a bogus setting as follows:
```
 ["load"] = {
       ............
        ["class"] = {
            ["single"] = "DEATHKNIGHT",
            ["multi"] = {
            },
        },
```
_Note_:  You can confirm that the bogus setting is also in the encoded export string by importing it into wago.io.  You will see that "Deathknight" is set as a default category _(and cannot be changed.)_    This is how I noticed the bug in the first place.

--------------------------------------------------------------

I think it should be pretty quick/easy for anyone to see and confirm this bug.  However, if it's not clear and/or more information is needed, I'll be more than happy to create an in-game video showing the issue and/or provide screenshots.

Thanks!

**Comment by mrbuds** [comment]
There is nothing bogus in this aura data, issue is on how wago is using it.

**Comment by Amadeus-** [comment]
Soooo......the fact that the LUA export string indicates a class, when no class is set in the UI, is intended?

**Comment by mrbuds** [comment]
yes
