### ISSUE TITLE
Add folder to help organize auras

### ISSUE THREAD

**Issue by voidlol** [WeakAuras/WeakAuras2#2919]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add option to create a folder, where you can put auras and any groups

**Describe alternatives you've considered**
There are none

**Additional context**
Would be very good to make a folder and put auras and groups there to help organize them. Making a group doesn't solve that, because you can't put group in group.

**Comment by InfusOnWoW** [comment]
This is technically not possible, due to the structure being hardcoded in too many places. 
We might eventually do something like https://github.com/WeakAuras/WeakAuras2/issues/581 instead.
