### ISSUE TITLE
Allow custom activation with 1 trigger

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#292]
Currently in order to show the custom option for "Required for Activation" you need to have more than one trigger. This is understandable but actually it's pretty common to want to invert a simple trigger with `function(t) return not t[1] end` but to do that we need to add a junk trigger (usually status - conditions - always active).

So not a big deal but if it's a simple change then it makes inverting any trigger much easier.

**Comment by InfusOnWoW** [comment]
Should be fixed in the next release.
