### ISSUE TITLE
tracking cast on multiple bosses/nameplate shows twice

### ISSUE THREAD

**Issue by nukhub** [WeakAuras/WeakAuras2#2921]
## Describe the bug
made a very simple aura to track a cast on boss, the problem is that it shows twice.
aura is in a dynamic group (from my dungeon weakauras that i made)

**Do you have an error log of what happened?**
```plaintext
no error
```

### To Reproduce

1. Go to Theatre of Pain
2. Start 1st boss, wait for cast

**Screenshots**
https://cdn.discordapp.com/attachments/218084462523711489/808345557118615592/unknown.png
https://cdn.discordapp.com/attachments/218084462523711489/808347900164833280/unknown.png
discussion : https://discord.com/channels/172440238717665280/218084462523711489/808344257822982165

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
no

**Which version of WeakAuras are you using?**
Version: 3.1.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
i dont think so

### Additional Info
- it doesnt happen if i track the cast on my focus, so i has something to do with tracking on multiple bosses (i have this bug on some other auras that track nameplates too)
- i'm 100% sure i only have one aura tracking this
- i think it only happens with cast that can be interrupted

and i remade it from scratch and uploaded on wago so you can reproduce it :
https://wago.io/YV6wCKa4H

**Comment by Causese** [comment]
Chance is really high that you have a duplicate aura somewhere. Logs-wise I can't find a reason for this
You should export your WeakAuras.lua file after confirming that you're still having the issue.

It's located in WTF\Account\<Account #>\SavedVariables\WeakAuras.lua

**Comment by nukhub** [comment]
ok so i tested with a only this aura loaded and its working fine.
it was a conflict with another aura that tracks a different spellid, on nameplates, on a trash that is not casting during this fight, so i dont know why it messed up things.
anyway its working now, thanks !

**Comment by nukhub** [comment]
so i have done some testing : 
deleted my weakauras.lua, started the game and imported this aura : https://wago.io/PPabfJcaI
its a dynamic group with two auras in it : 
- one tracks a specific cast on the first boss
https://cdn.discordapp.com/attachments/736271525803589703/808686326278914058/unknown.png

- the other tracks a cast on a nameplate, on a trash later in the dungeon
https://cdn.discordapp.com/attachments/736271525803589703/808686370301935646/unknown.png

and the bug happens on the boss, the aura shows twice.
in the second aura, there is a time remaining <= 1.7 sec, if i remove it, the bug doesnt happen anymore

**Comment by InfusOnWoW** [comment]
You have two auras, and two auras show up?

What exactly is the bug? Can you make a screenshot of the actual display and explain why that is not matching your expectations?

**Comment by nukhub** [comment]
i have two auras for two very different things that never happen at the same time, please click the link in my screenshots above.

the bug is that the 1st aura track a cast on the boss, and it shows twice (screenshot from my first post : https://cdn.discordapp.com/attachments/218084462523711489/808347900164833280/unknown.png)

and i believe it's because of some weird interaction with the time remaining in the 2nd aura trigger (the one that tracks a cast on a nameplate later in the dungeon)

**Comment by InfusOnWoW** [comment]
Is that screenshot with just https://wago.io/PPabfJcaI installed? No other aura?

**Comment by Causese** [comment]
can confirm the bug

example:
aura 1 - status cast - nameplate - spellID that can trigger
aura 2 - status cast - boss - spellID that can't possibly trigger - remaining time <= 1.7

result: aura 1 triggers, then aura 2 triggers when the remaining time of <=1.7 kicks in and it inherits the icon from aura 1

**additional info**
- bug goes at least as far back as 3.1 wa version
- bug doesn't seem to occur if unitIDs among auras are matching (only tested with nameplate, boss)
- bug seems unitID specific. e.g tracking "target" as unitID in aura 1 won't cause the bug
