### ISSUE TITLE
Load condition: Soulbind selected

### ISSUE THREAD

**Issue by Theguyxd** [WeakAuras/WeakAuras2#2926]
Would be great if we could load or not load something based on the soulbind in use.

**Comment by InfusOnWoW** [comment]
I did review the soul bind trees before the shadowlands release and considered a dedicated load option for it, but it didn't feel useful enough.

**Comment by Theguyxd** [comment]
I see. Well not much I can say more than I hope you reconsider at some point. Cheers!
