### ISSUE TITLE
boss5 debuff WA not working properly

### ISSUE THREAD

**Issue by jaervified** [WeakAuras/WeakAuras2#2927]
## Describe the bug
I use Aura - Specific Unit - boss1-5 - aura(s) found WA's for my dot timers on bossframes.
Boss 1-4 works perfectly, but as soon as it tries to track boss5, it breaks in all kinds of ways.
![Cduo8zt](https://user-images.githubusercontent.com/69879849/107638056-5a794a00-6c6f-11eb-877a-c3b828df0c20.png)

Either the dot Icons get stuck on the screen even tho the unit has not spawned, the timer keeps ticking when the unit is dead, or it shows even tho the unit does not have any dots on it.

**Do you have an error log of what happened?**
It does not show any error when it happens.

### To Reproduce
It happens mostly on Stone Legion Generals Mythic or Council of Blood, because those are the only fights with a boss5 unit in bossframes. So hard to reproduce outside of the raid.

**Which version of WeakAuras are you using?**
3.1.9 but has happened all of Shadowlands.

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
No

**Comment by InfusOnWoW** [comment]
There's no hardcoded limit to the number of boss units in WeakAuras. We use the blizzard constant, which is 5. Thus I don't have any clue why this shouldn't work, except for bugs in World of Warcraft.

**Comment by jaervified** [comment]
Me neither, i've asked around alot, and tried all kinds of things but nothing seems to work. Its not really debuff tracking on boss5 thats the issue either, because if you just use like Elvui debuffs, or shadowedunitframes, it tracks just fine.

**Comment by RodyCillessen** [comment]
Have this issue as well, though with only 1 use case (Stone legion generals) I haven't spent much time trying to figure out what the cause is or if it's WA specific.

**Comment by InfusOnWoW** [comment]
We just reviewed a few logs from another encounter with multiple boss units, Prototype Pantheon and for that there are all kind of bugs in the events that are fired. The seeds are actually boss units but fire events for arena units.

And thus we really should have asked for complete logs to investigate. That's probably too late now.
