### ISSUE TITLE
All of my WA gone

### ISSUE THREAD

**Issue by krahmalec** [WeakAuras/WeakAuras2#2930]
## Describe the bug

Im using WA companion, and this utilit showed me error like "folder error", after this i had start WoW and WA addon is empty, all of my WA just gone.
**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
The companion does not change the WeakAuras settings file, thus it cannot delete the auras.

The companion has created backups of your auras. It's probably best to come to our discord if you need further help in restoring your settings.

**Comment by krahmalec** [comment]
Oh, sir, how can i get ur help?

**Comment by Causese** [comment]
https://discord.gg/weakauras
#compaion-support channel
