### ISSUE TITLE
Default Trigger for the Kyrian (covenant) proc doesn't work

### ISSUE THREAD

**Issue by StoRmBinD** [WeakAuras/WeakAuras2#2931]
## Describe the bug
When trying to use default triggers to show the cooldown progress of the Kyrian covenant stun-proc (Mikanikos-NPC) the default trigger doesn't seem to fire on the event "SPELL_UPDATE_COOLDOWN" in this case.

Here is my aura with the default trigger:
https://wago.io/N6buJ9trX
Note: I tested with the spellIDs (331612) and (332423).
- 331612 is the spellID when hovering the mouse over the skill in the covenant tree
- 332423 is the spellID of the proc firing in event tracker

I made a custom code to double check on this and my TSU worked, see below.

**Do you have an error log of what happened?**

```plaintext
-- SPELL_UPDATE_COOLDOWN
function(states)
    local _, _, _, _, _, _, spell = GetSpellInfo(332423)
    if spell then 
        local s, d = GetSpellCooldown(332423) 
        s, d = s or 0, d or 0
        local exp, dur, icon
        if s + d then    
            exp, dur, icon = s + d, d, GetSpellTexture(332423)
        end
        states[""] = {
            show = true,
            changed = true,
            icon = icon,
            progressType = "timed", 
            duration = dur,
            expirationTime = exp,
            autoHide = false,
        }
        return true
    end
end
```

### To Reproduce

Since the issue has already been explained you can reproduce it by trying the linked WeakAura from wago:
https://wago.io/N6buJ9trX
Note that a Kyrian with at least "Renown 30" is necessary to reproduce this ingame, since it's then when the player gets access to the proc.

**Screenshots**
It won't help much, but this is the outcome when you compare both approaches:
https://prnt.sc/z3vv7g

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I'm pretty sure it has nothing to do with other addons.
Why would my code work then.

**Which version of WeakAuras are you using?**
WeakAuras 3.1.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Since I came up just now with the idea to build this there aren't any older versions of WA that can testify a possible functionality.

### Additional Info

Before I opened this ticket I have discussed this issue with the moderator asakawa on the discord who advised me to come here to report it.

**Comment by InfusOnWoW** [comment]
The trigger works fine with the extra options:
* DIsable Spell Known check
* Exact Spell ID.

**Comment by InfusOnWoW** [comment]
332423 is the right spell id.
