### ISSUE TITLE
Unreliable activation of Glow

### ISSUE THREAD

**Issue by Xo1o** [WeakAuras/WeakAuras2#2933]
## Describe the bug

I made a dynamic group for my cooldowns and attached it to the Personal Resource Display, which I have set via cvar to also show when targeting an enemy (or myself) on top of showing in combat or when below 100% HP. Within said group is an aura for flame shock. This aura has an "all of" condition that checks if 1) target is attackable and 2) aura flame shock is missing. The button is supposed to glow when both conditions are met, i.e. there's no Flame Shock on my enemy target. This will not work 100% of the time and I think it has to do with the anchor being the Personal Resource Display, because it works 100% if I copy the aura and don't anchor it to the PRD. My guess is that the loading behavior of the PRD somehow interfers with the Flame Shock missing check. 

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by InfusOnWoW** [comment]
Please answer all questions.

And include the aura in the ticket.

**Comment by InfusOnWoW** [comment]
No response from reporter.
