### ISSUE TITLE
WeakAurasCooldown Frame Not Inheriting Correct Scaling

### ISSUE THREAD

**Issue by ManagerWoW** [WeakAuras/WeakAuras2#2935]
## Describe the bug
The WeakAurasCooldown frame is not correctly scaling the same as the frame/icon that it is attached to. In this gif example, there is a 1 pixel gap between the icon and cooldown swipe on the left side of the icon which should not be possible if they are the same size. Throughout the gif I'm changing the size of the icon which makes the gap go away and reappear.

[GIF](http://manager.heroicstrike.org/cTLKMrvD.mp4)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Happens even with only WeakAuras enabled

**Which version of WeakAuras are you using?**
Current alpha: 3.1.9-27-g1951e1f

**Are you on World of Warcraft Classic or Retail?**
Retail

### Additional Info
I'm using a pixel perfect scaling for 1440p, achieved by this: 
WeakAuras.frames["WeakAuras Main Frame"]:SetScale(0.8333333333333333)

It seems like the cooldown swipe frame is not properly inheriting the regions/scaling of the WA it is attached to.

**Comment by InfusOnWoW** [comment]
Your analysis is wrong. If you run GetScreenWidth() / GetScreenHeight() you'll notice that wow does not think your screen has a round number of pixels.

The cooldown frame is attached via SetAllPoints to the icon.
