### ISSUE TITLE
Simulate different class, character, or zone etc. to see which WeakAuras load in different circumstances

### ISSUE THREAD

**Issue by cloudbells** [WeakAuras/WeakAuras2#2937]
**Is your feature request related to a problem? Please describe.**
I would like to tell on an alt which WeakAuras will load for my main when my main is raid logged with world buffs in Classic.

**Describe the solution you'd like**
Options for entering your class, character, zone etc. in the form of checkboxes and/or textfields(?).

**Comment by InfusOnWoW** [comment]
Too much effort for too little gain.
