### ISSUE TITLE
Generic Trigger - spell cooldown  - remaining time - GCD dependant

### ISSUE THREAD

**Issue by McKazou** [WeakAuras/WeakAuras2#2938]
**Is your feature request related to a problem? Please describe.**
I'm having a spell cooldown UI based on multiples WA like some of us are using. 
Some of the WA are spells on cooldown but show a bit earlier to give the information what next spell GCD i can press. 
This "bit earlier" is set in stone using a constant "1.5" or "1" sec (depending if it's a melee class or a caster) in the generic trigger on Statu>spell cooldown. 
The problem is during bloodlust or haste proc or even thorghast, this constant feel akward sometimes and doesn't answers to "What's my next ability" or "Will it be ready next GCD" perfectly.

**Describe the solution you'd like**
I suggest to allow the input for the generic trigger to be able to accept something like : 
 - "GCD" : give back the current GCD (getSpellBaseCooldown function API)
 - 0.5xGCD or GCD/2
 - 2xGCD
 [Bonus]
 - or (let's be crazy) any custom function based on spell cooldown or cast time
 - "CastTime(123) + spellCooldown(235) + spellCooldownRemaining(569)"

**Describe alternatives you've considered**
The solution i'm currently implemented is a custom function based on getSpellBaseCooldown to replace the generic trigger.

**Additional context**
This could be extrapolated to more input filed in the trigger section
For example : *probably another subject* Chi < 3 imagine you could have Chi < MaxChi-2 (so it dynamically change if you change talent that give you 6 chi max instead of 5)

**Comment by InfusOnWoW** [comment]
That would take far too much effort at the moment.
