### ISSUE TITLE
[Idea] Choose to fix text length inside progress bars

### ISSUE THREAD

**Issue by Kittiez** [WeakAuras/WeakAuras2#294]
Would be nice being able to choose to limit the length of the text to fit inside progress bars, if wanting to.
Just like an option or something like "Limit text to length of bar" or something.

I use weakauras for castbars and it's so sad everytime the text pokes beyond the bar D:

**Comment by InfusOnWoW** [comment]
That's supposed to be the case automatically. Can you export your aura and attach it?

**Comment by Kittiez** [comment]
dOKZkaqjvQQrbv6uqfRcvHxHc1SiOUfkAxOq(LkLQHPQoMQSmK8mPQPPOUMISnc5BO04uOohPQ3rePMNkLO7PsPCqfIfcv1djvmraPlci2ib(OkvyKQurNKGSsa0mvP4MerTtO8tfsdfvPLcapv0urQRQsv2QkLuFvLkTwvkjZLuP9s9xaAWioSuwmQQhRsMmPCzL2Sc(mrnAI0PfSAIi51qvMnq3MqTBv8BHgUu54QuclhYZjz6sUoQSDIW3rv04buNhfSEIi2pO9Z0odof6ulAODT6oIM2OhLU3DB4nchQP0vYRwOPl9cCXHwLUHR4XPYjfJMzevVtXo1CQzANQUgcV7g0kPgB2jWJomO2YymFSZozy0Hb1wgJ5mRtvxdHhaIvRcXJXOy)o53UWtgf5oA6ebJitBSNfWYY(1)y))5V(pf73dmN6ngLfWYY(1)y))5V(pf73dmN6nwVfWYY(1)y))5V(pf73dmN6n2SfWs9Nyf9)ZJ)9SJ1)9aZPzxohINsaytw5C07rFJqyaXj)gsNiyezAJ9SaruprS99I(9uSuuprEG5KiJrzbIOEIy77f97PyPOEI8aZjrgR3cer9eX23l63tXsr9e5bMtIm2SX(mIDYLZouugTkfVO9kOcXJX(obJnnt7mCKrrUot7umhyfmTlxo5ulGNvIfz(oRg4Ekt7umhyfmTlxovD7LPDQchzW1ypNI5aRGPn2Z47YLtTWWq4IdSyW0ofZbwbt7YLtueCnTtXCGvW0UC5SAG7POmTtXCGvW0UC5CODvH4X0ofZbwbt7YLZlWMszANQWrgCDcuaCpHaQtXCGvW0obkaUNqa147K3rUzeGkeMX3LlNO21AANI5aRGPD5YzNeDvdCpLPDkMdScM2LlxovIJXskVOOmAvkJVt0khIhAg6wNnouJFd5uvTl8uMVtvxdHhqxvR4qTAnFNHtOa8kkUdCRvZypN1cCXHwNcPK()oRf4sq8uodIBYHZc4q8uovDneE0lWfhADk0Pw0q7A1DenTrpkDV72WBeoutPRKxTqtx6f4IdTkDZBbxdTaExPHADYpI0wKqh1wg75KFePTi8Bx4PHIDoXIN1z7QcsS0OGS8IKCuBn23Pwq1b2yGEbUUzhkN3Vdsycj3)4u11q4PtemImTXEwWy2j96NPg)Nf9(JNM8aZPzJrzbS6htnE69(Zu)3yQzpWCA2y9waR(XuJNEV)m1)nMA2dmNMD5SDcIBviEmTtv1qLPD2Hw1wovGbTfChkxohcNGsQPDEfbJOrm2Z5vemIOzOBD2XbQwDIGrKZo0Q2YPcmOTG7q5eyJ9D2a7K2m23P6QbUmySNtgm235vemIW3cg)N6N1pn(pt1R))17bMttoVIGr0DybIEJFZVh1up1uVikrEG5uVt1vdCb2ypNxrWisa35Y5a35QcXdUDOOmAvkHHe0tyir(jmKW)jmK0EcdjikHHezkHHe(ucdjnkCGaesGeibsGeibmE1aHK2rgCHKBdsWTdfLrRsbj8asOGeEajIBLug1fWbsycj4kUvszuxasUDiHchiaHeibsGeibsaJxnqi5S8KxuugTkfKCBqcU4kUvszKkCWTDKbxCGegdjpCUDkCK0qacjqcKajqcKG2IdDGe0dsymKG7z5jVOOmAvkiHhqcUikiHjKGE4GJWqacjqcKajqcKajqcKajqI8dsymKG7z5jVOOmAvkiHhqcUYuqctir(HdocdbiKajqcKajqcKajqcKaj8FqcJHeCplp5ffLrRsbj8asWLpfKWes4)WbhHHaesGeibsGeibsGeibsGK2dsymKG7z5jVOOmAvkiHhqcUnkiHjK0E4GdeGqcKajqYE0GaesGeNOy1Q1yFNxrWicawW4)u)S(PX)zQE9)VEpWCAYjNAb8kcgrgFxUCwOGS8ImTZIHU1PQAfNYjNAbK7ekJVtUZkXEkNnUk68ItvrXaknOToRG4vZz3IU2tjDBGLuNV)35kXEkN60uLto1cy3IU2tjDBGLuJVZUfDTNs62alPag7wuRIiN3sxoRf4Y8DQ6Ai8KCaHIiZ3j)isBrJomO2YypN1cCLbjzn2yNruypvRcXJZ7Cuai0TAum6rUbqHWU1abajqCkDdYslJ96DE4etJcYYlszmkNQUgcp8b3JMKJARt8Vbiya1j)2fEAOyNorWiY0g7zSVXOm23y9g7BSzJ9C58kcgrM2LtEg0kPwWeflROPXZ6zfXQVFwVhyop5KFePTiJVt(rK2IaIM868oqbnkirayRCYpI0wugKK1ypNCNcfKLxKPDYDcLZoWgdlYLZWv8aOkOToVbicODQfuDGngOxGlaeKLwoHK73bj3)4u11q4DNBqwAzSxVZAbUea2Kvoh9E03iegqCg0CY7wqcJHeEbBmSiirNMQCwbXlkdsYAS3ZPwqjP4oxvqI1z7WGZMMwOcXtdeWcfKLxKY0g7zANfkilVit7SyOBDQQwXPCYPwa5oHY47uXXFLypvYnmea2jG6mssdyspcaODYDwj2t5SXvrNCNq5SBlNRe7PCQttvovC8xj2tXlAhca7m5fi3CJlNCNcfKLxKPDYDcLZUTC5YLt(rK2I0jcgrM2yplG9X(N7z)t9SSZu)Nhyo1BmklG9X(N7z)t9SSZu)Nhyo1BSElG9X(N7z)t9SSZu)Nhyo1BSzJ9C5mCfpMVZWjuaQQgQwnJ9C5ucJ9MPEUSb

**Comment by InfusOnWoW** [comment]
I can reproduce that. 

I was wrong on how we layout texts on progress bars. While we do limit the length of the text, that's only done for the right text, that you aren't using. Adding a limit on the text length can't be done without breaking some auras, so we need a more general solution and that probably requires making the current magic configurable. That's a bigger task.

I'll probably change how text are layed out for progress bars in the future and I'll keep in mind what you want.

**Comment by Kittiez** [comment]
Ohh thank you for the reply! Did not know that it only worked one way to be honest.
Do you know if there's any possible way to do it for text-only-weakauras? Since i wouldn't mind making the text a separate weakaura, but when i try to do that it just adhere the weakaura size to the text

Either way it's only a minor "issue" of anything at all. I don't notice it much since most spells don't go over, it's just those times i mount etc that i really notice.

**Comment by InfusOnWoW** [comment]
I've improved the text aura so that it can now be have a fixed width. Thus the work around for now, is to create a separate text aura and position it on top of the progress bar. And configure the text aura with a fixed width.

**Comment by emptyrivers** [comment]
This seems to be a stale issue which was fixed long ago, so I’m closing this for now.
