### ISSUE TITLE
Added Shadowlands Spell Models and  search

### ISSUE THREAD

**Issue by volko1ak** [WeakAuras/WeakAuras2#2940]
I can't find a single one. looking for a model of the Fairies of the Soulshape and the Door of Shadows of the venti. I searched manually (it is very inconvenient that there is no search). 
please add spell models from the latest additions and search by words

**Comment by InfusOnWoW** [comment]
A search box has been already been added for the next release.

Blizzard no longer names their files. We've recently added the latest community file list, but neither door of shadows nor the Fairiers match any names.
