### ISSUE TITLE
Progress bar Foreground-color disappearing when full

### ISSUE THREAD

**Issue by TalasNetrag** [WeakAuras/WeakAuras2#2941]
## Describe the bug

Setting up a progress bar for HP/energy/focus with this triggers:
1. Trigger when ones HP/resource is < 100%
OR
2. Trigger when in combat

When HP/resource is at 100% while still being in combat, only the background-color of the progress bar is shown instead of the expected foreground-color.

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.
**Which version of WeakAuras are you using?**
3.1.9
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
In February of 2020 it was working fine (haven't played since then).
### Additional Info
String export:
`!WA:2!1v13UnXrx8SYsuXkKAIlerKsfuQGVEdusQksTc(A9ASjMMyBwVqGcQ2ZUZSEhy9mRMz24KChw9ICTFe819k)iKNGrwv9bipc5jONzwJXbrJuSpNzoZ5V)(DSt9YdkJlJp57NiZqI3TpfRsU2eAeN1HNlIiBUI4WwXXsIYrC0CHPiwucx0MtzQWQ1AguZFM91(Cfsr5mNS1UG(ECmXRYZdA5zCCYiLG2Vpri)J7iMlEs5ZYLKUOqjxeAmVNpdnGiDNGjH5XXbhLre7uB321F(UEkqjucUoxoY8QCgv1tKZihqykpuUINToyEeOLqqPQKUCqfP4IYpC2fUy7TU)99TpZVnFirKTQXFZnjZCsppJ3dZsrhreNjZdTw3wqIPh63PDTD3DKmJKM2alDxCDhiJPhoTB1kDc62jOIFWiCUW2kkVv2AlfJI0O3Plhs91ZU2Y6lL9JZzZByU3rFL)rVMU8PgVrzr8bHivp9v1xRia9jmIGg1jHpSfR3SlOEM0(vvopfZhY0BQ)6zcit6yQKMqF3zMXfYpO2B8crh9gtQYzyQPyK6VT8wJnMQeOO31t)L6v1)p3PyQ8T5Sif9aY2i2rzRHSYbfPUz8(xRyXyDJ4PCXtlb)DoaMicgk9faWa89ZgljPXwmM(sJcrIQfM64ucWesy4d9esYPwGwbW8votGjGpPVj1(511RnfbgbpTl8)jRNvwrou1vMGGI(LfpP0y7zMpU1TZYwDjlkINdeVZkoDr6C5SVYEIbPnaMQrwwJxfq9C7fWWNGTh((zfCLxnN6CQ9(3Mlv04J0xAIWWqibWHEnB1SMEnbubgBMyn8JTNI8mMdyIvRlOhFZNLJWqhaDZGGluyZJ0MRueQdOsAykP3mR2qUaVVaLnA)5cZw4wddZRjNrM3ewIJpPrZM187UBT6bzFZI(f8kbu9DZ6QOdaaTGerndUszB8zSPqW3yk(JbTd9yYgZBrZNioz34)ke4JGDc0OKtUQ(HL0p6w3MP))2bK(x0xw)R6kAV3RR6OFS(s6A66a74j6DSDpDd9t1)2MRO3t3uVBp9ZMwus(nEYob6w626xSHEFNptMZMl4XGwtycH2prDdVuocxpuHsbo66(dYtvuxpGJeTUURRFuksknsEsO(mcNzrPEG5yd6F7kp(X2vnvWgOabtW7Homz7CkE6WWyr79sAu)P7ngXOdSBnEGpSUtOQFkbjjDuccRVk5lGc81Z(WILUMTIcjbyvy5iJDMjQ(1EdquwD9BTwRFNovpq)6WykJkt(0J)0CIYsMiS0j7(35SjHHndmShOPUAURh4kL7mGmadXwz2RChBz3skM4B7XlttFPtiCzmTV7u7P7yBQpsyA75cYiVu6XhJe4PXcyHduTakVK3XC(ahF7dsMO4rhuSM46oDhFlkE7MKHZ9gfJjm)M1ErnFFuAwcQ05faS6g3zkKWov9RvRP)qdd9pVsXV8vDbvtqzgN)HDlbfPv231WSGkgfrEtveWFz99qI388g39JA3TJ5bt5ckGlStLj70YVXV3QzqLDNeTyTP7ukRawbAUNhc7o7l45m8IDoTlD)79JLL()W926E)u5d(7x(Vp`
Lua export:
`{
    ["sparkWidth"] = 10,
    ["sparkOffsetX"] = 0,
    ["xOffset"] = 0,
    ["yOffset"] = 0,
    ["anchorPoint"] = "CENTER",
    ["sparkRotation"] = 0,
    ["sparkRotationMode"] = "AUTO",
    ["backgroundColor"] = {
        [1] = 0,
        [2] = 0,
        [3] = 0,
        [4] = 0.5,
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["use_absorbMode"] = true,
                ["use_unit"] = true,
                ["unit"] = "player",
                ["subeventSuffix"] = "_CAST_START",
                ["debuffType"] = "HELPFUL",
                ["type"] = "status",
                ["percentpower"] = "100",
                ["unevent"] = "auto",
                ["names"] = {
                },
                ["percenthealth"] = "100",
                ["event"] = "Power",
                ["use_percentpower"] = true,
                ["spellIds"] = {
                },
                ["duration"] = "1",
                ["subeventPrefix"] = "SPELL",
                ["use_percenthealth"] = true,
                ["percenthealth_operator"] = "<",
                ["percentpower_operator"] = "<",
            },
            ["untrigger"] = {
            },
        },
        [2] = {
            ["trigger"] = {
                ["type"] = "status",
                ["use_incombat"] = true,
                ["unevent"] = "auto",
                ["use_genericShowOn"] = true,
                ["genericShowOn"] = "showOnCooldown",
                ["unit"] = "player",
                ["realSpellName"] = 0,
                ["use_spellName"] = true,
                ["duration"] = "1",
                ["event"] = "Conditions",
                ["debuffType"] = "HELPFUL",
                ["use_track"] = true,
                ["spellName"] = 0,
            },
            ["untrigger"] = {
            },
        },
        ["disjunctive"] = "any",
        ["activeTriggerMode"] = -10,
    },
    ["icon_color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["internalVersion"] = 40,
    ["selfPoint"] = "CENTER",
    ["barColor"] = {
        [1] = 1,
        [2] = 0,
        [3] = 0,
        [4] = 1,
    },
    ["desaturate"] = false,
    ["sparkOffsetY"] = 0,
    ["subRegions"] = {
        [1] = {
            ["type"] = "aurabar_bar",
        },
        [2] = {
            ["text_shadowXOffset"] = 1,
            ["text_text"] = "%p",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_selfPoint"] = "AUTO",
            ["text_automaticWidth"] = "Auto",
            ["text_fixedWidth"] = 64,
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["rotateText"] = "NONE",
            ["type"] = "subtext",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowYOffset"] = -1,
            ["text_fontType"] = "None",
            ["text_wordWrap"] = "WordWrap",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "INNER_LEFT",
            ["text_text_format_p_time_precision"] = 1,
            ["text_text_format_p_format"] = "timed",
            ["text_fontSize"] = 12,
            ["anchorXOffset"] = 0,
            ["text_text_format_p_time_dynamic"] = false,
        },
        [3] = {
            ["text_shadowXOffset"] = 1,
            ["text_text"] = "%n",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_selfPoint"] = "AUTO",
            ["text_automaticWidth"] = "Auto",
            ["text_fixedWidth"] = 64,
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["rotateText"] = "NONE",
            ["type"] = "subtext",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowYOffset"] = -1,
            ["text_wordWrap"] = "WordWrap",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "INNER_RIGHT",
            ["text_text_format_n_format"] = "none",
            ["text_fontSize"] = 12,
            ["anchorXOffset"] = 0,
            ["text_fontType"] = "None",
        },
    },
    ["height"] = 15,
    ["load"] = {
        ["size"] = {
            ["multi"] = {
            },
        },
        ["spec"] = {
            ["multi"] = {
            },
        },
        ["class"] = {
            ["multi"] = {
            },
        },
        ["talent"] = {
            ["multi"] = {
            },
        },
    },
    ["sparkBlendMode"] = "ADD",
    ["useAdjustededMax"] = false,
    ["iconSource"] = -1,
    ["icon"] = false,
    ["useAdjustededMin"] = false,
    ["regionType"] = "aurabar",
    ["anchorFrameType"] = "SCREEN",
    ["zoom"] = 0,
    ["icon_side"] = "RIGHT",
    ["actions"] = {
        ["start"] = {
        },
        ["init"] = {
        },
        ["finish"] = {
        },
    },
    ["sparkHeight"] = 30,
    ["texture"] = "Blizzard",
    ["authorOptions"] = {
    },
    ["sparkTexture"] = "Interface\\\\CastingBar\\\\UI-CastingBar-Spark",
    ["spark"] = false,
    ["sparkColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["id"] = "New",
    ["alpha"] = 1,
    ["frameStrata"] = 1,
    ["width"] = 200,
    ["sparkHidden"] = "NEVER",
    ["uid"] = "wbfrPMhIFJM",
    ["inverse"] = false,
    ["config"] = {
    },
    ["orientation"] = "HORIZONTAL",
    ["conditions"] = {
    },
    ["information"] = {
    },
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["main"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
        ["finish"] = {
            ["type"] = "none",
            ["easeStrength"] = 3,
            ["duration_type"] = "seconds",
            ["easeType"] = "none",
        },
    },
}`

**Comment by InfusOnWoW** [comment]
At 100%, the second trigger provides the progress information. A "In Combat" trigger has no progress information.
