### ISSUE TITLE
Shadow Dance cooldown bar is showing the buff duration instead, when Enveloping Shadows talent is selected

### ISSUE THREAD

**Issue by TalasNetrag** [WeakAuras/WeakAuras2#2942]
## Describe the bug
Setting up a progress bar to track the cooldown of Shadow Dance and selecting the Enveloping Shadows talent, causes the progress bar to show the buffs duration instead and after the buff is gone, it shows the CD.
This happens when there is still 1 charge of Shadow Dance left. 

### To Reproduce

1. Set up a progress bar to trigger on the CD of Shadow Dance
2. Select the talent Enveloping Shadows
3. Use Shadow Dance while having 2 charges left

**Video**
The red bar in the middle is showing the CD of Shadow Dance while the bottom teal bar is showing the buff duration.
When first using the ability, the red bar is at first showing the buff-duration and then changing back to the CD.

https://user-images.githubusercontent.com/23062877/108401777-01845580-721d-11eb-9f6d-986ced816ccf.mp4

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
3.1.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
February 2020

**Comment by InfusOnWoW** [comment]
That's a misconfigured aura. If you would have included your aura, I could have told you how to fix it.

**Comment by TalasNetrag** [comment]
Heres the aura:
`!WA:2!1vv3UTrru4SyvbYcHsDGOgPk1qLkQCrlKwAHwOaEDwtn464U72MwPkwp7oJ9o01ZSAMzZF3vlUix7hbFnx5hH8emYWla5ripbCMz34(Jkrk2NZmFN5mZ358DSt7gJBGBGp(RMjZrIxUlfRs)Sz0eolGxisixEfXH7mCOKOCMJyjPCrFoLPIB51l0ZFHniFUcPOCMt(fFl)hXXe3MpjChxZ5LorjOJgreYp5levMh340cjjcfl5Iyd8blgryebnjiLV)oStL2VAX5zy((m3cgvfNNHoKiMHjXfdhgEyor8qVU9B)KUUkWjwcjVqEQSiMShHPcaq0dMh1Qzqyuqyt)WjMuAoPb(m0yISUVfy(gNNMn7l4JeePCZRhKtYY(YLhwFbbom)G(ED7Uqqqz297bNYjbjPiLcWGyhTWKb55BnyI1SdwwF6YfV0h83)ROGzpvxuHIpbxiSSwJTMAcxjqjVCq(fn2VfNmyAbRI(QNFruIIUhjS03WG)1k2QxucpJl(1AWFNb1lIGHYEkW9qcE8ujjBOTmQVWKyKOvjuhNAaPkb2dUiK0tS1YYA)ZDMbuGpzeeU8(RRxBocabHgb)F865nuKdurYueqFpRmKAtTRz(4QxlpF13arz(CG8DA5QlVoFu(A2vmeYyGnsS9JUnb3ZSBaSpbBx8vlkBhFEv35j29)JcPIo8q9fMjmnHKqyr3E70ZtVMaEbgmZSaFn9uEphYHoGvBlOhT5JlqyGbqBgg(wpSQmD5vkt1Eujnod6yTE7Zf4DfO8j7wzSy5XAArD7XzKks4nKrZ60RNNFuxV2H5F(s(cIsaV(O8ifDmjkxqsOMcxT8nEpykn8nqXVoPb0JiBurrvveN8R8)Lc8HGsGMKE8NQ3QM(wx9Am9TTfi93O)i9D03v)TVs)Do67PVG((6VxVM(h0pWYE6Fu)t6F(YROD1T0nhOBpV8j535xEyOEBTN(32q3159CZzvgUmGAItj0rPQ)8JDZ4iC7yfkdegR7pUitrR7cYMK11H19tYqsPXYvcpqJXP22uxao20(FRMBVD(QGOPj20lqWe8JqhKo3I6HumMW8759up)PigDSvWDxFyKHq1(ecsscuccBKk9dH3y)fNRjJmtwesciSWYjgCMIQUV7yeL1whzrRhOr6yD)4HugvM(Ullmsvq(Cx9VxxJR7cGu1F3RkLLotyLz2bBvQmXbN3K)gAYN5m1k0LumX3s3XG7q6O6LOmT(fcs(17yK)drjKx0cbQd2ixK4fpPZnET3ncmbuXr2cXdeQYWN4Mrp6iKaFRckEoFRE939EOSIKh5EeNp2X3gt6mfpzVYPlxYjA6vP4fM5HGOzZTHEqI)(gj7v8rz5POANv2w2waZbnpZ4Gw(EE9Mp0SauaaTxTYFoQ1svQGYmjaKBWSbi4DYTKz95Cb1m014LVkuxd70Qz3Oo9aZaVzMcgTcjLv2WbE1plgMUosWly4LtJ6x7RV5DAi9V9n36M3RXE)ZZ(Vp`

**Comment by InfusOnWoW** [comment]
1) Shadow Dance is put on CD on usage, the display of it is not a bug.
2) If you want to only track the charge cd, you can enable that in the extra options on the trigger page.

E.g.:
!WA:2!1v12UTTrtyZiGue1GchLw3iGGw3aKIKlYFBCAcqlqpiktfR8llRqYy7ueaQLKRe3gQDj2DPpO7IqVWxRhbDDVspc(jyHAFbQFe8tqNDjTCsqIae5oZUZm78nZ3qRw1gvlUw8jF3mrgI)69iXYKVygjIr9y58i8TxzbkxMW47KjjmQOk)4DgmqGLwZr0iqFpgHkdB6013XDHXhUmjsFwRSB8oYBZIX2nEH)oCuKXxpXvirCz1WbekrKu1gEjRorYjdhI5Ip7B5Llp5MUsWOxZJsq8HyXK4CUXL1E4IHykMtI8syhUd9mH5vtglnMDiiMhIpatL944bKJC9650PZSyCy(Gb(hNH5B50PxRx0XwccUImCAkpNASWgYAMlfnclQojxGdYH7wFxZEz1ViaR3JZgYXcX63ZtB99T1hlmlfDmMVGJrPg1Db3CQhC5LsWCeD8cThfxSv)jMLTJfvNUu5TUYF)VlV)EWfMC08GMn88d88B46FM2dOqbJhQX1(t1YgqQF2n0RFhCb2MwILvZUHg(pa7xiRT(VwXuXdIyPm(ZQa)ohkQyofLUluiaG(LtruYidM)e1N26umsG9KCmDOm5tu1TPmkEXfvLanCYfyWLXIj6JQbB1JShHi0wQnadups9dQhREc8(6VVMjHiEZIBILvfOCjqsTNXjNA6Nk6)EP1maDCXd1Ds)0AQ6ZrWHatdG)N8LzFLeFKmW8yaJdx9GSajzeUuYA6Y9VZDZYw1ijsqqvTi2wqSpRqloDGPlxDTSBA0O7n0GrKHUy3aepVisKJWXgLVzrb94LLSLtn7)h5cjzWXQRoJRjfyFqPD3D66OQZHSrFMzMdEzLyAzkaTDR2ItgV(ZZrXaAGw33Vmg7xgJSAVvwug4BVsrKpGiiHP4(lmshY4X7Xrzt2RCXILrrxQS7cLZsm5Ty5ZA3TRJBqhNw(z1)aWBXcxnkhN9nFm8pJJJi6EQkxgupYyC9S7)Xmj(yGisIcKjaxlbOEVBQwM)vo5Zv)Ef1VCN7sv)QP(P(n11unu2QMVrTPLYrDvvl1tHETTuTnGR6zQ)VA7BVIAhvpv3(kV5fPOB7NULV65kx1(1vDS(azlTCH6rHjyYWe5FED7ugkE3qjkfySR5okpvsQAlGuBnv)QUrPiHqVYg44r6f8XamdS(RCMPV2gSlwth3OXMBMTkqIBeRByWX44TrhLyR5OjNhcC8HCwonEzJAVkF))7XVVfeAYmUHEyg1vYo4hDrd5BXL23AQH)liXyxtUBpMXgzn3CMTiXXyQBxNDDCl1yY4FMRbKCoEIDkz8yepoeCYaYWQf(2Vy3S71wplzakc)QMiO)No0gXF1lA)GlLEGN5dfgZsMjzrhum25wwbtVdjEHE2juOxFtOBeFErlzlomLuNAHEnDDC6oFGwbmuc4gvCputc)AxuAwcQYg5K45Sh2T3E)iknpABoHQdaUFXh9AUKSnNXj6j06PyzRc5RF7Mn6e0UlS0ZzMEGgP4ZGZj0IgaqcMAVCeXvRj2yt8b1o4F2))o

**Comment by TalasNetrag** [comment]
> 1. Shadow Dance is put on CD on usage, the display of it is not a bug.
> 2. If you want to only track the charge cd, you can enable that in the extra options on the trigger page.
> 
> E.g.:
> 
The aura you posted did not have any triggers (there was a warning about it being from a newer version and that it might cause issues).
But I found the option you mentioned, now its working as intended. Thank you!
