### ISSUE TITLE
[Buff remaining time < GCD] | [Buff remaining time < CD remaining time]

### ISSUE THREAD

**Issue by Fosphen** [WeakAuras/WeakAuras2#2945]
Every spell priority profile made for simulationcraft, whichever the spec and class, has global cooldown dependencies like:
cast:rampage,if=(buff.enrage.remains < gcd    OR   rage > 90).

Archimtiros once told me this, while discussing arms warrior:
https://cdn.discordapp.com/attachments/766832027495432192/812322156150784010/unknown.png

(List of all simc class profiles:)
https://github.com/simulationcraft/simc/tree/shadowlands/profiles/Tier26

What I want to happen is this:
https://cdn.discordapp.com/attachments/218084462523711489/811934731641683988/unknown.png

Beeing able to compare buff or cooldown remaining times against GCD **remaining** time or GCD **total** time

And beeing able to compare buff remaining times against cooldown remaining times

Thank you

Kind regards

**Comment by InfusOnWoW** [comment]
That currently out of scope for WA.

There are other addons that can handle that kind of thing much better.

**Comment by Fosphen** [comment]
If you now of the name of the addon I'd be grateful.
My googles weren't successful
