### ISSUE TITLE
Slick Ice"(6823)" - "item Bonus ID Equipped" will not recognized or symbol will not displayed

### ISSUE THREAD

**Issue by tehmilcho** [WeakAuras/WeakAuras2#2950]
## Describe the bug
I created a new Aura to display which legendary is equipped with a Symbol, i want to switch between "Slick Ice"(6823)" and "Glacial Fragments"(6830). It works fine with "Glacial Fragments"(6830)" but its not working with "Slick Ice"(6823) ", there will be no Symbol displayed also other Auras with this Trigger as "AND" will not Display when the Item is equipped . I think the ID "6823" is wrong but it is the ID from the little Help-Popup

### To Reproduce

1. Create new Aura -> Symbol
2. Create Trigger ->   Status -> Item Bonus ID Equipped
    Item Bonus ID 6830
    Fetch Legendary Power - Checked
   Item Slot  Legs
3. Create Trigger ->   Status -> Item Bonus ID Equipped
    Item Bonus ID 6823
    Fetch Legendary Power - Checked
   Item Slot  Legs
4.  Switch Trigger to "OR"

**Screenshots**
![image](https://user-images.githubusercontent.com/22918349/109002325-59501000-76a6-11eb-8471-df799dab8f53.png)
![image](https://user-images.githubusercontent.com/22918349/109002419-7be22900-76a6-11eb-9381-d577cbcd5a9c.png)
![image](https://user-images.githubusercontent.com/22918349/109002359-67059580-76a6-11eb-8af2-f2518e0734e4.png)
![image](https://user-images.githubusercontent.com/22918349/109002490-91575300-76a6-11eb-8ef1-304bc232f6a9.png)
![image](https://user-images.githubusercontent.com/22918349/109003066-438f1a80-76a7-11eb-962e-d2032a948fdb.png)
![image](https://user-images.githubusercontent.com/22918349/109003108-5275cd00-76a7-11eb-87cb-be48fbc93520.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
3.1.9

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Unkown

**Comment by InfusOnWoW** [comment]
The code does look correct, and that should be the right bonus id too, so we need a bit more information:
* Your actual aura.
* And the outputs of running:
/dump GetInventoryItemLink('player', 7), GetItemInfoInstant(GetInventoryItemLink('player', 7))

while having each of the legendaries equipped.

**Comment by tehmilcho** [comment]
**Aura Export:**
`!WA:2!LrvZUTTXtCR4wyuvuKy1e142GexxuFiOWi2Poi)7Luth5yvil5qsN4EPIljxkUou7YS7slPG(bIo5Z6qFaekqV0t6bO4p8tWcHI(a4hb)e0zxsPK0QdI78BMD(A)ntP9Q0TsyLWZwBmjGrDyz8a8TwG3VvuKal3)B78n)(cWp(GcG)Fe(PAGjiAqmJFiJqL(7wRPBn7PbmwsiRh1Phjf7D(mXAHDWXCuGKWOIhylKiUSSfHsKL9JGpI4YdLCsNoyU4hwNxC8SQdjsC3MOU4BELF7pVitGBJ8fmU)bSqS3LAzTbwmAMOEO3qnqg403OYbl1x3BYBjCLXHy)SOi3bPy((1AC4Eh1Wscc(qEjZewAx4NMGgG58mk(umvAHYKmt24KWKx98z()noVijSEWdV)9Sn3jTADaFvJIvRhUATxMrstXHZVS2vEPlRftWDW0qeFqD4jWBOifNKupuu(crMVXzhYXrK(2ohwRrJ5Goqvq6pP9U74422XDhB3jgFtpf6J44HHzCKULxztBkKOIYJYOf92QQBRUZ6Qp6SLZtai8yojWjM1Rf1B67iEHW8z3Iht1nvRO(cVrMKu3akPQQ(e1NQ(m1QQpxDD1nMYXOeN5QNQdWCR9u36QQR5PUBLnvR5nsRtcuJx4PUn0826(QVsNBF9KqI4KmkqzofVfIoiDzK5SBE(Rza)XcxcupmNIsEguWqH(0lFbgNUdeRaPTU0JhjWjrgkQ69H3Db8ad9eC8yOhAJ7O5J39SRNwrI7lBlIrqbECopVu6kgqZFrmExeyqXblkJIhnx9AFPi9AVLh2LLW4FxPsLw8IC0z5G1oh52k9JnGAgf4ksWZjHYyRDaXlZJfPpo0a(6P5JyFFrgDUr)jzcjjAaupCgqyXUaOvZwnRPQYHQsBZyJHbM0yr43OIIaiLxBpo5vR(0mui0hqR66(o1(Sin1G1JXdFohLo85fhYtGtjcIFc2ROMFR1aPlxVzZA2TTA5626a76pzF3PZdTd5v4vkQOJFN4O1AMgBDKBJ6nR93t7KW6Thh)YmmnyWHV392yRTZRoTIj6)M5HHAb9LN6NjLmAlG7dJUJ1WnW0oY4BySFwLnslS78oJEy8jZqIT0kJnM4eGsWlAse3ysWlOyHyrJMge48YMayb9fmp2pgt6elFTvcdf(RCcTdNLLw1UBwIKSUTrYZIJiHEP3qp532xVuGe2gxStqDhlnPDDFbC5e8sQtkBMmcsqcr(InTEpFjKvuzvqVTr36kM1b78KAaq6kZwS8FCVNLaA(6BnMBi96gMLED)uGgcVhTsnRMlpC2g74rikPRz7XduFWEWe(JohJeyhj30uxA6SLlT1RoH1nGZcfd12ODU6rwDreQ5IQFCj1pP(z1Vah)W)nI1RySULMeXHvdGZbo5IJLSGtZhOVzP2JwJeAdJ7zc73qOTrjPXOdx8EBS9L5mQ90oqhzFNDTRvRPpKprKoL3kJeozF2ZA27HB(4T3h2QvSDm96ZQv9a0JjceWPdJT7zM8gRlhsEtzcHMp2dsLv99QiSV)gBUX)RYP)1X)d`

**Slick Ice(6823)**
```
[23:04:02] Dump: value=GetInventoryItemLink('player', 7), GetItemInfoInstant(GetInventoryItemLink('player', 7))
[23:04:02] [1]="|cffff8000|Hitem:173246::::::::60:64::64:5:6823:6717:6649:6647:1507::::|h[Gefrierbrand]|h|r",
[23:04:02] [2]=173246,
[23:04:02] [3]="Rüstung",
[23:04:02] [4]="Stoff",
[23:04:02] [5]="INVTYPE_LEGS",
[23:04:02] [6]=3552762,
[23:04:02] [7]=4,
[23:04:02] [8]=1
```

**Glacial Fragments(6830)**
```
[23:04:51] Dump: value=GetInventoryItemLink('player', 7), GetItemInfoInstant(GetInventoryItemLink('player', 7))
[23:04:51] [1]="|cffff8000|Hitem:173246::::::::60:64::64:5:6830:6717:6647:6650:1507::::|h[Eisbringer]|h|r",
[23:04:51] [2]=173246,
[23:04:51] [3]="Rüstung",
[23:04:51] [4]="Stoff",
[23:04:51] [5]="INVTYPE_LEGS",
[23:04:51] [6]=3552762,
[23:04:51] [7]=4,
[23:04:51] [8]=1
```

**Comment by InfusOnWoW** [comment]
Your have enabled a load option that limits when the aura is loaded.

**Comment by tehmilcho** [comment]
OMG .. im so stupid .. sorry and Tanks a lot.
