### ISSUE TITLE
Text Aura not displaying with Always Active Trigger

### ISSUE THREAD

**Issue by Crelam** [WeakAuras/WeakAuras2#2955]
## Describe the bug

I have a text aura I use as a label for some values, its set to simply use the Player/Unit Info > Conditions > Always active trigger.  Under the latest alpha, it does not display.

**Do you have an error log of what happened?**

```plaintext
No Lua Error
```

### To Reproduce

Make a text aura with any static text, use the Player/Unit Info > Conditions > Always active trigger, close the options and note that the text does not show.

I have made an example for your convenience: https://wago.io/WiesSNhO6

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

Alpha version 3.1.9-37-g62029a4
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

I believe it was working with alpha 3.1.9-28-g99622d5.

**Comment by Sensorzp** [comment]
Same bug. All of my text weakauras stop working after last update.

**Comment by InfusOnWoW** [comment]
This should be fixed now.
