### ISSUE TITLE
Aura Icon now showing up on Combat Log Aura Event Trigger

### ISSUE THREAD

**Issue by MarkoRacz** [WeakAuras/WeakAuras2#2959]
## Describe the bug

I've tried to create a WA which shows the icon of an aura applied to the player, but the correct icon does not appear on show, only the "question mark" icon.

### To Reproduce

Trigger
 - Trigger Type: Event
 - Event: Combat Log
 - Message Prefix: Spell
 - Message Suffix: Aura Applied
 - Destination Unit: Player

Display
 - Icon Source: Dynamic Information

**Screenshots**

https://streamable.com/h15am7

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

3.1.4

**Are you on World of Warcraft Classic or Retail?**

- [X] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Haven't tried.

**Comment by mrbuds** [comment]
Can you try again with WeakAuras 3.1.9 ?

**Comment by MarkoRacz** [comment]
I feel dumb for not updating, but the issue is still present in 3.1.9
