### ISSUE TITLE
Individual categories for SharedMedia sources

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#2964]
**Is your feature request related to a problem? Please describe.**
The amount of dropdown elements keep getting bigger and lack structure.
It's one of the reasons why I don't just add all sounds to my SharedMedia addon that I find useful.

**Describe the solution you'd like**
I guess the initial thought is to give each sharedmedia source its own catagory based on addon name
Additionally it would be neat if sharedmedia authors had the option to add more sub categories, e.g "HealCDs", "Personals" etc.
That would allow me to go crazy on sounds.

Example:
![](https://i.gyazo.com/599d64d2aefadbab8064f7fb69d111b2.png)

![](https://i.gyazo.com/8245dc83ac404a891a52d18c40e7a26a.png)
**Describe alternatives you've considered**

**Additional context**

**Comment by InfusOnWoW** [comment]
But LibSharedMedia has no categories at the moment? So what do you expect us to do here?

**Comment by Causese** [comment]
ok ill knock at their door then
