### ISSUE TITLE
4th arg on Duration Info (both code box and SetDurationInfo() function) doesn't apply inverse.

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#297]
***What steps will reproduce the problem?
Make a new progress bar aura using custom - status - every frame. have the trigger always return true
Use the following in the Duration Info:
```LUA
function()
    local tick = GetTime() %10
    if IsMounted() then
        --WeakAuras.regions[aura_env.id].region:SetInverse(false)
        --WeakAuras.regions[aura_env.id].region:SetDurationInfo(tick, 10, true, true)
        --return tick, 10, true, true
    else
        --WeakAuras.regions[aura_env.id].region:SetInverse(true)
        --WeakAuras.regions[aura_env.id].region:SetDurationInfo(tick, 10, true, false)
        --return tick, 10, true, false
    end
    return tick, 10, true
end
```

Or import: https://wago.io/BkC2wnSCb

***What is the expected output? What do you see instead?
You can see the different things I tried in the commented sections. Basically returning the 4th arg on SetDurationInfo(), or on the main return from that code block, doesn't change the direction of progress. SetInverse() always works reliably. 

***Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
No
***What version of WeakAuras are you using?
alpha - 2.4.23-14-g905598c
***Was it working in a previous version? If yes, which was the last good one?
Not sure tbh.

**Comment by emptyrivers** [comment]
Heh. It didn't even occur to me that this might be not the intended behavior.

**Comment by asakawa-k** [comment]
SetDurationInfo() was a reliable way to invert the progress and I made wiki entries to reflect that. I think it was when SetInverse() and the Conditions stuff were added that these 4th args stopped working but that's just a guess.

**Comment by InfusOnWoW** [comment]
Should work now in the latest alpha.
