### ISSUE TITLE
Regression: cannot create school based debuff trigger

### ISSUE THREAD

**Issue by kuhma** [WeakAuras/WeakAuras2#2970]
Before

![image](https://user-images.githubusercontent.com/16953334/110616965-705a2c00-8195-11eb-83b9-28eb5ff8b5ad.png)

After
![image](https://user-images.githubusercontent.com/16953334/110616995-7819d080-8195-11eb-98e8-6ad7c7541bce.png)

Regards

**Comment by mrbuds** [comment]
I don't have this issue with version 3.2.1
![image](https://user-images.githubusercontent.com/189656/110819642-aaf3bf80-828e-11eb-818f-17c6c756a2d4.png)

If you can still reproduce it open a new ticket and answer all questions asked in the template, a ticket with only a screenshot is not enough most of the time.
