### ISSUE TITLE
Regression: cannot create school based debuff trigger

### ISSUE THREAD

**Issue by kuhma** [WeakAuras/WeakAuras2#2972]
## Describe the bug
Debuff type is no longer available in aura triggers.
Any previously created weakaura relying on debuff type are broken and are working as if only tracking a debuff is active.

**Do you have an error log of what happened?**
No

### To Reproduce

1. Click on "New Aura"
2. Click on "Trigger"
3. Select Type: "Aura", Unit: "Player", Aura Type: "Debuff"

Debuff type is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/16953334/110616995-7819d080-8195-11eb-98e8-6ad7c7541bce.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
3.2.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes: 3.1.9

**Comment by mrbuds** [comment]
Citation from Discord
>  Vardex: In the screenshot we don't see what did he put for "show on"
Vardex: It doesn't work on show on missing and always

**Comment by kuhma** [comment]
Thank you for your quick answer!

"**Show on**" was set to "**always**", as per default.
After reading your comment it is logical and I feel stupid (despite it working in previous versions). In the same way other options should not be visible as well.
