### ISSUE TITLE
Burning Wound Legendary Bonus ID wrong?

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#2973]
## Describe the bug
I use a weakaura to track my current equipped legendary and It looks like the bonus ID in the tooltip for the Demon Hunter Legendary Burning Wound is wrong. I use the bonus id "7052" as it is refered to this Legendary in the tooltip. 

### To Reproduce
Get this weakaura https://wago.io/uxB9n4AjS or create a trigger Item > Item bonus id Equipped >"7052" and tick fetch legendary power. Then have the Burning Wound legendary equipped on a Demon Hunter (on the chest in this case as you see on the screenshot). Then the weakaura doesnt trigger for me, if i inverse it it does,

I am using the most current version, 3.2.1
![fyUmH9n](https://user-images.githubusercontent.com/51278436/110890792-fd65c800-82f0-11eb-806b-085f26bc7147.png)
![Jmko5lE](https://user-images.githubusercontent.com/51278436/110890807-03f43f80-82f1-11eb-8190-6ca9c2ecbb74.png)

**Comment by InfusOnWoW** [comment]
Apparently Blizzard changed the bonus id of 3 legendaries in a patch. The correct bonus id is 7219. We'll fix the tooltip in the next release.
