### ISSUE TITLE
Aura animations causing frame drops

### ISSUE THREAD

**Issue by FaleWhail** [WeakAuras/WeakAuras2#2975]
I was experiencing frame drops whilst in combat. I had animations set to shrink/grow my auras when they appeared and disappeared. I created a performance profile as per asakawa on the discord and uploaded it here: https://pastebin.com/V6APTMS7 :another mod, Spaten, then suggested I remove all the animations and that fixed the issue immediately. 

As above, the auras were intended to shrink and grow when they appeared or reappeared. As far as I remember this behaviour still occurred, but once I disabled those animations completely the issue was resolved. 

**Do you have an error log of what happened?**
I do not, but I created a performance profile linked above.

### To Reproduce

I use numerous weakauraas and tested in dungeons by setting load to 'never' on each of them. I quickly identified that the issue only occurred when one group was active, and this was the only group to contain animations. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, I disabled everything and went into a normal dungeon with only weakauras enabled. 

**Which version of WeakAuras are you using?**
3.2.1

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

The issue began after I updated Retail with 9.0.5. The issue only occurred on this character and other characters with animations in the same HUD groups that I utilise. 

### Additional Info

I have archived the auras here: https://wago.io/wAPf3avvk. I no longer use the animations in game but these still have them included. I've set the link to never expire but it is hidden.

**Comment by InfusOnWoW** [comment]
I can't reproduce any issues with that aura set. 

A severe frame drop is likely caused by lua errors and you should follow the instructions in the new bug template to install the bugsack/buggrabber addons.
