### ISSUE TITLE
Inaccurate GCD tracking

### ISSUE THREAD

**Issue by Kuurse** [WeakAuras/WeakAuras2#2984]
## Describe the bug
The global cooldown tracking seems to be inaccurate for me: auras that either track GCD (triggers -> Spell -> Global Cooldown) or have the GCD indicator activated (triggers -> Spell -> Colldown -> Show GCD extra option) are "shakey" at high haste levels. It's a bit hard to describe but the GCD sweep goes back and forth without ever finishing the whole progress/sweep. It happens way more often at high haste and the higher the haste the more erratic the sweep becomes. 
You can see it in effect in this video at 3:28, the Devouring Plague and Shadow Word: Pain GCDs are acting up:
https://youtu.be/HODj8oiGiXA?t=200
It's most obvious with a progress bar like in the video but the effect is the same with the cooldown sweep effect. I also have tried with and without "Smooth progress" for the progress bar to no avail.

**Do you have an error log of what happened?**
No visible error message.

### To Reproduce
Have any aura track a skill with a GCD indicator enabled and increase your haste (Bloodlust + Power Infusion is enough) and look at it.

**Screenshots**
https://youtu.be/HODj8oiGiXA?t=200
Shadow word: Pain at 3:27 is a perfect example of what I am describing.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
v 3.2.2

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**
I don't know

**Comment by mrbuds** [comment]
The shadow word pain aura i see doesn't show any gcd, and devouring plague always glowing is not cleanly readable on your youtube video, maybe i'm not looking where i should, can you show clearly what should we look and add an export of those auras ? (preferably only those bugging not the whole package)

**Comment by NathanCrama** [comment]
Sorry, I should have clarified: The cast bar shows (or should show) GCD usage, that's where you can see it going wild. I'll post an export as soon as I get in-game.

**Comment by NathanCrama** [comment]
Here I have made a tiny WA group (the red bar and the 3 icons) to replicate it and re-recorded a short clip showing the problem. 
You can see it especially well if you look at the gcd on the vampiric touch aura, the swipe "bounces" for a lack of a better word. 
https://youtu.be/Y_jE1MGWsow
```
!WA:2!fF1ZZTTX1FJbnUoyQtfL)vu(HnJ6uh74AfhMyNMMX1HqI0KouK0au)Y1nK4hljwBqa4fasIkn9BKMmjQxvNERh6WJD60d8yVup6wV9goDYHEu)d0z0PVh7Bxqq9d7KojxQMrGyF7B3992pFE)aslozO27otUzYnz3jTN0E7xFOPH1JTz(bZ676ZUNSSCD5BmZn3Z0NztyQJMmycvx6gByWSZ2W33nIg0pY3AvclK679Ysn)dS1R1UDijQ0tF1l)0tG)zMSboSEPteA)VAHtmWWZYXNv3N6fzoBHQnkO1prxD6gKxyqY7jwJKKK8qJ4iu)Abr4rfQStiXTTyXGcZWsi8wAHrgSifZ2upAOJIk(tKYwrmANoOj(kxMn61VSVnXmUD7g9ciSsfQuV4cvuJWbAgXmJCBfgqCDlBhQSxySjzvIxKoQnD9bnNnVEJM6nYR1qng3CZaxJEeMMNrxsOIMqvZsed3iNXlToJGlvtVEHkv2j2BKjOmYzly3HeKr)jXgms2IXUUzxYHgr2nz2K7SxSpJ0bDqU5Q1H5hhSJHhTRb3PVfmrXDjgHe9igXRtKZpeUGQNVhzOn6kCnAYDmwiXY3ZoClUQ89bUMAxdQxr4TWfaxd(zW1HzWFZCCjttT36UZo31vJ7Kt113WUOzKHl6xNxRBmYauuXBlRZdVRIMLRryi)n1qec5VmOndVzqtZiYqE)eeVixe3em1NvRqHQJq6YEONkBIwzBAhfTql8qK7JxIAcFpuzFeRjmpd3ftOBR0N7r0e6WaQxBFwYvIsUyQ9G534bRTE5Ilu)r5M06EBpDFkQUUFmZI8ANaozPpQ(F7gCckCQspT4)4VkE9fbLHwiV22Fnp91ObKw7MoKJtoQ89OfCMx6YWz3Ecn0TSESkYl9HlOj4m7iEwfDWtDP)i8kWRcxkyQzhTfzRZ87WiHHzVIoxTRgKjoK0SdXJWOw6o(RvZR1WJmSFi(tE31m6fcxuzaxDUKow2TgkgKECTGPuGxdED4nGPhYqcOE6m9NN6zNvfHMOD4lry0TGZbNh(jkbz4HoRsAKqkN33M8xob8lxz)htib55aBKg)o1bEjqbdAcnI4SkIdC73A7Zgmzez9i0Imq3B5eUQuWucHIhjqsZWrVaxBNXZn9pnmyIdT8dc03lrAA4TA(fAul4mcH8RAogBTe1oYrnpoC)KdIUoXwiCZHjSSvgzo7kM)rXHr029qFG5hH2FduOA1AvlaxGHumUo9fkALM9tENrEGxuWefz0nYE)ydBopoBJghXXtpPHczRHK5LygbBT0OxsmGvPHutxsRr(8HY9fKPC1Qf0AQwRrJAZRv(ULAmC8rZtfo1ipA5JCo8zfPVQTqJkLRw4Rh2X1FTImYtIjEw9Q)dUXm5UzI3XNya)r6oSfFaFXdnJJI89QHjWX8y95IRisICoH(PE2o8bJRliVlsJUBQehv(KoItVHd16XEibxwScDriS41kuuCgXbOMupW0Hq74eTj8ofHC8ufW7jEEtXZBjE(MqrT1eGkCvEEUJNR6T)VN9c(if1n897kb)yChuGmkWKkWlWlvHj2gEqSr2ooAha(W7ld)C4dG8d(4OpG221t3OCj4dvyupEXoItWzttmWPsZrdnq012rZWnWXqgUJYwPZ3coTY2tdZIjD(IK9(OjCG5AbfCgzEtkSWr5xG7cLqFPSiUwKlb(yOslyEOkpmhQ1cQlI7VOcCVxw(t)ZW93zrFk6qyLzqpnghAicPHfebXWIjXUWssWY49ZkyGi8arGh8RGhc)A4tGMBcTKaduztWcTaBGKy5THoGJeqHhbykexOl4nf4lbbWt(AGLY5Gqydhigwfw7CW6sqVKfhjbFQd8zYWVrg(TzG)ph4ZfO)TEg0pxk6pc254jcRhc2pMKmpJKtRa)UwWwsWx5mgT3vC5yIxoiyJva(7)7tEcbkSTmS5Mi6IWDXhOo36UrVZCb1HV0jLgChfKhbfBnchpzPNw)))9oO4XGNlwMq1oowYbUJHLC49Wyjh2U)ElA0nGIfcWgTITC4W59o12M)pcprS7zWteJr8ebZp7O453s0mhwk2IFx(vI72uKz6fBKgCKGf5hORVMzPRW6UCLNWrgel4abcO3rGSFFZhS9B3pmWG9yrTIZjqZtjjQ7leRXRoGTqifK5iJ5fgXlZIoWz(eoEMHJN7XlNAyg6Zm5ZJG5EHIQ2Pf8fGnhnVaIXcqxDwmvdCpj4(shG3C8hPc6T2IVH82kBHWCcTbvfznIc)PPE2hhuyDSUTEsxQTehJGl975B34TECAJ9XS1MgUzhBxJZnmWMg(Oyprpa5m86X5wIgLouHqoxdjABzAmQBCzo3ArNDf3qjLiwrcU9Va9Zb8(NrfBI)V9fcEJNPvGGMr0UKMbmIfL3eNmNWg8DIWgOwfBVfCqOZ)aUB)KQOvkuSrWf)Mo2KrpVwucg9IgxpBmmi4QFtBIDpSBFQvZihSxoh8gThSKmpau4lEF3c(qNi1dgK4bIoaWiW)usS4ZXw9g3of85x6BjIBpbaPI9QBZ5N5Yp3CbtGKN8282Hi2e75nw3zGqRsuBBINw1clwq77FX2dL474Ne1ZbEt2i6bCsPdZEwwAhbNlKAt0s8)pujrbE11ygj4kL5n)32WI8qEie1RJQb7Hlu(6hm6668fmYDenxCBwuYYnZZ66Z6HPvwzJ5P1QuWFH6umzIMq5dQqOIFOtwyZV4hXtdXZ38(YjPloO5hEMOtRmWNrXpbsKBOFPAALFqTQnYxjPqX(8pLM)zAE2J7Qv8X0tU6)C5)d
```
