### ISSUE TITLE
Instance Type Missing PvP Battlegrounds / Arena

### ISSUE THREAD

**Issue by ForsakenRealmz** [WeakAuras/WeakAuras2#2985]
The Instance Type under Load does not have an option for Battlegrounds or Arena.

**Comment by InfusOnWoW** [comment]
Yes intentionally.

**Comment by ForsakenRealmz** [comment]
> Yes intentionally.

Hello,
What's the suggested method to only have WeakAuras appear in Battlegrounds and Arena if this is intentionally not included in Instance Type?  I've been researching this online and old forums say it is in the Instance Type.

**Comment by InfusOnWoW** [comment]
There's a instance size type load option for that. (Which is badly named and has some additional hacks.)

**Comment by ForsakenRealmz** [comment]
> There's a instance size type load option for that. (Which is badly named and has some additional hacks.)

Awesome man.  I thought I looked through everything, but clearly not.  Like I said, everything online is mentioning the Instance Type, but I'm happy to finally find this.  There is a Feature Request posted to make this same functionality in the Instance Type.  Can probably respond to that and say that Instance Size Type is where we should look.
