### ISSUE TITLE
Error caused by Aura showing pet health

### ISSUE THREAD

**Issue by livinhd** [WeakAuras/WeakAuras2#2987]
## Describe the bug
BugGrabber popped an error with the following WA https://wago.io/8KnH9fmY3
I was requested to make a Github ticket by a member of the WeakAuras discord.

**Do you have an error log of what happened?**
https://pastebin.com/j8CHBhpi

**Which version of WeakAuras are you using?**
WeakAuras-3.2.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Comment by InfusOnWoW** [comment]
This is fixed for the next release.
