### ISSUE TITLE
Addon Broke. No longer showing Cold down Text

### ISSUE THREAD

**Issue by ivrae11** [WeakAuras/WeakAuras2#2988]
In all my addons with all my characters I have the text to show cold down count down. Last night for some reason it broke and ALL my weakaurs created with a cold down text; just wont show up. 

I have hundreds of weak auras that have a cold down text, and they all now won't show up?

Is anyone else having this issue or may know what happened?

**Comment by SpatenLa** [comment]
WeakAuras Icons can provide multiple text frames via the SubElements section in the Display tab, that can show a duration progress value. Aside from those there is a text that is attached to the "Cooldown Widget" ("spinner"). That text can be shown/hidden globally by use of the Blizzard Interface setting Interface > Actionbars > Show Numbers for Cooldowns. If the Blizzard option is enabled then WeakAuras is able to override that on specific Icons and so will show an option in the Display tab, under Cooldown Settings, called "Hide Cooldown Text". If the Blizzard Interface setting is disabled then that text can not be shown on specific Icons so the Display tab setting will not be shown to you.

Separate to the relatively simple relationship between the Blizzard setting and your Auras is the fact that addons (most commonly OmniCC and possibly ElvUI) can override the Blizzard setting themselves. If you have an addon doing this then WeakAuras is not able to affect the text at all and so the Display Tab setting will, again, be hidden.

**Comment by mrbuds** [comment]
As Spaten explain, it's not a bug in WeakAuras addon

**Comment by ivrae11** [comment]
@SpatenLa I apologize, I didn't mean to report it as a "bug" more or less ask the question if anyone had some input on how to resolved; this worked! It must have "un-chucked" itself for display text to stop showing. 

I appreciate the swift response and solution to this!
