### ISSUE TITLE
Weapon Enchant Trigger doesn't work on deathknights

### ISSUE THREAD

**Issue by Allenone1** [WeakAuras/WeakAuras2#2990]
## Describe the bug
Trigger > Item > Weapon Enchant / Fishing Lure will never trigger for any death knight runeforge enchants.

### To Reproduce
Simple show text weak aura with trigger: Item > Weapon Enchant / Fishing Lure. tried the following: 

- Fallen Crusader
- Rune of the Fallen Crusader
- Enchanted: Rune of the Fallen Crusader
- 3368

**Which version of WeakAuras are you using?**
3.2.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Comment by SpatenLa** [comment]
Vardex — Today at 14:53
Because it's not a temp enchant but a simple enchant use bonus id

**Comment by Allenone1** [comment]
> Vardex — Today at 14:53
> Because it's not a temp enchant but a simple enchant use bonus id

ah, got it thanks. I guess I was mislead a bit by the trigger name. I had also tried asking in the weak auras discord and got no reply. I figured since no one knew why it didn't work or provided a working response it had to be a bug.
