### ISSUE TITLE
since lat update

### ISSUE THREAD

**Issue by okdtoker** [WeakAuras/WeakAuras2#2991]
there is now a bar across the middle of of my screen that I cannot move, change or use in any fashion. all it does is display a single buff I happen to have or that i have summoned my mount. how do I get rid of it?

**Comment by InfusOnWoW** [comment]
If it is from WeakAuras, it's a aura you have created and you can get rid of it by deleting it.

**Comment by okdtoker** [comment]
I finally figured it out, and NO it popped up after an update it is really hard to figure out what wa actually does, so I had not touched it until after this weird thing made itself annoying.  Why do you make it so it cannot be adjusted anyway?

 

Thank you,

Anthony DeZurik
