### ISSUE TITLE
Error decompressing

### ISSUE THREAD

**Issue by Lyubo99** [WeakAuras/WeakAuras2#2993]
![image](https://user-images.githubusercontent.com/81156601/111970832-6674e900-8b04-11eb-9e46-bf37a0feb7ed.png)
I tried using this weak aura from wago.io ( https://wago.io/29b1FBZtK ) and many others and I get the same error.Reinstalled weak auras , updated them ,deleted WTF folder and the same error happens again.What can I do to fix it?

**Comment by SpatenLa** [comment]
![grafik](https://user-images.githubusercontent.com/39881841/112022558-b66aa480-8b32-11eb-8f55-387ffd2b1dae.png)
came into discord, got told he has a virus can be closed
