### ISSUE TITLE
Weakauras causing disconnects upon logging into character

### ISSUE THREAD

**Issue by Rynocat** [WeakAuras/WeakAuras2#2994]
## Describe the bug

Similar issue to the one found [here](https://github.com/WeakAuras/WeakAuras2/issues/2720). To restate, upon logging into my character, I will be disconnected from the game. Only occurs to me on my druid - my main toon.
**Do you have an error log of what happened?**

No error log

### To Reproduce

Log in > disconnected from game

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes
**Which version of WeakAuras are you using?**

3.2.2
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

Yes - I believe the issue started after 9.0.5 but I am not certain
### Additional Info

Attached my savedvariables weakaura files as I'm unsure which aura is causing the issue
[weakauras savedvariables.zip](https://github.com/WeakAuras/WeakAuras2/files/6201081/weakauras.savedvariables.zip)

**Comment by mrbuds** [comment]
I don't have any issue logging into a druid with your SV, loading time doesn't seem excessive.

**Comment by Rynocat** [comment]
To add, there are times where I am able to log in with no issues, but this problem seems to come and go without me changing anything.

**Comment by InfusOnWoW** [comment]
What makes you believe that it is a WeakAuras issue?

**Comment by InfusOnWoW** [comment]
I have logged in several times with your settings and had zero problems.

We would need a reproducable way to trigger the problem, if it is a WeakAuras issue.
