### ISSUE TITLE
CANT MOVE WEAKAURAS on my screen

### ISSUE THREAD

**Issue by Highscore01** [WeakAuras/WeakAuras2#2997]
Hello there is soft problem there , with me and couple other people that i talk to , we cant move Weakauras on our screens like we used to by holding mouse and drag it anywhere u want . It is locked now... please fixxxx <3

**Comment by mrbuds** [comment]
Looks like you locked auras position, click on this 
![image](https://user-images.githubusercontent.com/189656/112567948-002ce680-8de2-11eb-91a7-23bdc04435cb.png)
