### ISSUE TITLE
Auras loading when they should not

### ISSUE THREAD

**Issue by mgmolisani** [WeakAuras/WeakAuras2#2998]
## Describe the bug
Auras are loading when they should not be. The aura runs its init script, it is in the loaded section of the UI, however, its "loaded" tooltip does say "Not Loaded" and is greyed out as expected. I would expect the aura to be in the not loaded section and not run its init script.

**Do you have an error log of what happened?**
No Lua errors

### To Reproduce

1. New aura
2. Text
3. Load
4. Optionally add an init print('hi')
5. Set In Combat to selected
6. Observe that aura is in the loaded section, runs its init, but visually does suggest it should not be loaded

**Screenshots**

![image](https://user-images.githubusercontent.com/37375674/112710569-96234880-8e98-11eb-8c8f-1c4b4abcd8b9.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, I did test it after reading this and it created the same results.

**Which version of WeakAuras are you using?**

3.2.2

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [X] Retail

**Was it working in a previous version? If yes, which was the last good one?**

This is the first time I have observed this.

**Comment by InfusOnWoW** [comment]
All of that is as expected.

The only gurantee for the init function is that it is run before any other code from a aura runs. The assumption that only the init function of loaded auras are run is simply wrong.

Users generally expect In Combat Auras to be listed under Loaded, that's why they are there.

**Comment by mgmolisani** [comment]
Understandable then if it is intended but I guess I am missing then what the point of saying In Combat to load the aura vs In Combat trigger do and what it means to initialize the aura. My interpretation has always been loaders lazy load when the aura starts and initialize when those loaded conditions are met and that triggers create the show and hide conditions. It also leads me to ask what the difference is between the loaded section of the auras list and loaded auras per the icon/tooltip based on the photo provided. Again, if I'm just misunderstanding, that's fine and I would just like to make sure I can work with what I have correctly.

**Comment by InfusOnWoW** [comment]
The exact circumstances that init runs are not specified beyond what I already explained. Though noteably to show a aura in the Options runs the init code, triggers, conditions and other things.

**Comment by mgmolisani** [comment]
What would be the prefered way then to initialize a condition on the first loading of an aura? I was under the impression init only ran when the load was valid but given this new understanding, would my option be to add additional "silent" triggers that only exist to cause initialization/reset side effects?

Example: Simple Counter - Counts each time a debuff is applied during combat.
How I thought it worked:
```
init:
aura_env.count = 0;

on show:
aura_env.count = aura_env.count + 1
```
How it actually works: Do I need to now listen to combat enter/exit for build up/tear down? Where does that work happen (custom trigger, condition custom code, abuse custom text/animation)
```
???
```

If this isn't the forum to ask, I'm happy to put this question now wherever it best belongs.

**Comment by InfusOnWoW** [comment]
This is a bug report, not a help forum.

init is run exactly once, not every time a aura is loaded so clearly it won't work for what you want.
