### ISSUE TITLE
Error Message for a custom Script can point to the wrong aura

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#300]
What steps will reproduce the problem?
Import the following aura:
```
d0JEhaGAjj2LKIxdjshMuZuiyzqsZMK)ku3usvNNk13Oc1PvzNuj7fTBr2VuLFsusdtkvJJkq3siAOqIyWsfdNihukLtjeYXiQoNqAHsLgfrPSyjvwUOEOuvpf8yc9CQAIcHAQQAYemDLlkjPxruINrf56qTrjPUQKsBgsTDP4Jub5ZqmnjX3PczKeLQltz0efJhs4KqI6Sub11OI6EubCBb)wITjLmLZNGMphbpHi2AmvrkyPriqqGGaFccNVk4K4UgJGwPiKnKRKE3sgbKCblrqlURX(8HGy56lcgDfP82jyOqsNemb2LWjqOomsVocwOqWBk0OKYLgHUY6)YA9rOQv)es4WNpeel7Pl5eufTaFctRS0qLpHawTJphhHPvwA8jeWQD854iKlkJpHawTJphhbHdn6teRMB(ecy1o(CCeYArJpHawTJphhHlHKlyj(ecy1o(CCeKAKMwzPXNqaR2XNJJaAT4UsIpHawTJphhbS3IfvAVN1XXrqKpDjNpbT4Ug7ZhcILRViy0vKYBNGwCxj55tWpDE8jiuIfX(vcSlbrSFLabP8LMSPXzDSLAQXp9SA8sMsHYc96il96OXzDSLAQXxWzrZLoyrehhHtGGu5sZe61Xr5scHGW5RcojURXiOvkclFiiwMpHG59AelUizz9kzcoGdqa7T4G59Ae7DlzSlbVKPuU0bJaOkoQxNQ1kfH5wYiynwAeeLXerPeWsc6zeWjRXsJWUGjqWJRZAS0amA0hkie3Vn4JHA73VQaqqe7xjelZjye2fmbcwJLgH(LqD61RtekiecM3RrmczDsOe61XV8LqiG9wSxYukx6GXUeWEl2xWzrR20n2La2BXbZ71ig7sqe7xjep3sgb)0d7j4l4SOvB6gbjL2TLjemVxJyVBjJqFzVTpUEWHIH2Cyoco6eMmS6wYJIAfNDWwYRuXPOrDQfrhzLOes4WNpeel7Pl5eKXoezgRULJD2zNIwPv7rrvUJD2PweDKvIsqv0c8jmTYsdv(ecy1o(CCeMwzPXNqaR2XNJJGWHg9jIvZnFcbSAhFooczTOXNqaR2XNJJqUOm(ecy1o(CCeKAKMwzPXNqaR2XNJJWLqYfSeFcbSAhFoocO1I7kj(ecy1o(CCCeYgYvsVBjJWmumo6cv(e0I7ASpFiiwU(IGrxrkVDccNVk4K4UgJGwPiOf3vsE(e8tNhFccLyrSFLa7sqe7xjqqkFPjBACwhBPMA8tpRgVKPuOSqVoYsVoACwhBPMA8fCw0CPdweXXrqg7qKzS6wo2zNDkALwThfv5o2zNAr0rwjkHLpeelZNWClzeSglnc4K1yPryxWeiynwAe6xc1PxVorOGqa7T4G59Ae7DlzSlbS3I9sMs5shm2LGhxN1yPby0OpuqiUFBWhd12VFvbGa2BX(colA1MUXUeeX(vcXYCcgHDbtGqW8EnI9ULmc9L92(46bhkgAZHj4l4SOvB6gbjL2TLj4LmLYLoyeIG1CtpJJGJoHjdRUL8OOwXzhSL8kvCkAuNAr0rwjkHeo85dbXYE6soHtGGwCyTQxhlNlzcx6wSF68mb6sobvrlWNW0klnu5tiGv74ZXryALLgFcbSAhFoocchA0Niwn38jeWQD854iK1IgFcbSAhFooc5IY4tiGv74ZXrqQrAALLgFcbSAhFoocxcjxWs8jeWQD854iGwlURK4tiGv74ZXXriBixj9ULmcZqX44i0qxYRGQCosa
```
Then, while on a priest, cast Levitate (this can in principle work with any class in any situation, I just happened to be on a priest while making this test case).

To reproduce this cleanly from scratch, edit multiple codeboxes from different auras at the same time, introducing the same error to each. The aura at the top of the list in the WeakAuras Options Pane will be blamed for any errors.

What is the expected output? What do you see instead?

Since "pointed wrong" only triggers on Void Bolt, it should not trigger. "actual error" triggers on levitate, and runs the broken code. I *should* get an error along the lines of: 
```
1x [string "--[[ Error in ' actual error' ]]return fun..."]:1: attempt to perform arithmetic on field 'sourceName' (a nil value)
```
Instead, I get:
```
1x [string "--[[ Error in ' pointed wrong' ]]return fun..."]:1: attempt to perform arithmetic on field 'sourceName' (a nil value)
```
Full error message [here](https://pastebin.com/rPuMfZDX)

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

Of course.

What version of WeakAuras are you using?

[ed8d063](https://github.com/WeakAuras/WeakAuras2/commit/ed8d063d4a413f6baa17cb607389ffd8794ce3bf)

Was it working in a previous version? If yes, which was the last good one?

No idea. I suspect not, however.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

See above.

**Comment by InfusOnWoW** [comment]
So, that took a bit to figure out...

It's only blaming the wrong aura, if both aura contain the same code, and that's because we have a cache in WeakAuras.LoadFunction() which uses the original string without the comment and thus reuses the function. I think that's actually a good idea, since that means that same code (e.g. animation code) gets reused. If we added the id to that, that wouldn't happen.

This can make debugging a bit harder, since it might point to aura that only has the same code, but I think that's a acceptable trade-off. If you change the first aura it points to, the next error message will point to the next aura.
