### ISSUE TITLE
Bug WeekAura

### ISSUE THREAD

**Issue by Michel1985-Mich** [WeakAuras/WeakAuras2#3003]
## Describe the bug

It's been several times that when I log in, all the installed WeekAura disappear
**Do you have an error log of what happened?**
No

Enable and CurseForge already installed
```plaintext
PASTE ERROR HERE
```

### To Reproduce

It's been several times that when I log in, all the installed WeekAura disappear

1. Go to '...'WOW Launcher
4. See error No WeekAura installed anymore

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

ElvUi is installed, but i already had this error before installing it

**Which version of WeakAuras are you using?**

3.2.2
**Are you on World of Warcraft Classic or Retail?**

The lasted
- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### Additional Info

You don't support the LUA file, i can't import it here

**Comment by Stanzilla** [comment]
Need more info

**Comment by Michel1985-Mich** [comment]
Dear support,

I totally agree to add informations if is necessary, But, instead of closed the incident, can you tell me what sort of informations you need please?
Regards,
Michel

**Comment by InfusOnWoW** [comment]
This is either caused by some lua error, for which the bug report template instructed you to install buggrabber+bugsack. Or some kind of computer problem. This is not very likely caused by anything that WA does.
