### ISSUE TITLE
WA 

### ISSUE THREAD

**Issue by beresromanalex** [WeakAuras/WeakAuras2#3009]
Hello. I need 2 skills to be displayed in the same icon, when the dominant skill is ready, so that it shows it, and when it is recharged, then another, in one icon 2 skills in turn, with the advantage of 1, the usual rotation applications are not interesting to me, I try to do this with the help of WA, it turns out this addon can not so?

**Comment by Causese** [comment]
github's issue tracker is for reporting bugs and not for help

you can get help on discord https://discord.com/invite/weakauras
