### ISSUE TITLE
Character specific config file

### ISSUE THREAD

**Issue by toka1408** [WeakAuras/WeakAuras2#3010]
**Is your feature request related to a problem? Please describe.**
I play a lot of alts and I try almost every spec. On each character I import predefined Groups from Wago.io and often one import is only for one specc. During Shadowlands, I imported a few thousand weakauras and I can see all of them on every character. Opening the WA config (/wa) is so slow on every single character, because it iterates over all my weakauras. Because of this, the WA addons feels so clunky and a quick fix to a single weakaura is a hassle.

**Describe the solution you'd like**
I would like to see an option to import weakauras only to a specific character. Just a small checkbox on the Import dialog. Checking the box will save the Weakaura to a character specific config file.
For example: 
1. I want to import a group for a Holy Paladin.
2. Get Group String from Wago.io and import it in WOW with the checkbox activated.
3. The group is saved not in the global config (WTF\Account\\$(AccountName)\SavedVariables\WeakAuras.lua). Instead, the import is saved to a character specific config (WTF\Account\\$(AccountName)\\$(ServerName)\\$(HolyPaladinCharacterName)\SavedVariables\WeakAuras.lua).
4. No other character than my Holy Paladin can see/can load this WA group.

**Additional context**
a) This will reduce the immense size of the global WeakAuras.lua file. 
b) Make sure that during start up, the global config and also the character config is loaded.
c) My request is a feature something like the SaveKeybindings feature in WoW. You can store them on a per character basis, if you want.
d) My request is only considering the import Dialog. To be complete: If you generate a new Weakaura, it could be stored in the global config initially. To bound it only to a specific character, there must be an option to move this Weakaura to a character specific config.

**Comment by InfusOnWoW** [comment]
That has a far too low effort to benefit ratio.
