### ISSUE TITLE
Specialization filter for Player/Unit Info type trigger

### ISSUE THREAD

**Issue by the-isz** [WeakAuras/WeakAuras2#3013]
**Is your feature request related to a problem? Please describe.**
As a healer, I would like to track some tanks' resources in my party, such as DK's Runic Power or Monk's Stagger. This is already possible (Unit="party1", ...), but I can't exclude non-tank DKs or Monks because the "Player/Unit Info" type trigger only allows filtering by class, not by class _and_ specialization, like other triggers do.

**Describe the solution you'd like**
I'd would like to be able to filter "Player/Unit Info" type triggers by class _and_ specialization, not just the former.

**Describe alternatives you've considered**
I don't see an alternative, maybe I'm missing something though.

**Comment by SpatenLa** [comment]
a good alternative would be to filter by the role like "tank" 
![grafik](https://user-images.githubusercontent.com/39881841/114187875-c662f080-9948-11eb-9f81-c9f34c5b856b.png)

its sadly not so easy to get the spec of another player.

**Comment by InfusOnWoW** [comment]
What Spaten said.
