### ISSUE TITLE
taint.log entry

### ISSUE THREAD

**Issue by filliph** [WeakAuras/WeakAuras2#3016]
## Describe the bug
The taint log captures some issues from WeakAuras.

**Do you have an error log of what happened?**
```plaintext
4/11 18:16:06.709  An action was blocked in combat because of taint from WeakAuras - <unnamed>:SetWidth()
4/11 18:16:06.709      Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua:1309 <unnamed>:Scale()
4/11 18:16:06.709      Interface\AddOns\WeakAuras\Animations.lua:276 Animate()
4/11 18:16:06.709      Interface\AddOns\WeakAuras\Animations.lua:156
4/11 18:16:06.709  An action was blocked in combat because of taint from WeakAuras - <unnamed>:SetHeight()
4/11 18:16:06.709      Interface\AddOns\WeakAuras\RegionTypes\AuraBar.lua:1323 <unnamed>:Scale()
4/11 18:16:06.709      Interface\AddOns\WeakAuras\Animations.lua:276 Animate()
4/11 18:16:06.709      Interface\AddOns\WeakAuras\Animations.lua:156
```

### To Reproduce
I don't know specifically what to do to replicate it, unfortunately :(

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I do have a bunch of other add-ons enabled, but only WA appears in the stack trace.

**Which version of WeakAuras are you using?**
3.2.3

**Are you on World of Warcraft Classic or Retail?**
- [ ] Classic
- [X] Retail

**Comment by InfusOnWoW** [comment]
That's usually due to clickable auras.

**Comment by filliph** [comment]
How do I check if I have clickable auras installed? I don't believe any of them are interactable.

**Comment by InfusOnWoW** [comment]
There's no convenient way to do that, though you could search in the WeakAuras.lua for any "CreateFrame" calls.
