### ISSUE TITLE
Failed on load.

### ISSUE THREAD

**Issue by Nevering** [WeakAuras/WeakAuras2#3019]
## Describe the bug
Not fail

**Do you have an error log of what happened?**
Message: ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1076: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
Time: Tue Apr 13 00:36:25 2021
Count: 1
Stack: ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1076: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\WeakAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua"]:1076: in function `activate'
[string "@Interface\AddOns\WeakAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua"]:1121: in main chunk

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "PLAYER_TALENT_UPDATE"

```plaintext
Message: ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1076: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
Time: Tue Apr 13 00:36:25 2021
Count: 1
Stack: ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1076: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\WeakAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua"]:1076: in function `activate'
[string "@Interface\AddOns\WeakAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua"]:1121: in main chunk

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "PLAYER_TALENT_UPDATE"

```

### To Reproduce

Install start up game
boom error message above4

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Only addon installed

**Which version of WeakAuras are you using?**
Alpha-2

**Are you on World of Warcraft Classic or Retail?**
Burning crusade beta

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Got an error message with Classic 3.2.2 install but it worked fine after initial install

**Comment by InfusOnWoW** [comment]
Apparently we are to guess what game version you are using?

**Comment by Nevering** [comment]
You have a question in there that says? 

Are you on World of Warcraft Classic or Retail.

I answered that with 
Burning Crusade Beta

**Comment by mazuno** [comment]
same error here. latest TBC beta build with WA being the only addon installed

**Comment by mrbuds** [comment]
This is a known issue in one of our dependencies, it was reported to it's author
