### ISSUE TITLE
[minor] Scrolling through the options pane sticks onto sub-ScrollFrames

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#302]
Technically, this has been the case since time immemorial with the Options pane. But with the codeboxes now extending all the way across the pane, instead of halfway, it's much easier to trigger it (snags pretty much every time if you aren't very careful with cursor placement; dragging the scroll bar is basically the only way to avoid it reliably), which can be irritating if you have a complex animation which makes use of many custom scripts. I'm not familiar enough with how ScrollFrames work to know if this is even something which can be addressed (and this may just be a library thing in any case), but I thought I'd mention it.

**Comment by InfusOnWoW** [comment]
There's a function for that: EnableMouseWheel. I'm not sure whether the event propagetes in that case.

I guess, making it scroll the always the whole options pane and never the code edtior would actually a improvement.

**Comment by emptyrivers** [comment]
Ideal behavior in my opinion would be to default to only scrolling the main panel, and requiring the user to set the UI focus onto the sub-scrollframe before scrolling affects it.

**Comment by InfusOnWoW** [comment]
That's how it should behave in the latest alpha.
