### ISSUE TITLE
No update on weapon swap

### ISSUE THREAD

**Issue by Nickldio2** [WeakAuras/WeakAuras2#3021]
## Describe the bug

When working with the Item Enchantment trigger (weapon), the text infos (%s or %p for example) do not update on weapon swap (PLAYER_EQUIPMENT_CHANGED). They only update on equipping or unequipping items (UNIT_INVENTORY_CHANGED).

**Do you have an error log of what happened?**

No errors

### To Reproduce

1. Create new icon WA
2. Create Trigger for Item Enchantment
3. Select Mainhand
4. Select a poison with stack as enchantment (Instant Poison for example)
5. Create two texts, one for stacks(%s), one for duration(%p)
6. Close WA config
7. Apply MH with poison listed in the trigger (eg. Instant Poison)
8. Apply OH with a poison without stacks (Crippling Poison)
9. Swap MH and OH and watch as the two created texts don’t change (neither stacks to nil nor the duration to the Crippling Poison duration)
10. Unequip an item and watch as the texts now update to properly match the main hands poison info

**Screenshots**

None

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No

**Which version of WeakAuras are you using?**

Latest

**Are you on World of Warcraft Classic or Retail?**

- [X] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

No information

### Additional Info

None

**Comment by InfusOnWoW** [comment]
@mrbuds this works on retail so apparently it's a classic only issue.
