### ISSUE TITLE
TBC version swing timer reset/clip/freeze

### ISSUE THREAD

**Issue by fotmxd** [WeakAuras/WeakAuras2#3023]
## Describe the bug
When using a swing timer WA for ranged (maybe melee too) attacks, if you auto shot > steady shot > any ability, the swing timer bar will clip/reset, not filling. 

**Do you have an error log of what happened?**
No error log

### To Reproduce

1. Create a ranged swing timer bar
2. Auto shot then steady shot
3. While auto is on 'cd' and after the steady has cast, use arcane shot/multi-shot/kill command - really any ability

**Screenshots**
https://gyazo.com/e2fb4242625031e5c991948c5a3b46a5

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes - in the gif link I do not, but I tried before with everything off besides the swing timer.

**Which version of WeakAuras are you using?**
bc-alpha-4

**Are you on World of Warcraft Classic or Retail?**

- [x] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**
Yes, it worked on the version before this new update. Here is a clip of me doing the same thing on the old version and it working correctly https://streamable.com/zhzr6d

**Comment by mrbuds** [comment]
fixed with https://github.com/WeakAuras/WeakAuras2/commit/4e9e5e72f726836851f6ec8f7f7c64e938d8bf5e
