### ISSUE TITLE
[Options Pane] Multi-selecting auras with TSU triggers fails to render some options

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#303]
Minimal reproduction:
```
dScxeaGAsP61OqzMOq1SbDtsvUnQ2jPyVQDlv7NeL(jPuggPQ(TidLusgmjkgosDmu0cjv0Ijvy5s5PqpgONtstKevnvIjdy6uxKucxwY1rSrsj1MrP2oj8zKCyrnAuiJNuIwgk4wKk1Pfopk5VKipIujtJevEMlJQJkFPOGjAE19iFeyeyzSvurQlSORrQwIqpwAjDUduaRZXmOdfL0ckQQPxcOwJ(JbWOoiukRYau80yNWLwqrvn11WCuTGS1Qu09Oo1MiAtpgxl0AzeMYalJodRUzyzKtGow27rNHv3lJCc0XYEp2sWAzKtGow27rGGn7aKanRLrob6yzVhBzWAzKtGow27XOt1se6Lrob6yzVhPvq7mS6EzKtGow27r2zqhP(YiNaDSS3Je1sjqywvDDS3JGlRH5Yyg0HIsAbfv10lbuRr3m1F0TGIQAlJMfDncsuDIpcYOcKXgj0azxJGevN4kzw01OQZUi0azxJGevN4kXOaOgDWlG9imLbwgJovlrOxg5eOJL9E0zy19YiNaDSS3JabB2bibAwlJCc0XYEp2YG1YiNaDSS3JTeSwg5eOJL9EKwbTZWQ7Lrob6yzVhzNbDK6lJCc0XYEp6mS6MHLrob6yzV3JaHQ2jDqhkQXmeo2kQi1fw01yaM6JbWOUyySt4slOOQM6AyUxddlJzqhkkPfuuvtVeqTgDZu)r3ckQQTmAw01iir1j(iir1jUsMfDnQ6Slcnq21iir1jUsmkaQrh8cypctzGLrNHv3mSmYjqhl79OZWQ7Lrob6yzVhbc2Sdqc0Swg5eOJL9ESLbRLrob6yzVhBjyTmYjqhl79iTcANHv3lJCc0XYEpgDQwIqVmYjqhl79i7mOJuFzKtGow279iqOQDsh0HIAmdHJTIksDHfDngGP(yNWLwqrvn11WCmag1fZ9EuXAyQCmWC)a
```
Note that the "Check on..." row is missing when both auras are selected, when imo it should be blue (to signal that the choice on that menu isn't uniform). This seems to be related to how that row won't render when you have a status and an event custom trigger in your selection. In addition, the "check on..." row will still render if you have a non-TSU + a TSU trigger, if the TSU checks on event and the non-TSU is status - check on event, but any other non-identical combination will not render. Possibly, this is due to the fact that the "every frame" option extends all the way across the row, while the "event" choice gives a field to enter the events in.

**Comment by InfusOnWoW** [comment]
Yeah I changed a bunch of rules in how we coalese options. I'll take a look at that.

**Comment by InfusOnWoW** [comment]
![wowscrnshot_111717_174352](https://user-images.githubusercontent.com/12950521/32958581-2e75ca40-cbbf-11e7-9cb3-cca72d50355b.jpg)

**Comment by InfusOnWoW** [comment]
I actually changed that how options are combined for overlays. Since different auras in a group can have different sets of settings, because they have different overlays. With a minor tweak, that I'll push later, this will look like this soon.

**Comment by InfusOnWoW** [comment]
Having two "Check on" combo boxes isn't ideal, but for now that's what it is.
