### ISSUE TITLE
IsBC function not declared

### ISSUE THREAD

**Issue by Crelam** [WeakAuras/WeakAuras2#3030]
## Describe the bug

Looks like the BC check function isn't declared.
**Do you have an error log of what happened?**

```plaintext
2x WeakAuras\GenericTrigger.lua:3122: attempt to call field 'IsBC' (a nil value)
[string "@WeakAuras\GenericTrigger.lua"]:3122: in function `TenchInit'
[string "@WeakAuras\Prototypes.lua"]:5962: in function `init'
[string "@WeakAuras\GenericTrigger.lua"]:259: in function <WeakAuras\GenericTrigger.lua:240>
[string "@WeakAuras\GenericTrigger.lua"]:1155: in function `Add'
[string "@WeakAuras\WeakAuras-3.2.3-3-g06a09d6.lua"]:2748: in function <WeakAuras\WeakAuras.lua:2695>
[string "@WeakAuras\WeakAuras.lua"]:2824: in function `Add'
[string "@WeakAuras\WeakAuras.lua"]:2356: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2363: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1026: in function <WeakAuras\WeakAuras.lua:998>

[string "@WeakAuras\WeakAuras-3.2.3-3-g06a09d6.lua"]:1148: in function <WeakAuras\WeakAuras.lua:1099>
```

### To Reproduce

Load this the version in question.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

3.2.3-3-g06a09d6
**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [x] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by tflo** [comment]
Same issue here with 3.2.3-13-gd8f6d71, retail

WA starts up in paused state. Can unpause it, but not open the UI.

Unloading all other add-ons doesn’t change anything.

**Comment by Stanzilla** [comment]
Should be fixed with latest alpha
