### ISSUE TITLE
Pseudo-events caused by custom-status triggers

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#304]
Make an Aura with `custom - status - event(s) - PLAYER_REGEN_ENABLED PLAYER_REGEN_DISABLED`
It doesn't actually need any content other than this.
Make another Aura with `custom - event - PLAYER_REGEN_ENABLED PLAYER_REGEN_DISABLED`
Give this the trigger:
```LUA
function(event)
    print(GetTime(), event)
end
```
And upon entering combat, in the same frame, you'll get one ENABLED and two DISABLED events firing. 

We actually see this issue very commonly with ENCOUNTER_START because that's an event that people use a lot to do things like reset a counter or whatever. We see it so much in the case of ENCOUNTER events that we actually advise people to always check that the event carries an arg to ensure it's a genuine ENCOUNTER event and not fake news :-P
Seeing someone have this issue with a PLAYER_REGEN event today made me realise that these custom-status triggers are the source of the spurious events and the PLAYER_REGEN ones aren't so easy to differentiate. 

So, I get that these pseudo-events are needed for the way the triggers work, but I wonder if there might be a way to always be able to differentiate them from the real thing. So that using one aura doesn't break your others. 
I would suggest that generated events could carry and arg which I would guess would be relatively easy to add and wouldn't mess up the rest of the way WA handles them, however I hesitate at this because our standard advice for handling the ENCOUNTER events has been to do:
```LUA
function(event, ...)
    if event == "ENCOUNTER_START" and ...
```
so actually adding an arg would break the most common workaround that's in place for a lot of people. 

I don't want to overstate the issue. It's super minor. Today was the first time I've dealt with someone having this issue on PLAYER_REGEN and they were able to workaround it (by changing their other custom triggers to Event triggers).

**Comment by InfusOnWoW** [comment]
So I don't know what the code does atm. 

But what it should be doing, is to only send those fake events to status triggers and probably only on the aura being loaded or the options being closed. That would be the consistent thing to do.

**Comment by InfusOnWoW** [comment]
I reworked how and which triggers get fake events. It should now never send fake events to event triggers
