### ISSUE TITLE
Latest commit breaks WA

### ISSUE THREAD

**Issue by ResultsMayVary** [WeakAuras/WeakAuras2#3042]
**Is your feature request related to a problem? Please describe.**
The addition of PickupContainerItem to the forbbiden functions table breaks functionality in WAs that I have developed and are broadly used.

**Describe the solution you'd like**
Remove PickupContainerItem from the forbidden list.

**Describe alternatives you've considered**
I am not aware of any workarounds for this issue.

**Additional context**
I understand the security issue and risk involved and why the functions were added but is including DeleteCursorItem not satisfactory enough?

8cb556bc0c24a631a0c3621ecf9ee386c6365ba5

**Comment by ResultsMayVary** [comment]
Tagging @nullKomplex as you're the author of the commit.

**Comment by InfusOnWoW** [comment]
You didn't even describe the aura nor linked it.

**Comment by ResultsMayVary** [comment]
Here is an example of one of my WAs that is broken by this change. https://wago.io/rtDSk1EUl

This WA is used to fix an issue where the base game isn't able to equip 2 weapons of the same name.

**Comment by Stanzilla** [comment]
So the problem here is that it's the Internet and everyone abuses everything and that's why we can't have nice things. I do see your aura as a valid use-case but sadly I'd rather have us protect more people by blocking these API. We are in talks with Blizzard to potentially make this better but that might take a while and some convincing.

**Comment by Stanzilla** [comment]
Okay I read that too fast, just unblocking `PickupContainerItem` sounds okay to me...

**Comment by Zidras** [comment]
Based on the discussion already in the discord, just adding this here for clarity - `DeleteCursorItem()` is the only function that can cause irreparable damage.
Reinstating both Pickup API functions should be considered

**Comment by Zidras** [comment]
@Stanzilla What is the rationale behind reinstating  `PickupContainerItem()` but not `PickupInventoryItem()`?

**Comment by Stanzilla** [comment]
nothing, I just did not commit it yet
