### ISSUE TITLE
Recommend wago link when importing in game

### ISSUE THREAD

**Issue by krazyito65** [WeakAuras/WeakAuras2#3043]
**Is your feature request related to a problem? Please describe.**
Sometimes, sharing auras in game is too large and takes too much time. I would like to have the wago link, if available, in the import screen to pull from wago instead. 

**Describe the solution you'd like**
Add wago link, or make it easily accessible, from the import menu instead of importing from a player.

**Comment by krazyito65** [comment]
Maybe, before importing from the player you ask if we would want to grab from wago instead?

**Comment by Stanzilla** [comment]
So basically just display the link, if there is one, on the import tooltip, yeah?

**Comment by krazyito65** [comment]
Yea, but obviously before the actual import happens.. Which may change how that works, which I didn't think about before making this. The goal is to avoid stuck or long imports if they are large

**Comment by InfusOnWoW** [comment]
Meh!

No one wants to really work on this. So unless you come armed with a PR...
