### ISSUE TITLE
WA triggers to handle marks directly

### ISSUE THREAD

**Issue by futurex21** [WeakAuras/WeakAuras2#3046]
**Is your feature request related to a problem? Please describe.**

Because TBC currently has nameplate range capped at 20 yards (outside of arena), I am trying to create a multitarget dot tracking WA that is able to update dot progress & raid markers in real time, without relying on nameplates. 

**Describe the solution you'd like**

WA triggers to handle marks directly would, among other things, be useful for maximizing dot uptime on multiple marked targets (specifically raid encounters) by offering up-to-date information compared to alternatives. Asakawa had suggested this idea.

**Describe alternatives you've considered**

As mentioned, I cannot rely on 20 yard nameplate range in TBC, so I originally started with a multitarget trigger, though I wasn't able to get raid markers to properly display with this method, so I had to switch over to using a combat log trigger, as displaying raid markers is my top priority. 

Currently, the best solution I have been able to find to have raid markers display is by using a combat log trigger (see https://wago.io/lTmMDQ1Pc). However, this method doesn't update raid markers if they are changed at all during the progression of the tracked dots, and the dot progress bars persist regardless of a target dying or the dot(s) being removed/dispelled etc... Having to rely on a combat log trigger causes some shortcomings in functionality, and makes this WA largely unreliable in PvP situations.

**Comment by InfusOnWoW** [comment]
That would take quite a bit of effort for very minor gains. I sugget you simply improve your custom code to handle units dying or dispell events.
