### ISSUE TITLE
Layout using custom functions

### ISSUE THREAD

**Issue by ZeeD26** [WeakAuras/WeakAuras2#305]
I am currently trying to setup a little "all-in-one" bar for my rogue with some "preferences" I can work with, like the base dimension or frame thickness.

This is done by setting up a text aura which executes the following code on initialization:

```lua
rogue_bar = {
    base_dimension = 16,
    border_size = 1
}
```

Currently I use custom trigger functions to enforce the sizing and positioning of the elements within my group using `region:SetSize(...)`, `region:SetAnchor(...)`, and `region:SetOffset(...)`.

First question:
I somehow feel that this may not be the correct way, could you tell me an "as clean as possible" to enforce such dynamic layouting?

Second question:
I would like to use a dynamic group for my buffs then, how could I achieve that? To my understanding the top group assembles all the triggers from the children, so dynamic sizing seems really tedious as well. Are there "smart" options?

**Comment by InfusOnWoW** [comment]
There's no clean way to do that. Whenever you call functions directly on the region, that can break with each WeakAuras update. As such, if users choose to do that, they are entirely on their own. 

Towards your second question, this isn't a help forum, this is a bug tracker. The best place to ask questions is our discord channel.
