### ISSUE TITLE
add Translit Library

### ISSUE THREAD

**Issue by Takkero** [WeakAuras/WeakAuras2#3054]
**Is your feature request related to a problem? Please describe.**
It's not entirely a problem but for example i'll use NAOWH (main tank of ECHO guild) UI and Font ( i like it ) and my server is linked with Russians.. many addons like ElvUI / Plater /Details use it and now i suggested also to DBM integrates the Translit library (made by  Vardex) and can be usefull in pug with russians guys in raid.

**Describe the solution you'd like**
Using of LibTranslit-1.0 by Vardex

**Describe alternatives you've considered**
Ye i can change the font with one that included the russians but using a translit allow all weakaura's users to use all the existent font without any restrictions.

Thanks for ur attention.

Takkero

**Comment by Takkero** [comment]
here is the library: https://github.com/Vardex/LibTranslit

**Comment by InfusOnWoW** [comment]
That doesn't sound too useful to us and it's entirely unclear how to even fit that into WeakAuras.

I suggest simply using a font that has support for the cyrillc script.
