### ISSUE TITLE
Forbidden function override

### ISSUE THREAD

**Issue by jws305** [WeakAuras/WeakAuras2#3057]
**Is your feature request related to a problem? Please describe.**
The addition of DeleteCursorItem to the forbidden function list breaks some WeakAuras that I relied on.

**Describe the solution you'd like**
I understand why this was added, but in my case I have a list of items I want to be auto deleted and I want to be able to whitelist this WeakAura so it continues to work.

**Describe alternatives you've considered**
I'm not sure there are any

**Additional context**
I am using a modified version of https://wago.io/a9e4fsASG

**Comment by mrbuds** [comment]
This is not happening until blizzard add a protected dialog to confirm delete of items.
Until that i'll recommend you to use an addon like https://www.curseforge.com/wow/addons/dejunk more suitable for this task.

**Comment by DTuloJr** [comment]
As an FYI, Blizzard modified their DeleteCursorItem code to add a safeguards to prevent more than a single item from being deleted per hardware mouse click, and have now also prevented it from being run in a macro. The former is reasonable... the latter, is just a pure nanny-state-level overreaction. Please consider reversing the ban on the function, as the single-item deletion is still useful.

**Comment by mrbuds** [comment]
No
