### ISSUE TITLE
Can't CTRL+C, CTRL+V, or type more than one letter in Import

### ISSUE THREAD

**Issue by Serina-Lee** [WeakAuras/WeakAuras2#3059]
### Description

I copied the import string from wago, and opened the Import box on WeakAuras but couldn't paste it. Nothing was pasted even though the same string successfully pasted in a Word Doc. I also couldn't CTRL+C the URL for Found a Bug?. And in the text box for importing, I can't type more than one letter. So for example, if I want to type "wa", i have to type w and then click back to the box to type a.

### WeakAuras Version

3.3.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Click on the WeakAura add on
2. Click on Import
3. Click CTRL+V

### Last Good Version

yes

**Comment by InfusOnWoW** [comment]
Try following the advice to disable all other addons, or to enable lua error reporting.
