### ISSUE TITLE
Sort by TSU Custom Variables

### ISSUE THREAD

**Issue by EmElw** [WeakAuras/WeakAuras2#3066]
**Is your feature request related to a problem? Please describe.**
Sorting in dynamic groups is limited without custom code. While custom code does cover all the cases, it is often cumbersome to write.

**Describe the solution you'd like**
Some sort of option to sort by the custom variables declared in the TSU. Exactly how this would work I'm unsure of, as there could in theory be very specialized cases where you would want to sort by multiple properties in some sort of hierarchy. There's also to consider what happens if multiple TSUs are in the same group but with different custom variables. Maybe something as simple as "sort nil first/last".

I'm imagining something similar to the conditions fields, where you could create an arbitrarily long list of [variable][ascending/descending] pairs.

This could also be extended to work on normal triggers, for example sorting auras by stack then duration.

**Describe alternatives you've considered**
Doable with custom code, but changing is not end user friendly for complex custom code.

A easier drop in fix could be to provide the boilerplate sorting through snippets, but has the same problem for non-code savvy users.

**Comment by asaka-wa** [comment]
If you're already making a TSU then a custom sort function is trivial, especially with the Compositional Sorting functions - `WeakAuras.SortAscending({"region", "state", "myCustomVar"})`.

But your issue, I guess, is more about letting users of your custom Aura interact/change things more easily. That kind of thing is usually done via Custom Options, and that can be used for Sorting too, via `child_envs`

**Comment by emptyrivers** [comment]
Yes, the thing you're looking for here is the compositional sorting pattern, documented here https://github.com/WeakAuras/WeakAuras2/wiki/Custom-Dynamic-Group#compositional-sorting

When writing that, I briefly considered constructing an interface that would let you "write" a composed sorter like that without actually writing code, but decided that it would be both too much work to maintain, and (after feedback about the clickiness of custom options) less convenient to use than a box to put code in.
