### ISSUE TITLE
Ranged Swing Timer not working as intended

### ISSUE THREAD

**Issue by jodysaliba** [WeakAuras/WeakAuras2#3077]
### Description

Ranged swing timer does not appear to work/it is using the MH speed instead. In the aura linked, it has a bar for all three (MH, OH, Ranged). When I wand, only the MH Progress Bar shows (I made the colors different for all three in order to tell them apart). This aura seemed to work correctly on my hunter with it's ranged weapon, so it looks like it may only be bugged with wands.

### WeakAuras Version

3.3.0

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Trigger > Player/Unit Info > Swing Timer > Ranged

### Last Good Version

Not sure. First time using this trigger.

### Export String

!WA:2!Dw1wVTXXvytVq1URtSLKTLDCcsfCaCCUydzku3edyOQLI0KYYK0lP8Ly1qo7Ud5osl3DZmZsDP5sRAAIttAAk7ZTbGpNN4lPpRFafhOw0(wrHYl5TaO8dW5m7UsrsXUfOdaj3DUCMZ57YHzUZOcZjV8KxEIr7mQZOopCIEeU9Cu)2s33FSTSc4ouUbXEjhEqy4WgES1wJWDgVEqGNKfUjjs6gWRekzb(cD(QvA1sqLlm0aIVnUq1aMV0kx(Y1ZB2VvKNxog32J2mC4ibD6KTq5Z7ZKUzJ4EhMtSJJ0vnfscxQBWWL0TAH)iC1xxYzTBt5IZDbE6JFqFhQvuRw1xnKYlMFUQfMFodj(IjjItYUUiK65vYrOVLiYI2L6lRH7MTYGg5MUw9g1QpTzDJi8sSc9iRs5M(KouHUz8wTksjEs3DpAvofpQzTQ5NBUEr(PPG(a7aVOo(1cj2uTTXcMY9jE3bZtSuEqpb1RvmoKTELQMepwBF4ORZdKevPMPpgDtA7y8ZWlG4uWqWwJoMzNieH1nWkWEm4L1nT9icH6jljXdZg1JBALsn5c8c4ZQPPvvBIl)t5eFwhIK6Akuj1ZDitHnEgnloXHfjE)NYkHyD7N8BEN20WrQ9wreoD8cinn(DDzsAFECEPW2nCwfrgMDBEquy6PQHP5qMESom5X4RKW8zgKSws(Kjtgnd8ilBmtL7woDPs(4(02YglyjXxwaP8aUL50ZuA(AR3MZCu335nNzJKTNe3FmcylNGW9Lb2Dta3J(QVY5zoHNu4Y8P0vBuBzMF76So4Q9ur6UmhP7Xg0IJKAnjNijABNimlOMsDrw1YzMpFzlmDAXARNnI5mOAT7XNyXCEMTNSxcsI31vHNUaCkd)aF6guIqfVyxYr20bvAQD0qP74ckgkhX6Q9OUaOSrhcZhplugQCeOkCBWeF8ehCM1rlXCkW01qeWLq5(QaXsCwdy(Tc4jzIohboLYlZO2x7HxPpYX8LIl1t3NHNPwqexr6WpkdCe4OBgVU5o6TWr2373kWHAm981Rah7WgQt7cdF8laJ8pXS7zGZaND9DkVrVc8CdIr4XJHyC5Zbpp8t4r(XUddSxqamMUQoA4s8DAg)KYC1eEwDd1uqnyu4KW46HJOC6DP1t8qQS4louC23WEhPSgC(haVa6vSiP6PIt9VoJACQIt91)v14l10WgacIuLJu3nIlTefZ9ZaV4lpgCQbQgbyeAGF6MkbBOCyABM(sIIilUoCQEOBmz6u5xA6OuYPDdB0LjywytSDcgfDp8RmEv2kuVDIzqIBWYLYA7kpnCXU81qLd2j6W9uOIcY4UWLuMy4vvF3xnTDqhlccxVs88VK67TIRjd0X7OqPStpZmjDpDwmsiPouNBrwXDBvJaL503zxRxXP(3v)ZpchWTseV7xaw7)TKeEk8G6WX1HtOdxlZbVxgkwUkpfFHBoqmH)RDdXpRq1jFTeMOoDfKzOHxSKQPyl09UqoIqIsidcFH5lDPV)TlvtDGEXkabZHAAw6gfRdZQJgCdH8wfhehXIX4515YKi3pVx35lnEz0AafHsgRfe0jJz8oDHzW2dPNI54q9nlN)o5nXoWHUen4gAMlR8mf)5V579nF(JE0xbwntSs72lvJZ8vDAOn3RW6EzgeWzOGp2v0VyfZsVrLY1NEo4o6WDhl8Syd(aon9)eZRSg558aUOjmK(dVcC)tdVXUMt4bzGfGFbA(G38GopOHYYbkZJYNbeWcTxGDtWPzS5JMfLzPgkO1xCiO9U2MeghzsfHUhg)aZCIFWmUZQvCQ)(jJhfN6V9xIhAaZfwm1qbl1fKzGoGp4PbHXwd4TAcCqGlgark1EI2fwEFsCyLDu2DpmSkSg8lDv(BuzbV9(fSdPdVdQTG3ffaWVc(1W6WVb(0KQZQj8BVo8bWhc)(VN7Eyg4Jsy8e9sLIWNO4yLQa(DWhJQtNLYrNTRX0V(TVj8hAcFwg4pc9s4m4p1mvQFcLA))cjDG88jqyPDg3pJHSif)dy)2uNhpNPGcxSh3wBRgFlYd)NHJh)a4xbZk8hPH9J)iHKa)ia)KW(eMjf(3Rb))7UeOYfPWuc7MdcMzrVcfRsJk35GCNIjsjpfXGSgYMPSwwH0mL02dXISkkbEm81q6J29FCVV7d

**Comment by mrbuds** [comment]
It's working fine for me with 3.3.0 on classic.

![img](https://i.imgur.com/TaJiW93.gif)

**Comment by mrbuds** [comment]
I see you original talked about your issue on the TBC channel, do you have this issue on classic or tbc ?
