### ISSUE TITLE
BC - Steady Shot/Aimed Shot resetting melee swing timer

### ISSUE THREAD

**Issue by samhalli** [WeakAuras/WeakAuras2#3088]
### Description

Steady Shot and Aimed Shot are resetting the melee swing timer when using trigger Player/Unit Info - Swing Timer - Main Hand

Also Aimed Shot is -not- resetting the ranged swing timer when using trigger Player/Unit Info - Swing Timer - Ranged

### WeakAuras Version

bc-alpha-5

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Create progress bar aura with trigger of Player/Unit Info - Swing Timer - Main Hand, and cast stead/aimed shot

### Export String

!WA:2!Dv5ZVTrXxaCm(aGVajKekFjGS4quPO0qm8Tc1kuLxhBSbh7O1BAkHkSNDNN3DAxpZYmZ6eNJ(eN9Fc(pbFLBrCgTeXb4A(tOh6zEZSBtHUsw7SZ8(97ZBCPwRpzD660F5blvje5ZoHr1rBETVqsbPdj4zuPiXPNGd(NrcfDoyHFpn1)Kt39e559hpwb6sYz5lEWkcpisipsW4A)gn7510DXybx3kMeQK9p2RBNEnVY6hxHMOzcEPK1(pFFOGco1p2RFTuzCY2rADI6(7TNX33Lj27gNV3(FLdlqWJMRLSWqqQ(PDKflFHJEwc4KYz650uP1URV)1QuFykW1dshpMD(QHnQpWB4aV6UEYuU9ehsQwCDQcgs8vcPVjyg5ApA1GZy8WQESjGmBt)KyYmq6YjtavL5gnmEB0Cvceh3HwSxeHthDJFpscOFDhCuZUDVke4GKfmisCwF(Lk7R6bA2uWXOLZecJVKc(yS6HjJSDZUh164Uls5fjzLDYE)XzBKTzE8gFgzMsltHrzvhL9zz3jB7LneCkZK8QSnZ(KSpVYkkt90uU1n1i8zjRrSR9YnPjDlV0uvhgiIfYVRm(8CSxcsoj(ryngT1pEPTFL3XFCPfkiESTHN9op3VGx6WBjX2E0vy9e5H(j2GOYCFISrUHB)W)6w4Zh87LkFTsZcE2SdkAurstmHIFpxLMi1v8hZ4mvufh8LUICAEy8XlXYQleAK8oBLTXkcQpA)H4VPxLJVdf585l)mNoRHsKTXcu98TVS408uUujmIk2zktX8JHrRk(gOHqYAd(5uIeQ2knoU6jrmn8YJvSlGY(ralmsV2ccNnXMq3l7(TUeikyGwc8qD0BLTHdhhOU6LS5qdUkvaw4PQ5grnT8SUz3Uv23JsJRomRxwF89dE9DCIfe6lKiBkfPjB5ojnwZQSWWegMwg5RjXi8TvMBf5fOxr48nDdIjk1o(kuTyWV9XMjvuahS2dgjT6BfA0skdhxcqZoBlRiIyRiwahX9GrYX5DmRIjttELdDmNVt2jLnopF7A57JLkZIRTSKdEa1aF1QFWbjVhA460NMQ0afOhsopYYvM8JtZXN2p8pSp)D7h(RFe(S9hwQmoSOiAtffISm8arQma2(n(386pGSqbJ24M2D(fFnUH4F9iGXJwkTKMDsSa0kGQcuF0ZZHRws8gbJy(dA42SzVf2PjfJcUUD(22EUK4Kis5pLrNFiedq1Q1wzDFBl28nsnCoMeiM5eZU4cIKw1LWOvDisxRCroxietk5RGjy31F)7(f3D)VCPweumx82hTzHbzukWD718rnDZlbEfM(2Dmt0ytdEsdco8XdrR)KJ7S7R(A3bgfwn2Kni2s0KYUNz(NHF7DZ(FJQLYORU4X66n)6ENgD2Jq6Z4Dik)Q9dYBeq0kHKHTClJVSDF3oN2VNx9UldU5EPkRy8Xcz(GYwj3IfYfsO4(IMMlnBkLcPAKpQZywyL1vl9d21we39)V(0)8X)Z

**Comment by mrbuds** [comment]
Steady Shot reseting melee swing timer is already fixed https://github.com/WeakAuras/WeakAuras2/issues/3083

Can you show proof of the changes you ask for aimed shot are correct ?
