### ISSUE TITLE
Progress Textures - Recenter options not working (on alpha)

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#309]
Make a new Progress Texture. Move either Recenter slider. 
Interestingly the preview image/thumbnail in the config menu does show the change, but it's not reflected in the actual Aura. 

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
No
What version of WeakAuras are you using?
2.4.25-38-g730abde-alpha
Was it working in a previous version? If yes, which was the last good one?
Not sure

**Comment by InfusOnWoW** [comment]
Fixed.
