### ISSUE TITLE
reverse option of "Zone ID(s)" / "Encounter ID(s)"

### ISSUE THREAD

**Issue by rml9ty** [WeakAuras/WeakAuras2#3095]
my case for adding reverse option for "Zone ID(s)" / "Encounter ID(s)":

example situation for reverse zone id: I would like certain stuff to be loaded, except while I'm in zone X. Only other recourse currently would be adding ALL the zones (which is ridiculous :P) or to disable it manually, which is arduous. 

example situation for reverse encounter id: I'm a priest giving PI to certain people on a per fight basis. For instance on Sun King, my PI goes to the Shaman. In every other fight to a rogue. What I have to do currently is add all the Encounter IDs except Sun King to the rogue-PI-WA, instead of just saying: everywhere, but here.

**Comment by InfusOnWoW** [comment]
That sounds like something that should be solvable with custom code and is otherwise too niche.
