### ISSUE TITLE
Moving dynamic group with auras inside fires an error OnDragStop

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#3104]
### Description

Error happens every time dynamic group is moved around the screen with options open (currently tested on PTR)

### WeakAuras Version

WeakAuras 3.4.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

![](https://i.imgur.com/HSgCEZc.png)

### Reproduction Steps

1. Have dynamic group with some auras inside
2. Move this group around the screen
3. Error should pop when stopped moving

### Last Good Version

3.3.0

### Export String

!WA:2!fwv3UnXrByS2sHUbOjgiLKYxBuKinLkfbHg4tvQsKnznjvgVMDxJdLdmZU7yVtz9olZmBCsodleIJTuVb8Hv9iFjKRGxzv1lGCje1lGoZS2HFoP(GzN59)N3)CPNwM7EV1(X1UB5ULJkh9U1gGyHvXPDeXVz(tcOSimZcf(YignlBwReYrhHyrl5tPjcsg7aN2T5yXopmB8FCo5p2Htj497nvegHsdJPS6usQiyl7A(2UdBNNKSfHfMGFHlpdfIppdfki0u(9D5cetyg0MKs4XMwYpcZ(cgPthmJV4kSjxF7WiCqE72(hMHz7yxTELgvTeYhUOCgA9(8mCsYUrCZt45b49XPcpP0Kdg1ARn98B55VPRVvU04bzjOdXm3uuxm30vlAWoyuIi(mvRZWsvD9QBxT6G80jHG5OqAsE3upfcmcyOiso)nxQFohxL0LiIDrjKoPWfzsmPuO0qPbDXDua10kHIIQeiqjshmVB3Cz600sg2HZdRA6gMG4C1nlo5iS6Y4GjvHTOju2Vyyyu34oRTrFgTxreWqPKUibo2LhkTQrqrXlEyXx7Oo4S58EvoIHxQIScSuZyIapKPdivE84OdLzbsyhgnpBIwEsVFEloLjSsPP41ZjrJQ7SxJ2ONfUt86d44K26A76(o1LXIaPQJLovsbZsrjpvw1KeE(jHsqlqPIkYknLf4U5272WBmkxiBoCY0fFZJl8zrh0xeivPnPJ5qbnC)cZCJsT(NLjrSht3hVux8O2mzvZtWqcKXGomsutsKiEMtl65QO4QawG3wU2216RKq9Ez3Thv4QDtLEYWsI4EwB70SMBIQYnZeUfz6sLkzmuglrKIOCejTnL1vduZbfjD517dxQYXyexfp6XNlaxfEW4iz7OIDlvZjJJvgI3xjNksGhy1frsRaUAPbpWhAi)E5pLs5WfF3YdjsT9O5Sq8nphC(sWNxcUaCXXHYHXiAVuVEKm8loE6tvfp2sPZlGV8kRaZ(wyoOS0QxdUUjmp8vWnGfGfnHVgUj8)GVb(wZS5udI7J9lAXFmnc)NNd(5NF6lX4SnvDNcxfCIHFcUOCeKJek8HJHBD73DTSYc8bIw8yK097vuglLTGMO(OiV1Ip5c8GbNXB5BXZM9du)95(tkOoTrZAZg(ozxvtu2(qvz)qDD3At5ZtlCe5aCrZWRhx0m8SjHZXA()woxqAFOed6wwSVKOvnNA2WvzYHuLmd1cgoDyZyWeeKkYMTcJC0spjhfP68wY3)Ja(upnwtRNStQjdL1V5KlfbW(eojqU)BcM)GLKzZTBTA2UTSC89DES7UpAh)XN5A144ctq0EFKFuC1ldDA4xD3A2)94oj0Evy4xLJtdpS(NDN1wFJc0PymsDm1c9vpukpoixiOPoYXn5wXHkYf)vW11YpfzdupoBnKXXYnEpAkLylfZyT39JjHVmfZ5gAn80RL0xRsKKNt7aRITubXysNyXRHvQaFNAFh896ZBRp)b959GF1TNUOcprnU9Ptnp9)EocQBADeL2TemJ0cMWLnHRycBnzXY61W9CFFjhSnGhb7a))rRI2yV7AVAxp7daltgjvTqchNDTPZAQgOTjCKSMgPw8NfJmahZ(t5hdp0S8()1E)7p

**Comment by Altoholic** [comment]
Same problem here for Classic ERA
