### ISSUE TITLE
Broken Trigger: Player/Unit Info->Swing Timer-> "Remaining Time" checkbox is broken

### ISSUE THREAD

**Issue by styleen** [WeakAuras/WeakAuras2#3106]
### Description

Player/Unit Info->Swing Timer-> Remaining Time
This trigger is broken. The checkbox "Remaining Time" doesn't do anything currently.

### WeakAuras Version

WeakAuras 3.4.1

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

nothing

### Reproduction Steps

![image](https://user-images.githubusercontent.com/84561524/119096264-9a6b6e00-b9d0-11eb-81c4-303e585c4cc6.png)

1 Create weak aura for icon.
2 Set display to fallback icon
3 Select any icon (i tried several icons)
4 Set Trigger as displayed in picture.
5 Attack an enemy
6 Trigger activates instantly upon starting swing and disables for a split second when starting next swing on the same mob.

The check box "Remaining Time" appears to do nothing. The trigger behaves as if it is unchecked.

### Last Good Version

no idea

### Screenshots

![image](https://user-images.githubusercontent.com/84561524/119096775-3eedb000-b9d1-11eb-821e-455584dc93d2.png)

### Export String

!WA:2!DrvZoQXXt8frSCYKdXlzTL8nerjhYb(ZIT3ifLePDiGxsWazy2)7gLdqpt3ZmT9q3t6Uh(yLIumN2Z8iW5CINGiEcgHIYdW(iSpbP6EaID4at11hDv)Q(xvfAvACjCj8TF2kQpNnGNk8jfC85XCXpue(jM3liqsux8NxD3SF)OJoAnI5hXf95uMYRrZUUnD26Z5Xy(u2GP0eYOn7p2ehsIeiFfLZKN5iviHYYMYOklVa4JmYAHsqddjcz3VqSt82sjLeKXiWbw4qEcrGuCrLV5BTtHi9sIrZjILh8O0PlsLKHrigEKT(FBTHvyIxAqG7Ci8lA2PFRl7Sv72HWgTYefbfRIgDF(3djR035qMqyQ1aGyHLDPJjI7KPEgL9fKa6mNb9B2PJddnMiT8YJ3(fN9v1wRVxkBcGjsKTckGSp5qSdGAIoB9WgNpWD4a3ZDCnfVgyJwitiXXTXsRLPSD9cR1yQ81PmOfoHuhXMNCmYi7MB)vCm5po6E4PGiyO4)pKuOx)l3)gcj5C4(8voiO7hTeXOJ1sSZY(OwzvSzCgzdbjjduccluf9WT4uHXJH6AgkEGoGLl0(O7IzvZobce(8)EywTStZQdIF8)vd02LiL(IirRaq7qc1V9F5TNKusrMPgkJqaZ46CovHKNAuA(lGlGkCOCNqw1LhSv5ZLjp6DcVHHDwOqHI3LRLehy4J2NFPBVKp1OeLQ4Ai7FffdpnNdhVppr0zeSr5B3MZL)5DLZgJ9xNkv0G5zpyLGRaG4ckT72RBZSkcasAFwzC8FhswUdbmvYJAjO3u(NsryOjGk76(EaFFM2A0nLlWxjqjlUANqEbmHkPEXKr7W87mVLCC7UDB6m0UNRBVx50(Lx4U9qQhqVH80Di663lpARMjHEx62PD3M)92Wy(0wcYVMsy(Z7)b1Qw)f5OtByT(V93Wc9bDWB9svkoRhqSHjWvA1DmmNhB8FpYwQp04qNzdqVF5Enr2AJrgxg4JIjfnfIBe1)nmIuw0yPdfKp2KaBOVqerW4fnms9w7yoc3Ywca9joJtJvulBnj)jzilh)yKuQL8uWnZuAXvcd)tx(261BBbsb0D6Ly2izjMTF32V91E6DBl2V5ksp3P300gIY70NvVE9A23W5Jl4GItIqfxP4(tYN2(W(pUcfVPw1YxrJXLBGeypiQaAO16abSFagXaQqX7ZFAAPvPRiVbnCA2SBYj7tQMO99ujcE7Xr1tP412HTtFUhgD5pkf7xP4m1qDZcgTspHsZHYAklFUbozT8War2dkjDEw1Nx90st(RR)N

**Comment by mrbuds** [comment]
@InfusOnWoW 
This fix it, but it doesn't seem to be the right fix no ?
```
      {
        hidden = true,
        test = "remainingCheck"
      }
```

**Comment by styleen** [comment]
How do I implement that @mrbuds ?

**Comment by InfusOnWoW** [comment]
@mrbuds yeah that looks correct.
