### ISSUE TITLE
custom trigger logic is not being executed for WAs with only 1 trigger (2.4.25)

### ISSUE THREAD

**Issue by Yuuseki** [WeakAuras/WeakAuras2#311]
**What steps will reproduce the problem?**
1. create a new WA (not from template), i. e. icon. 
2. Set Trigger 1 to status -> conditions -> always active.
3. for activation logic, I can select Trigger 1 or custom. I select custom and write
```
function(t)
    print('test')
    return false
end
```

**What is the expected output? What do you see instead?**
Expectation: I expect to see "test" in chat as well not seeing the icon, it's not supposed to trigger as I always return false.
Reality: nothing is printed to chat and the icon is being shown.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**What version of WeakAuras are you using?**
2.4.25

**Was it working in a previous version? If yes, which was the last good one?**
Yes, it worked a few versions ago and "broke" sometime during the past few WA updates following WoW patch 7.3. I do not know which version exactly, sorry.

**Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack).** 
No

**Please provide any additional information below.**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`**

**In case you do know which aura is problematic, please export the string and paste it below.**
I dont have access to my PC right now, decided to open this issue nontheless because it is very easily reproducable by creating a new WA in a few seconds.

**Comment by InfusOnWoW** [comment]
Should work in the next alpha.
