### ISSUE TITLE
Smart group + Pets option

### ISSUE THREAD

**Issue by ncuddemiIT** [WeakAuras/WeakAuras2#3111]
**Is your feature request related to a problem? Please describe.**
I created a WA that applies to a Smart Group, which works excellent. I wanted to apply that to track HoT's on raid members Pet's as well, but the Smart Group does not apply to pet frames.

**Describe the solution you'd like**
I would like to have the option of applying a WA to both Smart Group + Pets, to track things such as HoT's on raid member's pets.

**Describe alternatives you've considered**
Reaching out to the WA Discord, the response I received was that it would require a custom trigger. While I am not a developer myself, I will see what I can do to achieve this result. 

**Additional context**
N/A

**Comment by garrymullins** [comment]
When will this change go live?

**Comment by garrymullins** [comment]
> **Is your feature request related to a problem? Please describe.**
> I created a WA that applies to a Smart Group, which works excellent. I wanted to apply that to track HoT's on raid members Pet's as well, but the Smart Group does not apply to pet frames.
> 
> **Describe the solution you'd like**
> I would like to have the option of applying a WA to both Smart Group + Pets, to track things such as HoT's on raid member's pets.
> 
> **Describe alternatives you've considered**
> Reaching out to the WA Discord, the response I received was that it would require a custom trigger. While I am not a developer myself, I will see what I can do to achieve this result.
> 
> **Additional context**
> N/A

Any idea when this change will make it into the live addon?

**Comment by emptyrivers** [comment]
It will go live when we next publish a new version. We don't schedule those in advance, though we usually don't keep things in limbo for very long.

**Comment by garrymullins** [comment]
> It will go live when we next publish a new version. We don't schedule those in advance, though we usually don't keep things in limbo for very long.

Awesome, thank you!
