### ISSUE TITLE
Include TBC release on github?

### ISSUE THREAD

**Issue by jecs** [WeakAuras/WeakAuras2#3118]
Hi, I play WoW on Linux and use a nifty opensource tool called [strongbox](https://github.com/ogri-la/strongbox) to keep track of addons. It allows you to specify github links instead of curseforge links in order to keep addons updated, as long as the github page in question ships Releases. 

However, WeakAuras seems to include only Classic in Releases on github, with TBC nowhere to be found. This has forced me to revert back to curseforge for keeping track of WeakAuras2. Would it be possible to include the TBC version under Releases? A popular addon that does this is [Questie](https://github.com/Questie/Questie).

Anyway, thank you for your time and for the amazing work that all of you have done.

**Comment by SpatenLa** [comment]
![grafik](https://user-images.githubusercontent.com/39881841/120023970-d022df00-bfee-11eb-9199-ee870d55d987.png)

**Comment by jecs** [comment]
@SpatenLa Huh! That's weird. I wonder why strongbox isn't picking up the release. Thank you for entertaining my request.

**Comment by SpatenLa** [comment]
(let [;; matches 'classic-tbc', 'classic-bc', 'classic_tbc' and 'classic_bc', but not 'classictbc' or 'classicbc'. see tests 
     because strongbox is wrong and needs to be fixed. the official name supported by blizzard, the addon pages and the packager is bcc

**Comment by jecs** [comment]
@SpatenLa Gotcha. Thank you! I will open a ticket with the Strongbox people. :-)

**Comment by torkus** [comment]
@SpatenLa , thanks for taking the time to look into @jecs problem.

>  the official name supported by blizzard, the addon pages and the packager is bcc

I've seen a lot of variation so far but not much/any usage of `bcc` so I didn't think to add it to the matcher. Do you have a link or citation or something for the official usage of `bcc` ? cheers.

**Comment by mrbuds** [comment]
This should answer your question
https://github.com/Stanzilla/WoWUIBugs/issues/68#issuecomment-830351390
https://github.com/BigWigsMods/packager#build-type-keywords

**Comment by torkus** [comment]
that's a very interesting link, @mrbuds , thankyou. The conversation around which abbreviation to support was kind of funny ;)

From the linked comment

>  The implementation we've been informed about is as follows:

Is this a secret channel of information leaked to the public by Blizzard or do Blizzard have technical documentation on upcoming client changes somewhere that I can read (from the horse's mouth so to speak)?

**Comment by mrbuds** [comment]
You can talk about it at https://discord.gg/h7WSRf8 i'm gonna close this as it's gone too far offtopic for this bugtracker.
