### ISSUE TITLE
Change or remove the "Use Full Scan" popup.

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#312]
There was a little discussion about this recently in #alpha-testing on Discord. 
My feeling is that, the way people make Auras currently, Full Scan isn't really what people want when they use a spell ID instead of a spell name. However I do think that most people, not fully understanding things, click "yes" on that popup. 
The rare occasions where Full Scan is used, I think it's okay for those people to specifically select Full Scan. This could help a lot of people make more efficient Auras without really impacting the minority for whom Full Scan is warranted.

**Comment by InfusOnWoW** [comment]
Hmm, I'm leaning towards agreeing. Full Scan isn't actually needed in most cases.

**Comment by Stanzilla** [comment]
I feel like we had an issue somewhere where I already said that I hate the popup and that it's functionality is confusing and that most people don't know they can just click "no" and it will still works like they intended it to.

**Comment by asakawa-k** [comment]
Yeah, I wasn't around when this changed I think but I'm guessing that Aura triggers didn't used to accept spellIDs without Full Scan so if someone put in a spellID the popup was basically saying "If you wanna do that then you're gonna need to enable this". Now they do it's pretty rare to want it - mostly to access stuff like `use tooltip "size" as stacks` and so on.

**Comment by InfusOnWoW** [comment]
Should be gone now.
