### ISSUE TITLE
Taxi Load Condition after summon

### ISSUE THREAD

**Issue by Jinnai** [WeakAuras/WeakAuras2#3121]
### Description

I think getting summoned from summoning stone (maybe lock as well) while on taxi does not trigger an update to the on taxi load condition.
I have to open WA options to trigger the aura to load again.

### WeakAuras Version

WeakAuras 3.4.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Make a WA with Load -> Not on Taxi condition
2. Take taxi from A to B
3. Get summoned while flying
4. Aura isn't loaded

**Comment by mrbuds** [comment]
Can't replicate
