### ISSUE TITLE
Multiple Enemy Castbars in pvp

### ISSUE THREAD

**Issue by 152Makko** [WeakAuras/WeakAuras2#3123]
**Is your feature request related to a problem? Please describe.**
no problems i dont just understand english enough to make my own and i dont find any info in internet about this topic
**Describe the solution you'd like**
a way to see multiple enemy "castbars" "cooldowns"? like i have seen around
**Describe alternatives you've considered**
anyother way to just make it happen i know possible
**Additional context**

![cd35f784ba759d0f661823103fc4a7e0](https://user-images.githubusercontent.com/85033794/120080017-8d7d0780-c0bf-11eb-902e-7e0c029c4da9.png)

**Comment by mrbuds** [comment]
You can do that with the Cast trigger already, if you need help about the cast trigger i invite you to join our Discord at https://discord.gg/weakauras

**Comment by 152Makko** [comment]
yo im in the discord already u can @Makko there i would appicirate very much
