### ISSUE TITLE
Swingtimer Reset on Weaponswap

### ISSUE THREAD

**Issue by Nathaniakek** [WeakAuras/WeakAuras2#3125]
### Description

The Weaponswing doesn't reset properly when I swap my weapon. I have made a clip extra for that. A workaround would alos be highly appreciated. 

### WeakAuras Version

WeakAuras 3.4.1

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Make basic Swingtimer Weakaura, should take 1 minute and Swap weapons when you are midswing

### Screenshots

I made a clip https://streamable.com/he1uyi

### Export String

It's most likely every Swingtimer WA

**Comment by mrbuds** [comment]
Can you explain in which context is it relevant to have correct swing timer when switching weapon ?

**Comment by Nathaniakek** [comment]
When I am dueling/Pvping I swap to 1h shield very often. And it is important for me to see the correct swings, so I can SealTwist properly as Ret Paladin

**Comment by mrbuds** [comment]
There are 4 swing timer on your clip, can you tell which one should i look and the timestamp where it's wrong ?

**Comment by Nathaniakek** [comment]
I showed 3 Weakauras which are topleft and in the middle. They all behave the same. you can **watch the middle** one, in the Ret Hud. The Swingtimer in the bottom is the Weapon Swing Timer Addon to show that it works correctly all the time, while the Weakaura Swingtimer does not.
Timestamp **12-14sec** and **27-29sec**.

**Comment by Golrathcr** [comment]
I am having the same issue. I made a video that clearly demonstrates the issue and how it affects the accuracy of the swing timer.
https://streamable.com/ws1s0e

**Comment by Nathaniakek** [comment]
There has been opened another Issue that is related to this one. I hope we can solve this soon.
