### ISSUE TITLE
Condition: Frame Selector Action Button Glow Bug

### ISSUE THREAD

**Issue by romeo2487** [WeakAuras/WeakAuras2#3126]
### Description

When you select a frame to glow per "Glow External Element > Frame Selector" under conditions, the glow will persist indefinitely until you reload the UI regardless of combat status or triggers/conditions. It will also persist even if you delete the aura entirely. This issue seems to exist with the "Glow External Element > Frame Selector" no matter the type of aura Icon, Text, Model etc.

### WeakAuras Version

WeakAuras 3.4.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a Text Aura (or any aura)
2. In this case it will be Execute: Trigger1=Action Usable Trigger2=Target Health%
3. Create a condition If Health% <=20 then Glow External Element - Show
4. Choose Frame Selector - Action Button Glow
5. Select a frame on my action bars to glow - in this case the execute button
6. Kill a mob and the glow will work as intended, but it will last forever until reload UI

### Export String
!WA:2!vw1ZpoTXx8nYIwKvvBji2wv4WQfi0Lwrxciqi1VABCWrbiSj1Xz3TcPMm2ECSb7zSMzC2n9qpe1d98(NqU1R5qpxXHEEuup2t7HVsThAL2)bOVzCa0sdc64d(n)6Z7nV3N37vQr50YbLd(XRZO5IKycM1UNBR7TTTJpnHYUFZT(J7Oh)BbJSpliMNLGg7Ipq0pKYsrI(WxCkUFWyckn2VViIH5r0KGXZ5rOa6(Ft7WqowCHvMHi(ruwhAmr4v3EBxBNS1wcGzfawmRu2h6NZf0u1j6LfGeyh8imrCekhwfjI93noqezvdMYq(IykHFlhUaXeMEHXKyEKPf8tyorWIhoeZ4FBf2cX)VLyCg2HNHtsoIN7PrUBEyy8bZ6xVwx3(DDR54ona7bl6cNL10UvNg9ALDMCoU)qm4)I97gr3VnzG0CEnTbSwpoYlb)ce7WWaIoD7y3Q1CggL0vPWTrPyM9by)CbEUcn(ZxDWeT49c4MZpHkoIR)vNc(x6(ehWLJ5Mw5WZZt5gXSdvajahXtgC4lW70D(5dZjlEZMvKL)v5zLxsEo5QZHxKpyHrGrjIQE9n3uA61uprErt55LxqUMP8sEG7CiwmrbUszdkE(N4YdYw9eZ7tHPiiOS(x()KFK8JLFQ5miA)4Cc4JgHRIiJZodsl7wyzpKgGpv25xkLOqWrXmcogiqygbLSdemb39JoKJtcl4vwTDDB)WPcQ)OInpDNZzfsjI5nA7u3(UR19R7vZXEkeACWdvKfZLYQp5tbYvib91CLWekL92Cf4xAFvaYHaKa2eLr0n(7Wx5qejwrCPKBjF)gpfJ44UcgMmue9UYZArOe88GCM(eADY4yFkjGprDufjuw3kfftAiTGliRlVR0w2a()bV6kwjuuqOMtOnIiiqMa24QoP5jIyZPQD8PPEiXah)eeNVQ8bMwaXXVqaSxLWIu59ksLnYUYB85xSO325PEy2uL5hRtnVAfh)iS)tAilFQ1Pza3yYielwLUi3WzekjhV(n2K5hHidX8pPICN7B0CRF)c6rjJjzmfTsmwAur6cG85RuGISx1ABFxpn28RElzzdzplv2IChdLUK9KBi3z9QBU447Evf0LAU1FVLEyyi3tH5oHhpmHUF)qge50E)5nCQ9q7U2TSR722zME3I6mYhnvpROWzjWo)RVxpmouVU(2E5cbL0gC(G)6iDrJxCNbtFPUwu6WsF87i37PQTa3RMOpLP5QQyVLawmBJLeaU(1wwiqw)TGSI88y4rXqX1i2bfb5MFvZvENvGr2fF9f9Zyy)yvwMrwL3OskEYEaximEO5sHn7vHLnEH18ld)ZFARN9SNT0ogIt2XO6B0uca8trjVurLypg6Yeho2QLDd3SV4)GhRFk6GZSECWXlkLVwNIdozFklyxgkBYUleMPd0qUosGmoUOByd1sQ4Qx36o22BV8G1RRfB184Gz3(jEO7CJBVP4bhmhAkcG2otNRPR3(CSo(YN4bC5zfP01l4ULkzmfArHd0nt)H3BwmPq3aoMlTK8ZfK3Sm35gx7MxRA5r)2E)Zp

_No response_

**Comment by mrbuds** [comment]
![image](https://user-images.githubusercontent.com/189656/120725095-79794180-c4d5-11eb-9cbe-da37608ae699.png)

**Comment by romeo2487** [comment]
LOL thanks for the quick response.
