### ISSUE TITLE
WA Version and Game mode in addon select screen

### ISSUE THREAD

**Issue by jec324** [WeakAuras/WeakAuras2#3127]
**Is your feature request related to a problem? Please describe.**
With the different addon distributers not all the links work to directly point the user to the proper version for the proper game mode (retail vs bcc) and what version they're on (3.4.2 or 3.4.1) etc.  

**Describe the solution you'd like**
It'd be nice if the addon "list" prior to character login showed what version and game mode it's used for.  For example, in the addon screen it'd show

Weakauras (3.4.2) BCC

And if I was on Retail and I saw that in the list I'd know I had the wrong one installed.  

**Additional context**
It seems like a simple problem that shouldn't occur but I've had to help multiple people in the last few days to install the right version in the right folder with the different addon managers like wowup and overwolf.  Being able to see on the login screen exactly which version and game mode they were installed for would really simplify the problem for me.  There is an in-game display chat that says if you have the wrong version but 2 users I helped earlier don't show those info in their chat windows.

**Comment by leobolin** [comment]
Wouldn't it be better to address the cause rather than the symptom?

Why are people installing the wrong version?

**Comment by Stanzilla** [comment]
I'm not a fan of the idea. Yeah it is a problem and will always be because of all the different sites and addon updaters get it wrong sometimes but I think the in game warning is good enough and I don't like extra clutter in the addon list. When we switch to multi-toc I might eat my words on that but for now, it's a no from me, sorry.
