### ISSUE TITLE
Adding Heal Absorb to Player/Unit Info > Health.

### ISSUE THREAD

**Issue by Surarn** [WeakAuras/WeakAuras2#3129]
Weakaura checks for total absorb on units but does not check for "heal absorb", like Necrotic Bolt effects. 
Trigger: Player/Unit Info, Health
There is a "Show Absorb" option, would love to have a "Show Heal Absorb" option aswell

To implement this i did a few changes in Prototype.Lua and Types.Lua where i basically replace
UnitGetTotalHealAbsorbs() with UnitGetTotalAbsorbs() and 
UNIT_HEAL_ABSORB_AMOUNT_CHANGED  with UNIT_ABSORB_AMOUNT_CHANGED

as such: https://i.imgur.com/xpxf01t.png , https://i.imgur.com/97qcaXu.png

https://i.imgur.com/yCsVrTI.png

**Comment by InfusOnWoW** [comment]
Can you create a PR with your changes instead of posting them as images?

**Comment by Surarn** [comment]
> Can you create a PR with your changes instead of posting them as images?

Done! First time ever doing one so let me know if anything is wrong.
