### ISSUE TITLE
Allow variable names in default triggers (Crazy idea?)

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#313]
I understand that this one might be asking a bit much but I would find it very useful. 
Something like:
https://i.imgur.com/cP7Gr8p.png

The inspiration for this comes from the wanting to make Auras that monitor the off tank without needing to focus them. 
I think the other major use case would be the fact that boss UnitID on council fights is often subject to randomness.

Of course it would be very easy for people to do stuff that would break if they did it wrong or didn't do it before the trigger tried to call it. But it would open up your default triggers to "custom" use, without people needing to rewrite a lot of the stuff that WAs does so well, in their own custom code. 

For example, I want to make a whole load of Auras for tracking debuffs on the other tank when I raid. I can put their name in if I know it will be the same person every raid. I can use focus and be forced to use my focus only for that while raiding. The other option is to run a snippet on ENCOUNTER_START to get the unitID of the other tank. However then the simple Aura checks that I want to do for each boss in a raid, become kinda boring to write in custom code. 

So, I understand that the implications of this would be pretty deep and it's potentially not a quick thing to just add to the Addon. But is it feasible? Think it would be useful to more than just me?

**Comment by InfusOnWoW** [comment]
It would be useful. But, I don't think this can be added. This would require a lot of work to even figure when and where to evaluate variables. A solution on when to reevaluate them. 

I'd rather add fake unit ids for "other tank" or "named boss".
