### ISSUE TITLE
TBCC - Instance Load Issue for all TBC Raids

### ISSUE THREAD

**Issue by aboose-aboose-aboose** [WeakAuras/WeakAuras2#3134]
### Description

![image](https://user-images.githubusercontent.com/42923683/120916176-e408b980-c65c-11eb-9373-f7d634a20ca8.png)

When zoned into Karazhan with the above settings, WAs do not load. When unchecking this, they load, so I have isolated it to this issue. Therefore, Karazhan is not being registered as one of the above instance types, so WAs will not load. 

**THIS IS ALSO TRUE FOR GRUULS LAIR AND MAGTHERIDON. ALL OF THESE ZONES ARE NOT BEING RECOGNIZED AS RAIDS.**

### WeakAuras Version

Weakauras 3.4.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Go to Karazhan or Gruul's Lair
Create any Weakaura Icon
See it appear on your screen
Now go to Load tab and pick the above selection which should encompass all PVE zones in the game
Weakaura will no longer load

### Screenshots

![image](https://user-images.githubusercontent.com/42923683/120916201-0e5a7700-c65d-11eb-88cd-2c23b6035a59.png)

### Export String

!WA:2!vs1YUnsru0yIqmQfIhrbRrIhYeKIMiboZyggKisKXTNoJd4xQD7jterYU6UUT7As7QAQQ6y7S0IfiwMpbVy2aIf(ti7yxRri(aYNq4hGB1TfSa2qj1QRQUN6wN7Jtv6OTMSfDl6p(jsrQoMXbz3bEToUJJBGiwi)MMhEZT44pF9Mh(YYMXx08WF9JmJJ3CfLPsIjZ9Gz6KYh1TXG(voT7axlV6D(2kpzq72N(XVsfrOIPN2nmub6pyJveEqKq2tW4A)goD8CCtENGuLwmX4MbjuIg8tZ)vlvgN8(rADI6R2F)PKXIQmX(Y5N8zbQj1(Y9FGKeOzcU6rUknrQT8dzCMkAxxLiLttE4XCnidjbWz1P0UC1zNaKZRNkjQZAdug5S(gCQZAq0TbX0AvfJhVGkgMF8iB0z6D9li3owwxHwkweTqlzJhdsvNDLRN(h265jq22RkGm0SYhPLovT0pnmSFKyAx(1Q8F1rEFb4cxaywOjqI1r3Os9Zx3tcHSzU9750QLlNmbuw)TT(OJyZwnSr9(Ed77v31BHkbIJpMQSY2oXjmLNNrU3WpnGKQG9SyHv4cDLbyO4mJP0Q7TtOaP4o7vrhbCljOtL8kAzkybCQ5Zniccop7dlUsvY29Av)uh3H5f4HnAwVZtDEIDk6rFt1hKlPGjc9Wiw20PvVJg06Qu(68szKx1)p51)hozA1ErUtUaQr4ZtExs(CVIlPTGc)Yg3Ym1Boj(zyLbVTVBXuHKEIKKS4K1tSdfC91T7B7vXMCPqCorErb4nTJfe6lxGSBOIDje5RjXy8x2DsASMz5getuQYzhyTKYWQqaU78Y(kgFCm4pzUoIfSYCyCdulLejVuWbSW8A2yjkWCWBmM)NdpsUg6UzFTB(KSd2nZzKTKWOJSnKWyjb7SNNDWfznhTqfaCIKjgTiuG7oHWhvtd8rl1trQopeZiJ8lMJqIHzm)yWagBDq39BRvJpVqnU5sjmgdDtHZwJQp5ScdLUsbXHfAu7UEEDBVmqWPSCXM1RiPAuc3nPyPVcMG5q3hu9(vV)sTiyDc9o9EVDy0B70TsXldy36tD8KZlUIMpE6p9ZpEJnkTkuI9491sIMS5TfVoCKzldR873W1XPJpE7HSXw1sz0vj64OtRlsoEWEYxGAnw48S7CdYjXeIMfCcJQJSRJlxveSnYFhRuPsBUe1oanhWp8MRyCmhAoIGxo5USXCHewhtoMgFhPuivJUIWzfOEu2B9SS76NibK)laIkNI2CSm)kk(OIbtUSxQat6sDTbdgzaFSo6nYo3oKqb7jegh9t25zXztY4zISe0MVp(MtaK92)BtzF)wk3pV6dRwBRl(9N)x)

**Comment by aboose-aboose-aboose** [comment]
Originally posted this as Karazhan only, but confirmed SAME issue for Gruul's Lair.

**Comment by raethkcj** [comment]
TBCC is using new DifficultyIDs for both dungeons and raids:

https://wow.tools/dbc/?dbc=difficulty&build=2.5.1.38988#page=1&colFilter[0]=17
