### ISSUE TITLE
Strange black border on my screen created by the Weakauras addon

### ISSUE THREAD

**Issue by jimster100** [WeakAuras/WeakAuras2#3135]
### Description

There is a black bordered box on my screen in WoW that i cannot get rid of unless WA is OFF. It still remains even after deleting all of my other weakauras. I know that WA is doing it because when I turn the addon off, it goes away. Please help!

### WeakAuras Version

Weakauras 3.4.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

No clue how it happened.

### Screenshots

![Screenshot (45)](https://user-images.githubusercontent.com/85460188/120940091-676fec80-c6e9-11eb-91e4-e250d004a584.png)

**Comment by mrbuds** [comment]
Sorry but we don't do support on this bugtracker, this is not a bug in the addon, if you need assistance with weakauras please use one of the help channels at https://discord.gg/weakauras
