### ISSUE TITLE
Focus target taking priority over party frame dynamic group

### ISSUE THREAD

**Issue by Zyin055** [WeakAuras/WeakAuras2#3143]
### Description

Not sure if this is working as intended, but when using "Group by Frame" and selecting "Unit Frames" for a dynamic group the auras apply to your focus target in addition to your party members. In Classic vanilla the focus target feature did not exist and it only applied to your party members.

Here's the real bug: the focus target appears to take priority over the party frame. For example, I have a weakaura to show when party members are drinking. I have the tank focused and it will show the focus frame drinking, but not his party frame.

### WeakAuras Version

3.4.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1) have party member
2) select them as focus target
3) have that person drink. only their focus will have the weakaura applied, and not the party frame.

### Export String

!WA:2!Lr12UTTrq0kl0B0PTokjQ5gsvdACTdcKJCCCckqqHPSuSBvCuiLClQrQ5sYvIBn1Ue7U036BcTP5P(G(e0NG(eYxWaJ(f4pH8qFUZskNK2(c5YLZo7CoZ5mf2UKY5EvxP6YLgukSu4lxXUVuCGJZMpEJoN6lKHuPnjyVqPijzo7y2XhtKHv6ieXAwI8WN2RNIQF0i8qPjBgi4xEMlS)W(swyNJsO30z9j55OUiwi)UcfkuCiME3esaT4YPY4KRfP1jQVzPLoG0xuLjws9WgpM0BZ6dwQMKeOzcUAvhLMi1w2motB53dFPISgQLS(9Ps1vNxoD5lghs9t71ZC3YnA0QDZUTS14hoKujz5HQeAC8MHkRtvP(09PCTlgn7Wj7wFn3o762znNoV5xTLu8xoUTB0QLDkEZ(jXKJOsNS)6VbLeRJC4KbuL1Ou(0sWAsGioDaphI(ssilv9BNBeHZgqmOzv4tBcxYMl40tcXQYS3UMAuQOi)fQEfLOOUAjL3xh9HdnFzWdCl7beghplClyE4RHf(qyrC5C)3DCiXS(C)6n2QtdhjYCMYQGCF8cWRQ4yeFo0(gE1kzUufDnEqKq2Mk7Iy0Zowqc7nc3F3GyIsf5RjXiEl7mifB5wYJXchPWzSrYmOmSILtwCMv2k2XuZIH4XBXgW0rN4pv8KlakwSy7I3T69Dug659L5ScnsEuUqQGJkaVUIVMX1ujNeVDEvVJFUmkAC(7gHiMQvPn7qA8yzgAmC0Rcpc7hSGm140qDXA69pH8UGCu3T2SttN1EsJLtzHtAUrB1612U76orJiYGwze)Vv2j2GGzN0tITySFq0KINIDiKr56MO0ui9DwB9n76ovJVjhrqXxL)roE(yFfDaY8o1QE3Q1gRfbtBdFu7lDtwyszt5uPP5gQ0gL4hvXgfKQrkACV2cKeG7mYyM(bwOoA2xNJISWnW13TUtJgBzResnClFS26X6BDcjvJr90KmVJ14EPXX1zYGyQ3KP0qwMlo2i3y5rnHX7jK5k0YjxgfqcjDAkAy07nKsHu5HUxDwqfkfC1xwDmdZHRivgqV(7b7ynoivPfd6qpupd8OcWZH7CsaoRiuCa39awc1lzU3gs3KqS5d34vNfIPT6zBYPhC()CEO0FpwfjoOEmQ5uEsuvTfcDp4YWvqrF5HN5FkvdUb8fW1DYA8WvHRnohbUip6bFULmLN5AD0Sb0qOI1iZaHmV7TDwxY47n2wIURknfIWj5drQBK1Z7mG0Nf45t5scwCWfGlcFP1KqM6xs544P9Plt4hLuAkQYhc0sGNjzHEzri4lOxSIKQtL8k6DQ98keEyfUqJFS8ZRq5HjNNKLPPN(jIqAr4B3517rPjRzSzAhdm9GVkF4X)EaWT3gUKFIKIYTSV)vNK0yf9Sq(FZhWzKkI2WC0iOAryjl)ikRFK(zqTxa3FgKnYOX59v4QykShSszypVSzcgAugb3Z4YNy2yAWrWdmBbRM98HMNNQ0SG9oA9P9OOHN1L9GzHZbFcIL59ZPTKhyAh7s57xDTWWS29cVzh0VPPvndGVtL3SzUNFXrHIDZtre8zZd)(nTSG)icMdxodUizU3XXK9i5kUDBIJUrhAIXVz8F2PATGxdQd9HUWDGnM4MU633O9YRuV2JDcoBWvrNdmUWNHZxtIifXM2BZn6Dr1ve8blAJUpHxYfpdSgD(6mfXpMggbpdCa3CV)P5(9mXhsI2hledkaTMf(HjUnA1OE(aQKl8UjQbFAE(jl8yMrj0Ot7hloWKlwqAmv9XWpBb7wg88gz8rzZKkuA))6h)N)

**Comment by mrbuds** [comment]
Please create an issue at https://github.com/mrbuds/LibGetFrame/issues/new and specify which addon you use for your party, focus and raid frames
