### ISSUE TITLE
Could you help to add the similar option "smart enemy group" as "smart group"? which support the spec filter.

### ISSUE THREAD

**Issue by OscarJxW** [WeakAuras/WeakAuras2#3144]
**Is your feature request related to a problem? Please describe.**
I want to create a reminder used in arena, when the healer of enemy team got CCed. So i can do CC chain or cross CC immediately.

**Describe the solution you'd like**
In side the trigger, unit type and a new option called "enemy smart group", which support filter of specs. healer, dps, tank.

**Describe alternatives you've considered**
not come in mind yet

**Additional context**

**Comment by mrbuds** [comment]
There is a "arena" unit for your use case

**Comment by asaka-wa** [comment]
Specifically they want the role filter for the Arena unit type. 
The info is in the API (AFAIK) but it can't be done the same way as with group members, so requires some specific handling.
