### ISSUE TITLE
Creating a Thrash aura in cat form with Spell Known load condition causes it to unload when shapeshifting to cat or bear.

### ISSUE THREAD

**Issue by PaterFrog** [WeakAuras/WeakAuras2#3148]
### Description

Creating a Thrash aura in cat form with Spell Known load condition causes it to unload when shapeshifting to cat or bear.
The reason is that cat form Thrash has a different ID.

Workaround: Create aura in bear form, or copy Exact Spell ID over from a Thrash aura created in bear form.

### WeakAuras Version

3.4.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Be in cat form
Make a new Aura
In Load, set Spell Known to "Thrash"
Change form to bear and back to see the Aura load/unload. 

Creating the Aura while in Bear Form doesn't present the behavior.

### Export String

!WA:2!1z1tZTXTvCtZQQPCsITL)tLvsSzKtyTCCLLPIDI9KmD4krzlpYuCwsf7upziWUlixeTCxuaSsI(ulp5ELtBV0EOLhAVwjNA3t9Gs)ZrJY2PFa4H(bqh65(a2LswXYsZqG99E437HFpG3dzwAI2t4nH3tMPp1nkSwum3L8ohZztCROLxSxT1)c5N)X3Vs7b4yPFeFvMKgfkYX7SAZMcImZo4qxqE1iAO0zHYvQx2EGBuuGx0MH12KYiOIX8GJBPbh1vYPTAr4I)83nBbE6hp5KdfXoKniHYQCst6w21QwELvSKDyeBbJeeyBuYo)cP4MVkpQfNie5VCnT(z2hGAXnba2PXcLQvVrT6LSRZovSG0OfjKWPU18J2C1q0oArU(yElIWFWH01xadLc2e3ryhIBte5gWj4aJBQaF7u3NJHfPrqmsiQRz6YEICwXHuPdla3HW7TVbtM53vHDA9AiBHDLhSs)EAHso2DDuFpIde(1HTn)ULxP6sRTsV4Wuskxb1B8F5GXMvPoT6mCGiwnmOdAqBS01Nis2a7kmdLCL0niQt5Cxi6L(QZNBpyXL1EVwsSIuxWrQPaP6DZPEt1BTlog2AALupXuoxFUB(jZpN6e2AXf7P)1qitPEB1L43TK99Hau9bMatvWxnNwXLvZO(bi1Puxb8O6drAC1WFb1vv)qaZBvCUBbyQUMEhOUK66ja8Kt2pLqDx2Zh0Fb4)l2vlRzeVT)q9mSJiI7C)ipcsDwK67pmzNo6qHXAn7JutLXjbQcocAyRaYlSBhhiPfEb6FIu5NmZ1(lQ3bIs2jRjHJVKRTe4KRvc2HwA3Do1Tp3yi10iiaF)Ka8zMyshZ3qVUZSg4N8laNGa(eo8iKuxHHd1bbfIP2oyiqGD(hJ0BfnBSpy)(dbM6Z02awE(eAsZyjMUJhv8vXHMmPJBSqg1MnrYy9KtfRe1I6YUAtJrrHxwotU8CImMhMx(OIFz(iom(rPJ34lZrc9yNcBamfbnDoMM8Rd0OKYq7ToHWkPPpPngaf1tqcAAUERghoIkWa8yjXNVbCpgC6n6dx(SjT0LfUYtUi79KKTKnm)OjtSSbRHK2M0GXjUu9kY2BFtS(GIZYy5FLLastwuY3z6ZJKGtRRxsLvRuMDsJ1cFmK6xikiIFVmzYKDqsXOhMwBAyIrJIFRsRvFv2PncHQzraWu3hq9K(wLGp3ljaOBr8mc)zSZFeBLKjovIB7q4P(7ls93Ugt)kidrB2rno7sV(91bKbRWrALhOVno4adZWE7J0WKPQhYE)JiAFvuuNGd5lTvSl86YuJiDJkxd7Mf(RxQPHYHvRNVgouKVcMd1HgSVctXRvxR(kld5OjEPC0ikI9HVEoXRduGH62q6d129HB1DsaEZiU3d4yw3hKojHN3a2qobeu6zHxQpeq9x8iDdpko0RHPXsZGOi(HcXrNAoy3uJ(yY8SzED00ReVzyV7ry7bov1()mOvq0MlXj)KysOBNQFN5MT4nS0Y81LoUtq6PzuxTmnBAxfoqg0x)5kKWws)ZUJE(i(SxRrl5EzHlajzxTmJvp8LTQMloGK1ea19PURhcnqhZOzfkm)ugFybumH774tOT8LLScIWE)pt3ogrc10Kbe)HUbyHaiCptf7cQB9cOI5lqq7KaOhmu(mNPd7geWnG9wPwLvD73cnoI)4Oqc0R842gCaf2lAV2YlQUDbR7x6oLrQFoY0w0OgnC)wTRhcL5rj9rPTcJ4MMH2qdU2jnKtD4A0K2QHWtc4(SZ8T67Mat)dMdDNRAjGCToY1v01LYUPTa6okZzrHs95CAcdc)C95McD6eJk3o0WKKmi5CSjtcP0hivw)AKYWLdUaPRJRFrWYWtGM84V5XSp4kfFRKm0Jkgt92z5F8TCjS78jXXE7bhJj8qCWNNuL9r2BQRjT2on5WEUg8Ibjol7mJEPLUW4IubgUp4HS0f3q9LrUPLONmtJF50uVDtE7s(lVawoJ1JJIAxn7CZoVnoG5JZUxYfOL04R3Fo1wWUC5kocsBagNRplCuDohyl0K2khNgQXMG2Dueu2Rfb1hu7rneW9kydpkXD9LuVr2UBG5uDSXolnuOFIMlfOhBIW8AtH9g4GyswhZcetDtyjQTT0T3vpndhEOwi8qTPkOE69YC3F0Wb6)(xzZ2LXJGQnYoQFDb1Fe8Zvp20rSP)0ptTDXsvwu91xXitT90RANQ4RVcG9yQTv)jayq7yJwWqYwmk3KjRdxTvpDI5b1JR22bofaXey3eFkiTO6z64aPEUUR3SfNvFNb8oa73lfw1ZEmyXVzm1Z3ln5AtcW6wUG4yqANxr6mQNR(PPJ)wy89upNDAn(xF2dvl6CG8jFj5hQB3rRmTorsio2(H4uG1Q)q3rjpupCin5G8nv)ILuNWkeUJUlbl0h1mLDgFGxCcbzkLb5EDUw0vBJ56W3y1gtdH1Q(g1FDC1Ft93v)dy6V6BlzcH98Z(rZwCIn(3p8)d

**Comment by InfusOnWoW** [comment]
That's a bug in World of Warcraft. It returns the wrong information for IsSpellKnown(106830), even though that spell is clearly known as it is in the spell book.

**Comment by PaterFrog** [comment]
106830 is not the correct ID either, the one that needs to be used is: 106832 from this spell: https://www.wowhead.com/spell=106832/thrash
