### ISSUE TITLE
[very minor] Add progress bar "stacks" (region) to Condition properties.

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#315]
Someone on Discord wanted to alter the colour of the stacks text (on the progress bar's icon - WeakAuras.regions[aura_env.id].stacks) That's not currently included in the Conditions properties.

**Comment by InfusOnWoW** [comment]
Yeah, I can add that. What was the use case though? Seems strange to want to change the color of that.

**Comment by asakawa-k** [comment]
The had something that stacked up and they wanted to change the colour of the text based on how high the stack got. 
It's the kind of thing that people do a lot with icons but, yeah, I've never heard someone talk about doing that on a progress bar either.

**Comment by InfusOnWoW** [comment]
Should be in the next alpha.
