### ISSUE TITLE
Instance Size Type load option not detecting TBC raids

### ISSUE THREAD

**Issue by VictoriousMakesThings** [WeakAuras/WeakAuras2#3153]
### Description

When selecting instance size type 10 man and 25 man in load options, a WeakAura will not load when zoned into Karazhan, Gruul's Lair nor Magtheridon's Lair. None of the Instance Size Types seem to activate while zoned into any of these three raids. Have successfully reproduced the issue with other players using the same version.

### WeakAuras Version

3.4.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a new WeakAura.
2. Go to load options, enable Instance Size Type for both 10 man, 25 man.
3. Zone into Karazhan, Gruul's Lair or Magtheridon's Lair. The WeakAura will not load which does not seem to match expected behaviour.

**Comment by PhilipKolar** [comment]
Same issue here

**Comment by Baswai** [comment]
Also having the same issue, exactly as mentioned above.

**Comment by JackTheEgg** [comment]
That issue has been fixed already and it’s planned to be implemented on the next release
