### ISSUE TITLE
transparent nameplate auras on unselected plates

### ISSUE THREAD

**Issue by Comfarol** [WeakAuras/WeakAuras2#3154]
Is there a setting to make non selected nameplate buffs/debuffs go transparent like the nameplates.

example. If you have 5 enemy nameplates on screen  all with debuffs, you have one of them targeted. The plates that aren't targeted are more transparent, but the auras above them are solid colour.

**Comment by emptyrivers** [comment]
Yes, that is what the conditions feature is useful for.
