### ISSUE TITLE
[PTR] Dropdowns Not Present Throughout Addon

### ISSUE THREAD

**Issue by ChrisKader** [WeakAuras/WeakAuras2#3158]
### Description

Example 1:

- When changing the anchor of text on the display tab, upon selection of a different option from a dropdown, the expected subsequent dropdowns either do not appear or appear in a different spot and not not be selected from.

![image](https://user-images.githubusercontent.com/633360/122062595-2ba5e880-cdb5-11eb-9188-4c280b1f8b19.png)

Example 2:

- Similar behavior on the conditions tab.
![image](https://user-images.githubusercontent.com/633360/122062693-41b3a900-cdb5-11eb-9817-c2918c457046.png)

### WeakAuras Version

WeakAuras 3.4.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a new WA, add new text and attempt to change the anchor options.
2. Create a new WA, go to the conditions tab and attempt to add a new condition.

### Export String

!WA:2!vE1ZpTXXxCSCIALtpKqsJsBQQ26QgbbxAcoH2K(Ls8clbhzSTwBcjnQ1mE3XENW6DhnZSaovvQbPkLBvIJ9Op0t9e9FGi(lyeQ67Fa5CpH6923mRTJnyiPRqWBEV38M3p(SFMLelnERXDh39fFAhItyqLWiMdojB7snAWXILFj9x(NFASXgJ1URI7v7LNbwp2EOahVqw5qsGO(cwfRAzFGtyOVB4wbv2IqXRVFVLwUnXEMQOV(ocgPztmJx8ASUI)FtrBkUUtexe26v8O64nXbIkrnAq2EVAlKRs1AvQMZU6EXEuZJ4ITfKwyxBTN1xgJ8fEMrberDQpQnMfhco9Nlxi3JTSRzBDFRI1SkMZSG1IgdPCX8vI1UqbRvVBLYwfkul3Q25QLRC5c5TwCqv2wRu6HdRQRx1wSufRr4Qw)oCk23pVlpL892(mbnIcCeKWGjq((CbsG5zm05BgJAzmG63Q)c1A98OiQfUNMb)joYl2vi2lTyfy2e6NXafXqvH2li1kmkqmzkd4H0i(enMBoJ0JSDK2q4Hd0oREOmykpr68fnwO0kM5QMEY(M6xfp5gFNXCg)qFdQhUx4wGsblcNzydcKZgCW0ngwVJhkOj2DK7HYcBYWCUQEahsRXaPh2hxOEvnxW(mdBbVnLeBRkSpW(9XcL0etAm1r91bXfyg4ZaD)HCafjcxgWHhlp)X(smSiIfOn3xNwah42BimrVPTEqCCyvAJqMXBWhne7uDCqSy6jnqbU9WnkpZM9M3j7DgEC7h6G8nIFxsv8XDRvHxWuRMiDSLbabqT86wLkQdS3HI8BeXCQOMHqoXa6J7WPbHEBHrNou6)kC6TcsDQWQHHwNe8QhYQ3Ftbc9ynvCS7PB7rux432oEyNnKxWoaYeEQ(8ULzyG31wdF64IRd0WQgfBzRcLxA1c7cT8yA7u75s4pvZLTjEguqB6fqA5QX2xj0f)7JDiWBGzbi)hcC(qZ6jhUbgtZb4phHTQ95Tlh73qFlI8SWbYrcvFh71bYiBCtyp8R)IlrhxG3wuJ7HGluEu8vrjOFGwP(xnczTqGdDfmdcdW723C6pJtp)aryHq)q2dsKirYxfRTxo0XSu1QLwPG1svPxuBsntGasCwJ4c3YKdwEy8js2g7Qv(8dIVl8XDZR912Fk04jnAdvflu13RcknlwQOL8CmO2u(0r7OJozscp72TuG8WABQcKUfQ9qLEVJ4aTUTczURXq0DwRRq8jVjHtQ7JxVBjpWf17MVyrGRVAPYh0)OQqEgE(UvWJgk8kR6HFPvRwiFrRxKwE9eYPKzKFE6pJsnow3FMPP1uVo1DDc506ESm7ZLZk)s5DEWYZ)Bxw98(jxE()4I6NKY)xc5CYVro)6sZ5LlmQPkTRG88YVqEw5nLZiVvc5TLNL(PNCoa9phIcZLKE1r6v)yEo5x1TjpCxqEx5xt)KrKnhn(dU5Eti6uNCQ52gERJ4ut4bZyp4JKAtN8KoMr47hFs(2TTpI6n7a17igCzpYGBe91ShVVkVhmbM6K984PUCrPvDpmPPN45M(Hi3LQlq(aTZLTBf5liPmvmdxwUwkBhFeNRKm5aavj0HPPduis57Ea8Ej0TlrvuW8u7IciT00XZAdSCmXs7JrCCfbdh0u49oWmoZb9y01KHmog(Gux(ok)0XmJzlejyjznT3Y1LizDzM6nibeU3rvVhjiUCH4PPcv34LhI4vs(R)L5ZcdBLGH0FNhFw53Ns6MYeIJivhrOZMXCHxjrT)onXD)QEmc8fBy8gyM9Rjd2RbdOMHkajqjT3st0mteXDpCE0TfwM5UvUVToCGnintbFEMkOyVdJbHlP2QQOQxzbBlRI2iFQhkzhvft0j1hEn5vNvM6JgBNnrmccOl2He4e2QosyVjYpc(xaIViLF9uP2P3xYVo9s9ev0zls4QD66no3o703A6SJV5F(O)n

**Comment by InfusOnWoW** [comment]
If I'm informed correctly this was caused by a wow/ace 3 incompability and is fixed already.

**Comment by Stanzilla** [comment]
It's a WoW issue and they are still trying to repro/track it down

**Comment by InfusOnWoW** [comment]
Or that. :) It's not a WA issue though.
