### ISSUE TITLE
WeakAuras.CreateFrame() is being called on ShowOptions, but is undefined.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#316]
In particular, [here](https://github.com/WeakAuras/WeakAuras2/blob/df6edf8a87ba91ca13c246b4d615489a640cc3f9/WeakAurasOptions/WeakAurasOptions.lua#L1265). This prevents the user from opening Options, and they are instead confronted with an “attempt to call a nil value” error.

**Comment by nebularg** [comment]
Do you have a stack trace of the error?

**Comment by emptyrivers** [comment]
Not on hand at the moment, no. The person I was talking to who encountered this issue only needed to type `/wa` to reproduce it, so I imagine it looked something like `ChatFrame_OnEnterPresed -> WeakAuras.OpenOptions -> WeakAuras.ToggleOptions -> WeakAuras.ShowOptions`.

I’m curious why you think that shouldn’t ever be an issue. Nowhere else in the entire chunk is the `frame` value assigned a value, so the if block with WeakAuras.CreateFrame() is all but guaranteed to run.

**Comment by nebularg** [comment]
Assuming the code path isn't helpful. If WeakAuras.ShowOptions exists, so should WeakAuras.CreateFrame. ShowOptions isn't called in the main chunk so CreateFrame being called before the addon finishes loading seems unlikely. The only thing I saw was maybe some weird situation involving combat when trying to open the options.

**Comment by InfusOnWoW** [comment]
Yeah, that can't happen.

WeakAuras.CreateFrame does exist as soon as WeakAurasOptions loading has finished. And the ShowOptions call you linked is in WeakAurasOptions.lua.

I'm assuming that this was someone updating from a ancient version that didn't have OptionsFrame.lua, and that they did the upgrade while the game was running.
