### ISSUE TITLE
 string "Error in: Mag'har"

### ISSUE THREAD

**Issue by ERFmama** [WeakAuras/WeakAuras2#3162]
### Description

I have been getting this error, nothing is really happening that I can see - but my UI is obv. telling me it's got too many errors and it's crashing. 
I have updated all addons. 

### WeakAuras Version

WeakAuras 3.4.3

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

8616x [string "Error in: Mag'har"]:10: attempt to perform arithmetic on local 'topValue' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:595: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:768: in function `CreateFakeStates'
[string "@WeakAuras\WeakAuras-3.4.2.lua"]:3818: in function `UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras-3.4.2.lua"]:3794: in function `FakeStatesFor'
[string "@WeakAuras\WeakAuras-3.4.2.lua"]:2795: in function <WeakAuras\WeakAuras.lua:2681>
[string "@WeakAuras\WeakAuras-3.4.2.lua"]:2815: in function `Add'
[string "@WeakAuras\Transmission.lua"]:341: in function <WeakAuras\Transmission.lua:332>
[string "@WeakAuras\Transmission.lua"]:486: in function <WeakAuras\Transmission.lua:401>

### Reproduction Steps

I really don't know, I'm sorry. 
I log in and it's there, I'm not doing anything special. 
The error is there no matter what char I play.

### Screenshots

![image](https://user-images.githubusercontent.com/24800030/122590984-3503af00-d05a-11eb-89b2-2f80778adbf6.png)

### Export String

[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/6678274/WeakAuras.lua.zip)

**Comment by mrbuds** [comment]
This is an error in custom code of your aura called "Mag'har", not in the addon.
Solution is to delete the aura or update it or ask it's author to fix it.
