### ISSUE TITLE
bugs when open options

### ISSUE THREAD

**Issue by ztnko** [WeakAuras/WeakAuras2#3164]
### Description

last version that works for me is 3.3. every version since 3.4 have this problem. when i type /wa to enter options i see this picture https://puu.sh/HQ6Nf/6827b8192a.png or https://puu.sh/HJNau/790b9f690b.png
same on live and on ptr. same problem have several people in my raid. these bugged lines stay on sceen even after i close options https://puu.sh/HQ6Qt/b334817c17.png

### WeakAuras Version

3.4+

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

https://puu.sh/HQ6NX/665b4c8a21.png
https://puu.sh/HJNdd/9f5f4e0078.png

### Reproduction Steps

every time i try to enter options typing /wa

### Last Good Version

3.3

**Comment by InfusOnWoW** [comment]
We need your settings, please attach the WeakAuras.lua file from the WTF folder

**Comment by ztnko** [comment]
sorry. i find the problem. if was outdated for several years version of WeakAurasCompanion that stores updates for several auras. all these bugged lines was updates from WeakAurasCompanion. after i delete WeakAurasCompanion folder all works fine.
