### ISSUE TITLE
Importing retail model WA to classic has wrong model string set.

### ISSUE THREAD

**Issue by MacTwist** [WeakAuras/WeakAuras2#3167]
### Description

When importing a retail model WA to classic with the 'Show model of unit' option enabled, the model string doesn't carry over. Instead, default lich king path will be set.

Retail WA:
![image](https://user-images.githubusercontent.com/26745110/122780837-38c34b80-d27d-11eb-9ab4-7023a738ddcc.png)

Imported to classic WA:
![image](https://user-images.githubusercontent.com/26745110/122781179-8f308a00-d27d-11eb-9aa0-494cd1fd073c.png)

### WeakAuras Version

3.4.3

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. import WA: https://wago.io/2n3A6nIRZ
2. Click on 'Character model' WA
3. Notice model string should be set to 'player' but is instead set to Creature/Arthaslichking/arthaslichking.m2

### Export String

!WA:2!T3xFqUrY19rWL03jijEK8oY7ljR5qjsUqhwWDxsU3DKhpEayXUl4TFraSCpEK0adWmaZOfyMHZmy)Gws2HwrMLSkgRnuUQKkPsvBzFvoBvUQSvsCuCIIkkxrroYjTyuDcr2XjfLIIsKSDc)J8Hv5S596E(gd2f4e1D2vikU7IPNx)6UF9RFVFVx3ZWilFWMhu4Gg5prYtM8evwHVUAUXxFuLtKAmLC5FJdkCto91MRwndrZPo3F2w7c)SrfvDbr9cYxx850xwu3qwvjEmzHnsnXRXvOQUOOI(Qw15RKyxCyDi7MmWDRWxDjbDvTmQnu1p)admW8dmCYtDFELQsQ6tOZ3uS4AAIvkKjF2SZUoVICtEtG3JLUjVSYePnHBMwrvr8UcT0P3PewKUHyvvfbJBiYBqza5XUd(1cM6Ik1nLEK8gM86Mtq2h5Xi7NCaYbH)(4psLAYkYgsblE0wYcBU4Bm3LovJZRTy(fw3qSrT5vLvm3i9Cflo3mtNDIIBY6Y0IRKj7SfZMF0w6n0(qsMMAgN(4hhLJjLvpUJG84Jo8DyInMG59xHDL0gMQvTKHpvKsFHnLvQPQZg3hv7PKRROQloNgEPr2LfvmZQRRQBuEZ66QT0y8Q8M1qzhmE5n5hiVrv(gIdSHUyDOsO8ipL2nqHKmLrrTMbZkuxm9SGanDdvEH3Edb5A1KR2QH5AhoFt4pYrtBatYhMmuu9A8vX6IFpF1g8gg0sLvO8g)EAD(QmsVoWXCcg7oTHMyvSK1BziwIwjP06Qnyuzc9sfZrXVxH9DkPAlR5E19b5ROUcFJlYKqxUIHytqAvzKKdNCKx6U8TmHPblXt0nzJk)Ax3WuxUEDO6ZE01BPyDb06SV8RLULISzfTg8RjQVHGyLw1QHIm9PYo98tSW0BGfuqsDL5uUJb9pPaXWYI3agAnAadYO5fXzLktjY3WuISV08GQ59mAvHwCbO2YRUzPmPkuSuHIPYxmVcmtze1HI51fbkYxy(StpT2b4PmViRVnJQG4xCxBkiB8XBPqVXO8nAyniZPat8p59yxK2ADL2(t3q(6xNxxGROQkm)PPZM1mglnOSBgL8erjhkAfqtOMC9OhC5V1RFq(OhS6)0BEuTdaTdS01uSKUQjv9lcipm4nXLAIsKN7WKyLjrRKzHcWIaYhymYhm4shYtCXkA6IqhlDnEbrSK9rUQdbh6IWf)Cbl9WBAuu9ectUYfUWSfjFiYhw3uCvOrf1oDoCYh07eVskbH5umUYII8lLc6pgxzgrbz(RuKrPXvkCTw86ILMOvJglkjBksE0Poh1SZU21DQ2YWuTzk6cwTtwJkkvvgmEuo4dmGBPRWHtALevwojibGr74TAwHAocOsurGCgYlVbmHLNUIY4zQzTsUuvQMgQMnwKbIynZusewvPDawxId7sCS(0(wh4bJgR5TsllBixPHy57ADTkD9SdNWfF7TcD(qSmzXXiV(rRWgoREG7p0qxuwNV(4IlJZ1Lar04WY)bThkj4IvtvTcVES4rJ2qfSjWzp25Ypz65f1RwuDkXvhupbx9eCvsWXBjs4ol8ZlFwUr44veGV(kNLByRVQQZnmLO6ar1DjQUlr1DjQcqufxIQ4sufxI4bI4DjI3LiExISMMmmrdojzgihm2rgE0v9(tSeC6FSrp1PGbe7pvy)Hh)dDMmAuNzAnGvMqB7OqWyotgm0q0B7ugTQdnehvPaUl(9muvfOxQiUch1amh0X4mLePQtCgQCYMCYgkhZKtdufaLzbotvkblKBEAjCmJ0i7kkjBWbRVvxXGRLbsOKSGiwcNAn3kGcgvLgRXHwJ4wrIhBcGnnexMhUnL)iJGEq0UPv7DuZgVouk4HgNVtjrUgNIQzyucdifkjDLtmrfBfvm6FGPQyouel(zO1hLYHZJtxq0Sa6wBqBbXPN0UK4X3MkLQrdQtAJbTAJGl4DhK(vp60qaojnzdyfvd28lZiQHT2G1vM4mcm30QbOLdtFAAnKzZ74mjwrdC(evc4q4sgu4sCuVOjrgLlz2KCZHZWs8llcZ1ICvLeRUuf1vP6xhBbdOe0xkh18ZX4Kv4ygf4aBhMG(QbvlbRoYqqje7fR5RpqhntjxxQb8JjJtUdE(AlvIn8GjVF(yo0r9Sg7tgnmkVCqYUkw3pzVrAs0kWiNPhjwVFiUE)qCL(HyQqdaDb1j2ewFIDMO9XGWvBZIkPauD5rUAFmm3z2DYR2hcIDMDN4Q9X07dWENhjVpxz(neSnc1e9iLJ2ZuEIEMYtEvWwcynTdkbqYzW112lFCSRY8EtxZpHmangShLGDzobqeSaGSJwX0qqpdgJHL12MQ)ovVSgS3Rav(Nk34LYmDQcfkLzUPNlFHl7RFce1pCSEVWX69dhR0lCSs)WrVkF7eJTP9mb8UWC7N0ftjOtIURs7gaZG9ZerI(rg3pexPFiMpkZlzgySJaGaxTAO7rxnD(MfbVVf0effcZIG37h7Qh3uvb8)kQpi4RpZf51heja48L4xzg1LfzKfpUxtU2XUmUSUidRBinthef7QNX3kYq4Yz5obDbjmEYdExvB6xUew7cyuLsQtjEWrJFgxqKQ6vHXV4QGNzg4HfrgR3srbCE7cGeDIFSSfYCmehSkuSoh3sIRbE3H4k0AzijkKaRTd2WvKb37gQnfnLHymTqikdri3c8W3qKx3M9iWJAn4RdDt8sMfdk4dfoQgiIvyjrrn3oJIOOzcUvOyCRkwdIQznUR1sU6sUKi7bMQmR5vI6GxBkv1LkuvxwdaUpNcgsnGbmamu8JtmEjb4Dk0uEymymOhxILwOstmx(mzlDHfYvmwCoNQn0qzkveg26jtvdIACWt5L59ktPrOdCfrIsb9h3JQfDGlCHwY0Og4Byi6bOGSsQPcT4I6qKWfwcNzCUDGGqQUmVUhi5CdI2oI7XY)Y8nAbw8feRX3QH5fzxXxTQAlfyoPQepgLViehxlLLuaHom2H1Eza2I4iHGIe5fOikplN1kPCk1u90m2H7GLKmzStZfJlzsqhGf(ZG02pEObqbak7O73GVIyd)mo2qSpCXsMKEBOv4gYZNybaX7iySxZFrzXv2rImAQcRt2rYkqjBEzZQ9kTfmxRHypslmJxDjqS1p1bSO1RCh0XNrwPFOMF1DKAO9TgOmBQ7m5Ema)oAMEBuMgmgMRkGo)3LUELl9KGrk6DJgCj)id7BnVvLYNTqwCnDEmVuOw0GNkoB9nWGJdgD3zJdwMf6z6zPiRuXCZKnpyK7LEPxQVR70PsNDAmi5CGzDv9LefEUyXxxqTelsVYKNymsZv39x218QSGigJBpegCyKaMJXBfTae0OLqk6o7sCexmQO(awXPfRzwat3(GH61hDdc2a9vL8igIDOoOYsyyMRPrnm4bSCbRz5rSSxTtsCqiBQtnO2Hyjry4EWPYa44qjmfdeemYGJKy4eddD5oOIbgSen41))dOGDBbm15pE)nafAaPIbFDrjIAzYHokQu)O9Wug1tA8OHOcHY(ovgXsDwR4OTVTAuaORoroIgryWBdtNZojJ)u1TDOoMadUPASc)AyQabMWTm0D4wbHvYO2kBvydqZdul4xvXuscilvSbacIdAFM7tDwUydhZD8512jBecnyb)GY92FsWDY47efJeVRM)HwGQEGQeC4MIDdNTKiplL7rIezQZ9J(i)9(D3ARFi50xopFdnj(53ZWjFHxKShZNuB)E2sr6Vw3zrD(vKfmLE0h)M4oss(OVpYptCYLww7aDyGBG76lG8Y3ZFK84gmnWMEuikVPMoDlDYPKsQCfMEK0D8Aj7ridg9(wBVXI68A4o8KhIFCM5RijIC(BXrokPCmzHkSLkKNVg5e7MCsCVWijP)Ey6VFrNTvtbAtDjYz)SxuxrDgr96ILj7dyha7uNS6a6anZc9VYPX29EwHMPY2XS3mTHPOgDBYashTPSsK0cIgv1ERunrTumtLcI11fHOj0avf2gTYTMAlUvOzBgG(BPFb6tS9Pij3WClIWDBYVKOxkmq5B1eCNySHzrQeKabqVKdJSGZEUaI0b6g0gu3DbdMWZrS6ljhfIiI8lmAt(v)0hMSV8q4w1fXX84WWOCAeqR2bSg0STqaNh0Twt(ildd7kuDEJtNgTwKNAjPclepYTiRbYsdXgGgb5Zlrwx7PT4LtpuWwDHC7bwM852nWqOA)8K9ry14(bsYk52ufNAm6UoWEt161BiYypxGK7YXBWjj7R6LTQ6NeAI)oSA9HNNP4X5U)7S1(GGk1uqvGoM2yVHQAtJatz1K1nmXPwdyO4AZGT)fOHtdwJ9PynwzOXoe2f7OEKBlHnYTPwk81kAQg0nD2ERpCUUIierfe6yTLStcoTfffsYn7CfZYnell4i6hdw3IPgWyBnvCRsGQawtOrBYmSrxnWXl8XbyswKMKne(eEgc0EzWoiiNiN73(OKx9WKMAF0W3NqePGLbq0(uQBUFsAsgYurVH9js4GJaTttY4KSKP3nzUDdG(OZn5XyYfa3BdmHdRP3aGFGyyb3dHH62XNP1EcZrRZPr010VbHPf7kkdbcaCFSrHzWG3WSdMZa4IBMbT2XeprykJeyLkXae7s6qdXKB0aHVgghmZBbDNHagHR8WEG3TlIXyAIt6ClI6mIAFBdKvJMRgM2bElvf6wmcDcEw3GJ2pyA)0wrxSPiMZiCBpalyYnSRCODrw3d5jJfaM2UKQHUSlx(gcuTJogbwzVLIBNcgbOm0wJfMH1Og6C(QcJ7U9cWHpBiyR9GoTvGHBak6PuQeiGf)kKm(ypKgAiFdoVlog0BhgSDrfUXPsxF7COhzwh3JMhLqk1nnkwbde9ESwBCR1DXIgLDGkm0otOZGjMF6uxkB(stmDQjlukZuPMDYSJNiO4NKBJmQnRWBYnTADYSr3K1k0ZzejNvBohyJbwDmYUTVlUtTKMGPdWKWBt(TTw)JwgqBb)gK3eSOCr)l7dSy3k)rE0lwitXCZnBPPMBHczlvyQ5wmMxznB1cE2eaRmVL2X6K8e(lkZ0Zvi743xynWLOCvBPMeyHI8fj5i)6GDRCKFRTFiCLDyi4lxxUdLI5tno0NETCtp9ooq6G4eElGoii)dc2R1oiBEWYgjmZjxvBiNoR9bakGLCwH4oSHT(f(I7IKFuEL1wVsd4AkYS0tND2XR0ugpXvsKNPc78FrEQrlo3838fi7zQx9t)5p(X3ARVZMnbYBuYWSK(1JaakhLxtUmjk5kD7yYe2bHj8JhZtLpFUjNIEWyCBfZ1EI3h5rh)q6Sswlc5vo)uN7h(7IF(odm15(t(lWpF7bivivjRo1R(fs)J(f31U(JOiEpd5LjN90xK8xhGjs(mOVXF5YKBQDW5bJQCu(zJoe63BIObXC2I(hxDV3OMQIjES)Qa(YKB1eQ3R(jQI775WWhUN75EoUfNl)RXLBwU5Zp3K5ZwOaxXPYwil34Zn7Xkc)Ml1SxQ4u5MDsUlLTiwHOV9M4QN8I0WDltsEiSl95LUba3PbVMHy5nry42xSoDJYPNsqd5MAaUPBPZ6UNepHowNeSNHHr6UykOZydB0fV0tGba6bpjDuJU)3h5yR3qUPSj7ueUbcFSaa6OQyeOA7FrakcIPstxfWeByqo8MJnYfg7LQ1AnLlDcptpGsa74srJEHCJPE1B90pl9uqEPdt(xFyYFqzYrZZA19(Hjhza8StYHtaZqlZiIhfQv)E7Fd2vA8MsAXPNLci(HJNs3uI3OHCvjmBJhN33LjBokexe5JiDddWvTOcmcUJMQUPoVSjceuISq(cQnKfSuHUUvtMZaHauMSmzfR7SQNotlJVo5J(4K3hl(RV735pFUT26hWoxsaYMi)Mp8aN8a9aN8tWzvkmuKuLlowUvXqRFcystBnp5PQxh9DRk(g7BtxWGM)hAcFIcretEMnzwwPw6aFildrVlk5znayGlU2HsPVuof0RIQ(ACwhVUrjp))tscpHhFC83yK7L0enb)4MneLSIzEe6VPh4u3GQ)0LjJHFzd6ruL66xI8cUXytEj6Vloa5CZYInigf4)bi)93n1fztnsqa944lHR2CCxiD0TKlacTEyPGlORUluTCO5gAGp3D0gMEO6cMslF2iJXCg(wB4Ilcabr(IvWG3BzKNEsKaxUiUGFJ0ywKWyFqrhg(r57wxuruxUk7aZsMeO88u8dttMHmhzEaxXBsUWaK8KcKF2xsB)0z4XLnWynWCBjDh2CEn5gI5egfMb9yuD198emNU)I)sMG3SeK)zORwY)CPhqoAjFz0jl5FreYJ(b2l5R867z4KJCQDWX6V6Z(Z(r2ARVURJ1pwhowFYm(9Zy7D1km()ah3sK)nOlOdV5f11nEXAF8fxrkn5Fxhos(B(n)vPUYVeZlc5B54b5(UnKLBKXpe5T)E7N8TjTz(ci)7Vm57aw(j)HK)OxNM0N)dul9K)4iK)JxO7w2j)NCmx0QVnw8a2ub5EKVRe57bgei)NdDTp57V9R3LyR3j)x6ZL5KFa5Ti)xPRgi)3i)q7fbKFeScG8NuM8NUtQ7K)mjY)DOk3pYnhM8graCmMnKHLlZTqXPZnBwYLToJ1Prqw5tlQiVuVPz)yHQz7w6tLgFKfOk3FjjYJUgv5LQTE(GAR3btvyan0R7OHE)azNYjzuRJtt5f5B00H2nOyS0PLDBjpKvugmjhGmtAz3wI0qc1XVWp4x6v31U(GKlng5)Ru7i7sIC9YawoEb1vED2t8WaagjIjntAK9i843yfa9iMq1BSO1x02VvibIRAUGMa4zfMCGfbWA2MFo9ZT1wRtxZc2pEgYtRJzlsU2AKF8MSwjJDsMhG87q(NaRjp1YdZ)APtDsL5wCJAYRkkSiMe5p9hawZGNpF0(f2sXosvRvQdgDd3oGwJUH(XJ(ovYBDooXu1gZN97yFIQGDDpgVzNRipfHyvPXgtkRnwFFY5PNqDlz8LyY4p0UCq2T3N8Hi7(lli7yPtsHjnqW6ZsffUN6V3PNwWq3nmNf2E3UlRg360ImeOycsqkv0(Y2TFTowa688nsncq7I4UD1shNAOKAlVPj7IrZN6SCdnIFTfpmzww)dytr7lh0QMwSkqfMM3We9EcvY6rmaILCqhELaASedns41Dcmv4BBLhb3Sl36ApmCB0ZYfJlqcg9iMD4usR14233zJ0dYzpDjN(ulnnr9b9F74D2MDo9Mi2z8rH9kRWPgrF60H90vTQe(x8hFwTSQTxCaD5Ov3xNA2Wy274dSzqd1WvoHrngGl6J0vkziyUHGAjdCVSKSWY8838G684dhMOHnQLx0psfkmL7r7FLaK7LSFy6SGTaaz8I6Ptipj88u2DcBipuyo3dbUJpIHvPUXsNcXX7h3Z(riniahecdcLbXazdTbb90u7V7oe2tc7NqI42RE9h9dZcxyZsw1BBo7TNPZ0S7jqhQxqavgIxl3DYGprgZWoLb2W3qWAieoAw)a0zhLCtab9nSN0OGI)QF(BocGtJ8)I8)2bBg5)d5phj(baOmYpomezHKyUjBj3qGTmZhWmkAk6nDqtTEbNISHMrFQfXhnZLennCtb2JtXDvNY6k23fc)GbalL4NbcY4zix6OTJ8Hl3oYZc)SBkMR98R)yw4UAhb(3Eqav8FTFpm3wTJSxggllGvhEZ1YoxMzVWKlKp9IimR2r(zi)42rEehGvTJ8(aiumatF0hVDKOi(jOP(Ga8P2rE)AFUaqlywDPDAlt8oAp0cT1Z8qrG9eH(OR5P(XI1vfjhYS2VH2r2Nher7(TFiIOF6GiIMIHju1zQ9Dim96cGP(g2CCqsqSaugYobn(2BtlUoyG6W2oTqCr2nyn2lY86dY7No6tXEzVq6PLcEqFLTXFBq3ODrQ17im7aFPTdn0lW1S8v1oYHAh5WOhR2ro425SQDKhVVDq1oYt4Z3K2Z6jEQsSN0ZskwFbSBEUB1NUP(6H5MIEGPGpjMCHCtpEP8ZvOy28Lwy(XtvmBcoRDkKDpwHbqueqABPwe2U6gaxxpLookBJDv)t1W412Lw7ipvqhz)dj)JSCM9pgtAa4mBD0zgZxa1B2K385j7znQ3mW4m1BM2hkezD1rDf2Dp9dDuYH6OKNI80upCEDV9gbDVD3mGr9L87y7Ew9QcSxRdUPFWktHwh9hd6bBbQWx40Jo6jLgDKrL02p8l6o9lYlGpSddtU1g4UzpbBeTpYFlkN2ep2WCwdZBBDyCUbk6t1C(G5Wi1mhF(zCYHHN0Hq(lqpMEDxor7ihRm56GlSKsTJKyaQxt0DOTlZ9wPflzeN(YU(pND4JFUT26Rr9g63hjoXD4nRwjBkHPg(6ANFAk(dhxL2PAa8vUAKdeWqPhpMylwGUghD8ax4ARdVIjCk4XSq0UzNZvwIpEN2ptmEnJ6jei3MnXijgjoDHXWHeNJVUx41NBumgS4HAi0ZYk3AGRz87XEpx5HESFG6X2v3YRcKvXygSOG2r)C4we)s0pX250x8oo)f9vWHb6FGJ4(n0q7uayVGaz0rYflAVSSXtQlcWGPI5L7bfU0SbytpeOT9GaFMD(e6aWHqQqWIaApYmuIdRN630RLeJzpON4DNDPEUQXosHy(zaT(BBQKqZ1ENw77(4r06AB2vBKHW0ZqXnf9DDWsH6aFepOL2Nh0sFFkkjeTKxusiQPMAYHJsQRbU7iCONztQ7uReUrnoeIT5ocmNC(oIgFaRaXPyxOidW4grSlXj7zsFyxyg37EO4pOaOCNXXxYhDBhrOqaUiw6(YBOXxveps2trpk3s3DzEDz(knePjzbIRgpFWAVEoaNOcwSa7uqdvGE4vvRz3kCvePNTv885YSmGNBwb6zRMEKy5xMxUbYc8WOiQuVHSHusYQ7LCR7JN2BvLPrRhYxxuW9mV(04E3OOQWGeG3ZU5aOnVn5FP7jVH81kt(xvM81j)(KBDhfVm7BCEl8wRpTkSmanlIqK0nPFDZXvPUeXjAYTwxGFTaOU0o44a4nv84CkUKl6llEEF6BkNMQkMsu2PDOuv0fxwMhFTP4wC7iPi3At61bz)bMXHkhUVx7EmL7RjYRFxmVRCJYjixx20GYUnWYdcr8sqzD2jTEilSR(9Wh7kx0MmUbJ85Qr7lU9Th3AOZgio9o8ehr(3cQJe8agDOzdD(XdctkIVorvsZ7s44hDHzU4V)F4U21UoOl8XdV5Lg7IRmJqbHRvG3kLlVWo8(rQd39wXMyz27sJ1oYllrra)kay40qBFE4Nz3B7itSxhOypYVz)8Ul6HW2EGcBR3aO9aA7J(Po(lSlLPeAJoLIa68jP7MhLbt9TaVULpjwfqBp4ArOAPWJ3zQ8LwmB2xB8uxQ0SPMjBHllKejbwdFvRAWwY6H(jwy6PXCcuAM5MT4uovJs3v3wydEaAyzdyqBMXLWURLG1IjS4iTeHKOjQ44b7hrO0vHTxB)DUdBoMKPz(8mDnkpfFCbafAxpGLbGVYaD5HThjfSMWAHqddX(L9a3hD74oVl378m27XRqFoc9uZWhJby9rs3NJr)nqNJYG8Vs3hLUoR6ZbPBfdFm6NXhzY(Ci6J9DocdW9mDFa66)S)1tTQyxvu9W4Ji0)6PUSpufvVCxmSbypACWrN3Ahv9ODyvIBJzvGR41oiMDQ92PebX8S7eyZ7sH0qb83ZHTeV7HT0pHDyV3FOFeAk2WeF(vJ3zgtBh5i)KNw07XI64BmW2TTFha7p03Ub(d(Ocl4bNiqUhlhL4dzfsS7Zh42LNYJ2oYIS8ugejz7idVT5M8lhi3Kx)fVwQxitXlCTmR11CtQTrO7JhT)c6Hd3X6B3yk9TaZUcoHzYnui1jSypDOYkVgfvPbxoiLJXdjxHV5dbD(tND3RRWoF3jTFDRF8oa)zx0P8TtBS74vP3Qi0CV9l3kFuHjBXIKxgFpOg2MhfB4H9UXHbs5gCtx3AboWssQT0nSFZuvRHQQtRF8tm2WdhpmYdMzEpV8vtwd0fPe1XrJQPSIr3RtiT)yddRMhKYSp2ydhpEhCeiSV4iWog3WrgCbThrzDhC2EeIK0DbliZX(G3n7GjpFLGZt4hhM6riU98MfpDyB7RV3(TE3vW3BY6y7iNSFsT4V87kPwm8DtL5S06PAOxt8i1Rl9KMZ200jFVecW047qj)qaaN3H4(Ns472U)NP2klo8BOUsURpF3D)FIDiNsExlaJKyD6pE3Cp0F8d9hVD(J)RewcNSNIw5bOLmMnbQLmAWmt9vwD9FLhBRT(sp4TO9SmlAr2odApfDBDSEeh8gAdYV7GBGXxL87b0DUFcFMI762zy9Ocpg5BC6onLQDihBPv90h7Qj13K8zhaVXVseYNt7PzHQz)wab3yg7tPYTUlLp2pY9K)gp6XEmY(QWq)z9cjXNqXMjKBhX3(dq(M(SIF42rQpgAjVDKpEKhiwZRETCdpISrUwfFXT5GM8z3MtKNZlJIZ2vWRX6wAF8hpO9BndRhdGqabWOqKL2x8ud7sBVgrPBLdHYNVZHvNDD8uFzXKxXxVn0ixTjDOo6SHDcu77OwFHh6L8HEjFViQ13fdDT3JOKgr7FfnWulXvVhqANNiyxtXHFEKCCif7Q2GNWhW3t(oKbVxG76NR3WD1oYv6oIj2B8MBUF67spt8iCxM(2dG()Vt0xCE03Ymwmw7a4989uUxgpNX3fFqxlyxLiGC8ZS9VLV2UxCt(xY7ol4S2ZpRcZ1HZBvN1nC7uVL2t2L35tKCApDgv1gcQROWnV1B3eUbPdO4uHjvIDp2)dyztPnGt8mhZaDQT)Gi8aWNpl5R()Gb(u)V2F7FHT26B9Ep4ZgEdQoa4ZD6fAtI3XOpb8AHd88auGNw9TTpo(FnOuuvDA6)Z2jHVRIG)EO1P)V1g(4KlH8(9t2xEzfTwSxbHBAXz8qIrU9U7rmLV)D)abtPCAXlwVAQvmYmx3ZqqMEpdboLrNdZWtNddjJbl(qSqpelupIfYRQuO)3sHZtYVFFLN6Dkh(l1olRUJolpiwT2rmGXHzO(6QYKe(bhAv427UlGG0Qo7SFo6ZhtOo4OVj199o7a9NJVq7(tBhzT2r0lJVn5Yr(TyYHD3oYYrAh5AL3gpBnSsRc4zBT)Fd

**Comment by mrbuds** [comment]
It's due to Retail & BCC/Classic are not using same API.
Btw you are doing bad things in this aura you should do this dumbframe thing and simply anchor to UIParent instead, but this is not the place to discuss it.
