### ISSUE TITLE
Mouseover Tooltip Of Grouped WA's

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#317]
What steps will reproduce the problem?
Have a Weakaura with many children. 
Example:
https://wago.io/SJ92um5LW

What is the expected output? What do you see instead?
When I highlight the group containing all the children, I get a massive wall of text, and I cannot see "whats really important". For example I want to know my installed version, which comes close to the end of the textbox. Because of the many children (which are all listed in this window) I cannot get this information.

The expected result would be, that the children list are stopped after listing N amount and instead a "and X more." text would appear.

Example of a good children count:
![image](https://user-images.githubusercontent.com/4364044/34040498-49ea6214-e194-11e7-85cf-4ba8dd6ed474.png)
Theres not many children and everything can be read in one go.

Example of a bad children count (display atleast, not the Auras author fault):
![image](https://user-images.githubusercontent.com/4364044/34040521-6f70adfe-e194-11e7-940d-4ae38938fc72.png)
Here I cannot see the real usage information. The children count display is just too high.

It should stop after ~10 maybe and a text should say that ~30more are following.
(So the user knows its a big group)

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
No.

What version of WeakAuras are you using?
2.4.25

Was it working in a previous version? If yes, which was the last good one?
No.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
Not needed.

**Comment by emptyrivers** [comment]
Would it not be better to set the tooltip description above the children list then (even if the child list is truncated)?

**Comment by pquerner** [comment]
Problem would still exists that a long list of childrens will be displayed where its not really needed nor useful.

**Comment by InfusOnWoW** [comment]
The tooltip has been limited in the latest alpha.

**Comment by pquerner** [comment]
Where is the alpha branch so I can check it out?

**Comment by Stanzilla** [comment]
it's `master` but Wowace builds zips from it, https://www.wowace.com/projects/weakauras-2/files
