### ISSUE TITLE
TBC: Mind Blast Weak Auras Stop Working After MCing Cabal Shadow Priest

### ISSUE THREAD

**Issue by wheatbread** [WeakAuras/WeakAuras2#3172]
### Description

Strange bug:

On my shadow priest, whenever I mind control the Cabal Shadow Priest (https://tbc.wowhead.com/npc=18637/cabal-shadow-priest) in Shadow Labs and then release it, any weak auras I have that show my Mind Blast just stop working.  

Even the most basic weak aura just showing Mind Blast whether on CD or not will just refuse to display anything after the mind control.  

I tried remaking and creating duplicate Mind Blast weak auras before finally figuring out what was causing it to disappear. 

*Edit:  It just now occurs to me that the "load" condition for it was 'priest' that knows 'vampiric embrace' talent.  Is it possible it was no longer loading because it no longer recognized that my priest knew this after I mc'd the Cabal Shadow Priest?

### WeakAuras Version

3.4.3-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

None

### Reproduction Steps

1. Mind control Cabal Shadow Priest in Shadow Labs (and I guess attack some with it, putting up its dots and mind flaying)
2. After you release the mob, Mind Blast weak aura no longer works (not showing up)

### Export String

!WA:2!1v1ZVTrXx86AkTyuvBmTPuOccrIanc50K0gqrQ6lEtDAcKyBw72eupyp7UJ3DAwpZWmZAhhXL6t5C4eLsb8zofPVN4w(lyKfI)aYFc5VaEZS2jue1h8(MzE)4Z7nV3NjZQ5BNpiFW(FYaIpJwJLi8XzC9zXmXxLf(j6vPvljwL5qe1pIjQYiuL3kLkxVK7qFgloG1LwRlHJJoA8YsbH4ibYxryu5sUsfsOY5qOevoVwWhzuU(kbjmelKLNrmsC)R7QaJ2XbLOy8jsK4gHykwq8RfX6wH2C4RSCGe(umUlQNSVr3eW9npqYXXXLrTXxY)dpwM4H7GPQQcClYUU1QwAJnCu94yxRAogt84XOEyHiHAvvFLbgNjtJOlf8KmNR9i(nxzu(nvvbluGLYP(0AghDB(7ymcVlKYnofbrdfyuCTXlhSjHgmLtmsQgAdX4dA23kUEGm3PiUwslaXh2yLI1Q3Ow9IU17hKiqMcA(5p2yoYtYeEBYcWnpWS2w6Aoia7bMwhYrXAL2O6QpAJdsOJkWZ4LMw686RDP78MhgqKpnHc3sDWlGO94tGSY1t1246F)CNa32ybff)y4UcI(tozhmMxeqSVY1GNOdqusBlYws)wRQVHdLrXhHrsCnLatdvrxC4yS3Wu8fsm0Pfi7B0XGu9DDAJiuWw9D137I6L0FU(laX3(FVdKDsKY4lO9QtkGYoaQzU4qtR2S7Fd(hPW7QAy)RftaaRbVHI0g3GlW(eRfhCQkt)XC(n)pmivW1yxWX2JK44w2wFNIpQEf(7y300OAsD)TibQiNIWYtsDezxCGDZNnmDS5BhnfDK98NMivKw90xyGGPGSPoSPt5kLlPVHashJodSkMohMj7A)V))1n)wCe4BXG(XRUQGS3uFtckaQiOPQxp15DGS0lghXZNI8ie0Zoo(JGZ2JxAvPlteSLaX7V1iHHNgeZ9dp)MvkxzL1CRSzPVVYJQVX6LlXVAAf4mob9fELaoocJumDZvstNmzYEweQr2dVi)2VURTGEWmiXVHkcg4IG5Vm8p41PB6Qm)1WWyw3vf4Vlbt97v9nUtHfUxAL1CWrW4YdJhbMO(MTmz5qVeLIrRa9vaJWaZ2ByBFV(Hg5XfWdchBQLE0XSmYQX2)tnQ5JIXzTaPEeXFhkWwK1EYgeqEcR)DGYnwe5fHjHrQN4eZqb7pHGqdfSe(KUTtIvKC2XBd7KiY1hOpKWCmOsm2RQ76LQvxhpPyRIUURxXTPL8sbHMQsPfSg00bihWtQJZ1FeZJFtXEWykW5CErQ6lyo2lvEgn7paV(1nDmQcRYcNniGaCs(aK6zu94t5W2HcuIrhW7WtT2CQJGfBdOJeUEncIwPVhyKhiSZRMQUJ5vNfseX83psP4YLNBUUOqwbcBUQYT7(05FS0DU5pKqtVBnoG)UKqktGRWTVVuYWxwsiycztdLMHpFDWPV75V2udHjuO)CKM5wiHeCyqq9hgt6S3d7TNNe3gkRUZx4ofUZjP9YRkakzdY8QTIBPsLD2JXANrFLMdum)rCoxQ61NMeC0ze6tn)HTm2bmEWKywxumpc(01Wa8eXUPngR9Ll)d36CWppaDTiH5GlAJdXn5xB8lNgIGhqKiy(nis)SMdmmLel6xEgx)iS)olPVC2(DqcIrPbm64hLC7GItWzf(riAiwo7m6x0SpxWacxvp9YtQFPHPSWcfmDEZO)Xv1x(ZoN(5luS8dMMXN((33Z6E5SMaOFU(N0VidiElqh(vrkf88IjIWB5HyL(fz1)87zcH(L6Fb82sPEt)R6FB2rwPhCMh6tO(S2EiWWmGHay0h0FCsdVApMDvFH8s3flC3clMVZFU9Fp

**Comment by InfusOnWoW** [comment]
This is almost certainly a bug in blizzard's handling of that case.

Can you check what GetSpellInfo("Mind Blast") GetSpellCooldown("Mind Blast") return before mind controlling the mob and after wards?

**Comment by mrbuds** [comment]
I had an issue too in tbc after mind controling myself an npc to not be able to use my macro greater heal, i think it's an issue on blizzard end.

**Comment by InfusOnWoW** [comment]
Also no response from reporter.
