### ISSUE TITLE
Swing Timer starts on ending cast even when not currently attacking

### ISSUE THREAD

**Issue by Aviana** [WeakAuras/WeakAuras2#3178]
### Description

When a cast ends the swing timer trigger is activated even when the character is not currently attacking.

### WeakAuras Version

WeakAuras 3.5.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Cast something
2. See the swing timer activate

**Comment by mrbuds** [comment]
Casting a spell reset swing timer, if that's changed tomorrow we will get a new ticket asking to revert it.

**Comment by Aviana** [comment]
I am perfectly aware that when a spell is cast the swing timer resets. But if there is no swinging going on (you have not right clicked the mob for example) the finishing of a cast still triggers a swing timer event.

**Comment by mrbuds** [comment]
If you have a fix for it a PR is welcome
