### ISSUE TITLE
Windows style "select multiple"

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#318]
Currently its possible to select multiple children by single clicking them in a group.
In windows, what I normally do when I want to select multiple files (but deselect some), is this combo:

Left click first item - Shift click to next item (possible the last item) (now all items between first and last item are selected)
Also possible to deselect some items now:
(Same procedure as above) - CTRL + Leftmouse click to deselect item. All other items between item 1 and last item are still selected.

This would greatly improve UI, where you want to delete most of the childrens from a weakaura group.

**Comment by InfusOnWoW** [comment]
Shift Click already has a different meaning.

It inserts the current aura in a active text box. Which is used for e.g. linking in chat. Overloading shift with multiple actions feels a bit iffy.

Also to properly support shift clicking we would need the concept of a "current" item. The behaviour of shift clicking is actually pretty complicated.

Imho, that's too much effort for too little gain.

I did add that Ctrl+Clicking toggles the selection.
