### ISSUE TITLE
WA Minimap Buton Left Click = Hide WA ....

### ISSUE THREAD

**Issue by walldiv** [WeakAuras/WeakAuras2#3184]
### Description

With patch on 7/2/21 - Weak Auras on WoW Retail - 

When you left click the minimap icon to what used to be open the Weak Auras Control Panel - it now hides the active weak auras, as well never opens the panel.  You have to SHIFT+CLICK the minimap icon to bring WA back to viewport, but can never get to the menu.

### WeakAuras Version

3.5.0-4-gee8cc53

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

in description

### Last Good Version

3.5.0-1

**Comment by SpatenLa** [comment]
you are missing the entries for the lua error.

**Comment by mrbuds** [comment]
It looks like a stuck shift key on your keyboard.

**Comment by walldiv** [comment]
thats completely not the case.....  though if i were to contact MS helpdesk
i would expect the same kind of troubleshooting.

Thanks though!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mrbuds** [comment]
If you don't wish to cooperate we can't help, i'm closing this issue.
