### ISSUE TITLE
LUA Error in Invasion Point Naigtal

### ISSUE THREAD

**Issue by Shivlocin** [WeakAuras/WeakAuras2#319]
Message: [string "--[[ Error in ' RaidCDs_Engine 2 2' ]]retur..."]:315: attempt to perform arithmetic on field 'shockwavehits' (a nil value)
Time: 12/15/17 17:44:41
Count: 3
Stack: [string "--[[ Error in ' RaidCDs_Engine 2 2' ]]retur..."]:315: attempt to perform arithmetic on field 'shockwavehits' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[string "--[[ Error in ' RaidCDs_Engine 2 2' ]]retur..."]:315: in function `triggerFunc'
Interface\AddOns\WeakAuras\GenericTrigger.lua:508: in function `ScanEvents'
Interface\AddOns\WeakAuras\GenericTrigger.lua:584: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:575>

Locals: errorMessage = "[string "--[[ Error in ' RaidCDs_Engine 2 2' ]]retur..."]:315: attempt to perform arithmetic on field 'shockwavehits' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

**Comment by emptyrivers** [comment]
This is an error in the RaidCDs set of WeakAuras, and not in the addon itself. Contact Tehr [here](https://wago.io/RaidCDs) for assistance.

**Comment by Shivlocin** [comment]
Thank you.
