### ISSUE TITLE
GUIDE: Setting global (_G) functions in WeakAuras, to allow users to run functions to extract/dump debug data from their client.

### ISSUE THREAD

**Issue by Bananaman** [WeakAuras/WeakAuras2#3191]
This is not possible. `_G` is shadowed inside weakauras to prevent setting global variables. You cannot use setglobal, function x(), or _G at all. Your aura is sandboxed. So you can't set any global functions for the user.

However, there is a workaround. Look at ScanEvents:

http://tfbguild.org/index.php?threads/weakauras-a-guide-to-world-domination.864/

All you have to do is make a 2nd trigger (which doesn't cause the aura to appear), register it to a specific custom event, then the user types /run WeakAuras.ScanEvents("FAKE_EVENT_NAME_HERE") and it will run your trigger's function().

Your 2nd trigger needs to be set as follows:
- Type: Custom
- Event Type: Event (means it only triggers when the event actually hits, and the event won't fake-fire like "status" does)
- Check On: Events
- Events: `YOUR CUSTOM EVENT NAME HERE, USE UNDERSCORES TO SEPARATE WORDS, IT NEEDS TO BE UNIQUE AND UNLIKELY TO BE USED BY ANYONE ELSE, I RECOMMEND INCLUDING YOUR AUTHOR NAME IN THE EVENT, SUCH AS BANANAMAN_SOME_AURA_DEBUG`
- Hide: Custom
- Custom Code:
```lua
function()
    -- your custom code here, to do whatever you needed to do
end
```

Your global "Trigger Combination" setting needs to be set as follows:
- Required for Activation: Custom Function
- Dynamic Information: From Trigger 1 (https://github.com/WeakAuras/WeakAuras2/wiki/Dynamic-Information)
- Custom Code:

```lua
function(t)
    return t[1] -- Only display aura based on Trigger 1's state.
end
```

Now people can type `/run WeakAuras.ScanEvents("YOUR_CUSTOM_EVENT_HERE")` and your custom code will be triggered.

If you're using this to make a data dump from the client that you want them to submit to you, I recommend using a scrollable editbox with pre-selected text, by using the following as your Trigger 2 custom code:

```lua
function()
    lines = {"Hello World!"} -- Store your custom debug data here.

    -- Display the results in a centered editbox.
    local scrollframe = aura_env.dump_scrollframe
    if scrollframe == nil then
        scrollframe = CreateFrame("ScrollFrame", nil, UIParent, "UIPanelScrollFrameTemplate")
        scrollframe:SetPoint("CENTER")
        scrollframe:SetSize(300, 400)
        aura_env.dump_scrollframe = scrollframe
    end

    local editbox = aura_env.dump_editbox
    if editbox == nil then
        editbox = CreateFrame("EditBox", nil, scrollframe)
        editbox:SetMultiLine(true)
        editbox:SetFontObject(ChatFontNormal)
        editbox:SetWidth(300)
        scrollframe:SetScrollChild(editbox)
        editbox:SetScript("OnEscapePressed", function() scrollframe:Hide() end)
        aura_env.dump_editbox = editbox
    end

    editbox:SetText(table.concat(lines, "\n"))
    scrollframe:Show()
    editbox:HighlightText()
end
```

**Comment by SpatenLa** [comment]
why did you post this? and please for everything thats good dont create crappy frames

**Comment by Bananaman** [comment]
This is a guide for people who are searching or using search engines. Closing ticket.
