### ISSUE TITLE
bug sack

### ISSUE THREAD

**Issue by chishan719** [WeakAuras/WeakAuras2#3193]
### Description

3x [string "Error in: 位面"]:6: bad argument #2 to 'strsplit' (string expected, got nil)
[string "Error in: 位面"]:6: in function <[string "Error in: 位面"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:604: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:740: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:701: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:847: in function <WeakAuras\GenericTrigger.lua:832>

### WeakAuras Version

3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

3x [string "Error in: 位面"]:6: bad argument #2 to 'strsplit' (string expected, got nil)
[string "Error in: 位面"]:6: in function <[string "Error in: 位面"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:604: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:740: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:701: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:847: in function <WeakAuras\GenericTrigger.lua:832>

### Reproduction Steps

3x [string "Error in: 位面"]:6: bad argument #2 to 'strsplit' (string expected, got nil)
[string "Error in: 位面"]:6: in function <[string "Error in: 位面"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:604: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:740: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:701: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:847: in function <WeakAuras\GenericTrigger.lua:832>

**Comment by Stanzilla** [comment]
Error in your aura not in WA

**Comment by chishan719** [comment]
@Stanzilla 3Q

**Comment by chishan719** [comment]
@Stanzilla thks
