### ISSUE TITLE
Arithmetic on Nil value error

### ISSUE THREAD

**Issue by tbrad86** [WeakAuras/WeakAuras2#3196]
### Description

Message: [string "Error in: Melee Hit':'custom text"]:7: attempt to perform arithmetic on a nil value
Time: Wed Jul  7 14:55:30 2021
Count: 54
Stack: [string "Error in: Melee Hit':'custom text"]:7: attempt to perform arithmetic on a nil value
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4121: in function `RunCustomTextFunc'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Text.lua"]:214: in function `FrameTick'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:646: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:638>

### WeakAuras Version

WeakAuras 3.5.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

Message: [string "Error in: Melee Hit':'custom text"]:7: attempt to perform arithmetic on a nil value
Time: Wed Jul  7 14:55:30 2021
Count: 54
Stack: [string "Error in: Melee Hit':'custom text"]:7: attempt to perform arithmetic on a nil value
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:4121: in function `RunCustomTextFunc'
[string "@Interface\AddOns\WeakAuras\RegionTypes\Text.lua"]:214: in function `FrameTick'
[string "@Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua"]:646: in function <...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:638>

### Reproduction Steps

Happens after loading screen for new zone in TBC Classic

**Comment by emptyrivers** [comment]
This is not a bug in WeakAuras, but rather an error in some custom code that you have on an aura called `Melee Hit`. Contact the author of that WA to report the error to them, or (if you are the author) come to https://discord.gg/wa2 for assistance in troubleshooting.
