### ISSUE TITLE
TBC Alliance Seal of the Martyr

### ISSUE THREAD

**Issue by Searcher314** [WeakAuras/WeakAuras2#3198]
### Description

When attempting to set a trigger on "Seal of the Martyr" on a Human paladin, after typing the name of the spell into "Name(s)" and hitting enter, the name disappears. I was able to get my aura working using the spell ID 348700.

note: Sorry if this is the wrong place to be reporting this type of bug, wasn't sure what procedure is, I did read the guidelines though :)

### WeakAuras Version

WeakAuras 3.5.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. new Texture
2. Set trigger "buff"
3. Name "Seal of the Martyr"
4. Enter
5. Text disappears, no trigger assigned

**Comment by Hidaruma1989** [comment]
Hello there, 

This also happens on my Blood Elf Pala. When i write "Seal of Corruption" the same thing as OP described happens. When i type "seal of Vengeance" it gers accepted but does not show me the actual image when i activate it, since i technically didnt activate seal of Vengeance.
