### ISSUE TITLE
Button glow activating when not defined.

### ISSUE THREAD

**Issue by torapier** [WeakAuras/WeakAuras2#3199]
### Description

Autocast shine is showing after a while of using the weak aura when triggering 5 stacks of shining light.

### WeakAuras Version

3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

As a prot paladin keep expending holy power building 5 stacks of shining light.

On 5 stacks the button will glow green which is intended. Sometimes once shining light is depleted the action button will have the auto cast shine which is not used anywhere in the weakaura.

### Screenshots

![image](https://user-images.githubusercontent.com/87155874/125003984-d0a59f80-e09b-11eb-8309-6d87eeb9f3b1.png)
This should not be shining unless it has 5 stacks of shining light.

### Export String

!WA:2!9D1tVTXXvCTM1XTSWi202k2Qoj0ovcXokeMs2UjOnOquMkw20smlPJCQBk3H7oK7yTC3XZmus0TPTM9pqN5NGAEOOOOOhuAAU1d6qp)arr)aOpcc9dqFZSlPKTOmpODM38M3)FV5NSwktRmEz82(A9zUrHvIAlCPw2UrbrI7Lc)13TTuf1QkDl1jeDwTrdjvzTdj01psuoIfQQVyXvQw0EGBuuGx0MHv2KXPo8ZCW9Ei3JOO1BB(S7q(k61K6xqRuNUkbRztQq(3NrKSC7S2kbXD9cK2QOUmfT1kKw0lA9xpFV2sAffEK0VhPTGeI0LtnOIplKf2mBjwtFLTHy6DqwR56tenPs)bnPHubZTIF0MRg2xIFwiytsh5EY21PBqdvLf0gSTSRuUyPs2gk8RUyI1MTSiQPGkLzF)IpTnJ3cpnBLGi11QlngtMBUR2AKCAqaZtov98F0C5VXnfOjOTC)UABPDit5iAhAeo8MD9WBOyrHzY3ZCrnNwdeusqLrBlO6WP2Azp3EXQAvofVwKiZpzKPxPDd003P2IluPATkvxWU6EA9rQlJe1FqKh1z3guLRFv0DumU)U6thgvDkOTR68ashQy0jANZzGE3itZPRz5YEY07JhuClIRQsmfN(EygUrJQOXkUBXsLx6HLg0IGQKkJJ4WBPZC1mzvh(z1RFPmItV2Hjj)jHjH3Ag40BaVRp8HqoyohyAyg4TNQ(8Z9JUv(BazMcohmpCt4JsJ89VXt)qEMd847IrqJxBZJ2KkYm)EMV1Igf5m2IHOdmLDz9ciRtpdfDa)CW1D0QEWi(0uDs05oEm5tAh6QyBqRhxOZZKuWh7cLIAYC5Z2WWuu47N4zxlDw8NGQAlcZMq7X5)YFCAAOh)SeJatKG2()BtSp2HrfHKGphBpqb949xNs5lG5bxLTU2XPhjK1YufDBBS(qOwAxkr3IiOHnv(NcMUqyuiDWWATAAhriPyJNNSRMvDodUFHwew4sW9Wla3hkbpawbUF9gyxL0)vjJjBjrPfi1VpwdAtBIswEVTNLNrHD81K(eSR5rXJls1Zqt)NctNphNND0(AnIeOXxBUC8AkwlAYEl(zoKyw0mmYYYk1(X3HTf1BnMNY)5Jru5Fvr9dpklJuhxqDz64AQ(Iif6o65vfwz1vk23CHdMd(so2xe7yxEc(SVgH71bhdXCRP8Xbh(4CKodmmUzKWBnbH3DTKfdsUFOY0(S6dRwA5vkYVYrL98VIZDWnRWEg9s8lF0ROJhXRT130BCMC(J3K5x6iSpuEqZbXVdKKNT2loerdAyEzyUQRwMFodn9uCDrQRjTvybC74S15ZDGShxEl)rZBjMqsgXACbTJur8EhF93bcEC6F(XW2pyScBKxC5XxGm8CyAb2)OpoPK)qVScVb)DgtW)WUsVr5F(fwW1L5HVfqcWhROs9A3o8p44BqgtYoZHSHrH0p44dxhve7A4Bdm4upaHbCLJZbETrW8hocETJteJX(FVJ3BpKcN91Kzpop6j40DwJoyo5kVMw(K0Y2Zc)2uq1ctJhaFUfSMz6f8ONdFHf8Zsbpg(5WxAgRa)Ilpb43bCacuhCbplGEjObwyuRdWWpD7aRdbqlieIWTcl4PwWFaEd43Lc(9DG2inzkC28MWZXLvsbpd(LWVXb(kl4x3b(vDGowWwi7BGNQsb8uWtSG)O12VlY7y6TLdJ73xB(5Zj16zOD0VWQvRU6dkvCPQgdk2FsShTpL4NOk1UfAuVubvYyIVh6639N(VEh9VjszfBXAt8RoP2Ehgj0Ud6hyCedipXASvjhyT)3bndI2Cjb9PT1L9L)o3i3C3QGMMJgrZNgK8mItxnn9yw7Y4Zib91BlzEP8c7OxpSQVxZHxzKX(2AJ10VQpZW9WjFgTx1N5UEiIrmL5YvCjb04LLyi5ZA0vbCMpv4x3NQbQ(XfcIiE)5yuguvDIsfq9nGt0Ger(W2zSNEM6seCBa9k2TAJa4sxqdayg4pDk4fZCkNt6yUHBarkD2BeKT1drGRXap1S7lEgIdabVDcBdN41fLxO0c3z5vGxmj8xCkiX3qMeErA(zItyljqqFM)Wp)DOkclqwBnwONoqJeZ3xyE33GF47Btc4(Ku9r1LGY0zhwyC(bzAs(fzndJe0v56TYIAyRffIiH0PVglcZq(6ZyJqgDxFj40N8Qr8R(jFs3nicgbhMuqdz3EdsqBQLar1hIO6NAYUCHgvNQJghsUBMthJNb252WPNDc4RNBHvUtDJaLxhjDk4RH)b8nPWLNmEPf8pNAg4BCGVf(SEJE5c7Yp7HcbLjiwke4(wjz75AZ825ZAiB(GQ8pTGTOWZIIAzbVPtFvK7gXa1UOvT)3vzE8luMeq8yH10p2NnQrwSuu0XEt97GF8on0IhHQruKu7FinQdP1RSODXIRmaF7ejNe2sxhJvnyntlyHAnHJyp)W)Jkn2L7WK6yLNJGyaEkVnSCAOC6ciooLb3QgM)YOqU4j(U3T7WR6NrApFUBL7gz24)8O))p

**Comment by mrbuds** [comment]
Triggers and conditions are never checking for 5 stacks of any buff, if you need help setting up an aura you can ask help on the Discord server.

**Comment by InfusOnWoW** [comment]
I've taken another look, and I don't believe this is caused by this aura. You probably have another aura applying a glow.

**Comment by torapier** [comment]
Thanks for taking a look you are right, I had a duplicate of this weak aura that flashes up on screen when low on health and it was applying the glow to the original aura.
