### ISSUE TITLE
Load Option for [In Rest Area]

### ISSUE THREAD

**Issue by tct-dev** [WeakAuras/WeakAuras2#3201]
Hello,

Would like to request a selector to load/unload auras when entering or exiting a rest area.

For example, to hide unneeded combat tools while in any sanctuary area.

Thanks!

**Comment by InfusOnWoW** [comment]
There's a trigger which can be used.

For a load option, that's too niche.

**Comment by tct-dev** [comment]
Thanks for the reply. My use case here is a simple straightforward way to hide a very large complex group of combat auras (https://wago.io/S1tvLLBV7) that already has dozens of triggers.
