### ISSUE TITLE
Can't rename my Auras

### ISSUE THREAD

**Issue by gabaru15** [WeakAuras/WeakAuras2#3203]
### Description

I tried to rename a Aura after I've made an mistake the first time I name it, when I press enter the name turn back to what it was.

### WeakAuras Version

WeakAuras 3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Right click the Aura
2. Select Rename
3. Tipe the new name
4. Press Enter
5. Try it twice

**Comment by asaka-wa** [comment]
Sounds like you're trying to give it a name that is already used by another Aura.

**Comment by gabaru15** [comment]
Asaka-wa that was my problem thanks for help
