### ISSUE TITLE
Add spell name contains 'word' or spell effect to trigger

### ISSUE THREAD

**Issue by anhell** [WeakAuras/WeakAuras2#3206]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an annoyance, to have to add each spell name or spell id of spells with the same effect

**Describe the solution you'd like**
A way to filter by a 'word' in the spell name or select the type of the spell

**Additional context**
I'm trying to create an aura which plays a sound whenever my target is casting a healing spell or fear spell

Sorry if something like that already exists, i'm still new to creating auras.

**Comment by InfusOnWoW** [comment]
There's no "type" of a spell, so this can't be done.
