### ISSUE TITLE
Holy Shock, Divine Favor incorrectly listed and cant be used as trigger type Spell. 

### ISSUE THREAD

**Issue by Dobranican** [WeakAuras/WeakAuras2#3208]
### Description

Holy shock, Divine Favor both can not be listed as a trigger type Spell.
they populate on Aura but not trigger type Spell 
this makes it impossible to perform an insufficient resources condition call.

Thanks!

### WeakAuras Version

3.5.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Create an icon, 
Add Trigger
select Spell as trigger type
select Cooldown/Charges/Count
under spell type in Divine Favor or Holy Shock 
hit enter.

acts like spell does not exist but is found under aura.

**Comment by InfusOnWoW** [comment]
I can reproduce it, and it is a bug in WoW. GetSpellInfo("Holy Shock") doesn't return any information, and thus the spell is not trackable via the name. You have to look up the spell id at https://tbc.wowhead.com/ and I think the exact spell id option has to be enabled to make it work.
