### ISSUE TITLE
Mod equals relational operator in the conditions tab

### ISSUE THREAD

**Issue by AdamHayse** [WeakAuras/WeakAuras2#3210]
**Is your feature request related to a problem? Please describe.**
There's been some situations where having %= in the conditions would have been useful.

**Describe the solution you'd like**
Put %= as an option in the conditionals.

**Describe alternatives you've considered**
Running code every frame, but this seems messy.

**Additional context**
None.

**Comment by InfusOnWoW** [comment]
I doubt it is common enough to have a use. Especially since you don't even describe one. But there are custom checks for conditions that can be used easily for this.
