### ISSUE TITLE
WeakAuras Companion broken?

### ISSUE THREAD

**Issue by jukx** [WeakAuras/WeakAuras2#3211]
### Description

Hi!
I used to be able to update my WeakAuras with Ajour and then update then in-game through the Companion addon. Currently that's not possible it throws on error upon logging in. Any character. Tested without other addons as well.

Would appreciate any help.

### WeakAuras Version

3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

12x WeakAurasCompanion\init.lua:27: attempt to index global 'WeakAurasCompanion' (a nil value)
[string "@WeakAurasCompanion\init.lua"]:27: in function <WeakAurasCompanion\init.lua:8>

Locals:
_ = <unnamed> {
 0 = <userdata>
}
_ = "ADDON_LOADED"
addonName = "WeakAurasCompanion"
count = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WeakAurasCompanion' (a nil value)"

### Reproduction Steps

1. Log in

### Last Good Version

not sure, but it worked like two weeks ago

**Comment by Stanzilla** [comment]
That sounds like an Ajour issue.

**Comment by jukx** [comment]
Sorry, you're right. I didn't know there was an app for updating WeakAuras. 🤦‍♂️
