### ISSUE TITLE
Colors are not being saved properly with snippets

### ISSUE THREAD

**Issue by flazhbang** [WeakAuras/WeakAuras2#3214]
### Description

I tried saving a table of colors with the snippet feature, but the snippet removed the color code, i even tried making the entries comments, but that didn't fix the issue

Double pipe seemed to fix it though

image 1: the source
![image](https://user-images.githubusercontent.com/26880404/126082265-ffd1736d-49a1-4bf1-a66e-a252c697fb6f.png)
image 2: The mouseover tooltip
![image](https://user-images.githubusercontent.com/26880404/126082282-47e1d88b-c260-4e7e-8cb6-3d88f7fb09b5.png)
image 3: the pasted snippet
![image](https://user-images.githubusercontent.com/26880404/126082288-cf0e4523-3f1b-47e2-9d34-76a2484e06b2.png)
image 4: Darian's solution which seemed to fix it for the time being
![image](https://user-images.githubusercontent.com/26880404/126082483-d8fc3c9b-c6fa-4429-9abe-ca19a41314ed.png)

### WeakAuras Version

Weakauras 3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1:  Enter the following code in an editor window:
`aura_env.markColor = {
    [1] = "|cFFFFFF00",
    [2] = "|cFFFF9900",
    [3] = "|cFFFF00FF",
    [4] = "|cFF00FF00",
    [5] = "|cFF94FAFF",
    [6] = "|cFF2BA3FF",
    [7] = "|cFFFF0000",
    [8] = "|cFFFFFFFF"
}`
2: Save as snippet
3: paste the snippet
4: enter the double pipe snippet:
`aura_env.markColor = {
    [1] = "||cFFFFFF00",
    [2] = "||cFFFF9900",
    [3] = "||cFFFF00FF",
    [4] = "||cFF00FF00",
    [5] = "||cFF94FAFF",
    [6] = "||cFF2BA3FF",
    [7] = "||cFFFF0000",
    [8] = "||cFFFFFFFF",
}`
5: save as snippet
6: paste snippet

**Comment by asaka-wa** [comment]
I can take a look at this at some point in the coming week
