### ISSUE TITLE
DeleteCursorItem disabled in WeakAura API

### ISSUE THREAD

**Issue by Renacion** [WeakAuras/WeakAuras2#3216]
**Is your feature request related to a problem? Please describe.**
I own a a WeakAura that creates attaches a button to the Delete Item frame. This button acts as a hardware event which deletes all items in a table, which I fill with pets I am 3/3 of or junk without a vendor price.

The issue is a few months ago, WeakAuras disabled this API function which is awkward because Blizzard endorses it, having edited the API function to require a hardware event to confirm the user intends to perform this API action at Shadowlands launch.
https://wowpedia.fandom.com/wiki/API_DeleteCursorItem

**Describe the solution you'd like**
I think some type of toggle in WeakAuras to access advanced API or perhaps some adjustment to the API to accept only one item to delete per hardware event would be an elegant solution. 
I assume the main reason this was removed was due to malicious WAs deleting items without a users consent (despite requiring a hardware event); some way to limit this or specifically state to the user that they consent to allowing items to be deleted would be ideal.
My WeakAura has a toggle to confirm the user is alright with items being deleted & this toggle is disabled by default, so I am really just copying this idea for an ideal solution.

**Describe alternatives you've considered**
From what I understand, this was an issue in Classic WoW? If that is the case, then the API should be disabled in Classic WoW, not necessarily retail.

**Additional context**
I made a post about it on the WeakAura Discord: https://discord.com/channels/172440238717665280/172440238717665280/866691204413652992
Can see more of the conversation here.

Thanks for reading! =)

**Comment by InfusOnWoW** [comment]
We intentionally disabled the api, and don't want to enable it again.
