### ISSUE TITLE
Addon not loading inside game

### ISSUE THREAD

**Issue by JuliGonzalez** [WeakAuras/WeakAuras2#3217]
### Description

I have reinstalled the addon and the WA's icon to update them to new versions is not being displayed.

### WeakAuras Version

Weakauras 3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Open World of Warcraft
WeakAura Companion open in the background
Fetch updates
in game chat:  /wa
No updates are visible, neither the icon when they are being displayed in the Weakauras Companion client.

### Screenshots

![image](https://user-images.githubusercontent.com/51747111/126234031-20d5b9cc-7e41-418d-8b70-c1805240fd2f.png)

**Comment by InfusOnWoW** [comment]
We obviously need your settings from your WTF folder and the companion data that was generated.

**Comment by mrbuds** [comment]
The update feature was moved to the top of the aura list in "Read for Update" section

![image](https://user-images.githubusercontent.com/189656/126234580-a8b72d16-f588-4d5d-a1cd-b9a27d37dfe0.png)

**Comment by JuliGonzalez** [comment]
Yeah, sorry for the delay.


[WeakAurasCompanion.zip](https://github.com/WeakAuras/WeakAuras2/files/6844370/WeakAurasCompanion.zip)

**Comment by mrbuds** [comment]
Can you confirm your problem is that the ready for update section was minimized ?

**Comment by mrbuds** [comment]
reminder for @JuliGonzalez

**Comment by JuliGonzalez** [comment]
yes, it was that.
Sorry for any inconvinience.
