### ISSUE TITLE
Werak aura + Aurora error

### ISSUE THREAD

**Issue by Axejess** [WeakAuras/WeakAuras2#3220]
### Description

Everytime i start wow (9.1) I get this error if i disable either wa or Aurora the error is gone:

### WeakAuras Version

3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

92x ...ceAurora\SkinBlizzard_DebugTools-1.0.lua:40: attempt to index field 'EventTraceFrame' (a nil value)
[string "@Aurora\SkinBlizzard_DebugTools-1.0.lua"]:40: in function `addonModule'
[string "@Aurora\Skin\init.lua"]:248: in function <Aurora\Skin\init.lua:212>
[string "=[C]"]: in function `LoadAddOn'
[string "@ChampionCommander\libs\LibItemUpgradeInfo-1.0-31\Core.lua"]:9: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "Error in: Golden Mission Table Helper':'initialization"]:7: in function <[string "Error in: Golden Mission Table Helper':'ini..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\AuraEnvironment.lua"]:292: in function `ActivateAuraEnvironment'
[string "@WeakAuras\GenericTrigger.lua"]:800: in function `ScanWithFakeEvent'
[string "@WeakAuras\GenericTrigger.lua"]:1099: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-3.5.0.lua"]:1688: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-3.5.0.lua"]:1504: in function <WeakAuras\WeakAuras.lua:1377>
[string "@WeakAuras\WeakAuras-3.5.0.lua"]:1541: in function `ScanForLoads'
[string "@WeakAuras\WeakAuras-3.5.0.lua"]:1594: in function <WeakAuras\WeakAuras.lua:1592>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'EventTraceFrame' (a nil value)"
Hook = <table> {
 LFDQueueFrameRandomCooldownFrame_Update = <function> defined @Aurora\Skin\FrameXML\LFDFrame.lua:13
 GuildMicroButtonMixin = <table> {
 }
 ChallengesKeystoneFrameMixin_OnKeystoneSlotted = <function> defined @Aurora\SkinBlizzard_ChallengesUI.lua:26
 QuestObjectiveSetupBlockButton_AddRightButton = <function> defined @Aurora\SkinBlizzard_ObjectiveTracker.lua:21
 FCF_SetButtonSide = <function> defined @Aurora\Skin\FrameXML\FloatingChatFrame.lua:40
 QuestFrameProgressItems_Update = <function> defined @Aurora\Skin\FrameXML\QuestFrame.lua:13
 OrderHallMission = <table> {
 }
 HelpPlate_GetButton = <function> defined @Aurora\Skin\FrameXML\TutorialFrame.lua:69
 LFGListApplicationViewer_UpdateRoleIcons = <function> defined @Aurora\Skin\FrameXML\LFGList.lua:91
 ChallengesKeystoneFrameMixin_Reset = <function> defined @Aurora\SkinBlizzard_ChallengesUI.lua:22
 EmbeddedItemTooltip_PrepareForSpell = <function> defined @Aurora\Skin\FrameXML\GameTooltip.lua:23
 NavBar_CheckLength = <function> defined @Aurora\Skin\FrameXML\NavigationBar.lua:17
 BossBanner_ConfigureLootFrame = <function> defined @Aurora\Skin\FrameXML\BossBannerToast.lua:12
 AchievementButton_GetMiniAchievement = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:85
 AchievementButton_UpdatePlusMinusTexture = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:39
 AchievementFrameStats_SetStat = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:116
 UIDropDownMenuButton_OnClick = <function> defined @Aurora\Skin\SharedXML\UIDropDownMenu.lua:104
 PartyPoseRewardsMixin = <table> {
 }
 PlayerChoiceOptionFrameMixin = <table> {
 }
 LFGListUtil_SetSearchEntryTooltip = <function> defined @Aurora\Skin\FrameXML\LFGList.lua:130
 LFGCooldownCover_Update = <function> defined @Aurora\Skin\FrameXML\LFGFrame.lua:70
 PetStable_Update = <function> defined @Aurora\Skin\FrameXML\PetStable.lua:21
 CovenantSanctumMixin = <table> {
 }
 RaceFilter_OnHide = <function> defined @Aurora\SkinBlizzard_ArchaeologyUI.lua:16
 UIWidgetManagerMixin = <table> {
 }
 AuctionHouseFavoritesSearchButtonMixin = <table> {
 }
 GarrisonFollowerButton_AddAbility = <function> defined @Aurora\SkinBlizzard_GarrisonTemplates.lua:29
 CommunitiesTicketManagerDialogMixin = <table> {
 }
 CovenantRenownMixin = <table> {
 }
 EncounterJournal_ListInstances = <function> defined @Aurora\SkinBlizzard_EncounterJournal.lua:26
 OpenMail_Update = <function> defined @Aurora\Skin\FrameXML\MailFrame.lua:76
 InspectHonorFrame_Update = <function> defined @Aurora\SkinBlizzard_InspectUI.lua:45
 InboxFrame_Update = <function> defined @Aurora\Skin\FrameXML\MailFrame.lua:18
 AddonList_Update = <function> defined @Aurora\Skin\SharedXML\AddonList.lua:31
 PVPHonorXPBar_Update = <function> defined @Aurora\Skin\FrameXML\PVPHonorSystem.lua:14
 QuestFrame_SetTitleTextColor = <function> defined @Aurora\Skin\FrameXML\QuestFrame.lua:78
 ExhaustionTickMixin = <table> {
 }
 WardrobeSetsTransmogMixin = <table> {
 }
 WardrobeSetsCollectionMixin = <table> {
 }
 AchievementButton_GetMeta = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:104
 AchievementFrame_ShowSearchPreviewResults = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:154
 NPCFriendshipStatusBar_Update = <function> defined @Aurora\Skin\FrameXML\Go

### Reproduction Steps

install weak aura
install Aurora 
start wow 9.1 retail

### Last Good Version

before patch 9.1 there was no error

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/6850069/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
That's not a bug in WeakAuras but in Aurora.

**Comment by Axejess** [comment]
ok ill ask them to fix it thank you for the fast responds!
