### ISSUE TITLE
Add UTF8 strings library

### ISSUE THREAD

**Issue by lorientalas** [WeakAuras/WeakAuras2#3221]
**Is your feature request related to a problem? Please describe.**
Many WAs truncates strings and for russian it works incorrect. Character become "square" due cutting in half by strsub.

**Describe the solution you'd like**
Include UTF8Lib by default(e.g. https://git.tukui.org/elvui/elvui/-/tree/development/ElvUI/Libraries/UTF8)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by InfusOnWoW** [comment]
We already have a function to correctly cut a unicode string: WeakAuras.WA_Utf8Sub

Apart from that it's up to aura authors to do things correctly.

**Comment by lorientalas** [comment]
> We already have a function to correctly cut a unicode string: WeakAuras.WA_Utf8Sub
> 
> Apart from that it's up to aura authors to do things correctly.

What about WA_Utf8Len etc?

**Comment by InfusOnWoW** [comment]
strlenutf8

**Comment by lorientalas** [comment]
> strlenutf8

thx
