### ISSUE TITLE
Unit Info trigger not updating on load

### ISSUE THREAD

**Issue by Peter-Day** [WeakAuras/WeakAuras2#3224]
### Description

I have an aura that should appear whenever a unit (my focus in this case) does not have a certain name. 

![image](https://user-images.githubusercontent.com/40751257/126738915-a706e2cd-dfe2-4e27-9522-d13a138d5bad.png)

The aura doesn't show up when it first loads (either from closing options or from changing load conditions). You need to move your focus around before it starts working. Specifically, you need to make t[1] true and then false again before the trigger function returns true. If you move it around between targets that don't make t[1] true then I guess the function never triggers.

Maybe the custom trigger function needs to be evaluated at least one time when the aura loads?

### WeakAuras Version

WeakAuras 3.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Create the above trigger tab. Mess around with the attendant in Oribos (or any other test mob, name doesn't matter).

### Screenshots

![image](https://user-images.githubusercontent.com/40751257/126739392-00fc9439-06a7-494e-945f-7ffae8bcc41f.png)

### Export String

!WA:2!1zvZUTTrq4Q4dfrOfnrjiXnfOGPbWOgfnW5NMdTOOquMUrTYscu0XoiUvAj3LIBc5Ul2DPuuUuuHEiN6b)iOZ9KEe8TEJqOpb(qFamk65olP(X2nwhixUC25BMVz(gQs7ujPcUc(TFTKNQJPmIS1EEnQ30zcnGZ6WtLbKsUb8yU8hwd(ndLQJ4YwcnLZuLfFbMQeXOrEKxR7gYLjiDxrxnnH0fpIHsObD1rsIkIhJhjh1kmur0)5uela8sBoLP9R500ZXDwahmHpK1zivq6jSUChx8ujX1csvAEIXI9eyKM4sgqy6tGqKdgqd2NI1r2vHhLOG8a(jUknsQl7hszuvuzB4MU8yTK2VprQ(9nKZx(VUmrqD8vS1Jee7uWkrLufPlYxXL(pLGI3LJj9orL6NdAN0Wq6RN2Tw1oED74v117KvMNBA2hkU5EGFSQfHmHdrsvqmQw6I2sc4c3oTDA04iZHZJGOz5lrjejaAsVXkbjoUowvoBD3qoqbUMxQkp2yNjq7D0sRf3OQwtyyetB1wY1KaGkMGj(q06bjM8PonAVZEaCS55D5PaV)Yugqxdi(feSOYCIUWKg8(0aX9cZnIZ(C9MLTGFsIovYSyCTL(fp4NkdWkUok3pZpOHg(J3t8jVZkBXcxtbgFk0wqKmu8ZGAcaXlo9veIOkK5bAxOWYJosrIdlAFSB551Ax5RlATknDU3RdTVRFvN1HSvHGidApIexhEzaeOKUazyCeRKDihAzA7z1bXuwnrsjF4eOK4s6BAyUZBVTOI2ePQie0EEWCyokFpZLj7ykcwFpaG4ANXYA5AMsLkT2jf7UiITRUNxlXnY388TQzF0P57cTbeC(o)6ScLYZNd7X5V)Lq5Ggok7QtYtdIHjTB2QPt2TLqONhv5gUs3weVMCn7Be3DzWFbLLqscOggFTZL0lqxS5LDW)VwFwUvd5s8(sKy8(ZxmBzCy6)YUYCk7mZdogga542TOSk(0ldXfdb(43HbflYEWkW6qFd5BNZLhCoUCaKV(XKE(reA)i9M(fuAp7yoc)3tnIQ3WzeqWf5RrXGoDdFfL1pMSMBsASMENE2kW73kRBzBthA(cZre3WlIy1b63aQH13QkBanEIXHf(P3emfgAeaoz0gz)SFYiDeniR7TYc7nEbUrNAwryb8uJMGIJCdIrkLbLzugmnJfaoe4sWf3fo8D7n9mwB)Wh)OTkgMaZyKrY55I9d3ARTgVyKB04LC0rignjxz8KSRVZXeKI0rljS(6O3p722m44ZWg1eyroSsfbuAy1yJP51uTDcIY2jtbhitNLMniBiCVYf354fW7G7tIMDE910ZmKi778tOGUug5dqfs7xEImxDAGZ28DQXlLZhb1sg2mPX1UHtZTDhAKrB6IIfrO1YLxPsIPt0yJ4M1AuD32ETSBuT2pwD7TR7v)zoI7D5F7zLcro3xINu3W1HOaYHvXyyMXH7tqVQkqsQdBZhsK5l3LGPOdl21C9rqpcpPK4MlybdyBtviibWrYvsCnpyqXyW1l19F(mkwCRvtCS(sR2azRsO6OXleBzTNgkHpbafoKgs6I2(DmBzym)o1CDCAM9l9EykfpD)929X2KNh2WzBjLzGAzXyHUF6fNOnXuYPf)fGPuwbfbpvEYQrx)2hur5(O7)v3FRkd(Rd(Vp

**Comment by InfusOnWoW** [comment]
That setup does not work, because if none of your triggers is active after closing the options/loading the custom trigger function is never called. This is expected.

You need to add a always active trigger, to ensure that the trigger combination function is run.
