### ISSUE TITLE
Generic health trigger doesn't fire on UNIT_MAXHEALTH

### ISSUE THREAD

**Issue by Kazimazi** [WeakAuras/WeakAuras2#3225]
### Description

I was trying to show my missing hp, but on max health change it didn't update with the generic aura I made.

I think it is a classic specific bug since health doesn't regenerate continuously , but only every second or so.
### WeakAuras Version

3.5.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Import string.
2. Increase your max hp (remove and put back on your item with stamina)
3. Notice your aura text won't update till you get your first health regen proc.

### Screenshots

[Image](https://cdn.discordapp.com/attachments/827198294832578620/868118808198516776/missinghealth5.png) showing that although my max hp increased the respective values on the weak aura didn't (bottom left of the image 6561 / 6561 / 0 which are current hp / max hp / missing hp). The chat shows the result of `/dump UnitHealth("player")..", "..UnitHealthMax("player")` at the exact time I applied stamina buff (which increased max hp).

### Export String

<details>
  <summary>string</summary>
!WA:2!1nvZUrorq4mAI0UYcfTmODbjqclqlkraHfqBoWfyCWwtqtYm4XztqCW02D5X9k7UB1D7zZSNqJ2dCoVbmN50ChjepbwriEa2hHCGZuTTx(nRV4QQU6Q(((QQ7fmOCaDa9h2vjQmfmoOMCA04JoXx(2uMwwqwgbxyIZeQsIj2imKIohpUGdB(hjjV79ZbsHj39JCVFtMwJ01PvAJOSjJWSkEQHj47UNJRRcmvkU7UKkfjg4l2xBigy)2RkuUpyp3p8)DAxlAo2b40R05eQ4jFZKSmnyERT2q4P5c1ubJBso0)Ki)qP7nqfzSHvcDE9K35Vr5Psk2OqybWnpNuHrjgw6zmQj3Bi6QinuqFqiIiLXjjJXz6Chp8NXzLrXMphu6DEpvN5V7zwkbVk84nTTj2gOEN1uiPkllcDuJ8hpn40X17KmQHH1VrIfYG656QKgSmvbzSlcNn1F84vvAi2wWVBLwcffhr1oTzPL7E6jhffpYF44OrFwBn(GMqhp88)v0)QYZqqWUyt8HdNffplAyy010LCsjl9lrX3s28q0f0oVa)5mkeAfq6Lv8oA6iFvRYSaIA9pwqHFARBu8BhIDE1BFnoRafNu8iu3WU9TxQHIS2rO3KOOjh7Lj4g5DcuSN6(1vekIkIBu0AKbHWC70WXRqqObj4UdYO7fwwvyyoEO6KEV6h6eMwq0ARLNM9uWASYwZzOdRBh682DO(RvnL0ow8miQtsf8m2CNljCwzJCCq9GGFfiAyMrb85M8Bv)61BFfTtTAgVknG3JQxzZZwR6T9kjmEq9N3KD9xupS2d))A)3iY39LVVkvqkZQr9LV5nMvNMU3ABZznlQi5ffc1x1h)upghGSSLEJ9dIwBePlAL8Bp9UVdJEzjtRz855YvprOONPiYvN1zSjtHRaiHrPV)1TVYcSHSClz2HH((NOw2kHJ(Lhp4p2c)(KkgDtq2hxDq4rpcc3t((VCQ1TYfBYvGoxuqxEf(6d7Yezln20oMoSHm961R)ACRfOnVmF2RSHXBRhMRJ6IxaKV)N)XriqgOd)09F4(pyWIF78)8d
</details>

**Comment by asaka-wa** [comment]
Quick demo Aura 

```!WA:2!LA1xZTTXrCHbtAtWmnvsPwAKRDkc74uPKihx1A300rnMqMmKUYuYGuws2oL6aWrcybcC5aaLOstBTAhx1)Lowp0pa8Xo5j(jiJ)eSJMo9dG)iOx7dT7DhcPKL80hQMrG3T3U3T7E7VF7PDVjtw4w0Ut2zsVj9o4Yh5qC32JhZwkomMFBDD9v1V2vV(ZDI5EuUv(ISXTcd2Bpc3ZSrCCyAaRFASBxkpjio6vx9c8DxPvReAQMJYoFEVCbdirU(X8vJdIsDwQuTgLS7R0PEWE0xzGAS6W1000pIKLI6Vclf35eJdtOHTKgdgCIRu4nStsj8udNwbrbj(gw4pPg7NYdA3g9Ol(288HpPVh1jRvRg9yuELslVA51w2kfNytY4Kf2pHrddR6Ly88KmhAxAuADu7GDh0CPI1B0SEJI2nSYWn3Hfs6r52rKo0edBPQovOKWu)HMUkNIMAxF1slV8Hzr5UGrEWwYRnLnr9pnJWPMLZcdnx3piL(m1QQC1R1NtBJbOWDTBZJZyhsIc6qeb9nGXl)mkjHwpLtJAN6)nHPTIIJOh5HHIqJMIaJNqDJJ8s2xOQyFG31QdjiQm8oObW7cVhmpCv83jErjfc8yt3HSRPVmSmD9jrTPMs3WkmM4v2jLeIX5u2DYWcadlm75of8JmSDdjjjIrwj4vQyWGwCmtHUkjLOFSQcOSqKWLCQVKDPs1YV5RgHrUUd61TcAByN4IhIEFmPAlZfjghJ39uEej8EQQTh0xeHbQYJbbrTI5QuKXczbEdwNnBNEUPB3BD)jDFNdUw)egHV96bEP(xOFaAA94mUl9sJbFdT(UzjPXDAq3nLvVvwKS8A25mmn500mEK5SI6KM0OUxfR4sPxnngZbMXCZRnN58Nz18mNCzdAKNb8QAWRbghjDbB0wX(RXM4uZVtSh1Q4AnwXs4D(WB86Vn8D(74vZLGlcFx47bMWBbfGzm2plH2uunUfU0LH30aUamf89nytiWfDPnuvCI97lhtgQnD)AmTo8ZFa86GX(oKCSMoI1q4rcjvu)q9FM0PufIBQbl(HtbtpqeGOfnX)pyA2BLIjQMYpQKEtwZ0Go0Mmo1nqC3OF4qvkCfx24Yzj(eV4DgHWFUs6qCDv2BiLGa)yXnPR8YYQio9y1HfSl1tk8XhPQL2mNC5zY1FeElg0Qhy0NlYPuX9PvTvQvcMMJfscD6lvCu64W8OikLnEzEWEM3nJ4jQwnB04OHRjQwTQHGm2KNisYp8lnwUZSrUZOSBhSQEDoHT)65du(yxm)4es3kpNCcsX(vRvRKDZLlvUb7nFzzy1mn2mNJcQb2c98g57c21zyZ9Y2qVEixwGBZuFonXpo0R3PIX8ys)GPGyDOoB8RKxC)(MxrccGgY7synOkCpyDyJhZU8zolPM5tqMM7dgWdGhIL2Fc8lvvLnHTaxelsahGcTG2Bb(duje7QFCLZlJOCKH765KsIgDKDMb80Gn1C8PbT9tRCZR)F(3F1yJng8dldliyQGFS871LFVH47ZLablKQZtaLwO4TUfBCe6v0tuNr9OE3HSR)aPwvc88Or21kDVs2WCco6xKN99)FZ8cFB0qdycdysJx8KcqcHFaphgEsi6gAhkr4jbEuBzQc(zgkfeL)zCkB2QcIZwex6dxIGiKO2we(dxR68JMnFDHb5XImdTipvz((FDdFO4G4gv7C7vE02XBEFR9IJ7OzlTWhEfS1p24a5XBrWMc27iaPvUj7RgBlmjBtcz(eD4dGFk8t0veXdFLHopis8(bQp8TmgeZdWwls(W(vwXU69xPwJIldFKbCtJJfVqr0hkYBijI8nkhCnyPlaFUgYKdLy2))tG3LeMrpf)98c(B4J1GkyD(TZjN)xW0oQohsg6FXwdjProzKAw9EGe2SRvRAJMvkvC5gv(q1limLIUtXnoL0bQDt2bFG0vYyE4xBxFQ724UpJb8ugmmaterOPzYdku4tmx08ZKZe)PcGfnxd7sOEEYSfuhrH5EVHAPscNulSI(8uKXJBJ0djcEqu)ccxlWTWifqMJDWfs5z0rcvVCW7uY)C538lfHyr(nV)fS8xogCNHDPuWib(aHjNag9csM4msQD7kF0)4IY)0rMPv8HvZ7Jb39GPbBKhdBkDwIlKE4LrnHCFc2POEsYjbjLpeapsd2gcZ5wAVfU3coYJVIk7)YziHpDej45WwknFe115WsIo6i)GdjOwJi5qQZStXVDJZWVPy86c7a76d)XH4u4VnesLZfnPKo6ZqUh4xHWt4xd)g43cpgPc(al71c2mzT2z3f2Fr43b)E4pRCYNOb)HHmcWtH)Koc6Ly)EWEi5e8x8HBHbXFf(cfUw8EKj7(p34)o```

(tested with Mark of the Wild)
