### ISSUE TITLE
Bloodlust/Heroism haste buff expiration wrongly affects Swing Timer

### ISSUE THREAD

**Issue by Bakamaka11** [WeakAuras/WeakAuras2#3231]
### Description

Haste buffs wrongly affect swing timer (Bloodlust/Heroism are main most important and frequently used examples, other sources probably are not important for now i think). 

Quick info from previous thread:

> If you have Heroism/BL expiring on you during the swing - the swing timer adjusts automatically to the normal speed, but in reality that one last swing during which the haste buff ended is still "hasted" and therefore Weapon Swing Timer shows incorrect info.
> So something like that is happening:
> I have Heroism/BL (Swing timer shows 2.5 attack speed).
> I hit the target (2.5s swing timer)
> Heroism/BL ends (Swing timer instantly adjusts to 3.6 attack speed for current attack)
> The hit still happens in 2.5s, even tho swing timer showed me 3.6 attack speed.

Proofs:

https://www.twitch.tv/videos/1092997016?t=04h02m50s  (swing reset at 4:02:57) Streamer is mad about reset and failed twist
https://www.twitch.tv/videos/1092997016?t=04h59m00s (swing reset at 4:59:05)

### WeakAuras Version

WeakAuras 3.5.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1) Attack something.
2) Get Bloodlust/Heroism (+30% atk speed buff) from shaman.
3) Wait untill it is about to expire and watch at swing timer bar.
4) During the last swing under the buff, WA will automatically adjust to normal attack speed, but in reality the swing will happen at hasted speed (resulting into swing timer filling bar reset at ~70% progress).

**Comment by InfusOnWoW** [comment]
That's a outdated version and the 3.6.0 has several fixes to the swing timer

**Comment by mrbuds** [comment]
It's a side effect of change made on 3.6.0, please give more tough on the ticket with a complete list of haste buffs that change swing timer mid-swing.

**Comment by InfusOnWoW** [comment]
The reporter is using 3.5, so it can't be the 3.6 changes.

**Comment by Bakamaka11** [comment]
> The reporter is using 3.5, so it can't be the 3.6 changes.

As the Sulis said from previous [thread ](https://github.com/WeakAuras/WeakAuras2/issues/3205#issuecomment-885976054) about those changes which today sneaked in 3.6.0 - the changes made things worse and shouldn't made it into release. 

It is probably better to revert all swing timer 3.6.0 changes to 3.5.0 state untill Sulis makes a new thread with his detailed findings about each haste buff interaction with proofs, since my thread lacked of information.

**Comment by InfusOnWoW** [comment]
@Bakamaka11 You open this bug report with a supposed bug in 3.5.0. If you want to report a issue in 3.6.0, you need to open a NEW bug report.

Adding a comment here, which isn't even describing what exactly the problem is, is NOT the way to go.

If you can't be bothered to create proper bug reports, bugs will not be fixed.
