### ISSUE TITLE
[AuraBar] Texts swapped for vertical bars

### ISSUE THREAD

**Issue by Hamsda** [WeakAuras/WeakAuras2#324]
While working on a request regarding a vertical bar, I noticed that the text fields for vertical bars are "swapped".

Simple example using the Prydaz buff: https://wago.io/SkDnwY5GG

What I mean is that for the horizontal bars, the bar empties towards the text that is entered on the left side of the GUI (so for RtL it's called "Left Text" and for LtR it's called "Right Text").
Just by switching to one of the vertical orientations that behaviour gets flipped. The bar now empties towards the text that is entered on the right side of the GUI (so for TtB it's called "Bottom Text" and for BtT it's called "Top Text").

I would expect the texts for the vertical orientations to behave the same as the horizontal ones, meaning the texts are swapped so that the bar empties towards the element that is entered on the left side of the GUI.

**Comment by InfusOnWoW** [comment]
Right, feels a bit odd and incosistent, but to change that we would add a bit too much complexity for something that probably won't bother anyone...
