### ISSUE TITLE
Can not get chinese charactors by new function of WeakAuras.GetMHTenchInfo() 

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3248]
### Description

After typing /dump WeakAuras.GetMHTenchInfo() , it returns unknown about enchanted name.
This issue caused by the factor which one chinese charactor occupies two bytes.

### WeakAuras Version

3.6.1-2-gef69528

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. /dump WeakAuras.GetMHTenchInfo() 
2. no enchanted name returns
![WowClassic_o5nfrzh7vE](https://user-images.githubusercontent.com/46548538/127733071-f0d22e44-4bff-4078-a437-986716505c7d.png)
![WowClassic_96Zcq7RA7S](https://user-images.githubusercontent.com/46548538/127733074-d5b4dcbd-7974-4f5b-935d-2e1d967b14ca.png)

### Screenshots

![WowClassic_o5nfrzh7vE](https://user-images.githubusercontent.com/46548538/127733099-0ba3af6a-4f5c-4abd-b15e-bdb5ed5097d1.png)
![WowClassic_96Zcq7RA7S](https://user-images.githubusercontent.com/46548538/127733101-6d96b154-27f4-40b1-bbbb-cc102b2453b3.png)

**Comment by q513902026** [comment]
i try fix this
`do
local patterns = {}
local gsubPatterns = "([^|]+)[|][4]([^:]+):([^;]+);(.*)"
local function SetupWeaponEnchantPatterns()
    local temp = {ITEM_ENCHANT_TIME_LEFT_HOURS,ITEM_ENCHANT_TIME_LEFT_MIN,ITEM_ENCHANT_TIME_LEFT_SEC}
    for i,v in pairs(temp) do 
      local raw_i = (i* 2)
      patterns[raw_i-1],patterns[raw_i] = v:gsub(gsubPatterns,"%1%2%4")
      if patterns[raw_i] ~= 0 then
          patterns[raw_i] = v:gsub(gsubPatterns,"%1%3%4")    
      else
          patterns[raw_i] = nil    
      end
    end
    for i=1,(#temp) *2 do 
      local temp
      if patterns[i] then
          patterns[i] = patterns[i]:gsub("%((.+)%)", "%%(%1%%)"):gsub("%%s", "(.+)"):gsub("%%d", "%%d+")
      end
    end
end
SetupWeaponEnchantPatterns()

local function GetWeaponEnchantText(text)
    local _,enchantText,enchantShortenedName
    for i,v in pairs(patterns) do 
        _,_,enchantText = text:find(v)
        if enchantText then
            return enchantText
        end
    end
end

  local mh = GetInventorySlotInfo("MainHandSlot")
  local oh = GetInventorySlotInfo("SecondaryHandSlot")

  local mh_name, mh_shortenedName, mh_exp, mh_dur, mh_charges, mh_EnchantID;
  local mh_icon = GetInventoryItemTexture("player", mh) or "Interface\\Icons\\INV_Misc_QuestionMark"

  local oh_name, oh_shortenedName, oh_exp, oh_dur, oh_charges, oh_EnchantID;
  local oh_icon = GetInventoryItemTexture("player", oh) or "Interface\\Icons\\INV_Misc_QuestionMark"

  local tenchFrame = nil
  WeakAuras.frames["Temporary Enchant Handler"] = tenchFrame;
  local tenchTip;

  function WeakAuras.TenchInit()
    if not(tenchFrame) then
      tenchFrame = CreateFrame("Frame");
      tenchFrame:RegisterEvent("UNIT_INVENTORY_CHANGED");
      if WeakAuras.IsClassic() or WeakAuras.IsBCC() then
        tenchFrame:RegisterEvent("PLAYER_EQUIPMENT_CHANGED");
      end

      tenchTip = WeakAuras.GetHiddenTooltip();

      local function getTenchName(id)
        tenchTip:SetInventoryItem("player", id);
        local lines = { tenchTip:GetRegions() };
        for i,v in ipairs(lines) do
          if(v:GetObjectType() == "FontString") then
            local text = v:GetText();
            if(text) then
              name, shortenedName = GetWeaponEnchantText(text)
              if(name) then
                return name, shortenedName;
              end
            end
          end
        end

        return "Unknown", "Unknown";
      end`
      
      but shortenedName always return nil

**Comment by roundzero** [comment]
> i try fix this original code by [Aura Frames1](https://www.curseforge.com/wow/addons/auraframes1)
> Libs\LibAura-1.0\WeaponEnchantments.lua#L58-L85
> 
> ```
> local patterns = {}
> local gsubPatterns = "([^|]+)[|][4]([^:]+):([^;]+);(.*)"
> local function SetupWeaponEnchantPatterns()
>     local temp = {
>         ITEM_ENCHANT_TIME_LEFT_HOURS, ITEM_ENCHANT_TIME_LEFT_MIN,
>         ITEM_ENCHANT_TIME_LEFT_SEC
>     }
>     for i, v in pairs(temp) do
>         local raw_i = (i * 2)
>         patterns[raw_i - 1], patterns[raw_i] =
>             v:gsub(gsubPatterns, "%1%2%4")
>         if patterns[raw_i] ~= 0 then
>             patterns[raw_i] = v:gsub(gsubPatterns, "%1%3%4")
>         else
>             patterns[raw_i] = nil
>         end
>     end
>     for i = 1, (#temp) * 2 do
>         local temp
>         if patterns[i] then
>             patterns[i] = patterns[i]:gsub("%((.+)%)", "%%(%1%%)"):gsub(
>                               "%%s", "(.+)"):gsub("%%d", "%%d+")
>         end
>     end
> end
> SetupWeaponEnchantPatterns()
> 
> local function GetWeaponEnchantText(text)
>     local _, enchantText
>     for i, v in pairs(patterns) do
>         _, _, enchantText = text:find(v)
>         if enchantText then return enchantText end
>     end
> end
> ```

It works.

**Comment by InfusOnWoW** [comment]
@q513902026 that addon is under a ARR license. Please do not suggest stealing code from a addon.

**Comment by q513902026** [comment]
i mean.just example
