### ISSUE TITLE
Add SpellHit and SpellCrit to Triggers -> Character Stats

### ISSUE THREAD

**Issue by cliaz** [WeakAuras/WeakAuras2#3256]
Add the following as trigger options, under Play/Unit Info -> Character Stats

- Spell Hit rating 
- Spell Hit %
- Spell Crit rating
- Spell Crit %

Unsure about the complexities involved by catering for talents. The custom triggers I wrote to cater for talents are...messy...hoping there's simpler ways.

**Comment by mrbuds** [comment]
Please answer questions in the template, crit rating / % are in this trigger already

**Comment by cliaz** [comment]
**Is your feature request related to a problem? Please describe.**
I'm unable to return spell hit rating / %, or spell hit rating / %, by using the Trigger 'Player/Unit info' --> 'Character Stats'

**Describe the solution you'd like**
I would like those attributes shown as trigger options.

**Describe alternatives you've considered**
I've written custom functions to reference the following functions in order to get the results:
- GetSpellCritChance()
- GetCombatRatingBonus(CR_HIT_SPELL)
- GetSpellHitModifier()

**Additional context**
Trigger options for 'Player/Unit Info' --> 'Character Stats'
- https://imgur.com/EFMloGz
- https://imgur.com/whWi0Mb
- https://imgur.com/NLa231l

Trigger Replacements shown when 'Player/Unit Info' --> 'Character Stats' is selected: https://imgur.com/XSCCnU7

**Comment by mrbuds** [comment]
![image](https://user-images.githubusercontent.com/189656/129010319-f78e021d-2335-4373-8bd2-6716794cfd37.png)

**Comment by cliaz** [comment]
The values returned by those triggers seem to correspond to physical crit rating and physical crit %, not spell crit rating and spell crit %.
