### ISSUE TITLE
Group placement resetting while moving with drag and drop

### ISSUE THREAD

**Issue by krazyito65** [WeakAuras/WeakAuras2#326]
What steps will reproduce the problem?
https://wago.io/Sk9uRW_5Z

I'm simply trying to move the group, usually towards the middle of my screen.
I've had it happen with this aura most recently, but I think its a general dynamic or normal group issue.

https://www.youtube.com/watch?v=BhOrlvqUn_Y&feature=youtu.be  -- i made a video to illustrate the issue.

What is the expected output? What do you see instead?
That the group moves as expected;  The group re-anchors itself to the top right corner and resets its placement.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes, same issue.

What version of WeakAuras are you using?
Video footage was from a 2.4.7 alpha, but I've reproduced it on 2.5.1

Was it working in a previous version? If yes, which was the last good one?
I think its been a problem for years for me, just never bothered me ENOUGH until now.

**Comment by Shupandulli** [comment]
It's broken for me too... anything i try to drag starts jumping out of my screen...
Even a new created single icon not even a group. As soon i start draggin its gone.

I had this Problem now for the first time.  22/12/2017 
I did a new Weakaura setup like a week ago and everything worked fine for me there

**Comment by Translitdk** [comment]
Same stuff happens if you try to select Action > glow  and click on the WA

**Comment by Shupandulli** [comment]
@Translitdk lol you're right... I remeber that i had this Glow bug a long time ago... never using that glow stuff but last time i tried (like 3 months ago) i had the same thing there

**Comment by jcai1** [comment]
I have also been having this problem along with several guildies. The offending lines seem to be [here](https://github.com/WeakAuras/WeakAuras2/blob/47cdf7af2bb4ea49354e4c4b29edbf0fc48707b1/WeakAuras/RegionTypes/DynamicGroup.lua#L370-L372). Getting rid of these lines appears to resolve the issue. Perhaps the addon authors have further comments.

**Comment by InfusOnWoW** [comment]
Was already fixed by the commit on Jan 3, now with a hopefully better fix.
