### ISSUE TITLE
want the WeakAuras to be adaptive for the Mop 5.4.8

### ISSUE THREAD

**Issue by carbonink** [WeakAuras/WeakAuras2#3260]
Hi, Author, The WeakAuras is very useful and many players can't play without it. it is great! And I beg you for coding the WeakAuras interface so that it is adaptive for the Mop 5.4.8 Version. As there is a server named Tauriwow and the Mop(mists of padanria) is avaliable.
Also, I found a WeakAuras-Mop repositories , But there are some Desaturate Issues and the Author want help, I think you are so great and have the ability to help him, and I paset the link below and wish you can help. Thank you again.
https://github.com/Maczuga/WeakAuras2-MoP (Avaliable for Mop 5.4.8)

**Comment by emptyrivers** [comment]
We don't support unofficial game versions. We will add support for mists of pandaria if/when Blizzard releases MoP classic.
