### ISSUE TITLE
Add additional original media

### ISSUE THREAD

**Issue by leobolin** [WeakAuras/WeakAuras2#3268]
I've created a few custom textures and sounds and wanted to see if there's interest in including it in WA. After some discussion on Discord it was suggested I open a ticket here. I don't expect all of these to be added, but if you want to here it is!

Also I'm sorry if I'm not following the proper ticket format, I wasn't sure it was particularly applicable in this case.

GitHub doesn't support uploading BLP files so I have zipped the textures instead.

## Bar Texture: Stripes

Of particular note I think WA is missing a striped status bar texture and after not being able to find a good one I created one myself. Personally I use it to overlay absorb amounts on top of health bars which I think looks quite nice.

I've included 3 variants:

- "Stripes" - A solid black and white striped texture
- "Stripes - Thin Overlay" - Thin striped lines with a transparent background
- "Stripes - Thick Overlay" - Thicker striped lines with a transparent background

![Bar textures in-game screenshot](https://i.imgur.com/2hps5oX.png)

[Statusbar_Stripes.zip](https://github.com/WeakAuras/WeakAuras2/files/7017528/Statusbar_Stripes.zip)

## Bar Texture: Clean

This is a clean, soft bar texture that works really well with all colors.

[Statusbar_Clean.zip](https://github.com/WeakAuras/WeakAuras2/files/7017731/Statusbar_Clean.zip)

## Border Texture: Drop Shadow

A thin drop shadow border texture.

[Border_DropShadow.zip](https://github.com/WeakAuras/WeakAuras2/files/7017737/Border_DropShadow.zip)

Here you can see a combination of all these textures together:
![Combination of all textures](https://i.imgur.com/FeyO29M.png)

## Sounds

I've also created some basic high quality sound effects. They were all mastered by me.

[Sounds_Brass.zip](https://github.com/WeakAuras/WeakAuras2/files/7017746/Sounds_Brass.zip)
[Sounds_Coconut.zip](https://github.com/WeakAuras/WeakAuras2/files/7017747/Sounds_Coconut.zip)
[Sounds_Dulcimer.zip](https://github.com/WeakAuras/WeakAuras2/files/7017750/Sounds_Dulcimer.zip)
[Sounds_Glass.zip](https://github.com/WeakAuras/WeakAuras2/files/7017751/Sounds_Glass.zip)

[You can preview the sound files here without downloading any ZIP files](https://github.com/leobolin/Media_Newsom)

## Copryight/License

All attached media files were created by me (Leo Bolin). I hereby release them into the Public Domain, meaning anyone is allowed to freely distribute and modify the works without any attribution, for any reason.

**Comment by Stanzilla** [comment]
Hey thank you! We're currently discussing this but I have to say I really like the textures!

**Comment by InfusOnWoW** [comment]
I like the textures.

For the sounds, I think most of them pretty good. Though the "duplicates" are a bit too much. That is I'd prefer one of brass error, brass warning, glass, dulcimeter not having all of them.

And I think Cocunut doesn't stand out enough.

**Comment by leobolin** [comment]
> For the sounds, I think most of them pretty good. Though the "duplicates" are a bit too much. That is I'd prefer one of brass error, brass warning, glass, dulcimeter not having all of them.
> 
> And I think Cocunut doesn't stand out enough.

I think this makes sense. I never expected everything to be included, especially the sounds. Just wanted to throw everytihng out there and see what sticked.

It might also be too excessive with the 3 striped textures, if you only want one I find "Stripes - Thick Overlay" to be the most useful one personally.

**Comment by InfusOnWoW** [comment]
We added the textures, but only a few of the sounds. Thanks.
