### ISSUE TITLE
Dialog/confirmation on re-import of an existing Aura.

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#327]
I'm wondering how feasible it might be to add some sort of warning or confirmation when importing an Aura that already exists, or shares a name with one that exists.
 
My guess is that it could be quite easy to simply fire a popup if you import an Aura when something with that name already exists - before adding/incrementing the number on the end. And, actually, just this could be very useful to just give people the nudge they need to delete an old Aura before importing an updated version. But could it be taken further and possibly offer to update/overwrite everything except Display tab settings?

Like, on importing a string:
```
You already have an Aura called "New" would you like to:
    [Continue the Import using the name "New 2"] 
    [Overwrite the existing Aura with this import]
    [Overwrite the existing Aura, except Display settings]
    [Cancel]
```

**Comment by Stanzilla** [comment]
You mean like this https://www.wowace.com/projects/weakauras-2/issues/266

**Comment by asakawa-k** [comment]
Hehe, yes! That about covers it :)
