### ISSUE TITLE
Microsoft defender recognizes as Trojan

### ISSUE THREAD

**Issue by Thomaswalbeck** [WeakAuras/WeakAuras2#3271]
### Description

I updated to latest version of WA trough curseforge to version WeakAuras-3.6.1-25-g1842c9c-bcc, and when i install microsoft defender marks it as script:Trojan. I believe there is an error in your update?

### WeakAuras Version

Weakauras 3.6.1-25

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Update -> Install -> MD deletes files

### Last Good Version

WeakAuras-3.6.1-24

### Screenshots

![image](https://user-images.githubusercontent.com/49226830/130254245-82abde17-5b2a-4ef8-beda-6cb36b45978f.png)
![image](https://user-images.githubusercontent.com/49226830/130254278-7c2e3749-53dc-4bf7-9643-8b4ddb7fc3eb.png)
Translation on .png 2: 

Threat detected: Trojan:Script/Wacatac.B!ml
Threat level: Serious(high)
Category: Trojan horse
This program is dangerous and can execute commands remotely from an attacker.

**Comment by mrbuds** [comment]
This news https://www.wowhead.com/news/windows-defender-wrongly-flagging-wow-addons-as-trojans-323858 show some other addons have same issue.

Scanning this bcc alpha with file from <https://www.curseforge.com/wow/addons/weakauras-2/files>, windows defender don't raise any warning for me,

Maybe this trigger only with files downloaded from curseforge app / overwolf ?
