### ISSUE TITLE
Windows defender (false) positive.

### ISSUE THREAD

**Issue by FearrMe** [WeakAuras/WeakAuras2#3272]
### Description

I have CurseForge setup to automatically update, and I've been getting slammed with windows defender warnings every 15 minutes. I've tracked it down to WeakAuras.
I'm on the alpha branch, and CurseForge downloads a zip that then gets marked as "Trojan:Script/Wacatac.B!ml"

When I download the zip off of GitHub(also commit 490d3d3) it's fine so it might just be because CF is doing it in the background in a temp folder. Anyway, probably worth knowing about.

### WeakAuras Version

3.6.1-26-g490d3d3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

Enable Windows Defender(W10)
Switch WeakAuras to alpha branch in CurseForge
Update WeakAuras

**Comment by InfusOnWoW** [comment]
We know about it.
