### ISSUE TITLE
It would be better if hunter's ranged swing bar reset to beginning when hunter casts Feign Death, and it holds still when hunter is moving until hunter stops.

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3275]

**Comment by InfusOnWoW** [comment]
We do have a issue template for a reason.

**Comment by roundzero** [comment]
For now , when hunter casts feign death, the ranged swing bar is still going and that is not correct. And the bar goes to end then finish the progress when hunter is moving which is also not correct .

**Comment by InfusOnWoW** [comment]
You choose to not answer any of the questions in the template. You need to do that.
