### ISSUE TITLE
WAs sometimes not loading in BCC PTR raids (#2)

### ISSUE THREAD

**Issue by Tems91** [WeakAuras/WeakAuras2#3278]
### Description

As a follow up to the previous post https://github.com/WeakAuras/WeakAuras2/issues/3261

The issues is still persisitng with WAs loading upon death during an encounter and usually not loading on encounters while alive. Results are still random and I have had them load and not loading on the same night with the same pack.

### WeakAuras Version

WeakAuras 3.7.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Import WA Pack
Run SSC/TK
WAs wont show (not always)
Die intentionally on bosses
WAs will start showing while dead

### Export String

!WA:2!Tz1tVnUXv861fyleqb2vBx3fb9aRB3nElq0AjV2BBrsaKKLC0gzjbs5yBu3koICi5etnZKzg6)Sb5q0P9SoNt6qo1tQaT9S)eqi0pb(q)a4l9AFZqkz7KiaBYzEV5nV3V379JVvAwCur)I(V)LtjEmQdlr4HxX2JfZeVDv43uVePInQp(cf))fKq9uegDJxwWc(rcSoeJoTAIajl1s2LRLbpWGcwQim1sGvjcQfM6V4auMYcbhyaMEwPyKuzXe)Gn(yR9WQ(KryWkFKv5sBBSLXa6F3x5p5wLxQHdCF1JqQ9XsjkeVX6F9rFJL9bDSQEy1JTGfRdg(JaNJhJ8WARBnktvlK0IIX(4m)v73WFIl7geiXQvMHOErmrpgHQgwVrN(nSN7XyX(SZPoNt4yx(JUfVoG7Ju4HjMhvseX8FtKsXL)5x9QZrHSse2R29TOGE)XMVX5vL3PMob4owjiHHyHSZle5V((xBt5ET8Tl)N2E7YcjhhhdR2ARnF9Mt0ObfbU)hyV12VU8MJ9Hn05HIBXFuEunGXXWMmX0ac1FJp85Yp8L3KiXdKM0DhTXJgIgXsOQIBoluWs4d8YwXFYDw2n3of)0PYi251JzuSm6AzYq8zyQYjjiGCXSb1R60FGt)Q29NdhWdKeHrXQO1RSPTrXP1zJgIuwTzHtmBOUKJ5pTx7Qh3WEGDJ9A0zWUTCQwRDJDf5bb)33hYtTteNIfw1WXSZTuOtXslKLpgZTgkWiv0mtyLHqUZ1lwAF3R0l9Xs1buIYDIELsG8o1LV29CZLW16F8NmvRvgY4E9IZ3mgfkRezKjvivcGbW77Dlq5QH3gxG8uo5(I2XQgeG9uyWXcXuSG45aGyx61sZJ65fs1sa3BiuAEjwyCsuiKcChVWZt3EjG3tGba32PxJ2TnENksJcM4Z2uvuySEBTfnEWapDkdY2t9HcZGG(aUi(SQ2738G28hRv4EEMRa2QdyNirc1CJ2kOvZ)kDvNbLj(6cpOsCBJRAQtDRPHBBTovMERhnuHeHy1nzO5sqU4Noh0i2Gt6RI)KwufIgsggJTGauIPE45ltRgVzCEgwwyYYnt33eG5vlUzrZ9YRMKYcf0rE0S70a8GjGxL1W9I0wPVn91t0iiKhu4z(e5xA4(odxbrVK)yK59(z6VpZh)3)z3aKcybff)fq3l0a(xU5uOUSk4GEkBDlz0eeLmY0CUJnu3iunVcJKyhLatdvrpmDVAui9mFrl8anokKyGxWxowRQ2RthuBeIq)I09shKoe(7V9Wu3u0qUgRuxl5ebkgr95jXs8qOJNiJAQvsRpOO(mq6xc1TW1aP2ZY83F7uOSYghQ5W)dV)z8IkGdBGmcbfLhLtaoXSN(FJD63ONv3d6ZF0D0RU57gRSYkRED2U44adBzTQh0Vl)jMnrjabjeGEhs8vr1Qcl5wln8GaMaKoaL3SKVoDW8mY3JZDLRmk)LaBlj4Y0hovWGorSM3TwNUDAW)GFKflxAPTs3tabRw4pXnxTzZg173y3LAp1i92VjojxBQI)0QEEeFOedfBkw1V7Dzo2DFhMV(pHhPBQ1vV3gLg5NZe(hkq8XhM)Y8LxPPLfW92TGG8r35Em48eqcqH2VBVBYob5cSVbN)27Lqx4u3AxhY7WpphJp6Ey8zePUz09)opeyDBkWFvIoi79Z3SuLTZqsTan96EX51arJ1BP915dtukgTluLbuAgt0pI4Dk8Ld5QZ0lx4ltcxCAdkN(UcgXhDxXoEOy8Qt1V220080A63DncBtaJ(yJWAaUHfrdJWKWi13wlMH8)(mkkGhdeajmiRTM9OKyfPqnDx6APFxbdfbeDAkkGh031WF(oOR0TMeqiqN1gd5k1LJqu3z3rZkVzRk2EWmjYxmusOHXyXHvTTB11o97Er637oSNDRgo9DRPn2v9XJ4qQ36ZbkcX7mCYYhmvy6(mn5)sXf5X94fty4ovteqmdzvqGmtIj3j9VgK(C(V(RfQ38nwhAxT)Nz1TJ1Z9Sm7C9IraYglHVXTJWTy4mn3SUeCJ1Z(MdmCemZZyFME8aQF0vlmHMnQIt1JTn7Zl3sh4bWeuNu13VlvEYYHbpzFSpbDIJwp5j10dQvIfgofS5c(5AaVKQqAqZjWMzoxu6)ok9FM(Vs)hrvsi(ZOoFvzXHo19p(SHs8iiTzxU0wLkFtwrAtb40ASAOtD7gn6aalB0k10SlrtvmVCATFrVNUoXN)7CyXibbrHrkHgkvKflWm5xvPsa0rWhzeZc0MeOJrk0Q2OyEe848SMNF1ISGMHzxIebDeWqtqgjGewqqO6RdhD1c1A4db5CWzapnFW4c6pJOX4wWPE2dkUZmcnRThKUg)zKqktGZvUH(RTnecMq6ozjnA6dlkT3Q0oLkx8S)Zr)))

**Comment by InfusOnWoW** [comment]
The last time we asked for lua erros, which you never provided.

**Comment by mrbuds** [comment]
No further investigation will be done without Lua error AND savedvariables, since you have spread clickable auras into dynamic group nothing tell us there is not more pollution on your other auras.

**Comment by Tems91** [comment]
Sorry about that, thought it was linked

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function '<unnamed>:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1235: in function `Resize'
[string "@WeakAuras\RegionTypes\DynamicGroup.lua"]:1205: in function `DoPositionChildren'
[string "@WeakAuras\Animations.lua"]:20: in function <WeakAuras\Animations.lua:15>

Locals:
Skipped (In Encounter)

**Comment by Tems91** [comment]
[WeakAuraslua.txt](https://github.com/WeakAuras/WeakAuras2/files/7046294/WeakAuraslua.txt)

**Comment by mrbuds** [comment]
This is same error, delete all auras that attach secure frames to weakauras
