### ISSUE TITLE
Spanish language clients break imports

### ISSUE THREAD

**Issue by krazyito65** [WeakAuras/WeakAuras2#328]
https://media.discordapp.net/attachments/369675183755362304/396064318866849792/unknown.png?width=1082&height=677
https://cdn.discordapp.com/attachments/218087027042811905/395738703026192414/WoWScrnShot_122717_193631.jpg
https://cdn.discordapp.com/attachments/218087027042811905/396451024363192321/Sin_titulo.png
https://cdn.discordapp.com/attachments/396422163089063948/396430982565199873/WoWScrnShot_122917_163406.jpg

we got a span of 4 reports in the weak aura discord about imports being broken, the one thing they all had in common was the spanish language client.

Switching to English seems to have fixed the issue for them

**Comment by Stanzilla** [comment]
Should be fixed!
