### ISSUE TITLE
Add Currency trigger

### ISSUE THREAD

**Issue by glassleo** [WeakAuras/WeakAuras2#3280]
**Is your feature request related to a problem? Please describe.**
I think there should be a currency trigger for WeakAuaras. Currently you'd have to do it with custom code and it's a hassle.

**Describe the solution you'd like**
I would like a simple Currency trigger to be added based on ``C_CurrencyInfo.GetCurrencyInfo``. It could be under Player/Unit Info, similar to how Faction Reputation works with the following data available:

- Currency ID
- Name
- Icon
- Quantity
- Maximum Quantity
- Quantity Earned This Week and Max Weekly Quantity

**Describe alternatives you've considered**
Custom triggers can do this but it would be really nice to have it built into WA.

**Comment by InfusOnWoW** [comment]
We only have a repuation trigger, because someone contributed it. The same is probably true for this kind of trigger. If there's a PR, we would add it. But at least I have no intentions of adding those kind of things.

**Comment by leobolin** [comment]
> We only have a repuation trigger, because someone contributed it. The same is probably true for this kind of trigger. If there's a PR, we would add it. But at least I have no intentions of adding those kind of things.

Good to know.

**Comment by InfusOnWoW** [comment]
Note, that there are others on the team. I don't know whether @mrbuds thinks this is a worthwhile project.

Or whether @asaka-wa who did the reputation trigger (iirc) would want to give this a try.
