### ISSUE TITLE
"/wa" does not open WeakAuras2 config (with a private server Project Ascension)

### ISSUE THREAD

**Issue by Jafusa** [WeakAuras/WeakAuras2#3281]
### Description

I am using WeakAuras with a private server client for Project Ascension (WoW version 3.3.5).  when I attempt to open the config interface, I type "/wa" in chat.  The game seems to "stumble" but nothing opens for WeakAuras.  In addition, none of my WeakAuras are active or showing.  I have included the error code from BugSack and BugGrabber below.

This version of WeakAuras (2.0.8) was working until I accidentally "Updated" it to the most recent version of the AddOn.

### WeakAuras Version

WeakAuras 2.0.8

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x WeakAuras-2.0.8\WeakAuras.lua:1666: attempt to call method 'Collapse' (a nil value)
WeakAurasOptions-2.0.8\WeakAurasOptions.lua:1197: in function `ShowOptions'
WeakAurasOptions-2.0.8\WeakAurasOptions.lua:1172: in function `ToggleOptions'
WeakAuras-2.0.8\WeakAuras.lua:46: in function `OpenOptions'
WeakAuras-2.0.8\WeakAuras.lua:51: in function `value'
Interface\FrameXML\ChatFrame.lua:4070: in function `ChatEdit_ParseText':
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText':
Interface\FrameXML\ChatFrame.lua:3698: in function `ChatEdit_OnEnterPressed':
<string>:"*:OnEnterPressed":1: in function <[string "*:OnEnterPressed"]:1>

Locals:
msg = ""
firstLoad = true
frame = nil
WeakAuras = <table> {
 SetAuraVisibility = <function> @ WeakAuras\WeakAuras.lua:2597:
 ShowSpellIDDialog = <function> @ WeakAurasOptions\WeakAurasOptions.lua:8465:
 GetRuneCooldown = <function> @ WeakAuras\WeakAuras.lua:731:
 frame_strata_types = <table> {}
 DisplayToString = <function> @ WeakAuras\Transmission.lua:391:
 UnregisterEveryFrameUpdate = <function> @ WeakAuras\WeakAuras.lua:4667:
 regions = <table> {}
 form_types = <table> {}
 EnsureClone = <function> @ WeakAuras\WeakAuras.lua:3816:
 debug = <function> @ WeakAuras\WeakAuras.lua:138:
 CanShowNameInfo = <function> @ WeakAuras\WeakAuras.lua:4427:
 tutorials = <table> {}
 RemoveGTFO = <function> @ WeakAuras\WeakAuras.lua:5082:
 pAdd = <function> @ WeakAuras\WeakAuras.lua:3309:
 Rename = <function> @ WeakAuras\WeakAuras.lua:2723:
 IsRegisteredForCustomTextUpdates = <function> @ WeakAuras\WeakAuras.lua:5022:
 LayoutDisplayButtons = <function> @ WeakAurasOptions\WeakAurasOptions.lua:1432:
 transmitCache = <table> {}
 event_types = <table> {}
 TenchInit = <function> @ WeakAuras\WeakAuras.lua:4697:
 raidUnits = <table> {}
 miss_types = <table> {}
 GetGCDInfo = <function> @ WeakAuras\WeakAuras.lua:755:
 OpenIconPick = <function> @ WeakAurasOptions\WeakAurasOptions.lua:8321:
 OpenOptions = <function> @ WeakAuras\WeakAuras.lua:30:
 autoeventend_types = <table> {}
 CanGroupShowWithZero = <function> @ WeakAuras\WeakAuras.lua:4405:
 talent_types = <table> {}
 GetSpellCooldown = <function> @ WeakAuras\WeakAuras.lua:739:
 LoadFunction = <function> @ WeakAuras\WeakAuras.lua:275:
 circular_group_constant_factor_types = <table> {}
 GetAuraTooltipInfo = <function> @ WeakAuras\WeakAuras.lua:4808:
 events = <table> {}
 AddManyFromAddons = <function> @ WeakAuras\WeakAuras.lua:2830:
 WatchForMounts = <function> @ WeakAuras\WeakAuras.lua:4927:
 StringToTable = <function> @ WeakAuras\Transmission.lua:373:
 class_color_types = <table> {}
 blend_types = <table> {}
 ImportString = <function> @ WeakAuras\Transmission.lua:825:
 GetPolarCoordinates = <function> @ WeakAuras\RegionTypes\dynamicgroup.lua:36:
 CreateFrame = <function> @ WeakAurasOptions\WeakAurasOptions.lua:5720:
 threat_unit_types = <table> {}
 Deserialize = <function> @ BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:240:
 group_types = <table> {}
 RuneCooldownForce = <function> @ WeakAuras\WeakAuras.lua:1053:
 text_rotate_types = <table> {}
 MultipleDisplayTooltipDesc = <function> @ WeakAurasOptions\WeakAurasOptions.lua:123:
 UpdateMouseoverTooltip = <function> @ WeakAuras\WeakAuras.lua:4538:
 spec_types = <table> {}
 WatchSpellCooldown = <function> @ WeakAuras\WeakAuras.lua:1007:
 RegisterCustomTextUpdates = <function> @ WeakAuras\WeakAuras.lua:5013:
 CanHaveAuto = <function> @ WeakAuras\WeakAuras.lua:4364:
 ActivateEvent = <function> @ WeakAuras\WeakAuras.lua:1850:
 AddOption = <function> @ WeakAurasOptions\WeakAurasOptions.lua:1952:
 Convert = <function> @ WeakAuras\WeakAuras.lua:2768:
 LoadDisplay = <function> @ WeakAuras\WeakAuras.lua:2237:
 class_types = <table> {}
 sound_channel_types = <table> {}
 CheckCooldownReady = <function> defined @WeakAuras\WeakAuras.lua:
  ---

### Reproduction Steps

1. type "/wa" in chat window

### Last Good Version

weakAuras 2.0.8

**Comment by emptyrivers** [comment]
Hi, we don't support WeakAuras on private servers (and we certainly don't support old versions of WeakAuras), so unfortunately you will need to figure this one out on your own. 

Since you likely updated past a migration barrier, you'll need to get a backup of your data before you changed versions.

**Comment by Jafusa** [comment]
thank you for your reply.  Sorry to waste your time.
