### ISSUE TITLE
Add Trigger to Armor Enchant (Chest)

### ISSUE THREAD

**Issue by anhell** [WeakAuras/WeakAuras2#3283]
**Is your feature request related to a problem? Please describe.**
It's hard to track the armor kit enchantment in the chest piece

**Describe the solution you'd like**
A trigger dedicated to do that like the one for weapon enchant / fishing lure

**Additional context**
Trying to track the time left of an amor kit enchanted to the chest piece, but I can only parse the tooltip text, it doesn't update regularly and it isn't time formattable

I don't know if it's possible at all as it's not an aura, so I'm sorry if it is a bad suggestion, thank you

**Comment by InfusOnWoW** [comment]
Blizzard has unfourtunately not provided a convenient API for checking for armor enchants. Thus the only way to detec them is via tooltip scanning. Several auras on wago.io implement that. For a built-in trigger that's too fragile to support.
