### ISSUE TITLE
Animation Sequence not working

### ISSUE THREAD

**Issue by Hristiyan-Ivanov** [WeakAuras/WeakAuras2#3285]
### Description

Animation Sequence not working properly.
The Problem is when I apply an Animation to my Metamorphosis (Demon Hunter ability), with Animation ID: 1135049
And set Animation Sequence to 6/1499.
The animation is similar to Arcane Orb exploding, the animation sequence should trigger that explosion hundreds of times, but its not, it triggers it only once every few seconds.
Check the attached Gifs.

### WeakAuras Version

WeakAuras 3.7.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Set Animation Model: 1135049 (To any spell with duration) -> Animate -> Animation Sequence: 6
2. Apply it on a Bar
3. Trigger -> Aura -> Unit: Player -> Aura Type: Buff -> Aura Name: "the name of the spell"
4. Use that spell
In my case its Metamorphosis Buff (Demon Hunter Buff)

### Last Good Version

WeakAuras 3.6.1-4

### Screenshots

![Animation Sequence Not Working](https://user-images.githubusercontent.com/80887878/131895378-53123a22-579f-49f7-9998-8f6a25075d8a.gif)
![Animation Sequence Working](https://user-images.githubusercontent.com/80887878/131895419-aaa43a77-ae15-4bc0-835c-d69d6426008a.gif)

### Export String

!WA:2!LzvWUTXTwuprfiOUVGAl0AKxWlagPTgTlIDKCtcsq7RrJTuKkSLCgj76MgajoA4OH1Jizi5ylPfjTQDrwRpH5tq)afW9hyGr33cJUR7mE7Z7ssLix0zZWH8E59YZ9CUCCQKVF(G8bVYpvYrIJ(gsGkk30(SaCCn5(uIkQiItIodLOIyIgCfHrLlkg2imuIvvF0JE9RxyHfCMIODH13JrOk)TkxVvzVZmBOhtH0(4umreZ)prkfx(Wn24eup26e2gLcXuKO92v34EBkqDn7(98KkKqTOFiHsKrRmoG1wYsObrUWeQfNeYOQkXOEsrJ9BTtT6LtjDz02DzXmXxNdEMiXXHMCj7QJ9rITSRu9RYwcEE)F3jxAawIujcKchnwmlhvV3PMC2E2(2CUXmuWRwwqO9eSe(kE9tIvKfNKiXTP4JXIiVUXiPCnFjysmE62L3Tr9Q7Rp9z3WANXGoUWzdVcmNRKmYmqOqXyQQOESVDSDDoU7Az3mx2nEyNoDsdiHHKUqyhQx9C9ocwehFeLDcTZe(X85(kcTaOzFeSytCsnjbRVps1jDURx)k)1VkgXO4AbYRmwIFEcM2fFTufPp(nWf84j7cBFUubUhSXTgYXEgQHpuH6EKmYsuAlvTtKprOWdaif7fIfBE3X6VQaGkFPkcYOvFsckaGB0QTAjSEnkEbpdEhLQyDb4ucX46oT)FtmzH23S7ppcIb)5sws688JVKz5TjsEmAynAilQycjy6WrL4hg4w(5(1NVbQrot0j1C3DhXy9DSf9w2KN)P1OkSgkXpBlKubfwxK4z7x72Z)62n1oCUpteGfUaqeiyC36aAEQDolbkNhkMhHYDrGn90ryhCOk)QPaNSgTIaoHDMADXMuooo5MHodCC1S6OlSkRkcuFSUa43ClVYLRZxQBIuX6R3095bap2pX86uotOeiI6PWzlYufAcCUBowji96bGC91eZg(QpCccKauyNL34SDXkuFMGhXKe54aT2aQh5lCwpmfliDBgXoPb9uP5vjGPDmESMCLaAsGjYobluq(9rNPN8TFgbkn)KWqDQlQwEN9QS)ocWI6qq7CUmXh0ruvtWcYGPT3QuZwTB2QKxRZn7qBg4fsXe36)(LIeQXwpn7iWZm(0TIqQv3flLOEy(sMiJfDHvmUh92aSNadbWR5EL3zNPwKRDejaNfo2ikazGvVA8RJNbtw0vFc80yurpZc5l4QpU(6YjwmjHodjxl7zDYKzQPqP(7tOgWPikoMVmYmUL1SDHkBUlrih4CbrZ2OO4dS0)V7u7QHKyqAkkuyZ7ENp)btqusFt54Ez)RdY4UuGRngJKggr2l85cmq4Cdrb4t1t3ujW0EQORE2BQJT1hfHeduQaPBFeHwj7NY(5mE2lYgF1SxcVU2bMV0d)HSFuplyWLY2HoUA2u0uJEPkjiat9Qx(GYENdkJUhnC7zXkYiZmDOZw2xI7dABVIRxC97iMPYFzQTbIMz(V9JWKErWDjBUW78A4X2eAM7x4d2PB)sdMlro3KbUqJVanKwS02BFM)mD4BTYzwmS9rsnn5XA5IB9g1lFP(kdDsTFWrQi(dm8b5g3pCq7aCF40KOlrTpbj6fJGAPKfQIWb4Uy4dr7(ePekwR3V4LV84qhFRUok1(UCau)lS6EKbq3tOies6T4SL0GqoXGz3O(l)XxKb3OUWeZDAsGJ65v7XvBDPeEKdF5)2LRAqWT0(TAmR0yWZpZ2g1i(nAgrNPwe5Y9pVuVjpTx8p4t4R(pEM5OTM84BrcsRKig2wh34z9RgEyUcRxyAOUpfq)Go9VR3j6)M4JVMafCm0fd3Xf(lcwh4(unnahz)dHTT3eJJMYeeqQAorPvB4v7PnQ3Q0oPAklX(FhtjqlEHvkSc)6KEuMap7NskR15LfcMq(MMQ1O62W5LEBU(9xVq(J)Td)))

**Comment by InfusOnWoW** [comment]
The animation was bugged previously, and wasn't showing correctly. That was fixed in 3.7.

**Comment by Hristiyan-Ivanov** [comment]
It is not, the 2 gifs that are attached have the same Animation Sequenece, you can see the first one "the arcane explosion" happens once every second, the second gif you can see "the arcane explosion" happens dozens of times at a second, and it is causing this "glittering, sparkles" effect. I have tested all the versions and from 3.6.1-4 it is not working, currently im with the newest Alpha build that is 3.7.1-3 (From 4th of September). Could you take a look again? This issue was seen and resolved exactly 2 years ago.

**Comment by InfusOnWoW** [comment]
The current behaviour is the correct behaviour, as you can for example see here: https://wow.tools/mv/?buildconfig=5172b7b6b7a17875f5329fd1480fdc46&cdnconfig=9c85515e748c7941d772db6677bb759c&filedataid=1135049&type=m2

In previous versions the behaviour was wrong, and thus this has been fixed.

**Comment by Hristiyan-Ivanov** [comment]
I am still confused, isn't "Animation Sequence" supposed to be how many times certain animation is executed? So if i put it on 1499 or 1 or 100 or 500, the animation is exactly the same, the whole bar "Animation Sequence" doesn't change anything. I can share you screen and go in game to show you what i mean.

**Comment by InfusOnWoW** [comment]
No, the animation sequence changes between e.g. "Walking", "Running", "Idle" etc animations. Not every model supports that, in fact for most models it has no effect.

**Comment by Hristiyan-Ivanov** [comment]
Oh so the model i was using for 3 years now, was basically not working properly (but was pretty cool). And now it is working as intended... Thats really sad, i guess i will play with 3.6.1-4 till the end of the Shadowlands...
