### ISSUE TITLE
Health condition is incorrectly influenced by Health trigger for dead targets

### ISSUE THREAD

**Issue by ntowle** [WeakAuras/WeakAuras2#3286]
### Description

Health conditions don't seem to work properly when the trigger they reference also checks Health.

This is affecting my Shadow Word: Death WeakAura which I only want to glow if I'm not targeting a dead target. Simplified repro below....

### WeakAuras Version

WeakAuras 3.7.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No errors.

### Reproduction Steps

I created a test Icon WeakAura which is supposed to glow when my target is dead.

There is only one trigger:

- Player/Unit Info - Health. Set the trigger condition Health != 0 for this test.

Use a custom function for activation:

`function()
return true
end`

Create one condition:

If Trigger 1 Health = 0
Then Glow Visibility true

Expected: Aura should glow when I target a dead target
Actual: Aura never glows.

If you uncheck the Health != 0 line on the trigger, then the condition starts working.

A second strange thing I noticed is that even though the trigger function for activation is just "return true", it won't activate until you target something with Health != 0. Once you do that however, it will remain active indefinitely. I'd expect to always see the icon with this activation function.

### Export String

!WA:2!DrvqpUrnuyIcOQoikQJkvLviu0IufTarBlILt7HDstylk0nYZuyriuINXVzSzDShS9KSPhQuZjoXH9NqoZP8ty)fmkcXpGEGFaR4ha2Esks4dzE2(798779(EP1GWPHKqYV9jRyzsrSSsLbTqzsUu9TTTl1ItZZ1GP1ASiJkvJKmHjTx)NL0hTjtk5e5Cr8Cwjm5QDB7tkaQcNzysH(qK2GvMGiMGzcsZTF00GLgfROau6F)(QTM)DKzrjevzHvgwPHX4uTuLEcG5FNKatUMATm0XYsqHns1(V8Ox)FW8qqWmWMDN4bIe4PGo416Qu)XJuqo7cu8O(dhw)(P2KQamPnbn8GL6sGZFkrhS0fuxwm5nUgxLBDD94EhhNmoo5yuYkhOgFNSIaPwaj2SxDs)HJg88Hxwj2YQG1eM(xQe2IXminRsBKtldB(M0azOSGLv(X5EqsXN(GGo2LcmvkrhJQccabP82yFi26JJU)XBDTTxakbM)92kP11F66ZbO8ylvYmiSny0lXc2uNL4W6BoO(wrcPaUcWAi2OarHHEJnKkLhXyx9xPbRoGOx6W4Ou9dJMIzcRV1pS(ZUr9Nx)f1DTMV7))eBzqJnUyb0v2khckC9)9(RnfC58bk4xRar2IrV9bDF8xvFlLfI7I1UFoBRiBPBJ7v3KwzmsXPZafhVyL74H(09d84)XT4V0TP3BeRxz7kFZUtOrUlPEiXzyo02Nijuw25cqRB7VziZAFB)dejveqrTscwb18QiUetgy1jCRc4UOPvCdlaLXXA9DR7fe5QYngSxaoJvkpJDPFKByAdUYyNyoT0pheOUyhj3nNqDAJsl)EQf99U5XNf9cPCAR15kRY12FWgC7vgz2SMU79An(F2Nrk)ihf1DMtbR8WRI70Oe7CuNdsTHkNveGW8skU91ntTdCr0LyPX9q97)SY7SlhsGlmpHPXPCGqFCfJS(jOYNtGKF4ItLkMW92afnNrm0xvFYKvo1bZZO9oeLrHSZhu)ETxodRyUGu)HOzyEfeEW(YY9p6OuotCUn0Qmkwua69UF9ppzzPYnfBw40jDFuxVoGjYLQgTAWLAGN7)RM63juJ(YUFD3hfo7pp7F)d

**Comment by InfusOnWoW** [comment]
If your trigger contains a check for  Health != 0 then the trigger contains no information if the health is 0, and no condition can ever work on no information.

**Comment by ntowle** [comment]
@InfusOnWoW So conditions based on a trigger cannot ever contradict that trigger or they face undefined behavior? Is this documented anywhere?

And if I wish to, for example, show a WeakAura when I have a living target (t1 Health !=0) or if I'm in combat (t2), then I need a third t3 Health trigger to add my glow effect for when my target has <20% but >1 HP instead of reusing t1?

Thanks for the response.
