### ISSUE TITLE
Swing Timer resets on extra attacks in raid with DeadlyBossMods enabled

### ISSUE THREAD

**Issue by Lemonism** [WeakAuras/WeakAuras2#3289]
### Description

 Based on discussion in the TBC warrior discord we think there still may be an issue with sword spec extra attacks that occur during the timer causing it to reset. I have recorded evidence of it properly NOT resetting the swing timer while hitting a mob in the open world, but also have recorded instances of it resetting in raid environments on the latest version of WeakAuras (3.7.1)

Example of it working in open world: https://www.twitch.tv/lemonism/clip/BenevolentSmellyDoveHassanChop-A1JpDDsaJU8YwcJ7?filter=clips&range=30d&sort=time
two hamstrings proc sword spec extra attacks and the swing timer handles them properly

Examples of it resetting in raid: 
https://www.twitch.tv/lemonism/clip/CrypticSinglePorpoiseWutFace-3JyrvOXmxsr7LsB5?filter=clips&range=30d&sort=time
Mortal Strike triggers sword spec extra attack and swing timer resets, goes back to normal after the next swing

https://clips.twitch.tv/ProudSincereWebFunRun-228jivHYHe5BBkeQ
same here

I've found clips of the same happening to warriors using different swing timer weakauras from the past 2 weeks as well, and seeing as how the extra attack logic in GenericTrigger.lua hasn't changed since the original fix on May 27th I'm assuming that their versions have the "fixed" logic

I tested with no addons enabled except WeakAuras, and the swing timer works properly (doesn't reset), and with both WeakAuras and DBM enabled in a raid environment, and the swing timer breaks (resets on extra attack).

### WeakAuras Version

3.7.1

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Enter a raid
2. Enable swing timer weakaura
3. Enable DBM addon
4. Proc an extra attack in the middle of a swing (ie Sword Spec for warrior)
5. Swing timer resets when it shouldn't, then returns to normal after the next auto

**Comment by InfusOnWoW** [comment]
You did not include the auras that are visible in these clips.

Additionally the Response to "Tested with only WeakAuras" conflicts with your description.

And you did not clarify what the relevance of the enabled DBM addon is.

**Comment by InfusOnWoW** [comment]
Additionally assuming that other people are using a certain weakauras version is rather bold.

We need a much more detailed and better problem description.

**Comment by Lemonism** [comment]
> Additionally assuming that other people are using a certain weakauras version is rather bold.
> 
> We need a much more detailed and better problem description.

Can you elaborate on what more details need to be provided so I can help get them for you? 
The assumption from others doesn't affect the evidence I've found myself using the latest version of WeakAuras. 

> Additionally the Response to "Tested with only WeakAuras" conflicts with your description.
The description explains that it was tested with only WeakAuras enabled, where it works properly, and reproduced by only enabling DBM along with WeakAuras.

> And you did not clarify what the relevance of the enabled DBM addon is.
Simply enabling the addon while in a raid instance is what causes the bug to start appearing

> You did not include the auras that are visible in these clips.
https://wago.io/RV2EmBsDn here is the swing timer used in the provided clips

**Comment by InfusOnWoW** [comment]
Ideally we prefer a reproducable example, a way to reliably trigger this bug.

If that's not possible, then we need a clear explanation on what circumstances trigger this bug. A video does not contain enough information, because we can't see what combat log events are processed by WeakAuras.

Enabling DBM is very very unlikely to have anything to do with this bug. You might want to try asking in the DBM discord for help though.

Also the aura you have shared has a total of 6 triggers. That makes it much more harder to figure out how to map any behaviour back to a trigger. You should try to minimize the aura's triggers to a minimum.

And lastly, do note that the World of Warcraft api for swing timers is poor and not everything is properly exposed to addon authors.
