### ISSUE TITLE
Dynamic Conditions Taking alot of Resources

### ISSUE THREAD

**Issue by skjetne** [WeakAuras/WeakAuras2#3290]
### Description

Did some profiling, and posted it on the WA Discord. And it seems like i have some WA's that are very simple but require a lot of resources - seemingly due to conditions. 

The report is here; https://pastebin.com/Z2wJSMT5 (this is from The Eye Heroic)
The Weakaura's in question are here; https://wago.io/VlcdcATDn

Start of thread on discord is [here](https://discord.com/channels/172440238717665280/218084462523711489/885241026053296188)

I do not have ElvUI installed.

### WeakAuras Version

3.7.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create WA icon with Spell(cooldown) as trigger. Show always. No glows or text, default cooldown.
2. Add Condition "insufficient resources" or "spell usable" = true, and color change (property change)

### Screenshots

Example of Eyebeam WA.
Display;
![bilde](https://user-images.githubusercontent.com/17202764/132585212-3ca9558e-70c5-4ced-b927-62bac2e77e64.png)
Trigger;
![bilde](https://user-images.githubusercontent.com/17202764/132585154-b2b955bd-5775-460c-b8ce-f37d0a1dca07.png)
Conditions;
![bilde](https://user-images.githubusercontent.com/17202764/132585239-07e71b36-b354-43b0-86ff-701cbfd309ca.png)

(note. Blade Dance, Eyebeeeeem and Chaos Nova are the only WA's with the trigger "insufficient resources"

**Comment by InfusOnWoW** [comment]
There's nothing strange going on. I did check that the dynamic conditions are checked as often as intended and they are.

Maybe it helps to understand that the "Insufficient Resources" need to be checked every time you gain energy, which is a lot more often than the cooldown state changes and thus it's not suprising that it takes the most time.
