### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by LootFever** [WeakAuras/WeakAuras2#3299]
**Is your feature request related to a problem? Please describe.**
Not really, but sometimes people import an aura with a font they do not have wich causes the font dropdown to stay empty and the weakaura to default to Fritz Quadrata TT (?)

**Describe the solution you'd like**
I would love to be able to set a default font myself. Outside of any aura.

**Describe alternatives you've considered**
Messing with the lua to set a different default font.

**Additional context**
This is to be seen as a qualilty of life improvement and with a low priority.

**Comment by Stanzilla** [comment]
That is part of https://github.com/WeakAuras/WeakAuras2/issues/983 covered by https://github.com/WeakAuras/WeakAuras2/pull/2948 and also the alternative you mentioned is currently already possible here https://github.com/WeakAuras/WeakAuras2/blob/main/WeakAuras/DefaultOptions.lua
