### ISSUE TITLE
Unable to retreive current equiped Arrows

### ISSUE THREAD

**Issue by DavidBabel** [WeakAuras/WeakAuras2#3301]
### Description

I saw this subject open in the past : https://github.com/WeakAuras/WeakAuras2/issues/1762

But there is currently no way to retreive the name of the current arrow equiped.

### WeakAuras Version

last

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create this : 
2. 
![image](https://user-images.githubusercontent.com/5599375/133927324-e08786ac-4fa9-4821-bfe0-e6c3aada1d81.png)

**Comment by mrbuds** [comment]
AS mentioned in the ticket you linked the "Cooldown Progress (Equipment Slot)" was updated to support amno
