### ISSUE TITLE
Looking for Text Aura who displays Shield Block VALUE (not %) - TBC classic Tank Warrior

### ISSUE THREAD

**Issue by Kelineya** [WeakAuras/WeakAuras2#3303]
Hello Mates! 
I need some help with my weakauras. 
I tryed almost everything, but i cant figure out a solution. May be you are smarter than me. 

I would love to have a Text Aura who displays me my current Shield block VALUE (Warrior Tank). 

I already looked in the section "Charakter Stats", but there is only Block percentage located - unfortunately not the Block value, wich variates with strength procc, trinket usage, etc.

Is there a way to do that? Thank you in advance for your help.    

*Sorry for my bad english - this is not my native language!

**Comment by emptyrivers** [comment]
Hi, we don't do support or requests on this issue tracker. Head over to https://discord.gg/wa2 for that sort of thing

**Comment by Kelineya** [comment]
Hi,

sorry, a Mod on the Weakauras Discord Server gave me a link to that page
where i posted my issue and told me THAT is the right place for that.

So now you send me back to discord? ;-)

Am Mo., 20. Sept. 2021 um 21:21 Uhr schrieb Allen Faure <
***@***.***>:

**Comment by emptyrivers** [comment]
Ah, a case of ping pong. Apologies for the confusion.

**Comment by Kelineya** [comment]
Your invitation link is invalid =(

Am Mo., 20. Sept. 2021 um 21:21 Uhr schrieb Allen Faure <
***@***.***>:

**Comment by Kelineya** [comment]
Thank you ;-)

Am Mo., 20. Sept. 2021 um 21:25 Uhr schrieb Allen Faure <
***@***.***>:

**Comment by Kelineya** [comment]
Absolutely zero Ideas? 

=(

If HERE nobody can help me, then nowhere :-(

**Comment by InfusOnWoW** [comment]
WeakAuras currently has no way to display the shield block value. You were sent here, because it's probably a good idea to add it. And this is the right forum to ask for new features.

It'll probably be added in a future version of WeakAuras.
