### ISSUE TITLE
raidMark bugged when changing targets

### ISSUE THREAD

**Issue by WANoob** [WeakAuras/WeakAuras2#3304]
### Description

The raidMark trigger replacement is keeping the same raid mark after switching from the first target selected. Also when you select a target without a raidmark first, then even after selecting one with a raidmark it will show no mark. (Same whether you tab or click to change targets)

I have tried forcing it to only show on your target using another trigger and requiring both for activation, but that didn't change anything, leading me to believe it is bugged.

My only total guess as to a possible cause is something to do with the raidMark feature being an option under buff/debuff auras, despite it not really being related to buffs/debuffs, potentially causing this issue of being triggered correctly.

EDIT: It seems that the issue is there is no default trigger that updates the raid target marker state. Feel free to close this but I will leave it as I have seen 1 or 2 cases of people having the same issue. It feels like there's a disconnect here in that it can show it but not update it properly by default.

.

### WeakAuras Version

3.7.1

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Have text WA with raidMark trigger replacement. Trigger-aura. Unit-target, Aura-Buff. Add raid mark info-check. Show-always. (aura attached in description above)
2. Click on a target and assign a raidmark.
3. Change targets (directly without clearing targets first)
4. BUG-> raidmark stays when changing targets, instead of showing the correct mark on the new target.

### Export String

!WA:2!1rvZoUrrqymwrGgqkHLOvGGdR4VliTszJu4eh8ygRaYzxtpoz3io4TNPRz6oB7U70DpRTZTyXboWP9rWpcZJqoZHrw8eKd8aSpbu9mEbekXxMAQPR(RQVVVY9gT389y7X(T7B1vEPqbXhRvWgrUwLQRS5WN)oMVIjCgjD1uyPFwH2oN6NDVdTub7ru7f7YeRW6i5AP2(t9XF1)NIQ)6)942vNuu4a)V)U1uvoxBNOfkF2WKJNMq2MR1sMEHkDHWaNBo4nGSzMxmh29wpZDYRCE98WjESHr9abUeu(xtRWSuVi)ubZZJhGVAP5EHw5EaX5PwFuwHqjC8Oy8HpAT3kklbR74VXUl8V2446fdL4K54X(vgGqRS0JETRkRfL0QIcXY6zdhKoDw60bKPBrmZ5Glfl8evB9dKlORCn3o7HavITsfIwg2aLGFtiozPW5D8)5sNyb8sjPtsgpETZas5pYCrxx5GKL4eK2LHxNRNNHc2J0mOfNX6fGZtu05GlABbG9bzhPF(ggKH96uCeSpmz8KrpE8vvQDJzuqREwLczNlHJOsP5JOTXt7(EaH(Mp7nQfDbKGKWUgfsWQOYNGSis0)Y1xaGzaoc5EckfA(voqw0k4nFa2soQhPtpWJl0kpzifNNninqGYGofLXbrj3)YyPMYgHCMePN9jZRKEruC4E3V57Ji5sQZfIIDIxaHG1l0w2PwQz9P3eeqif)8pV1XPOf7SoBy)xDJLlHvc8AHQBIq8338jIsL2cNyATnjbXjXA1w35BW9dMOnD0gBB7g42ypsoXHLNZ3Igq0DVR2OJQeSAtv5tkF(zpn)Il21fpTRlWLSV8TB1nwixei0(x3TYmYIACaVS0HKKKJRlcjs9ixs7h)cTEEp7ZW1crXQ4XjJMUXRZVSttE)j7)fcM5otB9FhemiheCiMV9TJpBf6Pe5Z8ClUhGS1kcvA40(KfHDRxAU7nCyO4Fq4OzsGXZqAOqugzfQa4a3USBA)J(1Dt)W2)TOxVE93GoEG1UQ(RF46BUo(vuLOtmEqZhp6va1fMsqv65VxZN2CRTSG)b)8SWYjIrqwCRdNlqpn3kEovOg1WApDd0u0uIpV7)pZEoY9p87o8E7D5FE2Fd

**Comment by InfusOnWoW** [comment]
I can't reproduce that on retail with your aura, and I doubt that there's anything flavor specific in this.

On switching targets we call GetRaidTargetIndex to get the new unit's mark.
