### ISSUE TITLE
Sword spec resetting swing timer(can reliably reproduce on my end)

### ISSUE THREAD

**Issue by Mizers** [WeakAuras/WeakAuras2#3308]
### Description

It's been talked about before but the issue is Sword procs making the swing timer reset throwing off slam timings.

Tried:
Reinstalling Weakauras
Disabling all other Addons
Deleting Cache and removing current Interface/WTF
Reinstalling WoW
Using ret paladin swing timer fix

What I've found is that it only happens for me directly after a slam with MS or WW. So Auto Attack - Slam - WW - Auto Attack. Initially I thought it wasn't an issue on the ptr because I couldn't make it happen against the target dummies in Shattrah. However for live I was testing in Scholo so to make sure that wasn't causing it I went to Stratholme on the PTR and the issue was there.

### WeakAuras Version

3.7.1

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Use a Weakaura swing timer(Can just make a basic one. Tried a bunch of different ones and making a basic one and issue persists for all of them)
2. Go into a dungeon
3. Perform a Whirlwind or Mortal Strike immediately after a slam
4. Proc sword specialization off the WW or MS(there's a special animation for the proc so it's easy to watch for it while also watching swing timer placed in center of screen). I think the mob may need to survive the WW/MS but not sure.

**Comment by mrbuds** [comment]
Hi, we don't support custom fix made by who knows, only last version we distribute, and we keep all swing timer discussion in #3234

**Comment by Mizers** [comment]
The custom fix was a last ditch effort and wasn't used with any of the other steps.  I thought that was obvious.
