### ISSUE TITLE
BigWigs Timer Pattern Matching doesnt work

### ISSUE THREAD

**Issue by Lardeck** [WeakAuras/WeakAuras2#331]
What steps will reproduce the problem?
Create WA:
1)Status
2)BigWigs Timer
3) Message -> Matches (Pattern)
4) "%a+: %d"
5) Create BW Localbar with: "/localbar 10 5

What is the expected output? What do you see instead?
The WA should trigger.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes

What version of WeakAuras are you using?
2.5.2

Was it working in a previous version? If yes, which was the last good one?
I dont know.

Please provide any additional information below.

In line 2233 in the file "GenericTrigger.lua" you have to add one **not**.
You change:
`if (v.text == nil or v.text:match(text)) then`
to
`if (v.text == nil or not v.text:match(text)) then`

**Comment by InfusOnWoW** [comment]
Thanks for the the bug report with the correct fix.
