### ISSUE TITLE
Instant Disconnects after login, only on 1 toon

### ISSUE THREAD

**Issue by codedbymatt** [WeakAuras/WeakAuras2#3311]
### Description

Anytime i login to WoW have to disable all the weakaura addons then login, after logged in, i can enable and reload, as i have a way to login about 60-70% of the time it works, sometimes i have had to do character stuck service on battle.net then login turn off weakauras again and reloging in, i have 6 toons that i play regularly its only specificlly an issue on one toon. other 5 have never had an issue.

### WeakAuras Version

Weakauras 3.7.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

as soon as i click login and i get into the world it just disconnects me instantly, i cannot use the addon

### Reproduction Steps

as soon as i click login and i get into the world it just disconnects me instantly,

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/7230398/WeakAuras.zip)

**Comment by mrbuds** [comment]
> I'm going to need your saved variables to investigate this. Navigate to World of Warcraft\_retail_\WTF\Account\<Account #>\SavedVariables\, find the WeakAuras.lua and WeakAurasArchive.lua files, and upload them here.

**Comment by codedbymatt** [comment]
i uploaded the zip is that not what you needed?

**Comment by mrbuds** [comment]
Yes indeed sorry

> its only specificlly an issue on one toon

which one ?

**Comment by codedbymatt** [comment]
[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/7230437/SavedVariables.zip)

**Comment by codedbymatt** [comment]
thats the whole account savedvariables

**Comment by codedbymatt** [comment]
[SavedVariablesMaddogg.zip](https://github.com/WeakAuras/WeakAuras2/files/7230438/SavedVariablesMaddogg.zip)

**Comment by codedbymatt** [comment]
that is the SavedVariables for the specific toon inside the account under the toons name

**Comment by codedbymatt** [comment]
> Yes indeed sorry
> 
> > its only specificlly an issue on one toon
> 
> which one ?

its on Maddogg

**Comment by InfusOnWoW** [comment]
I can't reproduce the issue at all. Does the issue also happen with all other addons disabled?

Also can you install buggraber and bugsack as the issue template asked for?

**Comment by codedbymatt** [comment]
No, only when weakauras is enabled

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by codedbymatt** [comment]
I reinstalled all my actual addons and deleted the addons folder, and everything seems to be okay, I just had to manually install every addon through WoWUP instead of tukui and curseforge.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
