### ISSUE TITLE
Timed duration info untriggers at the timer completion

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#334]
Currently if I make a custom trigger that fires on an event and starts a "timed" duration info, the Aura will untrigger at the end of the timer. This makes sense of course but there are quite a lot of circumstances where you want a timer to run but don't want the Aura to automatically hide at the end of it. Basically it's the difference between making a custom "Always" trigger and a custom "On CD" trigger. 

Could an option be added to get around this? I would suggest a couple of ideas but I guess there's already a way that default triggers handle this so there's probably a way this would work already in place in some way.

**Comment by InfusOnWoW** [comment]
Well, if you don't want the timed hide on a event trigger, you need a custom untrigger. The custom duration function to return the wanted duration seems trivial enough to me, that adding a option doesn't seem necessary to me.
