### ISSUE TITLE
Memory leak on Mouse-Related WA's

### ISSUE THREAD

**Issue by Huijiro** [WeakAuras/WeakAuras2#3342]
### Description

I see there's a Memory leak issue happening whenever there's an loaded mouse anchored WA, i've tested with multiple WA, but it seems the issue is with the addon itself.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Just load any cursor related WA, you can see the addon memory usage steadly increasing until the game crashes

**Comment by mrbuds** [comment]
Hi thanks for the report, could you include the aura you use to reproduce this issue ?

**Comment by mrbuds** [comment]
Closing this until an example aura is included

**Comment by InfusOnWoW** [comment]
I briefly tried reproducing that, and even with 30 icons attached to the cursor, no memory usage at all.
