### ISSUE TITLE
Support for Kyrian Rogue legendary not working as attended

### ISSUE THREAD

**Issue by Stealthiii** [WeakAuras/WeakAuras2#3343]
### Description

Recently in the latest version of WA 3.7.3, there was a fix for the Kyrian legendary only being able to show one anima charged combo point but since the update, it appears to not show any at all. Even with or without the legendary.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Not getting any Lua error pop ups

### Reproduction Steps

Using the ability Echoing Reprimand does not show the Anima charged combo points overlay, with or without the legendary equipped

### Screenshots

![WoWScrnShot_110321_190521](https://user-images.githubusercontent.com/93672777/140167449-ba4984df-0d85-43ae-918f-3da702278466.jpg)
![WoWScrnShot_110321_190524](https://user-images.githubusercontent.com/93672777/140167461-c95cf6b1-d210-407c-bb31-03439433e939.jpg)
![WoWScrnShot_110321_190505](https://user-images.githubusercontent.com/93672777/140167504-c91b7859-ca32-40e2-b695-862cc7e3f1ac.jpg)
)

### Export String

!WA:2!LIrtVT1XrXq56AwGAjfBHuxxGxOluPADySOCOduHQcjfLOSLLyEu2Y2XnKlFVL8TrpU7R7UpAjvKl8KrpQ2Md9Oo0lnhk4XgKwaHERxwiyGExnO)am6LERZUp(PSrqt7kqYDNDMzNV2zMvXwBMwZ4oJ7ZFVoS2yUp6aXDVB8yLw53pREC1sR8p(xR)hNyIjohW)EIp4BeWtebi(EB3OHalFuStrHspgF7ajHrf)4plV8GaSnHgek5Hc8QyHJN9ZiUsV4CxCduOVm4k2SMHyRt(cRYCsle)aR8iEM9Whe8Mo(iHawTfQfUmskXC6rTaAi(ek2RUpM2u6D18uy7GzlOrwtRLgDR(4dh7Mg88AOMSonSvDmx9TV9LvFlpvIoTi0D1IJ67E69jusRWwwrRVyC(brA1NF5UiQdOvLzeQSEHIBTtr7tnQTntI0AASGPhB99zU485EWoBNjK7)gCKJXCK1wirCzI8WbjN7ixwvNqHK1Qw9OF3FY2ncPgCTqHCuvmT9sBa4MA(ewWWN5G8TCK7BTSLa73inh3eWnnI7uWWGcmQeVV0GmPHfLjnyl9Wudm9iI8F5NoaWxhNamb8nOIPUMFhvs65D6jolTowwyeh2ysnyDWuPT5ya83fJ2lhOII0arrqt1NDZpQ8pgDJPibCWBKYi9e3BAL0Hf67AOPbH6ATBULsEtRX5PEWXYqo9vvjqptFoHC0LdWPFatFFGdJ2G0Ca4b4X7ZLrSVdpTHEN0Em2Ey3X1nnmb2jKJ1bePoVSbABfS0CEGo2pMjv1BAzUAnuzhXP3tewQsF7TH8uTq7NAu1QplgYdWkn)Orp9f4LTGR04bgs9NeVA47xxmHX5OHk0rKj3fX5egh0OKLr(ixcvpTuiejAaAsty2LtWcPE2Qye4jUhL00dwByDYkEOwidP3h10GpWy4a3ZaIrn)UkpK4gXHwG427q(0ZlCrUpSJmvMBA9a4MOrxsLmasNc43Zk1GXTi30sNfYIqTibicxKAO2nVLlBGfe889y9YgkwQPiSEQKwAHj58lfgeG5PMF8WHHXTJfZ9AYoUeilTqYuAopMlCC)05YUuhUXqeEj6i5KMnXCXhphV30N)9SJoM7V9w37eixAvHh7zfycP3zGGJBdbLLHWuY(2vkxCZn1PBRAOW7Oa2ZWCDbGlfmTgCtmfZjovagSnTMTwgfjovVZamRDKia77R1OyNog(Njm)uGX8DzpJQMmFii7NPPgvxW4115CRnqMQe2aKPUvlKRYovRSto7D6OrvttnBdg2L1hAWv0G54FriHJnq2bedVGRnqv9q8My3cSw1zMcaIANYXi)kdLtdQ9xwRJz6gUIeDCbZS(6WmlWdPMdnpuFKPwOEuaKXyjHYd7v7yxCDqK1hoVuXnlV2datjTNtiXCQB8pvtQwq9ZuROshtT8mlOYEYoiOaOec)12JfuFGAPyQFAT6sd45Qli0M(4PTnfmN9Y1u)KAhBoqZ(1uVR6wQC1u5vfuRMORlr8jMBVTXzq0dcMgzMVtKeOnUF(ehtGiVQomFg)UXHXlj6RnuK)dHygqp)OJ0HNgRKAwdYvyHCh81NOtDeVGHUsR8vxXmkTYF77RhxlECq5fiP2yH9gTFIhh7yWFgLUs8RMvnzxDGlWQQWNNp1lLeN9QQ7cWTAlqaZKB1vvtYbs0BCIz39J4uSiCh5CcMs7kG7keNQr9ru7mdosp4BkwiIFSzDK6glwS4DnwpOSiKx2l4nn7coshClWEAKGJYjlJbfMkJo9EihKAdTHQbG6tlGesWXaxBF6d24DgU6DQO17iYAteeqT6jqdoIKzUv0(9AmjwxZQiPF5OfTiCoJ7DQzbVF7jpFk1dv7crqps94yQN4P(OAQNgx9ZnQL6J9uvv1uivDLtnLBYBFlfoMQXYQMEkVVH0M9)dAF))hP1t5E67Vy6fhmgLnTpTodA1KxLzSzX7VmQLUmqGu3EqeKdXXpP3IHE9Z6bPVtPp6yx4EXcwLj7J9vtEee1fTXZNjdkG4X1Xd(v3pw3Ojcz1qXhgmTo6ncsFg2dZdV0jrtAq8XB4wFHSzVZIlCCeSaOoxWBBYSiExOlnefBYzcSfcMR64bfet3kZWZsEqSE89GlmekF)VAQodIkgb(HJSqUFSxoukr(bEOYXVv67ax)0kjkIVJq8bJs8HXoBiXo(KGA19W66Ztdm1zVMCwi1TFQG)A)ubNFs88(mKBB181oZumbCxU6CSoZPw)ftPkn7lMQMATzvLsWpKrbZL4nu)qypB7Tx)bfbW51ipRzc4w1toZKyjVoBHoBMA3GPG7Z5C)eOHxSl29(O99ocbpbWyCYQU(AqngkW8tWibUIKBUMDXt7NuVQUEfh6sJrDfD04OtERokFleHc0Qos9RVO63O(TQpdM(2NhcVxMPRpbKjYelUghkFy(k4hnO)4LIEvd84Ox3RKo2OtMg3UAgOJMUnY(Hp5URDpEP2brjs3jkdKQ(51wc174Owcn1C6Ly9LJikA41RuWUyXTSnrbXpYK)xqCX22BSEPDuRuRR5ukrCDXu7Tk(WI29Gy85lZ7LbStojN5qKh8Y(pgTNGDx1Fi6V8hYyTIzBi27yjZPDunL3kw1)DsI7jMcWwrvG72Jj6WlVUn0cl4Fqs0fux82xUEu7rZP(oQlPM52xoYivyqvl4DdAEJ9YRvhVUmODsA0vIJlTT9gpz7T2j3MhR9RKONXoNnCbZzVSQBCHoTrCccU2Mx3CGDBKFioo3XdrBIfpzo1xwRtaNfy6Mzg46s6SPhnLoGWPlKnD2(J7O(lbxrJwM0JNRxJ4IJLtRhIl(QiM89Uv)DV9RHnzFDN379ki(NwtDJRpH6l6g9yuJgNKfe8dkVzUhx0Uk0ExHnYT5gpj3oBS9wvluk3wRxCv1xg87g8aKbVCd66h6pYHG8jhII2s3VBMXBR10cvoDBggC2oYPAI9wcIO6)ybSVa)Ffn6gf7ttuNUQ)81s0LqJAkgqF2G3I0KY44E)dkkQ7jROUIPO2mc7ftFN0lot7x8O)Z

**Comment by durandal42** [comment]
I poked around with trying to get charged combo point conditions to work around, before I found this bug.

The only really weird observation I can contribute is that conditions like:
```
Any of:
1) Charged Combo Point 1 = 3
2) Charged Combo Point 1 != 3
```
... never fire, despite my intuition that =3 and !=3 should cover all possible values.

But conditions like:
```
Any of:
1) Charged Combo Point 1 = 3
2) Charged Combo Point 1 != 3
3) Always True

```
... always fire.

I have not been able to find any example of a condition on Charged Combo Point values from a trigger returning true.

**Comment by durandal42** [comment]
Confirmed by applying that change locally: everything works as expected now. Thanks!

**Comment by durandal42** [comment]
WeakAuras was updated 4 days ago ( https://www.curseforge.com/wow/addons/weakauras-2 ) but the latest update does not include the fix from November 7th. When is this fix expected to be published in the live version of WA?

**Comment by Stealthiii** [comment]
From what i can see there has not been and actualy Live release of WA since 11/2/2021 but only alpha releases.
