### ISSUE TITLE
Add Target Unit of spellcast trigger to use it for Internal glow external element features

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#3346]
**Is your feature request related to a problem? Please describe.**
Whenever you want to highlight the cast target of a spell you have to write a custom tsu to expose the unit as state.unit something along the lines of https://wago.io/ejdWa0FTy

**Describe the solution you'd like**
the inclusion of target into the cast trigger to expose it for anchoring either to have an option to set it instead of the "caster unit" aka the unit that is casting the spell or have it additionally with options to select it for anchoring etc

**Describe alternatives you've considered**

https://wago.io/ejdWa0FTy (can be improved ofc but sth like that)

**Additional context**

@Causese uses similar stuff in most of his packs and i think reloe aswell 

Edit: talked a bit to buds about this for reference https://discord.com/channels/172440238717665280/215496276609990656/906124240657465364 maybe just adding custom anchor function support for glow external element would be a better option

**Comment by mrbuds** [comment]
This can be achieve with a custom anchor function, it's exactly what this aura does https://wago.io/TargetedSpellsClassic
We also talked about ability to make "glow external element" use a custom unit too, i think that's too niche for something that can be done with a small TSU to get the `unit` field match the caster's target.
