### ISSUE TITLE
TBC: Group By Frame > Unit Frames misbehaving with Plexus

### ISSUE THREAD

**Issue by Jinnai** [WeakAuras/WeakAuras2#3347]
### Description

Weakauras sometimes fail to anchor to Plexus raidframes. Simple example given in reproduction steps.

But also with my normal UI that uses LunaUnitFrames (only for player & target frames - raid and party disabled) and Plexus for raid frames the provided example WeakAura initially anchors to the centor of the screen instead of to any raid frames. Opening and closing WeakAuras options sometimes anchors it to some random place on screen (fstack doesn't show any frame there). See attached screenshots.
After buffing Arcane Intellect and clicking it off the aura stops showing completely.

Sometimes I see it anchoring correctly to the Plexus raid frames and sometimes it anchors to the Luna Player/Target frames instead. In general it behaves very inconsistent.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No errors.

### Reproduction Steps

1. Enable only Plexus and WeakAuras
2. Make a raid with any character
3. Hide Blizzards default raid frames via the raid options flyout menu
4. Install the provided WeakAuras which simply tracks missing Arcane Intellect buffs on the raid
5. Nothing shows up
6. Reload / logout and back in / open+close WeakAuras menu
7. Still nothing shows up

### Screenshots

![image](https://user-images.githubusercontent.com/1058140/140590613-d52035a3-eaaf-4354-b03e-ff21394a9f57.png)

![image](https://user-images.githubusercontent.com/1058140/140590641-e1abea7b-98ec-4513-8b07-e9db3c1001ba.png)

### Export String

!WA:2!LzvZYnssryKelZoTNfK1cowmXakCW6iyG1ZA5D8mWfqTDlBniBRTvB7HDiqQ6UlPUg3QQMQQ2Y2CtXeeZjoOhH(naDdo6NGkCS8c4hbFHRKv1T1S7YfP6NSQkZV87lZU0WAJRfwt4U1gpFJTQf(UxWV8OHdfy5V57XphZfeg9HZj0Hm(yKeMSsYNqgrzC8rj6PcNZXuPdNZ4Ib3HObrmEloAm27YeSFVDCDCoCgIsYp822JreAlBjSPnLrX3eMYn70xVexGdy0qXumsyUa1sxRh2tYX0rYOh4kKiUSLYsTK6rQps9dH))rpWFiHserF3LDJjJjYLMjWXd7YiuPRB7923Rrkpo5NfjLjIF3tF6e0i2ge2tF(ROn(S9AD1vp9lMH4bDmV3BxjlivizJ3JZMuo5JZN00eKDX8JPez5KQPc83APbZ9z8qmFhwmJ)YsLkvjlFbNWry(M17sUahZVihLR4R9G27oBHdyhIfbLVbLkHRSaKTMcpshD4e1iLeo)x5)MlCEtRDpFRO5bS40X0EjOaCLBqFthz2Xh22RLBZdCMoItc1a6AU76dq8qYiRmjlOib)HDxPWf7rUc)bzIuFx8iZdVgjmPQlIew3Kvf19WcjhsdJGyPKRq)SLShb4JDhNwEzdtJJ3HWdIXd8ZVYOPCM0KJl5lWJHN0DZn(8n2628TTrbNfYzjjvTJjxDfIhw3JXILKexrakgx56C7YHRhothjNscLrlb37K8W2wW4s1sZhQDrGSGKOLY4Miqh0xhEjfnMeaEzAIphfssfV9rzAQgjhE55muC0DanbZPO4tYrMxZrbgt22g4yslvvl1YwZlGznPI7DuxDKBhZqHd5xbK62HIY2IeCWkUJtHiXYwaW6kQdSCdIrcX6WiFbHokg731TTtppFjePuP2KzqMUVXmBjpf7IIb5M)ooh654ovYjACxS66ZsPftS4fd(7tH3mogEDlLLlcewnStbN2pjgDjG6yTs1FFmkwgLfI9thouJo89D60T1XDUfY6gt6bBqUyE)DA2ZRFpVMUEl2QlhdB52RRtNoUunFWQGS3MQjZ3cykWnOYwaSX4(Un3T9X9UXVihNRiQuPs3kF(gpBMjF0goI)MB9SF7wnQD(x)QAbR(UDH1LXekK0p2Rt7dDaVvGK6kf4Omj(c5MgOFU9rEEhDGrvR(bQhC3zyCstnWlD1eUOBfssWzxUBrnMi7rXSjrQTvp)gZT0IbrlKA(PQFnibCNOPvpoPAUm3dS44Kq4n9tn)PCE916J1WHI8JXHr2GgLnWMarWa1ow3ea82q2eAVjKe8axZtS2Nk4eQwNHJuV8Dv55z6g6uDwibq6aGICPEkhPXDSWmEyoVtpwR97RJQbQJ0uhvx7dAUNdCTgauBInqtnem1FSSQtUrvmmjkK34r2CwSz)BlUR44ZOGNgPCnN6qdZl58K3ZdvN(pwx9kl1F6DpEU(qYCrjOqmv)BtpNiiamePgOqz5lUlgfgPD3D083O70NlNOLVaqpg7d51dqYGiSiteXM0Hnrxrbm9qGpn4AnV14GKqXtCB88TFXMWVV4l2unC1znLG8Am4H6R25caJ6Lt5J0b2EA4OFadKgrM7ENyWCXGKAfUhraPkkqpGKN6pdGgjC69nGQTzMbod0Nza0k51ZtYlJEaleNLsHSJ5Kz64PhC7hrVwy(RjKQauoLA0iUsYyC4mDCyuipjPAtEaIIR3gQTehdxsYYfRyZjqGcvtWQqfw9vR(jL)VDv)fv)caTh06ks5Rcsw(Esabym91Y6fO59TDsQvqCZlh0HnIeuozzKX7kwuhlvMhseVjLAwVbIEzUKAH4SY0Hf6IpsvUK67VI6dgyRxkPAlo5Q6FzkkuxITUNN6d3w9Wt8t4yq9NHItIqDtJfyO773QzC1VBVz1Y)FR8XQtU(EfKUtz0SfAu1)mtlY6Xs5q3g1pVKAnRP3BBEfHgMkcQtuT2wT36(5ir5zHS(5dJuvxx9VkR(3rQLVFWtSu)cvDZZ0i)zGUD39(MDMEDQ)G6VL8JV)X0ffaAKr)py6eO03PCuY0tlgO2xDIgD1vC1MwR(nlUDnGUzMwHN3)6TpI)gW1idVu1W1aDvUvxqr)LsbglSBctTVIXgx62fyrRy0iHIAQU0yTpnjp6FFY7(NxxxvfR(9vYEF5S1SSuF2Qdl6OckL8pqbouXkya3twU3FnfXX1BbTYRFAebQ8znd6aKBtrB7(fY)b3umNz6px6(Bs3XRss1cMfvcF2Nw363(WET31XuhDZI6OdCdw495NOX34eQ)JFeMmks(4BxaLfyG6xo)zN9YV809)Qw8UjQFIAfvLhQtP)Vp

**Comment by mrbuds** [comment]
Thanks for the report, this is an issue for LibGetFrame, could you make a copy of this ticket at https://github.com/mrbuds/LibGetFrame/issues/new ?

To be able to test it i will need a copy of your wtf/account/account_name/savedvariables/Plexus.lua and the name of the profile you use (if it's not default)

I'll also need to know on which frame the aura is anchored too when it is in the middle of your screen, you can find it using the command `/fstack`, you can include a screenshot of what the tooltip show.

**Comment by mrbuds** [comment]
Issue tracked at https://github.com/mrbuds/LibGetFrame/issues/18
