### ISSUE TITLE
TBC: Pet's won't show in display / buff-list

### ISSUE THREAD

**Issue by KarrokDC** [WeakAuras/WeakAuras2#3348]
### Description

Hi,

I want to make a weak aura that shows all players and (hunter) pets in the raid that I (as a paladin) have not personally given a blessing to.

This currently works for players, but pets won't show.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

N/a

### Reproduction Steps

1. Load the export string WA
2. Group with at least one hunter as a Paladin player (wa only active for Paladin atm)
3. Check if hunter pet is on the list
3. Use a single blessing on the hunter, note that now that hunter should no longer show on the list
4. Use a single blessing on the hunter pet, note that even after buff expiration the pet won't show

### Last Good Version

n/a

### Export String

!WA:2!1zv3UTXXvyrX6QKfbfYmoQokjTBjQvSaCOT(ZwXig1CLiLzlnj7skjRAKYD2DhYDSwo7MzMvsuWO)qye4R5f9bG3v0Cf7lqGEcgiuGEVUP3RR7f9m7UKsobvqs7mND(57CoFFNZMzVCCZ1k8OcRLRxo3CUVDZHiMtvmTRW7nlCHDaZfZmqoh6YccdN3WNC6PiMRERGaFbj0(yu3GkBp83TXlQU5bVc5WoPENoCS4zF)F(38F)(zMjdRFQHNA)4)XFzMzMDmI64fWAeqOc7TkvRvjZW5J44IjMXSDPeH34KBERa)a2VntMmzn5Hih8nwnI5h(jEcri)X3)(QBVaj4(tV(7Vgd5iibu(dn5cetOz3HqjCpnd4HqBGGr62fZ4lUelD43oYfBh1PtR(Hy2ZkvTr5DRAiGjMOigA1b8qSVFfxU2f8iB8ryQOjSAYjJBVvXMTA3SvrZwMuup81wrdggwHzZgLQw1m2I9ZWiFHNreGc7qFuFmByenfcAJDc8J6rBQCX)Jnd5sI4V5dgarLQKEq0We5t6snQwQCldxm3jmxlWppeZ07eW0vONxyalqGuUEg2rGdcdMBeGhtCxv4qBqxgXv5J532CyxwquyfNa6TN9N8Vn8dqUDgcxwBhFeN7zlq(aKxWSxeKJ1yNgqXqaywZ4xVGCDndiO4KmGCkwnyKtexe0RzateUENiACs4UO7PBVSMo8ddlIyuDubh)4tt)REIU9KjAyQ752PKSKuE2SzBK9bf2y1iI74L33g9L3LW238agIs6HeypdoCvguy)MChaVzTb3PdPRMDcZXBuYZsUDXH3S53eHyy9Yr((677re4rS44IkGCMBFi9rCIdkx413gcunc4eLhmozAzcJlm9v5ILtp3MGJFJHjObw4dL3S85UaHrnPTI(W4yarUC5TLp9mmIJBkyXYQ5gOMPUz5tn6Hi0YYNlRPwMS(CYgWJC)qldvjV9jUcVpkfGQa9ZdCXdrChi6rODVaUnGYtfLbfqaZ2S42v2TjGBKIIL5SeyNigFFBoUhWsmxPWdkS6irGtkL59ASqEIByUNt4C4m1nrexDdf)Aih73jw0k1g3Hb8DWFqcu2lt0ZLvMuoLDZTmlvQ2LWkXmkYFVKt(LPk6ku4(ZAab7Jn2XSY2NJIeW2RhksOPG9yzqMrQOhjX6ycfi6jr6fcVnOfcy40TusjVkXybmU1OoqcElcZXhBLZzX3UkKsf(ek4372QALALgrGtTzqeZb)PZiVH8NkXAJDjCLISf(er(74KYKvZojZctPYj0yshDvvH2y6rfs4BVmpeH7rOO8FTUWdtJxM6h)aGwQR071GiJ(tUAJWge4ctEZ0n0(EQFvaew8oyrZ4cpGJF3vEWxU2MlpDHaiMES)PNOtj(V7nFn9w(x3kFHcQZSqH8p(bVwOdt3Vy7Tuk5yLM6uU7)hOD1vcumTjpH)KVxg57l1o3b6c4gCmT5XKqSv48xf62n0foj7O4hxa54av2ZjMdBueMAOaLL8w1ws(rVDXHkeKuefY1o(rU4gyb)IgXvk5fPUQPa3GwN633svzm2f8K5nJ1TYFH8xckGE2qYoThI14e4eRghh7zjWjUDtBhexy0p5cSKli)5J4EbhVLQIe3IbRqfb8cNxHQgiHIm3wnEGHpowCi)e5Noom5UusXrruuNoyhb2fKUFSux(RKlQfMlHTUnHdomn(1wxQaW18tRK2g8WxSv9NBuSv7Q13PDP9GMJT3Tw5kvHEKL2(E67ywF3gTnR3eM3E3gBxSvP7PxQ2w13v1fnPv090BuT4bWS4oRvQTt79RBwD7rPOaJCTmD8Wohk1Vi1jt9ol5NPfERR7UbG3HGAjJGEOU39ZVd)Zxw(RJ1lVkwwCeEvKVF4nrXJBL0mtfk(UzKOxE5HyCyrvNcHPs5AjRQQsgxwtvElTy3V)hzj3p0c0HMJeQIRqD)obuXOsNeYGSWXO(YVyozHfF7cH5eaTRn3dbeYxKuMlZWyBQ)n(oRmLwho)1w6vFHXfjwNwMB5Wpm2Y7sELrxgBf6VJtkj)xppPc4bPx6zXV)va3J0PVuBuCFzSsuyuRETsYBZG2YQ1Kc5KDNc55gfBZzstWSjUGYPL)TW8t9N2j1dBFLxLAr(03jsmbuNhB7yOe8(mu4G9thC(0tpUFKFAO5AFIMPzLDEwReF6icNydLwVAxQUGF25VJhKj8J)rOKofC2EysxpXYYv(w5QwmqgPuVlzReu(y5RLRVK81wgmOVJv8NKqbLbZtUM6JmKBUK8Foaokr)EiQC99mdHpXRV1Qcm1AK4yqc1VdWeTStgBnOJp(KyilFiSvwJIvHUI1KRVGDdZkLA2Ys(O4dEJzhm1DoBsvn1No4nyYmVj9juF3K9kRTXMpAv5pBwzz5rYVACRTBD4EBq24vpSO5vjpZJveKLHpFl0dLLnHt8DH3AYPQOfqPbeGrxp5bY)GXPbb9YyOiDwYxM2pwFs)44wX6FHEdKpsFsHiU(QdMKzL)D5FmRST0soxgPHgeGvD2XEY5bTNM8d1K50gDf39nFGSRM0BbjXs(1sTCh9VEX)7

**Comment by mrbuds** [comment]
My tests show the aura work with `include pets = pets only` but not with `include pets = players and pets`
