### ISSUE TITLE
TBC: Allow filtering on Include Pets option (to show Players + Hunter pets)

### ISSUE THREAD

**Issue by KarrokDC** [WeakAuras/WeakAuras2#3349]
**Is your feature request related to a problem? Please describe.**
Currently, when selecting Include Pets it also includes pets from non-hunter classes, ie warlocks)

**Describe the solution you'd like**
Perhaps a checkbox to select which of the pets within that option should be included (hunter, warlock, other?)

**Describe alternatives you've considered**
A very convoluted lua function that iterates over all raid pets, and determines whether its a hunter pet or not, then keeping a list of that and injecting that into some display

**Additional context**
Trying to make a "missing buffs" list where the caster of the buff has a list of all players and hunter pets that the player in question has not personally buffed yet.

**Comment by mrbuds** [comment]
You can disable the aura for pets in the load tab.

**Comment by mrbuds** [comment]
I'm not against but i wouldn't want to work on it, pull request welcome.

**Comment by KarrokDC** [comment]
Maybe to clarify: It is indeed to provide the option of what type of pets should be included.
