### ISSUE TITLE
Cooldown Progress triggers default to a blank "Show"

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#335]
Super minor thing:
I think this is a recent change but I'm not sure when it came in. 
All 3 of the Cooldown Progress triggers, when first selected, have "Show" ticked (can't actually be unticked so maybe isn't needed any more?) but nothing selected in the drop-down selection. I think it used to default to "On CD" but defaulting to "Always" would also be fine. 

I often use these triggers as a quick way to test something and keep on getting caught out by an Aura not showing and thinking it's the thing I'm testing when it's just that I didn't select anything in the trigger.

**Comment by InfusOnWoW** [comment]
Seems I broke that with the introduction of the same option for BuffTriggers...

**Comment by InfusOnWoW** [comment]
Should be fixed.
