### ISSUE TITLE
TTS option for conditional function

### ISSUE THREAD

**Issue by Saxayone** [WeakAuras/WeakAuras2#3351]
Currently the only option for TTS output is the action> on-show etc which is somewhat restrictive.
I was wondering if the same native wa functionality could be added to the conditional section since the only way possible is running a custom code that calls C_VoiceChat.SpeakText instead.

Also a secondary thing would be the possibility of controlling the volume of tts called from the native wa functionality since it seems to always use 100.

**Comment by InfusOnWoW** [comment]
You can use TTS via conditions in the same way as actions.

For volume control, at the moment there are no plans to add that.
