### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by Dasblade** [WeakAuras/WeakAuras2#3355]
### Description

My WA will not open by keyboard command or icon at all. need help 

### WeakAuras Version

WeakAuras-3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

open the game
selected my toon
clicked the icon
nothing happened
typed in both commands 
nothing happened

**Comment by InfusOnWoW** [comment]
You should have read the bug report template carefully, as almost certainly the section above "Lua Error" applies.
