### ISSUE TITLE
Leader detection

### ISSUE THREAD

**Issue by DemonfangArun** [WeakAuras/WeakAuras2#3356]
I humbly apologize for not using the template, but I feel this is better described without it.

Long story short, there are many WA's out there that auto-mark targets, and when using the group finder, there is nothing in place ingame (as of yet, I submitted a suggestion to fix this) to stop anyone in the group from placing markers all over. I would like to humbly request an addition be made to the core addon to check for group leader and if you're not disallow this behavior.

**Comment by mrbuds** [comment]
Weakauras doesn't have any options for putting marks, so auras doing it are all using custom code, nothing prevent them to make that check (with https://wowpedia.fandom.com/wiki/API_UnitIsGroupLeader).
I'm not against adding a load option for this, but that would not stop anyone in group finder to have an aura not using it.

**Comment by DemonfangArun** [comment]
Hmmm, understandable, I will admit I'm not familiar with how WA's and such work (I've never used them, but I am aware of what they are and can do).
