### ISSUE TITLE
SoM: Frost Trap Aura not functioning correctly

### ISSUE THREAD

**Issue by abihaj** [WeakAuras/WeakAuras2#3359]
### Description

Hello. I used this Weakaura in Classic Vanilla that would i) show the duration of my frost trap and ii) show when the Frost Trap Aura was applied to an enemy. Now on the SoM client the WA won't trigger correctly when Frost Trap Aura is applied for some reason
I've tried both the SpellID (13810) and the name (Frost Trap Aura) as triggers without result.

The WA technically triggers but doesn't actually track for how long Frost Trap Aura stays on an enemy. I've tried changing multi-targets to nameplates and unit count to >0 without any difference. The exact same trigger I have set up for Entrapment talent and that works flawlessly.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Log in to a hunter that has Frost Trap learnt and Entrapment talent(s) speced into,
2. Activate Frost Trap on a non-friendly mob.
3. Observe how it doesn't track the duration of Frost Trap Aura while, for instance, Entrapment Aura tracks without any issues despite trigger being identical.

### Last Good Version

Works on the versions for Classic TBC and Classic Vanilla

### Screenshots

https://i.gyazo.com/8a80f11aa5909f20317edec79794030a.png
https://i.gyazo.com/d9b7c32a554342c66812f7e7fb06b042.png

### Export String

!WA:2!nJ5AWTr1vC8OOjLube8JedXgcUMsAcLK6ydHK0gms2si7rrYSsojqOiTs7vA3Kv7UC3v2wUVa3a103iAHsFpQpOqPV0aL2o0wW9bTtN25upDANq)MhAPVG2jFRFRNZDx9Yp4rkmTAMeV7v79Ep3793))NZkFhTlBRogEVx3EhEp7Fpfo41DD7Jjl3vXUu6szH9wrMNlgZOGJ6P7z5SMCfgpKCUtPWnTS6iKU2CZjZv6pLPPUJMfF2e5ZBZCI(ugpCS7ydByJ8YEnCdkd)VPgQjBKt1KpPPMHt2rdhpvyPAUJ6OM6M8j85ZNFjBl5CSnXLZ5OzAyVFjBhzUtGqAgAobYMh)JTAG5D4AfkW429UtU3L3Dvfw2s5ZNQSfJhnCSjJmvSqo4nsYL4YdnVTftxFCf7alBxklBAMHts8P1MTw6rdMmv6KPckLkujCsYAPlxMXLmKlYSdijE0SrzY6oQn66KCg2vPKtgowSkLm8cHa1YzQxQOrsAf4plxwrRK9PVGk2m98I18qPsmPKSUwbdyZCCDrDYxvCqLyfOfBGq6MYkrczRnhRhPILWD1aHWapxpWUdiLtx22MUkRJSoge0LlL174WDd0VF)t6FW9ETCzdTIYomvj7C4Z6F(s2SyAf1CuZ6UFRw19VHvkWS6m5TxsMZ6psjD9(pMQMdRkxeq0E5IkLXDcTCf4MLS86vsm(2KKonGNF18yVgvJNtNLjKTj3jKHPbRIBaGJX(Hlic0nCOfzY2SKoCbnDElPGhk0xNMoI42SCMgk2ZtpdnPWHcvuwZq0r4DCEWHHRhgbVClRSLqyyntOXsCS4lJJaULA4ebjhtEwPGJn(uj9WRXnqm0)IU34cLVX5XE6Esv1Xm30yqGHZMV67zanfRloIoTHiBGWnx2Q)X8I2A55ivGRczhz)vkW1uoMMIJ65FwxWoc9Tu8Nn5OsHdhFOsAk1uDoYeLImH9jdALfJX8AfcCwKfyCdz9J6oRNyj5soy)tyjy(aZtJmnodinwvANrZT9AAg5n5U7RbW43rCLVUYDYfgSkQB4NseoBRQg2PKML45yx6gG3Gp48GnVK47LQ3hRoB7(JyQWcfCQujolbu0zTHsdnPaPGlAl7e6yHlPMRmBuxy8qzQqYlHwPxRTgHZyZPzuWDxlC(8SCo4btXSAgSjz8Pq5LkUTBKWqVCMfrOmQPTJMUMtzv4YGDutazPZHZUtxdcDYJgu6iOoUQTQ5mJQJCLTkcaB9Sypt3sCOsneEw8GpPRkxDzSHJi7Kt1DWu549XXGmd0hCPqpWfd9gGEMBS5eMb2wa4sGDxrTEmXDVIvZBfqBsIqjM5mmBNfPvUWwrtXUxP9n8b23GwD3Ysibs2Yil211dxEaRojhTPzPC9kOX6r3G4GcFypTRF4Mob82fkgeXjsVo4FdRQLTSYwMpRSNnkDEDnrh5mIppRF)OZOTSdHWm1ffh7UsGB2hSZj6b6UgTqWENg)3c9z9MCyZ6Kw8FU0wAR0oAfzPT4SCAeV6VsJhzGReZeiUZwvwbpLAyKVSBR19(Gty1TOfe1njeoNGvdfeV9SUtM2Smx90DATJvfdoUXG7D(wYvWDZUleFlkEYtwcpUYxg2CvH0GLcBmu8eXdBT91y4CVqIgvL1yn7SY1m0nhDQPhXBYpU3Kxv0TMhIv8ggdhRoIW1MR)BQKSc5y0FQuRrKy5DbCxwD1YgP3s7s3WsngoYriuCuf420mOB2XqD28hZ7c3DHPXWnlAg7DS0sk3QJhpEyP0Xchj1ASbB12gS1UxVhWlFqAuuHYrtDLYnJqkXW2xJU6SEDTTLS3gQ)f2k8G(HYdCLAWCcucExWjG3n8EG37Dc3Hp4oHndZdVFe()aW94QB(GWhc(iOx3hhUxOsg4(Q5UuLg)gJMc(OWhdEGRawW3AS7BuF3)qlSnXSw5kPIaiVIxYj3Q)vnu17xJrC9cqkEUVfDJq3QGGpd(0pW2XqeJ(SQmTcQoxo8wYxHm6e59ZiU0aR(GRcxnL6hUkX))w3zwB0XvNLn6uIHcBBx03SSqPhcRuqHmBgk4yJz1boibviDctHPCe5zvdroqQWM8bNp57WrFCB5cSnUO3fI8ZdLm4nxvXmTxBQw7O(3UUlD0E6RTr4HHhb(6QWJInCHyav000rDsUzb843wDLrJgghxd3ZlcKcatgOIWF0wtHjjokdnNPzrFq8AwZwCm9sSedh9i1eRZOI9SdZPdKsCMust0vgR1Ysv2VRNxk3VXAxJtjFZJj(V1rLrddJcHK536uJVNM3TNKICJIUPcr9kkOV2ZUfed0gfgind5BD6laMWpedQhtAkkmdP4HpAyj30ZnQsZpxZGk5ODd5J7RMjxdlTtmMvJMqA8Bjr8ubJbP6DNs5uz5o1(Ho8p)0YCnzuJhIsgjnTmUt4NNtv2OaMfENWZmH)OJ8i9sF2E0rE67v8X)8wyzImUtzWbMkamaS5f2hCSTbh3NxfcaMp4wqw)Hu9Y1)MbvvUxDZGfCB9E2iCmJyZLpiNbYQcNc0HCDniLMXblCQG9qC386m42XCFmviVkuqf6R6OyIuzN(JzwOgHZ2TKToTTOEfQeHml7MFV(OLbozgiJOcbOiyaDckGwgkxnygatKpF9Ijhy4dopXpIsWglCOPIebENurkTpGdRUuJz3TOamZF3vYjcoDZcqplLo4usbthCYjJnE4XQ04jHFv1MHjSDQcM01NWmysEG)OBaSBKkh3JbNvLogkPctJPEpeM6fMzH(G7wy2zTg(nVpFT63DA4UilkYvbnkAXy5dJFbzUqgl1DaHpb8j9b3FzYw5tvgMTUR6gpN9uHpDtNuHH1xaTOok8fZSc)iOk8LA4cbFz4RaFvvsoFRnQLSMIMn9wwJJQ7S7B4R9axZbihOVHk8nrla4BDoxde6mKl1UukSB9DDtZDu4BdFh0eb(HWpcESddpo8DjTjuZh8dAQQVKvW0nK0Wt4NuZpjkQ)EW3h(XUBkpLk80(GfHFcjjHFkjhHFg8ZHNXp8lwxPh8lD1CKfBaylbqZWfguO9WT3nTU6Vor9Nh6JcnI(jYhbne(PsyPszVTERggF)tzRIOTHGJHTkug9gamVkWIklDWdsQVvrNNZBYRpspX)tq6)BkuyLqTxvaWN9LEe)CVmz3HpFBP0FvjvAHsArZ0I6qs4ElO7AuYWdez4SZjnLr0ed7X5eyVTwa7wqeIL9WFHW4jBK0IaEuT8Ys4rh532j9PROJ8Cpg95XJoYV(YOp7ObP7Qww4Trq(tVUaEpe(2mmHLgy4bxQaZGX1YLetTLWyzBXFg1elweFVrKS3UvNKRBBpvguy0fr8A0Rh(hi)B3FuNPgD0WjtUCd3(rfVmOqk1h8BGZijEp)L4mz9Kn84)BWVNYiiYrWz0VdbMZpd9tOKcFTcDvrQlmBlhZ2Qkkld3CZDQmzXlLyfFTvPfDKNv85pIxiSv6BvjqUyujSEQT1xeGqjrSiE2eAf6ls5HClkZEWxpeyVQKceM3IeabFpjaAA6zitQaIPrY1ZJhX42S4x29hZPHVoH6Eg7KaiET86rv3x29hs9Atq0pzk3a)dGqFGv6D)kaRHNdErv4pb)zczrWE)dkyuI8ic9Fqo4)f4VQcNbFsIfFbv4VJxkqpIJF(meq)pZa)R1fOwXpo2n8Y)ZL9kfOEWZbGcHq6Ch5M29R94j80h5GxBakH16v4nKReOAIsUOvBavlWeXwUhQxO4CTP5kIsEEREmwtWQf3tYJT7w8yBWxT4O6YxJpvIy234SrMz8JU(81M8ToyvlH8fDBTGxcMIamIPWXGWRZSuBVJcHzik5rApFgbO9ITcAVGRHjXO1rnCkUFQcdCsst1DqftqLXJv4lkU4KzeLHC5bOQ4ozjdXVQ1qYgLxZIFFDZ)Io5BXaBv82)x4F1AQ8hs8w2nPSZ5KcnY7pBCMw5tfnSH2STK3VN2Fn1gy5RKe)THMrGo2eL5FatRbo8HDZ)3dMG)jAMGVRP)Dh))m

**Comment by mrbuds** [comment]
I don't see how that aura could have ever shown correct duration in classic, LibClassicDurations doesn't make any mention of "Frost Trap" or spell ids 138109, 13810 or 13811.

https://github.com/rgd87/LibClassicDurations/blob/master/classAbilities.lua
https://github.com/rgd87/LibClassicDurations/blob/master/npcAbilities.lua

You can try open a ticket at https://github.com/rgd87/LibClassicDurations/issues but afaik the maintainer is no longer playing WoW, so you will increase the chance to see that change by making it and propose a Pull Request.
