### ISSUE TITLE
Weakauras with a close bracket "]" in the name cannot be shared in game

### ISSUE THREAD

**Issue by Zyin055** [WeakAuras/WeakAuras2#3360]
### Description

Any weakaura with a "]" character in its name cannot be shared by shift left clicking it into the chat window. A link is generated, but the link is terminated prematurely by the "]" closing bracket because the game believes that is the end of the link. For example, a weakaura with the name "New [test] aura" shows up as a link in chat as "[New [test]".

The recipient trying to download the linked weakaura gets a "error not receiving display information from" error after a timeout.

My proposed solution is to use escape characters when encoding the weakaura name. Or make "]" a blacklisted character.

### WeakAuras Version

3.7.3

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create any weakaura with a "]" somewhere in the middle of the name
2. Share the weakaura in the chat (ie party chat) by shift left clicking
3. Recipient is unable to download weakaura (it times out)

**Comment by emptyrivers** [comment]
I'm pretty sure this is a known issue, tho I didn't see it in the tracker. @InfusOnWoW do you remember if we ever did anything for this?

**Comment by InfusOnWoW** [comment]
I think we didn't do anything
