### ISSUE TITLE
Slant function of progress texture aura

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3361]
Once setup a progress texture aura with the function of slant , resize the aura will lead to a serious problem , which is the cut of the aura will become jagged .Picture shows the result . <s>it would be better to use angle rather than slant in my option.</s>
![WowClassic_wmPIKwJnnQ](https://user-images.githubusercontent.com/46548538/142197800-51ef0492-7b9f-4b19-8524-372189964be9.png)

**Comment by InfusOnWoW** [comment]
That's not a serious problem, but a minor incovenience.

It's too late to change it.
