### ISSUE TITLE
A new trigger for spellcasts

### ISSUE THREAD

**Issue by nukhub** [WeakAuras/WeakAuras2#3363]
**Is your feature request related to a problem? Please describe.**
In M+ we don't have bossframes, so all dungeons packs relies on nameplates to track casts that can (should) be interrupted/stuned, or to figure out who's targeted by said casts. To me it's a flaw because nameplates aren't always visible (too close to melee, mobs that are behind you, and so on).

**Describe the solution you'd like**
I'm no coder but this https://wago.io/BFADungeonTargetedSpells from Buds seems to track spell casts by events, I'd like to see that in a trigger that doesn't require code.

**Describe alternatives you've considered**
Combat log tracking doesn't work because even if casts are interrupted, the timer continues. And you don't get the target of the cast either.

**Additional context**
Additional note : many, if not all, mobs get their target 0.05sec after starting casting

**Comment by mrbuds** [comment]
> I'm no coder but this https://wago.io/BFADungeonTargetedSpells from Buds seems to track spell casts by events, I'd like to see that in a trigger that doesn't require code.
You can do what this aura do with the Cast trigger and a dynamic group without any code already.

**Comment by mrbuds** [comment]
> To me it's a flaw because nameplates aren't always visible 

These events require a UnitID, if there is no nameplate unit, no boss unit, you don't target them, these events do not fire.

> Combat log tracking doesn't work because even if casts are interrupted, the timer continues.

With combat log you don't get a UnitID but GUID, without UnitID you can not use API to get cast duration, so you need to hardcode it, we can't hardcode all casts of the game into weakauras to make what you ask, so it requires custom code
