### ISSUE TITLE
Add Unit_Spellcast events to the combatlog trigger

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#3366]
**Is your feature request related to a problem? Please describe.**
I know it doesn't technically belong there but there are some instances of the game that blizzard decided using Unit events instead of combatlog events would be a good Idea. This means that on some bosses in LegionDungeons for example UNIT_SPELLCAST_SUCCESS fires but not start or a normal combatlog event. This means you have to write a simple yet anoying custom trigger everytime.

**Describe the solution you'd like**
a default trigger to listen for UNIT_SPELLCAST_SUCCEEDED like the combatlog trigger

**Describe alternatives you've considered**
writing a tsu or custom trigger every time

UNIT_SPELLCAST_SUCCEEDED

function(s,waevent,unit, castGUID, spellID)
    if spellID == 198024 then
        s[""] = {
            duration = 10,
            expirationTime = GetTime()+10,
            progressType = "timed",
            autoHide = true,
            changed = true,
            show = true,
        }
        return true
    end
end

**Additional context**

**Comment by InfusOnWoW** [comment]
Not as addition to the combat log event trigger, but as a separate trigger.

And yeah I can add that, since it makes your life easier.
