### ISSUE TITLE
TSU: If State of WeakAura starts with Static and changes to Timed, cooldown swipe doesn't work

### ISSUE THREAD

**Issue by Aurokin** [WeakAuras/WeakAuras2#3370]
### Description

When you start the state with progressType = "static", then next cycle change it to progressType = "timed" cooldown swipe doesn't work. It works just fine if the state is always "timed". Even when cooldown swipe isn't working %p always reports the correct value.

### WeakAuras Version

3.7.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

https://wago.io/-aGnOSlbd

I've included the reproduction steps and sample code in this WA

### Export String

!WA:2!vB1tVTXXv8qtB4O1PjYkXgUPPPBiqtKsvLLLRDasQmaxrsBMklYSKYYTUbsZU7qUt0YzNmZS6FfTaHiOWN5HEP345EIFe0HE(bHI(bWN7j)jOVz2LYww2N6PsaU89p(M38BEVF7uQ3CdMlAoL)Tx6lwAL5IE6kYdB1RNIQlj3JkvSuE5jmEVu5aIgvCglP9XF7EOGEC0HCYawyFzAMyeHZYd5UEdimEdpngIhpLtpjktA9STXKurdt5rQHuIIAsd4CSrSJws591Xx2xPjsDdygWbUc8oWpb)9DVCqpgNPIFvZ(jSbm9vgPOj9ANY46v62Q9kzYeXplwRfQV8M3CFs)0LyP38xtUpVvNKGOBERrez462v7hV(WmfDDtsINeKkJOY1stsLFDPsLkpo3q9O(uXv789zej1TrwsI7wXmnvMVJPXNqY0XPYwcZEu5ipOaadmRCZAJoDHdKKiwM6hFNaeb6X67SsglAYJRw7pW3ALQcMxXc2HDe9sJ7HR0AmzycDNkSiXnAlt7lPkLbZC9Y67w)aYarcDSonS4O6TBF9XQSaF7rKY5Kas4UrYur(wQC5YTlV8s355imrLCsYJY)xpjiFzJLiY3VpvwYxjiH0l9SC7EfzrmRxc7OJiYi3UPPjAMWxfssOLpopU8T9mpd3CyI46gKqDQmWVATMB2jqrhGvP)TwA5Lw2tLk1GZKEsYaZbprtkpuMUFhZYAK02(LsJnDkScyfZMr4UEyJG2bEphywNjeEic92t(G1QVr36(fNIn5yTuEsyAs2aEEE9ssjrnc0yjZ1x3FqgUfC8dtik11H1C8uiSNliOHgbFscRphU3qTKzWf1h(PJY4fkoYcH)6qm(KKMrkhygFc2RVIxgwIbIeYH4oMUhUCbpGss0XJJObz96zocLpO(6TBS56pdpWSH0bDWoyY2RvTt3T70TQF3tD1wsrx(DAxF919XzoQYzyFjlYKNk(1gzK3IfPJVIhomUVxTwBTXZZHMggi2exqN18RxFJ527F945c)WN(zWfkHvJIOndN0y4IoWFe(w4Y3fE7xDidEVZzz2x1YZ3LsfvniN23C4fdvMiQUj)2PltUvJhDCi2XeLUp3mmfpMHhSDsZKH0p6TGFEj43a3bM)ZF6neFIMEGEB7JCoNTfBRzdOBlK0qMLos8tFnXKl4Bcns8(wF4uzQHrk0ImEvr1X2olAx0T3gT2O(j5y0JlgypPiNCT9aQ1MDxV5g1fZznRIjy9)7lc955HYoGMd8)WRPQufcibN18Ey9hGtZJoDzeZ2qYoY9BYirMza3UDZJ87YuAwVdH7Lxr7JD0BjjIHBvi8S8kAkNNx1n72s8XVjOlxR0Ot9x5xkk25t3oIzFP94lialm)sdzW9gBnfoLrPmmJeBtngfl8MQGIxuSTogjWIXgHdpdOEE83WaU6)Eu)KPvJzLSQRZ4u1v9mIXhJu33FAiXdn2mhCNeKP1P8wiDdobEI1CmlCx8pQkkxJTX20zFlW1SYE5SG2LPJLyBIrCkgzvoTunknK0VpJYdpS9fxEPvUZWP947eetz9J1)a8ziJm8XWVW)f4L4dMgMPnSgtrWEIODGp)jWQW9GYL9332q5DuA6GsWhaxd(IYEMbMDMeXugsLMOYnUW7)FGV0b(eNtMMVo7Ze0DGV6UWVTGEuY4M3mGt3vBaEgknOM9zD7ZgfKCIysz4bV7NcnDGV(Fcpe2a(gWhMjie7dthaDGUWF)Gla9Y4wo45vl6sx0vMXxWXf)W65opQ4(xw1LZswWvht5whtDsDxDv3kDQB5162CTkVsmMpjPiK7Ul9q3vD3ePpV)MnRnFLCo0klCMqvpbd7BX4(tNXS1vC6(OdTmJU45Cggt49PrVr)Ix(nSybRmVgkSYIUUNl09ijzMyU15ZIg5ysoVR)8z0oJIKIKWCBr9vN6GMOONf7628H1R9)jqNLi(1ICtVmig1Tx(8jIEGGLhqxmf2GC)vU3NQnQZVW)JykpYz6V4xyt4r5VGvjU2l6ox09u0gAbTHTCMKpiyV)6etxbnteHpHFhE)HyA4UqlXvn3pzpA38lf8W0i6)4TGpYbV6waEzne7Glb)nyoCeh5d(Vd

**Comment by InfusOnWoW** [comment]
Should be fixed now
