### ISSUE TITLE
"PvP Talent Selected" - Load setting issues

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#3373]
### Description

Issue 1 - If the active spec is changed at any point then the PvP Talents listed don't update to the new ones. 

Issue 2 - At <max level I can't select a PvP Talent to which I don't currently have access, so I'm unable to add a load setting for others, or for later levels.     
I don't know anything about PvP Talents but it looks like there are different numbers of them for different classes and specs so this issue could also be the case if you're trying to make an Aura for a class/spec you're not currently playing. Even at max level you might be on a spec with 11 Talents but want to set a Load setting for the 13th spell, for some other class/spec. 

Overall this is all quite far outside my own experience but was making a PvP Aura today (actually updating an old one that wasn't a PvP spell previously) and bumped up against this setting. The name and icon stuff is nice but it feels like it's coming at the expense of broader usability. 

### WeakAuras Version

3.7.3 - Annoyingly I only see "Dev" but pretty sure I updated it very quickly after the 3.7.3 announcement in the Discord. 

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

n/a

### Reproduction Steps

New Aura
Load tab - see settings
change spec
Load tab - see settings
Delete Aura
New Aura
Load tab - see settings

### Last Good Version

n/a

**Comment by InfusOnWoW** [comment]
The first issue, yeah.

On the second issue. The code as is, doesn't even know how many pvp talents wow has. It simply iterates over all the pvp talents that the current class/spec has. I don't believe there's much benefit in adjusting this to always include a hardcoded amount of pvp talents. The use case of being on a low level character without access to pvp talents is frankly too niche for me to consider adding a hardcoded pvp talent number.

**Comment by asaka-wa** [comment]
Well, I happened to be on a low level character but my understanding is that there's a varying number of talents available on all specs. So I could be in healing spec but trying to make a tanking Aura, and not have access to a setting for that spec.
