### ISSUE TITLE
Text Outline > Shadow Color is not applied

### ISSUE THREAD

**Issue by deemerz** [WeakAuras/WeakAuras2#3375]
### Description

Doesn't matter what Shadow Color you specify for text Outline feature, it's always drawn as a non-transparent black.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create new Text aura.
2. Choose Outline or Thick Outline in Font Flags section.
3. Change Shadow Color property to any non default value.

### Screenshots

![image](https://user-images.githubusercontent.com/26042479/144463940-b1680f6e-24fa-46d4-9025-4105c249a739.png)

### Export String

!WA:2!1n1tRrnquCx2dcbPAxWIGxwu0lkfPfBR6HYMLSSB72DxssTv6HWKmVSz0SZeMzY2UECrep3JErCp7P8rOFccfVl0J6TEZBotsOiI9DzEVH3F(9(9EVADAmPbUb(tpIZsLXekCMB3ET3D4(U97nWYoGfZ470D7FDuH0D7F(5cP72)4lA5R1tEcMisIrZCHtKEHm(eK0lXtsMaE4zu0esGNmIdIiwmEgF2WWqbiRLHObrm(igHk9BBnW1YoP51NPsRAj3jivizt0ESFcgjbBykqLxGsv)IKKGdiyzKzlLjhfijmQydBHeXLg(HekrezyQEKgZLCY4XaxS0J5vQFCbg8tddDNLa8Uw9h1z)(MsLHnkLJwBUibIJ7Hfgxis9lkRJYBYjzETB546542Y21mvLCFDtaCBvZdcJCd)UakwgDvyJ4GkmBNrw97FAkTQ8gjlRr8uWT0Epgg(2nsU))LukvS1Cd(sffcCkk(1Q2r1Xhn)yghFahLm)GkfZqgvEwlobf3CaIZzhVqbgBySMGmmJziChFjkwbUvSNKgljgMQ2nyL8NAyheJecTMPG8EqRmxNohLbCUicHzhFy1uDbViLAg0uQa8Iagftkgdgjp86hVjCiGOXE9truIEqYOBKVuNZaKaCKCGowgDZ87Aszu4CSACO9WtpC4cqxeXCTR6cNVL5eeH2jFtva5BL)I8xM)k17T)3FQW(BQWo)TQvls4mZ(wDCxizbtlPZ7vZ73pGGtw2PW9MT1NenLGqM9xnKTRLJRrwixnZvagjr1VSCfVJ(lnW8DABBznyTucoRxFwiP7o7(owKVc(HKXg8tQaY5QLzvCdtk5TSsy2U6s8QdWSgfYvkJQ)SvF(c1IfGloc(WTYi0sAwLhJtfqCy55M5qx3H71qyV(QBU66nM(9d)d

**Comment by asaka-wa** [comment]
Outline and Shadow are different effects. 

Your Shadow is set to 0/0 offset so is not visible,

**Comment by deemerz** [comment]
I see. So it's not possible to outline text with the different color then black.
