### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by Thanodes** [WeakAuras/WeakAuras2#3388]
### Description

Increase in memory while in an instanced zone

### WeakAuras Version

3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Normally at first when starting the game the memory usage would start out low but once you venture into the outside world it would start slowly increasing.
I noticed a dramatic increase in the memory usage once I entered instances such as dungeons and arenas in which the amount of memory would increase more rapidly.
I currently don't have ElvUI installed to test if the interaction was caused by it or not the only other addon I have installed is DBM and Details.
It seems stable for maybe roughly 30 mins but long and sustained play causes issues as it rises to high amounts and causes a crash

### Last Good Version

3.7.2

**Comment by InfusOnWoW** [comment]
Memory usage is usually not a concern. Lua is a garbarge collected language, so memory usages goes up until the garbage is collected.

But for us to investigate we need far more information:
* Exact steps to reproduce.
* Memory usage numbers
* The auras which are most likely involved. We don't want to investigate a set of hundreds of auras. And we obviously need your settings.
* All other addons need to be disabled.
