### ISSUE TITLE
Super little suggestion about Sound names

### ISSUE THREAD

**Issue by BigBont** [WeakAuras/WeakAuras2#3390]
Today we have so many addons who have they own sounds. And when you open Drop menu with the sounds it's a really Big list!

Here my little suggestion: add    WA:     or    WeakAura:        before sound name you using.

For example

WA: Phone
WA: Sonar

WeakAura: Punch
WeakAura: Splash

or even

WA Voice: Run away!

WeakAura Voice: Tount

Just a small improvement in the quality of life.  =)

**Comment by InfusOnWoW** [comment]
No one does this, nor should anyone do that, since the whole point of shared sounds is that it doesn't matter where they come from.
