### ISSUE TITLE
Can not add certain author options types.

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3398]
### Description

I don't know the string name of these type in english , but they are the No.2 No.4 No.10 of the list in the picture. 
If i add them , error pops up and prevent me to do further with author options , delete them will go back normal.

![WowClassic_WKbLVHZi2D](https://user-images.githubusercontent.com/46548538/147381756-37549951-b6a9-4497-9b76-25c522048586.png)
![WowClassic_Lu9rSDwtnJ](https://user-images.githubusercontent.com/46548538/147381757-1e3a8304-fc12-439e-abcc-904a350bc84c.png)

### WeakAuras Version

3.7.3-35-g7932d79

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

AddOns\WeakAurasOptions\AuthorOptions.lua:539: table index is nil
Count: 1

Call Stack:
[string "=(tail call)"]: ?
[string "@AddOns\WeakAurasOptions\AuthorOptions.lua"]:539: in function <AddOns\WeakAurasOptions\AuthorOptions.lua:530>
[string "=(tail call)"]: ?
[string "@AddOns\WeakAurasOptions\AuthorOptions.lua"]:2561: in function <AddOns\WeakAurasOptions\AuthorOptions.lua:2556>
[string "=[C]"]: ?
[string "@AddOns\Masque\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>

### Reproduction Steps

1. creat any type of aura
2. add certain types of author options listed above
3. error pop up

**Comment by roundzero** [comment]
The latest alpha version fixed this issue , it could be closed.

**Comment by InfusOnWoW** [comment]
Ah right, we already fixed it.
