### ISSUE TITLE
 c

### ISSUE THREAD

**Issue by a76yyyy** [WeakAuras/WeakAuras2#3399]
### Description

c

### WeakAuras Version

c

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

c

**Comment by a76yyyy** [comment]
I just opened this issue by accident. please admin see this comment and delete this issue. i am very sorry

**Comment by InfusOnWoW** [comment]
No problem.
