### ISSUE TITLE
WeakAurasMousePointerFrame has a higher frame strata than the WeakAuras Options frame.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#340]
This can cause annoying overlaps with editboxes when trying to edit code. Strictly speaking it's not actually a problem, since I can simply move the frame to the side. But I'd rather not have to do that every time I want to tweak something. Perhaps `WeakAurasMousePointerFrame` can be set to `DIALOG` instead of `FULLSCREEN`, and the base options frame given a higher frame level than the mouse pointer frame (or even lower than dialog, if mucking with the Options Frame isn't feasible).

**Comment by InfusOnWoW** [comment]
I did that because otherwise you wouldn't be able to move the thing with the options dialog open. I think I also made it default to a position outside of the options frame.
