### ISSUE TITLE
addon action blocked

### ISSUE THREAD

**Issue by Globalscrew** [WeakAuras/WeakAuras2#3400]
### Description

Any time i go into looking for group, i get an error. Only happens when I have elvui, enabled.

### WeakAuras Version

WeakAuras-3.7.3.zip

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: ADDON_ACTION_BLOCKED: WeakAuras tried to call the protected function 'GetPlaystyleString()'.
Time: Mon Dec 27 08:07:55 2021
Count: 23
Stack: ADDON_ACTION_BLOCKED: WeakAuras tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...UI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Interface\FrameXML\LFGList.lua"]:3508: in function <Interface\FrameXML\LFGList.lua:3499>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface\FrameXML\LFGList.lua"]:2576: in function <Interface\FrameXML\LFGList.lua:2573>

Locals: <none>

### Reproduction Steps

Go to dungeons & raids. 
select dungeons, or raids shaowlands.
mouse over any of the groups.

### Last Good Version

WeakAuras-3.7.3.zip

### Screenshots

![Uploading WoWScrnShot_122721_081343.jpg…]()

**Comment by SpatenLa** [comment]
delete that horrible aura that does try to change the dungeon search feature

**Comment by InfusOnWoW** [comment]
GetPlaystyleString is not called by WeakAuras. Apparently you have a aura that calls it.

**Comment by Globalscrew** [comment]
I deleted all my weakaura's. Will start fresh.
