### ISSUE TITLE
Doesn't work with the spell 330325

### ISSUE THREAD

**Issue by evgen66rus** [WeakAuras/WeakAuras2#3401]
### Description

Hello! I created an indication as icon for spell 330325 (ventyr type of execution for warriors), and it worked before I logged out. Now the addon does not show it at all, even if I create a new one (additional) with the same or similar settings.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

there is no errors

### Reproduction Steps

1. Import my settings
2. Try to hit an NPC and see you don't have 330325 spell activated

### Last Good Version

-

### Screenshots

<img width="863" alt="Screen Shot 2021-12-27 at 9 44 56 PM" src="https://user-images.githubusercontent.com/18571021/147491464-f4a8f842-da58-42f4-acbb-7b629fc07dec.png">

### Export String

!WA:2!LN5FSTr59F8462bZA)ijTn0uyf3cn0wODzU0mkRLw7u7gxSJdNDAAl)W357EsUJ4C317oNeNXyng(cbOmgHr53WMLgdHM0yw0Yp2kuvnT)7R0NeMQydqAeKMg)BNet7pySpFEUZoUPPIMrrQAePy)Cp3ZV)86Z7Nppp23EB2wyZB67VPn38qnR0SYeRA6CsYdQyzy2PrEdR943V)E83(M2szhd5Hzw2Ag6RWx2)1m5mSuywr8kRzJrYRn2yswkbZyyK3rZCAPcoQgwPmDWAyhiNB5vl7(DuLbyMnL(GfKSybJviF(G9PQ5WkBXgalEMIMmHbSmky6v80AJXwI1OP6VFBMtxNyTPxxd4FvCFP740NpF(fSLLYZ8BvSAb7BhTDiSGwsY8rrhc2oswobY1VMUMTAGi4xobk5yPnWa4uBLTz5L8(kRWYvO)(PbIvxrt0tSEteXHgvsfSKcvY2KLpFCf7aZyxihByMUtAS0AJwjBNHtNjB6mHfYePa245mZlvKzjOlneZoGaVO56IjL3rTwv7XIHvviDprtKyYc6EdHavK0LXfWEm0WQ0z0UZev4KUty3z3xpsEdjLy5CWPSUtlcdvax2debhAYTaxBab58s22uQi24QhLysBw((5ThCnRrtPsYIb7VGvXGJiznjF1oUmACx0sAOs)w44nTJLKJK)t7ooIrzrRh5s3Pq0ODNdlB)AdeiubSLew3nVND3xCw4(sFAS5zw6s53RlSCRLX5Pa3SAhysjDTHKiBrhqZXojtYM6fM(aoQxc0AeDdD20k4kmvIS06TLnd7hf7surPEh2wKHK00Jb)aScW2GTd3eSd87Lo3Ckt1tZf(QOP3VHLBhhWJAIRJRH(Bw(nN4QkRHLnTrblz2v0a8n7ANzoXwj(cASRti)zFmsqlcAdUMPLrYwXye90JOzYepz1hjwwnc1gIWYVJ2Gw(eOvboHaxgSc4kGVdSAZw70R0b7XYyalMTDW1LMkZ6nBQGnl7amDMLMCAvJrsPlo9z8yzB8RW5hrQOnSk4kN2c5hED7gnjMndVa8wtDi41N6(Gxboo86WrNMAr7QLqeU8aqWaMlLYLnk6lm77uHRcU6jPxGgB5bfNS2BwXIF3ncRnaoDogUS2fShry1thM7hfSxBPC5z0ybsUILeOxiLiFQ2JiCZZyZhZvNUWTicc8YS2avu0SVZc6yBmmlKKErZMK4PZ4s8jnuy)6gGB4wp9GmMzycKDeiBMk8DHRb9iTLCi2aNqBDdtSmZMDyJItfvjSF2NRpHpZw5zY)W1KN12lbSTjR9U1SwBZgRR6ZkHmJBUvDuIeU3mPmxkptuqZGyi5(0uCuJegF80UDK2OmfEMJpTRZY(9goNK)(7SGTJw)fX5GLHdo(ZGzgP7uDhfA1cDoOYuMxq5QkU(N0BgO7y2ymlTXcElfKui3XGzYCgt8Q90088gbr7(SKml1Nxc3bWWA2AObt0BoxNWIztX7U7OczJKktMujfIV7UYmDTUMuDB1BgTVZOFO3Y1gt1BMeX7o6PMEG8gJeZIDWcmD5I9S423uOT4o7OxuH(OAluIEGQ805k44yONc3vbfjltzNGlfSCE5RoZMKEO2Er(pjcR7UAoQrOxQY79mQAYdQJow(51inFRaEYeAy2nX7GiU7cLtLPnGQZ4W6pcSbsAeUU2YzRPpqE2sGRTLLiws2aLMLqDv4Exc1LzRMHyjpNlzrUFdxMvSSBrgkNKJiSX2G71QVWccXtjGTg8GIWM4Dsay3qhvmlK563)b1ysTNdUrshCUAz78ZxDdIeacVH2eKvzYdgdAXFPHLS0iVYYg189egwkFbM)C8czVHoGwq5ThUKMU7afEe)yw(Hhg(jyslzvj9by4MGWJiwYe3tNz5ueI2bCyS9xc8WrihBSGWpTAlbpQBtGVe(zyYC510hKPOctUbQrGhJK(3uOnrl8ygQWJb7hAcNXbGLgawwGiJzymKpWpfpbUFe0TWSoacs5nvL8dBgUEiKFylbS00PWpyQcJW90GVgxpH2F1DBRgFRsvvKfnxw1KKV2U046vkQtCvWU4k8Ni)74VQcVHW))pNsIk8quriMkSBuh)B5QJJcFUQxKkEWaKk4ndziHUAcFO4kjeI6OWQH0KEhjfU2aqFCXmyFC5ly)QCvl4a(GBfTF3gkbb3oxYbUdilicsqUXbzFGcwyg0p23daQ81cqdUtyqFqEyia3JXamHd2ky5dSbNtbfQ6TbddJ4dgfkcJTC4h6dUl3k)JuH7wfoKF4h7hgVjOKkCpi3hZdjVo(NBK)5gQbPBja8CQWZUIouFbCDgEcFEGkrGiiwhOoNCw6zLtvRR5Yo79PcgcEs3b5t5hEMX5g7oQONCVTNPyVBE0KdcpTkz9FEvimYLhgzTRd5UqH7ExNnf63JcHjxPl9bhH8sC5TLrixnZ)o1FP1x18N5XEUdD2MFAB8)g38tgEHl91s4A6t4UPNzRWK4e5)BQdn1HdcVj87WzZXXVFlOIhsSAiohjqMPgrGT5lwBVuev4nfuMQbVhiYAw8PxyVZfHeVOcHggMq0JzUFruafvk5SeMaEqk1duVUhHuIis5)z(2xWqQl)CAfMLSc5QHG0vhvkU709V(EtMzS2lqKfcD1rhKEkhXQQiolirIG1PZbpUikX1cryTW10qm75RxCz7)(Q0v6354hA(fxQNUUV7QQWIlDDzKRc8BHJcVkC8PEi4ncI(nVcCSASv6ZITU4wTzHJkK6ZIw8NCHcvGF58Xdzgo3131TinwphuD(4H6KCGFX5TGdscTx22uYAqEiHl)K80UbZSpFCjN0VsdEqX08xkqHfIbw7ZSPZ4zkIy0ATBvV9JMHh6bDyGC2gw5eXz7QmBMYuINbDWsQoICUAJ4s7QH1WJxHolQiAek7wqQqMnMAVrfseE)zJjKkz2OOMkYwECfYHZmB762MZcA8dmvx0Qe49FRjQuojVtW31oowl8)831o(JhH)NFeKRF9B)(GTEJTaTwHogowXS4)tCzWb8teU5cHWnx9zDqbZSoAdXYAAXK1OtU6hg8kAWC9NRYPuepuVMCwhv80CQy0gf5Um2r6gpflyu2nW6erJLXCvNR2W9P57ulMEjeOYP45bQlsU08jR(cZDg52Q(ZvChy8y9NNowV2XLQ52)AW9S9fGp8mCdwK8mDfcCcfEx7YSreMcRqheIPWusknQk3lefmpnDDt0TpORu7uy8lCQEFX5wFnDviGLheqc7wrT2LuFDAFdTJkgtYXtBnfMaFwwXW9igY51mfDDnN98ev4p3f)8aB3IwjkyXkv92S8ERMIctxO7OOdJloMXTCMRloDBh9ljZUToLWt5PpqejRBR34BC2N2yAUlnVAQZU3vJWtGQ7uar42vtDyuRpKByq373Gu8qnqurcdv5k)3nWVRldlnMURSq5Usje)aP6ot4elarkVyYnB2nO86pyy9VzZNXBibnC)Kz3Bto9FGFFi0EBV0)SHp)iNU94NzKtReEA35m()XWn1WD4WvHXNQeUgSqdD6uUHoHDXxjcDArlnXfS9dp18TFiZmHu727tZotNFXJpQ6EIZxis78Q)v)9A3W2)49phy0envHFSAvjl8GPUqebgcRWxY1z2Ox(zPtQk5yyTMTT9AChYqwEVV52rQ7YHFdrDeN5frf609qWBZbqxSJyh3t4HGeXxCQ7uWFEn302H)sZFp4DvNnen494Ohnq49jXKU18)DrqkKSl9t3Xfme89MpemvN9AW2II5wJe7lzeKfVHANb8UpWN)zaDgCUczpkkA)AuK5iwn(u3d8QC8Ie2wOczFaNMWE4Re6yxsdV)fmi6dMpiAWHt2vSUsKYzD75ccer3C1rQDdwZ50EjF5xUkhP0GVQ)ybZHJCVkj0S6gUUdPm5iWoybnl6cZ8KpiRpcljNbEueNEJ5GtvVLjIg53Q(IqKGtu9BHnk)Q(NKIjI)JnTsZwGNKdMLW26TXdhFu3lDH)tiGb4jRYSD)9fM29k7tQztxbkosxznamKu(8xCD0sK)o0zHG3Fvk8beRd(QXJ1F7RfzRBpDoKseNC2FXU915e41nwxWwZYq(QpCmxqJdt1FnOKJqnE(VwhpJS8t53lsqITrFMNL(55iP46jWCpEIQXKj)zF6jAObFZZ9n8IWhkcZSs4JOZeY5iePiuIWke6QZQFXR9(OlC7DFhyZDA0B7rcLEOlO27ZNBd4CzK)O6nYh98YiVtwVc1Kz2X5YiprJCZ5h6EbaZSYtcphU7uj41NAC4nR7(RjZFs4J9ewCVL7fpvxxmFb2Fr5Grc17U6P72vcfn(xECqBv5GZdi4JpVHGMh(pTV)Zd

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/2766
