### ISSUE TITLE
Alpha Conditional Error?

### ISSUE THREAD

**Issue by Crelam** [WeakAuras/WeakAuras2#3403]
### Description

Weakauras seems to get 'stuck' when this aura is loaded on the latest alpha build.  By stuck I mean when building the list in WeakAurasOptions it stops at "Creating Buttons".  I think it has something to do with the Conditions and custom code text options.

### WeakAuras Version

3.7.3-40-g04f8e6c

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

1x [string "Error in: Frenzy Timer 2':'condition checks"]:67: attempt to index field '?' (a nil value)
[string "Error in: Frenzy Timer 2':'condition checks"]:67: in function `?'

2x WeakAurasOptions\ConditionOptions.lua:228: attempt to index field '?' (a nil value)
[string "@WeakAurasOptions\ConditionOptions.lua"]:228: in function `member'

### Reproduction Steps

I had difficulty creating a new aura that generates the error so it maybe an odd edge case.  In leu of that, I have uploaded the aura that seems to throw the error.

https://wago.io/otbU1shsW

### Last Good Version

I am not sure, It works on the stable build.

### Export String

https://wago.io/otbU1shsW

**Comment by Crelam** [comment]
I know this isn't up to my usual standard of bug report, I got a head cold and my brain is a little fuzzy.  Sorry.  🤒

**Comment by Crelam** [comment]
As per Buds request, here is my SV in a convenient zip file.
[https://cdn.discordapp.com/attachments/627721814700982313/926622417814704178/WeakAuras.zip](https://cdn.discordapp.com/attachments/627721814700982313/926622417814704178/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
should be fixed

**Comment by Crelam** [comment]
Confirmed as working.  Thanks for your time.
