### ISSUE TITLE
Global Cooldown Trigger passing Heroic Strike and Cleave dynamic information

### ISSUE THREAD

**Issue by wowflexed** [WeakAuras/WeakAuras2#3404]
### Description

When creating a global cooldown trigger and text display of %n, %p, and %i, I can view the ability that triggered the global cooldown. However, as a warrior, if I trigger the global cooldown and then queue a heroic strike, the name and icon change from whatever ability that triggered the GCD to heroic strike. This does not seem intended, as when I queue heroic strike outside of the global cooldown, no icon or name shows. Is there a workaround or a way to fix this dynamic information passing from the GCD trigger to the text display?

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create a global cooldown trigger 
2. Create display texts
3. Trigger the global cooldown by using an ability
4. Queue a queued action like Heroic Strike or Cleave before the trigger expires

### Screenshots

![heroic strike](https://user-images.githubusercontent.com/96927935/147841749-db999a1e-6828-4768-9214-903404b50c5f.png)
![sub elements](https://user-images.githubusercontent.com/96927935/147841750-c41f4c14-66bf-413d-a879-83090d921e9d.png)
![global cooldown trigger](https://user-images.githubusercontent.com/96927935/147841751-09db989f-c6af-443f-a192-f314070168c1.png)
![mortal strike](https://user-images.githubusercontent.com/96927935/147841752-677d50e8-0876-406c-96c6-b0d0196390b2.png)

### Export String

!WA:2!1z1YVTXXzCstu4ITOiY0ncj2QbSUWcjnnYYmn2f9u5srzXyksHL0rYps5o7Ud5owlNzYmZsj6tn8Kq7Lc(hqpq0J9epKESf(ComGO3lG(tqN6T0Vz2vswUjeqANhFVF87BkUD5rLJkhDYdNl5iXH7tIuXV7CsiJ2LLkcXRvi4i0qwZTM9W6)M6Q2T4XIjDgmqIv78Vs(pF3PfkCTfiAymtShJqvb1B0UxdVLwP5XuifHrlYVXv2Vllc7w7j96unvKWxlwP4YF39UNrrBqy37cnDVQ3)Sau4HdfSuAuDwct85flwCVsBUXNnvjidhIfY)66I8LFJRAch7MsjQtLPb4XyQQB6GbKJx0VETU963TxnVElsL4(e6yGvCSNLi36iPsFJaEcAcwyjqYXjjnJINMVq6CHi3tGbr61DVgTA5rrJWsNPgwm61FEeoauzpWqe70O1EB)KwZsP5gOZ6635K1MHsfilF3Y93U5NTj)ggUhIPybjSBm7Oou)Lxz7Ps7N6mwse7iQ(N7p3OSghtKkP)mo7iSW46)u9pl2AkXiAKV(w6BlsPzEikvXwAU6cI91FGyNAE7cwi46kKyiwjakAdwMVEfpRJRlRVPauzhAYeFxJyDhHiu97E2JsybOKkNBtZSKB4T4sbgL09YTxeoZK877OxZzAeedmLcLV)YrivymwM5QZnUATKJqtKZmmQeq(3)uZsuGKjcm1o(6kolIiYxMsdvKX4Qi6eE5WuPInQxwOUfBijK)XdSuWOFyEg4JCQa)eyvQGwj)SNx9lDW0i(nqwHLlaJE(7fSDc9dTvELGFNbL4ybfL8fq5di3Nlqw5lFGNecHkNGbekrg74cFuRhKztxBweRF2Y4zikzK11FGERTFngjXDvcmDOk(66vCPmkE55bN(M8euMc2qKCQHutDL(X6QBR)CGAyvl9U62W3gV9jtdqI6xy3UryzipClI0uJlRGQOIj0kanvoIOIRmbA2RecDb2JG0CLHz53W88BfUGnuGLgNEJknPHjPGiRykJTKFUjVXRTD6ziehu8n390IZHwip8qt86zRQxzHPra0xF4VtwL)(k8XQ(2)nGjGyuFA(c9JNDXD35Uu(k2DYyeyzxGku60StXjdSirAh(nTNyk9nr8ql4MBny7zzAHCmoYE4xVmdc7PzwAXxBV)LqgJmyI(6ZfgGlCp4q32DA3qVIa8edn8YzQWY9bzCF352ZUSOzwUprvlQngrvvEeseHZznZlYv8AfwAp8iMiAFbIpD)8flVqewKLopPxRMTBKhiEd435nB3UHx)wn2U3vmTC5)TfUIwZn4sxk9UKxHV9YR4o5bJXejjib7FYT4)I)VefVVImcWwe4qIPcPKE)7Cx(3tgLNVWZqFK(PAh9Z0px)IVw)Lf1)b91191(6Vq)y(h9dPJOjqnhjSVkgQgJHIZjqvpshuuhAd26inwp6BlOhSwb(h8djLSDf1d1XAI(L6dxKf48A(OD6P)kF9b2skn72AErnT0jRASkJxro)QVFB3Al)6cVPXagsMECBdn36d1jw7dcsSFPr6FL)4LbqEgl6ZYI4NVnlpufApwKFIeYpLED(MWll9Zp58K05KJJaKS7xzpOqprVYmOOn7IGymzySANF)n)U)7FSqHcUgyUy3egk6BeeQzEl3XI)MaJpsIHXdjWuKv9gLMOioEHjiPC9ajqAcwSFnpVMD80qq6p7B5YEVVlaoIDeVc8Aya61CfSe866)KyRA7w7rnS0)xYO3mKse7ctjcxvFIJRXnnlo1cF4c6oYGhxT2wBXxbyOwKP3ehHJ2fDCCay8didDMDzV)1H5WsKYakHJZEAZLGHZSG6sc8ietJYPYrmMkEVCaU43wdeA8CHf1Y27LdADwwYzBbGaAopOBDVgnA7Hs4XOsNzv5wxAdIXzdm(47qI4VN59gvCrI79wtrxyzBhBY5Nim1TPcSxxwcjYZEvS7RySrfdK4rGa9(0n2CJ7pxXcZL(pEVvZfbjkctDD70BNmi4EzYI)HnndWgajMxymcibcMXlEsZp5YDFsxddlgy8my0esH(rEhzqj)BL1)k)QPKOfhFWGUVCZKQbHVsK)ukFXX54flyccuSyhhmFNoEnFwN29Q1AUzkgXoS8wR7bt8dp8b63P00XibbbfTUMj)EJrjP4sIq4PgdHhiTU(Fgpfg9WnVzr)pwqOzDUGuwL)EKHuMa3HBfAdZ7CAiemH0FjG5djN8BCklHi1d34tlp(FFW)7d

**Comment by InfusOnWoW** [comment]
That's not possible.
