### ISSUE TITLE
Subregion Error on StopMotion Auras.

### ISSUE THREAD

**Issue by Crelam** [WeakAuras/WeakAuras2#3406]
### Description

Every StopMotion aura is giving an error when loading in.

WeakAuras:  ERROR in '[AuraName]' unknown or incompatible sub element type 'subbackground'

### WeakAuras Version

3.7.3-43-g2716714

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

No Lua error.  Just an error printed in the chat box.

WeakAuras:  ERROR in '[AuraName]' unknown or incompatible sub element type 'subbackground'

### Reproduction Steps

Make a Stop Motion Aura, then ReloadUI.

### Last Good Version

The version that I downloaded off of GIT at the end of my last ticket.

**Comment by Nightwarden24** [comment]
The same error when creating any model aura.
