### ISSUE TITLE
Border glow for anima charged combo points

### ISSUE THREAD

**Issue by Woahverdose** [WeakAuras/WeakAuras2#3407]
Would like a feature to be added for Kyrian Rogue anima charged combo points. 

Feature to be added would be a border glow option around anima charged combo points.

The reason for this to be added it to increase visibility of current combo points while using resounding clarity. 

For example: When combo points 3, 4, and 5 are anima charged it is difficult to visualize current combo points when you have between 2 and 5 combo points. 

If there was a border glow around the anima charged combo points and ability to see bar color filled combo point count. It would be much easier to track.

Thank you.

**Comment by mrbuds** [comment]
First, please don't dismiss the issue template when you create a ticket.

What you are asking is already possible using conditions.
