### ISSUE TITLE
Brutal Projections

### ISSUE THREAD

**Issue by Wrangler4909** [WeakAuras/WeakAuras2#3409]
### Description

I could not get this specific aura to proc.  I the pic you can see that streamline works just fine but not the Brutal projections. 
Everything else seems to work ok on the Hunter Dynamic pack.  Thanks and GREAT auras!!

I havn't changed anything other than position and size.  Fresh out of the box. 

### WeakAuras Version

Weakauras 3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Visual bug*  Brutal projections is not showing up on my window when it procs.

### Screenshots

![2022-01-02 (4)](https://user-images.githubusercontent.com/96981184/147876027-b5d6fc5c-f973-4af2-be9d-ff66d4ae036d.png)

**Comment by BartStam** [comment]
Luxthos (which I assume you use) just made the aura wrong. Brutal _Projectiles_ is a buff on the player, not a debuff on the target.

You should leave a comment on the wago page rather than a ticket here. It's not a WeakAuras problem.
