### ISSUE TITLE
TSU: Trigger Update Text Updating For Every Clone Whenever One Updates

### ISSUE THREAD

**Issue by Aurokin** [WeakAuras/WeakAuras2#3412]
### Description

With a TSU when I'm using Trigger Update Text, the code runs for every clone even if their part of the state didn't update. For performance reasons I think it would be best if only the clones related to the update reprocessed but I understand if this is a difficult behavior to produce. I'm not sure if its intended but Buds thought it would be worth submitting a ticket.

As a side note if you have text running Every Frame, it runs even if that clone hides that text. I feel like this is probably intended / difficult to change but I thought I would bring it up.

### WeakAuras Version

3.7.3

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

No Lua Error

### Reproduction Steps

https://wago.io/yq1rVnPvX

I outlined the events to reproduce this behavior in the WAGO!

### Screenshots

https://i.imgur.com/NUtIicP.png

### Export String

!WA:2!nBvxUTTXw4QOgKyM0ghJ2uG8tVSQiPUTUYoo1oiXxharBjBLRILmfDKlsluhsouCQPgYoZqzlx0xeckYZEjON7tAjKvWbgfDb4h6ciRGodjJStIDFTxbiYZCMZC(578ZWCEt1Dk3P4M3R49lEVPCFX8S(1984yrowpmJtcP5hrOEHSUiHCH2qgUJ8Tv)i8lD7trDjoDyHXrhGOKurw0OlIqRyiKIyqdP4dDJzj70wXIXXoHux(amIJvQb0EPISPGHPDe(xWKlqmrfycqdUeCz4dKV)Wly7rOeU)BZ2mG0LiU0bCCGxJqcvmVv9gZhZcIUHVqeXF4SZUlQtyrs4S9)57YEkTrVTN9UhGyo1sS2ZV2GyoUMsj(JSdzUy2kHbHShNlxU8dtzu2Tdo6Qn)5yedRxjoiqVLprGzPrm2)quSWpKvpsfJCn2EzaOTYYvx9GXg2MHCjX8NFzBjc4r6OnFmXD0Qe3TRUGz0c8EzgSjzF85h6jT0keMta(hlqCJULvZT0TyKoDWm9TICLww3cZf6RPG)HIqNS81fBCTH8yBZK8ex7qBKZoUSWO04kF(8nYpxXfELeRWmkk4PPN6z2P22NjHFLnYzYJqo4ZFukFJmTenPraz)9rmxDRWWabjYK7GcW5FzQCPX(ehjJqPIOIkihriZ2S0Qv3QPnh3v6LM3T4CfNZGhYeG2ipgQRk7JeO8dyH72uzwfLiPOj3qv5cjdBLAtrSOHSAqObxrdMuBeI6iX)K0V9kL3WQSzwQSkv6l5h5ege3LMQxJGqKBfBH0LPIRz2nwgcAMobio)AWkAgCj2NseHDueMOashk8ObIuSNF97CqmnBHglJ43giLpiOQlxdMWejl4N3iw6I2rbO(Yig3tAo71XOaH)qxSDSNNQ2NTE5AnQSvTJKjSerAk3GS3O2RuQPv7MwLmTgVvdgwULzZgLRvZu24H5Ad6WiUk9uWC1du0TiUc)lzi7i31y16T24vPqtffeRKZU5kMLlVXu9(JTNY56V4RHZLtw9iciuzMBlRAv3OmKpp8(Ar6UeUY3TW7jAN2(3oQTG0fNTkNHxivenzfgzF9nJrUQeOULfCEdH8mWfweU4B3Tcx5D4m57WzkBJ6ww1Fc8rWhd3kh8TWcWn1GLwe(VzjC4Z0I(8Z2)IyyhsYKl4tH)JPZRR7ZhnPtmxe2vDM0oiOo8vpBWUYILwmu0GwzeqHrv2zLD69G79Gn3Coyz4rSFsEsIxFJALRynI7JCd394bfrF9z7nzdjBl8zyUFyGBF4lKTOW0AW9Zp6eNRWTDomvXFxAt0nFp4HAdp2LJ(lVyAs9)0FPMU8hXtF6wy0oLKLB8Iv5ztGQhHLs8L6cFmnro1pgweZO6fE3PiUNymsHLsoaM6M8oiu2AR3L3rFzDUSsN2PyAWnDHBZ1)g9B7M8OWm6Qk(2yAVIobYj(vDpbh5yabUyCITSKiYm6RHfkcPpMAUmFtANL0KM(i580q1DjojLZgLKlJUXPGW0mcq7u3okJWuLhCHsvadvdnSAYZYjpROEou2xHt7DE(LH1)W7av1Gh)NJsH(2(exmSlSjycpb2aMWoLp0eSG937C9hNv4ZOlJowm940JCH(YlRtjbNE(WdfWXlP)gO(4dJvhvLXABzwDT1kB2ERgRwYQC7MRxVvH3sH8NvyJqXRZPf(bzk7xgVzIa(H7kzkyX4zEJnC8r0oYYGtBVJtBYThN3wASm)6yQt6i)77ezWRsxzL0sC(FettFDkO6)pgmYkf5Fyl4PP3nWJM)mktMr)mJv5WVgqlTxxMR(4SrjnRPUi8)K3l6JD2bQhDv19U9WzdoEsOl(3FVSHvBNoSkV6Bu(KZ4BuGVh(HbQRluFztj1u5)(

**Comment by InfusOnWoW** [comment]
That's because you are creating new states, instead of updating a existing state.

**Comment by Aurokin** [comment]
Hi @InfusOnWoW 

I apologize I have updated my example, if i'm still misunderstanding something please let me know but it looks like even without replacing the state on Updated but updating it, the trigger update still happens for all parts of the state. https://wago.io/yq1rVnPvX

Even still should replacing one part of the state really trigger and update in every part of the state? I'd love to learn more TSUs are extremely useful and I enjoy using them

**Comment by InfusOnWoW** [comment]
There was indeed a bug, which is now fixed.
