### ISSUE TITLE
Load Option:  Legacy Loot enabled

### ISSUE THREAD

**Issue by peoii** [WeakAuras/WeakAuras2#3414]
**Is your feature request related to a problem? Please describe.**
There are a bevy of auras that I utilize for current content that simply have no need for when running old content for xmog.

**Describe the solution you'd like**
I'd like to see a load condition that checks if legacy loot is enabled, such that I could only have an aura set load if it is not enabled.
Another alternative would be to load based on specific expansions of content, but I fear this would be far harder and break with regards to timewalking/etc.

**Describe alternatives you've considered**
I realize for the M+ content, I can say that I only want it for challenge dungeons, and that's fine for those specific ones, but anything that is also loaded in a raid does not qualify under this.

**Additional context**
It's mostly a cosmetic thing, I get that, and probably doesn't impact many players, but at least I know I can see the value personally in not having the extra information that is meaningless in old content.

**Comment by InfusOnWoW** [comment]
That's not worth it for a load option. It would help too few people.
