### ISSUE TITLE
switching to german makes at least icons unfunctional, switching back doesn't help

### ISSUE THREAD

**Issue by Hacki1337** [WeakAuras/WeakAuras2#3415]
### Description

group didnt work after witching language to german (tested then) and back (tested after).
both tests didnt work.
when slice and dice is applied, rupture icon should glow but doesnt.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. use language english
2. use linked group
3. switch to german language (and restart client)
4. test group infight
5. switch to english language (and restart client)
6. test group infight

### Export String

!WA:2!TR1EWXX9DDV(IJIVmuKKFez1KMRUexBzhxRNXwnoo3jD6vLLK37KLFKeT7D3EAxR72DZU7PhgkXwfcI3GAOuAkVoGqa60YCqAlmmTbrP8U8LlbJ49ubtl)f)HhscbgQ573V)29Eijhx76z6mmCESUD)9(3V9ZNpFFSN0zB2vUZJ(yhTZMZ3CMMZS8dvoLA6zZ4yz3NvolNrcfk0eHo2r7E9uwoz0CI5xPDJXYzC5lR6KjsslRCEg2f9SspNMJRHLzlst)2Lvl4PB5mUThwGB4uIURxu8D8mZOz3uINTGQJwKbkKlxKP0n80kPAMg70ewgMEP6l(yjJl73HegxwBhLexlwysssHKDtRMtlKF5dB6Q5fYrnnpL9i76P64fovwdtdx9WXWV8cVKNJXmZGlZwpGJ)LpFXmAPkKnBYfT1Cgk(OtmWKJgZdVrwTGJAhl5ARLl3WzCdVUBHuAZPz6LaBTXcLMUVOjsoDIKrLtgRao4PSZPUOMJSPAEn3WYCttnKMAop9kDDchnSRYjMi(OJUsbt)LqyNfhpBwC1lDDCNR5yQM7SIJYlw0rBg8BAXjpJJvb7vC1YLLpHG7F)gzwprHuE508wmIS1mf0CwWFGkL1bxgj8Cu9udDDX56aur0iLkrFYXJpwSCwQzgiLhEgA6Tx58fWNJHJH7307fApSC6CQUU0vXCXtF6IuPTmZAmt4vfh4IPANfXnNmVkDdVIQPrEv6bqpqtdSQMQlTg0mNXtVbOLyMwMALZGhRulMMoKDC1WbnJ7sutP1g0BS8QgMdaNa7a0l8bHhhoj(DZBSKIu)meWRsgMzTCetC4okyKP0X1NBSzg0BYfnMT50)UlV)IgyZtyvWjT2dUn50by7qWJKBNqy4(lNgHXzSM3mX8g2AkRgClHu1JrDwb29x4aWEwExRwWvBAdZ0w5tP6PSoDNAkxlNuN2kJMs5z0m1CmsNq3A(Xnl6IFfn38Ql6cpCyyVWdGBHhYU5QDIaiChH3n8GLOYZBHadTm6qKI9vzlA3evvDJTszhSVji45y4d21tKZiTwevZmr6hVOm1E3GkvGwdVevcbuvGhcEpW(H33kujiej9SkRuPPTCpGo8Dfg3QzDW65EVcrfyCDRX6U9hRDAJugpUtRR5kwmLD5VoTHRRH5m4MCF8KWJZxM2ZWOkY2wZR50CxRZFpTf(0x1ZYz)pXj5fcxQcerEc6ciHYkCjekzNWW8IUCL2rLQWNN1nfWf3FhDdpfoKWtJdf8m4Wat3GF3bLGUukJH7LkyIsfZPLkDbxpR82nl(oPGtoQ1mgPTpywUrwMh0NQEOWoAEfCQC)fB)PpuynZm2nPYdMFVPNOFQTbh4IxFwnn7OeNYtMGN6WHG7hvCCv9iAGMo8yHtPRzmJU3fHpWC8bbt8u4lnrvd8m5ye7Bj)NOPvGopqk6yoNMS84dozCSsOJda5AGUOlQTW7hg0E3bG4KAl41VHRAQCiSAPGsvGd)pS9yx2YkVeCVHHDqY2OIIDJ1dKI0b0Dy4iHKN3iJN(fLvZzRRoX9CSJIh0rln0exk2q9pspto3aogMKba8XYJchfAefacd7km0Cy4uTDazeQKE2EG9CKTT0CQog0APJOJ1FkUC32WAAaMpgHIKNtnxbTqyj7eMhUm8DhYjTUQ5mi47a4nlz7qihVfb3daZXJi2SfGfhbVoKFpWl3r1lBO6Lbdj89qd2iSTTQ)je8HH(HNmmCCs(IvBqrNajONytL08glz59d99GBd6VoTfiUcmGomiQG8UqS6BYSJPcteEsu48WfqK67LiKfj6z8fmC9C1zaBRHDWNuJBMBrLRJp(JVaIYsimiPSkrkzARrg3wt1z7D39X7coRUpeheaqild5GzqKwBlVB7M9qWW0U6Qie4C(glS3hxi)hHo60U(xa9UsL62)J4A3ynDVQH41fLgyzkw0jtoU9U4cr)aSiH50trWNyrXBVUyImwqldx4vllSpDE)LZQC9xczJgzxezlowEitHaXXgB8XIdT4GwCO2uKByvX8v83bME2nIWXlh5mfuZqwaJKmzDB8GzQmx28O1SPCuTxAk)lelG5mCnquQI)EUgFtSBA4XglU80XgpzYXpT8WdouYYvMAYvL95VJoxDZdvl7LX4tMC0Hhl(1kptoR5hWr7zlOzMErFofV7Okkr)jyewIUH6C5uf88SmhhPAO7gfPIhLTVUhU9b7SvOBQ4cxiYM1GbLOhJQuNBsc2dkEHKu3i9SMAUUH4Ag1aVUjEcIjCEd0rjQSGHVEemljeb5G8BT(dyQdwOiZNAhGDDkmRJEQ5PA6fbpmDTmj5f3qSOXrcHskNy8H7yS5p4IZn3hckOdoxSETKWFlXpFFm)8WdDQdUn(d8ipEdBGJ(53riYoFJmb8SkKvLPAZjHh7jxrYFlnNSfMrJiS1yLbzYOHMwdt2AicoXUv2stun3f8un)41AGANBYafTcAcgxbgzDHL1(8vTPMXwcqjXmIw3ImRcqJ97E7qKRJpOtPMlsLEmHeiRatkvs44IVinoV4KMub2)29NVDXZh8B6BZ0FT0cuchzHllOh1ZO5jJawdhnC2zdTrkhLnrgzs2cJ9UOwQrkv16)XeTS9x)z41bFbTzftpEmu58Pe8kk0Iic8z5wmXsuahiyjf1tA1qlVpNo1VjNLe5uHuqA7p23eMPzdAb32r932z9321thXYjIPLxTw5RTfrUfdq3cNc2OeSclbdFej47drLF)OEk88S(j8dald)GWpe8dFv4hrc(rXg)Jb)44bYpb8tkmLSc8rHxqc(PGpg8tRaFC4Nb(e7dErj4tc)Sxd(5cKoGFE4xqc(fHIWV0EGFzj4xr05xsh(v1HFTqWlhc(1Bc(nqM8ddFGZcxkGj3j)3o2B983OLoVnkpeFKyooxWNYTbVYFIBTF6eDfjTcoCZmngLdc0cKhYWls7Obt(ya5)oE3hPgGAci3N0eUx2znk2QHrVWBPHx75b0lkt9L7CjlHiO7iJeAOt9c7M)m0P(8TWFcnsiCiPAEz((hqCZYb3WcbOQKVaqzxBvNzLjtniosYUP6UN8Ndw(6uSXuuyMzQy7J9Biq04Li9IPAd(0WNjWKoPiqsbeCgLiiLHkm8RDtKeO2k0esOy3k72hQb0NoX(WzoFkl2mKRsD6fFwMaXSNFlb7rQwwZVnZ2Mu6DGTfqrRq0eDHl(M3Rz3IUuLBc)oGwdC0x1yOMifiJyPuQ(rZp0P(3Fg(dEX3G(CdSrOllhj0Q8ZbHvTZlbpwV7fAPe55d23PX)V8dy)E3K3l2t7zKhJuWrlTbfgDiISzFBr2(KXgddwfEbeK8I(8oD4Jxuy4F04dK0(9CZMwXDBLxv2(xitTldsHTp0nBqYSigVLr6P90D0WN(5YSi8rcrIh8EX82t4a3eb7GsIDa70cQE8hj0r2I1QzfpaVLQfRZpJILdL8iIshr7VF7gryB0mKtCAz0YCA1f0lYTI94BpWG61PiCyP1DZBz5PpHJ1m4g2vzJdGb6nX73X)bFTGIZjHIfRWamxJmyer8odLyqLKs(kePZzyR4q7UcoAfXXYiVAo0l7RhOGKuu1iWFV4FIjWVu7domLvMSQP1EQ(urVsnNjMQZtn5WpA17E0eSCb3n9kQBRqQB0JtNsCndzKjJMP8yXpBCzFFE8RGJa8KIJOQUTbfuqv4EgWzSbgpJ6WdAuYYXqZuOjvCOXLh(cJpwYOJwNxr3(s0l3ouEpW1KQ4m0xqc(IiWcFiXrSiCDHuXeoSSAfjjlxp29fuKZpNcKixfvj2a4QvO83PRVy0toD4pyePqsSSWxYxia(dx(bGV8Dc7gb(1sTjtQ)XWFIe8Nc)zeJ4p)UbBJg0)IQCm4R4tLMJCHEwF2uroIFrUKU5Ut)xca8xPdFvyD2tIAPoVMc86i1a(Rrsezp7VbwJSEIeG)Ltc)DlfKNweh1TDHSh)Gx(e90rpW)i8pb)ZvbQRYwvIimRWMDDfMIrlY)R(qrD2I5xd(6(OTxTI5pFVQdI6DOxn1x8gVk5CD9owZPpRLLm80Yt(ekbdPe4X5dhwyTdn2qPF6v0dSmsGoclHilrE387Sc5f4eWziBpTgMZleNGvrEHIaJX4r0u0P9tM1YnMcBKSwEfkezQsmcCcVge(TVXzAcr08vuk5OLFC)uu18J3bExZDcxTv4C15HoUQ)30dmyxXJ5Qg1zhKrsdoKjyFDPX3NMChL5kFRQOVL7ydr3hMJpJbxxsVc(6DoeTUfoMDwNmwtZbfYbroTih6WL5ab580cf5ibNMtRCPyj7kghgA7DE9QfZnS8aYrpD8eXhnEFjhxM4Y)h6WBethLMH3g(VG3c(pjul5uyV1N)M2ENYudLzg3EUZZ3tQCgMZsjvLhTb4LYBI(j)gyTVLDltPPoBukDk9wFYVGp8Q0(dLF4SYxDbVFCVTyVvNwPQtRu1PvsmD9Wt3Ba)34U))b3iFdkZBu4Xb0pehJmxxF34XiEjgy0sJiF6H0o05J1tpJt0pKlIS6FVw2(9uMCb(owTVsmWngedCaJvARdfEp1WujSlHe5OCRqrjMR3ImVJ4LoYfSjlNc2j5WOV7V1qiVgXdz(05xveIBuodQmz0NFI9OvblLMKROuV7ZFnXieR9t0vNuL1WKFOuIqvd8a)5uOHlGFVxNHIkF6bMC0k04NMPXIqXRNftTVwwmnG0QJy3dRCxGg3WDbAC0sUDoO7GtKR78NzsckHWJTIETZQeJ7FZ0R6B)fUDOxBAa3idRPQmSaSbYd2aFAKBjFQ68SzQ1As3lZT8ndvd9AnPTjSPvLGDKGqmrgfRaYYu4atlzwNQgrUU4CpXkz4S0qLPKOIFL7cPJIIcDROGIfMy2eRSAxvDtRhF9vCXWl61KUpATgqC39wqC9XPVcJDNSLqB71yAlHZNOy85mCtt28cOU(42ek1tDdysNFnjPkr6YKzrwRPXEkYkA18rxLWUM02z6AqFj(6AO3vBnxDnP7zd0uQD3sRTcpk81M20RIcPPDE7rtdD3XAlQQEtm99TpU5URYnR55)DF6zyMEEhNhPAYA0As7mGMFerMJrkD0s25Do4LoR1zo48Dru7a6oQeqm1VePkE4HEYbUY2jRE1W920RPrqFePNzibkAyHxLjeid)4DqGKVVCvCZC3WuTMQ9J3DxD0bZ8kjSTjRPIrWJn87vWhoBvpbForUu(CCosFTVQpX78WhIt2YKCzj3agEF0uF1Et1E7D3(jApv7h74DCSJttBNT3zWs1p91t1g8zwnb)ApI0VQj6tdzNe3hx5BLKtxtYM8tdKDJNgJDvltKSwor6xtfdytKT399rRj)tBKwvjbP3PsObVyRVDLv1xoeLyv)SQE79(rq5alfeAg6t8wWHFfcFtIlvX4nvdgVIpHlCMf6AIrAFWrVG3gW4NQnMVIupIbImvMbQGKU4B(fLEBiz0MyuOFMhhTJJsUdJfis7jkmrYz18(ziwL0wtQ(01MXZAOubgMeHi57O4qkBGs1r7D0XX7KPuRj9DCZzs27l49Eejixsroi)ktpKGIf6KFWnrXOYQLI9Mvnt09X8ntOZV(KmAznst)eksOy3O)n1(lzWXVmQF(0g0ScrLu()b)Bj4)V1goS39Tr0VDJjwmFkRCUrSY6RMSfKbTNDUEgCo7zD6)z3izO3Bbzyh1zsScCEZ2L3cMsLbBnPDVf4)A9O7u34g3yRsdsZecNSu05J1t7NGqUeaMG0K)oI36OiHBJreHHzalbkt474e7Xuq0hV0gYlVWwck8k7txsgOeVX37aHUp5j3Qx8a87RxNI)ZlyB6Wu9sVFdsE6Q9UM07AnPVZ1KAKTjrgwUsan6)RcZjhi22tsHnZE)vu8ErPFcDi0hX57Yh9xbZxLgSfO)xCuYLKSxzBhNC9FtMaAoa1haTzFDWLWZ92Cc2IwQVE0hn1zMBWb1Ytzl(iCGpNQ16XX9(nXVhM2QNgS1W7MN71p3)l

**Comment by mrbuds** [comment]
Could you test with only weakauras addon enable, and report Lua errors using Bugsack+Buggrabber, it may save us from installing german language.

**Comment by InfusOnWoW** [comment]
You are better off asking the author of the WeakAuras. It's rather unlikely that this shows a WeakAuras bug.

Looking at the auras I can already see several defects:
* Several auras use non-localized names for their buff checks, e.g. Hit 1
* Glows are applied via "Glow External Element" instead of using a glow subelement.
* I believe the spell id for Slice and Dice is simply wrong.

**Comment by Hacki1337** [comment]
Hit 1 isn't even used, it's just legacy. Three items use the external glow function, which worked before switching languages. Looked the spell ID up on 5 other sites now.. Every site I found refers to it as 5171. The external glow might be the problem though. What doesn't mean this problem is wanted behavior, does it? --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 08.01.22, 23:20 schrieb InfusOnWoW ***@***.***>:

   
  You are better off asking the author of the WeakAuras. It's rather unlikely that this shows a WeakAuras bug. 
  Looking at the auras I can already see several defects: 
   
   Several auras use non-localized names for their buff checks, e.g. Hit 1 
   Glows are applied via "Glow External Element" instead of using a glow subelement. 
   I believe the spell id for Slice and Dice is simply wrong.

**Comment by InfusOnWoW** [comment]
This isn't a help forum for random weakauras that someone created. We are only interested if there is a bug in the addon itself.

I have looked at your case for a few minutes and have concluded that there is no indication that this is a genuine bug in the addon. If you disagree, then you have to much more clearly show why you believe that this is a bug in the addon, and not how the auras are setup.

**Comment by Hacki1337** [comment]
I know.And my Auras worked..But when switching languages, even with spell ID setup there seems to be a problem, that Auras, that DID work, do not work any longer.And in the WeakAuras interface there will be English and german mixed inconsistently, so that leads me to the conclusion, that WeakAuras itself has a problem.Ill give you some Screenshots when I'm on in WOW next time. Am 09.01.22, 14:45 schrieb InfusOnWoW ***@***.***>:

   
  This isn't a help forum for random weakauras that someone created. We are only interested if there is a bug in the addon itself. 
  I have looked at your case for a few minutes and have concluded that there is no indication that this is a genuine bug in the addon. If you disagree, then you have to much more clearly show why you believe that this is a bug in the addon, and not how the auras are setup.
