### ISSUE TITLE
Link aura in chat having a name with "[" or "]"

### ISSUE THREAD

**Issue by Ucyt** [WeakAuras/WeakAuras2#3417]
### Description

I linked my auras in the chat for a friend. The name was "Holy Paladin [ENG]", but it did not work until i renamed it as "Holy Paladin Buffs", seems to fail when it has that symbols.

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [x] No

### Reproduction Steps

1. Typed "/wa" in the chat.
2. Opened the chat.
3. Shift + left clicked the group.
4. Pressed enter to send the link to the group in the chat.

### Screenshots

With the symbols: https://gyazo.com/cf9cdf770f224e59b40c8f7e6fdad7f2
Without the symbols: https://gyazo.com/4b8bb10edc5e7a1af84e7fe99fc29718

**Comment by InfusOnWoW** [comment]
That has already been fixed for the next release.
