### ISSUE TITLE
The "Creating Button" sticks to 365/393 and doesn't change whenever I reload the game

### ISSUE THREAD

**Issue by JerryMMo** [WeakAuras/WeakAuras2#3426]
### Description

The "Creating Button" sticks to 365/393 and doesn't change whenever I reload the game, it happened for many versions of WeakAuras...At least 3.7.x has this problem
![unknown](https://user-images.githubusercontent.com/32919869/149279777-52cd8f4f-6381-49b0-a401-dd0b6ec16a33.png)

### WeakAuras Version

WeakAuras 3.7.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

![lua error](https://user-images.githubusercontent.com/32919869/149280006-05feb592-edaa-49c7-8844-b186f1840dfe.png)
Like this

### Reproduction Steps

1.Go to World of Warcraft, find \_retail_\interface\addons\WeakAuras\WeakAuras.lua;
2.Open it with text editor, then select all and copy and paste to Visual Studio, find line 2369, replace this snippet 
`elseif option.type == "select" then
          if value < 1 or value > #option.values then
            config[key] = option.default
          end`
to
`elseif option.type == "select" and type(option.values) == "table" the
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/7860618/WeakAuras.zip)
n
          if value < 1 or value > #option.values then
            config[key] = option.default
          end`

from line 2368 to 2371

**Comment by JerryMMo** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/7860630/WeakAuras.zip)

**Comment by mrbuds** [comment]
Neither @emptyrivers or me were able to reproduce your problem using your data.
You have many errors in Bugsacks before that one and you solved your issue, so i'm gonna call it closed.
