### ISSUE TITLE
Bug when opening LFG

### ISSUE THREAD

**Issue by SUU09** [WeakAuras/WeakAuras2#3428]
### Description

I get this bug when opening lfg

### WeakAuras Version

3.7.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [x] Yes
- [ ] No

### Lua Error

2x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:3508: in function <FrameXML\LFGList.lua:3499>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML\LFGList.lua"]:2576: in function <FrameXML\LFGList.lua:2573>
[string "=[C]"]: ?

### Reproduction Steps

Just open lfg

**Comment by Stanzilla** [comment]
That looks like a bug in one of your auras. Do you have the RIO filter aura installed?

**Comment by mrbuds** [comment]
WeakAuras addon does not make any call to GetPlaystyleString function.
