### ISSUE TITLE
Range check default trigger

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#343]
Just requesting the addition of a default trigger to check the range of a unit from the player using the given items found in the wiki, having the user select a target they would like to check and given then give them a list of ranges based on the two lists for friendly units and hostile units. The trigger should probably allow the user to pick if they would like it to return true if the item is out of range or in range by using a > and < operator.

**Comment by InfusOnWoW** [comment]
The latest alpha has that now.
