### ISSUE TITLE
PLAYER_SPECIALIZATION_CHANGED doesn't accept units

### ISSUE THREAD

**Issue by Ironii** [WeakAuras/WeakAuras2#3432]
### Description

PLAYER_SPECIALIZATION_CHANGED:player is treated as custom event instead of PLAYER_SPECIALIZATION_CHANGED event with player as unit, excepted behaviour would be similar to UNIT_AURA:player etc

### WeakAuras Version

3.7.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

-

### Export String

!WA:2!1nvWUTTrq0iOdbGiinrjWOjThestAsraYbNwBGEjwuLSsfmsQu0Xj5cXsUdf3yQDxS7szjFuOhYz)jOZ5K(eYxaHqq)a8NGV1BziPCqrq8EzNzWm7BM382gUTM2I2I((hPe5MmghudpmWR)ah18HjjAW0q(uktlZilcG5MWeHAkXekdnSPqiDbNmLfhAsvGovKrxSrNsOItEtDX)41wt4XPc1ibJBI66miWXx2(QFWAVgYBfNRnIPLzCOKsmGpmd4MZj5yuIHfFeJAsT7GUksSHj46981gIYyfLW4mDQLnEzSwAuSjtaL(M)SAR5)ABwiHOAewxFfwfcFatUEffIYtscWiQEoEJCp0RWkQhqYmPNRZJQ6KrkiHn3F8ihpp7CePOYjcu(iHaAR6K0YhoYRZBC8dX862VJx)32jO)WbHD71zWF68h)EDnF5rhJWYMVoSBNXbHJd64h4hNcXhxyTulHSS(uTvXDLpmjNxnZpPQQFXQnEKkKHVmaWPxoyPmk4xYT0ZY5Bzal5TljTzqqT)lfu4dxt(dFZ9sTrXJVaFFqXjzVczteCYzAilPEXApmiy4lTteCJ8wUk2PT)7CcvrmK2bbRWXZhMuUJU)of3zd6grIpEcQ44u7mbH6gzizyJVJ)08mdZYgN24Dk(vl)4mIwxAzRzNcLgllbzm6CVTsTxxl1AUsvHr5AZ2GtWQybNYQKgwYF6QLCsfeZkhOMNr4SsXLGVxXnD)iq0WyJc4tmPxV4o2Cbh2qZvvzujyuAOee9YYulbU4a7Peg3T4fybfhu0PWUOlE)DFDKLNiu0Jue5YJ2AOEhUVyjlS9CCdwzeXZQP5VVr4)9agD3bWjR)FdXdEKCDIc1AyhI0CZlQ)N5wgQStIg313Xzqe2FjSjw7MZORLP573lEIZ(U5QfB)D7hlYeQ)QjEwxZNDRc0OrJMRqXiqR(P9p3ynJxZBypzTb)hIOnuwtVT0(p)z7)SFR1Sp96pd

**Comment by mrbuds** [comment]
Compiled a list of unit events not starting with UNIT_ from wowpedia
https://docs.google.com/spreadsheets/d/1f6R0cwTaK_SO0IykWW-lhN4KQi_6AU-4mKkaGUBS3Bw/edit?usp=sharing
