### ISSUE TITLE
Issue with desaturate on CD

### ISSUE THREAD

**Issue by Renacion** [WeakAuras/WeakAuras2#344]
I've made a weakaura for tracking Spatial Rift for my Void Elf. I have it set up to display the icon in colour whenever it is available, and to become desaturated whenever it is on CD. 

It works fine except for one reason; it's almost always desaturated. Sometimes colour returns to it, but it's generally desaturated even if it's not on CD.

I've tried disabling other addons except for WA and I'm using the current version of WA.

I'd also like to set the WA to load if my character is a Void Elf which is not underneath the player race load options.

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  dWt6eaGAjj16LuyxsQSnjLMPKinBu9nLIUPuOFjfCBP0PjStj2lSBQA)Kk(PsvdJs9Bu(mrnuLsgmr0WPKdkjLtjjHJrkNtPuluQyPsQAXKkTCkEOuPNI8yr1ZfzIss0uPYKfLPR6Iss1vLKKNreUUI2OsfJssu2mPQTRK(RKW6Kevttk67kyCkv6WKmAPQXRqDjjrCljfDnfY5jsxwyzkXRvkm0GdKafTnxAAB3euc0sDJQRjOwqzGYGd0JXxBhM)KOgbkAJajDVE9P4OuZLDTbPYVynCgHSCyAKLfOutnBqtdhu)VvQYBOHbLmRobRHosRQg5jPvAJnOb6gHSCyGdeBWV3ZLIoGMPOIPxC0buYk48IQnqzzuTB3CxqxQvakD1NjqZuurQNnS3JoGI1WFqDzmEgBWRJKBzyYMiL0rYkJScoVkazcfNScoVOAdqKL6cfxhjRxO)GMPOIKvW5fvBGoGMPOcLUjMr3gzzb6ak1Zg27bL6zdvJpOKMan9XA4pi18mqEvBKGdfnqKL6cfxhjRxO)44GSmmztKsBzICrsW8Oyd6X4RTft4pOUvV4QE9G6dHC)rrIrG4mvgCGeEzdBAbhO2j)c4WXbDfp8hoqTt(fWHJdktOxViFYVu4a1o5xahooiJkpGdu7KFbC44G0RYVG5Hdu7KFbC44GSwTUIh(dhO2j)c4WXbDfp8FboqTt(fWHJdYW4bCGAN8lGdhhh0JXxBhM)GwSTxa9y816Y4mdCOSGInksGIDD2lsmAz7MAABwBZnTRfhKjKfmVtQvasKZ8G8ZwNrilhMekAGgVxV(uCuwSTbn93iKLddCGs9SH9EqPE2q14dkPjqjRGZlQ2aLLr1UDZDXbniYEpksmc0JXxduLybsVr1g0nQRqrcqImqKL6cfxhjRxO)6iz3QeuMiv1tF(fRbifNds4fVI0vMhzOObkN5ZexW8j4qrdoq59r(gWb6gHSCyqXg0QYiu6YdqmFxgJNXg8Gwv8zGIgoO8ELxosWHIgCGwv8zGoGSmmRWCPGYIK6tJ6boooklWbkVpY3aoq3iKLddk2GwvgHsxEaI57Yy8m2Gh0QIpduSXbL3R8Yrcou0GdKLHzfMlf0JXxBhM)KOgboooksahO8(iFd4aDJqwomOydAvzekD5biMVlJXZydEqRk(mqXghuEVYlhj4qrdoqwgMvyUuqzrs9Pr9ahhhhuoJXZydE0bh0kkAnx0Wba```

Thanks for any assistance =)

**Comment by InfusOnWoW** [comment]
The problem is not the spell. The problem is that you are setting the text size to 0. That causes a error.

You dont't need to set the text size at all. If the spell is not on cooldown %p doesn't show any text.
