### ISSUE TITLE
Protect WeakAuras from custom code creating protected frames

### ISSUE THREAD

**Issue by InfusOnWoW** [WeakAuras/WeakAuras2#3440]
We do have quite a few users that are unwise enough to use WeakAuras to create SecureActionButtonTemplate frames. This is obviously unwise.

There are two separate problems here:
* Clones being poisend
* Auras, that is main regions, being poisenend

We probably should:
For clones, check if the frame IsProtected() before adding them back to the clonePool. If a protected frame is returned, we need to drop the frame and complain via both a chat message and a warning triangle in the options.

For stand-alone auras, we can be a tiny bit more lenient and skip the chat message, while still showing a warning icon in the options.

**Comment by Hekili** [comment]
FWIW, I did search for clickable before adding my feature request ticket, but I agree with the merge.

It's also an option to co-opt creation of clickable frames using a Sub-Element and define these safeguards around that usage, and/or block creation of SecureActionButtonTemplate frames within WA2.
