### ISSUE TITLE
Generic Trigger

### ISSUE THREAD

**Issue by OttoDeFe** [WeakAuras/WeakAuras2#3442]
### Description

Logged in

### WeakAuras Version

3.7.6-4-gd1930c4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

4x WeakAuras\GenericTrigger.lua:3537: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:3216: in function <WeakAuras\WeakAuras.lua:3198>
[string "=(tail call)"]: ?
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:3302: in function `GetOverlayInfo'
[string "@WeakAuras\RegionTypes\AuraBar.lua"]:138: in function `propertiesFunction'
[string "@WeakAuras\Conditions.lua"]:418: in function `?'
[string "@WeakAuras\Modernize.lua"]:1354: in function `Modernize'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2547: in function <WeakAuras\WeakAuras.lua:2529>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2706: in function `Add'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2237: in function `load'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:2244: in function `AddMany'
[string "@WeakAuras\WeakAuras-3.7.6-3-gb17fa48.lua"]:1033: in function <WeakAuras\WeakAuras.lua:1005>

### Reproduction Steps

Just happens on log in

**Comment by InfusOnWoW** [comment]
With the limited amount of information you choose to provide, my best guess would be that this is fixed in the latest alpha.
