### ISSUE TITLE
New update deleted all conditions

### ISSUE THREAD

**Issue by Sarux** [WeakAuras/WeakAuras2#3444]
### Description

After todays update to a new weakaura version most of my conditions for installed / or new weakauras are broken.
Already tried to delete old weakaura and get new ones on wago.io. But the result is the same -> conditions broken.
Downgrade to older version & re-download weakaura from wago.io fixxed the issue. 
You need to download weakauras from wago.io again because all imported weakauras are broken.

### WeakAuras Version

WeakAuras 3.7.6

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1, Update WeakAuras
2. Conditions gone

### Last Good Version

WeakAuras 3.7.3 or 3.7.4

### Screenshots

![raw](https://user-images.githubusercontent.com/20129099/150643583-86b4c95a-bde2-4991-8a36-7dfd83c213e4.png)

**Comment by InfusOnWoW** [comment]
Downgrade to 3.7.5. and choose the repair option. We pulled that release a few days ago.

**Comment by Simon3** [comment]
@InfusOnWoW if we are affected by this bug (currently using version 3.7.6), can we upgrade to 3.7.7, or should we first downgrade to 3.7.5 and run a repair?

**Comment by InfusOnWoW** [comment]
Technically downgrade to 3.7.5 and then upgrade is the slightly safer option.

Since the 3.7.7 upgrade has to employ a heuristic to undo the damage of 3.7.6.
