### ISSUE TITLE
Automatic Repair Comfirmation Dialog

### ISSUE THREAD

**Issue by hizuro** [WeakAuras/WeakAuras2#3447]
### Description

I was surpised and irritated by a StaticPopupDialog on login with imprecise text 'Automatic Repair Comfirmation Dialog'. A search over all my installed addons pointed to Weakaura and why it called for repair. It should have a more accurate description to avoid confusion.

Greetings Hizuro

### WeakAuras Version

Weakauras 3.7.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

1. Login on a character
2. See StaticPopupDialog Frame with following text 'Automatic Repair Confirmation Dialog'.

**Comment by InfusOnWoW** [comment]
You are apparently using a broken installation where the text is not properly localized.

**Comment by InfusOnWoW** [comment]
Or you are using a locale where the text has not been translated.

**Comment by hizuro** [comment]
Okay. i've checked it again.
`
esMX.lua:209:L["Automatic Repair Confirmation Dialog"] = "Automatic Repair Confirmation Dialog"
deDE.lua:214:L["Automatic Repair Confirmation Dialog"] = "Automatic Repair Confirmation Dialog"
zhTW.lua:156:L["Automatic Repair Confirmation Dialog"] = "自訂修復確認對話框"
koKR.lua:168:L["Automatic Repair Confirmation Dialog"] = "Automatic Repair Confirmation Dialog"
frFR.lua:194:L["Automatic Repair Confirmation Dialog"] = "Automatic Repair Confirmation Dialog"
ruRU.lua:161:L["Automatic Repair Confirmation Dialog"] = [=[WeakAuras обнаружил использование более ранней версии аддона (осуществлен downgrade). Ваши индикации могут больше не работать надлежащим образом.
enUS.lua:154:L["Automatic Repair Confirmation Dialog"] = "Automatic Repair Confirmation Dialog"
enUS.lua:1174:L["Automatic Repair Confirmation Dialog"] = [[
zhCN.lua:155:L["Automatic Repair Confirmation Dialog"] = "自动修复确认对话框"
esES.lua:203:L["Automatic Repair Confirmation Dialog"] = "Automatic Repair Confirmation Dialog"
ptBR.lua:179:L["Automatic Repair Confirmation Dialog"] = "Diálogo de confirmação de reparo automático"
itIT.lua:198:L["Automatic Repair Confirmation Dialog"] = "Automatic Repair Confirmation Dialog"
`
It would be better if the detailed version were copied to the localization tool on curseforge. i could not replaced it because it is locked. zhTW, zhCN and ptBR looks like wrong translated.
