### ISSUE TITLE
Specific spell in trigger doesn't work after last patches

### ISSUE THREAD

**Issue by Firehex12** [WeakAuras/WeakAuras2#3448]
### Description

I made aura for priest to see specific casting bar with 2 ticks when cast Mind Flay **only**. 
Now it doesn't work. I managed to fix it only after removed specific spell name from trigger and set for all channel spells.

### WeakAuras Version

WeakAuras 3.7.7-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Go to Mind flay aura
2. Go to trigger
3. Check Spell, write Mind Flay
4. Give it a try on mob - nothing appears.
5. Remove spell filter - it works

### Last Good Version

It was working, but don't remember when last time. 1 or 2 patches ago

### Screenshots

![WoWScrnShot_012422_202529](https://user-images.githubusercontent.com/64840769/150833330-703699cb-39b9-4c5d-859c-df73fa922ec3.jpg)

### Export String

!WA:2!DEvtSTXXvyXWc4a5dMw21jgXPGvWkvQTrQsg1g1PPoCPOeznnj7YL(Nu3Yz)zi3XA5SdMzx93LcZK0QMMu3q3d9mrp2tSb9CHqVwGPS5EbecqVl0B9G7BMDPOLHZLUhOM38EZ8(EV59NYSXC9MZBoVd(rdfmB(w3J4f5)1hsCdPndJ5U4RmJHDCuiIVB9oDe4OY)1coVYmW3roHCpm3W2DlpEiZOwifp0nwef2ZcVBeRCNyQBejKU4sZYXrXCAEreNq7UCNqEp7OfNFHLxRZclmF(VBlkjQjdheu2weHxCEwG9Ey(8lT07mlM6X3BIMd)KBLh08iBQRFiVriHg5uSunRsMhQbFIC3))ogqmiqDMs9IzhRzAggzROZWYnfLTyE2ryNy9FwlMhWUIFuetCZvwzh7UHltcxHVk)b067yT5kRUg3wBrIRBkIS5rZAqaK)woj3hBHIa8bd0WMVb3Uh(MTOCCxcys8cbbL2gtJelU0aVW2jha50boVWF2(GFPBxmxu7T4Plp41pmwGB7c3O1EmmIlu(NkEVQ735yfdHF4ovbmtD3ZNDE1o4DbW1ovm)XDXumN42eKRo9qH(pfa0Vn(irSdwbMgCChYUMnBuQA1bATfyleObSWDW8iqRVXy1UNqIg6bUQoDuaIxUu1gB0QQHIHrm4g4Xu9TkZAsbJxmBF1HvCqMAggk3tFVyU(zyUv7pX44U(2ukoyK2WsnG(PlGNp12CCpBWzr76Fc8BcqHS7O2fl00QDtRcMwhPK02reYDUtOhgj)2ojHsMAlZPHzLsnTgettDYZoYJiEKomDB8A2bbSZBRxBLWxDj)Pz0jdTDddc5)4SW3XqyhMtTdUl8IbwcMD(tfGPoLrHww1hytj90BDD5f3qUKbfe(qSTa3mIJPDJ8pZ4jUJ2k)ixGbv5j6RKr5zKLmuMnCwzj5gNrUPSSScS8YV4oh7KMgwHUbpKg5BOaTFFhBErnWlFR)8f0FLV1HZP)kFR)9o6VSWZQWosbeS)GoWP3iWURGxVLv1k1k98PwpiZqW7Bcb1qsWhFj5sJbsLQ7YdJPEPBa534Kno41yFJiinRT(NK8(2S2rKE4uQmdoH)AlWYZU8lr8KfMQt5DKMLah0rN(llYUGEhvnkLV2vxaZOaqECYTq2f7P38XJtQB8GeBjZHA(pcsfjD2tE2HC17hwvvWOw9ALKlXbBrjZqTGtdagKcpAel3gCY(5)jX2EG3ZoVLflxca9T9c3jX1NjtMSS5EUTtbWvMjfq3pfqJ1YSduw9ECBw)7LUy8jQths0ivfpxrWrvQvRKzBZkBw2kXQ2Miioby0P0BQEYo9cBs2h)MSL(QEI82dYKjUTJ85yOcsG3ESV5xLSmo2LOshYEWfFjVI00fqu7Dxl)cuzhTFr((YIYFQ8HYF2JL)8mY2YZkrsBi42r6Q91spjw29kZijYhj3s2qgmmXyRwAdljfjzVP0pJme0k8ZlrXINtXZVG4)F9oQsX61AN0UjvRu02Js6c2waEYZmoLi5Pzni5BYoHPHCPKUtcmAK97T83pTt6jpAtUtShudA18nGi4a5sduPAAghK7yiqFR2GSuV29GYnRvy91tJxbghQ5M2VotISpxkol3jjlTd0LH8psltKp8lflezhQPNgXRRmR8QXC48xqZfQS6I7b1H1iyqHOgqHCGmr7tSLJoTSZF9RNWp9YylwrvmTdW(Ht7E(WwvE7PuVDtvbOKJLokqMrAQe0FTeIEeopK7pwtWN0S)GCYhl7dpSFG8dZi)iF5Vej)vzLhK8i)R9LFS83i)eK8tN)Axt(7Yi)TYNi)S3voWx(0mo(ysx)OYV379SN9VE2ZE2GPLDoRrqOT3bNxnpduPJDjZEXbrKz1Trv9b5(S5oPLkeq4PAS56BWddWxs(hM1qfWOwO7UPAyYX2b985r2GvfTMI1Gt2Eyz4x10tBHDsei5oGRuTyOhbAf6ciypfPYDQmE9DW2Mn9ehDA4aBDWB8FohYlh6lZH(fOhJ(i0xlh6dZH(m0)eDXCOFFo0fVk6Q5q)XCOpf955qFa6lph6VLd9e0)afLd93rFX5qpfzDvK8MWL9xCk3sLEG43RGPzL6WIgfQwy9k1qY3bnA9sfSkF7AQQuAjQwV4Tv7EN61spNPz9nBvczUUzRkRJmag3g50SCH7uOgYag(s7X47dTrHbdELJ0DMmuzbQEUY(SCGZSGNQKo2d7Dh7D9nGaFx2pSrStazRVLiVG0JfGZRg9ipKFMFhS9w5THeJLZ)Id(Xwj5uhpTbxXtL3Y3ozaGlpEs33ItYysYRfQyX9wpTfpm5sVWWi)g8WUq9uH)lcxc1Fix3BvpvKcvtlHK2yhTwmXBu5hTATBS)pahV0Md0tNiiWmhQsIocCpawMRUmaaZDu99SYns7OkRJMFxEAQ34gbq1aUvcLPDaZ3oRX(HH9YyQL3FyuOBQj(QnET0lH45HPM1kD3jdDNEbYNmQJAOxy0gOty2JtQbQNdwznonlAwQuT5jEda70lpmIXEoaY7q6olKePud2pzq91tkvH9hfYjqGR25nSCDZkVF9AwfQounJejz0(reAs5Dv4o71jDPWShPZ9Rh4UKQOGaL8p3CYZt25eMxB5BS8nMB7V4()V

**Comment by mrbuds** [comment]
When i import your aura the "Spell" filter is not checked
![image](https://user-images.githubusercontent.com/189656/150836268-4fe246eb-72dd-4898-b1a5-ecb5490a64d0.png)

**Comment by mrbuds** [comment]
I can't reproduce any issue with this trigger, you can safely remove the cast type and class filters, and remove all the filters you added in the "Load" tab

**Comment by Firehex12** [comment]
Point was it didn't work with "Spell" filter checked, only when it's not.

**Comment by Translitdk** [comment]
Prototypes.lua
![](https://i.imgur.com/vnhlYAV.png)
![](https://i.imgur.com/pHoqxdq.png)
adding _, fixes that
