### ISSUE TITLE
Issue for users importing aura after 3.7.7

### ISSUE THREAD

**Issue by wing5wong** [WeakAuras/WeakAuras2#3449]
### Description

An aura that exists in 3.7.5 before upgrading to 3.7.7 continues to function correctly for me.
Other users have reported to me that theirs stopped working (possibly after 3.7.6 updtae?)

![image](https://user-images.githubusercontent.com/4406993/150935371-a03e4d82-8205-444a-8349-851bbbc3ff95.png)

My version worked well after update from 3.7.5 to 3.7.7
After deleting and importing the same aura, the aura broke for me.
Exporting and reimporting thr troublesome aura resolves the issue

### WeakAuras Version

3.7.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No error is displayed

### Reproduction Steps

On Weakauaras 3.7.5 this aura pack work fine.

On a balance druid, Weakauras 3.7.7 import this aura pack (delete it if it exists already first)
https://wago.io/GzpP7i8ic/1.0.105

The "Ultimate AP Bar" does not respond correctly to eclipse changes - it should change orange/blue/green based on eclipse states.
The overlays appear to be missing. (2x tick marks, 1 grey area, 1 lighter overlay)

exporting as a string the ultimate ap bar, then deleting it, then importing the exact same string appears to have resolved the issue.

### Last Good Version

3.7.5

### Screenshots

Top bar working correctly ( i freshly exported this in game and provided the string to the user), bottom 2 imports show issue (not orange, no ticks etc). one his existing aura, the other an import from wago
![d2289358dc](https://user-images.githubusercontent.com/4406993/150934812-065f925e-174e-4e18-b899-05bc4b89fdf1.png)

**Comment by mrbuds** [comment]
It was hard to understand what was your problem with so much auras and custom code, but i think i get it now.
On wago the `subbarmodel` subregion is before `aurabar_bar`
After import `subforeground` is before `submodel`

**Comment by wing5wong** [comment]
sure.. i made no changes to my aura though to my knowledge.
perhaps something changed on the exporting/importing process that adjusted that order?

now that you mention that, i did ask for screenshots of his settings but never caught that,
![image](https://user-images.githubusercontent.com/4406993/150980398-63a7df74-10d4-4274-b793-be8ddd920381.png)
Background > model > foreground

His
![image](https://user-images.githubusercontent.com/4406993/150980552-f7794224-0fe0-45e2-a571-e507e8c84eac.png)
Background > Foreground > Model
