### ISSUE TITLE
Custom Trigger that are purposely false will not fire in newer versions

### ISSUE THREAD

**Issue by Lunastrix** [WeakAuras/WeakAuras2#345]
What steps will reproduce the problem?
Upgrading Weak Auras will reproduce the issue. It seems like the code is functional in 2.4.25 but above that it refuses to work.

What is the expected output? What do you see instead?
The weakaura is supposed to display the player's toggle menu in the box selected (which in this case is above a health bar). Once upgrading Weak Aura the box becomes unable to click on to get the toggle menu selection despite being usable in the older version.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes -- have also reimported the Weak Aura to try and "reset it" if you will.

What version of WeakAuras are you using?
2.5.4
Was it working in a previous version? If yes, which was the last good one?
2.4.25 

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
N/A

Please provide any additional information below.
One thing I noticed with trying to manually fix it myself (in the newer versions) is that when I set the custom to _return true_ it decides to run the custom untrigger regardless of the first trigger being true. Once you reload/logging out, the PLAYER_ENTERING_WORLD event does it's correct job and turns off the code because its true but after that point you need to reset it to false (and close WA entirely this), then back to true to get it working.

In case you do know which aura is problematic, please export the string and paste it below.

Specific String:
 `dmeZgaGib9jevmkrXPePMfi5wkvL2fvkdJkvogi1YOs6zkvvnnrjDneLACikX6iQCpQu1bbHfkk1dvkmref6IKsTrIOpQuv5KikPvQKzQu6MiQ0ofj)KkXqjclLuYtvmvqDvLI(QOeNfrrElIIAUiQ6UikyVQ(lrzWOoSqlwPYJjvtwuDzkBMk(Signi60iTAIQQxRuLzd42cSBs(nqdhroUsvXYj8CeMo01PQTtk(orvz8ev58eP9l9H(WFc(K)j)WF0bbafh(PY6t5UJF8kuqtsmXH)O7jqWGpoELosbvzs3v5YLltDkV1IosaeLAcjfXaRmcPP6QC5YLnacRRYLlxUC5YLba1JaLfLDF5SyX9GWlIeUjSekOIGmh9IOmtPXnAozWnHLqbvDvUC5YLlxUmaOEeOStz3xEdHfrtsrmWYeUZJiOkeQYHBTOJearPMqsrmWcHQSaQYHJP7fge6ifuLThrqfSfqciIwy6UkxUC5YLlx2XnVIILDFzYHequQjiNUkxUC5YLlx2rUXqiquq35rltOxrXqOkhscik1eHP7QC5YLlxUCzh5gdHaaqcqQcjYis3v5YLlxUC5YoYPTkUdWixqpHLbfElDxLlxUC5YLl7iNwwcLanHKGInaO67rKjCR5Gz7reuTjPqOkhQfnbsmBpIGQnjfMURYLlxUC5YLDKBmecef0DE0YeIsjzqhcv5qmksmmmDxLlxUC5YLl7i3yieikO78OLjeLsYCneQYHiyscGfykFy6UkxUC5YLlxwllHsGMytffZse1HmJt6UkxUC5YLlx2rUXWrxqjHzcDrPTcnriuBQOOKIyGjZfL2k0eP7QC5YLlxUCzh5gdhDbLeMj0f1wlQXcHQ8MkkkPigyYCrT1IAS0L7QC5YLnvExMkVRU6QRJFYPeYVxPJun2NOs6hQIIYiWOaT8Nc6psDXXHWWNAFHE))iSekOcwkj7dAYd9c7J8rZriFkOjlK9NOos1yWcAsIjixWC7PC3hQIIY0bdibyOL)uq)jQJuqfXH)qvu8WFYbLP7jqWGV74XpOjp0lSpufAcNOUr(yEoOIG8BTOJer99iVliKMG8Z(4JcRSKIyG5gMe)GcAsIjo8hukj7JUNabd(O7jqWGpoELosbvzmnMct3v5YLllm0luLDIaewxMkVRU6QRU6QRU6QRU6QRU6QRU6QRU(OdPPV3htJPWpMgtHeFKyleKjT1sM2PG1wlYAQ9twwCrRTKXp6EcemqgkLK9HaJON4JUNabdKbjn3(G0al)4hA(hjaIsnrzjfXaR8gau99I7aSpX8CksbvrazOGMKycId)uqF4pOGMKyId)bLsY(qGr0t8XtyYIaYxukbk82Z(dHFNPXu44DCOY7JSnGyGLnWqOf8htJPWpBaQYPifur8XRO4hsarPM4JNWK5vu8z)XRmnMc)e9i4hc)otJPqjeMdvEFgj0E72JF8kuqtsmXHpE84hLpawqtsmbXt56hinAcK4t5Q7(aagZp8hmcyk01d)jWdG0dF84hpHjtzAmX39bJaMcp8Napasp8XJFYPoouDpak9WFc8ai9Whp(re1Td)jWdG0dF84hQkra6jD4pbEaKE4Jh)qsdjmcyk8WFc8ai9Whp(XjQJuq1H)e4bq6HpE8JaeWo8Napasp8XJhp(H4JRULv3CLS)O5PGoRUc9XFa`

Which is apart of a bigger weak aura collection here:
https://wago.io/EkLaSvd5W

**Comment by InfusOnWoW** [comment]
If you always return false from your trigger, then the aura will obviously be hidden. If that behaved differently in 2.4.25, then that was a bug. Though I find that hard to believe.

If you trigger returns true, then the untrigger should never be run. (You seem to be confussed that the untrigger is run if the trigger returns true, but that's how it works. We do have documentation that explains that.)

So to make this work, the code needs to move to the trigger function not the untrigger.
