### ISSUE TITLE
Option to change Action Button Glow scale or set extra width and height.

### ISSUE THREAD

**Issue by Weeeqt** [WeakAuras/WeakAuras2#3454]
**Is your feature request related to a problem? Please describe.**
I like using Action Button Glow sub element as background for some of my auras. Problem is that we can't change the size of the glow separately from icon size, so it gets "lost" behind the icon and we can barely see the glow on the edges.

**Describe the solution you'd like**
I want an option to change Action Button Glow sub element scale or extra width and height similar to how Model sub element has been recently changed.

**Describe alternatives you've considered**
I can achieve the result I want with custom Masque skin, but people I'm sharing my auras with don't use these skins, so it makes sharing a bit more complicated.
Also I've tried changing it with code (changing scale of _ButtonGlow elements), but this is bad approach and is buggy.

**Comment by asaka-wa** [comment]
This would need to start with a ticket on https://github.com/Stanzilla/LibCustomGlow I think, as the lib doesn't currently provide those settings. Only once it is updated could WA fold those settings into its interface.

**Comment by Weeeqt** [comment]
Hi, this is understandable.
I submitted a pull request with changes to add this functionality Stanzilla/LibCustomGlow#15. It's just few lines. Hopefully it gets reviewed and accepted, that project seems a bit inactive lately.

**Comment by InfusOnWoW** [comment]
This is now a upstream issue. I have heard that the maintainer of it has awaken from his winter hibernation and there appears to be movement. Let's hope for the best.
