### ISSUE TITLE
GetRaidRosterInfo() in custom text update only once while custom trigger of "GROUP_ROSTER_UPDATE" fires functionally.

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3455]
### Description

With a custom event trigger "GROUP_ROSTER_UPDATE" ，custom text defines subgroup of raidmembers . The trigger works fine ,but custom text updates only once.

### WeakAuras Version

3.7.7-2-gdbb10ed

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. build a custom event trigger with event "GROUP_ROSTER_UPDATE"
2. define subgroup in custom text
3. trigger fires everytime when event triggered ,but custom text updates only once.

Url link : https://wago.io/Qg2qBEJ9m

### Screenshots

https://i.imgur.com/RmZhUu7.gif

### Export String

!WA:2!9z1tVTXXv8WWdjGOhSikutJuBxXuBlLirlX0MG62guUI)X0yLiZskjByzSE2DhYDIwo7KzMvI0r9cBqAkqrpOt5upiKd9qqka7Hc0cFjOFawi0pbbWgox9NG(MDxsrRi1fGC3zM3)F)EV3Kz389Z7MxWU27w89l((RvATEU22BSo2nV7N)RzZ5seoCSeBXdKijjGMHhek9jumV5oDmASD1tDXcKmKJKyVXeA3aE)ycNN9gKE0aoUjtTuu9qmvwLZd4IhX0a5Y8rd7GhiTsyXIzjj9XPRYO3nGkT)U)9x88V(lFbI64fWRXr9XDgYWJBx1O6MDQzwERQNGOKef(E69re6NpNTtGFaVC28dYCwOaBj5iQWxzE5hMXe5Z8qzsOPE2K3MPV1ZAlCq(4bzpBkt1cPoSFFx4FLowMXd6XXcXQAcjIlVx677VQMl2xIUx677Vson4bICHCAkPAVJ2u21E7u6xzIaUStbPGPU5(gmsGBl5yApP3RLyIdZAhNrWz0LqerNgqXN5QYcGvAP2IlWobuxXif3QOw0IN7vQ12oHczqFZy9VRnd0mwAl84e6brVXRfTq0Bf9tI(Pr)SOfT7sOeH3UWo)8lC0jcSF3wbeQ8u9MD60ClJQ16ukK7ZwWtkzIBFRBDeQxqrsWT(WEL(y9Q39x1)wBy3NOqcE8Hn72fu7F(vSvu1OYjtjA0rbC394i2O9s)W8iIR07)868bjmnh)qWlb)nBPqI7yY6g)sEfDJA1QXw4sWx00pIwK9oxn8ZDif1N4yj9G4HxGV7WZqHsa9LcJZDQmWjvVVERF0lKGic5yL9TvGl2CtJYB1k6nFep9a2TBqLyExKdE)YUUnPI93dJoOmKQe7Vf2LG2VtcLI9B)XHio2QwOV)EEej22dt65j3bqN0UKE5yV1vB3q6ZHehmgnTu9urOTjUNYSFZ5Jw4myPnY5GEqjm1TaXLLVfimmxRX5LTNj8qUbhD)Kq8IVs667LSol7AjOgLfSdZfGsMyvH9likVKI83nj0G19dqUhYFm8zdxXRQlyyN5n7h6lj50fKhJNpYi3jQ6tkiaUNPJpsiuBc4pLfYUrKX86CeX9r2cylFC0hAlbOpvQOYwG7d8zUrX1lU(P8yVuHQ1vX9XjnmIHL8onBPWK8pcmCs3H6QfJt8Qnvv93ntMmzpXgeSRkdwQCLkCuC1U490bCV8grlvixUtCdSs8DVOc5IUEo21MPTu8FSfMMAVDAK9oyKV0tthXh3vrcugJKOSJNjr(nx3PK21D2q760C5ylEjPyNnMcDpvvttsrINNkg8QF10wujTE8dG2eAHG5R9B1kWITMcXNS2APhghXHt3biAt13lRiFw29HuJFkfgQV)Eua9nHZV5Xo3SyrZYnQyb4)2TT2SPrtZ2pa6nGDKlxA1lOIvEyX4gUq0ygzbfE4uLTn85LPlyCI72jKbRkwuXsXI38y(nN4AtiMDilvwneT2TvIW0quxTch7aTiQTo8uOyXcTkCbbKWVlq5e(RSDLz5VY04iP73tdspm9CBj1mUcvQnHqvxE1NtKh1eG9xuGNhiG646QkeqYPr43DvT6yPIlZabuiQkOx(IIALvMkhguKjxEICoF)0bwZePbZ93aM7esHLFqHvJXfXmH9f4)pCplLGpQ(PEIMl7Ld0lnfORdxRWHT4ZFYx98N8KN)3)Np7F83E2x8xE6F8F90V8t)DvWucp4BHgZbQUwo7PgmOxgwYMBMIYwq3uQ0BKKt61d6l9134KqA6I5JwIT0fQzsTFjpeNAQ8uQFwATMYNy)HZztBg4zFe)aiJKMh6G49Wq43fpy5jLFVKwIjxHNASzZTTmA0UZduB9WlBpiQV(XYcAbCTcf0u224e7XYJaZCudaCH7Hzh2TRQhi)ovnAvBhdDvA3or5Wm7L(wilg3TUnqizWyRnl3UJv7oLn7arJ)6fDlanoTFwXgI0bGnzyffX4Yj(sxeadMIIV6wpPKhdYRoGiKIzQRUKaxshGKuXuJVfhdgVz7wvnms2rWYh37bCK6v7yTtRkL7unQUDsZxtvtcrUjrm1DJSH78idfJGHs((W4PCMoEyNdIQFJifWa62hj)miK8lMgsWj5UK6McBuAJsfUkmt0NeDC0rrlPI4rdJEC0NfvpAe7dAzu((vnTQzuUo0G8oL3UE1kA1nBUtllZMT7ahLy4APeA20OABlOBAJ6BxTs0Fk26adB3yfuN9dvrrTn9qQPvyoenjocLchPMQQcDpcmHpHLpDmrcs2iOhXH92tDm5l7gpyJhQqzYhu6HPUdurbuEioLF1iY4XxFuSeoexcrhEkKqWUXvHF6pWmU()UzHNl9EySj14dgPUJFB4Ua)48h(FVx0QrR9)c

**Comment by nullKomplex** [comment]
This appears to be working as intended. On Trigger Update refers to dynamic information being changed. Your dynamic information is the same between different trigger evaluations, so it does not update.

**Comment by roundzero** [comment]
werid , i am quite sure it updates before , because i set build it long time ago , it works fine. Idk since when it won't update.
Here is the url:
https://wago.io/rsZ0tjiRB
https://wago.io/NwZTD9lCV

**Comment by roundzero** [comment]
If it supposed to be , i will rebuild the trigger.

**Comment by roundzero** [comment]
I rebuild the trigger ,move GetRaidRosterInfo() into trigger , which solve my problem , please close this post.
