### ISSUE TITLE
%1.unitCaster text no longer showing

### ISSUE THREAD

**Issue by Fudgedup** [WeakAuras/WeakAuras2#3456]
### Description

%1.unitCaster text no longer showing up for self casted spells after latest update

### WeakAuras Version

WeakAuras 3.7.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

install the weakaura below. It includes pretty much every defensive and mobility spell in the game. Press one and see the text is not showing up underneath the icon

### Export String

!WA:2!nA1YVrYrz8DYOKiMiejoOnqccTXqSswIS6Q63hci32JJ3fV2w1m7RGqZuD31mDVBpD3PQES94BXN8YtjdiaPGuyajar4LriecqGSe3lnbfUV)hGzdOWj(QUh)iSjlmhMQ6V6x99(rvB5zgmt4mH79CJJdYsBLnKhW(eNJeKLKXVCD434GHIISbTzBxmBJg8rR3RNGvu7aAAqugFJS40c)fBUw7MKjbzzjHzBL2AR4Cwx8qEYd5P4A3Dl4X97Z4IV2C8PB37jZNPaWxeNFnAYq2Adh4Z41NmGweeXeTIY2A90dfLlleueVj7UIH(SnzPfBWz9I3M0AJMRU64HPXfn3owuiIYF8HcwNZY0OXHm)H961EuoJVsZv3y5RU6yfpxmjlLj6YHlSgDal6eE3cqhV9bDwCHwT70Q9cK2h2JbAu7kU2LuIYFfgnPi6q6qovKZssIdfVXRqmnX66edhBxmXbHnT8XiSJMMpY1Y000h5y7GT9rAg226WxwyltFSLHToS4GqUMEaslIocJn8mX22edtKd8HRdadyQLLPlCSJPMpwZe5IajOPeeCdBhD1cS6Jn0naEIWAUMg(iKjY2cyLHUdXcPRBrWG4WGAzB5cAhYrt3b0hdDqio2icw3fRrCTnS0jiSRnWkdG9GTzB6ysqUyDqKAGXGigUA6UelteceHJYIugMPTITUyLqCnC09WUG6HXihh4MilhdKxLzyceTi222wiFDKgYqNORibSXuhHaXGmTaTdP5AbW1T0mDuladvQGJUB5zAUkNTLbQs8oeWCCHJCaHGiGoAHiqCrd4RRHLTcTPHTl4LrM(6gGp2YxhJGnkNJbgumxqnLRdErKPYC0SCCb2AIDQuxWXc8Zb7RR7Aabz1IPlWldxL2Ja)LDPtYbmmnBi6cQfeCXwGRxhRbI0x30wXutdhlKNkv2ppHoIX3TmR6sHIg7RYXsHCurdVcinMO(gFeK42CBAqrRkCDjvqMa0Vu)0mEvA9(dtNwU14GWyXTgMwwjHPPJYNzADD15RM1poi)Z0Rerw6Zp9AVqJla)4SIH80lmL2xa9fBWsdZFcAjZMYGRKfYEZZDe0nGXtPjxdk2b(Wo62mw(cG1euqOaNJ2NMgpqTl1IikO8ILL74LcipKrfSwfCwA)IOhDsiyMkuDugnxWG2iHIDvyufZY74nGgNc3vEh5x6rLFz5xr(vL3XVxCASi6)Mm0fqqlume6iav6ewFGZIlFE5otGp9Pb3UppByA4EpB(Zwan66u(xVmoOPDY7uepG1jNZcIv2u99pbYKNdnVkQTivaMD(ZFF39Sh3Hdnng0rfOiPqBeE(JxcverHMMlw2WTwTA1pQIbXBZcVECyr0RL)PFW8TIM3vbkJ5zfGvQAw7T26R1mF277Q33f9fqGnT)4sqN23hApFQ2DZPD9NusBRmE41508DV(0nhwsEtW94NW6M)Ipy9L67ZzBgd6zNb0TFS85Eq64PG7M)cFqXMWrGxnoOtreNbT3tchL)XFFWwTHOUsy(f))tQkv8jYFYsC0HqbdKvgugx8wa(Cs1yWJ9pvoIBbvwX9gjFe5oCi)srB)PckTyCZTHujHyl6OjNqSCa16xT9QxcIzvo(3lJZ)KFq2E1x1(FL8Dg)4PITv8oSNj)PVVBgGMUtENPjPNzA)HGE2K0XB92Tx)ktT)BmvnVBvodlPxjuVfUA71Z)upynRmLJeKqfI3to3X8CVNs(NRj)M4LAUS87uwHi)dY)O8NkFt5391K)SAYFo4OFD53dk6)fY34Y1QVYN7V8Tu)(21L)s5Vs(dJKF)AYFFn5y5pqEG8xl)Da(Ftn5pw(tK)2Nr(Jgj)g1F7j9tY2Azo7vhYsdgTrDT5Xvbpf9dHUQVCY0A0U7QiPcyKnGA0KXQpxTSR1h5a1(Jdz73p5KY6ZOtEkYrLiVXzr2kGMWQxQhTJIdUn8(er9Ytwng2)HlLJhuWX4D9JyX9JkUPxsgn8A(fWntlopzWq4nkn47aDtHrhpKNQT7C(cO4oH9WY368pCx5FAo5BFWsnxO9kF(1U0lVsBGQ8V11tajcNx(wngZlBnw2I9dT)jXr5JCqCAvSdoTH3ozzdQD4Xp3RzyF1R9IdpWzRfVfw72Be5C98p6XhRAgTuSGcTgcJ8u1qDhxKfSz1eIpwToV7SXH5p1sSESubmqrCbAA4fUsMFCsCXiYwQATBEqpo03egpqlO1pQkPBzfjLQ63ArsZMRrOj5r06(WOIEX9Ban1uYGfnbKjaF9CLYlAWPLJ4ewY9A4bZlkMB)WSovtdJ8RwHx6k)6ngRg6exc(YZrGNLgC7LLpw9D3KYJvMZ4tZIjBQEVPCRzZYN9LEjEqenTpt80ZjVx0U58mO6gMJndKpnpE(Z2SCo5FxXs5rY)r1vL3dNZkKVt5vL)t5)6ee8PVjqEpP7uSVZfbuDRqPwvd3M3yEvMs11EXZnf5r4fwBj)stqCXPs8DpwIYxTIYDzBNhxn2Tn0ArD8NfoEgZk1rjO)9Uhhw7Y3EA67mcI(82ZBpZM)1B8F(

**Comment by mrbuds** [comment]
If you remove the condition that is hidding the text it works.
