### ISSUE TITLE
Additional way to get spec for arena units in battlegrounds.

### ISSUE THREAD

**Issue by Weeeqt** [WeakAuras/WeakAuras2#3459]
**Is your feature request related to a problem? Please describe.**
Triggers of certain types support arena units. We can also select for which specialization this trigger should work. This utilizes GetArenaOpponentSpec(id) function in order to get a spec of arena unit and apparently it works only in arenas. This doesn't seem to work in battlegrounds, although enemies are still arena units (arena1, arena2, etc) in BGs.

**Describe the solution you'd like**
I suggest to make this specialization check for arena units work not only in arenas, but also in battlegrounds. To do this we could use GetBattlefieldScore(id) function as it has been used here in BattleGroundEnemies addon:
https://github.com/BullseiWoWAddons/BattleGroundEnemies/blob/master/Main.lua#L3171

**Comment by InfusOnWoW** [comment]
What's the use case for that? We tend to not care about pvp that much.

Both of these sound like very niche things, that aren't worth the effort to implement and to maintain.

**Comment by Weeeqt** [comment]
> What's the use case for that? 
The use case for this is to make all PvP auras, which use triggers for arena units and check the spec, to work not only in arenas, but also in battlegrounds. It just makes sense to me because for arenas it works fine, but not for BGs.  

> Both of these sound like very niche things, that aren't worth the effort to implement and to maintain.
WA is used a lot by PvP players who play both arenas and BGs.
Arena unit type is already implemented in WA and arena spec check is implemented as well:
https://github.com/WeakAuras/WeakAuras2/blob/main/WeakAuras/BuffTrigger2.lua#L1099
This feature is very helpful, because it allows us to filter out certain buffs which are dangerous when used by one spec and not the others.
I just pointed out the inconsistency between arenas and battleground. Because in BGs all enemy players are also arena units (arena1-10 etc), but using GetArenaOpponentSpec to check the spec works only in arenas. It's possible to easily get enemy specs in BGs with GetBattlefieldScore(i) though, which lists all players in BG.

> We tend to not care about pvp that much.
Just like Blizzard :D Understandable though, much more people play PvE.

**Comment by Weeeqt** [comment]
> I think a niche filter like your idea would fit more into a custom coded filter added to the generic trigger, kinda like custom check for conditions.

Actually I thought about this too, it could be useful to have some additional custom check in all generic triggers like you described. This would cover many niche cases like mine.

**Comment by InfusOnWoW** [comment]
I think this is clearly on the wrong side of effort to benefit. The spec detection via such a complex system is not something I want to maintain.
