### ISSUE TITLE
New patch 3.7.8-bcc, broke some of my WeakAuras, reverted to 3.7.3-bcc and it works fine again.

### ISSUE THREAD

**Issue by Tadiaki** [WeakAuras/WeakAuras2#3461]
### Description

No idea whats causing it, but reverting it to the previous patch 3.7.3-bcc, fixed all the problems immediately.
The weakauras im using that gets broken with the new update, are the following:

Healthbar + prediction

!WA:2!TN1(ZTr11)SOjd0TyASjjLeiWIahStCC8dsacecs2Yrk1rwSs25fG0QDVs7swT7M7UYVOHhUTu3x0wxM2(TVRODAlL2cQLFUZKP)bCgnFN2FQZ0jtNP)E(hGEU37Qx2YHuMoD4hyNjY7EVNZzpNZ9Cp3pF2iTWa(Qto6Jn6KduzaJbmw)ankQPFzdQR3uU2U0ZejsKmrgB0JD9IUudcnE4KE7kUT1QRQrnuY56Ahy5rxEUsL8jbsffsAsxrmqYN502E7aVQrjLTCDYTIhrTm1TQxnHKzTwLSZn0CSQOfGZFCv)anAWmXdqbJ746qUgrZNKnGsCkhyE7nmQs5cMNja1NO76y4VgtgMPH7kEfnlNzG(G7c(m3oSlOFya4UkwYYXY3CZdxx4cIyvsskIQVUMnjsORLWOmXR)SxPQgLOmtvBBLZzAfqOA6mhW)4WDkhhTBGmSB51cOwLlJo0(pin82xVMbPy1sLy(fnzIzZmZ8Zc9PQHbWeR57rSTtz4lFD)QfjlsCcYIIATC98tflBU8zZftnx8QOXl6zRTcHQ6OvH4lRYfTysIMDGzlvZqjOQQzZKy2z3OQt47xUUMJUPlnJRfQYujsNlH61erMyT5t1qRAakWCE84rUwGR(IyiGpChz(SrTm8UxXlsjwrFxArFLdQGVkdlE8x3YPKlvSQjxVef9pCvslqlYneV3zydXc(IzNsnrI03aDdc1rZEbX74sHP)uoOVezdFIDjURcJuddmvE5IVCrCbUKvz5ASfAlHJg32vZyHIb4ALtWEvRuflbLPRIflyg92u1T1893lCs54ywwxCdwLXUzIQwg1NJCUmw6d)Sx0DYb0p06hRMVNg9YNZYiWCp1SW3tw3QuDY9Td42VZ7gommsdUaQUb8GvYR)UE(SUgK4XMp3CtuLA7Pyge45FIJE0L0k7oQL7rn5PWdRXtHhD8XUbBlgBhGJrRcp(Mm4EtFq4((RqFf1R6h4wPU4p8c964UIasvpd8x4aW9dheEe4HGhgMD5D6xQQdFfzinBBUC(JOWRlgwwbVSkP44gO0AYlfn6ZReysC20qNu5L4Y38Y30DjCWaAvYiDnHUPMtzIrpNZJ6wMs89zR7Oarz23spA3cTOMDv2SZJ13IkSHIkkZJoC3sgG5y7UK8SAlVDcZY0HYEAsqkhD3kwoLzQ53wffxQYyTu7Q87iog8)A7IB)v8rB0vMPzwKNtvojgvZNovU8jteB2CjJYtLTmO)O3SGRdXWEc6CZPOYkfgkuXJ6pkpMp04JnwNIxXY3hdgu8qbuosZ3LieS9jB1fpBSZVnE5hsI9)1okZlZNrnX0PMkxQ5sVj3vSU8ry51F0qLy)PRLA)r1meTt0SZewZY95EmmAYx6QBRwxA8NFBuKnthk3okY7ITzrhg1B7uSzn3qTZOpTYydRO5yWgJhw8b6kr1PXh1WIs49fy7dXw1lHNxhT3IUeR3hpkALO2ImyYEtlQHo22iU2YO44XdMmnhQh6PC4W33inT6WTQq(Vwen2nlyg7M56J1v9cLeuL6WB4jJJbkYIJE99C6OzWjeLHk8HIfp7CQXZh7SZnF6C5NkzS0NoX0DjrRTNDn6M2l0CooKG5ZadkRQBs0VmEeWqWWWdcrVH4GIf0OwAfTj(ll9VeDY7zj(4IMMnBt1UNVHLVNOOmQOJqhDTdcBN7uTsrCBgF8RkMUzNKEAiSPIY)jgRD3JBIFPCwHu3AMuCW72zrbYMBnlf2lzB9SBzxQDl1EARmIP)WT1vHdjxhv8f5aawKmHMZkE9RXVpNaeidCY7SdoQM86nX0hbo2LGpnIFDggyygM4qaXWDVLr29Mh5ACWpceKxqATIAnXphj5P(lVj76nKqKV(AbmK6etAiKY9ap(z2l0xDg(xuP84)w)aE3Faz5G88FeOjZ7LpWQcj8jPnAnF0b982xpKwCJktjJRXN6fXTdwLwbg568h7ayP3DZhbH96YaUQZX8fpg(4neg1AzIbFWxZB4TZZmwbXIBPNpWe3rz6ABi1qa49cHCG8oqpuvRyrkzrlwgPgLHCKKdNpE65sNWBxc)0uZWDP2Kr8EWTZd8W2GwSCAeVhUhYyGZwb7N1wmOpkcPMjL3aIma3HpVWH3zn(yTlp2i0EobE7AgQ1QkpBvndg0ELC565BSOv58IAZWX86pwR4nnFc)UEZHPQ(elylIEj24Qqd(tlHScohvZBTZfEtJwUdNk1CZNB2uTYADWX5APsNoHAEbtNWxNiP2ALPZbdJEP2MNXfDWgDLBK65Qq7fZ84Hf9V(UHxjcKV2GHBShCqWMVec6qsWaiqPxZ7b2QDesh(iUdZuckcJaViCzCdNlCfXEvk4dVmsgzzyfy14PrwoWNhUk8Q7dEnjyjZfdPrLNXXjsJWhebXe4MSMJ4kINqgGTxTLcj33AvOP9ii9x4EG(2alDedv0Kyv2myFWOYWtwAJQ(K8o4PGut4PyKRGN(2GNHFZP4)gJ9715TlIJm1my9IMi20t7TluZygSTPedIbEgHj8yyC)eYD2B58sXzDTmH41jlKv)Xp(vUi19jwl8qA)9FMKN6p)aSlmesEQ)H2yk7yh9TztBH6Fh0WwoWKWJQQz7zQfzdEdrFldIQAQtNmxD(lojp8oz4dwggeh10jwiHA9W3QUTLNjLTgwLswR5hbPOpPcoV64Jo2OpE8vDDRiPYnHjC0qI0ps4jxhUfv6dReEKrhuQvMqKaYjEbEdLIXyUKMo55Msd7P5uoUg95Mp1rA)0rYYuaMiIkhXZ0deN1CRGGsBRpIteQLdRnmXe2PuDxQfw2X5Uwl5CQPU4CPZfBw4e7)GG6mW9TZ1wmejrJWkubf2OUErFQtQYboeDYjPcAG(OwV3zWE)V)EyxtM8uV6UyxpsK1qUGObcwbUim(E9UhRYoUus4hBibd8uck1L6xa2h7tPa7wgqBnBuz5nmCZlW0yU(JctVhibw(J1CH0XHzKGtJBSsbNju1q9G33KzL79fe8OHzHZcPHSqUw0Lr0sCutiT59)j0MfxTaifYSkht5WY0pH38hV5n3tog9K98hLvzKBAtTe38Xdk0TzpFZip3nvphl7NuPBcEDnuNul7AIMejXb7GtUiDmSYt1jbDwUBteYV1yUUvA4DMU7KoC3bLGDnw)fwYCKMkoIsh1wDh1HIEZi3kJCmbvSNPImKbEw(3B8qYyp11hyTMF(9bgVrzIdHAPNf73nNZ195)zkxepS7soRXWgW(81f4A3h8q1yJioiXKw1HxhdVn8UrN8ySUZE9ZMVltwObffpl7dLNwRcrQbtc)MpwGd)iGQPF5cB0AujwxEHT66SltV921Z5zNmPf4sXt0UotArEJHqPagRW8WcW5ENDaNFt0L6())agDPnnYU3YixStMrrGlzcxqsqfcE(1pa8csqEKAttaJm8F64)eGgHYsmqHwMCmHfanOseGbNhrh6TZobigavHf7dwQGaMi8sCmIVSe8ksWRoidP4AnHPcFHTIof(I3AWpHVu3ypHxpc8LH1HVIe8v5GjHVwb4RZqncFd4n2h8C7bbkcFZoaikGg(mTbicFl4BdBiqa(5A)XW)osiuf43k8HVhIId((W3D)NbH6934x)umP(39ERp4d(aGHRd(bWperbbVDb4hDs4Nb)CgQRbVLqDb)k4xd)sbwn4hd)eOg8wW)xe43m9aWVqcrLcVdde6YMJVWvCD9ESvZa)o43dN4qhxaxsGlc(dW7cVx0JF8IO5VmXWeQ3ez0)C3SRXWe(FeUyigRqXNCYqTRlJyKG)ub4nnhyX))Z)Vd

AND

Threat on nameplates

!WA:2!1QXsVTXXzOQcKawduffy3AeuGPmqjKjuuKY1PTgrgGuIYIoYumuRStqCl1qUZso2l3DZm7kkQe3dcgfbfTx8H(dqhYpaDOh6XCUhwy0R9s(j4Fb9BMz5Y9fLuErijUp(MV3pNrlS9YJwwFz9VAfMTNRj1IW27aTDB2QrN(2M2S7Vi85CDk3XeprJCSB(v6FwFpUR9iXDhVW)ZWZQVl12QqXCi4d1aH9y4UeRJkZDXUee2spXJkZpWI6IChsSKRjyDw2UjbeOkGHyak(mfQ7SpX1ZrBiJGDBlaTq81xAg(yKbatwefIhILE41r5IeCGXUyU7bo6c(yJnqwutKn7Ia69N9Y(2wg0bLnuVzBg5Z9iw9NG(q09iUA0rKcfLYgkBHtTmL0ju2xQWnFzB6dK)HbknMvkBIqg6q4EMU5eGl)WMSNHbN4UW5yR(dTzTTPwU92SrlTgDCwAMFGIv7qoIy5UUhZ053m011HFN1wBmEGDzQ9ANWUT1NERbJ3T5AvxNHLUm8pOdqBMBUEgulkFyU6WxUVtpfEpEPVzQV1mDstaGapnoX0Omhm7tiS7DqZTqBGeUvIllK3r(48fvIsA80gucUtA5nQhHvWQesN0NocBYdDIhHDhwg3Jxa8zU7gOQv(ZFqC)WaTi3LrTaBSndwrH8RuopQC5q0jUoVXO8LqwO1KirraIjNKjrU13BI80ze5wZiY3hmjquXq3M5Oatf5f4tglolAq8gOn72cpIiHUmeaeEZ22mHHRqKCdHMH5MgqrN7SPjbZQzAkDm5fkM89aBwt65wizujx989SucrPOKQeAUql4AjmzrkvWsksr)e1lsJw6NQEtAKn0ECHmnJYxVdvNui0gjJSNJDkvsK42PzzfmT7JnrCvgaWALpFUi5LfgLght5GooRC5jZJLegqAauAGJkkjGP)qS1aIoaMlZ7cfyvSZuUQMHbbKzRbBApQhoUxucUkLWft1QuauUg26Pa6kH6wcwV0bNW6dj2aLgESw8NOa4Hytpsq(NTiUyQjrxb4(uxpSS840ustD0I4NNSeuipKr1HyCuajJXt4bK9m2LG1VmkgqSeiCduLmOAwuUALkXbkAvN5vDnM(svovsT46XkxY6JXTI6XPECiIJXHbvR1MrmHIsqWzmo4sCfxuuEEvuHO3(EsTZAX5R4Q(vxDkIjC3Qa6(bHG1tWpzAiIjjb4mMSe8S0A(lmeniZHgMnqLvha4r16UPjMZ3u0eP4zrJlLLzw1vcF(Ic7xq8ymAQqBVMYGHuzpcIwveTdMQ30sNCCqartlXtMpjZoQljUq)L55hPiE3sZ9NaLrhBtHY4EkS2XM7synTmSlKKwXTSjdrJInGNY)GAnBPvR1hLForQZ0zXStPIrvjsdBAA(wiGOP62kvt5ZHQzgjhyB3HoyOj8RBkZlWxtXxAzm5Scbft71YoeHnHuGCUg4WwTs7(U1gmGzlC0keptrGfwmIs8xi7gRyAHmG8VDQ(dAcxSN1mb6UqMjbAF7OXf3ni5AkukJXIfaL)l1AAbUlg4(Kh)yb25p(XYM1UusxUC(7u5ov(sxj4rrRWQ(JbEtX)rnYz6flDqIAUf(iPGkOxM5IP5vvicMt7TmR9mr)p7qeGLUfTqmiaAF6jr6VlDjHRgkBjAY2md8n)icdLXslrP25M4g8ORCrOyAb15udl2YZCi4PHwBP2baXQQXNYyzuGnSdRKdAWrRuUIXkRKVuupYszkXXv9zK5LVpDGLiNrAzveIjd8Y)(5tuzj2ifbvnNBk(lvA4WFwfjVkPmjzVsYuMXh0md(99sVDbQxVnmJSnReQAXSWuSEh(HJJ1Vk4iErQ0rfxfv2pXQQIF3AinJT4z2wZKaQi7pIq6c2PKutGLyNkEHUDx12zC4PGczWacJ36Dybx(vVXP6a8I5dwUAhlqJWZDMoPNNHH2ehcBNg72E7d2TUlCJ)YNRquxXDNlzkpjtp95dHzK64c8U(PChIPztDEo)FrVDiytO4MNLC3zQJ9CT)wUxp5D7duIE85D3S2(AD3xRwhT6EaF3tn5G)Yh)6)TW93dBAkjkVesU2sihmdpQAW3Rh89TkgQIHGnjKIgYZ3Q2dA0T9U10A09Gwn16wBRTASv(4LdtKktWkGUwrM0aT6QOMgOrGzG6aDgznDYCocZiiSUo0Qk2fzB1x4O5Wez8aYrziLEd5AJGNEuqQSridM9ieiMW7XIjkNU6uzyPJY2tjAMtPxv4ECutWnQ1TracK5CYSy5mCeF9bZYRO(vaiyOKQRbC52G(JWeBstXli16vIQsw)sRhlnCr6TA6S6Q2h302YLzBcZixWlCk94SYuxTptaWFcO7xKktt8HrkLotKAphY(LzoduL5cxSrfZGuhOCufmBg4iw6Llxlhdbpl3L2i0L7XLWQfDxuMF8zNgpyVhMkc9IcmfE)jmCrkV(tLbwo3qP5O0MQNsjTsruBNonQP1D3MqYVdAVfi6)OjTOlsCtuXbwZfSZ9j5CyY67hW4nbH4IZGAel4nDcRaOKjicakzgJmZ7Q21semjbfwFGKOYQzdDhR71xMFdzjlMJSnMcJTfIlMersGqmcnjGOYyl0VRcs3oRPTdSc5dtZlhAHMS7UiBuPk5Yvm)t6wzUk(Oxf)0lnz03Lesx9KsxEIP0jNI4UKg8NLoZw8sdXQ8mZN6Q3s20heCwfYTri8OOYL7upoPRquoSt)HK(pf6TrgwWDoirqrPmB2O0CsXvAojdc7scAmf6sQZ(TBS7UVs1S1dXmkUNjH78UkVcJKZSLx57NVuUNj5(x4zf01xoX5P(ezBvhrwhBnX5nWYR1uV)b26KfFfvmLUf28HqhJq7xF2PJTz6pIHDo9rbxu3aCKDwABg9e0h7H1H4vmstJDKAf38mG)7iNuLNRUPnw)H9CXMa3DJoYMMYXoX2IaDj(Z60xSxD3W)U5QdDo2xDbmZQ4Itfurma7nFjFiw3ECWHzSWzQPGfnQw3fgY9BfDwc96t7)iQU7W61GBzpb0wuJj13TX2ANbkrIU8Lp)AVaBrhj789d8)LB)nemNSVlJynWD4R5)w1Tao7Lt7nw2XlJtGU(15Nkavqu)w1hHPwp0)T8B5)XWVp4183ZVDpOLoG961Zg0We)L2w8CbiW7eGfifbh8Yc94KrGcRx1YvkxT6zU29duFVE7FvEQUZYk7AKd(HZoE6HIAi8Xb2gu8l(k1jKQC7b2R3(B2PrJw9uJQ8VCwk5Xa3ErGINo9SH240PNf0coxpZXTh6GUSD4A4lJnru7FELYvQ(QeBeXnDwk5w74Ct5adDvQgigBOT5edWACYeNLtV1i3(vjo8SoDAEVD0Cwo9PK5F)19O6NVtVN8h)Op(EFU3FOWlb3ebmoYta(F)p9FRoulhpiyNt2IW7pSZyHhYIR)uYe)NwxMU)nv4vu9ieZmDIbgCJ9VpegkCBU(lKE1I)hgg(caz7kF6qGa(2(od9)8f9z(uFUZsZWMI9998FI)rx3F8q)JfW3tf6clA9r4JF(1QZDjosL5TbSS(iQ1F)A(8t)KGYG(Elay(qbHorqOV45xZ)ldb3)zaWmFSak(PFAWAMbmX)lxuc2ccwtzQqcnnsOQ99UoSyYCa)nNTVxrwrryfdNTIfJXmsQeKWp0v03taX63gwy3VwTWdNTWQZONsFHuZJRCYuRfaI5RxxhmGo)N6M0tobZ0FxoQw7MOo4XOJeRqny2aIf0AHP5KPJUrHIN9MGWqRCcekVwxhCoqGvux0rrW))jb7rBaYkdwpkxuM2EmhnX2taPORerJhbOcEYGGNiB7ykBiHNPidQaTmPmsDUDCGwhbZrZfCr1kvkEe4o4ApyGjbeW(cnb3532oyQXzQFOZJpuSLXRGKbIc9N3H(p3P5w2aUe9Fmme2WoyqJfnEi48H4JiiOAchyvSLep2gs2gCarybk)ALF8Hcw45o)dreSq8avK4Riy32AvxX(MRMHxIrxfbK4PmcYQa3qg54ojq5kQKbph6AsqwQytHr9b(OhOiH0O6IqLXJhxwwMG2V8yBGZX6L7BpAnb0GQXqe9WDUH4GRrsMd(ju)iIU88haHxgGy8xf6gMFpa(3iiths2id1cTIku9CvQi5XhD)fwyHfptK8NkZzK7CQLABLG7UHZVMoWYMrcsO0qyyAWy2m(HVqSTsQ)LvQVNM2EpyzENBv(3x(wlF0)9t()p

Sry for the big strings :P

### WeakAuras Version

3.7.8-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

I dont have ElvUI or anything else that I think would impact this, and since it worked instantly when reverting to an older patch, its probably not anything else causing it.

### Reproduction Steps

1. Have the newest version of WA installed 3.7.8-bcc
2. Use my linked WeakAuras above
3. See the health bar thing in the middle is bugged, and the threat on nameplate also doesnt work. (there might be more idk, those 
two are just super annoying cus I use them a lot)

### Last Good Version

3.7.3-bcc

### Screenshots

Screenshots shouldnt be needed its quite easy to see the difference.

**Comment by mrbuds** [comment]
I looked at 1st aura and it doesn't set `changed = true`, didn't check 2nd aura but probably same and you don't give good reproduction steps
