### ISSUE TITLE
Multi-target auras does not untrigger when remaining time reaches 0

### ISSUE THREAD

**Issue by missivaeak** [WeakAuras/WeakAuras2#3465]
### Description

I have two weakauras both using multi-target aura triggers for some debuffs. In situations where i run out of combat log range (running or dying and releasing) the weakauras does not untrigger automatically but stays indefinietly (or until i open WA options or reload UI). Does not seem to happen for debuffs from myself or from my group, but I don't know for sure.
![image_2022-01-31_172551](https://user-images.githubusercontent.com/98763378/151832459-58d9af77-0db5-4ea1-a7bb-82965650e203.png)

### WeakAuras Version

 weakauras 3.7.8

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Go into battleground and run around eventually it will happen.

### Export String

!WA:2!LIv7VTrsz86gulYCsxJVR5oARozc0QwGZnED8l5okiVoon(WX2A9M(cxRSxV7yVZ117om748sbu1fHG8ztHpIq(lu46XlMxecoksH(r(WOO7VG8j(C(lGNz212jPPviflLDND2N53ZZ88YVNztKLI1nMvmRTlmWNyqFWTXwm7ZpaB65w3Rh1eDPtTRrpMThTkHH9C9Js3SA72(iwKHgUMW818WUSwfkwrVO2Usm08ygczJO0J6qUKnJr8FVRF91n64La7D9cfAOtnmFaIE9CWDjQz08zguw0wTXUyF7OQWn2v6B51WSNpZRRDRG7BC6Ny0JA0a5UwcHn6FJ4)G4rJd)(WC3p(nKJMn(9sQmVEjxgI22WeDV7PBq7Gyy3olrn6cpVAP3vZaBnE6sasnY9EjvelKn73maWSNqaZEuaZCcbmZrbm9jeW0hfW5pHao)rbm1jeWuhfqLtiGkhfWK3pE8Be)KazYjqgp4x0Fu0OrL1qnm9C8OFWuWV9FacrY7tqMmnr5HDFFKtBz1d)mB1YGwqk6YFN)7gYFtnz0alKVbdY7zi7TOJQU2rwSfumE3iQoEgwT73Zh1WfTgIA3Iz4GCzZO1TNddhL(qpxujl)tRkmHz4xmQMPJHVVyKQp(Hiyqgnar2Mn1mOixJMdek0ky8(m0gGfGUn1GSINfI8MfkNFLA6vvlNVW3n)IlwsV0TksohO)8wFeuRISqwRGDThqrDaRvFtcIkkDHnA)wGHzjqrtTCXklsdXEqrN1wTu8kE0UQp0ZRBTVWCjusRc0pEnhW8mHDLpa1xS2BPz4qSnMsPh2AyHQztN5dOof7Qm0c7tCm2uewE7t)g)0d6HUtKbbui6GYipRDpxjZZvVMm0JBhFmVcWeXqj6beqXz2i3OHb14oEMgoX7cicjm3eXMKjuY1cTXvpgaU24fdkqUYdHO4hfbBD34LkuTsJYLQR)HcXUFIeZo3pKn7yjb)v0r3H)210ZZXYBD36RJjOMKZnzRTkXc0UgKc4Y2zKyfT6azomkUthWh(lVcnC42xSVW7A6a5gnPqIHJtjlLKjZThehVj1RhbsG75YS3Z0RBlSlQgIUkSVS3YsKnc(Vyj3ZVxlP2QrrTXBOvVwXYLhkYdzG2zyI9UDnyM2i)62ERx1DhF5T8G7FnuFHtZfQT8JQfCdY1B1RDBz(YY51wzPvlpqSIccB0VjfaUciO9(cneiBbrESnTNR0m0y4UilXRlUb0DPEWMQ5yZSoSc8gdBuiFD9g11ZRPZZ1AzKHdZwvyc9R55SzxpkXMmTqhIYfCBSzdra1Ey4usm3kCGFuvXl5xChX2roj2Y)x9v1soFQ5wqEnNAQuPtRPKtjRI8AsTKWT08VT8(8AjZLjDovLmPYkhMfKyoXO5ZQMoBof1mkjtjUKwnt2SZPQmxw41jvwilmCH5vZKcw9cZNBEXL0AjNBH0IRPuYOLkv2CzusLAb1KZLrrnDYfslUKrDHCPvexsPPKzHClOPm3CzYinNmJI3Ree5KrGYERJ8zQmiYOj2Nkdeo)GGkFP(qAsqsv0RWF)FcVeD5ILRbrp(J4VEGN3NetlFPfBa(8BwuVXQ1wmVEXHbPUneWouw50lidg0R5d454Vo5shQynSGHr7HeLc8C7uW2GfFfKVVrhe)UTemaikFROc6GpsU01qamXclscSYYEDWMKVXyOdn(Gk2X6qoh0JqOjY0gsOcbqWF90tTpw0TW1W5wbKtqgTlURS0id)lT0UJQtK7pQpcyMS85ps1feDhKHpQod4x7WSp7wINeP98hR21a7UeVp)NboVhZ)5NL)lGBV2rNzpFg28bBUyOkG8vydBc2oQX4Me0qsZPha5)AsQy)hod)r7cp2coewhOi31kCI2EazTCI1g2YJAHOneDgMA3WhcoWNcqHZFuFbaYP3j8TbT6IejYu7foZAyFmW13CeyiGgImD9VFpONs8L654e)22ygAe8EbNRC73Iet0rOHVTbqEDNWJB2xoN4YSxMqo3bKOWefhm7O(QQ5xvVk5nKtk45eXft5jCvZdpk7P1aidqwYj)4Dd2G3nuJ7iFVOzgU9M8Zmq6urcsw1kvRuK)ik4deYmqk4Kw9bMABpOIyrpk2VwnYxzS1dZtbdPbPHGOQbHc0lIi0uhAxpYgix7LTqRnb2kGwIztrq5PJ1z3vk16GZu0LERBhoy3XwJKuT6Q6LlvPyOh8aNHh6fVKo5DEz6l4PiKV8XiqWaE1jQQoK3C(q)5DoK)CusX2xK)RJWFYWlBAaNwGki1jF9xa7jVSHrRwu0Ayie0ORXgtZ)nYqo)3Ypd)P8pL)7(y(Vpc)pap9h5dHQK)e5cViAjhzQpMCLxLUOq)GUneTd0KNMkm2CO9Ztpf)pld38)c)V(QHBIPBFiKgfL5pRLAvD9QRW)78)b)Z4)ZJjF5aWjZ04Vd)5njZ(QKlygvrhB(oNN)VJW)Br2EgPBV)LfDSesnXp(jVOFKe)fWF06cFULpWs62r4WpG7au0OTc)zAALU5Y6KR(YH6WH2Zt(A))iAZW90ZBk2ttXFYSx2CYM5Zp(KIdzJx6u8ptTcWelT1N3K)S(bNddke4)NJlv3DC(dFNBak)4YXugltlBeUJn7ATcyoGZGiopQ6Ot)QahB(ONy2yd7wDXuQh1MUXOp0g7gGiWsmd5TXDCbE6WphVOOXArH8(n7l)IdFSfI)ViV5OZ(j4Rwe7Ba1Cw2AtiPgknMLLw4nAbRSnUtuY0h6l4fwj)tuf42SLpQlujOLmbCQ8G)zbfgd2SyRbfkanmLFx)(bz3YpAsW50QEbTIfRmSTycOHNbZykT1fuU)4xl0mWwwixTkfVvrT9N0xAmZETPMlrAipt0ndzhCUE9GVAGC1jFWwbi3hsgvnOIpvBYtVBDXcgcCXG3sUZgSCvTsFVQv0ZxEGONmw6nVWv4BVe)9NAR1mOyHhBp0geCq7vDGeCwpsSVL2Ago9qXYqnTnC7G8VWmBrOEaZk0Ipg0rirQehSJ4wJcen1KMTDmFTujYMixS1(878)(d

**Comment by missivaeak** [comment]
tested with only WAs addon enabled, issue still there

**Comment by missivaeak** [comment]
actually i see now that sometimes certain auras start at 0 duration and stay there too

**Comment by mrbuds** [comment]
There is no way to fix this, if there is no event of the aura dropping, weakauras isn't notified. I'd suggest to use nameplate unit instead of multi-target when tracking this kind of auras.

**Comment by InfusOnWoW** [comment]
Well, we do have a fallback that should automatically remove the auras after 60s. I did a few tests and there it appeared to work correctly. Haven't done any bgs yet though.

**Comment by InfusOnWoW** [comment]
I found the bug on a second round of testing and it's fixed now.
