### ISSUE TITLE
Power Type - Combo Points does not trigger on Classic era

### ISSUE THREAD

**Issue by derM4rK** [WeakAuras/WeakAuras2#3467]
### Description

Hey, 
made [this](https://wago.io/HyAjQpjxM) simple Aura to give me a sound on a Season of Mastery Client...

sadly the trigger power type -> combo points seems to not work on classic era.

or did i miss somethin here?

### WeakAuras Version

WeakAuras 3.7.6

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

trigger power type -> combo points wont trigger at all

### Export String

!WA:2!1vvZUTTrq4WQdPvnO1ri1fnnOWXfnabTWTXUrjfOOOIYsOkr2wHIYobWa0l5oKCBO4Uz3LYs(OqoKEvpc6CpPhb)eqy0NaJ(eKNGolPsQ6p5c5UZSZp7mFFZA1U2WA0A0x1zXqofs6OgKY0XBteSy54dcdvG2s81uMsKqM4cJ1EHC5qI2t4Pzdbp6KuYqwGNowcQyEcDICYsZwqsdI5YECwQ2VzR9DB5SWNlPGSjpHlFuLkv6v5726(ssGMXtv1DuAIuFOCiOuKi49Ms5EkEwkn(8LI80teW29B8mNc5IT6KQbzijaoUbLI(44DbnHLOoUq)YFErzP7SfpkAo6WLEk2pKLYuXvTXF61NHAcYuA(W4PNI54rsIy6rlxmNckIots0q8ujxtmPRLDipvlwRTKD2gpjJqr1KnCDTt4e6HZYuGxqcrPoXxtsGu96odZs0SQ2kbeSE(xu1Pq9D8vS0OeWzxNbD2ffBRyNbg9VwJv7mjyYG9WEJ4gn72yVEUhy3TrZh3y3D7425WwtvWlYG0aOIJkaduL5sictpxSqzB8WmFm6uJdCS72A)DLlDRO()P2DeqEEd8AQoUh)uqwSCpGYihxk18DhzboX7mR5AEWiqQWG9(FZV5qseXeRTZy0f3DhE2dgmGn8f3DEiBmqpIr1XV8ALqmpL2tFMLKNPtyPG8GbUD7SFRllHg2KGNtLCHyn7e2zNrK0nC5CSWjUqftO8tFwj66wxzzIm2sSwzNZGohiOyxYbgHv8ljzOuSzfueF7g42PAjlkcZ6p6oYLlF16MMvFngyvCrFtyU9NSWSKcHSaKqCPkZVWP9KOKXo971QB38BfpR4Sgu5hCXBn1S9ee04NfgA6dYFPv3ETh012OWodXBV1D9XJWgVWRzJ(UE9DB44EzHl84Ozenxw7NMA8RXOte3WSuInCMekArgVhlwRiYGmaDyH1XoiPeuvDk2v77NIyUKKouv18F0PWW8nY3m)X(gsnipFvB38H3t8jRkyLuzww6YIwvX1nS2rGB5Ed(63VI4Z)FhuuUWXmVG(AMb1LssoSe6eCEzBmKLaDO(3B7T)H6pCgjLnSGLvpVA7ZbIP)iH0iD8vZFKDkpfUGA4J4jkgjivqah57tnh1uuY9ThsyPTZjOb5(5b50CuyET)TKvWKtSexhZ)ajOXQ8BO5RCGXwZX(Mtb)sDZ1ZF0f4wFe3ejnJz8JbwuS(LxZVWy4Kl8xcM)NZ7MAgC0hz5FMpM0HSOQ)DmKtSMPGKWIHM5x1VKuepV8FlAeyVV52xYfEAjxOYs1gFE7v814)CTZl1uEUpCfDNTYflt9eXx(UhXlKqaZ0RQ4pKjLCeEDAjH2j4nxSkYFf5GSWj4mM2UlwXzB(vInz053VzVnoLir((sE7eRfHseLInwCWzLxx(yrBJitd0VFtNwT2xSX7oVk3zjj0rOXq88shli6yXTlq8QVLidiPqjowzAkEbXGsV1WTx(uuNuSW8PlkRNL9jllRkZnWjwXZs38ooOnbpVE(pxz6iIKrWjQ24BDN6mIKKbvKbXK0iapy(S6ZlFXPGP3dZ78poFTlkLzowkK4VhrHuGPcPHyPXtSGLwExWWv9cCQfwioque8Q1uo7S1d2QETr)Xt)R)

**Comment by mrbuds** [comment]
My tests on SoM show it's working fine, if you need general help with the addon i invite you to join the Discord server.
