### ISSUE TITLE
Conditions.lua

### ISSUE THREAD

**Issue by RAtwood90** [WeakAuras/WeakAuras2#3477]
### Description

1x WeakAuras\Conditions.lua:824: Attempt to unregister unknown event "WA_SPELL_RANGECHECK"
[string "=[C]"]: in function `UnregisterEvent'
[string "@WeakAuras\Conditions.lua"]:824: in function `UnregisterForGlobalConditions'
[string "@WeakAuras\Conditions.lua"]:853: in function `UnloadConditions'
[string "@WeakAuras\WeakAuras-3.7.8-6-g26cc8ed.lua"]:1735: in function `UnloadDisplays'
[string "@WeakAuras\WeakAuras-3.7.8-6-g26cc8ed.lua"]:1521: in function <WeakAuras\WeakAuras.lua:1393>
[string "@WeakAuras\WeakAuras-3.7.8-6-g26cc8ed.lua"]:1557: in function `ScanForLoads'
[string "@WeakAuras\WeakAuras-3.7.8-6-g26cc8ed.lua"]:1610: in function <WeakAuras\WeakAuras.lua:1608>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 onUpdate = true
 units = <table> {
 }
}
(*temporary) = "WA_SPELL_RANGECHECK"

### WeakAuras Version

WeakAuras-3.7.8-6-g26cc8ed

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [x] Yes
- [ ] No

### Reproduction Steps

Just wait until the Fight Ends.

**Comment by InfusOnWoW** [comment]
should be fixed.
