### ISSUE TITLE
Wrong string exported from wago right after uploading.

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3482]
### Description

Export strings from wago.io will get wrong strings right after uploading.

### WeakAuras Version

3.7.8-13-gdb3bd18

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1st step : upload string to wago.
2nd step : copy strings from wago
The result is the string i will import in game is the string i uploaded , /rl will be back to normal.

### Last Good Version

3.7.8

**Comment by mrbuds** [comment]
This is not the place to report bugs on wago website, this is only for weakauras.
