### ISSUE TITLE
Lag on Mythic Sylvanas Windrunner since version 3.7.8

### ISSUE THREAD

**Issue by syndenbock** [WeakAuras/WeakAuras2#3484]
### Description

When reaching Phase 2 on Mythic Sylvanas as soon as the adds spawn the game starts lagging for a few seconds until all adds have spawned. It's not low fps lags but actual lag spikes. This happens on both add phases in that phase. The issue only started occuring since version 3.7.8, I rolled back to 3.7.7 and the lags were gone. After updating back to 3.7.8 mid raid the lags were back right away.
 
As the issue is occuring for multiple people it's propably related to functionality common WeakAuras used for the fight are using.

As we are progressing that fight I couldn't disable all other addons but I have seen the issue being mentioned on reddit aswell which pointed out it's related to the WeakAuras 3.7.8 update. Other people in my guild have the same issue which was resolved by rolling back to 3.7.7.

### WeakAuras Version

3.7.8

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

No error occurred

### Reproduction Steps

1. Install WeakAuras commonly used for Mythic Sylvanas
2. Progress to phase 2
3. Go right over the first bridge and wait until adds are spawning

### Last Good Version

3.7.7

### Screenshots

Lag can't really be caught in a Screenshot but I made clips.
The lags don't show too well in the clip, but they are actual half a second freezes.
[No lags with version 3.7.7](https://clips.twitch.tv/EnchantingCrackyWaterGOWSkull-veZbVXjL8fW2Bvc-)
[Lags after upgrading back to 3.7.8](https://clips.twitch.tv/WimpyGloriousEggnogMingLee-4X2cWCxAH8Pt8Qw4)

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/8083962/WeakAuras.zip)

**Comment by Stanzilla** [comment]
> Install WeakAuras commonly used for Mythic Sylvanas

What are these? But we think we have a fix in alpha, can you test with that?

**Comment by InfusOnWoW** [comment]
I'm pretty sure this is fixed for the next release.

**Comment by syndenbock** [comment]
These are the Auras we're using for the fight:
[Sanctum of Domination bars for all bosses](https://wago.io/Sanctum)
[Sanctum of Domination icons for all bosses](https://wago.io/SanctumIcons)
[Chains of Domination assignment](https://wago.io/p99rsw1p_)
[Arrow wait helper](https://wago.io/SJldE9s58)

I will test the alpha version in our next raid on Sunday.
