### ISSUE TITLE
Lua Error since Version 3.7.9

### ISSUE THREAD

**Issue by Cheveyo10** [WeakAuras/WeakAuras2#3488]
### Description

I updated my Weakauras Addon to 3.7.9 and since that Update I recieving lua errors and its everytime the same Error. 

### WeakAuras Version

3.7.9

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

1x WeakAuras\Conditions.lua:831: Attempt to unregister unknown event "ITEM_COOLDOWN_CHANGED"
[string "=[C]"]: in function UnregisterEvent'
[string "@WeakAuras\Conditions.lua"]:831: in function UnregisterForGlobalConditions'
[string "@WeakAuras\Conditions.lua"]:862: in function UnloadConditions'
[string "@WeakAuras\WeakAuras-3.7.9.lua"]:1735: in function UnloadDisplays'
[string "@WeakAuras\WeakAuras-3.7.9.lua"]:1521: in function <WeakAuras\WeakAuras.lua:1393>
[string "@WeakAuras\WeakAuras-3.7.9.lua"]:1557: in function `ScanForLoads'
[string "@WeakAuras\WeakAuras-3.7.9.lua"]:1618: in function <WeakAuras\WeakAuras.lua:1614>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(temporary) = <unnamed> {
 0 = <userdata>
 onUpdate = true
 units = <table> {
 }
}
(temporary) = "ITEM_COOLDOWN_CHANGED"

### Reproduction Steps

Updated to Version 3.7.9 

### Last Good Version

3.7.8

**Comment by Cheveyo10** [comment]
[Weakauras SavedVariables.txt](https://github.com/WeakAuras/WeakAuras2/files/8100130/Weakauras.SavedVariables.txt)

**Comment by InfusOnWoW** [comment]
Should be fixed for the next release.
