### ISSUE TITLE
wa发生报错

### ISSUE THREAD

**Issue by wangtao39** [WeakAuras/WeakAuras2#3493]
### Description

wa突然发生报错，无法解决

### WeakAuras Version

weakauras 3.7.9

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

[string "Error in: FoxHunter_AS_CD':'initialization"]:25: attempt to index field 'BarColor' (a nil value)
Count: 1

Call Stack:
[string "Error in: FoxHunter_AS_CD':'initialization"]:25: in function <[string "Error in: FoxHunter_AS_CD':'initialization"]:1>
[string "=[C]"]: in function `xpcall'
[string "@AddOns\WeakAuras\AuraEnvironment.lua"]:292: in function `ActivateAuraEnvironment'
[string "@AddOns\WeakAuras\GenericTrigger.lua"]:807: in function `ScanWithFakeEvent'
[string "@AddOns\WeakAuras\GenericTrigger.lua"]:1138: in function `LoadDisplays'
[string "@AddOns\WeakAuras\WeakAuras.lua"]:1704: in function `LoadDisplays'
[string "@AddOns\WeakAuras\WeakAuras.lua"]:1520: in function <AddOns\WeakAuras\WeakAuras.lua:1393>
[string "@AddOns\WeakAuras\WeakAuras.lua"]:1688: in function `Resume'
[string "@AddOns\WeakAuras\WeakAuras.lua"]:1042: in function <AddOns\WeakAuras\WeakAuras.lua:1005>

### Reproduction Steps

导入WA字符串就报错

**Comment by mrbuds** [comment]
You aura called "FoxHunter_AS_CD" has an error, you need to fix or delete it.

**Comment by wangtao39** [comment]
FoxHunter_AS_CD这个WA光环是我一直在用的，上午还好用，等到晚上时候就报错了

**Comment by wangtao39** [comment]
> 你名为“FoxHunter_AS_CD”的光环有错误，你需要修复或删除它。

这个光环我一直在用，没有问题，并且当天上午也在用，等晚上用的时候就发生报错了

**Comment by InfusOnWoW** [comment]
We sadly don't speak chinese.
