### ISSUE TITLE
Incorrect information for some factions (the Faction Reputation trigger)

### ISSUE THREAD

**Issue by Nightwarden24** [WeakAuras/WeakAuras2#3494]
### Description

There are several special single-NPC factions on Retail. Examples:
- The Archivists' Codex
- Ve'nari
- Chromie
- Bizmo's Brawlpub
- Brawl'gar Arena
- Tormmok
- Leorajh
- Talonpriest Ishaal
- etc.

WeakAuras doesn't take into account these cases, provides and contains incorrect information about such factions. [GetFriendshipReputation()](https://wowpedia.fandom.com/wiki/API_GetFriendshipReputation) and [GetFriendshipReputationRanks()](https://wowpedia.fandom.com/wiki/API_GetFriendshipReputationRanks) functions should be used to get details. Last one, fortunately for us, again returns values since an unknown Shadowlands patch (I guess it's 9.1.5). 

Notes:
- There are only problems with standing and standing ID (ID may be greater than 8 for some factions) at the present time, but I would get all data from the above functions and not from GetFactionInfoByID()
- No simple way to get text of all player's standing ranks with a friend (only current). Will have to make a list with common values (like rank #i) for the Standing option. But I would like %standing to still return a localized text.

P.S. Blizzard uses the following code to get standing text for normal factions, because in some languages (ES, FR, IT etc) it depends on gender of the character:
```lua
GetText("FACTION_STANDING_LABEL"..standingID, UnitSex("player"))
```
I don't know how important this is, but we could do the same [here](https://github.com/WeakAuras/WeakAuras2/blob/main/WeakAuras/Prototypes.lua#L2156) and [here](
https://github.com/WeakAuras/WeakAuras2/blob/main/WeakAuras/Prototypes.lua#L2228)

### WeakAuras Version

3.7.8-13-gdb3bd18

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No erros

### Reproduction Steps

1. Create aura with Faction Reputation trigger
2. Select any single-NPC faction (in [that](https://wowpedia.fandom.com/wiki/FactionID) table they are marked with a special icon)
3. Сompare data from aura and in the player's reputation pane

**Comment by InfusOnWoW** [comment]
@mrbuds do you want to handle that?
