### ISSUE TITLE
Import / Export weird behavior

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#3496]
### Description

On exporting aura to the string import window appears.

### WeakAuras Version

WeakAuras 3.7.9

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

no errors

### Reproduction Steps

1) create new aura (anything)
2) export to string it
3) delete that aura (this step doesn't matter, just to not duplicate the aura)
4) import it back

from now

try to export to string any other aura

### Last Good Version

No idea

**Comment by Translitdk** [comment]
probably related to https://github.com/WeakAuras/WeakAuras2/issues/3482

**Comment by InfusOnWoW** [comment]
@mrbuds that's caused by bacb4cbb3a371ab4089dd8552e23021508fa18e5.

I can fix it tomorrow, but if you want to do it beforehand. The reason is that the "import" sets a OnTextChanged script, which isn't cleared in the "export" mode. The reverse situation exists for "OnChar",
