### ISSUE TITLE
Offset options for StopMotion aura backgrounds

### ISSUE THREAD

**Issue by Crelam** [WeakAuras/WeakAuras2#3497]
Thanks for the work on StopMotion file and tile sizes.  That'll really make texture creation easier.

Equally importantly, thanks for adding options for the background texture for StopMotion auras.  It makes putting an animation over a texture much more accessible.  Before I had to make multiple auras and anchor them to each other.  

However there is one adjustment that would make it perfect.  Can we have a scale, zoom, or Background Offset (like in a progress texture) for background textures of StopMotion auras?  This would help in aligning the animation with the texture.

Thanks again for all your hard work.

**Comment by InfusOnWoW** [comment]
I don't think any of zoom, scale or background offset would add much to stop motion textures. As stop motion more or less requires custom media, I think requiring custom media also for the background is fine.
