### ISSUE TITLE
Can't import groups with long list of nested auras

### ISSUE THREAD

**Issue by deemerz** [WeakAuras/WeakAuras2#3498]
### Description

When I try to import a group aura containing many nested auras I get the frame that doesn't show the Import button because it appears to be hidden behind the bottom edge of the screen. And I can't move given frame up because it's top border is snapped to the screen. So I can't import such auras at all.

Widows size: 3440x1440
Resolution scale: 100%
UI scale: turned on, 1.00

### WeakAuras Version

WeakAuras 3.7.9

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Try to use Import functionality.

### Screenshots

![image](https://user-images.githubusercontent.com/26042479/154937498-fec04a6a-f558-43c8-94db-e193c09ca10f.png)

**Comment by InfusOnWoW** [comment]
This will be fixed in a few weeks by the merging of the nested branch. Until then I suggest using a different ui scale.
