### ISSUE TITLE
'constant table overflow' when opening WeakAuras options (/wa)

### ISSUE THREAD

**Issue by Hekili** [WeakAuras/WeakAuras2#3503]
### Description

I expected WeakAuras' options to appear without new errors in the BugSack.  I tested with only WeakAuras + BugSack + BugGrabber.

I did notice that the error occurs before my addons have finished loading.

### WeakAuras Version

WeakAuras 3.7.11

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x constant table overflow
[string "=[C]"]: ?
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:91: in function `LoadOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:105: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "WeakAurasOptions"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 130942 = 104081
 196348 = 253043
 Cyclone Water Visual = 21
 Crush = 29
 261885 = 62371
 Volatile Reaction = 126
 98175 = 241102
 Seabreeze = 143
 261886 = 209497
 2046 = 229481
 4092 = 15949
 6136 = 77903
 Shard of Afrasa = 189481
 12272 = 143443
 261887 = 117128
 Hips' Spare Fedora = 160403
 32736 = 261749
 49088 = 214022
 196352 = 54240
 261888 = 29781
 Fallen Prince's Welcome = 169295
 98177 = 160583
 196354 = 253042
 Infinite Marker of Helbrine = 225
 196355 = 207023
 261891 = 160990
 49089 = 179156
 98178 = 239827
 196356 = 207024
 261892 = 120796
 Heart of Iron = 248
 Dreamleaf = 200363
 Umber Ruinstrider = 262
 261893 = 36432
 Empowered Spellblade = 273
 0 = 276
 261894 = 125171
 196359 = 144497
 Jailer's Judgment = 306
 32737 = 202051
 Twilight Dust = 168804
 196360 = 54238
 261896 = 231176
 Gift of the Giants = 363
 196361 = 49023
 261897 = 101519
 Ensemble: Elite Cruel Gladiator's Felskin Armor = 372
 98181 = 258267
 Eye of Doom = 382
 Y = 188871
 X = 388
 261899 = 22052
 Z = 391
 49091 = 249038
 130950 = 64733
 Thistleleaf Cluster Guard - Conversation = 398
 261900 = 261763
 d = 409
 196365 = 130008
 261901 = 76250
 Summon Chase Targets Cue = 416
 Terrorspike = 420
 Uncontrolled Darkness = 423
 196366 = 75999
 261902 = 101539
 12273 = 182473
 261903 = 63736
 24546 = 103776
 32738 = 91282
 49092 = 142748
 130952 = 91038
 261904 = 62829
 King of the Fire Festival = 148550
 196369 = 130009
 Grand Delusions = 185981
 Valarjar's Path = 197244
 Empty Void Crystal = 471
 261906 = 30229
 Ogre Raise Visual = 474
 Upload: Advanced Adventurer Augment = 477
 Armored Recollection = 480
 261907 = 162190
 261909 = 30210
 196374 = 154299
 261910 = 222589
 196375 = 255200
 261911 = 142977
 Guardian Eggs Sparkles = 561
 32739 = 261353
 98188 = 144040
 196376 = 91444
 261912 = 222719
 Silkweave Hood = 588
 261913 = 72861
 Serrated Slash = 606
 See Invis Tier 2 = 622
 98189 = 180149
 130957 = 252099
 261914 = 30222
 196379 = 214703
 261915 = 30221
 Damage Amplification: Shadow = 636
 65479 = 23670
 98190 = 214338
 130958 = 7032
 196380 = 50732
 261916 = 188763
 196381 = 251470
 261917 = 188748
 98191 = 261645
 196382 = 58059
 Whirling Saber = 674
 196383 = 206827
 261919 = 72862
 32740 = 27643
 Reload Explode = 190163
 196384 = 20584
 261920 = 223937
 Taze = 702
 Reaves Bubbles = 708
 196385 = 255170
 261921 = 186245
 The Green Tower = 718
 98193 = 215383
 Gaze = 727
 Delvar Ability: Breath of Sindragosa = 734
 Daze = 737
 Award Honor - PvP - Battleground - Loser = 190276
 Upload: Resource Blueprints = 741
 196387 = 171373
 Raze = 744
 49097 = 24947
 65481 = 29502
 Maze = 749
 130962 = 182852
 196388 = 5206
 261924 = 162191
 [INTERNAL, DNT] Phase Control - A = 768
 Amber Glitterwing = 175613
 Fling Muck = 177131
 261925 = 203712
 Fel Fire Channel = 252064
 130963 = 91408
 261926 = 231154
 32741 = 222280
 130964 = 80644
 196392 = 261971
 261928 = 92736
 Track Undead = 907
 Death Grip (test spell for Caroline) = 190364
 196393 = 1640
 The Rocket's Pink Glare = 928
 130965 = 18206
 Fancy Footwork = 177358
 196395 = 236823
 49099 = 181364
 130966 = 74639
 196396 = 104506
 196397 = 255165
 98199 = 82334
 Empyrial Breastplate = 989
 196398 = 160716
 261934 = 226084
 196399 = 60508
 261935 = 125862
 32742 = 222282
 49100 = 181345
 261936 = 226085
 Menacing Shout = 1027
 Matrix Surge = 1039
 Dread Expanse = 1043
 Trappings of Vaulted Secrets Intellect Bonus = 190513
 196402 = 85265
 261938 = 86253
 Blue Dragon Tail Costume = 1059
 196403 = 59091
 261939 = 44851
 65485 = 247802
 Crimson Vial = 1083
 Shadow Port = 1092
 Powerful Weapon Crystal = 1096
 Beyond the Gates = 255469
 130971 = 64639
 196406 = 15826
 261942 = 127281
 Collector's Edition: Gilded Ravasaur = 1128
 32743 = 131897
 65486 = 90275
 98204 = 96701
 196408 = 126835
 Going Up = 146025
 Let's Do Lunch: Orgrimmar = 1151
 196409 = 59738
 261945 = 127282
 98205 = 173057
 130973 = 203053
 523893 = 17793
 196411 = 127461
 261947 = 49503
 98206 = 173058
 196412 = 31282
 523896 = 

### Reproduction Steps

1. Enter game.
2. Type `/wa`.
3. Observe red sack.

### Last Good Version

I can revert if needed.

### Screenshots

Adding the follow-up errors instead.

```
1x UNKNOWN ERROR
[string "=[C]"]: ?
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:91: in function `LoadOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:105: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "WeakAurasOptions"
```

```
2x (null)
```

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/8121949/WeakAuras.zip)

**Comment by glassleo** [comment]
I'm getting this too after opening /wa along with this error:

```lua
1x UNKNOWN ERROR
[string "=[C]"]: ?
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:91: in function `LoadOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:105: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function <FrameXML\ChatFrame.lua:5131>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function <FrameXML\ChatFrame.lua:4848>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "WeakAurasOptions"
```

**Comment by glassleo** [comment]
I'm getting spammed with errors as well after opening WA options through ``/wa``

```
3x UNKNOWN ERROR
[string "=[C]"]: ?
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:91: in function `LoadOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:105: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function <FrameXML\ChatFrame.lua:5131>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function <FrameXML\ChatFrame.lua:4848>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "WeakAurasOptions"
```

---

```
3x constant table overflow
[string "=[C]"]: ?
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:91: in function `LoadOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:105: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function <FrameXML\ChatFrame.lua:5131>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function <FrameXML\ChatFrame.lua:4848>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "WeakAurasOptions"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 130942 = 122074
 196348 = 259059
 Cyclone Water Visual = 13
 Crush = 21
 261885 = 64037
 Volatile Reaction = 123
 98175 = 253370
 Seabreeze = 141848
 261886 = 238316
 2046 = 247875
 4092 = 16221
 6136 = 79907
 Shard of Afrasa = 151
 12272 = 90472
 261887 = 149332
 Sign of Battle = 154
 32736 = 101166
 49088 = 159573
 196352 = 55627
 261888 = 30496
 Fallen Prince's Welcome = 112778
 98177 = 214808
 196354 = 259058
 Infinite Marker of Helbrine = 98803
 196355 = 237115
 261891 = 214971
 49089 = 223703
 98178 = 151101
 196356 = 237116
 261892 = 156670
 Heart of Iron = 245
 Dreamleaf = 248
 Umber Ruinstrider = 261
 261893 = 37354
 Empowered Spellblade = 272
 0 = 275
 261894 = 165211
 196359 = 174499
 Gilnean Raven = 303
 32737 = 234853
 49090 = 257223
 196360 = 55625
 261896 = 150373
 Gift of the Giants = 356
 196361 = 50238
 261897 = 116686
 Ensemble: Elite Cruel Gladiator's Felskin Armor = 365
 98181 = 198888
 Eye of Doom = 372
 Y = 376
 X = 379
 261899 = 22534
 Z = 381
 49091 = 257255
 130950 = 66450
 Thistleleaf Cluster Guard - Conversation = 388
 261900 = 101180
 d = 399
 196365 = 175129
 261901 = 78237
 Summon Chase Targets Cue = 406
 Delvar Perk: Death Gate = 410
 Uncontrolled Darkness = 413
 196366 = 77993
 261902 = 116706
 12273 = 225294
 261903 = 65459
 24546 = 121321
 32738 = 96575
 49092 = 201508
 130952 = 96067
 261904 = 64518
 Quilboar Costume = 158061
 196369 = 175130
 Grand Delusions = 126428
 Valarjar's Path = 167047
 Empty Void Crystal = 457
 261906 = 30957
 Ogre Raise Visual = 460
 Upload: Advanced Adventurer Augment = 463
 Armored Recollection = 466
 261907 = 215491
 261909 = 30938
 196374 = 211628
 261910 = 150371
 196375 = 174495
 261911 = 166535
 Guardian Eggs Sparkles = 547
 98188 = 202996
 196376 = 96801
 261912 = 244781
 Silkweave Hood = 574
 261913 = 74803
 Serrated Slash = 600
 See Invis Tier 2 = 616
 98189 = 224198
 130957 = 193860
 261914 = 30950
 196379 = 240943
 261915 = 30949
 Damage Amplification: Shadow = 630
 65479 = 24161
 98190 = 240754
 130958 = 7063
 196380 = 174465
 261916 = 228401
 196381 = 258417
 261917 = 228386
 98191 = 100474
 196382 = 174459
 Whirling Saber = 668
 196383 = 237022
 261919 = 74804
 32740 = 28123
 Reload Explode = 684
 196384 = 21089
 261920 = 31917
 Taze = 186416
 Reaves Bubbles = 695
 196385 = 174456
 261921 = 227099
 The Green Tower = 705
 98193 = 251950
 Gaze = 714
 Delvar Ability: Breath of Sindragosa = 182343
 Daze = 726
 Award Honor - PvP - Battleground - Loser = 728
 Upload: Resource Blueprints = 731
 196387 = 174451
 Raze = 734
 49097 = 206109
 65481 = 30048
 Maze = 154984
 130962 = 193063
 196388 = 5228
 261924 = 215492
 [INTERNAL, DNT] Phase Control - A = 755
 Amber Glitterwing = 117763
 Fling Muck = 119116
 261925 = 12757
 Fel Fire Channel = 169431
 130963 = 96743
 261926 = 150360
 32741 = 173596
 130964 = 82707
 261928 = 99438
 Track Undead = 892
 Death Grip (test spell for Caroline) = 898
 196393 = 1617
 The Rocket's Pink Glare = 903
 130965 = 18585
 196394 = 1611
 196395 = 204928
 49099 = 224761
 130966 = 76621
 196396 = 122942
 196397 = 174440
 98199 = 84449
 Empyrial Breastplate = 156277
 196398 = 214843
 261934 = 246258
 196399 = 180488
 261935 = 166543
 32742 = 173598
 49100 = 224742
 261936 = 246259
 Menacing Shout = 995
 Matrix Surge = 144910
 Dread Expanse = 1009
 Trappings of Vaulted Secrets Intellect Bonus = 1011
 196402 = 87354
 261938 = 88372
 Blue Dragon Tail Costume = 1023
 196403 = 60702
 Charm Drakuru Servant = 205720
 65485 = 256637
 Crimson Vial = 1048
 Shadow Port = 1057
 Powerful Weapon Crystal = 1061
 Beyond the Gates = 174941
 130971 = 66360
 196406 = 16101
 261942 = 169443
 32743 = 179078
 65486 = 94502
 98204 = 198878
 196408 = 191891
 Going Up = 92562
 196409 = 61359
 261945 = 169444
 98205 = 220969
 130973 = 235259
 523893 = 18158
 196411 = 169861
 261947 = 50727
 98206 = 220970
 196412 = 31992
 523896 = 183041
 523897 = 32631
 196413 = 169863
 261949 = 257860
 196414 = 31994
 261950 = 257861
 Mephistroth Dissolve Out = 1194
```

---

```
72x (null)
```

**Comment by glassleo** [comment]
No errors unless I open the options window and the auras themselves seem to work just fine. I'm also able to edit my auras fine, although the game gets a bit laggy due to the constant error spam. Reloading the UI stops the errors from happening until I open the options window again.

**Comment by zaldor30** [comment]
Also getting errors:
#1:
Message: constant table overflow
Time: Thu Feb 24 14:34:47 2022
Count: 1
Stack: constant table overflow
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:91: in function `LoadOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:105: in function `OpenOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:153: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5185: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4885: in function <Interface\FrameXML\ChatFrame.lua:4881>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: 

Error #2:
Message: UNKNOWN ERROR
Time: Thu Feb 24 14:34:47 2022
Count: 1
Stack: UNKNOWN ERROR
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:91: in function `LoadOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:105: in function `OpenOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:153: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5185: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4885: in function <Interface\FrameXML\ChatFrame.lua:4881>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = nil

Error #3:
Message: (null)
Time: Thu Feb 24 14:34:47 2022
Count: 2

**Comment by Stanzilla** [comment]
We're currently still investigating and working on the issue
