### ISSUE TITLE
UI:Accessability for big UI scaled (Eyesight)

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#3506]
**Is your feature request related to a problem? Please describe.**
I have bad eye sight and therefore have most of my UI very big scaled so I can read better. 
Some UI elements are hard to use, but especially elements that dont scale in a better way.

One example:

![image](https://user-images.githubusercontent.com/4364044/155520115-e6680db6-1c5c-4811-b772-81b251a84162.png)

**Describe the solution you'd like**
The table shown above could be split in half or made a simply checkbox option?

**Describe alternatives you've considered**
None. I simply must look up for example bosses ids from black temple then.

**Additional context**
This also happens when importing a very large weakauras, which shows children. The button "yes im okay with custom code, install please" is hidden below all listed children. If the list of children expands off the screen, you cant get to the "yes install" button at all. 
"Install button" could be relocated, or children could be toggled off by default? Dont now..

**Comment by InfusOnWoW** [comment]
The import interface will change in a few weeks and that tooltip is gone.

As to the encounter id tooltip. That's a similar to https://github.com/WeakAuras/WeakAuras2/issues/2824.

Note, that this likely won't be fixed in the nearer future.
