### ISSUE TITLE
AceConfig-3.0 unexpected symbols LUA Errors

### ISSUE THREAD

**Issue by FrankMcGovern** [WeakAuras/WeakAuras2#3507]
### Description

Getting the two LUA errors at every load in or UI reload.

### WeakAuras Version

WeakAuras 3.7.11

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```
Message: ...WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1159: unexpected symbol near 'char(8)'
Time: Sat Feb 26 20:55:54 2022
Count: 1
Stack: ...WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1159: unexpected symbol near 'char(8)'

Locals: 
```

```
Message: ...WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1159: unexpected symbol near 'char(8)'
Time: Sat Feb 26 20:55:54 2022
Count: 1
Stack: ...WeakAuras\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1159: unexpected symbol near 'char(8)'

Locals: 
```

### Reproduction Steps

Shows up at any load up or UI reload.

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/8147906/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
That very much looks like a broken installation. Try reinstalling WeakAuras.
