### ISSUE TITLE
WA in-game export/import failure

### ISSUE THREAD

**Issue by Sladlock** [WeakAuras/WeakAuras2#351]
[WeakAuras_lua.zip](https://github.com/WeakAuras/WeakAuras2/files/1700740/WeakAuras_lua.zip)

What steps will reproduce the problem?
When exporting WAs via in-game link, the recipient is unable to import and gets stuck at a window reading 'Requesting display information from [myplayer-realm]...'.
What is the expected output? What do you see instead?
I expect them to see the WA description and import button. However, the pop-up window only shows the above message and hangs there indefinitely (over 20 minutes).
Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes
What version of WeakAuras are you using?
Both of us are using WeakAuras 2, version 2.5.6
Was it working in a previous version? If yes, which was the last good one?
I have previously exported to other friends this way, though I'm unsure of the version at the time. This is my first attempt exporting to this friend.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
Neither of us is getting any errors, just the hanging message in the pop-up window.

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`
The error occurs on any WAs I attempt to share. Full library zip attached. Below is the most simple and shortest.
In case you do know which aura is problematic, please export the string and paste it below.

dydydaGAevA9cfTlHkBJOMjby2cUjbQBlQ2PI2lSBL6NiQAyu53kzOikA4iYPr6Xs0Xq4CczHcLwkbYIvrlxKhku4PKwgrEUknrcYuPyYuY0rDrevCvHQEMcUUuTrc1HLYMPkBxH8nr5ZuvtJs9DeLAKikmovy0sW4jGojb1TiKRjPZlH(Rc1Lv1RruYGagO5qTGAbd0IK3Z7(mMIKKQqPLRnoH6T2S4qZ)cL8XBeGWtYb6zlfJvyLGbtciUkxjQzYoNuuMDMTdEIQhykbXv5krnt25KIYSZSDWtu9aZbiwo7G4iIqYnuLJKJgGNO6bM2y6Ils25CoNZDez7YadLuA5N(7LmtFj9sxBmDqdRMfmqPB)0QtcgO59atHbmyOCl8BggO59atHbmyOLH29cd0lD7hEOcjO4fwiO59atHbQqckEHfcXcgmulQNhTSh4IWanVhykmGbdn1kFyGM3dmfgWGH61kz6Add08EGPWagmusJiXTWVzyGM3dmfgWGHMwHhgO59atHbmyOCl8BwcgO59atHbmyWqtVpDTnfj9qB9u7SLGs3uEC5kNu453ctcOw0l523LmD0dTfcqBLmD0BsuF)pj4L1JPichu(fiR0y(ysidTWt9lWyk5Gs3uE8LBj(TWKa6UNBsuF)pDXKaQf9sk0kAEbYc49yOoOKn1IlGjXHd65kz9jH3ItRnJtONTsYYpT6BRyScRemysaX2vjcjz3HtAilklAaEIQYykbXhrdY1QDTAN5goCzWtuDaZbiw2okAGqY2nyl5IQv4jQkJPnMeGHsTGsgFlWfGYjQV)NGbkxK0d9YnUFH23)OFZqBDEbTF)XTZ7kDk4L1JyH2V)4(MYiwO97pM0Nk)nx4BbUaobdg6fQuC14KHoctcBjcWaa

**Comment by InfusOnWoW** [comment]
We can't send auras across realms (except if they are connected.) That's a limitation of World of Warcraft. Though we should show a error message after a timeout. I'll see what we can do there.

**Comment by Sladlock** [comment]
Ah, thank you so much. That was the issue. I had him swap to a toon on my realm and the WAs imported just fine.

**Comment by InfusOnWoW** [comment]
I added a note and added a timeout, so that the next person won't be confussed.
