### ISSUE TITLE
Errors caught when opening WeakAura in-game after having updated/deleted some auras

### ISSUE THREAD

**Issue by Quietpaw** [WeakAuras/WeakAuras2#3510]
### Description

When I open the WA panel (/wa) in game since this latest release and since updating some of my auras, I receive 3 LUA errors. It only happens the first time I open the panel a session, and will happen again if I reloadui. I tried deleting each of the auras that I have imported one at a time, with no luck. I tried restarting WoW entirely, also no luck. I am now assuming the error is in the addon itself.

Note that I didn't notice errors when I first opened WA today before I deleted and updated my auras inside the panel. So I don't know if a fresh install had errors or not. I did a house cleaning to remove SoD auras and update others. That's why I tried deleting each of my still-existing auras before reporting this bug.

### WeakAuras Version

WeakAuras 3.7.11

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### ERROR 1
`11x constant table overflow
[string "=[C]"]: ?
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:91: in function `LoadOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:105: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function <FrameXML\ChatFrame.lua:4881>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "WeakAurasOptions"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 130942 = 121774
  = 2
 Cyclone Water Visual = 13
 Crush = 21
 261885 = 63975
 Volatile Reaction = 123
 98175 = 253262
 Seabreeze = 141783
 261886 = 238214
 2046 = 247778
 4092 = 16204
 6136 = 79851
 Shard of Afrasa = 151
 12272 = 90645
 261887 = 149046
 Sign of Battle = 154
 32736 = 100843
 49088 = 159287
 196352 = 55570
 261888 = 30455
 Fallen Prince's Welcome = 112671
 98177 = 214688
 196354 = 258949
 Infinite Marker of Helbrine = 167322
 196355 = 237010
 261891 = 214853
 49089 = 223596
 98178 = 150822
 196356 = 237011
 261892 = 156391
 Heart of Iron = 245
 Dreamleaf = 248
 Umber Ruinstrider = 261
 261893 = 37292
 Empowered Spellblade = 272
 0 = 275
 261894 = 164949
 196359 = 174449
 Gilnean Raven = 303
 32737 = 234752
 49090 = 257116
 196360 = 55568
 261896 = 150292
 Gift of the Giants = 356
 196361 = 50180
 261897 = 116378
 Ensemble: Elite Cruel Gladiator's Felskin Armor = 365
 98181 = 198853
 Eye of Doom = 372
 Y = 376
 196363 = 170035
 261899 = 22505
 Z = 381
 49091 = 257148
 130950 = 66386
 Thistleleaf Cluster Guard - Conversation = 388
 261900 = 100857
 d = 399
 196365 = 174881
 261901 = 78183
 Summon Chase Targets Cue = 406
 Delvar Perk: Death Gate = 410
 Uncontrolled Darkness = 413
 196366 = 77934
 261902 = 116398
 12273 = 225188
 261903 = 65392
 24546 = 120992
 32738 = 96323
 49092 = 201243
 130952 = 95821
 261904 = 64452
 Quilboar Costume = 158001
 196369 = 174882
 Grand Delusions = 126324
 Valarjar's Path = 167005
 Empty Void Crystal = 454
 261906 = 30916
 Ogre Raise Visual = 457
 Upload: Advanced Adventurer Augment = 460
 Armored Recollection = 463
 261907 = 215376
 261909 = 30897
 196374 = 211501
 261910 = 150290
 196375 = 174447
 261911 = 166549
 Guardian Eggs Sparkles = 544
 98188 = 202737
 196376 = 96553
 261912 = 244679
 Silkweave Hood = 571
 261913 = 74738
 Serrated Slash = 597
 See Invis Tier 2 = 613
 98189 = 224091
 130957 = 193796
 261914 = 30909
 196379 = 240848
 261915 = 30908
 Damage Amplification: Shadow = 627
 65479 = 24138
 98190 = 240659
 130958 = 7063
 196380 = 174445
 261916 = 228297
 196381 = 258309
 261917 = 228282
 98191 = 100179
 196382 = 174443
 Whirling Saber = 665
 196383 = 236917
 261919 = 74739
 32740 = 28091
 Reload Explode = 681
 196384 = 21055
 261920 = 31870
 Taze = 186361
 Reaves Bubbles = 692
 196385 = 174438
 261921 = 226998
 The Green Tower = 702
 98193 = 251844
 Gaze = 711
 Delvar Ability: Breath of Sindragosa = 182254
 Daze = 723
 Award Honor - PvP - Battleground - Loser = 725
 Upload: Resource Blueprints = 728
 196387 = 174436
 Raze = 731
 49097 = 206103
 65481 = 30007
 Maze = 154990
 130962 = 192996
 196388 = 5230
 261924 = 215377
 [INTERNAL, DNT] Phase Control - A = 752
 Amber Glitterwing = 117672
 Fling Muck = 118982
 261925 = 12744
 Fel Fire Channel = 169397
 130963 = 96492
 261926 = 150288
 32741 = 173336
 130964 = 82654
 261928 = 99149
 Track Undead = 889
 Death Grip (test spell for Caroline) = 895
 196393 = 1619
 The Rocket's Pink Glare = 900
 130965 = 18562
 196394 = 1613
 196395 = 204673
 49099 = 224654
 130966 = 76560
 196396 = 122635
 196397 = 174432
 98199 = 84394
 Empyrial Breastplate = 156238
 196398 = 214725
 261934 = 246158
 196399 = 180423
 261935 = 166226
 32742 = 173338
 49100 = 224635
 261936 = 246159
 Menacing Shout = 992
 Matrix Surge = 144823
 Dread Expanse = 1006
 Trappings of Vaulted Secrets Intellect Bonus = 1008
 196402 = 87296
 261938 = 88318
 Blue Dragon Tail Costume = 1020
 196403 = 60645
 Charm Drakuru Servant = 205662
 65485 = 256530
 Crimson Vial = 1045
 Shadow Port = 1054
 Powerful Weapon Crystal = 1058
 Beyond the Gates = 174865
 130971 = 66293
 196406 = 16084
 261942 = 169128
 Collector's Edition: Gilded Ravasaur = 1090
 32743 = 178811
 65486 = 94268
 98204 = 198848
 196408 = 191813
 Going Up = 92657
 Let's Do Lunch: Orgrimmar = 1111
 196409 = 61300
 261945 = 169129
 98205 = 220866
 130973 = 235160
 523893 = 18138
 196411 = 169551
 261947 = 50669
 98206 = 220867
 196412 = 31945
 523896 = 182767
 523897 = 32582
 196413 = 169553
 26194`

### ERROR 2
`11x UNKNOWN ERROR
[string "=[C]"]: ?
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:91: in function `LoadOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:105: in function `OpenOptions'
[string "@WeakAuras\WeakAuras-3.7.11.lua"]:153: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5185: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4885: in function <FrameXML\ChatFrame.lua:4881>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "WeakAurasOptions"
`

### ERROR 3 (this one is not very informative!)
`43x (null)`

### Reproduction Steps

1. Update to the latest WA 3.7.11
2. Open WA (/wa) and delete some old auras (i.e. sanctum auras)
3. Add/Update some other auras
4. Reload UI
5. Open WA (/wa)

**Comment by Stanzilla** [comment]
Fixed in .12

**Comment by ntowle** [comment]
@Stanzilla I'm on 3.7.12 and just got this:

```
Message: constant table overflow
Time: Mon Feb 28 11:41:13 2022
Count: 1
Stack: constant table overflow
[string "=[C]"]: ?
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:91: in function `LoadOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:105: in function `OpenOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:153: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5185: in function <Interface\FrameXML\ChatFrame.lua:5131>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4849: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4885: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

**Comment by Stanzilla** [comment]
@ntowle Even after doing a `/reload`?

**Comment by ntowle** [comment]
@Stanzilla I believe it was right after a /reload, in any case I had the error on my screen and at the top of the WeakAuras window it said 3.7.12.

**Comment by Stanzilla** [comment]
> @Stanzilla I believe it was right after a /reload, in any case I had the error on my screen and at the top of the WeakAuras window it said 3.7.12.

Can you try again after restarting WoW?

**Comment by ntowle** [comment]
@Stanzilla It doesn't seem to be happening again. Will update if it does. All I did was /reload then type /wa afterwards to get the earlier repro. Tried just now after restarting client, after logging out/in, and after /reload and it did not occur.
