### ISSUE TITLE
WeakAurasOption error when changing settings in Display

### ISSUE THREAD

**Issue by komxela** [WeakAuras/WeakAuras2#3517]
### Description

Was fiddling with some Display settings in weakauras and i am getting 18x WeakAurasOptions error.  Hasn't had this error before the latest update.

### WeakAuras Version

3.7.12

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

18x WeakAurasOptions\CommonOptions.lua:682: attempt to concatenate local 'display' (a table value)
[string "@WeakAurasOptions\CommonOptions.lua"]:682: in function `member'
[string "@AddOnSkins\Libs\Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@AddOnSkins\Libs\Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:512: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:501>
[string "=[C]"]: ?
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasTwoColumnDropDown.lua"]:137: in function <...-Widgets\AceGUIWidget-WeakAurasTwoColumnDropDown.lua:136>
[string "=[C]"]: ?
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@MythicDungeonTools\libs\AceGUI-3.0-41\widgets\AceGUIWidget-DropDown.lua"]:362: in function <...ls\libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:360>

### Reproduction Steps

1. Opened weakauras
2. Fiddling with "Display" settings on some weakauras for the latest raid made by causese
3. Error appeared

### Last Good Version

3.7.11

**Comment by mrbuds** [comment]
Hi, thanks for the report.

> Tested with only WeakAuras

Error show you use other addons, please test without them.

> Fiddling with "Display" settings 

We need exact steps, from /reload to what trigger the aura.

>  some weakauras for the latest raid made by causese

We need an export of that aura, don't let us guess what it is.

**Comment by InfusOnWoW** [comment]
No response.
