### ISSUE TITLE
Issue with "Overlay Charged Combo Points" & "Deeper Strategem"

### ISSUE THREAD

**Issue by Kogosh** [WeakAuras/WeakAuras2#3518]
### Description

Echoing Reprimand charged combo point highlighting not working correctly with kyrian legendary & deeper strategem talent selected. 

### WeakAuras Version

3.7.12

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

While wearing the kyrian legendary for rogues, with the deeper strategem talent selected, use Echoing Reprimand on a target and note that the charged combo points don't line up with the correct radial settings of the 6 deeper strategem combo points.  

### Screenshots

![image](https://user-images.githubusercontent.com/100788025/156398548-175ebe80-6bbd-468f-bc91-d695f39a75d3.png)
![image](https://user-images.githubusercontent.com/100788025/156398575-bb155e22-d938-4de4-93a7-b1f56e0ea1c9.png)

### Export String

**!WA:2!9EvxVTrwz4DwVv7MPq3eVLOTTlRgQqrjD76e78vtlD76VsI36K4m2TjfcepJNJ9mTtMz6zMjXPBGkmIsqCdY)a4IiUSIl8TCdSIFaVkIFaOkeiUaKi3bxq59CMX2XTEtlTaJ045CM5817ZZZ7Z5yHBh1vDYyZglEIOBfvlQ2(FWHQkvUNg12jTTPn9ZIejsHiteB6NOAt1i0uHF0zWuMgp4bkunPs22MEgoYUvumjrudANoD3vQw1L4j0sXQIUnTGTHLNA6SlxkR8bbTPOXdiNQvq5GjtqqiYbE2v2MqDnSTEFHYRtRhoouLkE47CNr21tH6jQw1WYWvxmf(WtSHh1OwnSBNFeAyXhDGgr1VA1s76qOlMnFH5Vv(uEyfzfFQsIgUoetZCAUIpX1xLSnXYRi2AJ6T2mDYIL2SyPKYLs5JdUQJPYUeQSLYwexrzEtvxKOy6P3PRfOeSRYflKnF(M(wHlbXWinRwnIZqfVVVcLinVVPP0A6gEKVi4Rbb4ahqj1WaKTCLRrT9DA6smRYXnyGlAO1mtXzLwG9b1k2wvnQj2Qkfxsf9OkEkrokaNNN9k2yOwmTC2Sl3YWQQnDlfg2jgc25SW5lYHk(EyhwXHdRIhHZdHAPyE7aWN0uXYiOFZaV78FbrXLnveRAE6VnmCklSjhQHijRfBYWvQlbxyAUnynLTeGPsTLIH18WKyhGPGPHzGzXNd(SV5aw)mcwhPmTv0Mx1dftwEdlVLpkUetHKvLHHVLOCftfxxwPuUO8HviHVHwlLjV)c1xU09LlulAL7U)1u9Dj0n3vi4zDbycXwkA3131JOTKs9OX7wZWkAC4TF8zH3bgW5SAexfpwurysDgpyPP3YLbQK64hiLt4tnDUGUNNJ7vhF8DuQzhZWE8CtSO6nvxCI4JhhodcyIWGIWqIq0Zmc8E7h9j46ytfvxBQ6s2AKYWfGpOPJ9oekd5g4q2N7uTmCw4RH4ZfGZbN)j8xVPnIVkE20l(jxh(q5cS3bsW3ObRJmrAzNZZk6QBVtADfAnIwA7TuT5Yh3YW7ls9T4k1uiTBlZh0OXB0Mari4Rl2SZQOmCrrNHyzCBtkfOLzl7h)gniwAjTQzs8H4eyuya4RMx8iuHrcGQqtJfVXF7FXUEQqe5kD8rERjIn70h0fH1BqT94tVqQQ2wEodop14bsR6ROXK0sLkrdDcICaMOjZZpCp)WWWhIvv7WpQ6eJA6Efov8zMlwcv(GIG4vFepG4kMYhWkgiQkd3GPBGRnIQRblwgcRX)EfeYuWVFD(3)KraIS8klCRSyn6dq9o6w8Mh1DEdc2fVXFyq21CpFbbNbXHnzOsJR8kFKxGoAnQIddtDoB68jxQqPvsLpz6BMmtMCLYD7SQvqtwu)6muxSnua6mBowMAvLkKnsQPTIL7gRruUxsesD3yjIMHYgHT0Ddzm(2CQjCQhZRMcKGLi)SjJx5fNEgSyQlOULbLAt1F2OYWQmmYrou7A4C6ggFWhfPPkc3ASGuov(SlNXzind3kuIhzZoeFdgXZ2j4CnDnvS8yTwn3YfZLjlCjrA4G5mtpXSDpXmpzGxmi6dEl73jpGVxbxWgrEhdnp92IexYwO2soESjInb8vy70GwSjql2JBbmFhSxxwX0rxjcCz4JBGYehwKQdFARcQoZL3pEbssk1WIjxj6od1vJesfWN3YMAGIpEu3mD(vsFZ1YvmlmNiet0zWUDiy3GtT)vGucqAbw(fKjAcilEZCPwNLD9x(hSR)PqeyEDyHYWIqo4hQ32Sb(mU)cCZbG894LalXTpGLzwhWkLHcmNbyvqgkIdFjUlaClw2pC7h)gWA)12z5VQshWra(ocWgW3f(ErGnz5UqzqjKf6XP8QpcQug06MDc8etOAzEMiuJvjiZu)nHDohC3YW9atyVDrAiXTmwYF6QRo53Eo4hPd3xhqpSrax473EQ8aFOreylbOoSBlBKPWD1RyA4ug3BaSaB4oIWpaE4XfdxbEe85OqMX6SThqfj8J1bJtmNh(jW(b0k8t7LgZgDYUu4FEw(vpu4lyGFTO3j7d9(npnJF7p3U)5oepyHfMu6fCEcvuDwHWAGk3sp1I34x9HSRCb1xqakDXytZ9C5NfSmOkW3yRZ4uwL)H6fIepw8M8YZJdQZFQk(llXy02MixwIN5UE4Z7GpzTE9WN3zmrj8Y0gRiPWsVLUUuNolDjPe4nE4f9yogJj9XsJgwwACPebDfDH8PwHZI0hjn6ObTb3ryu(aog(Y4JnEIXWrA0GjhhO4Jnw7L0lxNUtqNerJqrgahGa7YqGeWSnzhvAfFVCwDbBoI8BFjqenIPNY6Hp7brcOQmgylXNi00zvEmiQn80F44zgIlfoB9e99Vn3jiyd27Ljm0Hgcn5Ly6Ogo(MUKflE7O7keT(PvzoPepz(BdKe8Jo(lc6bdmQl8oSLyFqeA8llvdVvXBf8MMaRJ3Q4Tsir)APsA3zlYofA3nCi(Yy9Rf2Pq0SZwuXwG4HrCjgfZpM7OhBaF5cdgKkjbtEQGKn5ibptgPpEUmd7t23f3R4eSB7E8Natx0Uf9udTBZGoj793rl313(E3Tq61xE7L0zUXVilx4NDcgTZ1FJ2JV9Wj4Qovxx1dJYV()MR6u9Xv9pEM)hVR5Rf7nfSxMtJ03oJwVQ)nVf(FGnF9OVuzkgFIxv(BXFJ2dF6dF6t3dxztJu50T)NyhJ)6ZFN6vJSMUpK1VmABYcdRxGs5KzfU(7NZB7GcCyleZr0DV36DriptXvxvB5v3EzhkhV6I5myleUrYneU)pMJN45jM4CgdjMoS6RSMmGs7lnobllCMUzH)6lWV6jlmGfhItKbS47XyrKI6LelIdeNerEc5rNZY2hHsUVVbLWpPpB7bDotgWTizYiEgfZKemEVn56nCVzISWbJQJf1pZBg85EdgR)3ptevezWWKrniQ(LkfAN5PZ95273fTFPEj4ASJZWSSNpTL2kjVBg31Y7T9uVKNzfL3CAn62)(1)3p**

**Comment by InfusOnWoW** [comment]
Your aura has a strange settings of min and max progress. I'm suprised it shows at all.

I think it should work if you set for each combo point, the min progress to one less.
So for the first combo point you want:
Min Progress: 0
Max Progress: 1
