### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by betarantes** [WeakAuras/WeakAuras2#3522]
### Description

i have this Error Message on my Warrior in tbc classic:

Message: [string "Error in: GCD - Overpower Low Rage"]:2: attempt to compare number with nil
Time: Fri Mar  4 10:50:13 2022
Count: 1
Stack: [string "Error in: GCD - Overpower Low Rage"]:2: attempt to compare number with nil
[string "Error in: GCD - Overpower Low Rage"]:2: in function <[string "Error in: GCD - Overpower Low Rage"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:611: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:537>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:826: in function `ScanWithFakeEvent'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:1138: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1704: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1520: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1393>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1688: in function `Resume'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1042: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1005>

Locals: <none>

### WeakAuras Version

3.7.13

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: [string "Error in: GCD - Overpower Low Rage"]:2: attempt to compare number with nil
Time: Fri Mar  4 10:50:13 2022
Count: 1
Stack: [string "Error in: GCD - Overpower Low Rage"]:2: attempt to compare number with nil
[string "Error in: GCD - Overpower Low Rage"]:2: in function <[string "Error in: GCD - Overpower Low Rage"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:611: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:537>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:826: in function `ScanWithFakeEvent'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:1138: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1704: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1520: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1393>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1688: in function `Resume'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1042: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1005>

Locals: <none>

### Reproduction Steps

login an in game

**Comment by InfusOnWoW** [comment]
We obviously can't reproduce with those steps.

**Comment by Stanzilla** [comment]
This is an error in your "GCD - Overpower Low Rage" aura, not WA itself.

**Comment by InfusOnWoW** [comment]
Well could still be a bug. But can't help with if the reporter does not give us any information.
