### ISSUE TITLE
WAs not showing

### ISSUE THREAD

**Issue by hoviwan** [WeakAuras/WeakAuras2#3523]
### Description

One of my accounts, none of the WAs are being shown/found. 

### WeakAuras Version

WeakAura 3.7.13

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Login account (hoviwanx)
Any characters - no WAs being shown

Login secondary account (hovikenobix)
WAs - working

**Comment by StanzillaManticore** [comment]
We need more info, what did you use to install WA, are you sure the files are all correctly set up?

**Comment by Stanzilla** [comment]
We need more info, what did you use to install WA, are you sure the files are all correctly set up?

**Comment by hoviwan** [comment]
I always update WA from curseforge.com, and it was the most recent version 3.7.13. However, I believe I noticed this issue on 3.7.12. The files in my Account > SavedVariables have not been touched. In my WoW Account, there are (2) accounts joined from years ago, and on one account, the WAs are working, and on the other, they're not even being shown from typing `/wa` in the console. Of course the one account where the WAs are missing, I had several WAs on, and even with WA Companion, it does not seem to help with this instance.

**Comment by mrbuds** [comment]
> there are (2) accounts joined from years ago

I don't know what accounts joined means exactly but whatever you did to make them share same data is not working anymore and you need to fix it.

**Comment by InfusOnWoW** [comment]
There are instructions on how to enable lua errors in the bug report template. please follow those.

Also quite obvious we can't reproduce your reproduction steps without your settings.

**Comment by hoviwan** [comment]
@mrbuds  - It's (2) different accounts, but the same email address. So, you have the option to choose a different account via dropdown when you're at the login page.

@InfusOnWoW - is that just to edit my original request, or some other directory?

**Comment by InfusOnWoW** [comment]
attach it to the ticket.

**Comment by hoviwan** [comment]
I just manually added each WA to it; if this happens again, I'll be sure to attach a lua error if it quickly displays one.
