### ISSUE TITLE
Update auras that are not originally a child of a group

### ISSUE THREAD

**Issue by Boneshockx** [WeakAuras/WeakAuras2#3525]
### Description

An error appears when updating auras that weren't originally part of a group. E.g. the user imported it and put it in a group himself to organise things.   
The 'updated' aura will not work until a /reload.  
Other auras can not be updated until a /reload because it thinks another import is still in progress.

### WeakAuras Version

WeakAuras 3.7.12

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```lua
3x ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:981: Display "WA RM+ Required M+ percent" thinks it is a member of group "@Dungeons - Custom" which does not control it
[string "=[C]"]: ?
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:981: in function `Initialize'
[string "@WeakAurasOptions\WeakAurasOptions-3.7.12.lua"]:585: in function <WeakAurasOptions\WeakAurasOptions.lua:579>
[string "@WeakAurasOptions\WeakAurasOptions.lua"]:858: in function `NewDisplayButton'
[string "@WeakAuras\Transmission.lua"]:472: in function <WeakAuras\Transmission.lua:416>
```

### Reproduction Steps

1. Import an (older version of a ) aura from wago.io (make sure it's a single aura and doesn't contain a group)
2. Move the imported aura to a group
3. Grab newer version and update the aura
4. Error appears
5. Aura is not clickable or movable in the options menu
6. Additional aura imports cannot be done

### Last Good Version

I remember this is broken since updating auras is a thing

### Screenshots

"WA RM+ Required M+ percentage" was updated here. I had put it in the "@Dungeons - Custom" group. 
The aura appears transparent in the options menu after updating, it's also no longer listed inside the group.
![image](https://user-images.githubusercontent.com/6916881/156890186-1257a0d0-9b3e-4410-a734-879631d86508.png)

**Comment by InfusOnWoW** [comment]
This is indeed fixed in nested. Given that the bug apparently has existed since forever, but no one ever reported it, I won't invest any time to fix it before the merge of nested.
