### ISSUE TITLE
Basic search function for Models (.m2) based on file name.

### ISSUE THREAD

**Issue by lindenkron** [WeakAuras/WeakAuras2#353]
It would be super useful to have a basic search function under models for searching things such as "priest" or "holy" to avoid having to go through the giant list.

Could be very basic just based off the file name.
The website suggested doesn't show the actual animation, like WA does in-game.

**Comment by emptyrivers** [comment]
https://wow.tools/ exists, and has more features than we would ever implement for WeakAuras. I think that's enough to close this ticket.
