### ISSUE TITLE
Spell name Hand of Reckoning not being recognized; Spell ID 62124 works

### ISSUE THREAD

**Issue by raysmith59** [WeakAuras/WeakAuras2#3531]
### Description

I'm creating a trigger:
Type: Spell / Action Usable
Spell: Hand of Reckoning

Works with 62124 but not with the actual spell name, spelled correctly.

### WeakAuras Version

3.7.13

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

See description.

### Last Good Version

Unknown

**Comment by mrbuds** [comment]
Could you include in the ticket an export of the aura you made?

**Comment by raysmith59** [comment]
I think I figured out the problem, I was making the aura for someone else and wasn't on a Paladin, if using the spell name requires having the spell name in the current character's spell book then this isn't a bug; I'm not sure why it would be required, though.

For completeness, though, here's the basic aura that exhibits the behaviour, when I type in Hand of Reckoning in the spell name section it doesn't stick.

!WA:2!DrvWUTTrq0iOe0cAGIy1uJAGEW1aTO1hmAJrtl6nrvPehOiPssx7c0wPLKJi3yQDz3DPKLVfDkN1NGo3t6tWFbeef5dWh6hG)c6SlPuJRoqnZSZoV5n7B3ADAmPryJW3E4kAaN5YZebWN9GcsMkMl6NQOCM0smV)4XsqvBnHfGXhWPmLFR298A7ueW5jH8zm3z0uy0nBCBhgbX26IoAHsqJIaH8J(srL5)yRMNcoYuij5wzMpmfyk3SXJPxTEyRMUEdD9A64Tke8XGEyUIx0U7GoN1nD3mjmmcyGGg4gZN1NnYXS909BvH9bde8ibiLh8vUAe(6TqmqaieoUdA3TBHaijM17rMa1k01vUXD0cJ5PHsRI7b2TsZFBGYoJrv(PjK5GWHHBuATuxiLGeC5OLBRxTLzSkUBLUljqrNcEL(VIhc)1dUdhPGGrs(fCqHtD4UlbiTjwGaLdbphIxkHKXMrF(JWbJKOYeefeVcjNdePpP(X9Y3PaD9rWJe8mw4BFsAdfCLAOmMG97fvhKP7BcA(mMlMqWeQmSzi4l3U8HFHm9XVxfAXt4IxwRwT63wgDttz38mV(PFSjikF4yPObNtdvX2nr37kXIEfeAc(MIsT0Vw1r3yw)1zsfD8CKGcUcjNhg0Ux)ETZ3rG8sNZktIbM2Oo(BzfjqbWJ7iOxFWpNrcXbd5apV7X9nivyInJlcpxqsxCELrzdmLkP(jWOko)E690DpTxV2odT7751)voN(8x4vSfAx61W(vm6I7HJEvJ(T)zEDpTx73veLWN1ra)zgWcMp4HFZXp97kzNEH16pBQWcTJEZf(zkfN1FkiqL2kD4Ualsf)jM83WSLANwBNm3GcXNVjsSTEXyd6EX0Glz49J6MD4gqsGsZUum8UgaSX5ciI9JbAuS6n2jCsyhFfMktTNZKSef1Ywlp3l)mlNGeIuQTSL4OqBSsy0K62p)dDijPXK6ljmQwxWzpZrQicvNBaIeCvcdB(G8DYpQiulRXugQFIqib8jKq5cDEMADK9ecL1j)3nzN)h5dZhLFK)ykJkJ))HxtzLQASEw2xZ5tQj0x(W7kpl)3SY9TSX9PSwP4btlV49P1gDXH0qFpcEJ9ZD(pH26Xc8Im2RO2Q(DLN1D0H0TLVBlN2T75mZOT9XEEmnYsqz6QcXpnJgU2jD2L)Wjo9F9l7M(KnVtQv4)evsqrxy8knxPLp6UytgXIRQoFBi9p54V)4V9Kgt)7l(3)

**Comment by InfusOnWoW** [comment]
Indeed the conversion only works on the correct class/talent whatever setup.
