### ISSUE TITLE
Adding an option to put ticks into a timer showing GCD would be amazing

### ISSUE THREAD

**Issue by DeftMonk** [WeakAuras/WeakAuras2#3534]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DeftMonk** [comment]
theres a lot of mechanics in retail that could be done way more efficiently
if cast bars/swing timers could be separated by GCD ticks. Like kyrian
monks knowing when to cancel fist of fury or any proc based class knowing
when they can fit in a global to be off gcd as swing timer completes. If
theres a way to do that I would love toknow.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by InfusOnWoW** [comment]
Yes, but that doesn't make your suggestion something that fits into how WeakAuras works. A feature that works only for gcds is not something that fits.

**Comment by DeftMonk** [comment]
oh ok I just asked if it was possible in the discord and a mod said no but
it would be useful and told me to put in a ticket for a suggestion. Thanks
anyway.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
