### ISSUE TITLE
Bigs Wigs Timer Trigger not reacting to paused timers

### ISSUE THREAD

**Issue by Dradux-dev** [WeakAuras/WeakAuras2#3537]
### Description

https://www.twitch.tv/videos/1423181195?t=3h35m29s

In the middle of the screen pops a "Dispels soon" text. This is another addon, which triggers on "Prisms" bar <= 3 remaining seconds. Unfortunately this addon, does not properly handle the fact that the Prisms timer is paused during the Reclaim phase (see how the timer is stuck on 17s).  On the top left of the screen is another Text with "Dispels soon" with a lot of transparency, which was a quick test with WA (same trigger Prisms bar remaining <= 3) to replace the other addon with it. As so can see the text is popping the same moment as the other one, when the Prisms bar is still on 17s paused. 

### WeakAuras Version

3.7.11

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create a big wigs timer trigger with any amount of seconds remaining.
2. Run a big wigs test module, in which you pause the timer before the WA would be triggered.

### Last Good Version

Don't know

**Comment by mrbuds** [comment]
Test aura used for testing paused auras slightly modified for this case https://wago.io/2E0gaNtUi
