### ISSUE TITLE
DBM Stage trigger doesn't trigger on "Stage 1"

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#3543]
### Description

While doing some Weakaura work on Prototype Pantheon i relised that the DBM stage Trigger never triggers in stage 1 of the fight. This is prob the case since the DBM-Callback only sets stages 2 and onward. It will never set Stage 1 on Encounter start. Looking at the trigger Code it looke like Weakauras assumes that Stage 1 is set.

### WeakAuras Version

3.7.13

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

-

### Reproduction Steps

1. Setup the Stage trigger and either select no Stage at all or Stage 1
2. Pull a boss
3. See it never fires

### Last Good Version

probably never

**Comment by mrbuds** [comment]
Confirmed with DBM guys that SetStage event trigger on pull for boss with stages, so no need to change current behavior.
Prototype Pantheon DBM module has a few TODO and i don't see it setting stage over 1, not the best module to test this trigger with.
