### ISSUE TITLE
CDR (cooldown reduction) isn't handled by WA

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#3544]
### Description

While the `modRate` value on `GetSpellCooldown` and `etSpellCharges` has been around for a while there really haven't been many notable examples of it being used until the recently added Encrypted Affix in M+

While buffed player CDs run faster. Currently WA continues to just use `start` and `duration` values which make the displayed CD jump dramatically rather than just smoothly run faster. The default Blizz UI sends `modRate` into `SetCooldown` on the CD widget but presumably it just makes the widget run faster

### WeakAuras Version

3.7.13

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

n/a

### Reproduction Steps

1. Have a M+10 level character
2. Run a M+ of +10 or higher
3. have the group kill the [Urh Relic](https://ptr.wowhead.com/npc=185685/urh-relic) first, then the [Urh Dismantler](https://ptr.wowhead.com/npc=184911/urh-dismantler) that spawns
4. The group will get the [Decrypted Urh Cypher](https://ptr.wowhead.com/spell=368239/decrypted-urh-cypher) buff
5. See the difference between the way WA displays the CD and the way the default UI displays it

### Last Good Version

n/a

**Comment by mrbuds** [comment]
Clip showing difference between an action button (bottom) and weakauras (top) while avenging wrath is active https://clips.twitch.tv/LazyCalmPorcupineHeyGirl-l7Aeco1kiUzhA_y5

**Comment by yongri0** [comment]
the same error
i think [modRate] is miss
the correct result should be [startTimeCooldown + durationCooldown - GetTime()]**/modRate**

@API_GetSpellCooldown
