### ISSUE TITLE
All WeakAuras deleted. Can't make new ones either. 

### ISSUE THREAD

**Issue by Chaalk** [WeakAuras/WeakAuras2#355]
What steps will reproduce the problem?
I don't know how to reproduce the problem. 
What is the expected output? What do you see instead?
I expected to see log in to see all my WeakAuras, but they are all gone. And I cannot create new WeakAuras to replace them. 
Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes I tried that. 
What version of WeakAuras are you using?
Today's update 2/11/18 is what I'm using. 
Was it working in a previous version? If yes, which was the last good one?
Yes it was working in a previous version. Version 2.5.6 was working. The new alpha build is what broke it. 

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
Yes I have an error log. https://pastebin.com/aLhE00dK

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by InfusOnWoW** [comment]
That error message can only mean two things:
- Your installation of WeakAuras is broken
- Or you updated WeakAuras while in the game and World of Warcraft isn't loading Prototype.lua

**Comment by Stanzilla** [comment]
@Chaalk hey there, turns out there actually was an issue in WA, it is fixed now, thank you :)
