### ISSUE TITLE
HP delay/wrong value

### ISSUE THREAD

**Issue by Rimshot99** [WeakAuras/WeakAuras2#3550]
### Description

Today, after the ZA patch, some buggy thing start happening to the HP bar made with WA. Been asking on WA discord and seems that im not the only one with this issue. It just have a delay of 1 "tick" of hp natural regen. also sometimes the max hp is wrong aswel and sometimes it get stuck on some random value after leaving combat.

### WeakAuras Version

WeakAuras 3.7.14

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create WA hp bar.
2. Check.

### Screenshots

![hp bug](https://user-images.githubusercontent.com/35757655/159639542-3d44dc84-3093-4f9a-94f6-ac3dff590070.PNG)

### Export String

!WA:2!1vvWUTTrq0OkG0wv0IyLANeGGcxJ2IgGALyN20tfbIYsvkWrsHIo2jiasl5UKCBO2LD3LYs(w1jFwN6zDoN0NG)cie6xGp1Z(lOZUKYooOHhO2zMDgoZBM3OcnkpSmUm(0hoxgJeV9qkwfU(CQhN1JNi8i3)gIXD89LevbXKSdV7lwGyEHCrxoLPCRvVTtD7Lg3T5kKIYzfIx7AYpNJjwvpWPZfUiV3gi4jmCnEex8Scfk0T4JQ8ltvcAqari)QFqKF80BpLQidBJgsG4Lij9dimIG61lKFCh2GLxt8CP5NACEeMFmZkHrvUXrOjeXCmXnX33zsmr0S((DBCW(wkqiDT56OgsqrQWWZLjUKreMQhCx64f9RvTNt)EovTDU0uxbbmz3RB993)mTVRsWb2m4TSu8xR1QtLwmp(qklOje9WP4eHbikVZuzmjkQfwwAQ(Q60CGiHzcVfkrXZkviv9an55MTXSBtJ0sTDFKNoET2BWSewoGvkEnT2reNmznQ)UByAM99mODr45cOPremu0lb0gcrWmeJo0KDpXwQqcvJZiijPNsqybQWpnDDlgNrwUQg6RXoHKaHflNQVQgztRynerzns3gCiTs6dtFu6oPvC9PmQm8dvp1fjYgaA(0)(U6N708P)7yZtHIqdtIu6phj8mZGu2K3Rkmh6e2KailKpBJ01xcIxnrLRWNlizko9oXFJImw138c0dLz)4(k6qsUuHzxAFRVpo(wgjzicgHUC(S45zAjr(Mj(0pp(2gn6ULg48mSgRQG4fzFj6yc2O8VwMrvEvoh6mJ9)irQO(tsV5CHMGqCaLwT70UE66cOa03zU5Ix11MLxcmv8TAiONS5lsqyaGqB64S8sB6gHvBOzfx(9QK8p(9VrEYCuEYK53XCb(qbkE6H5hYYXruj1nImihtEpg)zTA3UUD)mEF89(Fa4Sd2ACgh)TFSoqSG4r1tGfVQa6rpHCV4h8XCbpbOzuV(Qqbbizr4jxRqZlSIJw4c1cr0xcHBTL5czLWUWK3kn88MsU4vO955AwbcRIhbhqUWkIEYjibEZ9OOiEq66Z0tHMl4gsObHQFZkIJW(Z0evnZwe6QqradEd7HjrkAjlDITrkPKTxesk1NSG9cE6dItG(hSF4to3m5Bb(H1m5DRU3EX3cczvSE(HGj4NJghMT3U2LPUiBXG8jP)uP0hxYcOFQsFOFuw4CHHgzwkIaQgalZUAe)MlHHBaT6eBcwPzMLiskMyB363B68(SYJk4cg9PbLwy02mdde6gtIGmDfELBLIXeMD76VSUDwuCYUx8p2sVycwSrEtneqqybwiXBoO12xjTDpZ)QyCBWCf3Bu2oSpR7D3II3QzxBuuCiQ4cFbSog2GbeKIxK14BOvPlx3E1SRxVT9XAc639L7MqXlgVN4f()zJxNmSPGY0rLeADcNpSWcUGcDoZMV5n7y361DA7uD)56TF0mWzbLLnMcsaGdwcllDFCLFTYo)C5r)Zr)3d

**Comment by nezmo1** [comment]
I can confirm this issue.
It happens to target and player HP bar too. It seems, as OP wrote, tick is out of sync with information (graphic and text) on HP bar.

**Comment by mrbuds** [comment]
For reference https://github.com/Stanzilla/WoWUIBugs/issues/228
