### ISSUE TITLE
TBC Player Info Health updates slow/never

### ISSUE THREAD

**Issue by vison2** [WeakAuras/WeakAuras2#3552]
### Description

Since the Zul'Aman Patch there seems to be a Problem with the trigger update for Player Health.

After taking a hit, like from falldamage it takes about 3 or more Seconds for my "Health-Globe" aura to recognize.
I´ve tried several diffrent auras, but they all seem to have the same problem. This was never an Issue before.

Also heals are recognized slow, and sometimes never.

An UI reload / opening closing weak auras / entering combat -> Immediately updates the Globes, and show the right ammount of health

I use similar globes for Mana/Energy/Rage, they work absolutely fine

### WeakAuras Version

3.7.14

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

I can't see any LUA-Errors

### Reproduction Steps

1. Use my Aura
2. Take Fall Damage
3. Heal

### Last Good Version

Always worked fine for about 1/1/2 Years now

### Screenshots

![globe](https://user-images.githubusercontent.com/12114693/159804196-3c6e4d14-fd93-4a45-a961-f8497288e318.png)

### Export String

!WA:2!fw1ZVTXnwyRQInB1Hf2Yoo)ePkgigjlqKLYpSttcASgz5iNilRmsoolGtL5mdNzyYOHSKZyBLtncflYXfc9VaDUN0LcShZHEMqO3lq(pO(sVuG2h5Oyz3EOJa0q(4JKFVV337nPwpBNSozDE3kwXcmVD3ujVpSr6c5Vl)WTCDf4Ox8pkEV7K)UlpWower70cFyeBx34q7icn863ito4HJJI5H56GI8Z7gqP8RVDijQkgfe5F9fybOUy(c3i3s5MyEt0HNyL)DUIfkCJhKbh6KH3n5IRU6E)8V)ntn1NDKlLJ9404qNY0ak)jPR(O))fHNl8RvF0pCo1ZLsZMZblqamqrydK9Rt83Nn9eyVnZbw0kw)6wX8a2L8JIyI7V0shG8O5j0L6Il8fUSDCF2s3JJ0rOyztreIhLXGaypJLl8s4NPxeN45H5IVAr(4H)Oruxg2igCJhhI3hhgzGIJO9CuGcoQSfn1wTsyGpiIT0ZBWXUKdnB2OsTAY5SsiLEcgoiydhrMJ9RzSl43W2Ll1Sv7MTkz2QhKVARUW9yZOgYWCBWrF957BgI6Gfzg4aXSRBlaC8QvQ1y9TR1poCmOZSOm7)vEw58YzLZb)US8kYpxEr5LKNlBr55zZPYy5k7Ju0bMtereBHm3EYRLzOdr8kToyF8TqHDzZG0JBLCYBsDWF)u9GmAPqVa83o)rKq4ecrbphOnGo86JcjD0mZYY)16YzncPH43JrcCZioo0lY)mJ(i31wXTCb2Mg6i6P8rfpYBA0brcH9kVPm)zKljlilcdN(pB5iRJLejsOuPsL2YMtzT724tlK)of7XPr6BkLHlnmIn96CYBY9SyKdaauUwT47Na7zga5dtSNsBCFG2gbtNC6V7SSSrGwRTWh5qp4fjs50912u)XVws2Hn9jCBcM(qIvCGBdkWxwLRuVvft2SAZk1KIWS3H4e5BucMEKEbqwGD0gF7iuOTpL)FsU4uVxV(RGAaIBx5Qd0rjwvnyuFR6vKZYb4R8zmSt29yy)BPgOnANu1bpjXHIGKRCQaD89D5PgPnEaL7SdhX6TZ4bJoEJQ8MrDitpMbsUrD0AAUXJR2IDLJjlydCiGBNqzJNjV5KdRj5n4Ro6uGECiVprqScW79UZkFqA5dx4A2YVuZWYhjxvwsAil)w5APKvGzRlFmOxQk3Owk5t0XP8PYvK1U8uYnL1LBjBiFM08um044f2qRRk3oL85(w(yINF0VKOQomrvzeqroU9v1M2biHypRiuauHoVzN4Gisg(BaIakY)edOC3EE5lZyQ9Brlbrv1y1SAPnlvx(Y55nkvR0ABuFpdbeZkppzhV1pUdjiSGBRKJkLJDWoqFwFTijMJvjcvzPz5AL2Sr)JvzYvzZmPhBReNzRSHQE1fzJ3TKJZwHID3bJEDj4(e7Uj2HG2DSNIDlt42b42n7qPr(dprgvUQfuX6s8Yy1HW5u(FbEKq)bCD1KsyCeJt9GtumgXd09E1nqs1hsNHoA8BuRs91mpqj4)ftuaZhLUViafgPw1AJ6n3yTk9(O(4cSzMuF(XGB5tfC0tfCnOhG56HjHzIv1)3UNnTdtHp)rqXieLBX0FKiJLa3bAqywmFH8RmiIApUBX)SX5xG403K6fJR2i3YM6APmdD5qVzOnh0Bj9rje26ktksWQzzZkvQFRyIZWdwBRL9cA8KNENVMtcvhk2FOq5ysGS3qkNackDRREpVIzRnkxQ2avBsIgzxCrtBFS9RxxMnDV9rCccOXrN6dflqzzFO5(OGy8c3Ta32hf6HHnk)FlpqOinDZxJgW3Lm1Zzp8VvA0u5Nyxd6HGoUe0nhPTKN65nk5mvxtioWAnckG61ds8aOI6k)UHKWKcDa(ZZopXleKMJ55kQVdwrjKe7XMEsADCPFwH1TZVs(I3j7()0l(Jd

**Comment by InfusOnWoW** [comment]
Already fixed.

**Comment by vison2** [comment]
Thats really nice to hear. So I take it that there is a new version out there? WeakAuras?
I just updated mine from cursed, before I posted this, but maybe that is not a good source?

**Comment by InfusOnWoW** [comment]
it's not yet released.

**Comment by vison2** [comment]
Ah I see, thank you.

/close
