### ISSUE TITLE
Icons not updating on either first or last iteration

### ISSUE THREAD

**Issue by mlbernardoni** [WeakAuras/WeakAuras2#3553]
### Description

I noticed this starting yesterday with the latest release.  Icons (for example a health progress bar) will not update correctly.  The icon will work during an encounter, however if you cast a heal after the encounter, and the character is healed to 100% the progress bar will not update.  Interestingly if the heal is less than 100%, with the next increase of health it will update.

I have noticed another issues that I believe is related.  On my Druid, if I power shift from cat to human to cat, all the icons will stay with the human form.  Again, this worked before yesterday.

### WeakAuras Version

3.7.14-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Create a progress bar that displays health (you can do this from a template)
Get in a fight
After the fight cast a self heal (the self heal has to go to 100%)

The progress bar will not update to 100%

As shown in the screen shot, the character is at 100% (upper left) but the progress bar did not update (red crescent below and right of character).  FYI I tested this with all other add ons turned off with a new progress bar from the template.  Same behavior.

### Last Good Version

It was working up until version 3.7.14-bcc

### Screenshots

![image](https://user-images.githubusercontent.com/23664650/159807639-f2b69096-d765-49b5-96ed-98590a3acc48.png)

**Comment by InfusOnWoW** [comment]
That's already fixed.
