### ISSUE TITLE
Don't show all WeakAuras when opening /wa

### ISSUE THREAD

**Issue by allmeta** [WeakAuras/WeakAuras2#3555]
**Is your feature request related to a problem? Please describe.**
If you have a good amount of weak auras and you open the main window, it can take up to 3 seconds for it to open.
By default it shows all loaded (?) weak auras and its ancors.

**Describe the solution you'd like**
Only show the WAs when the user clicks on them? Will save a lot of time

**Describe alternatives you've considered**
idk

**Additional context**
idk

**Comment by InfusOnWoW** [comment]
Not possible.
