### ISSUE TITLE
Broken UNIT_ATTACK_SPEED workaround.

### ISSUE THREAD

**Issue by mullerdavid** [WeakAuras/WeakAuras2#3556]
### Description

In TBC ZulAman patch, Blizzard broke UNIT_ATTACK_SPEED event, it's not firing anymore. Made an attempt to patch it: https://github.com/mullerdavid/wow_BlizzardFix

### WeakAuras Version

WeakAuras 3.7.13

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Swing timer is misbehaving, as UNIT_ATTACK_SPEED  is not firing.

**Comment by mrbuds** [comment]
For reference https://github.com/Stanzilla/WoWUIBugs/issues/231
