### ISSUE TITLE
Energy Bar dissapears while shapeshifting (Druid)

### ISSUE THREAD

**Issue by Minae83** [WeakAuras/WeakAuras2#3558]
### Description

Hey, since the ZA Patch, my Energy Bar dissapears while i shapeshift (I'm playing a Feral Druid). I testet it with Weak Auras only and it happens everytime, when i'm infight and shapeshifting from catform into catform.  But everytime when the Energy is changing, after a while it shows up again.

### WeakAuras Version

3.7.16

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Go in Catform
2. Come infight
3. shapeshift from catform into catform with my makro ( /cast !Catform )

### Last Good Version

3.7.14

### Screenshots

https://imgur.com/a/dIOFYZO

First Picture shows how it normal works. The second after shapeshift. I just see my combopoints (paws) and my energytick bar.

### Export String

!WA:2!nNvB0Xrv5)USuQS1JMeAdHcTmnqRjqAAYM20xG00Dt2KDlPB2o7MK2sB3D2DU7ot7SZmDMz3KuefIynIuFjhruu8Li6Ffrfxr8akynkVO(LNtk(Y5W5ONtu5lO))q8t8j85EVZ(wAlGGhpC)Wo35EFUV97(8C)97oRNXBYoDpDURo7U3MY3KCtYZUXftlL5uYwgMdyOzyDaVE9gZBxDUZLsByjtSc6wPzdb1upZzKSKfsyyO5OAoVJrMIelBvd93xSwSMA0SzTjoHpV5fIU)vTkpP5TxzE(ZqY5iMng)0fKSicdvqttycfvhsjj9mkgwXmu1DspqOOjcj62G4QNHS6s888zMhpE8kANrsJ4DrPcoyZg10bhDBFwszyz6v02rYYXx6SQ6Q2k(cIpC8nJJLAUC4mDdB1Yn7zNxMKUq2SjM2Kyfo0iXgASrc6GVikvWsY)m2MenTiY2(wYUqAsrIUtC0A1PkLCGaXtKmEIaIjcwa780MAsttSQywmlcAMy8yHgzerwjPdtK0Cue1LYtS9nxbD3PGpRPlJy6p8jxfMwGVy5LE1ZBrYHRj6mumNLrbZ5SjAzzafS2wvLnBAqXXImyiHTjeZysILqqjRsQ6znSYlrbdFLYAHdzChljhjVlZX5HOfr7Y0XhqmuOOlJ9gXsxsBC(gzU0zm0ZQMZ3Cs6Q8(PxOXHwGizt7jIEohL1aTeu3qNSOmcvulssbolBc2uz7zOMshbONG5Lu1hc8Jna6b2bStOx8ztRSK5rStKTwT95VGQCj9Pkmz0i(LDo04Zt7tv(MCqndj5Hs7G7)6onlMVa6e6liUtLPzyF(eZOjzBtZf0g9COzCDEIOJWP3MYC)ZkaFqFWwcF(3)Jbu8g8bRfAaxF(GRXh0KpyDFGTcR)vX52gfnPqAtDVe7zsdC9j5yy16(6BUc2KKSstbBwKH8WgHnbxpCdZXkMcgxnSbFWn5BgQTuVKuWncclwPLutsbndxlCZ(mBK67wKKG7vCqdzYJVky75G2H1IoP2souuMOy2OSQDglIdjPLHdd39a7EdndTSiIF0qyQtIUCAfIAofNZLMzfom3Ew2uMbpPyz1r)slfOpkgb7FRPTv1ZPrezUt0I6Nvra6Vl7qMcNaKjSKmPtnZ1nWiboySeJgCKadChbgCWijImEO05vTSmWU8dz5A)CPXnjzAledosOOdctyURiuxTSszihlGSmUHESjisNkaU6Spgdgzzpirwv6y8sP)6FpW2GofZWoaiC))9XyjpH7)1UnwYlSA8WhmCqCGGJk0nCvH3pz4nY2D7WR4KQYokNd6Y3mvWmrjntfjVWEkngz3sNkyXDfoYbHBZhCR(GUP(6mxt0dTS)6UUOsAALLGow44Q55SSXDlh(k7PZDU73eVlyGM8ddIotqi0jcgQSdemSRJdeM5Xark7LahG7u8oDgc3HcmIR)cCqi65GrPEgqSuWHQ6jaIq8v4aajGXGXXDwyc4WWrWFpkDdPou3pnSQdVWXphCNhWlU3S0Y00)IcYt1UrH49oupTNUD4eEGKEXndx0gDWDJiF7ay98odWWb5)6RD(IC2wOPRTEhWEOocN(4pfLa0fsW1lFHVNsD1Lsr)KOJTRXDE37X92f42X7LaomU9UyPW9)Npbl5PEaChua05zET7HhbVcamqIr2r4J2va1J4))Da4oFpLNx4()Npln9CRa42jf4MA3)1lnWL9qt5)OTDeNyrpZ7wGRR5TnLSo1e0Jwx)8QibDCJcwzi3WQOuRd9WAVKl16Im7elFWRzJ19oLBiyGXqMeAxOaRBtiK)umiNcVuOMcRd7LcZuqhXzeTRaZO1fz8RubpPywqBB4ubPf0mi6f2SzdXDqDpKTpew02P0j1ShXM6jZuwZRx39Szsl5k30lk3e3bxGnT5IYocUzEu2MPlVloweoV7SBWSjk5xsBfjzJjpmVbEMJvg9Nz2s3DYy)nVLkLLKRwlPBnjLjzqvxAjnTWm2mu76UiJnDZi6OMNiVeFqRinmV51WkbfiBqfWLHTrfma(Q5nDzhy2sGPJtmRMHH1IC5IhXDvSaRnNSGTJA2PrDjCTfjWcdgD0OHm38LyssNDvxiEHwSq8IAIBFxgHMN1SQ7dZ52n6olgSGQqmCSmOtmZgQbEREHG6q96NVfXrg1HKAr2BtIIbPYyMzc3mlwzGy3cy0XsmseCTWhMAUwYcrIgnKys(Ltm30LBPYFZJ5nEzbz(RPJwiFAIv1rNErNTz2(LRFLNgV5GAMKokweBfdn5PxMBL6uez2M79weAzoQiqMC3f5pCxb(r3zxDWjP6IxT7LmCbCkc6ErVkWvzZj4n2S6wigooAL7udo(oBdlJEwNkjtLxY8yOSFul4ISYQO0Ab2RUxl0dVb1kOTHkUOj1yxSi1smBCuWF1j22R21NbFTens3vBPY8mZQzbWEhViwgsE8QbT2Dx8HE6kEdSUL3AZ2QQdDaj0HwphEXPJnwKTv9TTfNgYZBwfuH9gFI2h)fxvVyaxDJpdpSc4mUKwbcen8(33T)6)L34nEJ3wN8Ve70MGLvpdpQzd4spGmn2JitKpO0uk4r((NOGJ7r4R46v76T(cxUuDnrz7wYoVHHJcgLLdDVStTYHtvNQQNEPy0rIszs13eADuHUZXoa1wf14lgz4WjqAM0te3mM0oMySchGFSzcoOdprj2RHz3nPpyIfeLW7glmSMHT90irvWZyyK3JiZifgVMBduLLj6IrdnEir444q)Kx48UsRO8Hj9YjJQ8Ll8APQt)MeK6o2(WEkzyPIBnmhZ5dpQyKJoA0ebgHZfUC1Bpv9CLz7cuxpCsKvJFNXAi2Gt5b0G8WVJz4LL5AnVjmxGHsnuwGj6kSgyFnVgQgJtxRqI64MaBg))gzPW9)8pin9quskWbzMozzMjOWSxpu0dmjmfmTh4tXNNpi8fG7g(iWx6EH71dmd2DFm4(GpUx4t4bBYzDpiTUdNxpmlF8)KW9dNbUl4b8aFw4ZbFA4ZaNlfm388Jghj0qjGpVh4dJGYdTn4lon8rH7PimVh4ldFfSVFy4RYNcFTuWxh(gWJS6zxhu0lmP)U7Ql(0J34lE6HtSANdpaUFqhC6KyUs8rN58Dj4j1DZGo84KcxKNl1SnaFt4rHVLh4B7b()uGVtk47INYapg89uGhNph)(TUd)WpWd8dHNa(rPGs9b)yf4jHFY)PrYWtHJ0pvHQ)cJHQjKdE6uWZq129ZENhbxnke(5WZIrE9KRx94dCGXDIibl4bopgJb)s4f4i3Vaxk)kEyf8RHNNf6qLiwjEcprXkKoXkNkHQA8fvGxYd8BGFlCB3YwfZOqYCQEH1FdRAMIswQs4PHZOQNXiFAudsr6HCESYOiPNJyJ(2xGzj8YZPir)wC5ioWFWl8hPXzZUxq9gP9m1v(QgSryl)dVS4jVWv6gt5VGLM51R44yAV3TV9jLYz0PQX2ZrkiAF6EnpW29xwM(wtNbpIYi)vmNSrsEwfMY9tGHxVaIvVIBWyRSGXBYh)ZZzBULXIgjrYyJob65mKyOdngsRVx(hXtie6on8rsezG7OCO7fGnxI37mXrLSP6EkykJ)cVYuE7pBbD2xESnPoeiDi40UpbmPzKrstitbloOoTqFcJPR6W(khT1kFWATdHEQ1A5cwOz(zLOMvOnIqF9j06LyY2QGKUCTD((eAJE(CsIEXo1qq3TydlHUANpcyw3(R6kK3noRSZ6RMPkY1u3SL3zokeDwg3zQUb2j3zRTE8vufnXlVpH7QUsPjujZKyfowfiDCrvY9MKVS1x(dpIgGzV46jtzQYTibQGcTAyIdnxBTlCRx6wy6Y)rvcI23ktADR1z2Dx5nIMnPUQ47G2ydzl46QZUZ6xnROY6xkROY3Q1XkmVgmTUAgijTrwDgilk8Pn)DiuXRTDHkFdUoJNrspelgPTADt6G1FTlGcsAVkcOl7R2Nxk)V(QXTIzKfbLcOZNE0gIPQmINLLTf46wG2xSp)UQS9g8VRE39YOIKqtjLXjo)JYNIfztJolhDFZ(kjRAFs2QQiXVKM2k4oREzx6bO4zP1Cz3AkPPvwYYL)RrIOpKfkvxHkgW(aH7)vBMLc3)FBDSu4(FUnrtB07s2u1GtpO7(Qs5ZGPe07TkbDrgTiLE8rASw2rZg5kJg0OaEol7VibMF1uUNMFLtCE659UQoU9ZcXuq1oS)AaKVP5GwsQY1qkrjH2AANjXD0Ptndsf6mDEj9umYkrXrhESqy9q8uW)FkoTL1zm0jrKTVcgZ1vu5pcIYiGkmyKgR1Y9F8z1WtR4YITy5pZodIsHCjls4UauKqWpLHkTnjp2sXU7SRo9hKk8pfCEcmHfEfVH0qoAkffYBvdl1YmbCdw9cduM0JFFns5u3tjPy7P7UoYO90LHm8IPy60y8v7Tkde87zmpByR4JzWaCt6hEhswVbE4g4bE96Q5pvTP0AGBTzZwuZPJ3239VCIfPeIQ)3ofYV3uXx(W)7)

**Comment by mrbuds** [comment]
For reference https://github.com/Stanzilla/WoWUIBugs/issues/230

**Comment by Minae83** [comment]
Sry i don't understand. Is this a solution for my problem? If yes, how i can fix that?

**Comment by mrbuds** [comment]
You can try make a bug report to blizzard in game, but solution is to wait for them to fix it on their side.

**Comment by Minae83** [comment]
Ah ok :) thank you <3

**Comment by mrbuds** [comment]
fixed in 2.5.4.42940
