### ISSUE TITLE
Request to add more unitframes to libGetFrame

### ISSUE THREAD

**Issue by Woosuk1624** [WeakAuras/WeakAuras2#3559]
**Is your feature request related to a problem? Please describe.**

Missing unit/raidframes in libGetFrame makes incorrect behavior of external glowing, pointing frametype to ‘unitframe’.

I have used ‘InvenRaidFrame3’ (former raidframe of Lime), and found it was missing in this library. Sometimes external glowing works into this frame but sometimes not.

**Describe the solution you'd like**

It looks working with     "^InvenRaidFrames3Group", --IRF3 in LibGetFrame-1.0.lua.

**Describe alternatives you've considered**

**Additional context**

**Comment by Woosuk1624** [comment]
[InvenRaidFrame3.zip](https://github.com/WeakAuras/WeakAuras2/files/8355499/InvenRaidFrame3.zip)
Inven Raid Fram3 : origin of Lime Raid Frame which is already registered in LibGetFrame

[InvenUnitFrame.zip](https://github.com/WeakAuras/WeakAuras2/files/8355500/InvenUnitFrame.zip)
UnitFrame version of above RaidFrame.

As there are many branch(eg:Lime ) version of this Raid & Unit frame, please review to add in the Lib.

**Comment by mrbuds** [comment]
This is wrong place to submit feature request for LibGetFrame, please do it at https://github.com/mrbuds/LibGetFrame/issues
