### ISSUE TITLE
LibGetFrame missing comma

### ISSUE THREAD

**Issue by qwerttyyyuii** [WeakAuras/WeakAuras2#3560]
### Description

LibGetFrame-1.0.lua Line 244 comma missing error

### WeakAuras Version

3.7.16-15-g8583018

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

always

### Screenshots

![2123](https://user-images.githubusercontent.com/42610598/160262770-531a5dc5-05f5-4aee-a525-dd356e695593.png)

**Comment by Stanzilla** [comment]
That's an issue in LibGetFrame, not WA. https://github.com/mrbuds/LibGetFrame/pull/25
