### ISSUE TITLE
Format for %c1, %c2, %cN appears under Format Options but does not actually work

### ISSUE THREAD

**Issue by Hekili** [WeakAuras/WeakAuras2#3561]
### Description

When using Custom Code, the `%c` replacement is suppressed under Format Options as it does not actually get formatted according to any of the rules you can select.  Since the same rules apply to numbered Custom Code return values, you would expect them to not appear under Format Options as well.

However, if you specify which numbered return value (`%c1`), Format Options offers to `Format for %c1` but does not actually work.  This is misleading and can confuse users.

### WeakAuras Version

3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

N/A

### Reproduction Steps

1. Import example aura or create a new aura with one or more Custom Text functions.
2. Use `%c1` or another numbered return value in Display Text or other text field.
3. Click Format Options.
4. `Format for %c1` will appear but will not actually function.
5. You can set Format = String, Abbreviate (checked), Max Char = 8, but the shown text will not be clipped.

### Last Good Version

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/9438134/160263689-51c8bbe3-c382-4578-bbc4-9ff0471449a8.png)

![image](https://user-images.githubusercontent.com/9438134/160263692-ad61a658-ae15-4da9-a2af-21a2efa0830d.png)

### Export String

!WA:2!9vvZUTTrq4i4ceacKIy12GgJIcbvKIwGcJAvuN2ceGiQqfRuzjvs6AxGciTKCj3nMAx2DxQF8TOt5SEe05Esh6dGFciek6dqEe8tqNLKYXnXO6aXmZo7SFZ38JQ0U64QbvdE9xSI6Zzo8uHp(ZUZguQIWf9tuuotASYpvQ4JDXZujpnmL5Rn)vFTrn4NaRsfSA1BA26zwTF(rDEXp394E9hu)BQvh55hGdJi0xEE8ygpPUbMfiM3pmuIvvwJy(WJmGtzkVww9CTS34Z5Xb8PmNP0e8Ol3QAfeHjMAeoAHsqJIWc5h(LIsX)YunpbBJsfOgxQ)ktWXX0a5EnE8H)GnEcgEGJWOyf5nYuVC9bcCiDMTZaRUDxfG9sddDHGioYQ7G2N0DrEi6einmtzuLxsmAowyZqJXsJRsLyRziFLtHtJUoQoqyOZwpSvth3HoUnTD3a(2jIXf4EWDjltzLG2izxic0jy3c9J5b4)8oxbCbwWqX)kKHajhD15yCstan(kBeq7KLsCCyoNLDxa4seq)ifMScWGnosxV(PhKDVnGQhY)8ibpLf869sQQGQ3qjbb85zLvGKpp3y(NqUymsn0VXqKNNapHcbD0YRpx8i)dQ9i)gj3)gXPfpMlErLkv25nfw3cnZMN42p5JYncTsCiYu)tPbkIztq9QIxKodhKB8vBkAf(TsCDz(5VeA6OHZH0uWvaA0TFM963ZAtjGzQ8sw)tC72PNv29eqoRpQmABZYv5U7NJ1DGFlV(6j3VTGErTFjffaCiQMRBYdFpgrwkyY4m8)Hg3c3K9EFA8GsjpjuVzrfqEkxeCQaLS40sHIeDcvs9IXJk52BmwKSBNE9SShA231T)X2DE(rU32J1Ouk7P3wf9GBwrFl35qVa)WK6))DadhJMT7T50bVRt)ZMOy(02c8FKIz(Zh8bF7(n((IAI(G16pBRil0k6A3gVuLIZ6pblGbSvAZDXSif5tY9FlbVuR066c4LWm1Z3AHyQpKK)6UeQ)5mSuUt(nC8rX4cXUuW8U5pGjW9ybXJGPre1RmJ5OG2EkWvM6b2JtJvudt9a3dY(DdB)yKuQLmLaFPfwjYNY0WpZWgfNqq7SeXO6ECo7qBPcjuTVeJKyhLipBUB29YEYMa9Gk4Yq92kHedBZcKl0(LhRNyogrzTZcY9odNfMfL9eVqkJkjVR51uwrLaINH5fC(4kcu(Az5Hz(gzqka3tzSsX9NuSk5tRm6S60Gfoe(0AMPr2tZh9whkGftasHbGDUQO3RT2KguEoTSTS6z)2Hhpa1H0idOPwhxmPrkny98l(rIOZJ7zEbk5J3U0wpV(mQebT2bKv6SLw83jl26brmRScxv69D7)49p4WQt(7Z(3)

**Comment by InfusOnWoW** [comment]
Oh this is Pandoras Box.

Turns out that there's a inconsistency what %c does when the state contains a .c member.

"%c" => Uses custom text function output
"%c " => Uses state.c
"%{c}" => Uses state.c
"%c1 " => Uses state.c1

(Same applies to all legacy text replacements, "p", "t", "i")
