### ISSUE TITLE
3.7.16-15-g8583018 - Lua Error 'isPaused'

### ISSUE THREAD

**Issue by behub-torch** [WeakAuras/WeakAuras2#3562]
### Description

Updated to latest alpha. WA stops functioning with a repeating lua error. Downgrading to release version removes the lua error and WA go back to functioning.

### WeakAuras Version

3.7.16-15-g8583018

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

2534x WeakAuras\BuffTrigger2.lua:1918: attempt to call field 'IsPaused' (a nil value)
[string "@WeakAuras\BuffTrigger2.lua"]:1918: in function <WeakAuras\BuffTrigger2.lua:1917>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'IsPaused' (a nil value)"
WeakAuras = <table> {
 IsSpellKnownForLoad = <function> defined @WeakAuras\Prototypes.lua:1105
 normalWidth = 1.300000
 StopMotion = <table> {
 }
 GetRuneCooldown = <function> defined @WeakAuras\GenericTrigger.lua:1976
 SortRegionData = <function> defined @WeakAuras\RegionTypes\DynamicGroup.lua:213
 CheckRange = <function> defined @WeakAuras\Prototypes.lua:35
 CheckTalentByIndex = <function> defined @WeakAuras\Prototypes.lua:923
 ShowOverlayGlow = <function> defined @ElvUI\Libraries\Core\LibCustomGlow-1.0\LibCustomGlow-1.0.lua:612
 RegisterItemCountWatch = <function> defined @WeakAuras\GenericTrigger.lua:3457
 CheckForItemBonusId = <function> defined @WeakAuras\GenericTrigger.lua:4051
 UnitCastingInfo = <function> defined =[C]:-1
 CalculatedGcdDuration = <function> defined @WeakAuras\GenericTrigger.lua:4030
 RealTimeProfilingWindow = <unnamed> {
 }
 GetSpellCharges = <function> defined @WeakAuras\GenericTrigger.lua:2014
 GrowFunctions = <table> {
 }
 RegisterBigWigsCallback = <function> defined @WeakAuras\GenericTrigger.lua:3113
 ToggleProfile = <function> defined @WeakAuras\Profiling.lua:377
 race_types = <table> {
 }
 ValidateNumeric = <function> defined @WeakAuras\Prototypes.lua:984
 CancelScheduledProfile = <function> defined @WeakAuras\Profiling.lua:385
 CheckMPlusAffixIds = <function> defined @WeakAuras\Prototypes.lua:1036
 WatchForCastLatency = <function> defined @WeakAuras\GenericTrigger.lua:3393
 TenchInit = <function> defined @WeakAuras\GenericTrigger.lua:3288
 StopProfile = <function> defined @WeakAuras\Profiling.lua:350
 GetGCDInfo = <function> defined @WeakAuras\GenericTrigger.lua:2038
 GcdSpellName = <function> defined @WeakAuras\GenericTrigger.lua:2050
 GetUniqueCloneId = <function> defined @WeakAuras\GenericTrigger.lua:3502
 WatchUnitChange = <function> defined @WeakAuras\GenericTrigger.lua:2612
 EJIcons = <table> {
 }
 GetSpellCooldown = <function> defined @WeakAuras\GenericTrigger.lua:1984
 CompareSpellIds = <function> defined @WeakAuras\Prototypes.lua:1149
 GetDBMTimer = <function> defined @WeakAuras\GenericTrigger.lua:2933
 SpellSchool = <function> defined @WeakAuras\Prototypes.lua:131
 gcdDuration = <function> defined @WeakAuras\GenericTrigger.lua:2046
 GetHSVTransition = <function> defined @WeakAuras\Prototypes.lua:487
 defaultFont = "Friz Quadrata TT"
 HideOverlayGlow = <function> defined @ElvUI\Libraries\Core\LibCustomGlow-1.0\LibCustomGlow-1.0.lua:696
 UnitPowerDisplayMod = <function> defined @WeakAuras\Prototypes.lua:1157
 ScheduleDbmCheck = <function> defined @WeakAuras\GenericTrigger.lua:2992
 IsClassic = <function> defined @WeakAuras\Init.lua:39
 GetPolarCoordinates = <function> defined @WeakAuras\RegionTypes\DynamicGroup.lua:130
 GetBonusIdInfo = <function> defined @WeakAuras\GenericTrigger.lua:4064
 GetRange = <function> defined @WeakAuras\Prototypes.lua:31
 UnitExistsFixed = <function> defined @WeakAuras\GenericTrigger.lua:93
 versionString = "3.7.16-15-g8583018"
 newFeatureString = "|TOptionsFrame\UI-OptionsFrame-NewFeatureIcon:0|t"
 CheckCombatLogFlags = <function> defined @WeakAuras\Prototypes.lua:1054
 CallCustomConditionTest = <function> defined @WeakAuras\Conditions.lua:148
 WatchSpellCooldown = <function> defined @WeakAuras\GenericTrigger.lua:2465
 CheckPvpTalentByIndex = <function> defined @WeakAuras\Prototypes.lua:935
 Ge

### Reproduction Steps

1. Install Alpha (3.7.16-15-g8583018)
2. Load in. Errors Appear.
3. Re-install release version
4. Errors gone :)

### Last Good Version

3.7.16

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/8356708/WeakAuras.zip)

**Comment by mrbuds** [comment]
probably due to error in libgetframe that is now fixed
