### ISSUE TITLE
Ready for Update

### ISSUE THREAD

**Issue by Lucbc** [WeakAuras/WeakAuras2#3563]
### Description

There is 2 auras that i want to remove, but they keep coming back to the READY FOR UPDATE, what i should do to remove them?

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Open the WA
2. See the READY FOR UPDATE SECTION
3. If i click to update, it shows to import, but i want to remove it

### Screenshots

![image](https://user-images.githubusercontent.com/31831495/160264679-4ac4ac99-623c-4e97-8de3-cb57160252cb.png)

**Comment by mrbuds** [comment]
Tooltip show which auras it wants to update, you can right click > ignore update, or delete those auras, or delete url field in information option.
In the future please use our Discord for general help, and github tickets only for bugs & feature request.
