### ISSUE TITLE
LibGetFrame missing comma

### ISSUE THREAD

**Issue by jazz836062** [WeakAuras/WeakAuras2#3564]
### Description

Line 244 in Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua is missing a comma at the end.

### WeakAuras Version

WeakAuras 3.7.16-15-g8583018

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

10x WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0-30.lua:245: '}' expected (to close '{' at line 240) near '"InvenUnitFrames_TargetTargetTarget"'

Locals:

### Reproduction Steps

Log in with Alpha version.

**Comment by mrbuds** [comment]
fixed
