### ISSUE TITLE
[Alpha] Can't edit empty groups until you move them once

### ISSUE THREAD

**Issue by Luckyone961** [WeakAuras/WeakAuras2#3567]
### Description

As explained on Discord, you can't edit empty groups. However, if you move them up or down once you can edit them.

### WeakAuras Version

3.7.16-16-g437b833

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a group or dynamic group
2. Move the created group into another group
3. Click on it - you can't edit the group at this point
4. Move the group up or down using the arrows or drag and drop
5. You can edit the group at this point

### Screenshots

![GIF](https://i.imgur.com/k64790u.gif "GIF")

**Comment by mrbuds** [comment]
> you can't edit empty groups. However, if you move them up or down once you can edit them.

It's supposed to show the "new aura" panel, not group edit options
