### ISSUE TITLE
Add "no auto clone" option to Player/Unit Info -> Spellcast [Multitarget units]

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#3568]
**Is your feature request related to a problem? Please describe.**
Alot of the time in Dungeons There are spells that are important to know they are going on that get casted by multiple units at the same time but you only want to see once to be reminded of them.

**Describe the solution you'd like**
A simply "no auto clone" option like the CLEU triggers do have

**Describe alternatives you've considered**
I could write my own trigger that doesn't have cloning. I even tried checking the GenericTrigger code to add this option myself and make a pull request but i was to stupid to find it

**Comment by InfusOnWoW** [comment]
That's not really possible atm. The cast trigger's multi-unit support builts on top of the unit support in GenericTrigger, which can't support that.
