### ISSUE TITLE
Button (or Dropdown) to sort auras in a group alphabetically

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#3569]
**Is your feature request related to a problem? Please describe.**
Moving multiple (~30+) auras to a new group often messes up the order of the auras. Especially for groups where the auras are for bosses and are numbered accordingly, having the correct order matters a lot. Also for organizing big groups (maybe even nested groups) it would help a lot.

**Describe the solution you'd like**
A small little button to sort all auras in a group alphabetically (including numbers). 

**Describe alternatives you've considered**
Wouldn't really be a complete alternative, and most likely very annoying to fix: moving multiple auras shouldn't mess up the order.

**Additional context**
Since for dynamic groups it could probably be a problem (and they already include sorting) the implementation would only be useful for simple groups.
I'm thinking of adding it either to the group settings (dropdown to select the sort method or button) in right tab or a small button on the entry in left-side panel.
![Unbenannt](https://user-images.githubusercontent.com/48932939/160890279-f1241f57-b06e-4040-ad31-558d793bd49e.png)
![Unbenannt2](https://user-images.githubusercontent.com/48932939/160890283-b0541011-201a-42cb-a9ba-399a9667fa25.png)

**Comment by InfusOnWoW** [comment]
No that's not a good feature. It has a far too narrow use case. I did make drag and drop order preserving though.
