### ISSUE TITLE
Leverage the extra payload from UNIT_AURA event for optimization

### ISSUE THREAD

**Issue by SweepyBoop** [WeakAuras/WeakAuras2#3571]
**Is your feature request related to a problem? Please describe.**
Recently Blizzard introduced an optimization on UNIT_AURA event, with extra payload isFullUpdate and updatedAuras vector containing the auras that changed. The blue post is here: https://us.forums.blizzard.com/en/wow/t/new-unitaura-processing-optimizations/1205007

The basic idea is to pass the extra payload to AuraUtil.ShouldSkipAuraUpdate() with your isAuraRelevant functor. With that in place, we can do a partial scan on the updatedAuras only, instead of a full scan on the unit id (unless isFullUpdate).

Do we intend to leverage this optimization, or WA already does something similar?
(I doubt it though, UNIT_AURA didn't have the updatedAuras vector until a few days ago, so likely we are doing full scans just based on unit IDs).

**Describe the solution you'd like**
Leverage the extra payload and AuraUtil.ShouldSkipAuraUpdate if it's not already in the implementation.

**Describe alternatives you've considered**

**Additional context**

**Comment by InfusOnWoW** [comment]
We are aware of that, it's close to unusable for our use cases. Nor is it particular useful for any unit frame addon.

We might take another look at it for 10.0.
