### ISSUE TITLE
Weakaura update bug.

### ISSUE THREAD

**Issue by kgwium** [WeakAuras/WeakAuras2#3576]
### Description

I am unable to get rid of this update bug,  from seeing in the picture, is that I have already updated the shadowlands dungeon WA multible times and still it insists on staying there.
if I hover over it, an empty long black box appears with nothing in it and I can´t right or left click it to ignore this update.

I check the waigo companion and an update appears there when the creator of the WA publishes his update, even then it just lingers there.

I have even let it update again and again and have gone AFK while it is updating for some time and it is still there.

![WA bug](https://user-images.githubusercontent.com/40608423/161870546-b37b18cb-a18f-4e81-ac9b-54c62946eab6.png)

Here below is the image with the long black box, hover over it with the mousepointer.
![WA bug black box](https://user-images.githubusercontent.com/40608423/161871675-a40a90a5-60bf-411d-a10e-7d620407a935.png)

### WeakAuras Version

Weakauras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No error string

### Reproduction Steps

Nothing to reproduce really,  that update just does not go away.

**Comment by kgwium** [comment]
I just deleted the WA from the list that I had installed and reinstalled the WA from that update WA and it still ingers there.

**Comment by mrbuds** [comment]
Please use discord for general help with wago app on wago's channel
