### ISSUE TITLE
Text aura takes double amount of time compared to the same icon aura during profiling

### ISSUE THREAD

**Issue by Vumse** [WeakAuras/WeakAuras2#3577]
### Description

I play mage and faced bug with Comet Storm WA (talent or tier set)

I found WA that suits my need on wago - https://wago.io/R_2MSCFU5
But I actually don't need fancy icon, only text. I converted it to text, deleted condition and second trigger and made text visible (because after convert its alpha was set to 0)
After that I run profiling to measure diff between auras and found out that text WA took double amount of time compared to Icon one
During profiling all I did is frostbolt spam and casted comet storm on cd. Did it in undercity to minimize other players impact
I think its a bug because Icon WA contains text too but takes less time 

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Install both WA
2. Start combat profiling
3. Fight dummy for 1 min, during it cast comet storm on cd
4. Compare results

### Screenshots

Name of WA - Comet Storm Tier Bonus
![image](https://user-images.githubusercontent.com/41110396/161996746-09422b51-331d-4095-81fb-3f3ae1987757.png)

### Export String

Icon WA:
!WA:2!fF1tVTXXvCZYdgyBHRJCHQvCAXA2gvRyjAjzyzeJQeisrjZaAk1LKXUiiy1S7oK7eTCNjZmR(JBsBdrpeGEtOWTN6bDoOhy)g4d58aH(jWh6PEsFc6BML)tMKQ6wNlK7B(9EZ8(9EVzEtMTMP9mbZe8TpMttKrKymFNg1RuUAPtj(04A0eUpoJ3HOw0YBEIJ7QpRwXTA8i(r70SPalZWUFarWIqhxhFK0TjL3gjDzUssBSBWXXO2eFxzihlcPrbhFMiefqp83MQ87DTUOy)qkFxkjw6vSu16LCoZNciPhgx7qcdVhZE62p9RmSB6NiK02Aenybij2bFaow(6(wQuqlCih5lj0yXAocjIlTkqIjY59svLvaLWrU44dYtefrcP962nrrcS1a5(0KyjMdtS8qHra06Wwrl9KaQBQ12ZRjyCrOvhjN0QfMl(7ZZ793)Db5XmS6wVrK4z2L1sA2KCux3IBuRUBT6B4uVBQvCdjbyhTJg0jawq9Up3QlRUH3tXOizyHeWb80udM3xfTT7c(NeNyiIbRYUCmSko12TuLkDemCuu5aHv6Cc2knQwgwC9KPBJgflwQ0ML28jPM3UyLsnEIzE3n34zBSDjh)qS)(QBOU1rx)F0mj2WT3ZSYIfnwDX85ZVGLnminTnsSxF9CtBHYzJIdSTbDSLH4yJE6re1hfz7UO7IMnnWZaKbZcwovmyA7vE0dF0h(OlQUEmXG1Krmi2l5j4jdz00G(tIJdSg93rCy7Cf35zf2OUBLD22T0Ncz4UnQUv5kqIU2PNGVQd4ap2MTie7kzysW5nLHB3O8MtGb6bZSAJgJs50rvDD7NJr7Vb4lI8Tp2iBm6kDx0NTf4iSV8ERS6WW5yKFFUFTXnMES0s26sTXKd6pHqdWRt2mtluoGVUCngg3gt09TxXEmL7hlVON0KeP1ODsKKyhGAJAHT7xInjhCWMZEPjS5)O)V4Rxrx1UxPVVUIinqhIe2p2oKiftcVgyAIytchBY9gUrES9Lg)7v4P1zCVqR9uPPLwcUBblnREn9XpJUWxon9wN0FfP0LVs83eiOH8tan(xnbw6Jw(s5ObWGSgTAXu5y(Y05jWsAfspH(ZYL7ZNou9yeCRB)7Mkmd0q6H9oYCXlfOFikUfo4kHLXPTGaROoCHgOqoZ1G5UCD6FjjGFLpm)dVCW4JyKu49QT0QC)TXMsT7TWLRmkrsFkC78)tx5RN4mtkHrp4yzcpE8lFUsjzJcy0)FHBMSG)4anLHfwNgG9Gwp0em)PLQS7wnQCcKGL2LI18QB)9Q5u2VjrGDrrhIowO3w7PEx1DsL5jOCVNrdaz340I04aIP9Qo6j1DMSNAEl2mdHQBAjf(9Tu2Q7Q(LQ3xTOAjvERUqlEFHPhIdGoJyZ0RDU0TsfAlIp7od6XqUWaE6Zw9Z1Eg7Dqgv7PGEr(URXUZe7Bm9pQF25eDTumk6tHUZaZ2689Xy2gW5C(shDAryNdP8GNZrSopV3FagtGK6KmCyHM0yj7MBXjV0(3KGcaHi7615hKAUSNc3k4GBPzKpyw1CNbF6H83Vf0KDCW3(tz3vQ3wYX7PLXX(eJjozaKCVpJn3euOVZ8gJy4Q6MMgPlSrJ67WULrOotfWq8FojaAzCd4ZZtnc5iCGr43CwAt49AkpZRnZ)fqmG08yL1PCQ(SannwO6ovlPMJdoJgZPgG(0ik)tYcJt6T7ILQpo1ihaEIxe0e)mP7WrB(ptVL9f9)0aPpPR(1NnWA6uu1pGDZuhA4dgoPC1QLCCRVZUxW(9nypfsfw0SlZKjt2H2Tg5L41zlmTiX4VEH9ZNg2EVeXletAfkxVljovcehTkerrbV6eDLqm0Oap0tIIGRbM1X0gHvbDs3SkFRZ1qisCB8xMap9jiKDt9x6E6nsar9QO8HEceave4Q1DphZ3At8MloZSEcsCRi83uqa(QbWftiuL70NjU7Pdtj(t)OU9QEkdVb82)4V)FE2f42SoPr9mp9JFZmMr2mDhPEdsy9afBsAbPpMQaDmSG(bLRMWJy3jukzIN8GhOFwzEc9bdEx5dw580i8wC4ukTwE1k6uQu1Un1cQj1fAzpbftsz31uVZwQ5ketJXVgJeAa44wYWRFw)BdmVjIlWWAhi6OXyYN(QcTrKyqx1xP(6RR(9Q)G6pc)D23wc7xm93FoSwL9t6)wtnSnjceK2he6jWTHiUZk5xo)YfEjL2odVxHvHkL2Q(PsQFVtmUDM9ErosaB2I02q7m1KWkzxNa33xGgNiuj75GIyHOSohQJqRFgeibAAhM5uxRvtibDxquz7O1ASpPmItI1ggE27XPHS)ZpS7BxjCQ)GtT)G5vlSM62V316CaOQEZ3He7tB7HKohGIsWz4P3ElE35vVA3SlNF1oWv0aXkpw9NtvoR6Vuq3lG6vzv)vnm9Hczu)n1x2Pp5eEYGdPuwZi8Ey(hNFL1M5G)1l(V)

Text WA:
!WA:2!fF1tVTXXv8qOdbHPbXHWWijUbybdAImSeTOmSeIbyc4sTusg0sQljTDrQZQz3DwUt8UZmzMz1FCrpuHIIEkh0hbDUOhy)gKd98cH8jWh6PCsFc6BMLKIoKsv36EGC3387nZ8(9EZm)MsTRKwjSs4FFDbltLqOyXU971z7DCoJeWODzzIaCj)drdyBVXPUER(0UTA3)rUbSeM4jL26BEtfZZclCUmgfYo8pSBuKeR(TVZqeniMj2JrOk)wo70ZX98aglbWq7EiHJ3NBfsK8e0X9WhP8IyIuKYJ7PiP4rFvIFRGmPILQr0NhIuyx8byQ6nOmWksrcEojufB3e(uGcuegvUMRuHeQY(rekrgx2g(t9f(fDe3gLjqEy6b1iYwiPYQHvekrIlpXEalJQWcOHvU0ycaThmX0wpnK5v0B7FIsqgmalK)4xig96)XwDmhNF73iZ8nZ1UzrrKJg61Qz3EED710T3zHyFWypaNylNo71UFNtcHrsp9RU6k5FG)wyucewzWm3xZqyHlfLILLZV9rV7)mkJAc1fHavHLlzgMLQvR29kBbpKilJfRgnQ2FNTHbDpNoDkg((TA54SHZgvTq0qllWhlvmMA8t)KWcqjwEl5TKKJtsGWfGmPvONlmdDTv9h9Wh9vp6TDx)mxoB(iMKcuIm88HmD2yCJyAy5P)FQa2QARDFQDZEED2DtpNNbLDE93P92DGQpDqpNyvxUb8ykFjiH5yysi4n19B2F7nMddmcMz0muR3gnFAZnDk40PDTH1ZXOx1eIfzT0Jn2MHUkMfJzBjobhOwS(QxMoNH8hZ9RnBNPFwEzlDf)m2b)NtQb4153nxvQCcFD9ECzEBgt33QU1mopox(2rsejr7rAwIIyfIsrdWwJxxnVaCYKZA55m5)6)VeR3Wq1QyDUvGEfrrIogjTw3kMOKZdVgyrHyerGn1Exorw36AZ)Jw4P9z2Oq79vstlVSad7VBg9U6TFMEGVEA6xTH7nKsx5gXFZHGUKFcz0VCoS0xVY1YrtGbvnA3Om1mXYvZtqpPDOyh6VTA1xE1q1ptHRH1F6kHzGgZoC0wMlDTadIr0b4WBewUGnasSs9zsGdv1v(HvVEFgFKfGV(xv7Hxpy8rCsb8rRT0UC)nXMLAlEVR3z9P9BrcX)pdL)8CBzEfm6hbwLjOZE4ZnQiBAat)(BDYuz4LtmlM3ouwUyFljV(vDQ8JhThqRoo9F80hT4geJdEv(hmruXEcmiQW1GzyHyepTUJHMcPmJuPX2JbMZ1KqpfQOluPuEiO967n6ioaVkIEmVYiLwfT3HnGeWV7eLgQ7nHT(2vFPo(4FeY48ihEkle)pEh(DNRKUIxYx(cIEfffL8mqYe0TdU4vymVjqqbkxDXr8PWbGrgnJ5VhitsIu6ImCSDeJQ43QTG8ARFFgkemIS61tCqrhTWzaX4IhO1)9P3j)toh(0hf8QbGQwAOFmMmiw14KX6pJTtyOW)MTK8A8DCnNUu2na24xENC7YxKjXEefof)dzGo1WyFfkb4CDB8k6gnq9Gnf80t99T1)QB9nVDd3XxsOdsW)f(T0DNo)y6sOplFYHmr4Zfi(jpF8l6qSlmJACgO8oKyeZAYtAcDBW2h)H)7)1iz2VOqM9c87F1AOdpg0msc8uXWk7yiYpE4uGR(74RMrch(6N8d71FdF3DPRDMWWG69aSvaeXXfJYV8(UhQLz3WfLWJrlCoSEeK2VlVykEkIssnlTxl)JA)tyKe3vjW0bQ43n)tSPmk(8X7vyksfsSocLNOHQhT8xANIi025)rWH8xM)D5E57d)x5xBH)5xD4Yf4aIPyW(1mwAjX3df0KOJT740Uh)2JZ9Ap3Gir(j6mReNcLqU1RTsTvotXcgvp9XL2)fvjH8pRflfoSRlC7IuREeyPPnJMjTwutp3ZwFfP9hgjaP5qedLKlCrXTEARnPJm)UTCDC2rCubtwYh8iImOSGq1dfoE1mrc)UXkfx(4h8a99SQrypyYfTEq9Hfj8wfx4QuPfodw4Jdn375V(BgsOfSamPl)tJJrNWb44ks)hwB9A1xRYb)8l(V)

**Comment by InfusOnWoW** [comment]
This aura appears to require a 4set bonus to test.

In any case, the profiling results might not be correct, as that feature can't by design track all the time spent on each aura. And also icons and texts are very different region types. I don't know which one I'd expect to use less resources.
