### ISSUE TITLE
WA ERROR

### ISSUE THREAD

**Issue by Sevens9527** [WeakAuras/WeakAuras2#3578]
### Description

WA has no title block，Some WA exist but are not in the directory

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

[string "Error in: 目标蓝量':'custom text"]:2: in function <[string "Error in: 目标蓝量':'custom text"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\WeakAuras-3.7.16-16-g437b833.lua"]:4067: in function `RunCustomTextFunc'
[string "@WeakAuras\RegionTypes\Text.lua"]:198: in function `Update'
[string "@WeakAuras\WeakAuras-3.7.16-16-g437b833.lua"]:3831: in function <WeakAuras\WeakAuras.lua:3830>
[string "@WeakAuras\WeakAuras-3.7.16-16-g437b833.lua"]:3925: in function <WeakAuras\WeakAuras.lua:3887>
[string "@WeakAuras\WeakAuras-3.7.16-16-g437b833.lua"]:4008: in function `UpdatedTriggerState'
[string "@WeakAuras\WeakAuras-3.7.16-16-g437b833.lua"]:3770: in function `UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras-3.7.16-16-g437b833.lua"]:3743: in function `FakeStatesFor'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1433: in function `SyncVisibility'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1459: in function `PriorityShow'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:780: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:768>

### Reproduction Steps

Every time I open WA (/wa), the interface appears wrong

### Screenshots

![截图20220407022018](https://user-images.githubusercontent.com/88993106/162042201-7ca55a43-456c-4de8-aec1-01ab98c6e244.png)

**Comment by mrbuds** [comment]
This is not an error in the addon but in the custom text of your aura called 目标蓝量

**Comment by Sevens9527** [comment]
Then why doesn't my wa open (/ WA) display the loaded title
