### ISSUE TITLE
Canceling moving a dynamic group removes groups and dynamic groups from the new aura menu options

### ISSUE THREAD

**Issue by MikeCook9994** [WeakAuras/WeakAuras2#3579]
### Description

If I cancel moving a dynamic group into another, groups and dynamics groups should remain in the new aura menu. This does not happen if you cancel the move of a non-dynamic group

### WeakAuras Version

3.7.16-26-g8f138a1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

n/a

### Reproduction Steps

1. Click on the button to move a dynamic group into a group
2. Click on the dynamic group you're attempting to move to cancel the move
3. Click on "New Aura"

### Last Good Version

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/6856899/162558299-337ce8b3-e96f-45dc-9747-a716ac700371.png)

**Comment by InfusOnWoW** [comment]
After try to reproduce this, I think the report is invalid. After canceling the moving of the dynamic group, the dynamic group is selected. Dynamic groups can't contain any sub groups, so not showing those options is correct.
