### ISSUE TITLE
All candidate events for a custom TSU trigger get fired once after closing WA option panel

### ISSUE THREAD

**Issue by Nukme** [WeakAuras/WeakAuras2#3585]
### Description

I make a WA using TSU trigger based on events. The candidate events are CLEU:SPELL_CAST_SUCCESS, ENCOUNTER_START, CUSTOM_EVENT.  This WA is loaded for a boss fight.

Everytime I open and close the option panel, or get into the boss fight.  the code block triggered by CUSTOM_EVENT would take effect while it's totally unrelated.

By further investigation, I find out that all candidate events are triggered once indiscriminately after closing the option panel or after loading WA, which is odd.

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No error.

### Reproduction Steps

1. Make any type WA with custom TSU trigger.
2. Set candidate event to ENCOUNTER_START
3. Write simple test code, like
```
function(allstates, event, ...)
    print(event)
end


```
4. open  and close WA option panel

**Comment by SpatenLa** [comment]
https://github.com/WeakAuras/WeakAuras2/wiki/Trigger-State-Updater-(TSU)#introduction
working as intended

**Comment by Nukme** [comment]
I see. Dummy events. Thx.
