### ISSUE TITLE
having issue with WA /wa not working

### ISSUE THREAD

**Issue by psyc86** [WeakAuras/WeakAuras2#3590]
### Description

Recently its /wa stop working.
I deleted all the addon/wa and reinstalled.
Deleted WTF as well started fresh.
still having same issue.
I installed buggrabber and bugsack.
it would be greatly appreciated if whats causing this issue.

### WeakAuras Version

weak aura 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x WeakAuras\WeakAuras-3.7.16.lua:1067: script ran too long
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:1067: in function `Login'
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:1150: in function <WeakAuras\WeakAuras.lua:1101>

Locals:
initialTime = 15000
takeNewSnapshots = nil
loginThread = <no value>
startTime = 218201759.868900
finishTime = 218204955.657900
ok = true
msg = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = true
(*temporary) = true
(*temporary) = <function> defined =[C]:-1
(*temporary) = "script ran too long"
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras\WeakAuras.lua:3065
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @WeakAuras\Transmission.lua:795
 combat_event_type = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras\GenericTrigger.lua:2366
 InitializeEncounterAndZoneLists = <function> defined @WeakAuras\Prototypes.lua:142
 IsEnvironmentInitialized = <function> defined @WeakAuras\AuraEnvironment.lua:187
 duration_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras\History.lua:21
 RunConditions = <function> defined @WeakAuras\Conditions.lua:648
 tooltip_count = <table> {
 }
 pet_spec_types = <table> {
 }
 AddParents = <function> defined @WeakAuras\WeakAuras.lua:2715
 ReplaceLocalizedRaidMarkers = <function> defined @WeakAuras\WeakAuras.lua:5062
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 ensurePRDFrame = <function> defined @WeakAuras\WeakAuras.lua:4576
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 FinishLoadUnload = <function> defined @WeakAuras\WeakAuras.lua:1750
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined @WeakAuras\WeakAuras.lua:159
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 StringToTable = <function> defined @WeakAuras\Transmission.lua:744
 RegisterLoadEvents = <function> defined @WeakAuras\WeakAuras.lua:1607
 FixGroupChildrenOrderForGroup = <function> defined @WeakAuras\WeakAuras.lua:3530
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:958
 CheckSpellCooldown = <function> defined @WeakAuras\GenericTrigger.lua:2241
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @WeakAuras\WeakAuras.lua:1964
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @WeakAuras\GenericTrigger.lua:2423
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @WeakAuras\WeakAuras.lua:3201
 NeedToRepairDatabase = <function> defined @WeakAuras\WeakAuras.lua:2043
 StopProfileSystem = <function> defined @WeakAuras\Init.lua:91
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 CheckSpellCooldows = <function> defined @WeakAuras\GenericTrigger.lua:2297
 IsOptionsProcessingPaused = <function> defined @WeakAuras\WeakAuras.lua:1338
 ValueFromPath = <function> defined @WeakAuras\WeakAuras.lua:3482
 Login = <function> defined @WeakAuras\WeakAuras.lua:1004
 GetTriggerConditions = <function> defined @WeakAuras\WeakAuras.lua:3310
 trigger_require_types_one = <table> {
 }
 noreset_swing_spells = <table> {
 }
 bufftrigger_progress_behavior_types = <table> {
 }
 chat_message_types = <table> {
 }
 precision_types = <ta

### Reproduction Steps

i just log in /wa doesn't work

### Screenshots

1x WeakAuras\WeakAuras-3.7.16.lua:1067: script ran too long
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:1067: in function `Login'
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:1150: in function <WeakAuras\WeakAuras.lua:1101>

Locals:
initialTime = 15000
takeNewSnapshots = nil
loginThread = <no value>
startTime = 218201759.868900
finishTime = 218204955.657900
ok = true
msg = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = true
(*temporary) = true
(*temporary) = <function> defined =[C]:-1
(*temporary) = "script ran too long"
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras\WeakAuras.lua:3065
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @WeakAuras\Transmission.lua:795
 combat_event_type = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras\GenericTrigger.lua:2366
 InitializeEncounterAndZoneLists = <function> defined @WeakAuras\Prototypes.lua:142
 IsEnvironmentInitialized = <function> defined @WeakAuras\AuraEnvironment.lua:187
 duration_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras\History.lua:21
 RunConditions = <function> defined @WeakAuras\Conditions.lua:648
 tooltip_count = <table> {
 }
 pet_spec_types = <table> {
 }
 AddParents = <function> defined @WeakAuras\WeakAuras.lua:2715
 ReplaceLocalizedRaidMarkers = <function> defined @WeakAuras\WeakAuras.lua:5062
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 ensurePRDFrame = <function> defined @WeakAuras\WeakAuras.lua:4576
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 FinishLoadUnload = <function> defined @WeakAuras\WeakAuras.lua:1750
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined @WeakAuras\WeakAuras.lua:159
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 StringToTable = <function> defined @WeakAuras\Transmission.lua:744
 RegisterLoadEvents = <function> defined @WeakAuras\WeakAuras.lua:1607
 FixGroupChildrenOrderForGroup = <function> defined @WeakAuras\WeakAuras.lua:3530
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:958
 CheckSpellCooldown = <function> defined @WeakAuras\GenericTrigger.lua:2241
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @WeakAuras\WeakAuras.lua:1964
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @WeakAuras\GenericTrigger.lua:2423
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @WeakAuras\WeakAuras.lua:3201
 NeedToRepairDatabase = <function> defined @WeakAuras\WeakAuras.lua:2043
 StopProfileSystem = <function> defined @WeakAuras\Init.lua:91
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 CheckSpellCooldows = <function> defined @WeakAuras\GenericTrigger.lua:2297
 IsOptionsProcessingPaused = <function> defined @WeakAuras\WeakAuras.lua:1338
 ValueFromPath = <function> defined @WeakAuras\WeakAuras.lua:3482
 Login = <function> defined @WeakAuras\WeakAuras.lua:1004
 GetTriggerConditions = <function> defined @WeakAuras\WeakAuras.lua:3310
 trigger_require_types_one = <table> {
 }
 noreset_swing_spells = <table> {
 }
 bufftrigger_progress_behavior_types = <table> {
 }
 chat_message_types = <table> {
 }
 precision_types = <ta

**Comment by InfusOnWoW** [comment]
This is one of:
a) Some other addon is interfering with WeakAuras. Try disabling all other addons.
b) Something in your settings is causing a bug in WeakAuras, we need your settings to reproduce.
c) This isn't the first lua error that bugsack shows. The first error in each session is the important.

**Comment by InfusOnWoW** [comment]
No further information.
