### ISSUE TITLE
AddOn 'WeakAuras' tried to call the protected function 'SetFrameLevel()'.

### ISSUE THREAD

**Issue by ekitrak** [WeakAuras/WeakAuras2#3593]
### Description

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'SetFrameLevel()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "@WeakAuras\RegionTypes\Icon.lua"]:257: in function `SetFrameLevel'
[string "@WeakAuras\SubRegionTypes\Background.lua"]:14: in function `SetFrameLevel'
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3550: in function `ApplyFrameLevel'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:886: in function `Expand'
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3811: in function <WeakAuras\WeakAuras.lua:3805>
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3900: in function <WeakAuras\WeakAuras.lua:3862>
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3983: in function `UpdatedTriggerState'
[string "@WeakAuras\BuffTrigger2.lua"]:1588: in function <WeakAuras\BuffTrigger2.lua:1580>
[string "@WeakAuras\BuffTrigger2.lua"]:1924: in function <WeakAuras\BuffTrigger2.lua:1917>

Locals:
Skipped (In Encounter)

### WeakAuras Version

3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'SetFrameLevel()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "@WeakAuras\RegionTypes\Icon.lua"]:257: in function `SetFrameLevel'
[string "@WeakAuras\SubRegionTypes\Background.lua"]:14: in function `SetFrameLevel'
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3550: in function `ApplyFrameLevel'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:886: in function `Expand'
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3811: in function <WeakAuras\WeakAuras.lua:3805>
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3900: in function <WeakAuras\WeakAuras.lua:3862>
[string "@WeakAuras\WeakAuras-3.7.16.lua"]:3983: in function `UpdatedTriggerState'
[string "@WeakAuras\BuffTrigger2.lua"]:1588: in function <WeakAuras\BuffTrigger2.lua:1580>
[string "@WeakAuras\BuffTrigger2.lua"]:1924: in function <WeakAuras\BuffTrigger2.lua:1917>

Locals:
Skipped (In Encounter)

### Reproduction Steps

no idea, showed up in raid

**Comment by mrbuds** [comment]
Looks like you are using a clickable weakauras, they tend to break the addon.

**Comment by Colerain** [comment]
Having this issue on WotLK. Can the frequency of this error be reduced somehow?

**Comment by mrbuds** [comment]
> Having this issue on WotLK. Can the frequency of this error be reduced somehow?

Don't use clickable auras

**Comment by Colerain** [comment]
I understand why a keybind might be better. In this use case it isn't. The action is only sending a message to BG chat.
https://wago.io/Xt-7JGvLx

**Comment by mrbuds** [comment]
This code create a secure frame and anchor it to a frame create by weakauras.
There are things you can't do with secure frames or tainted frames, you can read more about it at https://wowpedia.fandom.com/wiki/Secure_Execution_and_Tainting
