### ISSUE TITLE
Finish effect from OmniCC is not working on weak auras

### ISSUE THREAD

**Issue by somecodingboi** [WeakAuras/WeakAuras2#3594]
### Description

OmniCC has an option to show all sort of effects when an ability comes of CD. If my memory is correct that feature was working fine with WA but for some reason now it's not. I tried it with only WA and OmniCC loaded and its still not working. Funny enought when i open the WA tab and it shows preview of my wa's the finish effect actually triggers. And also the effect sometimes but very rearly actually triggers correctly but then it stops working agian.

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Donwload weak auras and omnicc. 
2. Use for example the pulse finish effect of omnicc. 
3. The effect triggers correctly on the ability bars but its not working on the weak auras.

**Comment by InfusOnWoW** [comment]
That's on purpose. We hide the OmniCC frame if we don't need it.

**Comment by somecodingboi** [comment]
Is there a way to show it ?
