### ISSUE TITLE
Power Type: Mana (or anything) is triggerd on Warrior?

### ISSUE THREAD

**Issue by rakkarage** [WeakAuras/WeakAuras2#3595]
### Description

I have a simple low mana testing WA that only checks [Power Type: Mana] and [Power: <= 75] that trigger on my warrior? I could specify each class that uses mana in the load page I guess but [Power Type: Mana] should work too?

Sorry if I overlooked an existing issue or simple solution.
Please and thanks.

### WeakAuras Version

9.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. check if [Power Type: Mana] triggers for warrior

**Comment by InfusOnWoW** [comment]
Why did you not include the aura in the report?

**Comment by rakkarage** [comment]
sprry here is a weakaura that has  [Power Type: Mana] and [Power: <= 75]

!WA:2!1rvZUTTrq4qOdbGii1vi2iiTheCrYLayGKG40dParuwcobYwkK0woNOwYDO0MqT7IDxkz5JcTa5SEe05Espc5jGqipb(rWpbDwsLwJIeEHZSC(5B(2VHoDQpPoTo9ZpwjYnzmoO6Dwy33EAB)erMq9UA4J8PuMwMrMhcxAIsfQjetKmYWMar05CYewsKzSc0Jfz05Q59st1GXznHNmwO6lyCtCR2Ng22x24hxPkph5oj5AJyInIZKuIb8HPa3CnjhpLyyjdyuZyVMORIKyycU(qFTHOmUXPmotp21dFzCxyuSrJaL((prT18Z7i3vcQeSEsXmqfjqpcwO9F9F4zMlbVCmtz9CnerI1cv8Xaj7ebfgETopUeib5PPSlxh1Qzqyuqyt)WVC7sU)RE51)x6LPw4633(jFKQaTBXUXwkaulltW2wNfAjKL9wQ29F7tFfG9XpOF7UDxyROfAdL7ynVDdhUP8KVvQHROqmcXq0wDC7U97Cw3L58TeGR8NTC2uiSY3IV)(oYF57ETuz4BVDO3GxIGItYohjuKZhTyMqrhOiYfd2A4LkqiTthf7QgVpNqrIL0imCfoq(Wi790J2R4bBq3ysYNgHcoo1ltqONV0obCCQvdJnKmCY2ZFsEMH56NKr069kEPRhYqjvgSRaRXcB)cqN)AJEmHkMDrLWR2kvz7SmGNbNOvjcoLvQuCL)2pwbkvqcZoC1ws4mRwtWpS4(D(cq0qGrb8rMX3T4bECbh2qZvLrezzDLgSnrVWgQTXfn9Mqy8ofVbtOOzHxrRIJW3)0))KTy)dvy)xVJ6JO8NLo3RB7oHRmIKPve(dDgEX(m6IUIznoHWjRV1Cu8U1PkuBHye58A3uT41XEKflXbT8B3(0yeHPSrUppNrxFKCG539EXvbZcvxUDHDdUIH51twrvRRqwRY)d444uBfQhbA563FEV1mEf7HX6UudzPvl6E9cd7DsDD8lo4vh8SdRp9Rx8p)

**Comment by mrbuds** [comment]
You can select option "Only if Primary", but the best solution is to load this aura only for classes that needs it.
Trigger works as intended
