### ISSUE TITLE
"Unit Name/Realm" doesn't work if an Npc-name (e.g. "Kin-Tara") has a hyphen in it.

### ISSUE THREAD

**Issue by hambold** [WeakAuras/WeakAuras2#3597]
Hi,

the following refers to "Trigger"=>"Player/Unit Info"=>"Unit Characteristics"=>"Nameplate" but should be true for any trigger that has these fields.

I'd like to add multiple Npc-names in the "Unit Name/Realm" field but it doesn't register names with a hyphen in them, like "Kin-Tara". I assume it's because it interprets the part after the hyphen as a realm-name.
It works if I add my realm manually ("Kin-Tara-ArgentDawn") but that's not a solution since it would break again when playing on a different realm.

One solution would be a way to format unit-names to work on every realm (e.g. "Kin-Tara-*"). 
Or if the option for "Character Type" is checked and set to "Non-player Character" to automatically ignore realms in the "Unit Name/Realm" field.
Alternatively allowing multiple entries in the "NpcId" field would also work since then there would be no need to use the "Unit Name/Realm" field in the first place.

**Comment by InfusOnWoW** [comment]
These can now be escaped with "\". So Kin\-Tara will match it.
