### ISSUE TITLE
[BCC] Add more options to "Instance Difficulty" in Load Tab.

### ISSUE THREAD

**Issue by Kolmarwow** [WeakAuras/WeakAuras2#3599]
**Is your feature request related to a problem? Please describe.**
In the Load tab there is an option called "Instance Difficulty" with 3 different selections: None / Normal / Heroic. In the past the "Heroic" option applied to both Heroic 5 man dungeons and Normal 10/25 man raids, but I assume this was bugfixed at some point to not affect raids anymore since they're technically not heroic. Problem is I preferred how it was before, as I want some of my weakauras active in heroic dungeons & raids but not in normal dungeons.

**Describe the solution you'd like**
Add more options so you can multi-select between: None / Normal 5 man / Normal 10 man / Normal 25 man / Heroic 5 man / Heroic 10 man / Heroic 25 man. The last two (Heroic 10/25 mans) don't exist in TBC but I assume they exist in WotLK, so it would be worth it to get that out of the way. 

**Describe alternatives you've considered**
The alternative is to duplicate the weakaura and have one active with "Instance Difficulty = Heroic" and another with "Instance Size Type = 10/25 Man Raid". Which works just fine, but it's messy when you have to fill your list with "dummy weakauras" solely because of a lack of this option. 

**Additional context**
If you're wondering what kind of weakauras would need something like this, currently I'm using a Demoralizing Shout / Thunder Clap weakaura that could use these options. I like having debuff reminders for heroics dungeons & normal raids but there's no need for them in normal dungeons.

**Comment by mrbuds** [comment]
These options are there for retail version of the game, you are asking options for wotlk, they will be added if/when wotlk will be release.

**Comment by Kolmarwow** [comment]
I'm asking for options for TBC, which has Normal 5 man / Heroic 5 man / Normal 10 man / Normal 25 man. 

If I want my weakaura to be active in Heroic 5 mans & Normal 10/25 Mans but not in Normal 5 mans, then that cannot be done with current settings (as far as I know) unless I create separate duplicate weakauras. I mentioned Heroic 10/25 man as an additional thing since I assumed it would be a good use of time to get that out of the way now that WotLK release is confirmed for late 2022. 

Regardless this is a pretty minor issue so I don't mind waiting to WotLK for this to be added, I can live with duplicate weakauras until then.
