### ISSUE TITLE
Empty string in the Standing dropdown list (Faction Reputation trigger)

### ISSUE THREAD

**Issue by Nightwarden24** [WeakAuras/WeakAuras2#3601]
### Description

**Issue:** empty string in the Standing dropdown list (Faction Reputation trigger).

**Reason:** string FACTION_STANDING_LABEL0 doesn't exist. As a result, function GetText() returns "".

**Possible fix:** change the initial value (start at 1) of loop index that populates the dropdown list.

**Problem:** standingID might be 0. Wowpedia claims it can be 0 (in this case additional fixes are required). Other sources describe possible values from 1. I didn't find hints in FrameXML that standingID can be equal to 0.

### WeakAuras Version

3.7.16-28-g5186602

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

no errors

### Reproduction Steps

 \-

**Comment by InfusOnWoW** [comment]
I did various quick tests, e.g. unknown factions, invalid faction ids and so on. Nothing returned 0, so for now I think assuming that 0 is invalid is good enough.
