### ISSUE TITLE
Sinceready timer conflict on 2 spells

### ISSUE THREAD

**Issue by bronze** [WeakAuras/WeakAuras2#3603]
### Description

Hi

I have two spells (Circle of Healing and Prayer of Mending) with conditions set to glow after 5 seconds sinceready.
However, if i cast one, the other stops glowing for a couple seconds.

Am I missing something here or is this actually a bug?

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Make two spells with sinceready timers.

### Export String

!WA:2!fA16YTrsv4ieHltYMels8gNkqjCTyYUW6AXzt2klSlLhh5yrSLKNzSDwGfREMP1mD8OPh3DpswMRrewm3bX9fkOqCjlx(LEe8tWPurTpa5ripb0DpJSZLFWF0095s3NlFNVwf2Se39QZ)AZ)5UEP2L8l5FW8dqmVvXXbIW7p9dDPmFmZe5TJpJMKCoZiY(7Jy(LDO0ibjzmkvesz1teeAm3G1RERwCSOq)agX3PxcEwRBoSvAu0seMxeUPfpb5Hpjd5PD46wCbIjmCBrIj8qdt5hHrFbJeeGz8lnhlF57m0h7M2QL6izRuz1glVXQMc5glukdTqFEcokQQp34H8uxChCSWwAnzVrBV0I2oBB7SOLJzQ8WDtIq9WmRyuBm3WsBQ7kyuKi8ixBWWsxTSBuz1vhKgNhcgJ8OrPTJTvzqXhrIfywmkAtzCktLGbCCuRguPyZvRSSJfkIee7UuLAovSyYSuDefgkVclCGUwzgrr(B6kqrYRCAR2PY6PbBFAmwMhFalVieNpn8IgMYCZlBbzFSAXy38(Xs0ik7lvSyXgfFL5Vw)uoEvsBIiKHIjTrcCOf3tE8kTVMBwRmCy23k(b4KPS3nfXWLxw2GkVvirGhY0rNQmFOFpzrI4fWOPj5EzlJGtAYPmHzSmqhKDpshUoCQLpeJ4yBbtJD(Wqj4gJ9LnhL6TvTkgh7rJ959v2PUb4gMTrK4LHpV2A4laVb8MYVN(PL0Nr7Mv2hLfhzjEHcfkAfPY4t9q5jllYXILLilkZ1AXBwDdBtzS31YQ6TwX5WmhZGNF08JPASCtXHcQxNSU4fl08oZs8tE(gmcMlkV0n5LVvvNv2WSCvB7nQmQftIBK5isGkoqHX3I4lcp1JqXEYXGLvAvzMR9swvQuBHuI)OfW8nS3923MU)kUYOSfjWWLH8jP87FA2E5ZlJYoan(bEHHQ6ejBKAejUfLLvLNo5IsqfLHZN3QOqRvymkJ3uwJeAJkuY7Loy2He5zyttzE4lFc4KgWhQa4aVWyp5CRpTBSDxscU5Ht2QGdHGHSnAaN2aEod4mNzo4ShColzU6Tt)j2bLS0JAWZdxeUamnCPKzwkxx5gmAadZ5LVITYMxmzkjIC7aCmMr8SdPDRh3C8tSDex)XcJ87bZymMjhe1(wtwitMkJ0OmTvz1ekjoyS6a5tmOjCEd4YWhhohmLwddRWts7chO2Qd9MdoY(lwSSn8jmsMsX(0b7KnxVg1h)Fobuo4r7GXjlQM2ewQkzi8jLTcFmhjuWyz9zUxFAO0y5mSAaunxe7FW5tkjW7j2MhIKfH7K3ptMrlu)tw7BBE(c4gdos3SFkEY5Em3pgx)WmPhXPS4go1t(yAHskxQcp4PXEMlk3(OSlIShodqEVXz4P3kpCouR)UPCbPvpzsPXkyhPqZA1RvbkXKjLYMHAd9MWRuCqEgelgwzVevZTlQ3tKXtUIXAzDLZvBXqj93kFr2n3HWjUs6)8K9Xa7jtvTwTkwBBw3XP(A6r1XhDNk6MzYtL78e3JsR(TG6B4SA1AvE)Xbr0UlZW7MIJ9614d(kZVW1YslLIdLWHBfLxFd7ReP8ESBQqqJRlN(LVkmujo7LVlmsTEsQniyIR6AIw3KWXuTjuF7oHeVDILLOIAhSvuVzlxLifpL(8nZyHDdXKGqX6WNEtnuvZ23eUIIEh(mZ5YLG4iSBdRQvSDuY(SAnVS(3RzQgUHxxr6(0CNFX))SPW72e20WCFkTDbRUk4Y6q1CMpRLORu(QwhdaKVJLeIkcRb1G6JUY(VAf8MCVAUUW6gmsSI3ehMC(j8dki1njCKSz7hc3UiSXLMZYle7TZMZstM9nFdx9g(lDD4Sx(e97GyeLT9jXE02UiHvhuukU4YWzlc)9bmfVGdPngEqPRL5Vwb8EkbmVquCaw(VeGh0SFI89qmt0t9e78xDEvTgE7qWUWbZcV1JtbcF5MWxzcx3ZPP7otnnxh8vH3wwO(AsMOmUnyBOztabUA6oVKPAWu)5bfH0AyjdDCaCmju4h5EVk0kecAQ4JK8mJ8j87MgR5Awaf3diAAg4UH5Tovpr2AESw3tj50pJKDYjHGOdop0UaelLrLSiqIM1a2fyaheq69GofGUYSDpON089HVUUDcFd4BcFRcW3g(oW9Ac9HVlC)zGVxb4DGV)7dhmzUb(bWpVa8JGFm8tUa8tla)SmN)HHWVie(LfHbfHF1uWVoe(nkem8Bpg5c)o43)m4v4DH)qbfBQQJmme(ZfpgW1GUw5fKTjfyrbYw3qIZ6TvN7Y31TJO6TG)si8hxxHzLqj4VMdJG)wgcsIf(hWdYXlzWINbNa)tncb(xW)wI7H)Koxk15)EN)3p

**Comment by InfusOnWoW** [comment]
I cannot reproduce that issue, which might be due to the incomplete reproduction steps information. Or because you have some other addon interfering.

What I tested was:
1) Import your group
2) Put both spells on cd, wait for them to get be ready for 5s, so that both glow.
3) Cast Circle of Healing
=> Prayer of Mending icon stays, and glows
4) Wait until Circle is ready for >= 5s
5) Cast Prayer of Mending
=> Circle of Healing stays, and glows

**Comment by bronze** [comment]
Yea it is really unstable. Just turned everything off and casting heal would turn the flow off. 
Cast Circle then Heal and PoM didnt lose the glow. 
Circle back, cast Holy Word: Serenity and both lost the glow.
