### ISSUE TITLE
Miscellaneous (Small UI issues)

### ISSUE THREAD

**Issue by Nightwarden24** [WeakAuras/WeakAuras2#3604]
### Description

The following are small issues mostly related to UI:

1.  Preview animation playback speed is very high (~ x3) for any aura that has a generic trigger with an event. It looks weird. That behavior remains until an option is specified or a hide time is set. 
To reproduce: create icon with swipe, progress bar or progress texture → select any generic trigger with an event (for example, combat log). 
2. Warnings about potential incompatibility of auras for Classic and Retail no longer exist ([Link](https://github.com/WeakAuras/WeakAuras2/blob/3.7.16/WeakAuras/Transmission.lua#L1561)). 
It would be nice to notify users about auras created with BCC. Because there is also potential incompatibility between BCC and Classic, BCC and Retail.
3. Localization of [this](https://github.com/WeakAuras/WeakAuras2/blob/3eb5387/WeakAurasOptions/AuthorOptions.lua#L1771) string is missing. As a result, localization of an option header is broken when switching the option from a noninteractive type to an interactive one.
![WowT_VE9de99bc3](https://user-images.githubusercontent.com/45747886/166115539-0784794b-ea1b-4ac4-8751-e1fa1ef4a841.gif)
4. Forgot to change toggle button text to "Start Now" in [this](https://github.com/WeakAuras/WeakAuras2/blob/3eb5387/WeakAuras/Profiling.lua#L681) and [this](https://github.com/WeakAuras/WeakAuras2/blob/3eb5387/WeakAuras/Profiling.lua#L804) case when profiling was improved
5. Conflict in value names for [this](https://github.com/WeakAuras/WeakAuras2/blob/3eb5387/WeakAuras/Types.lua#L1208) type when translating. Please, rename "In Group".
For example, in Russian "In Party" and "In Group" will be translated the same ("В группе"). Then values of the Source Affiliation option (Combat Log trigger) look like this:
![1](https://user-images.githubusercontent.com/45747886/166117464-73bb8d37-eece-4a02-b96e-6c0b8f2923ee.PNG)

### WeakAuras Version

3.7.16-39-g3eb5387

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

 \- 

### Reproduction Steps

 \-

**Comment by InfusOnWoW** [comment]
Should all be fixed now.
