### ISSUE TITLE
Shift+Click multiselection of root auras

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#3607]
### Description

Selection of multiple auras was disabled in "root", it seems it's possible now, but is not working correctly as shown in this example:

![image](https://i.imgur.com/JGV23RN.gif)

### WeakAuras Version

3.7.16-54-g78b4954

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

no

### Reproduction Steps

shift click between 2 auras (no folder in between) that are not in any folder (it used to not be possible)

**Comment by InfusOnWoW** [comment]
I can't reproduce that, it works fine for me.

**Comment by mrbuds** [comment]
Issue happen only after installing with "Ready for Install", and select with the new aura created, it seems it count the green aura on top in the selection

**Comment by mrbuds** [comment]
https://i.imgur.com/DfLNa8n.gif

**Comment by InfusOnWoW** [comment]
So that's probably PickDisplayMultipleShift, at line 1254, which considers the about to install buttons. I guess adding a check for button.type == "WeakAurasDisplayButton" would work.
