### ISSUE TITLE
WeakAuras.GetMHTenchInfo() with builtin weapon enchanted trigger can not return right result when change zone.

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3612]
### Description

The builtin weapon enchanted trigger can not return right result when player change zone sometimes , it is not stable. Entering or leaving instance for example.

### WeakAuras Version

3.7.16-54-g5dee01b

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1 . Create a builtin weapon enchanted trigger .
2.  Create custom text %c:
    `function()
    if  aura_env.state and aura_env.state.enchanted then 
        local _, _, mh_name, _, _, _, mh_EnchantID = WeakAuras.GetMHTenchInfo()
        if mh_EnchantID or mh_name then
            print(mh_name)
            --do stuff
        end    
    end
end`
3. It will print the right result `mh_name` , but when player change zone , leaving or entering instance for example , it will return `Unknow` sometimes.

### Screenshots

![WowClassic_G3lmGunXcR](https://user-images.githubusercontent.com/46548538/167245374-29961f92-fd55-40c6-ab4b-42a958fcd0e1.png)
![WowClassic_LeKE4rkXaB](https://user-images.githubusercontent.com/46548538/167245378-0f2041be-30ad-4ff1-8a31-3ff096d3c574.png)
![WowClassic_YtTlQpOlF7](https://user-images.githubusercontent.com/46548538/167245380-42f745c4-b6a0-4275-b0e0-49754a8984a8.png)

**Comment by mrbuds** [comment]
It's an internal function not meant to be use by custom code, you 'r on you own if you don't use information provided by trigger
