### ISSUE TITLE
The built in casting trigger return the destName frequently when caster changes it's target.

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#3613]
### Description

I dont know if it is a bug or not , but the built in casting trigger return the destName frequently when caster changes it's target.

### WeakAuras Version

3.7.16-54-g5dee01b

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create a built in casting trigger, player for example . 
2. Add sub element %1.destName .
3. Cast a spell ,during the casting progress , select other different target , the destName will be changed along with it.

### Screenshots
![World_Of_Warcraft_2022 02 18_-_00 01 21 02_00_05_55-00_06_02](https://user-images.githubusercontent.com/46548538/167245912-bea1498e-35ad-4420-96c3-cf22538e0e4f.gif)

The destName is on the topleft of casting bar.

**Comment by mrbuds** [comment]
That's intended
