### ISSUE TITLE
[Alpha] Error "WeakAurasOptions\CommonOptions.lua"

### ISSUE THREAD

**Issue by Luckyone961** [WeakAuras/WeakAuras2#3614]
### Description

Getting the following error while editing the display tab for multiple auras in a nested group at the same time.
(Only WeakAuras + BugSack enabled for testing)

### WeakAuras Version

WeakAuras 3.7.16-54-g5dee01b

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```Lua
3x WeakAurasOptions\CommonOptions.lua:705: attempt to concatenate local 'display' (a table value)
[string "@WeakAurasOptions\CommonOptions.lua"]:705: in function `member'
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:512: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:501>
[string "=[C]"]: ?
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasTwoColumnDropDown.lua"]:137: in function <...-Widgets\AceGUIWidget-WeakAurasTwoColumnDropDown.lua:136>
[string "=[C]"]: ?
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@WeakAuras\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-DropDown.lua"]:362: in function <...as\Libs\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:360>
```

### Reproduction Steps

1. Select a group with at least 2 icons
2. Go to Display - Text - Anchors
3. Enter a value for X Offset or Y Offset
4. Hit Enter

### Screenshots

https://i.imgur.com/PER3GCA.jpeg

### Export String

!WA:2!TR5c0XX1zDCpATQdRd1wRTuKvLtw7qusCQvSEB5MuyxzPyzllj2vYoXeIMz3z0oJ1OzMmZSsEDsBs2eQvjPy6wGCkeAlQqcpkqQOopCAcfducn84tBEnKYt1cfkpsRj0deAP89DVZS7QN2XThohsB8jAN5o35(8)VVVV79ochjIJvK2AURMBPZD3r77othYkk7PLurMmICe5zAlEgBZPN9adLO)Jn0GJeBGfszAlRyhxk9eY2MwwBoUU2jpPKTC0rmn1D1SkkL1v10EilxntdNWfW3pRv)PnnQVQAwF(m2AYJKZszNj2)SJNvxVhn706kIjCSKsReQ1S26wBx111YzF34noTugZM1mVr9SPNiNPHscZmzvSLsZk4ot44kz7go14AgAoQHJJ)4goVRTwMmk2on0KT)LFGzLvsLD8XPA1(a9oWW9n6aXDXBsiL1wQ18owk669l7eEbNSPuMsXWnjMBTtm3y9el5iJLCKyjgP0Jg2wbFuIKd37adKWqAsfNWjypi1buK0DvJNfBfPS0LYPyxiRHFti8CPn1ZoPrswNmLTKSwwNh4YZN1rzaTj1CvtiPRLXivp9o4i9MiUSItARnFyjzLOPYfDa)EVn2FPctywSXKqjdB01o3qJpUJI7b(rgyDHxh(FX1nLK7lLRKo2OQlXKzXPKWXX(y66GMdNiTUKJdDvChTtQqxuqYqBsjAiTt4D235uKCus6ARyKXvDdqTXnWAUOmoqr5ymAyZ2rbNmLDYtzLguH2JpPKMrFqB4laTdDaDcDH)UPLMsXu(IMEm1nTpyOqHgo0EAUJZRz4QyBiPFeSSXAjJnVjPOwqYo9aSMYduxcN0yFk0CC5hVeeeecLING6S8F7voJIvnjVZSs2kr7dfyrpQQMRYS2SbmQ5Eo5C4eNwAMU0)TsIdgvh3X02fAV1SAYZDSohUf1UvpQr8bt5yM1oTskTjTWNNc77JRLj8CJBJZ(4iLKRu1lGjIZogU9HItt7ujIT)(hn5CsgPrqyytS)bnDoEnXNU(bsOtZ7BCwxZ0tX711liER7ut2QgMkp6UrCYk6TqTX8iaYvofi65OAYUQB888cVpQvq9Quj7jrV9oybhf9X9Rr)HQ(nWkm05Po3bYLIWpPu6kF(fkvp2APNWr1AZbjSFnhxIYuTIeKuYSPWPOXZMrr1AlbjEinzdLCrtQA6wrQdJVTPop1ZvkrBLjvpFPsZLXkQw1fKYTOA64QJLfcmtOu(9sQQnLAXs5YK1aQVuPInjtCcqro6ru0mCkNt0MKHSkoW5Y0TcZskwnUbP50mW3Il5dBFcF(5hEZRJ9Frs)fMP5z1W8NKnTlKISc1)(lSNwJjV7uXvIbAyXLf7KtoIYjCRcUbbyqOPIPrRFYMtBKCAnlfrRnxolJAjJTXuzz)CUG8rcv14ufjc1ChnbrMzRlG2dyZ4JL2eTDOweBKPvvCWXYPhY4CoSFIHM)McL4yEhJWATX1spgz1rDokjxUryvyl2hiwIdJ26qcSUZtpIBgShYcGkupSn4QqZe2zuCZhW3rAb2oCLOCZyid9CIqdW7YgFZbrnMiCfnuFiH(TZAWS3LWvBsfzOXgS2o8XN)EHNcEs8Vp(8NcE25Fq4PJo)9dFg827frJjtPzOCyExzwQtmG50koUZsTgExdYwGSfZSN2qQw6UZUBRlyhHPbLgtqAXjIJovmH7kslfZOGMc1sZFrwXftFAPCoKXu24GiBCGEqM0YIuY9qJMIWvbrHg3N11cFy45GNaoZ83385H5GZapl(VNdotu43ft8EN)bNFg4SycFi8FB3AB94pHHIyZm2koorVUKKlJRNngEf7REHx7ZvFvt8jWFF5cmNj04fnwHIavAa2zmt0SPeAzyNV)BgQnbltZXfiJPQjRa3d8(HtnBq7EidXI01i0G2v1mYOwKjigkOuUPB22VKJ0wrBeMsguTlSysQOVkH)qXeSIjsRSri)sqLMLHTaBTat(qd2IC11IgPfHD0ukEJd(GWPPU3CYAohpRbtp2QKroRAKyxpc3P3HnLv(uRd2xMZpHIIvmsR6MGKzIWrHMqNYosUKUtr123eyhWUoyDqTfr)BKNcYaTH84(MXgJCyfQO)nMmQvW3OkYlbUd8dpzSP0C0qZCIbVTcIBqmO2cuHZs6vkMr3C6(SvUZSkgPZn863tZT2buRnMb6bNJGr8xMNgX8usSiiI1dAuYqzwkbUVPANJU(24gsekKj4LihCHyp7wR8zjz(Xyv(iQOPxdusfkoDRk75dGLUtnSYpo312mBZ6kDrdjJX(d341ywJreO)Dcfk98DEnwwBBfYn)c4EwGLCfUjS2clfcWiJIPz(xIhdV988sq7ekCNo3xrUtNGU65yp)4OowB8C4ukZCRczYl(GdnyVwrxTg9KMYJrZ8I8HBkhwr4Tcwf4pEfAwwAPlnywWVSmCNT3tyrSis(wx)Qvn(o6hZvfZQksXc(1IJQKC5zSILkv2e8qJoYa9pyV8uNgNboQTKv(J6FbVphOUS2CfT6GXZkRJGzE)mYtSCWlLRAkcKTxCrDFbRDSA9mSVNwJqMqPuv0YO62n8UNzRmA3sXnLKRRog9eDlzT2wf2dcVOHeDLejg6wgTxkUpMnaYzGyCBtDwSG5dCQiAFsmUpmO4QS5rs2k9yy30FzgpMsbLUyDa3ytWxSAO5MQwCdI2ynqUVOCnRSggeDAm8ZC0TluYq0egOTuXcwtz5hJk(u7X5b1txxSIIFun14ObjwBB2YVnz8bAH1Ioa0F(apQIqMD1uc0lt6j6eIek)us2AuOoXjZwjMsspRsiYUPbA1BFnbVUyElBYWmguBeuf2C7nx5ClMbMMd(68N2AZvARPo4RJ9wYUfMX)L(GivVttRi3e86rAf(xH7c(AnG5aopehSHwXaRpcloykQymKymC4uK6vXn(4yq(WExEOZln)W)b8nGncxo03C63MzFt2L2XBp5XipgJe4WFu4iwryE74dhO93eeJHRTWsvkukhLjX2BI2AU7M3t8tAAojf8DBWPuHFu)ypbjRTgmysumgiin(jlchQ6ettwaILOmmchmm8gIW7ax3eA1yIC73picvYVaTci(A(2YZdQ1zvpU8gtBf)ff2lfbrV22M2oIWpio80KTS5ymtG5XlCi7(QWM60ty9Qjy3z9E6NwKaQtuU9yYYyzC7hwBIKPrLlgQxM4mfp1MV9Ku2DU9GrHMnZKXtOAvyZHNPz44nUoycq3tyD8UWKbHVbO6XeSG7uL3EOA2)18BhEcVdpHnWsRMbPitQLiOKUsuWZWd0qQ2AVLo6QvkgfmQi4EHPvH7hYcVpriNk6E)EyXFG(zPqSy(CVBraFtEyvSyjWa1G7dYdU4RnLkgae8XHpb8lXCIcZYCBcFsv4xg9tEm0pj8Rmo8yc4V)gWVkZAc8Rjc)6OtUhn0RaFQa)zWVj8zeGFB4XHpDTWCcWVdVN)BjcNje8KQWtecEQAGNgDYaNvaEg09b8zXg7ZI11ZHbe95Up43taohE3Vp8ha)HOfB4Zd)rHGNNxm)XWxaEfb4praMxe(Zba(tH)mOiM7xuaEjEJ6L3o8ccWRgAMgW)ScUMCcCn1ov7obV2ZMFKHgor)3YbgzfAhVOWk0oEHCu7GAaudbBpf9e2i1PO(d2kEfHf5KX38FiWJz8e(luHxJmucFr4VKmT8xjc)1mBm)nIWFBvWFxzlGWcC7EBW3UNVTOVm7V)9QWxHDX)a7V)tS)(pQcFv208xkWQfcfEcHe9eQIHiKDccVxMTcI7j(hTruBzRbl3grq(qO8)uf(2XG)lIAj6()re(VHVzzixg(wCY)ndr2mWLZGgv6CWBBGSPSUUdnCgou7jiOczAanUr2srBA)BWRhc(Am7MKLTYMhH)DYu3Ba)ZIGTyzgJk3LHxuxCX81YGle485lpHltLiK7Mh6(Y4jIHqmHWjIyi0IiOkakghsefINTSN926E2ldpRaSWXQvgSiQ6rdTeW6XewmyHq0Yale2qW6jySvay9QHUKaRx4ccwi6DwbeSErbpHWlfGi1)YQjpHlp0ffdtVn1Er(Hi4CuNGrk1UusHTUfUZC1kOg1kOgmRBeAUUnkwb68ojY5lTyYHZmFLaMHdpF1f7VNSrJATLRn3vG2KRhjKYMKYO8(Ox3udCBwjN64hXMP5r4av)ew8TwUxWBNqgKD(2XyqaZnxjpg7ltaYYb4v07oJgVi9QpZUVO9kvxjps1vHFOgBfxNyK25UGARLUAJPXrWGGceAqGbjOg3Lve4rM)0ZFFWZHRX9(HpnUg3h3QbKdEC2cHXuzQfCPW09Z)q0sszX65hNJiIFFqg0ruwo(wiG4j3L2pfuaflpS1wGhgxr9NLTI6NokUs6NdRNpQiCf76Y2AB1x1BufC6l7Qo(CytU0QzFV3mJrjg)NexMzDSCSCxFSjdcr3hdrNkW33ZhEzU)qK7fR0xw8yJoYqFh5o7SlZDwamWvWvYdEcBsCv8E4hS8vlEnvsc1v9sCHiUAUqwpOs0hrbO02xbIcDMMC9fjJyOCfT8YDaGACukFkXYA7XyIEuCtuGV2VV5oU(ENo5Ost6MUh4nujKz19dntnPyXaMaJOKwj7jcXVpM)V3sOGxJ)8CHG3uG)O4HIKtOa7s2wwY3bewX22g4P3xwJ0vLIVqsHiNqGVkf6jORIhTudIEL3uOalYwQOIZ2ffQnsA)22qr)9YWWrNTpY0TSmJ(0ctwpqhrLbV10vfh12uDl25uJEc1Gmhk)PkeHcpHAfltBOoMOdIajSaHrFMbzkMZOw6OLUBHbue6We8pSNqDlMuqYYt4kc4Jg3LNWw8e2kduwvkjWpwaK47hBzqYJjSu)sEc1)DKJPZUehtibYqKTScisz8yPSrNxJy1IxT4YcXcv9xiVeeCSuVeKtaCgpWpWj6ox8t0ESoB)qALS267pazIaFbvWl8yNqocbkeLiFbQRHj)zQXtOHq09EcngYty7LGbpHRKabpHFivec8eI6jSduF7jC14)VZQWsXt4DHVXvfQsDovO0lDnEcnXQfU82t4AXqMUo1aSpiwsbvsulW00x4L2uHM(oQqttYZU7OZw7YFPmwTGM0FCuJCM5pf6RipAE)zqVdplE9PJcZHAMNeFiTJQLDDC3(SaJkqyGK9emqcEs(UypimLCjxibyqd1x138gwcdmfF3k9v)yJ(Ba1wG2HzjxDZm2(hLNNWnWcqS(IJfB0eXgl2Wdpq)9UF4UADpnVxy7Z2d7fIoGzgSTX2zcPuoM2PODSue(OQutKVHfSJay0YBQmV8zBm(SLFi2HoD9v9YFYvCfBLCBDq)ilrAe9CTyAeP0lTilVexYghGRCPsRqKLV6BLLg10MeRrKbXxl08vkwHdUQ5o4U4I0tq)1QGHrSnGH9J2R6Yr7vx5LEGSnA2RV5slDih1jpK1b6EiYME5i98j7fToO7Gc6JfMxjYUKnHleHZz11IWzSnb5vq4C7cVvjC7wARR26gx6IV7EY117(chZyG)Rod4D2orpgFJ2WXWn10kTORTbFa4uStlIF2tYjYAOWDYnZc8T)pyNvyG8dQwO0PuG0vlWVOiJI5Hj(HHt)aBJb)FeMzaIXjM)HNRIZoKb7HHFgvRiLkQYhycc(nggEerwyM7Ot4J5jSpyg6iiWsMbBHE7eRTLvN1wH9GOUvAvuIRcBHJxlISiScPlKtyStFhA44toOUU7ELjEGha5k4r8hN4j)aijEkyxaj)lON2VBTQOlffUNWExBHTNq3(AzsfX1VEcVhpHBAz62xAIvs3Mp4SXljA9eEVRHgflLVVgfV4IsGIdwRLaDWo1p4XoKYishXCnfO)yFVHa9lNFLeOjyF5dxKQtSi((Qt)1xCrPqXbS1sH2ZX74opyM(C0Tp2AQqv()Nk06j1PVIA56ts1skSabAb(h1WYeOSpINscuswZvNNE9MLvN0FOeE7N88s5CgwPiOxnjkoOTAsuruIAVNS9OlNU7dD0JVMs00)FJeDTpTaSUWEax8HvyZPAT9oABV7LToUo5Ieu7qQWtFzxrRKiIeE0EVu0)B3C0E6P3KjjrgjfrrONq7IWdhN(UY4AqpH2WvP2QiFpC6W)i6w5JEt8TVsp1vr6f6TK9rAwOS6J2K(WR6jG)wrN4FY3DD4ws2vx7FQU6jdDWnR8g5xHiovfBK)6w8zwtgs4BK)(ceZxWZL6ItTY)u(OT1W)yCNwT0rt5VLhKI9U4FRD0oLqwmFF0gECzlmiBFlASbRRgEeu28m0hN28peCw4PGZeD(Fc4PMppTn9SnS)Py7icDKypqdj6ORUBRD)pzUgkhbbYcpKi8lW31KttL)pxK2ySazE(NM(C0qBWl(ByJ1e)iCwImB)ZUZB6MPn2N)DIg1C8OUQkrhXM(Yfqe6NpsRmJ47J99Y9Hy91hHFID7Oj4JrXzq17QUrLFpsGgR2zETQOeoMTyuAfpVRLCgSFxe2oI1jDps7Nu)63R6ffSDS3YWM)oRV4ynIm1lDR)V)

**Comment by mrbuds** [comment]
I can replicate, issue is not with X/Y Offset but with the 2 columns dropdown widget
To Frame=Center  => OK
To Frame=Edge+Bottom => KO
