### ISSUE TITLE
dynamic group with progress bars (health) does not get sorted

### ISSUE THREAD

**Issue by Tyralon** [WeakAuras/WeakAuras2#3615]
### Description

Expected:
List of progress bars with raid members' health sorted based on current health.

Result:
List of progress bars with raid members' health not sorted based on any conceivable pattern.

tried with Ascending, Descending and Hybrid sorting options.

### WeakAuras Version

3.7.16 bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

no errors are appearing with /console scriptErrors 1

### Reproduction Steps

use the WA in a raid

### Last Good Version

first time I tried this WA

### Screenshots

![WoWScrnShot_050822_124246](https://user-images.githubusercontent.com/13432244/167294077-3aa566db-04c2-47b2-86e0-92f9c9db405e.jpg)
![WoWScrnShot_050822_124232 (2)](https://user-images.githubusercontent.com/13432244/167294078-c330bfe4-aeb0-4376-be0e-d82b261f0de9.jpg)

the first is descending and the second is ascending

### Export String

!WA:2!fAv3YTTXvyXbtBQrtDTyCuIsDTv1mYJDt9FYXo300jeuKM0vMKbesYjJ7qTa7sITceaExa9x)j1SUUQP)Cb70xaEDVIx1R1tWz00Na9iONGE2DHKC8KmLxqS7IZUNZ3589DwuA9Ys)7F7p(237HLhwMwMEWYodej74Ss7nADSFIGYeoKGTOIK00l5eX3FFIGUGxssugpvSB7(9LSSgF6h9v)NzWFI9oDHDSUPAHtKjISg75l4upIFeBUXPrK9yIfA0jCs)8OOQCrqeBZrOp7Mscywcsqgpjw(qxzgrKz73NhZLH2o4Jm7rzc(GbmH8dUUOy4RMqz(5977Txkt0O2QDQV2Qoz4exsUGS8izklkQjvAFSm3NTnloRlAnF3P9QwPRxVUEvC9CYXd33eANzwhbdnZTBNARUQREf)gmsuwOBmzitApopUieSNgKeLpm2GaFbHYZLV8ThLlzRYhYXDqI4dI9RwRLxnx3i1AVRaXNAZLMGo0LnqbABNOecTUFgjcD3CUdZX0STdcHG5Gp02niIiLQros((m1GXKy(qIkJ9q4hu)qgrY6MjyXdYcFl4YoXjXSJOyEqzrpvwrizbjXu5iLPQCgCpNHeECD4U4gG7bld3h(i85fFZvoYVGiunjkr8yllRow392pySKf1VtcpoBzV2DeM4Hf6k1jdxzaIfRJi5zHjI2P6ARTVHzfoX8SgDalD2UppNiyluhzflSripJnrOZkQG8q6EysNhGCZ80ID1ftbFhhfbdzaYawmLhpymreSQg(VCULZ50PvP3NiB8zBj3UVpc8(8b2hhQjKDXD(KekBm50nFmAawvIZQJKWeHVBLvAUw30lH1XkXby83HjwdzkHhAIadz)ct7lqcbM2jzeRjzjbBJzzmW)EDE)f50jn6Sa(QGTyIrdu6aeol6UYy14n40SWV)je9HxxDkQ363TQBTATobtPmrmjADZXnyQXRnJrNAvaIojsUkNo1mTohPvtnNNUMalvSltrRuPswtu1FUPqmLh3pryiq2OimtpQu5Gp4G7mbRGIT0H47EOESbVpTe8DlbVvj4lGLosVU7P7lD2V2Cv21PYAETD4OpdHlDXRdZEWSWpcUcugEhKCn)em32lulRcNgKlZsgQPP(yDilxQKq9uIZnH3dE)tuZ4Xbr5uwhwMm8yTGG3NhyqWjMtQxcYZjyfCXFXNaZ7iiCQV5nLVl8JHR6geYc2chDnBJuxMo7ATA61Rt7nQ52BToRuXRgmNnSGD6SQ(rBZ8mkDfI(3ZmrbNEbNkdSG1ha3rP)Etn0d()RQg5tkQnwQAdYKrClukOxpN)5LGB845GlFe2Rqjdv6GyAXcyfKzw4G3l9NKX2nRN(ptLTxAVm(qwVublGR4rwJpZKfxc7QRNjdj0KDoNKCSz1tL2qq67Oxb1Xjk6sGMx4ubNEIXz8Dzg(8loYW)(CtOx6q97)1yTL3FpyPjAwgZdx0Pv7w1GllqmOSzI2WZtRJlqrCw6LQl47VWNLtOkr2cEEMdDBeq4TkBMw(1arHFVYmfXXtlIJJ02SdQg2qqshTrXGJoZlkTNtlSJzro51KrtA2QfYmwTwDV0R(TLHnZkLo)3GbMbUk7ON7rvlS5tV532bw00RxwOGjdtIO791aAbWSo4YW)Yc2BXLIH91fp43abWVf(DWV)fWxwc(dWsWlGriR7pcV0qy)tWRGdUYmWxb)v4pVj8pMAWNBZh1Wd(BWFh(NZd)LVjKexmaUhQO4dcZUgCZ(Jv6Yyujj2e(PQBLGBP(xRTdsg6tYcHFME9BR()ynX2bVIJQ0tlxzLvm9yPkscJYOpHSBi026KZP6NXm1358MMZXMlFQqDFpQMGpgX7p3ESwKk5uMRbwnSD2pjzyPPA33qh9FIqbUCbB0PFBduF6ZFu7huRD1Fz)hTUrd6zSj9gnvDK7J3R9SQeKohpWHiE2AnV15ZUvxDdq92cHo4vafUJtPSy3w1wh)aGDuYe6fWVkinKybEWA49eWfmnCp72vlbpwDtclu3VPBsUiGDLzMMi4yllDdVjnA728lA3YRYQWZSHFLn82yBiB4I2Wp0U82)3N()(

**Comment by InfusOnWoW** [comment]
That's because those sort by the expiration time, not by the health value.

You want to use a custom sort, something like WeakAuras.SortAscending({"region", "state", "value"})

Feel free to ask follow-up questions in our discord help channels.

**Comment by Tyralon** [comment]
Thank you, this resolved the issue. I asked in the discord but was directed to file a ticket here.
