### ISSUE TITLE
War Mode Active Load Condition not loading/unloading when changing War Mode status in Stormwind/Orgrimmar

### ISSUE THREAD

**Issue by glassleo** [WeakAuras/WeakAuras2#3618]
### Description

The load condition "War Mode Active" does not seem to load/unload whenever you enable or disable War Mode in Orgrimmar or Stormwind.

Edit: I suspect WA needs to additionally check the event ``PLAYER_FLAGS_CHANGED`` since ``WAR_MODE_STATUS_UPDATE`` does not always fire.

### WeakAuras Version

WeakAuras 3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No Lua errors.

### Reproduction Steps

1. Create an aura with trigger "always active" and set it to load on "War Mode Active" or "Not War Mode Active"
2. Go to Orgrimmar or Stormwind
3. Toggle War Mode on or off and notice that nothing happens

### Last Good Version

I don't think it has ever worked properly

### Export String

!WA:2!1rvWUTTrqulOdjGiOiwOWiOnhiAb6LceGudyb042crvkehOA7qsh7EsAj3HIBZYDxS7sjlFlc9qp7FGcOZ9K(eYHEMqOFb(tW9hOZkk7wuKOtZSCM3(M3(g1AqNYo0o0FBFTSYYzcqFYzjdp64WLSmPiwwPZGNUJ(YtYZnGTL6RPmJItMNaxAhLl1Le7i1ilRegrNliLSSr2cnykKC681Mccvo7NBA(P7SIiYkK6tLmHnTF4XjHrRZKyLYzI4zmfmw5)XXVjRL6XzvgRS0vXzkkXcrWuqyF)DifsNafbo6pEHvZMmb0Mp5R0Bd)Za7Cfeujy2BQmWicFgzUXQRGX3yQs3avCvEo7YvJ63lozuCsVOKMstnsD6pjPW46hTSVuqzwMuyUVVt1a2xu8PHdhUWOao)iQXt15FB(LaH3aqNu3yc6iu0aJ3cxnosnEjfsX7pbzP(LHdpDWzdVUsSL9EQDjzw2uiPj3H1FSJ6Z)GQwtqKt8O3IsoOfe(Bq1aj9KBFlaQEijZSreCmkwmtQPNRjQfNVnazIHyR0OexeKlfw1JhOzx5)6kcfpK4NKSeh9iyItf(S9Q3DnMMsYE7e0njOPfaBsH9DrzsUu)Q24VaUKqFZk3WoJOlDkrQLWrTBVOYkUL5fLXjgZE177f4ixta7kWfSWrIym5fBDwx04SAFnrWkDtH4GiJLOTdEpqmqSvdIj2IhuVBGqkG1u3WGvnY5b0ga9iuZcxPo5U(WGsctmO(fyd1hw)D1FF9puFyAotWmf))JxXencmIN3YS7DdEl1BeehIbw8brpF7YteHRkiTx9FESuhKuWm(UY8XDMko1xk4Z9tb)PmdlLd(Zy2c)ZjAF3BTpii4H0VPIrxjFE3x310nUF3xP(07C)ou)rMztvfQV8JVoP0qgZzfAFBZA5an6eDSonUFuy4X3qQW1mC(YoNrTfb9W0GRKYYw6Fb3az5ZdggoizPvMnTXu9KwJV4lyuvN7PBcyS(9qvFncgEhNOA0Ov5UldFFqBu7Ozo8FN25SXpEq936v3ZlavDRxkkS5SjEAMWDjqXDQ3r4hEs7F)Vx14e6VXI1QvR2lXvqGUHY)6JwCNSuCTb45B(NN6h2XKU)Z6(SNFqNP)1f)d

**Comment by glassleo** [comment]
Actually it might be a Blizzard bug since ``WAR_MODE_STATUS_UPDATE`` does not seem to trigger properly.

**Comment by glassleo** [comment]
If anyone needs a workaround until this is "fixed" you can use the following custom trigger in the mean time:

- Trigger: Custom
- Event Type: Status
- Check On: Event(s): ``WAR_MODE_STATUS_UPDATE,PLAYER_FLAGS_CHANGED``

Custom Trigger:
```lua
function()
    return C_PvP.IsWarModeDesired()
end
```

**Comment by InfusOnWoW** [comment]
This is intended behaviour. You aren't in war mode while in Stormwind/Orgrimmar

**Comment by glassleo** [comment]
> This is intended behaviour.

It shouldn't be. That is inconsistent with how the game works in practise as well as Blizzard's UI.

> You aren't in war mode while in Stormwind/Orgrimmar

Depends on how you define "in war mode". Your War Mode abilities are enabled/disabled in SW/Org depending on your opt in status (and you can absolutely use them on opposite faction players.)

Also if you open WA options through /wa it does load/unload depending on your War Mode status in Orgrimmar/Stormwind. The behaviour is inconsistent.
