### ISSUE TITLE
Problem with %replacements for state variables

### ISSUE THREAD

**Issue by Hamsda** [WeakAuras/WeakAuras2#362]
What steps will reproduce the problem?
Add a new variable to aura_env.state and try to display it with a %replacement in the display tab.

What is the expected output? What do you see instead?
The %replacement should be replaced when the aura is displayed.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes, the problem still persists.

What version of WeakAuras are you using?
2.5.6-25-ge708889

Was it working in a previous version? If yes, which was the last good one?
It's been a long time since I tried to use this, so I am unsure if it has worked in previous versions.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
There are no errors, just weird behaviour.

Please provide any additional information below.
The weird behaviour is that the aura actually replaces the output in the preview window while the options are open (where it didn't know about .state variables a few versions ago to my knowledge). But once I close the options, my variable e.g. %asd just shows "sd".

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.
The aura just creates a random number from 1-100 in the animation code and stores it in aura_env.state.asd. The %replacement in the display tab behaves as described for me.

```  HERE ```
dKJbeaGAsQ06bKSlLW2ejZwQUjjvDBr5ZIQDkWEP2nP2Vk)uq1Wuv(nQEmjgQGKbd1WHWbfeDkbPoMsDoLOfcuwkjLAXaPLl0djPONsSmvXZLY4aIPkPjdPPJCEaonkpJKkUUeBeqmkbHnRQA7q0hbKAwQstJK8DGQlR4BkjJwegVGYLiPWTauxtj19iPKvksDyq)veT3UAjZcQfuxT8Z1KWaQXbpQSGYAQBrRqmKJfOgGfuwdrhcOoHrwudyd1cuHyiNAKLNpr1Zrhha8(ZsIHLNGmqsTALQuRxV8j1YNvQtQp)dSkqSai8))2qoyN6ZcuZYGeJRD1sgKPD1stb2NWCW2cbaXyrP0iEMf0sesmU2Y2stb2haoyBjmh8zb2rKa6Gplk8opgshSTaWbFwu4DEemhSTOW78iq7GTffENhRaqmwuknINzrH35rGu0kw(lAfIX1HarKNhNw79WX97HZ3Vhg097HH73dhFEpC(Z7Hb959WWNqFPp8Hp8Hz)hgwIWKJg5HHA0ddlryYrJCrJG0CykXOV0h(Wh(Wh(Wh(WWseMC0ix0iinlGn0dRwh(WzqkXIiuJYZcX(7l0x6dF4dF4rJEPp8Hp8HJdvI6dh3VhoF)Eyq3VhgUV0Jg9sFPV0wICcsJd(SOW78OA7GTLsBsQW78ObZKjlmulbd4waNHsjmqwRcKLltTE1(tLQhvlt5FGvTYcfz55t0vleaeJLgbPsZsPnjHDWHaAuSmgmlL2KSOzKbZsPnjHG24rqvphDmywgKJMSOMCnkJyCDZslbh8W1wAj4GhUoKked5yPOhKJMSale3KfDjRgz55tS5GTL20)dfNPjl1WdLfMMrjBemsdQd2w6CiQRwiyF00JRwYkDI5QjtwiyF0KRwYkDI5Qjtwqz))mLsNa4QLSsNyUAYKLiuzC1swPtmxnzYsK3hxTKv6eZvtMSGajcc2hn5QLSsNyUAYKfMopYliC1swPtmxnzYYpuHyCTRwYkDI5QjtMSeNCgxxbGySqtyKjlnlplwVifWpRboFw9bciGS0cshSv9Snzd

**Comment by InfusOnWoW** [comment]
That code has never worked like this.

The text update code is only run if the state changed after running the various functions of the trigger. (Since only those should affect the state.)
