### ISSUE TITLE
BUG: Trigger > Aura > OR conditions not working when checking for MISSING Target Debuffs...

### ISSUE THREAD

**Issue by Sethadon** [WeakAuras/WeakAuras2#363]
What is the expected output? What do you see instead?

Expecting texture to "popup" from the left side if any of the 3 debuffs are missing from the target.
Instead, the texture does not "popup" at all. ☹️

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

Yes

What version of WeakAuras are you using?

v2.5.3

Was it working in a previous version? If yes, which was the last good one?

unknown

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

no error

Please provide any additional information below.

In case you do know which aura is problematic, please export the string and paste it below.

dKdQdaGAue9skLAxOkSnsKzssmxuunBb3evPBJk7eL2lSBsTFsu)KKAyuQghj0qrc1Grvz4iCqjv)wuhdPohsilejzPOkAXKKworpus0tvwgLINtXeLeMkHjlutx1LP6QiP4zskxxKnIIYHLyZcz7ssNhr(kkctdj47OQAKiPYPLA0OW4jbpgrDluKUgLsUhsQAEiP0NPK)IenOHaRabwLzPmr8oRblDnLOPveBnbJSwz(uPJCWsxtjAfveRUvwtcS01uIUgfHJzWSHh2Ih1W4WIXIHatb1rrg)GLP002Xun46yEZXow9kQaRq(DvxiBllxYBo2bltPTJ16(uAErEpgS0y3v4jPJjCfEs6gMpcpeQt(D1Y7SwDvxgkKmmNTTy8OsiGDzBz5siWKohMTWKoNAcxwEwIrTupwY4uAiCYDutMYKUpuflZVwToqcuHL09XErA5hZWiZVAnMHrMF1AEBJP1wy6cNBGaS0y1TYAsG1gSkZszI4Dwd2AyRjyK1kZNkDKJJf7QMIIeKiCmQRop5LzuJk4yY8lVZAWsRODSIU5kVZAiWmVipeyNeHJriDJFmcPB8JzcDSh8OJJXvAneyNeHJriDJFmcPB8JrKcghhlQ1THbeyes34hZe6yp4rh7KiCmcPB8JJJ1XyvOwOmFuCMirOmFmtw4Cm(74ZaS02TJPtCczBz5sdyPXIBdtM0KFx1XkAsym82IXblfSBhlKlXqG9sW13giW4sH3qGJJ9sW1hcmUu4neGLcGkWQeOchhJCOymqGzATvWXyI68uf1vABCmzo4qGXLcVHahhR1wYCIacmUu4ne44yjJtj5qXyavyYczhcmUu4ne44yrfYVZAiW4sH3qGJJruL4LGRpeyCPWBiWXXsgNsYzovlhuHf3rrn5u4KGaJlfEdboooM0T6SwqIWXURWtshhRkyPPGn04a

**Comment by InfusOnWoW** [comment]
The trigger checks if all the debuffs is missing. To get the effect you want you need 3 triggers checking for the absence of each debuff.

**Comment by Sethadon** [comment]
how come i can do it the other way - check to see if one of 3 buffs are "applied" - and it works as expected?

dKZ1daGAcL6LuvQDrOY2uIMjr0Cju1SfCtrLUnkTtc2lSBQSFuWpPQAycXVLyOesAWOqdxrhuiDAPoMsDoQkzHcLLkQQftiwoQEirPNQAzefpNutuuLPsYKfLPJCzkxLqjpJO66ISrIqhwsBwbBxO68OOVsiLPjQyEekmscP6VkHrRKgprYJvOBriX1icUhHI(orQptvghvfJnu4ne2YxUL7lCnUmItcItoolEgEgu4s5FyqBee27i4SnNx4igo386ItXCA4KjfL4gUibZLLBjZWJMxE41rQJBkE75z8ClzgeeLDe8210cnv5KLbHnozsrjUHRmPOe30I)tleIosD8k1fN)4gpuzQfVq7Tsd1qaN4TNNXHcNBS4saViTZVlWeXWDvwtdfe24r9koMqqgCzlCEAsDXbb54VNRfhdmkzpyGWtAlFJfXWtABHEAJ9qpUi5AcIGRxls73HRxls73fDK64gEY1eov5EgHZnw)tJxPchxmet8mtK0WGI50Wf9O5NRefljbHZluL6IdcBFIGxDnBL6IdkCnv5eu4eZPHp5M2i8j30gHRdDMXBVvceoBTDqHp5M2i8zkOnCI50WNCtBei8H216vOWjMtdFYnTr4tUPncxh6mJ3EReiq4DgUS5XaJIAzMMmWOe5vwJbg34s3z0ke2rIG7sSkE75zCne24zTwStUrQJB41qaF1AVvcc5ejcEOuZGcNQbZrYafoBkqnuGaHt1G5iOWztbQHcc5GyqyjIbceE784L0ekC2uGAOabcFmu1AOW1TZly4Iw08L0VS(geoVemOWztbQHcei8K2wq1G5iicEsBlgdvTgXW51rdkC2uGAOabcFOosDXbfoBkqnuGaHpJpPAWCeu4SPa1qbceEsBlglSIujedpRhg6XuGycfoBkqnuGabceEfkCzlCEAsDXbHT8L7Tp4VNRfhdmkzpyqylF52hFWJ6vCmHWw(YTCFbcpoe25iZgeaa
