### ISSUE TITLE
Venthyr Condemn 3 Second Cooldown

### ISSUE THREAD

**Issue by rakkarage** [WeakAuras/WeakAuras2#3631]
### Description

https://github.com/WeakAuras/WeakAuras2/issues/2766

Thanks for this. I have been reading and testing this for weeks. But this weak aura is set to always show?
I play venthyr (maybe this not related to cov) fury warrior and it has a 3 second cooldown. In prot no cooldown works fine.
If I change it to "Not on Cooldown" It continues to show always.

```
!WA:2!9zvqVTrUv41RIXIvlwGyLeBNeNuLSBn2nDxLyNeN0CQA8k1MuVwEhjVo9sNHZmuZW1Jizi5iB5BvafixRo0Fa6utBAlGo1Z(xaHqrq7vFy)bKFb9roskUfk1awdFp(4hF87947XfQxQtPOsrVC9HKqgTjlteIx7dgJYujmrdUIWOYIIEnA3wIvR9HJq0qyI9yeQky7A72QM74qglnIDeT5reo2)0PI1IIXjcuOfITCLkKqvmOnHsKjfDGpQI9vcsCmwi)TRlMm8LxHF5mj2JetzcCtoon9xtb0s4lzuhJPybjSzc7Ogu)X)xIJK2pUyuuV(gJZG9WFyeoiRD7w94yXVQ2o7vF)DotMfG7IPQ9e42KJDBUxTD2Xrbw4knBOJzHb8uupSqKrTM6amc7mdQOajte8TSiS)mGAc7a54rEBxTzlVMTQ62Y1QNF1TNWgL3tWIfyPS8xypuFj)sgWWhdeKNDx3f1b7pwGrPnNkU6f(xF9yJzVZG(2Hpnsw0LcYWhfWXhQxRFuMaz46sBmWSeRA)bYZJ1Gm6eAEz9fhAORQPhH6jxx)PVrVIEv9n1)e9xuAdD5XvTXTY7lrbPy9v0lR)mdc6p3xFv91032xxYxFdF911RPVJDMFwXrre5pKrHv2fVjI2JVeYoUv(EAOScVfsCWckk97HWoSdXV9qmMxfCZqLRX)9hGOKo2tYw6pU(PyKe3ujW0yvYhPxXHYO4XtpREMGMqIHu3izFJPM4S(HoDqeAD9dGfOFOEl9J0pg(w8)vdKBirkdwqMA3Ch6tgcbvxCSjR9zlRxzmigauzSGLrJ6ooGjIWcpM9crb9kdmZB1nuHpw5fYszIINoXmR0ZwyHfkC2enDjscqP(JMiJHRj8LA(ImKaxUEwAA5dsik80PLKtWfE5T430cU9N2mbWpECpfPdEI0cdMn)T)PC(nMJ1MmRoEMKgxtkTGFr78YeeKFU9m)8T5RICmo6asKk53nuWuab1cu7SBJDRX)85aEeoecAPECbmWqJf4xBoMfhgz(3x)lEwb4V5EQm2eMGOuCAcV058XFtErOfgB1DeWphiq8(hmzWPw1tPx(QZbAB0WF8eLW1wGCV148sApFc68RoNfMpW1q4rNL7s4022QGov3Vvd(LSkn1imPUHwMZPkiob9P((CJmOGabUlXKfQxra5tMPhmZl5xSUGCs5VldfbzQOYTA9UtGTSwJ9BTZtHaZ5jRzhNYVhkoHeH9oblyjZnGgqI9OzDcGuWCD8LQoZn31oHCsg05AjOxKF93xifjvj5XOFitQiT7bgFR)VSHxh0XlnxBSz(Nlx7lFF2e1ds4jHEQeO2Bcuk(JEZ44u2r1f4xKHPH927c3RYMp0XOlzK53PexFJGHEhhKPumAd4kd0ryOr9o2QrxXA)0i7aJq(1itQ9Pqn4F5unj2jBgIsXfYJWgzRJ0kHeEif6luWAZoey8s2nXXwaijibtItuyNugk6hTDd4yvasPsXj2k92BZjbkaDQAz3ozPksXrMz6Ib0bZCmLxxpqsOXP4f19l6ykRSmmWcqyksk9pBwJMdnnC9DTQxx)7fhu119PnCbZhFou3NK0FYsc9ZBAFUUz5ym8DJx9c)X)H4eO4n076dhkSfyn0RJ5DhdMDDsV4icnpgcgSmF18hcm5Li1mnvRjemH0x)h8h1waLZGUdW1IcbsChGiC3OYMv2iaaTnjUOZjmwN9kCVk3xVM)qflCsv(vxW)53MeD22qJdChQx9mrVYB(28u56gun(wqZTDRvBxxukpbvW9iZTAm)YtFHJPK43qSDiJ83mJenI8Zr9EXJ357EMdCLLA2lCIB4SKInZeP8RNOuC5tU7DpcfZQqy3TxNDpW5bIh9T39HdnnYi2J6Dw3nmbhE4w6p9R(G(DrcIzFUDd3aRA5DGjkOF1qgD6tmC7IsZWfa9lQFLJP7U(1limLsJXYRTU(1(95cguVq1t)K11)jlY6xTz1D)g9FEcC6)cSMCe0)v9RlO)B2fQ)7MUIvEqftIz)PNFFXX5j))7sYG7x5rv2yRsD)Np))a
```
action usable and not on cooldown are both true during the 3 second cooldown!? if i do the same thing with bloodthirst it hides for the 3 seconds it is on cooldown, even with just the 'action is ready'

```
!WA:2!1z1YUTXnx4OOyKwfuJyNud3K0cNGud00c5yNehGUtJJuRduK8)i5y3ffZWzgQzy8isgso6I3vbu0Swl6IMMErBA7F3PvDTFciek6dGx0ha)eusosYUfYgWshEU8XdpNd)OYuAXMlgSyWRwDaYNGRrsy(WBDHrGereHvLkqemphRB1gn4qXTU4qa2xzyhccl82QyL6fTh5tiXbK24ATruO7gjSy6nJeck)txBT2GqsEezTUnRSN1dzp(zR9il9g52tWqHHqgVYQSXIV6QhZt8GTGyXomyduh7A7uSCzlrxk0MtHXXwjyKWJgd6czSeSXvlvQsooHdDaECcZ7zKaOBVGegqN7lUUTXRrf81lxzxoWlg2t7Ugl3rmiiUMg7kGMWHwXesGicX4IrAF4tS42ZiUDap3GaOxsJg1vzf7ZlwENs7wEAExtza1zOZwfQv3Pw9c21PxtJdSdWxCkAr2y1N8C9NQ5T(YT7NGhxiYnmaXFrcwLYTGBaWDPlamY1tTRpIzpr1bGmmi(5QIO6OfEYbqiTGcrFHT(S72NdJBy6uY5ujnhi0ffyeRvAexzGkTTHH6w8txso)i1spG)bHmscoOLC((AfewaKnm9lho6qy2bcyhHJpjMWYD0ydMvpntMmzpESMwiosvQDNekmiesxO2ltam4kLsIJxzViKaoASzIzal7RUnDrd88iGAMA)05Um07AuA(ObH1eiCOoEOqhCstpv0P6OluWZJbBHuNYkgdC6nNrGH(bo(aUiIE1ZSxBn9iCsQ7OoWG9qQXHVAaJiuywxP2Qs1kfNz6ea9rnbXouMsqxFZsVX5S5Q)DLR)0SQ)OFW5LGramggh9VQhFX46XiJU2Qs3EmaT3EJfoYOEsLNU8mG20OChnwPAIv1rV9O0B1tR2V3mcmvWwGAcdoonLMmEzvy36vPxZOuFBu5hY3u5SkOwog9j5o99Nb6GPnUi58m1CN2C)Pzj9QLyOdx5)LacuJWGvQxN(rZafDY5e0vD5c57iIyqEKIA6YZSgB8nDvg6TpphoTz2FQl35dPJhCodzOCUzcYPNlNMGolmZZUMcQPJMrWwtPXs7IViHlqn6kN70ELHYP6U1lVTAeCLZzUjcfaDoeYir)1OWys7sm4ltGy)U7CP7NFJhzP1fDKIu6ZIhpZh1tRtd(iVeHGGRQscfh7aT6YqCOi6DhQLN0b7hojuZiSX2(N1wnFqmmRz7RhH8pad58SP9vToJpLrkTly2dldfqKxeefgjGksyqWFB4FPqHhqiIHr91lnLNipHcDSyj7MjXcuUHAlTGQ9r5MLM)BvpochgdNtQE66qcgQOTVOba)yaN7E8uQ9dWQ3TCTnQxv2ITxbB7TRARIB0zqDxuuVXH47sV()HqpfJbNkV8L(2)WsZuUKcNbmdbRU6kFBwN0Q0DFNEtE00LbmVmX30MlamrolK6DPCEnuFXJYz7pTmBdIPrGSBKGcgsEz5n68IhLuR9ZToKqAUt27N)bYR5oqq8hZUVCg39Vdk44Ti4aytStPew3vEa96t2ynz2tqMNddCh2GPg)Qj0xUYEs6yDjTkDE7vBl7IfRy3wFJg6PE9UbkmhdH17emYJdBQKSxp)g5x)OjWxur3hnq5BaYC8U3Q2(rq)d2uELp5c9Abyi9oFNQ2Eg1A7TaXjWSYxpGG3AmkkVvkSuxJBlFtgMMtmeYVXQY342JYiQRdIUYpEv53zGv(6nku5jYV)Ek7zKVw(dPHl)r5BYk)jtuYFw)Ox(hMxp3neHtV6OsWLOlJcXegC8V5PO(58ImgHXD7dWOuV2u(1LKZBHvZuhbbCDfZC)4YJM8doC0)AfvzrFY590(yA9)IvtacRIv(lYF9YYFt()L)Us8B(VAwK79G8po)6BUyR)C))5d
```

is there any way to take the 3 second condemn cooldown into account in a wa?
please and thanks
again, apologies in advance if this is somehow obvious or dealt with already
seems to work without exact spell match now maybe something has changed recently idk

_Originally posted by @InfusOnWoW in https://github.com/WeakAuras/WeakAuras2/issues/2766#issuecomment-739297378_

### WeakAuras Version

3.7.16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. make wa to show only when condemn usable or condemn not on cooldown
2. does not take cooldown into account

### Export String

!WA:2!Ls1wVTTrw4iO1BYYCzDKrD9LTDfArstAqnw7CpafynDKYnzlzkQyN0lsdjhjnjuK0Zm02YTnTRGrGF2)eeq7t5j9W(di)coqyb2(S)jKh6Z9mKuXY21iaPVqoC4zoZ58D5K6XzewxDMBoZS3itRmozC2zMDjC7cuVgYMBp(Ew(ChkxNy)ChUFqWO6UST2IWDYA677kzb8nlwVUGktXBNSOhXZUPpVKpZtATqULmZz0TEOR7cmUTlTMHiGythHtSLmFpXnmescxQzvN5Xen10XxsTosoRrdkxm1f5jlFzxhQvy96MTdO87NRqP8vkOlXpmiHCYCDebux3h4i02teArxN6jlJrZ2Sx1fMVSz1YMZByQhIj3kWL0MYn8iTOcnJOqTUpL4kB(2JwItXJAuUuUcf2n0lPe06z77g2YRSQdsBXjoSqX2NPtOGwG1IjBAqCzn8GtXXEsDGuDXeAqBOAunDxFItEljXfVGXnAfIWNMow22JdxsZW2LieQv6c2wu1I(wjO(c(U(8hMoD6sP)xZC9oC)nIRaoXJ1IiPnne2ywtBftwn7g)oNtdAW5lVwiHtZMhzGSR0KjPD5rfKchFTtBefy2n4(HbjNQmE7JOl85sDpFp6CHmNEvw18r3A96lUOlFxb1TEe3oNzXsyTijkEm1BWDOCpI7Jrwd3OXE2ytljEY8it7ZTmM)UpOs5(Kqjkokger(AVo(oJvo)nl8i1zn06k9TxpontKQ2QFcZPJjDtQDOK2RohPTYsorssVBdoZzfMJS5PFtSOlV6VQoZQ8cg5YTuhveQV)eJ72l(UEGhEvP1XwEd97wCLLmCvu3Pt(BmuNkvQ0DXIXHfxM9yE195TI6uTDJrDC5nGZK)1uIqvpr(LtcJb3SVdQhv)UQsDYfuvIeDuXPQe4M6TimV8Gru0qzWeQGVp7H3jJ9d35ciXiDzEievXSWdwkxphMqPFr8q2DaOKDU(IMeh)nEsmq(pobCs4ubzhk2QX1F1GQswlAYxPcg1oui9BPIOsGdkLGP3dziFv)zhHS6ZJFcNgBvn4SAW50G)(hFry0DgfMaMegZiY2bt3F(i7C2kcILlnidAjQI(6guPbDTqgN6udMsl48Q9BqX(HzxUP)gf9Q1)aFUNi61c4WfSF8Gpc(4(C0BwwDnlHK7e)L))p3xLfXGDQbFGgmo8H7kgoMGXubr3efFdf6Ur1fo7551GZdzG)Pg2l)xe1Rb21GPdMCWfNTe3VbNkezVu0vF5O2TUkZqJAqZOfo9IRwdkXPnWQbpBqwdoVA826uZ4bhl67qF1jcM(pKqIxyO4fh4lBa3XsVOPzXf1R77jdgnpNTv2LdjokjFwtt4ctnomwFCWIA8GY565axmp8zQrgWLJE(5rpVI6zhvwuE6jt0iRgRrsdxvxI1b8xlC6Gp94vkbCQnt5etdlR07hw2(43Tqgg5UFauuJ)muRXQ3wVqU8MWcjoB4PWT6TU7t5n3S1wB9Ohb5sd3dUp8V1aDCO4GjFPdUYXxJjtXQkBImwtKaB3lUxhYnJJZPXZk2(mqjToBG29v4KGoRKSyNlaRaRcpzFx1SWxf7KGVof8nW0W3cvtCcNlYme5e(Ti1tSGWQg4a0iPeqIvm4efphAlpLQb1PtPPK0k56(Ifmj)YBLGWZJph0ziDg4UF0qRxDcWd8vsLygrb1iIpeJCODo7r2znGhRJaHs7CLJODIvtYjHquOaRdFxejaBKg((2WDGa4fimUj0EFE8)OusdypfJRRHm7YHZFVBuO01nBlvu6pergOyaPa4hHFkb0XCESq9bh6G4NcPuWRcdvyPDmON4p)1VibPTIqp8ZH9LhWTpaQhCivikOo(aXh(G4TQXpe0Dm2UHGUHuuxtbGV32if(Ii3bq9TJG6H9miO3(AHK6RT2IZlU9aIlb4FrK4FiKFOI7QrxW7sUpyWFcjyPgRpGcuSr9jgrRscfOyifOoaqv)544GKtfh0(SWr18yT)Nr(QOqLw7i63xQWU9bYB1B2lFBJWnBo7SZUCeiJI0diFFFnFzw))T6V)d

**Comment by InfusOnWoW** [comment]
You need to read everything in that bug report. There are several different auras depending on the exact talents you use.

**Comment by rakkarage** [comment]
sorry for extreme confusion

i tested all four ids tested: 317485, 317349, 330325, and Condemn
the only one that shows the 3 second cooldown is 330325 in my case

my problem is that i was then turning on require valid target which is not needed and causes 317485, and 330325 to not function at all: to never return true for is action usable

which i did not realize immediately or connect till now

most war spells it seems need to use "require valid target" or show up always like bloodthirst
but execute or condemn does not need it and in some cases does not even work when used

so I can just use 330325 and uncheck require valid target to get it working
thanks

- i wonder why condemn behaves like "require valid target" is checked (when not) and only triggers when have target
- i wonder why 317485, and 330325 stop working when "require valid target" is checked

**Comment by InfusOnWoW** [comment]
Because the spell is incorrectly coded on blizzard's side. There's not much we can do.
