### ISSUE TITLE
Deleted WeakAuras still requesting updates

### ISSUE THREAD

**Issue by stmarson1** [WeakAuras/WeakAuras2#3636]
### Description

I have deleted the Legion-Dungeons and TORMENTED AFFIX weakauras from my PC, but weakauras is prompting me to update these deleted weak auras. The auras appear in the "Ready for update" dropdown of the in game client, but nowhere else as they have been deleted. These auras also show up on the Weak Aura companion desktop client, prompting an update.

### WeakAuras Version

Unknown

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1.  install legion-dungeons or TORMENTED AFFIX WeakAuras
2. Delete the weak aura
3. check ready for update (im not sure if an update patch being pushed for a weakaura is required to trigger this bug)

### Screenshots

![image](https://user-images.githubusercontent.com/75420090/169358119-76b46430-42a0-4664-a7db-52ee5c1f3453.png)

**Comment by mrbuds** [comment]
Does /reload fix it?

**Comment by stmarson1** [comment]
No, I've been having this issue for a few months now. Just tried to /reload for the sake of completeness but it doesn't work
