### ISSUE TITLE
Glow sub-elements not always applied to aura clones (e.g. nameplates)

### ISSUE THREAD

**Issue by HPLT** [WeakAuras/WeakAuras2#3638]
### Description

There seems to be inconsistencies in the application of glow sub-elements to icons. In some instances the glow is simply not applied. This happens for all types of glow (Action Button, Pixel, Autocast Shine).

Have a nice weekend !

Cheers Max :-)

### WeakAuras Version

4.0.0-1-g5ea5c51

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

None

### Reproduction Steps

The easiest way I found to replicate the bug was to use the following weakaura in TBC Classic: https://wago.io/juV_mYYFt
and then

1. Make sure your nameplate distance is set to 41 yards
2. Move to Stormwind City and place yourself at around 58.1/64.4 (Thus you have the two Stormwind City Guards at the entrace of Stormwind in front of you and then one other in the back)
3. Rotate your camera always 180° between the two guards in the front and the one in your back

At some point you will notice that the glow sub-element is not applied to either one or both of the city entrance guards.
This problem also occurs when placing an "icon" aura in a dynamic group and anchor that to nameplates.

The procedure as well as the bug can be seen in the following clip: https://www.youtube.com/watch?v=tYv35sLwjtw

I hope I have provided enough information for you to figure out what exactly is happening :-)

### Export String

!WA:2!DnvZUnUnq4eKfy7QdnznAd2d9GrqBA7cKGKfR92J1Y1k)aVngsQbjNSPehjreAsvsk74C0N6z)i4Z9KFeYtGGrrEa2hH8e0HY2PaLx4WHFZFFZmB7vBynAn6F99ZzXsrGSqfdF3wljfMmP6QCdtk0oQjxLKObZ2liIyuFpjtyC72XlCzSuYPYXIGXSCyWJBE2HMczksCL9n91gIY4eLWemDMJlEzCMAuS0uqP)6dvRfFYxKhFb9GM)IRzso4wG4YRvOH(KiTufDoq4FwsHbFrxebJaHjOijHD)I(TBfe2piSLF4x(p4vq9RWvzQjZxqgcANzwmvHAWuDoW5xq1oV4ZEka9PFqVoD7o1I0Mgdk3BM14CoXaZPqeg4qmhvN3PBpV)O7ScX6IWj)T26EeeU6Tnl(7TEgzmqji8RXkgjf2Z3bqElm6XgFcstzZic2qRKOz5B8EeiAiWOarQj71L76kKcyjTqvHOVLEuAaBzu9uluBUuEO7qct4v(dObLhw(JL)u5pJ3o)Fny(RjgRVGS5yz7dP2(073VC3L4Zis8DPkzHG(0YuUCSNc(ZcqepP3Ro54p0OCxfcY(XJi7CgE3wYLQSPwv28yzuHXifxncuCYK5w1DRQJVDHv(21dtZs3y6L7GNQ)Uz9FU2hdQIEygl(obO17uzqqmHdRe7Yq1VTY)UsffuzrzalnZaUCjHE9Q2m2tXpmOvcZ((dl4gMJFmNO17x(RoU2oWkb2dGvahDSlbrSH5sLzUQIBSLLRDdP8SblyIePAvRYX9bPC42vdPTxp7JnCSJcdY)MnBdHW9MFJPjrCGM98QDipfonzD7SFV1N70RBRWoZnY4rRgp(QEV7agn)al7wVn2LzvBs1fst9w8XKj66TYZ5mGgHjvcl1zrI1H4edXq2XFmJAYa)4xy3puWOlUS9N0nV9spzBpftydfUKE)Ak3NWZZi7mp(LO5mDtbKntd8KQ1EF)lo78WA689(4XNC8jhD6rPnasJ4gNwB0)CZ)(

**Comment by mrbuds** [comment]
I can reproduce the issue on retail, easier to replicate when aura is not shown on every nameplates

**Comment by HPLT** [comment]
Hi,

first thank you very much for taking care of the bug so quickly!
I tested the fix and while it now correctly enables/disables the glow, the glow properties are still incorrectly assigned. You can see it in this clip: https://www.youtube.com/watch?v=N9B-KUbKaSM

Hope that helps! And again thank you very much :)!

Cheers Max

**Comment by InfusOnWoW** [comment]
Please include your test aura in a new ticket.
