### ISSUE TITLE
Lootinfo for caged pets

### ISSUE THREAD

**Issue by x9cf9w73cv7y** [WeakAuras/WeakAuras2#3639]
### Description

This WeakAura normally displays all the listed items with an icon and a text as a popup.  But if you put a pet in a cage it causes a Lua error

### WeakAuras Version

WeakAuras 4.0.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x [string "Error in: Looted':'initialization"]:28: bad argument #1 to 'match' (string expected, got nil)
[string "Error in: Looted':'initialization"]:28: in function `getItemInfo'
[string "Error in: Looted"]:53: in function <[string "Error in: Looted"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:548: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:747: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:854: in function <WeakAuras\GenericTrigger.lua:839>

### Reproduction Steps

1. Put a battle pet in a cage

### Export String

!WA:2!TVZAqYX5rPrBKv0kBhPlYk2ok2J3ejFN0P13dDNEeRiF79q3zoD3LDp9k2U2D2D(2DgD7oZOzM9EOibjh2XIq5uPoYVOQufCaoPcgsXbvkEMeoGajqGMJazXKajkMabi84cVceW09338AFDsou8dQktjn7389O7(R)6U)6U)(oPIDuPd1oCY3FYJNS3(6q9MhZEPPlw0H5o(N24YQpX22wk75z2o6MgpWA6gfnTRO4IFeFtfJcAM2JzRuHn7swS8zgo9OJo1kkg6IEmyQkk6gJLYfBmLHPbBd1Q28wYsvz7WkyAO6SmtXHdai(6uXmU2mJsUA7mTJRIT7yWUG4WUH7gUh837DN5lQBO7O1y1PlRxr3D3R4WkxCgtDd38PME2zN(C9v1US1b0CDTCo1J9ylOuYmPU5JDPso907mtD1LESE7Bff7ctYX4ZU)LR6WMKaKM1EWIdXNHZWSpVbw1A5nTvz2dBw20(jLKKITQOIrvlXS2BMRwvXMjpw1YLLVOMUlZwWiy52qPQlcMPTOPUtC7f9yVpXZQ)rL322EK8evnXiRequ9vvxDTNCOJx8KZPu9jhiFEBfv9Qop7DNhzyf1lfF1Iiwgw3UqzwopIiJ(1y7yvxZcERv3VuUlTsjBZQwtGd6(3(D9Hx1PA(0SscAazTLkXSL2iVsH5uTnTeZQyXIntSEsoWMidKzBOu(ccOXYlWIwAhlLcSDSST5czOsXULOHuEGXApPkRFTRPyRkpRPzzxDR8oSkinLUVK9MSN1f9wWa21Tqkdjed3Xuk4AANp9qJmX5ZK2PGszwSuoM2Uq81ksYxOmHIRsmeTUCbiPvT5ZesSzD1LmuQOxGpzxLeP09y0iuPcdMcLyCJdVH4WEIVMqQviIm8Otn7OP9wxNWaPPyRvWSC1kgIjxQYMkQxW(AidycvNTNYXIvy)PRufNxXt5GC89dNnE6cLvCCOs5Drc3WLxPsz9sgWql7ARtmANh8qRu1W7J42EfEFlJqSCze2XHDLwb1o6lvvKwZBvwzjKNXMhbx(XzkLD1wvLLVAXI0m2E8rNCMXo)K3cxr5Djd2G(IRLD4HYmB2mZou6zdAAgBg2u6mZm6KtMg5tmN4lxYwxLGtI0JScv(I6QUA7ofYaxiX5NjHU6YtAA6s66Dm)x4sDu4W38XxrhzSzD0vzPMC0XMfjghfxsBMPbVU4RJsf2ZjwvVKe82TPPsEfByNdcV(B(grXwu4AOyDSO0gOwvwCX0WPmPA0XssiNYstrs0NZgt8BAVFtflpxAyXyl7B7OJEjJa8AxkwElBgItCHr3ipx4GjTra4hRQrbRBueFtdStlBZsy3D6wMBy5sE)E5ULvzLDvUK3VxUR4Y4JndNFgEDv(iYbdx(WE9VlFa0QwrOWmuJh1kviHrmFR96GFRxsZDw)QH3WfaJvDkJCzBQbCIIJ3iWk3EWMHQnu7MZXywdrsMUPjgKg0bm06fqLpvZfmiBtARXxEgxxvLzKEQrVWOPHTp(NApBJ)y7YweNPSL9vCHypq6fijIxPJvPv9mMvTlWoW2GhLSPapKKy1EwXWS6CcYurruD5PhwXbLAkLsX(Pp)ehn8RJMHgGWIQ6vQ64YuzQNt3qRXQuwmh0h0p8wEz08(AOmwbBDUvt467y5IMOGoQZLUSIDjwkISxEmgjfYCkcxpwFZXwAnvDhs3HKFHDL31SuPYmBejJGWslfj)BTVre9rgngwfHLm1z0aqrfuVo38Pi0ADc)glH8r5YypKxqhTSNNj7HcMQSIJSISddviXfpzUHQKiHapVpzCwCW4A1pe8(Zb)Ww71hXu1CScVqUlyByEogoH0q6vJPGl9iiisEkeCAWZT93h8bS6Cw(mr2vla)Y5xItxiDGB2ur2wXw3DjCS5NxPCvMZvS7nPSLPP9k9LuUGzLkMgR1FszuzGx2(yjPHWShiPmZsVW6dMuUmRekZQyVe88RlaNaT4Ab3MhU3kkLjMmDmbH008Ej71Tx4kAA5WNlaRGZg4hH4fFOCWZTP)e3uSfiT39Y4sk8dM2PIs5YWZz1)iOzkdXeuPIjAQu2SOSREfrvKTOGfG51D0ZxML8ftHInw0(v9sl)v0n47DbFG1Ma1BfoxKeE(n9yyJ4zaPVkklUB0ClQ1vIjMmVjFc0VpYDslpDbVWoVarN7csUcUImoJ0k12yECwRGua3UzoCvJQow4Sc(XXzuFPrEjA4hfrqw6CDJtELRwLjtB4sBvzGYpIF8NGjNhxP33OgeO5v6V38z4cvR7OzUG)(SHsv7ldwTSF9beEoFch(yAWpDo4LIrq)(MfTP5iJtW8vDDXFkv2CbHm7glGBe7W1ulZCcH)(9ii)wcWGgSp4(w23qJg8iRLz2PV2ILV205z9aVJbHZCO8fqnBZklUdfAdHSmJ5tYnR7iFA53n3kRfF7j8ZaR0OvXU8n(M46fkw8eN4KJCYrsiNmjAU1M(jX1TtiJCx543iE8aix0GG6nIwrsDCcHBWgf(LjeuVfEB0mvsu8tTtzQ1UFu(UYN6r7swHwESXvntB5IkLDyCJ61JbUIqicKVJWaPYENIGZPSWmMlWSFnJKkklyrd8ofrZW96GwEJYWkHEJwhMiNHp75NyKotiCtjrxYN(0Yu3AcMLyU8fGji93OlYz8P(YM4o5YCg(K6gZHDYBIGUoxqJ3XUXf8dU4rU(4ILLdUWrUUws8)OuqtWidFWnbfFWJGIx(Po4rpZbvp1ZCKMHWeQ4OrvJQvYZS7SzWiWGpGovNhu9WDDQKhorxnbjYaE3Yz72dUO9i(xzJuhHRZgHh1Px1cyv3YBie96te42k(ojw2iBxVb2ojf2kUUEuUoxun5rrE(rBINtT1AwUpOrWqfBndNAjGlrF8oRI(n7Uue(uD)tWT8NzDgI9gbkchdxANP2Tu6ndtE4f5lG4QhPy0BdGzlKfcXT3mSnscCWGlrri9c0kbh6nVmhYre9O7aa0DDtS6yx0Y)kQMzfwBZjc0bEP3l82kcV4oHpEoynn4M5Gpyo4dFf(o05I6X(LLGhgKxZ0whJxGV9NvhJpD6jExtp1Sdnz2jMcDymZOPl4hHySBXhCkmwh1ZzQY6BOrgb66k7h21gyuhH7V5vrrtmwnEf38awpa52ww(lrMeY64vaIB9g51JrlBsjqOaF710JPVitDvHV9KpNPMA6PgDdruCxsmbKGDzJiIgT1HAcb9M0iBE9szfRIE1AT3HWWQzZRJqDkEdoRZhKNZf52WdegU8ymND8jg(7B6Zp7Ktm1OwDWBZrtb347YEKG1d2eIl0B4u7HBjzPeqdABkAJMS85T69A9MB5yefZlegBZ0vLvqhDSklU7AbDk(DPvcMoRo6IuqtolOSu4CK8RUlXNlGbdFrBfRLVOxHBjMT(5vj1qNF2PTER3M5tw0jR9UsqNsDqSzVfTao2EIWgdtQIx1rcthuwLxvOayByNCHmEULsxeDn22BHQozLDx3QNVaKyTNIdrV4sGYnFyRhPjmyLLChnKNgRfcZwEfstDvfwp1qOWm8Bc)wO)u)2WNrQL8nNg5BWNlN1d1o8l(sYQR21bV0HK1vdxM1qVZwc(DHFp4Vuc(8sTuMkqdCdaEVTK1gLc1APmNtlK5GVa8hd)jDbFrOg8NcVCBgxtQMWNf(sK8Id8Nlb)fCzc4RS5edp9uzfP0Jsab8vBVGGtebb4RbVYoQtoWx8d(6WqF9vi)Fds9vS1rN8pRFn54nI7HXC2BkQOMWmdvCz6fpvmdnCgnSlBWRqtVWCy3DITg9Phc7lVI9QCqXtY49XlNsKonokYWZ3fFi(eh)dFHtoShZMHrpyuyPzED9KSVbM3ltAEkfetYlnwzzyi)29kpdAkPSx25cSQb7AfYenVYn8AtqLPOq99RY0Jk8(KY0vmR957QpzfgdyIIkqvd6MTzOj)a1yPLXzDWxJFMV0x8zEpBBBJVkFNdUbU7dEcyOvrgUxEcZzTxEJP9sXhTZc8YBuxDsPUMPzfohOFVKAWJ960WjJvt6UZ5h3TiLNXVh40V)dLUGgRWCJLW0kXPpnmvSL9JElVie308WLLSlOrXd6C4dTSfghfZgLE2dYRs2FYqJp1KoWto(z(Q7fF2Z3A8Z81(5PNpyqHyhQM0dTjnObsgiyDhmMhiK6Qj9G1KEZ4yWsVLdVFeE1KEyXpYTPN7G65He9uGSp5drpteB8Z8rVF65uXenlVfn3kiVZgGmToEa6rowui2q1Tcs7QjA8vCPN5h)mFUFu6z2XpZ38ltpF66P1TSBTct7UbmHZYVYEONtkffYnu9dmOagW32J1)GuFxnCPeRoxK(TSFO5r7EnP9ii6p0(ONEAvHx5O3v2x9v)kRkCvJ0K2mW78UItoYTHVAwMf0Ty54PGlYwF4U(ug(zAWifHr3omgLTzyC(7j4VFs6nLUISgS59szV9CAWKtDi4CXHPU5dcNhUG1EPEuIzWS1lqPqyAJCByZukNXpqdj4tS498DcJ4uHI9b3aWPBz28DJXHNmQFUc1hYFzr0LHTG(PArz3miMF6jS7uqPDhupLJJMQK8iCCDvwtn4NtySHijyGoIKKnK0NWXqRMTO)1L9JGGKdhM)cElgA08YegEnnOBeHnq5Qt40MaOIyN5(6l6fYqQQuIfwdXJmyLdRiCi9jQGY6RUs5XkRuYrudDufdlg3eJuhyMWqLTyD1KsXjc2QAGceQE0cUJM)WP46fLYBKHNsl)w0DoNzE9Ym)VYGUGR76)TgUG51FJjzUUm78ME43Pk3d00k6QEHgHctcGuu2W0ncVIYdMrWIGiij(NueVbbpD0JkxuVmIcAQ5kxbboYjD8bzNS5PmuKy4XhA2SNlZzZo50tpBIU4WMgl9zaoWVXHWZ4RUdLSv((CDlRAsKgUxFPGU6rTTr0JNhfok8ITZNKdXcLKprULvCmEuxzZQ2o3ryQH01iYrtJiZFWYXBQaIE(jcj3PQjH45mqLIfOHJYVCcdN7fumK1uSSWAvk4IHAwEPUIsrTirBDgUY1v9lDTm3inNjJOQxnK)OOWUoWw3h(wBsE1Wua0BR7bDAauAl8PNw3RWe14vQ1Dtxq8HPKP1aZfTtqz)mrc5gEA)ucxSSQMVSUJgDEtU1tNbwLFQG5XZq2j9n62eOMy2rpxqDm0svtRKuskUtwi)UkxfnVahKoN7O1xFfhu(u4)gPLs6gIdNa3sj)sC9k0AMnUt1I6U1n(2OZg94oEQOK7rK79zAMb0GXOa2PHA7PCV9jRwPkTWOgjfvHRH(S0NHNV2wuFOy9TTdhP(mHrk2r(UfKM)idsOxZ067OxoEtSipD8n3oIKejETPC2eq2sLv)5zBuc9ZzNxHTsfRrnxFz3BJIB9mPw3zpbZtxNCV8)B1VdLncvVBeoNBOlkpZ0xC00YDwOQTnZWT8sYlWKfw51uMNjRGBpQy4i7AkC2cnYZ5aAmBwxBTHb)dIyRnoGKbPHPJuiRcsbm16GAD91cHHBNjO6pLCIU9tHSnJ7JBu8eH0c2zR591Q3TY4rMjn5dW5MEQrVCcHAuR3aNoM2qNe49N7Qq7qUqlY70lpDufHIOErjz9GdPPKihYrCjuoXbvpc6sIQz9R((aZRaQ0vkERS20GXLHcgNV4ts(bzxNrdEvj9GC7B5ibhiRTxPw6prRfHd0jcMjnqJXBNM(zzUdBQB4DndeQBDkGsxXBNsS3G4PyVT9nqxUNMNiHQBjiEqIwQS9AqkB4ZNo9Otn8wlOnmxvTWsHcB(dRExt90wU4qNs2)c6iFu5cEJoQwhTp4sm3KEN2sD6DTZjAphh9MCuOOBsHi65mnLSRCIRuKJ1bQZt6URxNcEQ4RjcVLNbU14cevTuX301RllDbNYHHsdzwX7YavyUC87fuGhmA(aGcIa(gBk(6cEjUXzrPpIisYadTHbw6F7ioT4uzexqHeHXXrKe1OWDHiniU1e1bl65P6HebsuYMffk8w6L3Yc0D9RXM6ZFqmJgBQFEt5rK1ylhJ3IvvBCjSX2gG3Mj)oleAxreF5n8cuteyBlzfKLEkXMTGrK30SCIOWjsKUTfw(H7U1Wl(n2OUemClh(pd7LGJ1O18cL5xUUCW7esVItyUhMoUDvdU4g8nGDbFciZ6dtX2DoH4iCz4DbxeUeuUJExlIyQM1EPB938Szf3WoklIV02O8cEfEImMN1NIXsqPyImrgM63e6Q5NKFDAGDa31nFCihOa5Pl3guqcE7GQ3Dzdy01ydksxDnOKeOfd0JbxjgmxmIwOlNvLyGbycwsWvb76UMQoGl)oE10L4Q1xTlyE(L5cwqdwewkYD2cUg8UHypaC9xPd4grUzwW3p8daVhn496DnQ(yrUtkpl8CW7JUdi73)YUey4OKIUHd)sGSzdwKICnq8hLFtYNLpQxOPB7d8Jv)nHbw9fHFc)BPd8t6DhDGFk45Hxe(i7g77hvGI3CZ3cNalJrUjobxOLgqZpdo5GFw(0a(4He(93W9JjciB5DKb(5eGyTqq8GnDfyIae(1Gb(fO7)Yu2x7IN4KxnDXRwrC)xGpXIB)lhy0h5TfkROxHFto47C8)n3kgUf9i3dgxt7sAkoUEeTEeRC9EYJ3x347E7L)UF69G83h7y839WFpa9UNtYlZF3pVpdWBDqrnhNdHtWRFq69X5VpghYNG3Z(4JQpoK7vuJOp8r1pNsgKxt)8(maFS9ZX(ac6KxUFEFgGdTEfLfWKtd9lObrp502a8A6JdTb41CcE5(eyuml41miVM(4J9yCipihYdYRPxr)fZur9CiFCoeoUGhkWiVp9j4E8rDS(BXLvYlXzZsovhOxf9(AG(FwNtK6Dl7QRsEsQBPOB705wSi3KZK6f7Kgm6FsJjlIFXGI6oz0YE9jmRMEYy08jo8lg96gmg8I7MURbFCC)9rZb)s8lwa8ld)kWVk3il8RbFsXnfa(u0Rp9npa8RJ25wh(n4hs6NrIFoP)oWNf(C54NA5Nxc(9Xo8hObG69c)HWgWFuJNRi8NTx4lbF5ONwiA6wC(GWTOdaC30HF(1PJ1f(RIb)14gkRd)nrovw4VLoYv4Vtc(MroRu4VNFGOW)Gg8p2eo)NOtPe2SoK(T8r6)m)uhH)fXzmc)RIA)3Yb)77f(2KTY)d4)e(oW)vm4)gE1AsB7(QjjPvtA7XQjftQM0Rd))o8oMVAs3fh81K2znPxFnPDLd2vnP41K2DnP7UM09GD9EXgFd05WvtAp8JERM0ER7q3Qj1b)W2Qj9gX1L9bVCnP7d70(fNJwnP3K)XNvt6(V)TFpfOtnR1hUIuthJZwFwybhJZ374V()Hh)vnPhPHJ9QMuIVlpWRAsV1AsVTAshefYoexFOM0JEBodRAsDIAfD14jxvt6WiqocD8u74PV9hp1wNK(aRUTkr9FVJ36o54TA6uw8IDn7itKzMjh6Yzp)mJm0SJ6FElBD2t89jLc3S7WKTvTs4hdZ5THFt(Hk(BuiSUjnDCf1f5WLQdD4MHC5IOiKMD1Jf5h)0Y90vBpfNgiE2I68)KhAzQDJIOgtVBDTfMCuKC6jERZrBKmr6rPhPj03gwR3LcD4SdhPIKuMtI8DNrjPUA)bjHSX6ZryD(YupuUd4JTkbXxTXPtJzkkHp6oL8tBKizYOturFAvMxBm1r1nkQUX0lZMyK43(ubhV9jaUoGE1wKj4BFg0ANeu0Z451s6qRp7PBv6FQjDu0qBsR3uB0OHNcnr3tnPERj1NiHo1K6hlCm0Q9aW3OM0G1KoEnPtut6K1Kofpc)AsVDk0(AspUFu91KoD0y5Rj9oWrFMxAB1KEIAsdHbQxtkLFa6lhewkgIo5A5)Z

**Comment by SpatenLa** [comment]
thats a custom aura. its a bug in the code of the aura not from weakauras.
