### ISSUE TITLE
BUG: Issue not resolved :(

### ISSUE THREAD

**Issue by Sethadon** [WeakAuras/WeakAuras2#364]
I wasn't sure how to re-open a previous "closed" issue, thus, here's the link:
https://github.com/WeakAuras/WeakAuras2/issues/363

**Comment by InfusOnWoW** [comment]
There's no bug. You are misunderstanding how the trigger works if you add multiple buff names and use the "missing" mode.

**Comment by Sethadon** [comment]
Ok, then answer this for me...

I want to check to see if any of 3 auras are missing, so i create 3 triggers and set the activation option to "ANY TRIGGER" - as you suggested. That takes care of the OR conditions, but how do I add an AND condition that ensures the aura only shows if the target is attackable?

To me, it would make sense to add the 3 auras to the first trigger (using the OR options), and then check to see if the target is attackable in a second trigger - setting the activation setting to ALL TRIGGERS.

Why is this not possible for "missing" debuffs, but IS POSSIBLE for active buffs/debuffs?

**Comment by mrbouyou** [comment]
you can use a custom activation function
```
function(t)
 return (t[1] or t[2] or t[3]) and t[4]
end
```
If you need help on how to do something with Weak Auras you should come on discord, it's very friendly place
