### ISSUE TITLE
TBC 4.0.0 arithmetic on 'modRate', a nil value

### ISSUE THREAD

**Issue by Blumberg1337** [WeakAuras/WeakAuras2#3641]
### Description

I am not using custom code in this WeakAura.

But the following LUA-Errors occurs...

### WeakAuras Version

4.0.0

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

24x [string "Error in: Shield"]:42: attempt to perform arithmetic on local 'modRate' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:602: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:747: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:1815: in function <WeakAuras\GenericTrigger.lua:1785>
[string "@WeakAuras\GenericTrigger.lua"]:2436: in function `CheckCooldownReady'
[string "@WeakAuras\GenericTrigger.lua"]:1962: in function <WeakAuras\GenericTrigger.lua:1956>

### Reproduction Steps

When you have the WeakAura posted above activated
and when you cast Windfury Weapon
then the error above occurs.

### Last Good Version

3.x

### Export String

!WA:2!nAvZVTXXvCRWMMu2l201coobOegOc2bnYY0FCiOogCPOczkLiZsklBNyWD2DgU7iTCMnZmROOC)iGTh8zEP9mp3t8uVgbe0ECarrVwaDT30Fb9nZUuYQaTieWw77J59(9EZ7JzLTknSeUe(nBntMGehShfRIUXmAaN1LNkcifeh1EWajrTIyC(hZrSGiUOdNYu(1QVtV6UlSh2LRqkkNTsLurCYhgPujYp9E3BekKVoLFVAhhUxRnE(lBDVh6yCG30bCMARyuOu0E3ETAUtDRJ7hWJ5IVOa87SdiKKQYesGY1y6OPss8aRN1)4j(irnRQnE6)(dn)(PnE6)6NB(vOXt)B)j43F(xuygMirQubsrIoXcZSW4fR4eZr43usqzHcEAYQUdtJv0IttLK(mYHerKBqmskxZxcQet872O62v3rFJv1FGNvlRyphbkGSM(MU9e84yJ4pYtCmNrAILVJqHIjmvLv13O4Pw97Jy4(MqYWYptmC6rWbh55SuWmmDWaAaGOXgsXauGj1A)o7mpW890KdtYiTsqWzoIiTsmaeftpKaaKhtm8CK0JTFKCvqAv8(PsfbtWBtzrZeKqWb9gNq0Glihb5mIO7bJJPmswIRxgZK70KPiger(6AiPcsooiXxVBZp5cQpPR5aoOuf3BMIhaztjy93VZnDrXjrOczLB1o)MEoMktIrJBcfa38DU(EV9v1ZxX3ud1CZPNxc5ErnYIaopgZhX6oIMq8sUAaev8HgWUBcgU29tT)5KL6vhhsIMOe0Wqav)13TWAICI3uAoguFWGAMlkOGafsd8MIGQhgAir(PjxTfnmsXGGSC3ikjgFYEGPfljQJeQOCIfdrQGiISBeFuB2cP9pBtLMIjxR5U1mOeKJlVvQy8SmhBs)Ig1B1zRDBjG7ODa98ovM6d1Jmv3uZ978(1Q2Tx)U9Q62BM5qzE4KmpufQtoK4A13VbbfRIwy8wFoyzKIlU9tEY8Suu)ikM4QOdj45MQfO2loUjoAs(hYIokapUM4VItkJQ8nxreX5aQJGaaYTBN6TAjGuBBw8yVjdsJJLbiw00uwEMT4A6p7nx3vbTkhO3iPKGmernPXlG1V6jlcjmIGgKfpZmXt14rOXs9l0VmdHaRWaS30Zp)TV)g6M6VaU1JqIqI8TdtroVs3x3j5dQLF9xUJGhkisz5701eN3n56gttoc6WYsbMKE0cbK76UKuxBX5zi7DsY1m0xcWEwvohzWSQLA)()H)UEpxlPTT0Mg8Sruoe909ZsrAp9g6ypTVoWe1ASNMKhJ6bqmPh6P7OJ00i9(6A6d80FtKMzDGMRdHqnXtJGK5pCdgDHbDSg0dmyW3()1GGt)FAqZ5USfJZTOXAa(VWGMU(9tz2sw)SIYKs59VzfoT4qlysTbwL4S7OUBXYLfeyoeRS6RU)RkdttlFh1xv5vL5cGZdE1DxY6H5SE0RUBrcdNCnK1p5gEBoM8xUYzuZOmgk(zzdOON(wdgnJfNIy0H2TAp2vQG27NP3ZpbkFiQjeKKyAyDyWW(tmuDvccluf9ElWMnoWP6B6Gescmwdl1V2bw1mYXuHa2r)B1)g4F)U3t)71FR(1UjPXsI)aO6rgze)6lj2zactoZhQCWcEst2wcy7z0PWe3GdgVzU7Ie5tA)jZGEux7iD5hVQEVfaP5SMvDm8)CrymF0wcY3KsybJ78J2y9kpsVNauYiyU5)EE(6(jgctyUWpvP4S2GhGPaZmSBzJ2By1)f56p1qCXG9tGe6NVKtKvy3ayJvble6fbONbnJfCmKzYBbBCKxZ6ahUadlI9JiM5UF5P2TcoW(oS5(Rs1n3CXYmY5UStHnw)rtwoT37s3OOJIQKsXZ3)xFiFB0lgg(W9DT2mk5NT8eMnhBsLi)ycoAHVfblt3ohZ5dTPRhp1(wfPzeQBZpVrVZUi9MbLvwzflusU2LEDKb4ov3Tx75w2nSr2tol7rvBjGXfMKTF3AU1RVZ8bggqzfsHE3tZWItEaNCvNy6XhJe4Y9aOROj(sYq42X9(RVX6p4)Ehpe63MI9ZwoL7BkgtyU7u)z1DtkbQVCgjGr49wep3rM3d(LIShFiFS(4I6)yrhOcvvCbSChqC7eROIWZOmLEWGtRP3m7vxKO5Cbf2uyd9znA728LT3Px1wZmneu7rV1AUWEYGdES(Z(LxzYHib1K6RuDNn9T8LFmi5JUI(7Mqzb8H(iL7HO4usbGDb935ywkO)(cMP9myu6Twt)9EtseMfbQXM2G1RSUTQMYgWfznZRMCtAiJli5WVUzBwDHGlKE(a0gqdlws6(qirUrPd)hp))8

**Comment by Blumberg1337** [comment]
Actually I was raiding as a testee today and this bug occured so often... My game got so many lag spikes... Still playable, but being tested by a new guild AND this bug wasn't ideal.

**Comment by mrbuds** [comment]
Thanks i can reproduce the error and we will fix that, but i'd suggest to remake that aura without the 4 spell cooldown triggers for spells that don't have any cooldown

**Comment by Blumberg1337** [comment]
@mrbuds Hey, thanks man! I changed the triggers to aura triggers... My bad.
