### ISSUE TITLE
Aura Visibility State

### ISSUE THREAD

**Issue by Kiofea** [WeakAuras/WeakAuras2#3643]
### Description

Auras not remaining visible after clicking off of them. Auras automatically hiding and resetting visibility toggle when clicking onto a new aura. Impossible to restore previous functionality.

### WeakAuras Version

Most recent version.

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Open WeakAuras2.
Toggle Visibility of any aura or group.
Select a new aura or group.
Watch visibility status reset to hidden and previous selected aura(s) or group(s) vanish.

### Last Good Version

Whatever version was available yesterday but not today.

**Comment by Kiofea** [comment]
The auras stay visible if selected, which is a normal function, but will disappear after selecting another

**Comment by Kiofea** [comment]
Not sure why this was closed; just checked with latest updated version and bug still persists.

**Comment by InfusOnWoW** [comment]
because it is fixed in the refereenced commit.

**Comment by Kiofea** [comment]
But not pushed to live?

**Comment by InfusOnWoW** [comment]
A alpha is automatically built so by now it should be in the latest alpha.
