### ISSUE TITLE
Secure Clone/Protected Frame Warning Opt-Out

### ISSUE THREAD

**Issue by mrbuurns** [WeakAuras/WeakAuras2#3646]
**Is your feature request related to a problem? Please describe.**
The Secure Clone/Protected Frame warning is producing a lot of spam around 6-12 Lines on one Weakaura use

**Describe the solution you'd like**
Opt out or a spam protection for only warning once a login.

**Describe alternatives you've considered**
The suggested alternative to delete the Weakaura is not an option, its too deep in my playing routine

**Comment by InfusOnWoW** [comment]
Each time the warning is printed, a bit of garbarge was created that can not be recovered. This eventually will affect the frame rate of your game. You are better of deleting the aura, as suggested in the error message.

**Comment by mrbuurns** [comment]
As i said deleting is not an option. This is not resolved.

**Comment by InfusOnWoW** [comment]
The problem is between you, and your aura.
