### ISSUE TITLE
无法加载wa

### ISSUE THREAD

**Issue by miraclejm** [WeakAuras/WeakAuras2#3647]
### Description

4.0.1
/wa 无法打开wa

### WeakAuras Version

4.0.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

/wa
无法打开wa
但是wa加载了一部分

**Comment by Stanzilla** [comment]
Please fill out the issue template, otherwise we can't help you.
