### ISSUE TITLE
i can not use /wa to open wa template

### ISSUE THREAD

**Issue by miraclejm** [WeakAuras/WeakAuras2#3648]
### Description

my wa had installed，some wa string is used，but i can not use  /wa to open it

### WeakAuras Version

4.0.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1./wa

### Last Good Version

4.0.0

**Comment by InfusOnWoW** [comment]
It sounds like you might be having an lua error. Follow these steps:
1. Install https://www.curseforge.com/wow/addons/bugsack
2. Install https://www.curseforge.com/wow/addons/bug-grabber
3. Try to do whatever it is you're having a problem with again:
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
    • GREEN
      • You have no lua errors from your addons.
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • You have an error with an addon, maybe not WeakAuras.
     • Make sure you clear the bugs once by alt + click the bugsack, to turn it green, then try to replicate the problem again.
          • You may also want to disable all other addons while you test this
     • There are error messages. Click on the red bag to see them.
     • Copy all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
     • Paste the error messages into https://pastebin.com/ and click "Create New Paste"
     • You will be redirected to the new Pastebin that you just created. Copy the URL and share it with us, and we will be able to give you more specific advice.

**Comment by miraclejm** [comment]
2x WeakAuras\WeakAuras-4.0.1.lua:1101: script ran too long
[string "@WeakAuras\WeakAuras-4.0.1.lua"]:1101: in function `Login'
[string "@WeakAuras\WeakAuras-4.0.1.lua"]:1184: in function <WeakAuras\WeakAuras.lua:1135>

Locals:
initialTime = 15000
takeNewSnapshots = nil
loginThread = <no value>
startTime = 702097059.992000
finishTime = 702102644.653100
ok = true
msg = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = true
(*temporary) = true
(*temporary) = <userdata>
(*temporary) = "script ran too long"
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras\WeakAuras.lua:3160
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @WeakAuras\Transmission.lua:346
 combat_event_type = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras\GenericTrigger.lua:2378
 UIDtoID = <function> defined @WeakAuras\WeakAuras.lua:1812
 IsEnvironmentInitialized = <function> defined @WeakAuras\AuraEnvironment.lua:192
 form_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras\History.lua:21
 RunConditions = <function> defined @WeakAuras\Conditions.lua:720
 tooltip_count = <table> {
 }
 pet_spec_types = <table> {
 }
 AddParents = <function> defined @WeakAuras\WeakAuras.lua:2804
 ReplaceLocalizedRaidMarkers = <function> defined @WeakAuras\WeakAuras.lua:5161
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 ensurePRDFrame = <function> defined @WeakAuras\WeakAuras.lua:4675
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 FinishLoadUnload = <function> defined @WeakAuras\WeakAuras.lua:1796
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined

**Comment by InfusOnWoW** [comment]
No fruther response.
