### ISSUE TITLE
Updated, changed every load setting

### ISSUE THREAD

**Issue by Boterwafel** [WeakAuras/WeakAuras2#3649]
### Description

Updated to 4.0.1 and all the 'Load' settings for all my weakauras got removed. Everything is under Not loaded now.

### WeakAuras Version

Weakauras 4.0.1

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Update Weakauras via Curseforge
2. Type /wa to see loaded/unloaded WA's

### Last Good Version

Weakauras 4.0.0-4

**Comment by InfusOnWoW** [comment]
We obviously need your settings to investigate this.
