### ISSUE TITLE
Weak auras option to only load when have Leader role

### ISSUE THREAD

**Issue by Believe82** [WeakAuras/WeakAuras2#3652]
**Is your feature request related to a problem? Please describe.**
Weak auras should be able to only load when I have Leader or Assist role

**Describe the solution you'd like**
Add Raid Leader and Assistant to the "Raid role" load option menu

**Additional context**
Not all addons should show all the time, Sometimes I dont want the addons I need for leading to show when I am not the leader or assitant of that raid.

![image](https://user-images.githubusercontent.com/28548048/170328708-f2a0a9c9-2b55-4788-aa60-c20fae03d6f8.png)

**Comment by InfusOnWoW** [comment]
That sounds too niche for my taste, what is the use case for this?

**Comment by Believe82** [comment]
At the moment I run Pugs as a raid leader and I am a normal raider on my main. On my main and some other raids I have many auras that I dont need to see or load. 
I have one weak aura that shows me cooldowns from people, one that shows me consumes and buffs, one that marks targets and one that changes people to groups.

I have not created any of these auras and I do not like to mess on other peoples code, however if you tell me there is another way I can go ask coders to implement this, it just sounded easier implemented in the addon.

Thank you for your time

**Comment by Believe82** [comment]
ty!
