### ISSUE TITLE
Debuff track

### ISSUE THREAD

**Issue by Exidt** [WeakAuras/WeakAuras2#3653]
### Description

sometimes there are problems of a similar nature, fixed by checking and unchecking the box several times

### WeakAuras Version

WeakAuras 4.0.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

--

### Reproduction Steps

In screenshots

### Screenshots

![3](https://user-images.githubusercontent.com/106329888/170513701-839ce429-f98c-4694-912b-3edaa716597b.png)
![4](https://user-images.githubusercontent.com/106329888/170513715-ed7e6712-3a9d-4c9c-89d6-d1b7e9bf458d.png)
![5](https://user-images.githubusercontent.com/106329888/170513731-72cf31f5-1f2f-4537-9fb0-35cd41cf915a.png)
![6](https://user-images.githubusercontent.com/106329888/170513752-7d76b48d-5c4b-47e4-81d2-81fa6c2ccc34.png)
![7](https://user-images.githubusercontent.com/106329888/170513765-3d200711-311a-40d1-bb79-667d19cc163f.png)
![1](https://user-images.githubusercontent.com/106329888/170513794-36651230-8ce0-430e-80a4-e05336af3bba.png)
![2](https://user-images.githubusercontent.com/106329888/170513816-57c5df5f-68a4-4dad-837a-cddf99c76777.png)

### Export String

!WA:2!TJv3sTrYv4vLYgNDQkRTKnM1oBsuSl7yItiijKeKu7MOblHWgKWJgmWMFqZOPLM2mm94Uhj(j)cj1UKK7OsYdGkFzUIhbEcoLQT8dGFe8L5QC6zKmyhGLSSCv0nsN50NZ09P)(oN(mDKNexOn(OJnAY4Rf3kU1UF7UMg1x1IZ8MI5W4pmA0OZhDSrZ8stg3IWv7nO3vuDOBTLb3kHoJ54t964ZQ3MWfuM7heP2s8nQ0OHG4hXm0rB(M9uSVHBDBgFEg113CQcL1lO1j0MQ0TiV7(HYHZEKirI21OLpAFfpF8vlu2tqCAe4mOWnQhOmRMW3G7Ry2G6sf2kQ4F(k74ZPnBIlPBExEpXpTJfXSvJg6B6r4Lkm78fxywvF8bnJwCJu7i8iooZyjuEPOLjPnX1VkAnDJ9xzQ8v1xPQEEnD1w4l30ZXytcxZ1ynIqrlWuZsedhF7x768Cc6Qw15lm7S71YT3sqPxWwWQjXlw1N1YGtsuSLJtIfTP(KdchnCV696WjnXauUC1AYzT82ZWLUMHmOZcxP4bedbPQpN4203(sWWQUmxsxlmuKwSImW4csDMRLyhPPY3dCF11mOUfHFa6aCF4hc)iyu8)yVTMBrTu1jcFvhMHvrtFdhmMUU2ATq0wrf3PQFDiTIwDhdHqkPkq4tkSFdoURGlldFJOVkeTlkvjNEZQtPvOq5EO8mUyug1exHnOnv0e1XjjAhCduliUfkVcXzc31W5jHulAhz0qdPc7tDBW4HBhkPArT2)zjP5YozP2pAKkXR)V392DOO5vzT41jF47aFtf4BebEpqPBDKZAXw3T66upsTd6)OetSvL(udU67Fx4AVG3sqkJl9A7jjibO9n1YMm9Kj5O9vCD2Sg8DHeWhMYJ43rYmkSbv4lS7IlR62ervB26vCpqe8xEKU2Ma3qb(okW3dUfCt4BHB5FameVuET5qYiCBfVygbMPhYxMJzr(xVd8X0xTkH4LxUV7RjdzByejh4TXXF8xmYIjbcdFjlHydF0p56WWDXTCzEVKJ5AT718I7t2WFfHTbUTSuVexVBeOm4NW99ve9eG7V3Rh7w3r4DLJ4(HzYVmuB)8x18lOxX7QbkXCCMeiRVi1Y3wnp(4RcNi6geRaLB3nKkTCVLZbbJ)0wcFAJnbLoCMpgq6Os1YvkxagMJbL0MobgwVF5SO71lcC99UsroDRepULHLKSMqx)nc8(Zu3aDRJm2f5gE7SypHWfqBQGA6qQ1lMpsXnVyZuUCbTvuRORxzoTzMUKE3xp1YAD3OxeT0BmpYrdQpvzb9zNPCHx0TPdB9ICYZArCRV58FTXgnvMWOtoW(YF6)g2r(G05UMT89zUvWkYyHQos1ZguLyOa77hz7jF41f6JEaY2NUVgBv5G2bZUUnT(QUeHiAGhvdYtdeNLIQJfmbQHf6nTj0M2(BdjB8YGId4EI1ksE7Dnfu3MoKNFzi91F(LRbPKLl8UkoRRqB6Y4bPAAyv01SHXVl8hIcPVznidkP9aTfM5bOBW21GSs3GVpueYVVJTM7svDl56XG3huGFUI6wm2ArGjGj9Uw)eBjR4buHbcuw2W7kpGclVXXDkBgZv7qUHxCCXmvpVWupmtJutB9a(NMHJNTru4NQWPUYJ6WSNCrHVEe4NPSt)zQgCzmRubIPaXv292WuhTUd8GAqbBOy)QlW01Gs3untQKjHh2Rqc8iywByoO8XvMaQGfiG5dQhap(lFfaqRxIpuD3Rb6rGfqDpbZCHfdYuHLGLHpb(fWVCB4xfb(14sFfOgAUbygSpb1blGebAanb7AafEkS6naNiWAG7lawFsk4bplcWbb4pe0kc0o051THnSHnJcBff(nXGFRn87K0f43Ji9HKd8HHq5HQb)X3MoaBFmuH2to(tNV0J8361ub4pfWdG)8HyE35KKZntOAiStKc(0Wf0Nvd2DB4ViXw4VEiQc)TVeWPzQXYKD8XhaOhhGEju(sNva1D5hAsFQ2JZw0(Kb0xvKHNUNG1irz5zAKVsH0DJX71s4N)CzMAQSPZjb2qqD)GwYWtwWM7INmamLGQeCLipI13ieUNU2lLvwp06As(G3vpI)vWc(g(m(T(4p6)JyebG9zJmOVXt0MoZwM21h5Kjd7xIAkBx0NCbLBNm74tKmZGC7Zds(GfwS(0tYk6Mw7KrY9Q2c)Ma(feoQLoDUjYoagppW4yTZT5iLVN(ZQm3PaJtTzDh8JsVOshNm1yto2aC84oQngkh7SEuBHgTgl3YlwC2mlDYG5o628lY2MsLE8CdWYJdlVdkFNZkwQ12AMfkSAYL9sEkTnv1h7RXGNOOJXfvvw1KJLBYba6XbOs5lFwb08KC5szvAXcJCkFyJMg17ISPNudaYZZPL3l7NS0cnMo30ERFYyyN5ySlYUEqum7GBA4818AXfS9gHkmNGCk4yvMS0QkXyTlMes8OYmdQSESvwhgLh(Swz9Em35kx2jv(fF4jJMEXMZqisuW13qE7LRrC9VqoTmBUjh8LLNRKZNo)enlznsR1PlEkhuonNTUZxXxteS34dHyyQ0PN8W7hc(7Fb3ke8pcUii4Fo4wFoP70L4iwWyIPBN6uo20lEVCtQBZeAmMV4IQrOmzYLAqJq)xikILhPP23ampeJpkSMXzj7Y6lNA8XZFYWQPMXQ)p3ju82F(s)Nd

**Comment by InfusOnWoW** [comment]
I don't have time to decipher what the bug is. Please try to actually explain in words what you think is wrong.
