### ISSUE TITLE
Simulate a specific situation to check what weak auras are loaded

### ISSUE THREAD

**Issue by psyquest** [WeakAuras/WeakAuras2#3656]
**Is your feature request related to a problem? Please describe.**
When using weak auras it is sometimes hard to know exactely what weak aura will be loaded when fighting a specific encounter.

**Describe the solution you'd like**
It would be interesting to a a simulate setting where players can select:

- a specific raid boss
- a specifc raid size
- an instance type
- a class or spec

and be able to see what weak auras are loaded.

**Describe alternatives you've considered**
The only way to see what weak auras are loaded is to play a specific encouter and see during the encounter what weak auras are loaded, but when the encounter end, it is harder to configure the weak aura and another pull is often required to do further configuration. This "solution" is cumbersome. Having a setting sim toggle to load these would make configuring and debugging weak auras more simple.

**Additional context**

**Comment by InfusOnWoW** [comment]
Too complicated for too little gain.
