### ISSUE TITLE
Not have 「new」button

### ISSUE THREAD

**Issue by Feiya1126** [WeakAuras/WeakAuras2#3659]
### Description

I can't see 「new」button ， how can I do?
![wa ](https://user-images.githubusercontent.com/50092218/170818125-ec1f7770-93c7-4dd5-a15f-8b752de8b5b6.png)

### WeakAuras Version

4.0.1

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

See error

**Comment by InfusOnWoW** [comment]
It sounds like you might be having an error. Follow these steps:
1. Install https://www.curseforge.com/wow/addons/bugsack
2. Install https://www.curseforge.com/wow/addons/bug-grabber
3. Try to do whatever it is you're having a problem with again:
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
    • GREEN
      • You have no lua errors from your addons.
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • You have an error with an addon, maybe not WeakAuras.
     • Make sure you clear the bugs once by alt + click the bugsack, to turn it green, then try to replicate the problem again.
          • You may also want to disable all other addons while you test this
     • There are error messages. Click on the red bag to see them.
     • Copy all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
     • Paste the error messages into https://pastebin.com/ and click "Create New Paste"
     • You will be redirected to the new Pastebin that you just created. Copy the URL and share it with us, and we will be able to give you more specific advice.
