### ISSUE TITLE
Set of global functions in Weak Auras. 

### ISSUE THREAD

**Issue by FranekW** [WeakAuras/WeakAuras2#366]
If i make a dynamic group, is there anyway to place some "global" functions which could be used by all auras within the dynamic group? I have a set of different buffs (result of applying Rogue's Roll the Bones). Currently, I had to create set of local anonymous functions for custom triggers and custom text. For each buff, the functions are the same. They are different only by one line where I specify a buff name.

I wish I could create set of functions in dynamic group scope and have access to them from each aura and call them with a parameter: buff_name. Is it possible in Weak Auras?

**Comment by emptyrivers** [comment]
This has always been possible.

**Comment by FranekW** [comment]
Thanks. How do you do that then?

**Comment by sragia** [comment]
Make a global variable (function) https://www.lua.org/pil/1.2.html and it's accessible from any weakaura.

**Comment by Bananaman** [comment]
Not possible anymore. `_G` is shadowed inside weakauras to prevent setting global variables.

**Comment by InfusOnWoW** [comment]
I deleted a comment from Banaman that was simply wrong in the context of the ticket. As the original request was simply for a group wide function, which was correctly explained by rivers and sragia.

**Comment by Bananaman** [comment]
@InfusOnWoW Ah I didn't read much more than the title of this ticket, and thought it was about how to set global functions in WoW from auras. I'll post it as a separate ticket then.
