### ISSUE TITLE
Miscellaneous 3 (Small UI issues)

### ISSUE THREAD

**Issue by Nightwarden24** [WeakAuras/WeakAuras2#3662]
### Description

The following are small issues mostly related to UI:

1. Invalid atlas format [here](https://github.com/WeakAuras/WeakAuras2/blob/e274bda/WeakAuras/AuraWarnings.lua#L76)
![11](https://user-images.githubusercontent.com/45747886/170882580-411e059e-fb45-4446-8e86-091363d910fd.PNG)
It should be ```result = result .. "|A:" .. icon .. ":12:12:0:0|a"``` (see [link](https://wowpedia.fandom.com/wiki/UI_escape_sequences#Texture_atlas))
2. It seems you rushed to combine error messages like "Cannot hide secure frame..." and "Cannot show secure frame..." into one category (protected_frame) with warning messages in [this](https://github.com/WeakAuras/WeakAuras2/commit/b73d46e7fb84a6b10a19e9d05958defdece4ee7d) commit. I mean error messages should have their own categories as it was before this change.

   As a result, at the current moment:
      a. "Cannot hide secure frame..." and "Cannot show secure frame..." messages are not shown on the Info tab and in the tooltip.
      b. In combat. If "Cannot show secure frame..." message is printed, then "Cannot hide secure frame..." message will never appear in the chat. And vice versa. Only one message is possible.

### WeakAuras Version

4.0.1-4-ge274bda

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

 \- 

### Reproduction Steps

 \-

**Comment by Nightwarden24** [comment]
By the way, if you are in combat and region is protected, then the following error pops up on Show:
<details>
<summary>Click me</summary>

```
1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'SetFrameLevel()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "@WeakAuras\RegionTypes\Icon.lua"]:258: in function `SetFrameLevel'
[string "@WeakAuras\SubRegionTypes\Background.lua"]:14: in function `SetFrameLevel'
[string "@WeakAuras\WeakAuras-4.0.1-4-ge274bda.lua"]:3645: in function `ApplyFrameLevel'
[string "@WeakAuras\RegionTypes\RegionPrototype.lua"]:929: in function `Expand'
[string "@WeakAuras\WeakAuras-4.0.1-4-ge274bda.lua"]:3906: in function <WeakAuras\WeakAuras.lua:3900>
[string "@WeakAuras\WeakAuras-4.0.1-4-ge274bda.lua"]:3995: in function <WeakAuras\WeakAuras.lua:3957>
[string "@WeakAuras\WeakAuras-4.0.1-4-ge274bda.lua"]:4078: in function `UpdatedTriggerState'
[string "@WeakAuras\BuffTrigger2.lua"]:1616: in function <WeakAuras\BuffTrigger2.lua:1608>
[string "@WeakAuras\BuffTrigger2.lua"]:1952: in function <WeakAuras\BuffTrigger2.lua:1945>
```
</details>

It might also be worth checking to see if locking restrictions are currently in effect before calling [this](https://github.com/WeakAuras/WeakAuras2/blob/e274bda/WeakAuras/RegionTypes/RegionPrototype.lua#L929) function.

**Comment by InfusOnWoW** [comment]
> By the way, if you are in combat and region is protected, then the following error pops up on Show:
> Click me
> 
> It might also be worth checking to see if lockdown restrictions are currently in effect before calling [this](https://github.com/WeakAuras/WeakAuras2/blob/e274bda/WeakAuras/RegionTypes/RegionPrototype.lua#L929) function.

Yes I know I only made Show/Hide "safe". Making everything safe is not something I want to do. If someone creates protected frames, it'll break the addon.
