### ISSUE TITLE
'Since Apply' condition does not work for auras missing/always show state

### ISSUE THREAD

**Issue by wing5wong** [WeakAuras/WeakAuras2#3664]
### Description

I tried to create an aura that implements a condition after Xs of being removed.
i.e. 2s after losing rejuv, make the aura red.

It seems that either this functionality is not possible with this trigger, or an issue exists with this trigger that means it doesnt work as expected

### WeakAuras Version

4.0.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No error

### Reproduction Steps

Create a Aura > Player > Buff trigger with Show on: Aura(s) missing or Always

![image](https://user-images.githubusercontent.com/4406993/171146488-a62b3fb5-e2c5-4100-b66d-047f44bb80d6.png)

Create a condition of 'Since Apply > 1'
![image](https://user-images.githubusercontent.com/4406993/171146576-d818a9a8-3f9d-4b14-8b7f-d55bc1c2eb1f.png)

The condition is never met. Expected outcome is that 1s after the aura is missing, the condition is true.

if the Show on value is set to 'aura(s) found' the condition functions fine as you would expect. i.e. 1s after applying the buff, the condition is met.

**Comment by InfusOnWoW** [comment]
it can only work if the trigger is active, you need to set show on "always".

**Comment by wing5wong** [comment]
Ok, so it is not possible to track time since losing a buff in this case?

**Comment by InfusOnWoW** [comment]
That's different from what the user claims to want to do, but I can take a look at that.
