### ISSUE TITLE
update aura does not work

### ISSUE THREAD

**Issue by WoWretweet** [WeakAuras/WeakAuras2#3666]
### Description

hey

1st of all; atm i got that problem only with this WA: https://wago.io/SL-Dungeons
you can find my issue under "[aeuae#2331](https://wago.io/p/aeuae#2331)" 
when i try to update the mentioned WA (ingame tells me there's an update & WA Companion does the same) i type /wa ingame and click on the update button. i try to update the WA and the progress bar fills up. nearly at the end the process seems to cancel and i'm back on the /wa window with the update button still active.

i was told to write this issue report cause the creator of the WA got no solution for me...

if you need more information pls tell me.

i tried the same with all addons deactivated - same effect. no lua errors on bug sack or bug grabber

thx in advance

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

 i type /wa ingame and click on the update button. i try to update the WA and the progress bar fills up. nearly at the end the process seems to cancel and i'm back on the /wa window with the update button still active.

**Comment by InfusOnWoW** [comment]
Please attach your existing settings from the WTF folder.

**Comment by InfusOnWoW** [comment]
No the WeakAuras.lua file found at WTF\Account\<Account #>\SavedVariables\WeakAuras.lua

**Comment by WoWretweet** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/8826128/WeakAuras.zip)

.lua is not supported, so i zipped it

ty :)

**Comment by InfusOnWoW** [comment]
So I have taken a look at your settings, and from the state of it:

1) You did several imports before, some might have had lua errors and or you imported the SL-Dungeons group as a copy. It's kinda hard to tell.

2) The update actually works, as well as it can given the strange state of your auras. So there's no bug.

I do recommend cleaning up your settings though. Delete all the top-level auras that came from the Dungeon-SL group and probably the SL-Dungeons group too and then reimport.

**Comment by WoWretweet** [comment]
thx for the aid. is there a simple way to delete the complete WA in windows explorer or do i have to delete it ingame manually?
and whats the proper way to clean up the settings as mentioned?

**Comment by InfusOnWoW** [comment]
I'm not suggesting deleting all settings, just clean it up in game. 

And I forgot to mention, that there are known issues with selecting hundreds of auras, so it's better to delete them in batches of ~10-50 auras.

**Comment by WoWretweet** [comment]
Ok
I deletet the SL-Dungeon WA and all the separate "child" WA 
Then i logged off and closed the game before restarting it. Then i imported the whole WA from wago.io
Hope the next update will import smooth... 

Thx for your effort :)
