### ISSUE TITLE
how to resolve the error

### ISSUE THREAD

**Issue by stefanielyq** [WeakAuras/WeakAuras2#3668]
### Description

error in dungeons when show friendly nameplates

```
1018x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = <unnamed> {
0 = <userdata>
}
```

pls help me

### WeakAuras Version

WeakAuras 4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

6/3 16:57:19.540 An action was blocked in combat because of taint from WeakAuras - <unnamed>:ClearAllPoints()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\RegionTypes\DynamicGroup.lua:45 <unnamed>:SetAnchorPoint()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\RegionTypes\DynamicGroup.lua:1078 <unnamed>:DoPositionChildrenPerFrame()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\RegionTypes\DynamicGroup.lua:1194 <unnamed>:DoPositionChildren()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\RegionTypes\DynamicGroup.lua:1056 <unnamed>:PositionChildren()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\RegionTypes\DynamicGroup.lua:1037 <unnamed>:SortUpdatedChildren()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\RegionTypes\DynamicGroup.lua:842 <unnamed>:Resume()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\WeakAuras.lua:3997 ApplyStatesToRegions()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\WeakAuras.lua:4091 UpdatedTriggerState()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\GenericTrigger.lua:752 ScanEventsInternal()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\GenericTrigger.lua:708 ScanEvents()
6/3 16:57:19.540 Interface\AddOns\WeakAuras\GenericTrigger.lua:854

### Reproduction Steps

the error will be appeared when I was in the dungeons and I show the friendly nameplates

**Comment by InfusOnWoW** [comment]
You do have some aura that creates protected frames. By default WeakAuras doesn't do that.
