### ISSUE TITLE
custom code to return string in "On Show" message not working

### ISSUE THREAD

**Issue by Noloony** [WeakAuras/WeakAuras2#367]
What steps will reproduce the problem?
- Create a weak aura
- Add a random trigger for example gaining the buff "Riptide"
- Under "actions" > "on show" tag "chat message"
- Select the channel to display the chatmessage
- Fill in a "radom chat message that uses %c" in the message box
- In the custom code add the following function

function()
--this function was dummed down to show it still causes an error
return "abc"
end

What is the expected output? What do you see instead?
on trigger (on show) it should send a chat message to the selected channel saying "radom chat message that uses abc"

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
yes

What version of WeakAuras are you using?
2.5.7

Was it working in a previous version? If yes, which was the last good one?
Not sure

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

Date: 2018-03-08 00:01:26
ID: -1
Error occured in: Global
Count: 3
Message: ..\AddOns\WeakAuras\WeakAuras.lua line 3941:
   attempt to index local 'regionValues' (a nil value)
Debug:
   [C]: ?
   WeakAuras\WeakAuras.lua:3941:
      WeakAuras\WeakAuras.lua:3927
   WeakAuras\WeakAuras.lua:3990: ReplacePlaceHolders()
   WeakAuras\WeakAuras.lua:2572: HandleChatAction()
   WeakAuras\WeakAuras.lua:2628: PerformActions()
   ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:456: Expand()
   WeakAuras\WeakAuras.lua:3729:
      WeakAuras\WeakAuras.lua:3680
   WeakAuras\WeakAuras.lua:3786:
      WeakAuras\WeakAuras.lua:3778
   WeakAuras\WeakAuras.lua:3869: UpdatedTriggerState()
   WeakAuras\BuffTrigger.lua:758: ScanAuras()
   WeakAuras\BuffTrigger.lua:1236:
      WeakAuras\BuffTrigger.lua:1233
Locals:

AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  WeakAuras, v2.5.7
  WeakAurasOptions, v2.5.7

**Comment by InfusOnWoW** [comment]
This is fixed for the next alpha/release.
