### ISSUE TITLE
Weak auras and Elv ui error

### ISSUE THREAD

**Issue by marttinez125** [WeakAuras/WeakAuras2#3673]
### Description

When using weakauras with the elv ui addon, the last two versions give me an error which prevents the weak auras from working, I have tried from different versions to the latest versions of both, I have tried deactivating everything, eliminating everything, only running the weak auras and the elv ui separately and they work perfectly. but when they are together the weak auras throws me that error

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: Interface\AddOns\WeakAuras\Types.lua:2527: script ran too long
Time: Thu Jun  9 04:20:25 2022
Count: 1
Stack: Interface\AddOns\WeakAuras\Types.lua:2527: script ran too long
[string "@Interface\AddOns\WeakAuras\Types.lua"]:2527: in main chunk

Locals: AddonName = "WeakAuras"
Private = <table> {
 power_types_with_stagger = <table> {
 }
 swing_types = <table> {
 }
 frame_strata_types = <table> {
 }
 operator_types = <table> {
 }
 subevent_actual_prefix_types = <table> {
 }
 eventend_types = <table> {
 }
 anchor_frame_types = <table> {
 }
 operator_types_without_equal = <table> {
 }
 rotated_icon_side_types = <table> {
 }
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:150
 point_types = <table> {
 }
 totem_types = <table> {
 }
 covenant_types = <table> {
 }
 anim_finish_preset_types = <table> {
 }
 grid_types = <table> {
 }
 subevent_suffix_types = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 anim_ease_functions = <table> {
 }
 difficulty_types = <table> {
 }
 talent_types = <table> {
 }
 spec_types_all = <table> {
 }
 StopProfileUID = <function> defined @Interface\AddOns\WeakAuras\Init.lua:156
 round_types = <table> {
 }
 group_hybrid_position_types = <table> {
 }
 spec_types_3 = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 text_check_types = <table> {
 }
 timedeventend_types = <table> {
 }
 blend_types = <table> {
 }
 texture_types = <table> {
 }
 time_precision_types = <table> {
 }
 text_automatic_width = <table> {
 }
 threat_unit_types = <table> {
 }
 group_sort_types = <table> {
 }
 unit_realm_name_types = <table> {
 }
 time_format_types = <table> {
 }
 sound_condition_types = <table> {
 }
 Archivist = <table> {
 }
 anchor_frame_types_group = <table> {
 }
 debuff_types = <table> {
 }
 text_rotate_types = <table> {
 }
 instance_difficulty_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 anim_translate_types = <table> {
 }
 anim_color_types = <table> {
 }
 unit_types_range_check = <table> {
 }
 aurabar_anchor_areas = <table> {
 }
 rotated_align_types = <table> {
 }
 sound_channel_types = <table> {
 }
 power_types = <table> {
 }
 raid_mark_check_type = <table> {
 }
 anim_rotate_types = <table> {
 }
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:147
 combatlog_flags_check_object_type = <table> {
 }
 spark_rotation_types = <table> {
 }
 slant_mode = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 glow_frame_types = <table> {
 }
 TocToExpansion = <table> {
 }
 group_aura_stack_info_types = <table> {
 }
 actual_unit_types_cast_tooltip = "• Player, Target, Focus, and Pet correspond directly to those individual unitIDs.
• Specific Unit lets you provide a specific valid unitID to watch.
Note: The game will not fire events for all valid unitIDs, making some untrackable by this trigger.
• Party, Raid, Boss, Arena, and Nameplate can match multiple corresponding unitIDs.
• Smart Group adjusts to your current group type, matching just the "player" when solo, "party" units (including "player") in a party or "raid" units in a raid.

* Yellow Unit settings will create clones for each matching unit while this trigger is providing Dynamic Info to the Aura."
 chat_message_types = <table> {
 }
 precision_types = <table> {
 }
 grow_types = <table> {
 }
 unit_threat_situation_types = <table> {
 }
 combatlog_raid_mark_check_type = <table> {
 }
 trigger_modes = <table> {
 }
 character_types = <table> {
 }
 orientation_types = <table> {
 }
 aura_types = <table> {
 }
 wrongTargetMessage = "This version of WeakAuras was packaged for World of Warcraft Retail. Please install the Retail version instead.
If you are using an addon manager, then contact their support for further assistance and reinstall WeakAuras manually."
 align_types = <table> {
 }
 combatlog_flags_check_type = <table> {
 }
 main_spell_schools = <table> {
 }
 include_pets_types = <table> {
 }
 suMessage: ...nterface\AddOns\WeakAuras\RegionTypes\StopMotion.lua:4: attempt to index field 'StopMotion' (a nil value)
Time: Thu Jun  9 04:20:25 2022
Count: 1
Stack: ...nterface\AddOns\WeakAuras\RegionTypes\StopMotion.lua:4: attempt to index field 'StopMotion' (a nil value)
[string "@Interface\AddOns\WeakAuras\RegionTypes\StopMotion.lua"]:4: in main chunk

Locals: AddonName = "WeakAuras"
Private = <table> {
 HandleGlowAction = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3158
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:342
 operator_types = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2378
 UIDtoID = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1810
 IsEnvironmentInitialized = <function> defined @Interface\AddOns\WeakAuras\AuraEnvironment.lua:192
 talent_extra_option_types = <table> {
 }
 CleanArchive = <function> defined @Interface\AddOns\WeakAuras\History.lua:21
 RunConditions = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:719
 tooltip_count = <table> {
 }
 IsAuraActive = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:4468
 AddParents = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2802
 ReplaceLocalizedRaidMarkers = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:5156
 grid_types = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 ensurePRDFrame = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:4670
 talent_types = <table> {
 }
 UnloadConditions = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:932
 circular_group_constant_factor_types = <table> {
 }
 FinishLoadUnload = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1794
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:159
 spec_types_3 = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 StringToTable = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:291
 RegisterLoadEvents = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1648
 FixGroupChildrenOrderForGroup = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3622
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:1016
 CheckSpellCooldown = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2255
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2010
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2435
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3293
 NeedToRepairDatabase = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2089
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:147
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 CheckSpellCooldows = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2309
 IsOptionsProcessingPaused = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1370
 ValueFromPath = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3574
 Login = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1036
 GetTriggerConditions = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3402
 trigger_require_types_one = <table> {
 }
 chat_message_types = <table> {
 }
 precision_types = <table
Message: Interface\AddOns\WeakAurasCompanion\init.lua:37: attempt to index field 'StopMotion' (a nil value)
Time: Thu Jun  9 04:27:41 2022
Count: 1
Stack: Interface\AddOns\WeakAurasCompanion\init.lua:37: attempt to index field 'StopMotion' (a nil value)
[string "@Interface\AddOns\WeakAurasCompanion\init.lua"]:37: in function <Interface\AddOns\WeakAurasCompanion\init.lua:4>

Locals: _ = <unnamed> {
 0 = <userdata>
}
_ = "ADDON_LOADED"
addonName = "WeakAurasCompanion"
WeakAurasData = <table> {
 slugs = <table> {
 }
 ids = <table> {
 }
 stopmotionFiles = <table> {
 }
 uids = <table> {
 }
 stash = <table> {
 }
}
count = 0
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'StopMotion' (a nil value)"
Message: Interface\AddOns\WeakAurasCompanion\init.lua:37: attempt to index field 'StopMotion' (a nil value)
Time: Thu Jun  9 04:27:41 2022
Count: 1
Stack: Interface\AddOns\WeakAurasCompanion\init.lua:37: attempt to index field 'StopMotion' (a nil value)
[string "@Interface\AddOns\WeakAurasCompanion\init.lua"]:37: in function <Interface\AddOns\WeakAurasCompanion\init.lua:4>

Locals: _ = <unnamed> {
 0 = <userdata>
}
_ = "ADDON_LOADED"
addonName = "WeakAurasCompanion"
WeakAurasData = <table> {
 slugs = <table> {
 }
 ids = <table> {
 }
 stopmotionFiles = <table> {
 }
 uids = <table> {
 }
 stash = <table> {
 }
}
count = 0
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'StopMotion' (a nil value)"

### Reproduction Steps

just trying to run weak auras 4.0.2 and elv ui 12.80 both lastest version

### Screenshots

![image](https://user-images.githubusercontent.com/107068974/172801883-8281e9f0-1314-4972-9e81-864ab9fbced5.png)
![image](https://user-images.githubusercontent.com/107068974/172802065-fae9c33f-3978-4023-bc81-ddf125ec29b0.png)
![image](https://user-images.githubusercontent.com/107068974/172802157-dc699252-d615-41f1-9f9b-1fc745295eb3.png)

**Comment by InfusOnWoW** [comment]
I haven't investigated this in depth, since the elvui license prevents me from that. But from a quick look, you should report the issue to the elvui devs that installing a callback that reacts to each LibSharedMedia:Register with running a bunch of code is not a good idea.
