### ISSUE TITLE
Weak Auras weird interaction with Masque

### ISSUE THREAD

**Issue by filologiggy** [WeakAuras/WeakAuras2#3674]
### Description

I was trying to make my own pack for Weak auras for demon hunter and run into an issue were I couldn't make swipe on my abilities when they are on cooldown. The abilities i tried on was Fracture , and isolation aura on Vengeance demon hunter. 

For both abilities these were the settings  I had.

In display Options : 
Enabling  "Enable Swipe"
Enabling ''Show Swipe"
Enabling "Hide Timer text"
Enabling "Inverse"
Disabling "Show Edge"
Disabling "Blizzard cooldown Reduction

In Tigger section :
Trigger 1 , Type "spell" , Cooldown/charges/count
with only Spell option enabled , show GCD and Show Always enabled. 

In Conditions : If trigger 1 on cooldown = true then Desaturate (ticked)

I tried different variations in conditions , like making an additional property that if trigger 1 on cd is true on top of desaturating enabling cooldown swipe + inverse that didn't work as well. (Only cooldown Edge worked).

I asked for help on the discord weak auras communities and after trying different things one moderator asked me if i have masque and to disable it if i have it. I did , and then everything worked properly , the Inversed Swipe was showing properly in my ability. Re-enabling masque again , made it bug out again. 

Note that , this issue was only present with weak auras i made , not with weak auras i imported. I tried making myself an exact copy of weak auras i imported with masque enabled and the issue was still there. 

### WeakAuras Version

Weak Auras 4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1)Enable Masque Classic 
2)Create A new weak Aura 
3) Enable in display all options except show "Edge" and blizzard cooldown reduction 
4)Add a %p text for the progress timer
5)Create a spell trigger for Immolation Aura cooldown track.
6)On extra options tick show GCD
7)Show "always"
8)Create these conditions 

Condition 1
   If Trigger 1 
   On cooldown     True
   then 
   Desaturate      (ticked box)
Condition 2
   If trigger 1
   Total duration    <    2
   Then 
   1.Text Visibility   (unticked box)

### Export String

!WA:2!1rvZUToru4Rv0vGmsO7nffDVviuPav07IcuH6k2exsA7LstKD6Txwa2JThBpuNzgMzC(PWgYQUopcz9DvwZQ(emkING(iuEb4m2j9heTlAMZ4ZpFFFZ5CSAxVF946Xx(zZirmQhRqeH)4NSavOYyIoCfHrL2IXDssKy1FznhrJGp0LrOQW9BDsVwUlIyS8y2qQ3qchhC1kZwXP4mhtwdMOeK0uSq(HBjwE8YgUkbk6ChOsS5fsSpHoa8aNTiftXcsKxgByh6mj8tZ8HOXsNckrfYZrJXIYimFknkoyIXidrJdMfJdlss6nMJfh264UTp9yhfy4k548CEDJJOqjteEigL)JSyCW1YIq8amv5bbsgn3F)ME989610T3135EPR8NBU4bWlWTmw(l3FjR3ORGLkWs5gFPNPMBZxZeeEeks5xIItq9bskG67TY8MJ63NLJmI9gnleOfLSB1xdMuE8OyP9TGTRadG11RBRJp2LcojTlvbJefm1CQuDdMEBwErT)jBAbDP8BZFoaiYaCVkBd)E3tUbEvXckk)nWlbaMZV5CmM3eYrKY1aVSPsCEs5RV(PGylrkaUkC2mayU4ut3YRAOBSamdH6Nkyf04lxNxxHhb8pdbA0BRAMSMwEN5FB(fC(lV1YpHj6Ju(8LhCvK(44RRYWQY7080ED4RvEPPfc8JeDgjwL50emVPkrKr44Yl)t(N))KFtI9ZXPOOX(j5mMi7Qsh(1cPIKmgOOGPa61dU05KoN0I)Ppww4cCeXOz1wunISIL6gcqmmrWF29eH9z5mXRTSSQnR82Os7AWFtxMDORATMdqu1birmEdhO)ANE9AZ)Khdcvwwl16ku8tvO4dQ41aaHH54GfLwdzI4Zei(KZwEyXTvUCaQZP9o(iGZp7E5B5tpFJhde9zX(MoIGh8KVegw3vbpYf4T5B)yPjEm0utI8vzWSugqDRfpGqwHzysAM6aNCgkUDOcLdtfnC7xKRi2oMo2g63y7gLJKsZjhjuqZHzIY2udd1V)UfK45KbV(GV5Id7k(TFykIs6xohUNRuHeQ2xHrsSNsGPPQS3t3WHYO4fXMUEWlFZYfyPfSKlwoX4AzEdC6Ji02AFiaDGgPd1r6GWecLiZ(VxpNqR4oKpBNlyS(wcZSjmkTN(xS1yBhioLn)JwTz10o(9ejcEkHvEkw0GQX1xyf8ZBsIV(OhSmX9UwR5jcytaWgKcvZDOzW40YLIR2EbRbCnJZHaHsiP2ILlLdUPs9BBI3qXqV9DB16exuopdvBMH)Ksi)QTCJYWrNVN2U2KbibXGYzm6Qk4oaLxGRjIG91Py56BPViycxWazunw)vBPh2gIupAYkjEtgV(3PVO(U6FF9g6)GxhMM2z3DUF)8KvctGyuv7X7EADP73UZxVZU1h83V9Fp

**Comment by InfusOnWoW** [comment]
I checkecd with all the masque skinds that ship with masque. None of them were broken. But none of them looked like the screenshot you posted on discord, so it's likely a bug in the specific masque skin you chose.

Or since, your WA options interface was skinned in the screenshot a bug in whatever evil addon is skinning weakauras.

**Comment by InfusOnWoW** [comment]
Which skin are you using? Make a screenshot of your settings screen.
