### ISSUE TITLE
Major stuttering

### ISSUE THREAD

**Issue by Luthaniel** [WeakAuras/WeakAuras2#3680]
### Description

I am using WeakAuras with ElvUi.  The issue is that the game stutters / causes my entire system to stutter. 

The issue appears when three things a true: 

1. WeakAuras is on
2. ElvUi is on
3. I have two instances of WoW running, and logged in game (as opposed to character select). 

Upon these things being true, the stutter persists until I exit out of WoW on both characters.  The stutter persists even if I disable both WeakAuras and ElvUi in game after loading in on both characters.

When either ElvUi is disabled, or WeakAuras is disabled upon log in I do not experience the stutter.

The stutter caused is a system wide stutter i.e. if I alt tab to browser, the browser will stutter. 

The stutter occurs at a consistent interval (for every 1 second of stutter, I will have 1 second of smooth operation). 

The stutter occurs regardless of whether the particular character has any WeakAuras loaded.  

### WeakAuras Version

Weakauras 4.0.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No log - I have error reporting enabled but nothing shows up. 

### Reproduction Steps

1. Have ElvUi enabled
2. Have WeakAuras enabled
3. Log into the game on character 1
4. Log into the game on character 2

**Comment by mrbuds** [comment]
It's an issue on elvui side they should solve with next release
