### ISSUE TITLE
Parallel Ephemeral Weapon Enchants (oils etc) with Chest Reinforcement (Heavy Desolate Armor Kit) Under Items

### ISSUE THREAD

**Issue by mltco78dhs** [WeakAuras/WeakAuras2#3685]
I'm attempting to set up reminders on my Tank (Prot Warrior) and "you forgot something" warnings and I've got everything done except application of the Heavy Desolate Armor Kit. While weapons (both main and offhand) have a selection for application of ephemeral (expiring) oils, there is no parallel for Armor Kit applications on Chest pieces (slot 5).

It would be very helpful if you would either expand (and rename) "Weapon Enchant / Fishing Lure" or add a new category of "Chest Reinforcement" to include ephemeral slot buff applications to Chest Armor (there may be more to this than just Armor Kits - a broader, more general case change may be appropriate).

Ideally a selectable trigger could be created for the absence of/presence of reinforced armor with the amount of the reinforcement and the remaining duration will be made available.

I discovered a Weak Aura that does this but does much more that I don't need (like creating a virtual macro and attaching it to the displayed aura). The code looks as if it could be adapted for this without too much trouble. My issue in using it as is is that I'd have to repeat it as I need both a per-item reminder and a "one of your buffs is missing" reminder (which would aggregate all of the ones I'm looking for into a text warning on screen) and I don't think it would be very efficient to repeat this code in multiple places. The WA I looked at was this one: https://wago.io/-qB-64pD6/4

Spaten said when I asked for the link to this page that "There won't be a trigger for the chest enchant". If he's able to summarily dismiss this, then I guess this is dead on arrival, but I don't see the difference between being able to detect ephemeral weapon enchants and ephemeral chest reinforcement from a player functionality point of view and it seems odd to include one but not the other. From a player functionality perspective they're identical - long-term buffs to gear that need to be in place under certain circumstances. It seems completely reasonable to add this. I don't know why Spaten would be so adamant that it won't be added.

**Comment by InfusOnWoW** [comment]
There's no useable api for armor kits. Complain to Blizzard.

**Comment by mltco78dhs** [comment]
Did you even look at that Aura? It manages it by scanning for the text in the rollover data attached to the item itself.

Honestly this feels vindictive because you guys really don't seem to like ANYTHING I say or ask no matter how politely I do so.

Spaten flat out telling me before he'd even read the request that it wouldn't happen is indicative of that.

As much as you guys call me "condescending" when I ask for clarification on things that don't make sense to me, you folks are among the most condescending I've met in WoW.

**Comment by mrbuds** [comment]
> Did you even look at that Aura?

These armor kits items are in the game for about 2 years, issue is well known

> It manages it by scanning for the text in the rollover data attached to the item itself.

Reading tooltip will break on non-english client, and break anytime a new item like this doesn't match pattern, anyway adding support for an information not supplied by API is a chore long term to support, for just one item you found yourself a work around on wago.

> [...] (offtopic & insulting)

If you can't interact without starting drama, please leave our Discord and Github.

**Comment by InfusOnWoW** [comment]
Whatever, life is too short to deal with the bullshit that comes from you. You had your chances, they have run out. Now leave.
