### ISSUE TITLE
cooldown trigger not noticing when cd are reset such as arena

### ISSUE THREAD

**Issue by oldspices** [WeakAuras/WeakAuras2#3686]
### Description

i havea WA that announces in voice when innervate is about to be off of CD (because i often do not notice in arena matches and forget to use it a 2nd time) it says "innervate ready in 30" 6 mins cd, so if i use it at the end of a match, then enter a new match, some minutes into that match i will get the voice 'innervate ready in 30" when i maybe havent even used it yet.

i have maybe made a bandaid by setting it to only load in arena but was told to report it here anyways

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

reset  cd via arena or something

### Export String

!WA:2!LEzxZTXzvC86ObArDgghNu34qMIAceAzsCSKtCtAAl1swUwP(TSsojTyW7QDFKE2Qv7U(zxzB5sGIOTyAskGgEPqN2cIHaLc3Ol6WfqPJ)eCgpmCd35paCr4dq4CE2vswowtAc3yVV98Y58)35)5r9DPb8uo9WJmCIbkpGXagB8yBLxtVKHWXnLJLJ4crIez(iJm8zA47OVct4z6y)qZFOTZ7imyIKHFQB)jTmxFDnHrSCoow(MUI1MRqbpMFF5d(sEJG)N2OiZD)zxUIMGfBYkwwXUm30N1uZwN7iM3X02pFQ0ZMlTs4aYAUo7ZvVOWPIBgDh7dTVdy0m4nb7V(6RVikE6AwSiIQHRPqt3h3NEJP45Rj8JM0020pA(c4)84rR5lmlwedLdFCr4LVzddw(kfkKRQltmv6PNFYfMoPpEJIwfHwIAEUmlRmgEr32RsE2kmB)S4xBUwZLsnE2ClLn34k5swbxK8UwAvzcfBTYmVOkYpn)umnlFE7HoVGHdvj78PNE66vSd3crBiyfXnnTfuKH7MbHzqm9fcd6m24nrQ7XSkitwWdFutd3dnUTTtfBDwmdrftJyPqrWWzvBVKwoAgtM0dtIdQuUcQmrtIbJ(GWWrv0T088ORY7JPpBF6YMfe4wpRVqZxlYTcuLjPhr7R8ztPKo9SBPvXhF8CUYKC0e4k2m9QV4LTMj3QjJpYTWTftyRzDPaCPudmYvKbNx06A2ML1ObogmWKWqjTDSzBY08O1Kzx0N)GBzG5C6lwIuaHhdLDdVA03qBc48jlRzAJJfop8mpi8SWZbFd8YdU7N0GgNzWESPPDbhrWchnp(IcMfJoG(RSXjAyI3L1PIqNDKhi)QAfDYmr9eILm9YT8fQc9p1NESB)FV9TV9TGOWdVLEyIn7QMUmv3(1R457uohBn)fCn08ris(VevewUdX99D9E6tDkAsh205uPsL(fUO1LJRKKwtv4r(IhhgCJJPGjB9sjXKQJie0usK4SXtuRvIiXOJnsndMN)ceIHiDrMFDbJsdM2fh403QIhBjpzmmPLwrpED58mlkBp0XEu4iBfIPlG7GSzHh3DOwasS5foffmpVyprwAipP7bO5ITgwbTu7jrTPCbc2B8KeCRGf82gB3zHPTM6M09T2O860DYGtT5o2DjNX0MTvrMntyQNL7S6C2B7j)xRDfCm4R42)UcQr5BrpX1zvMGado8OWH2wYWMfm1dKwrfBznMIVzzMH7aTtsl5GOKgMHp6Z8SY5P9BuHHuKHgel6wcSun7oYDB1oWL5b4lfTg9eQux1D)0LDfhQWJbF5gDsi4nKTsWl3miihh9MwHbF1OU7xtEzUadGzCmyrGZw6wLym3XPIuFfkO4WxhE4Kysv39SAHL5EXQIRrmsanTX1FfK5IPBG3eBfht0g4KX01SJLNfJHvamdrOZDe4ChEqyOTWcsYLNSzSnYZzMf5(rGt8XYGJml4bCGzrBhbJcDfmXuMdJC88EyoZIPmHYczManmKISufuHtEC4QkOXUTgm8K1W0nkbR4QcVMAd5nYxPMq(S4KBdCk6VnmmrZuD0DQAW0PzHPf1TmTr7BmAL(arfRJofOh8(YhKFZBw21r4dpT0ibl7PQ)wMbp)D8KdU7NuRvTmhoom9MTUJAqXX2bEA(u1hIzF(PEE9)9QFWTV97bPgeB2rGwCU7bBncQ6FctpT8wmdomkCA3bWGOflJYkkJm18ESYOkOeh71osY1DCk3hmRkebBMso4932bpPMhpwQju0SC5ArGeruw10WNhb2pgO3uy4SKLJJlsFyhgpTIy2X3BjPQhPb(YWNQUzRxtLJOJNG5VUi8z3sUgiRBuLqMtxdhNhHc82JIs5jYLlRI85UNpd5PxqtNT44ggOJ6IxMPvACmd5T48ufP8YzqAtBXS0i8wuRiIxd7uSyDC2d8j5BkNnS2ZLP53hCWXG3DFW7WH3JdhyqObhgR5tLPIvYINZA6zoNW0M4wg2603uVu1jcTd5WzoCbyO8(4KBXsuIvfUb2BSGgsqCyXAbnMIfxGYWeyDdh(5rGXJcjh09qbeDyRR0KvrAHa9Dvv0BDCN(24eWeh5bG0WKble8hGpKd)r4gWhHtp8NOPR7(cWlOctbzGRXduj4xOc)YiW7Oc)k4xdVR7JKPDvA7S(OJqH9VRpkS)nWVfEF4dctc7mTe2JaMbMfMdMhEf0)cYc5GfokobxIdx(Hw()ahbUc84WlbVSk8nPT43c(2QWsCqvf0G8GoyGMBaYYfKUMqjvGdMKzfGLIfJccWdktZKn5XboQWfbfYggwg)MHal0Vc8j7jOI0qcUjhwl0obQcRtUhWRYHVdpOMgE9OWpCFW3RvH(BgfEdv0(aUk8DP7jRc41qBc47t(dqnv4hOcBa)iuLG)SkvscxaEXWQ7D1Q)5V7n)3zv7ynZx6IlpZQJxkZc(WplcPFjIa)fPyd17Qo8WTQdfXMdDx7OBPMa(jWpf(XQufo82C0laUbh(9C46CyfyvcWElomT6Eqpe68HbOZhX7n9qX70TowWrBl5Ksiv8bIhi4JhVTG3l1MuU7qULSdk2KCI4q5TNL84yFnVyVaw862r7DL9XKspbgFgL(aHUJe)69sLpvlIaPdekqKbjfs6Xm5BjDJPcPq5jin)2sJvk7tIq3s2(BBDkddSp4of)2Y9ynFYNyTfsNAuTQx5CKUTxvQndMczrkv(rfLuXzdzL6D6xD)28jWoIaDeDU)9B6bXG6xaWC6aGz(03vGH07oadrieXqOxjPbbbuLRFznrSSOr(oyfjuH0uVGLRFhWY)QlFcu6JhAyKepQiBq4Q5ZH)QlMT8Wi0Ju7Wk3Bgi33MhxlOKESMLN6cI4vJFfXtKHyiuiqEAh0fYLeq2cfhSnk2otfJ4rKwdnoQ3xhJJqcFp7y0FWGvA3J(ZsZIalOBYV)TGUgVdpTxnDAtug3t9CiWi0ecztIUikJyUY0u1PPZrJps7Uoi1D3HPn2p8xvLhAKo4VGCt22cVYQZb(FUNLGNpgbRAZsh0nTvbf5NC0NkEpWOxn43Ui)korFT7P1baFJwT2cnVcLrE3n(ZY1WtbwMzzSlTu6S4(KDDUQ5WZvnpUPp5OdpsRJrLb)HR0PO6PfuOJ5n))WmkGir0m0JfX1Ec27iG62OTD5XynFzB3uRDo2cz8wM4CYLkK17HT39cmkzKGtan8zcOXx6iFwOXU7jI0v7EIiAsek1tKMR9Qp4Upc09T1c5RSBgUFIHqtX)wlK6tB5og0EKWxI7(ey4bHprAh2fk(pis(VtGEVDfdfGoMJxNVNil(BdeL8kHyAaVUtFNn7HVtxN1kXORPXUs6kv9uKkFauG0r3DTp4o(bpHlyVpIvpBlEZwMEO7WaR8pVY)7d

**Comment by mrbuds** [comment]
I tried make multiple auras like that with various remaining time set for testing, did tests on skirmish on ptr, everything worked as expected, cooldowns reset when they should, action>on show never happened when it should not.

Will need to know step by step exact actions i'll have to do to reproduce, "reset cd via arena or something" was not enough precise.

**Comment by InfusOnWoW** [comment]
Also sorry for the later response, we missed a timely response.

The other reason for not being able to reproduce the issue, would be some kind of lua error. I'll paste our canned response to that, below. 

It sounds like you might be having an error. Follow these steps:
1. Install https://www.curseforge.com/wow/addons/bugsack
2. Install https://www.curseforge.com/wow/addons/bug-grabber
3. Try to do whatever it is you're having a problem with again:
4. Check your minimap for an icon that looks like a bag.  Is it green, or is it red?
    • GREEN
      • You have no lua errors from your addons.
      • WeakAuras is working correctly.
      • Either you found a behavioral bug, or you are just doing it wrong :)
      • Explain the steps you took, and we will try to figure out what happened.
   • RED 
     • You have an error with an addon, maybe not WeakAuras.
     • Make sure you clear the bugs once by alt + click the bugsack, to turn it green, then try to replicate the problem again.
          • You may also want to disable all other addons while you test this
     • There are error messages. Click on the red bag to see them.
     • Copy all of the error messages (there may be more than one, click the 'previous' button on the dialog to see previous ones
     • Paste the error messages into https://pastebin.com/ and click "Create New Paste"
     • You will be redirected to the new Pastebin that you just created. Copy the URL and share it with us, and we will be able to give you more specific advice.
