### ISSUE TITLE
Advanced Caster's Target Check wrong target

### ISSUE THREAD

**Issue by Tems91** [WeakAuras/WeakAuras2#3687]
### Description

Hello,

Using the new WA v4.0 feature of Advanced Caster's Target Check for Eredar Twins' Conflagration cast. The WAs purpose is to detect who the boss casts Conflagration on, while a condition pushes a /say message when it's on the target to make it more noticeable to move out.

The issue happens when the tank of the casting boss has the WA, then the WA signals the tank as the conflag target for them on every cast and pushes the /say message as well.

### WeakAuras Version

WeakAuras 4.0.2-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

This is a widely used pack, so the problem was reported and reproduced by having the player tanking the boss(Conflagration caster) use the WA. It was also reproduced with other spells than Conflagration.

### Export String

!WA:2!nAv3UTXXv4sRc4aHIclMegxJMG1cOcUbi0vsXsbPXTDxkszPsrYUCPLvQaiND3HCNOLZoDMH6hBKlmVivn9IcWhbI2IIcxGwc0471tWaII(a4hbDtVTNz2LskXoULaKCMZC(97CMZzYvjF)8H5dp99htcsOntgWdW54hxVBxbwMBCWaHmPVh(yj7)0DanqssO35hpVf8H01Axm6a7bCKO4wI6m9zWFyGblzeMAXXYbCQfMgotaAI0cbc0gtpSymsiTs4FdcFI1MyPhPpg0YhyTCX7z0Lrb6pFDMV)LmFbhnb7vkcj3bleOE47S4tE0NB52QML9U27zbBweu8haohlgfG1A3QFkRwiHffJdXP(R2VHV8tYaJjiAqucVrcHk9lvUMxz3PbjjXHjhrBEeHH7WUXL4vlwisI9hy(7Sz8voShUJJgQ7muYj96H5IAlXZwEAEUGHJJ3k8n(hVhBHbcCB8XOaz7mQDgQjnGsKDggIfYwWkFimobZhhc2QBxVtyy(dkxTrLwvDKWghn3VqmWhFiMkBcSqoEs7s2n9A30Z21ZLIGOFEwbTMtOPETwVEiEpSSZK0iQDeje7kbKou9oJ0YaMvINOLAMZLAcbRyP674y71UA9nBx(Hao1UvTkBvfGRYByzSC9AT3RER2TASHTx5zwq7TtesqRPyMRrDoLG88zAZmlGJUiAAWXq042Sr5QvhM5fI5hnGMbNZpjKi(mtv7H4vqXXSfqM1EPNVtsi(zFNZH0jMtrXpeYfqj8bNFagZSb9fiDrqrD0iboURjTRUoGZceuwdoye)WujU9yWJCX901)BxqvykS1hfCqpEYaA4PVllVekiAlIqqjWJYQMy)adrZpDt49radzlCOju8OloMvOu9AvQAVPv9Aw)OLlQbIA6mW7)sA4YdBJ8954djGF2Up64fy3(1XCqsCcVZlsDZzbRJDlV6S30qenasrayeSljug5ydBzwVKgrD7cGgomBVA9PPxz2llMpZW8Nb5Bs3taSKNOt36Blo1QxRm7wVcF8cDXw6)VWnIDJRa3L0r225YLBovboKxma6l752vQuUKx5nUWAJnNAWLTNd(mkJBQK922bbWTbQefBbLGc96GtE9UhhJI73wFVXLc1U8SsIxf8Cirq8JXDMA2DucpCxoInC3SftVWrm31R3YR6wa0DJROpt2BeCsz32E1BCEQeKJXHMS3t)A1JZm(L6Tj5X4BNL5UOADXxx0Lv2QVDE67QUxo1AQ1vF0lUszlCDxTzAA4N2r9jQ7R(zQFU6xaSvjs5OUUQKAdvzy7VwTV6Jxqvq9a1wW2TnGV6xQQQ2rvtvpN6r5u)kLRQPYt1s9q1Upv1isT3TvFAoLDU)90EXjhvHJ)nd05KgF3FsXvUxAIxFGUpYMXzffrd1K0G4u)bszcToKxGEPJ1KRIP9KrV9e96zi0OEZe14uo6TrgoMHsgR7frcoGctuMZiqZaumoDzvcqEbJ(DGSjMh5hHj9IKp1jobf(vJ0T5mLhropgAbWERMqLIUNAehe1QecoI6O7mvWT)Gyjz(ZnZiObqJgOjgjBcHw4iU(xOH4kRU69MmJkSVJpu4ckTGIpVBamgvSKVGq7fJ57A76UvDxfFj)gUBvUPxh1t6m5kQFL1xzDhbuFacxyiK2LN0hr7mfApaflzpby(XCtVqn0Q(Eti00YdGsb2nj9OjCCgNL1DXlZ5jCrhDVA9OSTGzJ38A5)YrikjvQ1CHPcCzfOOy9ZWibUPKBspxFAOUrmWIz4bxGbzdfd18ym(6o9re6d1cQ(9W3tVUpdUWIHbImchfJOHSbXcS63P(s)UekrezScWOMKwgFqLDj9MN9wZgHRBxTbrGG7OHrUhLDJca4szmaJvG5gWy(hNK0pNJU1z0yzsq20I3OXnxKeYUL3reQaEItjWaXOEPbILECNVa3hy2D5IRwCzxumlcn35P3hRWH7B6yZVzj3YLRnPRMaaiijAUvgqcNS5bEu)vxRmX2gkA02ehTYaEm7hgjLmXhF37EeQxsrsYD3yBu3gFuL1BE3LxJJmpTtSM63(f8SNdDTZYwyq3vAAV3lMriDKn7ox(KWzp2t3dq3t4olM(Ue4XwWBOggM0wOhggXENz6iRnsWLTCbMYomY1WnB1T01DDH3PTVDyyDQy)lEY5(7GdjO9BQ5tSVnH)GeoTysVECqnXjjSi1FyEhiNkxYp1DV2i4K0LrJ1vketiFRLCdIWbhur99NB4HiorNzv5xmHT49VV7HO4by1BYdIq0EyXNwyiJNa1AaKKh6QuCLIxTP9sQ)zh1Ztpz1xXj6hku8dlQ7aae(c1FKz9eUC9p36Qt4hKbHPhXEVVbGn74z42(Q)U6VWw8BJRlN8a9p)RWy0VvoV6i0L(FZK5zfQ)K6pREUdGosiGwBSjTzQxCAa5F1Zu)TPP00aifh7VduGJ5QNRE2Wz3O64E5C28c3pSi01o)H)Rh9Fp

**Comment by mrbuds** [comment]
Does boss target tank when it start casting? If yes then behavior matches what is expected from your aura (it is not a bug in addon).

**Comment by mrbuds** [comment]
In any case, we don't have enough information to know if it's a bug or not. I can reopen ticket if you have an event log showing issue is from weakauras and not your settings.

**Comment by Tems91** [comment]
Yes probably, but I thought that option was to avoid such issue with detecting who's the target of a spell

**Comment by Tems91** [comment]
> In any case, we don't have enough information to know if it's a bug or not. I can reopen ticket if you have an event log showing issue is from weakauras and not your settings.

There's a vod of Laty having the issue (https://www.twitch.tv/videos/1509269221?t=02h20m30s)
