### ISSUE TITLE
Add Spell Action Overlay textures from retail into Weakauras for Classic

### ISSUE THREAD

**Issue by caccavale** [WeakAuras/WeakAuras2#3691]
Hey all, thanks so much for maintaining Weakauras for classic.  

I was hoping you could add the spellactionoverlay textures from retail into the classic distribution so that folks could easily use these.  I see these being requested often in class discords as we're moving into WotLK classic: getting DKs and more modern rotations that people associate with these textures.  I use several of these textures currently and its quite a pain point getting folks to download a zip and drop it in their wow folder even when I set it up as simply as possible.  It would be really nice to have these 🙂 

Link to retail current spellactionoverlays: https://wow.tools/files/#search=textures%2Fspellactivationoverlays&page=1&sort=1&desc=asc

**Comment by caccavale** [comment]
I'd be happy to PR these as a change if instruction is provided on directory structure.

**Comment by InfusOnWoW** [comment]
We obviously can't distribute blizzard files with our addon. You'd have to ask blizzard.
