### ISSUE TITLE
Can't use quick advertisement report feature in LFG due to WeakAuras

### ISSUE THREAD

**Issue by toffi23** [WeakAuras/WeakAuras2#3693]
### Description

Recently the option to quickly report advertisement groups was reintroduced in the ingame LFG system. I can't use it because when I try, I receive a popup that WeakAuras tried to perform an action that is only available to Blizzard UI. I get the issue both when I only disable WA or only keep WA enabled. When I disable all of my addons, it works.

### WeakAuras Version

WeakAuras 4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Go to LFG tool, Premade Groups/Dungeons
2. Find an advertiser group
3. Right click -> Report Advertisement.

Expected: group is reported and hidden
Actual: Error popup, group is not reported, not hidden.

### Screenshots

![kép](https://user-images.githubusercontent.com/10179556/178112676-552923b5-df1a-4068-b99b-878fd2504c12.png)

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/9077459/WeakAuras.zip)

**Comment by mrbuds** [comment]
This is not a problem with WeakAuras but with with a custom aura you have installed called "Dungeon RIO and Class".
