### ISSUE TITLE
Weakauras TBC Classic Nameplate Aura Glow Bug

### ISSUE THREAD

**Issue by Moki182** [WeakAuras/WeakAuras2#3695]
### Description

I have found a nameplate aura glow glitch in the last update of WA TBC.
First I thought it was Lose Control, but I went back with one version on WA and everything was all right.

So this is the Broken version: 4.0.2-bcc
This was flawless: 4.0.1-bcc or rather say this one 4.0.-bcc

but what is the bug?

Well I have a lot of nameplate auras with time-glowed feature
and this version will mix them up for some reason.
Ohh and the bug only occurs after playing like 10-30 minutes.
I use a lot of addons (aprox 100)
and when I disabled a lot of them it happened less often.
(doesnt matter which addons)
Maybe its affected by memory usage?

What I mean by time-glowed?
So for example when the Sunder Armor debuff reach a certain time
it will light up that aura (to tell me I need to refresh it)

I made a picture how the actual bug look.
![bug](https://user-images.githubusercontent.com/84582380/178311561-c4a882c7-62ac-44f0-9908-cf070694e89f.jpg)
Right side is with 4.0.2-bcc

So you'll have to search what you guys did between these two patches with nameplate glows.

My Weak Aura Files
https://up2store.de/TQ4HW4KY02S5/WA.rar.html

These three are I have problem with:
![image](https://user-images.githubusercontent.com/84582380/178493172-3a785ed4-fd52-40a7-88e4-862eb888e702.png)

[WA.zip](https://github.com/WeakAuras/WeakAuras2/files/9093020/WA.zip)

### WeakAuras Version

4.0.2-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

I cant reproduce
it is doing itself whenever it wants.

### Last Good Version

4.0.0.-bcc

**Comment by InfusOnWoW** [comment]
Obviously we need the aura.

**Comment by mrbuds** [comment]
I noticed some wrong anchors, 

`General - Nameplate - PvP - Major CD Buffs - Nameplate (Méret Scalelös) ` => Wrong anchor, don't anchor to "WeakAuras:Nameplate Point Anchor"
`General - Nameplate - PvP - Interrupts felirat a Nameplaten` => Wrong anchor, remove custom code, use built-in options, replace "PassUnit" with "unit" in trigger

but your file have way too much (horrible) custom auras to audit what goes wrong, we need you to check if you can replicate with only those 3 auras, and steps to reproduce

**Comment by InfusOnWoW** [comment]
Ah sorry I didn't see that you included the aura. Nevertheless we need some smaller reproducable example to investigate and clearer instructions on how to reproduce.

**Comment by Moki182** [comment]
> Ah sorry I didn't see that you included the aura. Nevertheless we need some smaller reproducable example to investigate and clearer instructions on how to reproduce.

I don't know how to reproduce this bug, it is happening in random times.

But anyway this WA work flawless with the 4.0.0 version
Isnt it possible to check whats the difference between 4.0.0 and 4.0.2 and figure out that way the problem?

also how can I help you to fix it?
