### ISSUE TITLE
auras dont stop asking to be installed even after they have

### ISSUE THREAD

**Issue by n0t49a1n** [WeakAuras/WeakAuras2#3714]
### Description

after importing a wa from app they sit in wa as click to import, i have already done so and offers import as copy but i cannot remove the waiting duplicate imports

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

install via app 
reload ingame
/wa
click install
and they dont remove

### Screenshots

![Screenshot 2022-07-26 130404](https://user-images.githubusercontent.com/87333/180914291-d3f2e16c-71d9-4486-9440-2834e331f808.png)

**Comment by mrbuds** [comment]
You didn't mention which app you use, but you need make this app stop sending this aura.

**Comment by n0t49a1n** [comment]
but when you add another from app it clears them and then the new one is stuck

**Comment by n0t49a1n** [comment]
> You didn't mention which app you use, but you need make this app stop sending this aura.

wago app

**Comment by mrbuds** [comment]
It's a problem with wago app then.

**Comment by n0t49a1n** [comment]
please delete this
