### ISSUE TITLE
Alot of models don't loop anymore

### ISSUE THREAD

**Issue by Bowny1** [WeakAuras/WeakAuras2#3717]
### Description

I noticed many models don't loop anymore. I tested 3 models between 4.0.2classic and 4.0.2bcc version.

1a: https://streamable.com/r0vysp
1b: https://streamable.com/z3npuw

2a: https://streamable.com/hungc9
2b: https://streamable.com/kgrw7h

3a: https://streamable.com/e9t70j
3b: https://streamable.com/qlund3

There are many more models that don't loop in the latest version of BCC anymore. I am certainly sure the same issue is occuring on the Wotlk Beta version - but sadly I cannot access the model viewer in WeakAuras because I am getting LUA errors. (see my 1st bug report #3716)

### WeakAuras Version

WeakAuras 4.0.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. open WA
2. create model
3. pick same model for BCC Classic and Classic
4. compare animation

**Comment by mrbuds** [comment]
Can you add to the ticket an export of an aura? "many models" is not precise enough.

**Comment by Bowny1** [comment]
!WA:2!Dn1ZUnnmCyI6bMcd0OtAG40GdCS0vn6zAkTSIkDf3maXLiN4FjXSe7GTtxBpwnH48Ee6zo1hH9eevXtWepb7jaN)G2yN8pB9ZF)((83Nn6xpUoPo5NnxhZjq0a5jmQk8kxUGaclS3PebpjzhRi6IfybzFBopsrtAHtOHIzh77lbLHyEvXAmZlKlgZPmLB3EJS7Hef46mZyDjMD5rCX7RvR24AnB8Ab2tr5mzBKuHfktxFkJkdnT0lkZLkbniaeYh9srv5pwra3uFF75jG4OEdh3)KHwk9geovGBTuMarrdisZRKPUWuGPMO7MoBTt3otSDMy3bzBLQb3njcpheigogKMOIwDpcWrA1)VRowa6RIMmU3WHxKYQOGzYJZz9uWUC)h0c8x37ATKbbdh9jnF1s60llfUpncgqCpOD7dB1Cv5zjyvyY(fuv(kkJbcboaCOXjAGD8cbPQrCRshXrQCuZnwk4kC(tLXToEMXknvrqq(t4Z2lB3n6TUAtlqWtze3qGgeQoFBRioM03vHJ0IApuCQ2cnT0Z3BVSgMiViSuMxzjPlG8IwPuY6dinHV9UVY)C8WnUvjH)39wkHVNcmpOgs6PbVMBPhhUQCThjaSgXzWkrbhZnnub9RAyIEEp)gbLk)4nBelmUaZOXfQUD229VeWsyIsaSav49Z21IPrEdrB75D4KhcesWJZiYL5TMpTSowXykRF2B0xiRtMvw3S3QxF4DpznL5ZfLdZ8cje5xeIZ2AdovPJ0hNuKtnVf)MBCzPkkd)pyLI7nT083A8tFbL0AeCwv8FUXAFHoPPPpwHRDD5)K(5hLtt3jDr96nQ6lYaMgUN4QvIpnWeDgLOcpF7Bn5z)zNkCxySkxW07so1cdbMmvpgiSUeDyJMnAvF6V)YF)d

Model: spells/innerrage_impact_chest.m2
Created in BCC

**Comment by mrbuds** [comment]
It's not a problem in WeakAuras, model is not same between classic & tbc

```Lua
local f = CreateFrame("PlayerModel")
f:SetSize(50, 50)
f:SetPoint("CENTER", UIParent)
f:SetModel("spells/innerrage_impact_chest.m2")
f:Show()
```

Animation is different between versions of the game, we can't do anything about it.

**Comment by Bowny1** [comment]
I compared the model between all version available on wow.tools and it looks like they are all the same. All of them loop.
https://wow.tools/mv/?buildconfig=fbf8a2348df9e3747bbbc0190e26d437&cdnconfig=2d24014fcbe70a028728621d3c8a3ccf&filedataid=166420&type=m2
