### ISSUE TITLE
weak aura not working on a one character

### ISSUE THREAD

**Issue by jde-beer** [WeakAuras/WeakAuras2#3721]
### Description

after importing one weak aura my weak auras icon doesn't show nor can I access it via /wa or /weakauras

### WeakAuras Version

3.2.3

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: [string "--[==[ Error in 'Death Strike':'condition c..."]:80: attempt to call method 'SetGlowType' (a nil value)
[string "--[==[ Error in 'Death Strike':'condition c..."]:80: in function `?'
Interface\AddOns\WeakAuras\Conditions.lua:649: in function `RunConditions'
Interface\AddOns\WeakAuras\WeakAuras.lua:3643: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3609>
Interface\AddOns\WeakAuras\WeakAuras.lua:3725: in function `UpdatedTriggerState'
Interface\AddOns\WeakAuras\GenericTrigger.lua:833: in function `ScanWithFakeEvent'
Interface\AddOns\WeakAuras\GenericTrigger.lua:1092: in function `LoadDisplays'
Interface\AddOns\WeakAuras\WeakAuras.lua:1399: in function `LoadDisplays'
Interface\AddOns\WeakAuras\WeakAuras.lua:1244: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1181>
Interface\AddOns\WeakAuras\WeakAuras.lua:1383: in function `Resume'
Interface\AddOns\WeakAuras\WeakAuras.lua:929: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:892>

Time: 07/30/22 16:42:50
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:1027: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:979>

Locals: self = <unnamed> {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 lastArchiveClear = 1633106014
 minimap = <table> {
 }
 lastUpgrade = 1634407998
 dbVersion = 44
 login_squelch_time = 10
 registered = <table> {
 }
 frame = <table> {
 }
 editor_theme = "Monokai"
}
Private = <table> {
 HandleGlowAction = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2843
 frame_strata_types = <table> {
 }
 combat_event_type = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2176
 UIDtoID = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1460
 IsEnvironmentInitialized = <function> defined @Interface\AddOns\WeakAuras\AuraEnvironment.lua:162
 form_types = <table> {
 }
 CleanArchive = <function> defined @Interface\AddOns\WeakAuras\History.lua:21
 RunConditions = <function> defined @Interface\AddOns\WeakAuras\Conditions.lua:646
 tooltip_count = <table> {
 }
 IsAuraActive = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:4122
 ReplaceLocalizedRaidMarkers = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:4557
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 autoeventend_types = <table> {
 }
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 FinishLoadUnload = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1444
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:135
 array_entry_name_types = <table> {
 }
 RegisterLoadEvents = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1313
 FixGroupChildrenOrderForGroup = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:3282
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 CheckSpellCooldown = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2065
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:1661
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:2233
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @Interface\AddOns\WeakAuras\WeakAuras.lua:2968
 NeedToRepairDatabase = <function> defined @Interface\A

### Reproduction Steps

typing /wa and nothing showing

**Comment by mrbuds** [comment]
WeakAuras 3.2.3? Is it a private server version?

**Comment by jde-beer** [comment]
> 

yes its on warmane

**Comment by jde-beer** [comment]
it was working until I tried to delete a imported weakaura

**Comment by mrbuds** [comment]
We don't do support for private servers versions, you will have to contact who made it.
