### ISSUE TITLE
GenericTrigger.lua error

### ISSUE THREAD

**Issue by imarkvisser** [WeakAuras/WeakAuras2#3723]
### Description

```
5x [string "Error in: Bosses"]:54: attempt to concatenate field 'MS' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:548: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:747: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:854: in function <WeakAuras\GenericTrigger.lua:839>
```

Is this from the weakaura addon itself? Or from an imported weakaura?

Thanks.

### WeakAuras Version

Weakauras 4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Get into an M+ fight.

**Comment by mrbuds** [comment]
> Is this from the weakaura addon itself? Or from an imported weakaura?
> ### Export String
> 
> _No response_

If aura doesn't have custom code it's weakauras fault, if it does then it's most probably aura's fault, but you forgot to include said aura

**Comment by imarkvisser** [comment]
How do I figure out which aura is supposed to be the problem? This just happens during dungeon fights, not during import.

**Comment by InfusOnWoW** [comment]
"Error in: Bosses"

**Comment by mrbuds** [comment]
It's unlikely to be an error from addon, we can re-open if you give missing information asked and they show error is not from custom code.
