### ISSUE TITLE
Condition for aura being active in a [smart group - combine matches per unit - show: all] trigger

### ISSUE THREAD

**Issue by BartStam** [WeakAuras/WeakAuras2#3731]
**Is your feature request related to a problem? Please describe.**
Tried to make an aura that shows which Mechagon: Junkyard buffs are active/missing on people. The idea was to show an icon for each buff per unit, and desaturate the inactive ones. However, there currently does not seem to be a condition that allows for this.

**Describe the solution you'd like**
"If aura is active" condition (not trigger active, since in this case the trigger is always active)

**Describe alternatives you've considered**
Some dirty "remaining duration <= 0" condition Reloe suggested, but it didn't even work!

**Additional context**
![image](https://user-images.githubusercontent.com/7372712/184006655-16f6bc4a-80f5-4598-9d1b-badb581ed6a1.png)

That's the idea, with the inactive buffs being desaturated/transparent.

**Comment by BartStam** [comment]
This custom check seems to do the trick.
```lua
function(states)
    return not states[1].active
end
```

**Comment by mrbuds** [comment]
My proposed solution is to use condition `total duration = 0 then desaturate`
```
!WA:2!fw12UTXXz4SyRBCxh7krBRARM0kOGO4MayyldBhe0GcUuK2QLHKzjLKDAt1o7Ud5orl3D9mZskQEuSUPk9myrp30wWR7v8rqpb)GOipa(I(aONG(pZsQy7ErVz5C()W3bASDbX6Bq7vOBHGcbhD9reUFvAChz4Jx6jEj8ak3M4VxapjnDb7i2bhq4bR0kjjsYs57xVDBbvAWhmBWesSFycVrclw6vQCTwLDg3olkQeJ7hrDDePeF6z4eFjljwChhHKWLwETzXmrOLn(J0AOKZ60HYflVgF2WpACa1lRD7wdsP87xUAJkBv1wItCizCY6dfP0OOndewprK5r7rJLnXtZ2FYULk2S1UnBv0PLDg(4EPrKbuUtmPlvy5OpQ39PKiz4PxTbNIx1PzJYvRoklEwkynXpjkRBCtvfy6XjbSmXJFPHzcAvwxMm0HeX6edNLJ1K6cgJXh0H2rvOw2rjKGkEssegGLC6MHTplBmT9xcUMLJFeriuJSfSdOQbt9M11lLeLW)MMMMnmVX1V9qEs)8mGtIzDjsAOJWhFvtVCWkCC(VLd6qtxS5JYiC6kvqeyLDczs6yUoHu9XJdgGDbMFhEsw6SB1eJ(zSfjCPDCsmD9mwWKRTv)gpSCPQ3U0TgjOrT1ylCwmtKefkACcoNYJjrBJygUWEpXhlzjjwwbX5eUNtXn2CRMtjzsKAupvd9whNhXCEZxWdVsBwhRXYe)E5pZvmC)GvzbJqGAff2lM0MJOwtjNijMJ6Wzb7WcKHN7KCoxf1UQcZRzjNYLRnuDc18vD2ysEW2mgJLPnwX9hF)6oB((1R1QyvNif(DUzNjVFByyyogZPawE2oHf3oH3vxWwJYB94W7aVuLJPeHkR0IMxeUiC3PbiPuT9UkkkxqvpKyO6CQ8bURDxclUc8E6tdoqtOf(75F(vk4)gh9QJz4TBMKX9PV8laNXa(8gWlcNDQpkbds6h3SplL6E88PkCp0wDhx4lEH1Gf(pJfHj9lfHWPWLJS1AyBY9eCWU5AQskUxiSe8LMGj7wOi5DtcORtIIGVm8YWvC0eKrkHMw1SSZ63823zD4YwWYwWRaFfeU76XIPnYVTlwcxcwekaFvR0fvk9E0w5Ai1d)VEb4RV3j7rPPfv0FPJQtfcVnCwuJlisvRJgcV2BVeCXPOcsPduzqCWrxkTGKUVCxribl1hmZYj9Q6f1FYXODfZga3D0P7T6Rjsx4PU(NHZpjF15uB7IB1QE6f1lIu2efs7RzA2fXPNKhi2(0C63HtZPFpCw6CSE)pmtizThGfLwMqBHlAxRETYWf5yrPoZy9b9NlVnhnRcILPluHZoyL3lJeO46R0Q1Zu4ZJ0u9A9rw7oCs6WDMnipb6Xemp0XDwn)u2YPlUzTALD21UERw1FxNnV39Bn90qRmaU6Sk6bptCu7QTFRVvRQBwR8NoTtus)kC6JYOX(dA85UX1x)25vNAJjQpZFHHQjQlp1ltktIRJsC0hESA58)S5Y6ZpVYgPMCQXN5Xiz9EZxj0wTzOo6Tcz(7H8AHP(gn1gH6Hvr(OyrDaSZ9f9cPSoHYdH1QaVUYHf(A6VVH(7BQ)El4HWBnHS)3klRA5K9zvHgkf(Zlu36)V0fQBLEP5Asf4Vbtqq8iieoh(KwW5TGlyzFqssxdWEMvNtnA)vw35ZOeWgMo91KS0cypO0S3dLrOQH6cfT4SyLDjkyQa3d)hO0qIjuB51C8dP(7vbwWCypcNPc9W5Uso9irz0c3y1K0vFN3H7hsI7GY61GpXDyk(pouUCaqhop7DHVH1rVkSn6(KB9a74cpyEDCbDPK70aVVl8TDHVJ2mb8C1(hOhH7YREZ7Q8lUcSRYWa(a47(uMeGV2tac0UaWCXp0(OlbDmGqSBYq1l8HA1kShebDHyi5qi1aEeEdoiWJlHS8MwpOpSVbmaoa(EUW3h(bWp8QWpYa(XWHFkmCorf(jWppe(PWhb)SldhzaFC(LFSb8lcHFLj8lnHF9IWVje(TAkZB()qzE9tPmfTWwe8pDHFNHcgGrHWdDFwu9wkN7)Sj8hoe(JUihRuVTFRK4ThG2SWFkeXz43NhFe7G)Ic3G)k83Gpzokb)Dn(a)dGIuRz0sfFdPDpfT85w58p)kf69VFW)9p
```
@BartStam said on discord result is not inconsistent
maybe it's better with `<= 0` instead of `0`, i'm not sure if my solution is correct

**Comment by BartStam** [comment]
Tried Buds' suggestion, this is the result for "total duration <= 0":
![image](https://user-images.githubusercontent.com/7372712/184122269-19b08690-8a9f-455d-b5bd-dba2f12d9809.png)

This is the result for "total duration == 0":
![image](https://user-images.githubusercontent.com/7372712/184122492-32cdfc7f-0172-4532-9115-1c91071d5752.png)

Note that in the above image, the only buff present is Retribution Aura on Naempala. None of the other players have any of the other buffs.

The result is also quite inconsistent, it doesn't always give the same result. Meaning sometimes instead of the last image, it would desaturate everything except Retribution Aura (as it should), but it does it for every single person (even though only I have it active).

**Comment by InfusOnWoW** [comment]
"stacks >= 0" works. 

Strangely enough the state already contains a active property, which is not checkable via Conditions.

Since there'll likely be some rework with the new DF api, I won't add the active property to the condition list atm. I'll keep this in mind when we decide what to do with BT2 in DF.
