### ISSUE TITLE
Group Settings Space Vertically/Horizontally

### ISSUE THREAD

**Issue by phoenix7700** [WeakAuras/WeakAuras2#3734]
### Description

I am unable to set the group setting Space Vertically or Space Hor to 0 after changing it from it's default value of 0 using the sliding bar. Value automatically changes to -1 or 1.

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Select group
2. Change group setting value to anything but 0
3. Attempt to change setting back to 0

**Comment by InfusOnWoW** [comment]
Those settings aren't really settings, but more like actions to layout the group members in a specific way.

I'll make setting them to 0 work, but how they work is kinda suprising.
