### ISSUE TITLE
Listening for a custom event in one trigger and also checking for specific item (count) leads to lua error

### ISSUE THREAD

**Issue by Blumberg1337** [WeakAuras/WeakAuras2#3735]
### Description

I didn't expect the error to happen, but it did.

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

3x Usage: local itemName = C_Item.GetItemNameByID(itemInfo)
[string "@WeakAuras\Prototypes.lua"]:6526: in function <WeakAuras\Prototypes.lua:6525>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:3996: in function `CreateFallbackState'
[string "@WeakAuras\WeakAuras-4.0.2.lua"]:3432: in function <WeakAuras\WeakAuras.lua:3421>
[string "@WeakAuras\WeakAuras-4.0.2.lua"]:4053: in function `UpdatedTriggerState'
[string "@WeakAuras\GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "Error in: Custom Timebased Events Helper"]:8: in function <[string "Error in: Custom Timebased Events Helper"]:8>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

### Reproduction Steps

1. Import the WeakAura-String from this Bug-Report.
2. Open the WA-Options ingame.
3. You see the error happening. (I am using Bugsack.)

### Export String

!WA:2!TJvA0XT11znAKIKhfPirzPirh7dmTTmPLm9OHlswht7qmC4s9WLGzOKTvuMbdWBgatmaqpGHuu(4KJ5X1r)O)I)O)kBESZsttsByZj7RSPPTPXPxZ2QQM4SPS4ShBzN4K040CVpGzJl(ho5h50J1HcdWd339DF339(D)UiYjBZtP3UJ3DI2k3MEB6xqALcQAZOZDCt6y5W)lIgn6urJ3DFUTP5y7ZDSSy6jnmT05m7BXvkzfpFNYsznlZkO6X0LsnlZ23tAuMLlJlLyLKo2EvkRwWI5jL4YfC46mUC4k4UBzlZZFEvUUuwhhlFt3Q(oAZY4EMo2BFQdO4PPAXIUOQTzzvFCS(v88v5(dVmdxRm(OjuY3yBY(Z7YKTDSzROxHlemhne3JH2SU3cK0zXbGDjxw10Ey4vVnyNWUGxdSBypWUku0020ZyndhySg85NSyrpM)tTTLuT1mC4t5yIEIStov6udNTAGuzmppBRROwXhF)KUKj4fBPGxf4hJejsu3DhOGH5QLzIl8XnP9MBvoReohYivkXDQ46UNMeDkvCN6NFbFUzPs42Q9dXdV9rQQZkuPyrAI8rtLEQHNonStfv0nKybpxML1y6EXUSxLcm6CjdkQ55wkxYbZKnxMSdQKvUITPFbxl15zCfBCT8IPieTWOmvlFJ6tDkodNQsMPsLo9IvSdx)y8Zf4CEJBA5GDBWJxvOBjLEjM7EYC2k4oqA4kwwsNYW0NTOhZQOWnwizQjYMsPdtD3BECtppt7ssYOv6jPARl1CWtwog1qHu4Vc)B)WoIb7nMm6b9JTurYrHHeQ(QrVst(oYZSuMuPtLm7WkdoEQRGlkJBRADYGWSzsuXuFP5MBUPp)0A3)Xp3zLTCu1hUGpg5z7VFLYvW4YyYOVuB)WGXu0Su98O7K9WJC6MQOlsrC8v)iFmB0heTkf9zgglyAx0HhefhRa(IIMLI1M29DHUWtBFltB0ZnD20JnrQcUItBO)L0n9OdMSSZ5V5v8mu1DM7EdCVVUnb7h6ZvQjjYfO(CU58XCXWNI4UBnrckjX0U6Q(m4WxgJsDilr7uM6(gYdIpchl0BchpginXHGR)IWolemx4qWndDa3aCy4iWTcDdDcDbzoxK)QB9wL8yy(LKQKF98FrWIKVHQVKMQTubMKLPNpZgFLVtSIvSfhED2vmjjC(sMfLSD8LOa2Cm7z7g9U(soCPry(eMsNDjDRR6L35angiWp2DfXodLNIE8ny2HkxAvtDGgQnMyPR)AY(51MQ0Qg)ejX4jMLys4(n2QFpQ3K5i1Y7Ec2CznPW0oFPSXJi1WpiDkM6mdIc71Dg0HfaF2zhJlNmBUSJnEk5bZKAOCuQDkLCPojMT0rxKvuZbsge(F4MIb3cgDAW0MboCqkRN7Rn9Kdo0ytmsUmjvsLAICdnwMbLtNAOLcozfOKfqiv)kE1gYWuNPqBlD42IrHG3VWuNLLq1EEevsCF2GS)XD0zFGn52Xghgw2rphMsYY7EOnwilwjvT5Zv0YXHBa9wqEYSzNCC5Iy9g3Dpm388sVHkQ6uMTu2SqQ23pSZvWCoQofHvIB(7Q4cv8y5OmsJfP7SrhaQRxpLFcjfxLfxhcV2FcmEmFv)5qF08fXTtEyx5xGwocf)GUxZ6yQ2H3a7kmt8EcYeJcxRSpk3cZHj(NIR6UWPcVzDvJBn1CA4oMX9g2yFIlNPzs4trHrIbhS9)AevNRAJoDC7neZtZirz1ZTdzm1YDQTeV749PmhLnhnbgGfrMqYDpqqgVuyIHPTuybreIQOkIRfnXmS5xU5it3dVXMK(8Own1Y5BWzEgow6ZZVFmMXS48YuHqy7yfBehh2cm2(HhikC7rHtuiiWd2xeyGLsprM7BcZ0D15X1v0QrUikepYsbU0gfkRILAy6c4Ph(vdJgdIHWtRU(m02AgzVREKlexgdrMdEZq0t4E1d74OJ4jNsL7Ifz4LOQjUhiC0r4Me3gPXROxezdGV5GHVjJRP28sJIWuzvTkuzgPeWRc2gKg6h23DSzcjUArS0wstUMflVINRQgBRTIO2oIO(icq0Dc3iLRsyQeo6TeRoSkMUHELkLTZqkikgGa9QOm2iJMvr1YSKn0hhtvP8UiqQyWDnCy4TCtb5djUU56S2uSWJv)DWdyqXmGRkkCWyWvBajGEGRD5WZubLd4aBv2ZHJH4uYuAAIglWD8f1SIuGRQBwXdpogl2LXOi0uS9hgHdC4fuqqMPZGNWUJO3xwTjsDVPmHJEv4KNlCVul2yRyuXIL4MbNT7aob8wwGEKQs3HYqWWizpUwAbVUhE)yOb0UiGGsc(Jjm4MRAI2CgNkCngw8mnS1QnkmUzk8epfxrdjHIXH2zMZ0fbfMco8Y1gIiYy06z6Nfpt)su64eyYw(fjaFbbQ2vs03T37rXnV9K2wZNxCaJN1RGNai(SxgdN5M0gHrOFc58ulKGIdWqckiHcwUTy4A8RsWzLt0F84IHE02HQcXE8Ld0WGcezXIGZKIPifDtcLSeoZjrMHQ4PuB3b8y5H3v(cOfRWkNpq5xyplG8XktBHTBTdb2PgcP6N3Dp09LWc3CtTato)kT84Ldw)KHEiXslIWLjnswXYKkQPECTnGdxDm8rKxhUeKnk2iW7wu6IgRT4xw8BoNAw9DgyNZIBNmeRJNOfkewoyhcse5mfhl2qujIbKEarn8hOJHuMESH64isjW)okwS80NECeb1IDMZ8Ghbf5bRp)a6VjjMD40Ng5tkUxgj00zhbVSdA1cin0zlIpGuhktoY0P6GyTS63m60cYTD1GzbN5xHBl5ZRWQZMa)drALmX1(Ohr6gAz3O7iM26SSnl2PnpZPp6zAAzQTZYDKg)HHNZesbsWTDmKrANRwljoZrwJM75mDfQuYmeQ5oLI3YQT6ng9VGnxTFdUgkvrvlpMG2Y9a3lmng8sboN09AEjO9iIVUTyWBeYG9IgK8gqdjTtjtn3BVEGHFxnwPo9rhdD04JBTUenv4JBOWB69mcJ4nTneS9kZWyUds7DFfcYZ4LnAd2tMhsPIlaCtDcKUcOFHRZTnINqUwypeX9GIb9BQARxDMglw)DDCtyVYnn9MAP8gxJcwpwvxoyY166sEWPZoP7Efd2A3aGYvc0v9cWp0kbDt9syYA1n5LfdhslaRlkkFWiqw5jMCIuUsBK12GO41VrI0Gs06ycnrSANCKCi9UqpElM)wRkgRb9Jfd1cIhP1YecB1ABTCUfoyKvQplX3v4UdEUghqWoWpmlAUyVR5dp7A6RhS8ytmbgyhW01962OTCTU4wRBR)UXcWAZ0iyPHfrKy3NBxBKoxlnUvAzdh5IRuYYzUH5SZwHzRnpXUmrFbEv6flrxQfmSa9a5cwPqfFFh7jrA3imvvA4GQ47tiFnDVi9q9pSuuQaXi1gXqMEPHy1ZAGDrzZ88IkMrMGVdKqRyRYE7rSaYbFFMcgmZsg(da317bWeUIH0(xIk(mldvKfoQGKuq5ncanOlbKwfs(VAqrVYfuXW)KhQavp2Ivia7g7waEM8kIsj5vei95dAIakLhmOohWoaiYfeF3hkGr7OXQ17(y4loWM31BMiDfpI85DCktmHpMZXU9EVNsNRR4NTo1O)sOYairpxd1OeTi32qZQwTvSrlfk5a5EXnTPpqgZW9QRXnHsVgY0J(mj6gWZLhgbPBoD)W1hDHzv5M04YuTALzvTQWIY1mOgj8qHEX8l4YPsT(ZtFfJU7PBYVUqnfJnJb9DHBgEBiLjKk2BVgrj4DiihbVtXQfqesWzHyE8y1j8iQSJf5Fx5jMjuPEb5LgeBG3d8EH3F(GHrrcNATVXqipgC6)ni5LhhEFTYl6c7b(B3U1UHpqEXc9HG)oshbCS)7ft(WWsePduh)dTfxOYpyEH2)W5HpYAyw8Kn1uUKOQ8RWU4)NWUGo6pj8rdJDikeWhd(4b19HpHimh(KnvRg(VJaFASG(Nbl8c)R5HpNb85HVaSmOa)Jpe81Mh(6rGVeoN)z4Fb(3WsoFQiWLqX3j8vGNyRWxnaf4Fh0GNmcGDk(FMh(paByf4UH)l4IWxok8zd6Q5)zFWxmc8pb76IWtvdNf(gW3Za(wW3g(o7dUCe47gOTVze47BapDu4hef(H7b(rgWpE1iEWpjeNd(PgWplp8Zj4m4xaptaig8S5HRSwWl45GFD(WoBoo1CZLIeXObec8)c)o4fJc)EbCb8)DPiBQgmh2ff8BnqmP6yypcHCraHvgaEHOiqx8(nT75UZCp9yMc(ngWVmcbe(8ceX6TZrmNqcunrWAvJS3vpsiKeQQ1dsATnPjWnE02v6TNJ1FVcWIAiuiItRDEHGnRcFkOPRlfzlHqAVVATArZOvikuB0k9(Z3ea1dpfbqH4oe(enLMbO(WbnfHWuIpFNW0OvHGRwda1M7(pPauKiNAqfLXMujqOJ2JqOmZH8GPVxugFU5mmVMeFQbttForu8EWzKqiEsSdyvSmCO4Vc63FM2BfI(1ObQwr)E52NtRqMeayDmZq8neMSjCteQdbsRHBIWQe0jI0UwyteZeroj8sc3eHpjyteK9llGmr831azIWJRbYeHrriteV8PF5azEseYKhMGiaoF288WeG1fe9fAI(h88foAp9gV34eTPqyYbwAYevKVVeUg87((RJy(wjOse)ne3eXsdGjBMf36ablWOXQwTn7wEW)W

**Comment by mrbuds** [comment]
I don't get this error with your aura and development version of WeakAuras.

Also, if you are the author of this aura, i recommend to come on weakauras discord and ask help to fix the way it check talents (it's really bad).

**Comment by Blumberg1337** [comment]
Sorry, I should have been more precise about the reproduction steps. Login as a class that loads the weakaura (for example Hunter) and do not have one of the tracked items (for example Grilled Mudfish) in your inventory. Thanks for your criticism on my "bad" solution. I will ask for help on the Discord server as I don't see a better solution, yet.

**Comment by InfusOnWoW** [comment]
Please create a minimal example of the problem.

**Comment by Blumberg1337** [comment]
First of all... **I love your work and your "product"!** I am really into making WeakAuras for every problem I stumble across. I might not find perfect solutions and I am always interested in better ways to improve my WeakAuras. Calling a solution "really bad" is just not nice and against your Code of Conduct participation. I appreciate the criticism though. Anyway, I would really love to solve this error that crossed me. I hope that you share the same interest in doing so. Here are two videos, showing the error (they are also not perfect), another error reproduction, a friendly guess about the problems source and an even smaller approach then the minimal one shown in the video:

**maximal approach video (~3min)**: https://www.youtube.com/watch?v=FEqW_aBRkUE

**minimal approach video (~6min)**: https://www.youtube.com/watch?v=cZyN6F645D8

**error reproduction for the following export string**:
1. log in as a warlock
2. have at least one "Blackened Basilisk" (itemId: 27657) in your inventory
3. open wa-options
4. as there are no other weakauras now using the custom event... click on the food wa
5. click on any other wa
6. error occurs

_it seems like something isn't working when having to check for item count and checking for a buff with a name and also a custom event (3 triggers)_

_also, another observation: the error does only happen when the wa options are open. it does not occur while the options menu is closed._

**minimal approach WA-Export-String**:
!WA:2!DI1YZTTXz8qt7ABK0uBfhLyzxxeghxjhzfj6xjProdbfPeJPEeqilNXrdjESKyJabqwSqYuzsFWjtIp0t6qVx2z6Po9ap0)a0Fb7Od5upP)eCp2l97Bbi1dBLot0qbcGD3V979VFlZ8OrI0VZutpv(rApIZiop7DchXoWNZc88iofDPEomI)ndVwX4iEqBvdABILzeXrT0MeFEK6ceVqcRFXa)O42MwEKO9TcyoeMMP9goSGWWlO5r3EBtMJQrqGhNgUNzm3nGTCiNcRsH1z5MnJi8)9z7B6BddSsafuaJLxPAPYg9tKwXaVa2NLjtMSmtB56UNEe3KXvSAs9PrUkAWxCLUCgTvlclASBWsV9775qSIB20OdOOluQ6kLxTQghEq3mMzMVBuiXZRItKY(rXwe0QQbZM(0(1lwOMr9Agf0ngo0kmcmKETvkvTQUVzBsKIUCaRfiMECxTyqlSc9m7qy7e7NQckphSicZ307rGQbA)g7y6tBBIgY9e)YY7saxAno4PBXDpR4sA(b(K9Ca1dNrDuzzreiU4e1fNkAkIRR12K6xw8UWcexx8EIBi(TW3V(XFtpq31jTK(AnVatNYwCtpqLhvVDmepu0apG9OIjv0T9mJIW70IOBtWB2ZknmMeaYMn7kzNEQ7AffeZSjw02HbmUEKniWSwjHk3WlKehlZa)J8cBrkAUH9ys9avF9wSG4WEjlPgSBNj8IhAzRycodEJDtgpjb5894b2BM4ap3kVDoQt47TinkI63svdczrQM(oQhktu1asw2aYoBIIe8VMCZSp)q7cQi9RvQAPIgL1lSyPu1PKtls4fR91XGsOwo2ZtDnxkNKpM60FggDTGhQZiB)qliG0K2sjnfTIpOJz3jI41uMbBvS0sgL07HHnAsQEFQFZawsCxH90eZ6lFLrS)4NDtWDW9O(GXUQr1klvs8WmHVVdncZLmipLxpzL1dRZHAW6oDGSpQDDUlJe5g450zVixtNGT(IePE1xrCEXcHQNSesEkt4fSLL24mwn0XKtexDFOcnavt71OoqsDb4rXRbzQkIxxr8RuexyPBiU4pkUKvYA7N8Lmr1ckl5XrIreVH4QIFT4YIXext8BegpnZF(w3snIajXQMQ8HnsKLpQCxtUQTPVQfr1JgXj(Wq8aLMX(Y69XNqrvfwVkTPQFaxfRDRt83CkiLLRgWuNNWXMtJpH6To2Gpy2dErsiBQyPHcZhZD4Ue)uHRESLo7bIvrU1dhg1F2GLQES3)XfHKmINCrG9QC8Xb5wSokw2ulr2YGIjPJ)tPJtQEGFqDnI5gfGjhnvnWHL0hE8ClQv0OUrLflPvOwP5QJn6kPxV0JGKWCtGAXahiQqW)Irvexbk5Dj2BiUAs3TOW3Q6YfMRYsZxVwr9sLwQ(CvQvqRAP5eVL4TheLDPoeD0oCeQk9HeSVsQBBsYB63bQIL3BK05BXahY)4vcZDYPHTdCQdfMKgI3zJUBbvsRXmd7Uw6nAnbWOWluMr3w9ZJnDWsyvddXeJnQ4s7bD2W(tyReWGUzZUXrK6yRl3DW78bJI5kEFSrMyk51BjV(bW17LhYXA0JVfy3DAcACdX1B0f3oSB0LfZiYhELxIA7NEJ46PfCpoPGlR4(ACyEI5T0w2Wy5ffvucVXjB3EKwM2DQ30liaAz(UN8edzeBk2ZlR4SJ9xexsNz6dEwWaNJez7MVT5tFvnOGjCLtp9utFx9TWs2S5H0MmAicv4BNuwRMMUt9vtXsGUwnnbiGS53G0z3dNV1)qQZPeLgv8nzzFfe9Pn7OHOYIpjPbSiRU9aGHSIhKv8PwjjoIZLruSFlx)nkqFAuZnM3ku2rxm7l1PgoWP(L9tCQhG33dWBjoY(qF3Rj(mfroeX84OEJ))hh8z51GeLTe)EXPgl8YLdcCGofAEicb2RrZmIcnE2qCgXVqCwfX5(Kt98iaCBHowmQJbcOmQ4hCfVQuR0JcnTjN5OnfhdAk(9YgFxs8My9fu0i7)DffzRqSniuXaES42(1qbK1Iz6qJJalBED9kZVGHUPhTLVybg0gflGYiMqrCZYPjX36qPYFG8AjfX0dHLX8)QqaK7IPVqbL42z7Yc4saNmI74kki0e3F3uWdjeS4JoJUhUgijcmxWFvS)2wlV9cfQuzPLR(Z2DVJjZUQKqZ3n6(q6gyp(8YqZHaMLo0Jz1Ay(YV78DBHUxa4iN(CdtRonO1BL4H2bhxg(FvXNk(JIUIzfLZcOJi(wVMa6CrkZ2dkFROaPhSeIve3NnEpkST1Keva0W)GmhT3bGDNcZrbzSNnqlfs58RTfneeZNlU6UdEfYeW9Ob5)jeK)xYameD3d2kOdAun3GTw2hAiGFLYjzi63OkyX6sqPydzkWvu2b71lzpoME(7(r3zgzsJQci6NDXUavJ24SpN35LTXSHUB8gHxeVVfKRYO2j7xJ9oYJ7NS9ft1D5Ejtg1qjIQ7UOigi(gI)MR4Q9QapcKMGTqxUrJmTuP)RIEyA7Ok7lFB9aGcQje7g5bj65MGlWaa1p1JpeYe8haY4fa0bvrsL6bEK5Wo2ZQ(nsyYVj3k6vkvZi3KQ3Es1z(iaq6jpPMSIhBaS(6F7KPZR2cfwSWsW8Mb(CF58k5rAdTqazViGntyDo00xPqve3cMF(HYDHaVoQ1CPepNdnZ50xTYCPY9dLZBXaGqo0vS8bAW3o0msOYxejgdwXQa7E59q3cY45sgmhISMqpy8Jm9zvZTyH5lLdPNC8bwRGE1Ll(qaAEihcgHhZ8v5SyYqEdWhWXOsH9gu439iovNa5YEjB7HN2tOR)Kzw)qBZalR(Kh8bYg3iLSJ8ObvaEQJFCPKF9jFbjF71NivOOAifZduN(i72Xnm8VeJBW3jxtNvttViIKGYQIhjEmufH5WFr4v(ji4K2zvSEEtpp4aSj14jmqQg0IAh(bdZs5tCWEXbpJ8qdCW4sV52Rl386NbAF(8niKWcOnZ1XEOUI5HEooKiGHlYzXvmXhd8qeKNDTW3bb)RZ)PWVdV8lmNOHSj2z4y5Ep4qZYNoow4EjNDjLIFM9tM0GdCOvyvJLdFd5lpkbErTNNSPdHs)tPIkL8sMWRFsQ)r4PSRCcPmbaxHeBHGDt1wA5LkfQEsszilVxIp4aW)WRDsRp9WkIlXaoF44HJKyNh2kotp57oGrYoPsc4D4CKfK6bpB6lpYjNYS3WvjpN9IjppGAQWkXjSjetbobnsdvh6NUy3klTeKzMWc8L4sU3uawO9ghe6pIw84xqlq(OVz4eNKR5fpj4lXhBpCZ(X9A5fSvzg5RJj(2DqsJ5VBIFfhOpEzGo0fFaDc7zfZ5b(ld8PHon9WxNGT)MY5pWZTd(WWFPGSiCZ8dEJRgoORC3nCHJ84tIIYkxrn5pFG82QWjGJUOCd0s(1eSCj0wU8zf38VlA6kALYNVpcLTjbeKhugk5fLawI9aD7LGB22YKNCuaGvfYWFQByHqZEeRfwfpCUyYMS0oXnyPyin0WM2n0LafnSsaIAyLaC1i5Sdc3gckEGbjpR7RHmnaMjNgiGmG6Cf4vwZC77m9DYl(pnqgLf7)HBxyn3A6Rz6DNWlnGJbw9mhncjy64gocOTdqWHdpPlpz0aAr)GKbeqBkEwGNyORzwG)hJ6J)OiGxa4e9ZLTMOcqE9X3qFttVys2UBAYOOcPHuky2U4joIGz8FB0nKHub4DWFwPPU9uyKQ7atXvB7GG2zgzZt)T)Vd

**Comment by mrbuds** [comment]
Made a minimal example that work on any class, it error on retail & tbc
```
!WA:2!DA1xZTTXrCZW4AhuNwj6y7i7ufyfBfl3gzBfxLoTrDcbfOfJ5)miKKttZaEa4iXzccC5Wbjt1NQMoD0Z6P(mFOp1PpWpbD0NGB40jFa0hb)fODpaqklBP0zkFaCbU7293U3U)2n3wfIOx7ROSWxGD4F2oywejm4Ru52of6xWTG7bQhBhYCXmnKtpxwiLoJMpzV9qmxvZWqFoHogfZ9cznOC4OrkSbn60jcZ34F5CJ)ZfGFJqboW6ndjbCMzJMv1lBokvPLc9dzFDUC5YZqojhFvJioIXv0ibeUIDh4VipL95ms3Ua4U5ISmX)6qxSDCNoMdOy2g6vBwEZQAC4fdumdTY(ruSVFf3iLJJITX7Gd4TGDtE5iRsfBzA1YSOH50LAYWWsgTAQxTQraQposXizb7nWiFUNwmGgBQpAaMDyCqgeuEf4rywaYFR04wVdJW(DsCu7s61n1ngcwWa3njWO5hIClRfr2dFDJ(XqOtrdqPZ1f3rXWXhffjLS5iFWWsXX2zX80Wu(85BM)Hl)RTJcJzoyBsFAiJBe5ahiVDAa1JotA0Umd8IKhSAqmSpIoKLGdz8YOllmMom9iTa8Cr6SV2XAIyacAFu66P3MV3qEOtw6XLB(HlqCP3TgjkIe0vvdcSrQOax1sGFg3hz7JJunHR0Ey2Oosv2IZqCu(x9AwrcKrT0RQxYSSrXA6zWr3TlMoBRVpgaHA5yFF1T9iCSTtyqhsxf2lNKDH(BxwMDTsmXD0JyKTdFQbdV3tZYSQeaBk)q4uUK08YrKGoHS(i5BkhIKXeP4QcLYIz1ccdWhHrrsKId6Y9U0yxipsUdlzwflcl1v0(Y9iHUOKwFejaoROKy9lj0fLfpbeVYB(Lco3)GLG4n3NearZnnRwPUUHZKR08JJ8qUH7(nP(1hDbXprOsvDjrY0nt8l5wPW2IAXj9XzVLJoJtCepSVChBsDrCSyUJHkXqPB5SnXfYAlcVkEpWdve)ufXvueVF9ff)SFqmRD6zfFG4AJsfT8iUydPbCfZjUP46IBmzfP7BdvL84O0QLi6nQ2O46vQ)eRwLm01RBTELwf1QQVU4z0FOtCqsP89wsrf(r6OkliTWb7SSu9mvUhoizj5VtV2VTeKGG9ZokoWv5T3J6AQLSmLslxhVRjrMKDVP67r)k1PYNGe1TXOEfb1eTClhuGEIxCVfQPvY0YSsnDTIT0x3sYIOByPVfu6UWstn)skGK4dHAupStpi6CvfXTeFK4NlMr8lugb3uViXq7GxbfmaQKsKnt5iQf6I)hxGUW5FF2p01cs0WTfZ3B)DHK3Tzi6(BNjO1jmGtNPmJSN6ZIrUYYivttXTV51fZogyxKCeYYzaIlS1HXryRa4sI5j(ujfIyXKN3n55NapxDfooO9q(UqeyqhaNTfLAVV0isEG5eljUp9wNbydYeeLYYxFEA(AEXd04W(OlE(EOpUlYzGvh)WqaxAPvCNUQzJ)31rdbgASBsI9F5kNjgPtWyl6NC(OHYWoejnwEX7QiwBuxVGEfjVmQtVNWEbKXt6mqt2Is84mEU5lLuhOkZ5SHQFx108h1nW(aXG4I5eRMx8f2P1cIVmN43LKvmX(Vd9xE(OXDa0UH4yX9y4iVqF3bJsJVN0Au8vkIIkIp2wRHPzJAh8PdjavuRKMaaDXxMB4jmbVJenabYyhO3mOLGw7sOWDCDXChn5tsgwpnPoAlE))jqi83Hi9TowM6G83fniIZIHJaCdI5gwAkbAso)vv2xUpz7W2socOSiRoa0ZbZUpWu3VoqUF5hwljx0bsm5EJbhgkEIA5fUBJaibs(xw3JXDXaTiXjDTJtxRuguNwNnRMuZzyQcicTAK9HbBinNNrIHk8qzTjal6SsJFkn3gG6rYVobITpo5mwHWDiIhYk87t9IDGOXZaIS5FdImgMhZcuLbNecbtXMIVbydKqCl6T(r4sYIqI)WkiFFAHSBRu(HQHDjo0hm1wCPXMyQV9rFxsBv(3UYeHp)7sm(F8IaBXR6HX0IYri4gYovEIpwOcJffbu1sgfpXTVpWsiSpyE6TLfPw8FSYb6CV1EIMw1F401w4UuQ65PTPKz07CEB5uSbhNSHPtnPvCtZg0RM8Xt3lt08vP6AkjWFMU05zI3UOAC6GhznzZDuYHYQ2HygleAVHLfqA1BuxNotkSEJcXZWTxDzOXOtVtIt05ppqL13wmldyTtOmlK6NjilJo9Idt(2jthCyMMc4cu2bo18c5oLwY(4Ls9VDG7vyuS2JtEBsRfH14P6mzqMVoZDFTX0pQsDygfRucNtz2NpXSZDg(5e63tmGSPY1gFkx8SoQZ04NThM01JVg0mt4mPjwA7Rfx0wsy4JT3yt5S1I7SdB7IggvAy0wkuTrPN2M1Syv5OjT1Qv8j6Tnw3yZkR32U1gfRvSEB7Mgv0Bz2oTvOWTTiP)NSRN4bI)0RpR0(tOl9K8V))20I(btuJm5ADsKC2yxpOdH2EHH9t6CmPpZCLddDv)mvnF5GZbqFgnueXNe1t8fcMbYN6HYBSRm3FnAbGkBcljmJHrYaeRn63SxXT9AzSnY)XmsGCEDGf4DN2oQcq6B)Op)Xp8XRiBP80KuSc78VF()9p
```

**Comment by mrbuds** [comment]
I could reproduce error with item trigger as trigger2, but when i move trigger2 to trigger1 + change dynamic info from 2 to 1 error don't happen anymore

**Comment by Blumberg1337** [comment]
I will check that in my maximal approach weakaura. Will edit this post, when finished.
