### ISSUE TITLE
Add Cast trigger "Interruptible" checkbox

### ISSUE THREAD

**Issue by Soothx** [WeakAuras/WeakAuras2#3738]
**Is your feature request related to a problem? Please describe.**
In WeakAuras version 4.0.2-50-g0e49842 for WotLK the API check if a cast is Interruptible does not currently exist in the WeakAura interface panel for the Cast trigger.
It was added in patch 3.2, and is accessible on beta/ptr through custom code, but currently isn't accessible to the WeakAura interface for the Cast trigger, but exists in retail.

**Describe the solution you'd like**
Add the checkbox that currently exists in retail:
![image](https://user-images.githubusercontent.com/33608256/184544785-760d9f31-3ec2-4d62-9847-a1ab14dc8fd4.png)

**Describe alternatives you've considered**
Custom code for UnitCastingInfo, but would rather see it implemented properly.

**Additional context**
https://wowwiki-archive.fandom.com/wiki/API_UnitCastingInfo
![image](https://user-images.githubusercontent.com/33608256/184544809-f414f024-d92d-44fc-9cdb-262f3b6de27b.png)

**Comment by mrbuds** [comment]
`/dump UnitCastingInfo("player")` seems to always return false as 9th arg (tested with greater heal & flamestrike)

**Comment by Soothx** [comment]
I have submitted a bug report ingame instead, and hope that Blizzard adds this back in.

**Comment by Soothx** [comment]
@mrbuds 
The API works opposite of how we both thought. It returns `true` if the cast is `notInterruptible`, such as when a Paladin is casting during Divine Shield:
![image](https://user-images.githubusercontent.com/33608256/186658641-030f5721-2bcb-4c33-ba05-857a1492ae83.png)

Perhaps reopen this, as it does work as intended, and hopefully can be added to the WeakAuras UI for Wrath.

**Comment by mrbuds** [comment]
Indeed i was not paying attention, thank you
