### ISSUE TITLE
Add name filter to trigger "Item - Cooldown Progress (Slot)"

### ISSUE THREAD

**Issue by vaisest** [WeakAuras/WeakAuras2#3739]
**Is your feature request related to a problem? Please describe.**
I am trying to make an aura that shows trinket slot 1 cooldown, but not when there are some less useful things in it like the So'leah trinket.

**Describe the solution you'd like**
I think it would be good to have the name available as a filter for the trigger since the trigger state seems to already contain the name.

**Comment by mrbuds** [comment]
I expect you would not want only 1 name to filtered out.
Generic triggers (except aura trigger) only way (for now) to have a variable number of input for a field is thru delimiter (spaces, commas).
Problem is that a trinket's name can contain spaces & commas.
So a system would have to be added for generic triggers to handle a variable number of filters, like the aura trigger has for buffs.


Let's step back and look at which solution is already possible to achieve your goal (without custom code)

You could use multiple additional triggers that check if an item is equipped (or not) in a specific slot.
"Item Equipped" trigger lacks a slot filter, making it possible is an easier change, "Item Bonus Id Equipped" has this optional filter..
