### ISSUE TITLE
The toggles inside a Toggle List keep the previously defined width.

### ISSUE THREAD

**Issue by hexaheart** [WeakAuras/WeakAuras2#3744]
### Description

**What happen:**
When the `Width` of a Custom Option has been changed in Author mode and then Option Type is changed into Toggle List,
the width of the Toggles of the list are keep as previously defined by the `Width` when going back into user mode.

**What I expect:**
Either 1. The "Width" slider stay accessible on Toggle List
Or 2. The "Width" default back to 1

I already took a look into fixing the issue, both options seem doable. 
I think option 1. is better as it offers more flexibility, but I might have overlooked something.

### WeakAuras Version

WeakAuras 4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Go to `Custom Options` of a WeakAura
2. Click `Enter Author Mode`
3. Click `Add Option`
4. Change the `Width` slider field
5. Select `Toggle List` in `Option Type` dropdown menu field
6. Add a few `New Value`
7. Click `Enter User Mode`

### Screenshots

![image](https://user-images.githubusercontent.com/14247159/185265157-e9a61949-7f4a-4109-b5ff-875a1e821406.png)

### Export String

https://wago.io/6jE32Zvc9

**Comment by InfusOnWoW** [comment]
Width is not selectable. We aren't sure why it wasn't. If that'll lead to bugs, we'll probably remove it and hardcode it to normal width.

**Comment by InfusOnWoW** [comment]
width is *now* selectable
