### ISSUE TITLE
Missing return on succesful import from Weakauras.import in Transmission.lua

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#3745]
### Description

as stated in https://github.com/WeakAuras/WeakAuras2/wiki/API-Documentation I expect the first argument to return a truthy value on succesful importing but it just returns nil. 
Checking the Code  local status, msg = true, "" is set but it is never returned anywhere but it instead returns  ImportNow(data, children, target). That function however does not have a return value.

I might not have explained this properly but hopefully infus understands anyway. Can do a pull request to fix if you want 🤷 

### WeakAuras Version

4.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. call Weakauras.Import with a proper table to import
2. import Aura
3. watch the return print and see that it is nil

### Last Good Version

not sure probably before the importing rework

**Comment by InfusOnWoW** [comment]
That's not a bug. The import process works entirely different now. A PR to add a callback that is called after the import has been canceled, failed or succeded would be something you can propose though.

But I don't think anyone on the team wants to urgently work on improving our import api.
