### ISSUE TITLE
Copying an aura's triggers doesn't copy its custom trigger function

### ISSUE THREAD

**Issue by ewollesen** [WeakAuras/WeakAuras2#375]
### What steps will reproduce the problem?

* Create two auras, I used icons.
* Define two triggers on the first aura.
* Define a valid, custom trigger function on the first aura.
* In the aura list pane, right click the first aura and then select copy triggers.
* In the aura list pane, right click the second aura and then select paste triggers.

### What is the expected output? What do you see instead?

I expected the second aura to receive the triggers from the first aura, including the custom trigger function. Instead, the second aura has no custom trigger function. I did receive the triggers themselves, however.

### Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

~~Ooops, not yet, but I can try that and report back (I highly doubt that's an issue here?)~~

Yes, same result.

### What version of WeakAuras are you using?

2.5.8

### Was it working in a previous version? If yes, which was the last good one?

Unknown, I didn't try on any previous versions.

### Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

~~I'll have to come back and report on this later. I was sent here by the discord channel, and I'm not able to open my game client to test at the moment.~~

Tried with `/console scriptErrors 1`, but saw no output in console.

### In case you do know which aura is problematic, please export the string and paste it below.

~~Likewise I'll have to come back and fill the above in later as well.~~

Aura 1:
```dyJ0caGAvbTlvLmtsKzl4MQICxvjDBszNuu7fTBI2pf(PQqdtvuJtvGHQkLbRugojCqiPtPQshdIwijQLQuvTyvvTCOEOsv8uWYOipxr)wOPQYKjPPlDrLQYPfDzQUoH)cHZdj2mKA7k4Zk57QsmnLk18uQWivQshMsJwHgVQs9ys1TuQORPQI7PujRuvQERQIgLQctK8iy5XsysW0x)81diOrqLGkpcQ58HcPEZbNGUy2OgbREZb)W5A54NIQonVtKptO4CTCmpcZX4lpkjmhJV8Oev9MdolHq0QYJqTbxwt8iOjcn5XYsO2GllpcAIqtESSeut0OtDrOOWJGMi0KhllbSv35rqteAYJLLaogCEe0eHM8yzjOyqrTbxwEe0eHM8yzjKYfokuWJGMi0Khllb0w9MrjpcAIqtESSSe0fZg1oCUwowP4k1jGwi1BgLgBFu8VgVBSzSzSzSH9kWsJTI)e5RgBwPQXMm2pk(ttV(RX7UuLa2xzuEOOWjK6rjbPq7W5A54jnBIGvvnBgL2aIIZ1YXtE0msEekoxlhZJqrrHtywBftcIPJy0THosLjiK(GllbROrcIPJW(FgX)FkQ6uzc(GllH962qhjmf)9bx23Wo68BcWB7tjLim62qhj8ZZeMI)(GlliqJo)MaI9GkCiGd19FeethHqMLktqiZsqrWIIJjm62qhrev4yBJyc7yxSeeYIZ1YX8yzzjKQeoF2uUm2qsiLzrmRfxxLMrYsyGMrUBtizjb```

Aura 2:
```detGcaGAPcTlfWmLQQztQBkvPBJk7KkSxy3e2pvv5NsfnmPsnoQkmuPsgSubdhfoic1XqjleLYsPQulwbTCIEivL8uvlJk65szQknzu10fxeLQUmLRJ0Vv0MrrBNQCAjpgbtJQQAEuvPrsvrNhHmAQ04vGomj3cLkxtQI7rvf)vH(Uuv(mIgSWIRWIG3WDoqpd4dCoCECES48vRJubHuEgobAltoCfHuE2klsst27K3Gd2XQB8ilsstIfV5o7RtbEZD2xNcIjKYZqW1tfpw8O0MioXIZr1PWIGGhL2eblohvNclccoFXKzrGQdryX5O6uyrqWLkcgwCoQofweeC5uByX5O6uyrqWz4XikTjcwCoQofwee8sqkNugyX5O6uyrqWzQiKAkWIZr1PWIGGGlnYAkwIyy4fHPaxq5wzrsAYgC4exXZxPMcLEmYIK0KnSWblS4rwKKMelEiIHH3Ik0goTzJUMshxWgovyEMi4kAM40MnQg2MYH9o5nWgU5zIG7ttPJlEJo08mr6sAmRbXFxSV)(XDnLoU490nEJo08mroLjZAq8rFr83XVe77fN2SrQOcydNkQGZqRiYK4UMsh3XjdtQYuI7x)GGtfrwKKMelcccEXJVwlLG0FDWjEjQm2IsgJhoyHG7bhS8Vtwiaa```

**Comment by InfusOnWoW** [comment]
I can't reproduce that. 
Can you try the alpha? That one contains a patch for different a copy/paste issue, but that should not have affected copying triggers.

**Comment by ewollesen** [comment]
@InfusOnWoW I've tested some things to fill in the holes in my report above, and I tried the alpha version. Here's my summary:

* Reproduced again in 3.8.5 (just checking myself)
* Reproduced in 3.8.5 with all other add-ons disabled.
* Reproduced in latest alpha `2.5.8-7-g35a52cb-alpha` with all other add-ons disabled.
* Turned on console errors, tried again, no errors produced in console.

Hopefully my steps to reproduce were clear. I could probably figure out how to upload a youtube video or something if that would help... I'll try and see if I can't do that, can't hurt.

Here's aura 1:
```dyJ0caGAvbTlvLmtsKzl4MQICxvjDBszNuu7fTBI2pf(PQqdtvuJtvGHQkLbRugojCqiPtPQshdIwijQLQuvTyvvTCOEOsv8uWYOipxr)wOPQYKjPPlDrLQYPfDzQUoH)cHZdj2mKA7k4Zk57QsmnLk18uQWivQshMsJwHgVQs9ys1TuQORPQI7PujRuvQERQIgLQctK8iy5XsysW0x)81diOrqLGkpcQ58HcPEZbNGUy2OgbREZb)W5A54NIQonVtKptO4CTCmpcZX4lpkjmhJV8Oev9MdolHq0QYJqTbxwt8iOjcn5XYsO2GllpcAIqtESSeut0OtDrOOWJGMi0KhllbSv35rqteAYJLLaogCEe0eHM8yzjOyqrTbxwEe0eHM8yzjKYfokuWJGMi0Khllb0w9MrjpcAIqtESSSe0fZg1oCUwowP4k1jGwi1BgLgBFu8VgVBSzSzSzSH9kWsJTI)e5RgBwPQXMm2pk(ttV(RX7UuLa2xzuEOOWjK6rjbPq7W5A54jnBIGvvnBgL2aIIZ1YXtE0msEekoxlhZJqrrHtywBftcIPJy0THosLjiK(GllbROrcIPJW(FgX)FkQ6uzc(GllH962qhjmf)9bx23Wo68BcWB7tjLim62qhj8ZZeMI)(GlliqJo)MaI9GkCiGd19FeethHqMLktqiZsqrWIIJjm62qhrev4yBJyc7yxSeeYIZ1YX8yzzjKQeoF2uUm2qsiLzrmRfxxLMrYsyGMrUBtizjb```

Here's aura 2:
```detGcaGAPcTlfWmLQQztQBkvPBJk7KkSxy3e2pvv5NsfnmPsnoQkmuPsgSubdhfoic1XqjleLYsPQulwbTCIEivL8uvlJk65szQknzu10fxeLQUmLRJ0Vv0MrrBNQCAjpgbtJQQAEuvPrsvrNhHmAQ04vGomj3cLkxtQI7rvf)vH(Uuv(mIgSWIRWIG3WDoqpd4dCoCECES48vRJubHuEgobAltoCfHuE2klsst27K3Gd2XQB8ilsstIfV5o7RtbEZD2xNcIjKYZqW1tfpw8O0MioXIZr1PWIGGhL2eblohvNclccoFXKzrGQdryX5O6uyrqWLkcgwCoQofweeC5uByX5O6uyrqWz4XikTjcwCoQofwee8sqkNugyX5O6uyrqWzQiKAkWIZr1PWIGGGlnYAkwIyy4fHPaxq5wzrsAYgC4exXZxPMcLEmYIK0KnSWblS4rwKKMelEiIHH3Ik0goTzJUMshxWgovyEMi4kAM40MnQg2MYH9o5nWgU5zIG7ttPJlEJo08mr6sAmRbXFxSV)(XDnLoU490nEJo08mroLjZAq8rFr83XVe77fN2SrQOcydNkQGZqRiYK4UMsh3XjdtQYuI7x)GGtfrwKKMelcccEXJVwlLG0FDWjEjQm2IsgJhoyHG7bhS8Vtwiaa```

**Comment by emptyrivers** [comment]
3.8.5? Do you mean 2.5.8?

**Comment by ewollesen** [comment]
Whoa, yeah, sorry, will edit comment. Where'd I get 3.8.5 from?

**Comment by ewollesen** [comment]
Here's a video of me showing exactly how I reproduce the issue. This was taken with all over add-ons disabled, running the alpha version.

https://youtu.be/SLXPYKEszIU

**Comment by emptyrivers** [comment]
Ah, you're talking about the trigger activation function, not the trigger functions itself. @InfusOnWoW I've managed to reproduce it. In fact, it's not limited to custom activation logic; the logic isn't copied at all.

**Comment by ewollesen** [comment]
Apologies for my language not being precise. I guess it was good to make the video. 😎

**Comment by ewollesen** [comment]
I tried this in 2.5.10 and it's now fixed! Thank you!

**Comment by InfusOnWoW** [comment]
Ah thanks for closing the bug report, I somehow forgot to do that.
