### ISSUE TITLE
(Request) Add Game Screen Resolution as a conditional load option.

### ISSUE THREAD

**Issue by Razoroth** [WeakAuras/WeakAuras2#3764]
**Is your feature request related to a problem? Please describe.**
Yes and no: I play on two computer, a desktop and a laptop, with different resolutions. When syncing settings between the two, since screen resolutions are different (4k vs 1080p) most of my weakauras as not in the right position. This could simply be fixed by Duplicating the weakaura and adjusting the positioning to work on the 2nd resolution, but each "group" of weakauras would have to be manually turned on and off in the load settings as needed.

**Describe the solution you'd like**
Adding a load option to detect game screen resolutions as a conditional option for load.

**Describe alternatives you've considered**
Can't think of any, aside from manually checking Never load on groups that don't work and loading duplicated groups that do.

**Additional context**
None.

**Comment by InfusOnWoW** [comment]
That's far too niche.
