### ISSUE TITLE
Trojan warning when trying to update to version 4.0.3

### ISSUE THREAD

**Issue by AiApaec** [WeakAuras/WeakAuras2#3765]
### Description

Trojan:Script/Wacatac.B!ml 
Windows defender flags new update when trying to install newest version 
file: C:\Users\*user*\AppData\Roaming\WowUp\Cache\Cache_Data\f_000164
file: C:\Users\*user*\AppData\Roaming\WowUp\downloads\5ZwjTwxzK0TGbdrA8nXO9-weakauras.zip
When trying to download via WoWUp
file: C:\Users\*user*\AppData\Local\Temp\CF\AxEIKOx6zEOddlAQZuckg\2.zip
when trying to update from CurseForge

### WeakAuras Version

WeakAuras 4.0.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

1. Go to WoWUp
2. Click update on WA
3. Windows Defender pop appears
4. checked details for file name
5. Error updating WA

### Last Good Version

WeakAuras 4.0.2

**Comment by Stanzilla** [comment]
Please report it as a false positive to Microsoft
