### ISSUE TITLE
When Downloading Virus Protection Detected Trogan Horse Virus

### ISSUE THREAD

**Issue by Tatskii** [WeakAuras/WeakAuras2#3766]
### Description

As i was downloading the files my anti-virus detected a major threat declaring it a Trojan Virus 
I'd like to give benefit of the doubt to developer that this wasnt intentional and it got stuck in BUT until the issue is fixed i will not be downloading the updated version

### WeakAuras Version

Weakauras4.0.2-bcc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [X] No

### Lua Error

not a lua error

### Reproduction Steps

go to download new version
get virus detection 
files stop downloading
Delete Trojan virus
Repeat process 5x times 

Fix your shit please 👍

**Comment by SpatenLa** [comment]
https://www.wowhead.com/news/windows-defender-wrongly-flagging-wow-addons-as-trojans-323858
same as a year ago.
it does again affect mutlitple addons.
its exactly a year since it happent the last time.
microsoft messed something up.

**Comment by Tatskii** [comment]
i use another virus protection that before didnt flag it but now is so that doesnt help my question when posting the bug report

im not gonna download something flagging a trojan

**Comment by Tatskii** [comment]
lost 1 PC that way not doing that again

**Comment by SpatenLa** [comment]
if thats the case, why do you download a old version of the addon and where do you download it from? 4.0.3 is the newest version.

**Comment by Tatskii** [comment]
curseforge auto update

**Comment by Tatskii** [comment]
and for Burning Crusade Classic is 4.0.2 retail is 4.0.3 or am i mistaken when they but 4.0.2bbc and then 4.0.3

**Comment by SpatenLa** [comment]
https://github.com/WeakAuras/WeakAuras2/releases/tag/4.0.3
did you try downloading the newest version of weakauras here? sicne 4.0.3 it is one version for all flavours
![grafik](https://user-images.githubusercontent.com/39881841/186210974-ff61a0a7-376d-47c3-80d0-d95d1340f847.png)

**Comment by Tatskii** [comment]
Still Flagging a Trojoan....

**Comment by Tatskii** [comment]
i love this add on but ill be upest if my current version doesnt work in Wotlk but i like i said long as it Triggering a Trojan threat sadly i wont be using it

**Comment by mrbuds** [comment]
Analyze from 88 antivirus show archive is clean

https://www.virustotal.com/gui/url/5929da804da8adc0913e73f7f588cc1eac0a16dd6582f908fe2e18fdf0837f9f?nocache=1

**Comment by InfusOnWoW** [comment]
There is nothing for us to do. This is to the best of our knowledge a false positive.
