### ISSUE TITLE
Seal of Corruption cannot be added as a trigger by it's name.

### ISSUE THREAD

**Issue by KalinPopov** [WeakAuras/WeakAuras2#3767]
### Description

When typing out the "Seal of Corruption" as a trigger nothing happens after pressing okay/enter. Adding it by spell ID is fine but it does not solve the problem of not being able to add it by name. It's just a workaround.  
  
Here's a video of the bug in action: https://www.youtube.com/watch?v=5ztZx8NhHSY 

### WeakAuras Version

Weakaura 4.0.3 tbc

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Open Triggers
Type Seal of Corruption
Press Enter/Okay
NOthing happens.

### Last Good Version

No idea

### Screenshots

https://www.youtube.com/watch?v=5ztZx8NhHSY  

### Export String

!WA:2!1zvtST1XrytXyibHGIiAhbBJ0uwHA1A3gzBrf3IG2gqkt5FGSO8J0rPN4BFV3s(wRh3DZU7tI0NAyrb0HcuaEPxADDzbYPEiHP)gKgdOd9upSIOOTN1LEPNe6LI2c0z2hPmkqnpW3U7m7SZoZ38nBUnk0PquHOdEJHSqbVUivfsFTZmmmvBeDAq7AMr1RwRwAQ5t)CJi8WyHABbJBcwV6wnQ6nouisIe7ZRVpts9LVYZ34dLredni195WP6vnQnnUcEw(9nkw72uLERLvtgEWRVQI2PWAhNQP3wjsLndfPCt8WiWqTA1ONKQUt1n3EJhUz)OufXWe8c3yGwsts2I0Ho3x4rhRtdO7r5MTv0wSUE13U6MB2hSxZuoZ4pchzaNXWKXNatQ2LeAQJg4UrXNU56WPX6oQ56LR3Oz9gL9Aixa3jCsHSwSqNXIhqaFGdNR(XNuNsskkAvCDrNoeE04PZ3K1o2CQ07bHhwivE(PlyIPfxxLQjruL8vNUQhUjQivZPA9XtxDhMos05ulxjriIuqmTgpPN)OSiFZywe1ZW6qJuPC3DPcj1iGJGIriF8o3mlCUEcrRJpeVeUiilsFPGsR9n(6xFTHO86XI9RXhQHpLt2N0t75URxvwW(Jp6hE07B)SJ(Uh99SFK9tSFO8s2NA)WJE)J6JRA)m7ZS)Eyem)OFGNZnKxC9jyGIBReTvWnR4xXf4VsfdKy9q)y1Xk42vFA(uEo7pY(RSFkAl7VR4rhaF(KXtsezQ43xNL80xDUZx6cZ8pMXLIz89aKf1FeGNQbOgcecw6B)Toou0jGXP3NycJPA3DBtX(uTzCNSLYU023OcMHdKjKEu1aadMbqx0waWyJIy6hLYdnS9ORs49KlqCJBKP09fr0FXzgcUrJmGM)j7sPYYi4X4HGw)bAAslxHK9ShJqID7DRj45yf65WGgZneGJE02Wy99w0wAmmnGeUBBOYGhTNT0aCbHcGoJZ(0u4kvZp0afGqTtIqn)Hte5MDVC5YL)4jRShtZcsGy0K5uO2uUq93lLOOf3injP4oXmdDQyn7X08)5XTte7VHI(EPuEyVTFPRVYQVPTKc8euWi8V3nJWixFCcwZooi1ye8AWfdINdXL3KYBBIFvN(FNj6paNSUZnZd)oejbMUsSty9qscnVZfAedbnS8iFfCAM8nHuREb3buX50XhCr5x0fmC)1sOG0CtztSaPPubfZyKo)GtvzPllLfFrBOJiQjKKO(h7eEAoSs5h2OM8CUfXInylSWDyrM4kLHPNKzkwxAKBX3FCgr6079Ho5pcPgA1ZE2HkHboeKdTYw12QQ8I)F8NSb2lNf6rzYR8IC7OEqDlWzzIHIUyOgmN9(3l)DE7)()g(9F(835T)B)f83)CsyOLGBgwTReRqHQE5R)ISB2SCYczrJys0ZZLYV0lAxj02KWEnBbSxk)Xof2hYv7OiY(7mzW4tDehLFTh2yZ7cbIxjlc)8Uq2ZMf7MIK)FCLPWWNBS6ac(ktc(tLoXOzBz9tRrcIPih8dasws0bNtX4yvNCrVoPqf98dqogKEvf7fI0OlhObvsOQTlVz5BD3TS9x0ZR2TFyvFNQoD8ROiH0fT9NV)0Ej(vWQkCjLbG2CZQ44GSXlB)(xgSZxfucufMLhMDw8s6e3e8BfPMejnMDyed6yfcoxp0chFkh5UCGX1x9ybNcCKZmqUNmB7UdTfsCj444kkrIZtg(89n3d(yhBRKAcigtcnoq7EIqaRJuOmEHNwT2FAhE)HqZ9igAw9BTShWPgU7nTVC((7rumcKLcWEl0iV9ijP08QWycVnvFPLTpnUVujG8TPh0WxtmiJiDz7pzd7l)1oZsczHVP9jlvZlWzt9vHLZNT6tl8M2NCmTRKLXH2aaA4zAFI9NAFAo7pdTUVDisOUsPvq(bWSGgV2zSpPpJJDfGQjNMlAhA)GHkhTlI(SZpgQPbetwKwpVQBg05po7QPSOr3VLClVBTtPD3l1(Z9pjdDTHcAnH7oO(6EvRULSaegN2)d6p4HSidiCwhN)EtpTHOmVJTufoKO6tjA3UTJoehw3OC0LZoE6JEAIDmH(ByOwhGLQutLwWJiQ0HW4hSqGlX4LpqJmMDZNnV8KV3oVTKDK9JTJYK3lVhjrgtYLHvD8Tf6LBGBK7wK94IcDZfKronr2gqtWzS)YzHE0)6mtxjFqlgNPJ)GPhbkZ(SCdCNaASk4tuS)g7V1UqHBaB2HWaKmxNawo25doLbWgTduI5vAL1w5MvESq0z78xFLs2VS)qJiCsBY52(clXI8WxfPLNFkkezpVftJ4Ti)rTW0befjgYSE7JCWpW(mmyWBXApVAYJfIxnvLilgBms9BDTRTpPTyfM4ALBr5evtpr7u61UrPsQSAg9nTF0I9Jen1y34y7Fyr7FfEzl8QH5X3hGVC4UWbCHzEP)1igpJdel1KxG1Mlu0jWPQ4BJQQucL2)eGsJQ4KK3j7QTBb9G1wbUXfnbHf27p9U)3)

**Comment by InfusOnWoW** [comment]
Can you paste the output of /dump GetSpellInfo("Seal of Corruption") ?

**Comment by Translitdk** [comment]
From my testing (on a shaman with ruRU locale)
GetSpellInfo do not print by name, because i'm on a wrong class
Pasting in "Seal of Corruption" (localized) in the name field does nothing. Pasting 348704 spellid shows correct spell. Removing spellid and trying to paste name works now (https://i.imgur.com/Fsd6AYQ.png) but trigger do not catch icon info.

The issue might be with a state that is horde version of https://tbc.wowhead.com/spell=31801/seal-of-vengeance which works fine

**Comment by InfusOnWoW** [comment]
No response from reporter.

**Comment by KalinPopov** [comment]
Here is the dump you requested:

[01:11:10] Dump: value=GetSpellInfo("Seal of Corruption")
[01:11:10] [1]="Seal of Corruption",
[01:11:10] [3]=135969,
[01:11:10] [4]=0,
[01:11:10] [5]=0,
[01:11:10] [6]=0,
[01:11:10] [7]=348704
