### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Aldric69** [WeakAuras/WeakAuras2#3768]
### Description

Monitoring Weakauras I noticed that it is constantly consuming more memory. None of the other addons are exhibiting this problem.

### WeakAuras Version

Weakauras 4.03

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Monitoring in game use of memory. WA memory utilization is constantly climbing. Reverted to 4.0.2 and have the same situation.

### Last Good Version

Unknown

**Comment by Stanzilla** [comment]
Would have to at least provide all the auras that you are using/the SV file to be able to help you.

**Comment by InfusOnWoW** [comment]
The reproduction steps are far to sparse even if the ticket included the auras.

Also if your auras contain custom code, then those can cause memory issues.

In general using memory is not a problem, due to the way lua works memory is used until garbarge is collected.
