### ISSUE TITLE
Accessing the wago import version

### ISSUE THREAD

**Issue by kopparberg** [WeakAuras/WeakAuras2#3769]
**Is your feature request related to a problem? Please describe.**
To access the Wago import version you have to go through. `WeakAurasSaved.displays[aura_env.id]["semver"]`. I maintain a WeakAuras that communicates with other people through `C_ChatInfo.SendAddonMessage` and it's important to have backwards compability for people who might not regularly update their WA's as not to create excessive amounts of Lua errors. Therefore I'm dependant on what version of the WA the player is using. 

**Describe the solution you'd like**
Would be great if this was stored in aura_env like the id for example. 

**Describe alternatives you've considered**
Like I said, I use `WeakAurasSaved.displays[aura_env.id]["semver"]` as of right now but that's not optimal. I have been told that `WeakAuras.GetData` is better but I havn't explored that option yet.

**Comment by mrbuds** [comment]
There are solutions to your problem that don't require changing WeakAuras addon, like define your own version counter or change SendAddonMessage prefix or message.
