### ISSUE TITLE
[Request] Load conditions per specialisation role healer/dps/tank

### ISSUE THREAD

**Issue by matthiasweller** [WeakAuras/WeakAuras2#377]
I personally use different UI settings for healer and dps specs so some of my weakauras dont fit well in both situations and the currently available load conditions make it hard to differentiate between multiple specs with different roles on multiple classes.
The dungeon roles condition only works if a dungeon role is selected so its not very practical to use that.
A load condition that checks your current specialisation instead of dungeon role would also probably solve a lot of the "spec profile" requests.

**Comment by InfusOnWoW** [comment]
Suplicate of https://github.com/WeakAuras/WeakAuras2/issues/381

(That feature request contains a bit more information.)
