### ISSUE TITLE
Ability cooldown trigger option ''ignore rune CD'' does not seem to be working

### ISSUE THREAD

**Issue by HenriPeegel** [WeakAuras/WeakAuras2#3770]
### Description

I was making a Death & Decay ability cooldown weakaura that ignores rune cooldowns (only shows abilities own cooldown). I found an option under the cogwheel ''extra options'' to tick ''ignore rune CD''. 

This options does not seem to affect the weakaura at all. The cooldown still triggers if its a rune related cooldown. I expected the weakaura not to trigger when the ability was not on cooldown but I did not have the runes to use the ability.

### WeakAuras Version

4.0.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Copied the string of the part of the WA in a text field below that includes the ''ignore rune CD'' option

### Screenshots

Picture of the WA trigger
![Ignore Rune Cooldown](https://user-images.githubusercontent.com/76994383/186432356-6e205ae8-d229-4cc3-b477-064377c82dd7.jpg)

Picture of the WA triggering after using 2 blood runes for something else other than Death and Decay.
![Death and Decay WA](https://user-images.githubusercontent.com/76994383/186432892-e6c44ae8-603c-41a3-b8b4-6423ebafaf22.jpg)

### Export String

!WA:2!1z1tVTXXv8iZ4ydIIGy6e1eL0gv3gHOuazhLuJ60dgALO(JlRe7s6AxeKYD2DFC3XA5mtNzwsrDReia(uoqGEXjTfGFe4TKlTq5lWcIG(bqh6XgaDjxZBMDjTSTipWDM59N59NFZ79wy7kDQewj8XFWiAaN1GNkdG35L87rI47T1W7SrpXgP9(OBl7Fq72kqVWycliMlRZPmT)Mv3Vzv3jbCEsiVhRrpQa8oz62QHrqSKeOPCM62UknrQl7qzuDz)24hvC5bAjnkcKQVyfzXYh)tD1OqhoyQAKkbKKSx4v)2kNLQGwDi6Gyi0nLbEIRzojcyGKg0iM37aM3KNz7Pk7Nnlu2ad)POj4n2SYqmkimEui4N2UDZ(cqUB1A13((1C04gx7Dp0()(KoaAdIkgbrFjc0UWFnLkHqVjMZKqhc6wSO4tvP(qxGPRlH20JCBuVATAU2teV1utz56sEKeuQLF)gg9VQ46gTahHrSwZUX4jsGK0y62Z2ci64LjSWL3cci9Tx8mM9gueRuLNzcnq)IE04wBUrJMTA0Cd3Mog)3xKq6dYXZKFVqVHwpZe89CzO6uLhMYkslLhhsvpkLHzZUW6ewFrLGuLM3Pzo9A8iAG4dAB5GZE)cXwTCzjOtLSLlo4tx)Z(DLldSqX1iwDvi)FGhcLodbvGKrs(tiKa1YHNDiaInq7lq7sq96nubjTTGVSxbtAkcQBIgHzDZLO0i0VDHidK7ElMT0eCRp6qrsEkl8)ojkH3BBjM2awq)6V8TwB9Ft2ssKjdHXM)EybqFGzJbqmXpvR5SdWBadzJmhxdyr643WY)FUG)HMnBYt4Y7vc)Dcgl3z6jXwIncijqjhZYyRH0mMgCidraLS0RrX1xZEboCziiJF8kIFUgos3Y(xBUeX(TeT00oqXUfgoJ(nEpHy5xG71x7z5x8AwQQys4uZDHfwOKyL5lzcerc63QDcNl9olNf6rq4dOH64)M4xnpl88Yfl(zx4fGp(Afqu64rsUgtKnr6o7FW(vhz5mWAG7E3V)Fz(9nL29U)))I5xVsIkNZpMMdMJ)BVKycJbjXI39czXcpAzFYBT3jfmGVFOhdRojVQ3uSH4gZ9EIPHqRJbjp(cmMIathEyldQ170CF4PqAX1TNqsXhwiEpWgID2a3wybt90tS89i8fiTDFuUF58tFcjeqTVnMtsoeP3HK8ugxi)jHHpXQZZjc7JLiObT0XynSySK2cI3zUrftn2HZcPI3yJGamoX0KeSkiOmRd6NhZ7Hq)hijIbpOyrrM(z9FXVE(o8lAzpnBARWFW9BwBV9RkE7luh5lDnQkS41Y565L9k5H(UyKYpb7aDEC4m8XVyErTZLmUX89GzaeXBDbkkFrMOD2sdnL3S1kgN)PLcHRx(KInbZEFFAXjtn7PSdyp6tDsOhFmrgUCDSdD)jfK45(IFmqJI174KWjH)pB)gbO9jADceFAqcrPW4tOPjsWIUDst00Y(yIfZUlMnOSRLJv8vyFXey8wv3O5U)(93BNDBIeDmwRHlBNhg2VclvAwAfY70znNoKHnmJhuSpiVFBxaRFMa3Ng7yoCLSp)Yzdw8kEIx)56JMl9ONU(Q)7FqEmNbyJYl5RSZ84t7i4sTBWSk4JK22igeJJz2OXuwEKhpCrXBsJyCjCGWoDtvtN2QsjxQ8mnknnx3dL5nV01Zgsy0CPUDw5TZwYHH38jarbn0sBJKRmj00fd5WwbsQau0q1adpMRp7joMjlqzZEs2xELSVk7FK9pXL)KN)KjyHdeOwyuL9r10Mgvw86tNLYuEDlQIGqGWy3EMQl)r7anthkbBd7AaEohZ5DQx6wR9roMIrEJ08GIwSxT7)5g0W13ALTg3wItjGEbrtk5sseXKsNL)wzBdfJT73yt3Qv33xbDq5D)W1U1A3A9uA4y6DOF8HRUZ9GhUJKYm6g8wpvMiE7yTwO(KBEtZmORr53C2qO38dLhv8cBKjcrTU5sR4IZdgC4TZE1sd6sKuJ35yMSZTljjfkjn1(JaKXSV2BGqYXqSUF2Vn718Y(7EvuUFmAuRxP739WF8

**Comment by mrbuds** [comment]
Your aura doesn't trigger cooldown when i use 2 blood runes on wotlk beta, only when i use ability

![image](https://user-images.githubusercontent.com/189656/186503792-a37e4bc5-832d-4119-a1ce-980064eb7254.png)
![image](https://user-images.githubusercontent.com/189656/186503627-7732cebf-0abd-45f2-b387-6a4711af8d0d.png)
