### ISSUE TITLE
WA Stays in 'Ready for Update"

### ISSUE THREAD

**Issue by Jorvanus** [WeakAuras/WeakAuras2#3776]
### Description

Updated through companion client, I have updated it, it completes, but does not remove it from the top of the list, listed as ready for update. 

I have reloaded logged out etc but stays there. 

### WeakAuras Version

Weakauras 4.0.3TBC

### World of Warcraft Flavor

The Burning Crusade

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Update through companion add, open WA list, upate, stays as ready for update. 

### Screenshots

![image](https://user-images.githubusercontent.com/89010934/187061309-9476ade4-de3a-4370-8971-a855d4348fc3.png)

**Comment by InfusOnWoW** [comment]
Please include your settings file and a link to the aura you are updating.

**Comment by Jorvanus** [comment]
> Please include your settings file and a link to the aura you are updating.

https://wago.io/jz-ehKg54
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/9439351/WeakAuras.zip)

**Comment by mrbuds** [comment]
This happen when you have a copy of the aura with an old version

from discord:
![image](https://user-images.githubusercontent.com/189656/187071398-41bdd5c0-9dfb-4949-9707-52fdb5b6a5f7.png)
