### ISSUE TITLE
Imported a string, messed something up and now WA menu doesn't open

### ISSUE THREAD

**Issue by OnneOnne** [WeakAuras/WeakAuras2#3777]
### Description

Imported a string for a hunter WA to show cooldowns. 
Something bad in the string/i messed something up and now the WA menu doesn't not appear after typing /wa or /weakauras

### WeakAuras Version

WeakAuras 3.7.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x [string "Error in: Black Arrow':'condition checks"]:85: attempt to index field '?' (a nil value)
[string "Error in: Black Arrow':'condition checks"]:85: in function `?'
[string "@WeakAuras\Conditions.lua"]:648: in function `RunConditions'
[string "@WeakAuras\WeakAuras-3.7.3.lua"]:3829: in function <WeakAuras\WeakAuras.lua:3795>
[string "@WeakAuras\WeakAuras-3.7.3.lua"]:3911: in function `UpdatedTriggerState'
[string "@WeakAuras\GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:2270: in function `CheckSpellCooldown'
[string "@WeakAuras\GenericTrigger.lua"]:2281: in function `CheckSpellCooldows'
[string "@WeakAuras\GenericTrigger.lua"]:2408: in function `CheckCooldownReady'
[string "@WeakAuras\GenericTrigger.lua"]:1948: in function <WeakAuras\GenericTrigger.lua:1942>

Locals:
region = <unnamed> {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @WeakAuras\RegionTypes\Icon.lua:140
 subRegionEvents = <table> {
 }
 Expand = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:857
 yOffset = 0
 anchorPoint = "CENTER"
 GetColor = <function> defined @WeakAuras\RegionTypes\Icon.lua:411
 icon = <unnamed> {
 }
 SetOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:330
 keepAspectRatio = true
 SendChat = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:278
 SetInverse = <function> defined @WeakAuras\RegionTypes\Icon.lua:475
 toShow = true
 SetRegionHeight = <function> defined @WeakAuras\RegionTypes\Icon.lua:470
 UpdateIcon = <function> defined @WeakAuras\RegionTypes\Icon.lua:435
 Color = <function> defined @WeakAuras\RegionTypes\Icon.lua:383
 cloneId = ""
 Update = <function> defined @WeakAuras\RegionTypes\Icon.lua:538
 regionType = "icon"
 GetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:399
 relativePoint = "CENTER"
 SoundPlay = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:260
 zoom = 0.300000
 triggerProvidesTimer = true
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:421
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:339
 SetGlow = <function> defined @WeakAuras\RegionTypes\Icon.lua:602
 SetRegionWidth = <function> defined @WeakAuras\RegionTypes\Icon.lua:465
 states = <table> {
 }
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = ""
 state = <table> {
 }
 RunCode = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:285
 Resume = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:905
 GetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:351
 SetAnimAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:403
 SetDesaturated = <function> defined @WeakAuras\RegionTypes\Icon.lua:461
 Collapse = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:834
 ClickToPick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:746
 SetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:368
 OptionsClosed = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:741
 SoundRepeatStop = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:206
 scalex = 1
 cooldownSwipe = true
 cooldownEdge = false
 GetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:347
 SetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:343
 SetCooldownEdge = <function> defined @WeakAuras\RegionTypes\Icon.lua:489
 color_g = 1
 UpdateSize = <function> defined @WeakAuras\RegionTypes\Icon.lua:298
 PreShow = <function> defined @WeakAuras\RegionTypes\Icon.lua:530
 GetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:376
 SetAnchor = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:318
 GlowExternal = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:293
 SetTime = <function> defined @WeakAuras\RegionTypes\Icon.lua:517
 SetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:389
 GetXOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:372
 yOffsetRelative = 0
 SetZoom = <function> defined @WeakAuras\RegionTypes\Icon.lua:497
 r
3x ...BM-Core\Libs\LibSpecialization\LibSpecialization-4.lua:229: attempt to call upvalue 'GetSpecialization' (a nil value)
[string "@DBM-Core\Libs\LibSpecialization\LibSpecialization-4.lua"]:229: in function `MySpecialization'
[string "@DBM-Core\Libs\LibSpecialization\LibSpecialization-4.lua"]:248: in function `RequestSpecialization'
[string "@DBM-Core\Libs\LibSpecialization\LibSpecialization-4.lua"]:218: in function <...BM-Core\Libs\LibSpecialization\LibSpecialization.lua:160>

Locals:
self = <table> {
 Unregister = <function> defined @DBM-Core\Libs\LibSpecialization\LibSpecialization.lua:293
 RequestSpecialization = <function> defined @DBM-Core\Libs\LibSpecialization\LibSpecialization.lua:247
 roleTable = <table> {
 }
 positionTable = <table> {
 }
 MySpecialization = <function> defined @DBM-Core\Libs\LibSpecialization\LibSpecialization.lua:228
 frame = <unnamed> {
 }
 Register = <function> defined @DBM-Core\Libs\LibSpecialization\LibSpecialization.lua:278
 callbackMap = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetSpecialization' (a nil value)"
GetSpecialization = nil
type = <function> defined =[C]:-1
GetSpecializationInfo = nil
positionTable = <table> {
 62 = "RANGED"
 63 = "RANGED"
 250 = "MELEE"
 251 = "MELEE"
 252 = "MELEE"
 253 = "RANGED"
 254 = "RANGED"
 255 = "MELEE"
 66 = "MELEE"
 257 = "RANGED"
 258 = "RANGED"
 259 = "MELEE"
 260 = "MELEE"
 577 = "MELEE"
 262 = "RANGED"
 581 = "MELEE"
 264 = "RANGED"
 265 = "RANGED"
 266 = "RANGED"
 267 = "RANGED"
 268 = "MELEE"
 269 = "MELEE"
 270 = "MELEE"
 70 = "MELEE"
 102 = "RANGED"
 71 = "MELEE"
 103 = "MELEE"
 72 = "MELEE"
 104 = "MELEE"
 73 = "MELEE"
 263 = "MELEE"
 105 = "RANGED"
 261 = "MELEE"
 256 = "RANGED"
 65 = "MELEE"
 64 = "RANGED"
}
starterSpecs = <table> {
 1452 = true
 1456 = true
 1449 = true
 1453 = true
 1446 = true
 1450 = true
 1454 = true
 1447 = true
 1451 = true
 1455 = true
 1444 = true
 1448 = true
}
geterrorhandler = <function> defined =[C]:-1
format = <function> defined =[C]:-1
3x [string "Error in: Aimed':'condition checks"]:85: attempt to index field '?' (a nil value)
[string "Error in: Aimed':'condition checks"]:85: in function `?'
[string "@WeakAuras\Conditions.lua"]:648: in function `RunConditions'
[string "@WeakAuras\WeakAuras-3.7.3.lua"]:3829: in function <WeakAuras\WeakAuras.lua:3795>
[string "@WeakAuras\WeakAuras.lua"]:3911: in function `UpdatedTriggerState'
[string "@WeakAuras\GenericTrigger.lua"]:834: in function `ScanWithFakeEvent'
[string "@WeakAuras\GenericTrigger.lua"]:1138: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras.lua"]:1692: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras.lua"]:1508: in function <WeakAuras\WeakAuras.lua:1381>
[string "@WeakAuras\WeakAuras.lua"]:1676: in function `Resume'
[string "@WeakAuras\WeakAuras.lua"]:1030: in function <WeakAuras\WeakAuras.lua:993>

[string "@WeakAuras\WeakAuras-3.7.3.lua"]:1138: in function <WeakAuras\WeakAuras.lua:1089>
3x [string "Error in: Stings':'condition checks"]:123: attempt to index field '?' (a nil value)
[string "Error in: Stings':'condition checks"]:123: in function `?'
[string "@WeakAuras\Conditions.lua"]:648: in function `RunConditions'
[string "@WeakAuras\WeakAuras-3.7.3.lua"]:3829: in function <WeakAuras\WeakAuras.lua:3795>
[string "@WeakAuras\WeakAuras-3.7.3.lua"]:3911: in function `UpdatedTriggerState'
[string "@WeakAuras\BuffTrigger2.lua"]:1568: in function <WeakAuras\BuffTrigger2.lua:1560>
[string "@WeakAuras\BuffTrigger2.lua"]:1897: in function <WeakAuras\BuffTrigger2.lua:1890>

Locals:
region = <unnamed> {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @WeakAuras\RegionTypes\Icon.lua:140
 subRegionEvents = <table> {
 }
 Expand = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:857
 yOffset = 0
 anchorPoint = "CENTER"
 GetColor = <function> defined @WeakAuras\RegionTypes\Icon.lua:411
 icon = <unnamed> {
 }
 SetOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:330
 keepAspectRatio = true
 SendChat = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:278
 SetInverse = <function> defined @WeakAuras\RegionTypes\Icon.lua:475
 toShow = true
 SetRegionHeight = <function> defined @WeakAuras\RegionTypes\Icon.lua:470
 UpdateIcon = <function> defined @WeakAuras\RegionTypes\Icon.lua:435
 Color = <function> defined @WeakAuras\RegionTypes\Icon.lua:383
 cloneId = ""
 Update = <function> defined @WeakAuras\RegionTypes\Icon.lua:538
 regionType = "icon"
 GetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:399
 relativePoint = "CENTER"
 SoundPlay = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:260
 zoom = 0.300000
 triggerProvidesTimer = true
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:421
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:339
 SetGlow = <function> defined @WeakAuras\RegionTypes\Icon.lua:602
 SetRegionWidth = <function> defined @WeakAuras\RegionTypes\Icon.lua:465
 states = <table> {
 }
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = ""
 state = <table> {
 }
 RunCode = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:285
 Resume = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:905
 GetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:351
 SetAnimAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:403
 SetDesaturated = <function> defined @WeakAuras\RegionTypes\Icon.lua:461
 Collapse = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:834
 ClickToPick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:746
 SetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:368
 OptionsClosed = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:741
 SoundRepeatStop = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:206
 scalex = 1
 cooldownSwipe = true
 cooldownEdge = false
 GetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:347
 SetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:343
 SetCooldownEdge = <function> defined @WeakAuras\RegionTypes\Icon.lua:489
 color_g = 1
 UpdateSize = <function> defined @WeakAuras\RegionTypes\Icon.lua:298
 PreShow = <function> defined @WeakAuras\RegionTypes\Icon.lua:530
 GetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:376
 SetAnchor = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:318
 GlowExternal = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:293
 SetTime = <function> defined @WeakAuras\RegionTypes\Icon.lua:517
 SetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:389
 GetXOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:372
 yOffsetRelative = 0
 SetZoom = <function> defined @WeakAuras\RegionTypes\Icon.lua:497
 r
3x [string "Error in: Explosivshot':'condition checks"]:121: attempt to index field '?' (a nil value)
[string "Error in: Explosivshot':'condition checks"]:121: in function `?'
[string "@WeakAuras\Conditions.lua"]:648: in function `RunConditions'
[string "@WeakAuras\WeakAuras-3.7.3.lua"]:3829: in function <WeakAuras\WeakAuras.lua:3795>
[string "@WeakAuras\WeakAuras-3.7.3.lua"]:3911: in function `UpdatedTriggerState'
[string "@WeakAuras\GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:854: in function <WeakAuras\GenericTrigger.lua:839>
[string "@WeakAuras\GenericTrigger.lua"]:860: in function `func'
[string "@WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
region = <unnamed> {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @WeakAuras\RegionTypes\Icon.lua:140
 subRegionEvents = <table> {
 }
 Expand = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:857
 yOffset = 0
 anchorPoint = "CENTER"
 GetColor = <function> defined @WeakAuras\RegionTypes\Icon.lua:411
 icon = <unnamed> {
 }
 SetOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:330
 keepAspectRatio = true
 SendChat = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:278
 SetInverse = <function> defined @WeakAuras\RegionTypes\Icon.lua:475
 toShow = true
 SetRegionHeight = <function> defined @WeakAuras\RegionTypes\Icon.lua:470
 UpdateIcon = <function> defined @WeakAuras\RegionTypes\Icon.lua:435
 Color = <function> defined @WeakAuras\RegionTypes\Icon.lua:383
 cloneId = ""
 Update = <function> defined @WeakAuras\RegionTypes\Icon.lua:538
 regionType = "icon"
 GetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:399
 relativePoint = "CENTER"
 SoundPlay = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:260
 zoom = 0.300000
 triggerProvidesTimer = true
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:421
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:339
 SetGlow = <function> defined @WeakAuras\RegionTypes\Icon.lua:602
 SetRegionWidth = <function> defined @WeakAuras\RegionTypes\Icon.lua:465
 states = <table> {
 }
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = ""
 state = <table> {
 }
 RunCode = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:285
 Resume = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:905
 GetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:351
 SetAnimAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:403
 SetDesaturated = <function> defined @WeakAuras\RegionTypes\Icon.lua:461
 Collapse = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:834
 ClickToPick = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:746
 SetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:368
 OptionsClosed = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:741
 SoundRepeatStop = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:206
 scalex = 1
 cooldownSwipe = true
 cooldownEdge = false
 GetXOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:347
 SetYOffset = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:343
 SetCooldownEdge = <function> defined @WeakAuras\RegionTypes\Icon.lua:489
 color_g = 1
 UpdateSize = <function> defined @WeakAuras\RegionTypes\Icon.lua:298
 PreShow = <function> defined @WeakAuras\RegionTypes\Icon.lua:530
 GetYOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:376
 SetAnchor = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:318
 GlowExternal = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:293
 SetTime = <function> defined @WeakAuras\RegionTypes\Icon.lua:517
 SetRegionAlpha = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:389
 GetXOffsetRelative = <function> defined @WeakAuras\RegionTypes\RegionPrototype.lua:372
 yOffsetRelative = 0
 SetZoom = <function> defined @WeakAuras\RegionTypes\Icon.lua:497
 r

### Reproduction Steps

Type /wa or /weakauras and nothing appears

### Last Good Version

WeakAuras 3.7.3

### Export String

[New Compressed (zipped) Folder.zip](https://github.com/WeakAuras/WeakAuras2/files/9439523/New.Compressed.zipped.Folder.zip)

**Comment by SpatenLa** [comment]
your weakauras version is a bit outdated. the current version is 4.0.3.
Version 3.7.3 is 9 months old and doesnt have any WOTLK release.

**Comment by OnneOnne** [comment]
hmm strange, in game the tooltip near the map says 3.7.3, but it does look like i have the 4.0.3 version installed

**Comment by SpatenLa** [comment]
the error also says its version 3.7.3

**Comment by OnneOnne** [comment]
im an idiot. updated and problem solved. tyvm for your help
