### ISSUE TITLE
Talent condition for loading not working properly in WOTLK v4.1.1

### ISSUE THREAD

**Issue by jucaza** [WeakAuras/WeakAuras2#3780]
### Description

The new feature for grafic talent selection on the tap "Load" doesnt work properly. If you do it directly on the "talent" option i will not load (when it should) but if you then select "or Talent" and repeat the same thing as above it will now work, and you could now unselect the "talent" option right above.
It seems like the first term of  the restult of  " **Talent** + or talent + or talent +.... " is not working while the following are.

### WeakAuras Version

Weakauras 4.1.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create a new aura
2. Go to "Load" options
3. Scroll down to "Talent" and mark it
4. Choose a talent active on your character (so the weakaura can be loaded)
5. **See the error:** the aura will not load
6. Now mark "Or Talent" and do as in step 4
7. unmark the "Talent" option from step 3
8. See the weakaura now loads properly

### Screenshots

![image](https://user-images.githubusercontent.com/112370879/187129432-1911f2bf-6c63-4331-8d6d-4188c8d1c804.png)
![image](https://user-images.githubusercontent.com/112370879/187129516-10461d31-daf7-4d09-bfe7-159a68eb8d63.png)

**Comment by GaryOakRobotron** [comment]
Adding to this, a bunch of talents are added to the load conditions for no reason. For example, this aura only had Stormstrike before the update, and now look at it: https://i.imgur.com/WPo2eo5.png

Another issue is that auras that were supposed to have load conditions of talents NOT being selected have the NOT selected aspect of the aura changed to "selected," e.g.: https://i.imgur.com/AJ8jlxx.png this Dark Command aura is only supposed to load when Morbidity isn't selected, but Vampiric Blood is.

**Comment by InfusOnWoW** [comment]
Auras created with pre 4.1 versions that had complex load setups are not converted correctly because the load options fundamentally changed how they operate and thus they cannot be converted.

**Comment by GaryOakRobotron** [comment]
Is this bug going to get fixed? https://i.imgur.com/IX2MMhU.png In the screenshot, you can see that the only load conditions are player class and Desolation being talented. My DK speced into Desolation doesn't have the aura load.

**Comment by InfusOnWoW** [comment]
The original bug reported above is absolutely going to be fixed. You need to at least add your aura to the ticket to have it looked at.

**Comment by GaryOakRobotron** [comment]
`!WA:2!DvvqVTrruyCnikgjq1fSGcfvLdr0EWkjKMkbuv5nXUofNy3DDHIuKYo7UpV7uVEMTZmRDCp6l0luaFLEYN5KVJekiXr0klexRuUYT8lG3mRtIG5G359M37nV5999EUqJYdkhuo453Cg1NZC4PcFOG3isiF3DMU5DATXdGMpkumUDVEsqvyoH5hXfD4uMYB7673TU9cFopoGpI5mIMaUBKkIVKLoyUtucAyiiKVZQILBF(hBRee)(wKufFkjvqyKbG8AZ2bK8yIIYzNMkHdhqu(rqGDkdCNRv4hreHGmAriWab13jIpQnBMe)ulEezS02eOsgJ1Ad9dCTuJtaB9TSrYv0h8FC29ezQhmeykN0E9Ohn)WTR509qNU1S7UqBTagqOmklmAwa4H20fdNOz9wDA8OwlYtrzESYUQa9yFmfCfyPOnlESR(Hu)iIVYjbIJ3ni6etUPf2MNYurtn71ovW2KhjF42lRL3OJGhkaP8gFQX7BMCvTZGoChEUBrleaj258OS48lWKjtK5xSS0e9bPmQYDM(36hrLkPRLEVxsmzmiMQTWanxuw6iaSSy70PERwtXeohclLCfmjOdHU5Y7XdGF51ofjeGGrI)AeVruS)P9biPgMb(kBnUIVwiUNH4i62UtR6n6IvvjrHOJcIedZ97nMH3UneIBLFELSklqrpmRcfyjl4VxegZh1qapnfy(J786RvDJBNvrGgPpyU(NhVKQorlOrSfEPkfN1gVb8PotRUfWcvrVVX(VDP9t1cBZJ5IhuexhJfK7FMMiZHo(KyOOjf6gr97Zq8POLwm)8wuuZvmxGfxeaIOEZ9mBousFgumRYu9RXO54Lh4BUWcfku8KLAgsLuVyK2VugcWI863Od9iiEXsD88u2lcOHrQhAfZjb)HqHPhtTrf7bPXkALx5AavgILIiV8dRK5S1EUVY9lY7Qgc47igIS04eEwPKY52HmnKm0or3qwCMHBy0hzcPFmrkDVGo3NHu2iBJ6v9KyhtmmFN61628R2F373Slg4zxy4L)9Yw66H((8KMjoE0bjCHAMWa8Aql7To(S5k1Xcq0KZKCNHJwcO6etERvTXwq)(nYE7Itgseucw480DQqWk8KvU7DThsItHccC8bdhFCTvZEI7Kebh7JvJZUZQzHAFZIobokHkmZF6shaAN)Y7M9KvwFTS(3cD6bnV3)8Z61lBEVF9661h18E)5NOxxVywSTbgr72AMuZtpup4XQds3SnYj3ExD7rpIpCqTGG2m5bFdq6xd5(Yd2dcOKdC02jpWM7XvwX0KQ8WWf5btN8mi2BpIedswC2txGJpXXW54JSugZqz9WktpAyPK37SIvxeg3Hk1LLGOtZND3qGZg0LypNTTRxFFRNX5d6uCTQFMNegGCf71RUw11NP4(l7jV8WFBfAq27oVN2vhKyOifTjXjr4Nr0av0dtkJKHZgEHteWwE9FfqdM7S5MIEjYi5aHGY0reB2pAzpNqpjbFbBzlveHQKxpCERmQKf(rvAEavQNoTl(U(Glv(G5uwpUyGbLknLWO5B3k77ACmqK6mZ0x)MzvSyCgSiinhsnWbEXAMJCI2udf7fw657nY(E0HSxK9dz)y2pHFF()xtzP9MvxV66Lh(xp(F)d` Will not load, but one whose talent load condition is Ghoul Frenzy will (the Ghoul Frenzy aura is the same as the one linked above aside from the load condition being Ghoul Frenzy as opposed to Desolation).

**Comment by mrbuds** [comment]
Talent1 data of this aura
```
        ["talent"] = {
            ["multi"] = {
                [38] = true,
                [111] = true,
                [29] = true,
            },
        },
```

With the math we use to transform theses indexes into tab/num_talent, talent "38" matches tab 1 talent 38

**`GetTalentInfo(1, 38)` return nil, which mean this index doesn't match any talent, this ghost talent is not represented in the UI**

With previous version multiple talents on talent1 were tested with "or", like `checktalent(38) OR checktalent(111) OR checktalent(29)`
This "ghost" talent index 38 that doesn't exists was tested as false but if you had selected a talent you have the combined test would be true.
Now it's testing if all talents matches what your talent, like `checktalent(38) AND checktalent(111) AND checktalent(29)`, so if one test fails the whole test fails.

Since talent with index 38 for DK never existed in official version of WeakAuras, i see 2 possible reasons as to why the data is bricked:

- Aura was originally made for an other class were index 38 exists, and this ghost talent can't be edited on DK => this needs to be handled
- Aura was imported from **PRIVATE SERVERS** version where the math to make these indexes is different.


Lucky you the first reason is valid to make a fix that will handle second reason.

**Comment by InfusOnWoW** [comment]
@jucaza Apparently the issue that GaryOakRobotron reported is different from the your problem, and thus unrelated.

Your issue isn't reproducable with those steps. Can you a) verify them b) add a aura created with those steps?

**Comment by jucaza** [comment]
@InfusOnWoW Hi, maybe i was wrong and the problem comes from the point @mrbuds is calling out heres is the talent load:
![image](https://user-images.githubusercontent.com/112370879/187206762-24543670-87c7-4530-aa73-326e51717f8e.png)
-
![image](https://user-images.githubusercontent.com/112370879/187206434-f8e6b26d-cc63-4c4f-9fcf-b2c67bb43577.png)
and now by choosing that same talent but doing it below on "or talent":
![image](https://user-images.githubusercontent.com/112370879/187207168-fdaa3101-b562-4a73-a69b-92ee064d010f.png)
-
![image](https://user-images.githubusercontent.com/112370879/187207335-4c31d49d-1e24-4b44-b943-45c187ad27b5.png)

**Comment by GaryOakRobotron** [comment]
Unsure if this is related, but this aura is created from scratch and has loading issues. It's supposed to load when I'm speced into Veteran of the Third War, but NOT Morbidity. Currently, it only cares about the second talent condition. Adding Veteran of the Third War to "or talent" below NOT Morbidity does not band-aid fix this problem.

`!WA:2!DrvVVnsru8ZAbXHLarS4cHpoicKIGcmj5Gi01eL1X(8Dys8TRpYrbk7S7(8oJ86z2BMzTJVsxD1UfefwIoQCpsixqjAKfIgAGqjve4paMz8AZbtZ8EVzEF979rPgv6xjUs8tENPKig1NLZJG34A8loTBxbilXhvqmdrJWmEBgHkdRv)Ko19weXyPXSHu)HKmiy(k26XjaMJIKegvCGNqI4YYHDjuIax2vFjlpwYjjjax8I7WliFYgEsTs9Cr5s2v5c48(izegI9YPqq2ggjjaf4KiFmB4P0Gf)h2Pc91rPdrJeEuuFquEMrfJ0KO4GPXqyE3UDgLb8M1B1UXdA5k1mEImin9srEimaOsF9Fixm78Ah535C)oh51XZkp7vRvKDB3MZs4GqS976Bu99wWbuQL8eTBNFmI3B7AS(9r04f2iy1tbJTK3nwuEYAHx)x(61oVnh0o3ZVD9wTMyu1cibU5Ailmlfnc4tYPf4v5Snmq8aOZs(pLfdF71UsxEaofL(zAWvJ)9UQhazhPDxK0dPRi4jikPVHIEG65BmhqcWxYbAIe)CQTCPmkSioNB)X5geIlaDNrSyS5Rg8tv1TpIqBOEFTcQQQpqTRAp9D5)VenMlqsJTa8uDs6bjMwIBVPARfA2qDYLWz504FErskBydo8OCGgnQ9ZSB19)i1wC9NmpmxJf3rFxJLY44XgrM4yryUuYONoa4ASzQrClBECJzg6pVOZDsYkvVNJ(yF7HfV5AyWwV3btI6r11vhRc(rOuyjzlIw8gw77Y4Xah3vT1etcy5wS86C2stoVGnY6XsLk5CzHKbebjmfcMvWd65KSn8FuoIdB3ipnD7ZWejS6zb5XGtigijy59DtzO4FGl1bfvU)ME9ZtLKn)gC4sjBQozZxjW2Wpa0jskGDn1CT8YtTDs2VHTDvrPiHi4Y19M9O626GcBFRNYufEd7z1yNqbHMKcZoU(rDA(jNC370SJX8)Rn09YUMO26vUTyBQtUMnl7NtIN1mCV9)4MNDw6f5l0J569jNMz3suEgH2LXx2xww9fbErRlyzV8QflDGlKhteinigJNkzrdw2KF9bF)BtIvV1vl3r1GRNRmoo0VMx96NKvrNmRgF1Jj65aiWBijwIVVhkndJCc1ryxsszoHASPUg11ye9GbsICCFmJ1VTZUvV1uZKaXgY3Ehp92POEhOEbNXdqCIjSMzbJhydrVbO0COepcJOjG412rXVxZd)9)YC(7Mh(B)P5C1AcNXzCMEAtosfUJIzmRkl7geQWSskIOReEGWUFwO4oQvg8xFj7znHJJs(uwy(YDouptqO4LwR3F8LMZx18WV7MMZR38WF8nnNBA1F8kmpyIas7Ax7RE2kcVpS6Ev3RYGF6H)d`

**Comment by mrbuds** [comment]
It's working as intended see https://www.lotame.com/what-is-boolean-logic/
