### ISSUE TITLE
Internally ensure numbers are numbers

### ISSUE THREAD

**Issue by Petroslav** [WeakAuras/WeakAuras2#3781]
**Is your feature request related to a problem? Please describe.**
I was trying to create an aura using a dynamic duration untrigger and ended up passing a string as the duration, instead of a number. This caused some issues until Spaten (in the WA Discord) pointed out I was sending a string instead of a number. People like me, unfamiliar with languages like Lua are probably prone to a mistake such as this. Even if they are, mistakes do happen.

**Describe the solution you'd like**
Just do a tonumber on the duration and expirationTime when the result is retrieved from the trigger functions.

**Describe alternatives you've considered**
To be more careful but we are human and this mistake will be repeated some day.

**Additional context**
N / A

**Comment by InfusOnWoW** [comment]
I can't reproduce the issue with the minimal instructions you added.

Please add a aura that shows the problem to the ticket.

**Comment by InfusOnWoW** [comment]
I have asked spaten to explain the issue to me. And that clarified what you did.

That's out of scope of how much guardrails WA provides.
