### ISSUE TITLE
Lua error on one character

### ISSUE THREAD

**Issue by joshhr** [WeakAuras/WeakAuras2#3784]
### Description

I recently installed heaps of weakauras from both wago and friends in preparation to play a new character, i'm not entirely sure what specific weakaura is causing the issue but immediately upon logging in my character only shows certain parts of specific weakauras. 

My fire mage weakauras remain untouched and working correctly, the character having the issues (boomkin) is unable to open WA addon with /wa, doing so doesn't open the addon or give any errors it just does nothing. Reloading gives the errors listed below.

I've disabled all addons on with only WA enabled and still get the same errors.

 

### WeakAuras Version

4.1.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1132: attempt to call field 'UnitRaidRole' (a nil value)
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1132: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1105>
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1797: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1794>
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:2098: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:2080>
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:2143: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1838: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1638: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1491>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1815: in function `Resume'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1140: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1103>

Time: Mon Aug 29 23:11:51 2022
Count: 1
Stack: Interface\AddOns\WeakAuras\BuffTrigger2.lua:1132: attempt to call field 'UnitRaidRole' (a nil value)
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1132: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1105>
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1797: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1794>
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:2098: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:2080>
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:2143: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1838: in function `LoadDisplays'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1638: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1491>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1815: in function `Resume'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1140: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1103>

[string "@Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149: in function <...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147>
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1174: in function `Login'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:1248: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1199>

Locals: <none>

### Reproduction Steps

logging into character

immediately seeing WA LUA error

Not able to open WA with /wa

### Last Good Version

4.1.1

### Export String

[WA.zip](https://github.com/WeakAuras/WeakAuras2/files/9444808/WA.zip)

**Comment by joshhr** [comment]
probably a stupid question, but the fix you made above is there a download button im missing? or is it not completely fixed?

**Comment by mrbuds** [comment]
> probably a stupid question, but the fix you made above is there a download button im missing? or is it not completely fixed?

It needs to be reviewed, then if it's ok it will be merge, and a new weakauras release will be published not long after, but not automatically just after it's merge, before new release you can use alpha version of weakauras to test it, but not before it's merged.

**Comment by joshhr** [comment]
appreciate that, thanks
