### ISSUE TITLE
Combo Points not showing

### ISSUE THREAD

**Issue by vison2** [WeakAuras/WeakAuras2#3790]
### Description

My Combo Points are shown via a black circle when empty, and a colored one when filled.
Im using this aura since AQ40. Prepatch broke it somehow.

### WeakAuras Version

WeakAuras 4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

My Combo Points are shown via a black circle when empty, and a colored one when filled.
Im using this aura since AQ40. Prepatch broke it somehow.

### Screenshots

#
![combo](https://user-images.githubusercontent.com/12114693/187718190-454552ea-2e97-4ddf-a36f-cb2b6f3c8ed3.png)

### Export String

!WA:2!DnvWUTTrq04Qc4gw0uBDWOiTNck8rzlHgR2a0eiQsvNazB6vYXbfQqAj5qYTMAxIzxklLJ8uoRpbDUN0xqr(cwy0VG8j4VGUlLQrr5bYDx(M38M3m7o9QpTEu9Op894IlIJLG6DF(ZpUXZxt5HPc0xW4QGUENp0J0QaZY)2uLkx(IJo6wAIObtC0c44Fko)64lp6hrAOIj4YtisffvoUmot5eeB(itDkviljbq55hIBx(H9(KSiaMbCLpcXS5Kb(E977QwKdUfMG1FDqEgDbGpGBqrSb36XD7my44bd7qg(PCXTaowKdivjWN9YFEzHegxD6esvqeF7Ms7XwwNugvyWAKA9MlRWzt4JlL5qw2RJKoKQdR3KWPtbPdwWROXLwOe39a52GMSkccmsAOznEQxF)Ex1FzbFB95SoIj)JcUXwMbTO8f57tRwpCZ)pteb)5JU3yXaYPzV1yogrDZsjKfx586Ag(LuLvUqAjkuvYEhC2gO7VY4leiX66p9a9tUZSnGgEtckk4rbPaljvDzqvCWe3mbnkUYDcZOszAGIMzQRditlYumh89coyQ)pZ14eHhOB5qQWDyGKXtYac5IF9kpDRd0TN4kzVhSqUxbZn6dUgP526H0TFNZ8dMYquGP57TzoQhACYQxF8AGEthtbjFXP(RWkTx5EB5zzGrsrvm52378Fr)Q82V2AqX0qyuNOOl4YrpWXOZGigD0WnXkh1LHHzW4btfcv6DM(Lj3xKxnv6KVVPBeIGcg)GrgiHPgVK0SXXnAVsjc3ASFXS)6zSOslDD9B2eNV5UHFn7vJyBDmqz6j0AKBzrQ0lj0S8uATGqbpML4C))PQTf36bE996oShPZzETkyrRvDN)BTNl6F(BAVKYztRuZj6D7PFIl30f(iqL2ua8ev6U39VZRJTZCOemPjswAXyzxpWDkLXnXQhOhUR(k9B1xBw(4))jRSXXQCJNEijmfcV5e9x(DpQCgfzuJXxY4HIPbufzgnRa2bdtP8eWGw)71kZr7Lm1cD)1mESa3O6dY)gwcxGWwF2ZEvXZ29LtiHImb(MAN(kTV95R2PwDj5hA0SrR6Z(739p

**Comment by mrbuds** [comment]
> Prepatch broke it somehow.

Can you define how it's broken?

I have imported your aura and tested on beta, it show a red dot when i have 1 point combo, which seems like the correct behavior.

**Comment by vison2** [comment]
Yes, that would be the correct behavior. On my screen, it shows nothing at all, even in the test mode.

I will test this further
