### ISSUE TITLE
Icon Info/Texture Info running without Trigger returning true. 

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#3792]
### Description

Unsure if this is intended behaviour but it's different from before 4.1.0.

I had previously been able to rely on "Info" code blocks not being run if the trigger function didn't return true, and not nil-check those functions thoroughly. After 4.1.0 they are run, at least when selected in config. 

### WeakAuras Version

4.1.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

1x Lua error in aura 'My Raid Mark 2': Texture Function
WeakAuras Version: Dev
Aura Version: 1.0.2
[string "return function()..."]:2: attempt to concatenate a nil value
[string "return function()
    return "\TargetingFrame\\UI-RaidTargetingIcon_"..GetRaidTargetIndex("player")
end"]:2: in function <[string "return function()..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:405: in function <WeakAuras\GenericTrigger.lua:401>
[string "@WeakAuras\GenericTrigger.lua"]:502: in function `ActivateEvent'
[string "@WeakAuras\GenericTrigger.lua"]:615: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:805: in function `CreateFakeStates'
[string "@WeakAuras\WeakAuras-@project-version@.lua"]:3926: in function `UpdateFakeStatesFor'
[string "@WeakAuras\WeakAuras-@project-version@.lua"]:3902: in function `FakeStatesFor'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1448: in function `SyncVisibility'
[string "@WeakAurasOptions\WeakAurasOptions-@project-version@.lua"]:814: in function <WeakAurasOptions\WeakAurasOptions.lua:771>
[string "=[C]"]: in function `ShowOptions'
[string "@WeakAurasOptions\WeakAurasOptions-@project-version@.lua"]:612: in function <WeakAurasOptions\WeakAurasOptions.lua:586>
[string "=[C]"]: in function `ToggleOptions'
[string "@WeakAuras\WeakAuras-@project-version@.lua"]:150: in function <WeakAuras\WeakAuras.lua:146>
[string "=[C]"]: in function `OpenOptions'
[string "WEAKAURASTOGGLE"]:1: in function <[string "WEAKAURASTOGGLE"]:1>

### Reproduction Steps

See basic example in linked Aura

### Last Good Version

4.0.3 I think

### Export String

!WA:2!fovWUTTrquRQa4ccKaevaJG2lcQabjhQKIsJtqpfrzABvi7iSIUXOWiKljhsUwu7sS7sjRCuN6z)jOd9uouOFGc0VacJI(bK)G4VGoKuiPiiaLx4UZm78E77nBTdBmRrqJGF77Lx9QWqfOp(p7Ut5NC52aVCXFu7L7StTnuUFSqowW4AVbwNABr6Ljts)UyTov9tD6SGgjAZeDoFQT5IJh8urNNkP(AMGR2NO0uP2WKXzAdVq8Nk2yLwYIIaP6EpuUD5)yQxMcE(zkTy27vzEWCGRNKfgYUAJZG(tSDMy3Ny)XuJLaMImzS1OrKYiEhd0eDSzgcLxAcDjijC6mqzKFV09dZ4Lu6rp2Oj(jbDMK38iqtOSaBQmc0d5bWvpQv1rB9ydGhuHLkTbP)WdCqcCKLTZzJpOVT1nvC1gUc7eKE5xgGwd5Aqgs9HlUOcfgp6qjsRlU4SH)WNahdp0xWDA1U9)hPi(XG)08VzLkfssggOm2uXfNsnevCDMADa4HQNngrES1OXhE2ORZ4BvBJ07xyqZb7Q9NicG3TZTScUYPj)cAn4nz61kijS03ZVd2pf2xjvdXRKcedSIAY5vLU7A0xiquHN)T7LF3BWTEu)PrsrgQIXalkw)bVYZbXMjcAWVlXRmMoDpYSSen7HKYDUMs8U7EDMcC4O6lJ900e0e2lVRHjEJ9lwCBrAG7JDhPmliEDadhv8XgT0q(wbhqz5Ri(juLQO(n)NAn79Jp55Mk2Bbmt4QWe4kMxc46PxGWS0TNg4URR2eIAK7QqHuVCgL7ssXH5LU3QRm9xlPPfshzWO(Nm2BgtkfY41YsDOu53w41y)5bLLAoY60dYpkTZNgm(S5IV4yXlsVFat5JtvGZhvFpfmdviYtA3TDV1AH)w34b1CDAXcE)jlBw0PMNqLtB2JqtsJP13ewGYen6K06KfSaD8hUT6jEj(f82BYaIL1P9YybB(vR(VO75xE5ZE9zEitczrg3qZ0y5VkT8nUbXxKiK)C961hFNUTF(ZwJLfWQYTHXr1BwjF3l9bSiUqcBpOvXBlRcnt5EnLZQQA)8V(W87AYrp8MGI5nmw5GTubfnw9xavvWFGhPJ3DvXUcoN)gZzughpB(BYDYDZP7M7Hln(8inu9oaM3y(FF()(d

**Comment by InfusOnWoW** [comment]
These functions were run always, but the lua error from them is ignored if the option for that is enabled on the information tab.
