### ISSUE TITLE
[WRATH] LibRangeCheck-2.0 using GetItemInfo on Invalid Items

### ISSUE THREAD

**Issue by DFortun81** [WeakAuras/WeakAuras2#3795]
### Description

I've been doing a bit of debugging for my addon and in doing so I stumbled on some malformed GetItemInfo requests being sent by this addon dependency.

The following items are unavailable in Wrath:
140786, -- Ley Spider Eggs
74637, -- Kiryn's Poison Vial
116139, -- Haunting Memento
133925, -- Fel Lash
75208, -- Rancher's Lariat
136605, -- Solendra's Compassion
129055, -- Shoe Shine Kit
90175, -- Gin-Ji Knife Set

Normally this wouldn't matter, but when the FriendItems command is executed, it causes a hiccup when the game attempts to receive information about items that don't exist in the game files yet.

### WeakAuras Version

WeakAuras 4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Type "/etrace"
2. Notice the "GET_ITEM_INFO_RECEIVED" event handler with a false response.

### Screenshots

![image](https://user-images.githubusercontent.com/15069481/188218563-1e282fe2-67df-4bf6-bbba-65c49d96eeb4.png)

**Comment by InfusOnWoW** [comment]
The bug tracker for that is at https://www.curseforge.com/wow/addons/librangecheck-2-0/issues

**Comment by InfusOnWoW** [comment]
Oh that was the wrong link, sorry about that.
This is the correct one: https://github.com/WeakAuras/LibRangeCheck-2.0

**Comment by DFortun81** [comment]
Posted as https://github.com/WeakAuras/LibRangeCheck-2.0/issues/6

**Comment by InfusOnWoW** [comment]
You should have proof-read your issue.
