### ISSUE TITLE
Weekauras 4.1.2 Returns "weekauras: nil"

### ISSUE THREAD

**Issue by Believe82** [WeakAuras/WeakAuras2#3796]
### Description

After updating Weekauras to 4.1.2 with curseforge. Weak auras stopped working. when doing "/wa" I get "weakauras: nil" as a message.

Reverting to previous version solves the issue.

### WeakAuras Version

Weekauras 4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Type "/wa"

### Last Good Version

Weekauras 4.0.3

**Comment by mrbuds** [comment]
Can you include your data and Lua error as asked in issue template?

**Comment by mrbuds** [comment]
Will re-open if information asked are provided

**Comment by Believe82** [comment]
It doesn't show me a lua error.

**Comment by mrbuds** [comment]
For Lua error:
> If you don't see any errors, make sure that error reporting is enabled (/console scriptErrors 1) or install [BugSack](https://www.curseforge.com/wow/addons/bugsack) & [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber), yes both are needed.

For your data:
> If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the WeakAuras.lua file in World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\.
