### ISSUE TITLE
Warrior Bloodsurge does not reflect buff

### ISSUE THREAD

**Issue by jonathanpowell** [WeakAuras/WeakAuras2#3798]
### Description

I'm trying to set up an aura to show when Bloodsurge procs, however the aura does not light up when the buff procs. I tried using an aura for the slam ability to "highlight when buffed" as well, but neither option is working.

I've noticed the the name of the actual buff you get when Bloodsurge procs is called Slam! not Bloodsurge. Slam! is not on the list of warrior options at this time.

### WeakAuras Version

4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create an aura for Bloodsurge on warrior to glow when active.
2. Create an aura for Slam ability to glow when buffed.
3. Go kill stuff until Bloodsurge procs.
4. Notivce the lack of glow.
5. Rinse and repeat.

**Comment by Stanzilla** [comment]
You're talking about the premade auras, right?

**Comment by jonathanpowell** [comment]
Yep. The premade stuff. I'm kinda new to the addon, but I had no problem setting it up for dk.

    On Saturday, September 3, 2022 at 08:45:13 PM EDT, Benjamin Staneck ***@***.***> wrote:  
 
 


You're talking about the premade auras, right?

**Comment by ArtfulDodgerB92** [comment]
Necro!  Bloodsurge proc still does not work, even with the built-in "premade auras" tool.
