### ISSUE TITLE
When using a dynamic group and an icon with a condition that alters width/height, other elements are not repositioned

### ISSUE THREAD

**Issue by lassevk** [WeakAuras/WeakAuras2#380]
I've removed all the steps where I would simply answer "No" or "No idea".

What steps will reproduce the problem?

1. Create a dynamic group and add 2 icons
2. For the first icon, add conditions that alter width/height depending on X, if the group is set to grow horizontally adjust the width, otherwise the height. As an example (my example), I set the initial size to 16x16, then add conditions that said that if "icicles aura had 2 stacks, set width and height to 28 (+12 up from previous)", 3 stacks = 40, 4 = 52, 5 = 64.
3. Play

What is the expected output? What do you see instead?

I expected d that when the width/height of the icon is changed, other items that follow in the same dynamic group will be repositioned to make room for the icon that had its size changed.

What I saw instead was that the icon that changed size grew behind following elements. The following elements did not change their position.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

Yes.

What version of WeakAuras are you using?

2.5.8

**Comment by InfusOnWoW** [comment]
That has also been the case with animations that increase the size of items, which are a lot older than conditions.
I'm not sure we want to actually change that behaviour.

**Comment by emptyrivers** [comment]
Stale issue.
