### ISSUE TITLE
LUA error in Druid Core

### ISSUE THREAD

**Issue by Tengill77** [WeakAuras/WeakAuras2#3800]
### Description

When using Druid Core i get an LUA error with the following skills.
Rake, Rip, Thrash (feral)

### WeakAuras Version

4.1.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

---------------------------------------------------------------------------------
Rake:
Message: Lua error in aura 'Rake': Stacks Function
WeakAuras Version: 4.1.2
Aura Version: 2.0.23
[string "return function()..."]:6: attempt to perform arithmetic on field '?' (a nil value)
Time: Sun Sep  4 20:47:06 2022
Count: 2
Stack: Lua error in aura 'Rake': Stacks Function
WeakAuras Version: 4.1.2
Aura Version: 2.0.23
[string "return function()..."]:6: attempt to perform arithmetic on field '?' (a nil value)
[string "return function()
    local name = "rake"
    local fs = feralSnapshots
    local unit = UnitGUID("target")
    
    val = fs[name]["current"]/fs[name][unit]
    
    return val
end"]:6: in function <[string "return function()..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:405: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:401>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:503: in function `ActivateEvent'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:615: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:537>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:805: in function `CreateFakeStates'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3947: in function `UpdateFakeStatesFor'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3923: in function `FakeStatesFor'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1448: in function `SyncVisibility'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1474: in function `PriorityShow'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1432: in function `Pick'
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1311: in function `PickDisplay'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua"]:1180: in function `PickDisplay'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1388: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1387>

Locals: <none>
----------------------------------------------------------------------------------------
Rip:
Message: Lua error in aura 'Rip': Stacks Function
WeakAuras Version: 4.1.2
Aura Version: 2.0.23
[string "return function()..."]:6: attempt to perform arithmetic on field '?' (a nil value)
Time: Sun Sep  4 20:50:04 2022
Count: 1
Stack: Lua error in aura 'Rip': Stacks Function
WeakAuras Version: 4.1.2
Aura Version: 2.0.23
[string "return function()..."]:6: attempt to perform arithmetic on field '?' (a nil value)
[string "return function()
    local name = "rip"
    local fs = feralSnapshots
    local unit = UnitGUID("target")
    
    val = fs[name]["current"]/fs[name][unit]
    
    return val
end"]:6: in function <[string "return function()..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:405: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:401>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:503: in function `ActivateEvent'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:615: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:537>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:805: in function `CreateFakeStates'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3947: in function `UpdateFakeStatesFor'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3923: in function `FakeStatesFor'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1448: in function `SyncVisibility'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1474: in function `PriorityShow'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1432: in function `Pick'
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1311: in function `PickDisplay'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua"]:1180: in function `PickDisplay'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:513: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:464>

Locals: <none>
------------------------------------------------------------------------------------------------------------------
Thrash (feral):
Message: Lua error in aura 'Thrash (Feral)': Stacks Function
WeakAuras Version: 4.1.2
Aura Version: 2.0.23
[string "return function()..."]:6: attempt to perform arithmetic on field '?' (a nil value)
Time: Sun Sep  4 20:51:11 2022
Count: 1
Stack: Lua error in aura 'Thrash (Feral)': Stacks Function
WeakAuras Version: 4.1.2
Aura Version: 2.0.23
[string "return function()..."]:6: attempt to perform arithmetic on field '?' (a nil value)
[string "return function()
    local name = "thrash"
    local fs = feralSnapshots
    local unit = UnitGUID("target")
    
    val = fs[name]["current"]/fs[name][unit]
    
    return val
end"]:6: in function <[string "return function()..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:405: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:401>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:503: in function `ActivateEvent'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:615: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:537>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:805: in function `CreateFakeStates'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3947: in function `UpdateFakeStatesFor'
[string "@Interface\AddOns\WeakAuras\WeakAuras.lua"]:3923: in function `FakeStatesFor'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1448: in function `SyncVisibility'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1474: in function `PriorityShow'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1432: in function `Pick'
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1311: in function `PickDisplay'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions.lua"]:1180: in function `PickDisplay'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:513: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:464>

Locals: <none>

### Reproduction Steps

Go to the WeakAuras window in wow.
Open up the Druid Core list in WeakAuras by clicking the plus sign.
In the list select the once with an exclamation point.

### Screenshots

![WeakAuras Lua Error](https://user-images.githubusercontent.com/112824457/188329674-699c9a15-ad9f-4332-9d53-744be6b1a459.jpg)

**Comment by InfusOnWoW** [comment]
Not a bug in WeakAuras but potentially in the aura you have there.
