### ISSUE TITLE
Unit Count includes pets

### ISSUE THREAD

**Issue by zerbiniandrea** [WeakAuras/WeakAuras2#3801]
### Description

I'm using a weakaura to track the number of people with missing raid buffs such as arcane intellect or battle shout.
Since the last patch it broke and it seems that some pets count as players, even if "Include pets" is unchecked. I've seen this happening specifically for the Power Word: Fortitude and Arcane Intellect WeakAuras.

The trigger itself is kinda basic, I'm just checking if unitCount is less than 100%. I'm filtering by spec in the arcane intellect and battle shout WAs, but the bug happens in the Fortitude WA too.
In the display I also have a text showing the number of people with the buff and the number of people in total (%1.unitCount/%1.maxUnitCount). When this bug happens, it shows something like 5/6 or 5/7 (in dungeons).

I've tried fetching the unaffected names and printing them and, while it shows the names of players without a debuff when it's missing, if all the players have the debuff it prints "None".

It looks like this bug happens the first time I enter in range with a warlock (and maybe other pet classes too, the only tests I did were with a warlock). It'll show the missing stamina and arcane intellect buff, so I suppose the pets count as a "warlock" since the intellect WeakAura filters classes based on spec. 
If I open WeakAuras or /reload, the WA will report the correct number of players and not trigger until I change zone and then go back to the zone with the Warlock player.

I'm not sure if this started happening after a WeakAuras update or just with the new WoW patch, but it never happened to me before this WoW patch (9.2.7). Other people commented on Wago and are having the same problem with my WeakAura, and all the comments reporting the same bug are from the last 2 weeks.

### WeakAuras Version

4.1.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

This is how I tested the WeakAura and was able to reproduce the bug multiple times:
1 - Invite a Warlock in a group while playing a Priest (mage should work too, but I've tested it with my Priest)
2 - Teleport outside a dungeon together (we used Plaguefall on Mythic but everything should work)
3 - Be sure that the Warlock has his pet out (tested with a demo lock using a Felguard)
4 - Let the Warlock enter the dungeon, and wait until he finished loading
5 - Enter the dungeon with the Priest

The WeakAura should trigger (which is correct if Fortitude is missing) but it shows something like 0/3 or 0/4 even if there are 2 players. Using the buff will show 2/3 or 2/4.

### Screenshots

![image](https://user-images.githubusercontent.com/43417875/188876849-f9ad8ed4-6ddf-465b-8601-70905439658b.png)

### Export String

!WA:2!TN1AWTr1v4OOKcOqIvKtnjUzab5X00P4eBh72KHzOs2s2oX2YSsoo8u3v7EL2fVA3n3DLF1sHycu3hukck99lv6BAP1n03pOU0HY0hCQiqH2Y0wxkTf6dQl9X0HzON7Dx5iBN8N0FWWmWpSU37E3Z9CpNZ333zdbYhPye1ios7TLwBPTiQZ0bBYu5Z7qD79nm1)9bV0x4fE6fCSyU9ozoMUAg5Cg0K2BTB6ywU6wMrJvIjh9IJgVu(8rZWKvgLY0SVGymfztA0(mDPgguf3vSJTpK14uw0rSyQ7pAs086ULuPRyBVQ4YUUg0OP1SkTcJmRUzElwrzUFeAbztfnlwsMCrAMjTP5s3LuIedww2u3BhDgVOSUzY4U4dJBAzsRQIUo)jz5lXCOkwMQottLDega2WC8HPDzuZcUANLKJRmZnjSEydqdqyyJ4VroRC51n1D0w(Ysg6f1DxxzhQr(HS0nDJ3FIKzAReZWERAUU2o7F37EC5cwTOBTB9rg9k2BIJCX67U12klZu6xCEhRPPl5q7NBgTzZHHjkRlldl2bceiqWkElKqTa1EJPpsjzgnAYsggrhrt3LYMWp)DF3sx3BdRAvRH5feOAvLl5IbPu28RTtOCCxOVUlVOhWgdJd4J2sBL0vNLznmn1ODFG(Y5wjpA9U0zkgusoMSQEjNJDU5WawE9cHQ4AP4)IBoajRVZLwFk6AR4ukNeTG40kxGzvYUp8L28Qp7lJHHZcfOSaso2Yk01vnhMuvzw2E3YGbdouW90shlGXokZu24qEhWO58SUwohRsmfAo9I2y1Z0mRXtZTtW59EECFRzhoUH(utjZuJMXYYWv3oNdTi6Ty5(EAPT582Tx86CMh9n0TmDtkR4AXYjfR7(goTKJISbnyCoia2WS55vyyvHSRCq8yDfLqbQWe3sEHZCQtAkxuxrCDRWlQ09c3yzRyqNXXAg3qqJHGnfAwV6wrrsUUsmyMes(P7(mrFk4SkwgLkA6D5IByjRMmNl6pMUnjvSeEHcjPyi740e0FO4oym3BGnvHpqs2qVGj0Z0UmDE02P5DwUKP)Kqm)b3804(nm6t1jeSEjzew0w8sOlMZ2qEsmurhdpUC9sLnC1QOsZHGq(fL1BI(hk5W9ppMKfBjn(a9jMnBxXsNjB6mXKYS4JgIrXhjLEOe93VegEOoHMUaNpbTZfj1Dz(4r0vD1wxCmUnUKuF90BMlsx1oIKSUQa37ud4hzStC4ikhyMDbRoa6ooYUCGmvdo7qW5aHG11jCUlhqcnUIv20YxzHrPu7y8qNRepRQbTd7DofSSr1ACtoytRIoMptlQ826QGlia86H9bV2ROjy9vXBkVeMN1nvNzZ2BXLoHBwXF8yPY64pa2GDJI1r0OfNCsrCZJhdNwrurrZGpo(GPgmrvVYJd7vHgOQV9mDfjGudNP)(gmHDeXYoAYOJE5(B1ENRWbATLIYtmmMy7c9r3f9Mf82J(euVuWrpLVkVGya5jw6RoNypJP7OJYcKYl6D2HtY0Nk6LvswLduIMjZj9CoXW28MoowOpct2E6r8hmV3fzrwZydNjL92onEZsDLYlUl7TUJ62WU3XsV2(r0fdtHRl2Dsgw)LRdCc9urSKsn(PGW6zysxCIrQB31YvljRuBrVa21wYXvp)KqppA5cg1o2G4XkM2VUj1z9X5d1Mdfb6P2w0MMVgpZlneMTmQkMQPRmk(coNJN)WxRIWmcDKgfJJlyuicZNwqNnlFyTGGyYI1y8jjz0JuIAQmPGfoVppP)LNhG8jPYsrybC(W6lZR)fl5ZaVyvrv)5wcZV4lY5QcoZwSVWvKDTZ6QxKM1Mrv05C(bpfyjB)bs8TQcgqrWeSa7aWragmtaWjau6O2760zCFo6SUAmQJgIWNegxdMOsIjWJ1XzC5jHP2f8gH3eCDqp2N)PZmEZca3Gu8HtM8cHPda3Oi8ahBoeCMqkB8uzYKAa4M8RyGBgElRDjLl(5G7EvWBf5PRX2OLtJQxqZ9OWRHRPcxeSnPtw5zhbll6YFRdyPI0vuI9MQ9YC2JU1D4TQPQbTokKe6b2mSfPXfWBy7Bj(uwwf5P22HDmRwVL6SyxUhzcL9bxAW4CkoYSQ6oC2Fp56ipp0vZ7usrJQmANq61o9yYmDU5JJXUXLgt2Oenitrt2Sa1z)7CABu5LYCNKl)3s7TWlOGJt2j8vSJWxPJwQN2W)jBM)K2AzLaj44Rf2vOQ1UCPhx3MsGU7es4lHY0n5TFGcahym2uyNDOq2QHuC9pyq(FNfJwz1nfcYAWa8Ly(tXX7modLyisI5e4G(6M2AYbHl7lStqkeKEMTUaQJAXO9zwRSgUc4kR4Ty3uzvYSI3hriiht8w3ZE2Xc8t1tTSlUcTgdxyqu6tJ7pC(iXK546Tc9xDvNMJ36E7yFajuvClXuCljBKg1Jil4DdumWMKhI66OnpUWaYUkAEhOMDeFxr3bZyMOegvv8wjMa76iTN8oboeCFvZtXxJRQoGmBupcgUNlzzGrWbgl(aX6jbj(aPg8GKCdj1xI0zisDlnCFDtyJetQ)uDHRNU3ydeBqcBOy9J9iniz(AwXZDi8Ex9U0qgSNcy4kYlEzEQhMOgMCSWKJs(jKJhMCJK7kmztHjBpm56iRjm56j3rycCy4YHRbYcxfC12nwxOnfwyjJnNf5skZdCIwjA2o8Y)Gd)0wy845HYSIampEtMUwB)rATI)tu6dHjy60EJ8fkqnPmDf8togpLjpKnsvgv46EwajiRFhZ7i(PgAKvYu0WtCU4oEZpeC4kIiXU539CENgwI15rXB71tkVOJfaZ6L5NVlVlhI)f48Mx0DNEEDfVVZbMNa)UaI7KMfQIyO7oPMDJ85uEQ(K3un4H0SBsu4SYsdEcklxJuuta)MiTc)ArjnmauD(6EjEPn80bGNe(9W1SAHdk8imdzVjErC0U0K5D2Ire0DuCe35RA1Wtb)b4zi2ruqToRIz860SFRc6k27pFjtrRWVA)gq3vOO4)XOyJCMr9x7kB9QJkBQU402V6qutv7nYBIEmQV9qUp6DVkoz11km5y0CENhCHHWUhH1cXG7bAc6r0SiK))7EeHcIUcbnnqFzDacx7mBggf31YeJqLiS9euncgd)zCcmbGIlBZxC5ndxpU6nahTETdKUUEbJaCbnuD4rH3MOlb4TVE4DOb3Ig8oHBfExOWpCBq5gHBNa3rq4DhaUZaW7Xt4gEVEM89X1OH3p8biWhmi8HqHx4dhe(iWh90jDcFmpfrOsDcHWhhL6G7AjU6NyPABWN0tjd(uAWNUo1l4Z4TRplb(C1Rjb3nxpc(8lkgDOoADS0Dy52EpOyeCpe4lU5vVM)cx)b(sCThyw4ldhpiCV7hvnGVQN6b818)9R7PwaFJLOqaFtU2a8TwIQa8T91cGVdxfa(Ue4(8P)HVxDu)NhmNhY47tG7h(bWd2C8o7811ocxHFeb(Pe4H8WqpGg8drlENssP6z4ee4Hf8Ls9LsImB3jq(0EhM)1DKC()cpcbEmc8Z5pnwMEp4G8p5Hapob(fAWt08C1)p9bNf9xottz2o5UAGCBKJ3aztBNC)HjNim5jdtUfYZ1azVHjDhMKjm5HiUHj3FdKt0a5wjpzdKBI8Zi3UhHkseZjuHFvKlHtUwhjjh9Zjb(TcIqojdY7HencCphklyYG)i8N4Cx3kAWBtqlGbHNPgxvtWF2NEc(RCYh4VrGN9uWV88WFVokfybUV9pwkTb8CW)e(xyL0)g(p(q5Z6LHYVedkhZzFhzcJlVdhJdEsOCJT)IiuEt1bLrq2d2SuBT2rNTXRIrq8pwJJM5LRig8b4yq7x5P8FMsoEH3BYYHui7WzmKAn16bQEuvtcVj9mBSMfW3gruiUcT9aWj4ajUL4wKFu1bL4ViAPtju6v8YqPxIbLA)GTDWu4N63vXdDsOuKh5ftOKOjr5CowSC8UW8WvE6JTT3o7WhtXl5FwbAIxF(4ELRprZvxY))deGjeWSm8u1I8pWH641NDvV(Shqh7g2SWzmo7gr1YB6mw66XoJKUwtn8gpL))o

**Comment by mrbuds** [comment]
Do you use 4.1.2 or an alpha version?

**Comment by mrbuds** [comment]
Can you post a screenshot of the top of /wa options with version number to confirm?

**Comment by zerbiniandrea** [comment]
Sure, here's the screenshot
![image](https://user-images.githubusercontent.com/43417875/188900279-aca86416-e99f-4786-9f0a-180c2ef58579.png)

**Comment by mrbuds** [comment]
Fixed with https://github.com/WeakAuras/WeakAuras2/commit/bad8758d512c0b45b82654bbd16a84188c4597d1
