### ISSUE TITLE
Swipe does not reflect essence reloading

### ISSUE THREAD

**Issue by githubcmass** [WeakAuras/WeakAuras2#3805]
### Description

If you create an icon based on character power -> essences and enable the swipe on the display tab, it will not reflect the next essence recharging progress

(version is DF beta)

### WeakAuras Version

CI-Beta #156

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

see description

**Comment by InfusOnWoW** [comment]
We don't take DF bugs atm.
