### ISSUE TITLE
Load - Instance Size Type: Battleground not working

### ISSUE THREAD

**Issue by theoriginalmre** [WeakAuras/WeakAuras2#3806]
### Description

In WotLK Classic, having a WA load in a battleground via "Instance Size Type: Battleground", does not work. 
Instead, it needs to be set to "5-man Dungeon" to activate in a battleground. 

### WeakAuras Version

WeakAuras 4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Load any WA in a Battleground
Select "Instance Size Type: Battleground" for the WA
(It will not load.)
Select "Instance Size Type: 5-man Dungeon" for the WA
and it will load.

**Comment by mrbuds** [comment]
> ### Reproduction Steps
> 
> Load any WA in a Battleground Select "Instance Size Type: Battleground" for the WA (It will not load.) Select "Instance Size Type: 5-man Dungeon" for the WA and it will load.

Did you test only in Alterac? Blizzard API is bugged in this one

**Comment by mrbuds** [comment]
If you can replicate in a battleground that is not alterac, can you show result of this command `/dump GetInstanceInfo()`?
Otherwise this ticket is a duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3300

**Comment by mrbuds** [comment]
No reply from reporter.
