### ISSUE TITLE
game freezing

### ISSUE THREAD

**Issue by daddy-winston** [WeakAuras/WeakAuras2#3811]
### Description

with WA active im getting freezing randomly, some are lasting 5-10secs.  this started yesterday i have removed the WA packs i imported and this didnt help. i also cleared my wowclassic cashe... didnt help. im all out of options so i came here. ty

### WeakAuras Version

WeakAuras 4.1.2-16-gb342deb

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

no log

### Reproduction Steps

1. turn it on

### Last Good Version

2 days ago

### Export String

freezing with no strings active

**Comment by Stanzilla** [comment]
Needs more info

**Comment by daddy-winston** [comment]
I fixed it finally,  had to update my graphics drivers
