### ISSUE TITLE
Ghoul Frenzy cooldown tracking does not work with "Ignore Rune CD" trigger option checked

### ISSUE THREAD

**Issue by Nnoggie** [WeakAuras/WeakAuras2#3815]
### Description

When creating a WeakAura for the Unholy DK Talent ability "Ghoul Frenzy" from the templates and then checking "Ignore Rune CD" in the extra options of the trigger the actual cooldown of the spell is no longer tracked.

https://dl.dropboxusercontent.com/s/772z3eaa192bk6s/WowClassic_vyfwErD0FH.mp4

### WeakAuras Version

WeakAuras 4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Open WeakAuras and create a new Ghoul Frenzy WeakAura from the templates
2. Go to the trigger of the WeakAura and check "Ignore Rune CD"
3. Press Ghoul Frenzy and observe

### Screenshots

![image](https://user-images.githubusercontent.com/27819512/189970612-1af855f1-2b09-4fa1-8b36-fb5dc8670951.png)

### Export String

!WA:2!Dv1tVTTnu8A4vSodSbhV2aKTDWOdlyByjRlBnh2nlx7M05A7kPSKEYMsIwInYKAKu2XbyDOUxYz)rqN3j)jyiFci0g2hG(riN2X9iLTrB9bjYh57p)(PFVNl1U24Ab1cU6lZi(mQdlL7J)IBLJsLrmEVejHrfv4Z6nAKallTer9b79zeQ0RzRUUTSZ9zS4a2uQZuscE41R32kiehXr(MiCOTqI4YkEJiuIiQIf8swzUKtcdXCXNSlF1YRQAlbNo3ckaMLCwc2wKGJJxyE2fngFN)7O3is9WtWuPt6OrKlwoOzdh3boUnSDVjvGhmgj9JWb2Pu8WKT0wcXumN47eXM2Jom)D2MjGxnINIMjSPqcevY5yuSZ6eE9JJyPX1BZX0lNLRJ2MAz4CZYJdevSnfuYonxb)695SqowiQ)1Mi9nBk6(Cmu02o9B1PJvkWdEjXOzy(cDOnGFywa2dGMlaF(rT60V9jDwKsxrrvs2sZQtWUf7Fkla)N36g4lcMtrX)kWNaLF(nNJXjnG6ZxAJGpcrlquYy9k6HQpQ91yKa7ibqfkJ(qvvlkJIZds5MBmqZ8CbgKebI56RQRf1EwJreAB13boO2tTV67vpaEx59Ta1Vaj1XchLb42ghQvb)82QQ5WwpaJHCwkn4Q7MutIVqoqeHaw7SvYSKDmgnpgX4qvpqSAHAVfBo7(FLiP6B5EtwmJ)KsLkv(nfwXXJmsvRgN42l5tng1clnn4Fkjqgz1a2EtrIixGdmgFvEHm)5RkNRnN)IuHKmAM62zCMeqMly0QBVUTuv5aO03jZCrFtzug(TyfcaHr12CYL1FwkkayfuDx33b4RZuUX2ugp4uokz(PRwuuaticIxmiPlW8B1kMS1XD72YEGvpx3Ep1(4hFKB(Mu7qUeVZkeD27Kh9PgnwVtC7CC3w)BEymBki0)Tum1Fw)p4b7FWdlqN(GL6hRJWC9gTZ5EPsjJ2BcMdY4mT5ogr19m3FnYwO30CdZCni2F8Alrw6dJmz3nI4Fof6BkB8WXhfJlw2HaM3YKalGxW8iVimjms(mRygkyKP)Xpgjed9KGxu522JtJLKT)7HwcGe2w5vX2CHD9eeAymE5JA1W9OFPRMWGdT0Dl6BLzAfnXikJBeVAOAPhrUyJQsD7K7UEANwm8iIabFFcIwsOfIvWVk3uW8T5W8cDq8CAA3QvxRlzSXLuVyyMK5pPON9ot(R7tcs(83EGtDsiLXX15WWS6(b8lw3IudQX1dBGraqpoEO9uT89zhKscw2rCPth2Zd(ruIhu2JiHv4eQotW9qXjrOYlhPlkyiaOilNP71jMP1F7U2W8t)Zp0EckofxE(eeNOHwY9iuHEMRpbOgBSW83fc1hxM7hHOHyXNTR6LpPF5hS)dnpkxEEcNbkm5mBtBXUQF)q1llR(JmgDD1dURE175yH3Q5QxpFnfpu9AJ0PMW(N2)h2)GAt(NZ()p

**Comment by mrbuds** [comment]
Thanks for the report, i can reproduce issue, but no idea how to fix it..

For Infus if you can help, to reproduce you can make premade 70 DK on WOTLK PTR
Need this talent
![image](https://user-images.githubusercontent.com/189656/189990437-d5fd73c8-d02f-41a5-80e9-ea72f383d6e3.png)
Use "Death Gate" (unholy spell) to TP to Acherus, go down, find corpse dust vendor to be able to summon ghoul https://i.imgur.com/6lwOw7k.jpeg

```Lua
local spellname, ignoreRuneCD, showgcd, ignoreSpellKnown, track = "Ghoul Frenzy", true, false, false, "auto"
local function GetRuneDuration()
   local runeDuration = -100;
   for id = 1, 6 do
      local startTime, duration = GetRuneCooldown(id);
      duration = duration or 0;
      runeDuration = duration > 0 and duration or runeDuration
   end
   return runeDuration
end

local charges, maxCharges, startTime, duration, unifiedCooldownBecauseRune,
startTimeCooldown, durationCooldown, cooldownBecauseRune, startTimeCharges, durationCharges,
spellCount, unifiedModRate, modRate, modRateCharges
= WeakAuras.GetSpellCooldownUnified(spellname, GetRuneDuration())

print(startTime, duration, cooldownBecauseRune)
```

"Ghoul Frenzy" cd is 10s, same as GetRuneDuration(), so cooldownBecauseRune is always true

**Comment by InfusOnWoW** [comment]
Yeah, then we can't fix it. The api does not provide the information what the "true" cooldown of a ability that uses runes is. (At least the last time I looked.)

Thus we can't distinguish between abilities that are on cd if they have the exact same cd as runes.
