### ISSUE TITLE
WeakAuras no longer shows timers for Premade Auras

### ISSUE THREAD

**Issue by CatalinGhioca** [WeakAuras/WeakAuras2#3817]
### Description

After upgrading to WeakAuras 4.1.2-19-g6ffac56 I can no longer see the timers for my Premade Auras.
Only a created aura that I downloaded a few weeks ago has it's timer active.

### WeakAuras Version

WeakAuras 4.1.2-19-g6ffac56

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No, there was no error. I don't have BugSack or BugGrabber.

### Reproduction Steps

1. Download WeakAuras.
2. Create Premade Auras.
3. Update WeakAuras 4.1.2 to WeakAuras 4.1.2-19-g6ffac56.
4. Enter game and activate abilities that are tracked by WeakAuras.

### Last Good Version

WeakAuras 4.1.2

### Screenshots

![WoWScrnShot_091522_011210](https://user-images.githubusercontent.com/19155341/190272117-a6c48881-78a8-412a-937c-2ed058a25df5.jpg)
![WoWScrnShot_091522_011313](https://user-images.githubusercontent.com/19155341/190272259-8ce04542-ce10-43e1-832c-91e95b3fbcf8.jpg)
![WoWScrnShot_091522_011335](https://user-images.githubusercontent.com/19155341/190272285-34050104-45ae-4227-b1ed-5d95bde5ac3b.jpg)

### Export String

I tried to paste it but the string was too long to be uploaded. Is there any other way to attach it ?
I can't attach the file either.

**Comment by mrbuds** [comment]
I can't replicate and nothing was changed that could affect this recently in WeakAuras.
It have to be a problem with your elvui, omnicc or the option not enable in action bar options.
If you need more assistance feel free to come on discord, but i don't think it's a bug in WeakAuras;

**Comment by mrbuds** [comment]
You can come on discord whenever you can, if you expose your problem i'm sure someone will help you any time.
