### ISSUE TITLE
Unknown Difficulty ID found

### ISSUE THREAD

**Issue by GatsuGaming** [WeakAuras/WeakAuras2#3819]
### Description

Opened up DFlight/Beta client and got this error: 

![BetaError](https://user-images.githubusercontent.com/112674640/190490295-1c065901-8084-4ddf-adf8-26d3e42ce179.PNG)

I have done a full clear of all saved variables, settings, and even fully uninstalled DF Beta client. No change.

Used version linked in DF channel on the discord.

### WeakAuras Version

Weakauras 4.1.2-19-g6ffac56

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

6x ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:156: in function `CreateFrame'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:779: in function `ShowOptions'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:612: in function `ToggleOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:150: in function `OpenOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:192: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5218: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4882: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4918: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
frame = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 lastArchiveClear = 1663268490
 minimap = <table> {
 }
 lastUpgrade = 1663268494
 dbVersion = 53
 registered = <table> {
 }
 editor_font_size = 12
 login_squelch_time = 10
}
odb = <table> {
 locale = "enUS"
 needsRebuild = true
 version = "4.1.2-19-g6ffac56"
 magnetAlign = true
 spellCacheStrings = true
 spellCacheAchivements = true
 spellCache = <table> {
 }
 build = "45569"
}
(*temporary) = nil
(*temporary) = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
(*temporary) = 750
(*temporary) = 240
(*temporary) = "attempt to call method 'SetMinResize' (a nil value)"
CreateFrame = <function> defined =[C]:-1
OptionsPrivate = <table> {
 SetCollapsed = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1741
 RemoveCollapsed = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1789
 AddTextFormatOption = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1872
 OpenUpdate = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:886
 ClearOptions = <function> defined @Interface/AddOns

### Reproduction Steps

Load into character, immediately happens

**Comment by mrbuds** [comment]
We don't take Dragonflight bugs yet.
