### ISSUE TITLE
Add bar color gradient support to the 'Bar Color Settings' UI section

### ISSUE THREAD

**Issue by tom-etchells** [WeakAuras/WeakAuras2#3820]
**Is your feature request related to a problem? Please describe.**
Bar gradient colors can be set using the 'custom code' options and calling aura_env.region.bar.fg:SetGradient("orientation", minR, minG, minB, maxR, maxG, maxB) or SetGradientAlpha("orientation", minR, minG, minB, minA, maxR, maxG, maxB, maxA) commands. 

This works and isn't too difficult but can be a pain to have to type RGB codes rather than use a color picker like when choosing the basic bar color.

**Describe the solution you'd like**
It would be nice to have a more user friendly configuration option in the default 'Bar Color Settings' UI section (and accesable from the 'Conditions' tab as well). This would likely be a checkbox ('Use Gradient?') which would create/unlock a new color picker for the second gradient (or maybe 'lock' the default picker and unlock two unique min/max color pickers to make undoing changes easier).

**Describe alternatives you've considered**
Using the 'custom code' options to set manually, this works so I guess this is low priority but a more user friendly method would be nice.

**Additional context**
Bar gradient colors are obviously not required for any real functionality but they just make things look nice:
![Screenshot 2022-09-16 102500](https://user-images.githubusercontent.com/47213133/190604996-4d05e6bd-67c0-4ddc-991b-7228d54445c1.png)

**Comment by asaka-wa** [comment]
I worked a bit on a PR for this a while back but the complexity involved pushed it outside the scope of what I wanted to add to the addon. 

If I were to start over I'd probably see how feasible it would be to setup the `fg` as a MaskTexture, and leave the gradient "static". This would still be a fairly big change to the way the region is constructed though. Just, easier to manage the colour as the progress changes.

**Comment by InfusOnWoW** [comment]
Yeah I don't see it as viable at the moment either. The aurabar can't easily support that.
There are e.g. complex questions how this would interact with conditions/animations which both allow setting the colour of the foregound.

Nevertheless it's worth it to take a deeper look, so I'll keep it open for that purpose.

**Comment by InfusOnWoW** [comment]
We now have gradient support.
