### ISSUE TITLE
Add a Load condition for IsAddOnLoaded

### ISSUE THREAD

**Issue by Daemoos** [WeakAuras/WeakAuras2#3821]
**Is your feature request related to a problem? Please describe.**
Sometimes WeakAuras are designed to use other addons, and it's usually better than having global code shared across multiple auras, which is not optimal since the load order of the auras is random. Those auras should not be loaded if their external dependencies are not loaded.

**Describe the solution you'd like**
Adding a simple Load condition that checks using IsAddOnLoaded(). At the very least it would be a text input to add the AddOn name(s) and ideally it should support multiple names (separated like events input for triggers).

**Describe alternatives you've considered**
Right now we have to use global code in Init custom code and have a bunch of if conditions to check if the AddOn's namespace exists. The auras get loaded even if they don't do anything without the specific required addons.

**Comment by InfusOnWoW** [comment]
That's far too niche.
