### ISSUE TITLE
Unknown difficulty id found. Report as bug: 192

### ISSUE THREAD

**Issue by jevchen1994** [WeakAuras/WeakAuras2#3822]
### Description

Can't load option with /wa

### WeakAuras Version

WeakAuras2 Release 4.1.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Message: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
Time: Sat Sep 17 16:46:43 2022
Count: 1
Stack: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:156: in function `CreateFrame'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:779: in function `ShowOptions'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:612: in function `ToggleOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:150: in function `OpenOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:192: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5218: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4882: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4918: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: frame = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 lastArchiveClear = 1663447107
 minimap = <table> {
 }
 lastUpgrade = 1663447112
 dbVersion = 53
 registered = <table> {
 }
 login_squelch_time = 10
 editor_font_size = 12
}
odb = <table> {
 locale = "enUS"
 needsRebuild = true
 version = "4.1.3"
 magnetAlign = true
 spellCacheAchivements = true
 spellCacheStrings = true
 spellCache = <table> {
 }
 build = "45632"
}
(*temporary) = nil
(*temporary) = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329

**Comment by Stanzilla** [comment]
Please fill out your tickets properly in the future. Also Dragonflight is not yet supported.

**Comment by InfusOnWoW** [comment]
No even worse that's using the retail version on DF.
