### ISSUE TITLE
dragonflight issue

### ISSUE THREAD

**Issue by Triadian** [WeakAuras/WeakAuras2#3823]
### Description

upon logging in get this message 

### WeakAuras Version

4.1.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

fixed a few trivial ones to get it working

### Reproduction Steps

1 fix the api changes in wa 
2 see popup in v10.0.2

### Screenshots

![image](https://user-images.githubusercontent.com/18445590/190918174-7b49d863-47c1-49a7-8be2-63560f4d1da0.png)

**Comment by Stanzilla** [comment]
You're using the retail version on beta
