### ISSUE TITLE
couldn't load when there is a string update

### ISSUE THREAD

**Issue by seakoria** [WeakAuras/WeakAuras2#3825]
### Description

After updated with WeakAuras Companion，I couldn't be loaded.
Disabled other Addons didn't change a thing. 

### WeakAuras Version

4.1.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x WeakAuras\WeakAuras-4.1.3.lua:2372: attempt to call field 'concat' (a nil value)
[string "@WeakAuras\WeakAuras.lua"]:2372: in function <WeakAuras\WeakAuras.lua:2367>
[string "@WeakAuras\WeakAuras.lua"]:2380: in function <WeakAuras\WeakAuras.lua:2367>
[string "@WeakAuras\WeakAuras.lua"]:2380: in function <WeakAuras\WeakAuras.lua:2367>
[string "@WeakAuras\WeakAuras.lua"]:2380: in function <WeakAuras\WeakAuras.lua:2367>
[string "@WeakAuras\WeakAuras.lua"]:2380: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2395: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1141: in function <WeakAuras\WeakAuras.lua:1113>

[string "@WeakAuras\WeakAuras-4.1.3.lua"]:1258: in function <WeakAuras\WeakAuras.lua:1209>

### Reproduction Steps

1.WA companion update WA string.
2.WA said there is a new update of string can be used.
3.It didn't loaded.
4.Disable all addons but WA，nothing changed.

### Last Good Version

4.1.3

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/9595578/WeakAuras.zip)

**Comment by seakoria** [comment]
After deleted and reinstall it comes back.Might be those string causeing the problem.

**Comment by mrbuds** [comment]
It's the second time i see this problem, you use https://wago.io/1nVdmqw8Q that include "SwingTimerAPI" this aura break the addon.

**Comment by InfusOnWoW** [comment]
Apparently something is wrong with the aura upgrade code.
Upgrading from: https://wago.io/0N1K2wIv4/1.0.16 to https://wago.io/0N1K2wIv4/1.0.17 does leave the WeakAuras settings in a broken state.

This needs some deeper investigation.

**Comment by InfusOnWoW** [comment]
This is now "mostly" fixed. That is the aura update code now prevents this error from occuring for all upgrades.

The next release should also contain some code to fix up the weakauras settings for people that encountered the same bug with the the "Fojji - Deathknight UI [WotLK] - Blood, Frost, Unholy DPS, Unholy Tank " auras.

Other aura upgrades that went awry due to the same bug are not automatically fixed and must be manually fixed.
