### ISSUE TITLE
Zone ID(s) ignored

### ISSUE THREAD

**Issue by Spuuwn** [WeakAuras/WeakAuras2#3826]
### Description

Weak Auras with  Load condition of 'Zone ID(s)' do not get loaded in version CI-Beta #163.
No new zone ID or old zone ID seems to function.
Confirmed with a few of the current Oribos map markers in live Shadowlands which work and then importing into the Dragonflight beta and visiting Oribos.

### WeakAuras Version

CI-Beta #163

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Create Weak aura icon.
Set position setting 'Anchored To' to 'Select Frame' and check 'Set Parent to Anchor'.
Set 'Frame' to 'WorldMapFrame'.
In 'Load' tab set 'Zone ID(s)' to '1670' for Oribos (Ring of Fates) or '2112' for Valdrakken.
Icon will not Show.

**Comment by InfusOnWoW** [comment]
We are not taking Dragonflight bug reports.
