### ISSUE TITLE
Queued Action for Heroic Strike is not working

### ISSUE THREAD

**Issue by Warkonaut** [WeakAuras/WeakAuras2#3829]
### Description

If I create a trigger Spell → Queued Action and set the spell to Heroic Strike, the trigger doesn't fire.

If I change the spell that should trigger the aura to Cleave, everything works fine.

Note: Noticed also the HS queuing auras are not working in creations of others, like Luxthos Warrior UI (https://wago.io/LuxthosWarriorWrath).

### WeakAuras Version

WeakAuras 4.1.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Error reporting is enabled and BugSack and BugGrabber are ON. No LUA errors.

### Reproduction Steps

1. log warrior character, that has a Heroic Strike spell :-)
2. create a WA that uses trigger Spell\Queued Action and set the spell to Heroic Strike
3. use Heroic Strike ability
4. notice the WA doesn't show up
5. change the spell to Cleave and notice it will work fine 

### Last Good Version

No idea, didn't hunt for the working versions. Back on lvl60 it worked for my war. Didn't play war in TBC, no idea when it stopped working.

### Screenshots

![image](https://user-images.githubusercontent.com/113946199/191125853-e9abc253-7ca7-4177-9fd2-e0918d846ceb.png)

### Export String

!WA:2!1vvqVTTnu4M6T2oJDOnDWOaRh8sXcqxbcs8kkqdWgGLJ9I3CJ9KDAA3HjrjsjXgArosk7KE0yh6z)tWN3jFCNgYVabJ9lWN3P8lypszN2oS4dwp(4tp(43779PnAT5WnXBIF33pJgYt7ZZKHKhEd5zDJIue9)ClXtWuLGHoFa5mTxexoeP9eEA6qIh(8u0qAONorsujCg(2YZlEVnMJsdt4YECAQoOrZJg00vu96ZuXQnQLjz3uIc1uEQ6zUknsQFPeZ9Iz8XjZn)7vSRdCEJNADOpxqweKP180UJis4aU06psIGmB3TLB9x0SFZonBmOR7S3VR4EnzJoUTNds(ChBgQfertPQKkltOyIhIXSNTkXbCRll266Vdd5ypjst8NLPid4CMMk8V8ucruxjiHAxeu4(tgZL4tKiXKtwzmdtuiDM5vtCI4P6lQlPiw1JqsjFSdJJWrtHu6fYqkLV1mLa30KanIrs1vChMbhwzxBaBhOOPXmI8K6UUT76M)OYoMZVI1G(wIXyHkbH5JFvr3Q0mjjga1baw5yOboVLZh2R0U7uZbLP5(Z08q4avqm3z0F5IyIeuPaiWiAC5zr0Zi4tOyDYV)5sEMMrtjYUhpOt7JAgmgfZBFW0rp)3odFqC7N6gYzC5pwc(TQiEDrr8WBSieanWrA)XubXxC3WmLMp0a1hlWa84c3AaEwhwtCmjzIwsJJHA7x3wUY8DvwAWiaw1TyOyvTeX9moIjqDrd7dmNUP(l(OLlv2hnwLANmOBhyA0ePlqYjQYqBkilkYGrYdB2PxRJ7mtzhxogInVHJHP5cinJTuLfyl1EscaoZ6v3DWR9(P2D6C1o9Hurp7MI7AkSI0SUwVVXf5mGN7zZ2rWXNKV)IFoJKrWvRB5)xyjesQMgIy(lKeeR)6GxCirYPHv7d4XPKf2ty9E(tSMTXQYlF)rBUb(tWgoiK7TQT7fRbqZojwkNgMlp1F6vz6oJ0tZsxb5L3o)7IYpm3jVzERjMWnaO)CJfn1qDi(5770aP0qmnY)LYZHbP3KLcxMrKAWyM4EiR9GIe(coM8h3q8L)VJBfgUMPo8LGadrMIyVSGFE6uukDO9E8S8YTUGGueaiiPX6KBNFOtkpLSy9n1Qoa1gWKXQjMqnT38iNHiAARCc8c5r5X5j5u45x8F9ixnt8PZG2QRDes9nvYpCbSmaqRyyAifd4YuJdyCNixu8WJxitEXQLfdfBSXgLwUYZiQIgWi(ZxTMaKD5Ev7bZAS1(mtZLcsi04e9JNyKo6dE(QGIMAaDOGl1I7wif3Yi4z)tC)tiOtRdyGA)E8Xezvq)B(kKUnGfp4MFYFUag8H3QRWQfxE(h0i26RfZPPfnbyZkIhqJt5sYQyBA43nbTlPYpqrgcGK7E7S7o7L)eFXJUE9tHKesnWzPPkclY(PJ8BvlJINJE5J39T)Wlo4aCDX2xFgyKyu45Ermox6lFdOEqJo3PtZwdChBKNoElkwu5eqxLYL7x9JgtMB)GayJ0OptSjqCxRfaurxJS(LFaoAOjZl(GI9BlIVyTOKPSoGQqqVdNixX9tMxi114Q28mdLJwGTtw)UjlnQTgun0kN6uhwUPY9P7S3oF7MJ(7x9V

**Comment by mrbuds** [comment]
Try make the aura yourself instead of using luxthos aura, i guess his was made with a rank of heroic strike you don't have on live servers.

**Comment by Warkonaut** [comment]
I confirm the trigger works fine. Sorry for the false alarm. :(
