### ISSUE TITLE
[Dragonflight] separate talent tree talent selection load condition to toggle on class and spec Selection

### ISSUE THREAD

**Issue by ljosberinn** [WeakAuras/WeakAuras2#3830]
### Description

hi,

probably already known, couldn't find it in an issue however.

right now you can only select a load condition for an aura based on talents once you've selected a spec. however, since class trees are shared across specs, the class condition alone should be enough to allow you selecting a talent from the class tree.

### WeakAuras Version

4.1.3-16-gbc000cb

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. set a load condition for your class, e.g. demon hunter
2. set a load condition for your spec, e.g. vengeance
3. notice how only now you can select a talent from the class tree, although it's shared with havoc. to have the same effect for havoc, you'd need to duplicate the aura and exclusively change the load condition

**Comment by mrbuds** [comment]
> since class trees are shared across specs, the class condition alone should be enough to allow you selecting a talent from the class tree.

That assumption is wrong, also we don't take DF bug reports yet

**Comment by ljosberinn** [comment]
would you mind elaborating why its wrong?

**Comment by InfusOnWoW** [comment]
The class tree is can be different and actually is different for some classes, e.g. warriors. While atm they have the same structure, that is actually not a requirement of the api. As there's really only a ONE talent tree data per spec. Not one for class and one for spec.

**Comment by InfusOnWoW** [comment]
The "Spell Known" load option might be a better fit for your needs.

**Comment by mrbuds** [comment]
Druids also have difference in "class" tress between specs

**Comment by ljosberinn** [comment]
oh yea makes total sense then. wasnt aware of the druid changing, thanks
