### ISSUE TITLE
Ignore LUA Error Option is again not working anymore (was fixed in 4.1.3)

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#3832]
### Description

You fixed the "Ignore LUA Errors on OPTIONS event" thing in the last Version 4.1.3 but after updating to Version 4.1.4 it is bugged again. Maybe some oversight after merging builts or pushing out the fixes deployed with 4.1.4.

### WeakAuras Version

Weakauras 4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Login

### Last Good Version

WeakAuras 4.1.3

**Comment by mrbuds** [comment]
Please write a proper bug report.
