### ISSUE TITLE
Deprecate custom untrigger

### ISSUE THREAD

**Issue by siikamiika** [WeakAuras/WeakAuras2#3836]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, everything custom untriggers can do could be done directly in custom trigger by returning `false` as long as you know if the trigger is already active. The Wiki page mentions "Automatic" and "Custom" Hide options, but I only see "Custom" and "Timed", not "Automatic". I'm on 4.1.4 (Wrath). I understand that lots of existing WAs might rely on untriggers, so compatibility would have to be maintained.
https://github.com/WeakAuras/WeakAuras2/wiki/Triggers-and-Untriggers

**Describe the solution you'd like**
Hide and don't use Custom Untrigger by default

**Describe alternatives you've considered**
Default custom untrigger to
```lua
function ()
  return true
end
```
or how documentation describes it.

**Additional context**
<img width="491" alt="Screenshot 2022-09-23 at 19 06 59" src="https://user-images.githubusercontent.com/5602483/192004594-d6a1a245-aed4-4e53-9966-9d652522a4eb.png">

**Comment by asaka-wa** [comment]
Untriggers can be handled in the trigger in "Status" triggers only, and for those triggers a blank Untrigger does return true.

**Comment by InfusOnWoW** [comment]
I don't know why you came to the conclusion that untriggers should be deprecated, but that would be a wrong conclusion.

**Comment by siikamiika** [comment]
Thank you, my main problem was that I was using an Event trigger instead of a Status trigger. I started using WA yesterday and wondered why my auras didn't hide when returning `false`/`nil`.

However, I still believe that untriggers are unnecessary for the reasons detailed in the OP, but the severity is far lower.

**Comment by asaka-wa** [comment]
For Event Triggers they're vital.

**Comment by asaka-wa** [comment]
If you wanna chat about using custom triggers (or more broadly just using WA in interesting ways) without the context of a Bug/Suggestion ticket, join the Discord. 
https://discord.gg/weakauras

**Comment by InfusOnWoW** [comment]
There's no issue at all. Untriggers have a place, and no matter whether you think so or not.
