### ISSUE TITLE
Dragonflight bug: 192 Challenge Level 1 none

### ISSUE THREAD

**Issue by Zelexisx** [WeakAuras/WeakAuras2#3838]
### Description

Attempting to run/load WA version 4.1.4-2-g8525d7d.z in Dragonflight beta version 10.0.2.45746. bug: 192 Challenge Level 1 none
Elvui is installed but not working and not showing in addons list and not loading. Addons that are running are Details: TomTom.

### WeakAuras Version

4.1.4-2-g8525d7d.z

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

Message: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
Time: Sat Sep 24 20:14:19 2022
Count: 2
Stack: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:156: in function `CreateFrame'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:779: in function `ShowOptions'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:612: in function `ToggleOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:150: in function `OpenOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:192: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5218: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4882: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4918: in function `ChatEdit_OnEnterPressed'
[string "*UnknownFile:127_OnEnterPressed"]:1: in function <[string "*UnknownFile:127_OnEnterPressed"]:1>

Locals: frame = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 lastArchiveClear = 1662157394
 minimap = <table> {
 }
 lastUpgrade = 1662166978
 dbVersion = 53
 registered = <table> {
 }
 editor_font_size = 12
 login_squelch_time = 10
}
odb = <table> {
 locale = "enUS"
 needsRebuild = false
 version = "4.1.4-2-g8525d7d"
 magnetAlign = true
 spellCacheAchivements = true
 spellCacheStrings = true
 spellCache = <table> {
 }
 build = "45746"
}
(*temporary) = nil
(*temporary) = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defi

### Reproduction Steps

1. open df beta client
2. type in /wa
3. error (lua) displays and chat message to report the bug

### Last Good Version

N/A

**Comment by InfusOnWoW** [comment]
You are using a non dragon flight build on DF.
