### ISSUE TITLE
Encounter ID's for classic wrath are wrong

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#3839]
### Description

Seems like the encounter id's on the tooltip for classic wrath aren't the right ones.

### WeakAuras Version

4.1.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Check wow tools and in game

**Comment by mrbuds** [comment]
Any example?

**Comment by 1ps3** [comment]
https://wow.tools/dbc/?dbc=dungeonencounter&build=3.4.0.45770#page=1&search=malygos

Here’s malygos for example, 734 compared to 1094 which is the retail ID

**Comment by InfusOnWoW** [comment]
Thanks
