### ISSUE TITLE
Talent load condition, destruction warlock

### ISSUE THREAD

**Issue by WalkApath** [WeakAuras/WeakAuras2#3840]
### Description

When I want to chose a specific talent to be active for a WA to load (load tab) in destruction spec, it shows me Demo talent page instead of destro talent page

### WeakAuras Version

WakAuras 4.1.3-20-ga1d8b16

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Make a random WA
2. Make the WA load when a specific WA is active
3. U wont be able to chose a talent for this in the load tab
4. Will see demo talent show up

**Comment by InfusOnWoW** [comment]
"2. Make the WA load when a specific WA is active"
I have no idea what you mean with that.

"U wont be able to chose a talent for this in the load tab"
Nor what you mean with this.

"Will see demo talent show up"
Nor with that.

Please provide a screenshot of what exactly you are seeing.

**Comment by WalkApath** [comment]
![Udklip](https://user-images.githubusercontent.com/113772394/192164518-365ab002-cea2-4408-8a7c-5d6802080122.PNG)

**Comment by WalkApath** [comment]
The highlighted talents are demo talents

**Comment by WalkApath** [comment]
Im in destro spec

**Comment by WalkApath** [comment]
:)

**Comment by InfusOnWoW** [comment]
That is not on Retail. That's on DF?

**Comment by WalkApath** [comment]
u cant chose DF in the bug report

**Comment by InfusOnWoW** [comment]
Because it's not supported. And we don't take bug reports for it.
