### ISSUE TITLE
Selecting multiple Progress Bar Auras errors

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#3841]
### Description

Selecting multiple Prog Bar Auras, with different Bar Colors, errors when viewing the Display tab. 

### WeakAuras Version

beta-1

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

sorry, BugSack is erroring currently. The top line is `Usage: self:SetVertexColor(color [, a])`

### Reproduction Steps

make a Bar Aura
set its colour. 
make another Bar.
Select both. 

### Export String

!WA:2!TA1tZTTXvCHbtMmbJhhjkBfZehlg3yh70Oyzfx32PJJnHmPPKPPKbPSKCCl1cSlj2iqGnlwijQ8NwR66rDAtsR(iWZ(ep0pa(qp)gn9tGUKJzgDj5y3flKOSh7KlHhaw847T49(9(9(TW4E5IzJI5O2rHTcOT9ft4seOjUCUo5W5WB)276I8wfZJythfeXN100CEZj)WFZEUrCmHBN9NSHTdOBUjIJl0ikkqqz9erERr4X0OWtz84EoXEOaIPRom)E67LWTjSrQ)zjioPq5KGGcl6tfKECsBzCn6YioT5rjSm3Rt3K8k91R1PJHHHjFJ5A1kMim6Jc98J4ZhrdfUtxQwJsoCKNqUtXx1jwG4cl3w0qASVLT8MWAlbN2UTmjFZZZZw(4EyIBsRwQ3nVsPQZxEHQ2cvIGs4OP2kMrccMbhBTxCIlznsOOU0B6g9BoDX6nAwVrrNg2jYn3LfG6s4oHOoKylNuxDRqqbc)ddDEorgQt95lvT6ojHzPGfVBwbTVSqi8quW90a5Q2briCzxHekdfJ50jrI0w2YCYBm49TC8cqXXQv2XsKsTyhuiTdsbbxfYv(PeumPUGtcBl8FviVDyuizxSSWuE0uvM8yIxuioElLRkqaM0UdIgwgUKmays4YWuWhjVp6ZB5SuStnY6f(ODrjczByowkYB1VfxcbY3ksGm3x3IkRmP2D36t7uQuTNQ7P6Y(1CLzqlABRSo9mHsJM9KGMtkTi2ANysqR02mmCpv6sZEv0WwrCD9Anvcf3F5LQ5SS)fVYLlxoN37V9L6fZq8vxKIf(NShvgA9OeUh50dbh3aoVb86WW7M6ItKiDBmyJ8mpFNimXU4cnMZwfTpCYJFEyS)7EjXKMX(rRx0noI7UIexodlNYik1GQVRICf40WBV3a7ABVJ90OybCgyC4TSGFf8UqbRTuoP4rRaVbCk4CwSruu51in0KevKpzO0sOP3btMMW7Tk8XWWB5IYMpmRC9V7h(XHK)QC9VF8XVHCHPKHhJeQMoX)PPfNg3x2aU2SJb53vI0QHE1KxioZGexjAdBNN9ocYgIMPx04DtwtbTdPjJt8OkMQ5oh6YzphJv4LfqNiCtvISYEP)5G(6TyJMArYLIunuV0EMDr5J7R3h6geCQXhYE3x22hqAJ862Svque3)PPo8PjXcARUsIdx1sjnKgTRnxTs7MfFOqrmTRjhnG8CzPRSVRM3Uu2GzVuFhG77CySSHlZPBw4UjiSIWxOrdwoDP5JWrRNTbMpJXL1gp9qS8VGcrVWrvpyDoUUCSyroIT1Izl0v2AsK3nGScBynYnqmS3m1QvYPz1sLBWoZldR0pzKfToZgiYoaDuIW5zx8LTn4UsfpQxtHpNiNicWDZWUSQ0y7taTnH7D2ZfcFw6wdlb3cwgUp8jpeegWFegg(tqt5iKlG1SAc0c8LZORcbqNvGW(66XzMBvPbScGaEEWZ4fGEHzlGjD9jQd3ghUqz4IkLr4xNE9dsVoH66EPZc2sPvSA6AQI38MSHLJHfXkodbtW3bTHF)uVQqXysOtTs3RKd8HkT1NxF8k)8kMWiYaTGrTGty98VjQuBXIRoZrolF0P0Lm2jDOpMIjoAe4pyPDqrLt4e2fMrDSrlKh5bkHfAyBBe)blmZedEAI6QaYQLuK5ACHo8To4KCOyFVfdMVw1fMR9TxWEZOOogoPr4dVI6m9du8NYzD1C4JoMdkG5JmHFh87HFRPwR9WpBWKtdvFqaXhUQv)iovEewQKAVkZ5mZ9NRwJIvHRBb3WA)bQphsat)OJTVem9jHBkzcAPAOKbuwsEQKPd)Fu6UWSPQSWTLcRq1NvvfUZbYPqTNmem3rfnH5N1uXgVRp4KPec1vxASDEyHugldwCLJYwFG)HSvfluXy9mokPvs0v8wk8PhYDHiGzCaZxYBJ7c)ImtajdMeG1KKR1)P46WgqxytF4ZHV4xe6l8Ls6k8vQtr)ZgWFbEOKucBb)v4rxd(BWJLujXfcNbnVxu3Bxg22a(7d4qtj5qW)4rhd(NhWCGVwxJFJIQaFl8V08c4FFiti3A)VL())

**Comment by Causese** [comment]
```
Message: Usage: self:SetVertexColor(color [, a])
Time: Tue Sep 27 18:23:59 2022
Count: 8
Stack: Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@Interface/AddOns/WeakAuras/Libs/AceGUI-3.0/widgets/AceGUIWidget-ColorPicker.lua"]:105: in function `SetColor'
[string "@Interface/AddOns/WeakAuras/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1368: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1101>
[string "@Interface/AddOns/WeakAuras/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1630: in function `FeedGroup'
[string "@Interface/AddOns/WeakAuras/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1910: in function `Open'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1035: in function `FillOptions'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1032: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:1030>
[string "=[C]"]: ?
[string "@Interface/AddOns/WeakAuras/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...face/AddOns/WeakAuras/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/WeakAuras/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/WeakAuras/Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/WeakAuras/Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals: <none>
```

**Comment by InfusOnWoW** [comment]
Is fixed in the next release.
