### ISSUE TITLE
Evoker Talent Selection Load condition

### ISSUE THREAD

**Issue by echo000** [WeakAuras/WeakAuras2#3842]
### Description

In a WeakAura's load condition, selecting a talent in the Devastation Evoker tree (only one I've tested) does not load the aura. The main concern is with the talent Power Nexus for evoker (however seems to be all talents from initial testing). A quick workaround is checking spell known instead, however if you want to have 2 auras depending if the talent is known or not will not work properly (typically for an essence bar).

### WeakAuras Version

dragonflight-beta-1-1-g540dcf9

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No lua error

### Reproduction Steps

1. Choose a talent in the evoker tree
2. Create an aura with the load condition of that talent, will not load.
3. Making an aura with the opposite condition will sometimes load?

### Screenshots

Despite having the talent picked in the tree, it will still load the aura even when it is set to not load.
![image](https://user-images.githubusercontent.com/3669134/192555416-ee23f33c-5d7e-4b28-bc7b-af192754045a.png)
![image](https://user-images.githubusercontent.com/3669134/192556696-54d8335c-5a73-4a91-84bd-4dbd0396deba.png)
![image](https://user-images.githubusercontent.com/3669134/192555364-e10da19c-463f-4fc3-9d5e-e0dad0a7ae1c.png)
![image](https://user-images.githubusercontent.com/3669134/192555321-03bb4628-77b6-4f29-a9b6-b3cc6ec379a7.png)

### Export String

!WA:2!DNvEWXrXvFn1ghcluj2cSJSWbMOqSLaP1sYwcJllmALwHeFY6y2v2gSD2D2D6DNbn7md9m7kTYXCOqioNFjk3jecSFqiheYxuUVbrc5gErHKVCqUehbssvFv5k)p51DpZURwjztrvF1xvruStF86x)E)EhD3plD4gDDUunQAoBRSMg5096inXtTJUW)lxp7TtTmzV6gZ3OwJANUNO5O2ZuE4Xvg5ghFSe9p6kPTPAeAu1mtRrTDC2CutJ5MtLQjNW220ZWj9miBhzWfsgNy3Xi7R3I0sJNnRlX74x4zCTPEdxkn1qlHAAtYoDAEqsrvxpvpdBR9hZ1LyLH4U)8QZ2xp6NLj7vVC2cMMdyqZyssnpkHXDuZqc1DbQPZLO7554U)DVBMGeXWE3vKKD3nvndJBU9QG8L6foDwdldx9WrXpEHN3JAKlhH628oP(nVZYAK0fYMnrjhcD4yJoXqtnAupSJIAbQA3Z76qmnhrZn8kUfstksS8IJuBm7IjhO)4jsgpr)kjQm1eucoLs8jIn6OkwQ5jUHv4tKEyIQPNE0cOuK2XuTeHUqblFri8IzSnlK3sOIPPQAgfCVJlCbxIz2jSnWvpqSXsetrrfnLwqRuu1yRtIwevfuB3uzuaui5ykE4fq7zbNrYyB10qpW9VOQvgDBkNnqRrnTv1gkQRXCKTPKVaAndhfvWmBd6kSsgtvxxwR0EQMOmZAoFbxYOg5n80xoTVdXa2M20RpuOqteQZi9SOWBrmOKKuO0U2fOziPnY7G(cNb3wc1s18WcjDAf3miZdLgfVSg5cNwSC9YIVX0YrC2s8BUGkLipe6aiFeDdpszkx3yMOL0kH4QrgUs6VQ4O6SPOmxVOw2we6Sc3rj0Tr4BjTywkAmI7rv9udPyYuOlyfueqG0YBi0LXMMwP)bhzQ4lOsZmkXkNN(DSTLeSxWTZpTljpI3kDfPZiDv2ZoJp43K0DwUfdTLc8FLJQs7UGH2IPhm7CAdmEHbSSqBIH2rm080VGZimidXeiMcLo(akXIn2YQf8WHh3H79g2hwhXc35qZZwnJ2wugKQAzKx1JOR4Y8woVYOwOz4VidRS208Cvo8cccXM9cBzOLiQUm9NRzNh0em4YAO7nB6KmNDQlHXi35z0X2kyWO5vnSgcEtCQHKqkqf)2y9J0yMR407Tmkm0P5k4wxI3waAhvcELW5bVkjic06Y8jucSjoBzv9pKTgjA)tLyC4vdVMZWC2yMylTkEwC3n4IV7DcB90nUc6xMuf91OPzlm1IS(eHfifSn41cnLotbxp78onwLuwqOGCXCCvFrwcisbhn8xQplcbTaVbqELyfTNMqL9nTSGHKSi4uWLa7aUSWIGExNDp1yJKi5eJFKykjhsj2KtHHR7xeLlZN6q9Fu(S(dctp7fUVSfS4PQALV)UTlZzw7YSnODzh7ziuMHOTWY4FgzRoISQLwn9UL(KBjw84XgBGyTi7PtS4lG9hL4vGk6sS04FnTXWpXIL7tEkCRMG1U1wecwlTlhZQq(iteW9i(QEB1SAm)8e1ZGdPo7lrEW)PJoKDN2WPIAjRzOzTlp5m6Qw5iYUgi5Yy6ipzHDXhCCL9Zyk7zBJYHvjzpdmjRSHN8medQwawXWW6GPk9K7RpzwQ9KeRIry7HqzyZxvZQJKdfmX5cFRfKjy8jIrxhrSdy(zI1qSuX(IuRNnyIHmcg0NSLHPSnTA)oxTyeSrDgP71ZwZMvBq)GDKSEK3TCR8F6c)HpDB1AETSNri1jqOT12QxTcCB9TmXX)x4b3UV1ZTTksMyfcc1qMMv10LuzwmxL80KsTlxu1Sar2Ws2r1G62AaBK1SRqRpKW3OJHl6em3EX6wfwe8xne6t36tseXMXeop66quvzFnthaZ13w4veSYnY7a9DNItXQGfgK4NcchVR2L7TwqabGGjVMQ(QRr)dWj3J5t9jwFmsiiCsXnRULSbWLRo37y1gYxYi6QGS65q9Y8AejwmWjxZM6qTZXsBZdYXuHSecAT0(AOZWsJmlsGp3wnbNk8lpGPECVITRp)CnxPCxNnWNLBrHWoO1WkhleETID2nkzvWEDG1JG1Dpx9(gF1636Weu4pX6YeuOQYbMSuPxKvBoQyp2ybQQqrRbiQHJb3trUd5wBT6WKzDmetWYtX8n6SnKem7vBB4(GYD1n5AQpp66kz1zGQS8nCv16JFUgF9gR(CMRnn7j3W9wRAw(vN2V9nwCxnm2NCR1DGrhRgdAd9kyNqSXC8LAazL4ErkL1n97PwRTS2eNvBJM)At4wBsMAclpqqy5zjK8LhYlokILYEdjXdVOR5zNK6Ho(tJZ8)Jy3)NGrD(Vry06ChGGVRtcvF3V1o9HQEL6GZ1dxZDjQihHrMRKrNKzAqgEDWLcnh(mINYCyvQbRIlUo31jfhlvtYaMUlaO6qVQglVa4KysY4vdCYTAUmALfqDTGo)63AvJY9pi9uTx5WXaJUqeofC5HX3VDy8bKBFjgcWRUIHMBZP3tpxDVDTp2t3od(mRyZIpkpUO0lP4pg7YdVOMH7nXV9zrcmTtJcfpH4fbJANZiJZUQ8Ok)hk0wyFi0V)XWt0qm0zlQC24Vy2BcFWgkBGpbozMGYBec2)0WjypEU(3aN(C)Q45tR6xtKHp4tCzx212qdsHg(GpTR7T1qdneQSgXv1JzFi6WvUjO9BCBqtl7wiD1N96paEHqIyGt3y3Qog608OSAMCwPffnC9swWDYQDOZvZm0sslj6K1WKmIgTR9T3R6Q6EpLfd6O6P70m3e4U7Rk7SjvNJqnWldKhF1BK8DxLrELK834sSNH3vnBXSpZMHHKwb13KIbZyA4KQMLwruvnD0vdbnnpQx8rwwmErdxd0ZvVM1mxW2n3eH2BK9v0VCijzfUk0Y(DefsPBCNHMwGbE8H9lAJVDKvrk)cAgSpPcygrlhboya3S5fSi0PB2z7EKzrzG9JOCkjT8BadUqL5A5n64iVgkDsYceyirsM1n1k8jRuipiNZfXhrTa66YIH41mjA)y3Zi4JXSerLIUDNlFJyVjjNAMsjZAABt1xItWnHbdgzlbTwMx0lscCWOJn(yXwwat3GFnXCABJyQFH1s6PJji0Tn1kbnrryLr66Gjo(nu4r(L5tvn2zbFsT8C28quJ5KNSGQgR6BYjs4SzbOORQzpt1ch60ynd7lU7OHLRWiwkROJzBredndA2ocv1z(J43qGdbot(Bsnv)CPrgBSykjfLs15s3iyq0tY51Vre4qjzmyf(luvzJvbYT7J0hnaPRvF8hmuADcRA8NpS7hJkQYA3Bd6ABNmfSx23s6WE2zAx8EwMK0Xo84)hXuWrHhnvzwPNelqFbwBEXAtXldgpaEA8szw6l4u0rqfVYTSPYKc6ENWsHGUAoLZfZltgl3ATRQC12nTP79rGozv(DfE15II8sJLES7(hCqNnJlVFnMRgrJOHhAPdhomSp4QHnJ5jddnggUOW1w)VBqcIjfLLxvV(fByPdxlLDgalaEYfnZF0j7jwX(hEMjfvtCGQot8eZUgAefLrUUHt0IH2c9euuoLzyblt8k6TZi7Br(chMdX9rzWFbkr5qSJyuezFIoNTDEj4qWyW4Sc36VcdnnILYyXoCmff(i6W1fcsatjuMeco506iSQzNfVF8Xhap1gntrvPhFQr6OAVoIZwaCGWudlwbIj68JvIZlk(oAyrBQbAD4hmdHGJDf7ekmeS1qTy70sF9PWpTeEO5l6FA(s1EEn1VWinVt4ztnpodoKxjyfbl2e8Crzx1bE2qP53qWT5E5Jc)nCi45Vc2QGxW5IWq6i7jYQs9ItD94Xt)V36TEpn0WUg(Gp1t9uV4l(Ipxi4fGBdoEyyxqRNEVqMTcAI65IgDrjDbIeKfYXkzl8e6bfNfmsb3KFvyHPbZuqEWcS9lQk4a3Cqbubk4Iu4bfQCFgOimtn3saMTzOeNvZfCpa4K4sEZWPGB5bBaU1khvJcjCB4XTp(DF3pm7q2Hp4kkkPyTGBxhECjXPSW8SFElOqEh6WBvcUZjH3MeCAj4TdVd4DcVl4DlbVh(zCW)j)Kn49McEFsWc4bxW7h(a6Whuc(qItLGpCi4JaFuCIpg8X55WG7kf8jGdc3nEoc8jXRdCp4XeW9MckJG0)fCFW9F7WNshEauu)0WNb(SsWNdZYcpi85Hhc(ccv5)g(IWIcU9L2rdWxg(kWxf(AWxxh(gW3e(wsW3oe8D2o8DLGVxi4HXmj)A4ry5o2vqoKkb8mFq()ojHHVVo8dsbpMo8Jsb)WWysgyj4rrkGFSo8tAAt33)ue0d)u4Nb)CD4PXnMfwRxTW71eHJX0SBTayam8lGFPqSpqy4jHFfpY6)zIn1tNr6Uh430h8BHFh87db)z4Va)jDrmh8hG)i8us(rySG5EdcMX8a9S3XDnTBBYHZwewrhEM1gLaplcwph8xHNVzHpDnHacN9)(666d)JZLF(l3B71yXN8O)Rp

**Comment by InfusOnWoW** [comment]
You have clicked twice on that talent, which *negates* the load option. Your screenshot shows an aura that checks that you don't have that talent.

**Comment by echo000** [comment]
The issue is that I have the talent selected in my actual talent tree as the below:
![image](https://user-images.githubusercontent.com/3669134/192567459-f8f44a6a-2b9c-49d2-8b4b-6d2805815fe0.png)
and despite this, double clicking the talent (to negate the load) still loads the aura:
![image](https://user-images.githubusercontent.com/3669134/192567893-792a11ad-9d5f-4fd8-8916-3338c66076dc.png)
The opposite is also true, trying to load an aura with the talent selected - not negated - will not load the aura.

**Comment by mrbuds** [comment]
I can reproduce issue with some spells of evoker devastation branch

**Comment by mrbuds** [comment]
Fixed with https://github.com/WeakAuras/WeakAuras2/commit/c0e60a30621430f6fd018d6256a69c3fb067238b
