### ISSUE TITLE
Unable to report adverts

### ISSUE THREAD

**Issue by Chappers1202** [WeakAuras/WeakAuras2#3844]
### Description

When in the LFG or LFR finder.  There are often many many many adverts.  Blizzard has made an option to right click the adverts and report as advertisement.  When I try to do this I get a message saying Weak Aura's has blocked me etc etc.  I have disabled all my active WA's to see if it was one of them but the only way to stop it from blocking the report is to just disable the WA addon.  

### WeakAuras Version

4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Have Weak Aura's installed
2. go to LFR/LFG
3. right click an advert and report them
4. action is blocked

**Comment by SpatenLa** [comment]
the issue lie with one of your auras. not weakauras itself.
Its most likely some aura that doesnt work anyway, something about adding rio score or something else editing the LFG Frame
