### ISSUE TITLE
Unable to select the class specialization load condition in groups. 

### ISSUE THREAD

**Issue by Mystream90** [WeakAuras/WeakAuras2#3847]
### Description

No class specialization load condition for auras when changing it via (dynamic) groups. The player class was selected before trying to select the class specialization. Works on the auras itselfs tho.

### WeakAuras Version

beta-2

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a group
2. Add auras into the group
3. Select the group
4. Change the player class load condition into a class (in my case warlock)
5. Try to change specialization (=> Not selectable)

### Last Good Version

Works on retail

### Screenshots

https://imgur.com/GVCW35W (Shows group load condition)
https://imgur.com/mOdzpMX (Shows one aura load condition inside the group)

**Comment by InfusOnWoW** [comment]
This is fixed for the next beta release
