### ISSUE TITLE
Execute Cooldown Tracking Aura Does Not Display

### ISSUE THREAD

**Issue by TheOneTrueKarj** [WeakAuras/WeakAuras2#3849]
### Description

https://wago.io/7WiuYpIcD

Created 3 versions of this aura, and imported one from Wago for a 4th.

One was cloned from a separate Cooldown Aura for a different class/spec ability. I changed the load properties from Class A to Warrior, and the Spell Trigger name from <Old Name> to Execute.

One was created from scratch. "Enable swipe" checked, %p set in the text display window. Spell Action - Cooldown with Execute as the trigger, no load conditions to prevent loading.

The other was the one linked above (it has some load conditions, class, and in combat, but otherwise nothing to prevent it from loading)

The imported aura was this one here: https://wago.io/BkOdUsy4Q

I loaded a level 70 premade warrior on Valdrakken and began hitting target dummies, waiting for Sudden Death to proc and allow usage of Execute. Then, I would execute and look for any of the aforementioned auras to display the cooldown after having used the spell. 

NONE of them have ever displayed their cooldowns for me while in combat.

ALL of them display their cooldowns properly when loaded in the config menu.

I've reloaded my UI several times in between test cases, and reloaded my game client once.
I've also verified that, according to the CurseForge client, that I am on the latest version of Weak Auras (and the install in CF is flagged as Beta Version).

ALL of my other cooldown tracking auras for my custom Havoc aura set work as I'd expect them to, and ALL other Warrior CD auras also display as I'd expect them to. The issue appear to ONLY be with Execute itself.

The character is a premade 70 Orc Warrior on the Valdrakken beta Server. No special items or anything. I've not done anything with the character except sit in Orgrimmar, testing auras/rotations. 

At present the only other addons installed are Details (up to date), AdvancedInterfaceOptions (up to date), and LibDeflate (up to date).

I'm happy to provide any additional information I can that I may not have thought to here.

Thanks,
Karj

### WeakAuras Version

WeakAuras dragonflight-beta-2

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

See above.

### Last Good Version

Unknown.

**Comment by mrbuds** [comment]
It works for me using exact spell match + spell id `280735`
But it look like a bug, you should not have to type exact spell id without checking option "exact spell match"

**Comment by TheOneTrueKarj** [comment]
Verifying workaround of specifying the spell id `280735`, does in fact fix the issue locally.

Bug persists without the workaround, however.

**Comment by InfusOnWoW** [comment]
That is a bug in how Blizzard has setup Execute, which was present already in Shadowlands, see https://github.com/WeakAuras/WeakAuras2/issues/2766
