### ISSUE TITLE
Latency Overlay for Casting Disappears

### ISSUE THREAD

**Issue by stryped** [WeakAuras/WeakAuras2#3850]
### Description

I have made a simple cast bar with the latency overlay. If you are not casting and then cast a spell, the latency overlay displays correctly:
![image](https://user-images.githubusercontent.com/68768013/193425429-eea7ab27-3d48-41ca-81d9-9737cb54eb8d.png)

When you chain cast spells the latency overlay disappears:
![image](https://user-images.githubusercontent.com/68768013/193425457-0aef2c8d-8ac8-4de3-9f7c-a17ef5592b3a.png)

### WeakAuras Version

WeakAuras 4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

N/A (none occurred during sessions where I have tested this aura)

### Reproduction Steps

Cast spells such that your spell queue window "chains" casts, thereby leaving no gap between casts.

### Screenshots

![image](https://user-images.githubusercontent.com/68768013/193425429-eea7ab27-3d48-41ca-81d9-9737cb54eb8d.png)
![image](https://user-images.githubusercontent.com/68768013/193425457-0aef2c8d-8ac8-4de3-9f7c-a17ef5592b3a.png)

### Export String

!WA:2!1zvtSTXXvyrZweaw4cB2y1ed3azJAH4dwrsXWfOaXkCLOmzkfj7sklBvvWD2DhYDSwoZMzMLIuTfjMih8PEGa9yVqG0wuu0deO3d09wmGOixBHouGERv3lAFZSljLtJNdK78M38M3pFVFYSB(U59Z7)Y9glIq8JpG4ldUXyIhJ2GfZ9W3Aj3ybM3QFMPOyzaJxlssyuro(GATBlWYsF4N4S0NU0slDrBgh3HZIP(BZcz8pklSMAKQntI03kZebQlUjUVmMJD2mMhEfl9t5yEWwEZV2iboSDDgHkD3Uy1MfTh6I4jsT0w)JLnRsB9LpXSkT1F6gMvPT(N)(t(qqvg7Jfi4nqsCWq(Sh3QnJkJU2UCYPR8JJr(WXOvA28mJkMymplJRhNf1Aq9VX6R9GnUqMOQhWrr7X8XrV52vkSx9M1SQuy7FuHD2PCZYpP4yHeXLfODcXzox0LXKb15SoCSq4eDnW7vW)5Xcj2h7VhHgmg8sG60CqeMJaDeSSrUHyQV(fSTQuS6oJeHiQuV3TC1gL3P4ewpmpenWlKefWt1QXfd7TF5vQY4DtSHuhB07wMkX82ip8rBJescTJfIF0(LV)ID3VH(cwqiL5mwY8aXlaL6TY40YgfgfGY6crK2Ko5IUMlY74K4AIt6BEzp2tZ4EcQdR8oJS(O4npyNp26PrV5c3V187geD9xblOToRc73S2LzF35qOGHsoPthqT(LRYt)8LF3laVzlra7KkaZuVbod913dex(nM2btXCIxd44A0ZfM)2MXc9zNqTIPePBe4cX8rrStWCj4)V6uT8MV1bWnUXTBBcnLkwP(U7xXMciwrol95QFWqn)Ar5WJP4EyQuD3jAAeQ2dIdoxe7AOxNJBt6B3OEXkvSnuS0E)ORR5(v0uNPCmkSreomSk8wzm6Ky2wNHMpl7lYDU(aKRGXD1opN5VvdqNj9N0A7cnA2QrZc2nptZk4wL7d6AWi9ojhcfoJMl4mJIPP(1Ct8jINht9KKE4nr0br59aalRBZKZRW6q8Us01rggsjQvHSdbyRb4)zlFbrd6OOWNKaLoEeIs6AInp02KHS7zyKa3qYX0oYG3q9ilkJINolc2s7IbFiG78fd1SQJdQdT6Ii0DvpdUG6q1prDK6NQo0TnHsebFvY8uC8hmg8n2M8mXHlRE0uy7IYtPewGRF5nJUToPQL5hGrqVBf1ss6cOdo2JOLz2rZz5o3nkALx3f6Y8BPXYoNBoCELm17f9Dmu0jDAhJNPyRvby7fjYH0h7Bi(IPiQhuS9zjjzzoZCUUkcP9a1vhBQPzkKAvTw1IrF)xNYeI7G8g0QDiJXDIU3RJn)bamN41sgavTcGuMbQhXbxKM1O8jATrHEAIc9hwASH4LQyNkvQCCX(r6AFNGge9oVUhmzxMuzlcqqsAQXERLMoxwMmXA73Ss5QftOEcJ7Rlhp8G0psCn9GqeuefQ3EjL142NuUA1I2TSl)4snFLNl1uYMELeIj9yYKjt2fkrdYP4Bp9vS)mrV9xJLL8HT2a9F5n(AyHM(bayX35Uu1NAEjvh17Pcue1ZFH64mQq1vvDvuaw)Xk(3sjmUxLufRo5wlPov9Zu9vdu)IXj2vLI72u9jzvV42QHzu)CNEQhnsJTbVdMpn5Vu3XMqNMjPueGnL9S0nEZn6ZtPmZDoJDSpKXVXk1baA4mHYs8eUbysNa5hCUP6U1SgzBcDh)Qn)q9HMalY6M1U6HlAxvW3hYyp6am64cqzbXr111MnFUh2NGokHQ(33)IeRAxUEKcaN42yB7IfRgD9fj6PVG6xnwxuHygC5MRA7fG9o(HQnZoShItqGHo1u8IhdZ2a7S7HcJXz4EbiAhmCd1Vgg748861B8))r2HrWmd6wiQVTBxcNZ4bwHmK)VjP9cw6IKYqCsDyDBdEGRebEk5Y2DJdLKC2EHiHyvxbrxm1TUD5InAQ(8Lv)ohlOUnoNrs9WbeVq8(Ka(PqLtONWvSG65ElR(8CwCwiEv1VLVtH9k84I26l)hDS0Xz9XtmrNseFFm1YQwZsdtNOqCtW0(7)l96FxAR)83ZSkT1F5DmRS2M75mYmFMGaTS1aoRtzSU1ZU(AVpVF6uGFrV1x6lGrVsFidMyWflc2ZtSkT1F7)(F0CEXmninkDt1D2mM4p5EpE9doD)hV7HRh4kWDbMC3CT1xBJhMmH6IzlVdX)CDp1vG5zw5(RuqeKmQ6GmtARbfqNgycVS2NORO(z5holx(TNCPYdQRYN17MR7VbiKhQEAovRCwqhg5QUjDcJU7IzNmiUF4(u9CCaYMximSOUnS4DV3iFwRKl4mHXjartRTXLQzx(WAvBwOsY8L9tMVCcHMuqa4z5O3I0Hcq30bSnISOgmjCg6bAGUMAqEH9dwBJ1Eq(E)1N()c

**Comment by InfusOnWoW** [comment]
That should already be fixed for the next release
