### ISSUE TITLE
"Collapse All / Expand All" button for Conditions and Triggers. 

### ISSUE THREAD

**Issue by ZINK-ZINK** [WeakAuras/WeakAuras2#3853]
Feature request: a very simple "Collapse All / Expand All" button for Conditions and Triggers. I mostly want it to work for Conditions, but I imagine it wouldn't take much more effort to add it to Triggers to so it makes sense.

When working with 10+ Conditions it can start getting really confusing and tedious to move them around. 

Personally I would love to see a "Condition Tree", but I imagine that would require far more work than just a simple button that collapses or expands everything.

**Comment by InfusOnWoW** [comment]
Yeah it certainly is more of a comment both of those tickets, as it is pretty pointless without them
