### ISSUE TITLE
WOTLK - LUA ERROR

### ISSUE THREAD

**Issue by jonomurphy** [WeakAuras/WeakAuras2#3854]
### Description

Error appearing at times pertaining to 'GuildControlSetRank'

I've noticed it with other addons, too - I'm guessing its an issue with the blizzard code?

### WeakAuras Version

WeakAuras 4.1.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAurasOptions' tried to call the protected function 'GuildControlSetRank()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `GuildControlSetRank'
[string "@Interface_Wrath\FrameXML\FriendsFrame_Wrath.lua"]:487: in function `GuildControlPopupFrameDropDownButton_ClickedRank'
[string "@Interface_Wrath\FrameXML\FriendsFrame_Wrath.lua"]:239: in function `GuildControlPopupFrame_Initialize'
[string "@Interface_Wrath\FrameXML\FriendsFrame_Wrath.lua"]:156: in function `FriendsFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

### Reproduction Steps

It happens randomly and intermittently - can't pinpoint what causes it.

**Comment by SpatenLa** [comment]
do you have a very old weakaura thats called something like [nameplate targets] ?

**Comment by mrbuds** [comment]
WeakAuras Addon does not call GuildControlSetRank anywhere, so error come from one of the aura you have installed.
