### ISSUE TITLE
Weakaura LUA error when checking player mana

### ISSUE THREAD

**Issue by spik3n** [WeakAuras/WeakAuras2#3857]
### Description

Setting up a trigger type to check for player mana
Generates LUA error

### WeakAuras Version

Weakaura 4.1.4-11-ge6683a7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x Lua error in aura 'GCDHistoryCastControl223': Untrigger 1
WeakAuras Version: 4.1.4-11-ge6683a7
Aura Version: 1.0.0
[string "return function() return not aura_env.casti..."]:1: attempt to index global 'aura_env' (a nil value)
[string "return function() return not aura_env.casting end"]:1: in function <[string "return function() return not aura_env.casti..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:669: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@WeakAuras\GenericTrigger.lua"]:711: in function `ScanEvents'
[string "@WeakAuras\GenericTrigger.lua"]:883: in function <WeakAuras\GenericTrigger.lua:870>

### Reproduction Steps

1. Create trigger
2. Type: Player/Unit Info
3. Power
4. Unit: Player
5. Power Type: Mana

### Screenshots

![WAError](https://user-images.githubusercontent.com/55240182/193715490-8dd59335-3204-40e2-806a-90c6bb64cb10.png)

**Comment by mrbuds** [comment]
It does not look like an error in WeakAuras Addon but in your aura called `GCDHistoryCastControl223`

The screenshot show a trigger 2, what is trigger 1? Your reproduction steps does not mention a second trigger.
Export string is missing.
