### ISSUE TITLE
Bug Beta DF

### ISSUE THREAD

**Issue by Shevan2** [WeakAuras/WeakAuras2#3859]
### Description

Bug 192

### WeakAuras Version

4.1.4

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
Time: Tue Oct  4 19:07:47 2022
Count: 3
Stack: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:156: in function `CreateFrame'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:779: in function `ShowOptions'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:612: in function `ToggleOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:150: in function `OpenOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:192: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5219: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4883: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4919: in function `ChatEdit_OnEnterPressed'
[string "*UnknownFile:127_OnEnterPressed"]:1: in function <[string "*UnknownFile:127_OnEnterPressed"]:1>

Locals: frame = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 login_squelch_time = 10
 lastArchiveClear = 1662186208
 minimap = <table> {
 }
 lastUpgrade = 1662186221
 dbVersion = 53
 displays = <table> {
 }
 registered = <table> {
 }
 RealTimeProfilingWindow = <table> {
 }
 editor_font_size = 12
}
odb = <table> {
 locale = "itIT"
 needsRebuild = false
 version = "4.1.4"
 magnetAlign = true
 spellCacheAchivements = true
 spellCacheStrings = true
 spellCache = <table> {
 }
 build = "45779"
}
(*temporary) = nil
(*temporary) = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 

### Reproduction Steps

/wa
Error
End

### Export String

https://www.transfernow.net/dl/20221004klxZ3mU0

**Comment by SpatenLa** [comment]
you downloaded thw rong version. this is not the dragonflight beta version.

**Comment by Shevan2** [comment]
I dowloaded with CurseForge in beta section

**Comment by SpatenLa** [comment]
https://www.curseforge.com/wow/addons/weakauras-2/files/all?filter-status=1&filter-game-version=2020709689%3A9493
the beta is what you want. what you downloaded the the retail, release version.

**Comment by Shevan2** [comment]
Oh. Thx for the help
