### ISSUE TITLE
Add Dragonriding as a Load option

### ISSUE THREAD

**Issue by jswartz12** [WeakAuras/WeakAuras2#3864]
With the Dragonriding HUD many users might make their own vigor bar to match their WA for  their characters. It would be nice to hide the combat Weakauraas while Dragonriding, and load my Vigor ones while riding. So they can share a screen location

**Comment by Pewtro** [comment]
Discovery notes: 
- `IsMounted()` returns true while on a dragonriding mount, but that could have false positives for regular mounts. 
- It's possible to detect whether a currently mounted mount is a dragonriding mount by running `local mountId = C_MountJournal.GetMountFromSpell(spellId)` where spellId is one of your currently active buffs followed by `local isDragonRiding = select(6, C_MountJournal.GetMountInfoExtraByID(mountId)) == 4`.

**Comment by Stanzilla** [comment]
There is also a DMUI_DRAGONRIDING_SHOW event so we maybe could do that same as with vehicle ui

**Comment by InfusOnWoW** [comment]
I didn't see that event DMUI_DRAGONRIDING_SHOW
