### ISSUE TITLE
My WeakAuras are gone and I cannot open the AddOn anymore, even after a reinstall

### ISSUE THREAD

**Issue by NicoWow1994** [WeakAuras/WeakAuras2#3865]
### Description

Hello, an hour ago I was trying to update 2 weakauras which the companion app told me to do. The screen got stuck and I canceled the update since nothing happend anymore.. next, everything weakaura related being gone. 
Logged onto my other chars to check which turned out to be the same.
I tried a reinstall, i tried deleting the settings (saved variables) withing curseforge, nothing works. 
I also tried running the game with only weakauras as addon installed, still not working. 
I'm not using ElvUI but another UI called "GW2 UI", if that matters.

Below I attached the BugSack Error as a Message, as well as a Screenshot of it. I hope someone can help me here as I really do not want to get rid of my entire Interface, Addon Settings or anything related to a clean wipe of it. 

I also do not have a backup folder of my weakauras, sadly.

Thanks for any kind of helpful advice in advance!

### WeakAuras Version

Weakauras 4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

22x WeakAuras\WeakAuras-4.1.4.lua:2372: attempt to call field 'concat' (a nil value)
[string "@WeakAuras\WeakAuras.lua"]:2372: in function <WeakAuras\WeakAuras.lua:2367>
[string "@WeakAuras\WeakAuras.lua"]:2380: in function <WeakAuras\WeakAuras.lua:2367>
[string "@WeakAuras\WeakAuras.lua"]:2380: in function <WeakAuras\WeakAuras.lua:2367>
[string "@WeakAuras\WeakAuras.lua"]:2380: in function `load'
[string "@WeakAuras\WeakAuras.lua"]:2395: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1141: in function <WeakAuras\WeakAuras.lua:1113>

[string "@WeakAuras\WeakAuras-4.1.4.lua"]:1258: in function <WeakAuras\WeakAuras.lua:1209>

### Reproduction Steps

Bug appears as soon as I reload my UI with Weakauras being installed and loaded.

### Last Good Version

4.1.4

### Screenshots

https://gyazo.com/6731e5bfaf34fca5a839fb6433a2e304

**Comment by InfusOnWoW** [comment]
Can you attach your WeakAuras settings file from the WTF folder?

**Comment by Jodsderechte** [comment]
thats the correct file

**Comment by NicoWow1994** [comment]
Okay, thanks. How can I attach them here without having to copy all the text? If I'm trying to attach the file with the option below it does no longer find anything in that folder.

**Comment by InfusOnWoW** [comment]
you need to zip it, or rename it to .txt

**Comment by NicoWow1994** [comment]
[weakauras zip](https://github.com/WeakAuras/WeakAuras2/files/9736467/weakauras.zip)

**Comment by NicoWow1994** [comment]
I hope this was the right one

**Comment by InfusOnWoW** [comment]
This contains a fixed version of your settings.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/9736547/WeakAuras.zip)

**Comment by NicoWow1994** [comment]
This file I just have to replace with the current .lua one? What about the .bak file, does it stay the same?

Does this also mean I will have my weakauras back or is it just to access the addon again?

I cannot currently test it since my game is reinstalling right now, I saved the WTF and Interface folder before so.

**Comment by InfusOnWoW** [comment]
The .bak file is not relevant, this fixes your settings. All auras should still be there.
