### ISSUE TITLE
WeakAuras.SpecForUnit currently only provides specID for units other than "player"

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#3867]
### Description

I expected WeakAuras.SpecForUnit("party1") to return specId, role, position but it only returns specId for units other than "player"

### WeakAuras Version

weakauras dragonflight-beta-3

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. create group
2. invite player
3. import aura

### Export String

!WA:2!1vvtZnTry44rdFubLgCAtHau8Kojnu(yAtBzctHwSsSlHAsmYke6jNvAxzTnYA3U7QyCUHhggoNFbD85EY)cyYVGD80J9u(jWHEUVRKcPTtIoiTF8(97ZZRk9SYs(uybQdljmM2jsDBFIcD7VPC3Y4Y43CN9qIGgKKoQOxn9b(mbMiCqbBJfmoFsNy6U7Ie4kEmwSIYfVy9Wqjr9O3E6LE7eWJOFXbp85)vI5GrOKGiMOjJMO8xU2AE1ChgMghVmveet2YvYrbKtjqbkklrExxPcju2o0eQY2pe(iJShOe0oDic5mZlkw(6HyIFAyOxFor8OAnAwFJgokyJlkvGwCGKtIJxflTpqM6t2HKOAbstFXO2lxTLx7wEvD9E)vnfe4k3wnR1OHBcQlrA7MDH)JiOyvKtken(8yuFIyV0KIqWEualoTBsltgy5lqyAQ8vNFpjjomlDx0B9MUiOgNOp7abtHmPyPHGxDjDmzRTtmdHR7iP7sM2TBkurTDGipyA9nSDdIrsPzLVcfdbJz5y)IwXYSyM4XwwwnT(Q78Dd6iOytPyw3veOeAxKIe5kda9S8Z7HrdZ)wd3HWVyRFlfjivQdnIkBgrvKHISqYyJ9X9HAanOJGLYl0QfeHNYrYekNewc5Dq2rejO4NbnfqTThKkjnODPQO9YDpC4D1NVUEk9s7tqsslLidtDMXyO)yUUTPBjKKawcwoWiJX56LC6IOjzkQV)z0pq)d6FewEH))jJrPkaxTopd3yFayga6KOQdijMW3T6kRUrl3ytmDU9ZtICK5hmkF3QjWgRHkwWo5jXLk96FFwk2DnsVklUNPIUjfRIo3OqbajGeaPqwVlhox3CKjE9BTSBTARbT3Ef4aiqcPDSxmLIh1BnAJ7f6S42bHoq5SNZkRV5Af(pVdwQujRHMsanppgrtczI8cOTaYidsRu5GzEZ95vWuPbe6rEHQDUuTnOLvXf70lnKc2QflveqU6eUbhcsSg9VuLp9CbvMlxXkZjyXKkZza9ddsLkw3mrEAyAsgJCHByxbEIzawQc6w(3kOYdQSjbTDvOnkVtlWk1zIna(XcZYbMB)VE2Cn4caJSqMg3WMKG1NUK(m6ZooagCGz9sA1JYjBDS5eVTI2LuSReFYJIRn4yaz7NM9z)dnLbshPphG3S1xWw)H26p6cZRN8VbeZ14LbKzBKpaDZiZpHHjBPNw)PgeBBtYhDWrsKF7vCBY6rezsyy(BPVMBgzWpVOzR)eB9m27fsubrUGj2sFj9LhNVfrXpbj2osFrDz91T5x0mzBhIx(mdJd(Jj4ZEYzDxgUnG0aBEVTF32ecVQXPkxdIis)9zKkGfyidhYnE4Z0t5ZfeapNT3CoicBikMhHAMgljg(Z)vl3SlTozq1khbQWejszOTqz(uLCczjk(K1f0DR80ue2WlQ45XV5jNuftuARIGOmc6A95x5yKo49U0pIy(10lhlJqql(xYPUxDc9xuxFlZGq9xM9(MzVxW8(ayGaZqCcYOTovHTog6WwdmbSzc2LpwVYlw4AcvmF(tonIjDqb9BhgZyIOIq755HM1GEaREtbIpyZIf61h1S(Q78KgvxYRprx1M)zhJPnqW3N26noEHm0ZJAhW)Qi5ZME151ZpZ06Pgd)tX8Nbdknbl(vGWqd770OwDp(NFY5dGzcOMrFwz0KLl4tai11GaD7z8Xl5F8HenJjwHkr(XeCe)6hxh08pRJsNFQyM6IWmv9S6ZQFSL(N1n0FRJcusVMnmKWm9LebbUkMMadP3WRXQRvBuE19OHKAp7bhghro7YyDlvEN)85)Zp

**Comment by InfusOnWoW** [comment]
There's now a **WeakAuras.SpecRolePositionForUnit** which returns spec, role, position.
