### ISSUE TITLE
"Own only" active aura filter doesn't work for debuffs applied by your vehicle

### ISSUE THREAD

**Issue by Mard35** [WeakAuras/WeakAuras2#3868]
### Description

I just made some WAs for tracking dragon debuffs in the Oculus and found out that "Own only" active aura filter for debuffs applied by your vehicle, i.e. by your dragon, doesn't work.

### WeakAuras Version

WeakAuras 4.1.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

make aura for debuff applied by your vehicle
check Own only filter
see how it doesn't work

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/61734903/194719381-569edd77-4e6f-48f3-a9bd-9d399f061ba5.jpg)

### Export String

!WA:2!Dv1ZVTrru4AIqf5kHAnOi(LuIQuJGaKGtdrfU51DdXLuVLXBiTasEND3z9mK1ZmmZS2X9wDV0ZwIRCWN5Kpcxq5VGTw8xqpWFa5aN5n7UjTLCiAM38MV5792VVNRTFJHnIBe)SnNZIe8EImve5JUs4y8arN7oZJ3T14KeVMlXzgQq5jnmbxxxnXljrtm)6cmpcI)abJBcB7213fTmsisJfJ59gZKe6ozQu5hsngP(R3EBlUBXeBFjWBVJJ9HdMAuSbdik9BVHQA5)mxtfJBNk4envLPjDXdj0xOZcjJiCtVSKe2Pl63Uvp)(98BH8vWJ6XtNeGksi8aco1qrC4A66Nda4EkoY0tsst7eh4KXzMqdwnGyMQldQRFj8pqra4r9EG7HhodNPWLWCMDzr2Sy9hG29RUZT3ZXmrsq2d2zEmje4LpeqDql093)OdNLXRkO6YBaVpBeXVC)9fXKF)kNdToIIJt)EO6HU7jNFcHiBbVrKbHH(nDgMZgAxX3dPbcB2)mcwt6zue(ad9Q5R5WHM0YyGb2S6B5JstG(ASEQnvlFY30ziMX3p)tGlKVz(NM)z5FE(MHjmott))HHcrJnwaju1OsM9MZHMdImWkb2C181wcBdXrNmqjY4XpBvzdd5utFnfdF(FyPcPM89lcw8VeHcQJ(6Qf5Bo7YZU5T0YR)kxVTivOUxTA1w5fLrjPjfQmNwh57jFNIGGOuyBmrhZInuNwW2ZlFi2PK4IGpzzPc9rv05SIZ)5mTHLmj)QZvcduI(qqNUEDDZxtbfLnNQIP82vfZ1MxelQGBRa)nRQS4g513xXE86Fxgog6z4199FTUXfp)YIyJfQ4Jvy50JRwuYQrmnlmLeu1iEfRL8gD621f13XZ337(OoFZb(Vg)QG)WRS8sc1J9yYTw(A0V2lpTqG6DK)HD66gsjSbuJWjvGJ)xfJB)Ekxfnml1WwfvSlygyF6ZbNHI68yqSDw(VL)hp)P5)5ZF6ZFYc7HJiuweWEuukwR3iudaLsuh3cH64HY93yXDDB5FW321Y(G8FkqzXb8C70C3DTUZ(eEeiKaZalMwazfvOtTBSztlYJzidj)sgmDjM6y9jRM7xFXRC73yXfxaGNcE8uWqBtYrdDLnY)XPGa0mziMN7pAQvJhlhjdqsWBnji0mgsFsWogcpyE5MeW1gKZcMMKsoT4JuOUywziBOeWA2L6tRMQWIu45U20lMggm3AhzLZprVucfcHtydQhQjdHUlQ5wFXwnrJTAxHSbuhTRaaMwaJdibq7xmSMJv7dStevzoFRr)1nzXYg9OIOtwVn1oxB9h5DeQ3Iefm6cMwa6Yvq4ujfVY5LcJ9TNyjAyV2ix3UY39c6ADe3LPXqPgdZWzXlU3o7kUtOB6OKFa0i2xfMmCAPYALZU4EUXdi0fXmTmfpPduBHnV9EnB(Lly8stpq1vLVhBaxOiv)CIRDERRsju6aLDcjeBV8pUE(21DGHtM6n0OD3Q5w72y0F)W)7d

**Comment by mrbuds** [comment]
If Blizzard's API won't let the "PLAYER" or "PET" filter on UnitAura catch it, then indeed this option won't work. But i don't consider it a bug of the trigger, you will have to find (if possible) an other solution, maybe with custom code.
It's too niche for weakauras to implement a workaround.

**Comment by Mard35** [comment]
> If Blizzard's API won't let the "PLAYER" or "PET" filter on UnitAura catch it, then indeed this option won't work. But i don't consider it a bug of the trigger, you will have to find (if possible) an other solution, maybe with custom code. It's too niche for weakauras to implement a workaround.

But how Pitbull target unitframe catches it as your own debuffs, and weakauras don't? It means API lets it. Surely It's a weakaura "own only" filter bug or incorrect API usage.
![image](https://user-images.githubusercontent.com/61734903/194747059-7cfdb1f2-ead5-46b8-b10e-8e1fe54c3859.png)
