### ISSUE TITLE
Item Set equipped needs /WA to work

### ISSUE THREAD

**Issue by Dsune0** [WeakAuras/WeakAuras2#3870]
### Description

If you create a weakaura trackinga buff from a set and add a second trigger for Item - Set equipped it will not show up until you've done /WA or /reload

Provided example of aura to test, made for Balance druid with 2p equipped, test by casting a starsurge to proc 2p

### WeakAuras Version

WeakAuras dragonflight-beta-3

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a new aura and add a aura trigger tracking a buff
2. Create a second Item - Set equipped trigger and add >=2 set equipped and a ID for the set
3. Equip at least 2p of the set
4. Restart the game
5. Trigger the aura to show by applying the buff
6. Aura will not show until /wa or /reload

### Export String

!WA:2!1zvZVTXXvCrX66kIcuj5ybfhdlgHuv7uyzlgK0Ga0p4krArdvj2LuvU(q5o7UZYDSwUZ4zMvuu9dxteuOl(cpKJbfe9ypPEpOq9JBbykrrV2c(hqlG)lOVz2Luwn28a3zEZBEF)(9MCvxSZI(l6F63JttKrKymFV9BUtTDRmK4rJBqt4E4BoJBxuBATTgS9Jfn8oiUxn(X7feiWYC8Ezlodf7fs51PKyP7Mv2Tzf7rEuAKpTBCJUeg2HnVxIqs70eFSCFMpsIDtmFoFcFv8BJd5ipjHgl(iBHeXLfCdiXerybl4JCn3uzSAHcd8PTs3e2xYjTBJ5IF(A8SL)nEIaVlQd2zakHJIHvIBWU2dqYqmNe3Uydq4czsqWOoiPxiw0iK2DV4ZfMpLbB4iSn(im4nBJrrYWXIexZ(6CCa5y7g1RSZowYEmSTwdL6ly4OOA(Ic2gTvy6fAaAHC8zT2SCJMTA0SSDZZdWGoBcUTKWcTsapZLfH6H5d9HOsqqtqS8TRSt9Q7VZGK4mNQWAQRF6B1NiXD0UwUXGp2c5kOC3Fm1h7mQngsGeVuxzCQRSzwWTVMzTMCylGFAcHXW(TOGAqskF1FW3V)eIlwsDB1DuRyP1dBXl0Hooy0Z5AAty3r9o9RbCwSbwoWedm22ioWDJl2QVIwGax18DmBNYSJAn13HTGM2L8GufnXDDgO3jH6JdDgmvuwB8HL(y17x4mFI4jjXM8wjuueBbKzDZ0qN2U)dZ8sO4eZJrr)uOybkYo8LhIXSYGH4jTrqzNZabokWueRMRucpIDZqPKj(K7DpDlW6e69M2dCVsBmwijEh2Bli)RRzdhc9m(et5BbRaASCC9MfBGIff3fX50U8Js173DiuByJBRz8XlPwzeS1f8R2qxyS)rQvgOjq5(y(zPFAjiNGZpuc9oT8OruEHZZoWS7H5YLl)4mkhree3iSZKRIH2k2cnEAcIJlwnjkQ4bHq8Bu2XutdC()5O2r0Uv5qEfh71R(x7(Rx6dvRWblrFGov8a47MA1f2xtYuKwEZgHaSXqnHDWXTLHx)m96FwgUWG2tU0dZd)mN9Ox9SgEOiCEJYBgcrZySqmNLEBO58DaPlwWiFlJbhE67Ww0eieHi)lKg7Tnen)fq5qBDlr2cRyAmEW0Jx9Blyf)kmZAjjDWT6q9BbPtSZ4uDmPEWQ8(n3JDndruca7aPCVdi(YqRYW2xMkkYXyFdXNpkfqCsC4CZ5pbaSib9uZnKtLGs0yHw7U3UvyV3BYEIWTrE9AferH4o7oVj287bOoeVwYqogA8J8ZNM70SYU1B6wP7YPQ)WT)H)NBDRF0mZmdS4Z)8)eSiF(bz3iwoSYXmqUIUOEVMWmlBHTwM(xk5Cz3FsL5iZUUq68aoI1)GSfJMQpDPLAw28Pr7lMSOMlJwQ03CATp7DFtUiy3EeDtx(leFdOz6TzR(vUYgRltXK3iJIkilnoPi70BQEEEfwfOApRk0rruprDOks155Q4CkQAoft9ufpuj6P8ZPwrjZchxsmxnnG)fFX)2eW)V)l9xiGRoInFvo5KI)KeKpueIk2SP6KCxsezr0RO(nghx9lv)k1VWr9SX12D3k2TAUxD7Apy7MQFTAwvsov)RR(0CQJv9CdXK2Hsu)jtBDSIOi)txwpoeWDylz3jb89cgy2yyYfuUzq)9IqcbODFnITxkmSHMJfNgHxs9Ic9ZWZ9CS0avAsgSBpkmaeflDgFzHSMRa0Ae(lvVyTV05V7WLaiqSSK(Ig5hb6pk0nL8AQp7QQxSeoDSbdlDrszeo0Yik1NLx9IBKE2ryacjcVpjKhK(ocTeh6tGjWEG31tVD80HphgdXHqlyKIXKhWoILQrJpnX4xcuVTX(bDzVL9(12cSg1V3z4fcz5V(SJ5NaOmWdaMD4fWaF63S)KcU3fgIQFoLlPdJYLJaqeiDUhlDCrPeI)zF8J26XLEWJVD1UhBJIyHO82D1sbXMpn5xLddcn)XEVdWOdldtEeFYwC4YfVBXYcy6yuX60UyErleVyPHCZqgD7KL(bDMe6KxeaZeTnaDxgotfXNctzNoDzkMauR(SN97m1Qw6BbVL4vmS6WagixBDcL2PE(7V(hOhkRFxtZmq33AsTNMWwebcad8DCf4oq1M7gRdJCU)qj1lBm5Y5(TdxL4ZUXR5zBfVDj2DkwAakM0Xm89JuFRQNJrcCdj3mh6Qq3xWi)SzZT0VuJlW6j0I(A(mymbwDqK4QQZnCR(ZQ)I6VcFN))NYzbAheen0uELx(k(SwkUn20UsLDH3UjqsT(WHUGEciTlagT2zWH9NG2bTR)rNjbMAaBl)nE)RCgjofWrxXYwM0oMYXzLgv0VHSc88bUaE3dCHAXAKOffSRbyeTb9ePBSVRlwIU7hS4r)Jh9)c

**Comment by SpatenLa** [comment]
did you try without the load condition? did you try a single trigger?

**Comment by Dsune0** [comment]
Just tested creating a new aura, only adding a Item - Set equipped trigger with Set ID 1528, restarted game, aura does not show

**Comment by ellhe-blaster** [comment]
What do you mean by '2 set equipped' and 'ID for the set', are they currently equipped items on the player, like trinkets or another type of item? , maybe it's a bit confusing with a definition of "item" that refers to a term to define an Aura

**Comment by SpatenLa** [comment]
they correctly choose the right set id. its a item set, like the tier sets. they have a specific id in this case https://www.wowhead.com/beta/item-set=1528/lost-landcallers-vesture so after excluding the other things bugging out, quite possible there is an issue

**Comment by ellhe-blaster** [comment]
I think you could look for auras that track set buffs so you can complement your code, for example this user https://wago.io/di4IR90t7 divides each aura according to the items he has equipped, which omits a conditional unlike yours code

auras:

- Disc Tier Set 9.2 (Dynamic Group)
- Manifested Twilight (Icon)
- Power of DS (Icon)
- Penitent One (Icon)
- Shadow Word: Manipulation Stacks (Icon)

```
...
"conditions": [],
      "config": [],
      "cooldown": true,
      "cooldownEdge": false,
      "cooldownSwipe": true,
      "cooldownTextDisabled": false,
      "desaturate": false,
      "frameStrata": 1,
      "height": 32,
      "icon": true,
      "iconSource": -1,
      "id": "Shadow Word: Manipulation Stacks",
      "information": [],
      "internalVersion": 51,
      "inverse": false,
      "keepAspectRatio": false,
      "load": {
        "class": {
          "multi": [],
          "single": "PRIEST"
        },
        "covenant": {
          "single": 2
        },
        "item_bonusid_equipped": "8126, 7704",
        "itemequiped": 173242,
        "size": {
          "multi": []
        },
        "spec": {
          "multi": [],
          "single": 1
        },
        "talent": {
          "multi": []
        },
        "use_class": true,
        "use_covenant": true,
        "use_ignoreNameRealm": true,
        "use_item_bonusid_equipped": true,
        "use_itemequiped": false,
        "use_spec": true
      },
```
you could replace the variables needed to determine the item id from [Lost Landcallers Vesture](https://www.wowhead.com/beta/item-set=1528/lost-landcallers-vesture) so that it works similar to the code above in your auras 

``` 
"2": {
        "trigger": {
          "debuffType": "HELPFUL",
          "equipped": "2",
          "equipped_operator": ">=",
          "event": "Item Set",
          "genericShowOn": "showOnCooldown",
          "itemName": 0,
          "itemSetId": "1528",
          "realSpellName": 0,
          "spellName": 0,
          "type": "item",
          "unit": "player",
          "use_absorbHealMode": true,
          "use_absorbMode": true,
          "use_equipped": true,
          "use_genericShowOn": true,
          "use_itemName": true,
          "use_itemSetId": true,
          "use_spellName": true,
          "use_track": true,
          "use_unit": true
        },
        "untrigger": []
      },
      "activeTriggerMode": -10,
      "disjunctive": "all"
    },
```
pd: I'm a bit new to interface development using lua and weakaura so I use those code blocks so that with the help of the community I can figure out a proper solution

**Comment by Dsune0** [comment]
I appreciate the help but the issue is with the trigger not working as expected, not with my aura not working

I try to keep the auras on beta as simple as possible in an attempt to have them function no matter changes or different settings not working hence the reason I used a "Item - Set equipped" trigger instead of a load condition

**Comment by InfusOnWoW** [comment]
That should be fixed in the next release.
