### ISSUE TITLE
picking up loot in LFR

### ISSUE THREAD

**Issue by Milky063** [WeakAuras/WeakAuras2#3872]
### Description

idk wasn't thinking

### WeakAuras Version

WA 9.2.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x [ADDON_ACTION_BLOCKED] AddOn '*** ForceTaint_Strong ***' tried to call the protected function 'yNAhb6PXrsm:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "return -- PLAYER_EQUIPMENT_CHANGED,COMBAT_LOG_EVENT_UNFILTERED,PLAYER_TARGET_CHANGED
function(event,...)
    local self = aura_env
    
    if event == "PLAYER_TARGET_CHANGED" then
        local friend_color, friend = self.find_friend()
        self.friend_color = friend_color
        self.friend = friend
        self.frame:SetAttribute("macrotext", "/use [@" .. self.friend .. "] item:"..self.item)
    end
    
    local trinket1 = ItemLocation:CreateFromEquipmentSlot(13)
    local trinket2 = ItemLocation:CreateFromEquipmentSlot(14)
    
    local trinket1ID = 0
    if trinket2:IsValid() then
        trinket1ID = C_Item.GetItemID(trinket1)
    end
    
    local trinket2ID = 0
    if trinket2:IsValid() then
        trinket2ID = C_Item.GetItemID(trinket2)
    end
    
    if trinket1ID == self.item or trinket2ID == self.item then
        
        local _, _, _, _, _,expirationTime, _, _, _,spellId = WA_GetUnitBuff("player", self.buff)
        if spellId == self.buff then
            if expirationTime - GetTime() <= self.config.minutes * 60 then
                return true
            end
        else
            return true
        end
    end
    
    return false
end

"]:9: in function <[string "return -- PLAYER_EQUIPMENT_CHANGED,COMBAT_L..."]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras\GenericTrigger.lua"]:611: in function <WeakAuras\GenericTrigger.lua:537>
[string "@WeakAuras\GenericTrigger.lua"]:853: in function `ScanWithFakeEvent'
[string "@WeakAuras\GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-4.1.4.lua"]:1848: in function `LoadDisplays'
[string "@WeakAuras\WeakAuras-4.1.4.lua"]:1648: in function <WeakAuras\WeakAuras.lua:1501>
[string "@WeakAuras\WeakAuras-4.1.4.lua"]:1686: in function `ScanForLoads'
[string "@WeakAuras\WeakAuras-4.1.4.lua"]:1747: in function <WeakAuras\WeakAuras.lua:1745>

### Reproduction Steps

test

### Last Good Version

test

### Screenshots

test

### Export String

test

**Comment by InfusOnWoW** [comment]
The problem is in your code:
"SetAttribute" is not something you can use without a protected frame.

**Comment by Milky063** [comment]
no idea what that means but okay.
