### ISSUE TITLE
[DF] Missing load option "class and spec"

### ISSUE THREAD

**Issue by RedAces** [WeakAuras/WeakAuras2#3881]
### Description

In the shadowlands version of WA2 there was a load option for "class and spec". I used them a lot for WAs that track specific things for multiple specs of classes. E. G. a weapon sharpening WA for the offhand of all DW specs (fury warrior, BrM monks, WW monks, all rogue specs, havoc DH, ...). A simple class onload option was not enough because then it would load for all warrior, monks, DHs too. Even specs that never equip an OH like arms warriors, mistweavers, ...).

This onload option is gone in the dragonflight beta 3. Is this gone for good or NYI?

### WeakAuras Version

dragonflight-beta3

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

None

### Reproduction Steps

1. Have a WA with a class+spec specific onload in WA 4.1.4 (Shadowlands)
2. Copy lua over to the PTR & install dragonflight-beta-3
3. Start wow
4. Weakaura now has no load option anymore

### Last Good Version

4.1.4

**Comment by RedAces** [comment]
Example aura: 
`!WA:2!nA1wVTnYv4Q6TyrvVS2ADCtA2ULRAwJe0f(IsAAXIA4kkthPyBjTu0XPalQMHKdfN1uCyho0YYVT(Hc)AvVHc0N0Z9jJI(dWO)agiS)c8d9P(u(f0ZmK2ojTUO8bYzoZzox(o3yPTRmSIFf)ZE4uQhlUhlJ7rkXh3jiiLikDoo2lKX7YOXc3gwTDSSN5Xyr(SrX9grtiOlUARL)asOPsiOtfC6GbeE6VAzEXYZQWjGOWXIl7fI5jKyIVXlA1Q1P(zCSGYIRS(5zPK(fCfovTzebNaYBQpXnliWzCcH30A3UBV)UMcyJjvqgYZIjhrIfM4mbtFR0q2OoXiBn5lpqlddRC5AMftfUjr4Xe(LPzUAE6bcNE859BuVNt)Eo1TDU(OUCcCKDVUw7U7PPjKOOw(PLVuPgSBkJ7UhZNGCZv5S8p7rttPXdovXKsDi7y8qsAz3C3PgliyswCbWSK0q(rll)MNDhzz53s(drYVt4eoziMgdYO2JxBn53fjFp58YfKvKF7kRlFF5IY7GMPK(18HKlj)EYpq(dsQCnT(maUWcgV6pFdzvK8dll)(Y7lnUi3kR7jOhrK)OYY7kVN8bYpwUSYw(XN7tt)ISy9P1WXJtwaRx7KBVk)9V(1EfKpq4X4Oxarzi4D4RoKqsQdaKNWwfodNKsIc05nY3bIFPyHkotq8JYVX3ykaX2KbWY0NVKCHzWwxS3Hd4SSy)GzUmUpH3NvKhwSnLEczUlk24XIy8N3CZ)1NRFAU5)Cj9tZn)lFG65(ZDzbNhrtPUre0vIHa5Qjl07xNH5eJTZIImoieYLKlmrzfAEoBXKkcYXciBcdP3VSOGi5EAI6xbm(qmWqXcZywmzY1hxTtZK5Fnj0qBTLkvAUlZPEf(ywFFNojVVMOkhgef17aQVi0SoS9v56IEmXxt8lNLxt(llSOl0N)fzPcAWyaR5mbGZoarZ2DABjxGd(KINPAgZbT5GNjforSiz(T50tm(SmSpeJWgooVHVFLMMPPncGNd44KtpOyXSRLJQa9cNMTAStN9D2TvBRca41AImPv72w29D609MR1dcQ3PWRE5B4vxf3o7EjF4)bUN0xqhsk2vs(lQ(Xjjg3gxdz(915Fstzd5wsl52FP8zLKnLVJSL85jp42Uyeza2BC)GigJJGAWDsE0TXQ)yOoN61xeYjqnwK)y5UAKwUNSTCJsYoLKVej7k)mPTSN05ICSWSJJtN9(VKyLuSWwjD)Kp620BcN4rv1uZjFXDKhuswxNM5gsOdcfwMrmS)zlQByKqeUyHiIeorTv15KhMurT2lcNMcHk)(QQ4qtolISSRQrweHVv99Q)mlB7Hzrc6sYqKDeC1OQpDntvj5ss6V50GiYX6OLDcMlgJofSsX4HyO)Tc59HATymQMGaTMZx7kgbTyhJMM)na6YG0DnvYm3c1QbyehbCaQPSEiXrKqQh4eMktvrLFcu7bDM)6t9PqVCpWmhd0dCJviveAc08pceXaOx9WXc42iaE4m475kmCeo6qDB0nrx(MabiLx8vZJ(TO)27H(hZJw8bi9mgp2qaidN9AwZ(0Wl1M7nnE3ydTtGJuEMTwWG8(7NVLvDNM70U1ZA6G4hu32UvhBKTDNNTVfYuH0i3U2TS6LF6UDASdcUZEDA3CF1iyKBXx7TS3V1wWv60EheVB9DRVvR2i90PBWHWj4y6q9m2NANkGyZ2xqWPKEciimqe(Uqw9MZUAmCF1GvEkbMJ7NEQIpvvTCtt1uLTL)En3Y)G8pk)tYnDdGjnPHVn5PCDFD9fF3ZPX5PRaLLsUlDaesiDsuBtTuJyT4CgpfnvPrQMCz(XfTbSVPDLlCEaDq5KfV6pou942IMIHCo)WxL3)yBomQvPy3EnSTSARZTBuCby2LTQhG5jm2WUZT2kp2nLmekbSxFL1wz9PcMxX0P7wc1Vk1p5(f)ScKBy0ta5ygDAAumFxUi68aL6aGe6AoN9iv7zRAz8OK7hkejPF6QRocpGTcLT6EUpgtcC2HSATAzu)ZnxRrVbp8eQtwcNgR0kj0ghLeINBgmea8KciQSAES6)vAb(p)X)KA)SNuR2PxbbiUA4mW2tL)UYY)CztiEiwEIpRVhmqGne5M)94sJPbgXmHbgIZWpzD0kEruVdvyNgYmeHK4YgWZTXWggn4ea907EyvZmbGhv)KQ3GqDAEfXBesEMWNyuThXlJtQRT2C2Cidb)sqQ(idJYKy)YLVfv)P9iI6rr65hPp8r)pzta)wLBMamqvEmyjvhI94SQ))Eln36X3WvxfYDma)Zh(x13or4ZJ1NU(pfwOLiqwn4Ulljlz9CpCDqTLlxj1(jRS(kpPYrF1l)3d`

**Comment by mrbuds** [comment]
Next version will have "class" and "specialization" load conditions removed, replaced by "class and specialization"

**Comment by RedAces** [comment]
Thanks ! <3
