### ISSUE TITLE
Lua Error in DF Beta when left-clicking minimap icon.

### ISSUE THREAD

**Issue by tcallan72** [WeakAuras/WeakAuras2#3883]
### Description

Lua Error in DF Beta when left-clicking minimap icon.

### WeakAuras Version

WA 4.1.4

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
Time: Sat Oct 15 22:18:20 2022
Count: 13
Stack: ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:156: attempt to call method 'SetMinResize' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:156: in function `CreateFrame'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:779: in function `ShowOptions'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:612: in function `ToggleOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:150: in function `OpenOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1016: in function `OnClick'
[string "@Interface/AddOns/HealBot_Data/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:144: in function <...ns/HealBot_Data/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>

Locals: frame = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 lastArchiveClear = 1663261475
 minimap = <table> {
 }
 lastUpgrade = 1663261475
 dbVersion = 53
 registered = <table> {
 }
 login_squelch_time = 10
 editor_font_size = 12
}
odb = <table> {
 locale = "enUS"
 needsRebuild = false
 version = "4.1.4"
 magnetAlign = true
 spellCacheAchivements = true
 spellCacheStrings = true
 spellCache = <table> {
 }
 build = "46157"
}
(*temporary) = nil
(*temporary) = WeakAurasOptions {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedX

### Reproduction Steps

Lua Error in DF Beta when left-clicking minimap icon.

**Comment by Stanzilla** [comment]
You're not on the dragonflight version
