### ISSUE TITLE
Installed/Updated auras never disappears from "Ready to Install" section

### ISSUE THREAD

**Issue by KasperOnFire** [WeakAuras/WeakAuras2#3886]
### Description

Whenever I install or update a WA, either from manual import or via Wago App or Weakauras companion, the "Ready-to-Install" entry never goes away.

I have cleansed my pc of every trace of Wago App, Weakauras companion and Weakauras 2, still happens.
The ghost of "SL-Dungeons" even persisted through this.

Where is the cache for these located?

### WeakAuras Version

WeakAuras 4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Install Weakaura from wago.io, either manually or via the apps
2. Try to install/update
3. Weakaura installs correctly, but never disappears from entrylist.

### Last Good Version

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/19799989/196139929-79c5ad84-8792-45aa-bdc9-ee68afbcf117.png)

![image](https://user-images.githubusercontent.com/19799989/196139949-063dfae6-524d-4894-9321-ab74eb50be46.png)

### Export String

[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/9798869/WeakAuras.lua.zip)

**Comment by mrbuds** [comment]
If you removed the app without removing it's addon it keep sending the data to weakauras, remove WeakAurasCompanion or WagoApp or WagoAddon i don't know what it's called, in AddOns Interface/folder

**Comment by KasperOnFire** [comment]
i've tried removing all three, but i will try again with a clean slate.

**Comment by KasperOnFire** [comment]
and after clearing the list in WA Companion:
![image](https://user-images.githubusercontent.com/19799989/196192469-667c1c6d-4be1-4d22-84be-246b988f57c0.png)

![image](https://user-images.githubusercontent.com/19799989/196192492-e7c3bf01-f8fd-4132-b65d-e5c4f6fc5ab4.png)

**Comment by mrbuds** [comment]
Iif data doesn't come from the addon of weakauras companion, it come from the one of wago app, or cursebreaker, or i don't know what other app you may have installed

**Comment by KasperOnFire** [comment]
fair enough. Thanks for the help! I will try and purge all of it, related to this.

**Comment by ptarjan** [comment]
For future people running into this, removing the `WeakAurasCompanion` and `WagoAppCompanion` folders from the `Interface\AddOns` directory solved it for me
