### ISSUE TITLE
Latency overlay sometimes fills 80-100% of castbar when interacting with objects

### ISSUE THREAD

**Issue by TorianKel** [WeakAuras/WeakAuras2#3888]
### Description

As you see on screenshot there're 2 castbars: one is mine and other is some import from wago to show that it's not unique to my setup.

### WeakAuras Version

Weak Auras 4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Find interactable object (usually a quest one)
2. Click on it to start casting (there's some chance of issue being present, but if the object "caused" it once, you can stop the cast, and reproduce it)

### Screenshots

![image](https://user-images.githubusercontent.com/20046227/196511089-97238343-e5a2-4d5f-9454-7d81329c655e.png)

**Comment by InfusOnWoW** [comment]
I cannot reproduce that anywhere. I've tried various interacteable objects, such as chests, world quest objectives and the cast bar behaves like expected.

Where is your screenshot from? 
We need to be able to easily reproduce it to figure out where the bug is.

**Comment by InfusOnWoW** [comment]
**We need to be able to easily reproduce it to figure out where the bug is.**

**Comment by InfusOnWoW** [comment]
Sorry, but we don't need your help in debugging the issue. We need your help in figuring out how to reproduce that. And I specifally asked you for that, and you did not provide any hints how to reproduce it.

I'm still interested in how to reproduce it.
