### ISSUE TITLE
Nesting Dynamic Groups

### ISSUE THREAD

**Issue by JoshBowdenConcepts** [WeakAuras/WeakAuras2#3889]
**Describe the solution you'd like**
I would like to be able to nest Dynamic Groups within one another so I could create a stackable UI that flows with one another. This way you could have both a vertical and horizontal group. This would allow for some amazing UI customizability.

**Describe alternatives you've considered**
You may be able to do it within a single group but I think multiple groups would be easier to work with.

If this is already possible or in flight let me know and if not let me know how I could help contribute :) First time looking at your repo

**Comment by InfusOnWoW** [comment]
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/3786
