### ISSUE TITLE
Class Talent selection as load option

### ISSUE THREAD

**Issue by Hexxagon** [WeakAuras/WeakAuras2#3891]
**Is your feature request related to a problem? Please describe.**
In most cases no, it can be solved with just using "Spell known". But in some cases (Victory Rush/Impending Victory for warriors is where it became an issue) a problem arises when selecting more than 1 spec won't let you specify a talent and using "Spell known" will track both spells even if "Exact Spell Match" is used.

**Describe the solution you'd like**
Having another talent selection, let's call it "Class Talent" below "Talent Selection" which makes it possible to select more than 1 spec and then select what talent in the class-tree should be the load criteria.

**Describe alternatives you've considered**
Tracking both regardless of what talent you have and then a ton of conditions

**Additional context**
If it's unclear what I'm looking for I'll add screenshots, but I don't have the time right now.

**Comment by InfusOnWoW** [comment]
There are no class talents in the api. All talents are spec specific.
