### ISSUE TITLE
Error Weak auras

### ISSUE THREAD

**Issue by Nata013** [WeakAuras/WeakAuras2#3892]
### Description

Whenever I enter Battle for the first time I get this error

### WeakAuras Version

4.1.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

117x [ADDON_ACTION_BLOCKED] O Addon 'WeakAuras' tentou chamar a função protegida '<unnamed>:SetParent()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SetParent'
[string "@WeakAuras\WeakAuras-4.1.4.lua"]:5181: in function `AnchorFrame'
[string "@WeakAuras\WeakAuras-4.1.4.lua"]:5053: in function `func'
[string "@Decursive\Libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <Decursive\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

### Reproduction Steps

error

**Comment by InfusOnWoW** [comment]
That sounds like you have a clickable aura that creates a secure frame, and that's not how WA can be used as the game limits what can be done to secure auras.

There should be a warning icon on a aura in your settings. If you attach your settings, we can help you identify which auras are most likely the culprits.

**Comment by Nata013** [comment]
I found it, I was looking for the warning icon only in the groups without expanding them, and I went one by one, I found the error icon, Thank you very much I was looking for a solution for months.
