### ISSUE TITLE
Spell Haste not tracked on channeled spells

### ISSUE THREAD

**Issue by TomKuhn** [WeakAuras/WeakAuras2#3893]
### Description

Spell Haste not tracked on channeled spells - e.g a replacement cast bar for the channeled spell "Mind flay" always starts at 3.0 seconds duration, and should be shorter than that based on spell haste. This is very noticeable during heroism/bloodlust, and causes the cast bar to end prematurely way before the end of the bar. Normal spell casts, e.g mind blast seem to work correctly

### WeakAuras Version

WeakAuras 4.1.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

import Passion Priest Suite: https://wago.io/XWIG0jzu_

make sure the priest has some haste, channel mindflay against a target dummy. Observe the spell always starts at 3.0 seconds which is the channeled time if haste was zero

**Comment by InfusOnWoW** [comment]
We do show what the wow api provides, so that would be a wow bug not a WeakAuras bug.

**Comment by TomKuhn** [comment]
Updating to alpha WeakAuras-4.1.4-23-gc5bb8a4.zip seems to have fixed the issue. Although it could have been resolved by restarting the wow client
