### ISSUE TITLE
Previous saved auras have mixed with latest dragonflight-beta-5

### ISSUE THREAD

**Issue by lloskka** [WeakAuras/WeakAuras2#3894]
### Description

All auras created earlier in version 4 ( or even 3 ) no longer work in version 5. 

They have all been mixed up and **there is no way for the class and specialization option to work.**

Alas they're not loaded at all on chosen class / spec.

Tested along with 12 chars ( about 70 auras between all of them )

### WeakAuras Version

WeakAuras dragonflight-beta-5

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No Lua Error ( test with console ON )

### Reproduction Steps

1. Download from https://www.curseforge.com/wow/addons/weakauras-2/download/4036685

2. Extract to \World of Warcraft\_beta_\Interface\AddOns and overwrite previous files ( from WeakAuras dragonflight-beta-4 )

3. Log into the game, and play.

4. Open /wa on chat window 

5. All the macros from other classes and specs are loaded when it should not

6. Even selecting newest option class & spec dont do anything

### Last Good Version

WeakAuras dragonflight-beta-4

### Screenshots

![WoWScrnShot_102122_201852](https://user-images.githubusercontent.com/20574132/197263605-506a0af6-aa78-415d-af88-c3a40c8527e2.jpg)
![WoWScrnShot_102122_202142](https://user-images.githubusercontent.com/20574132/197263613-29e2aba6-303d-4958-bb06-b5c64b200867.jpg)

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/9841433/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
We made a backwards incomaptible change, but as far as we can tell the new settings do work. As such we would need a example aura that shows the problem for you.

**Comment by InfusOnWoW** [comment]
None of your auras in your settings file has any class/spec load option selected.
You claim that you have no lua errors, when an addon in your screenshot complains that there are too many lua errors.

There are enough other red flags to make me doubt that we should invest much time investigation your problem, unless you present much more convincing evidence of a bug.

**Comment by lloskka** [comment]
aa i said , even selecting class and spec doesnt work in versión 5

Check it again , créate a New aura on versión 4 ( a y spec class )and then switch to versión 5

Test it properly Please 

Thanks , have a nice weekened

**Comment by InfusOnWoW** [comment]
That's not "much more convincing evidence", and thus we won't.

If there's an issue, someone else, more adept at reporting bugs, and who can propely follow simple instructions, will report it.
