### ISSUE TITLE
Empowered Cast Error with Overlay Latency

### ISSUE THREAD

**Issue by iamawl** [WeakAuras/WeakAuras2#3896]
### Description

I'm getting an error with using a cast bar and/or empowered bar with Evokers. Only happens when casting empowered spells. From what I can tell it happens when the "Overlay Latency" option selected.

This wasn't happening in 1 of the earlier beta versions I'm pretty sure.

### WeakAuras Version

WeakAuras dragonflight-beta-5

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: Interface/AddOns/WeakAuras/GenericTrigger.lua:3482: attempt to perform arithmetic on a nil value
Time: Fri Oct 21 20:13:59 2022
Count: 1
Stack: Interface/AddOns/WeakAuras/GenericTrigger.lua:3482: attempt to perform arithmetic on a nil value
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:3482: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:3476>

Locals: self = Frame {
 0 = <userdata>
}
event = "UNIT_SPELLCAST_EMPOWER_START"
(*temporary) = <table> {
 HandleGlowAction = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3331
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @Interface/AddOns/WeakAuras/Transmission.lua:343
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2433
 InitializeEncounterAndZoneLists = <function> defined @Interface/AddOns/WeakAuras/Types_Retail.lua:10
 IsEnvironmentInitialized = <function> defined @Interface/AddOns/WeakAuras/AuraEnvironment.lua:198
 form_types = <table> {
 }
 CleanArchive = <function> defined @Interface/AddOns/WeakAuras/History.lua:22
 RunConditions = <function> defined @Interface/AddOns/WeakAuras/Conditions.lua:721
 tooltip_count = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 get_zoneId_list = <function> defined @Interface/AddOns/WeakAuras/Types_Retail.lua:66
 checkForSingleLoadCondition = <function> defined @Interface/AddOns/WeakAuras/Prototypes.lua:1068
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 ensurePRDFrame = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:4880
 talent_types = <table> {
 }
 LoadFunction = <function> defined @Interface/AddOns/WeakAuras/AuraEnvironment.lua:625
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 FinishLoadUnload = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1915
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:203
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 StringToTable = <function> defined @Interface/AddOns/WeakAuras/Transmission.lua:292
 RegisterLoadEvents = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1765
 FixGroupChildrenOrderForGroup = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3805
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:1014
 CheckSpellCooldown = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2310
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:2131
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2490
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3475
 NeedToRepairDatabase = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:2210
 StopProfileSystem = <function> defined @Interface/AddOns/WeakAuras/Init.lua:259
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 CheckSpellCooldows = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2364
 IsOptionsProcessingPaused = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1456
 ValueFromPath = <function> define

### Reproduction Steps

1. Create a cast bar for the player.
2. On the Trigger tab, turn on "Overlay Latency"
3. Cast an Empowered spell

### Last Good Version

Beta 2 or Beta 3?

### Export String

!WA:2!1vv3oTXruywzjQIvjI40IksOwAutvtLijI2K(BARxh7yhCSjR3eG0OUE2Dg7DAwpZKzMfWCxSQQ4A)i4R7v(rGl61JS6tapc8e0zMDLHef4c0Co753VZ58zNALgucwcE8DMiya(R2bdLXF8eCeL0HMYJqRTWmqQmMYBZKykruKpSDVEcK0zkGeP1VnftKHvQ2YVQ3mBm8OsGXwh21El5NqHi3YpZVTRj8XJKCC)(iU4QFjp)5)6khYqUPeSKvkvGcaHckpSocKyCU7PI0q0(iIStAVE4dNguPCh)Go(L98pZyUiMEqtGerIg290Z936RN1r3kaHuD1qwcyiIpsWqjjnGIIZJ82CKoYED2UAZMEeWaKO4itKm1u3jquOoZ(6IKxVAZTR9SMJtj5fFr21ars8(i)mztw)NfSqzqenHYFCb9FNPrleNasEUUZ1GYRhlqj9SGOAXrHaELmtDCkOZMait56gk(elsMH875mrxTEO(M5XJxrT0mTyii6v950ucmxrpkhLP44vzLKOdLA4baPhSBwukm2QZ8VBCtgB15sbAphaKbS8hEs8ae80SimVwVc76wn6LdQ2iCKDZXTSw8SSOGpebTkFd7lEpb3e1GeuFq0WGEjukp(eRb)zQqI7nuT4eUzVb5Rv62QDRQSp)YIcJJIWgWSGAjUU1nMmlB7mVzDMyD78XW48WqKSLRXXhT(ttbqnsdw33NT8fqRSXHJEC8wG4EzXDTfYk691Ppmb1DMv6akhUdhWgTt(JzZZMz1XTfLGYtYfUHM0OvRQEbnRwZN9PxwRMj5Ww)Ymyafgy2y6EEo7GpcTk7wxMhWH61CCuGmMJ0hqjWH5yxEp6C8hPUvb1xFJBsu)KfjuBOUI62Q7OU7Bu1DuBQwu9nQVvTK6(QV3IUQFq9JQFETfu)I6xvpORYDAwV514r19v)MQSQ2QQVZ59S0rYF4s0yuymc3pw(zUjuaSwOeKOpqxXBqAIex0vF7gTIQDrVOeGqyE5k0DQ5XP2RfxT5qZv4MLF4dzlRVIldnBxiic(eWHXH6lZE4(fhdi4bwgQ77jKaUS2jiGa1rYrK(Y4pq3yBndAUd1MeyyO4cK2xOyKXoZivTL7aaMutTN1A1lu)U6LQTc7Hjyr87Q(DRfmjEc3EoBzwa6uPjc4g2e9f(9v7wu9hfD1HswKFy(qzSLxrGHiplQErcIDD2mfdN(6hjoG)0W09s2zQ9R1TW5d4gapLJg5MGp6iahEdmCuKMxCDDwZIJFMfSVQHHTQhic9sdXjM03fWF5ZASX5sB0XYXBDlEIKgTFgX2N483tYtlgcreVwvFEvppqclguyApUMAvJW6lUcEhyyj(Rp8SS1UAMpzaIWov8QwTv2pmvz(PlhtmPaf7EeLoWzkLJ1Rf2HZK6T9A8I2T8l3CIzaHZ(jRPys2wLwQ4zNZuo)2E7c3923RKGDDnfqF9srIbN2iejbBCVs7)F7())

**Comment by mrbuds** [comment]
Thanks for the report, this is fixed for next version.
