### ISSUE TITLE
WeakAura addon not loading in game

### ISSUE THREAD

**Issue by dewson8** [WeakAuras/WeakAuras2#3897]
### Description

When  I log in to the game the weakaura addon will not load. When I type /wa the options screen will not even load up. I have tried loading up with only weakauras active and it still will not work. I have also reverted back to older versions such as 4.1.5 and dragon flight beta 4 (which was the last known working one). None of this worked.

### WeakAuras Version

 WeakAuras-dragonflight-beta-5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

2x [string "return function(event, combat, encounter, a..."]:2: attempt to compare number with string
[string "return function(event, combat, encounter, alive, warmode, petbattle, vehicle, vehicleUi, ingroup, player, realm, spec, class_and_spec, covenant, race, faction, level, effectiveLevel, zone, zoneId, zonegroupId, encounterid, size, difficulty, instance_type, role, group_leader, affixes)
if((level>40)) then
return true else return false end end"]:2: in function `loadFunc'
[string "@WeakAuras\WeakAuras-dragonflight-beta-5.lua"]:1634: in function <WeakAuras\WeakAuras.lua:1511>
[string "@WeakAuras\WeakAuras.lua"]:1846: in function `Resume'
[string "@WeakAuras\WeakAuras.lua"]:1155: in function <WeakAuras\WeakAuras.lua:1117>

[string "@WeakAuras\WeakAuras-dragonflight-beta-5.lua"]:1264: in function <WeakAuras\WeakAuras.lua:1215>

### Reproduction Steps

logging in is all that is needed to reproduce.

### Last Good Version

 WeakAuras-dragonflight-beta-4

### Screenshots

n/a

### Export String

[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/9843604/WeakAuras.lua.zip)

**Comment by mjakobsen** [comment]
+1

**Comment by SpatenLa** [comment]
if you have the same issue,its because you have the wrong version. they say they are on the retail version, while loading in the dragonflight beta version. that doesnt work.

**Comment by mjakobsen** [comment]
Well that seems to be right, but i'm just letting CurseForge tell me what's the newest, and using release channel, so don't get why it sent with that version

**Comment by dewson8** [comment]
I've reverted it back to the retail release version and it still was not working, so there is clearly something going on with it.

**Comment by InfusOnWoW** [comment]
The original issue was due to installing the df beta on retail, which is an unsupported way to use.

As to our new issue, please create a new ticket. Since most of the information in the original ticket does not apply anymore.
That is the error message will not be the same, your settings will be different.

As a note, your zip also only contained the .bak file.
