### ISSUE TITLE
aura_env.saved not properly getting saved between sessions

### ISSUE THREAD

**Issue by Reloe** [WeakAuras/WeakAuras2#3898]
### Description

aura_env.saved is getting erased if you log out without ever opening WA options and the aura never loading in the current session.
I recorded a video where I tried many different things. At this timestamp you can see I'm adding data to aura_env.saved, then relog, then relog again without opening WA options. This made the data get deleted:
https://youtu.be/ZOfuQG0q1og?t=2118

There are other things I try in the video. For example at this timestamp you can see me checking through the data on the DH. Then I log over to my monk who is in an active M+ which makes 3 of the 4 auras I'm testing load. I close the game without opening WA options and log back on my dh. When back on the dh the 3 auras that were loaded still have the data, the 4th one does not:
https://youtu.be/ZOfuQG0q1og?t=1930

### WeakAuras Version

DF Beta-5

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Add data to aura_env.saved
Logout and log back in(I assume reload would work the same)
Logout and log back in again without the aura having loaded & without opening WA options
Check the aura's information tab to see no data available anymore.

**Comment by InfusOnWoW** [comment]
Thanks for testing that. It should work in the next release.
