### ISSUE TITLE
Spec Tree Talent load condition while multiple specs of the same class are selected

### ISSUE THREAD

**Issue by xerwo** [WeakAuras/WeakAuras2#3899]
**Is your feature request related to a problem? Please describe.**
The problem is that you can't select specific talent load conditions if you selected more than 1 spec of the same class as load condition prior.  The general class talent tree is the same across all specs thus it should be possible to make a weakaura load on a specific general talent for all 3 specs without creating the aura 3 times.

Example: https://streamable.com/9xp5jh

**Describe the solution you'd like**

If i have the same classes but different specs selected in my load condition it should give me the additional option to load the weakaura on a specific talent in the general tree of said class.

**Comment by SpatenLa** [comment]
the problem is that they are not the same accross the class. As much as it seems like that, different specs have sometimes different things in there and the data in the background is also separeted by spec not class.

**Comment by mrbuds** [comment]
>  The general class talent tree is the same across all specs 
There are exceptions which make your request impossible

As a workaround you can use the "Spell Known" load option
