### ISSUE TITLE
Bar Alpha on Progress Bars not in Conditions Tab

### ISSUE THREAD

**Issue by dridner** [WeakAuras/WeakAuras2#390]
I'll preface this with 'Great Addon!'

On that note, I've noticed that under the conditions tab for Progress Bars, there is no condition to set the bar alpha.  The goal was to have a 50% opacity bar out of combat, and then set the opacity to 100% while in combat with a combat trigger.  I could do this with the bar color option, but I'm also coloring the bar based on different conditions, so I would have to have extra conditions for fading/not fading.

Thanks!

**Comment by emptyrivers** [comment]
Transparency is tied to the color condition.

**Comment by dridner** [comment]
I don't disagree, but there's an independent Bar Alpha slider in the Display tab.

**Comment by InfusOnWoW** [comment]
I intentionally left it out, because the progress bar is the odd one in having that. But I tend to agree that fading being orthogonal to color has some benefit.

**Comment by InfusOnWoW** [comment]
As in, I actually think it might make sense in all of them.

**Comment by InfusOnWoW** [comment]
Implemented in 8.0
