### ISSUE TITLE
"Player Class" Load condition missing from Beta 5 10.0.0 DF version

### ISSUE THREAD

**Issue by MetalMusicMan** [WeakAuras/WeakAuras2#3900]
### Description

The "Class and Spec" option is still there, but the "Player Class" load condition is entirely missing from Beta Version 5. 

### WeakAuras Version

WeakAuras-dragonflight-beta-5.zip

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Try to use any weak aura with a load condition set to "Player Class", it will load on all classes because that option is entirely missing from the Load conditions options. 

### Last Good Version

WeakAuras-dragonflight-beta-4.zip

**Comment by InfusOnWoW** [comment]
Yes that is intended. You can multi-select all specs in the class/spec load option instead.

**Comment by MetalMusicMan** [comment]
Oh, that's unfortunate since I'll have to completely redo many weakauras' Load conditions :(

**Comment by Nokramx** [comment]
The weakaura devs wrote a modernization code which means "player class" loading condtitions will be converted to "Class and Spec" with pre patch release. So if you can wait until that you don't have to deal with it.

**Comment by MetalMusicMan** [comment]
Oh, fantastic! Thank you.
