### ISSUE TITLE
Balance Druid Starweaver/Rattle the Stars talent load condition is reversed

### ISSUE THREAD

**Issue by kory-stiger** [WeakAuras/WeakAuras2#3903]
### Description

It appears that the load condition and talent known trigger for this choice node is reversed. For instance, in order for my Rattle the Stars aura tracker to load, I need to select the Starweaver node in the talent selector, if I select Rattle the Stars, it won't load. 

### WeakAuras Version

dragonflight-beta-5

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Just make a class/spec/talent load condition on balance druid for the node shown in the screenshot (Rattle the Stars/Starweaver)

### Screenshots

![image](https://user-images.githubusercontent.com/59121984/197572329-2c8f1c13-1582-4b98-ae06-a6d631cb5ff6.png)

### Export String

!WA:2!vA1tVTXXv8WqxeecuGyfhvBdv0fSWsYTsYYkrSPPrjLKAPKCOPe2LkkgffKZU7SCh7LZUEMz1FIHBr1HGCwFe4H(bGa9qVQ7fyarrVMcFSxkG(e03m7YLKsUhYEG8nV59V5n)EV3uOXC9NZBoVV)bdiUru7OeMlEH3HD2(((CSOWqe1niIDqeHkCQB2QTP1i3OOqVOtO2NqIXDVC8stVE4U1uwP75cgPxpmJtxKLr(VyjCCluFC3lacBbY9f8UxGsyikWKF)rwiHie7zaBX4J6JeUbyUDq0j7thWH)QgEc6mUf(ymej7IrHIG3WtC0RpGH9jNAzFGzZMd8Woj((TplgZ21S5bnoS558yCy4EE8swANvQwcLiCIdrNHz5gXg0IC6Wo1RA3UJD7QwTRjaJyPIXnCGG2c3hcEA2bQ0IY3)7UYnHlI6)1igb5eI5X)8xvYq)5IOniucpWylJLCGu0sRu61YfCsvi1J84TR308Wpth3z(9W61nTTx5g8vXZn42O6Enn3EyQn7OI2HCbsGtI9GFTGmO7lCsxiVJ8JKLp9D)p(juxbjIUmkmulm)H6qM4BqJegQtBhm941crCHre7Am(CJDWI2K(4LFOXQgRV2JnebyA2z24AcV1eHZLimYffAOUHmPEQ9aP44qSRy5kRyCu1oGkhc3o1ajwEP0ROLwXyPzGhkgh0S6ZmTw6Hx30UGNZm9tTNy8nxXqz26WUeAV9O(r5w)TyIj3DcwcoFBihnDKpZrpB)zD)nK46qJPn3xCnLFKXJxF91NrDCihdojpn3Z1Zar9MLXxyS(pwhpT(Z6q6K1ttNdE(dLl)hbZ9Qz0svVML7wzMnCdq0EWT4BDVPIUC6jI86CkgwKWOtUzghxz89rqsQeWuEx59K)cDD64sKaIh2saNzp5cYYq9qH3s9Wkg6QZvmeaj0DWmDLsxf8bZaU6(K7C4EBpMw1ABmDJqup(4fwiIxgdpmxKQJIkvdf1uBpL0znTYiusNItlnbOMcGvMeYzk4TIC5YPSlNxxpjAn2ARPvAguYQRAu5XF86FIbHR2q5wxc4KY7uF7YPbX1QtG0ftxFdXoaGuzX0AEBLW1ZMlSS2QpC6IOCf1G3CDVbODgy9wtP2VoxPBGoVgAqJsu8kvs(a5IYLKFG8xg)Z()03v3Lmf2m0JWFUgBCmEde9S4BJ00TtB))0ipCXRGPIygff(1WSoiyE5vVaJJRQYCWnjeEWeokPVoqRyPd)gxIrQ5FmmTNi49KluJgrXJgFC0nXzCmmf1JFUsu1GmzLA9reAd5MGcYkYFJ8tL)wzfhFDnY1zdta5iHYG4Uda8RfUhyz(tMxUWiyPdm6ThlkH65lx4cfJiMhMnm9VoCY3IlEz2c3OWi2t29l)V)W)(DGVcfk(MSDoMWjWeVGXQHHP)X32(Ljig2OrsyOXrbebEu22rPpNa8O8lL)(IYQpPaymzTUY6YTLMf((5JNtGpv0HhGaqZ3K98J47PzQ)XpIbzYo8mczLlY3R8d4XFWuQxxh2kp8MuU4qF9tyQv9W27h)HAMOeOJaK0DpI4jcQvfwEvQJiNI90m)lJsF(ZZYcNl17)COxcX)m5TgWIunmAdmR1A)wMYfyq6ujt2Hjv7XhMbAEPP0IW3fzhlQ4YQmvLwleJfDYmjIXEEKM3jqY8igk(8JYisdOS7IUz5GPEYw8T3RvltRo12VD79FQ1E7SB7zcTznVkuSHR)pA0Sb(KD1VQA)dB3CVwMobysVaXM1cJqE)134cJ85Gz96OG)Z7WHXSH4)HJafcTpN3QFsOGS4FV7FRBnLalk9lkdknaExvNurcupmSJ2mDpxrQet)AXouOHmlWsVhOO12wq3lq745Yvj3ZG5HJW8kBZ0aFDb07Dv6rQbd6JQ44yx3Y0SfdPB(ZRi)KsYFxPAqbLO0qcnfJb7S4qG0fRNbaXL6XL9Ag1lyGQcLO19xbDvQiF)INFC2ZaDudxXEwhJctWfzPd943F(ZJzrq(tCM8Ztv5NiF1f5J6KVUG8pD)fLVUR8phFhaiT2gRnBX2iaYcNH9J1UTKfkmoavCJeI3W2y7g788xUBZN9847m(f5kG52eUkK86w7BJI6FWTwFTpEZbIi3Jt7yD3cF3GYep5p1AcUuNvh39g6ZzPAKyDIQGyZH(Qei0(cjqfDGCGpPxjgHQmhoyJewy89ceIy(N9OhDcQx0AKOhv1wWDB)vFA4f51HYBPAVQMeThyJ7(UZT(5Jd6UStZGDZXJ)qpgyeQFOcPTQdwGwDZ5o(F(n)V)

**Comment by kory-stiger** [comment]
Nice that was fast! The talent pane magic is a bit beyond me still, was it like I guessed or something else?

**Comment by InfusOnWoW** [comment]
No, your guess was incorrect. The talents were changed places, and that requires updating data in our side.
