### ISSUE TITLE
Arena unit triggers are not working correctly.

### ISSUE THREAD

**Issue by Kazimazi** [WeakAuras/WeakAuras2#3904]
### Description

When enemy has certain buff proc in arena weakaura should trigger.
Trigger type: Aura
Unit: **Arena**
Not sure if having the weakaura in a dynamic group is relevant.
The export string I shared is set up so it should instantly trigger on almost every arena game start, since I chose most common or must have buffs in it. It's not so practical for real games.

(Having multiple weakauras for respected units arena1, 2, 3, 4, 5 works as intended.)

### WeakAuras Version

4.1.5

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Import weakaura.
2. Enter skirmish game.
3. Aura doesn't trigger.

### Export String

```
!WA:2!DJ5(ZTr1vCCufbiBOeJsWqGuQAkKPanEsCiqHFaQxBzBrSTuxjJdPp0E1UxP9gVA3139U2wUpO4sPPL(ae9jTPpuFLsjLu12W0b(Ho(pGoNXth(dW)jKP)whMPN7URKL8RqG0Pd4FW(U39(ApNpNVNZ1jEYu(Ap4ahBGtKQwkZuMN9OQv5Ul0C8CAzpDUPko0eRv2LBs5QeJzn5UEE9PAZwAjc3mDrxxBbZJVyUkv8PIe86rng)tN7P)pV9t)2)ZwehdlxEExMJO8WzMQygTwrR2WU2U8NirIej189ig0DXjgcMRJ)dP5liCHIkZHjukxb)JVLYYcoRAvk3)opmpU5Z10KwoOsLI19O8XZmr(rNEcvb(GgjGtgCzFpQTDwtFL18dktNN6ikGJMTyRsdpuHILkuCiTIQb4Mu2ZMuNY1Ci1O(kAHdT84uITWQZuZZP4u1kKpZet0iWj(iO0YW1oOMtb5xqYYCIjlW)zV5g(u7kHFZWU1i2SQoWUvnP(gC1aCAMdWXpr58t0exFnAv53TIQTlXCuvF2s0(1QfGgwfv8BWOF4bu0mSj((YwLfeB88iB2OkNzodZuyTNvlh7CImRjtMmFYJoWj4ehwnIGA1iQbUppe8Hhf2VQJRdDfkXNwqWPovfw34QMOvtoIssBi3NA46y6VSCmslmCC1AeMdox44WdEJWjGhcEyS5E3ypA(g4jm5Yb(0jy1ycRYroCRMr)nJzvQ3TwyUacNME0aB70ZyXe0M8qZGCRwXSo6kygigg4fpRcOvzxQ(UCbC8gHVilE(UJp0n)gxgnZuUdX(jXdnUcZUkjqGmxoVqCsjM3Y6GCzY1WjH2EhXOiT5YlRn0izNUGMT8GUNvIgzecV7LLwx5X5qAJ0u4AmF0YFtZ)poeZ07EgYMYfPps6mo0A1tlpm(PnhtEWWolMPqXStnwZk4N3WmUHnvVvfoIxO1MiijVCuyXOYUKBr5cdRLjZulJXDrO0GbmZwJDSrgKio(85mQJVre6Cs0GWnMi0J9S93u6IyXFMmNkU8iFSsz8fvyvvsz8YN9EBYWNk4gWnOh860mAdijBAe4lCRvKUO4qkkWnMaUjy3RAGH0MUl4uybMhvFL2pk9AwWnJ0JcClkWEvG(ULdd36z33AOFEsIWWQKHlgxGKgIrHrs3PxFdXnio00zrpKTn1qGM)ALzo08u(0yGNfCanKcCiRi5CwfMHS3YHDDSwHE5Ovn1rHuW(A6B5UWW2i56RJq3Tb3oChWbHpsRARV)PoQ3(66XCijtqhDQhd6xHJh1PWtMU8mp26RUU3(6AV6Ak3n8rH7sbsR4DRsXP5PfJc7N01K(Qxhm8SxEwk1Bi5HxOjT8wWGrXx9gJ8PUYrnOwMpriJarZ8N4r7h2)QO0GmQwE0CmFRvRA7UWOC6CbuhJ65V(JoWGNqv2N(kYVgSryOV(YY(KmLwE2Iu7MYhJ4L6TKTFQyP6gvBpLNi54p(RF7H)m(JVsd5pVusy)CC)LJjCwNkEwHNIIwmJzrNGF(KhBGhoCHkiJ5ZF9yAKte(8eOt2FxHBUAu0)zVBVpMarTsH)kcvl5vsWQrl5XrVVm4kzJodr7ELsZE31MMJS7sHumCeVdSflzudn5kB6DFB3EgRXusyXPixzBwFTWr1r6wDOPlMZBFHDIkkUYqlJq1w1HWhVC0AI24ij4NXl92Tv1CnljDS6Rgf232fSs4ypdgfYQuh2DZWyCQmEuDQCtLX7E2Uf0MwLyuVufBxxULxQOZTfXCD)u0sppAulJAprotzxBXHm0EYXSD1kjdB1CW8D8MHJyDTIgXZWr413OC2sP)mbetPuw6If3U1KuUmNopt(H3ZzS9NV3b365f1wvkfSA4lxajOz4eVLNjUXQDonH5(ZnDXjYI2R(I8vRxXXk4BYOvsnxXI5M07U3oZz0tjINF0HC9YtwFZK5GoqSpSTHElCsB4JVunYI7PSfLv1sCo4(UKmXyjzsERgYwHMBlyazcD4tk)DttgwMIbwaqDfvURnvzvwysldAyQzLgCcdjk5BGJC4Y(mNQ2uTr0Mo7iWd0p8A6E9jx5innBkrg(b3)HH)eugEGddL1BkPrZqzwD4XuL5h8sHtz4yXEuFtt62GBiXYTtaO3YK5llukmVBYx(FJf24zrs6T)2JqcUJW8jiXzAbNsbozCUY93ox5KKQu8pdj3yTfKrnNdMkjKdYdJOaATeZ6XRTqMjQzEgoZrMWLAPUKRBTeqlD4jvGzuGpoS7ZEVWtDWRdoDizcF21tEbFoD4ZBjhBCYj4lybLUZMzDCO80JY4uGyfQQBaMankRcuPNKjWbqRek63VcmlMc4m6athQId1cFkTcyhk8d1Al1Js4sL8UK63qp7Dt94eRWdUVf4fPKJpSiW1bFqab1H5talS1YYZPd1taFXiPwyPqfy4lTl4lJcSqZeWtdFv47zb)6q0f(TjGVo8CW3aol8mWrGV5ZapFc4BJgQVd8DHVLo8vsc)C4xGBEd4LGVp8dISO)q4hb)yD4NKaEz4Nc)m4CWlQd)s4xbVqcyz4Rb)MdapBD43Th43l5z4IwWFWcE1y6fEff4pQeZZN3cbuK7ETiUeUGsxC4Fwhrr4XGwWFrx6wLEx0hJKWLscVUfYdpy2twoWVy258NSdm1FBykpNr9fTXPqiczP)(5qOvcFVHf8MjG)MKuH)QECLl7vw8sm(SzUzlQUjeGUFV(MKWNnTBL0clA6zy2ME9ngRIO7EKKLeD2bYssqsscrlKPqYscyiQjbYTGSU6lIyljlKyENawsaejRyIQnG1MSEHiY65Jaa07VbScrU2yvm6HS4lQFLjlj(jrlKerEejlez3az1L0OeGq46vdPSEiRZ3RcNeUIjluna9)rGaIgiJ8Mj6wD62AduJWXIU7WtiiDPiPPyDgTw2doD9Pdojzg2es8cr0ru2KQeUfBhzfsF9knTMMmTa1nWhVkeVUeIqG4kOoj5LEKNAdw9arYiQ)NP0GURyLg0R1LkdIcsIOlvgjVG0ZvJmdIoXq0guAoFVknxOlLMlUbLMxzBvAIuzIDQr0GwRIpY0ZvyStp19n2CBoTvEInPhDMlfQZGo)iDMxpmLthPM3T5f2jaAJP0UCrIVGMgR4iTkwf47e1N25W6r9PZnCEhaoxtesA2rij2fVJAjrPOUA0rwpfv3cjNFtcjVsBHKlSbHKlUTcjVRvL7i)0j1wxYp3EBkBgcNZq)zxcqX1gP1Ag)Jx7rwOYOAZmzCITy(ns9PRexBBYTnqqp6kfcRZn9iY6kxohwS1SmB7Mr9ISL3hSlv6f6uQKex2rfS1tOD1iI1jH212sLq(P7KjrIzrP1clzsuz8tnMyUzpD2j3Cgon3Qb0EuYqSg5SyyQtvtiN2rn7kKzBtyvgcxyLUGfJABUwgBAnQJGyNohryT20o4Tr8TOMP1WBc8b7kMIZqICeIb7OixCgYRgvUEYqETTIjeKKja6OzfZgiO0BztDQdhvmQrC2I6M0AnL7tCgvYGNYF8SBSGPnlzTTxNB7kE6rV80owU21XBcq9POk2AJYDXBe05XWmJDE89n1wTt3IBZQtxRUf31KARUHKB(sCIPY(i1ltSxAX8DGNuDQ5(KBXf46OdDnSQk8aDLRQA1I8a5)mqr6Hc4K33ut1)FUC279AQqV979AQ2XcQSDnMTBLjerLy2nil5F0fg5mfozg7XSSVc1uLA()1P(Vp
```

**Comment by InfusOnWoW** [comment]
Does the aura work in a normal arean?

Looking at the code and what you describe that sounds like ARENA_OPPONENT_UPDATE does not fire. I don't have a char on WotLK to check skirmishes, so figuring out what happens will be somewhat slow.

**Comment by Kazimazi** [comment]
I'm gonna try it today.

**Comment by Kazimazi** [comment]
ARENA_OPPONENT_UPDATE fires at the start of a skirmish.

**Comment by InfusOnWoW** [comment]
I have built a special package that contains some debug output, please try this https://github.com/WeakAuras/WeakAuras2/suites/9455169241/artifacts/447444912. It should print some debug output whenever ARENA_OPPONENT_UPDATE fires

**Comment by InfusOnWoW** [comment]
@Kazimazi can you test that?

**Comment by Kazimazi** [comment]
I'm gonna take a look and @ you with the result.

**Comment by Kazimazi** [comment]
ARENA_OPPONENT_UPDATE indeed fires, but the weak aura doesn't trigger

**Comment by Kazimazi** [comment]
Output in the waiting room:
```
LoadAura Alert - Priest - Arena 1 table: 00000191A2E813E0 true
LoadAura Alert - Mage - Arena 1 table: 00000191A2EAB4D0 true
LoadAura Alert - Warlock - Arena 1 table: 00000191A2B290D0 true
LoadAura Alert - Druid - Arena 1 table: 00000191A2E58D60 true
LoadAura Alert - Pala - Arena 1 table: 00000191A2C14000 true
LoadAura Alert - Warrior - Arena 1 table: 00000191A2BEC150 true
LoadAura Alert - DK - Arena 1 table: 00000191A2B6FA60 true
LoadAura Alert - Rogue - Arena 1 table: 00000191A2BC0530 true
LoadAura Alert - Shaman - Arena 1 table: 00000191A2B97F00 true
```

**Comment by Kazimazi** [comment]
After doors open:
```
ScanUnit arena arena1
ScanUnit arena arena2
```

**Comment by InfusOnWoW** [comment]
Is that all output?

**Comment by Kazimazi** [comment]
yes, that's all I noticed

**Comment by InfusOnWoW** [comment]
Are you sure that's the full output? That seems unlikely.

**Comment by Kazimazi** [comment]
Gonna give it another roll.

**Comment by InfusOnWoW** [comment]
No response from reporter anymore.

**Comment by BannZay** [comment]
I noticed that Arena buff trigger does not work for me either on Wotlk classic. Should I use "debug" package linked above or there is a new one ?

**Comment by InfusOnWoW** [comment]
If you can provide the full output from that, yes I'd be interested.

**Comment by BannZay** [comment]
@InfusOnWoW  
LoadAura test 1 table: 000002430C6986E0 true
ScanUnit arena arena1
ScanUnit arena arena2

Aura used:
`!WA:2!DrvtUTTru4i4w0aUOiso1aPOlmsr7oBy42KIMffquvk2fYsoK01URKgsoKZetnZ0zgkz5DrR8ADe06Us3G6tabrrpa(i4tqFZqkhNQfcV)M37779dB0R1KwXTIV5BxrJ4mFEUmc)nprE1WKefw3qoVwynIfr4Yt5uMoSt3bbD9kJ48Sy(mM)mQap(2nQDJtXext6gVqlPPPyP6l)EzT4nnVlxHpbPJiJI45m9yJ(BL8CrLoXnNr1EijMHwp5JX16GvX4W8KKG5cS8O2EN07S(Rue(SozCgwn2vdo8q5s0H3PYdXtXmTpep9Q1J602pyKFqBVapR9WJWOmn5EO0DVcfP9f4SSJJjsWWa0e84fQklkhpgORCwAsSv8Rfn9jiGP7Eoxg)MDpfrzpuWtLyOGE(N2TFFX2pc(dbqJ0CzRFPeQXXPmU0wjYsWzvRXr0eGcDkoOs)eEm(VEY9qhhlzOSFh6JuoB(9xIXI2a(IGUKMYjlv4Se7KP4ZHEKcPbOQXKvaO8WPWBuVzNITlb1qu0LPqVMfFZZfT04R0JuwUCr9Cw8cRr7FjCjqGrQAbxg0Mx(G7x(DkXZEug6WZ4YFRrJgBDxL1nGYT9zbdfBBnIY1Civ0OZPXWKUnOEFvTOxHJTg)qz1Q2FuJOBT(FFUsttMdeuY1a5caJUdgoOBX2sGxMywzdmYcJTGFlRjbtlEwpj96DFxokgAmODdc(eUVPsLwBZGH65sKyX51cvaykvrdZWJR58JohenpEWGUEJChgem8eVJF7rbLpuAF614xuZOl(K6y8AxLhEwq)Jh09FltZ4Z6jX)zoMfn)0p7G9p8vvSZ4yT5VnzyHrX84YWCTMZgoflZqZxzm3hZs1KVYg)gMT0O05HoZTMlUnwiUgNeB1di0OlHBj1w2x4hHYWvI9PG5M2c4c9fSKesW0uI(dUzCuCVqnektVJ3K8mn1X1SEUtXfoErziLYi5QGwHryL0UtAGFXtfpFZNnmt0FLQqqtoMSeXOM9eo71EknsQ7DlgPW(APLDFrX2f7vgBwZHqgzo8Lkm8fNy1ctC2CVN7e4YSxXyB0fOIWIOI9ctOmQI8)nVMYQ2YH854nZUi6EnNpPH0CtcNqVUyKtb2XfEU2zLMhnT6E8Pt)7xsJD1yL27JlFRtKWXnGxyFBR7RM)9mMmql0VJx3UdomNgV(63FUq9t8Jot8UqGaj0uhjLzYnMiAbdQo19h4RbW5oEShktqqBTYWwQfzol20dhxchyqLgkQC0sjA(Q9pC)d27WFCV04Oee6N)Hwt)Nl(Vd`

**Comment by BannZay** [comment]
But I found out how to "fix" this. If I open WA auras frame then the aura become working.
If I do this I get following logs:
RecheckActive unit:arena1 exists:true
RecheckActive unit:arena2 exists:true

**Comment by BannZay** [comment]
Please let me know if you need any additional information. Also we might arrange a call so I could share my screen to help with investigation, find me in discord on WeakAuras Community server in this case.

**Comment by BannZay** [comment]
btw, ARENA_OPPONENT_UPDATE actually fires (the game was against 2x rogues)
![image](https://user-images.githubusercontent.com/17499770/214758087-40db87db-4364-473c-a4dc-e488e6b8c012.png)

man, the problem is here tho:
https://github.com/WeakAuras/WeakAuras2/blob/e27af6a4d5b5369a710f0ec55c685515d45acb81/WeakAuras/BuffTrigger2.lua#L1970

**Comment by InfusOnWoW** [comment]
thanks, that looks indeed like the cause of the issues.
