### ISSUE TITLE
Anchor breaks when anchoring a weakaura to another weakaura after /reload

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#3905]
### Description

When i anchor a weakaura to another weakaura the anchor will sometimes be broken when i login and will always be broken after a /reload. 
Opening weakauras options will always fix the anchors.
I tried anchoring a simple aura to other frames (ElvUI and Blizzard UI) and anchors never break.

### WeakAuras Version

dragonflight-beta-6

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No Lua Errors

### Reproduction Steps

1. Import the example weakaura 
2. /reload your UI
3. Anchor is broken
4. open /wa to fix anchors
5. repeat if you want, result will be the same

### Last Good Version

4.1.5 (I haven't tested other dragonflight beta builds yet)

### Export String

!WA:2!fJv2ZTT117qt74e2KAzfhfx5SqRFoYs2w2AXsXXXnPKuuwkLsI)aPSZAjabUKawGaWxaOf32PZO46XPRtvFlZKx40(wtxys3sxJI7(IprjnPBPPrt62RE6Fa9CUaCrACSD90zIEGa4UCUlFFNVZ5OiNODxNBtJRu22QKPrzDV(kY8u6BK2R0Uw7AN)UxTOI6SACBNu2M28hoA0OzJ2)bh2PDvBlpUTPjtlLUHPgNzTVvh1VsLfJ3x8K(Lk5EjXV4xhNzX4kMRv0MRX4jdTNtBjnnoZzu4AXZBBB6z4SQIVNUnFAhpdBl3yfdgVE1GNP1kZC2EUt7RWzXhZ30m(j1n8y1uSuXjL12WYRyQ0tLpTu4eYzCg2wQ6zRohJ7IwCNrox1AbDfCwIejs0lHtJXTumprWGCLCvvmzr5kQIDXisUEkCVyjnSm8IvSe(Wvp2sECJYLXz0z38Wxpxvnwr8aNFrhgF80zYo2mzs6HFiP4ZvgCjxhMP5eAUXwZ1ViBoMLxoC0gluRqQe5Yxix(es5t6JlsrhtLfz8gdllNHdtkx20zYijAP44mftpDjlLkm3yl7BfUfIXxCA8gN5fzLGJzWx3CvoRmEwODMuzUTVZYkwgvuOZ3iWogd2vslBl2kmfxwopehl7PV1v1WDnnIc0zG7Yq4wZDjAmKDG(swrXWcNl0hCWTchc6hgaFTJn2sxgARKEbLkoMS4jqtwZWQKnpyXJvRehpc4AQ4Pe9sba5yut0sumxkP0PNIVq4zke6MWc)i6YUmZscmhU1Q4nLK4e6gBqFdTAJ()FQ5r8QFNSMvPTTraFkPPTI2yjDrArhsv8rgxSKiQO2bKiMKQPIRl9wrpe(T8eVItUKr5yTREMZpsvxhf(SN0qZt)9TI49G91JebUPyvv9D9SRKNTG3crFJs(wcYtp9glo(NrP4tyLYUsrfVm2i33EESN4E6mR4CMNp3koZstmsXpM2ibmEaKf)dgNypfywZDWGwAzifv4y)bnFq8Jw66uyhdSrtgC)2Ckb75CmvFolHOV6BxlBV6JM2MIMP)AyHuCMIhtav90L4rxhiULHz4pDfy0aOKHypo4U6THzExxF642CJCzUvmzL8oq8I2E4epq85jW4aX1zKSvJZ1rpoZlh5dRjXu9cXGaZE0uMmfEcttbZXD99LJ5jAUNUsoD(8tpzM0JLV(PA9n16U4DXe5NoR0ehF8RGbIV)67)adHFhCq6T5HoT5CZmwHSc9Gl)EFDJO5YxFTd2x4YhUW9ny)0phzDtM5DfTn291IHha)z47V1zMxHx(kB7Wr008HwRH1RVCcRV(TDWClKsX1lPc)QVkng51WQniUAJ0FGncCrJHKrONm3iClWTUQW7xY2tiIfXz7R77jT1yjtmt(PtAGYh6WDmv3WoF9Q(UScKyZeA6OczCN2Pguk6AZfQ50SKH7gUN1A2EqB7XzhZGrfINsxHIjX4gUEgQUqxW)xXadgdURyqCy3lrtLIGidDhd(aqNWEJvtZW9uc5O5ydQyTOZ2veVNpiIbTerRsB0cQ1dVhf2UlCu4wHdeeCy9c8dE1L8xc1IAKSqumSORIhfmHP3QU5JgbEG91bSRvr1BkfdkWKLwydyicwqdfdCkU9I4mrzzyi4HMd(qK68Acj7ckwAfcvXp)o)3Bt(DAt(cBtEZTjF22K)cYVQ8oAtEh7r(12MC(9iFH2KpCBYVI8tj)oBtE02K)8YFr5lkNVn5xRn5xyBYFPTjdJsMgs2DrxdRYyEaqIoLHuDdYfhFgk3cS3LP7zlmsmxNFgmWjguFtRjozjXihA0D6GjgDuN2WXLq7uOkhtJPnPYc6WrIGiRpxLv0OIJn3tC1Nt0YDEdxQ51qZ8tcc7086Cn3k22E6z52L5mxx9nUkgiLBFCkObIcq6y1SX9jkpOAA4iVSaPDn0yscUomcCFWWBPMyngxCrVFUhgedvK5hEk7zrb8KNX2UsKaKlFqxo9mbL0ujfv2tqEv4nf6y9eZmrFn)QVCIlemJoBzyBuQxyMaWMdxkdnnMvsutCCjfthDLOscTqVDij6xhowT5NUFJjgEUEh4etXnSOu4y6lfEyC7KUBe5HwZMBG8cHRx1XNwAIhB6PYNid8GXGd3DnKhPYst5m5k7StJYwiVkm9srRP5CBURmCBivpgC7DVSMDHGWs6fdE2vSyqhDufBhZ1YvPmt)8JKebP5HtdrFmN7bDKSMf1WIpMjZvhPOykk71n(Ky8rDB7zD29vzaXh8QpKHU6d5Wx9HmmCJWwHpcm0YICaNaPc7Ct32xgv0on0MGRfWLcsNMXjvh9WBMoWlNyWD0jkLDoHYYUG7KuDqbls5H0B2dCVKMeP5Gsj(vSqcGklqmjjP0IincaWTsYuzmQGYuvlHzXNYGRAYKxIxxpfEGyf5kAg(UN9wwwHRMrKq6z7aEOscppHBFspUpl0zvDtchu(jtiLz6uFyH)ROdHmbXOuzBf2uJsxG7pcpibyuE9MIbThfkd6WnRdX4depRXcmtyFROTiMETHQ4UcE)BrYK2Y9cdhnjQn7b9Dj6X4lwKBOLxPOjRd4P1r11M5WMviyPVgEpJLqy5ngQ8IQ6sjgDIzYTuzAEywUDjnk07Urh1MojBXPTwmJ4hN74KmLzP8NDp66QXAzYobjLcJulx6mPtLFmPetMgoYUrNO(1xy8ZOpY8zpvEONiHk6KmDOIDOI(gAPJn2ccoZhcNc)k4PKHZkZXJffejY53pyCN3aDvIRbfGufRNJsZn38gomzN2AMD8moA41ErFXJvQpoQ0UwPADdNJ87(Ky0Zphs5o)DTmjOjk3PtPHgCO7VFkm5XjObJBH1)OdzL5(wIQJGfGU70z7z8TW8JtJYSZZ4vW2D2E9yWgLmufbk1Rrn5fu9PUZTh(2jum9zfSXYEuqeR9heYjVkYwu1zU50TNFARvCfpsicLUcT3ev3zO52zXbgz4HhAaYROkvoyWeGx0PTqJ3WU1eMSN9EVU7TxYF6s0EjOgYuefxNAalDs1lxqPJ6KN3kLy4SclywN8644WMcVAccfuO1ZGUWb9UITu9I5AFaN2BDat5xPiJhf5OvkAyXMm4qwLoEzW7nxpYLELwNXMqhCipmJt7HGAqIezSlBO6S)gv(ewrARPqfpSThFGNuKn1j(k3akoCPzzmNeeQ4jrBrDrQhpQopSO9ObzjapEjyxltPkikcC1GhfSfPsenSC3WCyiPSW)xdfMZW1aDoLdlESadzAWZw)lQuWOWtob8qNVDu9u4RluokQlKuGNbs0b8mYjXmVyuhcmYWJvHDAFKAJqIqJzvrgbigGLfzwrNhuc5Guxl3O5bvC1AKEbilYSOQMrjKmI1IUi1rsUTPyDOyR09i9(sQyupluabN0wX9ZwLx2zoNMvPwRL9ZoJ8C1i9qupBnknXzxC0qKhZkaMSHRl6gl1scFhjcQvKxQ)0pQ)CzD0ga(OrHp2eICutf6IIz1ircMo7OUtl5opQHlP9H3dl0su(NEqFUPZU098CCp6Ho08kLTpOH9Hs(W33PLkLA877qdGYOICp8ZU5(p4ahMK)(e6ySPTatktPSs)lqOauBAP6RMClPJsItnfV2qlDSXwcvNiJhipbpNm8vHVg811XvRUcd886W3OtOg8tAFa4L0rxE4BPdFBDyfDreUSYWpe(rOYc8nfba)EDcFFruWFSo8cOKZpaEr47GsfuyWxwhUqDxp47ID8tJc)m4Nlcp(lQ7ab)s4xf6da)A9RBPz0vb(nT4KCXOWRgfaHta8kYWQWZID8Bdj5WRD5O3WVt06RhYMH3qh(9Ix(dWFCJmw4pvpM7BkE5VkOCVL49)sdgk8NfnqHvXOceZ7Fjd)ZnbR1GVHiEDWxKeAu4VTEs0NcEh5aEOqrati0rDUPpv)PheJLHKL3wh(7W)O14rnYIRr0JoIDLa)Rq8gcXq4N4ce4sa3ZlydehGawbvb5ievGGEbVaXDKnGKhIiSIqCUjpbzeHSbKkrSbIv9UXgc0axhWIOkHJRhzVy0)xdSba3BUr88TAbSd0xUU9h3OquDsbsuowT58ZDKEugYAXS(elbbFKcuNO0k94tt0JqveK5eiGqecKxGenKUnPCi4hA)RKZpc3cenROgCc6faAt3)wzceEt8Ga4waWenOU3Fiy)snWBK5q4nYw(VaUjS(IB0r(vJ(ENF81TavtV)3wOgGqfcyHo9xoO9ZiWXaxFeKpwTHgtzo1ELoDpoMekJ8cYF(AZZ)Aa8r8bXFcPQJWiuDHaV46ypH3iRGGEIGek8)sIuYQ7Q)YcfcbFarEKkjOue0litxzL)Rd)O3Bu(V2ficv(B1vNi6e2DSAtM5Xso(uh2EYrFecKdC03qiGplXyUSzkGuaIJe4OFz0XBFUn)X)pd

**Comment by Nokramx** [comment]
The issue seems to be related to anchoring groups to a weakaura only. Anchoring a single aura to another aura won't break the anchor.

**Comment by InfusOnWoW** [comment]
This is fixed for the next release.
