### ISSUE TITLE
Auras with Talent loading Conditions are not loaded anymore after swapping Specs back-to-back

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#3906]
### Description

When i use the Talent Load condition to load a spell for e.g destruction warlock, then swapping to a different spec and swapping back to destruction again, makes it so the aura isn't loaded anymore. 

This is just an example, it happened for all talent loads on different classes i tried out.

When i do a /reload, the aura is loaded again.

### WeakAuras Version

dragonflight-beta-6

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No Lua Errors

### Reproduction Steps

1. The aura contains examples for destruction warlock and survival hunter, so if you don't want to change the aura, login on a  warlock or a hunter
2. import the example aura
3. select the talents on the tree, so the auras are loaded
4. swap to a different spec 
5. swap back to the the spec which should make the auras load
6. auras are not laoded, /reload to fix 

### Export String

!WA:2!TI1)3XrvvCtx4u6cwAcLqOwKHcN0eOuAIyXY50ZXSB2LejKMoBAl0FjZBM5T77zMDMPVzMKU93Aoig9iQSkkApkYkk(fu0fuuerPkE0Jw9s0)cYV5V2J)b499Mz3mZMukf9xYmZ7l379D)85Z9D303jhiW)wSfKAEUvD41yH3VjnKC)hEG6dypG9QJ1KiSMH6wlK9KdUUPNWMkkqSw0w457VRco8ZDoIWwBEppNqUV4ShRA1aAyFnRj8I8N2YZ18WJF4dDOhQnX1I5jMZJ7gAwS0SZxsVv1ihNICHLd1yfH3Yv8jw0CcIvi3Zn4W6bHeryEZQCxEalFb8ry(vcf8A1OIG9mSi51NQLn1mQA15B4tftvAM5kFIzkeIFOtIeKXxjWN64mTDq(1dImPlrDdRGRMF22luCIkZVqL5NqF(crOXn9DinOIUlBobfxMEL5knZm6QrmNIsCcz6UK60G8nJCtcH8TT8CIQ7gFcUmEePcxIZjX4uEuAgqDQQo5Wo0jys2f2HapDYT2xl0D60AY1LVGJhX(KMHeh0zdQxpcZP5fNZZLIX)20TCibbdcJMVaEMSIFHFoQ8frJ4e)tEtRzMGof9C8eFQC5YnxUdDWp(krb0z415HmZaViHf1Kx33teQhiJ5TRhyHonhcdHez6VpZyOM1k(zj7Au)(RCMiIGQvgXnTtX4H0wcvKlt9x0UbMw4wkGpzxvWO76leGUPGlEiAhpACG1xF9LlzGPDXipxtIlVUY5hg(WLViLeqRekumVTd7go6A2iCkNEbj4kcOi5Yoyf56K(hoAH6eUBzyc1QHcqrys85o7DetCFv51YVo(ebb3WYiJZtyQpXKtFIkTRkqWfDmjKK7IXXxCQDhRutWTLUAF6t2k0ZAPy4DO(EQw7JBFXsNLu33HQnbgMMcInpk4jVPMY9CkUDi7gVCScOS0(sRywPOEPsZEzz6zQgMsBtmDOREq)bNOkkfvYGhwRONqe5lFN5FhPNysIyrTkEropS2JXdOIgm)BFsAqOikzbZ6PvepfwoncQZ81sVx52009c1gzwPKxRmHokZF)zmp1sbhU10kGABCLulHe5SXvEBzmg3N55QndVkL5FRzcHPRx3ZHeIJp6MCFre(I4HApGwrbL6lD0KusiJL98xqc1IfXPz(39K06EUyquRbAelKhl318iPMQnYJ2qWjUyWDxP3(eyDTgAJO754ixR6ZrvzQnS0Su0acT5qGG4GzQmEzlZu7nZPSseEmD1M2TQs2Z8pqpjbFQRT07s4aNWZxgVNe14Sgc0A7zlc4kCjzAu26PNB(hetozDTm8kZfyg((sh2xvFougZuuw8NutOGQ9M58hF2oj3blgIMSxswAOebOmO8vcG2DAhuM6eGYpKH(rZgsmIRl1jgmQQoH7nJ1JdmPkOMdro9TLnWyeBVLnJeUQz6brrboFrCp7p9mV3uEL19Ea5gYYkVV0H1vnXNHDvatRX5PAu0N1nrZ2daOENBP1PwOkpTX0fjyT4jfuInwlZzr1(hjtI498uDpzZzxjellPlvvLHshlZ5TmkJIlhW87pDAzkcEzjZFGm2zkYsEw9CEEebVUhI2kIrn86gKXDxBMXTjf5DTfK2oPU5BiisVFGTUUQ2itG3j6efstn4OQQnPtJBuUDA59gMChEydvbVuGLeiWBPzSXJ42TREQcpoE)YubNSOUJ8Y3BSaE94YTM6y6tF6Jn78tmZAKOq8sHJP8zq(wY704XV3M7wf1fQR8gUn(QfTKSjKad)HWwi8e0KDPgTKq4jcmeXxIszdyD6v3FloAVkQR737hcU((Gd2hCdWowZc7wdfhUvwM7tn83LvekbRpp9SHNW3g3TzK6Xf7So5T)ScsJza7ANdd9VA)(9JnuSqnQlvWTQW8w(yUgRL5Zwb4JjCwM0iaUZ8nvTHnlE33qBt)aWU1vFlICvnwvatdETKwmi2uWD4F7ft8U2CcVAcAqawvuUPrHbGBznmt7uPJnB2LsUMYiDg3agmpC7WEGpcSx42GHAkNfVB3ArJv60oXaJbAdBg731JF0XZWxb(Q(9lBiDj68XT69yE20CW(cU8I4Dwti7dluxAgg8jLTTOAYq2Sb2ZHS7JsBAKD27iy7RbKWivTxy47Dqy3RHTek7It2kLRDvy3nLdOAfjPJPfK991P9KfS62qvsd6lSepGJ9sy0z5ueafJPnh)SuN1sgZt1vtotgvkJooS)vVvP2x2(MSJs4(WKc(TdvCQj0N5yfFuCqfef3EktLlvTKAuaZOQ2qxjj7Bza3V8BfAi7wwIw1zI4ToUCQMDhECsGnmco2GFgd4addVY2LU)E3wlBo2NUf2eCdvVUyrlAxJ6tdnjHHouMOA8VyO7ulrzC83uCcoRP)s(jntJtUUkyxG4ARcr0rV2UqN(A7YWFGUNLUtBaJbJdhbEMv6OcmGBcH48WoZd38WnT9wiw2WmJFUV851T60ZDo4PYdLZRmCh2esDqQc1OW588Qp31DOdo2dcpNbmtsdK(3Q9g1B0wMiC8SwuBmyo444pAWNrYPVSSrYJdtNdoF7p9YSrp05CoEWiJJWMSxuujV7oXQulpjpq2qPnB9GqU1InMmHWZGp7Egw3IrTwSm0FUvwIGv5Xf2YRlXxFjIten3(8833rpQWcVkUgf)jxW7ASIpEJgve2aEry1HHpNb85nG7g2XQ7h(cPRXapTb8fHVe8LzjzTBEy4Im4pGzjzcmPkc88O6dfzknkQQrzXxtQtHVbwba(MWZEdd9UWfA2Tlh4BPu03zELG(Rdph8TnGMgOag(oWlOSulP6e(UD0JDA8Fd9ypJSZnnYlMidHVhk9GVp8s5GFGsDb)qd4hb)y4LZb)eLEb(Pjkf4vGFM8TFodABaVQA0xlrda)cg8lvV86WVkMN)0z45WVwn7BQ(7BP(7VLb)gg87srrHFVb8gQ5sOLsc2BBaxIjZ(WZyGucNdF6stVC1NOy9NaEhd4p9(LJnUKJjzv)LJd)5CiTf(RgWFtrtG)UKIa)daI5cW7MdwtreG)zAgWFur6VQKGDMHh0ljqIPDibsSnHei5gx4Y90KDct4zVNYs8xszqMaYlUYmHR9kZzycil4L7Liizh)VXeEHumHy4nMmGODg0pMCGCcKzetrqEthMac(DbcKpOQ8ibY33eGpMe5rgtcn48TpcZV0S0PgZ50lj5cXO7MOeiziHvKIs82xTYbpt3EiKixV4EAX)qx3D86iYx2H4k70oPP9eKxYkq8oPgWZRUfFZqVuBCPuOicHsqllm(s9ONXKFm89gxb4tcn)NBobAu44(3kfDxTCx0tI7BWrE1m65KKmM)(ax5crEKYE(2N5iwr0hX9m1)epUeprClnfO)GiXsCScVgls(FQk(ogjHjMfeR)7qEUgkcSff6VM4biCUfYFj74cIPicFpp3oY(H22)(skqpr5lzd)Fv6FPR1lb(aqAgnfP5vtj(3GHi5lVvhYZB2HoLs6VvLv7IhixiHujLbiS(ogxvUW4ssaYzsyeNV9O6N9ih)HE0ANXmuslqk2wYmUc1cgyP)1J)Fp

**Comment by mrbuds** [comment]
It should not be an issue anymore

**Comment by Nokramx** [comment]
can confirm
