### ISSUE TITLE
(Beta) C_Timer.NewTicker is nil

### ISSUE THREAD

**Issue by nikkisaurus** [WeakAuras/WeakAuras2#3907]
### Description

Using [Darian's Dragonriding UI](https://wago.io/dmui-dragonriding) WA, I get a Lua error indicating that C_Timer.NewTicker doesn't exist. I don't know if this is an issue with the addon or with this particular WA, but when I revert to the previous addon version, this issue is non-existent.

### WeakAuras Version

dragonflight-beta-6

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: Lua error in aura 'Dragonriding UI Speed': Trigger 1
WeakAuras Version: dragonflight-beta-6
Aura Version: 2.3.5
[string "return function() ---- Parameters ----..."]:69: attempt to call field 'NewTicker' (a nil value)
Time: Tue Oct 25 03:10:56 2022
Count: 3
Stack: Lua error in aura 'Dragonriding UI Speed': Trigger 1
WeakAuras Version: dragonflight-beta-6
Aura Version: 2.3.5
[string "return function() ---- Parameters ----..."]:69: attempt to call field 'NewTicker' (a nil value)
[string "return function() ---- Parameters ----
for k, v in pairs(C_Timer) do print(k, v) end

local mountEvents = {
    ["PLAYER_MOUNT_DISPLAY_CHANGED"] = true,
    ["MOUNT_JOURNAL_USABILITY_CHANGED"] = true,
    ["LEARNED_SPELL_IN_TAB"] = true,
}

local ascentSpell = 372610
local thrillBuff = 377234
local thrillSpeed = 60
local maxSamples = 5
local ascentDuration = 3.5
local ascentBoostMax = 35
local pollRate = 1 / 10
local updatePeriod = 1 / 10
local showAngle = aura_env.config.angleshow
local showSpeed = aura_env.config.speedshow
local forceAngle = aura_env.config.forceangle

local speedTextTypeAir = aura_env.config.speedtype == 1
local speedTextFormat, speedTextFactor = "", 1
if aura_env.config.speedunits == 1 then
    speedTextFormat = aura_env.config.speedshowunits and "%.1fyd/s" or "%.1f"
else
    speedTextFormat = aura_env.config.speedshowunits and "%.0f%%" or "%.0f"
    speedTextFactor = 100 / 7
end

---- Variables ----

local active = false
local updateHandle = nil
local ascentStart = 0
local lastX, lastY, lastT = 0, 0, 0
local samples = 0
local skipped = false
local angle = 0
local smoothSpeed, smoothGSpeed, lastSpeed = 0, 0, 0

---- Localized functions ----

local ScanEvents = WeakAuras.ScanEvents
local GetTime = GetTime
local After = C_Timer.After
local GetBestMapForUnit = C_Map.GetBestMapForUnit
local GetPlayerMapPosition = C_Map.GetPlayerMapPosition
local GetMapWorldSize = C_Map.GetMapWorldSize

---- Trigger 1 ----

-- Events:
--   PLAYER_MOUNT_DISPLAY_CHANGED
--   MOUNT_JOURNAL_USABILITY_CHANGED
--   LEARNED_SPELL_IN_TAB
--   UNIT_SPELLCAST_SUCCEEDED:player
--   DMUI_DRAGONRIDING_UPDATE
--   VEHICLE_ANGLE_UPDATE

local function setActive(allstates, state)
    active = state
    After(0, function()
            ScanEvents("DMUI_DRAGONRIDING_SHOW", state)
    end)
    
    if active then
        if not updateHandle then
            updateHandle = C_Timer.NewTicker(pollRate, function()
                    if active then
                        ScanEvents("DMUI_DRAGONRIDING_UPDATE", true)
                    end
            end)
        end
        
        if not allstates[""] then
            allstates[""] = {
                show = true,
                changed = true,
                progressType = "static",
                value = 0,
                accel = 0,
                total = 100,
                boosting = false,
                thrill = false,
                speedtext = "",
                angle = "",
            }
            return true
        end
    else
        if updateHandle then
            updateHandle:Cancel()
            updateHandle = nil
        end
        
        if allstates[""] then
            allstates[""].show = false
            allstates[""].changed = true
            return true
        end
    end
end

aura_env.trigger1 = function(allstates, event, _, newAngle, spellId)
    
    if event ~= "DMUI_DRAGONRIDING_UDPATE" then
        
        -- Detect dragonriding pitch
        if event == "VEHICLE_ANGLE_UPDATE" and newAngle then
            angle = newAngle
            return false
        end
        
        -- Ensure ticker is stopped on opening WA options
        if event == "OPTIONS" then
            return setActive(allstates, false)
        end
        
        -- Detect dragonriding start/end
        if mountEvents[event] then
            if IsMounted() then
                for _, mountId in ipairs(C_MountJournal.GetCollectedDragonridingMounts()) do
                    if select(4, C_Mou

### Reproduction Steps

1. Mount a dragon riding mount.

### Last Good Version

dragonflight-beta-5

### Screenshots

[With error -beta-6](https://github.com/nikkisaurus/images/blob/master/WoWScrnShot_102522_031545.jpg)
[Without error -beta-5](https://github.com/nikkisaurus/images/blob/master/WoWScrnShot_102522_031850.jpg)

### Export String

!WA:2!fZ3c4TXX15Y1WQUgs2rIYI2MXjEfSLcGeeeFiQx2YSeeGKqLIKbeKs2oUalWUGyTwGD9Ul4dL62gwxx17nnpytAtZR2YMV2MMMhF8RTxFF1Kp108OpsNW26ls8TnXY3K48W5HsA89M2B59CMz2f7cSqsoX3g(rcS784mNzMZCo)NzodfMVBlJDlBkTGETYAQluX(qfvSLo0r7UA3YDlFX71O7s61Sn110uKhTIQMSPsTtB0tkAnmvLvRTG4CzeZPwvX0YypTM(SgkkYTN8mQ2LQ0EYZRUGU5LlQBkRyMuQ05Ln1nm2zsn1lCbjtzXC66A2QgfxcQvMuRzFoRJCif1JzVPuD7k6MtByRQxZkS5ktxUSLI9KBFdPALGmMrxTMDXrtpvU0z3Gr9r110npTGGqObQBQzCVvSTnSo5Hpms6eQ6hwUAD1dj7H9o8aNWuQeTboAwlBjt7WjvRPAhUyz4lRkHx12uDHfGbHE3Vj)XNCDzLI1lxo3kgkMtKEYzgBUjtAdVKvQUP0aRAzOOPLr2k8LTQxuzrLA2ZcLwD5nYp6iZMl)S5gjBo3SMXubYk7SZKEYjZwtQQIv4S0mkoHIKMDLK1bUPOHM0kkMRvVgNfcFfORRywtsBEG1qUFnPAQvLWoYrj7EmsVjRPxt5skswkZAdZTlyx5M2ugypSe5rM10sbebKTwfld2viXswvsTguxsmYbUjYbjXjhcECpTMsszfRs3G5ISw((wh6kzvwGohLutxsESI2sAqpONSvRdtSHtcdiL6HCKWzlPjzzHpL0s9ck4dBwKlpWM5cfk0mH6lXqfT0RBwsPOAvdDt7SwLacgQiBoUY6SVtlVGIXUM9XQlzQiowDnnXZwr1wzDtkVG9OSlyQx3Gx8zHwCBxI9mtq6MlAPuf6fzhiXGjo6626L4DP7q4jxpIQ8vAroEJYMW8dmCkzlf6kmzWXWKW2Q4SJMnD6PgOUQ8gr10oFMhB8LprSfwZsrRmvqLCRCz0m1G2ouryWVS6cHxhNeuzs4BOwRSUjBwSNnGhlPKgffSkyUmJLf6U0JEXJTMKzPjPZPprpKB4aTVSnRYsQ1KnE1TMomazQHppBDZfui3e5NKCZKWKScKD8V2f5wkMC6C5M(mRxggmhv1SKMsHvn1xAwdPskHi7KSls3GWvyYTfMSNWKE6D)KB)jj3b5ob5Jxj5UctEvKxn5UjIK9gMeHCpK7LSpY(dVrjDT6vRXisrtjz16wpXoirzIP(f1sCTf(YkbQZQrUvGXSPducK(Ups)HnHfV4kdHvRBPmPAvv7kKbgJmikKrgI(5rPFEm6NVglYXDL2UIfiKnXkfHbQCsf1u2pjxfYCvmzlPuQq2EyY9fIC6no2KzM4HEOjMup2ri3FfJD6rgG(HXDFwfPZpcSmZ6KbQeKm8LKxbwLRwIkAsgzBjX2g6HNje5uKhyTfGkCwvz7kBpRg2j2(Lb5dORvZEmqnLUzXSJKkZCZsob5KKK3mzusksAU4kjusGOlLm10NDkY4HitqYu0awBaIEJrMk8QiPrj1iztrEfuDKzTWjfbY0HjZ0d51wGm5a5MEMlo)6q6MNNYg7zDvGbMLUA8U6chi2Ha5wwNjOmz6XYTjTSzDNm8iLS)ILQBzRx1y)OEX8k1wmXI4GG4Pe7lSBsLQibYIyARjRNNvJcG8fTHZxYrTqORCEffJrqvj2zX2c4wtGBrEy1IsCn)tm8ZV8Y)2D11oNy4NB37(U3ARFWedFP1w73ARTUsiqRTLKnQcuPsYYG1pJDoMP6feFT1LKXL0I5YDjANHTu7bfid87TbimL)cGMuqDEbUWevm6Yyguf9NVM(s1QWfROcAM8kyeT)tCSJhxCG(gya6Nds)8i0phc(S)(PPFIbxdPwnqTpOCRjrVJT9Hx1yNGkTQO(ALhRUQHHIC4nTQijRV05ySzOlBvvx3UYmM6lyQyzbsLaXgr(rHbsfzf5ZOcm3WM4WnmkTHo0gGTKsAQgfmTvwggpuYoRUMQmRVNJLKr0mO9LYG4XRBujlBqgoPK5RBUmhQ5BhAw6mpTAvysHWItJksHyYpUA0dToyHtHjw)e7aK7TbDqGs45YnzMPs7Dm)CcO(OSnN03qI3rGUr2(sm4jgI37FqwfURU2SeGEasO2SlPAOuWyNmjiSFmNHmmxtICzahHoQvTeLfsoc8kPNpeO96I7MopkbMBmlEgDzLcxMv9Pzdt9BCSY1RrHhenwyr4htfy4PMyeq58sa2LiXfBrqooiBRutEtKUg6lPyIZDfC0sA0DZ2dTVtBZnyTj1QCryTUDDlun6LqktLguLT6T4GhBOHo(qKixzenQLFBfXzq6JQzrDE5rGcfqDWmGfwghyUzsnsU05Nlt(ZMj14PZfxCUPYKl)mtF20zZZY8KmKfG27SLQOu68GI79g(ka5sVmOVzwgsMcxHXHZlzQI6hTmU9xpmASOKwDCHBKA1RwuXms4hpmOVhgw)ezbBKLo)QotnKEZs7hg7c5ZfuGjF1sZwrFPPRvGeX4ohLxorhHyXO0woMXUXkOGScBX2uGs2cBAcJCZ686DSTN6ZSP7QrAbWr7n91mx2I(LtdHJz01Cu(SWAwEjgRp8KuZx9sSjVFW(6zGXWuzhz8PNkBMuzMA88ZoX0NL87sEFKpajIZ8xfvzLS2aIzzITrExbN8XfXwNj)OwM(I4p3PeRPQjAxrPwtjiAoNIvaqgYRaNVYGcyujQ93dX(g2qw16rPn2Ikqd3nFbadO4K6lOwYiHlZyhZHIrTF4(FerqBS9dpWJetuQMm80Gpc2Wg7sIsnonqH0)OUmELq7Gsl4sR8mCk5n4pq(VdwunoyGLahrYZT6L3Ucm)wbMfw5hAeaCBvAKqBW0f0e0FYlORxDMBSVe9FKv5A6S6fmk8jV9BxSRUE7tm8LhyGFQU6keyM4PEQVWwB9v8OGrA5KauGHOOjoDpKE3eG1c9bf0qDnzEciAvwclYrZLhrYENBYFHbiyaqtRtk6mOMCGNESNX9hk)IQwQWAQko0tbH1EBUohLsvstFbXXHHmsVRHSaTyxSxJ9IQVZB3(yTHPsjvehBO1ClsK9zyi2PkuvxopAwSWLPz6czn5iZLBAJDtt0VouY75km64Qy)nyCVDI8AklivAL8L101nRCjAbWXC1YRqU11PW4uqjMKtn9uPn2jJf8pXkSjBGLBZtG0RjmsGL04v3PwL9MW60SAoSVgVOGdwtBTKKMSr3EArEdSnEISwLBR5CHgiXqm23zoBt6BlbZiN1uYy1ZYFyt32G6x1BJ3P841k5w30hTf8Xf8eJ3vtcHEVeZiwN6STT8sW4odOSolwlwrb3tGDTQdRt(6Kj2y20tME0CJLDKZK(YuJYjbV4KXv)dmsQuTIRqA5kR6Wz3jIhLABZrdluRSOeLX(7SobFYfBqBXjuLLvQLDQ0ZdU07PMRr3zHtkUpdsrsjkS3PcFjh7lONGfwJIx0c1bNnZ4tKlj(EfJ7PZTFZ1j8gNoOCkq7xty9Zqbqx4koAt44J6L8gne7mL5YEMCX8KiivWlleKEoJD5dXmo8s(CaE9SlHlJsT9R0uhJR8)ed)fE(3hO4kHrKo3OURInvRHoYQuX42CgHWINs1cnElxydDtvOtrB(1Ny6SzEOPNk3itsMgCO7dCuYThA1f5g6tIwBYsTZlyc4BQTGIvV7VHWEkSQb4ZocUPHWRG8rka(gn2ah3ELJ3)0AgLV48eJ9qESM(lSbZFb68cXYVtcGf26Kfre)KLORqjldq7xfG2Zk(fa93pZZ8mBT1wpD7O7drE9vi)SKhN8ZHO1j)8(WOt(f8blN8giRs(fRqEcexn5xkm5jdr(LRqUiapM8Rq(puG8FK8gj)QK3e5nZrZsElHiVvglTg4X6Vg5TrE7uaQKFDwQ)gK3b53e6LVZcK3faC6DtEpKEEViSYEiFyYhXKVpqfh8O9p0XpczJcK)tKNIcRaTDJok3luR1Py2i)bfw1z7zImyFaQOBJIWreXBdURxQKcUQJ8hxG8NGGu2WfXdapd99(9wG8FHIE5pTa5)Cb0fCkmMfzqyi)xDaRqBFBYFgd)qyYhDajnnYhRtqegGdryqxichHcrGCP)OUi)5uZ(Kp(lh2Yj)ful4KpbZ8n5tE1TBt(uKpTRPAYFj(XF1IK)67K83q(mK)2BMqyZqF2kKnj)DqM)9xSxY)qiYtd2bj)pkqAal5(8W01Z8gi)pRq(hj3k5FI8fiFrQTgYZc2xixM8CcK)xmQ8LiFzYxzBKNNAbG8vRq(AG(YVbio8cqf)McKVv8UiF7yKVJa5kWiY3DxKVhQpL8pt((KxK8)Uc5)dv)i5huG8VuH8Vs()s(3iB5rpwdHUk0qqOHWn0qiuLgc3yOgcB7une(jGuVjqttdHFsiZBUHqyUoK5AiSDQoJgc7i12BiCl(0r0q4wHk(kacTt47D1qOB0bF6A0zkgBXL6R6JMk3kx8moRrZkq(ud0FF9r2XUi3crV91Nl)Q21HGFebDHGgrW5dlr89WH10ljPjwfuvzZ2Nka86RNIA9HJmZKJ8GGxgNz65Mkx(uzMfFp)OtmYuJNovKhbkOTzDL48cZk1PNEUStnYK5NB2rsMzYm56C5Nm9iGnIu5P7AA(mtLp3ij9uOh3H1KSkH7(kDH0Peh8ydC0(7JNfyPuvtlz9YLP5CSbg8i(YHUd3qwh1PcvLwEwPQgG3pqQd5RbsXx4IukH)SsQRBzd2kXSCYXqxtdnocP1V4HfDzP6u)vNb8ArxU18qfXJuBbnSsn94KUfIjKW0P(f0SSoSFRL1ct3tzPBYyNimntk15LwdugrlmEUa0TXXPjrYIgzqapJOA2PwgDXv8uqFR16ng1uwCpjq3Ul07sWh7(dd(nfibrNETOuK6lfv(OfIE1gfyvhvSfzFj6V8kYh2kcQWJ(wKWkAwk)irY(kVV95qW(ac6NwoDryXhmxFm0TUWHPl1C9023knMxzqfklHmMxPMjGgKohcEv6x4hptd6uvZPWZfN(1dY(khMBC6VoZkUY5UPCE6Ep1stlXLBClfDNOOIEX5Vmo)nSHCKjDAmwxDsSQagszrhlq(70ZwsQMR2f3TxnrZK5LBCfBUuj)jE6Jug0ybPoAE6HzLG(EZ6KubxFAaZRZbtC0YbVMOTCAwJzO7ycKZm6wQ8L9UvQTmBwpirWbbnzeWS3Q4nD(yc3XBqOMnsajX6RNeFuu8QPCLvIRHgvwHcsnklh6(ertMDKvZn6OPtNkDk(2fXku77kcBpLy5oF6jYm6KPZdTh8jphhTo8zArWlNrOc1rbui4wFPybso43STlXvINMgnj68xuqaQLDMZ5NMcgrJe8(2eXxtal6yp4S)m820vDcp5A62(xR5Ra4pTSs0rGBkLLYPw68at7O4VJ8UNMliUO1FU6Dv2qo0zrJIb3ooBYKN3BwqVz26aH7S1dhbS72gt6pBhqbE)HVvxnnQ79hMNgYDmFd(2eMJAnrmc2wQLI0EbD2HY(ApljarTwWzzdUMPXul3EMfrd64r6Wvfgq1P4h6C(mdHG(FMXT25mUw1wZ7X99ghIooa12mMRzl(m21Vy7jhf89vrRfXYamXCTesEPiG4SVNmtlDUy(flU(hnGVPwwDnzZpe9(X20zHOh9p0TppUy(4I1uyGUO4sqxT8RPGwqCRCdA1xQzWvF(76UpaAitbiPlzl6nyeenWD5W7WiRfa4nrcsDAekmdhMmGrzUKKtj8LzRy54wnBzQNpW6FQjWjD0gvnR6MaFq12jQAbQz1PWgan96gk1WU4zhbEKDC3b2pNEMCzMEQzJ0EVHZkbAYGYFXUMmyqJ50G(4WERbWpE8P5HP8waYWqXYyDgSGkYrJfSMAabnkhrjxgzr1AIQgsQMwrbR)yANwVogehimGrXyXPeqlVhCmTqwrJftuwVtwkSuW6f9iXfBNO03ZuRSEYvYKkkNnIf7QBw5QnqF9BlPd2x()ttPmWUmTZbly1jinrcCMLVEhRPxNidCCZpq7Gxh1HEEWRRC(M(b3P0GwKg2DmqZwIwep1qgzgA1oedMVJwliJ73VVM(6va9OoNsd)aMXkEPT2B4oY(oSSJdfUmt4GqnGEefmmcFu2)abWyJHoKY0s6WtIG3yMkluxtc04GNznyZ3IoZxJUBNoTVhhDrLMzSgtBfybwu22A5xz493CCgg86lrFd5FiAELkQL0a)CRMsPKPsvy23Z0DZCZuZFUT2DgvVQrDyOgWIqdlb(OnWTg6w0tyWZ8Pknmqk53(NhVOJlY20yVEz5PmvLmyYp(DRjAegI(iUhpjwqF9wNnTW1zNGCZjkuT4I(jgNGU1S91zE6sTB833lUs5ouZVTmklUCCXvak5uIeW7UpVsaLFP4IvyDhVUGH9e)RDXnVzzXdiUKVuXMAfi1kbqzzwvyl8oxqfGvBwbEW2SlFoS6TL6dI15Qoe5iqvr3u9c61SDKnOY4St6KAsYpod8h)YovLSRKW6XmTJkJDC4JdISm80kXepmObPv1LER(di2xW6jzD9s6w5QOaZK8MbEpk9bPIwrPiwI1UbgOjCRxhPVl4AG0EzOd7w3xsgOcuBmmiNzHA6akh9IlQQx3sBfqmg05OkZABlG3avs64sAXLqnApA9QgiqdmQGSc30(cDOQ)HAPZ0rnRUnVtLbN)EnGfpfrzQjqudGPICDqbPYYghsAXfeXGaeqwJNqT)2fSQ1sZ2ClFOZfvvRfT)4oPgRJwLCC1z08OYe2oZ4QEaFn5kSyijv0MB4QFJxyO2aGDuaU1Us72XznuRED50D4ma9KjyAU9Am(GTU)S(6YEOPp)g467CcfLtjgLBf1dPXvb(PDlvNsCKYE2m5dkgTFGmouogSEY)Meh2paeOk3pNqTjV7iN7hWJ)zY(8NU7w41rVKcCAH1sfLSy44ZXgXX4FoClSQ3(kDgHvu)YzC(2tzBV59S(OvAIOgEPq3onIeWOrRJaZcfHvxuib66A0avuYGfuLoRczNkAtRNCnzSCpK39engUEVV(ABNLC4L2NKdGXvA1mzhMxVUbz26w7geafwNG1Jd3b1fnpFex9gGeF)X8SkgnIDw6HSJRQCk0HGcblN4V6P4GBRULU)wkHNHvC3b982b82mhKplDGMeZt1h3F9hpqc41ssRKX7UA7Hh8ngYIcrNGfq05O192rXXrFqHz8yqB4HvcN90Q12ZkHhfAopYZXvpnU8P5siEUoBtqZZycxPzzBceiblgdIspqKl9rW4DKwIdio0XsmWjg6yhpg94nI4n62ydjbaI0zvA02oViDZMObzqY9oNc56DkQ5Q4eE3mnh9q9Zo9f65U4Vxe8XnbDMwotMam45DhMWZ)2xelmjzEYfoTWed)S7Ax39wB95Ny4FVE6bE4Z6l(eEAKvWW(oCZavGfzchB)fTuXXvsmYr6HeRW6YQLlRwQUM9k7VHW(3aTaTKK25HcXcSHnDgTOrnkl2gyb9qRr4qbYflqJWHx6H3qKb6dJVb2PntJUH30(j3(xMgsb)UBqfxzEHr(GgpmBpEBnMqzBHPmf6ERP6rEnc8SgpzxHvNeFCAasWVrb8a01XSRXdeCa62mEjPYn5zCWbbN5gkUy)XBopIHHX7349D1orL4xRttjEGNKs8R1POeVJNGs8ap9emOoWi44UctSng0TFNirIG76oBZjReUXmAyYhTHGi5J1qyVUrXX)sLoechxCxfPXox2jg(R8IV4wBT1NdZJL2iHyFpUavIakFr6f1zLqK3IalRKtm8BzN7ewj8uDVIq3llWkWYHG2ynAbgd6fllCpEdwwty6zb4VIWFsWFMdaVd)ve(tAaV2t8Grdbw5f5k7zPLJ2QGaBF)5cc9flMV9NWPSUsMbbnV5zqciDNy25ZzkvJ7eSddD91j8zkNtC)1Z7(xxKfPKcSXnAGfAtJHz67vci2AMQ8AUNkDHl7)aQlSEZJpFBR5gbbfwZ9y6326np()k0qT5rVEd1MDEfClGZxedFqmS0uiV4M0uCVZoxI(QZLAIvCpxpdJD6gUP51Ox0PcxMwg7kWNGBuwBZy30eGvsLOBXcTDmhXEEuben6O43UHkRtlyZiaL128ClEKH67e9FCwA8lyiN74b5jVLDBOihTVnOPWyS9XEPQQPjolWcmviLlkIXB03uG80xAF930mf5zfmI0wKz2mFNq0mMtWi5lyLmUN2QA)bvxpX00ZfuKGwZTObg1UYkLuRkP1majPbeLVyI9Co3)c3yKYypJuQe4WaDxhMbwfGpxAfY3i5uGJVKNNEtRiFlOgy0t9vlqEH1Zm1uGoxAWr(v2g5kfNIADG8T3h57SIXRkagJcfJAXllnQrVyeyqUHWCnhUyb0f0XBiCw343YPr)gneEiK6pRqdHhPHWptdH5jXAiKdQUNHzyodh8GECdHZbDSgcpOd3dC93zfKxFHny8olefF6vHPy6cfJ7oGjiAonNCEobYvAi86moqhlABJ)HiF39so9gvvKp6rgRE2I9Ta5tiWIUScorxgp(5(EKVog9yyC5v8QDD0ObulgVz49eJfHzyeOHHMggIz3ig(zy8PXJUmA)NheAAKXOrX2hFfwiObGhExKind7mm(1yHD2b4buAdHDVQJo1gc7bEVhAyKIqMUC3Dd2h(Atm8Zzz9ZdpazE7KlCu3kwKHhakTqrWtSZRixWT6tm8Z)oEhFSU6k6ed34CNdQ9lkWQopUc3(7CEtqvaEZoGLMfROiH3azCi)gmRPFgfWFoGF3rO5BiuPaP3gcQneE0SumMneopnRfH6zRVamTykRuwcqKvGCyJ9KIdNNbGeCoSOKzIboVYkneUpSjtPyvQqs8(8ASBNYYWYsvqbuEMBS)e9n0IyRwTHqnKQh8SvualoMI26U(lWdNiAqSWAmkeRenemAiC)neEmy0WCD8wUiIBbJfYZpjqRxta0I5kdclwsLtTeq3JDasfP016aRHWXPS6LgNvE(4rTTrBZHDBtk3GgICAZ9YJokpnPhwga4Na7Tl1qy5dKed1QSv1xuzFUu(uCkVbJYUDh)ZoCbx3zNMdFUtkmxu4tkus)aCs3CYGsgrQ7oaH2MlHQae6K0ZzWIFqdmM354gkUIOHoIdxCr2(8dJLvf5xMElwR9t50A7LDGfS2I7iy00NBM0zZCM0ymxhdBB)HIj5ttdzA)bI5(beF1dig4WRCur8QIqD5jDTs0JJ0mPK5jZynpZaM3ZM0T(0RjWsE9S0xLNaOB0yoo6Gbb6nqweWyG8X0E5doDCBaFubLk5WYBVHz72aVf85hLlutuF2p6X39pSE)qVVHhnahG((u4UFqYhIgt1iMAmMQr)t2B4gcXn6)A4sIelKc86fITXZ4wjLwUVykxLZ)3h(u)na3HEFEY6sToeyumhVB5(P1o99Cp18r(oEx1apwE)gXdUr7GVoOJoOVzORF)3apuOx1nUNlbgS60RZgY)Te16Edw9o6MZ1rKQpvpR5UARWlr8WnegH8Inescwyhf(lfO7knOGymqV34neMOHqgiLttRxdHF6gct2q4mq5MckZ0Gy4ro2GneMzpneETvq1uzV4D5gl7FrMvFpXZoGKXd8peUcqZZEtU4zCJP9hNcdHcoIcmIclRc5fAi8Wigfag03(oPqLaqsF5nxqtFPXmvES6iOoenq)mSUy6BGF4C3SwfFH(FFHzuxwrJwXCoW2drlQZLEAn8LMxt4lb2nh3jLk0mNL(p(H1Xhz)dpypucWbHs(mjX3yfDsvOb2fTOjz)FIaJe)tVrUPsp(d9qAN2EYYxxGMUKxvyDgG02EzdG0yaoNi6gDdgZ3naQb(fMYhQVJhikN74ogERT(eCuonRCK7)uU1UHWVQx8vUBjf3rC)aKoGpJRB4ETdNltGMypaAyapIl8uNOOHeBEtf9JWKAj8nYTeUjwpwrPzTJqxCMR5v8OvlIZZTi26fEWX6bERlqRhFP9ShGKVYjg(VB2zZV1wFw3Rn0pMUTqO4GZvfY9Ec9MOx)C8A7GA5(DCUH42nVpqe7LdDkVwfA1KWvtj(1Ng8MNOnDp7A72HhPvRh(jqRhKHsZaTXhvciY0A9Fieiyp61z3nGeIdyjQxnbnruDsc379ESwp95wPMhYDgPLVEOyhcSN2)FurNpTyantZHGwU49oZjbfPrlLyjv5fuSNvXotkS2dC8bVANFoR0ymDXo31mNLMWzKQjTGIjUNuJbUlnNb96lAXYeqcwhdYE6MVGvnQtRMjv7h2EqN(UNwTJN9E7dxnRvIYatrD9r8WTMS3t(0ZqR419jZ3rChri)(i2SRhqzurN4Ih1dOS9IOws2julVe(NRGZvV73I8BJqHqKJbUlSG5NFOHNWrTcw4aFjq0j)H)7c6KU73pYKFKiwYbs03lN0R7bF5K5oYlZm3q)4gtxdH3ehixdH3CdH3cK8BTHWAne(1aQ)2G3E7Co)xh6f)gW3VdGD)njFMgcVtiH3fyh(Dxb3ykoiQjbxw9FHhXR5y7xZxM3uaOksXgcYiYkep1pbhE12dZav5Cjizxas8ArIqROGU8dTcHvba7rKvaAVHgR84hT04fTwE5M39rgwNPc39I34J))7p

**Comment by Daemoos** [comment]
The new C_Timer wrapper is missing the NewTicker function.

**Comment by InfusOnWoW** [comment]
That's fixed.
