### ISSUE TITLE
[Beta] Extra Options says "Tracking Charge 0" with nothing selected in Extra Options for Spell Cooldown trigger

### ISSUE THREAD

**Issue by Pewtro** [WeakAuras/WeakAuras2#3909]
### Description

With Extra Options collapsed, I have no options selected:
![image](https://user-images.githubusercontent.com/29204244/197802936-f6791726-a4e5-4ab2-aac4-f7b0595749a4.png)

With extra options opened, I have no extra options checked, BUT there's a new option outside the extra options "Show CD of Charge" that is ticked which causes it to say "Tracking Charge 0": 
![image](https://user-images.githubusercontent.com/29204244/197803192-b8149d26-dd5a-4996-822a-f6aaef751a8f.png)

Removing that tick returns it to normal in extra options "none": 
![image](https://user-images.githubusercontent.com/29204244/197803248-d97eef83-4c6d-4aae-986b-3476a4207616.png)

### WeakAuras Version

WeakAuras dragonflight-beta-6

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create an aura tracking Spell Cooldown
2. Expand extra options and tick the "Show CD of Charge" option that appeared outside extra options
3. Notice it's still "Extra Options: None" 
4. Enter any value in the field, then delete the value and press enter, 
5. Notice it'll say Tracking Charge 0 now

### Export String

!WA:2!1zv4UTrXt8Cyrr1cHstH0MQkieOvPFiqP6FRqarGpx7MuLAhoFjTPuPZRVB9Dl58UR2BVK4aiuJqO8z)i4V9xIp5hH8eSYING8iKNaMD3l2nvn5dx2z2zMDMz)n)w7uFUEZfnx0XF9WmosS7ZjrYKpzijKrBXYfH4BpJ4GMD7MHLoI(flgHOHjmXMmcv2PATg(18gB82JjrscJ6WV2fKFglc7wzl)MU6aNCKuqIJXISp6UIILhppC(400QSCQCUVHFT8mCqmMIfKWwjS9BsBp(cIdZG)vjDFu)m3Ckr2HNI6JfJ0(P3komk5mTGuGc3nmbjIXThgH7K3TRFFowSwTn2S(wB4kbbpZzpW8TbQh(Mo))hEAwEh8EyQSf4b5GrbvR0YpOLFfp)tnhYK0nzWKZPTNXf(cvzS0i2(0f3uWIf4SSfxUL2H7njSBkWqy9ATzTn2ySaJsBD(PpSorGx0nfLjhp5K0B0(iZY1JYk7rb5SYMY1wCzjEMuWfLlz8Rpn9cyq1IKmXsRU6O3OB8EdGnTD)Y8RHcLK9W(wz991)mJbfeeYszINwc(7m46glOO0THRo4wnBqgoTRbfOUYrDqIQwtDCkbn6mKmhowCYjgOGf6SJZqO(9WXA3F58QBmge7aPuSas1OcfDzcSvXXlW)Cj(azG5dOVhsgWdKKE4aUahs05rPbtmzP7W5lEzo0JffOZO2NA2CAYFv(1nA0DoWEsOzkWTciEMnoKdWrgLVM)Lxw4tXXOW(bDtzmrYjgd(18mjPBF1vgk0tcyFqPBJMnQnUWFQuJfDBWOy1neqPR1p2oE9IIPTHgBNEnmyIV8zRlihU4pNJIG6cTOVpFoBPLGaWxrakDbL7yvE7z4l8oke7cpD9ezZX9zIONlq8JEEXcBLTh057KIBZN125MsimC9gnQ5fSrT6(8p9Y6vwjNcVTzMf94aONPDNwKdXlWV3LfMO(WyajmqMaJyjWex)IExrv6C8hRwVK6Bx6ouvltOvFN6QQVx9dQvFTABh1pQUI6Nuvu3q9yvDt3v9e1AQNE7zupt1q1STAZr26XB9NSMVYvvv5VGQMZ7O7rlw4sHBZJN9mahTBa0JOrAKh(bvE8JlUJHnoXS75mRwBFJzg(StWIaUIgltaqR2gzc8Lc8jVpGz1kaAVqCpGpXCiIkYTrP5ydVGo5Yf4KHgdNcGSN95K5wPcB5lVUEgVleZxvf4Fi0yxK4vBT(ktLwPLEE2625WGtVyUS0dV)iJgBUVQvOhriGrJXgbX5pv0jbtItKFMBkdfvVJeb(iN3RxEQKu2fOXcNxXl7fc0Hz6vUzaMqV4udVIRUbR5Ru)cFwOQRePh6Wr4ONHoi5b5KOrBS9Yl34qXw)VdidquspZ5(iVmjsiRFcgLHBjfMe9daGWoJJ03bGjb6NgezyGfmk7iTD6Hv1oU9qeAD1HgRv)M63v)HANoDjuswYBR(TZjcnzOWq)zEecbhfqCk0SVaJ4Ju9lR(ZYUqOKLhdqaak3KB2Q8adBCgjc7zWIVjT6lC6aB2LexEKr7AMw6QIIB1JCtjhEisenQRaE2aQwGTOK7HmwphpJdagHfUNLw)Mo)9WLirQVOiwKOim1RrTTR55Hs5jOsNzhYQRdMUm60QQxTAn82xZq(xFO9xsuDcEtqO6qF(lb(2KsfpIjiWDTPxpCTMER)YMn8RSXqD)Myk6BDxVWeC4ULfWtwu4nUBvEeHAhZG9lF20NoMWESzP7)vpCUm(1boXyOPKQBfR0blrR8O527FFX)b

**Comment by InfusOnWoW** [comment]
Should be fixed now.
