### ISSUE TITLE
[WotLK] WeakAuras unresponsive with latest update (4.1.5-112)

### ISSUE THREAD

**Issue by stratoru** [WeakAuras/WeakAuras2#3911]
### Description

Good afternoon. As of the latest update, WeakAuras2 fails to respond in any capacity, throwing the following error in BugSack. 

```
1x WeakAuras\WeakAuras-4.1.5-112-g98d73ec.lua:2485: attempt to index local 'data' (a nil value)
[string "@WeakAuras\WeakAuras.lua"]:2485: in function `AddMany'
[string "@WeakAuras\WeakAuras.lua"]:1150: in function <WeakAuras\WeakAuras.lua:1121>

[string "@WeakAuras\WeakAuras-4.1.5-112-g98d73ec.lua"]:1273: in function <WeakAuras\WeakAuras.lua:1224>
```

### WeakAuras Version

4.1.5-112

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Update to recent version
2. Load game
3. WeakAuras are missing. No response to "/wa" command. Verified addon is loaded.

**Comment by mrbuds** [comment]
It should be fixed in the next alpha or release, thanks for the report

**Comment by stratoru** [comment]
Your fix on line 2485 does seem to have resolved the issue, just manually made the change myself. Thanks for the quick response!
