### ISSUE TITLE
WA Options Interferring with BlizzUI

### ISSUE THREAD

**Issue by baruchvlz** [WeakAuras/WeakAuras2#3914]
### Description

As title says, the WeakAura options addon is blocking the Blizzard UI in two areas (that I've found):

1. Edit Mode (see screenshot). Edit mode is missing the ability to select the frames you want to move.
2. While in combat, moving spells from your bars does throws the same error

![image](https://user-images.githubusercontent.com/14321495/197958145-a29e23d3-17b9-4cdf-a932-4504d3e23758.png)

### WeakAuras Version

5.0.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Load WA 
2. Open Edit Mode

--

1. Start combat
2. Move spells in your bars

**Comment by Stanzilla** [comment]
Blizzard issue
