### ISSUE TITLE
LUA errors

### ISSUE THREAD

**Issue by Enilyks1** [WeakAuras/WeakAuras2#3921]
### Description

LUA Errors

### WeakAuras Version

5.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

3x Interface/AddOns/WeakAuras/WeakAuras.lua:2801: attempt to index local 'data' (a nil value)
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2801: in function `PreAdd'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua"]:65: in function `Initialize'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:1043: in function `SortDisplayButtons'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:467: in function `OnAccept'
[string "@Interface/FrameXML/StaticPopup.lua"]:5269: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

Locals:
data = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'data' (a nil value)"
Private = <table> {
 HandleGlowAction = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3450
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @Interface/AddOns/WeakAuras/Transmission.lua:343
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2433
 InitializeEncounterAndZoneLists = <function> defined @Interface/AddOns/WeakAuras/Types_Retail.lua:10
 IsEnvironmentInitialized = <function> defined @Interface/AddOns/WeakAuras/AuraEnvironment.lua:198
 form_types = <table> {
 }
 CleanArchive = <function> defined @Interface/AddOns/WeakAuras/History.lua:22
 RunConditions = <function> defined @Interface/AddOns/WeakAuras/Conditions.lua:721
 tooltip_count = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 get_zoneId_list = <function> defined @Interface/AddOns/WeakAuras/Types_Retail.lua:66
 checkForSingleLoadCondition = <function> defined @Interface/AddOns/WeakAuras/Prototypes.lua:1074
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 faction_group = <table> {
 }
 ensurePRDFrame = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:5022
 talent_types = <table> {
 }
 LoadFunction = <function> defined @Interface/AddOns/WeakAuras/AuraEnvironment.lua:628
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 FinishLoadUnload = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1933
 subRegionTypes = <table> {
 }
 ToggleMinimap = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:203
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 StringToTable = <function> defined @Interface/AddOns/WeakAuras/Transmission.lua:292
 RegisterLoadEvents = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1783
 FixGroupChildrenOrderForGroup = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3927
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:1012
 CheckSpellCooldown = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2310
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:2146
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2490
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3597
 NeedToRepairDatabase = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:2223
 StopProfileSystem = <function> defined @Interface/AddOns/WeakAuras/Init.lua:267
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 CheckSpellCooldows = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2364
 IsOptionsProcessingPaused = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1469
 ValueFromPath = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3879
 Login = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1120
 GetTriggerConditions = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3707
 TocToExpansion = <table> {

Next

5x ...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:518: attempt to index local 'data' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:518: in function `f'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:56: in function `Fire'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1959: in function `Delete'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:447: in function `OnAccept'
[string "@Interface/FrameXML/StaticPopup.lua"]:5269: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

Locals:
event = "AboutToDelete"
uid = "BrH)WYh657c"
id = "Plugin - Group Finder Custom Extension - Buttons"
parentUid = nil
parentId = nil
data = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'data' (a nil value)"
OptionsPrivate = <table> {
 SetCollapsed = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1741
 AddDisplayButton = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1281
 AddTextFormatOption = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1872
 OpenUpdate = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:887
 ClearOptions = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:851
 EnsureOptions = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:859
 PickDisplayMultiple = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1200
 OpenModelPicker = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1572
 OpenIconPicker = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1568
 IconPicker = <function> defined @Interface/AddOns/WeakAurasOptions/OptionsFrames/IconPicker.lua:210
 ConfirmDelete = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:498
 ConvertDisplay = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:891
 DropIndicator = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1501
 MoveSubRegionDown = <function> defined @Interface/AddOns/WeakAurasOptions/SubRegionOptions/SubRegionCommon.lua:67
 GetTriggerOptions = <function> defined @Interface/AddOns/WeakAurasOptions/TriggerOptions.lua:150
 ClearPick = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1192
 AddUpDownDeleteDuplicate = <function> defined @Interface/AddOns/WeakAurasOptions/SubRegionOptions/SubRegionCommon.lua:105
 MoverSizer = <function> defined @Interface/AddOns/WeakAurasOptions/OptionsFrames/MoverSizer.lua:1036
 StartFrameChooser = <function> defined @Interface/AddOns/WeakAurasOptions/OptionsFrames/FrameChooser.lua:19
 GetLoadOptions = <function> defined @Interface/AddOns/WeakAurasOptions/LoadOptions.lua:921
 savedVars = <table> {
 }
 DuplicateAura = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:50
 GetConditionOptions = <function> defined @Interface/AddOns/WeakAurasOptions/ConditionOptions.lua:2725
 commonOptionsCache = <table> {
 }
 DeleteSubRegion = <function> defined @Interface/AddOns/WeakAurasOptions/SubRegionOptions/SubRegionCommon.lua:26
 ExportToString = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:871
 UpdateOptions = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:843
 ExportToTable = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:875
 MoveCollapseDataDown = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1773
 AddTriggerMetaFunctions = <function> defined @Interface/AddOns/WeakAurasOptions/TriggerOptions.lua:258
 ConstructOptions = <function> defined @Interface/AddOns/WeakAurasOptions/LoadOptions.lua:73
 ResetCollapsed = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1707
 expanderButtons = <table> {
 }
 SortDisplayButtons = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:958
 commonOptions = <table> {
 }
 OpenDebugLog = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:883
 StopGrouping = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1322
 OpenCodeReview = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1585
 massDelete = true
 Private = <table> {
 }
 StopFrameChooser = <function> defined @Interface/AddOns/WeakAurasOptions/OptionsFrames/FrameChooser.lua:89
 OpenTextEditor = <function> defined @Interf

Next

2x Interface/AddOns/WeakAuras/WeakAuras.lua:1812: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1812: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1809>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1863: in function `Resume'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:194: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:176>
[string "=[C]"]: in function `Hide'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:619: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:617>

Locals:
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Mass Dispel - CD - Holy = true
 Desperate Prayer - CD - Holy = true
 Words of the Pious - Active - Holy = true
 Purify - CD - Holy = true
 Grid - Holy = true
 Symbol of Hope - CD = true
 Mindgames - Holy = true
 Divine Hymn - Casting = true
 Alarns Tormented AutoPicker v2 (!tormented) = true
 Details! Boss Mods Group = true
 Luxthos - Experience Group = true
 Mana Bar - Holy Priest = true
 Empyreal Blaze Stacks = true
 Holy Word: Chastise - CD = true
 Dungeon - Targeted Spells = true
 Better Mythic+ Rating = true
 Holy Word: Serenity - CD = true
 Twist of Fate - Active - Holy = true
 Details! Aura Group = true
 Rhapsody - Active - Holy = true
 Fae Guardians Tracker = true
 Dancing Fever 2 = false
 Fade - Holy = true
 Raid Assist Imported = true
 Power Word: Life - CD - Holy = true
 Leap of Faith - CD - Holy = true
 ZenTracker (ZT) Main = true
 Apotheosis - CD = true
 Holy Fire - CD = true
 Guardian Spirit - CD = true
 Alarns Tormented AutoPicker !tormented = true
 CURSOR = true
 Group Finder Custom Extension = true
 Prayer of Mending - CD - Holy = true
 Psychic Scream - CD - Holy = true
 Plugin - Group Finder Custom Extension - Buttons = true
 Targeted Spells = true
 Experience Bar - Luxthos = true
 Angelic Feather - CD - Holy = true
 Dispel Magic - CD = true
 Sound when targeted by a boss = false
 Empyreal Blaze - CD = true
 Power Word: Fortitude - Missing - Holy = true
 Divine Hymn - CD = true
 Rhapsody = true
 Mythic+ !keys Shadowlands = true
 Power Infusion Provider = true
 Shadow Word: Pain - Holy = true
 Holy Word: Sanctify - CD = true
 Power Infusion - Holy = true
 Publik's Holy Priest [10.0.2] = true
 Lightweaver - Active = true
 Divine Star - CD - Holy = true
}
(for control) = "Dancing Fever 2"
id = "Dancing Fever 2"
(*temporary) = <function> defined @Interface/AddOns/WeakAuras/Animations.lua:389
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = true
(*temporary) = "table: 000001C79B16A530"
(*temporary) = nil
(*temporary) = false
(*temporary) = ""
(*temporary) = "table"
(*temporary) = ": "
(*temporary) = "attempt to index field '?' (a nil value)"
loaded = <table> {
 Mass Dispel - CD - Holy = true
 Desperate Prayer - CD - Holy = true
 Words of the Pious - Active - Holy = true
 Purify - CD - Holy = true
 Grid - Holy = true
 Symbol of Hope - CD = true
 Mindgames - Holy = true
 Divine Hymn - Casting = true
 Alarns Tormented AutoPicker v2 (!tormented) = true
 Details! Boss Mods Group = true
 Luxthos - Experience Group = true
 Mana Bar - Holy Priest = true
 Empyreal Blaze Stacks = true
 Holy Word: Chastise - CD = true
 Dungeon - Targeted Spells = true
 Better Mythic+ Rating = true
 Holy Word: Serenity - CD = true
 Twist of Fate - Active - Holy = true
 Details! Aura Group = true
 Rhapsody - Active - Holy = true
 Fae Guardians Tracker = true
 Dancing Fever 2 = false
 Fade - Holy = true
 Raid Assist Imported = true
 Power Word: Life - CD - Holy = true
 Leap of Faith - CD - Holy = true
 ZenTracker (ZT) Main = true
 Apotheosis - CD = true
 Holy Fire - CD = true
 Guardian Spirit - CD = true
 Alarns Tormented AutoPicker !tormented = true
 CURSOR = true
 Group Finder Custom Extension = true
 Prayer of Mending - CD - Holy = true
 Psychic Scream - CD - Holy = true
 Plugin - Group Finder Custom Extension - Buttons = true
 Targeted Spells = true
 Experience Bar - Luxthos = true
 Angelic Feather - CD - Holy = true
 Dispel Magic - CD = true
 Sound when targeted by a boss = false
 Empyreal Blaze - CD = true
 Power Word: Fortitude - Missing - Holy = true
 Divine Hymn - CD = true
 Rhapsody = true
 Mythic+ !keys Shadowlands = true
 Power Infusion Provider = true
 Shadow Word: Pain - Holy = true
 Holy Word: Sanctify - CD = true
 Power Infusion - Holy = true
 Publik's Holy Priest [10.0.2] = true
 Lightweaver - Active = true
 Divine Star - CD - Holy = true
}
Private = <table> {
 HandleGlowAction = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3450
 frame_strata_types = <tab

### Reproduction Steps

Using Bug grabber

**Comment by mrbuds** [comment]
Hey, can you include your data (it was asked in the template)

**Comment by mrbuds** [comment]
```Lua
    local data = OptionsPrivate.Private.StringToTable(self.companionData.encoded, true)
    WeakAuras.PreAdd(data.d) => data.d is nil
```
This looks like a badly encoded aura, since wago has some issues right now i guess it come from them.

**Comment by InfusOnWoW** [comment]
Yeah from what I understood of the follow-up messages to one of the people having that problem. This was caused by wago being down, and the wago-app inserting bad data into their addon.

We can prevent the error in WA, but the real fix is on the wago app side.

**Comment by InfusOnWoW** [comment]
This WA lua error is now gone though.
