### ISSUE TITLE
Login Bug WA wont open and wont load

### ISSUE THREAD

**Issue by Schlomey** [WeakAuras/WeakAuras2#3922]
### Description

![unknown](https://user-images.githubusercontent.com/116742656/198065536-2c5c7c4c-c9a6-4f37-b2d5-7b766aafaf08.png)

### WeakAuras Version

5.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Log In

**Comment by mrbuds** [comment]
You don't have 5.0.2 installed, it's 4.x

**Comment by Schlomey** [comment]
mb
