### ISSUE TITLE
attempt to index upvalue 'current_aura_env' (a nil value)

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#3925]
### Description

errors on init / reload.

### WeakAuras Version

5.0.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```
1x BigWigs: One of your addons caused an error on the "BigWigs_BarCreated" callback:
Interface/AddOns/WeakAuras/AuraEnvironment.lua:526: attempt to index upvalue 'current_aura_env' (a nil value)
[string "@Interface/AddOns/BigWigs_Plugins/Bars.lua"]:2131: in function <Interface/AddOns/BigWigs_Plugins/Bars.lua:2118>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Loader.lua"]:1070: in function `SendMessage'
[string "@Interface/AddOns/BigWigs_Plugins/Bars.lua"]:1688: in function `OnPluginEnable'
[string "@Interface/AddOns/BigWigs_Core/PluginPrototype.lua"]:31: in function `Enable'
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:378: in function `v'
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:57: in function <Interface/AddOns/BigWigs_Core/Core.lua:54>
```

```1x BigWigs: One of your addons caused an error on the "BigWigs_BarEmphasized" callback:
Interface/AddOns/WeakAuras/AuraEnvironment.lua:526: attempt to index upvalue 'current_aura_env' (a nil value)
[string "@Interface/AddOns/BigWigs_Plugins/Bars.lua"]:2135: in function <Interface/AddOns/BigWigs_Plugins/Bars.lua:2118>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigWigs/Loader.lua"]:1070: in function `SendMessage'
[string "@Interface/AddOns/BigWigs_Plugins/Bars.lua"]:1688: in function `OnPluginEnable'
[string "@Interface/AddOns/BigWigs_Core/PluginPrototype.lua"]:31: in function `Enable'
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:378: in function `v'
[string "@Interface/AddOns/BigWigs_Core/Core.lua"]:57: in function <Interface/AddOns/BigWigs_Core/Core.lua:54>
```

### Reproduction Steps

1. import aura
2. reload
3. see bugsack
4. revert to df-beta-5
5. bug gone

### Last Good Version

df-beta-5

### Export String

!WA:2!1QtBWTXX1rqeffdL4qrlRA7Xo5mYifGiAirqjzx3iBtqcksxksgaqr5iZH4WDlWDMhU70U3rsih1oHtgpA602md(r)rMotNb5pDY4FH(T7xtz7KoP)iDhozA5VstyAD)(pSt)D67T7D4lcas10IXwC33U7BF77R99E7fP84vhxFCwPPs9QPMCQX1FCAATLlxMr8M)TC((V6iJmY9OBrOmth7B300USdTQQh05IUpNzfBhkzzxSll7weBVSuQdLv8ivBndh6Cu1QKc1CjLYptUSzxQUQTPCX3mtvvt75Y4bdMX2XMSVUpvmYgiikJO5yRZ2LOYeiGFU9WM59Oe7kEgNnhZtL6nhpg)C8pn)ZWFA4VF2ZwQSPTjZOxW5SmRA6D26mIv5vCmT9sxy5vs7tTCFjdppx2RF1RUTAfNuMoxnJzL1mRWkKF1Ro1nQRs1wuSFFJlURpJSiIgJMLCO6e6mowo03osKirBibKvVcX985FGVkLOmNVLLYAgMEeQ8mtm2x13d4jbCRy0DczYP)jZdm5FTsinSWS1xyb)LEWR9AgPlrv1n9zFJpDjGxu2SsS0(M6nVZI5DEq1R)AvzQbBCEZhsotJYWooJjvZIuSEfQJV7cWQEUOh(rn8C0cKFpxKIRtboxLkeAK9lPQTPo1XvEsIgn6krVwQBCeWFiuBvR7kxdPKCxmYXCv1ir2L6SDESv0dLdKjanUJLXY8HpuLQRuWXXYZ0TeJuf25stM6APM667jNU8u)Yhcuhqj2EZPQ55qlLB6zxy185yAQwKOzyouV6QmnITUPDLMLr9iq2R6Pgf2FpHIsKgusf4VO6XE61SvRAQjo4nqvhZaUmGDSXnZaAgEX4JfJF(ynLANcvHsZKDPczZfiuxWgOTin1CS8RAlpLzSCu1ltFiWjwqNnAgMlr7I5Q6dhWyzyaR)I8BhlNMLkJHTk5bhaBpSzDqLzdXag5uTaBf(076rnrMp7fUCDF7GoXObn(GDbKBzbBtmESCQGbr6m(azxY1sTgHMJGwyLMNOA5z0qNuYVCz8WtNp7IRm3QlEiZVKyk5Hbm3P5gZmD(cBKVW05k0AOvOeyOC5xj7IlMdyzewSDRqn1r8ep3S1X2RzQ7zCUmaVC7mZU8Alf3u3D8addLcMvbYxbmqgFRFW9gx7fE861nbg(gmtDsMfZoxbGYyQEO1mXOHhzhVjfm6MzwUqHLVtUfU98f2duLOBwagZNsCtSaQXvgy2V7mQmpqGNrL(URUWR0U3RKhxWUvSC2gP09l5755yVmOCbCMJ2KqCNgLlE5qndJg48KgUp7Hak02S2SbExmOEYDTXDmr7sltMxgC6g8j5PflmJuDVj2(EsT1i8eOPtUTroZ8Vf9B9D(T(P)0)79fNICHQJhk6MbK(63XrNKE6zNTPa08M66e7ClL9UzZ5E(UweoXmtVAHL3TKAOhL5FZF85HFJ9FfnADKgYlnjaVhofZGS6I8B9cxoNMbrBZ5I74g)lFl(Yr3DlvQPAjlYHKDCnLhwuwLBlvlFs8jVgvZq1Ucb0821fSwjuVA83NV7Bhf2WFZxe)nB0JcDjSG9CuhBpJ91alzDNTTZVTPlPyoH4S0L0CekV2OBfIbF2Y8SJYNd155Zl(3fe)7B3YkWgu(Og878RFz(sX4l)Xn18zEov3WauAY5bKP(rsi3n4uWC)UVFmf4x41ck3QvZjed09Xeg2J6tcgQQRHkAAQdGJxcocXLdyYqvQEak34Lufijodpxvcgcek9fU0mD2JbxWxqO2(vlrOa0hXVlFnEoEEESsYnIFp(7W)M7C(VszFBHVPeQwwGNqpcBcHj6eWUMusULvequUfGYSlnZYRIUQKw0Xv8mi2IPH)qNfBqS3kLGeiuGiE)h1NrBDwzDpd4wDLnNylftBfxvtk79HZfZ1Y0lr8jIprNOhVjkfASzw2KOFxu7IL8rk6oTNupJE)Twpq8Oa2g)mVL5Lm)bTNbdFk30e9UnsougPGNLe2JwRnC9MaINCcLR37ydItF)TUFCnF4EsA8uPmxhPlbeWZtaOUqtNKBy7W)2LgrGl5nYJHcHOQBvcyUGMu3WWFwoGdfLsavSgrDZPbcML62eVWiFq)7zQTGEIwQHDVWomilLkStFMxB7tXm72CTpZh9SjMj2OpJJUEeJJn6Z4TTjlLk4A0(TlHEakLsdA0NzeAdd3VimItusAt1pErxoAGZyRU9J(qtCyATS2VpWG7wYdsSe2oEht1NSJMLVorq5G(3Wgw1wxbrH8CM84s)2eKJVNRV4K2ldnGwAJN(Jg8xlKi9dMQceOrceHte)sSlL4s6x5sjbJ54Xt23Ld7sa)(wkxBW7sheuVo6UVKcwF4lUFUiBTsWAEGlKyXi)VfRdCORmSn0wp2Pf(ajUHlA7hQqvVyNW5tQSzJxpNp0BRs)xeOfEcxzmWf2x4jIDI8)EV0XZrQsMyqIHKRpqK2Pr2aXR0RW69)GCC19Jdb2L(AT3dhEGk2duMnu5g6KCWRAycUtXIh4yjoDgrh7w8aV6Rp0L3xXvigcK2Necc8FbzQRzK4Kybt0L7o5oao5u6YHxYbULjJD6HEskjI78gQVVoUwtexyGlDuul9929vkDzJmyzDx3IHXsougmZWz7UcrFq)KjPOFQMlKgtfkHXWmcXGUf5reF4RzGPtmq)X9MMrlmCffiQjeyIKdhfbr2G)z4tmmDdyYb6udNx1zIl9nWZWlCajSuu)gWTSDBJFSzNkvCLequPIfaDsgV96b9NNKvtOY1FcC4odIQDNtGNgghNSXWNC7qddADc81GiadpYhJ7j6nXj4rZZbY7NCQuKbLyhQ3jo1hD6dmOhy9nLci4HbKoHJ7XZMyybXQ0zohYPCmpscWPc8duwT3ixKd3T1)PNKxr1Nr()lAMsWsvdE7fr5Iq6XNWR02rWP)m1EcUiX)KFMZry(vFcp0N6ZClAAqsQJ5wSfla8lMOxghybDTNqEdL45tThapj4VDohag)RYVVSkNm316n54ju6r)UnGqTN2qAXBNqPNYUWlWxL)UXcRFf(wfnfNfFxD4F5ReJ)lZl4oUC8cY66UOtftTrDppwl6TibaXs)9HJ0u3K9EIcbTfjTQDTgIYd2QI8r5JgH)jUi)mgIsbUOPnHD(CQwGtYOYIOklq59I4ogCiMw)9G9LOt0VJPTb)tDt(t17BHWh7yqo)XG8fAUA2S7SMMtHAt(o8NHp9(HLhxuwWI7fwwq8npmkzqmRy4n)B9gV2F7iJmY48O3UUOqHZbZTr2DCXlP3wT2EafINcXPZy)wtbF)IxPbE9yEhFQg5fhH)S8lY)CWzcNt6zG5aksvXIFVWs5xy2SYYk3MljQv77euR2dflcr8CwQvy0LxTWIlSu2gqOA5epya79Uip2(qxSAN4lgyRhaOSdLib84Fo3xgXZgI)r(MxB4UbgIXgW5rZeFAKOUpFFMJSb)x19zeWXBcW38stuw9mtdDBiEcdcw)7mlT8sz3x(EeHfBE)a8z7jE5Rp0DCbaMHQERt5loYrYzzUdrwW(V(EcaBbuwj8nGAHe(3wocQAywUgimfD3gKORrvD3DTGghk3LW3iJ)q3p3G4aYErQ3A84xYn4qekfKYUaIU9BLfaUJhGP5clTeyDjExaHCDdT2A)XOGubb6MCq0sWl)SHNbOMzaQL16IFfWuJ2MPIQBV8JFg(hvK3K)7W)D5)E8F)i8)a(hY)dbnV)OVo)pM)T5)j8P5)P8)m(Fo)H8)I4xsJVxe(FP4eW)RAiPy8To4F3a6K)xZ)Er5)nV8JVqF0jyH6eNRRDmZso2KwBQ7yZrnFOYxXxvhFNlLcf6LiyDsenxyMLxAd5Jx1jv8rgcc55)46Tm1edIgF3oesr(3AkURHK9IZJBMBfqtYAFXlSyyQTj4OHDgHDvGWknCbc36ZZFqr(xBLOtMAs(3jcNgrSI5OKh4tS1QTYN4APsFdXZeKg0j2n0prrHky6SISw0LpluAPA20834M838Y8V5oN5w9Vk2dkv8bnA(wH715WZaxfIg8sWTl9j6ta8zs7S(NWf5YRrbvkIxRSBU)uIIfjJq7(xh7KoOZnWotf05MyNRh05vXo3yIypkwaodPOocApgCFCW(VOJk4OvCVSmef5IS9R2DfLezbkiVzK8QW6d37CWNyjZA9lgHY497HpcH8Phu11HKuowLFbaP0GiFRbxjc)3RNN4nnEhuIRLuzGteF)zXhaqNtVRzpZgcUDQPld0FIRLAYBmrBck5q31tCJWGesgRFba3fJUL4)oG(UAfsIJPVmr7qUG9Agkb8CdzzQuo5)3GXSTY4Pns7OC)OG)xcu66Ra03EqIqeNKK9wD5(eSpXdIqQcj(WQu8Pu5R7nl2PReqcCd2rdO4hXgq(seV7dRCDr6yN0Ca0lyhNIsYnWcPm83x7jjVRF2uyAjVewkT1wG)VUUZgYWolk)mh4X)GJ6XL5Oh1t1fnA2XRhuSK0zrXd7(vWEHpy3GxR66JsLVK11hne0uHGMQfO0HGs3c0KHGMC097Q2vgUJ1RJ7r3RtvRUIZ9DIW)8CL6TIWJ)9Zjg1O3WFv3XOrqm4WC3jYpSTFLJ5OuMjuxf2qMEsy9y6JPxync6zfcW9mv7Ekqtx4Ux0EIL0bX26DxYUEgnvkLJvbNot8RJ94yQ7bzujpDIsD0AYhVUqTn8cssvCsBxxXbHD7(ITyd8vn6yz9nvqm1VVuRVFjrKgtgePrr(p4PKHCozhzrW)T3VLgegn4K8RYV2rTZgOv4QZ)M)ON7xCLrg55DhRTY0QYm9kW)fOOmaeKzEOJtvCZN6Wwj1iY9aIP8NpAJGKyAfu7BXNoUP(HGj92T)IAe5)0rOVUxim2jCpN1KjJCIFfsWhvIiNRB10HAcNirM4nMF5Cl8vxEPctVyUoIHMl)ZFVm2mzcMImgEw(l9r3LA7ChcfYIJhdYJd9hXzrPGXekZnYG0(O3LZodmSNtLkwK0BsQX)hYGsd3lNhRNJJTvnrffA9KfHojfvtNWGuhlR6B5zSfGOdIeJ)dXpke5hOdSV5mTD99GJN4d25GiNZ9l0(1pc8cOKqZPAvvfgXLGFzr6jpiYNjGWoiYtHi9Fhx5KdGIclb4vfVjUqrnG4a80IU(poiYtBGi8ZEqKXeusQ8ddf9NOoiYzei5tcCYdICwJdI8PgTCWo8JfKlYFNLW0mWT4Le1jeC1RaHPbEizkjktDQQmTU(Y2igl21X8hHR5zYk9AR8Lr)2Vbsr4bP4hKrhqRB9PTGOYzk1C8v8Ccyd1u2gdQeSkdLpFrgWPADAyk4hUOW1lCusPqsvrjd(b(q3ujXKj)A2qEbmfDhcZ(l6fezCaIyawv9cVwtbMMQfeOKEnfpkyvHVucNH6F38gLeFpsShMBj8tcAVLb7AY2kRG3p3a6iAOmz7MPB3CQ2nVE7M3azk)NG6jK5krZ7GixOiWH2pNG(c0Eawt0oflNjuS831u8firev3OiF(NviYUGbK4ILLQlJy0eevZe0j4dReZkpNkLQwd36dXcle8rD(R8Biw)tBGQp1fFJGwM2edCE)Bb6vxqi0hBgFkfdgde4kOPgQ505QpissXY(x7CzhnJWl0jUO)Lox0br(sdAE)ZDpVRmO59XNs89pDkX3)4PeF)K(GpWFHqkux8r9k)2GBG6VYIhfjG72fFIX)K8ZIro8)8

**Comment by mrbuds** [comment]
```
!WA:2!1rvZooorq4nkhwKfA1sanA5NdwbXqc7iKyeSW1XHe2fLzYGThMLtEA7UCCZy3DVv3oZK9yecX55riN5uEcq8eynING9ryFcO64iyfIXhsQQ9xxD)99vL7mPxvpEp(V9POQ2wkKao7S4Pp7KXHzQsf(9DPh9J5cJUKTmgU2MKRWkMnrNyfvqcFPKvjYsSfiykuL8L3AkyC1v)0S8Cdy)O7THjZku4PkH0MoA8jXJd1(3DbBZ6OFywTXQQCiotZzwiewas7Ry10QmRi7Cb3weCeLISmRqjnpj0yzO1lqif29VHRsARXfPT)RXcL6sdKvJqETmBW3XQGyLQ0k0h43pcSNrBmOopV)b(oaUQoyON)UNrjX0ne)8JYTao4lEtm(AKO3G(fqzPQ)qFqYh65(jnNUmMcVvwumFoGMhSpUl8xxZHu6WIxQb8PJNE6KZMgyPKqwnYoCLrtf7zCJ3Rm1PBjFeHwC9MKrhffNefFuyCqnDJtDsjG)dStj6jUom60XtN24L(uGvAlcjFcmE3ul3D8E63XPBlG428JvC43VNU)DBnvkEcsoXfVM4kGsw5pseI4)v3WKcNPOKpP5btAEuGujH)eygiYIGCUT4(3Yjs5qK4OisUGsYnRCyCcqZGGkMqs7TzqZW738znpU5ak8D)VReKRKw9dNGIx6)d1movuMFC8AI8HWCxBWhSxZJULstzzxoNARL8GsfJpjWiEjSxyvn53EbK6MTxZx6fMvYmgxuQLvsQNlCL7qIi4V)UU5N32n3DnU9mC34alPq41TVOJE)7w3kH5SSLj5LkfwO)47gOgHmHtq7Q)W)xuTbHoW81Khd8Ttb)YBV5nG3)t04ptn8I8LbthpjETvLTO1OERf)rFbx)E0CW)og4N5QhU6kfYphz6vNVlytos9mKdssC3x3ogpXTKJ(PrJchp(KdRf8ndTto(B(6PF1lEbpLS1CXCpC5oH5wAGL23m92ruVnT65OTFCPtNoDx76de7EPq2YqkZ7gduM3(vJGzXXZoUN5WVfw0BXF98)(
```
on init > action
```Lua
hooksecurefunc(GameTooltip, "SetUnitBuff", function()
        C_Timer.After(1, function() print("hello") end)
end)
```

**Comment by InfusOnWoW** [comment]
a) that tooltip hooking doesn't work anymore

b) why the heck do they hook the tooltip
