### ISSUE TITLE
WoW DragonFlight Beta v.10.0.2 (46259) Oct 21 2022

### ISSUE THREAD

**Issue by Precurseurs** [WeakAuras/WeakAuras2#3930]
### Description

Hi, 

When I attack, I systematically have this lua error.

**_Message: Lua error in aura 'Dancing Rune Weapon': Trigger 4
WeakAuras Version: 5.0.4
Aura Version: 2.0.13
[string ""]:7: attempt to compare number with nil
Time: Thu Oct 27 15:23:56 2022
Count: 8
Stack: Lua error in aura 'Dancing Rune Weapon': Trigger 4
WeakAuras Version: 5.0.4
Aura Version: 2.0.13
[string ""]:7: attempt to compare number with nil
[string ""]:7: in function <[string ""]:2>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:602: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:843: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1889: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1723: in function `ScanForLoads'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1786: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1784>

Locals: <none>_** 

Best regards

### WeakAuras Version

WeakAuras Version: 5.0.4

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: Lua error in aura 'Dancing Rune Weapon': Trigger 4
WeakAuras Version: 5.0.4
Aura Version: 2.0.13
[string ""]:7: attempt to compare number with nil
Time: Thu Oct 27 15:23:56 2022
Count: 8
Stack: Lua error in aura 'Dancing Rune Weapon': Trigger 4
WeakAuras Version: 5.0.4
Aura Version: 2.0.13
[string ""]:7: attempt to compare number with nil
[string ""]:7: in function <[string ""]:2>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:602: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:843: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1889: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1723: in function `ScanForLoads'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1786: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1784>

Locals: <none> 

### Reproduction Steps

RAS

### Screenshots

![WA lua error](https://user-images.githubusercontent.com/45815282/198303426-45036d34-6071-4a15-8ade-e5da34eab60f.JPG)

**Comment by Stanzilla** [comment]
That error is in your aura, Dancing Rune Weapon

**Comment by Precurseurs** [comment]
Hi,
aura Dancing Rune Weapon ?
i dont understand your response, What is the solution ?

thank for response

**Comment by Stanzilla** [comment]
The error is in the trigger code of your aura, not WeakAuras itself

**Comment by Nokramx** [comment]
This github is for errors and bugs for the weakauras addon itself only.
But you have a error with an aura you imported, that's why you won't find any solution here.
Visit the weakauras discord if you need help with an aura you imported.
