### ISSUE TITLE
"Talent Known" Load condition seemingly dropped from WeakAuras UI when sharing WeakAuras with others

### ISSUE THREAD

**Issue by ZingusWoW** [WeakAuras/WeakAuras2#3934]
### Description

When exporting my WeakAura as text (haven't tried other forms of sharing), the "Talent Known" load condition (specifically Steady Focus in this case) is dropped from the load conditions in the WeakAuras UI when the player receiving the WeakAura imports. It still loads as expected, when swapping to another talent, it unloads as expected. This appears to only be a visual bug. I don't know if it matters but Steady Focus has multiple points that can be allocated.

This is the WeakAura in question should you need it: https://wago.io/KHgLOW8l4

Thanks!

### WeakAuras Version

5.0.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

N/A

### Reproduction Steps

1. Create WeakAura with a load condition based on a talent.
2. Export WeakAura to text and upload to Wago
3. Delete WeakAura from your client and re-import it from Wago
4. See talent load condition visually missing from the load tab

### Last Good Version

I haven't tried on other versions, sorry

### Screenshots

Before export:
![image](https://user-images.githubusercontent.com/101422551/198550362-d0578594-30b8-4bba-87c1-a8a2e5ca4b6d.png)

After export:
![image](https://user-images.githubusercontent.com/101422551/198550296-8a2ea61b-77d1-4d57-85af-8093791efd73.png)

### Export String

!WA:2!1z1tVTXXvCWOg4cguNiMwv100InQOQsawYw)Znon(axQvwmrs0yjLKBnmwo7UZYDIwUZ2zMLu0WUPrhcmqU0quGwGI2MYd9dapKJfT6AVmGOFce6NaDOOOhS6BMDjTvCmbb5oV5nV)87979MTWbLAxYVe3EJLVXYRxY)jxJ1Rwqahl2(VV7f)VlU4I)5aFmhjsziboCijoGYAJeeA88jZsAftz4AjQLCRo4yHfJrz8MdbT8WAj8Mdy4wGcn6LGnjE04(OysMjUPzBej(a3egg8ORlnn2dFkgXX1fmCClr4vmfWXKV2iFvaahXrTMXXGD85NOuvB3yAm2MlqmXbYxRppI4JJWbc536kYRkljFD5BiNwwYnGet4HB98Yavo)imoPmpb7jSvojSphhfCxkjw4wXAVgw2N6rPr(0UXw(TWHduzrDAkKIfyhpgUU)h)0lU4P)3KPHWW7iEfASasU2aeWQTFJ6v30YLJB3bZSxfW6vgHsfHuwo4v8KXEi0netAfkQomZo6WW2U6D2UHBxulA1n7)HB3ANAh(UrRB7rJOSpyk4tsPuoUsUn2L6djcUzY3ESvBGpwSjHJCJW(HNdweZIrrhaij49U2OOKq0u2Dj(IWQdrXEqKPDSCwwNmL(rRMYIsE7qHiH)Ex)6Qqzzc96tILRVYpD1uI)qVf)a69w4w1I4eZhsPTlmqq9YTXSf(0Vyyad1wvFrc0uYVzZH(eEseQxvatN9v(gPduvwsgOmGN6ARjp83Bg5vhblDbmPfdik(p57M8ociTC0)KrlDsCeK2yhGq5ruECQKV3xJozpyRu1p5n17bvdQIu6DOcdmldlhWOcafvqN5E12ZAugUCVScEHr52mwOyGQA8ov3ZkPKwmpebW(ppx1ZZuLCm2xB(p5uTGoqicfKM9NyPbwhR6f4Dr9Yu5Js5csqp5SzERlL5FidLCYH5pCwM3gtxnlVFJAj)WxgSKTQq)j77wxGr(9YZSXHBYB8C5qfnfRqHctLl(5yhNcjTLTJzTgnQT7a9UpJrkVkdQxkHjl(Yci)EXO2ephriK1HavT3LWVxeQRtEi(heCQlK(ywUZuX2WCjyO)mz66)YuedBSvAuKXHHebwE1(kUJwNZYvDm6pkFnnZxJTeh80uJg3)uVljb30f4MbKwfzKyfJghAgrr()Nb(KGaIxAKO3m2TH)ifnvhFgzqrwaYtrMvppaArDeOiyKqOTxeIZNxgmV727RgX00C3A79HnD5K4wry5rUzkcNB(5w5gnDx5wRTXAR10KH8Ym8dHrEv95VIPAWLYqVAZR0u2(v7R8smgcWqtgncpXZE02Uirt9KchT7HAPVJ64np7YRNr2(F)69t6KmjikYYYd(nnHzOIIY3SO87u8ebJ0Qfaf)T57NgNVygxpG1sBNSDampxDOfwSOb8HHHRrInwabZYDWXDw2dXfyFdWRgFvz)QBBSXnV56RSyrCSpl3YpzA4Yi30GaDh32w7C3T2FNbzEtn)WTO(J8Xhx4NnX3y1TqxZW5AgafW6zl0ZVVZ(v3uV8f)c4quu1nZcDsGXcJpUXTVTXC1VR1o74uPC9go13VsfR61NZGYmEP60OSDJ5YSLkDFM3vAUpGOQNxyo1KqmBUfneH4yT26t8vaNBpo4MOro0Mlwztn6zS0szD4g1dPILwsRpaOf)6TAmjsb3UAiJN89RuBxZYnC2P2DCSoaUi0z)92Q6oaz1AtBOXfZlomd813k7cxyjs52EHyVJS12iV2ShOllR2m5eHWv0YhFswe7ZlAMcGGBw(FY4B7lTQ8ZC3gJIeHWD2p(maE12ToWbihp85W2ZZhLSz(jdNO7DzyqxBDXyE5Jkk)4)6QmC7sBi)1YpXf6fSXTB2xbg5PeSznGEHeuwP3)u1g6GK4ZFRSUW1Lx1wjE1ZHtBDm0yupllAYabQKnu(BKFEMZ(u5FOO8VeocM6badhQdDRfpIR)Bxcx1Ul)JVL8pPIg5x0uDqiv)Zzh(lhQ6vZXOMY(WKaLEdYOpkAJ8ZptRYebzw4Zgur3TBSdTfm8lR1pcE(3o6sKwwUTDx7gV763Af5Vt(7tMw1P3b3iRNdExc8uQlP)iDdvhOOLukRgMRb4cIxY)ysdNyrdn)APLmGlZ640YZF5vwMR5HWGDQyEvl8ybbuWyldyo8Ys83FJh9I7PM)o)cA5WTe0yO(g3YbbVPzx9Ep6D8OqHgflw(OEmck(YtBwqC)vEGUPtC)vFWIQUuX9xdEqjkMkGvR)afT)8SB22s9(jQbmU1RyBzTNj8(VEjpUAmpHWG2e3EgLFiLjcrmiB)jCdteZfKR6Wm2ghbuNRbTVeUb8fzereIiSXHy0rLboJHGAeckz0LicnujT6TeHeYGcVjyBuKrEd7wQC3ivjeV8Ce)K3(sBK5iJLm(fWzt5Nm(YXYL68VUN8hlN)))d

**Comment by mrbuds** [comment]
Thanks for the report, wago was converting the spellId from a number to a string, a fix is being deployed
