### ISSUE TITLE
Initial Game Startup LUA errors

### ISSUE THREAD

**Issue by madusmacus** [WeakAuras/WeakAuras2#3935]
### Description

Just reporting not moaning :¬)

1) 
Message: Lua error in aura 'Cast': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
Time: Fri Oct 28 11:28:07 2022
Count: 1
Stack: Lua error in aura 'Cast': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:838: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1889: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1866: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1159: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1121>
Locals: <none>

2)
Message: Lua error in aura 'Cast 2': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
Time: Fri Oct 28 11:28:07 2022
Count: 1
Stack: Lua error in aura 'Cast 2': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
Locals: <none>

hope ive not ben a pest

### WeakAuras Version

WeakAuras 5.0.4 newest to date

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

1) 
Message: Lua error in aura 'Cast': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
Time: Fri Oct 28 11:28:07 2022
Count: 1
Stack: Lua error in aura 'Cast': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:838: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1889: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1866: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1159: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1121>
Locals: <none>

2)
Message: Lua error in aura 'Cast 2': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
Time: Fri Oct 28 11:28:07 2022
Count: 1
Stack: Lua error in aura 'Cast 2': init
WeakAuras Version: 5.0.4
[string "return function() CastingBarFrame:Unregiste..."]:1: attempt to index global 'CastingBarFrame' (a nil value)
Locals: <none>

### Reproduction Steps

1. Login to character 2 errors popup

**Comment by InfusOnWoW** [comment]
That's your aura "Cast" not a WeakAuras bug

**Comment by madusmacus** [comment]
thanks for the info sorry i didnt /dont know :¬)
