### ISSUE TITLE
Weak auras does not open anymore in release game version

### ISSUE THREAD

**Issue by taori** [WeakAuras/WeakAuras2#3936]
### Description

Something has to be wrong with dependencies because now it tells me WA cannot open unless i get ace3, acegui3, getframe, specialization, spellrange-1.0. in the toc files they are listed as optional dependencies, which does not seem to be correct if it does not open without them at all?

### WeakAuras Version

5.0.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

no errors, just messages that dependencies are missing

### Reproduction Steps

install 5.0.4 into retail gameversion

### Screenshots

![image](https://user-images.githubusercontent.com/5545184/198600337-80c124a2-8a1a-4aee-83d0-695d1b91e051.png)

**Comment by mrbuds** [comment]
It means WeakAuras is not installed with it's required libraries, you have to re-install from a proper source

**Comment by taori** [comment]
i installed it from curse?

**Comment by taori** [comment]
@mrbuds  cursemods 5.0.4 has those errors, github version does not.
