### ISSUE TITLE
Weakaura Can't Detect Covenant Version Of Abomination Limb

### ISSUE THREAD

**Issue by CaptainFred01** [WeakAuras/WeakAuras2#3941]
### Description

If you create a cooldown tracker for the covenant version of Abomination limb it will not show even when the spell is learned. To replicate create a cool down tracker, link in covenant Abomination limb and it will not show

### WeakAuras Version

WeakAuras 5.0.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

N/A

### Reproduction Steps

Create cool down tracker for Covenant version of Abomination limb

### Last Good Version

N/A Abom limb was split into 2 spells with 10.0

### Screenshots

None

### Export String

!WA:2!Dv1tVTrru8A5wHyLi04MgLI4qurnhAHOOcjiXnVg72uCTd7ULuozp7Up7DiRNz7mZAhxkcQpG6z)ja5ZCYFeI4dWOviK4A)iKdCM3m(pQP(WSZ7))z(9EUuJkdQexj(nF2mAeN5ZZfrWNETcsUkHlANPOCM0rmUDVEsqvAoHfH8pHtzQWA1Bfu3RiIZtJ5Jy(JOzq3lwrwpUpKiirwpCKNurekNWEugvM44IFuotucA)(GqUXEILx)px14mWtMbPPZIHW8E9cqgIhxV5jnEwZ3kZdHHat5JcONpVtTQ(bD8dQ6fSw0jcaf55Fs9MnZ2mxcD6dmqqJ8t4JAZ66z1AUVje7(DmmvZULrl4Cmz7yJClYaiPqaKu)vKz3SAiFaLrm1ZUnPdclmgTw9UtSxpow6uCL4ntIFQMoImw6XqfLoU5yXhMLsgdIPgNOW20zDNU2x7CD9xonNTSL4KTPPloecwq)uEm8Nx7s8faems6pG9pmLgD5zaKvf9rKYZKKjtjm6aB6EK(dBCbqKGVsaS(QKpqVHlJZGI4CHvJoMUUqcieiwoXOQPRRFG7acL1qFF0a9d0FU(l07JFDEFo4lLKOm(csMHVdEqFZR(3STEJcKmelV(cEol(nBLvrbNJT5eccsE(syv2DSmTh94cmR7ixEr)GPRLD37jZU57yEnEkx8KsLkv(Tl4cP9Sqt3QplOD2TSmrKm30gIoLgRsCRIKxUiq0ZHylZxxSaw)JltNlSY)PCPI2BS(gZeCfwzbit3wTBvxVHalkJoZSkgztJY4VPlRaMk7Mne0xU73NtIXUcz3GGRu4RIuHL3iUi(ubjBYPlVSibgsL0WuO7YA(Dg9Y284wTQ71XTDqq7N6D8JECqX6q7tFjCNLv0ZVsCmsTttTFwqZJBv)Fk6NYh1qaVihyrJp56hS)dpCr1zem3CSYdtmegJlcZvkoR9qqGi4zg2nTGQBB1FvLn1quBDN5ceN)OvCsCnctSrpiHgDgdKYYwl8JiPWIRnPi7nTbWf7lGijmbO9tue3uojEORel0T9gKNQOoVnkLiLypk2msgTxOKY6Nc)1hR74eQqFYuBR7S9o34FVxxxJgiLtwfZ03vTSRNL2iEMD20ABYmHfsBAaUMfLtxJ103iBRv78mqKVLkj4RwCYCkBbegTZ5YfVhne44TXjH(18QxVL7l58bL0jDNP4rdxmjVtPF)pUlnoBR3FHZU14dfNVAKXK71wgxCLaoZdD9gzGZKhMtJNlZp6f1o09GVw8KqmH7r77iOmtmq9iPzjKYZ7zshCPaIqlpZm7tTBRV)EErjq0zh5nKKMdLNmKiOMIk72uM0S5nIInfpqA)7cP(JklIsiS(G8t2t)QNCs5d2)q7r5YtYeCeXPg7zht2t)ZhPFvz9VmJZwL9O56F99mCH16Ft)6jRAUD1V2cLQi9oC)d2)RQm8VF())d

**Comment by InfusOnWoW** [comment]
You linked aura actually contains a "Spell Known" not a Cooldown aura.
But in any case I think this should work if you enable the "Exact Spell Id" option, since as you said there are now multiple spells with the same name. If not comment and I'll take a closer look at it.

**Comment by CaptainFred01** [comment]
Yeah my bad I used the wrong terminology but even when you use the id for the cov one 315443 it still does not show while in areas with covenants enbabled

**Comment by InfusOnWoW** [comment]
Can you export the aura that you have? And do you the new talent learned?

**Comment by CaptainFred01** [comment]
Apologies it seems to have been user error. After a bit of fiddling it seems to be working now. It appears the issue I was hitting was that the premade abomlimb WA checks if you have the talent one, even if you change the spell ID in the trigger. My bad and thanks for your time.
