### ISSUE TITLE
[LUA] Error if open Blizzard Edit Mode

### ISSUE THREAD

**Issue by G1ZMO** [WeakAuras/WeakAuras2#3942]
### Description

https://paste.ee/p/Ten0p

### WeakAuras Version

WeakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

[LUA] Error if open Blizzard Edit Mode

**Comment by Stanzilla** [comment]
That's a Blizzard issue
