### ISSUE TITLE
LUA error in Automatic COvenant Swap & check 2x superior parts

### ISSUE THREAD

**Issue by Dusamavn** [WeakAuras/WeakAuras2#3943]
### Description

I use a WA for covenant check of 2 superior parts, it says there's LUA error. The WA I'm using is this: https://wago.io/kt9oOksQt (it was fine before the pre patch).

here's bugsack:

2x Lua error in aura 'Automatic Covenant Swap & check 2x superior parts': Trigger 1
WeakAuras Version: 5.0.5
Aura Version: 1.0.0
[string "return function(s, e, ...)"]:8: attempt to call field 'GetNumOptions' (a nil value)
[string "return function(s, e, ...)"]:8: in function <[string "return function(s, e, ...)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:548: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:713: in function `ScanEvents'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:885: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:870>

### WeakAuras Version

WeakAuras-5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

2x Lua error in aura 'Automatic Covenant Swap & check 2x superior parts': Trigger 1
WeakAuras Version: 5.0.5
Aura Version: 1.0.0
[string "return function(s, e, ...)"]:8: attempt to call field 'GetNumOptions' (a nil value)
[string "return function(s, e, ...)"]:8: in function <[string "return function(s, e, ...)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:548: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:713: in function `ScanEvents'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:885: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:870>

### Reproduction Steps

1. install https://wago.io/kt9oOksQt
2. go to hall of enclave in oribos
3. click on any covenant representative (like general draven)
4. that's it

### Last Good Version

before prepatch

### Screenshots

![image](https://user-images.githubusercontent.com/92813139/198822619-cb2c3b97-d165-4ea5-926c-e2cee038ec62.png)
![image](https://user-images.githubusercontent.com/92813139/198822633-2337c1d1-b959-47f2-8c05-4f67421e9b6b.png)

**Comment by InfusOnWoW** [comment]
According to your first screenshot you have even more errors, but his particular error is cause by an api change in wow and is not a WA bug.

The api funciton C_GossipInfo.GetNumOptions() was removed. You can either contact the author, or if you know a bit of programming follow the advice at https://wowpedia.fandom.com/wiki/API_C_GossipInfo.GetNumOptions
