### ISSUE TITLE
No aura for Feral Spirits Fire wolf ''Molten Weapon''

### ISSUE THREAD

**Issue by Shuyo02** [WeakAuras/WeakAuras2#3945]
### Description

I am busy making Weakauras for myself on my Enhanc Shaman to find out there is no aura for Molten Weapon for the Enhanced spirit for fire. Frost has one and Lightning but Fire is not there yet. Maybe its being implamented but i can't seem to find it 

### WeakAuras Version

WeakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Go to 'New Aura'
Click on "Premade Auras"
Next 'Icon'
Then 'Medium icon'
-> 'Buffs'

Then there is a lot of buffs but no Molten Weapon

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release.
