### ISSUE TITLE
Unknown difficulty id found

### ISSUE THREAD

**Issue by anyger** [WeakAuras/WeakAuras2#3946]
### Description

Can't open WA options window, it's print log:
Unknown difficulty id found.Please report as a bug:192 挑战难度1 none

p.s.挑战难度1 in english is "Challenge Level 1"

### WeakAuras Version

WeakAuras 4.1.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Can't open WA options window, it's print log:
Unknown difficulty id found.Please report as a bug:192 挑战难度1 none

p.s.挑战难度1 in english is "Challenge Level 1"

**Comment by Jodsderechte** [comment]
4.1.2 is severly outdated you gotta update your addon

**Comment by anyger** [comment]
I tried 4.1.2-2-gd4cf04d and it's same error,is it latest beta version?

**Comment by InfusOnWoW** [comment]
I don't know where you are getting WeakAuras from, but that are pre dragon flight version and thus they don't work.
