### ISSUE TITLE
Set Offset of a MODEL inside an aura

### ISSUE THREAD

**Issue by Kurnidor** [WeakAuras/WeakAuras2#3947]
**Is your feature request related to a problem? Please describe.**
What I'm trying to currently do is write custom code to change the current position of the **model** in a condition when something is triggered. It doesn't current appear to exist?

**Describe the solution you'd like**
What I want to happen is to be able to write a condition that triggers for the Model offsets (x, y, z) to move. Something exactly like aura_env.region:SetOffset(0, 10) but on the model is what I desire, which currently can be used in custom code under conditions in order to move the entire aura itself, but I'm looking for the ability to move ONLY the model inside the aura when triggered.

**Describe alternatives you've considered**
I couldn't find an alternative, other than creating more auras just to reposition models but that seems somewhat heavy handed to load one for each position I'd like to set, but I could be wrong.

**Additional context**
Specifically, I want the models to be offset differently based on which druid form I'm in, but at the moment without creating a new loaded aura for each form so I can have the model position exactly how I'd like it (within a 200 x 200 frame) based on current form. This way I can have one loaded aura instead of 5 for druid.

**Comment by InfusOnWoW** [comment]
That's a won't fix. The model code is pretty fragile, whenever we change anything in it, it tends to beak.
And this would additionally require new functionality in the condtions system of enabling/disabling properties, which currently doesn't exist.
