### ISSUE TITLE
Division by zero in RegionTypes/AuraBar.lua

### ISSUE THREAD

**Issue by Daemoos** [WeakAuras/WeakAuras2#3948]
### Description

We've made some updates to the Luxthos Experience Bar WA to be event based instead of being throttled every frame. We use a C_Timer to trigger a custom ScanEvents. The "Division by zero" error triggers when you go into a different zone that triggers a loading screen. Manually reloading or relogging doesn't trigger it. I even added event checks to stop my custom event from triggering between PLAYER_LEAVING_WORLD and PLAYER_ENTERING_WORLD events, but the error still occurs.

### WeakAuras Version

5.0.5

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```
15x Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:348: Division by zero
[string "@Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua"]:348: in function `UpdateAdditionalBars'
[string "@Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua"]:477: in function `SetAdditionalBars'
[string "@Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua"]:1308: in function `Update'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4220: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4219>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4314: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4276>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4436: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:757: in function `ScanEventsInternal'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:713: in function `ScanEvents'
[string "return function(allstates, event, ...)"]:100: in function <[string "return function(allstates, event, ...)"]:99>
[string "@Interface/AddOns/WeakAuras/AuraEnvironmentWrappedSystems.lua"]:48: in function <...e/AddOns/WeakAuras/AuraEnvironmentWrappedSystems.lua:44>

Locals:
self = Frame {
 0 = <userdata>
 GetAdditionalBarsInverse = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:480
 GetBackgroundColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:555
 directionInverse = false
 SetAdditionalBars = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:469
 additionalBars = <table> {
 }
 GetOrientation = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:512
 SetMinMaxSmoothedValue = <function> defined @Interface/SharedXML/SmoothStatusBar.lua:45
 UpdateAdditionalBars = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:308
 fg = Texture {
 }
 SetOrientation = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:501
 value = 0.052537
 SetAdditionalBarsInverse = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:484
 UpdateProgress = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:271
 additionalBarsMin = 0
 SetForegroundColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:542
 ResetSmoothedValue = <function> defined @Interface/SharedXML/SmoothStatusBar.lua:31
 max = 1
 UpdateAnchors = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:226
 GetRealSize = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:593
 additionalBarsClip = true
 additionalBarsInverse = false
 additionalBarsTextures = <table> {
 }
 iconHeight = 0
 additionalBarsMax = 0
 rotate = true
 GetForegroundColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:546
 additionalBarsColors = <table> {
 }
 targetValue = 0
 iconWidth = 0
 totalHeight = 30
 totalWidth = 600
 GetVertexColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:572
 horizontal = true
 Update = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:424
 alignSpark = "RIGHT"
 SetVertexColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:568
 extraTextures = <table> {
 }
 bg = Texture {
 }
 GetTexCoord = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:185
 align2 = "BOTTOMLEFT"
 GetMinMaxValues = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:456
 SetStatusBarTexture = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:529
 SetMinMaxValues = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:438
 SetBackgroundColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:551
 SetTexture = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:560
 spark = Texture {
 }
 GetValue = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:496
 SetSmoothedValue = <function> defined @Interface/SharedXML/SmoothStatusBar.lua:41
 GetRotatesTexture = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:524
 GetTexture = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:564
 SetAdditionalBarColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:489
 min = 0
 SetRotatesTexture = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:517
 GetStatusBarTexture = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:537
 OnSizeChanged = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:431
 orientation = "HORIZONTAL"
 fgFrame = Frame {
 }
 align1 = "TOPLEFT"
 SetValue = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/AuraBar.lua:461
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
}
(for control) = 1
index = 1
additionalBar = <table> {
 width = 130
 direction = "forward"
}
extraTexture = Texture {
 0 = <userdata>
}
valueStart = 0
valueWidth = 0
startProgress = 0
endProgress = 0
forwardDirection = true
width = 130
offset = 0
(*temporary) = 0.052537
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*tempo
```

### Reproduction Steps

Load the WA (tested on a non-max level)
Enter an instance or teleport to a different city

### Last Good Version

N/A

### Export String

`!WA:2!1YtBmYrYvDJ37YLm(cXEVCoxC(QVHSoZC3SZo7A7DpV49m7S7SENlR3DVzM12x8LmBptxZ095E6UVU7z)WxSIIjemiIcSabuafGnqGFa)zfiabsGoHe8ZctiYcHeG)j)bjZFq6es8QQ6pQU7A(yDU0YU3UR6vV69E179Qx9QQNuThV74kJ7y98k2YDmnARR1r1DYMix5jNDCL7Fo793ODBhKR(tBVdY2rZ0OYrAgTnT7k7cVCUJ6yB2ZIbZ2hbL3cvEhKHRZ2pw2OLQP9k2YDr133c1S2svlxE9dKn0yTD2sDL1mwPKluzjdtd0du6ztRPbPiBhultdfN7HKDOia)CVh5XAU2iJoUQpBvhxzB3vWNe)C4pk(Nc)XG)EQNTzBndnh1ef7y2dOTMADTmTDNPNTU1xq111Yz(PMAxGZlOzo1A92Zv10P8EqNRHmAHkjBp15N9OMM2ki7Lm1nTF9uPsn2HSckR0bzD6AVtpzBK0k901LUHQMlQPdQliQQE(cflm9Ho9Awf1b4jN02YTimNZSLak0nn(0PXJN(qxZwEc2xm138qpuxt7oON5aQOTcieAo95N5sxA2h0uU1TvSnTyKYyJn2MJvSWfFSMHlY2qw)6m840KHe1JyJaBAcamt9n289yLZgS(iwNIBaIE7EBvztGxmCT3JbtQMertLLp48xvERlu3DV3(O2eaHHazx5XMPNMYrZn96x)67uu9DMZQjqQT16K(qY4MgLxt)iwFwYJYTovjDT7ChzBfP6MM6UAwz0uSoRNKxAsPqHV0vjSFjfKtlRzwYgj7IuKAUVKpSNtAzzuxttN07U7UfC3vZTLAb3DMsNv)dK7b)XEdlgDus3uw5623buZQO4CIsowOwNPA3EajKUKdiUpd(YPR2sx2XH8utxzDqqqE060CYjM8r9EU2AD6aI7ZEUd6z49sABVh(M3dWUUo0pPXNSQmOuptPEWqEtlD59bndeXaP5QizDx1dvqn71Unr)2E1YRT5kBT2JaDgki1Gk027OglTyT6nQvFXQ1dQAtBeuv1ABwET1QAaeMtAp10kgWa3yhAtv6iOTkvnQQtlGJg7ahKEBQcXHL2OE9nU2ALxP(478dV54To79V8bAWixdhnfujs5aT5i7sSjrQ4N(m4p02hzc6Qat0sxZABCvBcV1u2g)rMfNoUfh(0jkz8eLSf(l8ihyq0vDtBZo2ihNTXVa(mLUJPz3u4tKY2fThqbOQ1m11uWJvP6UAkUQFJjoKqQ1O20Po0Xs2(23GuXlGFLupG(AvtxQVKuwNQNdArL3UNdOaHuUMMHA8IK3tfFw8Nc)Q3zh8SwBw2qUPUMrhjxvnhPD1al7oA7GK23ShuesYvRlsIowQij7YGshgw0LmTLCH(vNuCx59yLwaV9yZCB0(pI(gPXts4k8jB6A2PJoYgiMLbT8TlrgiTo1MmmxN0l1baHr12YGI62eIBPrI4a9pdxjndgqT6zt0ALCaXliri0dUJ1P8ELJGWA43EB8TbNASQcPbC3TBtB2JDun3DplvqYZ1ivOrF61iShHYOT6Cs3CZPwfaZV9eQV9GO(Lm7APJiw5YgksvrKbhjsFiXnHdtGJKAA66A2vYSn9noVgGpBFg8D6b4WMINym4NiSVoNFpfHnT(ee(uZOLhCuunjrvpGFpBnacPkbGi9geyCieaURkdnVhblGIaDKpSPVaTPaGeUb0(KOIowREgOvanJCByJi(ScB1RuLuSuKXgIKYxodLvL2ePTQa4cp1rBzjVK1Rwj7vD7uvw3svEm8NJmld(t)Dpd(KpaCMqMrH4FWqXRaqqJyfC)ZA9sePwd6n2aqdRge1Lgw2OwAeQymRptcyOmR3l4NZ65P1bEJnjJGTOMPLweE9qBIjkIi3lT(gRx(bm)S30BUNh4HtdxQZXn2Q(AvwVS140IDuLvm39nzG(PFkRZMGkAnDijKRF8HY(GjNwRgUQGix1uxz)hZGsBpKcLs)6VhTGDaUTPoABRpPauXEOkbJkheq1wNAfBT7aAfYkKzlLQxpKJiZV)sSx3f8AFdBzR7DdVhEeJb99txAXTQVH1NTFCa7Tuheu)mt0AApjPN4b8aYjZcdJXRyUGeoSY6RxUAdQVFADT8d0ym8jTbTdsHEJargSozKHfVchJj6iEz1AVFZLkVE9YvV)eceHgbdv47H)5WFd8pp(BMsG2NNJSBUz4q7edaiQAmnwYQT1nnTX)k4Fv8Vg(xh)BG)ocAiOK1kEdX)r4FlqIoJ1pDcWTrKWxbFz8Kt(bqon160WOx3MiBV6SoZInBAJ2rdScwt2UdADATowsc6mIpk(E6ZLagQpkEqkmqAob5G)tSE5eTGoDgaTcyW3vwp0Yp1aawaQX)IGvAMKshpNNCKn(x(RJ)wBlqG7JD(rhbIbFWcW3bFg8Va((4F)Xe5LyMq4oe)9XF3u4FBQXb(359ygdm1w83ZZka)7kymouZrGy6Lga4ScAYg3hOYtseF)84)Gigm4)qym)l0VEZxs7ZV)vwVYqbnIDaNXd(p2ZU48cqYmfC7NZ1(B0X0VdOn8V3B9uwZmu6tG0E4mLCGnNQ1CI1EgA)mg(pde9GYartT4OHKiQT5gIGicWNBO8e1p92uBS8Jg1eOfuCiusszmXa9VegJeBqD(Ogum7gRpLq1epi)24dEj8FXy8gFhXm(Qw5QRw3AQJXyAdiARtlW5rGwjxOls9hkVPvhfBeyzCDBqICVQbe4JnXxZ9)CbMM)sWFbZtrsQ5cLuGX73AB8Fliu)RH))3dwxepwWWj(FiL1NFGJqr8B(3aT8q8nP2QGBpM56nf15xiSDed5lWl8XxN3Dh)09EruKpfm4J)7snA85fhn(e)pXXdvPJ8r5JFe(bEu7fJOQWwilRbH0n(hgqLNvqihljkKd8Fo8QhfjItMnSraBa0kW9c8VtdaUEOAeaopJyxFJnjHyH)x8yNzJi8)3IWett4bWq6(FY4E79LC)JqX4bmTP3Y86p9CpGEysV)vpcAUie0)UqcQPkIKQWfWtVdgw(S5247OIFNTXUBJv3gVJ67rxfotF5ntHZJN8itYs0yRk)Wv3OALV0gRxFX1ija6fJUaoPj9ZYZJOyPKoYq5AMkOzwC5LziUolVawzRqs(vB5wO3AjziqtJoq7FRTQmz4BtwJ0GJOnBvnffKr11lFDyo9pVZJdx)tqCX0CQDpyPESsw9k)hfjxBU6v(rNHC9MREL)7Vg567pM1PJKQbcfctoEo83)qyj9E53kIG4MP8idMSRezvrQ0uzWhQDHXkrks9ifnhsAgiPa8f)O)G3cpt6dBbrtB2LW9wVD7Eg0mkMnxAj4s3SLSUKR0csK0Y0azStHqODOGqVzJajNHKBHwtNNCFg69ZtVFb69lsVpl9(CPbzFvkvRIFE8h3wZGKVsK698YfKZ8V(yRELh9y46)5zsng5L)RVe56RT6v(Njx)Wtm2Rh8ia54KRNfa7)0878Z(up1tH)mZI)SNRjJw37flZ4dFEGJDsNoGXUkYTM8oiLRlB7aqiusCJfRXllCiWtYqZ7ExkqXQybc8Hcj4LcEwoSQcEledXbSqhi4Asu6rBryXqtlMOr6YKO2J1eVcHgSLHg8u2mSChMjxI2dt4LO5SYcA91K3BaiGMgDA2ewOpLtsRf83SjBlz2V6K4le0(O1jK3jGSMV3sbnpSU(k6i1YYywvwwAeijtcta64TiikaGYoNAglRElqfJuAHtmgaKMdf32GuEnp4JHGxBbjqH1V(vmTb3DYgeYJHuOYyLKlx60mTyOoy5b0ClTMzNYKKnJiQ8l1WVScIbbyrHveIxAfvwgOhO2kgkO9sGxbGa4nWCtlhV8ZbPJA5M9vZhGCOr11C1raG5OIwwFxJcipDTp0ZIkLVZYjfIHkou48tJxu6UItq5q7JbQhcOLvfjRSpWB1bQVIruKeRoEc5DycLC(8DBzDhKuunNTSuGOrFd2sY7NhkynYVH0cIhMIa47eGNICLgU45yveM3Yev5r75bAFxzBWPexDW43BedCUbYQEnGrWjkvKaIIiofegMjcQatpT28yJPcq8Y6QImcAUhHjcqpXueCcr5iPbWdtVrLWkMbysGoMVsm5YJW56Ri6(8Gg8aWb(n71KkgLWz8(GKBHktbUKs0dE9saIe2nbKpTN8F6vIoo3x071fXSvIqCcSycRxi5qUIOiY9YaimeynjexXuRJ86GWNNUHO39FoI(tGrCc5z0Q7dVffObq0rScO64jgzfPVsGmupSgj2ZwBAA1ZQbeDlkBMflT46lVX6nEJTkxREMrgYg3Os9vBuPE5RvlJy1CFYyjtGom13u2aP3G5OJGBusTaF39Ul2u2qX04n8MGoEjjDZ3xn1HrezZfb8y9exT8d9dW3n0IWAORuG3Bo4FjVKxksC49yt2zzIlOIFLS(vtTWZLiQJQeCsqK0ltBvoPPO)ngrTcDPBEXjf0)KWYYlXwwxoFvj6waE5fKU4LIoI41HzUS00DZKuTNr4k5LuZlbCfnidvzx6(E3G0XLGqYU9YM7Y624l6GreeMmZekkstOQknr3UzKMCs495Ny15N4AZprTmH9hx7TKJiv3jXmh7ibeDr62DLPygPcfGsGEAN(Xfo9AsO)3nap3kZetSC2BTSYx(k5Y8LHQuOgBeeMf69Sk5iinZetNH6SltM8rAQsFAQYaB1QzV1QQ(TklRzayQKhYf23QdUVvhowuhicUw2BDTU(iG0HDd6WOa2LhWUIHPw2BvZHhzo9bzo8a6efM7gDY6BNFhYMvBjRz7KLm0LJFoBIYL78DGYZE78s7iyc)jNuQkQlSEujxBzn6(ldlyTfYzQ7GSnH)4SF3MM6orcw1LCCn6M1dZz(kt48YfF5m5bPxoUIGH9vvbHcRc4M08tn5xntUywNGJ1BJSRwFt(G)dle4rdnDo)iSLHaeA4stigaKaj5W6s6iz76COowuKGTUGolInFY6NFjzJwKLymayGUIqV9FMXbYarfnEl5kkCj4ddt3HGDXSvuruwbtCnmA21UhAaTIxMSe1nODH1r7sFiBXcxmp)mxj4v2Sz56ZenCPNjWzvRPHhZWwij1rx01sYSFAndbOIWmffLYwmNNvvRZtlDc)xVa5v)xUi)lZY)YCEVC3etbUue6lGpDiZZY7(NKijsAKijrIKcjscKiPpQ1C8UKjUbOHjawdHjFHucpQA3jscSyNOSW69Nbo6uY8R9Xr06WJVg9qv6eY7Sofcompcw3FUirTX1Br0pzdqbhTdVzB5dSLcb4ecuhlWM6mBMjCGru4w2jCGXuj2u(C7mmqAb7iilAcXa5TfOdceUDcMbMa3Qu9PeK4etWetasITximefm5ygcFmXe5YWMtcie6yvy78668stZvNODRkaSOcFIpJ(naavdQs3ktSJRemzuFcsLaI((0y0Dke8YGxug1clMak4uqPzmV3yjC37m6qgvbweCpu3KLBlYXBInLDif8AqOoWfviYelbvnfTkIOG0QKdS(aMRpOlZx0F0iTOLdLq8f)iujs(rDTetkeC(QMx6R2Af46sZvSirB4RssUp7exXQ6cRCPIRScRQmjursObKacgXftdPVlTZNVIEu8IZvdWWo09z9Wtb48bEoC9Z3z4alhffFHTCik8qeoFu3q9fzdI9IF0(IZGmF(HDSh8HDn3MgfVZfhqGOPYcCVcZpe1VhmzrybeVmWmhPJyvbtJKoIcgmNs6iYnycMO8tR58dUeiXdumBWOPTXN(C4336)Lpyj2PJTqtz7cT7uawJ4vTLviBo1IKtjxOSsCdMNRbzZWTtw5Lkw485H)Fr42LMJ86CttE)c5NgIy0F4)yJv2PFMUFuzJ2dedIO1g0H5NMLZv8)324XpZJuHv83qwxVrhDZDDuXl(9ohU0zWV)jWlD)p5JyIQL9o)9Na)64VO1P75GA0bzGS1AroWIByS9dijLVg5WnVoSOWu43FVtVEqybaYPZM7KxIEgLZd6sfYDmMBN4RMmo6732)GtcAVKaO5JqS)ZNhqf3kdDLhrFNS5n(9dlTT3nAwyivfXur4EjXV9tCXCYGvx8MaioCIyT194TxkX60rFxu4guybu41uUT5HpVWbodcspCyTJ8MEXN4Au72HZqLxIBgrspKN(VKZkfHIP9y8DhtuV5hn0cI2nmrnGp2OfcA(KHDCc4zhopwgEV5ML3tvMCOhPljqa(dtRyImnkuyXL(qr5EuqBIL0rXjJms7smZFIzijHpm8nwtyUP51Q513MCeq4R0F7GOrXXza8JFFeyYmAHjjy(wq6oQbGcyr8(U23e9h1IS)SBaQgE2)P2KKa54q9usNF2IfhPDoG1C)q)dm(7lhqU4c5UfstpBqRMIHUCcBvuFf0gYBWoviAFzk5N7jAdbIMmGyZP8UrAU30jK8iKpA4DQYgDcYXq06S8(CxiNTDsSyo0KZNjkq7iR3JBag8uM0Sk0dv((VqLjNuAlh5M6ijyglnYdojnEamXLIHaMGZB7GOdEFL5JTby8Ut5EloybEr9Fmkaj2nMyeQ4DJjkqdy3yIciNUzW0uP7VAi3B9fmAG0ranWErqw(ZYbhlRUtozM891TAWZ9beVoxyh5dtU891JAWZ9bKbG(ayIH(O(W4ERVGnGoHdQyDtyUgcNkpi99zd1UNYV2CGFdybZSzUfIRavyHOmQZOJbsPRJvmg9SmogOZ)OWKeB(MrhdK1k8ywiqegAqDmqzOLNqKgXoDuqRW0gjcZzJSPXbJ)5gPEjYlYkSpYvzD)VDXetnqUExHZIbEKxkYhoMKGDUMCPOz7DKiGzjABAt2K7y(b8VOFAKj3kA(R7MF0PV4FABFasHXwdilkjbFTDEHDMiSvXy3KEglhG3)JReW7ld8do(w8eBdG(bv0S)4kSsga0Dtl(T7oG9bjXocKnsurc24f)DlzX2Ui7StNp(U(WFDdK8Txe6kNc1AjBW(feiBM1UXInkdRNQALYRVu5gBT5YlwVC0CGjOF9pFRj2xhscyizbINUzsZ4rLpsb8rZFWOfX3Dhov6T7qSpVBhRxqiVJ3m9rSu1q)2qoIsK9OJmvBPIADB8QpisgBEKd9plzAQRyURH3XhMK8Mt4JisIHWV)JzVfeE4EpZtZyAHE58YwxA(yhdLrEhBzscbcgwx7wSmJN5lhkvC9I9L9PI5V1WE7kfxyNdfZl59bohEkYh1UHp6GH2nChs9StKBu7IWOJhAhqxz7taxenc7H2nvdIF5jwGXhc0tu)DCKGCRmye6lQl7FmymVWWo(90XHLcxlZq7h2CVpXmKFGGh7(54Worwu1Wnxd(47FI5kUq8EI6UrJ5sF3hqYbUJFcV3gVc(Q29mO(OXF7dCcZe(YPXNe)(E5rFd2xgX0NaV6HqV3u2vAnZo41pbETtCp)FKBgF6dii31wU1T3(C4sPXlD)NNK49hMk12pm1jizx)K)PbZz6LsDz7ottVpd9(5P3VqYuTpGCKYFk18(2b63NjWqsr8OMBCVdPJLTMHBsgj6M6MzZ1w8nlxTb9ZUTY6xTXn2O6AlNrAHfy7QqIDQJGisCozj4k6QPzbmvG)Ntbbhv1(8fCuSVaf8fBKmHW97JZG(3(cf)xGbNWEO5E0N1PC(a5R4FNgfhiK8Fsgdwmi6RVO4WP74r0(eMS5lVGO0l2)tEu2bSR3Ebh6R(Tw5RxEniQR(P4L4tejySisfjH)NqFTijeZJ2y6W1vtFCg6fP8gr6YcJLey7IRxRYgRZKZ9ti75KsZa4xFHf8wwXobJVTvaFW3oW52WA3pjgT4OICd2yWttAy4luAqZqr2ri7)eIm7Ro7fkwKKt8CdXh4X2BK)Gl7yKV2gx1FLAHdRecnZwRxPEJqGwA1fx)QL5DTtDEtSJGsc3HoX2DXpK2cPO6vUw5gul6LBCTAxnzxfZT5GCzsiSrY6IG2pGnFogh5Xy(XU5MjhmeyJXnVxyOdtkywpHQWbT(YI8h3NniM5UruFWNxUbpxYX5JV8vciK0hZj1hrNK(s(n2So4zR2GczzOZ)nS9iCaZhcMAHH)wXPc9h8qyXxz7ZxPZinDzITjl(rzA4AN9Ddup2(V(GX9vKZX0Xp)tPJNehaFpm1tB9Bkm(vP4(gLe7mukUzRuS4rKcMbD1f3Qgrrts8CQsX899WuFi8Qpm1hgVkzrmpm1ZHF)hM6Jbl04u4V9dt9rEyQ0pm1hF8Pjlsba75jRMbwTYdtD6upm1lST14EhWl2VWHWQz0Az9LILqppPHW8vEColpGK060KFSm3b51FKVS(XiFo8VnTh3bbe3S45y)W)Tu4xo)L(bvz9YRwKU4k6VihQ4fi)ooIFn69RqUtRKcPk(NHw88NGUuplKlSAnxDKk7xRVgMWkgLDnTh)Y4Nf)Hj)mg8))d`

**Comment by InfusOnWoW** [comment]
That should be fxied for the next release.
