### ISSUE TITLE
Convoke the Spirits ignoring conditions

### ISSUE THREAD

**Issue by derickso** [WeakAuras/WeakAuras2#3949]
### Description

I can't get any Conditions in the conditions tab to apply to Convoke the Spirits

### WeakAuras Version

WeakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a new Premade Aura (Icon, Medium, Cooldowns, Convoke the Spirits, any option)
2. Use Convoke the Spirits
3. Notice nothing about newly made WA icon changes

### Last Good Version

WeakAuras 5.0.4

### Screenshots

https://i.imgur.com/3hUd1TF.png

### Export String

!WA:2!Tv1tVTTnu8A4fmmbuGf32G2HbeJwSGTlbDolbB90SCTBsHRTJSsB3omBkjAj2itQrszh3ldZRBn9Q)emOZBx8NGHCFaegd9dq(iKB72EKYoOPy6Ge57X3F(94V3tfAuAyPGsbNEVmIpJ2LLY9XF61wGsLrmE7ejHrfw8jThmqGL7)Tp6ONEn4zoI6d67WiuPxT6TCR7SWNXIdyJPDhtsW9pB126bH4ioY34P9CesexA5nGqjIilB4J0AQKtcdXCXpSfF5Y3Ytf4wOH4(ZqPCefwj(eVD(MVC3kFnh8ABA8K(o4ryi(7JrXYi7uWvEjXOjyEMED9ticPiAXqK0pcl6gXg3MEMW8PkKoJWtfj444dcewoMayDUi1Z4ZoC8aYjoD7uVzZlf2nDaiCEVAv762RRBvhxB5KeSJobRKfG9a9UGa((1B2PXrnNLsxIgRTuxFWcoKND1ruJRKBuJrhXogxwgHl3nHWjsHAthtkPkLCNAlRFL7WzHCSqu(Zng)fjRdLMEHykMt8Zrv)fxzBMgKvJhJMiMjwfWBV2)gPUN18aI4fPud(RGOtswhzw7MNPpHfG)JRDbCTI5uu8tHlf4EB8fhJXjvbF5lDqWnz0meLmuVIUN6JACggjWDLCmnug9HQnTPmkEraux0NONUkXfyGFfiMQpQUkP2XEiIqBOQagO2r9vQDv7bFTEFjqLvGKAFHJYG7chCOMk9GnuBUa26H8poKZsPbNEZKss8jYEIieu5EEoNTqYDmcnVgW4qw3tSCHANzxQ7UFMi5JFhZRXIz8hxOqHINNlfhpWW3TREKB7KByecTjmDzW)zKaGcwf2ErEGiNGdmc)5f59kF3Y05mJ(xKkKKbtuRLXzsazUGq7wTBvxTjhaL(mzMd6BsJIWZSLiGkt(4gCYllFykkaQkOYUUxb4RI0cJSXmEWZ4OKPpB5I8eyerq8IX9xI53PFoz9dA1QUtp72UUTFIZbpAF3fxg6UKxIVZse98RehTwd7V9rUnpOv93UimMnUbh)JPyQ)KoFW93UYU5OtRyU(1kpmvVrB8cVuPKrBpcZHg5mT4Mgs1TmNFfYMP3u7YkZzqdXJwjjYwRmYeD3iI)XuO3POXIU(OyC(YMeq86Mayd1fmpYlctcJKhAhZqbJSfaq3WzyASKyDUFmsiGAuqpDlWwEccnmg)3Qqlpj4sQCdv4g6gS(26da7SskP7sVQH9Dm71QZ0AZTnkJBy0A8BRhcp7sQMATKBUAoQMH8qIabxAbrZj0CgmyN1f5xhn4qxU2jEDR5uVEl7xYydlOs6Njz(JYBKVDHF73Vlji5w)pdFkxHFYYX8)vQ1FQhZBaXQbrWObO3h33zSMwFyLusW8hh8eH87NC4dR3YdY8bKqloHQdgCouCseQ48b68cgoam1Iz6zaeZVcEWwoWyz)J3ZzekofxC6ieNOrxYTiuHEuRpbQooyH5Fsc11xJ7hHOHWpc2s9Qh3P493ExZRIfNMWzaZtoXX0USL6x2t9QIQFnJrxL9G5Qx)EgMBT6u1BU0cB9Ot11lQE9dGZgb6(j4BF1P6jpBVZ2AcJ2jAAN2WPRUE6REJryjHZUBdUT0O)55)3p

**Comment by InfusOnWoW** [comment]
That's because the premade auras is already set up for dragonflight. The aura is restricted to be loaded only if you have convoke talented. You can disable that on the load tab.
