### ISSUE TITLE
Bug 192 Challege Level 1 none

### ISSUE THREAD

**Issue by Blorgie** [WeakAuras/WeakAuras2#3950]
### Description

I haven't been able to use my weakaura since pre-patch. It has been giving me "Please report as a bug:192 Challenge Level 1 none". I have tried reinstalling many times. 

### WeakAuras Version

WeakAuras-5.0.5.zip

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Open WoW
2. Get UI error

### Screenshots

![World of Warcraft 10_30_2022 7_24_41 AM](https://user-images.githubusercontent.com/117018218/198878343-0f644ed5-afea-497e-855e-2127da663d7e.png)

### Export String

[WeakAurasArchive.zip](https://github.com/WeakAuras/WeakAuras2/files/9895801/WeakAurasArchive.zip)

**Comment by InfusOnWoW** [comment]
That's a very old release, not one that was released after the Dragonflight prepatch.

**Comment by InfusOnWoW** [comment]
You should try installing manually from https://www.curseforge.com/wow/addons/weakauras-2/files, and make sure that you are installing into the _retail_ folder of the right wow installation

**Comment by Blorgie** [comment]
Thank you very much, I was downloading them onto my external hard drive, and not underneath the wow folder on my /c
