### ISSUE TITLE
Auras referencing other auras

### ISSUE THREAD

**Issue by Geowall13** [WeakAuras/WeakAuras2#3954]
**Is your feature request related to a problem? Please describe.**
Creating auras for multiple specs I will often have separate dynamic groups for each specs. Sometimes multiple specs have the same ability available that I want to track, but wanting to make placement of auras dependent on how many abilities are available at any given time, I am forced to copy auras for each spec. This makes maintenance harder, as an update to such a aura, will have to be applied to several auras.

**Describe the solution you'd like**
My idea is to create a "reference aura" type, which references another aura, and acts as a copy of that aura. The only difference would be the load options. Whenever you make a change to the original aura, all references to that aura would reflect this change.

**Describe alternatives you've considered**
An alternative to this could be reference by optiontab, where an aura could reference another auras Display settings, Trigger settings and so on. This way the referencing would be more modular, as you could reference just the display settings for example, but not the trigger settings.

**Additional context**
An example of this is for mage, where Rune of Power, Shifting Power and Meteor are spells I want to track for all 3 specs.

**Comment by InfusOnWoW** [comment]
I understand the problem, and yes there's a problem.

But the solution would add so much complexity and is specific to your use case that it's not worth it.

We do plan on making dynamic groups layouts more powerful within dragonflight, and that might help you.
