### ISSUE TITLE
WeakAurasOptions warning in the new native Edit Mode after opening WeakAuras interface

### ISSUE THREAD

**Issue by Hazno** [WeakAuras/WeakAuras2#3956]
### Description

Upon both entering and exiting the new native Edit Mode _after_ having previously opened the WeakAuras interface (`/wa`), a warning will appear stating:
> WeakAurasOptions has been blocked from an action only available to the Blizzard UI. You can Disable this addon and reload the UI.

This _only_ occurs if you've opened the WeakAuras interface prior to entering Edit Mode, even a fresh install with no Auras created/imported. Reloading the UI and opening Edit Mode again directly does **not** show the warning.

This occurs in Retail, Retail PTR and Dragonflight Beta. I've asked other players on my server to reproduce it and they get the same warning.

### WeakAuras Version

WeakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

11x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAurasOptions' tried to call the protected function 'ClearTarget()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `ClearTarget'
[string "@Interface/FrameXML/EditModeManager.lua"]:1496: in function `ResetTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1531: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1462: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2657: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3159: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

### Reproduction Steps

1. Perform a fresh install of WeakAuras without any Auras created/imported.
2. Hit Escape and enter Edit Mode _without_ interacting with WeakAuras.
3. No warning appears.
4. Close Edit Mode.
5. Open the WeakAuras interface (e.g. through `/wa`).
6. Close the WeakAuras interface.
7. Hit Escape and enter Edit Mode.
8. A "WeakAurasOptions has been blocked" warning appears.
9. Click "Ignore".
10. Close Edit Mode.
11. Another "WeakAurasOptions has been blocked" warning appears.

### Screenshots

![image](https://user-images.githubusercontent.com/6724776/198916517-ef5c3d82-940a-4a70-8287-07c2d8e217f0.png)

![image](https://user-images.githubusercontent.com/6724776/198915999-4140a391-a087-410c-9857-258f155f8b50.png)

**Comment by Stanzilla** [comment]
That's a Blizzard issue, nothing we can do about that, sadly.
