### ISSUE TITLE
can't import/make new weakauras or even search

### ISSUE THREAD

**Issue by Dead-Wanted** [WeakAuras/WeakAuras2#3957]
### Description

![WoWScrnShot_103122_081754](https://user-images.githubusercontent.com/114364369/198936696-10b3ef82-b47a-494c-9308-6a89bf70fcb9.jpg)

after login or reload there is the options on the right side to make or import new weakauras, but if i click on any WA its gone, and the search bar is not there from the start.
also tried to delete all weakauras files and reinstall manually it didn't work. 

### WeakAuras Version

weakauras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

Message: Interface/AddOns/WeakAuras/WeakAuras.lua:4043: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4043: in function `GetTriggerStateForTrigger'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3217: in function `SetAllStatesHidden'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4147: in function `UpdateFakeStatesFor'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4126: in function `FakeStatesFor'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1442: in function `SyncVisibility'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1468: in function `PriorityShow'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:729: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:698>

Time: Mon Oct 31 08:16:07 2022
Count: 1
Stack: Interface/AddOns/WeakAuras/WeakAuras.lua:4043: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4043: in function `GetTriggerStateForTrigger'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3217: in function `SetAllStatesHidden'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4147: in function `UpdateFakeStatesFor'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4126: in function `FakeStatesFor'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1442: in function `SyncVisibility'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1468: in function `PriorityShow'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:729: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:698>

Locals: <none>

### Reproduction Steps

/wa
click on any weakaura
can't see import/make new wa, the serach bar is not there at all search

### Screenshots

![WoWScrnShot_103122_082729](https://user-images.githubusercontent.com/114364369/198938651-47af0535-5c5c-4861-9f9a-f2b89ebbb483.jpg)
![WoWScrnShot_103122_081754](https://user-images.githubusercontent.com/114364369/198938681-6e5b001d-e7bb-411a-8a29-20e746f654d9.jpg)

**Comment by InfusOnWoW** [comment]
Can you add your settings file to the ticket?

**Comment by Dead-Wanted** [comment]
I am not sure if you mean WeakAurasOptions.lua here it is
[WeakAurasOptions.zip](https://github.com/WeakAuras/WeakAuras2/files/9904861/WeakAurasOptions.zip)

**Comment by Dead-Wanted** [comment]
here it is 
[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/9906394/SavedVariables.zip)

**Comment by Dead-Wanted** [comment]
fixed, i removed this WA https://wago.io/HB29dQYlW/16 then /reload and now its works fine <3
thanks for the help.
