### ISSUE TITLE
Custom Function Load option

### ISSUE THREAD

**Issue by jamby** [WeakAuras/WeakAuras2#3959]
**Is your feature request related to a problem? Please describe.**
It's not necessarily a problem, but I am trying to give custom options for things being used at all. And for that an easier way to make it so I don't have to add another trigger would be to add a custom load option which would allow me to just check `aura_env.config.option == true`.

**Describe the solution you'd like**
A load option that allows to either check for a custom option that I've made or a custom function so I can check my custom option.

**Describe alternatives you've considered**
Making a trigger and then writing a custom function to essentially check for that custom option and then any or all triggers, but that is very cumbersome to add to a variety of WAs.

**Additional context**
No other context needed. Just want the ability to have a load choice based on a custom option I've written without adding a trigger to everything.

**Comment by InfusOnWoW** [comment]
But then you are just duplicating a option that already exist, the "Never" option on the load tab. What's wrong with telling users to use that?

**Comment by jamby** [comment]
I would argue that it's not duplicating work. It's adding a feature that with custom options you could toggle on/off without having to go into every single one of them (since you can access the custom options from the group even if the group isn't the one with the custom options).

**Comment by InfusOnWoW** [comment]
Well that's too little benefit for the complexity that would introduce on the load tab, and the amount of code to implement.
