### ISSUE TITLE
POSSIBLE BUG: Shadow Priests > Psychic Scream > Action Usable...

### ISSUE THREAD

**Issue by Sethadon** [WeakAuras/WeakAuras2#396]
WeakAuras 8.0.3b appears to be working quite well in BfA Beta; however, I cannot seem to get it to show a simple Action Usable aura for Psychic Scream:

dSdQfaGAvaTEvLQDjkfBtfPzQc0Sr5MQiUm42uXJfyNuyVKDJQ9RQ4NQugMkuJtuYFfvdvLyWujgosDqQKMgfLoMGonIfkjlvfvlwvSCjEOkipvzzuPEUutufstvOjRknDOlsrXvvvYZuP66u1gPOYwvHyZiPTJeFuuQ6wQG6ZsQVRsAKIsLFlYOvvnErXjvr5SQaCnkQ68uKvQQuomL(MOuAfQOgrgH3pnmlZQ1AzLnhF4haT31C0E1EvudHmO7ljch1QUfJ3orlW3yYjczqTpF7Z308CSqQRHIIAOjAqRrl6BnphOaCuZ6XKMVHC7tNkpNKEbvPbuaoQ5Aass8pU8vBFyGw7FakahVuaQKmA7Izo4b1kGLnAGXmSoG2rsK3pUuLyOMVH8MgymdRdOkT2)auaoopvQKmA5hY1fZx01ZJA9F66nUw)NU6k7Q1uR55euJMznbfnFd5EobvLwtdmMH1bKrwHUDluZgGekqSqQRHYjPxqgho8ynlN4yrsIROwJ2cQOgAIg0OlqdOgDbAa1OAFbHAowcxrn6c0aQzz0)2lEwdc1Os4K(xrn0enOrxGgqn6c0aQr1(ccfQHfsDnuuudnrdAnArFR55afGJAwpM08nK3)PR34QsZ3qU9PtLNtsVGQ0akah1Cnajj(hx(QTpmqZ3qUNtqvPvalB0aJzyDaTlTPGFsWhxwqbSoA(gYBAGXmSoGQ06)01BCT(pD1v2vRPwZ3qobbNXsOQ08nKt4uGsd6rRPbgZW6aYiRq3UfQHqgm8sIWrTZpl7ZUO2pqQ)rzC)unwY(QOgHxxsEAf1C8mKOOqHA(gY5afOOhTaMTBf1AcVMbAxo)mZSOqnFd5OLbCuvA(gYdy2UvLwXgakQ54zirrHc18nK30qGQ0qld4OBf1AcVMbYi8ynhpdjkkJWqvjJq3QsOqn0YaoQOwt41mqgHHAoEgsuuOqnFd5uGFsad0JwtdbkQ1eEndKXDHAVeQujbEgAsrnhpdjkkuOgvBassCf1C8mKOOqHA0uOrld4OIAoEgsuuOqnFd50a(yrKb6rRKyGIAoEgsuuOqnFd5uGFsad(IOhHAeocfULDeO0Kexg31EjnnZA6SGexgH3pnmlZQ5BiMsmKqRkTcuts8OjAqJeK4AulwhyyXIwzyEneYGUnxIJJ8DqgHhRz6gvQnGYWDwMxZ((sqsIBz5yHuxdLwrHAiKbd1QIgzRM1Jj9OHqgm0CjoQXbFjrNyAKxTlTPGFsWhxwqbSoFC58JEaAiKbDBUeh14GVKOtmTRKx8xg3pv7L0hONhGekGMLX0YCJk1gqzC38ACVtSqQRHslJqneYGHhkXrlH7aCu72xXD2rnJqnkYi0SUdfkb

Is it possible this is a bug?

**Comment by InfusOnWoW** [comment]
There's a load condition on the aura for Midn Bomb. The aura seems to work fine if the load conditrion is not selected.
