### ISSUE TITLE
Wrath: Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by WeakAurasOptions

### ISSUE THREAD

**Issue by klingo** [WeakAuras/WeakAuras2#3960]
### Description

Some dropdown code of "WeakAurasOptions" is tainting the code that breaks Blizzard features such as the "Group Browser" in the "Group Finder" window.

### WeakAuras Version

5.0.5

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```
11/1 00:09:31.273  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by WeakAurasOptions - Interface\FrameXML\UIDropDownMenu.lua:966 ToggleDropDownMenu()
11/1 00:09:31.273      Interface\FrameXML\UIDropDownMenu.lua:205
11/1 00:09:31.273  Execution tainted by WeakAurasOptions while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\FrameXML\UIDropDownMenu.lua:890 UIDropDownMenu_GetSelectedID()
11/1 00:09:31.273      Interface\FrameXML\UIDropDownMenu.lua:550 UIDropDownMenu_AddButton()
11/1 00:09:31.273      Interface\FrameXML\EasyMenu.lua:30 initFunction()
11/1 00:09:31.273      Interface\FrameXML\UIDropDownMenu.lua:79 UIDropDownMenu_Initialize()
11/1 00:09:31.273      Interface\FrameXML\UIDropDownMenu.lua:1094 ToggleDropDownMenu()
11/1 00:09:31.273      Interface\FrameXML\UIDropDownMenu.lua:205
11/1 00:09:31.273  An action was blocked because of taint from WeakAurasOptions - Search()
11/1 00:09:31.273      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:225 LFGBrowse_DoSearch()
11/1 00:09:31.273      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:178 LFGBrowseFrame:SearchActiveEntry()
11/1 00:09:31.273      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
11/1 00:09:31.273      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:67
```

### Reproduction Steps

1. Make sure "taint logging" is enabled: "/console taintLog 1"
2. Disable all addons except: WeakAuras, WeakAuras Archive, WeakAuras Companion, WeakAuras Options
3. Reload UI
4. Type "/wa" to open the WeakAuras window
5. Click "New Aura" and then select any option
6. In the new (empty) entry, make right-click so that the dropdown (with "Rename", "Copy settings...", etc.) opens
7. Open Blizzard Group Finder
8. Create **any** listing
9. Chat will display: "Interface action failed because of an AddOn".
10. Reload UI and check "/World of Warcraft/_classic_/Logs/taint.log"

**Comment by InfusOnWoW** [comment]
I believe that is this blizzard bug: https://github.com/Stanzilla/WoWUIBugs/issues/4, which Blizzard has known about for 3 years.

**Comment by InfusOnWoW** [comment]
I'll take a closer look at it in the morning, but I doubt we can actually do anything about it.

**Comment by klingo** [comment]
Maybe https://www.wowinterface.com/downloads/info24408-LibUIDropDownMenu.html would help? According to the description this lib aims to avoid taints while still providing the UIDropDownMenu features.
