### ISSUE TITLE
wotlk: Require Valid Target on dummy does not work

### ISSUE THREAD

**Issue by Ragnoroct** [WeakAuras/WeakAuras2#3961]
### Description

When working on a trigger for a spell that requires a valid target, dummies in wotlk don't count

### WeakAuras Version

5.0.5

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Go to Ironforge dummies
2. create a really simple trigger, like a spell is usable but requires a valid target
3. target dummy and enter combat by right clicking. notice trigger never activates
4. uncheck "requires valid target". notice trigger now activates

**Comment by mrbuds** [comment]
I have tested on ptr and it worked as intended on dummies in DK home & Orgrimmar

Can you include an export of the aura you made?

**Comment by mrbuds** [comment]
No answer from reporter
