### ISSUE TITLE
Include melee haste in unit stats (wotlk)

### ISSUE THREAD

**Issue by missivaeak** [WeakAuras/WeakAuras2#3962]
**Is your feature request related to a problem? Please describe.**
Not a huge problem. I tried to make a weakaura for unholy death knights, to calculate gargoyle snapshot, which could have been made very easily except that melee haste doesnt exist in unit stats, even though there's a straight forward api function for it.

**Describe the solution you'd like**
Simply another tickbox for melee haste.

**Describe alternatives you've considered**

**Additional context**

**Comment by mrbuds** [comment]
> which could have been made very easily except that melee haste doesnt exist in unit stats, even though there's a straight forward api function for it

What is this straight forward api function?
