### ISSUE TITLE
Talent spec load option (wotlk)

### ISSUE THREAD

**Issue by missivaeak** [WeakAuras/WeakAuras2#3963]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I suggest a load option that checks which talent tree the player has the most points in.

**Describe alternatives you've considered**
Usually when I want something loaded for only a certain spec I just pick a talent deep into the tree for that spec. That works for max level, but when levelling up it doesnt really.

**Additional context**

**Comment by missivaeak** [comment]
Ive used them for things like adding a swing timer for enhancement spec but
that unload if youre restoration spec. Rip snapshot prediction for feral
druid but useless for balance/resto. Role/specific things that are not
directly tied to a specific talent but rather the role/spec as a whole.

**Comment by mrbuds** [comment]
There is no api for specs in wotlk 
There are 2 workarounds with selection of a talent deep enough, and role

I think this option would add unnecessary bloat.

**Comment by missivaeak** [comment]
Fair.
