### ISSUE TITLE
Weak Auras main window bug

### ISSUE THREAD

**Issue by fandom1991** [WeakAuras/WeakAuras2#3964]
### Description

So after the pre-patch went live I updated my WA addon to the 5.0.5ver but some bars and buttons were missing. As you can see in the photos the 2nd one has the search bar on top with the ''new aura'', ''import'' etc. functions but mine doesn't (1st pic). I did reinstall the addon and didn't fix anything. By the way I didn't mess with the WTF folder because I don't want to reinstall all the aura I have. Any suggestions on how to fix this? or is even fixable? 
Thanks in advance
![me](https://user-images.githubusercontent.com/117193279/199273346-ca9b61d9-9ba2-4104-88e9-c24d35398760.png)
![korra](https://user-images.githubusercontent.com/117193279/199273466-4e0b207d-9aee-4ad0-bb94-d65210ee5725.png)

### WeakAuras Version

weakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1x Interface/AddOns/WeakAuras/WeakAuras.lua:4043: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4043: in function `GetTriggerStateForTrigger'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3217: in function `SetAllStatesHidden'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4147: in function `UpdateFakeStatesFor'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4126: in function `FakeStatesFor'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1442: in function `SyncVisibility'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1468: in function `PriorityShow'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:729: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:698>

### Reproduction Steps

1]load in-game
2] Press the command /wa
3]Can't see the research and other functions icons/bar

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/9911843/WeakAuras.zip)

**Comment by mrbuds** [comment]
As a temporary fix you cant type in chat this command to remove the aura blocking options
```
/run WeakAurasSaved.displays["Atonement Count"] = nil; C_UI.Reload()
```

**Comment by fandom1991** [comment]
thanks a lot for the help this made the WA window as intended 😄 
![Screenshot_1](https://user-images.githubusercontent.com/117193279/199617016-fb47e72b-9c2d-4316-8bdc-9a34f608863f.jpg)

**Comment by mrbuds** [comment]
Data has 2 versions of same this aura harmless aura https://wago.io/r1JHvtSz7
- id = "Atonement Count" ,uid = "JLHQfZcUEph", 
- id = "Atonement Count 2", uid = "ZJ0d7gSM17v"

if i delete "Atonement Count" options loads, if i reinstall from wago > no error

Made a diff of data that crash options with data that works

```
fieldName, dataFromBadSV, wagoWorkingData

xOffset, -200, -311.00012207031
yOffset, -70, 23.000244140625
selfPoint, BOTTOMLEFT, BOTTOM
scale, 0.9, nil
uid, JLHQfZcUEph, fmryzCQH6GZ
height, 200, 100
preferToUpdate, true, false
frameStrata, 4, 1
width, 200, 100
fontSize, 12, 32
```

This makes no sense to me

**Comment by fandom1991** [comment]
I download your WA you mention.Works fine for now , thanks so much for your time and help

**Comment by InfusOnWoW** [comment]
That's now fixed for good.
