### ISSUE TITLE
mind blast using holy fire icon in weak auras setup

### ISSUE THREAD

**Issue by voozul** [WeakAuras/WeakAuras2#3965]
### Description

When in WA setup for icon - making a weak aura to track mind blast it uses the holy fire icon and again the name of the weak aura is tagged with the holy fire icon but uses the correct icon on the actual weak aura when it procs in game (and the aura functions correctly).

### WeakAuras Version

5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Make a basic icon weak aura to track mind blast.
It tags the spell with the holy fire icon.

**Comment by mrbuds** [comment]
Please include an export of the aura you made, the reproduction steps you gave are not precise enough.

**Comment by voozul** [comment]
maybe I did something obvious wrong..

!WA:2!1v1tVTrru8y5wvWiIAslreardfAeTs0)bjafOTEd2nPKyNUEBt7j7X7oE3Pz9mtNzw74CRgAjibcKL4ghq(mNYhGku(emYcXzu(aas5ahbEZS2PnaXh8(M38M3F(n)EVjtXjBozWKbB9M9j(mAfwIWh)AJnaLOIyIYCfHrL5eDk3OHeR((TruFq)QmcvvFHcL8k4oWNXIdyTPvAt44ODgTSqqiosG8TEyExPcju5CiuIkx9gWhzuUUkbjmelKJpRyO4F6O6WXUsoooUN9)sOM4N7u)WUYK64wyQQssJgKn2U6c5R4vTIxExpxRE(0lmmYZSQGfkWs5mVDfJholFIejUAiMIfe)krS2LP1gCGL9LWN8XTrDKojqkwNhJ6GfdeyuCLrzr)vi0GzCIrs1aJd3p9Q11kUuGmNlfwlZXpHXa8gq5)uZI2VgwvGHAWTYQfwE5EglvaqTET(b46q15biGyXclVAXBd7shIm54tyaZwyV01RWcW)0y7bxeybffFhagbKU9ERJX88qm9vUia7J6jXXnSxy6JcbqIujcKch1hsgxCO525MtPhFaSSoKeHcwcnyRtYNuH3as(ieaP3n96pdFARs7FnyIMiWGHcougf3B)Tp9zK8J)mEybwmtCZmzYKD3uTJskN832Rm)ewLaPJbUI4Vgjqf5KhwUxASiBGdSkF4Gug49gMr7y3)(jsfPrhOafmfuCEGsNsLlvqpUaQlJn9Tg6BtJfV2V)x)9mJn2yGWvVAnqiB2EdlkGiD8IcYMZCReuaauOz88oawmkYdS6AZebRjq8URnuinHArKK6X4AdXGNPRHpXsLkvWTQtzpVYR4U0nw0BW(HUczt80dRW7EG4y21YlkFBVLxQuHFDqymRDrb(bjyQFNvpYfp)LNlTAnBST5VrEORzH5WdQNOumA5wybqV7BuVmMgQIEjR9JQSEMfPxyzHF7ae0BmstKJzZiRjv8rX4S2eXlI4VofA5YA3zzcipHnaoaUGfrBnn)n(pChEvfPjUkxG9jgYBw9fp9z4)pKm(qbxJ9b6lRFx97PNtp)d1VFg9hOpQ(d1xH)whM)JXHi)ovBeZG8xpU(J4N9WmnOd0)s8RQIG5hrW4Km6p2qxEYt(nlD5po1PUULUO)e9v1Vtg91YWN5WCwtwqvtRwn911513qVOEb9r5V(HzE6QmANA6cNrxmJ(s2(L6rysyK6woXmuqR(MPf(SM1rQA76dJIKa5kWmJXFQ6scnmgFKJxxbxmu1uUntIvKC8jTh6agxZ1UEkDqoh7HTca9Zi0xyNlyOmoMxf4NC0qDtJ1NsKiGBhej2iLWS4pxRyFavgR7iZI6HOetNmJoV(5lcy(f2bJK4kkHLVDSbbMHqW2vnJ7fsmeLazxJnMOQVGtteHApOMDmnx)aTaeFH)TgNnzSMz2UHagVcohAxZ2xX8BLom8LZ84F80Ka9R66VpB2ffZJqz3lTjRO5GMiwVYcUfkuQoKhniH5UCcjy77TYNT5LCkMm)Lycc14tCKflh9qdmc21C)622mA6w9nfbX(E35M11pc7V(86xmB3wibXGy9z0rN0TfkobNr4hHOHy5RmR(r3zpt7svBPyrLbfDZVsHkfwUWcELDTDOvtFo1X8A1U230mkTfxT(p948tUggTEEaILx5PVzz7mTEwVsxUGb4UQZogLWLQ9nKz1DnjS(Z1FH(rz1p(CqAnV(l1BP)kNisaw)16Vr)T6Vduxd(EUTj0uslKt503V2Ks35o)fp)Ct26xU7)m

**Comment by mrbuds** [comment]
> maybe I did something obvious wrong..

No you didn't, but your reproduction steps could be interpreted in multiple ways as multiple triggers can "track" a spell

Thanks for your fast answer,  can reproduce issue now.

**Comment by mrbuds** [comment]
Your aura indeed show Holy Fire icon in Holy spec, but if i switch to Discipline it show Mind Blast icon as intended, so this seems to be a non-issue to me.

**Comment by voozul** [comment]
Its not a major issue its just weird that in holy spec or disc spec when I'm scrolling thro my weak auras to find one/edit in the list mind blast has the holy fire icon. No biggy tho. It doesn't swap to the correct icon in the list for me in disc spec.
It does howeveer always show the correct icon in game when the weak aura is being procced.

**Comment by InfusOnWoW** [comment]
That's how the spell is setup by blizzard.
