### ISSUE TITLE
Import of WA with the condition of loading "talent or talent"

### ISSUE THREAD

**Issue by artazika** [WeakAuras/WeakAuras2#3968]
### Description

I expected to receive WA with fully working load conditions when importing from the site or via chat.
They are imported with checkmarks for "talent or talent" but without the selected talents.

### WeakAuras Version

5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Import WA with load conditions "talent or talent" from the site or via chat
2. Check load conditions

### Last Good Version

4.1.5

### Screenshots

![image](https://user-images.githubusercontent.com/39316666/199302794-97ad4195-0959-4029-b776-7b68c88fe957.png)

### Export String

for example this one
https://wago.io/Skpv--coQ

**Comment by oratory** [comment]
This was a Wago.io export bug, and is now fixed.
