### ISSUE TITLE
sound fires even if both triggers are not true

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#397]
> What steps will reproduce the problem?

trigger 1: group -> buff
trigger 2: player -> buff (missing)

set to all triggers
both buffs are the same.

actions -> on show -> fire sound

> What is the expected output? What do you see instead?

The sound still fires even though the buff is not missing from player.
I expected the sound not to fire

**Comment by InfusOnWoW** [comment]
That's due to how group and player buffs are handled internally. It's a won't fix.
