### ISSUE TITLE
Stucking at 100% loading screen

### ISSUE THREAD

**Issue by SkelzorTV** [WeakAuras/WeakAuras2#3971]
### Description

Latest wa version installed. The game gets stuck at 100% loading screen forever then crashes.

### WeakAuras Version

WeakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

.

### Last Good Version

WeakAuras 4.1.5

**Comment by InfusOnWoW** [comment]
We obviously need your settings to reproduce that.

**Comment by SkelzorTV** [comment]
What settings specifically?

**Comment by mrbuds** [comment]
> What settings specifically?

You skipped this at the bottom of the issue template

![image](https://user-images.githubusercontent.com/189656/199607214-04b49b16-aeae-41d7-bab7-71ec1951d83a.png)

**Comment by SkelzorTV** [comment]
[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/9927075/WeakAuras.lua.zip)
