### ISSUE TITLE
Allow to setup progress value

### ISSUE THREAD

**Issue by Flowy** [WeakAuras/WeakAuras2#3972]
Would like to set progress for display, based on combination of triggers. Not use only the first active trigger.

I.e. two triggers with progress and return minimum value - compare gcd vs cast, compare first DK rune with second DK rune
or make progress shorter based on subtract of two triggers - debuff on malygos lasts for 10s, but there is some projectile time, calculated in other triggers, that would shorten progress and give easier to see bar

I would like to be able to code it, but even simple choose (same as icon) would help, so my triggers does not need to be ordered in specific way.

**Comment by InfusOnWoW** [comment]
Those are all best handled via custom code, namely a watching trigger.
