### ISSUE TITLE
Allow to define custom options via code

### ISSUE THREAD

**Issue by Flowy** [WeakAuras/WeakAuras2#3974]
**Is your feature request related to a problem? Please describe.**
I want to enable users to define their 'default' choice, out of options that they provided (list of values, one should be default)
I want to enable users to define details for mounts they have (some should be used only in some situations, others never, display only currently owned mounts, without user needing to type in their names)

**Describe the solution you'd like**
Allow me to create code that would configure 'author' options.

**Describe alternatives you've considered**
Until recently, it was possible to 'hack' into WeakAurasSaved and define these options, but WAS is forbidden now and there is no alternative for dynamic configuration.

**Comment by InfusOnWoW** [comment]
No, we don't think dynamic configurations is a feature we want to do.

From your problem description it sounds more like you need to write your own addon instead of trying to shoehorn it into a WeakAuras.
