### ISSUE TITLE
Dynamic Information not displaying trigger icon and name

### ISSUE THREAD

**Issue by Brodieman** [WeakAuras/WeakAuras2#3975]
### Description

I am setting up an Aura that will display an icon and text when an item is not equipped.  I have multiple triggers get up with assigned gear.  I would like the icon to display the name and text of the missing gear that triggers the aura.

Currently the tooltip is enabled and is showing the correct missing gear.  However the icon is missing, all I see is the glow.

### WeakAuras Version

WeakAura 5.0.5

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Set a trigger to Type {Item, Item Equipped}, Type in the item ID, and check Inverse.
Set Display Icon Source to Dynamic Information, no Fallback Icon
I enabled Tooltip Mouseover for testing (it's showing the correct dynamic information

### Screenshots

![Display](https://user-images.githubusercontent.com/13592675/199554534-83d14d2f-14bf-4e53-92a3-5bb34bb137be.png)
![MissingIcon](https://user-images.githubusercontent.com/13592675/199554535-e88660d5-2271-4291-9f00-81ca8977efcb.png)
![Trigger](https://user-images.githubusercontent.com/13592675/199554539-96b729f8-9d67-4ced-85e6-dffadaa7eb97.png)

### Export String

!WA:2!Lw1tVTrru86AeTAfbrCBdQ8NIBvPIkffvckfjU51yxcYnoS7wA5K3X7oE3Pz9mtNzw74ER(upIYbob9GpZjFIJO8jyKfIpa9aN4u(eWBMDDAABYj8H1V3BEV38793Ps7AdRfxl(53AgjIr9z5Ii8NCoX(DhmqIv)7xnlkxQyddW7R43Eqonsry0V42o1RlWQCbTokxG6HPJ2GOWd3bne7GPXIjf2FZvMJOrPmXUmcv1VzRDcA5TiIXYIzJP(JjCC4HlzBfNGtDnWiCQsqssWc5F8UN)wIsM)XvnHJDn3ZlL59XJWuLF(GbK9N3Rzd)GE(bn8cwKGPybjYpLnUl9Ls7FnlVI55sCpcDe4zCON1dl2g8x9wpjNW54y3Ckr1NNHMGfhAvgo1pJPs9OqSjDMk54SSTJLohJHDfyadE(72QtNJTXKjcNUK6IV4s8vnh9AGlCwmUpeabqyj(UwD2T9d6CqoTmCDUL(9(f9k63xFPq9L1xrVM(d1FwO(td1x7IVyn9Q6A666RRVrHIGSR8gAA0WypyXju8m84V9StXJ37)Jh)1F(eECEmr(yB7Zi8Mi6e(QilDqrWEFwm(3p3miffaLkfHhE0EymVbKTJuEiOPl9ajoBGTpsFbiXjrq7hsHtNb1bpCc0wk)MNFn(vvqRAp7NbmXqKQhTKWLYO4do(4B850dTmJiss)mCi)dSSYue0Q0KLXeFFLkvQY)432JB8LLK61FzHrlXMBJhe0LFjRquom5ayp6HKyvQBdG9Oc3q2hhBf(SffZhpQyEPsj7pvYwaWhdJGKbtGWwWuqiBggD3P7oT41obIx6ItjdWlj8uKH4y(1offmNuYvrVIaYPMZltjNyggaHvuKn)uf(DqPJOG2TfKNw)hYrXqLbvpi41a4YGQu4RfPt438SavgobfnP3GmgtKUWQWyMi(HceF6dljwCmgSZsDFqqNTH0Zh9w(m6vfo(1pRBKlWrqpbJwLx)S0zilUNP9l8vxTp5P4RYV9zzr8eydcjQNkvGHTszXtoLkv0XWBn9klGQqFu0Ejcwon(VxKKXg3wGFsoMgnz335oBS5wfLkZbZnFw2dm1Wysfl6NRumAxyJhStBMrChmnrLEfR(lljhyyAECj1Sf7ElLK6Aom0E7bPKO9OyPSQ1c)iugUGSdbeVQ9cCHIcwK2pftssvpZnJHIB3xbQsvR5nmhgVDCnd2RPJC8IYqsPHYvc5pdXmHDA2aFTdVgGLLRVHTeEMC(bikXmyXO31tQqcv7dXij2xjSX2fGnsRVi2SEauPN5vdyFp8UsSCQrpRNx3DiIqBR3ZQTotput1R3FaHsKPVP45eArDb8NZmJNigsPJazFquEx9JD0ChxWALJhkJNIQ6(ugByLnZjXZBShL0yVoBU9t(6zkwK59hWQlo6pVbC49jsjHMu3DB)JkgkAlG3mmOSVFtVwT2z(aJai8GPQQEJTlo8E1eyFaqdijoIYx2s5xE5BQMvfFlrIG9BXPlGfsG37YlWUzLS5LUTbZp)0LweEemLJfuu2pwGYX1KEBTXD2yRAJ(Rh9F)

**Comment by Brodieman** [comment]
I am sorry mrbuds, is that something in the addon code that will be fixed in next release or something I have to add in my Aura?

**Comment by mrbuds** [comment]
The line automatically added before your comment is a potential fix for your issue, it needs to be review and merge, and then it will (hopefully) be fixed for next WeakAuras release.

You can test the change yourself by editing the file if you want.

**Comment by Brodieman** [comment]
No worries, thanks!  I was just checking to see if I was not setting the aura correctly or if it was an actual bug.  Thanks for responding so quick!!!

**Comment by Brodieman** [comment]
Tried adding those 4 lines in the Prototypes.lua (to help you test it), now I cannot load the WA settings in game from the minimap.  What did I break?

**Comment by mrbuds** [comment]
You didn't copy correctly, but if you can't get it right you can re-install addon

**Comment by Brodieman** [comment]
I added the code to the Prototypes.lua and it still does not seem to be working
![NewCode](https://user-images.githubusercontent.com/13592675/199565847-f6a507ff-d685-4227-a100-774b0ae2b953.png)
![NotWorking](https://user-images.githubusercontent.com/13592675/199565850-8668021a-1fe8-4f12-896a-7e2990f93284.png)
