### ISSUE TITLE
WA Disappearing

### ISSUE THREAD

**Issue by Mvttoz1** [WeakAuras/WeakAuras2#3976]
### Description

https://pastebin.com/rc5sZbJN - I'm getting with that issue I disabled all addon bar bugsack and weakauras and still go the same error for when i type /wa all my current wa vanish and only reappear with a reload.

### WeakAuras Version

WeakAuras-5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

3x [string "return function(allstates, event, type, wat..."]:17: attempt to index field 'loaded' (a nil value)
[string "return function(allstates, event, type, watchID, ...)"]:17: in function `Collapse'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:183: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:176>
[string "=[C]"]: in function `Hide'
[string "@Interface/FrameXML/UIParent.lua"]:3309: in function <Interface/FrameXML/UIParent.lua:3304>
[string "=[C]"]: in function `securecall'
[string "@Interface/FrameXML/UIParent.lua"]:3347: in function `CloseWindows'
[string "@Interface/FrameXML/UIParent.lua"]:3364: in function <Interface/FrameXML/UIParent.lua:3362>
[string "=[C]"]: in function `securecall'
[string "@Interface/FrameXML/UIParent.lua"]:4013: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = Frame {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:145
 subRegionEvents = <table> {
 }
 Expand = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:909
 yOffset = 0
 GetColor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:426
 inner = Frame {
 }
 icon = Texture {
 }
 SetOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:319
 keepAspectRatio = false
 SendChat = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:267
 SetInverse = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:490
 toShow = false
 SetRegionHeight = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:485
 UpdateIcon = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:450
 Color = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:398
 cloneId = ""
 Update = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:617
 regionType = "icon"
 stacks = FontString {
 }
 GetRegionAlpha = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:388
 currentCoord = <table> {
 }
 ZTRegTypes = <table> {
 }
 SoundPlay = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:249
 Collapse = <function> defined return function(allstates, event, type, watchID, ...):16
 ZTCollapse = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:887
 zoom = 0.300000
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:410
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:328
 SetGlow = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:624
 SetRegionWidth = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:480
 UpdateTimerTick = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:439
 RealClearAllPoints = <function> defined =[C]:-1
 RunCode = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:274
 GetYOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:340
 SetAnimAlpha = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:392
 finishFormatters = <table> {
 }
 SetDesaturated = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:476
 SetYOffsetRelative = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:357
 ClickToPick = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:758
 OptionsClosed = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:753
 cooldownSwipe = true
 cooldownEdge = false
 GetXOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:336
 SetYOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:332
 SetCooldownEdge = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:506
 color_g = 1
 text2 = FontString {
 }
 UpdateTexCoords = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:321
 GetYOffsetRelative = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:365
 SetAnchor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:307
 GlowExternal = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:282
 SetRegionAlpha = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:378
 GetXOffsetRelative = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:361
 yOffsetRelative = 0
 SetZoom = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Icon.lua:514
 regionHasTimer = true
 subRegions = <table> {
 }
 height = 16
 startFormatters = <table> {
 }
 Pause = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/Reg

### Reproduction Steps

Open game
type /wa
All wa current wa alpha got to 0% and no longer visible
/reload
all wa appear again

**Comment by mrbuds** [comment]
You forgot to include the data of your weakauras, file's path was in issue's template

**Comment by InfusOnWoW** [comment]
Waiting for reporter.
