### ISSUE TITLE
DF Pre-patch LUA errors

### ISSUE THREAD

**Issue by fraerie** [WeakAuras/WeakAuras2#3978]
### Description

I'm running bug grabber and bug sack

Loading into the game I get scrolling errors and have to roll back to WeakAura 5.0.5 release to stop the errors.

The WA that appears to be linked is https://wago.io/Afenar_Druid/174

I will also post the bug there

### WeakAuras Version

WeakAuras-5.0.5-15-g461e450.zip

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

**Error No.1**

2987x Lua error in aura 'Astral_Power': Trigger 1
WeakAuras Version: 5.0.5-15-g461e450
Aura Version: 5.0.11
[string "return function(event, unit, cast, spell)"]:90: attempt to call field 'updatePowerText' (a nil value)
[string "return function(event, unit, cast, spell)"]:90: in function <[string "return function(event, unit, cast, spell)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:611: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:853: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1883: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1678: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1860: in function `Resume'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:194: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:176>
[string "=[C]"]: in function `Hide'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:620: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:618>

**Error No.2**

6x Lua error in aura 'Astral_Power': Trigger 1
WeakAuras Version: 5.0.5-15-g461e450
Aura Version: 5.0.11
[string "return function(event, unit, cast, spell)"]:83: attempt to index field 'generators' (a nil value)
[string "return function(event, unit, cast, spell)"]:83: in function <[string "return function(event, unit, cast, spell)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:611: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:713: in function `ScanEvents'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:885: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:870>

Error No.3 

4x Lua error in aura 'Astral_Power': Trigger 1
WeakAuras Version: 5.0.5-15-g461e450
Aura Version: 5.0.11
[string "return function(event, unit, cast, spell)"]:64: attempt to index field 'generators' (a nil value)
[string "return function(event, unit, cast, spell)"]:64: in function <[string "return function(event, unit, cast, spell)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:611: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:853: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1883: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1678: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1860: in function `Resume'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:194: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:176>
[string "=[C]"]: in function `Hide'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:620: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:618>

### Reproduction Steps

Install WeakAuras-5.0.5-15-g461e450
Enter game
Install https://wago.io/Afenar_Druid/174
Reload

### Last Good Version

WeakAuras-5.0.5

**Comment by mrbuds** [comment]
I don't have any error with this aura, but error come from custom code of "Astral_Power", not WeakAuras.
It had 3 updates on wago in 2 days and these errors does not match last version.
