### ISSUE TITLE
Progress Bar - Absorb Overlay Color goes back to White instead of selected color.

### ISSUE THREAD

**Issue by RShadowhand** [WeakAuras/WeakAuras2#398]
What steps will reproduce the problem?
- Have absorb on you (such as prydaz)
- Get in combat
- Get out of combat
- Voila!

What is the expected output? What do you see instead?
Absorb overlay color is supposed to go back to defined color values after the combat.
Instead, it goes to White.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes

What version of WeakAuras are you using?
2.5.11

Was it working in a previous version? If yes, which was the last good one?
No idea

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
No errors.

Please provide any additional information below.
In case you do know which aura is problematic, please export the string and paste it below.

```  dKZceaGlkHFrfzyqIJbXYOsEgvuttqCnPGTrPKXjf5CqszDuIYbPcwivQhsPutKsuDrkfTrbjJKsbNKsvZesYnLIANs8tPKgQuILsjspfzQeDvbP2QuO9Q(lkmyiP6WKSyH8yPQjluxw0MHuFgLgTG60qTAkr8AkvMTKUTuz3u8BQA4OOLJQNtQPdUoHTlW3LsnEQqNNsA)uk0JSCQBkEsp5YIgSabzkE5eoEYgAXgrD3k(KkogdyVrvzaCmlBY1lVGSCsyaoMLn5lhMaoMLn5lNegmmXSQSM8jHjdsdmPeGFslIYG0aTWt0yhNOwSjQq1KqNmWMEFxKc29ugKgyY2EtmgWEJEcSYmN0Gce6jTikdsdqc0OXooXW2oqsgK0blvoj0jdvK2ZJA2hN7EsOtgcdg29WWWumwBjctpGdYjLX6epzXEJ0kZCsj4QifFc4yw2KVCsOtgQiTNh1Spo39KqNm0H9TDis75r7EcSYmN0Gce6jHozimyy3t6W(2TAM0H9TB14qpGdYjHjdsdmPeGFycT3aHQQy1tTgAjQSVyZjbVofgaMAlZjNARy9wG9oXTtypArJ2cTtitq6ii45uOQkycBWadnO4qgFbzQ3BIXa2B0lVGSCQpC2B3YjGJzzt(fKPafhRIQ5KoSV9uGQkYlidt9Hvg2uV8cYYjMCpZKdwN8bjVQSQTazkqvf5YlixqU46ckxC(ckxc5cYWWWWWeG7s(rtq6iC0e2eKCDU7jFqYRkR6LxqwEb5ckwGGsdn1KlNBWfQfccstxCDb5IZxq5sixqggM0GQ3o9rtQEahKsoMLn5n7JZlOmzeDsoMLn56lUMQEv8YjUQpxo1jQaE5WWumgnACVOcwxo1jQaE5WWeOQPbwo1jQaE5WWe3xZLtDIkGxommbQAAaxlN6evaVCyycTQhWEZYPorfWlhgMWgwUxWC5uNOc4LddtmdycQAAGLtDIkGxommmHnqYnQAJjxJ9MlopmfCbjexitTvSE7T8jUDc7rlA0wOhE ```

**Comment by InfusOnWoW** [comment]
Should be fixed in 2.5.11.
