### ISSUE TITLE
Errors Setting Talents - (blance druid)

### ISSUE THREAD

**Issue by syntrixsystems** [WeakAuras/WeakAuras2#3980]
### Description

First errors appeared when I changed spec from resto to balance and then a second set of errors when I saved my talents.

### WeakAuras Version

WeakAuras 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1.  Change spec from resto to balance

or 

1.  Change talents and save (as balance)

### Last Good Version

Fine before dragonflight pre-patch.  Don't recall what version I had then

### Screenshots

1st Set:

1x Lua error in aura 'Starfire_2': init
WeakAuras Version: 5.0.5
Aura Version: 3.4.7
[string "return function() aura_env.region.bar.fg:Se..."]:1: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "return function() aura_env.region.bar.fg:SetGradient("HORIZONTAL",0.98,0.78,0.83,0.59,0.59,0.94)"]:1: in function <[string "return function() aura_env.region.bar.fg:Se..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/AuraEnvironment.lua"]:372: in function `ActivateAuraEnvironment'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:838: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1882: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1677: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1719: in function `ScanForLoads'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1779: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1777>

2nd Set:
3x Lua error in aura 'Hibernate': Trigger 2
WeakAuras Version: 5.0.5
Aura Version: 3.4.7
[string ""]:7: attempt to compare number with nil
[string ""]:7: in function <[string ""]:2>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:602: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:537>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:843: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1176: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1882: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1677: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1524>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1719: in function `ScanForLoads'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1779: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1777>
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/9933042/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
Thats a problem in your aura Starfire_2, you need to fix the SetGradient call in the Actions/On Init section.
