### ISSUE TITLE
Models dont respect parents

### ISSUE THREAD

**Issue by Dajova** [WeakAuras/WeakAuras2#3982]
### Description

Any model WA that is attached by a parent other than WA itself will stay displayed and not respect the parent it's attached to. I'm not sure if its fixable by attaching it to blizzard frames, but it sure doesnt work as it should on other addons.

Note that it's only Model WAs that seems to be affected, everything else seems fine, so i think it's just something you've overlooked somewhere.

### WeakAuras Version

WeakAuras 5.0.5-17-ga515894

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Make a Model WA
2. Set the anchor and parent to anything that can autohide itself
3. The model says shown, while the frame autohides itself
4. This does not apply to frames that isnt shown and not just hidden (like target frame)

### Screenshots

[gif](https://i.imgur.com/16tgXYu.gif)

**Comment by InfusOnWoW** [comment]
I believe that's a wow bug, not a WeakAuras, see https://github.com/Stanzilla/WoWUIBugs/issues/295

As it appears that the frame the model is attached to fades away.
