### ISSUE TITLE
Anchor breaking

### ISSUE THREAD

**Issue by ChabWoW** [WeakAuras/WeakAuras2#3985]
### Description

On the new Alpha version WeakAuras-5.0.5-21-ge3c212d on the Dragonflight beta, I'm getting this error after setting up an anchor to another group:
WeakAuras:  Warning: Anchoring to your own child 'Evoker Primary Bar' in aura 'Evoker Secondary Bar' is imposssible. 

This is 2 Dynamic group with 1 anchored to the other.  'Evoker Primary Bar' is not a child of 'Evoker Secondary Bar' as the error message seems to imply.

### WeakAuras Version

WeakAuras-5.0.5-21-ge3c212d

### World of Warcraft Flavor

Beta (Dragonflight)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Set 'Evoker Secondary Bar' anchored to frame: WeakAuras:Evoker Primary Bar
2.  /reload
3. Anchor setting is removed and we get the error message in chat: WeakAuras:  Warning: Anchoring to your own child 'Evoker Primary Bar' in aura 'Evoker Secondary Bar' is imposssible. 

### Last Good Version

WeakAuras-5.0.5-17-ga515894

### Export String

!WA:2!TZ3c0TXvA97jQ(KwLST2ozDZJ2g18cBVTjwY2YpOPblB5hjo2osYps6dPrAgRzIhnZKzgzz59FbQB)xmqll1BiTuELkGg62wyX0wAbwo0auGfoN97yOD1Hx7s41wkpdWY7t47ENrYJ8lPe7yYMtZ5e55EN79o35(9773339(9jXmwvjQIRkD1kB6q1FOMEqpUFW48neZJBpCvXnZ(0spWyJPZBWOnbVMUOISJ5eLhtrlbRbwWzuvwnEzdToKy1151VcRCmbfTU0ytWhkTkF0GDeWV)(NLvw0SdE9LGvuUlFg4n9jRiZppxsn6DctQstNpMImN(08S60ba26Lixg0aFkXne2CaDdwnJUGTaBf(uWDc3f(3k2C0XeLf1fwC1EskYn3i90yQU8p8jQ3NBpj1Ku3TGHHQEBh(WPyJRCirLdBCmFAPR3D6uh2TAv4t3qtrsINRdbrjo8PwNAv(NqzCEnxdQHVeAPD5JvtD7w1fKoFTQDUOkAC8ADOiPODmggghzmRWpxCE1kdE2K4ALRUskj5Aebrd(O68jWf1aUX196ZONmAa(44cHUtn2yKveDV(WxldNqLoHQCMXqjMLiyhmptgRHoO4u8LVxrUOMZN5JYgBConfvZ5Gdhog0bkuVIOSbVMmR0WMdqQOM9wyot51GkydI2H)(d5pWLmVLPu)oMBmIOex(znyDKH8UkAyohN0cxeLSo2BNZMFzmk2QXeJ78YMdKpRzKAf(KeNAkwnoxHuuKmev9jPWY1vudwjebvDGejXkDgigbjvn0KtF647M5fQ8XixyT(2Rm(CDmTHMy8447ZUo4SjLTk4uZ6INzAStss9YP7e2saweJ5XxsCXmQQeBACnNFc8zgThEwjdHmC8rto2ye4Mwp(7BWUgQVlJsdAtcI3qCY5c3r7bdfoyO2dek)TguJhVvGGd6VV(ciJRs6oNNnPbUCoGQ5AugnQaLmWbIRPKunGEm8L1XS68sJrxZHARAIB7jQk2fUVzAg20ZU1ROROz0t6OAICHyJkXptfxQtnE2eU8HFAiimlzItfHcrpnVQqAnbRg0LKyCbdb1D2LicYmBURA6KFcwuJHmDQvqTIq8juv0yLC1USscwP0cxjOaRbcneLJ7kiQzH9VtEE1LV)ZsgADdu3xitNAOuxg)Gxik2rDu7BUGQIA4kSKIscbelNsuMt4kiIJJv2WL)errynVWL9tqIIgPDfmPg27lhsu1LHaVRGKLgDb42QEoKEjgVFYASEeOCy)WMHBhUdVGZfRGdvUKAQAX1eqsmHOXwG(HAHpnu9SSAX6JYL80vNjws81jr3AkP2RtNWDFHkGHHhhcbJcNcEmyq4rGHGtcbGhfoneggbcoDsD((iJNaSlQgoSB4E0mz34fGJ5eEqg4qWHbhoGTnN)j6MRMt20X7Q3ethNisrGWEd0juVZ5IPiLmHCqvCjXbSVYH9s0Pr9yyhWECQHl5eqmJpe1KktpdeO3tpq)HAVp4GPGVnHa60UfvxjjUofvKitna3Gh4eoG6UJzjpQre5me2cCVW95JaPWvIpJJPXbZ8jIxzkuzGhWjC8lXLgXVIXOyuumXjMu)P3k4YlC)wKpqn4QxdDbnsudbV0pBM(zlKpdWIOpzSjTTRdcF7oHh6zGJG6DWddhf(oG2bFqhqNGFOlOBOhOxNqRoYmgYd2HOwmj(ixgzmWxzzJUqIpfTObAVZEhkiCG88xZuhSjgunvN1GyTGNGsGieSXowtyJRmoc2BNqVyeGSEiaja5lfdPN4usjtOTfYiItUG0v67PmI0fxsH9ux1WwMhjci0TKvnzUXS4ndhlp7VfDvyECCMRtKc0fQTHdmSLzjDLEtlsYWtiQlI67cZBvwHsUMFiiuHoMo3elsubEI2(jnHneaxGy5i8DOwfcs7WQPNqHdFZ4JOU9CDoe)KgDkQtyx4eiaQAmvmcKIazojIC9nfQbp4Tv)HC3mcIhPPAhYDQo4hUVrrmKpYYrK54e1jeP9If2e8a7YRwmbw548ix80Q4lkVMrAiDGjyLsYhjQKO844Zkqmb(yJ7fEihtpbRMizcKrro3efEEhiksvG1X85MPbtjQYhb1wq6jcRhk2B48ZIVCHLjSGcwiqVhe)mQosHjXh1)WdCC)bO40Q3r5xC7rORgHPgvcZkZfMiSJyIANn)DqeybnahXQ95UrVnhbEP38rYqANPvkbQsXbJAsCSPz5ucBEPau5bHxEsMHjMAcZlpXHy5odEhtbLRJ4QENskidhLLfl2REqI9PJlJVN10qZ13ytEQ1QfDjH2swst82uRn0CUMyrpV420IhpE9wRt8FIJz(GWxiRXJCLv3WjLStx4)wP5Ado5L05XXOMchKADPOzRoZHZSYf)qQT4pfp0NYQ2e3o5L5iVpqgbOQQjF2w)MmmFtcddYUmpr4qT13podIqiAuRKuxCEz0UwSGckPgqoI62i1XpjsWyR1ZM)scwz(c6sgD8pTlLInTo6bbTHZJVAsbT3fOD1DMdbJ(hQehnqQJlrK2ulLSJq61RjudDIk24ruRK4D3e8HmDubvq5F9YikuNjPm9gEyLtJwsigdggoo8Celxucqi96fVhmfLPd(ScW)pM8KATHKAWtmg8DAAz77c(UXYpjmTa8uoGN2XhoBCjLuMow2Zr)Gp4d(6LvwOEoA2x8f)1kRSAC4GE7(eL51VlFKlfUe(s3DUUezAsDuxHguCsEP5PffeJno2b9YHTOHCIK6YqhgQf6bD08HAIw2hLgmc9rqDuWXCKlpLLpO0cJAvGoYDPXF2K8YXstTFa))JapJn2s47HYucZeb(ETZbcFFe(p47pp5NCIEg7eD06XoBsnK8dEUiWpGwJEBO(gBSr4bQ7GWNhPZkhoNpcwbzWGphA)7hK4k)HA4qKPb88r8AwjKgVgMvG2fhW5GFis7pVd4fimCWlICBFi8dxaNg8sWpsoMSPE5izOyWXjQ67O8p43fUGGjng8JfXhULfENxoVQaTrcQBFryEZQHFCc9g8tq52GF0iMuAWlVjI6fHfd(jTPU94fQUb)uuvm4Noc8kcWfjtm4NbEveO8fGxd9DQD41Tb7H3iIz3NPYC9612r5Ap1Lik80PKiN(UII8Fn1udWRe5k4e2pz(g0059iKhh5PErsVOpiCAGJl5XqCViNlfVre4N91ld(5GVOLMZJFtLMd8ZFmh9C0V8l9sOMsV9CuyWbJuwzd5aM7UGFbb4nJaVf82WViQeaVd8Uuup8lfb(LDa)kmWxIb(vxBG4U7(S91BI(oJsJ9zde7XtJn1IDqm8E5rWWLqW6bleQAdfxaQ9TxjuRtc2khcf(nfG33e6DqIL1wIKda(RJG52wByq9rxadoNT9)uIOr43AxWVnI(GFNRF8wOpbVLhVfS1ZO1Uqq31OQVi8wR5XBowj8w5fdVD(vHL8cFLifa6kGP7ccLekBPGdc)ulUB5AfHSYG2iKEFHVYcGwAPLawxeeB0naiMTT4CZngBIrthT)MInElNCWCySnzbUIs3NHED2qzlGRyGh6bkdo3EhiacWQMaW8AdcA3(87Te7ZRgY7Dp8niKxt13sZRZiV39W2rEyPIH8o1nDipeVvrfUkRS9JqW)GTV99C1R(f3OqEDMy0HowYeHs2V)fJ8wwRL4no4sj7kez9(RcYA69viYcbt2SLc)EMgs)nOgsVy6vhO1FrmKo9(S5m3JvuCXJ9j4IfWfgJo8a(JQoH4inwQ4IL3VRs09keAihjYk5J11gUOyoy9HN3gUyWvYTQHP9L6mfP3iJfHwQqiZGFcKzbitxtgkw3JhBa9eN6AaYS51cBYln16hBISLzRkiWglJtVsEKdbSGqNV6wiqNa0Z(WhBsdfInhSYvad920rXAiUiz(Mh5r6XRqTc(A06VwGDpYglSRUvh2D9B7XFq5HgIB4MADeBageg857cMVolZmm2bpfF)BRgA5n53qS9qL0VjVDVsWsfZ6Zq3urLmZUvVFd(jnct)Wma5HvdBiMGpSQgFmrASZv35Y0gZlcqAkN62O3JOOqcyEmACC81owmdnMn8KJV3x)d0V)5ndDBUt9sDVlzKDFOycSAX51DBvdS15TUVSbnANdmuO(6TF)QvrRwNgDICNPMQRv61jHcxynAqf2)k1ej(4SXshEmjffnHRy2aXj5ndl1tAolsPOXnIgR60JyDXLOvBfjKiZMFQMX)KQKZvnfBAZMqoJyXXsd1Uml55FPZ)oFzZxUCHC1x7dfAa17BLM5MLyMn)9ZCG8dP1sE(vOkSTSTqq)TQ2wK1vRS3(73FGW(giuOborGE7UNqzOTzHG2yE(NKkvRDLMAwrPlSHaUAiOiXLUabx(Z)m)chj5a251nzZ4tgKLezSwAIFrKnErYgBKmDTxf1QEiAznRvk45RYT5oT80E)DcFU6YX9GB5sTkZZh1U0U0PKo)X34OKo)XTtjHLkgL0j3qpfOBuwzAC0qX7BOUhrySql6qVBLeRVs(8SxzXOckdfkuggbE)ifkdnpBW363FTjdX(BtgILkMmmWgRzLJvshZY3OLwcF1R(1yUg9mDMDb)HoG)i4pg(tG)u4RbFD4pJb(ZH)c4VKb(RIa)1cW34jHpwyzOr9SeAu4Vf(7G)EeY8rWFd8pc)tWvyG)5mhiFdH)vg4BA(s8Vb)7W)HfTg8Fc)xPH)Bg4)56NjIVZMpEpJkCCFJYzJjQntMO2w48AySD(HdJKs79ihHuXZxv9W8iM9CzsWozhwZwAdVQjhvwMYwIx2R0buoFDDTWiJ9CZ4W7HYa(W5gtYZRWX1KYRXcP8UwCe7zVZ1pwVCB2JeUOtWAetandLu2iIMsk5bKLstpRjuhkJyCzfn(o5z5eOQwe3QpItA6CquGihpL3gAQHgjQrO20CjwyWQQE1TzR4aOVgSgkAv9WfrB9zVt7ARyPIPT(O3uPToZUxQ(M6bwgFumqF5K0nW9eztbBjkMrwg3flIc5EpqjOiU2ivUUvJpJ7j9mCt(hlO(OlvnUoBhgI1MCn3aZchxRnfuBkCrnxgPAD02KLHzbL1LEiWV3sh1mMANwbST01kVO46)MPx2Op0KxpxFNb8kmCnSEFKYxu0UElwQy6TN(wJnK3uRdpv0rpPumv2v2h5cJaXYcPlvm3Bu6oovIMbwpIfAXahPlaCKUOGJW5bh1Etc4y1wjxDudwgbn5qmemKjozBZn6zp(Wb7XNydD3qoiZYEAniO4fOWZRLOTVsOc9ttGATDNfrKHnZMidlT8ImtX1iBSIR2wh9ywy5mUDJqyprxNYZGn3zQ(otpxFbfOauWQzu6jMP0nkzHgE8IGgEIzSJgWsfjaarBOLM92ONv(4ydMhX0kSPhGbg49vVx)jqFeL4C5tsrxxjXIZD97MKR(T5Qd2KK0vFkscRtZ5qb1pT)jvtkhNFr9iWjtYljjOEVlkd0xuZMpKycExDkkrllCLbIQlYjYkNlF0JgGxpwsEHlhGxMKs7XXji7u4JTYCt4ousKiPmPZb6rHKxQQvyox7NMTYsItzlFL3pS55c6Vp)DeQRaTFc)x)6gS5ZODi6txneBtWD)LZYSVSmhilZUZYCVzzUNSmUYYS3Sm7jlZ9LL5(ZYS)Sm7c4SN665sxDZCxNM06sC10KwIX9p8iNgA1HfGpUzARd7Xjjz1fzicXDcsoO6NNbg3mX0bntv08PIoOSf4SoavA6NJYCDW4P3kjLZfCuy2Lh18OXuR023FObPFZIISkPDoKS0t5C1kSn00puVNr4zhVDsMO12s)g(aPGjHjIS4Kq3o72o))kpv6Tu8uP3c9uP(otWjLIFC9anTmHoW2EOp46tOdE1kUM9nU6v7aEMPAIanlZweiCqVAfintwMTsyFqgM3iVZkuoRSm3b(FNuUlSLi3vwMpfU9GJKZ5LVqoGrwM7SQfroHkrROVPFlLeVNad4V72fBnyl5tdRS44V(CcE7O8ZvzPlGFN3P4c4v06ZtMYU1hSurCFePaV1qaQgSNg7)yNMVHoo(ncb4B9XBqcW36Jl4iy)4Ila39TgcWHhxHFQtvJ3wtgWoN76H47Pk9nc(ONzni7WoBt2HLkQS7EVfr5BKGd2slCUhyu1RxLVpSiSNM6v2sJFI64YOc(MpYSQtOA(fqY5AqwEUkTllXsfvwEpBaYYsoRMlPGzqol0pwi)rJ(pGpUChnk8VuIHO46bUeASt6Vw1oIEIUZdx0C3qRn2sRUX97TmyMvkcQ04h4oF8dS8plFmhCSKyo4WEmhSA2crEW8WqlvwLxO0zvEUNTe8zBvZmiCeiWXVkKLahXsffo6AdfoEJIzrr70T07yU59Ec2cdVQ3gwNmoiw6IX3UV1aHc2zBekyPIkb37gRXH2UrgC1RBaqIyAtg0GDOKtn5ss7Vc2k2so04smqLLUpG6EwN2LwUJqk)wVmJHiD)Ahf6B5IDytn7U56TIDiD)z0nJvSdM0tbhmPNId52ZTg(J0CZkjpX4PpL7rMC92xYLphZxjgJP33AGXWEcMtlvuX39DRH4Ztdt0AFT3qI(QVL1BXxYRHyc9rRbzh2z7HX5JkUS7(Zl7(mlr2rUZ6R96sltA(ODUZJE1R(H3GYKMSm32key(SmLxYUFII8LdBTT5y7TXXNQ9H6uKLJI0mrze8woKgIzk4RChXNI28wyc4LL52T7eA52CcnxETSOSyz1(oszfn(fLrm58(82XEy9ZScjZvv7Em63YDf5AQL(n)383ZawxhXLQMOSrn5)LaGCa98hY6hXhZ2QXBKut2fl5hfaIMHPwyXIkMqjevSuF2IBA79ZLz6Aj15jF))fqBCZsMV0F7F21C0ajq(nWHvIAUZ8RVLNgAmVvplfLJ4SiAA40XMMgwQOAA7NgmaKp8BTzjN4uPQFIApT3yQJV(BK7lXr3YTCVfUF7LdtKLX9AzJ24JWM8dlvu53UYXuswU(F)d

**Comment by Pahn1988** [comment]
27x ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:1279: attempt to index local 'data' (a nil value)
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1279: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:1278>
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1292: in function `PickDisplay'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:1183: in function `PickDisplay'
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:761: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:760>

Locals:
data = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'data' (a nil value)"
displayButtons = <table> {
 Attumen the Huntsman: Shared Suffering Left (Cast) = <table> {
 }
 Swiftmend = <table> {
 }
 Tussle Tonks: Abilities = <table> {
 }
 02 Eye of the Jailer - Ire refresh = <table> {
 }
 Cloudburst = <table> {
 }
 Affix: Burst Left = <table> {
 }
 Wikket: Abilities = <table> {
 }
 The Menagerie: Chains of Damnation Left (Other) = <table> {
 }
 HK-8 Aerial Oppression Unit: Fulminating Burst Right (Hardmode) = <table> {
 }
 Attumen the Huntsman: Shared Suffering Right (Cast) = <table> {
 }
 T28. 3. Traps = <table> {
 }
 Sinful Hysteria  Tracker  = <table> {
 }
 Lower Karazhan Trash: Shadow Bolt = <table> {
 }
 Skulloc: Rapid Fire Middle (Self) = <table> {
 }
 Astral_Power = <table> {
 }
 Grimmrail Depot: Trash Warnings = <table> {
 }
 05 Wracking Pain (Tank) = <table> {
 }
 Shade of Medivh: Guardian's Image Middle = <table> {
 }
 10 Sylvanas Windrunner - Banshee's Blades on you (tank) = <table> {
 }
 Lower Karazhan Trash: Volatile Charge Debuff = <table> {
 }
 Mana Devourer: Abilities = <table> {
 }
 09 Fearful Trepidation Cast = <table> {
 }
 King Mechagon: Giga-Zap Left = <table> {
 }
 02 Retch Dot = <table> {
 }
 Streets Trash Warnings: Trade event Right = <table> {
 }
 09 Manifest Shadows = <table> {
 }
 Lower Karazhan Trash: Shackles of Servitude = <table> {
 }
 03 High Energy = <table> {
 }
 ### Zo'phex the Sentinel ### = <table> {
 }
 Halondrus Bombmanagement Helper (Volatile Charges, mythic) = <table> {
 }
 M+ Display = <table> {
 }
 04 Remnant of Ner'zhul - Malevolence = <table> {
 }
 03 The Nine - Crushing Gaze (others) = <table> {
 }
 Fleshrender Nok'gar: Intimidated = <table> {
 }
 Moroes: Warnings = <table> {
 }
 Mechagon Trash: Shrink Middle = <table> {
 }
 ### Moroes ### = <table> {
 }
 Grimmrail Depot Trash: Activating = <table> {
 }
 SHOOGI - CORRUPTED = <table> {
 }
 Ankh = <table> {
 }
 So'leah: Shuriken Blitz cast = <table> {
 }
 06 High Energy = <table> {
 }
 Hylbrande: Titanic Crash Right = <table> {
 }
 The Menagerie: Abilities = <table> {
 }
 M+ AUTO MARK = <table> {
 }
 Guardian_Rage = <table> {
 }
 HK-8 Aerial Oppression Unit: Reinforcement Relay (+Hardmode)  = <table> {
 }
 Details! Aura Group = <table> {
 }
 Maiden of Virtue: Mass Repentance Right = <table> {
 }
 10 Sylvanas Windrunner - Terror Orb = <table> {
 }
 Attumen the Huntsman: Mortal Strike = <table> {
 }
 Stale Bread <Fine Cuisine> World Map = <table> {
 }
 08 Monstrous Soul 50% = <table> {
 }
 09 Unto Darkness = <table> {
 }
 Treants Active = <table> {
 }
 FF = <table> {
 }
 Nature's_Swiftness = <table> {
 }
 Astral_Communion = <table> {
 }
 Earth Shield Missing = <table> {
 }
 CHAKKA - CORRUPTED = <table> {
 }
 RAINBOW 1 - CORRUPTED = <table> {
 }
 07 Guardian of the First Ones - Sunder = <table> {
 }
 Streets Trash Abilities: Lockdown = <table> {
 }
 07 Relocation Form = <table> {
 }
 Mythic+ !keys Shadowlands = <table> {
 }
 Zo'phex the Sentinel: Rotary Body Armor = <table> {
 }
 Rocketspark and Borka: X21-01A Missile Barrage Left = <table> {
 }
 FoE = <table> {
 }
 Ironbark = <table> {
 }
 Lower Karazhan Trash: Pierce Armor = <table> {
 }
 Skylord Tovra: Abilities = <table> {
 }
 King Mechagon: Giga-Zap Right = <table> {
 }
 Zul'gamux: Blood Barrier = <table> {
 }
 King Mechagon: The Mechoriginator = <table> {
 }
 Nitrogg Thundertower: Suppressive Fire Middle (Reloading) = <table> {
 }
 Streets Trash Warnings: Trade event Middle = <table> {
 }
 King Mechagon: Protokoll: Protocol: Ninety-Nine = <table> {
 }
 ### The Curator ### = <table> {
 }
 Capacitor Totem = <table> {
 }
 10 Sylvanas Windrunner - Banshee Shroud = <table> {
 }
 Tussle Tonks: Lay Mine = <table> {
 }
 The Menagerie: Whirling Annihilation Left = <table> {
 }
 Beautiful Beast: Dent Armor = <table> {
 }
 10 Sylvanas Windrunner - Wailing/Black Arrow WAIT = <table> {
 }
 MasteryValue = <table> {
 }
 Tussle Tonks: Maximum Thrust = <table> {
 }
 Au'myzas Oasis: CC = <table> {
 }
 T29: 06 Lihuvim Push/Pull icons = <table

**Comment by mrbuds** [comment]
@Pahn1988 please open your own ticket with answers to all questions of the issue template

**Comment by Hexxagon** [comment]
Those groups are children as well since they are in the "Evoker" group. Groups in other groups are also children. I asked this and got it answered in my post.

**Comment by ChabWoW** [comment]
It's not its "own child" like the error message implies.  I also tried having both groups outside of the "Evoker" group and I get the same error. I just can't anchor any aura to another aura. Those 2 very simple progress bar cannot be anchored together.
![image](https://user-images.githubusercontent.com/20584297/200140585-cdf14317-fc2a-43c7-a909-5275423eeb5d.png)
![image](https://user-images.githubusercontent.com/20584297/200140602-d8b5b519-2551-46bb-878a-cd3a42d96e9a.png)

**Comment by InfusOnWoW** [comment]
Right that very much looks like my check is not working correctly. I'll investigate that

**Comment by InfusOnWoW** [comment]
Should work now.

**Comment by Pahn1988** [comment]
> @Pahn1988 please open your own ticket with answers to all questions of the issue template

@mrbuds was the same error with the exact same answers to the questions thats why i replied in here with the error from bugsack. but its fixed now.
