### ISSUE TITLE
Show Border Around Text

### ISSUE THREAD

**Issue by Dohtur-Frag** [WeakAuras/WeakAuras2#3991]
### Description

This Aura:
!WA:2!vI1ZZTXvDCl0KP0fyiwjXjXjbBsN4MKM6y70ytcqtSCKXUJRJzLsD7jTVD3N0UXR29XBFsoYCHrqdUWKzycmWmahO6aN4KoXm9shFIHa0V1dh4S)tiN4iF)URSS(XAhZotSE7B)(ZpF)X77lP(GmH63EYPM82zQKXoJ92xAxtM1g2YaXcbEbY3lvQuP3ZmqAZLzB)b98bEU2nvbw14Yq3a)ZL6P)j9qlMhpTzmPgY6pSuPqUAP7h85PgcFAk5LrsluxW1lldQkAgtzE3T4PBfV(ankFY(S)S)7q3hzFNykI3nLKzPqHfoREOIjvAMLC9DdD0YI)O0AOKULlJM2OtiBV8PnT5MvlvIuVCPCRS2IpALSkYwyvLSzAek4EElBhQTxyvtEnUVkpsT7tAvCH5ZxOy(cZRxiBvu4McpwDUu3NvHhQPhrQ5sCMNYPdRRj5iR65xl3kR88Q(TnbT2oCoB8LPhFn3NW9EPRVIl9zEFqmqUzlMVLtGCTa8dMlKB1c50FEi3Ru0gWvVSR9EtpzEUvGVDX8kMkSnYTSpclPBvsIMvELKPyPFzSOwK2ICBZ8lONl3QTC9lfiRWi8BKw4slEoYOdnMPQRDR1)iVhlVZw3PM5J3LvvHc4HIiOwRj6E6rXWqTNZ8DJfXSWjxCholK0k3VSY51GZM1pWNVRncSeffjywggzZHnisjRbMlBfMR)IWSidWCW3bUdCx83H7FNMeFUXMqwVaM9IMkmrZxnIELQEkxTSySZAe4EA6wESWqAv2qmPIwyImxYTSwgRr3EvXBz7gsHVc8NOkgdcfNEsljkDm3fnsluST)G5QvRyYLWT0sKnrrLBfEr76yEGRvrLJKh6e4zxh(QPeZLOEy1cCTXycFFfzZTqq0ROqIlOO)jexlboNzYBnPRIxjpxTkgkBVnmNy8d3UIFlf8nXWJgmSgKrtC5eTQ(y4AWvZwkWxjo5Is3Tg)hwLztjtJxOGy6KuhtkRFe(Z1tuNvyHywF9EbCiN4MhR4Jel2QuKQ)09XYnj86zvidhIU6NBlQfJrIoZagwzl7IoU28IBXLboIBKipulqmp3RF3j54JQh4wC7JJzy6wUOFu2yBseJmVPPKxZLP4RWKL5X5QHhIfoqI3(aoSGwtSrf3EDxBLZp7RlUAI87qMt)8IDWvEU(yh5hvyLLxnN4wVAEtib5ohjM6QoQKR3mXILKkv2n0HzhS5hfF6Xfh6yMPX6GYoItAvnufuHy4rcBClyS9W(JbuxqRi8l784RWP(RN4RmbC6TNqCYQH8EkqmI3IjReiBVLJiZG(AMPeNPhClaxWubYmV7l7ZeZm1oDRbIZEkjpGtrMiDBggiJoU69dS5TnitVaRn6yJNP7x7saWyVCbhgDWlxoE0rpIZ1pG1L6gPJKvugQQJdFHecUDXxKf5X5wo7ZXEhy4rgn8T0eNI2RpTBeRZi4TxDUt3OjIrNTVcSUCYZaJelMbTsJDO9PdTWzouonO3OjcmeNosV9vLzaFB4YWOWf2PBanZuWfHlfhm61kAhm62unGZRft6(UkDIQFzmBSFTLzQ96vCOIolCrX5hO4VlN9n0Om1tV3(EIBi9xNw07U(ecWD2TmhlYDTY7eS5d93lm6NfcWJ6c20h(XgVmI4dQ5mA11lzlW83Ov76aLlZZzx6fQ3DuxChCwbICWZOjDekt9iAeR4O3o7l5iXgzKhqJbbJWy7M7hv1vub9RXrvckJg7ZqkXWeh9y9g7fnHGBjekPbk0OWDmk8NHFDk43yapf(5rsEBd4xzGi4ZGXGNdFYmpyT8hq82NQjjBAUJLTngKZpb(freJba0ZI8dozNcUnj2D7cYq(nJLZiMHyO1J)XOxG4k8XgWynxGS3BMhja(LoXk)3c)oJ2sMOCm4pgP2F)iWF4zeFXwzlSb3JR6JtjxJpdZVUyyw06cXZIsfs)LHexiXjiIxOthuzdtSPyIx1b)Dop5200G9pr339vpJhCc6geW3V2ZJs2jNUDSQidh0LaOji37EZ(mJFQbImVlnChmpUPCT5xz(hS8Q47Tlv6Hnh4(rKML(BINyK8WvW3yPp)hm0q)e8MhIRCudo158O0W7mkgY3fNsMUafDfhF72h88HXh8KorOSN(TDMf6To8HhgCOZedKHDCMg0eD09SoVy2J1bFdmXbSEIQWVJkA11xf)henV744Zv6544XVspyT2cOwJjBalqBjQz2DPV0DdrT3hF5Urm0B3on6(t7lRbBDRnp1fmsC93puBnktMKz3P00nnS2G2T7OJ2HmGvcJnAHB5iU0HK50g1(0ehdTN8Hbh7PXM4f(wxYenwV9c4nHRMyQ97K89gU5X2jCy((CpNeJ9DYv)uDR4RTNEP793oh9mAAXBC43n5GkgXBFuvwjC3QPBnfV6wZDThVi3A9d56Cj4h4)mKpgNFZTu9SRKBXcIjpUJDUF9iEXB94HEUystDw6Ggh3in82WKjcaQbaGB9)5CO4mdpz4JzrCctmNuNSKsrAf326G)7yGV31Nq3YHBTXSWPVXqnQXKUmtp(mZV6dmJ2p864xED4fzPje0RX8QYtJ7Cc4fW)c(IuskxQmpC0jGV49sNAP7brpFz6gcjnrIQo8zZc)9iPJS8pG)jjVVwm3KGET2cYeV0Xg05Oqhr9IlqpJMg(s4ZGBocmLXX7EvdcqzQ9V)W)h

----
Must show black background under text.
But. On game start or /reload no background at all.
Every time i must open WA and uncheck/check "Show Border" for show background.

It old bug from WA 4.x
[BackgroundShow.txt](https://github.com/WeakAuras/WeakAuras2/files/9947474/BackgroundShow.txt)

### WeakAuras Version

WA 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Start game
2. No background
3. Open WA
4. Uncheck and check again "Show border"
5. Background show

### Screenshots

![MustBe](https://user-images.githubusercontent.com/88601137/200208951-0822b71f-3346-44a9-9733-5f7759fe69f0.png)
![ShowOnLoad](https://user-images.githubusercontent.com/88601137/200208953-eecccd46-6c0d-4935-a995-d66bf0b431c8.png)

**Comment by InfusOnWoW** [comment]
This is because Texts are somewhat special and dynamically resize to its contents. Groups work only with the "static" size of auras, and don't adjust to the text size.

If you put your aura into a dynamic group instead of a normal group, then it'll work all the time.

**Comment by Dohtur-Frag** [comment]
Thx for advise.
