### ISSUE TITLE
ADDON ACTION BLOCKED Bids do not work

### ISSUE THREAD

**Issue by Kime086** [WeakAuras/WeakAuras2#3993]
### Description

When I enter combat My Key bindings doesn't work.
What I can do to Fix that ?

### WeakAuras Version

WA 5.0.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

61x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Frame:SetFrameStrata()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetFrameStrata'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:5414: in function `AnchorFrame'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:5267: in function `func'
[string "@Interface/AddOns/Details/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <...ce/AddOns/Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

### Reproduction Steps

broken is only Bind with mouse wheel

### Last Good Version

dont know

### Screenshots

![Screenshot 2022-11-07 16-34-31](https://user-images.githubusercontent.com/30907824/200355622-a8fc187f-f7ec-4f59-98aa-4850048884b0.jpg)

**Comment by mrbuds** [comment]
Bugsack show 398 errors, try clean them (alt click bugsack minimap icon should work?), /reload, and start from error 1.

**Comment by Kime086** [comment]
![Screenshot 2022-11-07 18-04-42](https://user-images.githubusercontent.com/30907824/200370898-51eda5be-2a0a-413e-8928-84997630064f.jpg)

**Comment by InfusOnWoW** [comment]
Okay, that's the same error. Then what I explained stands. You have either have auras that create SecureFrames, or this is just the pre-patch which has several taint issues.

**Comment by Kime086** [comment]
I found that Aura.....
