### ISSUE TITLE
WA Castbars not working while in Meta

### ISSUE THREAD

**Issue by Effeh** [WeakAuras/WeakAuras2#3996]
### Description

WA Castbars not working while in Metamorphosis. Maybe other player transforms too, not sure what else transforms the player.

### WeakAuras Version

WeakAuras 5.1.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Use any WA castbar on a DH. Afenar's DH weakauras contains a castbar, for example.
2. Enter meta
3. Try casting something; no bar.

### Last Good Version

WeakAuras 5.0.5

**Comment by mrbuds** [comment]
We need an export of the cast bar you use, and you forgot to tell which spell you cast in your reproduction steps.

**Comment by Effeh** [comment]
Sorry; I tested it with multiple castbars and spells, so I didn't think to specify any particular one, which was foolish of me. It's all castbars and all spells.



Here's a castbar it doesn't work with:
`!WA:2!1vv3UTTnu4iyGmuJLIuVUGfGInVG1HUH10Ft3)yZkvEXnP2zYknTDzqHsKYIlYKeKujX5UAmm0R9tWGVEx5hHEXUMWypb5ripbJKslETOjxeCohD(9JNZNDAwRFnyn4lV1ybdWpyxmuM((JXXusxAopgDT54h3jjrGKo8bLctaK4ukFBkMiJw3RDGN)uB0(ujqIPeh2vEn9htHi3g7e0X1K40HsoUxpexC5pLxk(3UYbmKBoblz1YfOqqKGYJ2abYmbV)PI8i0HiISBEsc(4jHR3OBqy3Gg(bNoZDRR(w)CxhiKNh12CKok)UB7T1wtm(lyOSSwW0HLcIQdnMn1FF1LJyzGbiUpb0hjQogII0vnq3G8n82A7M7S1OCszJxLDfqSeFikOq30c)1CwammMMr5pQI(VZ0ifItazprp1Aa5OrcuwIfavZpmcWxVWvhNk6QjaYCoqIsFLfflq9N5mwpn(OE6WfpAj1ct1QrG4d6XP5eyPHekhvy4LlZ(yj6yzO9FA79bYqwOe3hfY4OySPpQm6Cxw56mw9lkG(uyOPJ2)u7hN18xI9EwlGCjv7po2Ua52qREwrEWhJGwJVG9jxu6Zq9aXdctYOuE6RSo8B5cjozGA(XCZsekqB0TDN2EtlJNinpiUTPeKAbUE0n2NwSz(0Yf1XwFN9mm68yzl2KJpP(pNdG65cupiGvRy0sbq6rLjOYRz8zfgV2CSLFldsHGVzEGf94ruoCxoGnC3sHIj7qnYhLH2NTybYn7wACR2T98d3YRza7dViSQqZPm6IoRy7XrV9mdD6IpbTm7ZUO0ahOxUXXHYuosKsZGdkXUYP05Lxv9TvuF(kxNO8SPw9fQlPUPAv1TEHAdh1DuZRUR6EQfupq9vw0v91QVr9DxBo1pO(rvJ9vUtkMh)w)0gbQ7Rwt1Cz1x68wqpsPGlr)AgLIW9sLFKBgfaBgjbz6d4L87NNjXvD13RXlP6u1podiegjxHEsncNAVwC1UdnxH3TXdFiBr9vDdOzzcbrWhdoo9U5y4KJePD28(34Eh0U9iab33Ys9aFHeWLnFfciqDLCePNm9D0d4MtHM7rTlHgwkUaPVUHIHg)mlHQnD7dWKMQNB9w9lQ9u)QAZOemblsFtZVzpHjPJ52ZAlddqxknHa3WQOV0FG6zvvHvD1PswDQ(mt)e1Hz)u1rwwgbgI8Ty8)NU4Por6pMG7vDI16gwq975gypNJg6MHp5eahojHRj50tR(kOI7juAFhFBaPJL04dlOR(aN)4pxbdzx1qQw3fWR3Q(J09F9hdGOY8JHqeXVT3t889bzSuqLZkwOAAkGz0I6UUVNxB)JmSb)(7w8doRF(XjhtmL7)y9ckAu2nAzOotaXO9mvht6PR)E706MZ0UzxtatOCSEtX(onEJo(TEEN2bn2AS5TcxaytWKIfnTw1ZMrEE(9Z2vU9QRvt4V2Q3z1Bx7W)5P)7`

**Comment by mrbuds** [comment]
I can't reproduce your issue, but your Lua error is pointing to a problem that is not connected in any way to the cast trigger.

Could you include in ticket your weakauras settings? (WeakAuras.lua in wtf/account/etc...)

**Comment by Effeh** [comment]
https://mega.nz/file/9mRz0bBT#ZapWlsbQMdsC3MSA46Z6NX096aCC4nb5WhGitPnk-HI

**Comment by InfusOnWoW** [comment]
I can't reproduce the problem with your imports, nor with the settings file you have.

At this time, you need to provide a better reproduction list. I very much doubt that it has anything to do with Metamorphosis.

Also make sure to rule out any interference by other addons first.
