### ISSUE TITLE
Dynamic Groups breaking with 5.1.0

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#3997]
### Description

After installing 5.1.0 if have a lot of issues related to dynamic groups. 
When i log into the game i get the lua errors listed below and some weird behaviour is going on.

I have a normal dynamic group for my class cd's in the middle of my screen and when i type /wa some icons of the group just disappear, typing /wa again will make even more icons disappear. when i type /wa again weakauras options will finally open.

After the wa options are open the addon still seems to "create buttons" forever.
https://i.imgur.com/LjB70iH.png

then, when i close weakauras options all my dynamic icon groups are just gone from the screen

Since the dynamic group i just tested out works fine after deleting all my other weakauras, different weakauras i have might cause the issue.
But since nothing is mentioned on specific auras in the lua errors i have a hard time finding out where the issue comes from.

I will try to update my post with more information but currently that's all i have.

### WeakAuras Version

5.1.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

LUA ERROR 1:

1x ...erface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1336: attempt to perform arithmetic on local 'regionLeft' (a nil value)
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1336: in function `Resize'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1292: in function `DoPositionChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1137: in function `PositionChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1118: in function `SortUpdatedChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:923: in function `RunDelayedActions'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:914: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1380: in function `ResumeAllDynamicGroups'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:735: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:699>

LUA ERROR 2:

1x ...erface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1336: attempt to perform arithmetic on local 'regionLeft' (a nil value)
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1336: in function `Resize'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1292: in function `DoPositionChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1137: in function `PositionChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1118: in function `SortUpdatedChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1015: in function `ReloadControlledChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:920: in function `RunDelayedActions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1178: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1121>

[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1273: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1224>

LUA ERROR 3:

24x ...erface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1336: attempt to perform arithmetic on local 'regionLeft' (a nil value)
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1336: in function `Resize'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1292: in function `DoPositionChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1137: in function `PositionChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1118: in function `SortUpdatedChildren'
[string "@Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua"]:1066: in function `RemoveChild'
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:795: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:770>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:840: in function `Collapse'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4449: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1342: in function `Pause'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:775: in function `ShowOptions'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:614: in function `ToggleOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:155: in function `OpenOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1024: in function `OnClick'
[string "@Interface/AddOns/BigWigs/Libs/LibDBIcon-1.0-44/LibDBIcon-1.0.lua"]:144: in function <.../AddOns/BigWigs/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>

Locals:
self = Frame {
 0 = <userdata>
 controlledChildren = <table> {
 }
 AnchorSubRegion = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:453
 subRegionEvents = <table> {
 }
 SortUpdatedChildren = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1081
 Expand = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:963
 yOffset = 22
 anchorPoint = "LEFT"
 SetOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:319
 DoPositionChildrenPerFrame = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1147
 selfPoint = "TOPLEFT"
 sortFunc = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:258
 SendChat = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:267
 controlPoints = <table> {
 }
 OptionsClosed = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:753
 suspended = 0
 cloneId = ""
 regionType = "dynamicgroup"
 relativePoint = "TOPRIGHT"
 SoundPlay = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:249
 sortedChildren = <table> {
 }
 UpdateRegionHasTimerTick = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:410
 SetXOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:328
 Collapse = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:960
 RealClearAllPoints = <function> defined =[C]:-1
 RunCode = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:274
 IsSuspended = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:895
 GetYOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:340
 SetAnimAlpha = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:392
 growFunc = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:456
 SetYOffsetRelative = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:357
 PositionChildren = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1128
 needToSort = false
 GetXOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:336
 SetYOffset = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:332
 Resize = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1296
 needToReload = false
 needToPosition = false
 GetYOffsetRelative = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:365
 SetAnchor = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:307
 GlowExternal = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:282
 RemoveChild = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1059
 finishFormatters = <table> {
 }
 ReloadControlledChildren = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:984
 AddChild = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:1021
 subRegions = <table> {
 }
 currentHeight = 16
 Suspend = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:899
 Pause = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:966
 SetOffsetAnim = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:369
 currentWidth = 16
 Resume = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua:908
 yOffsetRelative = 0
 ClickToPick = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:758
 regionHasTimer = false
 needToResize = false
 xOffsetAnim = 0
 yOffsetAnim = 0
 values = <table> {
 }
 SoundRepeatStop = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:195
 SetXOffsetRelative = <function> defined @Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:353
 SetTriggerProvide

### Reproduction Steps

Not sure how to go about that, the dynamic groups are working fine when i delete all my other auras.
I can upload my complete sv file if you wish so.

### Last Good Version

5.0.5

### Screenshots

![](https://i.imgur.com/LjB70iH.png)

**Comment by InfusOnWoW** [comment]
You need to give us your settings.

**Comment by Nokramx** [comment]
[WeakAuras.txt](https://github.com/WeakAuras/WeakAuras2/files/9956444/WeakAuras.txt)

I renamed the weakauras.lua file to a .txt file so i can upload it here. Hope that works.

**Comment by Nokramx** [comment]
i can't even re-import that group after removing it. the import animation bar will just be stuck forever.

**Comment by bloodstrike** [comment]
Having the same issue with a dynamic group anchored to "TradeFrameCancelButton"
