### ISSUE TITLE
Beta LUA Errors selecting tabs other than display

### ISSUE THREAD

**Issue by KappKapp** [WeakAuras/WeakAuras2#400]
What steps will reproduce the problem?
1. installed wa beta4 with beta3 aceconfig file
2. in game, type /wa
3. select an aura, display tab appears fine
4. select any other tab. Nothing appears and I generate 4 errors.

What is the expected output? What do you see instead?

Tab content. Remains on display page.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

Yes.

What version of WeakAuras are you using?

beta4 with beta3 aceconfig file

Was it working in a previous version? If yes, which was the last good one?

first time using wa on beta

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

ERROR 1:
Message: ...ddOns\WeakAuras\Libs\AceComm-3.0\ChatThrottleLib.lua:216: hooksecurefunc(): SendAddonMessage is not a function
Time: Wed May  2 10:36:29 2018
Count: 1
Stack: ...ddOns\WeakAuras\Libs\AceComm-3.0\ChatThrottleLib.lua:216: hooksecurefunc(): SendAddonMessage is not a function
[C]: in function `hooksecurefunc'
...ddOns\WeakAuras\Libs\AceComm-3.0\ChatThrottleLib.lua:216: in function `Init'
...ddOns\WeakAuras\Libs\AceComm-3.0\ChatThrottleLib.lua:512: in main chunk

Locals: 

ERROR 2:
Message: ...ce\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:69: attempt to call global 'RegisterAddonMessagePrefix' (a nil value)
Time: Wed May  2 10:36:29 2018
Count: 1
Stack: ...ce\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:69: attempt to call global 'RegisterAddonMessagePrefix' (a nil value)
...ce\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:69: in function `RegisterComm'
Interface\AddOns\WeakAuras\Transmission.lua:1221: in main chunk

Locals: self = <table> {
 embeds = <table> {
 }
 OnEmbedDisable = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:295
 callbacks = <table> {
 }
 UnregisterComm = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 RegisterComm = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:61
 frame = AceComm30Frame {
 }
 OnReceiveMultipartNext = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:179
 multipart_spool = <table> {
 }
 OnReceiveMultipartLast = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:200
 SendCommMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:84
 _RegisterComm = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 OnReceiveMultipartFirst = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:165
 Embed = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:287
 UnregisterAllComm = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
}
prefix = "WeakAurasProg"
method = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:1221
(*temporary) = nil
(*temporary) = "WeakAurasProg"
(*temporary) = "attempt to call global 'RegisterAddonMessagePrefix' (a nil value)"
error = <function> defined =[C]:-1
AceComm = <table> {
 embeds = <table> {
 }
 OnEmbedDisable = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:295
 callbacks = <table> {
 }
 UnregisterComm = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 RegisterComm = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:61
 frame = AceComm30Frame {
 }
 OnReceiveMultipartNext = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:179
 multipart_spool = <table> {
 }
 OnReceiveMultipartLast = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:200
 SendCommMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:84
 _RegisterComm = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 OnReceiveMultipartFirst = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:165
 Embed = <function> defined @Interface\AddOns\WeakAuras\Libs\AceComm-3.0\AceComm-3.0.lua:287
 UnregisterAllComm = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
}

ERROR 3:
Message: (null)
Time: Wed May  2 10:36:29 2018
Count: 8

ERROR 4:
Message: ...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:66: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: Wed May  2 10:49:00 2018
Count: 12
Stack: ...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:66: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:66: in function <...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

Locals: (*temporary) = "igCharacterInfoTab"

Please provide any additional information below.

When using ElvUI, it only generates 1 error:

Message: ...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:66: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Time: Wed May  2 10:51:15 2018
Count: 1
Stack: ...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:66: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
[C]: ?
...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:66: in function <...Libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

Locals: 

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

it's all of my auras.

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by InfusOnWoW** [comment]
Try replace all libraries with the ones from beta3. Not just AceConfig.

**Comment by Stanzilla** [comment]
zip was broken, new one up now. sorry. blame curse.
