### ISSUE TITLE
Dynamic Group not working properly when auras were anchored to frames

### ISSUE THREAD

**Issue by Zac-oihfdwrrtuinvbcp** [WeakAuras/WeakAuras2#4004]
### Description

If you drag a group of auras into a dynamic group and one or more of these auras were anchored to a frame, you will need to /reload the game before the group start working

### WeakAuras Version

5.1.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. have auras with some anchored to random frames
2. put them in a dynamic group (the dynamic group won't grow properly)
3. to fix you either take them out and remove the frame anchor, or reload

### Screenshots

Here a group of auras that are anchored to some random frames:
![image](https://user-images.githubusercontent.com/109383107/200682448-c39b8dde-fc62-4c4c-b0ac-64679f9f68d7.png)

If I drag them into a dynamic group the dynamic group won't grow correctly having every aura stacked on top of each other (this is hard to know what's happening as a wa creator because I now don't have access to the anchor setting of the childs auras which of course make sense, but make this issue hard to detect/correct), **this is fixed on reload**:
![image](https://user-images.githubusercontent.com/109383107/200682697-ccab5cd5-68ff-473e-88f4-30e35572ed58.png)

If I then go and change all the auras anchor to "Screen/Parent group" instead of frame before putting it back into the dynamic group again, it will now grow correctly
![image](https://user-images.githubusercontent.com/109383107/200683137-7cd85f28-2642-4e4a-9880-d18c1ca08630.png)

**Comment by Zac-oihfdwrrtuinvbcp** [comment]
> 

yes does the same on every version, sorry about that forgot to update the ptr one were I did the screenshots to not mess up all my retails aura

**Comment by InfusOnWoW** [comment]
I cannot reproduce any issue with those reproduction steps. We either need a settigns file with the pre-drag setitngs, or a better description of how to reproduce.

**Comment by InfusOnWoW** [comment]
Waiting for reporter to clarify reproduction steps.

**Comment by Zac-oihfdwrrtuinvbcp** [comment]
> Waiting for reporter to clarify reproduction steps.

Hey, sorry for the delayed response, Im not sure I can describe a better way of how to reproduce the issue as I was certain that it only needed some auras anchored to frames and then putting them into a dynamic group ( I must precise that the frames anchored don't exist anymore, might probably matter I didn't realize before)
here is a link to the wa I used in the example in the bug report: 
https://wago.io/nRczo4bxT

You can reload the wa on import to fix it, or get the auras out of the grp and in again to trigger the bug, the only correct way to fix it is to remove all the frames anchors

**Comment by InfusOnWoW** [comment]
Next time just ensure that your reproduction steps are actually reproducing the problem by verifying them.
