### ISSUE TITLE
Spell Known trigger returns true when Spell isn't known from talent

### ISSUE THREAD

**Issue by Luxthos** [WeakAuras/WeakAuras2#4005]
Spell Known trigger doesn't seem to work properly.

Currently on an Unholy Death Knight Spell Known Trigger with Exact Spell ID 152280 (Defile) will trigger even if you never learn the ability from your talent tree.

This wasn't an issue in 5.0.5.

!WA:2!DrvZUTTrq4O6w0cEOiMX1ibOhesrl6jHMuKa0EZuwY2PksUK012NexsouCRP2LD3Lsw(w0HcFwpc6CpPhb)eqquu0Z(rWpbD2vu2X1hKNF(2zMVHZmn6Ap2o2o(6VzjnIZ84fIi4RFI4Ybjjsq1qmRwyfHfLYfhZPmvy7o9974wfX5zX8PmVP0Ci4MnQDIhbPo6WfmxjOJgbc5x(DIAXRTZ3UqcdhbmqqJ8s5thWcQEK6TsZ)AxhqNcgvfMNrMbILXqyrsI)SCqCyNEh39KEokuXvMdzz526qtcLCr4Haj798yi4wzrimbykp8H0lxnS9EE(d983Z1FUgUo6bUgeR80rP5VWWSM)mTt4ssKAOj49jJHGkbgwVnQnQ0yEW7CJ4rXsRBFOqmfXI7b98pX9FVVKowayj56DCNE9wOFIsqIUiWLHaLwlky1DnR8TX6Gob8xRRJ5F9K7WpgGGrY(nSft5SP3Dba57HPks5suuE6cjKLy(Ov(zyRtsufcIcsxIfGlmcFJ8N3T0UcvdXepsWlyXxVtUTcUePDkb7)NvpcK)cJrZpjCXyccOwWHXzWI7D)YVvM)0pkcT5zCX7A0OXw3U26MIYzVt8hK)mJrsHIJHIgDknwL6ShQE36CrVeIng)q16PWZRROBm()9cPIMmdjOGRqY5JgD6pOFNsBbYlnMLgGrMYyl8Vf1KGPYFAxb9QM)AbjgBmKM((pI7BYuLX2uUi(ubjF(P1cRlGjujnmdcQ58hTPKV9r973XDOZaF)bV39Odo0V6(u7rVcErnJo7r5r71mHp4e)Eh1VZ)unkJpTRa(JcGfn74p9hA963SMDAhR0)SjcZ1k6hxfwOuC2GjGa3CwQn3dyJuPFLb)gMTqR0((oZn4q4bBSK6ODMAYUFkn6cgiLBzEHxejdwl2JIM32KahSVaI0WuGokv9bNmojUBOcHYu76oUitrTC0JN7wEULBugrk1sosSvOfwkmZK6YV8lY3zZff9x09Psc2KJtxqyu9CcN9wxPIiuDVbisWtjmS7ZlTlBvfRhZrid13gesapgflNRXzIDlNXekRBjXGUmSmQmUSvycLrLP)FZROS1t5y8SCNAgeDUIZh3qO3jXvO3wgyvMy5GpxzTuXJMSEF85n(ZLVKgNVZ(arL2KWIBUperM10hKk3hghxLiW9DKb4e4w3TEIOR2KUyd9A72Pt)xxqJxDYrN7(tF)O3DqYpgIukHoYsqz6SbPMBFBozI3hWdaqGljlpLS1sn)PMA1A(MUAqfUYHzAq(Ah2s3306vTEL9K)(S)7

**Comment by mrbuds** [comment]
It's working as intended for me on beta server

**Comment by mrbuds** [comment]
PTR servers are down and i don't have a DK on live servers

Btw don't remove issue template when you make a ticket, i'm testing on 10.2 but you removed the field where we ask wow version

**Comment by Luxthos** [comment]
This was a mistake, I accidently removed the template when editing, and couldn't create it back.

**Comment by mrbuds** [comment]
I was on wrong branch, indeed using IsSpellKnownOrOverridesKnown return true for unknown spell that would replace a known spell

Defile have spell id 152280, it replace spell Death and Decay, Death and Decay is known so IsSpellKnownOrOverridesKnown(152280) return true

**Comment by InfusOnWoW** [comment]
yeah we need some more complex logic to handle that case and handle overriden spells differently. I need to look at the original bug report that lead to the change too. I do have it on the list of things to fix on the weekend.

**Comment by InfusOnWoW** [comment]
This should work in the next alpha/release. And we'll probably do that release soonish.
