### ISSUE TITLE
Dynamic Group - Custome Order Tab

### ISSUE THREAD

**Issue by Jerks88** [WeakAuras/WeakAuras2#4006]
**Is your feature request related to a problem? Please describe.**

If you use a class collections from like Afenar you can rearrange the auras by moving them around inside the Dynamic Group, but if you update the WA collection its being overwritten every single time.

**Describe the solution you'd like**

A mechanism to override non-relevant author settings wich is being untouched when update collections/auras.
For example a custome display settings tab (an equivalent to custom options) to rearrange single auras inside a dynamic group, override fonts or used bar texture.

Regards,
Nico

**Comment by InfusOnWoW** [comment]
While we have longer term plans to improve the display and selection of what to update, selecting the right update categories mostly does what you want already.
