### ISSUE TITLE
Condition based width adjustment displays both values

### ISSUE THREAD

**Issue by LukasNoxio** [WeakAuras/WeakAuras2#4008]
### Description

I have made my CP's adjust in width and x-offset based on my max cp. In some cases (mostly when I get multiple CP due to proccs, i think) the original width displays as well as the adjusted one (maybe only the border adjusts). The bug always fixes itself on the next cp update (spend, generate, timing out).

Edit: Reduced WA import to necessary stuff

### WeakAuras Version

WeakAuras-5.1.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Generate and spend combopoints
2. ???
3. profit

### Screenshots

Bug with complete UI (border different because of elvui):
![temp](https://user-images.githubusercontent.com/20885653/201341562-bac87b96-1e8a-43f7-a890-bc0417a5fe81.png)

With all addons except weakauras disabled:
![temp2](https://user-images.githubusercontent.com/20885653/201341607-c200f661-588a-4051-99c8-34947508e0ea.png)

### Export String

!WA:2!nV1AWTX11zTcrwJHvsKOSOLOF0nkX0KYw0eGIupIKTiiHeHcjina0tBfGfyVe7kTC3v7UGGqn9HPZ4QoJtDdtBsBtZ0u2y34PPpg4mjPjTDszAN20MPZzyADzDt(rzAITZRMQ0M2MotBpN7DbWcaczBv3obJf4I79U3hN73335CFyPZ0LBQHhiYar6AUUu7s9A3965TCuzoXukCzvhlB7ThZq)QxvXrvoJLLHNU9QkL80SCM22t3Y0nStLPNDwxMNXTvvXSaMXmw6ME5hlEYmXtvvuzJzzy5CkjjPqokf4V2iPC9uC8cht3u3lC(zX)4QfErph9IfzoU90RJ)Jp5YQS8LMD2mvSzoteFYzoXPNmMh(JukLCuIUORnZWiHQB41DlLNnpZ0lnwA9fQMDSrtNjB6mJMktSsyJK32qPcZPEXMXHHflv6zIp5KP4PKFcMIHNwktL5yUHxQKPFxi81XbeZXuX4myxd79LxsXuFofAGmce(eWoIzAzYwHP4Ys75Wml6PT1vvXUhvISuN1XLvWYu1DrQm0qbKJnNIUj(UGm822kSx4TdVd8XT1AklJ93uSICtDmdlf1ZK3tXa7TDNAUs40ryNRITnAa2CQcgkUUDd9hogAukiEq)Qm6HvZ7pDkMjcfk0mHgCGHt5waRRq5fZsAll(BC1Im7DK(kLuCyYNOKHH8z109yl7W7guVpvrhRs2(fpn2gBzfXZcOWTUSNvH5f2QDl9KF09QRAFhJr9o59lNYQyjMCkMRvjNcm3QZ6GMB0SP4Pe66ce0jOKO2jF6XsfpEY8OTBw9IH9rtjmX2i0sUmJz5yTLJnDMmtp1KXprMOL0vREgd25p4e9DfRl1)YKvxxauRQBoRLJ)0M9U1lAA5W8rXXP5)4oowoU5QILQaJNc(d(ivmSY5SG4bPUk8zVwKLDTvCU8z1v9021Y6ydLMpIURnbB5bUf4wGTUkVaPS84nPK9oA63tzPYIn6PZmDm6D1G38BPx4T8coLCzjXrFo42HDTk2zlOXCtRzvEAZvC5)zuKanpd6bUty3WEwMG2Xxq31ZvBjIrWbV9KFOidFGdpcSZWq3WDa3vyhRYMtBAujhcV6cERW2H7oS9ou41vgbmN6qFInXhjzludMecUNYWdbBDX8k(S4jE4V5NL(85ie0HM4H)B4FEHqip1vXJa9mTv4JuHX68sqVNQByhRIazcfsgutv)eqtntKW8WowIkbFgEvXFYkGdrX22FQplbOd5d287LKSIVOv251D1ZBWYvR4mek7erEg9fyg1QulXC41Uh794XwWll)lbYiRP)dGS97OTmTZMxVywZsZLhRfrA27y085DyZRJJ6K8mCxv0PpVpuXwEdQhp95yzNZsnlzTYz3FNkIAfC6uVqwpnhgo7BOwzDEPQd9HjT3jpfut2IG2f44XyJI)86Ikeh6Q8eF8ny8A7)qErNFdh08EIbROsHkzN1WYYrBfEbUujxp9zRaBDzhcsZYGjgl50jJB3LOtQPOAv(Cc7qi7ThiXg(d2WwuLvaLxnYA7GpqIisWoCqWbvk77PtDrXVKwMNvda8s(ff1jIVawJUULvQigb(Ofn)oCttCHAAu4N4DTPv5jwgrsN1rXEXZ6)WQ1BeUFQPpDMjtGgIThOE5ZxRKizY4PYkCoA)260qP(a3V3tFT37nqRqAU7YhPDUAiT7EdQoo3I7ckfFUlVgtVOM3EGJunD8jJpwMtKA0PId33tUek8KL7bjhC)9M3v3SOblvQPp5PJJ(pwNNdosuZs(w6fE6mBh6FKX3EUmBp3b2EoOpYltvQoMNPPxGBuRxJ1Fpn4bWxDlq)DVLCW(PxzDUsrm0HMkP)eD0Xh3E74loQkbVyQm1Puwqd(X4(zrVIKZXA(kV32szBTMY1BO40aZb3kwBHHTfgUnS9NZYYtBghRIe0ixRnUoQmpKdjSIIqWBkCqLTZjTexS0vxfTujo5ezGJxDWhP8zDNTYKEjgcoA4Q8Ipb3MFmhAQPKdBL0xgDQIthLzodlQWmICS7lbfPXSkfyp2yki9YSymfNh70j2FJFT)0Cl2vTSMtkf)L1GdsEz9BlDvvMzQKXpt8uPumS1ucbhouQYKcGx3KN4UsBOxGjJZjYJtpG1PWvw9ydc5OBsUVzAWjLQA5OJUc5(SwEIPtL4ctNmZOtcX2xVPqNtfU8jG3sOfNxXrxb5sRZwWwxe4tgejNAEfJsS9o0G71YEVh9yof0umlI(N6fQMBrBmEeMdIn7c52dCGbcYj7f(DhbRx43lg51dQkbpFpHHX6gIJtrbIsG)LD3NLPC5rXjj3Je3K5uSIikJRDV4mVNHUjdEc77xv3LcbmZRfz2vBH2tUZTL7Cn4R9yV9ciWXAoQeN2wfffHEwVzPzyUGWpHx)pf3Pm6WhMEvHt(P0Djgi3lp5aFNHVoIlJVa6WoTiG3COtDkaGviSjpiyDv3EG0((2Ht)j2K9DUHDyXdPO(Tk6DFXAIzWJhJKwG3d0BpO7z4cW99bH3FhO6WsAWhqd(5YfGrVmNWBnxEfpsdbEA4NNkjNNVydvRM9ladfJM3HTSTBX(T3zdCdfXBATaeldXc7472kgfUOG4qKIEANui7pjKkqWqhoeCe4DI08twktYr6x)SNAMtH0CuyOAG(E10jhxEQePtNi5jR2QhVLB4r(9UnbIgEO8IqyV2qlAHepSAC7HAqjibfoPeb)GtjbVlysyk)qf)g4yRBoOPNuZqsjlwBfhDfzfAMGqsJz5IZficYPKjFnoXi04s2u5jNcBLIqerrlsVafkjbRwL(r9IKlaIcot9ycfZcTS6L79vF9mWxudoBhdIeoNgulGr4c0xp68q2qWf3B(IGQeKtiGRKdYdfWCFSR1dusc(zqNJGEo4YO9XazyMpoCLCGdA0CbpOIeCPkyHxaMx86xvmk(XVEmuBZnMb6JaxA1clapzi4Ncn4lcpb8tdpo8tKdEVyDybFb4N82GRDVWpReOjbp1D(AJzSVnhGfq0KTI0KT674d(fGFr4dscSWhcnhF67G)P9hcHyl4dlrXGd)s5GFz0De8Ra)wIrWXRAp6P1uYmN(yzgd(vHpcSm8BapNx3WV2XGpk8Rt41pMe8I5eaD4zHFt4z0GpohfJW(vcQws44pHgmXUGFB43bzkWy9syZXZ5lyDBKM11oivacvIqEfF)KOl6qWw2dClozMEgIxL3LnhIJtfzGbhyqFGB0sog23PMNNT7rEWhSSsrRb0TEWjIK9SrTg58t9Gr4i7KiY(A7CP6iWCRwKH9r9cI1abZWLd)7Vv4RkWLihifVGDfzD(FZs(uu8SC27dDmu(8fG)2UIqsLerzNHxNQyL8UyGqu4g5Ir8cj4RKd(7GxKiciqNyYxQKjFPrrvmm6iWNq0iWoaWpqkBRTuiuVpoFIh(7Ep8pHie)sK24jmuk6cpHJ)YMdb9EKGCae7Fr4Dti(w4ai54PUdeDSoCFx72r)281RsamUnKi9oeEKRnl24acBgZXYGVXacWOJiNO8NvOTpHX3iboIU33AUDMJq1nGWlRQJfQqjdVk8ITVn7xddXBz75T93JckZ2jkXCWaC4T1SITdIxUgCfo1ihIUnJCIiNAIXU6C9pvqqyn4pYDEUNgo8wHpn8z40cu6GG4erajkiS3NgqScKh8mA1f8xDm0pLLmpOC5iebJtkEFWMJL0YSgxGte2hglYj4XIKYdxOJbuTRrOWzo2XGNhZRAz4tcpx3WN86(7oqkMHcHDQ)AW)TFXR21bfVcZ)vwtAtnyzFiAELVTmnizN89d)dHeoawh(EHQ5d4RdFJafh(Nq9QZey16R3zSg8MF3CggNw8YiDIW8nrN4mHVzn2ZlLJihVsxrjhfin6BlXjGeB6BLdjlyLDgE0l)X9KFOOdn8WhIxpFEUthYRX3jQIzfofQnDDcmtGAec3mMwvcf93saapoy21UK30M20ep8x9J8r(8BAts4GrrdlCuIzGeaCUgX)W)mhjDDUc83Nlc)V0aLd)R8V)b3iKn8V1cw8FN)7)d(3)N8V)HDavt69(ixe8Tz4)Iarc1csfW3nOVArlPST2sXhyBFhncTTzilH3pE1lnyFJCMiXpvM0Jxh6JomqKEZq)Vg8pUXy)OnfoQpjaPd(uSAKGJSrO5rcqaW)(L2ehrhOKeIpivH5xYhtQwjXG83cwYpfuneweKsyF70IbgAGM3qhA9c1Y7aTKxdg0uADG5eG2GozAMUCtRNJqUotZcWorAB7XZGq7nkCMx34ECUUjCFdG7)BG)isoiUFdW6)WaecKR5J7jPhe7C8QVRdM6kPoF88NYYTjHBcCDJG1rdgDtn885LEDGNhIZ8qCmsGqAyaD8J0mWSDn8necVHs33yi8As3IaVUM0wBaoRj8IkQKUlQL2SSljPwx2LuLjbuslgfErjyu4LKSFLUgQdcVhUvH31K2mP7kOe4Sccv8PdKXlaLiOaWgXnUjuVq23RUlOVvUo4b6v66anmfOHIg4I434do0u8sIa2(kBKLyKb7GLODM4niQQx3mXJ()jmrKBDt5bIyINVUkok6j8Niw(qRCMdWPzDKuoua6hs9igytROWNWrCBs594v7RVjkPNy((p7GNJyFOo8))6dzJjGVQXxHJY2yfczRwqSTXDBkKjeu(suitdt4vc6I4vcJtiybISje7Wh4qdDOoHyFdWnfs77mvKO7TXkEJmUSJx9kjIEUPFKrSs2)bFdneTxF(OABXfebbPSiHGWTi8TJW)dW9j9HLc6pQTLw0r)rdhmuaKbI8qIVCdcV6M33uXBwQrtbovPgF4HAoYPM22YKnVkceZFd8MH0gIa47m7L4oZqo0RGK)AaE47UH49Bcxp3yWoTiKJ8Amymc)IQd)i06koE1tmH7qZD1fY3)fCjijFRhHNR8nmOQH5aye11k2CeoCg5)nGZ(671wPmhZtyBF9DKU0a5ovBlqUZqYNAJ01jyExhfE(EqGj8X7SsTi4Lgc1Tam74kHFJFRAQd899e02MrHG6d2a430EpX5aF76B20lLliWVnC5RYg(8Jqb97diivn01FI8XpWfoDPKZKGRM8QjUochBEs96IRiASTG9RfTrR43dYHMKOAXgX6VrOYoTLnTjNIOro0TvezWDa9HHes0wpb5tXCSmmGTCy((Z)hibF923GZI7x3A(Hp0Cl8Gdfub1EVD(SoQFXaU(Lzm7rPdo1lfTZ(AWFc84ek8pfEpW99S0upFkD3B5l)0529wU0Ju)0yctWaXbVWpkaSkcEKm0C744CB34Cl8b4km)5HWzIVO9TxWYYq1QSj1Vgx3Lotp1CWlwtp4JtB6SrFZ(iroFHkPtRw7ypsuWYC33(p4fGFF4jYtJ9eJVu9Ho85URnTATkoDzD6qf(dZxIFazRulD6whH8RpZTgIyyDbPcdttXA1J9TZpVu(zZmMJLRBEltMl)SM9e3inTLPBiw9DigJSIoTSSIlog)EhPrHAf5WhEKbhIFMAeBT2(yTZE2DOB75HKA0MdFsA7tZwWQKPN260zzPBYMsClCwMoqLjTkZC9Oq1eBwCl91vY4uIjhJPq7e7As9PTMu)IE0As7ZVtm0q4A12GoXM)(tJDI1KEa8F7FnPb6yJSumhlfv6uN7ClmYg3ct(ARfQEshYApfZGDdAJd1EBe(1w9B3vQsEAgmxx5zQDWEDUDo4nD7C9yLC0zQYzCykULC60ybHfd(6QnE2f19yZr3tlj7DqqTMoKICvPCJzzwYnHASdgjYb4vAp2DNatxMNHCcv54xPKUTntLFAD1QWCWoIrpdV86IJcEmF(X1Rvk)kU25YrDN1KoS0Ashj3AsVtS9Igv0ERjDS1KEiScxt6HHxEnPJVM0ObERxGFoFom6EiIO1ClXpfzQpS73e4z3v9CQFKkO6yp27PwhsU2LMqUp(zs3p1QRIwAJ01QO1tH6JYEAmAqZCxQEvU3Odc7ifVbHxMtSg1OSsf3v9vReVEoAmXphdphLcxU(jr(DYloMD7U8pUDXfyBsRI6fwyZFYz5hEJLzF8lFGB)HLXpgwfumKDjLeeAZLqKpMSOepAKlgOmEif2Nb3OerdwI814FbQIHcwGIe9HZEAuGdeSaoc4FDWFJInCtneh(wd92OqJeSqIdywfTenkWbBQwmkzQYCYxYnq)9qblrb1gzCyrgbni0PEedLsPxFWg5IETK1pwKhyezvlrk0h9z9T7pQ(f7NM7nBUcA8J7ps9xIHQnH9FiSFT0xFbmJKCuZwJ(5P1O2o2XIksQGQygN301BbhMxjht(KROHmCzTMzFnQTJgLxx9zA5j3xFbHeuYnm59lJgH(AgwX7RnS58I0aY0FZ9sAaJ)Jhe4kWxOryRTEbhod)NVJ6hMEE6USX8wMFhFMPeoCA)kpSURNEHlxzC)lgGg892A9l3Xt9iWF2EYlUfU51NZ2YXdEt7dx9FEpRIfnyoQSzvkz4Pbp3wIr3Qu77KK3KPRrGCzY2MYlMSURmIEhBC6ERooZTqUOxMvzrHo4yJhdhVfSpBgnSyL1niSkwdkYnUQOQYCjIm1KiKPBufo7lxXQKSjJrZW40dfNfo)71uBopPSDM1Kol2fdTM05S3jDdxfTHUPS4MOSM0fqzKh1E7uEu)kH5y(zCr7(IBsb4GqfSoXgYQ(7xwthtVETGbWE3bcGT5RYm23CxSwym5GpBf4l)E3gmvo7E7CmEnDFk5hU)FboeU4cHEgHXcBl6I9W7mUcZnzrWFwYqvMFngLBwCvwPqblhvcIIJek5ILq8gD7Nqf68mdRY9t2nkhhEhh7D0BW5X2umoYhEGOdm8aHdlcSfP)OGQCFkO9Ew5H90Kpvjt2dihDWOr7)icYZ(LFxymQYIRlOC9atKv4Y5BuzcgHKWGZhDLOSLtxNyTrV6gfhyBvrSgmVMQdfZkYrLPicLfX1XPeYSfkWS9KdeWJ89l3sydOfzcetqwU6tmLTCUS7rcpDYjpFWjPwMtiOkVbfGJW7xoDZtOAkZZKnT49l32ZMp44LjIORhE)7xUKjpYP6VEDRoL50PAKrtM6rtoo175pNWCE9IwKOqt2CzevIArkovATM2qlFWACmlZcONF0OfW(hS(Kh3I5AEFE1Oxbh)rjfY5SqpCCZqTbizg9k7BBKP)Nri4Se9ulZtHdNC6mXpImNcH)NcwPQ6ZsfX)Avqa5MMgZtMxBQ5o50tN8ThjYHpuuKqGdbzfp5wxmxS0LJM4qEztc)rWCWZ9iWxJFfxIYVRR1IlAkl1u0Q3431YwWdjTklUdzVp4Ve(sWFv99s5O9UM0JHcv50Gvfl3p4fW5Jj118)1N7)5d

**Comment by mrbuds** [comment]
> the original width displays as well as the adjusted one 

I don't get what you mean, can you make an example with only one single aura and explain what from login what you do, what happen, and what you expect should happen?

**Comment by LukasNoxio** [comment]
If you look at the screenshot "Bug with complete UI (border different because of elvui):" you can see I have 4 cp and a bit. The little bit is the 4th combopoint original width. In the weakaura it has a reduced width because I change the width with a condition based on my max combopoints.
 
I have marked it here.
![temp3](https://user-images.githubusercontent.com/20885653/201397688-534a2372-48f8-4a6a-9c04-bad0644fa245.png)

Short explanation of the wa. 

As a rogue I have between 5 and 7 cp based on talents. The individual length of each cp is ((total_bar_width-spacings)/number_of_cp). So for 5 cp each cp is 71px. With the talents for 7cp each one is 51px. 
The default weakaura for each cp has a width of 71px and with conditions I change the width. 
In the image you can see that the 4th cp is correctly defined by its border, but a small bar comes after it. I assume this small bar is an entire 71px cp (the default size) and only the border changes to the correct size.

**Comment by Daemoos** [comment]
We had a similar issue with resizing bars, the progress texture of the aurabar wasn't resizing correctly. We had to trigger region.bar:Update() to make it update.

**Comment by mrbuds** [comment]
Could you provide a minimal example?

**Comment by LukasNoxio** [comment]
I have experimented a bit to create a minimal example. The bug only occurs if the element is anchored to another frame. In my example the CP are anchored to each other like a chain. 
For me  only the last link of the chain will bug out:

![temp3](https://user-images.githubusercontent.com/20885653/201470588-3f4da2c7-7da5-4385-b036-2bb4924fb2bd.png)

I was not able to reproduce it with something generic like auras. To try it just hit any dummy with CP generators and spenders and it occurs within seconds.

WeakAura:
!WA:2!9AzxZTXvzCCVDNoMiMm1rU2nttsXKsnEsjoXk2ozcysTCKIDW2sz1A7K0uKos7rA34v7U5SRKSnqbCHG5TgQ5DysNI4TsjCr1NGo5AU4z8amCd3KpaCr(cappND9lYXjmjzk6IJoVVpNZ53))NJY8X91gzWHgCO4vJBe3yTJSrrwPfneUEt4A7kUOQQAw1to4i3RORWGlsg1OxxjTTwzfMWOpDxx7alpn)smBUAXW(zkwot5Y(8GjFT3Od1oWFTyoLmDfzDTCckorQz1tP1mSV5SwH)SBWQfGnNXlWY1XpwRWMcJbfffvXsrZ3h9Y)N)jnFrdoLrfU3bYDJAmbVV01ST7BbtRaUGvsorJQ5hWebXsA5yfeRyz8pFZyRgiSQuHl8FX(frzVztdEXALlRVShxmzQPZMEUPtgGf0y1eSeR67XTTNYWp298RvKxN7eKd7T1sTYpX450ZNtFCn9K1WpsrpB2YCXwDlRGJDtlx2utpTMSMItYz2bMAoSQC)yRxZjkeI1uWRGbnfcAveU18UpUxXfom75XyfBPrIAwgTSYu31B(bMOAA91zowvz0kDu4aPHdM0X1HFxoZNNlqWDQey25ggy8t9ipTAe(8sUog(Rs9H(qWRMSkZYbhl8QWNRt44WGWjWSDV7AoQLrtDUFGLtL(Mi7Dd39dpt2xRYcCTGFswat9(Hh0PPQOVqXCtOLk1STSCk7kIcwVdAvXXvWJoUtrBlPecxHFHwyVkXL1GfKBdHFLcfXiVSvLyndClvpCd5Gk389AI70AYnoCZ0NBxwIyntMrxpZmtNkTEtAfBfYvjTDzgZxmarvNGE1Qwdr3yIvWDn8S9z0kzZ897fsgljEExkmdsNuMiICkhmuuJx6QRD6M(EmXIlyzey2ZDL5dd0lRa7xb6ub(eW(wVSRtqABwfFrM50NEQztTHSNAUbYDcfVd0w5zCn4jhFo9mjQjS9oKzqGN)zpXjAWQ4oOL7jMCO8lKWD0RmZjgkPfUSmHNF2(HEwR71R5ZZ752GlkSrfUdxyvkNPBJmo31x(34OCOohoc8sRl7fXc7BJTgevSa0l8c4H(re1CKCAsus6Epz75Dr0Hf4ko6xCm4tRLLQd(uqFWHGdVknle5xaEXy3JkWk67kkslLcjPjtz1nzW4dPjNV4dbVCm4ZeRLHL)1R5idUemBBVdWK51dve0uCNoAsR08L20osf(SnGJfY7iHs4jsPeZEYhOMU3DnAmBptM6QfzrEltEU)U83)yYZ9VFj5pvv0kWNfqHm38(KDirHogBzgjnefriOk8foBVWb3aPWT7AufikZdRO(gH4tExjIOSzXqTscmCI4R8eVPgjVIw0K)xK)B(6w(wfT5f2S7C0)tmuFzTwIBdhCDkkKnu0KBvXm4fGUWDQyq8yq3XGxBTNxG6xstriTeAOZAHPxCkVe)XyYipH)MnP6cLkMRVv74zQRTusaPPurypsiZZiprUucbJJP9)Cf6UqlAS15MwLS5MqQ(l6JbHnVtizVDwOPHfoMsOqCz5OM4zIMWtjdrV6ErIvS09Apa7hEt9UGKJE(UkO3vHH7cJmwjzKjkh6)lNXZJ9ttlZfMlfnfs5wsCgni6kX4N)8EDHX34gxVMFa3GBmdBPcTK9AslddUJ2SPMhVRswZw3jQgk415lHCc3BGPiJA8JYV2emPhzsM4AZn1X3U0XZj15ni7IBjr6CU1qNUd3Hxx7WXuM4DOf4Sfhhjq)ZsEU9Lcv0vwUpn3k14WRiORKqKbutol6Cv0Nxfpd1gAWto4jxxkw8Tm4AAtDHj139IZc9mU8MRpjImMiiCvC3ClI3Fw2MeOJad06cMR4vmBsJ0o1tUIRBvfn5OmHppz7I3hSUm2MiBFdTt7VROaNQtyyyeymyFWzJHehjv4MTyrHbUdR2YvyHNQsxHMtMrBQRMzw9XNgo3X6xRKjV0IPHEuxTotyXqCxla9hT1QZSRXJp6rD9o6yJjkzYCQW9pw)W73yvpbzrfSm829cFW9JESGg3Mr2j9d)EA6G)a8hdhl8(Xpn8NOrYHpqoe4pdJ2pCMcWPlaFYyRDAyYEav4hJ5Lo5c9mzP7s20Vf(YOfwoqhE9cWC7dMFlZtYreUI0MeUQ0ImF8eKVlAosEEVHcOvawaUmCTcObiuibZzzO4D6aMwbMbMfYazJ0SDlLTxe(sqPT89gdUdULc8903ckBcxYemrlPlIoqGfLC96yIpydvHfvaxPzc4vaUbiah16GZZUDB4K2tp9HpUAYZ9VU9T)Oo6qbNuptSVpNCsq7KMQKlcutQSQBkfxW3MkSKjSCbyLTngGVIm9R2Uza81ila4ndv)Wxx2Adt4BiZ8nLPFlz6Bjtx9bu5OfbCt47aRva(UW3l6QaYIp6blrxfSRA6(bQzGwlUqQQPDoZOxCCx4ha)q4TVfHU)iVU3L8JqC4vG1H3tb(jWpf(zWph(fMW7Ac)YXGFf8RHPuGBRG6QhuAKaQS1vgGHkmCRCPMo1e6P1gFMuWToChW3p8W93yc)w43r8)EaRJgcRniyf))V2bbS7OJeph15TPA8)RP0ozV)3jKSPV7(Fh6Wu(mL78eFF6oP2lT1RrieNehe23U6iF8tTT6aLdKqGKsO4avsO4i6rfBQoG)IuB0UaiAh7HlcindEu1UkaVPMaDIJBxfSOYJTk4Jbjac17ucShy)BTdTbkycLa7K1ofI0xPX0Ru9slxDUzwK4XHHpKqAewj8fzuYtJW39eYtSdKgDrijbH7sOwQ125Jjqyg1li5J(ri8IgLpa)sK7oXYhk)UNUY7b)UTwkKJXVEKb9wm8tGrWdX5D3w9eA2ont07w0msSe4Qrpdws(inJeE(4dtO9dfMXtNhtqgHuIvrEUDogzZNA7CKREAG4TLcpr25ijfPTjydPlKB3tq9usCM4tetjCgr9TrxYD72kBJU7uJm8U9JrbcPjgO1ux9mnUXe1VAPl1G4z0E8JF)4lz(aV0arcclEK(Qiw9iE0bcI5JpIexrsKOxKeF9WhDqC5EIIpXxaqNupAa()RVh5PeGF8CH3g3JayIij6dbz5BG)qs9gz(oqRvU80vVyfVGfQMTnNucGFx6z5T)CI9KFhzVfedhzhJu7J49epX(Xv(F6hhV(F7Y)3d

**Comment by InfusOnWoW** [comment]
I cannot reproduce any issue with neither of your exports. All auras seeme to behave like they should.

Please provide a better explanation on how to reproduce it.

**Comment by LukasNoxio** [comment]
I literally dont know any other way to explain it. I just generate and spend combopoints. I have provided a clip showing the bug without any other addons activated.

Clip:
https://streamable.com/d6zi2a
