### ISSUE TITLE
GCD icon does not seem to be working on beta

### ISSUE THREAD

**Issue by stahl** [WeakAuras/WeakAuras2#401]
**What steps will reproduce the problem?**

Use an ability that triggers the GCD.

**What is the expected output? What do you see instead?**

I expect to see the icon during the GCD, I see nothing instead.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes everything else disabled.

**What version of WeakAuras are you using?**

8.0-beta4

**Was it working in a previous version? If yes, which was the last good one?**

It is working on live using 2.5.11.

**Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack).** 

No errors as far as I can see

**Please provide any additional information below.**

The problem occurs on BfA beta. 

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`**

**In case you do know which aura is problematic, please export the string and paste it below.**

```dytUdaGAsG2fjsVwvOMljKzJQBss1TLIDQQ2lSBH2pjk)uv0We8BugmjudNumoPQJsc4yQ05eXcfvDyvSyvPLJWdjP8uQESu65smrvHmvjnzKA6exKeXFruxwX1vQnks2kjQ2mLA7IkFKe00eLpJiFhjDAkEMuz0IuJNK4KQcUfsCnsPZtsAzk5BKQTrjJlQWnWFikdH9PDu0dTSyrrp8voz1nLwYkWEkIHfv)q8y4f49knq5DKtg8g40WPrfElJZiqf)ls1NOF71Tscz6RvwiaBkA7WFHu9j63EDRKqM(ALfcWMI2o87qQ(e9BVUvsitFTYcbytrBhe4NwXKBQegsKgc1z0d(uUb4MOmeXdx5drXWI43bximKineOcFxgYN3cJ4vDg9G8W3LHCjnJkPwAKh(UmKnXCdrzWlCrvnd8ICKDb(oo5MOa)Sfg8DzixsZO(mI8W3LH8oAeKh(KBIcCfYzVhUYuSAmgNMrncNyoCxZW5)tZGFa(UmKlAgo)FAgKhEjnJ6Zi8sAg1Nr1ymonJAeErZW5)tZGFac80JHuAb)BiaNZo0Oc3ejrW2AqfEZMlguHabUC4tuqfEZMlguHaboTX220U5IQOcVzZfdQqGaN40oOcVzZfdQqGaNGXhuH3S5IbviqGRjNg5WNOGk8MnxmOcbcC7tRyyruH3S5IbviqGlh(eLfQWB2CXGkeiqGtBkk4o2kMCd8dNdxgvKRAmoJav8VivM21Dzf6dRo9e9KfSPyfWFHuzAx3LvOpS60t0twWMIva)oKkt76USc9HvNEIEYc2uScqGR6tB7YiiLLLEOZkPFzfUD3KoytjldoXqYWIvv1mWnTSiCvEABxgb)BitPxllTHUKG1sl8Zwy4fUHgUcv7rktX1PiWPAOL04Fdb4TmgNMrnwhveLepV8HgVWJ7MkHHePHOG)fUjAeYf5qidn(x4TmgNMrnI8WLrf5QK45Lp04fc8C4FZwxiaa```

**Comment by InfusOnWoW** [comment]
Thanks, that'll be fixed in the next release.
