### ISSUE TITLE
群组无法删除全部子项

### ISSUE THREAD

**Issue by Yemenghuan** [WeakAuras/WeakAuras2#4010]
### Description

Wago链接：https://wago.io/zdiZER1VT
此群组中有180+项目，每次删除旧版本均会出现几个项目无法删除的问题
需要/reload之后删除其中一个子项，然后再/reload删除另外一个子项
后来又发现这些无法一次性整体删除的项目均勾选了“自动克隆”（Auto-Clone (Show All Matches)）
如果取消勾选“自动克隆”（Auto-Clone (Show All Matches)）就可以全部删除
此问题是从WeakAuras 5.0+版本后出现的，之前的4.X版本WeakAuras 无此问题

谢谢！~

### WeakAuras Version

WeakAuras 5.1.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1、导入群组
2、删除群组有残留，然后WA插件卡住无法进行任何操作
3、/reload之后可以删除其中一个子项
4、群组中取消勾选“自动克隆”可以删除全部子项

### Last Good Version

4.1.5

### Screenshots

![111](https://user-images.githubusercontent.com/114139322/201521215-13cfa601-15cf-447e-9636-be720d5cb2d2.png)

### Export String

https://wago.io/zdiZER1VT

**Comment by InfusOnWoW** [comment]
We don't speak chinese here.

The automatic translation inidcated it had something to do with deleting auras.

And indeed there are limitations that affect deleting big groups, which are hard to fix.

But we'll eventually fix them.

**Comment by Yemenghuan** [comment]
Thanks

**Comment by Yemenghuan** [comment]
sorry to disturb you again
The problem is not to deleting big groups，but to can‘t delete the group if there are Auto-Clone (Show All Matches) items in the group. For example, only the last few items of the group can be left, and they can‘t be deleted together.
Hope you can solve this problem,Thanks！

**Comment by Yemenghuan** [comment]
!WA:2!TZxFWrX5997huttICAkiSvad2(SIniQryjHbBClXrNqcegq4tcWX1P627Uv62WP7wV3E6T4KijqVWBsWHaeibY64DKrs(qGe61u(1M2)ChnPPBB)JFZWODV7MPPzgMjZ0PZKo973N9E)wjKDDDRt4goD7T7Z(8891pF((88ShK9NHBtBAd5TH8YO6mSLHT23SxgbR7I1zvI2pCMp0IlbBScgzSEqBcU45xQrhCn0aJGndL7YLdroEl1YuLRs2M3gSX9(fzkV9xUqDLwzLUzf3Xp)Jm8upDd)Ik9wLGlp8Ly1LZvSKV130pJtR2DjSxxCofTuyr7P8Im5RspoCuiNGvhSMn5MNXkBA57rWXseySkY5YP7nBYTiJGy6wQKZjNB7PBe(qm9Mff4QQkwb3p3AecFyR(SXAXtLvwE98Sc7OODT3I33UmkcFXeJhbM8B2npRdhLyZD6p0ThlS1W6uSmO1C15VIclOSYROSYlWu5g9aDUfEhm1ZkyYjt1SUt3eTPw2blJdr7rV19kWc3QPY2Br7AxE94mSiKUFRUC4PANLrvdlcm2484(WFlVmo5QMb1Mnl9Nw8dyzCZwMOa1g)1LY0OtxozN1giJylQaLyb3SGbZM7MXMI6J0AnwndNZILwdCdsRvkBP1j9NbFU0KpJjghCv5ukDJ2yDBnJ0faBhkyeHAGof6(L5d0atSvHw20BUkboBy3NLPTz0HlgBfB0nxdSzAQApGZnDJGfZAMsVE6MS6GXTB8ilImoaTNEOBxEeSYAHRAExcIZAjCmsHUC4syNPLwA7nTC3WMEKB4A7OEl44WyXbB7tWVIqtCk1E6nqF3rP3lRo4m5eOPbu8D(c3MD(vQ219uoI)Gn2IA7TR25jvA5y5OC7RPmTx78VO6WJP2K35U)Xc07K5m3uZeORBeO5PcCOBh4SthC0tP)DRE7jcDl4Alvz4ovB8w5e6w3iqx(v7Di78zcxxz4UcESovo6hRm9O5eQRMcD6PTZV6GNyiLJ0SYyThCOXvp7q5eSTrG(r9iNwPTjSZVIKVCOZDRaDmmk)zRCLBQCYHu6PhyqvU8a5e4uxs9STP2(iWafORrd0(Dd2FJHARt7pyV5LJ6Dod0jbM(OGSeQ7zuo6Tug7qH6zuLl2robU5mkTpoOtbNPDqoHHjW43jh1ZCQ5gFCq1c1kyrwN(kqok94lu39P2FRQx6EHgO75gFqDKmLXpnCVk93Lsl3pKVwNBSjclz8Bs9mNxzWUvp2rGEoWeJOC1RsncxU5aJFFWmQ0EJ6oeRuDKEu)KRR0)La1ihLo)eLUUIYT9PC7tIQXjVrWo9h6cTMtWX9RmzJQxyKqxUJq9Cl78VCYQHsRdhQ3EvA1pyUZoyB3sz0pDDGxbK1GZCR5U)XPsZiGO0L6hF)isD2jhvHQ2WtIw0l0AWtoLsVdREU7f6CJGcA8rsO617qkN8KQnbbfRmXrz07O05Wb(KBeSNJbsqc3xWdnfmWbo)0kT3Q6qDHXfr1rqdu8D6yY(lQVjvzu)kD7p4GtzNFTG4RC17Om6aqurGtEhLB0lMxe4WdddxOEUrS(k7eKWaDDx1l1uWP(e1t4RWT9QQNDk4(JeGOxcb6(B5U25xE4ec12bV3rco6DdowN2FeevQfFO0Yrc0XqXYBup3Xa)L6zVj6isYFPEXgHwf6wJgAGwsopnqx9PCQPuACY4mupBmd1CJDuiWm7TzC3GMLvkadhQDWaO5Aco0eQxSFOrjKqeSNEcm1PafpOVbGduA0R6zgooL72tm349hrLFn1pEYatDomKWFtu7FNDRmzZQ35gkdFyDdPxDYPLquuGBoIYjgamr2Nn8Oe4ynp39)uq0E8joXeTGtnK6DUkmWumLvNSQREHbbxGYvoXCt0MD(mso0cbBwLEHmurbV6lQhyi9ubA6UHUDZ6G)fjvkNusLaV70NxljkqpNsTJRNDWz6rz8RbEeAMzsylHdHoXWbhC4OwPqTDI5M8kX5BUW5uM6tdoZOH6HI528GbpCNbUWHvg74iyzpNnN9MhmEHUOV8XuVKCDHMOt175x5SJQoElX1NnDp1gVU6qEbi6KbKGybqZJexNeyffMsX3Lc0dagVUyw7WHVNCmLopR(GEkJDgLR2g6Tbdm4SuB6grikEXeYuH3W3HGdqvIyPF5Kvlq0NB8tTTImUVIlowk)YHMH3Ogveiqud5ZMqIM6K3u9E9JE(ucAXe3lmsGjoT6f7dZ(Ipbcta14Ex9cLDakQorBQ(psOj6gsSwieCDnBVOoU7G9pCWgBIYNpagDgopPLtcoATSf476myGzkaGSaKPhThDhSvOVbbv6xEH6S44EsMYxt4uAFu1ZoCYo64HKJGeVA9H2aFNYzglzgPWmlnnqWJ(PjFTO3xamR5fwGSgLEUe4Sba9ah56GGdnqT3EWr)2hNIZJKExEa1UMouJab9YtewnC8zM6Nja9BcA8CJFfk9J(moZn5hhQXM0R4OREjuEo8vuB0BWrVyGRnreZ1cyqPeC6byE0Raf2bXqkOGNchf(rlxfi7up75MxKALzoeGTf4Oaist0k00mDqzv6hXQm4ruA5gqrcbB)sACNnFlaccaHHO4eSEHticxKX61Hdl4LV)CtD6fhluOwgtd8d6q0yLKUgy6RaDLYqEHrnWG3wtY62py1v7(QkN(QXrc1FJyO0zhiW5quuDauqCHeqk74WbN5KaHlWde86TgRRc4B6a(6qZlKsqBcLPVADa9auBa3JYeS0e56M8(XbV7Fc1ddPGTO41BkjnZCjaSjqZ3hlaa14a9CUGJmPYanf4Qqg2gsP(xalRLpbkihKdLJENatElWmo3yxmsOFQKAuFlMXo1NIicXYmg48Zn1jcDEWWqRohlajZKbmMBSJPE1jJRaRahz8ahbSuRsVu481sHH(jgYV6H7tTVtdJFISOuBNslTaGgXQwdHUNYhDwogsQG2tbYku451uV9Lv68obhPV4IgsyAo6OchfvHKiWXYtp3n0jke6h1ZE7yrH6pbUeGZsjqp45hacM1GR1CQhVdWeJXfTIeSpMIM1Rw1w7a8IbhSFQBALjRJQdEmLX7JA4wACM(zAeGOGYWIcje8UxkW0DeCOZP)SjcotBbNAQyfi27nvp)z0rAc1tR4KFbv4AaO6RTqKe6JmKI6Pvu1LBo0foVMb7C9e8yxtPJJP0(9w4QS2iOFXPYdEmOSEADble5oDmWsBNE05M8ub69J1oXGhr9OxaqtHcUszkS0YWIuI28u3R6r7oWLVrSqnCg2DDxLEMoyltNmofivHASVyX(qFfS5RqDHlpXcWoHpi23o)RKcuaTqvnYCfVhpsWXYtO0UiXaPmpt46yPDh)(PmpZeNQciEq4mGCMyTdRms2enDrZ)bPl0O3OzAJmbMKFeSY24sdco0qkdbjKpV(13yiYuMw9cvKt0GuvVNbIBsO6xT5AayQkN8e6g)LKNO1tavjOFAjItDp)HvSybnOvDKj0bTn(AdsoekEctyMZ6etRPAbA7qbo01ZgfI7mbuf3AIPzrx(H5P60KxaOyFNY9GkWCZCrKT7QqDl6wWXvUo6LBB8aDaE58Mhuya)fqHbSyiSQ7GdEL5g7eaWbuPciUVsk5g(pp0ZPeMTQfiPw)Yhvo)NqnDV2cXXPRLjZuI(pwZi2C0SVG92TM7zElYkWPVwWRFzWTQCYjXY8tseuVBtQD3hcgUaCbZtzs6ILaAtW7cLjTIuMFdu)0WhwBgtjRvT2LI)Bc3jn6tVPsRviSwrXOzPXlaSz5GUVR1uO2okuw9VzYMwOf(bi8GjEPxGdLniciKoROyFHA74bB8EW9HvVC5bIuXswlKftBkLjxtA0SB7cARqnR9zz8iA3LqP801EpDtUTY4Gfxk334rCofzfCY4y)ARKCTw02Ca7(0(SiBvXYVSY(qpmcSgk2JdhgoGDorwFc0fBgxL5hyRENmvZzLUJaHVRY4AG9RzYbx1CIpTfRUCwjxvPBex0yP12Sh3S7cVGD)vkWunUK5mImP9qOvUfzCkwmJvrxcwmvW2kzFL1SGRA1w19hO1XABdX30IB2QRHvWuEB4n2qU(eDzn86G)nQ5NNfNn(Sm6PkdcS4kyNJvgNoDjAWgRdwrwdI2znqfuONfPRmpXlUC5hGZMO9N(rA7JrXOCHQMLYk0urfTh)AJDjoHHoT89WzZ)o3IT37D3yU7VoRB3RBwhvQTZhglT8YlD3gH(V2S23EfQp8EM895EQ069NW(0(Wf)NtZd4NZzLUe029Gm9dhALTiCdiCBo8GPTG7ecjTmSoE7VQpo4MlJU08ePVM0FS0)E6(S6XTORQlNToX6iVCLECs3yLSxx6gGxCvA4aSmhSapcmU3qjUd74lLNfAaAeCsBf(sGv0JGtdz9rwReELl8kqh3uzW7PC9tdHqzrBhRtB0pP)XHli4XWEatKHTAa3dMkyDwZgaFNi7gW9zbVsezG2QegouWkOIcXDEGQIylYg)Z6m8t3QHSYkXwJVcpsZZDfTPrKX40POscEn4TmzfePVPu6ZA1Llh2CvRZYQLJN1S0FYsK(24w4iunRB3mvXUe(ScFufAoPkYBdwzCd5jypg(CsRL3qkTkI(hTn(S5QIWTYU0sZSz4RUD5XPn7sllDPm(2RrA5T)sMGmaRh0iKI6kFb2QZixVOvLUnvpNPnM3BMFE8ldsAQOkwNScCwlZURAl1Pz)4PCdhxLvBM9c3hdNtoNvLrE(PX3vyfggXmYJF5X9vW)djBUeY67TvF4TwOdxozDBwALspN0lWVYcdBwmSxbxvjasTHSld3DT15fhlQuA(HWHBpwpAE2eKkAVwGJAzQ3T0Qmrh5hGkdDt64SH6ZMY9n2I0Zi9Sszk9DMf73OIUDb4RO1ZSGhN0TJtMSw(mIE9kCft8Lmi9spcAEr1bWfLPTfG2BoYUTLrEZkWY4GEESd9vSGl3Ig2JRAyOdP7ixWS0kshbKQaDCM9ddvetugFpPNpDVrB4V1c0ktSvBxkR1itG)TwzYRlt2e)YW9ZSg2Y12PWD7Yg7N8us)h1(OdYYYxaUtBIMqrYU0RGryjVrFVAQB9xnszAHhm(SIEPO0io0SUbJpxv2fldpd2oQhHEDZ0BDnFDzYoKjFhF2yDZiIMbiE71wMuUVFMszoRBpwWnYd9hoT9RMTkhUQTyb2p0dRtR1V3)OC3q(BsktbOr4f8J)590GUinJFHkbw8ik6YzPaoRdM69HNwB3KFwA7)bHBVx8lr3RW0EagSe5m2PxKQbPrfHYTZz9Gq8N70mIF1m967IdoZYOdGrnIO2xj)licGCvq)t4un(ke5IMMr8g96z9k88RuNwRDGj8MS9q6LIcBBSG9vEP8lNEsmhebLTs5dmwa81hP1rC1XQrs0e)lpFsJd2QySwFfv6WLlbZpG2GFeGrZvz9sP7JY3WIO1g3tP7PiEdZxVuTlBvG(pZA(eSf8RB(ACyU3keTdHm2H0xIpARSg1h4n8Db8tbBc3xg(xA(6miSZkhsJMgFgA2i7m2I5C5xACNmg)0S0Zwl4SoGadFZhi8bZgDCP7CFP7R8DvcO2A9rCpVaaCS23ImmAgUAabXceDhRBWAk2A42gj(mb5mYjB)5LjUstM8dFG2(cO2XXv7SF(StrTtavhbmQUce11ec(iit(RKjvitmltyKjwKjw1XXRdVGX9bqj8F3fUPu3J0MLj1sKjvkLUmPkzIDzYpM84etglweyRHdZVLjhSEPmLj)OWwHemnFWtjtCSZD82)M))4Rq74T)1xeFDQ0adt18lTybUgm8UEySHfFzO8YLj1VvzcpinFa8guE3YK6avVgFGJRitvSRIkgAZhsD4Yeay2d)6xScAfvZu3YKjnaDSTMAFfAdXpmRxXAQMySf6K)AnkFACwlQQR5PDqJ0bftMCy0QOPjOuMGU4xtxmvY23rCkd6cqLhLVFmXIDweOTjP8plfJLglyx6nWNncPnVglUbIihSg3DbBVi4muUJgasuZc4FlXM7LiTjSP(JCb4u2nIhWBeMLluEpuQEGo6bMVW6JFoCRpPjRSESS)H7s5e9R06q4Kah8IkJFAPnsfJ3uAlYKNvkDP)tJyzHnhPCgiIyLp3Amz1oR1dwS0Ytllx8zT1TAQgghEyZi3MRHrGdFAn8IKDfIS3cwTZ4SkOmJmBMxazxfR3eJdE7msFDWySK05ZauJivfaCBMqyjzYsLjG)8RLg)ZezKryTTX5g7DBGuSwOrFRW1IVSK29zd5ltap4tltUqAMQLIOc2hxvdd4Y9xQTQFxXdUDywbaHQtSOEwZMIHL9GiJhoRe7(TX5gFME0EkKY4NltEoGyEvM5xbxvoDjWgUOxAD1fji4sWniwEn3(RktE(ifrltEbzYlgPWqzIHyvdktEPLitYcJ5(U4FEzSaozYRexPBRksPaRdkSzJ5NlKq)xafNOvAau)Gmz9WqMtg5HLRibTgAGrZy1pYKCHRSfWwTTFlw(Lm5nG3VPm5TmlbsuEYK)CAh)2YKVVmPaSofSGjzYwHB5vHBnF493d64elhrMumT8dzY2)mvXbT4HsKj7epJm5DsSOczYUIvmHmz3)kzYEIu2GmPuzYEbN37ktmjtkd0SYHVTVWzK7he3daF(EW7FaiYVpe48xcu6rbb41heqMGbAXHmYzoC((bjjKV7udbaZ3JKqRLXRL9xd2dygocaellpkfXSVs8GwYKFIm5NQNe9ZKjnktAsxiBzsZXWILjhsd6nna7Tp81474T)3(P4RoIIqnpyTYKwseJvM06NbGtzsB)3eGuM0(8HlktocIjktoAmWqzYXKjhhowMCc427im2NmPtWECszYPsbVcY)KjNwdNsM0vmqkzYzYixzc0)NtM09Zbs(5baIWWqYKEId1rM0RoqmXVK4XdXitUeyy6JIUCG3TMc2P13Zw(hyNYK(HoWxyZYLHo8kRyjl)PIaHitU6)tIv86Bj38EcwXx1WkKjx)jaeFLfGi(DXF(ai252x3bSDWIFVn(o1QharA993)Lear(BjVn)eaINaq8eaIV8aiIFVlNpaIYlOU3SWg2z2fSD36xbbFkaeRpcabGouh5xM660N4sOBGXPTKxv9TVVs2wIRlomDydCg2QH8wVHxpxd2CLWcMRTa94K8GwSwCfnGzjjYUwdBydg4MNwshITAyFHpmB8CRlH2cskUpkrBmkpgGP4ZCq6YRNCBJ1PB9XRojkpCoTXwhimBNv0ed(lmqOkwXsWtQJyf3Y9RDFO9BTFu5LGBRvLmwz)GpqRdG5Tt3xNp4d2xj5eRFHtJZFScnRdThGdw7BL7hjU2egO43FHihN0(kGi(8ln22YSpEBG(AXd9dmgHYf0kYfyrRvACcET5QcTVB)br2sb83lIrtfuY2Isye9s2yDlUKO0hq02DGUze7szShKg551GWX1PF3mIwTRTo92rAfVrFcIEOvxvBHZj7EzfqxUDk8FeuFJMJr1qztqAiKWq6ze2rbM2DX7BxAmoVL5imlB1oskHKjuchkBvCSniXKgb1gTJSnsRs61tISbNm)pIMBudB(moR)Zl5dARE8Cp7uJ75RkuhOQS4yoiAR63hVu81ArgKFg(6YXio24NdIJvPnu0zlhzlUwSCiX62gijSqLrwV3ee9yKm8zPZ6lMY(RPPm1ssLeYvufbvzKW6dctbDnKckm9smkiqkoUzF24QSsoRECiwFmkP3icLKg5eLsA)M4zeeR3C(ISon7tSwwNI1xje6A2I2XMBgKqX6RMXPzK8ckoCXtDbx8men6lKbjgjZY9VLnDG9(g1uJNTutvAusZlL2dJ)NIuQ0ziDisl2Vzkd5ZIElK)QT45VGQxtG(sMmC8qDYKpvM4pkUwLA14IGr3vMCpescHTKjJo)GvRoceWyHXggpCfPjxZB8GqYKjIuXlfiHIrPHdfTGxedl(YDPOtumoO668EZnVP3uRQxOG5Kl6DszYupb95ZxHRHHF(1tHVUja)8V(r4Rk)Ib(rMm9NDmhzYmZheJm5N)focIm5V(XGCitEaC1)FW7)g49Fl8(x8fkgr2BUG3lVnvw9BUH39XGrexzVApNNlECIl85hNO1y4e05dJWeAagHl05)7Hy4v7hubu40tqnEcQXVxIAi2Ww4kVbM8EtUDSyqnI)3z0Ih14V7pOqn4Zq7N0qOZpAOU)u1Z0U6L69j4hpb)43lXp(W3)D(qERCfvAD7EXGFe)p5Nfn(rgx4piMDsUBztB6j4epbN43lXj20bRPYD5SGDNNJdSiwbJO)uDx81y0ZxUyeVqmmcHW)xr03439oyISmzwned9xAvm3pYo89wM1wH0iWgYKnhd3qYWdP))ruf7TitLu62kPqPxWyHmUfdd182pq7NUN6zhwT7(8h9XBUeBAR86RcjLypgELxF(0)kkKs9FraP8c4TP7ZXP2)ThL0AlsxWZyxjckuKr8ZgoudKfpo08T7EThrbrtfIbHMf0qg10(iTFJDr)PSoV2z7lk78HFm2zk0yQg6V8aIspzaMAw3g3FHLwCzgDv7JRqKNj1F5VlwCM06BU)xdNrM8p8n(DT8fleJm5xH1M8pgburMilt(NEccskiizPja)Zu4bzY)sK7w3NB74avs452wdSqt(qOH5dnGNKOqv)w19PUw3Hj8tDDS6MECsyShaE6TeVznEyT4aX0WhQZSUpT7X1Z0hGxZA2BnqSFmjriSgir9Spi()pn5p4qVQT8dySUQ2F51BDZpo0RVJU)VaZIVqPnKeawg18lFV)R)

**Comment by InfusOnWoW** [comment]
Can you write the reproductions steps in english again?

Or can you export the group twice? Once how you can delete it, and once how you can't?

**Comment by Yemenghuan** [comment]
1、Import Groups
2、Delete the group but nothing happens
3、/reload ,then can delete a sub item in the group
4、/reload again，then can delete a sub item in the group again，until delete the![333](https://user-images.githubusercontent.com/114139322/201524213-5ea3e6fc-cd81-4d16-b637-53bec77b057a.gif)groupcompletely
Or click the trigger of the group and uncheck the “Auto-Clone (Show All Matches)”， then can delete the whole group at one time
![222](https://user-images.githubusercontent.com/114139322/201524121-a21de4da-2e45-43f0-b2c2-24cb38fb3308.gif)
![333](https://user-images.githubusercontent.com/114139322/201524225-e52d804d-cbcb-4526-b42c-067c9052a3ef.gif)

**Comment by Yemenghuan** [comment]
![333](https://user-images.githubusercontent.com/114139322/201524450-cec562ab-4210-437a-8bbb-0b017420e09d.gif)

**Comment by Yemenghuan** [comment]
Can you receive the two gif pictures?
The first picture shows that the group cannot be deleted even if there are only 9-10 projects，and the second picture shows that the group can be deleted after unchecking “Auto-Clone (Show All Matches)”
Can you reproduce the problem and solve it？
We look forward to your reply .   
Thank you

**Comment by InfusOnWoW** [comment]
Yes, that's enough infomration, I'll look into it.

**Comment by Yemenghuan** [comment]
Thank you.
The code was modified according to the method you provided, and this problem was solved
By the way, when will the new version be updated?
