### ISSUE TITLE
New Spell/Blizzard Alerts

### ISSUE THREAD

**Issue by lumidtc** [WeakAuras/WeakAuras2#4012]
With the addition of the Evoker class, there are new Spell/Blizzard alerts for some of their spells, was wondering if you guys were planning to add them to the Blizzard Alerts tab of textures, or if you weren't planning on it, if you could. Thanks!

**Comment by InfusOnWoW** [comment]
Which spell alerts do evoker have?

**Comment by mrbuds** [comment]
so far i have https://www.wowhead.com/spell=369299/essence-burst, texture 4699056

**Comment by mrbuds** [comment]
@lumidtc these textures are not nicely listed like other ones, so need to get them from game's event

If you know more that essence burst, you can run this aura to show in chat spell name + texture id, then we'll add them

```
!WA:2!1rvZUTTrq4iOdfGOinvPWO)cqKIM6IMt(qkkqDBfvjJDQIKljTDYj2LChkUnR2DXUlLT8rHGIC2pc6CpPhHEONjm6tGFeYtqNLunWOOMx4Sl)MV5NVzyVObZhqhqF9xQL1wota6PhNo(WjH6ZNwwAaBp1xtzgfNSmfo3Mvk1Zj2mvMLnhYOlfK5SImBLgmvsoD5vMkcvE2l6C(tVZgIOOsQpsYe28rHtsdJv(3oHDN6PUxrTXkN7qCSIsSqmSae2Rj14TelR4ug1wfmepQjfwMuyECSXs0wV8sMGzQ8cWxwVvwnB2mqBU7d1Bn)Ra7sfK3fHRn15TuNuxwYoFt2OHjPzjPdJtB8YpaiCB1BXCKgqmXjhfoE8AkKJUKIuPpiC8rrhpoOgJyURYaDNdg1N1coB4O0dpzy6HtNKn9KW4XdFrwYbtpngBFGXBtxUK5YRgVvgfW5hsnEnFGswwlARVDBj8r(TFKrFKVf7n1A4R88XhUSGW7(2eKs)99FcytA5ruk3DRtDyvAul29TyVbtGG(VPsfJcXojHEzTyBJZt9(UE9ciT78ZKu4pUJ6b3UCoxsZ0O69RQhE7G4WmsXYSsUuQRU0a8YUPLGPPPtFwqPuyv3lsZUW)xQjuKoIFA6AutIHzoH)J3P5(xHhZjfVCgoglObCjHgLBjCSLTt88AUL5fGvCXon75fxWjgJZkWWUaCgRCbjbp8rBNFFE38B)162y4u5axBkVqkkzZ8UKiyU5qP4Xn3n6pbIbsSAqmZw9on3pqifWv0ADlIwzvBa0vQzLdQJUM9dMtyIOMVdDOz)MVV5hA(r8979FVr953ERtPHcMbJrF1N8)IQZO5lw7coRDpbRFjxQFAF8r)BOAZkxgmomkDTvwSatue0h273x)ag962HeFjElYSz1zsn9unrT60TgBk14eew5OO0)nDR6rURCvyEYO4WWj6LB)rYE1m6MVj6jp9c6jJv)83EfUmJ4NQ6sRn3Oag4VPthg1MQ961R)ACZdOTR9V6D3WeDvg6P3BWHfqli8t6s(Zgy27NGfdw83p)Fo
```

**Comment by lumidtc** [comment]
I believe there are only 2, one for Essence Burst and one for https://www.wowhead.com/beta/spell=370818/snapfire and the texture is 4699057 according to that aura, thanks again! :D
