### ISSUE TITLE
WeakAura ADDON is not providing update icon for new updates available in companion

### ISSUE THREAD

**Issue by garciaoki** [WeakAuras/WeakAuras2#4016]
### Description

I have weakaura updates available in weakaura companion that the weakaura addon will not show for update in game

### WeakAuras Version

WeakAura 2.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

right click on WA addon to open console.  No update icon is available for the weakaura updates shown in companion

**Comment by mrbuds** [comment]
Tickets for WeakAuras Companion are handled at https://github.com/WeakAuras/WeakAuras-Companion/issues
But for your case it's most probably not a bug but you see auras that don't have any update (column "update" empty), i can't tell for sure because you don't give enough information.
