### ISSUE TITLE
Border selection not available

### ISSUE THREAD

**Issue by Zeetocht** [WeakAuras/WeakAuras2#4020]
### Description

I play a demonology warlock and I've created progress bars to track the time remaining on spells I cast on enemies. I've currently set conditions for the background and text colors of those bars to change as the spells they represent near expiration which all work; what I'd also like to do is add a property change that would change the border color once the spell has expired. I can get that to work for the spell Corruption but the issue is that the border selection isn't available for other spells.

![2022-11-15_11-36-12](https://user-images.githubusercontent.com/99370084/201989176-f46b6878-4533-4694-854d-76287df29fa9.png)

![2022-11-15_11-39-34](https://user-images.githubusercontent.com/99370084/201989241-f2688730-a2b7-4ed1-b4e6-a73b44da43a5.png)

### WeakAuras Version

5.1.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Open WeakAuras, select progress bar to be edited, select Conditions tab, select trigger, set conditon

**Comment by InfusOnWoW** [comment]
I can gurantee that the reproduction steps are incomplete, since by default progress bars have no border.

So please add correect reproduction steps, that you have verified to show the problem.
