### ISSUE TITLE
Rebroadcast the arguments from player_entering_world event in wa_delayed_player_entering_world

### ISSUE THREAD

**Issue by wing5wong** [WeakAuras/WeakAuras2#4021]
**Is your feature request related to a problem? Please describe.**
When using weakauras.saved i’d like to be able to reset a value on login only. A ui reload should not reset the variable. 

**Describe the solution you'd like**
Player_entering_world supplies 2 values, login and reload, but appears this event is not always available by the time weakauras is initialised. Sometimes it appears to be available, so may be inconsistent due to timing. 
if possible I’d like these values to be rebroadcast with the wa_delayed_player_entering_world which would allow me to consistently and accurately reset the variable ONLY on player login

**Describe alternatives you've considered**
Alternative Solutions involve guesswork and somewhat complex checks to see if the variable should be reset mid combat ( counter of events and then checking for other events)

**Additional context**
The main use case for this is an orbit breaker weakaura. 
the count starts at 0 on login and does not reset except for on a proc at a specified count (currently 30). At 30 stack a full moon is energised. Full moon is also energised from a player hardcast, and also has a chance to proc from convoke the spirits, so this event can not be used to reliably reset the count. 
changing zones, dying, opening wa config, reloading ui etc should not reset the count. 

My current solution is here https://wago.io/myCOqQRFi which attempts to fix itself each proc and generally works, but would be nicer to just be accurate in the first place

witht the proposed solution a simple counter weakaura could be used, resetting every 30 count and clearing the count on login

thanks for considering this

**Comment by InfusOnWoW** [comment]
While I will make that change, do note that the event is internal and its behaviour is not guranteed.
