### ISSUE TITLE
warning window

### ISSUE THREAD

**Issue by renak0** [WeakAuras/WeakAuras2#4022]
### Description

Upon logging on today on all my characters, a warning window appeared saying "Unable to earn new rewards after this week. Any unclaimed rewards will be lost after the launch of Dragonflight."
After disabling all addons and re-enabling one by one it seems to be caused by WeakAuras

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Just having weakauras enabled causes the issue.

### Last Good Version

The one before WeakAuras 5.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/118319016/202051722-1d9970c7-3500-4e12-ad88-e4b468c6998d.png)

**Comment by Stanzilla** [comment]
That is either one of your auras or Blizzard, not WA itself. Are you sure it worked with a previous WA version and you are not just logging in to 10.0.2 the first time with it?

**Comment by mrbuds** [comment]
If you have "Advanced Mythic Keystone WA" delete it

**Comment by renak0** [comment]
It happened on every character that I've logged on today. I assumed it was WA because once I disabled it the warning went away.

And I don't believe I have that WA but I'll double check.

**Comment by mrbuds** [comment]
If you don't have this aura, try search for auras with the name containing "vault" (use search field)
