### ISSUE TITLE
Message in World of Warcraft windown 

### ISSUE THREAD

**Issue by malencar349** [WeakAuras/WeakAuras2#4023]
### Description

![WA BUg](https://user-images.githubusercontent.com/118360327/202181073-3cfc4344-3281-459f-9b7c-b91b0256ab3b.JPG)

### WeakAuras Version

5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

.

**Comment by InfusOnWoW** [comment]
You have an aura instaleld that interacts with the great vault. That aura causes this message.
