### ISSUE TITLE
Option to position Tick at empower cast stages

### ISSUE THREAD

**Issue by glassleo** [WeakAuras/WeakAuras2#4024]
**Is your feature request related to a problem? Please describe.**
I would love to be able to have a tick to indicate where on my cast bar each empowerment stage begins or ends.

**Describe the solution you'd like**
An option to position ticks at empowerment stage locations for progress bars with cast triggers

**Additional context**
Currently only overlay textures are able to to indicate where each stage is located on a cast progress bar. I think this can easily look messy and I think being able to add a tick would help with clarity a lot.

**Comment by InfusOnWoW** [comment]
While we are planning a overhaul of how ticks are placed, that's a long term plan and for now you are better off manually position them.
