### ISSUE TITLE
Warning message in the middle of the screen, which does not disappear

### ISSUE THREAD

**Issue by reden7or** [WeakAuras/WeakAuras2#4025]
### Description

After we updated wow yesterday. Started this warning box on the screen saying "It is not possible to earn new rewards after this week. All unredeemed rewards will be lost after the release of dragonfligth".
But the message doesn't disappear, it stays on the screen all the time, during cutscene and so on. The only way to make it disappear is by disabling weakauras.
![aaa](https://user-images.githubusercontent.com/118419737/202359964-757c4846-1155-4714-b6ea-49c0dd869559.jpg)

### WeakAuras Version

10.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Open the game and have the weakauras addon active.

### Screenshots

![aaa](https://user-images.githubusercontent.com/118419737/202359309-b1e60b63-86d1-45eb-8eb7-ddc1b308ef90.jpg)

### Export String

![aaa](https://user-images.githubusercontent.com/118419737/202360121-091cbba9-f668-44f0-8961-b312cb0e5095.jpg)

**Comment by Stanzilla** [comment]
You have an aura installed that interacts with the great vault. That aura causes this message.
