### ISSUE TITLE
Does not load import button/search etc

### ISSUE THREAD

**Issue by AnimaCharm** [WeakAuras/WeakAuras2#4026]
### Description

When I open up the weakaura window then it starts to "load" my existing weakauras (Creating buttons ....) and then it gets stuck there. It does not show the buttons New aura/import etc neither the search bar.

When I login with a different toon then it finishes the loading and show all the buttons as it should be. It only stucks in 1 character.

All addons are up to date

### WeakAuras Version

5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

20x Interface/AddOns/WeakAuras/Types.lua:784: attempt to call field 'CalculatedGcdDuration' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types.lua"]:784: in function `formatter'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4553: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4521>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4701: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4671>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4722: in function `ReplacePlaceHolders'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/SubText.lua"]:258: in function `?'
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:35: in function `Notify'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4248: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4245>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4340: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4302>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4450: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4179: in function `UpdateFakeStatesFor'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4152: in function `FakeStatesFor'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1442: in function `SyncVisibility'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:816: in function `ShowOptions'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:614: in function `ToggleOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:155: in function `OpenOptions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:197: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4924: in function <Interface/FrameXML/ChatFrame.lua:4920>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
value = 7
state = <table> {
 triggernum = 1
 progressType = "timed"
 changed = true
 expirationTime = 616136.330000
 show = true
 autoHide = false
 id = "Vivacious Vivification"
 trigger = <table> {
 }
 duration = 7
}
result = 7
now = 616129.330000
(*temporary) = <function> defined @Interface/AddOns/WeakAuras/Types.lua:171
(*temporary) = nil
(*temporary) = "attempt to call field 'CalculatedGcdDuration' (a nil value)"
WeakAuras = <table> {
 IsSpellKnownForLoad = <function> defined @Interface/AddOns/WeakAuras/Prototypes.lua:894
 normalWidth = 1.300000
 ClearAndUpdateOptions = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:848
 IsRetail = <function> defined @Interface/AddOns/WeakAuras/Init.lua:278
 GetRuneCooldown = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2043
 GetUnitFrame = <function> defined @Interface/AddOns/LibGetFrame-1.0/LibGetFrame-1.0.lua:486
 CheckRange = <function> defined @Interface/AddOns/WeakAuras/Prototypes.lua:35
 SetMoverSizer = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1615
 ShowOverlayGlow = <function> defined @Interface/AddOns/WeakAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua:612
 RegisterItemCountWatch = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:3601
 CheckForItemBonusId = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:4219
 UnitCastingInfo = <function> defined =[C]:-1
 UnitNameWithRealm = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:5623
 InstanceTypeRaw = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:1518
 RealTimeProfilingWindow = Frame {
 }
 GetSpellCharges = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2082
 SafeToNumber = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:5515
 GetAllDBMTimers = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2999
 ToggleProfile = <function> defined @Interface/AddOns/WeakAuras/Profiling.lua:384
 IsAuraActive = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:4864
 Rename = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:2045
 UnitStagger = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:5778
 EnsureString = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3980
 WatchForCastLatency = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:3468
 TenchInit = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:3365
 raidUnits = <table> {
 }
 StopProfile = <function> defined @Interface/AddOns/WeakAuras/Profiling.lua:356
 GetMoverSizerId = <function> defined @Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:1629
 GetGCDInfo = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2106
 GcdSpellName = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2118
 OpenOptions = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:151
 GetUniqueCloneId = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:3655
 WatchUnitChange = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2681
 EJIcons = <table> {
 }
 GetSpellCooldown = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2051
 SetModel = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:5477
 IsWrathOrRetail = <function> defined @Interface/AddOns/WeakAuras/Init.lua:298
 GetAuraTooltipInfo = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3844
 SpellSchool = <function> defined @Interface/AddOns/WeakAuras/Prototypes.lua:165
 AddCompanionData = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:914
 gcdDuration = <function> defined @Interface/AddOns/WeakAuras/GenericTrigger.lua:2114
 GetHSVTransition = <function> defined @Interface/AddOns/WeakAuras/Prototypes.lua:243
 SpecRolePositionForUnit = <function> defined @Interface/AddOns/WeakAuras/LibSpecializationWrapper.lua:102
 defaultFont = "Friz Quadrata TT"
 HideOverlayGlow = <function> defined @Interface/AddOns/WeakAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua:696
 UnitPo

### Reproduction Steps

Open weakaura window by /wa
then it get stuck at creating buttons

### Screenshots

![-8sEeiHxT0ScVvbF0yGMpw](https://user-images.githubusercontent.com/118481882/202554956-221ac2c0-dd87-46f8-a639-7c45551b0e2f.jpeg)

[WeakAurasLUA.zip](https://github.com/WeakAuras/WeakAuras2/files/10035593/WeakAurasLUA.zip)

**Comment by InfusOnWoW** [comment]
Is that the first error message? 

Clearly those reproduction steps require your settings.
So where are your settings?

**Comment by AnimaCharm** [comment]
Added the weakaura.lua file from saved variables. After a lot of search and tries I think the issue is in some of the weakauras I already have that gets an issue ONLY with evoker class.

**Comment by InfusOnWoW** [comment]
What is the first error then?

**Comment by AnimaCharm** [comment]
This is the first error in BugSack. Only BugSack and Weakaura addons.

16x Interface/AddOns/WeakAuras/Types.lua:784: attempt to call field 'CalculatedGcdDuration' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types.lua"]:784: in function `formatter'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4553: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4521>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4701: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4671>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4722: in function `ReplacePlaceHolders'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/SubText.lua"]:258: in function `?'
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:35: in function `Notify'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4248: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4245>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4340: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4302>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4450: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4179: in function `UpdateFakeStatesFor'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4152: in function `FakeStatesFor'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1442: in function `SyncVisibility'
[string "@Interface/AddOns/WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1468: in function `PriorityShow'
[string "@Interface/AddOns/WeakAurasOptions/WeakAurasOptions.lua"]:730: in function <...terface/AddOns/WeakAurasOptions/WeakAurasOptions.lua:699>
