### ISSUE TITLE
Progress Bar ticks overlap text

### ISSUE THREAD

**Issue by diab64** [WeakAuras/WeakAuras2#4032]
### Description

Created a single-weakaura progress bar with 5 ticks tracking Evoker Essence, with text checked in display tab showing how many essences I have with %s. I wanted to position the text in the middle of the bar, but the 3rd tick (in the center) overlaps the text. 

The text should be on top of everything else.

I see there are "Background" and "Foreground" sections that are moveable up and down; I've never used those before. But I tried positioning the "Foreground" above the text and the "Background" just under it, and nothing changed.

![WA-ticks](https://user-images.githubusercontent.com/44482861/202835494-df535624-5bf3-444a-86a5-f76a6e3b88d0.JPG)

### WeakAuras Version

5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [x] Yes
- [ ] No

### Reproduction Steps

1. Create a progress bar weakaura, with any trigger.
2. In Display tab, make sure Text is checked and input %s or any static number. Set anchor to Center/Background/Center with X/Y offset at 0.
3. In Display tab, click Add Tick and add a tick in the middle of the bar (At Percent: 50)

### Last Good Version

Haven't tried using ticks before.

### Export String

!WA:2!1z1tVTXXvCTGijacrbYuigoaUo2g1w2fnksmYXnaXqLRevPCLPyxs)xO6LZUZqUJ1YDwmZSsK6w5bdDM3samqbrpMt8wUfOpbdy8NaHIIIcKl6tqEZSRiPsLeGiEV3(MFZ7)VXAZ8TZJZJpA5bIyeFVNtXYGp9yd9onBkiYxyX7KszX7MsC)HOi)agVkJgj9wVuL6LCgzoIdtIKuwKv8voh)tyyIDXNwFNt9q(71IZsIWRZcz8hBvET)3Hh(pNzMzkV2V8U39tarUEsoTvlcx8j3LNr(FSLDJj2jruzC(ebXf5jyCVYeuOg7gNis8i7tIK1sA2K2zO76fRv3Tw9Io1pzI6gvDm65uLDaHR(eV4quxc3jc1MiMTFSwQ(QwSNiMegUfgeQbW8HGXxtvobUgNAvlT9290FxBzngnwtnengGjEG5uhO5LlTD1nF629tIY8OzJVcYxs3NupLxBB)WmdO(SixFtOjh83PqeMWJqHpdchqG8G(OiABtm9RDesexU5XeKGutYjrTKbFKAo7iwezeoHB0YvBjCbbGfl6PvvBoQfTBJOrptnNAr1Fa()EQ7RU7h5fZjq(Dakmoavnjuq8AsJOIGFRIQ)4qpih6t2G4J62ZdXtZMLx7)ETR9NHCOvUCG3lqsTzqcMUG6LwdGOOdPfyDIV)QQ5gbSnzCsAzXr3ioVK0r6kcqy2bVi9q5I)mJqZpGYqiWvKr4vjPThH3FSc3(oI4F)fOoM4dXUqxWl9Pctz6n))ul2vsBtCBZWUAtVXjPgdjSPPCx9HXlyKGsKmDIW30YyxeypnfhAhc2i8FCbwrg8HKwi)UUndzmEWO02PxM1MDSr)3KiK0MDvF4aUUjIuheAxzNkLY0olWyfFRl7og7MxuWloJWrRkwnhhsc6VNf8p)DmWiBsvz)mKIK9lS8YfUPnlehFJlZos5SohYN3x3hmtVqsJrgUdyC8Z5O4EppJy04Rtx7AxbQVJNFkWolXm)u1nztxSSYDUYPS796ZmbZA0dj3j((xM1J7cJgO(UYaO3iaC0UX)UlO2Yu7AA2Cmj1S66jJ7oA(tHIL9Cb)euekVio2BxQYgJms5Nn48yd7ztCtpYunsXZpUUdQH0D8qbQwhza8Beri(GbgE)S(rv1Qn09JLx7NxyHBQNUoupKsB8jCaVfmAddb9jTH5AgdJxu(muycj1wol5CY51m)kPFU74mPXmsXn(pTLEUvtq3DlIXqJ(UpNG2Ri4eIDntEnKpHGPODtLQ)DLvxzObMux7rPmTPCo0LKvJcsoAE1UQ)omsks5APAeOqnuEFG61wkCGIOAQEJApvRgQG8fuulv4JuTdu(xyW4sGsdc(YoJgZX3WxLb)RTYGcSIPrsJ8LJuq(vNcTuKG7(IH6sWiZNnwZdodTuOGl)O8fqX0GtGr0MCBORFinoyykTq6Mi(Bty4hAPMRheMnsoovEtAizlS3xT6Qp4HfgKklgjdIxKeTpLZI0LdIVuVns8LuFIpNDqehrXI96UCHLAxyc(YUw8uMUL)24zm)n1T35FpFVXDczkE4TM64DSMs7UNXywxvETF870)9VgLkmRSDkpvE4zy2XYlGqBfi)C7qgcVPNebvCYR60ojusN1gw97Fv1BN1XpejeAkBbmLqtCIztMTUjwVXUqXn2iEEOJQiwpWMGj4NG6eCBk(4ni7JUzjHGaRj9G1VnPTGt3MXKbv5SwW0erJF7rPrbd4MnJMhnGGEciXX1pua6H(A1DMvT0S2Wkz5S9NALuFZRgeuyMIZw)LY1hbdjG5I7eBo2SfsO4HH3)vp8BI(RR8gVhp04dLnrGhXZAzDQXcPy7dzS2wPRRRN1lFVj9YRJGLsrTSr8DF6wFXeUVOM51EMJfmqY83p95kxZ6TdYUnkgtICQu6zLCCmjSCdBYHhDbVCbjr5onDu(MArAF3R26oLkvX5a9I03)XPVoD9XBG40i9vqcmpyQglH7tU(mdzCkKhn1pdkVJZwVANk1lU9a9JFOPXIH0O0z2ahejHVeKx48GLkS0Y53)9V4xd

**Comment by InfusOnWoW** [comment]
Change the order between texts and ticks.

**Comment by diab64** [comment]
I... don't know how I didn't think to try that. Thank you.
