### ISSUE TITLE
Entering an instance breaks tooltip info if its value is not nil

### ISSUE THREAD

**Issue by IKnewOne** [WeakAuras/WeakAuras2#4033]
### Description

Retail version, the setup is a watched trigger, it activates correctly and gives correct buff, but doesn't provide the tooltip info until after reload upon entering the dungeon
First SS is directly aftering a dungeon while having the buff with tooltip info, second is after reload, third is trying to update the buff value after entering the dungeon and having it being broken
Text weakaura that only reads tooltip info without any custom code is broken too

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Get an aura with ( at least probably only ) dynamically changing values and stack it to some value
2. Enter a dungeon
3. See no tooltip info, as indicated by DevTools
4. Reload
5. See it now working

### Screenshots
First SS is directly after entering a dungeon while having the buff with tooltip info
![image](https://user-images.githubusercontent.com/41551327/202845851-6a61ed1b-7165-4b42-ac11-40b3f6b32aec.png)
Second SS after reload
![image](https://user-images.githubusercontent.com/41551327/202845854-00028e8d-f24a-45a3-a99c-4393eadb12c2.png)
Third SS is trying to update the buff value after entering the dungeon after having broken it
![image](https://user-images.githubusercontent.com/41551327/202845863-4dc6764a-bc5d-47cd-aa3d-75f59b2fed62.png)

### Export String

!WA:2!1rvWUTTrqulOdgGOW1rgWOXjhmsBccqbmQCqIDrAcGPbjscKTCPwxNCIEj3HIBd1Ul2DPLLpkuu0Z(tqNZj9j4d5mHr(cYNG)cYSIcnbbw8a5mZo7SV5nVLncBnOfRf7)ESwwAl4cq39ysNxFyquQSqQFtt8r9RmUrvqhrGZTXzs9aQnwfB5dGy2ibDapn2MRbtUSGn6AtoLjh(UUzzgWE)Lu)YTS72BzLYclx1EEeFHuaQnx8bv71qTAAPXkh4Y4yfJAHi4mqy)mTeJsT80t4mBU)EORMMA5sH5zrglvB9sY4cUj3Zh)y9gB18(9bTzLhPNB(rF7iferl10TVY92OGIcoZSrYt2z3FF3DUkdSP5KAOFALxYRaAHn)ZMYKzO4inKXppQ3rbD6OLdfDffJoD8SQ8AMXZVep4exdc6iK3aJ3nLgi4CeO9Qt60)Vw9kZWAnnE)96rI7r2lImHbjyqcIr9Rc6Cu4XDUSumh7EQ74A3ZasT)bsg8HLupyXm6ajlwJe4PQhT4KkG(00rXzfsPo)sduKDKKlSj(DjKUh4Njfw1QHA(fB(NLugwo6MeYeShIG(oUFJ1Rw7A0nHM(((OgtW8lKuwyILwGn56rdkrU0Zh5O01RA7fLwqngNLVHFb4mg7oKEOZDNlTEBT0QP(8AJgt0ZomhX4BXE4sQG70csXZQwj8kGAGEwni6BZxUATQLVMHZw3YXU5T2aPsbZm2LNRgvl7pGYfHvpFw2v)r1lQEj(9h)(iQ7DRexTrKJ)yQFEXCRsdPCdcJMtCaGptS6nEOuZortvJpzUrcUAgVVN(VrPppBKFNGqYeRm9me74E(Pg)7KhWz(eWyVgVhKl1Dv1fBAMgLzyZJdMM3qfP4AHUqU(mP3(rbbhQhnNg3UKZMso49QHLT72E33n9BG(0h(1RStRRtTqy)GdjbrtRNm7p7FgnA0O5eu7cSz3f)NFykxu35iM8Ub3fOf0I)Qg9dBzIE6wBV1V16Sp92Va

**Comment by InfusOnWoW** [comment]
The tooltip implementation has already changed since the 5.2.0 release.

Do note that due to game limitations the tooltips are not always available, that is even the built-in buffs in similar circumstances don't show any tooltips.
