### ISSUE TITLE
Weak Aura interfer with reagent bag

### ISSUE THREAD

**Issue by Arizosa** [WeakAuras/WeakAuras2#4039]
### Description

I can not combine the herbs for example in the Reagent Bag, the WeakAura program interfer in some way.

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

I did not get an error except the message in the picture.

### Reproduction Steps

I disabled all addons except WA, to see if I could replicate the issue by enabling them one by one, but I didn't succeed to replicate it. After I did that the issue seems to have stopped.

### Last Good Version

I didn't have a reagent bag in the previous version. :3

### Screenshots

![WoWScrnShot_112022_192115](https://user-images.githubusercontent.com/42410021/202920278-c6aabb45-fe28-4f8e-bc39-824d2a1bfbd5.jpg)

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10050459/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
WeakAuras does not prevent that.

You either have an aura that does taint your ui, or you are running into a Blizzard bug. Unfortunately the second is very likely, as the game was not ready for a release and was released anyway.

**Comment by Arizosa** [comment]
Ok, Thank you for the fast reply. 😊 Have a nice day!

Med vänliga hälsningar,
Lisa Ohlsén

Från: InfusOnWoW ***@***.***>
Skickat: den 20 november 2022 20:08
Till: WeakAuras/WeakAuras2 ***@***.***>
Kopia: Arizosa ***@***.***>; Author ***@***.***>
Ämne: Re: [WeakAuras/WeakAuras2] Weak Aura interfer with reagent bag (Issue #4039)


WeakAuras does not prevent that.

You either have an aura that does taint your ui, or you are running into a Blizzard bug. Unfortunately the second is very likely, as the game was not ready for a release and was released anyway.
