### ISSUE TITLE
Changing loading option on multiple WAs at the same time does not work anymore

### ISSUE THREAD

**Issue by NecoVeritas** [WeakAuras/WeakAuras2#4043]
### Description

Basically, either choosing multiple WAs manually or changing the loading option of a whole group currently does not work, you have to change every single load on the WA by itself. Seems like a bug because it used to be possible.
Usually when I do new Weakauras for my class I copy ones from another spec, change the loading options from e.g. Paladin Prot to Paladin Holy in the group. This does currently not work.

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Go on any Group of WAs
2. Select "Load"
3. Scroll down to "Class and Specialization"
4. Uncheck the old class, check the new class
5. For me, now only the first WA in the whole group changed, rest remained the same.

### Last Good Version

no clue when it stopped working

**Comment by mrbuds** [comment]
It works fine for me, can you upload your weakauras settings in the ticket (we should make it mandatory) and tell on which group you are trying to do that?
Also if you have the possibility to record yourself reproducing the bug (starting from a /reload) that could help

**Comment by InfusOnWoW** [comment]
Waiting for more information from reporter.
