### ISSUE TITLE
Multiple errors in WeakAuras/Animations.lua:17

### ISSUE THREAD

**Issue by dmsierra** [WeakAuras/WeakAuras2#4045]
### Description

What the title says

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

10119x bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))
[string "=[C]"]: in function `SetVertexColor'
[string "@WeakAuras/RegionTypes/AuraBar.lua"]:543: in function `SetForegroundColor'
[string "@WeakAuras/RegionTypes/AuraBar.lua"]:1152: in function `ColorAnim'
[string "@WeakAuras/Animations.lua"]:125: in function <WeakAuras/Animations.lua:17>

Locals:
(*temporary) = "bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))"
<HR>
1x ...aceWeakAuras/RegionTypes/RegionPrototype.lua:398: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:398: in function `SetAnimAlpha'
[string "@WeakAuras/Animations.lua"]:94: in function <WeakAuras/Animations.lua:17>

Locals:
(*temporary) = Frame {
 SoundRepeatStop = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:195
 iconSource = -1
 AnchorSubRegion = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:734
 xOffset = 260
 desaturateIcon = false
 Expand = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:909
 yOffset = -170
 anchorPoint = "CENTER"
 states = <table> {
 }
 iconFrame = Frame {
 }
 state = <table> {
 }
 icon = Texture {
 }
 SetOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:319
 icon_color = <table> {
 }
 regionHasTimer = true
 subRegionEvents = <table> {
 }
 currentMin = 0
 currentMax = 100
 triggerProvidesTimer = false
 SendChat = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:267
 SetInverse = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:859
 toShow = true
 SetTime = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:841
 Resume = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:971
 Pause = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:966
 Collapse = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:887
 bar = Frame {
 }
 ClickToPick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:758
 UpdateIcon = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:933
 OptionsClosed = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:753
 startFormatters = <table> {
 }
 SetSparkHeight = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:810
 cloneId = ""
 Update = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1254
 scaley = 1
 regionType = "aurabar"
 SetIcon = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:918
 relativePoint = "CENTER"
 inverseDirection = false
 iconVisible = true
 SoundPlay = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:249
 subRegions = <table> {
 }
 GetMinMax = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1250
 zoom = 0.300000
 SetIconColor = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:796
 smoothProgress = true
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:410
 alpha = 1
 color_r = 0
 SetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:328
 PreShow = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1351
 SetRegionWidth = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:816
 Scale = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1312
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = "11"
 UpdateMinMax = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1209
 RunCode = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:274
 GetYOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:340
 values = <table> {
 }
 color_a = 1
 SetOverlayColor = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:949
 overlaysTexture = <table> {
 }
 SetYOffsetRelative = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:357
 effectiveOrientation = "HORIZONTAL"
 ReOrient = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:958
 GetColor = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1155
 ColorAnim = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1147
 GetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:336
 UpdateTimerTick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:439
 Color = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1139
 color_g 
 <HR>
1x ...aceWeakAuras/RegionTypes/RegionPrototype.lua:400: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:400: in function `SetAnimAlpha'
[string "@WeakAuras/Animations.lua"]:94: in function <WeakAuras/Animations.lua:17>

Locals:
(*temporary) = Frame {
 SoundRepeatStop = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:195
 iconSource = -1
 AnchorSubRegion = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:734
 xOffset = 260
 desaturateIcon = false
 Expand = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:909
 yOffset = -170
 anchorPoint = "CENTER"
 iconFrame = Frame {
 }
 icon = Texture {
 }
 SetOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:319
 icon_color = <table> {
 }
 subRegionEvents = <table> {
 }
 currentMin = 0
 currentMax = 100
 triggerProvidesTimer = false
 SendChat = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:267
 SetInverse = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:859
 toShow = true
 states = <table> {
 }
 SetTime = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:841
 state = <table> {
 }
 Resume = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:971
 Pause = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:966
 Collapse = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:887
 bar = Frame {
 }
 ClickToPick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:758
 UpdateIcon = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:933
 OptionsClosed = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:753
 startFormatters = <table> {
 }
 SetSparkHeight = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:810
 cloneId = ""
 Update = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1254
 scaley = 1
 regionType = "aurabar"
 regionHasTimer = true
 SetIcon = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:918
 relativePoint = "CENTER"
 inverseDirection = false
 iconVisible = true
 SoundPlay = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:249
 subRegions = <table> {
 }
 GetMinMax = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1250
 zoom = 0.300000
 SetIconColor = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:796
 smoothProgress = true
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:410
 alpha = 1
 color_r = 0
 SetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:328
 PreShow = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1351
 SetRegionWidth = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:816
 Scale = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1312
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = "11"
 UpdateMinMax = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1209
 RunCode = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:274
 GetYOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:340
 values = <table> {
 }
 color_a = 1
 SetOverlayColor = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:949
 overlaysTexture = <table> {
 }
 SetYOffsetRelative = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:357
 effectiveOrientation = "HORIZONTAL"
 ReOrient = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:958
 GetColor = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1155
 ColorAnim = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1147
 GetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:336
 UpdateTimerTick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:439
 Color = <function> defined @WeakAuras/RegionTypes/AuraBar.lua:1139
 color_g 

### Reproduction Steps

Entering a dungeon in a 5 ppl party

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10060752/WeakAuras.zip)

**Comment by dmsierra** [comment]
It was caused by an aura, was not a wa bug, I close this.

**Comment by InfusOnWoW** [comment]
We still should put out better error messages.

**Comment by dmsierra** [comment]
Then I may add that I verified that the aura causing the error was the version of "Healer Mana" installed. Once I disable it from loading the error was gone.

`["id"] = "Healer Mana",`
