### ISSUE TITLE
Glows are sometimes modifying default glows?

### ISSUE THREAD

**Issue by rakkarage** [WeakAuras/WeakAuras2#4050]
### Description

I have some auras that Glow buttons that also sometimes have default glows from procs etc.
Recently, since patch I think, the glows sometimes interfere with the default glows instead of just overlapping like normal?

I have tried:
- changing the (mysterious) Border checkbox - no effect
- changing the type of glow (all 3) - no effect
- changing auto disable glow to manual disable glow - no effect

Have not been able to reproduce at training dummies just halfway into a dungeon? idk

Please & Thanks.

### WeakAuras Version

WeakAuras-5.2.0.zip

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. in settings add a glow when ready to a button that glows when procs
2. do a dungeon 
3. see weird glows

### Last Good Version

not sure but cant remember this happening before patch

### Screenshots

![WoWScrnShot_112222_175726](https://user-images.githubusercontent.com/962340/203633383-8ec06041-9a21-4527-bf58-cddac3530e0a.jpg)
not-normal
![WoWScrnShot_112222_175715](https://user-images.githubusercontent.com/962340/203633505-e9435d39-d373-4fc7-b64c-bf8585ae72a0.jpg)
normal

### Export String

`!WA:2!Lv1tpTXru8aUrPXkhcUrrPvrvw9qe5cIajuP2if5fwcK6GjJnbAdiVZU7Z7oH1ZSDMzXahTQQYPwvNpavYFe85EIVaDLv)e4l9ohA7X(MznKI6kz538M3)F)EVzM1R0TsyLW3TSuKPtyCq2yNw13Cl3HSabVPitga3)A(9OrInxBWAh9DVyls2JFU84gD6Oa9mJvX0qrVVT449V2ikpiwi3wW4A)vD3QLlzCGqKGYWB2JLcEP3oitPfDBbhR3jnKQbcCeW1lLjtM1X4vV(AjlkcKQF6bYPKV72eoTlOk7OpjfiQuijj)wJRfOzcE1Duu)eiTsMcARPYiqtGVpJjHWyNmot7NMqpbKPZzeicWSKf0mw0Rb3B8voorz)B1Pr8evMVn42wcDyhtAUTB96JLanPPja2cJiP7XqqMggBmT6cUE9TKBgQkFPnAM1bTXO2RwRzR2nBvJ0Ayi4JmBHzKCd36BV(o1t)eJDGJPb6pyT4b2etsdo0BWLC)478BdY4tRpLhfYuVnJJ1JJGLO8tsRmTmxCFDreli9PDSsi4ZRFy5Q4Ne0zsEv9BE0bvP8WQZRFZshuvirolFWdTS0V5Xhug4HLtNJAT(ul(sriu6CSndson51y3cTBVZpeG0AymgOju0tXduqshlCi)My(QOOdXEESthbxNE71LStR(QmAiYKwTvl5rfgQ0qSSrGiKu9z3nVYy8OpM)rioLh6hdSOyn4KiOH)LT0NcAFQwNaXtcsOkvBm2nvWGh4Ry8Oe49KUzjA2kV37N9(fpFnnb7j3n)PLhzu)iiMfGkxGHUQfILNk4a2lNDWLx61pqGnvkx)G8V(65p9Ux3BO9srxmm8ScYX2UmE8)X87WIjw1rLK7wJq2Sbb1n)5fkqtWYRNJnQVWQok2PGjmjbIeH8fLWV(MAxtK)N2)IzR4H4GtiZ0BvLNouUxXqzPZUqi3Wielr5SUMwdFfIchw0VoVIdhtW(avbgSyEZZmKn1sGhPJVX4qtldvOTz2tQaJRu(PsaT(ivcdHXcnI1C6szC0C5nZBH)25g5VoF389iy4Ci43HXzQ4))1dSwib6O73tid3vst7V7uIHsleWevoACHXszSWr7D834S(kDNF(9ELKAHZQvYjV7ENhLi61UJeNnSr641j1EPBt36UR2QbzK92c5DmJ5vIkjdfTnS9kUmXMVZnWEWMR1wTzmUuCakxX4umrzaGPF1MgGFhAaSFTWqmc2FxGEynSqP2FBrputd5lHqgD)Mgnu77Szl3ferrdl8fAw1CtkCfcooepQUzF0rwh4vrw6mlvBjKcu9ngIxHlavuShwX3g6jcrA8KPznUWd4bNS9hT4clVCHpkqmB8SF)xnFEB8S)8VXV)zUl5ye(lFsrY7JLCeUo8dfXjfBxDYWEl)rlD2uVBRmexcPbzIDF6LUYByreNs1XZoUGoiMY5qI)AmAIikF)JYzEtIXgoI2tS6QIZJCmCYH8o5NKFAopD5RuEBCLY7vkQ1yYnesUPUMlJDqigot3n(8INHw3KggWZGD2AZww4GDa)I974omClf4zwEAEIW8M0SeAsAmTO04CQq0Dg5BXEpRZjo1DxVv6DUyCYi9Am7tpHE(kOloUtE0clUWId1IGPlYU3m)4WVGfM)5YtM(K5iBXfNUWnELi9yH6yWhhP6WIklzCJE4smAgI2WPUGDnc4udpoQySEvBxDMzMP0q89ei0kWpCRrmEhHSyY(bJqYaW18SJYl9ESiUqcnsTZkwUUsPqQIhJUbRttVPCff5jlS0clw5O)yV)9p`

**Comment by InfusOnWoW** [comment]
Please add a sample aura to the ticket.

**Comment by rakkarage** [comment]
!WA:2!Lv1tpTXru8aUrPXkhcUrrPvrvw9qe5cIajuP2if5fwcK6GjJnbAdiVZU7Z7oH1ZSDMzXahTQQYPwvNpavYFe85EIVaDLv)e4l9ohA7X(MznKI6kz538M3)F)EVzM1R0TsyLW3TSuKPtyCq2yNw13Cl3HSabVPitga3)A(9OrInxBWAh9DVyls2JFU84gD6Oa9mJvX0qrVVT449V2ikpiwi3wW4A)vD3QLlzCGqKGYWB2JLcEP3oitPfDBbhR3jnKQbcCeW1lLjtM1X4vV(AjlkcKQF6bYPKV72eoTlOk7OpjfiQuijj)wJRfOzcE1Duu)eiTsMcARPYiqtGVpJjHWyNmot7NMqpbKPZzeicWSKf0mw0Rb3B8voorz)B1Pr8evMVn42wcDyhtAUTB96JLanPPja2cJiP7XqqMggBmT6cUE9TKBgQkFPnAM1bTXO2RwRzR2nBvJ0Ayi4JmBHzKCd36BV(o1t)eJDGJPb6pyT4b2etsdo0BWLC)478BdY4tRpLhfYuVnJJ1JJGLO8tsRmTmxCFDreli9PDSsi4ZRFy5Q4Ne0zsEv9BE0bvP8WQZRFZshuvirolFWdTS0V5Xhug4HLtNJAT(ul(sriu6CSndson51y3cTBVZpeG0AymgOju0tXduqshlCi)My(QOOdXEESthbxNE71LStR(QmAiYKwTvl5rfgQ0qSSrGiKu9z3nVYy8OpM)rioLh6hdSOyn4KiOH)LT0NcAFQwNaXtcsOkvBm2nvWGh4Ry8Oe49KUzjA2kV37N9(fpFnnb7j3n)PLhzu)iiMfGkxGHUQfILNk4a2lNDWLx61pqGnvkx)G8V(65p9Ux3BO9srxmm8ScYX2UmE8)X87WIjw1rLK7wJq2Sbb1n)5fkqtWYRNJnQVWQok2PGjmjbIeH8fLWV(MAxtK)N2)IzR4H4GtiZ0BvLNouUxXqzPZUqi3Wielr5SUMwdFfIchw0VoVIdhtW(avbgSyEZZmKn1sGhPJVX4qtldvOTz2tQaJRu(PsaT(ivcdHXcnI1C6szC0C5nZBH)25g5VoF389iy4Ci43HXzQ4))1dSwib6O73tid3vst7V7uIHsleWevoACHXszSWr7D834S(kDNF(9ELKAHZQvYjV7ENhLi61UJeNnSr641j1EPBt36UR2QbzK92c5DmJ5vIkjdfTnS9kUmXMVZnWEWMR1wTzmUuCakxX4umrzaGPF1MgGFhAaSFTWqmc2FxGEynSqP2FBrputd5lHqgD)Mgnu77Szl3ferrdl8fAw1CtkCfcooepQUzF0rwh4vrw6mlvBjKcu9ngIxHlavuShwX3g6jcrA8KPznUWd4bNS9hT4clVCHpkqmB8SF)xnFEB8S)8VXV)zUl5ye(lFsrY7JLCeUo8dfXjfBxDYWEl)rlD2uVBRmexcPbzIDF6LUYByreNs1XZoUGoiMY5qI)AmAIikF)JYzEtIXgoI2tS6QIZJCmCYH8o5NKFAopD5RuEBCLY7vkQ1yYnesUPUMlJDqigot3n(8INHw3KggWZGD2AZww4GDa)I974omClf4zwEAEIW8M0SeAsAmTO04CQq0Dg5BXEpRZjo1DxVv6DUyCYi9Am7tpHE(kOloUtE0clUWId1IGPlYU3m)4WVGfM)5YtM(K5iBXfNUWnELi9yH6yWhhP6WIklzCJE4smAgI2WPUGDnc4udpoQySEvBxDMzMP0q89ei0kWpCRrmEhHSyY(bJqYaW18SJYl9ESiUqcnsTZkwUUsPqQIhJUbRttVPCff5jlS0clw5O)yV)9p

**Comment by InfusOnWoW** [comment]
I tried reproducing the issue with no success.

And I looked at our code, and there's no way for our code to interfer with the default glow. So I doubt that this is actually caused by WeakAuras.

**Comment by rakkarage** [comment]
Thank you for looking at this. Sorry it was unrelated... I did test with only WA but I just discovered it happens with no addons too. Just looked like it was related because they both affecting same thing at same time. Seems to be related to macros or show tooltip...
