### ISSUE TITLE
Setcooldown

### ISSUE THREAD

**Issue by orlith** [WeakAuras/WeakAuras2#4051]
### Description

10702x WeakAuras/RegionTypes/Icon.lua:554: bad argument #1 to 'SetCooldown' (must be a finite number - Usage: self:SetCooldown(start, duration [, modRate]))
[string "=[C]"]: in function `SetCooldown'
[string "@WeakAuras/RegionTypes/Icon.lua"]:554: in function `SetTime'
[string "@WeakAuras/RegionTypes/Icon.lua"]:609: in function `Update'
[string "@WeakAuras/WeakAuras.lua"]:4242: in function <WeakAuras/WeakAuras.lua:4241>
[string "@WeakAuras/WeakAuras.lua"]:4336: in function <WeakAuras/WeakAuras.lua:4298>
[string "@WeakAuras/WeakAuras.lua"]:4446: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:757: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:713: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:886: in function <WeakAuras/GenericTrigger.lua:871>

### WeakAuras Version

5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

10702x WeakAuras/RegionTypes/Icon.lua:554: bad argument #1 to 'SetCooldown' (must be a finite number - Usage: self:SetCooldown(start, duration [, modRate]))
[string "=[C]"]: in function `SetCooldown'
[string "@WeakAuras/RegionTypes/Icon.lua"]:554: in function `SetTime'
[string "@WeakAuras/RegionTypes/Icon.lua"]:609: in function `Update'
[string "@WeakAuras/WeakAuras.lua"]:4242: in function <WeakAuras/WeakAuras.lua:4241>
[string "@WeakAuras/WeakAuras.lua"]:4336: in function <WeakAuras/WeakAuras.lua:4298>
[string "@WeakAuras/WeakAuras.lua"]:4446: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:757: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:713: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:886: in function <WeakAuras/GenericTrigger.lua:871>

Locals:
(*temporary) = WeakAurasCooldownpurge/tranq {
 0 = <userdata>
 expirationTime = Infinite
 SetDrawSwipeOrg = <function> defined =[C]:-1
 duration = 15
 useCooldownModRate = true
 SetDrawSwipe = <function> defined @WeakAuras/RegionTypes/Icon.lua:268
}
(*temporary) = Infinite
(*temporary) = 15
(*temporary) = nil
(*temporary) = "must be a finite number - Usage: self:SetCooldown(start, duration [, modRate])"

### Reproduction Steps

in raid, didn't paid attention when or how

### Export String

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10079329/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
So "in raid, didn't paid attention when or how", but you tested with only WeakAuras?

We need your settings to have any idea what could cause this.

**Comment by mrbuds** [comment]
Error come from an aura called "Purge/Tranq"

The duration function returns only the duration, this function is expected to return 2 values: duration and expirationTime
https://github.com/WeakAuras/WeakAuras2/wiki/Custom-Triggers#dynamic-information

I think WeakAuras should raise a more readable error
