### ISSUE TITLE
Analyze default UI for feature inspiration

### ISSUE THREAD

**Issue by InfusOnWoW** [WeakAuras/WeakAuras2#4054]
WIth Dragonflight, Blizzard overhauled the default UI and we should look at their implementations for inspirations on future additions, especially in what options we might want to add.

Thus we need to:
* List things that are worth anlyzing in detail
* And map them to existing / planned / missing features

Things to analyze:
* Castbar

**Comment by emptyrivers** [comment]
#4217 (pr is #4266) contains some thoughts about action/soft targeting, and what we'd want to do to support tracking it

**Comment by mrbuds** [comment]
Default UI has a new "new feature" animated indicator

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/ce6a3c0c-8ac0-4ebb-81ed-128991c83180)

It use template NewFeatureLabelTemplate or NewFeatureLabelNoAnimateTemplate, i have not investigated yet if it was ported to wotlk & era

**Comment by emptyrivers** [comment]
By this point, if there are any features in the blizzard UI we want to ape, it may as well be in the War Within version of this ticket. Closing.

**Comment by InfusOnWoW** [comment]
I've finally taken a close look at the casting bar to understand how it works. First of all there's a huge amount of stuff there, the cast bar consists of ~40 textures, ~50 alpha animations, 17 translation animations and 6 rotate animations and around a thousand lines of lua code.

The basic of the cast bar are pretty simple though. There are base textures, which are shown depending on the state of the cast. And spell effect textures which are mostly faded in/out quickly, and or moved around/rotated. Some of the spell effect textures are full overlay textures, e.g. a glowing border that shows up on empowered stage finish, and some are just a few pixels of "sparkle", that move.

The Warlock Soul Shard bar's code is hard to understand as all the power bars share some of the code, but it seems to contain:
* base textures for each "0.1" soul shard
* glow textures also for each increment, which are faded in/faded out on incremental changes to the soul shards
* 3 different deplete animations, depending on how full the shard previously was, all of them a flipbook and a outline glow that fades out over 0.5s and two differnt fill animations, depending on whether the shard was empty or not

I'm assuming that other bars are somewhat similar in implementation.

Now to support something in WA, we would need a way to add more textures/stop motion textures to an aura. A way to define the necessary fade in/out and other animations. And a way to trigger an animation run based on how the state changed.

Maybe a good intermediate goal would be to allow adding stop motion textures and a good to trigger them for a special fx.
