### ISSUE TITLE
Early Preview: LibDeflate, pure Lua compressor which compresses much better, with similar speed to LibCompress

### ISSUE THREAD

**Issue by SafeteeWoW** [WeakAuras/WeakAuras2#406]
Repository of LibDeflate: https://github.com/SafeteeWoW/LibDeflate
Commit when I wrote this: https://github.com/SafeteeWoW/LibDeflate/tree/c1510af970ccd092235d46f1248181f20bb50f18

Hello WeakAuras developers:
     I would like to give an early preview of my recently implemented pure lua compressor and decompressor, called "LibDeflate". This library uses [DEFLATE](https://tools.ietf.org/html/rfc1951) compression algorithm. The library provides much better compression ratio than LibCompress, but the compress/decompression speed is similar to LibCompress. I believe this library makes WeakAuras transmission in-game much faster.

_I hope you can have a try of the library and give me some feedback, and I want to know if WeakAuras2 is willing to switch to LibDeflate as the compression library._

---
### DISCLAIMER
1. The library is NOT production ready at the moment. This is why the README of in the LibDeflate stills says "NOT working yet." However, I have tested the library through Travis CI with 100% code coverage, so it is at least testable by WeakAuras right now. The functionality and the API is still SUBJECT TO CHANGE. I plan to make a pull request to WeakAuras when I release the Beta version of Curseforge, but not now.

2. I think that using this library breaks all WeakAuras transmission compatibilty., including WeakAuras stuffs on WoWhead and Wago.io, but I think it's a perfect time to break it when the new expansion comes. The compressed data produced by LibDeflate is formatted according to [RFC1951](https://tools.ietf.org/html/rfc1951), and can be decompressed by the popular [Zlib](http://www.zlib.net/) library. Also the Zlib compressed data can be decompressed by LibDeflate, so I hope this won't cause much headache for website developers.

3. The library currently lacks functions similar to LibCompress:GetAddonEncodeTable():Encode(). I plan to implement my own version that does the same thing. But currently you can use LibCompress:GetAddonEncodeTable():Encode() on the LibDeflate's compressed data if you want to transmit the compressed data over the addon channel.
---
### Usage
LibDeflate has only one file "LibDeflate.lua". Load that file in-game, then
```
local LibDeflate = LibStub:GetLibrary("LibDeflate")

local compressed = LibDeflate:Compress(str)  -- compression, current default is level 5
local compressed = LibDeflate:Compress(str, 4)  -- optionally provides compression level, 1=fastest, 8=best compression.
local decompressed = LibDeflate:Decompress(compressed) -- decompression

-- The following assertion always works for any string. If not, report a bug
assert(str == LibDeflate:Decompress(LibDeflate:Compress(str)))
```

---
### Benchmark
I selected a popular [WeakAuras](https://www.wago.io/Nkgbld8YW/15) on Wago.io, size: 132462 bytes.
Then use WeakAuras to decodeB64() to process it to get [decoded AceSerializer data](https://gist.github.com/SafeteeWoW/d9770e08a6989032de01b7d61b53d981), size: 158492 bytes.

The following benchmark runs out of game on a Lua 5.1.4 interpreter. The compression operates on the above decoded data. The decompression operates on the corresponding compressed data. Time is measured by average 10 consecutive function calls.  I think WeakAuras2 currently using LibCompress:CompressHuffman

|  | LibDeflate | LibDeflate | LibDeflate | LibCompress | LibCompress |
| --- | --- | --- | --- | --- | --- |
|   | level 1 | level 5 | level 8 | CompressLZW | CompressHuffman |
| Compress(ms) | 65 | 150 | 465 | 66 | 75 |
| Decompress(ms) | 32 | 28 | 28 | 21 | 99 |
| compress size(Bytes) | 23659 | 17323 | 16106 | 72639 | 99346 |
| compress+encodeB64 | 31546 | 23098 | 21475 | 96852 | 132462 |

(List LibDeflate level 8 for reference, but it's too slow without much better compression ratio).

---
Next steps of LibDeflate
1. Code cleanup
2. ChatChannelEncode/AddonChannelEncode
3. Preset dictionary feature.
4. Documentation.
5. Release on Curseforge

**Comment by Stanzilla** [comment]
That is a really neat idea. Do you intend to make it work with AceComm-3.0 ChatThrottleLib or your own implementation there as well?

Regarding compat, we could just run with both libs enabled for a while, LibCompress only for input and output is all LibDeflate

**Comment by SafeteeWoW** [comment]
Not sure what you mean by  "make it work with AceComm-3.0 ChatThrottleLib". I don't think I am going to implement a new ChatThrottleLib. (But I has a plan to repalce AceSerializer though)

**Comment by InfusOnWoW** [comment]
I'm certainly interested, but time is in short supply at the moment. If you have a serialzer working it would certainly much easier to test.

**Comment by SafeteeWoW** [comment]
Just to give you a quick update:
1. Early experiment shows a new serializer can further decrease the size after compression by 20%, with sacrificing much CPU time.
2.  The idea of new serializer: AceSerializer produces human readable format, thus not producing small serialized data. My new serializer will get  rid of the readablity, and the serialized result can be more than  50% smaller than AceSerializer for some WeakAura Lua table (Before any compress library such as LibDeflate or LibCompress)
3. The library is still under implementation/performance tuning/testing. I won't publish it until it reaches 100% test coverage. So I currently expect to publish the beta version to Curseforge within 2weeks.

---

The purpose of all these stuffs is to produce much smaller WA string, so it is more quicker to be transmitted through addon channel (roughly 90% smaller than the current implementation). However, the in-game string sharing of WeakAura, in my opinion, is very hard to use, and needs to be updated so it is actually usable.

My experience how WeakAuras shares string in-game.
1. When WA option panel is open, press "ENTER" so the keyboard focus is on the ChatFrame.
2. "Shift+LeftClick" the WA to insert a WA chat link to the chat frame. 
3. Press enter again to send it.
4. Receiver needs to click the chat link to import it.
5. Receiver may asks sender to send it again, if the receiver's chat frame is full of message and hard to find the WA chat link.

There are lots of cons for this feature. First, I don't think many people knows to "Shift+LeftClick" to insert WA chat link to the  ChatFrame, though it is the same keybind to insert an item link. Second, "Shift+LeftClick" is inconvenient and requires keyboard focus on the ChatFrame. Third, people often complain that WA link has been lost in the chat history and request to resend it.  (Last time when I checked the new features of WeakAuras is two months ago. I am assuming WA haven't changed this part recently).

Let's compare it to TellMeWhen. Although TMW doesn't have a good external website similar to Wago, I think it's in-game sharing is much better than WeakAuras. TMW supports to export the string out of the game, meanwhile it supports to broadcast the string directly to all players in the raid or the guild through the addon channel. The receiver can choose to import from copy & pasted string, AND the receiver can choose to import directly from the broadcast which comes from  the addon channel. 

If I was a raid leader, I will prefer to broadcast the WA string in-game, rather than put a Wago hyperlink in Discord and ask everyone to check it out.

I hope WA can do sth similar to the TMW's implementation. I don't think it is complex to do. It's basically is just to add several buttons in the menus of import and export and some code to handle the addon channel communication, but this will make WA much easier to use in-game. 

---

There is another problem of WeakAura string import, but this will be harder to fix. It is not convenient to update WeakAura, so people don't like to update. When you import a new WA string, the first thing you do is to adjust the position and size. And you would have to do this again, when you import the new version of the WA strings (Besides, you need to remember to delete the old version). So people don't like to update WA string.

My suggestion is that, when you import a new WA string, if you already have a WA with the same name and type, prompt the user whether he wants to replace the old WA and use the position and size of the old WA. The old WA won't be deleted, but will be renamed to sth like "xxx.old". The new WA will be named sth like "xxx" (not "xxx 2")

**Comment by InfusOnWoW** [comment]
We do have tickets on updating/importing improvements that go into some of the stuff that could be done in those areas:
https://www.wowace.com/projects/weakauras-2/issues/542
https://www.wowace.com/projects/weakauras-2/issues/266

But, that's not a area I'm too focussed on.

**Comment by emptyrivers** [comment]
See #450 for some work on updating.

**Comment by emptyrivers** [comment]
@SafeteeWoW the repository you linked in the top comment doesn't have any commits dated after May 25. Is this still something that you are developing?

**Comment by SafeteeWoW** [comment]
@emptyrivers 
1. Sorry, I am not working on addon development in the recent 30s days due to work schedule and FIFA World Cup.
2. Though I haven't touch the [LibDeflate](https://github.com/SafeteeWoW/LibDeflate) repository since May 25, it has been in a production-ready status since May 25, including code cleanup, code comments, [documentation](https://safeteewow.github.io/LibDeflate/source/LibDeflate.lua.html), online CI tests and 100% code coverage. LibDeflate has been released on [LuaRocks](http://luarocks.org/modules/SafeteeWoW/libdeflate) and [Curseforge](https://wow.curseforge.com/projects/libdeflate).
3. I am planning to tag the version of LibDeflate as v1.0-Release soon. No code change is planned. I am just waiting for the feedback of the authors whose addons have integrated LibDeflate (For example, [Total  RP3](https://github.com/Ellypse/Total-RP-3) if there are any issues in-game.
4. It should be simple to enable LibDeflate in WeakAuras2. You need to pay attention to backward compatibility issues though.

---

I did mention in this thread that I was working on a new serializer that would make transmitted data further smaller combined with LibDeflate. I am working on it and that work is still WIP, but I cannot give an estimate date to release it. However, I think the compression effect of LibDeflate is good enough. So ignore my WIP new serializer, for now.

**Comment by emptyrivers** [comment]
It took a while to get around to implementing this, but we finally did. Thanks for all the work on this library!
