### ISSUE TITLE
Loading screens from changing zones/instances cause Spell Charges Changed Event triggers to fire

### ISSUE THREAD

**Issue by Breeni** [WeakAuras/WeakAuras2#4061]
### Description

When changing zone by entering/leaving instances or taking a portal all Spell Charges Changed Event triggers fire as if the spell charges have changed even though before and after the loading screen they are the same. Seems most likely caused by Blizzard apis returning wrong values during loading (or maybe spells being unlearnt/learnt) but would be lovely if it could ignore those changes.

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Create any aura with a Spell -> Charges Changed Event trigger (gained or lost)
Set the timer to longer than your loading screens
Enter/leave a dungeon

### Export String

!WA:2!fAv3YTXTvyZHn9ND60XI(NiL6KWQe7Q0gRilh58ttAlxjsj5stQSCLSCg3sIDbixyTCxyS7kkQ7SAhpQZ0EdVR3Y76m5k(iONGZWPtFa0JGEc6byxsj)JMEZUahCoaNdW33hqUDkezTYIlV4sf6wGwGE87p2H4Uhvgkwn0pu(W85ZVv(LwCLtDcLuM0mBqXvn95hEirslAhg6hZfdJdD3NjJ4HbZM7LdLhuVD7iwCoN0a9gM(VmTdtmtJNNqKSIvs89l(ypEmBOK1bJ0UVGz1rgMiYCVb)q27mkTDAcLlxU8wrUeFw(m7BgGRtEjXngNHOhyfftKXgoT5b8ipdt8xSXrXsENoy69E3rM18LdPmNK2TvRPCJYv3QY2vnJvjajrsw(OibZ3FtAKXPrjoS9zbXnqV5hmQ5QLAy3SHDjlBZeCYDe(K(mPvaPllYWs7QZgmIFS30q3sYWqTASv5QvhKeKLcgY(z7sNXdIzYaI)oPBH9grcC9cLBfId4SA5A2LTgeX8BRnalmpNkE3v9iYoSi8xqhgTSADSzrXJ4bTdLDjQTdJrTLyA1iwsIj5plDsROmPkBNgRAvUCTXKKy0CDHEd0WXnmOnVJXjPBVPz4pBiwkw6dPiJbKaE68)ayMkNWirQvGf0j27NaZAgegWgtXnrLhnvBPYigoP0OJuUQwzyfZUeEqf4ZXaGvGhaFb8L4)cVULHQ44PjMPFiHwXjgp7dIVPv3ee3zyINtU3e(wdlxFsuKQLzeIAunwoHthTWxU)9AS2swpGgxW93C8hnKJtzJWePl7wxbUDo4xdlm2fbX0WEbn6XfSwNmPRcT6zQcOfC9FXDGBCCHbuUKPHAMvR3WwmtseRzhwatYDB4f2REqRXVs3tJ0)wnBkHp0ySkKPttl4MW7cZAPXBWVeUfu8SSt2IzhTIRPIGDacXBQDRgEa6nwIySgt6E2AmsSxrsaT4AmxsF9Im15wW7zC0KJK5V3kdMoYp9FNdEF4dgOChrjU71cMh(i4JneZOyu7ZStXQpkKY(HRa3P3z7XyIsQD9yl105bFcSaYLIiXQ5N5bl)13eMDmIxusjk2Ca94RlkeZoatFpcUlSBgSxmN2O(tkMTzuwdyLbthB(BhjU6fc)CLGttToHyywAB76IRPnIG6qfi19XCASNzjS7zPle)agvB8fJtjepjlDorp(ZsII5T7JfLmmgliB0OzT61kdZkXIs5ZqTJUtuiZpiRccIfxTIKFyXVlHqvuUI22VsHpzLgRT1djypwseh94SgPjW(8iUJpRvwnFbLaXmBwRwzRMM1TTR)iRnxFd7XtxALw5Czv0UVY6OgvlZvFB7QBwR8)DCh)WEvKSNNWcC7V1pAPfxEL0QtnWi1NjZWrQoQGh7Kehhguhf5r9UHkZv1u(BO9FsLnq1z6Dh5pbXvRpXINPAqpTln0s46eX2J7UxalkkVEKQCS9m6fWm9UdhpgVJx8lGFxf4pQi2WVx)9pO)(n6Vgqfyjd4hN7OjK3wIRpPP6iCnEeb3vPEWNM38WWWU5G7RKV0QnOOZejOV6nSu4nS8oQR4Umn4QHrXwNJnSi(cpsE4UWIIc4UXeHaKqH8hKzwAuxwp)7D)o3N1EhjpqDlkZZQNgHcFMb81gWV1aUkMSgW1mGcgh)zdJee5EAq8nGvv6yFAETqM2ULc3Ie9CIzEL(kom0eQ4nrmdw3z9siGynObkkape(tO8euntscEuQCeudQ7bBbFhyP0r06dOKbyR0o2UfSzluUa25hUIwA9c0cuTqjoCKdj7Y78iLf217eDwLcyEsoy5hI6fWtYenq6plt0yoXV6n0henJ5DznfO6jxDtzE4PZFBHO4L5y3qAtPEF(VGLElGaoVq8XxM3(Soe3(nB7hIOvGclamOnezwdVsdZXoGmh4LwBC4zW3Nh27wx5TOIjYAyPMvk4dDbuOpCyk9TA5k2Ip4YYH0E5G)SwHdE(CIp5YCL2hF0b3TzSNKHxZ4t7dU5o(6Q8c3vcMmfNx54WtRkv5CHAblKP55O08ulWarW)ctcSYFl1zWu1A4V(Hk6538g0tnH9u9jUjEXnvbcxU0ARjUksgkrvQTmkJ(iYbEJ0ETbNszbw1kVtzRmk6R9kHV6))7gYOlfumMxFL4bEGHu9kpeyIkgxeoUBUbAqCeNYSsR)LmsDqjIKizIf2u9wT2ex2txLGxve0XKiF62BE3Z7D3gQaYkhT213kJtd)OjpCg59FH)NV8ZF2E9k12bEzolT7ENlUm3BrCzD8vtiG6F(3(5WFxRPGQzPIbNR5c)dpu2yuOKJbOj(d3OU1MFF9A2LQMQMC25xnp9Yu978lS))z3)3p

**Comment by RedHarlot** [comment]
Additional information:
This always happens as the op posted however I have a .lua  error dump

6x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON11"]:2: in function <[string "ACTIONBUTTON11"]:1>
