### ISSUE TITLE
Druid Cast Bar Error

### ISSUE THREAD

**Issue by Krispy262** [WeakAuras/WeakAuras2#4062]
### Description

I updated my WeakAuras for my Druid and received an error pointing to issue with the cast bar.

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

Message: Lua error in aura 'Druid_Cast_Bar_Balance 2': init
WeakAuras Version: 5.2.0
Aura Version: 5.1.7
[string "return function() PlayerCastingBarFrame:Unr..."]:27: attempt to index field 'power' (a nil value)
Time: Fri Nov 25 14:51:33 2022
Count: 2
Stack: Lua error in aura 'Druid_Cast_Bar_Balance 2': init
WeakAuras Version: 5.2.0
Aura Version: 5.1.7
[string "return function() PlayerCastingBarFrame:Unr..."]:27: attempt to index field 'power' (a nil value)
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:111: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:90>
[string "return function() PlayerCastingBarFrame:UnregisterAllEvents()"]:27: in function <[string "return function() PlayerCastingBarFrame:Unr..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/WeakAuras/AuraEnvironment.lua"]:374: in function `ActivateAuraEnvironment'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:805: in function `CreateFakeStates'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4176: in function `UpdateFakeStatesFor'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4152: in function `FakeStatesFor'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2996: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2862>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3018: in function `Add'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1846: in function `UpdatePhase1'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1854: in function `UpdatePhase1'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1854: in function `UpdatePhase1'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1641: in function `ImportImpl'
[string "@Interface/AddOns/WeakAurasOptions/OptionsFrames/Update.lua"]:1488: in function <...ace/AddOns/WeakAurasOptions/OptionsFrames/Update.lua:1487>

Locals: <none>

### Reproduction Steps

I used the update application inside WeakAuras and in the process of the update LUA error. Attempted to reload the UI and received the error again.

### Export String

!WA:2!nEX3VTrs5ymCv4JhAtRs7joa3ae1iLZnXPPnTsvv7A7e7whBZA7M07A16z3DS3Pz9UdZmojoVrec1NJoH090H8Fc(FaG8kcXkdsiepr0H4fEQpGesGkFZSRDC6LwXgL1ZmFFFZ3V)XMyJz7oRZSoVsBaNIy7UnXr4(ThqSd8Rh0JzJ)4zyhuTDBowStYLZSgRF0ML(Mdr(2UbSAbeFHvUcvAuWyK6kmceibjWpr2EmpAAxHGYFWTV9(Oobzib3wRn2hXmZZ6rCU9kRFNxBHS3TdlONVtUaVa2Jl(OF7vUs6zM5ofF0F4l)YF9BEZFV4J(lFXx8BMzM1tEC7aFXgEOoCw1MnkxQsbLOAAROmj8Cmh71wjuHFWrwi2478FC9R)dEZB(BfF0x95F(VAMzUAYKdCWCKOhdjWUNOK8iv7zj09cqoV6QmIVuUOZz0TNNGK64ECSPpEpmZ1W2dX5lyXbu8Wg5nAwkF41(LdZxqRrXNuP0MfB0ITTMHrPQgTy10kRLVuLw6BPTzb15LRM7jTmmQUzZcTcVbaOALN0YQErTT0Q0sXhfdAPZc8WleEDwEnjTgHxBUWFylDo5q8CHxlftG8W(ISY1NQOWe57yYPyBGO)iG9VVLveosu0LaGfpOvRwSdd8XLC4FJboK2Tj2Gg2xIZijZ3d7sS9WnjUS2iBPZuc6y6E0ZUmfIuSWcjeEyxLq7bghpxDgYwjE0zNOjtKl3t5DdceU1ybDyyo3LEzajnNx2JlWoyNTi(Udy4oapB0NIziWbbUXxRCq5pZJXe4dGLyJCEyKFK)Rr0rwRS6YRFV7zOoZDGiWgCzC4cVrIFXadKh1fLmkApk4izXh9x)UYhCIKNAfWCWmDiM0Hfq1RawjlzOBP8hxCxwDNIBS1MgQWTu0lBdcDqxjBBsDaPYQN6NJemsNoapRSalE5)6eLPaXfsTYvxaV175teNY7zbwnFr9EGB4GHM50Q3WSEdnJgdJUEtxId2qq6IDoYrQ8GMm7kJ6G9XmIDD3G9Rc6V6hnWxThEYvwJHHR0OETcLlF0yERlxCKuAKSV1rGtXZdcesz4J6I5PcFSf1d1hZmu3HEoaDwp)OnOEIaiVXcKvL3PyHY12Oz5J75hRNPg6q4VSNVsqYI87tVcsTUre8TcCWjFnKDIz(iVNg5x2)yKpPRsXURbxGyINgws3hm9hHrCSKtHDorUSUGH97iCV0OXwctPLKXXqvahUffcPWc92ihSExeXFJqYLclf2j8LH7g6g2XQnXNWDFQ6myVeSeKxyxvDiPpVK)gmOkdeOki272pFmJCzXrr)8pCayGnuHO8pDUWsJGTNveBVrrHqMbQQjjhVnQCzwiwoS0XskuhFsm0Ocyjsmjc0CpcNy5HBnmEp2PdMEL6)0Eigo9g988sVTlrGhdwwsi5cH9tfjpTdGCiL88QzZIOqICxWY7zEqIHrl4cZE8FYzByhMiS0raLQtoj682epOgH1QzxFTLxEq0zuKWLEtvud)2iMnYhtd2xkbqzFie3fZfz6M9SBw0prmZ7)XZmfdp4RU8rS4Ef5)WtbdJzeqBpcT1u0FWy6pCNK3nZAXqIYJhfTzIX6mQoCknL1pXRstNvwYWK7ICc2FNOA9jO3uDO6fyZGGqt4pixZecLSjs)DYJNGY8)ykDX3fbo9HeiITPWfccDd8C6pkYNpHxF0xJuA8IWkX4(SyCpnswh3ltxRzJQ0RQouMdktwSv9Q11GTVo6ojhGDuh(ZOF)3LugTlb9hDbYIcbpChKDFZ2EbbSwNOqqwBM0UF4hmq5VWYcE6vQwPWfOrIjAe9YtzVZnj(o2nCE1nSedc9Kaoh4XwUbQZShxT(F(FGN)73dAQ)NLp)7ypKC2GbfoqwdGVpQpn97YgaXfMYMiToxiXyz5cOJ(w0nsbCFiZBBgIE02XlISwJJfJ1)PgtAyPkvkyyAihpy0erwvE77CbEm658yNrqDiv)JUG4q67ko8ccYPVDqULlM0XvCZtvng1HU8oYA1z1YN)T7qJoW1IRgo0I0LgWe0lhPKBWGoiQxJQ3CJMq7LOojzHr9gU66ER94612F1nEwCjXXfAdFrRJvtXXHgD6LlSrJPhhBNe0RCU5kLILfmNutTYdvakQK8hYIMuHF3W2ZXCcm74fSVByWCH)oxDOQVybRO(PhK8L1uILSZgm)MoksWFqtF5ChGsY088ki73XV1IPs9jFstoo98xmngFDkMpTiinmhIF6a)0wEKdpeXCsl76MgQXLkvkVaBKxA7vwkTD20pmDoggIPuji3cMW((lf)6(3zPvwCP3c89xhGS(QsWRaGbH7)RNuPiTt7hislhNYe7VxMOrSYasuMomKdbK90cxSFQ0WZ7fRhErGFqKygpbgy2ExxtxeF337vSfGWzxdego2GbOCXegdFkbCA5ngAmFhlcPsng(dQJfJ5Nuk28STlU45Wc8XQ0yUeVmwDop0nJxFR5lw1O0NwTsdTYZVe4LTZcbrsEonN(SpRKCgiy6A8Z1CCQ6ZF(2y0UAG2XF(wyhc65XOYFEupFtzpFvl)x8ILspFUYABvRrv9YA5EcKJwQrPNwy(3Z5vkOzuOEJ5xCIOCE1PnOoPIwebe6UERLNsfbPCAxJ8wwm1eVHAeGm98HsKK2eSdyQBJ844JHeXO0UwJGgxqrIQuvwAkliJVnPtkloUlmzLXAzwjZ9m2x2(Q23k7kRcn6JYUjooyFD9QnkQFyqq3AWNHU6W2YSpyAqKaDPxpv1hzXuR65mkuOYOXd0LB8hhkjDT5jo05uF9PPmz2esLH)9G7agN2xoJh2D00FTb2DyatAcuvFgCM3DGCMtsK2mK4hvzf2TWqyPnoQEql6niD8HPXI1B1PfySag81DYQETMLd6E2mlp7E)PD(F

**Comment by mrbuds** [comment]
It's not an error in WeakAuras Addon but in your aura called "Druid_Cast_Bar_Balance 2" on init > custom code
You can ask it's author to fix it, or update aura from where you found it, or try WeakAura's discord for help fixing it yourself

**Comment by mrbuds** [comment]
But it should not trigger an error from Update.lua ..

**Comment by InfusOnWoW** [comment]
That's debug stack trace actually not a problem. I have looked at the code and tested it, this doesn't prevent the upgrade process from working.
