### ISSUE TITLE
(Rogue) deeper stratagem and tick on a progress bar

### ISSUE THREAD

**Issue by Paliosis** [WeakAuras/WeakAuras2#4064]
### Description

When tracking combo point in progress bar. Theres a bug that skip a tick after the 3rd combo point and add both the 5th and 6th at the end on top of each other. Everything is perfect at 5 combo point without deeper stratagem.

The progress bar work fine just the tick that show up in the wrong spot.

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Taking the deeper stratagem talent

### Screenshots

![WA Stratagem tick and progress bar](https://user-images.githubusercontent.com/119116168/204091628-a27f3aef-dbc1-43ed-9672-e7ec16940579.png)

**Comment by mrbuds** [comment]
You didn't share the aura and/or gave steps to make it, so there is nothing to investigate for us.
But that sound like it's the aura you made/use which is incorrect, not a bug in the addon.
