### ISSUE TITLE
deeper stratagem, combo point and tick on a progress bar

### ISSUE THREAD

**Issue by Paliosis** [WeakAuras/WeakAuras2#4065]
### Description

I just tested it back and it might be a bug/issue with Tick 4 after the 3rd combo point (tick placement value = 3) with the talent stratagem. The tick disappear if thickness is set to 1 but reappear if the thickness is set to 2. The bar thickness when set to 2 is correct. 

The issue happen every time the thickness is set back to 1. And only for Tick 4.

p/s.: Sorry for not adding the string in my first post. First time reporting something.

### WeakAuras Version

WeakAuras 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

taking the deeper stratagem talent

### Screenshots

![WA Stratagem tick and progress bar](https://user-images.githubusercontent.com/119116168/204095459-59a21c42-2e13-446a-ba98-de2f810396b8.png)

### Export String

!WA:2!DwvuRTXrqyle0svOefvsin0cP(btHGDtCIDtGO4ijlf5uhl3tNttdb0T3DR0UXN29y39KTZlPiAt9Rr0N6tf9CFs0Faf)lyX0)av)bk4)aPZUNITCOqk2pyT7EFFZm7mZ3SzQvOBHWcH7)vdLXiX2FhnurU4qAaN1KNicWF2mhIsueUOrSIYzYCI9A0UTeRQ)NK7pZkV5nVzeIfaFFtoLP8RuDd3QohATLdxHmCYeFHtT)r8qC5sB52qGcS2CzhPcju5ktzuvo)2WpssU(kbTthSqUXCIjl3)k9tK4wIeg2l(cMLDWmSGg0KW3PbZ7WtTDS0(tfopkKVdZsnb8G3abUlcCcRtHRp2CkYxYf(M4YZHH6IL5kBa6hhH2dlo0ajMVdwO2lg7nme7N0UTlSwuV66BwBR1hlt8X9Wmvt4d0Dh1QsPMUTA6wYX1s(y)5fx4e)vhJIs9P14fUXy7VT4GHrkUy27v8ydVPadg2P5MvxFDh7joBAahN3gCyOsXuw6KbhhQF0GJJCV(YyCu0AHWvZ8j9LlBYIzJlCCSnTFpyAlo7Dwk(ItFWjiVBXbjSjfNCJcPYNNWGAAp8Ii2EXxazx7M(DZv93NX2A1kGhXfpml83rqxdwWqrpgQ0qZWodK4O22Mj9h03hjQKcT(k)9RF9VnZmZKjluaKivcebyYb2oR0oYVpZqiD5G7y6P(1lPV2HW22CbUJGNWcNCGpky70d2p)rkAW2T8JWSWwDHWBXsRU6H2ZeVT39a72Dt9qMuct5)48G6G3fWg0cmthfXBSfJIa)NHLYS6Rja3AoCKPCOW7cCXKHwyNKisPbDCb4UqIUW1t98e12K4yc54VCntwRnG9zvqsfu9kJepBR1M)KDZ30KzsP1JkPWT0BKDxACwmDtxQqWfK4p50U3MoeLupgfLG3pVUO(E6vYOVFgDjIUSNUcCT0RQRs01SrV(bfUHUEg9A6hQ)gp96f1pIO3q34)h1fp7uV5zN6To7ux6StD5)lQ(emTdr95LJ4OWEwzldu5cY4GiKu2cbnOGaoyoFjuDJW)X5D6MePOlVAEp38E3kVNVcb1v1L0BLRSbPzr6WMtBbIJDFko6lWMfJTIOYgzGrKQVNDQsPWNNiv4qC4Jq7sCqrXeu2Jsh2xtatjnta9BwXPA1nkBu1K3LgLrgkSYr7Wseizab9aeJ21kUwwFUA6RvMXz4dWijUPsyBn)WddnQlarlZSkHedwpu23GXyjnUSzMfWvJ1T)qDhnrtHLF87EYa7Wgjne74S2dQ7oYErRtddXmNnQ(4QoI3QSN8jBzOOyIot0C79IOm8Ij0Wr7v72nCR9Tryx3YVGZ7MXXsbeY8GEPdVUCMxnCwA4Gk8U(8RcIqFW)TPDYnQTjHb3pKcL1zhZJS)Y5sND5ors)P(CwIK7)CSDOPCEivnVfr6lZvoEsHGYm(70d)EsMrCbf6aS5TH1B4S2tBSHBP1hAYDu77SpDoNacoy7A6ZNTFpKGIGHc6VywE8Sfl60Zi1lCdrabX6GLxzo9Ri9JfMz9qvOamdBHLwy6XjZP)rJL0)uQjUBr9RaL8pBjQ3pLXYVxg3eyCP3c)RFVWV10WV97f(std)oNc(ikdECiTtm3rN8SqAIU(k)q(8x18Et9v(Nx(s7lpfKolTWIlC9c9(RN8V)

**Comment by InfusOnWoW** [comment]
I believe this is arleady fixed for the next release, which we'll release before DF launches. If that's not the case, please report back.

**Comment by Paliosis** [comment]
Great!  =)
