### ISSUE TITLE
LUA Errors  GenericTrigger.lua 

### ISSUE THREAD

**Issue by rionshin** [WeakAuras/WeakAuras2#4066]
### Description

WA generates LUA errors on generic functions

159x Lua error in aura 'Stasis Icons': Trigger 1
WeakAuras Version: 5.2.0
Aura Version: 1.0.6
[string "return function(allStates, event, timestamp..."]:54: attempt to index local 'state' (a nil value)
[string "return function(allStates, event, timestamp, subEvent, hideCaster, sourceGUID, sourceName, sourceFlags, sourceRaidFlags, destGUID, destName, destFlags, destRaidFlags, spellId)"]:54: in function <[string "return function(allStates, event, timestamp..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:548: in function <WeakAuras/GenericTrigger.lua:537>
[string "@WeakAuras/GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:711: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:884: in function <WeakAuras/GenericTrigger.lua:871>

### WeakAuras Version

5.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

 
159x Lua error in aura 'Stasis Icons': Trigger 1
WeakAuras Version: 5.2.0
Aura Version: 1.0.6
[string "return function(allStates, event, timestamp..."]:54: attempt to index local 'state' (a nil value)
[string "return function(allStates, event, timestamp, subEvent, hideCaster, sourceGUID, sourceName, sourceFlags, sourceRaidFlags, destGUID, destName, destFlags, destRaidFlags, spellId)"]:54: in function <[string "return function(allStates, event, timestamp..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:548: in function <WeakAuras/GenericTrigger.lua:537>
[string "@WeakAuras/GenericTrigger.lua"]:752: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:711: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:884: in function <WeakAuras/GenericTrigger.lua:871>

### Reproduction Steps

Error happen during Dungeon and open world content on my Evoker and Hunter

### Export String

[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/10097098/WeakAuras.lua.zip)

**Comment by InfusOnWoW** [comment]
That's your aura 'Stasis Icons' not WeakAuras
