### ISSUE TITLE
Always-When user transports to a new location actionbar or mouseclick use causes error

### ISSUE THREAD

**Issue by RedHarlot** [WeakAuras/WeakAuras2#4067]
### Description

After zoning into a location the game issues a .lua error when any keyboard or mouseclick is used.

### WeakAuras Version

5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

6x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON11"]:2: in function <[string "ACTIONBUTTON11"]:1>

### Reproduction Steps

1. Hearth, Teleport, or leave Instance
2. Click the mouse button or use a keybind on actionbar.
3. Blizzard error frame states that Weak Auras is attempting to use a forbidden action . 
4. User must use the command prompt /reload.  To clear the error.  
5. Does not happen until step one is done again

**Comment by InfusOnWoW** [comment]
Nothing in the WeakAureas code creates any SecureTemplates. You either have bad auras, or very bad auras, or are running into blizzard bugs.

**Comment by RedHarlot** [comment]
> Nothing in the WeakAureas code creates any SecureTemplates. You either have bad auras, or very bad auras, or are running into blizzard bugs.

I only have one aura loaded at this time.  I had previously reset my UI by deleting my .wtf folder an the cache.  I'll try removing that aura and see what happens.

Thank you for the quick action on this.  
Cheers

**Comment by InfusOnWoW** [comment]
The game is also in a very buggy state where using the edit mode almost gurantees problems later.
