### ISSUE TITLE
gcd calculation on evokers triggering errors

### ISSUE THREAD

**Issue by raduabc** [WeakAuras/WeakAuras2#4068]
### Description

The weakauras that use the "Time in GCDs" format don't work on my evoker. I can't view their options or duplicate them, even if they're set to never load. If i duplicate a group containing one of these was, it duplicates one weak aura, but only after i relog.

### WeakAuras Version

5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

1st
https://pastebin.com/wSqvBB9n
2nd
https://pastebin.com/c49tx81G

### Reproduction Steps

1. Log in to evoker
2. type /wa to open options -> this is where the first error occurs
3. click on any weakaura containing gcd format -> this is where the 2nd error occurs

any other weakauras worked fine for me 

### Export String

this is the innervate weakaura from the error, but any weakaura with gcd time format would trigger the error

!WA:2!1vv3UTTnu46guuSSlwN7qqN3qrwXAw3UiOlflady3y5Q0Moh7mzLMoGairrslXgjrcsk7yVFaQVyOx7hbF9UYpc5jqWypb5I9aKNGDiLtshqIbKfjph9D()J12PEwDsDY7)MzmmpVhVqIPF5TwGk0jCzxHMXZvRkh1TFFfvt(O5OCmiyFolxh1YTJVR3cmNNs4dZ7nKjOHI7HluAEMp9e9bccstJkSVo9c9CjX0qjcBXEBpLgj1B4P4f5eXpTBUMk7JW0JAsiG8JoKIoUzHePoAF(qQ0UCpkHHoQN5luhbWEmJUjpoEcHhyHjmQplNPsw1bEPxDIwYIJPsvNnKlx((7FwHI(cjVqeGHprNibpRBE6OKZufr0b0C9(sAF2jE923TD75G2bAia0mrYmcet977psqLV0T9(7CqBhnSXdbo3wNBuTsJwPiLk5uZXkbnnLrun826h)(T32lhLrvnMUBEovoaYoEwtg9skkvN4uaUDKifnIkxKH04eQQxcFy38tv2xnHK3a6udWvavU(eRf2LavlWb6aNEvK0d8f2jZdA1SNFqp)ME(NH5zrSC6EvGpZaBBi)Q0ZmoELXk3WelUNaLQEvGhofsvvzWvNtyQ3wKB9KTqPPIpfzx7xjFpoH(336CMPEMJsFnK(H69WZpMsfnbFfR9qqhqYufnTVTFQ8oNP0m8XJEoewMMJKzqa4rJn9jF3ALnwaBJq4JJLMI87FO4HAOjlW(xFUesubIanlJUCxTPxk)rpwi(IRr7ymjaJu6qXNFnsRwiFrRN7dOk(QBYCcjfZmH3kNzLEzi508a)UI7BpegP4W3WWhYiqjUjS98kSyNqj2dF3IQXR3unUvt813KftPXi8OG(PCUm8uRcVfg7y9hvENzsUg6OmdGoD62XvCVkNkbbtFT4PC5RQvR2kxB2ZMpsqqxzA41ADcePzO0piKlBiH6IrlrJBar4jCM9yS18Ra)MUuTCT4E7izJx)xkqeOUJw33xS(nf3zCsaOeqZu)dcQFDz(Qkrma8ROuA4c7UHCj5qjsm5WLlwCPHTdWDpWV9UxMK(a6Tt3TthxVaNU((D37A9itOLWi0GXujp5)5rxubVYy9yJPpw8T3uGrgbdYmCaqerHHXuYOL9cxeBrjuwCI(DoPCe5FLAukmyV1AEzfaN0QtnKo5WWUmjQs0AL4vNyovYHCHh2qfTrKILhNsD2RBNFUeVwjl0rb(Lr3zegqsGb0gz26ae02ZnKXMHrZ6PIbIRq3XG8gLjrV0TzBxpJUa6gkvRuZmUfGX8CkWlD7zs7OSjR7yUSrEYYqBYf3meA4um0E7cIFWTVVOSiCkkNLzPd2U8J3PSHtoa3cYskIadVRurb9jQtPifTNwsZJ1j3DIzNXyLJDYqS8xx2OCC5Fcp)w5Vhb9VGPJIaMemT8pUB5NSJvoiZSdulcWSplEvrDil2APhcSAEM2pVH25vXNDHRBM2EotHGgpsOJzwh6454bv0EpO2Fn7rms56EOurcAL59Labn4Qq)(kNxvO3XCKXFJ61YZ1TZwfmY8N8M3(m9lsYE9tEfKCnOrt8UAiYzmNNT)kpDZNnZKbyvxxpNLx1Cb72yoSetDnxdOcfpGfNZL0LxSBp1vk5sviCPMcPnPvAsDL3pS5wB(06d(N38F

**Comment by InfusOnWoW** [comment]
Will befixed in the next release, soon.
