### ISSUE TITLE
Update 5.2.1 has messed up all 'texture' weakauras

### ISSUE THREAD

**Issue by UnaffiliatedGamer** [WeakAuras/WeakAuras2#4070]
### Description

Updated to 5.2.1 today and now anything with a texture has been moved, resized and incorrectly cropped. Downgrading back to 5.2.0 resolves the issue, but I am now unable to manage my weakauras because it is detecting an old version.

### WeakAuras Version

5.2.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Use any kind of texture weakaura.

### Last Good Version

5.2.0

**Comment by InfusOnWoW** [comment]
The reproduction steps are severly lacking.

**Comment by UnaffiliatedGamer** [comment]
Identified the problem now that I have reinstalled new version and messed about with some settings. New option 'Legacy Zoom Out' is automatically ticked, which changed the appearance of all texture weakauras (I use a lot so it created a whole mess). Non-issue. Thanks.
