### ISSUE TITLE
Non-backwards compatible change to rotation + mirror texture

### ISSUE THREAD

**Issue by Road-block** [WeakAuras/WeakAuras2#4073]
### Description

Previous versions behavior

Use a ⬆️ texture.
Rotate it 90 ⬅️
Check mirror ➡️ (this is now flipped along the screen x/y axis)
The coordinate transform is done relative to the screen/parent.

5.2.1
Use a ⬆️ texture
Rotate it 90 ⬅️
Check mirror ⬅️ (this is now flipped along the arrow x/y axis)
The coordinate transform is done relative to the new texture orientation.

This breaks auras that used the previous implementation to reuse graphics.
Example: https://wago.io/2fw7mfRGm

Minimal aura to test the behavior.
```
!WA:2!DjvWUnnqquQ6bqwvGiQ0d0diXbexiqlqrC0o1rnqst0gtlGIu1yVJTxv7DT2DDAdhJQqCoFc5mNIe3r8fyfXxaFc5lGDDI4a(G3zM9nZ7TZmB1UrEdAd63E0knETUuINlHIEckwSBRUU9ge03RRBR37E8XDc6CM)CTiAmkvmb)oJ)5cgpwiZbTX1rED)4yfQ3ArSeYXHAjOHTdZzsPqMkNS525smXapysbk3qjjsKjKVBBZ3SWmKtT8t866F6XlaEuQqoqW46Ww(Ng4twcLAtO(fwwvoRwJOTLtBrdh2I47FQeIQV)iIsdsTtymJZuPoEMdTZuTKLKyEh39jYnMFDofdlJJRf2j(Dh0(dD90ghcukHdNQkWSSouLZFuLH4yKRhAqZUEXfTChgCXWaxsGxPP4HfzWeus4gbPCi1qdpbHmD6)sDGenPsgoWVB3zL8nsWP4(wvpgdw7BBdF)wvofVPdxJYyich5sPMx1OZr4sxJUuJgiUcL1M9qkdgToQ9)lF1kMnpoKD26r2KLzycen5ZcrEFtxCgWzRNEhvTB7FHGYo2qEIo92v77XfCCj1ujlIlS9cPcJeCQAQfQTtv10lhy82vpZKqvZQNx9IQdmNp4)J8ygDEV6vHauPpSKrxqE7zF6Qop1VtpcbYksHTnJafOTeIPtLcDnX)i0qzmlXzMcZIR3eQU3CtNKuViPE4Ev7V04gcrxMifLCAykYss13SZCRyzR3t8YeaTDOgmly69i5LzAMJNzQgTxLRdjkdukRLNI9fSo0vmQo9MDAOiVU5HnpOX4F)X)c
```

### WeakAuras Version

5.2.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No Lua errors, this is an implementation change that breaks backwards compatibility.

### Reproduction Steps

Use a previous 5.x version.
Test the example aura by rotating 90 + mirror
Use the 5.2.1 version.
Test the example aura by rotating 90 + mirror

Observe difference.

**Comment by InfusOnWoW** [comment]
Indeed you are correct, I missed that when I implemented the change. We won't revert the change.

**Comment by InfusOnWoW** [comment]
More related issues have come to light that are due to the same underlying change, I'll have to take a deeper look.

**Comment by MGraefe** [comment]
This destroyed our wrath immortal run today. At Thaddius people where running into the wrong direction because the arrow of their trusted weakaura pointed in the opposite direction :D
