### ISSUE TITLE
Resize of texture - incorrect behaviour

### ISSUE THREAD

**Issue by Salienne** [WeakAuras/WeakAuras2#4077]
### Description

WHY: I expect behavior of texture resizing - if I put bigger X-ray - it will be <------>  But it work oppositely. When I move ray-X it move to high.
HOW: I think there is opposite ray-X is behaviors as Y and Y as X.
WHAT: I would like when I move X then <-----> and when Y than top.

OK: 
![image](https://user-images.githubusercontent.com/53642762/204396825-01eda8a4-d13e-41b4-9691-a283a6b9dcb7.png)

BAD:
![image](https://user-images.githubusercontent.com/53642762/204396850-bb30d4b6-a76f-45ef-921c-c0dc555e9e72.png)

I used newest version.

### WeakAuras Version

WeakAura 5.2.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. go to WA options
2. resize texture by mouse

### Last Good Version

26.11.22 was OK

### Screenshots

OK: 
![image](https://user-images.githubusercontent.com/53642762/204397150-84dfffec-4787-42ba-bac8-ddac72a090c6.png)

BAD with No change:
![image](https://user-images.githubusercontent.com/53642762/204397183-87d8ac4d-e7d8-446f-8f70-e31d1972672b.png)

**Comment by mrbuds** [comment]
You didn't include the aura

**Comment by Salienne** [comment]
[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/10108163/SavedVariables.zip)
