### ISSUE TITLE
WoTLK bar background color blending with foreground color

### ISSUE THREAD

**Issue by OnceWasPerfect** [WeakAuras/WeakAuras2#4078]
### Description

The background color of a bar is being blended with the foreground bar color.  If you use a darkened background it is making the bar colors darker.  This did not happen on version  5.2.0-23.  See screenshots both with the same background color.  

Version 5.2.0-23
![image](https://user-images.githubusercontent.com/53492647/204404628-6abc2776-6c61-49ca-8e44-5a9f37f02816.png)

Version 5.2.2
![image](https://user-images.githubusercontent.com/53492647/204404813-8dd947c8-e90f-4b87-8e4d-4481eab03bf0.png)

### WeakAuras Version

5.2.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

None

### Reproduction Steps

1.  Make a bar with a darker background
2. Adjust the background color and notice the foreground color changes

### Last Good Version

5.2.0-23

**Comment by mrbuds** [comment]
You didn't include an export string so we can't investigate, but you most probably have your background set in front of the foreground subelement

**Comment by Shragenator** [comment]
Having same issue when I updated.   Foreground is the incorrect color. 

`!WA:2!9z1tVTXnw8iOaKfcBaCKtnqck2QTyBrcwKGe5nglkWcdjf5iNil5sn(pjnTsCgsPHnJijiNX2k9un6HCQh0hbDEpPJ7PaV9ypqOuK0EQa(s7Tc4VaPpYzKDAlsjGht(E8947p)EVNYTwXHfjfjp7JMOLy1t2HrIdFNjSabVJirfqF3ZnwtJ6VPGXJ9RvVLxDKAu7(9104gpNF9)3p(6x)6PyEqOq5UJ58ZceIiIyFEN9zsAVzo9IeX4yMGNtEPFZ5neeA1kB51(O5svNmG2tHdSC1RG0Xyv8stiIUdPAnEanSkJZIl43h(NoSWHXk2GbuL(R)qv22xwnEKKIWjkC5ts006haARJKgfTojubprBE0OEi6EuWLAqXrXHhRt8DN3ur7Zoa1zZ6nBwnbEiF49hqJp9cDs6dxyA3Av641TJxfK3H6uvRlG4yWilCK9LDeze9vrRS8Dw5wJT0CSV6X1suAAjr)svgi4JuGf2cy0BcH6dk3dSDvJkOnwBRMJt4z(uHPeM(Zt4qyzpAzmFKSyqIowm0lLFtXawG8F23Ddb)AzID9cLkvsrJtu8szK(KB)PfOCsb5LWoLLPaBI4)EoxIVBGisOUFEyDcKrPkooABicd69lo5juQSc4CbXiBcS3ymNn0LkxXCXTnlwLl40dPyn16iMYZiGJBz31MuahhEaI2xQOacAQgcruFrm4ihzLPtSIYhehEHQdXmoOotzZYWF)lZDmRmbhjdXBMePPM)9fmlSMJnSZYfUv5egzABTQZTUnvVfo6W5qQEh6Jv1CovJv)5dCRgR(nx2TAS6)Fr76DYdjano2AU0quq21FPB9QgR(tVYU((gR(lVNBL)ihqoTu4H5MaaeeDGf0(OLmlodo2xOOduIeojJGpo4jPeE2vLfJPhe3vhIblC3uTKtEfhr3hqAiU2vNTXuE8P8qoGJCH3qdPExUC5YFCk151SMcYfDuWjqqgYebUs8QvGJNK(qSdOehXVCwAH8dZmNJC8)CaNX6pYC(jkBrl1diwTv7w1L)J)G1k7gZgs7grhGdg1TFKqOcnlQaF3El51FBcqgb1gSGUXHaUieYAJM4U1ziXXzsXJLlSMI90sFCcMaPkCjpp5F)TPxaMfWSa38)M49Chuw6Tj4qbPRfi0BMJ5(cfzhfwE4ozBsdn7b62pIgMLkEJ2GYfwVvR6OUvB751EJM1xZt(3EBVv6PCZo1dDTaAVLxZ1Bv)mQDypLELSm0FcGrMTbz1na0m7M3SguNCV3)dKM1DqeZ9nfmpW00SXxAqHM2MZB208XgQPpur1XqYz2YfZnBB2XupN5H5mFApZNyESbB8nFM8sVPVHw)En8m9YzEuptWvmEJmTYT3mFiorvDfPM58JPgFzOACAgfn4u5pk7qw2UXQZk6wnw1vZ9QFi)Xz3yEaFU4uyyH62L2eGWrMfhBRXCmKloqHjmOFDBL9RRd0KgTrR)O2T8Q0uE559gSO57Y0yqRKWQrcmz7Xqh5UbryTUh09pceFj0WKOy2sVOhYr)d91m(GiQANkOMTR9aZ(fQA7jUKBd4s2nh76pufKNyBUwUYDVRCbq1vi2kkkHs2aFamndAig6RDdB9zdLcvSpqQpBqbKRHxE0(2IZV6VklcsxlZUbvIS4ZFVkz8WjkxFihkYo2XgUD2sdgHq5Ow13Uo6KZAgDAVJnZFRBENXUraAOVmYLAvhKI1(2loLXtHwGYxAkSnGw3osu3lt9u2GW4)JYIgtuuuTikMN2L0lLK8ARBNN0hhqFCnm0wHpOkw94Tw)gND6gDCHTNkedBS6lwE5sN7C5qoLeojweSx6GO)YEp)9zetJzqBnas1w6(5cfM2xbJsHPiqJH8NKc3wZsYgm87udvVEl)qND(EP)GNAN2HrX4wLtdFZg77MBQ4meKrnXo(IL(yJNpvPmip04LYTOO7Lb8clQr35MlFZLlU33T7V(`

**Comment by InfusOnWoW** [comment]
@Shragenator it's exactly what mrbuds already posted.

**Comment by Shragenator** [comment]
Oh i see, you can reorder the subelements, thanks.  Ignore my post
