### ISSUE TITLE
When you rotate (rectangular)square textures with borders they misalign.

### ISSUE THREAD

**Issue by Hera4** [WeakAuras/WeakAuras2#4079]
### Description

The border to also rotate.

The border does not rotate like it used to.

https://wago.io/QAKH7H2Jk

### WeakAuras Version

Weak Aura's 2.2? Updated 1hr before DF launch

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No

### Reproduction Steps

Make a rectangle and rotate it with a border. 

### Last Good Version

Weak Auras 2.1? Two updates ago 100% fine. 

### Screenshots

![sq](https://user-images.githubusercontent.com/119376377/204415183-a052803c-c6d8-4002-87c7-a00d80aa44bd.png)

### Export String

!WA:2!9s1sVnXrCC7ULsZwkKKcbk0QAEiAvf1jXIeOPpaVj2yNyhBwBianQoZU7S7okR3DzMzdXCPvrvioIYxGk5Z9qLpWHEkLB92Fzr)cG612d8fiDgVBGYJ(qQah8655Vz(94)K2E02JAnktFQS5YMBuRBFuANA22mmpnDnmLrc8v6r8TdOTrCrh1hI8nDdOfPO24MDcXgnMvVqHf3e5tIxX0ATre)IACXKA(b(4(wr0bZ0soeLHnd8TyBGrSbaaQ3t2SbNI9D4U7wNXruEryiqfElypWBl(FV72WM4tyUp9W5Iiw9UETkNU(8luvVUtUiQx4rC58q2mJp(nqobzjbJFX8lu6mLYn)QJpjD9e211iGAHPfSCWHJ046rikotXipVml5s4ydgUTG(6tMDISt0LfzOJDemGPsrMsQWMwtCF4QW(uHHv7YdmteRdL(wDtGUb5M4DDmIv4btGVjEDEK4FTiNmCmJ33azUQfniC2aVa68kkk1vMi7upK4ZXuFK3LJHSJrmEU9IL(6bIfymBHfBwq)EXtfZPH6zlDfHsI4iLUszMm4YQAiABtCuFq8Y1so3WH18i38MiQvMMbbECsyV4fu2xaNsFuexCE1cJbrZlazv0GJ8W(8X0Bhj2GQUPhIXgdgxvJj4BCJqSPSrcyXSlD60kBWPehhbRo8j3mYpPJknPXT2qSrpVYwmvyiDKi0KtlsiYgHEOocVaVM4CnkHrEC3UwyJiBBz(HwQqL6fVuLhiCPblPHycY69AnB(gnB1OzE9MpAQ6uSyk9g1luPIUVqRyQDPdCwjs6o0GOqDMPGHkBYWE2dKA4egYGu5528r5Orx7(xzuZ5V9XHxR05Dw5UFZ2BFFXvIH4YOo2fEDvyokp2VHDpn8MpDWf23ZmYWpZiJ0BHInMCPP0kunxz4DG9B0MqPbux4aL2A1vUBQuP(r4qW7ch(JhdgQVGLYeLKf(w2jrJwMXHR0Lo3w35oF)2B3xjXxAHfzF4GWqBk34GHsYhTwJWigE4v6N0piUMzNnkD6DbhzA49skaG3xM7HsqzDZDYYkWr7OJ8cDrkBkWY3QAGfwxRsHfNt)gelU73Th4JuHtQy4IjoUCr3DbVb8HQpmr3wIIcL7jC)ZwjF16nRPvj)SlKFU5k3S8LlilSoqsHvE5PK5cuKfryYWcHALLLq2it8Y5TSQ5ZwEjmA18cZHTCvSfbTCsTiB5yiAnaIDqil3bbNsf(KIqwzqgMyW3jh8nN8BFpSdYSZ1ccAxtuKaNEVNeMsfM(wWzeHx4SWNcZaFg85WxaFjCo48qEqdMvnCe5ZhRHBgN4LS7hsbhhobCbXpfLnOb8bpvMEq0AR8B8RcpEky(4efSW)NS0erb34QALNVJ36YSeunogDXr(2uPo1JJrWI2qTNiVa1LPe4IG(kqJ0qZ)gRhU0o2oCzfyj4kWv)LyhgU2Jmx4RGLLw3h8CTUm6ytoY3XdlO6x)pBbqR)ZYoSYtOYakrE1(JF)fN8gwWDD6zR6Au)QpwEp)mJTL4is9QwEp1)I8Mj3zMiJEsy7LRw)Bd)ept(cklJ8TlPL3UgI8xe7P)z22BV9p9YrS355QNJAFSNVA)QuJLx6)8p

**Comment by AmenitradieDruidin** [comment]
Yes, have the same problem. :(
