### ISSUE TITLE
The progress bar material animation cannot be rotated

### ISSUE THREAD

**Issue by kaien617** [WeakAuras/WeakAuras2#4083]
### Description

In the animation settings, it was previously possible to change the progress bar material into a rotation
invalid now

### WeakAuras Version

WeakAuras-5.2.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

no error occurred

### Reproduction Steps

no error occurred

### Last Good Version

WeakAuras-5.2.1

### Export String

!WA:2!9z13pUXrD8yCpvj3kDBSYz1uXdgt0PKYXPCU3fkpevT(h3DoXNTzTV2kLG8m7UJ9o9wp7YmJDSdkQTMa6ajeutFdHaS6d9bepyDVWdOkfvXtGy5iiEKQJ2cvcjKoXFa8DM13Drjbg5173z2VFNVFMV)CsSz6EPDt7U)x3UVGWBpkr87Hj4dR3PJGi)9xKpkM6FL64obCsxEqFMBXa)a(n2(v)3)Tp(CWai(WpurLmz4fCjcSSphljfWo7fZV3mbUhPfzi8bcIl8XmjX17rzEZt3CVXsoTBxcxuBz(CY9tFeGS2cVG7yAlc42i9CS)DWJesEFY856VTtGlbDyxcJWPonbrQZEGq)Y0rshqos03MmGWKn4Ko0HwnBuUA1zo9fYGET9OUeljThXTGCuiPqFgvgM(SnFBc2xRGt3LM97a7YS2fnB2QDZwMwTS0RRzvchYtqEfMtqpkRRADKfdSiIuJfHeF)kUaLInL2q8(m9gua3xgm2vzEObS0RfLXo0hpIWN6sSbL2cWhF7YvBS5UvN0Nn3uLjkt0xEMlv8M9z6JBEmBu45XA6wX8Ooa)QZnMWCnzD9j3pZXuWHWzy)xdm7GYgXv8hWexZsiXCzMjUbTJTqEfOaixoAvKD8cH)DmaX2e2GvvWVOpwiYE9ScIpXrE58RS7jlE5CXWp3vUsQtfPOJkwsjW3(EPODYwry66wNvna7sCVCUVKwsD8Mi3vYIzUzlUBZw13PDXQMnB2Uy9Q1TAMv6ryPYcJNY((u4pfXxq(FXVLzLspg3mx7oWPw4LjAvVjygTN2LCTOV6MrlvGfWihEIBQTkQHliobmxXdiybPPKtyDLEp7y1mLtlA9c9Wu2(x0wRuRKtv(EEGeYdqr5YDTRob7h6Hv8ogcVX0UEYyElKm(9wjJzztWjhEZoAxDa7YH8GUCIqSswTBBLSUeFj(k6JkNazAS4pK9RK9uEZ(sNWfCotnnggAyE9jXjzGE8MVUsFrMrlfD1OV2Zg9krRBlCW(Krj1SQHgYslrIj6z6n6QPhLi9WeXq3mPDiOxImmt8EweY6HOVI(bo7DhQGelOstdt8CpLJgFTvY2fESHhm8WZdZHhB4bNp(WcrspLOsv4Zt4Xpn2rnamG9Z6CAqhep84cCRNCJ)MpM88v6UIni6z7ZQ8vEKjDF0j2Nk8CpKw6vwtVSYLOEud7yZ19ZeBZhMmAJORfLhcbJwxto3J4WdcBpSrYRU66Jdgq4qsN4LUrsOk9BPhB)Q)v94VOyzJBO(pV6Vx5uQnosiPo7nQ08GAVXAvdujk0jGjdn2KtVB2VrFSlWaoBRw8bXfowykuw0I0vv74fZeT0HWu7t7dy7ruHYh88ZWmhVaEJaOUJDXY1Av2kg2J0W(bktS1jQm0aITmDFtOAdbkkSdEO3yfkAsVl5IhF2UFsxPp2qnw6jjsmvh8RR5L44yiSjx1zccsTBw0QC5ArBL0UhLZd4EpUEPmVckq24zaiUwbFOe1(P5qbDq7HzS613xstPZdu1V5EwAN8Y2cQsH8gMvnlvPwe93nRuzZwBFZAv2A7wi(RBAzvPUfkQhQWoMBvgz3WQs5MTq2n32ChZAAoQwV4nrGC7uV227Qmxi75VTkzTBLsGO1RDtKLv9T2TmkozuPDVcqLCsMiAQccWCPi4si4HjZROpsZuBiVOn0iYz5i)7Ber3F57Ho4wO3c9(lIoyr0hb)Uf6HlI(oO)ZIOVl6cgOlzGw3avYa1Ya5c)Fj09nqVNb69nqhyG(id0dnqFIb6hI(dOFe6pIEx0Fc9tqFYIO)m6cxc9mgO3bjnq2XajgCXAFHiAMfqtDPqlvhWEosd47cfyHwKFHdvhRqI0glL(ep90bepQJpzxkCsd8JpGyvdzIqt3jUrMIEs4GWZu5eBGYv1j0Qq1Y1kzPVvsIXqpAv5jH3e9ckgSRuRzLsLdp)z3aA(DzcVqfvPlqjKB3S4Tl9Y3(Br7V(eO3xhDSD0Tos0liq61yE1l0uUo5qfXD8jL0KXB2XZF)6CCOgxqtODAmvg4mp56fs89MMJ6gM(F8E)8p9D)TF2p7h)pp4d(0FWh8zV97eE(ZYd()HTxEwhvap0tcYBxW6ouxP3bp)HWnnGCH6H6E(VyNOLSLbDvbTGjUer44LFpYii0x991kOU6Y4p)T)(F(V83KDnUlPdgCvEr)0K57tDNnQv1H5jM9EJneqYHc6epOYpRdTBMOFH3SaofCb6u7XVwzRwvkAwDQQDjnw7lB54rC2BZON7lEUXdWCkg8uJPQlpbo(CbH5U(1TgG97tsYD8WSUeqMOF9nsMirYXGjfA)khfTWmkdCxXnQxEgq6qkRUvLaf(c0UmWto)4QxTSkJh(KXzMX479UqAH1gRMF18Ph8W34)(

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
