### ISSUE TITLE
[Feature Request] Only show Loaded Auras in WA Options

### ISSUE THREAD

**Issue by mohcow** [WeakAuras/WeakAuras2#4084]
**Is your feature request related to a problem? Please describe.**
No, it is not.

**Describe the solution you'd like**
Add an option to just show loaded Auras in WA Options.

**Describe alternatives you've considered**
there are none.
**Additional context**
Context to why: A lot of WA packs are displaying auras based on how are they ordered in the group "folder". If you have auras for multiple specs/ that are not loaded it gets insanely tedious to check why ones are loaded and not.

**Comment by InfusOnWoW** [comment]
There's an icon on each aura on the left side that shows whether an aura is loaded or not. And usually authors are somewhat reasonable in e.g. using groups to distinguish between specs. 

Thus I don't really see the need for additional filtering options for that use case.

**Comment by mohcow** [comment]
All good points, sadly the icon you speak of disappears when you try to sort via drag and drop(more tedium having to use the little arrows). And as an experiment regarding your 2nd argument i went to wago and took the first most popular warlock  WA pack there is (Afenar's) and it has the same structure i talked about. Most active ability are in "Core Group" and sorted by position in group.

But since it's your time and effort, therefore i can just hope that this feature will make it someday. thanks for your hard work regardless.
