### ISSUE TITLE
Convoke CD not triggering weakaura

### ISSUE THREAD

**Issue by NinTanDao64** [WeakAuras/WeakAuras2#4085]
### Description

I have a handful of weakauras to track cooldowns of various abilities, but any of them that track Convoke the Spirits don't trigger the cooldown animation/timers
It's the only ability for which this occurs

### WeakAuras Version

5.2.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1) Import the weakaura string linked below
2) The weakaura is set to load only while in Balance spec on a Druid
3) Cast Convoke the Spirits and the icon won't reflect the fact that it's on CD

### Last Good Version

Whichever version was latest before the expansion launched

### Export String

!WA:2!vvvZUTXrs4ith4yfaVwu2cYlcqemq0k5dcXkBmG9nouuXkqwuyiLL3adWP5mfNPTg2DNU7HuuE38dpeOZe5As8Yd5bGpc6UbAqeKha9iOB5wQUNHYw6Gy1vvD1v9vv9nZTD5ULJkhD6)AmnKZAWZKHWN8bYb170rb65MqyHjC5(Ckt3UAT9AwZFAiNNgX7ZA0NkGaXTdZuAE3MWX6deren0oZ9ZzZ8RwumK4zdFWqTKghds1TwvwiE6sdJYKenLZk)WPXadK0Wgj8(1zJv4pvs7tgO8YyuDBnrgd6rkbKMUhPlS8h(xjxKPGwAjj8OWeR5KXryg0PtZbcq(0A7U)2hSRpdDw9GZ8HxL1dyUhBOpel591jtTbqcDjugLfNCUkRnGoP3xcDOh73y)A7U7LkBGrME8KwvR0OzRgnR43CS96kx(giZyoV8izAUVtuCVQfWWk7l5XsqPwzTg2cyDXI2Rchtc1TUSKsMkbsAJzhflwLZ6XpcwrNaR0qqLuTYLXxEJGHoXDIuZlwWA5kyyGNgbcFNldTwTazWOlbTGj5TVwj0iWxt7crJYyf9MvBNxyMBzw4JE6qXcyQs7bnZT(mEeu6cCWaKms6ZXUkcRdU4iaevW3lu7Bb6KrkiTJBaYCDS3OiAB7g7tiMI9a8oQNSKzTP4X2ycHnLmw0P3ruwJtuiYsqW7ffJJI75u6(xhUSlbDOqWJXzWOlnF)ptjU97fHQ8uU8RNBU5kDEU2zjLxLdAwxSOtPTTHHIgEinsN4vbpEr(BrpgICk)XP5Be)NIm6mN9xHyiTZaSaLCnwC2LbV9QVxnZAsSUS(m25yOlnkH)nQOiWrK7wjmerFMMKIdjGYkho4kaWSNBQtxFUm6qjrm8WcHPxgm3yF9dAU7o7vRaaEVv4rOLA(TAwF)3DJg0tGhwuvV4kvvpQI2ofc(ZPXP8(BlHVnZMy7F9pFJn)Y8kZA4mCy6RslG4KHwv2SyA7mTMZQ3dKPKbJTQ3fyX6K7oXkpRIgfp7QoyXzBwA4zpK4E9Mj0WJy42ZnDxOrijfk5e3LIQxWfFpeoazs7eGgNObVuoj60BlpbNmW1JRjX9BC6sSKF3SunD(ZdtjkfIpr2TPqCAhDifERbw6Tbiztk2swYaZlkBxxUQZbEURyIlHEFZaFNv8O)w(hSZw4L8WTlWE7XruKZieFXbl50ZtD6hj6jE3Bi7y3T4mR8WI97W89uxOdK5(UPlgkSN5IT0TazHBZnViVhUTejfSAA3OQFTA7nIWODDuEpYxHmO6NBwRTahZa9qGOCUAE80zKWTS8fsfG01rkZR96qIGZS(1qlDTVB4zPk328)mFNznZJn)Wnm)xZJB3bPpvjySnV2E2z(1MVhnpC2hccMervcCyyhm4lFT)X1MIlCygxxyFy18(VB7yZmA0K1x3FZ170BNVP9bUwWmMuK4bPwGaVt48UZz(0GXAEyVC(NLN7NgFFA04z0Mv3AshlGGzprtk5tsfj4p9T7YGmhZvpYCY2YiEl34MBcSvUfpl)3i0sojzIBkRLlGIfpeihvbrn1tWVe2r3fyrMHZ7H4a2r)5K2yr2Hgppo1zZni4CKJi8ObBva0jI7mdyS0fBrveCzlkzSf5PU86bR6hMaHh9iZhxAypIKA9ymNndi87rsZG5K4x(yX4h4w18MGHcjhBG6bw(1n(InSzmQF7XklVQR76Tp2d8DNLRKxzfwfeDIyLDSu648i8YQoJnS2uV8zal7HB0v8ftZD2(QmiT9Zik0FZyZVVQ5xSPQ5xn)M5nLm)))PnHqd)7juwolnwvRobfdHA2VoQceltJzCjumd40wtk5sCI)4cAGYk)VCJn3yZY9(Jx83)

**Comment by InfusOnWoW** [comment]
There are now two Convoke the Spirits spells. You need to enable the "exact spell id" setting and use the correct spell id.
