### ISSUE TITLE
Cooldown trigger doesn't always work for empowered spells

### ISSUE THREAD

**Issue by leandervr** [WeakAuras/WeakAuras2#4088]
### Description

I have two simple weakaura icons to track the cooldown for Spiritbloom and Dream Breath. Most of the time they work fine, but if I change specs from devastation to preservation evoker often these weakarauras refuse to load and only do so after reloading the UI (sometimes it takes multiple reloads). I've remade the weakaura several times and the problem keeps occuring. Its' an extremely simple weakaura with just an ability cooldown trigger for an icon. 

### WeakAuras Version

WA 5.2.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

No errors, it just doesn't do anything. 

### Reproduction Steps

make a new icon WA
make a trigger for dream breath or spiritbloom to trigger on cooldown

using spiritbloom/dream breath should make this icon pop up, but it does not happen

### Export String

!WA:2!DrvZUTTrq4i4g0cAGIy1uJyGEWifTOfgWOqajaT3mvLsCHIKkj9p9qR0sYrKBm1US7UuYY3IouKZ6rqN7j9i4NacII27(qFa8tqNDjPRD0bQzN)(Mz2VzB0T50MHndF)xUMgWzU8mra8fpsC5GjtKGQHyrLWgcliMlgYPmLF7o9964ueW5jH85m350uy811h7egbX260nEPsqJIaH8t)ArL4)ARwKcoYuij5gzMpmdyk3SjtOxUzu7JC9g56DKJ36qWhv6H(kEDNEd7EsV0DYKWOiGbcAGBmF(a2yht4P71Uc79hk4rcqk3)BC1i8T3bXqbGq44oStVEfcGKyS3Nmf24MsfuLFcNpTqdHS2Y4LgXJdLwfpa3BKM)Qr1oJHXNMqwachggO0ALorkbj4IXRUlFp7X)Z2RYyvtcR0Dibk6mWR88B4HWF(OBXbmiyKKtXXgLZwC7faKEeMJaLdrr5XRKqYeZfr(JXXKKOYeefeVgBvhicJr(d7MVDbE0hXpsWZyHV)PPnvWLQrYycwYNxDTMUNrP5ZeUykbDOsWMXzWQ7m)8VsM(K7LH28eU4NA0OXw3uQTUOSp6eVbPFMrjjtXXurdoJgQITpcpEBjw0lHqJY3vuYS(LQk6AJ93Mjv0jlWguWvyZ5HkT7pOFN8TfyFP9zTXXatzSf(BvvtG0HN0vqVA)FoJeIdgY(EEpO3RrQWOBoxeEMGKU8SkHYcygvs9tGXv989y)P7CC)(DCgzpWZBWBCo(vV2R4oODPxb7v1rN)aC0wnS5bN4174(D(7IOe(8Uc43ZawWIHF03DyRxu2DAdB0FQZWs9bDWf(zkfNnygiqY2AT6Ealsf)5g)R7Sv6dTVBYCnYfFvTMyBTXyd6EX0Gly42YwMiCdijqPypkQEhda24CbeX(Xankw9o7eojSRVcDLP21zAwIIAzRPN7MFQLtqcrk1s2sCuOfwlmCsD5N)jPpT(vc9n6psLeCihgVIWOAEcN9shPIiuDVgisWvjmD3hNVD(bfHAAo6Yi9dicjGpWekxQ9ZK7dSNsOSU5)MX78r5JZj5h4pHYOY4pu9gkRKLJ5ZYzUHiAFf(aqdHENexHEz(VALhyzJHRSwR4bZk3hFwJ)y9ZPHf37rJ9B58)0Wnte4Mow5iZBRBlzcD1Q0fPVBBNoD63kJgU5e4TN3AW3FQhDQp2ktOrwcktJceN2eVYQFDbFxax8HXoKK0yYwR19n1uJwlRNMJlWvnePbPLgAkDEXHToSvZz)15)3

**Comment by mrbuds** [comment]
It's a known bug on blizzard's side, happen when switching spec with the max empowerement level talent on preservation spec.
Log-off => Log-in fix it, but we can't do anything on our side.
