### ISSUE TITLE
Mirroring broken when using rotation

### ISSUE THREAD

**Issue by twhit027** [WeakAuras/WeakAuras2#4092]
### Description

Using the **mirror** option _(I have only tested this with textures)_ has historically inverted the aura across the screen's Y-axis.

With recent releases, this is no longer the case. Adding mirroring to a rotated aura uses the aura's new 0-degree point instead of the screen's.

If this is intended, new behavior, I would like to point out that this makes it difficult to create HUD-style auras where a texture is mirrored across both sides of your character.

### WeakAuras Version

WealAuras 2.2.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create a texture aura and mirror it (Y-axis is the same as the screen, so the mirroring appears correctly).
2. Add rotation to the texture (the mirroring occurs against the new Y-axis of the texture).

### Last Good Version

N/A - was working during Dragonflight pre-release

### Screenshots

![rotation_bug_screenshot](https://user-images.githubusercontent.com/2110532/205443867-49b0ce73-b1e1-4d7c-98de-0cde266e12f1.png)

### Export String

!WA:2!fw16UnXXxCSS4sxU0KqBkbOflQAkxuPL0KaiuRKxFryQtSZ6nxasRZS7mR3bwVZYSZgJtR6fleIpNhb)z(KFeYtWrr9jipc8e8)m7AqrW)O(Lzp7SZLZ53LZMBTPITw4wZDR5MQ7u0POV(73LiDRZc7O8F50h4iKuM0K4(mQuefnHzaFNDisAbBHiqXJKVOHNxmtLt2FCWisORVq2uWdvoLQSSDfRHEjbbL4s3a2wwXrex2XLexfxegVOvSIivgoE8qESVHj(qzmqj5D6WKXxCw54WxnKYCs88S7hXKpOs9MvxTUPcFXIKijZnioIfeuJgBCqCIdBBwOQfUA(lg1UuXw2TBzx0Y2mbpCNOasFM0kK0LfByLUuNhWibk)3V1MsgUvRwnRuV(UjHJtbJrUIGKUHT0vqEhjHYtIF5zgKeZQZ7Yv(wKaENq4usSM0Bi3q8aTyD0fQHzGGqR6Oib4fmTv3ee(mmX02DA4AgwUbK4yDKzmFhMoyGu0l7Q23zm(xseiKpmF(8nZ)d3AbjjK3LOy(wXU4PMFOlEYmPgHUADlNmQZFy2Zk0oSOjB98eIKvOkYhfw3NRydLPPNEp7r7Jyc3TJuKenExTWC54MXcPYmueYMlHthrFO121nLeV5xz3ywGxktpNDJMycRiAwn3B56ejKeSgYH4e9pWfHafjuvf5DH0XQy5AR2AFsIcLknIsLcg7LDNz6OpXb3IhVJXqLWD7SJ5c5E1WRYPrtAn(IkyM0PqzwxXipjsNTusIIKF3osoDDov5F63MjgRQ)QUgDAvYQsLLhOxrkozvEu2TwleV08wbAI80Mig0ZSCJ1xE8xZa(C5YHGSiKYZs4r8qpHSBAQySBgBGHlcNP6EmsSoFs9rNeopC39POov)52AvRmMPpO4b61PZe4UMDj8WQqR0vd2WQWA4ZZ(HZmL7nE9TrksfWdrWAv761wUcu0yeLhRL22SxOIMzzr431LlLcjJw4APedgm)cxF)yFcv07rzO8LpgCs4urfo0EBNvsTJAR4DzJFlx0eUjXkrx9kwnIINgCPdq6tOlz3uW2Si(kCAS6nGZAaNZa(0ZnlmXRGjHPWc4ZGp3aMg(c4cWmWfnGlbxg(s4RGRyenPUzW2m7mB2sck7nhl6s)FZPSalDQrJM9Ot7awhIB)2EbcH0hUVJzdB7glH9qIjknpW8HF6jMEIqv0evL8DkSscHQvpfSTHV5ItdNFF07Q9DA7qi1XNX74Jv9dGAWSvHVv7qHRNoEJ0XBQhFRctLejBDjjsxhrFwP6fxQPDdZ6fl9lflxUMDT1QawAjYhY0R)FZ9JjVnYiV8Wp33jJK9HMgW8YX3E0vpAGPRG2wx)BTRd2iIQtslZ6vwUmuYaoEUOV(O3AKK5Y1(W8Gi6o10wCpS90MfPu0nS56mYZkIyB8Mnf9yY0WLyuozZSz1J)4cWjYTFg58yHOBdSbG8POYI71hZIQ2q5XM89oScgQMh7Tg5tYB1tl1yd6H2snipy9XbW9g14oHpErXCwl2lEGMz1nVMj6MhDbnUHxBmhyX(IaA)rza8HS74)byzntE5zGvW(0VRfC(xFByd4rWJHNaBM5JGFnh8BOWUnS1yFW5sTchTpqBa0gb0pCfdG8MJboGlsRJviAQhvahsH8bZC2pAgpTWg6a(zQyGdpLb7W0A2B(rA2mv8ZGayqAjbDZd3hyq4wW)GL78GaO(WZbj8x9H)CgeJfHBxmCJRnxY9wgIrDaOGFh(diXh2g69EYBWsVJ46Nh5UutZjYPvyfnGOTG)ofB1A2v0IUP2(F34)9d

**Comment by InfusOnWoW** [comment]
That's already fixed for the next release.
