### ISSUE TITLE
[ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'TargetUnit()'. Lua Errors

### ISSUE THREAD

**Issue by alliepet** [WeakAuras/WeakAuras2#4094]
### Description

Hello, I am receiving these lua errors with WeakAuras whenever I open up Edit Mode and move stuff around, or when I learn a recipe from my bags. A reload fixes the recipe thing.

The error it gives me ingame is: "WeakAuras has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI."

I do not have Elvui, all I have is WeakAuras and Dominos and Details.

### WeakAuras Version

10.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

5x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'TargetUnit()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@FrameXML/EditModeManager.lua"]:1518: in function `RefreshTargetAndFocus'
[string "@FrameXML/EditModeManager.lua"]:1462: in function `OnEditModeEnter'
[string "@FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@FrameXML/EditModeManager.lua"]:193: in function <FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2552: in function <FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "*Blizzard_CompactRaidFrameManager.xml:295_OnClick"]:2: in function <[string "*Blizzard_CompactRaidFrameManager.xml:295_O..."]:1>

### Reproduction Steps

Open Edit Mode and attempt to move things around.
Also happens when I try to learn a recipe from an item in my bag.

**Comment by Stanzilla** [comment]
That's a Blizzard issue
