### ISSUE TITLE
Support professtion gear slots, like fishing pole, in triggers

### ISSUE THREAD

**Issue by mortenn** [WeakAuras/WeakAuras2#4096]
**Is your feature request related to a problem? Please describe.**
There is no easy way to see the fishing lure timer on the fishing rod.
There is an old weak aura on wago.io to track this, but it triggers off of an equipped fishing rod.
With Dragonflight, you no longer actually equip them, they go in the fishing pole slot instead.

**Describe the solution you'd like**
I would really like to add a trigger that looks at the enchant on the item in the fishing pole slot

**Describe alternatives you've considered**
It should be possible to do this using a custom lua trigger, but I don't know exactly how.

**Additional context**
N/A

**Comment by InfusOnWoW** [comment]
There's as far as I know no API for checking enchants on the fishing rods.

The api for checking for weapon enchants does not cover the new fishing rod placement and no api was added.

Technically it's possible to parse the enchant from the tooltip by calling
C_TooltipInfo.GetInventoryItem("player", 28)
and then making a bunch of assumptions.

But that's too fragile to add to WeakAuras and you'd have to write a custom trigger for that.
