### ISSUE TITLE
Image issue in 'Blizzard Atlas' category.

### ISSUE THREAD

**Issue by sapiens131** [WeakAuras/WeakAuras2#4101]
### Description

In Texture Settings, in the Texture list,
Some of the images in the "Blizzard Atlas" category appear strange, unlike in version 5.2.2.

### WeakAuras Version

weakauras 5.3.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

The images just come out messy.

### Last Good Version

weakauras 5.2.2

### Screenshots

![combopoint](https://user-images.githubusercontent.com/119821540/205523658-4b4c6e4b-9487-4c5e-8bd7-2c2a7b256b82.jpg)

### Export String

!WA:2!DrvVUTXrqylBeyaMaKicbffdhezxiKuyjtkyBKFua4rrbYyAsIJ02PJ3U3T8Un64UhMDprrLowy4cdeewgG0WUaKkIG8aO20CGiipaSjfrvc5biZUKu2oxZT)mZSFZ38nZAhLVF(G8bV8(t4(srBzk4ZU91OdiHYAhoU6XbjHdRw9rWPn71tX0RbdxUykr4hjHwsUqtlxPrNkUZ8LY4a5ar7b8eM35R2wjiKfbeFnxkup0vPjGohThxWvr5CWF6CJ0apmKbQg7alx(YpXvJoDSdjvlhNQyT14oL3yskqeK(m1To)Ix8Ql(PF5F(HxDXp)BGFebczQ87pkaTW8y5lmlKjya3VDKCqtXef(Ru8aYq1imGDtXN2BQzL5Iq)GiQY(i5l4yUJMetgYaRflJU3CvkLDctOBN2Rh)0PDlxQDNUT7uYTJJEycZ1aVIxACXc)f(fnwLWIJBGWERR)3)rYhSmCDLjmeRs4UhCW03W(87pFbsAU6(V(aivyF4S1bm6Mq5LSU5DERC0Z1AuYhvEj7VDlqgcmLA7pTTbdF2vzqlGHzGB7wvQxFgWiXTxHXSnMzzLv79gzxwlqLBsaJIzEhmvHQvQ36ONwFUXwcvjb6tKbmpxB1j34R4apaXrtr8qVXPILL3nZ(WSTMgWvFxQavgNWksIJtwNyx3zHnMO9Rx7suHXabj(zO(aRQF)LhZyjLqe5RDn1zVXkwCpRsm7Mi(ueTraWIgbsTviSgCYcF)YjyY7YcnkXBTz2DMHBPicdbzQiGgX4Hr6cuRFmpNyjj4VM7htuQUerGHq83HQ4IWy2p62pnwZ38FFFpQMeJ85Mz12CR35R(DpxRh7KvLw9PMgJSA5GZKcgYFxpjVvn9wH0B8vN5n)kI)ybYAlUYu4HiBn5ewe3pM9uEKJfnzvVjg(rl9Y3BYR91O0Cu8ZyiWYDPMDkslSNdKedVMSr56LEsRonDQxQ8JlD4H16u7zvWIOzcaL3prcAhZmbVrR6J9O95aiHOXebVVLyFy27E05mIP5eyIqD0nZUJJat1zR6b7AAkafdJuGAKXuJ0jZZPpHlokRl6qMxgjJM5J)FV))jtaBXYk3wMbZWbc4KNMj25j5gtrUpWKsUo1R04WIPqCYTJ06e1xS3EMbz7YL7D1KS9k(5uel94H5UCXiSJauUAEaA7YUvQ0yApZbycr0KBK1l5Jll7tLw5L6EVE99E8qGteufRpwCOf39(7w4bjBSIS6GG9qUIGOlikBDVjAP)sr4wR9Ij3Lhm)nNETDbNZKY(RzLhRADXKY1OdDhWd0r75sItIi3Oykpy6P1B044NF2Jck7aCHjWOz(Yyj8n3a)MyOB(ccAkx0tclQx7mfx6ZQyA)vEjBXdfsGTKkTNwXuHXRwhBn9bMM19QMO8k3hS7(7wi)j)53(F)

**Comment by mrbuds** [comment]
You must include an export of your aura

**Comment by sapiens131** [comment]
Export String added

**Comment by mrbuds** [comment]
Thanks

**Comment by mrbuds** [comment]
This happen when aura's data have mirror or rotate options enabled (but UI don't show them for atlas)
It will be fixed, as a workound you can change texture for a non atlas and disable these options, or make a fresh aura and copy your settings
