### ISSUE TITLE
The api SetVertexOffset doesn't work for the fg of an aurabar . 

### ISSUE THREAD

**Issue by roundzero** [WeakAuras/WeakAuras2#4103]
### Description

Before the latest released version 5.3.1 , this api works for the textures of an aurabar , including fg/bg/spark/overlay .But it doesn't work for the fg now , everything else is okay . Here is an example : [https://wago.io/8W0z25711](url)

### WeakAuras Version

5.3.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1 . create an aurabar 
2 . use the api to shape the bar in Action - Init
3. bg/spark/overlay can be shaped except fg

### Last Good Version

5.2.2

### Screenshots

<img width="263" alt="WowClassic_kHzNZCL9zp" src="https://user-images.githubusercontent.com/46548538/205528571-1bc7d718-9581-4c0e-b2db-8049f215aeb5.png">

**Comment by mrbuds** [comment]
We don't do support for unsupported hacking in weakauras, you got to find a new way or drop it.

**Comment by mrbuds** [comment]
Alternatively you can make a feature request or pull request for the option you wish included
