### ISSUE TITLE
Dragonriding load option after relog

### ISSUE THREAD

**Issue by m33shoq** [WeakAuras/WeakAuras2#4106]
### Description

Dragonriding load condition works wrong after logout while on dragonriding mount. After loadscreen WA wont load even if u still on dragonriding mount

### WeakAuras Version

5.3.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

1. Make a weakaura with dragonriding load option on
2. Mount your dragon
3. Log out
4. Log in 
5. That WeakAura wont load 

### Export String

!WA:2!1UxFWTXX1HtyefhJiBtrBRilfzFMoscuIcIFirlPyzzccisOqrsdasjBzhGd4oG7epC357oWpKJCSzSDzMMMp4F0zCNPzAyts)kTjLPTX5t7rPnDAtJ7tSFiLoPzsztZVFU9)0KzY0oDg13B37oChiGKtAkhPd3U7B39TV991(23fzMUSZEKedMO)UQ1Luxsl)(m7QSHUJLHMMS0ikQAswY6p1gNvr1stvVQqU6wvLVEsldDBzH8Q1K1mkp76NXOMSUt9AcJPwvjBotzzPSZOw1WAJsgwsYwjflpRKLHPzNj1uV4ffTKeYByO5OAwAEXQgzsTI5IPFIQw5oyU1fR7OyynPPJkohXSwCYkvSLD2AS1e1lJnmLHQUtPrspr(0zxJp6JyOzyD6irIeDG6wAM7sXXX0(4h6q0qNq14q(J9H63sSmBChkRTJOLtSKQ6QoXkvb)Xwj2sowQvRkBzVZ9A5(6RSQKCP6vQKFrtzRXsp(uNA6Xt6GfYkw3sCGLSnL10YizhBd76LKNdPc5qOvxyTcJmCU8fYLF4S59BAklzSPS5Mk94JNvxSMSDSSSgknMSOMJsY6i2uYutCrzRvQR7IcXUoUILT0f1Mbrne7FUvSL1QWieWDBnhVYORIZsw5QmQwsndrPtvYrudh8TNTwDKuhljIRL3oKiw2YAI220BjTvVOm9Y6LC3H40YOrJov0(sCKs2g1TklxsTMPHLtw7Y4agTeNQRSk)30svLn3wUNTUOLSWPQRPjGmloYRAXWfIULTQLrDtxWZHZ4wUm)D(w7DuYwUgUkY2FI(s03QogLDxs7iYRSA3QsMDnDgHdkKk7WJo5eczZKkZeJUwflK8LZXs0rm615CgNIQIMVs5gjB60tyTaF8phUs6FG6QsRDUAhUF1PEKXw80XlHC5vuRgZLfkdYo7eDfgIMbBQu)dE4(gAWvXxLu5CIRPQxXWQMivA7RXGKp(kRiQRYRFi4EpfSRK6g6Yxww0Mqqz9Qok3(6si3cbrbI3XYwMgy7LiyimgMmznrvDSVWKWu3o8eqwih(62BUMUkFHL3)QQyVZX2zEVDaXG3nS1yWDo2BSRx9R9LhCWhfUl4UxVmkEjzmVEU5vnLlEzVI0MLcCpiEgdUVyW2JbVN7AVWow(EYIKYYZMef(mm3wDB5cvL1LTulNtXy(j1lUEOIRAJ)mS28IlAdcWdTgbpvv1YsfH7h2jSRSm5cZUOwerUilgh(zmKKlcpa8GWdBE)J4Isctzzu1s22wiEoQt9ScRVtGBM7ylVK56wyhZ5vJ5dc)gx5fUYh5klDLpXv(OWRbFvb8X3aE9R8rGV(v(yx5fxNHlEGxe2DmO7yWEG9UrduHHgRqLzl6IlrVsIEfH9fZCBKkI5KZZf(iy)cDaXFURpRSS5WKiKtwANub6bUBu5GTOdT1Iu19hfoW(3oSR1rbrsCIyr0LQa7AfQcgB268FkyWyCI4kguOSVcmx9LfMt1wTKMCrx2ZcY4(gCuVsKuB0skYOYwNXE8h)v)m)Oo642GENXStALizH690TuLq91fHdsI3qFSNhI9SF2ZbHdB2zabh2JRFwzXzhgxp2hNPehowsIxlBzpTcrHXJbtWzZdZQM)wZ8cZvSKjQLavB94q61grCIYdEKjgZ8jkXyu8yiqsosHLlAEVECT5LxWjLQTisrKuGtapgCsxDdqui5A5spE6rYFQSdFM0zf1mveJMDEvjhLCWWrHrJzPQtkuKvsErdJAKETbHTbDbFGDU3SLvKlp7qWo6TJLMt0sLMHUNmBjw127hBikS0Am2PPztF25e1QlhH3WQg6E4m8YrTkRiQxvgTDaVCXLmrDPYwolcxyjVvrri1yVrPV9GF4BCJp0Y7hMUjzxOJo64OKSlmtr4STuifoh8KWtveop80KCh8mUsBWhek4kxbfbXDSLx7nHsOOYN6kVa8TGVj8vWNRDLFvsy51HVfk)Se8LGVoifq8aqzLkfHQKiaOW44bvgpoCHgS2WSi7mOb1Ia6m(vWOiychfE2OGvqorW(MY5boqD4yWCW8)YGPcwGXpvT0CtmA1KJy(ShdUyr45AIt5DajHpeCPOWZ7YxaFyf4fcXoaViJvawc5bGpI72p8sWl7UHdVcUpd)kSDyyz4cWhL2tF8sFJV3l0rh9U8Xx1gzVN9SeV395V)Mc)9o)V7aURbYp5uBiRtSrJAjkPIYbkRZ6rwdhMXHiMBluzs5tYHNo)KmeCof498bj(GUSC96O0GpYad1FFl5zCzGbt0hC(nSzkP9znjofoBYdZ4reJGQFVxMkvHreTDqF6kxgf2LLwZx5zgK3OuKgCiithXK4XHqyX9TeALVgPLncx3kZEGJvDKtsM4r)1bHBZDIFVm(ZBdN6ltG61XIWdV6i(wyPjHnNxMCTIHgQs27exKpYadEyMIDMZsKfucpUowt6fqT158W4kCSCFXwts1(c11zkYhqutJ4OzwnleqtgYH)lmthYXTsjrUNNdGdxKOl5v80rh7KV1)5)LqhDehLpUGY1BylG3(yN8n6StS5o28lrzsANMjP5Ajb95qM375irppliCn3dGtkul6MegxURbenvv2aBUqnKjsRqznvZIRXF32PqD7NOrbRlgjqHfJCzEHkQAYep2ah9i913Q86mfDumFi2EJ9HeTklQlBAmpzsc5yLlG6nTDsuBGgdNZIrS4fwm4KSWpUZLS846HDTeUqzngOJl41rFSJPBNeyhADEf(wjB0Rl61RfIawmLR9(kmwhYDBYvIAkOUjMXFDKBYsHRMAf)Mh4IvKDvx1xdLwBWKltIUtlrcLdmCQumJTdlDH62oKSZzexqHuQGA34Qb89KoAZqQQRq6I2WUMHHJIN7pfbhZ7VH93ubSIlmDg4ywKubTFFPOM3tvxfitArpzKXvhBYSzEQjNi)WJVcJv3wvsoB2mJowEs93wGxiYAmeBmMFdNWYbTQw3soBoduoJ0vEzwZ55vBgpdDQJkILLFAslbIgjfTE6PZCWgLoyoM2kw3u4AADNcvjjz9StKEM0z5Jk3v5NmcP695)P3TN1T9wQmsvmQzUxA1vqwFUeZrNBu4ec9fZVk0YkEQtQUvKmkW7rry77fUQ5KQve8HdjJOQpbhfz9yc4FP1lJcoo05pToo56A8Ey13ChoHqfrnB5y4Ul89vqtjdk7mvYCx4dC6jkJwjcUcoxK1mAqZHVl8bIbJV91qP0YYPjTt4(ypLsoz(8tEMLNc(yC7aBD)Za7cDytefDTqMbMYVK0ga8oT0noJmU8kcpFuueVKJr1QAYOqEfr8yBftIUyw28(q3FOZfkytULjyOlGCcjgyw5fxHvdTmObofcCXKeZS5941fMNCcZqoUap)uVd8uwhH0psTr71RmLQtzLJlSht4oFi0)JFn4teHzVH2Iqs8TrKK7dFzHDCTdI)jmLi5QisvTfOYXIPzGNluOgrQ5KaKG(Cmc957EQXh(jtNTWzMC6jYxivMCu5cJm2WtmA6uD)miGKbJEDbMd1PNC6Stm84fMo3WjZmEM8Th(XtpmYJLQa7a1fYmrH8dNmaqxYd1eTlthmNzX7ecCJMUn5OyPQPLepZoRfYstOw4eVtimKxhQjUqoXAMAY0Q8iHMGuUMHPrkr4MsAyy7GQiOM8AX0qtJC0fRRFHdj4Js1nLWANcpULHuZTr7ZEOudXd2rzt4Zi4blvM2Hpf7yR9gOc0OjtgR79KOVk7zpD3lod9HZZJelgBlEgxFHdVdZpyKV0sqSDmrDjnQjDvTWeDkmlmPzETAOYJZ1l7NNK)tEQ1Ez)ZdX9PV(1mRQPjBrhCQ56pzKJEDlmQBjAG9OtEdoFPno1v88tscvyoiGoEeArMdTP5Zf7RoorJQDHBuzhk8xiqUV5w)WvqjdS2rkqvALGvUrFskt8bM4wY04bozWHftSPwA0JPyHdcBzkdBvx2l)oTPgB0pSYZAyPjrbCjyxcwVlnX9SUiRgNsGvXxRhNEvq4MjeZH4wi5YbQvIR8wMEIm55vZJA20Jms60PsN648yHXbk1zMotbEuG4bbQW0tLA48P92582pfq10dZyvJJU(XCmXg5pOFDv)7XhZQJvfBxkoYM4niUwk8(RX2F8U3mEKBSjpB3HMc0sc)f2dYgfFo9nn53MB76goHfLcbj9xtcAE8xtipFE1YZIyVN(K2UicmDTcDA(VB(AMt7XvnPRT1ZdseI1u5gagSXMje(BBNVBuD(MqYWn7zRj4FUw1ByRi4F8ZPl122nDDiJcmhPJKMl1YDVzazXcGPGztnjINOsR1n5GU9snHACBrJmJoE652C7mv4KFdeI1ekDPqLSKrV40zlXnrZLjDObO5V9z8o(i4bpK1AIXQf2aUvBZ)8SfNiKtAThSWBSV9Pg4V0)B4VPBG37NMtprPaQsyNcTxHcS)5EC5Ws7mieEECpQfcoPMIeCAJQas1RUn6)TGdtQwq1g1RyWS(HQ2mmL1PdeC2HXx5XLoarLpTNaN2jNkFMjNix3BMY6sjAPosgb(wiIIiyk05VYocbJZOa76uouWEG4taxcppd3AXoncwg7ZWCtxkEpTwJe6DnrQzdxgjbvDbvtrvl74OrnQUtBuNUEeY62i0fxvghRGNFIbKD8E6rqYODAeTLP(f)W9kS5bLvoJEfJKlMjvCx0ONEU5QpVze63(6mBJE0)pAlL7ZMqjYB1wZy1ol1D3YDwxHdQNb9bVL0TW(l66uvtkAAZkpSIHGY1(RtxF6d5Xw8acTmAGMJidKa9qIqgw3oi3BvprCSHhnSR6Hwv44X8TxtTg6Mh)uBCOTFOyTf99qzp)I9rMyTY6Oakw0AZLHg5WeceXgbpVDDe3qJuSRUWf9WH30WMfrLaeavDCSrD(HuRg4ag9kWJovqVTdatnrtobpS7TX7M7zx394TYiadrb9oKKVtVTYD34y36vi8G5oG(9CZmMbwsB2MsOc(SfEJwOw5O4c9kSiosEqKal7)(ITa(57vqHVCc6koTscZSthwCbH9lmFOAPPArSwLwmYs8UW5upxRaG3BoapzyaOUqDFt1(KuFUPKipgkfdl1lAO74XBiGEeiiYc8fthUjfPHqDomVdEkvLe2pRLtCjAHJpoaHY4Bl2dE6ujNM1VeS7pMqFTwXcFPx2WoVImUt6ony54SxelzhVVE2S2yC497tBhBFFYWHniYCi)((ZL28wQ6cjWzQQBGUeyuAovJ62AlISWOZNQs852gXnrhbdsCwyEs8)c1RzswLXndz7ynugZit9FKMwmTvnK)071z8eb7dnpiliXSxqs)wYs1lJ6ywW8GIZvvyEvDj0zn6gkdpVOjGMM2ghZNTputvpE)96vBpTvfUNhYJuGuKWpDUVQbQyYf5xiqQ4ncUtyn9toNSf6zGmITokB2OhIZUZcX)Yu()OHmpDGMd4tRuC5DR2NqiUR9JadbXohEmAQ7mSHu5gikuhqioEcD)rUhuWiC0LIf20l2Lh1DG2eZRhtByt9H3w6lC9(XGPTEr3sAmFMkjAZ9GnpNYs5utSMq1GRvgLNdAyMgx8oaSBE6dWS38ys2l)5zCBhfPfuJMPa5qq49LefXLUglk2IM87a3tKIFRXnmd6QsI36bdgKREiH3(AskIwRU4YM3KBbIl3S9U2SV(229QMJnxR80GVi4R4yTr2VrGv9vcGC893tazFYA0zz3Ebjv5b0brGqXj3IbaxxEEFO7VjicqwPabfO0(donhWDxA)ngSaDF0W9F0woabnl08WemmLbWHq0WPzEnk4gXEbV0ui4cLOJHCcKJJT6aX2j8IArZZNDcFvRKqsdbfFrk)yp3c1DEYpXPzICm13jREyYDbPWyRbjynKPsem8gEAf6N1)U7M1n8K56vtWZdR4Toa3irUPaD3cBjbJha7wF4xNe8pHVz2DGBhPaFUkywGuItxMAbYL5IWhxzP5nSKoRLO5sN19f4ZD6iJDY)FZp)l0rhhikD5VjRGUdz25Pq)IeEI6Isu(QjKpp8pgb(RHVl07pHwpuQKfJD37K96ms2UxkPxwtS3s2iuAYWKqITdtwCd)RPFwDJ51vwvsTsf1Y11CwCVWpBncrNxuBwSpu3TlA5oSMX7)ypYr7vyG(gya2Zbzppm75rWN93pR(JnO7vF(6kR7TnYYBTyR2yw3Xw(Ilz2jDt(ulYpBDMwGyRBRiIoaCo(TLff(llcFNIWXG)k4Vfa4kW6WFN7nfsPIXFb7(rxTI6cYsS0M4L2ksmCqfMYwtoD(XZmrA4heHLgflap(AIU3H6zu17EG(CNQNKpvV3oGpj8P2GsGnkx8kZgUKdJfH3ZhFVWo(jWUGRUg)UdzlM1yIl8ZKDDE9(x7HzkEmf9Kv6wVETs4bm4bCtIDIGMR1x6PB0MQgw5LCZiN3hl9Z4ZGN1EZhRPy06Yq6hckUasb(uDaH(sG7p93BdgwkPoUQ5G(JsIejA9a5flloeux7og8IiAT7y8Ks128ZEZIVFV3Qy73BlJRFV3Qy63BBJNFVcZKESmJmE6c44Jp51YYKK9fd(mWQMDXjMUxBX4gvvlBMWNuGox5seI7C(bEgsVHZ5h8z46HCo)HFgsvaLriM7QLc68xYsIrsTpjrwEBLy5sswuG)N9ZUXnUX3NAJx3Wr5)oAew3q4lXsD2fJcxkcVPKJDYpzND(G34gVwxlgzfwvSeb9QCixikoz8QpfUUwiYd7V8kG(CJCcvX)xc)Vi(FluSTk()s4)fhiOfZaEHsUog0rB(7IleVzEoESRD558ozKxSh8GL53i5xtRojrJRndDmFSCZK3su3986Ei0BVfriNvCh8W9lyeClXYOe5iDTqewcEWiFkTi7D(SSm2HLRnxWlxBGFhw(1a)UWVxlZOMoVofq2cLOuaHLtnW3g2LLD9su1xM1MB(ghHdzGud1StF1sf0yjeCXnyW4OGpXJOzVLvzLBKiOmZbUzOHI59WAfzvlltjApB(Tg2HDN(852lvy2imKDpuF82DhQsh(i9DS(pkVo3uRpYASsCeBp8c1uTSqA36Sc(jQZYDB2fnqfcPKpYkS6OhxEp93WgUzNbG1ph9rQdtAZxL)lA((87FtwB1KRkwEXcv0mqCzv(UljRMCIjNiDl7MKCz1AIAfmTWxOCipYQmaAK2xHwbU2oISoRop75W1x3Du1DiHYRfjAJkOy18qRZt)kpcG5UBbQWC7JzPjlBbyE)BciD3xGjn7Etn2Gq2akH2rP89lzd(QZ77di54PpvEK9HQmSPXRf52DxfEeHlZGISWQwzr4UD5UPnsojl0AElR4trGFAia8ThB2t7WwPf1fRHYcOjtkbC0Kw0CFBc2aCs9puF91Gi8qTBy930J6Y6f4lg5Arg18bAxh5LIy(W3mKObcCtXvhdhJgGE)Tyk5VuAcMZdCIUN07YDb)(kWFqr4l8eWFye4pkc8fHVe8hdRbF5iWFse4p9h3j8Nrgv(kWRfb(QrGVglD4GVEr4Beb(MraR9qPS7AnjZffUmQT6pV4sEmW3pljCFHiWVnxMyVT3J3qYGq61Ko8fuv7BYY1hBqWX8bBBcRjWsRiijmsd32exya88RuIS(3aFpkP0ENWBEcZTfil0NID04Iu2OzEG2JuBMbc(8308Q0YLTMydE42pUn4GG)E4FGL6U88vZuO9DYJ7PtxVsqi4NzdDY6dR4LIZ)ZuUITZHyPyCuyPsC3fHxoAj0B3zP8ANLxX4Q4B9apWJ3rh7BSt(dE6NgpiXrh7KFZDV7tEJBuokSm85GX3o8dlcJUD4TkU8rxr0Q84mf3V02HBBNRW(OReskAbVl4o4PF8wFxWDgzPQ4gdPlR7SPGoz8elzrhNdTte1pBV8t3Cet2XR4N7U7ogZtwYLt03rxhAPSSf1QwVMoFqkrzKyD7xARqpiroROMAvD4UPpTIXPRarXcD3M8wlcZS7)lY377AvE21rA2GEpvOJkfiJnPSsSS8Tdd4)XmrsoeB)OXGJeDvkUzYmFU6E8SWqkWJG25p2LD5SyNjdE)BjPTHLdpFFT4FLpYkRq0sMo03nmw0nkBWoIK7znlLD4uzMo31P(n2ILiQoDIITFTiQkWJEhHtj9Bpl76HE3etgkOKeN15HVhkKn0fQo9zgE2Emp15GTgB1k110gr1QmQHaYSJBBRVfpRdj(G4p3YhLYYq)tjD74Un7Ri4teHoqu4mhFBuMz3DmwcXYYBxEUuZ3OVQ)hrq2PO2GQf9oVKIQeAf8EVwK311IChWvxylY(UJ20LIJ89I(EmgNkXC7MEjX8QsvLDYKIUy8WP75z5Ti1tOBVQfr)1Di0RyWJaCgEppJOUiYBrUBEkuQAAtMYeBEJZOAxNs5lMpmuxJ3MjVXK5EHZS1gDDZ8BBMVudDjYSQcLFcV)MAlCmyE)TmyLXdSSiQvJISHwphdpqQwA8eNj44Bo)gsWZ2wxAxJlNHweQNa9soWWH9ppL)jC6tZxhUBaKuFgVCJI9oomp3LAXLjzheQ2F)q2jcKnon1YnjJnSt0uE4SpEE4SVMGYlDAcSiRGSabJg(MqPWKCIOqF3IU0Kh7ecQT5Q9Be8SB10rhC5Molhapp2j(fzMy(8VP5s4MmcnJQQ63Y7FYNIHvieMvT5SoLunWyA9Kfz6ossFme6oIuGCyR43gG4QFGtGoFRLrFME2u0VJ)lHr94zSzYtXBvsD8lJXhfrdMldT8stAkMKXIX(WSUwK72StEiqq1DfoBMuJMopZw8UJDTiXmV3WrQI17lX)eDMHz9(3I)rX8BUt4t7hdLbe1xK9vEX9)d(4k)IBp29W08qFE1R(J6OJDYc9jlX3d95SCRoIDRD(1)Znbn)johEQEMHWc0fnwaDk1mrTbAR3XrB4zmfU1pVV3vr38lrVfF2AmxOvaR7J5eb9HXLkIBamPW5(Duyr585FckUMO7T8C(h(rW)sryJv9(S3Nod8Vsj6p9z09JH))jjPh4Ftb(3vG)dZDsCjcP4j(Va3vo3K4hE(TW8i9npbloQKxebJLk6mb6Gb5qp3tc0fIzMqx8P6BHJMkBFOZIxlYYfjNr9(SlGRAU7wZRI8qh(Wd1hlI4X4ETUF(hg3wGLssQY9)g4qQ5B9QV6RFJB8dh7K)KHgcDr9Tg7KV5N(t)gD0XhL5Rk2VtHE72THzxpkSe8YWlFTif49L8i7rqyUe9T)f)56AU3XL(F(d

**Comment by InfusOnWoW** [comment]
This should be fixed in the next release
