### ISSUE TITLE
[2.5.11 Live] Full charges/stacks not displaying when using Cooldown Progress (Spell)

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#411]
_What steps will reproduce the problem?_
1. Log onto hunter and import example aura.
2. Attack a dummy.

_What is the expected output? What do you see instead?_
Expect to see a number on the icon for the maximum stack count (2 or 3 depending on example), but it is blank.  If the ability is used once the stack count will display.  When you are back to full charges, the stack count will disappear again.

Yellow aura on top left: https://media.wago.io/screenshots/4kedFqKaZ/1501189273779-2017-07-27_KillerCobraAssistantParsels-optimize.gif

_What version of WeakAuras are you using?_
2.5.11

_Was it working in a previous version? If yes, which was the last good one?_
2.5.10 and both 2.5.10 alphas

_Please provide any additional information below._
All stack-use action auras I have are built the same way and all won't display stack count when at full stacks, but display stack count for anything less than full.  They use Dynamic information from Trigger 2, which is Cooldown Progress (Spell) > Spell Name.  Conditions control when the text displays.

_Example aura 1 is for Dire Beast and should display "2" for full stacks, but is blank.  It displays 1 stack when at 1._

In case you do know which aura is problematic, please export the string and paste it below.
```diexjaakjL6usk5wIQk7cfLHHsoMiTmu4zIGPjQY1uuzBOu(McX4us15eHENuvvZtuvCpLu2NKICquQAHkXdrrMOuv5IkK2ikQmsPQkRusbZeLk3usf7uOFkvLHkPQLkPspv1uLYvLuuBffv1BfvLUROQQ9c)vsgSuXHfSyPkpwuMScUmYMvu(SsnArLtJQvJIQ8AfvnBkDBQ0UP43u1WPILt45enDsxxITRiFxQ04vOoVsY6LuO9lIgPOHZrKrcSLUoB4sCgmBoMLMI7IpGpGgUsJ1uMZB0ZRrcrg5HN5TEbAiMhISy2iST(6ZXkVeyTEESXifk(Q(MntskIRNiEit5tutW3Bsuh)aHyko3OKWeSmFsi5EdIjGRc(Etc0W1voeUudArIxm0ezu8qr94fjvXntKqsOhonrgfN9zk3Bs2PMLHEwcViPQIHRybxqb7DiRngCj8(XfuYoluqQ4fjvjDiRngCjSGlDiRngCjetzWITrsepRivVBvo(aHRCxAakUsJ1069CJIZ0OX2O1fxPXkdMZBu8w3kMitvDAvlE7aEoIVZPiohlCRpmGgEMniLOHl5MTLW7VAo2gTUqX5MTWxCqd3TyvoAqHIxKuLHMib6HRblzu0WLCZ2siohUBXQC0qKnSGyEybku8b(Sz8SIvxHgUBXQC0Gcfx6qzOHl5MTLqmfkUiKrOH7wSkhnOqXlsQsdwYOOhErsvz2GuIfCH3sOH7wSkhnOqXlsQs6qzyb3zYrdwYOOH7wSkhnOqXNfYuU3GgUBXQC0GcfViPQmVBVGIfCnyjJYanC3Iv5Obfku8bUK5vmzkFIWZks17IBkUnbFVjHeXeWvASMYCEJI36wXezQQtRAXBhWZks172e89MeSZV5z4ZkMmL7n1wf89Me1kznKStYoj7KSJG0IWKStTvbFVjr(MM)j74fj7Oc(EtI8nH8Vw9FYAGmd4cAZ9M2khcNN5n4CdxRY8UowsPbetXdddCL7nbBLk47njKOHykA4QGV3KanCb5g4gUzx5Dirq9c88zn8IKQkgUIfCb5g4gUzJNYS5WlsQQ)cY6jfl4shYAJbxcXugSyBKeXZks17wLJpq4k3LgW1voeUudArIll9OjYOVmBgFmEftS)TQ3yFDB4fjvjZ572Nbl40ezuCM8E7GVRjzN6f(TGKYKDQ9DiRTw4ckyVdzTXGlH3pUGs2zHcsfViPkPdzTXGlHfCzPhnrgTEbnJpg)1pk7yhUmNVBFgCzoF3(mm592bFxdErsvcYnWnCZg9WlgAImkEOOE8IHR4o2WksafVyubFVjbA4shYAJbxcXugSyBKeHcfrgOHRc(Etc0WfKBGB4MDL3Heb1lWZN1WLLE0ez06f0m(y8x)OSJD4cYnWnCZgpLzZHNvKQ3TkhFGWvUlnGlDiRngCjetzWITrseViPkb5g4gUzJf8IHMiJIhkQhViPkzoF3(mybNMiJIZK3Bh8Dnj7uVWVfKuMStTVdzT1cxqb7DiRngCj8(XfuYoluqQ4fjvjDiRngCjSGRRCiCPg0IexMZ3TpdUmNVBFgM8E7GVRbxw6rtKrFz2m(y8kMy)BvVX(62WlgUI7ydRibErsvfdxXcu8Irf89MeOHlDiRngCjetzWITrsekuO4J7B2mjPiMFRNiEn69UiYIzmseNpGVuN8RFCbLSZcfKkUsJvgJAc9S0awW7Yh0Ciohl8mV3o47AA0yDutONLgqpCUzIescl4fJk47njqdx6qwBm4siMYGfBJKiuCUHRvsniuAaXu8mVzGRCVrIgIPOHNLJYMhnCvW3BsGilCVdEnTg(uWwi8u8PGGh6zjCPgYMxcfplxWSjjAiMIg(uWwi0qmfrwiYarwiMaISqmpezbf3r4DiHUcxPXkdM8wVakuOiYan8SCu28OHRc(EtcezH7DWRP1WNc2cHZaFki4HEwcxQHS5LqXZYfmBsIgIPOHpfSfcl4ocVdj0v4BRVluOqrmb0WZYrzZJgUk47njqKbU3bFT1WNc2cHZcFki4HEwcxQHS5LqXZYfmBsIgIPOHpfSfcnetrKfImqKfIjGileZdrwqXDeEhsORWvASMYK36fqrKbA4tbBHqdXuetrKbIPiMaIPiMhIPqXDeEhsORWvASYGjV1lGIycOHpfSfcl4ocVdj0v4dKmOfrqjOqHcfpZ7Td(UgSafFcX08yKcfaa```

_Example 2 is for Mongoose Bite and should display "3" for full stacks, but is blank.  It displays 2 and 1 stacks at the appropriate times._

```di0zjaakjkDkjsDljc2ffWWqKJrrltP6zkfttQIRjHSnjs6BsumoffNtcEhfOAEse19qi2NeQCqkOwicEic1fLQQnkrLpsbkJKceRucfZKcYnvuANc9tPQmuPkTujQ6PQMQuUQer2QeQ6Tse6UsO0EH)kvgmf6WISyf0JfLjRixg1MvGpRKrliNMKvtbsVgH0SP0Tfv7MWVrA4cSCs9CIMovxxsBxH(UGA8kLoVIQ1lrI9JOgMOHRq0Ctzkvs90dUeF3afzatt8C8j8j0WDERBwoQWVQuye37bFEFdgizhrZDt8uMRg5MwTwSEw6eJOjUs4SwKSfpRLkQaXn4UwTwSgnCFEaJl9KxL4vbpYchpvDkEvYDkXiRLmgIZJSWXnCMROcYgljzAOLXRsURkuoiGR5K9bS1gt5m(SuXIsLmzJeuoJxLCNmGT2ykNbb8SQ0P5DHutmURY5jCzaBTXuoJOzbsf2Nbo(elZWnywAyjzJHdXcYgNtRKngknYKnUHSXSqj9ILga35TUzVuLWXjU)yR)YJ78wFVCuHJ3c3rml6MT1rGANWdXQvihXIiHBPPj0WvILMwdqdpVADfAWHJxLCNGhzngI7jllC0WLkXYYiAwapVADfAiAAcciAwaeGdhxgWzOHlvILLrCdC8mBskrdxQellJBqkPyR)YdhVk5UmBskbbCn1YOHNxTUcn4WXNudgOYQwFoA45vRRqdoCCDkJrdpVADfAWHJhmg4jllC0WZRwxHgC44dszUIkqdpVADfAWHJxLCNmGZab8QK7YO5dtoiG7jll8D0WZRwxHgC4WXvIrwlzqa35TUz5OchVfUJyw0nBRJa1oHxfUwTwSgnCzaBTXuoJOzbsf2NboEwv608MwTwS2q0LkdFqvK5kQOSUwTwSU0KlgYgjBKSrYg1Sx1cYglRRvRfRlrZILSrQMSrxRwlwxIBk2sBWjxmSycxZlfv0MhW4QmQapSAYdHyrKWDERV3Vin0YtGaEg1s1OHypOCLAH9ImNPaP9YuM9I2qQagucfTboEAAs5kQiz7CTATyTenenrd31Q1I1OHR58KsOeRoAaRtovJxYebVk5UQq5GaUMZtkHsSWnnqr4vj3zqsYEzheWZQsNM3fsnX4UkNNWLbS1gt5mIMfivyFg8QK70CEsjuIfgIxf8ilC8u1P4vj3jdrd3NaeW5rw44etP2jAybzJ9QPlnlLKnw2hWwBPX1CY(a2AJPCgFwQyrPsMSrckNXRsUtgWwBmLZGaUSoKhzH)6GbQT4DeB436EZWLVHldrd3NaxgIgUpbXuQDIgwG7ZdyCPN8QeVkuoEGnnN14Y6qEKfEVAEGAl(7TFdzi44vHRvRfRrdxgWwBmLZiAwGuH9zGdhXD0WDTATynA4(8agx6jVkXRsURkuoiGlRd5rw4VoyGAlEhXg(TU3mC5B4vj3jdrd3NaeW1CEsjuIvhnG1jNQXlzIGZJSWXjMsTt0WcYg7vtxAwkjBSSpGT2sJlRd5rw49Q5bQT4V3(nKHW1CY(a2AJPCgFwQyrPsMSrckNX1CEsjuIfUPbkcVk5onNNucLybc4vbpYchpvDkUmenCFcCziA4(eetP2jAybEvOC8aBAoRXRsUtgWwBmLZGaUmGT2ykNr0SaPc7ZahVkCTATynA4Ya2AJPCgrZcKkSpdC4WX323Gbs2rSmfHxkuAoIKmWEbC1e(l(sywQyrPsMSrckNXNusdAvK5QrgpRkDAoEgLANOHfnER3Vin0YtyiUOM30Q1I1se3GRekVt6jTZtiAINrftkxrfs0q0en8SqCgrrd31Q1I1iscFmPvPHwgx6PmIkXPb4fhrWht2kJBchplusSyjAiAIg(yYwz0q0ersiUJije3Gije7brsWXd00aw7ZXDERVtm1s1WHdhXD0WZcXzefnCxRwlwJij8XKwLgAzCPNYiQeNgGxCebFmzRm(g44zHsIflrdrt0Wht2kdc4bAAaR954llnmC4WrCdA4zH4mIIgURvRfRrChFmPvPHwgx6PmIkXPb4eHi4JjBLXjbhplusSyjAiAIg(yYwz0q0ersiUJije3Gije7brsWXd00aw7ZXDERBsm1s1WrChn8XKTYOHOjIMiUJOjIBq0eXEq0eoEGMgWAFoUZB9DIPwQgoIBqdFmzRmiGhOPbS2NJpXYKx1jNHdhoC8mk1ordlab44JiA2ZUjCaa```

**Comment by InfusOnWoW** [comment]
I don't know what changed, but this isn't a bug. Your aura is set up to show the dynamic information from trigger 2. Trigger 2 is set to only be active if the ability is on cooldown. Thus if you are at full stacks, with the ability not on cooldown, there won't be any dynamic information available. You need to change the trigger 2 to be "Always" active.
