### ISSUE TITLE
Weak aura has been blocked

### ISSUE THREAD

**Issue by LuckyBlob** [WeakAuras/WeakAuras2#4110]
### Description

Getting the pop up 100% when triggering this macro with a keyboard shortcut:

#showtooltip Death's Advance
/cast [indoors][combat][mod:shift] Death's Advance; [mod:ctrl] Fishing; [nomounted, noflyable] Cliffside Wylderdrake;
/cast [nomod, nomounted] Swift Red Wind Rider
/dismount [mounted]

### WeakAuras Version

WeakAura 5.2.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Make macro:
#showtooltip Death's Advance
/cast [indoors][combat][mod:shift] Death's Advance; [mod:ctrl] Fishing; [nomounted, noflyable] Cliffside Wylderdrake;
/cast [nomod, nomounted] Swift Red Wind Rider
/dismount [mounted]

Add to keyboard shortcut (on an action bar)

Press

Notice pop up

**Comment by InfusOnWoW** [comment]
Those are blizzard, which addon authors reported months before the release.

**Comment by LuckyBlob** [comment]
Is there a way around it?

**Comment by LuckyBlob** [comment]
I was not using edit mode.

However, reloading seems to make it work! For a while anyway, which is good enough. 

Thanks :)
