### ISSUE TITLE
Progress Bar shows a line on the left

### ISSUE THREAD

**Issue by Hrocks1** [WeakAuras/WeakAuras2#4111]
### Description

Since yesterday a progress bar shows a part of the background/different color on the left.

### WeakAuras Version

Weakauras 5.3.1.

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

Just make a new Progress Bar for player life or holy power and you will see

### Screenshots

![progressbar](https://user-images.githubusercontent.com/75955019/205710255-927db03b-4d76-4b5b-8f98-e239017fa3f0.jpg)

**Comment by InfusOnWoW** [comment]
I can't reproduce it with those reproduction steps.
