### ISSUE TITLE
Absorb bar doesn't show after update

### ISSUE THREAD

**Issue by Blightwoods** [WeakAuras/WeakAuras2#4113]
### Description

Issue: Absorb overlay bar doesn't show anymore after update

### WeakAuras Version

WeakAuras 5.3.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

How to recreate bug:
1. create horizontal health bar from the "premade auras"
2. go to triggers and check "show absorbs"
3. set the absorb display dropdown menu to to value that fixates the absorb bar to start of the health bar

### Last Good Version

3 days ago, don't know version

**Comment by InfusOnWoW** [comment]
Already fixed for the next release.
