### ISSUE TITLE
Don't work trigger event in my weakauras

### ISSUE THREAD

**Issue by Daviongamer** [WeakAuras/WeakAuras2#412]
Hello, I need help, recently I imported a UI made basically in WeakAuras and Elvui, which worked until the middle of the beginning of Legion, several addons are already discontinued, however I'm taking advantage of the good idea, and basically using the weakauras to return it the active one, what happens is the following, at a certain moment, where I go into combat, a sequence of images should have the effect of appearing to spin on the screen, but at the moment it only appears, without creating that effect, I need to know if Something wrong with the code ...

The following is the String of the location where the problem appears:
[string.txt](https://github.com/WeakAuras/WeakAuras2/files/1997328/string.txt)

AND FOR BETTER UNDERSTANDING THE IMAGES
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/1997331/WeakAuras.zip)

My weakauras SavedVariables
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/1997332/WeakAuras.zip)

I already tried everything, but I did not find anything to help me. My knowledge in LUA is very little.
Currently I use the latest version of WA2 for legion, I have also done tests, only with WA2 enabled.

this is the original link where I got the weakauras codes:
**http://www.wowinterface.com/downloads/info23510-SilverUI2.html#info**
this is the video of the original addon author:
**http://vimeo.com/118511375**

Obs: notice the holographic 3d model entrance effect, on the left side, when it appears in combat it, it seems to come up spinning, this is what for me does not!

![print](https://user-images.githubusercontent.com/38500821/39954331-9a30b168-558b-11e8-85fe-b60211083967.jpg)
[Simulation correct effect.zip](https://github.com/WeakAuras/WeakAuras2/files/1997341/Simulation.correct.effect.zip)

Sorry, my bad english! Congrats for ur work.

**Comment by InfusOnWoW** [comment]
This isn't a help forum. This is a bug tracker. As far as I understand you are seeking help, and aren't trying to report a bug. The best place for that kind of questions is the WeakAuras Discord: https://discord.gg/wa2
