### ISSUE TITLE
Dragonriding load condition is not set on login

### ISSUE THREAD

**Issue by EJ-K** [WeakAuras/WeakAuras2#4120]
### Description

The 'Dragonriding' load condition is not set when you login, so any WAs which require this load condition to be met won't load until you dismount and remount.

### WeakAuras Version

5.3.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Example WA: https://wago.io/dmui-dragonriding
2. Login, check 'Dragonriding' load condition is set to true.
3. Mount up on dragonriding mount.
4. Relog

**Comment by InfusOnWoW** [comment]
Already fixed fro the next release.
