### ISSUE TITLE
Save nested group settings after update.

### ISSUE THREAD

**Issue by Mistrick** [WeakAuras/WeakAuras2#4127]
**Is your feature request related to a problem? Please describe.**
Annoying to change the coordinates and scale settings for nested groups every time when updating WAs

**Describe the solution you'd like**
Add an option to save nested group settings to the WA update window.

**Comment by mrbuds** [comment]
Tick option "size and position" when you update

**Comment by Mistrick** [comment]
I don't see this option.
1. Changed scale and position for Icon group
![image](https://user-images.githubusercontent.com/4307674/206477292-51b1c2f7-445f-42a0-9c47-4cc3f969ecfb.png)
2. Update window with all checkboxes
![image](https://user-images.githubusercontent.com/4307674/206478113-6eaa60d4-c536-42c6-88d2-c70db05da7ef.png)
3. After update
![image](https://user-images.githubusercontent.com/4307674/206478453-dcebbe13-a939-4793-85da-3f7d6e507de0.png)

**Comment by mrbuds** [comment]
If i make a group or dynamic group + an icon, export, edit position offsets and scale then import it goes back to what i had.
Can you add a minimal reproducible example with export strings for before/after?

**Comment by Mistrick** [comment]
The option works but may change the name to inverse.
Something like "keep my group settings" and off by default
