### ISSUE TITLE
Convoke the Spirits not tracked after spec change

### ISSUE THREAD

**Issue by zeroeden-69** [WeakAuras/WeakAuras2#4128]
### Description

What is expected?
Convoke the Spirits to be tracked so it can be used on triggers like "action usable"

What happens?
Convoke the Spirits is not tracked after switching specialization. All my triggers that reference convoke the spirits stop working, the action is clearly usable as I can still use it in game it just stops being tracked completely. All other triggers with identical parameters sans the spell name continue working as expected.

### WeakAuras Version

5.3.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [x] Yes
- [ ] No

### Lua Error

```true
I see absolutely nothing in console or similar it just fails silently
```

### Reproduction Steps

1. Create simple trigger for convoke the spirits from icon template. As the trigger itself pick spell -> "action usable"
2. Test to see that it works as expected
3. Switch to any other spec
4. The aura should stop working

### Last Good Version

Unknown

### Export String

```true
!WA:2!DrvWUTTrqulOeyuwaJyfxJeGEqifTa9IrHlsqBpvrvjBhOi5sshBFPsljhkU1u7YU7sjB3trhkYz9jOZ9K(e8xabrr(a8H(b4B9wNDPOBC5bYzMD4mV3SZm162ysJWgHV)lwsd4mxEMia(8nkizQyUyqQIYzslXvdIIKG6WFK)1Fyd8zfHfGNFmNYu(T703RJtraNNeYNXCNrtHr3uP2jCmelibMi9khPIiuw2ugvz5hHFKXwZvc64XGqU1xjwl(32QRsbhzkKKCRmZhMcmLBwue9YvdB3Y1BORxlhVfgh6tMap7X)tC62zsy4yGbcAGBmF2a2OIhOER08P9ASzNHWWpnHCfikeajXTkCPpTnNnLFb0ufdnDtPcQswOd)9zC0CJ4rHslhd8kAzizZtKe)e4EuFSaqu74ECNE9Cy4pkTwOdKclkxmAzi4J0YdzR4Wo9oU7j9wKXwxfSs3wx4McEL6VHhc)5g3HfDqWijVflzyc)97UaG0wiAcuoeecXlKqsK5Yj)XycKevMGOG4LiMCGX6BIFy38TkqvFeeJf8mw473jTHcUunugtWIZzLx51sFUXO5vexmHGoSwWMXzWI7p(fFPm9jFueAZt4IxxRwT63wATcu2ToXBq6tngXgnogkAWP0qvSDlu9UYCrVecngFxrz325Rr0nMZ)1mPIgDfsqbxHKZdnA3Fq)o5BjqEP9zPXXadmQJplwtcMk9jDf0RB(ZzKqSWqA659aUxLPcJTzCr4Pcs68txlucGPujfVNhTMZF0er62h1VFhNH2d88g8gNJo4qVI7tTl9A45Rz0zpip6tn9bdoXR3r978HIXj8zDfWVLbSGRo(rFZE7)Ys2PpyL(vveMRv0)CHFMsXzdMccSTEP2CpGnwf)zg)Ry2cTs77Rm3GnKhuzj2wFySXf3ascu3aeVyAWfmqkRBoPhfL32KaBSUaIy)yGoow9o7eojSRTej6UotYsuulBDZ5U5NB5eKqKsTKVcJmtPfxkm9KA4BR3cLUt1Yd9L6prnZtHXIlR2c9ODAQ3cnVYTrlimQUlIZEv(N0nFR89UbisWvjmCFZIq9aaE8q9AfHeWSekNR9rN189SNqOmZpMhSzEyoKhHIF6)3I91C(KAoKK0ys9LkEW0YrWNv7pw(cA4nEGu1C9MdN)RXBvKaN7r0G9A1VR8UVR2Ko5(UTD60PVpcPi6yR9ZOHR6DGD)V77NE(RJERGY0jbItBGxsvBUWnb4OomYzMzczPMp0YL1ROSYXtuZk)xg1q68Y9(292VX0)6S)9p
```

**Comment by zeroeden-69** [comment]
Forgot one detail. Reloading the UI does nothing to "fix" the problem but if you re-log it starts working again. So the workaround at the moment is switch spec, relog then its usable again. Naturally this is a tad bothersome, but there is a workaround in case someone else is suffering from this same issue.

**Comment by InfusOnWoW** [comment]
This sounds very much like https://github.com/Stanzilla/WoWUIBugs/issues/354

The workaround is to enable the "exact spell id" option for cooldown tracking.
