### ISSUE TITLE
progress bar delay (castbar).

### ISSUE THREAD

**Issue by dnlpz** [WeakAuras/WeakAuras2#4129]
### Description

Since today's morning (08/12/2022) i have had a very noticeable delay on castbar's progress bar at its start and then, obviously, the progress bar ends before reaching the end of the castbar. No matter what its done, the issue persists.

### WeakAuras Version

weakauras 5.3.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

.

**Comment by InfusOnWoW** [comment]
As I already told you, that's an already fixed issue. The fix will come with the next release.
