### ISSUE TITLE
Custom trigger "autoHide" option

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#413]
_What steps will reproduce the problem?_

New Aura : 
custom - event - `PLAYER_STARTED_MOVING` 
trigger: `function() return true end`
Hide = custom
duration info: `function() return 5, GetTime()+5 end`

_What is the expected output? What do you see instead?_

Expected is that the duration runs when the event fires. Then the trigger untriggers at the completion of the custom duration. (autoHide)
What happens is the timer ends and the Aura continues to show. 

This was discussed in #wa-alpha-testing. 
Ideally, in my view, we would have the option to set a custom trigger to be autoHide or not. 
Infus suggested that this option might fit into the functionalities of status and event type triggers, with event type triggers always working with autoHide and status ones never autoHide.

**Comment by InfusOnWoW** [comment]
Is now implemented.
