### ISSUE TITLE
Top to Bottom progress bar with icon bug

### ISSUE THREAD

**Issue by phepa** [WeakAuras/WeakAuras2#4132]
### Description

If you make progress bar with :
orientation: "Top to Bottom" and Icon Position: "Bottom" 
or 
orientation: "Bottom to Top" and Icon Position: "Top" 

the progress bar starts shifted (seems like elapsed) with empty space has width of the icon.

![image](https://user-images.githubusercontent.com/41948953/206582908-198d143a-f477-4194-bc16-cf93301c0d60.png)

Import string:
`!WA:2!nxzZZTTXzyCHHJLtWKXrIow115Jr1TvJDCSQlTTg7MOOsqrkszkszqOpIRBexaSKawGaWlwQpOAou1oD0zDPNlp1d5e7)az8TC7TAYPEuh696)c67UaKuY21o2JpuEGCXlxSa7ZVNN3vz10r63E6BoDM0TsBN2(Gp(itI1M2SGWCbEbSftLk1YPUX03(yZaMnLPL8NHJP552PdHzpPrqGh3nSlpWAlklYnW)D267y7uTrJikV43T)xd)9rgzeZ473PB8V5TBsdhV2JBty0jl02ZBY1CC50UmAtCbm2nKQ3Kf0omz61C7qptV4XXVxkkkPoI0M7eWQgYX7js9qIVBlIy8m6rCcJx4juseTgNr9BYDoRghxwn)aF6r2TzYjUHOelIAf4BhTVy2IhnCETwex)cW4NfsdNh(a4cWeW5nB467g58SLzel5ZFgymv4IQA4K4Q7ZzUnBIl9LMILm8V01MA2UrdXtGvmF5LlSsziTobFvYSFui1ZRKDK6XrTnPBr951WP6UtVnYLTMXg1mYQBO1gxzZqpYUuMUpPfnsvxovZIuIh3zWTUmJI3QETLZxU8HT9tE(QSD7ZKL)R)dejJ8uxFoL5t8wnMB71J4BHc6Yb4FyMlFfJ86hgr9AilatFzx7NO1gxl7j5UTOSEU(ncyXsUAVgm8vcfBcNK6PXlubrjX(1Swo985RKqWs(4Brktu0B42uvpYI4rt1fF71L0ps9jXZl(19D7kOJBmJ18ci2fm54D4ZNqVvB06PQHQN1eWSQ6wEKOiXiTi0XigKPTRDVzYC174vrVyq11sB9OdY0nkKW2CnxBUZf66IlFTG2mlQcmQcCnf46W0hjNHEaxU5uch)uxVuGnvl7kgv1e3Sd8HNBk4Joym4xQIavIYdBhr3a1cRnRd)m4YWph(fHJlQ1K6tzUw1Cc2UQF9Jo1Lhhj)jhgOSd22hUcC1JyiARjwXkOuQCKyjI6FzDys1dhCLYH8aoTLqUpdmLUH4c58huUo8XWNaFQA44cl7wuJyJHy38TJi1HnS6h6tbF2EWVcMEFtssIR4C)7vLFko3)6bYpfNdKF(NPqRDeHlcvuNEsPQORTn1xVs(vZR)ezLyA(vkWD(0jG0hH4w0PrKY9TtkGUjACbthQBth(3dF(QsPuc26Wxiqkm3uMrU(n9qBvXSlLTIO2xk)NFR47JLpon0Hyl2AzYo)8HJHlsw7h1oItTP2lr2Xj88nzeBx0gvLj(wc2UfRQx6bvRyKT8H934zq5qjf8tL57ljI4W7JJli7bGTcsAda)KNRYfFUkNt9zFtCr7Jkt0eaFEq2Eo3pi3JN)UZS7I39Pd1NH98ouIPixBQUEPfkAa3eULoXl0HKkr4Lc3SmoDheiu28lixHygyexm8kLej)gel6dZrI4OyQrypCLsxF4vxVMuf7ee0srxEZoWzWo7ytanonIhNHYn0VK5S6BlsuZEsCVUcmJkZ1xCYaAncgk1HJHodJs5YwEJsvWH1Yd)gv4xprp0eyrZl6Jfv)yQpX0JUqcPCoidK7cW8F0iOsMKuH8kqbyHe(CrjI6NhXaesGsWIdcHW9QdLHLej1kkqvrcsgkUpgzaDOwDyzfmHagF7iWkNmhaR(sdaWAoWwXZ)bjoC43j(6HWVxyIHVUV59ltSWWgq9bwwGaMGLd8noOca)H6joStFqJWH9mvU4ZvPyDOj6Oahy07JspSj4b7OaBpl4pleaHiMGhdmGhttyD4RqIAki6KzGwPe(jisbDIRzR3(ELY6V9nSHDDGhjTFqhypbNAehkSbAcsu()qImyJDZ3oqPOZBoxsGcseKgBQvoFbdbuqAKWLe3ZZWgbksGscaY27E3LFRMUEbrlyjaZO)nOZ(9ZsVi2SZlGnOnPpseI9RgjcW9sqcQr)4cj4(5vWIHu4e907ZcCt1F)9wPH8O)N(Kr0ujBp9TlUPrN1QCNI5XOZFSVOl0)eo16umAGfBgjTqCIqnbLiRr80b(tXn2eoOpBVbi5Ax9)bpea4e8aHqcoeiyapqcmehXhR)wJhZ(gXdmvEsKm6F(9oT0QTttkDXIgHb341tAV1aP97pT0IU6oHPhEK9PpizyB0xFFXWZzeBJRv(1TV2qOjO5B9tAe6XRGAV0oAVXDXIvv0CH(vu9t47ok9pPjbpiOEHN2maP3(f1xlxq4koK1V3MZptCWHE6UzP36hw))(d`

### WeakAuras Version

WeakAuras 5.3.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Make any progress bar with:
orientation: "Top to Bottom" and Icon Position: "Bottom" 
or 
orientation: "Bottom to Top" and Icon Position: "Top" 

### Screenshots

![image](https://user-images.githubusercontent.com/41948953/206583020-3845c751-dd5e-4676-8bd4-bdce9a1f331e.png)

### Export String

```true
!WA:2!nxzZZTTXzyCHHJLtWKXrIow115Jr1TvJDCSQlTTg7MOOsqrkszkszqOpIRBexaSKawGaWlwQpOAou1oD0zDPNlp1d5e7)az8TC7TAYPEuh696)c67UaKuY21o2JpuEGCXlxSa7ZVNN3vz10r63E6BoDM0TsBN2(Gp(itI1M2SGWCbEbSftLk1YPUX03(yZaMnLPL8NHJP552PdHzpPrqGh3nSlpWAlklYnW)D267y7uTrJikV43T)xd)9rgzeZ473PB8V5TBsdhV2JBty0jl02ZBY1CC50UmAtCbm2nKQ3Kf0omz61C7qptV4XXVxkkkPoI0M7eWQgYX7js9qIVBlIy8m6rCcJx4juseTgNr9BYDoRghxwn)aF6r2TzYjUHOelIAf4BhTVy2IhnCETwex)cW4NfsdNh(a4cWeW5nB467g58SLzel5ZFgymv4IQA4K4Q7ZzUnBIl9LMILm8V01MA2UrdXtGvmF5LlSsziTobFvYSFui1ZRKDK6XrTnPBr951WP6UtVnYLTMXg1mYQBO1gxzZqpYUuMUpPfnsvxovZIuIh3zWTUmJI3QETLZxU8HT9tE(QSD7ZKL)R)dejJ8uxFoL5t8wnMB71J4BHc6Yb4FyMlFfJ86hgr9AilatFzx7NO1gxl7j5UTOSEU(ncyXsUAVgm8vcfBcNK6PXlubrjX(1Swo985RKqWs(4Brktu0B42uvpYI4rt1fF71L0ps9jXZl(19D7kOJBmJ18ci2fm54D4ZNqVvB06PQHQN1eWSQ6wEKOiXiTi0XigKPTRDVzYC174vrVyq11sB9OdY0nkKW2CnxBUZf66IlFTG2mlQcmQcCnf46W0hjNHEaxU5uch)uxVuGnvl7kgv1e3Sd8HNBk4Joym4xQIavIYdBhr3a1cRnRd)m4YWph(fHJlQ1K6tzUw1Cc2UQF9Jo1Lhhj)jhgOSd22hUcC1JyiARjwXkOuQCKyjI6FzDys1dhCLYH8aoTLqUpdmLUH4c58huUo8XWNaFQA44cl7wuJyJHy38TJi1HnS6h6tbF2EWVcMEFtssIR4C)7vLFko3)6bYpfNdKF(NPqRDeHlcvuNEsPQORTn1xVs(vZR)ezLyA(vkWD(0jG0hH4w0PrKY9TtkGUjACbthQBth(3dF(QsPuc26Wxiqkm3uMrU(n9qBvXSlLTIO2xk)NFR47JLpon0Hyl2AzYo)8HJHlsw7h1oItTP2lr2Xj88nzeBx0gvLj(wc2UfRQx6bvRyKT8H934zq5qjf8tL57ljI4W7JJli7bGTcsAda)KNRYfFUkNt9zFtCr7Jkt0eaFEq2Eo3pi3JN)UZS7I39Pd1NH98ouIPixBQUEPfkAa3eULoXl0HKkr4Lc3SmoDheiu28lixHygyexm8kLej)gel6dZrI4OyQrypCLsxF4vxVMuf7ee0srxEZoWzWo7ytanonIhNHYn0VK5S6BlsuZEsCVUcmJkZ1xCYaAncgk1HJHodJs5YwEJsvWH1Yd)gv4xprp0eyrZl6Jfv)yQpX0JUqcPCoidK7cW8F0iOsMKuH8kqbyHe(CrjI6NhXaesGsWIdcHW9QdLHLej1kkqvrcsgkUpgzaDOwDyzfmHagF7iWkNmhaR(sdaWAoWwXZ)bjoC43j(6HWVxyIHVUV59ltSWWgq9bwwGaMGLd8noOca)H6joStFqJWH9mvU4ZvPyDOj6Oahy07JspSj4b7OaBpl4pleaHiMGhdmGhttyD4RqIAki6KzGwPe(jisbDIRzR3(ELY6V9nSHDDGhjTFqhypbNAehkSbAcsu()qImyJDZ3oqPOZBoxsGcseKgBQvoFbdbuqAKWLe3ZZWgbksGscaY27E3LFRMUEbrlyjaZO)nOZ(9ZsVi2SZlGnOnPpseI9RgjcW9sqcQr)4cj4(5vWIHu4e907ZcCt1F)9wPH8O)N(Kr0ujBp9TlUPrN1QCNI5XOZFSVOl0)eo16umAGfBgjTqCIqnbLiRr80b(tXn2eoOpBVbi5Ax9)bpea4e8aHqcoeiyapqcmehXhR)wJhZ(gXdmvEsKm6F(9oT0QTttkDXIgHb341tAV1aP97pT0IU6oHPhEK9PpizyB0xFFXWZzeBJRv(1TV2qOjO5B9tAe6XRGAV0oAVXDXIvv0CH(vu9t47ok9pPjbpiOEHN2maP3(f1xlxq4koK1V3MZptCWHE6UzP36hw))(d
```

**Comment by willjenkx** [comment]
This bug is not unique to WOTLK. This is also occurring in DF in all orientations of the progress bar.

If the icon is removed then the bar is "fixed". It appears that there is a chunk of progress taken out of both ends of the progress bar for the icon.


https://user-images.githubusercontent.com/19401799/206584637-9bb95dba-b898-488f-9524-865bd2fc3718.mp4

**Comment by InfusOnWoW** [comment]
That will be fixed in the next release.
