### ISSUE TITLE
Progress Bar doesn't account for icon width

### ISSUE THREAD

**Issue by Odjur** [WeakAuras/WeakAuras2#4133]
### Description

In previous versions, progress bars would start after an icon, but now seem to be using the space that the icon is occupying.

### WeakAuras Version

5.3.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
No errors.
```

### Reproduction Steps

1. Create new progress bar.
2. Show icon and set icon position to left.
3. Set trigger unit to target and aura type to debuff.
4. Enable aura name under spell selection filters, using Agony for my test.
5. Cast Agony. The bar will continue on slightly past the icon texture.

### Last Good Version

5.3.1

**Comment by InfusOnWoW** [comment]
That's already fixed for the next release
