### ISSUE TITLE
Progress Bar and Model now requires model behind background

### ISSUE THREAD

**Issue by wing5wong** [WeakAuras/WeakAuras2#4138]
### Description

I have a progress A progress bar containing a model used to be configured in this order (this is the expected ordering in my mind):
![image](https://user-images.githubusercontent.com/4406993/206789490-3233bd89-a2d3-4745-94b2-7644d2eb10ec.png)
In this state, a model could be used as a backdrop for a progress bar and have a foreground bar color visible over the top.

The bar color starts as transparent, and then on conditions is changed to orange/blue/green.

It looks like this before.
![image](https://user-images.githubusercontent.com/4406993/206788988-bdfba431-dba8-4de3-8aff-97166d9ce68e.png)

on a trigger condition it looks like this
![image](https://user-images.githubusercontent.com/4406993/206789323-d1d4ebc1-d815-423a-bca4-3d0a9a795920.png)
![image](https://user-images.githubusercontent.com/4406993/206789374-0288fafc-bebb-4690-a2b2-ca2b9c6dcf8e.png)

Since 5.3.2, to return to this behaviour, the model must be placed behind the background layer to work consistently. (this is an unexpected ordering in my mind).

![image](https://user-images.githubusercontent.com/4406993/206789554-f54ae422-203f-48bd-9892-8e371051c9b8.png)

here are both change and unchanged auras side by side. OG is in BG/model/FG order, new is in Model/Bg/FG order
![image](https://user-images.githubusercontent.com/4406993/206789880-5723bc04-330f-4db8-b6d5-f5c2d2c005e0.png)

Occasionally, in the expected order (bg/model/fg) the color will work as expected, im not sure what triggers the working state again

### WeakAuras Version

5.3.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
N/A
```

### Reproduction Steps

use this aura https://wago.io/J5V9sTM0F
enter ecplise states (solar/lunar or CA)
observe bar color does not change.

reorder model behind background layer and repeat test.
observe bar color changes

### Last Good Version

5.3.1 (prior release)

**Comment by mrbuds** [comment]
Using alpha version of weakauras it works as intended, but you forgot to tick the option "Clipped by Progress"

**Comment by wing5wong** [comment]
in this case i dont clip the model.
the model should cover my entire progress.

**Comment by mrbuds** [comment]
> in this case i dont clip the model

That doesn't match the screenshots included in ticket

**Comment by InfusOnWoW** [comment]
You need to provide a simple aura that shows the problem, not one that contains custom code that changes the region in various ways.

**Comment by wing5wong** [comment]
hmm, ok.
i feel like the presented issue is not being understood.
The issue isnt related to ticks, or to the model and its clipping.

The ticks are overlays and not edited directly on the region.

The foreground color representing the progress value does not display - i.e. the bar at the value of 43 in the above screenshot should be orange.
this worked until 5.3.2 where the ordering perhaps changed, and now works inconsistently

Il reduce it as much as possible. and feedback further

**Comment by wing5wong** [comment]
![Wow_yTEI2Cvzax](https://user-images.githubusercontent.com/4406993/206810232-87af59dc-06d5-4f5b-82d5-6df9b57d2bd6.gif)

top image - model/bg/fg
middle image - bg/model/fg
bottom aura - model/bg/fg (the full aura)

reduced aura with issue https://wago.io/auFsQHmJr
reduced aura without the issue https://wago.io/b3wB86Ngt

only change between these 2 auras is the position of the model subelement

**Comment by InfusOnWoW** [comment]
I'm not even sure after all these messages if the overlays are relevant. If the overlay color changes in the conditions are relevant. Whether the color changes in condtions are relevant.

Please create an aura from scratch that clearly shows the problem and has easy steps to reproduce. 

Again, I stress, MINIMAL aura that shows the problem.

**Comment by InfusOnWoW** [comment]
I can at least confirm that it looks different in the alpha compared to 5.3.2 Whether that's the intended look.

So I guess it's fixed already.

**Comment by wing5wong** [comment]
to be honest im not sure why it was addressed as a model issue, or an overlay issue.
the overlay works as expected and is only to place a drak opaque 

the issue presents itself in the BAR not being shown.
ive removed even more from those auras and uploaded new versions at the same link.

im not sure what else can be removed to prove this issue at this stage - its just a bar with a value and a total

![Wow_y0aMcIQEm4](https://user-images.githubusercontent.com/4406993/206812688-109ccc0e-d1da-4615-9534-1394a1018caa.gif)

**Comment by mrbuds** [comment]
We don't ask for more screenshots, but a MINIMAL example without custom code and conditions

**Comment by InfusOnWoW** [comment]
I think I understand the aura now, and I'm confident that it is indeed fixed already.

But for your next bug report, please create a small reproducable exmaple. You haven't succeded in that here, because you somehow think that you need to retain as much of your aura as possible.

**Comment by wing5wong** [comment]
Thanks for following up on this

I believed the screenshot showing the ordering was clear, so was surprised comments were related to clipping or ticks or editing regions were produced. 

in my mind in those examples I’ve removed everything that was irrelevant and left what reproduced the issue clearly - there’s definitely no intention to keep as much as possible. I agree the initial example still maintained some unneeded areas
