### ISSUE TITLE
Incarnation: Tree of Life

### ISSUE THREAD

**Issue by Kazik22928** [WeakAuras/WeakAuras2#4139]
### Description

I am making my updated Dragonflight weakauras for Druid, and I'm making different icons show when character is in different forms. Base healing abilities are shown while in caster form, travel form, treant form and mount form, while I hide them while in cat, bear and moonkin.
Thing is, when I **activate** **Incarnation: Tree of Life**, weakaura treats it as a new form and disables icons that are configured to show only in certain forms. I am unable to allow icons to be shown while in "Incarnation Form".
It should be either added as another checkbox to **Trigger**: "Player/Unit Info" / "Stance/Form/Aura"
or treated as subvariant of treant form and show the same icons.
I know this still can be done in some capacity with checking "Inverse" and choosing only forms you dont want to see certain icons in, but it feels more like a work-a-round than a solution.

### WeakAuras Version

WeakAuras 5.3.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
none
```

### Reproduction Steps

1. Import weakaura code I pasted.
2. Have a Restoration Druid with both Efflorescence talent and Incarnation: Tree of Life talents.
3. See how weakaura shows in Humanoid, Travel Treant and Mount Forms, and not shows in Bear, Cat and Moonkin Forms.
4. Activate Incarnation: Tree of Life ability and see weakaura disapear.

### Screenshots

[https://imgur.com/a/bqVCet8](https://imgur.com/a/bqVCet8)

### Export String

```true
!WA:2!1zvZVTXXv8SMnWOmniwsrckYXgms1mwTkkwYwUiPheePPIKQSK6UuX2OnH7xd3DSwo7Kz2Ls09u4HcDMafOFa0cWZfOfSP)d4JfOapW0MJ9GU2B6VG(Mzxkz5knasC238(AEZV3hgRpERX9h3)4pSp1lMzfNk8igIJ2TztjjXq0jFZahMxySyVyklXTATDQxZCOxCCKF8HmRdPCIn)gEPYK4w1jhLSp33jH4MQ)5LJ4RMFaju44LqJzYhAktCejtj8JBeefFyOBtkJkdlwb)jPSBMY4DDsfoniS2lkibOClIs5DG8tTijAF5UZwz36139XMB(zBuF2fk9ASVqPx787TqPLMV4vRuRqh0vZU03DPfk9rlnFp0dZ8MWUjcAqari)JLf5Bp(gdtLKgsojkAhNwe7kjD4KEEXTCDsIIde6t203DPhSYY3BfrkJ0MWsmtOTi(99XGuZM1rjeBuB79wF)T76J(Mkcn79VNPM1(v16Q02XbNitD102tqAspY0AVABVDLumG5YJC6qedoZx203UB(gzXt0K1VT7JmBBYqpfjpsDwOtqpAyJQRzvVH1(vRwZYQ)58dZ17S73WAnBgflispcZJ0lLLhhkwgM44j6QmuZyrRq4wJV0WacJiOEwHyiLDIu)t1C0auc(a4hBatcZcVxfN0Ky4dlwrjBzxjLferky2knkHU(1TFB73Y2WgUn)gwjiqK8XRJS9XRHrk(yklEb7ypuqCISg5WgW7Ad3PiC3b5xV6RzwhUj8(6yfL1gFojH9uFKGGZdSr)zo4JkoWNkFEkdrRTjW7WhphDNDBX3cQhFHM6ZJz3npimFXs4sqssfSs50(fl)f)0IeMpFmhTUY1WJJ9j)534uectemNOph9cur)QtpGq4RHrBVetfmiSNKe1ud1H38ezc17GopkhHe2hF)m1iy5wtbtoe)0fVbbI4uM)XZXhpbZfBi1q6NMNiZ)HAI6)Pc2ojn4nCPbnyPTCjICA8XwZ1vqAtX83D0hi538semWZVHNJmjKFJxXwvJreYwgggfonJD6re)Nq9tc)6l18QCHgrKahVonqWvSWUViobnTQwsLD2DNAxQy(epAlNOgCbUrf9m4ZCf(i(NDFnzpTVvax8BFvxOqhgJefEH43ZYJFd10omw4)ee919j5BgMRgwIozE39RV9MOBx6kmri1N04ferC45cArFbz(Hz1zp716wxIc0pVnuLzm1rl(7DjmLTbM5KS7W5Gi(eAkQeoKbQN(DPYA4N52E0n9LA(Eoc7Pn7GY9)hUYkBM)vfwmJatkqqOIN8G3fVo9o7YYNCnppmiWsCIkHvZKQ9EDUGuJCKlnkQXmTI9BG5cQMpVICJUOZFvI53bR)r9AKeIgoelhzCPybnVzFzW)GRIHZqFf6DglZEhEw0RnEIBeX(4PHAgxY70OGh4bSzVJe2uN1aFXGxPRf8LqdyRVgSnah4nHTHhJ1m9H90GyOjeargGPbCqhWcQdXHWZHVc(LWmqRcWtNdEMbSp85F3qvx21fKVkvfO377DVfxELkkA2VeR99zr5PT2Dv00G41QAfszK(kcBtybjHtoqTF07sVGrcTvHnw9FVVETXQ)NVuVkKHfu8OLAegq7h1dXczmIuwqRelphSCVE72OfLJPTzfm3IicDdj0GWK1Qef74F8ycS3aMbWNcEqrtVihPSmCFZhzU)MpcP0xxhh1gljRMUMd7kI4iIsIU5ni9SRiX8nfjrg7lR2FIMDeh5Rzc183cpyQV12nJhKLYVJ90x7NSckE25FFLr9Py)tpSzvhLs6XBZpJ)I8XpZnotVO)44Lz8xGznyl6RjAMnyKIy)SXsupcvutLzEOkh9N3ZHrBPR8)q4Tw)LehjXkrOFyUocj8goA0bDTbSRgkQVSRIpLQaVkTCOS1HFRMB43b)E4pG)(2VoLUJgylu1dunyXMOMM(A)GDW5vKojkRqcDrAnPbfR8I44wg83DKqQA2pIkDqyVFiSew2n2RDw3TPn(19NL6ZN8cZqusP9sZT0GMcSDnEJCsCUUPtep0PWPzz0RRorDhCTQAwR2o6y6ObjWoPMQAalNs9h8SNVYrUFs1A)m5Nig1B388A(WVXUVkQq1ZG(JkB6fs8o4HWef622rqvoDf1ykMTDIsX5GvTcciYpTmmWUlxeJH1KoQ2Ul(GfvquK(wBS6)9M61gR(pVLAD7nw9FmJADZcW3C65mRtvuAc(g4pvg(lOzF)3a(RDPSSPfHbgWFBMPWt)7dOSScdOBwEaU1JutnOM0MpnnGHXUD56RGMAnHiwiThI10XGv(jfhxAUYI3FXLhV9)6P)V)
```

**Comment by InfusOnWoW** [comment]
That's a bug in WoW. 
We use GetNumShapeshiftForms() to determine how many forms there are and GetShapeshiftFormInfo(#) to get informationon each form. And GetShapeshiftForm() to get the current form

Tree of Life appears to be form number 6, that is GetShapeshiftForm() returns 6 while in it.
GetNumShapeshiftForms() returns 5.
And GetShapeshiftForm(6) returns nothing.

Thus unfortunately you can't use the form trigger for that purpose. 

Your options are to use a custom trigger or check for the buffs of the various forms instead.

We won't add a workaround for this issue.
