### ISSUE TITLE
Bug when anchoring to Vuhdo

### ISSUE THREAD

**Issue by Pinkis333** [WeakAuras/WeakAuras2#4142]
### Description

I've made few dynamic groups to hold some basic auras, that tracks buffs, CDs and such (only basic triggers). I've anchored those dynamic groups to vuhdo frame "Vd1" and it mostly works fine, except when I first load into game (or do "/reload") - those groups are floating in the middle of the screen, aka aren't anchored to vuhdo frame. If I hide vuhdo frame - dynamic groups hides as well, so "Set parent to anchor" option is working. 
If I open WA options ("/wa") everything falls into place cause I believe groups are recalculating their anchoring. Maybe it would be possible to delay anchoring so that it only happens after everything is loaded? Or listen to Vuhdo load event and hook on it? (I'm just guessing, don't know how internals are working)

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
No lua errors are happening.
```

### Reproduction Steps

1. Make an aura
2. Anchor it to Vuhdo frame
3. Reload UI

**Comment by InfusOnWoW** [comment]
I cannot reproduce that with these instructions.

Anchoring an new aura to Vd1 anchors correctly on relog/reloadui. So we need more information on how to reproduce it, e.g. the exact auras you are trying to attach.
