### ISSUE TITLE
'WeakAuras' tried to call the protected function 'OverrideActionBarButton5:SetAttribute()'.

### ISSUE THREAD

**Issue by neuvo123** [WeakAuras/WeakAuras2#4143]
### Description

Getting this constantly and have no idea whats it about and Im not using the "PressAndHoldAction" either as I dont play evoker, sometimes it breaks my raidframes and have to clear it with /reload

### WeakAuras Version

Weakauras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
[ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'OverrideActionBarButton5:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>
```

### Reproduction Steps

The bug appears random times I cant reproduce it

**Comment by InfusOnWoW** [comment]
Nothing in WeakAuras does that.

There are two causes of that: Either you have an aura that is buggy and is spreading taint or more likely you are encountering a WoW bug. The game was released in a buggy state where unfortunately the game bugs out on e.g. using the edit mode frequently.
