### ISSUE TITLE
Show spells "%spellCount" with "Disabled Spell Known Check" when spell is not known

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#4144]
### Description

It seems like currently in weakauras a spells %spellCount will only show if the spell is actually known. 
My logic tells me that the correct spell count should be displayed when you select "Disabled Spell Known Check" in the trigger.

Also, the spell count is still shown on my action button, even if i dont have the talent providing the spell count selected. So the information from the game seems to be there.

My example is a implosion weakaura which shows the spell count of my implosion (number of my imps, which is quite important information, even if you dont select implosion talent)

### WeakAuras Version

5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Log in on a Demonology Warlock
2. Import the string for the example weakaura
3. see how spell count is correctly shown with implosion talent selected
4. untalent implosion -> spell count will always show 0

### Screenshots

https://i.imgur.com/kJubOWQ.png

### Export String

```true
!WA:2!1vvZUTXTw4RJVf(wHSWwnXXXPlesW1ibb1)M60Bkqb0OmQ1Tk2gJKRtrrHgoZWrKXZqYqYXYkENqqrwuCxOv9NDc5jqa9fWpbde6tGFe8dqrpKJSJtqIwOHNdp8WZpFFhov9YPLJkh9QVuYZ0jugwUZETAS12UdPHCwtEMmepL8ODIJvy9VC1rruLib1Rf(i94)7AlRe4KKA8mMw2RWMxE1riwiHl3LtzANgU1BnoKZtI4Dzn7sfyFrLl5K2XCzks3w0wttXtKMsmByMsZtnwSNicPXbz2pRNjte3IO1c1JwzLUOo8LP8vC(2h(CV4AFZdxznjkut5m1MEknsQl5qzu9sbfU72LkniI3UqGeed7PiL6RL0oDWs1)Fj5KLV6oEAWth4GY08bOmjIHsXQf92y9n(FRkHuzhwsp)b20FByRfUYF)NNLPWTJGinoUwcsPigfUhbbutJzBf57HpeZ0IBwBs9OYUsEhjwPQCxRj370qEAa0eEcshsWQHkcVBdExSspW4CBm5FkS8RH2LODOPWtmYTrbkUm4j8iS)4oyOnsdBchEhM1hvt6I6PovLfyJGDL4y6rEn31TrJrwhdbKMkixyrtijOhnQDTQnB1UzRQETKzm7o530ROwiMRrgdjR4MkGiuMAYSRzCgTdJlX2e67yqw6pSOO0QNal)g3g7wFVgozqBjWacWshnSHNTukHZBkNKtm1CRkAKAXGnEW6FXApWMOVbXrg(M1LxvmNz33k197BuzUj)XsmkP55DRbBLks4kaNm(cxA073xv0PuLkChigsJPHwNq6hbbLbDvETHMeQ4worz)ufWDhIhNw05k2kVU4tEtm2Md5psZLL)QbgcJfPvYWOEwgZE61rSEIYtG(f73G3HgkUFS1co7Uto29kvb(jX6mjRYeD)4A)ujmlsmhY6SjoWajMwCR3lLRyHNH5fDgWwXsgk57bMaCthF2bySOQPcO9mznPFxUmAFjs0F)jlKpdcvACV8pEmquao)ocl5Re0XviTPAHjI7)HP7r9aSeuE1eGfqasrpNyotp09iHHwaGw5HfHZ0dbOPhUJX9loF(MJbXaGn0bicSOacM2HODhRiiGy9dfJI(0)Ltchf9QRlPmJDI59sZaCEjlzYaNLerzZ6qdFTnIfz74(dUqNVywlRwctAysAe4is)Zrg(ok6lWZNhusQrja(FDZ6tFBNTuGcouc(1ZMhm)RN1pOWuWY5ndnaFymk)GpkpyrF5l4mma)UIdW0TEEyefyIHqy3ZioqCO4chusgxmTZS2IKpetOHj49OeROaRdqADcM0pKdKxetd30mWvpJVNnmbr5(v9AStTVd8HJKNyV1ay2FmTtjXsVNE3LN6prNddI7(MwxtOI07KZh47g1btCmVK4pP180IwZ0du4Ky7teb1C3ULR3qyEdoAFAKM8YRkMT4nK6sGvA)tCJ9XOdQAMk8OhNLM2RYNvXb4GQHslOWmCXrdrz)ZVBY5VvTfC9lmZ)5lofWQHh07XtiXKpqY18DtU8Jfx7CNAm9Xufkibhre35dJSb8Bi1cCp7sPIjkdAwZZ1D7rXgfnHr6A00oVGZt39FV6YR9G8B6puZdNa7xyQFE4TPrIB8yCkNXt4D69OkW0Rk2aSY6NAEGcUwAOTY5ufe9qjccAAVUgnUdqmAQnH3mFU6JpFewBZqxPcd1Miv(M5hFcgPmHdM1rtMPVrYeT5h7KIOS65)A(Vzml)3Nj)pGpx)D1SEgnAu94NV2MBC4gm6QaNZKda)FUlva2fbxGMmQamudsi53o1utn9qtCqlgEmIYkQLG0sJGLHyxZlpazCHI3wMmMXQ1vk5sfaNT(AA4xzL3NV8glVr5d)RN(pd
```

**Comment by InfusOnWoW** [comment]
You have to enable the "Exact Spell Id" setting for that to work. This mirros how the game api works, GetSpellCount("Implosion") returns 0, whereas GetSpellCount(196277) returns the correct value.
