### ISSUE TITLE
Spell Usable condition does not work with CC

### ISSUE THREAD

**Issue by Revelryfx** [WeakAuras/WeakAuras2#4145]
### Description

Before Dragonflight I would have my spells Desaturate if the condition was "Spell Usable is False" so that when I was stunned all my abilities would desaturate except for those usable while stunned etc. This functionality was broken at some point just looking if there is a fix?

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create normal icon weakaura with a Spell Cooldown trigger with Show set to Always
2. Create condition if Trigger 1 "Spell Usable" is "False" then "Desaturate" checkmarked
3. Then get stunned, or sapped etc. It should desaturate everything except abilites that can be used in stuns such as trinket and monk port with Eminence or mage Blink

### Last Good Version

Before dragonflight, not sure the version.

**Comment by mrbuds** [comment]
I tested on mage to runevery frame `print("shimmer", IsUsableSpell(212653), "frostbolt", IsUsableSpell(116))` and got stunned by some shadowlands rare, both functions return true stunned or not.
But i don't know if that was the same behavior before dragonflight.

**Comment by mrbuds** [comment]
If the game changed `IsUsableSpell` behavior i don't think there is a way around it.

**Comment by InfusOnWoW** [comment]
Yeah, I agree with what buds says. We use the api that the game gives us, and we haven't changed our code. The game apparently did.
