### ISSUE TITLE
(bfa) Specified-Unit related triggers seem "broken" on certain occasions

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#415]
What steps will reproduce the problem?
can't reproduce, maybe pulling mother (raid boss) with the weakaura below might do the trick

**What is the expected output? What do you see instead?**
I expected the weakaura to only show if the specified spellid is applied on boss1
but instead it appears to be showing any debuffs applied to the boss and then suddenly stops.
https://gyazo.com/ff8db54afb17cef933587364e4626c19

I can send you a VoD of it happening if needed. Don't want to include it publicly

**edit:** I found a public VoD of it happening to someone else with my wa pack:
https://www.twitch.tv/videos/262715503?t=00h02m50s

**What version of WeakAuras are you using?**
It happened on beta 4 to 6

****In case you do know which aura is problematic, please export the string and paste it below.****

```  dWt(daGAksA9usTlrP2MqKzke1Sf8BsUjuHFrj52e6YuTtk1Er7gY(fk)eQYWisJdQQdlvdLIQgSq1WLKdsjCvrjhtvDAvwirSuksSyrXYf5Hqf5PGLPkwhfrnrcyQKAYqz6kxui8kOI6zsQUUeBKaTvkISzvPTlP8nkcojfv(SO67eLrsrOPrjA0cPXtqxIIu3IIIRrrPZtu9CP8yk8xOsZp1eoA)Rxx6hFcnc4NTuZKXxpseejGraJAcZfUVGk0GZAN2)irWO0Msu7chbcDJD1CD6YZ9eouyoTnZxkHskqi6wvZKTYkz9Cv2NYQmV9u)W(w9yjHLU8CprnHc6gbrxmJNi0Q8qWCynQP9N2pMGLpsnlhHwLBCVNrwOBeYOATpHwuLm8qeArvYWdzHXUAoHsZXTv5g37zGBbDJsiG6IEJAA)jiGxf85yXIhbYt5Y5iG5zkVVA5vobt0ctbhcMvK5imx4(4KcT(HeD0iGxwAWCcebH5c338QdncsWtRXdheI6xE0rB8LsiO6yuty9GJ2d1eelHDuZXry9GJg1eelHDuZXrWrgQcAE6Wi88T8tO0CCDKHQGMNomkHa29(EgLWKtnbXsyh1CCesQGtnbXsyh1CCesDdNAcILWoQ54i82n2PqutqSe2rnhhHdLNuLkQjiwc7OMJJqvTQ1doAutqSe2rnhhH2zTtnbXsyh1eEdUWltWPecZrucHjZrt(7vZPecVQ0Kl2rucHjZrtoLWXXr4qZtOEWK8u7uiAxNWCH7lOcncwKUEiwC7EkPKra7AMAbzSRMtOhceqfrD6YZ9uJ2Fcjp)uiT8kNWzOqe6g7uOg1eARNg1eAQccJqS4gL2uIeAQccd3Q(IsGaMc3MQGWygoocZfUhbvObN1oTFmlbzh2IsB8LsyUW9jGZcyEGG1kLiTLMDDcZfUhcMUzAdchgbPpXIlGxf85yXIhbYt5YjyOubmLmeLqyUW9iOcncwKUEiwC7EkPKXrOtnbb8QGphlw8iqEkxoT)1Rl9JphHA0(B5ZNJea ```

the weakaura was in this dynamic group when it happened:
https://wago.io/bfaraid1

additional info:

I redid the entire weakaura and used Slow Fall as buff/debuff on specified unit (boss1) -- it still happened 
so it happens even if the spellID is unrelated to the boss

it might be related to a lot of debuffs being applied to the boss but that's just a guess. It would explain why it mostly happens on pull

**Comment by mrbuds** [comment]
i confirm it still happen, tested in lfr, using last git update from today

**Comment by emptyrivers** [comment]
For some context, this issue is still not resolved, despite attempts to fix it. The problem is that WeakAuras only looks up to the first 40 buffs/debuffs that a target has, but the game has no such limitations.

Demonstration (courtesy of @sragia): https://i.imgur.com/jGQUXYo.gifv

**Comment by sragia** [comment]
Tested by upping BUFF_MAX_DISPLAY to something unreachable like 255 and it fixed it. Though at a quick glance don't see why it was bugging out in a first place.

**Comment by InfusOnWoW** [comment]
Looking at the code, it would indeed show the 32th buff, if there were more than 32. Since we upped it now to 255, we shouldn't have that problem anymore.
