### ISSUE TITLE
[Wrath PTR] Item Trigger Cooldown not working

### ISSUE THREAD

**Issue by briancupp** [WeakAuras/WeakAuras2#4150]
### Description

When I imported an existing WA package that works on Wrath Live onto the PTR server I noticed some of them weren't working properly.

I have some WA's with triggers that look for the Item -> Cooldown Progress (Item) type and don't get the proper options and thus don't operate correctly.

### WeakAuras Version

5.3.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create a new WA
2. Trigger type: `Item`
3. Try to set the sub-type to `Cooldown Progress (Item)`
4. Notice that the sub-type is actually empty and doesn't list the options below that it should

### Last Good Version

5.3.3

### Screenshots

Live:
![image](https://user-images.githubusercontent.com/6579154/207484561-f0317d88-c0c2-48da-a17a-2d4b248186bf.png)

vs

PTR: 
![image](https://user-images.githubusercontent.com/6579154/207484626-dffa3466-3807-45dc-8d6c-ca2033069ad7.png)

### Export String

```true
!WA:2!1z1tVTXXvClWeixAeylABg)FWOMOkPKiPizBeeazasAQyNOqQSK2kgbUCND3HChRLZmzMzjfDpvEiv5wbrVhh6w0l9epKlfiavFcgqu0pa6JG)e03m7skKaBEGCM37n)EV538(dNBNCDYfKl4OLhr8z06SyHp(gNXRhQn7H3FyTpUuXh85X32xCyTwTKy1CI(PlgJO(HmXEmcv5vUs1gvCM4ZyrbSE069iCS7Xt3wjOnouG8vegvExhPcjuzlrOevwVwWpYWSducs72yH8xwsKU8OCdikCNQOo4Z(xVbFHyjUzBmfli(1dz9QrDN8R2osc)umQhQV0HchsMDOKJJISa8V)BLu954sgeprg7H7IPQ6XTAroCCZYfR3Oz9gfDAmW4KyiWCDSw49amksfo7e7jWWjCQVxLD39yJTg8QhXuUtm7M5p3b2LpmqMDua2d8tdW7Ihuz3925rNEsRPLm(ZJhH6JfdnAuavDG7eb466tbKFL7J7WOe)cLjc)i8NvObocZzc1WyAkHLDj95)z9faYYcJpd0eQxWvN7ePLHkN(EO)a9sow1524e7Vnzq0HumXI3BBDE97QFFx91h9qielu2OxVO(3Rx14GJwa8WJFIfw9f1xkR(Ya5ApZv0xvFD9n0xZvVSEfDbx97L1a0n13Y4r9FW9uy(5eu(qB8b2y0)X52qVMjaUUEDlG50Fu6jghqKplMczqDXE(XsfRdpxYVnsU87YAt85B3YAeJUSALSfGpcSkwqlSS6B)KNwardkO(2nF6kfycJOTMk62pDLSyAaFbK1dPq(vSa8)6mVcYVXckk6Xq2jG8F6vhGX8IW7RVYbb(YDOeh1YwhONhETLiWLifKX3n5eNBeK(4GBBY()I868tGTEWtCBbqTbhDnEof(qvtzicEC(M0Yl(vTcTF1Ij6GadsxuIYO4HZuV4hWFngZtx4OiDWbNK4HPXzPIpQrn(fTcrXajc3d)9jbQWsfHTVkbiYH4aRW)m)9Fn4BaUzeUnYVFZwrmMi8yRbpdEwiT6dCHGPaEObiSu1AvRWFV3ekCb2NyOQm68cGDmMmjP)Yu(yK9y(SiM4lYaFgMcdvXVWocYZl81XOaG2rfA0GFR3KJs2n3VIXFsQhMmdrBTATh1y3hwTsI0EmrW(ceFW(PlsUQDHG2lc7YVqcvEAhr98PX)u0tnjXLLTxJ5MBUmN606KNJVjFL3uKh0h6Pr8BQcfyOAokyoEH3KTDybnnzGU)VjTJy92rG)Uym1V)EV1gRT5DsOyJIXMVMsWdmBm38jEXkfJwdYEHEsJmI3ftBRcVS1(PxOHMnLN9Ey6P95tLeAvw3hfHZuYSm0gincj(hqXszgR(DjW6fSoOeqRyryRjE2fnzj(qNFOPwXk74uv(Z4UtsLm9vyC6EmmUHVq9VlgjWf2jokQW(Hq32PQLarNXletAhQ2Quedf0nPFzeskDpzwF8dOqRsxpfCjOQ8oDIJuKSLm1951hM1XA(sEscTDewSFrNDRv(lbfJo9WN9z)XsgVzS3tAhT6r6yAApsyBh0WoscM76CAI9GPtndhIOetLjJEx952b6iEVJXijUUsyFoMFsGPpdOUPz0MqIbGcKdm2yawFVsDqeQ9G6VFE9FrFK(hGLVZVvYMXIi(1dvkU8ZwFDZK)1iS1Nn6F97mb6raPY142b4z3mMemoC5Qb1Q94Ne88VAClbmHcclO6ld)stJFtD)9jse80ee6jXDGekNpzTnw72Jum)0EJNT7)zraTKXSq7Ck2PNPLZx7GI4HOmVkPkAhJhmxkV6LDQuPkph8mnDCg0N2XKT7b3)wK2zfeQbDCyPNZyD2lZgRT1id1qSH)QWOVqS)b3vF(p6md6IeeteUynhpRy5QGIm6xmInBCPtxuumodiFE9l0J0VmJWperBJLxBj9lDhWfMPNQ(6p9U6FChdSlY4lU926xSzXQ3x)tRcYEB9l8G)3dGFQUxMBdq8Vda8FEQeVic9aGT0)DlY6)H(thtOjf3qSNFmS0hxX8prKU6bU5Ko3zTTwBRCD)VFZ))
```

**Comment by Stanzilla** [comment]
That's a Blizzard bug that should be fixed with the next PTR build

**Comment by briancupp** [comment]
Much appreciated for the quick response. I wasn't sure if it was PTR related or WA related. Good to know it's a PTR issue.

**Comment by Lilianos** [comment]
Still not fixed (updated to 5.3.4)

**Comment by Lilianos** [comment]
@Stanzilla

**Comment by InfusOnWoW** [comment]
We haven't released a WA version that readds the triggers. We'll do that soonish.

**Comment by howa003** [comment]
For others experiencing this problem on Wotlk LIVE (after update to 3.4.1.):
This problem still persists in WA release "5.3.4". You have to download the most recent WA alpha release for 3.4.1 (as of writing this post: "5.3.4-37-g2da89fa)".
