### ISSUE TITLE
Weak Auras break when I open the WA window in game

### ISSUE THREAD

**Issue by Grallum** [WeakAuras/WeakAuras2#4155]
### Description

When I open the window to add or adjust one of my auras all my weakauras break.

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
https://pastebin.com/9342RTxs
```

### Reproduction Steps

1. click on minimap icon to open the window
2. close the window
3. weakaura's are in permanent preview mode
4. open window again
5. closw the window again
6. weakaura's are no longer visible

### Last Good Version

Back in Shadowlands

### Screenshots

![look it works](https://user-images.githubusercontent.com/72307981/207926362-5e666c12-a29c-4d1b-93fa-5a8817702096.png)
![Look it broke](https://user-images.githubusercontent.com/72307981/207926376-7f33b122-04ee-4153-b014-0839e4b11bfa.png)
![Look it's gone](https://user-images.githubusercontent.com/72307981/207926382-67599947-e72e-4793-bfe0-e385d02c9167.png)

**Comment by InfusOnWoW** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10239751/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
I have fixed your settings here:
[WeakAuras-fixed.zip](https://github.com/WeakAuras/WeakAuras2/files/10261500/WeakAuras-fixed.zip)
