### ISSUE TITLE
Proudmoore - Timers for Olaf DF (Community Feast, Siege) are not accurate

### ISSUE THREAD

**Issue by GMHadouken** [WeakAuras/WeakAuras2#4156]
### Description

The timer for the Community Feast does not accurately display the timer for the event at least on my server.  Currently the timer for Feast says it starts in 3h 15 min, but it actually starts in about 10 minutes.  When it said the feast was going, there was no feast active.

Similarly, the timer for Siege on Dragonbane Keep says it starts in 1h 41m but the event starts in 4 minutes.

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Go to locations (Iskaara, The Waking Shores)
2. Observe the incorrect timer on the WA 
3. Observe the event status different than expected

### Last Good Version

Unknown, first time trying this WA

### Screenshots

![image](https://user-images.githubusercontent.com/32582099/207959941-071fca07-4c7a-4c8a-9570-8d59260ae271.png)

**Comment by Stanzilla** [comment]
This bug tracker is for the addon itself, not auras from the community.
