### ISSUE TITLE
Can't toggle visibility of displays.

### ISSUE THREAD

**Issue by DutchSkiddie** [WeakAuras/WeakAuras2#4157]
### Description

For some reason, Pressing "View -> Toggle the visibility of this display" only hides the aura while the WeakAura options window is open.
When I close it, it just reverts.

I have tried disabling every other addon, same result.

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Add any aura.
2. Toggle Visibility
3. Have it change back after you close the window.

### Last Good Version

New user

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/39133917/207976874-9263b79b-d341-41ae-9165-8346fb137a5b.gif)

**Comment by InfusOnWoW** [comment]
That button is only for visibility while in the options. Outside of the options the load and trigger options control visibility.
