### ISSUE TITLE
Icon pixel glow desapearing when trying to make it thinner on thickness edit option.

### ISSUE THREAD

**Issue by dnlpz** [WeakAuras/WeakAuras2#4159]
### Description

As stated on the title. The more you reduce the thickness the more the glow disappears.

### WeakAuras Version

weakauras 5.3.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

.

### Screenshots

![image](https://user-images.githubusercontent.com/119383957/208280754-63f19a7e-8909-4f7b-a306-43519546bef3.png)

**Comment by InfusOnWoW** [comment]
The glow is provided by https://github.com/Stanzilla/LibCustomGlow

But thickness is a pixel value. I don't know what you expect for a pixel value of less than 1 pixel, but the screenshot does not show anything unexpected.
