### ISSUE TITLE
WA simply won't work for me in the Beta anymore

### ISSUE THREAD

**Issue by AckItsMe** [WeakAuras/WeakAuras2#416]
I'm not clear what happened but for me, when using WeakAuras in the Beta, I get a LUA error on load and then nothing works.   

I've disabled all other addons, even renamed my WTF folder and I still get the error.  I suppose I could try deleting and reinstalling the whole game, but other addons work fine.   This started happening a couple of weeks ago.  I thought maybe it was a Blizzard patch that caused it but I'm not sure.   This happens with both Beta 4 and Beta 5.  I haven't tried rolling back to Beta 3 yet.

There are a number of errors complaining about being unable to load HereBeDragons-1.0 but the files are in the correct location under libs so I'm unclear why that would be happening.

Message: ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: Attempt to register unknown event "GLYPH_ADDED"
Time: Tue May 15 14:57:08 2018
Count: 1
Stack: ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: Attempt to register unknown event "GLYPH_ADDED"
[C]: in function `RegisterEvent'
...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1343: in function `activate'
...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1389: in main chunk

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "GLYPH_ADDED"

I also get these errors:
Message: Interface\AddOns\WeakAuras\Prototypes.lua:24: Cannot find a library instance of "HereBeDragons-1.0".
Time: Tue May 15 14:57:08 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:24: Cannot find a library instance of "HereBeDragons-1.0".
[C]: in function `error'
Interface\AddOns\WeakAuras\Libs\LibStub\LibStub.lua:38: in function `LibStub'
Interface\AddOns\WeakAuras\Prototypes.lua:24: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "HereBeDragons-1.0"."

Message: Interface\AddOns\WeakAuras\Types.lua:320: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue May 15 14:57:08 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\Types.lua:320: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\WeakAuras\Types.lua:320: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:39: Cannot find a library instance of "HereBeDragons-1.0".
Time: Tue May 15 14:57:08 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:39: Cannot find a library instance of "HereBeDragons-1.0".
[C]: in function `error'
Interface\AddOns\WeakAuras\Libs\LibStub\LibStub.lua:38: in function `LibStub'
Interface\AddOns\WeakAuras\WeakAuras.lua:39: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "HereBeDragons-1.0"."

Message: Interface\AddOns\WeakAuras\BuffTrigger.lua:823: attempt to index field 'frames' (a nil value)
Time: Tue May 15 14:57:08 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\BuffTrigger.lua:823: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\BuffTrigger.lua:823: in main chunk

Locals: tinsert = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
next = <function> defined =[C]:-1
type = <function> defined =[C]:-1
WeakAuras = <table> {
 group_hybrid_position_types = <table> {
 }
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:292
 ScanAurasGroup = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:767
 RegisterRegionOptions = <function> defined @Interface\AddOns\WeakAuras\Init.lua:19
 PowerAurasPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Auras\"
 blend_types = <table> {
 }
 ImportString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:1174
 versionString = "2.5.11"
 actual_unit_types = <table> {
 }
 trigger_require_types = <table> {
 }
 group_sort_types = <table> {
 }
 threat_unit_types = <table> {
 }
 trigger_require_types_one = <table> {
 }
 form_types = <table> {
 }
 me = "Nuckyouup"
 ScanAuras = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:408
 ShowDisplayTooltip = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:733
 sound_condition_types = <table> {
 }
 group_hybrid_sort_types = <table> {
 }
 glow_action_types = <table> {
 }
 DisplayToString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:461
 IsSpellInRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:20
 precision_types = <table> {
 }
 maxTimerDuration = 604800
 anchor_frame_types = <table> {
 }
 trigger_modes = <table> {
 }
 text_automatic_width = <table> {
 }
 race_types = <table> {
 }
 font_flags = <table> {
 }
 containment_types = <table> {
 }
 unit_threat_situation_types = <table> {
 }
 DisplayToTableString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:497
 spark_rotation_types = <table> {
 }
 event_types = <table> {
 }
 hostility_types = <table> {
 }
 debuff_class_types = <table> {
 }
 trigger_types = <table> {
 }
 point_types = <table> {
 }
 class_types = <table> {
 }
 sound_channel_types = <table> {
 }
 debuff_types = <table> {
 }
 text_check_types = <table> {
 }
 character_types = <table> {
 }
 slant_mode = <table> {
 }
 texture_wrap_types = <table> {
 }
 faction_group = <table> {
 }
 PowerAurasSoundPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Sounds\"
 aura_types = <table> {
 }
 class_color_types = <table> {
 }
 actual_unit_types_with_specific = <table> {
 }
 frame_strata_types = <table> {
 }
 text_word_wrap = <table> {
 }
 RegisterRegionType = <function> defined @Interface\AddOns\WeakAuras\Init.lua:16
 circular_group_constant_factor_types = <table> {
 }
 unit_types = <table> {
 }
 L = <table> {
 }
 inverse_point_types = <table> {
 }
 check_types = <table> {
 }
 aura_cache = <table> {
 }
 spark_hide_types = <table> {
 }
}
L = <table> {
 No Instance = "No Instance"
 Scenario = "Scenario"
 Group %s = "Group %s"
 Stacks = "Stacks"
 Whisper = "Whisper"
 Raid = "Raid"
 Player Level = "Player Level"
 Attach to End = "Attach to End"
 Cooldown Progress (Spell) = "Cooldown Progress (Spell)"
 Caster = "Caster"
 Aggro = "Aggro"
 Summon = "Summon"
 Player Character = "Player Character"
 Instakill = "Instakill"
 Bottom Right = "Bottom Right"
 Down = "Down"
 Officer = "Officer"
 In Vehicle = "In Vehicle"
 Slide from Left = "Slide from Left"
 Resurrect = "Resurrect"
 Rotate Right = "Rotate Right"
 Pulse = "Pulse"
 Dispel = "Dispel"
 Source In Group = "Source In Group"
 Amount = "Amount"
 Power Type = "Power Type"
 Ascending = "Ascending"
 Region type %s not supported = "Region type %s not supported"
 Loop = "Loop"
 Shoulder = "Shoulder"
 1. Text Color = "1. Text Color"
 2. Text Color = "2. Text Color"
 >= = ">="
 <= = "<="
 Poison = "Poiso

Message: Interface\AddOns\WeakAuras\GenericTrigger.lua:688: attempt to index field 'frames' (a nil value)
Time: Tue May 15 14:57:08 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\GenericTrigger.lua:688: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\GenericTrigger.lua:688: in main chunk

Locals: tinsert = <function> defined =[C]:-1
tconcat = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
tostring = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
error = <function> defined =[C]:-1
setmetatable = <function> defined =[C]:-1
IsPlayerMoving = <function> defined =[C]:-1
aceEvents = <table> {
 UnregisterAllMessages = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 UnregisterAllEvents = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 SendMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 RegisterMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 UnregisterEvent = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 RegisterEvent = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
}
WeakAuras = <table> {
 slant_mode = <table> {
 }
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:292
 ScanAurasGroup = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:767
 RegisterRegionOptions = <function> defined @Interface\AddOns\WeakAuras\Init.lua:19
 group_hybrid_position_types = <table> {
 }
 frame_strata_types = <table> {
 }
 class_color_types = <table> {
 }
 ActivateEvent = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:367
 blend_types = <table> {
 }
 EndEvent = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:308
 ScanEvents = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:590
 text_automatic_width = <table> {
 }
 trigger_require_types = <table> {
 }
 PowerAurasPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Auras\"
 anchor_frame_types = <table> {
 }
 trigger_require_types_one = <table> {
 }
 form_types = <table> {
 }
 me = "Nuckyouup"
 ScanAuras = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:408
 spark_rotation_types = <table> {
 }
 sound_condition_types = <table> {
 }
 ImportString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:1174
 glow_action_types = <table> {
 }
 versionString = "2.5.11"
 debuff_class_types = <table> {
 }
 debuff_types = <table> {
 }
 actual_unit_types = <table> {
 }
 group_sort_types = <table> {
 }
 threat_unit_types = <table> {
 }
 ShowDisplayTooltip = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:733
 race_types = <table> {
 }
 group_hybrid_sort_types = <table> {
 }
 DisplayToString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:461
 actual_unit_types_with_specific = <table> {
 }
 DisplayToTableString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:497
 split = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:97
 event_types = <table> {
 }
 texture_wrap_types = <table> {
 }
 IsSpellInRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:20
 trigger_types = <table> {
 }
 precision_types = <table> {
 }
 class_types = <table> {
 }
 sound_channel_types = <table> {
 }
 maxTimerDuration = 604800
 trigger_modes = <table> {
 }
 L = <table> {
 }
 font_flags = <table> {
 }
 containment_types = <table> {
 }
 unit_threat_situation_types = <table> {
 }
 hostility_types = <table> {
 }
 unit_types = <table> {
 }
 point_types = <table> {
 }
 text_check_types = <table> {
 }
 character_t

Message: Interface\AddOns\WeakAuras\RegionTypes\Model.lua:290: attempt to index field 'frames' (a nil value)
Time: Tue May 15 14:57:08 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Model.lua:290: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\RegionTypes\Model.lua:290: in main chunk

Locals: SharedMedia = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:285
 GetDefault = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:281
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:272
 GetGlobal = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:268
 List = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:258
 HashTable = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:254
 MediaTable = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 IsValid = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:250
 LOCALE_BIT_zhCN = 4
 UnregisterCallback = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Fetch = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:243
 DefaultMedia = <table> {
 }
 Register = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:217
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
L = <table> {
 No Instance = "No Instance"
 Scenario = "Scenario"
 Group %s = "Group %s"
 Stacks = "Stacks"
 Whisper = "Whisper"
 Raid = "Raid"
 Player Level = "Player Level"
 Attach to End = "Attach to End"
 Cooldown Progress (Spell) = "Cooldown Progress (Spell)"
 Caster = "Caster"
 Aggro = "Aggro"
 Summon = "Summon"
 Player Character = "Player Character"
 Instakill = "Instakill"
 Bottom Right = "Bottom Right"
 Down = "Down"
 Officer = "Officer"
 In Vehicle = "In Vehicle"
 Slide from Left = "Slide from Left"
 Resurrect = "Resurrect"
 Rotate Right = "Rotate Right"
 Pulse = "Pulse"
 Dispel = "Dispel"
 Source In Group = "Source In Group"
 Amount = "Amount"
 Power Type = "Power Type"
 Ascending = "Ascending"
 Region type %s not supported = "Region type %s not supported"
 Loop = "Loop"
 Shoulder = "Shoulder"
 1. Text Color = "1. Text Color"
 2. Text Color = "2. Text Color"
 >= = ">="
 <= = "<="
 Poison = "Poison"
 Mirror = "Mirror"
 Remaining Time = "Remaining Time"
 Instance Difficulty = "Instance Difficulty"
 Distance = "Distance"
 Ambience = "Ambience"
 Looking for Raid = "Looking for Raid"
 Aura Type = "Aura Type"
 Any Triggers = "Any Triggers"
 = = "="
 < = "<"
 Inherited = "Inherited"
 > = ">"
 Minimum = "Minimum"
 Hostility = "Hostility"
 Block = "Block"
 Extra Attacks = "Extra Attacks"
 Timed = "Timed"
 Second Text Color = "Second Text Color"
 Remaining Duration = "Remaining Duration"
 Specific Unit = "Specific Unit"
 Heal = "Heal"
 Arena = "Arena"
 BigWigs Addon = "BigWigs Addon"
 Legs = "Legs"
 Changed = "Changed"
 5 Man Dungeon = "5 Man Dungeon"
 Main Hand = "Main Hand"
 Player Faction = "Player Faction"
 Monster Emote = "Monster Emote"
 Shake = "Shake"
 Aura Removed = "Aura Removed"
 Trigger: = "Trigger:"
 Overlay Cost of Casts = "Overlay Cost of Casts"
 Resist = "Resist"
 Slide from Bottom = "Slide from Bottom"
 Channel = "Channel"
 Keep Inside = "Keep Inside"
 %s - Color Animation = "%s - Color Animation"
 Run Custom Code = "Run Custom Code"
 Tabard = "Tabard"
 Mons

**Comment by InfusOnWoW** [comment]
You need a a WeakAuras that is suited for the beta, which can be downloaded from here: https://github.com/WeakAuras/WeakAuras2/releases

**Comment by AckItsMe** [comment]
I was using the 8.0 beta-5... have used the 8.0 beta-4...  just replaced it with the beta-6 and now it's working.  Thanks.
