### ISSUE TITLE
Spell Cooldown Retrieved Wrong

### ISSUE THREAD

**Issue by Dradux-dev** [WeakAuras/WeakAuras2#4160]
### Description

In certain scenarios the spell cooldown for Execute is not retrieved properly. For any reason WeakAuras assumes that the spell has no cooldown at all. In this case the Aura goes red for "Not usable". This is an else-if case on the conditions. I added custom logging code to the conditions to see what's going on, and it shows that the aura state has no cooldown at all, while the Blizzard API clearly returns a cooldown, that is not the GCD. 

In the video of Wolfdisco he was showing his action bars again at the bottom to compare and ~7s into the video you can clearly see that the spell gets its ~3s cooldown, but the WA stays red, which is only the case if the spell is not on cooldown and is not usable.

### WeakAuras Version

WeakAuras2 5.2.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
No Lua error itself.
```

### Reproduction Steps

1. Use Execute a ton of times and pray. (Honestly I am not capable of re-producing it.)
2. It may be caused by ElvUI, which was the latest available one (13.10) at that point.

### Last Good Version

Unclear

### Screenshots

![image](https://user-images.githubusercontent.com/9249707/208289876-0da156bc-d354-46ba-af29-8720ed2d8f7f.png)

https://www.twitch.tv/videos/1679004807?t=0h37m00s

### Export String

```true
!WA:2!LB1tVTXXvCXWeuuAuujzv1yGGITg1gIU20YYXQffiXqRkPLCPfvxsx5GIeYz3D4Ut0YzgpZS8pcWaT8qHpvGqKc0Iu3gWdPPa9e)euOpblik6TwuO7Th8NG(Mz3Lj2U6ypL9WUZ8EV5nV3V3)2c1wT3Q(R6)0RmL4XOnzXcp8BTKJhlIjUFX9U7)(jp5txAPL27U)N39D7alkkg1OBxjwvygI6fYehYiuL7UvpOvvN5EmwKpBaT5ach3zRyre)BpyWGkQbeLxyfv)Bkq9X(ePhZwFFDgReKGaSq(RVQiB5tVOJsG8o2gfRy8vIL42bykwq8AgYg0G2z(lSDQe(St0a0iPdf1dlln1h7g3TBRrCSyVQ1pS2dRBRGnosook6mzSlUpMQAcYqgoR9U70Sv7MT2XP1z67c5kzc3hW8XDgR3htjQooMtWV0Uz(N1HcwGalLwB0uR0YJ9JfifHrx9wZfyuKH6bG5iQoe7fRWZ16sMtTZyZY99LLMSG4B(679hfXuZvL8nwyNhkWGD608WQ1RprRfd60XwByU8i0iSysmnd8wp5BMS8maG)WyQNI0hVfIoIVQxSuX61kvM6SaIh)ADnsWOBOkxYcEmVeyvSGAP(5369tjIP(L4RGm6k78AS5VS0ZHWowqrr)mi6bQzWZpgJ57aEJNYrdfHtK4OUM0JK3aIjsKsJr4WPGN5GdGZiV)6jRnh26cEuGGft9F6BXxvHhQAldras)OSKn(LmenV6Ye9qGazlSPmkEYc2x(kC(YFjnSRjtUqHcfplLAUrzVZdB1GFrdrDQgOkI3reFvO9oW2NNExKHyFdXF580893lZIo1W)dbGL0De4GcMcCUwar7dACqv(37vmyEBfPhUDeoa5nQD3igteYlFEI5pcYMjETvHqEwiK2nI)Dppz5cShrhekMSMaGtTizWyQrNbJxyQHwwXn8mjtzqU9Y1eKtS(PXiFiiHSA1IBDExxpMFBDKSZleQYbg(358ox6UcZnSgWe(hjq8XhLTy(cBXu524HTQVpGJl)LCdtCJVY(hCqvN22nA1QXdC2)E71knw0hGa3iC4l45zwv9L(c13KCc(sZFbG5)v(fpBHJ229)7ZdIydQjWpogt9gD4RVzLTUtkARzmt)kxzJ1B0oXC3yLIrB0hlG60PAY1X0av43YiFoInrVz3fbLtHI87Ltj0wZm0C7TcjEhtHUofnNOPhkcNUSobiVI5cSb4elc7o31SOnl9oswBIUoZq70mwEFrPrgLmiSZSS9y)amFLMpogjWw1IJISokKOW5SLasw0netccvnTJyi)pZ0Hs3dte6Qa7JQw3PxCKIuYXlcjLx1vsObryXr744SFdNerjZrmm7yR146aTXzTl96CMHden9n7VAI6JseR)rqU3IJTGjC(urEdqfItG(cqh2xdAORNQ5s6Xzc1uHP1Jo8K81fdZhMrOPrBG16ZGLE4Q6MVYoNMptRkGfH2NWy9oS4MvUTdkIhIkYxlNVU0)htKia)8d3kM4p79E7hGFB7Qp(NCNhmvX86N2O8nl8RMEzI)z1IfJSUHv28bJ7KpEb6W6ORVM1vaZfAQ0vKx45PzS10K0wVBZDDQw9aNb6UtnDHPPDjbLeeQ(EWHZHEAG4n4AxswsGmn7LB7iviHQKBxcLidlzdFuLMcN2Nye4Ax1Xle7D82jxO44(ibr7qtz0CBZPpkkgxu4fIObyq8Kp5(7D3)1YlBz(nH)XZE2FDPLkS3D)NFWh8l0)VWyUGbLZQrjVgi66UPJIgw4rrmi)1IYgy9ow3dRAbvzBuUuk1bipFGmepcR0dnCJnVUfcgE0gt7xrQ7ZwbpKtsN4QpiGJGIkxk74gx86w5ZKtVaZi5CVyJT(HB(dU9DYVVxsBVtQgS((lurMCUrKto5vmTZXwWrSGnKWGzAqL0KRnUCw02AdWQ88l)JSUI06MWRlFDRxsYJ2byw5wDboA0O8RiGT2wwitMLvUC5KNnnfJ9G50BN8B1bYKF3mZVz8qt6zYNui53BcCfHA)KNLgzs(ddl8(F1oOqzkRyde9)PitYNc7OhJ97moVTrNjikjTXZ2jFCTtXiPUI3mM4RLSwY2ZZD326FIfkT11QYXA5mnX22UhIqRL8zgPt(tjFEYFg((BEzkRkNENkBvzZBGH2iR2)V9O)7p
```

**Comment by InfusOnWoW** [comment]
You need to enable the "Exact Spell Match" for Execute and use the exact spell id based on talents and specs. Retrieving the cooldown of certain spells via the name is broken for some spells that Blizzard has incorrectly setup.
