### ISSUE TITLE
Apex Predator's Craving is missing from the premade aura triggers

### ISSUE THREAD

**Issue by IngEyn** [WeakAuras/WeakAuras2#4161]
### Description

The talent [Apex Predator's Craving](https://www.wowhead.com/spell=391881/apex-predators-craving) for feral druids is not included in the aura presets' buffs section when creating new auras or change existing ones through the presets. This forces players who want to use this proc in an aura to set the trigger to another aura preset and change the spell ID or create the aura from scratch without guidance.

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Open WeakAuras as a feral druid with the Apex Predator's Craving talent learned
2. Click the 'New aura' in the upper left corner
3. Click the first option, 'premade auras'
4. Select the 'symbol' option and set its size to 'standard'
5. Open the 'buffs' tab which does not include the talent even though it should

### Screenshots

![grafik](https://user-images.githubusercontent.com/6011827/208504061-00d6e479-62c9-4dbe-bc17-07836c6f99d7.png)

**Comment by InfusOnWoW** [comment]
Can you check whether anything else is missing for feral druids? We manually create those sections and rely on bug reports to find what we missed.

**Comment by InfusOnWoW** [comment]
For Avatar of Ashamane we indeed need to use the exact spell id setting.

**Comment by InfusOnWoW** [comment]
Thanks for checking! The next release should be complete then.
