### ISSUE TITLE
Bug which mixes up aura styling (skin) with Masque

### ISSUE THREAD

**Issue by Weeeqt** [WeakAuras/WeakAuras2#4168]
### Description

If I use Masque addon, but disable skinning for certain Clone/TSU WeakAuras inside Masque settings - it will make them appear buggy and incorrectly update size and style after reusing the icon (I guess getting it from the pool).
I took a quick glance at WA source code and how it handles Masque and it seems like it always assumes that Masque will be skinning all WAs. So it creates and modifies icons differently compared to if Masque addon is not loaded at all.
So if there are some auras which use Masque and some which don't - it mixes them up and creates a mess.

I'll provide two test auras to reproduce it below.

What I expect:
If I have Masque addon enabled, but I disable skinning of specific WA - I want it to behave the same way as if Masque addon wasn't loaded in the first place. At the same time I also want it to behave normally for Masque-skinned auras.

### WeakAuras Version

5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

1. Get Masque.
2. Import provided WA.
3. Type /masque in chat and disable Masque specifically for "Test 1 - Cloning Auras 64x64" WA.
4. Cast some buffs/debuffs on yourself.
5. If you don't see the result immediately - try resetting it few types by opening and closing WA options with /wa command.

### Screenshots

1. Two different dynamic groups with Auto-Clone icons of different size. Both skinned with Masque:
![World_of_Warcraft_2022-12-24_04-07-37](https://user-images.githubusercontent.com/7283432/209416612-a07170c8-55b6-4a97-a794-56192dc64e6d.png)

2. Disabling Masque skinning for the top group like this in Masque settings:
![World_of_Warcraft_2022-12-24_04-09-35](https://user-images.githubusercontent.com/7283432/209416621-b15f92a2-00e3-4009-967e-133463e3df1c.png)

3. Buggy result:
![World_of_Warcraft_2022-12-24_04-06-02](https://user-images.githubusercontent.com/7283432/209416628-11bf176b-7c9c-4ae1-8c19-f57f5c21ba42.png)

### Export String

```true
!WA:2!TA1AZTXvz4SrXeYMKsSAIBDsOicTbid2Kih7wkxMQvrYsbzjNvRTtlxS3lhP9yVA3nNZzTKDOarecM7GakdW30N5t6pam(xW7Op0Fa5NG)fW7zxjhzyMwMcAgV756EEFFFUCSY6P56lo)cZVq6wPDs7CWRn0Y0Ehhwqy(aVa29tLk1QPU98lgM2oWxWc88io5DPEomI)TSmiCrM7K8k7ZTcyoeM2O9hEjnp6(7BYCYyee4jOHdnJeUbSAHcAGpx1kz9U9tExWPjjC66pkYKrYumYZlZgUubzGPVnUPvdO(cR8fQAuqF0gQt3NmvFrG9Uegh)IVQYZ6pizQKyxrrj1r42imFtV1tw0J152MEKumt74OyjDUWKju1O(uHQvd8f3vTRGrB2e3XvVjBuZN13Hyf1OHXEHewPcvwT4Av0eyhDZiMz2U8qINxzhU6Z5rwKDj(I64QPDgSz(C1n2SUroDdTi8qSc9m3JWoEzRYi4Y0RVAHkv0JhXQeX0t4Q7B2IWv7f5pkeuz7vRrdorOCysAM07C9zKMyUiJm9MSGOWEM(0wMY8Bj4YfHRP5h4toKyYj1fiU1u4E2HoyulxXMYCGXji86W7kxJ87aZP1YK6J7fMdM)SWxfUnChS5m)7JCdQZrXW)kM8hfrYOf1K1zuuoObdZa8infMPokbhlkhsEcw1ZRxOqvnVatNIACelNrVvestu1WsP9mWBRQB7zY5YwwceZ8fYMzJOodwQZ66Aolz0K71Jt8AeZoGl2hRP6X1cU6iMqzFmss1xMD0eA3aQFJaws5r1cNObTPAA77FWD6zYSRexEE6mqQRgE9e6DM5YK3lWN63mtoSOXZS0D7S0DHpfCwRqKRIh8cWxsbUaCr4sXCoDEOPnzk4LXQVkCfvygv4vU6nHx9zWSWvXc41HpRk8AWNdYaFE4gWxaED4nGBQcFr1b2bErT8Rl)aPSyMo0i(tVa8oWf1n9On9HlYq(QKmOa5uH3Qi81Kff4Rh)8Be)8Bgx78OTOIZdN(yfmlHuqC73afx5PmBpYwqAS2qKsejMCJk6W5Cbv48WTo0zpK)rTJjuWlnLgpGjG56YceXLof4UkW0pg(kjuStstY(XtCEow5XuXxuevIbml9C3R8A1bTuWx(CDBYOoXbK(9GpJuxJ0m4m9KdVb1r4EEyXuWsWBIrt7KAfuqf(wdA6OPxD)DkTD2oAyG3UFPA6LFVAvnYvPBeNurwtCH8QW9uHpT6bVEFkgf1dIy2KRFkzcLGJdTrdlNG2(1BtdjBD44Uslkxn5E2cELxcb0pOp3nOTKDq4BfdSsuvIMsufbzeuLy8SAA1mkH4B40sFNDjgjk6vcCi)9tHLXJ2HqcZjj(cDz51vc5OJd3ui1Pexi3BpdCTHibx6plbfFNdUCyAbPJytURjgEpCKSlC24bJFKW03KpQbmxVJN7gVbp8stS9x4z(8KrhRR0YTMrTWxoEq0bpqkDSJHbTCy3JsoiAhsc28KHjk93DSxv88BhXf0g7HjvmbIyGdQvTw1cW1yysjxt)4fAp(ANu9gLb(IWlvKr3pZdImDKEjzmmorIp(KggpwBu3VbZmS7gJAKea7s5ulKXpkNN4wLWPlxTAb9nriYO2k6LxUKXWJpA5LmZokJE4joh5SXxguBnJkLRw4dh20lODrgbTb9T3B1ZC75ZUys2jNyG8X4Vqxzh5MhAfjeb(1WRWWBf6lhoXb6kXRFCM1t254lKtDiYLxE8iUAYjDJxs9472IdedxQ9oiTKNkEMkuS90XhGwY1UwUeAtxXt(imrGBbMsHvj4mDhRb2AsBnT9dcAPeE5Xtkr17r5MyH2X9tS1WlK8lR)c6aAag6Agl71Bht0qbF4dw4b7wE5LFRkRWO(Y)raIByAS8KFueHkmuqHgDOHXX6(7afN0Hp7)Hd)cz7SqwPdpM6O5EP)5QVZPpf(BctEO8NidE4(PGVDIJoub)BLpgFCO6KE4qnxyvPPn8Gj9QbD0GgQJvod0wU0)W4uX)(FXEgwdwpXmg24eUWtbpCS7l8UJSDFZ3lA3LRMvS9IRdFh47cFVj9yHV)KwRWMBbB5cMJnqbRpsFtWwwZCI9ibsSRi0yKzi08GldUkafJ2Tr3myNeGXdAb(qae(e4rkad3bhe4YJGDJjsqBOdSNcSp8y4hSf8(Wpe(rZc)yf4jq3pe(jJfUWtHFQc8m4NbhCf4NRa)IKn)lDHFLl8Rtb)MuWVDA435c)(C)xjHMc6DcTd8huG)4)pej)n4pLeAFqcQ8NZHqY2TZNBfrXBND5IWFXf(RNqaKE3Z8()Rd
```

**Comment by InfusOnWoW** [comment]
That appears to be an masque bug. I have proposed a fix at https://github.com/SFX-WoW/Masque/pull/298
I'm sure the Masque maintainer will take it from there and figure out what to do.

**Comment by InfusOnWoW** [comment]
The masque bug was just fixed, the next masque release should then fix it.

If not, please report back and we'll take another look at it.

**Comment by StormFX** [comment]
I'd appreciate it if someone who's run into the problem could test the beta to ensure that it's fixed.
https://github.com/SFX-WoW/Masque/releases
