### ISSUE TITLE
more robust WeakAuras.CheckRange()

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#417]
When using WeakAuras.CheckRange() with a unit that don't exists LibRangeCheck:GetRange(unit) return nil, nil and "max <= range" or "min <= range" raise a nil comparison error

Maybe it is a good idea to return nil if the GetRange return nil ?

example:
```
print(WeakAuras.CheckRange("player", 5, "<="))
> true

print(UnitExists("party1"))
> false
print(WeakAuras.CheckRange("party1", 5, "<="))
> Interface\AddOns\WeakAuras\Prototypes.lua:35: attempt to compare nil with number
```

**Comment by InfusOnWoW** [comment]
It's a internal function. It's behaviour is whatever it's behaviour is. And in this case checking for UnitExists isn't exactly a burden.
