### ISSUE TITLE
Warrior Execute availability check when Massacre is talented appears bugged.

### ISSUE THREAD

**Issue by jwal2tusk** [WeakAuras/WeakAuras2#4179]
### Description

I have an Icon weak aura that simply shows the spell Icon on my screen when the action is usable. For the warrior spell Execute, I have a trigger that is simply (Spell - Action Usable) with the Spell Execute. This exact setup I use for all my other spells and it functions as expected, but with this spell, specifically in conjunction with a talent, it breaks.

Without the talent (Massacre) which states "Execute is now usable on targets below 35% health, and its cooldown is reduced by 1.5 sec." this setup works as intended. Sudden death procs (free executes), the icon shows, and then goes away when the spell is used. When the target falls below 20%, the icon pops up, and I can use the spell and then it goes away, then it pops back up when the CD completes.

With the talent (Massacre), the bug appears. Sudden death procs (free executes) still work perfectly fine, the icon shows, and then goes away when the spell is used. When the target falls below 35% however (new execute window), the icon pops up, and doesn't go away regardless of if the spell is used and on CD.

### WeakAuras Version

10.0.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Be a Fury warrior
2. Spec into the talent Massacre
3. Setup a weakaura icon to proc when execute spell is usable
4. Get a target below 35% (such as the pvp target dummy in Valdrakken)
5. Use execute and notice it doesn't go away despite the spell not being usable

**Comment by jwal2tusk** [comment]
I fixed it by changing to exact spell and using ID 280735. I still think the behavior is odd when using the spell name since it registers availability of massacre correctly (35% HP) but doesn't register its unavailability during CD.

**Comment by InfusOnWoW** [comment]
The bug is on WoW side, Execute has acoording to the api no cooldown, only the exact spell has.

**Comment by InfusOnWoW** [comment]
I btw tried to reproduce this to make a proper bug report to Blizzard, but couldn't with those reproduction steps.

From the last time I investigated a problem with Execute in depth it required a particular talent setup in multiple steps and only occured after changing specs. So if you do have a fool-proof way of reproducing it, I'd be interested.
