### ISSUE TITLE
bfa - custom tsu with internal event trigger without event

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#418]
What steps will reproduce the problem?
new icon - custom - tsu - check on events - "BLABLABLA"
function() print("hello") end

close weakauras option, or /reload

What is the expected output? 
expected: nothing

What do you see instead?
what do i see: hello

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?

What version of WeakAuras are you using?
8.0 from git

Was it working in a previous version? If yes, which was the last good one?
tested on live server (git version): it doesn't trigger "hello"

```  dGJfdaGAqIwpiLDji9APQYSL4McIBdQDcL2lz3q2VOFkqggiu)wvDzkhwvgSkdxQCqqeNsq1Xqj)fkAHGOAPGGwmuOLlLhkvfpfzzGKEovnrOGPIQjdvtx5IssNxs8mPQQRtLfjK2kisBwQY2fQplPMLGY0aH8DbQrccmwPQ0OrPgpiHtkGUfikNg4EGuTsH4XOyucWIL4IGfHlcxCr4apu6qmdeBIELIOhZaXgVbQRTwiFCtyHmwqSiaAwd9kqQ18Gpsy7VO1a11wtCrRsNjIX53hweJZVpmMSb4MObGnCrwSHMxuGyiiS8Q9nqItHLxivXwnqoeufcfX487dJ5Q0zI87nZ1H)MjYIn0e1h2VLxiM3)QnrmSnM(jYIn0eX487dlQNdXmWhfWRu87nZhwEwSHwy5fAOHgEgjV8YlVUgaTaIY2kLF0WZlV8YlJKxE5LhOxEwSHwEqh65fDMFrZBSnugjV8YlV8YlV86Aa0ciAW)wbpA4zK8YlV8meEgjV8YlVMnxdL3AolJyiCroKfBOj652xKN9p4GqI8S)bhecsygi20ev(pCXf58gMEa0mb5I2RyOjUiyxzaX10e1(ftCrWUYaIRPjch0RhGXvwfXfb7kdiUMMO2JXexeSRmG4AAI6I72RyOjUiyxzaX10e17XmWhjUiyxzaX10ebq1TVRtCrWUYaIRPjAVIHgufxeSRmG4AAI8aOzIlYdq1ftu3RTkAAIAwn4J4v6mraMpseax0m)YJX53hoV5DIqoyEduxBnVWYseabgM(9AZWfwwIMbfJvv0dJfdxyutKxegSyrXcllicQS0Ka```

**Comment by mrbuds** [comment]
I forget to add that it trigger once for each event added

**Comment by InfusOnWoW** [comment]
That's intentionally.

**Comment by InfusOnWoW** [comment]
To explain a bit further: Opening the options destroys the internal state of all auras. That's a bit unfortunate, but that's how it is. To give custom triggers a chance to reconstruct their states, they get notified on closing the options by sending fake events.

**Comment by ashkashlitwin** [comment]
@InfusOnWoW , for someone who knows little like myself, I have an Ipse WeakAura with this fade logic:
function(progress, start, delta)
```
    -- animation
    local not_pandemic = 1
    local pandemic = nil
    
    
    -- Buff information
    if UnitBuff("player", GetSpellInfo(194084)) then
        -- Savage roar found 
        local expires = select(7, UnitBuff("player", GetSpellInfo(194084)))
        local currentTime = GetTime()
        local timeRemaining = expires - currentTime
        local maxTime = select(6, UnitBuff("player", GetSpellInfo(194084)))
        -- calculate time remaining and compare to pandemic values
        if timeRemaining <= maxTime*0.3 then
            -- Pandemic is active            
            local angle = (progress * 2 * math.pi) - (math.pi / 2)
            return start + (((math.sin(angle) + 1)/2) * delta) 
        end         
    end        
    return not_pandemic
end
```
How do I fix the error?

**Comment by ashkashlitwin** [comment]
Did not even realize that was a thing. Now I feel dumb. Thanks! :)
