### ISSUE TITLE
When anchoring weakauras associated with trinkets to the Personal resource display, cause everything else anchored to the personal resource display to bug out

### ISSUE THREAD

**Issue by JR61010** [WeakAuras/WeakAuras2#4180]
### Description

I expected for the weakaura to work like normal, but ended up bugging everything out. It works like normal when not anchored to the PRD, but when anchored bugs everything associated with PRD out

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. get trinket weakaura
2. anchor it to Personal resource display
3. watch everything that is associated with PRD bug out

### Screenshots

![401137a296728e062fbe51fe9972bd93](https://user-images.githubusercontent.com/121605280/209925741-b42a4686-e52f-411a-87a1-e3cdd0696a2e.jpg)
as you can see, some auras have no swipe, no cooldowns anywhere, buffs arent properly aligned, random shaded boxes on left side

**Comment by JR61010** [comment]
Im sorry but I tried it without Plater enabled, and it works fine even when anchored to PRD. So the issue is trinket weakaura being anchored to plater personal resoucre display

**Comment by InfusOnWoW** [comment]
We can't reproduce with those reproduction steps.

As we fail at step 1 to get "the trinket aura"

**Comment by JR61010** [comment]
If you play wow you know what the fuck I mean smartass.On Dec 29, 2022, at 1:11 AM, InfusOnWoW ***@***.***> wrote:﻿
We can't reproduce with those reproduction steps.
As we fail at step 1 to get "the trinket aura"

**Comment by InfusOnWoW** [comment]
No we have no idea. And since you choose to insult us instead of adding the necessary information, we won't investigate this.
