### ISSUE TITLE
Progress texture above and below glow?

### ISSUE THREAD

**Issue by rakkarage** [WeakAuras/WeakAuras2#4181]
### Description

I have a simple WA with a texture and a glow. Sometimes the texture is above the glow and sometimes below. Seems to depend on which button/ability it is attached to? Raging Blow always looks messed up... but if I copy same WA and use it for another ability it looks normal?

Please & Thanks.

### WeakAuras Version

WeakAuras-5.3.3.zip

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Make a progress textures WA that checks for enrage and raging blow with glow and un-glow actions
2. Texture is under glow?
3. Change it to enrage and spear of bastion now texture above?

### Screenshots

![WoWScrnShot_122922_110533](https://user-images.githubusercontent.com/962340/209980848-1bd00d27-c595-45b9-8ffd-45168c927175.jpg)

### Export String

```true
!WA:2!DsvpVTTry4i4guebuaBdx7exGcJoeu06Q6eb7wuGIaszky5izPsshNbdiDK3RiVAQ7yV7OTu6MqrrN1FGaObp1j9hOazltLqO)c0s31s7MZDKkwPzSC449X7x3ZZZ7vO669whVo(3k7LiaE7bfY)3VaFqZUDfGSW8UmoeWzjuCfweJF8kQV4nWGajt4ijyI8Vi)8WjcupWf6Roa68U2u92yeouYjbbax8PpKVy61Cvspr5ANriL5u1mX2EwuokaSHlbQ07iafjdNjs8Yw3IdDj9TDAzvV(qrmefvdlkE7XojDvhpPDfdh32oUg2UMjuI0locna42zjOOPCqmyRt4JhJbpLlUQn4hzvVv1tRpkHUO6k(W07DD6w2zPjEnvP2oaOaN47eYUQjTt6hn1Wxsy0DovG8IG0ns)4PCvb7O9qFVMyJci0GDmJyxnvhaXBpPt6ds3E6)jEZez)QWyry2v0rA7LCfi3z0TUD)cn(80pPy8AivIVeCZR0gmm873ziqXg0Gi4x2CoHkboff9mfERkWFEeIs6H016b2cjIlR(kajahjhObYWpmDltkJctXAwtzvBngXfGpJIfd1MQXO0Dn7Hi0QPFPYH0Dt)Q0sPFD6UEDjuIi893ESK5FzE(VFHFD8qotMf7cMDzuz8Qv5KxSZpKGWQuI2X1DSIfTHaLfIT3mDRPQLE3kX8cbsqO81Jequ3wm19ZRI1jUw2kOfHR6jrrk(Ft7EjrssrtfG5Vz63x02pcje6zMcYla9K4vru)qgVkxHNzdlyrZePuHpXRQaEd8pMiKagWnq9dNlZL2NXrXASoEJk1nA0YTPzDJkp14WdR5w7zwJ1GfrhjHIGw29SOVi(BRPjLUiF4Cdmwz15NbOlmuiU48wSRaE20gaMGopFx94J2RmV)IwsokRqfhK(fxppqPPA3vx)zK10Q2gnSCSQBvXTP9SStLHe)lOGqCVjzRZD3uRZ4ywB9EDMTioWpLau)bTU7ELkxU84Lrp1m35OmLYAJYJSUfQfPpenlRVqVNV(vIoJxo)4JEYF(Yx(h3CZnh9K)(F(37O(UDNwFWEL(M9tF0MZcjyOnkkkliIoMkTKSOxpcNZ4HVpzqOHJ5zAeTECEmNfWv3Vf8t8AlfmVf1p4)fQxEKQFMI1KTTzDRto0trUDjbfNIsKkXtZ4CEEKicrLAZ8QDItTdTM)oIlDjojNrYihBuuCiALHA5VJsn(G5ll38NyBTYEL2)9gMKhXmnF63n0N1lwFLd)mcEQliK70Abi45ZzXQxYNKrBQwBvB1k2xrWYWxpoRPp71HcpoHGNWoyGJ)PhDWZpgXjuDBke(k9BI2VTlDcJtuTuzlMACIBTk1Bw5PNvZXkpr9lmHqvQ88NvuTvlVm5Y17UUWE)sLlvE9l)RN)Mp
```

**Comment by mrbuds** [comment]
The Frame Strata in display, tab can be raised to not match button's strata

**Comment by rakkarage** [comment]
but then the weakaura shows above dialogs like talent etc...
is there a way to change or raise the frame level of the texture within the strata?
https://wowpedia.fandom.com/wiki/Frame_Strata
thanks

**Comment by InfusOnWoW** [comment]
We don't make that available for individual auras, because we already use it.
