### ISSUE TITLE
Luxthos Weakauras after modifiing still bugged

### ISSUE THREAD

**Issue by Mortysha** [WeakAuras/WeakAuras2#4184]
### Description

HI I just downloaded Luxthos UI for affliction warlock for WOTLK classic. I made some modifies many times last days and it seems that the weak auras addon still remembers some of those old created profiles. I reinstalled the addon many times also deleted it from addons, but still is bugged. After i lock the setting it always go back to some of the other profiles even if the profile is not loaaded. It is also imposible to lock the windows where I want to.

### WeakAuras Version

weak auras 5.3.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10325082/WeakAuras.zip)

### Last Good Version

weak auras 5.3.3

**Comment by Stanzilla** [comment]
That's an issue with Luxthos auras, they have their own settings

**Comment by Mortysha** [comment]
I see.  So the only way is to disallow general setting or the general
settings in luxtos? Thanks

Dne pá 30. 12. 2022 15:20 uživatel Benjamin Staneck <
***@***.***> napsal:
