### ISSUE TITLE
Convoke the Spirits cooldown Timer 

### ISSUE THREAD

**Issue by tannerschwartz5** [WeakAuras/WeakAuras2#4186]
### Description

The premade auras for Convoke the spirits do not show the cooldown timer. 

### WeakAuras Version

5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

creating a premade cooldown of any type for convoke the spirits.
once in a while i can get one to work for one spec but it wont stick long term

**Comment by InfusOnWoW** [comment]
Convoke is special because there are two Convoke spells. It should work if you enable the "exact spell match" option. I'll fix the template for the next release.

**Comment by twsx** [comment]
For anyone else coming here trying to fix their own Convoke auras:

* Enable Exact Spell Match as mentioned above
* Use spell ID 391528 (which is the new talent. 323764 and 337433 which WA may automatically translate to won't work)
