### ISSUE TITLE
Brewmaster Monk Purified Chi buff tracker

### ISSUE THREAD

**Issue by LW-Frost** [WeakAuras/WeakAuras2#4188]
**Is your feature request related to a problem? Please describe.**
Premade aura for brewmaster monk for Purified Chi buff

**Describe the solution you'd like**
Track buff time and stacks. 

**Additional context**
![Wow_wUSlSGoDgC](https://user-images.githubusercontent.com/37908055/210248309-771cba00-9170-4484-8f90-4e62c7467a7a.png)

**Comment by emptyrivers** [comment]
This is already possible to achieve, if you need help making a WA please visit the discord at https://discord.gg/weakauras

**Comment by InfusOnWoW** [comment]
It's about the pramade auras missing that buff.
