### ISSUE TITLE
Ruby Life Pools error

### ISSUE THREAD

**Issue by DarlaAngel** [WeakAuras/WeakAuras2#4193]
### Description

I would love to be able to post the error message that spams my screen anytime any button is pressed, but of course everyone is mad that I have to pull back, shut off weak auras, reload ui, and then reengage. Of course, the copy I made of the error message doesn't get put into notebook for future reference, LOL. But I'm putting this here in hopes that someone will know what I'm talking about, It exclusively happens in Ruby Life Pools and has been an issue since I started Dragonflight.

Always using the most up to date version of WA from CurseForge. Not sure what else you need to know other than the exact error message that I will likely continue to fail to get.

### WeakAuras Version

WeakAuras 5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Be in the Ruby LIfe Pools dungeon (normal, heroic, mythic, mythic+)
2. Press any cast button

### Last Good Version

No, hasn't worked all Dragonflight

**Comment by InfusOnWoW** [comment]
No idea, but prety sure it's not a bug in WeakAuras.
