### ISSUE TITLE
STUCK ON UPDATE

### ISSUE THREAD

**Issue by Takkero** [WeakAuras/WeakAuras2#4195]
### Description

as i said in discord chat when i login everyday FIRST thing i do is update the in game weakaura.

for the 3rd time the update was getting stuck and i had to reload the game (close wont work... when u reopen it open still stuck)

what i did
1) login
2) /wa in chat
3) open first update available (that was M+ Timer)
4) press update

the bar at 60% stuck (like other 2 time)

bugsack grabbed this error:

1x ...aceWeakAurasOptions/OptionsFrames/Update.lua:612: GetIdFor for unknown uid ShMBwseJbSL
[string "=[C]"]: in function `error'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:612: in function `GetIdFor'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:531: in function `GetPhase2Data'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1634: in function `GetPhase2Data'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1892: in function `UpdatePhase2'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1674: in function `ImportImpl'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1518: in function <...aceWeakAurasOptions/OptionsFrames/Update.lua:1517>

### WeakAuras Version

5.3.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

```true
1x ...aceWeakAurasOptions/OptionsFrames/Update.lua:612: GetIdFor for unknown uid ShMBwseJbSL
[string "=[C]"]: in function `error'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:612: in function `GetIdFor'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:531: in function `GetPhase2Data'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1634: in function `GetPhase2Data'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1892: in function `UpdatePhase2'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1674: in function `ImportImpl'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1518: in function <...aceWeakAurasOptions/OptionsFrames/Update.lua:1517>
```

### Reproduction Steps

1) login
2) /wa in chat
3) open first update available (that was M+ Timer)
4) press update

### Screenshots

![image](https://user-images.githubusercontent.com/41358238/210548904-5719c7a9-7791-4de3-a9d6-7717046d8de3.png)

**Comment by Takkero** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10343798/WeakAuras.zip)

WeakAuras.lua attached. had to zip it

**Comment by InfusOnWoW** [comment]
In those settings there M+ Timer is on version 117, which is the latest version https://wago.io/M+Timer/117. So there was no update for that aura.

Forcing an update to it worked fine. 

So with the information you provided, I cannot reproduce the issue.
