### ISSUE TITLE
Unit Creature Type Trigger

### ISSUE THREAD

**Issue by ManneN1** [WeakAuras/WeakAuras2#4196]
**Is your feature request related to a problem? Please describe.**
It's not possible to, to my knowledge (which may be lacking), create a trigger filtering units of a certain type, e.g., totems or beasts etc without custom coding. For example the use case could be wanting to avoid adding an icon on a nameplate if that nameplate unit is of creature type totem, or beast etc. I am running into this often with totems, where I oftentimes find myself not wanting auras to show up on them.

**Describe the solution you'd like**
I would like for a new option to be added in Triggers, probably under Player/Unit Info -> Unit Characteristics with "Creature Type".

**Describe alternatives you've considered**
The option could be added elsewhere but I think this is the logical area to place the option.

Until an option is added one has to write a custom trigger using UnitCreatureType or, in the example with totems above, filter them based on names using the Unit Player/Unit Info -> Name/Realm option. If there are other solutions I'm all ears, but I havn't been able to find them.

**Additional context**
It would be good to have have the "is" creature type filter but also the inverse, i.e. the "is not" creature type filter would be very helpful. Although one can use a custom activation function to inverse the "is" filter, it is a bit more convoluted.

**Comment by InfusOnWoW** [comment]
The api for that https://wowpedia.fandom.com/wiki/API_UnitCreatureType returns localized values, thus we would have to ship a file with localized names for all types. That's a maitenance burden that we don't want to have for such a minor feature.
