### ISSUE TITLE
Lua Error bugsack...

### ISSUE THREAD

**Issue by Milky063** [WeakAuras/WeakAuras2#4199]
### Description

for it to work...

### WeakAuras Version

WeakAuras-5.3.3.zip

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
1x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'SendReport()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SendReport'
[string "@FrameXML/ReportFrame.lua"]:176: in function `SendReport'
[string "@FrameXML/ReportFrame.lua"]:79: in function `InitiateReportInternal'
[string "@FrameXML/ReportFrame.lua"]:432: in function <FrameXML/ReportFrame.lua:418>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ReportFrame.lua"]:56: in function `InitiateReport'
[string "@FrameXML/LFGList.lua"]:3260: in function `LFGList_ReportAdvertisement'
[string "@FrameXML/LFGList.lua"]:3292: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>
```

### Reproduction Steps

Nothing

### Last Good Version

dont know

### Screenshots

![Screenshot 2023-01-05 131118](https://user-images.githubusercontent.com/50210970/210871164-1a4c4837-568f-4787-a881-86a69b17e2c4.png)

**Comment by InfusOnWoW** [comment]
Tell Blizzard that, because the game was released in a broken state. Every addon can taint the ui in various ways. We won't investigate taint issue until the 0.5 patch.
