### ISSUE TITLE
Some errors not reporting (to chat or Bugsack etc.)

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#420]
What steps will reproduce the problem?
```dKdzcaGArH2LOKTrPk7JsvntkvmBb3uu0TLYovf7fTBI2pj)KuXWKQ8BroTKHsvPgSqdxv6GGsNIuPogLCCQQYHjyPIkwSOGLtLfjQQNc9yc9Cv1ePQQMkWKjLPRCrrLUkvfDzvUofltQ0wLQAZsfBheFKQs(mvzAuvPVds9xkLBbsgnOyuuv4KuQ0zjvY1eL68KQwjO6zIQCoQQyAraXgrnIAequqCfKd4kpVZLzs74duw9iox55Docio9VhrrZFPgrnJtyvssmBIhKtUprFBhy1vU5ydbWMdix)BltD6B3hFru08xQzB6FpIhKtoIFysqRJK4hMe06iHvCfKJOO5VuJyhJuCvs6dDRIk4QOkQIQ4RRKl)D)LVkQIQOkQGRIQOkQIUBgNufB6bPDFFkl)zU(cov0(QOLkQGFsnfCfCfCIIM)snBWuAhXvTtJJyijOraXjeo56saXMjSIaooItiCYraXMjSIaooIAvNoLOjm9eqSzcRiGJJOtq8iGyZewrahhrxkCeqSzcRiGJJ4lK3jeo5iGyZewrahhXs65sMxci2mHveWXrSJG4QKKaIntyfbCCCel5oNui0)C)kj5tEe1QFgnsXvqoIcHar35vjjq)7rSetsIstd4kpVZ95JfXsJ4ZbnXswZ2FcUDA8XIJ4Ny3SYolllOS6bLN9Yld98tVUeHWhl)21IJea```

What is the expected output? What do you see instead?
In the example Aura above it should give a Lua error when you move. 

What version of WeakAuras are you using?
Live (errors to BugSack as expected on beta)

**Comment by InfusOnWoW** [comment]
Should be fixed now.
