### ISSUE TITLE
preservation empowered spells not working

### ISSUE THREAD

**Issue by voozul** [WeakAuras/WeakAuras2#4200]
### Description

I had made some basic weak auras that track the cooldown of some empowered evoker spells (spirit bloom, dreambreath and firebreath) they worked fine and showed the cd counting down and when they were ready to use... I took an update today of weak auras via curse and they don't work anymore. 

The weak aura shows but never goes on cooldown and does not track the timer when i use the abilities.

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
I don't have any current errors in bugsack
```

### Reproduction Steps

using %p doesn't seem to work when it did previously. Not impossible i've done something dumb but don't recall making any changes since they worked.

### Last Good Version

Not sure as haven't played evoker for a while and just take updates when pushed

**Comment by InfusOnWoW** [comment]
That's a blizzard bug, details can be found here: https://github.com/Stanzilla/WoWUIBugs/issues/354

Until they fix it, you'll have to enable the "exact spell match" option.

**Comment by voozul** [comment]
the weak auras that are not working have the "exact spell match" option enabled,

**Comment by voozul** [comment]
!WA:2!1v1tVTrru8AzQQWiIADdrTvOQqaIOhiQkLMkvvO1BQnPi340DDBkNSND3z3DiRNzyMzTJlxOU0Qkqcq(JGpJ4qeFaqrI7JSq8bOxqCnhqaxG3mRTBkq2dZ(M37nZ79(9(ZuOw5oLdlh(03CejGr9yzIa8RFSXOmvct0GRimQSKOFJOijwTXnU2F)hhd(2drda5BXiuL)6v3Szv3XbmwAiRh1RhHJBV)0TvdJXjcuG9MwZvQqcvjhcLOk5hb)KjLgOeK4ySqo3YIjK)UJQph7k5400H21nrDWN5402ptM5J7IPkVSOiYU71A9kEnB51SIBtxlF(zxFIPxClblwGLYfFhpZvCb(PYK4wXykwqc8sy9AqBp(f2osc)QK2d1xoZqBjWGHC92QA96JfyuQ3H9NXMRCMh2EGL8wHYsozqm6Ztr9Xc(PnAH3fGHdPRlfwLLgAKPaiAN2JcX(qy1eIDXgvRVvT7wFygDcMuIFkdm2f3mF)TzH4V7yhaPaSGIsVhaGag)zhSdgZRawjq5IaupzOeNgztv6JdgqIuzcKcNmccqxCSjVC1f0Zng26dorSGLrdF654VHcVRQLDjIj6GuT4TuKo4wCboGySvr(z)p6iNq4qzu8WzIx6T5)pkZNq4AU3WNzfnZBDQC3Mn4N2YeQhzGEKGTjHQeNkW2dYViYU4qlZhooVO8JZRvlSVv(NKjvKO(qKlykiQBcmD2SXMv5V1rfEP4yuq)wrPmMirpNaWfJw8lCuhiSpKijbTujqXwcu7vyKvRawkt8rBC9Fy(5xeAAkUX1)1RCLByOgo5wGGC1lEXv5LZJ8eeu2E)j()lWCAqXx8OCIoSWwM0A7XwH9yIWTfi(GTNqmEMjTvxnUBZ63cqHtMdVpVDwFC(5pkBKVBcY2fkb8tNApZf7rEa(StYcZIItEOOyDlGuOqHI)Y44uwVAc8NMHPb936LU4kRE5CS2iypZY0RyGzJXPh7NPumAJUyb0vnYWUoMgRsEnR(tXOHMn5MQi8Tp0E9Ht5K4yeMyvXlaLIlADKMjKGDOWKIIwj1ja9PSgWbGpSiXpbtItu3XjLHcJS98MMxZ0GoThoJKFAVD6J7rOXVRhjf8Zomg1xb2HQwWTtwQIuYX0AUG2VKBqksknuosa5meJe2(rtW6yMhZNF6yutD7njseG4HjIDNmp(hd)PoM5XdMQwYqeLyAuy010VCn9C6v2hJKypLWIuNyCOP5he3YmGviXGvcLdm6ySQEfNoic1EqD6j0D0undiFL)nhNhWyDk4Is5jOIJuSGU5JFotHNmAjs4(3eWJol6aRQe3GzjJ9IeawbEdsHkEqEPsndlJX99w3TA1n9bxkIexA1ms4EX9Aid21)E16YeeQXi4eEza)NoKhMc6Ak7D7zgcCNrM4HyFS5Ql7gKGd2zn9RwCqxKGyaVrm60t62fLMHlkcsq0yS8ClRFu7bCbdGfvF9fww)51GtQF4qiic73eAa0pQ8LwIXx6AVV(lmQhzlrM1N)9N)83iVp)3(Z)Y2XBRlBL)4NJ5PL8dybb(cBJr7ubshYREy0YwbAZoA3NzFVAMnAFWZpUvJX1CRC7QEvRxD9MnC1pEFJCOsX(GWSaq)KjoE5pi3Vxt)16Vr)uNesiw)L6Vs)y93UhHM3EdUAjDC7Ys3lVYLw59k39NV))8

**Comment by InfusOnWoW** [comment]
Then you have the wrong spell id. Note that the correct spell id depends on the talents that modify the spell.

**Comment by voozul** [comment]
nevermind my bad there's no bug i've missed something

**Comment by voozul** [comment]
ty sorry!
