### ISSUE TITLE
Encounter ID list fails to populate when Details! is enabled

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#4202]
### Description

report originates from this [discord conversation](https://discord.com/channels/172440238717665280/215496276609990656/1060956184867246160), but I am able to reproduce it myself.

Strictly speaking, this is probably a problem with details (@Tercioo fyi), but since that addon is so popular it's likely we'll get reports about it regardless, and we might want to harden against this kind of thing in the future.

### WeakAuras Version

tip of main branch

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

```true
none, oddly.
```

### Reproduction Steps

1. Install & enbale Details! addon
2. create any aura
3. go to load tab, hover cursor over Encounter ID

This should produce a tooltip with recent encounter names + ids, but instead no encounters appear.

### Last Good Version

unknown

### Screenshots

![image](https://user-images.githubusercontent.com/24878501/211117304-b904c7b9-3acc-4330-8cd9-05d3c2aa4347.png)

**Comment by emptyrivers** [comment]
note that other addons have also encountered similar problems - Meivyn/AdventureGuideLockouts/issues/22

**Comment by Tercioo** [comment]
Thanks for reporting
________________________________

**Comment by Tercioo** [comment]
nop, tested it's all good
![image](https://user-images.githubusercontent.com/9000280/211147531-af8f642c-89f5-4763-b3af-7bff84a64374.png)

**Comment by InfusOnWoW** [comment]
I can reproduce this on the PTR with just WA and details enabled.

Details version WD 10403 RELEASE 10.0.5.

Disabling details fixes the tooltip, so that sounds very much like a details bug.

**Comment by Pewtro** [comment]
FYI, It was also reproducible with only AdventureGuideLockouts and Details in a prior version.

**Comment by Tercioo** [comment]
Hey Infus, on PTR: "Details! Damage Meter", "WeakAuras" and "WeakAuras  Options" active:

![image](https://user-images.githubusercontent.com/9000280/211149633-357b9b43-9d6c-49f8-8f4c-76ed2cfa7cb9.png)

**Comment by Tercioo** [comment]
okay with the version from curseforge I'm reproducing the issue

**Comment by InfusOnWoW** [comment]
I don't think we (wa devs) need to anything at all. It's most likely fixed in the next details release.
