### ISSUE TITLE
Weakauras Note Clearing Update Status

### ISSUE THREAD

**Issue by dnbarclay** [WeakAuras/WeakAuras2#4204]
### Description

I am using the update function to update Weakauras in game, but the "Ready for Update" section does not clear the WA when I am done.

### WeakAuras Version

Weakauras 5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Type /wa
Go click the update icon to the right of the WA name
Complete the update process
WA still remains on the Ready for Update list

**Comment by mrbuds** [comment]
If it's still show then you still have at least one not updated aura, your reproduction steps works for me.
