### ISSUE TITLE
"Blizzard Combat Text" broken - found by bugsack

### ISSUE THREAD

**Issue by Thor99-1273** [WeakAuras/WeakAuras2#4209]
### Description

"Blizzard Combat Text" broken caused nil error loops and some secondary problem. Bugsack shows endless nil errors for auras that previous had blizzard combat text that worked without any problem in shadowlands; now in dragonflight it is broken. I see the text in the fields was lost when patched to dragonflight version, WA was generating looping nil errors, due to the empty text fields.  However, re-entering some text in to those fields, findings are that "blizzard combat text" displays nothing.  I've had to find all auras that used this with bugsack complaints and delete or change away from using blizzard combat text.  These were all configured in "conditions" then "chat message" > "Blizzard combat text".  Also does not work in "action" tab either.  Change to show in "chat frame", that works.  I don't use ElvUI.

### WeakAuras Version

534

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

These were all configured in "conditions" then "chat message" > "Blizzard combat text".  Also does not work in "action" tab either.  Change to show in "chat frame", that works.

**Comment by InfusOnWoW** [comment]
You need to improve your bug writing skills a lot. The reproduction steps are supposed to be a step by step guide on how to create an aura that reproduces the problem.

Based on your information I created a simple aura tha prints a chat message to Blizzard Combat Text and it works fine.

You also failed to include the error message that you apparently got.
