### ISSUE TITLE
Show Glow on Frame Selector - Hide Broken - glow cannot be turned off once triggered with show

### ISSUE THREAD

**Issue by Thor99-1273** [WeakAuras/WeakAuras2#4210]
### Description

Show Glow on/with Frame Selector - Hide Broken - glow can not be turned off once triggered with show
>you can put a glow around a button that works, then "hide" will not hide the glow when you want it off
>once triggered to glow (with "show") it will not turn off until UI reload, since hide does not work
>I do not know when this worked; didn't work in BFA or SL, surprised no one reported this

### WeakAuras Version

534

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

in "conditions" add then "glow external element" glow action "show" glow frame type "frame selector" choose glow type does not matter which one, set your action button as frame.  This part will work and turn on the glow when your condition is triggered.  Do the same again on another condition except use glow action "hide" for the glow to be turned off.  Hide does not work, glow will never turn off.

**Comment by emptyrivers** [comment]
I tried to reproduce this issue, but was unsuccessful; the following string doesn't leave the minimap glowing forever, only when prismatic baririer is active. Can you provide an aura which does reproduce the issue, or more specific steps to reproduce?
```
!WA:2!Drv3UTTnu4A4nSbfGHgVUG1IDrqlwqqVyOWBjxS7SCLBYGJDMKYs2V2us0wCrMuJKs2odDB1xm0R9JGVEx5l2dGFcieg2dqFe8tWoKYoTD(czYZ5qE(((4hzLw1gvlQw0lF0csiJ6XY4H4p5o8jDhmqGLv4t3myjIggZ4NZiuzqtNo(oUfHmwseBm1Bmjf3F12PordXX26TR)mjNmCiMl(Gd4Bg(32YPPyxughvFL(RifNKqIepiO(NF0xC0tkgHKHXyHxmBCx6cb8xJKXOPcxCogA(jyuIm(vISaZ8Z54bKjUEN70U9mZEDAKW620EzdG0l71SHNFpp)gU(2zuIminbnfZDPOryH16mb2zcku6vU((lIWbWc9bKYpXP95TUO98m6ggyLUlukjh7xo)mwe(VUZAqyWCkk5Ba6sy0NV(AmoTbGOqPlssyXZf4Kbgbu9UqdeijWEjoEbGvx8qynIVCp1ofW0au41d5SmA0lVxAnjEISNigbI7vBoosVVjO5ZaghKSEIndSPmkE(TPF4NksV7BSdnzjm(xvPsLQVQm6wqz34c)UPFOjiktYGTIeEjjsgB3aMUUSxKj4itWxuu6i(2niALj)pNjKKbtbcYzsGC(qq7oD74O2Hd8sxZctHHgyuf(nFdjOY072ItUz)VodfbcdAFF)3I7B7uHj2ygp6sokD2LBgucGCIGeKG7VHZVHRnD3t70XXTNDxF)UN5E6ZoXV42w7rUbF)nm6Q3Qp6SgFq3l8BFAhN)TyycBClo(xYW0WPN)op5ZQFuj70jwQ)SDhMPNOxCrqMuYODZXCW3TqhUnMoug)rM63YS56jnVvzwb2YNTnsSTozSP7(XKWRPyHOQzfEHOeC5W2ei8UMgyd6cMhheJjdJLVWoHHIAfiHsPY9ChLLijw2A75Ekpl3WeKqOhzlaPqpyb34j1Wx9(P3B7TB9j6tjceiYrXZruI2NWOh7kKiUS1kmsG9KCd7Ep1oQdlI02COKE6l(CbgEyismtxNzVp0EeIqBP(Et1QFq9JQFsDyWacLiI))HxsOLUCy)SChBmI23WyJQW13jHRqhR(olvFlBy5sRfswyE59XpUYFU4HKOca(MRP7R1i3xBdxoGdVfaihCEvxx6eAPdPbzGxtxhNo1Zirlthu)4RSVQZj3KhauzazOfNq1DbhNwdoYAUrPG3fGl(4(UOK0yu1fAEtmy8Xh4cVWfE9XkRQZYrCIwnd0V4GJCZrjz4Q8WyeDiw8Gdu5TwRXApdanIyrl3gN54502PPFxxZbVjUQLXo1RukS1pDU41lLFgrFALolLZGdc50v6CB1JducnCusvMkVIA8JHgFSAIAQ6xTJjry1Zv)M63v)beUp8)JMT1q0VaETaeRUPgUzvtu)P48A5)Zv)3
```

**Comment by InfusOnWoW** [comment]
Same, works fine.

You need to write a much clearer reproduction steps. And include a minimal aura that shows the problem.
