### ISSUE TITLE
WeakAuras only working for one faction per server

### ISSUE THREAD

**Issue by taori** [WeakAuras/WeakAuras2#4213]
### Description

I have recently transfered 2 of my characters from one realm to another. For some reason the alliance characters are unable to open WA with /wa It just stay closed and i am not getting any errors reported.

When experiencing this issue i renamed my WTF folder to get a blank profile, imported auras on my alliance char that worked. Now however it does not work on horde chars anymore (i have chars for both factions on one server now)

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

- Have Alliance character and Horde character one server
- create sample weakaura on one faction which should display for both
- relog to other faction character
- weak aura (mod) + weakaura itself is not loading

### Export String

```true
No specific weak aura
```

**Comment by SpatenLa** [comment]
do you have bugsack and buggrabber installed?

**Comment by taori** [comment]
I am looking into lua errors through /console scripterrors 1 but i can install both if that helps

**Comment by SpatenLa** [comment]
also your weakauras saved variables file is needed.
if you have bugsack and buggrabber a screenshot that involves the wa icon and a green sack is appreciated

**Comment by taori** [comment]
Alright. i will take care of it.

**Comment by taori** [comment]
You can discard this ticket. It has to be unrelated to WA itself. WA running in isolation once restores WA to be working for both factions, then reactivating other addons fixes it so WA can run along side other addons. Thanks for enduring the nightmare which addon development appears to be.
