### ISSUE TITLE
Spell Cost Overlay considering Queued Actions on resource bar

### ISSUE THREAD

**Issue by Iain-sh** [WeakAuras/WeakAuras2#4214]
It would be nice if the Overlay Cost of Casts option in triggers would consider queued actions such as heroic strike and cleave, so that similary to a cast, a portion of the resource bar could be changed to indicate how much rage is being used, and also if the action is being queued. - I'm not sure if this has application outside of warrior. (I believe feral druids are able to queue maul for instance, could be applied here.)

Either an additional button to select Overlay cost of queued actions, or for the already present button to consider queued actions.

**Comment by InfusOnWoW** [comment]
We simply use the api that blizzard provides and that does not consider these spells. So that's best handled as a custom trigger.
