### ISSUE TITLE
Item CD trigger not working on WOTLK PTR

### ISSUE THREAD

**Issue by jpgulliver** [WeakAuras/WeakAuras2#4215]
### Description

There is currently no option to use a Cooldown Progress (Item) type trigger on the PTR. 

Imported Weakauras using a Cooldown Progress (Item) or the GetItemCooldown(itemID) function call do not work.

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
Errors show GetItemCooldown doesn't exist. C_Container.GetItemCooldown seems to work however.
```

### Reproduction Steps

1. New Aura
2. Trigger-> Type "Item" "Cooldown Progress (Item), Unit "Player"
3. Option not available

**Comment by InfusOnWoW** [comment]
Yes, Blizzard removed those apis. The apis are now back and we already have a fix to reenable the trigger, and it'll be in the next release.
