### ISSUE TITLE
Temp Weapon Enchant "Enchant Missing" not functioning as expected after 5.3.4-14-g3218903

### ISSUE THREAD

**Issue by TheCheat54** [WeakAuras/WeakAuras2#4216]
### Description

I have two WeakAuras I made myself to track the Windfury weapon imbue for main hand and Flametongue weapon imbue for off-hand on my shaman. These are configured to trigger for weapon enchant for the appropriate hand based on the enchant names, with the "Show On" set to "Enchant Missing".

Prior to the stated version, this would display the icons only if the imbues were missing and it was very easy to test by clicking off the associated buffs.

With version 5.3.4-14-g3218903, the icons now always display if "Show On" is set to "Enchant Missing". Conversely, the icons never display if "Show On" is set to "Enchant Found". Both of these issues happen regardless of whether the imbues are actually active.

### WeakAuras Version

5.3.4-14-g3218903

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Create aura on shaman as Enhancement spec that triggers based on Type: Item, subtype: Weapon Enchant / Fishing Lure, Weapon: Main Hand, Weapon Enchant checked and set to Windfury, and Show On set to "Enchant Missing".
2. Cast Windfury imbue ability.
3. Note that the aura will remain showing.

**Comment by Crelam** [comment]
I can confirm that this is occurring on version 5.3.4-14-g3218903.  It seems to be related to the "Weapon Enchant" check.  I have tested it with Windfury Weapon, Flametongue Weapon, and a Chirping Rune.  With all three they work fine with "Weapon Enchant" option deselected.  Have tried with both the Enchant name and spell ID.
