### ISSUE TITLE
Swipe/GCD for recharge

### ISSUE THREAD

**Issue by Syrato** [WeakAuras/WeakAuras2#4223]
as soon as an aura has stacks for spells, you do not see the recharge time (swipe) and the GCD as long as there is still a stack. could this be changed to look like WoW/Bar's?

https://ibb.co/5sqNGN8

left icon: WA (2 stacks left, and swipe/gcd are not visible, only the recharge time)
mid icon: Bar with Swipe 
right icon: Bar with GCD and Swipe

**Comment by InfusOnWoW** [comment]
At the moment there are no plans to allow that.
