### ISSUE TITLE
Custom Options/Description text wrap length is too short

### ISSUE THREAD

**Issue by EJ-K** [WeakAuras/WeakAuras2#4224]
**Is your feature request related to a problem? Please describe.**
Text wrap length in Description options is too short, making it hard to format for easy reading when using for basic documentation purposes.

**Describe the solution you'd like**
Text should wrap at the end of the frame.

**Describe alternatives you've considered**
Using wago description.

**Additional context**

![image](https://i.imgur.com/NLaFxPG.png)

**Comment by InfusOnWoW** [comment]
The width is a settign you set.
