### ISSUE TITLE
Dragonriding load condition does not move weak aura to "not loaded" section when not dragonriding

### ISSUE THREAD

**Issue by Furydins** [WeakAuras/WeakAuras2#4226]
### Description

For weakauras which have a dragonriding load condition. When not dragonriding while the aura no longer appears on screen it remains in the "loaded" section in weak auras. 

### WeakAuras Version

Weak Auras 5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Create a weak aura of any type (or use an existing one)
2. Activate the Dragonriding load condition 
3. Ensure character is not mounted
4. Observe that while the aura is no longer active it remains in the loaded section

### Screenshots

![image](https://user-images.githubusercontent.com/35685316/211428837-00c525ca-f987-47e4-836b-4502f998a31f.png)

### Export String

```true
!WA:2!1nvWUTTrqujOdbGii1varinTheCaspuaJa32a70CiMksXoqXsLIoY9e9sUlj32v7Uy2L2wP3ekmAVQpbDUN0xqH)cimYxG)e8xqNvuiWiiMx4mdMz259M3uVxZjnPnP)93dQcRGlzWGJc7FWHDHZhKMAy29)V)z(bpRwTA6FGYnAbzAi7CBuQcMqSr6ilFclIovsMWtIS5aZKRe0PxzYju1z)wvt(UAljYKCfmuXL24oDpmSBGU9D3WkV66nskmw1exghPPellGDktAVMuGrjwEYyo1M7Vh6cKelxjnppWyjG1loLl5MCpF8N1BMf4zzmW8GNcRnVybLfxKMgovZG972FyVJ67BrNasbq2EMrZeIdOgVRnfXRE2ry28Zxg1zVrHrJc3li0VaBESdemia5aMXR0lEFgryZ)uzdbgwwWOHD73FEHC9Z7P)A3eFklSY)Dkk7FRP38UjLjkAeGCWj6NE3jjyzKKPrPcLcYNByI0ko3Fqy4G35NQKw9g9a(hA)Rfek2os7WWf4OgWYC03JBv(WRq3ysYFKHIcj1xOi0u9gfgCrdKmLe4uUm7K5UiseIqESLiqK2kysHWY9cseeJPv5wE(ilMuzW)aZzmZncJqNVzTg54knsJfWQjWTo8TiWItuYuEM3CIK721k5ZlFqVlzedBKfyYmB(9kFOVujzxrXnMlJi3(dmmSuQzMlvx7k31FcHl7vUdwq5ULVO8xkFj()R(8i6NC3eRgyjCd(gn0F7xmRkJaxY0fUbGVspIKHsOG32a)GFhLZ80P(972lCHvLGCNRLpQ(fl2Kt1TczgB7xFlsUTJ8NDMcOJbIE241gltbuSH0aU)ACt1TvpxihCJh1jOB3dHPRVGF1Ppk(v4f82fC6st6oJ2ES4nfV)SRWRiSUb6Q5C5Tq1L3EgwwTN6Scg1RxVXcuoZORo9(R7VKlRqo2eVBqPgdKeX7Ra2F20e8ZB9JB9tnp9Jh))
```

**Comment by mrbuds** [comment]
That's normal behavior, same as for In Combat, In Encounter, Alive, Warmode, Pet Battle, Vehicle etc..
