### ISSUE TITLE
Issue with trigger > aura > nameplate ...

### ISSUE THREAD

**Issue by TPhoenixyz** [WeakAuras/WeakAuras2#4227]
### Description

Issue with trigger > aura > nameplate > buff/debuff > filter by nameplate type: hostile > "unit count >= 8"

throws errors and stops working during combat. 

### WeakAuras Version

WeakAuras 5.3.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
2x Interface\AddOns\WeakAuras\BuffTrigger2.lua:1551: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1551: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1544>
[string "@Interface\AddOns\WeakAuras\BuffTrigger2.lua"]:1940: in function <Interface\AddOns\WeakAuras\BuffTrigger2.lua:1849>

Locals:
unit = "nameplate1"
filter = "HELPFUL"
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
}
(for control) = 1
index = 1
data = <table> {
 debuffClass = "none"
 modRate = 1
 duration = 0
 isBossDebuff = false
 expirationTime = 0
 unitCaster = "nameplate1"
 stacks = 0
 time = 5906.186000
 casterName = "Expert's Training Dummy"
 unitName = "Expert's Training Dummy"
 icon = 132485
 UpdateTooltip = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger2.lua:256
 auras = <table> {
 }
 index = 1
 isCastByPlayer = false
 lastChanged = 5885.262000
 name = "Banner of the Horde"
 filter = "HELPFUL"
 isStealable = false
 unit = "nameplate1"
 spellId = 61574
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 New = <table> {
 }
}
(for control) = "New"
id = "New"
triggerData = <table> {
 1 = true
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = true
}
(for control) = 1
triggernum = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to index field '?' (a nil value)"
matchData = <table> {
 nameplate2 = <table> {
 }
 nameplate9 = <table> {
 }
 nameplate3 = <table> {
 }
 nameplate5 = <table> {
 }
 nameplate1 = <table> {
 }
 player = <table> {
 }
 nameplate10 = <table> {
 }
 nameplate8 = <table> {
 }
 target = <table> {
 }
 nameplate7 = <table> {
 }
 nameplate6 = <table> {
 }
 nameplate4 = <table> {
 }
}
pairs = <function> defined =[C]:-1
matchDataByTrigger = <table> {
 Hawk Aspect Reminder = <table> {
 }
 Header Active Buffs = <table> {
 }
 Target Debuff = <table> {
 }
 Stings native = <table> {
 }
 New = <table> {
 }
}
matchDataChanged = <table> {
 New = <table> {
 }
}
```

### Reproduction Steps

1. Go to Stormwind Target Dummies
2. set the trigger as described
3. enter combat
4. move camera a bit so the number of visible nameplates changes
5. aura breaks, throws errors and stops working

**Comment by InfusOnWoW** [comment]
I've created !WA:2!LrvZUTTrq4i4aKaAGGALgdeGEinfTa(srHbA6paTaIks2UqrYLKo25sLwsou7wtT72DxQFCpfDkN1JGo3t6jOWpbecf9bWh6dGFc6SKukoT6GWmZoCMV5B)2Pw76JQhxp(DF2swKG7lYurWNCp1SEjjAWuBfHhrfQtfmUjSzRUbT8whjePXIjC)jmjm46nUTIhcuxBvgm3Oydhck9J(cvL5)SutftAMk4GM6AMjbpsMIC4nzA4iLit2psKXndwgdHzjjbycUU9co2dgdyRpgiPg6n6SWc)tvqcBQN)PT60zbvOnSuMzMQ0cCZ4mZcozeitjgyUwcPPNeRD8SX0oRg((gw)BVgrWXBkXGTTWhrbB6Q(nB4h03pOHxG8X3576jbfXiup)h)HfOB5q6i3JezyJHGs)xjIH)4E3IChO4K0xJmctW)9BVeazdevrgpIHjOl0qAsbhNFFKa0edsngGUebJhme)g93VF(URr3qs0LwyWJF3tK1nWutFnLG8)fv3yYNweS4VeHAebtOYWLJS)IThV8ZT8ut70i)O7uPMIuH6NQvR2o3ugDd4CBCwqp5JlcsYmcSKSOZzXgQBd092YEYMcXfbF76sXZBQq21fN)RzivNmdhuLWGdzag0TBVUTY3vHZxbWksmQag7G)wunmwC2wXU6z)CgjgjiYZcc(aoytNwxeBIqfFUIiNFELrjagZ0SWuyq1mFhbUCVt62TLxFu3f07vENC0XbR32ARIu17SGoN0TL8t)FC8wQSkq(bvt)fFaMSvYNDf80)E9WuXK2k43YaE0StV)x9Lh(1LuG9Gv2)28PZTo2(VomZye8EJbvkz2sB4oaFOH(KI83m(lSon3sFwb(rBIqDThsl6EaLfDj(EuVtXx4hrsHsZomm8EfnWfjpqrdPaBi18w3ubjUDObtLB23BuwQH54A1Y7N)AhVOuIwBTC14uAnwQkeWw4N)GdZyXRolH8MuDZVXl87wq4mRksWFHN2quM2xden4BufJ1dY3f5Xy7JbmL(2TgknGByI1ZT5vu0dChry8259lYoFqojpm)GWegNPP)3WRy8Y7hSEoRrrmEd1tA90ok7Bx04f5)ItESJlwaJJ7vcXOAEtke0lnIOXLpIF44)85S4d7ct8EVqDvIcxWGOh1M7CB59FBBilqd9B61QvxzD86Oz1otCbbUbageIZucBOJIXT1hOEKujLSJ8J3SD1(m5LmnbvUX0LwkGvI65BYyGAA19FD9HVegxF8FDX)(d

based on your description and spinned around quite a few times while being at the Stormwind training dummies. I could not reproduce any lua error. 

So we need some more information on how to reproduce it.
