### ISSUE TITLE
Weak auras crashing on menu open, missing import/lock buttons

### ISSUE THREAD

**Issue by Tsubear** [WeakAuras/WeakAuras2#4234]
### Description

Opened weakauras menu, lua error occured, no import/lock buttons visible. weakauras wont load, when menu is closed all weakauras disappear.

### WeakAuras Version

WeakAuras 5.3.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
https://pastebin.com/WfsyKqVm
```

### Reproduction Steps

Open weakauras menu
lua error occurs

### Last Good Version

Weakauras 5.3.4

### Screenshots

![image](https://user-images.githubusercontent.com/83790136/212281470-d488c9fc-e209-446b-974b-933630419e51.png)

**Comment by InfusOnWoW** [comment]
That error message doesn't look like a bug in WA but some other addon interfering with WA. Please try disabling all other addons.

**Comment by Tsubear** [comment]
I disabled all addons and still get lua errors

**Comment by Tsubear** [comment]
1x Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua:4268: attempt to call method 'Expand' (a nil value)
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4268: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4262>
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4357: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:4319>
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4467: in function `UpdatedTriggerState'
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4196: in function `UpdateFakeStatesFor'
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4169: in function `FakeStatesFor'
[string "@Interface\AddOns\WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:1445: in function `SyncVisibility'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions-5.3.4.lua"]:816: in function `ShowOptions'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions-5.3.4.lua"]:614: in function `ToggleOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:155: in function `OpenOptions'
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:197: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4933: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4596: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4632: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
id = "Equipped Items"
cloneId = "IW_Slot14"
region = <unnamed> {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:152
 subRegionEvents = <table> {
 }
 yOffset = 0
 GetColor = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:443
 icon = <unnamed> {
 }
 SetOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:319
 keepAspectRatio = false
 SendChat = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:267
 SetInverse = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:507
 state = <table> {
 }
 SetRegionHeight = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:502
 UpdateIcon = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:467
 Color = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:414
 cloneId = "IW_Slot14"
 Update = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:579
 regionType = "icon"
 GetRegionAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:388
 SoundPlay = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:249
 zoom = 0.300000
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:410
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:328
 SetGlow = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:643
 SetRegionWidth = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:497
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = 134148
 RunCode = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:274
 GetYOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:340
 SetAnimAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:392
 SetYOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:357
 triggerProvidesTimer = true
 states = <table> {
 }
 Scale = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:484
 cooldownSwipe = true
 PreShow = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:569
 GetXOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:336
 UpdateTimerTick = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:439
 SetCooldownEdge = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:523
 color_g = 1
 SetTime = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:554
 SetValue = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:542
 GetYOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:365
 SetAnchor = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:307
 GlowExternal = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:282
 SetZoom = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:531
 SetRegionAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:378
 GetXOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:361
 cooldownEdge = false
 UpdateTexCoords = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:332
 SetDesaturated = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:493
 subRegions = <table> {
 }
 height = 26.400000
 startFormatters = <table> {
 }
 scaley = 1
 SetOffsetAnim = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:369
 SetIcon = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:450
 color_a = 1
 SoundRepeatStop = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:195
 frameId = "equipped_items9"
 values = <table> {
 }
 xOffse

**Comment by Tsubear** [comment]
1x Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua:4470: attempt to call method 'Collapse' (a nil value)
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4470: in function `UpdatedTriggerState'
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4178: in function `FakeStatesFor'
[string "@Interface\AddOns\WeakAuras\WeakAuras-5.3.4.lua"]:4159: in function `ClearFakeStates'
[string "@Interface\AddOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:191: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:188>
[string "=[C]"]: in function `Hide'
[string "@Interface\AddOns\WeakAurasOptions\WeakAurasOptions-5.3.4.lua"]:620: in function <...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:618>

Locals:
id = "Equipped Items"
changed = true
show = false
newActiveTrigger = -10
oldShow = true
activeTriggerState = <table> {
  = <table> {
 }
}
region = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 IW_Slot14 = <unnamed> {
 }
}
(for control) = "IW_Slot14"
_ = "IW_Slot14"
clone = <unnamed> {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:152
 subRegionEvents = <table> {
 }
 yOffset = 0
 GetColor = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:443
 icon = <unnamed> {
 }
 SetOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:319
 keepAspectRatio = false
 SendChat = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:267
 SetInverse = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:507
 state = <table> {
 }
 SetRegionHeight = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:502
 UpdateIcon = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:467
 Color = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:414
 cloneId = "IW_Slot14"
 Update = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:579
 regionType = "icon"
 GetRegionAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:388
 SoundPlay = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:249
 zoom = 0.300000
 color_b = 1
 UpdateRegionHasTimerTick = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:410
 alpha = 1
 color_r = 1
 SetXOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:328
 SetGlow = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:643
 SetRegionWidth = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:497
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = 134148
 RunCode = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:274
 GetYOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:340
 SetAnimAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:392
 SetYOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:357
 triggerProvidesTimer = true
 states = <table> {
 }
 Scale = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:484
 cooldownSwipe = true
 PreShow = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:569
 GetXOffset = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:336
 UpdateTimerTick = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:439
 SetCooldownEdge = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:523
 color_g = 1
 SetTime = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:554
 SetValue = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:542
 GetYOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:365
 SetAnchor = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:307
 GlowExternal = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:282
 SetZoom = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:531
 SetRegionAlpha = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:378
 GetXOffsetRelative = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:361
 cooldownEdge = false
 UpdateTexCoords = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:332
 SetDesaturated = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:493
 subRegions = <table> {
 }
 height = 26.400000
 startFormatters = <table> {
 }
 scaley = 1
 SetOffsetAnim = <function> defined @Interface\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:369
 SetIcon

**Comment by InfusOnWoW** [comment]
Then we would need your weakauras settings.

**Comment by Tsubear** [comment]
> Then we would need your weakauras settings.

you mean the weakaura.lua file?

**Comment by Tsubear** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10415207/WeakAuras.zip)

**Comment by mrbuds** [comment]
Is it the only error you have? If not, could you make a list of all Lua errors you get?

**Comment by InfusOnWoW** [comment]
I cannot reproduce those lua errors with your settings. That probably means your WeakAuras installation is somewhat broken. The error message don't make much sense.

They appear to be connected to an aura: "Equipped Items" and the first trinket slot, but I have no idea how these error messages could happen.

Maybe try seeing if it depends on a specific trinket being equipped? In any case that aura contains a lot of custom code that I won't investigate too deeply. You'd have to ask the author of that aura for more help.
