### ISSUE TITLE
Icons Disappeared

### ISSUE THREAD

**Issue by MadovyAle** [WeakAuras/WeakAuras2#4236]
### Description

Hi, I was editing my auras and my pc started a random windows update and hence, everything were forced to shut down instantly. When I relogged in to my WoW account all of my weakauras were gone, it's complete black pitch darkness. Are they gone forever?

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
I did not get any error
```

### Reproduction Steps

1. Open up WowUp.io
2. Click 'Check for updates'
3. Run WoW
4. Log into character
5. Open WeakAuras Addon
6. Create new auras regarding spell buffs and cooldowns
7. Click 'New Texture'
8. From 'Texture Settings' click 'Change'>PowerAuras Icons>Hieroglyphics
9. Random windows restart/update
10. Repeat steps 1-2-3-4
11. All of my auras are gone

**Comment by InfusOnWoW** [comment]
There isn't mcuh hope, I'll copy and paste our standard response to that:

If you login and your WeakAura's are missing, go to the World of Warcraft\_retail_\WTF\Account\<ACCOUNTNAME>\SavedVariables folder and check the WeakAuras.lua file. If it is empty, check the WeakAuras.lua.bak file. If that one has content, delete WeakAuras.lua and rename WeakAuras.lua.bak to WeakAuras.lua. If WeakAuras.lua.bak was also empty,  you will need to to rely on backups or remake your Auras.

*Window's hides file extensions by default so you will need to turn these on which you can do by going to Control Panel > Appearance and Personalistion > File Explorer Options > View tab in the new window and untick Hide extensions for known file types 

If you have not made backups or don't use the WA Companion (it makes backups for you) then as a last resort you can try putting the following in to chat in game:

/run local L=WeakAuras.LoadFromArchive local h,m=L("Repository","history"),L("Repository","migration")for _,r in ipairs{h,m}do for _,s in pairs(r.stores)do local d=s:Load()WeakAurasSaved.displays[d.id]=d end end C_UI.Reload()

**Comment by InfusOnWoW** [comment]
Also obviously that's a game bug, you can complain to Blizzard if you want to. The game shouldn't just loose settings on a windows shutdown.
