### ISSUE TITLE
Text patterns like `%s` show as literal `%s` when WA has another text region that is hidden

### ISSUE THREAD

**Issue by 0xjc** [WeakAuras/WeakAuras2#4238]
### Description

I noticed that a buff tracking WA I was using started showing a literal `%s` text instead of the # of stacks of the buff. I believe it started happening after I updated to a new alpha version of WeakAuras. After further investigation it seems like I can consistently reproduce the issue with two text regions, the first one being `%s` and the second one being anything with a `%` like `%s`/`%p`/`%n`. If the first text is shown and the second text is hidden, the bug occurs with the first text.

### WeakAuras Version

WeakAuras 5.3.4-25-g715ce5a

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Reproduction Steps

1. Create a buff WA for any stacking buff
2. By default there should be a Text 1 subregion with `%s`
3. Duplicate the Text 1 subregion and uncheck "Show Text" on the new text
4. Close WA options and observe that the WA shows a literal `%s` when the buff is active

### Last Good Version

WeakAuras 5.3.4-21-g93ee75a (probably?)

### Screenshots

![image](https://user-images.githubusercontent.com/5281913/212605126-eaf0406c-a295-49ab-941e-851f4aaa8c43.png)

### Export String

```true
!WA:2!1vv3UnXXxCSsrTYi9xexkQ8xOQaTuvslPqcMp6hOMn1gcYyNUEHKELZS7EwpdSEMHzM1jgPEb5IkUopc(6ELFe8tWiRQ(aWf9bipb9m7UoaTKiLvNVM587CMZ5NR0S2GAX1IF1NpMfj4DfzQi4INsTFNKenyQOgvkmHWJOc1wcg3eUrJ2bn8NfjePXI94D3JjHDNoxTrCFG65UUDpWOy97dk9)7lvLI)TNzKe8jzkYQtDF1sinLfR))HRDNBV2DxBCmeMLKeGrPEqJwB18XTMMaMiAaE)gMK6ddbeepaiPgQxgNzcLPKrG616SWCFBPGe2((D3QrRw(CYaqx9G80SzSU6Xr1fZcB)j92y9Ub96gSUFWefmOdMwIrOQDVJY0qJ9jrMUfhD3vr31UEiA2hgqpmJxwsvLlIrXgcbf6psed)XPoc7uGItsFcw)mb)3o6zaixhXrKXNyyc6HAinjVJApnw1AIbBhgGogrOp0hpJ(HN3EMzOAij6z9vImE8RoNSMb230ttjy3ENY3h5fYnM)jrOgqWakf84coC4XUV8v0YZ(w3WgIuH6HvQuzHxxyDoO8w)XbDKFCUrsMrGxflABwm20xhvpQixS9H4CJVCwXiYVwIOP5(FAM2WsgHfOsyWIlan61Ut7g2ZOW6YfZ48aJYHXc4FhwweCJ8SnvSxS0VKrIXgdzPGG3P2NNPz522tOI3wrKhSDPqbagY0SWuy3YA(TgJLlUz72n8751jiOZJ838(piy2XPUl7fWfkRODEN848MpC25XbT2SDJxDX3tVNxkyx2Ev8)V(YxHlx6)eLSNHna6nqe3Z9WVR9A2vSFR962B8s5xCsrNc9jrJ6LKkekQDn7PT30w36z3WUEf7xvXEg7TEpPYuS8CJ3GRBN3ST3XE33d(LLc(UugB)UkYp7KWtHwf73B)b7psT3Bk2xoURA)M8jl5LoPtlvqeZTESG9NUG8QNuyXJW1ywupdvbAkYZmYUAL)Aw)uXEnvWZZaE0OT(GRVYQ1lMRCoM4(m)T7aNI7zBwyMXi4DgckK0ySZClG33q)K84NptDOtzJJNjNIl93FUfQNZjnp7buw0Z4GwVq(j6grsHcXwm08I5jWdNibfnKcS(uZl9sfK4MHgmuU58(dYWxMQEoIHZB7v1pkLO1ojpnoe6egRYzdCW3(rYZnNO1Tl9ZmnbhVJPhs4m3gQGFlFTHOmnNcen01OYRUpeNlwEwSJGbdPNJdwPbKJowFGlU87EzVbegVPTFE0wQLzFQD5WegNPP)BZty8I3i8(Q6VxofG3leIbvuo2qK86w2KQ20QE4XnvhBerdlyc)0k)(4lZIF9LcA0nyPTa8NCWfo)3WamjrHK2i0XL(foQyjSPZKdLHD3WVrJ2RMXINmCNT1p)QpPUsldXAjH1VQIXDPbOYA4B2gLTkKs23TH5tsLuYcJDfolhKvpyE7Kodz5Wm1rw4OMwUy9vwBLBETvRFT(3(g1JG6KAd)ZD(N
```

**Comment by lowpita** [comment]
Hey. Same here. Had to downgrade to the previous alpha version and use a WTF backup from before this issue because the addon failed to repair itself after downgrading.
