### ISSUE TITLE
Snippets not working with WorldBossTimers addon enabled

### ISSUE THREAD

**Issue by nullValueReturned** [WeakAuras/WeakAuras2#4240]
### Description

The WorldBossTimers makes the snippets not work properly.

The toggle snippet button was still there and toggled the panel, but the panel had nothing in it other than the "add snippet" button.
Adding a snippet still worked, but didn't display in the list until i turned WorldBossTimers off. When i turned off worldBossTimers I had several snippets that i had tried to add while the functionality was broken 
There is no LUA error.
![image](https://user-images.githubusercontent.com/47422133/212727780-c86768b8-eabd-4f25-848b-c81df5bc3a13.png)

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1.Install https://www.curseforge.com/wow/addons/worldbosstimers
2. cry due to lack of snippets

**Comment by InfusOnWoW** [comment]
I can't reproduce that. I installed that addon and the snippets are there.
![Wow_toEMNM2ZVU](https://user-images.githubusercontent.com/12950521/212775215-90dded18-12c4-4822-8e9a-677bb9dab04a.jpg)

So there we need more information on how to reproduce the issue. Did you have only those two addons enabled? Does it depend on some settings in that addon. Can you try with empty WeakAuras settings?
