### ISSUE TITLE
Layout of pending updates borks when first expanded in a session

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#4242]
### Description

at a glance, it looks like there's extra (empty) items being added to the scroll frame. But, /fstack doesn't reveal any frames.

As a workaround, either collapse & re-expand the section, or don't start the session with the section collapsed (in which case, the issue will appear briefly but then resolve itself).

### WeakAuras Version

tip of main branch

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
none
```

### Reproduction Steps

1. install at least 2 auras which WeakAuras Companion believes are outdated, and ensure that the "Ready for Update" section of the aura list is collapsed.
2. get WeakAuras Companion (or cursebreaker or whatever) to prepare the update
3. start a new game session (i.e. reload or log in)
4. open WeakAuras Options, and expand the "Ready for Update" section

### Screenshots

![image](https://user-images.githubusercontent.com/24878501/212771131-f3a1e012-09dd-4f15-b52f-916eb6b41aa0.png)

**Comment by InfusOnWoW** [comment]
My guess would be that the data structure on which the layout function runs contains each update button twice, so it assigns the position twice that would show this pattern.

**Comment by emptyrivers** [comment]
hmm, i do have both companion app and cursebreaker on my machine, perhaps this is a stupid collision? i'll see if that makes a dufference

**Comment by InfusOnWoW** [comment]
No found the bug already, it's nothing big. My guess was correct, and with that not that complicate to debug.
