### ISSUE TITLE
gladdy breaks /wa 

### ISSUE THREAD

**Issue by pimbeenes** [WeakAuras/WeakAuras2#4248]
### Description

since the game client updated to 3.4.1.47612 `/wa` no longer works while also using Gladdy_Classic_v2.22-Release.zip

Disabling gladdy fixes this issue.

### WeakAuras Version

5.3.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
6x bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
[string "=[C]"]: in function `CreateTexture'
[string "@Gladdy/Modules/ArenaCountDown.lua"]:30: in function `?'
[string "@Gladdy/Gladdy.lua"]:174: in function `Call'
[string "@Gladdy/Gladdy.lua"]:311: in function `OnInitialize'
[string "@Gladdy/Gladdy.lua"]:108: in function <Gladdy/Gladdy.lua:106>

Locals:
(*temporary) = "bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))"
```

### Reproduction Steps

Steps to reproduce:
- update game to 3.4.1.47612
- execute /wa to open the weakauras ui

Expected:
The menu opens

Actually:
Nothing happens

Disabling Gladdy fixed the above issue

**Comment by InfusOnWoW** [comment]
Then report that to them not us?

**Comment by pimbeenes** [comment]
I was asked to open this by one by @mrbuds 🤷

**Comment by InfusOnWoW** [comment]
Well, he probably assumed there was an error in WA. But the error log doesn't show anything in that regard.
