### ISSUE TITLE
Reordering triggers can break conditions

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#425]
To reproduce:

1. Create any aura with multiple triggers.
2. Add a condition for any trigger.
3. Change the order of that trigger.

Expected: condition updates to point to the new location of the moved trigger.
Actual: condition forgets all trigger information, but retains property information.

I'm not actually convinced that this needs to be changed, but it is unintuitive behavior.

**Comment by InfusOnWoW** [comment]
Well I wrote code that should have handled that...

**Comment by InfusOnWoW** [comment]
Fixed
