### ISSUE TITLE
Attempt to concatenate a nil value

### ISSUE THREAD

**Issue by djfbryant** [WeakAuras/WeakAuras2#4254]
### Description

Error occuring after latest update whenever options opens, weak auras do not then appear to render until reload.

### WeakAuras Version

WeakAuras-5.3.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
https://pastebin.com/7dUaMdRD
```

### Reproduction Steps

Login
type /wa
error displayed in bugsack

### Last Good Version

WeakAuras-5.3.4

### Screenshots

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10452160/WeakAuras.zip)

**Comment by mrbuds** [comment]
duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4251 and https://github.com/WeakAuras/WeakAuras2/issues/4250
