### ISSUE TITLE
Some Premade Auras for Shamans not loading

### ISSUE THREAD

**Issue by unaetnumitsirc** [WeakAuras/WeakAuras2#4257]
### Description

Two of my premade buffs are not working anymore since yesterday. I only picked some premade icon buffs to show up when they are active, but the ones for Stormkeeper and Flux melting are no longer working anymore despite the fact that they were working two days ago.

Other auras using the same setup work perfectly.
Creating another aura of the same type does not fix it.
They are always shown in "Not loaded".

Please see the attached screenshots.

### WeakAuras Version

WeakAuras 5.3.5

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Go to premade auras for SHAMAN.
2. Select any Icon to display, then select Buffs.
3. Search for Stormkeeper or Flux Melting.
4. Notice they are automatically places in Not Loaded.

### Screenshots

![image](https://user-images.githubusercontent.com/123090975/213472689-fc383554-06ac-4444-9189-74594fc559bf.png)
![image](https://user-images.githubusercontent.com/123090975/213473106-ada8bfc3-a99a-46a5-a60b-2280222fc869.png)

**Comment by Icytroll** [comment]
I'm having the same issue as of today after updating addons.
