### ISSUE TITLE
Item count weakauras not updating properly with current wrath verison

### ISSUE THREAD

**Issue by wendybird** [WeakAuras/WeakAuras2#4258]
### Description

Apologies if this has been asked and answered already and my github search skills have just failed me. 

I have a couple of very basic weakauras that trigger based on the presence of quest items in my bags. Specifically, the phantom ghostfish and the wrath heroic daily quest items. I have created a new aura since the recent update that does the same thing, but it also does not work, so it isn't an issue with old auras being incompatible somehow.

Examples of the issue:

The Ghostfish daily. Loot the ghostfish into my bags, and the WA does not trigger. If I /wa and then close the window, it does trigger.

Hearthing back to Dalaran with the heroic daily item in my bags, and the WA *does* pop up when I enter town. However, when I turn in the quest, the WA does not go away from my screen. (https://wago.io/d_WlzrRUg)

Edit to add: I have tried it with weakauras as the only addon running and with the item WA as the only WA loaded and still had the issue, so it is not an issue with interaction of different addons or other WAs. Downgrading to 5.3.4 **does** work, but I'm sure that probably breaks other things, hah.

### WeakAuras Version

Weakauras 5.3.6

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

I added a trigger for fountain goldfish for the fish alert WA I typically use to make reproduction easier. Feel free to use any other item ID you choose, though. The results are the same.

Verify trigger not triggering: 

1. Start with no fountain goldfish in bags. 
2. Fish at the dalaran fountain until you get a fountain goldfish.

Verify trigger not untriggering:
1. Start with fountain goldfish in bags. If WA is not triggered, /wa, enter, close window to trigger the WA.
2. Sell fountain goldfish to Marcia Chase, trade to another player, destroy, etc. to remove from your bags.

### Last Good Version

Weakauras 5.3.4

### Export String

```true
!WA:2!LrvtVTrXB8ACQQ1gGM4MAOqPKGqve(dLsrnh4qL8660wW1oD3nKWjVZU74DNK1ZSmZS2j5as1hq9S)iyXP)Ily(eq(emYcXhG8rih6zEMXRdTfFy9Z88(B)EkTD1(vJQg9IpDcjKrDz58q8nVKtilLX)UYWp(XD61tGL)6vNIOHjm(omcvg0OzBVMoZczS0i2qQ7qsg2)0fpBgfJtS1E0FKKtIJXCb928cYxAlpodBtK4(JZf4UHSCQ0)mrEaEaMkDZ71JC00UnQ76111RUJ3zgn6YYWCKKXR(GSv12fJPyoj0nHnSd1)unlTpBJ6J9DOWxHLDoLidYsrhJ5ogVu9UJez400NejSCmXBYtaJwVHw4f5WoCmKdoU70SvRzVwCoty(RrrLoAreR8hTNeHdGC3dko(JB2ANT3T1yWPZlARBRSEPAz1BREhF17QUQ6JvRRw1xv1xDnl1hO(qvTQ3v9EwQBQ(i1AQRREF1nu3QYVVIALQpqTX)XCnxWCTwAJbF8g2do(wv())SjoBynnIioiNgkjdW3drpoBvKH2BE29uwe(3U05WKfZPO0FaMxeg95NFigNvh6xHshKKWsgJOK(Ak6wocjIl3wTSnLrXNIrcSRKJPXYKRmlkNB0QREsZfyytismsRJU7O20UpIqbBvBQ(8RO(FQVq9LQnd6rOerYBYgARcKu7qCYeya5GJbpl(2AQLNbpdqHhgZHPx0lwlRQeFKSRibbZM9NV4wk7ggMMp9yCi97kkiuBo(czbUpUUZ3Vr2kVIlAyGbLkvQ8zZ5It7z2)TRVRxNSRzyIYLmDpjCpsKmXUo8885bJCeoYW85ZMJD(XIu6uJ8dYfssVJvxEcNjHQZdyA3Ut7MQL5qHP1zIrX)fnoUOkOYSv2Mtoz9NLJIGodADpVxR4xePzgEdz8O94OSr7vqmpbgqeKGuSFrn)k47t7SlaV7A3XZRZtNDrqDjNG3OOw2)1IGwQzXhmS1tA38VNfNYgUnh)t5yA4X7S0DVZ9U)86slqdwFuArdozKML26zb5sjJ2zaMdq2jA2TmBuxFQMErrnoEHPMMIr2I0Xw)W3OHBikfx2KiEjKWdPyHOSrslcqVQX)2qhbZtcsWK4e5svStzOOFjBfnUwV8cfajldhvlqqOXP4hUr2AlU08QY9NQ5EcafGlljbsi0uznN(5PsIfVG)BzRXs1urwoHPiHqtzlGMQMiqyU(gq6NX4YjCZAUbUuHRbRWo)wQpZYgajsl1xznAX12KXxSxQUSdknlbvoBTfs1BvpKiqWGokXzOEDCPktKSWbZb5vg8NFcjA8Jsyczpa(DVCs00N91bpQF7dcE8HBLvfkSfN7G7eWHaS)5Z3b2Mdx(0PyGBdNMnBZpQykeaa(EKyloHQddozgGsad6KzQdRP90wc3lGv3Yt0xhifci05qt4vTPaziUP(GSW3(egRFPQcN7FNV5oBvDWFT))8d
```

**Comment by emptyrivers** [comment]
this is a bug from blizzard, see Stanzilla/WoWUIBugs#381

**Comment by wendybird** [comment]
If that is the case, why would it work with 5.3.4 today and not work with 5.3.6 today? In both cases, the fish was looted into one of my non-backpack bags (my default bag is full).

**Comment by Stanzilla** [comment]
We started using a different event for this and that is broken on 3.4.1 on Blizzard's side

**Comment by wendybird** [comment]
Ahh, that makes more sense. Guess I'll keep using the older version of WA for now and hope for the best.

**Comment by Necro87** [comment]
this is still a issue in 5.3.7, will this be fixed at some point or?

**Comment by InfusOnWoW** [comment]
As far as we know Blizzard fixed the issue.
