### ISSUE TITLE
Maybe unnecessary trigger updates for aura triggers

### ISSUE THREAD

**Issue by Nercus** [WeakAuras/WeakAuras2#4263]
### Description

Because the BT now includes all the UNIT_AURA payload info, there are way more updates for the text as well as the amount of `TRIGGER` events.
Even though having updates for changes is nice some might not be that useful. Especially things like index changes have not many use cases and are disproportionate to the amount of updates caused.
Another thing I noticed it is: Using "Fetch Tooltip Information" becomes useless (besides being able to use %tooltip#) as the payload for UNIT_AURA includes this info. 
_(The issue with tooltip info seems to be inconsistent as the TRIGGER data sometimes includes the tooltip and sometimes not independently from the setting. Don't know why this is.)_

### WeakAuras Version

WeakAuras 5.3.6

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Minimal example (set spellId in trigger 1). Prints the Trigger event when according event has been fired, prints "text update" when ... text is updated :smil
```
!WA:2!1rvZUTTrq4iOdfGWhCekmAtlALvACTrlcGCrDqZntxshxOyPqrhNEPkl5ouCtj3DXUlDSYTkuu0Z6rqh6PEspc9jyHrFcYJGFc6SKQjbbX8cN)25B25BMTvyNYo0o0)CpLOYuW4GA4zXdo50GOurHq9tTXVvuMwwqMfdxA6DV0LPvAJO0Pj3pRINAyc(U751f)Kkg3SBpd6RBLKsmqVghkWuP4EaNELoNqfV8NhMLPbZNFRveEAUqnsGNm5OGtJdIKDFheNKjuLeZe5edRewR1sU5BRIZQbkcUa4MxtQqRedl9Cg1K7FiQQi1LO(GiTHOmEjzmotN75J)mEZnk20PGs)l7Owl(xQknCkPeE(csLIWrj9Ds63)hoOFF7gjpcifM8xRRsQHCKcYyxgnEuWGbZ1sOO4eQ27nUhxLHUxn5OdhhpzC8HrX(viUjU7hOIQtUNVzMeICGT)skKGhjgnOEuWGrHNnyrfFDL5TJ9JVWUDsZLVba9I4Oto(4GOh2FvJ9jUSz3W(f2V0Ex7xz3r(1VHNG3LOG3NC()eKZOqKRFtT3ZZX)VO(8xa7t4ZK3Mulh3utpwqH)(wYE3mNvkOtuif9C5o3CqfWus6SjzfcHkFHgkYAgj8hghp8X(zcUrUzOI9QUpPIqX0r6ghl)Spqctxl4ZfCWVqqOHjgsb2Q2kQSQWW88rAkDl7d9IsliATtYxZEf4eM7qAmQ8PRNuFwZKA7piwY1c2VDPcMInyhV57M)xq4m3GOGFGDZW)biAySrb8PM8pYUT9bxrr225UMTuAivWP65U4C5W(a)scJhA)X6OTb2q7X4)B)(wUgBsGItkEkMemD)M8U3CtwQGuMlQ2lDWXQ3l8ux2CfBLGgZyt9uVahdyzZ8heegV0isVOj3FsR)yzpg961dCDHljLYcq(n3mI0z4eolDIjxb6CrbD2QmfoZJ9cKcBFDZ2FOZK7ANm(OOGGtvZwxr7xXORk39jJEA)PH0P7DfUFJXpu2u5ZFPqrpxrKZpFTWQgs7O6xVA1Qv7L42hqRFn433yfJ3uE4P9wIROr1KM(oBz3(kunHK(RtXNc50o6OV)(F39pOZf)7Z(V
```

### Last Good Version

WeakAuras 5.3.4 (i think)

**Comment by mrbuds** [comment]
Indeed it retrigger when index of aura change, this is solved with https://github.com/WeakAuras/WeakAuras2/pull/4244 where there is much less update

**Comment by InfusOnWoW** [comment]
There's no bug there, a watching trigger obviously reacts to all changes.
