### ISSUE TITLE
Bug when enabling "Overlay Latency" 

### ISSUE THREAD

**Issue by ki-88** [WeakAuras/WeakAuras2#4264]
### Description

Getting an error when I enable Overlay Latency option under "Player/Unit Info > Cast > Player" 

### WeakAuras Version

5.3.6

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Trigger > Player/Unit Info > Cast 
Unit : Player

Scroll down and check Overlay Latency.

![image](https://user-images.githubusercontent.com/117937940/213843561-7fb8a9e1-739e-451d-afe9-4e6634dbf683.png)

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release.
