### ISSUE TITLE
WA bug. Incarnation talent, feral druid

### ISSUE THREAD

**Issue by flipliip** [WeakAuras/WeakAuras2#4265]
### Description

I am trying to create a timer that tracks my "Incarnation: Avatar of Ashamane" buff as feral druid. Unfortunately the timer does not appear when the buff is on. The timer works good for the basic Berserk. But when the Incarn is talented it does not.
I noticed that the timer is working for the Incarn talent as guardian druid, but not as feral druid

### WeakAuras Version

WeakAuras 5.3.6

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
No Lua Error
```

### Reproduction Steps

1. Create Icon Aura
2. Set the triger as "Player > Buff > Incarnation: Avatar of Ashamane
3. In the Display menu create Text that tracks the progress of the buff (%p)
4. Use the spell "Incarnation: Avatar of Ashamane"
5. the weakaura doesn't show the timer

### Last Good Version

N/A

### Screenshots

N/A

### Export String

```true
!WA:2!1rvtVnory4efTAfgPQLaQIfHwclFibhwjkIEGtexCuBvjj44(bNCg751XdR9mJMzCAtV1CaTNZ)aYboXP(lyv)fyfXpa0EMt9xaVJDs3ke1hSN3x)(XZZ7htZETZBtBtF1NTKfl4JefQy4JBSIuysfQbsdtW1oQzdss0Gz)FW8p9FDJgnVMWJX)puW4MO986h45VkwiYOIZ5JoNjHX3Sr0JobsvK4QiTRV2qughxgNzCIsWp6uN5gfBYeqP36lvRp(hUMzsWNuOi7SW(MtYb9hj)Kd4XefNyJ233P7ucgUoIKoD1PKCch8HPacP9bsMj9n6IOk5HkiHDH)OHEhD0CTeYYoGQDClqqejZiZaLQqd9Xum2Vkro356OIe01Rd3R7OGWrbD9dwsHiuzaIp1(EhnS3XhTOGVg3oY3Zs1PqqT8pjOWF24wSmbiQZobjjI8RU9Lai7Iij24B5s6cnKLuvolFeManXGC2aPlrC4dtS1UVE7YTwHIrK4xorjk40x9u5NAGlmHvVseQCIjugAy5qOubXmBUAT4otE(xiLpPscRwyVzprMqDyZMnB9MATBWGB3JdgiF)kL4KGaJll(ug1K62ffVToFSlaALYRwvpo8l1tjnVP6))AH2WsMH8rjmixcqLU9h03t(5peOZGjK4zHjzcHkTClfYwRvYV6HCGodBxS4qtQc0P4a3SLvwfxXSw4ZI1EXnYN0tXUSZpxqOyPL0jiq(0)N4wFW3gEQS99QwByNSZdHMCbn021gVQ6NNlu0tve58txFOUUmfBlrzW41TI7Tjv(i5ZEOyxl1C1D0PA(BWXbhDqFV3QDe7saw3ooBdGVpl2Omkfytsnx5Mji0EUA0VT9ZlYmmhx7C52Lh64hNr0A7PidjdxgShxQQghTP31ELH8d2SPBBW)ittqYrhRUyZvgp73)7g4Z8nMLUGWz5vBW7w(o9k3YLl4WnardJmkGpXK(4vu74pArO9AaLgWer1ZT2ytCzGBoHXrFldkp(XLNuEA5z4X39)QX9sHiVPpjtMsAT0iINwVa(Hn)TLpNrR6Yk)3oTCDIcx)ryGdiTUTUm2ZQYM1Or75751pcXscBIZofm615FZoN4D4Sbho8sfJBJoKkBJxMS3A2Ixa4Bhj8pVAtzPLiS6BvVMXR7QOKt5GXT1(F3l(2xSB7P)1z)7d
```

**Comment by InfusOnWoW** [comment]
That's because you gain two auras that have that name, you need to use an exact spell id match with the id 102543.
