### ISSUE TITLE
Dynamic Icon Info does not work for certain auras (which all have icons)

### ISSUE THREAD

**Issue by FireEmerald** [WeakAuras/WeakAuras2#4267]
### Description

I wrote a really simple symbol WA with two triggers (OR combined). The WA watches for two Debuffs which are **not** present on the target. If so the WA should show the icon of the debuff which is missing on the target.

1. Trigger: Aura+Target+Debuff+IsMissing, `Name=Improved Scorch` **OR**
2. Trigger Aura+Target+Debuff+IsMissing, `Name=Cone of Cold`

The WA shows the correct icon of `Cone of Cold` if it is missing.
The WA does **NOT** show the icon of `Improved Scorch` if it is missing, it always displays the placeholder (?).

Example Video: https://streamable.com/zz2npl

It depend on the chosen Debuff **AND** it seems like it depends on the client language (mine was initial German). Another example which does **NOT** show a icon is [Shadow Mastery](https://www.wowhead.com/wotlk/spell=17794/shadow-mastery).

### WeakAuras Version

5.3.6

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Import the aura which was provided below
2. Select any NPC, the WA icon should show up
3. Attack a dummy npc with Cone of Cold or Scorch as mage to see a change

### Export String

```true
!WA:2!DrvZUnsrq4ymOadIqI3Lisesywe7rRvzzJeCcpg7eJCSdZmHK9YA3EMEMU3mU7HU7XoohqS(0E2pc(mCXh4mKNGwwiEa2hH8aauDB7WUmh6P6QQUQ6R(RqJsdkfvk6LF(mAiN5ZZfH4pzJfOCfHl6KPOCM0rmUtCSeRo(Biv28N3yJ3AoIfcYpLtzQ(1Q3oOU3IqopnIpI5pIMH7DZ6R1JsWebk0APd9KkKq54szuLt)y4NK4mrjOjjyH8zpuSI83CvJZWEOCb6GPMtgAawU)TnhKj4dXrL9d5IqYIbivibl9j8rDylK2FNqLsklXdpedr3XyuQI4zFVZezgonTzK0XnhIG(qWKGvICjUniV3RK59TVYppoME18U1Q6h01pOQxWDIovGbrE(NwVvRzr4(GMbqOkoUQ3jnoR10C2ki48q9heR3VNE79VPgNHlZJlxdYj6pwVNUK(E6T0FO(t1L1FMZ8iQ855mihneFaInoBhKLoyPLoHhH)LnUfY1ybdL(dqMcsMV42lX4SQaIcvEii9sMkXPX2AI(DGqtIuqItHjZGy3dNykaF9U6Twax7JcVmrWZzrV8(zLu4RuDLeeuVUyzLUq2EwM2JyUaYZDLRiCzaAMEN4h8fYSTFnlayKl(Ucfku8vl5UoOCREwqNS7zzc9xCWu0WZPrkIBv46Tl9f9kCKL5lwSSj7PRIOBSYFEUurJhdauWva4caMUT70UUElbGlJoZSkgAdJIW30vGGPY2UHGED5Vphfbjgu5GG3a7R90clVrCr05cu2KZxrSmagsL0(P4ERW8RniKTtZ2TR711TtqqNt8AE0XblUZ1(0RX7Tcrx8g(Xi12b15SGwnBx)VwKKYh1qG)XCmlC8PV9JQCWtwIoJG5MJ1wyI5I5Xl6NRuCwNHyrkA8md7wywII8rw9xJSPMl1UlZCd04F0AoexJqIvf)qukUOnqci0WlzyPSOvslkqVJ1bUqEbli9jyAcb2n05F(7nGp3uokQHRea8UEdYtvuhxtt6U6N64fMIKsdfm6LcttgYzcBVPbgUMLqz3F9UdtX9BPseKVJiIRwTe63)PGFTm4OjRvR3ueJA6M4Sd1VxdyWQYnyKe7Re2CWMlImdcG4UMTkcjg8sKCIrhJx1vChGOm7d1HBQJ0yDmq(()FoUxZ5dk4HsZiOIZu8WHlhfF3H)XdOrIG6(bnBFK3)16npwa7vG4a62kE7YQFddlJB77xZRE929HGjMM4CqonA(rJR)O0V6ltB6(ybLzmpMKvckt1wHvyxamSJ75nYoJmZGe6YT0ZPSLdOWTDNywnL0IN0t)SELKEpPYJRCyPH)5f)l
```

**Comment by InfusOnWoW** [comment]
That's not a bug. If an aura is missing there's no information on what icon that missing buff would have. We do have a system in place that tries to guess at the expected icon. But that is not expected to always return an icon.

I don't have a mage on wotlk to check, so I can't check the specifics. But this falls into expected terriority.

**Comment by FireEmerald** [comment]
@InfusOnWoW And why does the WA also not show the debuff Icon if you switch the trigger to be enabled when the Debuff is **persent**?

**Comment by InfusOnWoW** [comment]
I'm not aware of any bugs with icons if the triggers check for that.

**Comment by FireEmerald** [comment]
> I'm not aware of any bugs

Because of that i opened the bug report. As i said, the WA does not work when it watches if the debuff is present.

**Comment by InfusOnWoW** [comment]
You haven't even shared the aura that you think is behaving wrongly. And I think it's much more likely that the error is on your side, because we would have gotten bug reports if it was that broken as you claim it is.
