### ISSUE TITLE
Running out of a reagent keeps "Insufficinet Resources" from being true

### ISSUE THREAD

**Issue by uplime** [WeakAuras/WeakAuras2#4269]
### Description

The following Priest aura (attached below in the `Export String` section) is a simple Icon aura with 1 trigger:

* `Spell` > `Cooldown/Charges/Count` > `Show: Always`

and 1 condition:

* `Trigger 1 Insufficient Resources` > `True` then `1. Glow` > `Custom Color: Red`

If I set the `Spell` section of the trigger to `Power Word: Fortitude`, then the aura will glow green normally, and switch to red when I run out of mana, all as expected. However, if I set the spell name to `Prayer of Fortitude`, it only works if I have the reagent on hand. If I am out of the reagent, then `Insufficient Resources` is always false, whether I have the mana or not. I don't know how it worked in previous versions, but I'd expect `Insufficient Resources` to be true when the reagent is missing.

### WeakAuras Version

5.3.6

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
No Lua error reported.
```

### Reproduction Steps

1. Install the attached aura.
2. Remove all of the reagent from your inventory.
3. Use a spell to deplete your mana.
4. The aura will continue to glow green.

### Export String

```true
!WA:2!TrvZUTTrq4iWwudIIay5gJ2GEqifWOThekCqCVvatvjNyOAlSujn5K1YLdjxyQDzMDPKvUzDkN1JGo3t6CVu)eqiu0hG(i4NGolLKbAr1bXD(FNVVz2g9AoUzCZ4p(nlLcTkuxIc4RF0AEPntJxwyLALXhNDzsIbSnwXvcs)aTuzJ609IHDzRfADESEQkCQSagD3oXUXPqwGlPJMBrzAkGMhFeU94h3FbVe5k(yW80IdgG8za2sN0QNgTsBzmSEm3kYatyME6LQLg6ZP5t5ZmRtbfGsXgdvpMvNe)LXquzsYWzfa(YU9h0719dSKaZua55)TPmcMakBi5J8Mvx150WHxfo8u2qwT(IVQZ2lERbOofbJP13g6c97Ei2biqXYch0TF)1iWZRTFbv(QpFDPbUYStE086JVk24xSVZY)6opcjvo3Yw8qe797pBHZrlYfxpkOujTrf5ouzrPAlOr5IlSYjWWnY)Iog(ThDpXfaQ45VHqyIUU9(RbO4ukZclJteivfipPMZQ(ucMmClb9wiBj1ymi1rXF)HvhSMeJOQNI6sv8FTonxpThcVVeuIzd(KFO9XVO6aKCYzyL7V3UDSyUtWH8SbYBG8LoX(Gk1M9KA)E3w)w4e6OZ145n8A4Dh1WNTtZOaNXr1vDyMuCTIOaV6icf8CyZX(ss9(1fiqJXaMfLbY0m7Tb5AE8BQXqfXwKblfLYEiBCzUv6Ze5CJ5WQFYpWbnBoi)a4oSeRrbxhuTxWh06XnwWvYXo0tDcZy5OT3Da3aHwSUV(SQdcuAfSo2bLKxx5M1qdqZ7XM5oxRZ2zbJ5svVQEuavNv9YQxvDE1zrjsL0K9FvVsQs04MQ6J3Sf0k(IDRudHBS)S0WJYH4m0nkqm3jvD9R67hqz06V0Qft2mgS3K)4zY4IV8)z1Q1qWyzIAEWJ(X45fzCp2uzSn72JlLXRsI(1(V)1p)D2FuhrTuIm1hLkxQHSIMeiVBBHMbPHmy09BEzOhsZYUopkSdRB3lw6Wdz9f9PhXO9zX1Nu57nFchLU(O4jsLXTskKexXat9dqg2eEEj4HImUkLEH4OQOZ9A0WBEbQjy2o7EAmS9XTFyEA(omkBvI7kq8e3Y9AAyVO9ZBFsZj)5B)N
```

**Comment by mrbuds** [comment]
Correct condition to use for your case is "Spell Usable" instead of "Insufficient Resources"

**Comment by uplime** [comment]
Thanks, that does work like how I was expecting. When should "Insufficient Resources" be used?

**Comment by mrbuds** [comment]
When you want to check if you have mana/power/energy/rage etc.. to cast it
