### ISSUE TITLE
Add sync read numeric order under Condition Trigger section that reads from Trigger section Or give sub arrows/up-down under Condition Trigger

### ISSUE THREAD

**Issue by wazerstar** [WeakAuras/WeakAuras2#4275]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when when editing or modifying triggers section and put them in nice order from 1 and down in numbers, then I add the same section under condition > triggers

If I then start moving triggers up and down to different places or even delete them, then triggers under condition will no longer be sorted from 1 and down in numeric trigger order.

**Describe the solution you'd like**

Let condition section when trigger is set under condition sync with Trigger Field in numeric order all the time and OR perhaps give us a SUB ArrowUP/ArrowDown for each trigger inside conditions to let them be set correctly and follows the Trigger section in numeric order.

If  **Trigger 1** and **condition > trigger 1** is the same

Then if you move **Trigger 1** under Trigger to **Trigger 2** then **condition > trigger 1** becomes **condition > trigger 2**  but is still in the top as Trigger 2 where suddenly Trigger 1 is under Trigger 2, it that make sense?

**Additional context**
I made a video to demonstrate the issue..
https://streamable.com/y98xrz

**Comment by emptyrivers** [comment]
Condition ordering serves a different purpose from trigger ordering (and neither order is merely cosmetic for that matter), what you are asking for would break many different setups.

**Comment by wazerstar** [comment]
> Condition ordering serves a different purpose from trigger ordering (and neither order is merely cosmetic for that matter), what you are asking for would break many different setups.

That's why I had a alternative option as suggestion, to give us up/down arrow inside condition > trigger, would that not be OK?
