### ISSUE TITLE
Convoke the Spirits cooldown not working properly

### ISSUE THREAD

**Issue by zmoothrc** [WeakAuras/WeakAuras2#4282]
### Description

Sometimes works but stops working at the worse possible moments.

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Simple aura with trigger Spell > Cooldown/Charges/Count with spell:Convoke the Spirits cooldown does not always track cooldown. 
Every druid aura on wago i tried is affected by this

**Comment by wing5wong** [comment]
Use an exact match for the dragonflight spell Id for convoke, or go to shadowlands and change your covenant away from night fae

**Comment by InfusOnWoW** [comment]
I've now created a bug report for blizzard. I don't have any idea whether they even agree that it is a bug, if it's feasible for them to fix, whether they'll fix it. But that's all I can do for you.
