### ISSUE TITLE
In code editor, if a trigger is found, let us see a popup with the trigger information when hovering mouse over it

### ISSUE THREAD

**Issue by wazerstar** [WeakAuras/WeakAuras2#4285]
**Is your feature request related to a problem? Please describe.**
It can be a mess to figure out what the trigger is and what it holds inside, without going back and fort from code editor to the trigger.

**Describe the solution you'd like**
Hover over trigger in code editor that has been found and let it show us a popup what's inside the trigger

**Describe alternatives you've considered**
n/a

**Additional context**
[A raw unpolished picture of an example of popup showing up at either mouse or in the middle of the code editor](https://i.imgur.com/Y3UfwHi.png)

https://i.imgur.com/Y3UfwHi.png

**Comment by InfusOnWoW** [comment]
That's basically impossible.
