### ISSUE TITLE
Game start lag and weakaura gives error when in pvp

### ISSUE THREAD

**Issue by neuvo123** [WeakAuras/WeakAuras2#4286]
### Description

Start witness 2 sec delay and buggrab gives me this error, I dont use the press and hold function and I use bartender4 as my hotbar addon

Doing reload in the pvp removes the lagging but next time I join another game it comes again

[ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'ActionButton4:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:330: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:392: in function `Update'
[string "@FrameXML/ActionButton.lua"]:342: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:801: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:196: in function <FrameXML/ActionButton.lua:193

### WeakAuras Version

weakauras 5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
[ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'ActionButton4:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:330: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:392: in function `Update'
[string "@FrameXML/ActionButton.lua"]:342: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:801: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:196: in function <FrameXML/ActionButton.lua:193
```

### Reproduction Steps

going to instanced pvp and press some button but i cant tell which exactly causes it as it seems to start random

**Comment by InfusOnWoW** [comment]
Nothing in WeakAuras interacts with secure buttons, so you have either some auras installed that are creating secure frames and in that case usually in the options window you'll see an error message on the aura.

Or equally likely you are just encountering a game bug, that blizzard didn't want to delay the release for, the 10.0.5 patch fixes some of these bugs.

At this time the game so hopelessly broken in regards to taint that we do not investigate those issues.
