### ISSUE TITLE
add line numbers to code editor when in expand mode

### ISSUE THREAD

**Issue by Ragnoroct** [WeakAuras/WeakAuras2#4289]
Not much to say. I know I can see the current line if I click but scrolling it's hard to tell where I am.

wotlk classic

**Comment by InfusOnWoW** [comment]
There's a line number in the top right of the current line.

I once briefly looked at adding line numbers, and it didn't look easy.

So it's not something we intend to do, unless someone comes with a PR.

**Comment by Ragnoroct** [comment]
I understand :/
