### ISSUE TITLE
Long cooldowns shown incorrectly

### ISSUE THREAD

**Issue by MuunJuze** [WeakAuras/WeakAuras2#4294]
### Description

I tried making a weakaura to show the cooldown of the trinket: Ruby Whelp Shell, specifically, somehow due to it being a very long cooldown, the number for the timer is shown incorrectly as 50 or 51 days or some negative integer around -36000 seconds counting further into the negatives.

https://imgur.com/a/z9HW7O5

After making a help post on the Discord I was told to make a ticket regarding this, since some workaround was made for the Classic version in relation to profession cooldowns.

### WeakAuras Version

WeakAuras 5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1) Equip Ruby Whelp Shell.
2) Use it.
3) Make a weakaura Icon.
4) Select Item as trigger type.
5) Select cooldown progress (item) in the dropdown menu that appeared to the right
6) Type in Ruby Whelp Shell or the ID (193757) in the Item field.
7) Go to the display tab and scroll down to the display text field.
8) Type in %p
9) Click Format Options.
10) Select Time Format in the Format drop down menu.
11) Select any of the format options.

### Screenshots

https://imgur.com/a/z9HW7O5

### Export String

```true
!WA:2!1A1sVTTXw4OOcyavuaBLMGeGIcgJKcB0ex)OXfOP3cy6kL4cfjxk6M0vYJihroXuZmzMHYwzx8IISQfW)eeWD3DL(fu4nDlHWfDx3KvDTrrx3ZmKus2rUDrrjGeNhNZ35X8DodluTC3Y(L9F9Dgq8y0MSyHh(dUYiuSkKjAWvegvwAGxSuX66IpsD0vVFNyQNE9LwUKf8eX8qrwsfsOUNLFSaP3Z6)y9iSAhApmvXe93rH7UnJf5ZoKU0I8iuFSyX7zT2gl)WPWat9BPiDXGYg4S(4X4nTycCxeHsObGCJv5(A75cJwkdssNPe8lSw1sfIPMD0pcSkwqTw1SaosIhVtQncHeHeWVteJjwAcqFI1gBU6QzMyI4Dj0yfEIctPXDt1a0CZ3wpjgs6(ZYq398IdrtQl9LxmsMkAmsSYklgAT4en1bhODUh(xPFMmacDVicZs8mNhexoT0u)s5VHFI(n60rIv)4qe1dOu7Yiuv7TRu3TIZiVmkrZdjC8(NMpTIFaouGmKm5MogUqjBiVOk1Ud8sgw6yLGeeGfYF4Jezd)dBvFo2MauTHP81wHeFSJME4NVIwehSMvEASe3slCDux8(8f0tdWuSG41mKDyd6(Jo30bs41wrhI6lTJbxPDkl(nY42g8Ag3Pd5OHT2ERMUTA6ULJBY153mN0BTRGfiWsP1s6AHLpwYXrr74llngGDfyaaNM7wPwnhVqS3bTJ5(if2HcEOS0X5o7nV6V)Rd8XTbd6cHJ4XvQTB19QDsmnltuAOpr(CtvAp86iAFE5Sc409RXciE8F7c1X)ZQG)BRD)3TQnBNX6onfKVaYKjYI(NW8X)VRCgqdXckk6Bbse4KV6SdWy(wWXINYr72HNGOKUMayZK3TAY82ugfFkgjXnvcmnqfo3O8q0WRezfehRLrFYKSMT2DaDtwlz95s2i5ttEam89U4kWPPeP0yHdha8bhCGM6)53iz(rW02iVdceSyQ)RxKxwbDHBjdrWjXZsRTkWVLzrZFDycWRBjZgKSg)oV1Mkt2Vveoa51VLP1tiF(PaEBwet81fkuO4zP6roc7)uIVk8vZWwEJT1abtbbH(Ic76nQxzGrmpdAfHNZ59FxM3pYS2HmH)tfi(XpnBWOmtqvgwEJ9CRTt9ktwTj5L4BXx(T8gEAW53hkBiETuHqzxiqC7ZTUmz7Y8BPt(7)Mu3dh1X0NYER9CBWVMzr4grMMo4zsd2BbtNrQWDsA)dVS0E6ScJsBiMNfo1i5ZH6usN(jZndSZhKCTK5faTqV3jJth85RkiV06BIr(qOGSCDtrShrsAhbD4U1mI(CaNHZYN2zlEY49x8U8zKivxirMXMMQNpFHDQxVItl7gUUnEIZop6XUzzGXS4BFzobxG9i6Q0IZ48wDPN335YW78e)BFzqoXS)YOGi2Hvf4xeJPE939DwDL1Fq6PGEJH6)YdJJ1t0u2rTJvkgTrpSaAxoqVCntFJRBKp)G)e9KThxIOVx6r5ReAR3m0ist4dgWfnoIBiX7akCBsrZo1iW4fmgWgkEWIW2HysqO6v2rmKFvBjuQCdNUXrksjBDlUBKOk54fHKs9O2kazQspCGW06X1Ctk0nJ)(5xkRRP)kIebCj)9fhL68p(NE4pBDf454CX2pP)(2VKX6wyyhbCzf0ReyJfhOyE9s70EZcF))DrIV(gC6by16TbZ0HeuYbfXdrfplLuuvRS2nA3CBNkvQ7mPjY6Xe)HvEH)Ek1r71lEnahn0aPRmK7YVKcAZ7OzIohAABnq3AMK(5Sdj00dAywPtgxTNmxzPZdwzJv(SY9()p7pd
```

**Comment by InfusOnWoW** [comment]
I don't think we did anything in regards to classic item cooldowns.

@mrbuds does that ring any bells.

In any case, this is most likely caused by your computer not being rebooted in the last ~40 days. The game, not WA, reports a negative expirationTime because the game uses a too small type to store time offsets.

**Comment by MuunJuze** [comment]
I fell over this, and thought they might be related:

https://github.com/WeakAuras/WeakAuras2/issues/2078

I'll try to shut off my computer properly and check it again then.

**Comment by mrbuds** [comment]
There is https://github.com/InfusOnWoW/WeakAuras2/commit/da932c71029daaf218e66574b58ef712e9562119 indeed but i can't reproduce the problem with this trinket either.

**Comment by InfusOnWoW** [comment]
You can try reverting the changed lines mentioned in the other issue, so basically delete the green lines mentioned in https://github.com/InfusOnWoW/WeakAuras2/commit/da932c71029daaf218e66574b58ef712e9562119, because those could be a source of your problems too.
