### ISSUE TITLE
Load Condition Avatar Talent Doesn't Work

### ISSUE THREAD

**Issue by jackshlin** [WeakAuras/WeakAuras2#4298]
### Description

The warrior talent "Avatar" recently changed its spell ID. Now if I use the Avatar talent as a load condition, then the aura never shows. Removing the talent load condition makes the aura work as expected.

### WeakAuras Version

WeakAuras 5.3.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Reproduction Steps:
1. Use a protection warrior.
2. Make sure the Avatar talent is selected.
3. Create a new Icon aura
4. Set the trigger to Spelll/Action Usable.
5. Set the spell name to Avatar.
6. Under the Load tab, selection Protection Warrior, then under talent, select Avatar as a load condition.

Observed Result: Aura does not show up despite the Avatar spell is usable.

### Export String

```true
!WA:2!DrvZUTTrq4i4(hObkIvtnCakkmsr7LayuKg7d9MOQKJduKCjP)PNKwsoKCBO2LD3Ls2UNIouKZQVbcT36j9i4NacII(a4d9bWpafD2LKUXvhK25B(9B0mtR(TN2oSD4B)Iv0aoZLNlcGp7bIlgffjbvlXL1pwtybjCXXCkt53T3qVEoLbCEAiFoZDondMCDJyVWyiXwhUjlucACmiKF8xjQF(32QlZahzgKMEJm3hMbmLBEue9I1J72X1BSRxhhVvHGpc6H2kErVbh3)KbzBLlHXXade0a3e(8rSjog3l7eOOC2UNij(PWDr9ybGr1X94EdgukasQRoPdjtb)oZikIOuhqzd4KfMNhfkTkVxwUrA(PBn)SZzuLFwk5sq4WqhLwl1bsjibVEYY7I3oFWN)plZz182kBlcwLZaVk5xXdH)4b3ITtqWiPNInjKc)8TVgGSoymcuoeKujlLqAKPTx8(ytrsu5cIcswHS0bIrFKF72fBwII(y(Jf8Cw4BFuwBfCHASmHGL851)jM9ydO5RiUykbnO(HnJZGL3P(jFPm7HVte6Yt5Ix2QvRnUPcTPOS7CI3OSpXasYvCmu0GZOHQe7oO4Tv5IEbeAaFtz1C0puxrxB0)J5sfn6sKGcUcjNhcApC0WEfBkqEPTzLXWatzSb(zznjyQSh2xqVA3VpNeIngYUEE3J7nzQ0GnNlcptqYwCw9JQcygvsXjNj1C(DM1Z26OHd75m2EKN3Ox5C0HVWR8Uu7sVcECnJo)E5rR1m7o6eVbhnS3FvgNYN3xa)uoWcU8437R37z7xXoTI16VAIWcTG25s)CLIZgnde4W2kn8aGfRs(uJ9nmBPwO7DDMRXzXdBqsS1ktmz3lHg8AgiLBy8WnGKcvphqr4TmjWg7lGiXpbOXjQ3yNYjHZSLir32zAEQIADtqkrkXEuOE1jyBFjLfNc)QVcJhtTDXPBVtRF7Gj2gTfNAL1wVDCFVM4yK1Qxz2Dm(MSsyMO1KV4JYEuZff98W3rnl3HjljmQEkJZoWrIlXQ(xdej4QeMEZhwSzXtld1ljOjJ1hBesapgfkxOTZe7NApLqz9l8nwxeuewGG(rugvM8)Hxtzv7iy8SCMBgJTVIZN2sqm3DKhuqSkITSr3vwRu8GzvBZ706x(9NqdxxDTzxfivo)3i86ibELaRBu5g3wnf1xdPlrF3Uo96n8z5O7Np4W9X7dp)LDVYhjsen2sqz6CajMMBZLj8McE0aM4qsZsiBSsZAQPcTw00lNuIRPyMgLvPOT0z)9(M9EE7z)55)7
```

**Comment by InfusOnWoW** [comment]
I cannot reproduce that. The reproduction steps do create an aura that succesfully loads.

As to your export string, that one does not have the talent load option for Avatar selected. Do not that blizzard changed the avatar talent in 10.0.5, which broke auras that had those settings previously.
