### ISSUE TITLE
[WoTLK] WAs not updating sometimes

### ISSUE THREAD

**Issue by Iowerth** [WeakAuras/WeakAuras2#4301]
### Description

WAs not updating though their triggers were changed. It continues at least from v5.3.6 and after Ulduar release. For example, there is simple WA below which working very simple - it counts Frostweave Cloth in my bags (including bank). If quantity >= 60 then icon appears. If <= 60 then disappears. But it is random. I can have 59 items in my bags, then I loot 2, and I have 61 now and icon not appears. Or I have 65 items, then I destroy 6 and I have 59 now and icon not appears. If I print /wa then icon appear or disappear as it must.

Tested with all addons disabled except WeakAuras.

### WeakAuras Version

WeakAuras 5.3.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Described in description.

### Last Good Version

Before 5.3.6

### Export String

```true
!WA:2!1vv3UTXTs4OOc0eHIdCCkmqApOqh3gJK0wdBNJDkkqkGxFKssHILZQ15NErLO2DwTmEfjdjxjRGGIgHcu3EPEeeqURxPR6fheG6NGTcf9bWx0ha)e0HCL8pPX6croCNz4mFZmFmx5zBpBWSb79FL8eDmLbYQB7v5EBwAi1NZQXtK(qEXNgqvIysppyxD9qUSnrxxuxtBd1d6XiTP(11rsqfXJd6n0prP5Tn6kEqycZxt5SRD9cfXFXCFsCrFEctF77a67PH2ByeU2kRS6Tw9Z0YeW(xM2sqNizxB5L(CRfxVaWcgRIib8UpPAyOc0)7ZnIW8J4YT4uMU5gL20RK7yFogh8USADPcOHO4zh9zs5eZCCmVTiGOHMj2L9N6QsbTGijXMlQ1CvAIuxOziLrvrfCWf9cdc41ZCtuZS1Z3xlPTAbs1)Ab5KT7nZb2KPoxasIMlN)RUDFkIdBsAdxO)RhKOG6wnACGkPj0by6AjHH0DhvFJ1R5vVM36UE9vcio(EbQcIlzmOfGvoQFTiE3QSgJpL4bk7YgtYKJ86wsa9QBTTkvPYHgNqz(XjbGdHTtdNemLAAqnq6AdN5xBjxRDdnvTI2YMlw7bvH9TwpjhA4O7jahJ4Waehdd9qz5DlvzRYBxzaAvgqGrUbo7aEzY3Nha)Y5eF4BTyLTX1uZcoeR0GKrIFicSy54LhUdaI1reXx7sWcu0afehM1r4u1ZR69XarrWEjSIg5eYzAXmLL0Nx8bjKa8qsrpVHiS4cTmL3VCU0BmgfBs83PfoxWc(ZXTI5DllHNLam)EB9olT4kRMEdjQK5dM8)o46g8yUmQV5ito7UfDxiEOrScWAPJE3rM9tADZnO1ut(684phJyKvJhFsnQHtmqEBa4fr93HbkvE7xQGJRQlz9VdxgaYO9UI4)OnaN(F2QlKGp1Gx5hCKkZFvHygRu2uvw0KlxU8hKD6uC0z9T9QkUS9qsc2AJ4S)JOb6iN1rXdZUpmDdSh(sXNCwHrm0I43REymhHQ9Tk8uCyHg2l9IdLCnwImLENnRUzPXzZ2tbSma3yI46NL7Fl0rwT8pcNhmXkMo9leZEIKFkQFQdNE3IIN1n2Mhu30y1yS9JDXkXJKer)hnzZ4JUptpr65Na4NG2k9IIp6S8(ecQmGQdw)Agp9MmUSg95WvMathf)x5T4SSnPl3mcOTI0l3FACM(ToXCsWFn2mdBgNLajUDKKYmT(IfAQWDXGJcbq32jXA6CPXnSSumKoqg1uJ9Nm9CPTl4yMbnBex2Yi0IXLGHtW16tRrXOrXr9nBvyW34W3qRHPV63)(0xN()t)1dS6EsIsx)yIsTq6oo3F97ukT9CP72W1Q183APbhf9N3X4AJAmodmQ9Ig9pcUCmVS1y8Pk65hrzzqeoGm3iCRpuYq2PAm8426F49K9MaYdLwUcBj97K7oDGLWOz(yT0zkVpquqnTmB2p9gPVyCGHdc)CDdhPubyKeO6B0Z6Px40MqzLt)rR2P7L(tP)mUEP38KvsObJIV7s38HLw(PFZtE2OtqAo)v9pmRHOSebeJFBwBd3sL2u8XN9dHhZomk0ygg2iVyENNZ5TZjE)PpdAS8)rveSlmisozW1PsPYEd1C)ozeYxOZVnpnWqXYv6UaPduCJyUoAmYCGHvvH9r0cUKyrejVBxd0USywSLy6Bu4BbUMrQMi(esBva7gn(gICpEoE0Bszn0aMuRV)GfC9Ja)DwlDU897qKuta7yEh0TdjobYl9JiSwaQy6RA0xin9y6EM3awCLfneQ9NMXrhCA(U0QZQCxDXBU4TMTZF84)(
```

**Comment by InfusOnWoW** [comment]
That's on  blizzard they have broken fixed, rebroken and as far as we know it's supposed to be fixed again. But in any case we rely on game ebents to tell us when items change and the game isn't reliable at the moment.
