### ISSUE TITLE
Texture WA WotLK Classic - "Prestige Symbols"

### ISSUE THREAD

**Issue by kbinz** [WeakAuras/WeakAuras2#4305]
### Description

Hi Weakaura Dev's,

my "Texture" Aura from the "Prestige" Symbols aren't shown correctly.
Some parts of "near" textures are also shown, I tryed some of them but all seems to have this problem.
After this issue appeared the first time in WotLk it was fixed some time ago, but reappeared again one or few patchs of WA again.
I thought this would be fixed again but now it's quite a while in so I decided to write you :>

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Create a Texture Aura
Use the "Prestige" symbols, maybe other symbols are also "bugged"

### Screenshots

![image](https://user-images.githubusercontent.com/50100372/216822450-3cefb602-0bfe-450a-a841-0d3a34b206e9.png)
![image](https://user-images.githubusercontent.com/50100372/216822540-d0c0acaa-8792-4d48-bb92-827b300b2518.png)

**Comment by InfusOnWoW** [comment]
That should be fixed for the next release.
