### ISSUE TITLE
[Idea] Add TexCoord and Atlas to Texture options

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#431]
Is it possible to add in Texture options ability to supply coords for SetTexCoord() ?

Also is it possible to add ability to give an atlas (texture:SetAtlas()) instead of a texture path to get both coords & texture path
https://github.com/Resike/BlizzardInterfaceResources/blob/master/Resources/Data/AtlasInfo.lua.txt#L3463

These two functions would help to re-use game's assets without custom code

**Comment by InfusOnWoW** [comment]
Atlas support could be added. SetTextCoord are used internally, so that is not possible.

**Comment by InfusOnWoW** [comment]
The next version will support Atlas Textures. Just inputting a atlas texture path will make WA use the atlas functions.
