### ISSUE TITLE
Provide a "Spellpower" option in the Character Stats section of Player/Unit Info for triggers

### ISSUE THREAD

**Issue by ksulli10** [WeakAuras/WeakAuras2#4310]
Currently there are many options for Character Stats in the Player/Unit Info section of triggers:

![image](https://user-images.githubusercontent.com/20649230/218014275-228b99e1-9f82-478a-87e4-51bf0f9a168a.png)

However Spellpower does not seem to be among them. I'd love to use Spellpower in a trigger for a WA.

**Comment by mrbuds** [comment]
Spell Power value is specific to magic school, so this would add 7 new lines <https://wowpedia.fandom.com/wiki/API_GetSpellBonusDamage> for something we never had a request in 5 years of wow classic.

Could you give more details on your use case to help decide if it's worth to add?

**Comment by InfusOnWoW** [comment]
Waiting for reporter.

**Comment by ksulli10** [comment]
Sure! I have a spellpower weakaura that displays my current spellpower. It's just a number -- it's much simpler than trying to track which of my individual talents/trinkets/set bonuses has proc'd at any given time. It just shows me if my current spellpower is high or low, so I know if it's a good time to use other things. I am looking for a condition option to change it's color based on the specific spellpower value, but I can't do this if I can't reference the value.

I managed to achieve it with a custom condition function but it would be much easier to just select "spellpower."

**Comment by InfusOnWoW** [comment]
Thanks, but imho that adds too much clutter that I would want to see much more demand for it. For now that's best served via the custom code.
