### ISSUE TITLE
Issue with the GetAuraTooltipInfo() function

### ISSUE THREAD

**Issue by hkhljn** [WeakAuras/WeakAuras2#4314]
### Description

Hi all, I was trying to obtain the hps information for hots using the GetAuraTooltipInfo() function but it returns nothing. The code worked fine for SL but it does not work for DF. i.e. for c, and d in the following code, the data type was 'float' but for a few spells I tested today, they both return 'nil'. When I search the code it supposes to return float based on the tooltips instead of nil. I am wondering if there's anything changed with this expansion or the function.

Please check the following code:
function()
    local name = GetSpellInfo(774)
    local index = nil;
    
    for i = 1,40 do
        local buff = UnitBuff("target",i)
        if buff == name then
            index = i
            break
        end
    end
    if name and index then
        
        local a,b,c,d = WeakAuras.GetAuraTooltipInfo("target", index, HELPFUL)
        
        local dummy = type(d)
        
        return dummy
        
    end
end

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
Did not see any lua bug.
```

### Reproduction Steps

1. create a text aura
2.  select %c in the display test 
3. use the above custom function
4. select aura type: buff with speel id " 774" ( rejuvenation) and own only for druid
5. when applying rejuvenation to the target it return "nil" instead of "float" 

### Last Good Version

4.1.2

### Screenshots

![image](https://user-images.githubusercontent.com/58991440/218346971-81b43081-b07e-4103-83ac-6037283e0274.png)

**Comment by mrbuds** [comment]
You don't need custom code to get this information, but that's a topic for discord help channels, this function is not meant to be used outside of weakauras code.

**Comment by hkhljn** [comment]
> You don't need custom code to get this information, but that's a topic for discord help channels, this function is not meant to be used outside of weakauras code.
I also tried to create a very simple aura from premade for rejuvenation and used %tooltip1 and %1.tootip1 for text, both of them returned nil.
The following bug has been detected:
1165x Lua error in aura 'test 3': Custom Text Function
WeakAuras Version: 5.3.7
[string "return "]:16: attempt to call field 'GetAuraInstanceTooltipInfo' (a nil value)
[string "return "]:16: in function <[string "return "]:3>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/WeakAuras.lua"]:4539: in function `RunCustomTextFunc'
[string "@WeakAuras/RegionTypes/Text.lua"]:202: in function `Update'
[string "@WeakAuras/WeakAuras.lua"]:4270: in function <WeakAuras/WeakAuras.lua:4267>
[string "@WeakAuras/WeakAuras.lua"]:4364: in function <WeakAuras/WeakAuras.lua:4326>
[string "@WeakAuras/WeakAuras.lua"]:4474: in function `UpdatedTriggerState'
[string "@WeakAuras/BuffTrigger2.lua"]:1651: in function <WeakAuras/BuffTrigger2.lua:1643>
[string "@WeakAuras/BuffTrigger2.lua"]:1999: in function <WeakAuras/BuffTrigger2.lua:1992>
