### ISSUE TITLE
Evoker_CastBar 3

### ISSUE THREAD

**Issue by Roneasaurus** [WeakAuras/WeakAuras2#4316]
### Description

can happen anytime, casting an ability, mounting up, dismounting, healing, using potions, dismounting, 

### WeakAuras Version

5.3.7-18-g4bbe916

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
56x Lua error in aura 'Evoker_CastBar 3': Overlay 6
WeakAuras Version: 5.3.7-18-g4bbe916
Aura Version: 5.3.3
WeakAuras/Prototypes.lua:8579: attempt to index field '?' (a nil value)
[string "@WeakAuras/Prototypes.lua"]:8579: in function <WeakAuras/Prototypes.lua:8577>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:359: in function <WeakAuras/GenericTrigger.lua:353>
[string "@WeakAuras/GenericTrigger.lua"]:530: in function `ActivateEvent'
[string "@WeakAuras/GenericTrigger.lua"]:599: in function <WeakAuras/GenericTrigger.lua:544>
[string "@WeakAuras/GenericTrigger.lua"]:737: in function `ScanUnitEvents'
[string "@WeakAuras/GenericTrigger.lua"]:921: in function <WeakAuras/GenericTrigger.lua:917>
```

### Reproduction Steps

there is no specific thing that make it happen. it just does.
doing the same action doesnt produce the error all the time, 

### Last Good Version

10.0.2

**Comment by Stanzilla** [comment]
That is an error with your aura, not WeakAuras itself. See the first line for the name.

**Comment by InfusOnWoW** [comment]
That actually looks like a issue in our code.

**Comment by mrbuds** [comment]
@Roneasaurus could you add an export for your aura called `Evoker_CastBar 3` and precise if you are playing an evoker or not when it happen, and if you use or not Font of Magic talent

**Comment by Roneasaurus** [comment]
!WA:2!nI1FST1rDC7z2MKbKst3A3M2yErBrnOu3gN20srDg)sCIZQJD2Zo9h0wzFV37SFxZZV3R375K4iHGzKqL)1)XKM20gYs8pGagwBujqWgHbsWFWoYyLvgtJfGTPjG)i)XqJXW89U75eNU0jCvDU7((J77p(CFVVNdp9G1g0yqJRmtBpxeDXZqm8n)STj6o2fCQt1X3Bi6k5RuXd7F2iho(rPnKtg9t1bzRB6qN3Hy7Rnz6CftRUUqfQo(iFIJD4e1PwUXm99D9oXHo0YOQoXjohkvfSnIwk9solIPhkrIn1q6lwL6u32yshlh6JKj5pFp7jwOqhjtYx(zEMxOB3)wMKx)jEIxmuOJhUvfhB)PTqv9O5xOy2zZLwyQL0fsgb(SbODnl8muKbbB7B2YdBvryKSBRPgI2BpENREvqJ3sMKV3F81dfkuSiHBBG9q(1PiFS5Acpr6QNlS7ERgOU8u(3c3RDM8QZ(LZNRyQSkwoiJRChuIn3pC3NAT6w(KOTQ7HlzJxctnDhKpw3c55vczBuYZfRB2AR1kRqDSWdR5bAWctNk1CPMjTkB)7JDFLv8iRI3hB)rP(ilyZtWhle1cuTLPMCz(QkC1cdUNYQc1om7E1sF68NIRQL0YSaphvMEMuQQZMxoiB(jpvzv18ZSq6Yk8nTCNPsNQyMtLB2zYuKpzU85ceuHI0fgsBdsLkeDWhBWNUXoDlytFPZZ2)Wp35l)sNV86Cd1f7RH89TWMTCxYDB7LwbPZdL8XcgxcBs0TWlqmDhGp3GcGgBkXaIlM0vDSXZA4DlB4vZXX3CEQtvk2ZtYBkJlv3ZhBGnMJyB2MIRckUydxmfbPuiX3XbsewOg6we3YuF8kqQgRwWXIyiZ2fLl5ENNDEfenLnP2bZtr2vXf4uvq19Dk323rhuJhO77k834BRISCnrrKhDMCBmOMd1atvaGTb1Xvjhy4AC8)St16CQhFMdU4Jo2cQcmBu3b0b72PgF3xW1aaFA1f)PPpLuTkSx5gMgm8k7znbKb55Z9mZn5Z8mDwolWVTEdZMgC4lyCdo26vX2ykrVaqoV9AEI)Kcc3lHBYfRUnXVma51QxPIimLjD25NEHSk(WefovADo2fo38WU7V3gnPjIwfBmvW2uwvWHYKGf1SNzPWh0eGcwwq2kAhP)vYKyGv9j1WgB4vxti38uCfYkQfMpD2SBTybWGiR0P0KPkuSuHIPulYkQ5cjomv1gvd7bGF7Gas0ogeVlv3w4wjq2nC3dsmUOK(Cog4iBcN9XuBK1PLjUhRfcYTc7FcvpFe1)0Sck2qoQjg5H5UaBX14dl4tX2v9nVDnxaOH9vQGmWR3lgxIhPOEyO(JHNsneXEAwb2ISA3oZLDzMfBrTkeBIN5PflBjjzZC4Kfv94GJzTNMc10m7iWqZrOuhQ5gE(e9fB0lmBsdWChSneLufqBVv3hRW6W0TlFgSqfha8lwyjwHwCoeOX1L)PKSSDc4erVvCeL5ISwWuzT0WHd3dhxAjIhbQPwUtWCSrvS7EkC56iko201TSIDgtIpUhzEbRixzWeixI5gW(uQgKgSkjo41ro2ZVuDVhD7j0vd33KgHxtoPcXcoXRnEIJF0dF42Y1Cr(MUpGaE5DievhzJDDwMVTqDz4WHj2ZpETeBRo)gHPYjnexH13gTYFDGM0GRRM6tZk0eIwcQ9j9k9KE1ZgzITKwCWFEqDhFD5cbXiZ(KC1EsUs43E9QwolpnfF568dQCbhJvGcBhFD(P6zG)kQGuUjFjokuDEYkylHKfH6IlAdf7I0Hp9CYBMc3QApPEKizs(pU4f)QD7(pZK8TF))fCL2qsEpB)8wqhk(gPnFywb0(of8eakyFff(mtbRzjW(nIGvfrE18kXCFaEDZsIVaygCiQKBj(z6sWbeDchIgXDKBgpgnGZVe9s(MWPjthlJgUp4hJxFjVw4Qi9gLQy5arK1LMxppXDqHaEMiJTDp3y3STfYbL4xQxU1wCm0d5UHuh9Aoqj1cfZ7UxXI8k986d6IMHusbt3uQxiFyiw8XC)C3mlxolCGn3ltTMGt(vuKkny3wBbQdZl6RKlFU0U39UOo5a2f3LOU)ng1xpGQTOem7Zibx8f3LaJ)neyAliQ3dh93)pWNp6(GEK(d8pFqKwBP82PxHxk0BzuJDKfo3otn7033fNZDlNtA4ldiSZqrUnptWaz8Q3Hk3b6tTI8vNzZLlTAjvEBk7sUWDh5IaXLM6KBvEB7ywbOI1DVlax)BcWDV7cW1DxaUx5o2fF3UNVVi77n0dzZ(1cJH99z)a2ZY(HSopg75cZEE2TX(rSRc3C8ty)0DnPW(zSxG9IHz)c2lX(Xqc)x1wgsYME6ISFPj73C3SVty23nSMjMu10)b2qCbJc07Lb)AXePMAQBSXj0kMAEIU(1i1CDG2oK9N5nb7srvG7Y8hwtEB(k3Y7A5a1sIPp2OX0ta)F8yNm2KumaNeb4dC44h7iJcLhpYOJn6yJm6nq7lmoqBIX4FD0pgz(YhNtcOe9G))9jAusLy2o(X4D7vcBVuCzhGXH7FI3R79y(My7OXGpFICDYDJ8jKwyqtIhyKBQAQH8w8tufZbmSTAG0r0OYyjWYUlya9(mW(T3aQb7BptiA0E0prbSFV9JBfZS90rgzhCLYYsC4YJZxCTQ7KAVNuDGH2(LpdnkaaG8V(4JenkFB7FZo)5NL35f0Kp(cPmmYB7DHZGrlMcCqVlmh2GGUqaRExq2mrjEZeIEjU4fhn2qtMn1CZxmVs2utEkaUoBXzpD6H(ewpx6uQPluCOr2Yu2Phvb8OOYbsIWD4h4W95LGv2F2HRLrAz4usc6nzqVN9Eczc(Hs4S4FouO7zRbHvw1XPg)29XtuNy0zIZzFQktCKzhlFw3bKvVMMc9Wk(YDVBfnorwrhmk8EYc6lCRxtW12rdAvRxZIk8h9wUL4PVEqF1k8d9AWSkKQrBg8qhVlbpZ9LV)7pz3UF9mjzZpF5qHwitYF7t)0WdF)MraIx7Ax7n729zZKekOadEryL9TV7VB3FhN4F6PEk4T3pFMKVXB8gD7299ZK81FYNeK8CCIBm4GaFVhmyZnbIBKj5BD5l)1cf6b5eFNJDmyp)GmjF3vw5Bfk0aqdjp(J)mD7E9i8y2R(QVkeQkcw0adeJlHSZ3mIQuNCZ(Is8BY0kmPA6052SNpfKAUe7lU9)gIy4oG83tOe)Liqym24AE4AGmQhn(4XhV)NZF2WbBiXWaBROKVyMov4Bh0TpYhD7QlZVGF(BnXyJdXDOxaWCY7kkdg1Dp74x4GxhvBUu5wivw4T)8E0XMYFdKPK)ucq7GoB)lgWUJ283kqe6A1HvHwv1xCc2JeP5sikH)RwOWFJL6siR64iuDt(Jp9UNHzFuKMUaKat9BW(sdZ(3CzyFylCnrJVydGb2)LZxzwx27lzy0qSpmrQCtPj2fVpVuMxlCiGz5y(gWFmx)sZFFr8JgN30hOMPb(gYXDOh(KSpK)sPQy2hn4ysM5PYRF9R3varEL9UxivwmcOGEjQ4jUbf8AHVvq6eBl97T6QaO4Azs(xELx5n5OJ(LE8Dv6XdKgWy7F)aa8TISf8ChsFKTcsshgeBFSUq2d8UJeVVo47qSLxgdPKH7ad1XP5pc1RS7DrQAdVKki1lwnn)XzELvfP4Yd6jaxhBWL(9N9)n






there is the Export of cast bar 3. i think i did it right. let me know.
i Am playing my Evoker when it Happens, and am also using the talent Font of Magic.

i hope this helps
