### ISSUE TITLE
deleting trigger after setting dynamic info to it causes it to display wrong icon

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#432]
##**What steps will reproduce the problem?**
1. make a symbol type weakaura
2. enter some buff name (aura type trigger)
3. unselect "automatic icon", then choose some icon unrelated to the buffs icon
4. select automatic icon again
5. make a second trigger, also aura type trigger with an icon/buff unrelated to both previously used icons/buffs
6. set dynamic info to 2nd trigger then delete second trigger
7. apply buff from 1st trigger to yourself -- the icon from when "automatic icon"  **wasn't** selected should appear

**What is the expected output? What do you see instead?**
I expected the icon from trigger 1 to be displayed but instead the icon from when "automatic trigger" was unselected is  #displayed

**What version of WeakAuras are you using?**
live, latest

**Additional info**
It can be fixed by /reload so sharing wa string doesn't make much sense

**Comment by InfusOnWoW** [comment]
Thanks, will be fixed in the next release.
