### ISSUE TITLE
MouseEvents in tooltip on mouseover

### ISSUE THREAD

**Issue by feboss** [WeakAuras/WeakAuras2#4325]
On my way to build my debuff/buff tracker in top of my unit frame I found that I can't use my binding macro if I hover over an aura(icon) with **tooltip on mouseover** enabled. 
The problem is that the tooltip on mouseover makes the weakaura take the mouseevents.

Solution: let weakauras handle the tooltip and so bypass the limit that i can't use my binding.
vuhdo have something similar but when you show tooltip he let you heal, so i think that tooltip is built in vuhdo so he have control on that

**Comment by InfusOnWoW** [comment]
I don't think there's any way for us to make the frame react to mouse over events that doesn't make us handle click events too. And I don't think there's any way for us to propage the mouse events.

Though that's not an area of the wow api that I know that well. In any case this is too niche to spent time on investigating potential workarounds.
