### ISSUE TITLE
Unit "Arena" does not work.

### ISSUE THREAD

**Issue by Humperd7nck** [WeakAuras/WeakAuras2#4327]
### Description

Attempting to create an Icon Aura that tracks enemy arena player buffs. Unit "Arena" does not recognize enemy players at all it seems.
As a workaround, "Specific unit" -> Arena1, Arena2, Arena3, Arena4, Arena5 can be used. But this is troublesome and can require 5 triggers just to track certain things.

### WeakAuras Version

WeakAuras 5.3.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. New Aura -> "Icon"
2. Trigger 1
- Type: Aura
-  Unit: Arena
- Aura Type: Buff
Spell Selection Filters
3. Name(s): Divine Plea *(just an example; NO buffs work)*

### Screenshots

Does not work:
![image](https://user-images.githubusercontent.com/125936632/220232394-c8dff3d0-aff0-4bed-a008-6cdce7a0dec9.png)

Tedious workaround: Having to use specific unit here forces MANY added triggers to be made, especially for Combat Log events like tracking non-buff/debuff spell casts.
![image](https://user-images.githubusercontent.com/125936632/220232466-bbe10611-0003-48cf-b76a-521bbe126911.png)

**Comment by InfusOnWoW** [comment]
That's fixed for the next release.

**Comment by Humperd7nck** [comment]
> 

Oh nice. Is there an ETA for the release?
