### ISSUE TITLE
Glow Effect on Raid Unit Frame vs. Main Tank Unit Frame

### ISSUE THREAD

**Issue by Jakobud** [WeakAuras/WeakAuras2#4329]
### Description

I created a WeakAura that adds a glow to a unit frame whenever a raid member has a the debuff "Weakened Soul" (from when a priest casts Power Word: Shield on the unit).

In a 10 man raid group, I have 10 unit frames. But two of those players are marked as raid tanks. So there are 2 (larger) additional unit frames that I have for the tanks. So essentially the tanks have duplicate unit frames: One unit frame in the raid group and One unit frame in the raid tank group.

![image](https://user-images.githubusercontent.com/87356/220391399-4b5d85a1-3fe8-4b20-9493-e6b4300de564.png)

Here is an example using Pitbull Unit Frames. You can see that it's a 10 man raid group, but the 2 bigger unit frames are for the 2 characters who are marked as raid tanks.

**The Problem:** 

I noticed that when my weakaura glow appears for my tanks, sometimes the glow is applied to the raid unit frame and sometimes to the tank unit frame, but never for both. So for example if I have a tank in my group named "DKTank" if I look at his normal raid unit frame it would not have the glow effect on it but if I look at DKTank's raid tank unit frame (the bigger one), it would have the glow effect on it. And sometimes it's swapped where the raid unit frame has the glow but the raid tank unit frame does not. 

I'm not sure if Weakauras is maybe confused because a unit shows up with multiple raid frames.

It seems like it should do the glow for both of them. Either that or you should somehow be able to control whether or not it shows up for one or the other (or both).

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
There are no lua errors.
```

### Reproduction Steps

1. Create a raid
2. Mark a character as "Main Tank"
3. Have unit frames that show both raid unit frames as well as main tank unit frames
4. Cast Power Word Shield on that character
5. You will see the glow effect only on 1 of the unit frames for that character. I will show up on either one but not both.

### Last Good Version

I'm not sure. I just made this WA yesterday

### Screenshots

![image](https://user-images.githubusercontent.com/87356/220392540-e1cfce1b-590c-4e06-8f84-a331ae39b665.png)

![image](https://user-images.githubusercontent.com/87356/220394087-93909b2e-3326-4077-9dbc-3bf6a5443b0e.png)

![image](https://user-images.githubusercontent.com/87356/220393293-f4660646-3404-4411-83a3-71fe9037cd50.png)

### Export String

```true
`!WA:2!1z1tVTXXvCjXdUqihAOAudsBb2Qcl4I2qBrzh7uuxdsgklgqjZUKkYPx4o7UVD3XA3zMmZSuIPOhmrpeGK2cWpa5ap0t5e7xGe)jyHqrpwuOB5QUe0EQVzwsl5IAcWLZm7BE)53V3F4Q7vnRAy1Wp7HsEUoLYa5toAq3oh2EgnGZ6ZZLbWQ(NsI5D(GPp7tGU(h09d74gWt5YpSc(r8lcPkrkz8a4m9WiUmJOhkgQPzWWWXmsgnyOorcQeEA44zb5knpZiR47IYzbAkNDRF(6o4hAKZXa5Kg5sIQwh1teM3H)aOao6eG5ibDUK5aSWLxGX1oe8cdb2OAPeL2Hl)Fo4x78yqpaDhulVRZo1UNvxwfy(8Qc)WRe(Ls0hTxReI(aqPiXWT263)0)GJ7rh6044gFSdUzluXVl6CikeagT7KvkQdr5Waiek9xJFJFLJFsuKc0RoNWcs4YECkt73Q9HdA7EEahHj(PS(NsfGNW51dUL7wv89Vcspses0GFU9NxSuvTdJbpjXc1Q3ZvPjs9FDwCk)0HL04(p6F(LF5xVYkRS)J(BBSHJDX3(V)pMfvUWkNoHgCcddQBm3UVuznro9uziFO5mVsnAsHuVvPuPalwN0RYDR9Gs1ejHpjhybJ7v5o1QpTu1JfGBp6zq6f5ky4vUL3LlUdbdwJutp6Wod2ZTXbT9JOmQkzZlsOHWqsAQ9AkVM4X6T9lbK1MIEw5YKjAjnogKQd3wUy5NDZ5Hiuff1cjE1MUzKyAGNujG00oHU1FW9FWUtnjhykmOENZnPMadcDWAI0jH4lmqq16ZrsiibD5CMU6DMAV)H4v87KjiPWmdg1kLJOI3LMa8AgnXCq7ZqWSFPvtMla5rymCapeMqIIGane6cJaMEwlEMpr70Lhp3ONfoQ3m7gnrNRsmi4JXczrP7KmNYcsZdHEGwDrpmncrGgSq7wvUVvV9Kqe9m3(9A3T7fbOnqcSxPxu6WxthEV8w9XyGE28HTA0FWW(dA4oqSr8vwglAr8HlR(BMvgVdq(tUFd3d27OUgV8GRaTKM2uaduxF(10r17iZzwJ5AY3dNyCMCJB108SPKqdNz6Sq0gN1htRJbTRLUw3MlD1l9o)LqMHBsMSa9uR)cJDT7O4oXgxJnVkiK4Tn3ZZG8nwqljtn6KeJUS3uu8Y0Qnl6v8BNJvTpZ2CBeuNWglEtID9GszmS7xTI4h9)T2UCrrxX2V(s)uiMemEyukNltU8eaenWqiq7AYjtMCkxgESKiMC8IfYZw2X5A6CnKAuyAdgJqY5Qec2R4JlL7hVsZiotlERgbbyfgttsDW8eLzDWy5imncZ9BndZgCHytBL3zZI9ph36tcoXWHSq)eGgNOF(fKCSceDSGJPHiz3a32mLtc)hw8ZWWYeK8WMfASkmpvt3Chp3atbY2(kklof8752PD)bfQnlg5j)uSycPoXpCN7E)FPZo39bMhVp(4E3X8yhBfrPcl5iRUsS5pM7Al7Ww(wsgKuSS7ABwB(s5qBK00SyTMg0DZc16nv0pfWfBobje94mcd75GZj9eB96zRmE4qdi7nXaQ9rnCtFLDWQpntG65sQX0ms6hvcSpFbB80s2OYucJMzB38EfBS3laIc6RL2MR3Oy)Mm0fpFzdjBNsPcqNkunXiQP0R4lAMrOSpQy)IVO4VGF)8Bu8Nk(Z(cKub9fkbvssjSqrEQck(P7zEVruugJ4NJCioOAXe519rLhrJxFM0s(gd0uJXD9CzQ4NKO1c1V62328FgQr53EaKPoknmNiV9U7ovbPr2bEfVHljvKqQGnPkXluvBphxgaTnv9kpXBtJzCjSWU2tBlLCPYBzICh0vE7124Fj(zVE8hdYaQbxRGSjpBv5ZWHc0OXn72EVbIFWYXKMB(bufXpfRT9vqgMy6wVw9A7mtZdwKZ)9g9nBrdfvFmoVX5vgjCz5W89mJRmiIF)wUTBFOOkMo1AHjWcFxtIG7PMsHNp3oBdPsIMuPEonC(V7E95hKV)D35KrskZytizg2OfcTfp)X3yEzMrl7C7vxD1kZmenTKxMSmu8AAk6sQQCVxTDRD)QJ(7p9)o`
```

**Comment by mrbuds** [comment]
You will have to handle this with custom code, there is an example for glowing multiple frames for a unit at https://github.com/mrbuds/LibGetFrame#glow-every-frames-for-your-target

**Comment by Jakobud** [comment]
Looks like that requires completely separate libraries. WeakAura doesn't have an option for affecting all frames? Does the same thing happen if I made a weakaura that adds an Icon for example to a raid frame? It will only add the icon to one frame but not all of them for that unit?

**Comment by mrbuds** [comment]
> Looks like that requires completely separate libraries

It's the library WeakAuras use to find the frames, you can access it from WeakAuras.GetUnitFrame

> WeakAura doesn't have an option for affecting all frames? 

No, you will have to handle this with custom code

> It will only add the icon to one frame but not all of them for that unit?

Yes

**Comment by Jakobud** [comment]
Okay looking at the code I do see that WA is using `LibGetFrame-1.0`. Where would I put in custom code in the WA to specify the unit frame?

**Comment by mrbuds** [comment]
Please ask on discord or check the wiki, we use github for bugs & feature request and this conversation has gone offtopic
