### ISSUE TITLE
Create new auras button missing on top of window

### ISSUE THREAD

**Issue by johndolotko** [WeakAuras/WeakAuras2#4330]
### Description

Just recently, I have lost the buttons to create new weakauras and to import weakauras from the
 top of the weakauras window as shown in the image attached.

![Screenshot 2023-02-25 151307](https://user-images.githubusercontent.com/49884783/221364736-ce214a62-4688-4be5-8f90-91314ea6e658.jpg)

I have tried the new alpha version but getting the same issue.

Weakauras.lau file
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/10831567/WeakAuras.zip)

### WeakAuras Version

WeakAuras 5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
1x WeakAuras/AuraEnvironment.lua:359: attempt to index field 'child_envs' (a nil value)
[string "@WeakAuras/AuraEnvironment.lua"]:359: in function `ActivateAuraEnvironment'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:336: in function `sortFunc'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1256: in function `SortUpdatedChildren'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1064: in function `RunDelayedActions'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1055: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1380: in function `ResumeAllDynamicGroups'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:733: in function <WeakAurasOptions/WeakAurasOptions.lua:697>
```

### Reproduction Steps

Happens everytime

### Screenshots

![Screenshot 2023-02-25 151307](https://user-images.githubusercontent.com/49884783/221365251-762e1f86-13ff-474b-a108-8d86e0cf26d5.jpg)

### Export String

```true
Unabme to paste weakauras.zip here so attached to description instead.
```

**Comment by mrbuds** [comment]
I can repro error, it happen on Private.ActivateAuraEnvironment(data.id) in customSort func of `Boneshock's Trackables` aura

```
function(a, b)
  --ViragDevTool_AddData(a, "a")
  --ViragDevTool_AddData(b, "b")
  if a.region and a.region.state and a.region.state.expansion 
  and b.region and b.region.state and b.region.state.expansion 
  then
    --sort by name if expansion is equal
    if a.region.state.expansion == b.region.state.expansion then
      --sort by name
      if a.region.state.name and b.region.state.name then
        return a.region.state.name <= b.region.state.name
      end            
    else --sort by expansion
      return a.region.state.expansion > b.region.state.expansion
    end
  else --sort by groupIndex
    return a.dataIndex <= b.dataIndex
  end
end
```

**Comment by mrbuds** [comment]
`Boneshock's Trackables ` has 3 children
```
			["controlledChildren"] = {
				"Free Bagspace", -- [1]
				"Player Money", -- [2]
				"Currencies and Items", -- [3]
			},
```
Somehow when activating env of the group, `current_aura_env.child_envs` is set to nil when activating env of the second child `Player Money` which is not in environment_initialized table

Saving address of current_aura_env.child_envs before child'env'activation and restoring it after fixes the error

Proposed fix: https://github.com/WeakAuras/WeakAuras2/pull/4312/commits/d92b5c96d63715dfbfce777271ceab41599507ae
I'm not sure if it's best way to fix it
