### ISSUE TITLE
IsBagOpen() conditional causing ForceTaint_Strong to bug out with certain Triggers

### ISSUE THREAD

**Issue by HonkdeVries** [WeakAuras/WeakAuras2#4334]
### Description

Greetings,

I was trying to make an overlay with a border that changes color depending on the open/closed state of my bags. For this I used the conditional IsBagOpen(n), with n being the BagID:

![image](https://user-images.githubusercontent.com/51466944/222264554-57a85b86-88ae-4bcf-9862-c37ac3d1f1c6.png)

The Weakaura works fine within the session it was created or loaded, but it starts causing problems when the game is restarted (or /reload'ed). After a restart, when trying to right-click an item with "Use:" functionality in the inventory, it shows "ForceTaint_Strong" to somehow have been affected:

![image](https://user-images.githubusercontent.com/51466944/222264828-a119e329-d378-40ae-a8f3-3e1ccadd96eb.png)

This behaviour seems to depend on the type of Trigger used. A small list of things I've found:
Fine Triggers to use: Aura, Combat Log, Player/Unit Info: Cast
Error prone: Custom, Item, Player/Unit Info (minus "Cast" subtrigger), Spell

I'm not sure if this is unintended behaviour or if I'm misusing the IsBagOpen function.

### WeakAuras Version

WeakAuras 5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
[ADDON_ACTION_FORBIDDEN] AddOn '*** ForceTaint_Strong ***' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1402: in function <FrameXML/ContainerFrame.lua:1311>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1454: in function <FrameXML/ContainerFrame.lua:1441>
```

### Reproduction Steps

1. Make a WeakAura with an error-prone trigger such as Player/Unit Info: Health
2. Add `function() return IsBagOpen(0) end` as a custom conditional
3. Right-click an on-use item in inventory - No error
4. Restart or /reload
5. Right-click an on-use item in inventory - Error

### Export String

```true
!WA:2!DvvWUTTrq0O6g0cEOiwn11PWfWiOni5IrqkIlGVz6kf7cfjhk640tMljhXDRP2Lz3LswgOhIou4Z6tqa9wrlGo3t(lGGOONlYNG)c6SlPusQoin7mZoZ8M9nJA0U5WMXnJV6BMZIe8(ICze0OKKRPczVmntWvoYj9gmqb6gli8iu)XcgxhEqRU(T8kJeI0yXyE)XSmi46LhBfNauxtmdMQLSKeqQ(ShiRfV6RNNRGZuzq0rXbtzAyyxYqyZg)5)(wJbs6yYeLwMdbvNdvcz4ZfXqqzcWbjlQpvmUhFUc)zFR3tnoMZz6GWQ4UrOIXtsb9DYw3y7dUyGhhtOYX1CJWSuYeqwwxtPPMIPkZgZmLnSZwzAZB)x)H1ztmKajDi1vpjdk2WclkQrtPVvLhcJaUUF(GbSlwC2b733)S((775ppgcrL(4DKh2QZXTpPtwZ3b0dXaybRN9(2ZA61ghw2Qckn5T)Yk6MJLSHczmJKU9PKrWIvqX0FRfuoZFhCk(YzgFYeJbjTYDnziJtcS61ss05bRGWXsaHGx)JB1PZSCE9ZOt26KinBe4xD2uZ)(TUbzhGKtsFj(MJeO3CZ5aKTV5rr7rqkfDMcshyzrf3gBfkIoxs0aDoMopiXq62BJITkXJHyzKif584RUBwtnCH(mfLGmSxvZjZUNvP9Rbc5qc6qTGlxWHzRmF)VvLDN3lchisfYFSrJgR92kTllk39pXVx2NBvItccmuSOtzXAQ7(4XBQYf7ci2Q8nLvJf)uDfDT1(pNR0SbtqakfAeC(Os3U962QyljIlJpZTogzlJ1WpZQbbxNDN2s2LB)ICsm2yiB77)byFzMkT6gJV7NkjztpTwOQagXuSWuiOgZV3OB26h1TBlVZC757375Eh9Sd9lxL6(SlH7vJOx9b5Xy1Yy7DIFNJ626FktsfJBlHxNd8Ojh)XpENN80k0zmSW81Yim1CWC5YWCTwW7ncK4m3CJ6oaprt)cR)lr2mZHdw1zmu)NTud11yKAZUpLfDohuQ1S3OFejfQe7Wq1RBtGl2xqsEifyju9BCtfK42HA0vUEdVH5PAMJRHEUrb44fLsukJKRcBfgH5slN0u(fF6tYzXl6E5j9OT29LVG3DgHZmeebFxpCcsQBFnquqFT0cRpPyRI9kJn8B0LZmBjKkaxlgRMA8Zg09Chsy82fCR3fIISIxxSx4agNPO)F1ly8k6ngpN5MiXSRP)Qh4frHOZ3TWzRBnDerYi4Z)IiKhkgAT4nIKMdzpyqopYCLh(iNTXpsah)4BFKYLK0ld4p8XpYb4XYikHNayClMyNsMMjfy1RN4zPSsIniQDlg6uGlsXIv74EPqmSH8I6NX5Ar0OQTaB24x)T7ZIlxLgFqPl(f7ZRD33b1)ZbUeb3sab3uXbBlX1BMUuy)d8A1Q7Ibgfy7fNlwleH)awIJKXnPbOEJTtKEK0mkzTfXmLz1(rOBB(r3T50L)7en7UlfnZL)atz6vX0MkVNUZ3TZ33C0F)Q)7p
```

**Comment by InfusOnWoW** [comment]
That's not a bug in WeakAuras. Blizzard has open bug reports for taint issues with bags: https://github.com/Stanzilla/WoWUIBugs/issues/310 In any case there's zero indication that the taint issue is a WeakAuras bug
