### ISSUE TITLE
Item check should include Item ID

### ISSUE THREAD

**Issue by Gogo1951** [WeakAuras/WeakAuras2#4337]
### Description

Trying to create a weak aura that checks your bag to make sure you're good to pull.

I want to check for Healthstones.

But if you add the ID "36892" it converts it to "Fel Healthstone"...

The problem is there are 3 items with the same name, and it's only checking for one behind the scenes. Maybe the first one?

36892
36893
36894

![image](https://user-images.githubusercontent.com/55365231/223509926-adf6c394-2aac-4f4f-997c-a9667d3c3eb2.png)

It either needs to check for ID -- and let me just add IDs, or it needs to check based on the actual item name and ignore IDs.

Happening in Wrath Classic.

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Add a Healthstone check.

### Export String

```true
!WA:2!DrvWUTTrq0OkGMyHwaB1aJAGCqignO5qLtCCDrdkkGPSKTkuKKPORD7fXLKRi3yQD3U7sjlFl6qR7TcDOFa6CpP)G6VacHI(b4pbFON7SlLCSJoio7mZoZ8E7mtUAf7xmOyWLpFkXNr7Wse(4N8aVHOqw99N4Fes1B7MeKTplMj(H8WpXOw96jXQgF8me1pIjAZiuLxLQnDQAp3NXIdydPDgs4y3TteX8nIukU81BTLoOLjSTUnQcKVIWOYDTLkKqvWRhHsKrfSGpQcJvcsyiwiB(mXcX)BmrH73e1h)O)4jtsK4U(SeQY9AzIhEaMQ6K0Rh58zDRSxhNUDC2Z25AJhDzCSaPyIIFhFn99cXuSG43jInSf112C5P1HGxQI2FBkKdzHBJBBbgIRDN2vB0W2eXIVCSKJJJRhilCLoIlRmxReO694XOryX87LNRLMpvwWrwQrCSL(EtdWEqL7aNfhwTr7Ah3ycKJmqxywar(2ekWvdWBJOJ4RHmYoz2Fdla)xp4g4ralOO4FeymGuF3nNHX89GA0xzJaAoAIeh3Z8yL(qiHsKkbOeCKyq2nwzkGwBCO(f51RNU5C4OhY)SqbG3GlFmVOcFUQRmcbf)Pznb54ByuA(Rht0hboSqWIYO4j3A(PFHKV6DIqfthvUC5YFDM2LvN1Eh70I)zgLOefdcfX)esGkYAp44nz5ICooWO8DZZAd)Pfv0vg7VnrQi9gbivWuakDaLwnB1SA6McaxAFMAC89n2twacQIVAnb5IshLGcagcvYX5EyFzMMB0nKjcorG4JpzHW8BJJ59S1XonQ3S6cSFNrg(A1B2SQDxRwooTEJD9do059xTd5c8glq2P3dzdisIxmo6FNhgZgwtG)Lem1Fu78VO8ozGtRx3sEq8cw2DSwLUASBd8w8u9XgyAOkAJzA5fiALjHlVcWi5YBSD6DT1XhfJZBYSteX)mkwkxXsF01yVbb0SIj(waDGfrErysyK6iRygk4pfeQUDI)mpjifJTeisGD)Kyfz9uxxpfeEQA9uuHz6zQbyijawT9Jrs5TQxeKiZgaummk4onBzqFpe0MOB61oBjbwul4jnl28i95mHAQW0K7yM(GTEZHUmGMBXnlJkmE5om3PGXasMwX5lx7XF8sh0nv7tKi45iW1dCUhjSWSEcylqhLUZj)nzVG10Q05ZRtf7QvBADbJ1pNNe3hM9SFz5xu(vtvm)fdIpAWF)usa)57B5CqPVQuLiS)zLGzQshIrXQiPcMRkrOLQt1RMyIr2OyEekpViqclxUaBfGXESR9q9qYrBNqcMruF5rN9Z722P53cpe6SHJUAjyQgeIJs77Q32OxEvhWZN)rR(9Zi0S5zOYkmbrjzI7M(j1UcJKAKA6KEy6MP7mpqVtbm3vVBdIVMbLJ1(PHF6ow9reAT0F14D6VLEz6VdF)0putrP9xx(vL)MId(Nt)))
```

**Comment by InfusOnWoW** [comment]
In the next release there is already a "exact item id" option in the item count trigger.

**Comment by Gogo1951** [comment]
@InfusOnWoW Thanks!
