### ISSUE TITLE
Addon Action Blocked: Protected Function MultiBarBottomLeft:SetPOintBase()

### ISSUE THREAD

**Issue by RaphanW** [WeakAuras/WeakAuras2#4339]
### Description

Just doing solo shuffles, when out of the blue, I cannot use my (base UI) action bars anymore. I could click on them, but the keybinds did not work until I reloaded my UI. 

I had a similar issue to this with omnibar and ended up just stopping using omnibar. I am hopeful that I don't have to "just stop using weakauras" so I reported this early.

I fresh reinstalled weakauras, and literally have exactly one weakaura (that I made) to track lifebloom on raid-style group frames.

Maybe this is UI taint that isn't weakaura's fault, but IDK so I decided to report the issue so smarter minds could judge. This happened once so far after dozens of shuffles, no idea how to reproduce. If this isn't a useful report just close, no worries.

### WeakAuras Version

Weakauras 5.3.7

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:126: in function `SetPoint'
[string "@FrameXML/EditModeManager.lua"]:638: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:564: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:743: in function `UpdateGridLayout'
[string "@FrameXML/StanceBar.lua"]:73: in function `UpdateState'
[string "@FrameXML/StanceBar.lua"]:12: in function <FrameXML/StanceBar.lua:10>
[string "=[C]"]: ?
```

### Reproduction Steps

Happened once so far after dozens of solo shuffles with this weakaura, no idea how to reproduce. If this isn't a useful report just close, no worries.

### Export String

```true
I fresh reinstalled weakauras, and literally have exactly one weakaura (that I made) to track lifebloom on raid-style group frames:

'!WA:2!1vvVVTTruCriGweHcJeLgJ6MKcxJgJ0HKg4uN0pIJJOTuKmSLSPOTtkma9jEhfVekYdhpkl5PeneKTcO)eeq36K27sw7Yb1U1nn3jp05(UJkY2bXAq49E89U37979LrP8TYJZJF7sdIzi(l3NIf(x7DA6AEEXeXZm4DsPEugE33tnef66hX3oIgk6zxBBRkpTS9iTzwrcKGgfAWUY543kctmlSRDntQBuOFpbN2SjHhpZI8jK)3Gy)OJwlikKeFOPOlJyHs4OL6R(pe1Ie)L93K6rAeef1AaM0iXZZg0IxU4MBxA3nhhN0G0Mek2Mt8ODSQVDXn30slPrzckq4BPFLCJtIjpLhLWCCJscf(CGVk8Ld7fZibbvWX5mtcPcli(fDh28uvZFpLTBHeU(tSDQtRdrdTZqN1ku32PUDblB2vpJL1G4ejI45FCFGlnHZXUcYvqBtSt5vq0VNzGcFaJcI4BKf(nMeIAeabmctb)43pMe4PrE5N0RbIVMwZYR(Nx)6pjtgJSLx9pU5n1uagfJea4ji(wOaMpk7zlTp3yae8wKMq1jEJzLZmcyBGCFPkSdXte4fXjPcE7CS8cshHtSpchD0ZsFLS91Yu)TWTyS5MY5aw2cjCytiSe0we840xyAkCj2v1sqjIiqjQRUf0SaWEs6Rq7qWAHVM9nFKhx9QobKMi3UoEqNb3)DAfErsSG61TXAfRAx0Aax1gsSHVywTw1ISV(IEkgN4sJbijRCgoK)kvgL2UpjJngOn70ku)jptOGD5sC6XZVtccdOoAEBB2LpdKLwQmmmYEoK85PV7nYKg5Tb3dfC)rAUJI4495iwV9NqmAQ3un)MvHXLjo5mdLdRuTArlh9Cj7RUOCnLZGn)fPqRiSJQ95WtDAD6XK5yF7fzbUlmJrDDGPkcmohG7ob8MKKgV9ZLFxw59w4wHstnuiVV8sYVxUS8bVwwZq(dYFu(tYFwoJCf5QA4v(ezb5A3iJSOSKCDFzf5gYNkll3Ao5Jn(inCHtimdbOPHpH20xCnZGie(nCAOEMCXgXavaXsZz1kjqqNvU3HM8OasUXUbO4yaoXoWcb3zL7(xneOay4Bw5(5mtLTFolTAkkwEyRGZ5T6qZyaPuFDSEMZeShRMWxQW6RZUmyqbSQhLGj4TqD8hbtaamvJPwwgNBinmnlaUCNC6u50wOTZEV7UCFuinvNhyflGTvLEhbftQl4KWMc)pfqXDgHvBaavCuRu5Xey9coUNspvdKChZwiAyjztT2sFjv(c5on8OH0y)pu8hg40q)bC9ge9My1MAyL0jqhiHhIc2d8h8TxR3PvpkH7sUrM(6fCXumXs3F2ay9OnZnuJtLPymj0QAX9kAnrIUcUcxvJt4KEMb0JpgXXwhP2kSI5XW5adlTQ(derUTtD6xy8MFBbk(KPNmM3gAq5QTYPBsRXv)RHMbLRzv5xQv1UWMd94WPaabH53SNK27wsjsLG93TAf7swf2Qy6Iu70qID7kQe2d5soyneS3jSPjIFWUvUZPC3PUYGLsO4Hp0LSEN9IoE31RdnKQWL4NE)DTP7uggDA0jF1avnJQ7m(YfTC9jUVSK8ZY2RnItvhhgt6WOPvzvsA1gfKqYV8crSfE0kCxFuyt465IYFDJSgLx9Fp4GxLjtMS9y8iOOj6kVD)3FizPnGdi)J(ucCbHRUpbo9bsVCYGCMqpHix(yRLV79V7dZ3(VF2)p
```

**Comment by RaphanW** [comment]
Similar protected function error happened again.  This time at the start of a shuffle in the waiting room trying to put buffs on. Last one was a few rounds in.  Was fine for a few shuffles, then the error came. No idea how to consistently reproduce it.

`1x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:89: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:23: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR4BUTTON11"]:2: in function <[string "MULTIACTIONBAR4BUTTON11"]:1>`

**Comment by InfusOnWoW** [comment]
That's unfortunately most likely on blizzard. They have not prioritized fixing their taint issues, and as such I can only direct you to them for assitance. Especially the first one reads like the typical EditMode issues. After using the edit mode its best to reload the interface.

**Comment by RaphanW** [comment]
Just in case you may be willing to help or provide a suggestion:

A few weeks ago, I removed about half of my addons, deleted my WTF folder, fully redid settings on my addons and base UI config, and since then, haven't hit edit mode since then.

Is there something more I can be doing to prevent errors like this? Because from past experience with stopping using omnibar, I think it is very likely that not using weakauras will stop this issue... But that's a really unsatisfactory solution.

**Comment by mrbuds** [comment]
This is a question for blizzard support, we can't fix their bugs sadly.

**Comment by InfusOnWoW** [comment]
I should mention that you might have auras installed that do touch protected frames, though these debug traces do not look like that is the case. They look entirely bogus. 

There's an additional taint logging you could try: https://wowpedia.fandom.com/wiki/CVar_taintLog, to debug the issue.

But that taint log is unlikely to be illuminating, since it nowadays rarely reports enough information on what exactly is happening and how taint spreads. An long standing issue that has been reported to blizzard before the release of dragonflight.
