### ISSUE TITLE
Setting anchor for basic group

### ISSUE THREAD

**Issue by DevoidCoding** [WeakAuras/WeakAuras2#434]
If you actually use the distribute or space option for group, it will automatically set the anchor of the group to left by default and you can't change it.

So, if you want to use the space option and want WeakAura to center your group anchored to screen, you actually need to provide an X offset manually. (see image below, first group)

The point of this is to be able to set the anchor of the group and using the distirbute/space option to obtain the result of the sencond group from the image.

[https://i.imgur.com/wh6QaCD.png](https://i.imgur.com/wh6QaCD.png)

n.b. : I'm sorry for my English. If something isn't clear enough, I can give more examples 👍

**Comment by InfusOnWoW** [comment]
I understand what you want. But that doesn't fit how the user interface works there was designed to work. That design has certainly its flaws, as you desribed, but there are no plans atm to do a bigger rework in that area.

**Comment by Drexl** [comment]
If DevoidCoding is describing what I think, then I'm having this frustration as well. In order to not constantly need to manual offset my groups I require the group anchor point to be "center" rather than forced at "Bottom Left".  :(
