### ISSUE TITLE
Incorrect texture margins when using category "Blizzard Atlas" for WOTLK classic version of WAs

### ISSUE THREAD

**Issue by NeckRomanSir** [WeakAuras/WeakAuras2#4345]
### Description

Selecting texture category "Blizzard Atlas" for WOTLK classic version of WAs now has all textures within this category showing on screen with extra bits of unrelated graphics, as if cropping zoomed out vs. what's shown in preview. This happened about a month ago, was hoping that the fix would come with update but several updates later, no change. Some pretty awesome textures there, most from post WOTLK era, like Legion.

### WeakAuras Version

5.3.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
no errors.
```

### Reproduction Steps

1. create new texture aura
2. Display tab, "texture settings" section -> "Choose" button
3. select a 'Blizzard Atlas' category
4. ANY texture displays snippets of random other textures not shown in preview selection.

### Last Good Version

Don't recall, at least 1-3 lupdates ago for WOTLK classic version.

### Screenshots

![wa texture issue_1](https://user-images.githubusercontent.com/86993963/224863722-b3ff3f3f-1884-430e-b671-6e8fecd99692.PNG)

**Comment by mrbuds** [comment]
This is already fixed for next release, i can't give any date for when it will be public
You can try use Alpha version of the addon if you really need that fixed, but don't make a backup of your data first
