### ISSUE TITLE
Conditions - Can't select talent when chosing for multiple spec

### ISSUE THREAD

**Issue by vincent-bru** [WeakAuras/WeakAuras2#4349]
**Is your feature request related to a problem? Please describe.**
When selecting "multiple" spec in the condition tab, the "talent" checkbox disapear. Since in dragonflight, the left tree is shared between spec, it is a missing spot

**Describe the solution you'd like**
If chosing multiple spec from same class, let us pick talent from left tree

**Describe alternatives you've considered**
Have to make multiple auras

**Additional context**

**Comment by emptyrivers** [comment]
this is incorrect, left side talent trees are not identical between specs.

**Comment by vincent-bru** [comment]
no wait, you jumped on conclusion too fast. The left tree is a shared tree. I never said it's identical. Surefly some key talents are spec bounded, but it's usualy only 1 to 3 of them.
let say I'am playing a rogue and I need to activate my wa for all my spec but only if they have chosen the 6th combo point talent. Deeper stratagem is available for all the spec since it is in the class tree, not in the spec tree only. As it is today, I have to do 3 copy of the same aura right? So I believe there a spot for small improvement

**Comment by mrbuds** [comment]
You can use the "spell known" load option

**Comment by vincent-bru** [comment]
Yes it works. Thank you.
