### ISSUE TITLE
part of foreground always show in the bar

### ISSUE THREAD

**Issue by HanzheZhang822** [WeakAuras/WeakAuras2#4354]
### Description

part of the foreground (the white line in the picture) always shows in the bar. It seems that it will happen when you change the scale or size of the bar to some specific values. There was no issue in version 5.3.7.
For example, this WA has this issue: https://wago.io/4P-Py3Fwy

### WeakAuras Version

WeakAuras 5.4.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [x] Yes
- [ ] No

### Reproduction Steps

UI scale: 0.65
WA Group scale: 1 or 1.3

### Last Good Version

WeakAuras 5.3.7

### Screenshots

![image](https://user-images.githubusercontent.com/25359938/225554887-042a889b-ab7d-41cb-a682-bde6a2741218.png)

**Comment by mrbuds** [comment]
What is your screen resolution and display settings regarding scaling?

**Comment by T3tzu** [comment]
3440x1440  fullscreen
![image](https://user-images.githubusercontent.com/25359938/225583577-049332d5-60b3-48b5-abf6-70c5e023e3a5.png)

**Comment by T3tzu** [comment]
> What is your screen resolution and display settings regarding scaling?

fullscreen
resolution: 3440x1440
UI scale: 0.65
