### ISSUE TITLE
Error retail

### ISSUE THREAD

**Issue by Mithras2801** [WeakAuras/WeakAuras2#4356]
### Description

I see this error on my Bugsack

### WeakAuras Version

5,4,2-2-ga5e163b

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
79x Lua error in aura 'Pull Indicator': Custom Fade Animation
WeakAuras Version: 5.4.2-2-ga5e163b
Aura Version: 1.0.16
bad argument #2 to '?' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: ?
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:361: in function `SetAnimAlpha'
[string "@WeakAuras/Animations.lua"]:94: in function <WeakAuras/Animations.lua:17>
```

### Reproduction Steps

i dont know

### Last Good Version

5,4,2-2-ga5e163b

### Export String

```true
xxxx
```

**Comment by InfusOnWoW** [comment]
79x Lua error in aura 'Pull Indicator': Custom Fade Animation

You need to fix the custom fade animation of that aura.
