### ISSUE TITLE
Evoker Essence should be handled the same way as Death Knight Runes

### ISSUE THREAD

**Issue by LieutenantMoon** [WeakAuras/WeakAuras2#4359]
Genuinely surprised this isn't already the case, they are functionally identical to Runes outside of the limit of 1 recharging at a time.

Please change :)

**Comment by InfusOnWoW** [comment]
The api for evoker essences has been broken since the release, they apparently fixed that with 10.0.7 release, so we indeed are planning to take another look at it.

**Comment by InfusOnWoW** [comment]
In the next release there will be a essence trigger, but note:
* Your intuition that essences are similar to runes is actually wrong. Essences are more similar to e.g. rogue's energy
* The api blizzard provides is still broken, the display will randomly be incorrect. That can't be helped. We have reported that as a bug, but well they haven't fixed their own essence display in 6 month, so clearly they don't care.
