### ISSUE TITLE
changing trigger from "player - buff missing" to "group trigger" keeps cooldown box disabled

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#436]
What steps will reproduce the problem?
1. make a wa "trigger unit aura - buff missing"
2. change unit it to "group"

What is the expected output? What do you see instead?
Cooldown box (from display) stays disabled when changing unit from player - buff missing to group.
I expected it to reset when changing it to group trigger.

What version of WeakAuras are you using?
happens on live and beta versions

**Comment by InfusOnWoW** [comment]
So it's disabled for both unit == player and unit == group?

Why should that be a bug then?

**Comment by Causese** [comment]
cause unit group isn't adjusted for what I did in the unit - player trigger.

**Comment by InfusOnWoW** [comment]
Thanks, will be fixed in the next release.
