### ISSUE TITLE
Regression: Item Icon not grabbed correctly 

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#4360]
### Description

After the item trigger changes, this aura no longer correctly shows the item icon from cache, the options still do.

>= 0 gets the icon, >= 1 does not

### WeakAuras Version

a26f2cc05affaddacf057f65c6e753c8ad4f5727

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. Log onto a character that does not have any of the rep items from the Dragon Isles
2. Import aura
3. Observe ? icon

### Last Good Version

5.3.7

### Export String

```true
https://wago.io/BlxGft4kr
```

**Comment by mrbuds** [comment]
It doesn't show an icon because trigger is not active and there is no dynamic information, it never used a cache, i don't know if there is something we can do

**Comment by Stanzilla** [comment]
Hrm but I'm pretty sure it worked before?

**Comment by InfusOnWoW** [comment]
I can't reproduce any problems with the linked aura, since it only shows up with >=1 tokens. Neither could buds, so :)
