### ISSUE TITLE
Custom Options bug when using arrays

### ISSUE THREAD

**Issue by Translitdk** [WeakAuras/WeakAuras2#4361]
### Description

This error might happen if  **Option Type - Option Group** was used and you delete one of the **Sub Options** 
![IMG](https://i.imgur.com/DJK4Roi.png)

It bricks SavedVariables of given aura and prevent Author Options tab to be used

P.S. I've met this one long time ago and it doesn't matter WoW Flavor, but coulnd't reproduce before

### WeakAuras Version

WeakAuras 5.4.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
https://i.imgur.com/DJK4Roi.png
```

### Reproduction Steps

1) Create any aura, go to the **Custom Options** tab and create **Option Group** with Array group type
2) Now you have to add couple of **Sub Options**: 
    - first one should be something that can't be used as **Entry Name Source**, for example **Toggle**
    - second one we use as the **Entry Name Source**, so we add "String" or "Number", and set it as source
    - delete first one and try to **Enter User Mode** > fatality
  
Error happens in this place ![IMG](https://i.imgur.com/KIodvEn.png) because when you remove one of the **Sub Options** SavedVariables have wrong **nameSource**
In my testing i had **3 Sub Options** and deleted **1** of them. And this is how SavedVariables looked like: ![IMG](https://i.imgur.com/jgs5TVV.png)
**2** subOptions with nameSource of **3**

### Last Good Version

-

### Screenshots

https://www.youtube.com/watch?v=sVdu6xneTfo

**Comment by InfusOnWoW** [comment]
@emptyrivers Did that fix work if people had actually broken settings? It looked like it only fixed new cases of it?

**Comment by emptyrivers** [comment]
oh, yeah i suppose there could be people with broken data. Do we have any reports of it?
