### ISSUE TITLE
1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Search()'.

### ISSUE THREAD

**Issue by PAKOTxx** [WeakAuras/WeakAuras2#4365]
### Description

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@FrameXML/LFGList.lua"]:2101: in function `LFGListSearchPanel_DoSearch'
[string "*LFGList.xml:1167_OnClick"]:2: in function <[string "*LFGList.xml:1167_OnClick"]:1>
[string "=[C]"]: in function `Click'
[string "return function() ------------------------------------------------------- Hide Buttons --------------------------------------------------"]:43: in function <[string "return function() -------------------------..."]:43>

Blizzard blocked the ability to access LFG completely? Or It can be fixed somehow? 

### WeakAuras Version

5.4.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Search'
[string "@FrameXML/LFGList.lua"]:2101: in function `LFGListSearchPanel_DoSearch'
[string "*LFGList.xml:1167_OnClick"]:2: in function <[string "*LFGList.xml:1167_OnClick"]:1>
[string "=[C]"]: in function `Click'
[string "return function() ------------------------------------------------------- Hide Buttons --------------------------------------------------"]:43: in function <[string "return function() -------------------------..."]:43>
```

### Reproduction Steps

LFG weakuras, somethis like https://wago.io/NDlWRwsLr

**Comment by Ulidan** [comment]
This error pops from random addons.
I renamed the addon directory for testing and logged in without any addon. This error was still popping at random when queueing for dungeons.
I believe it's self introduced taint by Blizzard. It seems they forgot to mark some of their code as secure and it spreads taint into their own code.
