### ISSUE TITLE
New talent selected load condition not working.

### ISSUE THREAD

**Issue by Theguyxd** [WeakAuras/WeakAuras2#4366]
### Description

Hey, ever since the patch yesterday/today depending on if you're NA or EU the new Skytouch/Skyreach talent does not seem to work. To make my basic Skyreach debuff show I have to just selected for the aura to load when I'm a monk/windwalker. If i select for the weakaura to load when I have either Skyreach or Skytouch spec'd the aura wont load. Maybe this is a known issue but just thought I'd throw it up on here real quick. 

This exact same setup worked fine for before the patch on talents not recently introduced to the game. 

### WeakAuras Version

Latest version as of this post. Do not have access to my pc atm.

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

The aura wont load when selecting the correct talent as a loading condition. That's all really.

**Comment by InfusOnWoW** [comment]
skytouch is new isn't it?

@mrbuds We probably need to regenerate the talent data one more time.

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release.
