### ISSUE TITLE
cooldown ready event

### ISSUE THREAD

**Issue by xxvalexx** [WeakAuras/WeakAuras2#4367]
### Description

hello.lm using cooldown ready event dor some skills.very useful for me but have a problem.problem is timing. lm maked one skill cooldown and one more big skill cooldown ready event. cooldown ready event skill incoming late.maybe 0.30 sec maybe some times little more late and some times incoming good timing.can you fix this pls?

### WeakAuras Version

5.4.2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

```true
hello.lm using cooldown ready event dor some skills.very useful for me but have a problem.problem is timing. lm maked one skill cooldown and one more big skill cooldown ready event. cooldown ready event skill incoming late.maybe 0.30 sec maybe some times little more late and some times incoming good timing.can you fix this pls?
```

### Reproduction Steps

hello.lm using cooldown ready event dor some skills.very useful for me but have a problem.problem is timing. lm maked one skill cooldown and one more big skill cooldown ready event. cooldown ready event skill incoming late.maybe 0.30 sec maybe some times little more late and some times incoming good timing.can you fix this pls?

**Comment by InfusOnWoW** [comment]
You need to put a lot mroe effort into creating bug reports if you want us to take a look.
