### ISSUE TITLE
WA not load

### ISSUE THREAD

**Issue by kendinikertenkelebek** [WeakAuras/WeakAuras2#437]
**What steps will reproduce the problem?**
When i logged in.

**What is the expected output? What do you see instead?**
Lua error.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, i'm only using WeakAura.

**What version of WeakAuras are you using?**
2.5.12

**Was it working in a previous version? If yes, which was the last good one?**
8.0-beta6

**Do you have an error log of what happened?**
Sure.

1/9:
Message: Interface\AddOns\WeakAuras\Prototypes.lua:25: Cannot find a library instance of "HereBeDragons-1.0".
Time: Sun Jun  3 18:20:44 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:25: Cannot find a library instance of "HereBeDragons-1.0".
[C]: in function `error'
Interface\AddOns\WeakAuras\Libs\LibStub\LibStub.lua:38: in function `LibStub'
Interface\AddOns\WeakAuras\Prototypes.lua:25: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "HereBeDragons-1.0"."

2/9:
Message: Interface\AddOns\WeakAuras\Types.lua:320: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sun Jun  3 18:20:44 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\Types.lua:320: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\WeakAuras\Types.lua:320: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

3/9:
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:41: Cannot find a library instance of "HereBeDragons-1.0".
Time: Sun Jun  3 18:20:44 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:41: Cannot find a library instance of "HereBeDragons-1.0".
[C]: in function `error'
Interface\AddOns\WeakAuras\Libs\LibStub\LibStub.lua:38: in function `LibStub'
Interface\AddOns\WeakAuras\WeakAuras.lua:41: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "HereBeDragons-1.0"."

4/9:
Message: Interface\AddOns\WeakAuras\BuffTrigger.lua:827: attempt to index field 'frames' (a nil value)
Time: Sun Jun  3 18:20:44 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\BuffTrigger.lua:827: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\BuffTrigger.lua:827: in main chunk

Locals: tinsert = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
next = <function> defined =[C]:-1
type = <function> defined =[C]:-1
WeakAuras = <table> {
 slant_mode = <table> {
 }
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:292
 ScanAurasGroup = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:769
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:461
 prettyPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:13
 anchor_frame_types = <table> {
 }
 trigger_require_types_one = <table> {
 }
 form_types = <table> {
 }
 ScanAuras = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:408
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:33
 ShowDisplayTooltip = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:733
 point_types = <table> {
 }
 race_types = <table> {
 }
 unit_threat_situation_types = <table> {
 }
 DisplayToTableString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:497
 event_types = <table> {
 }
 trigger_modes = <table> {
 }
 faction_group = <table> {
 }
 aura_types = <table> {
 }
 text_word_wrap = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 check_types = <table> {
 }
 aura_cache = <table> {
 }
 spark_hide_types = <table> {
 }
 group_hybrid_position_types = <table> {
 }
 text_check_types = <table> {
 }
 class_color_types = <table> {
 }
 blend_types = <table> {
 }
 actual_unit_types = <table> {
 }
 trigger_require_types = <table> {
 }
 threat_unit_types = <table> {
 }
 group_sort_types = <table> {
 }
 me = "Leithrien"
 StartProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:29
 sound_condition_types = <table> {
 }
 glow_action_types = <table> {
 }
 IsSpellInRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:20
 debuff_types = <table> {
 }
 PowerAurasSoundPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Sounds\"
 hostility_types = <table> {
 }
 trigger_types = <table> {
 }
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:31
 printPrefix = "WeakAuras: "
 sound_channel_types = <table> {
 }
 RegisterRegionOptions = <function> defined @Interface\AddOns\WeakAuras\Init.lua:24
 containment_types = <table> {
 }
 L = <table> {
 }
 ImportString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:1174
 text_automatic_width = <table> {
 }
 PowerAurasPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Auras\"
 debuff_class_types = <table> {
 }
 unit_types = <table> {
 }
 group_hybrid_sort_types = <table> {
 }
 character_types = <table> {
 }
 actual_unit_types_with_specific = <table> {
 }
 versionString = "2.5.12"
 RegisterRegionType = <function> defined @Interface\AddOns\WeakAuras\Init.lua:21
 texture_wrap_types = <table> {
 }
 precision_types = <table> {
 }
 font_flags = <table> {
 }
 class_types = <table> {
 }
 inverse_point_types = <table> {
 }
 maxTimerDuration = 604800
 StartProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:27
 spark_rotation_types = <table> {
 }
}
L = <table> {
 No Instance = "No Instance"
 Scenario = "Scenario"
 Group %s = "Group %s"
 Stacks = "Stacks"
 Whisper = "Whisper"
 Max Charges = "Max Charges"
 Raid = "Raid"
 Player Level = "Player Level"
 Attach to End = "Attach to End"
 Cooldown Progress (Spell) = "Cooldown Progress (Spell)"
 Caster = "Caster"
 Aggro = "Aggro"
 Options will finish loading after combat ends. = "Options will finish loading after combat ends."
 Summon = "Summon"
 Master = "Master"
 Instakill = "Instakill"
 Bottom

5/9:
Message: Interface\AddOns\WeakAuras\GenericTrigger.lua:726: attempt to index field 'frames' (a nil value)
Time: Sun Jun  3 18:20:44 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\GenericTrigger.lua:726: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\GenericTrigger.lua:726: in main chunk

Locals: tinsert = <function> defined =[C]:-1
tconcat = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
tostring = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
error = <function> defined =[C]:-1
setmetatable = <function> defined =[C]:-1
IsPlayerMoving = <function> defined =[C]:-1
aceEvents = <table> {
 UnregisterAllMessages = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 UnregisterAllEvents = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 SendMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 RegisterMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 UnregisterEvent = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 RegisterEvent = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
}
WeakAuras = <table> {
 slant_mode = <table> {
 }
 SetAuraVisibility = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:292
 ScanAurasGroup = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:769
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:461
 prettyPrint = <function> defined @Interface\AddOns\WeakAuras\Init.lua:13
 anchor_frame_types = <table> {
 }
 trigger_require_types_one = <table> {
 }
 form_types = <table> {
 }
 ScanAuras = <function> defined @Interface\AddOns\WeakAuras\BuffTrigger.lua:408
 StopProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:33
 ShowDisplayTooltip = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:733
 point_types = <table> {
 }
 race_types = <table> {
 }
 unit_threat_situation_types = <table> {
 }
 DisplayToTableString = <function> defined @Interface\AddOns\WeakAuras\Transmission.lua:497
 event_types = <table> {
 }
 trigger_modes = <table> {
 }
 faction_group = <table> {
 }
 aura_types = <table> {
 }
 text_word_wrap = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 check_types = <table> {
 }
 aura_cache = <table> {
 }
 spark_hide_types = <table> {
 }
 group_hybrid_position_types = <table> {
 }
 text_check_types = <table> {
 }
 class_color_types = <table> {
 }
 blend_types = <table> {
 }
 actual_unit_types = <table> {
 }
 trigger_require_types = <table> {
 }
 threat_unit_types = <table> {
 }
 group_sort_types = <table> {
 }
 me = "Leithrien"
 EndEvent = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:308
 StartProfileAura = <function> defined @Interface\AddOns\WeakAuras\Init.lua:29
 sound_condition_types = <table> {
 }
 glow_action_types = <table> {
 }
 IsSpellInRange = <function> defined @Interface\AddOns\WeakAuras\Prototypes.lua:20
 debuff_types = <table> {
 }
 PowerAurasSoundPath = "Interface\Addons\WeakAuras\PowerAurasMedia\Sounds\"
 split = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:97
 ActivateEvent = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:368
 hostility_types = <table> {
 }
 ScanEvents = <function> defined @Interface\AddOns\WeakAuras\GenericTrigger.lua:619
 trigger_types = <table> {
 }
 StopProfileSystem = <function> defined @Interface\AddOns\WeakAuras\Init.lua:31
 printPrefix = "WeakAuras: "
 sound_channel_types = <table> {
 }
 RegisterRegionOptions = <function> defined @Interface\Ad

6/9:
Message: Interface\AddOns\WeakAuras\RegionTypes\Model.lua:298: attempt to index field 'frames' (a nil value)
Time: Sun Jun  3 18:20:44 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Model.lua:298: attempt to index field 'frames' (a nil value)
Interface\AddOns\WeakAuras\RegionTypes\Model.lua:298: in main chunk

Locals: SharedMedia = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:285
 GetDefault = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:281
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:272
 GetGlobal = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:268
 List = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:258
 HashTable = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:254
 MediaTable = <table> {
 }
 RegisterCallback = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 IsValid = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:250
 LOCALE_BIT_zhCN = 4
 UnregisterCallback = <function> defined @Interface\AddOns\WeakAuras\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Fetch = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:243
 DefaultMedia = <table> {
 }
 Register = <function> defined @Interface\AddOns\WeakAuras\Libs\LibSharedMedia-3.0\LibSharedMedia-3.0.lua:217
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
L = <table> {
 No Instance = "No Instance"
 Scenario = "Scenario"
 Group %s = "Group %s"
 Stacks = "Stacks"
 Whisper = "Whisper"
 Max Charges = "Max Charges"
 Raid = "Raid"
 Player Level = "Player Level"
 Attach to End = "Attach to End"
 Cooldown Progress (Spell) = "Cooldown Progress (Spell)"
 Caster = "Caster"
 Aggro = "Aggro"
 Options will finish loading after combat ends. = "Options will finish loading after combat ends."
 Summon = "Summon"
 Master = "Master"
 Instakill = "Instakill"
 Bottom Right = "Bottom Right"
 Down = "Down"
 Officer = "Officer"
 In Vehicle = "In Vehicle"
 Slide from Left = "Slide from Left"
 Resurrect = "Resurrect"
 Rotate Right = "Rotate Right"
 Pulse = "Pulse"
 Dispel = "Dispel"
 Source In Group = "Source In Group"
 Amount = "Amount"
 Power Type = "Power Type"
 Ascending = "Ascending"
 Region type %s not supported = "Region type %s not supported"
 Loop = "Loop"
 Shoulder = "Shoulder"
 1. Text Color = "1. Text Color"
 2. Text Color = "2. Text Color"
 >= = ">="
 <= = "<="
 Poison = "Poison"
 Mirror = "Mirror"
 Remaining Time = "Remaining Time"
 Instance Difficulty = "Instance Difficulty"
 Distance = "Distance"
 Ambience = "Ambience"
 Looking for Raid = "Looking for Raid"
 Aura Type = "Aura Type"
 Any Triggers = "Any Triggers"
 = = "="
 < = "<"
 Inherited = "Inherited"
 > = ">"
 Minimum = "Minimum"
 Hostility = "Hostility"
 Block = "Block"
 Extra Attacks = "Extra Attacks"
 Timed = "Timed"
 Second Text Color = "Second Text Color"
 Receiving display information = "Receiving display information"
 Specific Unit = "Specific Unit"
 Heal = "Heal"
 Arena = "Arena"
 BigWigs Addon = "BigWigs Addon"
 Legs = "Legs"
 Changed = "Changed"
 5 Man Dungeon = "5 Man Dungeon"
 Main Hand = "Main Hand"
 Player Faction = "Player Faction"
 Monster Emote = "Monster Emote"
 Shake = "Shake"
 Aura Removed = "Aura Removed"
 Trigger: = "Trigger:"
 Print Profiling Results = "Print Profiling Results"
 Overlay Cost of Casts = "Overlay Cost of Casts"
 Chest = "Chest"
 Slide from Bottom

7/9:
Message: (null)
Time: Sun Jun  3 18:20:44 2018
Count: 18

8/9:
Message: Binding header WEAKAURAS is defined more than once in Interface\AddOns\WeakAuras\Bindings.xml
Time: Sun Jun  3 18:20:44 2018
Count: 6

9/9:
Message: Interface\AddOns\WeakAuras\RegionTypes\Model.lua:278: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sun Jun  3 18:20:44 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\RegionTypes\Model.lua:278: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
Interface\AddOns\WeakAuras\RegionTypes\Model.lua:278: in function <Interface\AddOns\WeakAuras\RegionTypes\Model.lua:271>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

Please provide any additional information below.

[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/2066070/WeakAuras.lua.zip)

**Comment by kendinikertenkelebek** [comment]
![ekran resmi 2018-06-03 18 05 32](https://user-images.githubusercontent.com/12395430/40888211-7f5375c8-675c-11e8-9e85-4ee517617313.png)
![ekran resmi 2018-06-03 18 05 43](https://user-images.githubusercontent.com/12395430/40888212-7f7042e8-675c-11e8-9fd3-83c0cf4f99d9.png)
![ekran resmi 2018-06-03 18 05 53](https://user-images.githubusercontent.com/12395430/40888213-7f8c90b0-675c-11e8-8be3-9838c31e4197.png)
![ekran resmi 2018-06-03 18 06 04](https://user-images.githubusercontent.com/12395430/40888214-7facea7c-675c-11e8-89ac-8e4146ae2ba6.png)
![ekran resmi 2018-06-03 18 06 12](https://user-images.githubusercontent.com/12395430/40888215-7fc8faaa-675c-11e8-9d52-bfb9a5fb7f6d.png)
![ekran resmi 2018-06-03 18 06 22](https://user-images.githubusercontent.com/12395430/40888216-7fe2c160-675c-11e8-95be-29ea93a8d99e.png)
![ekran resmi 2018-06-03 18 06 34](https://user-images.githubusercontent.com/12395430/40888217-7ffe2680-675c-11e8-9f1b-5f81a1bb9121.png)
![ekran resmi 2018-06-03 18 06 50](https://user-images.githubusercontent.com/12395430/40888218-802491a8-675c-11e8-8809-156fc7299903.png)
![ekran resmi 2018-06-03 18 06 58](https://user-images.githubusercontent.com/12395430/40888219-80404268-675c-11e8-853b-298c4b46c93c.png)

**Comment by SpatenLa** [comment]
2.5.12 is NOT a BfA Beta version. it cant work there.
