### ISSUE TITLE
"Tooltip on Mouseover" not showing a Tooltip anymore

### ISSUE THREAD

**Issue by Thovald** [WeakAuras/WeakAuras2#4372]
### Description

Hi,

when hovering over an icon or a bar which has "Tooltip on Mouseover" checked, the Tooltip doesn't display. 
This happens with old weakauras that used to work correctly in the past as well as newly created ones.

There are no errors and I tested it with only Weakauras loaded.

Thank you!

### WeakAuras Version

5.4.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

1. create an icon or bar to track your buffs
2. check "tooltip on mouseover"
3. hover over the icon
4. no tooltip :<

**Comment by johndoe8908** [comment]
It's for me too.

**Comment by johndoe8908** [comment]
Thank you mrbuds!
You're my hero!!
