### ISSUE TITLE
Bug with buff trigger

### ISSUE THREAD

**Issue by ki-88** [WeakAuras/WeakAuras2#4373]
### Description

I keep getting various of lua errors. This bug happened with previous versions as well. Its worth to mention that there is no custom code. Its just buff trigger for unitframes. Additionally, it is causing a lot of frame drops specially in bigger raids. 

### WeakAuras Version

5.4.3

### World of Warcraft Flavor

Classic

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
https://justpaste.it/bicdi
https://justpaste.it/axvf8
```

### Reproduction Steps

happens randomly when joining arenas or leaving arenas..etc
[WeakAuras.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/11056477/WeakAuras.lua.zip)

### Export String

https://wago.io/0dPiUTwBq)

**Comment by mrbuds** [comment]
We need your data as asked in issue template

**Comment by ki-88** [comment]
posted the WA link. Anything am I missing ?

**Comment by ki-88** [comment]
Uploaded the zip file.
