### ISSUE TITLE
Actions / Glow options move items around the screen

### ISSUE THREAD

**Issue by krazyito65** [WeakAuras/WeakAuras2#438]
What steps will reproduce the problem?
Create any aura.  Text / Icon probably work best.
Actions -> On show -> Glow -> select Frame -> choose newly created aura.

What is the expected output? What do you see instead?
Expected output:  Icon remain stationary. 
Result:  Icon moved to edge of screen out of scope.

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
No, but i don't think it will make a difference.

What version of WeakAuras are you using?
Live: 2.5.12  -- video is 11, but it happens in 12 as well.

Was it working in a previous version? If yes, which was the last good one?
Not sure when it was last working.

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
No errors.

Please provide any additional information below.
https://www.youtube.com/watch?v=rPwgGRYCFvo  -- heres a video of it happening.

```  HERE ```

**Comment by InfusOnWoW** [comment]
Thanks, will be fixed in the next release.
