### ISSUE TITLE
More intuitive Load options for Zones

### ISSUE THREAD

**Issue by Elitesparkle** [WeakAuras/WeakAuras2#4383]
When configuring an aura to Load only in a specific Zone or Dungeon, it would be nice to have a list of names with checkboxes to toggle rather than list of codes that are hard to mentally parse. Codes are not intuitive at all, which is a problem for auras which are supposed to be easily customizable by users.

My idea is to have a dropdown/checkbox field (exactly like for Class and Specialization) to select one or more Dungeons. Since the list would be too long, I believe it has to be handled with another field (for example Expansion) that should be mandatory to fill (such as Class and Specialization for selecting Talents) before being able to access the Dungeons field.

Alternatively, allow the author to create customized Load options, in this case for a limited list of Zones. The author should insert IDs to tell which Zones should be in the checkbox list seen by the user. The user should be able to easily select one or more Zones based on their names (visible), not their IDs (behind the scenes).

I need this kind of feature at least for the current Mythic+ rotation. In that case the list would have only 8 elements, making it way easier to implement and use. The interface already provides in the tooltip a shortcut for configuring those Zones, however, I think it's not enough for the average user.

**Comment by InfusOnWoW** [comment]
There are an order of magnitude more zones than specs. That would not help at all. Also the benefit of that feature sounds minimal at best.

For the second idea, that sounds like a very complex idea for a minor benefit.
