### ISSUE TITLE
WA_DELAYED_PLAYER_ENTERING_WORLD

### ISSUE THREAD

**Issue by Elitesparkle** [WeakAuras/WeakAuras2#4387]
### Description

The event `WA_DELAYED_PLAYER_ENTERING_WORLD` is not being fired all the time. I believe it doesn't fire in the first session after starting the game but fires if we relog without restarting the game. Sometimes it works earlier than that. It's inconsistent.

### WeakAuras Version

5.4.3

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

```true
BugSack and BugGrabber give no errors.
```

### Reproduction Steps

1. Intall [this aura](https://wago.io/NuaMa3RXZ) or restart the game if you already have it installed.
2. Enter inside Ruby Life Pools.
3. The text won't be visible because `WA_DELAYED_PLAYER_ENTERING_WORLD` didn't fire.
4. Exit from Ruby Life Pools.
5. Repeat from 2 to 4 if you wish.
6. Logout, without restarting the game.
7. Login with the same character.
8. Enter inside Ruby Life Pools.
9. The text will be visible because `WA_DELAYED_PLAYER_ENTERING_WORLD` fired.

**Comment by mrbuds** [comment]
It's an internal event, auras are not supposed to use it, you should use a status trigger instead
