### ISSUE TITLE
KeyBinds on CD-Weakauras

### ISSUE THREAD

**Issue by felipsbook** [WeakAuras/WeakAuras2#4389]
When I'm learning a new class or spec, i'm not always sure which bind is which, so I keep glancing more to my hotbars than my UI Weakaura.

I would love a feature to search in your hotbars if that spell is binded somewhere, and show the bind it's attached to on the aura.

I do it manually adding texts, but every class is a new burden, would love to automate that.

Love you guys's work!

**Comment by InfusOnWoW** [comment]
One of the developers looked at adding that as a sub element, but there are too many edge cases which made that feature not work out.

There's a bit of more details at the PR:
https://github.com/WeakAuras/WeakAuras2/pull/3816
