### ISSUE TITLE
Add Fishing Journal Fishing Pole to Weapon Enchant Detection

### ISSUE THREAD

**Issue by EmmaAvemour** [WeakAuras/WeakAuras2#4390]
**Is your feature request related to a problem? Please describe.**
I ran into a problem with detecting when fishing lure is applied to a fishing pole with the new Dragonflight profession system, since it is no longer in your mainhand, but in the profession journal. I outlined the problem [here](https://canary.discord.com/channels/172440238717665280/1092495614983557130/1092495614983557130) in the WeakAuras Community discord, just linking it as to not make this ticket gargantuan.

**Describe the solution you'd like**
Under trigger Item>Weapon Enchant / Fishing Lure>Weapon , add the fishing journal fishing pole (slot 28) to the dropdown so that temporary enchantments from lures can be detected on it without requiring custom code

**Describe alternatives you've considered**
I can't think of any that'd attack the root of the problem I ran into, technically a field for specifying what temporary enchant is applied under trigger Combat Log>Enchant Applied would also work since it can only detect that an enchant *is* applied over *what* enchant is applied, which doesn't leave room for detecting if you are using a 10 minute lure or a 15 minute lure.

**Comment by InfusOnWoW** [comment]
You can always report that as a bug to blizzard, since after all the fishing lure is currently not conveniently shown in the default ui.
