### ISSUE TITLE
Swing Timer triggers not working for Retribution Paladin

### ISSUE THREAD

**Issue by vorpalgithub** [WeakAuras/WeakAuras2#4394]
### Description

Unsure if this applies to any other classes as well. Seems like maybe a 2 hand weapon thing?

Swing timer triggers do not currently do anything. They are never considered active to cause a weakaura to appear and they do not contain any information for a progress bar or something to use.

I am using a simple trigger set to Player/Unit Info > Swing Timer > Main Hand (Off Hand also does not work)

I also tried using the inverse and remaining time options but that did not seem to change anything.

I also tried copying another currently-working swing timer from my demon hunter and adjusting it to load on ret paladin and it does not work either.

### WeakAuras Version

Weakauras-5.4.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

Create swing timer weakaura for 2 handed spec
See it fail to load/do anything

### Last Good Version

N/A

### Export String

```true
!WA:2!1v1ZVTrXx8AzbvApaTg10uururjbufn)WPjLVvIgL1XP2LK4O1oHwuLSN1ZZEN21ZSmZSUj9yqQQhao4d8hGVWfo5)eI4pGbRVWFarcj4AK4oVzwNKsLypS7BM59EFEZ79592CBuOxbAb6RU7qvcr(SVIr1rx5iNCToDuG(r5cFoPRO66dQuAVdwAVWkrYdYo678gr4TJeYDemUoSu5TBuoySZ2aHMOzcEUKl)VwVLGc(RTBJAftLXjxpsRtu3B(5Timhtm)zqm)slkjTTwOwjqPjsTxyhgNPI88XpAVd1sw3UGuXNvor8vxoPGe6rWZ5DBksajrlKfUFaN0duEdo7SclCyQcAgr40w(23(2dgsHW0oDACaAyLYBUZg7U5yRANzwusb7AsOsidRaKy7LP1XQ0qOpW11rJz7pQzP1Q3Oz9gRf0iWT)O6phn(gny9a5iRdy8(yCdrhQsG44QuLNFkELctIjhasFngaMBE85q5GXfXw1ohWDKacyq9DkV5Mds5tYcEZAk8JMzm30C9wMzBz(qZnq5p2mvlZN0YC1IIoDmxZ8(MBzv8LoXjkNPXRzYT8grzQNMYXcrFOiHFqYLjo5gzyzJSF(cdzTf8MTfXc5dZJpNGKbqYjX7HxtSc(TdcjYs2JlINNl)acN1ZXgwX8oBCequqDTe4D1rx0mJpxWHX0uPtJM2SbMSqeOQdTQARpM7yMEdZsO2O0YMvm3f)(UV5ohEkSpSYQ)XVzF(vu4VTp)zLv)R)N9PrESSRiAlCquGJRg960)hNBiMVdGUwQ49MYmZyCziP9Z6kfPC6Kn6iKq2g9hfkKuq2uXEbKF8KfzTjfXaYmZaRdCBF0KtZsD5YLl)Xt2PptXcJHwN6mGIz7fVXoS9H4t9PWfF5dJaw3i9BnqbXDCnIMl6hli0Fp5dSCgUq3KPHEndf8ufJ2e(MuwscqJoUDmrPWyJ2ezITNnuH80y47d6LgRzEJzCSXJ3gC1apFNoMTYB22l5A)NEnS4cl(5lUWal0o)3Y3MjMcT6eh5hnYPlgaooT1TTcCQIEF06L3Q22v21ojbnX5goY2LrHAsms6rhn705N9hAn9B)z3VvYLS(ZgFNIV3XUINpQl1splU26RNCj0nRrFAQsduGUfz)OXKunwrQL4gX4H9zPY2qiRxIqQZQ)nG9rAbK8PvT05oK2WtkruAmh5tKpz3Q3(8v3UU1a5(zuMCHiBTdRRxajojIK)nHNXJgkDek3SgcY9qIXjzCKnK4Wk7(H1lfuU82jVxxjHYWBEnP9TRRyyLAbv)6AB3yTnh4A(Wkaeeu9bvAi7N10T6hXOjxTKmvHwJJFWom2Za1KXqUlyfhX5lK6SlAWw40iw2VbkDwZS)leIE5cvqp0XHlo3cZT0cd1I2tGz6CV8NM4ngLc8GTlVx5aFBqfnQJ9UGat0Klg8C7Fw(LRCY59oLoL2Vt(fMB5IPm6Oh39lxAR96rQgvvE6ys34L6U6Z1VWiX5zbtVH2XcSSs4igh7cZMRm1iuSnu2oLu16yGtWMPhmjpgvqfS8C3zU7uO)))r)Zd
```

**Comment by InfusOnWoW** [comment]
Your auto attacks get replaced, and thus the events for the auto attacks are missing. There are events for crusading strikes, but we don't want to add a special case just for retribution paladins to that trigger.

There are suitable auras on wago, e.g. https://wago.io/5juqfYglj that handle that.
