### ISSUE TITLE
Preview Sounds

### ISSUE THREAD

**Issue by JL907** [WeakAuras/WeakAuras2#4396]
Is your feature request related to a problem? Please describe.
Yes, currently in WeakAuras, when selecting a sound from the sound drop-down menu, it's difficult to know which sound you are selecting without actually playing it. This can be frustrating when trying to quickly find a specific sound in a long list.

Describe the solution you'd like
I would like to request a feature that allows users to preview sounds in the sound drop-down menu by adding a "preview" button next to each sound in the drop-down menu. Similar to how BigWigs does it, This would make it much easier and more efficient to select the desired sound. However unlike bigwigs I'd like it so that currently playing sounds stop playing when a new one is previewed

Describe alternatives you've considered
A feature that allows users to preview sounds in the sound drop-down menu by hovering over the sound name. 

Additional context
I have attached a screenshot of the sound drop-down menu in BigWigs for reference. Thank you for considering this feature request!

![image](https://user-images.githubusercontent.com/7343912/230745038-44ed848e-2e84-4715-8411-d5d050859eb8.png)

**Comment by InfusOnWoW** [comment]
We play the sound on selecting the sound.
