### ISSUE TITLE
Massive freeze when getting into angel form as Holy priest

### ISSUE THREAD

**Issue by Meivyn** [WeakAuras/WeakAuras2#4399]
### Description

This happens for example with buffs checkers WeakAuras such as this one: https://wago.io/jNjrKl3US/172
Here's a short video of it: https://youtu.be/VFBQ360gqsE

I managed to isolate this issue using the profiler (not shown here, but this is for ~ 2.5 s of profiling).
![image](https://user-images.githubusercontent.com/793322/231827880-eff9815c-570d-4619-8719-7968e14a772e.png)
![image](https://user-images.githubusercontent.com/793322/231827899-b48a5032-23fa-4574-986c-974db5b2681c.png)

What happens is that the game fires `PLAYER_REGEN_ENABLED` and then `PLAYER_REGEN_DISABLED` when you get into Spirit of Redemption. Here's the sequence of events that are fired when starting an encounter, dying, getting into angel form, and then dying. This makes all WeakAuras configured to load out of combat to load and unload in a 300 ms timeframe.
![image](https://user-images.githubusercontent.com/793322/231828321-486240ef-4fa6-4192-8785-b49b135fef01.png)

### WeakAuras Version

WeakAuras 5.4.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Be a Holy priest.
2. Have a bunch of WeakAuras that loads out of combat only.
3. Get into any encounter in raid (unsure if that happens outside, kind of hard to try)
4. Die from any mechanic.

**Comment by Meivyn** [comment]
I mean, while those specific auras might be poorly designed, the issue is the same. That would happen with any aura that is configured to load out of combat. As long as you have a lot of them, which is often the case, it'll happen.

**Comment by InfusOnWoW** [comment]
No, "the massive freeze" is very likely attributable to these horrible auras.
