### ISSUE TITLE
My WeakAuras is unable to retrieve the count value from the BigWigs timer.

### ISSUE THREAD

**Issue by GnomeTW** [WeakAuras/WeakAuras2#4401]
### Description

(1) When I use "%count" in the display of WeakAuras, the value displayed is always 0 regardless of the number of times the BigWigs timer shows for that timer. For example, if the BigWigs timer shows "Breath (3)", the %count in WeakAuras displays 0.

(2) If I use BigWigs' timer bar in a trigger of WeakAuras and input a number in the count field, it will not be triggered. For example, if the trigger content is the BigWigs timer bar name "Teleport" and the count is "2", even if my BigWigs has already displayed "Teleport (2)", this WeakAuras trigger will still not be triggered.

### WeakAuras Version

5.4.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Reproduction Steps

1. Enter "%1.count" in the text display of WeakAuras.
2. In the trigger options of WeakAuras, check "BigWigs TIMER BAR".
3. Enter "Teleport" in the message field.
4. Enter "2" in the count field.

### Export String

```true
!WA:2!fsv3YnTXxC8OH2IMo0e32aeGIagcjqBAsasH(VT0Ou7GP5lKuIHsP2R0UYAPYAxwTkeNo9gthgUopc(MEdx5hbU4)1NXtN(aWJapbDxlbKjLm9gP9JZzp7VpoBPnlN6CTPV60xTC7Y4Y4ND6b(OGFfly8fzXmXTnmmw3yMPV2l9zcmryxSjFe7y6o7Geylpglws59KSGTiIukl54LE6Fk2ETWWuISKFEIrIofl0tqAPcYRdN40sWY49YJWLUd5W9ZhNx7sLkz4KgGIjg(bSKqAltbkqQsoDENujsin9dPj00itB1pPzxPG2QL6sm(eIIHpThM4NfgQlN4wvwE9QBSSTuxBuManx3uojoUgo18LPz(KTijsxv00T73yXfC9A46TGJNDM6W95XOoeHtcQnj10zyO(3IGILrVj11fevQoURxz5L3nlP4kywaWk4we(OUpkdjiwvZIJTQhrLKxrtKerckEZC27j9rjbrmX6m1g(lwzvVko7IsOTrAKppms1xqqPexPGK0sg9(WXStyjKbyfE0r0qJorkrXy40U6q1yhUSDBenPkCjvcWLHph(cyA1)r3)kNJI5hFsjjvoLLDTLQxBjxRaMcmw2BSuFAsitKFtm7hkuCH6EGKiJxLFPRQxsxpF3fDQuz1bOmPA514dvnZc5TwIYiy8I8j52IJ0trIodDgPM7MsIdhIFyYEACqZt3oMHWv9LkhrICmN2zkJNPTscdgd(wtNGyuAQEKDQYlPhmxgf3)rZoRBONloA(hvo4spBsLNtgttuvEdVLRTAf(LX0uT66r2w2ihFn4nK02Kg4ok9Mg0qgjiPrSyCNbPrim7X3l)AFQdbxeMKBDWNq(Ss8rcYsLS26i2GJrscCMxQihMMmdQtXYi7futHpsPWMWOMqzt4Jp6eWN8)HJ5JWyf(3nlL0yOwebJdN0wQolFBbbjJ6Q3spVjCk40WjmHpZeoZaBAR60wPwEQBIaolCUb6yAWugeKKj6P6EWtEXlKEXPGpfgdoVjFuDd2weVCR7kmm55hIFY3j8Yh4OrjMpXbZaXKwOGoncJzmreCdF7188wBf7qwIKpsvbDhR7KHWAxKLNhC9Xhdo2aLzq)oK(9Hem8)cHVxlNW3m873P)2NKmKkick2EU5N5RGBQx(vAIypB1SRUo63worHYD3CLZWj41pWzahbwHF23bcMD6HhuXuvtYu6(V93d9L)3DvW7vIF(dMI4csav38BaFTz3hR6lQlq8U1lgah1u8qL9Hg2XE5kv9GdRFIv3Po2KEvC9MYAZ18QzTYmx3k3oWp3bxR2mCdfztAcZzaxbUk8bLGf6xt6(qenE7ze2W1m7VN05JMFMw3)cf0Xd6NZKV9vALrABcEOl(p(qywtyIN8SjHfHFqHBOshOAEFcSuj4wWzGAWTl85LhA1h6Z)BfF9JWYn1wByLUEKycNjKQWxx7CH1A6mS6LNBpw87aofoxW95hc8GnGnJkujn9RuH9Os7BLr)xRCx4E5gq4N0MUh0SWXDZ367G7d)CHB8xob0WqXwA7dGuPpXtGBa1bFdOTIgAM7TEi)KVgl7HcTAX(nH8k)oqGW3kNhF)Y5ByHf6FVfjSv50zwGDJ9OCh1eIAcXdvbL3rZ9baU8w)1D)Np
```

**Comment by mrbuds** [comment]
On which boss / ability are you testing it on?

**Comment by GnomeTW** [comment]
(1) VOTI Raszageth Mythic
(2) all the ability, like 
hurricane_wing = "Pushback"
volatile_current = "Sparks"
lightning_breath = "Breath"
lightning_devastation = "Breath"
shattering_shroud = "Heal Absorb"
tempest_wing = "Storm Wave"
storm_break = "Teleport"
ball_lightning = "Balls"

-----
In the boss fights of VOTI M1-7, these WA issues did not occur. At least before 3/25, M1-7 did not have this issue, as I could see from the VOD that M1-7 was still working normally.

**Comment by ntowle** [comment]
This could be a zhTW and zhCN specific issue, as BigWigs uses `（` and `）` chars for those locales.

**Comment by GnomeTW** [comment]
I'm not sure if the issue is related to the difference between full-width and half-width symbols, because even when I modified the content of the common.zhTW.lua file in the BigWigs folder to change L.count to the same syntax as in common.enUS, I still couldn't retrieve the Count value from BigWigs in WA.

However, if I downgrade the WA version to 5.4.3 or 5.4.3-2, I can successfully obtain the Count value from BigWigs.

**Comment by InfusOnWoW** [comment]
From what we can tell this looks indeed like the mentioned localization issue, please try again with the latest alpha.

**Comment by GnomeTW** [comment]
> From what we can tell this looks indeed like the mentioned localization issue, please try again with the latest alpha.

Thank you. In WeakAuras-5.4.4-9 alpha version, the issue has indeed been fixed :D

**Comment by GnomeTW** [comment]
After updating to version WeakAuras-5.4.4-10, the issue still persists.

I have recorded a video showing the switching between two versions of WA for reference. 
The text in the video reads "TEST BAR [%count] - %p".

[https://youtu.be/sr0PbYw03Ag](url)

**Comment by InfusOnWoW** [comment]
I just tested this with the TW localization of BW, and it works correctly. 

Do note that WA 5.4.3 did not require the ( or （ arond the numbers, but 5.4.5 will. It appears that for some reason you do not have paranthesis on your BW bars, which indicates that the problem is there.

https://user-images.githubusercontent.com/12950521/233840037-add08f62-97cb-4d50-8e39-8149fe7552aa.mp4

**Comment by GnomeTW** [comment]
> I just tested this with the TW localization of BW, and it works correctly.
> 
> Do note that WA 5.4.3 did not require the ( or （ arond the numbers, but 5.4.5 will. It appears that for some reason you do not have paranthesis on your BW bars, which indicates that the problem is there.
> 
>  Wow_65R9R9XfqG.mp4

When I checked the common.zhTW.lua file in BigWigs and added back the parentheses in "L.count = "%s（%d）"", it did work properly in WeakAuras-5.4.4-10 version. Thank you for your assistance, once again, thank you.
