### ISSUE TITLE
LUA MoverSizer.lua"644

### ISSUE THREAD

**Issue by Mithras2801** [WeakAuras/WeakAuras2#4405]
### Description

7x WeakAurasOptions/OptionsFrames/MoverSizer.lua:644: attempt to perform arithmetic on local 'virX' (a nil value)
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:644: in function <WeakAurasOptions/OptionsFrames/MoverSizer.lua:641>
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:714: in function `CreateLineInformation'
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:847: in function `CreateLines'
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:1246: in function <WeakAurasOptions/OptionsFrames/MoverSizer.lua:1229>

Locals:
virX = nil
physicalWidth = 1920
physicalHeight = 1080
virtualWidth = 1964.791138
(*temporary) = 1964.791138
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'virX' (a nil value)"

### WeakAuras Version

5.4.4.-6-gacd04c2

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
7x WeakAurasOptions/OptionsFrames/MoverSizer.lua:644: attempt to perform arithmetic on local 'virX' (a nil value)
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:644: in function <WeakAurasOptions/OptionsFrames/MoverSizer.lua:641>
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:714: in function `CreateLineInformation'
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:847: in function `CreateLines'
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:1246: in function <WeakAurasOptions/OptionsFrames/MoverSizer.lua:1229>

Locals:
virX = nil
physicalWidth = 1920
physicalHeight = 1080
virtualWidth = 1964.791138
(*temporary) = 1964.791138
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'virX' (a nil value)"
```

### Reproduction Steps

1. Logon rogue
2. Use talents builds:
BQQAAWulQAmRd/c4Iy2r7VOUFAAAgERSAkkEJcgkAxBkEJSSkkECAAAAAAQ0C4AOQCIRKBAAAA

3. Attack enemy

**Comment by InfusOnWoW** [comment]
Fixed for the next release
