### ISSUE TITLE
Load aura when on continent

### ISSUE THREAD

**Issue by stornquist** [WeakAuras/WeakAuras2#4409]
**Is your feature request related to a problem? Please describe.**
Load auras based on continent

**Describe the solution you'd like**
Option in the "Load" tab to add a continent ID where an aura would be loaded.

**Describe alternatives you've considered**
Using wowhead to get the zone id for the zones in DF, but they are not the IDs which are used by the API

**Additional context**
from any mapId one can loop
```lua
local zoneId = C_Map.GetBestMapForUnit("player")
local mapInfo = C_Map.GetMapInfo(zoneId)
while (mapInfo.mapType < 2) do
  mapInfo = C_Map.GetMapInfo(mapInfo.parentMapId)
end
```
| mapType | Description |
|:-------:|-------------|
|    0    | Cosmic      |
|    1    | World       |
|    2    | Continent   |
|    3    | Zone        |
|    4    | Dungeon     |
|    5    | Micro       |
|    6    | Orphan      |

**Comment by InfusOnWoW** [comment]
Why?

**Comment by InfusOnWoW** [comment]
No reason given.

**Comment by stornquist** [comment]
Sorry for late answer, but the reason is stated in the original comment. To be able to load auras only when on certain continents. Prime example being the dragonflight helper which tracks rares and timers for the zones. Would be nice to tell it to just load while on the dragon isles.

**Comment by InfusOnWoW** [comment]
That's a bit to narrow of a use case.
