### ISSUE TITLE
"attempt to perform arithmetic on local 'currentValue' (a nil value)" in xpcall function of GenericTrigger.lua

### ISSUE THREAD

**Issue by rene-a-dippe** [WeakAuras/WeakAuras2#4411]
### Description

**Background**
I created a [DF reputation and renown overview aura group](https://wago.io/uJYumdJpX) containing three combined auras for each faction in DF (so a total of 33 auras for 11 factions, 12 auras throwing the error mentioned below)

I use a combination of a default Trigger1 and an additional simple TSU Trigger2 based on some CustomOptions.

Everything works fine, except for the four main factions IF (and only IF) the character logged in is already on maximum Renown and aiming for paragon chest.

**What I've expected**
Everything works quite fine

**What happened instead**
Each aura referenced to one of the four main factions throws an error everytime the aura is loaded while the faction in question is already on maximum renown.

### WeakAuras Version

5.4.4

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
3x Lua error in aura 'expedition_fill': Trigger 1
WeakAuras Version: 5.4.4
Aura Version: 2.6.1
[string ""]:43: attempt to perform arithmetic on local 'currentValue' (a nil value)
[string ""]:43: in function <[string ""]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:647: in function <WeakAuras/GenericTrigger.lua:563>
[string "@WeakAuras/GenericTrigger.lua"]:948: in function `ScanWithFakeEvent'
[string "@WeakAuras/GenericTrigger.lua"]:1291: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1890: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1674: in function <WeakAuras/WeakAuras.lua:1524>
[string "@WeakAuras/WeakAuras.lua"]:1717: in function `ScanForLoads'
[string "@WeakAuras/WeakAuras.lua"]:1793: in function <WeakAuras/WeakAuras.lua:1789>
```

### Reproduction Steps

1. import the aura
2. get maximum renown on at least one of the four main factions
3. get the aura loaded

### Last Good Version

-

### Screenshots

**Trigger 1 which dynamic info is used**
![image](https://user-images.githubusercontent.com/23211089/234821395-83416ef3-860d-4d12-ad9b-a68afd5f08b8.png)

**Trigger 2 which only defines visibility based on some custom options**
![image](https://user-images.githubusercontent.com/23211089/234821562-65c1ce91-d52b-4fbc-a9cb-2214d2430ba6.png)

**Trigger 2 Custom Code (nothin very special here, just some display options)**
![image](https://user-images.githubusercontent.com/23211089/234821620-c24375ef-9b8d-43fd-87ab-c2fb94530822.png)

**Trigger Combination**
![image](https://user-images.githubusercontent.com/23211089/234821797-27e9dcb2-17c1-4fa1-b273-a7f47cdb2a92.png)
![image](https://user-images.githubusercontent.com/23211089/234821843-098a5de1-ce3b-441d-adae-4153757c0589.png)

### Export String

```true
!WA:2!TNvZUTrYryZiRyBg7yl61)7KmMXRGCSeTxTE1MyKGfKuu20H6NDOwlly7q2Zmn50RgoDNUNrIYb5cdqWcS34LCjih0LCNiibih9tqdJ8aK1h2ha9eKQ7zi5qBjzPGeKdX6GupvxD1Fv1Fv1)OulKPvgNmoF1pZkuG512ov0FBN6vOWaxkFzwaH6l(7F7oIqR4pUFJcbBZWwb0Mn9WCyaZJf2UZUbE7ccx6wf8rTWSZxfAASaYwngdtSpDlFUdUbk0lOU5weNa3X)w5X)jBkh3YpSLfMlpDk5jCLNKtB0qGdEImnF5Owfeby2kJD3CFI8mJbdq(9LNEIK6U(aDxxorFfLJB2KtdzGI7OGuvAi3gNsM2Sihlcan6byVi1ZdXe46CF6IyEtmyvtBLcDSJ7YTRhPfjyvWPl4t9XD1Mv9PLG0I5H75sCWMyk4F86feKxGVqSRPqAKxjpRmT8Ca6o(DZn7q)a660prd4tkZaAC(eAak8bkfUqk5jl0G45PKDP6Yl7kt)Yv40MakfgfqC5pQU8AYRl)bYFO8QUsJlKyKP3PuBg2HOwggo(tUdEO0RoC0GHmuy)(nat8DbmDkncRdi77jpZ47VxnYIJAitKWHgSGm0FKxjHZiV4B5bdNjLXsTVXV4GNglhq8lTmBcNxEd1KmIpNeBalXpafYtGqRfr8WWngbMJgQ0i4u64eeUsgQEhoWehcWFXKG)kVf4pcllVjxBVwAUrYLMShi5IxwSbcXrjWhpieKX5VNw9g0QD2e55WrBSborIy6DE8qP7b76r7j7AS44yhOknvv8PF4KDP8GKzEiiYak7AtvLNIt93FFFVQSEar5JcF8jrrT3rfWvo(CkrhCjWJcVSZACuG7OL86SvFz7bZ8r7jZCSer)BdIMok6))k(ACWCFjTXHX)JYA7kqwyppckjPTB1bcpYCwiq2pcp9)NXk3Ti1c5fyKxiWTS82obETS1D9EQ5rGA2XMJAeG5IeaLLjppGiqQAF(ck0oS175OhboklZAeFiOYWarDHqUf1RzYIOnIejEpt9OS1VdIVraYdOKj5QNFEqSXQA5gt9q19hU17jRhfY61wgUcMdSpKXAi1TVGWyE9(s2qKCi43LgR2wrA9wK3EiNVmeULPZIe)zN5tUlF7ORtMQhyk4EWRqHKcRILwA1sMSpWblqbHWPjWfq2BOUnOVt9DcO2Bc2goGXLt97)Z9eWvoxf3g0dxF2qUh7AUbbmX9VZD2c1KMJqVt4JwpSLZJyp5oFAsBUaLJJSPBNaoPztWO)Pj5Xn)QmVgU1AnKfuCZArQdU(RHRMJ3eUYYkCCdsBZQRuQsfTsIaKVdXVzzh3DCWwHnAOU0k)HLQSYcFrf54fc9jbSmdT3dXiVrTzvyqK29QvmF1vRvD18MRkxYI5H2gZn1kWYm8o(SWaKQz3grIkp)F5p(6gCc23r4syMi)nYmNP6U4I0DeqfgVYoI0rayu1CFLwwFZuNDHr1zruBTASln64Qrb)dfq5z(5DuJq5G17g6hh8spP8bQhCWgwRPTI8qb7hVsL8RxYSwLLFq5LM2i(l9AD5LEqT1w2SY89Igsn1lF0dIRb4qMd8BtBxS9gYQYkYfL1A)D(dnc91GEkKNNwpX0g65zAJC5YDR0ggEuBKNbC)sKXVq)NAy)nhip2NHUeaO9BMRjSumLsTCeNPnYw7d3623ml0iRYwdggqzIgLwZOVg0jdXbaaDUggTrEqbrUhGdm1knv8eMlxwi(cln9T7mZagfsbmyuH(Dcazr29(f9WioKNPZketDRH9ufhOfov2OCfaOrtoa4bs0qe2EUbP5tJN9NNt9(g5IF5N3TkRhdYbb5NMn7Zbh83aYmmuVcv)qXBAevFtR1Y2f53e7akgWdXrYyXVQIkpb6iRY4e7SrDc3Fluj1N4fjiGc10tkWrLahTomqgUnJejDvsRrgU6YB6BQLebQSJKkrSh1CaIS3qmIg(o42df8BJImCmunXxB40qcICjPP8xLUNdr8LAg6MyznwMiw9QrzhvOnj2mVbm4G)lWw7dRNo7ZvWInbsJLyeOQ9mwhqEE)MEyNtTR(Oi(iVhhvy931f5tAPdMZzcrcEWJHSzMMN2bJey16M86VQ)6GoDLlWqm0r8sLcvda2yZa3ti97i8GGFaLvOfI4VaSVY1L8tizYFTKkVUvdIpr4c2x6R(wlh62xkSufWlpF3b1V5rrbXCYwt21HwlkQ6c1dsLAVJFhqs7HiLvR(EK3ME)Ypt)VB6zYz6GYr3x9w)wfG4yWKYTHWb7N2paKB)jo6UFtYJmmTLnNYQ1wDMH79rD40OTAsvObf2e6ClWjVW4ZdroWcpYy1v5XBfFw1dxhf2ex9IYXFf8P1GnTTCXKMUbFZUdfvK6r5p6HF2)8CNZ4yh7yVDJuraz7iGuWJIC2uVxJ6DFH9AGw(qbFURfuCacTx0SvOxajT6XMR9cQpg2ZZ102djexu(1Pla7dARAinMeoKII3dKTVon7CG(5JpvcCUeuB3DdIooXACetLPywSs(fxb24w9U2wKwm46o7OZk0Pp38m82XNIXkAz6Vk)W5KNQU8ktkpBkzMjK3iQr0JDn3cJ03TRR7o(KDzIp729pmkn1bmlF8HXa5omkDZdywUZHXaF6HrPzpmkDR9hkVw0IsdC7)C91FZ1vIV7orzNQAx72FdO4L6ok2DvGyDLUwazYrVSxOsPLMF3OdMUGk1x)VIOArZsLwQNUwauLdsdgRRWd5hOgJv5LQwE(sSjgs0JpBkBUYQASq(i(z5DCG0KNnOKZZwHUfMRBUigo(8ZIKQ(9hB1IW5uU7UngCC1OuNXGF6kWEn0vAKFMLa3cshmNn3C5(OoQxKu5FUzjo7o8)brnvjJzdjo926l(8YfQm3unkN3e5XCrJjpZFJnXWzPpUVCizMHgygxmcozVYmVuvfXSF9bO4IQua2ThvDsX4dOwSYYf)LRvUAPDuBnOTGiDpIpmnrBVmzpOPnUK(eI1zxM00hqq8)bmT0sk3xTEomKgLTnEgH5NK7E5UxMn)hp5F9d
```

**Comment by InfusOnWoW** [comment]
Please create aminimal example that doesn't use custom code, that reproduces the problem.

**Comment by rene-a-dippe** [comment]
I already did, the trigger causing the error is the default Faction reputation trigger (Trigger 1), not the TSU trigger (Trigger 2)

**Comment by InfusOnWoW** [comment]
Try deleting all custom code, so that the aura is **minimal**.

**Comment by rene-a-dippe** [comment]
I created a second aura with not a single line of custom code:

`!WA:2!DrvWUTTrq0k4cua62IebdJ0EYi11T9qmstv8TEGuIcrnYYkuSY5GbKwQDO4wtT7IDx6iLJQff9So3t6sV0tc9liOFaecf9diFc6lOZskBvyDGAxoVzN38M3YknRoPkTk93EwuMgudMvP8)PvutViowdMkQzBxSjwOGXkrgNwxKku)WE4p5buqtmzkIb8iJUUm(WvAYeieMIbGH)FmnV7msMBuSXJbL(tprTD5)6zMjbVmoZiRIezajslurVaiPNlOWW3RZIGBaUPxwCmB6Qb1D7foOxOBq473bVaAqboz1MKrgMGFuaiZme7Y8posMsMbQ12uIlJ3QXW5AjKM2IQDc4i71oZTXTCzxD7QaSUb9663U9I7s9V(9LuicPuiYE1l8B3T5p2ErgFBx5iFOf5nqy5El)(ZpyoWPU8XPWVC4gg3akojTpQg4j(ZliC2KcYEwG2quMMVdiAONrb8XMKpkFFpUGdRPwnfrnWkBknmsWP65wOwMKFS3ecJ3m)lWeYpo)lZpj)RYpokMXz6K7)6LgXOBkR)JQ8R)XCLOuUQ4flqH8bnvS3E0RYiuSKKJcdxIAsamgrO)8dZ3FnUn6odqucWgNy(7pXlvqO9lusn7TWWidjf1XddMKLAyobJsjA9H51C8q1Fu5ce3jrAMvBq6vZr(amDx6pLPnafONtMMSXu6TUurKw5uEq92UN3n8cV2U1FPBJgTcB13FHgsJ7kq1nQUFNq)a5d35H36oLpkJ9eyQeOmB3(KeGqbvmlnDzHYxmIQS0QSfa0ortykLqLCFAX4jlvfcIv83ivIXkqR3Y0OrkHCWSUF4tpT23UicfbQL4bET970qv6K0NL)yN8VXXdhqg01StpVLSN1Y6uqJhCLlLIzC1La5Ax0gOVQR4nGQy55yZqUQ8T2NF3cDkHBS1lQvNETA4)SmgD1R6FD0RR)195tjRjzMeH6czzlUHWhHBBQS3IXMjQx9aF)obKuzczV5wdrpCk9zZhjMiTnzYJzu5btywBB6T3PgyaTzv5rvmfY)(vX2Je9XOhAVG3WOMe6(B21NLFyP7Ep90NFVhVJGnsWTEsfJB9QqseoyIzJDwjum0xveDTBNWw1BFr9xEzRE(Lc)0sHFfJJoGYRwOVAxH3(nUQ6GNFATtRv9M)51)3d`

```
1x Lua error in aura 'minimal_faction_test': Auslöser 1
WeakAuras Version: 5.4.4
[string ""]:43: attempt to perform arithmetic on local 'currentValue' (a nil value)
[string ""]:43: in function <[string ""]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:647: in function <WeakAuras/GenericTrigger.lua:563>
[string "@WeakAuras/GenericTrigger.lua"]:948: in function `ScanWithFakeEvent'
[string "@WeakAuras/GenericTrigger.lua"]:1291: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1890: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1674: in function <WeakAuras/WeakAuras.lua:1524>
[string "@WeakAuras/WeakAuras.lua"]:1717: in function `ScanForLoads'
[string "@WeakAuras/WeakAuras.lua"]:1793: in function <WeakAuras/WeakAuras.lua:1789>
```

**Comment by rene-a-dippe** [comment]
Sure, I have this issue on several characters in the meanwhile.

```
[12:07:36] Dump: value=C_Reputation.GetFactionParagonInfo(2507)
[12:07:36] [1]=25945,
[12:07:36] [2]=7500,
[12:07:36] [3]=66156,
[12:07:36] [4]=false,
[12:07:36] [5]=false
```
this is from my main character "Tiripserutan-Die Aldor" do you need additional info from another character?

**Comment by InfusOnWoW** [comment]
If that's the return values, there should not be an error. 

I have found https://github.com/Stanzilla/WoWUIBugs/issues/206, which indicates that the api might return incorrect values while in a loading screen. But that isn't sufficient for me to reproduce the problem.

We need to have clear instructions on how to reproduce the problem.

What exactly were you doing when "Sure, I have this issue on several characters in the meanwhile.".
If it only happends occasionally, then just importing the aura is obviously not enough to reproduce, and you should figure out the exact steps to reproduce.

**Comment by rene-a-dippe** [comment]
"the api might return incorrect values while in a loading screen" this might be a hint at least

A secure way to reproduce the error is to
1. import the aura while Expedition is on maximum renown
2. enter a dungeon (doesn't matter which) > this will unload the aura because of the loading conditions
3. leave the dungeon > this will cause the aura to be loaded AND to throw the error

Other load screens like using a portal, hearthstone or something like that doesn't seem to cuase the error (at least not reliable for me) while entering and leaving a dungeon does so and highly reliable.
