### ISSUE TITLE
Option for remaining duration to appear as "max progress" on trigger

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#4413]
**Is your feature request related to a problem? Please describe.**
When using "<= remaining duration" and for example an icon type weakaura I would love there to be an option to make the swipe appear as full once the weakaura triggers. For bars we can probably work around it using max progress I guess

**Describe the solution you'd like**
either max progress for icon-type auras or a way to set remaining duration as max progress dynamically
(basically always set initial remaining duration as max progress).

**Describe alternatives you've considered**
I think there's some set duration code to do this

**Additional context**
![](https://i.gyazo.com/935889608c6c53747364e28aee2f4ae2.gif)

this is how it looks when total duration > remaining on trigger with remaining duration checked. hate the look of it.

I would even go as far and say that everyone would prefer this over default look

**Comment by InfusOnWoW** [comment]
The eternally work on progress branch for progress changes does include a max progress setting for icons, so yeah that will come this decade.

**Comment by InfusOnWoW** [comment]
The progress refactor branch that was merged does include a max progress setting for icons, though I decided against having an automatic max progress setting for triggers, after considering it for a bit.
