### ISSUE TITLE
WeakAura addon not working

### ISSUE THREAD

**Issue by Auditor69** [WeakAuras/WeakAuras2#4417]
### Description

After last update 5.5.0 version, addon will not load and after trying to open main window I get this error:
Message: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

Time: Tue May  2 17:53:05 2023
Count: 1
Stack: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1277: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1228>

Locals: <none>

### WeakAuras Version

Weak Auras 5.5.0

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Lua Error

```true
Message: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

Time: Tue May  2 17:53:05 2023
Count: 1
Stack: Interface/AddOns/WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@Interface/AddOns/WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@Interface/AddOns/WeakAuras/Prototypes.lua"]:1278: in function `enableTest'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:681: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:607>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2966: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2876>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:3044: in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:2502: in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1154: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1125>

[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1277: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1228>

Locals: <none>
```

### Reproduction Steps

1. Load Game
2. Type /wa
3. Nothing happens
4. Lua error

**Comment by Stanzilla** [comment]
5.5.0 is for Patch 10.1.0, you need to downgrade if you are EU/TW

**Comment by wazerstar** [comment]
@Stanzilla this happens on latest version you just update via curseforge on WOTLK

**Comment by Auditor69** [comment]
I updated via curseforge
Please explain what I suppose to do

**Comment by Auditor69** [comment]
I am EU, please explain how to downgrade

**Comment by Stanzilla** [comment]
> I am EU, please explain how to downgrade

Go to the addon in the CF app, select the versions tab and install the previous release

**Comment by Stanzilla** [comment]
> @Stanzilla this happens on latest version you just update via curseforge on WOTLK
> 
> Go to the load tab and it will start spamming, and make weakaura useless until you restart the game.
> 
> [i.imgur.com/PQHAN8L.png](https://i.imgur.com/PQHAN8L.png)

Sounds like an issue with your aura, which one is it?

**Comment by Auditor69** [comment]
Thank you so much! Problem solved

**Comment by CLKRUN** [comment]
Also 5.5.1 appear ingame as out of date addon. 5.4.4 not
BR

**Comment by Stanzilla** [comment]
> 

Cannot reproduce
