### ISSUE TITLE
The last maj 10.1 does not work on European client

### ISSUE THREAD

**Issue by Seb-Dupuis** [WeakAuras/WeakAuras2#4423]
### Description

WAs are not available in games and the /wa command does not work either.

### WeakAuras Version

5.5.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [X] Yes
- [ ] No

### Reproduction Steps

Installing wa with a UE client and launching the game

### Last Good Version

5.5.0

**Comment by Stanzilla** [comment]
Duplicate of https://github.com/WeakAuras/WeakAuras2/issues/4417
