### ISSUE TITLE
Weak auras crashing 

### ISSUE THREAD

**Issue by Nanousis** [WeakAuras/WeakAuras2#4427]
### Description

My weak auras doesn't show up.  

### WeakAuras Version

Weakauras 5.5.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [ ] No

### Lua Error

```true
4x WeakAuras/Types_Retail.lua:181: attempt to call field 'InitializeViewLoadout' (a nil value)
[string "@WeakAuras/Types_Retail.lua"]:181: in function `GetTalentData'
[string "@WeakAuras/Prototypes.lua"]:756: in function <WeakAuras/Prototypes.lua:751>

Locals:
specId = 256
specData = <table> {
}
(*temporary) = nil
(*temporary) = 256
(*temporary) = 70
(*temporary) = "attempt to call field 'InitializeViewLoadout' (a nil value)"
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras/WeakAuras.lua:3493
 frame_strata_types = <table> {
 }
```

### Reproduction Steps

I think the weak aura got bugged by the talent tree addon and vuihdo both trying to use it's api and not having macro slots available (for vuhdo). Disabling them doesnt change the problem. 

### Screenshots

![image](https://user-images.githubusercontent.com/11467288/235759346-b7bc1411-c4a8-4cca-ba9c-dbb60a844d3c.png)

**Comment by Stanzilla** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/4417
