### ISSUE TITLE
LUA Error when entering combat

### ISSUE THREAD

**Issue by isarantoglou** [WeakAuras/WeakAuras2#4439]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have enabled only Weakauras addon, Bugshack and buggrabber. When entering combat I get the following error. If I disable WA addon there is no error at all.

### WeakAuras Version

5.5.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
8x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Frame:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1474: in function `Resize'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1444: in function `DoPositionChildren'
[string "@WeakAuras/Animations.lua"]:22: in function <WeakAuras/Animations.lua:17>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}
```

### Reproduction Steps

Enter combat with a mob and the error pops up.

**Comment by InfusOnWoW** [comment]
You most likely have an aura installed that is creating secure frames, there should be a warning icon in the settings and maybe a printed message in the chat. These auras fundamentally can't work inside dynamic groups.
