### ISSUE TITLE
GetAddOnMetadata error on login

### ISSUE THREAD

**Issue by netnusa** [WeakAuras/WeakAuras2#4441]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

will receive lua errors until I manually update GetAddOnMetaData in Init.lua to the current 10.1 version of C_AddOns.GetAddOnMetadata

### WeakAuras Version

WeakAuras 5.5.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
6x WeakAuras/Init.lua:299: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@WeakAuras/Init.lua"]:299: in main chunk

Locals:
AddonName = "WeakAuras"
Private = <table> {
 Archivist = <table> {
 }
 frames = <table> {
 }
}
(*temporary) = nil
(*temporary) = "WeakAuras"
(*temporary) = "Version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
```

### Reproduction Steps

I get it every login since 10.1 and Weakauras doesn't function.  The only way to avoid this is to either disable WA or manually edit the Init.lua.

**Comment by mrbuds** [comment]
Can you try running these commands in chat?

```
/run LoadAddOn("Blizzard_Deprecated ")
/reload
```

**Comment by InfusOnWoW** [comment]
We are pretty sure that's on your end. 
The Blizzard_Deprecated addon which can't be disabled provides that function, see:
https://github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_Deprecated/Deprecated_10_1_0.lua

**Comment by netnusa** [comment]
That did it! No idea how it was disabled since running /dump IsAddOnLoaded("Blizzard_Deprecated") prior to returned false.. Any thoughts?
