### ISSUE TITLE
Error 132 when loading weakauras from character select

### ISSUE THREAD

**Issue by antrjs** [WeakAuras/WeakAuras2#4442]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Getting an error 132 when loading WA add on 5.5.2 as of 10.1

What does not work: 
Select add on from character select, enter game. I get an Error 132 on loading screen and wow crashes.

What does work: 
Loading from character select without WA enabled, when in game activate WA and /reload.

What was tried: Scan and repair. Delete WTF, Interface, Cache. Fresh install of WA. Deleted all WA imports.

### WeakAuras Version

WeakAuras 5.5.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

At character select screen enable WA add on.
Enter game.
Game crashes with error 132.

When loading from character screen  without WA enabled it works. 
When enabling WA add on ingame and /reload it works.

Deleted WTF, interface, Cache. Scan and repair from launcher.

**Comment by InfusOnWoW** [comment]
Game crashes are WoW bugs, not addon bugs. You'll have to contact to review the list here: https://eu.battle.net/support/en/article/8288 and/or contact Blizzard support.

In any case there have been no reports of anything similar.
