### ISSUE TITLE
Load > Class and Specialization > Talent Artwork not displayed correctly

### ISSUE THREAD

**Issue by plopek** [WeakAuras/WeakAuras2#4444]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I wanted to use Hpal talent "Maraad's Dying Breath" as a load function.
As mentioned in the tittle artwork is clipping into scrollbar hence cannot use talent. 
Resizing WA window has no effect.

### WeakAuras Version

5.5.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Holy Paladin
Load > Class and Specialization > Talent Artwork
Untampered Dedication, Maraad's Dying Breath 

### Screenshots

![image](https://user-images.githubusercontent.com/21142557/236677332-05c646aa-d04d-4b7e-8000-9bc0a800d75e.png)

### Export String

```Text
!WA:2!1vvqVTrru4AsbQmsrTgAuOcHwQGs7LQsGweHdOSPRPPYn2z9wAHd4D2DE7UdD9mtNz244Ed3d0Z(a)amx7P8tihqCGdRSq8dO)eYVaEZU2PTOgFy9mV3BEVV338EVPr7wdBrBrF2vNXIf8(Icvm8rNjAejvSZTNMQ6X25UJ2lwDq3KenyEEZzXfAJyyaCG5TuJRL(3N7qcpotO6jyCt02E7g45ppwiYPIr8(Jysi8OLB9OPqMRnAHtmkwAkO0REf1IL)PRzSe8jfkYghz)QLqEoJQVu0x(1FZn(QVWh2hWyChGKBY85KHGUPBbNzIK5KXG64cn4Daj203EWDOzt01l0nFHUiQ609uqc7a)(98605eH9lsqHhoy7T6hmOFWw(btTXVkcxsEX7ruec9Z1o3EmJN64QaIjtHbBx0GWzuicpFaID1D860R997mTGViNAkVaIh2(qq9(7jOWZpZXivbkoj)hqcGj4p94hbGCleTXgFIHjYMQH8KkkT8Cya0edIhdKndHSpKINrV5ALRoh3grIFuQsuWP)780CXO2k4XfapECVZEJRVXnlxvHgzvCeI4Vh)FBrUqLnXkYc65rfgJG3DFqHS4mR4oap1KDXdTR)X675gttxE07Uc(Rs3dFvD9Jj5WkvqiiJf)ioO1R4A3MvPVddLCHk)7kuuqL9SljBzWIPb6mc9LEt(HvcR(KiudjOblw4YfCy6jQV8NPFdglxSW3Wgc0xuhHL0P7w3pOR89ReskWQzKUJFaJAYC3c3ECTJyha0kH)Q8tFd(364b5qkjE8GKCbYMhvzWVG9hSKX4vMsyWRlBNI7UD31tE(xjpRjXgnASs9DJv186MOLuWSkZJpHTNUi(CJ88TvSN4SxbHIfeeNGa5NCAiuQGyMT(ALxJNxEJwJ59rlIYHW5v7gH3mpqrKtEWIfZpjYvf4DVFqNDojFELo)POgp)bbD7j)4tdp17AiDondgkOdSL5HVmQ9zpb(w51oTtqhJnPS4by)iOZWPmJxWKltYOmGLMz2ZnxqO)UYG1OCZgR5pSi3WAofBjgWXzaQWOAvRv(Zxz9357iHR)2)1Fe6hNt0AuwZzwlRnjZ12OAfkBzLwzdYf0bw5HV413VwKghAKdp1vJPI9ur6QrTrSHsHYmtv1oBz3Y3ZfB1JLtUntBNOPDuWqcJBh6et0gTJiXPFgdYP2vMmWX3MCGOq7ebiZao22lR9gHdJtzXiB6KOaWXEHApfobqn2HPDKcD1nVZvrxwfJowN5yhMDTdz8AIgH2voexgdE2jL6q56SuogPUsRoDLupLsO0HtjCw9rULV2quM2hben03OQMN8ULRwU5CQDqgAYa7WELgWhdO6jw7QOGnDTzC7svL1L6stzr5Mrjic1z)FXZXoy8UEbuA6)YgMnky0d96gDl1p9q2ESRDyIcNvJib7zwr(blFqY2GIKnbPbA2X1voTTwAXsu)T9982DMreVF9C61B8BN9YmAu9dc(KCzg6nBrW2lCioF33wa7pYo9ypBvtaQYWKHryMMWsBQyCR7WhcFIqmSHY((aI(Bv(4MLJA6IjQbFPfzfwDwnzjydBP9V51V513O1()Zd)V)
```

**Comment by InfusOnWoW** [comment]
I cannot reproduce that. Are you sure you disabled all other addons? The last time a similar issue was due to a elvui plugin.

**Comment by plopek** [comment]
yep, I left only WA enabled
![image](https://user-images.githubusercontent.com/21142557/236687228-a32901bc-c3a6-4b71-b2f9-6eae7e500bd6.png)

**Comment by InfusOnWoW** [comment]
The font in your first screenshot is not the right font for an unmodified WA. Can you try reproducing the bug without any auras installed? (By e.g. removing the WeakAuras.lua file from the _retail_\WTF\Account\#account\SavedVariables folder? (Obviously make a backup first)

**Comment by SpatenLa** [comment]
![grafik](https://user-images.githubusercontent.com/39881841/236688065-45232f48-653b-42a9-a63f-87df9147fa86.png)
i can confirm the issue. its about the 2 talents on the far right

**Comment by plopek** [comment]
> 

I removed my custom Font as well as Weakauras.lua from WTF. Still the same issue.
![image](https://user-images.githubusercontent.com/21142557/236691769-088911bc-74f7-43a2-9a82-c6c4563e6cba.png)
