### ISSUE TITLE
Player/Unit info -> Cast -> Spell 

### ISSUE THREAD

**Issue by efrain18r** [WeakAuras/WeakAuras2#4445]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When using the trigger (Player/Unit info -> Cast -> Spell ) when 'inverse' is checked the spell name/id is removed from the trigger.
it'll be nice if we cant track whenever a spell is not being casted:

Example: If I need to cast smite, only show if smite is not already being casted.

### WeakAuras Version

5.4.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1-New aura
2-Trigger
3-Player/ Unit info
4-Cast
5-Spell (name/id)
6-inverse

**Comment by InfusOnWoW** [comment]
Due to how the trigger operates that would not be an easy addition.

**Comment by efrain18r** [comment]
Totally understood. I was able to dig into the documentation and use custom trigger functions to archive the same result. Thanks
