### ISSUE TITLE
[Feature request] Make it so that so you can copy paste spells with brackets.

### ISSUE THREAD

**Issue by Mcprepped** [WeakAuras/WeakAuras2#4448]
When I make auras I usually copy paste the spells from the spellbook. But when you link something in the chat it comes with brackets (IE:  [Shield of Vengeance]) so every time I do that I have to manually remove the brackets for WA to recognize the spell.

![xBrJ6hl](https://user-images.githubusercontent.com/72827845/236689325-763682c6-c20d-45ff-8d42-3950e70e7f3e.png)

**Comment by InfusOnWoW** [comment]
You can drag and drop spells from the spellbook into the text box.
