### ISSUE TITLE
Lua errors on Weekly: HDH

### ISSUE THREAD

**Issue by Warhage** [WeakAuras/WeakAuras2#4451]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

184x Lua error in aura 'Weekly Quests (HDH)': Trigger 1
WeakAuras Version: 5.5.3
Aura Version: 2.2.28
[string "return function(allstates)"]:65: attempt to concatenate a nil value
[string "return function(allstates)"]:65: in function <[string "return function(allstates)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:578: in function <WeakAuras/GenericTrigger.lua:563>
[string "@WeakAuras/GenericTrigger.lua"]:911: in function `CreateFakeStates'
[string "@WeakAuras/WeakAuras.lua"]:4221: in function `UpdateFakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:4197: in function `FakeStatesFor'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1445: in function `SyncVisibility'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1471: in function `PriorityShow'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1305: in function `PickDisplay'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:1188: in function `PickDisplay'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:567: in function `f'
[string "@WeakAuras/WeakAuras.lua"]:56: in function `Fire'
[string "@WeakAuras/WeakAuras.lua"]:2153: in function `Rename'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1760: in function `RenameAuras'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1679: in function `ImportImpl'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1520: in function <...aceWeakAurasOptions/OptionsFrames/Update.lua:1519>

Locals:
allstates = <table> {
}
cfg = <table> {
 zaralekEvents = true
 lifeSpark = false
 siegeKeep = true
 catchRelease = false
 trialFlood = false
 revivalCatalyst = true
 weeklyEnable = true
 crCount = true
 worldBoss = true
 trialElements = false
 primalStorms = true
 keyLoyalty = true
 commFeast = true
 hideComplete = true
 grandHunt = true
 aidAccord = true
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 zaralekEvents = <table> {
 }
 grandHunt = <table> {
 }
 trialFlood = <table> {
 }
 revivalCatalyst = <table> {
 }
 worldBoss = <table> {
 }
 trialElements = <table> {
 }
 primalStorms = <table> {
 }
 keyLoyalty = <table> {
 }
 commFeast = <table> {
 }
 lifeSpark = <table> {
 }
 siegeKeep = <table> {
 }
 aidAccord = <table> {
 }
}
(for control) = "zaralekEvents"
event = "zaralekEvents"
v = <table> {
 questInfo = <table> {
 }
 questID = <table> {
 }
 name = <table> {
 }
 questReq = 18
}
lang = "enUS"
name = "Zaralek Events"
questDB = <table> {
 1 = 74352
 2 = 75156
 3 = 75222
 4 = 75370
 5 = 75441
 6 = 75450
 7 = 75451
 8 = 75454
 9 = 75455
 10 = 75461
 11 = 75471
 12 = 75478
 13 = 75494
 14 = 75611
 15 = 75612
 16 = 75624
 17 = 75664
 18 = 75705
}
required = 18
info = "4/18|r"
tooltip = "Incomplete Events: |n|n|cFFFFFFFFWhirling Zephyr|nStress Express|nShellfire|nSmellincense|nImperfect Balance|n"
completed = 4
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 74352
 2 = 75156
 3 = 75222
 4 = 75370
 5 = 75441
 6 = 75450
 7 = 75451
 8 = 75454
 9 = 75455
 10 = 75461
 11 = 75471
 12 = 75478
 13 = 75494
 14 = 75611
 15 = 75612
 16 = 75624
 17 = 75664
 18 = 75705
}
(for control) = 10
_ = 10
questID = 75461
questComplete = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 75455 = true
 75612 = true
 75461 = true
 75370 = true
 75624 = true
 75471 = true
 75450 = true
 75454 = true
 75611 = true
 75156 = true
 74352 = true
 75222 = true
 75441 = true
 75478 = true
 75705 = true
 75451 = true
 75664 = true
 75494 = true
}
(for control) = 75461
infoID = 75461
x = true
c = ""
out = "4/18"
(*temporary) = "Incomplete Events: |n|n|cFFFFFFFFWhirling Zephyr|nStress Express|nShellfire|nSmellincense|nImperfect Balance|n"
(*temporary) = nil
(*temporary) = "|n"
(*temporary) = 75461
(*temporary) = nil
(*temporary) = "attempt to concatenate a nil value"

### WeakAuras Version

WeakAuras 5.5.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
184x Lua error in aura 'Weekly Quests (HDH)': Trigger 1
WeakAuras Version: 5.5.3
Aura Version: 2.2.28
[string "return function(allstates)"]:65: attempt to concatenate a nil value
[string "return function(allstates)"]:65: in function <[string "return function(allstates)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:578: in function <WeakAuras/GenericTrigger.lua:563>
[string "@WeakAuras/GenericTrigger.lua"]:911: in function `CreateFakeStates'
[string "@WeakAuras/WeakAuras.lua"]:4221: in function `UpdateFakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:4197: in function `FakeStatesFor'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1445: in function `SyncVisibility'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1471: in function `PriorityShow'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1305: in function `PickDisplay'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:1188: in function `PickDisplay'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:567: in function `f'
[string "@WeakAuras/WeakAuras.lua"]:56: in function `Fire'
[string "@WeakAuras/WeakAuras.lua"]:2153: in function `Rename'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1760: in function `RenameAuras'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1679: in function `ImportImpl'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1520: in function <...aceWeakAurasOptions/OptionsFrames/Update.lua:1519>

Locals:
allstates = <table> {
}
cfg = <table> {
 zaralekEvents = true
 lifeSpark = false
 siegeKeep = true
 catchRelease = false
 trialFlood = false
 revivalCatalyst = true
 weeklyEnable = true
 crCount = true
 worldBoss = true
 trialElements = false
 primalStorms = true
 keyLoyalty = true
 commFeast = true
 hideComplete = true
 grandHunt = true
 aidAccord = true
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 zaralekEvents = <table> {
 }
 grandHunt = <table> {
 }
 trialFlood = <table> {
 }
 revivalCatalyst = <table> {
 }
 worldBoss = <table> {
 }
 trialElements = <table> {
 }
 primalStorms = <table> {
 }
 keyLoyalty = <table> {
 }
 commFeast = <table> {
 }
 lifeSpark = <table> {
 }
 siegeKeep = <table> {
 }
 aidAccord = <table> {
 }
}
(for control) = "zaralekEvents"
event = "zaralekEvents"
v = <table> {
 questInfo = <table> {
 }
 questID = <table> {
 }
 name = <table> {
 }
 questReq = 18
}
lang = "enUS"
name = "Zaralek Events"
questDB = <table> {
 1 = 74352
 2 = 75156
 3 = 75222
 4 = 75370
 5 = 75441
 6 = 75450
 7 = 75451
 8 = 75454
 9 = 75455
 10 = 75461
 11 = 75471
 12 = 75478
 13 = 75494
 14 = 75611
 15 = 75612
 16 = 75624
 17 = 75664
 18 = 75705
}
required = 18
info = "4/18|r"
tooltip = "Incomplete Events: |n|n|cFFFFFFFFWhirling Zephyr|nStress Express|nShellfire|nSmellincense|nImperfect Balance|n"
completed = 4
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 74352
 2 = 75156
 3 = 75222
 4 = 75370
 5 = 75441
 6 = 75450
 7 = 75451
 8 = 75454
 9 = 75455
 10 = 75461
 11 = 75471
 12 = 75478
 13 = 75494
 14 = 75611
 15 = 75612
 16 = 75624
 17 = 75664
 18 = 75705
}
(for control) = 10
_ = 10
questID = 75461
questComplete = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 75455 = true
 75612 = true
 75461 = true
 75370 = true
 75624 = true
 75471 = true
 75450 = true
 75454 = true
 75611 = true
 75156 = true
 74352 = true
 75222 = true
 75441 = true
 75478 = true
 75705 = true
 75451 = true
 75664 = true
 75494 = true
}
(for control) = 75461
infoID = 75461
x = true
c = ""
out = "4/18"
(*temporary) = "Incomplete Events: |n|n|cFFFFFFFFWhirling Zephyr|nStress Express|nShellfire|nSmellincense|nImperfect Balance|n"
(*temporary) = nil
(*temporary) = "|n"
(*temporary) = 75461
(*temporary) = nil
(*temporary) = "attempt to concatenate a nil value"
```

### Reproduction Steps

1.Just log in. WA is constantly in view and generating errors

**Comment by Stanzilla** [comment]
The error is in your aura 'Weekly Quests (HDH)': Trigger 1

**Comment by N6REJ** [comment]
I have the same basic error and have no such weekly quest aura
```
2x Lua error in aura 'Keystones (HDH)': Trigger 1
WeakAuras Version: 5.10.1
Aura Version: 2.4.27
[string "return function(allstates, event, ...)"]:36: attempt to index local 'db' (a nil value)
[string "return function(allstates, event, ...)"]:36: in function <[string "return function(allstates, event, ...)"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:640: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:865: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:819: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1072: in function <WeakAuras/GenericTrigger.lua:1057>

Locals:
allstates = <table> {
}
event = "CHAT_MSG_ADDON"
cfg = <table> {
 party = true
 ownKey = true
 raid = false
 mplusEnable = true
 guild = false
}
db = nil
LRS = <table> {
 GetUnitInfo = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1263
 RequestKeystoneDataFromRaid = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:2578
 GetFlaskInfoBySpellId = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:403
 GetSpellFilters = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1984
 PrintTempCacheDebug = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:249
 GetUnitCooldowns = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1959
 TCopy = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:31
 __errors = <table> {
 }
 UnitIDCache = <table> {
 }
 CooldownManager = <table> {
 }
 RequestKeystoneDataFromParty = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:2567
 GetCooldownTimeFromCooldownInfo = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:2002
 commHandler = <table> {
 }
 IsInGroup = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:145
 IsCommAllowed = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:86
 __version = 126
 GetUnitID = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:173
 RequestAllPlayersInfo = <function> defined @Details/Libs/LibOpenRaid/Deprecated.lua:29
 DoesSpellPassFilters = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1980
 internalCallback = <table> {
 }
 UnitInfoManager = <table> {
 }
 GetBorrowedTalentVersion = <function> defined @Details/Libs/LibOpenRaid/GetPlayerInformation.lua:92
 DeprecatedMessage = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:196
 GetPlayerSpecId = <function> defined @Details/Libs/LibOpenRaid/GetPlayerInformation.lua:220
 diagnosticCommReceived = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:184
 specAttribute = <table> {
 }
 UpdateUnitIDCache = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:151
 GetAllUnitsGear = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1586
 GetAllKeystonesInfo = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:2546
 GetTalentVersion = <function> defined @Details/Libs/LibOpenRaid/GetPlayerInformation.lua:75
 GetFlaskTierFromAura = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:408
 GetCooldownStatusFromCooldownInfo = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:2070
 GetAllUnitsInfo = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1258
 sendRequestedAllInfoCooldown = 364157.247000
 GetFoodInfoBySpellId = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:425
 UnregisterCallback = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:781
 bHasEnteredWorld = true
 playerInfoManager = <table> {
 }
 KeystoneInfoManager = <table> {
 }
 cooldownManager = <table> {
 }
 isNearlyEqual = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:80
 GetRangePercent = <function> defined @Details/Libs/LibOpenRaid/Functions.lua:42
 GetUnitGear = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1590
 commPrefixDeprecated = <table> {
 }
 AuraTracker = <table> {
 }
 GetKeystoneInfo = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:2551
 GetAllUnitsCooldown = <function> defined @Details/Libs/LibOpenRaid/LibOpenRaid.lua:1953
 gearManager = <table> {
 }
 GearManager = <table> {
 }
 RequestAllData = <function> defined @Details/Libs/LibO
 ```

**Comment by InfusOnWoW** [comment]
the first line mentions the faulty aura: Keystones (HDH)

**Comment by N6REJ** [comment]
> the first line mentions the faulty aura: Keystones (HDH)

my apologies, it was buried deep in an aura pack. ty
