### ISSUE TITLE
Initialization issue with auras custom code.

### ISSUE THREAD

**Issue by cgsub** [WeakAuras/WeakAuras2#4456]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Sometime a custom code piece just doesn't seem to execute or to run in a messed up way.

The issue gets fixed by opening the custom trigger code in the editor by clicking the expand button. and then clicking done, I'm not sure if clicking cancel does the same.

It is a random behavior I am not sure how to reproduce it.

### WeakAuras Version

Weakauras 5.5.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

I have no idea.
It's randomly happening after a reload or changing character.

### Last Good Version

Weakaura 5.3.3 (not 100% sure, but I know it was not happening back in 1.0.7 I however did not install alpha versions)

**Comment by InfusOnWoW** [comment]
That's not enough information for a bug report.

**Comment by cgsub** [comment]
Then keep your bug buddy.
