### ISSUE TITLE
Elysian Decree not showing when talented into Precise Sigils

### ISSUE THREAD

**Issue by AceDCed** [WeakAuras/WeakAuras2#4457]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When I talent into Precise Sigils, my CD tracker for Elysian Decree disappears, and when I talent out of Precise Sigils, it shows up.

### WeakAuras Version

5.5.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Play Vengeance Demon Hunter
Talent Elysian Decree on the spec tree without Precise Sigils on the class tree
CD tracker shows up
Talent into Precise Sigils
CD tracker gone

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/110493916/a2780e85-95ae-42eb-b0d9-e4b42254c5bf)
![image](https://github.com/WeakAuras/WeakAuras2/assets/110493916/c7d05d61-2f4e-4b85-a094-d8dc72acd5cd)

### Export String

```Text
!WA:2!1v1tVTXTsClO40c5l2ojUjbpuOMMyK4xRB(dIV0)4Q1wk2UYskRwx7xUOLAxkTmEf5wsUYw5wup0CQPqnOxtHo3t6tqHr)aqiu0Zf(qb6PhGX7dWBi1UojT16WQHdhoZWFZm)yMsZ3zE)59F27pK4XO1zXCp8)AQXOyzaJxnssyuroEVQTAjWYmJqupqFngHkBUwXkofTh7XyH(SdO1pGeHDpkDzr)24alTtD7l5K2TXCrLf5jI)HLSxe2weHddpwe3e3ftL1JB1IC4OgRvOUtJ6ofSDg6JBckDaB5BuSCTs7uoAUybUrBmfZjE1dyhuL6ABoE0vwlj25RXzT5yHi)nRRJWTSIPezZOqupmFmhJcnQRG6GpUyypbbrZVo2JJXJ1oxKUPBFJ4M(ICJFJioua)vi8aupXPzFnogYE761kwUSnfoTi3aT3KCK3(Udo1Px(8N)phettaICJ8jIhht9KKU47IO9IMdzKDMS)2mF8pn1jaEJ5uu4xcOius(6t2hJJka(0tAJGIuWaeL0rlrxXwirCzPJWibUUKJPTLbVLAglkJIh7hZnw1qJ)CbgQp(I(At1GSAjRoicTK6wWbulP(3Qpq9HQLA2IqjIG)QAO6iqsTdXbdbyWg3w3U8OfuZmgw2eU3T5SyQFRrnzCFmVHG8eCw1md07A0CuYgESqgFRmzYK94enDjcsZqSB6rXq)e)o5RroehoorhBsx5ZUA07jXhkBy(0IXbGOrudjPdUreh7r0qw2OR83SrKiOwAWP7DTBefnRzLiabntR9QmBIwCylt)VvHDCQgDbJsyCHPrFVDj(YaRcWYtMeiiD9nkFA01pRCme3g51RrRqgJhCKXGhhlKKw9utpKZKa(6akTQuTsX)HBruIGT2z(Qz4a6Q3F8KH19sMDhAoZeGo7gR(FF5l)5PMAQnw9xEXl(XPMkt2bj(egKMTeN8K8pmg5d1wuEhNO5Fnej1HVHY)tIYjPFAXBSz1bq1AxokQ)UjcJpnuMj7Q74uEt4Qnb2Fnkg10rV7zbAtwLjk)zzqhMFdDRP7RIwDO97or36SoHFpySL41qgaChbavsMeim9Y9SlQQKr9XWeWNCTBiuFQPTq9zQvvFUQGY6PQhLrTUAAvrvjyozt1xSvw4NQSABv1mQhQSv1Cv7en3MvQu0UHvvhNQBBV5d2WrT3nuBLrvx58BJBhYoOeh)vXyQxVAN72lF37pPMQ3yK(tAbOVEHgbh3mwkz0QDXCGIBOwDzZy)Lm2NM(d0lM0pRZRJa2PhKQjWsVzGj6obeV9Pa9zwZjQ7HcXtelta1ZzcGLzemOzaM0oqITczi)F4yVqKqaLqFnjQ3InfeA7qSZ1T7ehkjl4CD3MsWBu5ck6cxE6)3fCTmgQ6mTIMBOHV0SFGH704o3(jKYEUrZFQ2tdIRTzn4IrRxC7Qv2yh9ZsG757wW2EZQ2qiG6(cA)ZnmugMU3(UXe)rvdJ2BLh(47WIVh)W0h5i0j9fGPlmce9Wf1e8cxUMAgy4wrDZCQpkNfWkkZz7DkIgDX0x)0ZRRteiyiW3DOK51DcX9LZ8nN7AeF17yFGMuaBUqPpBbC926g2tM01vIdVwOZ1M1xZUyXk2OWOau2MaLDls7CCcv7uGHSL2qGPhMvZA9egRtTS3E57nutTtm57slA7fG92Ff7UOWyC2(DrCIo3IUeHk0V66rGlOnwyE)xOYLL7fGOTXIRUO65BTXQ)(SZM3WwKiKnB)iodMDL9upDr13UcCe13nKrtVlQNNvnqFyx13RUD)uCbEhmL)un98c77V89x(EZ39x37))d
```

**Comment by InfusOnWoW** [comment]
That appears to be a game bug, which you can work around by disabling the "Spell Know" check in the Extra options.

**Comment by AceDCed** [comment]
> That appears to be a game bug, which you can work around by disabling the "Spell Know" check in the Extra options.

I see, ty for the info
