### ISSUE TITLE
Texture region:Color shades

### ISSUE THREAD

**Issue by airsmit** [WeakAuras/WeakAuras2#446]
Setting region:Color(125,125,125,1) will not apply a grey shade but instead converts it to white (255,255,255).  It looks like if assigning the r,g,b color in region:Color to anything other than 0 it will overwrite any values and set it to max (255).

For testing, I'm using a texture, square shape, blend mode set to Opaque, allow full rotation turned off.  Just using a simple Custom Trigger:
`function(t)
    aura_env.region:Color(125,125,125,1)
    return true
end`

**Comment by emptyrivers** [comment]
Color values are in a range from 0-1, since this is what blizzard expects. 125 gets clamped down to 1, so you get white.

**Comment by airsmit** [comment]
Thanks for the quick response...
