### ISSUE TITLE
Shadow Bulwark doesn't show when using Grimoire of Sacrifice 

### ISSUE THREAD

**Issue by phoenix7700** [WeakAuras/WeakAuras2#4460]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When using a Spell Cooldown Trigger for Spell="Shadow Bulwark" it tracks the spell while your voidwalker is active but then disappears shortly after you use Grimoire of Sacrifice and your voidwalker's body despawns. The spellID for command Demon while Shadow Bulwark is the active command changes from 119907 with the pet out to 132413 after using grimoire. The pet ability has the spellId 17767.

If you track the exact spellID 132413 it tracks the grimoire sac version but doesn't track the pet spell.

### WeakAuras Version

Weakauras 5.5.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1-Have Spell->Cooldown/Chages/Count->Spell="ShadowBulwark" trigger
2-Summon Void walker pet
3-Use Grimoire of sacrifice
4-Wait for voidwalker body to despawn about 3 seconds
5-Aura untriggers with Shadow Bulwark still learned in spell book

### Export String

```Text
!WA:2!DrvZUTXTt844ueadeaB1wxN0EWXhmA7)czh3AxGcy061woofk2k7Q0)jagql3LZUKvRi3sY1YYxkG6HMZc5jqx6LEsOOpa5jyHqq7D9iKxG0HusUFWlC4W5lo)g(BHJR0PcTc9f)VH8yPiqwOIHp6grDjPYhD0Gop7KID1KNY8JLzs13UiUu9oljrdMt(MW759JV9TVEereZKQgsUWeDyTtBwZFCSuMrLDfbD55qy(YXfAJStt4sZtZPedev42E1C7QrtbMIeB4sHEpFTHOmB6RLfcA(x)iHbujKy48dOu8(Z))aP9bfkI(8gYUGYj(yGYjNhy9qFodq)JaIPQmnTpv2YfjwucxW1SL8WnZs9nkEAkO0NUPAM4l(aFdwfT9ifgzFUb6CkPdSq(kfAOvkiafpoGj7EMiC8)64qnUDqwxspDFRTfyccZRyftKzzYUYlaLItb2qk(4tsA2lhuNuREJJFADpR1r5zKEGYZGx4RZHSSjwVjrAPk6Xskeorxebxacta6p)YrTo8GGMTcAEGFtvHWDt5Q(U987E4Sg76nuYufO1R)Xb2G(jVYg15VSW831EeUe78TCj1QLnwbKSG5hNeWiyOw3RaFFQ2JTECTTH9DIpIQxAW1kx7MVZ(9PiQyHZkp46cVHcWc3pOrT61hydJRzh6lqFq)leZGHvlVB59gr56VVqGJexa7qYYYxH4KBo1gBl5xVXB42zdbj77qCet2p9M2aKFawjXgFB6zd0qwIB2S82t0gEC7EhnRYyQlM61IdXk0hsTdFF6QL3FmEmcRSuLDS5pgNIa4Xk4hkarCVg3A7Q7SB59vOr2lSn0hI7hA)HW6Bvzb3XrfgJuCgMceyhAvxhePg27pYk)8PFIwyq6CxDFUC39S)5DbXKmyrxj0KHvVaXYf9ShzU7RZrnR4IVNurbflIb8uM5jEzsc93NeNr06web1cAXBgP5I0m4Ll73PiZW38Llh(BlhgzWSimRw6V6Al8l)zOVZl84sEA(vGvyY14EBboyXMKHyAwljohtms1g7VVNnbwtDyR7AMVBBJVC7H)TR2mOUskaCQ5M48TLZjI3jxQmdvouW2a9SesLHH9NZreoGi4DCi3EL354xbeneyuUM6TlVVNaJ445tDTS)JuAaJbv33AQnMLuVoeU44Yy0HsAjuMuMI7R8F1mgjaqoTZYDesl5DLu2zHDk40rN8WViR(ZVApHSw5QH(D5ud7j5V38I0sXDextIYaKVrdDq83)bv3U62dnY4zZBRTWpFRn40YpZNKLZil6ikM)JfhSXjxi8ntPvpwHFoS1EuWH(1QD6OeRc8DtmKfJWNxcpDjfxydnsHE5CY5nUZ63ax7uOYY)qMXKR)QT2YsRxLl36AE9TEWqBhIp9zoIlsKQPT4nhHIXqn7)wDy(A8uHubZAioT1ukPshIeAAIX22bwfT)Uv3T6Nx5Ix)S)6
```

**Comment by InfusOnWoW** [comment]
Well that's on blizzard, disabling the spell known check fixes it.

After sacrifice, GetSpellInfo("Shadow Bullwark") returns 17767, which is according to all blizzard apis not known to the player.
The spellbook instead lists 132413, which is indeed known.
