### ISSUE TITLE
The information window from hovering an aura can be too big

### ISSUE THREAD

**Issue by ezrekiel** [WeakAuras/WeakAuras2#4463]
**Is your feature request related to a problem? Please describe.**
It isn't related to a problem. The thing is, i made an aura that only has 1 trigger but a LOT of spell ids in it (around 100 or 110) and when i'm hovering it with the mouse, a huge window appears with a list of the first 30 or 40 ids hiding completely the version and informations about the aura.
link to the aura i'm talking about : https://wago.io/Dl9GhMDxH

**Describe the solution you'd like**
i don't really know but maybe just replace all the ids by the amount of ids when it exceed a certain number so that players can see the rest.

**Describe alternatives you've considered**
anything that could solve the problem would be good, i don't think it's going to be difficult anyways.

**Additional context**
![image](https://github.com/WeakAuras/WeakAuras2/assets/56939212/3ee6a3df-56a9-45c2-83e2-341d33ec0c2a)

don't mind the text my game is in french but as you can see the window takes too much space on the screen.

**Comment by InfusOnWoW** [comment]
Can you add the aura to the ticket?

**Comment by ezrekiel** [comment]
yes here it is : https://wago.io/Dl9GhMDxH
