### ISSUE TITLE
Unit Frame Glow Sticks Around Too Long

### ISSUE THREAD

**Issue by Wicketfuzz** [WeakAuras/WeakAuras2#4464]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Weak Auras is supposed to place a Unit Frame Glow on the Player unit frame if their own Lifebloom is not active on them. It works fine if you start combat with lifebloom on the Player. If you start combat without Lifebloom on the player the Glow will not always go away when lifebloom is cast on themselves. At this point the glow only goes away if you let lifebloom fall off and then reapply. If you refresh it before it falls off the glow sticks around. 

### WeakAuras Version

WeakAuras 5.5.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Weak Auras is supposed to place a Unit Frame Glow on the Player unit frame if their own Lifebloom is not active on them. It works fine if you start combat with lifebloom on the Player. If you start combat without Lifebloom on the player the Glow will not always go away when lifebloom is cast on themselves. At this point the glow only goes away if you let lifebloom fall off and then reapply. If you refresh it before it falls off the glow sticks around. 

### Export String

```Text
https://github.com/WeakAuras/WeakAuras2/issues/new?assignees=&labels=%F0%9F%90%9B+Bug&template=bug_report.md&title=
```

**Comment by InfusOnWoW** [comment]
There is no aura included

**Comment by Wicketfuzz** [comment]
!WA:2!vAvqVr2rr4D2brigekziXAZgoyTa(ai5n2EZUcuIiZB84ydJx78MXRdclnV(96(nDh)ED3Q7E84XbKcZIG98Caek5cVFa5W8haKZvF4jhK4U5FGpWnKOQ(ngNdXhWsEMQ7UQQ)QQ(QQNAB2iVbTb9fnlejkzx1qtc77FNlidDCLzxTtOK2f0)eQWQZiJ7XoX1pvzYjU(6(oroRpDSKKls674gMLRYOJnJ3nn1YCB93pE5fZo)8ZNrKjG32tjKU4wTFAV2H6LUDpwTQ2Adnz63K7CA7p7HpCezGAfH6Hb29h11o(a9dFuaI4i9dUDpLRO9nehl6QJymDtRML4cjqmXNmszOhyi6jhmxOGYSe3quD(eJYHQj34BhKQKo9RSPrC6sFWqcfoNSuVEbzkc9fVQrihyud1lgMpmZjwy6qlRVKDmZWdtYiw7YXwqLmw4gH7V9gLVELg(JIcmQm2IWEtW9qWfzovjzBtT314izmPBn84l9Q3NiPELwU8EFz5RV4xgfxPdQsW8dEzqUGkstfjaEgJhnvFS(gfnPKemWq5cpuu5XehGfscRYtIt9cx5G85qddZn7OOm9R1QtZD2R3UbDA26x2CJn2U32pR9fwoHQg9Hvv86fg2aW79gRzbO9tJHlMIMVgyHzUl1pzBPJHqHDytkfyyhEaJCuti5BpCp1iMXlUdJkihwTl(5Qpo4uLkVwaqovrfovcKNTW1DVA)XVrijtZjaPrqN1o89FYrpAJX)0p40IuXjm6bcQJ)7)oqLYLjKmZU73RZ2p9AW)RQapW6tua)vns2DKqZ46xjzO1PYrI1(AkqmIh6)6SR1RnDaqwCgXGbas(UlBMl(IF4LqUDhIlHdj4HshFkbcaOrHz)XHRV(tE8639chWXY2vZagLY8G39DnGd3vMnoAYqPW9uq3Ph)fFEII(fFUu)980SkNDTnnENqVpA8wxHvskaV00wixHFPDymWcLUUWwItM1VvZU963TxZWEizRhAgp0Rr8wmsMJFjseGCJh0mBb0kpQdukSUzGb7phrCmU6tITktmwvJMIXuFHe67WEqil8)U69mm4Qd7Ux7oDqF03bznNqZViV6o6cxXUYlS(V2ryXoLlszWzHebDhI5iErvqH8jZwT7S3M73zndlVXQgWHiGIM9vsm42s)DxUMVNctKrH(0(9N2rKYIZacegdV)nwfD21RdH(rEaAuCvWuGxEfmpRcMnHUNJztG2TSmOp9(FRN)VMqXHganSXQZaSDt1jWbWoel8RHXFZ0uy8dJYJHfHSC(u4YR4llOFvI3X9QwJP26638RDWwLqioFJELa7JKKSNv1i88PePi3dMhhADeJBZlUgD9r0ySmyMj1wkdKWKMZyelRRZWKdC8xAcUct1LFCqoriFwPS8Jl)TW))MxQCC5PXAycpZfpsfdT1XPcPWY3epXRiOeO7LwNi5OXBm)w5M59OVCbWlc9thS3FXsOSpmoMKCew(K0yotmG7269S)h9V(FUWpp2pag6TWPVDHjsVbq5WNMIf5ALXfNlmgLHRx(2h(NXgqsg3pfk5g(mpfTk1S8mqmH1gjk2i99edKkdB(BD(DBJo3gfd5QuXGfmNm)bT)2)(8p5oWFHjQmL5xuVE9A6FWTJaiFLiWGV(SVIs31unc2(4Yt(dxnitnQFQb7IWc0fBg2CN2DB3PDRE7gw4pfhzzFJzE5ktdqYyXnMg(m6QBTQV30VPhErt9Y(YEZwD5GxkU5ua81QBOkVbrL)UJl)tL)5l5ck0ENL531YNaNBX6dV8tl)SY)saEEOFh978)Xm8UOf2dt4eP7rROgmO8Vgfa0h3ItHBOAkl38rW3I0XbDAVzVPwwwQ)hmu(nFGGw0jyP5tiUQ6htSjg3izD6(pD7E(SMUbKaAnF0m0cfIV8hocN9V179j)OpDjOYnZNVakp8mE9lXhsqorI)bIGMWs4fDKXY4XwwoifU6kV1kRpR6LIw(mxTA1QxGTrIQFD0KRFois)AxlIf6newc0Oq5nSHV9kV9kR344)Xh(Fp
