### ISSUE TITLE
주술사 전기 충격 안됩니다

### ISSUE THREAD

**Issue by GyudongKim1123** [WeakAuras/WeakAuras2#4466]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

주술사 전기 충격 안됩니다

### WeakAuras Version

위크로아5.5.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

TW/Asia

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

주술사 전기 충격 안됩니다

**Comment by InfusOnWoW** [comment]
You need to describe your issue in english
