### ISSUE TITLE
Slanted Progress Bars

### ISSUE THREAD

**Issue by Ponix310** [WeakAuras/WeakAuras2#4467]
**Is your feature request related to a problem? Please describe.**

No specific problem, but I use WeakAuras to fully customize my Player, Resource, Target, TargetOfTarget, and Focus frames, and would love the ability to make Progress Bars (and Progress Bar "spark") "slanted" similar to how you can make Progress Textures slanted. Progress bars have better functionalities for tracking HP than textures. Alternatively, I suppose, would be the option to add "sparks" to Progress Textures, and allow those to slant when the "slanted" option is chosen.

Attached is an image of what the WeakAuras I've created look like, all using slanted Progress Textures.
![image](https://github.com/WeakAuras/WeakAuras2/assets/134174063/4b833841-e444-4c5b-9798-b8a8d37dc4b7))

**Comment by InfusOnWoW** [comment]
That's far too complicated to add to progress bars now.
