### ISSUE TITLE
[Enhancement Request] Display -> Model Settings -> make model unit able to be passed from a custom trigger

### ISSUE THREAD

**Issue by JPEscher** [WeakAuras/WeakAuras2#4468]
My raid was joking about some deaths and being able to tell who is down due to some similar names that we have in the raid. I went to make something to show models since the names would have very different character models due to different classes (eg in this case the bear tank v the warrior tank with similar names >.< ) 
i made a wa to show name and model, which is reviewable here: https://wago.io/feCVaWmFW

this shows the unit id sensing works, but passing that to the model does not. 
![senseunit-party](https://github.com/WeakAuras/WeakAuras2/assets/46279739/6ec96e92-5949-425e-95e2-50f5c7448a63)
![senseunit-player](https://github.com/WeakAuras/WeakAuras2/assets/46279739/36e78d58-cebb-4b81-9e61-eb729b5bc8b6)

i would love to be able to pass my variable with the unit, aura_env.my_unit_token to the model pages' model field. I think this would be be the most user friendly solution. 

i did look to see if there's anything to show an image of who died on death, but only saw announcements to raid text chat.

thank you in advance for considering this.

**Comment by InfusOnWoW** [comment]
That sounds too niche to add, thoiugh you can do that with a custom code hack by adding this line to Actions/OnShow:

aura_env.region.model:SetUnit(aura_env.my_unit_token)
