### ISSUE TITLE
Aura trigger remaining time doesn't seem to work in classic era

### ISSUE THREAD

**Issue by Masquue** [WeakAuras/WeakAuras2#4471]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I'm having trouble with aura trigger remaining time feature, it doesn't seem to work all the time. I use a remaining time <= 5s trigger and another aura missing trigger to track my Battle Shout buff, the aura missing trigger works fine but the remaining time trigger seems broken (when buff time is <= 5s, aura is not shown).
This aura is only loaded in combat, don't know if that's relevant.

### WeakAuras Version

WeakAuras 5.5.4

### World of Warcraft Flavor

Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. cast Battle Shout
2. wait until buff time is <= 5 seconds, aura is not shown
3. wait until buff disappears, aura is shown

### Export String

```Text
!WA:2!Tvv3UTrXx84AqfmFL4KMslfAuqP)fcuvsOPibfbEtDAdYXoD9MMuUG1ZU7yptZ6DgMzwN4()gWCtfLkK8JGVOxXv(rWpbJSq8a0hH8aaCMzTdTQXxS(mN53C(Ao)otUTk2UyuXOhVYaAilPolveIVYmIJR1SPeRU73s))F1pnZmNt0DQIV5F(7zMzMCdrjHeMyxgnrfSz5QELDhhYyXrSJsQFeLJBmA6YYrTWebkurzjYB6kviH6z8pQnwkrTW(nzI2iLp3xrBJ9BZI8fifUb)IVcGmbxdUOrt3v1LJxVEPhmiI5prhrmrWDLKLwHZ)FNTRI6MGAtd9vebwsGyT7R4ZKjcojSem)kNTDYwLJV8zVDmUfkSRFZygtq4x9SbXf4qQekq5dAstOsYZ0fAOFl9BRFh97QFpIEw9C6ID1ZRxqFHC6fj6lM3baQk0tjOTAHfYF4AIjIpE(1f42f3ym4GqcwwNWoQwYiP9VsW9qhStkC2aEmQlwm0cZpKLMOkU2GiCqAZMEqzvC3Yv2DR9QisL4QO2yYZLPb4o4evDab94H(BwQUNFDVsUE9amEmfkMWN)fSxnWkiftu8wU2doytw7aKAPkSwNaNO8XqBrDoooE7OgUW1bww4uNSRadoXT(ULRuPNmdKSGJ5c3fLkqRpeYYPoy5B91JmkT4OrYl7U2ABSXQJBIHyXfrJ2bjoKea(0f3UrFi0YQvfUM(d6OxvVM(Q6L0F(L13qVS(J1F44SQ1ouPKM0s)Pn03KO)IcdJOYhMMyRHRJs6YNdzL9YS2oSi8FmZjaNalsqX3hUwG70F5KdXyEji0cvUiGgq6lXXnTCh9RdfCjsLAA6jdGC3f3Yqu(Yf1RogwgGcpSLaQLrpEbErf(yLVKGaE1bzmYC8lzvA)mPPsorqVq)t3B5vK8zFHJVjlMj(UC5YL)5zANgroL2ZRgFERsuQIb2HgUpnsrCkblpjZr0JXrwL)84Sjbpys4mYU)dtLkAZUq2jGMcf2du6uTw1Y6vfqszWmWcm0gg5HF9NKbjk(SBjOpAP7LIIGQcAjpVxkXN6PXwDhXer7lq8E7prila6aSPGyymswo)ctR4ZTD1QLD9DQ55vBh3TVZD9gFQRRtFe(stYOdEj)y21skQTNxLTRw(Vg3kMD0wc8pMItc7U7RT61xFJSSZSXqZNPwONzH5WJdsvkwsToybq9gyuxbN0srUGf)0mRVzXMNwzgbDT3zQgIJztI17EeA4HjWaL82tupefJZeRqb1ZzDGduxWcsabtBruiNygkQzFWK(HXiPSraqAb22IUTtJv0cUwTxlW02hJf7xY1D7AUAwHb2JyPVnCm9YlckDKqbZimqyBBnjPJ5LKtYQHBjaoTrzV92E3sUW7edPjznNa6cdaKru7ddw77bpzOO8g6JASEknA4bFYwQkFF37TVmY5rmw7CdBAmyDLPVi)aflStgf7n(SNSmnAKdsPIXlbd8svU)xRLlkMtq5DpY0WI4fbpT5KhNagRR55MaisAsBvqqtmMet6JsOzr5n1V59Hjel0dJK2CrVW4idFf2Z(8da3KhYaykoC9nmayRH4BJdrDhzodeU2l5Z70grtm26P6FfgK)e9VPFAqgA9VFE97VL57Qt2bqWxy6BOg(ZTPse0shrmdHmJU3g8656nfsJXaBfk514z1ZIs3nU(gx)gf78Nh8Vp
```

**Comment by InfusOnWoW** [comment]
The api in classic era is severly limited for auras that are on other players. 

We use a library LibClassicDurations that helps with that aspect, but it can't do magic, there are cases where there's simply not enough information given by the wow client and thus bugs in tha area are to be expected.

**Comment by Masquue** [comment]
> The api in classic era is severly limited for auras that are on other players.
> 
> We use a library LibClassicDurations that helps with that aspect, but it can't do magic, there are cases where there's simply not enough information given by the wow client and thus bugs in tha area are to be expected.

In my case, I'm the warrior who cast Battle Shout on myself. Is there not enough information to track the duration of buffs on myself?

**Comment by InfusOnWoW** [comment]
No, you can only get accurate information for buffs/debuffs on yourself. Everything else has to go through that library.

**Comment by Masquue** [comment]
Sorry, then I don't understand why you close the issue by saying 

> The api in classic era is severly limited for auras that are on other players.

if 

> you can only get accurate information for buffs/debuffs on yourself

which is my current case.

**Comment by InfusOnWoW** [comment]
Oh well, then I must be misremembering. 

I can take a look at what the library provides in that case.

**Comment by InfusOnWoW** [comment]
This should be fixed in the next release.
