### ISSUE TITLE
[Request] Add explicit visual feedback when a WA is set to load: never

### ISSUE THREAD

**Issue by drnoonien** [WeakAuras/WeakAuras2#4472]
**Is your feature request related to a problem? Please describe.**
The scenario where this has cropped up as somewhat of an issue is when we distribute a large pack to a raid team and the pack comes with "extra" auras that are opt-in.

Currently the only load-condition feedback one gets at a glance is the document icon below a WAs name. In a raid setting this information is generally useless since all WAs are locked behind a particular encounter-id, but in addition to that it also obfuscates WAs that have "soft" load conditions like a particular encounter-id, and "hard" load conditions like "never".

From the perspective of a raider consuming a pack, knowing which WAs are set to "load: never" at a glance would make it a lot easier to customize the pack one is using.

**Describe the solution you'd like**
The solution I would propose for this would be to treat the "never" load condition uniquely and provide visual information in the overview, either by changing the document icon to something like a 🚫 symbol, or color the entire row differently (this seems to be what Echo did with their WA fork for the recent race).

An alternative solution is to relay this information in the tooltip one gets when hovering the document icon, but this implementation feels more cumbersome than getting direct visual feedback.

**Describe alternatives you've considered**
There's no direct alternative to this problem, currently one has to select each aura and look at its load-tab to see if it's set to never.

**Additional context**
n/a

**Comment by Jodsderechte** [comment]
see https://github.com/WeakAuras/WeakAuras2/pull/3715

**Comment by InfusOnWoW** [comment]
Spedcifally this is the prolem "behind a particular encounter-id [...],  obfuscates WAs that have "soft" load conditions".

The problem is not that never loaded is not highlighted, the problem is that we do not distinguish that an aura will be loaded on demand. That also affects the general list, not just an individual auras.

Thus your request is not somthing I want to have.

**Comment by drnoonien** [comment]
Ah, thanks for the reference. Interesting discussion, I definitely see where you're coming from with this being a half-baked solution and that conveying complete information about load conditions would be the "proper" solution.

From personal experience though I'd agree with Asaka in arguing that this falls under "letting the perfect be the enemy of the good". The icon is already there and in my experience ignored by most users (given that it conveys no short-hand information that doesn't require going into the load-tab anyway) and would definitely be more useful as a boolean informing the user of the never-state of an aura, which seems to account for the majority of the interactions users that import auras have with the load tab anyway.

But thanks for the response, I hope we get some alternative solution in the future.
