### ISSUE TITLE
InputFilter

### ISSUE THREAD

**Issue by ytovuap** [WeakAuras/WeakAuras2#4477]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Bad InputFilter in Texture Picker

### WeakAuras Version

5.5.4

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

InputFilter
![Screenshot_1](https://github.com/WeakAuras/WeakAuras2/assets/134998170/28f222a0-fdaf-4224-9cfa-fc335afd70e4)

**Comment by ytovuap** [comment]
Its only in Texture Picker, on another places all good. Just try this

**Comment by InfusOnWoW** [comment]
Ah it's the "Search" text that isn't properly cleared.
