### ISSUE TITLE
UnitFrame Anchor duration bug

### ISSUE THREAD

**Issue by Merfinq** [WeakAuras/WeakAuras2#4478]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have icon-auras with a simple trigger to replace ElvUI buff indicators: _type: aura > smart group_
Lately i've noticed a bug that can be fixed only by reloading. When you shuffle your raid group and aura is active, it seems like expirationTime or unitId (unitIds are not changing so it might be only anchoring problem) bugs and the icons not disappear and stays on wrong unit frame positions

I'm sorry for not disabling ElvUI to test it, didn't have a time, but i'll try it with BlizzardFrames to c if it's ElvUI only problem and repply with updates.

### WeakAuras Version

WeakAura 5.5.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create WA with Aura > Smart Group > Buff and anchor it to unitFrames in Display Tab
2. Build a raid group
3. Make the aura to be active on random raid group member
4. Shuffle this guy with some1 else from another group

### Screenshots

Perfect example with timings:
When group is being shuffled: https://www.twitch.tv/videos/1832461200?t=00h27m45s
Wipe, icons still stay on raid frames: https://www.twitch.tv/videos/1832461200?t=00h30m14s

### Export String

```Text
!WA:2!Dr1YUnsru0yzKIOrGymOiyyKsMSisGeobN5bjcqkDsCsa7yt1D4Xk3v391DxtQUQMQQ2jzwgwWS2FcEnR8c(aYxqRaFb(tiFbCR2oZmGxyFV1R75EoNRR1UrwJ4gXV6ZNWIKcpzHkcE0sHxqtKNCW4T3j6QbB9RDBDlTWKkv9YnmPq7OUQ3WHAW8OLMsfr4g9LmHzQBpF)EDjNC0X(3gjL8y5fcVly5qqRcfp)ZsnMC9UBUP91BYKB(6NFZTDTLp4AJILKak9hSHAr4R(Wj6u5f7ZLcqhOk0WP0miGiWV1oJPfkAv4dB98N)KzrYSqMa6dQZemtQcbqpb)QacmceMWJbk3KotxewL3xbdzxs86FyNoUf4fijkzr(mSihzdgejleMGR15aNFsS2j)JsEZ69Ybf1ivn(UPV1Qn2Y1CvoqSaR1RRKxXqSsthS)EE(d883J4pjgcXf9XZQo(Wo9BFwNX41N30o5pGgzyJa)55DLXWFU0DihdkbL)tidH6WVF35aKVhIUidHIkt6ynWhwPfLlJfqtnikmqQA08BS8eeqeiXkIFXkLRElMgsJo3IFr8WYvhBxqQIb1TZ)zGSsORDZI0ijxQ((A1QvF2IvgX0SqoemDroeNa5pW73kOkyT2fC(A)CkZa3VTM9sOEykWssnp2LlPX)LIjQiWnc1yehCvuwmjRGByRuUtWyuogiqAuLgAOCKnxPCxhseNQ12OP29x8eb5nSzv7nGkIhyjNGz)38vk)6)2DEWUowXEqLaFUaDlbtEtC8wUw0ApvOUAYiKLLlvMjQkk0QDLVN6Y5Zc1V(ElFazolvh)mMkyzwTr8mI2qvM2LR6kqV8navdEgfismPlFBSvOWtnWAEuAaNgI1xBptvv66Mrzc8ULDlpD5YEL9l)XYUHdzcMo9)VmAEQgkBRWbJ(OmGE4wfS4PEzhY37OFyhANWkEA)fagTxO)bcY)47BbF4sZbmnff24GqnKHSp5RAUvZwtmYOfUPpP2F8oRZIZ)0du4RV7AN1MS2xUgbErbA5R6gYfSyt6JNo0IeSzPg67E3BboBVn(StpXVnzVUhsO88uA9qS3hYsCqBHTqqQ7lLYS(13Q523Cp(oenzPtSKeR6FKE4gKOui682LVF91L5R)nF71JOkMf)ZGlZzZjxFwgqgr5fqJTvrPurc()gRu(IGPmXqPAUo5OSJE4B(SYooUibBCk9CAOjpT5tB(KgJ(NF5Fp
```

**Comment by mrbuds** [comment]
The second videos with icons staying on frames make me think the export string doesn't match what we see

These reproduction steps does not trigger this issue for me, and are not what we see on videos

Do you have bugsack & buggrabber installed? I don't there the green sack icon on your minimap
Can you include your weakauras savedvariable file in the ticket?

**Comment by InfusOnWoW** [comment]
No response from reporter
