### ISSUE TITLE
DBM Stage triggers don't work with combat-related load conditions.

### ISSUE THREAD

**Issue by Kolmarwow** [WeakAuras/WeakAuras2#4483]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

If you have a trigger with Other Addons -> DBM Stage -> Stage Counter and a combat-related load condition such as In Combat / In Encounter / Encounter ID(s) then the WA won't activate, without those load conditions it behaves as expected. 

### WeakAuras Version

WeakAuras 5.5.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
^ by "Tested with only WeakAuras" I mean Tested with only WAs + DBM as naturally this trigger needs DBM to function, DBM is on version 3.4.40-wrath. No lua errors.
```

### Reproduction Steps

1. Create a new aura.
2. Create a trigger with Other Addons -> DBM Stage -> Stage Counter = 2 (for example).
3. Enable a combat-related load condition such as "In Encounter".
4. Aura won't activate, but if you remove the load condition then it will work as expected.

**Comment by InfusOnWoW** [comment]
Can you try the version at https://github.com/WeakAuras/WeakAuras2/suites/13350946956/artifacts/730072741 ?

**Comment by Kolmarwow** [comment]
Downloaded that and got this error when I went to make another DBM Stage test aura:

```8x Lua error in aura 'New': Trigger 1
WeakAuras Version: 5.5.4-9-gc0191a3
WeakAuras/GenericTrigger.lua:3414: attempt to call method 'GetState' (a nil value)
[string "@WeakAuras/GenericTrigger.lua"]:3414: in function `GetDBMStage'
...
```

I went into line 3414 of that file and changed that to "GetStage" and the error went away but the issue still persists.
