### ISSUE TITLE
Missing buffs/debuffs not always being tracked

### ISSUE THREAD

**Issue by Elitesparkle** [WeakAuras/WeakAuras2#4486]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

We were in Raid and everyone had the Sated debuff. We engaged the Boss to reset cooldowns. After the Sated debuff got removed, my aura tracking it kept saying everyone had it instead of becoming hidden. The same issue happens with buffs. In particular, I saw it happen with Earth Shield. At first I thought the issue was related to Smart Group, however, it happens also when using Raid. Adding "Remaining Time > 0" may fix the issue, especially if using Raid instead of Smart Group.

### WeakAuras Version

5.5.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Install [this aura](https://wago.io/CkqKuxTab) for tracking Sated debuff.
2. Join a Raid and enter in a Raid instance.
3. Use any type of Bloodlust effect, so that the aura will show you have the Sated debuff.
4. Pull a Boss and exit combat before the Sated debuff expires.
5. Notice how the Sated debuff is no longer up but the aura is still saying you have it.

**Comment by InfusOnWoW** [comment]
I cannot reproduce that with those instructions. Does it happen every time?

**Comment by Elitesparkle** [comment]
No, it doesn't happen all the time. I believe it happens more often when using Smart Group. For example, sometimes my aura for Earth Shield on allies (included in my [Shaman Elemental Shields](https://wago.io/oNc_VtEFz) aura) tracks the buff that was up during the previous combat and doesn't track the one I just applied, even if I keep refreshing it. The trigger uses Own Only and the bug happens even when there are no other Shamans involved. I wonder if it's related to changing Talents.

**Comment by InfusOnWoW** [comment]
What did the unit count display after it bugged?

**Comment by Elitesparkle** [comment]
Assuming that I just refreshed Earth Shield on an ally that's not taking any damage and the tracking is bugged, the aura will show less than 9 stacks and a duration of way less than 10 minutes, which are obviously incorrect values.

**Comment by InfusOnWoW** [comment]
I meant for the Sated debuff, since that has a unit count text

**Comment by Elitesparkle** [comment]
Despite the Sated debuff being removed, the unit counter was matching the amount of players in the Raid and the duration was showing as if the reset didn't happen (eg. 9 minutes).

**Comment by InfusOnWoW** [comment]
The root issue that we could identify was an incorrect handling of group changes. So if that's right, the not resetting must be due to e.g. changing the groups in between getting the hero debuff but before resetting the boss.
