### ISSUE TITLE
Texture Rotate Custom Animation doesnt work

### ISSUE THREAD

**Issue by lierox90** [WeakAuras/WeakAuras2#4489]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When i try to apply Rotate as a custom animation for texture texture stays stationary.

### WeakAuras Version

5.5.4

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
None
```

### Reproduction Steps

1. Create new texture weakaura
2. Go to Animation Tab
3. In Main section select Custom Type
4. Tick Rotate animation
5. Select Wobble preset

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/4543689/f7da8825-9936-4c4f-8bd3-311393e70afe)
![image](https://github.com/WeakAuras/WeakAuras2/assets/4543689/67980013-7edc-4850-8e1c-4ed1e7c4c339)

https://github.com/WeakAuras/WeakAuras2/assets/4543689/a2b2ce33-1393-459a-bc80-16f5a62af38d

### Export String

```Text
!WA:2!LwvZUTTrx0OQe0wc4chvxdeGUGiiTW2FbEHtJb6IIcszQyLkljtrhBdya7HKdfNAQziMzO(X7QkqHxRhbT(BL301npbec9jipc(jO3ziLCYIUQcqKZpN5EpN7CMHvAuBqTWAH3U9CsaJ2JLXdWF7J4J7efjWYk8jLnUdrdIz8Umcv6x3PTNJ7IagljKnI2BejfF17x21jSpo2wfURMk5K(9XCXx998YM)X8qSFwuK3Kum)qNwDBCslBj0XfLXr7nvKItsAgkm(GiZhpetL9a0KX3DzDREEx2ZZY1ZoJsK(PjOjyUlfnalmC1q9peJsKXRwAxogwQBVUoTAnlJwsbJ0NIcKKHyVI(hXcX))hDpOmmNIsEhWxcJ(73FngNAb8jq6IKew8mbojsxbYFcOcbscmwIJNYzsfaAL5qIDX9HMID2mFTfqxFuW195SmA4TBKwtIhlVueJG60zLv20NPhu)iIXhGaaLnSPmkE2QPF(3jsx)JIqDwcJ)2kvQu9dfJUKE2wN41j9R1dIYKmiuKGtjHYyBlO79f5ImghQh83wuS5EEjJEVE(FntijrtaPQLh2dg0UDN2o5RXbDPWmxdmqtJQWVzLIGktxVbNCJ5XzOqOeHm98(eTVmtl0JnIXdpLJsNEAzJccmKii(j4Rk18hzatFAZ2TDCV0UJNxNJCB(Md9wSk19i3GFwPIo7tYJAwTTRZjETA22Xpgt6hlF86(fk8k7egkSHVeLaENnDhKLijg2khWM52gUbjiHq1Ywa5q1qxjZ4yfPvUO0nQ3Y6OUEDSBzv)xSo4GMEnFNJ)acNZ4XZ5ARHMcLlCgiqAOAPU2TCAFW9f8Ubhm1kC(9Q7640EgIsgOTy77kKiUSX7XibUNKJP9LXFE(A5VyrOYncqUuDAIlWWbWqXufovKYFH9aeHE734R3VCRoptGVSu4txU2pRyw7QfVFt1fkusoIksuw9818daFbBq(pxj3ds6QPAKrds)Zi4PkoBLYz95yH4LMA(Ew57ZFPziorIoR895BByc)sybOeteTFc28NmxUwZDm3d(dcpE3uIgihdvnAzmn)FMBveTLOcyITE1o64S92lt5kyNVeMGqFaMbSb4lG8JNu1fLKgJQK7M3R2Kk1g)L5h)KIkHv1hKQUCEr5XcTUN8VP7sz(FqLa7xX5cgdG1bvrCJLhovELrmFWovOLXv9JiuIiUr(XA7HstQDS7i0Ilxa2AK)209BQU2lcfGVWkmeU46ItXORTa)G4IUSryUU5r4qc6IIrvpFL7dN6TVHXguHJ0faX(5DnYJnSHKlnMlzbdlUo9lg(xpNeUxB8O9YiH3rT(r5iVq7gJp)UiLBh8YWffvDhPUr6XRNwdmE1l)IcC(WvztHTcAePVbNqvrfSJxvnDJLF3rDb1bebcQbHXZvUFIMrgtxI4QfWTHWXRoPftut4(6DF9U)qTH)9z)Zd
```

**Comment by InfusOnWoW** [comment]
There is suppose to be a setting for how much the texture should wobble by. The bug was that this setting was hidden, thus the texture was wobbling by 0°, which is a bit hard to notice.

So with the next version, you'll have to check the settings and then it should work.
