### ISSUE TITLE
Color Picker is Bugged Out 

### ISSUE THREAD

**Issue by Nuhttie** [WeakAuras/WeakAuras2#4490]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When I go to choose a color customization for anything it will now allow me to pick a color and the buttons are blank.

![Screenshot 2023-06-09 173709](https://github.com/WeakAuras/WeakAuras2/assets/136133093/e128218c-a0ec-4c32-abcd-76e4c8cf438c)

### WeakAuras Version

5.5.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Click anything for color selection

### Screenshots

![Screenshot 2023-06-09 173709](https://github.com/WeakAuras/WeakAuras2/assets/136133093/26f76f17-fc49-402f-b051-f53b1274421e)

**Comment by InfusOnWoW** [comment]
Did you follow these instructions in the bug report template?

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (/console scriptErrors 1) or install [BugSack](https://www.curseforge.com/wow/addons/bugsack) & [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber), yes both are needed.
Note that if the error looks like [string "--[[ Error in ' my awesome aura' ] then the bug is in the aura that got mentioned, not in WeakAuras itself.

**Comment by Nuhttie** [comment]
No error log or Lua even after doing the console command. Nothing that appears that says it is having an error for me to paste anything for you

**Comment by Stanzilla** [comment]
Which color picker addon are you using?

**Comment by Nuhttie** [comment]
Its not an addon its in the Weakaura settings as im using the addon. When I tried to change the Color of my Mana 2 Progress Bar, this is what appears. Its like that no matter the aura im trying to adjust for color.

**Comment by SpatenLa** [comment]
do you have bugsack and buggrabber?
can you provide a full screen screenshot with the colorpicker open with the two mentioned addons?

**Comment by InfusOnWoW** [comment]
Can you try this:
* Disable all addons
* Right click on a chat tab and select "Change background color"?
* Make a screenshot of what you see

**Comment by Nuhttie** [comment]
![Screenshot 2023-06-10 084757](https://github.com/WeakAuras/WeakAuras2/assets/136133093/a0cea1ef-5251-452b-b915-4b6349b2c56d)

This is what I see when I disable all addons.

**Comment by Nuhttie** [comment]
SOLUTION! So after i sent the last post. I went through and re-enabled each addon I had to see if there was some kind of problematic addon interfering with Weakauras. There was. Deja Mark on curseforge was the problem addon here making the color picker interface in within weakauras not working. Thank you @InfusOnWoW!

**Comment by InfusOnWoW** [comment]
You did answer this question:
"Tested with only WeakAuras" with "Yes".

Please do not lie in your bug reports. It wasstes tremondous amounts of time.
