### ISSUE TITLE
Trigger and Condition "Source Name" not working for Battle.net messages

### ISSUE THREAD

**Issue by wowregistering** [WeakAuras/WeakAuras2#4491]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Attempting to set a source or destination name requirement to  a trigger or as a condition for a Battle.net Whisper does not work.

If the battle.net sender is GenericBT#111111
print(aura_env.state.sourceName)  or %1.Sourcename shows the correct name "GenericBT" but you can't match it with Source Name in a trigger or condition, even attempting to match aura_env.state.sourceName to it fails(this works in normal purple whispers).

aura_env.state.sourceName == "GenericBT" will not match

### WeakAuras Version

5.5.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Go to Triggers
2. Make a trigger with type "other events" "chat message" "message type battle.net whisper" 
3. Try to set a Source Name to only trigger for a specific Battle.net friend.

**Comment by emptyrivers** [comment]
This is deliberate on the part of blizzard, see https://wowpedia.fandom.com/wiki/UI_escape_sequences#Protected_strings
