### ISSUE TITLE
Extend instance load options to allow for NOT load

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [WeakAuras/WeakAuras2#4492]
**Describe the solution you'd like**
Allow for weak auras to be able to NOT load when doing certain instances, like m+ or Raids. For people with many auras that have an impact on performance it would be beneficial to be able to just not load most of them during m+ / raiding.

**Comment by InfusOnWoW** [comment]
That's already possible by selecting the "None" option in "Instance Size Type"
