### ISSUE TITLE
Option within aura trigger for buff/debuff expiring post-gcd

### ISSUE THREAD

**Issue by rembeast** [WeakAuras/WeakAuras2#4497]
Because of the spell queue window and how some classes have "gcd locked" rotations requiring knowing what the conditions are for their next gcd before the current one is finished. I would propose adding an option to the aura trigger for buffs/debuffs.

The option would be a simple tick box that reads something like "aura expires after current gcd"

Currently it is done in a custom trigger by checking gcd end time vs the debuff end time.

The end outcome is a trigger that returns true if the buff/debuff is present and the player is not on gcd, and returns true if the player is on gcd and the buff/debuff will still exist when the gcd ends. It would return false if the player is on gcd and the debuff expires before the gcd ends.

**Comment by InfusOnWoW** [comment]
That's far too specific and too niche.
