### ISSUE TITLE
Blacklist for WeakAuras shown on Unitframes

### ISSUE THREAD

**Issue by KampfSchneggy** [WeakAuras/WeakAuras2#4498]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I'm not absolutely sure if I should mark this as feature request or bug, but as it is working now I don't think it's intended so I chose bug.

The problem occurs when attaching auras directly on unitframes (Group by Frames / Unit Frames). Some unitframes are shown multiple times. For example I can have a player from my raid group also as a target and in focus. In these cases it seems totally random to which frame the aura is attached. This problem is consistent with vanilla unit frames as well as in my case pitbull unit frames.

I think it would be nice to have some kind of blacklist or whitelist for frames where a aura is allowed to show so that it igores all other frames.

### WeakAuras Version

5.5.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create Aura in dynamic group
2. Activate "Group by Frame"
3. Choose "Unit frames" in dropdown "Group by Frame"
4. In trigger of the aura choose as unit "raid", "party" or "smart group" (behaviour is the same in every case)

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/66181493/f9402f69-2475-4d34-b3e9-bb3abbf892da)
In the screenshot you can see that bozh tanks (Paacha and Gundrul) have renew active. The WA is the symbol with timer on it. On Grundrul (it's a bit hidden behind another symbol) it shows on the tank frame. For Paacha it shows on the targettarget frame in the tanks window. For none of the it is shown on the raid frame (Group 5) In group 1 on Mønka you see a WA that shows prayer of mending with a timer. This is the same aura (multiple buffs as triggers) so the renews should show in the same way.

### Export String

```Text
!WA:2!1DvcuYrvv0uPe5ydijDidKyaRmO5KjeczhoEig7AspzgONfQUNmt2SRQR639VYuDvf)QQztrLbeIBO2G7kIT4ckU1UGlrrN4(6ZreJkUfWnupQJ6rpEoU8()FnBHKAotx)6xV)7)EV)7DF3s5azJm21w21w2z26zDY6C8D0WIzxG4xlME7TD6kbmhct3YEehwqy4k09CNCslMJwPGaVy3q2e9xTAejwPLLVnnGnqGRFCt9(lvQ)ElKVRsTKkOZaVa2nOOOOgUIKisoPSe2G(UXMml7y3a)ODBefBXIZO7IZMPsv8wenZuXm3A1iSO1Ubw6W7OPdPss1QLMiKW6oFHb6AWc6X4dgwjmRTpvuiXZRhNOmNokPczuIFCruA3XBvUZCflvUyPCgL0tWnPsON1ee28InaJGIzuCG8fkyiMPs3elVyQHVvDsuMgj(PMqMw2bEj19lgAztuNfDAcZ3Y7aODIUYT1iI4vvelGZ3WYZTMVHrp7V7sgEU1DJVag6OCTO0e3zdsnU3NPz1epVoDz2EeZgw(U1T4rLDdxqxqwD)aFY0eRisXyM4S58NXb9vUeL5EolIyh47enfxgECb6qVULRpUwOdytNpCvWMHRghErN5m6EbwohOsSLh6UTzupbpwZOh5ojPnyBzmS9SII4J0XOQnFaBs0wWO7YRWSCCtIU9lCMkP5hYJzvv1bu36w21u1yUoCBPDJ9XKoeHofE8xGheOgr24EQ20MWdEc5kyurMVqBkVN3PgjCLfV5elgrRlm(One1nM0KjIz81mTZe4zJRDnwqsy6QkIg)5nJ1ItYAmyF9uQlJC9MVcgNQ6wlJoUIXGRmCv2jrXb1xskz7zY0GB8d56etVGtJRapW8J7ctudyvmYTVEgSOEualg6yA5wkRcEgPP794JpO2moWEuzcXLPCNpT2DDoDUcf0mSCD00XeYOPqlqMa1QkdtWWZwRyRvnR0Y7Ipf3fRuStJ857JnEAP22tCDADGGR7y9EZdzvXQ7WvSOfi(jC9d4gRJHRDwE)84seEljmKW9n9K44a)TzeX3yf0eIfzrkn55pUIcXmTC9RgWKjGT1chAtYZRgImNXkjg3Q(dLcM1Eth)6AIQInIiwT6PfJLg6Wkg2ZLqOcNNc8015qc6tgeuNNGSJzSrqeNGX8loMBiXCgXAnMZGcx5sEU3ahIEUbl1)0ZTkEYbv3fTBt4zExBaU4JVUTZi1ZU1gCyarf7XAMN5tsiSe)ATWIZJDYt4xJpUplB6y4)re)gd565mwcoMdVDYtqj(oKiTcKke)WlRtIVfZnYMsyAhYcXjy44K4jXKI6vC9jPzmu8O0VFFVjmHlvNHNWn54l5h3nkoI2cZ5lhlbmPnrWGagPicqqNMxt5w11MRILxbfZGuNoRuICOt0h3jo0S5XJxnHr5AtJJMDOGAKf)CxEeUjINAj8STWSDfmssuKlHHvwAO)5rcxt(6eeqvdDKrdymRAC3uRB88ewbSYMr0GX60dRSJmnIXqUx77ERm0G4wG508aQav11jATTVTRLxfxIlfD6QKyBAA3ak8SG1nl(U8JJLkfLWWu4YZGyoRcUKmWAG12cpI6hbSSWsPSpFy1qBZi2V5MR9RFpZGAOhrmGV7u4kY0YXn6yj(yFIrjB3YFIWSYQ2ss04cb1CTdV(mvfIe4VXoYOHxmsCcZxBJPy2hEBhvZY3rBJ(bXAZn32pAhDKbdfHR0sO9unYZ2EWL1KNCvErjXA32SJqiH54NBXg88skSrje9sHz3YXV0kI1zOYNRHLxi1IxmpvewK7wJglFTUQ8((vLI0f6bH348(rilOgJefTznrRXnJh6EXwlX7eVq7Q0MxwTnnNuOBLzgrUhwoe5XHFBWFuStuUjlEuyauUzpZ8ckSJB5CzhdNE)GPg0WP3p4t1Yg(SzAd3XCk4S92dkT8kI(dtOAimxLgcZuGhkp7ZoHs2XvQiaWikYWyovPycZVXzKo4fGkuBbyoT9OneXAeEDw0w2pjoNibOZ5F)gBFaJEYxSKw35ZvqBbGK2LQlKHT334cQ7W74OYxS4yW22S4pHdHxykYcXyUVGGCP5dLMBAPFpU6tTv9S8(S8gD(oZtOs2PTIfB(EVQi7OiRyo7acDX4Xhub2WMAdYods6ybnD81fEfXKXJll(rc7xoSCSBDs6tkHR5Piqu6amfA(31(ZfjikEkIAHa0lq670YzNNtuTWvjMbbFc4DzSfnp0ZHpoRCxChNi7(ERP9XpyAZVPfV)yygGB1jQ0z((kL3OPmhOe(g9(6VV8HANlhQEGtzECXmSJZLiP8jkJq6eeu0Z5S5((Z7(qwggo5Vl85CUuPhPML9eLR6feWmBkeybmLgPlWpoC15STDDW(SyAksfnIp2gX6KXQLegsNugOtNCDlBM51LGAC)dwQqp9Lxo7yiZKHywHtnu6azKCu3i3kiJZ0tUfXIhEOZIJhMoWG7yolXkgwAfQlyeCEyRo98B45m81FUIsHmSxiV9LAfkHxrS(PMRtpfUMrXQnbhpKcABi3lVatb4LpsthbV2kNzkSDXV7ydvIqH9ivK1VW22GEV933nAcpQjStuKnzAc7A5NwuAOJ0ED4O9Bp3(2N8JtC4zxehItVwJtBk60j6UzcVWmqPUF4Nm39Vd8cwpRu)dWz0a5Zi5aTqnimemm8caxWOvX8fY3PK7zywuBDM6u4MAWtfBiAYWpSHRu0WPyqcs4ADldjmgUMLYyuRVeMggCi(KwIDSBrKApmE8mHrQKJvpGnbCVQHxYCbpEzX(CJSWtzhQHyvuOpoJ0uv46G5zg9L)a5nKWfLKklCJ9WzMxf5jEKoTWco)A6wSJmypx9cpD1f5laUjvJX4vRR)mJGU4z3GTQxC3JvF37GUn8thD95CIj0wbmxEQoh7mCf4ExQNoZvOCp9HdlMhoCg4iTbh1eYWBV2WjOSe1Nc3hYo3iIdDf(8wWaZ540VF0rMhq)i9sCCTosrUCrhrhPd6BnaH4v0ZnClb1QnfQrHsOWfMbUOmh)6GYRgmvaRfORcvqBFiV9pUnzF3y1DETGJjquGQqnGsLggmlf(BWFxyuW)GIkIRUu2OWXYUvyKd1QOGXynKJwC4LRFYtWzt6PH)ogXts2C)43DIXl2SfrtKtTJP1lYonoCv7hPHglMqhBrk6)0ipZHZ2ZZbWm)iKXjedjuyukmgfgF5WRGctEi4fbVy4wGxc8s587GxMjmLjCBCYBCoxWTtHxUGUgChNbbn4orAzhhPHb3kYbeqgTxrg4vcVk4vdVg4UEWLbVwze6NAcVokSE4Xaxt4bKZ9bOWhmTld8Gya47PcFyeJ8JGTgGpQOva8XWOxl4JdFIBf(KkWNcEi4tdFg4ZAcFxf4BcFlCHFE4lycpSuHFr4lbNCDldMwb(YWxb(QWxd(6MW3ax1jq9(HuGVZQHpNc8Tvb0sKjmxZOWmCqc4hycpYCid7A5iSa8dHhfbdGF0sqcKGgNc(XWpHcLus5ZHDD5nFxeFo41lOYbnG7gUhv4nOcVr4nbVzk8weuPG3NQqY3g82H3kfUxf49aVxKJc8oH7JRTMQW7gUF4DXjTaVdr39Zyp(vOFMpd8lmNh84pUESsg(LWvcpj8h4Wbx6zahyHm716CFrWJVh4jGFnyl(Uk43qHFBAno87GFph36Mubd4Nd)jk8ZKr2)mfE)ZtGa(lWFfo8nSbdmZ0EKUGlwDQrXsvoMHo)dPApiS99ShJrT8siGhZMA5xJeT2nCkLLDdDV3h(zZV0uvuNc5YHnEINaEGDd)hUEG)l8)KRgLf(NNsrrUkLU37JToXLQ6Puwo8av8C9hH4yEwx3)E(119EFIsIRU37JF38R7rrU(tPOU41Yx1)AofOAEU3x47trA9zh9rg())d
```

**Comment by mrbuds** [comment]
The screenshot and the description are about different problems
- on screenshot issue is because tank frames are indistinguishable from other raid frames, it's not solvable afaik
- description is about pitbull frames, but not enough information and example is given to investigate what's wrong with them

The default priority list for frames is defined here https://github.com/mrbuds/LibGetFrame/blob/master/LibGetFrame-1.0.lua#L20
Pitbull target frame *should* be ignored, it has name `PitBull4_Frames_Target`
Pitbull focus frame is **not** in the list, if you can give it's name i will add it, to get it's name type /fstack, mouseover your focus frame and it should show the name, probably `PitBull4_Frames_Focus` but only a guess

**Comment by InfusOnWoW** [comment]
We are waiting for further information from you, once provided we'll reopen.

**Comment by KampfSchneggy** [comment]
Sorry for the late reply, I didn't see the notification mail.

So as I understand it's not possible to solve on Vanilla frames?

For Pitbull the issue is that the frames can be named when creating them. So it's always "Pitbull_Frames_XXX" for single unit frames or "Pitbull_Groups_XXX" for group frames where "XXX" is a name given when setting these up. So maybe it's possible to have an option to enter custom frames names to the priority list in the WA GUI.

**Comment by KampfSchneggy** [comment]
Additional Info: I added the names of my Pitbull frames to the LibGetFrame.lua and this seems to work fine now. So confirmed it is not a bug, but a problem with pibulls weird frame system.
