### ISSUE TITLE
Help: Can't open WA config in WOW

### ISSUE THREAD

**Issue by augusttay** [WeakAuras/WeakAuras2#4499]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues.

### Description

Since last night, I was unable to open the WeakAura's config window by typing /wa. This is after I was playing around with the intensity of the 'glow' of my weakauras - to show glow when the cooldown of my specific skills are finished.

In the middle of that I've gotten an addon error mesg below - after which I can no longer open my /wa.

### WeakAuras Version

WeakAuras 5.54

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
Message: ...akAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua:641: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@Interface/AddOns/WeakAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua"]:641: in function `glowStart'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:134: in function <Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua:126>
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:191: in function `SetVisible'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:235: in function `SetUseGlowColor'
[string "local newActiveConditions = {};"]:48: in function `?'
[string "@Interface/AddOns/WeakAuras/Conditions.lua"]:770: in function `RunConditions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4394: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4355>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4503: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:970: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1291: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1901: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1685: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1530>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1878: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1165: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1127>

Time: Sat Jun 17 15:14:21 2023
Count: 1
Stack: ...akAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua:641: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@Interface/AddOns/WeakAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua"]:641: in function `glowStart'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:134: in function <Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua:126>
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:191: in function `SetVisible'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:235: in function `SetUseGlowColor'
[string "local newActiveConditions = {};"]:48: in function `?'
[string "@Interface/AddOns/WeakAuras/Conditions.lua"]:770: in function `RunConditions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4394: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4355>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4503: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:970: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1291: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1901: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1685: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1530>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1878: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1165: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1127>

[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1279: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1230>

Locals: self = Frame {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 login_squelch_time = 10
 mousePointerFrame = <table> {
 }
 editor_font_size = 12
 lastArchiveClear = 1580810229
 minimap = <table> {
 }
 lastUpgrade = 1679441403
 dbVersion = 65
 clearOldHistory = 30
 registered = <table> {
 }
 displays = <table> {
 }
 editor_theme = "Monokai"
}
Private = <table> {
 HandleGlowAction = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3500
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @Interface/AddOns/WeakAuras/Transmission.l
```

### Reproduction Steps

1. Start wow or reload UI
2. See Lua Error message

### Last Good Version

WeakAuras 5.54

**Comment by mrbuds** [comment]
Hello, a few things wrong in ticket

- weakauras.lua data from savedvariables folder is not included
- "Tested with only WeakAuras" is ticked, but the error message show a lot of addons are loaded

**Comment by augusttay** [comment]
Hi, thank you for the reply - I have replaced the error message with one with just WA addon loaded. Also pasted below FYR. How do I uploard the Weakauras.lua file though. It is 4.5MBs as well.

Message: ...akAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua:641: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@Interface/AddOns/WeakAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua"]:641: in function `glowStart'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:134: in function <Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua:126>
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:191: in function `SetVisible'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:235: in function `SetUseGlowColor'
[string "local newActiveConditions = {};"]:48: in function `?'
[string "@Interface/AddOns/WeakAuras/Conditions.lua"]:770: in function `RunConditions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4394: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4355>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4503: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:970: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1291: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1901: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1685: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1530>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1878: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1165: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1127>

Time: Sat Jun 17 15:14:21 2023
Count: 1
Stack: ...akAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua:641: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@Interface/AddOns/WeakAuras/Libs/LibCustomGlow-1.0/LibCustomGlow-1.0.lua"]:641: in function `glowStart'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:134: in function <Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua:126>
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:191: in function `SetVisible'
[string "@Interface/AddOns/WeakAuras/SubRegionTypes/Glow.lua"]:235: in function `SetUseGlowColor'
[string "local newActiveConditions = {};"]:48: in function `?'
[string "@Interface/AddOns/WeakAuras/Conditions.lua"]:770: in function `RunConditions'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4394: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4355>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4503: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:970: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1291: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1901: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1685: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1530>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1878: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1165: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1127>

[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1279: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1230>

Locals: self = Frame {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 login_squelch_time = 10
 mousePointerFrame = <table> {
 }
 editor_font_size = 12
 lastArchiveClear = 1580810229
 minimap = <table> {
 }
 lastUpgrade = 1679441403
 dbVersion = 65
 clearOldHistory = 30
 registered = <table> {
 }
 displays = <table> {
 }
 editor_theme = "Monokai"
}
Private = <table> {
 HandleGlowAction = <function> defined @Interface/AddOns/WeakAuras/WeakAuras.lua:3500
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @Interface/AddOns/WeakAuras/Transmission.l

**Comment by augusttay** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/11778216/WeakAuras.zip)

Figured it out, thanks.

**Comment by mrbuds** [comment]
Which class/spec do you log on? I don't have any error with your data on a holy priest

**Comment by mrbuds** [comment]
I managed to reproduce error on warrior fury

**Comment by mrbuds** [comment]
Error is fixed with this change in LibCustomGlow https://github.com/Stanzilla/LibCustomGlow/pull/20
I close this ticket as there is nothing we can do in WeakAuras.

Until this fix is merged in the lib and a new release of weakaurasyou can replace LibCustomGlow-1.0.lua with this file
[LibCustomGlow-1.0.zip](https://github.com/WeakAuras/WeakAuras2/files/11778372/LibCustomGlow-1.0.zip)

**Comment by augusttay** [comment]
Hi, it's fury warrior, thanks

Regards,
Augustin
________________________________
