### ISSUE TITLE
Ability to disable display text formating options via conditions

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#4510]
**Is your feature request related to a problem? Please describe.**
In some cases people will want to use e.g. class color only for certain conditions for example when using class color for bar when something is on cd shortening the name of a unit if it's a debuff/vehicle replacing the units name or other endavours.

**Describe the solution you'd like**
A simple condition option to disable the formating

**Describe alternatives you've considered**
Currently the only other way is using %name and using 13 conditions to change the text.

**Additional context**
-

**Comment by InfusOnWoW** [comment]
I don't understand, what you want to disable.

**Comment by Jodsderechte** [comment]
![any of those](https://github.com/WeakAuras/WeakAuras2/assets/39654549/3cba9809-3ff1-4a98-913e-8b775ba0be6b)
any of those

**Comment by InfusOnWoW** [comment]
I looked into this, and it's too difficult to implement for to little gain. The fomatters are not easily added to the region's properties, and there's just not enough gain for that.
