### ISSUE TITLE
Can't detect Elysian Decree

### ISSUE THREAD

**Issue by obliviom** [WeakAuras/WeakAuras2#4512]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

WA is unable to detect if the Spell ('Elysian Decree' - 394985) is learned, usable or in cooldown. The only fix is to close and reopen the game.

### WeakAuras Version

5.5.6

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

New aura
Icon
Spell
Action Usable
Elysian Decree

**Comment by InfusOnWoW** [comment]
Due to how the spell is setup you have to use the "Exact Spell Match" option with the right id. 
Which is either 389815 or 389858 depending on spec.
