### ISSUE TITLE
Sound Looping Does Not Stop When Stop Condition Should Trigger Sound Stop

### ISSUE THREAD

**Issue by allthefox** [WeakAuras/WeakAuras2#4515]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I use sound cues for many of my longer CDs to remind myself to get them on cooldown when they come up. 

Unfortunately, the newest release (downloaded from CurseForge) appears to have broken my { IFF on cooldown = false, loop; IFF on cooldown = true, stop } conditions. The moment I enter combat, the audio continues to loop until I exit combat, potentially for minutes at a time.

Upon further testing, it appears as if all audio loops persist despite any and all stop conditions entered. I have uninstalled and reinstalled; removed all addons; repaired; used older, backed up WAs; nothing appears to be working.

### WeakAuras Version

5.5.6

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Create a condition that tracks anything (cooldown, aura/debuff/stacks present) and create IF TRUE condition to loop an audio file; set to stop when the condition is no longer met.

### Last Good Version

5.5.4

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/138162225/341dfd11-8d63-43c7-83f0-ac12c6756fe7)

### Export String

```Text
!WA:2!Dz1tRTXru8QOAcOuOXUjghtpicPM0a1K4q9HqBbTosXoilPU76AhWG3z3D0Ut8Qz2mZSsw5wfeA6FoPJ9wvdTei0c6upBO3heL(bWFeYNG(Mzx5KuFW7BEZ8EZ7p)E)gvQXs9wkCPWNFZjKag1HLXdWF87XpPD3UcS8l5dZf(IlmfrdIz8omcv6Vv9wU1TNfWyjHSbuNbKuSx6LdYeswpx8jY9sdrsSFM5ZPZpx9WiCmhfijmQytBHeXLv87sOerCfl4JSYijNefH5IwRXleF(vSLGrhBHYKSZYe4Jq(cg3Fxwi2BweMI5KaNy2G20jc4tTKbOHcRmWD(PjOHy(uTr6TIcc9MecXv3UUdtX8TR3StJ9AAjHf2IuCscpJI7JPs1IJnRBH6HxzHxEvBkiiQyB2m9ABvKrv7WzrCSqu9Mo6J)PJcZ4iD(T0DMXXOeN5ozKBmU62zu5mtWmxT3iJ4oHIkNjY8nU3bcpYjtpARAoUh54wZ2DK2gDc5LUOw8DsAVXAvMsK35(Odhd(W2Pt9Mnhd3AEPSY0qI4XzuOd0hVbIomDrKr2nFFDjT8RHomMtrjFd0gGm5zV(ymoTgeNbsBDU5nwGt6AqcwnR3W9mHKeC8W7xK5XtGGWghPBYpCz1QZGL(qWfXzz0WNFL0LKacb6hiOcEqo(Qu61mkn)RlJ3dbhOqWIYO4XNV91)er6LFlpSflHXFyPsLkFwU2ZJTA752o9Jmk1qhWvKG9jHYyRAWYxNFxKtWHgLF7SCe(JkIOtn7)yast6ouTWeotcyzn42Qv7w1vRYH8sFMjMdgycJYWFJlscQ8SoUvDqur1wioNn4Ds85xZmJUbmE4(Cu6O9leYV9(ebXpbhxKWV1iy6I70QvD7JSA762Ex7DEW2UZo)EDipfFTI05G35E07Aq(T3ZT5oTQ)VZIsydAWXpjdtdg2P8TxFJ8mtR)uay9GKIsC8iTkJX12YjMqXt0kAIPrY4RovlppNghn3itbXS384WsVi2CTUXaSHcdpLng4eGsW5InbVlUKX)wqbbZJ7QwDSghzwnn)ZrciplFAXIG3Gdk0uu98MFCmq)WVt1oqlpzwHowEu5hJjrXYV0kHHaikNq1O10LT7LLijvmtyAIbEC6sA5GeKqa9Jq9KCG3eZeie(uz84Z33ZcMjXlRsQmQyMpWZshZAv88JVHw(S31DR5lG7pb7EdvYYU3WZp)OWjxELs)1F7zOZ6JHQhanSmwO6VaS7ca5gb4ocGGEO5sEkm6aClxG3nN1vR02CBGjtVF9DB3A790C5GEtseW65JKEJt7NE(TwXIZsmbnW7QFGWN0lLXLt4MHCnKWs)6XRZrCn4aVMwPVZw21R3AmIs6zyg2uDPgQvv3B2CsYJ0eVCbgmouCkgjWosUbqDXr6vAVOUNvpeHAmu99QFq9Jxu9tG4h8)1mLqZjmahV2uqmaxxtfkItxHerzCC7uZlpgT1HjsUWttiQFKyhieUG6zE(W3UKOkM28CwEGwei(Gx4UY8xY00a3Niqa8kmwTy8ejlOFoD5kL(U3)6KWZ2znRQFw15S(t7QRkq2HKOY2OK0y4ZanVZxdpijqsDfbhVrgjCAaDt(gwp5X3(reaiQDloEgWGb12ImOI1tzSE6P17orx7igT3At7GyCWXBQ(WYJ6J4eD4nHrNNg29rjz4s(je6XqyZdIr0iS4wRPEH3OuodAfYHAY71V766rpqFJjcnPTPpz1KXspnFnhNIrYY2MvPF1o6xmaig(WAHHqKC4(y0X1GusCyh2aGWqlUloKGo0rBH4WuemQatJRZIIML7tD4qXjB404a1VRE1AQFrNiQjQFv9IYQF7E6We24NHVBQEPLJKLQEfVA(p6q9hQ)uBvLrZBrX2VHsEjH9NV(NV(Ml1)Fo4)(d
```

**Comment by InfusOnWoW** [comment]
That's already fixed for the next release
