### ISSUE TITLE
Importing an Aura made with an Evoker talent load condition from PTR fails on live servers

### ISSUE THREAD

**Issue by seanpeters86** [WeakAuras/WeakAuras2#4516]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When exporting an aura created on PTR 10.1.5 with an Evoker talent load condition and then trying to import it to Live servers 10.1.0 the Talent load condition will be erased.

[Example Aura made on PTR](https://wago.io/LzaZkT8h7)

PTR:
![image](https://github.com/WeakAuras/WeakAuras2/assets/10604059/7fc006d9-9a74-4d4b-8eab-e3c7aa057b31)

When importing that onto live servers the talent load condition is still checked, but now empty.

Live:
![image](https://github.com/WeakAuras/WeakAuras2/assets/10604059/f9ebec9a-21e4-4598-b548-2d05656ad5b1)

Both PTR and Live are using `WeakAuras-5.5.6.zip`

### WeakAuras Version

WeakAuras 5.5.6

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create aura on PTR 10.1.5 with a Devastation Talent load condition
2. Export that aura from PTR and Import it onto live servers
3. Notice the talent load condition is still checked, but now empty

### Export String

```Text
!WA:2!Dr1tVnoru8nQGaCrO2SLODL4q0IGUNQqlQ9a3IdoBlkBsX2LwecsgB)C8qDMXmZ40MEBJeI9C(iKZCkI7iv(cyfH2pa9Jq)eWBg70UfFWAE))3V38MxTo1hxpQE0B(8f0qoZJNlcHp7rIl7hhlbvnX0QdljSWeU4yoLPcA70Z3XDviNNgXVG5DbndgE9ArNOrqIToDdNPe0rJaH8t(sr1X3ARMMb25mQkREUegqcKCrWHaj9v8iy4nY8aycWuE5XX0lxoODlp)bE(TC9V5E3nU6A8lBNtWC1SDcrqcvGGkv0qzXhhKLsMcctq6QrL6)dNjZG00JIKwlUxBXJDzKXG0A2AVVhhhlaehUEh70T7IiiaHLpYaXHoDpUZjDNNZQyMv22iaOta)szng)ZhDl2WabJK(dyBGYz)(TNdqwlefHkxIIYtMlH0ytJT49XcijQCbrbjlqe4cJWyKFtJInxHIbKWZhj45SO3StwDfCPAGmHGn9ZQUMYEQrP5xmxmMGouDWMXzW87m)SVqMT17KH28uU47QvR2g3uQDnOSBDIF)ShBusYvCmv0WtPrQe7wO4TL1IEjezu(6vLtk)yfIU2y)xZXBL4PibfCfsoFuPDV(9Ck2uG8s7ZcJJHgySb(nVIe4n8wDe0RA(95KiSXqA67)aUVUsRm6UGlIovqYMDA1HsamHkPbPWWko)otZzBFuVEoUdS7773)vUh9Yd9xDxP9OxbpTIrN9G6OTAMd6FIF3J6582vJs5x0ra)woWcNE879v79I9lzN2Ws9V1zyMwqh8QGCLIZ6pbe4W6cT6UaBKk5tn(VMzZ1cTVRZCnoK(Y1AsS1gtmv3pHgEodKYnmr4fssHYJDPO6TnfWg7lGijibOJsuV2oLtIMylrI2WDCEQIADtykrkXEu0a9yAJajLnkf(RFkqHjKPAu424j1(N)EOTXCHRv5l5hg2qxJS28cT1YytwimJ0A2x8Hz7SEPHEG4BPscEhfLmNWO6Xmo7axPIiuDUgisWtjmnNpOyZIDxfPFLGUmqVpribCFtKCM2ptU31EmHY6u8lgVlgumSGuSBqmLrLj)F1lPSYhjy(SCVWmhBFfNpUMENI(f4bf)SvrOLngUYAHIhoP858tQ9hF0ZOrzB5mHFoiA6dsvZwi0CVFsEzSaxUGOhhE342YHPoAvAGg4121XP3lYPrlp95x(1PpFYPc2HbiDIPJSeuMUsqIPf3UQBHRwWDh4gqsAwczJfAUtn40A26o6Wv4RvSs9Zknux6U)E7V3b1N8VN9Fd
```

**Comment by InfusOnWoW** [comment]
That's not a bug worth fixing.
