### ISSUE TITLE
Access to internal UID used by WeakAuras

### ISSUE THREAD

**Issue by Elitesparkle** [WeakAuras/WeakAuras2#4521]
**Is your feature request related to a problem? Please describe.**
I made an aura which can disable Masque for itself, so it doesn't ruin its look.
For it to work, however, I need its UID (see [here](https://github.com/WeakAuras/WeakAuras2/blob/6225b88d7c899f8865571cdd448d9c151fa4a369/WeakAuras/RegionTypes/Icon.lua#L312)). Now I'm forced to hardcode it.

**Describe the solution you'd like**
I'd like for auras to have `aura_env.uid` as a field.

**Describe alternatives you've considered**
I'd like to be able to use a `WeakAuras.GetUID(aura_env.id)` function.

**Comment by InfusOnWoW** [comment]
The uid is in the returns of WeakAuras.GetData(id).

**Comment by Elitesparkle** [comment]
Thank you! I searched the wiki and asked for support to no avail, so I thought it wasn't possible.
