### ISSUE TITLE
Support for Npc ID with Multi target input

### ISSUE THREAD

**Issue by wazerstar** [WeakAuras/WeakAuras2#4522]
**Is your feature request related to a problem? Please describe.**
I would like to add all dungeon bosses in WOTLK to NPC ID to determinate that they are in fact a dungeon boss

**Describe the solution you'd like**
Player/Unit Info > Unit Char > Npc ID - Allow us to Add Npc ID as multi-targets as a example below

Npc ID - "12340;05678;09123"

**Additional context**
https://i.imgur.com/gno7hJX.png

**Comment by mrbuds** [comment]
This is covered by https://github.com/WeakAuras/WeakAuras2/issues/4403
