### ISSUE TITLE
Can't export weakaura source code for external editor

### ISSUE THREAD

**Issue by Debuggernaut** [WeakAuras/WeakAuras2#4523]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hey team, it seems like there's no way to export/import the source code attached to a weakaura to edit in VSCode or the like.  Is that on the roadmap?

### WeakAuras Version

5.5.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

-

**Comment by emptyrivers** [comment]
Frankly I don't see any reason why this would be useful.

**Comment by Debuggernaut** [comment]
Thanks for the response, I've been trying to get an answer through it via discord/asking around for a few months.  It's strange that you guys would not see how editing code in a code editor useful, but I'll just put together a PR for it if I end up getting big into weakauras

**Comment by krazyito65** [comment]
Why would a feature to export it be useful?  You can simply copy and paste it from the editor..
