### ISSUE TITLE
Ebon Might Multi Target unitName Unit Count Issue

### ISSUE THREAD

**Issue by Saminymph** [WeakAuras/WeakAuras2#4525]
**Is your feature request related to a problem? Please describe.**
When using 1.unitName as a display text for a trigger with a multi-target unit count on a singular progress bar it will show all the names of the individuals affected by the aura on top of one another with no options in the display text to have the names not do that.  This is most noticeable in the Augmentation Spec with Ebon Might and Prescience. 

**Describe the solution you'd like**
A way to format the display text so that each unit affected by a multi-target unit count aura buff is in a list format and not overlayed on top of one another. 

**Describe alternatives you've considered**
While i could use a complete seperate aura to track this information in a seperate text box, that would require custom code. 

**Additional context**

![WA Ebonmight 1](https://github.com/WeakAuras/WeakAuras2/assets/139096390/36a93aaa-0121-442c-8f2b-b1a06caad2e3)
![WA Ebonmight 2](https://github.com/WeakAuras/WeakAuras2/assets/139096390/c1aeda57-6db8-4e9f-b3b2-7a61a93f9208)

**Comment by InfusOnWoW** [comment]
You need to put cloning auras in a dynamic group.
