### ISSUE TITLE
[Premade Auras > Paladin] 10.1.5 holy rework changes

### ISSUE THREAD

**Issue by isse95** [WeakAuras/WeakAuras2#4529]
The 10.1.5 patch brought a rework to some of the talents in the holy paladin talent tree and template weakauras do not reflect this yet so this is what should change.

### Remove
**Bestow Faith** - Removed from the game
**Flash of Inspiration** - Remove this, no idea what it's doing there?
**Light's Hammer** - No buff for Light's Hammer
**Rebuke** - No buff for rebuke
**Rule of Law** - Removed from the game
**Word of a Worthy Ally** -No idea what this is doing here
**Mana Divining Stone** - No idea what this is doing here

### Add
**Unending Light** talent spell ID 387998 - buff spell ID 394709
**Hand of Divinity** talent spell ID 414273 - buff spell ID 414273
**Untempered Dedication** talent spell ID 387814 - buff spell ID 387815
**Shining Righteousness** talent spell ID 414443 - buff spell ID 414444 - buff spell id after you got 5 stacks 414445
**Awakening** talent spell ID 414195 - buff spell ID 414196 - once judgment gets a proc buff ID 414193, can have both at the same time
**Rising Sunlight** talent spell ID 414203 buff spell id 414204

# Premade auras > Paladin > Holy > Cooldowns 
## Remove
**Bestow Faith** - removed from the game
**Rule of Law** - removed from the game
## Add
**Hand of Divinity** talent spell ID 414273
**Daybreak** talent spell ID 414170

**Comment by InfusOnWoW** [comment]
Thanks a lot, that's some very good research.

We do have some automatic collection method that unfortunately sometimes picks up buffs like "Word of a Worthy Ally", and apparently this wasn't caught when we added the templates. There are simply too many specs to do that manually, unfortunately it can't be done fully automatically.

You wrote that we needed to add "Unending Light " to the buff section, but as far as I can tell it was already there.
