### ISSUE TITLE
Evoker Preservation

### ISSUE THREAD

**Issue by inabelwetrust** [WeakAuras/WeakAuras2#4530]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I tried making WAs with my Preservation Evoker,. Such as making a proc for Living Flame, the procs do not pop up on evokers. I tried testing my WA's on priest and the work

something is afoot

### WeakAuras Version

5.6.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
WeakAuras 5.6.0 on WoW 100105

Aura: 'Ancient Flame'
Debug Log:
```

### Reproduction Steps

!WA:2!Dr1tVTrruCBzQqDLa1ykrLkqjQiIAauuvIsa1lbVP2jPYXoSEtBbKQ3z3D8odz9mlZmRDCfhATeIE2Fe2Jio5pbvr8byLfIZOCGRiLpb8MzTJAWh8((Z8()V3RCJQ9Rgwn81FAgnGZ6Wtfb4pU0muQIWfTtuuotAjg1UxpjwDWBs)7sFtPsLMIybG(J5uMYFV6TCR7mlGZJd5dzDgstWENVGTEyeMiqbgpTJJuHekl)EugvsSSHpkRXkbnkclKV)AI5K)LivIBH6J9MGsfigqjVR)wF12B)1BjaV2MfpYZbpadX)amkwrStbx5NeJgHfzA66NrLkjzwFKkGGLDi8HTzzs4tT4HOrYXYeCC8HHslhJ7TUqM6B84XcCp6zoDoUEZMxjStApq40U7vRJB3oU1CCTvJsWo60BZSqSpO3feioOEZJBCsZjPS51IvYs6YFa2TG)iEi(3lDj06Wcgk(jqHd9MF5YtX4KAqsfOCqq3ImbXO91uSDYVzJZXijUJsGzrkY7MVInJZWZcHORFrxDUiKyyggkhRFQoxYx3UpIYAKFFWG81Z)88Vi)lHVw)Fjq(lrkTVWKmOIDWr6X1dxoFLzaRpk40ibpLf(6BNuvHpt1vsqW09zf4IYjFKrO5VECbK1DLZjYxFYv6U3NjtU1Bz(E8yU4XLlxUYffsXX9myk7AN42o5dmcbOix3gcEknegZ1a2llce9mCOr4RMvGh)U5PZ5g9)yQur7nk)gzcUcQmxqODR2TQNVIakk9BYmpmWKgvoy3)D3D9a0D5ktMxjmvYTAiOVy1VnffcDh0QUUxRbSiIZmYgYfHpvGsg)05efjYaQK6hJ9Mx7V1UtYsh2QvDNU2TDDBFKZH7FG7SRcDh6lWFY8k7zxloATgSw7tCBEyR6)ZSOy(Wgc8pLIzbJo(DEWgBUDrvQvCU(VhnhPuzSMtB9m)uLIZApalGTMmT4Mg01hovtVO0MOzkMuvGFNdlM7VqcX8YRsoJNj0GtzyPSIXWobOyCfBnjXiOjfuUKjA2qxcli(emnIOELDmhfoWwcL9Yo9tJvuRlcIrsj0Xc7QxmwZxszrX4)4hYFULVc8mtTC(Zx(oLFYepB9laoRKQqk296w65y41QZ0AlSLKjmaDD3WwF)BYviW8BKC7fNW0aNhrLiyggsMszfaBWULhR37JAYJ8YJ8SFbN3VSdkoHGQKP4bdk2SVt5F9M3JgoRglGcbD1gXW5gXzloPU6V9gaZvYK17npIWjc4ga27YIPFdbyHoj97SNt96T2mLgoDh69BS)Jp8ih3V3hs9E0ilbLPJjMmTN2c4AbazR4m0SJKPVnqnNHV7AoWjXGt3Xzakofxz8aKGQlpF9vmCy(7vreqqSiS8HRL)ZKXjcoG2uJYhcSE5VuFJyJT2qpebbgCr(lDm7rJx018YhBuuv6S9g7SXdQo4pF2)9d

**Comment by MariusNHaugen** [comment]
The Aura in the state posted is not loaded because of a Load condition (Talent is ticked, without a talent selected)

When loaded the aura works perfectly fine.
