### ISSUE TITLE
Gradient Text

### ISSUE THREAD

**Issue by greevir** [WeakAuras/WeakAuras2#4534]
Subject says it all. I love the gradient progress bars in WeakAuras and would also like this to extent to text. I don't know if it's possible, easy, probable, etc. It's just an aesthetic thing I would most definitely use extensively, lol. Thanks!

**Comment by InfusOnWoW** [comment]
There's no easy way to extend that to text. Text isn't a texture. Theoretically each character can have a separate color, but that's not something I would add support for..
