### ISSUE TITLE
Add Hooks for Bar fill

### ISSUE THREAD

**Issue by sean-donahue** [WeakAuras/WeakAuras2#4535]
I am trying to create a progress bar for DH souls.  Similar to holy power for Paladins however souls is not considered a DH power.  It would be nice if I could use a condition to control the fill of the bar in order to do this.

ex.  If the souls aura is = 1 stack then fill the bar to 20%

If there is a documented way to do this currently either through the built in features or through custom lua please let me know.

**Comment by InfusOnWoW** [comment]
That's done by writing a custom trigger.
