### ISSUE TITLE
Execute WeakAura not working properly

### ISSUE THREAD

**Issue by RohhDaFox** [WeakAuras/WeakAuras2#4538]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Execute weak aura ignoring cooldown no matter what the cooldown is, as long as the target is low life enough to use execute the weak aura keeps displaying even tho it's on cooldown

### WeakAuras Version

WeakAuras 5.6.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Out of sudden death which procs the weakaura then disapears properly after execute being used.
As soon as the target reaches 35% hp weakaura procs then never disapears even tho execute is used and on cooldown.
Tried with multiple version of the auras, nothing seems to work properly, cooldown is alaways ignored.

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/139982340/37933d32-aef5-41c8-9f28-2a5971b272ed)

### Export String

```Text
!WA:2!vvvZUnsrq44nSAbFWkRtu0ccjI2dbehwbRe5gc5j7yIJYANmEYMWj7EMUNzAY4UB1Dp(NaxWsiY11pc(iIt(msGI4by0iEcYJqK2Zq19yNnzo4PMQRUQVQQVQCLM1huhxhF1NpNgYzD5zYqYNUwbktNWLDeAkNPQkN0jksr0h83N9xVBT1w7dwGyHW5hZPmDW(UT9D9kc58umFeR7iQG0xSryMsZh4tgRpvGrAsqM911RSZfhtsCmrT)uTKghtKQA7kxkE1gEm0aIQQJEIG4PeK00BuzbKHeM(yjjIo2R7XUhDKmJz15aqMpntr6LXO6(tXzsKb91)6IycJiPHDt4J6WUwzF1iuthsCm2gisrtiYcjbL21eN2qG)WT(ZcJZuRu0FQvSfwv9oC0nlcWXIE73ORFVU(n88NPUNdeBA8azmkuFp)4zVAHbaC2oNQqbPK5yO8ef5dPQ8a3JoU5PhnlJTSuSD(NzC2trwi7xQ81Cm5pw7wO(tKmu6BGIh4UF92lierdiyHApt6NmtrsJS9P8hdrrH0M6cjzoKdEKyt79l3oVwb8zak8IyjpJHVAtrDn046PsqqR68YUFLzwDMFE(o7i24EwSppLlpSsLkRFtP2vb1PXP(DeBAvAAqdaqfEgfRtCAaFER9aOgsWwL)srjX6hwgXRTN)JatIgnbsajxdG3WPCA3PTBEnjGBJnZTggAHX6vo47(9pX8S16LqoIZ0InAkPxUZjzimuaq747)GCCvelS6gXL4ZKiX0ZwkuCNFS9OoN6FuR2UlRb3Byq80wTB761ZPJVFNx7167pW)9xTl9sYhVmdp)bz4qQIc0GKGecnorFItkhHVQUKYmneX2EdYs10QI6gcvyksPGGInKQW(ZUtxFhjkKSD(HvNUK6g23rbb1OsQrPaV7Lg5BEOl2nqbbkL828d3(T9dkn0yNJ90CVhdYZXuGShc4yI9ijp163zIHI3FdzeYYRTYiZ0brzKNBbjFqas3xEjNrG5Oh5zHb4F5zn88A1XZyO0sknv58Q3wwRAkH5gJMGU775622BzFgEwqzrC5a7K(UlaXqIRz8sLiEgnMXLKL7WSADLsUuLSatvMz(wWUNhjlbSAppLgj1vdIOmQkPQd8sxvoE1MVV9)(hyZxTxMrXlWFrMtAq7gOrXITwTpZWkFf1ooJtCUKZhujFZK5AE4WYHZNv53(ONtXoUJjHEOurcA9frMuRR2Wix3BKze4eBtE)LofgZH5ys)aaQr04QaJW4nsYmeJwM27Lh3mVMddkQfRw61ZS0emdUfwDnbPmXGWI1jpzQ5lB5DSZaeL9M8A5JZ)58XbcjbY05wKDCwQIK)tpjFs(L5jnT2yebnGPZn(Lw(FdtxL)j3atPHxm5vlXqsDL338I9EXxvF4)E())d
```

**Comment by mrbuds** [comment]
![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/9b88f8f3-d452-422a-a18a-80d92ad1b6d8)

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/9274fe1d-959f-4fa2-82f7-0eb96f80bd40)
