### ISSUE TITLE
[BigWigs] Tri-state for Explosion timers

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#4539]
**Is your feature request related to a problem? Please describe.**

BW introduced "Explosion" timers that are basically bar timers that count down when a debuff goes boom.
The only way to identify them is by the bar name "Explosion" or "Explosion (1)"
Sadly those share the same spell ID/key with "actual timers" (before debuff application).

Currently there's no easy way to exclude Explosion timers, especially since it seems to be localized(?)

Here you can see the issue: https://youtu.be/bDvnGxYkklI?t=60
You can see a countdown "Debuffs in 4.." followed up by another countdown that is triggered few sec post debuff application

**Describe the solution you'd like**
A tri-state similar to BW castbar that allows us to exclude Explosion timers or just always removing them since those can be done with smart group triggers anyway.

**Describe alternatives you've considered**

**Additional context**

**Comment by mrbuds** [comment]
I'm closing this ticket as you should open it on BigWigs repo, and after they implement a solution we can look to implement it on weakauras, not the other way around.
