### ISSUE TITLE
Lich King

### ISSUE THREAD

**Issue by Hliproov** [WeakAuras/WeakAuras2#4540]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello,

After downloading WeakAura, the Lich King is appeared in the center of my screen and I don't know how to get him back on his ice throne.
Could you help me please ?

### WeakAuras Version

Weak Aura 5.6.0

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

The Lich King appears as soon as I logged on

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/140102778/b07339d9-4ee6-4181-8de6-5b2f72a29242)

**Comment by InfusOnWoW** [comment]
You create a new model aura, which by default displays the lich king. You can delete it in the WA interface, which you can open with /wa.

**Comment by Hliproov** [comment]
Ooh yes, problem solved ! Thank you very much for your fast answer
