### ISSUE TITLE
Timer Text bug(?)

### ISSUE THREAD

**Issue by aciabob** [WeakAuras/WeakAuras2#4543]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

So I want this WA (https://wago.io/WtwVFVDU9) to display charges left if stacks >0 (from Text 1, %s), and I do this by using Hide Timer Text at charges >0 in conditions. The issue I am having is when it reaches 0 stacks, only SOMETIMES it does not show the Timer Text from the Display tab. For some reason it never happens if I load all my WAs through /wa after logging in/reloading.

### WeakAuras Version

WeakAuras 5.6.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

I cannot identify what the cause of it is but I do have a clip showing when it happens, if any of you can figure it out: https://youtu.be/8Sa9A7e6jjI

### Export String

```Text
!WA:2!1v1ZRTXXE8OSKgIieSvk(zhEj4A4jskpcPUeFWqAqRTe2bhzZkPNtpPD2DhT7eVANjZmRSvGsPcknqHeqPn3s7dDOqHEP6pbFQxAzq0l9QVv6n)xq)oZUYXUKSh2zMVZ3F)97NVtHAL6wkOuWZU5iIpnPbnL7J)3NJFW2D6iWYc8(5BgJs8JO8DOKeP3AvR3SQZeFknoGUFsJ9jmSlBg)uHK2Tj(azlwasI9snlhoLVQbH4iBTDChi5KWqmx88Y88Tp7F5i5i)9SrPskB2ubUDiobZj(nIO7VDI7KZCCKawQeVpQVWonHi9yXO(y(yTC6Rc9dIowFWOu)iehm(OaWP60PzFgMVr1T2PwRTgky4446OU45l8J31wcx5yinqlSwZUhjs9W9WjYgGSKdg3ETknA2UrZkonheKYrscnP0hXttmmPUIJzLTWA5X9I7WPHCSqS4nBO18TyxvRB8biFz7tmF0eogf3y6Xr1iC8I2XiHCIjMMEH7aZ2ndefhPdMS0XHcZsfFjPh(iTaipbL79qAa(nbWoCmeaon2P6wBn8KKJRtcOxrXHPj51I5uZOMDCar840eJgxgL0NvkVaNXZw0qI)5zZImmKtuBUF6ChdnjyEck()bvyi58LhVhgZQa(TV0rNUIgkWXDmntQlCKqs83R)65zYOrG36GdHTIvNtTWe4Oh4LHCAAsqh1cd1eO8aOyNT0wqEk26W8d(0yk)bfkuW6OCk9icIxm2Dk7yOpKnBJNKIGmCT044f3nIiXtYVMA64TE21yLKqVm0nHGQ4JYbcSfmen)6q5Drad5BStOj4HNC9s)hXBHzw(ghjPlo4OmlmnzyxPvZTzx1qudda(i(7scKr2vGJhNPiYb4adXVysgQ8tZ9Tdn3)yOkr60xDHrCQeWFAaPD9TRxLDJ3I3ODJ8tfulWHCR((8qpt95HU1idT88RvbRH5AkroQ6bmDdoGgNCgzkCMC4u)KnZPiU206vHjgQ7dvHD5i2GDZ3KfvtlI5YEQXrQlW(G3vGbELpr3cAn5eN1G(3UvZT2SE13qTb0dDl2TExkkOpGri(TLrqCgb46(NjfLhzwErysyKSLDmff8dgGldl9qszmoYG40dj4rEsumGhl7jijHX4R70nnwsMB(c)m1LvsZNpG8fG2d0iFFxhZ5YQWXRx9HBxFJw6jWQO5u75ASspCeXpg3IezR5hy0sfDn3JoRAMtf(58mtVCrBnSzovuryqHESVhPlJYLSzYcPACyOG5hB2QX9ATzBBeFf7uPKMS8iUbGQtLQItGwvqGTzA4RO4GPZ7D56zdaPvCesexw0RdjHiIkAdlY58YgNCEyOSaj1OFC0YPKGX1EsSK7ujLfHn5IPZrHHlW0dSR9tP0U7yDNB)XQR4oss97LnMz(cF1LwIeWUUz05drH4vx8ntrxCnZBaIJpv4P9FVgR5uTADhumlcz5SVgy1ACh91nGXJs0f9GxS6qclYjjAlHHIHPN1c(yV)0OvdZwNiqqtAq0iqKaIj4xTSJFe2FVAQl)Fp3suwPpzqpeNO5B5k1x3ZCP4dxrDzl1lgrtMgTo9qXPylqmlJuQxw6oQxWZEjtOxtG1vlREP7agNc90Y(QlbhJuVs9EAYQxD4PDUYQNNzKdZEajXrRb1llO(2RbS)GnU)F(h6VFzJ7)B3q)T5g3)xFT(7VSav(1G85oZs37EzEJ6BYKfmL6ZgtsYWmquxEmS1hxv)OJWLnpjmHYX5DigQv5Ckx4oeLqYezfv)AhIrcDwhNekJUOAbL9KPpW2w)YmK81jwXanFMMpB7Uissn1RnCR(o13R()W6t)NukjCU7Tx523PuVF)r)9d
```

**Comment by InfusOnWoW** [comment]
I can't reproduce that.

Unfortunately your clip clearly shows multiple different addons being activated, thus it can't be ruled out that any of are not working correctly. In any case we would need better reproduction steps.

Uploading Wow_PQPk6OKwu3.mp4…

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/assets/12950521/d57ca7a5-4c05-4ac1-a80b-1552a947b525

**Comment by InfusOnWoW** [comment]
Ah that video shows that I didn't disable OmniCC. I've tried now again without OmniCC and the condition works as expected. The timer number appears at 0 charges and is correctly hidden otherwise.

**Comment by aciabob** [comment]
Thanks for looking into it.

I swore I tried this with just WeakAuras active before and was able to get it to bug out randomly as seen in the clip, but now when I try it I cannot reproduce it either. Maybe I'm schizo in that I tested it before... I'm really sorry for the time waste in that case.
