### ISSUE TITLE
Auto-clone bugs out and aura stays permanently on even after expiry

### ISSUE THREAD

**Issue by Kenobai** [WeakAuras/WeakAuras2#4545]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

This issue mostly happens in solo shuffle, I've mostly noticed it happening with monk talent "Zen Spheres" even though it can happen with Priest shields, renew, etc, so it's not tied down to one type of spell only. It also happened once when leaving Mythic+ and reentering the instance.

### WeakAuras Version

WeakAuras 5.6.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create a dynamic group.
2. Create an icon weakaura inside the dynamic group, make the trigger Aura->Party->Buff
3. Add multiple entries of spells that you wish to use to replicate the bug, select "Auto-clone (Show all matches)" at the end
4. Queue solo shuffle as a healer (can be done as DPS too, just instant queue) and just play the game until it happens, it happens eventually.

### Screenshots

Image: https://i.imgur.com/hfojIlM.png
Video: https://youtu.be/vc1a7UGoziw  (round ends, new round preparation room starts, when the buff expires on mage it permanently remains on mage)

### Export String

```Text
!WA:2!fA1sZTXXryJcrX0RSsebTyOuSDGvfPkmpyjtAXuvoKQ4scqrfqs4fGIsjhaMD3byhRfZmEMzji0LeHijZKu5fY748eNZjCn34VGUqLFb8G)bWFbPNDbOOvKRCz3EMUNE6NF9K7Ef0E3EPvx6wf6uiSq4rRmGOcQq5Tnrpz(t8fQqQYLe8WqLqkVSBm7rpIOclwxiInm5ysIjsO2vAycU2zqBLirUvGGVq()YNFeHhGmRkyCJ)6L2PEjVHTsIJxNPcIPnLxortxlteQApoZ0urcsv0QEAdrzC8BX4mDKJl(Z403OyTBtv6RDt1eYNnmK6N0Qv9EsQ6oLQuT8EvCn4cpsIISCFTKghVvO25eDIp9ak3udLMD4OgRVwT6nQvFnV6UjOY9LXKEuLhN0HQD8sf1)ousSj6SJwvrXJ6vRAPkvgKWNycoJceXjD41KKaAEFfjKLOFYR3hDUkSomtKhjM1MdZ4fBxErf6A2ZLBiQxpA70axFLOBMc802FxWnwqcl7BiX4fpVxNemA74IUtW8W3WXliMO1wkxn7rulXOSu16IyH6U5YLl)y)jzTSTYNpF183APBpGWzDi2O8QWRx(ykrtRzuP57xfMZLl40XHySZkrdBKuPPy(mu33kQnodR42HW4LHLXdaRaVhCByv8)LEXDuzxfnYthG(r(HbOVqvwDC9kE(zgC0WS)LcBtLZw7dtikAXYyvsX9Jyg6qvAeYEMJd7HzhwqAn2Ktvd9(lmMC(IOb7TZw1l7T22LwoHfoA33xv(9IouV5xBNjHOT4AQj)PmRTWjX3d9q8gEQC2m1uwHLavrRGJPE0ZX0f3uglmfkFV12yR9QnQLvemQrmKlDCMs3TvluRVgMhnPHUCdnIGdYu9c5(Ox76OPGk10ROTCv3VTIfMgi82yGLEFwOj6INEotWY1V26ELkTJRwOmWk(O10I12XfJaDDRuQCD1Hz37)u1lJyXH2CflRBCeJ3sOYs2od004wPTIEEBT5DQxi4AhDJHmu8AIeva9nFfy)CW9ZbVkmZ4aS7ou0LxRltsBE80L2CueCrSWXbUKd8fCGV4o3eU8Nmuhj6UEmw6OBIfaVbmp8LobR)30MPAeiWELi4ldVj8wWBdl4jTXb4AoWvCo2wrZAXc2lTh0Y4Dv4j3bdanTQyBIjiAIkgy7PtBq)hZE6AyuNBkUbTfLJXF5v3eRCczeErrRIiQcZY97X4T1YR4gt1AK0YQgjqzVqQCUZVDzfLgk68IYYdmOA7jN)8BxftY0uGQXBWoGXPfRfXOXHYcvfDPQI7JveFNP7D5QyVsXAjsPYQbb)KmH2I3kXUuUWN6gT4vDTocVTNhLt7EAj(b0yH0kW2mTzC6UtxnQcRfT46cmdXpPMmIInpOAUJqshxtimrtfeMfkaFfNrHm9hKGEf7a6YeEpSOpLUEgw22Iq6)6vGYp90hsPY1SjhJNT(jcExlCXl2Y)T))dcGa0AIXcOGLo38UZdZngX9Syt2(yE4rxtwWqp00qhrWAS7NvhNtE10nt)Kve3qpHawzWz8U(nWHsN74ph(7KSDNw07U2E13vox6M4mlHTRiiTPZDnC5Pzxe7qAwN4JNGP8GjMZXP8)GeTH1QhmZW02CADCt3D2DNsYV6)J1kBeIv2DiXnWeFaZMQZbZPqF3kL8DEjhWW6qFU05hMYnyk6D(btKMBgw6W0QPUKEtSZZcBNpw(Pn(dqT6JJDhNUQlwJUVIi7V)eIXNP90zP7Ux9kBHowwW98dYD3TE9D3(LKFKti83jPJp2r(2FwUy2QCp)gTO4VJCXpl5NG73WeHoDecf1t(wVeztlNshz51kwiuFY42XIUyJ9hMq5b9Q(5U1slF7SuGLXX2pBmzsx((2vwpFSFIXi47Iy34lcgA3o71qxzKLEAmDGDXztwZNYBAs4yl03u2rUwwrP2s9iwWdrqsD(0JxlDQykzfefrpB6T5Mnw8OfGFyo4hHnsp(63qd9tlQHFm8e4PWZGp6XWr5GFcmd8tHFg2U9ZHFzQDa)k4xd)b4pc)MCWGCWVd(9WVTj8NG)m8xZbFSNnCgc)TRc)9EWViVFeL1oYSiS4ZSVwPH9PerJSuiQHf6oAGDbhF8Jkc(62xzOMWbPVPxkvtxfHf2e(Mw2W3k97s43YdTT8H25OKMEz)a)MWknHVRRDSd(Sizejp8VBcF)5hHzXaAj7RSWripWb2mc(bWmYcObS(KPpi4eIfrB6(iHOtoy9rTRx(UlU)Dkv9E7bBpzi7W0HSnSdz96A7KxeUBE49bxOU14TtKPrY3y6enBh8gmnbBmcJ8EEVMfN0(IW0NYUA0h3F6bIGl4u4G)Z9)V
```

**Comment by InfusOnWoW** [comment]
I could only reproduce it once, after which I developed the fix. But I couldn't really tell if it works or not. So there might be more to do, but for now I believe this to be fixed for the next release.
