### ISSUE TITLE
Allow us to add Overlays to progress bars the same way we can add ticks, models, etc.

### ISSUE THREAD

**Issue by Kenobai** [WeakAuras/WeakAuras2#4546]
Overlays are a very useful tool to keep track of Pandemic DoT refresh timers as well as to more easily see when a critical moment of some buff is coming without checking the actual timer for it (when you see the spark closing in towards the overlay you're instantly reminded of whatever it is you wish to be reminded.

I'd like it if it was added as a free-to-use option in progress bar weakauras under Display tab while using basic triggers instead of being buried under custom->event triggers.

The feature is already present in the addon but as I've already said it's buried inside custom triggers which adds a pointless layer of complexity instead of simply giving the user the ability to freely add an overlay for whatever it is they wish to do. I think it's kind of unnecessary that we have to do this: https://i.imgur.com/oPqO6sZ.png  just so we're able to have this: https://i.imgur.com/2wNFjcl.png when it could easily be done with just a basic trigger and a basic "Add Overlay" button on normal Display of the WeakAura in question.

**Comment by InfusOnWoW** [comment]
Overlays are fundamentally tied to trigger states, that makes them both more powerful and less powerful than ticks. What you want is a differnt design which is not easily added.

**Comment by Kenobai** [comment]
> 

Fair enough, couldn't you add the ability to just color parts of the progress bar differently then? F.ex. coloring/changing texture between a tick and the end of the bar, or between a tick and a tick. Serves the same purpose as an overlay, gives the users what they want?
