### ISSUE TITLE
Range Check trigger runs continunously, even when no target

### ISSUE THREAD

**Issue by lassevk** [WeakAuras/WeakAuras2#4548]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I ran the performance profiler built into WeakAura, and noticed that a few of my auras was running continunously.

Common to all of them is that they have a "Range Check to 'target'" trigger. If I remove this one, they stop running until other triggers change.

I would think that a "Range Check to 'target'" trigger would not need to run when I have no target. Understand that you don't get events that says that units move, reliably to only check the trigger when I do have a target, but when I have no target selected, there is no need to run, at all.

### WeakAuras Version

WeakAuras 5.6.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Click "New Aura", use icon, but doesn't really matter, give it a name
2. Change the trigger to "Player/Unit Info", then sub-type "Range Check"
3. Specify unit "Target"
4. Add operator "<= 15"
5. Close WeakAura window
6. Right-click the WA icon on the minimap to show the performance profiler
7. Ensure you have no target selected
8. Click "Start Now" in the performance profiler
9. Observe that the aura is continuously running

### Screenshots

![wa1](https://github.com/WeakAuras/WeakAuras2/assets/1311683/df4d4e8d-f03b-42df-b275-c7c994bea10b)

![wa2](https://github.com/WeakAuras/WeakAuras2/assets/1311683/f66b1c9e-fba3-4ab6-a2d8-f768c5a55da1)

### Export String

```Text
!WA:2!Drv3Unoru4nkGaCrOTHLkwjUOQiq9QQYk1kbcUOoRZ2IYghSDPfjGKX2NypuNzmZmo9N72iHyVopc5AUkpc5jWkINGEX(a0NaoZyN2DXxyDMZ)FN57mn60ACR4wXV(lNtJ4mFEHic(IhjUYD0ijOAiUUwybHfLYf95uMkSTtVahVvrCEwm)sM)L0Cy4Y1hDItGuBD6govjOjjGq(jFTOw8n2QRZb7cgvL3QqcdiHsUi8yGK9sEmm8wzrimbyk)IrJOxTyq7J8dg4hCKxWTp4UXvpbHLa78nhmvBqNXHEMqx4PnSD7ui6cpgzmiTMkZHSStILwZ0oBI8HA1xayT88770TB5hhQiIeqDRXPb8CqquCXoF)pmpgcXUkabG4yNU97CA3zfSAGzLVjjsrNabvN1T4)8O7W5fiyKSFgNcuo7VU7caYpc7MiLhrr5PZKq2iZCT89XcijQcSEq6CS58Gemg53Tv5gRWJHKOlse8cw8RFsElfCLAGmLGZ8ZRVLYFQrP53iUymbDOwWMXzWS7nVZxjZF8BLH28mU4hB0OrZBR0UUPSp60a38p1OKuO4yQOrNrJvP2hHhVRQw0RGyJYxTQIO8l1D0sJ9)OqQOJUgbOGRqWfGkT752ZPCdbIlTpZnogzAJM43SAqWu5pUJGEZ2)ubjghmKTdcEhSVUsRm6UKlIptqYNEwTqvdmHkPHzWWAm)wK58npPxphVb2UbbUV07KxCCWQ7lTp9g4P1i683PoARgEG7PbDpPNZBwLKXVSJa(ZcGfDD)3B)9E2bvOtByP(3Z1xS49zZP6t6OxfwOuCM7eqKrUEUwDxGLOs)SfA51qBM(q77hnlrg8lwRj1459nNjZP0OlyGu20eOFejdAARftnk6srJBAQMnoLarAykqtsvVYoJtI7G8)mCPylVXfzkQLTMSUvzGLxugrk1s2sCWOfMlmmunwk)WNvqJx0N9TUUK0RoB39Nry0XgeFONe3PuDwcej4Regm(bLBuU7Q46HYa9ZccjGpBelNQ9ZK0DThtOSoL)MX7YFVCq5WYDdhrzuz6)x9ckRISJ5Zk)jRFqsZ2EovsqcqCQqVKI7uhw(RwLHw2yIuw23W5JBmxXJMuTM(5n(7pAhASDGJFG3dKYfJe4RjiaqEytVlneEZRyTRlfU0JB1WWqegJOjwcktNri9UksuhD8AGf632ZXPNhjlpL0CUg1utFznDDBpCfUVHX4MxzOL07G9oCV9Bn5Fp))(
```

**Comment by InfusOnWoW** [comment]
The range check has to check whether you have a target.

**Comment by lassevk** [comment]
So there is no way to first react to events like PLAYER_CHANGED_TARGET and only do rangechecks when receiving such an event has "turned on" range checking?

I just feel like other api functions could be used prior to doing range checks, and then just turn off the entire trigger until events are received that says "Hey, now you have a target", and then turn it back off again hen "Hey, now you don't".

**Comment by InfusOnWoW** [comment]
There are events for various units existing or not existing, but for simplicity reasons that's not something we are doing, nor want to add to the range trigger.
