### ISSUE TITLE
Add spell description to some Spell Id fields

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#4549]
**Is your feature request related to a problem? Please describe.**
Some triggers does not show any information (icon or name) for a spell id, that's not practical when reviewing what your triggers do.

**Describe the solution you'd like**
Show Icon + Name as information next to following fields

- Combat log trigger: Spell Id
- Boss Mods triggers: Spell Id / Key
- Aura trigger: it shows icon, but could also show name when input is a number

**Comment by mrbuds** [comment]
Preview of change

bigwigs
![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/8051a512-909d-4e2a-b92b-13e7e81df996)

aura
![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/393151fe-b582-4f2b-8baf-1f9bcf789213)

combat log
![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/52217ff4-7705-4dc0-9adf-cb48cbe866d3)

But i'd like to make it show real value when field has focus

**Comment by mrbuds** [comment]
I have same idea on fields for durations, to show a formatted value when it does not have focus
use case is mainly for encounter/combat timer triggers, show duration with minutes instead of something like 436

**Comment by InfusOnWoW** [comment]
This is done now
