### ISSUE TITLE
Feature Request: Cooldown Progress ("is usable") for Items

### ISSUE THREAD

**Issue by Raistlin1990** [WeakAuras/WeakAuras2#4555]
When adding WAs for the infight prepot, the condition for "not on cooldown" is insufficient. The cooldown is only started, after the combat ends. In this way, the Aura is still displayed, after using the pot.

With adding a "is usable" feature, like its implemented for items, this can be easily fixed.

**Comment by InfusOnWoW** [comment]
I do not understand whether you are talking about the trigger's behaviour or the conditions behaviour. 
Also "[...], like its implemented for items, [..]", when requesting a feature for Items, is a very strange thing to write.

In any case both of them consider a used potion as to be on cooldown. And there are clear indications that you didn't prepare this report with enough care.
