### ISSUE TITLE
Combat Time Trigger

### ISSUE THREAD

**Issue by JustusW** [WeakAuras/WeakAuras2#4558]
When trying to create helper auras for coordinating Mythic fights for our Guild I often have to solve the same issue: Get something to happen at an offset time from combat start or another event and then display a separately defined length countdown to that time.

I propose adding a new Trigger called "Timed". This should contain the following settings:
1) Checkbox: Begin from Combat/Encounter Start
2.1) Variable name where GetTime() is stored. ("aura_env.startCombat")
2) Checkbox: Begin from Trigger Activation
2.1) Dropdown, Multiselect or Script
2.2) Variable name where GetTime() is stored. ("aura_env.startP2")
3) Checkbox: Fixed Time(s)
3.1) Comma/Space separated List or Script
4) Duration(s)
4.1) Comma/Space separated List or Script
5) On Activation Script
6) On Deactivation Script

I have implemented this a bunch of times in different variations. The latest one being when I needed to track the time from the Start of P2 (provided by DBM, love that integration!), and display movement instructions if the player has a certain debuff. Sometimes I can use the on show logic, especially when going just from combat start by storing GetTime() in the on show script. A separate "on load" script executed at the time the load conditions are fulfilled would also be of great benefit as a partial alternative to this proposal.
Otherwise I usually end up using some CLEU subevents with adequate frequency, SWING_DAMAGE and SPELL_DAMAGE trigger often enough for the low precision required for this kind of timing.
An alternative of great help would be a "Tick" event, going every second/tenth of a second.

**Comment by InfusOnWoW** [comment]
There's already a general functionality to built on top of other triggers with the "watched" trigger. That can do everything in your list with minimal custom code.

Additionally there are custom coded auras that solve all these things easily. 

The kind of I want everything in one trigger, which then would be most complex trigger in WA, is a bad idea.

**Comment by InfusOnWoW** [comment]
Also I should mention the "delay" setting on the event triggers.

**Comment by JustusW** [comment]
> There's already a general functionality to built on top of other triggers with the "watched" trigger. That can do everything in your list with minimal custom code.

I assume you meant the Custom Event Trigger using the "TRIGGER 1" pseudo event. While that certainly does allow one to store a certain moment in time it does not address the core issue.

> Additionally there are custom coded auras that solve all these things easily.

Do provide links please, because the auras that deal with this usually end up having every frame updaters, which is ridiculous when all you need is seconds precision...

**Comment by mrbuds** [comment]
There are an `Entering/Leaving Combat` and `Entering/Leaving Encounter` triggers for this purpose

For phases DBM/BW Stage triggers are STATUS trigger, so there is indeed not a way to set timers from them without the watched trigger solution Infus mention, or you can use a Combat Log trigger with the same events these bossmod use themselves (which i agree is not ideal)

I did same kind of auras for my guild for sarkareth and you can see almost no code is use https://wago.io/21m_KjUPi

**Comment by JustusW** [comment]
So in other words: If you want to write an efficient WA that does not go every frame the official stance from WeakAuras2 is "go f yourself".
Noted.

**Comment by mrbuds** [comment]
If you don't read answers and start insulting that's not going to help your case.

**Comment by JustusW** [comment]
> If you don't read answers and start insulting that's not going to help your case.

What case? It's closed and we're done. And it's a bit ironic to complain about folks not reading when I specifically mentioned that I don't want to poll every frame. And you reply with an absolute monster of an aura that... checks every frame...

It's a simple usecase, have a weakaura trigger that's true from T+x to T+y but apparently it's too important to close feature requests straight away without even asking for clarification. I guess instead I will use my shoelaces to hold up a drill with a piece of tape attached that hits a button every rotation... Does that sound stupid? Yeah. So does using 3 layers of code to setup a timed trigger. Which is what I've been doing, what you're doing, what everyone is doing. I apologize for suggesting something that might shorten that ridiculous setup.

**Comment by InfusOnWoW** [comment]
You are an entitled asshole and thus now banned for life.
