### ISSUE TITLE
MM "Fortitude of the Bear" unknown with "lone wolf" talent after switching specs

### ISSUE THREAD

**Issue by ValeryL1** [WeakAuras/WeakAuras2#4559]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

While in BM or survival if you ever take out a tenacity pet (ever has the pet command skill turn to "Fortitude of the Bear" on your bar), switching to MM will cause WAs that check for "Fortitude of the Bear" to disappear; the skill becomes unknown despite "Fortitude of the Bear" is granted as a baseline for MM with lone wolf selected.

The only way so far I discovered to make the icon reappear is by a relog. Reload does not help either. 

### WeakAuras Version

5.6.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No Lua Error
```

### Reproduction Steps

1. Imported the attached simple WeakAura that tracks the cooldown of Pet Command abilities; it has 3 triggers, one for each type of pet. 
2. In BM or Survival spec, take out a tenacity pet so that the action "Fortitude of the Bear" is usable. 
3. Switch to MM, and dismiss the pet manually if it's not exotic. "Lone wolf" talent will kick in, granting the skill "Fortitude of the Bear". However, the cooldown Weakaura will not appear, and only a relog can fix it. 

### Export String

```Text
!WA:2!DvvZUTXnq44OeeuvGyhLuxf7auHueLFqRrQlIp0dfqRTCCQLTfwjxKEsK7UJ2LXRixqYv2khfqrZz)ii0Jf9GaAFaCb6zcH8ey0B9Mr7HERdPKCtQoisoC4hhoZ38TlSDPELIkf9MhnIfk4Te5Yq4Exro4GUDvGEHXuEyIq2uW46GnRVF76(tcfI0iXX8whZYas2sH5kTOxB4e9HzruneK7goBUF1JIHejnuZeC1g(knvQlg0LXzQKIE4GU4qTKfhds1pxvoB6B(yFnEOJ8O5AX55kOdnqjKb7jIaYKyGdswyReXXhWhPWHAPhthOoxLha9bUUPe6YoXVvZ6nAm2EARpXHrjxyx4qomHkXiBuegXD72Eqgi3PEJMBFyJtvzqA6(0Eq5R94h6PXT8DM85Onvrzo3DjMLYULfU3lAixgdTqyzNmUZM1A1UtR218B77SND3nNLAQ0ukILGsv5rTS4)4SBBXdobZwDUmisMibAAR5lZ(OTfsntNhbveDROtGkEavoX9kN7ezOB6lIufhzFEtJTZuUHAyTOpmmkxsTfLsFHxowfcYsPda5PxMGidTtTBronNpRUSSPK52vn383nlAwYSQ5EMpHynz(mZNBEWK9OkniFOQYM00uZdjMYM7MDhloSyUqcUxXUC8TNyUV5tnRrmRGj5NyEAre0FDoG2TCaoUPK1JMwXNgdZGZEBUs60cOImhKQiiJJyQxLZDpW1P8bzLMrpNg9neXSWRMDlQZHzgTuQF6kxGuCqYPPFlYdXSY3FXraKvdtJHAFBEk5ufK211kyU25knl8ObBnlfMmcl6(qSLI)KLnRobxgGPWyPiNh1DsGqgbYocxxvbZQNA33z7SzBfksfYVzHfwOW5ZS0NPybPaz8S1a2hj)IknzNaPZTPyVgkeKaS4e9Z8sf0O3SuwjxYjLQuDO8ilNimrQPPi1B9IN)(BunqX4XPWpUOFV8unBJ)ArYFSi5TlscMEIQMDFGPr1Yx)x(Bs5R(pFnXZDmZUfmnwH47qdxnER61AVZU7)INVtBtJLXL7DW(7COvWG4yu2ogzINuKcO7ETRT)UiSYTQTxTNJ(yAp1nhEepK(zDt2kevKWkFJLnVK4y49HewykCilz4mcFi58lP(h5ywtjCVtx0uZJ(V5LV(F(BE2K3YMgfrDfRSxaRxg2yLT0unVTLyBK7VSBvpT)HVOJhvUHxUwl4Rps6Q1wrdpRWPjImCUEh5ukh5SwAXgMIBFgqvqlTe4X6KByw1Jl4WK59EDSIlsfGyePgAD1IPjXRhLX32eJhWKyyMxzoch)W)Vfu8sr1wSGe)PuOc4V1ZzrJFupyNgINN297(YXDTVdmiOA6nYUZ8i1QzVftrrwwuIzjYiTiS)u2F5f(Hp4(SOS7UtUTT4RQ0e0v2u0RhsCQ06iwA6fVtAYgZbT20VE99DSV56ByNf26ae)Jzr6KN5ttZsOfcWhBxwCrjJBVnuoh14rOoiZ9jIIEVwi61SWtx7lhztlmN1vQ6hMaHhTH5Mfg2Nkz2OEKGp)Q87ttZHcsuuGJIcRu1mKmmtkWSREGP3ygVRqoTQuDmoneQB1IvKSYtvMMD7oR1LsHurKNm7ZGLu(pBTnw7PL6)2x(V)
```

**Comment by mrbuds** [comment]
I don't have a hunter to make any test, but this sound like a bug on blizzard's api where it does not return the correct spellId from spell's name in the situation.

A workaround i can suggest you to try 
- type `/dump GetSpellInfo("Fortitude of the Bear")` in BM/SV
- note the `[7] = xxxxx` it's the spell Id returned by API
- switch to MM spec, type same command, note the spellId, i guess it will show the same
- now log off and back on (the workaround you found), type the command, note the spellId, i guess it will be a different one this time

Then in your aura, enable the "Exact Spell Match" option for "Fortitude of the Bear" it should show the spellid for BM/SB, duplicate this trigger and use the spellId for MM spec

**Comment by ValeryL1** [comment]
> I don't have a hunter to make any test, but this sound like a bug on blizzard's api where it does not return the correct spellId from spell's name in the situation.
> 
> A workaround i can suggest you to try
> 
> * type `/dump GetSpellInfo("Fortitude of the Bear")` in BM/SV
> * note the `[7] = xxxxx` it's the spell Id returned by API
> * switch to MM spec, type same command, note the spellId, i guess it will show the same
> * now log off and back on (the workaround you found), type the command, note the spellId, i guess it will be a different one this time
> 
> Then in your aura, enable the "Exact Spell Match" option for "Fortitude of the Bear" it should show the spellid for BM/SB, duplicate this trigger and use the spellId for MM spec

Everything is exactly like what you described. Somehow BM and SV have different IDs too so for consistency I added another trigger for SV too. It certainly seems on Blizzard's end. 

I appreciate the workaround and the immediate response!
