### ISSUE TITLE
Integrated TTS Support

### ISSUE THREAD

**Issue by kensylvia** [WeakAuras/WeakAuras2#4561]
**Is your feature request related to a problem? Please describe.**
For people that use a lot of WAs and like sound cues, you quickly realize that there aren't many amazing sound options in the default addon (short, recognizable sounds that alert you to a specific and unique thing and don't have long run-times).  

**Describe the solution you'd like**
I would like the default addon to have a Text-To-Speech options integrated into the sound menus.  

**Describe alternatives you've considered**
I have used third-party sound packs to help mitigate this, as well as an audio browser (coupled with wowhead data) to find additional in-game sounds to use.  This works ok, but IMO is not as good as having TTS as an option.  Those options also require more effort, making them less useful for less advanced users.

**Additional context**
https://wago.io/T0nQ2j28P/4

This weakaura manages to use TTS through code to read the name of a spell that is called for in an MRT note.  This is **_incredibly_** useful.  I would like to use this same tech for things like WAs announcing when a certain external defensive CD is cast on me, or when someone whispers me to ask for PI, or perhaps with an instruction for when I get a certain debuff.  I think there would be many uses for this.

I think this would also be a great accessibility option for some players also--imagine being able to have a WA that tells you when certain spells come off CD by saying "[spell name] available."

**Comment by InfusOnWoW** [comment]
We already have TTS integrated. It's a chat action.
