### ISSUE TITLE
personal default font / texture

### ISSUE THREAD

**Issue by qpa-pko** [WeakAuras/WeakAuras2#4563]
It would be nice for the user to set a specific font and texture which will not change if you update and import an aura/pack. 
You could uncheck the display part when updating but I find it not feasible because it is likely that they changed important field like text / c within display. 

You can select the package but that are still many font fields you have to change and 6 for bar / empowered texture

**Comment by InfusOnWoW** [comment]
That's more or less the reverse wish of https://github.com/WeakAuras/WeakAuras2/issues/1129, though you are both describing the same problem.
