### ISSUE TITLE
All imported bars are blacks

### ISSUE THREAD

**Issue by cedet6d** [WeakAuras/WeakAuras2#4564]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### WeakAuras Version

5.6.0

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

I don't get what happened. Usually, those WA i import are fine. Original colors are there. But now, even after uninstalling weakauras, deleting saved variables, and reinstalling, bars are always all this black.

Hope someone can tell me what's the issue.

Thanks !

### Screenshots

![WA2](https://github.com/WeakAuras/WeakAuras2/assets/141950437/e765c5ef-c58f-4f0c-875c-b05b8d6ec898)
![WA1](https://github.com/WeakAuras/WeakAuras2/assets/141950437/d047bc67-8ffd-45d2-a43a-8751dd471624)
![WA3](https://github.com/WeakAuras/WeakAuras2/assets/141950437/b2bf88a9-030b-4b31-9ac0-b04a99b5896d)

**Comment by SpatenLa** [comment]
all your screenshots have other addons enabled. can you send screenshots with only weakauras enabled?

**Comment by cedet6d** [comment]
Sure, i did try tho, and it's the same issue :

![WA4](https://github.com/WeakAuras/WeakAuras2/assets/141950437/397c96d6-f0db-4699-bd6e-51c7b7488af9)

**Comment by InfusOnWoW** [comment]
Can you inlcude the auras in that screenshot?

**Comment by cedet6d** [comment]
Like this ?

!WA:2!TV1E0XX1zDpERXnBAk2kXkXkXUBvsuKsTLLx9WYoXrDxPvELJELrRKFL0DMDMr7m2JMz8DMvVsdHiscgkua1xeGMgwk5pAlHgbhkpkPjkPNcbO8HcnikW5qfLWJWH)WN20Y)WHVV7mZ(qs2Yj25CSpK5p2D27CN797EV)(9777(yfgRgxX2BUJMBPMjQrTg1ZDxo1OyB5XSnn1u7w3WuLPznRtnP1Kn90JLuMfBVX6HvWq1zBdiBjxDkIY51QkLAszPXYptvPDtDBpro7ydBBy55wk1D0RnBIyRTi7w21RYuwjNntvJLuw5mQmBhNTL00y2zLzQXYyBB6z4KBk58291Z8dQXAHnTTx3SPhA8XD18eyZeCZcYwk62mUfepZqdVGFz2TTPn7OcccrIxGz6Ch6EEoUhAF7JkWMnS3x)fM2t32LBghJj7PVV4hKjR4zyB52HORNmZlAUXnSmC1JMe)Yl6CEmJ851yU11al42NSOQwUcJpEMzC0yPt1)W9oA)j9WFikxGjhFoxhntZ(uDJUIBHCAtQz5ncMBJPxiB3jgjt2rYKqmtPhnmtdFK4idNQ)(twaRXCoMYZOXe5pnN)GMOL8eAUrNVGvGje98y7wJzjBogAAO1)eZlBzmHm1q6aQT3f1KD1gXdh4Z7PVvyxjTST0wsfnpkhzjJL5QHWev35OSsnfyVjNq2WQxyp4la7fAg2h0c(9nV6usQQ5Q4C7diRQfl3mXc6tXrxVPm8u0B2BY9z6NgBsFR7EkInxrT8u3C0KM2YQ9M01ywTAfNOaoGhnj2LPul0zurftzxx6UCEYMyhaD7s5cqk(JUrIez4iT0C75CTlWu0YzmHJnZt0vbFHilQuW1ZEIeC0XMZ5Jk0l6)Dk18AoBFKZwqMPfR3cMMXoMUHNwrg3YO(aX8m7cobzFe0c3IZ29rA9YWHGHXx0YtFr)N7dfVUCUAtGTZCXBULMJ3rrpBLGw97FpFI6r8)2f18T0smLfgNkmC4r2toY5RO8jti3iDlMk1G5C4115l37YF140RF62sT)0n2)aw5BlhogoUr(OZ7QzooNnKR7udMjLyaHOpl0eJuKgPn4O8OlyynoYt5aHAxaVvrlfb1CLwsUawvSHC8ZynkV656AoBSXGas36iwv6U(7FQN6f30M6SObwIJWBv32MGpOa8tkaBdgBjx0QpJOThV0fGBeUPKuo155pRs44xKv0SKZzQDeMSQb1JcJcBFUCYb830D961sxNiDxF)pnD9jt31s1qxBncY9CL9iGSM(I8QZFy4eco3y(GIBig9j3gkMEiX(o5qdMjr)qhp58fC1YYHyslr36O5Lt2ZZutN)elKZX0H7HaDWb4FEOgY5AyL3utShXr7RhkPd2aC6TcDw7wLyZISkKOV5vCNW22tFyMDEMgw4oBdlUeQNgXIAQAQdyyPd9Wi1bSnUqqxQIPHJeZtBAS1OjoITPHQFdkJFson2hXXhxwr7bjju0mqr0hC0(2B5FT3rOxijoWzlb3pc4eLnD0LJuKxqL4lrQSN64cWhaUbyyO)I(KfQ(MwO1XlyXfcBSPOXWltBKqfZn2HJr2DwnRjBg1h90Q4H9FSe4JPpLTuPVpv9CqA9pumBwSh(r4zL)HX4vMTMh1rflj0(PQoMNUMfpxLlzFeQFH38r086MJYBSEwivQ(MAwNlnMf7rB2p7LkJs3W0WosR1wLn628KYMf02tm3MrLqfccYlT9euZ(DbAwQLBcbLvWBgLEwuNTxfGFaBvTKjgnZqWo)Gna19wOO5DScbSKrTkwo6XsScwCLDOWC0tifFP5cfMRz)lsj6QBpv32UEsqJrH6HBFEh7P0yKOTa8HIc3bCNqdWDbXGpSpko8PsWTc3g0eAwKlTj1Y47SGQ3iWD)eWhHCnSA599VXc(oB3WDyg6EHntOwMe029aTF0AHDTekTtc0KYPLAqcyVOMFctUKVquwBFh3H)0x1loo6b7AEQi4jhOSwwPqiiyHStA4AGkgsb6Az1qTCO7WFrot2Y52TZUj6uw(h(dKzDY6zmHwWVeMV0ZR)ovCIDHY9e2QzjfgjNDUozX)grkNQonDHkd1zqN2gkz90rqRUTP6mRWZvjHAymNBKNcXEj9yLJzO6PNmb(ZZ7xGgtRPYt8XC2M)lRlRsyJWOCwh7tj4gyVlYtMeHmgFgySImcMQr4)Kdo0GPCUJlKPBQLxwzMSJBABZKCQPIA(4(sirMp4TS8C2wVmJzJ9afKvj3zXYKb2fdhpPmSuPCXdvAOrZ0FFdMQip1Y(cwVUWk5Kz54iEmlICtYPLn4fu1uqWQzwhgEd5jwOQgXj8Be32MCAynf0(d1d4KQsDL(TKPqWgg1OZChl4g)E4qOzWyufrMUyFdoykXS(EKD(WxO(7s2zKL8F5aluOChiflYUcEAWGGGZDUb9d(jMBWctKdJprxZiVUxtRWLSsIbxPscdXt0tpR2DL806WHH7Z3jch)TJ55oWDnu1ef77iPZiYFM(8H(SJJdLcrwGNAAEfD4f8dn5i8iQklwd7avH6iNVRNnpVQDw)B1lI3Ir56ItarhU5OWT0a8YoFKsoF8dsR5kku09q9Ll36JcVIuYzTTNqa6dokKjAG1yOQQzjoyQXsjIHJbrGbIiof1OYStyqyOZxw8QeVkDxVwRT(r30MUrMHffmhAqIl0BMJQLZPv926T1fSlhHbmoC8OWjAaoPKZTyK3cv(cIGIhwvkgZM5kbNk656cEWQJIcEOkdEc(y8aMGS6GeNyaY84IGCyarFXBIUAjDx)J8RVC6U(pNLU(CrafDqva0q7OJNeYlb66GXQdIbonCMQJDbm3mmHeqbMa2GJeCwGbUa6xYpqcyYiWu(MX0LcyaMzAHMVwloHjWjKELkkbUQWBRGeGhg(4WoF6WWbGhrc(PGcWJkb)01SF4XcDXdZv21U4WuTqU3HFMqx647pjdzPdIZsqIY28uVnFAHhk(b6OZKT3wNhi5b7O12y2tznKL5mslHMOIUM7iy0edzTKl)RbmCP4zrtz3bL8cQgUNMpKoPgs4QjiMq)qh63oVHIttLgYdAZbntVtf)HIwv7hE8lRanGNOCCfWtsF8ZojCob4Nd(5X7)eWVapKa4xuc(Kq3WV0wo3Tc)YcWVc6lhMxc(Sih6Zb)QWt9yWVoww)g4p)8WtdliaFMzGpf8PXI43cE(iWZ6dR)nHIWVg3lk8LqE4xgFLVc87aFr43g(DHVk8CsWZeb(92f87laFbj4R1e8hc)rWFmxze(t2b81H)u4f0HVbx4dEXddV0CHinFjo4L3m8k6W3SSywJBGyw47xpQKbFRqzm4pd(ZjHR3hkCbVQVOf8xuLmf8xscudnEBEJNJDGHAQh4BxHSe8xZLFUV1i)eqSrfiS9eicHQpKQeQfraxspAvv1o)yBmwos5Wu)BwdoME3DppFrsi08TS5)7haET7g(oWRdljb)DslLxZsJzO4JBls42eMtHtbLkXLyOG)iv(U8qGlvA(Msdo7SBBmKlKkelCszXAK)An5SD6fQQo4nd(maXPKRCMaBTw47bRaF34YMMWJ)v2uOO8lnhd9qXhMjfXlhO(PIIA70Az0z6UEPTJxB7Ps31xDB01DX11jCuTVDqqHMghbjZDmCPtMQlGm5WjlvWMq4FizkGWGekIm9mvrME(QjsibI4ri9JOu(eP55ePa)kD8huLVQYEPYlLKzBQrPoxWORc3HvG7R6KM3zsh)fik0hxa5K8xse0aAjkMqogl7OdfNq6eN8ImlIGHmxY1hrSQW9hr42cr4q3GeFdDqkUWuZEKHowNgnjF68eJdzORMM9c6xXOz7(crZ0lrZ26fJMngxJ)1Qd(B5PTe3Rb(isIoekxuJV2Ux5aZrs31)XbPRmP76B)001ZwciVocI39gaNlBExBaOFBg)17cy2FIvJzBPNjp((h4(fhDIMUWy2dLedaEQCDp6izgAayZN0zhvSa)X2F5v4VYKJV(j366NCBRFYThMmefU(qAsahPg(qZCOLnIJSIweonHqsr5aOOWoRdX5pjhEtyDKmqKaIAeUejitbJWbNRzHjS8lKC0AewW9X)aKYs)gty4V4JIYMyS7j7pvVzYr9fdzXu0LTYRPsZ0rrBlmmOwkIibEakrFhtvMlpZqLMoC9I9aD0Bac5G(4e(N(ihCq)ElTu3WXIW8xFFn9GfTd5it58QLcmZsBQHTD9xI39eZF5FcwW9MUsejovD94VIgHlbu1XJFbY0gByu8JuCYDfPifHTgJ350ViKqhsI84EwmyLu4lnp07ws6AZWPKlAsdE3aN5mqKv0Njh2Xgwvl4)ZEnWHTvqrfCWZYRxS2Tz5et0tFJosXXlyA2TbtbN4oK(640Qqs0wjXW5Pbk(KFVEInnVmtPF(2P841I0QUtOM4S5mmAC2XjLVmrppzvP51AgAPThdElD4hQd)yD4hOd)iDoLRwKYnhlC5XXjeIoe8Nd4cYbt)gN8nkYx9mcdCn8D(F(MORHgxNzh(MpmD9aP7AX5XRp1ot31xQo6QRlRzhQhkaTotnmt0I8vWzeAQEBU8ue3A5gIHvnT4p7NsrmoFPLRup0Lg6CJ8Ef6s76cDPrU6UKDP9DH)9l7zEOZj2h6c6BbhcqFl6b(wknFajoaK0MdCcusxffPrV8V0IkKCh2QP9kLMXaH0qz4GO6)b8O6plxWwCH4hzYe9F2zA5ODEasT2p(VxPSdZ9SbomRSU4Um5I9hQbrCIGkNPxOUi1B7u)9Eyr(8tRP15MuMzqWvr(OsGMNBDnSSWUQfRVXwB9foOtvx9rpMM8zsG5XT5ruKT83iPgRhfdYo6W9KitQSjtiw)EkT0a7j2(3tS2BAohMTdTM1bIzk2QADSSWTfAGh(Wy9xtBllS7Lf(q5mnSoJMQ0YcXkzxzV42LUrEDtArOENAGllu)Yc3(AnP29nPLfUJQmNtEXnhsQ5YZscJnGVksLenwwyh1e)QgTcPlSwXYc1wPgXYc3mYURwAyzHB5))OjSSWoxRsWpSkLGEh8a5hJLm5qtXcvcIgkdSSWTwb3Ucq69YbPTgcsJ9Uipo(fJM026ttExK1g)QgwB8lfwBRxJYAJ)ES2vXAFRQyTkZU)E80h(KdD2ZEvjRT1RUyTTEvdRT1lfwBBxJYAB99yTRI1(JQI122X7i(jAr26GEh)QswBBxDXAB7QgwBBxkS22VgL1227XAxfR9hxfRD6tmAIXmM54EXtDvjRT9RUyTTFvdRT9nI1EL7arCX2HjzfTOW)LEf7R0HKKKG3eVN1tIbsCKuIi7DzHoLcO2R54sGiteJw9PLOAIC)L3()ZvdXAFmF23CcHuuAdEisnsN5hdNSvEsd050BIuhS22iH)rLwSYSu)bBXzhvDMLOvwr2ZMHy9QeaoekaqBY6Afb(h2mFdoFxviO6TMb(AxFLBN(Q3XSGT6OI9wh(Nw9gKrsOK8qbjsA49JccjmINE0mnE)N(OPQCRYpvusEG2bfUCWDxj6)(i0F9D2ch(Fie(Rxj8pZ7cW)kOGDa1DBBkuuA3fL5BYThRG2QPHdFfwBkK8vs0TkTtNM3GfzKo9lzlDwfOJD15(O0qyK0D9gtsxFH0D9x95PR3mY6ZOx1q5Az3VXRtx)RP76vcp)3b3ebIdTwIE)zlZT93bL8y)2bIsuAIgJC3qgCi1Vw2Xsi2)qDF)Li1LwLBh9sUMFHYUMfxy)n1YXvup(4hu)ORHy)CeXU2ZhEOD7hhrSuMrNtz)ER4FKBcpjc(e)BOsI))SaNvhSbVnKKoy3Ck))Ia89Lis)BiTav4LogAOaW)MefbaNzpE5tyCjWd)Puf0qXUlDQ)dy74R8S4R8Y8Zmb)yi7FSHByXU1L9InG)PVJN5x2PZvDqVkFQZ5)xfo0Owe8W1tJLW0maZ1eTvol4VOUz1nu1Gxo8xunHQCpQK))7fxNDmC)jorkXS8dhzFdEKShBiX(7jiUf6CxyntOY0lnNcw58TP(DQcL)HbCad6445RvDYl1TrENL2gz(Hm6JVo7IC4Pl6ZmtL7F8Z4V)XbBXC4wiVG)HcLFmklTzY3kTzYpFKZDtRZj61Q0XqLScRWYRclblLqlHSIkmbQ(lDQMk6xZ0MCYpBt8k95w9zBIVPdZPAN1LotKL37HM2O9EiyiIRiqoZdKV)6W)l5AjiqVxSj0F(5d)xLe8xDOoK3fS12NkkjNFDKt8k0Wj1BueVWQdPd1nxI)pHIvWXJoeUOIPqo(MD4E3D4NHLfobLkjMs)mjXkRuDD0lU6AblScUCK5BGK552X9TkH9Lf6YpBn47nW3ApfzTuUqLR6HjlRs)TO9cU1AM899i)Fd

**Comment by cedet6d** [comment]
Ooooh so i realise that it's not black when imported outside of the group...

Don't mind then... i'll find another way... Thanks !

**Comment by cedet6d** [comment]
Well, here's the full aura group : https://pastebin.com/wB0QpN3n

If you could tell me why bars are full black, it would be great, thanks !

**Comment by InfusOnWoW** [comment]
Those auras are made by Luxthos, which override various settings, you need to take a look at the Class Options/General Options auras.

And for further questions, do ask him not us.
