### ISSUE TITLE
Implement spec check in triggers for target/etc

### ISSUE THREAD

**Issue by Kenobai** [WeakAuras/WeakAuras2#4567]
It is very annoying to not be able to sometimes have WeakAuras trigger solely based on unit's spec.

To my understanding Blizzard has recently implemented a way to broadcast player's spec and display it on the tooltip. If this is something that is accessible by WeakAuras, a spec check in triggers for target and other units would be amazing.

I've included a screenshot of a random player in the world while I was in war mode on with 0 addons on, so this is default Blizzard UI - it has shown every single spec of every person on tooltip upon mouseovering, whether they were friendly or enemy: https://i.imgur.com/9yyAVwr.png

I'm not sure if this is just tooltip related or if it's usable for a trigger or not but it feels like this was a recent addition and it'd be cool if it was implemented as a trigger.

**Comment by mrbuds** [comment]
> It is very annoying to not be able to sometimes have WeakAuras trigger solely based on unit's spec.

Most triggers where this is relevant have this option already.

> To my understanding Blizzard has recently implemented a way to broadcast player's spec and display it on the tooltip

The game may have this information, but the API use for the tooltip is `C_TooltipInfo.GetWorldCursor()` where localised spec is in data.lines[4].leftText, and it requires to have the cursor on the unit to work

> it'd be cool if it was implemented as a trigger.

Already implemented
