### ISSUE TITLE
Action Usable aura not working properly

### ISSUE THREAD

**Issue by GermanOrtega** [WeakAuras/WeakAuras2#4569]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have this simple aura for showing when Execute is available. Right now, it is showing always when the target is below 35% even if it's on cooldown. I even added a second trigger to show only when not on cooldown, selected All triggers but got the same result.

### WeakAuras Version

5.7.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

2. Import this aura in a Fury warrior with Massacre talent
3. Search for a big target, get the health down to 35%
4. Use Execute on it, and it will still show as usable even if it is on CD

### Screenshots

![WoWScrnShot_081323_183416](https://github.com/WeakAuras/WeakAuras2/assets/7717155/fc5e2fca-8197-4eeb-817e-f0e36c454bed)

### Export String

```Text
!WA:2!vvv0UTrrxyCnvfSQqTMOqAfseHer6NlG0aeex6nztBkj2L1RB7FUX7SZEwVdD9mdZmRtCUbHLqKlqcH5baj)i4hH(eSYINGCdxtEc4mZAhAYfzN5mN5C(oN5774Ah0CyZKMjxS1mgvW7kkuu4dFRfKctMq1rAycUUHACN0unyUBJ5eofp4zcg3eVNF7q)GfuHiprCkV7PmjejVhTqBeddHZm9Kjedex4(86v(5NmaY8SPlAIrXgmau63Bl1YLx0CssHIytCZhTyaWbfJ2ntCAh(LA3N9wgNaoziOF40UgIsxOgaZRYC)mwceyydHepZyjeOLqEUQGdJaUXdlnXScn0VkArZsqeMMgIEQEsRGJpO3rbopx0IArXM90K4CyI9kfCMjAHci5DTXSncaL)zaTWalCHCL1OjULhMOBiVV9KBuirxQlID54zkiLDwq3N5F0rxBSlch2zZ7VxRUH97g2ki0ZM4yzozmOMEDs24TFYFoTGVSXTE5)BJB93c59jiShbHvwpwKa1VcFTafNK)CSvJL0pF1Raq2cde1eyB1ztjC2qxtF3an2pnhuUMhxWHfREm6BBLknGpBj6xden01Oa(at2DMy3z7FLB7nKW44Dl3U8rL7u(f3P8ll3ooLXz6SN7mB3lvaYMMhlk4uyFGsgB9eVWLAdJ(QX7VmNzZWwsamWsc)01lxBbUnMqF1afEZKlwt20GSm8HKG8HxwXrRn1zZ(Vp(tOY79gESNixOEATA1QFzLvip1XK9A1lSJ89DgT0dBNG(cwIjZRfU9k3b4tcK4m(tlQub))Lz81UZ)EK8XshxE7zkHb57wbGx7oT9lxdPNXwFM5CK6GrD8VkOMk4g59oqXoFZVRGKGLozZWWBuBRY0cNTtfQKxOiYjVy5IkamIPzirnAzn)gkv59pSDB)G(EDcd7CCWHp(jHYhCDBcbGcR4(0Llk3EX14Ql7C4bll3xEdqyp1Pz60l8OdB7hNbSbzMXE5csYfnvmU9vsUEWWICdRXuRiWQavzYM210CIwJGmXkAOztV2wKNsKdRxEsJjlLu0ipnIJTI1yqrLyAoCMTslpjTmok2CkQzghTJbqXC1MuuaenblhZ4HeEuGez0JJugsoE6oBvsQxEY6BuFZlJU8M4ap6hlpz3)i63I(DmYo)rB3U8KTCU)oJ(hemvoIgFio9GHIvkwJJTq2trOoSpvoswDD7ovkXnlXU2n7HkggtmrQZrjgoK4wboyGb174wp2hbxW(b9oC)Ozkh73jUA4ACRM(HcBu6crb)hDAYQjSrY1wT0Yc3N5MGLKPQqHE3YpVr5Un8qzPPH6SQ31F9UXO2oLnOH35cXWALFa2nf0rvJm2O2V8UFmlP8JUQImCGchazHvC39c89Bpp1AahjGS36bNALjJdi5Yms9DkyjZ)2J37rpTx23is)bKAydkKn9AbikASZvyv)CZCgVIjI72AoUKc(25I6i5gSbCHcw(dtoR(kLqPTJX1eJDWbK1uh8vF2x)zB3C0F9Y)9d
```

**Comment by mrbuds** [comment]
It's a common issue, but a bug on blizzard side
Tick exact spell match and it will work
