### ISSUE TITLE
Add the option to copy display items to other groups

### ISSUE THREAD

**Issue by diffins** [WeakAuras/WeakAuras2#4574]
**Is your feature request related to a problem? Please describe.**
I imported some class-WA from wago and want to add keybind display on it. I added text components in Display window, configured it and want to copy this text settings to other group (icon of skill). But now you have to create the text again and manually transfer the settings. We have an option to copy all display settings, but this replaces/removes the settings already in display window.

**Describe the solution you'd like**
Icon of copy display's inner element. Like duplicate. And the button to paste it in header (or somewhere) of display inner elements

**Describe alternatives you've considered**
Copy all display settings, but it removes existing elements.

**Additional context**
![image](https://github.com/WeakAuras/WeakAuras2/assets/40886578/121be46b-f60b-4912-9fc0-1f35978064f4)

**Comment by InfusOnWoW** [comment]
Duplicate (or subset) of https://github.com/WeakAuras/WeakAuras2/issues/1303.
