### ISSUE TITLE
Slanted Progress Bars

### ISSUE THREAD

**Issue by Ponix310** [WeakAuras/WeakAuras2#4577]
**Is your feature request related to a problem? Please describe.**
A fairly simple problem. Progress Textures  have a "slanted" option, and I think Progress Bars should have the same option with the same functionality.

**Describe the solution you'd like**
Add "Slanted" option to Progress Bars.

**Describe alternatives you've considered**
No alternatives.

**Comment by InfusOnWoW** [comment]
That can't work with various other features of progress bars.

**Comment by Ponix310** [comment]
Can you explain which features would not be compatible?

**Comment by InfusOnWoW** [comment]
For exaomple the border/model and tick sub element.
