### ISSUE TITLE
WA trigger based on talent selected by party/raid members

### ISSUE THREAD

**Issue by Trickhamster** [WeakAuras/WeakAuras2#4579]
**Is your feature request related to a problem? Please describe.**

I would like to track the cooldowns of unit:partyX that change when partyX has a specific talent selected. 
Example: unit:party1 is a monk and has put one point in the 'Tiger Tail Sweep' talent. Leg Sweep cd is now 55 sec instead of 60. To track this cooldown, my WeakAura needs to check if that talent is taken or not.  

**Describe the solution you'd like**

A new trigger that checks whether a unit in /inspect range has a certain talent selected. 

**Additional context**

I saw some indication that Blizzard will change how /inspect stuff works in the API with the next patch, but nothing confirmed yet.

**Comment by InfusOnWoW** [comment]
That's out of scope of a built-in trigger.
