### ISSUE TITLE
Spell Charges - BFA Beta

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#458]
I'm not sure if this is a blizzard issue or not though recently I've realized that swapping out talents or items that manipulate a spell's charges breaks. The charges stay as they were before the swap, I've dumped the info from GetSpellCharges and it returns the correct info so this is probably a WA issue. An example of this would be something like swapping from Specializations from Survival hunter to Beast Mastery Hunter, Kill Command returns 2 max charges in Survival but nil in beast mastery though WA still shows it as 2 charges, same with Butchery and Carve, swapping between the talents keeps Butchery's max charge count even though Carve dumps as nil charge info. This happens in every version of WA Beta build, though only recently since about a few beta patches ago.

**Comment by Stanzilla** [comment]
Probably an event missing

**Comment by InfusOnWoW** [comment]
Yeah, I'll take a look at it tomorrow. I though we already did something special for spec changes.

**Comment by InfusOnWoW** [comment]
Should be fixed in the next beta release.
