### ISSUE TITLE
new combat log trigger: spell lockout duration

### ISSUE THREAD

**Issue by Trickhamster** [WeakAuras/WeakAuras2#4580]
**Is your feature request related to a problem? Please describe.**

I would like to easily track the duration of spell lockouts on party members and arena enemies. 
Example: If my healer (party1) gets kicked by a Rogue, then I would like to have a WeakAura that shows 
- the exact duration my healer can't cast ('Kick' lockout duration)
- an icon that indicates what spell was kicked by the Rogue

**Describe the solution you'd like**

A new combat log trigger called 'spell lockout duration' (or whatever) would be ideal. The user can determine: 
- unit that got interrupted
- spellid of the interrupt that was used 
- lockout duration

and it would return the icon of the spell that was interrupted.

Thank you to everyone working on WA for the best mod to ever exist in a game.

**Comment by InfusOnWoW** [comment]
That's out of scope for a built-in trigger.

**Comment by Trickhamster** [comment]
Units getting locked out on a spell cast is the only combat log event that WeakAura doesn't cover yet. The addon GladiusEx has the logic around the SPELL_INTERRUPT event here: https://github.com/vendethiel/GladiusEx/blob/master/modules/interrupts.lua

Maybe there is a way for the team to apply this logic to WeakAuras without too much of a hassle. Thanks again for all you do and all the best!

**Comment by SpatenLa** [comment]
![grafik](https://github.com/WeakAuras/WeakAuras2/assets/39881841/94c5045d-ed69-4814-bf94-5e18db7ffc65)

weakauras does handle that event. this event however does not have the information you want.

**Comment by Trickhamster** [comment]
This and the other ticket (https://github.com/WeakAuras/WeakAuras2/issues/4579) are the only two features missing for me to complete my WA-only Gladius that will help boost PvP participation because of how easy it is to keep everything up to date with WeakAuras. It would really mean a lot if you guys could look into it. Once that is in, everything you could possibly want in PvP can be done with WeakAuras. Cheers guys.

**Comment by InfusOnWoW** [comment]
There's no api for spell lockouts, thus it requires lots of code that we don't want to maintain. That's why it's out of scope for WA.
