### ISSUE TITLE
Cannot delete a WA that is pending an update

### ISSUE THREAD

**Issue by Wolf-DK** [WeakAuras/WeakAuras2#4581]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Got some old sh*t in my WA's like Quaking from BFA.
After installing the companion App and going through my WA that had an update pending, I realized this and wanted to just delete the old crap. But when that Update circle is present I cannot:
1) see what the WA looks like (cannot select)
2) cannot select delete

Is this a bug or a feature request? not sure, but it is definitely annoying.

Thanks for the stuff you make.

### WeakAuras Version

WeakAuras 5.7.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No errors-
```

### Reproduction Steps

Have old WA installed.
(Since I do not have any working options (except Update) I cannot export the old WA I have).
But I guess anything with an update can be used.

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/12844808/252857f3-84a1-4c98-a306-b545baa616a0)

**Comment by mrbuds** [comment]
Tooltip show `linked aura: Quaking 2`
That's the aura you need to delete

**Comment by Wolf-DK** [comment]
Issue is that I cannot delete it now that is is pending an update.
Even after selecting update I have 4 WA that are creating copies and stay as Ready for update:
![image](https://github.com/WeakAuras/WeakAuras2/assets/12844808/9f214504-5af2-491a-b5fa-e72444198136)

I do not have any option to delete these 4.

**Comment by InfusOnWoW** [comment]
The "Ready for Update" buttons are for updates, they aren't the auras. You need to look for the auras further down.

**Comment by Wolf-DK** [comment]
Got it, thanks.

Would be nice to have on the menu though... but OK, not a true issue just not easy to see.

Regards
Wolf
