### ISSUE TITLE
Update all

### ISSUE THREAD

**Issue by Wolf-DK** [WeakAuras/WeakAuras2#4582]
Having many WA that needs to be updated and have to do each 1 by 1 is a bit time consuming.

**Describe the solution you'd like**
I would like a button to update all, and not have to decide to copy or replace or reset position.
I am pretty sure most users are just interested in getting the updated stuff and using the companion is to do this not make a copy.
![image](https://github.com/WeakAuras/WeakAuras2/assets/12844808/30bb864b-206c-4326-8d22-87408483cbe6)

This should default to Update:
![image](https://github.com/WeakAuras/WeakAuras2/assets/12844808/31df2f8e-02d1-46f8-82aa-9e9219dc2c68)

These options are OK as default:
![image](https://github.com/WeakAuras/WeakAuras2/assets/12844808/944b43c6-6e9b-4da5-a04b-d615d5056f3f)

You could present these options first time update all is used and then have a section in settings where it can be changed.

Thanks for the work you are doing.

/Wolf

**Comment by InfusOnWoW** [comment]
That's not something I want to add. The update process per aura should be a conscious decision and in the future we are likely to offer fine grained options on what to update and fine grained display on what the changes are that will be applied.

A global "Update all" wouldn't fit.
