### ISSUE TITLE
I update to latest aplha  and addon just stoped working

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#4595]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I DL latest aplha and WA just stopped working.Aftethat i try reinstalling last working WA file.When i logged in its say try repaor tool but that didnt work as well.Then i deleted addon (without settings deleted) and reinstalled release version.Still didnt do nothing. Now i cant open main window and none of WA are working .I can only open profiling window.

### WeakAuras Version

WeakAuras-5.7.1-11-gcd5bcf5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
Count: 1
Message: Interface/AddOns/WeakAuras/GenericTrigger.lua line 234:
   attempt to concatenate a table value
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"] line 234:
   in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:205>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"] line 303:
   in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:252>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"] line 1439:
   in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"] line 2970:
   in function <Interface/AddOns/WeakAuras/WeakAuras.lua:2883>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"] line 3051:
   in function `Add'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"] line 2509:
   in function `AddMany'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"] line 1156:
   in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1127>

Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1204: Login()
   [string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1279:
      Interface/AddOns/WeakAuras/WeakAuras.lua:1230
Locals:
(*temporary) = <function> defined =[C]:-1
```

### Reproduction Steps

Installed latest alpha and addon just stopped working

### Last Good Version

WeakAuras-5.7.1-8-g7a16831

### Export String

```Text
I would but dont see option to atach zip file .I tried copy and paste but its too long of text  to copy text into this box.
```

**Comment by Addonman** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/12568817/WeakAuras.zip)

**Comment by mrbuds** [comment]
This WeakAuras.lua file is working fine with alpha version, we would need a copy of the file made before the use of the repair tool to be able to reproduce the problem.

**Comment by InfusOnWoW** [comment]
If you do have the original file, e.g. from a backup we would like to have it. Or the first lua error that occured. 

Otherwise there's nothing for us to do.
