### ISSUE TITLE
No RGB fields in colour picker window

### ISSUE THREAD

**Issue by johndolotko** [WeakAuras/WeakAuras2#4599]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

There is no longer the RGB colour picker fields in the colour picker window as shown in the attachment.

![Screenshot 2023-09-11 200419](https://github.com/WeakAuras/WeakAuras2/assets/49884783/b4621db5-f90a-4511-94fe-10112d6e2d96)

### WeakAuras Version

WeakAuras 5.7.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No LUA errors
```

### Reproduction Steps

happens everytime

### Last Good Version

not sure

### Screenshots

screensahot in the description

**Comment by InfusOnWoW** [comment]
That's the default color picker in wow. If you want a better one, you need to install a color picker addon.
