### ISSUE TITLE
The full scan aura trigger is missing the remaining time option

### ISSUE THREAD

**Issue by elvador** [WeakAuras/WeakAuras2#46]
![image](https://cloud.githubusercontent.com/assets/8883045/15611792/4bf7d72a-242c-11e6-8226-5e8adeee3d28.png)

**Comment by InfusOnWoW** [comment]
Duplicate of http://www.wowace.com/addons/weakauras-2/tickets/411-no-remaining-time-option-with-full-scan-auras-on/
