### ISSUE TITLE
Block imports with an internalVersion > current

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#4602]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

There are scenarios where a user can try to import an aura made with a newer version of weakauras (export made in alpha, didn't update release) and brick their addon (no reverse migration)

WeakAuras should not allow imports with higher internalVersion

Bonus: update repair tool message to write in BIG LETTERS they really really should backup their WTF before pushing the button

### WeakAuras Version

any

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

...

**Comment by InfusOnWoW** [comment]
Fixed.
