### ISSUE TITLE
Pvp Flag trigger getting stuck after leaving a BG

### ISSUE THREAD

**Issue by mdavidson37** [WeakAuras/WeakAuras2#4603]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I was directed to open a ticket from the help channel in the WA discord.

I have a small weakaura that uses the PvP Flagged player condition trigger.

I find that when I leave a Bg the weak aura remains active as if the PvP flagged trigger isn't clearing after leaving. The only way to reset it is to /reload.

This wasn't an issue until recently (it's been a few months since I did a BG so not sure exactly when it started).

The flag appears to work correctly in the open world when turning War Mode off and when leaving a forced PvP area (eg Wintergrasp). I have not tried with other types of instanced PvP.

### WeakAuras Version

Weak Auras 5.7.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

The follow weak aura demonstrates the issue:

With this WA active and war mode off:

1. Queue for a Random BG or Brawl
2. Observer that the PvP flag from the aura appears
3. Exit BG
4. Observer that PvP Flag does not dissapear as expected.

### Last Good Version

Unsure

### Export String

!WA:2!1vvqVTrruyB5dvArQn1fIG2iXQGOQriCCsvtfuvvvNAtcYnXSEtAHlRNDNz9o0zNzyMzDI7fKSufCHlr9isG8zo5ZCaHGEEve)cIe8dOIZeMzw3wAWELS9mV3B)Mz(MV3NlVF10QWQsVBu7M1wRk8BVPy4UXXsKARFPZW)8Rp90)sWYuemfj2Dp)2BVttXaKqIz0ktW0yMifO0tC4UqSKtad9rhQckIhefOWPOPZk3iMrv8fAjWp29ZYaqbqbC99FoGgLWeTeGuK)qokS7MEnBUZrakUa7nAKcW0wnu6KnOmk6yyMWMjWesirrmkuocbKwaYVWVAg2vjq0(QKZ5jvaHQv(5ZVq(c5xmVQ(3lDUWymfltoB4JKisChgMQcBSRV)U3F9mbHFLeLIl)4vx9aqFwnmB1B2)RUE3b7Cp4QRn6aMa(abG71KGHiXHVG)(IV)VlvQCVJLjai7GhweUY6zy4KUr7(r82RxNEdc)QZG44fehb1henmiMWyIe(hm)cHdPGuSMUteizcJahEmitPz1D5gEs6mwXIMEV92L)M3ySml0d13K6YlMF(J1tdbrpQV(UMcdLSmrekeNYzc10T)NxS9xQKaezHCJgA(t5K)Mo5VLtO(gig33H)EZxfWfOiSv4eAyXTV3rVKeNuSgBYimXNwUC5kEr2Hv26o)8slDNt)NFyR78Bp9P)yPsxQsOeLQpjERvRET6Jf2dH5wVHsVK8RmtoQyGNzBaFU(QfjOaY(f0XtAqya4ZoktIcOinYjnK4hJw0lnJOWohBJRLMceGKM4fras5I53YjubiiQYmKx1uKntaGcdKCuuVjMydqj4icsdPoKP0tmr1tiKhrzhqtSWZrQqGsPR7KxhKfdLyAFc6jhJPArmnczv8otkAzkKPB2Ch)MElJHR3zaFCm(qe8byOk57eFzMuHJh2ODZw(ZuMfnlz27oZcbHHc0amqHs4lePbMLAkypouhkmZ(ZCU9F1RgKco8ItInD66UtD7FLj)N3iSZGoUVFeF55VttzWa97H6n20YJNQTF12H)7XzuR(8AR4QFCmFryraIlFa3xdHOBHBH7TD14MuZEOV2NGuD2VJnV(fx1DT61RVYTEjc4y3R9)b42UxV(AUR4QsquBzMhbsLjOUlxF5BzJHisK7zZEgOMwjf6y(OFMZDGvcAfJEwL6mDeIMJJq5zYR8ZWRNOTnygB3iRgYRLrontVD(R5TpsjW97R7Oo)vpkJoDIJy6GN1it7veAGajgd16L4ytpRyRMT70AV2JmDbMs6v0kb0wqIWT0h37ZGOEJSnmBdLfTpfzTzSZ1SzmbOxhyppnTqvJ38LIdT7E0jA3nB8U6LfF4KGnVBx)GU(31Z3ZqMAyFrfDeiDfED70SDB(fnoDdq(fNbZ69tL4xEMuU1UQ3m1)8Z6(ntpQOPdY3yK5Fj7QDGENQd(JhM)H51(3

**Comment by InfusOnWoW** [comment]
Where is the aura that reproduces the problem?

**Comment by mdavidson37** [comment]
I'm sorry I missed the export screen - I've edited the OP to add it.

Also available from: https://wago.io/7gq3SvNDd
