### ISSUE TITLE
Get cooldown information from other players

### ISSUE THREAD

**Issue by Shielumad** [WeakAuras/WeakAuras2#4606]
With Augmentation, I would like to track the cooldown information of other players. Currently this requires custom coding.

**Describe the solution you'd like**
The ability to recreate omnicd style bars but in weakauras. This will allow more customisation than is currently available.

**Describe alternatives you've considered**
Omnicd, method raid tools do not have the level of customisation desired. Custom coding would be massive overhead to maintain and is out of my skill level.

**Comment by InfusOnWoW** [comment]
I wouldn't rule out that we will eventually do something for tracking group members cooldowns. But it's unlikely to happen, there are a ton of questions that would need substantial work, as such I would recommend in requesting more styling options for OmniCD or MRT to be a more fruitful approach.
