### ISSUE TITLE
Bleed tracking (manual list)

### ISSUE THREAD

**Issue by linaori** [WeakAuras/WeakAuras2#4610]
**Is your feature request related to a problem? Please describe.**
Yes - due to Blizzard not making "bleed" an official debuff type I have a hard time maintaining a WA where i have to manually go through all the dungeon and raid spells for the current tier to add a possible bleed. This is time consuming and I'm pretty sure I'm not the only one that does this.

**Describe the solution you'd like**
I would like to have a bleed type in the list of `Aura <unit> <buff/debuff> Debuff Type`

**Describe alternatives you've considered**
I could add this list in my private addon and then recreate the logic using a custom trigger. This would only work for me though, and makes it hard to share this feature with others.

**Additional context**
ElvUI has started to manually track bleeds with a small piece of documentation how they got the list: 
https://github.com/tukui-org/ElvUI/blob/fc39f65022e62006f410a35ed775aa4afab3a8c4/ElvUI_Libraries/Core/LibDispel/LibDispel.lua#L50

I'm not sure if manually tracking this list is worth it in terms of maintenance.. I am aware of #2758, and I'm only proposing this as a feature because most of the work is already done by ElvUI.

**Comment by InfusOnWoW** [comment]
We can't take the list from elvui, because their license does not allow for that. You should not consult that list for your own purposes without asking the elvui team for permission. 

And we certainly don't want to maintain a list of bleeds ourselves.

**Comment by linaori** [comment]
I was referring to the steps they took to get the list from wowhead, which everyone can do without breaking a license. I'll make my own list in that case, thanks!

**Comment by Jodsderechte** [comment]
https://wago.tools/db2/SpellEffect?filter[EffectMechanic]=15&page=1 would be better since it's not in read only mode anyways right?

**Comment by InfusOnWoW** [comment]
yeah what jods said

**Comment by Jodsderechte** [comment]
also bop can remove a whole number of bleeds aswell (that has been in the game for a while though atleast since bfa that i can remember)
