### ISSUE TITLE
The battle record is not working

### ISSUE THREAD

**Issue by kkomsss** [WeakAuras/WeakAuras2#4611]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Activation conditions (battle record)

### WeakAuras Version

5.7.1-19

### World of Warcraft Flavor

Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
..
```

### Reproduction Steps

Activation conditions (battle record)

### Last Good Version

5.7.1

### Export String

```Text
!WA:2!1vvqVTvXw46AIkYcrttHOwqcfA41QNGM8sQOTQSOkxh7MestsV2jPTeH9CVZCV3HC9DgnZ444SRwSiV(kuKLQelyLfspeQlQIOsWkq5xWil2JuwskBYVaoZCTtALiZc7ZCoZCMZ8nFFNBMIdvBi8q4T)WouFwsjwDHpjtxuDvetSixrzjYCIMlgeijQ4xBhuIpeyjgnr5LVWcLl421NXIXSgjLAq5KQ8b9RlvSALjBQwMJrkIxD7FtwxeZF3iLIlVX4J3afYgJYgFZcy6TU)9rUJpPa5BpUR6kviH6IUsw9em)gZMOiIaKpzTPWyi(ARsqRpvDbsU2sSgeH182emfTwjZoKR5JutoglmSfMvXMKQo0eQkNxa8NmkxlLGggseY38IIEMBF(DRljv8rsv5MCs0EMzipjt4DBgMuTTzUKtIJR2YywhYx1wyIuTmy5SoJjSZwavJiMUbtSonXMX(oJ6GbKiiWKDXmfMFPIlpFBBcnrFh(G7)0FA)F8h(RN8DJS)JF0l()F5EY6EKnijQLeKa6MULwQW8Z7OGT32NvZdPIzH83Uxz5tdO(v6xovf1tSB1vrRrWTWaczG2HM4WKwckf6MDRKFQsLRuA585luQKRnsN82SpY8SqliiTuc7vW1wVDkgJKrJ4alR7HOIjE1wwZzXYCV0onfuKBcexM7qeXwLDoAbE8yutIWXaREWRFir1UEsV3MH1xtFD(zm0JniLt9zEuE6joGA4gjO4vGht4c(FpyDcHpLbquUMRCuBjjoWsx1dSNur9xV509qJiXgP7AGoaQ4scnKVBmSE0UWupK)6Hcd3z7ZZFpfqMRy)jGjQHuv4vmiBVzzAFy8l8V48bTZKriquKNfZeZLjtMS7L6TF14m1YLxKFwRtqSXG0q9xLIvrotbtpi9WOBsWwNpOBQW7EPcXm7AJ)fGsJg0upqhbtbsmJMZzHfxOaFOxQgUBV9OhvaxmtGEjRFGo2f7Bl1SWODVBAIIpyrbDRrUtDegWm0iLlZF)Jdl4cGfAGZSVYP3VI7EysTkGfxU88ZUqHuVGCbVQaXBTApJ0R3gq68InTusHPJA9OhGF()H6i1qFj(hCCfzmje53SsqmOxREujvIUf5t4)7JBx4Ma9f0xQibrgbD7AYh54wBngUcGvKQBFoD5S68T3)zp5f)Y3(N)8Z0tBjc6c6I6BPNrp7d0ZLr)P6b0ZRVTEu9I6LZOVZCzN5M6bHXP)JzU5ETnJFnR2vxsVuMEa7Rqf((tRVFv9D13tVIEv9NbzBn9L0oz0FEdDLM6fY4frOHrQN7eZq4vaXvmiYh2Tw9yfnNJeU5dRdY56dIAPXYXOEmgITyjeqmFsVuDQhTgNjuqFmjsz0qqpnHv1yErDmF(Ov)VfuDhmvA00ZcEp3jp7CIntl3zU5V1(eMH7r8TjRtX70WTr8QBotYvkIDrX8iuw3ggM)Z3jqa9okPmeWS83Q)jy46ttLiGGaT3nsOOokMFpj9R)rp6cuSgAGtQbUCNyS)ZytWhcA)KV3(HgiUMNPdsrZIMdXCp8kL3TqHfC2IXQLXdQ(aAyobnXKys0U9p(c4qsKMvTdScmn9ZK7qts5cWSlUdy6tky6OkRYphnmHji9(GQ1BbHGjKvBJsOPB5Q63yf9OEGocWPweK0wpojWRq3(DWRy6)dfI5uL6h6eGWKDnlfWhssOk6uo1q0KIaD6r6Vs)16V5u6)hyEgiZ6hAnnEFO(XqKHK8b)4XU2ytC5RF5WRHM4Qx)ktm0g)(D)7)
```

**Comment by Stanzilla** [comment]
What's a battle record?

**Comment by kkomsss** [comment]
Please understand that my English is not good
battle record = bettle Messages  (Battle Messages in Active Conditions)
ex) stanzilla cast blind

**Comment by kkomsss** [comment]
![image](https://github.com/WeakAuras/WeakAuras2/assets/145413689/91a8befa-d5af-4399-860a-b2dc6fb16258)

**Comment by kkomsss** [comment]
It works fine in 5.7.1
It hasn't worked since

**Comment by mrbuds** [comment]
The aura you have exported in ticket use an invalid unit id in the "specific unit" field (koor) if i replace it with `target` the aura works as intended

You mention an issue with "Battle Messages in Active Conditions"
- Checked condition tab: there is none in your aura
- Checked action tab: there is an action to play a sound on show, which is working (cat sound), but it does not print a message
- Checked load options: nothing is ticked there
- Checked display tab: there is no %name or %spellName or anything that could be related with the issue you describe

I tested on classic_era as your screenshot show items from this extension and not wotlk

We need a better description of the problem, I'm not sure the aura you exported show what is not working

**Comment by kkomsss** [comment]
Combat messages only work their own.
The target does not work
I tested a lot of times with various files
Everything was confirmed to be operating normally before 5.7.1.

**Comment by kkomsss** [comment]
Other acquaintances are uncomfortable with the same situation.
Please test it again and fix it
