### ISSUE TITLE
Tracking Absorb Values from Tooltips

### ISSUE THREAD

**Issue by husskhash** [WeakAuras/WeakAuras2#4613]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Sometimes when I get a buff with an absorb, instead of getting the absorb value from tooltip1 it gives me the initial duration. Happens randomly, sometimes it works fine and sometimes it doesn't. I feel this has only been happening since DF launch. This happens like 10-20% of the time, and mostly on absorbs applied to you by other people (like Mass Barrier or Temporal Anomoly)

I put an example (in the string below) of one of my absorb weakauras, molten blood from blistering scales augmentation. This happens to all of them. I tried using custom code for the text as well as tooltip1 text, both the same issue.

### WeakAuras Version

Weakauras 5.7.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Apply, or apply any absorption effect, such as molten blood from the string below.  Sometimes it will give you the tooltip value, sometimes it gives you the initial duration

### Screenshots

![Capture](https://github.com/WeakAuras/WeakAuras2/assets/9640862/d0c22cb1-4ee0-45d3-a022-33531f5ca1ad)
![capture2](https://github.com/WeakAuras/WeakAuras2/assets/9640862/d368d441-586f-4bb3-93f9-0cc40185ba1e)

### Export String

```Text
!WA:2!TI1wWT1rDFuC7KI7mLehAieOKfxQXEWrXsoYjT8vMXswoXT(2ijx32x052kD26Jo7P7UhzRqOqnqjZWWdvdp0HNy089epQNPdGHzGY1TIYtuUmgMwEJzYd8m)3Dps2oooUtcQns71F)VFzDQ5hPXiEJ4DRl2H4sdltJzU4p7hZzt760fMR9l0y(C1A69YZ0XnMlOnQG3sS1jENAXHUccnC8jggbFi1q2Xm7Q4WMP5cBbgj8XH6TuFcOU2bOq7gy0ZIgD07yDBhoL5a7CqislO0abjkdIY2)LoeTshhsefS5cmdzh6HcPc0AWslWvFp(rE4jrJgfy3cZgDIdYUQpjm76m7iLiVqybAaLvG6HhhT(Svxtu7QLJDUtWD1aVmC3jrZmXKiooa7kg)YtIUgwuiWMZ1WmEY6zNuZO6noA(Cc4dAIbChgeXKp3dDcpcheSGNwHCeB9SplkZtp1LZnZD7qjk)ShwZCmMRSOlErs9qkdJISjHiFBoklkmUHdMXrWcEyUlJeP8E2Vmn8HX3m41uUmhKfRrznSflAZQJxwd84MZoHYvXmCaCmSiMfQTNtU)9uKe(hR1k1QXXIuDTdD9PSvPKqHtHIlxPyPEUGi5r3mS8MKiSv0P2leyTipqMlHBIdf70)yf9QJ9z26ad(mLa1ctmwBpAvZ98Dm)EI8eW2oM8tyjp1wP(3hTub6GbXzgf4GOnZ0)Vmtn1uAl0aX0CX(6ZdEYdEuUGrcRNMdEXMZmzMjZmr60J(8J(LpkaoEeYECiC8qm9XcXhrbzP7jgFeLL9dYXX0W)L(WBE5jZLaKYHZPgy95(dVnCU61HyILhJLm8wpblj20jZuxj3vU8UXC81y04OQU04qHFpW)W1hZl7t3CLWD46FMfCqAI7bhTQ(2QSp(7c0x7CUkdxJSvPYRwCXfzXH61kjinWEDv3ijO1VKk(GFENzBAdET5vZKJUTh4AQ8(g5QThaD0iZHBqz2bKBaYjcyLyrBLpCcctF5CzZE1ooX1Qzyt553rTTgaIhCIlNzQzYLHbKxZQ3wXhEy1f0jc1luClimQSrzy1XSBLwry21lU4QZV2I7uddAIkgU3s(ODkqB4ylqlsRpq0ld3HSvVQfMTCLQLxRqHILlNxaGusXpz7oqJbKy7Kb8ZFUu))ZSRElDLqv(zRUMa3Q(epS8c76c0IeIxYym6Omdls3eZfD27ooMsl5vPXLFL2G1ZyJhURhH)k6O6M4S2bbrN2wpUIz)LGkmdDBiheMfAh8cG)bO))23EdmoAwGhDfLuweR2qfKA6CvYhbupCBHYubzFAAUH4X6aQHs46QurV8zL56btDSD3Oo4of6vRRdL5Hzv5KBGhQxYeQot4q7Km1vvQ65sLk1q7MSstcN4eGT6FBmKWl60LF1yBiB)8XbbO19jcSmxBf10N5d6vpGU58m8RgJdDBT6dnv6S5YRwZFh13ZL4In02QzktCPvjBHd6OMUioSUW)X7Qg)sM80d1wnrxf95gc(SJkeP)k(YCmGYQtOpwzO9cq80i7tC3ieZ5dPr7f3pAlcgt(P1umVMPTU15J(CcinFv9xMeZvJQQIBsMLQ9G9h9PIIqh1PBq9QQSmw7Q3CGzl)SRvzLOZOx0ogCUaTG76epHF(zHP32afOj80l(6rFHJIcb462UTQwlGszw7OpWRaURKATaxdgvvBwvXk)YRSCXOtz4cFBV(krL9TNP2xIsjLrlQoz0N(UqvZa5f6Ox2DGPODYXGemlBd23Or2hX6JDYIgcMytt1BWn1X4RSwLfxy5IMv3eSiQUW2E9KbgrSVRyIeT)I35xPsLvw6auVpHI(8hLwmIHDjQiNH2Jzkdbhpr0eh1v8AbP8iUvf(mmKdiWlvVdkw36cs7usNSpLBwjq7rpeqzg0JBYkTZtQBQ9lJKxq2qBDKEsSSMSUe8coS9Wnzq(qAiw(6PKVI8rKBidKV2qYVA2kRSQ8gwYCs6DXf9oiU8BjFvTHuYKC5wYwYVwkzCQOZFyAMT)vEdzt5MrFPJgAhs9QM6GjBfD6zDCy4MeWV0iQ8OlEV0mhcb53v(nAj)6pHm8EQt3JhD8XK6(IRKpGA7DRtLxL07SLAedNAyvXAvf2ZkFZHZRsWoMdhwkaFs5Bo2jTEylhbKdjeAx77Fg5BE2ZyXQzAWtDHsUQcwWwS1NTuPfwPeCc5BzLNrdWQ9Bh1mYCD1SoEeOGKlq2wQP7oO(ZgHqZJM6Gq2ZgqQsODtp)U7BY5oXp(BMhATudlZGzwnO7HW5EOVxm7gGxaug7eoMsroKgruMO0ErPDjHg9cidJ1fg6IlQQwYTIoNPV9v09MZ1RwKXOmUvhMUsIk6mV6vIQIyQcClaJp3J9UxBxiFJ7gT6Nm3pBmli6Z4ler8N5sxs9uY0e6LMf2oVn7szNot2yIx3fWzQZiVu04(BM)guAJvhAQ0tFBtm08mO3af9CkxOuXIlhncOEkK0OnuKSKkNQdh3ak4XYKgQQm9urFY(DIRs4nhHBdzi88ZRYVA1rqDtkoEUuFNhDuIx0JVe4OaTac(fup04MgPMOKDqKV9qDRP4GYcqIS)4L2uLe(5BBhsmAUzKp2larvVX2yBUMnLVrV(Dlvv1JbJJbDJhFh1bau0vYoPdKMbYm0LdDcHDOciVF(gWRKMxHL8Nk)zYDoP8NadpJgD9WKv)5YFHdGyns9)daMRVDOWQDdOxsOheBOffWs6GTH2WCXwLeuW1XQKzlv7LHBGfwzJOcRTBGHlxNgAXIfKaIOL12yi6kaAk1I5fhwhd7LVgOsaFFgyw5woBITJGvlf5tSdSa4uAsOBJT6xX4hz1rjUeTNZWB33o43d09G1mXL6h(PaXcIgTHASYj9ZRIBpblKUegEZJV8ThA(T7N31b6qLe3qMR7(EVO89JsFZkzHE3VAUR(mtNv9)tDtb6MUZdFkuyQPwaKBuF3e(nzY3(HBcKuqRdH0z3a3s(EazGA81SH4ql5t6SUw0uDJohqiR8kYfnx(wi9DuT4k8jCevZaOw0y0MeOrhCOY5s9ecusSaIwtpTVSNgiSCx5)q(BLFO8Fj)aGySkglH8FAbCHYe)Nb1G89pH8VOLE5Fv(3Gf)7GC(u3SY05YE1Sxj3DvoZd92oq80u5xcaOW9j3UOX7GRi5hg9C3NIcST6DKAOqrmQlFGa97ayx4bbwWpuDuvt980gnZQ6L4gntFc9N6ltoRQC8sKOR)arAfq3H8877tMULai5Ovv7AO1ZFFsRM2mcnMJyAapi5KaUKhiRss4AdCFtZKiESRpYMJkgGvldY4IalylmQ3Ef33vUdL8VgyN1Ea8315Am2s1FEhJw2MjAziTtf1(3bnF3(AC2CMeogTDP7h2OVQoj1fsveNuZnX764cYYmn8A17Emwbv2ZdgK9Bg4PO3enh8LVH3R()GugdSW6(kq603ipfn2Z75xb06h8aqR(pT8Wevvm5I7NMdCQwhAX4Ixh6SWdTqiuQhE9kx)xKBz17oXFro6AWta9i2HgBENLaOqAv0hHuDpPYkm9tp9tFxTclr4UhWg8h7BdIgPIU8eAmeCipc0bVWylAC)QF04DPg9rtDfq8f2HBO(DtqnO(TeTEmgO61Jv6YbwMEaL9VFOmu5Kh3qDdvvxaypvzI9tr1P1JRbMa17un65DM3C(5uN)Gry)HbryRzQYB0mV19PMXfdnDcr3jTmOdUq9B4zphL6uhazGdH2BytIQhhcpmcB8vGoGG3zJvzebNq973sWchigOeFNhWSr7RniK5pBeYCrJgR787TVrHncVuU0xjDMrA(EV4)n
```

**Comment by InfusOnWoW** [comment]
What does %tooltip do in those circumstances?

**Comment by husskhash** [comment]
> What does %tooltip do in those circumstances?

%1.tooltip1 or %1.tooltip2 (depending on the tooltip of the absorb) to extract the absorb value.

I have tried both the above, as well as whats existing on the WA with a custom text:
```
function()
    if aura_env.state then
        local name = ""
        local absorb = aura_env.state.tooltip1 or ""
        if aura_env.state.unitCaster and not UnitIsUnit(aura_env.state.unitCaster, "player") then
            name = WrapTextInColorCode( WA_Utf8Sub(aura_env.state.casterName, 6), select(4, GetClassColor(select(2, UnitClass(aura_env.state.unitCaster)))) )
        end        
        if aura_env.state.spellId and aura_env.state.spellId == 190456 and aura_env.state.tooltip2 then
            absorb = aura_env.state.tooltip2 --ignore pain has 2 numbers in description
        end
        absorb = absorb ~= "" and aura_env.formatLargeNumber(absorb) or absorb
        return name, absorb
    end
end
```
And using %c2. Both have the same issues.

**Comment by InfusOnWoW** [comment]
I'm specifally interested what %tooltip shows in the two cases where it works and where it doens't.

**Comment by InfusOnWoW** [comment]
I fully understand the issue, but if you can't answer a question for further information, there's little point in trying top figure this out.

So please add %tooltip to your aura and make a screenshot showing it in the buggy and in the working state.

**Comment by husskhash** [comment]
Apologies.

When I do %tooltip, the entire tooltip is returned (as expected and shown on the attached)

But then also, it shows 38 seconds remaining on a different instance.

![Capture](https://github.com/WeakAuras/WeakAuras2/assets/9640862/5712984e-f50c-4981-b7c4-edaa1cfc5c32)
![caputre2](https://github.com/WeakAuras/WeakAuras2/assets/9640862/b9c2f20f-2d5d-443a-8085-5b4c3eada5b3)

**Comment by husskhash** [comment]
Another point, with the testing I am doing at the moment for this specifc aura, it happens mostly when I reload/login.

But there have been multiple instances in a raid/dungeon environment when it happens as well.

**Comment by InfusOnWoW** [comment]
In the top right corner where blizzard shows the buffs, what does the full tooltip show? I'm guessing it simply doesn't contain a line for the absorb amount after login.

**Comment by husskhash** [comment]
![WoWScrnShot_092223_125720](https://github.com/WeakAuras/WeakAuras2/assets/9640862/4e525308-ed53-4578-93d6-5c04b6456766)


Just tested, both instances, where it bugged and it didn't it showed this tooltip

**Comment by husskhash** [comment]
Also, if its relevant, bugsack and buggrabber are not showing any bugs

**Comment by husskhash** [comment]
One more thing - if it bugs and I open WA options and close, its 'fixed'

**Comment by mrbuds** [comment]
After importing and changing texts with `%tooltip1 - %tooltip2` on top, and `%tooltip` bottom i got this

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/463e7e97-d298-44fa-9576-bcd585715ddd)

but i have a hard time reproduce with /reload and re-login

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/6f97b850-98ac-40e2-89ac-901d09cc0612)

i managed to repro once more by closing client and restart wow

**Comment by husskhash** [comment]
> After importing and changing texts with `%tooltip1 - %tooltip2` on top, and `%tooltip` bottom i got this
> 
> ![image](https://user-images.githubusercontent.com/189656/269943611-463e7e97-d298-44fa-9576-bcd585715ddd.png)
> 
> but i have a hard time reproduce with /reload and re-login
> 
> ![image](https://user-images.githubusercontent.com/189656/269943832-6f97b850-98ac-40e2-89ac-901d09cc0612.png)
> 
> i managed to repro once more by closing client and restart wow

Yes, seems to be quite random. I reproduce it when I login to another character and log back in to this character. But again, this happens in other situations, I could be in a raid where I have Life cocoon and temporal anomaly on me, the life cocoon correctly shows the tooltip value and but the temporal anomaly doesn't.

**Comment by mrbuds** [comment]
![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/e7835c0a-4af2-45bc-85d0-fcf07c813ba7)

after restart wow, first top line is 

```Lua
function()
    if aura_env.state and type(aura_env.state.points) == "table" then
        return ("%s - %s"):format(aura_env.state.points[1] or "", aura_env.state.points[2] or "")
    end
end
```

**Comment by mrbuds** [comment]
Proper solution will be to save data.dataInstanceID from [C_TooltipInfo.GetUnitBuffByAuraInstanceID](https://wowpedia.fandom.com/wiki/API_C_TooltipInfo.GetUnitBuffByAuraInstanceID), then use [TOOLTIP_DATA_UPDATE](https://wowpedia.fandom.com/wiki/TOOLTIP_DATA_UPDATE) event to update auras with matching dataInstanceID

**Comment by husskhash** [comment]
> Proper solution will be to save data.dataInstanceID from [C_TooltipInfo.GetUnitBuffByAuraInstanceID](https://wowpedia.fandom.com/wiki/API_C_TooltipInfo.GetUnitBuffByAuraInstanceID), then use [TOOLTIP_DATA_UPDATE](https://wowpedia.fandom.com/wiki/TOOLTIP_DATA_UPDATE) event to update auras with matching dataInstanceID

amazing that there is a solution. Unfortunately I am not a LUA expert and I don't really know how to implement it in my WA. Does this mean you also know why it can't read the tooltip sometimes?

**Comment by mrbuds** [comment]
My comment wasn't aimed at you, please don't close ticket before issue is resolved.

**Comment by husskhash** [comment]
> My comment wasn't aimed at you, please don't close ticket before issue is resolved.

I accidentally did, my bad

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release.
