### ISSUE TITLE
Lua Weakaura

### ISSUE THREAD

**Issue by Mithras2801** [WeakAuras/WeakAuras2#4618]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Wait in game to look error

### WeakAuras Version

WeakAuras-5.7.1-32-g2786ffc

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
11x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'UNKNOWN()'.
Debugstack was nil.
```

### Reproduction Steps

Go to game and wait for bug.

### Last Good Version

??

### Screenshots

![Zrzut ekranu 2023-09-26 113156](https://github.com/WeakAuras/WeakAuras2/assets/6137838/304cdea3-e64d-4088-991c-2a866f649d3c)

### Export String

```Text
11x [ADDON_ACTION_FORBIDDEN] AddOn 'WeakAuras' tried to call the protected function 'UNKNOWN()'.
Debugstack was nil.
```

**Comment by InfusOnWoW** [comment]
That's a issue blizzard has introduced with a hotfix and not a bug in WeakAuras.
