### ISSUE TITLE
More default Fonts please

### ISSUE THREAD

**Issue by hambold** [WeakAuras/WeakAuras2#4619]
Hey,

It would be nice if WeakAuras shipped with a few more Fonts. 
The default ones are not very readable at small sizes and take up more horizontal space than necessary, leading me to almost always use a custom Font instead.

This is a problem when wanting to share WAs with others. 
Either I design them with a suboptimal Font to ensure a consistent look for everybody, or I pick one of my preferred Fonts and just accept that some people will not have it installed and will have to deal with larger and wider than intended texts.

If WeakAuras shipped with a few good Fonts, this would not be an issue anymore.

Thanks for reading and for maintaining this addon!

PS: 
"PT Sans Narrow" and "Accidental Presidency" would make great additons, i think.
![](https://i.imgur.com/XjQuf2K.jpeg)

**Comment by InfusOnWoW** [comment]
I decided that it made the most sense to add more Fira Variants, based on:
* I think we shouldn't duplicate fonts provided by LibSharedMedia_Fonts, telling users to install SharedMedia is fine
* We already ship a Fira font, and having a selection of variants for one font seems more useful than a wider selection.
* I have choosen to include the Black (that is Extra-bold) variants too. These should work pretty well for the mostly short texts that auras use and look distinct enough from the normal font.
