### ISSUE TITLE
[Documentation] TSU Wiki lists incorrect value for Needle in Complex Custom Conditions

### ISSUE THREAD

**Issue by Lisonna** [WeakAuras/WeakAuras2#4627]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The TSU wiki section on [Complex Custom Conditionals](https://github.com/WeakAuras/WeakAuras2/wiki/Trigger-State-Updater-(TSU)#complex-custom-conditions) describes that the `needle` value for a `bool` variable will be `1` or `2`, and not `true` or `false`. 

Testing this, I have found that the value for false is actually `0`, not `2`. 

Here is a weakaura which simply shows as active, and has 2 conditions on a complex condition, checking True and False, then inside the `test` function I print the value for `needle`, which shows only a `1` or a `0`, never a `2`

https://wago.io/jcI7U80xj

### WeakAuras Version

5.7.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Create a `bool` complex custom condition variable and print the value for `needle` after creating conditions which check the variable for True or False in the dropdown. 

Alternatively you can use the wago I created as a test case, but I understand if you want to create it yourself from scratch. 

### Export String

```Text
!WA:2!Dr1ZUTTrt8iOVp0cMIIy10GeGCGqfniUoWinOXfOa9GPIuSluKuPOJJBrR0sUdf3yQLS7UuY2f5qeqrZz)iOZ9KEe8PEKqOOpa5qFa8tqNDjLCs5HLZ(BN)9BNzNkTQnUgTg9nF2CwqcVFsMiaU71eN0nmucQkItlfwq4brjIEjmUYVrZoEnDxgKKettMY7pLLcdVy12M0rqKJ2DdNPeSrJaH8JVNOu8VDuNMc(bzsvY43kZ8Hjax1plmKDYIbn2TV3G(E766nNc(iOhQSyVMT716G2Ugv93diXQO1M2taOPU971SDBNmot5NgtofeUCYyqAvOK0hDQ3b9xue3b6CyHuruqwkfxDdIGGJZ3yMmfIJ3NkTY)O0WWmEGILWVVnrAVPLn(rK)OD962)K93A)Rga9NmkzkcOezWdwdger4JaAjUb(v2MFcqLj4fWaNEzro9CIGr8Jbz6Fw4zoa0yWdKQ3lyuMutqeREhJg2Avy8r1Vk2A6PvWhljVlCHVwtlZfWdkd0MRvt)LkWcnY7mbzaWNSnJ(a7Nckp2y4(BUYe7RSb5rbfnRflV68mEzv3kDdcgZjGxX(NLqH)4AxIXaeCs8ZXwemH(TlpgG0DXAqGYLGPy05sio000L))XocjbV5WCoAow9DHrOnYV5w5xFjU1NeC8irsgN(MBMwtbNOgiJiyd5lkBHtVJb0SeMigtqfkfC4jC481hx)ZLP34D8qJK4eX3vPsLQVTaDvs5S7bEDt)edijdlIyshCiJQIC2f3EzrSyNaud4Rxw8k6OYm6cZ5Vel)SWtrcks0fepe0Pt3onZVUa5LwN5gfdmPrv878ssWvP3OLGDM93NrO4fdX2Z794(QiT0GnnrqpuqsNDyPqrcmHjzyJ3Wso)oV0t3y)oDA6oWPRNx3N5U)t3ZB56q3NDgCNsg9I3lo6tnpC7EGx79708FwokozAlb8lzap40E)VhU9JECb70hCHE5j6clwpRotVtB9s)mLkH3DciW(95A42aFKk6txOLxrTZ1BAS(Q5Imj80virgnxNCgphXcoMdszvJH9diXqvhTyKbOndpCdt0CWBjqe5hbSrrQx7eNqOT8vObC1TChNfRywo6M1BLFOLBqmrk1sos8Irlmxy6q1Cj)dtV5Q5J667tys9BDA05eoBSH474IphfQwxaej0xjmu9dYVE(wlPL3nMXwcjGJwPYzA9m(ElNXegVv(aJ25dZj5(5B5hY4mz0)fEbJx0ZJ(ZYDQPT05SKKXveeZub5o5)Svo1YbnxznxLemP415TR87r1z00BxoVXUC8tdmByAlDVQbDrOaN(ISa7jREzrpslnKoH973WTzZopkJrx8KUhTZx9Yhs7D0p4J0kKnYcN8OJieLwdRLnkV1Wjg4ibyOljonIuDEWQOk)I7LF3DYTQoBs5e05xn50DcjodQkkgglTkvnFA(j5Nwj)mRzRQkdxIpGXSSBQXPw1KUpE7VE7VS2K)6f)7d
```

**Comment by InfusOnWoW** [comment]
It's a wiki, editing it is allowed.

**Comment by InfusOnWoW** [comment]
Eh I see the discussion on discord now. Seems asakawa wanted someone to take a look at whether you are right.

**Comment by InfusOnWoW** [comment]
You are right, the wiki has been edited.
