### ISSUE TITLE
Option to trigger load based on known ability

### ISSUE THREAD

**Issue by gabrialm** [WeakAuras/WeakAuras2#4628]
**Is your feature request related to a problem? Please describe.**
Missing functionality

**Describe the solution you'd like**
When defining load trigger hierarchies, it would be nice to have an option to trigger based on known ability

**Describe alternatives you've considered**
Customer trigger is always an option, but that requires understanding specific nuances of game assets/id numbers and how abilities are differentiated from talents, skills or spells

**Additional context**
For example, I am trying to create a 3 tiered trigger hierarchy for rogue characters, specifically related to the Poison's ability.
Trigger 1: Class == Rogue
Trigger 2: Character Level >= 20
Trigger 3: Poisons ability is known <- this is what is missing

Scenario this accounts for: Rogues are eligible to get this quest at lvl 20, however for Classic HC servers, it's generally inadvisable to attempt the quest solo unless you are at least lvl 22 (to be able to train Vanish). In the above scenario, my Auras to track MH and OH poison will display when the first two conditions are met, but will flash "Missing" until I can:

1. Complete the quest
2. Gain the Poisons ability
3. Brew poisons and apply to weapons

**Comment by InfusOnWoW** [comment]
Spell Known is eaxctly what you want.

**Comment by gabrialm** [comment]
> Spell Known is eaxctly what you want.

I forgot to mention I had tried that, but using that by the name "Poisons" yielded an invalid result, and I was not able to find the "spell ID" associate with Poisons anywhere.

Is there a reliable reference somewhere online?

**Comment by InfusOnWoW** [comment]
the spell to check is the spell that applies poisons, which you can find in the spell book
