### ISSUE TITLE
Can't open WA or use /wa

### ISSUE THREAD

**Issue by SPAMLIGHT** [WeakAuras/WeakAuras2#4629]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

here is the bug code: sorry I'm not good with this stuff and cant figure out what it means:

1x WeakAuras/GenericTrigger.lua:232: attempt to concatenate a table value
[string "@WeakAuras/GenericTrigger.lua"]:232: in function <WeakAuras/GenericTrigger.lua:205>
[string "@WeakAuras/GenericTrigger.lua"]:303: in function <WeakAuras/GenericTrigger.lua:252>
[string "@WeakAuras/GenericTrigger.lua"]:1439: in function `Add'
[string "@WeakAuras/WeakAuras.lua"]:2970: in function <WeakAuras/WeakAuras.lua:2883>
[string "@WeakAuras/WeakAuras.lua"]:3051: in function `Add'
[string "@WeakAuras/WeakAuras.lua"]:2509: in function `AddMany'
[string "@WeakAuras/WeakAuras.lua"]:1156: in function <WeakAuras/WeakAuras.lua:1127>

[string "@WeakAuras/WeakAuras.lua"]:1279: in function <WeakAuras/WeakAuras.lua:1230>

Locals:
self = Frame {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 login_squelch_time = 10
 lastArchiveClear = 1696533799
 RealTimeProfilingWindow = <table> {
 }
 minimap = <table> {
 }
 lastUpgrade = 1696533803
 dbVersion = 66
 registered = <table> {
 }
 displays = <table> {
 }
 editor_font_size = 12
 editor_theme = "Monokai"
}
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras/WeakAuras.lua:3511
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @WeakAuras/Transmission.lua:350
 combat_event_type = <table
}
 regions = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras/GenericTrigger.lua:2838
 InitializeEncounterAndZoneLists = <function> defined @WeakAuras/Types_Wrath.lua:9
 IsEnvironmentInitialized = <function> defined @WeakAuras/AuraEnvironment.lua:208
 form_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras/History.lua:22
 RunConditions = <function> defined @WeakAuras/Conditions.lua:769
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 get_zoneId_list = <function> defined @WeakAuras/Types_Wrath.lua:150
 checkForSingleLoadCondition = <function> defined @WeakAuras/Prototypes.lua:1170
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 CancelDelayedTrigger = <function> defined @WeakAuras/GenericTrigger.lua:851
 centered_types_h = <table> {
 }
 ensurePRDFrame = <function> defined @WeakAuras/WeakAuras.lua:5143
 talent_types = <table> {
 }
 LoadFunction = <function> defined @WeakAuras/AuraEnvironment.lua:661
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
}
 regions = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras/GenericTrigger.lua:2838
 InitializeEncounterAndZoneLists = <function> defined @WeakAuras/Types_Wrath.lua:9
 IsEnvironmentInitialized = <function> defined @WeakAuras/AuraEnvironment.lua:208
 form_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras/History.lua:22
 RunConditions = <function> defined @WeakAuras/Conditions.lua:769
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 get_zoneId_list = <function> defined @WeakAuras/Types_Wrath.lua:150
 checkForSingleLoadCondition = <function> defined @WeakAuras/Prototypes.lua:1170
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 CancelDelayedTrigger = <function> defined @WeakAuras/GenericTrigger.lua:851
 centered_types_h = <table> {
 }
 ensurePRDFrame = <function> defined @WeakAuras/WeakAuras.lua:5143
 talent_types = <table> {
 }
 LoadFunction = <function> defined @WeakAuras/AuraEnvironment.lua:661
 reset_swing_spells = <table> {
 }
 circular_group_constant_factor_types = <table> {
 }
 CheckCooldownReady = <function> defined @WeakAuras/GenericTrigger.lua:2895
 event_prototypes = <table> {
 }
 CanHaveDuration = <function> defined @WeakAuras/WeakAuras.lua:3659
 NeedToRepairDatabase = <function> defined @WeakAuras/WeakAuras.lua:2240
 AtlasList = <table> {
 }
 StopProfileSystem = <function> defined @WeakAuras/Init.lua:461
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 CheckSpellCooldows = <function> defined @WeakAuras/GenericTrigger.lua:2769
 IsO

### WeakAuras Version

WeakAuras 5.7.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Log on

**Comment by InfusOnWoW** [comment]
That's because someone exported an aura from an alpha version and you imported. It will be fixed with the next release automatically. You can install the alpha and switch back to the release versions with the next release.
