### ISSUE TITLE
Nameplate Aura Scaling Not Working

### ISSUE THREAD

**Issue by stevengrimaldo** [WeakAuras/WeakAuras2#4633]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I just updated the WeakAura addon through Curseforge, [5.8.0](https://github.com/WeakAuras/WeakAuras2/tree/5.8.0) (2023-10-08).

It has a note that reads:

> NOTE: This version has a change that affects some aura's scaling. If you log in and things look different and you just want them to look the same as before, go to the "Position Settings" in the "Display" tab and disable "Set Parent to Anchor".

Followed by "If, after doing that, things still don't look right, please create an issue!"

I created (just now) a Dynamic Group, Checked "Group by Frame" > Nameplates, then set Position Settings to "Set Parent to Anchor"

I then added a simple icon aura inside of that and chose
Type: Aura
Unit: Nameplate
Aura Type: Debuff
Name(s): Imprison
Auto-Clone (Show All Matches): Checked

should that icon still scale/fade when selecting/de-selecting the nameplate or moving away/closer as it did before 5.8.0? or am i just doing something wrong?

![Screenshot 2023-10-08 125554](https://github.com/WeakAuras/WeakAuras2/assets/3181158/3da7adc7-482c-4015-b46b-0d3c33f63891)
![Screenshot 2023-10-08 125559](https://github.com/WeakAuras/WeakAuras2/assets/3181158/d2be2df2-3570-47a7-94c2-90cd5af5c1d8)
![Screenshot 2023-10-08 125610](https://github.com/WeakAuras/WeakAuras2/assets/3181158/43864aa8-8cf8-45b0-9dfb-b6757a99d9fc)
![Screenshot 2023-10-08 125619](https://github.com/WeakAuras/WeakAuras2/assets/3181158/f492b69c-2e0b-4ad5-8993-d5a6df0c2971)
![Screenshot 2023-10-08 125625](https://github.com/WeakAuras/WeakAuras2/assets/3181158/63be8aab-29fe-412f-9ae6-0cb79d2413ff)

### WeakAuras Version

WeakAuras 5.8.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
no error
```

### Reproduction Steps

1. Create Dynamic Group
2. Set Grow to "Right"
3. Check ON Group by Frame
4. Set align to "Bottom"
5. Select Nameplates for Group by Frame dropdown
6. Ensure Position Settings is set to "Set Parent to Anchor" checked and ON
7. Set the "To Screen's" position squares to be top left yellow box
8. Create an Icon Aura inside that dynamic group
9. For Trigger 1 select type Aura
10. For Unit select "Nameplate"
11. For Aura Type select "Buff/Debuff"
12. Add a spell name or id you want to show up on the nameplate

### Last Good Version

WeakAuras 5.5.0

### Screenshots

![Screenshot 2023-10-08 125554](https://github.com/WeakAuras/WeakAuras2/assets/3181158/04d66f01-42a4-45b4-b0da-088b43ad8b20)
![Screenshot 2023-10-08 125559](https://github.com/WeakAuras/WeakAuras2/assets/3181158/89383484-f126-4174-a06e-ea5355ffaad8)
![Screenshot 2023-10-08 125610](https://github.com/WeakAuras/WeakAuras2/assets/3181158/e1fb48ee-7d4c-4ead-ae59-9f9bc00024be)
![Screenshot 2023-10-08 125619](https://github.com/WeakAuras/WeakAuras2/assets/3181158/e739fff2-0978-4212-b66c-391679f72744)
![Screenshot 2023-10-08 125625](https://github.com/WeakAuras/WeakAuras2/assets/3181158/7e161146-c469-4cbb-aea9-c4241a8b2247)

### Export String

```Text
!WA:2!fsvZUTTrx0iq4VGp6K0eLu3a30wJ020M(JrIbsqrxKwrfjBviBlmK(N0IIOHKJehyQzyNzOLL3fHG2KT6rqR7kTOpa(j4cH(eKhb)e07qkxeKnDZmdjV35CVNZ5Yk7xvtE06F36pO6GQXvJF1gtOQO2mrFtYlx5nHsvmt5rJokwjZYUUxk)0tPQ41cKYudptDYU96PzMkQrlomJkIsKQosUWOc2Tt7gndMvEn1LPs1pvPsfNSRNRz1kdKP2tWnDv0idxk0pMOnuLXnShxW1jUE4MXDSrX73NP0REp1IJ)(0ywyEVEbJYyQTA0UtZ9A7zWhi0CfDJX6mwAARyT7B05HSJzcJpgn)KzpVEn)GN7huJe4LJxEywkDetre0bmTlPi0WTy0utY)MAhfdtL43Pr72tYflkb3zrY08bc)mAeZjurJ556xELXyZ1MpGBsi0uEFbH0AZTcM1tHa4Buud1rHnP9gQmfrGW6B7CxVujnUzOHMIiUczqoYWUEyFeTc8vUKOuQwBp5P5NYSh2iNhpB0MB26WdL3)OoEZdxiuLmTJJthNhS(JMOzP9keKPE7geS72wnrrf8budlHOTv)seDeIRZ0ieBMYsQ3TnjSu4sMwU3iUpl7g()wovXwRzEA6AhKWnSPQIgWMZzXJqAKh1xjZZwKLpwTl5PLkJNqkyNZTaiOP7JYjM2RNtZnOry3Sc93nmsk6X77MDJsNutlT1bruy6(g8BiZjmnr3IufsQ90w75pwjhwkbNvIyPv8)pUVIhx0jKNo1iJoUeWBx5pw(U84n2HnCApSjQZvrPSUtSrFap2KS85VfY28d9RtA0yhsQvuxEHBULaXWXd70HWNHLGHAR)kZPVTTEYo12UrN21cAmfl9yEzloJl6jvdksWDsPqGhFmCLMNXOARjPya8YWnHNmpgTZ2p)CR5wPz2lsp2gNT2GN4nGYfnHdkIgoeEg8Z4(vF33unA1x9Pt5y2(YCve7oxcwQc8)QaxoSEJDcAqMhHZ0XYHc)H8mw3ZU4rRQN4ztSl8Ex7EW1)RP6e5W6POyQ7QqZ(oip1DIDSRygA1XTgKP4APa(q4oWhbFm8(UWkWha3EInaCEZWGvDXQ7wWn8qp5wWNy1B8pahZckNT2wgZ(Zlb)WRp)iglRMDkWqS8qc8q4xXzFn1yjgwc8fRUcCZ54GK1(BDEI4WegVFI5fWx2eUVDub(6I1VPy9Blw)EOlS(m1dhD0jpJLycsH9TkW7sK)Y)n1c75MDRlORa2jMNY10WuwCcSmELUWvDHR56DQuoOcS1c)hb9FRTbj6Irvh4ZDidT(VxKvfj16lUpKiW(M1fQ5Q4cRhgB52W24)wYsOoqG74lGUl8JUvp(Vp8Fo
```

**Comment by InfusOnWoW** [comment]
"If, after doing that, things still don't look right, please create an issue!"

So where doesn't it look right?

**Comment by stevengrimaldo** [comment]
The icon doesn't scale like it used to when the nameplate grows or shrinks, prior to the update if you clicked on a nameplate and it got bigger so would the icon, now it stays the same size but its unclear if that's a setting/user thing or an actual bug or difference in execution/design.

but as a user i'd expect the icon to scale with the nameplate as it grows/shrinks as it did before and also indicated by the tooltip.

![Screenshot 2023-10-08 131303](https://github.com/WeakAuras/WeakAuras2/assets/3181158/b2fccbc1-17bb-494d-901b-e2b0983d4ff9)

**Comment by stevengrimaldo** [comment]
Another example is its translucency, it used to match the nameplate but now does not either along with the scale.

 ![Screenshot 2023-10-08 133037](https://github.com/WeakAuras/WeakAuras2/assets/3181158/63948137-af2c-496c-b755-2b51d7f50161)
