### ISSUE TITLE
Something is off about Load Conditions with Spell Known

### ISSUE THREAD

**Issue by ljosberinn** [WeakAuras/WeakAuras2#4638]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

This WA should show `Upheaval` while talented into `Font of Magic`: https://wago.io/WGqPBXKqL
Since the latest release, it no longer loads:
![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/08874481-c361-4970-b063-cfead8d751b5)

This WA should show `Upheaval` while NOT talented into `Font of Magic`: https://wago.io/zjJRJ2eFU
Since the latest release, it loads when it shouldnt:
![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/6d31959e-004e-4a4b-970b-ab28efeb8573)

~~I'm not sure whether it always behaved like this in terms of `IsSpellKnown`:~~ **confirmed** it behaves identical on PTR so likely no change here
![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/b25e6078-ed44-43f6-bb0b-b1aa07170154)

Meanwhile on PTR, WA 5.7.0 works fine:
![image](https://github.com/WeakAuras/WeakAuras2/assets/29307652/691c9daa-cc49-42ea-b127-7873220c4b35)

The actual cast spell id in combat log is also accurate: https://www.warcraftlogs.com/reports/MRczQjFaLC1ygYZb#fight=2&type=casts&source=18&ability=408092

### WeakAuras Version

5.8.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

all in the description, im sorry

### Last Good Version

5.7.0

**Comment by mrbuds** [comment]
This is solved after reverting https://github.com/WeakAuras/WeakAuras2/commit/68b6d98fb178f8285ae24fb67f65229aa6cf34f2
