### ISSUE TITLE
Better sparks

### ISSUE THREAD

**Issue by Amanthuul** [WeakAuras/WeakAuras2#4640]
**Is your feature request related to a problem? Please describe.**
For my castbar I have to make additional progressbar auras just to have nice vfx like DF blizzard castbar uses. Also custom fade-in code.

**Describe the solution you'd like**
*Multiple sparks per progressbar
*Frame strata adjustments for sparks
*Animation for sparks (at least fade-in and fade-out at given progress percent)

**Describe alternatives you've considered**
Just that ^ 

**Additional context**
Like here, i had to make 2 auras for actual bar + vfx glow and spark itself.
<img width="352" alt="image" src="https://github.com/WeakAuras/WeakAuras2/assets/18071324/58121c68-0ec0-4500-8454-0c4fa4ba6d50">
Also had to hack some custom code in conditions.
```lua 
function()
    if (aura_env.opacity == 0) then aura_env.region.bar.spark:SetVertexColor(1,1,1,0) end
    local conditions = WeakAuras.GetActiveTriggers(aura_env.id)
    C_Timer.NewTicker(0.05, 
        function()
            if (conditions[1]  == false or nil) then aura_env.opacity = 0 return end
            local remaining = aura_env.state.expirationTime - GetTime()
            if aura_env.state.duration/remaining > 1.14 then
                if (aura_env.opacity <= 0.9) then aura_env.opacity = aura_env.opacity + 0.1 else return end
                aura_env.region.bar.spark:SetVertexColor(1,1,1,aura_env.opacity)
            end        
    end, 30)
end
```

**Comment by InfusOnWoW** [comment]
Multiple sparks is supported via ticks, they are essentially sparks with more features. Including rudimentary control over the frame strata.

As to animations for sparks. We certainly at one point want to make animations more powerful. But that's a long way off and not specific to sparks.

**Comment by Amanthuul** [comment]
As far as i tried, tick texture somewhy is rotated 90 degrees from regular spark and don't go beyond set "thickness"
