### ISSUE TITLE
debuffs on focus target showing when no focus exists

### ISSUE THREAD

**Issue by hampussellden** [WeakAuras/WeakAuras2#4641]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The icons tracking debuffs should only show if a focus target exists and the debuffs are found. They do show in those cases now but they also show when no focus target exists at all.

### WeakAuras Version

WeakAuras 5.8.0

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. import this [weakaura](https://wago.io/m4BsgH60n) on a warlock
2. try focusing a harmful target
3. clear focus

### Last Good Version

WeakAuras 5.7.1

**Comment by mrbuds** [comment]
This aura have the option "Show if Unit Does Not Exist" enabled

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/704254d6-67cc-43fb-b83c-273885fd95e0)
