### ISSUE TITLE
Multi-Target Aura Trigger loses matches on infinite duration buffs after 60 seconds

### ISSUE THREAD

**Issue by Lisonna** [WeakAuras/WeakAuras2#4644]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Infinite Duration auras fade within a Multi-Target trigger after exactly 60 seconds of being applied. The aura remains on the target but `matchCount` on the Trigger is reduced. 

This applies per match. So, if you start a timer and apply an aura (`matchCount` reads 1), wait for the timer to read 0:15, and apply an aura to a second unit (`matchCount` reads 2), when the timer reads 1:00, the `matchCount` will drop back down to 1, and when the timer reads 1:15, `matchCount` will drop down to 0. 

The auras remain on the units even after `matchCount` drops to 0, and the `matchCount` does not increment back up if I target a unit with the aura again. `matchCount` will increment again if the aura is applied again. 

### WeakAuras Version

5.8.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No LUA error
```

### Reproduction Steps

Steps below create an aura from scratch to show the issue. Following these steps produces the aura in the export string, if you want to use that instead. 

Create an Icon. 

Display -> Text 1: `%matchCount`. 

Trigger -> Aura -> Multi-Target -> SpellId: an infinite duration buff (for my testing I am using 394036 -Serrated Bone Spike (Assassination Rogue))
Aura Type: Debuff (Or buff if above is a buff)

Cast spell on a unit (I am using the Training Dummies in Stormwind) and start a `/timer` at the same time. Some time later, cast on a second unit. You should see Text 1 begin at 0, and increment to 1, then 2. 

Observe Text 1 decrement to 1 at 1:00 on the timer, and again down to 0 60 seconds after your second cast. 

### Export String

```Text
!WA:2!LrvZYnorq41LHckLQOynSPyP4qQqrUrQLSSPaUz51EtO8pzLuiHFThj1wA2ipJyMr2o526lSC1pc(aN4KFe8tGkx8eSh4bWpb0Zi5Kfqhu193mt3F9x3ZuPvTr1cRf(QpDbnGZC5zIa4tUNyAVHdLGQI46sJLewqmxCgNYu(nA21RPZ6aopjKpH5oHMcdwT1TzyeeBRd3GzkbnkceY37arP5FyRUofCizcYrR0)LPqscnu(X(p(R)Yh94JDGXaMJtasIk(1YmFJ)zcyiDQJ7znB3EM5iNgkT2KjHMtjbk3cKb2zmQYzuwII6WiJaP1TrWnBigHL9Bu31RVRxDhVfHGpc6H8rCsDNoToV98mwjpTsVpgx6yWRWVdpe(Z7TblFqWijFhwuuo733CfaP1rcfOCikkpEUesgAKP83gtGKOWAubXlqE4ar4zKFZU57SgD9jbxfj4zSWx9G0AkyQQVmMGs4LLIE6dnGMFd5IreCdLg2modMF7Yl)meliUbgmv67)gHQbpHl(2kvQu91fOBzND9Z96L(bgqsMIJNNgCbnufBxhD3uKu6ui0a(Y1fdaFFj1wzw)fzsfD41yLk4kSk9qq7U962mFhbwG69SWSXadnQIFZlRgnpBjO3S3ZZiHOcr2ZZ7FjcBZ0Ad2eUi8cbjD2fLgfeymvs9tGbL18BmKME)t72TPtF7EEE964C6ZoXB9TP20Y7DUx7t728oux6nWdt3))P53jTLi5huQgBBu)96Oe(Kwc4xZawW1N9wp6WJEsHgOxyL(3t1Zby7V6mTNMbR9ZukoR3yqKqUEHgUnWIuXpyP2ERamx704wbCfoZ)STiXMDULggw4ftdUIbszvZbDdijqvBTzSbOnfx8(MSzJAjiI9JbAuS6L2jCsylFfEaMA38DTS1Z1AdNGeIuwaHIK2yHWmmRRJ83n9d3E5xpb8uQKGnLW45egDKPOp2rQicvRvarcUkHPmFN8DqLmSux6RFxqib8DJq5m9(mX(a7rekRv(pA2D(pL)Z5)s(b(dPmQm()cVKYk6qy8SCMygCTVHZhvrOVmJ39oo)hSYhyzJhxzTqXdgxCr(JQ8B7SpnmD)o63o(CpIicu7vh52ED0T)aD7FVtLYmW5UH5Ldf4Jmy9GZVv3umt0sdPPUVBdNMn7EugnCz00x88RAFjxef5Jf4qAKLGY05gItRHD0gL6h(md(ocmWHKKgtQUqRgudZTMTvJhSgVWIzQxAXc1Kop5WV6WVO24)6Y)j
```

**Comment by InfusOnWoW** [comment]
That's by design. If you want accurate tracking you should use the nameplate unit.
The multi mode relies on combat log events, which are not guranteed to happen, thus after 60s a match is automatically removed.
