### ISSUE TITLE
Other scaling after the update

### ISSUE THREAD

**Issue by Loregon** [WeakAuras/WeakAuras2#4651]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

After upgrading from 5.6.0 to 5.8.2. I noticed a different display of a pair of my WA. Most often this is the size.

https://wago.io/xI1_S26mN
There was also another display layer. Now the name of the opponent is visible...
![image](https://github.com/WeakAuras/WeakAuras2/assets/56803265/2c6e8ede-e451-4aad-ad34-c740766978fd)
https://wago.io/FfRRTmLIE
![image](https://github.com/WeakAuras/WeakAuras2/assets/56803265/afe469e8-75a1-45fb-a096-677468679d6f)

Before the update, I played on the WOTLK PTR (ICC test) and there were no such changes on the old version

As such, there is no problem, everything can be adjusted. But is this a new base?

### WeakAuras Version

WA 5.8.2

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Taunt any mob
2. Mob swing any party member

### Last Good Version

WA 5.6.0

**Comment by mrbuds** [comment]
The swing timer aura is anchored to unitframes and use a scaling ~= 1, we are working on fixing that scaling
But for the first aura linked, scaling is set to 1, so the fix wouldn't affect how this one is displayed

Both exports were made with the last version of weakauras, it applied irreversible migration to the data, so it's not possible to test how they were working with an older version.

**Comment by Loregon** [comment]
I opened PTR, there was version 5.7.1
Here they are
https://wago.io/ZNshx8MMG
https://wago.io/J9dCeXSCH
> 
> Both exports were made with the last version of weakauras, it applied irreversible migration to the data, so it's not possible to test how they were working with an older version.

**Comment by mrbuds** [comment]
Thanks

**Comment by mrbuds** [comment]
![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/fe602b63-4e62-4540-a231-0bd17464b31f)

This group had the "Set Parent to Anchor" enable, but this option was not working, it was fixed between 5.7.1 and current version.
How it is working now is how it should have worked, you can disable this option to restore old behavior.

There is still an issue with group scaling not applied but this is tracked in ticket #4637

**Comment by Loregon** [comment]
> This group had the "Set Parent to Anchor" enable, but this option was not working, it was fixed between 5.7.1 and current version.
> How it is working now is how it should have worked, you can disable this option to restore old behavior.

Thank you very much!
