### ISSUE TITLE
'WeakAurasOptions' tried to call the protected function 'resume()' with available companion updates

### ISSUE THREAD

**Issue by linaori** [WeakAuras/WeakAuras2#4652]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Reporting this issue just in case. I can't accurately reproduce it every time as it seems related to addons off-loading processing over multiple frames after logging in. 

Whenever I log in or reload and I get a notification that there's a weak aura to be updated (through the companion app), I might get an error opening the WA options through `/wa`. I can't reproduce this with just WA enabled, and I need to enable a bunch of addons to even somewhat activate it.

When (re)loading is finished, especially in Valdrakken, my FPS is a bit lower. During this period if I open the WA options and there's an update available for a specific weak aura, it might give me 2 lua errors (see below). The more addons I have enabled, the higher the chance is this triggers. It's not _specifically_ when I just load in, that's just when I can reproduce it most often. I've also had the errors trigger a few minutes into just standing in Valdrakken. Another scenario where I managed to occasionally trigger it is when I open `/wa` during combat and then it opens when combat ends.

I know this is very little information to go off with, but I wanted to report it just in case others run into the same issue. I've had this issue trigger for [this particular WA (on version 94~96)](https://wago.io/Pd53s_NPU/96)  on 2 different characters, of which one doesn't even load the WA as it doesn't meet the loading conditions.

I can provide a list of all addons I have enabled if needed, but even with the full list I can't accurately reproduce it. I've tried to forcefully reproduce it for about an hour now, just getting inconsistent results. I suspect this started happening after the "macro fix" from Blizzard, but I can't verify this. I just know it started happening to me recently.

### WeakAuras Version

5.8.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
(the resume error is always triggered first, the UNKNOWN() happens after, just pasting it first cause it's one line and won't be missed)

[ADDON_ACTION_FORBIDDEN] AddOn 'WeakAurasOptions' tried to call the protected function 'UNKNOWN()'.
Debugstack was nil.

[ADDON_ACTION_FORBIDDEN] AddOn 'WeakAurasOptions' tried to call the protected function 'resume()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `resume'
[string "@WeakAuras/WeakAuras.lua"]:4101: in function <WeakAuras/WeakAuras.lua:4084>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

### Reproduction Steps

1. Install a bunch of addons, can provide a list if desired
2. Have an update ready through the companion app for https://wago.io/Pd53s_NPU/96
3. (re)load and type `/wa`

**Comment by InfusOnWoW** [comment]
That's a bug that blizzard introduced with the ClearTarget change.

Now you'd assume that after 3 weeks of addon authors reporting that, they would have fixed their garbarge hotfix. You'd underestimate how unprofessional their handling of bug reports is.
