### ISSUE TITLE
cant use wa

### ISSUE THREAD

**Issue by Dovelol** [WeakAuras/WeakAuras2#4654]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

![1697344776097](https://github.com/WeakAuras/WeakAuras2/assets/11696600/e8595ca7-3aa8-41fb-baf8-0fea5c4d3ebf)

cant use wa

### WeakAuras Version

wa 5.7.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1

### Screenshots

1

### Export String

```Text
1
```

**Comment by mrbuds** [comment]
> ### WeakAuras Version
> 
> wa 5.7.1

Updating to last version will fix your problem
