### ISSUE TITLE
Class and Specialization List - Difficult to Read - Class color text?

### ISSUE THREAD

**Issue by Lisonna** [WeakAuras/WeakAuras2#4657]
**Is your feature request related to a problem? Please describe.**
The dropdown lists for Class and Specialization are hard to read quickly. It's a very long list of text, and the class/spec icons are very small. For my eyes at least, the two icons bleed together because they're so small and close together. The colors do not stand out so I have a hard time quickly scanning for the spec I'm looking for. I end up having to scroll back and forth till I find it, the icons aren't big enough to jump out. All the required information is present, it's just hard to read. 

This also applies to the multi-selection check box list (In the Load tab). However, the checkbox list is _slightly_ easier to read because the options are slightly larger and are more separated. I still experience difficulty quickly finding what I'm looking for, but it's not as bad as the dropdown. 

**Describe the solution you'd like**
Could the text of the spec names in the dropdown be class colors? (This wouldn't help colorblind folks unfortunately, I imagine they have an even harder time scanning the list with their eyes). I feel that class colors here would make each entry have a quick standout association. This may have problems contrasting with the background, I'm unsure, but that's the best thing I can think of. 

**Describe alternatives you've considered**
Icons or text size being larger in the dropdown is also an option, but I think that coloring each row with text color would be better. 

**Additional context**
![image](https://github.com/WeakAuras/WeakAuras2/assets/70078996/6c8ef754-cf0a-462a-87fe-8783ffc792f2)
![image](https://github.com/WeakAuras/WeakAuras2/assets/70078996/7d8e1171-e9b8-4c14-a115-0292055f194b)

**Comment by glassleo** [comment]
Could we also get this list sorted in a way that makes more sense? Like alphabetically by class like: Death Knight, Demon Hunter, Druid, Evoker, ...?

Right now they are just sorted randomly (Mage, Paladin, Warrior, Druid, ...) which makes no sense.
