### ISSUE TITLE
Per-WA option to set which tab should be in focus by default.

### ISSUE THREAD

**Issue by hambold** [WeakAuras/WeakAuras2#4658]
**Is your feature request related to a problem? Please describe.**
If a WeakAura is intended to be interacted with or configured in some way, often one particular tab will be of interest to the user.
In those cases, giving the author control over which tab should be in focus whenever this WA is selected would help highlight features like Custom Options and be very convenient for WeakAuras we edit often.

**Describe the solution you'd like**
A new flyout menu option when rightclicking a WA, listing all the tab options. Whatever tab is chosen there will be in focus every time this WeakAura is selected.When multiple WeakAuras are selected, their focus is ignored and the Display tab will be in focus.
Groups should have this option too. The Group's focus setting should take priority over whatever its children are set to.
Integrating it like this feels the most intuitive to me, it avoids focus conflicts and it doesn't clutter the existing options..

**Additional context**
Here are some examples that made me think this would be handy:

Many users seem to be unaware that WeakAuras can come with Custom Options. Allowing the author to have that tab in focus by default would prompt some users to have a closer look at that unfamiliar window when they first install a new WeakAura.

I have some WeakAuras I use to highlight specific buffs/debuffs, either on myself or on the group. Whenever new content releases, I make many new entries in there. This would be an example where I'd set the Trigger tab to be in focus by default. 

![default tabs](https://github.com/WeakAuras/WeakAuras2/assets/104383249/94795848-2a2e-4516-a2e7-45e64b59f978)

**Comment by InfusOnWoW** [comment]
Nah, that's not going to happen. You aura sounds like it duplicates trigger settings on the custom options tab which is a terrible idea, anyway.
