### ISSUE TITLE
Key binding display - header no longer shown

### ISSUE THREAD

**Issue by mbattersby** [WeakAuras/WeakAuras2#4659]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Looks like header= in Bindings.xml is now non-functional (on retail), so the keybindings are not obviously part of WeakAuras:

![image](https://github.com/WeakAuras/WeakAuras2/assets/1300207/4d7aa303-bad1-41df-b290-c661f80474e1)

Fix is probably to remove header= and set category="BINDING_HEADER_WEAKAURAS", but I don't know how this interacts with classic/classic_era. Probably very poorly I suspect.

It seems like with DF launch using anything other than category="ADDONS" caused taint but it looks to have been fixed.

See: https://github.com/Stanzilla/WoWUIBugs/issues/305

### WeakAuras Version

WeakAuras 5.8.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
N/A
```

### Reproduction Steps

1. Open the keybindings
2. Observe

### Last Good Version

I assume it's been this way since DF launched

### Screenshots

See above.

### Export String

```Text
N/A
```

**Comment by mbattersby** [comment]
Also: https://github.com/Stanzilla/WoWUIBugs/issues/284 for the taint fix

**Comment by mrbuds** [comment]
Thanks for bringing it up, the change you propose works for the 3 released versions of the game
