### ISSUE TITLE
[Idea] Modify how the custom text function operates. 

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#466]
Just a bit of brainstorming. 

Custom text doesn’t play nicely when it comes to auras with multiple text regions. Currently you have to manually set the text on at least one region if you want custom values on both text fields, which I doubt anyone thinks is ideal. 

There are three potential solutions for this that I can see:

* Multiple custom text functions. Whenever you type `%c` into a text box, a new edit box appears, waiting for you to write a script for it.

Pros: easy for users to adapt to. Anyone who is comfortable enough to use one custom text function should be comfortable enough to use a second. 

Cons: Doesn’t scale well, and if the user wishes to make a change to the text, this can multiply the interfacing required to make edits, making the interface a bit less pleasant to use.

* Accept two return values from a single custom text function. First value returned goes to the first text field, second value goes to the second.

Pros: Compact interface, only one edit box to finangle with. 

Cons: Places burden on the user to remember exactly which of the text options is the “second”, and which is the “first”. Is the left text the first? The top? And what about the custom text functions which are used for chat message actions?

* Accept arbitrary returns from custom text. Use a new replacement pattern along the lines of `%1, %2` or `%c1, %c2` or similar to specify which value should replace which substring.

Pros: Scales beautifully, and allows the user fine grained control over text with fewer concatenation operators or string.format calls if they wish. 

Cons: While existing data in saved variables could be reformed as needed to work properly, there is the problem of user knowledge, and users who were familiar with how the old %c system works would need to relearn this. While a small change, it would still require retraining. Additionally, how do custom chat messages respond to this change?

**Comment by emptyrivers** [comment]
The question I was asking about the custom chat stuff is more, should the way that those scripts work stay identical to the way that the text display script does (this would mostly cause an issue with the second proposal, since there would be some amount of special casing to get it to work nicely)? I'm of the opinion that they should, for consistency's sake, if nothing else.

**Comment by Stanzilla** [comment]
%c1 %c2 imo

**Comment by emptyrivers** [comment]
Implemented in the next release.
