### ISSUE TITLE
Auto tick "Hide All Glows" when you add an External Glow to an Aura

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#4664]
**Is your feature request related to a problem? Please describe.**

It's so easy to forget to tick "Hide All Glows" in [Actions - On Hide] when I add an External Glow to an Aura (in Actions or Conditions. And that's for someone who understands that it is needed in 99% of cases. For those that are newer to the WA settings and how External Glows are handled it's a bit of a "gotcha". 

**Describe the solution you'd like**

What I'd like is for the "hide all Glows" setting to be added automatically any time you add a glow. I can't really think of a situation where someone would specifically not want this, but I think it's okay for people in that situation to have to remember to untick it tbh.

**Comment by InfusOnWoW** [comment]
The problem does exist, but that solution is not a good idea.

**Comment by InfusOnWoW** [comment]
We could switch the default for new auras though. (Not trivially, but I think we can.)
