### ISSUE TITLE
Icon Picker smarter sorting

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#4667]
**Is your feature request related to a problem? Please describe.**
It's a bit frustrating when you enter a spellId or something like "Corrupt" in the icon picker search and the first few results don't match what you're looking for.

**Describe the solution you'd like**
when typing in a spellId, ideally it should list icons first that match the spellIds name and or spellId. I mostly enter spellIds but might be neat to have this for names too, e.g when search is "Corruption" it should list all icons that consist only of "Corruption" name first.

**Describe alternatives you've considered**
pain
![](https://i.gyazo.com/43520ede0f897e38a5d02a8946bc0b9e.jpg)
**Additional context**

**Comment by InfusOnWoW** [comment]
If you enter a spell id only the exact icon is displayed.
