### ISSUE TITLE
Nameplate Aura triggers to be filterable by a list of NPC IDs

### ISSUE THREAD

**Issue by ZingusWoW** [WeakAuras/WeakAuras2#4669]
Currently with an Aura -> Nameplate trigger, you are able to filter by NPC ID. I would love it if this could be extended to a list. 

My use case is for a singular pre-pull Hunter's Mark reminder for raid bosses.

Thanks.

**Comment by InfusOnWoW** [comment]
This is in the next release

**Comment by ZingusWoW** [comment]
Thanks very much!
