### ISSUE TITLE
Usage: local continuationToken

### ISSUE THREAD

**Issue by pbb-nor** [WeakAuras/WeakAuras2#4678]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

bugsack was going highwire in ulduar
i have no aura loaded or unloaded at all, just the addon itself

### WeakAuras Version

5.8.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
1396x FrameXML/AuraUtil.lua:65: Usage: local continuationToken, slot1, slot2, ... = UnitAuraSlots("unit" [, "filter"][, maxSlots][, continuationToken])
[string "=[C]"]: in function `UnitAuraSlots'
[string "@FrameXML/AuraUtil.lua"]:65: in function `ForEachAura'
[string "@FrameXML/CompactUnitFrame.lua"]:1370: in function <FrameXML/CompactUnitFrame.lua:1341>
[string "@FrameXML/CompactUnitFrame.lua"]:1387: in function <FrameXML/CompactUnitFrame.lua:1375>
[string "@FrameXML/CompactUnitFrame.lua"]:1525: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML/CompactUnitFrame.lua"]:191: in function <FrameXML/CompactUnitFrame.lua:187>

Locals:
Skipped (In Encounter)
```

### Reproduction Steps

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/13204629/WeakAuras.zip)

**Comment by mrbuds** [comment]
This is not a weakauras bug, you should report this issue to blizzard
