### ISSUE TITLE
Inconsistency with on show > region.bar:GetSize() started by TSU

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#468]
**Describe the bug**
I show a progressbar on event from WeakAuras.ScanEvents("WA_SOMETHING", duration)
Because of #413 i use a TSU

I want to create frames on this bar, with custom code on show
I need to get the size of the bar, with aura_env.region.bar:GetSize()

The **first time** i do the WeakAuras.ScanEvents(....) after a /reload, GetSize() always return 0, 0
Then if i let the progress bar finish and call it again, i get correct size, for every next calls.

**Do you have an error log of what happened?**
There is no error reported in bugsack

**To Reproduce**
[https://wago.io/ryyTxR_fm](https://wago.io/ryyTxR_fm)

**Expected behavior**
I expect to get correct size every time

**Which version of WeakAuras are you using?**
8.0 branch from git

**Was it working in a previous version? If yes, which was the last good one?**
I don't know on beta, but i tested it on live and i don't get this behavior

If i change the trigger for a aura trigger it always show correct bar size

**Comment by mrbuds** [comment]
asakawa helped me find a way around it, aura_env.region.width give the correct width everytime

**Comment by InfusOnWoW** [comment]
You are deep in unsupported teriority. Whatever the behaviour is, is the behaviour.
