### ISSUE TITLE
Addiitional OR conditionals in various triggers/conditions

### ISSUE THREAD

**Issue by Knbi** [WeakAuras/WeakAuras2#4681]
It's a bit annoying when you're trying to create a trigger for a certain spell being cast from multiple specific units but you need to create a few triggers instead of one. Or if you have a castbar weakaura where you want a few spells highlighted in the same way but the conditional requires you to create a new condition for each spell instead of just adding another one below the previous one.

**Suggestions:**

- when making a combat log trigger and writing a unit name, let us add more than one unit name (so let's say you type WALDOROGUE and then additional field opens below it)
- when making a conditional, allow us to add an additional legacy spell name f.ex. without creating another conditional: e.g., instead of making a "any of" conditional then making a bunch of nested "contains" conditionals, just let us add more spells under the same conditional

**Comment by InfusOnWoW** [comment]
The source name and destination already support multiple entries as the tooltip explains.

The condition thing is a rather minor thing, that would complicate that more than I want. There's also custom checks that can check in any way you like.

**Comment by Knbi** [comment]
> The source name and destination already support multiple entries as the tooltip explains.
> 
> The condition thing is a rather minor thing, that would complicate that more than I want. There's also custom checks that can check in any way you like.

I may have missed out a few things I wanted to add. But take this for example:

https://i.imgur.com/1EJrWbj.png

It'd be extremely useful if you could add multiple entries under specific units f.ex.

**Comment by mrbuds** [comment]
> I may have missed out a few things I wanted to add. But take this for example:
> 
> https://i.imgur.com/1EJrWbj.png
> 
> It'd be extremely useful if you could add multiple entries under specific units f.ex.

Source Reaction = hostile would achieve your goal without multiple entries for specific units
