### ISSUE TITLE
Add icon ID filter for `Spell -> Totem` trigger

### ISSUE THREAD

**Issue by Nikyou** [WeakAuras/WeakAuras2#4686]
**Is your feature request related to a problem? Please describe.**
It isn't easy to check for specific totems and make WA work for all languages. Currently, you can only filter for Name Pattern Match, so if you want to check for a specific totem (`Windfury Totem` for ex.), you need to write 9 triggers with name patterns for all languages.

**Describe the solution you'd like**
`GetTotemInfo(index)` (which I assume is used for totem triggers) provides an `icon`, which is the universal identifier for totem between all languages. Now instead of writing 9 triggers, you can specify only icon match (`136114` for Windfury Totem) in 1 trigger.

**Additional context**
I took inspiration from `Translit` when I saw how he implemented this in one of the WAs.

**Comment by InfusOnWoW** [comment]
You can enter a spell Id into the "Totem Name" field, whcih then compares the name of that spell with the name of the totem. 

From a quick testing of various totems, the names of the spell and totem seem to be always equal, at least in the language I tested.
There's admitely a tooltip missing that explains that functionality, which I'll add.

If there are languages and totems where that doesn't work, I wouldn't reconsider adding an icon id check, but for the moment I don't see a reason to add it.

**Comment by Nikyou** [comment]
I found a weird interaction in my WA if I change the name to spell id. How it is supposed to work:
(Without Totemic Projection) If you have wft buff, it shows nothing. If you don't have wft buff, it just shows an icon.
(With Totemic Projection) If you have wft buff, it shows nothing. If you don't have wft buff and don't have the totem active, it shows both an icon and glow. If you don't have wft buff and have the totem active, it just shows an icon.

With spell id instead of the name: (Totemic Projection talented) if you get away from an active totem, it will show both an icon and glow instead of just an icon.

https://wago.io/DS2x6L2ZB

P.S. I have accidentally updated to alpha version 5.8.3-11-g7d8b1b0, sorry if it will cause inconvenience.

**Comment by InfusOnWoW** [comment]
That aura has 4 triggers and 3 conditions. If you want me to take a look at some behaviour you have to reduce the aura to a minimal example that shows something not working.

**Comment by Nikyou** [comment]
Ok, turns out I was putting the spell id into Pattern Match instead of just Name, it is working correctly now.

**Comment by SpatenLa** [comment]
Revival of the dead tickets!
https://www.wowhead.com/beta/spell=198067/fire-elemental
spell name "fire elemental"
always summons a total called "greater fire elemental"
