### ISSUE TITLE
`Progress Bar`'s dynamic spark icon / spark icon based on different conditions

### ISSUE THREAD

**Issue by sbsrnt** [WeakAuras/WeakAuras2#4687]
## Is your feature request related to a problem? Please describe.

We can specify whatever icon we want as a spark background in `progess bar` aura.
However, we can't change said icon based on dynamic information in `conditions` section as there is no simple option in GUI.

Here is a short demo: 

https://github.com/WeakAuras/WeakAuras2/assets/19862545/691c03e5-01d4-4686-9e21-abca88a3b19d

> **Note**
> The static `icon` on the left is a separate aura and is not part of the `progress bar` aura.

## What is available at the moment

What I want to achieve is having each spark `icon` to be equivalent to the `bar color`.

Here are current possibilities in the `condition`'s GUI:

| Option        | Image | About |
| ------------- |:-------------:| :-----:|
| `Icon`     | ![image](https://github.com/WeakAuras/WeakAuras2/assets/19862545/63b73748-d055-41b4-aaf2-441302356a9b) | related to the progress bar icon, not spark icon |
| `Spark`      | ![image](https://github.com/WeakAuras/WeakAuras2/assets/19862545/deb5bae8-b7d3-4f1a-95a6-252ecaf88f0a) |   limited options without `icon` |

## Describe the solution you'd like

I would like `spark` option to have an additional `Icon` option in `conditions` section.

![image](https://github.com/WeakAuras/WeakAuras2/assets/19862545/e9f179db-4703-4915-bebb-8a71ba9a2d5d)

**Comment by InfusOnWoW** [comment]
Ticks, which are the more modern replacement for sparks now have conditions for changing the displayed icon.
