### ISSUE TITLE
Aura alpha doesn't affect model

### ISSUE THREAD

**Issue by Jerks88** [WeakAuras/WeakAuras2#4688]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hi,

if you turn the alpha of an weakaura to 0 it's model texture stay visible. So the aura alpha doesn't affect the model, but it does affect the text, so i think it doesn't work like intended.

If this is intended there should be an option to let it fade out with the aura by link both alphas.

Greetings
Nico

### WeakAuras Version

WeakAuras 5.8.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. create an aura like a progress bar (i.e. a ressource bar)
2.  add a model
3.  add a condition to set alpha to 0 when you are out of fight
4. take a look to the bar -> bar itself is invicible, but the model is still visible

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/44670299/9d0254aa-8760-4eec-bcad-9586298d0983)
![image](https://github.com/WeakAuras/WeakAuras2/assets/44670299/8d97f238-4afe-471c-a1e9-87291ac994fb)

### Export String

```Text
!WA:2!1z1tVTTrwCtOceavKDDK3nDBH7c3GUgnfnYok)PbPOOqswUslSLvPKJtcka1qYrKtdfNPZmuYY3Qq3eh0B6q)aOd9upPd9dGrrpti0R5IrV2lgf9A6BgslP0U2hKN3BM3)FVFpASDUU5CZ5E8hnwWq8NCaXv6)pprFEVoDey5dnS7J8O12AK)w305EDQr6Wpm5kJXorcjTBl8Hs2QDIcDKeA47D9SCSmIhU21KyH8AzXHU8bPsmbf64t5nOKqPD5k1BvXCQ2yMujsjTb7kVc9UuxCPI73AVcr8a2Q(sjtC)n2q5s5j0nM5tBCZBFMnY5jECAuOBzAaL)FnmmAKzZ83zOKt88WCXFBDE6XFQKCadxkkKipvezJ7HdLnJ60HC4eRYfB2YQzRIMTojsGTe(0(LPczBZquxSiRP(XMnO9X8rm1VkvDPHcgoiOMRi7mf2GJbfA2SrLD2zOsvkZ1o(FyZcqdW8PkwZuq7XUyBWdAbN5vRStJT3FNrrHP(Bw2vqq2ThUvcTkT89lnM4qdTC0bBg4VtXHi7a8NYrUeW((Nbzzmpef8ai4HK5ZhjWbD0j)4SAHBsJ4o4vxQKeQH(dTr8KuxMQFYV(Ix8Yx(YF3id4yceuqrsSFjLq(8Ej67ThdHQj2dokE8vJxzkqoViKYOdLJtyCCUcigX)uWkwDHaiWYjGWApj5SqAfj(S5e8JmIxziOanNts43HeGR5AFRc37oBU54eEmK0N9o60Vyde3bfI1zvqjGlB54dDH57wyUMLdm4jedA8A3m)9UZcg9WFz5H8Z7ftF1Hgli7mcuaZhLzbrhymnHOhrqGYWcbM8OZ11rg9MAt5UG7rtgjoNmzYOaKCMKYrqocN5KucNZBPZCAkNzMjLg76HzxP5xgH4412okiyTd8jsC8kJuLf9Bo(nz)BvL2s)duz6IKwmljPloLYy0S7V2)HXEZ)pVo5GPsi3t1xnVR6YSv0CqraUaKeD0akLkcKNLOfYHyxnZVI9UxKReG9qodS6eqP82NOFWxainKodG2wD1bRWCkvFV6vyRDrAbs4wQM22XRWHmG6fSRFrp2DamDtCSK(CmmXh4Amw)Q5dxJsLkuYwUovUFT12goVwvmQ3a27Cr6LXXoe1SsgwUKCLpYL2)rj4HRUeB5f4od2kZun3(qr7aoIn8G0dj5IZl8PYUaK6j1QxVIPvkWAYfPMYy6m)xdXS3(T2Pw9kZ52e62UEQmpmvMxXNtzMHTIxkaZEC1V6zLXv3ZS2J3RERI7y2xvE36nkfqrUFBckhwAJKYaS)PobiHa8zxlyI1zDBbj0la)B)DZUrbsY6)4YT)5LBBlrbGMVAC)StuY3d7tCaPlPLjU3LI7F)2TBpsDNwHTn1)dUYU6(QGhKKLB21ZShObimv69u9AMsGzCvGPfkU1wSLbbk6QA1WUy3Drh6pcfs6QdW7AcWjC52NGrcCtjhh6j9Vu8kLcPH4PUk4r4vwkOCUadOKUIHQNQs2XpTuxejC74)hiq8tJFw8XXpp(P2DiHeH)FHTqdkBt6YOC5OZXKlaDHqJbmzbfO9ykRjYU4M6hzCQOlLk9BWPEqxSO9FoGiH(J5A4ADlacCAq72(yINV8Yt6WHfCqOHKOmJ0RweexSPzTpTARKppO8SPHjA6QexxCOz9kpOIjSHs37STslnamiybex1(eXXM7cGZetTm(LoIs7AylWDH1iM3o)M5lmwsDs3P8VmE2RFnI70DPHpzTBSwLqm3BGn4mDiEzntaDpBblPIe7MLnRuPEQpPJMpUqeXDs5UF4M3kO6wF2JRWjHklG9tszTsCm27vtTISdYb)5LraetOxje)Z3V2nMtDJMkbMqN3Sh)LJvfyIUg8wRBcRyCEYDJZ9blnShItu7GluS(w2A(I3hUz1LINmKe6q7cZbM9qbryJu2J8rQolpSm(hm4o(OqpS4TU6qgNYuFAq83nHeMaQaM7QtGJo4kQVVq4Zr6p5sC34VoB83KTe0pjZMtyEN83l)TY17NF4F8
```

**Comment by InfusOnWoW** [comment]
This is a wow bug, see https://github.com/Stanzilla/WoWUIBugs/issues/295, you can work around that by adding a property change that hides the model. We aren't going to apply the workaround that is mentioned in that issue, as that's a fragile workaround that breaks easily.
