### ISSUE TITLE
Delete button missing

### ISSUE THREAD

**Issue by mammasaga** [WeakAuras/WeakAuras2#4689]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello. The delete weakaura button is missing. So I have to continusly unload all my unwanted weakauras, or deleting them in the folder. Making simple things like checking if I like a weakaura someone else made and instantly deleting them, a hassle.

### WeakAuras Version

5.8.3

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create or import a weakaura. Can be a 'blank' aura, or a complicated one, doesnt matter.
2. Try to delete aura, button isn't there.

I just want the button back, so I can delete the auras. I have uninstalled. checked all files, tried to download weakauras from other places.  It works on all other computers, so obviously something is wrong with my addonsfolder. I can just reinstall the game, sure. But I would like to know what's wrong. 

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/149841188/ac406c8b-bbcc-4964-bd70-cdb0f49b06f6)

**Comment by mrbuds** [comment]
You ticked "Yes" to "Tested with only WeakAuras", can you confirm?

**Comment by InfusOnWoW** [comment]
If I recall correctly the last time that we had someone with that problem it was caused by another addon shipping a broken version of the drop down library we use. I'm pretty sure it looked exactly like that, thus I'm pretty sure the "Tested with only WeakAuras" was ticked by mistake.
