### ISSUE TITLE
Total duration of CD to trigger.

### ISSUE THREAD

**Issue by Shaterhand** [WeakAuras/WeakAuras2#4693]
Hello, I want to create a WA for Lady in ICC, that only activates when I cast a spell under the Curse of Torpor, which adds an extra 15 seconds to the spell. For example, the normal cd of holy shock is 6 sec, I don't track it normaly, but if I cast under the curse, I want to have a wa that shows the duration of the cd, which is gonna be 21 seconds, if I used it under the torpor. I managed to create it somewhat, but it dissapears if the curse gets disppeled afterwards, I want it to remain. Maybe a total CD = 21 to be added to the trigger list would solve it ?

**Comment by InfusOnWoW** [comment]
That's far too niche to add to WA in general.
