### ISSUE TITLE
Weak aura tells me to update, wont actually update, just recycles over and over

### ISSUE THREAD

**Issue by RogerRabbit10** [WeakAuras/WeakAuras2#4697]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

as per title

FeverHUD :: Druid :: Combo Points wont update, every time I click update it wont actually update, adds it to my list but still says "needs update" nothing changes, done it a thousand times, tried creating a copy

can't even remove it from the "needs update" area

### WeakAuras Version

5.8.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

/WA
click WA circle to update
update aura

rinse repeat

**Comment by Davidmartin5665** [comment]
Can confirm this is happening for me as well for 4 weak auras. Stuck in infinite update loop. Have deleted and reinstalled both wago app and wago companion. Have also deleted all 4 weak auras.
