### ISSUE TITLE
[Bug] [BFA] WeakAura Beta version - "Stack count" in "Use Full Scan" not working

### ISSUE THREAD

**Issue by JeffJeffrey12** [WeakAuras/WeakAuras2#470]
**Describe the bug**
I tried to more or less copy paste a WeakAura from live to beta which simply takes the value of a buff and shows it as a number. Works fine on live. Also works fine with the Use Full Scan. Doesnt work at all if you try to add a "above 10" for Stack Count for example. (Without it it perfectly shows the % value"

**Do you have an error log of what happened?**
No, sorry

**To Reproduce**
1. Go to '...' Beta with the latest WeakAura update and create a WeakAura for following Buff (you can easy make a Enhancement Shaman premade toon and test at the moment) "Gathering Storms" https://i.gyazo.com/thumb/1200/91aae9fc2862d02ea9a84c841799c132-png.jpg 
You can also take this string:
`dSuykaGisQlPG0Oisofj0RiLcZsa3IQyxKQHbkhJQAzG0ZuOmnb11eKTHu6BKsghOY5qQSoKIUhsv7Juk6GkKwiOQhcIMivPCrsYgbHpIuyKuLQtQaRKe9sfemtQs6MuLyNe1prIHscoQccTufQEQOPkvxvHOTskL8vfuERcH5QGO7QGQ9Q6ViPbJQdJYILIEmIMSu6Ys2mc9zfz0sHtty1KsPEnrQzRKBRO2nKFdmCIy5u55cnDkxxP2oP47cuJhbNxGSEsPA)q99F)P4Y0PLpmTG7z8jC6W80SmgCpNF2(S99NtlqWV5tRiy(qaqwk0EDzOWEscwa37x2)qOfD(qHcJ2WWc7tByAdR1j6jeCxESld72ZwruYIfuViyphA8zquismw2Ld7)KrAcnv3jMMkNxaT1LH9uqcqh(NwrWGcbazpHWj0oMpe3SwhZyyEV)0CIPPY9(ZOKATg0(0No4gdgSNGGruqRGo8p3XcsWgzh(NK7ObMP2q0wpnXC1(mUBsc2i7W)eXMlQajLJza3t6P)jjyJSN(WEsc2iJIKYXmG7P2K(N7yrnkPwRbTh(Ni2C9KgmRr5eOjmpnGBo(m2aemf0ZydqWuqJsAcn1teBUIVFz)NJeTkwSbM7nay(2Z4UjjyJmibBKDz)Ne3RvKKHo83EAfbZhsaYyc0CHSNdKZbEt1ZOjiLoiVTDmtaqV5tjoWKRIrfCfPikaOld7jraYEQAU5QMFAfbdkeaKbXInfFszKDVoqw1ZgLyQHDiOdgmT8PdkuTcf2No)XO9e9eMUNcKMYfR385cWAF)Pan5aBjV)CEVmX73U90yRczV)CEVmX73U9KCXIX3FgfOPv9m9(OEzu5BpJskY3FgfOPvDzO3EUJfvYflgp8pBfejki3llO3FoVxM49B3E6aR69NZ7LjE)2TN7yrnkPip8pLOrIXwfYE)58EzI3VD7PJrwV)CEVmX73U9KiJ0ea07pN3lt8(TBpn2Qqg03FoVxM49B3U9STImB7yw9Mpjcqwk0EDzFAFAfbdkKaKXeO5czphiNd8MQNwrW8HeSaU3VS)LHPhcQFiAHJwOAfoem6G7YqVS)Lh7qaNwHOJUWqHdwyA9HbxOqNONqHVC4l7F7PvemOQqSMRQ9nFscaRwqWOErWuHynxv7H)PvemFiaidIfBk(S79bqoeOmYUxhiR6PRMeaupij1tRiypfTpPbZAuobAcZtd4MFsGcrIXYUSNWW90kcguiailfAVUm0Wp127Ojig0tivj3vn(tTdaZxgMo0qpTIG5)COXH(0kcgufacK9esvYDvJ)0kcg0NdvYt22aV5tRiy(QqSMRQ9W)K12kmbaXwunNyAQCX3V90kcguiblG79l7Fz)ld9Y(xESl7F5Wx2)2tIo2CLMJzSlh6zWIwRXHaoFAHQf0WJrxiA9ddfgCNONWW90kcMpeaK9u1CZvn)KrAcak((ZOXC27pBbuj3rdm)Mpj3rdm)CbizlmxqcWC6X8HvmPhD7yrDxnjaO4iyBhJAH0OlAhUURMeaKUGeGWk94bZfKaAML1lc22vsH50OSusTw9IGTDLuSTJrTqA0fTkI5kIvkib0mlRxeGeaCTsH5W09dG5W0PluamhMo0qbWCy6AfcZveRKTDmQfsJURyiYgaNukE7PajS3F2cOsUJgy(nFsUJgy(5cqYwyUGeG50J5dRysp62XI6UAsaqXrW2og1cPrx0oCDxnjaiDbjaHv6XdMlib0mlRxeSTRKcZPrzPKAT6fbB7kPyBhJAH0OlAveZveRuqcOzwwViaja4ALcZHP7haZHPtxOayomDOHcG5W01keMRiwjwjB7yulKgDcuiseZPhZHI5E8G5Adm3ayUtm1WcG5EWCdG5RIOHvY2og1cPrpikejI50J5E8HH5E8G5AdmFcurmFljaM7bZNaveZBbbJWkzBhJAH0OlbiqgfuAmsPJyo9yU6offuJvY2og1cPrxcqGmkObKaeMtpMRUtrb1yLE8G5sacKH5ajMaGIyoZvyUAivj3vnU6ayUA4P07u8I6ayU6offuhaZv7vvq0vhaZvp(aA49U6ayUA4P07u8IxvbrxDamxn8u6DkEz8b0W7D1bWC1Dkk4vvq0vhaZv3POW4dOH37Q1XkXk94bZftiGRW8M1cemM3OCLowjwjB7yulKgDxXqKnaomNEmN4grAcaskfXkXCmhZX8fGKTW8OXiLoI50J5dRysp62XI6UAsaqXrW2og1cPrx0oCDxnjai9OXiLoIvI5yoMJ5lajBH5csacZPhZhwXKE0TJf1D1KaGIJGTDmQfsJUOD46UAsaq6csacReZXCmhZJgJu6inHCvm3ORLcabYIsPiwjMJ5yoMhngP0rAMLPaqGmPyBhJAH0OlbiqgfuAmsPJbWCbjafaZzBhJAH0Olbiqgf0asakaMZ2og1cPrNafIedG5STJrTqA0dIcrIkIvwOwSsSs22XOwin6UIHiBaCsP4TBpr75UtmnvU4L9Fkqw5qSL2QCrbaD5XEgRfrfacK9esvYDvJ)SveLSybnGeGEoazLJiJSgYbKauCiJsQ1IASbBMHO2qm1WeT1tsay1ccgD4FAfbZxbGazpHuLCx143EYE)5irRIfBG5EdaMVmTHGr7y0E7PMl7hgQ)TFa`

2. Click on '....' Aura, Use Full Scan, Add the Spel ID, Use Tooltip Size instead of stacks, Use nth value you take "first", own only and then try with and without stack count
3. Scroll down to '....'  ???
4. See error ???

**Expected behavior**
You normally should see the number pop up with more than 10% value of the buff (Why?! Because with 10% it meens you hit 2 targets and activated the Crash Lightning secondary ability)

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** + 

**Which version of WeakAuras are you using?** Latest Beta version

**Was it working in a previous version? If yes, which was the last good one?** Didnt test, cause this buff was added a few patches ago and is an old artifact ability

**Additional context**
If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by asakawa-k** [comment]
We talked about this a bit on Discord. 
Essentially it seems like using "Use tooltip size" prevents the "Stack Count" trigger option from functioning. Perhaps something to do with the added option to select the tooltip value you want?

**Comment by Causese** [comment]
It works just fine when applying ice barrier to yourself and using fullscan.
ice barrier string: https://hastebin.com/xipatezuli.m
unitbuff dump: https://gyazo.com/df30f108c4746c511eae5364ab6d4c8a

but doesn't work when applying buff from dread gladiator's emblem (can be bought on gladiator realm on beta at the login location)
emblem string: https://hastebin.com/tamebisehe.pl
unitbuff dump: https://gyazo.com/3affc4768588dc6450e16a2775840002

**Comment by InfusOnWoW** [comment]
@Causese that has nothing to do with the original bug report. WeakAuras doesn't use the additional returns, instead it parses the tooltip. I fixed a bug in that parsing for the next release.

**Comment by InfusOnWoW** [comment]
In the new buff trigger system, which we will be part of one of the next releases, the option for tooltips no longer replaces the stacks variable, and thus this is fixed.
