### ISSUE TITLE
Unit Characteristics - Nameplates no longer works after 5.8.0

### ISSUE THREAD

**Issue by sascatuan** [WeakAuras/WeakAuras2#4701]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

This weakaura to mark units / pets by unit name using a texture while showing friendly nameplates, worked up until 5.8.1, after this version it no longer works. Not sure if the functionality was broken intentionally or not. But it still works when reverted to version 5.8.0

### WeakAuras Version

WeakAuras 5.8.1 - 5.8.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

no error the weakaura functions just no longer work after 5.8.0 but still work with 5.8.0

### Last Good Version

WeakAuras 5.8.0

### Export String

```Text
!WA:2!Lr1ZVTrruyISevAfcLAkr00lvCiNcojgAuHlTEDCun4KyTEBlhSK9S782Dh5zNDzMzD(XjKLqXOwjeMkoYbdsiKkQvMkeuqCG)cwzXFbrycrLt5ixkZSo1IcN87xZN)EFV3(MBZ8H5X5X9xYzxKFu1ngGwR4hyVlQO3yuImiIVtSKeXeg893XZtasyeI5QIxpIWKoLRSTDfRIjCA8LcKYyX7SYkAGkqIwzgsRSgh5MHY6wcjIlnmjmI0WXt9JiWONKt89bU4LxIFMz)x9Oeb0I4ZI4qdG6fmw7hejKekrU)ux3aKgzGhmywMEECcWW09hKvbfjebdMvyrwS7qm4K45zVFmWVrLA138M1YqJHcboGOHTnLQCMjkooywW4op5H37V(6(p5lV)Yt6)n)XNF4Xp(7(9F6dx(4V)BN8WFEYhDNjp4WJ)0V44()YZN3I0LWoGWsOl)N35tM84p7KdVR(b)WDxUrhG2bDW)pZrIehOlWKnueLS3OwLl1WUvd7sw2wzXJVWnvS7YLFwFruDVRONUn00U9rznoXJ4I0cVr6LY6Kyksc9eXaLwflmS0XegXN)zTFwETW0E8Z5M(kZyuDoOyKvJ6vQLjBvZgrBRQoyqc7SXNcs9eVlyp1FRimC)x4u1gdWzi6TuZAfR(4bigjmJGRNASz6IMSig8RasanKCG5ldo3yCcpRIw6zcxaUrmSONUMmITQziIWuVnD101oxAX03m9TuMV0)nIAOlqsnwqqpEKmdZ54DNYKCdvTNf4R3rxCH0fhRCDqUD85rjmStaq8dKN4K9oOTjncH9Y2VyknHh4iruL0SGvycvsmMk(TqmClLu7UKJGW8PWJMp96R)vZ3(rZ3(EZ32uNAH0RByLvT2Yuqoa0gNkH9uCfUnhfRLU4luUwPTQBVJzTsLFVsBSrv7Q3QIJikH7coKW4iU0jKW5r8GH8S2iB7(myg4OyhwdKLzTkBVHA4K9j8MC1uRosP0YG0AXVDv94Xd5cnlHX7WenVnG6usPzIMBbycQP9u8enDvaa03GOggfK(O4ZJjcxU64qRzsRLBenI)U5M7gx7hV4fV2tF6FNZraHk5YATcRwy1HYi3Zu)xBUddEDc(upG6NG44lhI4Du1HOXbOCw7sWYGtg5PzRAVajr5Cu)XEeFJIje8i)RUE3TSXCRRCaFVPhPu7A)RwuRfonkBvPY2d1RpKPx0gryEr8P7Flmsz6cv0B4I2deQlozh4sFX8cRRu4QfwnF3F79)Nd
```

**Comment by InfusOnWoW** [comment]
I looked at all the changes between 5.8.0 and 5.8.1 and nothing relevant has changed in these version. 

The aura does work for me with the current version with two caveats:
a) The aura as you exported it is not attached to any nameplates, so I changed it to be attached to nameplates
b) Attaching to friendly nameplates is restricted in certain enviroments, such as raids, dungeons and some other instanced content, so you you need to test this in the open world.

I suspect you probably tested in different environments between 5.8.0 and 5.8.1 and thus detected a spurious difference.
