### ISSUE TITLE
Outlaw rogue's Between the eyes

### ISSUE THREAD

**Issue by JakubHorakDev** [WeakAuras/WeakAuras2#4705]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Outlaw rogue's Between the eyes is now buff on player instead debuff on target.
So I can't currently set buff to be shown when used because it's still in debuff category.

### WeakAuras Version

5.8.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Try setting up Outlaw's Between the eyes buff to show when buffed.

**Comment by InfusOnWoW** [comment]
This is now fixed for the next release, but you can also manually fix the trigger by changing the "debuff" to "buff" and the unit from "target" to "player".
