### ISSUE TITLE
Add conditional option to increase/reduce the remaining time of aura

### ISSUE THREAD

**Issue by Knbi** [WeakAuras/WeakAuras2#4709]
There are situations where you would want an aura duration to be either increased or reduced. For an average user without much experience/knowledge it's frustrating to have to resort to custom code or TSU triggers because modifying expirationTime in conditionals doesn't work properly (or at all). 

So what I'm proposing is that condition tab should have another two options in the "Then" drop down menu: **"Increase remaining time"** and **"Reduce remaining time"**. This conditional would modify aura_env.expirationTime by a set amount of seconds user specifies after the condition for the reduction has been met.

Average user has no alternative to this other than pleading for help with custom code and wasting everyone's time, this in comparison would be a good quality of life improvement.

**Comment by InfusOnWoW** [comment]
The expirationTime is something a trigger provides, modifying that via conditions is not possible. 

The supported way to do that is via a watched trigger and yes that requires custom code.

**Comment by mrbuds** [comment]
Conditions can't and are not meant to edit the state of an aura/clone, only triggers can do that.

This feature request lack a few real world practicable examples where increasing/reducing the remaining time of an aura is needed
The only one i can think of is an attempt to track other's cooldowns, if that's it then i'd support a complete solution working with any spell for any class without too much maintenance (= no code to handle all cdr/proc spells) which is quite a feat
