### ISSUE TITLE
Static progress triggers probably shouldn't expose a "paused" property

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#4719]
In 0e8d47f, a new common condition check 'Is Paused' was added:
https://github.com/WeakAuras/WeakAuras2/blob/0e8d47f663a3c2ece2706aba4a121d135aa727ff/WeakAuras/GenericTrigger.lua#L3941-L3947

The commit message suggests that this is supposed to be visible for any timed progress trigger, but it is also visible for static progress, e.g. Player/Unit Info -> Health.

It's minor, but was enough to trip me up when making a WA today. If it's simple to do, perhaps we should teach WeakAuras the difference between 'common' conditions, and 'common for timed progress' conditions.

**Comment by emptyrivers** [comment]
Doing so would possibly make TSU custom variables more complex to think about, which is the main reason I hesitate to say we *need* to do this.

**Comment by InfusOnWoW** [comment]
That's actually fixed in https://github.com/WeakAuras/WeakAuras2/pull/4677
