### ISSUE TITLE
Unit 

### ISSUE THREAD

**Issue by Enotikik** [WeakAuras/WeakAuras2#4720]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When selecting a specific unit, for instance, 'Focus,' while checking for hostility and the possibility of interrupting a spell, the icon does not appear if the selected unit is not the one indicated. Prior to the 10.2 update, everything was functioning correctly

### WeakAuras Version

5.5.6

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

I need to create a trigger for when a player applies a spell that can be interrupted. Information about the unit: the unit is 'Focus,' the checkbox for hostility is checked.

### Last Good Version

5.5.0

### Export String

```Text
!WA:2!DrvxRrsrx48XIRmIXnJRZgwwcX9Ibe0WsadrqzD6Xjj76KpONjUErGPRU7A6Um9uvZPQEsMalsccgq8M5NWCH4fccdklk4(UKFb1gEXFaXl8kbj)bINQ6jtehyOo1PpF8CoNNtn5Qf7umSy4jVnCWwTBlPQ1)y4h9Ma)b9gP4f9M4PhD5LxoKWdIfW2cgx5xT2MnR5cKaftWLl7kveqvWHXzQc(TXdzCPbHIwDOsjjIgFScyrruqYldJep5oNMjPTcisvZEPuVZn3i(sb4VHiK65KHbZTTiit2hODiyq5rl9GfxjDwJL0dWK3sMstsEuy8Xgvgh8ges9ZA32esy9A13E1DQN7acBkazPkMFc17mJQXHn(CzMpTlLRAG(YoyyRQvA0SvJMvCBczC7xCizkHBUyve0okmf6zSW2cJnjy1gp4A57o3n(7F64RkqhJqFJ180adKhHDzH8qiYGa6oMsWxgl2Fl(P5hvWECxAAXXGTLalnIsa3)d)OX4EBGI42TX21Qx3LBYEH(z8rT6s6z8Xbuevvw)AFNEE9mPfVUBVoLKy746x3tFVHUeEeDHQX0G90ZOFdlIbJopx7rXv0VP35wX)ns03w)w63TaMGF3Ka9IE65McJOTrhetmCfkeRFNP6p(MFAcPhf6hlKkwct1dYLOygm5wFV0BB6iiAg5bd)CG0gZXo5nk1ddzYViJBBxlrsssNLyLBM3emL4pmXfwAaNK8zize5UFBFjnPTLuRVbYDKevgwsiJfekIHDp5aSh7sJme97wsp)z4vFsWErGiJh6htzrX4AZgF)FTaU24BDdzVjcs4jZc48cTlTKBNSefRq(8hNyqSBqcrkl7lrtsOUUBT2o10Rvs)PEoyTslPxRaCOGtrgYuGIKGd5Lmkp36xlcp0q7ckRFCZBPxB1J8(QB59uVV0Zp3wJPogdmcdcziToaHqpZv72Ij2Xos2HMuvEGPOdjaLt8CZpG25R3gpoJXXvCEaTLH1xWbejwe2pTB615B4vXfXC8fk6byVK(eGKA69UvRxzJT9Z55(SoPcq53HbGaIha2(RDPDKB9XTuEO1rN6128t0(PFWJmZoev0DRegUfxU7tOK9QGZl5UBqdzKDBM7RC3adwtEVoeyVfvrK0zrUraqviv(QXQljjnMm9aLiOBoxyUj)647ZctVJ(30)8c6)N(5V8y9Z1)k(F4l)g9VmSnGlwnuyRImT7(Sqv8rxK)Q4QMVyGVFJQU1QTPFGG3MfvyPmw4Wh0Rz1d7LUFfq4giseWJx)H)rJgMNzx)H)5ZE2lqHPNUpHZ6yH2Y6xzv98oCSrEwOHnI6S9DqsX4gkpLsKgCq5rQ4BES5Mj3APJ5jc0xTuR0z6U3uVpk(Q)xndmrHzF6UWqgVTaYtC5HOyaTM5bfPx6CSiUaOBLAT0QTMzCj9odFleR6rFPqrP77V4klUCXU))p)Fc
```

**Comment by mrbuds** [comment]
Your example has 3 triggers including a range check trigger that is not as effective has it used to be while in combat due to a blizzard hotfix.

I can reopen the ticket if you can give a **minimal** example (only the trigger having an issue)

**Comment by Enotikik** [comment]
Sorry, but what alternative method can be used to check the distance, or do we need to wait for an update in the Wiki Aura? Thanks for your answer!
