### ISSUE TITLE
Dragonriding load condition wrongly enables when exiting Passenger Princess mode

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#4721]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

If a group member has Passenger Princess mode enabled (i.e. they talked to Lithragosa to let group members ride along), then exiting that will briefly (and incorrectly) enable the "Is Dragonriding" Load Condition.

### WeakAuras Version

tip of main

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
none
```

### Reproduction Steps

1. Get a friend with ride along enabled (they'll have a buff called 'Ride Along' while on a dragonriding mount)
2. Make an aura with a load condition for "Dragonriding", or import below
3. Hop on
4. Hop off

The aura should appear incorrectly, until the next load condition check.

### Last Good Version

unknown

### Export String

```Text
!WA:2!DrvZUTTrq4iOw0cc4cB1uJgGEingTONkcmqZHEZuMk2fksQu0XoTfvAj3rCxBQDz3DP8p3Io0gGEtpc6CpPhb)eqi0NGCOpa(jOZUKYnP8aXmZo)99TZSn60AAlAl6B2BjprkgklujWx8a1v9NmrdMgQRRfwrejmPAGKlmXTd6ffeUorkZOYlfdVKNdJVDJAanfy(20nEUrXttbL(t(AvT4VVKcXftMeDDoOokO7GoN013GkHKcfz)56Cil7yQ27T6IyygimdrV5xTAu7dggnAy0bHr(fcUjopJCnOcfKPG2l05A8rajZWUp0bkadnC4GGUDxuiQBbV8Dijg(miQs)fsk8xp4oezGsqYEj2VCP4pV7caYpa7NetiXWLSfAiBIJbk)qefAIb7ydWwILlesXy0F)ULBTgvJjjxKQKfc6BEyEldCLzKMrq25SA(m)roJUFtKQPe0HAbFHualU)4N8v68TFNm0wMjv)qJgnA(2kRBAk)dojQF(N6mskmsmv8Kt5udZ)au9UQAXVcOoJVED1v6RQ7OBDNFEH2WNCncqL0GGlcn63RFVGYTuiUS(S05yIRnAIFlQbHWKVDhf)Mh)JfeksmKhhf9EyFtLw7SDPurpvrYNFATqvdmJR5XzW4Am)oJD57CCVEbHJ87hf1)fHh)8JIwFFPhYVbEunIo79QJ9u3Ww)tI6ECVG)zDAM8Yok43karY1d(GN(T7)DvOZEWT2FhAVyX7ZMZTA2Oxhxymsr)zGch7wAn3fePg2NTYkVbAlSkTVNAUTqdpFJfMZZ7BoxMz8KleGw30f4Wesg003kYCg6YXd3XvnFKLaflMb8uM51(zsc9L5BJfyes2PsHIt5I0XXgmhcZUHtlYmCVWKmIwVB5apF7KCLaYvwHLk3qRfELF8(fC6QZzXP9JF658VP9cIGp1rcpluBiktNBbIggAuoy)rLBvU3AAnpnYUaR0aUZt1ZT(5s6E(tjCrNYx58U8Nk)5YFPCV4jCbxZ()MxXfvZ)y(8YF4MxtSdGhY1eCMGYu29wCn7zLN5v(RE(yImE(3iLtBS0itMvT5(5n(d2t4u)VKcZc)V50vtu4tfiaWrZMHx62bYBHey76sHVdGl6W4yegt4PEkUWMrGDx1CvhB8wGfpSDyqqVqswoJ0CPf1CxF5nFtBpEnUcIX0pV6Gw69peM1A2FF2)c
```

**Comment by InfusOnWoW** [comment]
I did some changes which I think should work, although I couldn't test them, for a lack of friends.
