### ISSUE TITLE
WeakAuras not appearing in addon list

### ISSUE THREAD

**Issue by DoomKat** [WeakAuras/WeakAuras2#4723]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I could not find weakauras in the addon list in Retail WoW in the character select screen. I also tried opening it in game using /wa and /weakauras.

I have also reinstalled it.

### WeakAuras Version

WeakAuras-5.8.6

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Go to wow character screen
2. Click on addons
3. Weakauras not listed

**Comment by InfusOnWoW** [comment]
That means you didn't install it correctly. The discord is a better place to debug this, you'll need to clearly document (e.g. with screenshots) where you installed the addon.
