### ISSUE TITLE
"limit per frame"  for dynamic groups when you select group by frame

### ISSUE THREAD

**Issue by nickpwagner** [WeakAuras/WeakAuras2#4724]
My goal is to have a maximum of three spells shown above my nameplates. These icons are in a dynamic group and have many spellIDs as trigger each. Whenever two or more icons are shown, I want them to make space for each other, centered above the nameplates, such as a dynamic group would do when selecting centered horizontally. 
My problem is, that each icon results in multiple spells shown above nameplates. If I limit the dynamic group to three spells to be shown, then often I get three spells from the first icon but none from the other. I want to ensure that each icon can only result in one spell shown. 

If I could put each icon in one dynamic group and those three groups into another dynamic group, this problem would be solved. But since this is not possible, how can I achieve this?

**Spaten suggested in the WA discord to request this:**
ask for a "limit per frame"  for dynamic groups when you select group by frame

The discord post also has a screenshot of what I currently have. Thanks!

**Comment by InfusOnWoW** [comment]
Spaten misunderstood what you are doing, and what he suggested wouldn't solve your problem. What you apparently have is multiple icons that create clones, and you want the limit to apply to each aura's clone list. That's not something we would add. It's doable with a custom grow though.
