### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by Stumpy1234** [WeakAuras/WeakAuras2#4726]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I am using Ipse warlock weak aura kit, its supposed to be showing my siphon life DOT, but every time I log out or switch specs, it disappears.

### WeakAuras Version

unsure

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

logging in or out, switching specs.

**Comment by InfusOnWoW** [comment]
That's not enough information for us to even start an investigation. We would need the aura that is supposed to demonstrate the bug. Also we need your WeakAuras version.

**Comment by Stumpy1234** [comment]
I'm not sure what "We would need the aura that is supposed to demonstrate the bug." means, I thought I gave the weak aura group, unless maybe you needed the specific "children" part of it? But anyways, I'm running weak auras 5.8.6. However, I've fixed the weak aura, have to go into the children part, scroll down to "siphon life 2" to load, then uncheck the talent option, works now.

**Comment by InfusOnWoW** [comment]
You gave us a name of an group, somehow expecting us to know which auras that contains. We don't.
