### ISSUE TITLE
error during logging in

### ISSUE THREAD

**Issue by morvinm** [WeakAuras/WeakAuras2#4727]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

my weakauras stopped working
the addon is active but not working and i uninstall and install again still not working
/wa not working too
![weakaura](https://github.com/WeakAuras/WeakAuras2/assets/152012417/6e633936-57a9-46cb-a7c5-bfca64ca7aa2)

### WeakAuras Version

weakauras 5.8.6

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
in photo it says no other error it does
```

### Reproduction Steps

just not working

### Last Good Version

weakauras 5.8.6

### Screenshots

![weakaura](https://github.com/WeakAuras/WeakAuras2/assets/152012417/dc09ba59-223e-4150-830e-2e0eb046c470)

**Comment by InfusOnWoW** [comment]
We need your settings to debug this, the issue template explained which file to include.

**Comment by morvinm** [comment]
> We need your settings to debug this, the issue template explained which file to include.

setting of what?

**Comment by SpatenLa** [comment]
Your saved Variables file from weakauras. 
![grafik](https://github.com/WeakAuras/WeakAuras2/assets/39881841/dadfdeb6-ceff-4d03-aed1-08d7c355d85f)

**Comment by morvinm** [comment]
> Your saved Variables file from weakauras. ![grafik](https://private-user-images.githubusercontent.com/39881841/285597059-dadfdeb6-ceff-4d03-aed1-08d7c355d85f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjI4MzUsIm5iZiI6MTcwMDkyMjUzNSwicGF0aCI6Ii8zOTg4MTg0MS8yODU1OTcwNTktZGFkZmRlYjYtY2VmZi00ZDAzLWFlZDEtMDhkN2MzNTVkODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE0Mjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNDdlMjc3Mzg4MmFlNTQwY2I1YzllY2QyOTYzOGE1YjM5YTU3ZWNiMTVmZTk2MGZmMWEwYWU5NTAyNWE2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GA3wUTdhaL9_N7qSnp2r9gx1oEvnYkkVkjNZtVPLcA8)

[Uploading New folder.zip…]()

**Comment by morvinm** [comment]
[Uploading New folder.zip…]()

**Comment by SpatenLa** [comment]
you keep linking to this site

**Comment by morvinm** [comment]
u got my settings?


> you keep linking to this site

you got my settings?

**Comment by SpatenLa** [comment]
no. try clicking on what you did send.

**Comment by morvinm** [comment]
idk how to uplaod it

**Comment by SpatenLa** [comment]
[fyrrakSound.zip](https://github.com/WeakAuras/WeakAuras2/files/13464467/fyrrakSound.zip)
you drop the file in the textbox and wait until it says the name of the file. the link will then end on "filename.zip"
![grafik](https://github.com/WeakAuras/WeakAuras2/assets/39881841/10129a87-f8b3-4b84-8687-3545619d38a9)

**Comment by morvinm** [comment]
[New folder.zip](https://github.com/WeakAuras/WeakAuras2/files/13464540/New.folder.zip)

**Comment by morvinm** [comment]
> [fyrrakSound.zip](https://github.com/WeakAuras/WeakAuras2/files/13464467/fyrrakSound.zip) you drop the file in the textbox and wait until it says the name of the file. the link will then end on "filename.zip" ![grafik](https://private-user-images.githubusercontent.com/39881841/285600402-10129a87-f8b3-4b84-8687-3545619d38a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MzA0OTQsIm5iZiI6MTcwMDkzMDE5NCwicGF0aCI6Ii8zOTg4MTg0MS8yODU2MDA0MDItMTAxMjlhODctZjhiMy00Yjg0LTg2ODctMzU0NTYxOWQzOGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE2MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYTZiM2QwNzg5NGQ4ZWZmOWM0ZjNjYzAwYmU1MGMwMzg3OWJkNTc4ZTkzYjA1OWM4NWI0OWY4ZGM3MDQwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9QyOIIhzjxCCxD-L24c_xczL-GCGVYUbqyZvBTLN8PE)

got it now?

**Comment by InfusOnWoW** [comment]
You can replace the WeakAuras.lua file with the file contained in this zip.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/13464823/WeakAuras.zip)
