### ISSUE TITLE
Range Checking in Conditions behaves strangely

### ISSUE THREAD

**Issue by Lisonna** [WeakAuras/WeakAuras2#4736]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

In Season of Discovery Classic, I am creating a standard Cooldown / range aura on Chimera Shot (409433)

Using a standard Cooldown trigger, and checking the Spell In Range condition does not appear to work. The property I tell the condition to flag does not happen, regardless of my range to the target (close/far). 

I am able to produce the behavior I want with a single Range Check trigger, using the Distance Condition option on the Range Check trigger on my lower/upper bound ranges, as a workaround (But also to confirm that the overall range-checking behavior in WA is still functional). 

This is a new spell in SoD so that may be the issue but I am not sure. I feel like this shouldn't present a problem. 

![image](https://github.com/WeakAuras/WeakAuras2/assets/70078996/2379b37a-d823-46a9-b659-560f09011361)

### WeakAuras Version

5.8.6

### World of Warcraft Flavor

Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
None
```

### Reproduction Steps

Create an Icon Aura - Go to Trigger -> Spell -> Cooldown -> Exact -> 409433. Set to show Always. 

Go to Conditions -> Trigger 1 -> Spell In Range: False -> Add a property (Color -> Red, in my case). 

After doing the above, the icon appears but never changes color, regardless of my range from the target

### Export String

```Text
!WA:2!Dr1pVTTruClO(NaAGIyLuJ6IoiKIg0cxyuKGyu0fdtfPyBOiPqsx7mjDK8jXlM6o27okz5TOPS0f9bidAUt6tqH(eqq0pbzOtfDWdDUV7eLRD1a17)V3V39EVsnQmSsyLW391ZPbCMlpveaF1gIlB3VVeuLetkiwqybrCrhoLP8RvVLxDN8aopoKpM5oMMa9wUMTE4aiYwhUEtvc6GbGq(zpwuq(p2QjjGJmbIJNhc(P977HcehvVzNgN28dYuFyeWuUOc6Ll6w7qxVUUEh64zNYOk)KyYeqKSvQe6oayGGg4gXh3M1ZX4xYo1kQJQDe8bcqkR(TU6S9D3e7ocaJTJBN6nBMlasSrFlYq4l(KdEDUo0Y1s6n1qECO0k5bAnWLKa1T07WWVsR87umZL4FhgpMmrot7KsqcUO3m5TZZSuwrpXkzlmM0rG3k(xYdHFBJRXwniyK4FgBGuo7xV(casoeJrGYHOO8OzsiUV5jj7JXEPKOsfefenhbQdma9r(tBNTzoY6J5FGGNYcF3dtQOGlrierW205fpWj7yeA(0NlgsqdkiSzCgm7g1p6BKj3)wrOgpMloPuPsL)WkPRlk7dp1RDYdmcjPkogkAWz0qvK9Hi71RYf9si0i8T5RMXEDrfT0O)nPsfT)eeGcUcbNhk0Uv7w1Z2uG4sBZCJHbMYOm(BwbiWHH73qqVQ6RsjHyJHu1Z7oyFDMYnYgZfHNjijtpRGyvbmIkP(XqVcmFR9GKToUvR6oDTB751(Loh)IJ8YVj1U0RGDkq053jpATMr(2N6184w1)Z8bX8XneWVKcSGjD(OFyVN8SvOtRyP(ZZ1pS47z5PAoT35(PkfN1EeiWnI5AXnb2av0NVqtVgAZ0m1UP1SehgFXAjrglVP4mroIgCbd3zkBC0nGedLT1KrgbnPOYTmzZg7sGiYpcOdIuV1oMtcB4RqhyQTDgMgROw26H1TZoZYjiMiLAkBj2y0eZfMjunwYU3tsPHlEANg2V5e2tftE1mcJo0G49DKkIq1yjqKGRsyW4NMTz2U5HfnLU6lkcjGxCcLt12zc6U2djuwJSEgRZiz(zbz763NYOYO)V4fu2QHDmEwjpC9Tm902ZPscoaegj0lP4o1(zDTYalBmqkl7R48HLMR4bJwTMEVV)VEenmzRAr0HGGufpiOQ6bsLZ)nHUOVapcGObhkl7m2m9NubFBwF7cVaGR4qpFet9PdSeuMo8q01RMOAO9xJsF3Ao1R3YHeNerkpx3cOMI8lFStqeeCX(zwLNoIiOAmSC1TmMdHnaCgrItHsIGinh6q2vNC0b)97F)VVXgBC0blRuP6TjkpnrWX(SAs2WPR7p9YXfBSEANysQvfPZZ27h3B)kJ(JZ)3d
```

**Comment by InfusOnWoW** [comment]
This is a bug in the LibSpellRange library, for which I've created a patch, see the linked PR.

I would expect the PR (or something that also fixes the issue) to be merged soonish and we will then pick it up in the next release afterwards.

**Comment by InfusOnWoW** [comment]
The fix was merged, thus the next release of WA should fix that.
