### ISSUE TITLE
weakauras 

### ISSUE THREAD

**Issue by Lix31** [WeakAuras/WeakAuras2#4737]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When I configure my spell icons at one place, it doesn't appear where i put them and changes place each second

### WeakAuras Version

Weak Auras

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

targetting

**Comment by InfusOnWoW** [comment]
That's not a sufficient description. With that information no one can reprodue your issue.
