### ISSUE TITLE
Mouseover as Unit for Aura UnitID

### ISSUE THREAD

**Issue by stamicvs** [WeakAuras/WeakAuras2#4738]
I would like to anchor buff or debuff Auras to my mouse cursor and show the icon as a buff-tracker when I mouseover the unitrame by hovering over the unit rather than targeting or using the nameplate.

I would like to be able to select the Unit "mouseover" in the unit selection box for every icon aura and the aura would return the aura from the UnitID where I mouseover

![image](https://github.com/WeakAuras/WeakAuras2/assets/48605567/07cdf291-8e13-4a1c-a8aa-b2b5879223bd)

**Comment by InfusOnWoW** [comment]
The game doesn't provide sufficient support for the mouseover unit.
