### ISSUE TITLE
WA not always showing correctly.

### ISSUE THREAD

**Issue by ErikTMA** [WeakAuras/WeakAuras2#4739]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have this WA, that should show if there's no poisons on MH:
`!WA:2!TA1tVTrru8AmLwTiOjUjL2auCdLa9avLanQcja5n1PjiN401onfHQ8o7UJ9oTRNzyMztI7bGAKq5cxI4tGfh7jFIZHVaJS4tqoWhG8jG3mR32eGGks4dEM38EZV3BE)DlSuPULIkfT7vhqcz0gSuriUWiuQkMjQZvegv6i6vVDBjw9lNBiIgcmwNrOQGfRUwZQEJczSKi220gBt4y)9ZjRg1bh7Aa1VVsq60blK)6RuCoXyIDljWayiQ6GvOsfSwgGvYO9jkC31qDXf4tMkXT6GPybjSrmB76u)rhJ8aPDzXX6COr(XO6pWqSngXblyqeoiTD7M94yXYvRT(sBuZvbeUgDDGmnaVfMQAaIq2zyRfR0OzRgnR410IrMo833Sp328DtPevapb1dl6l54KKvIKoEuGN0ji7k7NTujur2c7zvXbBAnOYvh)0Zv96cmOAVgRxTwTGmJ2TlIq3lLo2F5mN2z3s6xD0TXOOKEJDw6xRG(191NtpHEsFDjF951tPNwFb9BOVO(s(6z81VR(Q632r)M63s)o6Y6RONvFzh97PNt)(5yYNyrbHZti0oV44cGaWAqphwJkogU7VjlLg9IdPbaata5CinWFCtDYkuSufJvKW)Fb(8RsOrFinTBW)j3W)g0dJiYhMsTX)GWuPI1LxkBTzwuTgRdjK3UTviiV4duxZPm8tGvPcAzktvw91F0dkJa3ygX8hL4JpkXNCuIBEuIfEGdMg5WNeznLX6Evwe(PN6qOuglOOK7bfOGj8th(imMxbsPdvEiWOI3tItABl51NgkKKiW0qkC8ai51d3X0I4tVGE6razak8rDeMG(FmQtcB7Le4Vjfki7T(lFJRp)n1tlaHmm2383Tn4axVyFdLP4CuqQsXO13clGkRbMJRHPDuXtp0S)RY6dvypdXISeM4llwy5V4NNAQYN6ufkAQqVtohF7nU)4B4Ai8T3Rrikbx0AEnJjHpcsNKfTCQrG9tA1QlteHfX7od)kk8oQw2)AZeDrQw8wksxClUahsmESI8l93KroEJlLrX79m2ZU6Y8jSuYyuu(BOqHcfpi70CpTBLnAwNFE7HqZygafjCtsKk2TcqEyMUi7GJSh(KrznMZDq7B5)qitJ0Uhe1emfeXAch6Uw91QYV6j9OsWDqH9A1oHXeXzHlJu8RDsxiQh0YJe2sflWq7UKOEdSsfMfDGF7n(wufFILeKhx(UPOiiWJk3S5)GNJpEJNb(iEPJ4TYFD8YNK10Lf1YKB6pYYCBikUPaX7V54nz(LTGWwqc2FCO4iZ00NMF5tc7mQcJE2ZXonP(gnRTYAvF(PnipgFPXHJ8SVJ9kYpmigt6eREIBcdf9J7zMUeMGKsFp7YCbsOpuc2ZR(D2OQx30efXXkvcmXiXpqbPXu1f0mhp7jZm7834a7UwmWWqkMyMz)8pZ1ujBKYvcwMzZaHTO1y(6ZgadOBt64i2jZSE656Npb330(YmHBfqMl(stnpFQCwMmPBtKiWlgf7(ygRBH9qusxB58cEW4CHAjOr5k7JrsCdLWweFMrrJR4Bzg(kKya4izFJmwRzf9C2BP)UZO)E9t091Re0MqjY4)6XduSWTYAyD2T(TzjrdYAyllV6YEpp3ZdLWJrf922wKCywuzjbmK2OVGgl6vT6AZNsIggLU(o7C37HV2M3sqOgOXXdBBKeSEizTiVe47Z)qdO1PNjnBG5bqY(kPHeAwkcq5iq2(5Yf0FRJl8cuo6FWPK07Mx)wxFHsB973)p)`

To start with, it does not show.
If I apply a poison and remove it again, it shows up.

### WeakAuras Version

WeakAuras 5.8.6

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Load the WA on a rogue above level 20.

**Comment by SpatenLa** [comment]
you can either, ditch all triggers but 1 and just not check what temp enchant is on the weapon.
or you can set it to "enchant missing" and use "any" instead of your custom activition logic.
i would reccomend breaking that aura down to be as simple as possible before.

**Comment by ErikTMA** [comment]
> For an aura to be visible a trigger has to be active, with your setup none are active.

which is negated in the "required for activation" custom code, since there's no possibility of "none of the triggers"

**Comment by InfusOnWoW** [comment]
That does not negate the requirement for an trigger to be active.
