### ISSUE TITLE
First child of a group doesn't properly inherit Frame Strata

### ISSUE THREAD

**Issue by Ricodyn** [WeakAuras/WeakAuras2#4741]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The first WeakAura in a group doesn't always properly inherit the Frame Strata when Anchored to a selected frame and having that anchor set as Parent. Reverting the changes in commit f00565f fixes this.

### WeakAuras Version

WeakAuras 5.8.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Create a group and create an Aura in that group.
Set 'Anchored To' to 'Select Frame' and check 'Set Parent to Anchor'.
Select a Frame, for example the PlayerFrame or a bar button.
Duplicate the Aura.

The first Aura (top child in the group) will not inherit the Frame Strata properly, the duplicate will.

### Last Good Version

Weakauras 5.8.5

### Screenshots

The only difference between the two images is which aura is the first in the group. That first child didn't inherit the Frame Strata correctly and appears behind the character frame, whereas the other 3 appear correctly in front.
![Test](https://github.com/WeakAuras/WeakAuras2/assets/117543846/ccca6993-28ca-4374-aead-8f949c9ef0ca)

### Export String

```Text
!WA:2!vx1tVTXXv8qSjijlqsKyKLTCTtvCrCtDBuDKQ(tCqtkxksj5qrsTCLLSDs5(VHC3Ov7UEMz1)ABASksIsaYf9nO8CpXl1N6b9j4bI(jqh8PEsFc6BMDjLKLlkqasb6LHZ8M3SZ8E)(dZDV8m9PNyUjMn)M5DZ7EW17zB5SHlnkUyuqe9Ukkk1vU9etFSDe1Lq1Y2mEiTa)92ZI6oUruua3pUdpYzlcL5hfELCFJNoZXkGOyNEmp6U1A1Ir456Af64frRh5hYTlwQQrj9oP50WFpYl1nDE6DNlxof6o9py6olfIluOwoC8IyZOZ4wuUQMFOpx1Uf(dZtDFo1VDB8TC1BsZM(1DCj2jTAzSBmHUyPk1lVAfnoUq3kHAn5(SysqWsUm1Jzj2KTiH8gy2(70TzXcnmA2WOGUHwcEj2Xbw7sOdsRoLGPP3OEPkv0LrSxKyfW90dT2KWupmjm7jOMvNLCBtIhUXJsSOKXlNeem(AE(CYrP7MwTVAhkPnwGINREBAus8HwH(BAjk6zGHkdxwlmkKCeXIrAWPKW2CVxUNlwkImAkkmkJ4ef6Y2xKJ47a3sBtl)q8SWTGF5ld)k49GjWP5F2i3W39qdcJVG4ETXpsl)2QDBrX6bVllULYjPGyzriXN2Urr9sLQQfez5wwJHa5O6BMGScvnSX6mkmRQUtGfJjMzZrIrixmDYeF3US41N5rpiA2QZ9bNGKccn0k4EPePVVd2M1LDcStYibTK8gqTJO08Lua1U(HTIOP9g1EwjC8LvloDV8o39GB2XhZUruc1HCTxaETvGx5sWRcQ9CqIRB02Hn22pMyEu)Lc8XttCgt4nF9BcJ8uS)CT48jmstlBwevcWlh5smHRc)KEyR2bRhpjQF183gghEB4gQW1GRdVf8tHXup(0Jkp2(I1cYKz8WIPN7lygp65w3mcxAXJOxn)hbxcgf(zQXdlO)BrmsjwIV5F7fGF73FYgesCbrhNRlAhEWhJTkxcZIlygep4JUZOWL7HnvHixWRcDpyK48CYo8MmplS8xptUfpMmOCiT92KLnbU1Hd27gVdlEOZC8tfUhNgTpMPvyvJAXVPmiIrrc8YznFxUNwbC5jPxK)oexzWh3lLID)SNZrY9)8eg3V1UyrrJ4ybzGb1QwRAj4YuSOe50rMOtFVlLdZQGqE8qLP(7n(kjwUcs84ggNRW7Ft9KX2gfJRrTI3FTSjPpGT8z(2beZSA(mEzXdVu1QL0BQvZWO2Y6lTWIg9gC1cRTXYQO1p39i2v6jvBvJklvT0t71oiA7YuYJsiHo7w)fV9etoDA1j24iXW8zYCL9fReNUNDcNhfwd9Fr3PoIWvKEcxQRyE)s7qXIb26khHCVf6hXtMz)hNMyHNm)gsFC5ZYWZ3zJqcJPi3PIpoFy5TPL6YB7r8B7XFimDzygHahMto(bYX7igJh6mEhYHU1LoQY5WphklvAfZeJi3gPYOs7xKA7DERRF9)DZS97lRn766ZeM3lHk7Rm3t(hOk60xsD0moKBcAOr1Ggu8i9pSGOnVpZcXExp49vHxs8FCOrPMWOuFBbL9HWKkWuDBuQsPIgL1lSCjDRGyplf4d7U26rBUZ8vyRevN6hk(Bsum(gyjPcdRc5vHFNkuqvBVOOnZDWnHIcFQ)AMpfmVjuYdkFw3iybP3dS4Z1VbwYeURj8jMqLtnnGLLEeqvPRaulZmaQFWiWk5aDSR1avZGHu9cRc3dwdwhU)JHhKdEiEIpf(mm9Fp0u2BatWcSZboGlGWtlOn4ng4Nd(CyJNcb9jUWMa3dIGy4rxcO5aw6HdvGKCWokW2kWwEWUdd75b)bjV5oxG3KYK(JWFsWoGVrbbjSzbFjcI)D4XMz9X8Yw53Ld721O7oJwJs7T4Ivhau2cGA8jHV6HWxyctbFTaTqG8B9G)Ixg7czncYZzyxptK8xicIB)ztyFzvLbC4R7v(x5(Xb5(HQc(FiCJq7fGBKcGWnc0iCJG(zH7)d2edGBeSe0vSjlW7NiW70UTqGGO9z0IPq8usWfzjFLuq(HDF3L3O4ufCOnwTUaTVGQdX)(sUv(Xd5()An3xyMP5Wg2ZtWv3D6v25(pG6oP3ZGg)Mmyidtgi4YWWVKo1SV)StD7Pfa8pury(T(NR)Vd
```

**Comment by InfusOnWoW** [comment]
With your setup the icons are in the frame strata medium. The PlayerFrame is also in the frame strata medium. The exact ordering of frames in the same frame strata depends on the frame levels. 

WA automatically assigns frame levels to auras in a group, to minimize interference between auras in the same group. 

But for ordering between the game's frames and the group, you have to use a different frame strata.

**Comment by InfusOnWoW** [comment]
Yes the behaviour has changed slightly. No what you describe is not a correct.

The frame strata is applied to all children. Again, the PlayerFrame is on the same frame strata as your auras, which then leads to the order depending on the frame level.

**Comment by InfusOnWoW** [comment]
The frame level is not overwritten. Again, as I already explained:
WA automatically assigns frame levels to auras in a group, to minimize interference between auras in the same group.

But for ordering between the game's frames and the group, you have to use a different frame strata.

**Comment by Ricodyn** [comment]
In the screenshot I provided I have 2 images of the same group of auras with exactly the same settings within the individual auras. The only difference is that the left image has the top left icon in the first entry of that group, whereas the right image has the top right aura in the first entry. So only the first entry appears behind the player frame, whereas the others do not. Do you know why this happens and could you explain that to me?

And more importantly, if I revert the changes in commit f00565f, and only those changes, this no longer happens. With those couple of lines reverted, changing the order of the auras in the group changes nothing, and regardless of order all four auras appear in front of the player frame.

I understand that frame strata does not play a role here at all, in all cases the player frame and auras all remain on the same strata. And if you say that frame level is not changed or overwritten, what else is causing this behaviour?

**Comment by Ricodyn** [comment]
It seems that my issue is closely related to issue #4718. The commit that I mentioned multiple times as the cause of my issue, f00565f, was part of an attempt to fix this other issue. Although details differ, dynamic vs normal groups & retail vs classic, and our issues have come and went with different WA versions, the core seems very similar: The first entry of a group does not seem to get the same frame level as other auras in the group, causing unwanted and unexpected behaviour.

**Comment by InfusOnWoW** [comment]
> Do you know why this happens and could you explain that to me?
WA automatically assigns frame levels to auras in a group, to minimize interference between auras in the same group.

> It seems that my issue is closely related to issue https://github.com/WeakAuras/WeakAuras2/issues/4718.
No, it's unrelated. #4718 is an issue because we assign the wrong frame level to the backdrop of the group, and thus the automatic assignment of frame levels lead to the auras being behind the backdrop.

Your "issue" is about the ordering between a group and frame that is provided by the game. And for that I can only repeat myself:
But for ordering between the game's frames and the group, you have to use a different frame strata.

There are no gurantees what the relative frame level of auras vs unrelated frames is.
