### ISSUE TITLE
Implement the trigger that exists on retail called 'Spell Activation Overlay Glow' to Classic Vanilla/Wotlk!

### ISSUE THREAD

**Issue by Somatics23** [WeakAuras/WeakAuras2#4742]
hello, I am suggesting that Weakauras Vanilla/Wotlk adds the trigger option 'Spell Activation Overlay Glow' just like how it is exists on retail.

Why this is useful is due to the fact that ideally you wouldn't want a spells WA to always glow when the spell is available or comes off cooldown. You would only want it to glow when it's cooldown is reset by a passive. For example, my retail Stormstrike WA only glows when it's cooldown is reset by Stormbringer, exactly how it is handled by the default blizzard UI when the spell is on your action bars.

On vanilla Season of Discovery, there exists a new spell called 'Molten Blast' that has a chance to reset it's cooldown when Flame Shock deals periodic damage, I of course don't want this spell to glow always when it's available.. I only want it to glow when it's cooldown is reset by Flame Shock. I hope this makes sense. Thank you for reading and this is the best addon ever!

Retail Examples:

![WoWScrnShot_120323_225527](https://github.com/WeakAuras/WeakAuras2/assets/122374928/6510d0ec-eeeb-4487-b8d4-48c214105cf1)
![WoWScrnShot_120323_225529](https://github.com/WeakAuras/WeakAuras2/assets/122374928/b68742a1-b423-4883-9951-00db2bed431d)

Vanilla Examples: (No Spell Activation Overlay Glow Option)

![WoWScrnShot_120423_172723](https://github.com/WeakAuras/WeakAuras2/assets/122374928/f70c1ab9-c3fd-4a98-8bec-c612b4e91fad)

**Comment by InfusOnWoW** [comment]
Does 'Molten Blast' glow on your action bars?

**Comment by InfusOnWoW** [comment]
I just researched that, and it doesn't. The trigger does not trigger based on a cooldown reset, but on blizzard applying a glow to an spell. As Molten Blast doesn't appear to do that, the trigger won't be of any use for the spell.

**Comment by vookhan** [comment]
Sorry to necro this, but this trigger is still missing on Classic.

Example: Warrior's Overpower glows when enemy dodges, not just when Taste for Blood is active. This is useful to track Overpowers from stray dodges. "Spell Usable" trigger is not useful because of constant stance-dancing.

**Comment by InfusOnWoW** [comment]
Please make a new ticket, with clear evidence that it is indeed a spell overlay glow.
