### ISSUE TITLE
Caster in conditions is unitName instead of casterName

### ISSUE THREAD

**Issue by Robosterone** [WeakAuras/WeakAuras2#4745]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

title

### WeakAuras Version

Weakauras 5.8.5

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

not really sure what to write here

### Export String

```Text
!WA:2!9zvZUTTrqyRQgKwveGeLFmsqqRQsJJdsGqJdIHBADBeLLSSRSKdfDCcccOxsUsCJP4YUCPKLBZHOt5spu9a0d6CpPNGc3xGfcf9bih6dGV2lD2Lu2onjLqqC2zNDM5B25hMQs2ozDY68QRnIyt9BsJy24RoZeue3LYAeWju)WmS(nA1keZR(aZx8pZmZmF4yKVnS)MuIp3Qu56gL1NytPEo0E(n7rcW7CW0LLDAJDziBLMwupKJy8mAeFcpJvl4vOBMbCgPDBml8xNJLq(xSOqCDuh8ohceMoyROwTk5HcdDFDyKfUl2N3eyr2BSzPInnmBAuu34GwyUTRbyzojWvxjLvvmYJ7Qfbw0cmEBmxJ3paRJIyOfgegG98wZjmZrQDtgguREZnlxRMUp4cHzgkLvrELrLOmwKkUmrznDeXzdeBx3rXoPbOBw1I6BuzRAdJ8tWtM5eNPRywl7OqoTtSHcdo7w1xZWS4w6fVFSNnoEFtPdkoV4IwbEO(yMihRA5ABcAuCT9sDRwr(QW58k1CZm5GhpQnYlxBpAVClNt6UMy)Ufy42GCfaOPROcF6cp7eIBFewUDoZ36NeWGY2UO5Qy(wq4BffaNpFSVM)25YFCWqUAZAfFszDjvc(Zh7BbminzEP6oPVMOEDQfTNNIpPvmtUl2pNIJ8rIP730L2B(4tJ9cXV5Mvjo4PB67OENrsaptdOUGi6CshSJiFMXoKWNRIHDXIRfKnwgJ4BQA02e7Gp7OyCs8LH5rm)C8NENNj1DW5qQJNCOnOo4FBMdbyIz(iVhb5YWz)5d3fJdkcPy2CDeOn3HHyVwQQgXPG8LqeOueh7o64BO1VKy2jWslK9UTz0iFNxDHGSC8ECZqxeur944AXubxwXu9xlkRdceiHqZN6JhE025VoKQDcnuI6rzRNkvQ0VoM7uNsR4wgncoVIj0bGcQIyVnXbkFkclpm2wK9WokMVCsCBGNK4rhO2)5q0K0QpaqgLdGZayQvVr9YIzzaUKYmsjOTYnsdpdtaHpp4SvyK9Z9WiKdeyq5mmEdSp1stu86rzoBZqbd2oHi2b6scjwEy3emFIwvbNBT61lRBQ1WWOXg6RTAvJjhz6MK9Xxobrp(nSJCxvzDJTmQTw9Y)9ezAxfg(hIW(2938d)YclCVy0j34a5FRiVyH7Z0dKRKNEIveNt9B0fZGI6rs21W(T5UxCSKEk0gkxu6OqZbq7VvNYXvj5uNttUWvjFtOGcNw5wgUe7D9XHHPv7uJa0NtznnikHzUV6QIftj(Qjx)ofSrHqcRSnR4(Q8bXxl(gXYIVn4lERCRtkDcpXsVt5KDAlPK9)tUatz5OPhUnYUVzlpkaprrXPeAIsIVFhrJub5EFhQd1Xuw3SJywXkVJ6GGPg(wIYQOOOctdTpLUlk4tFFknEvQK8T3iZEzX39sXAI1fBkEOOg4Jvtf85Vp9eWW2ez5FAr9BeCZ3Nyo9HEDeBtUldh6cZk7lEqklxmPTl)LAEuKZJgkh95dn5zUWKlpOx)L07ebZ2YOBlhfEjrqgnz3Lyci)vsmkUPVmLttotp4cthflRexHeIGIdhx2EjZ0)9hmZhaZ0NzWuX2ziYN0rL9UO4JRaX4LoaJcXn5mv(6PN4KKCRMtXcXGvCchiLrAvXsADqeF1bf7FAXpk(jXlaYp5)YrdUr6iREU7D0rEbUO0J4u7UXnp)OU)rEIZOJhrPFC)IXTyqwi4pqlI0hgFvvrYsAERML0lxUUf4uTiTZSqeXzCV1R28UZ)eR5xDrywK0cq7HSq4TucMHg46Yek9EQgBJKiIO(KLRmNUTl2E3kIZKopni)YlpOlIrKbXrhNPR3f5fHf3Gz7I8BdFNWCIFzNbbmkeF49LT3lC3cYIWXe)48aq3zer7Knu)EfwQW9Y29pF8)(d
```

**Comment by InfusOnWoW** [comment]
Your title is not even remotely enough for a bug report.

**Comment by SpatenLa** [comment]
context, i hoped it exists in here.
using the condition for "Caster" on a bufftrigger uses the casterUnit as compare value (player, raidX, partyX) which most likely no one ever wants to compare except its specifically the player itself.
it would be nice to get "casterName" added and "caster" rename to "caster Unit".
its also possible that my testing failed as i tested it only with the player and it does something in the background transforming everything BUT the player into the casters name.
the provided import shows that "player" as comparsion works for player applied debuffs

**Comment by InfusOnWoW** [comment]
Thanks Spaten.

**Comment by InfusOnWoW** [comment]
Ah, I found the discussion and that person is playing on a private server anyway. So the number of requests for this feature is again 0. If there's actual demand for this feature, I'd invest the time to add it.

**Comment by Robosterone** [comment]
That request is not from private server so I don't have a clue what youre talking about.

**Comment by InfusOnWoW** [comment]
I'm talking about this:<https://discord.com/channels/172440238717665280/827198294832578620/1028071916604498052>

**Comment by Robosterone** [comment]
That's one year ago. Should I be ashamed that I was playing on private server? But I'm fine about closing this thread, it wasn't my initiative to open it anyway. Thanks.

**Comment by InfusOnWoW** [comment]
Well, we certainly don't support users on private servers. It seems I was wrong about that, though. So apologies for that.

There's definately something missing with the condition, so I guess I should take another look at that.
