### ISSUE TITLE
Text in a dynamic group isn't aligned correctly in practice

### ISSUE THREAD

**Issue by Tems91** [WeakAuras/WeakAuras2#4747]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Text WAs in a dynamic group are not following growth direction correctly. The result is text WAs scattered randomly on the screen (As if they lose their anchor) It's also not consistent, during the same fight it will sometimes display correctly

The issue exists randomly for some people, and not for others.
The issue has also started with WA v. 5.8.6

### WeakAuras Version

Weakauras 5.8.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
There are no errors occurring
```

### Reproduction Steps

The WA issue appears generally in practice, meaning in the boss fights it's supposed to work on. They look fine when viewing the WA from /wa

### Last Good Version

Weakauras 5.8.5

### Screenshots

![WoWScrnShot_120323_225933](https://github.com/WeakAuras/WeakAuras2/assets/88907488/42aead35-966f-4848-9130-963bd2791110)

### Export String

```Text
https://wago.io/TemsICC
```

**Comment by emptyrivers** [comment]
I'm sorry, but the reproduction steps are far too vague to make any progress on this. I also tried creating a dynamic group with text auras, and nothing seemed amiss. If you could gather more information about the problem, or provide more specific steps to repro, that would be helpful.

**Comment by Tems91** [comment]
Hello, understandable of course, but there's no reliable way to reproduce this, it seems to be happening on random with some people and have had received multiple reports about it, from users of my pack and other popular ones.

**Comment by InfusOnWoW** [comment]
Also that group contains 375 auras. We need a far smaller example that shows the problem, we cannot look at 375 auras to figure out which one might be problematic.

**Comment by Tems91** [comment]
Here is only the text group: 
https://wago.io/IgCczAw4o

**Comment by InfusOnWoW** [comment]
Well 49 is better, but still not something I want to investigate.
