### ISSUE TITLE
Need option to load when talent NOT selected

### ISSUE THREAD

**Issue by kkerwin1** [WeakAuras/WeakAuras2#4748]
**Is your feature request related to a problem? Please describe.**
WeakAuras2 v5.8.7 provides an option to "Load" an aura when a talent IS selected, but does not have an option "Load" when a talent IS NOT selected.

Compare to option to "Load" an aura when a spell is not known.

Real example: Restoration druids have the "Undergrowth" talent that allows druids to cast Lifebloom on two separate targets (one target when Undergrowth IS NOT selected). I want to display one aura, centered, when Undergrowth IS NOT selected. I want to display two auras, centered, when Undergrowth IS selected.

**Describe the solution you'd like**
Provide option to "Load" an aura when a talent IS NOT selected under the "Load" tab.

**Describe alternatives you've considered**
I have considered loading one aura at all times, and the second aura only when Undergrowth IS selected. However, these auras will be displayed symmetrically only when Undergrowth IS selected, and will be asymmetrically displayed when Undergrowth IS NOT selected.

**Additional context**
Please see attached image that illustrates desired functionality.

![undergrowth](https://github.com/WeakAuras/WeakAuras2/assets/47354/848586e0-2ec9-468b-80fb-6a864da1e5ee)

**Comment by mrbuds** [comment]
There is already such option.
