### ISSUE TITLE
Healthstones - Count not updating when refilling from soulwell.

### ISSUE THREAD

**Issue by itsavih** [WeakAuras/WeakAuras2#4752]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When picking up (refilling) soulstones from 1 count or 2 counts (out of combat) - the COUNT trigger does not update to 3 stacks...until you enter combat.

### WeakAuras Version

5.8.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
NA
```

### Reproduction Steps

Be on a warlock
Get healthstones (3 count)
Fly up in the air and fall - so that you can use 1 count
You are left with 2
Put down a soulwell
Click it - and watch you go back to 3 count on your action bar
But the weakaura monitoring count does not go to 3 until you enter combat

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/22582688/420d136a-e3be-495f-9978-f5f71b9d179d)

### Export String

```Text
!WA:2!1zvZVTXXvCrWyex6(HftLSSRHbTrJqtrRqItKJrlCD4srAkhAs1L0vo5c3z3Di3jA5oBMzOOyUfEP6speceGau1gv2po1te5pGwDONYHhiQb6XcFON6jHE39nZUK(JyBalo7BEF(BFVFVntL89Y7N3)WxFcZJh1K3x4rV8sZi9vbCrJyfJhjZjg2Othjv91zNsI8Wl2HZIuULkxVvz7zECEOpFquZbSyQZjZFSSFxAGL2RoJucw3UuH8kRlsp(pSudJPwmfT3JK9DP7tJun73Pd7GPTlvSzR2nBv0Uv8Y9L02DPrubZRzaFqJiNt0I02vN0J6SW4Deu0y7M7uUwnBJK41kLMkf2rW7kOszHF02OHVXizmnmCBFzUzpJVNiXFkgoGmuoAEeo7khAhH)kZz1pIPCJdjdPIj(uxmBBH1GOA5A7u5(1g3pkT2YToK7WlaRHMoM0xqmMFPrB3RhpKOOZ6ruEbuzsmHlaRI))I5MODF5dysL0joVPiJ8c77tlfqeDPsNXMSwNtR9k)VliqnmiaSmKh(oW3fUKRsROsGvCJOWHoW5DGVNZmbLe2CUPtQesLbEcsh1mDmw4thyLCW5GVDsOPhq8upbLHxBIg4kuIJf5yTckbXBph4YIQfTVhw9WvYfVmAdBFAReu4ECF6FDPtXgfQiIe(RWx)yZ0V509O04Iyy9u2eS9kymjI1tFk6g2sScuvoHsK0MkbnQRk4vHZzfXJOZ8rKuRvBDJJqsXglF5iTQ63cWMw9iSOkW7GgaBc3aEx4MWMUDyrmzWZlgF9jjkTdPbtWoiBAxDJ(hUkCUz4JUyT1vG1Q)HReNxrpq1wgqWoPhKmhKj(IgHM)0HlW0VTm9aS54f3z96xFdz85FkhuIhYf3ntMmzFuIuAyhZWKvX73Qr8RzeIdFCnI4TlZxfyveF80KqXoG6Be(PZsge)G0e6eZ9FuFPI1ziCMjcUcRTw6COEJ6LHZjWYsRZeJIEM0il(VXP1qK60kmbPqtsKSGvicaptHppoZmYgWf(7kiXJ2n9qs43NjzUHuN0k(POkIxE761lB32QrRwnUN923PAR4FW3acrWAbioBrE1K9j0RMwUp4zsd9TMjWg3VvTTRx()mRBiFqfb9J7tJ8gUZR8MBC9ntkD9fAIJ7eM(oiyKwK26zU9vkEuJ9PcC0EIwCntN3kt1NNx5J7o3udUDI(XTsBjZA0CrYz8CaZBViKYjRXWMEKqAwl9XaJGAm8YLnrZcbrQi4WlgF1VbKe3wX6rBhlOEm94tw49oToVqvCKwfiX0ME1xqVyC6bBTX(qjylOmubUZNcvZaBdNbUl8(GLPneNkQbpidCV7MT6T)7F2N9Lp(XpU6T)6Jo6VT0s4T1HgWVidStgOza8lbB4dGpeADcc4lEBgFLxwwN8uM4cVmf6X9BRNbDGDxj(nEzA5pejqzETvbifEaYOpm(h(Y0nK2L4nSDNqoxJO6C)9MwJpOqkj68Q(fdjIadC8Xdr4O6T)xFXxObHQ3(HF(NFCYHh(W)9cy5JYQHLyNNalqeWna1UROH0qONBaL1nqDlRqoX)V8iVqIuIZf(AAxV1DLSOUH0V68296hQyR(vN3bPWdXvxRchKZYOdm4vXZJ844gnI(IbFlZcW5cCgLYI7LU04zJHZ4fYCSn)GEuSBr7Ank9(MGGtx6O5knR(Dz9I5c1eHHq0qSE2PSOeqgLS6u8OhTSE)Q0zQptQ3hUnYfV2zV5WXlOZGZioizC4)MXfVTdRBU4V)8pnqZlTftsqYc)GPDe4kgKUNOizNO4E7NSPyTm)6GRX8JZ)un7f(Pf2Ikv2d0CG3YuWZ3XJRBS1TsNMWuur7uD(72SKD5Y1TjHXbKSxVpZF6U032F3Wq3T27TeSiD4Oi4Sy026t48EzMO3VWmF)ZDx3g3x7Txfi3pzPr7temDMF9I136A84RDRB5AUv(JVbKllC0eE08CYEFsyFAg0UZah5Il3qTGJZ)MjMj8ciryp5Lwho2zuSGJmz4UT8iD1gVZgpnJ66WV1eB4i43Lyl871r7YOKr4xjW75ICMhNgi4pKQdgjyIX7WFe(tZDs6LOREItG)8lY63AH1jj1MpFsLuWWxchN9jb6NpA(RzhH(dcqa8gWBNd(z5SWDXQC5L2BUXn34DZV))8b))d
```

**Comment by rafaelmalheiros** [comment]
It is a problem with Blizzard's API.
There is no consistent event fired when recharging your candies.
Sometimes the ITEM_COUNT_CHANGED 5512 is fired, but it is not consistent.
Then, Weak Auras has no way to know that the number of charges has changed.

**Comment by InfusOnWoW** [comment]
This is a bug in the game api, where GetItemCount() has a parameter "includeUses", which counts the number of healthstones, but the event ITEM_COUNT_CHANGED does not fire if only the "uses" of an item changes.

This used to work, because we used to listen to the "BAG_UPDATE_COOLDOWN" event, which does fire when a healthstone is used and when refilling from the soulwell.

Unfortunately that event fires a lot unnecessary events: https://github.com/WeakAuras/WeakAuras2/issues/4174, which is why we no longer listen to that. 

The correct way to handle that isn't entirely obvious.

**Comment by emptyrivers** [comment]
hmm, something like listen to BAG_UPDATE_COOLDOWN, but do nothing until the next:

- frame
- BAG_UPDATE_DELAYED

might "magically" solve this
