### ISSUE TITLE
Item type equipped trigger: option for checking offhand slot

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#4753]
There is currently no way to test the type of your offhand with current Item type equipped trigger

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/6b98ea3b-c2c6-43e3-af58-a2ddd508efa9)

**Comment by InfusOnWoW** [comment]
The api that we are using:
https://warcraft.wiki.gg/wiki/API_IsEquippedItemType. which we call with an item type and item sub type from: https://warcraft.wiki.gg/wiki/ItemType

doesn't support checking for the off-hand item type. What's the use case for this?

**Comment by mrbuds** [comment]
A use case is check if both main hand & off hand have a dagger equipped so you can use "mutilate" on a rogue

**Comment by InfusOnWoW** [comment]
Right we can probably add a item location to it, the right api sequence seems to be:
GetInventoryItemID("player", slot) to get the item id, then
GetItemInfoInstant(itemId) to get the classId and subClassId then compare it via:
classId * 256 + subClassId == userInput

Doesn't sound to bad and does fit the trigger.
