### ISSUE TITLE
Add a Subzone load condition

### ISSUE THREAD

**Issue by Ricodyn** [WeakAuras/WeakAuras2#4758]
**Is your feature request related to a problem? Please describe.**
There is currently no option to load based on GetSubZoneText(), only GetRealZoneText(). (And Zone IDs of course.)

**Describe the solution you'd like**
Either an additional option in the load conditions that works exactly like the existing Zone Name condition, just with subzones instead.
*or* 
Add support for subzone names in the already existing Zone Name condition, similar to how the Zone ID supports both individual and Group Zone IDs.

**Describe alternatives you've considered**
You can check for the current subzone using custom triggers, which is effective and makes this feature request not strictly necessary. Adding it to the load conditions seems relatively straightforward however, unless I'm missing something, and might be a nice small quality upgrade in some situations.

**Comment by InfusOnWoW** [comment]
What's the use case for this?

**Comment by InfusOnWoW** [comment]
There's no locale-independent way to check for the sub zone, as they apparently have no id in the api. I'd be very reluctant to add anything that will lead to locale-dependant auras, it needs to come with some much needed benefit. 

The boss specific reminder, while somewhat useful, doesn't really clear that bar. And additionally the sub zone to boss mapping is not unique in pratice nor in theory, so for that it would be a crutch.

And there are addons such as LoadoutReminder, which are exactly for that purpose.
