### ISSUE TITLE
Add more load options to built in trigger conditions

### ISSUE THREAD

**Issue by Ricodyn** [WeakAuras/WeakAuras2#4759]
**Is your feature request related to a problem? Please describe.**
Some of the load options, like Zone Name/Zone ID/Mythic+ Affix, are not a built in option for triggers.

**Describe the solution you'd like**
Add more of the load options to the built in trigger support. Instance Type/Difficulty/Size Type can already be found under Player/Unit Info -> Conditions. Options like Zone Name/Zone ID/Mythic+ Affix and maybe more could be added here too.

**Describe alternatives you've considered**
It is possible to achieve this functionality already using custom triggers, but having them added as built in trigger options might be relatively simple but still a nice quality of life improvement.

**Additional context**
Player/Unit Info -> Conditions may not be the right category for these options. The Instance Type/Difficulty/Size Type are found here too, even though these maybe don't totally fit. Perhaps the addition of a new category, named Location or something else, would be appropriate.

**Comment by InfusOnWoW** [comment]
What's the use case for this?
