### ISSUE TITLE
Dynamic ticks for progress bars

### ISSUE THREAD

**Issue by Grumpymurloc05** [WeakAuras/WeakAuras2#4760]
**Is your feature request related to a problem? Please describe.**
When creating a progress bar for a damage over time affect or a channeled cast like Mind Flay, there is now no default option to show case ticks at the moment a dot or the channeled cast would do a portion of its damage. 

**Describe the solution you'd like**
When adding a tick to the display, have a 5th option at 'Tick Mode', which would be called 'Dynamic'. When selecting this option, the input box at 'Tick Placement' would gray out and the WeakAura will start showing multiple ticks at the points when a damage over time affect or a channeled cast would do a portion of its damage.

**Describe alternatives you've considered**
The alternative I've considered, is having an option at the trigger itself. For example like available at a cast trigger, where you have a check box to Overlay Latency. But I find that lesser of an option, due to people possibly wantint to edit the color and thickness of a tick, which is better suited to be done at the Display tab.

The other possibility is custom coding it, but that is something I'm trying to circumvent by having it as a default possibility of WeakAuras.

**Additional context**
Besides damage over time affects and channeled casts, this could also be an option for Healing over Time affects.

**Comment by InfusOnWoW** [comment]
Estimating when the next tick of a channeled spell requires hardcoding lots of spell-specific functionality, which we have no intrest in maintaining.
