### ISSUE TITLE
WeakAuras doesn't abbreviate big numbers correctly in east asian client

### ISSUE THREAD

**Issue by Elnarfim** [WeakAuras/WeakAuras2#4762]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues.

### Description

In East Asia counties, people use different numeral system to western countries (CN,KR,JP,TW)
reference - [https://en.wikipedia.org/wiki/Korean_numerals](https://en.wikipedia.org/wiki/Korean_numerals)
But WeakAuras is showing wrong number above 10k now
10k - 만(萬, 万) SECOND_NUMBER as GlobalString
100m - 억(億, 亿) THIRD_NUMBER as GlobalString
1000b - 조(兆) FOURTH_NUMBER as GlobalString
East asian uses that instead million and billion
WeakAuras is calculating 10m as 억(億, 亿) now. 10k is working correctly

### WeakAuras Version

5.8.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

TW/Asia

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Use big number for number format in east asian client such as CN,TW,KR

### Last Good Version

Never

**Comment by InfusOnWoW** [comment]
Those number formats use blizzard functions, that is AbbreviateLargeNumbers and AbbreviateNumbers.

Thus I would expect /dump AbbreviateNumbers(10000000) to show an incorrect formatting too. 

Does the game display those numbers correctly formatted anywhere?

**Comment by Elnarfim** [comment]
Plater shows numbers correctly. for example: Tindral supernova's shield numbers

**Comment by InfusOnWoW** [comment]
I'm not interested in other addons, I'm interested n the base game. Also please add the output of /dump AbbreviateNumbers(10000000) to the ticket.

**Comment by Elnarfim** [comment]
it shows incorrect format. maybe blizz bug

**Comment by InfusOnWoW** [comment]
Right, how does /dump AbbreviateLargeNumbers(10000000) look like?

**Comment by Elnarfim** [comment]
How about add custom function instead blizzard. I think KR client has the bug only

**Comment by Elnarfim** [comment]
It shows 1억 now

**Comment by InfusOnWoW** [comment]
That's incorrect right, it should be 1000 만?

**Comment by Elnarfim** [comment]
right. it shoud be 1000만

**Comment by Elnarfim** [comment]
and it should not be space between number and text like '1억' '1만'

**Comment by Elnarfim** [comment]
also you have to check other asian clients such as TW, CN

**Comment by InfusOnWoW** [comment]
CN doesn't exist anymore, though JP has the same system. We'll check before deciding what we should do.

**Comment by InfusOnWoW** [comment]
There's apparently no JP-client, and the CN client can connect to TW servers. 

The bug is indeed in blizzard's code, more details at https://github.com/Stanzilla/WoWUIBugs/issues/515

Now we have to decide what WA should do about that.
