### ISSUE TITLE
add InstaceID load option

### ISSUE THREAD

**Issue by SpatenLa** [WeakAuras/WeakAuras2#4768]
**Is your feature request related to a problem? Please describe.**
Once again as Classic (SoD) gets popular the issue that instances dont have a map and dont work with map ids arises once again.
GetBestMapForUnit("player") returns nil for instances (tested in BFD).
InstaceId is available and is already fetched directly before the load.

**Describe the solution you'd like**
Adding the instanceID to the zoneId field to overload it even more with i

**Describe alternatives you've considered**
Adding a separate Load field for the InstanceID

**Additional context**
https://warcraft.wiki.gg/wiki/API_GetInstanceInfo
https://github.com/WeakAuras/WeakAuras2/blob/7887a1dacd55eab830e535e6d7aa8d45b2fa55ad/WeakAuras/WeakAuras.lua#L1643

**Comment by InfusOnWoW** [comment]
This is now in with the great syntax "i###".
