### ISSUE TITLE
Update any linked WeakAuras that exist when a major pack is imported as update

### ISSUE THREAD

**Issue by mikeekert** [WeakAuras/WeakAuras2#4770]
**Is your feature request related to a problem? Please describe.**
When using a large WeakAura pack that may be continuously updated, if a User extracts one of the items out, the WA addon knows it is linked to that pack via the URL field.  But if you update the whole pack, your single extracted WA won't update -- BUT it will show in the Update section (via the WA Companion) as Linked, and the Update area won't go away until you do the remove the old one from your custom group, and replace it with the new updated one.

This is mostly troublesome when trying to maintain a Raid WA pack for your guild, and maybe you extract some very custom WA from a major pack from Liquid/Echo.  As those authors release updates, you have to delete them from your Guild's pack, and cut/paste the updates to your pack, one by one.

**Describe the solution you'd like**
Ideally the Linked Weakauras would also update, both in the original Author's pack on your list AND the single use WA that you copied into a custom grouping for guild/personal use. 

**Describe alternatives you've considered**
For now I have to delete the WA out of my Guild's group (which is setup per boss, usually), drag the updated one out of the (in this case) Liquid pack and into that custom group for whichever boss.  And I have to do this for each one that is updated, which in some cases is nearly all of them.

**Additional context**
It may be a work around to disable updates for the ones you add to your own custom pack, but then you just aren't getting updates which could be vital to the WA breaking, or a change made to the boss.

**Comment by InfusOnWoW** [comment]
The url only links an aura to the pack that contained it. To update an aura, the uid must match an aura in the update. Since you copied an aura into your pack, the uids won't match so the information which aura from the update maps to which aura from your copy is lost.
