### ISSUE TITLE
"bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))"

### ISSUE THREAD

**Issue by Redhealer** [WeakAuras/WeakAuras2#4779]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The following error is occurring with a fresh install of WA with nothing else added in:

**Message: bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))
Time: Tue Dec 26 18:31:52 2023
Count: 3397
Stack: bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))

Locals:** 

This error is occurring once per second and I took out all other addons to verify it is coming from WA

### WeakAuras Version

5.8.7

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
**Message: bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))
Time: Tue Dec 26 18:31:52 2023
Count: 3397
Stack: bad argument #5 to '?' (Usage: self:SetVertexColor(color [, a]))

Locals:**
```

### Reproduction Steps

Open wow with only the WA addon 
Receive error message you have to many LUA errors would you like to disable your addons.

### Last Good Version

Unknown this is the first install of WA for me

### Screenshots

![WoWScrnShot_122623_183658](https://github.com/WeakAuras/WeakAuras2/assets/154941693/dd587d36-7ba6-4dd2-bc1c-20e3163bc257)

**Comment by Redhealer** [comment]
Loaded prior version and no error occurs.

**Comment by mrbuds** [comment]
Screenshot show many addons are loaded
Screenshot show there are 2 errors, what is the first error?
Error doesn't point to weakauras, but if it is indeed weakauras we need your data

**Comment by InfusOnWoW** [comment]
No response from reporter.
