### ISSUE TITLE
Group alpha/transparency slider

### ISSUE THREAD

**Issue by johnnylam88** [WeakAuras/WeakAuras2#4782]
I often import an entire WeakAura package but then painstakingly go through each child WeakAura and reduce *alpha* from 100% to 70% to better fit the visual theme for my UI.

Currently the *Group* tab allows setting a group scale that allows for modifying the size of the group's WeakAuras together. 
 I would like to see additional option to set a group's alpha/transparency, e.g., *Group Alpha* that goes from 0% to 100%. This alpha setting would be multiplied into each child WeakAura's alpha setting when displayed so that each child's alpha is correct relative to other children.

**Comment by jjholleman** [comment]
You can already select a group, or multiple aura's with CTRL/Shift + Click, and change all the selected auras at once.

**Comment by johnnylam88** [comment]
> You can already select a group, or multiple aura's with CTRL/Shift + Click, and change all the selected auras at once.

Wouldn't this destroy the relative transparency settings between the child auras of a group?
