### ISSUE TITLE
Preview for "Group by Frame" WeakAuras

### ISSUE THREAD

**Issue by MetalMusicMan** [WeakAuras/WeakAuras2#4787]
Heya,

Could we get a feature to let us preview WAs that are Grouped by Frame the way we do for WAs that are anchored to Nameplates? Just a pseudo frame with a preview of the aura so we don't have to check/un-check Group By Frame to preview them?

Thank you!

**Comment by InfusOnWoW** [comment]
I do not understand the problem from your description.

**Comment by MetalMusicMan** [comment]
Not a problem, but a feature request.  

When you set a Dynamic Group to "Group by Frame", you cannot see the child WAs, it's just an empty gray box around them. You have to un-check "Group by Frame" to see them, then re-check it again when you're done previewing the WA.

It would be nice if there was some placeholder frame that would show the child WAs so you could ignore them, like how Nameplate-anchored WAs show a placeholder nameplate.

**Comment by mrbuds** [comment]
We need an export of an aura showing your issue, because it is working as you wish when i try

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/b33953d0-a8b0-4be0-89b9-ef68af408cd9)

**Comment by mrbuds** [comment]
My test aura:

```
!WA:2!fsv3UTrru4AwkLUTusScHqOqJQqvu(PGSiLl4cWRJnXGJT7UB(PbKIND3XEhL1ZSDMzJJZD1Qc6n9glepa(AUYpc5j4ilEcYJqEc4mEDqOEd3SZz3987333zkSxrvPTONuSFXOIrVSKtpPyWKTB5w)Wwn9l34IaHmIkDiHhhjfPPl5KWo7mImAdFHirZsLN2QBxfvxqoCHXucpmwiBlyCDj)wTNMNIkIeH8NkuOGv6szkA5CNOYD5mDhjjuZeC1JDvAIuBh0LXzQyBh8qBpslz96rLQ1FGCH5VnjIgK1TR)WuQC7QnAxB3goA8fxsMKuAKkLMKupszFHklGEcLR9qVzNo9OkL98pYZVSRVtgM8G0eYqQ0Lt6tv2UZDnyBkjrh)VH2wsXqD9AxTrJXz8fTG90qrswFUxkjKAfijrSm1lU9iC4AW6Z0XUKewpEqLQn9R6ocX1CpL4iAIVWem)U0EM522jrqIQfOjjy9w1TFgIT2o4ueUk852UHjeLYy5OyNrngLYyrtpw0FZMdpuEWq1SGfuuooBzz126RF0Myz1ed0wqs4S(ennESIM0Do7e40Y3V1oUQqSSwtcXstLge9(nCdYzT4j5NvJ6rtx27zzejDJAzjjBSFmttNiN3)MyopAiIHSquaLLUikpSzVUBIbnU1Lmt25KK9qIeJ5vZizAuc0kDoZBhek4Dz9ShR000Y8Ej07Db(jeS46AO8qidClVv9D9g1tYIM3LUBDEEDYvE3CAxjYIEAjrtSMOfHNKxQ1k879VplQut6GjDXEVctgMq7m2KO9zr64BDzUMTMjEtQd8Q4wTAZXezydkVNo(fRUqgxNJvYYrjKAhUGtNr(Vc5XnlVt12nkJeUYq2xFcocrS8jCkJ3vi7pNoShNthO5JH3P25uIY04ZR1nGvGNmlc1XMFFKrvlvutIuJm(zAq4jo9jmEn4G5Edpfoe(f88oV(xkgU(l)KjmmAprMmKE3Rb3Oa82WnNfIlWrIbCVbSuANZV6vdth7ycOdS0DEaS8Forflgujbhwvhm1Vh8(WAWDHpc(y4EWQ2WhAdFWyZ(dUkPPqrhuwTnSHD6YMT6tO(57l7iIO)11GV)vxEmfzyJ2w7AgXy4BGnX9zfrBMzAm8PRVkSYmC9WiQnckEuqmL1lw)C4H1GpZSaaFX8NF58NpA(ZVd64gEL83c23GSVoa9R))qgSNnSRnCBmCB4o2W7AdF10nF4p)0gQVTx8HEoNje9lKwex0RSa0WzdhfAhy7fAnxuRTrjOXODR3USlEda8JwUdmATNJxlKgtSGY2sg3OqPXPRCf67tpvVftrcsOrXWpypnIPm3qvh5J1EJ38pgDLJDG3QqXt(7d(Np
```

**Comment by MetalMusicMan** [comment]
Thank you for the reply! AH, yes, mine also works if set to "Group by Frame > Nameplates" as your sample is. What I forgot to mention specifically in the original example was that this pertains to "Group by Frame: Unit Frames." If you change your sample to be "Group by Frame > Unit Frames" then a preview does not show and you must toggle to Nameplate or Ungroup to preview. 

Here is your same WA with that enabled and there is no preview: 

`!WA:2!fsz3YTnruC8AmLmvT0M6PecLcntb6mLcHIPjD4slh7jgCS9SsUFeyiEL0APDISwXURIJZD1thO30B8WWdGVMR8JqEcoJhEcYJqEc4Swoma3WnshT6SN98XV)BHNwsr2AZVDZYLgukOuWRFSDOumC6UTjn2VDl3knpZtidysBQ)HbsrA6Q2X8toHkd2WviI18050mDKq2ovZfjkl5O297Ry6cNRes9UJ8K8axQxmBnsl2WnkhnlpGvfXc53vOqHIevk1NDzj1Fre2MO0uP2YMNW1wE9XxQiRXAjpmKjv3((YLM)Y0aMxw)(UJszYDR1St9UnT14heAMKwESkLfh3iqzDMkZJDelr7GEZpE2bvR44EGJBfIRDgEiEPX0rmjjHoGPSilC1Bxgnwh93BTJKHBL40PwZMtYswMcwZ8fXzdsCmvqrpjnGNPE11MOyX97i4yySB762EpcnMhM4vTwl3AKXzkwt(aUosIvQjmfMIhdHfUOboHMWhqnTITH3ToCl7erc7ugvXC0swsOoAL5bybA84at5kvmFrsGASXhtZaEO9akpb3l8q4lwb(syt4RqZB8Fx5CmdzYeA8tXGGH7n2XcAqDBf)eCCnidhVw2yB0Fn4Xwe)yQszS800ySLymhJWsEXp3BjHKpylwSyNIpAZTMqL(nxK1VAnzELXUabAKGCco(9XWvCQpZKmM8)EnjE5Eenn)DTGqw6nD(5mQKTr9S44nEwexZMO0S0kjHXS7U0rhmZVSTH8GhoNM4JGzhMSloKN0Tvd36Kk7vJeBA(xDsisMpJhOJU6yJ5ItMSZzyVehlj66ipkKEKk70ORJNsKj9zE8bPySpn)WYb9RmTpMqv5s)ywVPAH)r5nZ1l8RdUhpOms9LZ4bZoumyRwJ2x(8rQz9LiQHJtQMw8880SUzjto45uLuRwRPYf8GzLtdgHOj3hvMzPEy(1NhAjpEPoB2YY0GBLDB3jDvKVQ8pl9Etn8bpxFoJN0xiZbmZ4tVWQqj)B)6pBkhD0zrLENlbRua(b4hN7JY8aXWeNH8uwVtV4tZijcUgYOwW1TGBybRE97d383NQIedRgJmRQhIBVh8(W6WDGpc(y4UWAwWhAbFWeJsdfDAguYgvi7cByLEtJ()iMBUYApra7pUe81V58dz4m2aHAIjvJGppxx8Vz7h9)t741fkQ2OCWe)b3En4wZrzNbBnn2KaVigpms)sOCD4BmWnS1INBV45tw8SjSh8mBtBcEhRXx0l6nlGRmxI0a)X6V1B)BP36IF5YowVdxzUamiI4FH2Oi8cl7teIbfslHJRQl9gRASiz9GolPh4kq3XDB0PcbV6aVfjnIwKm0aTVeClcKzB9GV)fnvpjmAFhjpXGEyXTFbiUh8twWbwWNaFAPJ(ZN)xp`

I realize this is not a bug, I just think it would be a very nice feature to have a pseudo Unit Frame like there is a pseudo Nameplate for display purposes when previewing.

**Comment by mrbuds** [comment]
Group by Frame > UnitFrame preview works correctly if you use a trigger that create clones with correct unit parameter when options are open

Your example use a trigger that create clones with nameplate units, it's normal they won't show on unitframes

This example work

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/370a4cdc-5865-42d9-a911-af13be07ca5f)

```
!WA:2!fwvZYTrrq4ieHuS5hsuatWeiQcHujGXK4uoCbFqRSewGSKQDxLFCiyp7oJ0oL3DMLzMvYYuCrvkixYfv8eOZCspc(aNNYfpb5rWpb0ZUYPItoWCyMzNE6U)6U)MEl8GsYvwNmOuCjCj8Zx1UVGpC6gTDASv7wEvA(sFUate2OGDXcEsYfTJO7VpsGl7X5rkAIyV296jjQcIrZ3mUVGI9gLqUUZ6ZYvVkpIl(Xcfkum5IPssfwqix0Hi6YOQDeOafLZK33rQqcLLFpkJkdTSHfL1yLG2Vprix8MI5B)JPyIFAVEgFi2OwZo1720wbF4GsfOvgltirrnWsRxkt9jdimLlCB6EZ2UAfxVTD9Q44zNcg3pjcnIiCyOyI0Yj7Q(BqqrQWxPAhbbu1XTtTMnNKYMdbRzb8O0yMBckGu0xGW0u5ZoNaIaJ4ctKKOED4uWEvR1YRMJdkI2NPVXyi8BsJPQWXcUczc8ctbF5q6BYbwosJfp9rGMebdf9aiYbbVWoIJW19vOiatl4eNc5ElBisdwq)nwobriP0SZws3Ny2mdLNKnyqFJd9NxaZReflwStX7S8Q(bCwpAFlbIrJrks4rsUqTXiFtfe5hrwWPfzy5vcDKbGNlonGyWvwXTPJFEXnCA(AnCFsYLC)1uKGuUEAuu5hgsvKPISqZOZb4rqQMgaCS0K5A5c490hIEDgXKUTA4v3PYM1SnWXMXzqPnkjevesAdZZ5tmSShsXQWZ(sikGeptvhysCHVtL1B01DLukE2U84vBnAlXJgjpi3F5K03FApaGvPIGiYotv8Gb555Ru4pJVofVce1hIsvaMANKroTM1taSexLaPqfpkhV1nhzcmF3Qo1Q1AIursQW6hrU2CIFdg4SItqIGMewFv4ZwWxYtfbeFACceBorgUWzNcraMo3ruwpUioJAynjVWaBVV(C1pGGKgiKzQZOVS2(qmW4nI32W)fsIXqYXM7zWL22ogrz11pj726Fw)u9VaRN)npPuWIp)lNsbTDZG3vpLULL(mf03DfV2DomaERJ5dzUdPjKDo44pnv8qBJw7O)GlCt9f)NPYq(WQrqbtUJ(Y(bPsfpwVG(J1FQ(Q6pt)55pQK(WJqVUU6pYsFf9NOxeEpLD1SWygumvK0emmR7TxHo9szzTiUf62wLHbKFkV7sLhuMYkNGOcjiOmMNjZmgSSbgLxRCpuKK8AhheIy9jyqIsKMlGWWVYMMEcgB(WkB3aO5G7)bdtDtsSpKBV1j8H5(uWq3DPY371p3mqpXyPLxM(u4c)2jezgZbNbcl9wcpjeFB5zyCTSLti73F1xhhrhVkiQublpInNzzPVKTDBVn0xZk5sMMVdiE5T12KJj)9P0F1loAxcWKnTxuog(vO(l8bv8AVj07vIugwhjuFRfxqF5dH2xM2lMx1mSFiH2puTM(RRRxY0isVC283MnFNS5U6hO)EnwVLHu)MCZT))zR6hBPFKL(9kO3y2Q3(NECt531pCl3Kp8yIPhzp16uPPdgomPe0ZT6CjqecbezhDZ5p1133zOPlYA62f1Dg3TrNkoqhBD1I67zjOmtJbsOtWX9nlAVpNhxygMkn)9Obq(VY78U)14JD9o6ZcrLL(8w6lyvAW)(O)7d
```

**Comment by MetalMusicMan** [comment]
Does not work for me when importing your new string: 

![image](https://github.com/WeakAuras/WeakAuras2/assets/51964348/e040e0bc-c892-4eb6-b6e8-df2881188544)

Also, does not work with your old string if I select Smart Group, etc.: 

![image](https://github.com/WeakAuras/WeakAuras2/assets/51964348/720faf16-22d5-437c-b7b8-6e8df23f4037)

Which is specifically what I am saying would be nice, a sample Unit Frame the way there is a sample Nameplate. So any time we used a Dynamic Group with Group by Frame > Unit Frames, we could see a sample Unit Frame (could just be a simple box/rectangle) that would show how the children of the Dynamic Group would look when anchored to their corresponding Smart Group frames.

**Comment by mrbuds** [comment]
With this example you don't see it anchored to your unitframe because you'r not in a group and don't have raid frames shown.
It make sense to have a fake anchor for nameplates because their overall look is similar for 99.99% of users

But unit/raid frames are too different for each person
It's much better to see them on your own unit frames, not on a fake anchor that doesn't match width/height/scale.

I don't agree this suggestion is good.

**Comment by MetalMusicMan** [comment]
I don't see them on my unit frames when I am in a group or raid either 🤷‍♀️
