### ISSUE TITLE
Tems ICC Pack says always update even after updating multiple times

### ISSUE THREAD

**Issue by Apx2023** [WeakAuras/WeakAuras2#4788]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Tems ICC Pack says always update even after updating multiple times

### WeakAuras Version

5.8.7

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
no lua error
```

### Reproduction Steps

click update, it updates, still says need update

### Last Good Version

?

**Comment by InfusOnWoW** [comment]
Your reproduction steps obviously aren't enough to reproduce your problem as you didn't even include your settings.

Your most likely issue is that the update is linked to multiple auras, which are you can see from the tooltip of the update.
