### ISSUE TITLE
Not UnitInRange

### ISSUE THREAD

**Issue by Huntershows** [WeakAuras/WeakAuras2#4791]
The desired function: when the healer is not within the range of the party or Raid, display text.
The trigger has only one option: within the range by UnitInRange, only can display in the chatframe when the icon be hidden, but cannot be displayed continuously.
Can add an option that is not within the range?

**Comment by mrbuds** [comment]
Range check with group doesn't work in combat while in dongeons/raids.

**Comment by Huntershows** [comment]
Thank you.
But can give warning in combat. Please see below my simple WA.
!WA:2!1rvmpUrru4ySeeTGGlgKfcqOJaknr6cbjIe0G8ESw3HCUZSEnoPYE2DE7Ud3UZm6nZEND6WcjsdfCfHQiHCbvu5gkcsiLFbRS4xWvqcviD)cyMDDGtOyxy)Ep)M579((EVPr3w5TOTO3)6OOqNX4aE4WGE7FGho9W4yfOBSsLsOItUBT77CPLeEuQa7lyCD4UEhe45l)aktjZiZcGP6XXcmNOhFZDYzCFcpbwhXLl4GC7NtQYXAw(ZsRHCROcLwKBZyOKs0GpCmW1NrkmrjAw0igvN62X4IKintWv3YxPjO2jmMXzQ0h0cB(4CqPig01ZKGFF)9piybvmED0jOXojtCsAynAN)xp8NE6V)d)5Yh9Kh8J)9V9nTsAIRZTS9PMKRtlTvytxdgAN5AKLKaO6vVgU28(V(zfkymjujWWBlOWKvw)OuITobm1TWCs)edxlDrrgeUNxNEE(lOqyrCCGPqX9861V7WEYRypjsy0BtWJ2NtHPPYw)3TVhqYQqyPn2AIEY8QdzU4jLVS8ngAaB7DFg4mLH5u(CIPRCQs0wmtQQywcxGWNdeA6CLeYY2NQCotvewr8dm1gB6YX72zqW4bbD8dCTCA57(Vz0hbtg(d671R3zrzeLIfZIiwPXr2(ciWurcohm1dn90c(AEZrEfRoEmeu7BBSF5sYRU5rLCb1qoAyY5MPqa5KSVYOeg4((tvqwC1Wz5l6gl4A5wDr292(lliuZjiBheSWu2(qIDU5TAxEJvg3qs0rwzHtDZeeA3qnjZ0xT9ZlY0mhxdPe1U8ZC8RAoRLRIDpWAm3cYaJdyeMcmccz5sbQxV3CN69MMYTQ3B6IgbO6l5wJaYrDkqI6tF6V(WN8ZpAbwvv25axTPPLV9ZLbQn8TebvE9nts0zgXMfnwNIGkvKrNTWW(uw1gJZ8teiDesKZhT2q((B(UKieXSeCt)irMa)IMMpBAVNm9I79Lxo0aBmlXb)AZoelEMBpVUbl0IOJRfT3SX3LEvgD(icYz8K3dNT(TNLXwIAG2kCnp)ceOLIchSRVN3bYRT5QodsirZghNjey6hvWOlVl2xDtVIWGrdxzEpXCFhkR5JLx4AEHL1I3UvTAJgnAUWmFd0QhE(2xzjJxJJD((ucNvBERYxR7JbIYwWaprN(sL3O8YROgf2(3vpeHkWQbQ528SDr5LDZjmE3Y4QSltktlzMF36)hPLY)J35t25dBD8FCN)5d

**Comment by Huntershows** [comment]
On the raid frame, when blood bar turns gray, whatever in combat or not, will give warning in chat frame. 

I want to show warning in one frame which is in pointed position of screen and show it until close to healer (blood bar turns light).

**Comment by InfusOnWoW** [comment]
The unit characteristics trigger can check if an healer is in range. Negating that is easily done, so this is already easily possible.

**Comment by Huntershows** [comment]
Only can show on chatframe one time, can not continuously display until close to healer.
WA not give option of not UnitInRange.
Lua language seems simple, but it is very difficult to write, even can not know the meaning when addons or WA code data.
