### ISSUE TITLE
Ver 5.9.0 Frame Strata

### ISSUE THREAD

**Issue by Theguyxd** [WeakAuras/WeakAuras2#4792]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Version 5.9.0 does not respect inhereted frame strata. Different auras end up ontop of eachother even tho they shouldn't given the order within a group. All auras in question are simple and created using default templates. Rolling back to 5.8.7 fixes the issue.

### WeakAuras Version

5.9.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Updating from 5.8.7 to 5.9.0 makes auras overlap incorrectly within a group

### Last Good Version

5.8.7

**Comment by mrbuds** [comment]
Without any example provided, what you think is right or wrong may be intended behavior, there is no way to tell with this incomplete ticket.

**Comment by Theguyxd** [comment]
This screenshot was taken after I rolled back to 5.8.7. Note how the number that indicates charges of spells appear on top of the empty Fury bar. This is correct and how it is supposed to look. 

When I update to 5.9.0 the charge numbers on abilities like Throw Glaive, Immolation Aura and Fel Rush will appear underneath the Fury bar. without me changing anything at all. The order of the auras inside the group stay the same but on 5.9.0 something has changed that makes it so the numbers are now appear underneath the Fury Bar. The numbers themselves are a part of the icons and are not a seperate weakaura that is just attached or anything.

I currently do not have a screenshot of how it looks on 5.9.0. But just imagine the charges number on the icons now being underneath the Fury bar. 

![Memes](https://github.com/WeakAuras/WeakAuras2/assets/75401245/bb0cec82-a9a6-45e1-aa00-a51ab2d4c57c)

**Comment by Theguyxd** [comment]
I probably should've just updated the original post but hopefully this is okay.

**Comment by mrbuds** [comment]
An export string wasn't provided so it's not possible to know the settings of these auras.
If both have the same strata settings they won't behave like if they have a different strata.

**Comment by Theguyxd** [comment]
Thats the point. How it has always worked within a group is that if it is set to inherited it will respect the order within the group. If I want an aura to be ontop/above another one within the same group you used to be able to just move then up or down the list inside the group. Since they all have inherited strata levels from the main group. 

Here is a string for the entire group in question. I have no idea why it would behave differently in 5.9.0 compared to every single previous version in recent memory. 

!WA:2!L33c0TX51zYrWQXb2PHIwsrw(fmTLnPSScF)WXo0eKaKqc8faOiLCuigamaZqcGz4mdafKxxNWnXrPUUoLPXnpAsCz6MUjTnnHND96KUnXH5rtRDs(x2DtMnp24Lj1XnV2SA30Zz72eT37)mdWaGbGKaKwPN1NJPaMh)yM)7977(4)ENH5mnPeO7t23j7TPunfRPyx6w3icB0fIjlknKysr5t5WHJjD02j7wQPOIPvLftMKl2q8cjJjZL(BTzqjUOQYSjDfuibVQCir5uCPv3mOyMKU8kZMa)MIKRq8YIl5AKKScz5CDgU0j4ythLZvZJnYRFOrA2vhR4ozgzxUZep(LhNtLNtEj2KlO)D8pkUythZLKSyuLLNiECxJcFDLXyfst)0YEZiNZLBw5vOFie3fu3CWicjfu5uCH)UTx8x7yZiIYX4KDBCFk1O7Kcx8ISYXCfsumPQGuaLOSj5Cer)44LZb)OkCQmRkZLqqmDOCsCbsilMrAv9JiOWf52)QQIrZYjRahWryEh8RPVl9jrggghgBWxAyKCiFbJHuMnQkCgk9eqrLvw1zK4cPfu4D6g(hvNlRklKibmOh9UKn(4JTAmUiWCcEripQh)t6DA)UvXRi2mYSDSSIexYK(IP4CtLmr4YcZ)bHJw4cRn3qdgm0CbdnyGqUZadEePKS54KdKMnfNIZa0dnYOCSjv5ZFQtkZbNAGGt6XV)vYK24sWPXTTNyj4KoqWfZWkZ5YBMKjDndpmlVU(E1VbF1RbsAEr5jffGHFipJhYtGvytlKIfVT7HCRExNJvHlOkOoLqL)vroM70IP52igCZGhXC4TMSchO8ftzz8qXBCs)UtbIFVK(GtG0p5(iVbY9d)7Tv6wAwi26dZLse0uGlFo5nyZOcxntirN0DUwCz4Uh(XzvzDCz9RuV4MWFKibhkGhpJ7oPiBmVrubnI0QhoqQmGgIt3W0C0dt84mq0KSkk4NCRaAb4hIaxRXfs48Yc4VyA2KNrxR4jwfMwdq1GuC2rgHyRnb3iZEbpdNQLZWTkEdkyCvjKooaKO3)oxrHlzC6ShPNMI(0(U0DUQaCSactok3n3a5Mh95I8Ox5T0qd7JCOrFUrF0Fzdn0adPBspBefuMJjUu6GljiXfEDZVIsnE34yeMC7V57I08ZiNrHBC4Mo8kOkevF4OKRbGkPNiDYCHj3l5KKt4KC3ojhNCpKxpPnslKwHz57IChK7K0UtymEjYXcq18WDTc9t4iEK99ItlDay4NlbxAozHOb5fxAI0H3OOVUPc9FgY4ce)v2qguedAomKRzdCmYpSHXRL7v6gnpdxtklMqMtrXvl0ZPv6f5jCUcEwGWn6cHnUuxlMGY8zsdyUSCDWMoN0byPFoKUM9yIX4(ZAGCQN4YlWXjnikKvdGYbEYKKEaKNcRkQyYXto9Xpm5yBasuKUejdshlUbeFoutWb5yRG7LUfdiXCrZZgyWbnxwbfHij5cBEQCG0H05ggFtuNKicphsVogzO4Bs13MdO9MZqf8Uo4Dgo0DgMmmQ7j1eElx8XWtgb3fXl9VJs)7HjHi(CgrcqUGI1BCztLJWUVOOykKWVtYTaOtNexoj3MtPdAEai76WckSW1CmEsViaMI3ayNji8bkBl3wzB5grksaCsUMarnnZ4GEXBktbrbmZZfoWscXu5hJ8Goi(xRZGEAxEPlgB(aYYcPr2wqsmiXDa2Ks8SoiJF07kquEUOl0dP59VCwwzb8c1nQFfilBYmCoKJYZcMFacvYJeEzWKcWUOMJWrMWjzaNx6ojtbykjYBebttFLF1vEnEpocMibctcYBmLCB0zfDSdz6WKZCuY(jZukobXhiobvfTItiZs3mUPZfM8qK3e9OppmeVzD9AYCgQVKWHjN9i77V7dcNlHLeHeLQBsIr1gjMkHK4XjjzijCqeOQwK5dtwG0jSdEskuNHKUu1edncqTUuLc)RfxqyKaYTnYeXNXq(wcj7dS10U4SPSUwKkv0su4HP3cI99J8wjm4TYegLHKSJbQKKlWtY5aL2GSKCruosEyY)kYJ4G8BrLzKhfewlgMekSHW6MzOYQp3vUYJ9rouzYkQ6l52)nH5()Xvr9GHscMxGRMPdVjyXn6cktaAaSQIYnD)u5sb5iiaJOFi7Zk3hiT)nqILG0DXBiBTiBQzqbkqVpdbkk8ktIMK5shvQjvacoNcplGsM1WlcPBKUr6F0nDmNIXhi9Vs(918XuS5iLm(qavHuCX2uF4nn64EWPdnH0nq3iy7ueTkfDges6Eq4RxwFGeUaxm6gFRs3PnJpoWZLKlbB0CZfpPOOm)60dy(mkQcXZbmRYIQayhjxCp(eJ7r62R0OijZfvaTMc8RYa)kEiBOB42CYyv6PvGwzfJHjT6L9kiZ6kiBAfxUtcspPgTmxwWtTIMIpRXOQFfBsxVb9BlbS0ZiZkT8mgFyJ8)uu3ZMy6q(9b3n6)mwCeQJqtmP0TwP7r9VXi5QshqkXyZHwHcx43dDb9ULATsNrSCGzDHOZPYdMj5bg2CgtAM3EMmfGkVq6ej5cDNftzC4JW88)8Wg0fIHniqSAmHYjbataMdOcd0FOWfW8)gMCba(gW6aQ3)AjB1tN91Ryc2(Adr(inac9DIeialSbehgsQVnxPHl)P)gwG4WOF7Jdi7l1yaQvE3OgkLHfbRiAgjtnyzbS7AuViasGerJf2GUfa6ih7Dqo)6wJsb5Enq2SDWc(1uo37wcvjVDgY7y1J1(jbBoYGnhYLiVtYVn5Xj)oKNG87(wjFugY7cgRFpYkK3N(j)EyGr73N8u6MdlheKFOYdUj)bK3l5D7G8(ziFiYhM8hs(GKpqyYtt(JiFKWKvzi)XTs(3KJ8K6wcEkzDVy7qxG(cxByqGt(tSrw)PBmmiLxL6)e9u4xRWN7OYEuqU5x46qLGAMdSGQdAeoVUZRYu3XWwro0BGKzd1r7NDMt3ZmbiximQtH6oNcmB4L0SdYdlBoV)in1wZIsn)apGfBi5pkY)oy)Td7hma8BD0dtEuPMaELt25jTc41nfbhT0HesRGbufvaMjcWPq9dxPy7t5p611JglDa0NdYJWOFmNYbZOdCPJCKhSHgG7OhLOIA7wmxvSxiJCLFfO2)nlrTNAqJ8wr7yK3gVvlxM(E8VEFgQ36gTCJHytwgUjlZGvPotubf68ueK)KdAJgZ9Bskig2gVkotVtMyS4DDMSY(2D9QWQlz5vxUwYn7)vBWZGQl6(va6o6KluwkJzzJrABnrVSD(iymrxW9GvlKcdu0SLt3jzOZ4fpDdZ)40DwYNIVsZ4R)6dxGj2gOOvhGG7yyUcbNgtGwDg7vtv1Ye2C2Y)AD3QBXHBD(4QNsfN4EqkNToRCTISVuhUHOKwA1rNiGVZnX4Hg0pXXt3O0b9LkLysAOUUgecTIM0hPMMoDemIkxdXZkQq3MSpiIrvbwPd6rrHdZEKBigXfCnmnBisn6LljMdiz2eC6JXHgInzuH4cCXCfusybo9Hr6a6PdW6MAAmov2uIYs8IkcMhM3mYcIzuCnc7fngWM8kWHjAsgtgL(p7L9LgIzNfJGu)yUf9Jb5fsML7ewY1LkSdPBysrGTijM5QHKzJOFohzgbuFjcR8c3TcD4JYRVNBAWOWrJUNc2Kr)wILaJSZ4(leg6Au2KWVMkmvOs3m5aKMmSxo3dUV5BFSVivF(OuLlieD2OC7V4WyagPMFmQwkQmdAYOgoQnFcNuTCuPgcCg8NktQ0bXbWrez2yczuEBxFndLHa2esKM0Jm4Gng4nd50or1SH8AeGIxlHPORvVV8PICzWuKFHuWSMSEMK4cVIIkeVo64YTrUbhRgLdt9c6dwZ(dqoipPdasD41n8cIM6oYr2VBfrzWeAGK4yDDlt9bf0dzqCQpNBgvmnC1Lw1lmplkhjWGd7B6GRWkh1pnvvVTdt66vVCczHy0FNadxaq5egRL0NQwbpaQRXxhfBDtOHl1HMEu3xS3Gb9V4QXZKm5qcYrbNkPWqiCgDGgqtyjchMkff6o2qWLlbXvDBcNQ62eEPnsKuCjVYClMbWK5M8AA7KD0TUN54owhKuJK0W36WlJBcNS2isgvvX0tabWNKn3Q4M1Ntp0A4Nn9jDLeMN6PgDGx8t(jFUgadMJoWt3yJUWp5g3Dy6zy66p9QjeVq0fGy8uCqhGG0C5Uo(XHnsQO(o8lah0bO)6U1t07LUj0vQhdutFhBaUTbAwr5hc4HuRINBGBwgETbE7P74g1NmW3RY9j7j5Tj(iR)qf8R7p(yOJBg(fMYxLS8w1q5p7s(LsNUNouJ3xDz0Tix6LiwmD8zlXVSS(kpgED3Sw1YSPU)w59hJ30NRUkYNRIIY30mntvJWFhzNosND1Bx90EvTrB6JpO6dMPll)kVe5hyQYt(7jVep5hgysiw4KK)Hdr(rmKFS(f9pjm5NYq(5oi)pCq(zoi)ppa5Y8urAwdPvLCP6KL5sf4nGH19bOg1rHrbrt9NoUphs2acouwsdq7mD0(mt17PxsfctheRG8nVNaBdztTYrrEUTNNQv01jFv31PcHYMF(1kUj5yTo7mJT4zsZgf9bmVxp1a6XqYus6VEoQGd94YNf)tZ7MfiyVzMkq(VJ8jnIkgaKQXS6gf55evVxE0bdmM3P9x9PztT)rhyZn24fXfyy0bE5N9zXpvC2g3g603F4cAZJyRonmxHZo7A60FEtfuy(1y(2)AEpDRtiF62Y0vibd6kqAORxxEKy7bKpRzXFvBzG2vYIO94J9xcTvyYpK8)jpL1Od8D(oFxugdMA)bh8GutTguy)S9Juy)8IPWQck7NvC0jfHYYlUdf2cdgQ5LxWTovpWkBKs7D3)iNQ7UvCpuPSrBBaZ2IasQXsJEWEcPAMxWo4vzjV368BPjP5UaSuBHpcZZE5QsLnYSC9NqnZmkN5S0zZcHqRBuVOj8Vq5iL8wZ1HhG8YcZ(Eh8yDRrP9kn(WbIpWanSdEaOcjDhqHZ4NWxbyr8kMyT2QEq7G2QHz9cwoksg9frbNvmXmZ2TqeFD3zx(M3cMW0Xl98A9WBYDbjbDNFdjKId9alF(QwvpDxOFWfbKWlIA30tEr5gffD9UVSClZALVQK1kl50M3UCAxsoukYryGOjVu5lzn32(0fmd2wKrYoZSJlOOwwUTleC3UVZtRBn1fx1OTQUxaDv2sjy4fG)1Y5T)ibZDwpqWXun)Qg)XxgLcvi2dNffaXwQnx6C7)SDZTRzjhqgtT)QQh5qvOy0nbdMwlZc8BrNHz0b(r339fwNQbPIQuuevXeX9JMiEXQMA2jp98DlhVZo64c5ksZREC7TG4YQBV)1gslqsbciDHLr281Lw6GH9oZkRwiFD7Der1AqjF6EQU7sBPPHVsPMgCNkA8f7C6uZkNDB7Uu9X9Srr5)S6bXTfie91pJMmMMpMIzMqSpjmVBh0mW8EkkdmyoBE)myQxWmWGzIbtbZQmykB0ZUYtQdGESYqpuXWLXv8sqLlf3IzeK4IXVMLVC0JW8N)xuqqzHxZk06ItN9091w)DO21fmcKupqWIITPgGx5f5)nwS7ueh4dAXJnqLzVdsH5zxoQqAHlcUkpymwj9KOE1Xo)JPXCGWAmnD0JSVRD0Qz8PIjnZNtkcdM1kyLxHVO1X(V1cmdMV9Vw3lo)49PmHVmjsBSmt52j25R9P(MgCXmCOLEpPLfIYJfB7ENVYvEzUnZzkctRCIsbWgIrbyNfm6BNML0pszq0pafIc4zljaTGWfHEvr4MxSoYox4(8LkCBpBlINr0FNlLjzLfU7UKOsh2(19zpWxUTi)MLWbxIWfKOLu)cLtcRxAcvHd(JYyHd(GLYbNxK744FTcoQxb22HA7mS(hTRf6nXKMEogkSfJLf554lucZzEhs0DFVcRs8UNqosN91FF932VM6FEBv2)8o7O7m(6nN7zZiV1(N)v3g(N)GRQiXkVaDrYoezkgJk6lYl2qd3)NyjAPmtpGaMRpxhzKtUVlxOUBZx5wJoWlg5tHootlrAlLa2MCPXcbDeCDlXIzbVWxocRr15Jx39v4poGzX1P)I6RQ0zzKUHegN5eY4F1TW9xrg6PiFs9ImonxwozqXeMoFnOJ37)N0uy4pxhm7bBATH9m2eJp60yXVdZVAm3fm9cB3bXZrr6kAD2evmvew1WLjsOcQnvsjkQYBwNZ8sncNYGXWcOJlgxSXesdIhzS8TH7kzCvuYiZj10zfZ4AqzoxU5yZOkeptYBNiZq(486ciuqasKd4ECX0CrwInHOVHxj5zsMQxf(2YHRgPuJrHFbXuyH5nTumwvUizO)d52)euf(JbQ3O2lOVlNjnTNbiF8nXBh2ikIYrWcQgGbRfCjKjdt9GmQ)VSz593u74I5oh2pcy1yr)cpW3f2yfODJFPdX4XxfxUD9YfFD9YfFqAHBRxwTFuArFHf6fTgphm5sS5u0RR211lHGGQYclWH181zpY(E4FeTWWYxIxWi8u4TcTkZ5fvuXUfjhq80jCTlDWPHRoSseWE1GtgcNxiQYk5pmz9pXPX0dEv)pRF3RIvhkQZvOmYIOpxk1KXCQEjN7xmHquPoItlkDX0TO2QtxW)jZbsW0UuFOoppT5xAr9HA)8UeLHT0X5B1jhe(PbDrTAC)YM95JV0ELftJD9bCJTqoZfjLx2OBwCyAMWOG3JlkZPd8YI8jM1QUE9e2bO)voTdg9ZRztkMYDs4Ahvl6yWHhMSpiy3p1bW)R1Y)GJi6vxveHusIYQwXKZYSHz70qV4bFRVR1IJfxHhuhujS0resKgUqn60d6w9illkReEfk5GIqmUab8nYOHa6lPdueddE5rE81OBBuAP3)aKqLH5ybQm)R16ilgYJVZnyMSterHlfmNfO9t22jBdP8qgWRtNDlFZuPNC178OgJUqSyCPdmUNZ4jG(9xidSBl(WsyioBuU30qSkOJaUzLFtt77El8T7niEcyPVzXrY1elIIYSkQprdKhU5jceHwD8khxV80W6QMXOeR)puO80OSGJoWNhfcn((Y)bhKhvJP5vmPn7aUB0lPe5f4V0dQXCZwiVJ(Ox5kFHPEcK8wJ5wy0yU19PXCBfXrRX4IoFOXC7u(yySTJjwJ5oGt)onzB1yowfPzbEv7yx1yU7kWQQX0cS3wbQtnMJRXCpAmNWo(rnM7vJ5KAmVEKsuJPnnM215)UutAmD3u7iYFfzoSJKabttW(7f4o6J8aAm3NgZBGssslgvnMUmkTFk1YD7Ks4K)mHRLoiFCPMYVH5eluB6izgLjbUw7tJPF4N)lJSE0r6H0y0pIZRX8aijhEKafhLtcOfdBs7r56Eg9MiriUqu9EmsJ5nsj7Oxornj64PjbdUOhqJbeVdshm4ErJXDbsnnMH0ygwJXt9shPX4fU)hb()rTs4OX4JYYOXCknMtxbMfng)AmJTfKjAmJRXmHgZKG60uiFHgta4Uoi8)H0yMgyb0yod5X1yMbb7AmZIO7i93zx(MjWI8PMxJ5CAmpKjS(61yEtwHZAmWu)BwJbMYdxcIuJHTCGOgtKJBj)81csuJjkfcQXeJ)sDPJ)YxS0X(Ex5xnZ99flaaP3AueO(sBq9y9BGYt9Egs3En2)F62SbfwD7FbMuCjWQ9jCUIe(bSF8UdlXHIAfu9M87nSf)znb5f0m25o1It3VgKDy0bE5zN9TqthQjZqL1uSnfbhBNvgn66vOQaQ2aE6s5QS63)ndZSTe2chIHsHpN6Av6mxu9JzEadgMCo0vtq5MorJUYds9ye5ziu3BK4zNzIEhn4PALUWouUhQMKttjpnc0wbtXQjfsZbbxbhd2HByNDgI2VhsBuCxmG6dsUSCi236bajh5E3S4(9aI5RSiE(g68blyrDrJjjLFlvPkjAmPTQzi1CLVkY3Fd1JAJBSTiGiqp9rPAivP0cx2SbkU3nkPTAA0slHs)JutZWXUaw2Ck3NzBhtoSB0H7Ln7geYhu6UQ89wrTbJ0nz7bAueyVtP7OYJJLgHzCupu6EQ8XwE3FiB06nU97XBOcHR9BI27qDW1c6XVNHc5nWGJ5bPtETx5k)3)3(L6d0khnBW2sXNQn(rLqQg9aJxR0wOz1cTe0B76P5kjI7jcfAIXUuhK)JGoSJN(gxoephTRCx2lAVb955GbfsiK0LyCxEtct2UgLnRy01CNKngNRHXQOv6Of1j509B2f5l7jhnqNuAmx)LXQRyyUSGRsulCldFpcomKF5MgNBiUusCkQshQ0cqMoOs3yPBoFL8kDuBpdxn71hqjFnsh0tYCkcSPHF)OYCgxKshPKTwy4ULkThxn7lyZshPK5elNyL2d9e3eNccKrH34c4gk(7UA29KWLBds3qXf)S(b)6kEJ5hzlvxm)h(kx(rU7)slvxm5Rvtvwm5R7GqQJsjM8FcUc2yhvaXiTY)zEY)fSwHjFdRLim5BsoY(jAWO(F96iBgM83XJiIVn57q(U069L8FROc991s(EoiVOLk7T1bhzW5hAqXujhKwnVFlg7kOx7YMK5YrEPgjFmYh32MycDYdM6(tnBDjZolfmECjDx82)h7q7bzCVIjsAk0N8kKcPN9lvOMf3mF3BVqASjJZBSD1cBKETBt5bznh5wtL3RnVuaV7lPQfJ6BQO(8HpNdohTZGMIM02JNVVCwvSq3MBFN7y1lmh49TrB6uqioGZQKm)XRzj57uxsEn7)BP31V)578QsvpL8VdYNaZYQ95RfZKBrnBg5VWOxYSTULnsV7B3SFYWK2ovjR88HTk8)fvFPmrXxHSWRxby1DH(HZDwQcJPmQ0VmENQhUXcDM(pLeQly0eq3xX9)1oP)Wi)7RGws(1TpV2s(vzDBT6p1IcZMfBeqx5XXT112RGoTdr)yMzE)dXxbxLnRIanMpm9NYgulkG3fRlznMF7sH4TOm8IdnEor)NEAlq8JMx0OX8hvstJBTKL3YfSXISW8bEHvzbkF(tlUfsFXGi89XT04O1qh2nLr76JZ6dxCv9vEHBmCYCxKFm1(s0RVDZY73kZ6JxA99pfnh(HnZH)XR88DbqYZuLU3FlxyLsyspHZQllqHLr)8s(ZS2eVvLiTYLGaqhIePvELVaQqGq0gI0IwAtdEuKwfOMbsullTj1k6NS4wY9GvQLCrg31Q06B6FTSJi3LNtfQ7yQtSNu56Am)ounKIx0mk8dx0StzH10Grf4wTNvvNrvVqelHv9z2wgLhDG3Lv6wRfn)EgDRgZtyqXU)hP2PyZV6Bfa6Oa(EkRsElVDp2LPvFIsPv7zW09pspslj4DqB9CAhaZTY3oGZT0B3ThY2Xn)lqPW1Bln7UYYMwnU5NQsL1lwIDME7sTCkMFbS)WL4zR)1UWyX6E4zNzMXNqNUvVSGabHnfbpERAPOSNkFrzh2SOS3wYg78MDhwl32BCCBk1UFvuQ97w3gh1948WuzGzjoEpHH)C9L1wjfvIJXV4mbAHVl)ZRUB095Lv2i4TgkjRhrKnwj3(LFWBENZNbsLN4VcLkpzrleAzpHIUxPJqFOA5IUGR6P9WOZnPJZ5zmgu8HSXj0t5Nofjm8v8bx02U8ynBSoYlxst1Px69okU07P(VIl5ZhkC1cm1sSjuNyHRuRQlXY5j3Gk(hTd3zRl1LIQ(KISI(Ku1LmHlwDXObWUVAerxHNxsAmVQT0442m7dO82QBVuBIKFPH8()1jEfo5dvWo69VL2r36Kka3uLMtHHhkDi2lWorBxy7hWrLtxGnZ4BVan2)B42ru776QJfW8eWfMVFbhvL7138N19cU7Au3TNEByT7DTByTZgQ0TNLU6cg89nHb8xTGbgeEh(GwAWLFkF9dg0y(9kfn01SJ03WZ2ZSDg3BTGg2PUzS9Gg4uVHCO2BD4PS29wLovwf9CXZ1tVl25PBP9XBzpYOXkvZOr1M63rHgvRPUSe9)6mZLLxU)7GSxws5McXGxEMlRA9p(8)0x5df7Dxkel30NwWTp(yJpCPjXUMtCzvJjRw0c4lpa5RXqn4M(k)6FcSJBB2RFHgUQK96RXUSxpv6LgU)H6A6t1FilzVUUvcYthyVsq9eR3()FFdKZVzXlQ5vZO1py5Df3l0apGX))wLq2loT2(xZZ8bJmrGST6pxeloXyiVk)zDOgZVVbA2oFy2cQ6k3wb13AeUMXAecYNAoZvpvLA0q7NsnzpRYkfy4QXUhp67Xoy0PxA2r7ywFdTu8PTaJ2c3vk)bbHDcKX3Lei)lXL6Jk4dRl436N0d76I6NYorDxzhtTN4Yl2D)9TBYyUtEQGuxPkdGjGUXhPUDITI5QeGQBFIVCxyQo9kmp)sPgApAbf(d2B9QTEwgjBKfxTwhjdyzLwlja9xQBT25vtL6PNEA330NnqIwMk6E1Yg9ERMu(41ZYgTZ0dQjm5((NAGC(LnlGQDjKPDlXNl(TR9t)R17mJ0)Wz6kqISC7rYS33V(ImPsenMN9FrImTvYxzWj)y(ND85VG4WkE3Je0V)R2GZ6EvzBWm3dP2Txvw8Hy1R0PcOHstfqNxCE3TpCcPtpX87MRk7EeB5p(lGIKRTU5j36krYBv4hNyrj5yruh8cEAFpc28b2n4hRJy8Sj5lxRrR(aIG6OaW8w00Ei7kaSr2IcaBx3x))q781V7GZougv(X7wmwTfwNz1OFdYdlOiNrsDD0kVh8tcIPxvV3rhxmll5ZS8WSY0hRSl7lLKSGIyAPBmFX3bhOqAlfkT0TwXDPxw3hn)(dkKK(qzSW5EBvEF6N8HYFaJjOGpVvmQz9s3SDxoLUl9r8ghuokBAoxHeLX3iqUAjMX74NwxjKSq6f4uD1E(p1Hut5lM8c)eVUY3gTiZLAK(94zY)GQ2svKN6PBOHN56y))VRI8glTkY7LT)wpN70ENDkV7nvroDbS4lzbS0y(SgShF1VYRKRG1yvUPSeRYBAIQV4vnAH64ZwQ50zNkR4sXNxD(whZ4fhX22CAjvG27L(wCObBkp89Ov46n8Xqb1NR(STo2w2gC2vUPE7EMoMorRJeBWH2JwGRphvWv4frqz(HwxINQz1DN6gQTRaSgZZzaG(lxS2FdBuWRNWvgvKV0vWFkBEkHnGv0WUG13NZM3DpPNVZLIMJpYKt6dftMpFd3cRVGeE7S(t18QW)zmebx55FfMd7PQ27PJkhvFdPl5fOdt1FO4(zOyelIHeNUpVz7QTo87zHDGyylFs7vpLcHgZN3iEm4URMPOk4hA4TW8GTtK62h2fErezvVSaI4ZtLdwTQCUqXANFKX6EAoolwv2c5WU6cXXxC2ld8YOOy962wrvROoNLvmDWpRvZgJ11eT7RVCINHJLoLz3sNv3pi8WBta5y(uWBScMo2gl4wf7kKAUgTCCO3p58xUKqa2wYHTMHPsl(2Z(9lK5iZ06xqOCpdxKqPVoMpEhPLAD427S0N5N57dKgly7OUKmf9uLESD8YHMViyRkcP2YVpkM0y(M7czr0yv42ozretFyzpc8SKfrZYw5dy(cCZilIJvL87BUqCOsqjpEPZNhXGXhl7Wz71ZG8X2lbIFXQaeR7CjUfnWvD68GuJLg5THzSd9(EL8bz5wc1)0xBjq9IYdwrqDA5Q0OHlf2(UyvJ5lz0nx5F9FjFMbVqFZo2s(vUOrAvmupQVc8R(wT8VvrYIAD1YnY2)2z1YlbNA7tYq7wT8X2QvlhfFv7fPznRDz8wEJP6EU8Ln9G0Wvr)RTO0WCbBvC2fdmOHNlLcwRPLmVIm31UDvq32IDv9CzTlzx1Uwf4BB0YDwazJujtQTgpyRrxYBwPaJVh8y0U4mA8xB9XQ4yf3sMBH509yh))UgOuyYPM93Cl8Z5BVti)2JJc4RuwuactifiuNzwORL6SgIcy3TaJkwyuDkZQ)wSTCxBS9vGwjuMvRaJ0xG0cVBARoLzbHU9fyujVNgQz5DLsH4FJn5)y2oIlUK8m9FQHoL1aV37On3fsF4R77ro)MfNR)Rc1MjIX1yowrRIN1mJu2Y9vEa((xJVpzFDobVuOi5Fo0wWYxzcW)wlnYUDzxSEdr8FKCm34Jh(cWtPMnFeJ4Y8X2QRw8Gp94XNt3UcMuuTvla41nFAZJ7i8YMF6MazN0nqF3lZPO6vu2CqdJI88N04SP40pj8tmB1dD)IBVUFUJYBVUxI2ED)eERVTjOwrlN1UWBg4dVtYFVHBP2qVU7KYYNVyjo1rN26VLmXwi(PVqRlz9DpXwWopGZT)J57JPX89nI(uJ5LdB1CPgZFpOi)s3cir1y(H6pHBVxnMFGgZ)aZEYJ17TUjkbjF(MOeK1gszqGwgS1Yk1C4DWBGs1jdj6ziVrM(CcMXCwioKYFdHOX8cg0RgIM8VmdaDIxrQBABwt9N1iJY)tnu7j1VIfJjwYxv2fZsxB99AZCFvBmZDXfv7C2zep70EMzhKF5bk8wmVXA2LMTuyuSln7XVMdUk4hKnvj2oWlOk92QsJ5RzJCokN40T0Ys(NzXH2vDNzVcw(1nCU9AFN1ZATTJwIb4N6vu44x3gXe35Y5Rx(LI0TY87i4ytzVMh5)h

**Comment by InfusOnWoW** [comment]
Ah it's about nested groups. Auras in different groups have no guranteed order.

**Comment by Theguyxd** [comment]
Interesting. So what makes it work in older versions then? Just curious :P

**Comment by InfusOnWoW** [comment]
Multiple different parts of the code handled frame levels incompletly and thus the effects with nested groups where somewhat random.
