### ISSUE TITLE
Incorrect Unit Characteristics Target trigger behaviour when unselecting a target

### ISSUE THREAD

**Issue by calummitchell** [WeakAuras/WeakAuras2#4797]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

A simple Unit Characteristics trigger with Unit=target with or without other checks such as level should activate when I have a target and deactivate with I unselect the target by pressing Escape. Instead if I'm close enough to the target (<40yds-ish) the trigger deactivates then activates then deactivates in very quick succession. Among other things this causes the On Show/On Hide to execute unexpectedly. However, when standing further away from the target (>=40yds) the problem doesn't occur.

Related discord help thread https://discord.com/channels/172440238717665280/1192816168306749470

### WeakAuras Version

WeakAuras 5.9.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No errors
```

### Reproduction Steps

1. Click on a target to select it
2. The test aura activates showing your rough range to the target and playing a banana peel sound
3. Stand <40yds from the target
4. Unselect the target by pressing Escape
5. The test aura deactivates but plays the banana peel sound again
6. Repeat the above steps but stand >45yds from the target and the problem won't occur
7. Change the trigger activation to Custom Function and repeat the above steps to see the weird trigger deactivation sequence.

### Export String

```Text
!WA:2!1rvZUnovu4jQlqYIfmrqfthwekIoDeIK2IOtBrZI6scnqAtXX9hef5ETVhBFNX5EV6EVUTzwgHeSbw0hHSMv5raXdGvfpb9rywWAox7qha16ifF)54ZpFFFNtTo1hwNwN(ZTuICtgJdQ(h63R7(TdVGKi6(Lx9SvEv)Vz3WJ1ErImH6RNdFMeLRnIH(WLg56X58idtWx(PonWhfyYv8ghdKxUDUIOB(vGXJWtGLFIHOsaZtEQdWPxRtjuXfFx)4yny(GhmLWJsfQdemUjCN27732t2GY0YmYiBCcIfQHetGmWWgcZ2vt(oVjtousjgimV81nKC8yIHfDmJAsD3g3QiL5PEDpnMjML80ICovUvxUbuXKi40TP0(C9P3M7NUhqzKthyTtFQlHJ)oaGSbzmztrsYyQiO0jNfgZ4mDQJl(Y4m2OyjjGs)RlPMT8VCnJKGBoETSEUgciHAHkCxGKTNGcNDJopeoh4Mb5XXSlNgSZ2d8dg4VTN)TxDGcWR8gCq7E9UjdpklqibfblTfw85p3R0i57EigJg7KsS1lOyAee0flewH(JTX2MfNDLDvPxshRLqwwxQ2XJtgcANBEtgwMDEL2TWIF6Q38pFptB)pDcfH84yFS4u72U3bDoS3v58zfTZuKbFrP(4CyncFKS(m(Q6(EIewKS1TkitLesQqrWYMVF1F4)iPShyLoYhskD4mNytWF7bYhFNILQfEwnd91mlrZjzhHmdgUF5kcNz1ic(6fpSZVdenmWOaEIj9TkEKlxWHRPOoWArGL(uAisGsHXwtTLCXgUdjmENINHFqXgfBwSvXxGVFV))jUXcUXBFI4Iu15vHFUjiV6bjwj5cZx8ORXTHKOxMOSkk3mbHEujhXrSxLI8xgsVZ7nmpZWC8IYiA98fTDCrYlQAb7vGDXyBWgGB6ImyUkcczdLcLzwp3jv9CZn9FHyJv2w0gFCKCX7VPBOGgGObC2evzABraxdA3euwc0YoTF8TLF4D4HvBwPxR2wSXDsxr3ET6fOmHfpYTx7o(HiMhZsCKF09NAsfeXkrv1LvLxTRXra4eL(YYMENR0qwC14f3(((93luddrG1B1MR0CLjgr0mE59R9tPlYOYg3vFud)YUOg(G2SwUkt(4uJrQ3Qvl74YMmrRBNx2A1PXkSBcLuedzUxxnGRJ9ilWfoyhV2T3F8fcf9yfro(4zlwlNrNEIi7Bp6ZwBt1fVs(j3FzthH9RSOatQc0PIm6i1OQY)pQpTIT3PCQDTA1WP2O2LvHgtz8kpH7CKlD)ridsirJcIZecvADT3N3CZMRu)8)8K)(d
```

**Comment by InfusOnWoW** [comment]
That's a blizzard issue, we are receiving 3 events that tell us that you deselected the target, selected the target and deselected the target. 

I've created a bug report for blizzard to look at:
https://github.com/Stanzilla/WoWUIBugs/issues/520

Though I have to admit that blizzard fixes only a few issues affecting addons per year, and as such it might linger there forever.

**Comment by InfusOnWoW** [comment]
Apparently (I haven't tested that), this can be worked around by disabling soft targeting:

/console SoftTargetEnemy 0
/console SoftTargetInteract 0
