### ISSUE TITLE
cannot modify Guild Note

### ISSUE THREAD

**Issue by WingZeroMaster** [WeakAuras/WeakAuras2#4798]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When I try to modify the guild notes, the following error occurs

=====================================================================

1x [ADDON_ACTION_FORBIDDEN] 애드온 'WeakAuras'|1이;가; 보호된 함수 'SetNote()' 호출을 시도했습니다.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetNote'
[string "@FrameXML/StaticPopup.lua"]:2673: in function `OnAccept'
[string "@FrameXML/StaticPopup.lua"]:5317: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

### WeakAuras Version

WeakAuras 5.9.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

TW/Asia

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
1x [ADDON_ACTION_FORBIDDEN] 애드온 'WeakAuras'|1이;가; 보호된 함수 'SetNote()' 호출을 시도했습니다.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetNote'
[string "@FrameXML/StaticPopup.lua"]:2673: in function `OnAccept'
[string "@FrameXML/StaticPopup.lua"]:5317: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

### Reproduction Steps

1) Modify Guild Note
2) Click OK
3) Error Occured

**Comment by InfusOnWoW** [comment]
Nothing indicates that this has anything to do with WA.

**Comment by WingZeroMaster** [comment]
then why WA tried call 'SetNote()'?

**Comment by Jodsderechte** [comment]
Because you have an aura that tries to call it. You can get help with that in discord

**Comment by WingZeroMaster** [comment]
I changed all WA string load option to "NEVER", but same error occured
all addon disabled and only loaded WA, same error occured
Is there a way to find 'setnote' in the entire string of WA?

**Comment by InfusOnWoW** [comment]
Your installed auras can all be found at WTF\Account\<Account #>\SavedVariables\WeakAuras.lua

**Comment by WingZeroMaster** [comment]
I opened WeakAuras.lua by UltraEdit, and tried to find 'setnote' or 'note'....
but there was nothing......

**Comment by InfusOnWoW** [comment]
Nothing in WA calls SetNote, so it is not WeakAuras calling that.

**Comment by WingZeroMaster** [comment]
![error](https://github.com/WeakAuras/WeakAuras2/assets/114285816/a40fc349-da5c-49ef-8fee-e70c27f10ff7)

I deleted all wtf files and reinstall WA.
but same error occured

**Comment by InfusOnWoW** [comment]
It has nothing to do with WA, take a look at your other addons.

**Comment by WingZeroMaster** [comment]
I already wrote it above...
"all addon disabled and only loaded WA, same error occured"

**Comment by InfusOnWoW** [comment]
Then complain to blizzard. Again nothing in WA calls SetNote.
