### ISSUE TITLE
WeakAuras.regionPrototype.SetTextOnText for text1 (stacks) is altered if text2 is ticked

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#480]
**Describe the bug**

altering text1's current text via
        `WeakAuras.regionPrototype.SetTextOnText(aura_env.region.stacks, "any text")` 
while text2 is ticked causes it to display text1's current text instead of "any text"

if text2 is removed however, then it shows "any text"

the code above was used in custom trigger activation 

**To Reproduce**
1. import wa from wago below
2. make sure to /reload before any testing
3. apply slowfall to yourself

**Expected behavior**
I expected "text2 ticked" to show "Spread" when slowfall is applied instead of "Dada".
Both wa should show "Dot" at <=27s remaining, basically when t[2] fires. (this part works fine)

**Which version of WeakAuras are you using?**
beta-9 / live

**Additional context**
profiling wise this seems way better than other options, alternative is every frame if I did profiling correctly

kinda also wanted to make a ticket in case this solves some current/future problems

**Weakaura**
https://wago.io/S1vRUZ477

**Comment by InfusOnWoW** [comment]
That's not a bug in WeakAuras. You are trying to set a text on something that WeakAuras controls. You can either create your own FontStrings or make two auras that have different load conditions.
