### ISSUE TITLE
'Destination Role' added to Combat Log trigger

### ISSUE THREAD

**Issue by BarthWOW** [WeakAuras/WeakAuras2#4800]
**Is your feature request related to a problem? Please describe.**
There is a various types of weakauras that can be made using combat log trigger which cannot be done using any other trigger however to get information about the destination (player) role you have to use other triggers and a smart group which unnecessarily makes the weakaura duplicate and malfunction, to make it work you need to use a code to compare two triggers and not everyone is able to code.

**Describe the solution you'd like**
Add destination role in the combat log trigger

**Describe alternatives you've considered**
Don't have any other alternative ideas as it would probably need a 'Dynamic info from more than 1 trigger' functionality

**Additional context**
Ran into this issue when making a weakaura that displays a dead player's name, his role and marker. However there is no role setting in the combat log trigger so i had to attach other trigger with smart group which makes this impossible to make because i have to set dynamic info to combat log trigger. The smart group trigger that gives the role information is causing issues here and displaying every other unit matching this criteria and giving a fake information. Adding this feature would not only help my idea but probably open a window for many more people and simplify everything, i heard that weakaura team doesn't support PVP much, but this feature could be used a lot by both PVP and PVE communities, a players role information is very valuable but sadly it is accessible only through Aura and Unit/info triggers. If it was added to combat log trigger it would be a complete trigger (at least for me).

**Comment by InfusOnWoW** [comment]
The combat log trigger does not typically carry unit tokens, and as such role information is not available in the general case.

You seem additionally confussed how multiple triggers interact with each other.

**Comment by BarthWOW** [comment]
> The combat log trigger does not typically carry unit tokens, and as such role information is not available in the general case.
> 
> You seem additionally confussed how multiple triggers interact with each other.

Do you think this could be added in Condition trigger? This could actually be really good idea. Combat log wont need that one but you could check the role in any trigger using the condition trigger

**Comment by InfusOnWoW** [comment]
No that's not how different triggers interact.
