### ISSUE TITLE
Dark Corners On Wow SOD Button (Instead of Rounded)

### ISSUE THREAD

**Issue by PeterJBrian** [WeakAuras/WeakAuras2#4803]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The warrior ability Raging Blow shows dark black corners instead of rounded ones like the rest of the buttons. Can you please fix this visual bug? Thank you so much, if you could.

### WeakAuras Version

5.9.0.6

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Created a Raging Blow weak aura. And it has black corners on the icon no matter what I do and how much I fiddle with the settings. All other Buttons i create with Weak Auras have rounded corners and look ok.

### Screenshots

![black corners](https://github.com/WeakAuras/WeakAuras2/assets/156214279/71291ef4-bfe4-4aeb-bcef-a33f64cee118)

### Export String

```Text
!WA:2!Dr1tVTrru86AX)wjqnM0icIdHiLeOQnQQvocobEd2ehsTnZUPjibYE2DND3HSzMvZmRDCaouFkx4I)i4ZCYFcq9CrALf3rQN5u(aG4nZA72uFW7mV3BE)53737vQrLZReuj4QTMq95mhEMWN8j3c5Zt4Idld)edBhgkjQd(tSyZ7)Ix8xtXm)yUOdNYuE7xVLBD0mFopjGpG5mGMs698fxRherIfyFfLZK7HKkSqz5fszuzSLn8rznsjOrreH8d2wm)4v3nD1mjPlnIXfeNussY3XaVfFTw65yLFmjaLXiXPROLeryeb13jMpOnR3SBCDIe(ulzaEO8LYmpsFct1rqcPxGC6u)OJsVR2dAJs4sjpeWaLGNuekfK6N5hJfqvmwQZJw4ZjF0BV1)mtRwqohd1alkEPRDYcbxpT7(1CC764wd5IyWtKwiJ6013FoYSrhbpsqKYn(mtb(5itWSXzk(mbbN4SiCtr4iigByNWhyc7YeP3iZXMbsl7mal9stWdjIPAJkYAzSTAykbzSB8YsQ3KaIhKPUGoXb1pQtJJpACgBo8BLUIUJ1N4wC)j8aYFCRRHUnrWWjpf6vq783V(mcjTg4zFfcdnyaHijHgwr(BbbqIvzcSIepbahejstbU3vRMwrrUqbiogGHtlOwLsx3i08xixaT4UY5hSzCgz8s1BULm9oVMh23WtlvQu5xwiDroyx7y32PFOrOgubxr9pHgOITRbxVUiw0libgHpBwbR(hMNrp3O)NZKkA4qOEeCfulUGq7wTBvpFhbuvABMym8vJlJNxeqZ(one0l347ZWbaoG3W19g1(IinZiBaxeCIaNo6K5hksG(uj1lH0BEn)AtEPR0SvR6OU2TDDB)euZV9a3zldTd9sY6ZROtVrC0AnT92h7EuZw1xlFNzqL4bSIibpJf4ftOrXQNb0nCqFdNXpblL9E5sU3z6HXEEkCcqPxdDEwIIAHmwTTNe4QjeXj1qOMTr5hBzRPiRbhM8QhRhHSLqsAKlmKdDwzR3bnnuaKBhLg0kpd6Dqr0o1ScXAkLvqlGBwtaJdOgf3BBeSuW)S9q9XjzKsJ6JfumGCtnb9yP(C(7xwaZfmyU4J3o3)WoLF4Uvn)vU8Oubhqf1W8BVDU3E5(LZdMWzlgxHNMh(gpQ4L5r53o)N6nbqhxWyfnnoD1f7)08LVHAcEq8JYObtpSQ4Wl7CXtpL)ftuC)(fdtV79)3nPb5FQ4I57A)6V6)(XBb)q4K0yCz0adh96IoAdn(OHlpN9r1R3YdWHqAKLGY0(dylvGSzrQdJVi9yO9LC(5LMgqL61enH3C7rlYZEJXmAbQUx(7145eSu3aiSiv87KVtE1zb6zzqDx9(eigAOxosBNorYRARxf2i)sJ15)s(VM)BWxR3usfy6T6UF5Up8b79GOQvRg(4h94k9)7t))p
```

**Comment by InfusOnWoW** [comment]
That's the way blizzard styled those icons. If you don't like that, either use the zoom setting, install an icon pack or install an icon skinning addons such as masque.
