### ISSUE TITLE
Frame strata problems between layers occur only within a dynamic group, not in a regular group

### ISSUE THREAD

**Issue by SMDal** [WeakAuras/WeakAuras2#4806]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

In a dynamic group,
when layers with the same frame hierarchy are arranged in order,
the upper layer should be positioned below the lower layer in the image.
However, it seems like the frame hierarchy is not applied, and the placement is incorrect.
The information from the upper layer appears to be cutting through
and showing up on the lower layer's image

### WeakAuras Version

WeakAuras 5.9.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

TW/Asia

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
It seems not to be an error, but a bug.
```

### Reproduction Steps

1. Create a dynamic group.
2. Create two layers within the fluid group.
3. Overlap the two layers and add text to each layer's display.
4. Check for errors.

### Last Good Version

Weakaura 5.8.3

### Screenshots

![이미지 128](https://github.com/WeakAuras/WeakAuras2/assets/156682387/fc37d5ce-e94c-4b42-a4d9-a885184a4d66)

The cards at the top are the results from a dynamic group,
and the cards at the bottom are the results from a regular group.
After version 5.8.3, a bug occurred similar to what is seen in the dynamic group at the top.

**Comment by InfusOnWoW** [comment]
All auras in a dynamic group are on the same frame level. This is intended behaviour. Although dynamic groups previously worked differently and thus I think we should add an option for different frame level behaviour.

**Comment by SMDal** [comment]
Isn't there any way to solve it at the moment?

**Comment by SMDal** [comment]
> All auras in a dynamic group are on the same frame level. This is intended behaviour. Although dynamic groups previously worked differently and thus I think we should add an option for different frame level behaviour.

Isn't there any way to solve it at the moment?

**Comment by InfusOnWoW** [comment]
I did change the behaviour again for the next release, it should work in the way you want it. The current behaviour is then an opt-in.

**Comment by SMDal** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you so much. I've been waiting for this update--------- 원본 메일 ---------

  
    보낸사람: InfusOnWoW ***@***.***>
    받는사람: WeakAuras/WeakAuras2 ***@***.***>
      참조: SMDal ***@***.***>,Author ***@***.***>
    날짜: 24.03.06 03:24 GMT +0900
    
    제목: Re: [WeakAuras/WeakAuras2] Frame strata problems between layers occur only within a dynamic group, not in a regular group (Issue #4806)
    
    
  
  
    
Closed #4806 as completed via de49f96.
