### ISSUE TITLE
When weakauras is opened for the first time in a wow session don't make any auras visible or use their last visible state

### ISSUE THREAD

**Issue by calummitchell** [WeakAuras/WeakAuras2#4816]
**Is your feature request related to a problem? Please describe.**
A large number of weakauras are visible when I open weakauras for the first time after logging in or a /reload. There is no scenario where I want this behaviour, it fills my screen with clutter and slows weakauras opening. The first thing I do when this happens is toggle their visibility off. It's a frequent annoyance.

**Describe the solution you'd like**
Currently when you open weakauras for the second and subsequent times during a wow session, weakauras uses the visibility states of all auras from the last time weakauras was closed. I'd like this behaviour for the first time weakauras is opened. Alternatively just don't make any auras visible the first time weakauras is opened. If you're reluctant to change the current behaviour because players are used to it and/or like it, then please add an option to give people some control over this visibility behaviour.

**Describe alternatives you've considered**

**Additional context**
![weakauras](https://github.com/WeakAuras/WeakAuras2/assets/859270/1ec5b79e-8542-4b6a-8f30-2780be501b22)

**Comment by InfusOnWoW** [comment]
We obviously need your settings to reproduce that.

**Comment by calummitchell** [comment]
Oh I thought this was happening to everyone. How do I provide my settings?

**Comment by InfusOnWoW** [comment]
From the issue template:
"If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the WeakAuras.lua file in World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\. In case you do, please export the string and paste it below."

**Comment by calummitchell** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/13988238/WeakAuras.zip)

**Comment by calummitchell** [comment]
Something I just noticed is when this happens if I select a single aura all of the visible auras become not visible (automatically toggle off).

**Comment by InfusOnWoW** [comment]
The behaviour is that all auras that are loaded are shown. I checked several of the auras that are displayed and all of them are indeed loaded all of the time. So this is indeed expected behaviour and I would suggest that these auras shouldn't be loaded all the time, so the problem is in the auras you are using.

**Comment by calummitchell** [comment]
Thanks for the explanation. There's definitely a bunch of these that should have more restrictive load conditions so I can greatly reduce the clutter. However, I'm still not a fan of this expected behavior. It would be nice to have the option to not show loaded weakauras when I first open the addon, although I appreciate you don't really have these type of options/settings so there's no place to put it.
