### ISSUE TITLE
"Stormstrike" for shaman, doesn't seem to trigger if reset from "Stormbringer"

### ISSUE THREAD

**Issue by belven** [WeakAuras/WeakAuras2#4823]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have a simple trigger when stormstrike is avaiable (tried with both action usuable and not on cooldown). Currently it only works if it's normally off cooldown and not available due to "Stormbringer" triggering. 

i.e. When "Stormbringer" resets it, the trigger doesn't actuvate, even though the game suggests it's usuable. 

It also seems to ignore "Stormbringer" aura found in an OR case. As in, if Stormstrike Availalble OR "Stormbringer" found etc.

There was anotehr condition, for Maelstrum stacks < 5 but even when that's 100% the case it only comes up after like 3 seconds

### WeakAuras Version

5.9.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Keep attacking something
Expend Maelstrum charges until < 5 and you have Stormbringer active
The icon won't display, even though the active is clearly available

Note: the picture is a few frames early but it's almsot 100% reproducable where it fails to dispaly

### Last Good Version

No idea

### Screenshots

![WoWScrnShot_012224_171026](https://github.com/WeakAuras/WeakAuras2/assets/6589562/640bff8d-4da0-4601-9c61-0ce8e005b34d)

### Export String

```Text
!WA:2!Dv1pVTTruCPkuKwwudBvd36IoiK2gexuhG40eGguGwrzQA5klPqs)NIgdPJKNeVyY7iU7OKD2QgAZsx0yg6GM7K(eu4TSriKPoMH(bWFc67okzexoq(EV79NFV)DSy9YXLdkh8ITMs8zuhwk3h)zfS9zrm((f377)Nx(Y)UqHILkXVOD)(cS8Rlndr9dz8omcv6vZQLRL9CFglkGnI6mIKG7D5swRGb4qoYxsyuXJSfsexAysOePHxF4Ji0ySKtgmaZf)5D4li)xt5fjyBrcok6nIup8qmv6K2Vp58zDRv1XTRJBvB3jAfAHIXVxTxNSwQa3DaMI5eFNq2O20EZVb7mH(JngfCHzkabVKi0fy(Cogf5S0vZCKmESaqYz45kxEDq6nwt2iqyyRruYM1wKMv6Wzd4yHOYD1oARRrDhogqTTthRMnTPGxegtuEvcfLZ6nna7bPLlKT89SA2P(HnNKsxufmUt2h(Bz3o7Z5GbAa8gO(5FMOnOncqz5VBckLJ0E9ttw9aeocWnlUYXyucJMTIT64DuXZrBypVChu(HzBK9XzFHXSaI4zPuO9meVdkkkPSFQqYIDZrqt2aIFY(91AWO3DbW2YOc8WXYuoTYsH)Y9pTcJxzj3doDRkiAW187CQbMgKSgshRf()awa(VkCfmgH5uu0rWqaeM)4QZW4KQqX2xAJGahorGJ6Rh3YExOKjqqKrsC4yotQuGwCkuVTXdutzF1gzRmhy9GmDaNLsdEX6jLL4ZLDfHiOBDs(CCXKn1c1V6d9CeOWcctkJINC9X3(lfjR(wEOw(YrXILEtU0LWZS6HUTt(iTqukuib05FmjqgAwfyVkpwKZXbAH)688nPFEbIUuF(ZGwaP)fqQQtpSli0Sv7wwzRWH8sPZuTI57OLGNjlscyMC16CYZR8KuuauIqvCDVrUVmsZ1YgX4bhZrjJpEbroagseeViCVf58BTTNSwJwTSS7A221T9b2n(X9CNFDODiphV5Im6KBeh1P6z82h62SrllVqmzqO8vE5jyOzedfu3uaoyd740ijXWu1(3i7edB)iKqOO8KOiyJsrQlKPCScZQHOK1R1S6bDCBB2SATFQ6U72WTXrwEXeoNXdNY1tgAeSWWjq(rduMAB20Q1UxLd76CyxsPNNtnBlRwZHMiiUDI((lJXlVwRxwVKTBOgB7J8XpTZrD0w(0gWvOcf72MikC1Z2wXqGI3(bFJ5ZzS4IjRV0dQM6UebcooiCwFL1osvhR0ujZFy(MWNu83JVnjiBtpWV9jdmSrrjHOs2JutpVkPmSzV8kiixGLfCVDsjbZyI7)W99hfV)wpHtOkVHdNGOKy92YJYE)6zRK94lXi1ndCmDGm8wZdulvWXDvx(cwaXmqmwPJQIK9yZyeHQnmtERS0SHzJaYp4)lHFEEVFVFOqH3Pa8RJPkhrYRGZi08nmGd(paCsVYc7hEVV9E7uE4Rp5)(d
```

**Comment by InfusOnWoW** [comment]
I cannot reproduce any problem with your aura, do note that your second trigger prevents the aura from showing with 0 maelstrom stacks.

**Comment by belven** [comment]
> I cannot reproduce any problem with your aura, do note that your second trigger prevents the aura from showing with 0 maelstrom stacks.

I guess I'd have considered none at all as < 5, but I suppose it's null with nothing, so it can't be determined. Thanks though.
