### ISSUE TITLE
Incorrect loading of weakauras in version 5.9.2

### ISSUE THREAD

**Issue by geberramalho** [WeakAuras/WeakAuras2#4827]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Since the last update (5.9.2) I and some of my guildmates have the same problem: almost all WA are loading, even when the conditions to be loaded are not satisfied. In particular, the WAs associated with specific encouters (encouter ID correctly indicated) are loaded, which provokes a mess. Normally, only the WA qualified to be load should be loaded. The rest will be loaded when the conditions are satisfied.  

### WeakAuras Version

5.9.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Simply, ask to display the loaded WA. There will be a mess in your screen.

### Last Good Version

Until the previous one, there was no problem. 

### Screenshots

![wa-bug](https://github.com/WeakAuras/WeakAuras2/assets/157542478/2996ed47-657b-4d5d-8a8d-7e3c32430e1f)

### Export String

```Text
Lots of them. Perhaps the problem is connected with the "new feature" standby. "This display is on standby. it will be loaded when needed". It is displayed on screen, even in stand by. If you want to create a new category ("standby", besides "loaded" and "unloaded") ok, create it but do not mix it with loaded. It is a mess!
```

**Comment by InfusOnWoW** [comment]
That#s already fixed for the next release.
