### ISSUE TITLE
Spell in range trigger does not work with Mend Pet as intended

### ISSUE THREAD

**Issue by JP-Satrio** [WeakAuras/WeakAuras2#4828]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I tried to create a heal pet! warning (text), and adding a range based color change, to notify the user if they're out of the spell's range. The trigger was pet health % and spell cooldown/charges/count with a condition of spell in range false, but it did not work at all. I tested to move in/out of ranged attack range, but with no success either. With Lisonna's help in the WA discord channel, we got clarified that the weakaura worked if the pet was targeted, but since it should be working without targeting the pet, this specific spell (and probably Health funnel as well) should always be defaulted to pet, without requiring a target.

### WeakAuras Version

WeakAuras 5.9.2

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

as mentioned above
text aura
trigger pet health %<20
trigger spell cooldown/charges/count
condition spell in range -> false : color change

**Comment by emptyrivers** [comment]
It's a bit strange to presume so much about how WeakAuras is 'supposed' to work, I think. Mend pet has a 45 yard range, and indeed as you describe the range condition hinges on whether or not you're in range of your target. For more than 99% of all spells that you would ever track, this is sufficient. And for the rare exception like mend pet, we're not really in the business of creating special magic edge cases (that's your job as the user 🙂).

**Comment by JP-Satrio** [comment]
Well... OK. I see. Actually Mend pet really has a 45 yd range as being said -  but only in SoD https://www.wowhead.com/spell=136/mend-pet in contrary to the classic version, which has a shorter, 20 yd range https://www.wowhead.com/classic/spell=136/mend-pet.
So, the users are in fact able to create workarounds, and the members of the community is helping each other, but as one might expect, the spell in range condition might trigger according to each and every specific spell. Might it not? As I could notice, it changes according to talent specialization, so other hunter spells range trigger works properly. With that being said, I thought it would be a good idea to bring attention to this phenomenon with this specific spell (and probably Health funnel - and haven't tested tho). It started as a bug report, but now I think it's more like a feature request. But I really don't want to force anything, but if you, as a dev, say that it works as intended, I can totally understand that and accept it.
