### ISSUE TITLE
Show spell name in brackets when a spell id is used in the spell name field of a combat log trigger

### ISSUE THREAD

**Issue by calummitchell** [WeakAuras/WeakAuras2#4829]
**Is your feature request related to a problem? Please describe.**
Recently I've seen a number of recommendations on the weakaura discord to use a spell id in the spell name field of a trigger rather than use the spell id field. When you do this in an Aura trigger it helpfully automatically shows you the spell name in brackets after the spell id. It doesn't currently do this for Combat Log triggers though. Probably just an oversight.

**Describe the solution you'd like**
Show spell name in brackets when a spell id is used in the spell name field of a combat log trigger similar to Aura triggers

**Describe alternatives you've considered**
n/a

**Additional context**
![combatlogtrigger](https://github.com/WeakAuras/WeakAuras2/assets/859270/d3217938-35b5-437e-9789-84af1d2eb94d)

**Comment by InfusOnWoW** [comment]
That's the spell name field, which matches only against the name. The Spell Id field above matches against the id. There are subtle technical reasons why different triggers work sligthly differently.

**Comment by calummitchell** [comment]
Ok just to make sure I understand the situation, could you tell me if the following is true?

1. Using a spell id in the spell name field of an Aura trigger is supported. It shows you the spell name it will match against in brackets. In fact it's recommended to do this over using the spell id field.

2. For subtle technical reasons this isn't supported for Combat Log triggers. Which is why the spell name field isn't shown in brackets. I shouldn't be using spell ids in the spell name field of Combat Log triggers.

fyi using a spell id in the spell name field of a Combat Log trigger worked for the few examples I tried (cast success, aura applied), but I'm assuming not everything would work.

**Comment by InfusOnWoW** [comment]
Oh you are right, the combat log trigger actually supports ids in the name field, then you are right that the ui should reflect that.
