### ISSUE TITLE
Load setting for any boss encounter

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#483]
**Is your feature request related to a problem? Please describe.**
Wanting to load a WA in any boss fight, instead of specifying encounter IDs
The usual workaround is checking the existence of boss1 in a trigger but that sometimes fails on encounters where the main boss is absent for phases. 

**Describe the solution you'd like**
Personally I like ticking the encounterID checkbox but leaving the associated textbox blank. In discussion on Discord Infus didn't like that as it's not clear to users that that's what they would do to achieve the goal. I can't really disagree but I do think it has an intuitiveness to it as well as simplicity. I may be thinking too "quick fix" and not "long term" though. 

**Describe alternatives you've considered**
Standard workaround is a trigger firing on ENCOUNTER_START and untriggering on ENCOUNTER_END. So I guess an option might be `status - conditions - in boss fight` or `in encounter` etc.

**Comment by InfusOnWoW** [comment]
You have a strange "intuitiveness"... 

Adding the condition is possible, as it adding it simply as a "In Encounter" option. We after all have a "in pet battle".

**Comment by asakawa-k** [comment]
Oh, you mean the series of checkboxes at the top of the load tab? That would be good, yeah. 
Though, if it's not too much extra trouble, perhaps a checkbox in `Trigger: status - conditions` would be useful too?

**Comment by InfusOnWoW** [comment]
Both wouldn't be that much work. Someone has to argue strongly that this is common enough...

**Comment by asakawa-k** [comment]
/shrug
It comes up occasionally on Discord. More than that I can't say.

**Comment by InfusOnWoW** [comment]
Actually implemented it, since we track those events already.
