### ISSUE TITLE
While Renaming - Sometimes text highlights while typing

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#484]
**Describe the bug**
Sometimes while renaming auras the text will highlight everything while I am typing.  It stops happening after about 30 seconds, but happens consistently during those 30 seconds.

Video: https://www.dropbox.com/s/0krr8qrzy5td458/World%20Of%20Warcraft%202018.07.13%20-%2011.56.09.04-Cut.DVR.mp4?dl=0

**To Reproduce**
1. ???
2. Edit, copy, duplicate, delete auras for awhile
3. Rename an aura
4. Type and the text will be highlighted without your choosing to do so

**Expected behavior**
Text should not highlight without my choosing to do so.

**Screenshots**
Video: https://www.dropbox.com/s/0krr8qrzy5td458/World%20Of%20Warcraft%202018.07.13%20-%2011.56.09.04-Cut.DVR.mp4?dl=0

At no point did I press Shift other than to capitalize letters nor did I press Ctrl+A.

highlight+typing = clearing the field

The highlighting and clearing only occurs when I type a character, but that character does not show up, instead the field is highlighted or cleared.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Addons enabled:

- Bartender4
- BugGrabber
- BugSack
- Can I Mog It?
- idTip
- SharedMedia
- WeakAuras

**Which version of WeakAuras are you using?**
8.0-beta9

**Was it working in a previous version? If yes, which was the last good one?**
BFA Beta - but have seen on Live over time

**Additional context**
Working with updating this set: https://wago.io/AmiYuy-Hunter-ActiveBuffs

**Comment by amiyuy** [comment]
Had it happen again with all other addons disabled and only happened once rather than repeatedly: https://www.dropbox.com/s/39kb1329rklv4if/World%20Of%20Warcraft%202018.07.13%20-%2013.17.12.02.DVR-Cut.mp4?dl=0

**Comment by amiyuy** [comment]
Happened again with first aura I touched after login, you can see everything I did since the loading screen ended: https://www.dropbox.com/s/o7l6k2luips84wu/World%20Of%20Warcraft%202018.07.13%20-%2017.03.46.04.DVR_Cut.mp4?dl=0

This time Bartender4 and idTip were on.

**Comment by InfusOnWoW** [comment]
So @emptyrivers  can't reproduce that, and looking at the code I have no clue at all how that can happen.

We can try debugging it though, you need to edit AceGUIWidget-WeakAurasDisplayButton.lua in WeakAurasOptions\AceGUI-Widgets for that.

Search for function self.callbacks.OnRenameClick(), and add these two lines here:

print("#########");
print(debugstack());

Every time you start renaming that should output the callstack, which is normal. But apparently that function gets called from somewhere while you are editing, which then selects everything.

**Comment by amiyuy** [comment]
I did try a clean Saved Variables file on Beta after Buds suggested it, but at that point I was almost entirely done renaming, so I can't say for certain that it would never happen just from refreshing the Saved Variables.

After trying to get it happen myself yesterday with the old Saved Variables, but I can't make it happen again.  Must have been some other program, pending updating or something on my computer.  I wasn't having problems in text editors or forms though.

I'll keep the debug print in my Live install for awhile in case it happens again, but for now I can't reproduce.

**Comment by InfusOnWoW** [comment]
Right do comment when you see it again. It should not depend on anything in your auras at all. So.
