### ISSUE TITLE
TTS voice options have disappeared

### ISSUE THREAD

**Issue by Electyctz** [WeakAuras/WeakAuras2#4843]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Since about 3 weeks ago all the TTS voice options besides the WoW default ones have disappeared, I have the same exact issue as the one described [here](https://github.com/WeakAuras/WeakAuras2/issues/4605). Tried going back to the version when it was still working (5.9.0, Jan 5th)

The images are pretty much identical with exception to the /etrace which has some different numbers, which are here:

**/run C_VoiceChat.SpeakText(0, "Test", 0,0, 100)** no sound output
![Wow_r9zqfVGLOK](https://github.com/WeakAuras/WeakAuras2/assets/12433617/968d0ce8-4841-46e9-8d4f-3ef7d5d11a6f)

**/run C_VoiceChat.SpeakText(0, "Test", 1,0, 100)** no sound output
![Wow_EmpGXWgKC9](https://github.com/WeakAuras/WeakAuras2/assets/12433617/a8734f3d-500e-412e-ad8c-53e9d351e1f0)

**/run C_VoiceChat.SpeakText(1, "Test", 1,0, 100)** sound output "test", with the male default voice
![Wow_aathw4UFa8](https://github.com/WeakAuras/WeakAuras2/assets/12433617/97a554f6-72eb-4994-a61a-fc0cd8bce73a)

Using the same information as the last post to maybe save you some time

### WeakAuras Version

5.9.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
none
```

### Reproduction Steps

1. open WeakAuras
2. create new aura
3. go to actions
4. check on show box
5. check chat message box
6. select Text-to-speech in Message Type
7. open Voice drop down

### Last Good Version

Possibly 5.9.0? Happened on Jan 5th so whatever game version/addon version it was at that time.

**Comment by InfusOnWoW** [comment]
You cannot have the "exact issue as the one described https://github.com/WeakAuras/WeakAuras2/issues/4605.", because those bugs are fixed. 

We need a lot more information, e.g.
* Which voices are installed in Windows
* What WoW shows as installed voices
* What WA shows as voices
* Whether any of the voices you can select works or not.

**Comment by Electyctz** [comment]
like I said, it's pretty much identical to the settings he has in his images but I will provide you with mine as well then.
![image](https://github.com/WeakAuras/WeakAuras2/assets/12433617/80aabeee-fecf-474d-9191-249fe38b5c26)
![image](https://github.com/WeakAuras/WeakAuras2/assets/12433617/366d8747-fc87-487c-9a70-25b9a124d0d3)
![image](https://github.com/WeakAuras/WeakAuras2/assets/12433617/a55daf3f-d684-4045-be8f-2bc960e5c0ef)

the only difference being I see the default wow voices in the weakaura dropdown instead of nothing, they do work, but they suck really bad in comparison to the windows voice options.

**Comment by InfusOnWoW** [comment]
That's not a WA bug then, the game is not properly showing you the voices you have installed. You'll have to ask Blizzard for support.
