### ISSUE TITLE
[BfA Beta] Checking "Use Full Scan" does not carry over Aura Name or Spell ID

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#485]
**Describe the bug**
On Live the Spell ID and Aura Name are carried over to the appropriate boxes when you check Use Full Scan, however on the Beta those boxes are empty.

**To Reproduce**
1. Create a buff aura
2. Put a Spell ID in the Aura Name box
3. Check Use Full Scan
4. See no names in Aura Name or Spell ID boxes

**Expected behavior**
I expect the name and Spell ID to carry over like they do on Live.

**Screenshots**
![wowscrnshot_071318_151243](https://user-images.githubusercontent.com/3958649/42716301-b58c5480-86af-11e8-9fa3-1bbe950ebceb.jpg)
![wowscrnshot_071318_151246](https://user-images.githubusercontent.com/3958649/42716303-b77e5cf2-86af-11e8-8fe4-1e920f3b91f7.jpg)

Live 2.5.12
![wowscrnshot_071318_151527](https://user-images.githubusercontent.com/3958649/42716395-1dc06d16-86b0-11e8-980b-2ebfda9cb65f.jpg)
![wowscrnshot_071318_151530](https://user-images.githubusercontent.com/3958649/42716396-1dddc866-86b0-11e8-81ad-bd130c1df861.jpg)

**Which version of WeakAuras are you using?**
8.0-beta9

**Was it working in a previous version? If yes, which was the last good one?**
Works on Live 2.5.12

**Comment by InfusOnWoW** [comment]
That's not the behaviour on live. You must have not tested with a freshly created aura.
