### ISSUE TITLE
Ebon Might trigger not updating correctly when spell-queueing an empowered spell immediately after.

### ISSUE THREAD

**Issue by NANTOIANER** [WeakAuras/WeakAuras2#4850]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hey,

I've been noticing that my Ebon Might WA would not update properly occasionally. Every now and then it would only go "on cooldown" with some delay after finishing the Ebon Might cast. Through some further testing I might have found the cause:

Whenever I'm instantly spell-queueing an empowered spell (Fire Breath or Upheaval) after the Ebon Might cast, the WA will not update and go on cooldown (no swipe / %p text / desaturate through condition, etc.) until I finish  (or cancel) the subsequent empowered spell.

So I'm suspecting the empowered spell has some weird interaction here, cause empowered spells incur a GCD at the start and at the end of their cast.

Example video: 

https://github.com/WeakAuras/WeakAuras2/assets/73881929/78b052c8-5a54-404b-93df-735ee388f7ab

Using:

![Wow_ImLnmoXYB7](https://github.com/WeakAuras/WeakAuras2/assets/73881929/9104b568-bef0-405a-8d86-1efc5f6b9df7)
![Wow_t0Sa6yCEu2](https://github.com/WeakAuras/WeakAuras2/assets/73881929/a4200fee-def0-4b5a-a600-d5fc1dccb3e9)

+condition to desaturate when t1 on cd
+"spell known" & " spec" loading conditions

WA link: https://wago.io/aWM75B5L3

Originally suspected it to just be a Blizzard Evoker feature, but unhiding my action bar showed that the cooldown on there is potrayed correctly (and instantly).

Happens with both empowered spells and with extra option `show gcd` enabled or disabled in trigger 1.

In case that's relevant: My spell queue window is set to 200 ms.

### WeakAuras Version

WeakAuras 5.9.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No errors.
```

### Reproduction Steps

1. Cast Ebon Might
2. While cast is about to finish, spam empowered spell.
3. When starting the empowered spell immediately after/when the Ebon Might cast finishes, the WA won't update its cooldown state, until empowered spell is released (at whatever empower level it is at).

**Comment by mrbuds** [comment]
> Originally suspected it to just be a Blizzard Evoker feature, but unhiding my action bar showed that the cooldown on there is potrayed correctly (and instantly).

I was able to reproduce the bug, and for me blizzard action bars have the same problem, they don't update the cooldown when bug happen (it doesn't always happen)

https://www.twitch.tv/videos/2048187016 at 2:20 it's noticeable

For me it's a bug on blizzard's api, not on weakauras

**Comment by mrbuds** [comment]
Do you use an addon for your action bars? Is it stock blizz default ui, or elvui, or bartender or something else?

**Comment by NANTOIANER** [comment]
Oh sorry I forgot. 

Yes, I'm using ElvUI for my bars. But the same behavior happens that I get on ElvUI, also happens for me with all addons except WeakAuras disabled.

Reproduction rate is like 80-90% for me, cause I don't always get the timing right.

**Comment by NANTOIANER** [comment]
I guess you could make an argument for there being a slight delay on the action bar, too. But when I fully channel the empowered cast the WA icon is like a full 1-2 seconds behind.

**Comment by NANTOIANER** [comment]
Hey @mrbuds,

did another test today where I just kept starting/queueing empowered spells at the very end of the Ebon Might cast.

Did about 40 of these and I see what you meant in your comment above now. In some cases the Blizzard action bar doesn't update in the same way the WA doesn't (as seen on the very last cast in your stream test). During my original tests I never had that happen at all and it was only ever the WA not updating, so I totally missed your point.

Timing the empowered cast properly is the only crucial part in reproducing. I added a tick to the cast bar around 94% and hit Fire Breath as soon as the Ebon Might progress bar hits the tick, but I still don't get it right **every** time. 

What I don't understand though is what I showcased in my 2nd clip, where the Blizzard action bar does update, but the WA doesn't. Cause this seems to happen a lot more frequently than both not updating.

That said, I'm not sure how you'd like to proceed. Should I close this issue or leave it up for now?

**Comment by InfusOnWoW** [comment]
We have identified a bug in our code, though the spell is also providing wrong information on that cast sequence.

**Comment by InfusOnWoW** [comment]
This will be **different** in the next release. Unfortunately the api is giving us incorrect information, and thus our display will be slightly odd at times. We should now detect that the spell is on cooldown immediately, but the remaining cooldown time can sometimes jump from e.g. 27s to 24s and that's on blizzard.
