### ISSUE TITLE
Ignore Bigwigs events soon after ENCOUNTER_END except for Respawn

### ISSUE THREAD

**Issue by calummitchell** [WeakAuras/WeakAuras2#4854]
**Is your feature request related to a problem? Please describe.**
This is a fairly minor issue so I'm entering it to make you aware it's happening and let you decide whether it's worth doing something.
Bigwigs will sometimes send a bunch of BigWigs_StartBar events immediately after ENCOUNTER_END. You can see a couple of examples of this happening here https://www.youtube.com/watch?v=oLmd0n4t4V8. I've only noticed this happening on Mythic Smolderon. Some of these timers last long enough that they can trigger weakauras early in the next pull. In my case I had a weakaura tell me "intermission soon" (tts) because a Stage 2 timer was still active in the first 10 seconds of the next pull.

I posted about this issue on the Bigwigs discord (bigwigs-bugs) but they feel it's not their issue.

**Describe the solution you'd like**
These timers don't make sense to exist. The encounter is over, none of these mechanics are going to happen. So maybe just ignore Bigwigs_StartBar events except for Respawn which happen soon (e.g. <= 5 seconds) after ENCOUNTER_END and their corresponding Bigwigs_StopBar events which happen later.

**Describe alternatives you've considered**

**Additional context**
You can read the brief discussion about this problem on the Bigwigs discord bigwigs-bugs channel.

**Comment by calummitchell** [comment]
Oh I forgot to mention, Bigwigs actually shows bars for these events for about 5 seconds then clears them.

**Comment by InfusOnWoW** [comment]
Well that's not our problem? It's a bug in BigWigs.

**Comment by mrbuds** [comment]
Also you didn't link the aura you use to show timers, if it is what i think it is, it doesn't use weakauras built-in triggers.
