### ISSUE TITLE
Colorpicker not working at all

### ISSUE THREAD

**Issue by Zuperhans** [WeakAuras/WeakAuras2#4855]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hi, been looking around for fixes and others with this issue. Since a couple days ago while fiddeling around with weakauras, all of the sudden not any, ANY, color picker is working to choose another color. Impossible. Does not matter if its icon color, foreground/background, glow color, in any aura old or new, nothing works. Have I messed up some setting or os this a bug?

### WeakAuras Version

5.9.2

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Go to any new aura, try to chose any color from the color picker.

### Screenshots

![color picker 1](https://github.com/WeakAuras/WeakAuras2/assets/158732558/364b8c03-c941-4286-8912-88453674504a)
![color picker 2](https://github.com/WeakAuras/WeakAuras2/assets/158732558/5ab6087e-6770-4642-8ce8-1947d8101078)
![color picker 3](https://github.com/WeakAuras/WeakAuras2/assets/158732558/8772dcbe-5e38-48e8-8721-c9654c32e5df)
[weakaura bug.zip](https://github.com/WeakAuras/WeakAuras2/files/14151103/weakaura.bug.zip)

**Comment by InfusOnWoW** [comment]
You did check the "Tested with only WeakAuras" box, but I don't believe you did.

**Comment by mrbuds** [comment]
This is a bug in Bagnon, not in WeakAuras

https://github.com/Jaliborc/Bagnon/issues/1875

**Comment by Zuperhans** [comment]
Thanks for support. Sorry, I missunderstood the option "tested with only weakaura?". All good
