### ISSUE TITLE
5.10.0 update throws new "attempt to initialize with nil" error

### ISSUE THREAD

**Issue by quixoticraindrp** [WeakAuras/WeakAuras2#4860]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Seemingly new in the 5.10.0 update from today (07 FEB 2024) is an error where SavedVariables are being initialized with 'nil' instead of a table:

> Message: ...erface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua:79: Attempt to initialize Archivist SavedVariables with a "nil" instead of a table.
> Time: Wed Feb  7 14:11:15 2024
> Count: 1
> Stack: ...erface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua:79: Attempt to initialize Archivist SavedVariables with a "nil" instead of a table.
> [string "=[C]"]: in function `error'
> [string "@Interface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua"]:53: in function `Assert'
> [string "@Interface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua"]:79: in function `Initialize'
> [string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1117: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1106>
> [string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1123: in function `LoadFromArchive'
> [string "@Interface/AddOns/WeakAuras/History.lua"]:10: in function <Interface/AddOns/WeakAuras/History.lua:8>
> [string "@Interface/AddOns/WeakAuras/History.lua"]:24: in function `CleanArchive'
> [string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1289: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1260>
> 
> Locals: (*temporary) = "Attempt to initialize Archivist SavedVariables with a "nil" instead of a table."

Error occurs even when WA is the only Addon enabled, including when all of the dependent Addons are disabled, and does not occur when WA is not enabled, regardless of what other addons are enabled.

### WeakAuras Version

WeakAuras 5.10.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
Message: ...erface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua:79: Attempt to initialize Archivist SavedVariables with a "nil" instead of a table.
Time: Wed Feb  7 14:11:15 2024
Count: 1
Stack: ...erface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua:79: Attempt to initialize Archivist SavedVariables with a "nil" instead of a table.
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua"]:53: in function `Assert'
[string "@Interface/AddOns/WeakAuras/Libs/Archivist/Archivist.lua"]:79: in function `Initialize'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1117: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1106>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1123: in function `LoadFromArchive'
[string "@Interface/AddOns/WeakAuras/History.lua"]:10: in function <Interface/AddOns/WeakAuras/History.lua:8>
[string "@Interface/AddOns/WeakAuras/History.lua"]:24: in function `CleanArchive'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1289: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1260>

Locals: (*temporary) = "Attempt to initialize Archivist SavedVariables with a "nil" instead of a table."
```

### Reproduction Steps

No real steps involved, error throws as soon as the UI is loaded if WA is enabled.

### Last Good Version

WeakAuras 5.9.2

**Comment by emptyrivers** [comment]
is that the only error you're getting? Also, can you upload your WeakAurasArchive saved variables, please.

**Comment by quixoticraindrp** [comment]
Yes, this is the only error that occurs. 

There are no SavedVariables in the WeakAurasArchive.lua file:

[WeakAurasArchive.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/14202227/WeakAurasArchive.lua.zip)

**Comment by emptyrivers** [comment]
That's the source code, not the saved variables. The savedvariables are found at `WTF/Account/<account #>/SavedVariables/WeakAurasArchive.lua`

**Comment by quixoticraindrp** [comment]
[WeakAurasArchive.lua.zip](https://github.com/WeakAuras/WeakAuras2/files/14202266/WeakAurasArchive.lua.zip)

**Comment by InfusOnWoW** [comment]
The contents of that is literally:
"WeakAurasArchive = nil".

**Comment by quixoticraindrp** [comment]
That's the whole contents of the file WTF/Account/Accountname/SavedVariables/WeakAurasArchive.lua … all I did was zip it up and attach it.

**Comment by emptyrivers** [comment]
this should be fixed for the next release, but for a workaround you can do right now, run this macro:
```
/run WeakAurasArchive = WeakAurasArchive or {}
```

**Comment by quixoticraindrp** [comment]
> this should be fixed for the next release, but for a workaround you can do right now, run this macro:
> 
> ```
> /run WeakAurasArchive = WeakAurasArchive or {}
> ```

Thanks, will do this and then look forward to the next release 🙂
