### ISSUE TITLE
Trigger Aura Buff at Boss is always Trigged.

### ISSUE THREAD

**Issue by nuttin0011** [WeakAuras/WeakAuras2#4864]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Trigger Aura Buff at Boss is always Trigged.

### WeakAuras Version

5.9.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [x] Yes

### Reproduction Steps

1 Create new Icon Aura
2 Set Fallback Icon (Dynamic not has icon data in this case)
3 Set Trigger --> Aura --> Target Boss --> Buff --> Aura name is any E.G. Immolate
4 this icon always show

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/74884682/0ecc23c6-56e7-4d43-bedd-7439b4f775e8)
![image](https://github.com/WeakAuras/WeakAuras2/assets/74884682/91fc9c0d-b3ea-4635-9a9f-e9a938cff21e)

### Export String

```Text
!WA:2!DrvZUTTrq4iOeKcAGIy1uJKEkiO1affWWWaoaTNIOmvSkuKujPRDVuPLKdf3AQDz3DP8p3Io0Ml9Ia6lGo0df9KEck0taHqFc8HEP38tqNDjLBs5bIzMD2z((Mz2Pw7gtAe1i6TF6cAiN5XZfHqT1KCvcx0ptr5mPL4Q(XXsqD8lJ)IF9E43sclepFaNYubTC6574UoKZtJ4xW8UGMbJwTr1jAmKyRJ9OzkbD8yqi)WDfvI)MT6QmWLKlihmx)NrMaYpzwNjt4Pef4ctbmfhdKuvYnY8aJ(abetV01BGt3UZKzqAANiPLDoJQSd4sPixc9WanY1eoR7UOxEmEXLdB10ZFONFtx)frqaA0hrH4yNUdAFs355Sk0zLTnjurNc(L6VMhb)X9UfjniyK0VfPcwF(LBphGSMiocvUeSILmxcPXMItXdWeijkKzkizbIdxySUM(v7uS1AunGeE(ybpNf92hN1qbxQgktiyH7SYsETSNAmA(fZftiOdvc2modMF3Xp)ZKzp6DIqlEkx811QvR(nLw3ak7MN43p7JmgXgnhdfn8uAKkXUjQEBzUOxcrgJVzDz3(7Qq0kZ5)qUurJVcjOGRqY5JgT71VNtXwcKxAFwyCm0aJ6438ksWuzpQTGE9Z(MCsewyipZ3)94(MmT2y7cUi6ubjB2PvcLaykvsdsHrvC(DMiZ2UtVEoUdT7773)1UDE1X(RVl1E0RHNwXOZEV8Op1mh0)e)UD6583RhNYVOTa(XCGfE1G7V)EhCyj70hSs)7iDJf7N1NP103EDqUsXz9NcIuYvl0M7cSXQKpEPwEd1MRvADxPzfoX(QnwsmEUbC2ALeJ)EHKuOUbw(j0WZzGuw3CsxkkVTjB2yvcejbjaDCI6n2PCsuBBjs7DCNKNQOw26r1DkCTCdtjsPwkqHrMP0IleMjunxk(Ga8DBmDSL4YQna)5p97)ZlXnaZ28(E0YiQmdPAh01NSVZn2xZ5tQL94noOhmoIkjyVkkzoHrNyQyVWvQicv7ITk2DfqKGNsyQtpCDuvrDOE3GqcyGJKZ0(ya1U2tiuM5IfdFyXOcsrqXUbXugvM8)nVqXdNw(o9j1(5jpNgz7dsL7)nv6ssZsi1VTCKOTa3yOttGxlxhNEUxyEcCqonAzYNFA7dpA)uprUGY0rfsYAGDUwvuf3pGlaGrlJ1rbjeoBxFHg(0YfPlPSYNUOMLqVBbT(IIV3YgbVYQiYQH09W9(Y9oOX0)6S)n
```

**Comment by nuttin0011** [comment]
i found it when i try to track "Burning Brush" buff aura at "Soulbound Goliath"

**Comment by InfusOnWoW** [comment]
With grouptype unit auras you need to either select the match count or unit count options at the end.
