### ISSUE TITLE
Giving Groups a Memory When Toggling Load Never Off and On

### ISSUE THREAD

**Issue by billybob234** [WeakAuras/WeakAuras2#4865]
![Screenshot 2024-02-08 125552](https://github.com/WeakAuras/WeakAuras2/assets/71467750/7724f554-8340-4103-adb2-fce07c7edcd4)
When selecting Load Never for a large group it would be nice if when I unticked never it then remembered what was already set to never. Rather than what it currently does which is just toggle everything back to load. I then have to go back and recustomize everything that I had set to not load. 
For instance in the screenshot linked I have a lot of things in the Liquid Amidrassil pack disabled. If I set the entire pack to never load and then set it back to load all those settings are lost.

**Comment by InfusOnWoW** [comment]
A specific option just for load is not something we would want to do. You can always reimport the group and only enable the "load" options.
