### ISSUE TITLE
Low FPS in SoD Phase 2

### ISSUE THREAD

**Issue by dhaern** [WeakAuras/WeakAuras2#4866]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

After login in SoD new phase fps is very low (35-40 in Ironforge) when my normal FPS is the max capped at Vsync (120). I only have installed Quazii Classic Era SoD and avoid lava damage aura.

### WeakAuras Version

Alpha 5.10.0-6-g2df204e & Release 5.10.0

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Login in SoD, FPS around 35-40 in Ironforge (my normal FPS in city is the max 120, capped by monitor and vsync).
2. Disable Weakauras and FPS back to 120.
3. No Lua errors.

**Comment by Stanzilla** [comment]
Are you sure there a no Lua errors? Do you have BugSack/Grabber installed? Is the FPS normal if you remove Quazii Classic Era SoD?

**Comment by InfusOnWoW** [comment]
There's hardly any relevant information in your ticket. You didn't check for lua errors, nor did you include your settings.

**Comment by dhaern** [comment]
Looks like this is a "Model" problem (texture or graphic issue?) in Aura, NOT a lua error problem:

![Model](https://github.com/WeakAuras/WeakAuras2/assets/7317522/394dfc00-87e0-4735-92d3-3b460b94d27b)
Model enabled

![NoModel](https://github.com/WeakAuras/WeakAuras2/assets/7317522/70cbfb6d-0de7-469c-a514-ccaf34af2ba0)
Model disabled

116 FPS (capped) to 45 FPS and not a single LUA error lol

I have a big PC, 5950x + 6900xt GPU and every driver updated. This error never happened before phase 2.

**Comment by Stanzilla** [comment]
Models are from Blizzard, you'd need to take it up with them. In any case, ask your aura dev to use a different one in the mean time.

**Comment by dhaern** [comment]
> Models are from Blizzard, you'd need to take it up with them. In any case, ask your aura dev to use a different one in the mean time.

Weird because this problem didnt happen before Phase 2, I dont understand why this problem is happening now just with the update if game client is not very diferent and Aura is not changed/updated... and not lua error related, a graphic or texture issue. I cant play disabling it but happening this now is so random and weird...

**Comment by mrbuds** [comment]
With P2 patch they added some (bad) changes from Retail to Classic, there were report of fps degradation when using models on retail not long ago
