### ISSUE TITLE
Weakaura's disappeared after downloading 2/9 update

### ISSUE THREAD

**Issue by slayde333** [WeakAuras/WeakAuras2#4869]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Installed the most recent WA update, logged in World of Warcraft, all of my WA's are gone.

### WeakAuras Version

5.10.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No errors are present.
```

### Reproduction Steps

1. Downloaded version 5.10.1
2. Logged into Retail WoW
3. No WA's are present

### Last Good Version

The one right before 5.10.1 was working fine

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/159591993/0e6ef83f-59e1-4871-a900-a226c12c1792)

**Comment by InfusOnWoW** [comment]
Did you follow these instructions from the issue template? 
"If you don't see any errors, make sure that error reporting is enabled (/console scriptErrors 1) or install [BugSack](https://www.curseforge.com/wow/addons/bugsack) & [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber), yes both are needed."

**Comment by slayde333** [comment]
Was able to restore from Archive files.
