### ISSUE TITLE
Error for custom text function

### ISSUE THREAD

**Issue by MikeRixWolfe** [WeakAuras/WeakAuras2#487]
**Describe the bug**

When creating an aura with a custom function for a text field (`%c`) calling the `UnitBuff()` function (and possibly others), it does not display text as it did in the previous version (before the prepatch version) and will throw an error when either: clicking on or off of the aura in the auras list, logging back in, or activating the aura. I'm sorry that I cannot give a more specific case of when the error is thrown but the servers just went down again in the middle of my testing.

**Do you have an error log of what happened?**
```
Date: 2018-07-17 20:06:19
ID: 1
Error occured in: Global
Count: 362
Message: [string "--[[ Error in ' New' ]]return function()..."] line 2:
   Usage: UnitBuff("unit", [index][, "filter"])
Debug:
   [string "--[[ Error in ' New' ]]return function()..."]:2:
      [string "--[[ Error in ' New' ]]return function()..."]:1
   [C]: xpcall()
   WeakAuras\RegionTypes\AuraBar.lua:1292: UpdateCustomText()
   WeakAuras\WeakAuras.lua:3544:
      WeakAuras\WeakAuras.lua:3538
Locals:
None
```

**To Reproduce**
1. Create an Icon aura
2. Choose an ability for the class you are logged in and testing under that applies a buff aura to your player character, I am using a hunter's `Bestial Wrath` 
3. Add a Aura trigger for `Bestial Wrath` or whatever buff you are testing with
4. Under the `Display` tab, set `1. Text Settings` to `%c` to enable a custom function
4. Add the following in the Custom Function Box, substituting in the name of the buff you have chosen to test with:
```
function()
    local _, _, _, _, _, _, expirationTime = UnitBuff("player", "Bestial Wrath")
    return string.format("%.1fs", (expirationTime or 0) - GetTime())
end
```
5. Click `Accept` on the Custom Function box
6. Activate Bestial Wrath
7. An error is thrown. If the error is not thrown right away (I've tried these steps a few times) it will either be thrown when activating the skill, relogging in, or clicking on and then away from the test aura in the auras list (left panel) of WA

**Expected behavior**

The expectation is that the aura in question will display with the text generated by the custom function being the remaining duration on a given buff. Instead, no text is displayed, and an error is thrown. 

**Screenshots**

N/A

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes

**Which version of WeakAuras are you using?**

2.6.0

**Was it working in a previous version? If yes, which was the last good one?**

It worked in the latest version released on the Curse client prior to version 2.6.0. I have used an aura with this function for all of legion and it has worked fine up until prepatch.

**Additional context**

Interestingly, if you look at the reference page for the `UnitBuff()` API call, it is overloaded, which is to say that a different version of the function would be called based on number of parameters given or data type of parameters given: 

```
name, rank, icon, count, debuffType, duration, expirationTime, unitCaster, isStealable, 
  nameplateShowPersonal, spellId, canApplyAura, isBossDebuff, nameplateShowAll, timeMod, value1, value2, value3
= UnitBuff("unit", index[, "filter"])
= UnitBuff("unit", "name"[, "rank"[, "filter"]])
```

I am attempting to call the second, `UnitBuff(STRING_PARAM, STRING_PARAM)`. however in the error output above it references the overload `UnitBuff(STRING_PARAM, INT_PARAM)`. Perhaps its not taking into account that an overload exists? Although it clearly says the error is in ` WeakAuras\RegionTypes\AuraBar.lua:1292: UpdateCustomText()` so it may be something more general.

**Comment by emptyrivers** [comment]
The UnitAura api has changed in 8.0, what you are trying to do is no longer supported by blizzard.

**Comment by emptyrivers** [comment]
If you do not wish to change with the times, then methods that mimic the previous behavior of UnitAura are provided to you within WeakAuras, via `WA_GetUnitAura`, `WA_GetUnitBuff`, `WA_GetUnitDebuff`.

**Comment by MikeRixWolfe** [comment]
Thank you for the reply stating the WA provided methods, but say that I did want to get with the times, what is the new way to go about getting buff duration information that is supported by blizzard?

**Comment by emptyrivers** [comment]
This is not a help forum, please use Discord for this kind of question.
