### ISSUE TITLE
Menace Display Issues

### ISSUE THREAD

**Issue by snaccctv** [WeakAuras/WeakAuras2#4876]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

In SoD Warlocks gain Metamorphosis (their tanking form). This has a number of effects including changing certain spells into other spells. One of these is turning Fear into Menace (the Warlocks version of taunt).

I setup a WA to track the cooldown of Menace and everything worked fine at first. Then I noticed that when swapping out of and then back into Metamorphosis form sometimes the Menace icon would disappear. 

I tried messing around with the settings to make sure everything was correct (it was), checked the debug log, and worked with someone in the WA Discord community to troubleshoot. The issue still persisted. 

The strange part is that the WA was show as being loaded properly despite not being so.

After continued troubleshooting in the WA Discord I discovered that in order to rectify the issue I had to select "Exact Spell Match" in the trigger. I have no idea why this is the case.

Please let me know if you need additional information.

### WeakAuras Version

5.10.1

### World of Warcraft Flavor

Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create a Icon to track menace cooldown
2. Set it to load only when Metamorphosis is known
3. Set it to load only if class = Warlock
4. Activate and deactivate metamorphosis

### Screenshots

![visible](https://github.com/WeakAuras/WeakAuras2/assets/156457961/c4b3444e-61e1-4fb5-ad88-9ec3bdffb27e)
![conditions](https://github.com/WeakAuras/WeakAuras2/assets/156457961/6707b90a-50f1-4a47-b039-9008cfdddfe1)
![load](https://github.com/WeakAuras/WeakAuras2/assets/156457961/c48cdbf0-265d-46b2-b1d2-eac9ce7ee386)
![trigger](https://github.com/WeakAuras/WeakAuras2/assets/156457961/d1913134-0ab4-4047-b491-acdb9a346398)

### Export String

```Text
!WA:2!Dr1ZUTTrt8iOVVKaDkwjniPObqjf1ngTWWXajh6nrf5e1kl6ssxN26aPLKJi3yQDz3DPKLB7HQdf5sZb9iiGCRN0lqb0taHqFcYHERx8tqNDfLRt1bXDMD2FZ))vAVQdQgwn81F8mAaN5YZebWhDLLKmvmxyNQOCMSIySD)(sqvAoHfG6pGtzk)gn7410zzaNNeYhXChrtHElwl2mmcIT0G2BIsqJIaH8nBkko(6B4WidazLLzsORagqOmklk2bgcmv6DBuGsTde8ibiL1EOBkKKS17Kz(gBCZ63NE68UnQ76111RUJNvgJQ8ttiJbr6gACJagiObUX8r2SElFpXzs8t9KrKXYlW8abGy64EqZ2TxkasIXNDWa9ox9peMqvUwtVjMJTcLvMfc(y04nofepVz7d27W2wkuWXyr6n1VdoLeOU0RNQvQeKGt6nvEzVmnJvuJQmpKkFvglqrhc7syJtRgKjv8bERUVnpIgK(P9nwWzpuTvLA4pbOYeSAQV)rVSgxGF39Lvawy6gedqfpEFEi87x5CSpccgj5BWUdIXVD(jaKwhdOaLdbrnEQes6B635)FmpLeeCIcINH1mhispE8f3o)ElrrFmzIe8mw4RVvAvfCkMVXeSl(IIPN07AuA(RpxmGGguCWIXzW0lU(bFIm9gxcHg8eU4llvQu53Ts76GYQ(HE2P30OeNz5iu0GJOHQyR6O45R8f9ui0O8xwUAa(BlIOfM7FfwvP9hJjOGRWKZdvA1XUtZ87jW8sBZmJHbMWOm(BArsGZQ3ypb9SAFDgjelmKAEEVxUV2tln6gXfHhjiPtoQ4WQayivs9tGEf58LwYs3OvNonD6Az75zVVtRN9CVLx4Ax6zWDlYOx8E(rFRzC0(qV2T608VwgLWhTNa(HmGfm(G)3oBV7JxLD6lwO)7P6gl2plprlPF9s)mLIZShccCPAMwDBGfPI)G56ZRtTPAHgRlnLwGt2pBTMyJLRdolTqSXE3ascu2ewEX0Gty4oEzZnTP45nmEZcRsGi2pgOrXQ6wjCs4VA2CcsiszV3DXg5jmKSy1sfdxLX3Oq8zQn9LiTsc8wNbzjk6TFBphZt3mVR4O6oTTB8v59QyPh4VnEy2)c2DU6w7BjXkSrVWmQRlk5x3h506tJQiiM9o5tCKkIq1xG8zsseKUrJNx32TMLDBVADSp6(3)(tc5DL6nJ4ffg1vtqSWPERN2fJJoT68SzOnfxg7ymoDNw61Z(Ka446HH2m5XhbKtQJnk5X7dHuYXUA7Kh3bB6BZJIeigjCEAplKovvXVp(rgxzYAszm7Vye2zKEJOU1zC(Gstjm6at7)j509YVx(olaIeCvctd)AldlMomXTqcyniuorBJPOSJLMb38W8ZUw(pM)t5)mEu9F1mtXdgUIR56F(F)aAO)(adZpXPR5iQI9W1S)ijfYcb9oF1m(EcKJu7oF3gonB2zEFTcmgX9UY7MrdNh5p87o8qgSf8kbLPDewljjPXKYZ0rm10W(WnDcIHGtEsELYtgseucU8nJZw7wNHKKmOSiiMWIa08830BsQGJjUAC(NnNYwrAHyvj9wRRTAwJNsLAScJRk9F82pANTFu1H)5l(Nd
```

**Comment by snaccctv** [comment]
Also two additional pieces of information:

1. I disabled "remaining time" on the trigger because it was empty (that had no effect)
2. The "exact spell match" solution that I said fixed it, didn't. 

The "Exact Spell Match" toggle will let you display it until you log out. When I log back in Menace is gone again and I have to drop meta form, uncheck "Exact Spell Match" and then check it again and go back into meta form and it will reappear.

**Comment by mrbuds** [comment]
This aura use "exact spell match" with the wrong spell id
