### ISSUE TITLE
View button doesn't work for most WAs in Loaded/Standby anymore

### ISSUE THREAD

**Issue by romdeau23** [WeakAuras/WeakAuras2#4878]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The "view" button used to toggle all WAs in the given category. Now it skips most of them - probably because of the new "standby" mode. So if I want to see all WAs for the current class & spec I have to individually click view next to each one.

### WeakAuras Version

5.10.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

See video. Most of these WAs have the following load conditions:

- in combat
- not in vehicle
- class and specialization

### Screenshots

[Video.webm](https://github.com/WeakAuras/WeakAuras2/assets/43295566/15a9dce5-4a7b-49d3-a41e-d6c9a2586ed7)

**Comment by InfusOnWoW** [comment]
That's by design, we didn't change the behaviour of the view button. It only toggles the loaded auras, because showing all stand by auras is often not deseriable. The tooltip does state that the button works that way.

**Comment by romdeau23** [comment]
Isn't the majority of WAs typically hidden out of combat? Since you can only manage WAs out of combat, this makes this button pretty much pointless. I understand that it behaves as the tooltip says, but I still think it should be changed or a new button added.

**Comment by InfusOnWoW** [comment]
A button that showed all loaded+standby auras is not good, as many raid/dungeon auras are in the standby state, and showing all of them is useless too.

That's one of the drawbacks of the new loaded/standby vs non-loaded categorgies we have introduced. But that doesn't make it bugged in anyway.
