### ISSUE TITLE
Not load at all (Version: 5.10.1-5-g655818c)

### ISSUE THREAD

**Issue by Darkion43** [WeakAuras/WeakAuras2#4879]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

when i update to 5.10.1-5-g655818c from curseforge app, and login i got total 44 errors, and the addon not load at all, ( /wa not work)

the last one of the errors is: WeakAuras/Init.lua:1 WeakAuras/Init.lua:381: unexpected symbol near ']'
so i change the line 381

from
--@end-experimental]=====]]=====]

to
--@end-experimental]=====]--]=====]

or 
--@end-experimental]=====]

is load normal without errors.

**( im not a programer, i dont know lua, i just know 1-2 thinks and i try to find out what happent, and I like to experiment and see the result. sorry and thank you ! )**

### WeakAuras Version

5.10.1-5-g655818c

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
8x WeakAuras/Init.lua:1 WeakAuras/Init.lua:381: unexpected symbol near ']'
```

### Reproduction Steps

1. update to 5.10.1-5-g655818c from curseforge app
2. load any character with only weakauras
3. same error

### Screenshots

![v51](https://github.com/WeakAuras/WeakAuras2/assets/117835316/73894d46-591b-4e41-a5bd-9cb0fa4985c7)

**Comment by InfusOnWoW** [comment]
That should be fixed in the next alpha build
