### ISSUE TITLE
New trigger: Update every <user defined>

### ISSUE THREAD

**Issue by Grimonja** [WeakAuras/WeakAuras2#488]
**Is your feature request related to a problem? Please describe.**
Add a trigger that would execute every (user defined) period

**Describe alternatives you've considered**
Well at the moment people(me including) just do Every Frame then manually compare times. WA solution would be alot cleaner.

**Comment by InfusOnWoW** [comment]
That feels like a too niche case to include as a default option. After all this doesn't take much code, and is only useful in rare cases.

**Comment by Grimonja** [comment]
I think it only looks on the surface as a niche idea. If you look at WAs people use many off them have every frame in them. Yes, its not needed in 99% of cases. But if they had options of "Every frame" and "Every x" they might actually think about it.

**Comment by InfusOnWoW** [comment]
The actual right choice is using the right events. Having a "Every x" is just a the same crutch as "Every frame", so I don't think that argument is good. We have discussed this for a bit, and believe that this is too niche and wouldn't be used too often.
