### ISSUE TITLE
Abilitie to change tooltip color

### ISSUE THREAD

**Issue by N6REJ** [WeakAuras/WeakAuras2#4884]
**Is your feature request related to a problem? Please describe.**
I'm slightly red & green color blind and the dark/bright red in tooltips is impossible for me to read.  All I see is a bright red blur.  The color blind options in wow do not help.  They only make things worse.

**Describe the solution you'd like**
I'd like to have some method ( hex, slider, name ) to change the color of the tooltips to make them easier to see for people with color disabilities

**Describe alternatives you've considered**
idk.

**Additional context**
When the text is large like this image shows I can read it though its slightly blurry
![image](https://github.com/WeakAuras/WeakAuras2/assets/1850089/7047b0be-a4f6-4e7c-a9cb-959ad9649cd4)

**Comment by mrbuds** [comment]
I think you need a more generalist tool to fix this across all apps on your computer, i don't think it's realistic to ask for each of the app you use to change their options.

Maybe this would help with your issue? https://www.ryobi.co.jp/products/visolve/en/

**Comment by InfusOnWoW** [comment]
Well we could simply switch the color, red is argueably the wrong color anyway, the standard for emphasized text in wow is yellow.

**Comment by phoenix7700** [comment]
If you do decide to change the text color I suggest maybe using an outline or shadow to help with the contrast.

**Comment by N6REJ** [comment]
> Well we could simply switch the color, red is argueably the wrong color anyway, the standard for emphasized text in wow is yellow.

That would be wonderful.  @mrbuds suggestion was blocked due to trojan.  Nor do I really want it affecting all apps on my pc since I work with a graphic designer and am a photographer so having it fool me on all things would be bad.

**Comment by InfusOnWoW** [comment]
Note that while I fixed that issue, we use red in many different places and while we can tweak colors, accessibility is not exactly a priority.

**Comment by N6REJ** [comment]
> Note that while I fixed that issue, we use red in many different places and while we can tweak colors, accessibility is not exactly a priority.

I can understand that.  If you could please put it on a this century to-do list that would be a blessing.  ty.
