### ISSUE TITLE
The Custom Option "Media: Sound" can cause the options to become sluggish.

### ISSUE THREAD

**Issue by hambold** [WeakAuras/WeakAuras2#4885]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello,

I noticed that using one or more Media:Sound options in the Custom Options causes short freezes whenever anything is changed in that menu. The duration of the freeze depends on how many Media:Sound options are used and how many custom sound effects are available.
It's not a big deal since it's only relevant while changing options, but it's odd that the other Media options don't seem to cause this.

Here's a comparison of 7 Sound options vs 60 Font options. I had no other WeakAuras installed and had Causese's SoundPack and BigWigs loaded to make it more representative. It still happens with only WeakAuras loaded tho, but it's less pronounced since the amount of available custom sounds has an impact on the duration of the freeze.

https://github.com/WeakAuras/WeakAuras2/assets/104383249/d5a1ee0f-b68d-4bfb-bed1-14ce428c9995

https://github.com/WeakAuras/WeakAuras2/assets/104383249/c5fc2943-5260-4aa3-bd0d-7a370ecc9eb2

### WeakAuras Version

Weakauras 5.10.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

- Create any new WeakAura.
- Populate the Custom Options with a bunch of Media:Sound options as well as a toggle option for easy testing.
- Clicking the toggle or changing any other options for this WeakAura should cause a freeze.
- The duration of the freeze increases with the amount of Media:Sound options used and how many custom sound effects are loaded. 

### Export String

```Text
!WA:2!nsv3Unory0nkxGKfAPeuJ4VlIkIfKaQOP0YcCvCWrTO0MuB3nfuqMXEghpuNzgnZ40M9YOva3Wn9rixI4Q8iSpbJQ4jyFe6taFtC2QUR2i1Cr88n(89ZCoNXv6uBCnCn8F9zsEHoNYiYENg29WJ9Kx2lnvr0veFbMQe5OPHKl1rPC5yKosePPJjr4Pm0yAsKotsuz8C80Rvzim)IFUm5p(blqSKmUSpNY0XT9oo0Zx0y9fSmQIyJKcLMp2I4ubgPj(KjeM(fOcyxKMMmGI1zUTGqjkrt5m1((knsQDItPmQkZXfEODMPL0rJis1dFKC1Y)yoMexKMgovqKh41TFNt76QHaFuHe1CMsqYZpeRCEHQiEzBda00lxe1Uvqyuqyl)q3cO4X2dbr6dCar5yCIpGGY1z3MwFjbsZpOVx3UxvWw1EhX7AN4jKWY4J4yY)(aXwRNugZXrsGd(nXJwpOCYiuY0O0CoxMDLIKNwY5U9cd7DKBkNPfB0rsFAJtkqyOCOgHHZHr1NmYsFFyDZMxdHXOKZhbMbg2nNJWDI1OC4Su3FCrUM64cStsDZx64NKJuk7kxf9Pe7Iz2MeabFWkxWzLUGQZLl7HLWD1WOhNWzP0r1J5cR0LDfIrTQkNTV5HDEobPibAjHnsN9wMnDzCg5AmOnwerwLsQiqjWQzwO2YAES7yeL1X8TqcMhB(oZ3B(b457867i(K1tHcjjHQGEuv8rVruLl8TGXZTdaDPZd4cEox(tvHFYFhmU00PUD96eoxZtMadla69R8NJ3IIfVxqo)IgTx6UB0B5Xxn7cUepqIeZgSAXIuj4PaoaKPQ3uEfQJDl7znoOTVN3XYPRUG2SGIxS7KW96YJd9o(ZVgUKa4xv8)j1SzSMpAuorwOi)irLK18CYuZEsmjfbIAMR1apReFJD8VWE1Q6KRGdjfzBOVYAhmB6VChZjYszRP5mXUhY0ezkkHmSfg3JPgoGGoVfOvQHhzrpmWMRAylQ8aUKTnmiM(zMGx2UMMtRoX8eZaqKoZCYZxv6eUy6(Wg)YsW38sWn(QgTH38Q5i24Ujz)72ef1FTmFJf4UnDVBZ18RRh13CVqT79cvZ7fQDwlQf3b1RcAXDmXB9PIfLxkBV0RwPsLQZHVorWl)s6ZE7fuwP9gQLZnuRSYq5pP09(31uX7T9oF927uBY)D2))d
```

**Comment by InfusOnWoW** [comment]
The reason for that is that all the dropdowns fill the popup with all items that can be shown, so a lot of widgets get created. And the items in the Sound Drop Down are probably heavier than the font drop down.

I briefly looked at whether that can be easily be made lazy but I don't think we can, since the code is in AceGUI. I'm leaving this open, in case rivers wants to take a look at it, too. But imho that's a "can't fix" in an reasonable amount of work.

**Comment by InfusOnWoW** [comment]
@emptyrivers That is in AceGUIWidget-DropDown.lua, in the AddListItem function, disabling the item creation fixes the slowness.
