### ISSUE TITLE
Weapon Enchantment/Imbue Trigger Inconsistent Firing

### ISSUE THREAD

**Issue by matthewPapageorge** [WeakAuras/WeakAuras2#4891]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Weapon enchantments are not firing consistently.  My use case is tracking the weapon imbues on my enhancement shaman. When the main-hand is missing a weapon enchantment or has 30 seconds remaining on the imbue, I want the icon to display. When its enchanted with more than 30 seconds remaining, I want it hidden. While it works, it requires me to reimbue the weapon several times for the icon to be hidden. 

### WeakAuras Version

WeakAuras Version 5.10.1

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Click create new aura
2. Create Icon
3. Add both triggers
4. Apply Imbue on main-hand weapon

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/38256981/8017656d-3d0b-4923-ad94-77de8f6faea0)
![1](https://github.com/WeakAuras/WeakAuras2/assets/38256981/46e70629-6e6f-4e1d-ab8d-226912931a8b)
![2](https://github.com/WeakAuras/WeakAuras2/assets/38256981/019ec25f-6c47-4dc6-bb90-e6b1adac3a54)

### Export String

```Text
!WA:2!1v1tZnTruCuDzkJPTdXHsHH(NqAGz6mTmbycTLsBXYytsQJTrwHaxWAL0ARLiVR6Qv2XCdFkxAp4pc(Cp5pc(tWB80pb5qV1l5qp33kzhGoeFq(9E7B)T)23)wJkf6wWVG)HRnM5j4nfjsp6NDMzKevGqwpsXe848Yb1B3oMQ28b79h37m4VjeUhUEdbJRClvUMDzRzEcrOVOpVzFwe1z6c1Y(DObMAWDgQKSoDOY4NFd5CXdxAitr7wJ0LAeTusmTvhkNkzEnde9RZDM9wQhfN(xP5qpr7pfzcHRCgRv6tjr4bn2N6M0UT9GiQCZYvBuz3QMkuXuFwhfN4s7r5QMOlSdM0QuXM2TAAx0YofJSZWzQwEb3CS44348dJJOHHB5hN)euAiPikwnBuUAv3S9ol7VDyXXmEhRu3oAVuQTs5m6AMWzk3OqYaQ0nJ1MDjm(Oe(8it(Ba5)xyz4IWsqb4dDGp1jQGKQDcbTLaVAeLqw4(WxcRaxdwfUSZOtwF17SoCbh4JGpg(8Pz0PONI1JotFToXnh48gWxbRbxp)eFw8ls4PoDBcFq0sKuz7m6SJWN(NN5ymFtLCs4tWSiwA87hVpLgveJkEklcwSemkMg2oTUaolMgIjQeKN0GXy8YI2rxoT9LGLNHQUeV97ifjC)dVAubf9afg7jyI9PzvBgrxj1y6N2czxc6WCbtUGthDYYRE9O3HZrZfSuSUu)JYoHf0ZS4U21Jwo1iwTlq)yE7X8vbMfr1JZaIDa1p14RIw7DGVg4wH0oeVbTAhkeYGPPo8IKyfR9ameifk86BJgnRvVw5ORDAOejPEmDmn3SSMRfrbyzjgS07i6cVrqQKiui32WWi34uREP65WFJMJoh3qfj7LR84eIpMeiRyBh9fN25NPz8wjINnNczxQEi9CdPoZs16lK(7jjrd3BUWSto20(U67AxDl8cNX53yEXOTQvRSvl76nIw50itxHFlDzJZC6KT95058V(KAYEj9QrF9PbJ)aSTL51sfiPytqO)GzVfsg)9SoHI(vK0FlbNJmOX7V(nV9gzbC9ct1FEOUawNxgQ103TzUjkLGxVhvInWJ1MRs5DubFYeT8cWhPvkDsArpq5rlSeK65IuCklSdyE7ZPXX5s3ytpsinNPw0j1qvgU4sPNMjgYPYGdVcChd4URUZMW3bFp8dW9GFeUp8tVc(5a4xGZcpakcM5WHipekzavsPb8iytOCAHdSTbudQdvHDGF1bAmnlZyw32U(oWwgGLdyFfy3bWtmCdOSobQhBgki(pzKEkchhSjdCvip5Qlz1njuXYB5fsIJVeSFEt9uHmbmlPfglthaOdHW5UDcZFspv1T23C9NTD9NoIWzDtd031kwrKQktPKyAtLmn0(b4TyJz(ZZfT0tZLXu8vf)4HA)sbDdyTkGk1vib6b9HnCBJd6Id()MNW4zLkiy5hRHHn)Po9upu4UqCE4G8M4Uv5JU4IxZ0nYpKftW(a)a5blEwS9ZNPFwCSs41lBY45(M)zvM)X7GZz)2njC)v2QRBc161DPwKWOasoR(6PlpoQagrx8UgoR1sx87I8QnRtEjJRrLgCCw1Bfj(yK(c72SKv5Y1M0wBaJuypEo9CC97kBHB(YV3YwdxqDhZxkeDnke7UXnV1638wf69xp9)(d
```

**Comment by InfusOnWoW** [comment]
You have enabled the "Weapon Enchant" check in trigger 1, without inputting any string.
