### ISSUE TITLE
Latest version doesn't load

### ISSUE THREAD

**Issue by fotoman-62** [WeakAuras/WeakAuras2#4896]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Latest version installed using Curseforge app, would not load. Tried Reinstalling and nothing, It appears in list of addons, but doesn't actually run. Went back to previous version and it loaded fine.

### WeakAuras Version

5.11

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

just install with curseforge

### Last Good Version

5.10.1

**Comment by InfusOnWoW** [comment]
That's not the latest version.

**Comment by Stanzilla** [comment]
We had a bug in 5.11.0 and just released 5.11.1 to fix it, sorry for the inconvenience!

**Comment by Kiinoh** [comment]
Why is this closed when it doesnt work? I have the latest version updated 10 minutes ago and it does not open as the original poster described

**Comment by SpatenLa** [comment]
by the reasons stanzilla said. it is fixed. you dont have the latest version.
