### ISSUE TITLE
Can't select color in weakauras

### ISSUE THREAD

**Issue by ragingdruid2** [WeakAuras/WeakAuras2#4903]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Not sure if it's an issue on my end but for some reason every time I try to pick a different color of any kind of object doesn't matter if it's text or texture it doesn't let me select a color it just stays on it's default one

### WeakAuras Version

Weakauras 5.5.0

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Create a text - try to select color in the color picker

**Comment by emptyrivers** [comment]
5.5.0 is about 10 months old, consider updating to the latest version. If that doesn't help, then try disabling other addons - bagnon is known to cause this.
