### ISSUE TITLE
Hide Tooltip Information

### ISSUE THREAD

**Issue by DaleHuntGB** [WeakAuras/WeakAuras2#4909]
**Describe the solution you'd like**
A simple toggle, such as `Lock Positions` & `Magnetically Align` that can hide the tooltip information when hovering over certain fields. This is super minor, but it would just be nicer to navigate and see what is being typed. Even possibly being able to anchor the tooltip elsewhere might be nicer but that is more complicated, I'd imagine.

**Additional context**
[Screenshot](https://i.imgur.com/DZRj4Ck.png)

**Comment by InfusOnWoW** [comment]
The underlying issue is already tracked in https://github.com/WeakAuras/WeakAuras2/issues/2824. If we fix that, I don't see any good reason to add the requested toogle for tooltip information.
