### ISSUE TITLE
(request) UNIT_SPELLCAST events would be a good addition to weakauras

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#491]
**Is your feature request related to a problem? Please describe.**
There's currently no neat way to hide a cast without using custom code except for status -> cast but that only allows spell name and doesn't work well for nameplate units.

**Describe the solution you'd like**
Event -> UNIT_SPELLCAST
new args are unit, castGUID, spellID

Message Suffix: START, SUCCEEDED... and so on 

It should be a TSU so that selecting UNIT_SPELLCAST_START offers the option to hide the weakaura (via castGUID) by checking "Hide on interrupt" or whatever.

**Comment by emptyrivers** [comment]
Why does this specifically need to be a prototype? You can write a custom trigger just fine for this.

**Comment by InfusOnWoW** [comment]
I don't quite understand what you want here? Can you describe a use case for it?

**Comment by Causese** [comment]
soo yeah we agreed on spellID being useful for status -> cast trigger
(just in case you guys forget about it)

**Comment by InfusOnWoW** [comment]
Which is part of the next release.
