### ISSUE TITLE
Weakaura didn´t start

### ISSUE THREAD

**Issue by Buggyman84** [WeakAuras/WeakAuras2#4911]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello,
I have the Addon Weakaura and he is activated but i can´t start that with /wa or /weakauras but some Weakaura that are inside is activ but not correct.
Please help me fast for use back that Addon so i have to need it

### WeakAuras Version

Weakauras 10.2.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
Message: Interface/AddOns/WeakAuras/WeakAuras.lua:1282: script ran too long
Time: Sat Mar 16 17:21:51 2024
Count: 1
Stack: Interface/AddOns/WeakAuras/WeakAuras.lua:1282: script ran too long
```

### Reproduction Steps

i tested all about only with weakaura and than he going

### Last Good Version

WeakAuras 10.2.5

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/163669398/26aa7f30-3ab8-488a-830d-8a2f3c30338c)

### Export String

```Text
Message: Interface/AddOns/WeakAuras/WeakAuras.lua:1282: script ran too long
Time: Sat Mar 16 17:21:51 2024
Count: 1
Stack: Interface/AddOns/WeakAuras/WeakAuras.lua:1282: script ran too long
```

**Comment by emptyrivers** [comment]
10.2.5 is the game version, not the addon version. We need the addon version to be of any help. Your saved variables would also probably be useful.

**Comment by mrbuds** [comment]
Also you ticked the checkbox for "Tested with only WeakAuras" but the screenshot show other addons running

**Comment by Buggyman84** [comment]
Version 5.11.3

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Buggyman84** [comment]
i have all addons up today but it doesn´t work i delete some addons and the same no weakaura start

**Comment by InfusOnWoW** [comment]
Can you attach youf full settings? Both the WeakAuras.lua and WeakAurasOptions.lua file

**Comment by Buggyman84** [comment]
what do you want correct about from me?? i can´t send you the .lua files

**Comment by mrbuds** [comment]
> what do you want correct about from me?? i can´t send you the .lua files

For upload on github it needs to be a zip file, it is explained when creating the ticket

![image](https://github.com/WeakAuras/WeakAuras2/assets/189656/132f9fdc-fc86-4c0d-a502-adddc4997ea4)

**Comment by Buggyman84** [comment]
[WeakAurasOptions.zip](https://github.com/WeakAuras/WeakAuras2/files/14625731/WeakAurasOptions.zip)
you mean here??

**Comment by mrbuds** [comment]
Your WeakAuras.lua file size is 39.5mo, this is the largest such file i have ever seen so far

**Comment by Buggyman84** [comment]
ok, but since wednesday i have that problem and there was these weakaura all inside

**Comment by mrbuds** [comment]
Try disable all addons except weakauras (as asked when making ticket), then if it work enable then until you find which one is the causing this

**Comment by Buggyman84** [comment]
i did it but some weakaura didn´t work so Raid Ability Timeline it doesn´t work and this is one of some weakauren they didn´t work

**Comment by emptyrivers** [comment]
So the problem here is you have too many auras installed. I took the liberty of deleting some crap from previous seasons in DF, and was able to cut the # of installed auras by about a third. Try replacing your savedvariables with this:

[WeakAuras-minus-a-third.zip](https://github.com/WeakAuras/WeakAuras2/files/14627091/WeakAuras-minus-a-third.zip)

I can make no guarantees of accuracy, so i strongly recommend you set aside some time soon to go thru your installed auras, and delete crap you never use, or is very old (there's a stagger bar from WoD in there!). Additionally, try to remember to do the same each season - no reason to have a Court of Stars WA when that's not in they mythic+ rotation anymore, eh?
