### ISSUE TITLE
Bad link chat

### ISSUE THREAD

**Issue by Merecy** [WeakAuras/WeakAuras2#4918]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello,

I use an addon to click and open internet web called Click Links (https://www.curseforge.com/wow/addons/clicklinks)

Now that weakaura also give the wago link when you link in the chat a weakaura it's doing some weird shit

With addon :
![Capture d'écran 2024-03-18 222453](https://github.com/WeakAuras/WeakAuras2/assets/106228694/475880cd-c7dd-487e-ae1a-494349d81a2c)

Without addon : 
![Capture d'écran 2024-03-18 223307](https://github.com/WeakAuras/WeakAuras2/assets/106228694/3704474d-80b9-4b38-8943-90955755b715)

------------------------------------

That gonna be a full guess, but if you add a clear separation (like a |) between the weakaura and link it should be solved
Something like :
[Mereci-Hyjal - Important weakaura] | https://wago.io/xxxxxxxx

### WeakAuras Version

5.11.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No lua error
```

### Reproduction Steps

1. Install Weakaura and Click Links
2. Link a weakaura in chat
3. Try to download by the chat
4. Error

**Comment by mrbuds** [comment]
This should be reported at https://legacy.curseforge.com/wow/addons/clicklinks/issues
