### ISSUE TITLE
WeakAuras Bug

### ISSUE THREAD

**Issue by CWS12** [WeakAuras/WeakAuras2#4920]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

WeakAuras will not open and I am getting a bug, I try and open the addon via the minimap indicator and via /wa but nothing happens.

### WeakAuras Version

WeakAuras 5.11.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
4x Usage: local result = C_Item.IsEquippedItem(itemInfo)
[string "=[C]"]: in function `IsEquippedItem'
[string "return function(event, combat, alive, encounter, warmode, petbattle, vehicle, vehicleUi, dragonriding, class_and_spec, player, realm, race, faction, level, effectiveLevel, role, spec_position, ingroup, groupSize, group_leader, zone, zoneId, zonegroupId, instanceId, minimapZoneText, encounterid, size, difficulty, instance_type, affixes)"]:2: in function `loadFunc'
[string "@WeakAuras/WeakAuras.lua"]:1746: in function <WeakAuras/WeakAuras.lua:1620>
[string "@WeakAuras/WeakAuras.lua"]:1970: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1252: in function <WeakAuras/WeakAuras.lua:1211>

[string "@WeakAuras/WeakAuras.lua"]:1369: in function <WeakAuras/WeakAuras.lua:1317>
```

### Reproduction Steps

?

**Comment by InfusOnWoW** [comment]
Please add your settings.

**Comment by diclementedan** [comment]
Facing the same issue since the release of 10.2.6 today

**Comment by CWS12** [comment]
deleted all my auras and it appears to let me run the addon. going to re download some and see

**Comment by Variesh** [comment]
Mine was as well, it seems to have come back on its own though. All I've done is update Guild Roster Manager(GRM) and /reload

**Comment by InfusOnWoW** [comment]
If none of you add any additional information, don't comment.

**Comment by mrbuds** [comment]
This is fixed for next release, please be patient

**Comment by CWS12** [comment]
just had to redownload, all appears to be working now

**Comment by CWS12** [comment]
deleted all auras, redownloaded
