### ISSUE TITLE
gcd swipe colors are inverted

### ISSUE THREAD

**Issue by NathanDunahoo** [WeakAuras/WeakAuras2#4924]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Since 10.2.6 update all gcd swipe colors are inverted

### WeakAuras Version

5.12.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Use any weakaura that triggers a GCD

**Comment by emptyrivers** [comment]
This looks to be the same issue as #4923, so I'm closing this as a duplicate. Feel free to watch that ticket for a resolution.

**Comment by Nytsua90** [comment]
Possibly related to changes in `WeakAuras/RegionTypes/Icon.lua`.
`UpdateEffectiveInverse()` might be getting called multiple times when Inverse is checked in the Swipe Overlay Settings, which results in the inverse never being possible.
I was able to resolve this issue locally by removing one of the function calls inside the `UpdateTime()` function on line 586: `region:UpdateEffectiveInverse()`. 
Not versed in the impact of the recent changes to progress handling so I'm not sure on the scope of this change.

**Comment by InfusOnWoW** [comment]
This should be fixed with 5.12.1
