### ISSUE TITLE
WA isnt loading 

### ISSUE THREAD

**Issue by Jinzopz** [WeakAuras/WeakAuras2#4926]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Everything fine when I logged in today. I updated everything in curse forge and everything broke. 

### WeakAuras Version

5.12

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

I don't know what I did besides update it to the latest version and everything broke. 

### Last Good Version

5.11.3

### Export String

```Text
https://pastebin.com/GitFgWGQ. Wont me upload the zip
```

**Comment by emptyrivers** [comment]
Your saved variables would be useful to figure this one out, thanks!

**Comment by Jinzopz** [comment]
[Blizzard_Console.lua.bak.zip](https://github.com/WeakAuras/WeakAuras2/files/14662165/Blizzard_Console.lua.bak.zip)

**Comment by InfusOnWoW** [comment]
That are not the weakauras settings, we need the file at WTF\Account\<Account #>\SavedVariables\WeakAuras.lua

**Comment by Jinzopz** [comment]
The update was release fixed the issue I was having.
