### ISSUE TITLE
Inverse option on swipe overlay no longer has any effect

### ISSUE THREAD

**Issue by jtsorlinis** [WeakAuras/WeakAuras2#4929]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Creating any icon weakaura and then toggling the "Inverse" option under Swipe Overlay Settings has stopped functioning since the latest update.

### WeakAuras Version

WeakAuras 5.12.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Create New Aura (Icon)
2. Can use premade auras for any buff/cooldown
3. Inverse option will already be ticked if a cooldown
4. Whether the inverse option is ticked or not has no effect, visually the icon appears as if inverse was not ticked

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/17734528/1696cd3a-4b57-46d7-b1bb-ddb363e9a780)
![image](https://github.com/WeakAuras/WeakAuras2/assets/17734528/2d9cb09e-a5e5-45f9-b49c-a23663177648)

**Comment by InfusOnWoW** [comment]
Duplicate.

**Comment by jtsorlinis** [comment]
Do you mind linking what it's a duplicate of? I didn't see anything similar in existing open/closed issues

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/issues/4924
