### ISSUE TITLE
Sharing auras via communites

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#493]
Leaving aside the fact that communities are disabled at the moment that I'm writing this, and that it may not even be possible depending on exactly what API methods are available, is this something that we want to support?

**Comment by emptyrivers** [comment]
My first instinct is yes, since they're basically like cross-realm guilds. But then, they're much more public than guilds are, which could be open to abuse.

**Comment by InfusOnWoW** [comment]
There's no SendAddonMessage for communities as far as I know. This has been reported to TheDanW, who didn't seem to care.

**Comment by InfusOnWoW** [comment]
can we expect SendAddonMessage-like functions for community channels in the future? im doing something pretty terrible right now, a text protocol visible in the channel

TheDanW: 
wouldn't count on it, communities aren't intended for mass broadcasts of addon data

**Comment by emptyrivers** [comment]
URL pasting it is then.

**Comment by InfusOnWoW** [comment]
Someone needs to test whether cross-realm whispering SendAddonMessage works now, if so we could built on top of that. But I doubt that they fixed that.
