### ISSUE TITLE
Custom Anchor Bug Since 10.2.6

### ISSUE THREAD

**Issue by husskhash** [WeakAuras/WeakAuras2#4930]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hi, I have a few weakauras that have a custom anchor below. Reason I use it is I sometimes for various reasons switch between ElvUI/SUF/Blizz and it allows these weakauras to essentially take the same position on my player frame relatively.

Since the patch, when I login, these weakauras aren't anchored to anything. When I open Weakaura menu and click them, and then close the menu, they anchor back properly. But when I reload it happens again.

function()
    if ElvUF_Player then
        return ElvUF_Player
    elseif SUFUnitplayer then
        return SUFUnitplayer
    elseif PlayerFrame then
        return PlayerFrame
    end
end

I also noticed this issue is happening for my weakauras that are Dynamic groups, as standalone Weakauras not within a group that have the same custom anchor don't have this issue.

### WeakAuras Version

Weakauras 5.12.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

Create a group weakaura with the above cusotm anchor (anchoring to the respective frame). Reload and check

### Last Good Version

Weakauras 5.11.3.8

**Comment by mrbuds** [comment]
WeakAuras is not an optional dependency of Elvui or SUF, so there is no reason for WeakAuras to load before them

Your custom anchor function assume Elvui or SUF is already loaded, which is not true when the function run, the function return PlayerFrame, so weakauras anchor to PlayerFrame, then Elvui load and hide PlayerFrame

I tested to create a group with your anchor function with SUF on previous version, and as i expected it doesn't work.

**Comment by mrbuds** [comment]
I'll add that next WeakAuras release will probably fix your problem, but if it work on your computer it's only luck because it probably load a ton of auras and loading is slow enough to let other addons to finish their setup.
