### ISSUE TITLE
Border around Dynamic Group misbehaving since 5.11.3-11-g9ac1daa

### ISSUE THREAD

**Issue by Surarn** [WeakAuras/WeakAuras2#4933]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Noticed behavior yesterday(EU so before patch).

Border around a dynamic group misaligns in either x or y direction (heavily). Changing any setting under the the Group tab fixes the behavior while /wa is open but after closing its back misbehaving.

During live play the border and background doesnt include the first instance of the wa vertically and is offset by some x value horizontally.

EDIT: Cant try earlier versions of weakauras, i get "Notice that weakauras have been downgraded, want to run experimental repair tool?" when im trying to go back to older version, the version in the title is incorrect though, i could go back to that version and the problem was present there. The "Last good version" below is the first version of weakauras i cant go back to test.

https://imgur.com/nEYzQrq
https://imgur.com/7tB1Vo1

### WeakAuras Version

WeakAuras 5.12.0-1-g2ab4v79

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Import https://wago.io/loNlRKhcV
2. Open up /wa
3. Select "Better Loot Window"
4. (Optional) Change anything under the Group Tab to see it snap to proper position

### Last Good Version

WeakAuras 5.11.3-4-gd0ff7be

### Screenshots

https://imgur.com/nEYzQrq
https://imgur.com/7tB1Vo1

### Export String

```Text
!WA:2!LQZwSTXv2zAwVgGz3ulfBNeVjRNWSYrkrwHVePelCWksrgZykrLHuYoRJl1qoxYzIgoZ47musmXPfriyB(QlQqrb2I9Jcb0(v)PQOVqFGwHUTDB3U7fcBlCrlqb8h9)6p6(z75CVZm8PsDrjSPUZ9EoN7595CVddT10o2tT4cXtSqSBg)MTtO0ivJmlpDNPvNw9lw8qfAZYeZ2UAF(vFsdlQkHMtP5oQulB7lLZq)J)yfQQunlldxDBAVkTA5qCV93sB7ZFo4ZXkMn1SOByPB62iFH1Rvq(ybrYBzyrFVqHcf(aQ1EvTvAscNOl1W(L1CDTDY(2V9EkTTwq36TnSw3q(oAn3IQ00v3Y0jTSJRc1nsJw6M6oArYb)XnYbUu92TjuNRDdQ3WVZrQKgDB1QwpBc92fkVrXnlNZfEqwPlvjXbo2edJsQorEIt3gKDjMUvbO13)465xPAT6vRTICTCDbI3W2qPhHga2gucaMC1nkuUSmFMg3MOy4QjBQ0H4e5WUMESqKJBAz0TJPqaBqvu17685F1dvm17OGstA2xR4jefhsvxkxnFr2LZzAzsovf4reI6ihtDinTmvDoabfLh2m56OOBwK9nbeyZWUb7nyZc)95hDgzfd92MSlEClkWBWUO4QeoNkXP5txtrLi1OxwPQWwrnbdHlFhdDeiOYK2OYoYtbthHAQySfWeWmF3tv66c20k2CJrKCgwkQfB4QyaQHRk3Pl4iejhOABEvwQiYnnuCCWr5C0)yco4qhIrlUhrIAv240gEEtboeBeo2clEuRUgg51PnniBtfklY2h2MA11UeOiEPN)FBvzNMWEg(OMeKbrDs0YYneExBFK4VfubBqCPn03NyCeLlriGNO2dmu6n50Zd0Qa7Dbzd9o6UpNNpAjtWxg8k1vpE38Z(Ugj(OTsBEVdDCj2Ry22GCD7Pe(3frv7gkGb0D7NaSh4FA6weCxTOnKxz1sBwfSc2AkHprqyruYfY5yrDzZCKRvZDfk3xk0VIzuDv7PZrCbHsQSLLR0D1nvT27G2uDvUukV6H447QR6Q9CpDaoaxTr18YfkSEoq02l3QvU76na(PLE7i099In)lT)3)V)wN7CHoORdPmkUAYoO35foc9W0fw1J1nBzrfUOrOG8GoZHMU51(I35iaA6o8D)kNWhli89cDm)PBRRQsmLxVWwfKzX)nlEqlliWc0Un6qaV)oSlFm69r15oq5Cj77AFTA6DisWokzasSHUJRKRLKJM1EzL3d3Pn(5ITqMf)DyxUHz3oniukW8Rcuz7eDu2))mhAscZ0rOsUyIo6MHZHrI5qYck8wkGx51tSdPxoxyg282VwWgQ7s6W3mxLEswMbmWwWEPrGie(EToqnnw7ZtnTwJqBdJ1dxecZAXuzewB7ze5iLSAXjicUudcqFckfuxIPUz7Sahgo(cjaXG9rSD2MzqyDcyBMzyMvdbDao8QRPSVKXquffjgTHys2dV1wSD1as1f4l2Eih9FGbUEbMVjSlY6M2DDXDspmqYcvmn6jbsJkxYHbuj7UuBlhY8sQwehjtlxnGrLAAbzg2t3HSGuEftqsaoPLRePJTBp2dp)H8OCdDtqpyDyjudIsm7tUcJEGV8Fi6FXzvTFdGl)u2oAO8hBHumlkhNsRcsdcom4xwdX(HNNDG2XA6QezIiqgW6iuURA1LczqbzIh0cc0Xa9HKggk2oaBaYVL9u5mGSjO1derClCoOPpehYdTfPofjsQXReqPk9y0dBGywgWKL5kdAyFdzshRDjsvVDL7wVCLk1QxRcuCqQf1QJ0kgeQlp0ZZ0MAxWRX1QnKCa0eOReenqeI9IShUnZkhFcWImV99kQtb(SRn41rjnj67IQ(wqaDpUxO0SLlkpVudlZUosuqoCMhmmMUqAFiBHKH(oejBIRudfxxdWpRRTTHoXzUfYPdGT9r43c12RCo2fcX(kSlY(2HoTjuRgYNywDpDBY2NYJzL9Z8Bp1qpVg4hKBLnRv5eFSWmQASVku2kc7N)ghQAvVzxhxRoB3q839pFMBEtPbTdOb2rstzxmIGykHQtvmIlphbj)cjaALAj1ZQRutnfZ2imAej02J()4ySQTqXd00ejbp4vVJeapT3RfP)he06eZDxOHIPjqQBj9jFAKiOxF953vs3us3wrN6mBaCISKle4gmheqerc(O3sAxG(Qs7UGWvL)GRLip0S(ZoN0V0TKm1nqg1KJi(XvbIwxqhQJqDNDeEA(jqeyoAxYCC8jMQrW)hb4GrztFpl(UnOB4MMyvoqVtlGTLmB0r8BJohNU5SCCYHCbDCmkSE(kBIDQjqtUq(cL2QWQrNRVsTtpE6ZBnkFD)Oy61Opqc0ZXJ1hEV0y3AC5Wl)gvkzm2ZhHDPN)gSP(NHWVVp7fzV0tfUuBPq1r9OJ9h(jctIFg2Bjf1bA0YSD055lacHRUcT3yl4y1ChisbMUb4h7pPlyRDGjrDEKpL9QSVb7RZEf2lZUMOnph7x8mugSV)(p3pRvxtEdPZQmph85xyHfMZ3NHpJ0TGDSYg1kvz9Qrh2ZGx6b274ZlL03vZ)JY91Fa6Xo0KCogki6XVZp2I(rnN16(9tcaKE8vj7BRlw3Z0(UexC0SZj9wtcEBQvBkXXbtII6v0WRgDC4WKqW66OQiop0jouHotkjH8FlPeIjJLm2YXIXDCsMowY4Jtjtpl(e2eOJulE4Wzj7d4ymaNSj0Ap6hnBur)9rNBHfKIk9OMflglwr4tzcPP2JOrhHzJENUGM2KpDuO3zB4udts077MoWMgTQMc1wQ6Eq9TXiCEW7ukVgXXvq8IwUDKUnXOdXDcBqGx9aKVLIHdzeYI6eCk(AtMm1GUWgHphJ5q9IqZ8wv9uktYyeewXXnjh3eiWXgg2pn4jmJK)ykXTl1mYGt7hsbHxdhdzybNaasOlsEopxHxw3CN5LEyxObCD3EZljSSEMbGcbiFZBkq)zg54jtMoZYsZd6HwTusMCrc5r3gXkRyLSPxmDISXxoXYjsKL)jtSSXtLEPSztMmBMSzwotMSPtVycyuYfZUC8uPYU0YzsKnzILJLDPmPZKnE2elLnEcGw4NhPD)TumEJD6rLwXboLdEabPQWH5iUp4rOB58y2JahW)FizzwktSLMOKXxjR3hquIhdKT4PZMoBMKlUC2uXYME54GSLzPuzJV4sWcPtLEC5ytZgwDb)G88CuqJJThrcGZoTVAFryWsEIQL3xinpquXt4LmKJZiEf(bFZd(h8hGo94sE9X(hUk6)3L6L3d7CSeC(Nz91CZDw7cfo1FPY7AiWBvc0BMbrfXVmuaWyyImj85mf)OVajkvRWA1F)nxPCPAFq98vkxrU697Z6pycsyvOnnN(mn)X)356G8g8ectyrVSbrJoof0BnWgpu04ORE)OfwBdqqQwj)DkuR(gYLQU2k1kLhApatj8Sahpze3GhWY8CzdYJJMvAqFIVe)d)kcrMmRZnfRvz165LRVYwvkT6kRNVqDOzk5Ar98bhSzJ(LmwzxlDvOfEYO8Yzt)YLkwOATcRu(zH(bLKE2OD1nkuy1Nf6w1Mqu))aDRTP8QLwVq1QpleVKjCIFWYbTlb9Xn6Um4296bfnFNb6w0Rnr(omyvvVHzHt9oB85hb8BMakNhf(3qBMY9FDL3k(4TxDMTw9L1w1Zstqd021i9ppmCNDdyV1xkEFP9(mGYAGunq33W3zVlvXgJIkzYNnpCwVz9raBeAwq55NGduJZfDUriUxRD9tFo86bnceu2jYe6NRFLOrW2pIxmy8f9sa4pCyaGsm74XB8sFroJUb9h2hGpDKwreNoyGdKDS4uj8RL9yqgDjDTvHVLBQrAUdCkIRgHD9iSPzVatkI9u4LwVlPM46GXZt)7Eo(jZRZncVxy4ZrDDiE3G(2pX3NsCY938vo35zlXUOCFOpSHI42Ztapgk8b(p(EHdfk0rqGMIl6YbNspc75g8c6(GqS3(JUk7YNcHl4ntHxcIPQ3e41WkM4lEv7PXlLRUJMcCI)7jqoK9lZNK)L4QbR74nGnZHbRDYmMsZ4RvTV0aeQ)n()eXS(xdm77z)c8zqxz8khBYVCXCRap(uX(PVprCFNFM9RngBywxPrdkzxDqOR3rz)PovCNOFGhNFch4pcSA6T6XU4r8R5MG(m5wVY6fS)MtGIQKM6DumQBtHbyJxHTFPjag3QWs7PWeBRNclm7YuqVYVEZxDcOIrwDQJbbYMqVc0J4lpGz2dCt3JkSVn6rSNsVHSm(Y3q7U3Kp6CNgGp)1FuzZALH81IzXZEGr)hCxVbcv0UGKc5N32ZSnW7Ujx5cfRzlnMy4BOdCeMGxIP3GC4XT6Zv4ncF9thsLfAIkQ(gxTV4ASFVqSJzZW(9TNEg)CvZ4NcG9hWDVy)HSVh7pI9hZ(t(RNEc8Sp0b8m7pne7pJXy)5S)IjaEjVDPp4xMDc7Vkm7hWntS)g2Fl7Vle7hVn7hjxWaVCV)E2)a7Na07hEf2Pa4)0RZ(NcnbcRpkH)cPj4CBxhlQmGFOq8JoJZeiPhWDSuRJza22EUZceVxasDxnWZsZYqDsX32EdK511qvFGM9ZMquJhPniTvAcEegwwunHU9ICD734SWq8ui2)cizGQe0V2rNOzJ4oKcBcuuavFBfADq7XpC(ZX(rS)r2)km3pwJ9tSVuP8vwVEUk1Qvzn5sV7TR5BpdmzEEt)xN22WAVIuYd7smB2dVR(elMdNt7e87v9QVh(a8j(DklEDt4JI7)(kNaj4FxdVuGBFmUIFW7HTncsnczZfjnW54BBnn9M7ycX(xGJKFCc)bV4t2VoNev5Vmm(qOGhXzk((NJFj6A2VqB8npsmDRqXV5m8rqFBL(2vwV2kLzX(USeFNJu1B1sVzxd3ErW7odVJ8i4T4xNNGs7uD(l2QjHx6lclj(28ylY)on)7m43pHxYjh0eMkwUlXkRUQ9LaQSIkMcMOsuxtzFTNUdHyVc(AcDLr2rJ96PzFn8LUG56iU8xM5nyVXJdDUJCWWkOaQMl(UnNRi)1BcJcENNaAaCdGYJdfca4a)lTwJ9G38gSF70SPcFWUE3MydHRI8UkgDjHPI28CU2nECOlS9bqryiNPBp89PSq6fqvjGFra)hhkCdrJnrTSN(DaONo(Jd9ve494qx0EAeLfxyWeQpTFX1GIGHAOrqj69hv3OdCBEk2Yhuy)jetKxFxpRNgB9WhYBEWbt0WyFqr2V6V1VWnyFEJ4lhl1IPyF2jBqXcx4jTTCWfselw6Ls3FHIwq)lbySi7ZSF58wM4lrftzOknkyjIfpv84ayxDfZMitiTf(20KwbY83cAUjaMeamxBYWivUOSylJNzPu4wUkvPnEBgA4VEGkTKUJP1EWjNBt84SKjIbSSSvxh8DIGVOKGfwI9zNgSa1YX1FL4loWkfuOUAbIjW)h7VsP(0kzSbWyvstLEb7s6bWyfDAW8jgaJkyWLq(tLidGH9RSjeCzBdQXIw0g8xe6WIwIyjtNidQbe6z8nDM3WcoCtvBqLb0ZjaSLbW(69bRmrboaeDCatYTo9bCnfDdPCuLMdatkG7E6qBPYob4JwUxCu(zecWnVxEuGWRMmGmlnmz853CwwU9jdkuxBCGktA3guP9HBeDexM4xmQToPzFvzSH3toyJsRuiJnDFGwhAt3qPprsH80u9xh6v3eYmeixlojjphXiaIujg2aiGas4VlPV1eH5LgfMrzv0HCqXoqhoIXija2lmIypOTadsgC34amUJtQHLSnmGmadlzOR1vgt2h0IMmZWcFalpazIJSZRmomJBqtT4WmUpKdRmtLAy2IlEJacWwpPpeYGw2FPfrL8L6V2Djk2wMbQUKdZbcLYy(NXNKQBitq6HnLcigZgGjTgmGqa2OkMePtJQWlxfo0aKCPQToCyEPQnX3kCaeOH4kvjiabjEheeWwLEc(ndzOspm3iS3tWmfBydGNNtF)IePZWdn9y4GCGJYZyO30Eavu3rBugE5HvZcgEOekPMS73qzMsoCwcpUDKmKjhMqcGg0PAXLtJbXVCbOTlm9FvxOltPIgyzChxltpTtQyz4oX3vJyyJx1TuEOJgxOwLs7oqTXaOqD9LHcH7qoli4jbVBpyxQYpXxld8ot8bJ9jVnZ56SFTTTNM)tHq0Rd0ZLm27V3pghEtg3I6kUGMd8)f7X2KTvUp2YQd(ltiPmhwn27797pkhCOht2D2M9wHz6F(uIlrW7oESNTe(7Tc8UiFyEf4m1MTZPq)WnlDZ(pDZQicSBFSQZhKRYDU7ARRBdjvXFKten7l73wgsXv1DWoCu1o2QFRPSF2XQ6o4ndX)XED(l9rSFXiIF3r5doG807(tV3)Zp
```

**Comment by maximus210793** [comment]
Can confirm also for WoW Classic Era V1.15.1

**Comment by InfusOnWoW** [comment]
Simpler example reproducing the problem:
!WA:2!TA16YTTXvyJbJBNclNkZeRg56MWih7g1wN6W0M8R0ziKiTykfPmi0fN6gQfalj2yqa4fasIQxnRAIAADVWEj920lSxNwN2z4JGEcoJM(eOF0ha)e0ZUl0f7gp9p9hcyXYDp7E(oFFFhPTsHKsZt3OqVcEf829Lgs4U1PHDt93zQdCI4EuUjX92E8O44jndyBVnH7v0okkiLfZ3QzNoj0unE)8bd6YzE29JPZyn)OozbbZX4Ub01TsIjU0tZjUPSOWKxXkjLWtnC6Wczj(gM4RuJbPCw3UuEYfUcpF4BpYJ6K1PJiK8fQuFPQlx3mf)WIKXjLgKetdcQ5LyCqsMdDdAyAlC1STg3EUYTSB3YUSLTzggCN4asFk3kK0JMyyjxQZcusqQ)rBDjof3QvRLQuV(WSW8RGXy3OGSEHTezGUdN4XYs2zIHKqwpIiBEf4mv3JssOTs5sK7ddfmdJcP77H3rXkAlUX8eQBuOxYaXsf5dCjZEewyvygCdWLGNhUmCf89ep6mwKaw3qN5Q0WUI1aEuQmOAJW7TfTRapnWLe7t0ndIiEvDsjby6mLvVmSkzyIGK7uWN1WYnGKKigzMW2MkgSVtEXDUOGi(RRRRVK(1EXpFPmM34WfR1mAPw3yRzBYvjl1FycnOZsrSW0s2nxYkXfpj9rU4Pr5YYEDlhfRz9rQ3v86sJpxR7Kr40IvrgrXv9zP0rC5nxSN986JvfMBxEuwC(UAH3VtBMeXtHlnwnL6gQPPP)aM44cjbRGGkgK7Tpjl1pI3mwsUmCqCUdRRXb4BKNfMwfPDrChRYZxB5wdtsPXLd7gqF29urwXD)iiYUPQipknYDdvSFAT3jCgMxPg0nh3HJKhSitsj6dfe9vzEP(N5bKqx80Rk(vr(40AoRkvAmilHwN1JL6NNa1cXtr3etZnnNV5QngR2NenHzTceR9mJeCeMkpgZc7eXvKmdoMjc6Owb3p1ULgH6j(TLN)53towLeRPbFinyzy29LtADixj(Cp03lg5rnlVSDZhiQ)cGp07i8vYaGN4jUc8r)3qbh3SK0OEW5HPGjHZn4qoDHxgUa8XHlcFc4JbpnmTbSE8f6Kfkf4VWSf500mEyXuEgTin0BSkmsLaCblxFQ7TXa8ugkPxs85xQE5BwXsjzRmF7fBUsTgx)WT5Z8OwPSEup4zmIpNWgzdQTsGksM7FQrme5A7Einw)aAiXjGEDHEfpaF4vHzh4qYPr6incTwsiPI0H6BUDuupTtIK3ud(0V(uqH9rv2XGu(eyzHQMy3PJFUu6wPTLpuLR2XTfx12XCQltqI0hE0sM5YXXfFCBOxKxBX1z9dK)4rAn4nJFs5mippsWhCLvEZY4Npqfh2wufD8UXp)Jl8b0Ue3(T7eefX93tUG3cHxwN(WSJK2kuBCsZgnBuz)89hMkO0Mnq7mOahtDX87RyURLB6psU2JH(HhT34jRYzBx8gzepHQPOTDCbvQ5t8I2mpa6p0K3un5fpv80FajIAa4RUFBIcRv5K4bRMpqLvBGOow7xpEsfQDSoBuTgnqsw9kvTJFMhhoP(slF3QB1XUphJmctQPJN9XfMCBT2P(CAIFuGx)CClpd129PGD0HKzUCiCpzOHm4nHnGnHTUl8d1GTHzHVc8vXwbFd4UsKfgaFl4BFXtbVdSl8DwhE3XQ8XQ21xWg(AWxh((tdFtTpaKl8qK7so(uwx)0NfUAv4ff9aGRjF(sYNLeppqQdmXMiEcXvPYZpF8KODwzpbFH6r9wKSLp8CyNVvqhcKNJPJS3LOJf2869gLeGkwU4GGp5)7oCWA4)caQF9H5UhyGH1aMWaoRXJEQmCfFbUO1pQKLk(wrzCxkIiFUX3SwM9nwZERO7CNHsZGeHPHcAM3WAtH6yNjglZTfKyWRXfqugNo4W)Zg4ZORmbSv)q8lut0RPd2v4wZrqTsyxtc)wlx7Qh)1vBjTwLBZh(IIog5hcZZJgA1OYkvSWEiwypKILGf1HMWskd8J66Qdvm4SqrthQpCATXrCHRL0PD0cnTQ9gnByxUoSQXWd9WkH7ttp(j7M7W184DaV)ULG348WVgXfv7a4wAWxgjx)c)Jm2H1LE6DbFGCcZCk0bDLXF0bCXj9W)qVDHfp6(JMVa7(NcEl1Dglw5Ca49EOYp8ZfvDrbg)6ev9hzMaPpm0Z)q05LHOCBxiw84o7oDUejgsx)KYJ((hjpqLIqH8d6FsrYBJPLqOKlSe6fH84DHVl890eshPqb46)Fqec)iyiMnQikoLFSuCv6)sCPKB)e4Nc)mF4FcVp8pK1qaPnTpUZ7P1GFjsZHFf8L0qAb8BGFl83uNmsCGF)RbJG)GGg9hH)e8NZzCWFb(RqOgYFHF3otG8DuquRXwM9cE1ERET(WF3pxxDwP06(4HVQbk7eTflSX)AT)Zp

**Comment by Surarn** [comment]
From your example it seems like its the "Slide from Right" animation is what causes the issue? The border around the group seems created around the position at the start of the animation and not the "true" position that the weakaura ends up at after the animation is finished.
