### ISSUE TITLE
Animations not working on relative progress

### ISSUE THREAD

**Issue by Dracolince** [WeakAuras/WeakAuras2#4936]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Before 5.12.0, I had two auras animated:

- A shrinking circle texture for cast spells (it would become smaller as the cast time went on, like you'd see on a "bow and arrow" crosshair for some FPS).
- A rotating spark texture for player power (it would "follow" the progress of a circular progress texture).

After 5.12.0, they just won't animate at all.

I've tested it with a fresh cast time / power texture and it won't do anything.

_Progress textures_ or _preset/non-progress animations_ work just fine. The ones affected by this issue are _regular textures_ using _custom animations_.

### WeakAuras Version

WeakAuras 5.12.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. New aura: Texture (NOT progress texture)
2. Trigger: Player Info > Spell Cast
3. Animation: Main > Custom > Relative progress (1)
4. Scale, Rotation, Color... any will do (nothing, that is)

### Last Good Version

WeakAuras 5.11.2

**Comment by InfusOnWoW** [comment]
I cannot reproduce that, this aura created with your description, correctly displays animations:
!WA:2!nAvtVTTTB845v0nFyO2RRyfRhekW6StZABm2Ah(dmuy5A3KohBpz1vNt2us0sCvHuJKkjoaBy1xwUna)rWN3PaSVa5tGGXoS)xZHIDoFc2dPKDAswbQaOeFEH853ZlKpkxZs7uYRK3H3zgXLr7XI5U4BTYCuSmGX7ejjmQOaFCNrJeyzUJquxGFxgHkDQ3OTDdR5UmwOhBpAV9ir4HhVGSHNpoWuTPdNi5eFFmx8r3HNn9WIrfJf4b(ykMtC7fW2RdD48ZrEIq)PE2gorPFmLihoZd7epAK94imFJgT6285TmLaHPsAujLEihbJ7SbgfUfZdp8erSdExmv2dwhz)JguVwp7b9SRzzBP5BwhjKtfr4WW2ODW5MZHL27ms1EUu6Wj6PB6jkCYzgtBOKsorHOXyUffuuuyQsUKJCF5zyOlhdyWQx3gTAnnMMfrkeve5kj7ITtPvB3FSYPqGgZPOWFacFqU43p9LyCunW(UsleKDcMIOKDuZOp0sirCzZJXibUNKJP(YGRMu0KYO45EXCTwdurkUadjgpXeLQQ4ysfZDqe6HF2uHlke3mM6g96rWB1skhXz(CSqSMH2c9Z(Un8vPD)SVBxPGb8eYacde1peB8TglxSXQgvHbG1G7frQy8LgLZMBCFJQPlLJLXCAMvmURr5YP6ii0Y6nScWC9k3VAfyNkNACyJwVsLfq6DBrBNUOcyQxHKvNWXHivO3rlC)U5FW9(QPOWOaKk2mrajqIFG0XLfY4MB84)5V))RapP0pnxQQ6y2392IzRz4HdLOl7Mka)gHOmTuaBYIuwP1tkF15zvsubGv8qDHL2Udtr9ynQtk64glKSDsXwT8jRLuz(YLPX4p)oKx1WOF23TFljNlc7(NllCrPBN6vAGRb3qln(ZP5O9HHLgpEQwMkUpFrCVUItP99(W0ItLmRO4qbovxTt9N)hofF91m8HHdmqWGxfOHHdmqNVIJV(fGCzEvOgHRRS8VKqFLqFTqNlj0rj0rleDjHiLq0IAphotcPLCPzlRnE8jC(VcvwNLXuoBuXfrc7fSDgrOerqtOWiPysLKvtURktd3mkqsvzdoygCFJf2xDb()7gjfNdKoW9q(Cwm17WRhvsI3xoqeGGlx7ND)E0n1m1VgX4WXObISjjvMUu2T)Cr01EJLRtqplxUC5pjLloCKUhHzTNB3j6J1mHwkm1fvUVG4jdmRbKNMAiY(ypnZxnpT)Y2zW5yT8FekOjJgNCLzPrlBGPz7oTBKuKdoLsNzAf1bXNLhEMM5buz01AYjhy89XipiQGmSTpNJVWsZ182JX9Ebhfn5fztsbWUebXbQoZ853OhyuXnB3UH1aZo22D2YAZNUH98LMUh5a8nZ8O(NZokP6UxDEUDRnB341Z9dz71KJ)Pym1DC33)b3R6xN6DkbhRE9KSldYprrPpF4elLmANDXCOLZmf7w678)KJuZx4Atve1xgAogoT90fCc0AUeC6DoG4(skuTMxVWEQtC5nvtd0mAraHf1wZeIsyEGtawvB(kZqgYRPJewavEdRDIdLKcMQwv3i5xky5gIec1mtbeyutIUgGLAEQ8l2d7TfA)GlYIqdMX1fX6UuFG1E66KQXeVJWFZJo4rSwpGA19icnTkfuSWjloVL(3mRERvEposF3G4HjFrHKTkychEKfmpGX2jxsT8ZKm3Dt7V(P5(n6TjEvBJ3t)Jel(5dOBSL6A3JgXH(6qZvOwk)PP52Mkwk450RUvJgTToRoeoxthr8lWjuLbWbrxFX)hPQIFcrGGclVa((zPGzQ2YK0)6AYcvhoD5bQKRusu9j4DlT7F1)Fp

**Comment by InfusOnWoW** [comment]
Ah Texture. That's why it's easier to just add your test case to the ticket.

**Comment by janjoerke** [comment]
+1 Witnessed the same problem, when animating icon.

!WA:2!Tv1ZUTTny865w0bLHTgVUGwGEWOaRZPTOijaTdB7WGLRDBgCStLvAtoztjrjXvzsnskh7cSdZxwpmGbySNaFyN2j)iKNabH9eem0hG8eSpsj52mmFqKF)HF))7NR0P24AE18E79wsCz0bSeUl(oxXYLfX4)qv4hFwFFFbwwzfI6gY4hYiuPtR29SBBL5YyrEStPdoLeJhDwjzBVaCOPYGJMl5KGamx8P3JxC9DMYzXylrmok6CrIdEcMkhK47tMUAyRMdShoWUPL9spSdW0g0L)82DpSZrDJ3mrGhgGPyoXDqi70(0rzxI8CH(OvrGyMqjsN4i0mmpJJrrduoThAmE1lzrrso23hKOSQOuYO56R77jmS0Hw8Tlnx9d5SaowiQ3qBOTxh(hcwIm1AWHT721IcwrySqzvjh5(6rlwB8BD1a8IeArLWiEtKRKmbBNtFaZd)xx5cOaJ5uu0lHYgHr)9ZJlCBE75(35kF0ceLmgjbPpXsirCzNZWibEaKr0az41t3WKYO4mVeUwRHQsoxGHwINyUsvvDnTH5yeH(2Ao6(TvvhHlkcpTAoTzX5ZQMvKluresIhLUHJBIqYgN(ahLT2NMTwyNeQB8p7dFv(TrzO)W66W84IZtEyDpCKeDCX5jBBuh(XXYeoTq16pO(6Nx)(f6VDPb()Kcwbt9mYZIzvTqrXHOk1MvP20F7tMxwl2B3D259XRQoeVPaOjbHs7s2oCMeoQK(vxpD75CmWd6t51JMvD8juIiSJs6gPns3o9(PpiTbmYkqsLBWHlHrdlCa4pX3Uv6gzaPdmleWzjuV3EZ4As8u5qricgSoUyfl(2AM6p(mo0GhkkUK2yXAz39lfX34dEEl9YALkvQEEoxCKVEn1S5r29J)Cntuc0VGKW9vepzOztG8IChrMI90m)LS8v8tkcNZ0Y)rOtt8NLETL5LeBGPzV(9ANUbhskLol1k(EmJffzaS7CJoCYBQ)IeKhuvq1TTVuIx6PmnVtzCVxXrXZFvXL8aycrqCIWHf58hadfV5(9612AOzFB7(hyT)ZEUD2AxpG8g8TlYOJVKFus1Wk9pYU7(9A)USGi2PD44FkbtDND4v35r7948Stj4m1NNwm8uDUIs96mNePKr7pbZb8LLk2D1lFFXk19YuBHIO16sZzWM0Zk5eQ1CDWPTCiX91uyMUQ(HdutYvnvxd1m6saHBQ9MjuLW8qNqSAY97mJyiV)uVPgJLoiPeQzAqikarXh5ibtrLBznojssmwPKmbdUduZYncjeBLcis3qXhAwbmkN4rObHNRfc1DpfiPlO1w)ZNnkUMsXllk0Sqbdtbu9xBVMEQHiSh27a00W)llcnCjxVPOXK(4v(CaPeGYGbMQCKghr8K07zK(9gMWEN0yfHMVvasmU41yCCtLJLwkoHzWOo0Z7hRFOHoqlrWbewlfcM5BySXv2lH4T6GXnBy(ItqhfV9sjZDsoO7TQ8R07s8o)d(BI6TE6f5JtDubOkyDg0YQD7EPFDvRtvBqFdaqq9jbgCcvziyO9ML)POAV5PebcgL9c5tZB6)XglvqYK8qDEPUHlwVdNETAcNh)OD37r7wBYFF8)c
