### ISSUE TITLE
weakauras profiling tool issue

### ISSUE THREAD

**Issue by tyujrtuy** [WeakAuras/WeakAuras2#4939]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

weakauras profiling tool behave really weird,any one knows how to fix this?

### WeakAuras Version

5.12

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

TW/Asia

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

just using the profiling tool 
![image](https://github.com/WeakAuras/WeakAuras2/assets/108184767/d8f3d467-0aeb-45f9-8413-26f9ac3b2275)

**Comment by InfusOnWoW** [comment]
I don't understand the issue, I can't see anything unexpected in that screenshot.

**Comment by tyujrtuy** [comment]
as i can remember.it used to be go down as the cpu usage,now it all over the place

**Comment by mrbuds** [comment]
> as i can remember.it used to be go down as the cpu usage,now it all over the place

You will be able to chose the sorting you prefer soon https://github.com/WeakAuras/WeakAuras2/pull/4906

**Comment by tyujrtuy** [comment]
ok，thx a lot 

> > as i can remember.it used to be go down as the cpu usage,now it all over the place
> 
> You will be able to chose the sorting you prefer soon #4906
