### ISSUE TITLE
Icon Cast Inverse bug

### ISSUE THREAD

**Issue by ShiftlessAK** [WeakAuras/WeakAuras2#4941]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Icon>Trigger>Player/Unit Info>Cast>Inverse no longer triggering an icon.
Pretty square no show when me no casting stuff.

### WeakAuras Version

WealAuras 5.12.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Open WeakAuras
2. Go to Icon
3. Go to Triggers
4. Select Player/Unit Info
5. Select Cast
6. Click "Inverse"

Icon should now display when Player not casting. It does not. 

### Last Good Version

WeakAuras 5.12.0

### Screenshots

![WoWScrnShot_032124_112115](https://github.com/WeakAuras/WeakAuras2/assets/164404317/6c121401-0348-48a2-9f67-57fa41f39f5f)
![WoWScrnShot_032124_112202](https://github.com/WeakAuras/WeakAuras2/assets/164404317/839204d2-9bb9-4f60-87e7-c8f0a19dd575)

### Export String

```Text
!WA:2!Dv1ZUTvXx4AmOsVOMM4gcPbkecQbPQFQqJuJeivK811Ujih7W13qlRIN7DgFNHC9mxMzUoXDbqT(HO7qYpcEbBkR8cEaYc2WMrw8eKf8aKNaoZy70)4f2ZCMZCoFFNZ3CCHAL6wcxc)SpDelwWBjYLXKctq5AQq2mtZeCLNSFZoDueDHXiEmyFFbJRJQuTry1GjXcrkwCmV1XSms7tNVTkoHqLOyxe2oqPrsTNpJZ0ErDGFuuVbAjljHivF1MYzl)lFD)mIFo4wwPCf5quKsiJ2HGs3tGjTptLhr6r46w5D6Woz8Hvk3k8WwHLdcp7fU7CnW5x2YhaXA9kuKflejtPzXQaoQlr5nqLrst3fR8mxlcaycrFrc2xsGee0A)Q1RpWgAlMApnjAnk(iuukP9imjcqsiaA5ovRVFTdQpmNpJmEBAU6FkHB0aYw7HOCjYL31ckNi49LqvQjpTFBZYocQPMv8mVhGfZQMfcSUVLzjtjZnmRzUPCNYb7bH38r2W2XSEBZhV2OkcPm31Lm30SP5tABwWClxaCU97W2RzwST56qs8RGuAGOzPO(e5amrPT1gZQJTKIX7bDcObA3m)mQ59Bdb(dHOLTKTx2JeoLB2s8FCPZbDarYrPFlCxae)2zzsrIKOutfs3(dU0Bmurs74umM3ckxkKgiMMqhbv6asIvE8LRywycSnckRjsroh)SLZkPjNOpurrGA6XZ0Fz3Wz09vhHSlcCy2cFUGtgEXXBClv2IVueQisfYVUqHcfpBQ15GYV8bHnZUUZiO6fqOyXpIH1u)YW2ZNMl2jeSZ4tNm9jW3ndrN6o)7ZbzvN(abLcnqUqWOFJMnQAwqc8Y6ZiNJXoyue(mCgjaj6I1KSNS(3KJWqHbTEy4RW95zAIZ2Xcj(rsu2GhnBXua0JPyGEKoJZV0Z0SL2TrJQbh63mmS5Eb7(WDcNCrQBXEc5gZy0JFL8yp1PQBEqy9DBu9FNKKkoUMK8d5eEC)9FZp)oBDVPSZEWP2VEGTXc9ZIdS7S3EsuUwl4nbPfi6gznxNWt003DSD9CQn0UPYfLgRe8HZTqDEohC(2nuN)TIrPKIoyfszXhXbvxr3j1zW6LCzZhQsejnIsyju9Z9tfiCnFfq7vc6MNQzE(WmG4vmrEbXPiLYUcgfKctaSlZweWszST)sWe8EOtOVUjgNos60Xwg7BNIoUJeEN3sBBNfLNmf7)V3EW8zJ0XyMY(mCxW5vV2F)zNFeHKv2IeDGTesDd)QmZD4TgyL0oB55bWQVEatzhbHPrqq6Ws8gPfX9M(oC1c)kFdg(89aI0HfVEakdE1rco2kHFEaknJIkE(0(EnlwTqpQvLGQvBe8cn6w5m84C5xCs29AXZXbYzdjO(pri6wyiIZ6664BBUsnyuZ2NsqklVD94lpbptqCODOoCpaOy1aRp28z22VlIXDx08Jx28tMF28uy5786wgzVhZ9hj3EZGykj(OAMRELnezBC)7pOhsYSfIa3W8GEO0CIrjJPiEcmRDLbWiji76(M8nn)FyO4vm)sugcQVyZZwZBmJpDaceEpdRDjv09UZD36o3TuV)5X)3
```

**Comment by ShiftlessAK** [comment]
what you mean "more information is needed"?
Its really simple. 
For years I could use the in-game tool to trigger an icon when Player is NOT casting.
Icon>Trigger>Player/Unit>Cast>Inverse

as of your last update, its not working. 
I'm not sure how much clearing I can be here.

**Comment by emptyrivers** [comment]
Sorry, who are you talking to? I don't see anyone asking you for more information in this ticket (though, on that note, it looks like you pasted in the debug export; if you would be so kind, can you instead paste the import string (while possible, it's quite the hassle to install a debug export compared to the normal export string)
![image](https://github.com/WeakAuras/WeakAuras2/assets/24878501/4b452112-3269-4920-b6fa-b8a543e56b22)

**Comment by ShiftlessAK** [comment]
> Sorry, who are you talking to? I don't see anyone asking you for more information in this ticket (though, on that note, it looks like you pasted in the debug export; if you would be so kind, can you instead paste the import string (while possible, it's quite the hassle to install a debug export compared to the normal export string)? ![image](https://private-user-images.githubusercontent.com/24878501/315851911-4b452112-3269-4920-b6fa-b8a543e56b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzY4NzcsIm5iZiI6MTcxMTA3NjU3NywicGF0aCI6Ii8yNDg3ODUwMS8zMTU4NTE5MTEtNGI0NTIxMTItMzI2OS00OTIwLWI2ZmEtYjhhNTQzZTU2YjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAzMDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMjU3MWY2ZTg4ZGI2ODllODg3M2ExMjQ1NzM3NmY2YzA5YmU4N2NhNjVmZTc0NTA1N2Q4YjUwN2Y2MzJkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4_3oDfpE332f-F57UisgohyfAohUcCNz3YBI-coBk4)

Sorry for gruffness. Was confused by Lavel that said "More information needed"
I updated post to [hopefully] the correct lua string. 

I've reinstalled. I trouble shot to make sure I'm not an idiot [hopefully]. I even tested an aura that I know for a fact worked before update and now no longer does. 

As an interesting side note, if I interrupt my own cast by moving, the aura WILL briefly flicker on then disappear again. So I'm guessing it has something to do with how/when WA is checking for the "cast" status.

**Comment by emptyrivers** [comment]
Oh i see, haha. No worries, that label used to mean what you thought, but then we changed how we use it to approximately mean 'this ticket hasn't been triaged yet', but I guess we never changed the description. Sorry for the confusion!
