### ISSUE TITLE
e92843c breaks Luxthos' class WA packages when new auras are loaded

### ISSUE THREAD

**Issue by AntoineBnl** [WeakAuras/WeakAuras2#4945]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Prior to 5.12.3, when loading auras (for instance when swapping talent loadouts or by enabling warmode) Luxthos' WA groups would update and rearrange new child auras with no issue.
Since e92843c when swapping talents, newly loaded auras aren't updated properly to fit their groups, as they have missing borders and/or incorrect sizes. There is no issue when doing a /reload.

Luxthos' packages use a lot of custom code to handle auras and groups, so I'm not sure how this issue should be considered, but I figured you'd at least want to know since Luxthos' packages are quite popular.

For now I have simply reverted that line from e92843c and everything works perfecly once again on my end.

### WeakAuras Version

WeakAuras 5.12.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
No error from BugGrabber/BugSack
```

### Reproduction Steps

1. Install WeakAuras 5.12.3
2. Import Luxthos' class WA package for the class you'll be using
3. In Custom Options for the parent group of the package, select "Always Show" under "Utility Icons"
4. Select a talent loadout that will load at least one aura that isn't currently loaded (enabling warmode also works)

### Last Good Version

WeakAuras 5.12.1

### Screenshots

![wa_5121](https://github.com/WeakAuras/WeakAuras2/assets/97803599/aaa3b61f-6cae-4caa-9e7d-7c4a5e9d7778)
![wa_5123](https://github.com/WeakAuras/WeakAuras2/assets/97803599/85eaf324-9090-4f8e-acf8-d241c7585ad8)

**Comment by InfusOnWoW** [comment]
That's due to a faulty assumption in Luxthos's code. In Init() the assumption is that all child regions of the dynamic group exists, even if they are not loaded. That assumption is incorrect, regions are created on demand when auras are loaded.

The correct way to do that is to not use custom code for setting the icon's sizes. Or if he must set the size via custom code, to do so when the the child region exists, e.g. in the grow function.

**Comment by AntoineBnl** [comment]
Thank you for the response! I did expect this would most likely be on Luxthos to address rather than the WeakAuras team, just wanted to confirm in case there was something else going on that you didn't intend.

Since that's not the case I'll probably keep e92843c reverted on my end until Luxthos' packages are updated.
