### ISSUE TITLE
Error when trying to remove a TRIGGER """"Only occurs in SPANISH language version"""

### ISSUE THREAD

**Issue by djdenisdj** [WeakAuras/WeakAuras2#4949]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When modifying a "weak aura" and wanting to eliminate a TRIGGER I ran into the problem that it won't let me eliminate it no matter how many times I give the option try to eliminate (X).

"""I must clarify that this problem only occurs with the SPANISH language version"""
I have this problem since the last update where they changed some translations to the Spanish language.

### WeakAuras Version

WeakAuras 5.12.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. enter weak auras
2. enter any aura
3. go to the Trigger window
4. try removing a Trigger
5. You will notice that it does not allow it.
![image](https://github.com/WeakAuras/WeakAuras2/assets/164722883/b4c2b333-bf7e-4cf8-afa7-31dde9bdc83e)

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/164722883/06b24515-1df0-440c-b4f3-bc8351d17208)

The illuminated (X) is the one that should remove the TRIGGER, but it doesn't work.

### Export String

```Text
It's not a problem with a specific aura, it's a general problem that happens to me with new and old auras.

It only happens with the Spanish version.
```

**Comment by emptyrivers** [comment]
Bad translation in esMX on the trigger delete string, same as the one in 5.9.2 for esES. Fixed for the next release.
