### ISSUE TITLE
Errors after update to version 5.12.4

### ISSUE THREAD

**Issue by Odysseas68** [WeakAuras/WeakAuras2#4950]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

After i update to version 5.12.4 none of the WA that i have installed works. I have the following LUA error:

1x ...aceWeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:410: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:376>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:508: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:504>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:566: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:558>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:576: in function `UpdateProgress'
[string "@WeakAuras/RegionTypes/Icon.lua"]:616: in function `Update'
[string "@WeakAuras/WeakAuras.lua"]:4560: in function <WeakAuras/WeakAuras.lua:4557>
[string "@WeakAuras/WeakAuras.lua"]:4649: in function <WeakAuras/WeakAuras.lua:4615>
[string "@WeakAuras/WeakAuras.lua"]:4759: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:1074: in function `ScanWithFakeEvent'
[string "@WeakAuras/GenericTrigger.lua"]:1395: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1997: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1781: in function <WeakAuras/WeakAuras.lua:1621>
[string "@WeakAuras/WeakAuras.lua"]:1974: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1252: in function <WeakAuras/WeakAuras.lua:1211>

[string "@WeakAuras/WeakAuras.lua"]:1370: in function <WeakAuras/WeakAuras.lua:1318>

Locals:
self = Frame {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 editor_tab_spaces = 4
 displays = <table> {
 }
 mousePointerFrame = <table> {
 }
 minimap = <table> {
 }
 historyCutoff = 730
 dbVersion = 71
 editor_theme = "Monokai"
 dynamicIconCache = <table> {
 }
 editor_font_size = 12
 lastArchiveClear = 1607896128
 lastUpgrade = 1710952045
 features = <table> {
 }
 migrationCutoff = 730
 registered = <table> {
 }
 login_squelch_time = 10
 RealTimeProfilingWindow = <table> {
 }
}
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras/WeakAuras.lua:3601
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @WeakAuras/Transmission.lua:354
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras/GenericTrigger.lua:3018
 InitializeEncounterAndZoneLists = <function> defined @WeakAuras/Types_Retail.lua:10
 IsEnvironmentInitialized = <function> defined @WeakAuras/AuraEnvironment.lua:185
 duration_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras/History.lua:22
 UpdateProgressFrom = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:558
 RunConditions = <function> defined @WeakAuras/Conditions.lua:838
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 get_zoneId_list = <function> defined @WeakAuras/Types_Retail.lua:72
 checkForSingleLoadCondition = <function> defined @WeakAuras/Prototypes.lua:1156
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 CancelDelayedTrigger = <function> defined @WeakAuras/GenericTrigger.lua:905
 centered_types_h = <table> {
 }
 ensurePRDFrame = <function> defined @WeakAuras/WeakAuras.lua:5404
 talent_types = <table> {
 }
 LoadFunction = <function> defined @WeakAuras/AuraEnvironment.lua:637
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 player_target_events = <table> {
 }
 GetTalentData = <function> defined @WeakAuras/Types_Retail.lua:185
 subRegionTypes = <table> {
 }
 UnregisterAllEveryFrameUpdate = <function> defined @WeakAuras/GenericTrigger.lua:1837
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 StringToTable = <function> defined @WeakAuras/Transmission.lua:298
 RegisterLoadEvents = <function> defined @WeakAuras/WeakAuras.lua:1889
 GetReputationsSorted = <function> defined @WeakAuras/Types.lua:1723
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:1115
 CheckSpellCooldown = <function> defined @WeakAuras/GenericTrigger.lua:2883
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 GetProgressValueConstant = <function> defined @WeakAuras/WeakAuras.lua:3907
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @WeakAuras/WeakAuras.lua:2259
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @WeakAuras/GenericTrigger.lua:3077
 event_prototypes = <table> {
 }
 NeedToRepairDatabase = <function> defined @WeakAuras/WeakAuras.lua:2336
 AtlasList = <table> {
 }
 RegisterRegionType = <function> defined @WeakAuras

I revert back to 5.12.3 and everything works.

### WeakAuras Version

5.12.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
1x ...aceWeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:410: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:376>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:508: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:504>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:566: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:558>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:576: in function `UpdateProgress'
[string "@WeakAuras/RegionTypes/Icon.lua"]:616: in function `Update'
[string "@WeakAuras/WeakAuras.lua"]:4560: in function <WeakAuras/WeakAuras.lua:4557>
[string "@WeakAuras/WeakAuras.lua"]:4649: in function <WeakAuras/WeakAuras.lua:4615>
[string "@WeakAuras/WeakAuras.lua"]:4759: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:1074: in function `ScanWithFakeEvent'
[string "@WeakAuras/GenericTrigger.lua"]:1395: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1997: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1781: in function <WeakAuras/WeakAuras.lua:1621>
[string "@WeakAuras/WeakAuras.lua"]:1974: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1252: in function <WeakAuras/WeakAuras.lua:1211>

[string "@WeakAuras/WeakAuras.lua"]:1370: in function <WeakAuras/WeakAuras.lua:1318>

Locals:
self = Frame {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 editor_tab_spaces = 4
 displays = <table> {
 }
 mousePointerFrame = <table> {
 }
 minimap = <table> {
 }
 historyCutoff = 730
 dbVersion = 71
 editor_theme = "Monokai"
 dynamicIconCache = <table> {
 }
 editor_font_size = 12
 lastArchiveClear = 1607896128
 lastUpgrade = 1710952045
 features = <table> {
 }
 migrationCutoff = 730
 registered = <table> {
 }
 login_squelch_time = 10
 RealTimeProfilingWindow = <table> {
 }
}
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras/WeakAuras.lua:3601
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @WeakAuras/Transmission.lua:354
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras/GenericTrigger.lua:3018
 InitializeEncounterAndZoneLists = <function> defined @WeakAuras/Types_Retail.lua:10
 IsEnvironmentInitialized = <function> defined @WeakAuras/AuraEnvironment.lua:185
 duration_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras/History.lua:22
 UpdateProgressFrom = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:558
 RunConditions = <function> defined @WeakAuras/Conditions.lua:838
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 get_zoneId_list = <function> defined @WeakAuras/Types_Retail.lua:72
 checkForSingleLoadCondition = <function> defined @WeakAuras/Prototypes.lua:1156
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 CancelDelayedTrigger = <function> defined @WeakAuras/GenericTrigger.lua:905
 centered_types_h = <table> {
 }
 ensurePRDFrame = <function> defined @WeakAuras/WeakAuras.lua:5404
 talent_types = <table> {
 }
 LoadFunction = <function> defined @WeakAuras/AuraEnvironment.lua:637
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 player_target_events = <table> {
 }
 GetTalentData = <function> defined @WeakAuras/Types_Retail.lua:185
 subRegionTypes = <table> {
 }
 UnregisterAllEveryFrameUpdate = <function> defined @WeakAuras/GenericTrigger.lua:1837
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 StringToTable = <function> defined @WeakAuras/Transmission.lua:298
 RegisterLoadEvents = <function> defined @WeakAuras/WeakAuras.lua:1889
 GetReputationsSorted = <function> defined @WeakAuras/Types.lua:1723
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:1115
 CheckSpellCooldown = <function> defined @WeakAuras/GenericTrigger.lua:2883
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 GetProgressValueConstant = <function> defined @WeakAuras/WeakAuras.lua:3907
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @WeakAuras/WeakAuras.lua:2259
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @WeakAuras/GenericTrigger.lua:3077
 event_prototypes = <table> {
 }
 NeedToRepairDatabase = <function> defined @WeakAuras/WeakAuras.lua:2336
 AtlasList = <table> {
 }
 RegisterRegionType = <function> defined @WeakAuras
```

### Reproduction Steps

1. Update with WOWup the addon
2. login to my character
3. No WA display
4. revert to 5.12.3
5. Login
6. Everything good

### Last Good Version

5.12.3

**Comment by InfusOnWoW** [comment]
Please include your settings.

**Comment by Odysseas68** [comment]
> Please include your settings.

here is my WA settings file.
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/14736397/WeakAuras.zip)

**Comment by Sratarak** [comment]
Also seeing this issue with 5.12.4 (reverting back to 5.12.3 lets them load)
`8x ...aceWeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:410: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:376>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:508: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:504>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:566: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:558>
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:576: in function `UpdateProgress'
[string "@WeakAuras/RegionTypes/Icon.lua"]:616: in function `Update'
[string "@WeakAuras/WeakAuras.lua"]:4560: in function <WeakAuras/WeakAuras.lua:4557>
[string "@WeakAuras/WeakAuras.lua"]:4649: in function <WeakAuras/WeakAuras.lua:4615>
[string "@WeakAuras/WeakAuras.lua"]:4780: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:868: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:814: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1094: in function <WeakAuras/GenericTrigger.lua:1079>

Locals:
self = Frame {
 0 = <userdata>
 iconSource = -1
 AnchorSubRegion = <function> defined @WeakAuras/RegionTypes/Icon.lua:155
 subRegionEvents = <table> {
 }
 Expand = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:965
 yOffset = 0
 GetColor = <function> defined @WeakAuras/RegionTypes/Icon.lua:471
 button = Button {
 }
 icon = Texture {
 }
 SetOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:268
 keepAspectRatio = true
 SendChat = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:216
 SetInverse = <function> defined @WeakAuras/RegionTypes/Icon.lua:405
 state = <table> {
 }
 SetRegionHeight = <function> defined @WeakAuras/RegionTypes/Icon.lua:530
 GetMinMaxProgress = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:372
 SetAdjustedMax = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:358
 UpdateIcon = <function> defined @WeakAuras/RegionTypes/Icon.lua:495
 PixelSnapDisabled = true
 cloneId = "208393"
 Update = <function> defined @WeakAuras/RegionTypes/Icon.lua:615
 regionType = "icon"
 progressType = "static"
 GetRegionAlpha = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:337
 UpdateSize = <function> defined @WeakAuras/RegionTypes/Icon.lua:324
 maxProgress = 0
 states = <table> {
 }
 SoundPlay = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:193
 Collapse = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:948
 UpdateEffectiveInverse = <function> defined @WeakAuras/RegionTypes/Icon.lua:414
 zoom = 0.300000
 ClickToPick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:874
 color_b = 1
 UpdateTexCoords = <function> defined @WeakAuras/RegionTypes/Icon.lua:337
 UpdateTick = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:602
 color_r = 1
 SetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:277
 MSQGroup = <table> {
 }
 SetRegionWidth = <function> defined @WeakAuras/RegionTypes/Icon.lua:525
 OptionsClosed = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:869
 RealClearAllPoints = <function> defined =[C]:-1
 displayIcon = 4620672
 outer = Frame {
 }
 RunCode = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:223
 GetYOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:289
 SetAnimAlpha = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:581
 SetProgressSource = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:341
 Color = <function> defined @WeakAuras/RegionTypes/Icon.lua:442
 SetGlow = <function> defined @WeakAuras/RegionTypes/Icon.lua:622
 SetYOffsetRelative = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:306
 SetZoom = <function> defined @WeakAuras/RegionTypes/Icon.lua:550
 masqueId = "crest_tracker_tsu"

 cooldownEdge = false
 cooldownSwipe = true
 GetProgressSource = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:368
 GetXOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:285
 SetYOffset = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:281
 SetCooldownEdge = <function> defined @WeakAuras/RegionTypes/Icon.lua:542
 color_g = 1
 SetDesaturated = <function> defined @WeakAuras/RegionTypes/Icon.lua:521
 Scale = <function> defined @WeakAuras/RegionTypes/Icon.lua:512
 GetYOffsetRelative = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:314
 SetAnchor = <function> defined @WeakAuras/Reg`

Settings here: 

[WeakAuras.lua.bak.zip](https://github.com/WeakAuras/WeakAuras2/files/14736454/WeakAuras.lua.bak.zip)

**Comment by malbaratar** [comment]
Exactly same error here. Reverting to 5.12.3 works.

Message: ...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)
Time: Sun Mar 24 15:44:40 2024
Count: 1
Stack: ...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)
[string "=[C]"]: ?
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:410: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:376>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:508: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:504>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:566: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:558>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:576: in function `UpdateProgress'
[string "@Interface/AddOns/WeakAuras/RegionTypes/Icon.lua"]:616: in function `Update'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4560: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4557>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4649: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4615>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4780: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:868: in function `ScanEventsInternal'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:814: in function `ScanEvents'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1094: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:1079>

Locals: (*temporary) = <function> defined =[C]:-1

Message: ...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:410: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:376>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:508: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:504>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:566: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:558>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:576: in function `UpdateProgress'
[string "@Interface/AddOns/WeakAuras/RegionTypes/Icon.lua"]:616: in function `Update'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4560: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4557>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4649: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4615>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4759: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1074: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1395: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1997: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1781: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1621>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1974: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1252: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1211>

Time: Sun Mar 24 15:44:40 2024
Count: 1
Stack: ...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:410: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:376>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:508: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:504>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:566: in function <...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:558>
[string "@Interface/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua"]:576: in function `UpdateProgress'
[string "@Interface/AddOns/WeakAuras/RegionTypes/Icon.lua"]:616: in function `Update'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4560: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4557>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4649: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4615>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:4759: in function `UpdatedTriggerState'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1074: in function `ScanWithFakeEvent'
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:1395: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1997: in function `LoadDisplays'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1781: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1621>
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1974: in function `Resume'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1252: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1211>

[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1292: in function `Login'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1370: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1318>

Locals: initialTime = 15000
takeNewSnapshots = nil
loginThread = <no value>
startTime = 932866727.106900
finishTime = 932870242.464400
ok = false
msg = "...ace/AddOns/WeakAuras/RegionTypes/RegionPrototype.lua:410: attempt to perform arithmetic on local 'value' (a string value)"
Private = <table> {
 HandleGlowAction = <function> defined @Interface/AddOns/WeakAuras/W
 
 Settings are here:
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/14736492/WeakAuras.zip)
