### ISSUE TITLE
Intermittent major FPS drops when dragging the main WeakAuras configuration window

### ISSUE THREAD

**Issue by brittyazel** [WeakAuras/WeakAuras2#4956]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Sometimes when dragging the main WeakAuras configuration menu I suffer from major FPS drops that continually get worse the longer I continue dragging. The issue does not always happen, and I'm unsure of what the trigger is, but there are times after typing /wa and bringing up the window that moving it will cause my FPS to drop from 144 to <30fps. And the more I move the window, the slower and slower the game bogs down.

I'm not sure if this is new behavior or not, but I don't remember this being an issue. Likewise, after  few minutes the issue seems to just disappear, and dragging the window goes back to the normal behavior. I apologise for not giving you more to go on regarding how to trigger the bug, but it's happened multiple times in the last few days - enough to lead me to want to report it. Nevertheless, whenever I try to record it happening the issue seems to have resolved itself.

### WeakAuras Version

WeakAuras 5.12.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

- [X] Yes

### Reproduction Steps

1. Enter the game
2. Press CTRL + F to see FPS
3. Type /wa to bring up the menu
4. Drag the window and watch FPS drop from 144 to <30fps
5. Keep dragging to see it go lower and lower

**Comment by InfusOnWoW** [comment]
Please include your settings in the bug report.

**Comment by brittyazel** [comment]
Which settings? In what form do you want me to provide that info?

**Comment by InfusOnWoW** [comment]
your weakauras settings file, found at WTF\Account\<Account #>\SavedVariables\WeakAuras.lua

**Comment by brittyazel** [comment]
Here you go. I had to zip up the specific file due to GitHub indicating that they don't allow .lua files directly.

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/14751004/WeakAuras.zip)

**Comment by mrbuds** [comment]
I'm not able to reproduce the issue with your settings while dragging WeakAurasOptions frame for a long time, i lose at max 10 fps (95->85 with all max settings in valdrakken) if i move it fast but get back to normal when i stop

The code use for moving the frame do 1 api call when mouse button is down, and a bit more when mouse button is back up, but nothing special in between.

**Comment by brittyazel** [comment]
Yes, it's inconsistent like I stated before, but when it happens it's very, very obvious. I don't know what triggers it either. Perhaps the slow down comes from loading assets into memory in an on-demand fashion. That could explain why the issue eventually resolves seemingly randomly.

**Comment by mrbuds** [comment]
It look to me that if there is a problem the only ones able to fix it are Blizzard or your GPU's vendor with a driver update. WeakAuras doesn't do anything particular while windows is dragged.
