### ISSUE TITLE
Allow WeakAura Action to glow more than 1 external element at a time

### ISSUE THREAD

**Issue by brittyazel** [WeakAuras/WeakAuras2#4957]
**Is your feature request related to a problem? Please describe.**
One feature I use a lot of is the "glow external element" action. Generally, the way I use this is to have an off-screen WeakAura event listener listening for some aura or ability to be present or available, and then having this weakaura listener trigger an external element glow on the action button corresponding to that ability on my action bars. While this functionality works well most of the time, there are certain situations where I would like the weakaura listener to glow multiple action button frames, rather than just a single one. An example being a listener for _Divine Word_ (holy priest talent) glowing 3 buttons corresponding to _Chastise_, _Sanctify_, and _Serenity_ while the aura is active, and clearing these glows once the aura is removed.

**Describe the solution you'd like**
It would be great if the frame selector box perhaps allowed a comma separated list of frames and/or some other graphical means to have multiple frames selected for glowing. Likewise, the "on hide" section already has an option for "Hide Glows applied by this aura", which would seemingly work perfectly here without any need to change the wording.

**Describe alternatives you've considered**
The alternative method that I am currently using is to have 3 separate WeakAura listeners, each with identical logic apart from which button frame they trigger the glow effect on. It would be far nicer to consolidate the duplicated WeakAuras into a single WeakAura that could trigger the glow on each of the necessary action buttons.

**Secondary Request**
A WeakAura event "listener" might make for a very nice 'default' type of WeakAura. Right now, I am using the "Icon" type WeakAura for my listeners, making the icon 1x1 pixels and having it sit just off the screen. Having a specific "event listener" WeakAura type would be nice, as it could have many of the graphical components stripped out, as it could be an invisible element by-design. Not having to disable all of the visual elements of these listeners would save a lot of time setting them up, and would potentially be a (very) minor performance improvement should there be many listener frames. Just a thought.

**Comment by Boneshockx** [comment]
@brittyazel you can do this with conditions; create one condition for each element you want to glow
![image](https://github.com/WeakAuras/WeakAuras2/assets/6916881/c65e6459-1e32-42dd-893d-c3a3a0d0404d)

**Comment by InfusOnWoW** [comment]
Hide All Glows by this Aura hides Glows applied via Conditions too.

**Comment by brittyazel** [comment]
Oh, fair enough. That would do it then. I never thought to use the Conditions to trigger the glow and the Actions to stop the glow.
