### ISSUE TITLE
CodeRewiew lua error

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#4962]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

i have no idea what caused the error

### WeakAuras Version

5.12.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
3x WeakAurasOptions/OptionsFrames/CodeReview.lua:92: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@WeakAurasOptions/OptionsFrames/CodeReview.lua"]:92: in function <WeakAurasOptions/OptionsFrames/CodeReview.lua:91>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:510: in function `SetSelected'
[string "@ElvUI_Libraries/Core/Ace3/AceGUI-3.0-41/widgets/AceGUIContainer-TreeGroup.lua"]:185: in function <...ce3/AceGUI-3.0/widgets/AceGUIContainer-TreeGroup.lua:181>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
```

### Reproduction Steps

no idea how to reproduce

**Comment by InfusOnWoW** [comment]
The error is on clicking on opening the code review button and then clicking any of the other tree items.

The data that is nil there is the "scamCheckResults" table, but that's always initialized with an empty table even when the import has no custom code at all. Looking at our handling of that, there's not much going on there so I doubt we can be responsible for setting it to nil. Thus this is probably some other addon doing something fishy with ace gui frames, like a skinning addon. For that we would need a way to reproduce it.

I suspect one reason no one has reported the issue yet, is that almost no one clicks on the code review button, and that might not actually be that hard to reproduce with the right addons. So a test would be appreciated.
