### ISSUE TITLE
Eclipse direction 

### ISSUE THREAD

**Issue by mushymeterreader** [WeakAuras/WeakAuras2#4971]
Hey, I'm trying to make the eclipse boomy bar. You've added the power but I just found it was missing this in player/unit info. 
The photo is from a private server version of weak auras.

![eclipse direction](https://github.com/WeakAuras/WeakAuras2/assets/163530287/7be51fd7-3e02-4192-bad1-cd7613e9f267)

**Comment by InfusOnWoW** [comment]
The power trigger can be used for that.

**Comment by mushymeterreader** [comment]
It's for a little arrow to show which way it's going. We can have it moving around but you can't tell the weak aura to know which way it is moving around,
![arrow](https://github.com/WeakAuras/WeakAuras2/assets/163530287/68a47c3d-dd01-4a6d-b575-fbdcaae26518)

**Comment by mushymeterreader** [comment]
you could make it guess but there must be a back end thing in there

**Comment by mushymeterreader** [comment]
![weakaura](https://github.com/WeakAuras/WeakAuras2/assets/163530287/35c71041-9139-420a-8ca1-438b1f71e8f3)
