### ISSUE TITLE
Color Picker ain't working

### ISSUE THREAD

**Issue by Hexenmux** [WeakAuras/WeakAuras2#4972]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

when i try to pcik a new color for my wa castbar, i'm getting an error. The error is: libs/AceGUI-3.0-41/widgets/AceGUIWidget-ColorPicker.lua:73: attempt to call method "GetColorAlpha" (a nil value). The color isnt changing. What can i do to fix this.

### WeakAuras Version

5.12.5

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

- [X] Yes

### Lua Error

```Text
libs/AceGUI-3.0-41/widgets/AceGUIWidget-ColorPicker.lua:73: Attempt to call method "GetColorAlpha" (a nil value)
```

### Reproduction Steps

I tried to pick a color and the ui opened
I picked a color, pressed OK and nothing happened. It changed back to standard. I get this error

**Comment by mrbuds** [comment]
Error message is not long enough to identify which addon is the problem, but it's not weakauras who's to blame.
You ticked "tested with only WeakAuras" but that's not true.

**Comment by Hexenmux** [comment]
I can try again with only weakauras

**Comment by Hexenmux** [comment]
Lol now it works thank you very much
