### ISSUE TITLE
Get Unit Spec Based On Tooltip Info

### ISSUE THREAD

**Issue by Trickhamster** [WeakAuras/WeakAuras2#4974]
**Is your feature request related to a problem? Please describe.**
I would like to trigger a WA based on the unit's specialization.

**Describe the solution you'd like**
Tooltips (that appear when mousing over a player) now include the player's current specialization. It would be amazing if you could add another trigger to the 'Player/Unit Info' drop-down menu that returns the unit's specialization based on the info in the tooltip.

Cheers and all the best to the amazing WA team!

**Comment by InfusOnWoW** [comment]
The Unit Characteristics trigger already provides spec information via LibSpecialization.

**Comment by Trickhamster** [comment]
but only for the player unit? or am I wrong?

**Comment by InfusOnWoW** [comment]
yes

**Comment by Trickhamster** [comment]
would it be possible to extend that functionality to also work for any other unit (target, focus etc.) by checking the unit specialization in the mouse-over tooltip?
