### ISSUE TITLE
Cataclysm Beta DK Talent tree request

### ISSUE THREAD

**Issue by stsep** [WeakAuras/WeakAuras2#4985]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

as it noted in discord after using !cata there is no DK talent tree yet
any chance that we get DK talent tree before Beta runs out? so i can make my weakaura to support all 3 specs 

### WeakAuras Version

WeakAuras 5.12.6

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Deathknight talent tree is not exist

**Comment by InfusOnWoW** [comment]
The dk talents are now in.
