### ISSUE TITLE
Tracking cooldowns for pets stop working (since Season of Discovery phase 3) 

### ISSUE THREAD

**Issue by Xdembe** [WeakAuras/WeakAuras2#4996]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Trigger:Cooldown/Charges/Count stop working for pets (hunter)
Do not catch spell from name(IDs works fine), do not shows CDs even with right spell IDs

### WeakAuras Version

5.12.7

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No error oocured
```

### Reproduction Steps

1. Go to Trigger tab
2. Set "Spell" and "Cooldown/Charges/Count"
3. Try to type pet's spell with cooldown like Dive or Dash 
4. Get "Invalid Spell Name/ID/Link" 
5. Try to type spell ID (works)
6. Close WA use spell
7. CD dot not shows

### Last Good Version

5.12.5 before SoD phase 3

**Comment by InfusOnWoW** [comment]
I tested this with 2 different spells, that my level 10 hunter has access to:
https://www.wowhead.com/classic/spell=16828/claw
https://www.wowhead.com/classic/spell=24640/scorpid-poison

And they do work for me

In any case this sounds like a bug Blizzard introduced with Phase 3, so it's up to them to fix it. I suspect it has something to with the "Spell Known" checking that WA does, so you can try disabling that in the extra options of the trigger.

**Comment by InfusOnWoW** [comment]
I could reproduce it now, and the workaround is to enable the "exact spell id" checkbox next to the spell id input.

This is due to wow api being buggy on Season of Discovery.
