### ISSUE TITLE
Trigger only Debuff Magic that can be dispelled. 

### ISSUE THREAD

**Issue by cybersrs** [WeakAuras/WeakAuras2#501]
Hello!

I am playing as Priest Discipline and I would like to Purify those magic debuff types, like fear, polymorph, etc...
I tried and no success, so I was wondering if it is possible to trigger Only those Magic Debuff that I can Dispel, the ones I can not dispel, I do not want to get triggered. With old addon Power Auras I could select an option to trigger only the ones I can dispel. Weakauras also have this option? Will it need a custom function?

**Comment by emptyrivers** [comment]
Don't open duplicate issues. If you want help with making a workaround, then ask for it on discord.

**Comment by cybersrs** [comment]
It is kind not duplicate, mrbuds told me to make a new issue instead of two in the same. So I made this one.

**Comment by cybersrs** [comment]
I tried on #help channels, looks like nobody knows the answers, that is why I posted in here.
