### ISSUE TITLE
weakauras stopped working

### ISSUE THREAD

**Issue by spire02** [WeakAuras/WeakAuras2#5017]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hallo, my weakauras addon for wotlk warmane stopped working. None of the windows pop up and now i cant open addon setting window, for example when i type /wa or /weakauras in chat and click ENTER nothing happens. I have checked if my addon is installed correctly and it is , even further i reinstalled my addon but nothing has changed.

### WeakAuras Version

WeakAuras5.12.8

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
Message: Interface\AddOns\WeakAuras\WeakAuras.lua:155: attempt to call field 'NeedToRepairDatabase' (a nil value)
Time: 04/17/24 02:25:35
Count: 1
Stack: [C]: in function `NeedToRepairDatabase'
Interface\AddOns\WeakAuras\WeakAuras.lua:155: in function `OpenOptions'
Interface\AddOns\WeakAuras\WeakAuras.lua:240: in function `value'
Interface\FrameXML\ChatFrame.lua:4070: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function <Interface\FrameXML\ChatFrame.lua:3694>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

### Reproduction Steps

When i type /wa or /weakauras in wotlk warmane lua error that i patsed on top showes up.

**Comment by mrbuds** [comment]
Private servers are not supported by *official* WeakAuras.
