### ISSUE TITLE
Sharing a WA with someone on a connected realm results in "Error not receiving display information"

### ISSUE THREAD

**Issue by jungheeMW** [WeakAuras/WeakAuras2#5018]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When attempting to accept a WA on someone on a connected realm, it results in an "Error not receiving display information". The WeakAura itself is functional.

This error only occurs when trying to accept a WA linked in the chat window, from someone on a connected realm (i.e. Gilneas to Elune).

- It does NOT occur when importing via an import string.
- It does NOT occur when accepting a WA linked in the chat window by someone on the same realm.
- It does NOT occur when accepting a WA linked in the chat window by someone on a different, non-connected realm.

### WeakAuras Version

5.12.8

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Make a WeakAura
2. Link the WeakAura in the chat window. Make sure the other person is in the same party, and on a different realm connected to yours.
3. Have the other person click the link in the chat window in order to accept your WeakAura.
4. In the case of the sample WA provided below, a character on the realms (Azjol-Nerub, Blackrock, Muradin, Nordrassil) can be created to accept a WA linked in the chat window by a character on Khaz Modan. The error should occur then.

### Last Good Version

Do not know

### Screenshots

<img width="635" alt="WA error" src="https://github.com/WeakAuras/WeakAuras2/assets/134947146/48b195f3-337b-4523-9d85-9c9e7ef4e1ce">

### Export String

```Text
!WA:2!DzvqVTrXx866IQWq7)eN2qBiT1ns1cL)sPTUQviefjVU2KGCCcRDiLdfVZU74DNM1ZSmZSoXbUGVqVHWGaec4GpWjoLpc5qppYWNGCGpa5aN5nJxBABoSzM38M37379(9EJZulF38(59F27mI4XOnzjCp8YNX2JfX4Fuw4pE)T60rGLzocr9cz8TzeQ0Ts1gTQAp2JXI8z7tBUpjg7C80Tv9dWHCKNKWOIhylKiUmNfHsK5C7a)teMBGKtccWCXNvKNU85wY(X4HESUUizelGlIXrrB4V0Jw7erIlUhMkBM0Pd5GXTRuUzR2n3PsLQnBABozufZ9kuNfyLaEYnoc1hZpkrGBNAiNbPle5gAw1a1fVA8C1jbHskHguOzibh5pUjJjd173KiKZ892Cm4B7MBxTE9XZmR2go2u4Ri3iFSlaWwqyWxVA9TRTt9Hj00Wlxr1f(D1fv)p1ClDLmFZZvZRYRwqDj1YQRPElhvb1nvxwTO66oQRU641XOidIs4by1BRwj3r(eXttOqsThUeI2pEEKzDRjMFtMp(poZPqXbZPOOpbsTq2)7oDpmoUmGupPncQhHdf4OoMIO61a8kqYeosIdhbHPnoqxXEVfvxCmS1f5TxaNLq9F2LIZlXhiBlcrqb(XPuI4RAeA(0HX7Iafsxyrzu8WzhVYTeXZ9cwOIHFLjtMSNmr6uqzvENwBfVGrikrYatr82L4ldTkdBpDIVihG9nc)QXtyLFAkIo2C(ttessN(qaYzsi4AbcTASvJQQlYH4sRZiJI)hnFyAqqLXZvJtoSWhNG8HedQqRwVuSp1tJnY2NX93LJIhSB6IjaOhrqCJWoPX8l05ep)gnAu1UT1wTAT1M2B8HR3A8mx3KCi(QPr0JFj)Op1qR2ANw13Or1)ECqeB)AC8NNGPE93(C3zTs3Fs0Pp4y9NhPlSq9m7a9o9Th7MiLm6w9WCO5yKwCDmnqgE5J0RNgAd1BQml1CmW1)WPscnAofCw6nHg9B6HIWznWQviXBpkwiYAoPobwpVXBwqwcZdDdX6wUSwrmK))mwZoBhZeenAZXr6wCOBYvcwKkx0UBsKKKBOULJcDI8qBViKqSO6j54qpcWqJH1fTnRCS4iIVZqZgDcD183BL7DNr(eWSEGL6R1fqaNr8CC72h609GlXIW5oXyxOC5R7T9k6kaZhH)t1tw8pDmT8ZSAOLwdnegtOWaoQhUTE8fi5tUHZ5EtNR5CtN5DIZp7gTzq5djz8vx5dE4kV)dTeGWIksP4EXaIg0jcFGH0yhdJl7dChWHL91CzSp2Ft0bHNoHAuJdtB01t3MvSRwTXRQjHgoIBAL1kzPhSperjDnSHhOE9AWuOBFmgjWnLCt9)8J9tjlMGGlWWD8fd06OTH62wDreQ5IQ(NxDO6luFjS8nEvjdM(eGJECLEe8gGLUYzxGWpy6qJlnvhDB5Jicee0(HUGEDib5SoKX6Mzm07dr6wXMNqYnsY86nzI2vY810vi(Xlx9aaOKUadbfvag6uOcItqbuCHELIZdzKkPUbMmcJ(G8kkkoeL1EF9GJSh1rNfHea0JNTucX)OkbFCPAL(07V7DdbAL2DqvgMq6f))FjFTB5cswbeLctg9Wf6IEk48PXKqTVZiDYZqMfRw02le7Txn1fYoONgGqWAjcz7B3dfLGZ6AowS0dafudvFN67ZY9cr0aSyPIQVVw81HhweOa80bSaGK63Cs3RUnpvH48vqWyp4nJBn7HPJNEzDvD8gnA2QCJkvBxz9YTIVXRy4zxAMLheZ1CwzFlarYIQVfa5RLcs1pOHxh1pfp))5UcmAH(Se1VaCIFMV76BaVvAhVWuhPHEBIq)6SJ6hbk4lEWWBnnYu)Q63oIqNGc9eHtaCeWbDN8ZtwD5ZC28c37V2DlT27MV3F94)n
```

**Comment by emptyrivers** [comment]
> click the link in the chat window

which kind of chat are you using? party? raid? guild? (battlenet) whisper?

**Comment by jungheeMW** [comment]
Whisper and party are the ones I've tried, and both do not work.

**Comment by emptyrivers** [comment]
It's far too late in the night to find a ~~victim~~ volunteer to troubleshoot this, but I suspect I have a fix: [try installing this build of WA](https://github.com/WeakAuras/WeakAuras2/actions/runs/8717408014/artifacts/1420916234) (on both ends), see if it helps.

**Comment by emptyrivers** [comment]
Right, so this is probably [blizzard's fault](https://github.com/Stanzilla/WoWUIBugs/issues/535). With any luck, they'll get around to fixing that regression and we won't have to do any workarounds, but who knows with blizzard really.

**Comment by jungheeMW** [comment]
Hmm but the link seems to imply that only whispers are affected, and not party/raid chat? Should I test the latter again?

**Comment by InfusOnWoW** [comment]
Where you post the aura does not affect where the addon communicatin happens. So yes please test.

**Comment by jungheeMW** [comment]
Tested again to confirm. Works fine in party/raid chat on non-connected realms. Fails in party/raid chat with connected realms.

**Comment by InfusOnWoW** [comment]
I tested the change that rivers proposed and can confirm that it does indeed fix the problem. So I have to assume something went wrong in your testing. The next release should fix this problem, and sharing simple auras should work. If with the next release sharing simple auras doesn't work, please report back.

(Note that there are other problems with sharing bigger auras atm due to changes blizzard has made to addon communication.)

**Comment by jungheeMW** [comment]
Thank you.

Sorry, I did not test the change from emptyrivers as I assumed it was a Blizzard issue. But I am happy to know that it will be fixed in an upcoming release.
