### ISSUE TITLE
No Classic or SOD version?

### ISSUE THREAD

**Issue by Velarax** [WeakAuras/WeakAuras2#5020]
**Is your feature request related to a problem? Please describe.**

I noticed a lack of updates for Classic and SOD

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SpatenLa** [comment]
why do you think there is no Classic/SoD version. it exists, and is infact the same thing.

**Comment by Velarax** [comment]
Because to some extent, the code is different and I didn't know whether or not W/A picked up any of the Rune auras like regen, for instance.  It's not as stupid a question as you make it sound.

**Comment by Stanzilla** [comment]
> Because to some extent, the code is different and I didn't know whether or not W/A picked up any of the Rune auras like regen, for instance. Blizzard does periodically break addons, so I thought it worth checking to see whether there would be any chances. It's not as stupid a question as you make it sound.

The latest release is from last week, if you're missing anything, please make a new issue. Otherwise I'm not reall sure what you are asking for.
