### ISSUE TITLE
Almost KR locales are updated recently

### ISSUE THREAD

**Issue by Elnarfim** [WeakAuras/WeakAuras2#5024]
I've translated so many strings and corrected others recently
Please updated them to the future version

**Comment by InfusOnWoW** [comment]
Those will be picked up automatically with the next release. We do regular releases whenever a decent amount of small fixes has accumulated, or any important change has been merged. This falls in the first category of a small fix. Currently there isn't really any other reason to do a release, thus we won't immediately do a release. The next release will come at latest on the 30. April, thus in any case it won't be long.
