### ISSUE TITLE
Allow Charges/Stacks Count Condition for Weapon Enchant Trigger (e.g. Rogue Poisons)

### ISSUE THREAD

**Issue by RadicalRoy** [WeakAuras/WeakAuras2#5031]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Bugs:
1. Enabling a Condition for remaining stacks of a Weapon Enchant trigger is not an option in the list. I believe this is a bug because "Remaining duration" is an option in this list and they shouldn't be notably different
![image](https://github.com/WeakAuras/WeakAuras2/assets/19538210/93322dba-1c6c-45cf-8018-c7ecafdfb033)

2. Another bug I noticed when I was also able to create a Trigger for Deadly Poison III with a Stack Count toggled... but it seems this property is completely ignored and does not actually affect the trigger.  [626 is the id for the Deadly Poison III (rank 3) item effect]
![image](https://github.com/WeakAuras/WeakAuras2/assets/19538210/0ebe874b-a2ea-4c6c-be26-7a5420932b3d)

My guess is some conflating of "stacks" and "charges". For instance, Combustion will gain "stacks" as a fire mage casts spells and increase the counter on the buff. Poisons however do not use "stacks" in the traditional sense but rather "charges": these do not show a counter unless you mouse over the buff icon.

My ideal scenario is to specify a Condition for when the Stack/Charges Count < 30 to display the Pixel Glow alerting me to refresh my poison charges.

Please fix the above so that Rogues can use the Stack Count option for poison charges. Thank you

### WeakAuras Version

WeakAuras 5.12.8

### World of Warcraft Flavor

Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create Icon WeakAura
2. Set Trigger for Item > Weapon Enchant > Offhand
3. Specify Weapon Enchant 626 (Deadly Poison III)
4. Specify Show On > Enchant Found
5. Using Deadly Poison III on Offhand now correctly displays the icon
6. *Bug 2 from description*: Setting Trigger "Stack Count" with any <, >, <=, >=, =, != symbols and any number does not affect the Icon displaying. It will always show (even if you put Stack Count < 0 as in the screenshot).
7. *Bug 1 from description*: Further, there is no option in the drop down when creating a Condition for the Weapon Enchant Trigger to select the Stack Count as an option

**Comment by InfusOnWoW** [comment]
I don't have a rogue to check, so can you run this command in chat: "/dump GetWeaponEnchantInfo()", and make a screenshot of the output?

**Comment by RadicalRoy** [comment]
As requested @InfusOnWoW 
I used `Crippling Poison II` Mainhand and `Deadly Poison III` Offhand (Crippling does not use charges)
![image](https://github.com/WeakAuras/WeakAuras2/assets/19538210/207dd065-9c5d-48f3-ab17-21c71d1bf7b4)

**Comment by InfusOnWoW** [comment]
That looks correct, what does /dump WeakAuras.GetOHTenchInfo() return?

**Comment by RadicalRoy** [comment]
Here's the result of that command
![image](https://github.com/WeakAuras/WeakAuras2/assets/19538210/faa06955-862e-4ae4-b605-03cdfc1432de)

**Comment by RadicalRoy** [comment]
I will add that thanks to your pointing out these methods 🙏 , I've managed to implement my desired condition using custom code:
![image](https://github.com/WeakAuras/WeakAuras2/assets/19538210/77ef8f5f-7076-4325-a446-98d088503bbd)

I spent some time looking through the Lua code in this repo and I think the `Stack Count` check is just missing for the weapon enchant trigger (should be around the `remaining` or `triggerRemaining` comparisons in `Prototypes.lua` near line 7227). Though I'm admittedly not very proficient in Lua code.

**Comment by RadicalRoy** [comment]
Confirmed the fix is working for the trigger, and the condition option! Thank you @InfusOnWoW  🙏
