### ISSUE TITLE
Add a Global Mute to Weakaura / Weakaura Groups

### ISSUE THREAD

**Issue by intentionaltypos** [WeakAuras/WeakAuras2#5040]
**Is your feature request related to a problem? Please describe.**

I find it incredibly distracting and frustrating whenever a weakaura makes a sound, which seems to have become the default with the rise of custom sounds / text to speech as an option.  

I've tried to manually delete sounds whenever a pack adds them, but with the options spread across actions, conditions, and various custom options it has become increasingly difficult manually silencing each weak aura.  This becomes even trickier as each time you upgrade a weakaura, many of these deleted are recreated and it becomes a chore to silence pack every time you upgrade. 

I'd love if it there was a way to globally mute weakauras, whether that is across the addon or for specific weakauras.  

I find it particularly strange that weakauras (the addon) can tell me that a particular aura makes sound, but doesn't let me easily silence it. 

**Describe the solution you'd like**
I'm really open to any solution here, such as a global `/wa mute` option, the ability to just click on the sound / TTS icon under a weak aura to mute it, or a right click option a weakaura to mute it.  

Bonus points if this persists through weakaura updates, but if it becomes a simple right click / click, that's still way better than going through hundreds of weakauras disabling actions and conditions.

**Describe alternatives you've considered**
I've tried manually managing this, but as more and more weakauras leverage things like text to speech it becomes harder and harder to the point where I can't even use most public weakauras, or I just stick to older versions of packs that I have already silenced.

Apologies if this has been asked, tried googling for it but wasn't able to find any references.

**Comment by mrbuds** [comment]
> I find it particularly strange that weakauras (the addon) can tell me that a particular aura makes sound, but doesn't let me easily silence it.

Note that the icon indicating that an aura or group of auras has a sound is clickable, and will show the first aura of the group with one, with condition or action tab open (maybe you knew, just pointing it out in case you missed it)

**Comment by Stanzilla** [comment]
Imo should be handled by default options when a user will be able to override values of imported auras (future thing we want to do)

**Comment by intentionaltypos** [comment]
> Note that the icon indicating that an aura or group of auras has a sound is clickable, and will show the first aura of the group with one, with condition or action tab open (maybe you knew, just pointing it out in case you missed it)

I do know!  It's helpful just things remain very tedious when dealing with some of the larger imported auras.

**Comment by InfusOnWoW** [comment]
So I didn't add a "mute" button after all. The complexity of having another layer to the sound settings didn't seem warranted to me.

Instead there's now a menu on clicking on the sound icon, which allows for removing all sounds from a group (and its children).
Obviously those come back when updating, but a) removing them again is pretty quick and b) update should ideally take into account that all sounds were removal locally and not readd them.

**Comment by intentionaltypos** [comment]
I actually saw that in the recent patch notes.  Seems like a great solution.  Thanks for the feature!
