### ISSUE TITLE
Cata Classic - Trigger for Ranged Weapon enchant (rogue poison)

### ISSUE THREAD

**Issue by theoriginalmre** [WeakAuras/WeakAuras2#5043]
Cataclysm Classic provides Rogues with the ability to put a poison enchant on their Thrown Weapon (ranged slot). Please can you add a trigger for:

Item -> Weapon Enchant -> Ranged Weapon

**Comment by InfusOnWoW** [comment]
The api: https://warcraft.wiki.gg/wiki/API_GetWeaponEnchantInfo returns only information on main and off-hand enchants. I'm not aware of any api that handles ranges weapons.

**Comment by InfusOnWoW** [comment]
Apparently it's supposed to be there on cata, can you with no poison applied, except on the ranged slot run this:
/dump GetWeaponEnchantInfo() and post a screenshot of the result?

**Comment by theoriginalmre** [comment]
Result with Thrown Weapon poison only:
[1]=false,
[5]=false,
[9]=true,
[10]=3499740,
[11]=0,
[12]=7
