### ISSUE TITLE
Load bug with talents

### ISSUE THREAD

**Issue by Askhay641** [WeakAuras/WeakAuras2#5045]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Very often when change spec WAs for talented spell with load by talent selected dont load until change talents.
https://outplayed.tv/media/n7Nlnn clip with spec swaping back to back (look at class WA)

### WeakAuras Version

WeakAura 5.12.9

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create any WA for usable talent (Ex: Ray of Frost/Arcane orb) and set it load by talent selected
2. Change spec

### Last Good Version

Before DF S4

### Export String

```Text
!WA:2!DvvZUTTrq44O2AaHIcBLub1ICqOhmSdceSvQvIp0dMosPPq2wGunWTOaIljhrUXu7YU7sllFj16sZz13a9iOhbFONxi0R9so0ha)e0zxjzKeEqCNHZ8n)9TJwRvPbLIkf9UAtPHCMhpxecp6EtdZLk(GUWLQSFRFolur5ST3Pyv8X(tkpKKwnKNZuv)HQVeuVsbdoYiU9tB8Sdo4jvz00NuvjYHDw4Hau5c22wxwceWIeJoTFFjOwBgHfMWfD4uMk4OMN0TP78qopnIpK5nKMb(3SsSzumKii2Cs2WvQicvrhkJQkg0hFjtkowjOXXGqEYwILhF3dDvOtN7qYv8SnZLqVyGbcAOxcF4Pm)5FK4uj(6W0HKrY3lZdGlaMQJa6tV01RtZ2TNzaWytCyK)ezgKMEczauPq1)1rnkdCTQUfTQ5LyQ6zKEvuItoMMbzPKrGqKZSWQ3W1(o7BoAzfwTJGhlaPS62wh3j7bMWbgK6DxS8NlasQ3hg652S6odglxewzrxgkllExP4L3hlLz9o6qVU986EOB3PrqaQSlM7IFSz7oT(52tmOzBA(JJYfetdV0EtWb4IwAzDj9dMfrLVXYqUaQtyJY2Kyp3DHnhZJGc3IdvqWiPVghjii)1TNdq2Hy2fQCnWMmHWOdSbOHUylDfhgNb3aej4PealwLS(8vPqpt)vibKVgjhBSXK066odiug6RUU(PRR)E9(6g4XV8t1GfQKOmyHSOlwKqRpfBmUqSHr94Y6kZrXaSUJfiDn6)MhNYh2sa)EoWch15Z2Tw99Dm6sUbBrVepCepLlsgB0zsM5b5kfNDkcpoQTU3nHgEodNPfMze)LL8(jXR8(NkGp3yeFXYcTG9JE4nnOWuZX22oXxRRiW8ZOWc1zFiuTPym20ATdxebIKGeGgNO6851pO2Z23jLtI(BlpjdubeLkfsSdAdzeTwHrJPk7oipvrlxzTdoZ3XmOkR7uED)PwkH1KfEfMsKYehj9kaTO44LeWWKSs395EewKvP)7)y5TcKuwCkCnI91(U2pAIJZXh(YM(IRqoasEVF2giuhg9gCNeebrhtUmjqA3ufqhKXfk3W7AGZOS(CXcQ0wZWJHqtdHx6NvHgZ4c40m7IdR2Mcbxi9nCyZDYxHukXEno45pB3D)0GszjtfwgIza7y2worcP9TBS0FXCCTcU)Aj4fRNtJMTBB(2P)6j7SZEhpRVaVaICzIISU7qAKkz5abVVy381YyqhIW0zDjPzjKcoxX5d6uazBzpC1YpZk5xqLKGuikrVH)ufpCjjUYA)j77Or34sgvL3VAlbxQcKWa8ZU7vZGIzKSAhdEXeV6b(3(bH3uzbEh52S5j6y)aSe7tJlkOmtea)65I07lUCjDBQ5(h1wUF7wUHjq45T0FvHXxqeut6nLZwfl3liP5qHaRrYhVL(610V1XS9Sb6H(T6)qFDbrycHfdiy6R9hNj44LC1i9ZhVQ09FF2Y1Il(BQh)O7D)sYG9RTx9Ahu6I)5S)p
```

**Comment by InfusOnWoW** [comment]
I have tried reproducing this and can't. I do assume that the problem is on your end, as if that was a wide-spread problem, we would certainly notice that in the bug reports. My best guess is that you have some undiagonsed lua error, that is interferring with the loading of the aura.

**Comment by Nokramx** [comment]
i had a similar issue after updating the talent loadout ex addon and i see you are using it aswell. i don't know why but after disabling said addon it was working fine again.
