### ISSUE TITLE
Cooldown Progress (item) can show durations when not on CD

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#505]
**Describe the bug**
The trigger will fire occasionally and very briefly with a duration of `0.001`
When this occurs, GetItemCooldown returns a 0 for the third return 

**To Reproduce**
Make trigger = status  - cooldown progress (item) - Healthstone - show = on CD
Get in to combat and use a healthstone.
The Aura should flash whenever you cast something.

**Comment by InfusOnWoW** [comment]
Should be fixed in the next release.
