### ISSUE TITLE
Texture/Text Color Not Saving

### ISSUE THREAD

**Issue by dascobax** [WeakAuras/WeakAuras2#5050]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Changing the color of textures or text. The color is changed, but not saved. Clicking another tab an then back on the Display tab shows the color has reset.

### WeakAuras Version

5.12.9

### World of Warcraft Flavor

Wrath of the Lich King Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Go to Display, click the color square.
2. Choose any color other than white and click ok. The color change will show in the selection square.
3. Click any other tab and then click back on Display.
4. color has reset

**Comment by mrbuds** [comment]
> Tested with only WeakAuras

> I got this issue with only WeakAuras enabled

Are you sure?
