### ISSUE TITLE
Pet ability CD WAs not working on SOD

### ISSUE THREAD

**Issue by scottw89** [WeakAuras/WeakAuras2#5053]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Link to discord thread: https://discord.com/channels/172440238717665280/1235997243664896000

I have been unable to show a cooldown timer on pet abilities in SOD, even when unticking 'known' and using the exact ID.

The same WA works perfectly in the cata client.

### WeakAuras Version

5.12.9

### World of Warcraft Flavor

Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Create icon WA
Trigger: spell ID 23110
Disable Spell Known Check
Show: Always
Use pet ability (e.g. dash) - no CD shown on WA

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/25009964/b3194b7c-e9a6-408f-9b27-3c58659eecaa)
![image](https://github.com/WeakAuras/WeakAuras2/assets/25009964/51bd74b1-366d-424d-951c-bef4a3395fa7)

### Export String

```Text
!WA:2!DrvZUTTrqyRQgudDOWw11agihmcqdAtDDBCBsl6nrzPe3il5ssx7KlsljhrU1u7YU7sllFl6KpR(gOZ9KEe8tabrFc8HESh8tqNDjLAs0bQz(Mz2D(5B2kTRpQEq9GBE8CQpN5Wtf(WdxtCvVHdLGQIysPWccZpIloHtzkVMT662Yo3NZJd4JzoJPjWGBxQ2kieIS0h3GPkbnmeeYp9XIsXB20wji(xyrsv8KntLq)qGbcQVteFCp2G83tDUe)Rr8yYePvkJQ8sIjtaX8aWlD4q3jjG4LT6Cs7t7yPqfBzcehFNm1dUeykh0h6vl63SHJBFh3g2U2g8KDAwMS7EIGhkaPC3V0rh6xnZCcDjJG1Ft7CbqIDwcyDirgLRZ4v(myQr8OazTKT0wOHmUamH8kgE(dUhrBDfXx5u44Gvj3jcatoBNtA1PZmDSM(YaBgEUYAZszLDSAjBIHtVeCl0pMha)1A3JdcqWiX)g2EPC2FExszLumeFYdx7JMry0refA952sfrOAFlqKGJsaSqv0NKTLfJZG8GuHXR(6wOqc4Olqov7QUbNTN1icL1o7RXaY2l7BY2p7BZ2ZBiLrLrFimozKeL(aHO5yPAdH4jl)5TZ2khv9WsmuWtzb3SvsDfCLQVmIGtIZljAj7yanFgYfy63xwkKT3Sv2E0xit24DcVjpMl(LkvQu9UcuiEOHSA14u3EjFMbut509d)ZObQiRgO69fxe9kiWa(28cI(RltNBn2)9uPIoCs2dMl4kSYCrqRU962kBlbwuAFMBC03KgvXFZkRaKSTrBb96D)1usa2vi766(Ef(YBk3GnMlcotqsMEwPqrcCjvs9IHbL187SmMS5rD72YUVvpx3EhBF0lEPB(QR2HEnStzfD(7DpARMTNEN625OUT(N8Wy(42c4psbM)Kt(4VB)dEwr1PnCR(ZHL0KQt1A6OZ9svkoR3LGaxlNRH7yOwF(cT8YsBMwP5QwZTiz)flrImEUk5mNCe1)cgYKRAc0XNedvT0IrgGou04MMBZc7sGiYlcOHrQ3AfZjbT9uyam122JsJv0Aw4kQ)2zE1S9JjsPwYsIngTqYgyU0iqpFHai4yYvrFieLfnxyiXMLH1tQJ2x(8bUlAJ8HbhKsdw8Mr)q3xL86VV7pEXckRGZIHvlh5D4aOxIwtwtO3MrHNN9KAzpTMfUgPWxpw(8PMBDivsWXDqK11C(Ok2K4Kis15kU)LfB7RV3)(iAWbDHX3xmDBlWxn0jONtt7wT6UyOga30rgxv7XgQT9)Zo9Wv8H0WAcktFIq09xaqsdDNszRZ6O56hbOfz80L52GzR2RYEqDP3Z2)PhS)pv)Y)(8)7d
```

**Comment by InfusOnWoW** [comment]
There has been another report about the spell cooldown trigger not workin in SOD for pets, https://github.com/WeakAuras/WeakAuras2/issues/4996, but I couldn't reproduce the issue back then.

Nor can I reproduce the issue now:

https://github.com/WeakAuras/WeakAuras2/assets/12950521/913c1df1-b7bd-4cb1-b80c-3f0c6f4dc6d9

As far as I can tell, we haven't changed anything in the spell tracking recently so this does look like somthing blizzard broke in season of discovery.

Can you check post a screenshot of /dump GetSpellCooldown("Dash") and/or /dump GetSpellCooldown(23110) while Dash is on cooldown?

**Comment by scottw89** [comment]
@InfusOnWoW your example is a GCD and not an ability CD? Did you try with Growl?

![image](https://github.com/WeakAuras/WeakAuras2/assets/25009964/f99e2ede-8bd8-4f3e-b9a3-791111f8ff48)


The dumps are in the SS above

**Comment by InfusOnWoW** [comment]
Right, that's the problem, why I couldn't reproduce. I can reproduce it now, and it is an issue in the api blizzard provides. GetSpellCooldown with the name is supposed to return the cooldown of the "right" spell. The workaround is to enable the "exact spell id" checkbox next to the spell input. That switches WA to use the spell id you entered instead of trying with the name, and then the cooldown tracking works.
