### ISSUE TITLE
Trigger for different GCDs, such as evoker hover and druid shapeshifts

### ISSUE THREAD

**Issue by Zeilar** [WeakAuras/WeakAuras2#5054]
**Is your feature request related to a problem? Please describe.**
I have a bar that tracks GCDs, and I'd lke a streamlined way to include all the different GCDs, such as the ones in the title. They are not on the global GCD, and therefore not really trackable unless you add exceptions for every single spell that incurs these GCDs.

This basic WA (which simply tracks GCD) doesn't trigger for e.g evoker's hover spell: [https://wago.io/3YuvC-bXu](https://wago.io/3YuvC-bXu).

**Describe the solution you'd like**
New trigger(s) for these different kinds of GCDs.

**Describe alternatives you've considered**
The only alternative I've found, even with the help of the Discord community, is to track e.g hover and check the total duration of its cooldown. But you'd need to do this for every single spell that can affect these GCDs.

**Additional context**

**Comment by mrbuds** [comment]
Please take your time to rewrite the ticket, with better explanation and examples of what can't be done with existing triggers.

**Comment by Zeilar** [comment]
> Contributor

Not sure how much more there is to elaborate. There is no way to properly track misc GCDs (i.e not the global one).

I mentioned a workaround in the ticket, other than that I see no other way to track it. And it's a very nasty workaround.

**Comment by InfusOnWoW** [comment]
The terminology around global cooldowns is incosnsitent, but for WA purposes the global cooldown is a cooldown that puts the aptly named https://www.wowhead.com/spell=61304/global-cooldown spell on cooldown.

Hover does not do that, and that's why it isn't displayed by the global cooldown trigger. Hover does apparently not put any spell on cooldown, as far as the GetSpellCooldown api is concerned.

**Comment by Zeilar** [comment]
> The terminology around global cooldowns is incosnsitent, but for WA purposes the global cooldown is a cooldown that puts the aptly named https://www.wowhead.com/spell=61304/global-cooldown spell on cooldown.
> 
> Hover does not do that, and that's why it isn't displayed by the global cooldown trigger. Hover does apparently not put any spell on cooldown, as far as the GetSpellCooldown api is concerned.

So how would one track this, is it possible? If I look on my actionbars, I can see every spell that's bound to the global GCD, go on a small cooldown. Whatever is going on here, should surely be abled to get tracked somehow, or?
