### ISSUE TITLE
Unit Characteristics (class/specc) not active when other trigger is already active

### ISSUE THREAD

**Issue by Breakerzeus** [WeakAuras/WeakAuras2#5057]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hey there,
I just found an issue with unit characteristics, especially the class and specialization triggers.
I made a test WA for that (link below).
The aura is set up like that:

- icon WA
- Any Triggers
- Trigger 1: Aura --> Arcane Intellect
- Trigger 2: Unit Characteristics -> Smart Group -> Specialization (all mage speccs)
- Condition 1: when trigger 2 active, then glow 1 visible.

The expected behavior is that when I buff myself with arcane intellect, then the WA should show the icon AND also the glow, since trigger 2 should be always active since I'm a mage.
But what actually happens is that when I buff myself with arcane intellect, only the icon appears, no glow. If I cancelaura the buff, then a questionmark icon appears AND the glow is active.

Another test: if I set the activation mode to "all triggers", then the icon only is displayed when I buff myself with arcane intellect. So obviously both triggers are working properly at the same time.

So my guess is that there seems to be an issue with the condition not getting the information from the trigger 2 that it's active if another trigger is already active. but it also could be that trigger 2 is indeed not active when the required activation is set to "any trigger".

BTW: this also happens if I set the trigger 2 to Player/Unit Info --> Health --> Specialization (Smart Group). That was the first time I noticed the issue since I need this for an actual WA I'm working on.

Test-WA: https://wago.io/yumqABGVB

### WeakAuras Version

5.12.9

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

import test WA or create a new WA with buff trigger (that you can control) and a class/specc trigger. Also add a condition that does something noticeable when the class/specc trigger is active.

### Export String

```Text
!WA:2!DvvqVTrruyBmvG2CGg32O2qpefeHsLiIeObsHwHxx7MaU2H1BAkGq2ZU7yptZMz2oZS2ovcHQVqLGEjCVh8boXj)lOk)cgzXVGCGFarCQN4nZ6KM29WQ59M37nV3B((Et(Qf3RyuXONU0iAiN1KNkcXxn3euQIWfnsuuot6i2VrNosSAJVr8Yx(IC5YngXcH93ItzQGYvQ7xXBsiNhhX7ZA2NMGBF4jIvI6IjUMG3EOsq72flKpFjX0L)LRA)eShkvGw9qZFzcooMgjN3DLp)gR7H7HHtydmkwr8yO9WsNHwt2ms64MYOQGKy0(yXrY0aRXnt70HoyCRYLA63QPFjp)JtL4kdqHQMzo2(uB3sGbB9AUvLA1gfHdax9H0rSrLABvD7AhKYMMMolPDE6CJGa1co9WnJihzwt7Y4cCtCCNmzuGKlcUhpc3(m7FhmkICGromgjLKGSqmN3EPXk6ApP9V2(xARNx)(hz3N2HgIm9DNKIVkOMwGnWhtSnJwCiprkUy(I3EOXmtVOT(Y6ROFVKlUniSqzcsavnwqLkAOuFbVUcEAsYCNj1Os4IHHbRIi6IobzbF(IRyR1mP26lPNZZMBJVtLs(B8D138UB4RN1rpJ(c6R6moIkFyklur7HxfX2pPyyQuX3ZpR5vJ3LgM8rDSwWzxt9XolaFcSkvWwq9tR8ZwzhmlYXXjzwKnqtD2uZ)DUJbCgwWqX3hqpqm(ZJ3fJtkzAKkptZICaIr3Z22wZtQqcv1dXijUPsGzDvK3rpJlJZWtIamMXQwgCNqIHYpso0yQ5MxVU7EikRQ(lbh0RRVP(R0FTE9GougvsEt1aKrIuMaIjJamLhURHUCZ50ZmbedqH7A64SONEXKIk8avljbbCIhKXMYNCfRs7VoCbK(TKtxOx)Gt3BXpuMC(Z4EzEmx8T5ZNVWrzAb8NLj6wAB)gjxWQeiWCt)iChAKI4wcepo7GOdWrwLpzsgl(hMMohA3)HWvhTZ(6ZnsWvqL5dkDR3OEf9mcOOm2mYAyOnnkaFhmTcyQKZxvqF8cFFkkc6kOf89FTc)KtAIvxFUiAhbkz4otxKLa9OsAqmU90A(mtAsMDZ61R41YTHVFJ75zaHto9OBsFm(ktROh8ANJzxlTUX2(12SEL)Ds3yE)Qc8JsXSW936T)0Lx9gzvNzJdn)UZuysHHgjJ3tcsvkoRrpSag4mYOUMfADPXM1NuAhyekFAR5qGgD3t0qSwEAYzJmHgUldlLfSo2mefJl4AwsSkQrHnN1EAUqxcliafL2LOEIBmhfvnqboWuZP)ahxdBWSq)jzIqdXSi58qoukYCVIJWr3dnG8MQOmYiHf8AjbVRxFl(y1uA04WO()y5b0vACTWXuwg60mC6OebVRaY8S3mU(vZ9wMPngcWA6VWrFBhxG0OCCFmNVxEpuCcbvyKIh2lJcF58)gBrAuYS7uQvzZSfy6Cyyl30U2XELN(8bW)bcoU94ocy6pqNbyvHJZUMRAuzY4GML9QuPU3RGKbaVUdTRJGYmNhMKCXtEqYaOH5EiaJfredM(Y2lE0Z)p4HTCJmdeO2Yy(L8cj4WDV)I8KfV1TcScYRVM2PWWEib1ebxjH33RhkofxOQ25C6Fx)h6NviZJxjlcjiwxmes9ZApe6CaAuTVzMXYF2YMl3HNKDTp4u6S(CfLb3y5vwD51l27FEW)d
```

**Comment by InfusOnWoW** [comment]
Conditions work per clone, which can be a bit counterintuitive when using cloning triggers.

The Unit Characteristics trigger is the wrong choice for what you want to do, you want the "Class and Specialization" trigger.
