### ISSUE TITLE
Copy display setting change trigger2 spell if the source spell is not known

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#507]
**Describe the bug**
- Make 2 icons
- For each, make 2 triggers, the 2nd trigger have to be a cooldown progress trigger for a spell this class know
- Log on another class
- Copy **display** setting from one icon to the other one

=> trigger 2 spell was changed

**Do you have an error log of what happened?**
no

**Which version of WeakAuras are you using?**
git master

**Was it working in a previous version? If yes, which was the last good one?**
i don't know

**Comment by emptyrivers** [comment]
What specifically does trigger 2 get changed to?

**Comment by mrbuds** [comment]
it copy the spell name

**Comment by emptyrivers** [comment]
Ah, I see the problem.

**Comment by InfusOnWoW** [comment]
Fixe by emptyrivers.
