### ISSUE TITLE
The War Within Issue dump

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#5073]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Ticket for War Within Alpha issues. I will edit this as i find problems. Other can use the comments i guess

### World of Warcraft Flavor

Beta (WoW 11.0)

### WeakAuras Version

5.13.1-6-g7743d38 

### Lua Error

```Text
287x Lua error in aura 'Test': Trigger 2
WeakAuras Version: 5.13.1-6-g7743d38
bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))
[string "=[C]"]: in function `GetSpellName'
[string "@WeakAuras/WeakAuras.lua"]:6199: in function `Check'
[string ""]:78: in function <[string ""]:7>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:687: in function <WeakAuras/GenericTrigger.lua:627>
[string "@WeakAuras/GenericTrigger.lua"]:1039: in function `CreateFakeStates'
[string "@WeakAuras/WeakAuras.lua"]:4508: in function `UpdateFakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:4484: in function `FakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:3179: in function <WeakAuras/WeakAuras.lua:3034>
[string "@WeakAuras/WeakAuras.lua"]:3199: in function `Add'
[string "@WeakAurasOptions/LoadOptions.lua"]:757: in function <WeakAurasOptions/LoadOptions.lua:745>
[string "=[C]"]: ?
[string "@WeakAuras/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@WeakAuras/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@WeakAuras/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...faceWeakAuras/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@WeakAuras/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@WeakAuras/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-EditBox.lua"]:70: in function <...ras/Libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:67>
[string "@WeakAuras/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-EditBox.lua"]:114: in function <...ras/Libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:111>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))"
```

### Reproduction Steps

Make a unit info -> spell cast trigger. 
Don't think this matters but i made  a nameplate trigger and pasted a spellid into the name field

**Comment by mrbuds** [comment]
fixed with https://github.com/WeakAuras/WeakAuras2/pull/5071/commits/e02ebd7022f23f5c5a1882e7667f02fe05406a7a

**Comment by Jodsderechte** [comment]
### WeakAuras Version

5.13.1-7-ge02ebd7


### Lua Error

1x bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))
[string "=[C]"]: in function `GetSpellName'
[string "@WeakAuras/BuffTrigger2.lua"]:3095: in function `Add'
[string "@WeakAuras/WeakAuras.lua"]:3121: in function <WeakAuras/WeakAuras.lua:3034>
[string "@WeakAuras/WeakAuras.lua"]:3199: in function `Add'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:2027: in function `ImportPhase1'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:2037: in function `ImportPhase1'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:2037: in function `ImportPhase1'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1640: in function `ImportImpl'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1609: in function <...aceWeakAurasOptions/OptionsFrames/Update.lua:1608>

### Reproduction Steps
I tried importing https://wago.io/SL-Dungeons will investigate further tomorrow to figure out what exactly the issue is.

After failed import and reload i got

### Lua Error
1x Lua error in aura '[TOP] 05 Manifest Death': pAdd
WeakAuras Version: 5.13.1-7-ge02ebd7
Aura Version: 1.1.28
bad argument #1 to '?' (Usage: local name = C_Spell.GetSpellName(spellIdentifier))
[string "=[C]"]: in function `GetSpellName'
[string "@WeakAuras/BuffTrigger2.lua"]:3095: in function `Add'
[string "@WeakAuras/WeakAuras.lua"]:3121: in function <WeakAuras/WeakAuras.lua:3034>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/WeakAuras.lua"]:2655: in function `AddMany'
[string "@WeakAuras/WeakAuras.lua"]:1264: in function <WeakAuras/WeakAuras.lua:1232>

---------------------------------------------------------------------------------------------------------
2x WeakAuras/WeakAuras.lua:4401: attempt to index field '?' (a nil value)
[string "@WeakAuras/WeakAuras.lua"]:4401: in function `GetTriggerStateForTrigger'
[string "@WeakAuras/WeakAuras.lua"]:3388: in function `SetAllStatesHidden'
[string "@WeakAuras/WeakAuras.lua"]:4505: in function `UpdateFakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:4484: in function `FakeStatesFor'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1539: in function `SyncVisibility'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1565: in function `PriorityShow'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:1523: in function `Pick'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1281: in function `PickDisplay'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:1276: in function `PickDisplay'
[string "@WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua"]:525: in function <...eGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua:472>

**Comment by mrbuds** [comment]
fixed

**Comment by mrbuds** [comment]
# TODO

Models Thumbnail on WeakAurasDisplayButton + on New Aura menu doesn't show the big sword guy
