### ISSUE TITLE
No Buttons in Custom Options

### ISSUE THREAD

**Issue by Elitesparkle** [WeakAuras/WeakAuras2#5074]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The buttons in Custom Options disappeared.

### WeakAuras Version

5.13.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```
1x ...s/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua:101: bad argument #1 to 'SetText' (Usage: self:SetText([text]))
[string "=[C]"]: in function `SetText'
[string "@WeakAuras/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown-Items.lua"]:101: in function `SetText'
[string "@WeakAuras/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:566: in function <...as/Libs/AceGUI-3.0/widgets/AceGUIWidget-DropDown.lua:560>
[string "@WeakAuras/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-DropDown.lua"]:610: in function `SetList'
[string "@WeakAuras/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1279: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1110>
[string "@WeakAuras/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1639: in function `FeedGroup'
[string "@WeakAuras/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1919: in function `Open'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:1001: in function `FillOptions'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:998: in function <...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:996>
[string "=[C]"]: ?
[string "@WeakAuras/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...faceWeakAuras/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@WeakAuras/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@WeakAuras/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@WeakAuras/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = <table> {
 1 = false
 2 = true
}
```

### Reproduction Steps

I'm trying to create a new aura but I encountered a bug.
I made an Option Group (Array) with 2 fields (String) and switched back to User Mode.
I compiled the fields and switched back to Author Mode.
I added a third field (Toggle List) and switched back to User Mode.
At this point the Option Group was no longer visible.
I could only see the collapsible label at the top, but I still had access to buttons.
I switched back to Author Mode and I unchecked Collapsible Group.
At this point the Custom Options look completely empty, without buttons (see screenshot).

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/d70fe4a1-aad1-476a-9cc7-49856bf2d376)

### Export String

`!WA:2!1rv3UTTnu46AmuaJLUwVLGT0HnHmKGU2bNMuSCrXcqTCKBZGtCQSCAhWauOePSyJSibjLtuV0yaBx7bShaF9UYpc7IDnrWEc6JqVyxVdLCstdweGT4phE(o6777WkhwFyDCDzW33yJh3yJ64F7HI8UrrsIQIGLPsOPer3(ED2DFhXiIqszPvNrtJyIHifmPg3ctL8euUh5uLF56(CFfDiz(Sk81U(qsidqH5(rjmMiEQGmaYPxoNyRGyNGsPLWSL9qenTTTYSvklLCgotuSJVzjHKeYsXYXeKKyoU(2)LzypLGKoqfFlxPcjuT1lOVT(t03rFx4D9BfertPY4RU8ejjj6agnvfy31ZR7EBMjs43lwP4YNS(6NGgWAqzRpQFBz(XnpgT(gItNZzbsYqGMC3OXJA8OZqzQyMOl3uNYL)3zXumXLWeyIi2wsFdzr3tOyvCvrMKSdrggpdg0ILKG4ss8KbGeWnFoUiHaLpo88D28ysEqpojjrksz7rediX86sMq1mHhJcikAikjj)OPYSG54)G)q)1vNa5VtbLehKu8EXjdZsuuJqhRxDLD3rVGlnLNP0wX2POHeyjOGJqqu3CeKIGrOKmI8bJBlOKuCsURtkzyUE1XUeuObk9cZkYjqJKqtE0n0pwV(dIpcYDX30Ke6qQQuOMAaPhltes(iiW1eLjrULnioQA6pTM(ZQfaYBeDWs61wEn9JHmbv1n5FZ17R4csiTWTgy0RD3zYfYLlqJmXpwfE43jmtQydnjOphJuG8mIKQEhO9erkk5Wsl)Vp(eq1EPaXh)Y5d2mJIN9It3QNBBh8Hp71ZqPHGyxABA5SVNJR41qYPr52DCA7ntgJWStAvGDLkvQAhXsv87aS4BSErgcd2zKLN3uflCEJ2Nx5xzgb0TORqU8s6fodMgGcp2WIP4zrcd3PmhT6SlrgRSk)Ss8(PsJ5xEJPMgeAbZwJFV)xIRCGRH)WVf8UmtVx4lnou7MWu(dVE(gNdYin0xfliYywcoNVY1h9qg2hkAYr2jmeUDGcbMr1sUf2MAUHjiPCj9pxt)vM)TLCsOzW0i6PeCrb9lF8yLGoyaWu3ETjzPZNutmFWFpRuz9n9C6(tXKGSOiJJt8CNoh0UFh7mWEfykqIqVqqz464tRCZOS0cl49l8cFNvJgn(2AwWdnYQyjRT32ALwD3ZUPNFNUpZ35qqV97VF7D7aYUZoRyPIjPfhX8CXGeg0vAbs48Syv2HC)nVegFWbaaFF0aM9oWPth)wn7553ZRPR3va6do7La0CrHpf)Ea34QicnY1o)n87TNJApG0ONo7sqwUUKVyRoo9FYvli9tdEobLOIDnD1YANRcMlP1p9I0EGGaP1T40JlkVDXGT8UMw)reVsjCpgM8N3yUp(vL(4QRqX8LkU5ZQfsQS6zUx3QzcrOExzhyBtpHrOd61Y1Xz)XM(SEWLTFr9r)ZR0)GE7)7p`

**Comment by SpatenLa** [comment]
please get bugsack and report the error.

**Comment by Pewtro** [comment]
What does "compiled the fields" mean? 
Following your steps as I understand them I have correctly showing
![image](https://github.com/WeakAuras/WeakAuras2/assets/29204244/36aa2bc1-0bfc-49b7-bb9b-86f4a624a5bd)

**Comment by Elitesparkle** [comment]
> please get bugsack and report the error.

I edited the bug report to add that. I didn't notice the error earlier as I had no audio.

> What does "compiled the fields" mean?

I wrote some text in the first two fields (String), then I added another field (Toggle List).

**Comment by Pewtro** [comment]
I still cannot reproduce with the steps given. 
![image](https://github.com/WeakAuras/WeakAuras2/assets/29204244/9641cb94-6efc-494a-ab9f-d91929e5c797)

**Comment by Elitesparkle** [comment]
The default values for the String fields were set to empty.

**Comment by Pewtro** [comment]
> > please get bugsack and report the error.
> 
> I edited the bug report to add that. I didn't notice the error earlier as I had no audio.
> 
> > What does "compiled the fields" mean?
> 
> I wrote some text in the first two fields (String), then I added another field (Toggle List).

You just said you "wrote some text"? The fields I added have no default values, I wrote text in them

**Comment by Elitesparkle** [comment]
Yes, I set the default value to empty and then wrote some text in it.

I don't remember all the steps. Maybe I deleted the entry right after.

**Comment by Elitesparkle** [comment]
You can download my saved variables from [here](https://file.io/v2BP2BgoERip).

The error will fire when looking at the Custom Options of the aura called Spell Cast Start Alert.

**Comment by Elitesparkle** [comment]
First I created an Option Group called Spells, with Sort enabled and Name as Entry Name Source.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/c4a6d55c-82c6-4673-bf02-11ff3b615eb5)

Then I added a String field called Name.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/4746d62b-551e-40a2-875e-102f7208e184)

Then I added a String field called Spell ID.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/debbd739-ae1c-4f08-ab1e-d28efca44c76)

Then I added one entry and compiled it.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/8982ed21-0697-4632-9b39-da0cc543d3d7)

Then I added a Toggle List called Reaction at the top, with 2 Toggles called Friendly and Enemey.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/e34e9a70-f46d-4a61-b513-1eab31c418a2)

Then I went back to User Mode and the error happened, with buttons visible.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/c94e747b-4bef-4cdd-b200-6d1ae0bd50de)

Then I disabled Collapsible Group.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/05b11ea8-a6db-4944-b31a-07ca5ba24aa1)

Then I went back to User Mode and the error happened again, with buttons not visible.

![image](https://github.com/WeakAuras/WeakAuras2/assets/9367799/408b5afc-745a-4861-925a-4ced62f8ebc8)

**Comment by Pewtro** [comment]
The issue seems to be that Entry Name Source points to the incorrect place when you change the ordering of Sub Option. 
The work around if you face this issue: 
When you move the toggle list up above the currently selected entry name source, you need to reselect the entry name source to be the desired string again.
