### ISSUE TITLE
The "aura" covers the charges of a skill

### ISSUE THREAD

**Issue by djdenisdj** [WeakAuras/WeakAuras2#5084]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

My problem is this... I have a "Weak Aura" in which I have "the ability and the aura it produces." I noticed that when the "aura" is active and you accompany it with a "glow", it does not show the "charges" of the ability.

Despite activating the "charge text" in conditions with the aura active.
### WeakAuras Version

5.13.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. create a "weak aura"
2. put the next skill "Divine Steed" followed by your aura
3. set the condition to "glow when the aura is active" (Also try increasing the "show skill charges" condition.)
4. I activate the "weakaura" and when I activate the aura and show the glow, the "text with skill charges" disappears

### Screenshots

![image](https://github.com/WeakAuras/WeakAuras2/assets/164722883/3f969828-de61-4dfb-9abe-61084f48ef65)
![image](https://github.com/WeakAuras/WeakAuras2/assets/164722883/1ed4b189-adfd-4940-951c-5d6293ba525f)
![image](https://github.com/WeakAuras/WeakAuras2/assets/164722883/10113ffc-3135-4318-aa56-9589f79eab92)

**Comment by djdenisdj** [comment]
I tried using weakaura without the "brightness" and discovered that the aura is the cause of the problem.

**Comment by InfusOnWoW** [comment]
Please include an export of the aura you have created in this ticket.
