### ISSUE TITLE
Lua error on login.

### ISSUE THREAD

**Issue by theantichris** [WeakAuras/WeakAuras2#5085]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

This error shows when logging in. Not doing anything.

### WeakAuras Version

5.13.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
1x Lua error in aura 'Cast Bar - LWA - Shaman': Trigger 3
WeakAuras Version: 5.13.1
Aura Version: 4.4.4
[string "return function()"]:2: attempt to index global 'CastingBarFrame' (a nil value)
[string "return function()"]:2: in function <[string "return function()"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:718: in function <WeakAuras/GenericTrigger.lua:627>
[string "@WeakAuras/GenericTrigger.lua"]:880: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:825: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1110: in function <WeakAuras/GenericTrigger.lua:1095>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'CastingBarFrame' (a nil value)"
```

### Reproduction Steps

1. Log in as character.

**Comment by Stanzilla** [comment]
That is an error with your aura, not WeakAuras itself. See the first line for the name.
