### ISSUE TITLE
Can't get WA to show the cooldown for some druid abilities in Cata

### ISSUE THREAD

**Issue by billstpor** [WeakAuras/WeakAuras2#5086]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I created two WAs using the "New Aura>Icon" preset for Mangle and Swipe (the bear form version). Just like with other abilities I only changed the trigger to "Spell" and entered their respective names, expecting them to work like Maul, Feral Charge, etc.. which work flawlessly so far, tracking their CD with the dark radial overlay when they're on CD, but this isn't the case with Mangle and Swipe.
When I try to track the cooldown of "Mangle(bear)" it works inconsistently: e.g. today when I loaded the game that WA didn't work at all, but after reloading the game it started working again, and that happened yesterday as well.
Swipe(bear) used to work fine, showing the 3 second CD as it should, but as soon as I bought the cat form ability with the same name that weakaura stopped working completely.
I tried inputting each of the spell ID numbers for each ability as shown in Wowhead, just in case (33878 and 33876 for mangle, 779 and 62078 for swipe), but doesn't make any difference. This seems to be related to the fact that these two abilities share their name with their counterpart in cat form.

### WeakAuras Version

Weakauras 5.13.1

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create aura with "New Aura>Icon"
2. Change trigger to "spell", then enter "Swipe" or "779" and it should then show 779(Swipe).
3. Try to use the swipe ability with a bear that has already learnt Swipe (cat form), if the bug is consistent the weakaura should not show the CD correctly.

**Comment by InfusOnWoW** [comment]
You likely need to enable the "Exact Spell Id" option, since the spell name is not unique.
