### ISSUE TITLE
Add default triggers for chat messages from party, raid, or instance leaders

### ISSUE THREAD

**Issue by MutantRex2** [WeakAuras/WeakAuras2#5088]
When using weak aura triggers to determine if a chat message contains a word in party, raid, or instance chat, currently if the group leaders send a message containing the trigger word, it does not activate the weak aura because it is a different event than non-leader chat messages.
 
Instead of having to write custom triggers for group leader chat messages, could these be integrated into the default triggers?

**Comment by mrbuds** [comment]
This should be handled already as you can see here <https://github.com/WeakAuras/WeakAuras2/blob/f589b6e362eb352d5f651d61261dbaa5f04dd66b/WeakAuras/Prototypes.lua#L7571-L7582>

**Comment by SpatenLa** [comment]
`!WA:2!DrvWUTTrquRQg0c6IcB1uJeGCW1UXOOhmCIrYHEturY2fYsQu012NKxYDe5wtTl7UlLT8TOlnNv)d05Esh6hG(cie6xGp0pa)f0zjPuDcpqmZSZSZBM9ntPgvguHwH(H9MY8f8UIePp8I1wqs0Hcz7yntWvwYrT73xb6sZiCF0EhbJR9QvVLBDNf(crevCdV7nSy4Q5lvRtdGqBZLE1yTKfeas1xVNSq8VT1JIbhyiW13Rs8Ye6M0Vp72z9QvTRBVUUvDChttKedgQCy6xnVwirV9PGsrcGvb1rcyqoD7uVzZXQyik6eQYAkf8WBZftI846n704SM2jCM2loImcKoCYaqz9qIc6ni)cnUE1ShPCFTJR6270Uh1RdIKlNKWlWUv8MeFnBi4MRFQGc)1ApGTeqYjr)kwOiI)ZhUgG4QiI81oMAiCcHZgKvnV1rPjsDJ5arbD1sGhOd)I01T5coSyzn3Z0IKkaBHu1yJRgyLUR9acJ3iDhmG0Dt)(0xMUx6UE9zCMk8tnJ9bfrBUqiCk2YCGaZl6pTv66lqvpI)1bsrcN(HNgxrd3Q7Pcj4Z3ffp4XppZy2V(cjc)EQcH0DNS6SDEPkEJhfEnrKq(ZLkvQ895wHO(zKg7QN52o(BYmICmHPF4FoJQdTRIQpKNi2TanZ47xKt4USaoZZo)3suAw)rPpzQuOXkZfnA3QDR6PRlXIY4Z0mh9ZGrz8BsrfW1XB0qYUB7FjHqXUczBx3pQWxMPfz2UriPNljXJpVqihadzkMxeCvrn)OHI4npPvR6o9SB762(uNto6y3fRsDx2DWZlQOl(O8yonJR2(m3MN0Q()UiisCtdj87ja3FuNp)G9F9BYRoZbZn)ExbnP8yJMj6fEjATG3Eiirw(uJ5MzuRVDMrEzPnXOuBvRzooeC0slHzEUcCz3CiZ)AooxuolWU(KiOSTrmmZqtgE4MzzZg7sGm0leybH63Bhji0gEAmaUElNbjrAMLTzIyR0lTC8JikLrYwHngJq8giwQsnVVafONsUn8tnX4HtLzK4SHHV05MmEYRty0zTo8GGKrnQEWHUZy8Cwk6O19XsrGeRG81B)4lw7ZKMjyCq4TPFNv6pyzJdpAl77eIbLCirXHKYt1c)H5JYpR0Fi2HrJFMVzbueqWIC7ILbBRbLoUccYAfl(W1b48oUlPVexYGt3ilR8d5V6nmMma3RBnN61B58)mupCmVplWsY4M0cHXpD5Qud)(DmfbPC0q5Tfpotn7fy5lOhV01RMSAul9jvuEVz)xD4(VQYW)5I)l`

i tested it by making my own group in the group finder and posting in the party channel. no icon
to make sure double, i set the message type to say and tested it in say. icon shows
