### ISSUE TITLE
Add pet family and/or pet spec to unit characteristics or as its own trigger

### ISSUE THREAD

**Issue by Pewtro** [WeakAuras/WeakAuras2#509]
**Is your feature request related to a problem? Please describe.**
In BFA pet family and pet specs are more important than before as the 3 pet specs are bound to specific pets and this means that different auras should show depending which family or which spec your pet is. 

**Describe the solution you'd like**
Add Pet Spec and Pet family to Unit characteristics or as it's own trigger. 

**Describe alternatives you've considered**
It could also exist under load conditions. 

**Additional context**
It's currently possible to use unit characteristics and pet name, but it's annoying having to change that as you change pets around - and doesn't make it easy when sharing WAs.

**Comment by asakawa-k** [comment]
Current workarounds are:    
a) `status - Spell Known - pet - spellID` - on one of the spells that's unique to the pet spec.    
e.g. `status - spell known - 264735 - pet spell`

b) A custom trigger:    
custom - status - event - `UNIT_PET`
```LUA
function()
    return GetPetTalentTree() == "Tenacity"
end
```

**Comment by InfusOnWoW** [comment]
There's a PET_SPECIALIZATION_CHANGED event

**Comment by asakawa-k** [comment]
You can't actually change the pet's specialisation any more so I don't think it fires. The specs ar elocked so you're changing the pet itself.

**Comment by asakawa-k** [comment]
No, I lied, it does still fire when you dismiss or summon any pet.

**Comment by Pewtro** [comment]
Sadly your workaround a) won't work. All the dispel pets know all the dispels apparently, but can only use 1 specific - so you can't look for X pet being out based on their unique dispels for example. 

Example: https://wago.io/BJl0hfG47

Shows Spirit Shock even tho I have a Crane out and therefore should be showing Chi'ji Tranquility.

**Comment by InfusOnWoW** [comment]
All dispell pets? We don't play Hunters, you have to explain stuff to us.

**Comment by emptyrivers** [comment]
This should be implemented in the next release.

**Comment by InfusOnWoW** [comment]
That is as part of the Status/Pet trigger.

**Comment by Pewtro** [comment]
Different pets have different dispell spells. 

Spirit Beasts have Spirit Shock, Cranes have Chi-Ji's Tranquility etc. 
When scanning for Pet Spell Known, even if I have a Crane out, it says that Spirit Shock is known, thus showing that trigger in a WA for example. (But not showing me the CD on the Crane dispel after I use it) 


Also a bug report - the recent addition of Pet Specialization doesn't work. 
It triggers regardless of the specialization of your pet. (If possible to include Pet Family in the Pet Status trigger, it'd be amazing)

Example:
https://cdn.discordapp.com/attachments/129594743393878017/471075531190697994/b85a8b6ffcdf8511b0d3a3578b098a7a.png
https://gyazo.com/e0219c08c84d7b33b92d4f4bf4654934
