### ISSUE TITLE
Changed my language to german?

### ISSUE THREAD

**Issue by baltapiroca** [WeakAuras/WeakAuras2#5092]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

i wanna know whye it suddenly Changed my language to german?
i dont even speak that language and all my comouter/game is setted to portugues brasileiro 
already reinstalled tried different versions , did it mannualy and also neither worked .. how can i change it back to english?

### WeakAuras Version

weakaura 5.13.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

just open my addon
already shows there

**Comment by emptyrivers** [comment]
This is because of a bug in the Remix Gem Helper addon. There should be a fix for that available soon, if not now.
