### ISSUE TITLE
please add 'debuff type' bleed on triggers!

### ISSUE THREAD

**Issue by Somatics23** [WeakAuras/WeakAuras2#5093]
**Is your feature request related to a problem? Please describe.**
No, it is not necessarily a problem.

**Describe the solution you'd like**
Currently, the trackable debuff types are Curse, Disease, Enrage, Magic, None, and Poison. I am just requesting bleed to be added!

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by emptyrivers** [comment]
Sadly, blizzard provides precisely zero way to automatically determine if a debuff is a bleed. So, supporting this would require constant maintenance and be a big source of bug reports.

**Comment by Stanzilla** [comment]
In theory there is https://github.com/tukui-org/LibDispel/blob/main/LibDispel.lua
