### ISSUE TITLE
Refactoring of aura names

### ISSUE THREAD

**Issue by Chechi-dia** [WeakAuras/WeakAuras2#5095]
**Is your feature request related to a problem? Please describe.**
I try to keep a naming scheme for my class/spec auras and aura groups. If I create a new group for a different class I copy an existing layout to have a template and its always a pain to rename all the auras.

**Describe the solution you'd like**
Is there a way to implement something to automate the naming? For example I would like to set a fixed prefix and/or suffix and the main text would be the spellname eg. prefix_%spellname1_type1 (meaning ret pally dragonflight, spellname of trigger 1, displaying Buff as the type of trigger 1). The finished thing might then be: RPDF_Avenging Wrath_Buff

**Describe alternatives you've considered**

**Additional context**

**Comment by mrbuds** [comment]
This is a way too specific request to be implemented in weakauras, sound like you are better off writing your own script/addon to do that

**Comment by Chechi-dia** [comment]
Ok ty for the reply though
