### ISSUE TITLE
Change bar / element texture as a conditional.

### ISSUE THREAD

**Issue by dgbarrow** [WeakAuras/WeakAuras2#5105]
**Is your feature request related to a problem? Please describe.**
Not particularly a problem, but at the moment my use-case is changing colours for my resource bar in druid forms. I just figured it'd be a cool idea to be able to change the textures too, to allow for - for example - a lunar texture in moonkin form.

**Describe the solution you'd like**
Configurable texture option in the Conditions, or the ability to do this through custom triggers.

**Describe alternatives you've considered**
Spoke to the guys in your Discord, Buds sent me here, apparently what I was trying to do isn't doable in the current build.

**Additional context**
N/A

**Comment by mrbuds** [comment]
Hello, it was implemented and merged in alpha version just yesterday

**Comment by dgbarrow** [comment]
Damn, so fast you've time travelled i'm impressed!
