### ISSUE TITLE
Cata Classic WA valor cap conditions

### ISSUE THREAD

**Issue by SultonMRP** [WeakAuras/WeakAuras2#5106]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

i got list of text showing different currencies, one is valor points (cata classic), weekly cap is 1600, i got 720, i set conditions to
If: 'Capped at Weekly Max'  'true'
Then:
'color' red

Even if i set to "Quantity earned this week" ">=" "1600" it still trigger color change when my valor amount is 720 (haven't spend any yet)

### WeakAuras Version

WeakAura 5.13.1

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
not using Lua coding
```

### Reproduction Steps

see discription.

### Screenshots

![valor error](https://github.com/WeakAuras/WeakAuras2/assets/30296276/434d883e-7262-40b9-97d4-17c28106d49a)

### Export String

```Text
!WA:2!nBztVrXrAC8XQdbOdKygcgWgcZAcErHGX27ItWA5f3Mz8lm(f6PhBGnjZuD31mDB3txfvvTThFkAeczP90cN4WQinNIIYPr5dWk0EKv6rwr5dGvuoKJCGZPQUhEXoRb0QGe(q3v19JR6553))p10DmFAU957FW)s)dMUwA30URNztBcZfZmqol5YiuANgb(RTgI5MXIqce(u2QZwPchlM4FF3F6xprQuPy1F6dwlCXF(RtLQfk0XJWMJ4hkShl7mwznBLSQJrciSP6OJo0gkIfqpQNqq5JCUZTcQkPFFY5(S8ND8PUzjKld5i8jH8Hn5cetOBxXp0N7PBiVj0Biy(vRIz8U7J1E4DB6ITJQuXQofZMiB(5YvmVHqoXefXqd1GtXbbt6Y13KhzJxghkkiJ2F1wLgB0cwLkynQPLziQg(fIyogwgHzH5YMpVz8tSNaJceEgrYSWMgGQJz3lkSDkO)yz9IzHOG5LPMm7V)9qH(1qQczyyF5EigXXfemCyvH3UHdAescXB4ktpveLujlJJDiHU8gQqvLcCsJAi)WCqVY)b4KWhdNc6tEF)B)jgUyUdT3cEKv4zOkYZZqQKzzeZNeXZ4eXK7RJpM3uwDM4Qk4QBeqqU5SfOazT1LzTiP(QBirLtxWz1nDcqCUAKb3FnSAWg2TTfjcPMM2CAd0)5n5oYLqZorK9AMCpRBvm9afUDeIHZKlkiiZcE(cCtw8URQoZQmseTD4fK7XUEyY4ed1EBkiolNWY98VGE9DTJ9u8wvysLsIsKaP94e3wo1JulQDHXmZMDMHI8DB5mK7fYV0azDhDrBjyR4xv3efq9qA3JJdQeVAWUBBoNmuUNAnvcGFS5tVLFyfclrb13afjK7ZS0K3L25wRFAz6lc8dLjCrR8tot2wU(CLTWcVQO3tr3G7HCjRCZKY5yPG3f2nnZletPKLVeTKWVgU9SoOD6eXfKAQiksDrcm0ZMYDNOYeNf8DLoWrLtH3tAR0H9RdVVo8bVFFqN)I0sCCOl4W3lIJlTmkicxgok09MQPT9a1N0TCd1CLjU8MXbvIi9EibH17LUyZNhN4iWH0Ll4hzghv6bGEAmw73chrhoaKgoHo9aQM1LXwjTbttCXFFkAV7CzwJ4wsUB4Y0(25GcWvro1lvjGqyEWyg5ZMZYOcjuq7mhZFTmxpsDkHaLXYc(KU7co4gsJTYEQ8uHUWzYbFQYYc9hF9CXxhqDTHAvuUTd1wFUrI(ObJQddBiK5c8NunSBVP7p)QBdP98)SIsgyQkmxiRo9K7CDtzyhFLJxdENZtpZohOBD5Xv(oLeEmm3Je4wVXksF8cmeTXcThWwuAK8RuhUfmssheZYiJAXGDnXvs)K78Oh9O)l830Glcxc2lOdxU1fgAuHZ4ZozHQtdJlpd4Pn6ATsG1ZpcVP8WrSBSD8o7dYPdzU)6NgMaMeMs69HRL43H8Datd9aZaZ(s8RWCX(u46LbZYqbPneS(pp19bfvopy(NB5Gf((uWnkd3u6mK12Fh(Iepa8LVeDh(QdbLsezO8)3kmGaBiB39z64HDwkh0Pwd1HSi7amTl5zDHcFr9Siwi21YZNVagVeu0yWHhyGEjuzDXC8qHvXYF6ckoLMeJnOmv3NOoSi4OeDWToGHkq1NRAnNhjP(ZeU(FxZRk)BRc3vRw5ZVa1ZE(BvqkCWIXIgSuSubbVruOF4TAfcQnSuDGqBheLk77kQb3Un1N4YF7roYvKF7IgWEjy)HtPAFCWpd8JK(jp4bp4B2k4h86wuUOi7AKXFtbEjwLCxbALey9JlR4ESgOaVupuS)ToWdrBL5Fx3D)QzEZjiHVGv34FAVN1x)FSvIVKx9vM70g)1Xnh(vtC5w86W77gZVdcFOcTkSlzUc29ahlg8TjRQevO12ywlRzN(1MVh(pc((oDi)Xdf5AxXszEB0BJKpqkJ87uLFrdSRo2MvDSQ8RkMC1PYxxbUPOhpM2JO32OpIE8bnJOBrcoRXi)oKME5F8g)2p
```

**Comment by mrbuds** [comment]
What is the result of the command `/dump GetCurrencyInfo(396)`?

**Comment by SultonMRP** [comment]
Dump: value=GetCurrencyInfo(396)
[1]="Valor Points",
[2]=960,
[3]=463447,
[4]=96000,
[5]=1600,
[6]=0,
[7]=true,
[8]=4

**Comment by InfusOnWoW** [comment]
[4]=96000, means that you earned 96000 this week, clearly the api returns bogus information.

How does the tooltip for valor look like in the currency tab?

**Comment by SultonMRP** [comment]
Weekly maximum: 960/1600

**Comment by InfusOnWoW** [comment]
Can you make a screenshot of that?

**Comment by SultonMRP** [comment]
https://i.imgur.com/Cg2niSV.png

**Comment by mrbuds** [comment]
@SultonMRP could you try an edit

open `WeakAuras/GenericTrigger.lua` at line 4725, or search with a text editor for `Private.ExecEnv.GetCurrencyInfo`

Then replace this block:
```Lua
Private.ExecEnv.GetCurrencyInfo = function(id)
  if WeakAuras.IsRetail() then
    return C_CurrencyInfo.GetCurrencyInfo(id)
  elseif WeakAuras.IsCataClassic() then
    local name, currentAmount, texture, earnedThisWeek, weeklyMax, totalMax, isDiscovered, rarity = GetCurrencyInfo(id)
    local currencyInfo = {
      name = name,
      description = "",
      isHeader = false,
      isHeaderExpanded = false,
      isTypeUnused = false,
      isShowInBackpack = false,
      quantity = currentAmount,
      trackedQuantity = 0,
      iconFileID = texture,
      maxQuantity = totalMax,
      canEarnPerWeek = weeklyMax > 0,
      quantityEarnedThisWeek = earnedThisWeek,
      isTradeable = false,
      quality = rarity,
      maxWeeklyQuantity = weeklyMax,
      totalEarned = 0,
      discovered = isDiscovered,
      useTotalEarnedForMaxQty = false,
    }
    return currencyInfo
  end
end
```

with this:

```Lua
Private.ExecEnv.GetCurrencyInfo = function(id)
  return C_CurrencyInfo.GetCurrencyInfo(id)
end
```

then /reload or restart game, and test if that solve your issue

**Comment by SultonMRP** [comment]
edit done, will test once server mantaince is done

**Comment by mrbuds** [comment]
can you do a `/dump C_CurrencyInfo.GetCurrencyInfo(396)`?

**Comment by SultonMRP** [comment]
Dump: value=C_CurrencyInfo.GetCurrencyInfo(396)
[1]={
  canEarnPerWeek=false,
  description="Earned for defeating the most recent raid bosses or completing heroic Dungeon Finder runs and used to purchase the most powerful PvE armor and weapons.",
  isShowInBackpack=false,
  iconFileID=463447,
  isHeader=false,
  isTypeUnused=false,
  discovered=true,
  quality=4,
  quantityEarnedThisWeek=96000,
  isHeaderExpanded=false,
  isTradeable=false,
  totalEarned=0,
  quantity=960,
  name="Valor Points",
  maxWeeklyQuantity=1600,
  useTotalEarnedForMaxQty=false,
  maxQuantity=0,
  trackedQuantity=0
}

**Comment by InfusOnWoW** [comment]
That value quantityEarnedThisWeek=96000 is strange. Do you have any other char that has valor on which you can run C_CurrencyInfo.GetCurrencyInfo(396) ?

**Comment by SultonMRP** [comment]
give me a few, my other 85 has not done a heroic this week, let me do a "quick" heroic RDF and ill give ya results

**Comment by SultonMRP** [comment]
currently this week earned on him is 0 since i haven't done any heroics this weak lets see what happens when I do one heroic

**Comment by SultonMRP** [comment]
did a heroic should be 240 more valor...........but.......
Dump: value=C_CurrencyInfo.GetCurrencyInfo(396)
[1]={
  canEarnPerWeek=false,
  description="Earned for defeating the most recent raid bosses or completing heroic Dungeon Finder runs and used to purchase the most powerful PvE armor and weapons.",
  isShowInBackpack=false,
  iconFileID=463447,
  isHeader=false,
  isTypeUnused=false,
  discovered=true,
  quality=4,
  quantityEarnedThisWeek=24000,
  isHeaderExpanded=false,
  isTradeable=false,
  totalEarned=0,
  quantity=720,
  name="Valor Points",
  maxWeeklyQuantity=1600,
  useTotalEarnedForMaxQty=false,
  maxQuantity=0,
  trackedQuantity=0
}

**Comment by SultonMRP** [comment]
https://i.imgur.com/C2DsHCb.png

**Comment by SultonMRP** [comment]
is there a custom trigger i can use to do a divide by 10 until  its fig out?
