### ISSUE TITLE
Professions in load tab

### ISSUE THREAD

**Issue by SultonMRP** [WeakAuras/WeakAuras2#5107]
would be nice to have a multi-select drop list for professions in 'load' tab. I'm guessing there is not one do to dozen spellids for each profession. I just like to be able to set my herb tracker list to load for people with alch or inscription without have to make custom trigger code. players are paranoid about custom code in WAs

**Comment by InfusOnWoW** [comment]
I don't think that comes up often enough for us to add to the load tab. The design choices for the load options require us to be somewhat picky in choosing what to include.
