### ISSUE TITLE
Mass delete is not deleting all selected WAs

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#5113]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Mass selecting WAs with shift click and then hitting "Delete All" no longer deletes all selected WAs.
I think this has been going on for a while.

### WeakAuras Version

5.13.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. import https://wago.io/dfraid3
2. expand icons group
3. mass select 01 - 07 or w/e
4. right click and hit delete all
5. notice how a lot of mass selected WAs remain

**Comment by InfusOnWoW** [comment]
The underlying problem is that Shift+Selection is broken
