### ISSUE TITLE
Alternate Power option for Cata Classic 

### ISSUE THREAD

**Issue by TeaDrinkingDragon** [WeakAuras/WeakAuras2#5115]
**Is your feature request related to a problem? Please describe.**
The Alternate Power option that used to be available in MoP (when I last played Retail) doesn't seem to be available anymore.
I'm referring to Power Type 10.

**Describe the solution you'd like**
I'd like this to be (re-)added as a default option if possible.

**Describe alternatives you've considered**
None honestly.

**Additional context**
Screenshot of said feature on MoP WA:
![image](https://github.com/WeakAuras/WeakAuras2/assets/21976376/62c84c76-6bf7-4ca0-aa38-e2e1f66b9918)

**Comment by InfusOnWoW** [comment]
Where exactly is that needed on Cata Classic?

**Comment by TeaDrinkingDragon** [comment]
It's used by several bosses in Cata that have extra resources, Sound on Atramedes, or Corruption on Cho'gall for example
