### ISSUE TITLE
In the 11.0beta test server, as long as distance judgment is added, the game frame rate will drop to single digits and the game will become unplayable.

### ISSUE THREAD

**Issue by fwater** [WeakAuras/WeakAuras2#5119]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

In the 11.0beta test server, as long as distance judgment is added, the game frame rate will drop to single digits and the game will become unplayable.

### WeakAuras Version

5.13.2-15

### World of Warcraft Flavor

Beta (WoW 11.0)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

As long as the WA prompt with distance judgment is used, an error will occur.

**Comment by SpatenLa** [comment]
what is "distance judgment" and you seem to not have used bugsack and buggrabber. you MUST post the aura and your savedvariables file.

**Comment by fwater** [comment]
> what is "distance judgment" and you seem to not have used bugsack and buggrabber. you MUST post the aura and your savedvariables file.

![_20240607002737](https://github.com/WeakAuras/WeakAuras2/assets/11889465/a1bb1b1e-77b8-42c1-9df1-3cd144f59208)
![_20240607002744](https://github.com/WeakAuras/WeakAuras2/assets/11889465/700bb06f-5fdf-4429-8fbd-3195a7036f17)

Problem with range check and distance check

**Comment by SpatenLa** [comment]
you are still missing things.

**Comment by InfusOnWoW** [comment]
This will be fixed in the next build/release.
