### ISSUE TITLE
Toggling View to hidden after opening WA causes temporary freeze

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#512]
**Describe the bug**
When opening WeakAuras after 2.6.1 many more auras are previewed.  When I click the View (eyeball) icon to hide them my game freezes for ~40 seconds.

**To Reproduce**
1. Open WeakAuras
2. Click on View (eyeball)
3. Game freezes

**Expected behavior**
Expect no freeze.

**Screenshots**
Video: https://www.dropbox.com/s/jk2fcy9jcbwto97/World%20Of%20Warcraft%202018.07.22%20-%2015.04.23.08.DVR-Cut.mkv?dl=0

Errors in chat log are from auras I was going to update.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.6.1

**Was it working in a previous version? If yes, which was the last good one?**
Yes 2.6.0

**Additional context**
Saved Variables: https://www.dropbox.com/s/dwbn8imwowt4ayu/2018-07-22_WeakAuras.lua?dl=0

Large groups probably responsible:
* https://wago.io/VJJIupZVf
* https://wago.io/Vyfk0e9-X
* https://wago.io/SJ92um5LW

If I delete those three sets I have a very slight hiccup when toggling.

**Comment by InfusOnWoW** [comment]
Fixed it, even with loading all auras the toggle takes around 2s now.
