### ISSUE TITLE
It hide my HUD when I type /wa

### ISSUE THREAD

**Issue by Kamouraska** [WeakAuras/WeakAuras2#513]
**Describe the bug**
It hide my interface when I type /wa

**Do you have an error log of what happened?**

**To Reproduce**
Type /wa in chat

**Expected behavior**
It should open my wa, not hide all my  interface

**Screenshots**
https://imgur.com/SqT6nF5

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.6.1

**Was it working in a previous version? If yes, which was the last good one?**
Yes, 2.6.0

**Additional context**

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by emptyrivers** [comment]
Are you sure that you didn't hit alt-z by accident?

**Comment by emptyrivers** [comment]
And did you get any error messages?

**Comment by Kamouraska** [comment]
No, it load the wa panel for like 1sec, then no hud. I have to press esc, hud come back, but it close wa

**Comment by emptyrivers** [comment]
Install [this](https://mods.curse.com/addons/wow/BugSack) and [this](https://mods.curse.com/addons/wow/bug-grabber), if you would, and see if you get any error messages then.

**Comment by Kamouraska** [comment]
19x [string "--[[ Error in ' FA - Cleansing Protocol' ]]..."]:3: Usage: UnitBuff("unit", [index][, "filter"])
[string "--[[ Error in ' FA - Cleansing Protocol' ]]..."]:3: in function <[string "--[[ Error in ' FA - Cleansing Protocol' ]]..."]:1>
[C]: in function `xpcall'
WeakAuras\RegionTypes\Icon.lua:397: in function `UpdateCustomText'
WeakAuras\WeakAuras-2.6.1.lua:3574: in function <WeakAuras\WeakAuras.lua:3568>

**Comment by Kamouraska** [comment]
8 bugs, I c/c all here ?

**Comment by emptyrivers** [comment]
That's an error in one of the auras that you've installed, and is not an error with WeakAuras itself. Dump all of the errors you've got into a pastebin or similar, and go ahead and give me the link.

**Comment by Kamouraska** [comment]
https://pastebin.com/ZpfN5MYQ

I tried a downgrade to 2.6.0, no problem, then update again and same thing. No new wa

**Comment by emptyrivers** [comment]
All of those errors are still not the addon's problem, though it shouldn't be preventing you from interfacing with the options pane. Upload your saved variables file (to dropbox or something since github doesn't recognize lua files as valid to upload), and give me the link, I'll see if I can reproduce the problem.

**Comment by Kamouraska** [comment]
The 2 files in WTf/Account/AccountName/SavedVariables ?

https://www.dropbox.com/sh/aom74cckj2y4nn5/AABPwgfLLhC0rjHnfegMqJOla?dl=0

**Comment by emptyrivers** [comment]
I can't reproduce the issue that you're having, with only WeakAuras installed.

**Comment by Kamouraska** [comment]
Ok, I think I found it. It's an issue between AddOnSkins ( https://www.curseforge.com/wow/addons/addonskins ) and WeakAura 2 2.6.1.

If I disable the skin for wa, no problems

**Comment by emptyrivers** [comment]
So yeah, not a problem with WeakAuras, unless @InfusOnWoW or @Stanzilla wish to investigate this.

**Comment by Kamouraska** [comment]
It's only with the 2.6.1, so idk. At least I found how to fix it. Ty for the help, should have tried to disable others addons before
