### ISSUE TITLE
Guidelines/process for updating the wiki

### ISSUE THREAD

**Issue by noddycode** [WeakAuras/WeakAuras2#5135]
**Is your feature request related to a problem? Please describe.**
The wiki is notably out of date and doesn't have clear information on how to contribute updates. As the wiki is hosted via github, it's not possible to update it with a normal PR. It's also frustrating to use the wiki since you have to use github's repo search and it does not provide any text linking/highlighting when you click on results.

**Describe the solution you'd like**
I would like a dedicated docs directory that has all docs within the project itself, preferably formatted in markdown. You could use something like [github-wiki-action](https://github.com/Andrew-Chen-Wang/github-wiki-action?tab=readme-ov-file) to publish the docs back to the wiki, and/or host the docs on an external service/framework (something with a better search function).

**Benefits**
- Devs could be encouraged to include relevant wiki updates with submitted PRs
- Docs are provided with the project, allowing viewing/searching within an IDE and easier access when internet access is limited
- Host-agnostic markdown docs can easily be migrated to new/multiple hosts and frameworks without major restructuring
- May eventually be able to automatically pull in API docs contained directly within the code
- Local image storage means images are not subject to service outages or rule changes

**Describe alternatives you've considered**
- **Updating the wiki directly** - undesirable since the versioning is not as robust and you risk leaving the wiki in an incomplete, unreviewed state until all edits are complete.
- **Updating via PR to wiki repo** - Better than nothing, but github does not easily facilitate this process and manual steps must be done to merge PRs. It would also require devs pushing feature updates to make a separate PR for the wiki, causing issues with syncing changes with doc updates.
- **Hosting on external wiki-building site** - Generally combines the worst of the previous options, as there's no natural syncing between PRs and wiki updates and version control is made more difficult

**Additional context**
I'd be happy to contribute to both the wiki structure and content, I would just like to confirm if this is a solution worth pursuing.

**Comment by InfusOnWoW** [comment]
The wiki is not maintained by the addon developers, but is an intiative by other people. Putting it into the repository would make it harder for them to edit it not easy. 

And it certainly isn't "notably out of date", it might contain the occasional wrong information but it is mostly correct. Putting the updating obligation on developers would almost certainly make it more out-of-date, as I have zero interest in documenting internal functionality.

**Comment by Stanzilla** [comment]
I think adding a contribution section to the wiki is a great idea, otherwise I don't think we should change the general structure of it at this moment.

**Comment by InfusOnWoW** [comment]
I've now also discussed this with several people that have contributed to the wiki in the past. All of them though that putting the docs into the repository would make them less likely to edit it.

**Comment by noddycode** [comment]
If I could add some closing thoughts on this:

- I don't think updating the wiki need be much more complicated than it currently is, as you can edit markdown directly in github. However, I understand that's not the workflow current contributors are familiar with, which obviously carries heavy weight in the discussion of major changes.
- I don't think documenting internal functionality is necessary, but adding/changing features available to the end user could be synced with corresponding changes to the wiki (e.g. changing available unit types).

Bringing these up just in case the discussion should come back to this issue. In any case, I'll still try to contribute wiki updates in any form.
