### ISSUE TITLE
Player/Unit Info Power not updating when Combo Points are swapped with Redirect

### ISSUE THREAD

**Issue by Ratlaw** [WeakAuras/WeakAuras2#5146]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Even the most simple WeakAuras that consist of just tracking Player/Unit Info > Power; Unit > Player; Power Type > Combo Points fails to properly update Combo Points when Rogue's Redirect is cast under certain circumstances.

Redirect only sends COMBO_TARGET_CHANGED events which don't update Combo Points properly, since it seems WeakAuras only updates upon UNIT_POWER_FREQUENT or UNIT_POWER_UPDATE.

Building to any amount of Combo Points and selecting a different target, waiting until UNIT_POWER_FREQUENT events stop firing, such as being at full energy, and casting Redirect will not properly update the Weakaura and it will say 0 Combo Points, even though the Combo Points are clearly on the target. Simply deselecting the target and reselecting it will properly update the Weakaura. Alternatively, after casting Redirect and the Weakaura not updating, casting an ability that does not interact with Unit Power in any way, such as Sprint, Evasion will not achieve anything, but casting Fan of Knives (even without hitting anything and remaining out of combat) or simply casting Adrenaline Rush which will send Unit Power events, will immediately properly update the Weakaura and show the appropriate Combo Points, even though those abilities don't interact directly with Combo Points themselves.

Casting Redirect, even out of combat, while Energy is regenerating, therefore Unit Power events are being fired, will normally immediately update Combo Points on the selected target and work flawlessly.

### WeakAuras Version

WeakAuras 5.13.2

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Build to any amount of Combo Points on Target A
2. Wait until your Energy is 100%
3. Select Target B and cast Redirect on it
4. Weakauras will not show any Combo Points on the new Target B until you reselect the target, build another Combo Point or consume them, or trigger a UNIT_POWER_FREQUENT by triggering energy regen

**Comment by InfusOnWoW** [comment]
Can you try the build here: https://github.com/WeakAuras/WeakAuras2/pull/5159 and see if that fixes the issue?

**Comment by Ratlaw** [comment]
Doesn't seem to have had any effect, issue still persists. Same replication steps still apply, Weakaura doesn't update until energy gets affected in some way. Noticed in testing that even a haste stat change like equipping a gear piece that would change your haste stat or a haste buff being applied also suddenly updated the Weakaura, even though that action itself doesn't trigger UNIT_POWER_FREQUENT like my previous assumption was.
