### ISSUE TITLE
WeakAurasOptions should perhaps not auto-show all loaded auras.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#515]
Following the release of 2.6.1, many users have complained that it is confusing to open weakauras to many auras being shown (this is related to #512 - I am opening a new ticket because this is a separate issue to the problem of WeakAuras freezing the game for a long time when hiding the display previews). Perhaps a better approach is to not automatically mark all auras which couldbeloaded as visible, at least to spare the user the clutter that can result? For example, [these](https://imgur.com/a/UQSnZPK) [screenshots](https://imgur.com/a/nEcPJkd) are examples of what can happen when opening the options frame with many encounter specific auras are installed.

**Comment by InfusOnWoW** [comment]
This is argueably fixed.
