### ISSUE TITLE
Add queued spell cast cost support for %p

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#5162]
it would be really nice to add spell cast cost support for %p in the power trigger. 
Basically what "Overlay Cost of Casts" does for the progress bar, but this feature would be for the text instead.

im preparing my ui for the next expansion and want to get rid of custom code power bars for some classes, which this change would achieve (they break from time to time, i heard some use really bad code and i dont know how to fix them)

on the screenshot you see a custom code bar at the bottom which achieves this, the top one is a default one.
![0CvJ7sO](https://github.com/WeakAuras/WeakAuras2/assets/51278436/9b9585be-8829-4cb1-92ed-823203a81b13)

**Comment by Nokramx** [comment]
just a small follow up question on this: 

doing the same for queued spells resource gain is not provided by the wow API and every spell would have to be hardcoded. Is that correct?

**Comment by mrbuds** [comment]
> doing the same for queued spells resource gain is not provided by the wow API and every spell would have to be hardcoded. Is that correct?

yes

> In that case i wouldn't expect a resource gain feature to be implemented, i imagine that would be quite some hassle and maintenance effort.

yes

**Comment by InfusOnWoW** [comment]
For queued spells, there's no way we would want to maintain that. There's a) no api for that, and b) often intricate behaviour for resource gains.

As to %p including spell cost, that's also not something to be added, %c with a simple custom text function, e.g.
```
function()
  return (aura_env.state.value or 0) - (aura_env.state.cost or 0)
end
```

does that job and that should never break.

**Comment by Nokramx** [comment]
> ```
> function()
>   return (aura_env.state.value or 0) - (aura_env.state.cost or 0)
> end
> ```

oh thank you, this is great <3
thank you for sparing me from using bad resource bars wa's from wago for some classes
