### ISSUE TITLE
Frost mage doesn't work anymore in War Within Beta

### ISSUE THREAD

**Issue by actineon** [WeakAuras/WeakAuras2#5168]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Lua error reported without even loading a weak aura.

Message: ...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:627: attempt to call upvalue 'GetSpellBookItemName' (a nil value)
Time: Mon Jun 17 19:47:51 2024
Count: 1
Stack: ...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:627: attempt to call upvalue 'GetSpellBookItemName' (a nil value)
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:627: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:622>
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:643: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:641>
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:719: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:696>
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:1013: in function `init'
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:1324: in function `initialOnUpdate'
[string "@Interface/AddOns/WeakAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua"]:1404: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:1398>

Locals: spellName = "Arcane Intellect"
(for index) = 1
(for limit) = 198
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'GetSpellBookItemName' (a nil value)"
GetSpellBookItemName = nil
BOOKTYPE_SPELL = nil

### WeakAuras Version

5.13.2

### World of Warcraft Flavor

Beta (WoW 11.0)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
Lua error shown above
```

### Reproduction Steps

1, Enable weak auras on frost mage. (I don't have any weak auras added yet.)
2. Start game.
3. Lua error appears immediately.

**Comment by InfusOnWoW** [comment]
You need to use the alpha on the war within.
