### ISSUE TITLE
Unit "targettarget" triggers are broken

### ISSUE THREAD

**Issue by glassleo** [WeakAuras/WeakAuras2#5176]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Since updating WA to 5.14.0 I can no longer get any of the built-in unit triggers like Health or Power to work properly for ``targettarget`` as the specific unit. It seems like WA is no longer checking if your target of target changes. It was working fine in the previous release.

The aura won't trigger or untrigger properly if your target's target changes. It only seems to update when closing WA's settings.

### WeakAuras Version

WeakAuras 5.14.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create an aura with trigger Player/Unit Info > Health or Poer
2. Set Unit to Specific Unit
3. Specific Unit: ``targettarget``
4. Close WA and target yourself
5. Change your target and notice how it does not untrigger/change

### Last Good Version

WeakAuras 5.13.2

### Export String

```Text
!WA:2!1v13UTTTx4O6l(v4(BdPUBflabBzfRd7pTzTbTfyyRdZYXUXzU2PYknPBfWHsKYIRYICKuPj5UAmG1RnWEb817k)iKNaIG9eKl2dqEc2HKAXOfn5czYJo8OZ3hpFFXRvTr1W1WV(btLCK4f7qXQ0pCknML3NviIjlVG4GEjjsIYBgc)Rfsfb)y0bxA(gA(LehEEk5XPmXwmAUkQrZUHndoXw3aMcPOSCp(vFJ9pMHj(13oSNafB2lFqGuHeQQrj0CQmTQp8JQ6yLGoCiriF)pxuU8F8vhYj(fWR51kKKbOijteTbbLzk6ENklIi7tYv9lssOhmBqJ69dh0pSEq4PZt3MAGnp7rvPb5Orez1jMCIZqsz65vAlbbQuq)TA2PZyjNKL1glRo2KPPn2JFvZs4fX0eASlM(Ahd4zir5EAlBguTS0Pyse0AHakeB0SZwT2UZKI8s0vLFvdHSpj0T30N)1c27LbXSmMyZkWFNsYrrzKhjqyk0FPNYfSHcIu6U7(QLx4stq50rwQ(b63R1XeKK0xji5dvP)pDn)Cwo5eCHWMXadJkKe4JGLJnPAAo9T8hHO5T0FnCa9T03wVQ(BGFF)3osukHomv9jJJqIgUE0ZRcatjsz(cK0JT39UzLN5nf41aYqZT(Mxxx7eyBek(fdfSICCzGeMG4c86L4FQICGAG9behq1a(afDezaxauUekuLjNNYnUjNVYfDGrm8athT3P2xkjzj2zw9v4xZgbvOygAl2ki8RdBpZvh6beSn4R4F2fv(mYqu8HdsYymr6X2emIfAYH6lpvyg9jHqq)U9628KYZNRmKTFx4crxtaq3e)eNEA3s51uBUZV)NC(z5l2sqpALNuGWaUqRegYR5GwkcZEzzbQ8gbFMl4YlWx6Dae3IadEWUE8LmbEhbIpENYfoKTpW8Wq4E8fDm3ChGPT72TzWGonBfY)4lIRC78kpTRZCtpEW0ZC2Pp9iYs8V8Ikd(qq3cIovkm)NYYWhwYDLO071FGEZk6V9g3mxhAlT(70xr)96hQ)HxP3Xt)J6lRRR9Hb6M6hzzx9g626FA5f0D190BTN(jZC4jO9J2iu3qVUE7L0T8EhSxE5c9T4xByP4SNW80QZMUrVG2)CVUH17yXxHG4eSR1P)J9ZyiCRifkds)6bJkYu0Q(gtLRR3RAG1sYSYxceIzXPwrLpKo24sSw91xNViyZuV0G26xNolra(AG0hMoQmJM7AqOzQEgCtre5OSNcAFiWFEcm8dexpU1qU6BxmAE6uHv2ATUqG0ge8oPDOdn8VOTPMjOyYZBGGb)8H(iXZ3U9TNV729nhyYCP3LNyD3KumjWsXRvqXZ28EDUB91)TNLS(UZSFInOymjpOBZN2mOmI125HIsQCSFg9OJqcCWlnY0F))7FeJnYlWMB6uflEFhq)iV)GDdkMV4NUY2GvnywivRyGJ7Ff24CzwakJNIQCMBGQLHinqpQFJGMn7E2CtRZNB3QYDw9(raCsOdRkO5MV4BA)TR3m28jc9Vm1y6sDm(K)ZaDn4Z7vX3WlP1Kr3F17EVvVtT9)7D)3p
```

**Comment by FluffubSheepub** [comment]
i has same issue
WeakAuras 5.14.0
Classic Cataclyssm,Classic SoD
