### ISSUE TITLE
Item Cooldown Ready Event (Slot) Triggers For *Any* Slot Ready Event

### ISSUE THREAD

**Issue by evanseigler** [WeakAuras/WeakAuras2#5180]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Item CD Ready Event (Slot) seems to have broken recently. The equipment slot does not seem to matter, it will activate for any slot that triggers a ready event.

The WA's I had previously worked during raid on Wed 6/19 but stopped working (properly) last night Thurs 6/20.

### WeakAuras Version

WeakAuras 5.14.0

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Have basic WA that displays for trigger:
Type - Item CD Ready Event (Slot), Equipment Slot - Gloves (using Synapse Springs)
Hide - Timed, Duration - 3
2. Unequip/Equip on use trinket to trigger CD
3. Notice WA activates when trinket is off CD

### Last Good Version

WeakAuras 5.13.2

**Comment by InfusOnWoW** [comment]
I cannot reproduce that, please add an export of your aura to the ticket. Creating an aura with your instructions correctly triggers exactly when am item in that slot finishes its cooldown. The aura does not trigger for any other slot.

**Comment by evanseigler** [comment]
Thanks for checking - I guess the simple aura does indeed work after retesting.

Here is a WA for Synapse Springs. Trigger 2 is simply to play an audio cue when its off CD. After taking off Mirror of Broken Images, and reequipping, my audio plays. This also happens for my Nitro Boosts on waist.

```
!WA:2!Lz1ZUTXXzCtXK6u6drI2swUXfLWarWrjqi2nrhSVuUuK2kMIuE3vwUijq7S7oC3jA5mtMzwkrz3aeIGaFwig5uts5H(aWR5MEcgqKNaDOpa6fO9Bg(hBNQdCNV))N5773Ocnk3TCC54x8HdjrmQhlxeHV5LgHI)QCPchVd64fEfbHUGOF7oDKyvHriAuktSlJqvH1Q3YVU74igllMDe17ichhC2mY6Xj4uhJ)dgOeKKeSq(tRjME8fl7QeOOdDq5k2aIc3TfQlUaFPCj(GemflirEPSJAtdg)gKdLWNQzhH6lDPGjYsJmMy4MefhyDLxgtT8WyCyENo(95yXdR3C3g710rbeognoxMhI7HPkpqfYXJoOwvp)d88R667KtjQqEgQpwCMX1ZsUGXcmkZJJZYmK8v3c3LrjrvQrerz47vXhNH5mHAUvM8iySn9MzvWa7XTJLL4x1irHLQgmrTPDTG5z2UcmKzUE7wVzZtNB)78R)WPwZmnVaxRM8BnZ6k7kyjcSuw521)6CcVliTIjl(GtZPt78LwtFL)T(66vheNlqkcJw(VQVn)Vm3hUyuC))phOFp9n1vc0xBz97gOx8CP92yMr6)CGEz9k61lnkMi)QCAKI0dhgbtqSU8Yt(6pjbAYsir83RJvjg92QpOKaRYf0kQp)oFzjmnMVeYA)ud2HfJlEbmXHfuu2tG5iWSxEXHymVk0yIuUMYi4ujoRJDYu)hGlFjszQpC6qOJ6ItaBK3Bf91hdKHqZlrWYPXV4A8Yk8XkyacbfYtNoNZVHLP9NomrxeOW0dougfF6CX369L8fFnpuJLXeFwHcfkE(eUZskNQ753MFvltZqp4ks0(KyvQtvG8IjXICmo2Y8Bhpzv7VpnJoZk3Sss60hkqbtbfNpW0Pv7w11xxa1LrNHwfJSPrr4VtNweWCYIneKtQ84Cum0yqv89FJAFwKgB5DeteVVaXhS)0dtsGEejjmdNoTMFn4a(sB3QvD3dCA773Eh3TFWd9hpp0EKtW3yAf903iogP2D02753C7w1)pJtYyh1qG)6CmnQ)UV1hVXD)0jvNrWzMF2A6GBXbgkJ1JdZvkgTDpSawChAy3ettuPlpYCEwPDQHO28wJzr9bZ4KA1CwY5yisT5IFkj6qkSuv0AUxekdp5ytcWEjB0CGUewKgMIjjPQh7KXqXFVdSKIxlusOjz4WhWcZiu3U5zkYk60GZNdmCi1U5hLHKsOLgB4gvkubbIQwrtw5zbUwHRPtgTv9Q(p8rTm9xqIMg4y0g0Q0Wx5Svl83(VosOPB4ZxeIu1PW5w09uxugpfv83lHqthkSRkMMQ(poee7dR4kcpDWmG9GHaMEmXCbixFn3OuC0HBQVsXb9qcccgogYMJl42dLLJlkIsr0eS8pTM(5bd4cgCFR6R3CnDFWYp6s6tUB1wBfADLCDG1BRpXXGWOFErJR1NOFM(5f0)dJdAmuA2CpWcMVlCD7APfvMGYmvkhPs53CBdOrh4w4l8mCLFHSpfXL4nyjjJNOOj1O4SWDqqtqO)g93ngwpH502CBjwsC8mqHLMma3qaaX7IeWLtAi0l6qsk5CcJ1Ta)AZAsMfZTist7io9IxZotJn0RMB96TgQyr9MGM9o)t9TiX8v(CVA7T9xwXBswwXJlGzhPazrkLB6kviHQKdbEIQuyh4JmT0Oog)6Pm70fDpYaEG5LHBUzxca(jGqIdUBojEuReNNCNAp5WS93h8Tj84Gtrusx7g1M6x2aEB4(NHrsJlT7qxE8SxkS9CWcZaGCGrh7CY9D6IiuRH6F(Y6Fr)V0dHJ)4VNZ58Pppn5)4y9BEPfmpxyERDBWLRUWLF0icDcmleTsUVcfRSm8t34oFYgFC5E)2t)Fd
```

**Comment by Deathtouched** [comment]
Also having this issue with a simple item ready event weak aura. When synapse springs come off CD all of the sound and icon events play/show at the same time.

!WA:2!LFz7ZTXrDC8OCusQcT0OKykj1tCnqMegIJTcXjnqzqYwk2b)G8jLhAgpyT3DR0TXNU7YU3jfzEOerOeEgeeOTmLhefk0uEOQ84WWmm(VGFJN(xqyMWBzYl41873DskJtZeGj8k6BK2DV90(B3VF((DTtC2ukJJn2eF4XgpvTuwPSU2jYwv61OZmlQp7fwCHszM7MgEslUmlZCvlPNV)JL1rS2AmP1iL88Cce(gnyv9MD62h)4tSK805MWFdwyGTNCr)aHNRkPS5IvQO4bZ8xNn4Fm6Op5F)2kpzWmnnKcRsmdh(zx)uoE15Qr05mRM2DZ65fOgrg152LKc3v5bJKU3aB0FGEDNcxIWA8ED9FSqfpJRjU8f4YZ4kcS7gx)t554jpDIej0AH7VI(mtUw6qPJ)(Sdc8vN8ihH2gJj8oYG9XrMqYmJ2dtQRcyYGKzf4VysJk4xk7KTcKIQv5s1EpGSxZNRJf3iSsLsn95YzYnxH8NzUSbyhDwOKLULYN74mRLk5nvHg86C3GI4SfxU7ktLPyPvkwkJEPbpQGKJpsVyHCZnx2qCLn8Dyn5s9ONAmdN5eyR7YQXvjBh62Res210ZjSMB8w0qYSeHQR(UAR4ovk4jWxCQClukNUoZru1foSUIM4dHNkbmAZMqwh3sydToyHOZRgjIDQe64mLqA6WllXddALsK1XJzL3iG5G1Zq61crCizwCpAoeC8K6MomLIALvjwJtn6YILgQmGdVHrpMkwB000kOn(yhlDOWQBGLXPhpNJ7LN8usMROglGBBy65wrunPUYexrAUt2XexzUKoUhDoDJyP2Ut835SQY93zXlfYK8rYJ1)iNZweWBRc4(zCR6W3FVjwelVhs3ruteSddLxO0KBiQ5JuA7QiKEoHvG9oAhxg4PXKWq5HHZ665YxNZu8IbsUB1a7TTHfkY0mwHKCPIJfSLQfnhQcH5ZwJjCX3fMhwyBWIqbyjS5JF3JGsJVnt7M4RJh1Ub5rm0tAONz6zptXSK7bMF94sp2A9WgkEnu20NySXhB8obEM90WT)sWOcl)DnBaVwSfb)SMWfFZoYiPLkS1TAIuKWeD(H(DRirIc3tSaM2TJfS80q0mnkoLEUCl0MjnNlApF1H65VM1fRdn5LJlOeTOdUizrF6BlinYL5C24I66DOZfrC6qxHBfpz8b7qDXMM8CeERk3cTYZrAIDkZlCTX6iW3QyK48eBbENW26YSUyiQLwZZU8wVthH7wHhob8rq(YedOS8A4wSHWNxE9(DjUWg2dkJjH3ts4XtcV3foaS3BHAkIh1GrGNSvFLmvA)DI1Xkv5UCPWSOTxJfDlVXM6Etv0xt17NNQ7vi7Az4a(7P)OXHBJCqsjoeCWKW(tUonrAfxapDldJcVp49dFGw9hz7)TrH9bpbCOKDTeQlg6Izr15PzUn93jlQDPyh)8Ew8xBla)63Evos2K)lqNQEB4dbhgtKuSaA7GB6j0G0NCiy4nqRn5(if316wBu1XRrEj)sHCxZMfEhJpw6JbdlXjrpyD6JP7DGO1I6fLVLzQI2cxEhAGyAypDP2ptpgOn1zG3wl6zNV3ZO9(P6)y7OzwKC1AzPMLJkOs2cZvD5kLw0ZNdxl1oJwTSX(8k9yVvO8LTbd3M2vrJ0ZDSI5Gu)ExJTsDHsG35uU)RYryaYTrVEEXvNHnxu1o4kWXQ0MejxmXvAdtszyrdGzN1rj7e0aWtf95jPpJV)PhkgrM2WSWPHDb7gQoeyx(UNGW1gwolH2WCiqE2OKGLIsdm8LCSyWcfLE(0CtwZOacDAsVqVjbVqNOWIcHokE0JFlPjWZxgmtapD3mN54(5QpzLjoDAy7jri6oE7cyePlEzsdkQ7k(PWISp4I0fct8Y(7UV)Pe)Ybtlu0v3w2W5HNbUqCod8UHpPguudwbkNDnpVAejnXXGpEs8oBkrIBRBoGhGk79a6M2CZvNe2RwR6mPG(jZsUj96mNqUM00M5wLJxWcVYKDueRgfTMTaErOEuF)p2Su6sf8oSLZyzHrklFooB1miUQwUGxdetPMZZTeSLlsVHA58cj3G54mMx1QBe)RslKl3XyEgkmYw(4TsCzqt4gT6VRTVjoyvusuXHqFWNylB9AJbxmomcwDRGt)GhOwzW9UsyEumH5A7gAS9x)fHlvgKDJdnIsfgy7l64fSVit)WGhLdbyiIFQ0q9YTXCB8YdHB1uhDqWbn)Y(Pg8OvOQMH3vK6JI5l(7IMxaxfK3t2xoTXSNnOXh8s2rjphWF)3DuvUlfk8RHCXi06CimicwlkNb(urjlWN(obkWN5wWNTFWb8SWNtdUc0c(87bUAc4leR3pxc4lAdxtd(sLHVSg8v2j8vTRaFn04cFD4Be5sHVzz4Bb5G2jGVn5(GVtpxhC97HBd(U3L7c(EOBcE(3IvcTlV49Y7aF))nwMzsxl3f0BeS0QC0YaVKn8dUc8dld)OnZ9p6D4E4hpa6Ho2WpzaQdVmH5Wpf(zWROb)8iKg(fWRc3W)eBcHxCti8Ma3P9crhY5S98u2e8c)s4xb)A4gWVXgE9hqGe6syi8gdFV5p43M6OWVRm87Jql4pqCe8h7XoWF6TJWX5dp4fUyG6PoLBT7hC8ipqWb8NFqf5)jQXV2RgjJKIIYgk31J)7nqb9nEespjPNKrjOI0(4)WJ)Fvs38CZwHzfF3zFL1)uY1oU(IZKNV09rz7KL7eehw(G5)F6)7VclxXcz0)et8)IqaIpE5NLGccpiiGqfceiOGiK9qecHli1G4ZB34d4VSj4yPLYuPr(1ovZvz3pB)oEWyIJ(F6Dc4)dsq1q37jjKQ(BE()f

**Comment by Deathtouched** [comment]
Same issues happen with this weak aura that used to work correctly...now when synapse springs comes off CD all of the on event sounds/icons show at the same time.

!WA:2!LFz7ZTXrDC8OCusQcT0OKykj1tCnqMegIJTcXjnqzqYwk2b)G8jLhAgpyT3DR0TXNU7YU3jfzEOerOeEgeeOTmLhefk0uEOQ84WWmm(VGFJN(xqyMWBzYl41873DskJtZeGj8k6BK2DV90(B3VF((DTtC2ukJJn2eF4XgpvTuwPSU2jYwv61OZmlQp7fwCHszM7MgEslUmlZCvlPNV)JL1rS2AmP1iL88Cce(gnyv9MD62h)4tSK805MWFdwyGTNCr)aHNRkPS5IvQO4bZ8xNn4Fm6Op5F)2kpzWmnnKcRsmdh(zx)uoE15Qr05mRM2DZ65fOgrg152LKc3v5bJKU3aB0FGEDNcxIWA8ED9FSqfpJRjU8f4YZ4kcS7gx)t554jpDIej0AH7VI(mtUw6qPJ)(Sdc8vN8ihH2gJj8oYG9XrMqYmJ2dtQRcyYGKzf4VysJk4xk7KTcKIQv5s1EpGSxZNRJf3iSsLsn95YzYnxH8NzUSbyhDwOKLULYN74mRLk5nvHg86C3GI4SfxU7ktLPyPvkwkJEPbpQGKJpsVyHCZnx2qCLn8Dyn5s9ONAmdN5eyR7YQXvjBh62Res210ZjSMB8w0qYSeHQR(UAR4ovk4jWxCQClukNUoZru1foSUIM4dHNkbmAZMqwh3sydToyHOZRgjIDQe64mLqA6WllXddALsK1XJzL3iG5G1Zq61crCizwCpAoeC8K6MomLIALvjwJtn6YILgQmGdVHrpMkwB000kOn(yhlDOWQBGLXPhpNJ7LN8usMROglGBBy65wrunPUYexrAUt2XexzUKoUhDoDJyP2Ut835SQY93zXlfYK8rYJ1)iNZweWBRc4(zCR6W3FVjwelVhs3ruteSddLxO0KBiQ5JuA7QiKEoHvG9oAhxg4PXKWq5HHZ665YxNZu8IbsUB1a7TTHfkY0mwHKCPIJfSLQfnhQcH5ZwJjCX3fMhwyBWIqbyjS5JF3JGsJVnt7M4RJh1Ub5rm0tAONz6zptXSK7bMF94sp2A9WgkEnu20NySXhB8obEM90WT)sWOcl)DnBaVwSfb)SMWfFZoYiPLkS1TAIuKWeD(H(DRirIc3tSaM2TJfS80q0mnkoLEUCl0MjnNlApF1H65VM1fRdn5LJlOeTOdUizrF6BlinYL5C24I66DOZfrC6qxHBfpz8b7qDXMM8CeERk3cTYZrAIDkZlCTX6iW3QyK48eBbENW26YSUyiQLwZZU8wVthH7wHhob8rq(YedOS8A4wSHWNxE9(DjUWg2dkJjH3ts4XtcV3foaS3BHAkIh1GrGNSvFLmvA)DI1Xkv5UCPWSOTxJfDlVXM6Etv0xt17NNQ7vi7Az4a(7P)OXHBJCqsjoeCWKW(tUonrAfxapDldJcVp49dFGw9hz7)TrH9bpbCOKDTeQlg6Izr15PzUn93jlQDPyh)8Ew8xBla)63Evos2K)lqNQEB4dbhgtKuSaA7GB6j0G0NCiy4nqRn5(if316wBu1XRrEj)sHCxZMfEhJpw6JbdlXjrpyD6JP7DGO1I6fLVLzQI2cxEhAGyAypDP2ptpgOn1zG3wl6zNV3ZO9(P6)y7OzwKC1AzPMLJkOs2cZvD5kLw0ZNdxl1oJwTSX(8k9yVvO8LTbd3M2vrJ0ZDSI5Gu)ExJTsDHsG35uU)RYryaYTrVEEXvNHnxu1o4kWXQ0MejxmXvAdtszyrdGzN1rj7e0aWtf95jPpJV)PhkgrM2WSWPHDb7gQoeyx(UNGW1gwolH2WCiqE2OKGLIsdm8LCSyWcfLE(0CtwZOacDAsVqVjbVqNOWIcHokE0JFlPjWZxgmtapD3mN54(5QpzLjoDAy7jri6oE7cyePlEzsdkQ7k(PWISp4I0fct8Y(7UV)Pe)Ybtlu0v3w2W5HNbUqCod8UHpPguudwbkNDnpVAejnXXGpEs8oBkrIBRBoGhGk79a6M2CZvNe2RwR6mPG(jZsUj96mNqUM00M5wLJxWcVYKDueRgfTMTaErOEuF)p2Su6sf8oSLZyzHrklFooB1miUQwUGxdetPMZZTeSLlsVHA58cj3G54mMx1QBe)RslKl3XyEgkmYw(4TsCzqt4gT6VRTVjoyvusuXHqFWNylB9AJbxmomcwDRGt)GhOwzW9UsyEumH5A7gAS9x)fHlvgKDJdnIsfgy7l64fSVit)WGhLdbyiIFQ0q9YTXCB8YdHB1uhDqWbn)Y(Pg8OvOQMH3vK6JI5l(7IMxaxfK3t2xoTXSNnOXh8s2rjphWF)3DuvUlfk8RHCXi06CimicwlkNb(urjlWN(obkWN5wWNTFWb8SWNtdUc0c(87bUAc4leR3pxc4lAdxtd(sLHVSg8v2j8vTRaFn04cFD4Be5sHVzz4Bb5G2jGVn5(GVtpxhC97HBd(U3L7c(EOBcE(3IvcTlV49Y7aF))nwMzsxl3f0BeS0QC0YaVKn8dUc8dld)OnZ9p6D4E4hpa6Ho2WpzaQdVmH5Wpf(zWROb)8iKg(fWRc3W)eBcHxCti8Ma3P9crhY5S98u2e8c)s4xb)A4gWVXgE9hqGe6syi8gdFV5p43M6OWVRm87Jql4pqCe8h7XoWF6TJWX5dp4fUyG6PoLBT7hC8ipqWb8NFqf5)jQXV2RgjJKIIYgk31J)7nqb9nEespjPNKrjOI0(4)WJ)Fvs38CZwHzfF3zFL1)uY1oU(IZKNV09rz7KL7eehw(G5)F6)7VclxXcz0)et8)IqaIpE5NLGccpiiGqfceiOGiK9qecHli1G4ZB34d4VSj4yPLYuPr(1ovZvz3pB)oEWyIJ(F6Dc4)dsq1q37jjKQ(BE()f

**Comment by InfusOnWoW** [comment]
We believe this to be fixed, although I couldn't reproduce any issue even with newly attached auras.
