### ISSUE TITLE
Not sure from witch update it whose but it started happening in Cataclysam

### ISSUE THREAD

**Issue by TheEye2108** [WeakAuras/WeakAuras2#5184]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I keep getting a crash report with Exception: 0xC0000094 (INT_DIVIDE_BY_ZERO) at 00007ff607b95959 its not happening all the time but when it does its onloading screens. Mostly when initially loading the main character or switching to another. When i disable WA addon it works fine. Did you change any math related code recently so it can try to divide by zero. It also seems to be related to Intel 13th gen cpu mostly. 
[2024-06-24 00.21.55 Crash - 13564.dmp](https://github.com/user-attachments/files/15950555/2024-06-24.00.21.55.Crash.-.13564.dmp)
[2024-06-24 00.21.55 Crash - 13564.txt](https://github.com/user-attachments/files/15950556/2024-06-24.00.21.55.Crash.-.13564.txt)

### WeakAuras Version

5.14.0

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Just log into a character that has wa addon enabled

**Comment by InfusOnWoW** [comment]
Unfortunately that's not a bug due to our code, but the crash is in blizzard's lua implementation. The mentioned "division by zero" is in their code. Addons in general cannot easily crash wow. 

Do not that this is the first time we have received that error, so another possibility is that there's something wrong with your computer.

Blizzard should automatically receive the crash report and if it's a bug in their lua implementation will hopefully fix it, though you can also post in their forums.

**Comment by emptyrivers** [comment]
You may find this helpful: https://us.forums.blizzard.com/en/wow/t/132-error-still-crashing/1743778/4

**Comment by TheEye2108** [comment]
> You may find this helpful: https://us.forums.blizzard.com/en/wow/t/132-error-still-crashing/1743778/4

Ty it seems to have worked but its so stupid that we have to do this :(

**Comment by TheEye2108** [comment]
A small update ever since the latest update to wow cata classic i dont have to do this any more :D

**Comment by InfusOnWoW** [comment]
Do note that further information on that instability has come to light and it seems that Intel has sold faulty processors. 

You might want to research the topic by searching for "intel 13th and 14th instability" and contacting Intel for further assistance.
https://community.intel.com/t5/Processors/July-2024-Update-on-Instability-Reports-on-Intel-Core-13th-and/m-p/1617113

It's unclear whether any firmware/microcode update can retroactively fix your processor or whether replacement is necessary.
