### ISSUE TITLE
Group scaling not working properly

### ISSUE THREAD

**Issue by kirihn** [WeakAuras/WeakAuras2#519]
**Describe the bug**
Scaling isn't affecting some of the auras in one of my groups

**Do you have an error log of what happened?**
No error buzzes

**To Reproduce**
I'm not sure what makes the auras not affected special, they share the same characteristics of auras being scaled

**Screenshots**
https://i.imgur.com/0ZFkhw8.gifv

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, and it still happens

**Which version of WeakAuras are you using?**
2.6.1

**Was it working in a previous version? If yes, which was the last good one?**
Not really

**Additional context**
https://wago.io/Nk-REqT7G
Only auras that scale: soul shards bar, imp and dogs timers, talents cds, and spell #2

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
