### ISSUE TITLE
%tooltip# text option not updating, specifically for Carved Blazikon Wax trinket

### ISSUE THREAD

**Issue by ricktifier** [WeakAuras/WeakAuras2#5193]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

While trying to make a weakaura for the item "Carved Blazikon Wax" (itemID: 219305, aura spellID:451367) I noticed that while the tooltip on blizzard's default tracker updates the versatility value (located on tooltip1) but the %tooltip1 text only returns the initial/max value (I'm not sure which it is, given when it procs it starts at the max). This isn't the case with any other trinkets I have tested so far.   

### WeakAuras Version

5.14.1-9-g7e748d2

### World of Warcraft Flavor

Beta (WoW 11.0)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Import/Create aura that tracks aura spellID 451367 using %tooltip1 as the text
2. Cast until trinket procs
3. Move out of range of trinket-value on weakaura does not change

### Screenshots

![WoWScrnShot_062724_001124](https://github.com/WeakAuras/WeakAuras2/assets/95903710/97881cec-c45e-4063-94cb-6ba26eb3f999)

### Export String

```Text
!WA:2!9z1ZUTTXt4yRIeaEPXongXbbOcgOb2focw)12fifWsroXfoYUukX(hccKwYDL4gtTlZUlLLCrpeHEih6jDP31Tc0cuOhb9eqi87jih6dGFc6SKuYk2fvaIC3VD(MD2HZ8rUW(l3Ez8Y4pU(qQnNvL7lSjp6wJq435lve8lrDx8Qju2IIEh1SPKOwyeIz7WfhZPmLvPYvQv2CInN7I5NZQEo1J0y80PLXTiocKTIYzYcMsfsOmkszu1JhG51TbNZB3Wk6E3f)fKVavNW6KQdrit(0KzYVvgddxUnYnzm0pzKe(9M87U9BJnyZiKcBTvesUCZqYgHStHzifcrkKzNPiPJyvyNzSshXA7mZyLoI12fUI1UHi7KERPizIyTtHzSYeXA3TMXkteRDZdS(zdJMCrsPlxbyPZUzY05sI5HwgEj6utvK21PyWKNtuhW6qykUO3ba6Hu2zRVMNlQhrS2MA)SX15XqTjaZs112Ns7a4(bSM81JD7gxTDHxOnNN4)kZmP3n7w53iPYHWc5mJ812CxshIlS7sIlXwTEUn)VIJnUPRMglr(bXWHvaV5kS3(5XG(31RFUbJ5(nJiHHnMEh(B1eQpLog9vcARwGdQ8yr8WpUK3YkO0wr9EnY1NuXVTfrKysBKY2HiR6Wp)i2qjCBp3Zr9KM68O0W7U(ss95j6metS8B2SwppI4fLp849F1HfvWet9jiZLG9L7cTnv9iUUhGB4D)5zxNdSqqDWAF)tnj6scRxqqUkNXnjqGulY0gJ1(sQ9aflFOvU8PZwy7(Yixknk6dTHwr1pFs6Bf6OQqqr7oQEP9QwRE1A7zwtaTXhXC71yMnhliGnMvpU8HhoE(4QOUBCGploBzmctLVZNbD)DizqSEElHchxlA9xYXK)4wxcQiebd5(AivdYe)2N8e8wcIugjj9Tp6wloaXOqogwTqGX(bRwKXzKXeKKuvjiSwkN7mbdhwTf11PrHKaAAyzFTn6KCq2ITrugWniBqU7eKpOqW2WWV86iWdgjsP9f8qcoXMKwATRVBLGvNatTq2N1sW9z4pUculq6QQlDqGu3PXIJERgcgEb6VHOUUmEqq2bZwBW3eN4s7T2niKj10fNX07UZTxL4UCXpSWclK4trOe3MHQXf37v1oY7EHGiFqsfYi2NqXkhZ9PDj4lJ2f9Wq0pmjsk))fh8Jdxxl5tB2l42dfCfKhQbGfRCuLYbRkGuG2gVK3iOVripmCv7Wynb8BqS1mL3D3xqVi5p6JWqEgLSwTplvonAMeIDoxGprG86Fs8GOGSdvsTCjnItmZ9kPGBpz2ovLEb5RJpKN(zUvVAy33rVQ2HhuP8FpPLl)89fK37ty29o(l2kvM8rhy9cJ1xEwCjwI(6zA2Mhd5s3H6PhgwhE)r6Xtpbd0tknldmgARF(ueNqlNguf1tCcTVkOGssego1CO2NXGwHeHRak(e5sH7wrizqeowoeAlh1hk6Yr4MAzJ6A1o4qaVgg3WsbUIPwXSTp8SXy0CR9WhK40F302fjLRe4AueKfSJgaPm9GqrR9IF)F4Nd4CDikZzOiS)qNlkQ)mcVLbtkf)2FOb3eQFAmbQfHhah5f(zag9N(1bngmRYn42xEgH4TNomuM6SSJ5vLoEF1uk6AXNrLi4rp2Xc2WM0wgdvC7orQhpyH)8VwJI9UxjKOdbNSOl6c6zCwYtqDnppSM3e565GsCzuvX(cqIwh(wvlzwUCLrn1aGScuyMiJpfpQWPOtV4I3xPN76cktVpeNIxW5Txiq1yOwMHgEUE4JnHxcyFwHGLs0Vdsq1bPLwLNGn7O1htiSDqSweW0GFTrFqNdQ)u90YmPYMs)yDeLf1(ao0q0nU4yzP3s5tLoxQ0pz3N0ABY252bNz5o))t)N)
```

**Comment by mrbuds** [comment]
It seems the game doesn't fire TOOLTIP_DATA_UPDATE event correctly for this trinket.
I checked and TOOLTIP_DATA_UPDATE still fire sometime, it wasn't removed.

If it was a common problem we should make a workaround, but for now I recommend you report this problem to Blizzard with the "Issue Reporter" button
