### ISSUE TITLE
Text Positioning Slightly Off

### ISSUE THREAD

**Issue by cetraben** [WeakAuras/WeakAuras2#520]
**Describe the bug**
The text position for bottom right is currently sitting in bottom middle. (Release Version of WA 2.6.1)
There is also an issue with the text colouring of conditions. These do not appear to be applying at present.

**Do you have an error log of what happened?**
If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 

**To Reproduce**
Create an aura with text within.
Add conditions for text colouring.
Trigger Aura.

**Expected behavior**
The text to be alligned in bottom right.
For it to colour based on conditions. This exact scenario is Ironskin Brew changing colour based on duration of buff.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.6.1

**Was it working in a previous version? If yes, which was the last good one?**
2.6.0

**Additional context**
If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

```  HERE ```

**Comment by emptyrivers** [comment]
Can you provide a specific aura which you believe has an issue? I'm having trouble reproducing what you describe.

**Comment by InfusOnWoW** [comment]
I'm pretty sure rivers is referring to the second issue, not the first one. As that's also the one I can't reproduce.

The text position, is what it is. There are plans to offer finer control over the exact position.

**Comment by blub0r** [comment]
Problem with textpositioning inside the Icons too...  left or right, bottom or top, everything in the middle ... not in the corner .. thx a lot

**Comment by InfusOnWoW** [comment]
The text position will look a bit better in the next release.

**Comment by cetraben** [comment]
![image](https://user-images.githubusercontent.com/25280504/43103989-cce6b880-8ec7-11e8-8855-eafaae27d2d9.png)

The conditions set for this Ironskin Brew weak aura are as above.

I've noticed that the text colouring does not function with the option "Cooldown Text" enabled. However when adding a text value and then setting the condition to that it does work.

**Comment by asakawa-k** [comment]
I think the Cooldown Text you're referring to is a default Blizz text on the Cooldown widget used by WA. It can also be modified by addons like ElvUI and OmniCC but in all cases that text is out of WA's hands.

**Comment by cetraben** [comment]
![image](https://user-images.githubusercontent.com/25280504/43104105-2820d474-8ec8-11e8-9ead-bb9dca61458c.png)

With regards to text location, this is where bottom right is set to.

However previously it would be here:
![image](https://user-images.githubusercontent.com/25280504/43104148-56b01840-8ec8-11e8-890f-7d92ba6aa2ce.png)

**Comment by emptyrivers** [comment]
@asakawa-k is correct about the cooldown text, WeakAuras does not support modifying what happens with that. The positioning is being adjusted and fine tuned for the next release.
