### ISSUE TITLE
Preview "Glow External Element"

### ISSUE THREAD

**Issue by rakkarage** [WeakAuras/WeakAuras2#5203]
**Is your feature request related to a problem? Please describe.**

It is hard to preview WeakAuras that only use "glow external element" instead of a texture or text.

**Describe the solution you'd like**

Would it be possible to display the glow from "Glow External Element" when previewing a WeakAura?

**Describe alternatives you've considered**

I was using textures for a while but back to basics and miss the preview.

**Additional context**

Thanks.

**Comment by InfusOnWoW** [comment]
I have no idea what your issue is.

**Comment by rakkarage** [comment]
when you press the Eye button or select a weakaura, a preview is shown... the preview does not seem to include "Glow External Element".
A preview of a texture weakaura shows the texture, a preview of a text weakaura shows the text, a preview of a "glow external element" shows nothing.

**Comment by mrbuds** [comment]
> A preview of a texture weakaura shows the texture

Texture is a type of weakauras

> a preview of a text weakaura shows the text

Text is a type of weakauras

> a preview of a "glow external element" shows nothing.

"glow external element"  is not a type of weakauras, it's an action/condition, those are not played when aura is selected

**Comment by rakkarage** [comment]
Thanks. I realize it is not a type. But i do have a lot of weakauras without a text or texture, that only have "glow external element" for button glow and i think it would be nice to see a "preview" for those too. But I guess that is not how it works; I need to highlight my buttons with a texture instead of a glow to see previews? Thanks.
