### ISSUE TITLE
Remove DBM / BW Triggers for TWW?

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#5204]
WeakAuras still have DBM, BigWigs, and unified BossMods triggers

TWW is a good time to remove BigWigs and DBM specific triggers, but still keep them on cata/sod

Anyone having a strong opinion on the matter? /discuss

**Comment by MysticalOS** [comment]
TWW for sure. devs there have moved to unified.

Cata and sod I can't speak on, cause I'm not sure how well known it was they could use new one. I'd be curous if @QartemisT  has stats on that via tools that can poll the wago backend?

**Comment by InfusOnWoW** [comment]
I don't really have an opinion on that, meaning I'm fine with disabling them in TWW.
