### ISSUE TITLE
Cata Lua Error

### ISSUE THREAD

**Issue by crossfactioninstancedpvp** [WeakAuras/WeakAuras2#5211]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Just a lua error 

### WeakAuras Version

WeakAuras 5.14.1

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
1x [ADDON_ACTION_BLOCKED] AddOn '*** ForceTaint_Strong ***' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: in function `IsItemInRange'
[string "return function()"]:7: in function <[string "return function()"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/WeakAuras.lua"]:4862: in function `RunCustomTextFunc'
[string "@WeakAuras/RegionTypes/Text.lua"]:258: in function `?'
[string "@WeakAuras/SubscribableObject.lua"]:94: in function `Notify'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:622: in function `?'
[string "@WeakAuras/SubscribableObject.lua"]:94: in function `Notify'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:828: in function <...aceWeakAuras/RegionTypes/RegionPrototype.lua:826>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
```

### Reproduction Steps

think it was happening in arena

### Export String

(https://drive.google.com/file/d/15uToYgL6SFUFYW9Cfs5g5XHVwy5Bdu3C/view?usp=sharing)

**Comment by InfusOnWoW** [comment]
That error is most likely the result of an aura creating a "Secure" frame, which leads to tainting. From the information you provided it is not really visible which aura that caused, though there most likely is an warning icon in the WeakAuras Options on an aura warning about creating secure frames.

**Comment by crossfactioninstancedpvp** [comment]
> That error is most likely the result of an aura creating a "Secure" frame, which leads to tainting. From the information you provided it is not really visible which aura that caused, though there most likely is an warning icon in the WeakAuras Options on an aura warning about creating secure frames.

Thank you! Well I do use FrameSort addon to sort my raid frames.. And I use the ‘Secure’ sorting method in that addon.. could that be it even though it isn’t a WA? The only WA showing up as causing lua errors intermittently off and on is my WA to resize the resource bar (mana/rage/energy etc) on raid frames.

**Comment by InfusOnWoW** [comment]
No that doesn't look related. If you add your WeakaAuras' settings to the ticket, we can identify potential problematic auras.

**Comment by crossfactioninstancedpvp** [comment]
> No that doesn't look related. If you add your WeakaAuras' settings to the ticket, we can identify potential problematic auras.

here's the Weakauras.lua file with all my settings:

https://drive.google.com/file/d/15uToYgL6SFUFYW9Cfs5g5XHVwy5Bdu3C/view?usp=sharing

**Comment by SpatenLa** [comment]
["Melee Range Reminder."] is a non functioning aura. and the source of the issue.

**Comment by InfusOnWoW** [comment]
I've come to the same conclusion. My original explanation was wrong though, the reason is that the aura is calling IsItemInRange, which was recently changed by blizzard to no longer be useable in combat.
