### ISSUE TITLE
"Show CD of Charge" option on Cooldown Progress (Spell) bugs

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#522]
**Describe the bug**
Once the option is ticked and a number entered, the setting can not be revoked. 

**To Reproduce**
Make a new trigger for status - cooldown progress(spell) on an ability with charges. 
Tick "Show CD of Charge" and enter a number.

**Expected behavior**
The option can be unticked to stop that functionality.

** Actual behaviour**
Even when unticked the trigger will show the CD of the specified charge. Replacing the specified charge with a blank entry gives an "Invalid Value" error popup. 

**Which version of WeakAuras are you using?**
2.6.1

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
