### ISSUE TITLE
Text anchoring to nameplates is sometimes offset

### ISSUE THREAD

**Issue by hambold** [WeakAuras/WeakAuras2#5230]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hi,

on very rare occasions Text WeakAuras don't attach correctly to nameplates. I've had this issue happen for a while during normal gameplay but I was never able to reliably reproduce it until now. 

The method to reproduce it is not something you'd commonly do but it produces the same results I sometimes see during normal gameplay, leading me to believe there's a connection.

If "Set Parent to Anchor" is unchecked, the issue doesn't happen.

https://github.com/user-attachments/assets/93f9f1db-dbcd-4638-a994-79f86e17e847

### WeakAuras Version

5.15.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create a Text WeakAura, anchor it to nameplates and close options.
2. Be somewhere with nameplates visible and confirm your WA is anchored correctly.
3. Open WA options.
4. With options open, move away until nameplates disappear.
5. Close options and move back until nameplates reappear.
6. Some of the WAs should now be offset from their correct position.

### Export String

`!WA:2!DAv3YTrnu444P0HnmqQtie6ptDBHwAduAtBk)waVU2006yhwVPPPZWyRDxzVIUELqsBsCUdpmqgU0307919kFbpa9jqJhEcYJqEc4ODxNF6qGz4gVshD0r68D((oYzEsoHZs382lDZBLRtoVCE7EHroi3N7XPSI0ak)rzZMD1S36MlTNdL7H5MPlYM2mGSZoiUxEBknqsydKu3nXCbHgoFMFNY3UwRwcSmJtYg9hK8TKxBm7m1)5iehNVCuqq(19js8quORpLVkLekDkwQQDjR0nuNSd(udtgNCLYKjtwlHlkaNDFWDmpef8KKt(fCKRe(kUNLqI4sdtsirA40c(i8n6j5K2Tbxp7v5Pd)TbEyNOwTS7YW8hwQYQLxRIPeMyHI4Of7jy4GGL9eg7jICWBIdL1bVjBpSrXc1TBu3UGLTzeCioSauxm)a3wLJb3SQVAPkvSIT48qmkq6BfI6Gfg9JctVcg8UPy1RssZKzV5aoUnKl6BMvBonI1xGdAfdrQPUmXJDfB82Y8fIrU80W8vHad3cjwKNiYtJJYiuKewUglgwmg2IdovxYrsu29ta9YAt6tXPErRsLQoKe2IY7G07Wif5xoeIv2(OqsI97Potz18MH0q8RWiHoI4W2s)tpYdGnThn0GixGDPHEIEAF0hHArZoisiSx1IQ7CA1DvlPUhmCMx3IdSVwK2gwOaMpk7aDyij5Gzaf5v2uaeJ5S6ebKpdtOm5oN6(gwUbiHqpYrceKqPE4IreVH3DdurZN)WWhV9DY5EJDVgaOYasiG2Rzxz5QLulyWwWJi0LrnU2ibdAWAijDWn86cLnIBdPphl8PbEDhj8rE0T2iPAD(jugQPy5p5iKmldBA3iHK2r7XAmpOAPU0EqrIQbw31jEsFZcWu10agBOYzOMXqn7BFv17(NaeDbwUibUbYrq5X8PvOE4MQZPo)EhApX2LuxwDrvE1zn6PxsZrBQUIH6c9dhZtuZPEp1hyWoJw1Sj2oHpQ3(lNGDU)XujzGLoJ8yx9KZ2aCBKB3gTcOuUV62j8LJxZ)S)BwGzlAOKnDzozN8)qeYttBZBBpaezwXIdXzNtn)iyQURLwKe6P(QYQVwx2vFt8VFB8VFN(3E6WPBOCX0I3ttkEzvxZuc5G6nYOENxWUYjNwmo2LO70KDaOUXEX1RF9Tyx(K3shQxd4EJBA5oUJAw(pbCasRUMvkv2wDkDdtqqZJ1ZRxqvy4Zc2WK3PmH21v9XzvFs)QfwP0Qvkyxs9HzuFUXWJCEQM92cePRZrSERNoyys(Dydt1xAO(ud11DmRzBxBLDV(aciPQtJ4UyG7UGXqKN(sH9wbT9KhoHeoP(ebU9ixOrpeZW6Bry4MVA8uDhD)tGTQECm3uv5O0r1kj8qv1u(NQ2lNaW99yCABqDjsUv348tm5)BId0vxGK6wrWDBTBaKe1t2DwwoDvUXXQ9zyVFSr5rQCI0bQf7FWA8Lb8ckoSPpsmoeF3lX6bnOBZMj2YXv2QhTFY5Ca35xgL0eEJXpbeVEk9qn1aovc5GUmBwTg0LAEoq21(mi2XdPu9tta4STpwEooYJITnMPOWjN0MaB2ja3mnToYZW9HgJLSAyxB1rhe6eTtItp9yXvVACd(h44JjT9L3)FrhYMg6iviLIfZ48T2sJg3)1xHe6dAtnvT3y(wZXCFDbz(jNDbq1U)ZXywb9Jasl9Rp(GeXChkTtg2SJ3NgdFarGGS1Z)anhBM06A(pkKcpBkIWIRh3KTy6(G2HwA5BSou5O(ISG(8736zDkwR8JUtxkNeQ)Fpap7hJleQ)O5yXMAQCB(xp9V)`

**Comment by InfusOnWoW** [comment]
You didn't include your test auras in the ticket.
