### ISSUE TITLE
Add support for CHAT_MSG_COMMUNITIES_CHANNEL event

### ISSUE THREAD

**Issue by jrowles** [WeakAuras/WeakAuras2#5231]
**Is your feature request related to a problem? Please describe.**
I want to trigger a WeakAura when matching a regex filter in a community chat message.

**Describe the solution you'd like**
In the Other Events > Chat Message trigger, add the CHAT_MSG_COMMUNITIES_CHANNEL message type.
It should work with all of the existing Chat Message event options.

**Comment by jrowles** [comment]
Hey,

Thanks for adding this.  It doesn't seem to work with the Matches (Pattern) regex condition.  The same condition that I was using for channel is not working for community.

**Comment by SpatenLa** [comment]
because the text you receive isnt text. the text you recieve is basically a picture of text.
its a texture string, a secure string, something you cant read.
you cant interact with the community messages at all besides simply displaying them.
