### ISSUE TITLE
New Vampiric Touch / Vampiric Embrace

### ISSUE THREAD

**Issue by Socks123-beep** [WeakAuras/WeakAuras2#5233]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The new rune in SOD has these spells as separate spell ID's but when trying to create a weakaura they are tied to the original spell.
One spell has a 12 second duration and one has a 60 second duration that I am trying to track separately.

### WeakAuras Version

5.15.0

### World of Warcraft Flavor

Classic Era

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
see note
```

### Reproduction Steps

see note

**Comment by InfusOnWoW** [comment]
Sorry, that's far too little information to figure out what you are even trying to do.

**Comment by InfusOnWoW** [comment]
No response from user.
