### ISSUE TITLE
Cooldown tracker doesn't always find spells with the same name

### ISSUE THREAD

**Issue by seanpeters86** [WeakAuras/WeakAuras2#5238]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When tracking certain spells like Breath of Eons, I can only get the cooldown trigger to be active when using Exact Spell Match. Without checking this the trigger will never fire, even though nothing else changes.

### WeakAuras Version

WeakAuras 5.15.0-10-g8de72dd

### World of Warcraft Flavor

Beta (WoW 11.0)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No LUA errors in bugsack.
```

### Reproduction Steps

Augmentation evoker with this talent string: `CEcBytdzKfmH8fd41IZLCpDCAzMLzsNGzMbjHYmZWmBGzsBAAAAAGAAMzAsgZmpmxMzAAAAAzMzyYmZbmxYYYYYsMLWWmlhZWGmhZmGxCA`

Will not trigger the aura.

### Export String

```Text
!WA:2!1z1tVTXXvCtrKgdbueBAhfglJuwHuIyJezrMy10IIcqkrL4efk6LuXUabG7S7mC3XA5odMzwkrDkH9I6LCGx6DEPiUrif8qtcYnNVadi6XEIh6ha9jOVz2L0rn1gWIVzM38(38797T52Rq)c4c4ZQoH6ZIBZse(KBFfVJrbShS74tBHp8dECFcFgkrfYehWvuwSC1Pi8tsKkc(tOXRigEqVEsIk3uuSpOulgnw5TtJMDA4mZNXIWSJJBFmLtC5xZhUgRFhYjQd5yKI4Ly)5zl0RboGew3elUJucAqariBwwKjE26okbY)O6q4WgrvK(nr9jx9vpBEIK0ffDmAOujsiUJrjcumCM8wEV72vUFLFh)6gvciXeb1VDi74dIDNDPLtKWp1S2OEsmv5XJqdjI6QHCIJKtIIsTbi6t7r97AukuKetgqIv6RpbdztVEDa1fFyJ9BT3H77KgcoFikjgIljXeUUJTgZiw8x8wFZCzIN1cTHltpzA3DQ1Ut32DQ50zI1DPXQJvh(RVtwHQulblqqKYsVvBJ5UZZmkVOK4YVHzj5eKVQ7s3fotqqrTxSCEDyPkSeRxPgWR6SSKl9q3rwXhGLRocdftZdFHkld2wcceSoTB1y)9hzUOPy4o2izFHCN1hP8djY0ARU4ytfW(iUTNmBpDb4Pt)MfZ93(8PyQ8jjX(k6asvu8q(1rw5oP35tyyYxFLlaGfreJI(uavaXZFDopRiKcCV7TVYkJLKOEwiO(QZLkQ)rd3nl8dfdsV3RobsdhsGblF310Rpdw6bbDGGLeJp7w8ckaGcvEeuPFCg6M)62nT)PhtaPxxzMq9ywmz8YJ343W5L(zkZ7QO9jD7ZWDHWH4op1hlI261oSZb8By30GUHRq9FefRcRxdwErQPONqW2n)c(B(I8qeja5pSBVigte(mRcMMvAVH6RorWuGZn9F1BEqZg834fzL0v50RlGIJ58zPD3lkhtS3XNfXeFuE4FJZSbGrV2Ec6PLEyccdjkQuNo8F9lYlCb0lzEsYFPA(FkZjZwAuBx1bh2z)h0Sr6UhZe4hjq8rpktinvhaMZlYq1KwkFoLK(QzPWcRNPsQl3XMj5YLl)ZDAB6PK7WVZlk4XdH2BGhaibiaKoc))dJWZeCmxb7fsObHQhwpIHWN9AcASbZXxZPFsKIUQT)XWNic5fmY(riPescSL1X1siOqrqdy44LN7wh64iRPdwD0c(j36si2nBjsvVAzpj4SiYROd2U4l9F(dUfFPF4RG)CXx4o)YEznn)MFMx61alSwXC)yl3PglpGes9Ja(zJAL1886GB5kofa)anXkowZaBlEunN9pyNpg8(emfi18HKBOjyMVKI5OyGdlu0Z0LZInNnMpGV0PPvIiOsefYV5)dvw6DN8CzdnADblYMW8RbQxlB(emHcDsON0sp4r7ZzcfWtlrkdNajCkno95bcIYtbrFsdd9MmKxKgeZeKSrE2DBiemHm0WvzMn8aykvXvUX)wKMeYTDKkKqv2rAOreLsN1ncZ6A3agRbCKR61d(rg(ZItkKsclNKbRR)LopV3YdCupk8wEsgY15ydhWdDqr8quEGR0IR3ta82Tqcd6WcFwmRaypDmuoEssFaB5uzZQBwP(Pmw)w53AZ3vFD3jkMFg5yXCNpDdkMFTlpDOuv(nxmK2qFSlvIG(mS70Eg32wz61ZFXpjsmPHx7DCA0O5fhri8AguJYXuRdRMqXt9FVdRjFsJ6p89Qancg3dpil)Yc0jRunreXVDOsXL)(7DpZ3KSjLDVLFuY9QS1eOYGP2Q)Dl7aZB8pAB9R82xz0aKGAIVnoWXZUT8UWb51pDclErzXzakkHKpD)Pw40H2KsFEoHFikoaMDxwFU7iymdq)OgQ)ZL1FL1b6NwTwZD1)9mRQ)A9553de3GXl8h1pDo5eonDQthOVxF(gBVL(Bmg7xP)h8BauQWtWL4zgTO4cF7smnfrUT(VSNED9UpJGKMkmjoqf(YZwmoUR5ltGIMPgihz0XIC2TEFen(tnxu)9W))NVShqZcWMjw4sRKijr)T6Vt)LwJdNBxbQwqYlC)nRC)n36DQS17e8(yYVTkgxyW)6X)3)
```

**Comment by InfusOnWoW** [comment]
I cannot reproduce that. 

But, this sounds very much like the issue described here: https://github.com/Stanzilla/WoWUIBugs/issues/354  There's unfortunately a bug in WoW, where certain spells do not return cooldown information if we ask with a name. Enabling the "Exact Spell Match" fixes those spells, because WA then asks for the cooldown information not via the spell name, but via the spell id.

And thus it might require multiple spec information, or even depend on the hero talents choosen, and or the order in which specs are activated. See that ticket for some more information and speculation.

If you can figure out the exact circumstances to reproduce that, I can take another look to see if we could workaround it.
