### ISSUE TITLE
Dragonriding / skyriding issue after WW pre-patch update

### ISSUE THREAD

**Issue by KungenSam** [WeakAuras/WeakAuras2#5243]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Since the WW pre-patch update, my dragonriding / skyriding replacement auras stay active even though they are set to only load while "Dragonriding."

### WeakAuras Version

5.15.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Toggle "Dragonriding" under the "Load" tab

### Last Good Version

Unsure. Haven't updated for a few days.

**Comment by InfusOnWoW** [comment]
I cannot reproduce any issues either.
