### ISSUE TITLE
Ever since 5.14.0 inactive spell cooldown triggers don't provide icon information anymore, I used this and would like it back

### ISSUE THREAD

**Issue by Weberkraut** [WeakAuras/WeakAuras2#5244]
**Is your feature request related to a problem? Please describe.**
In 5.14.0 a change was made, so that inactive spell cooldown triggers can't provide icon information anymore. 

Because using animations with conditions is pretty messy, I use two weakauras for each spell, a desaturated, 10% alpha one which shows "when a spell has no more charges/is on cooldown or in combat" and then a regular one that shows on top of the other one when certain conditions are fulfilled that make you want to use the spell (pandemic threshold for dots/certain ressources are available etc.) as can be seen in this gif:

![image](https://media.wago.io/screenshots/4yz3N1TG7/5fb91986ff5bba046b74ef7f.gif)

These desaturated auras do not show the spell icon anymore as of 5.14.0 if only the "in combat" trigger is active. 

![image](https://github.com/user-attachments/assets/a897f26b-69fe-453a-9138-3332dd28b8ba)

![image](https://github.com/user-attachments/assets/28e02254-fe3b-4931-be4e-a1d4130437a7)

**Describe the solution you'd like**
I would like if you choose a spell cooldown trigger as icon source, that it would always provide icon information, even if the trigger isn't active at the moment, how it was before 5.14.0.

**Describe alternatives you've considered**
For most of the spells I can fix this by using a fallback icon, however some spells change icon under certain conditions (Lava Burst when talented into Elemental Blast, Chaos Strike during Metamorphosis, Stormstrike during Ascendance, etc.) and I would like for my auras to reflect that. As a workaround right now I can add another spell cooldown trigger that is always active and exclusively use it for icon information, but it would be much neater if the behaviour could be reverted to before 5.14.0.

**Comment by InfusOnWoW** [comment]
A trigger that is not active has no useful information in its state, that's by design.

You can set your desired icon as the "manual icon" and set icon source on Automatic. This wil make the aura use the manual icon if no trigger provides an icon.
