### ISSUE TITLE
Glow code error on option open

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#5249]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Error when opening options

### WeakAuras Version

e163a50df99321797e2d02fbf19fd3ebf0c20474

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
3x WeakAuras/SubRegionTypes/Glow.lua:219: attempt to call field 'glowStop' (a nil value)
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:219: in function SetVisible'
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:399: in function modify'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:818: in function modifyFinish'
[string "@WeakAuras/RegionTypes/Icon.lua"]:631: in function modify'
```

### Reproduction Steps

- Open options

[WeakAuras.zip](https://github.com/user-attachments/files/16367336/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
User error.
