### ISSUE TITLE
Scrollbar sometimes gets stuck at top

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#525]
**Describe the bug**
Often when opening the options the scrollbar gets stuck at the top and refuses to scroll down until I click on the down button or in the bar.

**To Reproduce**
1. /wa
2. Try to scroll

**Expected behavior**
Expect to scroll down without issue.

**Screenshots**
Video: https://www.dropbox.com/s/38k9zm9kjn23hma/20180723-ScrollbarStickTests.mkv?dl=0

Video 2: https://www.dropbox.com/s/iicc1qh6tnawofw/20180723-ScrollbarStick2.mkv?dl=0

In video 2 you can see that the first time I opened WeakAuras it did not stick, but after scrolling back to the top and opening it again, it did.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
2.6.3

**Was it working in a previous version? If yes, which was the last good one?**
Has been happening for quite awhile.

**Additional context**
Saved Variables: https://www.dropbox.com/s/aa5p6uwm724k3tn/2018-07-23_WeakAuras.lua?dl=0

* Does not always happen.
* Will both start to happen after closing and opening the window as well as continue happening if I don't click the scroll bar/buttons.
* Does not happen after I click the scroll bar/button if I leave it scrolled down some.
* If I move the scroll back up to the top, it happens repeatedly again.

**Comment by emptyrivers** [comment]
As a workaround, collapse the group, and it won't stick so much. If the group is too big to navigate without scrolling, consider using smaller groups :)

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
