### ISSUE TITLE
The bug is in your aura "Flurry Usable': Trigger 2", which is using custom code that no longer works.

### ISSUE THREAD

**Issue by JeeveStobs** [WeakAuras/WeakAuras2#5250]
The bug is in your aura "Flurry Usable': Trigger 2", which is using custom code that no longer works.

_Originally posted by @InfusOnWoW in https://github.com/WeakAuras/WeakAuras2/issues/5248#issuecomment-2248862024_
            

Range Check isn't a custom code.

![image](https://user-images.githubusercontent.com/15347708/351880526-970119c0-9261-44ab-bf6b-eaafa684bb63.png)

**Comment by JeeveStobs** [comment]
![image](https://github.com/user-attachments/assets/81546ed8-241b-4976-a993-406fa3846738)

**Comment by InfusOnWoW** [comment]
Do not create new tickets.
