### ISSUE TITLE
Recent Update Deleted All Auras

### ISSUE THREAD

**Issue by Odessa1512** [WeakAuras/WeakAuras2#5251]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

As the title says..after the recent release on 7/23/24 I updated the addon, only to login and find all my auras, easily over 800 had now all been deleted for some reason.

Is this a known issue? Can I recover these somehow? I am really, REALLY not looking forward to making all these auras again across 13 characters and multiple specs/talents for each and every single one of them.

### WeakAuras Version

WeakAuras 5.15.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

None

### Last Good Version

WeakAuras 5.15.0.

**Comment by InfusOnWoW** [comment]
Nothing in WA deletes all auras. It's either that the game didn't properly save your settings. Or that you are having lua issues.

I'll paste our general help from the discord:
If you login and your WeakAura's are missing, go to the World of Warcraft\_retail_\WTF\Account\<ACCOUNTNAME>\SavedVariables folder and check the WeakAuras.lua file. If it is empty, check the WeakAuras.lua.bak file. If that one has content, MAKE A BACKUP of the .bak file, then close the game, delete WeakAuras.lua and rename WeakAuras.lua.bak to WeakAuras.lua. If WeakAuras.lua.bak was also empty,  you will need to to rely on backups or remake your Auras. Not enough space on your hard drive is a common reason for losing your WeakAuras.

*Window's hides file extensions by default so you will need to turn these on which you can do by going to Control Panel > Appearance and Personalistion > File Explorer Options > View tab in the new window and untick Hide extensions for known file types 

If you have not made backups or don't use the WA Companion (it makes backups for you) then as a last resort you can try putting the following in to chat in game:

/run local L=WeakAuras.LoadFromArchive local h,m=L("Repository","history"),L("Repository","migration")for _,r in ipairs{h,m}do for _,s in pairs(r.stores)do local d=s:Load()WeakAurasSaved.displays[d.id]=d end end C_UI.Reload()

Note that if your WeakAuras.lua file is not empty, asking on the discord will probably be worth a shot.
