### ISSUE TITLE
Delay in text-to-speech actions

### ISSUE THREAD

**Issue by th3ufo** [WeakAuras/WeakAuras2#5257]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The voice messages that i get via text-to-speech chat message (Actions) are delay in all weak auras. In the past they were played immediately as soon as triggers met the condition and now there's a big delay of 5-10 seconds.

### WeakAuras Version

5.15.3

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Add text-to-speech chat message in Actions and trigger the weak aura, notice the delay between when the trigger happened and when the voice message was played
![image](https://github.com/user-attachments/assets/21df946b-e67b-4b39-92f2-ce243899d099)

**Comment by InfusOnWoW** [comment]
That's not something we can affect. We send the TTS request to the game, and it handles it from there. It's known that they can play out of order and or with a delay.
