### ISSUE TITLE
"Disabled Spell Known Check" in Cooldown/Charges/Count Trigger no longer provides icon information.

### ISSUE THREAD

**Issue by ph-Phobic** [WeakAuras/WeakAuras2#5259]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues.

### Description

Previously, selecting "disabled spell known check" would provide an icon to still be displayed even when the spell isn't known.

![image](https://github.com/user-attachments/assets/7d68c1da-1db6-4a4f-aefe-b6943904db93)

(This dragon's breath weakaura I've used since forever to display the icon even if I'm not spec'd into it)

However since one of the recent updates to weakauras this functionality seems to be broken.

![image](https://github.com/user-attachments/assets/b95bf656-fce4-4f7b-81d8-75be921959d3)

The icon is left blank with just the border.

### WeakAuras Version

5.15.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No Lua Error present.
```

### Reproduction Steps

1. Create an icon weakaura with a trigger to track the cooldown/charges/count.
2. Create the trigger for a spell that is not always known, such as Dragon's Breath for mage.
3. Tick "Disabled Spell Known Check" in the extra options section of the trigger.
4. Icon information isn't displayed even though it should be when "Disabled Spell Known Check" is ticked.

### Last Good Version

5.14.X

### Screenshots

![image](https://github.com/user-attachments/assets/0962fd18-e180-470b-b0dc-23f3d370571a)

![image](https://github.com/user-attachments/assets/055bcdde-3b00-4fcc-a087-b01e7c58c455)

![image](https://github.com/user-attachments/assets/e54fb27a-50a7-4f53-955e-d700948dcb20)

All spells that I have used in the past with "disabled spell known check", and now none of the icons are displayed unless the spell is known.

![image](https://github.com/user-attachments/assets/1e3360f2-0757-42fb-afea-3e7988e9e3e1)

**Comment by InfusOnWoW** [comment]
Unfortunately that's a change in the base API, the game no longer gives us information on the textures if the spell is unknown and we ask via the spell name.

You can either:
* Enable the "Excact Spell Match" option, which makes WA ask via the spell id. (And we'll probably have to make that the defaultat some point.)
* Set the icon manually on the display tab. Note that currently you have to set the Icon Mode to "Manual".
