### ISSUE TITLE
Feature request: spell not known

### ISSUE THREAD

**Issue by LootFever** [WeakAuras/WeakAuras2#526]
**Is your feature request related to a problem? Please describe.**
E.g. Combo point auras that change the max number of combo points.
Everytime blizz moves the specific talents around the aura breaks and has to be fixed.

**Describe the solution you'd like**
A simple invert function to the spell known load condition could help with that.

**Describe alternatives you've considered**
Something that could help even in other scenarios would be a custom load condition.
But I'm not sure if the is doable.

**Additional context**
PS: 
Also a menu like triggers just for load conditions would be something for the future.
I think that would be a little bit cleaner.

**Comment by InfusOnWoW** [comment]
That's not trivial to add. I don't see a bug usage of that apart from what you mentioned,  and talents don't move around that often.
