### ISSUE TITLE
Adding a "Neutral" value for Hostility in Unit Characteristics

### ISSUE THREAD

**Issue by Aishuu87** [WeakAuras/WeakAuras2#5262]
There is a "Friendly" value, an "Hostile" value already, but it would be nice to have a "Neutral" value too.
So far, I have to make a custom trigger for that specific unit type ( function() return UnitReaction("targettarget", "player"), and the stack ID for neutral is 4 ).

For example, if I want to color code an element in green for friendly, red for hostile, and yellow for neutral, first ones are doable with the built-in characteristic preset, not the latest.

**Comment by InfusOnWoW** [comment]
There are multiple classifications for the unit's relationship with the player. These triggers follow the one that the nameplates use for visibility. Which doesn't distinguish between friendly, neutral and hostile, but only has two classes.
