### ISSUE TITLE
Memory usage increasing by .1-2 MB every second

### ISSUE THREAD

**Issue by drake236** [WeakAuras/WeakAuras2#5270]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The WA addon memory usage is increasing every second by .1-2 MB.

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Hovering over information (ESC) shows increasing numbers.  Deleted many larger WAs.  Accessed unused character which had very few active WAs

### Screenshots

![image](https://github.com/user-attachments/assets/359e5f8a-2e4e-4b9e-a6e8-9889878840d1)
![image](https://github.com/user-attachments/assets/bf20ee27-0c4f-4275-afe7-62eee6f1fba6)
![image](https://github.com/user-attachments/assets/c60fd760-742f-4212-b512-b56b2dc25fe2)
[WeakAuras.zip](https://github.com/user-attachments/files/16417298/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
That's not a problem.
