### ISSUE TITLE
Active Class/Spec trigger not functionning with Mage specs 

### ISSUE THREAD

**Issue by Aishuu87** [WeakAuras/WeakAuras2#5277]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello ! 

It looks like the class/spec trigger is not passing parameters correctly for the Conditions tab for MAGE specs only

### WeakAuras Version

WA 5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Trying to change colors of bars with each specs, the mage ones are the only one not triggering
.

**Comment by mrbuds** [comment]
We need an export of the aura you made

**Comment by Aishuu87** [comment]
`!WA:2!vIvxSn11DC7EfQTUcsIjeGu(4kwxkHYYWo4G5HkW2XH4r(W9ANcbcK7xh77fCU3Ro3RnjTfTo)eV2WejmkdueVoPjRk6EPuefTTh2Ko1dHkPqHfA3OQF8qKw12ll78X12yJlIXd5C85())V)F(7)5i8oG)P8R6x9m9jN3gaNCgVS1P9cNE0mzSboEljPEI82oa1HLM(5Q9dDJNdotvrmu0mHjn1nCKJfFK0XfSAxfyl5Khk5aIkPCYSqZ8gQALSLMcKgmn(daXhxMbmHaxzk6a1ZMfaT)dVixxq3FC1OoZybIM3q3XYp2fNus22ekpiqk3WMQaXLSZldkamCsLptg9PlnzSiPspzQ0resVunXPIkqLZQ9XWyXhttckP4aG62o6k2vHjjeGHrivY4dnurBlqUCjuT9vKafXhefmWbITpulYw5KMbaxqfiJTCAStchm(qjhySHMnVHRZ7Rl0QVkAnOwqTkIAd5hTwru7cjnpfaIp7LrBWhAJIOo9H6aTE0MqBgTfIg)Xg1aToIa3G4d6gXmNswYr0vxcky9RQ7TxGif2VvsOk2iolelNKT9ppf(RulYxffzhjywGtDqD1M7g1C6wq)KAsNbTgbjCfn4Yyhi(04uBkwYtKid08ugJAKBgXBqKHMw1vTpICVH7l4UctwcS3(KdeoCW9UlHDhouG9q)ByA8vbF0RG(PSiUlr0REc5abcfyVbWAfA3bdgnWEcVB2rbJgkyGqcbc0BW9uZb)HhlCwYIucM0exZKCmHDUTx)1NLK3OhRHJ0TsJ0nkol9esh4RsI716g3VC5Qst(MyZTcQxcWODZaeNZiygATUa5w56RIYLu1TprEdfh9cazfmxZCkl)S10SUPHmZQRy1tgQqMgB3PBEiaZIm4DoAWJXlzOYVDNJ27X4nH4tcDSU5bgQwTjrH0fdcryvfXNhXiBoWnFHLXmxa0qk3BI5DyqNBjlOzwiW2oLzEOcyhBYZZnRnixgkhh9cl4yQuGj6g8(7(9fHMoseNXB0mMyUvRda1Fl(3iVKkoXkXNo9cyELailwc7o7aTMY4FkxDQGSgqpRMZDwU2rXmZzc)fdUV)6M38(94X7tUHlAotj1cwTsQayRK10aQRQBKvJvtaoy2HtoGgULohMp3HWu5Z5O7J(1canDLCGX01IsOiDGgYNGcHtq2f1w)TaKnYtPdHMqnQnI4o3JoguZQTAUQ70mR(sqsHzKuatervfhOtCiG0jJq6ZNGs1PBhgOQlnb7uYF7vwbAAHN3A1wMQJaRazp1b5OyiJOBRLppdK45kmwIjIPdXHsMCsobxUgcvYFF5TU1d84XZG77V3wB80n3(23(bK83Ssg6trRz9jyJP9oNzDYkeTe4KTvW5SPtYTREcXolkhB9aC08NduYWgBrG4Surha3kAD2QnKvAD2jpf4d7UooELi9HDxhVBF84)527YeL)14RQo)o43otb(FM7N7U7ky1ubhVIGJ3D3(Wn3(WSWWmxKmyUSn2XjDAPiNueiztpwMSjHr5QrfnCo9Zq4OcY5iDy31NHWHj)pwmubfIJZkbZqlbcs5S0K8kt5yaV(NziV(N2Bn3LedwTvj2sx5ywflchDIgfoXBqI0uoqGrwhTxQOk5MxCegCx9eUCLFmjzsg0gOyAOAhDkjDJbqRjQHPbaz(8iiYgPIYlNr3a3jEM1HokhAcQxIogh64COjfrIijsEhjJuWYcqzqzrAmz09IorLaaDsuo0uCidrK5lHSWorqc8lzpLPPJws38IyJSpDdTfG0jjK4E5k5phgLjyED1saB53i2BMkwFf6Ewzm5xLmTti6qXhPF69ocvgwX4EZ4DwCcZWHiLCIrsLO)4cNsx1r7oLYaX3YJty4Hypp5zcK5x9HoIVO4W3XhQGVLDT7HGswuReBOidNSiziyk8yKnwubp(M4FABtx9g0Xa8mglsNBz2ZMgGyeAJyQycXJpYc0Ud2G5vJRIgz0Z6dQBqM3c0klL3bR0OwuNXxjtOoE8gnEMn2qJg7GhkrQ4lqQE6ujU8M6sqrdOCYbqREvflib1LW5e0OcfKYLhuQ)4rsp4bhjXbgm92mTW3tbv0KmYcS7Sl084biF3Pp9LPZn(NF4hED6Mh9z3bV6HRio1BrU4dD4UqNdJ(o9GMlyKr6NHJm1O27a)bo0COrzNIMhDE8jRgnh09rvvpFhOFJRnF08ZZm1hV1TUVvw5)Ih6FXl(XRSYkCOluXyViAoz2ZBQaWh0svaqT2kBy3J(3)h2g3WOEaqxcn)nBXv)k6wUC57Jn1G77R(x)GhQU)T1Uw(61DvpEaHtHdp6idog5vVvr5lDCExQY)5nSH9t3817DVInbf08c9lmwI(RZl4gCF3FYjzaCL2BVbRJtEOFB102Rv1MF)xCFMdx1ZV7et8UnrxSw7SHOEXfxCfAuVyNDs8xUgZuvS3np6)xzk3S8hC0gS339rFe7EP)06xpp9EDuYKInr3k2T9jQQ7xF(ZZApwQuPRx3DA)ivi5gkoFvOqU1K7SiZXV39(cp1dGRJ)RAWVFw6SQRDp6Wroq8AD2mUd(64379y0QV5TF7M3y(lBWYF778omnU)LUelQ)KZE2lvpPWTJkkUF8G1PUxCh1sLl)GNsBm6k1AKo(Xz9EF7DVhZDFyV9U)M28kNuir8uPRV7LJ7jdNxP1gINQzGB43plt(p6OJNgptqy0dmw8AmKV)AxJ1cT4rosdD5TGMlQTM5PQOkxTEwbbrQs3I(WiVCnjKsnyKHJms95pmxAtBI108nF(D98uAu)1Twle)0pL5HFcLxGb5rtpDZR2xPX0Z9U4fVovLpRYaKh2CYv1XFTwl18xE)3NP812Yw2F9Kz3GeEOiccjgvObRwTR(HN9SSQZNFHlC96zgUJqG9goyF7kmFdiCNXhN178agFgxwp35U8tBaw3pP1RYYC3q1TKUb(9TSNS6ZQ1Apa39)ec)2YH6jqOE2T)c36W)Vp`

My bad !

**Comment by mrbuds** [comment]
There is 2 problems with your example

- we want a minimal example, this one has 9 triggers and 29 conditions
- trigger 4 for class and specialization is incorrectly setup
![image](https://github.com/user-attachments/assets/5747501b-122a-423d-9167-4ecc9c7940ae)
- some conditions are incorrectly setup
![image](https://github.com/user-attachments/assets/2abccd82-53f0-4137-8449-9b9a33edb4f6)

**Comment by Aishuu87** [comment]
Ok my bad, I had a weird corrupted aura yesterday and I had to redo this aura from scratch, I totally overlooked the ticked option in the trigger. Unticking made it work again. Sorry and thanks for your help !
