### ISSUE TITLE
Model extends beyond background by 1px right and down

### ISSUE THREAD

**Issue by wing5wong** [WeakAuras/WeakAuras2#5281]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

i add a model to a progress bar
i expect the model to be the same dimensions as the bar

instead, the model is 1px wider and higher than the bar (or offset 1/1)

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

create a progress bar weakaura.
add a model element behind the background element

observe the problem

### Last Good Version

unknown

### Screenshots

![image](https://github.com/user-attachments/assets/5a1ec1e7-b5c2-405d-a072-56e85553bee8)
![image](https://github.com/user-attachments/assets/cab7c093-2297-432b-ae5e-7bf02f192fec)

### Export String

```Text
!WA:2!Dv1tlUTruCR4dTO2djUu3siem5qOusceVD38hiS1YXo2HDTDKT3DBjG3rAgBnjYZOoZihBxkf8PCRGHqVw85wO4pbH8jqyAVxm5tWEOqV003iPD92OdAM3tV)nVF)EJmQMByoCo8lV3czas88dPyL3N(M49n73xsuhzScfQ84IMbkkNjnxIWpluQi49rJVWgbk7cIjjUu7R)UF6DVotgJLiMl4zloLPCkxPrNk2ZLe)(XkI(qbYnoK7ylviHY0PpLrLEMwWI66ZX8EUqS5d9CswVMP5Q4kZMRqApncU0)tEFoMyvQBNMN4GCF(abpKHlZ95IhNfEMPe0bdiczJRls3(3wQjbeRqiFb5cLKEihjx4uJG81X64LjjUN2QLqrQiHby49cmXjSF)oGArTk71QA39wVX9yxTjJimLDl(liIOpZjWhnHiCIvkdUC3g170RvZdRy3RQDLN0f6n3pXK1YWeRAji9PJTB3QYE7ntgq89RJLM2m0qcS46rCFE0vNPZQU8p(m)AdfgD8YELl1UtV2Dkz35KKtXbibf54tKb7(9MfGhegt1TnKFlbFGGiLfEqHBFJ4Vnc5hsarLiKCdtf0G9pt6hMhYsBGMlXu5ZczaqoIueXMeCju8(ojFx3k(1mlOUCwp3ZqIta4NiG8EaGgqb8ZRdslG28qHl5lVsMlmhXOdJr1DI(OQVHGKK2kbHnq59br5TyCgzfoueBrm(iKeily5mTPAKjAhRHikRA02Gdr7eDNO7gDpy9JFFnZCqIuAIHrwaBLiLoYeVZpi8nglGwSnzGMYE)xEPIOaQ3AW1EdHdPFpxFAG3YK9svVq5t2iiMAKkG8d8qzFtIqFQpPo2P4wBV1w3DJ1QjgIeHjgNlgJF7fNjoL5Fo9N3i1yJO8ZG6mwtAuMASkzZiQKceGJpN9tpnvJnYhLFf45MrNuf95csIchpcDGN6FwPiJHoejbTkUx79T85iCvhGLamW82dd9vutlG16Mp6iGT6JKs9oljDkrVzDCN1cmhR5ifl9WhgCrGmxk9(K4Rx8wszq2tObMIXPxV86Y)4)MbEc(KbceMczSPq)o2Sf1AAx)BB2OtP9S00oVz8rebmAjV8JRT7F1Q1XGNzRT7F(Qx9lWvuzxlhY5kVtNao(9RckZBHig0JN2raXaW8KBl3C3scrPtsBj4lQR539rUKNwgjvu2alK4PDRFZns3ST2H5XdgskMyBx)r16CsYfMvfWqUoDoTlBxPsd7ewZY4KulgdEGifdwx2NhIlatskQlY)KtpTP1YLNz5tNofjWwt58Hg2XXWBHI7okz47Zn(TFpnYumMWSBu5Gk2xJIpPNIivfIPhfUDW4L91LfmeIuOS2Vq)NI3E1IHu8Yrh29ofl6Y2M1Wboq9PdmfuMo(eV4z)eIYvYSKVbOICwONxPj)vz(PZGfH(jGkeM(QQhLIVE5KoBFRBV9T(QCJ(JJ(V
```

**Comment by InfusOnWoW** [comment]
I don't think we can fix that. We position the model exactly on the same coordinates as the foreground/background, but the game does render it differently from the textures. It probably automatically snaps to the pixel grid, but even if the texture is on the pixel grid with the model, they don't appear to overlap. I think that's because fundamentally textures and models are treated very differently by the game engine.

I think this worked before TWW, because we set SetClipsChildren on the frame, but that api no longer works in TWW for models, so I believe this is not something we can fix.

**Comment by wing5wong** [comment]
Understood. 

Applying a border covers it anyway so it’s relatively minor.
