### ISSUE TITLE
Cooldown Progress (Item) and Cooldown Progress (Slot) occasionally not triggered after login

### ISSUE THREAD

**Issue by Nokramx** [WeakAuras/WeakAuras2#5282]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

hello :)

i have a set of weakauras including "Cooldown Progress (Item)" and "Cooldown Progress (Slot)" wa's.

occasionally when i log into the game, some of the wa's in the example group won't show up and i either have to open the wa options or do a /reload to make them show up. 

(This only happens after a initial login!)

I started noticing that in wow patch 10.2, but it happened very rarely since then. I feel like since when the prepatch dropped it is happening at a increased rate.

This issue might be hard to reproduce for you because most of the time all wa's in the group which are supposed to be triggered are indeed showing up, but yeah, sometimes they do not.

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. log in on any character (optimally it has 2 on use trinkets and some other usable item equipped)
2. observe how sometimes not all wa's in the group are showing up, even tho they should.

### Export String

```Text
!WA:2!DIvFWX11vD)0Mut3OMSETJWr2oDJRJITsq2AL)O1qkJwPvXYDTK6tsXPec79TV3D33Z(TV3Z33BL06oLozBgqzstbeLegkjalPaH(bLLqHHVrtzg4pyMdkLoBtyOtfnqdLYaMpkFg4CU33URKLDMmr)HEV9(X5EUN7VZVZV7t7Hthw6uJm6Pg5KPRM2kT1QJUMHWSa3RsK9tmWML8fwCrodZlBj8dcsLZ15Qx1qyLzbFF3iNGnmQfz7lMniYX3lmPO(SLlhYJ0Aur4yTq9a(H1NSLYit476loVMMwc9Wadt(UfgMYzDA9WidruYsLD8CcTtMdFeLSrKWPsfUiCWHeXV(J00IxQw5YKDfNlFH5MAXc5IWFOButyKTrya31DARWKBgwReFjUx084ODwPvXjgF(fko)cJRVqUAOXlf4AuNl09mQYdtQlhAPZXnCJS7o15eCCQ6Zpx(cfwRMxSlKSLPVBTQEZt7GeLegwo1cFI(xlK7wEoFhVOCfYp1c6gUov8knr(zwiVUa3D0u1AIMwNxrgOWreyBKiNRVH1uLImCXvCa9Q1WyAYC4(WCay4K6MUgHH0B5cDUkNEzJsXhfQOzIejMlXjg5unlxZ1DchHPlNjm8CQAeXTBz4zINns3coIEOjUkjAAIRexipAkOxsD0y3u9mVvfEWEM)k1me8mtHMmZfTDI4nfsVMMZ6w1XGMJzfHFTG4znp6B3QURtvNOBtSIca8e93q4hzqNVAxZHwrpd3hgpnXgE2sM(ELDQKCt8jgC8IMcrc(Is6Jp50lo)AHr8GX9Q4YF3RRwaLjFNOfxwf3Bg5BUKYy7x7Z9foSJLi)kgvdC5TklWZ05JegrgjwJaHx0XkY(2UMkwmf1lTpkn)e65ZptJAH8cKJBhdsN2dxPeRPcHO5pnCBtTo3iKmPmNy3q6CE(E8nSqihnIIeaueYX9IvydAOK9HzYv1WXBk4c4eGzGzH5Gpi(S)RVLCyKCzD9PFOZTq2AowTM6sNFSQN8kJ)Wf8AsM0rLy1YXRSVq5tiAWxebZK288RosthCuZ7xtyYp4UGVxTwgwxQggbTUGXk917hoE9bVdnyu4iByIzUw(l7n)YobCwqktCe(vxGVs0IbwiUPun5J17mocuyNJwggC7F(HG74RiWO2myG0EDkVtM15yfoCPXoZONi77v94K42YBwp36myq4aWDLeUtyGRHtepOmJMxLPYG9Le(UH9VgzhvYigB2lCq4qqkypWDNexUvpOoECAE5CivJFdeowLw793336z3enxrJsy0O0f8T4SnQW94chZ5T9xEwVMH4JXDx2OEiTgTObtnvX0YEnbNoEC8QKD0SNa9ociuKOgq3ny)teV1ZmNWVIGhgM5OtJR7Xi)VO0zmTneyyPjrhPwU1dLpgh50qOznpjjcCjeUqU8g0m7UO2uWG2Hn6GIsp660i6S7yb7L(jNIvfLbyzRBiqoQ578ZjhxA1EDJrZ1c71Bq6UlyrFeJAG5yP)(OG7AD3hSG9qVVTahdU7bGQGhf7tbFygEKScCzkGdlJBORMEuObdQUPAd3jwrXy4JOfKwUp8mDRzXNqgLczQgv7MUBr4JQb)Wy4UjfAZmHpYXcpol(CVLLt4LQ5jdMLui0G0XivftCb)koMbVVYYb57D0yc6JLmd(NGhvt4LjUThD0hlJVO7VY(yj5Ewb7XqA9yZraOp7UGh8z3mi(mxLun8b3vFqbIgOBwlMatPY67OL(V(wW6vHgr0rm3gg68daP3aRbqu4e)PNvzi9AudsQNygOIevFIyMVIMDlAgxkU4soHoLqA(odNJPNIrZmNZkC3nIBZxsyMy13tWDhH51fL)tXFumOyKtvE8V0cURDmGW4xGzwRBF5U3XgjmiL83H2g45DVQ5xtnzC9vCTpEqMDyZrhz7lBtzXbor6KBMzNjFW7EhtrLH1ZzAk70StzVebP3I38HuLio4U2q24Yyy4IcJGgxm(L1Ln3j0fm0owTSJew0IBIS(Ufde4luTLeBepeuibEOCOnufrEKyno3Gyxq8l60M1AtLh2rAaCKG9kBHiYiQCtz8k344pJnD8(qt5Ve3Tt5648Ep38iApVfslqWenO4yZ2C3eR1DZ0m)kbechPgdo2ndGexOVyKnouBmhV(2SA3iEW9FZ9TBGnsTfBiJkRp9mZKxVyUzxyHzVqWb2HXqGxxmWnOBATI7(fVbDNDRZERiMorLG75Mfa6fydo4nWUbJ01W9GjsLPZU4cfMEM8REy43pb8SiHWpD6ta)mYCf4t94WpRg8CWZd)Cyh)8sKm8lGvUBc)IWlydF6eWV0HGFzn4xbEr4xfoc8zGpl850Gpp(6VgEcdFb4xpb0c(nGFtCsFX6Wlvh(TGFB43bh(VlAXNrd(9sa)b4B)HWFujBUtf7OPHJ(mYkfb8OsgrrUC7nLklXJblQ8H5qLcDibxpnm8Q7Xkf7BKI9ryFu2JZULuSNif7Lz7lf7tMIDKuSxif7LEu2x6rzVuk2hJ9NZGJne8LUxy4Hoe7EzW9J)ibm8Gm5YTe32bfKUOJn8ayhTMm)fMDMZTiPjggEa9j1xC6jzcL23SjL1KOQMcB47bL6(mncrPQgchFw2iUhRz0Y44QxgPSznWiFu9QgEm9a8MdOgJzW2C5RitVlPgjlBWsbO(g0UJhldsQkYoBnHBFWJmul0kM88uDASe1(rf7(cE8nzKTMxi8fHm4EWGFsSeqs4DLe6pzqQTiMu(VG9K3DPfNUyodXPZvlkY3llCgWytm918Y1NmUgVn8(tcNdMgUVeyXNEMyouTTxKTEpUTCx13V6C3Yjgz0tgSVo6WiYYjDcnWTOLnCjgmzS23GdK3LxfnHHBM58PvkJFz8TL5ImzLLE7uJglYPJ0UmyQe6ltCptd3AsyXwJLDISNZwFXjVYjfoEKYAo7AxMJYWj0rKo5(2xFK0b3qx8SdPBAZnV8PH74b2vJLWJlY)Yo(mtws2E4WypjGxlhjwqFjd3ACnSLBfETM(9Ko86jeiDVhs3p4qWRZAGLGX8OO6Wtpe8nuga(M4OGV1zX(TH)HG0it3iJnYwP1hOtZN86Bg(6OzMI8Wd7hC4h8brR93c)DdJTSB41kH3ab9Z4EE90NO36PHRhn9Vn5u4Z)r855p33)R(PO)EUD(scCmVsJoNxSvpo8dGjPVIkj)r7d(b7ObhEmg8dbfHxo4a2rrbHN94hFzJk(J44F8CN)mxrV8eN7mhF0oyUHGvpCYKRz5xujaYgXGWT)ji5zdb2dQpw2XEFNydKjcJ4HkjCWsYtRIrQBP)WuC3wQEvDd6jO0FBOcl4o36q6jt89J6(6QiDEx)OyfPr8WOP8fDo5y4v4QwYXJFb1Ql1CxarEHrOIXeJ8njj6peDxrSYnkWZgCzK0sseART4G2s1JLzn6SC3djXCqiukhSgSeuYwPuLaKoLXAkKyDetgBGUEElzC4O339gEFhdmhS0ON(uNASrLsyjHR31Gb7PqnKwjt(QbugcL3iL1skY3xY1lZXPh)XnSv6wv3WG(8aYBzGLr2siBMAvlXfjabB9T2CFOgw4hnRHxD4jdU)3IIujzPWtLafHcBAlzDABlIVNBcyOHr9JWNOm8Jt1b(XGFcvfL1yWpj8jHFQeWFms0VAAyDB4ptX4kU446fMDIpaY22w72y5e(UYpIW16CWYVsn8oG41Wic3KWFQ8)ht()Uu5IRI32DARW(AA5ugd81CJQtJynKDn(7wqJ)pXU1wS4G0zpsLi)mbu)IYQp2d9oMHGSR41(XLy3OVTB0ZWB1lnZg2WFLn8XLQU)NyWFJnXJsxgG(IntJ3bTJyCsKnj2UNy8RRL(3rlgmIa((saFvBjn8ujGxvrYUn20rUi3iW37SzMeVTfbUrf1pqMciJmrRgzZZ8qyhrzMOowCltw4PTH)Ag81IPsR6C1OJwYFQrxoa(6mGzJ3jhU4G94X(7L8ydgtP80yDi4lZG)YoSf3qAc4FMC(EP8W)c8VI5e)B2W)oLedFhmFDWGdFdU2AE68GW4zOSQJb)hm4)Kb)xW)nCzn4)PB6OGb)VQlLwMrPIT1Uvg8ghGY8ARDl2Y0N)pBmFQTwFyQO8c6Q0P2AjARTR2AAYKi868uclM7(HzT1Ehyx7wLj0w77cEY2AVt4PKxYIW3VDVufgWBRL8Tt(aMeeNk0w7oj4wBT3L9Bg2VTw)QHTVUq12A3HQP9QEKs9iT6XEgerrTWKH2A3EFeyUdatHO7CwhJRFtXfTT7u5yXwtm(h49E(t(bxCHp0eewdXVFnsfbLQSfKBt8QSExMhD2mJr4oeEtOCevIOEekI4qvbL(7wtbUg6OdiZ0q2M3eeiAUTvmcNOSi0ZVfejICuascg9DKvqUzWnjSHqCiM6noKeSr45gYB)t4gcJrveuaoc9HVCxsiNGTD8gvCaHJsyAfwmGdDRVinTwQpgHsrdm4gYp1GmNajPKRa6HVXHOvglxDG)c07(yKFR(ieebURBmUvslRogvmZBheI4nehUDmiHkLGW9fdq2jquvv1ZpAR8X2VLHNiiBD7RDDtFqAN0bl2fHU3yA6Ua4TIP7Vd5lcQqCsxMxj6igg(2M3fHFiimM0fHV3as3Eq3tsGAe6IaCI2BXwNX6kxQMt(cUlzqOyKhe5oERqOI8ePx6l)i)))
```

**Comment by InfusOnWoW** [comment]
I suspect you have lua errors from some of your auras. Try installing bugsack + buggrabber.

**Comment by Nokramx** [comment]
i have bugsack and buggrabber installed. i don't get any lua errors when this is happening.

i could try to make a short video clip where you see the states of the wa's after logging in and after a /reload if this is helping.

**Comment by InfusOnWoW** [comment]
Yes please do

**Comment by Nokramx** [comment]
i have some trouble today to trigger the bug while recording, i will update this ticket as soon as i can.

**Comment by Nokramx** [comment]
here is the issue displayed in a video clip:

https://streamable.com/cr725d

**Comment by InfusOnWoW** [comment]
I now tried to reproduce it for a good 20 relogs and even game restarts and it didn't happen once for me.

So I need more information on how to reliable reproduce the issue. Without being able to reproduce at all, it's impossible to investigate and fix.

**Comment by Nokramx** [comment]
yes this is a pain to troubleshoot. I don't know if it's a coincidence but it appears to me that it's way more likely to happen when i do a long playing session on a character and then log on another one.
(i logged in on one character repeatedly to force the bug for the video but i couldn't reproduce it myself then)

i log in between a lot of different characters at the moment to do the prepatch content, and i would say this issue happens once per day on average.

i think that's all the additional information i can give since i have no idea what could be causing it. It's too random. And it's too rare i have to admit.

**Comment by Nokramx** [comment]
I am quite confident now that the addon Bagsync was causing that issue.

i had some unrelated issue with another addon and i've read that scanning addons like Bagsync, TSM, Altoholic etc. could be the culprit, since multiple addons are accessing the Item API at the same time on login. 

i thought it's probably not a coincidence that i had the weakauras issue from this ticket just with Item/Slot CD wa's.
I disabled Bagsync 5 days ago and didn't had the issue from this ticket since then, when it was happening at least once per day before.

So it looks like Item CD wa's can potentially break on login when "scanning" addons interact too much with the Item API on login.

And sorry for ticking "tested with only weakauras enabled". I'll be more carefull next time when it's not obvious i'm dealing with a WeakAuras Bug.
