### ISSUE TITLE
Druid Trash

### ISSUE THREAD

**Issue by Thalbadar** [WeakAuras/WeakAuras2#5284]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Premade Druid Aura Trash (77758) not showing any Cooldowns. 
Aura is loading, but not possible to trigger cd in any way.

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Guardian Druid - Premade Aura - Trash

### Last Good Version

don´t know

**Comment by Thalbadar** [comment]
Was just testing some more Stuff. When checking "Exact spell match" the aura will work. 
Don´t know, if this is working as it should. Never needed to change anything this with premade auras.

**Comment by InfusOnWoW** [comment]
There are actually things here:
* We haven't updated the templates for TWW yet, because that's a lot of work and we did kinda forget to do it.
* The API for spell cooldowns changed in behaviour, which made it worse for certain spells like Thrash. We have changed how we use that API for the next release and Thrash should work even without Excact SPell ID with that. So I believe the bug is actually already fixed.

**Comment by Nesnidalka** [comment]
> There are actually things here:
> 
> * We haven't updated the templates for TWW yet, because that's a lot of work and we did kinda forget to do it.
> * The API for spell cooldowns changed in behaviour, which made it worse for certain spells like Thrash. We have changed how we use that API for the next release and Thrash should work even without Excact SPell ID with that. So I believe the bug is actually already fixed.

I tried a lot of ways including " exact spell match " button , unfortunately that doesn't work either. But as you write within two weeks it should be fine. Thanks for this message that you are working on it.

**Comment by Thalbadar** [comment]
Try this one as a workaround, works for me.

`!WA:2!1v13UTrrx84AfvKVa16wIsGkuicIirKqtPj8jK6fEdoQTknXS2HuUA3z3D8Ut76zgnZSo29oClLCT5cUglUeK(KFecVatT4jipc5jGZm760KcXxmEMZCo)MZF)TL2PANQrvJoE1rKqgTjlteIVZmJrrpltQWrpHqVMO)(TBlXQsJr0WeMObJqvbBxFVw1DNeYyPrSJOnpIWX(Nm9y9OyCIJbs)bkbjoglKV)YIIThFBxLaf(ChuMIXVzMe7fJPybjSzc7O9P(tU0Xrs4VAPhH6lDYOevapf1hlgfHdYA3UvFow8W672yNd2LFJWeKigl9yGqKIjw6bpyIbFbUdIqj04KtLzb4UyQQjymP3yVTR1SLxZw1CBDQrtjhNMUnlJQsCua2UwbUwt4lSDraUydblwGLYf)8MM7xHFlJX4EOqvoe7H6G9DPWQSYKZb2kDGD7JIKvgBUOWNFRN1qGbpZTzJ67URO42QBm0ORnV5p8CSMV0V1yi4R5j2k8BcVpPlUv(5NWIW)XmNb1lSGIs)EOkqy0F9SNJX8AagHkxKIW8hIOKoMD0TCLkKqTJEbhkJIpbJK4MkbMgRsU(KOmHvlptIriXq9nsoWOJPkOxZXKKbB1RPx)66VuFx9g61cAdjEzY7kgkFsKYaiozee5U4yaz5QZPxycCmaIZybugIo(J4FSc3t5zxAZeGN6X9uKo4ItL4l8VuqwSrV2WZVBPpJZx8QGQdlYZ4m(NAVuItBB70DQDqR953Yk00VAYtHhsIG2JAWXZYHI0dhzf(JtYNs(HIHMtS3BMMiT7RNDKGPGhPfi0zV93Ro)g5Vwcc6Q2MLYepUuPsLla5PfGOxqaPeJM8Qxq)IRNDKvwO16YWVHfHhvDYAlwVh30Nctp)hzjEXgxtki6sGpna4FYvLXaCdjMgQYtS3EeteDOaXhCyXM8yVlOtqk2ViuVajIE2jN7P2X49pO1UpcskvVGMt9J3QAtYlWRWx5QCRO(Wqhj0tLaXDcmUol)tVkDtXXOW(ETtzmHFqcMeNO(oNugk61JSJBOuyEmHFdZHibkMrfKilnsykskbFmYmyhUCGeKMIFJBNSufzU34hKB7CAV5MV0V8t(UwdGJvCmgy2WRAh)Veq(osi8S3AE0AfeXavmQxsG0sqhq6WzcL7rMgoV3vpcnzKWomzhkFVHN3kRNDWuc6eHHOaM32s)fvCGbuvf9xv5uEbRw(hcw9oZCnGrXwg2raSnnqct6q0ROMCVms04VU7ZqYooB5S5943Ek(Mg8VLirqHpkXgNtzobojxZy2iflSBoH08L(Z))sKOtp8V(9WeGQAXhIYWuxukpbvECBZldCqifQ8zxWzmrxqZTDRxFVjWGjiEFUnKQea8sTjXveeQ5fW(V97zOExZ5fmwNgLV763BKH)IyT5Bw2nmbh(8TC7IsZWLh0fjigVN)beQ08LIqce6U48kGuxPSHzMcmZF4Y6x(ydEBAxkxEaKfHMzvFx7i5Y6bBPFzz9RgXOttcG56xBm0x)Z67NRrj9Roj)ddqOdaFUowW)FMLnSlLbBoEmHM3kdE)CJHTH46MVDi91hBjbQkd2C9n2C97xT7F)0)j`
