### ISSUE TITLE
Auras won't update

### ISSUE THREAD

**Issue by gmanavarro** [WeakAuras/WeakAuras2#5287]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have installed the Weakauras Companion App and got some updates of some auras. When I try to update them in-game, it does the download/update/installation with the progressbar (same as always) but when it finishes, the update is still showing in the "Ready for Update" section. Reloading the ui is not helping neither. This is happening with all the auras that I got to update

Expected behaviour:
When I update an aura, when it finishes loading, it is successfully updated and does not show pending anymore.

Actual behaviour:
When updating an aura, it does not update and keeps showing as a pending update.

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I have a Bisector Report

### Reproduction Steps

1. Fetch updates with Weakauras Companion
2. Try to update an aura in-game

### Bisector Report

```Text
Bisect results:

report version: 2
addon version: v1.3.0
mode at print: done
bisect origin: cli
last test result: bad
Bisect took 1 out of (6-66) steps
Hints taken: 1
Addons ruled out: 31
Addons proved: 0

Narrowest set of addons that reproduces the issue:
|-- H:WeakAuras @ 5.15.4
|  |-- D:WeakAuras Archive @ 5.15.4
|  |-- d:WeakAuras Model Paths @ 5.15.4
|  |-- d:WeakAuras Options @ 5.15.4
|  |  |--WeakAuras Model Paths...(see above)
|  |  |-- d:WeakAuras Templates @ 5.15.4
|  |--WeakAuras Templates...(see above)
|-- E:WeakAuras Companion @ 5.2.3
|-- A:Bisector @ 1.1.2

Libraries:
LibCompress @ 90083
LibDataBroker-1.1 @ 4
SpellRange-1.0 @ 21
AceGUISharedMediaWidgets-1.0 @ 9004
AceGUI-3.0 @ 41
LibUIDropDownMenu-4.0 @ 90135
AceConfigRegistry-3.0 @ 21
LibAPIAutoComplete-1.0 @ 3
AceGUI-3.0-DropDown-ItemBase @ 2000
LibCustomGlow-1.0 @ 19
LibDeflate @ 1
AceConfigDialog-3.0 @ 87
LibSerialize @ 1
LibSharedMedia-3.0 @ 8020003
AceSerializer-3.0 @ 5
LibRangeCheck-3.0 @ 21
LibGetFrame-1.0 @ 60
LibSpecialization @ 10
CallbackHandler-1.0 @ 8
AceComm-3.0 @ 14
AceTimer-3.0 @ 17
AceConfig-3.0 @ 3
LibDBIcon-1.0 @ 54
AceConfigCmd-3.0 @ 14
```

**Comment by InfusOnWoW** [comment]
You should check this information from our discord: https://discord.com/channels/172440238717665280/532314347477925891/959031908283604992
