### ISSUE TITLE
Hero Talent selector shows wrong trees

### ISSUE THREAD

**Issue by silverwind** [WeakAuras/WeakAuras2#5289]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When selecting Arcane Mage in the Load conditions, which has hero talent trees Spellslinger and Sunfury, WeakAura shows incorrect trees Frostfire and Sunfury, which would actually be correct for a Fire Mage.

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Beta (WoW 11.0)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create a WeakAura
2. Open the "Load" tab
3. Select Class and Talents: Mage, Arcane
4. Select Hero talents

### Screenshots

![](https://github.com/user-attachments/assets/4872774c-2b57-4ab2-b6ee-225ee2e2bfaf)

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release.
