### ISSUE TITLE
UID for Totem

### ISSUE THREAD

**Issue by Niotras** [WeakAuras/WeakAuras2#529]
It would be realy nice for Mist Weaver Monks if it could be possible to make a Trigger for a cast and to select as a specific Unit a totem uid (like 'totem1').

We could check how long the 'Jade Serpent Statue' is channeling its cast.

**Comment by asakawa-k** [comment]
<https://wow.gamepedia.com/UnitId>

**Comment by Niotras** [comment]
Well I see this wont be possible with the UID but maybe another way?

**Comment by InfusOnWoW** [comment]
No, there's no way to get that information, except from the combat log. But that requires hardcoding the duration, which we won't do. You can find plenty of auras on wago that implement this as well as it can be done.
