### ISSUE TITLE
Add texture conditions for Stop Motion region.

### ISSUE THREAD

**Issue by Silvereyes1372** [WeakAuras/WeakAuras2#5290]
**Is your feature request related to a problem? Please describe.**
Hi, I'd like to have a custom stop-motion aura for each class, but currently, I have to create one for each class separately.

**Describe the solution you'd like**
Add texture conditions for the Stop Motion region, similar to how texture conditions work for the other region.. like this pull request: [(https://github.com/WeakAuras/WeakAuras2/pull/5096)] , if it's not too hard.

**Describe alternatives you've considered**
Creating an individual aura for each class.

**Additional context**
Ideally, you could choose the number of lines, frame count, etc., but I could manage with just the texture path option.

thank , cheers !

**Comment by InfusOnWoW** [comment]
Creating one per class sounds perfectly fine to me, especially since you did point out what the problems with a texture changing condition are.
