### ISSUE TITLE
StatusTexture:Hide(); doesn't work on initilisation until I tick and untick Custom checkbox

### ISSUE THREAD

**Issue by Celeriestix** [WeakAuras/WeakAuras2#5294]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello, I'm creating a WA that will hide a certain UI element around the healthbar. I expect this to hide the element, however, upon relogging or reloading the WA stops working. It doesnt not work if I open and close /wa. It only works if i go back to the actions tab and tick/untick the custom check box.

Video here: https://streamable.com/nf6r50

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create premade text WA.
2. Remove display text.
3. Go to actions, tick custom.
4. In the custom code, type: PlayerFrame.PlayerFrameContent.PlayerFrameContentMain.StatusTexture:Hide();
5. Hit accept and close WA. This works.
6. reload or relog.
7. it doesn't work. open /wa, go to the wa, go to actions, untick and retick custom.
8. close wa
9. it works.

### Screenshots

https://streamable.com/nf6r50

### Export String

```Text
!WA:2!1r5ZUnTsuy8gYIkzHqqqQQ8NfvCLkLlOkrfTibRQJCu79M0eSDP9UYDSNJJhWEMrZmUTPlJqiw3nSpRVxjuEe4jWQINaEe4j4EM4iec1Kn5Cg)55mNFFNXn60QOfTf9tpwjkn5moO6Fyy39pWZprKlu)vt8N8PuMwMtgfcNBIsfQcIjsgzyfqeDeNuWsImzkqNjYPJUsNrOIZ(N(PPAW8WLMs4jzc1abJBIB7DqONVCTfVH1znK3oPuBefwfhkPed4dNcCZ3jL4Qedl5ig1K5UlMQijgMGR3XxBikJJlJZmRFjvevVhNex)V8VhG1euDuKcyZFjUTGBW9(AwQhHX3mWqmLA7jPubVApgf24jVoofRIoZzSrXgoeu6BTUAE4hNqH4Y00WrsqTNx3bDoSRRbt8jLkYwJ1sipFFQ2576Y4zDvaQMD(0O27gegfeURFOBj2dXYzhOFkBGcqz(bd862TYjEpGKBY8rda0oxwYNxEh5DSa5uiSoVNGc)7sYhTyMxiOrkeXN8d0JafNK)wSHqK(5ljCML2c(ov3Qt1QUCbh(kq0qGrb8HMSLVIInLvrKTfvAirWP6XwnwauTHBbcr8DR2O6jlx9NvpT6zy4D)9vCtrKlVDhf7I1EtjHIBkzTWWjyZ7ddT(79xPA1RW0ysY7hIZRCQBUGq74QzxaR4xuMByoUiDtwP6fo(j5eT2gfBi5i9SHJTfjaLFV5JPhxpM2CIAwnSNyxdsi151pOHC9fZTCyijzuuAUqOYK)XIfkvqcZc0MYhCTQQd8TIPtqpgOZgV)WnN(lYVH6D4CmlDKBxVoHtmIKtRTPvB8FF5rm6whaNn(mHIEKIihF08GPP25z0UqE28h1xgNnIB714G2(EEhSvjJoDVE9E5(qX5YKEXOhMYg6OgnNcxHx7W3RVC2fnNP1WR9Spr0OrJMtSMoB(dz862bZCUud5P139D7hg2VxlD82B(8T38fTo9Bh)))
```

**Comment by InfusOnWoW** [comment]
That's an issue with your custom code, not with anything in WA. If you need help with custom code, the discord is the right place to ask.
