### ISSUE TITLE
Weapon Enchant triggers' "enchanted" condition check always returns true for Shaman Enchants when filtering by ID

### ISSUE THREAD

**Issue by Guffin7** [WeakAuras/WeakAuras2#5297]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When using the "enchanted" check in the conditions tab for a Item -> Weapon Enchant trigger to check Shaman Enchants that were filtered by ID, it always returns true for _any_ Shaman Enchant.
If you set the _name_ instead of the ID in the trigger tab, it works correctly.

### WeakAuras Version

WeakAuras 5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Make an Item -> Weapon Enchant Trigger on your Resto Shaman
2. Tick Weapon Enchant, enter the ID 6655 (Earthliving Weapon) and enchant your Weapon
3. In Conditions, make an "enchanted" check
4. Notice how it's true.
5. Swap to some other spec, change enchant and see how the "earthliving enchanted" check is still true

### Export String

```Text
!WA:2!Lwv3YTrsv4Omew25kBNetswVbHbCItXACCI9Ujl)5XwYXbfBZiL4afGupZ0sDhpAMjDpJKLzHI4IAldlCJVj3sPRHQO0JGFcoLkEc8f5bipbCoZmkj2j7cvT3mt)Z5VUpFFFDHhnH2zX5U5IZD7jApH3eEhC1Hom3D8uHrRe6hQUVHHXwgZp3I9JdD7WvAzyWLk8V(3h7eQ84kRCBJgZYxU3EmLxXAHH(XYOHSKyrOAZOy0dTPtM9cvVnB2uZJl0xXBH7uRxe3ULkmjQFMfvL7Xp3rzJZm99hKnlREkuOGHT2L5ZnY9OKxlE04vFActXlwoX3V42czmxXCtt9s26yMk20PPmqQfMw4VyZ9JvYwTWZZvMrLp8Z77XDsA2Kkj19kvzRYpSIvmvFSefBH91rCF)190MhRtC4D4bXvrRL7oO(klxTw9Q1w2UMvcgCNiFwpUYoG1MRnTtn15ECMFS4vUULIJUAxDRsvQCysqEjyoGf4I3ABfkrxwP0g1kz)sCixfW8Fu2T)ZhidAgQAZOtN5HAUFZuZHRnT0l6kTA2mOOwWAZckYXGXcIlk16eUwTB(vVnZpsWmEzwUkRWYKoZovxXUuPnCCddAkBzUqI0BqS1IBSqL5Vz51ydAsgwnwXIzg9XZHDAduBEilqMvnlbtu(iottwXdAflEp4YwbHb8HE4nizrD6(uP5yo807tMszg(yR2mzqzyj0b4JHpbUdCx8)5p9k9j)Kzikl)qMxzNyejeepPD7ee1zAHnj3jHFMPTRptRPrwAerrdYHrRhG3bgt4EJdMTVeJx1WeLlFQZmG59KeDm37bSDp7RNidol8TkaZaxBOlIS9c7guTRmI34Ortj8NWIcvd4IbZatEW4Q8BERLU9D(KOXt086T4bCL0TQiS7MbngEIPhRt)TsEaHVh897t(0LZIOO(THlHxKiMUnmf8HPBL5rJJOX0gBG9MgW394TtDPyPS8dFGjCv474KzDF63Y(Dz90qrZbKR51zdNSubFk8dmtpbW9Tw82ZppuPb8aydkiWM5fcSfvfWVSbyJzeQsj5rnGAWdPchJmS9PJZn)6eNbEs9tscq2Ch(cSGErJZshxlJZ8Gqp()8mW1F(l3HZJwMaaX2eyta3aUgYP1Syc9XfWTV7KWLhIqxsIJeDc8AomdvupmJBax(qA)01YvHQ7(kHNCvV6DKAPJpVroKQohHaWyJMraoJxmSLFy3Yk(ttWl5EB9nMFUfweUScJoTXr0NvZzfg7tZiMWqNK44WGnrLwudPpTCLuM0fhqJ)v5m4dPjVsF2GqbRnAfrQLpo3Y0QOMq6UtaxRnsDSAQ6PfnuKUqfjU54PzZktM2rWLTeXpd(jLHFkrEGFE63Lt)ArFJgdZ6Y50KuwJaULXPxvgiG3hw)4ivylfwbzSTBm1zolmRj8JV7m2UcU7olbtASFhMsYWR1dZrLCp7om)eUHIM2IJA1WNnPJlg7W2rxnsHQExF61xTytQtE3ILqzEHVSJmO10ZUpMruQjUx)m7DryYmqpmrNd2d(9WNza)H04b)X3rOk7J8jSr0kHp9SWFcEwMRgVLRFWB562sevLO6L5x0fgjtuJVB8QsnDa9eWnh4v5xeSAvTLy2a4JmS2lmSn9q7TG5GFeyqVXs65NFJW4IDdv7GhQIDLXIIRVkSij0EAXYp9)T8z0eyZzKkdYBqAcVHDxPxS4zWpSamVjEyOh5rUY4yomHZBcxa1sFfsJ4I0RBRJQDxY4FyU)OtNa(MMhmlS6uNHcuPZcLhjBcR1aU3O4DH0qEX5Y1gg8gTSrseiV)RsHGKgijcuPGetoHuZG3OTnkCK9FvXJccfVIPIpNiC7pQv(1jwWVjvCc(TI82g1pW2YB02o1kN)Tw53LlDb1BcCdOrbWjvocCBaEWy4gSxanhjXaTaSDiHNa7CrWVa0oTZbcdiSaOeWtnGidqpoelGKugU1BXWZ48DeWF5zq3ugmjMc)Db83O2o2SHVilSZBcFEgU9plEnS9kBNdzZyH(9YWU0RuWbnqDIuu(hzG8G1U19x7rBFN2xN9RH)QawVbPk8LW2kMZ2O48oz9VMQEU)VC(lHN)EWEw0JLNW)p8D4)jj7KK2UK22eD(pp()o
```

**Comment by InfusOnWoW** [comment]
This should be fixed for the next release. Note that the id you listed didn't match the enchantID that is actually used. There's a new text replacement %enchantID which displays the acutal id of the enchant, and a new condition to check for specific enchantIDs.

**Comment by Guffin7** [comment]
Nice. And ye it was late, idk where the wrong ID came from.
The example aura provided should've had the correct ones though.

**Comment by Guffin7** [comment]
> This should be fixed for the next release. 
Nice, thanks.

> Note that the id you listed didn't match the enchantID that is actually used. 
Ye it was late, slipped up. The example aura provided should've had the correct ones though.
