### ISSUE TITLE
Update Suggestion Skyriding

### ISSUE THREAD

**Issue by january19th** [WeakAuras/WeakAuras2#5298]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

![image](https://github.com/user-attachments/assets/87d29e8c-1842-4998-8022-4e904b9f36a7)

Dear Weakauras Devs,

Is it possible to update this feature " Skyriding " instead of Dragonriding? Some auras doesn't work after Pre Beta War Within update.

### WeakAuras Version

WeakAuras 5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

add Skyriding feature to load section in Weakauras Menu.

**Comment by InfusOnWoW** [comment]
This was handled on the discord, next time please do take the effort to answer relevant questions and include the aura that you are having problems with.
