### ISSUE TITLE
WA anchoring to party frames not working when "Use raid-style party frames" is disabled in Edit Mode.

### ISSUE THREAD

**Issue by nvnto** [WeakAuras/WeakAuras2#5300]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

There seems to be some kind of problem with WeakAuras anchoring to party frames whenever the option `use raid-style party frames` is disabled in Blizzard's Edit Mode.

WeakAuras that use "Unitframe" anchors and track party related buffs (via Smart Group) do not show up on party frames at all. Not because they are hidden somewhere (wrong strata settings), but because they probably just don't find the elements to anchor to.

Not only do Unitframe anchors not anchor to party frames, but it's also impossible to use the manual frame selector to select any party frame element as an anchor when `use raid-style party frames` is disabled, while selecting all other frames like the player frame works just fine. I tested this with text and progress bar WAs. 

I never used Blizzard's party frames. So for me the `use raid-style party frames` option was disabled (as is default). But once you enable any other unitframe addon (in my case ElvUI), this behavior also applies to ElvUI party frames. And any unitframe addon hides Blizzard frames, which in turn makes that setting in Edit Mode unaccessible.

When I enable `use raid-style party frames` again, the WAs anchor as intended again. Both with the default UI and with ElvUI.

I tested this with another account and made a short video.

Video example: https://www.youtube.com/watch?v=CeXD5eNpJGE
WA example using Prescience (Augmentation): https://wago.io/eE8yz05BI

### WeakAuras Version

5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No errors.
```

### Reproduction Steps

- Create WA tracking a buff as %p text via Aura > Smart Group > Buff trigger and use Unitframes as the anchor.
- Disable "use raid-style party frames" in Edit Mode and `/reload`
- Create a party and buff anyone with the buff you are trying to track.
- The WA text is not showing. It is not hidden behind any frames, it simply won't anchor to anything for some reason.

Now enable "use raid-style party frames" in Edit Mode and `/reload`.

-WeakAuras are now anchoring to the proper unitframes as intended.

### Screenshots

WeakAuras.lua from new account I tested with:
[WeakAuras.zip](https://github.com/user-attachments/files/16561425/WeakAuras.zip)

### Export String

```Text
!WA:2!1nvqVTTnu4AKdfqyjlXDiylDh8Yq7Lc44e0uKTddWktc1BoXPYknDNuOePS4kfjbjvIDoASd9SVS7(8gWG)jKFbcg7xq(jKFb7rjJUIHfDrV3JKVVh)((yJ32mVjUPo(W27Fy7x2e)HxOMminvtmnuIcdJYjQbNh2V3PEQRiknvWxBbLNku5idK4iBHPAjdnjKm2evxpsgzO5KvznKp)H3cJmcLmjkLjeQS5kYiONHtKexdS3zioTgMx5MJOCFxJDjUGtwIluvRezlP0KebhRNsqAI94LBCRnCOrr4JmzpoqBqkJF56LBu(5LBwUf8V5JJtPCQo7)wEMMWsptq5My3bHHdo5Gcft(0mJrQ)(927A0irBQypI3rtUPZHU92BF14vCwSMKd0uW(T70UZsuHjtOgiTZP2rHsQcELlGQXP8joLFHtmm3P0roYV9H5iPIKqRy(yl29(XzFe6GebtO(P1Gp5MjfAJi32GZLyKHeqUIWn3d3dIIJyVTw((9Pxlu4lui50lwfCqbfVaFOKW87E0p)(lwG4jWGxtbh7DAOxG6xHMttN423ZpCHodHfxFCf2nA0yn3ub3i30xrVP1BkqyqAqTcdNBejRmnFzJ)8VMRlIdQuy9oBxU(singL8(rGrJJxKQq5wbdo6Al(eYq9mzRqVHHlRb9xQz6V(rZTkoTMALp9)L9QdcSKi(oqmewZuYfuSjZTlKkFXdt64jCuonjYKPi6mbd3qU7dV7CbocMCYLUmbc7hBqmG63oiVGzOobjmKwVDPRJRMEdPoqssSbZtPJj4Qz63(SPgfD0iGX245Zk4RsCuRc(WwZXK4I0uRdx9AV(N5FE)BrWdbOzmgfR3j(L73PZrFxam7eTZ9fAI3yW2n0UEp8LZHBY1hZG3p6lxcJFsgrpeknGFRU6xxWIckgCUtHoK5wao1aRajxuT9OeqRmn7mZIAni3bYyLrBimz0XlIoU7WWOHHDdcNQRXv7u(S4xtqmtw56b2JEWDaeN8VD8Yp2LZueOlbdpZRFF5t(eqha3zKrOA(dYTqvJzynTCIat(JhTYE8UA7XA7co6UvU4wHeT5(AhTV1JzzVzNFAVq)GUN4n1ADhcQYx18Q)(DLFt5U)d
```

**Comment by mrbuds** [comment]
Thanks for the report, this will be fixed with next WeakAuras release by an update on LibGetFrame-1.0 https://github.com/mrbuds/LibGetFrame/commit/c8651587533563be027bff4d11e4bcfd041956b9
