### ISSUE TITLE
Add the font Expressway - heavily used

### ISSUE THREAD

**Issue by khelge** [WeakAuras/WeakAuras2#5301]
**Is your feature request related to a problem? Please describe.**
It's always frustrating to download a new weakaura pack and the author 50% of the time is using the Expressway font because it is apart of Elvui and noone else has it, resulting in ugly-missfitting fallback fonts being used, which doesn't fit the intended displayarea of the WA

**Describe the solution you'd like**
All of this would be avoided if you guys could include the same font as Elvui uses, Expressway with the weakaura addon.

**Describe alternatives you've considered**
Personally I've manually copy-pasted the font from Elvui install folder into the fonts of WA, but most people will most likely just remove the weakauras they downloaded to try because they dont look like on the pictures. Would be perfect if you guys could just include it seeing as it's so heavily used

**Comment by InfusOnWoW** [comment]
Express way doesn't have a license that allows for adding it to the WA addon.
