### ISSUE TITLE
What is this green/red button on minimap ??

### ISSUE THREAD

**Issue by Nem597** [WeakAuras/WeakAuras2#5307]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello,

I have a green button on minimap, i can click on it and it goes red, click again it goes green, but no tooltip, no right click or anything.
I disabled all my addon 1 by 1 to see where does it comes from and i'ts from WeakAuras !
I don't know what is the purpose of this button, and i don't know how to disable it.
Found nothing in Google about it ...

Please help 

![Capture d'écran 2024-08-11 202016](https://github.com/user-attachments/assets/ac6a4cd8-7f64-498e-a442-9a8382a16c22)
![Capture d'écran 2024-08-11 202007](https://github.com/user-attachments/assets/6905a969-05d7-4b06-953d-30c8d87ad52a)

### WeakAuras Version

WeakAuras 5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

I disabled all Addons : no button
Then i enable ONLY WeakAuras : button appear

### Screenshots

![Capture d'écran 2024-08-11 202016](https://github.com/user-attachments/assets/62c40201-1618-465f-ae4f-0c912ccbec38)
![Capture d'écran 2024-08-11 202007](https://github.com/user-attachments/assets/8c363147-5a54-40b2-8bc4-7b9b1886853f)

**Comment by InfusOnWoW** [comment]
That minimap icon comes from a WA you have installed, not from the addon itself. I asked our resident expert in indetifying auras, and he said: "it's the cursed lfg auto accepter", which is named likely "[AutoQueue - Auto accept LFG Check]".

Removing that aura should remove the minimap button after a reload.

**Comment by Nem597** [comment]
> That minimap icon comes from a WA you have installed, not from the addon itself. I asked our resident expert in indetifying auras, and he said: "it's the cursed lfg auto accepter", which is named likely "[AutoQueue - Auto accept LFG Check]".
> 
> Removing that aura should remove the minimap button after a reload.

Hello sir,

Damn thank you very much for this fast and perfect response.
It works perfectly thank you !!!
