### ISSUE TITLE
Shaman - Hero Talent select on Load

### ISSUE THREAD

**Issue by CeaserH** [WeakAuras/WeakAuras2#5323]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

While on Elemental shaman and you select a new weakaura under Load, class and specialization check, hero talent checked, the first skill on the right side hero tree (stormbringer) is actually wrong. It is listed as Surging Totem when it is supposed to be Tempest.

### WeakAuras Version

WeakAuras 5.15.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
N/A
```

### Reproduction Steps

New Aura
Icon
Load
Class and Specialization - Shaman / Elemental
Hero Talent
Select Talent
First skill on the Stormbringer tree(right tree)

**Comment by InfusOnWoW** [comment]
That's what the game reports as the hero talents, it'll work once the game reports the correct data, which will be with the actual release of the expansion

**Comment by CeaserH** [comment]
Gotcha, thanks for the prompt reply! cheers
