### ISSUE TITLE
Group Finder Custom Extension WA

### ISSUE THREAD

**Issue by coalgiver** [WeakAuras/WeakAuras2#5324]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

24x Lua error in aura 'Group Finder Custom Extension': Trigger 4
WeakAuras Version: 5.15.4
Aura Version: 1.0.40
[string "return ------------------------------------..."]:3: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "return ----------------------------------------- Addon: WorldQuestsList Turn LFG Option ON -----------------------------------"]:3: in function <[string "return ------------------------------------..."]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:716: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:897: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:842: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1127: in function <WeakAuras/GenericTrigger.lua:1112>

Locals:
(*temporary) = nil
(*temporary) = "WorldQuestsList"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

### WeakAuras Version

WeakAuras 5.15.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
24x Lua error in aura 'Group Finder Custom Extension': Trigger 4
WeakAuras Version: 5.15.4
Aura Version: 1.0.40
[string "return ------------------------------------..."]:3: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "return ----------------------------------------- Addon: WorldQuestsList Turn LFG Option ON -----------------------------------"]:3: in function <[string "return ------------------------------------..."]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:716: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:897: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:842: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1127: in function <WeakAuras/GenericTrigger.lua:1112>

Locals:
(*temporary) = nil
(*temporary) = "WorldQuestsList"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
```

### Reproduction Steps

Downloaded WA from WA website and received error message.

### Last Good Version

WeakAuras Version 5.15.0

### Screenshots

24x Lua error in aura 'Group Finder Custom Extension': Trigger 4
WeakAuras Version: 5.15.4
Aura Version: 1.0.40
[string "return ------------------------------------..."]:3: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "return ----------------------------------------- Addon: WorldQuestsList Turn LFG Option ON -----------------------------------"]:3: in function <[string "return ------------------------------------..."]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:716: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:897: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:842: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1127: in function <WeakAuras/GenericTrigger.lua:1112>

Locals:
(*temporary) = nil
(*temporary) = "WorldQuestsList"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

### Export String

```Text
24x Lua error in aura 'Group Finder Custom Extension': Trigger 4
WeakAuras Version: 5.15.4
Aura Version: 1.0.40
[string "return ------------------------------------..."]:3: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "return ----------------------------------------- Addon: WorldQuestsList Turn LFG Option ON -----------------------------------"]:3: in function <[string "return ------------------------------------..."]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:716: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:897: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:842: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1127: in function <WeakAuras/GenericTrigger.lua:1112>

Locals:
(*temporary) = nil
(*temporary) = "WorldQuestsList"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
```

### Bisector Report

```Text
24x Lua error in aura 'Group Finder Custom Extension': Trigger 4
WeakAuras Version: 5.15.4
Aura Version: 1.0.40
[string "return ------------------------------------..."]:3: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "return ----------------------------------------- Addon: WorldQuestsList Turn LFG Option ON -----------------------------------"]:3: in function <[string "return ------------------------------------..."]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:716: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:897: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:842: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1127: in function <WeakAuras/GenericTrigger.lua:1112>

Locals:
(*temporary) = nil
(*temporary) = "WorldQuestsList"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
```

**Comment by emptyrivers** [comment]
We don't provide support for custom code auras here. Contact the author, or ask in our discord for help.
