### ISSUE TITLE
WA throwing throwing continous errors and not loading at all

### ISSUE THREAD

**Issue by skjetne** [WeakAuras/WeakAuras2#5328]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Today after the update WA's are not loading at all, and is trowing errors like crazy, generated around 4000 lua errors while i wrote this bug report.
/wa does not work either.

### WeakAuras Version

5.16.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
4358x WeakAuras/Prototypes.lua:1099: Usage: IsPlayerSpell(spellID)
[string "=[C]"]: in function `IsPlayerSpell'
[string "@WeakAuras/Prototypes.lua"]:1099: in function `IsSpellKnown'
[string "@WeakAuras/Prototypes.lua"]:1111: in function `IsSpellKnownIncludingPet'
[string "@WeakAuras/GenericTrigger.lua"]:2525: in function `CheckSpellKnown'
[string "@WeakAuras/GenericTrigger.lua"]:2783: in function <WeakAuras/GenericTrigger.lua:2739>

Locals:
(*temporary) = 0
```

### Reproduction Steps

1. Have any weakaura pack
2. Log in with latest version of wow and WA
3. Open bugsack

### Last Good Version

5.15?

**Comment by mrbuds** [comment]
Reproduction steps are not good enough, we need your weakauras savedvariable file
