### ISSUE TITLE
Keep aspect ratio and shrink preset animation causing loop of errors

### ISSUE THREAD

**Issue by Skildar** [WeakAuras/WeakAuras2#533]
**Describe the bug**
On load or after using /reload, I was getting harassed by the error panel (see stacktrace further down).
I spotted the renegade, one of my weakaura is an icon using the "Keep aspect ratio" feature. But combined with a preset animation "shrink" it broke.

**Do you have an error log of what happened?**
```
Message: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:484: TexCoord out of range
Time: Wed Jul 25 11:41:45 2018
Count: 7616
Stack: Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:484: TexCoord out of range
[C]: in function `SetTexCoord'
Interface\AddOns\WeakAuras\RegionTypes\Icon.lua:484: in function `Scale'
Interface\AddOns\WeakAuras\WeakAuras.lua:2902: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:2824>
```

**To Reproduce**
1. Create a icon weakaura (I based mine on Status/Totem/"Feral spirit")
2. Change graphical height parameter to make it a rectangle
3. Check "Keep aspect ratio" box
4. Go to animation and choose in the Finish part "Preset --> Shrink" (I have the addon in french so my translation might different from what word you used in the english version)
5. See error

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, but didn't change a thing

**Which version of WeakAuras are you using?**
Latest release at the time (2.6.3)

**Was it working in a previous version? If yes, which was the last good one?**
Yes I remember it working perfectly a week ago, don't which version though. I keep my wa updated and check for new versions once a day.

`dKKAoaakuHtbv1Que6vqfAwcv3srYUub9lur0Wufhdkltv6ze00ekUMkvBdvIVruQXPGQ3HkcDpfuAFOIshufXcjQEOcYerfvxKOyJqv(iubJurWjHkALQqntIsCtfPANi9tfrdvbfhLOKwQqPNsAQe5QOIuBvrkFfvKmwviNvfyUOII9s9xfyWOCyqlMapwvnzHCzP2SkQpROgTc50sA1OIGxRqnBb3wLSBj(nWWrvlxPNdz6IUoH2oQK(oQuJhQ05vPSEvK2pInMLSEznYAKLSI4H7yovnkhzQWhRFaieb4Ui14MYuGccDKfyfLW)yeEb4mYkfuAR3M88zuNMofwm3TI4H74ybjmRGIPpwxqcZwQXnTklYGNK16huSaR1pOm4dcG1sMIzkMPVMIzQqtXmngtXCADC38NG47FglmRal3Qa4oeiawlzkMPyM(A6JPcn9X0ymfZP1fKWSckM(ynBCtSHbulP1HKHkjtSwr8WD8KNpJ68atFSgaWilzTwMxGiVLSEjgYQLC60QiQhuAU2Rfy9hGiKLSIQL5qBvNWjt)eQtRIOEWparil36c)TLSEjgYQLC60QiQhG47VLBnHHUKVwY6LyiRwYPtRjm0L0swr1YCOnf716LyiRwYuSxl3PtRi((BjROAzo0M(60QiQhCkO04mYcSgvpFU(fd5nlz9smKvl50PvrupyBy4YcSkI6bNckTfy9m8NvqXswVedz1soDAve1dq8DimUa4Uybwfr9Gc8QTaR8CLpHHUKwY6LyiRwYPtRli0wY6LyiRwYPtNwZ6vVdbcG1sMIzkMPVMIzQqtXmngtXCAD75kOiDJVTw)GIvuc)JrwGvbHUenDquBvUSidLZTwl1CWhCXh6SJmfZA24MIBB9K9cS3SMnUjEGsAfVTEkHjRIWOfMqctsYQaWg17KNpJ6007wr8WDSLBnRx9IhOKwXBRNsyYQimAHjKWKKScd8JGMIzvayJ6fNfuNMIHznQI4dWB48dkM(ku23LTSTIs4FmcpqjTI3wpLWKvry0ctiHjjzvaCXzbVfusl3ATuZbOeUzhzkMvbGnQx5W)4OfWBvEOE6PWnIWKaGqw5TweVK268CVitXScftGfyvSKBDEUxlzfncW9KfROraUNSmeaeIaCxSI47qGcVAtVJDxOqNwfa)JNxGyjAiqaSwYumtFm910htfA6JPXy6ZH3DAf(ZkxBPTop370brTPtH9yfgfvZkOaddYTop3lYsoTgvr8b4nPg3uw6ZPvcZA24MA902uSxRrveFaEtQXnJTopkTsywRLS3cmmTErvqX07wHL6fmRGILSIs4MwY6heaBSMIznsCHzfuS(A9dcGvUPyw)GayXbtXSI(WqlDJVTIYfwNhL6hgAROpm04jw(wplw(zfu4GFbZBJqXjmuc38O4egkHBEqCcd9HH(O4eg6dd9b4toMWimcJWimcB7uClegkHBEeHHJegh8lyEBeIWMiHXb6dd9re2uegkHBEe(4hNWqjCZdimCKW4GFbZBJqe2ejmoqFyOpGWMIWqjCZdWhFYXegHryewxIihtyeMv(TrDADEbCBfg4hbn9X6ntFSIRPpwrFyOX10xRFqaSNykM1fKWSn9XQiQhG(WqB5wrFyOVz6RtRxWAXsw)GayJ14XfH3h(ZRWNhHcJHl3hUS95PUl0k6ddnUMIz9dcGvUXJlcVp8NxHppcfgdxUpCz7ZtDxO1piawCW4XfH3h(ZRWNhHcJHl3hUS95PUl0AEJVT(frj4YAK4cZkOy95qzBve1d(GayTCRWa)iOPpwrFyOVzkM1BM(yfxtFS(bbWEIPyw)GayXtS8TsyegHryNfl)SckCWVG5TrO4e2IfNWMXItycWItyqS4e2(gNWMFJtycEJtyWx8jhtyegHryegHfaFyGWGL5qtydlHXb)cM3gHiSjsyVe2ejSlyo6q(k(e2ueghxWC0H8vcJtsyV4toMWimcJWimcla(WaHvAUhMfmVncrydlHXbhxWC0HOAHdyzo04ty4iHHHpN8fForYXegHryegHryBNIBHW4unC8jIleDio05e0PjTWcQMvqHJsZ9WSG5TrO4e2IfNWMXItycWItyqS4e2(gNWMFJtycEJtyWx8jhtyegHryDjICmHrywxqcZ20hRFqaSs34BR8IbupbDAw53g1PvEXaQDA9CTurJSKv0hgA8elFRNfl)SckCWVG5TrO4egkHBEuCcdLWnpioHH(WqFuCcd9HH(a8jhtyegHryegHTDkUfcdLWnpIWWrcJd(fmVncrytKW4a9HH(icBkcdLWnpcF8JtyOeU5begosyCWVG5TricBIeghOpm0hqytryOeU5b4Jp5ycJWimcRlrKJjmcZAK4cZkOy916hea7jMIz9dcGfhmfZAEJVTYVnQtRFqaSYnfZk6dd9ntFTcd8JGM(yve1dqFyOTCR3m9XkUM(y9dcGnwtXSI(WqlDJVTIYfwNhL6hgAROpm04A6R1fKWSn9Xk)2OoTIgT1YyNoTMBDEUxlzD7lRVwbCxMSeUz5wfr9GeK9ffE1wU1TVG1sTmB95qmRf4vJSKPywLbXV1KWodxG4Fu706xeLGRbJQrT1SE1rw3(As(EHjyTYzTI47qGcVAtVJDxOqRIOEW2xWAPwMTCR5n(2kkHPiYQiQhiwQPLBve1dqJaCpzXYTkwAU2L0kumbwBU2L0Qei7lRji7lk8QTkdIFRjHfjsybGiV1THbLVdbk8QTkdIFRjHDgUaX)O2QiQhG47qGcVAl362xWAPwMha47fMG1kNDyTIgb4EYIv0ia3twgcacraUlwfrDS9LL70A24MwU1AKvUbbU2ObqRrv0F7ShSGeMvqX0hRiE4oEiqaSwYumtXm91umtfAkMPXykMtRiE4oEcDDEuAQWhRzJBIxaoJSsbL2AwV61YTUGeMTLBfXd3XYdDjA6GO26jCoNBva8poAb8dbcG1sMIzkMPVMIzQqtXmngtFo8UtRiE4owQXnf32kolzVNH)MZmeeL1YSC4Yz404CQHGOSwMLd3PuE4o2QaWg1RmrZTvkO0wVQ7cwlWkIhUJN88zuNhz6JvbGnQxTEABkgxSkaSr9AbwRFqzaQg1wJfN4WeKSM1REXlaNrwPGsBnBCtmReM1rDDEuA67Jvuc)JrA902uSxROe(hJgceaRLmfZumtFnfZuHMIzAmMI50AwV6vRN2MI9AfXd3XXcsywbLPdIARNWPLM0kIhUJNqnkQlwPYmnzI1QaWg17qGayTKPyMIz6RPyMk0umtJX0NdV70k31OCKP3FSMnUjMmfOGqhzbwJQiobXYpRCTTcl3SI4H7yoVrWuCBlWkyRDjHzfuSonzIvcNdDISmaN0PjtSQmw)aqicWDXYDAfz99qUCOqRC1uSyEXCAd`

**Comment by emptyrivers** [comment]
Should be fixed in the release following 2.6.4.
