### ISSUE TITLE
QOL change for comparing stacks count

### ISSUE THREAD

**Issue by Aishuu87** [WeakAuras/WeakAuras2#5331]
Hello ! I really don't know if it's something conceivable to ask for such a feature, sorry if it sounds dumb, but here I go : 

That would be a nice QOL change, as well as a way to reduce redundant triggers and such, to be able to get a returned boolean when you compare a stack count that is equal to zero.

It sounds more complexe than it actually is, let me do an example : 

Let's say I want a glowing animation to display on an icon if my Demonic Cores (warlock buff) are <= 2
That means : 
• Aura trigger[1] for the Demonic Cores buff
• One condition : If Trigger[1] Stacks <= 2 , then Glow ON

That should work like that, right ?
well, no, you HAVE to add "if Trigger[1] Stacks <= OR Trigger[1] Active == False, then Glow ON", otherwise it will only glow when at stacks 1 or 2, and not stacks = 0.

See where I'm going with it ?
So that's my request : could a "<=2" also imply ZERO has a result ?
That would be also cool for case like refreshing debuffs auras etc, such as "refresh Dot if <6 seconds remaining", it should also automatically imply that 0 second is also <6 seconds (so where the debuff is not present), and then a trigger with <X sec should return true when missing debuff.

Sorry if I'm not clear, and thanks for your time !

**Comment by InfusOnWoW** [comment]
No, that's not possible
