### ISSUE TITLE
WA error / WA not opening / LUA error

### ISSUE THREAD

**Issue by Rotunda8** [WeakAuras/WeakAuras2#5332]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues.

### Description

hi
-the addon weakauras is not opening (click to open and /wa do not work)
-bugsack/buggrabber/weakauras show me it is because of a part of my rogue-wa (feint) and has caused lua-error
-because of that all weakauras look incomplete in my interface or dont even work/trigger/..

english/german answers are okay :) my first report here, so i dont know if i did it right

### WeakAuras Version

WeakAuras 5.16.1

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
6x Lua error in aura 'Feint 3': Trigger 1
WeakAuras Version: 5.16.1
Aura Version: 1.0.14
Stack trace:
WeakAuras/GenericTrigger.lua:3415: Usage: FindSpellOverrideByID(spellID)
[string "=[C]"]: ?
[string "@WeakAuras/GenericTrigger.lua"]:3415: in function `GetEffectiveSpellId'
[string ""]:11: in function <[string ""]:2>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:702: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:897: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:842: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1127: in function <WeakAuras/GenericTrigger.lua:1112>
[string "@WeakAuras/GenericTrigger.lua"]:1132: in function `func'
[string "@Details/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <...ceDetails/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
(*temporary) = "Feint"
```

### Reproduction Steps

dont know what to do here, sorry

### Last Good Version

no last good one

### Screenshots

![grafik](https://github.com/user-attachments/assets/66cedc60-348c-4280-8bb2-3f87606b8587)
![grafik](https://github.com/user-attachments/assets/dde8cb07-6cd4-4577-a10b-7277dfa0ca93)

**Comment by Rotunda8** [comment]
![grafik](https://github.com/user-attachments/assets/e53b1e9a-76a3-4796-8e57-2efdfe13af9c)

**Comment by SpatenLa** [comment]
that is the fourth error. the first error and your saved variabels are important

**Comment by Rotunda8** [comment]
what are saved variables and how do i find and "import" them?

1st error:

1x WeakAuras/GenericTrigger.lua:3415: Usage: FindSpellOverrideByID(spellID)
[string "=[C]"]: ?
[string "@WeakAuras/GenericTrigger.lua"]:3415: in function `GetEffectiveSpellId'
[string "@WeakAuras/GenericTrigger.lua"]:2627: in function `WatchSpellCooldown'
[string "@WeakAuras/GenericTrigger.lua"]:3426: in function `WatchSpellCooldown'
[string "@WeakAuras/Prototypes.lua"]:5189: in function `loadFunc'
[string "@WeakAuras/GenericTrigger.lua"]:1356: in function <WeakAuras/GenericTrigger.lua:1306>
[string "@WeakAuras/GenericTrigger.lua"]:1409: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:2038: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1820: in function <WeakAuras/WeakAuras.lua:1664>
[string "@WeakAuras/WeakAuras.lua"]:2015: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1288: in function <WeakAuras/WeakAuras.lua:1247>

[string "@WeakAuras/WeakAuras.lua"]:1406: in function <WeakAuras/WeakAuras.lua:1354>

Locals:
self = Frame {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 editor_tab_spaces = 4
 login_squelch_time = 10
 mousePointerFrame = <table> {
 }
 minimap = <table> {
 }
 historyCutoff = 730
 dbVersion = 75
 editor_theme = "Monokai"
 dynamicIconCache = <table> {
 }
 editor_font_size = 12
 lastArchiveClear = 1635407839
 lastUpgrade = 1719181525
 personalRessourceDisplayFrame = <table> {
 }
 migrationCutoff = 730
 registered = <table> {
 }
 displays = <table> {
 }
 features = <table> {
 }
}
Private = <table> {
 HandleGlowAction = <function> defined @WeakAuras/WeakAuras.lua:3645
 frame_strata_types = <table> {
 }
 DisplayToString = <function> defined @WeakAuras/Transmission.lua:355
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 CheckItemSlotCooldowns = <function> defined @WeakAuras/GenericTrigger.lua:3295
 InitializeEncounterAndZoneLists = <function> defined @WeakAuras/Types_Cata.lua:13
 IsEnvironmentInitialized = <function> defined @WeakAuras/AuraEnvironment.lua:200
 form_types = <table> {
 }
 CleanArchive = <function> defined @WeakAuras/History.lua:25
 UpdateProgressFrom = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:580
 RunConditions = <function> defined @WeakAuras/Conditions.lua:840
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 get_zoneId_list = <function> defined @WeakAuras/Types_Cata.lua:75
 checkForSingleLoadCondition = <function> defined @WeakAuras/Prototypes.lua:1218
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 CancelDelayedTrigger = <function> defined @WeakAuras/GenericTrigger.lua:940
 centered_types_h = <table> {
 }
 ModernizeNeedsOldSnapshot = <function> defined @WeakAuras/Modernize.lua:2081
 ensurePRDFrame = <function> defined @WeakAuras/WeakAuras.lua:5457
 talent_types = <table> {
 }
 LoadFunction = <function> defined @WeakAuras/AuraEnvironment.lua:674
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 player_target_events = <table> {
 }
 FinishLoadUnload = <function> defined @WeakAuras/WeakAuras.lua:2084
 subRegionTypes = <table> {
 }
 UnregisterAllEveryFrameUpdate = <function> defined @WeakAuras/GenericTrigger.lua:1880
 array_entry_name_types = <table> {
 }
 eclipse_direction_types = <table> {
 }
 StringToTable = <function> defined @WeakAuras/Transmission.lua:299
 RegisterLoadEvents = <function> defined @WeakAuras/WeakAuras.lua:1930
 GetReputationsSorted = <function> defined @WeakAuras/Types.lua:1717
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 EnforceSubregionExists = <function> defined @WeakAuras/RegionTypes/RegionPrototype.lua:1138
 CheckSpellCooldown = <function> defined @WeakAuras/GenericTrigger.lua:3219
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 GetProgressValueConstant = <function> defined @WeakAuras/WeakAuras.lua:3950
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 Convert = <function> defined @WeakAuras/WeakAuras.lua:2301
 sound_channel_types = <table> {
 }
 CheckCooldownReady = <function> defined @WeakAuras/GenericTrigger.lua:3353
 event_prototypes = <table> {
 }
 NeedToRepairDatabase = <function> defined @WeakAuras/WeakAuras.lua:2378
 Atla

**Comment by mrbuds** [comment]
> what are saved variables and how do i find and "import" them?

It was explained on ticket creation

> If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the WeakAuras.lua file in `World of Warcraft\_retail_\WTF\Account\YOUR_ACCOUNT\SavedVariables\`. In case you do, please export the string and paste it below.

**Comment by Rotunda8** [comment]
[ezyzip.zip](https://github.com/user-attachments/files/16645300/ezyzip.zip)


is that ok??

**Comment by mrbuds** [comment]
yes thanks

**Comment by Rotunda8** [comment]
okay okay - so.. whats next? what do i have to do now? :)

**Comment by mrbuds** [comment]
export string of aura making error

user client seems to be german, with spell name in english

```
!WA:2!1v1tVTrru86MdezHGutvLkQaMkOcZHKg30IO3YMSgsvsC6ANMYP1ZUZZ7o01ZmmZS2X5wZbup7lCIl(mN8hH8jyLfx5seFcYNaEZURDubsoepZBE))9(9BR0Q2GA0A03T(uwOG3rKQcHkbJirI92DcT7OtE5l8Id8cfjc1lwb)BgH(ZPAdqpGXVTAC7(91GPYmcpmwOosW4MGDCpSRR38qHiHkgX7mIjHEntvjYheBms9Z3ydBawNj2yze2yZN6yZGENBuSOiqP)OhPkp(U7oHKQiCYaq)PETamgNtrbgMGxBR5rahuSWoXIrT5Z05)4be6yVClQoLcbP973DSeu)O7(h1649vPA4q8XExHh8lEFNeIwhFPonagcCthue705(BFS32(EUh0(vU7orlHKeRHzRnvN3RoMZmbYeYyq5LBN8(7uw31psjIuGwx)B6yTRHtkQC2NnxbKKox7P52CyPN7DE(X9O6QxM)WYW0tEhRG3RC7TmFpsby(615i393FIvpJIe(MEogSS9YD5KuEzdTQ8oKqdBi0T4(bck8h36kSVckoj5vy3hBT)2vVba52OTHgpBZoEcHZgK32FMN2quMwxaen0XOaEKj(dYA4WfCy(IHJVn4knGZvQ(CRQ2HqwtNbegVv2MObznZEs2wzpnRzqFgNPJ)3IXPNMySoeIvdlYSVykw1EqeEu)87L1yoEnaR2iLiLt7plqOOGYxZod(45LxeflQxuETyHUsLkRCzPKHmnlib6TWAGgbY705xsjkOER0KK6NeZmqwJj2OLRZ7UVSMbo14RJj4e)1LGHj5YS)7HFTuwF5n)(cf2(8L(g2aWFGG6BlRExw4diPFo(Xz7J72w(j5cjPgHTJhEcJAID2gVEvHRyNc0CHVv(v3uesGis4y)(jcHk(ICfSyxw)XzRovjmyW7IcDoS9HUYp)M8sXTkznuyHBFFEbyFr5on3MRziMu6delSwlf7S6VmLqXcLuVBx5xEtrrQGqMD4UY71t)PYGmFPtZXXTpU7(7DOBH0r4W4efrE(jLhkk1fdu5AfTYRzOYwTSew49svkc5olxnUoODWvjISXnL80Xivdl03eJ49ye(xrE))hDlo4znHgedSOyZBDsee6VMJydTmq9UCjDWB4ilsV8N4igxfhyijiu)EEdstmSQowO59Yyv9YT8rbAgpkb88A)dh7IINETxw9V(BhlCWQTCn0JBxYIJ84KtJdkyzcydKcL5AkEYP3EgJxK24O5)ykJhpvLJdZb2F4mktBjd3dr8bB(KMn)(TMSCVoB1MPm6mxNToQZq4XnoGRoTS)7nQytUg6(f0NiPKNfDiV7IpKy3v3LPj4qL2Z5mHyqLanma7mbBU(JxFZTMAeHLueR(7zpKrv5FSO(t8ijYyYkZ6RqgwKUcxgx5QIvGwwr2SpOZoEUUhQSmJiVYZYECvhKrYun77QgG1tFwuvfJB9peFPSKBV4lMF7dU1TVyrA6IehXtTCESCpv98fV0BoINXy2ww8qnDZDHH1g(NV(Fo
```

**Comment by Rotunda8** [comment]
Do I have to do sth with the export string above? Im at home in few hours then have to raid.

**Comment by InfusOnWoW** [comment]
No, that's for us to debug the issue. You got instructions on the discord how to workaround this. You should follow these.

**Comment by Rotunda8** [comment]
Ah ok, i see.. but i dont really understand what to do.. thats new to me and i am not that good with such things.. i am sorry :(
Do i have to Change every "Feint" to the german "Finte" in the saved variables from the weakauras folder (im wtf folder)? Directly in the lua doc?

**Comment by Rotunda8** [comment]
ok, i changed every "Feint" to "Finte" in the saved variables data thingy and started the game afterwards .. i was able to open the addon WeakAuras and i just deleted the aura, which caused the lua error and this helped a lot and there are no more bugs or problems or errors now .. lol
thank you for your time and help !

**Comment by mrbuds** [comment]
The fix is not implemented yet

**Comment by mcstealth666** [comment]
https://gyazo.com/81c1f8b70e6354d1667b45d55a616bf3

some Was are working ingame and some are not i got WA in my addons but doesnt show up in the addon ingame options stuff also i cant take new WAs
