### ISSUE TITLE
GenericTrigger

### ISSUE THREAD

**Issue by lordsesco** [WeakAuras/WeakAuras2#5333]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hey,
I started to get an error with any weakauras using GenericTrigger.lua. the weakauras stooped triggering and working and gives a lot of spam error.
specially when I'm using clickable WA

### WeakAuras Version

Weakaura 5.16.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
945x Lua error in aura 'Tank calls': Trigger 1
WeakAuras Version: 5.16.1
Aura Version: 10.2.6
Stack trace:
[string "return function(states, event, sourceUnit, ..."]:14: attempt to index local 'spells' (a nil value)
[string "return function(states, event, sourceUnit, sourceGuid, spellID)"]:14: in function <[string "return function(states, event, sourceUnit, ..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/GenericTrigger.lua"]:640: in function <WeakAuras/GenericTrigger.lua:625>
[string "@WeakAuras/GenericTrigger.lua"]:1095: in function `ScanWithFakeEvent'
[string "@WeakAuras/GenericTrigger.lua"]:1439: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:2038: in function `LoadDisplays'
[string "@WeakAuras/WeakAuras.lua"]:1820: in function <WeakAuras/WeakAuras.lua:1664>
[string "@WeakAuras/WeakAuras.lua"]:1863: in function `ScanForLoads'
[string "@WeakAuras/WeakAuras.lua"]:1933: in function <WeakAuras/WeakAuras.lua:1931>

Locals:
states = <table> {
}
event = "UNIT_SPELLCAST_START"
sourceUnit = nil
sourceGuid = nil
spellID = nil
spells = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spells' (a nil value)"
```

### Reproduction Steps

895x Lua error in aura 'Brezz Text': Custom Text Function
WeakAuras Version: 5.16.1
Aura Version: 1.1.1
Stack trace:
[string "return function()"]:11: attempt to call global 'GetSpellCharges' (a nil value)
[string "return function()"]:11: in function <[string "return function()"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/WeakAuras.lua"]:4876: in function `RunCustomTextFunc'
[string "@WeakAuras/RegionTypes/Text.lua"]:246: in function `Update'
[string "@WeakAuras/WeakAuras.lua"]:4612: in function <WeakAuras/WeakAuras.lua:4609>
[string "@WeakAuras/WeakAuras.lua"]:4701: in function <WeakAuras/WeakAuras.lua:4667>
[string "@WeakAuras/WeakAuras.lua"]:4811: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:905: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:842: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1127: in function <WeakAuras/GenericTrigger.lua:1112>

Locals:
greyCol = "|cFFAAAAAA"
redCol = "|cFFB40000"
whiteCol = "|cFFFFFFFF"
(*temporary) = nil
(*temporary) = 20484
(*temporary) = "attempt to call global 'GetSpellCharges' (a nil value)"
x Lua error in aura 'Second Wind': Custom Text Function
WeakAuras Version: 5.16.1
Aura Version: 1.0.2
Stack trace:
[string "return function()"]:5: attempt to call global 'GetSpellInfo' (a nil value)
[string "return function()"]:5: in function <[string "return function()"]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/WeakAuras.lua"]:4876: in function `RunCustomTextFunc'
[string "@WeakAuras/SubRegionTypes/SubText.lua"]:330: in function `?'
[string "@WeakAuras/SubscribableObject.lua"]:94: in function `Notify'
[string "@WeakAuras/WeakAuras.lua"]:4614: in function <WeakAuras/WeakAuras.lua:4609>
[string "@WeakAuras/WeakAuras.lua"]:4701: in function <WeakAuras/WeakAuras.lua:4667>
[string "@WeakAuras/WeakAuras.lua"]:4811: in function `UpdatedTriggerState'
[string "@WeakAuras/WeakAuras.lua"]:4531: in function `UpdateFakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:4504: in function `FakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:3192: in function <WeakAuras/WeakAuras.lua:3047>
[string "@WeakAuras/WeakAuras.lua"]:3216: in function `Add'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:2041: in function `ImportPhase1'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:2051: in function `ImportPhase1'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1654: in function `ImportImpl'
[string "@WeakAurasOptions/OptionsFrames/Update.lua"]:1623: in function <...aceWeakAurasOptions/OptionsFrames/Update.lua:1622>

Locals:
(*temporary) = nil
(*temporary) = "Second Wind"
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"

**Comment by emptyrivers** [comment]
We don't provide support for clickable auras. Contact the author for a fix, or delete the auras that are producing errors.

**Comment by lordsesco** [comment]
thx for the response, but what about any auras using GenericTrigger.lua

**Comment by emptyrivers** [comment]
every aura that uses a trigger which isn't a buff trigger uses generic trigger, including custom code. if you have an aura which is breaking and doesn't have any custom code in it, upload it and we'll take a look.
