### ISSUE TITLE
Animation stuttering/choppy

### ISSUE THREAD

**Issue by Aur0r4** [WeakAuras/WeakAuras2#5338]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hello!

I've a curious bug with some of my animated auras so I tried to break it down:

- clean 'Interface' and 'WTF' folder
- latest version of WA installed
- created a new simple aura and added animations
- 
As you can see in the following video, the animation stutters everytime I'm clicking on the enemy units, as long as I'm in close range to them. When I'm increasing the distance, the bug is gone. When clicking on my own unitframe, everything is fine too.

https://www.youtube.com/watch?v=AD-A-yQETTM

`!WA:2!DrvWUTTrqujRcyac4aB1uJgGCii1XnTOWOjaXhkqrROIuSdKLCjPJDVuPLKJi3AQDz2DPSLp1Ot5SU076sV0ErFc(qpti0VaFOFa(lOZUusoP6GWmZo7oVz47nLBwDq1WQHV)PtPbCMlpteapSK4Yo97lb1b)4Wx)h)wPsLMrc)1mPccpIC5A35qzRjgTm13(9EfPYcI5IJ5uMYVEJ2EnCMhW5jH8lyUxqtHExV0TryeeBRlCVXkbnkceY7TRyH5FBRgLc2zmQkTAMe6s8LCH)baj5iEi07gzMpmeyk3S(9PxoRB9AUEDD9Q54DZDPBs1XKN5QQyhgzaiTgltHKKddLwREOJfa(qoUh3OvR875RiIiqLUL(XsbCWWuXMxiESoKgy9Mgc(y59qKkoOrRJBEsRjzSfDGv6wKafDi4v4RXYFw6wCWacgj5ny7s5SF)2ZbiTgcNaLdrr5Xtim6aTfBFhjIc1BY3Wpva4yEmqKGUA2modMhMjm51vpQesahLHYR154QealsfVE(oJLj0qqXtThqOSM5F165BKVB(xM)08NKVRFFkJkJXsKVJ23ehtzNzMR5Zvk(aSnLeLUyq8uCC5aryvLF325BmhD9jbNhj4zSW3F)0Qk4svxzmb)eFwb5OC6dmbn)1NlWMRRCHr(UtwD2JFImDZp4615jCXRlxUCLBkIcj9nel7AN41j9tnbjziaXPqWP0qvSDn092IcrVecnbF38cs5pVaoxBoxtIP9hLV(ubxHDMhg0UDN2nY3qGnLoNPMedmWOc(BYIoGPs3SPGE1J(PmsiovipYZ7JA8LvAUj2fCr4Pcs64txyuaGHuj1pb6TON)aHt6wh2UDdNU2D886CKZHV6aV5RkTl9k4bl6OZ(O6Op1qf7CIxRdB34FNhLWVOPaEBgWcgD8N8T798xu0D6dUw)3lxqHQmw7PV9C)m8BoRZqqKqgnvhULHl9zZ02lBTjAN6RgnxJAIxTmsSjZvGZ8YX0GZzGuwXCr3ascuXwBgBc0IIhULPA24uceX(Xankw9o7eojSjkhtqf42odYsuulBTEz78FXYjiHiLAlBjoy0gPBIyP2ILuMDwX))quw8uHHeR74ClhssAmPYZZOHZQ7oscoVKRYyZOScwkMO1nPcEeQcLfRj)6hwAnHwFJcH9Z)cR8VXYgLskl7R48bLDUJ1mvXdgwi2)8Y)1ShJ1WvHZyqqzr)WS(cCHeQxrAufZMU6l2pI7lWfc46RlmK4Bl(K3uNUg1(U1DA0OTpk67tJSWhtxeio9(lxWQz0VKkjijlmEokuWR3j1GyRP6Df0c7XlVqVjRKy5Rxv6)I9E2(79SQd)NZ(Vd
`

I've tested it with multiple other characters in different zones, I always got the same issue. Only my Level 48 Warrior toon has no issues with that.

I copied the character folder from the "known good character" and renamed it to another toon -> same issue
I've tested it on my US trial account -> same issue

Disabling the starting animation seems to fix it.

I encountered this already ~since Dragonflight launched.

This ticket here describes a similar problem::
https://github.com/WeakAuras/WeakAuras2/issues/4696

### WeakAuras Version

WeakAuras 5.16.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
no errors occuring
```

### Reproduction Steps

- Import aura from description
- go to Stormwind and click on the training-dummys
- clear target
- the aura will flicker while the end animation starts

### Last Good Version

unknown

### Screenshots

Video URL see description

### Export String

```Text
!WA:2!DrvWUTTrqujRcyac4aB1uJgGCii1XnTOWOjaXhkqrROIuSdKLCjPJDVuPLKJi3AQDz2DPSLp1Ot5SU076sV0ErFc(qpti0VaFOFa(lOZUusoP6GWmZo7oVz47nLBwDq1WQHV)PtPbCMlpteapSK4Yo97lb1b)4Wx)h)wPsLMrc)1mPccpIC5A35qzRjgTm13(9EfPYcI5IJ5uMYVEJ2EnCMhW5jH8lyUxqtHExV0TryeeBRlCVXkbnkceY7TRyH5FBRgLc2zmQkTAMe6s8LCH)baj5iEi07gzMpmeyk3S(9PxoRB9AUEDD9Q54DZDPBs1XKN5QQyhgzaiTgltHKKddLwREOJfa(qoUh3OvR875RiIiqLUL(XsbCWWuXMxiESoKgy9Mgc(y59qKkoOrRJBEsRjzSfDGv6wKafDi4v4RXYFw6wCWacgj5ny7s5SF)2ZbiTgcNaLdrr5Xtim6aTfBFhjIc1BY3Wpva4yEmqKGUA2modMhMjm51vpQesahLHYR154QealsfVE(oJLj0qqXtThqOSM5F165BKVB(xM)08NKVRFFkJkJXsKVJ23ehtzNzMR5Zvk(aSnLeLUyq8uCC5aryvLF325BmhD9jbNhj4zSW3F)0Qk4svxzmb)eFwb5OC6dmbn)1NlWMRRCHr(UtwD2JFImDZp4615jCXRlxUCLBkIcj9nel7AN41j9tnbjziaXPqWP0qvSDn092IcrVecnbF38cs5pVaoxBoxtIP9hLV(ubxHDMhg0UDN2nY3qGnLoNPMedmWOc(BYIoGPs3SPGE1J(PmsiovipYZ7JA8LvAUj2fCr4Pcs64txyuaGHuj1pb6TON)aHt6wh2UDdNU2D886CKZHV6aV5RkTl9k4bl6OZ(O6Op1qf7CIxRdB34FNhLWVOPaEBgWcgD8N8T798xu0D6dUw)3lxqHQmw7PV9C)m8BoRZqqKqgnvhULHl9zZ02lBTjAN6RgnxJAIxTmsSjZvGZ8YX0GZzGuwXCr3ascuXwBgBc0IIhULPA24uceX(Xankw9o7eojSjkhtqf42odYsuulBTEz78FXYjiHiLAlBjoy0gPBIyP2ILuMDwX))quw8uHHeR74ClhssAmPYZZOHZQ7oscoVKRYyZOScwkMO1nPcEeQcLfRj)6hwAnHwFJcH9Z)cR8VXYgLskl7R48bLDUJ1mvXdgwi2)8Y)1ShJ1WvHZyqqzr)WS(cCHeQxrAufZMU6l2pI7lWfc46RlmK4Bl(K3uNUg1(U1DA0OTpk67tJSWhtxeio9(lxWQz0VKkjijlmEokuWR3j1GyRP6Df0c7XlVqVjRKy5Rxv6)I9E2(79SQd)NZ(Vd
```

**Comment by InfusOnWoW** [comment]
That's due to the game sending us absolutely bogus data, see https://github.com/Stanzilla/WoWUIBugs/issues/520
The game on deselecting a target claims that you have lost, gained and lost the target if you are close enough for the soft target. 

The soft target is for gamepad support, which you can disable by running these commands:
/console SoftTargetEnemy 0
/console SoftTargetInteract 0

**Comment by Aur0r4** [comment]
I tried those commands via Chat and Macro and checked with
`/dump GetCVar("SoftTargetEnemy")`
and saw that it was still active (1).

I tried with
`/run SetCVar("SoftTargetEnemy", 0)`
then and it worked for me, issue is gone.
Have to make it on all toons now.

THANK YOU! This was making we crazy yesterday.
<3
