### ISSUE TITLE
Ready For Update stuck

### ISSUE THREAD

**Issue by contiumn** [WeakAuras/WeakAuras2#5339]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

One of the weakauras is always ready for update and I cant remove it. 

![WoWScrnShot_081924_131254](https://github.com/user-attachments/assets/c5c5388c-a10b-4cec-ac44-7c0ab88c4dc6)

### WeakAuras Version

5.16.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

No steps i just download liquid - aberrus weakaura then deleted the aura but the updated is still showing up even after installing and deleting the aura.

**Comment by InfusOnWoW** [comment]
Take a look at this message on our discord: https://discord.com/channels/172440238717665280/532314347477925891/959031908283604992 

If after following these steps, you still have a problem, post a message in that channel. The message should help you identify the source.

**Comment by contiumn** [comment]
Still stuck on ready for update after downloading it and deleting.

**Comment by nozzlegear** [comment]
For people who don't want to join a Discord just to read a message that should've been posted in the issue tracker:

<img width="1107" alt="Image" src="https://github.com/user-attachments/assets/9396a496-b62b-4eef-86d0-dd6e3619f40d" />

**Comment by Pewtro** [comment]
Those images have been posted several times or have been explained by text on the issue tracker already. 

See #4581 #4531 #3776 #3636 #3563 for examples
