### ISSUE TITLE
LUA error: Missing '}' expected near 'MAX_SUMMONABLE_HUNTER_PETS'

### ISSUE THREAD

**Issue by brittyazel** [WeakAuras/WeakAuras2#5341]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

New with the 11.0.2 update, 100% of the time when I open the code editor window in WeakAuras to edit my custom trigger, I get the following Lua error. This error _does not_ seem to be an issue with WeakAuras, but rather in Blizzards documentation code, but given that it happens 100% of the time, perhaps there's a way that WeakAuras can patch around it temporarily. Either way, I thought I would at least report it for the record so it can be tracked upstream.

### WeakAuras Version

WeakAuras 5.16.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
8x Blizzard_APIDocumentationGenerated/PetConstantsDocumentation.lua:1 Blizzard_APIDocumentationGenerated/PetConstantsDocumentation.lua:14: '}' expected near 'MAX_SUMMONABLE_HUNTER_PETS'
```

### Reproduction Steps

1. Open WeakAuras panel
2. Go to "Trigger" tab in one of your weakauras
3. Hit "expand" in the Custom Trigger section

**Comment by mrbuds** [comment]
This is a bug from blizzard, they are aware of this issue.
