### ISSUE TITLE
Cross realm Aura sharing fails

### ISSUE THREAD

**Issue by asaka-wa** [WeakAuras/WeakAuras2#5342]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Sending an Aura via in game link to a character on another server.

The prog count goes to full but then the popup stays on screen and the import never actually goes through to the WA config window. 

This feels like an AceComm issue with the final message on a multi message send not going through but I haven't investigated fully to know for sure precisely where the issue lies. 

It may matter that the two chars involved in sharing were bnet friends...?

### WeakAuras Version

5.16.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Have char available on another realm
Whisper them a link (also tried sending over party chat)
They click the link
See the popup for progress

**Comment by InfusOnWoW** [comment]
This is a game bug or a wrong assumption in AceComm that chat messages are delivered in order:

This small patch adds debug output to ace comm which just outputs the messages that are sent and received.

[debug-output.patch](https://github.com/user-attachments/files/16921799/debug-output.patch)

On cross-realm sharing these messages can be out of order, e.g:
Sending side:
<img width="146" alt="Wow_FfI2bkrow6" src="https://github.com/user-attachments/assets/8aaa8c05-a5a9-4b62-a5a9-342db0c9f74b">

Receiving side:
<img width="139" alt="Wow_KrYGIMabfD" src="https://github.com/user-attachments/assets/2154b0d3-9d13-43a7-a5fd-bb20333587c1">

**Comment by InfusOnWoW** [comment]
This is a patch making AceComm able to deal with random orders, although at the cost of being incompatible with older receivers.

[ace-comm.patch](https://github.com/user-attachments/files/16922224/ace-comm.patch)

With that patch I can share auras across realms successfully.

I'll bring that to the ace comm's maintainers attention.

**Comment by InfusOnWoW** [comment]
There's nothing more we can do in WA, it's either the game or AceComm that needs to change. If neither changes, we'll probably need to disable cross-realm sharing again. But that doesn't need this ticket to remain open.
