### ISSUE TITLE
[Cata] Item Equipped trigger doesn't work right if you have normal + hc version of the same item

### ISSUE THREAD

**Issue by Kolmarwow** [WeakAuras/WeakAuras2#5343]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

If you have normal + hc version of the same item and you try to use it in an Item Equipped trigger, it seems to only check for the normal item even if you put the heroic itemID into name field. In my case I'm testing with [359](https://www.wowhead.com/cata/item=60324/earthen-legplates) & [372](https://www.wowhead.com/cata/item=65267/earthen-legplates) Earthen Legplates, I noticed that if I set "Item Slot" to Legs then it works fine for both items. The Item Equipped load condition has the same problem.

### WeakAuras Version

WeakAuras 5.16.1

### World of Warcraft Flavor

Cataclysm Classic

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. You need to have a normal & hc version of the same item on your character.
2. Create an aura that uses Item -  Item Equipped trigger.
3. Put item into name field, it will only look for the normal version even if you put in the itemID of the heroic version or have normal item in bank.
4. If you enable "Item Slot" relevant to that item then it seems to work with both versions of the item.

**Comment by InfusOnWoW** [comment]
That's because we check by name instead of by item. For spell we have extra options to check via the spell id instead of the name. For items so far, that has never been necessary to add.

Is there any reason you want to keep the normal item around?

**Comment by Kolmarwow** [comment]
In my case I use the heroic legs in DPS set & normal legs in tank OS set with different reforge/enchants/gems, as the DPS tier legs are perplexingly better statted than the tank tier legs for dungeon tanking which is what I mostly do. Admittedly a very, very unusual edge case which won't be relevant once I upgrade those "tanking dps" legs to a 2nd heroic version. 

I mainly opened the ticket as I saw someone on discord confused about why their Item Equipped triggers weren't working, but I can see this being something not worth fixing due to how infrequent it is, especially when you can fix it by enabling Item Slot.

**Comment by InfusOnWoW** [comment]
It has come up often enough, that'll at least take a look at how complicated implementing it would be.

**Comment by mrbuds** [comment]
On SoD they also added weapons with different skin/effect depending on difficulty it was obtained

![image](https://github.com/user-attachments/assets/f9abcc30-5cdc-408b-8399-a9aa25e7e34c)
![image](https://github.com/user-attachments/assets/e4f80827-5814-4a9d-a267-2e10b2edb148)

![image](https://github.com/user-attachments/assets/a7a9b90b-d79c-41d7-9a75-1a7f268691d9)
![image](https://github.com/user-attachments/assets/3520a91d-6ed5-4af6-9040-b83295fb114f)
