### ISSUE TITLE
Steady Flight

### ISSUE THREAD

**Issue by coldfire989** [WeakAuras/WeakAuras2#5344]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When you are using Steady flight there is no option to not load the WA set. The one that is there for skyriding doesnt work when you are in Steady Flight mode. Would be nice if there was just an option for mounted/not mounted and it covered flying as well. I was asked on Twitter to make this ticket.

### WeakAuras Version

WeakAuras 5.16.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Open WA
got to the load tab
click the option for not skyriding but be in the steady flying mode

**Comment by InfusOnWoW** [comment]
What's the use case for a steady-flight load option?

**Comment by coldfire989** [comment]
not sure what you mean sorry I dont speak WA very well

**Comment by coldfire989** [comment]
> What's the use case for a steady-flight load option?

If you mean why do I want it. Because I like steady flight better then skyriding and I like for the WA to go away when mounted and it doesnt do that for steady right now

**Comment by InfusOnWoW** [comment]
Ah now I understand. That's too niche for a load option.

**Comment by coldfire989** [comment]
This is no different from having it load for skyriding. Why not just have an options for mounted over all. Good lord

**Comment by InfusOnWoW** [comment]
Because Skyriding comes with a specific UI control, and there are WA that are specifally for those UI controls.

**Comment by coldfire989** [comment]
So why not make it work for both steady and Sky? Maybe even for just being mounted period. I think there are many people who like to see the screen when mounted.

**Comment by coldfire989** [comment]
Plus the UI controls for Sky riding can be moved anywhere so you can see them so no reason for a load to hide the WA by that logic.

**Comment by InfusOnWoW** [comment]
The sky riding option isn't just useful for hiding stuff, but also for showing specific controls while skyriding.

In any case, the decision has been made. You had ample opportunity to add additional information. It's clear that you merely expressing your dissatification now.

**Comment by InfusOnWoW** [comment]
I don't think a mounted option is worth it either.
