### ISSUE TITLE
About the new ''Procc'' glow effect.

### ISSUE THREAD

**Issue by Fierced28** [WeakAuras/WeakAuras2#5347]
Hey.

So I went on retail today and I saw that weakauras have a new glow effect.
The one called ''Procc''
Pretty much a swirling effect but it looks so much cleaner than the usual ''glow''.

I was wondering why this option isnt on the classic wow version of weakauras?
As I spend a lot of time there, I would like to see it there too now that I've seen it!

Cheers

**Comment by InfusOnWoW** [comment]
It's something blizzard added to retail.
