### ISSUE TITLE
/wa does not work, chatcommands do work

### ISSUE THREAD

**Issue by freakkater** [WeakAuras/WeakAuras2#5348]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I installed Weakauras on a fresh wow classic and tried adding an aura for WoD where weakaura just stood still and did nothing, then my game crashed. Afterwards the big weakauras window doesn't open

### WeakAuras Version

WeakAuras 5.16.1

### World of Warcraft Flavor

Classic Era

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
..\AddOns\WeakAuras\GenericTrigger.lua line 215:
   attempt to concatenate a table value
..\AddOns\WeakAuras\GenericTrigger.lua line 215:
   in function <..\AddOns\WeakAuras\GenericTrigger.lua:188>
..\AddOns\WeakAuras\GenericTrigger.lua line 279:
   in function <..\AddOns\WeakAuras\GenericTrigger.lua:236>
..\AddOns\WeakAuras\GenericTrigger.lua line 1214:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 2424:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:2356>
..\AddOns\WeakAuras\WeakAuras.lua line 2502:
   in function `Add'
..\AddOns\WeakAuras\WeakAuras.lua line 1992:
   in function `load'
..\AddOns\WeakAuras\WeakAuras.lua line 1999:
   in function `AddMany'
..\AddOns\WeakAuras\WeakAuras.lua line 969:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:941>

Debug:
   (tail call): ?
   (tail call): ?
   WeakAuras\WeakAuras.lua:1007: Login()
   WeakAuras\WeakAuras.lua:1071:
      WeakAuras\WeakAuras.lua:1023
```

### Reproduction Steps

fresh wow classic with only weakauras 5.16.1
load ANY WoD Aura

### Last Good Version

Weakauras 5.16.1

### Export String

```Text
sadly here is NONE!
```

**Comment by mrbuds** [comment]
You didn't include your weakauras data as asked

**Comment by mrbuds** [comment]
You tried to import an unsupported aura, there is no version of weakauras for WoD, we don't support private servers.
You will have to use a backup or purge yourself the broken data from your weakauras savedvariable
