### ISSUE TITLE
lua error on login

### ISSUE THREAD

**Issue by Slashfile** [WeakAuras/WeakAuras2#5349]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

On every login i get this lua error. It seems to happen during character load screen.

### WeakAuras Version

5.16.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
1x WeakAuras/Libs/Archivist/Archivist.lua:567: Encountered unexpected token type while parsing object. Expected "KEY" but got "VALUE".
[string "=[C]"]: in function `error'
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:53: in function `Assert'
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:567: in function <WeakAuras/Libs/Archivist/Archivist.lua:546>
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:586: in function `DeArchive'
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:310: in function <WeakAuras/Libs/Archivist/Archivist.lua:301>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@WeakAuras/History.lua"]:20: in function <WeakAuras/History.lua:18>
[string "@WeakAuras/History.lua"]:39: in function `CleanArchive'
[string "@WeakAuras/WeakAuras.lua"]:1384: in function <WeakAuras/WeakAuras.lua:1354>

Locals:
(*temporary) = "Encountered unexpected token type while parsing object. Expected "KEY" but got "VALUE"."
```

### Reproduction Steps

just login another char or relog the previous one

### Screenshots

[WeakAurasOptions.zip](https://github.com/user-attachments/files/16737343/WeakAurasOptions.zip)

**Comment by emptyrivers** [comment]
Your savedvariables has a recovery snapshot which is corrupted. Close the game, and replace WeakAurasArchive.lua in your savedvariables with this file [WeakAurasArchive.zip](https://github.com/user-attachments/files/16738524/WeakAurasArchive.zip), and that should fix things.
