### ISSUE TITLE
Arcane Surge Mana cost is incorrect

### ISSUE THREAD

**Issue by Berlinia** [WeakAuras/WeakAuras2#5358]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

![image](https://github.com/user-attachments/assets/42d76ce9-7585-413e-a5ce-751c675193d7)

Arcane surge dumps all your current mana, but weakauras calculates this as *max* mana, for the purposes of the mana progress bar, leading to the following situation:
![image](https://github.com/user-attachments/assets/d16e17fd-f2c2-4b8a-a91b-aa325eb207c7)
Hope this helps!

### WeakAuras Version

WeakAuras 5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
This is working as intended, but the intention is incorrect with the game behavior.
```

### Reproduction Steps

!WA:2!fA1tVTXXvCsreeaIMcjzx1yBfafJeHeJy9paBdRwxhUYuMmGIKy5klBddSC2DhYDQwUZKzMLIYabOLN8PCGxcqb8fEU9c)c0cDix6Lfe5AVq0eGEQa8tqFZSlPOCpyDGAFZ8M5979E)EV3K9Wv7SQ3QEV5pmuWq8tpH4j9)ndjU0Wg0iUlE9m8E1A1sGLzhH8(Jrcj27iuVL4NpF1qxFkVoLek3ZQw9X67XKkrscnm7Er8a2T8LsMy)T3(muB6we62pW29KIw3VM127YrUkff33uirCzENwKqIWpVb8pzEnsSDPbu(3Kd(Bcoe5eGFkh5rWHs)bcCqlTTDmQzzv7O(oi(bA1l94)5TU1xNjt2sp(NJI(tzYKP0J)pp8HnHpYn0dlqYiosI9Vqd4eV5fzzxRD6DxJR(v7fdlvZS8lRv1QqfJakY7hhhjW2mS0bjLby)bkXqCxm33rIcGJTMzNOajj)i1oDX(exqn2Qkj3aKqyJc9SfmSBtdonaVPJGe2oa7uQyHkfnJxFT4pTPHA)1Ixp)4fUKJj(SLvYECiwgYjEWb9n1xQs3jx96xlEJVZqqEnwTN(GfstIqAKe6pKJBdoO15mmhbXdi6XL4EqObpSyq3JlVrvkVJXRP0ozn1bk)HsQl4Pc4yFC2)2ituaZhLZbYtTiTZVy085zDuj8YpzW889LCis4sSvUcx5iQh2OWXw16l5K2Tbt8R3KN(5VyibiAebCIKOiYrq5oLWOa1XAore5aX)qzJOwTi9gzFqHgw2nSkyAn5s11QAQ1ZSo9mmp(35WcqNJ5xOus4tp7aQq2CatTPYIz7drXGGYEI8MHOoyr(5wQohdwYSr9IvQ0xDCf4AMWmMD8MarZbqKo(wQyL6hECLbrHPovE2kkYFxSvIScE)1mtbYmMhIcEwsq(hMW402CSqKurEN1ZS0auiPJoOD)4F1HxGrcCdjhh2w6)HX7BesdXJ9u0BqdBfq4cmKG8e9vQQqtCdJois4HXMWbIBeBfFC8ZG))rV7k80CDUHGJBQzlIxUw8(JbrhK7PT50OqV0fArb(KEHUJDOCpm3MM0MyMys3I9aE2O0vuSZCxKkKuPNnB2CtsxPlrqGk(MZuh71gZwPX3gH44nomkiyJt8jsC8(duasRZBUb7gksST(hatqOYom9J4gdMVhB5pF3TGGJlKo15SpNTSEtHpYtXfMdMKvN1Rj(bSRPxbfjPQ8GRUVPrbqCAIrj9WE6f)ZJtC5xK2V8c9(QIasRZDoOyvRIMd5QsaSfSJr1AvlYwn52x8G1ZTZw3lEFo4LAOVOkpp9UhQx7YULdsdaG3TIbLteByeaPm4xAVES78)fJUAWWwNi10hZwbukp1MjbNuyTEg2MVV7jzvNQrDCW8XAfpdsuNWrS(NK(rsyzwYonnSWOLy6vSEQhNJT77Z4EyxOujWMXHpue5SJNhvAauVpz8vJHxURUOT2XwvkxT4BwzmKLp1MpBU2fAXzJgNQLwyOIUVFAJuFGSO2g604I7aaZUduOpOGSEcotUQuLzFrzv5Flq1xDacijHTnq8xDC57EP0DBOABosFSaDr)JME1EeIBENVkZsPSfqTPxfaIBE7hSdB55S30BP5KeKadAoneURpyOwoTMS0J)V22QXO5YLG4zjReP5Vhql1HW5uUFIDbLaEKYP3RWtEIJpM02xUY4upobX7vPXrt0JdmuARAfg)xE3bwOE(qFCL6oKomkhkGtsEhYHEZ6FyRDcgDAbili2)iuB8DRZH0p)COv7LAwh6DecT51pUqq8WMMLFAjRbZE7WEq1t2CJ0WPKgTpYqPR)uk0negyiSsW(nJ)QuTiEE4qZQfFwrthbUdOM5UBTZw7m9YEKZBNK92eV(hHcrBajtZZuDj(S1g1sHmOlosIwz6cGvrdh1OyLIhyDOzHJkMmHnfaXF)EreVrUhFAB8xYE9oSZ5KqvhBSFYd6oyEZGr0lFqt8VDOACar)YRBUPPRp290dJFyU(DrCI6fwxSyrKzxuqeg4m3MYU9V)rCxFuyBGKTz8FxXl(xV9T)d97S(3x)6BOii9b2itnbm(AJiHj1LGLYpgyCGBvJPTB(vfo3BRDFWw7SA3F65)Vp

Try casting arcane surge as an arcane mage, while not at full mana, and the error should be reproduced.

**Comment by InfusOnWoW** [comment]
That's what the game reports as the cost of the spell. You can work-around that by enabling the "Clip Overlays" option
