### ISSUE TITLE
Glow option doesnt work

### ISSUE THREAD

**Issue by Rhosaks** [WeakAuras/WeakAuras2#536]
Hello everyone, the problem is that the GLOW option does not work. The active, either by animation or from the icon itself, even with triggers, there is no way for the effect to appear.

Is it a BETA problem or does it happen to someone else?

I have the latest version and use ElvUI. In LEGION it worked perfectly

Thanks.

**Comment by InfusOnWoW** [comment]
When you open the ticket, you got some questions, that you choose to ignore. Without answers to those we can't help you.
