### ISSUE TITLE
Pass the cloneId in triggerState when a watched trigger that uses clones deactivates

### ISSUE THREAD

**Issue by calummitchell** [WeakAuras/WeakAuras2#5363]
**Is your feature request related to a problem? Please describe.**
When a watched trigger using clones activates the triggerState table contains an entry whose key is the cloneId and value is the trigger state. But when the watched trigger deactivates the triggerState table is empty so there doesn't seem to be any way to know which clone deactivated. This information might be necessary to the code in the custom trigger e.g. for managing TSU states.

**Describe the solution you'd like**
When a watched trigger with clones deactivates, the triggerState table would contain an entry whose key is the cloneId and value is nil.

**Describe alternatives you've considered**

**Additional context**
In my particular case I want to glow party frames when certain spells are being cast. I'm using a TSU to manage the glowing and the watched trigger to listen for the specific spells being cast.

**Comment by InfusOnWoW** [comment]
The solution you want is not possible with lua. You have to simply track which states existed previously.
