### ISSUE TITLE
Paladin Hero Talent Hammer of Light

### ISSUE THREAD

**Issue by derechte112** [WeakAuras/WeakAuras2#5367]
Hammer of Light Condition 'Spell in Range' does not work ?
probably because it uses the same hotkey as wake of ashes ?
it works if i use Hammer of Justice as a range indicator but it only has 10 instead of 12 yards range

**Comment by InfusOnWoW** [comment]
That's on blizzard, C_Spell.IsSpellInRange() simply does not work with that spell.
