### ISSUE TITLE
WA_DELAYED_PLAYER_ENTERING_WORLD stops working when Hero Talent is selected in Load Tab.

### ISSUE THREAD

**Issue by SweetaurasDev** [WeakAuras/WeakAuras2#5373]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I noticed my code would not run when WA_DELAYED_PLAYER_ENTERING_WORLD fires whenever a hero talent is selected in the load tab (specifically the Tempest Hero Talent for Elemental Shamans). Removing that check and checking if spell ID 454009 is known fixes the issue.

### WeakAuras Version

WeakAuras 5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No errors observed
```

### Reproduction Steps

1. Create New Trigger
2. Set Trigger type to Custom
3. Set Event Type to Event
4. Set Event(s) to WA_DELAYED_PLAYER_ENTERING_WORLD
5. Set Hero Talent to Tempest learned in the Load tab

**Comment by InfusOnWoW** [comment]
That simply means that your aura loads after the event has fired. That's not a bug.

**Comment by SweetaurasDev** [comment]
This was a suspicion of mine but wanted to make sure. Also, I figured this may help someone in the future who runs into a similar issue. Thanks for the input!
