### ISSUE TITLE
Can't right click WAs to bring up context menu to do things like copy or delete

### ISSUE THREAD

**Issue by gabespound** [WeakAuras/WeakAuras2#5376]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have disabled all other addons and restarted my game, i am unable to right click on Weakauras in the /wa menu to do things like copy or delete.

### WeakAuras Version

5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
no buyg output from buggrabber/bugsack
```

### Reproduction Steps

type /wa
right clik a weak aura or group
menu doesn't come up

**Comment by emptyrivers** [comment]
I can right click WAs to open the context menu just fine, using your steps to reproduce. You'll need to provide more information.

**Comment by gabespound** [comment]
What more can i provide?  Only addons loaded are WA,, WA Archive, WA Model Paths, WA Options, WA Templates.  no bugs logged when i try to right click.  no special right click keybinds

**Comment by InfusOnWoW** [comment]
The issue is on your computer only, since we would have heard of such basic functionality breaking.

Did you try this with busack/buggrabber enabled? Your last message is a bit unclear on whether they were enabeld or not.

Can you post a video of it not working?

**Comment by InfusOnWoW** [comment]
Waiting for your response.

**Comment by mrbuds** [comment]
If you still have this problem, try change your uiScale setting to 1
It seems a uiScale of 0.1 break the right click menu
