### ISSUE TITLE
WA not recognizing Creeping Death talent

### ISSUE THREAD

**Issue by zaldor29** [WeakAuras/WeakAuras2#538]
**Describe the bug**
I am trying to get an icon to appear when Creeping Death talent is chosen for Affliction lock.

**Do you have an error log of what happened?**

**To Reproduce**
Create icon
load using talent Creeping Death
set trigger to status:Conditions:Alive

**Expected behavior**
Just show an icon when creeping death is selected as a talent

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Doesn't matter and have done the same steps with multiple other talents and they all work fine.  This is actually a copy of a previous one with the load changed.  

**Which version of WeakAuras are you using?**
2.6.3

**Was it working in a previous version? If yes, which was the last good one?**
Unknown

**Additional context**
N/A

**Comment by emptyrivers** [comment]
I can't reproduce this using your steps.
