### ISSUE TITLE
"Spell Usable" condition is broken

### ISSUE THREAD

**Issue by Bakamaka11** [WeakAuras/WeakAuras2#5382]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

"Condition: Spell Usable - True, then Glow."

But the spell is on cooldown, wa thinks it is ready and it glows. 
I tried "exact spell match" and i installed IdTip and checked that it is the right ID. I tested it with priest's Halo, Mind Blast, Void Torrent - everytime this condition assumes spell is always usable.

But if i set condition "On Cooldown" instead, then it works, but not fully do purpose of "Spell usable"...
I had to redo all my WAs because of it with additional separate "Crowd Controlled trigger." But i remember condition "Spell Usable" was working earlier (atleast in wotlk), something happened now. 

### WeakAuras Version

5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1) Trigger: Spell-> Cooldown/Charges/Count. Insert any spell ID with cooldown (120644 - Halo for example). Show - Always.
2) Display: Setup any Glow, uncheck the mark.
3) Conditions: If trigger 1 Spell Usable -> True, then Glow 1 -> Visibility ON checkmark
4) Use the spell and glow will be still ON, WA thinks spell is usable despite being on CD or CCed.

### Last Good Version

Im not sure but in classic wotlk it was working fine

### Screenshots

![231233](https://github.com/user-attachments/assets/7af0fdf2-9744-4bca-8eb2-c161931aaeac)

### Export String

```Text
!WA:2!1z1tVTrUv8iRKDrfAbS924MS)PW7IeHMTacEDQJ3fix0ylVXb2YQJKR9EsdNzOMHXuKmKCKT8Tv5soREO31L(hGcuOd7ha9fOdekqV7d9dG)e0h5msR9UYgWAiF89E837)SWER2D1WvdF)VFejGZAYtKb4p9EJrHVjrPXHhIUyPFCdHTKS)rD6OW6tFWxTXZR81JrSGyUSbNW0(7uRERAUtd4CAi)CwZZjcSNy5aqyE3w4l0hlcrASFI9ZKz8vlmchlrbAcNPEHRsJK6s(DimIkUKd8rxAGwsIIWsv9YY8LV)34QbHoZbLO5drjsed1fRkjbnEeJ23BAeMHLKGMX8ZpInsbFQsph1xDLkXh3dZ0nK4oKlCB2O2bhiEyIc32WeLRu8oGZql504rHaE70PvFbw(QQUhU3Xhyv1ouodRILGu1H7nEOsGPuZYhv4)U71a5AxaMutd19dJDsaZWhSSiSEAxKoigRYaw6AUwWiE8o5(J1Bi5rsSsT(VZk(ZeFKbByJ(Ap)A8C0aMCT7NAX(8tgOYUvvP5MAtWgixmU9ovB2QDZwvDBjwXi0T8rEUzUWHMtSoxVjghRvDKqZbSCVFPXHe1BsyqqRhEteRVyfKDDRSZpKhIlEnKuGLme9pbroi4(xUsKBzz5zF5NEVLgQW0o20N0pa81kKgUqnoEeGCxCKjL41RLwEkS1hauKKNWcF)tf)wnKp12(thUe8OTfT1KU48Dfep(NXGkFHddcDdNF8x8uH4twG2IccBhGu6yXY2duXii6SdNYLVUqHcfVoJDYf4WtiH64Vx8K7ctuCekOF7ouox6nsY1GfAQhCQFu9AluSqCaPlI2wiHfgFxrXhFhye(pEKLCGfBfH)wO7XAqXigdtJfREdB67YkPlm1s7CUm8ejsm4K8ftZvdtBRco64whSpa71VJRiMeIBFjwY9(rbBsUe)SPz9kon)2wqesKVW141cVkdIZYpCQECRJeFKLOPMh4Jey98ovHTlWK13kJi)6NzStSCAASr60p9dwaAMTi9pMwwc5FMZgo3KMuvsq01RJKqhNC35TUHgfFELTep7UqvyFOyJe0whdfeXqLF)fWR4o4TO4ZVl9EJmMLVbOSUWH7xVEn32ToQrM13dy0Nc9OVz2W84ZNFxW5gxXIYD9jrTzjD9XYCAIvQ67lX9iqAFD7bQfM9yvExEyBthaVot9Heqqj8m8moFRcYLkojFtW8YXRYPmZMMXogMUiwP5Btqs867LqPRFsmrJtlp00sXYZ)BAeLF(Es8BtWSG(nU)gv2ClhdT4jqRWVLMx27nWqZue42ak7PJmBpaZI0XpCSz9SCRHrZeXwnoXSDxtFnJpllzYqYktU7(0IBuzlloAftcodMTOkAvtZaefNT8acqEf7T6ybESFmMefRp0HYrH)WvbuKsbb8qZWGGY(kclIIFYYUDtOAYA)BpycefMgSw67kjw10L)2s4nConp5LqxsygYsowDLo4bGqdYh0KZjdMTiJhk6jY0lW1NL(U1(mpxRoGTU76E8(7cs6ycB27DzqYQ5VOW(aJyluMn9dMC4Ac))u(iS4rs7abtaWX8ALRGA3GZ6pZZgpy2lk8KxKxdE)T3UY2P)zVPqhdOk4iH9rgL8bP7qIkDDwXXEsyUNrT(n3XTwT6oxY5DlKUQ3inpOx2WRhv4Fo(liH(Vcr5RV54ogrAcdj1OFHlIkIrfDp30mQX9F(xx5Be)6zyX0NFxIcb5KHEBMqchRU8KTBTXzx2FlQKWmQh7D9zySOQXZQDngt8qeJ01AwVi9xU30WCBSTzOpiaG)qvA50xobJugCyZc)WbMDgdj9LoDre2EP)10)MHT0)(hM(pGp)QFkLrgnrSELpUSl8SKGZEr6Yfh0dbT3amp2o8)yl(D7HOj4IsZqKimWF6)YBamshqKUVzGDL)qfBEnHLvtdAT8yyzaUM5rikpXJirmUeNhhSuRbnqLkiLzE9YQk)TQ8vBxzJv79Fo9))
```

**Comment by Bakamaka11** [comment]
![image](https://github.com/user-attachments/assets/3c6be46f-b93b-42ed-b0b9-988850bb0ef4)

Everytime this condition assumes spell is always usable.

**Comment by InfusOnWoW** [comment]
You misunderstood what spell useable is checking. It's for checking whether you have enough resources (for these spells mana) to cast the spell, it doesn't check the cooldown. There are separate checks for cooldowns.

**Comment by Bakamaka11** [comment]
> You misunderstood what spell useable is checking. It's for checking whether you have enough resources (for these spells mana) to cast the spell, it doesn't check the cooldown. There are separate checks for cooldowns.

So I was wrong, thinking that in the past the trigger was activated if the character was CCed? (because the spell was not usable)

If it only shows "whether you have enough resources" then how is it different from the "Insufficient Resources" condition?
