### ISSUE TITLE
[Spell: Action Usable] Option to ignore cooldown

### ISSUE THREAD

**Issue by ManagerWoW** [WeakAuras/WeakAuras2#5384]
Currently the [Spell: Action Usable](https://i.imgur.com/GeHiy1C.png) trigger only works if the spell is off cooldown. This is an issue when trying to make a weakaura to show when certain abilities are procced and usable, even when they are still on cooldown (Overpower, Victory Rush, etc). 

The in-game behavior of [IsUsableSpell ](https://wowpedia.fandom.com/wiki/API_IsUsableSpell )does work correctly; it will return true if the spell is usable, even when it is on cooldown.

Can an option be added to ignore the spell cooldown check for this trigger. There are a lot of custom wago auras made as workarounds for this missing feature, so it looks like others are running into the same issue.

Pictures showing IsUsableSpell behavior with Victory Rush:
[Not Procced](https://i.imgur.com/AW4r5fw.png)
[Procced off-CD](https://i.imgur.com/AIYHHlJ.png)
[Procced on-CD](https://i.imgur.com/qkj1vSg.png)

**Comment by emptyrivers** [comment]
I'm confused, why would you need custom code to work around this "missing feature"? Spell cooldown tracking is second only to buff tracking as a thing that WeakAuras does, to the point that the cooldown trigger is the default option when you select a spell trigger.

**Comment by emptyrivers** [comment]
It's not obvious to me that C_Spell.IsSpellUsable is incorrect in reporting that a spell that is on cooldown is still usable; the base UI uses this to distinguish actions which would be unusable even if they weren't on cooldown, and who are we to say that users wouldn't want the same functionality?

**Comment by ManagerWoW** [comment]
> I'm confused, why would you need custom code to work around this "missing feature"? Spell cooldown tracking is second only to buff tracking as a thing that WeakAuras does, to the point that the cooldown trigger is the default option when you select a spell trigger.

Sorry if my wording was poor. This request isn't about tracking spell cooldowns.

The summary of the issue is that the "Spell: Action Usable" trigger does not work when it's spell is on cooldown. I DO want it to work when it is on cooldown, so I can see when Victory Rush/Overpower are usable, regardless of their cooldown. This is how the default IsSpellUsable works. The easiest way would be for another option in the trigger to "Ignore spell cooldown", so it would not break the existing trigger functionality.
