### ISSUE TITLE
Some condition properties don't have a default value.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#539]
[Stack trace](https://pastebin.com/t22QW8WR)

WeakAuras Version 2.6.4 15c7caf53

To Reproduce:

- Option 1: Install [this aura](https://wago.io/HkiDY5L4m), and then cast any spell.
- Option 2: Create any aura with any trigger, then add a condition to modify a property, but don't edit the property. The issue is reproducible using (as far as I can tell) height, width, xOffset, and yOffset property changes.

Observations:

- In all cases, the UI appears to suggest a default value for the property. X and Y offsets look like they have a default value of 0, and height and width look like they have a default value of 1. But the value is non-existent within the data itself. Upon exporting, and then re-importing the aura, the UI now obviously reflects this fact.

Workaround:

- Remove the offending property, or edit it at least once to properly assign a value.

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
