### ISSUE TITLE
Manual Icon shows an empty dialog

### ISSUE THREAD

**Issue by tsteuwer** [WeakAuras/WeakAuras2#5393]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Selecting the manual icon button shows an empty dialog. Unable to select a manual icon.

### WeakAuras Version

WeakAuras 5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Go to "New Aura" or existing Icon aura
2. Click "Icon"
3. Click "Manual Icon"
4. Notice the dialog is empty

### Screenshots

![image](https://github.com/user-attachments/assets/0b8dcaa6-c8cb-4a9d-8009-d45b43f9c24e)

![image](https://github.com/user-attachments/assets/3c365bbb-f902-4930-a132-dcf6fb3ad018)

**Comment by InfusOnWoW** [comment]
you have to enter a search term in the top right, because there are too many icons.

**Comment by tsteuwer-accesso** [comment]
Oh, you guys removed the categories?

**Comment by mrbuds** [comment]
Icons never had categories, textures have them
