### ISSUE TITLE
PLEASE "view all displays" = view all loaded displays 

### ISSUE THREAD

**Issue by Warzau** [WeakAuras/WeakAuras2#5394]
**Is your feature request related to a problem? Please describe.**
old functionality changed for some strange reason, please change it back

**Describe the solution you'd like**
at the top Loaded/Standby > green icon > "View - Toggle the visibility of all loaded displays" needs to show ALL aura's, not some.   currently you need to go down the list of aura's, and click the green icon on every one to display all,  this is key in adjusting all their positions on the screen

**Describe alternatives you've considered**
you have to click down the list of displays to show ALL for positioning.  I have 24 aura's that load for positioning

**Additional context**
View all use to work, I submitted this as a bug, and was told, "some people" prefer view all only shows 2-3 and it was immediately closed without appeal.  the functionality was changed at some point, and it doesn't make sense...

**Comment by mrbuds** [comment]
Please don't resurrect old closed debates, this was discussed well enough.

**Comment by Warzau** [comment]
Is there a link to the discussion?  curious to see why "show all" wouldn't
show all?

btw I'm not a bum, I'm paying into curse forge to support devs.

**Comment by mrbuds** [comment]
This was answered in your previous ticket https://github.com/WeakAuras/WeakAuras2/issues/4888
