### ISSUE TITLE
Achored To Select Frame recursion causes interface crash.

### ISSUE THREAD

**Issue by Huijiro** [WeakAuras/WeakAuras2#5395]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

If you create two groups, and on the Position Settings, on Anchored To put Select Frame, and set a Frame 1 to be the Anchor, and on Frame 2, and on Frame 2 select Frame 1 to be the anchor, you will cause a recursion, this at the moment crashes the entire interface (And somehow WoW too).

### WeakAuras Version

5.17.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Create one Aura. (Aura 1)
2. Create one Aura. (Aura 2)
3. On Position Settings of Aura 1, on Anchored To, put Select Frame to Aura 2.
4. On Position Settings of Aura 2, on Anchored To, put Select Frame to Aura 1.

**Comment by InfusOnWoW** [comment]
!WA:2!Lsv3YnXrwyggiUyiHyjmEXecXHSqs5QcLXSWMI8hASLSfrwsmA8pqYUw9mtlnnE0mJ7Uh)Js2SXUsio36B5oDD2B0JGFcoLQ8e4lYdGFcs39mciqLTsv5Mz6(0N)pFNpTLZZMzo8M57K3lV3(x5iNiQhMAICx3JgfhpQzaPBxe1Bs7OOaojEakH7hrRfZjrHmd6o1A1IH5A9rHUc51JiHCNzlw1UOv)uFnBuqe9(AAA6uKRYQ7yX4ik3WPfjKW8nmf)4g7XPK2TXu2LUon74t65HDsA1YENymDHIvQxAPkMCXflucfnZESyCqqzpMXrSeh8M4qEdH2KT7V2SfAyVwd7cw2MjcN7ehG2btTcrDWmdlLQolGrbC)NzADkwyQvJ6fRu5GKWSuW4yrbHPHOGLfPMi7F6bmCqlvDcJygeH8kzYiDXJB1jr0GmSCdqm24WvnmfPNR8GdhficG84aNSoBAxrxxVU(0342oSOeQl2H0joIYTyUcd0Ds7F(9s)x0RnooxJnsqu8KLsccMCfFch3JIBlslzlYQnnkjot9gIC60hMEoDgDME8i3ntRIlQ9)6FvIx)cY(4KZlTRFlQO70GtrCK(XPJZssrsx70ywRIfRAHcI9r6zt2YHcVQptIWpDx6MU8ov7wYCbh3OWwK2g0TZGg9ec8iP4L(KWwr0oi5nJdqHK0J3bmkDigXKHhh2M7pcKZmmkepWtKGsnwto2PmS0xS9KQktl4EMDqKWsWNlmaUhuamHzf)p7lljV7u7pvpIW6gQo9Lpb8XcmR3JtyCS3IKWtcNwdEnyKbUcCUx0wHn2IeJBE4WRYUVVP0bnH34Cxho3tG3egveI8W5nGXGlaJd)n4TGldtaxcUOb82gX5K49nX2PiPfJ8W)8jGR80JxhJJlibhClzT5dVdmIaPZqCzXI97jGKwQPk7UJd5giUkHnYPBO3(JfNNJ3MVgZhjsSvZAYXtOeQ(K2HxJLDaU3bp7TREnw8OVG5pF58OuPdX2MfwYUw85vcfR8rY5K7kepUVzbX1JtdezBSNs4UdsbmpmlDou9US7sATJO6OrCrLzleAwTw1IqoQOOK60tPO7WTb9dYQGqE8OLOKUt(GeKNesoPT9VRWhgPbkzBjaKRqrX7Ts2H0eytcJ4eGBMvZVahvCUYvRw0AnZA221w0Q88lyp4zHwU7mrwfT6VloYxvSr1wYUs5Qf)1bTdI2QefVrco0DN6NA6BmZTtRo5dhMWWZhK1M93tksA9aNeopkSMyzuWl1tkUIc2FH(YZdlTdAp0uvR5q515Y2h0vAom5mLx8v63qXDOslBFI76Hygtx9sfI4Cov0mtzwC8XK2(8DHjlbVRKEc(7QVVN671KFJhvucfY2teBkOT9H3h(G4rFbcc1NJxbJwxsNWURIub(qOS1ZNR7nCrQ5rX0O2urwLUjo1LpXjHtza31aoJGgWaEDd4SgW)OFJIvkoRDjRclw0SBuuhT48Iuz2m3i2Melp4MWnZOYSsJ6D0HBPBTLctgp2WGkbEZryibwWZh(O(vE8sRp9)S89NE5nOKqjNi2)5SbOTpj8zskjfdIGiziTYCVIKZ(ks(ed4tFLUgj0F)PGIkwhO0qUgy(MWc(q5)0mkW9veiWxOOmGk(WIsccO6(Jb10G6IW)aXgoyP2OHgGnSeSmSYUWQAWdfw8i4lfQ)vW)sntG)nSg0udqGd42e8am0AcOTg4dKFfE8qWmSoe4dDGqi6cqSgSrQXuDGPbCFirh2uh2khiGg78)dlbDvyh4RHVrIoG)tQJ(2MW)9pcfaFhSRgS3lnMVz6yg((DHFqoolFR6TEuCJq)z2g(rFy))QJp4N8ZV5VS6Vb


Can you clarify what exactly you have?

**Comment by InfusOnWoW** [comment]
I can now reproduce this now.
