### ISSUE TITLE
Trigger if health is less than x after y amount of time

### ISSUE THREAD

**Issue by Git-BCA** [WeakAuras/WeakAuras2#5396]
Sometimes in a raid many healers have addons to color the name plate of the lowest hp in red and thus that character is healed immediately but also will be overhealed by other healers that cast the healing spell at the same time and consequently they waste that ability and have to wait for global cooldown time before they can heal other players with lower health.

One solution I suggest is having a timely trigger in "Player/Unit Info -> Health". For example if a character with low health is not healed after let's say 1 second the color of the name plate will change to red and consequently will be healed because other healers will focus on healing the lowest hp.

I know this kind of scenario is dangerous sometimes like in a situation when the most critically damaged character is not healed on time, but this feature may help in other situations if used wisely.

Kind regards,

**Comment by InfusOnWoW** [comment]
That kind of feature is best handled by custom code, and certainly not as a built-in option in the health trigger.
