### ISSUE TITLE
Error on log-in: cannot resume dead coroutine

### ISSUE THREAD

**Issue by Tequima** [WeakAuras/WeakAuras2#5398]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Got a never-ending error on log-in to one character in Dornegal:

```
501x cannot resume dead coroutine
[string "=[C]"]: in function `error'
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:53: in function `Assert'
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:200: in function `Create'
[string "@WeakAuras/ArchiveTypes/Repository.lua"]:27: in function `Set'
[string "@WeakAuras/ArchiveTypes/Repository.lua"]:68: in function `Set'
[string "@WeakAuras/History.lua"]:71: in function `SetMigrationSnapshot'
[string "@WeakAuras/WeakAuras.lua"]:2628: in function <WeakAuras/WeakAuras.lua:2625>

[string "@WeakAuras/WeakAuras.lua"]:4455: in function <WeakAuras/WeakAuras.lua:4452>

Locals:
start = 822019105.084500
threads = <table> {
 pools = <table> {
 }
 frame = Frame {
 }
 prios = <table> {
 }
 size = 1
}
```
I did a /reload and getting one error:
`4x WeakAuras/Libs/Archivist/Archivist.xml:5 Error loading WeakAuras/stores/RawData.lua`

I currently only have 2 weak auras installed: 

- Myu's Knowledge Points Tracker https://wago.io/L7lpDrqUO last updated 2 September
- Dragon Riding Speed Gauge v2 https://wago.io/Afdc0wSAr 9 August

Looking at Options, I may not have the addon installed on the first character I logged into this morning.

I didn't test (yet) with only weak auras enabled as I have to go out shortly. Will test on return.

### WeakAuras Version

Weak Auras 5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
501x cannot resume dead coroutine
[string "=[C]"]: in function `error'
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:53: in function `Assert'
[string "@WeakAuras/Libs/Archivist/Archivist.lua"]:200: in function `Create'
[string "@WeakAuras/ArchiveTypes/Repository.lua"]:27: in function `Set'
[string "@WeakAuras/ArchiveTypes/Repository.lua"]:68: in function `Set'
[string "@WeakAuras/History.lua"]:71: in function `SetMigrationSnapshot'
[string "@WeakAuras/WeakAuras.lua"]:2628: in function <WeakAuras/WeakAuras.lua:2625>

[string "@WeakAuras/WeakAuras.lua"]:4455: in function <WeakAuras/WeakAuras.lua:4452>

Locals:
start = 822019105.084500
threads = <table> {
 pools = <table> {
 }
 frame = Frame {
 }
 prios = <table> {
 }
 size = 1
}
```

### Reproduction Steps

1 Log in

### Last Good Version

Weak Auras previous version (I update daily via Wago app)

**Comment by emptyrivers** [comment]
This is likely a combination of [this behavior from blizzard](https://github.com/Stanzilla/WoWUIBugs/issues/423), and your addon manager fumbling the update process. So, it should be an ephemeral problem, try reinstalling WeakAuras and see if the issue persists.

**Comment by emptyrivers** [comment]
no response from user, and given the symptoms i'm fairly confident this is a broken install, so i'm closing this.
