### ISSUE TITLE
Permanent Auras Sorting "Correctly"

### ISSUE THREAD

**Issue by Loloup** [WeakAuras/WeakAuras2#5399]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated  when I'm trying to sort auras either in descending or ascending when there's permanent auras in the mix. The game counts permanent auras as having a duration of zero which makes the sorting inconsistent. Sorting buffs by ascending would put the permanent buffs at the very beginning when they should be at the very end.

**Describe the solution you'd like**

Change permanent auras to have a value of inf instead of 0.

**Describe alternatives you've considered**

I've managed to go around this problem by making a separate aura that only tracks permanent auras and combining it with a hybrid sort.

**Comment by emptyrivers** [comment]
eh, what's wrong with a custom sort for this? it's not obvious to me that an aura with no duration actually should be considered "infinite" duration by default (for one thing, the underlying data claims the aura to have zero duration)

**Comment by InfusOnWoW** [comment]
They have an "undefined" duration, e.g. there's a buff to standing in your consecration, which has no duration. 

So any sorting is imho fine and thus this isn't a bug and we do have a way to change the sorting, via a custom sort.
