### ISSUE TITLE
Item Not on CD Trigger shows on infinite duration cd

### ISSUE THREAD

**Issue by Rhkqt** [WeakAuras/WeakAuras2#540]
Describe the bug
Trigger Cooldown Progress (Item) - Not on CD will show if you have an item that has an infinite duration in combat e.g Potion, Healthstones

To Reproduce
Make trigger = status - cooldown progress (item) - Potion of Prolonged Power - show = not on CD
Get in to combat and use a potion.
Aura will pop up until it starts it cooldown when you leave combat

**Comment by InfusOnWoW** [comment]
Should be fixed in the next release.
