### ISSUE TITLE
Passive Talent doesn't work for "spell known" load option when not using spellID

### ISSUE THREAD

**Issue by CrystalBearer** [WeakAuras/WeakAuras2#5405]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

In the "Load" tab, in order to enter a spell known, one must use the SpellID, as it does not seem to validate spell names of passive spells.

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Go to any aura.
Select "Load"
Attempt to add a passive spell by name as conditional.

### Last Good Version

n/a

**Comment by InfusOnWoW** [comment]
Hero Talents can and are different per spec. so that does not work.

Usually the Spell Known load option is the better choice anyway.

**Comment by CrystalBearer** [comment]
> Hero Talents can and are different per spec. so that does not work.
Then, if you have multiple 'specs' chosen, could you have the hero talent options from each of them appear separately for OR selection?

> Usually the Spell Known load option is the better choice anyway.
"Spell Known" doesn't work if there is no spell. For example, using a WA to track the stacks of Bloodseeker Vines on a target can't do this because it's a proc from a passive talent. And you can't use "Spell Known" with the passive.

**Comment by mrbuds** [comment]
> And you can't use "Spell Known" with the passive.

yes you can

**Comment by CrystalBearer** [comment]
> yes you can

Ok. I'm trying it actively as we're talking. I must be missing how since I use this all the time on other auras and have never gotten it to validate on passives. In this case, the passive is "Thriving Growth". It's not validating for me.

**Comment by mrbuds** [comment]
https://github.com/user-attachments/assets/6b26a8d1-163d-4f92-9575-c35f24e0a675

**Comment by CrystalBearer** [comment]
So, unlike active spells, you can add them, but only by SpellID? I mean, that's fine, so long as I know that's what I have to do.

**Comment by CrystalBearer** [comment]
Plus... I will have to figure out how to get that on my tooltip or I'll be on WoWhead constantly....

**Comment by mrbuds** [comment]
Get IdTip addon

**Comment by CrystalBearer** [comment]
Thanks. Will do. Sorry I needed a video for that; I appreciate the time.

I suppose I would flex this, then, to attempt validation for passive spells as well by name, if possible.

**Comment by mrbuds** [comment]
I couldn't use the name for passive spell as spell known, i reopen ticket for this

**Comment by CrystalBearer** [comment]
> I couldn't use the name for passive spell as spell known, i reopen ticket for this

Sounds good; thanks. I updated the main post to match this request for easier reference.
