### ISSUE TITLE
Aura Trigger Based on Icon ID

### ISSUE THREAD

**Issue by kensylvia** [WeakAuras/WeakAuras2#5411]
**Is your feature request related to a problem? Please describe.**
I have an aura that reminds me to eat buff food between pulls/before keys.  In order for it to know if I have a Well Fed buff and assess its cooldown, it has an Aura trigger.  There are 407 "Well Fed" buffs and another 32 "Hearty Well Fed" buffs.  In order for the aura to work on different language clients, the Aura buff must be coded by spell ID and not spell name.  But having the aura check for 439 different buffs by spell ID is both extremely inefficient and a major pain to physically do.  Every single one of those buffs uses the icon ID 133943, however.  If the default Aura trigger let me look for auras with that icon ID, this would be a much easier check and would work on all language clients.

**Describe the solution you'd like**
Add a checkbox option in the Aura trigger to check for Auras with specified iconIDs. 

**Describe alternatives you've considered**
The alternative I am currently using is adding all the most relevant spellIDs and also using "Well Fed" spell name as a fallback for enUS clients.  This is far from optimal, obviously, and it is also must less efficient because it's checking for so many different buffs, even though they are all of the same category.

Another solution to this issue, which would also be a feature request, would be WeakAuras to automagically save spell name aura triggers by the list of spell IDs. The addon knows and displays the list of spell IDs, but it assesses the words on different clients, which doesn't work for obvious reasons. If I could click a button and have it assign all of the spell IDs that are found with the spell name I type in for my client, so that in other clients the spell ID list is used, that would allow for massively easier localization.  This would be useful for many things, but for the specific use case I noted, I think the icon ID would be quite a lot more efficient.  But overall, I'd love to have both options--it would make coding triggers for category based things much easier.

Another option, which would also be generally useful but less than optimal for this specific problem, would be the ability to import a comma delimited list of IDs for things. Having to manually type in each box is a pain whenever there is a list of items, which is something I come across regularly. Having the addon parse a list would be wonderful, but having this aura check for 439 different buffs will never be the most efficient way to do this.

Another option would be to just write this in code, but the issue there is passing text replacements for a timer becomes much harder and requires (as best as I can tell) a custom text function with an throttle, which is more resource intensive than I'd want to have it be.

**Additional context**
![image](https://github.com/user-attachments/assets/976168d5-fa3a-4953-9455-63044ada001f)
 Here you can see the enormous list of responsive spell IDs for the spell name "Well Fed," nearly all of which use the same icon.

**Comment by mrbuds** [comment]
You can type a spellid in name field

**Comment by InfusOnWoW** [comment]
There aren't 439 relevant Well Fed buffs, and adding all of them would be pretty pointless too.

The number of spell ids included in an aura makes no difference in performance.

**Comment by emptyrivers** [comment]
> You can type a spellid in name field

In case it wasn't clear, if you write a spell id into the name field, but *don't* tick the exact spell id option, the trigger will match any aura which has a name which is the same as the spell you entered.

**Comment by emptyrivers** [comment]
we could theoretically support "well fed" buff type in the same way we support "bleed" debuff type. if someone would be willing to do the grunt work of keeping the spell list up to date, that could be a neat feature 🙏

bonus points for "ineligible for bloodlust" type debuff

**Comment by SpatenLa** [comment]
"well fed" buffs are called well fed buffs because they are all namend well fed. even the earthern permanent buff is called well fed.
