### ISSUE TITLE
Cell Spotlight request to be added to higher prior in LibGetFrame

### ISSUE THREAD

**Issue by mrgrimms** [WeakAuras/WeakAuras2#5412]
**Is your feature request related to a problem? Please describe.**
Some augmentation weakauras are focused on sending glows to the spotlight frame, but since it's not apart of the lua it won't default to them. So you need to add it manually.

**Describe the solution you'd like**
With Cell becoming more popular going into the war within, any chance of adding 
"^Cell-Spotlight", -- Cell Spotlight 

to the  first line in "local defaultFramePriorities = {..."  in LibGetFrame-1.0.lua file

**Describe alternatives you've considered**
Just have been adding this manually to the lib

**Additional context**
For reference, an example weakaura that uses this function is the following https://wago.io/mo8kN0U36 but it will default to elvui, cell or vuhdo frames but for some that use the spotlight frames, it will not see those.

**Comment by InfusOnWoW** [comment]
What's the difference between Cell-Spotlight and Cell ?

**Comment by mrgrimms** [comment]
Cell would be equal to elvui party/raid frames, but cell-spotlight would be equal to say vudhu private tank frames. They are custom frames that you can set one person or multiple people from your raid frames to be a focus (more for augmentation evokers to pick specific people to buff).

**Comment by mrgrimms** [comment]
I'm told recently that this would be more for the libgetframe that I need to open a pull, which I did try but it said I was not a collaborator so I must have done something wrong.

**Comment by mrbuds** [comment]
Cell addon has options to override priorities in libgetframe

**Comment by mrbuds** [comment]
![image](https://github.com/user-attachments/assets/34d04ba0-1bb1-4209-9c58-df7722a5f939)

**Comment by mrgrimms** [comment]
oh cool, so would you just check both, or just the spotlight to make it overridden?

**Comment by mrbuds** [comment]
That's a question for Cell's support

**Comment by mrgrimms** [comment]
Ok thank you buds as always :)
