### ISSUE TITLE
glow when the spell is activated does not work

### ISSUE THREAD

**Issue by tritognait** [WeakAuras/WeakAuras2#5413]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

My demon hunter has spells that glow when activated, I made a simple indication with a texture display if the glow appears. But the trigger does not work on any spell. 
For example, there is a spell "blow of chaos" when glowing, it changes its name to "Annihilation". I tried to write both of these names in the trigger, but none of them worked.
I've tried the same with other spells

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1.created a trigger glow when the spell is activated
2.I'm waiting for the spell to start glowing
3.The spell is glowing
4.Trigger not work

**Comment by InfusOnWoW** [comment]
It's hard to tell what exactly you created, but it's most likely that you are using the wrong trigger. The discord is probably a better place to figure out what exactly you want and which trigger is the right one for that.,
