### ISSUE TITLE
Support new action: vibrate controller

### ISSUE THREAD

**Issue by LeoQuote** [WeakAuras/WeakAuras2#5414]
**Is your feature request related to a problem? Please describe.**
Recently, I've been trying to play WoW with a game controller. I think it would be great if the controller could vibrate when casting certain powerful spells or during critical hits. After doing some research, I found that the API supports this feature and it can be achieved through Lua scripting. Additionally, in WA2, this functionality can be implemented through custom actions. However, I believe that if WA2's UI could directly incorporate this action, it would make the creation process much easier. This way, controller players could use the vibration feature to gain more immersion in the game.

**Describe the solution you'd like**
Add a new action, didn’t look at the code but I think it’s feasible.
**Describe alternatives you've considered**

**Additional context**

**Comment by InfusOnWoW** [comment]
That sounds too niche for a general option, meaning custom lua code is exactly the right support for that.

**Comment by LeoQuote** [comment]
😁ok thanks for your quick response though.
