### ISSUE TITLE
Hero spec

### ISSUE THREAD

**Issue by Addonman** [WeakAuras/WeakAuras2#5422]
Can you add option to triggers and perhaps somewhere else to show something not only for spec but what branch of hero talents you took? For instance i have WA for stats but they are diff depending what hero spec i chose.

**Comment by InfusOnWoW** [comment]
There is already a hero talent option, you need to select class/spec for it.

Or you can use the spell know option for that.

**Comment by Addonman** [comment]
I can see now that Load section has hero talent selection . Would it be possible to add something (maybe hero talent tree)  into trigger section  like that since it stops at spec?

**Comment by InfusOnWoW** [comment]
There also is a trigger.
