### ISSUE TITLE
Add "or hero talent" load condition

### ISSUE THREAD

**Issue by Gnarfoz** [WeakAuras/WeakAuras2#5423]
**Is your feature request related to a problem? Please describe.**
I'm trying to make an aura that reminds me to use the new Paladin hero talent weapon enchant.
I want it to load if I've taken either of the two options (choice node).

**Describe the solution you'd like**
The load condition "talent" offers a "or talent" option once "talent" has been selected.
I think a "or hero talent" option that appears once "hero talent" has been selected would be great.

**Describe alternatives you've considered**
"Spell known", but since all the load conditions are AND'ed, not OR'ed, that doesn't really work.

**Additional context**
The paladin talents in question:
https://www.wowhead.com/spell=433568/rite-of-sanctification
https://www.wowhead.com/spell=433583/rite-of-adjuration

**Comment by InfusOnWoW** [comment]
I don't think that's a compelling enough reason to add multiple hero talent load options. You can easily check whether the player has that hero talent **tree** selected, and assume that they have one of the choice nodes.

**Comment by Gnarfoz** [comment]
Excellent point. I didn't realize that was an option. 👍
