### ISSUE TITLE
Lua error in aura 'MKPT_Cells': Trigger 1

### ISSUE THREAD

**Issue by lordsnugglez** [WeakAuras/WeakAuras2#5425]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Message: Lua error in aura 'MKPT_Cells': Trigger 1
WeakAuras Version: 5.17.1
Aura Version: 1.2.0
Stack trace:
[string "return function() if not MKPTFrame then"]:310: bad argument #1 to 'GetMapInfo' (Usage: local info = C_Map.GetMapInfo(uiMapID))
Time: Thu Sep 19 11:45:16 2024
Count: 2
Stack: Lua error in aura 'MKPT_Cells': Trigger 1
WeakAuras Version: 5.17.1
Aura Version: 1.2.0
Stack trace:
[string "return function() if not MKPTFrame then"]:310: bad argument #1 to 'GetMapInfo' (Usage: local info = C_Map.GetMapInfo(uiMapID))
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1847: in function `ScanForLoads'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1925: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1921>

Locals: toCheck = nil
event = "ZONE_CHANGED"
arg1 = nil
WeakAuras = <table> {
 normalWidth = 1.300000
 StopMotion = <table> {
 }
 raidUnits = <table> {
 }
 buildType = "release"
 EJIcons = <table> {
 }
 defaultFont = "Friz Quadrata TT"
 HiddenFrames = WeakAurasHiddenFrames {
 }
 partyUnits = <table> {
 }
 versionString = "5.17.1"
 newFeatureString = ""
 class_types = <table> {
 }
 L = <table> {
 }
 doubleWidth = 2.600000
 buildTime = "20240908210358"
 raidpetUnits = <table> {
 }
 class_ids = <table> {
 }
 spellCache = <table> {
 }
 GrowFunctions = <table> {
 }
 SortFunctions = <table> {
 }
 petUnitToUnit = <table> {
 }
 spec_types_specific = <table> {
 }
 genericTriggerTypes = <table> {
 }
 partypetUnits = <table> {
 }
 timer = <table> {
 }
 halfWidth = 0.650000
 BuildInfo = 110002
 item_weapon_types = <table> {
 }
 race_types = <table> {
 }
 defaultFontSize = 12
 unitToPetUnit = <table> {
 }
}

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
Message: Lua error in aura 'MKPT_Cells': Trigger 1
WeakAuras Version: 5.17.1
Aura Version: 1.2.0
Stack trace:
[string "return function() if not MKPTFrame then"]:310: bad argument #1 to 'GetMapInfo' (Usage: local info = C_Map.GetMapInfo(uiMapID))
Time: Thu Sep 19 11:45:16 2024
Count: 2
Stack: Lua error in aura 'MKPT_Cells': Trigger 1
WeakAuras Version: 5.17.1
Aura Version: 1.2.0
Stack trace:
[string "return function() if not MKPTFrame then"]:310: bad argument #1 to 'GetMapInfo' (Usage: local info = C_Map.GetMapInfo(uiMapID))
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1847: in function `ScanForLoads'
[string "@Interface/AddOns/WeakAuras/WeakAuras.lua"]:1925: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:1921>

Locals: toCheck = nil
event = "ZONE_CHANGED"
arg1 = nil
WeakAuras = <table> {
 normalWidth = 1.300000
 StopMotion = <table> {
 }
 raidUnits = <table> {
 }
 buildType = "release"
 EJIcons = <table> {
 }
 defaultFont = "Friz Quadrata TT"
 HiddenFrames = WeakAurasHiddenFrames {
 }
 partyUnits = <table> {
 }
 versionString = "5.17.1"
 newFeatureString = ""
 class_types = <table> {
 }
 L = <table> {
 }
 doubleWidth = 2.600000
 buildTime = "20240908210358"
 raidpetUnits = <table> {
 }
 class_ids = <table> {
 }
 spellCache = <table> {
 }
 GrowFunctions = <table> {
 }
 SortFunctions = <table> {
 }
 petUnitToUnit = <table> {
 }
 spec_types_specific = <table> {
 }
 genericTriggerTypes = <table> {
 }
 partypetUnits = <table> {
 }
 timer = <table> {
 }
 halfWidth = 0.650000
 BuildInfo = 110002
 item_weapon_types = <table> {
 }
 race_types = <table> {
 }
 defaultFontSize = 12
 unitToPetUnit = <table> {
 }
}
```

### Reproduction Steps

N/A

### Last Good Version

5.17.0

**Comment by mrbuds** [comment]
This is not a bug in the addon but on one of the auras you installed.
