### ISSUE TITLE
Certain skills do not work only on certain characters

### ISSUE THREAD

**Issue by gmlakffkdis** [WeakAuras/WeakAuras2#5426]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

SOD
The warlock's skill "Ghost Haunt (ID 403501)" does not activate.
I've done all the basic things like installing new add-ons.
It works normally with a newly created character on the same account, but it does not work with an existing character.

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1

**Comment by InfusOnWoW** [comment]
Your reproduction steps and description is not enough to discern what exactly you are trying to do.

**Comment by InfusOnWoW** [comment]
We are waiting for you to provide more information.
