### ISSUE TITLE
Instance Size Type Broken Era/SoD

### ISSUE THREAD

**Issue by danjohnso** [WeakAuras/WeakAuras2#5427]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The Instance Size Type trigger and load options do not appear to be working in SoD.  I have tried both dungeons and Molten Core, but using these options does not work.
![image](https://github.com/user-attachments/assets/e15da3f0-3781-484b-90be-b08d74a8eb97)

I also tried using the single selection option of a 20 man / flex for molten core and I tried 5 man option for BRD, neither of those worked.

I made sure my trigger was not messed up by changing it from Instance Size Type to a location id (Molten Core), and that works as expected.
![image](https://github.com/user-attachments/assets/32b87455-5574-4c81-a295-bf4c31e2eb54)

### WeakAuras Version

WeakAuras 5.17.1

### World of Warcraft Flavor

Classic Era

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1) Create Weak Aura
2) Set Load condition, or create a Trigger, to load on Location > Instance Size Type
3) Use single size (ie 20 man) or multiple sizes (ie Flex, 40 man, 5 man dungeon, 10 man, 20 man 25 man)
3) Enter dungeon or raid and weak aura is not loaded

**Comment by mrbuds** [comment]
It is fixed already for Molten Core and Onyxia

Could you help by giving result of the following command while in BRD or somewhere else you found it not working?

```
/dump GetInstanceInfo()
```
