### ISSUE TITLE
Color Picker not always displaying and then is behind another checkbox

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#543]
**Describe the bug**
Icon (cooldown?) auras do not have a color picker in the display.  After clicking to another aura that has one, it shows up behind the "Show Cooldown Text" checkbox.

**To Reproduce**
1. Open WA
2. Choose an icon aura with Cooldown checked
3. Switch to an icon aura that does not have Cooldown checked
4. Go back to the Cooldown one

**Expected behavior**
Expect to see color picker separate.

**Screenshots**
![image](https://user-images.githubusercontent.com/3958649/43296026-accf60f0-90fd-11e8-9f6d-c40f3dce74a1.png)
![](https://cdn.discordapp.com/attachments/273144328447197186/472202269077536768/unknown.png)

**Which version of WeakAuras are you using?**
2.6.4

**Was it working in a previous version? If yes, which was the last good one?**
Tried back to 2.6.0 and still happening.

**Additional context**
Noticed with these auras (but see it with others too): https://wago.io/AmiYuy-Hunter-BMAbilities

Aura that switching to makes the color picker box show up: https://wago.io/EJiAe2uy7

**Comment by InfusOnWoW** [comment]
This has been fixed upstream and the next release will contain that fix.
