### ISSUE TITLE
aura_env.states has a nil entry for an active cloned trigger if dynamic information comes from another trigger

### ISSUE THREAD

**Issue by calummitchell** [WeakAuras/WeakAuras2#5434]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I expect aura_env.states to have a non-nil entry for each active trigger. Instead if one of the active triggers uses the Clone per Event option it's aura_env.states entry is nil if dynamic information comes from another trigger.

### WeakAuras Version

WeakAuras 5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

The example I provided which reproduces the problem has:
Triggers
All triggers are required for activation
Dynamic information from trigger 1
1 Always active trigger
2 Combat Log cast start Hearthstone with [x] Clone per event
Conditions
1 Set text color to red if trigger 2 is active
Actions
On Show custom action adds aura_env to DevTool

While casting Hearthstone the text is shown in white but it should be red. Triggers 1 and 2 are both active but Condition 1 thinks trigger 2 is not. Looking at aura_env in DevTool also shows aura_env.states[2] is nil.

If you make any of the following changes this problem goes away:
Remove Clone per event option from Trigger 2
Get Dynamic information from Trigger 2
Get Dynamic information from first active trigger and swap the positions of triggers 1 and 2

### Export String

```Text
!WA:2!9zvZUTXTw4ijCXTvOlAfcsBtZcvxuJe0aJANuxeh0cijlHyhfBJrkXPagDeNHuImEgscsoYwzvHqw01ABl6cTVB0I(aKNacJ(e4f5bWpb9Wzgj3giBVW4qohE()77OcTQexbxb)R7i)smtlJqJ6so143xOIrgFJqezyY8J15cozkluW7isuHK7CJZqjgQqTV0WeCDz53SeBi9nSyIpEehfZc9nufrtfr4cQr73VVMyWF4mepemZbcg3e0O5EDB6jRE1Mk7uHnsurfR7cNEYvUATJfyFfYq6DXXeISMwscnEiiGPJprOWhQqYXhMlmft0itItD6yLW4uJxOEFb3mT5PsiY1NGgTuVT(AOyrcF(zBX6rceEO61qnBhSU4KenXNtgsu0adkIWn3YlobQULN5(sUA06U47w2pVSxyesRDs11SxtCcxya)LOiUi9zcmrEZgTR9Sd6UF921A80ABV9oD35fnpttryXjVmR4wAQImasIUJKK6U3pja8n29CV6TBU32QCJk3ChUHO6JcjhvdJH25rhsqhxdkg6JoqCcrLk(mcMHok7w3)Fq9xleXfMAeHqQPbp9zf(ZzEOijfvAJegE2M0MhVUYB3hkPYVAjfUnwlgkRObKfvUP9zNsWhYWg6B(iLiXeX4e1(pVB7D2RPxOisO2Te830WeTre7mwXL2tYhFxFHLLF9s7CqnpkApu8LHWzHWtHQiVZjmjPN8JV0vpxIHXdpOtYnVDUAnXdGjgJInyauf(Jvv5IVRUXv4t4mJSIRpJc0cvWtiOixlO356KGul1jPpK1Z8BuRtx)oDR5198lvpvv7MtBi4ywkuZdateD5jiOfKjUWshOiGL86CqZ2ThNMzWCvz7JdC5nrn2zwx80tbsUKMM5PiyYwBujKEakiach3iJ6jnBFqRN3EcmzNLrLx1(O3z3AsOioazIedu5(OS9hS)4ySd8aryLhKgVoDQ2wmW(yBl7U2NEMZvlk39SnlBBy32wldeKBjA6HWOuirVjlu)2ZG6MYqHobNyBxEg0mFvcp0Wgs2affjRK3LYIuWTSWIYpbLQq(LUszj5xSu6ImbphRbwU6vZOergGch53psiu0jiolonL30tBGWR1BjinPJrr4dm0)VDlyAAEvX3nnO0eGZcRh70ZvKbUIyeJ3Y6NQTTNfzdSfd6Z4mn99VEk0O9sX06BFl7wNbhdqHhpaakCCaLWgqnJcsjVilhXLpWVdEX4(yhdxhGMzK60mEJcJNpAtdIzkfKPxb699Tvo)ZpLzN7CJZHDecxfkmfrxVgCmaka9zdkFDO2hEjQ9A06bl0Y7eN5hT0OmVXbe4HmhhvPz)lLKv6sz6QWsPKiC1asvfbRCdnqfEt7p)xNpNFkB6ALYLF78BCTZn62TZuSWp)oQkxaM8wOMr7puWcjLcYSH8(Btg2fYGTaQ2Trg0DDazFcF49RUYCXQ3fcPtU3k3BmyDTR7sLF6)LR0pCr6pbukZ49MMQSVezOf9sLvvZ(uDyIYSQ9nu7Vu0IBzhNk8g6u4JYCFCbZThGJIErgF(VT0Fzq(m0LUxtI6NUa3(bRWWtB4qVv7s0z8EnYhMa4NNBx8S(kaqdGei3lDr26)wURC4HGon8A2CVRRTVXchREfKzS(JGLzTamo3TfcM7xgc)YI1SSz0gPRskuOaSkzb16Tx1lKscpEt7J(FJhIumeSXSURv4nefLqkPcPi(acOO933Te84XsLaG1Mr2VDgJN5dWsRodedjnDKYA6yhP6aGtIkV5COLl42MPDoatROd(U1w)7xB9kd)7x(pd
```

**Comment by InfusOnWoW** [comment]
That's entirely expected. The dynamic information chooses which trigger provides the clone id selection, and other triggers's states are matched to that. If another trigger does not provide information with the same state id, then there's no information.
