### ISSUE TITLE
typing in the wrong spell id feels bad

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#5435]
**Is your feature request related to a problem? Please describe.**
If i make a typo when inputting a spell id into various fields, then the field just goes blank if the value WeakAuras gets doesn't correspond to a spell it knows. It would be nice if instead WeakAuras showed something like `123456 (|cffffff00Unknown Spell|r)`, so I at least get confirmation that the input was accepted, even if it was nonsense.

**Comment by InfusOnWoW** [comment]
I don't see a way on how to implement that though, that is without storing the invalid spell id into the aura.

**Comment by emptyrivers** [comment]
well yeah, that's what I thought WA did if you gave it garbage. But on closer look, no I'm just being silly.

Still, though, maybe WeakAuras *should* just complain but still accept garbage. Like, isn't this exactly the scenario WeakAuras finds itself in if you imported an aura meant for TWW into SoD?

**Comment by emptyrivers** [comment]
i think aceconfig accepts validate field on the option table? that produces a static popup IIRC. maybe that would be "good enough".

**Comment by InfusOnWoW** [comment]
yeah if it's a number we can store it easily. I wouldn't store arbitary string though.
