### ISSUE TITLE
Missing Buff

### ISSUE THREAD

**Issue by Tuskkar** [WeakAuras/WeakAuras2#5440]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Missin Buff from Mistweaver monk (healer) "Strenght of the black ox" is a new talent from 70 to 80. Weak Auran do not recognize that talent's name

### WeakAuras Version

WeakAuras 5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

clic new aura, then trigger, select name, type talent's name

**Comment by InfusOnWoW** [comment]
<img width="941" alt="ZwmKXa2CBa" src="https://github.com/user-attachments/assets/9252ed5b-be93-4265-8032-6930ceecbc06">

That name is recognized.
