### ISSUE TITLE
'is offline' checkbox in Player/unit info > Unit Characteristics trigger

### ISSUE THREAD

**Issue by Bartholomau** [WeakAuras/WeakAuras2#5442]
**Is your feature request related to a problem? Please describe.**
I have troubles making weakaura that checks if player is offline and displays the name, wow ui is really delayed when it comes to checking for offline and it always slows down my raids, it marks player as offline after few minutes and sometimes shows hp bar for few minutes still instead of grey color + offline text.

**Describe the solution you'd like**
Add 'is Offline' checkbox in Player/unit info > Unit Characteristics

**Describe alternatives you've considered**
Haven't found a trigger combination that would give me the ability to check for offlines yet, while some triggers have a setting called 'Ignore disconnected' so i believe there would maybe be a way to add 'is offline' in condition trigger to reverse the logic and check if someone is offline, since there is already a feature to ignore disconnected (offline) people.

**Additional context**
-

**Comment by InfusOnWoW** [comment]
What makes you think that the WeakAura could be faster in detecting that a player is offline?

**Comment by Bartholomau** [comment]
I dont think it would be faster, might aswell be my weird way of explaining the issue but to answer your question:
I think weakaura would **SIMPLIFY** checking if someone is Offline with no delay to how wow handles it because - while the issues displaying offline people in blizzard ui exists, it is still **KNOWN** the person is offline when you hover over the person and look at the tooltip, it says 'offline' even while the bug exists and it contains the information.
Also there is a setting to check for almost everything rn including: AFK, DND, not disconnected, dead etc. - just a lot of player states, i think it would be useful to also have 'is offline'
Hope it all makes sense

**Comment by InfusOnWoW** [comment]
I've decided against adding that option to the Unit Characterstics trigger.

The trigger already has a "Ignore disconnected" option, similar to other unit triggers. The "Offline option" would logically replace that option, but that makes the trigger different from the other triggers. That is something I would like to avoid.

On the other hand, the benefit of that option is just to work-around a bug in the default unit frames, which isn't really a strong use case at all. The bug should be reported to blizzard.
