### ISSUE TITLE
Modify 'Item' trigger/s

### ISSUE THREAD

**Issue by Bartholomau** [WeakAuras/WeakAuras2#5443]
I was making a weakaura that works under two conditions:
1. Item slot is equipped
2. Item is enchanted

I ran into multiple problems making it and some of the basic ideas for weakauras using these triggers aren't possible to make with a simple method and using just one or two triggers together. I think the idea i am trying to make into weakaura is what it was made for and it's hard to achieve with current state of those triggers.

**What i am doing and the issue in depth:**
Weakaura that shows an icon WHEN Item slot is equipped MAIN HAND
- so it needs a trigger 'Item slot equipped [Main Hand]'
**Issue:** Trigger 'Item>Item Type equipped' - has hard coded and grayed out field 'Item type' so just checking for 'Equipment Slot' which also is contained in this trigger is not possible and to make a weakaura that shows if 'ANY' item in Equipment Slot 'Main Hand' is equipped, you have to make 12 copy triggers that check for every single Item Type, because the field is grayed out and required for it to work.

**Solutions**

**First Solution**
Separate these two settings into two different triggers
1. Item Slot Equipped
2. Item Type Equipped

**Second Solution** (better in my opinion)
Make one powerful trigger called 'Item (idk yet)' with all the settings ('equipped', 'slot', 'type', 'enchant') or merge literally all of the features of 'ITEM' trigger into one with no grayed out slots making any idea possible to achieve with less effort.

**Third Solution**
Modify trigger 'Item>Item type equipped' so it doesn't have grayed out field checked by default 'Item Type' and give us the choice to check that box, while clicking on it 2nd time gives the ability to choose multiple item types (ex. sword, dagger) because there is one more annoying issue/thing while using these triggers - when trying to check if item is 1. equipped 2. enchanted, you also need to specify ALL of the classes and specializations to make it works correctly because for example mages can't enchant OFF-HAND

**Just an idea**
Could be useful to have a checkbox for 'is enchantable' then you could just use 'Equipment Slot: Main Hand' + '[v] Is enchantable'

**Right now there is a lot of weakauras on wago.io that shows consumables so people are ready for the PVE content and almost every of them uses custom code, which in my opinion shows an issue with these triggers listed above, it should be simplified for others and also for hardcore weakaura creators, auras tracking buffs/enchants etc for PVE are super popular**

My explanations might be a bit confusing, i am not an expert, but i have reached out in help channel on discord and people also adviced me to open a feature suggenstion to at least add 'multiple choice' window for Item types

**Comment by InfusOnWoW** [comment]
Checking for enchant requires custom code, because it's a niche use case. What you wrote doesn't convince me otherwise.

**Comment by Bartholomau** [comment]
Im confused, i wrote an entire essay about 'Equipment slot' checkbox which is set to 'ON' by default and you answered about checking for the enchant while the 'Item Enchanted' trigger works perfectly fine for me and i don't use any code. It is literally not the issue i described. How is it niche too? Almost every PVE'r uses weakaura to track consumables, including oils, rouge sharpens, etc. Thats a whole separate topic about the enchants.

**Comment by emptyrivers** [comment]
A greyed out checkbox that you can't disable is an artifact of UI design, it doesn't imply that the underlying code is set up to support that "checkbox" being "disabled".

So, what would you expect the trigger to track if you could disable it?

**Comment by emptyrivers** [comment]
> Right now there is a lot of weakauras on wago.io that shows consumables so people are ready for the PVE content and almost every of them uses custom code, which in my opinion shows an issue with these triggers listed above, it should be simplified for others and also for hardcore weakaura creators, auras tracking buffs/enchants etc for PVE are super popular

My understanding is that most, if not all, of these types of custom code imports are creating buttons which actually *use* said consumables. Our policy is that we tolerate but ignore such "userland" features (mostly because actually supporting them would require essentially rewriting the whole addon), so I'm not too impressed that there are a lot of auras whose only other feature is to track buffs (which we already support). Is there something about these imports you wish weakauras had builtin support  for which it doesn't currently, and isn't "make it clickable"?

**Comment by Boneshockx** [comment]
Their issue is that this does not trigger:
![image](https://github.com/user-attachments/assets/31a8c5ab-c840-411a-a871-ee51e2647c7e)
Because the trigger requires a value for Item Type.
As Bartholomau said, their looking for a trigger that checks if anything at all is equipped in the main hand. However, to do so currently you would need to create one trigger for each of the item types. And thats a bit tedious.

**Comment by emptyrivers** [comment]
How does it make sense to track if you have an item type of nothing equipped? It sounds to me as if you got as close as possible to what you wanted in the options, and then declare that the point where you couldn't continue as the point where the feature you want should be placed.

**Comment by Bartholomau** [comment]
> Their issue is that this does not trigger: ![image](https://private-user-images.githubusercontent.com/6916881/371257153-31a8c5ab-c840-411a-a871-ee51e2647c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNzMyOTYsIm5iZiI6MTcyNzM3Mjk5NiwicGF0aCI6Ii82OTE2ODgxLzM3MTI1NzE1My0zMWE4YzVhYi1jODQwLTQxMWEtYTg3MS1lZTUxZTI2NDdjN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMTc0OTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQzZThlNzZhNjZlODE3YmJmNzI0ZGRjMzA4MDg3MDc3ZDdmM2JkYTUxMTBiMjJlNDdjNDVhZTk0NWZmMTc4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pOzbzdRfqk9RWaiPWBLuLEzvBk3CGLrOd0kG1mXLrCI) Because the trigger requires a value for Item Type. As Bartholomau said, they're looking for a trigger that checks if anything at all is equipped in the main hand. However, to do so currently you would need to create one trigger for each of the item types. And thats a bit tedious.

Thats exactly what i was trying to explain, but i explained everything in depth that leads to the problem

So if someone from @WA wants to understand my issue, i will show it by simply asking a question - how would you create a weakaura that shows an icon when
A) Any item is equipped in main hand slot
B) If it is enchanted (again - the trigger provided by WA works, no code needed)
C) Get info from trigger described in B) (the enchantment duration)

I want it to work if i log in for example on Rouge and check if i have ANY enchant on the dagger (which could be aswell sharpening) or when i log in on mage and have staff equipped - you will run into problems and end up making 12 triggers (if you want to cover all weapons, not just a single one.)

**Comment by Bartholomau** [comment]
![thecase](https://github.com/user-attachments/assets/f2c62b6a-645a-4619-8b42-bb16bf220f35)
This is the screenshot, i am also against clickable stuff, its simply to track if anything that is equipped in the slot has ANY enchant and shows the duration.
And i gave a few solutions for example adding multiple choices or checking if anything is equipped, aswell as solving all of these issues and combining many of the settings in one powerful trigger

**Comment by InfusOnWoW** [comment]
Why do you need to check for an item equipped? The Weapon Enchant trigger will work regardless and will show the duration if you have an item equipped and an enchant applied.

**Comment by Bartholomau** [comment]
Because not everything is enchantable and you run into issues when you do the exact same thing with off-hand. So this time imagine making the same aura but for off-hand, and check show ALWAYS on the enchant trigger. It will display mage off-hand which can be for example a candle (lol) and tell you to enchant it while if you were a rouge and had dagger equipped it would show the dagger and its correct. Thats also what i explained in initial post about checking for classes, it is really tedious, requires checking for 12 weapon types in 12 triggers and also checking for classes in Load tab

**Comment by Bartholomau** [comment]
And dagger is also an off hand but in this case more important to track cus its a weapon, i also heard of people having similiar issues with this trigger while messing with fishing poles, they wanted to do something more specific which was very tedious

**Comment by emptyrivers** [comment]
Right, so again it seems like you're grasping at the change nearest to what your last attempt looked like. I don't think it makes sense to muck around with item triggers when there's already a weapon enchant trigger, which is apparently incomplete.

**Comment by Bartholomau** [comment]
Well i understand it might be annoying to add something that only a small % of people will use but it would be super convinient to add at least multiple choice in that trigger or this (best would be if both): 
![screen1](https://github.com/user-attachments/assets/7350f77f-aae1-4953-b7a9-7a7fe06f986d)

**Comment by Bartholomau** [comment]
What about the enchant trigger being incomplete?

**Comment by InfusOnWoW** [comment]
So what's wrong with having two auras:
Aura one: Weapon Enchant trigger Main Hand loaded for all classes
Aura two: Weapon Enchant trigger Off Hand, loaded for rogues

**Comment by Bartholomau** [comment]
there is nothing wrong with that but there is also nothing wrong with having one that does the thing for all of the use cases in one single trigger, but it is your decision guys, im just showing something that caused problems in my case. i did what i wanted, but with 13 triggers and conditioning many classes in load tab and adding one extra trigger to ignore fishing pole - it doesnt sound perfect, you gotta admit it

**Comment by InfusOnWoW** [comment]
I have absolutely no idea what idea why you would need 13 triggers with the setup I have described. What's the purpose of checking the weapon type in these auras?

**Comment by Bartholomau** [comment]
so that the aura generally shows when that type of the weapon is equipped and works for all the classes and ignores a fishing rod, so you have to specify everything by hand.
t1:item>weapon enchant - main hand - always
t2:item>equipment slot - main hand - 1h axe
t3:item>equipment slot - main hand - 2h axe
t4:item>equipment slot - main hand - 1h mace
t5:item>equipment slot - main hand - 2h mace
t6:item>equipment slot - main hand - polearm
t7:item>equipment slot - main hand - 1h sword
t8:item>equipment slot - main hand - 2h sword
t9:item>equipment slot - main hand - warglaive
t10:item>equipment slot - main hand - staff
t11:item>equipment slot - main hand - fist weapon 
t12:item>equipment slot - main hand - dagger
t12:item>equipment slot - main hand - wand
you see what i mean, its annoying to set up and you could list even more triggers for ranged/gun/crossbow, but these often have separate buffs in expansions so i like to keep it separate overall

**Comment by emptyrivers** [comment]
Next release will allow you to multi-select item types in the item type equipped trigger.
