### ISSUE TITLE
Make the sound selection a drop-down with a filter text box

### ISSUE THREAD

**Issue by EntropyShadow** [WeakAuras/WeakAuras2#5444]
**Is your feature request related to a problem? Please describe.**
It is very difficult to find a sound in the huge drop-down list.

**Describe the solution you'd like**
Can you change the sound selection from simple drop-down list to drop-down with a filter text box at the top? So, I can type 'hide' and get the list filtered out to show only sounds that contain 'hide' in the name.

**Describe alternatives you've considered**
The only work around that I have found is to give up on using 'play sound' and use text-to-speech for everything. Unfortunately I can't use text-to-speech in 'Conditions' tab:(

**Additional context**
[Example: https://imgur.com/a/uOFxhPP ](https://imgur.com/a/uOFxhPP)

**Comment by EntropyShadow** [comment]
OK, I was wrong about the inability to use text-to-speech in Conditions. I found it in 'chat message'.

**Comment by InfusOnWoW** [comment]
The drop-down list widget we use is provided by a library, which doesn't allow us to easily add a filter input box, which makes adding such a functionality much more costly (in complexity) than just adding a simple textbox.

I did look over some options, e.g. duplicating the whole drop down source and then adding it, but I don't think that's a reasonable trade-off.
