### ISSUE TITLE
Report an error with WeakAuras and unsure how to resolve it? Or maybe it doesn't need resolving?

### ISSUE THREAD

**Issue by liuli195** [WeakAuras/WeakAuras2#5447]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

1、I have disabled all other addons, leaving only WeakAuras, Bugsack, and BugGrabber enabled.
2、After each /reload of the interface, the first time I open the editor for any custom code block in WeakAuras, the following error occurs (without editing the code, just opening it triggers the error). However, I can still use the custom code editing feature normally. The error does not occur the second time I open it.

https://pastebin.com/clone/9sfzHwVv

English is not my native language; the above content was translated by GPT.

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

TW/Asia

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
https://pastebin.com/clone/9sfzHwVv
```

### Reproduction Steps

After each /reload of the interface, the first time I open the editor for any custom code block in WeakAuras, the following error occurs (without editing the code, just opening it triggers the error). However, I can still use the custom code editing feature normally. The error does not occur the second time I open it.

**Comment by mrbuds** [comment]
This is a known error in a blizzard addon, they have fix it on PTR but have not publish the fix on release yet
