### ISSUE TITLE
Icons are missing or unattached to window

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#545]
**Describe the bug**
Trigger icons are not where they belong.

**To Reproduce**
1. /wa
2. Trigger icons are floating in the wrong locations or not there at all.

**Expected behavior**

**Screenshots**
![](https://cdn.discordapp.com/attachments/273144328447197186/472211303428128788/unknown.png)

Gif of them sticking in place: https://i.imgur.com/a7sUMVd.gifv

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.6.4

**Was it working in a previous version? If yes, which was the last good one?**
Was fine before today?

**Comment by InfusOnWoW** [comment]
That's the same as  https://github.com/WeakAuras/WeakAuras2/issues/543
