### ISSUE TITLE
Other Events > Spell Cast Succeeded DUPLICATE ISSUE

### ISSUE THREAD

**Issue by Bartholomau** [WeakAuras/WeakAuras2#5454]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

The trigger fires twice or few times instead of once

![zxczczc](https://github.com/user-attachments/assets/d632cc6b-c297-432d-b57c-31951cc4fa18)

I have some simple auras with 1 trigger only and for example one of them tracks mage conjure food when its placed, when i place it or someone else it fires 2+ times i don't know why.

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Explained above

**Comment by Bartholomau** [comment]
So i noticed it duplicates 100% of the time in raid, if i see it duplicate in other instances i will update this comment

**Comment by mrbuds** [comment]
Can you add an export of the aura you used, and precise reproduction steps from /reload to problem, if we have to be able to reproduce issue.

**Comment by Bartholomau** [comment]
https://wago.io/UcVP3olNu
here it is, just simply use Soulwell (warlock cookies) spell, same happens to all other items im tracking such as feasts (...) etc

**Comment by Bartholomau** [comment]
Also previously i was using combat log trigget to track these as they also have spell cast success option with ID field and it wasnt duplicating
