### ISSUE TITLE
WoW Classic Era Update - Version 1.15.4

### ISSUE THREAD

**Issue by maximus210793** [WeakAuras/WeakAuras2#5459]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Hi,

Could you update it to the latest Classic Era Game  Version of 1.15.4?

Would be awesome, thanks a lot in advance!

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Classic Era

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Hi,

Could you update it to the latest Classic Era Game  Version of 1.15.4?

Would be awesome, thanks a lot in advance!

**Comment by SpatenLa** [comment]
well, is there an issue? you havent provide any problem.

**Comment by InfusOnWoW** [comment]
If you mean that the addon is shown as outdated, that's already fixed for the next release.

**Comment by maximus210793** [comment]
thanks for fixing the "outdated" issue.
Sorry that I did not state it more clearly.
