### ISSUE TITLE
renaming or import->exporting causes hybrid sorting to autocheck/uncheck

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#546]
**Describe the bug**
Renaming or re-import causes hybrid sorting to auto-check/uncheck the checkbox for auras you want to list first.

**To Reproduce**
For proof that it auto unchecks:
1. Import wa below. Check co-tank (first wa) checkbox so that it's displayed first
2. export and re-import -> co-tank wa should be unchecked

for proof that it auto checks:
1. Import wa below.
2. rename a weakaura. 

**Which version of WeakAuras are you using?**
2.6.4

string

https://hastebin.com/efovorezuh.pl

**Comment by emptyrivers** [comment]
This should be fixed downstream, in #450

**Comment by emptyrivers** [comment]
Fix for this is merged in, and will be a part of the next release.
