### ISSUE TITLE
Using Auto complete duplicates any "|" character

### ISSUE THREAD

**Issue by Reloe** [WeakAuras/WeakAuras2#5463]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Whenever you use auto complete in the text editor it will duplicate any "|" character in the text editor.

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

- Type | into any text editor
- Trigger any auto completion
- every | character gets duplicated

**Comment by mrbuds** [comment]
Good catch! This commit fix it https://github.com/WeakAuras/LibAPIAutoComplete-1.0/commit/e6f37024a3c10aef0a1aa12c26c87f664b9f2980
