### ISSUE TITLE
Cast and Combatlog trigger (with delay) somehow sometimes interact weirdly

### ISSUE THREAD

**Issue by Jodsderechte** [WeakAuras/WeakAuras2#5465]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

So i've been running into this issue on a very specific fight (first boss of grim batol) to be exact there is alredy some discussion with buds here https://discord.com/channels/172440238717665280/215496276609990656/1291059821130285218 and here https://discord.com/channels/172440238717665280/215496276609990656/1292531343066009702 I tried reproducing it with mage  spells and it worked without any issues so i don't know exactly what the cause is. 

Basically Having a CLEU -> Spell cast success trigger with a delay below a cast trigger (presumably for the same spell but that could be coincidence) causes an issue as in triggering the delay incorrectly (as in not at all) there has to be some other deciding factor here as i couldn't repro with any other spells.

Reproduction WeakAura: https://wago.io/LLjYLw17w
Video: https://imgur.com/KLI6m1a

To repro you can enter the instance on normal nothing does any damage but the spells still exist.

### WeakAuras Version

5.17.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
No errors (i also lied on testing it with only wa) It also doesn't seem very consistent i had it work for a couple of pulls when i made the aura the first time so idk.
```

### Reproduction Steps

1. Import https://wago.io/LLjYLw17w
2. go into grim batol
3. pull first boss
4. cry?
5. fix the issue (hopefully)

### Last Good Version

No idea

### Export String

```Text
!WA:2!DF1wZXXrvyVEjXObdrwXLlBfhZIcXyhWYALLLVugxSZ6vyzV6sMDLLn2o70Zm9UtBp70T7zgjTIBXIqqM7iGafMBz5ov4L9bEINmvrv8avDkvu8dq)e8Vao9mZQl2wKuPOif5LD6P7ZCoN(CoFNVZMPEFn7ZPVaRtoy(tny((CwEazRPQxpGgMrohvgW4(z7W8RZLnjH4lApK4B7YLJjjnPvBjOwvkAuQ0KRq8zjsmQEtcZFm9q8qDFUpDvNiz8j1uBjdO2CFNGLOKGyfaApqTSsOK63i0DxgbHez4yqpGg8HGDdFy85hzxw1z(Sa3hD7HJyoDgDwBYirHndmkoCK0t8CUHHIGZE8JppPbFqg)4LlFRRvE(8NA(JNVJfx6qLf5EC5LYKjt22jBuYPbvSNk3jIiP5glYZl3SUSqQvaTjggmYp4qdou7GildAd8MeOjj2QRuWO6OFfQbpJg0Rw7qUDAqB)z(tDSu2F8lSY6MFaMZdYzrRtD9Yfsdcx1IyFBhjxK4ozZMD6Sdn4jFiZpKk9jExjrx33kXhDxl5PE6xj6v3JT4IePtUQCUxit8GebssG90PUkjHbwsijRCH00ABv4Nf78Aw466SgAPrLX9rbY2jjdpnhDdRILMSAjJ2Y4RTkDz0qYJe6ECIZywHepQF4(mAgHwxZW2JeeSpyyn9a2I0KfcQTAXQKOquPtjsm8sHswJg41R)dVsKF6lAY0fV(s4N55nUtGg0JbblFgwpcdZwcpslmBqNdTQ1fPeVq32ouRO61vUM8ILkp9yZuEnmpflsf8a2cDQvSqLQ1QuTGr11pAAjfpYOY0Lkx2WhdtbAgb241jRbXt4sYUsa1RECmaowAnsf8s9u9n3)8Q9zFPLpoSZYpnA8asOQ8M6cFanyqDggrHDnk8bF0kv4zESD69r35H3MsffuHSqdfIXfgho2dSXCRdFEFvjQBBLbQWJK20dUd4i7(aW(HdaJQTuxPmTCPSgUHVj8sADio3kkiK6mbZFNWHGpkCk)ddNwdoZFRtuaTwAu2foNUfpia(mqHLu7RI1MWz1GX0wBD5MufKmHZRxKeeIo(5aDOy7noQFRrg50NEKtbxakLyK)muXCPUG)(oTs9kLEo4td9SInVPfj0J3aoF7IXRZvgFb)yqF10m2mflwQsf0lKPEA)W1su9)cvn85s15yj6evDpW1nCOyrYa5hgopCJe1b3Cf1Ti(at4vqL0XHfCRiFecphDyIFlXEiXRRMu)nb3H(w7WWUlQmROxubfsdMy4KSG7AcjVHKgeKKmEPdUJDk2B3Kqv6cHxGfqS8Oy0DG7BmpZj09nbut9HAQyQyODW8m1e(uWXEutW8DHNf2lSNoZO7nHO4TVdRqK(ICEZmWZR6UaFISqzt1nrHkghll2Fp)djCuT22Oo4nv(WoxTRhvzEManu)NDFqpRIGavNhfs23z5(fFSqu2AX)K0OVMOwiRjTMqsTzXCaId8eKjzHHsuhXZgFgcZ5kEa7zv3y9c4RTL8q8wQ8h9jNAYsRM0F5QP9JwnvN(HXy4PMPA5XNSKOV4TdCjO3FTurf52ohTj3PMcfAk(4BNiE0ge7w1Q7X5s3hMiaBbQtSJE3NW9liDbsqfV9CyKatOURSUdl6DmjBXCVCeXr1Jnx1QjsQsIS6TGJLC3Mh7EmRKiwA20fRLC362GrVWmvNsCOTZXtElZkRF(aVOingUEGP3nfT2GBlD7n1ph7LfV1gL2qpsSCqTP4OBNh40c7qYSRf6If8Uyb1U2s65XZKQoLVWYhcUtwqcbqiebZbZdlKr88pMnYpOQDtIhbNaEn4RcVQj8fmHwWIWNpdSCg4l6cFP7kgy7(uILLKohlo9VTcjr2IM1uD6n8rgajCxyj4RG4Ud)2R2AnjlSh41HV2tijLkCYB6ZGRH71UeAGwHUm)gWxpd8nItgW38byTDjJA6tvT6utaFR0Wp8THVtl47Mb(EVGK5RgFa5sg6nIBqVio(eYcAcJO4qFOAlQVnIAX5dyoMqE12YuPgE4ZCc4KXSUsUh9W4cRa0f8O6vlm5LHtOoQZM(E98dDY8wbX9VSynfCz4gmgKf2j8CJchehT5Wl5WRfO6vyAe)qmY4knuNytVrbhhKq)gvCXbNCMG6Wi1ksqhnGEJyzVrH54mNb5nAGdibxmlodK4fV(Nv)M5gkFo94zHcAqTK)1)coZ11tOqUz80rWtbpTIM9VdxoHCfk)UMzfMiMlfM0fMAl8MW0MWlR4kbJugYxjLHeQG8Iq1ygMzszdHRGeGWSDz)GRICjBW3T9KsqThHqcmtiIacyb2V1oaNKQbm1xxrLanu0gqmLbWIjiGB1Lq4olAFeN6xTK3SNg82cBa0mLdaq(EEA7EqSC)posSl8cbAXWl4lJbQx1TlSighIv8k439WgoBUogpDZfV7kP49jb3Hv(pHOHVVj8dGF46M8nIXyWpc(XW9e7xnMXNSsKTnYXEK5zHU5IjWp6w8KFYtcgb3xbGGFAkSb(zPaf4Nd)Ieac8lvOd4nH2jOc4xb)A43a)w43Trrp87nH)a8h3OQ9KVJQAZLodBU85i(o5or3Q4mVNufV8EJhGJGOCPLASgtvXPypQnBq9XUa2vC5ZpLVz8GjPcQMSorySWpTMwbfuvSRULbcntGaNvB1TOT1cIF0DoN4Q(TaDUjIpIhkd)Zj232CJ5fxh)0Dqre8SzCdcRExJBQEgH3vV8LMBHrw49V4M9TzCtUJ4ZtGnVNHAg5DgQH771ADOZWDbnV2U)FlQzY3(g5h4)ATXlF5HU20x8k8zUd59TLJTNsLxVW)3vbg32wvt8Vd
```

**Comment by mrbuds** [comment]
For the triggers where Delay is not working, data for trigger.delay is a string `"12"` when it should be a number `12`
Fixing delay to handle string as it was a number won't be a problem, but i'd like to know repro steps to get there.

**Comment by Jodsderechte** [comment]
tbh i duplicated from the original not working aura when creating these test cases but i think i manually (newly) typed in the delay values? But i might be misremembering i'm not entirely sure. The original aura was send from my addon to wa looking into it it seems to come from there. Did this change recently and i forgot to update it? Otherwise idk how I fucked this up 🤔 Sorry to bother you
