### ISSUE TITLE
Overlay cost of spells

### ISSUE THREAD

**Issue by 1ps3** [WeakAuras/WeakAuras2#547]
Overlay spellcost breaks if you swap display power during cast
![2018-07-28_03-10-15](https://user-images.githubusercontent.com/15392657/43336097-c5aff6e0-9213-11e8-82be-db7b7b52d896.gif)

**Comment by InfusOnWoW** [comment]
What?

**Comment by asakawa-k** [comment]
I guess he means, cast Regrowth as cast then go bear form or whatever?

**Comment by InfusOnWoW** [comment]
He meant: "if I'm in flight form and start casting regrowth, it takes me out of flight form and puts me into regular, then the overlay just goes off the screen"

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
