### ISSUE TITLE
DynamicGroup.lua:674 after update.

### ISSUE THREAD

**Issue by itsreps** [WeakAuras/WeakAuras2#5473]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Keeps showing error just by opening WA, reinstalled current version. Reverted to last version, disabled all auras, happens still. Not super smart with this stuff but would love some help.

### WeakAuras Version

Weakauras 5.17.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
1449x WeakAuras/RegionTypes/DynamicGroup.lua:674: attempt to index local 'regionData' (a nil value)
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:674: in function `growFunc'
[string "@WeakAuras/RegionTypes/DynamicGroup.lua"]:1500: in function `DoPositionChildren'
[string "@WeakAuras/Animations.lua"]:170: in function <WeakAuras/Animations.lua:162>

Locals:
newPositions = <table> {
  = <table> {
 }
}
activeRegions = <table> {
}
frames = <table> {
  = <table> {
 }
}
(for state) = <table> {
  = <table> {
 }
}
(for control) = ""
frame = ""
regionDatas = <table> {
}
numVisible = 0
totalWidth = -3.100000
x = 1.550000
y = 0
i = -1
regionData = nil
(*temporary) = -1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'regionData' (a nil value)"
anchorPerUnitFunc = nil
limit = 5
space = 3.100000
midX = 0
midY = 0
stagger = 0
```

### Reproduction Steps

type /wa
click on any aura loaded or not.
shows up.

### Last Good Version

5.17.1

**Comment by itsreps** [comment]
[WeakAuras.zip](https://github.com/user-attachments/files/17289492/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
I cannot reproduce that lua error with those settings, on which aura exactly did you click after opening the options?

**Comment by itsreps** [comment]
doesnt matter which aura i click on, also pops up when i kill a mob as well, soon as it dies it bugsack goes off and i literally just /wa and just clicked on each aura and than would /rl and it happened with everyone. its weird.

**Comment by InfusOnWoW** [comment]
Is this the first error in the bugsack?

**Comment by InfusOnWoW** [comment]
and on which class/spec are you testing?

**Comment by itsreps** [comment]
its the first and only error, balance druid. havent touched/used any other spec, its a fresh toon less than a week old. it doesnt repeat just happens once, but only started happening after i updated today through curseclient. had a 4-5hour session and its been the one and only error

**Comment by itsreps** [comment]
i think i found the issue, it might be the mythic bev - druid group. soon as i loaded it on my mage it happened... but idk what to do to fix it, no waigo link just https://justpaste.it/7v7tk link i used from ui on youtube.

**Comment by itsreps** [comment]
Thank you for your help, works great now:)
