### ISSUE TITLE
WeakAuras Недостаёт талантов в бафах на дурида, сила зверя,

### ISSUE THREAD

**Issue by Diavyol** [WeakAuras/WeakAuras2#5479]
В готовых индикаторах в раздели бафоф на Друида, сила зверя, недостает таланта "жажда сверххищника"("Разорвать" с вероятностью 4% позволяет применить следующий "Свирепый укус" без затрат ресурса и нанести при этом максимальный урон.), Когда он сработает загорается иконка в спелах, і в бафах. У вас нету этого бафа и выставить соответственно никак.
![ico 1](https://github.com/user-attachments/assets/a2100da9-c314-45ac-abcd-33023d964d63)
![icon 2](https://github.com/user-attachments/assets/7123c7fe-ab5f-4d1b-b4e6-8ff7ea06f45c)
![жажда с](https://github.com/user-attachments/assets/556f38d8-b9ea-4694-ace8-05081a78235d)

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by InfusOnWoW** [comment]
Please report issues in English

**Comment by Diavyol** [comment]
In the ready indicators in the sections of bafaf on the power of Druid, beast, lacks the talent “thirst for super predator” (“Tear” with a probability of 4% allows you to apply the next “Ferocious Bite” without costing a resource and damage at this maximum damage.), when it triggers the icon lights up. in spells, and in bafaf. You do not have this buff and there is no way to set it.
