### ISSUE TITLE
Suggestion: add additional animation speed control options to the progress bar process smoothing feature

### ISSUE THREAD

**Issue by X-Zou** [WeakAuras/WeakAuras2#5481]
**Is your feature request related to a problem? Please describe.**
When using the progress bar, sometimes I want its process-smoothing animation to be a bit quicker than the default animation speed, but at the moment WA doesn't offer a control option for that.

**Describe the solution you'd like**
Please consider add additional animation speed control options to the progress bar process smoothing feature, to make the animation quicker or slower.
e.g. Provides a control bar to change the animation speed multiplier

**Comment by emptyrivers** [comment]
Eh, I believe that animation is off-the-shelf from blizzard, and i don't think there are any tuning knobs built in. Certainly it's possible to re-implement "in software", as it were, but that smells like a good source of annoying bugs to me.

Maybe it could be a good value add for when/if we implement general animated transitions.

**Comment by X-Zou** [comment]
@emptyrivers 
Thanks a lot for your reply.

Here's just some extra information to make sure I'm conveying what I mean correctly. Now the "process smoothing" function is a switch in WA (shown in the attached picture), used to control whether or not to show a transition animation when the progress bar changes significantly in an instant. I wish it's able to adjust the speed of the transition animation faster or slower.

I didn't realize that transition animation was off-the-shelf from Blizzard, cause I've never seen a similar transition animation in Blizzard native content before.

Anyway, this is just a personal advice, please don't be bothered if it's hard to implement.

![aa](https://github.com/user-attachments/assets/47a1d467-96a5-49f6-b156-1f115bf70e0f)

**Comment by InfusOnWoW** [comment]
What rivers said is exactly right, we reuse code from Blizzard to animate that. The code doesn't have a "speed" setting, and in fact the speed in which it animates does depend on the frame rate. So I think given that, I'd rather not have a speed setting.
