### ISSUE TITLE
Demonology Warlock: Conditions for Implosion Charges do not work.

### ISSUE THREAD

**Issue by QuinncyJones** [WeakAuras/WeakAuras2#5482]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Checking charges of the spell Implosion does not work with Conditions.
The display, however, works perfectly.
Perhaps Blizzard intended it this way so as not to trivialize the use of Implosion and Power Siphon.
I hope I haven't missed anything!
In any case, thank you for this great add-on!

### WeakAuras Version

5.17.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I have a Bisector Report

### Reproduction Steps

1. You need a Demonolgy Warlock
2. press Implosion or Power Siphon to consume your Imps (Test aura should not glow)
3. wait a while until you have two new imps (Test aura should glow)
4. Display of imps works properly

### Last Good Version

5.17.2

### Export String

```Text
!WA:2!Dv1tVnoru8MgKwPacAcLQDR2dvvIQUCOIw0U8NdaXDt2winPRTlTlsOKX2t8muNzmZmo)PNyZP9CUZLCgUej(c0lC1eXNGEGpa9ahr8MXoHTRpy)M38M373737npxOELEvcQe8QDNs95mhEIWh)WvedB1TReRo6RF(FS5kWZmuWpMiv4Gtqdx9)xqzRkgTW0l)ZDZmL5t4It5uMY7WAnDRzp3NZJc4dyodOX4oxVyzTGqmrG8vuot(eBPcjuL86szujPKf8rvASsqddXc57UJix8FIxprIBtdzCb2jghf9TmWzel1OySTuR4gzIhUpMPCs62LoCw7dR6422XTQT70aShO0fSvCuTgNw)SgXL1(leZWcQVdHpOfRJT54Xp4WCOU1PcEOalLBTRjKpYMH6HLLSva(V0cLO4Z1EXe(MWwDgBepoqwAjAovGb0y7CATgnSsG0ZlocnclMFNypvcFQgnansor7ste6mzPNV)Q)7VpjHLZgLIlRjW(y3S1NWdW)6k3cKpwWqrFhqDa7(l3Ejghxf8HVYgb8nzIeh11uKsVhWjsKkrGuyYuaS24qDf5l2iT8CyPhe)qbpHf8Q1JROWdvTLeeWkxKv6le)aJsZRUCrpeyqUGfJZWtwU92FOmETxZdhYJ4IVPqHcfVjt7cqzv9m3wXVVrPMCbxr9pNgOiwvHL3Mfl6qCGr5lNN119ICeDTzFDxkT7iibfCfKCUGsRMTAwlTSaYlTntng6BGrXJ(QBST7a9WfkojpzGEG1QlOxT1ZtqbabH2Y19oCWIio3OBaxeCUafp(8CHmG0NkPEr4o55(RDdjU8XnBwZUTvlx3wNyF8ZoYD(Yq7qVc)O8m7I7eh9UMw4wN5244M1(75Hr8b1f4FkbZ8hD6B9X7DWJZYs9gxRF9uDbgQRfhRxPp9CVeLIZA1hlG(WPA1nWSqf5dMPLxKAt0lYQufHNRHMYNTqdXy5sWz8mH6FjdUQu0CqhFueUOLwKyu0GcBw2enlGLWcIhbtdjQxAfXrb19uWbyQnS7LePOLS0nTBK(dLS9JqsPwYsceJwiEnalvZNgzgorEtvugzQW0pRZyl9uUzDfW1ihLUCwCgLL1PcwuknOZCOBdO7wXMHsqqxM3wxX59kCqcnywTV)ZpH6JAA)IpBQI73p7s29l8BZ2Mgy5ILQBZQA11rshypNdTRvRzCfaDlMPaxvH7I4o2dmTW2OOycQOhGWU0Wsckt7xmjE9fZl19VpLkrqRuazcIrZG9tsF76xJrsDkzkF3lTC6(ZdYR3T1Zfbhb(nqowBNgqP7B1drz1thySoDy6O0RGVVZBQzQ(CudBS5o2(eS)L1tFVIJ7Jeunse(eKielT7JIsWv2FBECLVuRKbk3CN0FUZ4ybhqGAKE2YEFYE6k)4f5uNBIZNSM9ZNp6HRSAfP3J3B)pDVdQ0)VU4)o
```

### Bisector Report

```Text
Bisect results:

report version: 2
addon version: v1.3.0
mode at print: done
bisect origin: cli
last test result: bad
Bisect took 1 out of (5-34) steps
Hints taken: 1
Addons ruled out: 16
Addons proved: 0

Narrowest set of addons that reproduces the issue:
|-- H:WeakAuras @ 5.17.2
|  |-- D:WeakAuras Archive @ 5.17.2
|  |-- d:WeakAuras Model Paths @ 5.17.2
|  |-- d:WeakAuras Options @ 5.17.2
|  |  |--WeakAuras Model Paths...(see above)
|  |  |-- d:WeakAuras Templates @ 5.17.2
|  |--WeakAuras Templates...(see above)
|-- A:Bisector @ 1.1.2
|-- A:BugGrabber @ v11.0.0
|-- A:BugSack @ v11.0.1

Libraries:
LibCompress @ 90083
LibCustomGlow-1.0 @ 20
AceComm-3.0 @ 14
AceSerializer-3.0 @ 5
LibSerialize @ 1
SpellRange-1.0 @ 24
LibGetFrame-1.0 @ 62
LibSharedMedia-3.0 @ 8020003
LibDispel-1.0 @ 10
LibSpecialization @ 10
CallbackHandler-1.0 @ 8
LibRangeCheck-3.0 @ 26
AceTimer-3.0 @ 17
LibDeflate @ 1
LibDBIcon-1.0 @ 55
LibDataBroker-1.1 @ 4
```

**Comment by Boneshockx** [comment]
You're using `%s` as text replacement, which usually means stacks. The catch here is "usually", it can be assigned a different value in certain triggers, like charges or count. In your trigger: spellCount is assigned to %s. 
This is why your condition behaves differently. You're checking for charges, however Implosion does not have any charges. It does have a spellCount and if you change your condition to use this then it works.

If a spell icon shows a number on your ability bar then remember this:
When you cast the spell and it consumes everything: spell count.
When you cast the spell and it consumes only one: charges.

**Comment by QuinncyJones** [comment]
Thanks for the quick reply!
The versatility of Weakauras is certainly one of the reasons why it is almost indispensable!
