### ISSUE TITLE
Sub-Groups

### ISSUE THREAD

**Issue by kippp** [WeakAuras/WeakAuras2#549]
**Describe the solution you'd like**
I'd like to have sub groups for weakauras (one more level).  For example I have a group that i use to track spell cooldowns, each spell cooldown weakaura has several weakauras that make up a single spell cooldown i wish to track.  It would be nice if I could group those up into a sub-group based on spell.

For example, I have "Frost Mage Cooldowns" as a group.  Under that group I have several things I want to track involving Icy Veins (involves multiple WAs) and I have multiple WAs to track Time Warp.  It would be convenient if I could have a group under "Frost Mage Cooldowns" for "Icy Veins" and "Time Warp".

**Additional context**
I realize that people will probably always want one more level of grouping and I understand that you guys need to draw the line somewhere, but this would help me a lot in organizing my weakauras.

Thanks for your Time,
Corbain

**Comment by emptyrivers** [comment]
Everybody would like nested groups. But it’s not on the to-do list for the foreseeable future. See [this ticket](https://www.wowace.com/projects/weakauras-2/issues/64) for details.
