### ISSUE TITLE
Weak aura not working after entering pvp

### ISSUE THREAD

**Issue by frozenorbenjoyer** [WeakAuras/WeakAuras2#5490]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When I make a weakaura icon with Trigger Spell 198149 (Frozen Orb), whenever I enter pvp area like battlegrounds or arenas and then I go do something in the world or enter a dungeon/raid it simply doesn't work up until I relog, /realod doesn't fix it re-entering the trigger doesn't either. This never happened before this expansion, I think it probably has to do something with the pvp talent "Concentrated Coolness" for frost mages. I also tried different spell id's it's the same thing.

### WeakAuras Version

5.17.2

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

New Aura > Icon > Trigger > Type: Spell > Spell: 198149

### Export String

!WA:2!Dz1tpTXru8aoTu5EbCdisuIecPeLgvHahf6PEWlyhibSjRnnPT06D2DMD3jSEMTZmlG5w8joB1R9YEONAUyP(fGd9upSYQFc4ypYNG(Mzx7echWZFEZ7979VFVDMgv6vbxbFXoPkYzQQhWPmL7w1B2PUDk1JZAZteEK7FRX6R3ObNPAtpNC3XOevix0kwr5mz5ri8BtKkcEF0zZk63Y3xsu)ZxmcX8aPmknBwbYZi9M2sfsOk76tzuz4JeyE3Gi(PHP6)31xG6rUUMh55hU7tx3krP4SnSarvLhAWOgeXZ3qqpFLxLGWcKcTsNoxFmHextgt8u2iWoHdLKi)cthpVb(BbVerz9iGpUBZ27UD9HAtUfpIlErj4ptqydZJgz1QtNw7BV7Z3PZvtTBJiuGu06Wo7TBZ6wrCe(ILfuwGGNeVKDVKifT8WejPlJCcregxrV2lcjLDrmCxn8Cgo9mNb6LNZzKqZkZ1wqCISu2dkl0xSlwo7yJcHOIGGI6fkuOiWdQQL5QBQ7h5kbWerEx2dw6DoJPmisZ8iDv9JjLTKqMdE0Fpq6ryibL7uvryoPQtb113NEcXzGpxO63dXCgaXvco(Kyh7yiB13PQEDQ5uKaEpiBe5mQBeXXo)a3Cf5yXaG7yzau2JNdWYCWDgqRXCAirW)OTyQVp1dcD91BZdzmUs7qrrhZ4NYchc2o)fGcxU0NFBD4XpVEYegkIEtKp1eI59CrkhBticEN1(1EEDqylbpYeGhOt(DGqZyxtvwliLfH6p2CCi17ygrklfppOSAf13qfofuVGeaww)ulDtY4P1h6MJnSnBx9HXwqxc3XuJ12dGFjBuuCiQ0i9j)qExYmUGc8PbLhHPYyW87c7xE2f(Mp0trzZo2JZJWGR1(uAmXjEEp4kEVoGHomgd5e3eZpxorU64as4LaYNwGhEnuvtemu03tesa()UbgVPagdrmApDJdBZSYngJteMnMshHKaGclT0BY28scssARGCEGkCUb6DDmxy1d6UAK9Jz)u2rzBM9ZZL9lWpF5NEYvsfeC7VDHjctvCVtYX0YZ8()kvM4ABcWYNSu2rJHTUiVJ19ym8f3jUIo82vgIWFe6nNP)3Qp0lVBVqI8M7zMzMsxLF6ewbRAh2Pv8xzouNN0oV3RPyvOvny71Ml8PNrWMdF34CYSjPTln3RZqu)(zZMQlPveDcXQzRM1Zosa4wlJHtbkgNWXKdvFnj2I188OyOQgfTYbcIuV2R)nCWjMZuI19uUa)AbkEWRlwmEQYmzG7v463G3n(UtdoGKcWp76vSiBZpOaDP73v4KV5go5juPPn3nKqdcvVYuqVhf6ow4tBoqNfMdHQFexB2Ixfl4bGdkZhN8K7FRztlyKNewgmPYn8QPJAmSTz3lTqHtzPn23u9TOPzTHG8Rj6q3b3E91Q(mdQ3OodbGg7yzMTyFQoj(kd7YwfwAFoggva0xg5x9Hs7pjlzar2cz74mqjObbqnAZhjkwEXIxRzzGOOxibBNaK4XlOpjGWicQx7q(PTyoJVX2rsZp2eeU)vqbcmLGPGupuNz3(G67T3idtgiuGhomfd91((6uRyN67DqJd3l7iBdpNzErcmu0zQAAdIspBu3TQ1Ut32DQz3jDIYaCyPf2vtWqe2g5JV7Kabu8LNEw5XT1k)RT1tBK3BqDxoZLhPgRN8yUQjCrAdb)CcBLwc3XtjE1x4mWSeMzvEWecKkBKhv0tdOapVb0HIeMbdzV0mnubZ8o2z4ufbu8F2WewrKgMQz8HSFl79lpZl(pnt5Btya7)jKQiw)4fqM1DYfhsRK)8wMIGQffbHRsXz)r8DMuJPBt3MkZVBK5loa(m4djkDDEdqd9r64UB7TSRxVjKjKiL2LiHvtO4rhVUFYoTxF7xEymm)xZErCeNL32qSoNZ7DqP1x7PPAEtAXhjrz5DDAo2b6uBWE8aW8COLOUoAiDIxMgW4csXhwzoTUqWfshtvVf03dFxrfP7ZwBJVDTQvo5FFZ))d

**Comment by InfusOnWoW** [comment]
Your reproduction steps are incomplete, please add your test aura.

**Comment by frozenorbenjoyer** [comment]
!WA:2!Dz1tpTXru8aoTu5EbCdisuIecPeLgvHahf6PEWlyhibSjRnnPT06D2DMD3jSEMTZmlG5w8joB1R9YEONAUyP(fGd9upSYQFc4ypYNG(Mzx7echWZFEZ7979VFVDMgv6vbxbFXoPkYzQQhWPmL7w1B2PUDk1JZAZteEK7FRX6R3ObNPAtpNC3XOevix0kwr5mz5ri8BtKkcEF0zZk63Y3xsu)ZxmcX8aPmknBwbYZi9M2sfsOk76tzuz4JeyE3Gi(PHP6)31xG6rUUMh55hU7tx3krP4SnSarvLhAWOgeXZ3qqpFLxLGWcKcTsNoxFmHextgt8u2iWoHdLKi)cthpVb(BbVerz9iGpUBZ27UD9HAtUfpIlErj4ptqydZJgz1QtNw7BV7Z3PZvtTBJiuGu06Wo7TBZ6wrCe(ILfuwGGNeVKDVKifT8WejPlJCcregxrV2lcjLDrmCxn8Cgo9mNb6LNZzKqZkZ1wqCISu2dkl0xSlwo7yJcHOIGGI6fkuOiWdQQL5QBQ7h5kbWerEx2dw6DoJPmisZ8iDv9JjLTKqMdE0Fpq6ryibL7uvryoPQtb113NEcXzGpxO63dXCgaXvco(Kyh7yiB13PQEDQ5uKaEpiBe5mQBeXXo)a3Cf5yXaG7yzau2JNdWYCWDgqRXCAirW)OTyQVp1dcD91BZdzmUs7qrrhZ4NYchc2o)fGcxU0NFBD4XpVEYegkIEtKp1eI59CrkhBticEN1(1EEDqylbpYeGhOt(DGqZyxtvwliLfH6p2CCi17ygrklfppOSAf13qfofuVGeaww)ulDtY4P1h6MJnSnBx9HXwqxc3XuJ12dGFjBuuCiQ0i9j)qExYmUGc8PbLhHPYyW87c7xE2f(Mp0trzZo2JZJWGR1(uAmXjEEp4kEVoGHomgd5e3eZpxorU64as4LaYNwGhEnuvtemu03tesa()UbgVPagdrmApDJdBZSYngJteMnMshHKaGclT0BY28scssARGCEGkCUb6DDmxy1d6UAK9Jz)u2rzBM9ZZL9lWpF5NEYvsfeC7VDHjctvCVtYX0YZ8()kvM4ABcWYNSu2rJHTUiVJ19ym8f3jUIo82vgIWFe6nNP)3Qp0lVBVqI8M7zMzMsxLF6ewbRAh2Pv8xzouNN0oV3RPyvOvny71Ml8PNrWMdF34CYSjPTln3RZqu)(zZMQlPveDcXQzRM1Zosa4wlJHtbkgNWXKdvFnj2I188OyOQgfTYbcIuV2R)nCWjMZuI19uUa)AbkEWRlwmEQYmzG7v463G3n(UtdoGKcWp76vSiBZpOaDP73v4KV5go5juPPn3nKqdcvVYuqVhf6ow4tBoqNfMdHQFexB2Ixfl4bGdkZhN8K7FRztlyKNewgmPYn8QPJAmSTz3lTqHtzPn23u9TOPzTHG8Rj6q3b3E91Q(mdQ3OodbGg7yzMTyFQoj(kd7YwfwAFoggva0xg5x9Hs7pjlzar2cz74mqjObbqnAZhjkwEXIxRzzGOOxibBNaK4XlOpjGWicQx7q(PTyoJVX2rsZp2eeU)vqbcmLGPGupuNz3(G67T3idtgiuGhomfd91((6uRyN67DqJd3l7iBdpNzErcmu0zQAAdIspBu3TQ1Ut32DQz3jDIYaCyPf2vtWqe2g5JV7Kabu8LNEw5XT1k)RT1tBK3BqDxoZLhPgRN8yUQjCrAdb)CcBLwc3XtjE1x4mWSeMzvEWecKkBKhv0tdOapVb0HIeMbdzV0mnubZ8o2z4ufbu8F2WewrKgMQz8HSFl79lpZl(pnt5Btya7)jKQiw)4fqM1DYfhsRK)8wMIGQffbHRsXz)r8DMuJPBt3MkZVBK5loa(m4djkDDEdqd9r64UB7TSRxVjKjKiL2LiHvtO4rhVUFYoTxF7xEymm)xZErCeNL32qSoNZ7DqP1x7PPAEtAXhjrz5DDAo2b6uBWE8aW8COLOUoAiDIxMgW4csXhwzoTUqWfshtvVf03dFxrfP7ZwBJVDTQvo5FFZ))d

**Comment by Foarfeca** [comment]
same thing when you enter dung or raid instance

**Comment by InfusOnWoW** [comment]
This appears to be a bug in how blizzard handles the spell replacement.
That is the normal Frozen Orb spell id is 84174, whereas the pvp Frozen Orb that is enabled by the talent has the spell id 198149.

After activating and deactivating the pvp talent, various "spell name" based apis, thus as GetSpellInfo("Frozen Orb") return the spell id 198149, even though the spell override is no longer active.

The work-around is to use:
1) The spell id 84174 in the trigger
2) Enable the "Exact Spell Id" option

This will work both in pvp and pve.

**Comment by frozenorbenjoyer** [comment]
84174 doesn't work but 84714 does

**Comment by InfusOnWoW** [comment]
ah, small typo.
