### ISSUE TITLE
/wa on, /wa off

### ISSUE THREAD

**Issue by andrewdudzik** [WeakAuras/WeakAuras2#5497]
WeakAuras is a fundamental addon for many players. Yet it has the potential to be intrusive, for example in a situation where one is studying the behavior of another addon in isolation. Example: Visual elements from WA may stand in front of other UI elements from other addons. I had this issue today with Details.

At the moment, the only way I'm aware to temporarily disable WA is to fully unload the addon, which is time-consuming, annoying, and prone to error given the complexity of the addon menu.

I propose a simple command-line switch: "/wa off" will disable WA, and "/wa on" will enable it again. This can be fast, and simple, and allow for better interaction with other addons.

**Comment by mrbuds** [comment]
Come on, turning off a single addon isn't that hard.

**Comment by mrbuds** [comment]
And there is already a function to pause weakauras explained on minimap tooltip
![image](https://github.com/user-attachments/assets/6b399194-6c27-411b-9421-b32e1754f31e)

**Comment by InfusOnWoW** [comment]
I agree with buds, there's no good reason to add this. Nor are you doing yourself any favors by that opinion as "ableist".
