### ISSUE TITLE
Fire Breath Weakaura not loading on Augmentation Evoker

### ISSUE THREAD

**Issue by MediaWizArt** [WeakAuras/WeakAuras2#5500]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When I try to play Augmentation Evoker, I cannot get my Fire Breath weakaura to show. I have tried creating it from scratch, duplicating other Aug WAs I have, using the premade WAs, and I just cannot get it to show.

I have of course triple checked I don't have any weird setting on the load options, and the trigger set to "Show: Always".  Even having the WA outside of any group (using the premade one and hand made), I cant get it to show up.

It shows up as Loaded.
It also only happens to Fire Breath as Augmentation. 

Have tried to get help on the discord and others were having no issue getting my weakaura to work on their end.

### WeakAuras Version

5.17.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Make a premade aura tracking Fire Breath using the template provided by the addon. Any kind of tracking option results in the same issue.

### Export String

```Text
!WA:2!Dr1ZUnXryCmBri5wjCCbusfhsJuJOKwlkisrCZRXgcYX2D3LsQuvTND3X7oK1ZSDMzTJ5qPyUWzFVx852lwQ9bipbJS6tqo0hG8e0Vz8AdbFy9mFZ3F)n)MFfAuEq5WYHV72ZibmQllJhGV1LwGYKXmE7ujHrffNJcFzMqIdpeDYLF)gc9Y8XT73xGLfMJObqeDyeQ0Vw9wE1DweWyjHSru3rKuCVtxTTEyeoMJcm5EFhHeXLf97tOerCrB4pzXjsojkcZf)YU88L)JTCCk2rKItsotK5JhIPs3S(9jNmVBTQUEDD9Q64LUrMa3nctXCsGBmBuBAphJVPBvlVb2UdNfXXcX232vNUVED(6WXq(CC7uVzZjMsDqOO4SqSpuipO(8NwVzNgpVPDg0M(PjOXyUdfnalkU4cfDMa(RAYi0yXutIAboT5vehnnJMprf3vDT9vLuBOUr6MMgz7QaOmePbMTBpeZH0R(sDqQDkopKiEzgv7a(Ei640nqM1Elt2HSq8FEPZb0hZPOKFeWoil)XzP5J6YB27CRlD5PikzGPg7R(0gNIrcSRKJPrY4RQkztzu8IWmUXJUAmNlWa1iumr7Qgeu7zparOnu3bcqTN6BuFRQc8)N9XwaGtGK6CHJNbySdosFN)OBQkTa26JcooIZYOHV76PLL4tKDfXi4g6OCsv6wgJMp9zCOR7kYxO2B66Z25RePL(GWRXsy8NvOqbRZwAfN03qmTR(CV2PFUXiWWzAyi4fKqzSDvy75lle5eCOX4BwSKu)t5TZPMZ1KFs)XQRoJZKWK5bgTB1UvDvjomuAFMzCmW0gwWVP5taqcl1GtE12)qgkeqf02EExyWxvPfgBJy8WxWrPtEr(ILnWqIG4NG7LpZFWdV0noOvR6oDTB751(qNdEYt9wSU0UKxH3kFIo6c1rFQHC3(5EnpOv9)BrucBudo(xZW0GXD(K7w5Epy50Pp4u9NhNZqSMO3PJEHFMuYO582zAZnnSQBmxVE1OnvVP2AO5u456twzj2456MZK5ysWXuGaBzc0naLGTS1lJngAsGd3WunBaLW8y)ymjkw(g7egkS)zbjiHaaPWUWZWGD9feAuc(6)SZGSejPOVesivEtfQOJXv9Q0YArKlgzpB9x9P2cajnUvcCRAUAOrCm(JnrOXZ4gwVgIS1ASZ7ZbPa4jhC)B5dg6tIkoNqxYRbplQEzp(j5GG9RySbfCEpxAMKfmC5R7nl8x)9oKqBjwiNUMKRUQP9xj2bcdoalT35lV5BOlUUx8DR5uVElNrgM(9YiHZdfU(1E4rp8UdrCcvxeCphusAmYk96RuV109hteiGbggptlmqmc5pAxNGyCWX77meLKHTMOtI2R0BqOcToDabaAhSWOejuxZIheJOryXxSR61pRJ1DR8aZhlRjGQfqhLJvP7Q(T9vV2s97Zy0vJeeQAYhf0YivV9dIWwlbRU2vw6Bp1B1sqvUFfnxzYQXP35hJXPv13Tshn8hxw4)GkF33x5(Lh(Vh9)d
```

**Comment by emptyrivers** [comment]
You're probably running into the spell override bug https://github.com/Stanzilla/WoWUIBugs/issues/654

Try the workaround steps mentioned in that ticket and see if it doesn't help.

**Comment by MediaWizArt** [comment]
In the meanwhile I tried to repair my game and that seems to have solved the issue, I will refer back to what you link above if it happens again :)

**Comment by InfusOnWoW** [comment]
I just checked te template and it works for me. Though as rivers explained the bug with some Evoker spells depends on a very specific spec/talent setup which I tried to replicate but maybe wrongly did.

Because of those specifics the bug might still occur, in case it does do respond and I'll take another look at it.
