### ISSUE TITLE
Add Blizzlike Purgeable/Stealable glow/border as an option in Icon auras!

### ISSUE THREAD

**Issue by Somatics23** [WeakAuras/WeakAuras2#5505]
Hello, to preface I’ve been using this incredible addon for years & it’s effects on me have exceeded just exclusively in-game, I’ve learned and took away a lot of knowledge regarding custom coding due to this addon so thank you..

I’m a pvper first and just the other day had the idea of adding the Blizzlike border or glow (although I think it’s a border) to icon auras for purgeable/stealable buffs.

I attempted to do this myself within SharedMedia by adding the Interface\TargetingFrame\UI-TargetingFrame-Stealable file in both blp and tga format to no avail as the scaling/sizing was hilariously wrong on the free online converter I used.

I use a mod for Plater that causes buffs above my nameplates to have this glow/border I’m looking to add to my WA’s so I believe it’s definitely possible to implement.

I think it would be a worthwhile addition to Weakauras as both pvpers and pvers could make icon WA’s for important buffs to purge or spellsteal & it having that blizzlike look that you’d see on target/focus frame purgeable buffs would look great and improve player reaction in my opinion.

Picture of the glow is provided. Thank you for reading!
![IMG_3163](https://github.com/user-attachments/assets/5d0ce20b-546e-473a-9d16-1f47a1c4d465)

**Comment by mrbuds** [comment]
This is applied on TargetBuffFrameTemplate as an overlay texture with alpha mode "add", that would require a new type of sub element

**Comment by Somatics23** [comment]
> This is applied on TargetBuffFrameTemplate as an overlay texture with alpha mode "add", that would require a new type of sub element

I see. Thank you for the information!

Is all of that still required just for simply adding the border or glow for icons? You did say it’s an overlay texture though, so my suggestion of it being a border or glow may not be so simple/possible in that case.

**Comment by Somatics23** [comment]
slight bump, would love this as an option if it's not too much of a headache to implement for the authors.

**Comment by Somatics23** [comment]
![image](https://github.com/user-attachments/assets/4c847195-e67e-4370-817d-81c11ec5ae67)


trying to do it myself LOL doesn't look too bad

**Comment by InfusOnWoW** [comment]
We did discuss that glow for a bit but decided against adding it to WA as an option. We don't feel it adds enough to be added.
