### ISSUE TITLE
Since 5.17.2: my "load always" weakaura is not loading fully unless I open /wa and click on it first, and even then it's spotty. Still works perfectly on 5.17.1

### ISSUE THREAD

**Issue by Fonjask** [WeakAuras/WeakAuras2#5507]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

* I am experiencing this issue on: 5.17.3 and 5.17.2
* This weakaura still works instantly and flawlessly on 5.17.1
* Retail WoW

WeakAura in question: https://wago.io/vToRxC78V
Code used by an addon that does the same is identical: https://www.curseforge.com/wow/addons/hideactionbaranimations/files

Specifically, the hiding of the castbar inside the spells' buttons is not working.

The way the weakaura works is
Trigger -> Always active
Actions -> On Init -> the code

I don't really know what else I can do but describe the issue and indicate the versions it still did, and no longer, works in. I'm sorry about the kind of poor title but I didn't know how else to describe this. If you require anything else please let me know.

GIFs of the problem (I hate the in-button castbar):

This is what it looks like when it doesn't work (captured on 5.17.3)

![This is what it looks like when it doesn't work (captured on 5.17.3)](https://github.com/user-attachments/assets/de037db6-2ecb-400d-9afe-806bc1f5a2de)

This is what it looks like when it works (captured on 5.17.1)

![This is what it looks like when it works (captured on 5.17.1)](https://github.com/user-attachments/assets/8e8ce969-ea92-4466-9168-90872ce85eee)

### WeakAuras Version

WeakAuras 5.17.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Load the weakaura on WeakAuras 5.17.1 or earlier, cast any ability that has a cast time. See that there's no castbar inside the spell's button, like this: https://i.imgur.com/4zEYnLc.gif

Load the weakaura on WeakAuras 5.17.2 or 5.17.3, cast any ability that has a cast time. See the return of the castbar, looking like this: https://i.imgur.com/TzasCkc.gif

### Last Good Version

5.17.1

### Screenshots

![This is what it looks like when it doesn't work (captured on 5.17.3)](https://github.com/user-attachments/assets/de037db6-2ecb-400d-9afe-806bc1f5a2de)

![This is what it looks like when it works (taken on 5.17.1)](https://github.com/user-attachments/assets/8e8ce969-ea92-4466-9168-90872ce85eee)

### Export String

```Text
!WA:2!nJv3UTnYv4yyuSOQ)eVUDd2TBb6eh0ePwB5KGnPPgnDHKmvSx4yPsjBNfnTIdjhkoXuZm7mdLSYIEJBbAbAVYpc(6ELEe6taHrFcYf7dW(e0Zmuswo2kRl6ErjGTi5C(BoNVZzohUW(l3B5WLvUpQ8tk)jlh(3wtoSruKIOxqYt1jugr2yV27S9UoY(ePIYz)Gruwex2dRHhUR4dPDzCjPHW8OYPpHPDKsUu5ncOkGyFJYtGcPkrcEyBYr6o583r0rt7rg)0cI7oFssiDXbd7eLW5Y4VgZcI5Y6sCps7HcIFRAUoo7EcMrZTQhxThMYQxvdlwLXzKZctL2v6yELurc4Sq1XeSYkGSL(xMBBPLewxD875Q0yPUE2nZwk79Zwo7hb)(JFp)ikJQIF7xFIIKe1KtzA)QnA3UXZFyQmr8XXATqTX6Rpa3LxMYxVFBU7r1(vpz)1FS8OCx8)436Ri9a3Q7dlF)Yp4mCQg2wJ9KVAFjJ)CISlXl7M(XeCiq3aAOoErzQISlS39QQbp1XhGLmkR7T3p72FNSB6Qe4aYjajBrODJ1EN1hlPy)eYbgM9arzE9IW2yuirfiPw9b8ECeNPBrFnXnbdQn7oI)yTymRliBep3Oq9m8I2TrBKpb1NQOGCxxJpKGirrKankLPPjOH8u06sschhIkc4iepcfW75J1LwfXLiZsDlNBWz)8S76LDpVSIF39Z(zWMndLD7fZwXdmGLoigRrAUb8y2cF6xnkMgsCjCj4o8QQaR9daQnEKnHnt8i4MA8KeSqrIpoyYDN0fqZclwrr7jsiGIE4HKHYXY9uvQ)y)(NfzSQhjdWkTpwc(EnVBxGJ7hxLboDXT3mNhKoMGmuHaYquMcmmefawkW2IWPjAVCrDC3GqvmKjbBTFniMSnUOmSRHWrAIera0Wq0ZQTz2VXRFvt8r8rfXSqWJP0qAMLbEsica1LSsFuqSjAPgqfJvGhOGp5ckWSg4)b(4dyaRiSpnHQPefAavhJglcqNJTyHKdadw3ZT4vNvGMLqrjyvmAqmbe3ejoez40iiaiA95NKq7r15jzNA8FT4PqvHfY2iBnjoW6YFCviXsFx)Guyp27OV3ns4b4eJVaQCGEk6llGGRv2B3TB3PvtND2PwLwT7S9UTDCD3RzBNnxz1RKIw7vRMJZMZD96v2EN5ZC7kUTN7AnAoNLQTvLD31zN3j7NtZCfJRt7TRTJthqkpZP93arWFvCNdnopVzJdCCFN2Z50yTN)uHcRT2AOjbCkBndQ(COEXEqTiK)q06PR)cEiTFPcfYJyrPmBeDcVTeKKKAaFMk6PssXsw9tJqyOEChcRFzqYr0U)(7nor8E)bKbTp)LlpoV0GdzwPzUGdlqDw1yRiQatLQI5GNsOq(uImxvS2xvSm)M8dNShKSXEmjPlvbzH23wKuAkNewyHz)f2amU()h3eUxNTG5VcZpeDHO)Clq9FbmO24kp1TNFscBzK33gyHjfwVOF8TJoJDxPAnNbg(5wZrKWlYP5kMZpe6paCfMTrX7nl3tyTtJP3Ujui(EREbjyJLtCbfnDhSku((lsPYPEI9eHy9mrNzVY9HtQwx3wL9PiJy24zeDtS0ezlvU2SeCLcIg9wsX4nVWBkB)FfOTPn2w1e68cQRxS0L9jZEnpb0sZfflD9yBJTGZkNdXtaQVR3DroVEb6NI0YuY3y(W8WQxoP4AEO6fYt2es0idlv4)TkGNFG)5HQ3c2UslthS1SuozlTYQtHLffwy0QJnslXtEyZXTkp55NZdDVeyf2a5IyS1mrhxn25kjDJweTtyxYKcpRSndkWebnV(YxoHMx(scqXkxu3Ze6kLh7mXgxspE)8qdJmaX9z8JO8uvYqKTDwuavgaXobximTVKkgxrdB7z5B)W0KEOMFmAw8ANwX8bnGIRqw4Zs4dMny5BP4sbG8xx2wb3iQ(2WwLeIuxUjOCBu96LCV2ABHdo00OTP9ARtC6Wuivo6WNeGHURnAEaboscDfs56BsZPCXARzSpRbOZXfiFjbFOYCQimCeGJcHGkAaEOQ8L4(DOEdARsIigx8(xwR160ggYuwUIbqu8(LF4JNX7p)AAxl19Gsxv5S3nI(KqEN8MH9Y(Gcz3QGFo86wzpUE2t9YQ4L9eVSAEI7m)jMfssa1mV(I(Mrq3EZtMobQlmxex(zlcxhpaMK6ajwC8bJVrSuUMnIm)ykxBBiFn1KEYWj7N)za(7pmLgo6Z7vnyNhP4UTyNgzQZAhY8V89pvZdg)9c(Wf(RXJYNypFk5AoMo3LVcudnAy1DCQ3EKkgd571S21clSWIMbYm9Yath8tUv2npdE0hqOMrkyH(k7me(WKCCP(SCE)88zQ)P3yuKPtiywESgV4OzCqlJgt6lYjDXtnFfaQDeKczFQ4lNuEpLXibeLcdD6unH(6xJLHOUqsPcHddHZsaS4dGb2l)OYfkuJdjmdKuTgWTZ0nKT8W0AjMZhCjHG2wfDaGNn1nmuxNZEfwDy53aZ(Zn5Bbwhy1kWJIp(kJU534AcYHIvMpaOhpSd4diEvnJH3VQsqcULBpyUuAHS1Vv2xu4uiDUt(y5XMpyqhMP7Uy3a4mALHaFnobc9MBpZSoHfa(Fagel(LZxXHdH58ObD0XWqRXqH8HhRL0UDb4Wp8UNa8N)qb54B(Qr5iUoMApz9o2OPuyGqVtdj(PrrMHhLB5StZ67TZBmlItmP)MJZ9YFgaesF4CkINy5ZFXweCI9LhRmzOBhQku1ixFJDtGj7Z(Zz7DATPyG3aGmluVjuGMEKRDaPPVSfyj0Jg158HdDnJZQkmX6nFzPS9eVVzO2(K257nJ()N3OQ5lRiwQUK(A0VlfhAGMO2TpvAr42HJVZk0qXDgJaN9GHPnO7y)alQSFXhTC))9lYAK18)m
```

**Comment by InfusOnWoW** [comment]
This isn't a bug in WeakAuras. Your code is trying to modify your action buttons, and whatever issue you have is surely somewhere in that code.

**Comment by Fonjask** [comment]
Then why does it work in 5.17.1 and not anymore in 5.17.2 onwards?

**Comment by InfusOnWoW** [comment]
A difference in when or why init runs is not a bug. The gurantees on init code is just that it runs before any other code from an aura, nothing else. And you have provided no indication that this is no longer true.

**Comment by emptyrivers** [comment]
to wit, we *did* change the rules on init scripts to be more conservative on when they run. you'll need to do some research to get your custom code to run accurately again. Or, you just use the addon you since apparently that does the same thing.

**Comment by Fonjask** [comment]
> to wit, we _did_ change the rules on init scripts to be lazier on when they run, for performance reasons. 

That must be it, then! Thanks for chiming in @emptyrivers , Infus' response is a bit too technical for me because I'm not very good at this so I was waiting for our guild's coder guy to log on to help me out.

> you'll need to do some research to get your custom code to run accurately again. 

Do you have a jumping off point for me, by any chance? Perhaps a weakaura you know of that might've been impacted by that, that changed their code so it works again?

> Or, you just use the addon you since apparently that does the same thing.

I guess I could, if the "lazy init scripts rules" are there to stay and intentional and so on (I don't really know what this means). It's just so odd to me that the other 3 parts of that weakaura still work, it's just that one small part that doesn't.
