### ISSUE TITLE
Shaman Imbues not refreshed upon login

### ISSUE THREAD

**Issue by Andf** [WeakAuras/WeakAuras2#5508]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I was a weakaura to track Flametongue on my shaman's off-hand but it's not refreshed hwen logging in back to the game. 
Aura is still there but WeakAuras can't see it; it works perfectly until logging out.

EDIT: Same issues with Windfury.

![image](https://github.com/user-attachments/assets/65737f97-be35-4d4a-82e1-acf44b51afce)

### WeakAuras Version

5.17.3

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
N/A
```

### Reproduction Steps

- Create a weakaura to track Flametongue imbue
- Cast Flametongue
- Aura is being tracked
- Log out
- Log back in
- Aura is not being tracked until re-cast

### Last Good Version

Can't say, sorry

### Export String

```Text
!WA:2!9vvZUnsrq44yKIKpSAJbc)TefIaeWHOSbCw(ti5XXgcYRT3XoKLtJ7zMEMPjJ7UP7ESJ3B4t5SVZfFgUyjEb8tWilEcYbEaYtav3ZyVjlk4dEQQ66)Q)QUqJYdk7x2)QpzgXJr7YseE4hTH4Y2bbsSQWCK)VKivy)NIUCZxYqOBkgVwfQxet0HrOk3A1B1RU9spgl2NnI2DeHJ7VyfBD)qCKLoq9NOeKWqSq(GpwKtE1BjWGRqu18gXObyfJgMGNqu4bTa2ctrjcefOKVlV8T0yVZXioJY3orIDcXuSG41nInQnT)Y7WET08PwE2mxRFEe7pvGhGiucnC)JoCM(KrgV2FMp2njiO3yow8d1B2PXznxQpET(rxltCXdXuvxqpYLZDQvTBpNU9QA3Z4OSO23sbUWsxnl0sxvw9xBEhbgm3UBN6nBABQZs8YRdJddsaKIjk)DtKCCC8P(Ys2gdVoRbSx9SAXnlGlY(u1trgITsOeLlpgngleq4nr2nRepIfemnHMpfkX3gzmPxg)tz(4)yJBGHlwqrX)emYim6VFnxWcfyPm7kZN9On2CkIsgGuWPhBlviHQr6UwugfVaJK4Uky6gQI2APpmg1A5OBicjgUo4lNO1r3KtRyPRyW20kPhVv6ts)Y0VkTIBa0fKrVQyy6irkTdXrZGgPnoe8S8R3jD3LaRlY7IqblH6F17XlRWxQGPbcg(pp)Yl)Dmcn)fWeq67iZjsRmD9z7)rC(E)hn5okYaSZaMVJob6FDwaWXbgWGv1Z61M)6gHOeft3B8oN4RISQcS3K5kYLyFJWFBzgq6NZtTfMZ1aosW40TMjykii9aHwTA3Qo)dVV8jghI8g7eeZyIi(NEFQ5pgUJr8CurWymcGeft3va9mTQ8p4(SIlWEe9nGIZmN6XIzIFSi8BAU2WfPtycIStN8o(DkRVDJ7mhwvS8hElH1m(SqHcfxAKoIj8pxG4topNiR1meYd3yC)CBV1AOPTpd2c50RDNLRtkdagK38uO3T79vEzCfFPzDjVa)(5tM)Nln8CcBTx8)NLHXSrne4Fnb2VmUZRD4bhvjR7QpqJ))(486mAIwKo7w6MOGnAThIfaoDMwCtdK5nNRPx1QMgUYutBFHM9KCivrJMRYtlntKr)UEOyCrtA1lI4DbfqUfnN0Ka0BBIMf0EXIi3imjmsDQvmd53WscDGDShKeRiLSGnpE7KQkz7fJKsnLRc8mvPj5pekSQ5VryEYi6vfrOrZegmQbRxAEGa2eb7gqkuXjRENisOxbb44Jt)IswaWxvk9BkTearWuOn3CeKcR7b83yLLA4XjejcUx4h5cBwciHLMPyEdZ2B92f(Z)AFIF6dShPXCNAJI5rOI3KnGBOtgDI52TMD96T4LHSF1ZfWIqBnk)OeI)8wh6EXZ8oU2Pp7Xccv7C4HTxWydkCZfymVQUpPS1ZKOz69BKSCEoHMDpb4knD9MI0TklDRCWJFYbFE5H)9Z)3)
```

**Comment by InfusOnWoW** [comment]
I cannot reproduce that, the aura works fine with your reproduction steps.

**Comment by Somatics23** [comment]
having an issue on cata classic similar to this, i have weakauras for missing imbues (windfury/flametongue) and whenever I zone out of arena they show even tho i have both imbues active on my weapons, wasn't like this prior to 4.4.1 on cata this past Tuesday.
![image](https://github.com/user-attachments/assets/f355deda-b6e4-47a9-93f1-2ad1418b890d)

**Comment by Andf** [comment]
Morning! Many thanks for helping on this problem.

I have just downloaded WA 5.17.5 but the problem is still present... As soon as I log out and then back in Windfury and Flametongue are no longer being tracked but they are actually present.

Happy to run any test, of course.

**Comment by InfusOnWoW** [comment]
Can you try whether changing this line:
```timer:ScheduleTimer(tenchUpdate, 0.1)```
in WeakAuras/GenericTrigger.lua line 4127
to
```timer:ScheduleTimer(tenchUpdate, 0.8)```
fixes it?

**Comment by InfusOnWoW** [comment]
Then I don't know what the problem is. We cannot reproduce it. That call updates the enchant trigger 0.8s after login, which should be a fail safe way to do this.

**Comment by Andf** [comment]
Uhm... I raise the value to 20 and after some seconds both imbues pop up.

I have a similar weakaura tracking Lightning Shield and it's there right away but temporary enchants are not... it olooks like they are "active" only after everything else was loaded
