### ISSUE TITLE
tooltips from spell-cooldown triggers don't update in real time

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#5514]
1. make a spell - cooldown trigger for your favorite test spell
2. ensure "tooltip on mouseover" is enabled
3. out the spell on cooldown
4. mouseove the aura. notice that the remaining cooldown doesn't change as time passes, contrast with action bars where they do

**Comment by InfusOnWoW** [comment]
The blizzard action bar simply calls SetTooltip on pretty much every event that it gets and thus it might look like it updates in real-time but it doens't. I can easily make it not count down correctly by doing nothing.

So our option would be to call SetSpellByID repeately at a regular interval, which doesn't seem like the right trade-off.

**Comment by InfusOnWoW** [comment]
https://github.com/user-attachments/assets/4704193c-e0a1-4500-b744-8f1b4724217a
