### ISSUE TITLE
aura_env.saved is wiped on aura reimport

### ISSUE THREAD

**Issue by lootwant** [WeakAuras/WeakAuras2#5520]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

On aura reimport it's aura_env.saved is apparently wiped. There is no mention of such behaviour in the docs, and it kinda defeats the purpose of persistent local storage.

If it's by design, it would be great to mention it in the docs.
If a hard wipe is not actually required, would be great to make it optional and disabled by default. A checkbox on import along with the others, "Erase saved data"

### WeakAuras Version

5.17.4

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Reimport an aura that has aura_env.saved populated. Observe the nil after reimport instead of saved data.

**Comment by InfusOnWoW** [comment]
The intended behaviour is that saved is not overwritten on update, that was a thus a bug.

**Comment by lootwant** [comment]
Tested, confirming the fix. Ty ty!
