### ISSUE TITLE
Dynamic progress bar overlay is bugged in conjunction with max progress

### ISSUE THREAD

**Issue by grioja** [WeakAuras/WeakAuras2#553]
I am making a weakura with the following behavior:

Max progress of 21 (max duration of Ironskin Brew)
Shows a forward overlay of size up to 7 (for extending the duration)
The overlay is supposed to dynamically size based on remaining duration (up to size 7)
I am observing that the "progress" given to the overlay changes in scale when you hit the max of the progress bar. A size of 7 once hitting max is far smaller than a size of 7 when duration is only 10s (for example).

What steps will reproduce the problem?
Download my weakaura and use ironskin brew 4x on a brewmaster with black ox brew (so you can reach max ISB duration). Observe the overlay does grow up to size 7 (1/3 of the bar) as the duration diminishes to 14s.

What is the expected output? What do you see instead?
Upon reaching a duration of 21.. the overlay should be of size 0, and as the progress bar shrinks the overlay should grow, up to a size of 7 (out of a max 21, aka 1/3 the size of the bar)

Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes

What version of WeakAuras are you using?
2.6.5

Was it working in a previous version? If yes, which was the last good one?
No idea, new WeakAura

Do you have an error log of what happened? If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install [BugSack](https://mods.curse.com/addons/wow/BugSack). 
No errors

Please provide any additional information below.

If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file. It's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

In case you do know which aura is problematic, please export the string and paste it below.

``` duuCmaGiQk1LusjnkeWPqGMffj3IIAxivnmboMQAzu4zqmnGUgu2Mk6Bamoe15uI7rvH9HuPoOskwiI4HqkMOskvxerYgrkFesPmsiL0jvs1krrVujLyMisDtQkANs6NqQmuksTuiLONk1uvPRsvjBfsj8vLuk7L8xLKbdvhMslgfESkmzu6Yk2mv5Zi0OPionQwnsL8AivnBKCBiz3c9BQmCbTCqpxvMUORRuBhqFhPIXJGopvvRhsPA)sS(6QgLAw1S6Q2Ysx7xoS(0sOQgF1(rNN3Bsvn)jVO2ZftAuwIp1OZxxsVELuQzyHOXr5G6QQHObsgaiizqKadStmagbYZmgOQiIggYj5LfagbgKnod(gYZmgOs1Hqhr48EMgoh8h3fvnqnLZYQRAEKi0Td1vnQnvY1vPs1PLAIPUQrTPsUUkvQ(foh6Q(XJePgv)kvdDuJUQrTPsUUkvQML75Xp2uPFDvJAtLCDvQu9(nRoOSVNirn0Em6Qg1Mk56QuP6qGHPLAIPUQrTPsUUkvQ2ZEKCxux1O2ujxxLkvFqzFpDv)4rIuJAFIU6ArP69Bw9cNdrI60snX0qx1O2ujxxLkvQo5OgiACuoOUQAiAaw(ggbNGbG)tWtWa5zgdtverJmcYzaaWZaqeYaaacqEMXWuQ(HY5stmn0reoVNirnCiYDXR)WrTDdTmSq1V0EG(NyOohcZnCutkkG(A9cE1brPo5OginxmvtkcdHZ7rhRF1mCq2bUE8nPQF17yc5ejoqDvFSFPdLAVD8i5UibiyHzbVGxWl4Wj3Wyb3UH2vtei9SBOn5Uyb3h(OGhuyorwLQThjh4CHCIehOpDSJQbQp2V0H6oeM(kK1MJ6b4et1S8xiL1)Dimj94LQxRHQDahiL1)txv)6Q6x1VQgIgzJtmqJLLaqeSammq5zgdrverdGbGtWaWFaczJLfaKLNzmqvbfnmWaqK)cGtaylglNF5zgdrPs18yoWOLcTyGpUlQkMAgoi7arJJYb1v1VQbQAOAGQiQgOkOQFLQTrokBYDrDv)slm1vDiCEtQ2ZYoQt)HJ6q48MuPApEK)mrx1HW5nPApl7Oo9hoQdHZBsLkvNdHPyOE)M1Wsx7xoSdRpTeksuh3OUqorId8PQHAgoi7arNN3Bsv)QtoQbsJYs8PgD(6s61RKsnd7b6zHUq04OCqDv9RAGQgQgOkIQbQcQAGs1MmCIMKQ(bvZzvVEtsbNelundhKDGIe1mCq2bskwIJ6Fb30Cchk1mCq2bUEKg0ftXqndhKDGKypqpl0fQU6IJAgoi7aBoAFu9Ro5OgyZr7JQ)VAlllp5UOLAvc5ejoWNUQ(1vDc5ejoqDvN(dh12n0Q(TzmaNy2BppoHQxHM103v9DnOLx174aCIPA7oDQJwuZtxv)Qxh6Ip0ZJfCsGdDuQE)MvwgphKHpDSJir9aCIPA06yPstu)2mgGtmnnC84eQUnnPinPv)chkQ1zF6Qu9ZehDqxu9ZehDqxCnhjh4OEh5P6qkR)bQE)Mv7ipfjQzhgBpVR)WrnALuK2008fPvQEhtiNiXbQRsLkvZYF01oEKCGJAB0VA6Wzttu9JHOMF4IIH6eYjsCG6Qo9hoQp2V0Hs9X(LouOd4aPS()Q92XJK7IeGGfMf8cEbVGdNCdJfCF75G0Xcz9TPk42n0UAIaPND84h8SWCISfMfMfMfMfMfMfMfMfMfMQ3VzLLXZbz4th7isuFSFPd1AFdTj3fv7TJhj3fjablml4f8cEbho5ggl42n0UAIaPNDdTj3fnvb3UH2vtei9dHHCOn5U4LJAkmNiR6J9lDOu7TJhj3fjablml4f8cEbNYDyPk4SBOn5UOPk4dHHCOn5U4LJAk4(OG)gQ5ijaMPk4RT1ScTnPVI8KKTNhb8DiL1)a9TPk4(EDOl(qppwWjbo0X3eKGfMf8cEbVGB3q7QjcKE2n0MCxSG7Jco7gAtUlwWDWcEqHzbVGxWl42n0UAIaPFimKdTj3fVCutb3hf8HWqo0MCx8YrnfChSGJ2M8YrneGGfMf8cEbVGB3q7QjcKE2XJFWZcUpk4O4rcy8l4Ml42n0UAIaPNDdTj3fnvbhablml4f8cEbho5ggl42n0UAIaPNDdTj3fl40DbpOWCISfMfMfMfMQhGtmFQvFSFPd1Q0F4O(L2C)uFyYCGE17qwBoQ3Xb4et12D6uVFZQDKNIeLQ5rEU6LwyoSQ(vF4IS8K7IpDv9RR6dtMd0RR6eYjsCGQ(vd0c5wguJ6HWqo0MCx8YrnQbAP2JAaQDHQPBLQpmXgjopDv9RRAGwQ9ORQFv)QAiAKnoXanwwcarWcWWaLNzmevrenagaobda)biKnwwaqwEMXavfu0aCID()lGGacodajJipZyikvhcDHdm9RMHfIghLdQuvdDvd0sThDv9R6xvdrJSXjgOXYsaicwaggO8mJHOkIObWaWjya4paHSXYcaYYZmgOQGQ(vQoe6chy6xDYrnq04OCqLQIORAGwQ9ORQFrd7Jbi4e5hya4dccUipZyiQAiAyNKpjVqgbZyzbbbbuEMXqufr1VQGIggyaiYFbWjaSfJLZV8mJHOuDi0foW0VAhWbsz9)O)RuPsvn0v9HjZb61vDc5ejoqv)QbAHCldQr9qyihAtUlE5Og1aTu7r9huTlunDRu9Hj2iX5PRQFDvd0sThDv9lAyFmabNi)adaFqqWf5zgdrvdrd7K8j5fYiyglliiiGYZmgIQiQ(vfu0orcWcqworwqaSSCckpZyikvhcDHdm9RMHfIghLdQuvdDvd0sThDv9lAyFmabNi)adaFqqWf5zgdrvdrd7K8j5fYiyglliiiGYZmgIQiQ(vfu1Vs1Hqx4at)QtoQbIghLdQuveDvd0sThDv9lAyFmabNi)adaFqqWf5zgdrvdrd7K8j5fYiyglliiiGYZmgIQiQ(vfu0Wadar(laobGTySC(LNzmeLQdHUWbM(v7aoqkR)h9FLkvQuP6NAd6pPhtnqv)GgFLsa ```

**Comment by grioja** [comment]
Ascii illustration of intent:

First number is progress, Second number is overlay size

|------18--3|
|-------------21|
|----14---7|

If duration is >= 14s, then the overlay should cover the remaining width of the bar, but it does not.

I confirmed via use of `math.random(7)` that the actual size of the overlay is being miscalculated once it hits max progress.

A better solution would be if WeakAuras did not extend the Overlay past the max duration of the progress bar. But until then I have to do a `min` calculation to prevent it going beyond the bar bounds.

**Comment by grioja** [comment]
@asakawa-k that screenshot doesn't illustrate the problem I see

**Comment by grioja** [comment]
The overlay at max progress should be 0 (non-existent), and as progress counts down to 14... it should grow to size 7 (and fill up the remainder of the bar until that point).

|---21|
|---20-1|
|---19-2|

The visual size of the overlay is the bug (once hitting max progress).

**Comment by grioja** [comment]
Here is the weakaura after I let it count down to 9 (once I capped it out). As you can see.. the overlay never fixes its size (it should be 1/3 the size of the bar at this point).
![image](https://user-images.githubusercontent.com/89693/43360839-0b9e6896-9285-11e8-8014-b23889c3bb02.png)

**Comment by grioja** [comment]
Looks fine prior to hitting max:

![image](https://user-images.githubusercontent.com/89693/43360856-825eb3fa-9285-11e8-895e-f831d3377dad.png)

I observe that the maximum width of the overlay is being set once a change in progress is made. It cannot be reset until I refresh the buff, and only if refreshing the buff at 7s (to 14s) will the overlay grow to full size (7) because the remainder is 7. If I refreshed at 10s (up to 17s) the overlay would be constrained in width to 4 (and never exceed it).

**Comment by asakawa-k** [comment]
Add `print(aura_env.deficit)` to your trigger and you'll see that it is showing precisely what you're telling it to show.     
Your calculation isn't adjusting based on the remaining duration at all, only max duration which doesn't not change once the buff is in place.

**Comment by grioja** [comment]
@asakawa-k Ah, I mis-understood the `duration` value (which in reality is not very useful...) switching to a calculation based on the expiration fixed the issue.

Appreciate the help. You can close this.
