### ISSUE TITLE
Select a specific trigger for activation requirement

### ISSUE THREAD

**Issue by ZingusWoW** [WeakAuras/WeakAuras2#5530]
Hi,

Please consider the option of being able to select a specific trigger for activation. 

The common use-case that I see is when a user sets up additional triggers for the sole purpose of feeding data into conditions. For example, when a user is tracking the cooldown of a spell as their core trigger while tracking the spell overlay glow or a buff (or both) to determine when to show a glow.

The current solution of setting up a custom activation function just to do a basic `return trigger[1]` seems unfriendly to those unfamiliar with custom code, and may limit those users' ability to design what they want.

My ideal would be to add an entry to the "Required for Activation" drop-down for all existing triggers, allowing the user to select "Trigger 1" etc.

I do understand that this may lead to additional feature requests down the line asking for GUI options for more complicated trigger combinations but I think selecting a single trigger is a good middle-ground.

![image](https://github.com/user-attachments/assets/b0cf91f4-b64c-427c-9f8b-d2b9828649c7)

Thanks for reading.

**Comment by InfusOnWoW** [comment]
This is a less generic version of https://github.com/WeakAuras/WeakAuras2/issues/1236

**Comment by InfusOnWoW** [comment]
And yes that has some chance of being implementedf this decade.
