### ISSUE TITLE
"Boss Mod Stage (Event)" Rounding error.

### ISSUE THREAD

**Issue by fisken1991** [WeakAuras/WeakAuras2#5538]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I encountered an issue with the Boss Mod Stage (Event) that triggers a fake stage 3 event when bigwigs send the stage 2.5 event. This rounding up made my stage 3 weakauras trigger early and twice. The second when it should but the first one from stage 2.5 was wrong

![image](https://github.com/user-attachments/assets/4c383aa2-09cc-44d9-9781-43a073b8bbb0)
![image](https://github.com/user-attachments/assets/55097afc-35d1-4776-aa8f-1127519a7918)

### WeakAuras Version

Weakauras 5.17.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Play The Silken Court in Nerub-ar Palace on Mythic difficulity.
Set up a trigger with Type "Other Addons", "Boss Mod Stage(Event)" as you can in the in the picture provided.
When you enter intermission 2. Big wigs will send a Stage 2.5 event comfirmed by Bigwigs discord(check the picture provided). This will trigger the Stage 3 event aura incorrectly. Maybe due to rounding up as suggested by the bigwigs community.

**Comment by InfusOnWoW** [comment]
I just checked that:
a) The stage code for LFR and mythic is identical
b) In LFR: Checked with prints when TheSilkenCourt.lua sets the variuous stages
c) Checked what WA receives
d) Checked an aura for stage 3

And also
e) Checked all code in WA that handles stages

This is almost certainly a user error.
