### ISSUE TITLE
Missing Stats in the Trigger Player/Unit Info -> Character Stats

### ISSUE THREAD

**Issue by Bisonpasfute** [WeakAuras/WeakAuras2#5542]
**Is your feature request related to a problem? Please describe.**

 I'm always frustrated when I need to do custom triggers to do simple things. Recently, I wanted to do a trigger based on the mastery rating and one based on the resilience rating of the player but I couldn't find it in the predefined triggers.

**Describe the solution you'd like**
In the Trigger Player/Unit Info -> Character Stats, add the Resilience Rating to this trigger, maybe to the "Defensive Stats" for instance.

For the mastery, we could add the Mastery Rating to the "Primary Stats".

I've attached the pictures of the trigger.

![image](https://github.com/user-attachments/assets/ad87867b-f96f-4403-a2ba-a1247531f904)
![image](https://github.com/user-attachments/assets/47e7e389-9b1d-4f3b-9f65-3b903bfe1282)

**Comment by InfusOnWoW** [comment]
Which wow version is that?

**Comment by Bisonpasfute** [comment]
@InfusOnWoW Totally forgot to mention it sorry, it's for Cataclysm !
