### ISSUE TITLE
WA Interface not loading

### ISSUE THREAD

**Issue by JeremyKnightly** [WeakAuras/WeakAuras2#5546]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

when I type '/WA' or try to open the WA interface from the minimap button, I get a series of errors. If I try a second time to open from the button, the UI loads, but none of my auras load in the panels. However, my auras themselves are working just fine. also, the 'loaded/standby' and 'not loaded' menus are populating behind the interface window, and do not go away after I close the interface.

![image](https://github.com/user-attachments/assets/907fc2a7-9949-45f5-a2a6-bf87c4c0b678)
![image](https://github.com/user-attachments/assets/d210f90f-3541-4228-8332-b150fdf5cd4c)
![image](https://github.com/user-attachments/assets/40593e0a-c63b-4247-a9f3-3476944c33ad)
[New folder.zip](https://github.com/user-attachments/files/17868901/New.folder.zip)

### WeakAuras Version

WeakAuras 5.18.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
https://pastebin.com/1DJs045b

pastebin with errors
```

### Reproduction Steps

1: type '/WA'

### Last Good Version

whatever I just updated from

### Export String

```Text
That file does not exist within that filepath. I was able to find the WeakAuras.lua file inside "D:\Programs\World of Warcraft\_retail_\Interface\AddOns\WeakAuras\WeakAuras.lua". It is attached
```

### Bisector Report

```Text
Bisect results:

report version: 2
addon version: v1.3.0
mode at print: done
bisect origin: cli
last test result: bad
Bisect took 1 out of (4-28) steps
Hints taken: 1
Addons ruled out: 13
Addons proved: 0

Narrowest set of addons that reproduces the issue:
|-- H:WeakAuras @ 5.18.0
|  |-- d:WeakAuras Archive @ 5.18.0
|  |-- d:WeakAuras Model Paths @ 5.18.0
|  |-- d:WeakAuras Options @ 5.18.0
|  |  |--WeakAuras Model Paths...(see above)
|-- A:Bisector @ 1.1.2
|-- A:BugGrabber @ v11.0.1
|-- A:BugSack @ v11.0.2

Libraries:
LibCompress @ 90083
AceSerializer-3.0 @ 5
SpellRange-1.0 @ 24
LibDBIcon-1.0 @ 55
AceGUI-3.0 @ 41
LibUIDropDownMenu-4.0 @ 90135
AceGUI-3.0-DropDown-ItemBase @ 2000
LibCustomGlow-1.0 @ 20
AceComm-3.0 @ 14
LibSerialize @ 1
LibRangeCheck-3.0 @ 26
LibDispel-1.0 @ 11
LibSpecialization @ 10
CallbackHandler-1.0 @ 8
LibSharedMedia-3.0 @ 8020003
AceTimer-3.0 @ 17
LibDataBroker-1.1 @ 4
LibGetFrame-1.0 @ 62
LibDeflate @ 3
```

**Comment by InfusOnWoW** [comment]
These errors seem to indicate a broken installation. Try resintalling WeakAuras.

**Comment by InfusOnWoW** [comment]
Error messages for future reference:

14x WeakAurasOptions/Libs/LibAPIAutoComplete-1.0/LibAPIAutoComplete-1.0.xml:1 WeakAurasOptions/Libs/LibAPIAutoComplete-1.0/LibAPIAutoComplete-1.0.xml(1): error: not well-formed (invalid token)
 
--------------------------------------------------------------------------------------------------------------
 
14x WeakAurasOptions/Libs/AceGUI-3.0-41-SharedMediaWidgets/widget.xml:1 WeakAurasOptions/Libs/AceGUI-3.0-SharedMediaWidgets/widget.xml(1): error: not well-formed (invalid token)
 
-------------------------------------------------------------------------------------------------------------
 
14x WeakAurasOptions/Libs/AceConfig-3.0-3/AceConfig-3.0.xml:1 WeakAurasOptions/Libs/AceConfig-3.0/AceConfig-3.0.xml(1): error: not well-formed (invalid token)
 
-------------------------------------------------------------------------------------------------------------------
 
7x ...dOns/WeakAurasOptions/OptionsFrames/OptionsFrame.lua:285: attempt to call field '?' (a nil value)
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:285: in function `UpdateFrameVisible'
[string "@WeakAurasOptions/OptionsFrames/OptionsFrame.lua"]:663: in function `SetLoadProgressVisible'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:691: in function <WeakAurasOptions/WeakAurasOptions.lua:683>
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:835: in function `ShowOptions'
[string "@WeakAurasOptions/WeakAurasOptions.lua"]:613: in function `ToggleOptions'
[string "@WeakAuras/WeakAuras.lua"]:172: in function `OpenOptions'
[string "@WeakAuras/WeakAuras.lua"]:256: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5479: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5131: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5167: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5163>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>
