### ISSUE TITLE
Very specific problem with the Devastation Evoker Spell "Fire Breath"

### ISSUE THREAD

**Issue by dkas** [WeakAuras/WeakAuras2#5550]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I present a very simple test case: 

1) Be a devastation evoker
2) Go to wowhead and import their simple weakaura to show if the Spell "Fire Breath" is available: https://www.wowhead.com/spell=357208/fire-breath
3) it is not working as devastation (no bugs in my bugsack, so it seems to fail silently)
4) switch specs to preservation
5) the weakaura for Fire Breath works

### WeakAuras Version

5.18.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I have a Bisector Report

### Reproduction Steps

1) Be a devastation evoker
2) Go to wowhead and import their simple weakaura to show if the Spell "Fire Breath" is available: https://www.wowhead.com/spell=357208/fire-breath
3) it is not working as devastation (no bugs in my bugsack, so it seems to fail silently)
4) switch specs to preservation
5) the weakaura for Fire Breath works

### Export String

```Text
!WA:2!1vvZUTTrq4iB0euDOqrnnigOOqnO1ijOiOPaXOxfDKqCIJLlLsCkIbixYDe5wtT7IDxkBzG024t5So0B9Io3ErO9fiOpaec9jWpc(jOZUKY5huRdI7mCMVzNz(MH162CutAt6R)MzSybVVixfd18Jfzc1Jwf)nNq)PCTbOpHXxrnP3WHAWuBoHhNku7kyCt0MD2zqh)fXcrgvCiV)Hmje(MLIDOjqQNf8WPAjKLTdzeCJps)8ZqFbfNK9mqPzc(VFQujsuGwxElUZNFPvMQHSHUOuC5zuqtm5kIbsNPZJ8He0l9DUUNzIewGAIiXhKOe5C6Rxt20ahzc0Pe8s88QR9uNo7F38RLY1oxkyOqnIycKvh8nSra90sewEd8A)0b9KFQtjj3iq7yX7XOMuV2O4zLaXocOoLVs(v)p4BboidsiXtcgMjeQ034mWwJzdNGzPsyWmCaQ0BNE70r(LxeksfeZSfUvlAOWS3AYIY(YY8DMZT32mNwbd3iB0vXoU1pKtOybL0AWazJ3PGTPZLA1QT67vh)XkClVZJXOhLbHlCshku09ue5j7vDyX5bBa2Fu9E6GT3cZNYW8o8NIll)IlkhlLQjBDrgmsqdSmIW3gT(SJH1K3(I8GoHtgXIdmPivlf5OtQkAltUOuGLKAELxMGq)TtJZiAnEFPbi7nE9inJNKbxBF)r5zg2g)1lc)NxeET9dJmKmGBUEXg19SwApmnxdboacvhl4Wwu9k(o51lUFuNN17XD8rZM5mtmkIycLnp3NZdAQNgZjlGYg4BBxnrIZKKJspzzoFpNRBwn29eb13wx(qpy80zk3KJTRu8XksSXogTHV2quM6EmoZupAi(qNw)KLtXHZWbykZzA9fi9hly9KLIVDfb5Ov(UCgD(Up(rP3BNJUfBJh4DSqmQ2zLL4UkC23g3O(B63PZoYRTeFlF)bmnb5t0up74v6mJiEC5QHBu7p)7BYOYpRltbT8uaXK2Q9yclZ6GpjtMswD(ql69nw(8Q(h6MbvhTSPIx)HSK6kg3IjKE2baiBBRUgSoXePNyuSKe8DFY6QQJVUHpYvaD9Ig(Uvxf1TlUu5Cym2Ql67ACij6WE8q5vTcjahuS4(L6w8EINwA5Yo0P4mRdNDvaU2WV)UD2E7Zv2pFiQCEWMT7piO)G2(dw4c2YnOHN4oImQ6E5yllsMrMaQOYymV8HpqOt8D4jxBzCBTB1A2w3QVfIB7yPyzl(GqChBegy3a7d7S9UDF62tZ5vLJ6YRAjlJHbLYifd(JlnNY02yVfwHL3El7o9HKyyFRSEFselJzMeaJfhakC9OcICTV5mE5Cj2ExFoEmg6yVN6q5nyjCHcQOxoTDukHshoLWzLUSrr3Ufn844q1cQ9BcOUa73bWERLPQFdq0wYaWtmPx5eRKJW)sVregh9T4Lf)CXVu8RxP4v4Xh(HAAQJU)DV33F3VT54)95)3d
```

### Bisector Report

```Text
Bisect results:

report version: 2
addon version: v1.3.0
mode at print: done
bisect origin: cli
last test result: bad
Bisect took 1 out of (6-70) steps
Hints taken: 1
Addons ruled out: 34
Addons proved: 0

Narrowest set of addons that reproduces the issue:
|-- H:WeakAuras @ 5.18.0
|  |-- d:WeakAuras Archive @ 5.18.0
|  |-- D:WeakAuras Companion @ 5.2.7
|  |-- d:WeakAuras Model Paths @ 5.18.0
|  |-- d:WeakAuras Options @ 5.18.0
|  |  |--WeakAuras Model Paths...(see above)
|  |  |-- d:WeakAuras Templates @ 5.18.0
|  |--WeakAuras Templates...(see above)
|-- A:Bisector @ 1.1.2
|-- A:BugGrabber @ v11.0.1
|-- A:BugSack @ v11.0.2

Libraries:
LibCompress @ 90083
AceSerializer-3.0 @ 5
SpellRange-1.0 @ 24
AceGUISharedMediaWidgets-1.0 @ 9004
AceGUI-3.0 @ 41
LibUIDropDownMenu-4.0 @ 90135
AceConfigRegistry-3.0 @ 21
LibAPIAutoComplete-1.0 @ 5
AceGUI-3.0-DropDown-ItemBase @ 2000
LibSharedMedia-3.0 @ 8020003
AceConfig-3.0 @ 3
LibDeflate @ 3
AceConfigDialog-3.0 @ 87
LibSerialize @ 1
LibDataBroker-1.1 @ 4
LibGetFrame-1.0 @ 62
LibRangeCheck-3.0 @ 26
LibDispel-1.0 @ 11
LibSpecialization @ 10
CallbackHandler-1.0 @ 8
AceComm-3.0 @ 14
AceTimer-3.0 @ 17
LibCustomGlow-1.0 @ 20
LibDBIcon-1.0 @ 55
AceConfigCmd-3.0 @ 14
```

**Comment by dkas** [comment]
I have to correct myself. 

The weakaura from wowhead does NOT seem to work as preservation. I get a weird message: "WeakAuras: Dara for 'Fire Breath Available' is too old, can't modernize."

The bug is still relevant tho:

I do have a - very simple - weakaura that does work as preservation, but not as devastation. They do exactly the same, only load under different specs.

Import String that works as pres:
`!WA:2!Dr1tVTrruC7yqrYsbLykrns9quLOuOquBLAeIluVU2XH6yB2DlnOEWE2DhV7qwpZMzM1)jahWNkx99EXNHlwI7OO(byLfQFaIq9gxYbos4nZUoTP(W637nV59NFZV3lFTs9l5vY753EgXLrTyXCx8nYz6Ycz8VPa8BoY7hIfsS3bOrR8gfcDf(4w96jWY6)5X)6RU4Il(V5iQBaJ3MrOsNkvBAx1CHlJf6XgsTgsIWDpDPAvpFCGHkLDNi5eFFmx8b3INj(kd54iSPichgEMi2bpatLwX96rgnVtLYw2DSSlBAhTrSa3XhtXCIRvaBylAxtTVrBvjlrB3MZ85yHy7BBPc3NAetjsNOq0ymFQodnr9Xx)9fhUqfTlT0DIwCFprXfxjfZf6)mXiVXMuWtrXlRX2CmuJMwTR2OXuv4KCK7rDN5HDGQ3gAkE9QnAx7jWP0SMTy0gixjza2ov)aMh(3YDoGHyoff(DaYqy0xC(ryCuzOMCLMijHfmvGd7PX6KvHeiqYyosIdMbfJj2hUJ4R2mzTfGQdue(Cwm175xlQKeps2reGa45W0xW8rBPnQ)0JX7JahYemOmkE6LhFZpweT(BfHkAIs(85lCwQ1LfLr5Ny3k6d1grXsgekI7tjEYaJYG65P5Imc7Pn(llsjpFFwfDQ(CfzJ0Bm0GCMeAoBWOrZwnRMSgh6lLpZ0o(g(60SMaibRxJtoz7Vng5badABB7R07lZ0cTTHmU3t5OOjpntiTagqeeNqC3SE(Ti4rBSFZMvn7y0Y2U1bM7VxD7fxMAlYj4TY6OdVsEuNQ5bTEIDJ9Bw91l8dzdRXXhhJPUJB)E3DN7)G0UtDWPQpps9WcVNfMO0u3EHtSuYOTgG5arEMYCdm1xg8rZvYlBTPkLkxcnNcmY9wAjq75YIZqPeO93YffIlOll7aI7ruy4PG(KgeqEdD2maucZdCcWe)az9h(1FX)2bwbyeYqE9oZnejeay5PgNCVLJGq9dXV8zM9JdLKnF5Z66iHKqLBMCyrtT3kPOsQrMRE5ad1x1Pgcau1UTo4w5Sfr69sbVRjcnygxpdOqRKIZ7XHbvlPIhu4SOSvcPB7(SBKBLjl3l1LRMfHrNDnfsexw0GaRlk60d(teuKpA5kVhU7N83V4ZV3cGAdVXTI0xQy01wgift9rebcipEboWEUEe)IZKm3bPZZxp)V)h3K4nVgHJ32GJrYaZHQbbalV4F6MlxonASCngSuaM6XDppLtvt1oQwZXQIz1QnnrHrbOc3pgI4XrOhpQ(JnpyV6CcvLoyt7jmw)8ZGYWJKwPZj005BqR4ueLKkUBcUwYAj35umsOWlnPA1fEzmWoQ9Yqavbsmr5JgFVJrFeHQVyYjRM8Jj)uYpdI(VRLscNhSZ9(YDUBPb)1H))p`

Import String that does not work as dev:

`!WA:2!Dv1tVTrru84yqrYGqjMsOrQhSQeO2anQu1wr7fWBQDtqU2MD3stfhSND3N3DiRNz7mZANKBKt9SpWnUyb3GlwWDu(eSYc4dqoWnUKdCn8MzxN2uFW7mV))(T)EVTuZQdRgun4L3yk1NZC4PcF4AljoOZGbsqTZF0X5NfT)H7oJe8DPsfe8eYbl)Qlu2YIdxy6l(PnQT0slnJW8J4IUCkt5TDJ2UnSN7Z5Xb8XmNX0eO)jlU2iieIeeFfLZK33wQicvfVbugvgvXcFOQCSsqddbH89(yrXX)2sDycyltG44tLPEWiGPCshmGEWSEBx3XTNJBDB3K1sLqVqGbcQVteFChwFBJTjBSDrbuRRGhkaPS2nC0H7M2mYqqwzAa4Hb0fZJyNgT628PTMRJMjNTrt6FS54UbYkZVukMjnpSbsWHwPyh4LetoeexuODfawO2oDB0Q1eDmviaSF)jxe6R(2)1dNKYkA2kjRPXNrGB(9NWdGFzPZqSfems83GidcE)4z7dqsDmg(kBccNrtim6q9j29ZENMNaej4OealufTs2QwmodMhKkmw0tJNcjGeGa5XAt1nE2MwdjuwZSBIoKTz2NK9Pz3cF(UVPeeSKeLowq0uSnTHq97ZhUE2QZXREy7fk4PSGxELKQk4avpzebr)9YjoLs2Wi083aUaR6EYIdzBo5cDx)JKjR(AUVnpMl(QsLkv(0CPq8adPZQ(tD7K8(gHKufxdd(pJgOISQJxplpr0dGaJWVFEoH95fLZjg9AcoDWHzRmvWvyN5IcTA3PDJSvfytPTzQXqFtzug)nPOdqc2Qnf0JQ91PKaevi1CDVuJVitZnYgZfbptqso(zfhYlGruj1lg6x0ZV2qvYA72UDd7EwDCD78e7DF8oUZVi1o0JGnk6O9UuE0Ane6op1T1UTB8pZdJ5JBkGxKcm)d7(w3ER7CV8UtR4eKB(44cyo6yTiT3Z9svkoRZiqG86PAXTmSQpyM(8IwBs4cxnqZj6RpQGUv2y5ffNjYru)9z4CyzJJo(KyOSL(yKrqlkQCnt2SqucerEranmsTZx(f36)6D(5NBfZjbdo1pMiLiyfOhv9x3tszHXWV9TEkmIm162dtJv0k2g7wpJujPQEg8YU13Y4mQ1sIWPXSvrZQxS2ZSfm6nfrzrtfgQVgNS0RtTjXjrKYz0(ZOSCgnQUYKlOQzRy)k(J1rC(Ws3jLgmR94BS7dg19535UpyQI7pkFk)QL(1F)60GKpSjva1Searfv7rWicU4uh4ZYFT3uGBr01GNZ22nA0E2aTaC6hPILThR58iSD()2hxwBA)fBdXDl4YdOVhw6dOHveuMoZquYvwSXwpg8iQKGmZGOttk2EM)zJnV2slpvVdHA2Nx54fo1FoogIfwNKCfvLE3BRp7Z362vh9N79))`

**Comment by dkas** [comment]
It seems that there is a know problem that maybe is at the root cause of this:

https://github.com/Stanzilla/WoWUIBugs/issues/354

I can - somewhat - reproduce this: as preservation, I can use "/cast Fire Breath" to cast the spell. If I switch to devastation, using "/cast Fire Breath" gives me a "Spell not learned" error.

**Comment by InfusOnWoW** [comment]
Yes, Blizzard has known about the bug for years now. It breaks basic functionality like macros, yet it remains unfixes.

I suggest you contact blizzard support.

I think using exact spell id, with the right spell id, and disabling the spell follow option should WA use the right information. Although that requires having one aura per spell id you want to track.
