### ISSUE TITLE
Pixel Glow pixel asymmetry

### ISSUE THREAD

**Issue by dwWei** [WeakAuras/WeakAuras2#5556]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Pixel Glow pixel asymmetry

https://github.com/user-attachments/assets/1c695118-7f9f-447f-a736-1c61980de77a

### WeakAuras Version

WeakAuras 5.18.0

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Pixel Glow pixel asymmetry

https://github.com/user-attachments/assets/1c695118-7f9f-447f-a736-1c61980de77a

### Screenshots

https://github.com/user-attachments/assets/c18eb627-404e-429e-9b69-a778643ec03b

**Comment by dwWei** [comment]
https://github.com/user-attachments/assets/c00c1ccb-2cef-451b-a830-b881892f4631

**Comment by InfusOnWoW** [comment]
That doesn't answer that question at all. Please be more through in writing bug reports.

**Comment by dwWei** [comment]
> 您是否设置了确保 uiscale 允许像素完美定位，并确保您的位置实际落在像素上？
Can Pixel Glow automatically adapt and adjust Pixel based on resolution?
![11 (1)](https://github.com/user-attachments/assets/e181f7ba-6ca8-4025-aebc-7a122099eb46)
![11 (2)](https://github.com/user-attachments/assets/7bb36d83-7cf3-48d7-9fc0-7eb4211ac70e)
