### ISSUE TITLE
Weakauras Classic Fresh

### ISSUE THREAD

**Issue by Smokeem6969** [WeakAuras/WeakAuras2#5557]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

1x WeakAuras/SubRegionTypes/Glow.lua:219: attempt to call field 'glowStop' (a nil value)
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:219: in function `SetVisible'
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:399: in function `modify'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:803: in function `modifyFinish'
[string "@WeakAuras/RegionTypes/Icon.lua"]:628: in function `modify'
[string "@WeakAuras/WeakAuras.lua"]:3280: in function `SetRegion'
[string "@WeakAuras/WeakAuras.lua"]:3345: in function <WeakAuras/WeakAuras.lua:3325>
[string "@WeakAuras/WeakAuras.lua"]:3355: in function `EnsureRegion'
[string "@WeakAuras/WeakAuras.lua"]:1791: in function <WeakAuras/WeakAuras.lua:1649>
[string "@WeakAuras/WeakAuras.lua"]:2010: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1273: in function <WeakAuras/WeakAuras.lua:1232>

[string "@WeakAuras/WeakAuras.lua"]:1391: in function <WeakAuras/WeakAuras.lua:1339>

Locals:
self = Frame {
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 registered = <table> {
 }
 login_squelch_time = 10
 lastArchiveClear = 1732658093
 minimap = <table> {
 }
 historyCutoff = 730
 dbVersion = 73
 migrationCutoff = 730
 features = <table> {
 }
 editor_font_size = 12
 lastUpgrade = 1732658096
 editor_theme = "Monokai"
}
Private = <table> {
 frame_strata_types = <table> {
 }
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 form_types = <table> {
 }
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 centered_types_h = <table> {
 }
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 player_target_events = <table> {
 }
 subRegionTypes = <table> {
 }
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 sound_channel_types = <table> {
 }
 event_prototypes = <table> {
 }
 AtlasList = <table> {
 }
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 trigger_require_types_one = <table> {
 }
 noreset_swing_spells = <table> {
 }
 bufftrigger_progress_behavior_types = <table> {
 }
 author_option_media_controls = <table> {
 }
 chat_message_types = <table> {
 }
 precision_types = <table> {
 }
 pvp_talent_types_specific = <table> {
 }
 item_weapon_types = <table> {
 }
 grow_types = <table> {
 }
 frames = <table> {
 }
 trigger_modes = <table> {
 }
 category_event_prototype = <table> {
 }
 dynamic_texts = <table> {
 }
 character_types = <table> {
 }
 orientation_types = <table> {
 }
 difficulty_info = <table> {
 }
 aura_types = <table> {
 }
 icon_side_types = <table> {
 }
 align_types = <table> {
 }
 main_spell_schools = <table> {
 }
 include_pets_types = <table> {
 }
 Features = <table> {
 }
 check_types = <table> {
 }
 anim_presets = <table> {
 }
 anim_scale_types = <table> {
 }
 group_aura_name_info_types = <table> {
 }
 unit_color_types = <table> {
 }
 weapon_types = <table> {
 }
 environmental_types = <table> {
 }
 orientation_with_circle_types = <table> {
 }
 string_operator_types = <table> {
 }
 mythic_plus_affixes = <table> {
 }
 group_hybrid_sort_types = <table> {
 }
 db = <table> {
 }
 barmodels = <table> {
 }
 load_prototype = <table> {
 }
 actual_unit_types_with_specific = <table> {
 }
 combatlog_flags_check_reaction = <table> {
 }
 group_limit_types = <table> {
 }
 texture_wrap_types = <table> {
 }
 FrameTick = <table> {
 }
 reset_ranged_swing_spells = <table> {
 }
 default_types_for_anchor = <table> {
 }
 regionTypes = <table> {
 }
 AuraEnvironmentWrappedSystem = <table> {
 }
 function_strings = <table> {
 }
 regionPrototype = <table> {
 }
 font_flags = <table> {
 }
 bufftrigger_2_per_unit_mode = <table> {
 }
 cast_types = <table> {
 }
 tick_placement_modes = <table> {
 }
 equality_operator_types = <table> {
 }
 inverse_point_types = <table> {
 }
 maxTimerDuration = 604800
 swing_types = <table> {
 }
 spec_types_3 = <table> {
 }
 AuraWarnings = <table> {
 }
 sound_file_types = <table> {
 }
 subevent_actual_prefix_types = <table> {
 }
 eventend_types = <table> {
 }
 anchor_frame_types = <table> {
 }
 operator_types_without_equal = <table> {
 }
 gradient_orientations = <table> {
 }
 rotated_icon_side_types = <table> {

### WeakAuras Version

weakauras 5.12.9

### World of Warcraft Flavor

Classic Era

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
1x WeakAuras/SubRegionTypes/Glow.lua:219: attempt to call field 'glowStop' (a nil value)
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:219: in function `SetVisible'
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:399: in function `modify'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:803: in function `modifyFinish'
[string "@WeakAuras/RegionTypes/Icon.lua"]:628: in function `modify'
[string "@WeakAuras/WeakAuras.lua"]:3280: in function `SetRegion'
[string "@WeakAuras/WeakAuras.lua"]:3345: in function <WeakAuras/WeakAuras.lua:3325>
[string "@WeakAuras/WeakAuras.lua"]:3355: in function `EnsureRegion'
[string "@WeakAuras/WeakAuras.lua"]:1791: in function <WeakAuras/WeakAuras.lua:1649>
[string "@WeakAuras/WeakAuras.lua"]:2010: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1273: in function <WeakAuras/WeakAuras.lua:1232>

[string "@WeakAuras/WeakAuras.lua"]:1391: in function <WeakAuras/WeakAuras.lua:1339>

Locals:
self = Frame {
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 registered = <table> {
 }
 login_squelch_time = 10
 lastArchiveClear = 1732658093
 minimap = <table> {
 }
 historyCutoff = 730
 dbVersion = 73
 migrationCutoff = 730
 features = <table> {
 }
 editor_font_size = 12
 lastUpgrade = 1732658096
 editor_theme = "Monokai"
}
Private = <table> {
 frame_strata_types = <table> {
 }
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 form_types = <table> {
 }
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 centered_types_h = <table> {
 }
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 player_target_events = <table> {
 }
 subRegionTypes = <table> {
 }
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 sound_channel_types = <table> {
 }
 event_prototypes = <table> {
 }
 AtlasList = <table> {
 }
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 trigger_require_types_one = <table> {
 }
 noreset_swing_spells = <table> {
 }
 bufftrigger_progress_behavior_types = <table> {
 }
 author_option_media_controls = <table> {
 }
 chat_message_types = <table> {
 }
 precision_types = <table> {
 }
 pvp_talent_types_specific = <table> {
 }
 item_weapon_types = <table> {
 }
 grow_types = <table> {
 }
 frames = <table> {
 }
 trigger_modes = <table> {
 }
 category_event_prototype = <table> {
 }
 dynamic_texts = <table> {
 }
 character_types = <table> {
 }
 orientation_types = <table> {
 }
 difficulty_info = <table> {
 }
 aura_types = <table> {
 }
 icon_side_types = <table> {
 }
 align_types = <table> {
 }
 main_spell_schools = <table> {
 }
 include_pets_types = <table> {
 }
 Features = <table> {
 }
 check_types = <table> {
 }
 anim_presets = <table> {
 }
 anim_scale_types = <table> {
 }
 group_aura_name_info_types = <table> {
 }
 unit_color_types = <table> {
 }
 weapon_types = <table> {
 }
 environmental_types = <table> {
 }
 orientation_with_circle_types = <table> {
 }
 string_operator_types = <table> {
 }
 mythic_plus_affixes = <table> {
 }
 group_hybrid_sort_types = <table> {
 }
 db = <table> {
 }
 barmodels = <table> {
 }
 load_prototype = <table> {
 }
 actual_unit_types_with_specific = <table> {
 }
 combatlog_flags_check_reaction = <table> {
 }
 group_limit_types = <table> {
 }
 texture_wrap_types = <table> {
 }
 FrameTick = <table> {
 }
 reset_ranged_swing_spells = <table> {
 }
 default_types_for_anchor = <table> {
 }
 regionTypes = <table> {
 }
 AuraEnvironmentWrappedSystem = <table> {
 }
 function_strings = <table> {
 }
 regionPrototype = <table> {
 }
 font_flags = <table> {
 }
 bufftrigger_2_per_unit_mode = <table> {
 }
 cast_types = <table> {
 }
 tick_placement_modes = <table> {
 }
 equality_operator_types = <table> {
 }
 inverse_point_types = <table> {
 }
 maxTimerDuration = 604800
 swing_types = <table> {
 }
 spec_types_3 = <table> {
 }
 AuraWarnings = <table> {
 }
 sound_file_types = <table> {
 }
 subevent_actual_prefix_types = <table> {
 }
 eventend_types = <table> {
 }
 anchor_frame_types = <table> {
 }
 operator_types_without_equal = <table> {
 }
 gradient_orientations = <table> {
 }
 rotated_icon_side_types = <table> {
```

### Reproduction Steps

Am not sure

### Export String

```Text
1x WeakAuras/SubRegionTypes/Glow.lua:219: attempt to call field 'glowStop' (a nil value)
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:219: in function `SetVisible'
[string "@WeakAuras/SubRegionTypes/Glow.lua"]:399: in function `modify'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:803: in function `modifyFinish'
[string "@WeakAuras/RegionTypes/Icon.lua"]:628: in function `modify'
[string "@WeakAuras/WeakAuras.lua"]:3280: in function `SetRegion'
[string "@WeakAuras/WeakAuras.lua"]:3345: in function <WeakAuras/WeakAuras.lua:3325>
[string "@WeakAuras/WeakAuras.lua"]:3355: in function `EnsureRegion'
[string "@WeakAuras/WeakAuras.lua"]:1791: in function <WeakAuras/WeakAuras.lua:1649>
[string "@WeakAuras/WeakAuras.lua"]:2010: in function `Resume'
[string "@WeakAuras/WeakAuras.lua"]:1273: in function <WeakAuras/WeakAuras.lua:1232>

[string "@WeakAuras/WeakAuras.lua"]:1391: in function <WeakAuras/WeakAuras.lua:1339>

Locals:
self = Frame {
}
event = "PLAYER_LOGIN"
addon = nil
dbIsValid = true
takeNewSnapshots = nil
ADDON_NAME = "WeakAuras"
db = <table> {
 dynamicIconCache = <table> {
 }
 editor_tab_spaces = 4
 displays = <table> {
 }
 registered = <table> {
 }
 login_squelch_time = 10
 lastArchiveClear = 1732658093
 minimap = <table> {
 }
 historyCutoff = 730
 dbVersion = 73
 migrationCutoff = 730
 features = <table> {
 }
 editor_font_size = 12
 lastUpgrade = 1732658096
 editor_theme = "Monokai"
}
Private = <table> {
 frame_strata_types = <table> {
 }
 combat_event_type = <table> {
 }
 regions = <table> {
 }
 frameLevels = <table> {
 }
 form_types = <table> {
 }
 tooltip_count = <table> {
 }
 SmoothStatusBarMixin = <table> {
 }
 pet_spec_types = <table> {
 }
 regionOptions = <table> {
 }
 author_option_classes = <table> {
 }
 grid_types = <table> {
 }
 non_transmissable_fields = <table> {
 }
 absorb_modes = <table> {
 }
 combatlog_spell_school_types_for_ui = <table> {
 }
 miss_types = <table> {
 }
 centered_types_h = <table> {
 }
 talent_types = <table> {
 }
 reset_swing_spells = <table> {
 }
 spec_types_all = <table> {
 }
 player_target_events = <table> {
 }
 subRegionTypes = <table> {
 }
 array_entry_name_types = <table> {
 }
 combatlog_spell_school_types = <table> {
 }
 blend_types = <table> {
 }
 text_automatic_width = <table> {
 }
 custom_trigger_types = <table> {
 }
 group_types = <table> {
 }
 subRegionOptions = <table> {
 }
 text_rotate_types = <table> {
 }
 spec_types = <table> {
 }
 anim_ease_types = <table> {
 }
 item_slot_types = <table> {
 }
 multiUnitUnits = <table> {
 }
 anim_color_types = <table> {
 }
 loaded = <table> {
 }
 sound_channel_types = <table> {
 }
 event_prototypes = <table> {
 }
 AtlasList = <table> {
 }
 classification_types = <table> {
 }
 unit_types_bufftrigger_2 = <table> {
 }
 trigger_require_types_one = <table> {
 }
 noreset_swing_spells = <table> {
 }
 bufftrigger_progress_behavior_types = <table> {
 }
 author_option_media_controls = <table> {
 }
 chat_message_types = <table> {
 }
 precision_types = <table> {
 }
 pvp_talent_types_specific = <table> {
 }
 item_weapon_types = <table> {
 }
 grow_types = <table> {
 }
 frames = <table> {
 }
 trigger_modes = <table> {
 }
 category_event_prototype = <table> {
 }
 dynamic_texts = <table> {
 }
 character_types = <table> {
 }
 orientation_types = <table> {
 }
 difficulty_info = <table> {
 }
 aura_types = <table> {
 }
 icon_side_types = <table> {
 }
 align_types = <table> {
 }
 main_spell_schools = <table> {
 }
 include_pets_types = <table> {
 }
 Features = <table> {
 }
 check_types = <table> {
 }
 anim_presets = <table> {
 }
 anim_scale_types = <table> {
 }
 group_aura_name_info_types = <table> {
 }
 unit_color_types = <table> {
 }
 weapon_types = <table> {
 }
 environmental_types = <table> {
 }
 orientation_with_circle_types = <table> {
 }
 string_operator_types = <table> {
 }
 mythic_plus_affixes = <table> {
 }
 group_hybrid_sort_types = <table> {
 }
 db = <table> {
 }
 barmodels = <table> {
 }
 load_prototype = <table> {
 }
 actual_unit_types_with_specific = <table> {
 }
 combatlog_flags_check_reaction = <table> {
 }
 group_limit_types = <table> {
 }
 texture_wrap_types = <table> {
 }
 FrameTick = <table> {
 }
 reset_ranged_swing_spells = <table> {
 }
 default_types_for_anchor = <table> {
 }
 regionTypes = <table> {
 }
 AuraEnvironmentWrappedSystem = <table> {
 }
 function_strings = <table> {
 }
 regionPrototype = <table> {
 }
 font_flags = <table> {
 }
 bufftrigger_2_per_unit_mode = <table> {
 }
 cast_types = <table> {
 }
 tick_placement_modes = <table> {
 }
 equality_operator_types = <table> {
 }
 inverse_point_types = <table> {
 }
 maxTimerDuration = 604800
 swing_types = <table> {
 }
 spec_types_3 = <table> {
 }
 AuraWarnings = <table> {
 }
 sound_file_types = <table> {
 }
 subevent_actual_prefix_types = <table> {
 }
 eventend_types = <table> {
 }
 anchor_frame_types = <table> {
 }
 operator_types_without_equal = <table> {
 }
 gradient_orientations = <table> {
 }
 rotated_icon_side_types = <table> {
```

**Comment by emptyrivers** [comment]
Err, 5.12.9 is many revisions out of date. Consider updating to the latest version and trying again.

**Comment by InfusOnWoW** [comment]
Yeah, we need better information e.g. your exact settings and an up to date WA version.
