### ISSUE TITLE
All Was gone on log in

### ISSUE THREAD

**Issue by ragexlukii** [WeakAuras/WeakAuras2#5559]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

Logged on all Was are gone how can i restore?

### WeakAuras Version

WeakAuras 5.17.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Everything

**Comment by InfusOnWoW** [comment]
If you login and your WeakAura's are missing, go to the World of Warcraft\_retail_\WTF\Account\<ACCOUNTNAME>\SavedVariables folder and check the WeakAuras.lua file. If it is empty, check the WeakAuras.lua.bak file. If that one has content, MAKE A BACKUP of the .bak file, then close the game, delete WeakAuras.lua and rename WeakAuras.lua.bak to WeakAuras.lua. If WeakAuras.lua.bak was also empty,  you will need to to rely on backups or remake your Auras. Not enough space on your hard drive is a common reason for losing your WeakAuras.

*Window's hides file extensions by default so you will need to turn these on which you can do by going to Control Panel > Appearance and Personalistion > File Explorer Options > View tab in the new window and untick Hide extensions for known file types 

If you have not made backups or don't use the WA Companion (it makes backups for you) then as a last resort you can try using the `/wa repair` command, which will attempt to replace your saved variables with the most recent migration snapshot.
