### ISSUE TITLE
Buffed condition for aura triggers

### ISSUE THREAD

**Issue by sragia** [WeakAuras/WeakAuras2#556]
**Is your feature request related to a problem? Please describe.**
Basically at the moment if you create Aura trigger that is always active (Show On - Always)  there's no real condition that you can use to determine if unit is actually buffed or not. 
**Describe the solution you'd like**
Condition Buffed that is true/false, similar how we have On Cooldown for CD Progress triggers.
**Describe alternatives you've considered**.
Can try using remaining time but when not buffed it seems to be math.huge or something, basically can't use remaining time <= 0. so have to do something like remaining time > buff max duration that you type in yourself.

**Comment by asakawa-k** [comment]
I agree this would be a nice addition ("show on" as added to aura triggers after Conditions went in) but a workaround for now is to use `total duration = 0`

**Comment by sragia** [comment]
good point, hadn't tried that out. However that doesnt work for auras that don't have duration, for example Consecration

**Comment by asakawa-k** [comment]
Yeah. In those cases I guess the workaround is imply using 2 triggers, one for buffed and one for missing.

**Comment by InfusOnWoW** [comment]
Implemented by MrBuds
