### ISSUE TITLE
Add trigger support for softinteract

### ISSUE THREAD

**Issue by gjfLeo** [WeakAuras/WeakAuras2#5560]
There's "Soft Enemy" and "Soft Friend" in unit info triggers. Can we support "softinteract" as well? It'll be useful when tracking cooldowns /items count related with GameObject, such as [Overload Sporefused Herb](https://www.wowhead.com/spell=438961/overload-sporefused-herb). 

Considering that the "softinteract" unit may be not a creature, maybe more works required?

**Comment by emptyrivers** [comment]
hmm, i wasn't convinced when i added softfriend/softenemy, and im still not convinced today. Like, I get the use case, i even made [something similar](https://wago.io/empowered_nodes_tww) myself, but I just don't see how `select(6,UnitGUID("softinteract")) == "1337h4x0rz"` is so broadly useful and/or annoying to implement in custom code to warrant supporting in the builtins.

As you mention, softinteract is usually going to be one GameObject or another, and most of the unit info triggers aren't able to glean interesting information about an object. Did you have a use case in mind beyond just "is my soft interact target an herb i can overload"?
