### ISSUE TITLE
AI-powered Custom Weak Aura Creator: Reinforcement Fine-Tuning on wago.io Data

### ISSUE THREAD

**Issue by Trickhamster** [WeakAuras/WeakAuras2#5570]
**Is your feature request related to a problem? Please describe.**
A lot of WoW players love using WeakAuras but don’t know how to code, which makes creating custom WAs super frustrating. OpenAI just announced Reinforcement Fine-Tuning (coming Q1 2025), which lets you boost an AI’s performance in specific areas by training it with your own data—like the wago.io database.

**Describe the solution you'd like**
It’d be amazing if the WeakAuras/Method/wago.io team could use this new tech to offer a paid premium service where players can just ask the AI to help them make custom WeakAuras. Imagine typing what you want, and the AI spits out a WeakAura that actually works—no coding required. This would make life easier for players, and it would be an awesome way for them to support you.

**Comment by InfusOnWoW** [comment]
Not interested in that.

**Comment by Trickhamster** [comment]
This approach seems like the ideal way for the team to generate consistent revenue. It aligns perfectly with the ToS and ensures a steady stream of guaranteed monthly payments. After all the effort and dedication the team has poured into this project over the years, I believe you truly deserve to kick back and let AI handle the grunt work while maintaining a reliable income. It doesn't appear significantly more challenging to set up than something like the Wago UI package website, but the potential is enormous.

The new o1 model can create pretty complex WeakAuras already and with a little bit of fine tuning it will get much, much better. Would be a waste not to cash in on this, honestly.

**Comment by mrbuds** [comment]
You are free to create that service if you want. Also note that WeakAuras & Wago are different entities/persons.
