### ISSUE TITLE
Dragging the Scroll Bar for code fields causes inverted scrolling

### ISSUE THREAD

**Issue by potat0nerd** [WeakAuras/WeakAuras2#5577]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When moving my mouse upwards while dragging I expect the field to scroll up, but instead it scrolls down

### WeakAuras Version

WeakAuras 5.17.5

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

Create new aura, write at least 5 lines of code, try to scroll with the mouse

### Screenshots

https://streamable.com/zs1udh

**Comment by InfusOnWoW** [comment]
That control is a standard wow ui control. We cannot control the behaviour in that much detail without major hacks. And scrolling that widget is simply not important enough to consider major hacks.
