### ISSUE TITLE
SHIFT-click modifier for larger nudge increments

### ISSUE THREAD

**Issue by kitsunekyo** [WeakAuras/WeakAuras2#5579]
**Is your feature request related to a problem? Please describe.**
Followup to #948

**Describe the solution you'd like**
I often find myself wanting to move a weakaura or group on an axis. The nudge buttons help but I get rsi from all the clicks needed for larger position changes. 

The magnetic alignment helps, but requires a relative element (or a positioning helper)

**Describe alternatives you've considered**
### Shift + Click the nudges to move by 10px
- known from other software
- builds on existing feature

**Comment by InfusOnWoW** [comment]
I tested a change adding the Shift modifier to the buttons, and didn't like it. We already use Shift to temporarly hide the mover/resizer frame, thus overloading that with the buttons didnÄt feel good.

**Comment by kitsunekyo** [comment]
I did not know about the shift modifier already being used for something else. Totally makes sense to not overload it with functionality then. Thank you.
