### ISSUE TITLE
Click() action not working in 5.18.1

### ISSUE THREAD

**Issue by hollo6** [WeakAuras/WeakAuras2#5588]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

I have several WAs that use :Click() (had to convert long macros to these) and they are now throwing a LUA error and not working.
(I know it looks like it is an issue with tdBattlePetScript but it is not, I have checked that the WA runs when I press the key and also the action it is supposed to do is working if not called from the WA.)
This is a new issue in version 5.18.1, I rolled back to 5.18.0 and it still works.

### WeakAuras Version

5.18.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

EU

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
2x [ADDON_ACTION_BLOCKED] AddOn 'tdBattlePetScript' tried to call the protected function 'UseAbility()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseAbility'
[string "@tdBattlePetScript/Extension/Actions.lua"]:62: in function `fn'
[string "@tdBattlePetScript/Core/Action.lua"]:31: in function <tdBattlePetScript/Core/Action.lua:27>
[string "=(tail call)"]: ?
[string "@tdBattlePetScript/Core/Director.lua"]:58: in function `Action'
[string "@tdBattlePetScript/Core/Director.lua"]:53: in function `Action'
[string "@tdBattlePetScript/Core/Director.lua"]:24: in function `Run'
[string "@tdBattlePetScript/UI/PetBattle.lua"]:314: in function `OnAutoButtonClick'
[string "@tdBattlePetScript/UI/PetBattle.lua"]:70: in function <tdBattlePetScript/UI/PetBattle.lua:69>
[string "=[C]"]: in function `Click'
[string "return function() if tdBattlePetScriptAutoButton and (tdBattlePetScriptAutoButton:IsEnabled()) then tdBattlePetScriptAutoButton:Click() elseif ((not (tdBattlePetScriptAutoButton and (tdBattlePetScriptAutoButton:IsVisible()))) and LFGListFrame:IsVisible()) then LFGListFrame.SearchPanel.RefreshButton:Click() end"]:1: in function <[string "return function() if tdBattlePetScriptAutoB..."]:1>
[string "=[C]"]: in function `xpcall'
[string "@WeakAuras/WeakAuras.lua"]:3854: in function `PerformActions'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:1083: in function `Expand'
[string "@WeakAuras/WeakAuras.lua"]:4781: in function <WeakAuras/WeakAuras.lua:4773>
[string "@WeakAuras/WeakAuras.lua"]:4865: in function <WeakAuras/WeakAuras.lua:4831>
[string "@WeakAuras/WeakAuras.lua"]:4975: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:974: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:903: in function `func'
[string "@WeakAuras/GenericTrigger.lua"]:845: in function <WeakAuras/GenericTrigger.lua:841>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```

### Reproduction Steps

1. create a macro that runs a WA, mine is just this: /run WeakAuras.ScanEvents("MACRO_TD")
2. create a WA that runs a function when above macro is pressed. I tested with my WA pruned to only this: tdBattlePetScriptAutoButton:Click()
3. press the above macro (I have only tested with this one so this particular repro needs td addon installed and being in a pet battle)

### Last Good Version

5.18.0

### Export String

```Text
!WA:2!1rvVUnUrq4tWfharWLlQWi)bebFWxoJayC2bXiiDIksWoq2shjD0LabqVK7qYnMC3n7Uu2YLcP4QDFAuDsJAsVFcimYtGFe8tqMLuojiiwnAMbZoFZ8nFdBnODrBAB67(CLO0KZ4GA0Pbdp6K(QlhLKObtRvuMwMtMhaxA2ABPA(dXj84mHASGXnr96FsqFpzN)vUHjcvbXekdnScyTxl5ZJl1grHnJtLuIb8Gza3ChPeJsmS4jmQjZTl6QiXgMGRpWtBikZGOMNkFHH6smMCymy8JvmPXMTBPXi4FtVCw85VAhpTOKtLF5rCdOsiXW0Uu6iUE6eGCE3sfrp9yGYit9T5PN2LPouO47kstVMkcBq6SfOzDHYCzCMXjkb)tNDWnfGwtsHqZCj4n27OtcwIPUoAMATX(AkzHrXstbL(zVuT28DTVRudHK8liZ1gvjG4GDKDw3)17UNBjcvKLgb1skevMKeGWOoS)WXdoDORfZQ3x2UUgrAHk6qGKFSGcNTQPVRBRkNh8YyuWZUeOvo30lJy6CCt)TqlH88JOAN70Lr17HXkiHDPN)4(dh(3b9XwGD5QWED9dc9d66f0exV44U98gfg8TECcoZo39p9uD)SW6BhNZU3ATMwSttgobFwsjVEd)Q6QTJJcmLkEhlL0b40Rl5Rzmh5hy1cZGGgFBX)TNi36XLBfcAisPWzYx(4jLdPK45Hj5cHk7AnKN0OMDhfem6y3eb3iF(af7QoVPKqXYr6eeSezfpi1km)4nR2(w0nIeFEQYQtCZfe6axn7kytVIYCdZXfj54nR654fNt0ARvKHKJdS1CHfeFm9p6wDgHkU4TnNxBSuvJHLRCnyRFlEGGNBJK1NeolUqOOtue5IjRnUMWzf1IOdQE2GQTD5coCdq0GVrb8ut2tV9bzwTarPHybQ9xyZXIt1i3ccJJVTAu14Nw9MkVkF0CZ)Be5lECovQGyMgXyJLOMbO1NZ)Y7j)K)3N0yuTJ8lE8ksNJIlwCOjtb6mroDU6NqHnlzU7W(dcwAeXZWHbH8dB97)Xwm6nxfwqIvcux2z)9lz0vSz)O0TOyYE)8KvjkuQIucUn34(MVHnWgYYar(9863)K1RIFOzv8Ppjc5PewkUbf5c13Tb(Bvtk9Qd0QvRnwA5swZYzfJ3mcONZ9m7NG4K8VVPj)126OVA39(6DFD7z)5B)Rp
```

**Comment by InfusOnWoW** [comment]
That's entirely custom code and has nothing to do with WA.

**Comment by hollo6** [comment]
But it's still working in 5.18.0 and not in 5.18.1 ?

**Comment by InfusOnWoW** [comment]
Ah, someone pointed to the change that broke your aura. This is an unintentional breakage, which we aren't going to fix.

You can simply create a macro that directly runs "tdBattlePetScriptAutoButton:Click()", there's zero need to use WA for that.

WA is not meant to be used like you are using it.

**Comment by hollo6** [comment]
I have to use these WAs for macros that wouldn't fit in 255 characters and I have no way of shortening them further.
I just trimmed this one down to this one function to test and show that this is where the problem is.

**Comment by InfusOnWoW** [comment]
That's not an inteded use case for WA.

**Comment by hollo6** [comment]
Then could you pelase explain how I could click a button with a WA? Or give an example?

**Comment by Stanzilla** [comment]
As Infus said, you're not supposed to click things with WA, sorry mate.
