### ISSUE TITLE
Equipment Set Trigger should use C_EquipmentSet.GetEquipmentSetIDs()

### ISSUE THREAD

**Issue by InfusOnWoW** [WeakAuras/WeakAuras2#559]
C_EquipmentSet.GetEquipmentSetIDs() apparently returns the ids that we should check, instead of iterating.

**Comment by asakawa-k** [comment]
e.g. <https://wago.io/CurrentEquippedSet>

**Comment by InfusOnWoW** [comment]
Done that now.
