### ISSUE TITLE
Interface/AddOns/WeakAuras/SubscribableObject.lua:1: attempt to index global 'WeakAuras' (a nil value)

### ISSUE THREAD

**Issue by JulianNorton** [WeakAuras/WeakAuras2#5590]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

WeakAuras only addon running

```
Message: Interface/AddOns/WeakAuras/SubscribableObject.lua:1: attempt to index global 'WeakAuras' (a nil value)
Time: Sat Dec 21 12:02:26 2024
Count: 1
Stack: Interface/AddOns/WeakAuras/SubscribableObject.lua:1: attempt to index global 'WeakAuras' (a nil value)

Locals:
```
and about 50 other errors

### WeakAuras Version

WeakAuras 5.18.1

### World of Warcraft Flavor

Classic Era

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Lua Error

```Text
Message: Interface/AddOns/WeakAuras/WeakAuras.lua:30: attempt to index local 'WeakAuras' (a nil value)
Time: Sat Dec 21 12:04:27 2024
Count: 1
Stack: Interface/AddOns/WeakAuras/WeakAuras.lua:30: attempt to index local 'WeakAuras' (a nil value)

Locals:
```

### Reproduction Steps

1. Log into World of Warcraft Classic

### Last Good Version

WeakAuras 5.17

### Screenshots

![image](https://github.com/user-attachments/assets/13075ebd-50c1-4874-9fd3-588ffbc180ef)
![image](https://github.com/user-attachments/assets/3ba7dd2b-b7cc-4a85-90f7-3dc2d5ecde7a)

### Export String

```Text
[WeakAuras.zip](https://github.com/user-attachments/files/18219371/WeakAuras.zip)
```

**Comment by InfusOnWoW** [comment]
That appears to be a broken installation, try reinstalling the addon.

**Comment by mrbuds** [comment]
also check if your harddrive isn't full
