### ISSUE TITLE
"Not Skyriding" seems to be broken

### ISSUE THREAD

**Issue by tbellomy** [WeakAuras/WeakAuras2#5591]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When selecting "Not Skyriding" in load aura will not ever load after this selection. Just noticed after 12/21/2024 update.

### WeakAuras Version

5.18.1

### World of Warcraft Flavor

Retail (Default)

### World of Warcraft Region

US/NA

### Tested with only WeakAuras

I got this issue with only WeakAuras enabled

### Reproduction Steps

1. Go to options.
2. Select any aura.
3. Go to load.
4. Select Skyriding, twice, until "not Skyriding is the highlighted option.
5. Aura will not load when Skyriding is not in effect.

### Last Good Version

5.17...

**Comment by emptyrivers** [comment]
Your repro steps don't work for me. This aura, which has the load condition "Not Skyriding" selected, behaves correctly:
```
!WA:2!DrvZUTTrqylRcyaEOWwn1OXihcsQtdYHcxJQa0Etuwk2fYsUumXUafqAj5qYTMAx2DxkB5BrNYz9cuaDONAVOl9UFcie6tGp0ha)e0zxsP8Joim)UZ3m8BMkTRnQwqTG3985uFoRppt4dpAdX19cdLGQYcsWVLjvqWPKR389ku2MIjRdH5hZfNXPmLxZwDDB5S0NZtc4xX6FfnfgE7k1wbrqSTUqdNQe0Oiqi)8Njkf)trMe6sgbdNrYeegkj3Z77Rx)GdpWbgd4ZFmqsuX3jZ8m6NjGq61o9pRvNotLPqsYjbsR1U7NfIUxmOzJ(Ud672WX1oJrvEPjKjGWXualB1KuWrxWdNhaEykUObXXT6Cw7x3zwgReDwP7q8v0XGBH(P8a4V24ESPbbJK8gSvOC2FC)LaK2aXIVYHOO84zegDKwI9shPIiuTVfisOVsaSiv8w57zZ4myzaIaDud04ribCifiNQdvJN89ThrOS25FnMq((5pl)BYFE((EHugvg)PMXgrsu6heINJtdhicFz5pUB(ElrvpI)LrcEgl4DpiTMcUwnqgtWpqxu(jn9HgJM)c5ce(dKLc57pBTVNSVmD7pi9M8eU4NQuPs17kScjHgAHDJx72l9lmgjzkUEE4FonqfB3avVVOq0RHaJX3USGs9lLW5wJFn1JgojFR5cUc7mx0OD3EDBLVNaBkDmZnb6BGrv83SYoGPs3UTGEZJ)5msaovip219JA8vvAPX2vCrW5cs60ZlfkaWyQK6Ladl75pG2NUZjD72YzGDpx3EN6CYRo2D56s3NEd8WYo6IpQoAVgYwVx725KUT(VLrj8RAlGFpdy(to7Zo4BpSEr3PDCR(VJkPjvNQ10zV0ltP4SEJbbYRNRn3XqT(YfA5vT2mTsZ1JMBXDTxTYsSjY1GZ8YXu)lzGuw1KyFFscu1wlgBm0HIo3XunBCkbIyVyGgfRERDcNe8M0TXcmah2rCMGgqzrXEk8nyQDDgLLOOwo(jePC38F1YwVUuiGZkTGj7gLxBmhFI)utuw8CHHxB2pSCijPXKQhMrdwCZK6NwVNZnhmz8ckRG4IbADxQGhjWMQ4o3lE0gBk0l14UXlZFQv(lSSX9jLL9nC(OkoVNinxX9hxSH)vv(7)5j0G5oa(ypTE9F47wekWlj4cnsSQMwdHzZY7D4nc8iam05kdT((csqBD4Aq71VPtRwD9Wv9qAKLGY01aItFWQdMAo(rujbPDbXlXvhm9EPgaBnxFHGwipDvcdNTEPlFRAYdpcgxB8)EX)d
```
When you are on a skyriding mount, can you use the following command and tell me what prints in your chat window?
```
/dump UnitPowerBarID("player")
```

**Comment by InfusOnWoW** [comment]
There's a known issue in the game where the game was horrible confussed about skyriding. Where even login out/in doesn't reset the state correctly.

That's not a WA issue though, if you disable WA you'll see the game displaying the game's skyriding ui.

(And I'm pretty sure that you are encountering this bug.)
