### ISSUE TITLE
Triggers changing itself 

### ISSUE THREAD

**Issue by rea111** [WeakAuras/WeakAuras2#567]
**Describe the bug**
All my triggers on weakauras just changed itself to on cooldown. Even if i try to import my backed up string it screws up the trigger for them on import as well. Asked on weakaura discord and was told that it was a migration problem, and was asked to make a ticket here.

**Do you have an error log of what happened?**
No

**To Reproduce**
Import any strings with offcooldown/oncooldown trigger

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.6.6-11-g2837804

**Was it working in a previous version? If yes, which was the last good one?**
2.6.6

**Comment by InfusOnWoW** [comment]
I think this is fixed in the next alpha.
