### ISSUE TITLE
Allow "mouseover tooltip" on TSU clones. 

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#569]
**Is your feature request related to a problem? Please describe.**
Making 

**Describe the solution you'd like**
A use-case would be making a "Full scan" + "clone all" type trigger but with the ability to blacklist. This would require the use of TSU but there's currently no way to display mouseover tooltips on TSU clones. 

**Describe alternatives you've considered**
It's very low priority. I'm not sure there are alternatives but it's *super* rare that anyone wants this.

**Comment by InfusOnWoW** [comment]
The commit message explains the various potential tooltips.
