### ISSUE TITLE
Possibility to override size that icon has reserved in a dynamic group

### ISSUE THREAD

**Issue by lassevk** [WeakAuras/WeakAuras2#572]
I use a lot of dynamic groups with icons flowing out towards the right. A spell "queue" for instance is managed in this way.

It would be nice to show a buff icon below or above such a spell icon and I can do that today by adjusting the offset of the buff icon so that it is positioned below the previous icon inside the same dynamic group.

However, space is also reserved for this buff icon in the dynamic group, creating a gap to the next "real" icon.

I'd like to have 1 new checkbox + 1 new size slider/value, that is relevant for icons inside dynamic groups. This checkbox would be "override dynamic group size" and the slider/value would override the width or the height, depending on the type of dynamic group (ie. horizontal then it would override the width, etc.)

This way I could set the icon to have size 24x24, have an offset which positions it neatly below the left corner of the previous icon inside the same dynamic group, and remove the gap to the next real icon by saying that it should not have any size at all reserved in the dynamic group. The slider probably makes sense as a size offset and not an absolute size, so that I can also remove padding.

![image](https://user-images.githubusercontent.com/1311683/43534776-7aa12522-95b8-11e8-83ad-953df3964ec5.png)

**Comment by InfusOnWoW** [comment]
That's out of scope for dynamic groups. You are better of handling the positioning of your auras on your own. Or you can make the buff icon not part of the dynamic group and instead attach it to the main icon with the attach feature..

**Comment by lassevk** [comment]
While I won't dispute the scope, I don't understand how I can attach one icon to another since it seems I have to pick a frame, and the whole dynamic group has a frame, whereas the individual icons doesn't seem to. Can you elaborate on how I would accomplish this?

**Comment by InfusOnWoW** [comment]
The individual auras do have their own frame, it seems you need to enter the frame name though by hand.

**Comment by lassevk** [comment]
OK, do you know how the frame name is calculated, for an icon in a dynamic group?

**Comment by emptyrivers** [comment]
`WeakAuras:AuraName` resolves to an anchor on `AuraName`

**Comment by lassevk** [comment]
Nice! Thanks, this worked nicely!

Exactly what I wanted to have!

**Comment by lassevk** [comment]
Just one last question, am I right in understanding that if I attach A to frame B, and B isn't visible, A won't be visible either? Testing seems to indicate this, I just created a custom trigger that returned true and the icon disappears if the one it was attached to disappears.

Will this be more costly than reimplementing proper triggers for the attached icons?

**Comment by InfusOnWoW** [comment]
There's a option "Set Parent" which controls whether the attached region visibility (and a few other properties) are inherited from the parent. This tells WoW that two frames should be positioned relative to each other, it's probably the fastest way to achive that positioning.
