### ISSUE TITLE
[Aura Updating] Font category

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#577]
One request was to leave everything alone but fonts. Investigate if worth adding as own category

**Comment by emptyrivers** [comment]
As in, the fonts on text fields on icons/aurabars? Hmm. This wouldn't actually be difficult, but that way lies adding update_categories for everything under the sun. I'm not *completely* against this, but I think it's not important enough to bother with. You can edit the fonts easily in any case, thanks to the merged display options in groups.

**Comment by emptyrivers** [comment]
Of course, convenience was always the entire point of this feature in the first place. The real question is whether or not it's worth adding fonts as an update_category before the import/update UI is rewritten (if it ever is) to use the full Options pane, which I think would provide much more space for detailed merge strategies, update preferences, complex categories, and the like.

**Comment by InfusOnWoW** [comment]
I don't think it's worth it.

**Comment by emptyrivers** [comment]
Yeah, this is just a little bit too niche to bother with specifically.
