### ISSUE TITLE
[Aura Updating] Design Discussion

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#579]
There are a few open questions about we want the tooltip to work/look like, my current draft is at http://jsfiddle.net/Stanzilla/b15kmr8h/38/

Open questions:

Are we happy with the text?
~~Do we want to check `Create a Copy` by default?~~ Done - Rivers
Are our categories fine/enough/clear?

**Comment by Stanzilla** [comment]
[ ] Make sure we are showing the custom code warning only when the update contains custom code and that for both single and group auras

**Comment by amiyuy** [comment]
1. When importing a duplicate, could "Import Group" instead say "Import as Copy" like the Update dialog when you choose "Create a Copy"?
2. If I check "Size & Position" or change checks in the other checkboxes it would be nice if it auto-selected the Update radio.
3. Was the name of the group that is being modified removed?  It was cluttery, but if I've renamed it, I'd like to see which it is before I choose to overwrite it.  Maybe only show if the name is different?
Or change text to something like "This import is a modification to [Group Name]:"

**Comment by Stanzilla** [comment]
I like Ami's idea, 

group: `This import is a modification to your group %color %name:`
single: `This import is a modification to your aura %color %name:`

**Comment by emptyrivers** [comment]
Alright. What color? WeakAuras purple, like in the first line?

**Comment by Stanzilla** [comment]
I'd say yes, also I'm no longer quite fond of that color but consistency etc.

**Comment by Stanzilla** [comment]
Currently when importing a group that is completely new it also shows "Import as Copy" on the button, do we want that?

**Comment by emptyrivers** [comment]
@amiyuy requested it, it should be an easy revert if you decide against it.

**Comment by emptyrivers** [comment]
Oh, wait nvm

**Comment by Stanzilla** [comment]
![wow_2018-08-12_02-39-47 fw](https://user-images.githubusercontent.com/75278/43997394-308579dc-9dda-11e8-8c3f-17a0b85ec080.png)
![wow_2018-08-12_02-39-47](https://user-images.githubusercontent.com/75278/43997395-35a63898-9dda-11e8-976a-65a90962e90c.png)


left or right?

**Comment by emptyrivers** [comment]
@Stanzilla those images are identical.

**Comment by emptyrivers** [comment]
Ah, wait I see the difference now. The second one is preferable imo.

**Comment by emptyrivers** [comment]
![old](https://i.imgur.com/pjw2QNF.png)

![new](https://i.imgur.com/td3IaUA.png)
First image is behavior on `master`, second are some local changes. @Stanzilla what do you think?
