### ISSUE TITLE
Deleting an aura doesn't cancel pending condition checks

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#582]
Reproduced on 2.6.6 and the current tip of master.

To reproduce:

1. Create any aura with a remaining time condition. with any property change.
2. Activate the aura.
3. Delete the aura through the options pane.
4. Observe this error, at the moment when the remaining time should have triggered the condition check (e.g. at 9 seconds of remaining time, if you had set the remaining time condition to < 9 seconds):
```
2x WeakAuras\WeakAuras-@project-version@.lua:731: attempt to index field '?' (a nil value)
WeakAuras\WeakAuras-@project-version@.lua:731: in function `func'
Ace3\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>
```

**Comment by InfusOnWoW** [comment]
Should be fixed now.
