### ISSUE TITLE
regarding hybrid sorting rename issue

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#583]
continues https://github.com/WeakAuras/WeakAuras2/issues/546

**To Reproduce**
1. put 3 auras in a dynamic group and enable hybrid sorting
2. check two of them to be listed first
3. export string
4. delete unchecked one
5. import string (choose update)
6. rename unchecked one

it causes unchecked one to be checked

**Comment by emptyrivers** [comment]
This should be fixed now.
