### ISSUE TITLE
WAs stack does not appear in the correct order/strata (since pre-patch)

### ISSUE THREAD

**Issue by MarioTheMoonSnail** [WeakAuras/WeakAuras2#588]
I wanted to post the problem on wowace but after several trys the site always responded with failing errors and I gave up so I give github a try.

**Describe the bug**
I want to create a stack of WAs for each of my skills to show the CD, the Aura and to be visually appealing aswell. I made a stack of 4-6 Auras per skill. I put them in order from top to bottom (1=top=background; 6=bottom=foreground - Just to get that possible mistake out of the way)
Here is what I did:
1. Texture: a black circle. Just as a visual extra for my WeakAura
2. Progress Texture: a white circle. It shows the CD of the skill and fills up clockwise. It's a bit bigger than the following WAs to appear as a ring around them
3. Icon: The icon of the skill. Always active.
4. Icon: Desaturated Icon. Active, when skill is on CD to show additional visual information.
5. Progress Texture: a class-colored circle. It shows the buff/debuff duration.
6. Text: a text that counts down the CD when it's ready in 30seconds or less

Now the issue comes into play:
With every login or /reload the WeakAuras order in wrong positions. So the progress texture for the CD (no.2) is on top or even the black circle, that is supposed to be the background.
A temporary solution for this problem, that I found: Simply drag any WeakAura in that group for an inch and put it back were it belongs. Do that 2 times and this group appears as it should appear. Repeat that for every group and it is fixed. - Until the next /reload or logout/login. 
For a guild member it even happens with combat start or loading screens when using portals.

**Do you have an error log of what happened?**
After activating "/console scriptErrors 1" and reloading, I had some errors, but after disabling every addon except for WeakAuras2, no error appeared on screen.

**To Reproduce**
As I mentioned above, every new login or /reload does trigger this issue.

**Screenshots**
Please read the screenshot descriptions for additional info on them.
https://imgur.com/a/CO0ofNK

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
As mentioned above, yes. I did try out many combinations, as well as diabling everything except WeakAuras.

**Which version of WeakAuras are you using?**
I am using version 2.6.6.

**Was it working in a previous version? If yes, which was the last good one?**
It was working before the pre-patch. So every 2.6.x version was broken and I tried some BfA-Beta versions on live, they had the same mistake. 2.5.x version do not even load anymore with 8.0, so I could not try my WeakAuras with that.

Here are my Weak Aura Groups

EDIT: Here are wago-links, as I now found the motivation to create an account there.
BM-Hunter Basic https://wago.io/BJvmJpWrm
BM-Hunter Damage 1 https://wago.io/SJZrJ6-HQ
BM-Hunter Damage 2 https://wago.io/HkHDJpbSQ
BM-Hunter Utility https://wago.io/S1cp0n-SQ
All-Class Basic https://wago.io/HJyjJTZHQ

**Comment by asakawa-k** [comment]
You didn't actually mention the strata settings you were using. 
However I wonder, are you using Masque (or maybe other skinning addons)? I have noticed Masque specifically has messed with frame level since 8.0.

(As an aside, I would recommend sharing a wago.io link rather than such a massive string.)

**Comment by MarioTheMoonSnail** [comment]
Thanks for response. Yes, I forgot to add my strata settings, when reposting this one. Had to write everything again. Everything is set to "inherited".

And yes, I use Masque with the plugin Masque: Cirque - But as I said in my post, I deactivated everything but WeakAuras and the problems still happen.

**Comment by Rehok** [comment]
Inherited can be finicky due to the loading process, Set Frame Strata in the order you want them to appear so low for last etc.

**Comment by MarioTheMoonSnail** [comment]
I mean, I understand you saying that, but way has it worked before, but it is broken after the pre patch. If noone also has this issue and there really is no better solution, I will rearrange it to better frame stratas.

**Comment by MarioTheMoonSnail** [comment]
I'm closing this issue then, because I'm changing the frame strata right now, so it should work, whatsoever. Thanks again.
