### ISSUE TITLE
Change Aura Size based on Aura-Type

### ISSUE THREAD

**Issue by Reloe** [WeakAuras/WeakAuras2#592]
Would be nice to be able to change aura sizes within a group based on their Type.
Users are lazy and may not use the workarounds of selecting them individually etc.
For example if you have Icons and Progress Bars in the same group, those naturally have very different Width and Height and people might want to change the Size of the Icons without touching the Progress Bars.

**Comment by InfusOnWoW** [comment]
What's the use case for changing the size of all icons that is not covered by the group scaling option?

**Comment by Reloe** [comment]
group scaling option would also increase/decrease the size of Progress Bars in this example. I agree though, >90% of the time the group scaling would probably be enough

**Comment by InfusOnWoW** [comment]
So what's the remaining 10% use case? In which case would you want that?

**Comment by Reloe** [comment]
in my Raid/Dungeon Packages I use Icons, texts and Progess Bars. 
All Icons have the same Size, but Progress Bars are independant of that. So there are Users that are ok with the size of the progress Bars, but they want to change Icons.

**Comment by InfusOnWoW** [comment]
But if you increase the size of all icons, don't they start to overlap?

**Comment by Reloe** [comment]
oh probably should've mentioned that its in a dynamic group.

**Comment by InfusOnWoW** [comment]
I think that's too fringe and there's a workaround of selection all icons manually.
