### ISSUE TITLE
can't move group with only text-auras inside

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#596]
**Describe the bug**
group can't be moved if only text auras are inside

**To Reproduce**
try to move group with wa from below

**Which version of WeakAuras are you using?**
latest master version

**Additional context**
it works in dynamic groups with text just fine or groups with icons

```dutJdaGAkjEnLsZuIkZwfDtQKBdHYof0Ej7gQ9tPYpPc)vc)MQgQevnykPgUqoiLIJsj4yQKJdHyHQWIvPwUOEivkpv5Xq0Zv1eHGPkPjJQPJCrkjDviu9mjsxNInsjQtl1MPI2UaFecPld(mK(UiDyu(gvQA0cvJxOmmkvDljkxJkvoViMgLqltIyBuISUuvJPQiTxdbiqdX04ACv1YaA7X1Kiqdn7nrAqSigMdCDO1CTqi1oRlvZ0Cne1wlmYDrqGv5ApC6S8(gtAhoQvhUkNvTCv70Z4QQzEOa5j7FDlsKgsvv4LQA8(JozjvigPHaJZ0YaA7X1KiqJGyKgdj1bqn3OOq2LNdkSSl71AUwiKAN1wuZ0CnejXc2EYDzBK7rCnk3OOqwvnkjc0EIrMxZ8qb7mLL8u2a6qZGHaatAmd51mpuWUFF(2LNd6qdcamP5MhZBQ94xZ8qHb3Ko0UnoDU4(uhyTpUp1b2gKuhaI0ACtfpXYeWv4LifwIQA8(JozjvigPHaJZ0YaA7X1KiqJGyKgdj1bqn3OOq2LNdkSSl71AUwiKAN1UtZ0CTs)sqWsXjKGTVgLBuuiRQgLebApXiZRzEOGDMYsEkBaDOzWqaGjnMH8AMhky3VpF7YZbDObbaM0CZJ5n1E8RzEOWGBshA3gNoxCFQdS2h3N6aBdsQdarAnUPINyzc4k8sKclvvnE)rNSKkeJ0qGXzAzaT94AseOrqmsJHK6aOMBuui7YZbfw2L9AnxlesTZAlPzAUg2nBSIvC(2hA5ink3OOqwvnkjc0EIrMxZ8qb7mLL8u2a6qZ8qb7(95BxEoOdniaWKMBEmVP2JFnZdfgCt6qZGHaatAmd51UnoDU4(uhyTpUp1b2gKuhaI0ACtfpXYeWv4LirAbk8YILCjsca```

**Comment by emptyrivers** [comment]
Should be fixed now.
