### ISSUE TITLE
Range Check condition, handle 3rd state "nil"

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#598]
The range check condition test is:
`conditionTest = "state and state.show and (UnitExists('target') and WeakAuras.IsSpellInRange(state.spellname, 'target') == 1) == (%s == 1)",`

isSpellInRange return
1 if in range
0 if not in range
nil if not applicable

It works good if we test "spell in range" is true
But if we test "spell in range" is false, the nil case is valid for this test which is wrong

**Comment by InfusOnWoW** [comment]
I guess the correct check would be:
conditionTest = "state and state.show and (UnitExists('target') and WeakAuras.IsSpellInRange(state.spellname, 'target') == %s)"

For which spells does IsSpellInRange return nil?

**Comment by mrbuds** [comment]
With blackoutkick when i target myself
With Whirlling Dragon Punch all the time it return nil

**Comment by InfusOnWoW** [comment]
Can you test what I suggested?

**Comment by mrbuds** [comment]
not exactly the same
IsItemInRange return true, false or nil

**Comment by InfusOnWoW** [comment]
Nice Blizzard!

It looks to me like the existing check should work then
