### ISSUE TITLE
Specific Talent Loadout Conditions

### ISSUE THREAD

**Issue by jec324** [WeakAuras/WeakAuras2#599]
**Is your feature request related to a problem? Please describe.**
I'd like to load specific auras in specific locations based on current talent loadouts.  Right now I'm piecemealing it together with "Talent Selected" "And talent selected" and "spell known" and settling for a more simplified version.

**Describe the solution you'd like**
I'd like a "specific loadout" section which lists the talents by row/column in a small box (similar box to when you expand the talent selected section.  Then allow you to check box the specific talents for loading that you'd like. 

**Describe alternatives you've considered**
As mentioned above I'm using Talent Selected, And talent selected, and Spell Known to hack it together. 

**Additional context**
I think the feature would be very useful for when auras need to shift between different styles of encounters ... Aoe/ST/Mix or even PvP potentially

**Comment by Stanzilla** [comment]
![image](https://i.imgur.com/0Kz5t5v.jpg)

explanation that was linked

**Comment by InfusOnWoW** [comment]
The screenshots don't match the explanation.

In the screenshots only 2 talents change, whereas in the description 3 talents change.

Anyway, that looks like a another "And Talent" selected would be sufficient.

**Comment by Stanzilla** [comment]
We talked and he's fine with a "won't fix" for now. Not sure if I like another "and talent"

**Comment by InfusOnWoW** [comment]
I did add another "And Talent selected" option, since it is invisible until the user has checked the other two. But, 3 must be enough now...
