### ISSUE TITLE
Icon text position is wrong after moving into group

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#600]
**What steps will reproduce the problem?**

Import

```
b4vmErLxtfMxu5fDEn1CEnfrLzNxt1MxtrMxtrMxu51uJv3C09wBuvgE051uMvNBJrxAV5gkP4hyYvgD1jNB(bMiuv2C0LMBNjIFGvMBK51uHngDPzxzujxANDwzY10BKvMxo1smW41u0jxANDwzY5fvEnLy1zMztH2B39KBEn1CO92Dp5wqJrxA2vMx051u0vgE0fduVLMB051umvKru51uYv2zP9MBuLhCL51uPn2BU51u0vgE0fJxtvYyEnvAK51uuv2C0L0yV5MxtvxAK51uhfxrSrNqov3A3rKxtrxz4rxmd9MB0fwAU1wzUrNxt9uvunvsevKxtLMBPr3xZrxyYrxzK5LtX4fDEnLDE5um0itmErNxEb
```
and create an empty Dynamic Group

then move the icon into the group and change the text position to bottom.

**What is the expected output? What do you see instead?**

The text is offset to the right and not in the center. *Note:* the issue corrects itself after a /reload

**Please provide any additional information below:**

Back then, @asakawa-k fixed icon positions in https://github.com/WeakAuras/WeakAuras2/commit/41e5e56aae8b228861987f464ce58a676f901151 we might have to apply this in other cases as well?

**Comment by InfusOnWoW** [comment]
Should be "fixed", until the next problem with that awful hack.
