### ISSUE TITLE
inserting template into trigger is broken

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#604]
**Describe the bug**
inserting a template into a trigger causes it to fire lua errors and not insert anything

**Do you have an error log of what happened?**
1x WeakAuras\WeakAuras-@project-version@.lua:2648: attempt to index field 'names' (a nil value)
WeakAuras\WeakAuras-@project-version@.lua:2648: in function <WeakAuras\WeakAuras.lua:2631>
WeakAuras\WeakAuras-@project-version@.lua:2661: in function `PreAdd'
WeakAuras\WeakAuras-@project-version@.lua:2745: in function `Add'
...rfaceWeakAurasTemplates\TriggerTemplates.lua:372: in function `handle'
...rfaceWeakAurasTemplates\TriggerTemplates.lua:386: in function <...rfaceWeakAurasTemplates\TriggerTemplates.lua:367>
...rfaceWeakAurasTemplates\TriggerTemplates.lua:408: in function <...rfaceWeakAurasTemplates\TriggerTemplates.lua:407>

**followup error**

1x ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:995: bad argument #1 to 'pairs' (table expected, got nil)
[C]: ?
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:995: in function `SetNormalTooltip'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:800: in function `SetNormalTooltip'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1486: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1481>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**somehow also this fired (most likely related to the above as it happened at the same time)**

1x WeakAurasOptions\BuffTrigger.lua:377: attempt to index field 'names' (a nil value)
WeakAurasOptions\BuffTrigger.lua:377: in function `member'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:249: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:197>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:371: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:344>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:1079: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1075>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:1616: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:1541: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1521>
[C]: ?
VuhDo\Libs\AceGUI-3.0\AceGUI-3.0-36.lua:71: in function <VuhDo\Libs\AceGUI-3.0\AceGUI-3.0.lua:69>
VuhDo\Libs\AceGUI-3.0\AceGUI-3.0-36.lua:285: in function `Fire'
...libs\AceGUI-3.0-36\widgets\AceGUIContainer-TabGroup.lua:156: in function `SelectTab'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:1652: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:1896: in function `Open'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:628: in function `FillOptions'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:768: in function `finishPicking'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:803: in function `PickDisplay'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:4060: in function `PickDisplay'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:514: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:488>

**To Reproduce**
1. make an icon
2. insert template into trigger by using that....
https://i.gyazo.com/e91d86e99cce62a7fdb0eb17e4266785.png

**Which version of WeakAuras are you using?**
latest master version

**Comment by InfusOnWoW** [comment]
Should be fixed.
