### ISSUE TITLE
Exit Update tooltip with X after selecting Copy - Checkbox text stays grayed out

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#611]
When importing an update:
1. Choose "Create a Copy"
2. Check boxes and their text will be greyed out
3. Exit the tooltip with the X
4. Import the update again
5. Check boxes text will still be greyed out, check boxes will be yellow again

![](https://cdn.discordapp.com/attachments/273144328447197186/476459638892527638/unknown.png)

**Comment by emptyrivers** [comment]
This isn’t fixed specifically, but the edge case you found can no longer occur.
