### ISSUE TITLE
TSUs ignore group order

### ISSUE THREAD

**Issue by jgersti** [WeakAuras/WeakAuras2#613]
**Describe the bug**
All auras but the first on in a group appear before a TSU in the same group regardless of the TSUs position in the group. Expected behaviour is that the group order is respected.

**To Reproduce**
1. Create a group with a TSU and atleast 2 normal auras which overlap the TSU.
2. Put the TSU last, so it should be drawn in front of the other auras.
3. ...

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
2.6.6

**Was it working in a previous version? If yes, which was the last good one?**
Not tested.

**Comment by InfusOnWoW** [comment]
Please include a export showing the problem.

**Comment by jgersti** [comment]
https://wago.io/B1x5ipuHX

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
