### ISSUE TITLE
error when opening weak auras ingame via /wa command

### ISSUE THREAD

**Issue by Dracondros** [WeakAuras/WeakAuras2#615]
**Describe the bug**
When i open weak auras ingame using /wa, an error occurs.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

Date: 2018-08-08 21:41:49
ID: 14
Error occured in: Global
Count: 1
Message: ..\AddOns\WeakAuras\WeakAuras.lua line 3882:
   ..\AddOns\WeakAuras\WeakAuras.lua line 3198:
   attempt to concatenate field 'alphaFunc' (a nil value)
Debug:
   [C]: ?
   WeakAuras\WeakAuras.lua:3882:
      WeakAuras\WeakAuras.lua:3865
Locals:
(*temporary) = false
(*temporary) = "Interface\AddOns\WeakAuras\WeakAuras.lua:3198: attempt to concatenate field 'alphaFunc' (a nil value)"

AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Babylonian, v5.1.DEV.332(/embedded)
  Configator, v5.1.DEV.431(/embedded)
  DBMCore, v8.0.1
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Gatherer, v7.3.1
  GTFO, v4.46.2
  HandyNotes, vv1.5.2
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  MapCoords, v0.28
  MasterPlanA, vA
  Ovale, v7.3.0.3
  Paste, v1.4.10
  Recount, vv8.0.1a
  SlideBar, v7.3.1 (<%codename%>)
  TellMeWhen, v8.5.2
  WeakAuras, v2.6.6
  WeakAurasOptions, v2.6.6
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=23b)

**Comment by mrbuds** [comment]
**Which version of WeakAuras are you using?**
You can see the current version in the title bar of the options window, if the options do not open, check the Twitch app or the `## Version:` field in the WeakAuras.toc file

**Additional context**
If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file, it's the `WeakAuras.lua` file in `World of Warcraft\WTF\Account\YOUR_ACCOUNT\SavedVariables\`

**Comment by InfusOnWoW** [comment]
Thanks, that should be fixed for the next release.

**Comment by Dracondros** [comment]
I am using WeakAuras 2.6.6 - the current version that is on Twitch.  I was using release version but a friend mentioned to try beta, but it gave same results.
It seems like one of my mods was causing the issue.
I have tried to reimport it but it doesn't seem to import quite properly, and once in it gives an error.
Its a health/mana icon deal where potion icons will show up in the middle of the screen if health or mana drop below a percentage threshold:

dSKUnaGiLeUKsknkQOtrfwLsLEfOsZcf5wkjTlaXVecggkCmcSmrvpJkHPrL01uQyBOO6BeeJdqY5ec16usunpaP09evW(aKQdsLQfQu1dfvQjkesxujfBeuXhvsKrIIsNuurRuizMIk5MeuTtq5NeKgQsQSurf6PuMkqxvjvTvuu8vHqmwHuNviAUujAVs)fGbRQdRYIbupgKjluxM0MjKplkJwjonv9AaPy2eDBLYUr1VfmCuA5qEouth56ISDqvFNGY4Ps58eQ1RKOSFfxbfS2vWs1W1YdeMdeMxBRwCT4cwZnHksewPcB18czNAhe5Hxbr(Smfj8qSwymQriFwMIkyn8sqycLxdVeeMq5UdrE41s18Csr8tYmkc7d8cBNA(4AmREsAjcc)438UlveHRDXXEYh4NeaH8zzkcxWs1IvmuTCcf4ZFsfr45PLJMp2JzLN45f2IYv4v08IdP5pKopWQmiS5DbJ1o)IEsAz(aAExiK1o)2XpGudPz(ahumRwldfsS14PnqKpltr4ctqnSkfTUGNt12luqqHk8CTg4awtSqfjcRuHTkqXOMmCXfSMNNHcj2cwBljjFblvQgDsLtfS2wss(cwQunrhe5d8cwBljjFblvQwcRaGKhgxGRHoiTG12ssYxWsLQf7fjYdLKK4cwBljjFblvQgl8S0jvovWABjj5lyPs1qbPwWABjj5lyPs1OtQCkFbRTLKKVGLkvQM6g7XJ14UVunOcwyckynsDJeaNaNm)ktlS8UwZnHksewPchx3HHlyodH4I8cHbqfXc2X1kAvxfsnOeMcBGQBunrjoe5dCNoMxgGo58Skcs5085W8oxp3tmREsAX5kyLNyfTchry9CpXS6jPfHFU5CfSYtSIwHdh7kGbJ5rkLq85DUI1cegIwHJvUOaA7iNSkcs5KJ5vECTdI8WRGiFwMIeEiwlmg18Csr8tYmkc7d8cBNAh3VDKpWlynmDiQG1WqNuHtIdvB(5NFErjoe5dCNSOqgsXyMMhthIIMP5X0HOizAEm0j1OzAEm0j1iDmrn)8Zp)8ZldqNC(JNj15ZH5DYIczifJNF35Zp)UZVD0cqy9oMF15DUD0cqy9ZhH5Z7yIA(5NF(5NhPucXNhthIIEE4oVtNo3oAbiyp35XZKQJ5H78cCeH8oMF35DIHoPg98RoVahoyAEmDikY5H78oD6C7OfGG9CNhptQoMhUZlWreY7y(DN3jg6KAKZV68cC4yIA(5NFELhprn)81oj7YbkMvRHj05Zwi3LSlxnOGmGCVWeudkidOvQWeulHvae64y5rA3xlHvaNKD56(AyOtQGIz1ASjjwRbfKb0(ctqncDCS8ifojouT5NF(5fL4qKpWDYIczifJzAEmDikAMMhthIIKP5JvjDrZ08XQKUiDmrn)8Zp)8ZJukH4ZJPdrrppCN3jlkKHumE(DNpwL0fTdMMhthIICE4oVtwuidPy887oFSkPlshtuZp)8ZR84jQ5NVgg6KQ4clFTtYUCfMGAe64y5rkOywTgMqNpBHarhhlpsRjUWyuZTclpdg1ItOJ8bEnbrW1AKywTguctHTAjScadDsT7RHc0rAHXOguqgq5yHjOgg6KQBfw(s1e55E8sbRHHoPcNehQ28Zp)8IsCiYh4ozrHmKIXmnpMoefntZJPdrrY08yOtQrZ08yOtQr6yIA(5NF(5NhPucXNhthIIEE4oVtwuidPy887oVtm0j1ONF15X0HOOD4GP5X0HOiNhUZ7KffYqkgp)UZ7edDsnY5xDEmDikshoMOMF(5Nx5XtuZpFnm0jv3kmg1oj7YbkMvRHj05Zwib1GcYaY9ctqnOGmGwPctqTtYUCWjXHQn)8ZpVOehI8bUtwuidPymtZJPdrmnFSkPZXe18Zp)8ZppsPeIppMoenpCN3jlkKHumE(DNpwL05yIA(5NFELhprn)81syfaHoowEK291syfWjzxUUVgjMvRbLWuyRguqgq7lmb1WqNufxymQDs2LRWeuJqhhlpsbfZQ1We68zlu(AIlSvZZGrn3kmg1syfag6KA3xddDsfumRwdtOZNTq5RfNqh5d8AcIGR1qb6iTWyudkidOCSWeuQunc5ZYuubRfNqh5d8Amas(DQDBHeNQjGbdgmQHzvPe2TP1YDyd4eM8bETewbSONKwkW1WjGv4vozjrI8Uvdqe1DH7(kTMASkcs50IEsAPgqXOg)20AWuHvlHva4qcbPRN7PUVwcRaIvmL4EQaxlHvakhEpkW3uoDsqXSA3xlHva3wiXPcCTewbCaJdiGfEiw7(AkhEpkW3uoDsqXSATC5oZ4EnOeMcBaw8XAnYVPX1yveKYPf9K0cGaRIokGQb0wJeZQ1W0rjCTexHx5uTlrHAjSciX9u3xlHvaXkMkW1WjGv4vovZw3AYvUaKB3nqa26ZDUxJz1UTqItacSk6OaQgqVwcRaWSQuc720UVwcRaGqEYdDYUVwcRaydctrGIz1cCTewbWQiiLtl6jPLUVgoKqq665EQgR8eROAjSc4sOdumRwGlvBr9zluHJR7WWfmNrEgrSG8afdxz(ov0QUY8AYWfxWAEEgkKylyTTKK8fSuPAjScGRWROcCn6KkNkyTTKK8fSuPAXErI8qjjjUG12ssYxWsLQHcsTG12ssYxWsLQrNu5u(cwBljjFblvQMOdI8bEbRTLKKVGLkvdDqAbRTLKKVGLkvJfEw6KkNkyTTKK8fSuPs1sCc5ZYuubRL4EQgR8eROASkcs50IEsAP2omQLWkawfbPCArpjT091yveKYPf9K0cGaRIokGQb0ZHAjSciX9u3xQgsZ8boOywTMhkWRDXXEYh4NeaH8zzkcxWctqbRriFwMIkynsmRwdthLW1sCfELt1UefQHtaRWRCYsIe5DRgGC7UbcWaDphbRLWkGt6Hx7(Ak8kNQL7ap2t(ahxdNawHx506qQiVB1S1TMCLRs1sCc5ZYuublvQunp3taGcBSsL04ctqnsDJeuBTqRT2br(ahxWAy6qubRHdjECTCYjfj6Gux6ECSq5yxgr0dOX9e6WUu4AS)CPfs8ySlJihI75zMhPCGeYYQfhaGdjECbUuPAxIcf4A(4AmREsAPMW8X0sHJR7WWfmNHqCrEHWaOIybUkKkAvxzEnEAde5ZYueUWYxZZ9eamDisJlmb1I9yw5joNqbETCYjfj6GuxMtOah7YCcJzaSUa5dCacCnFnOqqghegVaxQun4lmbUMxqPwa




    On Thursday, August 9, 2018, 3:48:23 PM EDT, InfusOnWoW <notifications@github.com> wrote:  
 
 
Thanks, that should be fixed for the next release.

**Comment by InfusOnWoW** [comment]
The second aura had a very similar, but slightly different problem. That's also fixed for the next release, which should come out soonish.

**Comment by chanzie** [comment]
ok when trying to open using the newest release I did not get a bug but the ui would not open with my addons turned on other than wa once I disabled everything but wa it opened fine...
addons installed...
Angry Keystones
ark inventory
auctionator
big wigs
Bop craft confirm
class colors
coolline
dominos
dresser
dugi questing essentials
exteneded transmog ui
extended vendor ui
extra questing button
fishing buddy
GTFO
guild member status
handy notes
higher hotkey
littlewigs
midelpique
molinari
multiscreensuport
ncHoverName
ncKillingBlow
Postal
Rematch
skada
talentArt
talentless
tthe Undermine Journel
transcriptor
Transmog Away
weak auras
WhoWisperedme
World Quest Tracker
DejaCharacterStats
ilvlr
AddonSkins

**Comment by emptyrivers** [comment]
@chanzie, in the future do not comment on closed issues unless you believe they should be reopened. Open a new ticket instead.
