### ISSUE TITLE
Export Issues

### ISSUE THREAD

**Issue by EZOBOSS** [WeakAuras/WeakAuras2#618]
**Describe the bug**
I expected to get a full string of code to export and to share it on wago instead I got a screen with nothing. Check gif.

**Do you have an error log of what happened?**
``` 1x WeakAuras\Transmission.lua:75: attempt to get length of local 'str' (a nil value)
WeakAuras\Transmission.lua:75: in function <WeakAuras\Transmission.lua:70>
(tail call): ?
(tail call): ?
...dOns\WeakAurasOptions\OptionsFrames\ImportExport.lua:52: in function `Open'
WeakAurasOptions\WeakAurasOptions-2.6.6.lua:3814: in function `ExportToString'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:881: in function `func'
FrameXML\UIDropDownMenu.lua:935: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
str = nil
B64 = <table> {
}
remainder = 0
remainder_length = 0
encoded_size = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'str' (a nil value)"
encodeB64Table = <table> {
}
bit_lshift = <function> defined =[C]:-1
bytetoB64 = <table> {
 1 = "b"
 2 = "c"
 3 = "d"
 4 = "e"
 5 = "f"
 6 = "g"
 7 = "h"
 8 = "i"
 9 = "j"
 10 = "k"
 11 = "l"
 12 = "m"
 13 = "n"
 14 = "o"
 15 = "p"
 16 = "q"
 17 = "r"
 18 = "s"
 19 = "t"
 20 = "u"
 21 = "v"
 22 = "w"
 23 = "x"
 24 = "y"
 25 = "z"
 26 = "A"
 27 = "B"
 28 = "C"
 29 = "D"
 30 = "E"
 31 = "F"
 32 = "G"
 33 = "H"
 34 = "I"
 35 = "J"
 36 = "K"
 37 = "L"
 38 = "M"
 39 = "N"
 40 = "O"
 41 = "P"
 42 = "Q"
 43 = "R"
 44 = "S"
 45 = "T"
 46 = "U"
 47 = "V"
 48 = "W"
 49 = "X"
 50 = "Y"
 51 = "Z"
 52 = "0"
 53 = "1"
 54 = "2"
 55 = "3"
 56 = "4"
 57 = "5"
 58 = "6"
 59 = "7"
 60 = "8"
 61 = "9"
 62 = "("
 63 = ")"
 0 = "a"
}
bit_band = <function> defined =[C]:-1
bit_rshift = <function> defined =[C]:-1`

```

**To Reproduce**

1. Go to '/wa'
2. Try export

**Screenshots**
[GIF](https://i.gyazo.com/ebc90fe89de7091cdee44128fb807b4f.gif)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes same issue.

**Which version of WeakAuras are you using?**
2.6.6

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

[WeakAuras EZO.zip](https://github.com/WeakAuras/WeakAuras2/files/2275834/WeakAuras.EZO.zip)

I took out 1 large aura that does a lot of custom calcs. It was 10k string alone. Now I could start export the main group (wow freezing up as usual) So I wait like 1min and the when the lines pop up I think it was 500k size and I insta dc when it loads up. If I put it back in can't export. I guess I can't either way since I instantly get disconnected.

**Comment by emptyrivers** [comment]
So, this is probably a bug with our compression library. Below is a dump of a conversation I had while investigating:
```
anyways, the failure in that ticket is that the Huffman compression has an escape overflow
whatever that means
InfusToday at 1:19 AM
thats strange
riversToday at 1:19 AM
using LZW, it successfully compresses
ofc that's probably not an acceptable change :smiley:(edited)
LibCompress follows the "return nil + error msg" paradigm for when it has a problem, and TableToString doesn't check to see if there's an error message
InfusToday at 1:21 AM
I've debugged LibCompress in the past, I'll check what there is
riversToday at 1:40 AM
so, the ticket mentions that removing a particular aura will allow the export to succeed (no mention of which one though...)
i figured out which one it is (DC Core is the name), and it has a lot of custom scripts
every single one of which has a few dozen newlines grafted onto the end
removing those newlines causes the export of the group to succeed
those newlines almost certainly weren't placed there intentionally, this happens to all custom scripts. After editing one several times, you get this huge string of \n at the end
```

**Comment by InfusOnWoW** [comment]
I couldn't reproduce the issue that rivers had, nor the one you report. For me the string was shown. Though wow immediately disconnected me.

A lot of you progress bars have the same action/init code, which seems ununsed for the majority of your bars. Clearing those out significantly reduces the size of the exported string.

The screen freeze is outside of our control as that is WoW not being happy with us pasting a 500K long string into the textbox. Your group is simply too big to be exported.
