### ISSUE TITLE
Item CD Progress trigger show condition is broken

### ISSUE THREAD

**Issue by sragia** [WeakAuras/WeakAuras2#620]
**Describe the bug**
WeakAura doesn't show if it's set to show On Cooldown at all. doesnt matter if it's on cd or not.
Always works correctly
Not On CD also shows always...

**Do you have an error log of what happened?**
None

**To Reproduce**
Make aura that uses CD Progress (Item) trigger (for testing I used Prolonged Power) 

**Screenshots**
https://i.imgur.com/qgXa62x.gifv glow shows that it's on CD (with condition)

**Which version of WeakAuras are you using?**
I'm on 871bfb9cce and tested with clean SV

**Was it working in a previous version? If yes, which was the last good one?**
yes 2.6.6 for sure

**Additional context**
prologed power was
`deeBhaqjLaJscLtjHQBHkzyiQJHILjjptKY0iX1eW2qKVHQmoLOZjHCqrsleipKKYebQCrGInks1hbQsNujOvssvVevQmtGQ4MIe7uk)uedvj0rrLswkQu1tHMQGUkqPTssLVIkLASOsr7L6VKKbRK6WIAXc0JLQMmPCzvBwI(mcJwQCAIEnqv1SvQBtQ2nOFJ0WLuhhvkSCHEoHPR46a2oQ47O04LGZJQA9avL9RKSzCOXSd9yuyeCNJrDJAg1COX4jKuyi)6BKisbQnk(UCrQeogbLegMKc4bmPhAucNhH5T6EuiPq3izuQzSD2vRbVrkqTraPMXd2i3Sde3boecwJBAwZHgbexv)oleoOhJVqDgQDndYJXEh6gJdnYpPSu8XPhG0YQkEbiZSKezLaklDjxkkgZ9JKZdJscIhtHQD34IHSXjkjiE0HgLZ1Bz97gJsfddpJaIRkhuqJbtHQDdYiXHpk7XokBc0OOJYMavJs3AuwOXHF9nkM8aimcapNdhJzGHAeqCveh(OSh7OSjqdYiG4QKZ1Bz9BqgpNdhJQrPBnklC16fJuI4fIvRl2cNRxCJaIRcakhdYy85nw)9UL1VBKnciUkr937ww)gKrr937ww)Ur2yqGYsSJYMank6OSjWu7hjN7XiaCIscIhDOrIdFu2JDu2eOrrhLnbQgLU1OSqJY56TS(DJrPIHHNhJXtiPWq(13OSNcnkHZJW8wDpkKuOBKmoVWWyCb1gNxyQadmhCFndY48ctLXe4Q1QboJsnJTZAeqQzSwjn1REUvQfyljBSqszP4JtFzagfsvvPPqwHKcPalDjxkb84wLdncaNOKG4rhAK4WhL9yhLnbAu0rztDZM5lmkNR3Y63ngLkggEEmM7hjNhgLeepMcv7UXfdzJtusq8OdnkNR3Y63ngLkggEgbexvoOGgdMcv7gKrIdFu2JDu2eOrrhLn1nBMVWiG4QaGYXGmo8RVrXKhaHra45C4ymdmuJbbklXokBc0OOJYMatTFKCUraXvjNR3Y63GmgFEJ1FVBz97gzJaIRsu)9UL1Vbzuu)9UL1VBKnEohogvJs3Auw4Q1lgPeXleRwxSfoxV4gbexfXHpk7XokBc0G8yucNhH5T6EuiPq3izKFszP4JtpaPLvv8sRifLLKQ4vvKl5srXy8eskmKF9nk7PqJZlmmgxqTX5fMkJPUzZ8fgLAgBND16kJZlmvGbMdUVMbzSqszP4JtpqrkKyiXqonYkfrQsHNl5sjGraPMroGbSCdUJhyvpXIuJ9uOMCKuOWHUX4qJ9DVh87qJtusq8OBKnYjhL5G7BKcvJs3AuwOro5nWDJXJX(UmK4ch6gJdnYjVbUbzSosRFC4BKytz94XJhpULMdncaNOKG4rhAK4WhL9yhLnbAu0rztGC)ZA8nkNR3Y63ngLkggEEmM7hjNhgLeepMcv7UXfdzJtusq8OdnkNR3Y63ngLkggEgbexfXHpk7XokBc0GmsC4JYESJYMank6OSjqU)zn(gh(13OyYdGWia8CoCmMbgQraXvLdkOXGPq1Ubz8CoCmQgLU1OSWvRxmsjIxiwTUylCUEXnciUk5C9ww)gKraXvbaLJbzm(8gR)E3Y63nYgbexLO(7DlRFdYOO(7DlRF3iBmiqzj2rztGgfDu2eyQ9JKZ9ymEcjfgYV(gL9uOr(jLLIpo9aKu4rEzrb4vXJxAllINl5srX48ctfyG5G7RzqgNxyymUGAJZlmvgBjRwRg4mk1m2o7Q1PzSqszP4JtN0YIiXeyPczLkfEbcqYLCPqYiGuZyWgXIuUnd4cawWNrjCEeM3Q7rHKcDJKhpg54gJsfJhBa`

**Comment by InfusOnWoW** [comment]
Is fixed again. Thanks for the report.
