### ISSUE TITLE
Unable to use dynamic info from custom triggers in conditions

### ISSUE THREAD

**Issue by BillWiegert** [WeakAuras/WeakAuras2#629]
**Describe the bug**
For custom triggers the conditions tab does not give the option to use dynamic info in a condition.
The only options it gives for a custom trigger is Active: True/False

**To Reproduce**
Create any aura type with a custom trigger.
Return your favorite number in the Stack Info field.
Try to create a condition using stack info from your custom trigger.
Cry.

**Screenshots**
![image](https://user-images.githubusercontent.com/21974998/43997123-862ae7ac-9da1-11e8-983f-02c4d0d5c035.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, confirmed with another user on the WA Discord that the issue is present for others as well.

**Which version of WeakAuras are you using?**
2.6.6

**Was it working in a previous version? If yes, which was the last good one?**
Unknown

**Additional context**

**Comment by emptyrivers** [comment]
I don’t believe this was ever implemented. Regardless, it is on the to-do list, eventually 😃

**Comment by InfusOnWoW** [comment]
That's tracked in https://www.wowace.com/projects/weakauras-2/issues/984 already.
