### ISSUE TITLE
Grid to position auras. 

### ISSUE THREAD

**Issue by Naiala** [WeakAuras/WeakAuras2#636]
Hello. I've been always struggling with perfect positioning, so I come up with idea of adding grid as one of WA2 functions (just like we have in Elvui for example), there is already addon for that, but some (like me) dislike many addons. 

Pros:
Much easier positioning.

Cons:
???

Here's how I see it: 
![example screen](https://i.imgur.com/h5q0fFs.jpg)

**Comment by Stanzilla** [comment]
I'd probably say out of scope, there is tons of stuff like https://github.com/Stanzilla/Align around.

**Comment by InfusOnWoW** [comment]
I have crazy ideas on stuff on that area, but they are very far at the bottom of what I'd like to todo.

I don't think a grid is necessarily the best way to position auras, I'd rather have "alignment" lines. So lines that automatically show up to make it easier to e.g. make sure that your auras are on the same y-axis.

Selecting a aura should be possible via clicking on it.

Also multi selection and "distribution" actions. That is on selecting multiple auras, you get a number of small quick action icons in the corner of the multi selection rectangle, which allow to e.g. layout the selected auras evenly, or with a given spacing and so on.

I think that would be much more powerful than a grid system, but I doubt it'll get to the top of my todo list anytime soon.

**Comment by emptyrivers** [comment]
With the new snapping feature, I think that this request has been rendered moot.
