### ISSUE TITLE
[BUG] Stopmotion module disabled causes WA to break

### ISSUE THREAD

**Issue by Uriyel** [WeakAuras/WeakAuras2#637]
**Describe the bug**

Upon loading in with a character that had StopMotion disabled in Addons, all auras show on screen.  The WA interface shows no auras at all.  
All Stop motions auras are currently set to Not Load.

**Do you have an error log of what happened?**

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:2665: attempt to index field '?' (a nil value)
Time: Sun Aug 12 19:33:59 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:2665: attempt to index field '?' (a nil value)
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:612: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:574>
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:2665: in function `PreAdd'
Interface\AddOns\WeakAuras\WeakAuras.lua:2755: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:2618: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:2624: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1278: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1247>

Locals: errMsg = "Interface\AddOns\WeakAuras\WeakAuras.lua:2665: attempt to index field '?' (a nil value)"
errorTime = 172041205.72785
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:378
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:105
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:295
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:355
 SantizeErrorReportString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:386
 errorFrame = <unnamed> {
 }
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:2665: attempt to index field '?' (a nil value)
Time: Sun Aug 12 19:35:00 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:2665: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:2665: in function `PreAdd'
Interface\AddOns\WeakAuras\WeakAuras.lua:2755: in function `Add'
Interface\AddOns\WeakAuras\WeakAuras.lua:2618: in function `load'
Interface\AddOns\WeakAuras\WeakAuras.lua:2624: in function `AddMany'
Interface\AddOns\WeakAuras\WeakAuras.lua:1278: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:1247>

Message: Interface\AddOns\WeakAuras\WeakAuras.lua:3984: ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:925: attempt to index field '?' (a nil value)
Time: Sun Aug 12 19:35:36 2018
Count: 1
Stack: Interface\AddOns\WeakAuras\WeakAuras.lua:3984: ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:925: attempt to index field '?' (a nil value)
[C]: ?
[C]: ?
Interface\AddOns\WeakAuras\WeakAuras.lua:3984: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3967>

**To Reproduce**
 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
All auras work normally on a different character (due to stopmotion addon already being active)

**Which version of WeakAuras are you using?**
2.7

**Was it working in a previous version? If yes, which was the last good one?**
yes.  2.6?

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
