### ISSUE TITLE
After 2.7.0 Update broke conditional height/width

### ISSUE THREAD

**Issue by Afenar** [WeakAuras/WeakAuras2#638]
Before 2.7.0 All auras was affected by conditions for height/width, but after 2.7.0 it doesn't work at all and just moving auras to some place, but not changing their height/width.
https://i.imgur.com/rhJg2VY.png
https://i.imgur.com/1BH08fg.png

**Comment by emptyrivers** [comment]
[Duplicate issue.](
https://www.wowace.com/projects/weakauras-2/issues/1184)
