### ISSUE TITLE
Broken masque skin for Icon aura

### ISSUE THREAD

**Issue by Modek** [WeakAuras/WeakAuras2#639]
**Describe the bug**
Masque is incorrectly skinning Icon auras. All other Icons including bars from bartender and Auras (Buffs/Debuffs) are working as intended. Referencing the screenshot below, The Left column are icons skinned correctly. Center column are icons with masque disabled, and right column are icons as displaying recently (slight difference from center, but you can tell its still trying to do something). Making changes to the frame strata while the icon is visible will apply the skin correctly, but will revert to appearing like the right column after the aura fades and appears again.

**Do you have an error log of what happened?**
BugSack shows no errors.

**To Reproduce**
The auras are simple icons displaying when a buff/debuff is active and is hidden when not. I've pasted an example string below. 

For the right most column in the screenshot below, no steps are taken. Simply apply the buff or debuff.

For the center column:
1. Disable the Masque addon
or
1. open Masque settings using /masque
2. Select WeakAuras in the list of addons using masque, or expand WeakAuras and select a specific aura
3. Check the "Disable" options.

For the left column:
1. Display the aura using the WA view toggle or use the ability in question to trigger the aura.
2. In either the /wa options or /masque options, make any change to the aura or masque skin.
3. The step above will already "fix" the skin, but if you toggle the view of the aura off and back on, or let the buff/debuff fall off and reapply it, the aura reverts to the appearance of the right column.

**Screenshots**
![wa masque](https://user-images.githubusercontent.com/5410015/44014653-0a39cdac-9e9b-11e8-939f-4eaf148d220a.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.7.0

**Was it working in a previous version? If yes, which was the last good one?**
Yes, I checked all recent alpha builds and 2.6.6-73-gc7196ee is the most recent version that works correctly.

**Additional context**
Both the working versions and not working versions of WeakAuras were used with the most recent version of Masque (8.0.1)

Here is a sample WeakAura string, though there isn't anything fancy going on with it:
dGZDdaGAcr9ssv1Uiu12qKzkIA2sCtcP(gj0ofP9c7MOFsQmmkLXjkoTkdve5ZQQHlQoOuPtriYHr4CeswiPklLs1ILkwUuEiPQ8uLLPkEUKMiHqtfPjtLMoQlsICvcLEMO01PQnsIARec2mjTDe1hju5YctJI(oL0iju8BcgTQ04LQ6XKYTKQCnsW5Pe3MchJk(RimCaf7qQt2NS2EWQypINK4j1tXS9(Ak6iksrGzG5I5ckMfDQQ1GHY9mvWjdjZSzEmTrIKcKmHApttmcn(ih029)rt0cUbsTHDsoAsIIieT6jirkjmUD)F0aftWQuNSyb6H5LhJXeTFWyUrhVQk1sEGjMU2fTYInzmjHrubfPoy295SVfGX64vv3RGvDsS6RGvDYUA8roaJXrF2jjHtYy6tPuQs2XEJ7)Yi1ubSIaHlOymrjK8dOyg(cFGcgmwnp0afREYFjqQdymMOesgumdFHpqbdgZ9uvpnFHTakMHVWhOGbJPviQvqXQN8xcm76eNyvcmwJqlafZWx4duWGXYjNZeLqYGIz4l8bkyWy(AKqsyeOdwtOeGIz4l8bkyWyscJaJAj)fZxJe18qd6HPsOXNGeumdFHpqbdgZxJeAfIAf6bgZ9QISxQXh5aJqAbRf)tqsTKhyNMGe7CXS7ZzFlWo5Xj0emYlbhUi1bJW194tqsusWT7)JwfuK6akg3U)pAGIv9DcYHKtQfQxFSLKsjNmwqoKmMycIc)I9dz0oT9kyvNeR(kyvNSRgFKdSQVtqoK88QQxFSe6R7OjgTRDkymVKB3)hnqbdgmwFDQQ1GHYKCu0mtMmMM2CS9ikBzGApttmRNl)IutfW8NlMYSHIIZq)IOi13et6nOT7)JwfPpyAccfxbRsOhymcqXS7ZzFlqQt2NS2EaJrgPoMpoGba

**Comment by InfusOnWoW** [comment]
I'm not understanding what exactly the bug is? And how to reproduce. Is it with masque enabled, with masque enabled but disabled in the options. Is it without masque?

I can follow your steps to reproduce but I have no idea what I'm supposed to see or notice as a bug or change in behaviour between 2.6.6 and 2.7.0

**Comment by Modek** [comment]
Sorry for the confusion. The reproduction steps were more of steps taken to debug the issue and show that there is still some interaction going on between the addons instead of a simple and unhelpful "this doesn't work".

The issue is simply:
- On builds 2.6.6-73-gc7196ee and prior, auras skinned with masque appear correctly like the two icons on the left in the screenshot.
- On later alpha builds and the 2.7.0 release build, auras skinned with masque appear incorrectly like the two icons on the right in the screenshot.

Center two icons were included as a control, just to show the slight difference between masque simply being disabled and the current bugged appearance. The masque addon itself is enabled. The screenshot was taken by displaying all 6 auras with the /wa view option and then disabling/enabling masque on individual auras through the /masque options to show the difference in appearance for each scenario. My guess is somewhere in the initialization, something is being overwritten, because making any sort of change to either of the two addons settings while the aura is showing changes the skin from the incorrect right appearance to the correct left appearance, but this change does not hold whenever the aura reappears.

**Comment by InfusOnWoW** [comment]
I think this should be fixed in the next release.
