### ISSUE TITLE
Bloodlust/Heroism template outdated

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#640]
The two old hunter pet buffs were removed:

https://www.wowhead.com/spell=90355/ancient-hysteria

https://www.wowhead.com/spell=160452/netherwinds

The new one (Primal Rage) is already in the template (264667).

**Comment by mrbuds** [comment]
This will be fixed with https://github.com/WeakAuras/WeakAuras2/pull/587/commits/8a9fd893b8f36fdb6ed934d586dc4700ca29b7fa

Thank you!

**Comment by InfusOnWoW** [comment]
Fixed now.-
