### ISSUE TITLE
weakauras 2.7.0+paste dynamic group background/border issue

### ISSUE THREAD

**Issue by Alex-Miller** [WeakAuras/WeakAuras2#642]
Wa 2.7.0 (release) issue with dynamic group background/border.
Beginning of the video with all addons disabled, 2nd part wi th Paste enabled.
https://www.youtube.com/watch?v=3n-l9p8eeZ0
Checked also with all wa deleted.
Works nice with 2.6.6 version.
https://wago.io/ryGgUx1I7

**Comment by emptyrivers** [comment]
Likely, this is the same issue as in #639, so I'm marking this as a duplicate issue. I'll keep it open for now, just in case it's a unique problem.

**Comment by emptyrivers** [comment]
@Alex-Miller can you download 2.7.2 and see if your issue is resolved?

**Comment by InfusOnWoW** [comment]
Ah yeah, that should be fixed.
