### ISSUE TITLE
Issue with spell cooldowns when anchored to PRD

### ISSUE THREAD

**Issue by Maeveen** [WeakAuras/WeakAuras2#648]
**Describe the bug**
I want to anchor a spell cooldown to the PRD. It's working without issue while in combat, but what I want is to still see my cooldown after the combat end. Problem is, as soon as the PRD fade after combat, the cooldown animation freeze (or the icon fade if I keep the "set parent to anchor" option checked). I don't have the issue if it is anchored to the screen. The icon is still there after PRD disappeared, but the cooldown animation is not progressing anymore, and the bugged icon goes away at the end of the cooldown. So, I just want the cooldown animation on the icon to keep going. If I go back to combat, the animation works again normally. 

**Do you have an error log of what happened?**
Can't find one, sorry, it looks like a simple graphic bug and doesn't display an error.

**To Reproduce**
1. Create a new icon
2. In the display tab, check "cooldown", select "anchored to Personal resource display" and uncheck "set parent to anchor"
3. In the trigger tab, put a "status" trigger with "cooldown progress (spell)"
4. Select a spell with some cooldown (I put Holy Word: Serenity with my priest)
5. Get out of WA, cast the spell, PRD will appear. The cooldown animation (icon getting gray progressively) starts. Get out of combat, wait until your PRD fade. The animation will stop. At the end of the cooldown, the icon will go away.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I never had any other UI addon and tried to make it work alone, still the same issue.

**Which version of WeakAuras are you using?**
Version 2.7.2

**Was it working in a previous version? If yes, which was the last good one?**
I'm pretty sure it was working the last time I played, but that was June 2017. I didn't kept the previous version so I don't know which one it was.

**Additional context**
Here is the string of what I tried, just with the spell "Holy Word : Serenity" for Priest, but a friend did the exact same thing with a few Shaman spells and got the exact same issue -->

```dyu9haqjku0Ouu0PuuYTuH2ffYVOsLHPqoMkAzIsptjzAsvUMc12ef(gvkgNqPZjuSofvoOqQfkK8qrrtui0fPsvBuf8rffAKkHoPIsTse0lPqPzsHQUPqWorOFkunuLOJsLslvj4PqtvKRIaYwra(QIQolcO2l5VujdwQCyblwQQhJOjRsxwYMvKplQgTs50aRwrbVgbA2iDBQy3G(TQgUs1XPqLLtvpNsth11LY2vs9DfmEHOZtbRNcf2pfTovsyqjXcTcZAKBmkRqhHxHxLeEb2zObjzW6syGsfAi(0KTyD4ySNXCMXQmgpQxSRI9SxpnDC8kHbsgSUsEqEE5JWFlr845iHnpv4gZ725CN7gggmAOcem08bRrpKcGL7cUZ4cU19RC7q0eAScbqU8WaLakVf8qrmdHShKNxELe2VnnHB)qCOq72pehgnjdwxIfEllPqtcx6bLLn7Y8F69hGwZUzU4tnmltcnjKakVf8W5m7onAKrJmjm6gV9(5m7w6bLfuMeAs4YFO811SRVbZU5RabJU5dwJEifaltcjWFZB2r8nYS70SBNg4P37y2XVzNtagYlZUa8A2z3c(YSZW38MD)a0SB(kqWOB(G1itcfs)WvjHCGwqoRscDAugOKyXcdttGilRscDAugOKyXc5aTGSscDAugOKyXcjPbRvjHwamNwcxUWSDpMel0hilLe60OmqjXIf2SLlsAWAfY(wj0)0sjHonkdusSyHxW0eGSrzdkj0PrzGsIflCF9ohOfKvsOtJYaLelw4uGKbpujHonkdusSyHayU)B7kj0PrzGsIflwOVYbpmzyVeM7)2UWkY9a8wx1xi4kCPhuw2SlZ)P3FaAn7M5Ip1WSeAl60YhazHrfpLIhbJ39hscdqYT3FWhCQKH9s4YfIOWaKC79h8bNAzWxqw9f2axH7lASg36ioB3oF0rlmY4tt2I1HJJZoQ3OyoZ4Cvp3eBmNz10XEXkwiPsI4Psc5ks(8Wdzeymkr8mdHxGDgAqsgSUegOuHgIpnzlwhooU34yIzuVmIP354vUz1PMo2ldHbsgSUsEqEE5JWFlr845iHbsg8qRscTCWZkj8(UYP)G6l8(UiBw(DuFXIfcGC5HbkbuEl4HIygczpipV8kjSzlxobMCRUl0GL6lSzlx5fS8asC7hIdvucZly5bK42pehk0U9dXHz(p9(dqHnB5QbbSIsyZwUSB)qo5v9f2SLl2hiji5wWNxQVqYMLFhxBGBjKbo1vyZwU8LtaabWC1xyZwUSB)qCOIsyTUGSWm)NE)bOz3s)N7lR1SBM4ErPZsOVcuCVOuIbNs4Ip1Gz38V)oNzhw(ccydcB2YLDVOuIbNsrjegCkRsI4PWfFQbZU5F)DoZoS8feWgelSbR1fKfgA8l0UxukXGtjIzhnEKq2WEj0YbUzflCRa5BSiUkRqUIKpp8qwibQFdYTJliK(HRscbWC)32vsOtJYaLelwyZwUG16YR(c5aTGSscDAugOKyXcT7fPscTayoTeXSIfssdwRscTayoTeUCHz7EmjwihOfKZQKqNgLbkjwSWMTCrsdwRIs4fmnbiBu2GscDAugOKyXc9pTusOtJYaLelwOpqwkj0PrzGsIflCkqYGhQKqNgLbkjwSW917CGwqwjHonkdusSyHnB5YUxKkkHHPjqKLvjHonkdusSyXcdqYT3FWhCQKH9s4YfIOqFLdEyYWEjeq(qHH7fWGhgOUypipV8wLelKRi5tHgtsHbi527p4do1YGVGS6leCfU4tny2n)7VZz2HLVGa2GzxMr0SlRWbWL3eXvzfgz8PjBX6WXEXmAvmJxf74SJDZ4S9Ivth7nwydCf62vrB8rGNrcgl5vydYEqEE5vsOD7hIdfA3(H4Wm)NE)bOW8cwEajU9dXHcTB)qCyM)tV)auODVOuIbNseZoA8iXcbqa7YYbpxxr8ui5)07pavuIflCTiE2l7Pyja```

**Comment by InfusOnWoW** [comment]
That appears to be a change in how World of Warcraft handles anchoring to invisible frames and as far as I can tell, there's nothing we can do to get the behaviour to what it was before the 8.0 patch.

**Comment by InfusOnWoW** [comment]
This is actually a bug in World of Warcraft, I've prepared a minimal example, which I'm posting here, for our reference.

I'll report that to Blizzard, but it's very unlikely that they'll do a timely fix. Bugs that only affect addons have gone for years without a fix.

``
local testFrame  = CreateFrame("FRAME", "TESTPRD", UIParent);

-- testFrame is attached to the PRD, if there's PRD and attached to the
-- UIParent while there's no PRD
testFrame.Attach = function(self, frame)
  print("Attach!");
  self:SetParent(frame);
  self:ClearAllPoints();
  self:SetPoint("TOPLEFT", frame, "TOPLEFT");
  self:SetPoint("BOTTOMRIGHT", frame, "BOTTOMRIGHT");
end

testFrame.Detach = function(self)
  print("DETACH!");
  self:ClearAllPoints();
  self:SetParent(UIParent);
end

testFrame.eventHandler = function(self, event, nameplate)
  if (event == "NAME_PLATE_UNIT_ADDED") then
    if (UnitIsUnit(nameplate, "player")) then
      local frame = C_NamePlate.GetNamePlateForUnit("player");
      testFrame:Attach(frame);
    end
  elseif (event == "NAME_PLATE_UNIT_REMOVED") then
    if (UnitIsUnit(nameplate, "player")) then
      testFrame:Detach();
    end
  end
end

testFrame:SetScript("OnEvent", testFrame.eventHandler);
testFrame:RegisterEvent('NAME_PLATE_UNIT_ADDED');
testFrame:RegisterEvent('NAME_PLATE_UNIT_REMOVED');

-- NOTE: This frame is actually attached to the UIParent, but the position
-- is relative to the testFrame
local region = CreateFrame("FRAME", nil, UIParent);
region:SetWidth(100);
region:SetHeight(100);
region:SetPoint("TOP", testFrame, "TOP", 0, 100);

-- A texture
local texture = region:CreateTexture(nil, "BACKGROUND");
texture:SetAllPoints(region);
texture:SetTexture("Interface\\Icons\\INV_Misc_QuestionMark");

-- A text on the region
local text = region:CreateFontString(nil, "OVERLAY");
text:SetFont("Fonts\\FRIZQT__.TTF", 24);
text:SetText("ABCDEFGHIJKLMNOP");
text:SetPoint("TOP", region, "TOP", 0, 20);

**Comment by InfusOnWoW** [comment]
I did talk again with Blizzard, this time with a different engineer and they offered a clue to why the text it is not visible. With that I do have a patch which makes the text appear, but it still vanishes on camera forward/backward motion, so there's more investigation needed.

**Comment by InfusOnWoW** [comment]
I did some more investigation today. And it appears that the fix works perfectly for Blizzard nameplates, but doesn't for kui nameplates.

I've looked into that and created: https://github.com/kesava-wow/kuinameplates2/issues/354 to track that subproblem
