### ISSUE TITLE
Usability: "Copy url" no longer focuses field

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#650]
It used to highlight the textbox with the URL to copy. It longer does it and you have to left click into the field to set focus.

**Comment by InfusOnWoW** [comment]
Thanks for the report, that was indeed unintentionally changed.

**Comment by Stanzilla** [comment]
the tooltip should spawn near the mouse cursor as well

**Comment by InfusOnWoW** [comment]
Should be fixed.
