### ISSUE TITLE
"Copy url" feature bugs with linked items

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#651]
**Describe the bug**
Opening the "Copy url" feature from a weakaura results in a little window with the URL. You may copy it from there and close the little window at will.
After doing so, clicking any linked items (ie. a friend whispered his new item he just got) results in opening the little "Copy url" window again, but not the linked item.

**Do you have an error log of what happened?**
No.

**To Reproduce**
1. Select any Weakaura which have been imported from wago.io
2. Left click on "Copy url". The little window with the URL appears.
3. Close the little window.
4. Left click any item which got linked to you. Either from guild chat, whisper chat or trade chat. Doesnt really matter.
5. The "Copy url" window opens again, but not the item you want to look at.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
ElvUI with AddonSkins was enabled.

**Which version of WeakAuras are you using?**
2.7.2

**Was it working in a previous version? If yes, which was the last good one?**
Can't remember if it ever did.

**Comment by InfusOnWoW** [comment]
Should be fixed in the next release.
