### ISSUE TITLE
Copying settings to the clipboard doesn't close the contextual menu

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#652]
Thus requiring the user to right click twice on the aura they wish to paste settings from the clipboard.

Issue is reproducible on bb452b8.

**Comment by emptyrivers** [comment]
fixed by 4dae64c6bf893f81634fe924772e9c901e8e37e3

**Comment by InfusOnWoW** [comment]
Should be fixed now.
