### ISSUE TITLE
Show CD of Charge bad interaction with CD reduction.

### ISSUE THREAD

**Issue by unbear69** [WeakAuras/WeakAuras2#653]
**Describe the bug**
Have 3 Weakauras to track Ironskin Brew for Brewmaster Monk, each showing the CD of an individual charge. Charges 2 and 3 will often not display after reducing the CD or resetting the CD. This same behavior has appeared for Prot Paladin's Shield of the Righteous.

**Do you have an error log of what happened?**
The bug does not appear to cause an error.

**To Reproduce**
For Monk: Deplete Charges of Ironskin Brew -> Use Black Ox Brew. Can also be caused by reducing the cooldown via use of Keg Smash though this is far less consistent.

**Screenshots**
https://i.imgur.com/MbuuE7Q.gifv
The 3 small bars are weakauras for Ironskin Brew representing the CD of Charge 1, 2, 3 in that order.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I have tested this issue with only WeakAuras enabled and I was able to reproduce this easily.

**Which version of WeakAuras are you using?**
2.7.2

**Was it working in a previous version? If yes, which was the last good one?**
I hadn't used this type of WA on my monk until fairly recently. I noticed this issue early on with my Prot Pally however which was a few months ago. It was far less common however since the only CD reduction they have comes from Judgment and only 2/4 seconds at a time. 

**Additional context**
--Brew Charge 1--

d4tZfaGAvP06vLGxQkH2LQc2gjzMQk0TfXSLY4GQ6MQsLttX3GkDzHDQs7fTBj2puQrPkfnmO43KAAkyOQQYGHQmCi5GQsuNsvs6yk6CIklesTuvjLflPwUspKKYtbltv8CctuvkmvvmzsmDQUOQQ6QQsvptuUUuTrvL2QQezZsY2fvDlfY3vO(mrMNQK4Vq0JjQrdHXts1jvv0zvLuDnr68qfhMs)uvLxdLmN8qWW7mldxmtcccpFa3p8qiHGcbfEiO(VQkr487O0Ctm5YMPQMpPyWFQIvJguraNFvvIW5DuUjHA9QeRA6ME5H3jVy49Hxm8MXlgEh4DsNGv2n6IGhcc3Uopeu0iL7cxNWAcYDHRtiqNGPyCEii3fUoHaD6eQ0f)BZkji879Np(59Fc12vnDtV8W7Kxm8(WV4JzI)e3SH0HNhmdtCz1O0mEZ43bCZYM5gYH5zi3mByYQrPz0j00wfEi42wu8hEiK0BUHh60j0fbYsKpwwtWTTO48qiP3Cdp0PtqGkK5HGWuKAbVt6ewRCWdHKEZn8qNoHUiqk3ScbrtqXuvzK7nhhEiK0BUHh60jS6wWdHKEZn8qNoHkRSB0fEiK0BUHh60j0fbsbQqMOji3ScbpeeMIuli8UF3xKobu5r52wuCEiK0BUHh60jyksRUJIhcj9MB4HoD6eejATJ4VvlTHqq0e2qYOlhCqfeS91wBxcc3kJLG1e8qDVVbH)B5F)NyJh6MTGfHA9Qe7Nfr48oji3fUo5eQ7ei0l(AKKILhccurRDTjbVZzUu8FOtWk7M8XznssX(oTsW7OjgcMIhBX2EPyfgDHxve8qDN1emfJJu421dfENeqegjeo)MIrLQ0umQshsZYuLHHvJgYrWnjXYAcgzDH1e81ijflpe6Ia52lbrtOlcKYiSRuiynbPOeRrgqOh)RqqGqp(LBJT4ii0fbsPOeRrgqOh)Rq0eK7cxNGeHrji4MKqHqxei91kJLmc7kfenbbQO1U2KG35mxk(peKryxPqGuJkwRRxcVcbhhubbHB9UGGmc7kfcctcDrGuGqp(xHOj0fbYEX4enHiFuCcQP1nf94c2493QL2qiWgV3eqfT2RsOxI8rXjy7UMWg2gGkATRnji8xFnv4yksyJh6ngtOlcKcurRDTjbrtWxRmwYiSRuqysy7LG3jDcJnkoc(nv1tU0NSzQQ0SSNumSA0GkcwffJB0fBdPVgjPyf8qNqTEvILOjuRxLy)xrkimXgV)mQhnc16vjwW8cbVtc16vj2plFxDXznbfJ4T9ISBYheSfCiuRxLyrBLXsz1OiC1LGq3Oq4TVMOAF9pkPgUveQwBsa(ADlVzeQTYyjT6ErrnDtV8W7a)oKI)JQHN0Cd4JBw2WaRgLMrNGrHa6ngJnEQHWUsb24njyk5Jveenbbk7I1BecR33G1eQ1RsS)QQeHZ7KoH88ohEM0jba

--Brew Charge 2--

d0ZLfaGALK06jkPxkKk7siLTjkntIsmBjUTqDtLu60K8niYLPStLAVODlY(HOgLqQAykXVj1YKQgQkHbtumCiCqLe5ukjQJbPZjQAHQkhwWILslxXdff9uWJj45qnrLemvvmzcnDQUirPUQskEMuCDjTrHKTQKuBwvSDPs)vv13fvMMqmpLeAKkjXNjYOvLgVOWjvj6wevUMk15Lk(PkPXPKQxtu1eLhckUrBAqAbLaMqF0qkA9eIjisqKhczC95bBo3lrBzzPjB2E0L8niDtOZ1NhS5ClxEucT6r0Mm1f9Wd3OCVWDp3lC3W9c3r4gLobLGoXwcp6KhvjiHjCDnhz5YTSj0gMm1f9Wd3OCVWDpJA9f01rrQjYDK((LiOiXh5UB4UHrfbPMg08rYV0hjpAteu(i3DdDcfDqKhcEOyjVNhcX1IR4HoDcvS9NSU2WwcEOyjNhcX1IR4HoDcyeMapeWQKuX4gLobHsaJ5HawLKkgH1EDhD0jOssJUIGhcX1IR4HoDcIQNhLqT4D4HqCT4kEOtNWeemEiexlUIh60jGOlcpuSKZdH4AXv8qNoHk2(Ximb(ry0fJhcX1IR4HoDcpbbxPt8qiUwCfp0PtOITFHsaJ5hDc4yT2FVy0sJHX8JWyskD60bHriuNqByiG9GG8y2sWTm86yeKDP7AUezz(kHK8eA1JOnxMWMZnkbHk21XhldNaHAYhLKKn8qaJWkLDi24gfn)9690jeeCvx7mkjjBwRw04wo0fcQKBtkuwTnyLoXDwc(OKKSHhcvS9p1KXpcvS9l8ggjdZwcswYgLa8QZDnra)QZTsLCHoycvS9lzjBucWRo31e)iGryLYoeBCJIM)E9EcvS97tqqEH3Wiz8JGqf764)xLOrWvXMibH3Wiz4FncBcUEiSIe8jiiVWByKmc9e8oimcyp4vmHAY6AjNqO6AcvS9JF15UM4hHk2(RjLZpcwxl5eYuRlI6CjKL5IrlnggJSmrpGWkLvMGWByKmmHEcJfkacRu2HyJWf1r90rLKqwMVXYrOITFmcRu2HyJFeMAY4gLob3YWzlbvs5)ypmUjYnkHGOOYv6uO87JssYgmp0j4QyBylHGGR0jmpeWEyCEiiQ)fQyxhZwccvSRJjqNGkPCEiiuXUoMaD6eYPe9xg1D2(839nO3zVBA6Vx4JCrYs41usVoJ6EjB277LS3rUBAY2SWh5IKNGsKW3y5qwMmFdJKHSm9eA1JOn8JqREeTr2IsgbuKL5cvgwHqREeTbuYQXnkHw9iAZLPOgDYzlbrfEvRjbx11iesDi0QhrB(ccYloAee26KrOQejGKQUkD6S6mfZjleEMqSb(e8a3neuPU2Gn(raJimYVcgo41XylHw9iAZ1NhS5CJsNqxUrJ0JsNea

--Brew Charge 3--
diewgaakGsNsevZcOWTKs2LisddkoguTmq1ZKIPjcxdu2gi6BsOghiCoqY6akAEsPQoOQuYcHspeOYebQ6IIOSrKQgPQu1jLqwPukVuvkmtvPu3uvQSta)eKAOsGLkLk9uutvvDvre2QuQYxfr0Ej)fPmyv6WIAXkYJPWKfPllSzvXNrYOvuNMsRwkv8AjOzlv3MI2TK(nIHdKLR0ZHmDQUUk2Ue57suJhPY5vLSEvPO9RWcxFXwbG30umgCXiXWtAXjfUytXPIt1xmDq)8GcxaqKiPyWGjbeqahcC4We)c6Nhu4cOfu4INiBASGJ0jR(caxayeaCbGrancaJasiaC5IZgULur6lg5511xCkHMXb5etnj24GCIPy5ITvRRVyJdYjMIhTnARvRXf8KXTs8XDdtsPyC9zlACniMMr1bJX16JRfnUGYRpUKNX1NTOX1xlfvSG54(Es)14waPCSJBZ4c2FqNNC5Yf)qQo99mfsm0jX)TlcizINYl4iDYQVaWfagbax0dbgCiWlUjbSeWHJjbEX6PfSgb0i6tuCtdoujGcd8eqH3KaxpTG1ixCNKt1xSTsTKdi9fBE6UvF5YfFqbTAukwnj2Z9O66l280DR(YLlgbkm0xmYwP6HaWLlEZgH(InpD3QVC5ItTppwJt3FPVyZt3T6lxU4dkOz0ZiKWkEj9qFXMNUB1xUCXpzd3sQ6l280DR(YLl(GcAiqHHWk2ONri9fJSvQEi(Dqd8gYfdQeip3JQRVyZt3T6lxUyp3JQdxFXMNUB1xUC5IrMeIpxWsO2aHewXBqzj1)lqH48zZt5vmYZgfI0KypOZpBioz9sjrrJl2EUwO4jYMgBrvu4caxSXb5eZFqNlE02OTwTgxWtg3kXh3nmjLIX1NTOX1GyAgvhmgxRpUw04ckV(4sEgxF2IgxFTuuXcMJ77j9xJBbKYXoUnJly)bDEYfFQ(APOIvFXiqrVdKndbGJdfmiGlxC2WTLI)APOI9DK0qaTWXi2w9yR5E7flYsQcasX(APOIvFXhuqBp1qyfFqbnJ58sfinjMkQXAn4zszORIrZKYVvVC(fs8bf0OIASwdEMug6QWkgbk6DGSziaCCOGbbCXhuqZ3SrHgZ5LkewXghKtmPnBtdXU1msfBmNxQarJak2StwXTVy)fOqmYZ(bj23SrHgZ5Lke3i(GcAOzszORcR4dkODQwxyfhLIQlgCespLuUoUfSeQnqOXfSmOO3tU4tnkfvxC(4eXBK7mOO3bYMH4coR95LTsnUy3OS4dkOHaf9oq2mewXgZ5LkqIBeVNAiaC5I9GoxtITvRtd551JubGl2Mkg7gLhxWnNxQyCBeBRLIffcRy3AgRMeBnivnjUSn1Nf9WGeouWG3GddsynnWHHrpTsaP45Wsn7IEyyGesyWWajSeWAAGSbJEALakX50uRBj1CNMVwkQyr6lx8eztJvyfpr20ytwkvigFClWsx0fpr20yz7Bgcax8eztJTOk9lP6AsCQf1oNQHBlfIZ1xINiBASyZgfMUeqIbi1q8XMkg8TrF7AMKGfViUiXpB2myFZEwanIrGYBHGpqz)SHMepr20yH(5bfUaWLlUKaWtahxUe

**Comment by emptyrivers** [comment]
As it turns out, this was actually a bug with smooth progress. It will be fixed in the next release.

**Comment by InfusOnWoW** [comment]
This was a interaction with smooth progress, which for some reason was never working properly for timed progress. This fixes that, but might look a bit different from what you are used to.
