### ISSUE TITLE
Point out new features

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#654]
Investigate using the "!" icon Blizzard uses to point out new features in the default UI to point out new stuff in our UI as well

**Comment by emptyrivers** [comment]
`Interface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon`

**Comment by Stanzilla** [comment]
`'|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0|t' .. L["Some translation phrase"]`

**Comment by Stanzilla** [comment]
In 2.7.3 I added this to:
* Templates on the "New" screen
* Condition Combinations
* TSU Custom Variables
* War Mode Load Condition
* Group Role Trigger Filter

We'll have to decide on how long to keep those around, I think having them for a fixed period of time is probably better than having them for a fixed number of releases since that is always dependent on how many bug fix releases we do.

**Comment by Stanzilla** [comment]
I suggest just leaving this open to track where we add and remove it.

@mrbuds you added it to a few places in your last commit, please list them here

**Comment by mrbuds** [comment]
Not release yet (2.7.8 ?)

* Templates "Hold CTRL to create multiple auras at once"

**Comment by Stanzilla** [comment]
When did we say we want to remove the indicators again? x releases or time based?

**Comment by emptyrivers** [comment]
I don’t think we ever did specifically. 

I think that 3-4 months is ideal.

**Comment by Stanzilla** [comment]
https://github.com/WeakAuras/WeakAuras2/pull/1087

is removing the indicators on:

* War Mode
* Filter by Group Role
* Condition Combinations
* TSU Custom Variables

I'd say we give Templates another two months or so.

**Comment by mrbuds** [comment]
Date of commits (not release!)
- Author Options:  13/11/2018
- Conditions for glow/cooldown ?
- Action tab => glow 06/10/2018
- Template + hold ctrl in templates: 06/10/2018
- Cooldown swipe & edge on icons: 10/11/2018

**Comment by emptyrivers** [comment]
Bump for features that we can peel the "New!" sticker off of.

**Comment by emptyrivers** [comment]
#2293 puts us on a clean slate up for shadowlands.

**Comment by InfusOnWoW** [comment]
We haven't really kept information in this ticket. So...
