### ISSUE TITLE
Negate Zone ID, Zone Group ID

### ISSUE THREAD

**Issue by pquerner** [WeakAuras/WeakAuras2#658]
**Is your feature request related to a problem? Please describe.**
I play with low brightness in most cases, but the new dungeon Waycrest something, is too dark for me. Thats why I created a WA to automatically adjust the brightness whenever I am inside that dungeon.
However, it doesnt work as expected sometimes. 

**Describe the solution you'd like**
For my solution to work, I would have 2 WA's.
A: normal - sets brigthness to a normal level whereever
B: waycrest - sets brigthness to a higher level when I am inside this dungeon

Sometimes the normal WA (A) triggers, when it shouldnt, because B is more specific (zone id based)

**Describe alternatives you've considered**
I have not found a clever solution yet.

**Additional context**
WA:

de0(daGibQrru1PeiZsj1TikSlIIgMG6yGSmjvpJiLMMIsxJiv2Ma8nfvghrsoNIcVJOshKOIfQK8qb0ejs4IcsBKiP(OKYijsXjLcRusmtIsUPs0ovWpLsnuIe9uvtfQ2Qs4ReLAVu)funycCyelwrESsnzrDzuBMi(mugTcDAKwnrQ61kQA2GYTj0Ub(nKHluhxrrlxQEUetN01fz7srFxkz8cIZtqRxsA)czdzCFIXT6x8RlZ5KzDFr)SF24(DgJIa4cJzFSokf7ZHetazo7v(uGYDab2cUxOiGhcWVWWKiLikq9x1ghV9szfQuJ7tZ(1iIIKZQsbyLADuk2prZ(sByjsXUfjr3Z6ddrYg3pvy4ByKsXtwT6VnUhGmUpzR0MmENIHX9LOm7bzaf2NcuUdiWwW9cfb8qa(ANIHXDJ7RcJz)DQOir)PKejFe1QnWVmIA1giNTsBY(7urrIWvHXSFrjAQ4NkmCYub1NwIYSx5ZnzG6h4irJeSKlfcg7Nkm8eGQEL)ovuKOVKeyRueq(GIeCwdCbPlFW1iIIKGxhjaki5gjGb5ibrvIQevjQsuLOkrv8taUjduFssr(7rEpVFkotu2Q)itXgvpa5ddrYg3pvy4vraUr2tw97mgfbWfgZ(0nc4tZ(1iIIKZQsbydOUibMFlAwh9aKFIM9L(zgsLqNanK1uSVYHOqHcitW4SNS6H6g3NSvAtgVtXW4(suM9GmGc7RCikuOaYemo7jFTtXW4UX9vHXS)ovuKO)usIKpIA1g4xgrTAdKZwPnz)DQOirFjjWwPiG8bfj4Sg4csx(GRrefjbVosq9GKBKagK93PIIeHRcJz)IsuofNjk7Vh598(P4mrzR(JmfBu9aKpmejBC)Qia3i7dfgs6wdfgkG1qHHMBnuyiPAnu46ZWVkcW(YMiC35IgjyjbG6(vragRJsXnY(1NBg(PcdVkcWnYELFQWWRIamwhLIBK9k)uHHxfbypz1VZyueaxym7t3iGpn7xJiksoRkfGjBIq)w0So6bi)en7lnlAGnVgy7AsM1NcuUdiWwW9cfb8qa(uavHxusx5ShGSA1VPhGMToKvBa

**Comment by InfusOnWoW** [comment]
That's a too fringe use case for negating zone id/zone group id., What you want can easily be accomplished with a custom trigger.
