### ISSUE TITLE
allow the user to search for a zone id by name

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#659]
Figured I should make this request before I forget about it

**Is your feature request related to a problem? Please describe.**
The problem is that there's no easy way to find zoneId/zone groupID unless [you know the command from below / you mouseover zone Id/ zone group Id in load tab while being in the zone]

**Describe the solution you'd like**
Entering a name in zoneID/zone group id could be used to return return the zoneID / zone group ID

for zone group ID something like this could be used:
`/run for i=1,2000 do if C_Map.GetMapInfo(i) then if C_Map.GetMapInfo(i).name == "Uldir" and C_Map.GetMapGroupID(C_Map.GetMapInfo(i).mapID) then print("Zone GroupID: "..C_Map.GetMapGroupID(C_Map.GetMapInfo(i).mapID)) break end end end`

for zone ID this could be used: (doesn't return anything since it has a groupID)
`/run for i=1,2000 do if C_Map.GetMapInfo(i) then if C_Map.GetMapInfo(i).name == "Uldir" and not C_Map.GetMapGroupID(C_Map.GetMapInfo(i).mapID) then print("ZoneID: "..C_Map.GetMapInfo(i).mapID) break end end end`

something to note is that there are occasions where zone group ID is not available, that's when there's only a single zone ID. if that's the case, you could make it return the specified id in zone ID instead of zone group ID.

edit: it's also localized so a german could search for "Freihafen" and find it.

**Comment by InfusOnWoW** [comment]
Well, patches welcome...

**Comment by emptyrivers** [comment]
What was even the request? Do you want a button in the Options panel somewhere that spits out the number you want when pressed?

**Comment by Causese** [comment]
how about making something appear upon clicking zone ID / zone Group ID?
for example:
1. you click it
2. new window pops up, you get two choices, a) I know the ID b) Search for ID
upon clicking a) you just hide the window
upon clicking b) you get to enter a name which spits out the ID, once you click Proceed it automatically enters it in either zone id / zone group id.

it might also be important to add an example that makes you aware of exact name being necessary to get a result, e.g The MOTHERLODE!! works while The Motherlode doesn't.

my brain just can't find a way to make a button look nice in Load so maybe this would be better?

**Comment by emptyrivers** [comment]
Well, I don't like the idea of window popping up out of nowhere when you focus an editbox. This would probably work better as a commandline option, honestly.

**Comment by Stanzilla** [comment]
We currently have tab complete of spell names which no one knows about, we could improve that in the same way the chat or mail UI show auto complete options for char names and use that on both places?

**Comment by Stanzilla** [comment]
Reminder for me: I think there is a spell name tab complete ace3 widget in grid1

**Comment by emptyrivers** [comment]
@Stanzilla, did you ever follow up on this?

**Comment by Stanzilla** [comment]
No, but I still think it's a decent idea

**Comment by mrbuds** [comment]
Now that tooltip show all zone ids and zone group ids for all dungeons and raid of current extension, is it still something we want ?

**Comment by InfusOnWoW** [comment]
I think we don't need this anymore.

**Comment by Stanzilla** [comment]
Agree
