### ISSUE TITLE
If you check Auto-clone but don't uncheck it "Show On: ___" stays hidden

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#662]
**Describe the bug**
If you enable Full Scan and then "Show all matches (Auto-clone)", "Show On: Buffed/Debuffed" is hidden.  If you then only uncheck Full Scan but not Auto-clone too, the Show On dropdown stays hidden.

**To Reproduce**
1. On an Aura trigger check Full Scan
2. Check "Show all matches (Auto-clone)"
3. Uncheck Full Scan
4. Show On dropdown is missing

**Screenshots**
![wowscrnshot_082118_100925](https://user-images.githubusercontent.com/3958649/44417564-c52bed80-a52a-11e8-9916-7c46e0d86026.jpg)

**Which version of WeakAuras are you using?**
2.7.2

**Comment by InfusOnWoW** [comment]
Should be fixed now.
