### ISSUE TITLE
Change Glow Color

### ISSUE THREAD

**Issue by disc0infern0** [WeakAuras/WeakAuras2#665]
Can a region setting be added to allow the glow color to be specified? 

Changing the glow color could then be done programmatically to indicate different conditions

**Comment by asakawa-k** [comment]
The glow used in WeakAuras comes from the Lib that utilises Blizzard elements that are yellow. 
Various different ways to "glow" Auras have been developed on the WA Discord so I recommend you go there to find/discuss your options.

**Comment by disc0infern0** [comment]
Will do. Thankyou for replying so quickly.

**Comment by InfusOnWoW** [comment]
I'm pretty sure the orignal wow glow that we use, only supports yellow. And that's the only glow we support atm, so that's not trivial to do.

**Comment by Dooez** [comment]
Desaturating glow textures and setting vertex color allows for okay colouring

**Comment by emptyrivers** [comment]
Oh, this has been implemented for a few weeks now.
