### ISSUE TITLE
Condition custom code on false

### ISSUE THREAD

**Issue by Dooez** [WeakAuras/WeakAuras2#673]
Custom code is executed when condition is met. Being able to run code when condition becomes false would be useful and save some space.
Possible solution is creating 2 text fields when "Run Custom Code" is chosen. Altenative could be adding option "Run Custom Code on false" and renaming current option to "Run Custom Code on true" for backward compatability and less space usage

**Comment by InfusOnWoW** [comment]
No, there's no reason to have that, as inversing is mostly trivial and that doesn't fit how conditions work.
