### ISSUE TITLE
"Crop" behaving incorrectly with Progress Texture

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#674]
Altering the value of Crop on a Progress Texture behaves differently with different Orientation settings.
When using the 2 Crop settings on any of the "straight" Orientations (Right to Left" etc.) Crop obscures a portion of the image. When used with Clockwise or Anticlockwise Orientations it just changes the overall size of the Aura (even changing the Width / Height settings). 

One _can_ still crop the image by setting to a straight Orientation, making the changes, then setting back to Clockwise.

**Comment by InfusOnWoW** [comment]
Should be fixed.
