### ISSUE TITLE
[Suggesstion] Streamlining creation of multiple template-based auras

### ISSUE THREAD

**Issue by eyriewow** [WeakAuras/WeakAuras2#678]
This is somewhat of an extension to https://github.com/WeakAuras/WeakAuras2/issues/647

**Is your feature request related to a problem? Please describe.**
Creating several auras at a time that are meant to be in a (dynamic) group is a very repetitive and for me at times frustrating process. 

- Create group
- Create aura from template
- Find created aura in your (often very long list of auras)
- Put aura in group
- Repeat 2-4 depending on how many spells you want to monitor

Another issue with the current template based creation process arises if users intend on monitoring a lot of traits or cooldowns. It's very easy to lose track of the auras that have already been created (since users can't see the existing auras while in the template screen). 

**Describe the solution you'd like**
In the screen where users select what type of aura they would like to create there should be an option to create a group or a dynamic group of icons or progress bars. Here's a mockup:
![](https://i.imgur.com/OFDthiJ.png)

The user should now be asked to put in the name of the group they would like to create.
After naming the group the user should face a similar screen to the regular aura creation screen which should allow the user to select multiple templates before the addon creates the icons.
Mockup of this screen:
![](https://i.imgur.com/8v965EC.png)
(At the bottom next to "back" and "cancel" should now be a button to "create group" - I forgot to add it)

**Describe alternatives you've considered**
Can't think of any alternatives to this. Something like a web tool that would create import strings for users as an alternative to the template system would be possible but probably even more effort.

**Comment by mrbuds** [comment]
I like your suggestion, i have started something which would work with any regionType
- Hold ctrl for multi selection, a new "batch" button show
- Click "batch" when done
- Select template for each spell (to do)
- Add all templates, without group, or in selected group (to do)

![mockup](https://i.imgur.com/Wfq1FQN.png)

**Comment by InfusOnWoW** [comment]
This is part of the next release.
