### ISSUE TITLE
[Suggestion] Option to center text on bars

### ISSUE THREAD

**Issue by capitaldeath** [WeakAuras/WeakAuras2#681]
Hi, so on progress bars we are able to add text to the left and to the right of the frame, and as you may have surmised from the title I'd like there to be an option for centered text. I don't know how difficult it is to implement but using multiple space characters to 'hack' the positioning of text is bad, imo.

**Comment by emptyrivers** [comment]
(Duplicate issue.](https://www.wowace.com/projects/weakauras-2/issues/307)
