### ISSUE TITLE
Incomplete Condition Properties break/error aura

### ISSUE THREAD

**Issue by sragia** [WeakAuras/WeakAuras2#685]
Currently I am on dbf17916668799 (2.7.4)
So there's basically "multiple" bugs here related to just selecting property but not changing it's value
All range values default to 0 (Alpha too but that is intended and fine i would assume) which cause some misbehaviour/error and values with select (dropdown) when nothing is selected seem to throw error that `options` are nil
But still gonna list all issues I found
1) Text Size defaults to 0
`1x WeakAuras\RegionTypes\Icon.lua:538: ERROR: <unnamed>:SetFont(): invalid fontHeight: 0, height must be > 0` think that's pretty self explanatory 
2) Width/Height defaults to 0
Doesn't throw error or change aura size (if only one of them is 0 other won't change either) however if you let's say add glow to it when either on them is 0 you get https://i.imgur.com/9voL0OS.png
p.s changing icon size seem to kinda break glow but not sure if that's a bug on WA side. https://i.imgur.com/HC1kZzW.png Think it just doesnt like that icon changes it's size and half of it is adjusted while other half isnt
3) Leaving empty value for Sound/Chat Message throws these errors

Sound
```
2x ...aceWeakAuras\RegionTypes\RegionPrototype.lua:143: attempt to index local 'options' (a nil value)
...aceWeakAuras\RegionTypes\RegionPrototype.lua:143: in function <...aceWeakAuras\RegionTypes\RegionPrototype.lua:139>
...aceWeakAuras\RegionTypes\RegionPrototype.lua:176: in function `SoundPlay'
[string "--[[ Error in ' New' ]]local newActiveCondi..."]:36: in function `?'
WeakAuras\WeakAuras-@project-version@.lua:4268: in function <WeakAuras\WeakAuras.lua:4256>
WeakAuras\WeakAuras-@project-version@.lua:4359: in function `UpdatedTriggerState'
WeakAuras\BuffTrigger.lua:828: in function `ScanAuras'
WeakAuras\BuffTrigger.lua:1365: in function <WeakAuras\BuffTrigger.lua:1361>
```
Chat Message
```
7x ...aceWeakAuras\RegionTypes\RegionPrototype.lua:186: attempt to index local 'options' (a nil value)
...aceWeakAuras\RegionTypes\RegionPrototype.lua:186: in function `SendChat'
[string "--[[ Error in ' New' ]]local newActiveCondi..."]:30: in function `?'
WeakAuras\WeakAuras-@project-version@.lua:4268: in function <WeakAuras\WeakAuras.lua:4256>
WeakAuras\WeakAuras-@project-version@.lua:4347: in function `UpdatedTriggerState'
WeakAuras\GenericTrigger.lua:637: in function `ScanEventsInternal'
WeakAuras\GenericTrigger.lua:620: in function `ScanEvents'
WeakAuras\GenericTrigger.lua:680: in function <WeakAuras\GenericTrigger.lua:671>
```
4) Spark width/height also defaults to 0
Same as width/height just stays on im guessing default size

------------------------
Another thing that was quite interesting is that if you have something like this https://i.imgur.com/R4N62uf.png, it won't change size (no errors), but if you add erroring Text Size https://i.imgur.com/IMZ10Vw.png it does

**Comment by InfusOnWoW** [comment]
Should be better now.
