### ISSUE TITLE
Dynamic Group - Arcs

### ISSUE THREAD

**Issue by vraolji** [WeakAuras/WeakAuras2#687]
An "Arc" option for a Dynamic group. Where one can define the angle of the arc and length.

Currently using clockwise/counterclockwise and radius, but these assume a full circle. In order to clump elements along an edge of the "circle", blank placeholders need to be made to fill the circle and force the visible objects in place.

**Comment by vraolji** [comment]
Or another option would be to add a "Arc/Bend" option to a horizontal or vertical group, similar to "Stagger" but would evenly spread them in a arc by the defined number.

**Comment by emptyrivers** [comment]
This is now available in the latest alpha.
