### ISSUE TITLE
Hybrid sort fails to correctly sort clones in some cases

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#689]
to reproduce:

- create a dynamic group
- add a child which produces clones to the aura
- mark the cloning child for hybrid sorting

Here is an example:
```
dOZ)caGEvH6LkuSnb1Sf42kOBIeoTuFJQ4YI2Pq2lz3kTFQOrPqvdtb(nu)LI0qPOAWujdNkCqvjoQQOogfohvPfQQAPkuAXuvlhX0qspfSmvfphvtKIyQkAYuA6sUOQKUQQqEMQuxhL2is0wviBgITli3Ik1Luf5Zq67QWivf4XOy0QOXRQ0jvOYzvf01qQoVqnokkhwL(jszzOPGRMQeWfysgsWqbwbwnf8LgccplrP7WgVP)XdDV0d75TH3bufIBQufWXK6bX(K2oV(bPMc8zrq46xLGERKS3GrjH34vrHfeGVwnfWYttzcUCU8vjGKOnENXosb249oSzqjywhcoJ9jT1CmVRgVcoJ9jTLYMWlbCmPeCg7tARG8RJ7AtR(f0wbvYlbX0qq4zjkn7dDV0F717BpEmZJ3bufIBQ0fW2wbdF9N(ONFEWp7yeCg7tAlGjffyBkWMCMCT9IkGNbiMJ7TemPzUkbmAQidnfCzQouojnkAsOaBtf52yGGI0OOjrtb(SiiWj(G2kGFIpOTVWuDOuWLTWmb4n1Vae2GaoZD1Vkb9wjzVbJscVXRIclGKOnENXosbndEfu53YqWtRG2kWNfbHlGTTcE8HjNJI)F1S5HGE7YuEDjvAvKHagmoWIpw9RsrF0uWLP6q5K0OOjHcSnvKBJbcksJIMenfS3HjxtfziyS5Mh9I60ffnVujWNfbboXh0wb8t8bT9fMQdLQe0BLK9gmkj8gVkkSasI24Dg7if0m4vqLFldbpToD52PRfxoDDD6IjaVPG2kGKBE0lQtxdBEjGTTcUpA8pCCS(EmHQdb92LP86sQ0QidvQeesrgu)yOsc
```

Expected:

Clones are sorted as usual, just separated from the non-hybrid members of the dynamic group.

Actual:

Clones seem to be in no particular order amongst themselves, and can change order without warning, seemingly at random. Static and dynamic durations are happily mixed, which also seems wrong.

Here is an example of what the above import can produce. Note that growth direction is down and descending, but the chi torpedo buff is sorted as above renewing mist, which has a longer duration, and Inner truth which has no duration is between them.
![img](https://i.imgur.com/iXhkkxU.png) 

Or in this example, everything is even worse! 
![img2](https://i.imgur.com/j8EJLKT.png)

**Comment by InfusOnWoW** [comment]
Should be fixed.
