### ISSUE TITLE
Taxi in load tab

### ISSUE THREAD

**Issue by jsassner** [WeakAuras/WeakAuras2#690]
I would like a "Is in Taxi" option in the load tab so i can do stuff when using the flight paths. I know i can add a trigger per WA, but it would be much easier to add that checkbox for a group of WA's.

**Comment by asakawa-k** [comment]
Seems way too niche for a Load condition. 
Maybe a tick box in the trigger `status - conditions`?

`custom - status - UNIT_FLAGS`
```LUA
function(_, unit)
    return (unit == "player" or not unit) and UnitOnTaxi("player")
end
```    
For the trigger

**Comment by emptyrivers** [comment]
This will be integrated into the Vehicle Load option. So enabling "In Vehicle" will cause an aura to load while you're on a taxi.

**Comment by InfusOnWoW** [comment]
This is implemented for the next release.
