### ISSUE TITLE
aura_env.state.name not returning valid unitID for xrealm players in a group trigger

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#693]
**Describe the bug**
well, aura_env.state.name prints SomeName - SomeServer instead of SomeName-SomeServer.
SomeName-SomeServer (without gaps) is required for valid unitID.

trigger is group buff trigger with show all matches enabled

%n works just fine.
**edit: %n also returning SomeName - SomeServer** (which makes sense :'D)

**To Reproduce**
1. import wa from below
2. queue for bg or whatever and cast raidbuff 

**Screenshots**
https://i.gyazo.com/331209a4b24160a7e6a228cf7d874d6e.png
edit: red is WA_ClassColorName(aura_env.state.name), blue is %n

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
2.7.5

``` di02eaqjjvQpjjIrbf6uqb3sfzxQcdts6yawMQ0ZuIMgiDnGSnu03Kughk15urTojv1bHsTquWdvHSrOiFusuDsjHvcuZusfUPsq7uHFQkAOOqhvsfTujvYtPmvqDvjvzRqr9vLqJvsuoRkuwRKiTxXFrjdwrhgvlwf8yOAYQ0LjTzQYNPQgnrCAcRwfQETsGzRQUni2nKFtLHRKwoINlX0L66k12jsFNOmEIQZdLSFKoabogpWPJvI9(O2dqXGe7g7g4yYF65v0oy6uTAqRcceBMlzVeOgiMSJ3jOqJjqTsq8pMvsr4qzWmwr)Em6eOog8tgJ9D8BGJTlkl8pVuYH0XiQVWHGXAvJDXcXHiW9jU9Amv(khD1ByiM4gBOYOZ3yBXngJ)JXagwusfYxw5XW6PNxr7GPtSbXg6z2aqFREMji2SzhVtqbLogEGZaiWXiQVWHGXAvJX3e(bojg(U0oiWQ8oM3gH3chcJyGcMoPt6KofE0jFt4SuK0hLM3kDYrx6KVjCwks6JsZB9bIdrPZwIIOGPt6KoPt6KoPt6KO9MGOZfXM1rFEPCK77idoefJ8nHZsrsFuAERpqCikgOGPt6KoPtfDPGv0LcMcMcMcMcMcMcMcoghVfsvyIW3xjl0D1mobunMa1kbX)ywjfHdLbZyxrz9ZXcwL31H61XQB8ynr47RKahZN42R4FhsddX2fLvzvXfEcCwBKOZHyLv9)R4wcCgazaaf05mEZGnWlW5mwMbaatO1shBJeDmFIBVgdXHOLaNbqmSj4CKsNvGA9)v8oJ3ymW7(R0PjXT7mwgJrNmLqNl6i36tNMeH(VPJDy75zsCYEIIvK4K9eHnElKQPJjUXUoTGQKMoL5ilGo9Ce6uor5FiXW3L2bbwL31B9YBnMkvrDmbs0SknN06ndGyBXnwDvz15r)Q(czVyNoJ3ah7aNCK77ibodGmQMXBWeiMGaavJz1QVNRbTg0QX7eiMzSmdG0XiQVWHGXAvJX3e(bojg(U0oiWQ8owmoElKQWeHVVswO7QzCcOAmbQvcI)XSskchkdMXAIW3xjboMpXTxX)oKggIvw1)VIBjWzaKbauqNZ4nd2aVaNZyzgaamHwlDSdBpptIt2tuSIeNSNiSXBHun2UOSkRkUWtGZAJeDoedXHOLaNbqmSj4CKsNvGA9)v8oJ3ymW7(R0PjXT7mwgJrNmLqNl6i36tNMeH(VPJTrIoMpXTxthtGenRsZjTEZaig(U0oiWQ8UERxERXuPkQJjUXK5ilOqNYjk)dj2wCJHXIeFpFVJd(yvA60XKMba0xG0ja ```

**Comment by InfusOnWoW** [comment]
That has always been the case and I don't think that should be changed. %n is after all meant for user, not for lua scripts. 0c5b1ba6542d96580d91a6b3cc1df0364a42eb76 introduced that.

If you want to use that with WA_ClassColorName, you have to remove the spaces.
