### ISSUE TITLE
WeakAuras.lua has exactly 200 local values in the main chunk.

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#701]
This is not a problem right now, but it does mean that any new local value (such as validateUserConfig, introduced in #694) will cause lua to error out before it finishes executing the file, and so that number will need to be brought down.

To deal with this, we can do a combination of:

- use fewer local values
- chunk up the file explicitly using `do ... end` blocks
- split off some code into separate files

**Comment by Stanzilla** [comment]
The Lua upvalues can probably all go away and we could move the profiling stuff out into its own file?

**Comment by emptyrivers** [comment]
Splitting off profile gives space for 11 more locals, and getting rid of all the upvalues would give another 68

**Comment by emptyrivers** [comment]
I'd kind of also like to split off the aura_env support and combine it with HelperFunctions, but `exec_env` is tangled with Anchoring and Actions.

**Comment by InfusOnWoW** [comment]
The Conditions code can be moved out, though I don't know how many upvalues that uses.

**Comment by emptyrivers** [comment]
#707 removes about 80 local values from WeakAuras.lua, amongst other things. I didn't touch conditions, though, which is worth another 20 or so upvalues.
