### ISSUE TITLE
Labeled Triggers to maintain clear naming for conditions

### ISSUE THREAD

**Issue by souleiman** [WeakAuras/WeakAuras2#705]
There are times where it's hard to keep track of which trigger is which in your conditions table. It would be nice to track which conditions by allowing us to label triggers. With the introduction of conditional AND OR operation it's become messier to maintain and track, this would help making it easier for maintain WeakAuras for authors and alike.

For instance in this image below, it would be helpful for me to know what `Trigger 2`, `Trigger 3`, and `Trigger 4` is doing.

![image](https://user-images.githubusercontent.com/1203609/45010477-cc97d000-afdb-11e8-98b7-de26b3c4984f.png)

In this case, as a user I'd like to be able to label the triggers in the trigger tab for each trigger and when applying these trigger in the conditions tab I would like to be able to see the labels instead of have to keep switching between tabs.

For example, I would like to be able to see instead of:

`Trigger 2` -> `Trigger 2: Mortal Strike Usable`
`Trigger 3` -> `Trigger 3: 2 Overpower Stacks`
`Trigger 4` -> `Trigger 4: 2 Exec. Prec. Stacks`

**Comment by Stanzilla** [comment]
Custom labels no, showing more info on what each trigger does, maybe

**Comment by souleiman** [comment]
Mind elaborating why not? It would be synonymous to variable naming/commenting.

What did you have in mind for showing more info. If it provides enough information to tell me what the trigger is, I can get behind on that. Although, I'm curious to see how you will handle that for custom triggers.

**Comment by Stanzilla** [comment]
Most because of the UI overhead/complications it would cause

**Comment by InfusOnWoW** [comment]
I agree with Stanzilla, no custom labeling for triggers, and maybe automatic labeling.

**Comment by souleiman** [comment]
Ah, sounds good. Appreciate the response.

**Comment by emptyrivers** [comment]
As a counterpoint: Custom Options in `Author Mode` names the headers based on the display name, to help the author navigate the sea a bit better. So it's not as if we don't have a precedent anymore.

+1 from me.

**Comment by alexisakov1** [comment]
+1 this would really help to keep track of things in Conditions without going back and forth between Triggers and Conditions tabs.

**Comment by wing5wong** [comment]
+1 on this. 
When comparing it to custom options which can have a name/description, it would be great if triggers and conditions had the same - it’s far easier to tell at a glance what you are dealing with rather than following code/config to determine it.

**Comment by wisnoi** [comment]
+1.
Have run into situations where I have multiple triggers whose only conditional property is "Active", which can make it easy for me to forget which trigger does what.

**Comment by Nivius** [comment]
so i se the issue you guys present with it, then again, cant you work around that?
add a dscription line + text line above "type" in the trigger. there you can fill in 1-24 characters. Display that next to Trigger 1 in the UI.  or if you hover over it and in the dropdown

i have troubble seeing how it is not somthing that it isnt somthing you can work in. or is there any other reason? an automated system whould be "ok" i guess, but still a bit wierd.  Maybe have the values displayed in the dropdown menu related to the trigger?

im sure there must be some way of solving this
