### ISSUE TITLE
Action Usable > Require Valid Target does not work for pet dispel

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#706]
**Describe the bug**
Action Usable > Require Valid Target doesn't seem to be working for hunter pet dispel.

* If I check it, the aura won't show up at all (enemy or friendly target)
* If I leave it unchecked it shows up for both friendly targets and enemy targets

Testing as a hunter with spirit beast pet in duel.  The spell I'm using (Spirit Shock) can be used on enemies, but not friendlies, and can be used even if there is nothing to dispel.

**To Reproduce**
1. Import aura, have Spirit Beast pet
2. Target friendly
3. Aura will not display (correct)
4. Join duel and target enemy
5. Aura will not display (incorrect)

**Which version of WeakAuras are you using?**
2.7.5

**Additional context**
```
dCeWfaqivLuJsvPCkvv4wkj2frv)svvnmc1XuILbspJOyAcvxdeTns4BeIXbkohiyDkjL3PKuDqjvTqLupujjMOQs0fLuzJQQYhvvcJeukNuvjzLQQKzsi5MQkv7KGFkP0qbLSucPEkYuvPRccTvLK0xbLQZkPiVvP4UkvTxQ)cQgSkoSOwSQIhlKjtsxg1MjrFwIrluoTIvRQs9Avv0SfCBISBs9BPmCj54skQLd8CrMo01vLTRu67eLgVsLZtuz9skSFPAV4RPXclYOqmeuykzcQ8IipKMKmPAs1xtiVdx(RPrAQbBHL4MEAemLcd81uQIdbHSeBHL4IiJcOgnLJWzlFbtPWGV3uzlSYIytpqWumeRsR2))lBU0KFA)xV0utp5wb2EAKbRa7zGE0L0)WycbtPWaFn9sm8rVLbj2FmvyndMikwt2A1MsXAYwRU(iC2YMsvCiiKLylavrCOkG0ekxfBkHz8Lm908wwJMYpSzk6LWMe8yJkBchjw1eVL1OP6JWPP7hiMYFcSPxIHZ7Yri8ufhcczj2Fmb4CGQ4qqilXMOQbmy)qXAr)00lXWtvCiiKLyV20lXWXmOWOO5A(naw1Rn9sm8NEqV2OPSEKY400(AskpAFnHYvXMQaCIrtvaoXOPQxiXgnAsLtrMGyk)jW9d26h1jvXH(jRv7hmg3pyguySFILt9tUFuNufhc5pbUFynix4(5ZtPs5nH8oCbwTrJMU1cltYvRsLjgTamXnfJNsm0cWi2uul0a(AH4wqS8ISiwSyXIfdJmXJRasJMcTSQVMgDb0Ev(As6fWXxJgn9smCnVLb(Jjmhyn6RjPxahFnA0uQIJ81uA0LaBHftsVao(AHfV2cq9AJgnffYPKVMsJUeytWgefU1jAJMEjgEuiNsETjqlW(As6fWXxJgnH5aRrO(As6fWXxJgnvTTcZbwJ(As6fWXxJgnbYrSVMKEbC81OrtkZr400(As6fWXxJgnPokvorVakNVMKEbC81OrJM2vRsLjg9FWSOaQiIOiUiqfdbOkuiJvUsCinPoPF)0r4SLnLdbtYoQymlaJytiVdx(RPrtxzHVkSg(3VWx3cQMIEjSjDbtPWar1ktKjLpDeon93qWukm4h9F1p9t)0pagFaD)8nemLcd2SSVFAG(bbtPWGnq33pnq)GGPuyWgz23pnq)GGPuyWM477NgOFqWukmydK77NgOFqWukmyJI99td0piykfgSrK99td0piykfgSbM9)OFYA1(bbtPWGnqy)Q3)fRvnb4Y00x5QyttutBAunblgxHQgWG9dfRf9Z(P(iCA6(bIP8NaBc5Di0)AAKMAWwybgtkbzjMqqgZwastJEq4rnPQaJSQfwmH8oCX0x(veSQtuFTjK3HqnvNGOR)lQZunAnjliwEOqWuwvDWPPZb4iykfgK81OjK3HqRtN)eyvV20BunrRffasiLG(BzLX0OheEcZaKvTWIPrJmqNdRkdsttBbfgnT1clXHUy0ga
```

**Comment by emptyrivers** [comment]
Pretty sure this is a problem on blizzard’s side.

**Comment by emptyrivers** [comment]
As in, internally we use InSpellInRange to check if a spell has a valid target (it returns nil when you don’t have a valid target), and it seems plausible that blizzard never designed IsSpellInRange to handle pet spells gracefully.

**Comment by InfusOnWoW** [comment]
Yeah, seems that at least Netherschock never returns anything for IsSpellInRange. So the "Requres Valid target" can't work for pet spells. I'm not aware of any other api for checking if a spell is usable on a target.

As to the second point, with "Requires valid target" not checked. Even you have a friendly unit target, the action is usable, e.g. via a mouse over macro or a focus macro.
