### ISSUE TITLE
"Dynamic information from first active" icon prioritizes Trigger 1 with Pet abilities

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#708]
**Describe the bug**
WA is using the first pet ability in the first trigger for the Dynamic information for Automatic Icon instead of the one that's available right now.  I have Nether Shock (Trigger 2) available on my current pet, it shows Nature's Grace's icon from Trigger 1.

If I move the current pet's ability to Trigger 1, it shows that icon.

If I start with the spell from Trigger 2, it uses that icon, but then if I switch to the spell from Trigger 1, it stays with that one, even if I switch back to the spell from Trigger 2.

Pulling out a pet that has the same type of ability (ie. Moth with Serenity Dust) will activate the aura, even though Serenity Dust is not part of the triggers.

I'm not sure if this is pet ability weirdness or because of Custom Activation function, or what.

**To Reproduce**
1. Import aura 
2. Start with Nether Ray pet
3. Icon should be Nether Shock
4. Dismiss and summon Stag
5. Icon will switch to Nature's Grace
6. Switch to Nether Ray
7. Icon will stay as Nature's Grace when it should switch to Nether Shock
8. Icon will stay as Nature's Grace until relog

**Which version of WeakAuras are you using?**
2.7.5

**Screenshots**
Video: https://i.imgur.com/QVYRxxK.gifv

**Additional context**
```
dGuNhaqisc1NafXOijYPijXTuu1UKQQFrsPHPqDmq1YiHNbsmnfLRPOY2Ku9nPQmobX5ijQ1bksVJKaheKAHIWdfrMijfUOGYgbr9rskAKcQ6KGcRKKKMjjv3usXof4NIOgkO0sbj9uvtvkxfezRKe0xjjKZckkVvsPURKs2l1FvWGLkhMulwrESqnzHCzKnljFwPgTuLtdSAss1RbfvZwu3wK2nHFRKHlrhNKuworphLPdDDuTDs03fKgVc58GW6fuz)syd3nFGdGYSqMREDFMVI(7R)58t9J8JCZhPriCiVe4bHJCa8z(qKCvfJqheYmFDmcusnjyVjznRiYbZdFSpxM97HyjdMQw1gQEV6hSul0PayghI5dpxGKCEvKwkaIntTH4RfGuncwc38t1aHB(ieLKFPKye6xkjgH(L8mJmA0hLG9MKU5Jqus(muJCMpNrd6j2sovZkICcFsjjqFOJrWsu0bjMEkt(ssNFjLZb6uYpqJCjbtyfDQPuht(CgnWkPCoqNsoHpNrdCbaDcFUGusc0xZXLpNrdOwUjeQKQXbskYt(SskNd0PKduuFMI61n6pk5QkgHgYHaVUI(6R(S(umwLvuVouC18ZMZhPriCyxab63sgw)iat15IyeOK8J5mCL63Ja7EOdczSFEPJCZhi2YfV0n)uEgbUz0OpNrdcsjj9KpQZKaDZpLNrGBgn6hN1mMB(mGyNj)WdPGwyq1OpRKIDZNbe7m5a4(P8mcCZbWDchOWjmA0pcuvbI5zec38t5ze4MrJ(YvMCZpLNrGBgn6Zz0qCwZyoHFPYsuNjb6MFkpJa3mA0VshJGLWn)uEgbUz0OVuhtU5NYZiWnJg9rDMeOc38t5ze4MrJg9JiwSpKy6Pmv0HRIUiaRKYfDArurh2Jk6qTCtyrxpnROtx0fbyLuoRNYurhjK6nv0nXRQ63hPriCiVeOFl0HKiXqnTHeRCKpsJqfHj0tzkYj8J5mCL2KG9MKQV2Gy)kUigblHkHsWEtsvPqvl6k6k6k6KeYLIIovcLG9MK1gETk6wYIouc2BswBf1svk60IOIouc2BswBOulvqHQsIiFjTblrdIsYheVe(6OiacwcDEaLG9MKm3CaC38rjyVjPB(ieLKpd1iN5Z4tKssGNxvbg5pKe0Vn8g0qT5Zz0GEITKt1SIiNWNusc0h6yeSefDqIPNYKpNrdCbaDcFjPZVKY5aDk5hqypsw09ERyyUpNrdSskNd0PKt4Zz0aQLBcHkPACGKI8Kpxaq)YSgcs6Z4tKssGWkPkWi)dByQRUpxqkjb6R54YNvs5CGoLCGI6ZuuFMrFUaLG9MKUz0Odu4Mpkb7njDZNZOHyndBqusEYpIM4vvjL1mMFQEdI93KGKG43BfAYcFwVvOjlGogbkjFoJg4ca6e(r0eVQQbrj5h(Wuhwidj195mAaiqsk5LiyktoHpcrj5R5sTpNrdr0eVQkPSMXCcFUGusc0xZXLpPKeOFsAg6hZz4kDOhiI8rqkf5Z4tKssGNxvbg5pKe0Vn8g0qT5pXRQEVvOjl8z9wHMSa6yeOK8zLuodJiMBg91CCfNxcYt(cDkXCZOpxaqFul3e6Z4tKssGWkPkWi)dByQRUFfpNzXAHty0NlqjyVjPB(Cba9rTCtOrJg9rAeQaYlbEq4ihapeFGaGdXR0YmHuKdG7J0ieUVAaJdByQRI9d3AL6GX9RqL9rAeQWVgOvtyKKFLuNshLAu7G58br(Ws48QbGvs5IUA0BqCrhmIxIIUgXq)qbrypheYy)4vEjDZbZCW4(7d(4XJhpECiqz2S6Zz0NdI8vDyewnHfkqmxFHZxWtBsWEtsMdGIpqaWbgQLif5a4(abssHoRcjjdSeoOUrFLoa(mfWnAd
```

**Comment by InfusOnWoW** [comment]
The problem is pet spells are strange and even the default ui is very confussed about them. I've split your aura into its individual triggers, so that it is clearer what is happening:

So, after login with no pet out:
GetSpellCooldown for both abilities returns nil
Both spells on the default action bar are shown greyed out.

After someone the stag:
GetSpellCooldown for its abilities works
GetSpellCooldown for Nethershock returns nil
Both icons on the action bars are shown normally, even though trying to use Nethershock just does nothing.

After switching to the Nether Ray:
GetSpellCooldown returns values for both abilties and will apparently alyways do so
And again both icons are shown normally on the action bar.

**Comment by InfusOnWoW** [comment]
Simple triggers:
dquTlaqifvQrPOcNsrfDlbLDbPYVGeggLQJPiltqEMIQmnfLRjL02iGVjvQXPqDoivTobv6Guv1cfvEivLmrQk1fPQYgLk5Jek1iPQOtcj6LekPzkLWnjq7KQ8tiLHsOAPsj6PGPs0vfu1wPQqFLqjoRIQAVO)kQAWsvhwKfdj9ykzYsXLjTzc5ZqmAc60kTAQk41kQKzd1Tfy3u8BjgUOCCbvSCHEovMUQRlPTlv8DkLXRqoVuQ1tOy)kyorjHeL8eCe8T2HqaHgcnusiQiBXiBNPeqILAgHhxeen6OKEtus4XfbrJusarnACTaHfBOzi4ewSHMXFRVDuEEcjRVDuzCrq0OGLgLEt8ewZ1OjH9rn62IHEDtyBiiU(W896Yu8qVGjK1AOhLwfZqVuDFOxSJLAgbNIfjEznNqo0Ks0eSf(1LKqDBi4)8hlqN57VRJLFeWLudLeEcRMhIscbv8xk55jKejAhPokjeuXFPKNNWty1CkjeuXFPKNNqmzPusiOI)sjppblCY5OKGBniyLGpdVN0VwYtOzfjATQ43Mscbv8xk55jelyLscbv8xk55j8ewnFEusiOI)sjppHSozpHvZPKqqf)LsEEcRbjwQzusiOI)sjppbrjRVfdLecQ4VuYZtO608w4KZr4XQYtqhLLmnAdZXtWIs6nrjHRJ(uxfZHvmk9MMrOnAIe50ZUgpd9ttTotG5H(PwrFOUhtrHntac1iMGW)mx4IcuylHuq3wqH)b78RTdZNvZ1yyILu0Sgehkgt4XfbrJokP3eLeECrq0iLeQonFcvxjIQGLgL5iGOgnUwGWIn0meCcl28hBl12rWLPySxkqPxibMfsabi82zkb3tV6iuDAEe1OX1cewSHMH5iODuZj4Rsb3uSzg6fpwqIQZn0phqMIXZjHOMWqMIXEPaLG)MG6h6B04qVx61iHQtZ7Yum2lfOmhHQr7OMtivFHq1P5FkIOVLA4u3O2qujuDA(QzpZXtOAECrq0iLequJgxlqyXgAgcoHfB(JTLA745j0SoFOAS(2rjKmTjyvDVeiJlcIgBrbzTiqiz9TJkJlcIgfS0O0lSj78esMni9TyOKqqAnus4TZuczr1PNqwuD6jKvXoLNNW1rFs8YAobjAItqOUicp9gBNaUKAOKWAqILAgLecQ4VuYZtO608gTJgjQeEcRMtjHGk(lL88eSWjNJscU1GGvc(m8Es)AjpbxMArjb3AqWk9MieuXFPKEtmh9cXC88eAwrIwRk(TPKqqf)LsEEcXcwPKqqf)LsEEcpHvZdrjHGk(lL88eY6K9ewnNscbv8xk55jetwkLecQ4VuYZtquY6BXqjHGk(lL88eQonVfo5CmhpHRJ(uxfZjiTL3xQjVGY85k4gcR5A0KW(OgDBXqVUjevKTyKTZucRvXqyeAIe50tVPwTtWQGlrkP3m6zhDDpz3UD72TpEEZMjqR8eUo6H6QyoSIrP30ycxh9jc(gLG4(1I5MW1rpKFMeQyTH5iiMsjGE2rxi0tyBiiU(W896Yu8qVGjK1AOhLwfZqVuDNW1rpebb9xSrPViikMcu4X0t0Rvc22MlKEJTtOUne8bu6NG(zBnT2Tyi0OolcH3LqfRd9Vm03SUmfp0Nmnd9xOo0)uer)qVWKBOpn03SUmfJtOI1HE1eti6qpQvrIqhp9crjHRJ(uxfZHvmk9MMrOnAIe50ZUctGXZqFOPXDBxabea9Tooeff2SXeQrmbH)zUWffOWwcPGUTGc)d25xBhMpRMRXWelPOznioumMWJlcIgDusVjkj84IGOrkjuDAElHQ1CbzkglwnfBgMJq1P5tO6krufS0Omhbe1OX1cewSHMHGtyXM)yBP2ocUmfJ9sbk9cjWSqcmJWBNPeCp9QJq1ODuZjKQVqO608iQrJRfiSydndZrq7OMtWxLcUPyZm0lESGevNBOFoGmfJNtcrnHHmfJ9sbkbp9c1OZsyXAUiuDAExMIXEPaL5iuDA(NIi6BPgo1nQnevcvNMVA2ZC8eQMhxeensjbe1OX1cewSHMHGtyXM)yBP2oEEcnRZhQgRVDucjtBcwv3lbY4IGOXwuqwlceswF7OY4IGOrblnk9cBYopHKzdsFlgkjeKwdLeE7mLqwuD6jKfvNEczvSt55j0OolcH3LqfRd9Vm03SUmfp0Nmnd9xOo0)uer)qVWKBOpn03SUmfJtOI1HE1eti6qpQvrIqhHRJ(K4L1Ccs0eNGqDreE6n2obCj1qjH1Gel1mkjeuXFPKNNq1P5nAhnsuj8ewnNscbv8xk55j4Yulkj4wdcwP3eHGk(lL0BI5OxiMJNNGfo5CusWTgeSsWNH3t6xl5juDAElCY5yocXcwPKqqf)LsEEcnRirRvf)2usiOI)sjppHSozpHvZPKqqf)LsEEcIswFlgkjeuXFPKNNqmzPusiOI)sjppHNWQ5HOKqqf)LsEEEcwfCjsj9Mrp7OR7j72TB3U9XZB2mbALNW1rFQRI5eK2Y7l1Kxqz(CfCdH1CnAsyFuJUTyOx3eIkYwmY2zkH1QyiCD0d1vXCyfJsVPXeeftbk8y6j61kbBBZfsVX2jCD0Ni4BucI7xlMBcxh9q(zsOI1gMJW1rpebb9xSrPViSneexFy(EDzkEOxWeYAn0JsRIzOxQUp0hIGykLa6zhDHqpH62qq8UfgZf9joC8tsyeAIe50tVPwTZZtOd9MMfAINe

**Comment by InfusOnWoW** [comment]
But IsSpellKnown works for those spells, so I have a plan.

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
