### ISSUE TITLE
Broken masque skin for Icon aura again

### ISSUE THREAD

**Issue by Balur86** [WeakAuras/WeakAuras2#709]
Hello,

I still sometimes experience the same problem as mentioned here: https://github.com/WeakAuras/WeakAuras2/issues/639
Masque is incorrectly skinning Icon auras.

**Which version of WeakAuras are you using?**
2.7.5

**Was it working in a previous version? If yes, which was the last good one?**
2.6.6 if I remember correct.l

**Do you have an error log of what happened?** 
No error message.

**Comment by InfusOnWoW** [comment]
Please add a description on how to reproduce.

**Comment by InfusOnWoW** [comment]
I need a step by step instruction on what to do to reproduce, and a example aura that shows the problem. Clearly this is not exactly the same as your previous report, except for showing the same symptoms.

**Comment by Balur86** [comment]
Unfortunately I do not know how to reproduce it, it just happens in combat. I tested on a dummy in the morning but it didn't go wrong, but during outdoor combat it happens. How can I give you and example aura, Exported string?

**Comment by InfusOnWoW** [comment]
Yes exported aura, and as good as a description on how to reproduce as you can do.

**Comment by InfusOnWoW** [comment]
This also sounds very similar to https://github.com/WeakAuras/WeakAuras2/issues/648, which is a WoW bug.

**Comment by Balur86** [comment]
There are 2 Icon aura I use for Rockbiter, I don't know exactly the stacks>=1 or the stacks<=0 one goes wrong, let me test a bit. I think this has a connection with #648 you mentioned.

Rockbiter:
dWJGdaGAufEPuQSluPABsL2NuQAMOsmBKUjb8BI(MOQUTi2jkTxy3uA)Os6NeYWKsgNukNgXqfvzWOkA4IYbjiNcvuoMu15qvvlufwkb1IjqlxOhIkQEQYJvPNRQjIkutLIjlHPt6IOc58IkptI66sAJOk1wrvXMjuBxImkur8zumnub(UumsubDzQgTinEuv5WcUfQsUgQkDpur6VQOLjv8AuPm6HbJa2(YDB1wxShRd3ZN78flbRaRagSQvJeggpcd2NkBezX(uzJq0MqUh7ZCkLnK4GTN)LZVTUqXc2BQmMNKyvSdrgJib4chXBdw4QKsUjsyy8OaYchS8QVfgXQE0gO8XJprAbBxmnsyy8imy13pVPHiJ)4aJXTEKCxQSrKf7tLncrBc5ESBAiY4)PmZJbvgXApNIP5YCSxdA9XQVF(PYgrwCGvF)KXTEKCxQSrKfhyEj3QyCUuslKnwUYZ8IsMO)px5jNSmNs5mSpZPu2qId2E(xo)26If9aDzoLYgsCmHLxUjir9iw99ZpZPu2qIJdSQ1l5wfluvj2nnez8hRhR((zqWxgfuazHJdS67NvlrXbuSuNWKQGTClmQmuadgXYeL1myWsQuLaduOyAG6wfgSKkvjWafk2Lg(hgSNyzOo24qHeqiwOyAG6wTdmyjvQsGbkuSy46WGLuPkbgOqXkiIftUvQMdgSKkvjWafkwusDyWsQuLaduOy13p)m)IdSSszAG6wfgSKkvjWafk2N5xyWEILH6GTdumXHRsKwyWsQuLaduOy13pV0W)4akwb55r1EvsjhlqPy8tKyXVRGTNVyrNHiTMCzog5kTyb7nvg5DmK4MCzowEcZXyKcmHLxUjir9iwdPqtbB5wyvsbg)kB4bxAxdPfFeglNiXIFxblV60cJyj65RHO6fGTh7kL0czJfhqXkb2EoOtpua

Rockbiter bg:
dWd)daGAssTlsIEnjjZeru)MuZgv3wkDtePtt4Bk48sk7eP2lSBb7xjQFkedtjnoeLrrKkdfryWkHgUu5GKuDkLGoMcDojvlejwQsKflKwUipKKqpv1YikphLjssPPkQjljtNYfvc8zs8mIQRROnIOARePQnJK2Uq1Jr4RePyAcL5rsWire5YunAPQXtsX3vk3Ii5AsX9isP)QuDyj2grmgrgxa6r5swjtcodxMkhuzdElEfEfY41IqLkZnqlLSv8sGOxNiHwemCkrY5iKsYlG8mEHWeX9CsOO4js1voOLACf3C1yJliuIY9kef3scffpHm(K57e9LKIZafCfp4jbX71Brc4SE9M68TsngorFjP4SDDNNkMoHRcslorFjP4m8v8jZ3v8GNeeVxVfjak4tMVZ61BrcGc(K57ZGWafCpUhmCvuR5v6TWYlsIKwj5m2YlkDVZ58fIpz(EjktNIsQUYbf8Kx4VZ5C6sRJVKMqvrfMNWNmFN15CoDP1bfCRwNJZSInz4ZGh3dgEzAACwNZ50Lwh0J1LpqMey49UqP3aT8v8kbt1ZaHjI74fohNRlviJBfUhmziJ3o5MazyWWNmFp4X9eIIBfUhmKXBNCtGmmy4e8cJHmoteu4o(jj1jvDAy4jn3rgVDYnbYWGHpz(obVWyGcELGkvbXKB1qgVDYnbYWGHNkeoY4TtUjqggmCQfctOdiJ3o5MazyWWNmFN15eGcoRZjqgNjckCh0YGH3fVZkCpyiJ3o5MazyWWfbLKE2HmE7KBcKHbdg(myjHIINqgN1R3IeWz96n15BLAmCwNZ50Lwh0J1LpqMey4jxrOd5ADoUGqhW3evwpOLVIlQWxstOQOcZtlVyufCcnxNqg0Ya5nsAgBgKSUkR(qSHyRGQundGwoiVrsZyZGK1vz1hIneBfuLQza0Xa5nsKnq2O8HM6nXQhtozGQunYHHxce96e5PsRNR154Kyj1IRMiuPYCd0Jn4trfUQTkPH06b1MfCCrqy7mRKmVc0J4eAnVsVfafCrW8uOWLEpXe6aOLadpoOhJjBega

**Comment by InfusOnWoW** [comment]
I tried reproducing the bug, but couldn't see any issues in my testing.

I'm not sure it's the same bugs as #648, as in that bug report the "Set Parent to Anchor" options is not checked. Though I suspect it has to do with the anchoring to the PRD.

I've also reached out to our Blizzard contact to ask whether there's any news on that bugs progress, but so far I haven't heard back, and it's their second-to-last day on the wow team, so....

**Comment by InfusOnWoW** [comment]
I got a "didn't get time to look at it" response, that means that we'll probably never learn when that bug is fixed.

If you figure out a good way to reliably reproduce it, I could confirm that is indeed the same bug. 
Or maybe find the root cause of it.

Otherwise, there's nothing I can do atm.

Just comment if you have additional information, and I'll reopen the bug report.

**Comment by Balur86** [comment]
I cannot reproduce it either, I keep my eyes on it and come back if I see it again.
