### ISSUE TITLE
newActiveCondition error in 2.7.6

### ISSUE THREAD

**Issue by Kinetyk89** [WeakAuras/WeakAuras2#713]
**Describe the bug**
The aura is supposed to change colour upon being out of range of the target, however it stopped working after updating to 2.7.6 and now just throws a syntax error in chat.

**Do you have an error log of what happened?**
[string "--[[ Error in 'Hex CD' ]] local newActiveConditions = {};..."]:17: unexpected symbol near '['

**To Reproduce**
Standard cooldown tracking aura with an extra trigger to range check. Condition then hooks that trigger and changes colour if the target is a certain range away.
https://pastebin.com/kwYVnDKc

**Screenshots**
Not required

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
I did not.

**Which version of WeakAuras are you using?**
2.7.6

**Was it working in a previous version? If yes, which was the last good one?**
It was. Given my Twitch client auto updates to the latest release client, I'd have to assume it was 2.7.5.

**Additional context**
N/A

**Comment by Kinetyk89** [comment]
Upon further testing, it's only auras that are using a range check condition and it's breaking all other conditions on said auras. Auras that change opacity/colour upon power thresholds etc are working fine.

**Comment by InfusOnWoW** [comment]
Is fixed for the next release.
