### ISSUE TITLE
Add Pet Type to Status > Pet

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#714]
**Is your feature request related to a problem? Please describe.**
Add Pet Type to Status > Pet

**Describe the solution you'd like**
Add a multi-select option (like Talents or class) that lets you add Pet Type (moth, crane, spirit beast, etc.) as a trigger.

**Additional context**
This will help for auras using pet spells to be able to load/show only when that pet type is active.

Example: Tracking if I can use Spirit Shock (dispel) from my Spirit Beast.  The aura right now shows up for any pet, even if the pet does not have that ability.

Multi-select will be useful for abilities or ability types that are shared across types.

* https://wow.gamepedia.com/API_UnitCreatureFamily
* http://www.wow-petopia.com/

**Comment by InfusOnWoW** [comment]
We can't use UnitCreatureFamily because that api always returns localized values. 

We do have a Spell Known trigger, which can check for pet spells. As far as I can tell that works correctly.
