### ISSUE TITLE
Changing color via a condition based on trigger data no longer works

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#716]
**Describe the bug**

Based on trigger data, a condition changed the color and that no longer works

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` d4JPeaGAjK60iTljsEnIK9jbyMseMlPuZgHFtLBkj8neLBlvDEuYofyVWUfA)sG8tevdtkmojOAzOOHIi1GLqy4uvhKuYFLshtsDojQwik1sLi1IjvwoQEOKONQ6Xc65KCzktLOjlIPRCrjuUQeuEgk01jSrjuTvji2SiTDPYhLG0xLi6ZuLVtkMMK0yLa1OjvnEPOtkb0TKOCneX9KqYHf1ALq02qbJAiX7XtWtGeNf5PPkBiOmM1KGZnpQlkz5B4ZAob3WdDeooKiGjkodmqgjLZSAnjmssnJL3OCKwgjmIagrXjR8AMmBWq1gvRzOkdmYePLrczy46nQN(HGQnWN1CcUHxGXz80COPTwjjKhvAxsltkTe8Ss7kSeAwBP1CcUP0UskpKWAFVZn9TSD8eJJpo1ZZ4kirqnK4Jt98moK4cL1670yCWgxOSwrKoWg33PX4JLVHGQ4cL1670y8XY3aBCDI00R3PH8iUsVtd5rTchTZWhlFdxT8ekCFNgJJxJ770y8wNVXZZXXlGIc36S4WjTtJXXfkRnRt546QWLyGnUiADwC4zXCyyiGjK4Jt98moK4JLVHRwEcfUqzTzcnzwQXfgyJlIwNfhEwmhUqzTzDkhxxfUedSXTolo8kDXe6OUOcxj0zDwCKMBP0M4N0fReLaxj0zDwCxKMsBI3wPwx2EPwLwIluwRishyJlI0H7tKzzCmCrCCQNNXHeddpHQkArmC0odphzHNdhTZKCQNNXRWLyiOgdxdnz6rq1g404mEmtuigxrDreqgonbVsxVoNVisQvqfrnUGMG7v4muWfzxjzSHlJtJ01QwMplbb14HUycDuxubjcQHepuVfskiXhN65zCeuJ3L50SocdxP3PbVltime0adpuFo6zkirqnK4(CNVXhl8qhHJJHHHHt4YjqItJECNWhs8EbXOqIHHNttPnnfK49cIrHeddFzcloiX7feJcjggEirwPGexrJEegEPjVqlSIHHZDegK49cIrHeddpHMMsdfeJfK49cIrHeddxOS2qISsb248CObjEVGyuiXWW978xMWIds8EbXOqIHHNMdh1fHeVxqmkKyy4kFlesCfn6ryiGjEVGyuiratWgddxOS2qxVU8aB8LjS4ycjEVGyuiXWWWBsEAQYgckJSgy4kCMLISsrcEhcQRYSgdaa ```

**Comment by InfusOnWoW** [comment]
Is fixed in the next release.
