### ISSUE TITLE
Earthlink aura using Full Scan > Tooltip size sometimes goes blank

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#718]
**Describe the bug**
Earthlink Azerite trait aura made from a template that I changed to use Full Scan > Tooltip size instead of stacks, sometimes goes completely blank.

**Do you have an error log of what happened?**
No errors, but video
* https://plays.tv/video/5b9170171f357b29a1/wa-tooltip-disappear
* https://plays.tv/video/5b916ecf8b4d060198/wa-tooltip-size-problem

**To Reproduce**
1. Fight things/enter combat.
2. Sometimes it breaks, sometimes it doesn't.

**Screenshots**
Two left auras should show "60" but are blank.  Aura on the right shows the stack count "4".
![wowscrnshot_090618_111006](https://user-images.githubusercontent.com/3958649/45176754-d846ea80-b1c5-11e8-9e8b-6bf7228b6376.jpg)

**Which version of WeakAuras are you using?**
2.7.6, been happening for several versions

**Additional context**

Fully edited from template (left in SS) - nth value is set to First
```
dCJfdaGEuq7IsX2eP5kvrZMKBsP03OGDcv7vTBI(PGmmk04eu3MsgQuL60qgUeoiPu9BQ6ys5CuHfsL6zurlgLy5I6Hsv1trESaphk)LkzQOAYu00bxeL0RrrDzcxxOnsPYwLQWMrP2UiCsuOplrtJsvFxensPQ0yLQKrlvgpkYLqbUfPuUgP48KswPuvSms1HL03MpHgx3yQMuDNtyt62yWM0jRjZjZ5tGGjOzNxceIHIXBHNGmQSuKXMpEB(eKrLLI88j2rLclOk39ewHqPy0Cs3Gdh6HN8jLHKkT29KSAjWMpEBI1Ag6uijZdtyrwc8rjS7jz1smXAndDkKK5jScHsXOj28XBJRBWHd9WdtrmHlScHsXO5UNWISe4JsOFFucJ3MyjYMn15tgsoH15tgsQ9aaLqmmmvdaucbpJklfzB9MIX1wZ4WeiycA92JKWK7qCEiBN6eOYoyCngNu(Q58jOQesqF(KvubO5ddtrmHlPiHipltqvjKW8jROcqZhgMmrSzJcIkqR5twrfGMpmmL9kX8jROcqZhgMksuavLqcZNSIkanFyyIDnaqE58jROcqZhgMY1aX8jROcqZhgMqYYSpwmFYkQa08HHHjqWe0SZlHjEsx9lKUSL7YTxzoLfLiVKRvHycf4LtGGjOnXaSEkzqXed9ERXnAJUJjK5eR1m0PqsMNsImHUX1yCkImN6Lgk26RLERpSNqsqKLvvpezmKxoUHjKebUWGAgeMJ3MmryfQQwmg4LJ7i1GgN6tbELppFC73od6PHD2SxJXwydotttNT204CyyQoFI1Ag6uijZJRBmvtQUZHPeJ3SxVn8a
```

Only edited to change stacks to value (center) - nth value is blank
```
dCtccaGlkfBdvA2eDtseFJk62IQ2PsTxy3QSFkj(POYWOs9BLCAvnukjnykPmCf1bPe1LfogjDoQWcjvlLsQwScA5u8qkbpfzzO0ZLmofyQImzumDPUOICvkrEgQW1j0NjLTsPQnRqTDuLpsIYTirAAOI67ujJKevpMGrlkJhvKtQqolLqxJsPZtPYRrvDyQ6VKWqfjqp2SU5AlxwoavGyTXPnCbLhedigKa1MxtlmfsyRIeO28AAHbjqJfLYsWFqhunhs5igqSoD4GDaOLRl3jTd6GoF(OqcBvqtEtNj)JpAqI33tC6RUGoOsCOWs8AOd685dqtEtNj)JpOAoKYrmfsyRInRthoyhGg0qXXJPSLRChOkB5k3zzH(5fGeRqrnhs5igOJgniVq)8IK510cJswmb2kv1nAqYLNbjqIvOqq6Rc6GeRqXf8cdgcsScf1CiaDq1CiGeO6pnzGTkAqcsFvibQ(ttgGuUL2PjRJgnitO9Rlz3Ca6fwhONb0K30zY)4BfRXc6VomNxAFyQFDy7eK4ZaYBb7TyMYS6adFoa9hVWub0b933kQ2B6GbBvqcRLKz56GoAqEKan5nDM8p(yZ6MRTCz5aniEyRYzwv0aa
```

Template with stacks still, size changed to 50x50 (right)
```
dyJYbaGAcvTlIW2urZMQUjbY3iHDsQ9c7gL9tq6NsWWuL(TKgkHkdMqYWjQoiHOBteDmu15iswOeTucklMqy5u5Hek9uKLHkpxPtlAQuAYs10fUOk1vju8mkQRRkUSITsi1MPi2Uk8ys6ZQQPrq13vjJKI0HLYOPW4jaNKa6weOUgr58ePghbXRjr)vcn4Hfucn37PStoZGwqCsOqItqscQdQdlOWL))4wyHMhwqHl))XblO6fRaZlnkb9WY4wa5glkbTYhVxG9fwO5HMtHusXjeeGynjNfwO5bD3CHHpzkrasepMyczuVkWaTg1RcmrQg5XGabOMAKhJ1L))4euTpqly(xeGmM8Beql7fKV26Wc6zNIQ(2UOe0Zofx5JkkbP6B7clOnzF)aYuXOT3cdbOv(OclOnzF)anpceGswmowZl6XTzLbTcqxzpmGw2li38ZkZkT8buQwzGYoO7Mlm8jtPqfLzqpzhK4zItRKtSk6hCGs2X42bLGswgf3O5IPdnpi1A13RxmuIaudwq3nxy4tMsO5EpLDYzgbOdO5fohpcaa
```

**Comment by InfusOnWoW** [comment]
I don't have any item with Earthlink, so I can't check at the moment.

**Comment by emptyrivers** [comment]
I just got an item with earthlink, but try as I might, I can't reproduce this. @amiyuy is this issue still occuring?

**Comment by amiyuy** [comment]
It took a few /reloads and about 10 minutes, but it happened with WeakAuras as my only addon (addon folder empty except WA).

**Comment by InfusOnWoW** [comment]
While developing the new buff tracking system I fixed a few bugs in the tooltip fetching code, though I'm not sure that this was caused by one of them.

I just tried reproducing the bug on my branch and it seems fixed to me for both the old triggers and the new trigger code.
