### ISSUE TITLE
Cannot desaturate with health trigger

### ISSUE THREAD

**Issue by Solstais03** [WeakAuras/WeakAuras2#719]
**Describe the bug**
I expected the weakaura to desaturate when I made the condition to have it desaturate when the health % was above 35, it did not. 

**Do you have an error log of what happened?**
No errors reported. 

**To Reproduce**
1. Create Health triggers for <= 35%, and one with no boxes checked. 
2. Create a condition to have the weakaura desaturate when the mob is >35% hp
3. Click or target frame when its @ 100% hp
4. watch as the weakaura doesnt desaturate

**Screenshots**
https://gyazo.com/1528afdaff4790d7eef6807b055607b5
https://gyazo.com/aad2b0f88abac1af60c1dee1c05fe0ea

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?** 
Yes 

**Which version of WeakAuras are you using?**
2.7.6

**Was it working in a previous version? If yes, which was the last good one?**
Created the weakaura using current version.

**Additional context**

https://wago.io/SkV2_ZyOX

**Comment by InfusOnWoW** [comment]
The aura works correctly, but you probably didn't want to check for your own health in trigger 2.
