### ISSUE TITLE
Creating progress bar from  template is bugged 

### ISSUE THREAD

**Issue by artimdal** [WeakAuras/WeakAuras2#720]
**Describe the bug**
When creating a focus bar (progress bar) from template the addon gave me a progress bar with wrong trigger (aura trigger with no info set) instead of status -> power -> focus as it should have. It also had prechecked "inverse" in the display tab, which makes very little sense for a focus bar. 

I also made a health bar later which had the same issue. Guessing it's the same for all preset progress bars you make, but haven't tested that. 

**Do you have an error log of what happened?**
No error log, as no "error" happened. 
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**
Using 2.7.7

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by InfusOnWoW** [comment]
Fixed for the next release, thanks.
