### ISSUE TITLE
Overlay Cost of Casts does not respect min/max duration settings on progress bar

### ISSUE THREAD

**Issue by Binkenstein** [WeakAuras/WeakAuras2#724]
My shard tracker is a combination of 5 bars with minimum & maximum progress values set for each full shard (ie: 0-1,1-2,etc). When Overlay Cost of Casts is enabled the cost overlay does not respect these minimums and applies to all bars.

Example with cost overlay enabled on bar 1: https://imgur.com/bwVfEse
String for that individual bar: https://pastebin.com/ev3jCrAS

I would expect the cost overlay to be included *before* considering the min/max progress values rather than after.

**Comment by InfusOnWoW** [comment]
What are the steps to reproduce?

**Comment by InfusOnWoW** [comment]
The position of the overlays is fixed in the next release. Do note, that overlays can be shown outside of the range of the aura, so you probably want to enable the new "Clip Overlay" option
