### ISSUE TITLE
Conditions changed after refactor

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#728]
Some of my "on cooldown" conditions got changed to "remaining duration"

example aura https://pastebin.com/s7dmKLgT

**Comment by emptyrivers** [comment]
I can't reproduce this. What was the last point at which you know that it worked?

**Comment by Stanzilla** [comment]
no idea, sadly. I made those auras before merging your PR and it was broken after.

**Comment by InfusOnWoW** [comment]
Could not reproduce it either.
