### ISSUE TITLE
Import old auras with "show on=always" or "show on=missing" converted to "buffed/debuffed"

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#733]
Tested with master

Import https://wago.io/S1tvLLBV7 or https://wago.io/Nkgbld8YW

Agony - Inactive" aura from 1st link have "show on=buffed/debuffed", if you search it on wago editor you see 
```
      "trigger": {
        "use_spellName": true,
        "showOn": "showOnMissing",
        "use_unit": true,
        "use_specific_unit": false,
        "realSpellName": "Conflagrate",
        "spellIds": [
          196406
        ],
```

On 2nd link (ipse's) "Agony" aura also have "show on=buffed/debuffed" 
```
      "trigger": {
        "spellIds": [
          980
        ],
        "debuffType": "HARMFUL",
        "ownOnly": true,
        "showOn": "showActiveOrMissing",
        "names": [
          "Agony"
        ],
        "unit": "target",
        "use_specific_unit": false,
        "unitExists": true
      },

```

problem reported from a user on discord with 2.7.7

**Comment by emptyrivers** [comment]
Those auras are corrupted. They don't have a type field in the trigger, so the modernization code doesn't know what to do with them.

**Comment by emptyrivers** [comment]
Hmm, on further thought, that is actually expected for a buff trigger (which honestly is a bit weird), but the trigger data is not being decompressed it seems.

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
