### ISSUE TITLE
Spell cooldown "Void Eruption" doesn't show "Void Bolt" anymore

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#741]
**Describe the bug**
Trigger "spell cooldown" for Void Eruption (Shadow Priest) doesn't show anymore the cooldown of "Void Bolt" in Void Form

**Do you have an error log of what happened?**
no error

**Which version of WeakAuras are you using?**
commit 66e0107696fec293a089b91308f79acbd3b19b88 (HEAD -> master, upstream/master)

**Was it working in a previous version? If yes, which was the last good one?**
works in 2.7.7

**Comment by InfusOnWoW** [comment]
Should be fixed now.
