### ISSUE TITLE
Profiling calculation error with combat log triggers

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#742]
**Describe the bug**

Count not Zero during calculations
**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` dmeclaqkfG6wujyxQOyysWXOILjs9mPW0uOUMeQTPQOVPanoQKCoQQQ1rvvQdQQ0cvv5HuvMOQcxukAJsuFubqJufvNuvvZuf5Muj1oH8tf0qPQYrPsOLkH8uWuf1vLuzRkG8vvuASka5SkaSwQQsMRcO2l6VkKblP0HHAXsYJfXKvLllSzPYNvHrlronPwnvvXRPsnBv62sv7MWVjA4uLLR0Zjz6uUUI2UuQVtLOXlLCErY6Lu1(LumDyMqpHhHhZeSOLv(Ipueqsrqqz4e3kqxFqKtAcTg21PcJOceugoXTQ8fFOiGKIGqQHDDQWiYX)eWIKsY1pPwye81eLBwebLhEDxK0WMwkiQaHvAylYrlJaAiQjbCIPLcfZeugEnMPrql0gZ0i0PfAvjMPrJqNuyLV4dfHH1Lp9h1KGorkgLiVYLzICiYHO0e5qudICiAmro0iOIBNFsTWi4Rjk3Sicv41N8kxMjYHOcNX)FwyqxnUHtJbtx8y)tuAwE8GF6QIDgmDXPlUG)9FJXSZfkUbrniQWzg0zWphpyHIDLRs3O4genMihAeEHcBZfBbRiO8WR7HDDQWgaevGWvIFmtqlow50Jzc9ZRPzMgnctvmseTJLvem8negZe6NxtZmnAesUyLIzckT44ge877PVF8hrOFEnnZ0Orq5fjmtqPfh3GO0e6NxtZmnAewCsWmH(510mtJgHPkgLCXkf)ryL3Gzc9ZRPzMgncpDxNozETumtOFEnnZ0OrWRTNHVHWyMq)8AAMPrJqhoX0sbZe6NxtZmnAeMQyKYls4pcg(gclnZe6NxtZmnAeu66dMj0pVMMzA0OrW09X6tELlZe5qKdrPjYHOge5q0yICOrq1lLwj)w5Xgkf)ryQIVp)zQS4fpxRfSIWghAPiNYliGNlUcVeugoXTIveSOLn3GGqliyrlRSuyekV66RPwxCIFl2W1uBotOsUVyh21PcJOceWttYFemDFSLLcJq5vxFn16It8BXgUMAZzc4RxjmroeQK7l2)cvye54qWIwMp5vUmtKdroeLMihIAqKdrJjYHgbLhEDpSRtf2aIOcesMkt2NJwwDEpSfeMEpSfeEAL3fNkhTStrNrOMAjyR(4iwfZe5WmbB1hhXYmbLxCV)Fes)zXd2GWBUytlfeCkCMpjCeIy1jqjPlhkiOkjD5qX3et3oimfAJG3fNkwcVOA21Lt5feoV5j)kx3jcwkVGq0oegb1SkAhcdMDD6weg57lKhb15Zxtaimfr7qyemDF8iiW9HIzAeI2HWi4t2xHTAQ9K8GGAwfTdH53gD6wea)AE6ebLxCV)FkMPryQIrkV4Er4(Gvee4(GGpPqfjl20sbHPkgPKZnjQtOn(JWufJMcTXFeMQyKYlU3)p(JGso3KOoH2i4DXPILGYlUxeUpi4tkurYInTuqJWuyR(4iwMPrJO0mtWw9XrSmtWs5feWZftqnRI2HWGzxNUfHr((c5rq(BrzcsxkgkUP4pcr7qyeopWxReb1SkAhcZVn60Tia(180jckV4E))umtJWlQMDD5uEbHZBEYVY1DIWuOncExCQyjiW9HIzICi4tkurYInTuqJq1SRdkjD5qbbvjPlhk(My62bnctHT6JJyzMgncpTYFMIet3oiGVxc4et3oYR(4iwxlFbro0iOfwSc8DGIvPLcICfbSq3JnTuWmbLHxJzcwkVGGqkccV5InTumYs5feurIu8u0i0J1cMjyP8cccPii8Ml20sXilLxqqfjsXtrJqNwOvLyMGLYliiKIGWBUytlfJSuEbbvKifpfnAeQWjUFR07VO8kfgRiyrlJveuMoXDQpMl20sbRim1pc7zB8l5Zp8gW((rWIwgORpiYjnbt3hlRiy6(ylFXhkciPiiuVu2tubckp86(3nepxlFbHVF8bHPk((8NPYIx8CnUfRiO8WR7C0YMBq4VWITdNedSpSY0IJF4DGR7Vl4dRmT44hEDbWdVUjO8WRBFYRCzMihICiknroe1GihIgtKdncv4e3Vv65tELlZe5qKdrPjYHOge5q0yIkCMIPrq5Hx3Nv)Sse5uGGYdVUlsAytlfUw(ccFRlpKqLCFXYkcyrsj5wEX9r5f3heoBGD)DUyL)(K(OKnSlxk8BLwKyYLawKusULxCFKt5feGMNA6lxUOVUUjHk5(I9VO8kfgRiuHtCFSYP45tELlZe5qubIstubIAqubIgtKdnc6ePyKs)ccf9FaEEMqLCFX28Deeqsrqq)i4tkurYInTuK19Xsq5Hx3Nh6JsgrnkqOsUVy)HtC)wPhbKueeEAL3fNkhTSI0hLmc1ulbLHtCR8jVYLzICiYHO0e5qudICiAmro0iy6(ybD9broPjuj3xSGU(Gihckp86(C97fccOMduZIiuj3xS(Kx5YmroevGO0evGOgevGOXe5qJq3I7dWwSHjQycUu)Ssen(tcLc9rjJixrqz4e3QYsHrO8QRVMADXj(TydxtT5mbTODSQGveuE419hHcBZnyfb5QdHHnTuq48Hf93FneL)EIqIu80MwkumtJGorkyfbLhEDZkAeue(iAtOnroJt7qJe ```

**Comment by InfusOnWoW** [comment]
Should be fixed.
