### ISSUE TITLE
More flexible Load Conditions

### ISSUE THREAD

**Issue by haasy** [WeakAuras/WeakAuras2#747]
**Is your feature request related to a problem? Please describe.**

If one wants to create a weakaura, that is active for example in groups OR in fight,
the only way currently possible, is to create the same weakaura twice with different
loading conditions. This feels clunky and cumbersome.

**Describe the solution you'd like**

A interface similar to the trigger interface, where one can select multiple loading conditions
and AND or OR them as they see fit.

**Comment by mrbuds** [comment]
That's a lot of work for something you can do in a few clicks

**Comment by InfusOnWoW** [comment]
That's now what load options are for. If you need complexer combinations like that, do it via triggers, or adjust the auras via conditios.
