### ISSUE TITLE
Unable to track a disabledpotion (cooldown locked during a fight)

### ISSUE THREAD

**Issue by thfontaine** [WeakAuras/WeakAuras2#751]
**Is your feature request related to a problem? Please describe.**
There is no triggers which tracks the state of a disabled potion, while already in a fight

**Describe the solution you'd like**
Adding a trigger to track this state

**Describe alternatives you've considered**
I tried item cooldowns as i thought it was considered in cooldown (but it doesnt seem so), i also tried action usable, but it's only for spells and not item

**Additional context**
![wa](https://user-images.githubusercontent.com/7479860/45500754-a9111a00-b77f-11e8-89f9-930c6da90fc4.PNG)

Thank you for considering this =)

**Comment by InfusOnWoW** [comment]
Please include your aura in the ticket.

**Comment by thfontaine** [comment]
dquafaakPKCkKi3skHDjPQgMc6yiyzQQ6zKcttrCnKK2gsOVHKACifNtvL3jPknpjvX9Kuj7tsL6GKslKGEiPOjkLsxKu1gvaJukrNuvXkLsQzQiDtPuSts8tjLHQQ0svGEk0uj0vLsLTIK4RsQO3kLQUlsG9s9xf1GvLoSqlMapwctwIUmQnJu9zbJwHonOvJe0RrIA2i62K0Ub(nrdxswUkpxPPl66s12rOVRkgpsPZtQSEjvy)sXMGfncTcfh(JgAO24A8F9PU(uBu1yPXslASVSOusMWklWiPmwArJ9LNliJ7AHg7lpVvCHfASGmURfnUqqGKn(v7uTT9JItJBfxyrJleeizROHtNgxvPmh)EYWX7AHgpoaLarDvSXy)IcINXnJfuETaJjtB2p2OEsIT7tZRI8unMqv(gqcsJ6PT64DFI6mwc3kYOUpfsGriG4SkClMzqjjVBLmHsGX8GHaFRfTcblAmpyiWNfnctwvjQYwHaf14))jg7lphyaFWcCu(udyHgdmGpybokFQbmUJYhTKprDRX(YZDamTqJhRgHaiiyKQ)m2xE(y1ieabblWOGoD64O8PgW4okFQb0wKqISXoGjYG0ySNsJ9LNHjRQevzl0itKbPrnLsYs5dO597jdhVBZBR(KSkLmUvmjPsuLTIgeOHMjgposIvmjPsuLnQLidcqqO5ToVyoASV88wXKKkrv2cnM6QyJBgZ(A8y1ieabHzzfFXuEgRN6YyF55OGvEcAJSKTqNg7G8GHaFw0yGb8blWr5tnGXDu(OL8jQBD60k)TOX8GHaFw0yQRIng7x042fWezqID60H0ACwtTO4mkQDqrJmrgKgBjhjZrJDamnwrg1XNXswqNoDrDvSXwQF63bA3uJGOkVw0kemkmMjj38(vMqjO5vsV5fZJbHC0PXTIjj)uUw0keSYFQ)rGQA4042fWezq(9y6qAnIF1pDQXJvRvXxmLNX62OGoD64O8PgW4okFQb0wKqISXJvno0yF5bzvl0PXoipyiWNfD60yjCPWoOiHezJf9nLQgl6BkvfpyiW3uzawyKEhuKqjOv5bdb(OutRBEBEpo7hO5npyiWx7jqbnVrqzZlqMnV5bdb(A)FkOEBAndknglsirw8GHaFTrwYwPfeg60ieK8bIKuHVfkbwHAJjtBAbghzyymTcHHdncbWCEZ4LCPviySdlngc1(r56Gs6hQ5zewAuy)2eccnVcjLYYMxnBRXhyzo6bOEOgu8hvN8BcntgQbHFtm9wmHgJBglO8oGeKg1tB1X7(e1zuEqgKXekbgPI(bf)OP2PZFuOI(br9ons0keM8NGtB

**Comment by InfusOnWoW** [comment]
Potions that are used in combat are considered on cooldown. Their cooldown doesn't tick down while in combat though. I just tested this with Healthstones and it seems to work correctly.

You probably want to add a condition to track whether the potion is on cooldown or not.

**Comment by thfontaine** [comment]
Ok, but i wanted to track the cooldown, and the availability when out of cooldown.
I found a workaround with 2 triggers: NOT ON COOLDOWN || ON COOLDOWN > 0
Thanks for the quick reply =)

**Comment by InfusOnWoW** [comment]
You don't need two triggers for that. Ask on the discord for help with conditions if you want.
