### ISSUE TITLE
Pattern matching: text box can't handle some special characters

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#753]
**Describe the bug**
I want to use a tiny regex with "pattern match" option on bigwigs timer trigger `^[^<]`

When i press enter it raise an error
`[string "--[[ Error in 'aura name']:4: unexpected symbol near ']'"`

This pattern is a valid lua regex pattern:
```
> print(("<hello"):match("^[^<]"))
nil

> print(("world"):match("^[^<]"))
w
```

I tried to escape [ ] with \ with no success

To give a bit more context, i want to show timer for a spell but bigwigs can also show a castbar for same spellid with message "<casting: spellname>", which i want to filter.
So i need my trigger to match a spell id and ignore messages starting with "<"

**Comment by InfusOnWoW** [comment]
Fixed for the next release.
