### ISSUE TITLE
%i height is slightly off for (atleast) text weakauras

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#756]
**Describe the bug**
%i's height is off. basically not on same height as other dynamic info

**To Reproduce**
1. Import wa below
2. take a look at it :D
--> 

**Screenshots**
https://gyazo.com/4a1b811b2eb6a9aa050566c60a3eb6c3

**Which version of WeakAuras are you using?**
2.7.7

``` d8t6caWBfDmk1FrODbv2gr0dbqxtI6wikZguxciDtvP0OauFtcVsvI2jLSxXUHSFv(PKQHbughq1ZicdfqAWinCj5GqjNceomHZbIwiGyPaqlwsz5kSiG4PKwgI8CuEmfnvLAYQQPl1fvLKRcaUmvxxjBer1wbO2mf2ou1NjQzbqMgi9DjYxvLQgRQegnuQXtKoPQuCwvj1Pr15rWkvfRvvQCBO4yNDur2PJYIscxbUIOyI(J(ZoQ06ggmVd5GxqQCbyfGbj42sABxMumidk4rju3WG5DiVOmjiHwUOOakuiLqsiLmgKbfA0HlZNOnHkp6NasGHBkpMRQOU0kb67)aKOCu7dKagW(GXNOyveL5WgaDYrD0DDGgDX)rHzVRg0xx(fGxqik)h1YlDujIcpf)SJUyortybJLAPth1m7yzND0pNvbliSDPDuq5hfuZJcmOvqCprnxSEIz7s7OglKzZNiGH4Eo6rp6r5ghvSgcIocpowlA)Oc0)OI1qq0r4XXAr74qcm(rBSD09C0JE0JE0JE0Jo8Enqh99yreGWcgdGt45WsGXbwMTQbSyneeDeECSw0ooKaJdiqaL9sqa0rbbeiG4Eo6rp6rD0)EC0)EUN75EIoCz(eTju5rBxAh1CX6jMTlTbGQVO9OoEh1r7bxw2hSSJLD2r7bxw2hzhvEmxvMWtKhGeDXCISk3KBWnjUq8o1IYQCy438zzhl7yzlbyPJwBzyOyplvhfLH9SuDewMnhVhfjW4SSJLDufEw6OKlGHthDH4Du5XCvLoDuHzZX77bxw2hVD(9yrMnyPJYrTpqcya7dgFIIvru(pQLx6OKIU4)O9RWcaXArOejoC60rXhlBOKStNa```

**Comment by Stanzilla** [comment]
Set the `Width` dropdown to `Fixed` and `Overflow` to `Elide`

**Comment by InfusOnWoW** [comment]
There's a newline at the end of the text.

Take a close look at the wago import: https://wago.io/rJp7diau7
