### ISSUE TITLE
Please add Slash Command to call Toggle

### ISSUE THREAD

**Issue by KronkIV** [WeakAuras/WeakAuras2#760]
Please add support for the slash command "/weakauras toggle", to call WeakAuras.Toggle().

With some of the non-combat events in BFA, it would be nice to be able to have a macro to easily toggle the display of Weak Auras on and off.

**Comment by emptyrivers** [comment]
If you really want that, then make a macro like this:
```lua
/run Weakauras.Toggle()
```

**Comment by KronkIV** [comment]
Because that causes an error.

Date: 2018-09-16 00:26:20
ID: 1
Error occured in: Global
Count: 1
Message: [string "Weakauras.Toggle();"] line 1:
   attempt to index global 'Weakauras' (a nil value)
Debug:
   [string "Weakauras.Toggle();"]:1: in main chunk
   [C]: RunScript()
   ..\FrameXML\ChatFrame.lua:2158: ?()
   ..\FrameXML\ChatFrame.lua:4734: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4396: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:2884:
      ..\FrameXML\ChatFrame.lua:2877
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:345: handler()
   ..\FrameXML\SecureTemplates.lua:623: SecureActionButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'Weakauras' (a nil value)"

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  Ace3, v
  ACP, vr259 
  GTFO, v4.46.6
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  Stubby, v8.0.6161 (SwimmingSeadragon)
  WeakAuras, v2.7.9
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=e1)

**Comment by InfusOnWoW** [comment]
It's Weak**A**uras.Toggle

**Comment by KronkIV** [comment]
thanks

**Comment by Stanzilla** [comment]
How dare you
