### ISSUE TITLE
Error: Unknown spell when opening Templates

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#762]
**Do you have an error log of what happened?**
> [10:43:55] Error: Unknown spell 18577
> [10:43:55] Error: Unknown spell 21709
> [10:43:58] Error: Unknown spell 18577
> [10:43:58] Error: Unknown spell 21709

**To Reproduce**
1. Open Templates as BM 120 hunter

**Which version of WeakAuras are you using?**
2.7.9

**Comment by emptyrivers** [comment]
That's resolved in #759.

**Comment by InfusOnWoW** [comment]
Fixed for the next release
