### ISSUE TITLE
Missing Azerite Trait Templates - Archive of the Titans and Reorigination Array

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#763]
* https://www.wowhead.com/spell=280709/archive-of-the-titans
* https://www.wowhead.com/spell=280573/reorigination-array

![wowscrnshot_091518_224717](https://user-images.githubusercontent.com/3958649/45593389-719a9d00-b93a-11e8-8d8a-a3f82fd309a2.jpg)

**Comment by InfusOnWoW** [comment]
Should be in. It seems there are just two buffs and not the usual one per attribute.
