### ISSUE TITLE
"Cooldown Progress (Spell)" trigger auras with unselected talent no longer load

### ISSUE THREAD

**Issue by parasemic** [WeakAuras/WeakAuras2#764]
**Describe the bug**

My previously working WAs stopped loading. I have a full set of healer timer WAs and I have "placeholder" auras in their place when the spell is a talent and I have it deselected. I used to simply create them with "Cooldown Progress (Spell)" trigger and load parameter checked for the other 2 talents of said row.

These "placeholder" WAs stopped loading altogether and I had to bandaid fix by finding a dummy trigger.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

1. Create new icon WA
2. Choose trigger "Cooldown Progress (Spell)" and select an untalented spell
3. The aura won't load

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

Newest. (2.7.10)

**Was it working in a previous version? If yes, which was the last good one?**

It was working yesterday but installing previous version didn't fix it.

**Additional context**

``` HERE ```

**Comment by InfusOnWoW** [comment]
Please add a aura that shows the problem

**Comment by parasemic** [comment]
diuejaqjjcnkQIKtrvK6wsuzxsuAysfDmbwgQ4zuLAAsLUMuvzBsvvFtIKXPssNtIiRJQOQ7jru7JQOYbPQyHuv9qvHjkrvxKkAJQeJKQiojvjZuQWnvjXof6NufgQuLJkrWsPQ0tvMQOUQuv2kvrXxPkknxjk2l8xvPbRQQdtyXuHhlIjJQUmLnRs9zrA0QkNMuVwIuZwk3wc7gLFt0WPslxspNKPJCDvSDvrFxqnEuPZliRxLu7xvLraYyAe72FoEZ5QykmoLTuLTKWkW4X4rglTjddhyKXLcUiz00xBigWblrkB8YWSSXLCYeoAgp8JfYJ7BLriwUUDIjyjFYApPMrypCgZo9fl5Oizr24s95Ylid74YlidtKqAjtHmMIevczmE5BAtggoWsBYWVIeslzyQpzymE5RsEy8WbMsEy8yEXiRElsSY4dpVhmvz6vfu58USDwMjpmEvz8etuPYkttX4LVfMsjsn4alTjd)ExffgMN1eL2NtvO88(QDjnVvU(697phqy3AMw9Hmimnttidcegv1PPwvHmIbiJrvDAQvrgttwruuyi2j2rzVPgZQ6K9jd7bd(XsnMv1j7tg2dgM6tg2Nwyrif2rzVhMMGFmLR1ArrHHyP8U)xTFyjhfjlE)08ggPlmESKprn1uVsxRkizfZZHL8jQPMcRtmMOWuiJyawVQiKv)9xE)7)vmgVMLcctDCypngTZ9TMl27dFw(DzF8nJDu2R6tg2dg8JDu2RMSIOOWGFm7PXiShszJxgM97FVQmTAk1V)EQ5ATMNgJc5Ayksqhfw1eT5ATwuuyy9XAMq997Fh6Bd7OSxLR1ArrHb)ykxR18IxHmiSdttyUnriRIDy2tJryIdjXok7n5tutnfCGPooSNgJ6vTBnxS1ZzhDGXBoo335qUgMN4SJEx6Rdqyhgv1PPwfzm1NmShmm1NmSpTWIqkSJYEvUwRfffg8JPCTwlkkmelL39)Q9deimrcPFA5Qon1QxrYBigacJmUeNlsgHDPQV(3)s4i4Rcs87FoJvAZC9r5AjKVcslHdmL1U7j1mc7HZy2PVy8MsqNQGm4aZTktRMs1RAjALwYqSlgzCPGEsnJWE4mMD6lgzCjoxKm6stKQW8OVChEfDI9z60pcXUDXAsbpYyKOzmIdYyfNgPrgeiSJYEz2tRchyKOzmczSItJ0iJya8Jih4heimLRLGmMsZsBgIEJvCAKgzedGFe5a)i6n8dcewstOuiJP0S0MHnpXNR4teR40inYy981lNld)GaHPzPv5XfzSItJ0idce2rzVKOzmcoWok7nPjuk4hRkBgYyfNgPrgeiSQiXqgR40inYGaHDlsiTKHmwXPrAKbbc7OSxLRLa)yUpDjrZyeYyfNgPrgeimE99To50OqiJvCAKgzqGWu6RnKXkonsJmiqGWiJlX5HKrcnRWyeMxX5v5DIX1J7BLriwUUDXiJlf8q2KvKrmaXae5GyaIEJyaIDrmaegzCPGhsgj0ScJryEfNxL3jgzCPaNmHJMXdhyKXL48q2KvKrmaXae5GyaIEJyaIDrmaew1s1swoKRHPtKmmDIKb)yKXL40tQze2dNXStFXiJlX5IKrtFTHiNUyKXLcUize2LQ(6F)lHJGVkiXV)5mgzCPGlsgDPjsvyE0xUdVIoXiJlfGvIUycwYNSEPkkSCixdBp81PZi2DvuyJQcsGyagzCjoyLOlM4qs4hlr2KvKrmaXae5GyNi6nIDIyxedaHP5X6J1mH6Rd9T97Vh33yIM7NaXamY4sCCYeoAgpCGfwZtFi2Tl21szbIDID08yC7xp(Y3kLi9scMM90QkdoWuKoP0Hk)PkiTKbhyjsgVM0sMczedqgl5ZsknYyuvNMAvedWEkQAHJMHjzpKYgVmmdt6IvYLm2tr7yigacl5tWsnfYigGm2tr7yWpMBv6AvkegVPe0PkideICqgeiqGWemDHG0sgYyksujKXOqUggtYmm3QPmc7wWBy8NQG0s2lfY1WuwIKXRaHvi0mKXCRMYimLRMHrHCnmMKzy8NQG0s2lfY1WuwIKXRaHDRzA1hYyuixdJjzgMB1ugHDl4nm(tvqAj7Lc5AyklrY4vGaHPzKvzIMNXQkTKHyjbc7jIbD5eacaa

**Comment by parasemic** [comment]
This is what showed the problem initially, but it does replicate with every spell with this type of WA.

**Comment by InfusOnWoW** [comment]
That was a intentional change.

**Comment by parasemic** [comment]
Is there an easy way to create something similar, then?

**Comment by InfusOnWoW** [comment]
Add a Always active trigger.
