### ISSUE TITLE
Windwalker Auras causing FPS drops

### ISSUE THREAD

**Issue by Babylonius** [WeakAuras/WeakAuras2#765]
**Describe the bug**
The LastHit WeakAura, a near required WA for Windwalker Monks is causing an enormous CPU load and eating up a TON of resources during periods of fights, causing immense FPS drops even on higher end computers. It seems to also happen using our Touch of Karma WA. Both of these addons use "COMBAT_LOG_EVENT_UNFILTERED" as their triggers.

**Do you have an error log of what happened?**
https://cdn.discordapp.com/attachments/434767646978998282/490003475086835722/lastcombo_WA.png

https://cdn.discordapp.com/attachments/434767646978998282/490004991105564672/addon_CPU_usage.png

**To Reproduce**
1. Download the Last Hit WeakAura
2. Try to raid
3. Lost FPS mainly during AOE situations.

**Screenshots**
https://cdn.discordapp.com/attachments/434767646978998282/490003475086835722/lastcombo_WA.png
https://cdn.discordapp.com/attachments/434767646978998282/490004991105564672/addon_CPU_usage.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.7.8

**Was it working in a previous version? If yes, which was the last good one?**
Prior to Uldir there wasn't any noticable drop in FPS, but it may have been due to not enough combatlog load. It did work in Antorus, even after the Prepatch.

**Additional context**

di1JyaGieYLGuPmkuHtbv1QivOEfPczwOs3cG2Lsv(fuLAykrhtPSmOKNHannbLRbi2gPk9niLgNeLoNevToivqVdsf19qvoOsvTqurpKuvteH6IaQncH(icyKKk6KqPwPs6Lsu0mbWnbKSti6NkHgQsWrHurwkKINcAQKYvfuTvivYxbKASKk4Ssu4TqvmxsLUlKQ2lXFHKbR6WKSyLkpgrtwcxw0Mrv9zOYOfKtl0QHuH61KQy2s62qXUr53kA4cCCivQwUcphPPl11bA7qW3LOY4rqNxISEOk59qQa3hsfY(Pw2enbIrGfcSq0eiU6SCYob2jH9gItwdJ4vki3wkWslYNpnBb52sbQyKHMJfMrwlq9bgPgWOrGKG0EIrljSdpOq1PateswlqWrvGH6oGIoeVX7YPWn3loX7XQMERO7yTWo8MGcmsozcNcShrC4Ybv0eKBIMa7rehUCiAcSaCO64KjWLcexYYrKegAwUfzcKgAwUfz7t2resbYuysQOjTajbP9ed2KtMa5dYi74KXb(E1333pY3xbouOsgc7vv0wNX2Nhp)TLBajmG43HsMVx99999999hzdoy(6DPEbsyaXR((((zLME13333333FKn4G5tGSHbzTQLe2GJKdf4qHkziSxvrBDgB89QVVVFYk8AYkeijiTNyqfkwKcKeK2tmcSlfKcKeK2tmcKeK2tmO6sbPateswlqk4UeHK1lms(rcfiCbGbaabwK7a5ZxRuqkqDcmalGy4aiWeHK1cu)jMDQ2hGjobsdYAf7cQOjTajbP9edXGdvhNmbYhKr2XjJd89QVVVp)5WpYBJByl9lM(E13333333pY3pCwS5eKpFoikOQkLdI46hXNhpcKnmiRvSz8NCSvE9I2WwIVFhkzE133333333333Vojvv)cWHQJtgx)KWG4q1XjtlIj955tZAs2CaeU(HZInNG85ZbrbvvPCqex)i(47vFFFFFFFFFFF)r2GdMFb4q1XjJRFsyqCO64KPfXKE13333333pzfE1333pzfEnzfcKeK2tmivysbYhKr2XjJd89QVVVFDsQQ(mfMKRpkU(O46JIRpkU(O46JYNNpbYggK1k2m(touGdfQKHWEvfT1zSX3R((((JSbhmFMct61KviqsqApXiq(GmYoozCKiKSMRpkU(yskvHl56JIRpDcoitceo2eZ1hfxFuC9rX1ViPnbchBI56JIRpkU(O46tdYAfBI56tdYAfPctY1hfxF(Qynl0kfK47vFFFFf4qHkziSxvrBDgBFE(kWHcvYqyVQI26m2(ZH)sV67777vFFF)6Kuv9PbzTcqK2(88rhGoYR((((0GSwbisB8STCjAl7s07ZZVhGPVpGa6RfXLd)fuvmE1333NgK1karAJNTLlrBzdd9(887by67diG(CwvK6zc2(LzKupE1333NgK1karAJNTLOnmSkl69553dW03hqa9rtKgz48HGm)YmsQhV6777tdYAfGiTXZ2YnGegqqVpp)EaM((acOpI1srgoFyocsw7xMrs94vFFFFAqwRaePnE22iOEbIErVpp)EaM((acOpIrAt9N89reCuYR((((0GSwbisB8STCdiHPx07ZZVhGPVpGa6ddImwKHZx)HIL(LzKupE1333NgK1karAJNTn9w2Wql69553dW03hqa9rdinuKHZFvvK(aDKv4vFFFFAqwRaePnE2acwBOfiO3NNFpatFFab0hOdfh1idNpXdfUjZFbqgziV6777tdYAfGiTXZ2gqww(YIEFE(9am99beqF9df9bAfcPx9999PbzTcqK24zdlcw(YQx07ZZVhGPVpGa6RFOOpNGdA7vFFFFAqwRaePnE22qB5bcwO3NNFpatFFab0x)HIup1idN)QQi9biIluZImCE1333NgK1karAJNTnGSSSlrVpp)EaM((acOV2eKmK)KVpXPQd5vFFFFAqwRaePnEWsVBLpm0IEFE(9am99beqFeJ02FY3VdL(aDOyN(ArC5WR((((E1333pY3prizTppE(eP)IafN7RHcGfjakGrxaJudv4ireBa0agnatmr(kwHpMKsv4sFE88jcUaWaaak93hQHcgU(6dmesKVIv4tNGdYKaHJnX(845hol2eiCSjMdIcQQs5Gi89vScFAqwRaePnEObzTInXO3VdLmV67777777h57tdYAfBI95XZxbouOsgc7vv0wNX2VdLmV677777777777h57ZMnhkWHcvYqyVQI26m2(845VTCdiHbe897qjZR((((((((((((((((luvLGtqwbIXAYbryZ6CWxrM6Q7(fflYO6QlqNk9Sp4qr1vxGklIkD1fobzfuD1LtftXulKzfwJb7nXHJiUebruhicF0zV677777777777NScV677777777777toXSBIyvrd5ZZFZR((((((((zLME133333333333xbouOsgc7vv0wNX2NNpniRvSj2R((((((((((((Ktm7Miwv0q(88x6vFFFFFFF)Kv4vFFFFFFFFab0Fb1yucVjEwGl93LzGx9999ZknJ89tesw7ZJNpr6ViqX5(AOayrcGcy0fWi1qfoseXganGrdWetKVIv4JjPufU0NhpFIGlamaaGcOWgcbMyI8vScF6eCqMeiCSj2Nhp)WzXMaHJnXCquqvvkheHVVIv4tdYAfGiTXdniRvSjg9(kwHph8vXAwOvki95XZNOf2hnOPmiYFo85RI1SqRuq6ZJNpreViXeayIW3VdLmFFFV67777777VqvvcobzfigRjheHnRZbFfzQRU7xuSiJQRUaDQ0Z(GdfvxDbQSiQ0vx4eKvq1vxGw15G4XmyVjoCeXLiiI6ar4Jo7vFFFFFFFFYjMDteRkAiFE(y5vFFFFFFFFab0Fb1yuYhV9jEwGl95mZaFFFFFFFFV6777NScV67777vFFF)r2GdMFpatVMScbcYseswlWoIjleyIqYAQa1FrGIZ91qbWIeafWOlGrQHkCKiInaAaJgGjwGuWDjcjRHG85hjuGO0FFOgkO2(OrtGG0efMKsv4sTsbPStGGSylWGQQuoKwGGSEeXHlhIMajbP9eJa9Qx9Qx9Qx9Q0sliXs0eypI4WLdrtGDPGuG0w1GubcstuQA5uLO9amfofijiTNyq1LcsbsBvNGbfQofiUKLJijm0SClYein0SClY2NSJiKceKfBbguvLYHazkmjv0KwGuWDjcjRxyK8Jekq4cadaacKgK1k2furtAbcstuGSylCkWeHK1cu)jRi2XjJkqk4UeHK1qq(8Jekqu6VpudfuBF0OjqqwIqYAbQa7PalYDG85RvkifOobgGfqmCaKwGGSEeXHlhIM0slWIifDmiJSJiKcuXkjqfzhri1grC4Ybqnlsb5M0cStc7nGzQD1Sq4uG6jZG9PbjzJgvhNYobQyrmQoozIMaPTA0IMaPKQAQvkifijiTNyeyxkifiBYsbcstuusvnLDcSaCO64KHQlfKcKMKtwbvGbJKMTaPbXHQkqkPQMicYifO0ceJkYenbsoRZbAeKl3R8LxVlrBzdJGBeeTybeGiqkPQMekixU3Mav1GqkTsbPaP9qfXfQfi5Soh7li3ei5SoheqqUjqvniKcrqgPa5dYi74KXrWyIBKukxFARgnx)IS2k89QVVVVV)iBWbZN2Qr7RJ85iymXnsk1xh7xK1wHVx9999twHx99fiinrPQbHuYobwaouDCYq1LcsbstYjRGkWUuqkqsqApXiWcWHQJtMa3eiinrrjv1u2jqqAIICwNdHtbsjv1SKGC5EBcuvdcPeKlfiHcYLcSKGCPajN15qRuqkqsqApXiqkPQMicYifiFqgzhNmocgtCJKs56tB1O1bU(0wn6YGRpLuvtDGRpLuvZYaFV677777pYgCW8PTA06GVoYNJGXe3iPuFDSphusvn1bFa9PTA06a(4Z1N2Qrxg(6iFocgtCJKs91X(Cqjv1Sm8b0N2Qrxg4JVx9999twHx99fyWiPzlqAqKjqYzDoqeKrkq(GmYoozCemM4gjLY1FSX1h3gx)DBC9vBC9hyX1hhwC93HfxFfw47vFFF)iFFYjMDteRkAiFE88387qjZR((((((((JSbhm)nU(l56VKR)MVpGa6ZbAYc89rtgKQ2x1TIupE1333pR0mY3NCIz3eXQIgYNhpFS87qjZR((((((((JSbhm)LC9xY1FJR)MVpGa6ZbNvWeFF)fuJrj8M4zbU0R((((((((E1333pR00R((((((((JSbhm)nU(BC9346V57diG(CGCoWOQ47vFFF)Kv41KviWXSvDkixkqYzDo4uqUCVYhw5xUvE9UeTLnmcUfMaPKQAQvkifiThQiUqnKuvtPfi)ilsdjAcKsQQPwPGuGKG0EIrGG0efLuvtHtbwaouDCYq1LcsbstYjRGkWUuqkq2KLcmyK0Sf4UjiJmjojvLKwAbs7iPEkrm4q1Xjt2jWojS3wygzTa5CrnTfbkb2jHnwioznIvfoQaxmCnaWgjWcmugXfQfKODPaRtvHOjqqAIki7DQURPStGG0eflrihYobswvuQOjqAKHRMceOwezzkqmG1okAslTabPjkYQIsfof4ywtrtGyaRDu0KwAbcstu0GKu4uG0iELIMaXaw7OOjT0cSv1K1yjAcedyTJIM0slWwvtwlAcedyTJIM0slqqAIcHmuKSMYobsdssrtG0idxnfKeuGyaRDu0KwAbcstumfMu2jq(kYoozIMaXaw7OOjT0ceKMOqidfjRz4rzNaJmCJjyGOjqmG1okAslTahkYu0eigWAhfnPLwGfr(8JKG1UKOjqmG1okAslTadqiOv1K1IMaXaw7OOjT0slWojSXAHzK1cuFGrQbmAeyK15GPQORCqJtMGS8cStcBS0FYAvKHjzTaXgjeBIbwGKtwrSJtgv0KwGDsyVP)SohIMGCtqUjiXsqUjijOGCtqgMGCP0cStcBSqCYAbI4iIx(OtGQIHQv(AAcSiPQgCO6u2jWojSXs)zDoenb5MGCtqILGCtqsqb5MGmmb5M0cCK4ItMwPGuGrYjtGDsyVH4K1iwv4OcCXW1aaBKalqYzDoenb5MGCtqILGCtqsqb5MGmmb5M0cStcBSqCYAyeVsbjwHjqfJm0CG4qHj1kfKceQpAagyKcuvdcPeKBcStc7nbIUfiWojSXcyMAxnlKDceVMtmcYLcStcBSei6wGavG9u4uGDsyVH4K1ceXreV8rNavfdvR810eySqGanq7dGI2HITV(tm7M(CosLEYHajCr(8Pzlixkq(dfMe2dvReKBcSCXIoKGeTlfi5CwlMLJPLe2aZu7QzHWPabJfceVA83X5(HdIFyHjWidHCqtzNavKDCYOIMaPTA0IMaPtqwHaXM15GVIm1D)IIfzuDbUIq4yRlMSiQ0LobzfuDlNAWImC7nXHtGftuKG0EIr2jWIjk6eKvi7KwG8JSinKOjTaJSylAcKeK2tmcubouOsgc7vv0wNX2NNVcCOqLme2RQOToJT)C4Vrq0sWYgMxjNy2nrSQOH855V0RE1RE1REvGftuKG0EIr4uAPfinR8xygzTa1hyKAaJgbwePbvvjSjNmbjqqlwljibfi5CwlMLJjCkWojS30FYAvKHjzTaxmCni2edS0cKkqS2dT7vwbIGGClmS2Kwe

**Comment by emptyrivers** [comment]
Well, that aura is committing some serious performance crimes, and I'm frankly shocked that you only just noticed the problem. You should get somebody on our discord to optimize it for you.

**Comment by emptyrivers** [comment]
Well, actually, I did find my old optimization of that aura from last year when I mentioned how bad that aura is. Give [this](https://wago.io/VJrQ4itcf) a spin (haven't tested it to see if it's still accurate.
