### ISSUE TITLE
Improve the sorting order of SortDisplayButtons

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#767]
**Describe the bug**
Auras with lowercase first letters sort below uppercase first letters in the loaded/not loaded list.

**To Reproduce**
1. Rename an aura and change the first letter to lower/uppercase.
2. See where it shifts in your list.

**Screenshots**
![2018-09-17_09-16-34](https://user-images.githubusercontent.com/3958649/45635748-aaca2e80-ba5a-11e8-8391-d859b8f938d5.gif)

**Which version of WeakAuras are you using?**
2.7.10

**Comment by emptyrivers** [comment]
This is how all strings sort.

**Comment by InfusOnWoW** [comment]
Only computers sort like that, humans don't.

**Comment by mrbuds** [comment]
it's easy to implement, but i don't know about the edge cases
```diff --git a/WeakAurasOptions/WeakAurasOptions.lua b/WeakAurasOptions/WeakAurasOptions.lua
index cac113f..0bf7561 100644
--- a/WeakAurasOptions/WeakAurasOptions.lua
+++ b/WeakAurasOptions/WeakAurasOptions.lua
@@ -3942,7 +3942,7 @@ function WeakAuras.SortDisplayButtons(filter, overrideReset, id)
       end
     end
   end
-  table.sort(to_sort, function(a, b) return a:GetTitle() < b:GetTitle() end);
+  table.sort(to_sort, function(a, b) return a:GetTitle():lower() < b:GetTitle():lower() end);
   for _, child in ipairs(to_sort) do
     tinsert(frame.buttonsScroll.children, child);
     local controlledChildren = children[child:GetTitle()];
@@ -3998,7 +3998,7 @@ function WeakAuras.SortDisplayButtons(filter, overrideReset, id)
       child.frame:Hide();
     end
   end
-  table.sort(to_sort, function(a, b) return a:GetTitle() < b:GetTitle() end);
+  table.sort(to_sort, function(a, b) return a:GetTitle():lower() < b:GetTitle():lower() end);
   for _, child in ipairs(to_sort) do
     tinsert(frame.buttonsScroll.children, child);
     local controlledChildren = children[child:GetTitle()];
```

**Comment by emptyrivers** [comment]
This will of course only work for English locales. In Spanish, ñ should come before o, but ascii sort won’t care.

**Comment by emptyrivers** [comment]
In any case, this isn’t a bug, so I’ve change the title of the ticket to more clearly reflect what is being requested.

**Comment by mrbuds** [comment]
i found this https://www.curseforge.com/wow/addons/utf8 which implement a function string.utf8lower(s)

**Comment by InfusOnWoW** [comment]
We don't need a toLower, we need a local aware case insensitive compare. Every std c++ library provides that. I doubt that we have access to it though.

**Comment by InfusOnWoW** [comment]
I checked various places in WoW, and there's one place where the sorting is correct and local aware. 

It's not the guild pane, not the toy box, not the pet journal. 

But the mount journal is. That's done on the backend. I'll ask our new contact at Blizzard, whether we can have access to that function and to sort the other panes, but no idea whether they are open to that.

**Comment by InfusOnWoW** [comment]
I did write a message to our the new contact for addon developers at Blizzard. I doubt we'll get that api, so I'll close it for now, unless he responds positively.

**Comment by emptyrivers** [comment]
I did some reading over Thanksgiving, and came across this: https://www.lua.org/pil/3.2.html

Which seems to suggest that lua supports locale-aware sorting natively. Of course, Blizzard's flavor of lua is not just classic lua (see: taint, equality comparisons with NaN, etc), but I would not be surprised if WoW-flavored Lua is still locale-aware in its string comparison. If that is the case, then the UTF-8 library should indeed be sufficient to implement this request.

@InfusOnWoW, did your blizzard contact ever get back with you?

**Comment by emptyrivers** [comment]
Of course, the various UI panels not being correctly sorted doesn't speak well, but we can always hope 😃

**Comment by InfusOnWoW** [comment]
No they didn't, and the standard <> are not locale aware in wow.

**Comment by emptyrivers** [comment]
That's a shame. Oh well.
