### ISSUE TITLE
Control Undead / Pet trigger interaction

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#768]
**Describe the bug**

This aura should show up as soon as a Death Knight casts Control Undead on a target and it gets controlled. It only does so if you had the options opened before once. UNIT_PET fires normally, I checked that.

Edit: Adding a remaining time check to the trigger makes it work.
**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

https://pastebin.com/tHgDLivK

**Comment by InfusOnWoW** [comment]
Should work now.
