### ISSUE TITLE
Wow client crashes when attempting to export a large WA. 

### ISSUE THREAD

**Issue by enshadowed** [WeakAuras/WeakAuras2#770]
info;
SlootUICDHUD:Resto is the name of the aura, found in the saved variables. Attempting to export it to string, the client crashes a sec after showing the string. 

**What steps will reproduce the problem?**

if i share you the aura in game and you try to export it.
**What is the expected output? What do you see instead?**

i expect to get the export string without the client crashing
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

yes
**Which version of WeakAuras are you using?**

2.7.9
**Was it working in a previous version? If yes, which was the last good one?**

Can't confirm. This aura was made within the client and attempted to export it when i was done
**Do you have an error log of what happened?** 
 
no bug was shown.

**Please provide any additional information below:**

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**

[SavedVariables.zip](https://github.com/WeakAuras/WeakAuras2/files/2393733/SavedVariables.zip)

``` HERE ```

**Comment by InfusOnWoW** [comment]
There's not much we can do about that. There's a size limit to the size of string wow can put into those text edits. My advice is to not create auras that are that big.

**Comment by emptyrivers** [comment]
This is a known issue, but unfortunately there isn’t all that much that we can do to mitigate it. At some point, your groups are just too large for blizzard’s editbox frame to reliably handle, and you’ll notice extremely long hangs, or crashes to desktop when you try.
