### ISSUE TITLE
aura_env not reset when opening config

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#772]
**Describe the bug**
aura_env table is expected to be cleared when opening config. 
Does still happen if you open config then adjust the Init.

Quick example https://wago.io/SJo1ps1Km

...this is more speculative, I've not done testing to know for sure, but TSU stuff doesn't seem to update and fire conditions between opening config and closing again. I'll try to work up a simple example of this but it feels connected and maybe makes sense in this context?

**Comment by InfusOnWoW** [comment]
The second issue seems to be this one: https://github.com/WeakAuras/WeakAuras2/issues/774

Which I just fixed.

**Comment by asakawa-k** [comment]
I made the ticket after discussions on the Discord so not directly an issue I was experiencing, but something I guess I had assumed incorrectly, if nothing has changed in that area recently. 
If it's working as intended then this can be closed. Thanks for looking into it.

**Comment by InfusOnWoW** [comment]
What was the discussion about?
