### ISSUE TITLE
Wildfire Infusion (Hunter - Survival) and Spell Known trigger

### ISSUE THREAD

**Issue by Kha-Khan** [WeakAuras/WeakAuras2#773]
**Describe the bug**
Expected to have the texture change color when a particular Wildfire Bomb (Shrapnel, pheromone, Volatile) will be the next castable bomb

**Do you have an error log of what happened?**
No lua errors

**To Reproduce**
Will need a survival hunter level 100
Import my aura (https://wago.io/Byz5xggK7)
the white box should change colors (using conditions) when that particular spell is known

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Which version of WeakAuras are you using?**
2.7.10

**Was it working in a previous version? If yes, which was the last good one?**
I am unsure, I only recently created this

**Additional context**
Another note, if you make an aura with "Cooldown Progress - Wildfire Bomb - Show - Always" and you have the Wildfire Infusion talent currently active, the trigger will only return true on one of the 3 bombs.  Thus hiding your icon/bar 2/3 of the time.
This can be avoided by speccing a different talent, then making your wildfire bomb trigger. 

da0VkaakPIOtjKsTlsinmjvhtvSmjLNPszAsfUMurTnjO(MqQoNeK1jKsoOQKfkepuczIsOsxuLQnkHYijH4KQi8sventsWnvr1of5NQinuvPwQkkpvzQu1vfsXwLksFLeQ1kHQAUsa7f(RkmysuhMOflv9yPyYsYLr2Su6Zs0OvvonPwTeQYRLanBQCBHA3O63IA4K0XLqflhLNty6uUUGTRs(UuPXlKCEvvRxQiSFsKXd8yAKQvVWDUW3kmMaRMIgDf9Powmwfwf8yrDABRGmKQJfRzSmd9y)N22kidP6ysEZxM9oR5gwr3t(7NHXYM00zos1X6DeV68CfHfrH7PIlMK38LzfJjJPIXKXeMIjzbFfysr0sXAxvRMrkP8j4TbHoZvs5isgwtMxPnDMlGhPh4XA(OMccpMX0LLedPAyxsMw27imXxUl2L0fiKEGH18j5LKaEKEGh7s6ce8i9GuDKQHuDKUH0dsDG0dmmvwwLy2pwt2LzWGbdPAWJ18rnfeEmJPlljgs3WUKmTS3ryIVCxSlPlqi9adR5tYljb8i9ap2L0fi4r6bPhKQHuDKUHuDK6aPhyyQSSkXSFSMSlZGbdgs3GhR5JAki8ygtxwsmK6a7sY0YEhHj(YDXUKUaH0dmSMpjVKeWJ0d8yxsxGGhPhKQJunKEq6gs1rQdKEGHPYYQeZ(XAYUmdgmyWWAYUmdEKEq6bPAi9G0nKEqQdKQROrVZWWKnMoZfWJjmjZGhgMMRn4HH1Q5AXh8WGHzuuwGryNGBeRv2qf4vv1PCrbumjl4RatkkW5uLwwapfLfyKOaR4eKm6qXFAJoIKzvedRIeslWKgHEmn3igx66uIj0zosfctY1XstN5WJjmjZGhZ(vjmEMtyvbM00z(H9RsycQjZReWWILAo8y2VkHXZCcRkWKMoZpSFvctqnzELagwRMRfFWJz)QegpZjSQatA6m)W(vjmb1K5vcyWWeKR9DwZnSIUN83pdtxHPyTRQvZiLuUOSlZeysEZxMvmMmM8)Qe2k6S73tysN6NePhSU6k7dPBfgRslAyKrhSSjnDMJuDSGUcZ)xvLS7f1w8pjwltgtZystI0dMX0LLetapspWJzmDzjXGhRI6dTT(FvctrURW7IfnkGz)QeMWKwqGfe0rGRneblWPlIByYGLXcc6q2lYS(ZZveIGfe0rjXjMUzF5UNYreSsItmDZ(YDpLJj(YDF56k)fyCzmjGhggJKUPsoxsgtykw7QA1msjLJKJ7Xcc6qOsoxsgticMqLCUtujGhgMi0txe3wOTvhf2rrVM)y(xN5XeHE6I42Bg1QJcBVVRGcy0fXnSIYzxvUlxjLFZYLmsius5o5ujNlAJf4Adt1j)jgMqLCUKmMqQwNluhfQZWWcCJPlljg8yLeNy6M9L7Ekht8L7(Y1v(lGbdPAWJzmDzjXGhZ(vjmHjTGatOsoxsgtivl61VDRqyboDrCdtgSmwFOTDF5UNYXeF5UNYF1y6lcliOdzViZ6ppxricgDrCdBQKZPKYNKN7YXcCTHP6K)edJrs3ujNljJjS9XKQCYPKYrYX9ybbDiujNljJjebtOso3jQeWddJlJjb8WWeHE6I42Bg1QJcBVVRGcyIqpDrCBH2wDuyhf9A(J5FDMhliOJaxBicwf1hAB9)QeMICxH3flAuagwGBmDzjXGhgmKUbpMX0LLedEm7xLWeM0ccmrONUiUTqBRokSJIEn)X8VoZJfe0HSxKz9NNRiebJUiUHnvY5us5tYZD5ybU2WuDYFIHXiPBQKZLKXe27pILJZCsjLJKJ7Xcc6qOsoxsgticwGtxe3WKblJfe0rGRnebte6PlIBVzuRokS9(UckGjujNljJjKQf963UvdgwGBmDzjXGhgmK6aEmJPlljg8y2VkHjmPfeyIqpDrCBH2wDuyhf9A(J5FDMhliOdzViZ6ppxricgDrCdBQKZPKYNKN7YXcCTHP6K)edJrs3ujNljJjSon7KM2rkPCKCCpwqqhcvY5sYycrWcC6I4gMmyzSGGocCTHiyIqpDrC7nJA1rHT33vqbmHk5CjzmHuTO)uVJcbdlWnMUSKyWddgwLwu8c8gtFrys(pMSX0xKNPllj255kcPhyyFKU8Zq6wHXyztAeIG5YYk4Xcc6GlJj0JzshXTAWJfhCMgEyWWcc6Gtxed9yM0rCdEmHMx6iKQvhlo4mn8ivRoIadggt2qWJfhCMgEyWWACsHaEmHMx6imfjAs(7NHfhCMgEyWWuVunPJ4g8yXbNPHhgmSwzJPZC4XIdotdpmyybbD04KcbIGXYocES4GZ0Wddgwqqhms6IrpwqqhcvQbrWQ0TT6MGZ(Hhlo4mn8WGHP5LSCqfES4GZ0WddgMqLAGhtO5LocPByXbNPHhgmmHUtqWJfhCMgEyWGHXOsDM7)vjmJIYcmcg2fspDu7bgaa

**Comment by InfusOnWoW** [comment]
That's not possible to check via IsSpellKnown, the wow api seems to never return true for that spell.

So you need a custom trigger for that, e.g.

dOuNmaGiiLrHQiNcvrnluf2fvHggK4yiQLPcEgcmnOixtLKTbfY3ujY5uHY6Guv6DqbDpf4GkOwiK0dHuzIqbUicAJuf8rivHrcfQtQsuRKsVesv1mPk6MQeANq8tvsnufKLIQkpLyQQYvrvP2kQk6RQqSwivrVfvfMRkb3fvLSxXFPknyLomklwf9yQQjRqxM0MHQ(muA0iYPLQvdPQ41OQQztXTvP2Tu(TIgoQCCivPwovEostxY1vvBhH(oQsJhkQZdvwpKQK3Rcv3xfs7hCiNxKEqoGcgDfgrWvrOrWaLyK7iJrgZlcMVgpEQwbbLi3DNB6YzewZN005bh7w9GJDRroIY4)WFhJI(EKUzeF3PWE5g(pTpBWIkZfH18jnDdn7Tkc6ie5ri)IG7A84PAfeuICA024fNJAeu9KqemiItX2NThoonsPyU(onI)Sn2R(SrZliKZlIpj1N)5fPCDSyvxqoeHiZ1zNgnc3zeImZxdc5ur8jXAyvAEbHCEriYmFnVGqoiOeKdbbLGqqqihemfeYPIW5MCQRWfXFAMUuPsfKd5fXNK6Z)8IuUowSQlihIqK56StJgHEgHiZ81GqoveFsSgwLMxqiNxeImZxZliKdc5GCiiOeeccckbbtbHCQiCUjN6kCr8NMPlvQubHG8I4ts95FErkxhlw1fKdriYCD2PrJq8mcrM5RbHCQi(KynSknVGqoViezMVMxqiheucYHGqoieeeuccMcc5ur4Cto1v4I4pntxQuPsfXFAMU8cc5Gqoihcc5Gqqqihemfeu84LUkveMF1NnAErOfZv5LksV1R8sfbFV1PKYlvQiLI5670ixUvQdpZxVWWJJx3Ox4ikJ)d)Dm6fUOo2zx4PyU(oLEbb9(ZCQ3JqQxQxuNUr1fH3(yrkieGrr6TsDnMHpvhTpBb5yrgvkR(owP5mcR1VzvF2YlcTyUkVifoonsB20iJFhR6ZM3chNgHQ(Z2invKBwVLxKchNgPnBAKXVJv9zZBHJtJqv)zBKMkc(ERtjLxKchNgPnBAKXVJv9zZBHJtJqv)zBKMkvK(yKJ0nJ47ofw0nnthnIBwSQpBbbLimdhjwqihH18jnDEWXU1hoonIGo(riHirg7uFNwQx3SyvF2cckr(9XipCJJifHOdp6j6pcEh7wLYXkwqihHQg8dn7Tkc6ie5ri)Iqs7yjvbHamkIBwSsdQrmt2yErOCQFErO9gwJgecIC)nvpVuPI0ByDZpxErU)MQNxQur(u1BtjQUCgPygTv5fH2BynAqoGsK7VP65fKdOeutLkYNQEDkZCNZi(ggLMxeAVH1OrWy(g5ri)IC)nvpVuPIm2XJV7)nfU8IC)nvpVuPI4y(AErU)MQNxQur(u1BJDR5mIBA08IC)nvpVuPIWrKRygTv5f5(BQEEPsf5tvVuo1pOgbpZV6ZwErU)MQNxQur(u1RVHrPb1ifZOT6qErU)MQNxQurOD0lnVi3Ft1ZlvQurkxhlw1rZliKZls56yXQU8Iq)NkrTvd5u8DmhrgIqp9msHJtJqlw9PrASBLMxQi0)PsuBL8XJVJ5iEr3WYZR8gMFViFQ6fR2ux3xin596wqnYNQEzN0P78IZrnOgbR2ux3xin596wekPjVdB4LHJg536veoddN6I4uMr4uJbHDRr8K9XJx)Q7CEFQr(u1lLtnge2TguJq5uJ5YJ08sf5tvV)wVcQr(nLO2QiSFnJOe1wfbDZPzCYBd2HCtSoLsHLNeo1y45iuo1yqy3AqoC1XW0XUkYOE(XJ)HJtJGXe65qEGV9mvKFRCDSyvxErWQn119fstEVUfHsAY7WgEz4OPsfKd5fPCDSyvxEr(u1l7KoDNxCoQb1i0)PsuB1qofFhZrKHi0tpJ8PQ3FRxb1iJ65hp(hooncgtONd5b(2ZikrTv0iYqe6PNIx0HXdJGEqigePWXPr8)0AEh58JhVqAY71TiustEVUnSF1jQr8)0AE7TWXPrOfR0p3iR0i)MsuBve2VMrOCQXGWU1GC4sOqabxfrjQTkIWPgdSO)2K3we)pTM3rW)B(vF24jMXqlwPuEgSWclSWYmgAXkLYhOHgFb7ayzgdTyLs5d0qJVGD6G94hfSWclSWAM(mdS0IvkSdGLzm0IvkLpqdn(cdblSWclS0IvQhPKM8c7ayl3xXqWclSWclyHfwyH1m9zgyPCQXa7ay9qVnkCQXCnr156JkQ4UmgWthU6yy6yxXZGfwyHfwAXk1J0tyhalLtngyhma2dxcfci4kWclSWclTyL6rUtyhalLtngyhma2dxcfcoqayHfwyHLwSs9iXtyhalLtngyhma2dxImky6kWclSWclTyL6rFsSgwDe2bWwUVIHGfwyHfwWclSWcRtRVRbB5(kgcwTncwWcwWcwWcwWcwWcwWcwWcwWcwWcwWcwWcwWcwWcwWcwWgXPmJWPgdc7wJi(KCmUMAmNZ7tnYNQEPCQXGWU1GAekNAmxEKMxQi0)PsuBL8XJVJ5iEr3WYZR8gMFVi(KuF(hrjQTkYV1RiCggo1fPXUvAEPI4)P18MpzUo70O0ihhSWclSWspHDaShhSWclSWclSWc7yNYzy4GDaSOjKCmUMAGf159jA8aSWclSWclSWcBHJtHDaSODoNg0alSWclShLhWclSWcwyHfwy5oHDaShhSWclSWclSWc7yNYzy4GDaSOnej1nVNnfwuN3NOXdWclSWclSWclSfoof2bWI25CAqJhGfwyHf2JYdWclSWclXtyha7XblSWclSWclSWo2PCggoyhalA850WQUrHf159jA8aSWclSWclSWcBHJtHDaANZPbnEawyHfwypkypkyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblyblybBQi)w56yXQU8sLkYyNI(8B(vNOgH1WfH5xDI6Z1XIvDxCoQbHCQurigeYy6a5uj
