### ISSUE TITLE
Trigger > Aura > "Own Only" and "Show On" should be on different lines

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#777]
**Is your feature request related to a problem? Please describe.**
"Own Only" and "Show On" being on the same line implies that they are related to/affect each other.

**Describe the solution you'd like**
Move "Show On" to the next line.

![ownonlyshowon](https://user-images.githubusercontent.com/3958649/45920143-0fb7c700-be55-11e8-98a7-73b58aa085c0.png)

**Comment by emptyrivers** [comment]
Yes, this is a known thing. Thanks for opening a ticket so that we can stop forgetting about it though.

**Comment by emptyrivers** [comment]
Also this is resolved in the upcoming bufftrigger rewrite.

**Comment by InfusOnWoW** [comment]
Still, something that we can fix today. The old trigger will probably not go away for quite some time. And I fixed it.
