### ISSUE TITLE
error message loading weakauras

### ISSUE THREAD

**Issue by hisboyelroy99** [WeakAuras/WeakAuras2#779]
![image](https://user-images.githubusercontent.com/43502216/45920310-60342200-be5f-11e8-841b-04d0930e26da.png)

if i don't load weakauras i do not receive this message. Please advise any thoughts?

**Comment by mrbuds** [comment]
you are using an old aurawhich doesn't work since API update on 8.0, replace it

**Comment by InfusOnWoW** [comment]
That aura is called "Mana bar text"

**Comment by hisboyelroy99** [comment]
I am updated to the latest version of weakauras. This error just runs nonstop until i shut off weakauras.

**Comment by hisboyelroy99** [comment]
I apologize..i am not as good at this as yourself...is that an addon i need to download with weakauras?

**Comment by hisboyelroy99** [comment]
or you are saying i need to go in game and delete an aura i had previously?

**Comment by mrbuds** [comment]
in game type /wa and delete the aura called "Mana bar text"
if you need more please join the weakauras discord, this is not a bug with weakauras itself

**Comment by hisboyelroy99** [comment]
I got it. Thanks. I did not understand that. I will go to discord for future review. Thanks for the replies all!!
