### ISSUE TITLE
Status - Power - Soul Shards % not as expected. 

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#782]
When using a `status - power` trigger with the powertype Soul Shards, using the trigger setting `% = 100` for maximum does not trigger.  Outputting `%percentpower` shows that the percent value is on a scale of 0-10 instead of 0-100. 
Perhaps this is due to the Shards/Fragments thing?

**Comment by InfusOnWoW** [comment]
Thanks, fixed now.
