### ISSUE TITLE
CheckRange function always true if in another zone

### ISSUE THREAD

**Issue by cashballer** [WeakAuras/WeakAuras2#786]
The (relatively new) WeakAuras.CheckRange function returns true for members of my raid that are outside the instance or offline.

For example, WeakAuras.CheckRange(name, 5, "<=") correctly checks if "name" is within 5 yards of me as long as we are in the same boss room. When I check members of group 5 (offline/outside instance) they are always true.

**To Reproduce**
1. Join random world boss group finder raid
2. Try CheckRange function on someone in another zone 

**Which version of WeakAuras are you using?**
2.7.10 which appears to be latest.

**Additional context**
If I change
`if WeakAuras.CheckRange(name, 5, "<=") then`
To
`if WeakAuras.CheckRange(name, 5, "<=") and UnitInRange(name) then`
It works properly.

**Comment by emptyrivers** [comment]
Does this cause an issue with any configuration of WeakAuras which \*doesn't\* use custom code?

**Comment by cashballer** [comment]
> Does this cause an issue with any configuration of WeakAuras which *doesn't* use custom code?
I have only tried it in custom code, so not that I know of.

**Comment by InfusOnWoW** [comment]
In this case, I changed how the function behaved.

But do note, that this is a internal function which behaviour might change in the future.
