### ISSUE TITLE
Idea / related project - desktop app to compare SV with Wago

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#788]
I have been busy trying to make a desktop app that compare your aura from SV with what is on wago to show what needs to updated.

Data we can use :
- url : created by wago
- version : created and updated by wago
- uid : created by weakauras on export
- wago username (user input)

Examples of aura manipulations to show how data lives, and detect edge case for version comparaison :

|# | user|operation | SV uid| SV url| SV version| wago uid | wago url | wago version
-|-|-|-|-|-|-|-|-
1|A|Make new aura | 
2|A|Export #1 on wago | 123456||| 123456| xZhjfg4|1
3|A|Modify exported aura | 123456||| 123456| xZhjfg4|1
4|B|Import #2 from wago | 123456|xZhjfg4|1|123456| xZhjfg4|1
5|A|Export #3 on wago | 123456||| 123456| xZhjfg4|2
6|B|Modify imported aura #4| 123456|xZhjfg4|1|123456| xZhjfg4|1
7|B|Export #6 on wago | 123456|xZhjfg4|1|123456| uflk45sDF|1

- 3 - author A have exported an aura on wago, and modified it on his computer since the export.
a. It's only possible to find the aura on wago with the uid at this stage, this can be like 200 request for a big pack of aura, so for update we either ignore it, or we need a way to do this in bulk.
b. To make this less an issue, we can make the update check for this case only work if user is authenticated on wago and only check uid for his account
c. Also there is no easy way to compare version, it has to download each string from wago and compare fields (way too much data imo)

- 5 - author A has updated his aura on wago
For user B, we can find the aura, or the group of auras by it's url id, and compare the version number to tell him it was updated on wago

- 6 - user B has modified an aura found on wago
Same case as 3.c

- 7 - user B created a new wago from an existing aura
url, version and uid fields on his SV didn't change
There is now 2 auras on wago with the same uid, this as to be considered when solving 3.a

What should be done to make it work: (imo)

To be able to tell author he didn't update an aura on wago, we need to match auras from SV with his auras on wago, and we need to know when he updated it
- Wago - add an API to get a list of all auras urlId / uid / version / id for my account (require auth) in bulk if possible.
- WeakAuras - add a timestamp when something is updated, maybe not for display settings

I think it would work better if authentication on wago was required.

I have done a little app with electron that can find here https://github.com/mrbuds/wa-update
It doesn't implement all the edge cases, so if you are author of most of your auras it will compare with an outdated url (if there is one)
It's the first time i do something with electron and i have not done anything in javascript or html for years, so my code and design is shit

![preview](https://i.imgur.com/UmCBPJJ.png)

I know @oratory has started working on a similar, and probably much more advanced project, i can trash this project if there is no point in continue it, no big deal, i have learned a few things from it :)

Can i get your toughs on this ? @oratory @InfusOnWoW @Stanzilla @emptyrivers

**Comment by krazyito65** [comment]
If you plan on doing automatic updates, you should try to detect if WoW is running or not, and refuse to update until the game is closed.

**Comment by emptyrivers** [comment]
I think the main use case for most users would be “hey, I have this WeakAura set that I really like. Wouldn’t it be great if I could just subscribe to it, and it stayed up to date without any real work on my part?”

To that end, I would expect something like:

- user links their client up with wago via their wago account 
- user subscribes to a wago or collection of wagos (similar to how starring works now).
- author makes an update
- wago does some magic on its end to notify the accounts that there’s been an update, OR client periodically queries wago to see if any subscriptions have updated.
- new versions are downloaded to the client, and then are dropped into a special addon similar to TSM AppHelper, to be loaded the next time that the game is started up.
- WeakAuras handles the actual update and conflict resolution as usual.

**Comment by emptyrivers** [comment]
For bonus points, the opposite flow would also be nice, to allow authors to *publish* their wago with minimal hassle (use the addon’s savedvariables as an output stream, send a POST instead of GET to wago or whatever, etc etc).

This also gets around the problem of exporting excessively large groups (which was only partially solved with #784).

**Comment by mrbuds** [comment]
I made a "project" on my github account https://github.com/mrbuds/wa-update/projects/1

current limits:
- it ask user wago account (optional) and ignore everything coming from it (no export possible)
- doesn't handle nicely auras imported from wago and modified to the point that updating them doesn't make sense anymore.
About that second point a way to work it out is to set a ignore-update flag in-game, and remove that flag on export or better, to make wago remove that flag when importing, that way the flag stay when sharing the aura with link in game

**Comment by emptyrivers** [comment]
It would probably make sense to, with this addition, add a semi-hidden option to regenerate a display’s uid. This would at least allow users to fix point 2 permanently, and it is correct philosophically too, I think.

**Comment by emptyrivers** [comment]
See [here](https://github.com/WeakAuras/WeakAuras-Companion) for the project.
