### ISSUE TITLE
Need help to modify a code

### ISSUE THREAD

**Issue by Muadiib** [WeakAuras/WeakAuras2#789]
Hi,

I found this WA which help to better see the mouse when play WOW.
But something is bugging me.
When I press the right button of my mouse to turn the camera the red spot stay at the position it was when I pressed the button and don't move until I release it.
Is it possible to customize the code to do that the red spot disappears until I release the mouse button ?

Here is a link on wago.io the see the WA : https://wago.io/SkWY_99FX

Thx in advance.

**Comment by emptyrivers** [comment]
This is not a help forum. You can ask for help on our [discord channel](https://discord.gg/wa2) for this, though.
