### ISSUE TITLE
[Templates] Hunter > Beast Mastery > Specific Azerite Traits > Blaster Master

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#795]
**Describe the bug**
Blaster Master is a Fire Mage trait, not Beast Mastery Hunter.

https://www.wowhead.com/spell=274596/blaster-master

**Screenshots**
![wowscrnshot_092918_152816](https://user-images.githubusercontent.com/3958649/46251008-65174980-c3fc-11e8-94e2-4a7ed77c4b9c.jpg)

**Which version of WeakAuras are you using?**
2.7.10

**Comment by Causese** [comment]
https://github.com/WeakAuras/WeakAuras2/pull/796 fixes it

used to copy-paste that trait and forgot to remove last entry
