### ISSUE TITLE
Auras always showing on Options open

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#800]
**Describe the bug**
All of my Loaded auras keep re-displaying every time I reopen WA Options.  If I hide them they should stay hidden the next time I open this session.

**To Reproduce**
1. Open WA Options
2. Hide Loaded auras with eyeball
3. Close WA Options in any way you want
4. Open WA Options
5. Loaded auras will be displaying again

**Which version of WeakAuras are you using?**
2.7.10

**Was it working in a previous version? If yes, which was the last good one?**
I swear it was, but I'm not sure.

**Comment by emptyrivers** [comment]
It looks like [this](https://github.com/WeakAuras/WeakAuras2/commit/0da173f9badea7cb0bae43cd724c96a4b7f9e201) might be responsible. Though I don't quite understand how this setting would persist between game sessions.

**Comment by InfusOnWoW** [comment]
We did implement that, let's see how it feels.
