### ISSUE TITLE
Nameplates manipulation

### ISSUE THREAD

**Issue by Dukas1** [WeakAuras/WeakAuras2#802]
**Is your feature request related to a problem? Please describe.**
I would like to create WA that anchors to all enemy nameplates when they are bellow 30% hp

**Describe the solution you'd like**
I would like to create WA that anchors to all enemy nameplates when they are bellow 30% hp

**Additional context**
I've tried something but only managed to get it to work on my target not on all enemies,
this is what i've dont so far:
function()
    local region = aura_env.region
    local plate = C_NamePlate.GetNamePlateForUnit("target")
    if plate then
        region:ClearAllPoints()
        region:SetPoint("BOTTOM", plate, "TOP", 0, 0)
        return true
    else
        return false
    end
end

**Comment by emptyrivers** [comment]
It looks like you're trying to get help making an aura. Use [our discord server](https://discord.gg/wa2) for that kind of thing.

If you're instead asking for an easy, no code required way to make auras which attach themselves to appropriate nameplates, I think that's well beyond the scope of WeakAuras.
