### ISSUE TITLE
Desaturate Bug regarding Combat.

### ISSUE THREAD

**Issue by Himegami93** [WeakAuras/WeakAuras2#806]
**Describe the bug:**
When you use a spell in combat and the WA icon gets desaturated via triggers if you leave combat and then the skill gets ready again, it will stay desaturated when entering the next combat.

Expected behaviour should be that as soon as you enter the next combat the icon is saturated again indicating its rdy, but it stays desaturated, other effects e.g. glow when off CD still work fine, just saturation.

**Do you have an error log of what happened?**
No

**To Reproduce**
Be Hunter :P
Get this WA e.g. https://wago.io/rklC2HZqX
Go to a dummy for example
Start fight
Use Chimera shot.
Leave combat e.g. just feign death or stop attacking.
wait til chimeara shot is rdy again.
start attacking again

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, the issue persists. 

**Which version of WeakAuras are you using?**
Current Version (2.8.0)

**Was it working in a previous version? If yes, which was the last good one?**
Yes Last versions were fine.

**Additional info**
Sorry that it's once again a hunter specific WA, but it should work with any other spell from other classes with the corresponding triggers just as I set them in this one.

**Comment by fayths** [comment]
I have the same issue as described. It affects all my cooldown tracking weakauras that saturate when off cooldown like posted. 

Once in combat and ability is used then recharged it's fine.
Example WA: https://wago.io/HJGiWIZ5Q

Last version was fine, latest update broke it for me.

**Comment by remcycle** [comment]
I have the same issue as the OP since the new WA patch. I have my abilities desaturate when on CD (Condition: On Cooldown --> True, Then Desaturate [x]). But they often stay desaturated when their cooldown is back up and I re-enter combat. 

Thanks in advance for investigating it! :)

**Comment by emptyrivers** [comment]
This should be fixed in the next release.
