### ISSUE TITLE
All WAs Wiped

### ISSUE THREAD

**Issue by Twintop** [WeakAuras/WeakAuras2#81]
I was working on some enhancements to the Insanity Bar when I went to /reloadui for what was going to be the final time. After reload, all WAs gone from the list. I went and made a backup of the raw LUA before doing anything else. On the next reload/logout, the LUA is replaced with the baseline/empty version. If I restore this backup, regardless of character, the same problem occurs. I have attached my WAs backup.

[WeakAuras.lua.txt](https://github.com/WeakAuras/WeakAuras2/files/387106/WeakAuras.lua.txt)

I'm in the process right now of manually trimming my backup of all of the Insanity Bar auras to see if that helps anything.

Thanks again for everything you do!

**Comment by Twintop** [comment]
Also: problem originally occurred with version 2.2.0.7 from the Curse Client, but the behavior continues with 2.2.0.8 and 2.2.0.9.

**Comment by Twintop** [comment]
I tried a few things on my end:

If I manually strip out the Insanity Bar from the attached LUA, the behavior continues.

Next, I took the new, clean LUA that is generated after the wipe and imported an old version of the Insanity Bar. This worked fine. I then pasted in the Insanity Bar entries in ["displays"] and it works fine with no issues.

Finally, I pasted the entire contents of my old ["displays"] entries in to the new file. It crashed.

I dug through LUA errors and found one that pointed to line 11748 in the attached file. There is a backspace control character that was added in front of ["numTriggers"]. Removing this backspace fixed it!

I have no idea how a backspace was introduced as there was no manual editing of this file.

**Comment by Stanzilla** [comment]
http://puu.sh/qgDZU/eebcf9c584.png

**Comment by InfusOnWoW** [comment]
Well, we have no idea either. This looks, feels and smells like a Blizzard bug.

**Comment by Nevcairiel** [comment]
Honestly the Backspace character in there has ASCII code 09, its supposed to be a Tab character, ASCII code 08.

Smells like random data corruption, ie. a bit flip.

**Comment by semlar** [comment]
Possibly corrupted ram.

**Comment by Stanzilla** [comment]
Blizzard Answer on the topic:

```
Yeah, definitely seems like it's probably just a flipped bit then. Not a great way for us to handle that :(
Don't think we're really going to start storing SV with some sort of error-correcting encoding :P
The issue is, like foxlit said, you're just as likely to get a different (but valid) character that's really hard to differentiate
```
