### ISSUE TITLE
Aura Shift Selecting

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#810]
**Is your feature request related to a problem? Please describe.**
Shift selection is quite common and we should probably support it

**Describe the solution you'd like**
Selecting an aura in a group and then shift clicking on a aura further down or up the list, should select all the auras in between as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by emptyrivers** [comment]
What about shift clicking between groups?

**Comment by Stanzilla** [comment]
Would be a bit odd, no? I'd say only inside OR outside of groups

**Comment by emptyrivers** [comment]
I ask because you can ctrl click to select children in different groups

**Comment by Stanzilla** [comment]
Fixed with https://github.com/WeakAuras/WeakAuras2/pull/812
