### ISSUE TITLE
Aura Conditions not working as intended anymore

### ISSUE THREAD

**Issue by Foreverzero86** [WeakAuras/WeakAuras2#814]
**Describe the bug**
Since the reset of the servers on 03/10/2018, auras' Conditions are no longer work as intended: they behave strangely or refuse to turn back to their default states.

**Do you have an error log of what happened?**
No: this bug doesn't produce an error and there is no error log to look into.

**To Reproduce**
Create any aura that tracks a cooldown or a resource and use Conditions to change the display of that aura based on any event (i.e. track an ability's cooldown and use Conditions to desaturate it when cooldown is "true").

You will see that that the Condition triggers but sometimes refuses to revert back to the default aura's "Display" state when the Conditions is not met.

**Screenshots**
Since it is something you need to see in action, a screenshot doesn't help visualizing the problem.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, the problem is still there.

**Which version of WeakAuras are you using?**
2.8.0.

**Was it working in a previous version? If yes, which was the last good one?**
It was working even with 2.8.0 before the servers' reset on 03/10/2018.

**Additional context**
As an example, we will use one of my Death Knight's aura, the progress bar to track the first Rune:

`!DAvBZjUnq4Fn9JjtGCj9Up0odqmhmxodf5KETZncewcB1yKCLKtG8b(T3DLSXojdzY0jza7vRE23FwO9OjuYwkHJ)dp6e7CJlyzwkjwReuI1XsFWsKplOX96tj7MTzJv4OXx0C2luFFNJzQ0CTzUwQCuYOO4KOfWDkzMhwODmNuR8QzWxejGHbqMfhrjRbyZm6kfFKUqBa)kUhQACF)Nx6)8tWNNFffUKmvRwM2rZEEn751SNxZEOEwrXMx5nRzM3yIXF6Q(96F9fF(I(x(RFb(JU5SRU81GXfwMRYaEoDDDufc9)YhufAMpFwzfltlywlDy4fBPifFoie0WkvzfqM7MObjt(w80VobRivfojCQdnLhd921mhErpaT3dC4JAdppmCflwVEfoGyNCR4fb8PYuB1Ax(CJoZio66d4)tL1j4c(3LkmOnImOgMSVe8EgKkGKztpbEm2kvzGZUVk)g9HvNDy1xnmUuGfaFFMgFASr(8Hv)rfJdjt2HvjGB)SwVn0HH5vpyONF6lWkkZzOZtQKqR8vphD3K)9IFeVyrWuFGyET2WfMHG3Zn6skHOlqOsHywVf7oVRKJvBsv93iUTZfoJmltySbJKCuqttGPcgpQ7byRTAZ6VR5EjzcLWitj56NMPGqg(EqXtS9WmvLscEwzbBpaePu)KW4W0D81bGALme7ixxTztOCmj625JV7wWl8VcffxfGNTAT4ri)tafL7OKLJgqswssgSiPg(L6sbKwHKf53)TGrEP)bgYdb0WkyU8dR(MsML7oSAbgGGhxFkRYPRXKsG6c6BDdXzQbPo5JcFdDrXuU13M2gwOL8jnSQ244ZncVJtMhDleDk2wrN75txd9VPAt)(oFM3yjbH(mF8z9UWZEOCcJIvCpu88usFbzUKBdeuj(KNXHpWXXDq4Y6KQa4Da3MucdjaLhzdJlAY41YaPBzspmb5kpl5jqcXqQK28)3wZfipXo4PQXgCEPEs0Zs5KPpS)MAGpow1oF9wI)tpY5hnhwiuCF6Km4MBAn(7pV5Z7(gKHnZD1ds1WM0qDmfloByPIFoIbEVkBiZ8Z7MEw7BNr8ueDzG)HN6iGBN1rbbTMmINbwO3HvZL7efusUaBKbN4OUnPWHHDmyEYVRXkXaErGQ(jj3LdtKxF(1n3793Afyyr3DsTfVSHP7pdyHEGVG0sVeQgFaAmU0I8fygCHhDYVKcUnWKHdOhw1KINi5CbmlghD)X1YFa43yGroGBdAd8REc74hJsdmpKrlIIIF1E(6oK7sMfMe1kB3jl)uOS(PJtaUG8hH5sXBxbX2HLdTbxNeANjtMTy6FplozaWmGdlYgdfiKtZfPp0LzgB3EKzKS14(xTAKwxW1pPqPfvI6ionNPYeTWeoZ)2P(LcV3VH4uN0KGlnidSBFNFBIdr8OLHF1t)R6Qxy3NRzhFNgGBfBQR)n9Z1ZcydiL0)8pFo0P9iy5p1hno9)o`

This aura loads on combat if the character is a Death Knight in Frost spec. It is a progress bar triggered by the status of the first Rune (note that it is set to always show). Using Conditions, it checks if the Rune is on cooldown and, if it is true, it changes the graphic of the progress bar from the default (defined in Display) to something else i defined in it.

Before the servers reset on 03/10/2018 the aura used to work like this: the progress bar was blue when the first Rune was ready and gray when the first Rune was recharging. Now, sometimes the aura retains the display status defined by the Conditions instead of reverting back to its default "Display" state when the Condition is not met (something that actually did before).

I say "sometimes" because I am not sure what makes the aura behave like this: it worked perfectly before the servers' reset on 03/10/2018, and now it just randomly "breaks".

Take note that I also use this setting for a lot of other things, like abilities' cooldowns (desaturating an aura when the ability triggered with it is in cooldown) or changing colors of resource bars based on amount of resources and they worked perfectly like this one I provided as an example. As another example, with my Paladin I have an aura that tracks the cooldown of Blade of Justice:

`!vAvxVjoou0FnR0SpmvKamT9rGg0Yk2aloDEyEWGjXjyvJDKTtBPpWV99ETt4JQ2DufiHJZ1hF89EphdnIMrjcAAu)F072H3sjwkj(M7UPhLSNskWVqao(RU4LAHYrjtssZswfMlAQw5iI3400(XusUwll0VOYGxLOyBL8c6yk5WIYsl3rtbqzQ8DAZ7GkVX607Xv9yDbZXPKM2Fz5oHwzroyDmJdhuOxxj1Vq3sj4VRdXabSdMeqTuOe2DqKWyyOZpcg7mIQkUbbl1FSBNahcKEHsEazBfxXnICcG2IwuhjFHDasmniAKAj7aSkITMlLPS9WHp6UbdVDiG4HAUNPUgF48N545K140WJw(6Rbh2Tc(2MYYm)6(RK5lN(4CkPDztAtNh3S0ORmCR94MVrWD9pdO55daIHZKKtSHmwYk4h3OlpU5VHmRiNhc)mHh3Y(zf2qEY2S1VPeGmIxPK1tgrYwtYgTk78lxA4(xswMmFEas2wR2S9F0fEmva2TPxYp1IIsTzpIoEeVmFUqncQzpZX31OUOm8)K7ViBh3By)HrHIkZduwacpps)EupF5g7zX(tkzQr82Xn)BdRWWCSJBYGT6joVEeaAUBfd6FWUjlxw(UoZcUfQLgSxecOUTmajICHfB6WwAVq4deh(nFQKvbSFXJzZNLMqj74IQDGuyiSqPM5vxyIeBvm4E4ysS4JPDHQsIklqk2iDcmX2hsZ(ZDUKzTxefz5O5JEyw65y9H5HgtABdJXoL9DpGNESSHJd419GE)wMRTlj)t4IhFlQ9ZUEsy6xVsXl2Z8k0ReXysfMCDRKHNRvqZyRcsPvCmDZrqiwPaKjAh4rGGVNjuFviyY6DSLnsl)khIVonC66w3eScpbQWaB27LRZsjZEibDbvfIoBRGtt(oE(txA5GkKNzgb6rcUpQoPooRSbDu8f5Dmvf)mmH3n23iwZnUdx1GcP74ZrL27M4HxgPpf0wGcb(ByvWHqTc5Wzu)CE5Fc)gJHbTkthmmok(h9URxC)BVh(ql)(W(00bThVZClxl1MwU1MBJM4N7sqJqqrO7ai)tcj6CiNULIssEfRKwWo5u173UCdVckKb7zrU)wgWp9Pdp0230DjKx52P5dxigpGsEru42fe7(32DPyB0q6(pQVGJV3SO0asxO6aMw(AZBAqb41u4fkDBzaerXhB87z94UYpIs4k4Pi2HdgzYQKeW5ObXGeFFX3C)6oXkcE9j4kz9UhG9g3OyYFct4D(UVL4xCrFHWIxood3YZ)JIU)vWPt9hPAGrpdRzqmM2P)3`

The aura is colorized and opaque when Blade of Justice is ready, and thanks to a Condition it gets desaturated and transparent when Blade of Justice is on cooldown. If I engaged in a combat and used Blade of Justice, the Condition kicked in and changed the display of the aura accordingly, but when Blade of Justice went off cooldown the aura reverted back to its default "Display" state, "overwritting" the Condition's changes and turning it colorized and opaque again.

Now it doesn't do that anymore: Blade of Justice is on cooldown, the Condition kicks in, the display gets changed but never reverts back to its default "Display" state when Blade of Justice comes off cooldown (so the Condition is not met), like it did before the servers' reset on 03/10/2018.

As you may notice, there is also a Condition that colorize the aura in red if the spell is not in range of my target. On my Priest I have similar Conditions to colorize my auras in blue when I have no mana to cast the spells they track. Now it happens that if those Conditions kicks in, the aura gets colorized but never reverts back when the Conditions aren't met (i.e. I get in range, I regain enough mana), and it did before.

As a workaround, I can surely set up opposite Conditions in pair to make everything work (i.e. Condition 1 colorize the resource bar if I have less than 40% mana, Conditions 2 colorize the resource bar if I have more than 40% mana), but the issue here is that before the servers' reset on 03/10/2018 everything worked just fine: if a Condition wasn't met, the aura reverted to its default "Display" state. Now it doesn't, and I don't know why.

**Comment by InfusOnWoW** [comment]
Updrade to 2.8.1
