### ISSUE TITLE
Add island expidition to load conditions/trigger

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#815]
GetInstance Info returns 38 for the difficulty ID, and C_IslandsQueue.GetIslandDifficultyInfo() shows DifficultyIDs 1726, 1736, 1737, 1762 for normal, heroic, mythic, PVP island expeditions.

Possibly not worth doing though, since this is probably an expansion-specific feature?

**Comment by Stanzilla** [comment]
The only usecases I can think about can be solved with other load conditions as well, so agree with probably not worth it.

**Comment by emptyrivers** [comment]
Yea, that was my thought as well. But now we have something to point people to when they ask for this.

**Comment by InfusOnWoW** [comment]
If there's a user wanting that for a valid reason, we can add it, but I don't think there's a particular good reason to add it proactively

**Comment by Kha-Khan** [comment]
really minor but i'd like my nnogga interrupt tracker to load on islands too!

**Comment by InfusOnWoW** [comment]
isn't InGroup == Group?

**Comment by Kha-Khan** [comment]
yea but i dont want it to show up for raid, gets too spammy.  I'd use it but can certainly work around it as is.

**Comment by InfusOnWoW** [comment]
That wouldn't show up in raids. Those are separate.
