### ISSUE TITLE
Import Own Progress Texture

### ISSUE THREAD

**Issue by Syulwen** [WeakAuras/WeakAuras2#82]
Hi ! Firstly, thanks for making this amazing addon :)

I'm currently trying to create a custom UI for my Assassination Rogue but I could not find any Progress Texture that suit my need (I want a flat drop of water icon that empties in function of a specific debuff duration). I successfully create and import a simple texture.tga but I could not find any information about custom Progress Texture.

Does anyone have information or a tutorial for me?

Sorry if I should not put this here, tell me and I'll move it.

Thanks :)

**Comment by InfusOnWoW** [comment]
This is a bug tracker not a help forum. There's a huge user community that is happy to answer your questions, it would not scale if we developers tried helped all our thousands of users.

Custom textures work by just putting the path into the path field, there's no difference between texture and progress texture there.
