### ISSUE TITLE
Will it be implemented a sort of converter for users that still use older versions of weak aura with LibCompressor?

### ISSUE THREAD

**Issue by blackrose270** [WeakAuras/WeakAuras2#822]
Hi.
Like i asked on the title will it be implemented a sort of converter for users that use old weak auras for old expansions?
Cause the compatibility with the newest weak auras and the old expansions doesn't let u run properly it
I dont know if there is already a solution for this but now if i try to copy a string on wago.io and import it on old weak auras addons it's just can't load these new kind of strings so here we go with the "question".
Let me know if there is already a sort of converter or any programm to try re-convert these new strings of LibDeflete in LibCompressor cause srsly every players that copy strings from wago.io of old patches can't run them properly.

**Comment by Stanzilla** [comment]
No, we don't support private servers. You should be able to cherry-pick that implemented LibDeflate easily though.
