### ISSUE TITLE
Always Show Nameplates gets removed by WA2

### ISSUE THREAD

**Issue by Rafinono** [WeakAuras/WeakAuras2#825]
**Describe the bug**

CVar - nameplateShowAll gets back to the value 0 and in Advance Interface Options it says Weakaura,lua is changing it back to 0 , aka default value everytime. its getting really annoying.

**Comment by Stanzilla** [comment]
That is one of your auras doing, not the addon.

**Comment by emptyrivers** [comment]
We don’t change any console variables. Check the auras that you have installed, one of them probably has custom code which is doing it.

**Comment by Rafinono** [comment]
Is there a way to know which one, I think there is a number shown. any help would be appreciated.

**Comment by Stanzilla** [comment]
Upload your SavedVariables WeakAuras.lua file

**Comment by emptyrivers** [comment]
You can look through your savedvariables files. Ctrl-F for “SetCVar”

**Comment by Rafinono** [comment]
https://www.dropbox.com/s/onbqq9cq3fhcodh/WeakAuras.lua?dl=0

**Comment by Stanzilla** [comment]
That's the addon itself, we need the WeakAuras.lua in the SavedVariables folder

**Comment by Rafinono** [comment]
https://www.dropbox.com/s/u7mh9v1mcyvtc1s/WeakAuras.lua?dl=0

That was shown that changed mine, I'm sorry this this the SavedVariables

**Comment by Stanzilla** [comment]
It's the aura called `Explosive Orbs`

**Comment by Rafinono** [comment]
Thank you so much.

**Comment by Rafinono** [comment]
THats the only one right?

**Comment by Stanzilla** [comment]
Yup!

**Comment by Rafinono** [comment]
Thanks a lot, that was really tilting me
