### ISSUE TITLE
Don't play sounds on UI load or Entering combat

### ISSUE THREAD

**Issue by dasjestyr** [WeakAuras/WeakAuras2#83]
Annoying side effect. When you have sounds for when abilities become available, they all play on UI load or when entering combat which is annoying. It would be nice if there were an option to prevent that.

**Comment by InfusOnWoW** [comment]
They shouldn't trigger on ui load. The sound should be muted for 10s after login. Can you check in your WeakAuras.lua settings file inside the WTF folder if it contains a reference to login_squelch_time ?

As too load conditions, I think that's too late to change now. You might be better of using the event "cooldown finished" trigger.

**Comment by dasjestyr** [comment]
I don't believe the problem shows when first logging in, but when you zone into different areas, the UI reloads the sounds play. I'm using 'on action usable' so I'll look into 'cooldown finished' when I get back home tonight.

**Comment by InfusOnWoW** [comment]
Can you attach your WeakAuras.lua from the WTF folder and tell me which aura it is? Moving to a diferent zone shouldn't play a sound.

**Comment by dasjestyr** [comment]
Yeah, sure I will do that when I get home tonight.

**Comment by dasjestyr** [comment]
I haven't been able to test anything out since blizz has been having some serious login problems. I was in for a little while and I didn't notice it playing sounds when zoning in. It may have been a coincidence that I noticed while zoning directly into combat. The sounds do play when entering combat, however. Here is the weakauras.lua

https://1drv.ms/u/s!An4RZNl3bFGnj6xE7xRTuhep339bJQ

**Comment by InfusOnWoW** [comment]
While I personally think that playing on the the change of load condition is wrong, we can't change that anymore.

**Comment by dasjestyr** [comment]
That's the second time you mentioned something being too late. I don't understand. Why would it be too late to make changes/fixes?

**Comment by InfusOnWoW** [comment]
Because while technically probably a bug, it could also be constructed as being intentionally that way and it has been this way since years. That means people rely on it, and it becomes a feature.

**Comment by dasjestyr** [comment]
Ok, but breaking changes happen. Either way, I was recommending it as an option

**Comment by Stanzilla** [comment]
Logging in when in combat is a scenario we can not properly support and will always be weird. If you want sounds only happen in combat and already have those auras set to only load in combat, then that is the best you can get already. I was unable to test your auras because you attached the WA.lua file instead of your SavedVariables but like I said, logging into combat will always be broken.
