### ISSUE TITLE
[bufftrigger2] spellID blank after converting multi-target trigger

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#830]
**Describe the bug**
after converting, the "05 Wild Maul (Tank Only)" weakaura's spellid is blank.
It uses aura - multi target

**To Reproduce**
1. import https://wago.io/bfaraid2
2. click on entire group and convert without specifying a trigger
3. check 05 Wild Maul (Tank Only) aura. (spellID is blank)

**Comment by InfusOnWoW** [comment]
Thanks fixed.
