### ISSUE TITLE
[bufftrigger2] multi-target aura is missing an event for cancel

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#831]
**Describe the bug**
With https://wago.io/HJBYPdeKQ when i cast paralysis to interrupt a target while group is dps'ing it, aura should be instant remove, but instead it stay on screen https://i.imgur.com/xTHrErf.jpg

No lua error

**Comment by InfusOnWoW** [comment]
Thanks fixed.
