### ISSUE TITLE
[BuffTrigger2] Tooltip warning should show when you have "Use Tooltip Information" checked but are using %s in Display

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#834]
**Describe the feature request**
![image](https://user-images.githubusercontent.com/3958649/46620991-1db74a00-cadb-11e8-9f1d-dddd12b6041a.png) should show on the Trigger and Display tabs when you're using %s instead of %tooltip#

**Additional context**
I would expect the warning to show if I am using %s in the aura, but no %tooltip# texts.

In these locations
* Group selection > Trigger
* Individual aura selection > Trigger
* Group selection > Display
* Individual aura selection > Display

Super ideally the %s would just convert to %tooltip1, since when using "Convert" I'd expect all incompatible things to change.

**Comment by InfusOnWoW** [comment]
The problem is that there are too many places where %s can be used, and that includes custom code. That's why it's a warning instead of automatic conversion.

**Comment by amiyuy** [comment]
That's reasonable, but "Use Tooltip Information" at least could use a mouseover or something to point the user towards the correct display text.

**Comment by InfusOnWoW** [comment]
Oh, Stanzilla probably renamed it...

**Comment by InfusOnWoW** [comment]
"This adds %tooltip, %tooltip1, %tooltip2, %tooltip3 as text replacements." is the new tooltip.
