### ISSUE TITLE
[BuffTrigger2] Aura Name box does not have preview/icon with spellID

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#836]
**Describe the bug**
Aura Name box does not have preview/icon next to it when filled with a spellID.

**Screenshots**
![2018-10-08_wa_buffid](https://user-images.githubusercontent.com/3958649/46642833-f5a50680-cb2d-11e8-8c90-02d9bf4065d1.jpg)

**Additional context**
This was brought up on Discord, but just so it doesn't get missed.

**Comment by InfusOnWoW** [comment]
Thanks fixed it already.

**Comment by amiyuy** [comment]
Is this fixed?  I still don't see it in the most recent version (38fee73c20f9df6c6cc48f90614cf1ae37f16485).

**Comment by InfusOnWoW** [comment]
Indeed, I didn't fix this properly.

**Comment by InfusOnWoW** [comment]
Should be fixed now.
