### ISSUE TITLE
[LIVE] Some Util.lua error after putting code in custom - event - untrigger

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#838]
**Describe the bug**
After putting some code in custom - event - untrigger I got a lua error.

**Do you have an error log of what happened?**
```
1x SharedXML\Util.lua:192: bad argument #1 to 'pairs' (table expected, got function)
[C]: in function `pairs'
SharedXML\Util.lua:192: in function `CopyTable'
WeakAuras\GenericTrigger.lua:3019: in function `GetTriggerConditions'
WeakAuras\WeakAuras-2.8.1.lua:3573: in function `GetTriggerConditions'
WeakAurasOptions\ConditionOptions.lua:1483: in function <WeakAurasOptions\ConditionOptions.lua:1463>
WeakAurasOptions\ConditionOptions.lua:1815: in function `GetConditionOptions'
WeakAurasOptions\WeakAurasOptions-2.8.1.lua:3276: in function `ReloadTriggerOptions'
WeakAurasOptions\WeakAurasOptions-2.8.1.lua:2544: in function `AddOption'
WeakAurasOptions\WeakAurasOptions-2.8.1.lua:2569: in function `EnsureOptions'
WeakAurasOptions\WeakAurasOptions-2.8.1.lua:2563: in function `ReloadOptions'
WeakAurasOptions\GenericTrigger.lua:309: in function <WeakAurasOptions\GenericTrigger.lua:307>
WeakAurasOptions\WeakAurasOptions-2.8.1.lua:2294: in function <WeakAurasOptions\WeakAurasOptions.lua:2283>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-67.lua:50: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:48>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-67.lua:789: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:610>
[C]: ?
...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-36.lua:71: in function <...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:69>
...faceWeakAuras\Libs\AceGUI-3.0\AceGUI-3.0-36.lua:285: in function `Fire'
...I-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:61: in function <...I-Widgets\AceGUIWidget-WeakAurasMultiLineEditBox.lua:58>
```

**To Reproduce**
1. import wa below and pray that it fires an error since I doubt that I can reproduce it.
what I did is duplicating a wa and adjusting its code + adding code to untrigger. (nothing unusual)

**Which version of WeakAuras are you using?**
2.8.1

**I assume you should get the error too on import since /reload didn't fix it. I suggest backup**
``` !nAvBVjooq4)lR0jDN0jAjL(2jTFGcbwwrdDXHv3NcXK4e82GDUyhAz)q(TFZyNeslTDxbkjE8451Nzgh0pWpGSlGehqubeNE30RpUaiEyrsIIPd8ohiWuuDzbvZc2eq0SN19FqYf6aYDl89xCFaHkI2klMuq3X8pKZciKrlDD9Wn47OAUuyueLBERIOzSNd8aD9SvbOWbMwRnhwXIKIyWGoy2nsMjlgAy3CYdMplvS1MDqBY8HvZrLkTCxnPPGa6DJZ1dU88BV58lU1P)vGdy4tifWtAw(wQrlfsn6GTkCP5OMZC5v3CfkJ6DUd356UB1SZKsruajacmknTqJ(AxL9oUjWEcxWvB)T5hoXJmw(qvolsVe5bdckwwsDEzKRNV7siivKfq2Q15Q)5SZEIMk7XLNrom9hl29Fx(TZ6J2Tmlw(KWhYQUc6MmwCWDO9ZJE8W4AdOnTprIsFybNMvf6rlkKpb5WoqL0mGYMJIfLv7jj8Fcbytkai58cm0Yzt)c4(Bz80TGOU586Z1XMSGSx5HpXJ1BpYVZBAHCaF7twvforwufc5gW7Qc3ivQ)fEvcM)zXmZ7QqNAbnceeGx3Xq5nZJmBSleprjfVqUS)fFl5h8dnWnm6TkpgbqKY63GzYke0SVZkuym072Ax6fsEXkFROnkTJ326n2OMZLTG1(DkRuDRREF8vlC83bc(rWoAuRwb(rr2v6kzPacqvHnfHgcRZPqkIacwU2YXMxOqJGRJ5y9Sp6I4FhZZlmphGpb((PeKlu)DrhC1KmAQYekNpZdcLjyFiIg8cB0IdoagsJ5Q8m6Hz4sV(xC51xF7aeQkI5nELUBgfTzAPw2c)diJLXPMC7EiRAAhMjPMgMX8KeEuzM(GjLaFWB8nfMb7qKKaT)4qI2MNn2wISqFyh1wW8eanoKW3ZoUc(YiReBg4eDGTdzIii8cOoESXKHELc9jCwqJyNq0YRZPMo0H5eICrAHSm)ujlZovYrzuL6eQ57ZFhZZ2xF3gQgD(UUeXP)GbTyLaYFa5CDbpnfsfwqdilGzlj7coQliNdR1TCB2cudDJswS5EzSjoB7ayhI8LHlVFYQ5hNMKaD2X4(FY2dg9Fxf2RxV)Q6RvH2F8KQqZovHF(ZvHFA0I7VBO)65lMU297qNQ1R8MmBo0WYD8NQc1BzIJNT5xMmc7zP57yqb1UCqjQYnU16BlpMnIQGibsxwweXMUA242fEaKVDHPGOD1skpUHcmkxxFo8Z6tHF2LJUNaqazzZgdoMXPp1UrFVXqRDFYdUZNVE0qI)AYQrJCjeWRPI4Usd4Z5ghNbx)EXJMFfm4UhcGRIs2PCXaP(1xSWs5f)aCeADaE5dsmGVcT59h6nYDTR3OfRWbmWxtho1fyBwnOXGPURbz00JeV7qtJ)OTSOhRvP9mwV2uu20CfqZnY47uyAf0nq9Ay2haW(yl9DXyVDSSjS9QcgIaqh1nflf1UJPFijLjGsYiYw5tlaxrzEpem99T3aBnIyHsoaoh3CTMMQPAzH4z4WLBmRFOGLWFgU6icEosMafLi5A4K)WL(wld4Kksl5cwviXms30Ucd0Q6Mjh7MBl8NltrUSJX2ZQPAAaGZjG5d)WKa2BUzywBVM3Ait9O8F5aROFnlfSuiNB78yMvb02d7nWbmk8wBZgdoBZT2GDd()) ```

**Comment by InfusOnWoW** [comment]
The problem is not a "custom untrigger", that box is the custom variables, which expects a table not a function. :)
