### ISSUE TITLE
[BuffTrigger2] lua error spam

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#847]
**Describe the bug**
I was in Uldir, we just killed zul, someone felt in mythrax room (as usual) and i then got a constant spam of lua error https://hastebin.com/ocifucuzit.lua

I had to /reload to stop the spam, and when we did the real pull it continued to spam the same error

The sphere aura: https://hastebin.com/obekiqunug.diff

**Comment by InfusOnWoW** [comment]
Fixed
