### ISSUE TITLE
Enhancement: Button/Automation to clean up displays

### ISSUE THREAD

**Issue by rnyberg** [WeakAuras/WeakAuras2#85]
For example, setting some data to **Cooldown Progress: Spell** trigger and later on changing it to **Item** trigger still leaves the old data into the **Spell** dropdown selection. Now if we re-use a lot of displays by just taking something that exists, and modifying it, we end up with simple displays that have a ton of reduntant data stored in them.

The problem is twofold, for one, this leads into larger export strings which is not good and two, it can lead to all sort of custom code issues. For example: when using `for k,v in pairs(aura_env.state.trigger) do print(k,v) end` I have a display that prints this kind of output for a Item type trigger:

```LUA
percenthealth_operator <=
debuffType HELPFUL
itemName 124637
names table: 000001C1CD3ADFB0
unit player
spellName 49576
custom_hide timed
subeventSuffix _CAST_START
type status
event Cooldown Progress (Item)
unevent auto
use_showOn true
spellIds table: 000001C1CD3AE050
realSpellName Death Grip
use_spellName true
spellIds table: 000001C1CD3AE050
subeventPrefix SPELL
showOn showOnCooldown
use_percenthealth true
```

Now my code is doing custom text stuff based on if `  if aura_env.state.trigger.itemName then` exists or if it's  `spellName` that exists, and the old data makes the custom text display the cooldown of Death Grip instead of Legendary Tank Ring in this case.

I can of course [code around this](https://github.com/rnyberg/Redfella-s-WA-Custom-Functions/blob/master/ALL_cooldowntext.lua) easily, or go clean up the display myself, but I feel that there should be some button in the GUI that let's us scrap all currently unused data in a display and even a group level button would be nice to hit before publishing large groups to other users.

**Comment by InfusOnWoW** [comment]
The old settings are left in there because switching back to the cooldown trigger should show those settings again. Your custom code should check the type of trigger, if it needs to distinguish between different trigger types.

That leaves only that this would make the exported string smaller. Which is rather minor imho. The size of the string has basically no impact on import performance.

**Comment by rnyberg** [comment]
A maximum export size exists and some people are hitting it though. I agree on the switching back, but there should be a way (rather than manual cleaning) to trigger some cleanup when you are done with your display and know you don't need to hold on to the old data.

**Comment by InfusOnWoW** [comment]
The maximum export size is somehwere north of 200 auras in a single group. That's rather rare and thus minor. I don't think this adds enough value.
