### ISSUE TITLE
[BuffTrigger2] Templates - Buff - Always Show - highlight if it buffed not working

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#851]
**Describe the bug**
When creating an aura using From Template for a buff or debuff and choosing the option to always show and glow if it buffed/debuffed it always glow.

Current condition is ```If Trigger 1: Active``` when it should be ```If Trigger 1:Aura(s) Found```

**Comment by InfusOnWoW** [comment]
Should be fixed.
