### ISSUE TITLE
[BuffTrigger2] Aura with a buff from an on use trinket set to always show don't have icon

### ISSUE THREAD

**Issue by Vardex** [WeakAuras/WeakAuras2#852]
**Describe the bug**
When using an always shown aura with a buff from an on use trinket when it's not buffed the icon is a question mark.

**Screenshots**
https://i.imgur.com/7TAu4hd.png

**Additional context**
When you use your trinket, the right icon will be shown untill buff is finished then it will go back to the question mark icon.

**Comment by InfusOnWoW** [comment]
Should be fixed.
