### ISSUE TITLE
[BuffTrigger2] multi-target %unitCaster can show "nitCaster"

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#853]
**Describe the bug**
Using this aura https://wago.io/HJBYPdeKQ
In dungeon i had a rogue sap a mob pretty far from us and it showed like that https://i.imgur.com/gD7kcVl.png

last commit:
commit 9fd48e3f8e6c210e40d9d297865c4aa54ebdf57e (HEAD -> bufftrigger2)
Author: Infus <infus@squorn.de>
Date:   Wed Oct 10 20:55:25 2018 +0200

    Fix affected/unaffected for unit's without names

**Comment by InfusOnWoW** [comment]
I did clean up this a bit as it was inconsistently handled. unitCaster is now always a unit id, if it is available. 
There's a new casterName replacement, which is the actual name of the caster and should be almost always available.
