### ISSUE TITLE
Error decompressing: Unknown compression method (26)

### ISSUE THREAD

**Issue by artistickatt** [WeakAuras/WeakAuras2#855]
Upon importing strings from Wago.io (all the ones I tried) I get an "Error decompressing: Unknown compression method (26)"

I reinstalled WA and I restarted the game, same error. I rolled back the addon to 2.8.0 and I get the same error. 

Otherwise the addon is working fine

**Comment by InfusOnWoW** [comment]
You need to install WeakAuras while the game is not running, and ensure that it is the newest version.

**Comment by artistickatt** [comment]
I always install addons while the game is not running. Just to make sure I uninstalled it while it was not running, reinstalled it (while it was not running) and relaunched the game. I am still getting the error

**Comment by emptyrivers** [comment]
Wago has strings intended for other addons, like ElvUI and TRP3. Are you trying to import those by any chance?

**Comment by Stanzilla** [comment]
Can you link an example that fails please?

**Comment by artistickatt** [comment]
And that would be the idiot move I was making. I had been using wago for years for WA and decided to try a Vuhdo string, but my autopilot was to put it in WA. Sorry for the inconvenience, that would definitely cause that error.

**Comment by emptyrivers** [comment]
Happens to the best of us :)
