### ISSUE TITLE
[BuffTrigger2] group member count not rechecked after closing options

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#859]
**Describe the bug**
aura - unit=group - spellid=17 - group member count < 100%

not in a group, as priest

step 1: not buffed =>icon show
step 2: buffed => icon hide
step 3: open options
step 4: close options (still buffed from step 2) => icon show

expected: step 4 result should be same as step 2

**Comment by InfusOnWoW** [comment]
Should be fixed now.

**Comment by mrbuds** [comment]
with same aura and same steps but instead of open/closing options i change zone: icon show

saw it while porting to dalaran, and can reproduce it by zoning in/out of priest class hall

**Comment by mrbuds** [comment]
https://www.twitch.tv/videos/323124242

**Comment by InfusOnWoW** [comment]
Can you attach your full settings?

**Comment by mrbuds** [comment]
[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/2480669/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
With that I can reproduce it

**Comment by InfusOnWoW** [comment]
Found the problem, should be fixed now.
