### ISSUE TITLE
[BuffTrigger2] Aura Trigger tooltip different

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#861]
**Describe the bug**
Legacy shows the name of the spell that matches the ID when you mouse over the aura (useful for double checking), BuffTrigger2 does not.

![image](https://user-images.githubusercontent.com/3958649/46929271-8dee3000-cff3-11e8-97a4-6fdf8d03939e.png)

**Which version of WeakAuras are you using?**
0b98bba54944314106655d7b07baa27b48cbebf3

**Comment by InfusOnWoW** [comment]
I aded something similar for to what the old code did.
