### ISSUE TITLE
[BuffTrigger2] Spell previews next to Name and Exact Spell ID acting inconsistently

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#862]
**Describe the bug**
Name - Icon shows, but does not show spell name(s) on mouseover as Legacy does.
![image](https://user-images.githubusercontent.com/3958649/46929557-043f6200-cff5-11e8-9b1d-b57e1a384a8e.png)

Exact Spell ID(s) - Icon shows, but tooltip has extra line
![image](https://user-images.githubusercontent.com/3958649/46929570-11f4e780-cff5-11e8-9b79-e0bb8e8fcf5e.png)

**Which version of WeakAuras are you using?**
0b98bba54944314106655d7b07baa27b48cbebf3

**Comment by InfusOnWoW** [comment]
I fixed the tooltip not showing up.

The extra blank line is a unfortunate consequence of the limitations of AceGui, which we can't prevent and I believe the blank line to be the best trade off possible in that area.
