### ISSUE TITLE
[BuffTrigger2] Switching to automatic icon does not update icon

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#865]
When an aura was using an icon set manually, switching to automatic icons does not update the icon in the aura list.

Video: https://streamable.com/3dui9

**Comment by InfusOnWoW** [comment]
That's because you are on a char that doesn't know the spell. The old code actually had a cache of spells. (In addition to the cache that the options have.) I'd like to not replicate that code if possible.

**Comment by Stanzilla** [comment]
We need to solve this with some sort of cache though, opening to gather ideas
