### ISSUE TITLE
[BuffTrigger2] Option to show clones for missing units

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#870]
Making the ticket after a brief discussion on Discord. 
The use case I see for this would be things like a Raid Leader wanting to see who doesn't have the Well Fed buff after they hit the Ready Check. On Live WA the best they could get would be a list of names that is quite awkward to format. 
If the option were added I'm quite sure it would see (relatively) regular use.

**Comment by InfusOnWoW** [comment]
I did implement that now.
