### ISSUE TITLE
[BuffTrigger2] group + auto-clone double entry

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#871]
https://www.twitch.tv/videos/323796349

`!vA1)VPnou8)xMuLALUTgcFF66pa0qh7OHkm9M0DAbmjoGBd2rXoLY(b(B)EpNeiaL1EABmh7NFF)ZNN9Q4nXJO8i3YEXJSYJeG)f2ArICThzOtFynvWxr1mV5GK(0iMNBfpYCQ)ZGqPIGbcft75Ab7jtcyjEexPG5r2mkmS4Ke2cUumztmSFWgbDf3hVCSh51ssPKjApIWCB2RXuralWRlSFm1hSQDzRwyfQVg0SYegAkC)jEGoc5cUAz2Ayz2UWAFqunvO7dxtcE64o3o4rc4F0aEQcmHLfEbnlrqJ(BwIc0TNB7ICa(vjdrcstmBovBImfd0FaKnZ(0eiGrxr5IpU07C9pM8A8GOWhKGxdXZG7(gCtoKEMNggQt4lwWsSlknf56kna7KqxXiAWeutbLk8xkt6J7MvNi9g744AIwujMkukQ5b9N80MvwFV(VGttK6S8cEmnIVq4r654oXzm4OzMhloUMgT8nmbhdDWml9nNHp0)XHfrgfIBBSQZIIgeOYQIQ05SxycnbUf)vpY0EDitMsM0zmOSuSetIJOBW2VcrFiHzeL8GZqq5M9aJXOr6Lq(dcuvrFrQyVRP31QeWl6TGVJKudYivXM6hrvqHiKgPygh1hpzvAKMVRtZiYX7Q4)ID8M6ICFEnmp7H6yxIBreahb8NM9QUsFjKgqf5wXg9tzuGCTycCKJGopkdZuG(63YY22QTDJMwTSBv3UHx4NR14TnjXpvPLRqn9yCac5jPf)FsKhzPwhR(61xVMUq(fU86XuEqxOE0BjZ)5RRy9)anMBkmTcukBNn9pY(NjTTD2nBN9iiyp8Rl)uwH9txT97yRXuM4LVKxUmswChyz9TZawJTZS3otMCWjTYpP6jNuj)KALuphQ(Nt33X0eS1ettPjSlTRuVH9vN1GhlELA1BF1zDIJLUrJMvH4(4)a4h508uy3SEOFhydJRI(DeRBCz8sgsy)iKkPBgKykxeknSlzzDvb6kNVgB)1qlNMhJnKaPO)YP(aJmiI1zG1QLY19qJOqRaAWfmu(YPz3WuPpsHJIza7estFZn52VWsvSSUiJIJa6EKiZgJe3ZvkUyXjG9Fl7XbSoLttpixJTy)a4o)62z9HPtCDAGHLUe5eiP7Ue6z4EWafPj4HC)PM85Ce5UAoxWUhJyWMMqyiysL2CHoHHmFDgAUuWVpR8NVfZfjGREkva4WxWGsSzhQotSHYfCFasAerkUud9IjmOxd631)BLFUDgdhUsnki)o3lHG29ZaaxNtbvIO5zglUdgB6X4GamWE7HLLgBDUrBLgw(XKE)WYpK8y6HPOA8C2o(0CsWUJMmz095tqXdSrI2(r0fqTz0JtgoW1b4az8flHrOnQTFKGgEuKqBFcBpw1fq7qIXugHE)5eK77CNdMy)rNXJhmAmU8HXdCitkq6j4RHowpbCOZ2h2zZjhLiJov(3COvyg)9j7h)s8zCFaSz4fkhaz70fDuEqHtVFS58ZogezDX7zs(9GKp0lSYGJH0pzWTo5fSdoAG7bNejtYXKiS08BvZV1WFFJ56LE90U3TumL94IF5NXAC29IcKQwwMXXVRhSR3kBiE78DkHPo7BXmMZJCbsH0dzdU(Iv0xFS4RtFvNrZ5xWW6s(LeMzyESwQwUlBxoeW34DWODyE6(hQ3VUDn7AnB2Qv1gTA0gEcc8GIQ4B)IxMzZ18aGZ1Gqm6(a8v(Bi790Yl380F1Cd)FWMiaJOmaY36T35TdVBEfy(WzwdWcJBLQ1B3Qjs)W9FEZT5mcGjmDAVacuZgVL3)9d`

**Comment by InfusOnWoW** [comment]
This should be fixed now.
