### ISSUE TITLE
[BuffTrigger2] Unit despawning does not clear aura.

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#873]
**Describe the bug**

I mind controlled something in kings rest and used the teleport after the instance and then ran out of the instance, either the teleport or running out of the instance made my pet despawn, I hope it's the loading screen, otherwise annoying to test.

``` !nw1wVTUnm4Fn7XoKBB9mG9sAAYPbRXTRYzxacuQInTTqLL8KKtA7d93(iLCUS0mCoabjksKI8J8JFI3NNYzsEYGHxp46HCMJZUf2Yz1Cwo9bp1dV6h8OrQ9C2KPjPtFkUx)zgTNjFh4j9hWzV9qrHd88KECMqNvzSN5twRZBQtrpx2Kl8aN129RiZlnAhfmNxy94c0pPw2TQax6QcRX)5TYYsWsMNes)UnOLwat8(ug0AfArn0zfBcMRwJ6JNxQZbroDp1cFwf4yvMDpOXih(DmMkBXu6B4BoSPTOi9Tg007g)0IzlVpEdtugn64geCoibVe(n4bTBGTawSqFKVYzRNmMLUMLo(jmLdNG3ciu(QGBRDnqMSqMTULkb4D5dbIWewOXtvQ55UyTjycRbl8e4FObScVXYz)kwWn1BKAyreNX87EZoW5pMspAHqkXEC69ieiuDXcsishl0HgHiCuACZfMCKiCfw79DugIEWzZSY3)45FVvKJjM4JNtri)canJjq6FsGDEcHcTSMwRpLe0HBnwsXsoIEYG1XnDqMrJfHqJuQ)(T(az67Z(o00NibyCQdnR5jS53ofl7wtPfCoSkMjDu2tS)G9xyGjurMPeLyV4HLP3ppbVIkqwwHtnJ(cNPmIWehXbWo6gH3RGoU0An2VS0FYucxCwrQlXZz3oDC6D)wY8VEhUzDRYl33Hi)IMJSqKcd8ZTWrZVNVPxOqyo4t7li6ByS4s2Fskfee2Bc9NBoMpBHkzwewef4uVgEItd37tUeJAgU9BFkUfrHd(LGDxywkPa1ST5yo(Fm1kY(m(X0XAABoF)WCVt4jQsm)9YSxE72oQtyqLAZxKQGSbWQfQ)avUceLF5aXszSrLg6ZaIcHOF219(5rJUUxVEdVU)xgnyeV4QFAeYtiRW7Tuz2rruIevQ7Eqr(CcMfkX4fLQcgVpjppS9PWsFVpeVEII(b(BuWhtNor(zwuKlE7SjpnDAsNTt1InkiFFrbLr)HgAUsvC2KX7gt9Xqent06neOkOlh13rLJGsSm)GACNwmkYzu5MDA6DL9Xe9uOAQI(StMJ6QH5RSVnMBPqS8FE7V)l9xh047rnoCUZbhaY)VSw44tWnjHi3)Yw8Pkuio7LtFZk5keYBfwj5fNno52oJ(8ZBeyoAj8AJmY7sL4RmmttqZFRq1cHNa7ySzvcDjC82IgCtq7cFSaNQIujpvpoConuAA15RTqdicN1TruF8EdfVWoifNO24SiSACEoI2v)jiEzmov4w9i(CJnSCbKlfRyKhUv7KQkqv)JMYY93lLNAqXzleo86Ou)yggdK)aM665emik9CDhnfpBlIZrdOEj)F) ```

**Comment by InfusOnWoW** [comment]
So far no one has reported this again, neither could I reproduce it.
