### ISSUE TITLE
Glow sub options 

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#880]
Glow sub options (glow type, glow color) should only show if the main "Glow" box is enabled.

and the glow color box should probably be the same as the other color boxes, defaulting to the standard ui color?

**Comment by emptyrivers** [comment]
What do you mean by standard UI color?

**Comment by Stanzilla** [comment]
Sorry, the standard color checkbox we use, like here https://i.imgur.com/R13ac6d.png
