### ISSUE TITLE
[BuffTrigger2] "Buff Type" for buffs or IsEnrage

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#882]
"Debuff Type" option only show for debuffs
IsStealable is there for magic buffs, but there is nothing for enrage
It was possible to do with legacy aura trigger

**Comment by Stanzilla** [comment]
two options:
a) show `Debuff Type` for everything again
b) change `Is Stealable` to `Is Stealable/Dispellable` and enable it for enrage as well

thoughts?

**Comment by mrbuds** [comment]
as a tank i may want to see every buff on my target (no filter)
as a healer or tank i may want to see both stealable and enrage (filter only stealable+enrage)
as a dh/mage i want to see stealable (filter stealable)
as a hunter or dps drood i may want to see only enrage (filter enrage)

2nd case can be tricky .. maybe it's better to ignore it and recommend to make 2 auras instead
