### ISSUE TITLE
[BuffTrigger2] Filter friends or enemies with unit=nameplate and unit=multi

### ISSUE THREAD

**Issue by mrbuds** [WeakAuras/WeakAuras2#883]
unit=nameplate and unit=multi can both show friends and enemies, it can be useful to have a way to filter that

**Comment by InfusOnWoW** [comment]
I'll leave that open for a while, as I'm not entirely happy how complicated the code for supporting all the various group filter options is, and how long it took to get that right.

**Comment by InfusOnWoW** [comment]
To expand a bit. The group trigger is smart in that matches for a group unit are only checked against triggers that match based on the group role/Ignore Self setting. The way that is done, is to filter down the list of triggers per group unit.

Unfortunately I didn't properly design and that's where sooo many of the group trigger bugs come from.

I think, there's a potential for a much cleaner design, where the matchData is encapsulated in a object, which has just 3 methods:

ScanUnit(unit) -- reacts on a UNIT_AURA event
AddTrigger(unit, filter, triggerInfo) -- adds a trigger and checks it against all existing match data
RemoveTrigger(unit, filter, triggerInfo) -- removes a trigger and removes it from all existing match data

For normal triggers, Load basically calls AddTrigger, Unload calls RemoveTrigger.
For group triggers, On Load or GROUP_ROSTER_UPDATE iterate over all group units, filtering and calling AddTrigger/RemoveTrigger as necessary.

Then the code that handles matchdata doesn't need to know anything about group triggers, and implementing something like friend/enemy nameplate filters becomes much easier to implement.

Anyway, I'll let this rest for a bit and see what other feature requests come in for the buff trigger.

**Comment by mrbuds** [comment]
some ideas for additional filters
- UnitIsPlayer() => active only on players or only on npc
- Ability to check more than 1 type of debuffType => ex: show magic & enrage only
- negative filter => ex: filter out the buff all mobs have in mm+
- as mentioned in #937 range check filter

conditions could be extended to use some more filters too, for example if i want to glow when debuff is magic

**Comment by mrbuds** [comment]
unit=nameplate doesn't allow to filter self, it can be handy when CVar "nameplateShowSelf" is set to 1

for context, while trying this aura https://wago.io/4JOSDWl73 i have https://wago.io/AnchorDebuffsToNameplates showing my buffd on the middle of my screen, and no way to filter it without drastic measures

**Comment by hyorinmaru92** [comment]
Add filter for dead person/target for unaffected by given buff/debuff found by multi-target aura trigger.
