### ISSUE TITLE
Beta Releases

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#887]
Because rivers brought it up again, there are several ways how we could do this, easiest probably like we do expansion branches, with beta releases being pre-releases on github and beta releases on curse, just need to decide if we want to constantly maintain a second branch and always merge master into it when we think something is ready and always do our full releases from that branch as well or just stick to one master branch and try to make the script create beta releases based on the tag name so it pushes github pre and curse beta releases.

thoughts?

**Comment by emptyrivers** [comment]
I think that the easiest method would be to just tag (mostly) stable points in `master` as either `versionNoBetaN` (similar to the bfa releases that happened this summer), or as `featureBetaN`. 

So, for bufftrigger2, we would either make releases tagged as `2.9-beta1`, or `BuffTrigger2-beta1` or something like that.

**Comment by emptyrivers** [comment]
And given the current pattern of only one big beta-worthy change being in pre-release at a time (😏 looking at #694), going with `BuffTrigger2-betaN` is imo the most informative option.

**Comment by Stanzilla** [comment]
I'd probably do `2.nextMinor.0-beta` tags, yeah.

**Comment by emptyrivers** [comment]
Another question worth considering: consider a user who sets their preferred release type as Beta on the twitch client. What happens if they’re on some beta, and then a stable version gets released? Is twitch smart enough to push the newer version to them?

**Comment by Stanzilla** [comment]
yea usually that works

**Comment by InfusOnWoW** [comment]
I think the .0 is redundant. That is, our usual pattern is 2.X.0 is a big release, 2.X.y are small bug fix releases, so those probably won't ever be beta worthy.

At my favorite work place, we used 2.(x-1).90 as the beta version. But that's not really something the world seemed to understand.

Also I think for now, sticking to one branch is probably good enough, juggling branches seems a bit much.

**Comment by emptyrivers** [comment]
Yea, my thinking is that we could explain to users: "Use beta if you like to get new toys earlier than everybody else, but without having things randomly break on you quite as often as alpha". A bugfix doesn't really count as a new toy imo.

**Comment by amiyuy** [comment]
Yes, Twitch prioritizes newer Releases over Betas.

What Rivers said is what (as a user) I generally expect from alphas/betas on Curse.

* Curse Betas are for the more general audience who want something before it's 100% ready - this shouldn't break, but still needs testing before we release
* Curse Alphas are specifically for testing - this probably will break, tell us when it does

**Comment by Stanzilla** [comment]
Started doing them, just need to write a text that explains it to users.

**Comment by Stanzilla** [comment]
The changelog generation script does now filter out tags with "beta" in the name when comparing versions so a release gets the full diff instead of from the last beta tag to current.

**Comment by mrbuds** [comment]
What about adding an incremental build number to each packaged release (alpha included) ?

With 3 versions of weakauras in the wild, that's something convenient for aura authors, when they use bleeding edge features it would give them a easier way to test and warn user if it's version is incompatible.

**Comment by Stanzilla** [comment]
we already do that, take a look at https://www.wowace.com/projects/weakauras-2/files

**Comment by mrbuds** [comment]
local str1 = "2.9.0-beta2-5-g8174110"
local str2 = "2.9.0-beta2-2-gea0f6c3"
print(str1 > str2)
> true

hoo nice 👍
