### ISSUE TITLE
Entering Combat while moving aura breaks things

### ISSUE THREAD

**Issue by amiyuy** [WeakAuras/WeakAuras2#890]
**Describe the bug**
If you are moving an aura and then enter combat, interesting things happen.

When moving a single aura: That aura is dropped out of place and displays as in that spot, while WA's Options keeps the old location.  After reloading the aura is back at the old location.  

When moving a group: You lose control of right and left click on your mouse and the aura follows your mouse either during combat or after you leave it.  You must reload to get mouse control back.

**To Reproduce**
Single aura:
1. Select aura and move
2. Enter combat while still moving
3. Leave combat
4. See difference between location on screen and Options

Group:
1. Select aura and move
2. Enter combat while still moving
3. Try to turn screen with right click
4. Try to click anything with left click

**Screenshots**
Before combat
![wowscrnshot_102418_094438](https://user-images.githubusercontent.com/3958649/47447090-9839c800-d771-11e8-826c-d70ef00cef71.jpg)

After combat
![wowscrnshot_102418_094458](https://user-images.githubusercontent.com/3958649/47447114-a5ef4d80-d771-11e8-8da0-d8b27a85d7e3.jpg)

After reload
![wowscrnshot_102418_094516](https://user-images.githubusercontent.com/3958649/47447125-aa1b6b00-d771-11e8-9c0f-976a457db62c.jpg)

Videos: https://imgur.com/a/53t6aPv

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes.

**Which version of WeakAuras are you using?**
2.8.1-40-gdcea081

**Additional context**
Saved Variables: https://www.dropbox.com/s/zjn0fvvlfvdt8oi/2018-10-24_WeakAuras.lua?dl=0

**Comment by InfusOnWoW** [comment]
Fixed.
