### ISSUE TITLE
[BuffTrigger2] %tooltip values not updating

### ISSUE THREAD

**Issue by crcarrick** [WeakAuras/WeakAuras2#891]
**Describe the bug**
I have a WeakAura that shows one of the tooltip values of the Touch of Death debuff on the target.  During the time Touch of Death is on the target, 10% of any damage you do is added to the value Touch of Death will hit for when the debuff expires.  This value is part of the debuff tooltip and so the WeakAura simply grabs that tooltip value and displays it.  It worked in 2.8.1 but in the current alpha, after converting to the new BuffTrigger2 and using the new %tooltip text replacements (%tooltip1 specifically) the displayed value no longer updates as expected.

It's entirely possible I haven't updated the aura properly to work with the new trigger and if that's the case I apologize :)

**Do you have an error log of what happened?**
There is no error as far as I can tell

**To Reproduce**
1.  Cast Touch of Death on the target
2.  Do some damage
3.  Observe that the %tooltip1 value is not updating properly

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.8.1-40-gdcea081

**Was it working in a previous version? If yes, which was the last good one?**
Yes, it was working with the current non-alpha/beta release.  This problem only occurs after converting to the new trigger type.

**Additional context**

!nwv3wnoom4NgoZUxaKMs)H9UsPDMUle4Gdd3LIBItJxCSZy7qPZf8SVsYPu(Bo7CoTjoYsYFs6tYz9YsZy1zSc8hS006vsTiJD1TPxSizgiw6Au8TPIN8zSd8gJYlB6LX2EvzPt4Zs6piJX15vg71gPguA6SK0z3KXYBDEtnA4TnfCp402DVTQmwL334(RJpEdFT5iP5y7FNou9J4RxDCFWH5EPr7qi58CRhwaEUuQLUQWAyzqkS2BLRxlSO6jue1jaxYB9MCLbIPvGVAek1IcqREdIghbiXj(Q102Sm30cyhuPM7ZReowLzZvAWc69eaopcaVSvPC5CD2zGPiaya4wdzbMMxd7NAAZRE(Et5Z3FUG7Ra7BxfC9z0AXJcT)AROu(ugJD9SlUGWWsYzKtjncWExkCzLSaCUxwlk27fwBj5LLtNWsxYsNCdeTfIvG40TnG(FBYnxo)w4a80N8wlpoa0LMgHL7nwkLw8hF5a3x(ZaqcoyQI7Cy2aen7jOyW6sCaenB0xPvBXLLcixLgOe43Dy)BcUcJD8ePmUSOR0W6Y7(WHrjnWo8i)8eExbZfQ5fGdrEb4NqGCn37fw9YFv2p3uVcOZxgQPbNFHzJW1vX687RD1NMAq8Q3tQishNGyAq4LgOcbbirmr)WvFhiKiwtofoxHQ8DDhoVm)HTNVlIGCDPb3FvXC6DLqUUYNnFWW4the1B44EdpD4ObNMvE4jJZykdNAyX0yJWVcqVs0vXwIKil(rovhXMiPEnSp7YRs(hGJ3cvSDXbAqqpOsynGwPFIgqHiN4WYF(gfyUCHMBLgCtVG6m8BaAW2sSaIKeJ1VTo0Z0aTYbMJs8KCLIuGBbpS3osVhr(uO3MRaPXFaub5FqmHZ9bCs)3TFHe6AYbjBFtuOn2AUcp68kUc88AcAvcRrsXTQ0sqe6b3WvpaEh)SERVI23)gk9kkc(fiemfN48PzzKVYPbbwE(hleLHXIVxUpWDyyPjjo6Lz2qok)bG1Fa83kwdwggm4Pz5fch3J0pcVDMSihzSdJgoyqm2(OlK7geJuETSMVdb7Ml3nErJJyFPdDzqOtGUWH2wZL6FFTFzs)VN(DdmrWLFNSaB9Nqdq)xyaQSC7(2UN2DT1H9IhqbbKIMczpaE100RfjSfNdx89tJPoljQBumKI2qoE(OO(dhpkoEuu844rd711qkl(4aONVpLUE457NutxcazuLXgMfI)IPN9PNN0n)O0cui4gmUNtJmd3TohLgkFSP3mBwcGhJT4olVjJD3lRAry4)UsEcVi6Rt1iDdMf4OASelUNfilZv81UxDnpCvIOiK6aku0UmZ7gAHmNP)VHa2gMXIpA8r9o8KOdxxKl4rJHq5ry)tIrvY(Vp

**Comment by InfusOnWoW** [comment]
Fixed in the next alpha build, thanks for testing.
