### ISSUE TITLE
GCD progress bar is displayed incorrectly.

### ISSUE THREAD

**Issue by ILIKECHICKENTOOMUCH** [WeakAuras/WeakAuras2#899]
**Describe the bug**
Unlike the circle shown in the previous version, the 2.8.1-48-g06fd83f version is viewed as a crushed circle.
I think the issue of the person who writes below are similar.

**Screenshots**

![weakauras-2018-10-27 18-51-02](https://user-images.githubusercontent.com/33839642/47602420-a578e000-da19-11e8-96d6-ca7bdfd100cf.gif)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, I tested it with no other addons

**Which version of WeakAuras are you using?**
2.8.1-48-g06fd83f

**Was it working in a previous version? If yes, which was the last good one?**
It was fine until version 2.8.1-45-g57696da

**Additional context**
↓ GCD Weakauras String Page ↓
https://wago.io/HJdVCNG6W

**Comment by blub0r** [comment]
![issue_2 8 1-48](https://user-images.githubusercontent.com/41595014/47603595-7d27bc00-d9ee-11e8-9085-abde5f017890.jpg)
**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Problem exists also with disabled addon.

**Which version of WeakAuras are you using?**
2.8.1-48-g06fd83f

**Was it working in a previous version? If yes, which was the last good one?**
All versions before ran without complaint

**Additional context**
↓ GCD Weakauras String Page ↓
[example_issue.txt](https://github.com/WeakAuras/WeakAuras2/files/2521720/example_issue.txt)

**Comment by Stanzilla** [comment]
A user linked me this http://imgur.com/a/kR2I9Rq

**Comment by InfusOnWoW** [comment]
Should be fixed now.
