### ISSUE TITLE
Template for AZ trait Steady Aim (MM) incorrect

### ISSUE THREAD

**Issue by Phylo** [WeakAuras/WeakAuras2#901]
**Describe the bug**

When you add from templates it adds it as if was a player buff that it needs to track.  In fact its a Target Debuff

**To Reproduce**

1. Go to New > From template
2. pick any of them like Icon
3. choose the Azerite Trait Steady Aim
4. the triggers section has it looking at the unit Player, and the type buff.

**Comment by Stanzilla** [comment]
That was fixed last week, in https://github.com/WeakAuras/WeakAuras2/commit/1d59c1492c9afe7a87607166d3bc5100f1030b20
