### ISSUE TITLE
[beta] (minor) Status trigger Duration set to 1

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#912]
Making a new Aura and changing from Type from Aura to Status (defaults to show Health) shows an empty Hide section and a Duration of `1` 
Presumably https://github.com/WeakAuras/WeakAuras2/pull/885
It doesn't appear to affect the functioning of the trigger at all.

**Comment by InfusOnWoW** [comment]
Fixed.
