### ISSUE TITLE
Converting a tooltip scan aura to BuffTrigger2 causes massive bug

### ISSUE THREAD

**Issue by Xyxeii** [WeakAuras/WeakAuras2#914]
I first encountered this bug when bulk converting my auras to the new BuffTrigger2. After a lot of trial an error I was able to cleanly replicate the bug while converting a Legacy Aura, with full scan enabled and tooltip checked containing a key word. For the test I used the word "speed" but I found that the word used didn't seem to matter that much. Doing this causes the following error: 

```
1x [string "    return function(time, matchData)..."]:2: attempt to index field 'tooltip' (a nil value)
[string "    return function(time, matchData)..."]:2: in function `scanFunc'
WeakAuras\BuffTrigger2.lua:1669: in function <WeakAuras\BuffTrigger2.lua:1575>
WeakAuras\BuffTrigger2.lua:1688: in function `LoadDisplays'
WeakAuras\WeakAuras-2.9.0-beta2.lua:1788: in function `LoadDisplays'
WeakAuras\WeakAuras-2.9.0-beta2.lua:1654: in function `ScanForLoads'
WeakAuras\WeakAuras-2.9.0-beta2.lua:1739: in function `ReloadAll'
WeakAuras\WeakAuras-2.9.0-beta2.lua:1445: in function `ScanAll'
WeakAuras\WeakAuras-2.9.0-beta2.lua:1395: in function `Resume'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:182: in function <...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:164>
[C]: in function `Hide'
WeakAurasOptions\WeakAurasOptions-2.9.0-beta2.lua:1569: in function <WeakAurasOptions\WeakAurasOptions.lua:1567>

Locals:
time = 9358.892
matchData = <table> {
 spellId = 2645
 duration = 0
 expirationTime = 0
 unitCaster = "player"
 stacks = 0
 time = 9358.892
 casterName = "Crj"
 unitName = "Crj"
 icon = 136095
 UpdateTooltip = <function> defined @WeakAuras\BuffTrigger2.lua:166
 auras = <table> {
 }
 name = "Ghost Wolf"
 filter = "HELPFUL"
 index = 1
 lastChanged = 9358.892
 isStealable = false
 unit = "player"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'tooltip' (a nil value)" 
```

**To Reproduce**

1. Create an Aura (icon was used for testing, but I confirmed this happening to a text aura as well. I don't think it matters)
2. Go to trigger and change the type to 'Legacy Aura'
3. Enable 'Use Full Scan (High CPU)'
4. Enable 'Tooltip', change the operator to 'Contains'. In the edit box below, type something. I used 'speed' during testing.

_All of this is to setup the aura to act as an aura created prior to the BuffTrigger2 update, as the issue is caused when converting the aura to BuffTrigger2_

5. Click 'Convert to New Aura Trigger'
6. Close the Weak Auras options

The bug should now pop up. **Note, unchecking 'Tooltip Pattern Match' closing WA can fix the bug.** Furthermore, it's possible to reproduce the bug by changing the same aura back to legacy and reconverting it. 

During my trial and error process with this bug, something strange happened. After a while of converting a test aura back and forth, the bug just stopped happening. Even creating a new aura and attempting to recreate the issue wouldn't cause the bug anymore. Bulk converting my old group no longer caused the bug either. However, when I reverted my Saved Variables to before the troubleshooting process, I encountered the bug again using the above method. 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes, the bug still occurs with only WA enabled. 

**Which version of WeakAuras are you using?**
v2.9.0-beta2

This bug did occur during the first alpha build using the new BuffTrigger2. I just didn't report it at the time.

**Additional Thoughts**
The consequences of this bug are pretty huge; many auras fail to load (even auras that presumably had nothing to do with the auras causing the issue). You can undo the issues caused by the bug by isolating the auras that caused the issue and deleting them; however when converting a large group of auras, it can sometimes be difficult to figure out the aura causing the issue. The first time I encountered this bug in alpha, I just bulk converted group after group and didn't notice the bug until I closed Weak Auras. At that point I had no idea which auras might have caused the issue. 

I hope I've provided enough information, if I figure anything else out that might be of use I'll make sure to add it here.

**Comment by mrbuds** [comment]
I can reproduce the error, without converting from "Legacy Aura"
- new aura
- check Use Tooltip Information
- check Tooltip Pattern Match > contains > speed
-> close options > error

**Comment by Xyxeii** [comment]
Using that method, if I: 

- uncheck 'Tooltip Pattern Match' 
- close the options
- open the options again
-check 'Tooltip Pattern Match' 
-close the options

Once I've done that, I can't replicate the error anymore; even with new auras.

**Comment by InfusOnWoW** [comment]
Should be fixed in the next alpha/beta/release.
