### ISSUE TITLE
[beta2] Advanced glow options are hidden if glow is disabled

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#915]
* ~~"CLEU" will mean nothing to most people and only raise questions I think. "Multi-target" is a known name to people who used WA before. I understand wanting to spell out the difference between it and "nameplate" but I'm not sure adding "(CLEU)" helps much in that regard.~~
* ~~"Group member count" and "Match Count" are poorly differentiated. I had to ask before it made sense, even though I had followed some of the discussion about these options being created. I don't have a great solution to suggest, it's a relatively deep concept. Might need a toolltip.~~
* ~~"Group Member Count" makes sense for the "group" unit but is also used in Arena, Boss, and so on. "Boss Count"?~~
* ~~With "Combined Matches Per Unit" selected I expected `%matchCount` to give a per-unit count. So I could, say, see how many DoTs I have on each nameplate unit.~~
* ~~Feels odd to have a "Use Custom Glow Color" Condition option that must be enabled before the "Glow Color" option will take effect. It doesn't stand out as a problem in the Display Tab context but in separate Conditions it's awkward. Could they be combined? Is an Enabling bool needed at all?~~
* ~~Pixel Glow uses the ActionButtonGlow start animation. I think there may be a ticket about this already, or is otherwise known.~~
* ~~War Mode Active (Load tab) still flagged as new. That's from the previous major version I think(?)~~
* Changing the glow type used by the Icon Aura requires you to enable it (permanently glowing). You _could_ then disable it and the alternate settings would remain but that's not intuitive behaviour. I think most Auras using glows will enable them through Conditions but any alternate glow there, without changing the base settings, would need to change up to three properties each time (enable, change, type, change colour).

~~On a side note, could a `unitID` value be added to the states too? With options like "Nameplate" existing, having the unit available in code blocks like On Show could make things like anchoring to nameplates quite easy and, I'm guessing, would be a relatively simple addition?~~

**Comment by asakawa-k** [comment]
Oh. I had a look in the state table with VDT and didn't see it. 
I see why though, I was looking at the region's state, not the specific clone. 
Got the unit now. 👍

**Comment by emptyrivers** [comment]
On the glow options, I went with this for the sake of backwards compatibility. The glow library we use accomplishes coloration of the action button glow effect by desaturating the texture, and then using SetVertexColor. The practical upshot of this is that in order to keep existing auras from suddenly changing their appearance when a user updates WeakAuras to a version with the new glow library, I needed to separate “use a custom color for glow” from “set the glow color”.

**Comment by emptyrivers** [comment]
And also talk to deezo about the pixel glow issue you saw.

**Comment by InfusOnWoW** [comment]
On the new feature indicator, that's discussed at https://github.com/WeakAuras/WeakAuras2/issues/654

Currently the consensus is 3 to 4 months.

**Comment by emptyrivers** [comment]
The question of how long to mark a new feature as actually new is already tracked in #654.

**Comment by InfusOnWoW** [comment]
I'll remove the CLEU part then, and rename Group Member Count to Unit Count + add a description to match count.
I can add a %matchCountPerUnit, but please report that as a new ticket.

**Comment by asakawa-k** [comment]
I'll make that now.

**Comment by asakawa-k** [comment]
Added a bullet about Aura-wide glow settings feeling a little unintuitive.

**Comment by InfusOnWoW** [comment]
All done now!
