### ISSUE TITLE
Make OmniCC Cooldown Text hidable

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#920]
**Is your feature request related to a problem? Please describe.**
There were times where I wanted to switch from Cooldown Text to %p, but two issues raised up:

a) i need 3 text regions (%p, regular name, %s) -- i believe this is being worked on

b) OmniCC hides the "Cooldown Text" option and re-enables it, even if you disabled it manually by removing the "Cooldown Text" checkbox. This causes both %p and "Cooldown Text" aka 2 timers to be shown.

Switching to %p would also fix the issue with **a crazy amount of players** not having timers on their weakauras since they have to enable a setting for that in Interface -> Action Bars (Show Numbers for CD)

**Describe the solution you'd like**
1) I believe infus is already working on a) but to truly benefit from %p weakauras needs their own OmniCC equivalent, e.g an option to change color when timer is a) about to run out / b) far from running out with an option to "enlarge" the timer if a) happens

I know this can be done with conditions but i feel like people want it to be in "Display"

2) Well, not allowing OmniCC to mess with the author's decision to disable "Cooldown Text" would be a good thing, dunno if possible since it's a blizzard option..?

**Comment by asakawa-k** [comment]
OmniCC does not do anything, WA hides it if omniCC is loaded...     <https://github.com/WeakAuras/WeakAuras2/blob/8449a11f7252c80eb701e251d68533090eb59598/WeakAurasOptions/RegionOptions/Icon.lua#L34>     
The thinking being, I imagine, that if you're running OmniCC then it is handling the display of CD text, including the OmniCC options to show/hide on individual Auras. 

I don't know how much the devs think it's appropriate for WA to work around other addons but everything you mention here is you getting yourself tied up in knots over an addon that's totally external to WA. I don't use omniCC and never have any issues.

**Comment by Causese** [comment]
hmm that's even better... so all it needs is something that brandmarks the exported aura with:
"the author disabled cooldown text, don't re-enable it unless OmniCC is loaded and cooldown text is checked manually by the end-user"

instead of the current:
"ignore the author's wish to disable cooldown text and automatically re-enable it if OmniCC is loaded"

it just doesn't make sense to me to give more power to an external addon over your own addon's display settings

**Comment by InfusOnWoW** [comment]
I'm pretty sure for that we have a ticket for a)

For b), the Cooldown Text option is hidden for omnicc, because it has not effect.
Configuration of the text is done in omnicc if the user has omnicc enabled.

We aren't going to replicate omnicc, users that want omnicc behaviour should install omnicc.

**Comment by InfusOnWoW** [comment]
Try to explain the problem, not what solution you want. I have no idea what you are trying to solve.

**Comment by Causese** [comment]
once a) is implemented I want to switch to %p + cooldown swipe + 2nd text region (%s) +3rd text region (in the gif it's: Dodge!)
https://i.gyazo.com/f35323fb4c879dc407cda087a6bfce12.gif

but aslong as OmniCC enables its own timer even if the weakaura's author unchecked "Cooldown Text", I just won't do it cause I'm alienating the part of the community that uses OmniCC.
Nobody wants to have 2 timers on their weakauras

If I enable OmniCC with the above weakaura, this happens:
https://i.gyazo.com/cf9054535d8e69232d9a89b48a446c4d.gif

so my main issue is that "Cooldown Text" is automatically enabled upon loading OmniCC.

Instead you should imo make it so that UI requests a reload when enabling "Cooldown Text" with OmniCC loaded

**Comment by InfusOnWoW** [comment]
Cooldown Text is NOT automatically enabled upon loading OmniCC. The Cooldown Text is NOT under control if omnicc is loaded. So any request to somehow make Cooldown Text work differently when OmniCC is loaded are impossible.

I suggest you don't use %p at all. Users that use OmniCC will get the cooldown text that they have configured in OmniCC. Users that have elvui, will get whatever they do. (iirc they do something similar). Users that use the default UI, get whatever setting they have configure in their UI settings.

**Comment by Causese** [comment]
Okay I think I get it.
Is there a way to seperate Cooldown & Coldown swipe and is that something that might be added?

That would be a solution since disabling Cooldown also disables omniCC's functionality and allows me to use %p without having 2 timers.

**Comment by emptyrivers** [comment]
Yes, I plan on adding options to help control the cooldown and cooldown swipe of icons.

**Comment by InfusOnWoW** [comment]
That's not what's asking though. He's asking whether we can control the text from omnicc separately from the cooldown spiral. 

I don't actually know that, since OmniCC changed quite a bit a few months ago. That might be possible now.

**Comment by emptyrivers** [comment]
I’ll look into it when I get the chance.

**Comment by InfusOnWoW** [comment]
I've looked into this in detail now. 

And omnicc doesn't offer any API for addons to control the cooldown text, the only configuration is for the user. 

So my recommendation is to tell users that they should either:
* Install OmniCC
* Enable the Blizzard option for showing cooldown texts
* Or have no cooldown texts
