### ISSUE TITLE
More options for status trigger

### ISSUE THREAD

**Issue by Dooez** [WeakAuras/WeakAuras2#922]
More options for status trigger type, for example
-player in group
-player in instance
-instance difficulty

At the moment these options are availiable as load conditions, but having them as trigger options seems appropriate

**Comment by InfusOnWoW** [comment]
For what?

**Comment by Dooez** [comment]
Guildmate of mine wanted conditions to work differently based on being in raid instance without using two separate auras. Not incredibly needed but would be somewhat useful

**Comment by InfusOnWoW** [comment]
Can you give a bit more context? Adding it wouldn't be too complicated and but adding features always adds a bit of costs of ongoing maintenance, so you have to convince us that it is indeed useful for more than just one person.

**Comment by Dooez** [comment]
Some abilities are used more in raids, but tracking them in other situations is still desired. Having instance type or group type trigger would allow changes in behaviour of auras tracking these abilities without cluttering list of auras. Difficulty check could do the same for auras tracking boss abilities. 
I cannot evaluate overall usefulness of these triggers, but i applications i've named are indeed rather niche

**Comment by InfusOnWoW** [comment]
So basically that's e.g. showing a glow if in a raid, but showing the aura plainly outside a raid?

**Comment by Dooez** [comment]
Yes that's what i've meant

**Comment by InfusOnWoW** [comment]
That doesn't sound that useful, on the other hand we already have Status/Conditions that contains a random collection of stuff that's probably as rarely used. At least InGroup vs Not in Group sounds useful enough for me.

**Comment by emptyrivers** [comment]
Yeah, this is in the same category of #386 imo.
