### ISSUE TITLE
/wa help

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#925]
Buds mentioned this in passing, and I don’t want this to be forgotten.

Basically, we should add a help option to the WeakAuras slash command, which prints out all the subcommands which are available to them.

e.g.
```
> /wa help
Usage:
/wa help - show this message
/wa pstart - begin a fresh profile
/wa pstop - finish profiling
/wa pprint - bring up a window with the results from the most recent profile
```

**Comment by Stanzilla** [comment]
👍
