### ISSUE TITLE
status - talented selected causes lua error upon expanding it w/o picking talent

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#928]
**Describe the bug**
status - talented selected causes lua error upon expanding it w/o picking talent

**Do you have an error log of what happened?**
`3x WeakAuras\GenericTrigger.lua:156: bad argument #1 to 'pairs' (table expected, got nil)`

**To Reproduce**
1. go to status -> talent selected
2. hit talent selected checkbox twice without picking a talent

**Which version of WeakAuras are you using?**
2.9.0

**Comment by InfusOnWoW** [comment]
Thanks, fixed for the next release.
