### ISSUE TITLE
[Use-Case] Healthstone

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#929]
**What spell item is this about**
Warlock Healthstones primarily, general items in the bag secondarily.

**What are the expected features, what is missing/broken?**
I'd expect it to be an icon that shows the cooldown of the current charge, the text saying how many charges are left.

The current problem is the text, in a pre- https://github.com/WeakAuras/WeakAuras2/pull/913 world we have to use custom code to get the item count and do update it on trigger update, it looks like our item count trigger is missing an event when healthstone charges change.

**Aura in Question**

```!nxvuVnUnm4FndOfydOjPz9Uh2aAttUMdPjDvUh2Ernk202AvrkqsoT5EW)2hPKDIBU11(4GdCKPOPi)4h)mVhpHZK85dh8PloFiN54SRHTC2AolJ(H7wOmpZxXzE4fFVjgTNj)oWN3RpNjQ8Lg7InEPr7qF9CwALZBwNG(Yz5v6uARtoT(R1lJxktQqvVm1uP91l)T6LFb8t9W6rKHtgoSx)FUEPwQW7EBfCA9sJTE5zhcGf8vw9(i0C9vqJ57Uf55oWZNFgMB6um3UZi1yMmA88KX33n7EytMWdCgSfihePT1aZ5fwFSyYLAPRmUgxgTIRRCaHkJmkJTfA6tqdND7oRuKvV8eCFWMkCWPC2taS5s3gi1FVaph6vCGk)OKldCcS2O0Ave2Jhqcc2HF9d3heUFoD330vAc0vlsswC79t)Ynutv7bRwO(gyDyPXN)5o55eLOaB1lEiz205J5SsqwuI42GZBI4yTyLcY4xXzkJiWdWI(XnGFLW7vHmKmOr8Z2(WwOuMQGhKhzGEmvjCb4DDLYlBbsct(rJe)6iJeZ69bdzkwOx1uNJW6ui1Rd93PZztVECevt2TbB8RQ8EJEbM(kXUoS73OfIroxwePccTCn1h1DPlSmQ1HgF0hIVdWxjdb54JAJgO3DnMsFCV3ta)y(73x6VluzHcmArOiaBSNLz(Yifi3kwdmpEIcY9d8MdJ(b86dCoV0zKm8oC2pL2erCPRdYFmP87gZ64OCL3SVT2HzkXr(BaHYxIt1iaeD4vddZgpbbpHAtzSsIQctO6lw7Sr3pE8CQ)AuzMN1K2qNJOIoJPL3CXF9hR79NQVrZviLXb7ve)xPzERSOaDlInj7neuBr1U545JIUdjKKgucIz0512M5mmz1OxnYQKtsDQQkdgvkSfODYByvvEESqUz8S7M8WSwgbsl9viA6QwfK4yOJYx4ShhDjl5rwYL33msxr6AxTxiK0IRxguJPzK8CwP55fy(4c)FjQtUfoe27SqiSS7gpBwtA2wFxfMVvQPzTfHUvTLAObNfRCg7QBnzb3d5cBdoqIqflckSZAw9OzdGGds4y)(Vfd3buL4(i)7Dq6398pk97IpVo3EJ6Vj(JAit1lVZAkSGZHQjeYEAmMfGgSY0gO942(RBGV23qB4s1ZIDVtV9i85)imbzJmP7VdFTMAUc9U4xe3cjXieaieFdYW6mz7hlJK70si9PUyp6jBRavrXXioZOBXdYQQcAKgslf6c4qyI7fEAY5d73R)VE2NoR)Gl(mEXZ)LHdO4(w7m4n3PvjAJLiq(DTFjX3H08JvqVUvaHw7Z9Z(FtU7piBfg28Y0N2DDlvAfT)wmaN3NIb)F(d```

**Comment by mrbuds** [comment]
it's missing the event "BAG_UPDATE_COOLDOWN" and you can use %p to get the number of items

**Comment by Stanzilla** [comment]
> So, is the discussion here, how could this be done most efficiently in the current system? (i.e. before text replacements of other triggers comes in)

nah I think we can take that as a pre-existing condition, I think we're going to merge it soon?

**Comment by Stanzilla** [comment]
That's great, I feel like we should add a variation of it to the templates then. Yes/No?

**Comment by Stanzilla** [comment]
I'd probably skip
>Inscriptions buffs
>Flasks, raid flasks
>Feasts, Foods

for now

**Comment by Stanzilla** [comment]
```
!vB1BVjUny8pntQvA7uakR3EXMeqPx5en0Htp17ngmjojEnyZSDGY9I8zFpp2jLaTv90EX0obkj2(5))5NFODOruIGg2V3hV8I(uIHsUIVLswtjj4F40Sc1o6k)7PCzMnNg2jGsIlnw16i(twkjTugBfk5zNx95QL(FfQywr1YyvP0wT83Rw(jUDILVEeUXz973P7pxTukkGNwDj)8QLkD1YGdcqZTLA5ZsO(3N5sWY2pln1WT0qWqyY4CL(oLqcwYOXHrJNdwNsvKO2jj7eB40HTn373KWSCkPS(DdPJtY4OJkIvsKJsdh95rQcL2TV0Y1swXx4Ad4R0WUGYFKZ3mWSHhBNZGiashtkwJFlXONXY0w8d7EWoisLeEMuQDeSWVPHdAmXqbZFnti)(PovifM8VB6TO5iIFC)v1u0Kw9UyeKxD)76E2Z98c8jYy5Q58mGhJNouNqSCHjNbXUhALoQ1A5kRR0WrL)ZFQ7hm1Be)(A0rxQctQ3UxlyjvlpdSvUoMz4NFK6BB)boPf4KwWjsZt9xBBSUT5fP1LpdUpAw9UBfgXQcxTJB9rLztcdhpFXWzrrZUD(KpDtutz4leo6brUqYS7JMojCmLOvwOWZ35eod3XZ7dVgVeX34Gp0fCcWX(xf238JxqF17f0No(6)tI5a55CrwoqrVlOKcfZbkcydl2WTRywR3A1SyoCG1FKKVL7WmWfB55I4c(9It2axIihO8wxwyfo(bjexWmMxSRbnQt2067FVwZ)7sUmEp4gFOlaJBvXBBqP(yq3GapD(yYQsRvjNbeuW2xFayqpk5GwHCh5PwXKeUHzr4cVx6Ga8IXbts(oQPyLwiqpBJTg9a9qLmvK5)2QfzzGXEaxXVrtyoJl5ArmjxTBMdxUUshYNLaCsPuaczd4kalWkiYl9kv553rWWdWIushWPpsOed8EqXo2EJRfYjJ708uXtuc5UXtN6ffBLrPxDRkXHk0qiPm1r4IrdirlirdMh5sSfftsmhQjeWDFHS1owLW76JQT3r1xcvT8oTktdPcOZdVUeA6EMZq8wtmNScuPplCZ4P3D99tDkr2kY92oO9asYbYpvfOb7U3T(IW3W1FLyKqgxuMWhLZ0zGpoeR3stBBhZKdGHf2YFzM8OC3R5LhLqpnOEucULPmKjFSUxRvkX7DKG3jpwBsyMOA5ipphxY1kx6K5c1goyiqxb5ponT46yteM)YnVegcysOfK5we5jZfJR7CCquxRbn4JdKrZhpoeoOytodjY192gd7Bk1A3hnt1GqExjmmavnXnDcgCh6zKatO50fraZuDdNvyZHPKWHiCt7jaibaabg0anbOEHz9ADNibhderercBdaxIIAs(nx(1)CDNhk(co3eIf5H7oa63mOglUbx45zLSipI6VEEghBnWrIWE0yiX584hBxoJg4wgC5fErcrjBATWDlkBITX5mzg)Gy8N5wD9f972P7VgaiN9U83GF00FPFpSP5ToP3BEsdi4gnwwy33GyAB1h(spOBBpa7zE22d()JT37hxB3EO)OPxyOsN4UZgoBlW8fDr(P)Zd
```

Stack count text does not display, I checked and the API does return the correct number

**Comment by InfusOnWoW** [comment]
That's because the item trigger somehow exports the stack count via %p. I have actually no clue why that is, but that would be a separate issue.
