### ISSUE TITLE
nil passed into ScanEvents in GenericTrigger

### ISSUE THREAD

**Issue by bubchi89** [WeakAuras/WeakAuras2#93]
This popped up using 2.2.1.0:
```
Message: [string "return function (event, timestamp, message,..."]:3: bad argument #1 to 'pairs' (table expected, got nil)
Time: 08/13/16 20:44:04
Count: 2
Stack: [C]: ?
[C]: in function `pairs'
[string "return function (event, timestamp, message,..."]:3: in function `table_contains'
[string "return function (event, timestamp, message,..."]:12: in function `is_in_player_table'
[string "return function (event, timestamp, message,..."]:27: in function `triggerFunc'
Interface\AddOns\WeakAuras\GenericTrigger.lua:494: in function `ScanEvents'
Interface\AddOns\WeakAuras\GenericTrigger.lua:548: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:539>

Locals:
```

Didn't look at the code but seems unlikely that it's related to any of my custom weak auras

**Comment by InfusOnWoW** [comment]
That's a bug in one of your custom trigger functions, search for is_in_player_table in your auras.

**Comment by bubchi89** [comment]
Okay I see now why the stacktrace looks like that. But I don't see any trigger with "is_in_player_table" in any of my auras (there are quite a few that just use the standard triggers instead of custom code, but I grepped this repo for that string and didn't see it either).

There's a separate bug where a "Dynamic Group" keeps reappearing on login. It doesn't appear to contain any auras itself, but I'm wondering if it somehow contains the code that's causing my problem? Is there any way for me to export my entire set of weakauras? Or, rather, where are they saved locally?

**Comment by InfusOnWoW** [comment]
The addon settings are in the WTF folder, look for a WeakAuras.lua file. WeakAuras doesn't automatically create groups. I suspect a separate addon doing that, try disabling all other addons.

**Comment by rnyberg** [comment]
One addon that makes an empty group is Details. The group was named Raidassist or something similar. 

That error message sounds like a particular legendary ring string from Wago.

**Comment by bubchi89** [comment]
Ah man, I forgot the triggers view only shows one trigger at a time now. I knew there was more code to that weakaura. Right on the money on both counts. Thank you!

I should've rewritten this thing a long time ago...
