### ISSUE TITLE
The Use-Case Series

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#930]
I'd like to start what I call, The Use-Case Series(TM) where we all take a look at a common use-case of WeakAuras and try to come up with ideas and ways on how to improve it, may it be adding a common function to our helpers, adding a feature or just coming up with a better custom code for it.

The goal is to take our snippets section and Discord resources one step further and try to come up with an ideal way of writing certain auras that are commonly used in our community to be eventually included in the templates section. There is a lot of bad code on wago and I think we can help here.

My first Use-Case issue is https://github.com/WeakAuras/WeakAuras2/issues/929

All issues in the news case series can be found at https://github.com/WeakAuras/WeakAuras2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%F0%9F%91%91+Use+Case+Series%22.

**Comment by InfusOnWoW** [comment]
Other things mentioned in todays discussion:
Class coloring
Attaching to unit frames/nameplates

**Comment by mrbuds** [comment]
On the use case series, i'd like stronger power trigger and power bar templates with
- static mark(s) at x energy/rage/...
- energy gain overlay (for SP, MK ...)

**Comment by emptyrivers** [comment]
This is probably better done as a project, so I [made one](https://github.com/WeakAuras/WeakAuras2/projects/5).

**Comment by emptyrivers** [comment]
I've gone through the #snippets channel, and added a card for every snippet. Many of them have already been done, or already have associated issues, but what I would like to do is have the `open` category be the entry point for this kind of thing, and then if it warrants discussion, convert the card to a ticket. Then, we can talk about it - whether or not to do it, how much work would be required, if it's already done, etc.

**Comment by InfusOnWoW** [comment]
We do have all of these tracked in projects.
