### ISSUE TITLE
Condition: All triggers active, play sound - only works once

### ISSUE THREAD

**Issue by blake8705** [WeakAuras/WeakAuras2#939]
**Describe the bug**
Every time my 3 triggers activate, and icon should pop up glowing w/ a sound playing. It works the first time, but afterwards the sound will not play. The icon and glow still activate though.

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Which version of WeakAuras are you using?**
2.9

**Was it working in a previous version? If yes, which was the last good one?**
Yes, 2.8.1

**Additional context**

This is the aura causing issues:

!nAvBVjooq4FnN0DFOvLu6YHoDReLs3YkAaHP7QtxxdojMGVAS5SDGY(b(TFZyhEjuApKQOotMmZZ8mJNzO1OJOebnU21rrnBqjwkj6YMxEfLmNsYW)G3Nl1RO3sjo(RUA3RvoI4NC4BIOKuTwMPxPgbVQJILi5zOMR7pDQL7O33Or9RUPrTBIUoQwZ63erNEr9BOeMkDM2mqluokPDN4rDgc2QW60Zrl90ImMJtjfL)NL6eALfXI1Xmo8qMEShxjGmDHcWAxLJBMYs5p3klRVY(835SxAvyy2NFKNjyptq9SpFlZnNPguay4sDEU3ubtKqb4iuc0bWPPWr7m)z4jNrKNZnikI90wPapyaVGqKsQbO2YhxGgbiIf6vCJB9cGUQhEZEjWRZ4jftNocFI8qNEdU)PEGD9pcbQRWwAbkPE5PX6fCWxAq0N)ZdSiAn8bd)Fleg(auM3Ua)WxYrEEqWsOwSeR2K8OoZJcBrIxfcGfXRuY42TiJgtg1Ais4l4sz3mBGskuLgJv407)YbgU)ljd60dIamOiZ0R6deI1))wqgCjevk2CEjds6OGpvppywGUilKS1ac9pVNCrYpo6ichTABPwbglzlJXGKq0wBbLj5Cxq4Ho9lmJrd1uU3f8ZzU0zC7PXFz0)aNjDZQgohyz4crFLC9BYWTg(OpdFeNcjeqsQyQinu4KGxSMNiuCFkYJHhe5aQcQhdU9)nX9UjHtXVxFe)A4W9)p9w6ByXcxH54GSkL)(q)9RlQMpp3q8OSXP56tNLpjPxnV8Hfcab1F)nXQvcBjjOQfAkTKjfzBMqqBVzs3789sQuWA5db6(2tLyizc7)aDQcoLjL7AtguRNoxKcDQ8QOv)A5x)BB(6MjBMy4aouBMuk9VR9JntyQS9cIowW1)4p28vo2nL59zPB85Y4lQDLh84yGdA2)cNVOfYLUHytqprYLtpQ7Eg3cn0my)8KWiL2AP2eOm8Vi)Vx7)To(7wxDKHqzr4uO7LSCObz)Ng1RBChkzghQZGA5gW0lPM5hDTnn7hFXKy5c29qOYL4eSMqwUq6eEu00NcC(YG0kQTxl)7tLmRFyufPORWsFMVXVfhrEKkGsVwoymU2NU6GbQqZWxxy4w7k2AFohBf2nfgO4Nm)7nkd72GUmHAUVSVBmP7DDcCzOOFG4vUS0SNb7ciEFEi5a4CmZA45qXvWhcevb0uMyUT)Or9FCy3V8WODW8SYSrhSlXULcU3a3KcUI0EyNoXL6EqbNhNuYVylrdi6NAyqsCjLg5hx6NqH1Ior6lRVB7eAqIiB3Wh7MjG2trFcT)yoMpBZKlMfoTsKbDw8LuPNbHIw(7Z7fB(R2lEP73WLjwcRmW3YUrVnzZuI5bKD42nHgekOH4(LlgxUyahIzOhLVdLqD(AVBDMZtFFNCvMy7QxHLEGoIPVC4WI4lacCjZiW0dL0k(UsLE7IsiHUxtSFk(SSGhOVQd5JJ(yLRmXcE6JuoemZyQC(EufEpUJMb3PYTUCr3Taj8(rLRxwspdKyo7ulCQRSWPFxl)XkREA1kMjS0zWQiOu4D2hzwxy3N9Wj4g32aqGUtXKFdQOW6L4M7UQ)2UcWPLqGwpcJF6)n

**Comment by InfusOnWoW** [comment]
This is fixed for the next release. Thanks.
