### ISSUE TITLE
Export -> Import breaks strings

### ISSUE THREAD

**Issue by rnyberg** [WeakAuras/WeakAuras2#94]
I have multiple strings that users are reporting throwing out errors. They work on my PC, unless I export the string and re-import it.

First string loses every % character from: 

- Display tab Text input box (says only `c` now).
- Custom Trigger 1 code
- Custom Trigger 2 code
- Actions onInit code

Code DIFF screenshot: http://i.imgur.com/QDceLwV.png

Second string suddenly gains a lot of apostrophes in places that there shouldn't be any, another DIFF screenshot: http://i.imgur.com/iTX2sjL.png

**Comment by rnyberg** [comment]
Here's a one of those groups, requires lvl 100 Vengeance DH http://pastebin.com/KWZ3ePn6

**Comment by InfusOnWoW** [comment]
Please attach your WeakAuras.lua that reproduces the problem.

**Comment by Stanzilla** [comment]
Info: we're currently suspecting a problem in LibCompress

**Comment by rnyberg** [comment]
How to reproduce with my WeakAuras.lua using Havoc specced Demon Hunter at lvl 100: 

https://www.dropbox.com/s/rfoeak449ypppyn/2016-08-18_10-35-38.mp4?dl=0
http://redlan.co/WeakAurasOptions.lua
http://redlan.co/WeakAuras.lua

You can probably reproduce this on any other class too. Easiest way to see that it's broken down after import is that the group name has changed from "Redfella's..." to "Redfellas" and in the custom code apostrophes and percentage signs are gone mental.

**Comment by InfusOnWoW** [comment]
So, I'm traveling at the moment, but from your description you can reproduce that even over multiple restarts of the WoW client, right?

**Comment by Stanzilla** [comment]
with the WA I posted on the wowace ticket (https://www.wowace.com/addons/weakauras-2/tickets/573-exports-convert-all-logical-into-assignments/) I can reproduce it every time.
It's not only happening for `'` it's also `>` and possibly other special chars.

**Comment by rnyberg** [comment]
Restarts and reload UI do not resolve the erroneous state, only modifying the group does -- and a minor modification may break it again once the string has reached a state where it's developed this behaviour.

What I find strange is that I've ever only had this happen to a single string at a time, but this time it started to affect all 4 of my Rotation Helpers during the course of one day, I did update WA to a newer version but I also did minor modifications to all of them (not same edits, though).

**Comment by Stanzilla** [comment]
Infus found the issue and we are now in talks with the owner of the compress library we are using since it looks like the bug is in there, will keep you updated.

**Comment by rnyberg** [comment]
Awesome!

**Comment by rnyberg** [comment]
Any update?

Would love to start releasing updates to the strings I have, that are affected by the bug.

**Comment by Stanzilla** [comment]
We're still in talks with the library guy, not sure how long it will take, might fork it and ship with our own version until it gets fixed.

**Comment by rnyberg** [comment]
I guess the biggest quoestion for me is: should I start export/import testing to get functional auras out prior to Legion launch, or do you think the issue will be resolved before or during monday at latest?

**Comment by InfusOnWoW** [comment]
It's likely that we'll test a patched libCompress in that time frame, since the guy understands the problem and promised a patch soon.  But whether that'll fix the issues, I wouldn't guess. If I had time, I would just fix the bug myself.

**Comment by InfusOnWoW** [comment]
The author of libCompress just provided as with a patch, which Stanzilla and I both confirmed to work in our test cases. He'll release a new version of libCompress now and this bug should be fixed soonish.

**Comment by rnyberg** [comment]
I just exported all of my strings, and upon re-importing none of them were broken.
