### ISSUE TITLE
% have disappeared

### ISSUE THREAD

**Issue by Kachicho** [WeakAuras/WeakAuras2#942]
**Describe the bug**
 % aren't showing

**Do you have an error log of what happened?**
 

**To Reproduce**
 

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

``` HERE ```

**Comment by mrbuds** [comment]
since 2.9 you need to double it %%

**Comment by emptyrivers** [comment]
You really do need to answer the questions we provide, buddy. They're not there for decoration.

And buds is correct.
