### ISSUE TITLE
Collapsible Option Groups

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#944]
**Is your feature request related to a problem? Please describe.**

There's often dozens of controls in each tab of WeakAurasOptions. This can quickly overwhelm new users and slow down experienced users. It would be great if I could temporarily hide the options which I'm not interested in right now.

**Describe the solution you'd like**

There should be buttons on each "group" of options which, when clicked, toggle that group between being expanded (all options shown), and collapsed (only the header, and the button to expand the group is shown).

**Describe alternatives you've considered**

The only alternative I can think of is to start nesting option groups using AceConfig's own option group system. But this has its own problems, like being very unwieldy to write and use unless inline groups are used, and inline groups have the problem that they consume some of the available width. We already have issues with width playing havoc with the layout of our controls, so I don't think it's a good idea to invite yet more troublemakers, so to speak.

**Additional context**

#694 does this for custom options while in author-mode, and extending that to all of the options interface would be a solution to the root cause of #915 (and a better fix than #943). However, the scope of this is too large to be done in a bug-fix release, so I am writing this ticket instead and intend to work on this for 2.11, if not 2.10.

**Comment by InfusOnWoW** [comment]
https://github.com/emptyrivers/WeakAuras2/tree/collapse

**Comment by InfusOnWoW** [comment]
This is part of the next release.

**Comment by emptyrivers** [comment]
Actually it’s already been released.
