### ISSUE TITLE
Ability to trim sound length

### ISSUE THREAD

**Issue by Theunwow** [WeakAuras/WeakAuras2#945]
**Is your feature request related to a problem? Please describe.**
I use sounds in my weak auras quite often, especially when helping me learn to look at new ones, however I always find myself using the same short sound files that come with Weak Auras because I do not know how to create my own. It would be amazing if you could trim the length of the sound files that are 'standard' so some of the longer sound files could easily become short and less intrusive.
**Describe the solution you'd like**
Some way of trimming the length of the sound so, for example, the "Rain" sound would only play for 0.5 seconds instead of its full 2-3 second duration. 
**Describe alternatives you've considered**

**Additional context**
I do not know if this is actually possible, I'm not entirely sure how sound files work, but it would be fantastic if it were to be a feature later on.

**Comment by emptyrivers** [comment]
We’ve decided not to implement this. You can implement it via a Run Custom Code action using the following code:
```lua
local timeLimit = 5
local soundFile = [[path/to/file]]
local _, soundHandle = PlaySoundFile(soundFile)
C_Timer.After(timeLimit, function() StopSound(soundHandle) end)
```
