### ISSUE TITLE
%debuffType would be a nice addition once infinite texts is a thing

### ISSUE THREAD

**Issue by Causese** [WeakAuras/WeakAuras2#946]
**Is your feature request related to a problem? Please describe.**
There's no performance-friendly way to return debufftype once Aura - Buff/Debuff is applied to you.
I wanted to return an icon based on debuffType once infinite text feature is implemented.
example:
![Test](https://gyazo.com/6d503cca1f3da6dbc94c62f4ee04d71b.png)

**Describe the solution you'd like**
Simply a variable/state for %debuffType for Aura trigger

**Additional context**
I could iterate on trigger update but that's not efficient since the job was already done by the trigger itself

**Comment by emptyrivers** [comment]
Why do we specifically need to wait until you can make new text fields?

**Comment by Causese** [comment]
No need to wait, I just need 3 texts before adding it to raidweakauras (regular name, %s and debuffType)

**Comment by InfusOnWoW** [comment]
%debuffClass exists now for the next release.

I guess we should add those textures to our default selection too. Do you have the paths for those?

**Comment by Causese** [comment]
kirin did all the digging

aura_env.EJ_Icons = {
    tank = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:0:32:0:32|t",
    dps = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:32:64:0:32|t",
    healer = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:64:96:0:32|t",
    mythic = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:96:128:0:32|t",
    deadly = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:128:160:0:32|t",
    important = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:160:192:0:32|t",
    interrupt = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:192:224:0:32|t",
    magic = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:224:256:0:32|t",
    curse = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:0:32:32:64|t",
    poison = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:32:64:32:64|t",
    disease = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:64:96:32:64|t",
    enrage = "|TInterface\\EncounterJournal\\UI-EJ-Icons:0:0:0:0:256:64:96:128:32:64|t"

**Comment by InfusOnWoW** [comment]
Ah they are just using one texture with texture coords. That's not easy to add to the texture selection, I guess I'll revist that when I work on a texture subregion sometime in a year or so :)

**Comment by Causese** [comment]
any chance for making it possible to return the texture based on which debuffType is selected?
![](https://i.gyazo.com/1a715d3b9158cec9ce57973e1f185ee2.png)

so that it's not necessary to make an array for each aura etc

something like %debuffTypeIcon maybe 🤔
