### ISSUE TITLE
The ablity to Auto-clone an item for each target in the fight

### ISSUE THREAD

**Issue by Phylo** [WeakAuras/WeakAuras2#949]
**Is your feature request related to a problem? Please describe.**
I can auto clone to track dots on targets.  It would be nice if we could auto clone to track all targets to help know the missing dots

**Describe the solution you'd like**
A easy trigger that lets you clone for every target in combat with you

**Describe alternatives you've considered**
I tried doing it with Multi Unit - is debuffed - but i think in a WQ it also caught the friendly members as there was no way to distinguish enemies from friends.
I was also thinking of doing it off any threat value against me, but it doesn't have Auto Clone.

**Additional context**
https://cdn.discordapp.com/attachments/218084462523711489/511440811804590103/unknown.png
in this screen shot i put in discord.  the orange and blue bars are Shadow Word Pain and Vampiric Touch.  the Black bars behind are what i want to Auto Clone per target (there were 4 targets dummies in this fight)

when i did a World quest boss in a raid, there were like 30 black bars and 2 targets.

**Comment by InfusOnWoW** [comment]
I fixed Buds aura, though to really use it you need to only show enemy units, or wait until https://github.com/WeakAuras/WeakAuras2/issues/883 is implemented.

**Comment by InfusOnWoW** [comment]
No, On Threat Table doesn't give us enough and accurate information.
