### ISSUE TITLE
Error with bufftrigger2

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#954]
Import this group (or any of the children from it): 
https://wago.io/SkagDsipm and then reload the game. 

You should get a printout to the chat window: `[string "--[[ Error in 'Last Stand - Duration' ]] return Trigger 1"]:1: '<eof>' expected near '1'`

Does not appear to impair the behavior of the aura in any way, however.

Reported on discord

**Comment by InfusOnWoW** [comment]
This turned out to be the custom trigger logic combiner function, which was loaded even though it wasn't needed.

Fixed for the next release.
