### ISSUE TITLE
Conditions are getting unwieldy

### ISSUE THREAD

**Issue by emptyrivers** [WeakAuras/WeakAuras2#957]
With just one trigger, we have this dropdown for conditions:

![condition](https://i.imgur.com/Z5sC3ya.png)

And this is what property changes on an icon looks like right now:

![property](https://i.imgur.com/aVvi7bm.png)

I see no reason to suspect that the number of features will ever *decrease*, and there's lots of potential to add more features to Conditions. This leaves us with a UI problem in our menus.

How to solve this?

One option would be to have just one item for each subregion, which when selected spawns all of the options you would see in the display tab for that option. So if you select the glow subregion in the property change dropdown, you'd see the glow visibility, glow type etc options all appear, and you would be expected to configure the glow via those options.

Another option would be to have nested menus, either by having the dropdown menu spawn secondary, tertiary etc menus on certain items, or by having your selection in the primary menu (for, say, the glow subregion) produce a new dropdown which has the Glow Color, Glow Type, Set Glow Visibility, and Use Custom Glow Color menu items which exist in the current menu.

There are probably other options which haven't yet been discussed, but this topic has been brewing for long enough that we should probably have a ticket for it.

**Comment by emptyrivers** [comment]
Also, the same questions about subregions apply to the triggers in the condition dropdown. Nested menus? Secondary dropdown widgets in Ace? Spawn the trigger options? Other?

**Comment by Dooez** [comment]
Considering conditions UI i would also suggest collapse/expand buttons similar to author options

**Comment by emptyrivers** [comment]
Well, that's kind of the idea of #944.

**Comment by Stanzilla** [comment]
I really dislike how some of our on/off Conditions look at the moment 

![image](https://user-images.githubusercontent.com/75278/52356904-6ce39c00-2a35-11e9-8071-dc04606408fa.png)

That lonely checkbox really needs some label.

I could not find where I proposed it first, it might have been just on Discord, but I really think we should move to a cluster of options for things that can be clustered like glow, offsets, cooldown like we already do on the `Display` tab 

![image](https://user-images.githubusercontent.com/75278/52357188-f7c49680-2a35-11e9-9b7e-2684a3128d51.png)


This would end up looking something like this: 

![wow_2019-02-06_17-35-49_edit](https://user-images.githubusercontent.com/75278/52357347-4bcf7b00-2a36-11e9-8fd4-d452edd24a57.jpg)

**Comment by emptyrivers** [comment]
This has been improved in the latest beta.

**Comment by InfusOnWoW** [comment]
Argueably enough that this can be cloesd.

**Comment by Stanzilla** [comment]
Well not quite, I'd still love to see all options of the Glow cluster to be visible at the same time, any arguments against that?

**Comment by InfusOnWoW** [comment]
That has nothing to do with the original ticket. And we have discussed it, and I still don't think it's a good idea. The most common usage of glowing is to configure a glow in the display options and then toggle it on/off via conditions.

**Comment by jjholleman** [comment]
I'm experiencing this bug again since 3 days ago. I'm using WeakAuras version 2.12.4.2  
  
![image](https://user-images.githubusercontent.com/6916881/59969479-ea73f880-954d-11e9-8ea5-677cc0c9049e.png)
