### ISSUE TITLE
[BuffTrigger2] Aura with Load on Combat doesn't show

### ISSUE THREAD

**Issue by Wizeowel** [WeakAuras/WeakAuras2#963]
**Describe the bug**
I have a multitarget aura for SW:Pain which should show number of units affects. On the load tab, I have selected to load in Combat and not in a Pet Battle. If I enter combat by casting SW:Pain then the first aura is not loaded. Subsequent casts work well.

**Do you have an error log of what happened?**
There's no console error.

**To Reproduce**
Make a new icon aura for Shadow Word: Pain, aura type multitarget, %unitCount in display, load only in combat
Enter combat with any other spell. 
Cast SW:Pain, confirm that the aura shows 1 unit affected
Exit combat
Now enter combat by casting SW:Pain, confirm aura-icon isn't shown.

**Screenshots**
No but could make video if needed.

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No but can do that if you guys can't reproduce.

**Which version of WeakAuras are you using?**
2.9.1-16-gdcb382a (2018-11-17)

**Was it working in a previous version? If yes, which was the last good one?**
Not sure, just started using BuffTriggers2, this is my first multitarget that I'm actively using.

**Additional context**

!DwvxVPooq0Fn7JTIe(QSVbCd3ls0acNUxTV4wtIjXcJDuSdu6d93(oJDsdTlsB1kvL6mmZXZhN5eAanHse04W(Jcdgrjgkj8(j3hCxWO7YZs31)HqgLCKsYW)aFT8xTHB0cLLsMTojz9JRIw0ypyHwzjI3404juYRR3V3WT04HdOKlTV0JsyQ0cDvdgZJItI2sjPATmtFwrolk50zGHAJvFmbG9PYmMLtj1n)V11OSCoDhGxQvOvgm7mwwLfoaaVxOeMc)z4O3kC2wjYZ5vO7XUQVXaEKvxXuSJ8MFKqkyWf9(l)wxL9NV)YgMqbTkkztDvo)9xSfWJFlspWZqKHuATsEbtEt9o(jUYUPIVx8ka0MOvRGkaYJOxfgRbZ7Ad)zlulwrj(AgFx9(9jxGYN8RPBFCXtqeMc955sTcsjawR7hXSm0hUpM5sMXHy71saJ41(88PKKNjjt3cfN7xaO5mPTGsWaja6Rv(BzQ8m7cm(nLCPCzMX35()3nG0lgc2nk1h3ju8hz20cUXFDR0N5gWTJEJ3ktWUf4qn0GCaQ6MuUjjo3pXt8gFuNXXS02qfJuSDsitGR)aNxofkRu7wgWuCnkUC)xiGglK6x(b0Br2KFGyyw8DhllxctcTux57g4FHUN9DphC9L3aDY6nBx(ZF1U1GBhlKSCO0w)uYQLXrusbxKxaRf9H(yMWukzxwMcxFCaSq2BmLi1m3EhoTl52DmRv6YhltIZtK0lu5sS4h12TsCVmZ3MWipXleP(4WgXNIQlOpCp1rOM5FXrioOa29vwsDZvNBDyrGYnIKClabgaZ62m6qloS3GGjJXWbjJVeMfPn)NDBwTfKswx2ka4IsTxK7p7A7ZH2oqvp6y)lJjl)rKFA6x12vBTA16t8kO3FLogie2Rx47VmdeBUAa(zZEPSfvar3Jgz(2OO4RG5Rd8kEoKRENf4K2d9v01MKUR271v7lgoz0KbJhhmSFWaGFes3F3W(FM9f(jvyGiYRum5FbsEiVgTHfVJcHjjLmQtsfLBVkvEtRp6KSD4sj)bUsoxxR8TEn6dtwwWC0ir2T1i83Z3y3zp2hb9yM1d4zrgOu52nasu3ciQDIxw)Fw93tKV92WdhXcfgHghf31xXutjo63MV6tdKSMv8N9QPgo4ni31iUQaTwQtxsO((E)XhB(E(7PPzIwAR)drGoy6b8WjMSM767NyvcCA4fg7(wLVFLwWu58oa8X1qAUVFyWWrpmkC8GH9M8GRJ)Vn2)wgBNhLv6sEL9s7QOTBZ0txAPRb3AhdoDcaAqiIf9F(d

**Comment by InfusOnWoW** [comment]
That's to be expected. The Multi target trigger depends on the combat log events to detect auras. All events that are before you are actually in combat are ignored and that's what is happening in this case.

**Comment by Wizeowel** [comment]
Thanks for your response.

The strange thing is that a similar multi-target aura for Warlock Agony does show, as if the damage ticks are causing the aura trigger to re-evaluate. However, that was the only dot debuff I could find which does fix itself. 

Warlock Corruption has the same issue as Priest SWP, but interestingly when talented for Absolute Corruption, it never matches a multi-target debuff aura. I checked and it's still the same spell ID, so perhaps because Absolute Corruption doesn't have a duration.
