### ISSUE TITLE
Pixel Glow for progress bars

### ISSUE THREAD

**Issue by Freeb0rn** [WeakAuras/WeakAuras2#970]
**Is your feature request related to a problem? Please describe.**
It's would be good, pixel glow on progress bars will be usefull on many auras collections

**Describe the solution you'd like**
Pixel glow on progress bars by ingame settings without using custom code by users.

**Describe alternatives you've considered**
Maybe some other glows, that would be good for progress bars? Dunno. Maybe settings for pixel glow.

**Additional context**
![](https://media.wago.io/screenshots/HJkDQqQXQ/5ba540474db7c7594f2a0539.gif)

**Comment by emptyrivers** [comment]
Hmmm, this is something that will be solved naturally in the medium term, I think. So I don't really want to address it specifically.

**Comment by InfusOnWoW** [comment]
Yeah, I agree, it'll come eventually.

**Comment by InfusOnWoW** [comment]
That is, I wouldn't want to work on it, if someone actually does the work and puts up a PR. (That's actually not too much work.) I'd be willing to merge it.

**Comment by emptyrivers** [comment]
Sub-region infrastructure has been implemented. Submissions are now welcome!
