### ISSUE TITLE
[2.10.0-beta1] Thoughts about Custom Options

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#973]
Having played around a bit with the Custom Options now, first of all it's very cool. Having an Init that's just code without having to expect and direct the behaviour of non-coding users opening that section is a big step forward.

(I started off with these separated into "QOL" and "requests for future development" but they're all essentially "QOL requests for future development")    
Example Aura in which I've been playing with this stuff https://wago.io/BkARo1QAm

- [x] Allow Description text to use escape sequences
- [x] "Collapse All" (and, I guess, "Expand All") buttons. 
  * Even a fairly modest setup can end up with a lot of objects in the list so having them mostly collapsed becomes the only way to keep track of it all. However, after a reload they all start expanded again. Perhaps just starting collapsed would be a reasonable default if adding more buttons to the UI isn't ideal. 
- [ ] Can the buttons for entering User/Author mode be separate to the main scrolled section containing the objects?
  * This is tremendously minor but I found myself scrolling to the wrong end of the list to switch modes almost every time. I would, of course, just get used to it eventually but if both buttons were just always at the top, and didn't scroll out of view at all, then that would be pretty great. 
- [x] "Send to Top"/"Send To Bottom" buttons
  * Since all object are made at the bottom and moving things around unavoidably requires a lot of clicking, a way to quickly move things all the way could be useful. Of course, most of the time you'll be moving something to somewhere in the middle but it still might feel nicer to use if you can send it to the top then move it down a few, rather than moving it up a lot. 
- [x] "Horizontal Rule" and/or "Heading" objects. 
  * These exist in the WA UI, though I'm sure I'm not using their actual names, and would provide more options for layout. (see [image](https://imgur.com/a/taqpc1O) - heading in red, horizontal rule in blue) 
- [x] "Vertical Space"
  * I found myself Adding an empty line before my Description text to try and force some vertical space and I can imagine doing that even when I don't want any text at all, using a Description as a spacer. A workaround exists but might be nice to add something specifically for the job. (the actual "Space" object I found I mostly just used to force a new line in the UI)
- [x] A means of duplicating objects - or even better, whole sets of objects
- [ ] "Dependencies" - I would like to be able to make an object to be enabled/disabled based on the state of another object. 
  * I can't think of a use case where this is strictly necessary. In my UI I started off with toggles to enable a setting then a String object to set it, and I wanted to have the String enabled by the toggle. It worked fine with me just handling that in code (`x = toggled and setting or default`) and I ultimately just made it use the string's emptiness as the toggle. All that said, it would be nice in terms of UX to be able to have objects depend on each other.

**Comment by asakawa-k** [comment]
> Always, or do you want to control when it happens? Only WoW escape sequences? 

I was only thinking about WoW ones, mostly for colours though I can imagine people using textures and stuff sometimes too. 

> They probably can, but I'm leary of doing this [...] I don't want it to be easy for users who don't know what they're doing to be able to accidentally enter Author Mode

This was a minor request anyway. But I totally understand. It does feel like there's some potential improvement there. I'll give it more thought. 

> Send to is possible, but it seems too specific. It sounds like what you really want is the ability to insert a new options entry at an arbitrary point in the list

I completely forgot to put cuplication in the original ticket. I ended up doing a lot of the same things over and over in the Aura I was messing with.    
Sending to a specific point would be even better, yes. If the existing objects were numbered then that would probably feel quite intuitive to do actually. 

> Headers are currently used to separate options from different auras in User Mode. 

Ah, okay. Are Horizontal Rules already used too? You can probably tell from the things I've requested that I'm mostly interested in being able to portion out the settings in to discrete sections, each of which hopefully wouldn't be too overwhelming for users. The specific tools for doing that aren't super important to me.

**Comment by emptyrivers** [comment]
The horizontal rule (with an optional title) **is** the header in AceConfig.

**Comment by asakawa-k** [comment]
Ah okay 😄

**Comment by emptyrivers** [comment]
Formatting is possible once #1077 is merged.

**Comment by emptyrivers** [comment]
Duplication is possible with emptyrivers/WeakAuras2@a8798fa093ac4aa5259f5c8e61bff6636cf178bf

**Comment by emptyrivers** [comment]
Which also doubles as an ad-hoc "insert here" button. For now, I think that is good enough.

**Comment by emptyrivers** [comment]
The last of the simple requests from this ticket has been implemented. The remaining two requests are tracked in the Custom Options project anyways, so I am going to go ahead and close this (reopen if you disagree 😄).
