### ISSUE TITLE
Dynamic Group Finish Animation with wrong Icon

### ISSUE THREAD

**Issue by despia** [WeakAuras/WeakAuras2#974]
The Finish Animation displays the wrong aura.
https://wago.io/SknpVu40m
https://imgur.com/a/spOOICg

With the WA that is linked above use Rushing Jade Wind and afterwards use Ironskin Brew twice and wait for Rusing Jade Wind to expire.

WA 2.9.1

**Comment by asakawa-k** [comment]
The trigger that was true, supplying dynamic information to the icon, is no longer true when the Finish Animation plays so it reverts to whatever base icon the Aura carries. This is basically working as Finish Animations have always worked.

**Comment by despia** [comment]
Makes sense

**Comment by emptyrivers** [comment]
Long-lived or not, this isn't really ideal.

**Comment by InfusOnWoW** [comment]
This is now fixed for the next release.
