### ISSUE TITLE
"Trigger State Updater", as a name, doesn't help people select the correct option

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#975]
It amazes me how often people select "Trigger State Updater" from the list when they know they want a custom trigger but aren't experienced in the options available. I think we've discussed this a bit before but thought I'd make a ticket so it's on a list and not so easily forgotten.       
Perhaps it could be renamed to "Cloning Status Trigger" or similar so that people would be able to latch on to the idea of cloning being either something they do or do not need. 

Tbh, I would expect that people would select the clearest and simplest option if they don't know which to choose. So perhaps the fact that people very often do select TSU as actually/also an indication that "Event" and "Status" could be doing more to guide people in their choice. However, I don't have any ideas for better options in the case of those options.

**Comment by InfusOnWoW** [comment]
I don't like to rename it now. While Trigger State Updater isn't exactly a good name, there's now ample information that refers to that name, so a new name would have to be drastically better to make it worth it. And I don't hink Cloning Status Trigger has that going for it.

**Comment by asakawa-k** [comment]
Is there enough space in the UI element to add "(custom cloning)" to the name as a compromise?

**Comment by InfusOnWoW** [comment]
I added "(Advacned)" to the name, which should be a even better deterrent, though it doesn't tell the user when they should use it.

**Comment by asakawa-k** [comment]
That addresses my immediate concern, thanks.
