### ISSUE TITLE
Power bar customization above 100%

### ISSUE THREAD

**Issue by Alventenie** [WeakAuras/WeakAuras2#980]
**Is your feature request related to a problem? Please describe.**
This is mostly a quality of life request to be able to edit the power bar to be able to see above 100% power in an easier manner than custom code. This is generally related directly to brewmaster stagger bar where we can be above 100% but current in-client options only mirror the blizzard power bar to 100%.

**Describe the solution you'd like**
Ability to show the power bar in some manner above 100%. This can be either by having a second bar appear, overlap the above 100% bar on top of the normal one, or have the option to extend the current power bar to higher % (Like have the bar be a 0-200% power bar instead of 0-100% power bar)

**Describe alternatives you've considered**
I have used a custom code a while back before a bunch of api changed in 8.0 that allowed a 0-100% power bar, and above 100, would overlap the bar with a 100-200%. This worked for the time, but eventually gave errors and I was not able to fix with my limited coding knowledge.

**Additional context**
This would be primarily a quality of life for brewmaster stagger as I do not believe any other class uses over 100% power bar often enough. Realize it would be a low priority thing, but may have applications in other areas I haven't thought about.

**Comment by InfusOnWoW** [comment]
Actually, isn't that a bug? I don't play Monks, but shouldn't max progress for Stagger be whatver the limit of stagger is?

**Comment by emptyrivers** [comment]
The limit was arbitrarily set beforehand to 100% of max hp. Until 7.2.5, there was no limit to stagger (except maybe maximum double or whatever). Now, the limit is 10x your max hp.

**Comment by emptyrivers** [comment]
It would be a mistake to “fix” that now, without a feature addition and maybe a data migration to keep existing auras working as they are today.

**Comment by InfusOnWoW** [comment]
I did add a scale option for Stagger now. I think I made a mistake to include Stagger in the Power trigger. This makes the stagger power type useful.

So that's your "extend the bar to a higher %", as you can now set a scale factor of 2.

For overlapping you would still need a bit of custom code. Our discord is a pretty good place to ask for help with writting lua code, especially if you have something that almost works.
