### ISSUE TITLE
Set Maximum Progress for aurabar causes bar to fill when aura is not applied.

### ISSUE THREAD

**Issue by Hekili** [WeakAuras/WeakAuras2#981]
**Describe the bug**

With Set Maximum Progress checked (Maximum: 6), I would expect the progress bar to stay full when the aura is applied and remaining duration is > 6, then deplete from 6 to 0, and _then remain empty when the aura is not applied._

The italicized portion is not working as expected; the bar instead returns to full after the aura expires.

**Do you have an error log of what happened?**
 

There is no error.

**To Reproduce**
 

1.  Create a progress bar.
2.  Set the trigger to Aura / Pet / Buff / ID: 272790; Show On: Always.
3.  On Display tab, check Set Maximum Progress and set Maximum to 6.
4.  Cast "Barbed Shot" (as a BM Hunter) and see that the bar is full even though the buff is not up.

**Screenshots**

The red bar shows my Frenzy.

Buff Not Applied:
https://i.imgur.com/Wh0fEBT.png

Buff Depleting:
https://i.imgur.com/5k3K24Y.png

Buff Gone, Returns to Full:
https://i.imgur.com/bVj885O.png

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

No, I'm lazy.

**Which version of WeakAuras are you using?**

2.10.0-beta1

**Was it working in a previous version? If yes, which was the last good one?**

I don't recall having this issue in earlier versions, but this is a new aura so I don't know.

**Additional context**

Workaround (offered by asakawa) is to add a condition for Auras Found = False Then Inverse (check).  But I think the bar should not be full when the buff is absent.

**Comment by emptyrivers** [comment]
Fairly sure this is fixed by #978

**Comment by InfusOnWoW** [comment]
https://github.com/WeakAuras/WeakAuras2/pull/978 only affects cast bars. This seems to be a different issue.

**Comment by emptyrivers** [comment]
Should be fixed now.
