### ISSUE TITLE
Player name as UnitID does not work in making an Aura with specific unit

### ISSUE THREAD

**Issue by GreatWhiteMuffloN** [WeakAuras/WeakAuras2#982]
**What steps will reproduce the problem?**

Making an WA with the trigger of Aura > Specific Unit > [player name goes here] > type buff/debuff > Soulstone (In my example) > Show on Aura(s) Missing

**What is the expected output? What do you see instead?**

Aura does not trigger on player name, does trigger on unitID like raid3 

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Admittedly no, but confirmed bug by others in WA discord

**Which version of WeakAuras are you using?**

2.9.1

**Was it working in a previous version? If yes, which was the last good one?**

Unknown

**Do you have an error log of what happened?** 
 

No error log available

**Please provide any additional information below:**

Asked for help on WA Discord where moderator asakawa was able to confirm this issue existing and said the following; 

"I confirmed what you're seeing. Had a quick look at the code. Poked a dev who pointed out that the tooltip on Specific Unit is actually different from on the Legacy Aura Trigger and doesn't say that I does handle it. Pretty sneaky!"

**If you do not know which aura is causing issues for you, please attach a ZIP archive of your WeakAuras SavedVariables file.** 

**In case you do know which aura is problematic, please export the string and paste it below.**

``` HERE ```

**Comment by InfusOnWoW** [comment]
The tooltip turned out to be incorrect, but that aside. I currently have no plans to support names in the new aura system. Supporting that isn't impossible, but doesn't really fit into how the system works.

**Comment by emptyrivers** [comment]
As a workaround, you can use the focus unit and focus the relevant person, if your focus isn’t getting used.
