### ISSUE TITLE
Debuff icon issue

### ISSUE THREAD

**Issue by Stanzilla** [WeakAuras/WeakAuras2#985]
auras that track debuffs show their icon only after they have been applied once like https://gist.github.com/Stanzilla/cbeed240c79be28b105014a6e8718c5d

if we can use a cached version in the options, we sure can use one for the display as well?

**Comment by InfusOnWoW** [comment]
The steps to reproduce were:
* Log in with Outlaw
* Switch to Sin 

The icon shows a question mark.

This is now fixed.
