### ISSUE TITLE
conditions sometimes stop working upon player death

### ISSUE THREAD

**Issue by BaronPlucky** [WeakAuras/WeakAuras2#987]
**Describe the bug**
I have an aura within a dynamic group, with a trigger of "Cooldown Progress (Spell)" and show set to "Always." Under conditions it is set to if trigger 1 on cooldown = true, desaturate (checked), color, text color. The conditions work normally while player is alive, but if player dies while the spell is on cooldown, upon release or resurrection, the conditions sometimes stop working: the desaturation, color, and text color changes aren't active even though the spell is on CD. Once the CD expires the conditions will then work again, on the next cast, as long as player is alive. The problem doesn't happen all the time, but it does happen occasionally.

**Do you have an error log of what happened?**
No errors in bugsack+buggrabber

**To Reproduce**
Intermittent, but:
1. Aura triggered by cooldown progress (spell), show set to "always"
2. Conditions set to: trigger 1 On Cooldown = true, Desaturate (checked), Color 93,93,93, alpha 1, Text Color 235 235 235 alpha 0
3. Cast spell watched by trigger
4. Player dies while spell is on CD
5. Desaturate, color, and text color appear as the normal off-CD properties, rather than the properties specified under conditions

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Tried briefly with just WeakAuras enabled and could not reliably reproduce the issue. Unfortunately I'm too dependent on other addons such that I can't play with just the standard UI. It would take a long time to readjust.

**Which version of WeakAuras are you using?**
2.10.0 

**Was it working in a previous version? If yes, which was the last good one?**
Unknown, at some point a while back there was similar & other conditions weirdness and I ended up making a bunch of every-frame custom trigger auras that checked the conditions and ran the :SetDesaturated()  :Color() etc functions. I only just recently started changing auras back to normal WA triggers and using the conditions tab again, after seeing some conditions fixes mentioned in recent changelogs

**Additional context**
Export of most recent aura I noticed this happening intermittently with:

!nF1EpkUnq8VlvQslT94iHh7UN09halC32YcimBVBRwLftIj4sioY2bwU)Gp7Dg7ei86Uw1RsvSkBI9mJNh)Mh2ZXBShH713PMtd4Nhr5rCl7uPCfpYspsa(hqryKyT3upIM9Q2PRiwt4FHbCburt1ZfYbjAUiwb0Q9iBgmBMIP96JBh7dBpuWJHnAny84bpm6(p8rqM(cruGyDmznpH51YJKQyJH108e8l)uLwSCmCGpMeq1my)S)NZyNGqgQuu)8ZMO0uP28Iingu(7J1m5mQp75MbbdIvp)jgDrZujv98dSao9zcsN65rIPcDRiEszryiyZIxScykAoZ4XC1CRPbVAKpqHvb3RQORqsFHfVQSKfcAuzqB8xOEx7igv2mkY4euxvA7VEbcjmTHMR(HXdgA8s)WVSDYredRCW2VXfFuVeODAJpeJvTfrcj6B4OdiMg97mPcy2R)TzbXoX0PrSau9xWyjnvjmF9ik4jnU0y(s894dCQ(OuhbHDW(bLYSpPs5Qa9rjZPJ3aXrGAjLhoxNrEtd5Mx)G5vdPDtJ99iBNy)nd(cf2vjsrOKPuGfzou4)bSinfCz50I)KmDQmoJMTt(5Tt2X52j)0P8WIdSFy8pVy0a0Wv(0iMvRtsJuSm9SLrptaXbyyIAUKhVitVnqAdBV613TCDaRBw619B8300(C(lpHVGm(58xE6iZnsaRc4G4Wi22jV)yR118ecxZlNWlbybGGSV2o5TW(FnV3NTUVRSCO4XxzoMsMLDk9wGzu6xz1qJWDkvANU)pH7NY5(SbgTjmelIz2GKHfekkfAmRFN)DtMJphb(ILtfZxazYyoWsk3GBVaffpQIz3)xf(oN)(GayrNRLOt8WNH(N2t)txWNEjhWLZwB9)4S1IiKDiHI5LfkpvmRSqzOJQA9vXzh6FigY2N6BR2gWvjr0n37Jvw31cvl5HHq9wat130FnBHIyspcqyilMj5(K5I1dIXknI1nJwt3aHOuSpdbfoWhjGnnD2mRg9Xo9g29XE5(dWRQtnmWwXWESq)yrMPzLlwOlDQz3Hs2m(REeYWo9ajKXr7S(PBNmCxC5ksclkQKvqSxHwSVOWv6txA6vlz0iYUf67wPUZnvYo2I0z(4(GSbdWTnwwbDIawgQtV0Ujz8lKXnhbUPyG9c8COJkxShC0iLXfC0QZ4uphx2O4FAW0RyyNVn2jkwXgBL2dIaGH34yodLM7VyZD5rXPySrbrajIDMIDnSEqWt7ZTDCRL1XnBgO8E3iWmEgp0ALifU4GvDJOHGQo4XX9UVFhpYCMj9SFTAzizlQc)Z18SQ5zn8jiNib1mWg61sy6PuT2cVXfqiIzQa)iQYoVehRx7r(uZr9g0(3GANPW8xgvkZ1BjfJ4cGWXNHcCYbtmbhj8yc0q(sS29cRxqf674UNe8Jw7pHvS5CFRzyoSICDKCd4aAYhwzZjhzYQK9N6jwr2z8ihpLz2rkpHqjmj5jlcAIuKMC86WoR5b652qxwvkNSiDHPVmF3gI8qxRLM8X77tU)Uo2HUT58tt1Ar8ai6bfeYGtTlagQu(wxN6nUPH711Qx52BmyJtxS65wmh5Kj0ZOhVEY48DLqsK5baDYNO(DdfRzYTtAAiblrGJRAnaowHm3u)(R3a05htkKeLD7KAfUWYX5vfmKHujAVzXcie9HcIYJ0JpLzt33obydko2kaBMgn7GB10Rtxab8fbCrG(vYkdx8gtEK7esUA4qWBa8)jQeMRBb4UMnlI7Bfp0qNKUCj(6Du5IWiqZY0LdolaHIko0yHQP2UG7nhRhN0PxN2J7oQ5dD2FJj82ufGEPOIe(hYvDF81BACZdiwgWyktMMjK1YIcB)Tl8GJwWZVhMTTN)CM)II9)q4)kQKJkaEwkS0VphC(JyW9TK(qnFIacKV)9iHrPSCHphMRKTxY29Azk3MWKqYEXYWAud3rvgsdxR713646wPrTkqR6AnQuZB2BQ3aTKUnU2XXTwJ6vQwVQB9ko4o12BD7phBnyBcU9y(gMPioV)63zBQBJ6nU926x7uPAT634u1ntNDV4ovV4ox2obMo2v(VlPTYHNtHAz686M5Wv71VxHzYUO659xp

**Comment by InfusOnWoW** [comment]
I tried reproducing this a few times and couldn't.

The setup looks pretty normal and I suspect many people use a very similar setup conditions setup, yet this is the first time that we hear about a issue with deaths.

There isn't really any code that should affect this aura when you die, so I have no idea how this can happen.

When you encounter this bug again, please note down the exact circumstances in which it occured. Screeenshots or even a Video of it appearing would be ideal. 

Just comment on the  bug report, and we'll take another look at it.
