### ISSUE TITLE
Anchor settings not updating when an Aura drops out of a Dynamic Group.

### ISSUE THREAD

**Issue by asakawa-k** [WeakAuras/WeakAuras2#988]
If an Aura is in a D.Group then it has no anchor settings in its Display tab. 
While viewing the Display tab if you use the ◄ (left arrow) to drop the Aura out of the group, no Anchor options appear. They do show if you deselect and reselect the Aura. (As such this is minor but thought I'd make a quick ticket while I remembered)

To replicate:    
Make a D.Group    
Make an Icon in the group    
Drop the icon out of the group    
(see settings)    
Deselect the Icon    
Reselect the Icon     
(see settings)

**Comment by InfusOnWoW** [comment]
This is annoyingly complex to fix, because it's also broken for drag and drop.

**Comment by emptyrivers** [comment]
This bug ticket has been open for more than a year now. Does it still occur, and if so, are we going to fix it eventually?

**Comment by InfusOnWoW** [comment]
Yeah, it's unfixed. It's still on my todo list.
